### ISSUE TITLE
AppModules fixes

### ISSUE THREAD

**Issue by IgorMinar** [angular/angular#10006]
Meta issue for various small issues found in AppModules code

- [x] `browserDynamicPlatform` is being imported from  `platform-browser-dynamic` package - this seems inconsistent
-  [x] `browserDynamicPlatform` and `browserPlatform` are factories but the name doesn't indicate that. we should prefix these with `create` or `get` or suffix them with `factory`. `get` is likely the best since the platformRef is internally cached
- [ ] remove waiting for app initializers from `bootstrapModule`
- [ ] `lockRunMode` is now deprecated but `enableProdMode` is not and we still print the instructions to call it during bootstrap
- [ ] router seems to be [hardcoded](https://github.com/angular/angular/blob/72544ba55113a652b2452f2ce5bb0fca576a1344/modules/%40angular/router/src/router_module.ts#L40) to always use `SystemJsAppModuleLoader` which depends on the `RuntimeCompiler` - can we merge the `SystemJsAppModuleLoader` and `SystemJsAppModuleFactoryLoader` into one and dynamically switch the behavior depending on if the `RuntimeCompiler` is present.
- [ ] add ability to add AppModules via UpgradeAdapter

**Comment by tbosch** [comment]
Re name of `browserDynamicPlatform`:
- what should this be instead? We already had `browserPlatform`, so probably `dynamicBrowserPlatform` then? 
- I chose the name based on the already existing`BROWSER_DYNAMIC_PLATFORM_PROVIDERS`. So we should rename this accordingly.

Re `browserDynamicPlatform` and `browserPlatform` being factories:
- as you said they also have a cache. I.e. this is more like a lazy getter then a factory.
- I would vote for not adding `get` before it as this is inline with e.g. jQuery style getters which users are used to.

Re remove not waiting for async initializers:
- this would mean deprecating them, i.e. logging a warning when they are used and eventually not waiting at all, right?
- `bootstrapModule` would still stay async as it calls the runtime compiler

Re `lockRunMode` vs `enableProdMode`
- `isDevMode`/`enableProdMode` is still being used to switch between some implementation details (e.g. whether to use the `DebugDomRenderer` or not. I proposed to remove it and use the `useDebugMode` flag from the compiler instead, but the change would have taken at least 2-3 days, and we can still make `enableProdMode` do nothing after final.
- The idea of `lockRunMode` as that `isDevMode` always returns the same value. However, for this purpose, it is simpler to make `isDevMode` lock the run mode on first call automatically (see the current implementation). I.e. right now, `lockRunMode` is empty and therefore deprecated, but `enableProdMode` still servers the purpose of switching the run mode.

Re the router and `SystemJsAppModuleLoader`:
- `SystemJsAppModuleLoader` only depends on the abstract class `Compiler`, which is in `@angular/core` and allows users to access the Runtime compiler if the application was created with the runtime compiler and throws otherwise. This is in line with other changes to make all of `@angular/compiler` a private api and provide tokens in `@angular/core` to allow users to use the runtime compiler if loaded (see e.g. `TestComponenBuilder`).
- The router only uses this provider as the default.
- +1 on merging the 2 loaders into one. Then maybe add a getter `isEnabled()` to the `Compiler` abstract class to determine whether the runtime compiler is available.

Re upgrade adapter and modules
- +1 on this. 
- See the declaration of `DynamicModule` in [`UpgradeAdapter.bootstrap`](https://github.com/angular/angular/blob/master/modules/%40angular/upgrade/src/upgrade_adapter.ts#L292). Add the additional modules to the array in the `@AppModule` annotation.

**Comment by IgorMinar** [comment]
all of this got resolved in rc5
