### ISSUE TITLE
Forms: controls using async validators remain in invalid state even after the validators have resolved to null.

### ISSUE THREAD

**Issue by nosachamos** [angular/angular#10009]
**I'm submitting a ...**
```
[X] bug report
[ ] feature request
```

**Current behavior**
When async validators don't cause the valid state of the form control being validated to turn `true` when they resolve to `null` indicating that the value is valid. 

**Expected/desired behavior**
When an async validator resolves to `null`, and no other validators have returned error objects, the control's `valid` status should turn `true`.

**Reproduction of the problem**
The issue is reproed here:

http://plnkr.co/edit/HcQ7ZLRRHm63242ILA5W?p=preview

Enter a valid email, and notice in the console log outputs that the promise resolves to null, but the valid state of the email field never becomes true, even though the control's error object has no items. Same for the `statusChanges` observable, which is not updated to VALID once the there are no errors reported by the validators.

**What is the motivation / use case for changing the behavior?**
Async validators are very common (checking username availability, etc), so this should work.

**Please tell us about your environment:**

* **Angular version:** 2.0.0-rc.4

**Comment by chinds87** [comment]
Your validator isn't async. You need to use NG_ASYNC_VALIDATORS instead of NG_VALIDATORS. Since your using NG_VALIDATORS, the validation actually error's out because it doesn't know how to handle the promise. 

On the flips-side if your returning an async validator, you have to return a promise. 
You can't just return null like the non-async validator. Hopefully this save somebody a ton of time.

**Comment by nosachamos** [comment]
@chinds87 Yes, good catch! The NG_ASYNC_VALIDATORS did the trick:

http://plnkr.co/edit/DRjZkU59RiF06JLNfciO?p=preview

This can be closed.

**Comment by kara** [comment]
Thanks, @chinds87. Closing.
