### ISSUE TITLE
feature(forms): FormGroup updateValue should not throw error for missing control

### ISSUE THREAD

**Issue by mmrath** [angular/angular#10057]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report
[x] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
Look like updateValue on FormGroup iterates through all the elements and tries to set value of for each corresponding control. However if control is not found it throws an error. In some scenarios we get more data than required from backend, in which case the server return data will have some extra attributes which are not relevant for a form, e.g. created_by, modified_by audit fields.

**Expected/desired behavior**
I am proposing to have a optional boolean parameter(with a default?) to updateValue, depending on the parameter value, exception will be thrown or not for updating value.

**Reproduction of the problem**
NA

**What is the expected behavior?**

**What is the motivation / use case for changing the behavior?**
We use the same model in the backend for lists and forms. The value for lists like createdBy, modifiedBy is not required in the form.

**Please tell us about your environment:**

* **Angular version:** 2.0.0-rc.X
 
* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ] 
 
* **Language:** [all | TypeScript X.X | ES6/7 | ES5 | Dart]

**Comment by choeller** [comment]
In our case the problem occurs for every form, as we are loading from a database and each entity has an id-property, causing updateValue to crash, so it would be cool to have unknown values be ignored...

**Comment by DzmitryShylovich** [comment]
Just create a FormControl for id but doesn't show it on the form.

**Comment by choeller** [comment]
yeah, that's what I'm doing right now, but that's quite ugly...

**Comment by qdouble** [comment]
This is also problematic because if you add more fields to your database document, it can cause your app to unexpectedly crash if it returns additional properties without you checking for it.

**Comment by kara** [comment]
Thanks for bringing this up.   This is definitely a common use case we'd like to support.  Let me clarify how we thought about it.

To our thinking, the best practice when retrieving an object from the server is always to transform it to match the structure of the form.    This is an anticorruption layer that keeps you safe from changes in the object you receive.  In other words, you'd write a function that would take you from objectA (suited for server) to objectB (suited for client).   Then you'd pass the object with the correct structure to updateValue().

updateValue() accepts a collection of control names as keys and sets the value of the form.  If we require that control names be valid, it's possible to provide checks for you in the case that you pass in an object with incorrect nesting or you try to update the value before the control has been registered with the form (this is especially a concern for template-driven forms). On the other hand, if we choose to ignore unrecognized inputs, these types of checks aren't possible and the form will just fail silently if something actually goes wrong. 

That said, it's understandable for developer ergonomics that you might want to skip the extra step and pass your response object directly to the form.  It's up to the developer whether he/she wants to optimize for convenience or safety.

With that in mind, we are splitting updateValue into two functions (PR coming soon):

**setValue**():  this works much like updateValue() does now. The value passed must exactly match the structure of the form, and it will throw an error if it receives a superset or a subset of the form.  This is what we'd recommend using in most cases since it will not fail silently.

**patchValue**(): this is a more forgiving function that will do its best to match controls based on the list it is passed.  It will not throw for unrecognized control names, so supersets and subsets will both work.  This is what you'd use if you want to include extra properties like created_by.

updateValue() will be deprecated. Note that this is only happening for the updateValue that existed in RC.4, as FormGroup/FormArray updateValue() was never released.
