### ISSUE TITLE
Enum in template binding causes error

### ISSUE THREAD

**Issue by rasmk** [angular/angular#10063]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report
```

**Current behavior**
I am trying to use an enum in the template:
```
export enum Panel {
    left,
    right
}
...
<div id="rightPanel" [ngClass]="{inactive: activePanel !== Panel.right}">
```

I get _Cannot read property 'right' of undefined._

**What is the expected behavior?**
As Angular promotes TypeScript as a primary impelmentation language, I would expect the legal TS construct to be supported.

**Angular version:**
2.0.0-rc.4

**Language:**
TypeScript

**Comment by pe8ter** [comment]
Templates bind to component instances. Panel doesn't exist inside your component.

**Comment by rasmk** [comment]
@pe8ter I understand that. And the workaround is simple. Still I would expect a full support for TypeScript. I can use enums all around the model and when bringing them to the template, I have to convert. This does not feel right.

**Comment by pe8ter** [comment]
See the docs on [template expressions](https://angular.io/docs/ts/latest/guide/template-syntax.html#!#template-expressions). There's a litany of reasons why templates only support a subset of JavaScript.

As for templates only binding to component instances, this makes sense when you see how the HTML gets compiled into regular JavaScript modules. They are code modules external to your component module which is why they can't bind to arbitrarily defined symbols like your enum.

**Comment by rasmk** [comment]
Thanks for the link @pe8ter. Since it's by design, I am closing the issue. I am not happy with it though.
