### ISSUE TITLE
bug(forms): Can't have radio inputs with same formControlName in form and nested form

### ISSUE THREAD

**Issue by vagarenko** [angular/angular#10065]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
Consider this component: 

```
@Component({
  selector: 'my-app',
  providers: [],
  template: `
    <div [formGroup]="form1">
      <input type="radio" formControlName="control" value="0"/>
      <input type="radio" formControlName="control" value="1" />
      <div formGroupName="form2">
        <input type="radio" formControlName="control" value="0"/>
        <input type="radio" formControlName="control" value="1" />
      </div>
    </div>
    {{form1.value | json}}
  `,
  directives: [REACTIVE_FORM_DIRECTIVES]
})
export class App {
  constructor(){
    this.form1 = new FormGroup({
      control: new FormControl('');
      form2: new FormGroup({
        control: new FormControl('');
      })
    });
  }
}
```
I have 2 radio inputs bound to FormControl named `control` in `form1` and another 2 in nested `form2` bound to different FormControl with the same name.
When I click on one of inputs in the first pair the corresponding input in the second pair is also checked. 
See plunker: http://plnkr.co/edit/fB9UO8LbKpXIfqYOuZCO?p=preview

Possible cause: 
https://github.com/angular/angular/blob/master/modules/%40angular/forms/src/directives/radio_control_value_accessor.ts#L57

```
    return controlPair[0].control.root === accessor._control.control.root &&
```

this checks if controls belong to the same root, but, perhaps, it should check if they belong to the same parent.

**Comment by chrisfoster78** [comment]
+1 - I was just about to raise the same bug.

https://plnkr.co/edit/9VtAIapMBiwpai5VBFoW?p=preview

**Comment by linusbrolin** [comment]
Same here, and it's causing big problems for me.
Is there any way to get around this bug for now?

**Comment by jwagon** [comment]
This bug has other serious effects as well. Let's say you have a form with two control/form groups, and each of these contain a radio group. The markup might be something like this (I'm using the deprecated forms syntax on RC4, but it should be the same issue with the new syntax in RC4 or RC5):

```html
<div [ngControlGroup]="food">
  <input type="radio" name="food" [ngControl]="tomato">
  <input type="radio" name="food" [ngControl]="bacon">
</div>
<div [ngControlGroup]="drink">
  <input type="radio" name="drink" [ngControl]="vodka">
  <input type="radio" name="drink" [ngControl]="beer">
</div>
```

And some JS like:

```javascript
let theForm = new ControlGroup({});

let foodGroup = new ControlGroup({});
foodGroup.addControl('tomato', new Control());
foodGroup.addControl('bacon', new Control());

let drinkGroup = new ControlGroup({});
drinkGroup.addControl('vodka', new Control());
drinkGroup addControl('beer', new Control());

theForm.addControl('drinkGroup');
theForm.addControl('foodGroup');
```

The let's say you click first on 'vodka', then on 'bacon'. Because of the line cited above by @vagarenko  from function **RadioControlRegistry._isSameGroup()** . . . 

```javascript
return controlPair[0].control.root === accessor._control.control.root && 
  controlPair[1].name === accessor.name;
```

. . . this function is returning true for **every** radio button in the form(!), because the 'root' value is the form's control group, not the radio button's control group. I thought maybe the second part of that conditional after the '&&' might be where you're determining if it's the same radio group or not, but every time I stepped through this code, both **controlPair[1].name** and **accessor.name** are always undefined (there's not even a 'name' key in either **controlPair[1]** or **accessor**), and in any case seem to always be radio button controls, not their control groups, so even if these values were defined, I don't think it would obviate this bug report; in fact, I think it might create the opposite problem, where no radio buttons are ever determined to be in the same group, except the button that was actually clicked, which is also incorrect.

So the ultimate effects of this are (at least) that **RadioControlValueAccessor.fireUncheck()** is fired for every radio button in a form except the one clicked, which corrupts the data within the form ControlGroup structure by setting their checked values to false. Also, it marks every other radio control group and every radio button control as pristine = false, which is also incorrect and problematic. 

In my specific example (click on 'vodka', then 'bacon'), the form value reports that bacon is checked, but that vodka is not.

So I agree with the OP; the condition seems like it should be:

```javascript
return controlPair[0].control._parent === accessor._control.control._parent && 
  controlPair[1].name === accessor.name;
```

In my brief testing, this fix does work for the case I described, but I don't know if that would break something else, or what the intention of this line really is. And honestly, I'm not even 100% sure I'm using FormBuilder correctly.

Fortunately in my case I'm not observing the OP's observed behavior, where the bogus unchecking or checking is reflected in the DOM as well, so my workaround for now is to rely on the DOM when it comes to forms with multiple radio groups, but obviously this isn't ideal.

**Comment by miguelleite** [comment]
I'm still facing this issue on **v6.0.9**. Anyone else?

**Comment by k1462015** [comment]
> I'm still facing this issue on **v6.0.9**. Anyone else?

Hey @miguelleite, 

If you're using the `[formControl]` directive on a `<input type="radio" />`, you need to specify a `name` attribute as well.

```
<div>
          <input type="radio"
            [name]="uniqueName1234"
            [formControl]="yourFormControl" [value]="1234"/>
</div>
<div>
          <input type="radio"
            [name]="uniqueName5678"
            [formControl]="yourFormControl" [value]="1234"/>
</div>
```

The name property needs to be unique between your radio button groups
