### ISSUE TITLE
Why are shim.min.js/zone.js/reflect.js loaded traditionally?

### ISSUE THREAD

**Issue by SetTrend** [angular/angular#10072]
**I'm submitting a ...**  (check one with "x")

- [ ] bug report
- [X] feature request
- [ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question

---
@ https://angular.io/docs/ts/latest/quickstart.html#!#index shim.min.js, zone.js and reflect.js are loaded traditionally from within the HTML file.

Why aren't they automatically being imported by `@angular/core` or `@angular/platform-browser-dynamic` if they are required anyway?

CC: https://github.com/angular/angular.io/issues/1886

**Comment by pkozlowski-opensource** [comment]
See https://github.com/angular/zone.js/issues/365#issuecomment-232067827

**Comment by SetTrend** [comment]
@pkozlowski-opensource : OK, so why is it required to load *any* of these files traditionally, incl. `System.js`? If `System.js` would be loaded by Angular by default, `zone.js` could be loaded by default as well as any of the other dependencies.

Advanced programmers could then override these defaults in some Angular.json configuration file.

But for 99 % of all programmers it would be feasible and sufficient to just load `angular.js`.

**Comment by SetTrend** [comment]
@pkozlowski-opensource : I would very much like to have this issue kept open so other readers in the Open Source can share their opinion on it.

**Comment by red-0ne** [comment]
> If System.js would be loaded by Angular by default, zone.js could be loaded by default as well as any of the other dependencies.

System.js is not loaded by default, bundling your app (using webpack) is an alternative to System.js which could also suit your (single angular2.js file) needs

**Comment by SetTrend** [comment]
Absolutely. I'm writing `System.js` here just as a placeholder for any loader system you might feel appropriate for using from within Angular.2.

**Comment by pkozlowski-opensource** [comment]
@SetTrend what you are asking here is a "I'm containing all" bundle approach as in AngularJS 1.x. The thing is that trends / tools / approaches changed. There are many ways of bundling / loading and we can't force users to one particular path.

On top of this different browsers will need different polyffils so we can't just bundle those.

 >  I would very much like to have this issue kept open so other readers in the Open Source can share their opinion on it.

Feel free to continue the discussion but at present there is nothing actionable for us here so no reason to keep the issue open.

**Comment by SetTrend** [comment]
@pkozlowski-opensource : It's not about "forcing"... It's about providing a simple default approach for [RAD](https://en.wikipedia.org/wiki/Rapid_application_development).

All the polyfills required can be loaded dynamically internally from within the Angular.2 code. There's nothing keeping Angular.2 from detecting the environment and loading appropriate polyfills or loaders online. And, thus, trends can potentially always be followed by creating and publishing a new Angular.2 release.

If a programmer would not be satisfied with the defaults provided by Angular.2, (s)he could use a (future) configuration file (e.g. "angular.json") to opt in for external loaders, polyfills or anything else. That's all.

**Comment by connelhooley** [comment]
I can see why System.JS is not required by default as it's not part of Angular and can be swapped out for alternatives.

But why are core-js and zone.js not included by default? Is there a stable browser released that can run Angular without the core-js shim? I'm mostly confused why I should care what zone.js is, especially since it's written by the Angular team and seems like an implementation detail?

If someone was to raise a bug - and they're not using either of those packages - are there any situations where the Angular team would want the bug to be reproduced using them? If so they should be included as dependencies in my opinion.

**Comment by MarkPieszak** [comment]
@SetTrend @connelhooley  I think Igor's comment that Pawel pointed out ([here](https://github.com/angular/zone.js/issues/365#issuecomment-232067827))

> previous comment was importing them in the code:
```
import 'reflect-metadata';
import 'zone.js';
// then his angular application (same file)
```

> Igor:  you should not import zone.js from your application like this. If you do, you are loading the prolyfill too late which means that part of your environment (module loader) won't be under the oversight of zone.js - things might seem to work for a while but sooner or later you'll run into issues when updates to the ui stop happening and you won't know why.
> 
> For this reason it's better to always include all polyfills before any module loader (systemjs) or application code. This is why we recommend loading zones as the first script in index.html.

This sums up why we need the user to manually insert them prior to Angular themselves.  It can't simply be "included" inside of Angular because it needs to be polyfill'ed in the browser *prior* to Angular even being part of the picture. (Since zones wraps itself around xhr / timeouts / browser events). Angular then hooks into this entire Zone system, to do its own changedetection / etc.

This of course is just how things work *if* you're using SystemJS.

If you want an alternative, I'd suggest using Webpack instead.
If you look at vendor.browser.ts & polyfills.browser.ts ([here - angular2 webpack starter](https://github.com/AngularClass/angular2-webpack-starter/tree/master/src)). You will see that Zone / reflect, are all included in those files, and the `index.html` has none of these things in there.

Webpack is then told to bundle those files & inject them into the index page in a specific order (just like we manually do in SystemJS), so the same thing happens just in a different way. And everything works as it should.

So you see, either way you need to do the same thing, there's just many different ways of achieving it.

**Comment by connelhooley** [comment]
Ah ok, that makes a lot more sense. Thanks for explaining! I didn't see the comment @SetTrend linked above.

**Comment by SetTrend** [comment]
Sure, I understand the reasoning for the current model.

But what is keeping Angular.2 from doing all this from inside Angular code itself?

Instead of starting right off with angular code which requires all these prerequisites:
![angular1](https://cloud.githubusercontent.com/assets/9283914/16870617/bf60353c-4a82-11e6-8a3d-7cca2957be72.png)

Why doesn't Angular2 start off with a loader that's doing nothing else than loading all these frameworks just normally - and then booting itself? Like this:
![angular2](https://cloud.githubusercontent.com/assets/9283914/16870619/c364b66c-4a82-11e6-9fc7-f35a2e77be27.png)

**Comment by SetTrend** [comment]
The loader code would basically look like this:
![angular loader flussdiagramm](https://cloud.githubusercontent.com/assets/9283914/16871687/a195338a-4a88-11e6-930e-9184b9d692da.png)

----

`Angular.config.json` might be similar to this:
```json
{ "environment":
  { "node":
    { "prerequisites":
      [ "@Angular/Zone.js"
      , "@Angular/Reflect.js"
      ]
    }
  , "web":
    { "prerequisites":
      [ "@Angular/Shim.js"
      , "@Angular/Zone.js"
      , "@Angular/Reflect.js"
      , "@Angular/System.js"
      ]
    }
  }
}
```
(I'm just making up some entries here without any deeper knowledge. Don't take these configuration entries literally.)
