### ISSUE TITLE
Router: cannot navigate away from aux route after a page refresh

### ISSUE THREAD

**Issue by fknop** [angular/angular#10071]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**

When we navigate to a aux route and refresh the page. When we want to navigate to siblings component and get rid of the aux route, it does not work and the aux route stays. 

When we do not refresh the page, everything works as expected.

**Expected/desired behavior**

We expect that we navigate away from the aux route after a page refresh.

**Reproduction of the problem**
If the current behavior is a bug or you can illustrate your feature request better with an example, please provide the steps to reproduce and if possible a minimal demo of the problem via https://plnkr.co or similar (you can use this template as a starting point: http://plnkr.co/edit/tpl:AvJOMERrnz94ekVua0u5).

@brandonroberts and myself could not make it work on a plunker due to refresh problems. So we had to reproduce it locally. I've fork his repo here: https://github.com/fknop/plunk-DySxiwCiwwehiLfUAfPn

* Clone the repository
* npm install
* npm start
* Click on `LINKTOC`
* Click on `go to aux`
* You now see `AUX COMPONENT`
* To prove that it's working fine without refresh, click again on `LINKTOC`, you can see that the aux route is no more there.
* Click again on `go to aux`
* Now, refresh the page
* Click again on `LINKTOC` or `LINKTOB`
* You can see the aux route is still there

@brandonroberts said on Gitter that if we changed the `id` (`a/2/b`) or if we go to `a/1`, it would work.

**Please tell us about your environment:**

* **Angular version:** 2.0.0-rc.4 and Router beta.2
 
* **Browser:** [Chrome 51] 
 
* **Language:** [TypeScript]

**Comment by vsavkin** [comment]
There are two ways to do navigation using the router.

## Navigate by URL.
 
`router.navigateByUrl` takes the provided URL and navigates to it.

## Navigate using a delta

`router.navigate` and `routerLink` always take a delta and apply it to the current URL. And then they navigate to the result URL. So the correct behavior is to always preserve the aux route. The fact that it is not the case in your repo is a bug and it has been fixed in master. That's fixed in master.

To clear the aux route, you need to do one of the following:

```
router.navigate(['/a/1', {outlets: {primary: 'c', aux: null}}]);
<a routerLink="['/a/1', {outlets: {primary: 'c', aux: null}}]">c</a>
```

This works in master.

I updated the api docs to make it it clearer.

Closing this issue.
