### ISSUE TITLE
DatePipe tranform adds extra unicode characters in Edge

### ISSUE THREAD

**Issue by mithun-daa** [angular/angular#10080]
**I'm submitting a ...**  (check one with "x")
```
[x ] bug report
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
If the`DatePipe` is used programatically to transform a date, a unicode character (_\u200E_)) gets added to delimit/escape `/`

**Expected/desired behavior**
These extra characters should not be added

**Reproduction of the problem**
If you try the following plnk in MS Edge you can see the issue. Works fine on all the other browsers:
http://plnkr.co/edit/8upv8WAhL85cIbmv7xDQ?p=preview

**What is the expected behavior?**
No extra unicode characters should be added or the extra unicode characters should be replaced with empty characters as demonstrated in the plnk.

**What is the motivation / use case for changing the behavior?**
It's a bug

**Please tell us about your environment:**
Win 10, Edge

* **Angular version:** 2.0.0-rc.4
 
* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | Edge
 
* **Language:** [ TypeScript 1.8 | ES6/7 | ES5]

**Comment by mithun-daa** [comment]
No, it does not. I was chatting with the guys on the Chakra gitter channel and they think it might be their internationalization API.

**Comment by laskoviymishka** [comment]
Yeah, theirs implementation of internationalization api really weird, and not even allow to pollyphil with different implementations, maybe it worth to reproduce it separately it file them a bug, most probably one of single components add redundant utf char. I bet on year component

**Comment by jdalton** [comment]
@bterlson Is there guidance on how libs handle the left-to-right and right-to-left marks in `Date#toLocaleDateString`. Is this the only place the marks are added?

**Comment by jdalton** [comment]
Scratch that :P

**Comment by jdalton** [comment]
I dig that Edge handles the bidi control characters in its Intl and locale APIs. It fits with the spirit of the API. That said for enviro consistency it should be stripped from the results here so I can cook up a PR to tackle that.

**Comment by bterlson** [comment]
This doesn't seem to be a bug based on the documentation which states (mostly correctly), "In javascript, only the components specified will be respected (not the ordering, punctuations, ...) and details of the formatting will be dependent on the locale." Pedantically, not even the components you specify must be supported by the Internationalization APIs (eg. imagine a constrained hardware device that maybe only has a few date formats available). Regardless, it is never a good idea to be sensitive to the exact byte-for-byte contents of strings returned from the Intl APIs because there is no guarantee it will be the same across runtimes and platforms (or even from day-to-day as the underlying locale data gets updated).

Here's the Chakra bug if you'd like to give feedback on this: https://github.com/Microsoft/ChakraCore/issues/599.
