### ISSUE TITLE
Skip Dart tests + issue a warning when Dart environment is not setup

### ISSUE THREAD

**Issue by IgorMinar** [angular/angular#1012]
Currently we skip all the dart related tasks when building Angular if Dart environment is not setup. We should do the same for tests.

The justification for this is that if someone not familiar with Dart wants to contribute a small fix, asking them to setup Dart environment is a not reasonable.

**Comment by chalin** [comment]
Blocked by #945, *JS tests (test.unit.js/ci) use Dartium under CLI and Travis rather than Chrome*. If someone on the Angular team can confirm that use of *Dartium* for JS tests was a mistake, then please respond to #945 so I can fix it. Then addressing this issue will be mostly done.

The source of the problem currently is that `scripts/ci/test_unit_js.sh` makes use of Dartium, hence it invokes the Dart environment variable setup which will exit with error if there is no Dart env.
