### ISSUE TITLE
What's about actual for multiple statements?

### ISSUE THREAD

**Issue by armorik83** [angular/angular#1016]
https://github.com/angular/angular/blame/e0710c4613ba51f008bc8a2f4874fb1fade9d09f/modules/angular2/docs/core/01_templates.md#L620

> Multiple statements OK: Statements can be composed from more than one statement. (i.e. no doA(); doB())

As a matter of fact, does Angular allow multiple statements? What does mean "i.e. no doA(); doB()"?

**Comment by pkozlowski-opensource** [comment]
@armorik83 It does and does not depending on the context :-) As described in https://github.com/angular/angular/blob/master/modules/angular2/docs/core/01_templates.md you _can_ use them in event handlers but _not_ in binding expressions. For example `<div [id]='foo' (click)='doFoo(); doBar()' >` is perfectly fine but doing `[id]='foo; bar'` would be an error.

This makes perfect sense since binding expressions need to return a value (one to be used for the binding) and it wouldn't be clear which returned value should be taken into account (first, fast, all of them???). On the other hand we don't care about event handlers return values, only about it side effects.

Hope this clarifies, if you believe that docs could be improved than PRs are more than welcomed!

**Comment by armorik83** [comment]
I see, thank you!
