### ISSUE TITLE
Validation on unbound form element not working in RC4

### ISSUE THREAD

**Issue by achimha** [angular/angular#10200]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
Validation rules do not trigger on form element without `ngModel`

**Expected/desired behavior**
Validation should work without binding the element.

**Reproduction of the problem**
https://plnkr.co/edit/T7YwMiMOnsW5wEkrjzJ1?p=preview

The `passwordrepeat` form element is configured with the `Validators.required` rule. With the code in the plunk above, it never becomes valid. As soon as I add `[(ngModel)]="passwordrepeat"` to it, it works as expected.

**What is the expected behavior?**

Validation should not require the form element to be bound. It worked with RC2.

**What is the motivation / use case for changing the behavior?**

I do not need the value of the field so I don't think I should have to bind it.

**Please tell us about your environment:**

* **Angular version:** 2.0.0-rc.4
 
* **Browser:** [all] 
 
* **Language:** [TypeScript 1.8]

**Comment by LunicLynx** [comment]
I guess 
`<input name="password" type="password" class="form-control" placeholder="Password" />`
and
`<input name="passwordrepeat" type="password" class="form-control" placeholder="Password repeat" />`
should be
`<input name="password" formControlName="password"  type="password" class="form-control" placeholder="Password" />`
and
`<input name="passwordrepeat" formControlName="passwordrepeat" type="password" class="form-control" placeholder="Password repeat" />`
respectively.

**Comment by achimha** [comment]
My understanding from the new forms API docs was that `formControlName` is required when `name` is not present on the control. If `name` is present, it is used instead which you can see from the fact that the `FormBuilder` in the plunk is created successfully, referencing the controls bei their `name`.

However, you are right that if I change `name` to `formControlName` for the `passwordrepeat` input field, the problem does not occur. This means I have to either bind the input field or use `formControlName` instead (or in addition to) `name`. Given that this was not required with RC2 and my understanding of the documentation, I still believe this to be a bug.

**Comment by LunicLynx** [comment]
@achimha to which part of the documentation are you referring to? As far as i can see a the moment you only have the choice between: `ngModel` AND `name` OR `formControlName`. But maybe i am missing something too.

**Comment by achimha** [comment]
I was referring to https://docs.google.com/document/u/1/d/1RIezQqE4aEhBRmArIAS1mRIZtWFf6JxN_7B4meyWK0Y/pub but can't find anything confirming my understanding now.

So in order to get change detection which is require for validation, `ngModel` or `formControlName` need to be present? In order to create it with the `FormBuilder`, `name` is sufficient? This is what caused the confusion -- `FormBuilder` accepts to build the control and takes the validators but then it doesn't work.

Are you sure this is "working as designed" and the design is adequate?

**Comment by LunicLynx** [comment]
From what i understand so far, this is working as intended. The name `FormBuilder` is a bit confusing because it does actually neither create a real form nor real controls (input elements). It builds a form model, which can be seen as a viewmodel for a form. This model tracks changes and executes validation etc.
After you created this model you can link it to your input elements, by either using the directive `ngModel` with `name` or `formControlName`.

You should check the docs about Dynamic Forms this shows a lot of this stuff in action.
https://angular.io/docs/ts/latest/cookbook/dynamic-form.html

But still, i don't belong to the angular team, all i know is only what i figured out my self by reading the docs and the source code. So an official statement would probably be good.

**Comment by achimha** [comment]
I've created a plunk for this issue: https://plnkr.co/edit/w2FTQXokpnqYROoxb9MH?p=preview

The binding only works when `formControlName` is set. It does not work with `[(ngModel)]="property" name="property"`. This is different behavior from previous RCs.

Could somebody from the forms team comment please?

**Comment by LunicLynx** [comment]
You are mixing Template and Reactive driven concepts here.
You can either build your own form model (FormGroup, FormControl) or use ngModel as this plunker shows:
https://plnkr.co/edit/vu4k3fC8t9WSKx4QU7m5?p=preview

But i think the team should probably reconsider using completely different names for the two concepts. But they are maybe already working on that:
https://github.com/angular/angular/blob/master/modules/%40angular/forms/src/directives/reactive_directives/form_control_name.ts#L64

I guess the rule of thumb is: If you use your own form model, you must also use the reactive directives for every input.

**Comment by LunicLynx** [comment]
Well, on a second thought i think you are right that last example of yours should probably work even though i found and explanation why it isn't.

https://plnkr.co/edit/cmQyY1aXt7Nly8CNrQ8x?p=preview

**Comment by achimha** [comment]
Thanks for the information.

Given that I need validation, what are the available options to construct the form? I only know of `FormBuilder` and the only combination that seems to work with RC4 is to use `[(ngModel)]="firstname" formControlName="firstname"`. Are there others, more elegant methods? Also when I set `ngModel` but no `name/formControlName` I get an error but when I set `ngModel` and `name`, I don't get an error but the binding and validation have no effect. Very confusing!

**Comment by kara** [comment]
@achimha As @LunicLynx mentioned, it seems your code sample is mixing the two forms strategies (which won't work).  If you are using a reactive form strategy (e.g. the `formGroup` directive), you must link the form controls in the DOM to the FormGroup instance you created in the component class. The only way to do this is by adding a `formControlName` directive to the form control element in the DOM (the `name` attribute isn't used).  To initialize async data via something like HTTP, you have two choices: use an ngModel one-way binding in addition to `formControlName` (not recommended) or you can update the value imperatively using `updateValue`.  See an updated plunker [here](https://plnkr.co/edit/x4jPa1yocBJ2x8AoEkxU?p=preview).

On the other hand, if you want to use a template-driven strategy, you can use the `name` attribute with `ngModel`.  As this is "template driven", `ngModel` and its parent form tag create the FormGroup and FormControl instances for you, so there's no need to create your own in the class or to bind it to a formGroup directive.  If you do, the formGroup directive will overwrite the form you're creating with ngModel.   You'll just want a normal form tag.

That said, it should actually be throwing an error when the strategies are mixed rather than silently failing.  The missing exception is a TODO issue for me [here](https://github.com/angular/angular/issues/9554).   Sorry for all the confusion!

**Comment by LunicLynx** [comment]
@achimha to answer you last question. For the template driven approach you use the directives to define validation, like maxlength, minlength, pattern, required.
When using the reactive approach you need to add the validators to the form controls directly.
new FormControl('', Validators.required)

**Comment by achimha** [comment]
Thanks, this is a lot clearer now.

@LunicLynx so it is correct that custom Angular validators that go beyond the standard HTML `input` validators cannot be used with template driven forms, they can only be applied to reactive forms?

This on the other hand means that `ngModel` 2-way-binding cannot be combined with custom validators.

**Comment by LunicLynx** [comment]
Not exactly. You can always build custom directives to add custom validators to the form-model. Have a look at how angular does this for the required attribute.

https://github.com/angular/angular/blob/master/modules/%40angular/forms/src/directives/validators.ts#L58

Follow the provider chain:

```
providers: [REQUIRED_VALIDATOR]

const REQUIRED = /*@ts2dart_const*/ Validators.required;

export const REQUIRED_VALIDATOR: any = /*@ts2dart_const*/ /*@ts2dart_Provider*/ {
  provide: NG_VALIDATORS,
  useValue: REQUIRED,
  multi: true
};
```
