### ISSUE TITLE
Polymer element paper-listbox not working properly inside angular component

### ISSUE THREAD

**Issue by surenrao** [angular/angular#10214]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```
**Description**
polymer elements paper-dropdown-menu with paper-listbox is not rendering properly inside Angular 2

**Current behavior**
without clicking anything, it shows the options, and clicking the option hides it.

**Expected/desired behavior**
after clicking the paper-dropdown-menu element, a dropdown should popup and clicking an option should show selected value

**Reproduction of the problem**
https://embed.plnkr.co/pKksem60YSlzMlJzi9CD/
example shows rc.3, but its also reproducable in rc4

**Please tell us about your environment:**

* **Angular version:** 2.0.0-rc.4
 
* **Browser:** [Chrome Version 51.0.2704 ] 
 
* **Language:** [TypeScript | ES5]

**Comment by zoechi** [comment]
dup of #5531
You need to enable full shadow DOM and load full polyfills (not -lite). Angular doesn't yet support Polymers DOM API
See http://plnkr.co/edit/1Gx2G2utKwgnNFvf0I8c?p=preview for an example
The biggest limitations with using Polymer in Angular2 is 
- template elements can't be passed to Polymer because Angular2 doesn'add template elements to the DOM
- styling Polymer elements from parent Angular2 components is quite limited

**Comment by vicb** [comment]
Please note that you can also use https://github.com/angular/material2.

Closing as duplcitae (thanks @zoechi)
