### ISSUE TITLE
error to install angular Quickstart 

### ISSUE THREAD

**Issue by hmuschett** [angular/angular#10217]
npm install
npm WARN deprecated minimatch@2.0.10: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue

    angular2-quickstart@1.0.0 postinstall C:\Users\hmuschett\Desktop\testnode\angular
    typings install

typings ERR! message Unable to connect to "https://api.typings.org/entries/dt/node/tags/6.0.0%2B20160621231320"
typings ERR! caused by connect ECONNREFUSED 104.24.112.177:443

typings ERR! cwd C:\Users\hmuschett\Desktop\testnode\angular
typings ERR! system Windows_NT 6.1.7601
typings ERR! command "C:\Program Files\nodejs\node.exe" "C:\Users\hmuschett\Desktop\testnode\angular\node_modules\typings\dist\bin.js" "install"
typings ERR! node -v v6.2.1
typings ERR! typings -v 1.3.2
typings ERR! code EUNAVAILABLE

typings ERR! If you need help, you may report this error at:
typings ERR! https://github.com/typings/typings/issues

npm WARN optional Skipping failed optional dependency /chokidar/fsevents:
npm WARN notsup Not compatible with your operating system or architecture: fsevents@1.0.14
npm WARN angular2-quickstart@1.0.0 No description
npm WARN angular2-quickstart@1.0.0 No repository field.
npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\Program Files\nodejs\node.exe" "C:\Program Files\nodejs\node_modules\npm\bin\npm-cli.js" "install"
npm ERR! node v6.2.1
npm ERR! npm v3.9.3
npm ERR! code ELIFECYCLE
npm ERR! angular2-quickstart@1.0.0 postinstall: typings install
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the angular2-quickstart@1.0.0 postinstall script 'typings install'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the angular2-quickstart package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR! typings install
npm ERR! You can get information on how to open an issue for this project with:
npm ERR! npm bugs angular2-quickstart
npm ERR! Or if that isn't available, you can get their info via:
npm ERR! npm owner ls angular2-quickstart
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR! C:\Users\hmuschett\Desktop\testnode\angular\npm-debug.log

windows 7

* **Angular version:** 2.0.0-rc.X
 
* **Browser:**  Firefox47
* **Language:** [all | TypeScript X.

**Comment by vicb** [comment]
Looks like a connection error.

Anyway QS errors should be reported to https://github.com/angular/angular.io

Thanks

**Comment by girishjjain** [comment]
I've had same error and I found it to be an issue with corporate proxy. typings doesn't use proxy correctly when using command prompt. Using Git Bash with proxy variables set correctly resolved it for me.

**Comment by hmuschett** [comment]
@girishjjain how to proxy variables set correctly?? i use "npm set https-proxy=http://user:pass@proxy.cum:3128" and "npm set proxy=http://hmuschett:muschett.26.@proxy.gesei.cu:3128"

**Comment by girishjjain** [comment]
@hmuschett - I suppose you are using cmd on Windows? I got it working by using Git-Bash (any other bash should do) and by creating a .bashrc file in user directory (C:\Users\<username>). The .bashrc file content:

export http_proxy=<your-proxy-server>
export https_proxy=$http_proxy

Using bash it correctly uses the proxy and gets typings.

**Comment by taohannan** [comment]
my version is above from latest doc is 1.4 and stil throwing this error, i tried everyting above none is working

> angular-quickstart@1.0.0 postinstall C:\Users\00094201\workspace\angular-quickstart
> typings install

typings ERR! message Unable to connect to "https://api.typings.org/entries/dt/jasmine/tags/2.2.0%2B20160621224255"
typings ERR! caused by getaddrinfo EAI_AGAIN api.typings.org:443

typings ERR! cwd C:\Users\00094201\workspace\angular-quickstart
typings ERR! system Windows_NT 6.1.7601
typings ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\00094201\\workspace\\angular-quickstart\\node_modules\\typings\\dist\\bin.js" "install"
typings ERR! node -v v6.8.1
typings ERR! typings -v 1.4.0
typings ERR! code EUNAVAILABLE

typings ERR! If you need help, you may report this error at:
typings ERR!   <https://github.com/typings/typings/issues>

npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@^1.0.0 (node_modules\chokidar\node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.0.14: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})
npm WARN angular-quickstart@1.0.0 No description
npm WARN angular-quickstart@1.0.0 No repository field.
npm WARN angular-quickstart@1.0.0 No license field.
npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\00094201\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "install"
npm ERR! node v6.8.1
npm ERR! npm  v3.10.8
npm ERR! code ELIFECYCLE
npm ERR! angular-quickstart@1.0.0 postinstall: `typings install`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the angular-quickstart@1.0.0 postinstall script 'typings install'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the angular-quickstart package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     typings install
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs angular-quickstart
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls angular-quickstart
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\00094201\workspace\angular-quickstart\npm-debug.log
