### ISSUE TITLE
Are there any drawbacks for using the ng-upgrade on production?

### ISSUE THREAD

**Issue by HassanBK** [angular/angular#10265]
Hi, 
I read the following [article ](http://blog.thoughtram.io/angular/2015/10/24/upgrading-apps-to-angular-2-using-ngupgrade.html) and it claims that using ng-upgrade on production is not recommended.

> Keep in mind that the goal of this [upgrade] phase is to stay in it as little as possible, since running both frameworks on the same website is surely not ideal

I am planning to write an angluarJS 2 code along with existing angularJS 1.5 code. And there are no plans to refactor the code of angularJS 1.5 to angularJS 2. So I want to make sure that there are no issues for what I'm going to do. 
CC:@pbastowski 
Thanks.

**Comment by RoopeHakulinen** [comment]
Surely it is not ideal to run both, AngularJS and Angular 2 applications simultaneously. The obvious drawbacks are the performance hit and harder maintainability since you need to downgrade and/or upgrade stuff from one to another. This said, it is up to you to decide whether it is worth it or not. I personally prefer Angular 2 so much that would love to replace all my AngularJS apps with it. 

The ng-upgrade is meant to be used to while using the transition to Angular 2, not as end-solution for your application. It allows you to use the legacy code you have until you find the time to convert it to Angular 2.

**Comment by marcalj** [comment]
I'm using ngUpgrade in production and we just improves performance when using Angular 2 code.

I can't migrate all my code because there's a lack of UI plugins completely migrated to Angular 2, but it works faster if the components are migrated.

It's not perfect and it's improving on every RC, but I hope I can do the full migration soonish.

I'm not using ```ngc``` (angular compiler) yet, I'm waiting for RC5 hopefully for next week, this will improve even more the execution time, but I repeat, in dynamic mode it's faster than Angular 1. Probably not so fast at the bootstrap phase, but after that it's always faster.

**Comment by pbastowski** [comment]
@HassanBK
I had made a conscious decision late last year to not use Ng-upgrade on any project that will go to production for the following reasons:

- Ng1 and ng2 are each complex enough on their own and mixing the two in the same app seemed to be asking for trouble.
- I did not want to throw in an additional middle "broker" layer, Ng-upgrade, which would increase the overall complexity yet again.
- In our team we were happy to wait until ng2 would stabilize and only then develop new apps fully in either ng1 or ng2, as appropriate.  

Thus, I don't know how ng-upgrade performs or what drawbacks one might actually encounter when using it in production.

In my ng1 projects I always use my angular2-now library, because it makes my code easier and, I believe, cleaner. Although, I don't specifically try to make my code exactly like ng2.

**Comment by pkozlowski-opensource** [comment]
Sounds like an invitation for discussion / opinion request and as such doesn't belong here, see: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question

I'm going to close it but feel free to continue the discussion.
