### ISSUE TITLE
Backwards symbols in two-way data binding (eg. '([property])') should cause an error

### ISSUE THREAD

**Issue by KeatonTech** [angular/angular#10275]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report
[ X ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Behavior**

The two-way data binding sugar is an attribute formatted as '[(property)]', a combination of the property and event bindings. The other combination of property and event bindings, '([property])', does not work. This is probably by design, which is fine, however it would be nice if the template compiler could throw an error or warning when it comes across the latter format. I spent about 15 minutes trying to figure out why data binding didn't work before I consulted the cheat sheet and realized my mistake.

I can't think of any legitimate use case for '([property])' outside of two-way data binding, but I'm by no means an expert here.

**Please tell us about your environment:**

* **Angular version:** 2.0.0-rc.4
 
* **Browser:** Tested in Chrome 52, but probably affects all browsers
 
* **Language:** TypeScript 1.8

**Comment by ericmartinezr** [comment]
For reference https://github.com/angular/angular/issues/4737

**Comment by vicb** [comment]
That's a valid event name... Events if this is hardly used we can not throw. Probably a feature for linters / IDEs

**Comment by wolever** [comment]
It's true that `[foo]` is a valid event name… but I'd wager that the amount of overall frustration caused by `([bar])` failing silently will be much, much higher than the amount of frustration caused because `([foo])` can't be used to bind to event `'[foo]'`.

Angular 2 has come so far in debuggability, and so much fantastic work has gone into making sure the errors it issues are clear and helpful. It would be great to see this continued here.
