### ISSUE TITLE
Component testing in isolation

### ISSUE THREAD

**Issue by rkirov** [angular/angular#1036]
As components are the basic building blocks of angular 2 applications, it is important to have a solid testing story for them. If the user has a component:
```
@Component
@Template({directives: [B, C]})
class A
```
it is important to be able to mock or stub out `B` and `C` while testing `A` and its template. Since the template annotation is static, we need a new mechanism of dynamically rewiring the template directives list.

To support this I suggest the following API for `TestBed`
```
// Most mocks don't need @Template (can we skip it?)
@Component
@Template
class MockB() {

}

it('...', inject([TemplateModifier], (tm) => {
  tm.for(A).mockDirectives([MockB, MockC]));
  var rootEl = TestBed.compiler('<a></a>');
}));
```

Further tools for generating `mockB` and setting expectations on it can be provided.

**Comment by trinarytree** [comment]
thanks, rado.  let me suggest a tweak to this idea.  as you have it, if my component uses 100 directives and i want to mock just 2, then i would need to import all 100 in my test and write 98 of them repetitiously in this mockDirectives list.  since the number of things we want to mock is probably small compared to the number we want to leave as is, why not use a map instead?: `mockDirectives({B: MockB, C: MockC})`.

let me also mention a related problem whose solution may be a bit more challenging, but it's better to start thinking about it early.  look at how the production `@Template` has a directives list and it uses the controller classes as DI keys.  in angular-dart, selector strings were the DI keys.  i'm guessing that angular2 uses the controller classes as DI keys here to solve the following problem
(0) by forcing importing, directive names can have a local meaning, thus avoiding the global variable soup directives cause in angular-dart.
but this can cause other problems:
(1) you probably can't have 2 components in 2 different libraries that mutually use each other because it would cause a circular dependency.  even if dart allowed it, your build system might not.
(2) it forces a unit test to **depend on the entire transitive closure** of the component dependencies, even though it may not be be using them at all.
perhaps angular2 doesn't care about (1), as it is a corner case, but (2) seems more significant.

i think the problem here is analogous to what happens in guice when you try to declare module bindings at the site of the consuming classes, say, with fancy annotations, instead of using a separate module.  the problem is that the consuming class shouldn't be declaring assumptions about how its reconfigurable dependencies are configured.  it should use DI keys to declare what it depends on, but not what those keys are bound to in the production config.  only the binding module, which a unit test should not depend upon, should declare how those DI keys are bound.

(0) and (2) can be solved simultaneously simply by
(a) making local uses of short selector strings map to longer aliases, and that mapping only applies locally: e.g. a template can use `<a>` and `<b>` and the controller can declare that these are shorthand for
`long.qualified.path.name.a`
`long.qualified.path.name.b`
say, in some aliasing param to the `@Template`:
```
@Template(directives: {
  'a': 'long.qualified.path.name.a',
  'b': 'long.qualified.path.name.b',
})
```
as a minor variant, we could use `'a': 'library.import.path'` to mean "import from library.import.path the component with selector a", since library import paths are strings anyway.  (but then you'd lose the ability to locally alias, unless you came up with a weird notation, like `'a': 'library.import.path a_as_it_appears_in_that_library'`)

if you guys like importing actual classes because you see (1) as a feature (instead of as a restriction), you can still solve (0) and (2) together by just making the DI key some object other than the production controller class (and that object is _not_ in the production version of the depended-upon component library).  e.g.
(b)
```
// in a_key.dart
library a_key;
const A_KEY = const Key('a');

// a.dart
library a;
import a_key;
@Component
@Tempate(injectedWith: A_KEY)
...
```
but honestly, (a) is so much simpler, and it even allows aliasing so that if you have 2 libraries that both use the same short selector, you can alias them to different values and use them together anyway.

**Comment by jbdeboer** [comment]
@rkirov Mocking out children components is a very big design decision. Could you link to a doc where you discuss the rational and evaluate alternatives?

**Comment by rkirov** [comment]
@vicb mentions this capability in his doc https://docs.google.com/document/d/1qFfHwYCOLpLuTap_l6TCEaU4I0C-pVFVbTl2o4-XbUo/edit#

under `TB.overrideTemplateDirectives(componentType, fromDirective, toDirective);`

**Comment by vicb** [comment]
There is an early proto in https://github.com/angular/angular/pull/1160. Needs more work but I wanted to test what it would look like. I'll keep working on it in the coming days.

**Comment by rkirov** [comment]
@trinarytree, vicb's proposed API `TB.overrideTemplateDirectives(componentType, fromDirective, toDirective);` solves the issue concerning keeping old dependencies.

The other concerns, go beyond testing, because the component under test would also be importing its real dependencies whether or not they are used (because they are in the `directives` annotation). It would require a major rethinking of DI if we are to support the string-based approach you are suggesting, maybe we should discuss it separately from testing.

Btw, dart *does* support cyclical imports, so this only concern in some circumstances.

**Comment by trinarytree** [comment]
@deboer, you should have already seen https://docs.google.com/document/d/10q7pvudn2KMELJypQnzHS_98wQIoNHHOLoBS9MdXxdo/edit#heading=h.xft1erqeq2t0
but, to summarize the component mocking part, angular
(1) injects lots of stuff, including components
(2) lets you mock everything but components
(3) encourages mocking for testing by design (e.g. search for how many "Mock" classes it provides)
(4) requires some form of component mocking to isolate a component for testing.

so it seems like the inability to mock components was a design oversight, not a master stroke.

**Comment by jbdeboer** [comment]
That is not a public doc.

**Comment by naomiblack** [comment]
Obsolete. (Finished as part of Testbed API)
