### ISSUE TITLE
APP_INITIALIZERs are executed in the root zone

### ISSUE THREAD

**Issue by vsavkin** [angular/angular#10363]
```
bootstrap(MyComponent, [
  {provide: APP_INITIALIZE, multi: true, useValue: myInit}
])

function myInit() {
   console.log(Zone.current._name);
}
```

It should print 'angular', but it prints 'root'.

**Comment by tbosch** [comment]
@vsavkin I just changed our hello world example to this code and it prints `angular`. Also tried [via plunker](http://plnkr.co/edit/dLsVJYqhYDgxAil3sbnw?p=preview) with same result. Can you create a repro?

**Comment by tbosch** [comment]
Ok, I was able to reproduce it via https://github.com/angular/angular/issues/10079. The error shows up because of the following:

`setupRouterInitializer` is a factory for an APP_INITIALIZER`. It is therefore already called when the the module is instantiated in `PlatformRef.bootstrapModule`. And that happens outside of the Angular zone, which is wrong. To reproduce:

```
  bootstrap(HelloCmp, [
    {provide: APP_INITIALIZER, multi: true, useFactory: setupRouterInitializer, deps: [Injector]}
  ]);

  function setupRouterInitializer(injector: Injector) {
    console.log('>>> current zone', (<any>Zone).current._name);
    return () => {};
  }
```
