### ISSUE TITLE
Data binding not work in cordova after plug-in response

### ISSUE THREAD

**Issue by faustomura** [angular/angular#10387]
[x] bug report
[ ] feature request
[ ] support request

I use cordova-plugin-cszbar cordova plug-in in angular2 rc4 Typescript into android device 5.1.1.
After the callback response of plugin the data binding not work anymore and this resume if i try to interact with the view buttons.

**Comment by ericmartinezr** [comment]
See https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question

**Comment by vicb** [comment]
Plus your question seems to be related to a plugin that is not part of angular

**Comment by faustomura** [comment]
but the plug-in have ended all work when the problem happens.
In the callback i assign the received value in component value and the the view no show anyting :(
Angular2 in Cordova are testend or it is not recommended to use it?

**Comment by Mintsaus** [comment]
For anyone interested:
We experienced similar problems with Cordova Plugins and found out the issue was that the callbacks wouldn't run in Angular's zones by default (somehow, don't know the full details here). This would case the change detection to not run. Its solvable by making the callback an arrow function that uses ngZone like so:
`let successCall = () => {
      this.ngZone.run(() => {
       doStuffLikeRouting();
      });
    }`

**Comment by Krisa** [comment]
Thank you @Mintsaus . I think it shall be better documented, cause NgZone is smart enough to handle most cases and it's not obvious at first we have to use this when developing Mobile apps.
