### ISSUE TITLE
Custom end condition on *ngFor

### ISSUE THREAD

**Issue by glemiere** [angular/angular#10419]
Hi!

Angular 2 is awesome! However I think something important is missing in the *ngFor built-in directive. I'm taking an example of something I'm actually working on : a picture gallery.

```
<div *ngFor="let pic of pics; let i = index">
    <div *ngIf="whichRowType(i) == 3">
        <small>pic[whichIndex(i)].id</small>
        <small>pic[currentIndex + 1].id</small>
        <small>pic[currentIndex + 2].id</small>
    </div>

    <div *ngIf="whichRowType(i) == 2">
        <small>pic[whichIndex(i)].id</small>
        <small>pic[currentIndex + 1].id</small>
    </div>

    <div *ngIf="whichRowType(i) == 1">
        <small>pic[whichIndex(i)].id</small>
    </div>
</div>
```

In that very easy case, my end condition will be "i < pics.length". I need my end condition to be "i < currentIndex".

Being able to customize our end condition is an important feature in my opinion. Is there anything planed about that ?
Thank you very much for you work!

**Comment by vicb** [comment]
Instead of using pics you can make an iterable of the applicable pics.

Please note:

Your question sounds like a support request.

Please use the issue tracker only for bugs and feature requests.

Use [gitter](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem) and [StackOverflow](http://stackoverflow.com/questions/tagged/angular) for support request.

**Comment by vicb** [comment]
> Instead of using pics you can make an iterable of the applicable pics.

Is my answer (or "no" if you expect a y/n answer). It's easy enough to return the appropriate stuff from your component.
