### ISSUE TITLE
Biding to array elements using ngModel and inside a ngFor

### ISSUE THREAD

**Issue by snolflake** [angular/angular#10423]
**I'm submitting a ...
```
[X] bug report
```
I'm using `ngModel` to bind values of an array into  to number inputs.
After some time making changes to the inputs, the bindings stop working properly updating the wrong inputs. But the issue only seems to happen on the inputs generated inside a ngFor.

Keep one eye on the input at top right:
![output](https://cloud.githubusercontent.com/assets/1047033/17326814/321b473c-588a-11e6-8647-9d1c4ff7ade6.gif)

**Reproduction of the problem**
http://plnkr.co/edit/OyquSRANdfBpP2qP7obb?p=preview
Open the demo and stress the first row of inputs firing changes at random until weird things happen.
Notice that making changes in the second row of inputs does not reproduce the issue.

**Please tell us about your environment:**
* **Angular version:** 2.0.0-rc.4 
* **Browser:** Chrome 52.0.2743.60 beta (64-bit) 
* **Language:** TypeScript 2.1.0-dev.20160727 targeting ES5

**Comment by zoechi** [comment]
This can be fixed using custom `trackBy`
See for example https://angular.io/docs/ts/latest/guide/template-syntax.html

GitHub issues are for bug reports and feature requests.
    For support questions please use other channels like the ones listed in [CONTRIBUTING - Got a Question or Problem?](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question)

**Comment by snolflake** [comment]
@zoechi I can't see how this issue relates to `NgForTrackBy`

**Comment by jntr06** [comment]
Same issue I am facing. Not able to use ngModel  inside *ngFor

**Comment by zoechi** [comment]
@snolflake you're iterating the items you're editing and they are primitive values. `ngFor` can't keep track by identity because when the value changes from `1` to `3` (by editing) it becomes a different identity. Either use a custom `trackBy` that tracks by index or use objects instead of primitive values.

**Comment by snolflake** [comment]
Thanks for the clarification @zoechi , at first `NgForTrackBy` seems to exist only to solve performance issues on change detection.

So, just for the record here's how you make it "trackBy" index:
```
import { Component, OnInit } from '@angular/core'

@Component({
  selector: 'my-app',
  template: `
    <label *ngFor="let item of items; let i = index; trackBy:trackByIndex">
    	{{items[i]}}
    	<input type="number" min="0" max="10" step="2" [(ngModel)]="items[i]">
    </label>
  `
})
export class App implements OnInit {
  items: number[] = [1,2,3,4,5]
  
  constructor() {}
  
  trackByIndex(index: number, value: number) {
    return index;
  }
}
```

**Comment by anivaisu** [comment]
Hi 

I am beginner in angular 2,ionic 2

I create chat application using ionic2.

I have an array value display UI using ngFor.

Pls refer this http://imgur.com/dpnLSSv

I need does not display repeated data.Because I need get input element value and compare with another value.I try to this way.

Below my html code

<ion-content padding>
  <div *ngIf="online === true">
  <ion-refresher (ionRefresh)="onPullOldMessages($event)">
      <ion-refresher-content></ion-refresher-content>
  </ion-refresher>
  <div class="chat" *ngIf="chatval">

    <div class="messagesholder" *ngFor="let chat of chatval | orderby:'[date]';let i = index; trackBy:trackByIndex">
       <div *ngIf="chat.sender == currentuser || chat.receiver == currentuser">
               <input [(ngModel)]="chat.date" type="hidden" value="John Doe">
               <p style="font-size:9px;text-align: center;" id="amount" #amount>{{chat.date | amDateFormat:'LL'}}</p>
       </div>
       <div class="message" *ngIf="chat.sender == currentuser || chat.receiver == currentuser" [ngClass]="{'me': currentuser == chat.sender}">
              <div class='image' *ngIf="chat.path" >
                <img *ngIf="chat.path" [src]="chat.path" imageViewer/><br>
                <span *ngIf="chat.path_text">{{chat.path_text}}</span>
                <span style="font-size:9px;">{{chat.date | amDateFormat:'hh:mmA'}}</span>
              </div> 
               <div *ngIf="chat.message_text">
               <span>{{chat.message_text}}</span>
               <span style="font-size:9px;">{{chat.date | amDateFormat:'hh:mmA'}}</span>
               </div>
        </div>
   </div>
 </div>  
 </div>
</ion-content>
Here is my chat.ts component file

  import { Component,Inject,ViewChild,ElementRef,AfterViewInit} from '@angular/core';

export class ChatPage implements AfterViewInit {
   constructor(public modalCtrl: ModalController,public navCtrl:     NavController) {}

 trackByIndex(index: number, value: number) {
   console.log("ngFor");
   console.log(index);
   console.log(value);
   return index;
   }
}
Does not called the trackByIndex function.How can I get this input element value. I was tried another way. Pls refer this link Angular 2 get Input element value Its not still wrk.

any other way to find this solutions.

Thanks

**Comment by DzmitryShylovich** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).

cc @pkozlowski-opensource

**Comment by nasiruddin-saiyed** [comment]
@cvsguimaraes Thanks a lot bro !!

**Comment by srihari-ananthakrishna** [comment]
@zoechi and @cvsguimaraes: I was having this issue with a row of checkboxes that had their model as array items. Came across these posts and the explanation/clarifications you guys had posted helped me resolve my issue. Thanks a lot!

**Comment by Braian2012** [comment]
This works https://angular.io/guide/template-syntax#inside-ngmodel
