### ISSUE TITLE
Custom Input isn't being sent as param when using ngNoForm

### ISSUE THREAD

**Issue by eliezerreis** [angular/angular#10433]
Hi,

https://plnkr.co/edit/nIf2Wdr6IqoJz87VVhdJ?p=preview

In this situation above, the custom field isn't shown in param's list of the http request when I inspect it and I confirm that all values are null when they reach the server. However, the conventional html input is being sent correctly.

Is it intend to be like this or is it a bug?

Best,

**Comment by kara** [comment]
@eliezerreis When you add `ngNoForm`, you turn off Angular's form registration helpers. In other words, the `NgForm` directive is never activated. This is the directive that knows how to interact with custom value accessors.  Without it, you're just using HTML5 forms at the top level, which of course won't know anything about your custom input. This is expected behavior for `ngNoForm`, so I'm going to close this.
