### ISSUE TITLE
NgForTrackBy function has wrong this context

### ISSUE THREAD

**Issue by PleasantD** [angular/angular#10485]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report
[ ] feature request
[ ] support request 
```

**Current behavior**
`trackByFn` cannot access the internal context of the class it is defined in via `this`

**Expected/desired behavior**
`trackByFn` should be able to access the internal context of the class it is defined in.

**Reproduction of the problem**
http://plnkr.co/edit/uqdHKi3TqD0ydBO5mgVO?p=preview

**What is the motivation / use case for changing the behavior?**
I'm trying to create a dynamic list/grid component. I won't know the tracking ID until the configuration is set (dynamically), so I need to be able to track by something within the context of the component.

**Please tell us about your environment:**

* **Angular version:** 2.0.0-rc.4
 
* **Browser:** [all] 
 
* **Language:** [TypeScript 1.8]

**Comment by zoechi** [comment]
`console.log(this)` prints `DefaultIterableDiffer`

**Comment by vicb** [comment]
This is because JS :)

It will work with `trackFn.bind(this)` when `this` is supported (see #10501).

For now you'll have to  `trackFn.bind(that)` & `get that() { return this; }`.

We have been discussing about implementing `::trackFn` but the bind op still in discussion for ES next and we prefer to wait for things to be settled before (not) implementing this.
