### ISSUE TITLE
@HostBinding not working on @Input properties

### ISSUE THREAD

**Issue by vankeer** [angular/angular#10499]
**I'm submitting a ...**

```
[x] bug report
[ ] feature request
[ ] support request
```

**Current behavior**

When defining a @HostBinding on an attribute directive referring to an @Input property of the host component, it does not update the host property after changing the value.

**Expected/desired behavior**

@HostBinding should probably apply to all properties of the host, including @Input properties.

**Reproduction of the problem**

Plunker: [https://embed.plnkr.co/kQEKbT/](https://embed.plnkr.co/kQEKbT/)
Stackoverflow question and answer with solution using a template reference variable: [http://stackoverflow.com/questions/38771403/how-to-use-hostbinding-with-input-properties-in-angular-2](http://stackoverflow.com/questions/38771403/how-to-use-hostbinding-with-input-properties-in-angular-2)

**What is the expected behavior?**

In the example above: the attribute directive should feed the input property of the component.

**What is the motivation / use case for changing the behavior?**

See Plunker above. This could be useful when you want to create a directive that feeds the input of a component.

**Please tell us about your environment:**
- **Angular version:** 2.0.0-rc.4
- **Browser:** Chrome 51 (likely applies to all)
- **Language:** TypeScript 1.8.10 (likely applies to all)

**Comment by schippie** [comment]
I have also bumped into this issue though in our case the problem we where having is setting the `md-input` `disabled` property (angular2 material - https://github.com/angular/material2/tree/master/src/lib/input ) based on if the user had a specific role.

We decided to try this route because we didn't want to have hundreds of `[disabled]="(accountService.get() | async).role === 'ADMIN" throughout our application. But we also stumbled upon the same problem described above. 

Example:


InputDisabledDirective:
```javascript
@Directive({
    selector: '[myInputDisabled]'
})
export class InputDisabledDirective implements OnInit {
    @HostBinding() disabled: boolean = false;
    constructor(private resource: AccountService) { }

	ngOnInit() {
		//I know this subscription is not cleaned up in the ngOnDestory() but this is purely an example
		this.resource.get()
			.filter(account =>  account.role === 'ADMIN')
			.subscribe(account => this.disabled = true);
    }
}
```

HTML:
```html
<md-input myInputDisabled ... > </md-input>
```

**Comment by sqwk** [comment]
Is there a known workaround for this? Other than going to the parent component?

**Comment by vicb** [comment]
have you tried to use @Directive({host, inputs});

From looking at the code, I can confirm `@Input` and `@Host...` are exclusive. It's indeed a bug.

**Comment by zoechi** [comment]
@vankeer your Plunker didn't work for me.
I updated it https://plnkr.co/edit/JwS6aPlCa5QfsVRkQlNg?p=preview
It seems to work or is there something that doesn't behave as expected?

**Comment by schippie** [comment]
@zoechi When you look at the plunker you updated you will notice that the example:

```html
    Using CustomImgComponent with SrcKeyDirective:<br/>
    <custom-img [srcKey]="imageKey"></custom-img>
```

Doesn't work.

**Comment by zoechi** [comment]
@schippie thanks. I see it now.

**Comment by vicb** [comment]
Updated plunker (2.0.1): http://plnkr.co/edit/BvjfXCN5eSoyiWWQs3DN?p=preview

Produces this error message:
```
Can't bind to 'src' since it isn't a known property of 'custom-img'.
1. If 'custom-img' is an Angular component and it has 'src' input, then verify that it is part of this module.
2. If 'custom-img' is a Web Component then add "CUSTOM_ELEMENTS_SCHEMA" to the '@NgModule.schemas' of this component to suppress this message.
```

@tbosch looking at the code `@Host...` is for HTML element only, would it make sense to support Component as well ?

**Comment by pkozlowski-opensource** [comment]
It opens up a couple of "interesting" issues:
* it would create strong link / coupling between 2 directives (one directive would have to _assume_ that another is present on the same element)
* if you can make it work for component why not for other directives?
* how should we handle shadowing of property bindings?

The example in the plunker seems a bit convoluted, you could make things working simply as http://plnkr.co/edit/vKPqcdMZKqZErshZ1hse?p=preview, not sure what the `SrcKeyDirective` brings to the picture.

**Comment by schippie** [comment]
@pkozlowski-opensource I might be wrong (sorry if i am) but:

>it would create strong link / coupling between 2 directives (one directive would have to assume that another is present on the same element)

Would this actually be true? Since the introduction of the NgModule system you can generally say that the module already declares all the requirements for the directives/ components within the module. 

So for example (in the example I provided): You could simply say that the module which contains the directive (that would set the `disabled` property on the host element) has an import statement for the `MaterialModule`

>The example in the plunker seems a bit convoluted, you could make things working simply as http://plnkr.co/edit/vKPqcdMZKqZErshZ1hse?p=preview, not sure what the SrcKeyDirective brings to the picture.

I think that while the example might not show the usefulness as well as it could this shouldn't be a reason to not explore the possibilities. Since there are quite a few use cases i can think of where having this functionality would be extremely useful. 
Another argument for having this option is that for example `[routerLink]` already sets properties (even if they are native properties like `href`). So for developers it would seem natural that it would also work for Component / Directive `@Input`'s as well. 

Added the example I gave https://github.com/angular/angular/issues/10499#issuecomment-244882457 but like @vicb said it no longer works in 2.0.0
http://plnkr.co/edit/JwgIzgeF6eMXyGmJrpoY?p=preview

**Comment by abierbaum** [comment]
@pkozlowski-opensource @schippie Here is a shorter example that shows a hostbinding and input we just came across:

```
@Component({
   selector: 'expandable-comp',
   template: '<div><ng-content></ng-content></div>'
)}
export class ExpandableComponent {
   @HostBinding('class.expanded') @Input() expanded: boolean = false;
}
```

We wanted to have an input that when set would change a class on the host component ('expandable-comp').  From what I can tell this doesn't work in Angular 2 right now and I don't see an easy or direct workaround.

**Comment by zoechi** [comment]
@abierbaum I think the workaround is quite easy:

```ts
@HostBinding('class.expanded') 
expandedClass:boolean = false;
@Input() set expanded(val:boolean) => this.expandedClass = val;
```

**Comment by schippie** [comment]
@abierbaum  This is sadly not related to the problem I've been having with Hostbinding's and Input's.  A @Directive setting an @Input property of the @Component element tag the directive is placed on.

**Comment by DzmitryShylovich** [comment]
Already fixed https://plnkr.co/edit/ZJHsfAr1Gs4BZYYWAHvu?p=preview

**Comment by pkozlowski-opensource** [comment]
Thnx @DzmitryShylovich

**Comment by schippie** [comment]
@DzmitryShylovich  Does that mean it will never work for use cases like: 

```javascript
//our root app component
import {  
  Component,
  Directive,
  provide,
  HostBinding,
  Input, 
  NgModule,
} from '@angular/core'
import {BrowserModule} from '@angular/platform-browser'


//Disable input directive
@Directive({
  selector: '[disable-input]'
})
export class DisableInputtDirective {
  @Input('disable-input') role: string;
  //comment this line for it to work. 
  @HostBinding('disabled') disabled: boolean;
  
  ngOnChanges() {
    this.disabled = (this.role === 'USER');
  }
}


//md-input compent 
@Component({
  selector: 'md-input',
  template: `
    <label>{{title}}</label>
    <input [readonly]="disabled">
  `
})
export class MdInputComponent {
  @Input() title: string;
  @Input('disabled') disabled: boolean = false;
}


//APP component
@Component({
  selector: 'my-app',
  template: `<md-input [disable-input]="role"></md-input>`
})
export class App {
  role: string = "ADMIN"
  
  ngOnInit() {
    setInterval(() => {
      this.role = (this.role === 'ADMIN') ? 'USER' : 'ADMIN';
    }, 2000)
  }
}

//MODULE
@NgModule({
  imports: [ BrowserModule ],
  declarations: [ 
    App, 
    MdInputComponent, 
    DisableInputtDirective
  ],
  bootstrap: [ App ],
})
export class AppModule {}
```

https://plnkr.co/edit/NHPEZ0IKaVO4qmLNZRqR

**Comment by DzmitryShylovich** [comment]
> Can't bind to 'disabled' since it isn't a known property of 'md-input'.

hmm not sure it's related to this issue

**Comment by DzmitryShylovich** [comment]
It works fine with
```
@HostBinding('attr.disabled') disabled: boolean;
and
@HostBinding('class.disabled') disabled: boolean;
```

**Comment by schippie** [comment]
@DzmitryShylovich Updated the plunker to show that it won't work in that way:

https://plnkr.co/edit/NHPEZ0IKaVO4qmLNZRqR

I talked about this problem in the first comment https://github.com/angular/angular/issues/10499#issuecomment-244882457 but I might just have to open a separate ticket that you cannot set an @Input property of a component with an @Hostbinding in a Directive.

**Comment by DzmitryShylovich** [comment]
> Updated the plunker to show that it won't work in that way:

it works http://prntscr.com/drcro1 u just need to set it to `null` instead of `false` if u want to remove it from the element

>  I might just have to open a separate ticket

I think it makes sense

**Comment by schippie** [comment]
You are right that it removes the property / applies the property but the component is never notified of this fact. The component isn't aware of this change:

![image](https://cloud.githubusercontent.com/assets/3273412/21641082/cb828552-d279-11e6-88be-34c009864a7c.png)

Which makes me wonder if it's by design liked asked in the original comment or if it's a bug that a Directive cannot set the Input value of the component on which it's applied.

**Comment by DzmitryShylovich** [comment]
@schippie file a new ticket pls
