### ISSUE TITLE
Componentless Parent resolve is not properly loaded

### ISSUE THREAD

**Issue by venkateswaris** [angular/angular#10494]
--
In angular router config, it is mentioned that`The router will also merge the params, data, and resolve of the componentless parent into the params, data, and resolve of the children.`

But when i implement this, i can get parent state params, data in child. I am trying to get parent resolve in child component constructor. But parent resolve is injected some time only.But I network call is fire to get that parent resolve data.  Wont the child component wait for parent resolve?

* **Angular version:** 3.0.0-beta.2
 
* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ] 
 
* **Language:** [TypeScript ]

**Comment by zoechi** [comment]
Please provide a Plunker that allows to reproduce.

**Comment by carlosthe19916** [comment]
`export const OrganizationsRoutes: RouterConfig = [
  {
    path: 'organizations',
    children: [     
      {
        path: 'edit-organization/:organization',
        component: EditOrganizationComponent,
        resolve: {
          organization: OrganizationResolve
        },
        children: [          
          {
            path: 'overview',
            component: OverviewComponent
          }          
        ]
      }
    ]
  }
];`

How can i get the parent resolve data **organization** into OverviewComponent?

**Comment by venkateswaris** [comment]
In child component, you get parent resolved data as activatedRoute.snapshot.data['parentresolve'].

**Comment by carlosthe19916** [comment]
Thanks, but i'm having the same problem. here i prepare a simple Plunker scenario http://plnkr.co/edit/iH0TvPjOZODwbcuXphXs?p=preview 

When i resolve data on parent router, the childs can't take the resolved data from parent

{
    path: 'user/:id',
    resolve: {
      **user: UserResolve**
    },
    children: [
      {
        path: 'overview',
        **component: UserOverviewComponent**
      }
    ]
  }

i'd like UserOverviewComponent take the resolved data **user** from parent router.

> i tested and i can take the data resolved on the parent router but no on the child router. This plunker is for take the resolved data on the parent router http://plnkr.co/edit/X6JKMsqnPP0dXwyAl9n3?p=preview

**Comment by venkateswaris** [comment]
@carlosthe19916 Yes. Thanks a lot for adding plunker. 

@pkozlowski-opensource  can you please check @carlosthe19916's  plunker link and reopen this issue?

**Comment by carlosthe19916** [comment]
I was spending more time in this problem and i notice that the problem is only when i resolve an **Observable** object, if i resolve a **Promise or static** data all the resolved data is ok.

Yesterday i upgraded my project to **@angular/__: 2.0.0-rc.5** and router to **@angular/router": 3.0.0-rc.1** and incredibly the problem was solved without any modification of my code.

My problem was solved upgrading angular to the last version, @venkateswaris  please check your own code with the lastest version and tell us if your problem persists.

**Comment by venkateswaris** [comment]
Hi @carlosthe19916 

i have tried with rc5 and router 3.0.0-rc.1

Still the problem exists.

http://plnkr.co/edit/ujSqCg?p=preview - ( I have forked your plunker and changed router to load data in parent route. )

@pkozlowski-opensource can you please check this plunker link and reopen this issue?

**Comment by carlosthe19916** [comment]
Hi @venkateswaris i was checking your plunker and i think that is incorrect to declare `id` parameter on child because `resolve` is on parent. You should change this code 

> {
    path: 'user',
     resolve: {
          user: UserResolve
        },
    children: [
      {
        path: ':id',
        component: UserComponent
      }]
  }

by this:

> {
    path: '**user/:id**',
     resolve: {
          user: UserResolve
        },
    children: [
      {
        path: '',
        component: UserComponent
      }]
  }


But the problem of resolve parent data still persist. I improved our [plunker](https://plnkr.co/edit/0f6HTyQ8MI99X4mrn31N?p=preview) to explain the problem with more details.

The problem happened when the childs of a router parent changed, because when children routes changes, the data parent is lose too.

Any idea to solve this problem? i'm going to check the code, i hope find the exact problem. let me know for any idea to solve the problem.

Note: this is the prepared plunker to explain the problem https://plnkr.co/edit/0f6HTyQ8MI99X4mrn31N?p=preview

**Comment by bhelzer** [comment]
I have the same problem. Here is what I see, given these routes:
```javascript
    {
        path: '',
        resolve: {
            personas: PersonasResolveService
        },
        children: [
            {
                path: 'home',
                component: HomeComponent,
            },
            {
                path: 'student',
                component: StudentComponent,
                resolve: {
                    enrollments: EnrollmentResolveService
                }
            }
        ]
```

1. Navigate to **home** route.data is empty
2. route.parent.data contains the personas
3. Navigating to **student** from **home** route.data contains enrollments
4. Refreshing the browser while on **student** route.data contains both personas and enrollments

I can prepare a plunker if needed.

**Comment by vsavkin** [comment]
Fixed https://github.com/angular/angular/commit/6ccbfd41dd1bcc8c2b7e2a86f893d91104856b9a
