### ISSUE TITLE
Setter method not using everytime

### ISSUE THREAD

**Issue by jaroslawziolkowski** [angular/angular#10516]
[x] probably bug report

I'm not sure does it bug but probably.

http://plnkr.co/edit/A3cE4M

I have 2 componennts, firt emmit array second get is as input. Display list between components is correct. But as input I'm using setter. It is run only when I remove first element next no. You can loot at plnkr example. Always when to component is set new value counter should be increment. But 2 is max value. First increment is when component is init and second after first click "remove" on list.

I asked about it on gitter and nobody know why.

* **Angular version:** 2.0.0-rc.4
 
* **Browser:** [all] 
 
* **Language:** [ TypeScript]

**Comment by zoechi** [comment]
This is expected behavior. The output emits the same array several times. Only the first time is it recognized as changed (from `null` to `array`). Subsequently when the same array is emitted again, change detection doesn't dedect it as change and no update is happening and therefore not call of the setter. 

Please check such question ins support channels before posting bug reports

 [CONTRIBUTING - Got a Question or Problem?](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question)
