### ISSUE TITLE
[BugReport] - More explicit error message when directives are missing

### ISSUE THREAD

**Issue by etiennechabert** [angular/angular#10644]
**I'm submitting a ...**

```
[x] bug report
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
When you forgot to add a directive for one of your components and you use Inputs feature, the error is : 
"Can't bind to '@INPUT_NAME' since it isn't a known native property"

**Expected/desired behavior**
This error doesn't make sense according to the actual mistake.
A proper error would be to report the lack of the "directives" declaration in the @component

**Reproduction of the problem**
I build this little example app, clone it and follow the readme
https://github.com/etiennechabert/BugReportAG2

**What is the expected behavior?**
A more explicit message

**What is the motivation / use case for changing the behavior?**
Being more friendly with AG2 users, particularly new ones ;)

**Please tell us about your environment:**
- **Angular version:** 2.0.0-rc.5
- **Browser:** [all]
- **Language:** [TypeScript 1.8.10]

**Comment by pkozlowski-opensource** [comment]
@etiennechabert I hear what you are saying but the issue here is that you can get the same error for a variety of reasons:
* missing directive, as in the described case
* a simple typo in the directive input
* a simple typo in the native property name
* you are trying to bind to an attribute instead of a property

Unfortunately we've got no way of knowing if the pb comes from a missing directive or a simple typo... So it is kind of hard to suggest a perfect solution. Moreover we are moving away from listing directives in components and shifting towards listing them in modules. For all those reasons we simply can't change the error message as you are suggesting.

Having said the above I think that we can improve this error message since we know which directives are active, what are they properties etc. We also know what are the properties of DOM elements. So technically we could even detect typos.

I will keep this one open to toy with different ideas but it is just to let you know that we can't go ahead with your proposal. There are other things we can do, though.

**Comment by etiennechabert** [comment]
Thanks for this detailed answer @pkozlowski-opensource.

I created this ticket because I believe that forgotten directives are one of the basic errors when you are new with AG2 (at least for me ^^).

A more generic error message (with a list of possible cases including typo, directives and so on) could a least put the developer on one of the good ways, instead of the wrong one. With the actual error message I checked the @Input declaration of my component multiple time before finally founding the real reason for this error.

Anyway it's good to hear that you will be able to be more specific in the future on this kind of mistake.
