### ISSUE TITLE
router: Add a factoryProvider field to router

### ISSUE THREAD

**Issue by hansl** [angular/angular#10659]
Example of usage:

```typescript
function getThatThing() { return System.import('my/path/to/module').then(x => return x.MyClass); }

@NgModule({
  declarations: [ /* ... */ ],
  imports: [
    RouterModule.forRoot({
      { path: 'lazy', factoryProvider: getThatThing }
    })
  }
})
export class MyModule {}
```

Signature of function:

```typescript
interface ModuleFactoryProvider {
  (this: void) => ConcreteType | Promise<ConcreteType>;
}
```

This would be useful for webpack 1 and 2 lazy routes, as webpack does not understand `System.import()` that deep in the module resolver providers (with string parsing etc).

**Comment by hansl** [comment]
This was discussed in the #router slack channel; https://angular-team.slack.com/archives/router/p1470870125000002

**Comment by benelliott** [comment]
I'm running into issues getting lazy loading to work with RC5 and Webpack and I think the fundamental problem is the same as this issue.

Essentially I'm trying to write a class `WebpackNgModuleLoader implements NgModuleFactoryLoader` and, at bootstrap `provide` this as a means to lazy-load modules. But it looks like `SystemJsNgModuleLoader` is hard-coded into the router too deep into the source code to override it at bootstrap:
```
    provideRouterInitializer(), {provide: NgModuleFactoryLoader, useClass: SystemJsNgModuleLoader}
``` (https://github.com/angular/angular/blob/2eda7a52931b8ae8c8429dfcfd79e1a2912a5d3d/modules/%40angular/router/src/common_router_providers.ts#L102)

This fails on my build because there is no global `System` object.

Perhaps I'm going about this the wrong way, but I think it should be possible to provide your own module loader to override this if not using SystemJS.

**Comment by brandonroberts** [comment]
@benelliott you should add your custom provider in the main module's `providers` after the RouterModule.forRoot

**Comment by benelliott** [comment]
@brandonroberts will try that, thanks!

**Comment by tsm91** [comment]
```js
function getThatThing() { return System.import('my/path/to/module').then(x => return x.MyClass); }
```

if `getThatThing` is only invoked in runtime webpack's `CommonsChunkPlugin` wont be able to create a separate chunk in build time

an api like this would be just fine, because you provide the `compiler` instance

```js
  {
    path: '',
    loadChildren(compiler) {
      return System
        .import('./pages/home')
        .then(module => compiler.compileModuleAsync(module.HomeModule));
    }
```

**Comment by niveo** [comment]
tsconfig.json
"module": "system"

`
import { Component } from '@angular/core';

declare var __moduleName: string;
declare var System: any;

@Component({
  moduleId: __moduleName,
  selector: 'app-root',
  templateUrl: 'app.component.html',
  styleUrls: ['app.component.css']
})
export class AppComponent {
    constructor() {}

 private url: string = '';
 private type: string = '';

  loadModule(): any {
    
    this.url = 'app/logger.component';
    this.type = 'LoggerComponent';
    
    return System.import(this.url).then((rest: any) => {
      console.log(rest);
      return rest[this.type];
    });
  }
}
`

**Comment by ashleahhill** [comment]
@benelliott Did you ever get WebpackNgModuleLoader to work using the provider setup?

**Comment by benelliott** [comment]
@ashleahhill no, I pinned to a nightly build of angular/router with support for a callback as the `loadChildren` attribute of a route config, then in each function I loaded the module using the Webpack ES6 promise loader, similarly to RC4 and downwards. This functionality may well be supported in router rc2 but I can't check right now.
