### ISSUE TITLE
Why NG2 App has to be downgraded if we want to use an existing NG1 directive

### ISSUE THREAD

**Issue by aprinaresh97** [angular/angular#10698]
**I'm submitting a ...**  (check one with "x")

```
[ ] bug report
[ x] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
We have a Angular 2 application. We also have a library of Angular 1 directives. We would like to use some of the Angular 1 directives in the Angular 2 application. In order to do this it looks like we have to still downgrade the Angular 2 application. Why? We want to run as Angular 2 Application but use some of the existing Angular 1 directives in the Angular 2 application.

_let appComponent = **NgUpgrade.downgradeNg2Component(AppComponent);**
NgUpgrade.addProvider(Http);
NgUpgrade.addProvider(HTTP_PROVIDERS);

angular.module('app').directive('awMyApp', appComponent);

// Bootstrap in Hybrid mode
NgUpgrade.bootstrap(document.body, ['app']).ready(function (ref: UpgradeAdapterRef) {
    let injector = ref.ng2Injector;
    let appRef = ref.ng2ApplicationRef;
    GlobalContext.rootInjector = appRef.injector;
    GlobalContext.getInstance();
});_

**Expected/desired behavior**
We should not be downgrading Angular 2 application in order to use Angular 1 directives. We want to run it as Angular 2 application and still use existing Angular 1 directives. All the examples in the web and documentation only talk about how to upgrade an Angular 1 application incrementally. Our scenario is we have developed Angular 2 application but also want to leverage some of the Angular 1 directives in the Angular 2 application.

**Question**
1. Are there any drawbacks of downgrading an Angular 2 application to use Angular 1 directives?
2. Does downgrading affect the performance of the application?

**What is the expected behavior?**

**What is the motivation / use case for changing the behavior?**

**Please tell us about your environment:**
- **Angular version:** 2.0.0-rc.4
- **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ] 
- **Language:** [TypeScript]

**Comment by petebacondarwin** [comment]
The terminology is misleading - `downgrade` in the context of ngUpgrade simply means making an Angular 2+ thing (component or service) available in the Angular 1 context.

In ngUpgrade, each DOM element must be owned by exactly one of Angular 1 or Angular 2+. Since Angular 1 is less versatile than Angular 2+ in how it can be bootstrapped in a web page, it turns out that it is best for the `upgrade` library that the top level DOM node is owned by Angular 1.

This means that if you want your app's root component to be from Angular 2+, then you must "downgrade" that component and place it below the root DOM element on which you bootstrap Angular 1.

There should be no downside from downgrading the root component in this way. Any performance effects that may be seen are due to the interoperation between Angular 1 and Angular 2+ in general and so would exist whether or not the root component is Angular 2+ or not.

**Comment by petebacondarwin** [comment]
It may be possible to only bootstrap the Angular 1 bits when we need an Angular 1 component in the new `upgrade/static` library. We are looking into it.

**Comment by petebacondarwin** [comment]
Closing as I think that this has been explained. Please open a new issue if you want to continue the discussion.
