### ISSUE TITLE
Using NgForm myForm.reset() has no effect on the submitted property

### ISSUE THREAD

**Issue by gregbown** [angular/angular#10709]
Using NgForm calling form.reset() does not reset the submitted to false

**Expected/desired behavior**
The form property submitted should be reset

**What is the motivation / use case for changing the behavior?**
If there are no other ways to access submitted reset should reset all properties of form.
Using [disabled]="myForm.submitted" in submit button
After request returns the data I want the form to be available again if I choose to.
Using myForm.reset() has no effect on the submitted property.

Angular version: 2.0.0-rc.5
Windows 10
Chrome

**Comment by kara** [comment]
`reset()` on `NgForm` was falling through to its internal `FormGroup` instance's `reset()` method.  Since `FormGroup` instances have no concept of submission (it only makes sense at the top level), the property could not be reset by the.

https://github.com/angular/angular/pull/10715 introduces a `resetForm()` method for top level form directives (both `NgForm` and `FormGroupDirective`) that will reset the form model *and* reset the `submitted` state to false.
