### ISSUE TITLE
feat(routing) consider merging canActivate and canLoad

### ISSUE THREAD

**Issue by choeller** [angular/angular#10795]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => search github for a similar issue or PR before submitting
[x] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**

While exposing more or less the same functionality `canActivate` and `canLoad` have to be implemented in their own classes / functions. Consider some LoginGuard you currently need to implement two classes:

```ts
@Injectable()
export class LoginGuard implements CanActivate {

  constructor(private loginService: LoginService,
              private router: Router) {
  }

  canActivate(routeSnapshot: ActivatedRouteSnapshot,
              routerSnapshot: RouterStateSnapshot): Observable<boolean> | boolean {

    if (!this.loginService.isLoggedIn()) {
      let redirect = encodeURI(routerSnapshot.url);
      this.router.navigate(["/login"], {queryParams: {redirect: redirect}});
    }
    return true;
  }
}
```

```ts
@Injectable()
export class LoginCanLoad implements CanLoad {

  constructor(private loginService: LoginService,
              private router: Router) {
  }

  canLoad(route: Route):Observable<boolean> | boolean {
    if (!this.loginService.isLoggedIn()) {
      let redirect = encodeURI(route.path);
      this.router.navigate(["/login"], {queryParams: {redirect: redirect}});
      return false;
    }
    return true;
  }
}
```

in combination with issue https://github.com/angular/angular/issues/10584 it would be very useful to merge both attempts into one, so it can be possible to use the same class for `canActivate` and `canLoad`.

 **What is the motivation / use case for changing the behavior?**

Being able to reuse functionality

**Please tell us about your environment:**

* **Angular version:** 2.0.0-rc.5
 
* **Browser:** [all ] 
 
* **Language:** [all ]

**Comment by DzmitryShylovich** [comment]
You can implement both interfaces in the same class like
```
LoginCanLoad implements CanActivate, CanLoad {}
```

**Comment by choeller** [comment]
True... with this the pain is much smaller, so I'll close this one

**Comment by MrCroft** [comment]
This would still be a more than nice feature (somehow merging **canLoad** with **canActivate**).

Consider the following scenario:
Given a lazy loaded module which would only be accessible if the user's token is valid, I use a **canLoad** guard so the module's JS file doesn't even get requested if not needed. **BUT** I also need to implement **canActivate** because, maybe the token became invalid sometime between the last api request and **now**, so I need to restrict the user from accessing that module (already loaded) if he/she doesn't have the right anymore.
Right now, I have **two** requests to `http://api.my-app/auth/check` when a user access that module the first time (one request from **canLoad** and another from **canActivate**)
