### ISSUE TITLE
Animations: Multiple/Configurable void states

### ISSUE THREAD

**Issue by b2bit** [angular/angular#10846]
**I'm submitting a ...**
```
[x] feature request
```

**Current behavior**
Currently there is only one "void" state, which is used to define an element style before that
element enters or after it leaves the "stage". 

**Possible use case**
A question that bugs me is how to implement animation behavior, where you can provide
different "... => void" animations depending on the user action issueing a route change. For
example if I (the user) click on a button called "left" and issue a route change with that click, I
want the current component element to translate and slide out to the left. But if I click on a button
called "right", I want that same element to slide out to the right.

**Desired behavior**
Maybe there should be the possibility to configure, into which state an element transitions when
being unloaded. Currently that state is defined as "void". If that state could be configured
dynamically, it would be possible to define multiple "void" states (eg. "void_left" and "void_right"
in comparison to the use case stated above) that could be accessed depending on a user action 
when leaving the current route.

Maybe that same kind of desired behavior could be extended to the "void" state of an element
when appearing (eg. "void_in_left" and "void_in_right").

So the base idea is that the void state could stay as it currently is and only to be customized when
necessary by similar use cases as the one mentioned above.

**My environment:**

* **Angular version:** 2.0.0-rc.5

**Comment by matsko** [comment]
This will likely not happen as a direct feature for animating `void` because it is something specific to routing. Instead the plans are to expand the triggering API to include support for multiple elements at a time. Since routing involves two or more elements (one element page being removed and another being added) it makes sense to make this work with element querying.

Here's an idea of how this will work with routing:
https://github.com/angular/angular/issues/9845#issuecomment-232476173

So you can imagine that having a directional void animation would be instead something like this:

```
// when going back to the homePage from outerPage
trigger("/homePage <= /outerPage", [

])

// or just global (going from right to left)
trigger("* => *", [])

// or just global (going from left to right)
trigger("* <= *", [])
```

The API needs some work, but we definitely do have this feature in mind for Angular animations.

The next two big animation features are: CSS-level integration and element querying. Please be patient. These features will be developed in the coming weeks.
