### ISSUE TITLE
Compiler.compileComponentAsync

### ISSUE THREAD

**Issue by kiuka** [angular/angular#10860]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
When trying to load component dynamically via Compiler.compileComponentAsync, it does not load the providers that are defined in the module thus it ends up "No provider for HelloService" error.

Here is an example: http://plnkr.co/edit/0IALuOh4WaXSpX9zgD9v?p=preview

**Expected/desired behavior**
compileComponentAsync should load dependencies that have been declared in the module file.

I know it works if I define the provides attribute of the component's metadata, but I thought it would be the responsibility of the defined module.

**Comment by sod** [comment]
`compileComponentAsync` just compiles the component. As soon as you inject it into your app, its part of that module and not the module it came from.

You can export the providers recommended by the [NgModule documentation about shared modules](https://angular.io/docs/ts/latest/guide/ngmodule.html#!#sts=Shared%20modules) with a `forRoot` method that exports the providers. With that you can create a child injector like:

```typescript
    this.compiler.compileComponentAsync(HelloComponent, HelloModule).then((cmpFactory)=>{
      this.componentFactory = cmpFactory;
      const childInjector = ReflectiveInjector.resolveAndCreate(HelloModule.forRoot().providers, injector);
      this.viewContainerRef.createComponent(this.componentFactory, 0, childInjector);
    });
```

And you wrote `export default module HelloModule {}` instead of `export module HelloModule {}`. Thus `import {HelloModule} from '...'` returned undefined.

Plunkr: http://plnkr.co/edit/HZY9JU1gLNmERN6hrTjT?p=preview

**Comment by kiuka** [comment]
thank you very much!
