### ISSUE TITLE
cannot precompile app with ngc when extending UrlResolver

### ISSUE THREAD

**Issue by a88zach** [angular/angular#10944]
**I'm submitting a ...**
[x] bug report 

**Current behavior**
I'm extending the UrlResolver class from the @angular/compiler module to include a version querystring in order to break caching during new production builds.  When trying to precompile the application with ngc, the below error is thrown:

Error: can't find symbol _ComponentIndex exported from module C:/inetpub/repos/credentialing-web/src/node_modules/@angular/compiler/src/url_resolver.d.ts

When I remove this extended class from my project, the compiler completes successfully

**Expected/desired behavior**
ngc should compile successfully when extending the UrlResolver class from @angular/compiler

**Reproduction of the problem**
Unable to do a plunker since this problem is reproduced using a cli tool

**Please tell us about your environment:**

* **Angular version:** 2.0.0-rc.5
  
* **Language:** TypeScript 1.8.10 | ES5

**Comment by zoechi** [comment]
Please provide more details. A Plunker that allows to reproduce is usually mandatory for bug reports.

**Comment by a88zach** [comment]
As noted in the issue, I cannot supply a plunker that reproduces the issue since the issue is reproduced when using the ngc cli tool.  You cannot run a cli tool from plunker.  However, the steps to reproduce are in the bug report and can be reproduced easily

**Comment by kylecordes** [comment]
@a88zach When a plunker won't do, the typical next step upward is to provide a minimal reproduction example program as a public Github repo.

**Comment by a88zach** [comment]
https://github.com/a88zach/10944-angular-bug

npm install
npm run ngc

Once this fails, you can remove the references to the UrlResolver and run 'npm run ngc' again and it will run successfully.

**Comment by alexeagle** [comment]
That `ngc` error was fixed in https://github.com/angular/angular/commit/a7b76826a015323aa971b116c3a2fad07e0be95c so you should be able to install a snapshot from `*-builds` or wait for RC-6.

But, if you want the Ahead-of-Time compiler to use a different UrlResolver, this won't work. See here:

https://github.com/angular/angular/blob/master/modules/%40angular/compiler-cli/src/codegen.ts#L145

Basically anything you configure in Angular's dependency injection only happens when the application runs. `ngc` is based on static analysis, and doesn't run any part of your program. So at present, customizing the behavior of `ngc` requires writing your own program to call the API. For example, I needed to load templates from a different location so I changed it to accept a custom XHR (since renamed ResourceLoader):
https://github.com/angular/angular/commit/6e842fc5bf0c3cb06c964400b6cf1bf3db01e18e#diff-a31457a11185e71c354cadf582f79612

**Comment by a88zach** [comment]
Thanks for the information @alexeagle
