### ISSUE TITLE
Add support to query which component templates use a specific directive/component

### ISSUE THREAD

**Issue by Tragetaschen** [angular/angular#10940]
**I'm submitting a ...**  (check one with "x")

```
[ ] bug report => search github for a similar issue or PR before submitting
[x ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
When a directive is exported by a module instead of being part of the `directives:` of a component, it's virtually impossible to see which component templates use the directive (or might use, it could be declared and not used). Instead of doing a "Find all references" and searching those component's templates in `rc.4`, especially with re-exporting in a shared module and the orthogonality to JS modules, the search space easily grows too large to handle properly. You better had memorized the entire HTML templates…

**Expected/desired behavior**
There needs to be a proper "Find all references" to figure out which templates use a directive or instantiate a component.
- **Angular version:** 2.0.0-rc.5
#10552

**Comment by kylecordes** [comment]
The struggle on this one is that from alpha.nnn through RC.4, the TS-module-level relationships were suitable for this purpose, and thus generic TypeScript-level tooling was very helpful to understand Angular programs. These tools conveniently already exists, and we've been using them every day for over a year, in VSCode and WebStorm (and possibly others).

Starting with RC.5, such tooling to fulfill the same purpose is *possible to create* in a sufficiently advanced IDE - but it does not yet exist, and is considerably more complex, and is Angular-specific rather than useful across all TypeScript software. Ouch.

**Comment by Tragetaschen** [comment]
Since directives now easily have larger, more uncontrolled scope than before `rc.5`, another question this could answer is:

I have changed the `HighlightDirective`s attribute in the selector. Does this introduce any inadvertent instantiations of the directive where the new attribute name is also used, but for other purposes?

**Comment by alxhub** [comment]
Angular Language Service now supports "Find References" in templates!
