### ISSUE TITLE
undefined value for App module 

### ISSUE THREAD

**Issue by yboujallab** [angular/angular#10965]
I'm getting this error while starting the application after migrating to RC5 

zone.js:101GET http://localhost:4200/app.component.html 404 (Not Found)

GET http://localhost:4200/home.component.html 404 (Not Found)

I got thi error for all of my components

thanks

**Comment by manekinekko** [comment]
@yboujallab can you plz provide a plnukr or an existing repo?

**Comment by yboujallab** [comment]
thanks for the reply here is a plunkr :  
[https://plnkr.co/edit/hSj6zAd6VtJcetd4tZsc?p=catalogue](url)

**Comment by michalstepien** [comment]
@yboujallab your plunker is not correct. Attach all files or simplify plnkr. Where is system-config.js ?

**Comment by zoechi** [comment]
@yboujallab Your Plunker does not reproduce the problem. 
When run it prints `(index):24 Uncaught ReferenceError: System is not defined` to the console which is not what your issue is about.
When you create a new issue the template contains a link to a Plunker template. 
You didn't fill the issue template at all. 
If you think it is a bug please create a proper bug report. 
If it's a support request please use instead one of the channels mentioned in https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question

**Comment by yboujallab** [comment]
here's a plunkr with the same error :  

https://plnkr.co/edit/cX9OyCkBRBwcxKl4B1fH?p=preview

Is the same thing as a quickstart example. 

I got this error awhile upgarding to typings 1.0.4.

**Comment by pkozlowski-opensource** [comment]
Closing as the linked plunker is more of a dump of an application code rather than a true reproduce scenario. Happy to re-open when we can see a reproduced bug.
