### ISSUE TITLE
Factorize common util code dash <-> camel

### ISSUE THREAD

**Issue by vicb** [angular/angular#1097]
`dashCaseToCamelCase` and `camelCaseToDashCase` are duplicated:

https://github.com/angular/angular/blob/58dd75a1c8abfa8396ead9b2b1c95dc6c6558668/modules/angular2/src/core/compiler/property_setter_factory.js#L9 & https://github.com/angular/angular/blob/58dd75a1c8abfa8396ead9b2b1c95dc6c6558668/modules/angular2/src/core/compiler/pipeline/util.js

Where should be move them and short support fns in general ? 

/cc @pkozlowski-opensource @mlaval

**Comment by pkozlowski-opensource** [comment]
Oh, I'm surprised it got duplicated. Will talk with @mlaval and will send a PR tomorrow. I think that for now we should keep it compiler-private (so for example, create sth like string_utils.js in the compiler dir). Any other suggestions?

**Comment by vicb** [comment]
> we should keep it compiler-private

My first thought was to make it available outside of the compiler - together with other general purpose util functions we can come with in the future. But I have no strong opinion about it.

**Comment by pkozlowski-opensource** [comment]
So, I would prefer to keep it as part of the compiler for now due to bad memories from ng 1 where we've opened up helpers as public API and those helpers are expanding into all-purpose monsters that are doing wayyy to much for the ng internals. So this is why I would prefer to play it on the safe side this time and open up things gradually when needed. 

But I don't feel too strong about it so if others think that it makes sense to open it up as a general API I'm cool - as long as those are not exposed as public to the outside world.

**Comment by mlaval** [comment]
Oups, my intention was to keep these functions in the `util` file where they were ... I'll fix that following the ouput of this discussion.
I would favor the private solution from @pkozlowski-opensource
