### ISSUE TITLE
(bug)router/AOT Unable to use feature-modules in routing when doing AOT compilation

### ISSUE THREAD

**Issue by choeller** [angular/angular#11075]
**I'm submitting a ...**  (check one with "x")

```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
We are using Features-Modules to encapsulate things belonging together and we are using theses Features-Modules in Routing like this:

app.module.ts

``` ts
@NgModule({
  imports: [SharedModule.forRoot(),
            BrowserModule,
            RouterModule.forRoot(APP_ROUTES)
  ],
  ...
})
export class AppModule {
}

```

app.routes.ts:

``` ts
export function getTasksModule() {
  return TasksModule;
}

export const APP_ROUTES: Routes = [
  ...
  {path: 'tasks', canLoad: [LoginGuard], loadChildren: getTasksModule},
];
```

this works fine when not doing AOT. Now when calling

```
./node_modules/.bin/ngc -p ./src
```

the application compiles without errors, but in runtime I get the following exception when enterting the `/tasks` route:

``` ts
Error: Uncaught (in promise): TypeError: r.create is not a function
    at resolvePromise (zone.js:558)
    at zone.js:535
    at ZoneDelegate.invoke (zone.js:332)
    at Object.NgZoneImpl.inner.inner.fork.onInvoke (ng_zone_impl.js:41)
```

after some debugging it looks like the application get the `TasksModule` where it needs to have the `TasksModuleNgFactory`. So the exception happens in this code:

router_config_loader.ts

``` ts
  load(parentInjector: Injector, loadChildren: LoadChildren): Observable<LoadedRouterConfig> {
    return this.loadModuleFactory(loadChildren).map(r => {
      const ref = r.create(parentInjector);
      return new LoadedRouterConfig(
          flatten(ref.injector.get(ROUTES)), ref.injector, ref.componentFactoryResolver);
    });
  }
```

and r is TasksModule when the exeption occurs.

**Expected/desired behavior**

It should be possible to use loadChildren in combination with AOT

**What is the motivation / use case for changing the behavior?**

Currently it's not possible to encapsulate routing into Feature-Modules when using the AOT-compiler

**Please tell us about your environment:**
- **Angular version:** commit 2b313e49791b932634cc58cf913a8cf867671d37
- **Browser:** [all ] 
- **Language:** [all ]

**Comment by qdouble** [comment]
I just encountered this. The bug is still present using the latest builds.

**Comment by hansl** [comment]
Could you try to use a string to the module instead of a function for `loadChildren`?

Also, the CLI is broken right now until https://github.com/angular/angular/pull/11387 is in and released.

**Comment by choeller** [comment]
When trying to pass in a string angular seems to try to lazy load although I'm using webpack with a single bundle. (with my setup this fails as it's missing System.JS I think) I don't need lazy loading (nor would I know how to setup my bundles correctly ;)) so using a function to load the module worked perfectly fine for me.

**Comment by qdouble** [comment]
@hansl  how would you load it with a string? 

when I try to put something like `{ path: 'lazy', loadChildren: './features/lazy#LazyModule' }` that does't seem to work at all with webpack.

Both of the ones below work fine in JIT, but not AOT.
```
export function loadLazy() {
  return require('es6-promise!./features/lazy')('LazyModule');
}

//or

export function loadLazy() {
  return System.import('./features/lazy').then((r: any) => r.LazyModule);
}
```
Is there any current solution for us that are using Webpack 2, but not CLI?

**Comment by hansl** [comment]
@choeller it fails because it uses `System.import()`, yes, but not because you're missing `SystemJS`. `SystemJS` is a library that implements a polyfill of `System.import()`, but normally webpack is able to detect calls to it and refactor the code to use an internal webpack-specific implementation. In the current RC6 the bug is that webpack is not smart enough to detect the call to `System.import()` and leave the code as is, resulting in a real call to a non-existant `System`. 

There are many ways to fix it, but there's only 2 ways that work with the CLI:

1. using a function that manually calls `System.import()`, similar to what @qdouble posted in his second example. You could also use the first one but it's more reliant on webpack and might require more typing.
2. use a string and the nightly build of Angular which has #11387 in it.

There is a few other solutions but they're way more complicated. The truth is, when Angular RC6+1 comes around with bug fixes that bug will be fixed in Angular. Until then, you're stuck with a manual solution, at least temporarily.

**Comment by qdouble** [comment]
@hansl I'm a bit confused by your reply, it seems you are not specifically addressing the issue as it pertain to AOT. You said the export functions work are a solution, but they do not work properly in AOT mode. It compiles fine, but when you actually navigate to the route it gives the `t.create is not a function error`.

**Comment by hansl** [comment]
That's because Lazy Loading changes with AoT. You're not loading a module anymore, but a module factory.

**Comment by qdouble** [comment]
@hansl so the solution would be that we have to point to somewhere different when the module is loaded lazily? Like in JIT it'd point to `LazyModule` and in AOT we'd set it to point to `LazyModuleNgFactory`? Or is there some other workaround we need to implement?

**Comment by qdouble** [comment]
@hansl Okay, I got what you are saying now...if I point directly to the ngc generated factory, it lazy loads fine. Seems that unless you have a plugin that knows where your tsconfig output is going and that can parse your existing module, it could be a bit tedious to set both...but assuming you don't have a boat load of lazy loaded modules, doing it manually isn't torture I suppose.

**Comment by hansl** [comment]
If you use a string, the module loader will inject an `ngfactory` in the string before calling system.import. That's why you don't need to change anything in that case.

One way we've been doing AoT is by running the ngc tool ourselves and then using the cli to compile. Rob Wormald should be close to be done with integrating AoT in the CLI. That will also include code to support lazy loading.

**Comment by qdouble** [comment]
@hansl could you give me an example of `return System.import('./features/lazy').then((r: any) => r.LazyModule);` into a valid string? I'm having issues getting it to work, not quite sure how it's supposed to look.

**Comment by qdouble** [comment]
@hansl I'm assuming the format is `'./features/lazy/index#LazyModule'` however, it keeps giving me a ` Cannot find module` error even though it works with the same route works with System Import and ES6Promise... so not sure where I'm supposed to point to or if there is a problem with the format.

**Comment by kylecordes** [comment]
A working example repo showing the exact workarounds needed to see lazy loading **in action today**, would be much appreciated - even though we all know it will be obsoleted by simplification in the coming weeks as all the right fixes land in all the right releases. This would help teams who want to make sure they are structuring and arranging things now as close as possible to the A2 final form.

**Comment by Meligy** [comment]
Try this one

https://github.com/sirajc/angular2-labs/blob/master/src/app/lazy/lazy.routes.ts

Works with daily builds

Courtesy of @sirajc

**Comment by qdouble** [comment]
@Meligy  That method doesn't work in AOT. I've put a fully working example of lazy loading that will work in both AOT and JIT in my starter project repo: https://github.com/qdouble/angular2webpack2-starter/blob/master/src/app/app.routes.ts

@hansl two things blocking a simpler solution for non-cli webpack users
1) Using a string seems to result in module not found errors
2) The following bug will cause errors if you compile in the same directory: https://github.com/angular/angular/issues/11408

In my real project, there will probably be less than 10 lazy loaded modules, so my current solution isn't bad, but it would be nice to have something prettier.

**Comment by Quramy** [comment]
Hi, I've created https://github.com/Quramy/angular2-load-children-loader to make `loadChildren` work in bot AoT and JiT with webpack.
And I also I've created https://github.com/Quramy/ng2-lazy-load-demo . It's a working demonstration building with the above loader.

**Comment by bmurali31** [comment]
This bug is still there in 2.1.
Anyone had luck in lazy loading with AOT? My code is very much alike @choeller 's code.

I am using AOT with rollup and using System JS to load additional dependencies.

**Comment by qdouble** [comment]
@bmurali31 rollup does not support code-splitting, so you couldn't do lazy loading with it without some sort of rollup plugin.

I have AOT and lazy loading working fine with webpack: https://github.com/qdouble/angular-webpack2-starter/tree/minimal

**Comment by bmurali31** [comment]
Thank you @qdouble. I have a question in your webpack though.
I was expecting the feature modules/lazy modules and external modules will be a separate bundle. But in your example they are all bundled as a single file.

I ram the following
```
npm run ngc
npm run build:aot:prod
``` 
[https://github.com/qdouble/angular-webpack2-starter/issues/137](url)

**Comment by qdouble** [comment]
The lazy module is a separate file, but third party modules are bundled
together as it allows webpack to tree-shake more effectively.

**Comment by bmurali31** [comment]
Any updates on this?
It is really frustrating that JIT is very slow and there is not clear direction for AOT with lazy loading. 

My application is a decent size application with around 50 forms and each form has around 50 form fields.

**Comment by chrillewoodz** [comment]
Any updates on this? Still not working with 2.4.1

**Comment by DzmitryShylovich** [comment]
can somebody add a small repro in plunkr?

**Comment by evanjmg** [comment]
This is very important for any app going to production. Any updates on this issue?

**Comment by DzmitryShylovich** [comment]
I don't have any issues with feature modules and lazy loading. So it's probably a cli issue.

Without a repro it's not acctionable

**Comment by SamVerschueren** [comment]
It's not angular CLI specific. I never used the CLI and I have the same issues.

I created a quick example [here](https://github.com/SamVerschueren/ng2-hello-world-routing/tree/load-children).

1. `git clone https://github.com/SamVerschueren/ng2-hello-world-routing`
2. `cd ng2-hello-world-routing`
3. `git checkout load-children`
4. `npm install`

If you run `npm start`, you will notice that you can navigate from `Home` to `Contact` and back while it uses [the approach mentioned in the initial post](https://github.com/SamVerschueren/ng2-hello-world-routing/blob/load-children/app/app.routing.ts).

Now if you build it with `npm run build`, it will output a production bundle in the `builds` directory. So navigate to that directory and start a local server (`http-server`, `lite-server`, ...). Open the url and open devtools. If you click on `Contact`, it will fail to load and shows an error about [`r.create`](https://github.com/angular/angular/blob/master/modules/%40angular/router/src/router_config_loader.ts#L35) not being a function.

**Comment by DzmitryShylovich** [comment]
@samherrmann rollup doesn't support lazy loading

**Comment by SamVerschueren** [comment]
@DzmitryShylovich You pinged the wrong Sam ;).

Yes I know, but this issue isn't about lazy loading. Lazy loading happens when you use a string literal as value of the `loadChildren` property.

This issue is about passing a function that returns a module to the `loadChildren` property. For example, the [app.routing.ts](https://github.com/SamVerschueren/ng2-hello-world-routing/blob/load-children/app/app.routing.ts) from my example

```js
import { Routes, RouterModule, PreloadAllModules } from '@angular/router';

import { HomeComponent } from './home/home.component';
import { ContactModule } from './contact/contact.module';

export function loadContactModule() {
	return ContactModule;
}

export const routes: Routes = [
	{ path: '', component: HomeComponent, pathMatch: 'full' },
	{ path: 'contact', loadChildren: loadContactModule }
];

export const routing = RouterModule.forRoot(routes);
```

Everything is in one bundle. The main benefit is that every route inside the `contact` part of your application starts with `/contact` and you can easily change that.

So yes, rollup doesn't work with lazy loading but this is not about lazy loading.

**Comment by DzmitryShylovich** [comment]
> You pinged the wrong Sam ;).

sorry, github didn't suggest your name for some reason :)

**Comment by kpudlik** [comment]
+1

Using loadChildren() is the only way to follow the NgModule encapsulation conception (because it encapsulates routes too). Without using loadChildren there is a huge mess with different conventions... It should work with AoT out of the box...

**Comment by DzmitryShylovich** [comment]
You need to return `NgModuleFactory` instead of `NgModule`, because we cannot compile it at runtime (compiler is not available after aot).

Example is here https://github.com/angular/angular/pull/13909

Until pr will be merged you need to cast factory to `any`:
```
export function loadProfileModule() {
	return <any>ProfileModuleNgFactory;
}
```

You should open a feature request in cli repo to automatically convert `Type` into `NgModuleFactory` during compilation, but for build tools you need to do this manually.

**Comment by baisui1981** [comment]
@SamVerschueren i have fixed it, as u mentioned 
`import { Routes, RouterModule, PreloadAllModules } from '@angular/router';

import { HomeComponent } from './home/home.component';
import { ContactModule } from './contact/contact.module';

export function loadContactModule() {
	return ContactModule;
}
export const routes: Routes = [
	{ path: '', component: HomeComponent, pathMatch: 'full' },
	{ path: 'contact', loadChildren: loadContactModule }
];
export const routing = RouterModule.forRoot(routes);`
change the ContactModule To  ContactModuleNgFactory
`import { Routes, RouterModule, PreloadAllModules } from '@angular/router';

import { HomeComponent } from './home/home.component';
import {ContactModuleNgFactory} from "../../aot/src/user/contact.module.ngfactory";

export function loadContactModule() {
	return ContactModuleNgFactory;
}
export const routes: Routes = [
	{ path: '', component: HomeComponent, pathMatch: 'full' },
	{ path: 'contact', loadChildren: loadContactModule }
];
export const routing = RouterModule.forRoot(routes);`
in order to make aot compile success，create a new file named “app.module-aot.ts”
and also should modify the element "files" which is aot compiler entry in  "tsconfig-aot.json"
`"files": [
    "src/app.module.ts",
    "src/main.ts"
  ],
` 
to
`
"files": [
   "src/contact/contact.module.ts", 
   "src/app.module-aot.ts",
    "src/main.ts"
  ]
`
tested, that is effective
