### ISSUE TITLE
multilingual routes

### ISSUE THREAD

**Issue by istiti** [angular/angular#11135]
I wonder if Angular Router have in vision to add easy way to have multilingual routes ?
It's maybe be achieved actually but not in a good, simple and official way.
I mean this for webapp where we share link a lot times... we believe in what  is writed on url...
example:
FR: .com/user/12/edit
EN: .com/utilisateur/12/editer

I think this can be really realisable and not hard if e can named our routes and then navigate to them by their name:
` <a [routerLink]="[userEdit]">Edit user</a>`

and in our routes object simply use instant translate to fetch named routes path in different language (from json)

**Comment by vicb** [comment]
planned after final

**Comment by intellix** [comment]
Anymore information other than that it's planned? :)
Currently thinking about rewriting our fully localised ng1 application to ng2, which uses ui-router and localised URLs. We're evaluating which Router to go with. 

We currently have an object of rewrites in configuration. During configuration, we loop through registered states and replace the URL with the translated version. It's possible because the view just contains references to states: `app.promotions`

```json
"rewrites": {
  "en": {
    "/promotions": "/best-promotions",
    "/promotions/:slug": "/best-promotions/:slug"
  },
  "sv": {
    "/promotions": "/kampanjer",
    "/promotions/:slug": "/kampanjer/:slug"
  }
}
```

ng2 references URLs which are defined per module. I'm thinking this could be possible by allowing us to attach mutators during read/writing stage of URL segments. If you already have a design/idea of how this'll get implemented, we could create a PR for this ourselves.

Ideally I'd prefer to go with the official solution, but if it's planned a year from now, we've gotta go with ui-router.

**Comment by istiti** [comment]
@vicb it's final, so what is plan? can you reopen this
