### ISSUE TITLE
Overriding templates/templateUrls of components

### ISSUE THREAD

**Issue by wesleycho** [angular/angular#11144]
**I'm submitting a ...**  (check one with "x")

```
[ ] bug report => search github for a similar issue or PR before submitting
[x] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**

Currently one is not able to override templates in a component when using the AOT compiler, which creates inflexibility when one wants to override the template used in a third party library (for example).

**Expected/desired behavior**

The ability to override the template/templateUrl of a component so that the undesired template isn't compiled in for the app bundle unnecessarily.

An example of perhaps one approach, I would like the ability to do something like

``` ts
import {ComponentOverride} from '@angular/core';
import {FooComponent} from 'my-lib';

@ComponentOverride({
  template: `<div></div>`
}) FooComponent
```

**What is the motivation / use case for changing the behavior?**

See above.

In addition, this is a feature that has been highly requested by UI Bootstrap users, and will almost certainly come up with third party UI libraries on Angular 2 to avoid rigidity and to allow users to take advantage of prebuilt widgets but avoid rigidity with CSS/HTML structure. This is important for customizability.

**Comment by icfantv** [comment]
This _may_ also necessitate having the ability to mark a template as `final` (similar to the TS2 feature of being able to prevent a class from being inheritable by declaring the ctor as `private`)

**Comment by juliemr** [comment]
@vicb I don't think this is a request about testing, was that the intended label?

**Comment by vicb** [comment]
@juliemr my mistake, read too fast

**Comment by mhevery** [comment]
We have been toying with this idea in the past, but it has a lot of implications, and so such a feature is complex. We will probably revisit this past final.

**Comment by fernandocode** [comment]
That's exactly what I would like to submit [this issue](https://github.com/angular/angular/issues/7968). Being able to inherit and replace templateUrl, selector, styleUrl, etc. thus facilitating the customization of third-party components. Because at some point if you need something custom for a third component of what you will do? That would be the best solution in my view, if not the only acceptable!

Then I consider that the angular2 team should better assess this constant request of the community, as this is not only an extra feature but a necessity for real projects.

I consider even the angular2 should not be placed in the final version with problems like this are neither considered in the development plans.

To emphasize how this is a community request. Follow the amount  👍 in [closed request issue](https://github.com/angular/angular/issues/7968) (in my understanding arbitrarily) unsolved forecast. And 🆙 in [my question on the same SO](http://stackoverflow.com/q/36475626/2290538).

**Comment by listepo** [comment]
Hi, any news?

**Comment by jayankaghosh** [comment]
Any updates on this?

**Comment by crishn** [comment]
Hi, what is the news?

**Comment by londomloto** [comment]
it's been almost 5 years

**Comment by petebacondarwin** [comment]
We are about to start trialling a new approach to prioritising features where we look at the number of upvotes on such issues (on the original description only). Given that this one has 52 already it would be considered fairly high. This process should help us to triage the very large number of such feature requests, which has in the past been overwhelming.

Give us a little while to get this process up and running and hopefully we can give some news here.

**Comment by fernandocode** [comment]
> We are about to start trialling a new approach to prioritising features where we look at the number of upvotes on such issues (on the original description only). Given that this one has 52 already it would be considered fairly high. This process should help us to triage the very large number of such feature requests, which has in the past been overwhelming.
> 
> Give us a little while to get this process up and running and hopefully we can give some news here.

@petebacondarwin As I believe that only what is open at the moment will be considered. If you can consider [this similarly closed request that is related to this one](https://github.com/angular/angular/issues/7968), only that it deals with the override more broadly, involving styles, selector, etc., not only the template, there are 144 more votes, which puts this on top

**Comment by petebacondarwin** [comment]
Sadly I think that trying to aggregate votes from related closed issues will be too much for the process. Instead I would encourage people following along to add votes to open issues.

**Comment by alxhub** [comment]
I'm going to close this FR, as the feature described is generally supported by the component extension model, as much as is technically possible.

### Changing a template breaks the encapsulation model

In Angular, components are a self-contained union of a template + a model (logic for driving the template). The component class is free to make as many assumptions as it wants about the structure of the template, and the template is free to make as many assumptions about the logic in the component class as it wants.

Therefore, changing the template of a component, whether by extension or through some kind of runtime "override", is necessarily a "privileged" operation. If the component does not support such usage, the component author might make internal changes in the component class which breaks the new template. If a component _does_ want to support such usage, this needs to be clearly documented in its contract. This is a similar requirement to those faced by classes in Object Oriented Programming around extension - base classes must be designed to be extensible.

Furthermore, overriding a component's template would override it for _all_ consumers, some of which might not be expecting the component to behave or look differently.

### Extension provides a straightforward solution

Given the requirement that the base component already be designed with this kind of overriding in mind, a natural solution to this problem is to allow a consumer to derive from the "base" component and override the template that way:

```typescript
import {BaseCmp} from 'my-lib';

@Component({
  template: '<span>Specific Template</span>',
  selector: '...',
})
export class DerivedCmp extends BaseCmp {}
```

The component can provide and document whatever requirements and APIs internally are necessary to support third-party templates. Depending on requirements, `BaseCmp` could even be implemented as a template-less `Directive` instead.

### Doing this in a tree-shakeable way is not possible

If a template overriding API exists that functions at runtime, then the base class including its template will necessarily have been included into the bundle already, defeating tree-shaking.

A compile-time overriding API is not possible due to Angular's compilation model, where libraries are processed and compiled in separate compilations compared to the application. This was a firm requirement of the Ivy architecture, for significantly faster incremental builds and a much simpler build integration. Thus, when compiling the consumer, the compilation of the input component is effectively fixed.
