### ISSUE TITLE
It seems that ng-content replacement does not work for elements selected by element name, after RC6

### ISSUE THREAD

**Issue by Eduardo-M-Cavalcanti** [angular/angular#11251]
```
[x ] bug report
```

**Current behavior**
It seems that ng-content replacement behaviour is broken on RC-6 for elements selected by element name, for example:
```
<ng-content select="element-name"></ng-content>
```
But works for 
```
<ng-content select=".class-name"></ng-content>
```
Sample error message:
```
'modal-content' is not a known element:
1. If 'modal-content' is an Angular component, then verify that it is part of this module.
2. If 'modal-content' is a Web Component then add "CUSTOM_ELEMENTS_SCHEMA" to the '@NgModule.schema' of this component to suppress this message. ("-modal title="Incluir grupo econômico" #addCustGroupDialog [approve]="approveNewCustomerGroup">
    [ERROR ->]<modal-content>
      <div class="ui fluid input">
        <input class="ui input" type="text" [(ngMo"): CustomerGroups@6:4
```

**Expected/desired behavior**
Normal behaviour verified before RC6.
As described in this article:
https://toddmotto.com/transclusion-in-angular-2-with-ng-content

**Reproduction of the problem**
If the current behavior is a bug or you can illustrate your feature request better with an example, please provide the steps to reproduce and if possible a minimal demo of the problem via https://plnkr.co or similar (you can use this template as a starting point: http://plnkr.co/edit/tpl:AvJOMERrnz94ekVua0u5).

**What is the expected behavior?**
Normal behaviour verified before RC6.

**What is the motivation / use case for changing the behavior?**

**Please tell us about your environment:**

* **Angular version:** 2.0.0-rc.6
 
* **Browser:** [Chrome 52, Firefox 48.0.2] 
 
* **Language:** [TypeScript]

**Comment by Eduardo-M-Cavalcanti** [comment]
The application has already been migrated into using NgModules.

**Comment by vicb** [comment]
Seems like your errors is:

```
'modal-content' is not a known element:
1. If 'modal-content' is an Angular component, then verify that it is part of this module.
2. If 'modal-content' is a Web Component then add "CUSTOM_ELEMENTS_SCHEMA" to the '@NgModule.schema' of this component to suppress this message. ("-modal title="Incluir grupo econômico" #addCustGroupDialog [approve]="approveNewCustomerGroup">
    [ERROR ->]<modal-content>
      <div class="ui fluid input">
        <input class="ui input" type="text" [(ngMo"): CustomerGroups@6:4
```

if `<modal-content>` is an angular cmp, is should be in your test modules `includes`

**Comment by Eduardo-M-Cavalcanti** [comment]
Please see this plunker:
https://plnkr.co/edit/K1UYuVEMyxmMIhmWz4nl?p=preview

And the role of the elements "my-component-title" and "my-component-content". They have the same role of "modal-content".

"modal-content" is not the component. It is the name of an element to be "transcluded".

**Comment by vicb** [comment]
May be I don't understand your question and your plunker bu still I think I have the right answer.

**Comment by AnimaMundi** [comment]
I am having the same issue.
`model-content` is NOT a component, it is supposed to act as a DOM node selector for its content to be transcluded into the component.

**Comment by vicb** [comment]
Sorry I'm a bit in a rush, I could probably have been clearer before.

The error is due to the fact that `<modal-content>` is not a known element - starting with RC6 Angular2 enforces that tags name are valid:
- valid html tags,
- Angular components or directives,
- Element declared in your `NgModule` `schemas` prop - support is rather limited for now and this mostly offer a all or nothing filter. It will be improve in the next releases.

The most simple solution is to create a "fake" directive so that your element is allowed:

```ts
@Directive({selector: 'modal-content'})
export class ModalContent {
  // No behavior
  // The only purpose is to "declare" the tag in Angular2 
}
```

Then you should add this directive to your module and you're good to go.

Hope this helps (more).

**Comment by AnimaMundi** [comment]
Thanks, that's a lot clearer.
It would be nice if we could define the custom node selectors that we are expecting within the component like we would have with the transclude property in Angular 1.

**Comment by wardbell** [comment]
I don't think we can call it a "bug" because Angular is working as intended and performing a valuable service by catching what is usually an error ... the use of an unrecognized element in an Angular component template.

Angular offers several ways to let the compiler know that your apparent error is intentional.  Victor mentioned one of them. There are two others, including the `CUSTOM_ELEMENTS_SCHEMA` approach mentioned in the error message.

I found this to be an interesting subject and wrote a [plunker that explores these three options](http://plnkr.co/edit/ye5NGXW6ZnyY4E0q5hBK?p=info). 

HTH

**Comment by vytautas-pranskunas-** [comment]
Yes but it feels like useless configuration

**Comment by wardbell** [comment]
I don't see it that way. Guarding against a common error is worth a small price for your use case which is (a) rare by comparison to the common error, (b) requires very little configuration to overcome, (c) has the virtue of being explicit.

Be honest ... how troublesome are these three lines that Victor suggested
```
@Directive({selector: 'my-component-title'}) class MyComponentTitle { }

@Directive({selector: 'my-component-content'}) class MyComponentContent { }

export const MY_COMPONENT_DIRECTIVES = [ MyComponent, MyComponentContent, MyComponentTitle ];
```
How many of these kinds of projected classes do you really have?

**Comment by vytautas-pranskunas-** [comment]
Less code to configure - better, why to have code that does nothing. I agree that validating tag is good thing, but ng-content kind of different thing. Feels like over-engineering. More tricky things to learn - more complex framework becomes. Complex framework suited for complex software this means less developers will use it.

**Comment by wardbell** [comment]
I suppose the compiler could see the `<ng-content select="X"...>` and let the 'X` tags through the element check.

That seems plausible. Maybe we should consider that idea.

**Comment by vytautas-pranskunas-** [comment]
This would be nice :)

**Comment by sylvainpolletvillard** [comment]
I just got the same issue. The fake directive workaround is not ideal: these elements are not directives and can't be used as directives, which confused my teammates. I was expecting ng-content to add these custom tag selectors to known tags. I'll go with the CUSTOM_ELEMENTS_SCHEMA approach for now.

**Comment by vicb** [comment]
> Less code to configure - better, why to have code that does nothing.

This is temporary. In a (near) future modules will be able to declare a finer grained schema 

> I suppose the compiler could see the <ng-content select="X"...> and let the 'X` tags through the element check when used in that context (and that context only).

No. We can discuss in more details later, OOO today.

**Comment by wardbell** [comment]
Thanks @vicb!

Actually, the whole problem can be easily avoided if you use class selector instead of element tags to denote the projected content. This is my favorite solution and requires NO changes and NO configuration.

You simply have to be willing to change your technique very slightly. I cannot imagine why this would be objectionable.

I updated the [plunker to demonstrate](http://plnkr.co/edit/ye5NGXW6ZnyY4E0q5hBK?p=info)

For convenience, the key class changes are here:
```
// USE A CLASS SELECTOR INSTEAD OF ELEMENT SELECTOR
@Component({
  selector: 'my-app',
  template: `
    <h2>Enabling Arbitrary Element Tags</h2>
    <my-component2>
      <div class="component-title">
        This is the Component2 title!
      </div>
      <div class="component-content">
        And here's some awesome Component2 content.
      </div>
    </my-component2>
  `
})
export class AppComponent2 { }

// Use div.class selector instead of element tag.
// Projects content in divs with special class names
// into two matching named <ng-content> slots
// The class names are part of the selectors.
@Component({
  selector: 'my-component2',
  template: `
    <div class="my-component">
      <div>
        Title:
        <ng-content select="div.component-title"></ng-content>
      </div>
      <hr>
      <div>
        Content:
        <ng-content select="div.component-content"></ng-content>
      </div>
    </div>
  `
})
export class MyComponent2 { }
```

**Comment by sylvainpolletvillard** [comment]
@wardbell : using custom elements is a way to ensure CSS isolation on the host element, and emphasises transcluded content in the templates.

**Comment by wardbell** [comment]
@sylvainpolletvillard 
You are not selling me:
1. Custom Element Tag isolation is at least as important as CSS isolation
1. You achieve the equivalent of CSS isolation by virtue of the NgModule declaration boundary that limits the effect of these classes to the range of the component itself
1. I don't know what "emphasises transcluded content in the templates" means or why I should care.

To me and most of the world there is no substantive difference between `.component-content` and `component-content`.

Speaking as ME, not the Angular team, I think you're making a mountain out of a mole hill.  To make a real case you'd have to show tangible consequences ... not wave abstractions around.  Show me that something bad happens and I listen. Lecture me about "isolation" and "emphatic transclusion" and you lose my attention.  I don't think I am alone in this respect.

**Comment by sylvainpolletvillard** [comment]
I'm not worried about classes impacting styles outside the component. I'm concerned about external CSS rules set on tag names and impacting styles _inside_ the component. It's quite common to have rules such as `parent-component div { ... }`. This is not something that NgModule can prevent as far as I know.

And no, *with all due respect*, "just switch to classes" is not an acceptable option for everyone. Almost all the articles about ng-content uses custom elements in their examples, so the users do. Some popular open source components rely on it too. You can't tell all these people to change their API because RC6 does not cover this (basic) case. 

The other workarounds you proposed are much more helpful, yet not totally satisfying. There is still an issue to be solved here, so we'll just have to wait for the improvements on `NgModule schemas`.

**Comment by AnimaMundi** [comment]
Wow strong opinions @wardbell ...
To assume everyone else would agree with you is dangerous, in any context.

Personally, I don't like the use of CSS classes for transcluding content because simply put... CSS classes are CSS classes, they are for applying styles. Using them for anything else hurts the readability of the code, and as developers we have a duty to speak to other developers through our code and not just to the Angular compiler.

From this point of view, custom tag elements is a better solution but not optimal. In my opinion, adding an directive for the parent component that would pair with the existing directive for the child component would offer the best readability.

``` javascript
@Component({
  selector: 'my-app',
  template: `
    <h2>Enabling Arbitrary Element Tags</h2>
    <my-component2>
      <ng-content select="component-title">
        This is the Component2 title!
      </ng-content>
      <ng-content select="component-content">
        And here's some awesome Component2 content.
      </ng-content>
    </my-component2>
  `
})
export class AppComponent2 { }

@Component({
  selector: 'my-component2',
  template: `
    <div class="my-component">
      <div>
        Title:
        <ng-content select="component-title"></ng-content>
      </div>
      <hr>
      <div>
        Content:
        <ng-content select="component-content"></ng-content>
      </div>
    </div>
  `
})
export class MyComponent2 { }
```

Now when someone else sees this code, they will know straight away that this is content that will be transcluded into the child component. Whereas if they are CSS selectors then their first instinct will probably be to look for matching CSS classes, and if they are custom element tags then the first instinct will probably to look for matching components.

**Comment by AnimaMundi** [comment]
As for the empty directives solution, using non-attribute level selectors for directives goes against the style guide. Element level selectors are to be used for components only.
Empty directives as a solution on it's own is very hacky, packaged with hurting consistency in your code's style - it is just not a valid solution.

Using the CUSTOM_ELEMENTS_SCHEMA ruins the whole point of Angular adding the extremely valuable feature that caused this issue in the first place.

**Comment by cpamp21** [comment]
I have a decent solution, use this selector:
`select="[my-selector]"`
Then as a transclude just use your selector as a directive:
`<div my-selector>Content</div>`

This way Angular does not complain and the content loads.

**Comment by Blackbaud-PaulCrowder** [comment]
I'd also like to see this fixed.  I have two reasons for using element selectors for my transclusion locations, both of which I believe are valid:

1. The semantic nature of the markup makes it very easy to understand (or "reason about" as all the cool kids say these days).  The child elements match the parent elements and it's obvious they go together and that they are hierarchical.  For example, this:

```
<my-tile>
  <my-tile-header>Header</my-tile-header>
  <my-tile-content>Content</my-tile-content>
</my-tile>
```

is much more intuitive and easier to document than this:

```
<my-tile>
  <div class="my-tile-header">Header</div>
  <div class="my-tile-content">Content</div>
</my-tile>
```

2. While these elements aren't components today, they may very well be components tomorrow.  If they're already custom elements then I can do that without the consumers of my open source component library even caring about it. If they use CSS classes then I either have to get everybody using the library to change their code or end up with a component library with half of its components using element selectors and the other half using CSS selectors, making the API very confusing.

**Comment by kylecordes** [comment]
I had the same issue about updating our curriculum. There is a certain clarity that comes from using element names as content targets, I think it would be great if there is a slightly easier way to support that in the future. In the meantime the provided workaround by adding an empty directive works fine.

**Comment by supermarcos** [comment]
I totally agree with @AnimaMundi. CSS classes are for styling, not for Angular2 transpilation, those are two very different things.
IMHO, this is a (huge) step backwards and I would love seeing it fixed.

**Comment by vicb** [comment]
@supermarcos as already said, this is planned and they are multiple ways (pseudo Directive, schemas) to use any element names.

IMO, this is a huge step forward as:
- it allows to catch typos in the element names,
- it allows to catch missing imports in your `@NgModule`.
