### ISSUE TITLE
Dependency injection not working for custom RequestOptions class when making a post request to remote url

### ISSUE THREAD

**Issue by ChrisMurphy** [angular/angular#11423]
**I'm submitting a ...**  (check one with "x")

```
[x ] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**

I have a CustomRequestOptions class that extends the RequestOptions class which I want to be injected with some values from a config class that I need for customising the headers and request URL etc. This is working fine with GET requests but when I come to do a POST request I am experiencing some unexpected behaviour. The api I am calling is on a different domain so CORS browser policy is issuing a pre-flight OPTIONS request which is expected but the RequestOptions code is kicking in twice and dependency injection of the config does not work when my POST request is actually executed (the second time the RequestOptions code kicks in.. 

**Expected/desired behavior**

I am expecting to be able to dependency inject an extended RequestOptions class when making a POST request. As to whether the RequestOptions should be called twice I am unsure what the teams desired behaviour is..

**Reproduction of the problem**
If the current behavior is a bug or you can illustrate your feature request better with an example, please provide the steps to reproduce and if possible a minimal demo of the problem via https://plnkr.co or similar (you can use this template as a starting point: http://plnkr.co/edit/tpl:AvJOMERrnz94ekVua0u5).

Reproduction is here: http://plnkr.co/edit/Bcr0RfJIf65TXOkgwgs2 see console log for outputs.

**Please tell us about your environment:**
- **Angular version:** 2.0.0-rc.6
- **Browser:** [all ] 
- **Language:** [ TypeScript 2.0 ] 

Cross ref: http://stackoverflow.com/questions/39359060/angular2-rc6-custom-requestoption-behaviour-when-cors-post-request

**Comment by DzmitryShylovich** [comment]
Does it still an issue after 2.0?

**Comment by ChrisMurphy** [comment]
Yes I have tried this with 2.1.1 using the same code in a cli (beta 18) project and the result is the same.

**Comment by DzmitryShylovich** [comment]
@ChrisMurphy can u provide a small repro using the latest angular?

**Comment by mattheiler** [comment]
This issue is caused by the `RequestOptions.merge()` method - it creates a new instance of type `RequestOptions`, rather than the injected type. The `Http` service calls this method when merging options for the POST, PUT, and PATCH methods. IMO, either make `RequestOptions` follow the prototype pattern, or remove that `RequestOptions.merge()` and change the POST, PUT, and PATCH methods in the `Http` service.

**Comment by mattheiler** [comment]
Alternatively, in `Http`, refactor PUT, PATCH, and POST, merging the default options parameters with the options parameters, rather than default options property, for example...

`put(url: string, body: any, options?: RequestOptionsArgs): Observable<Response> {`
`return this.request(new Request(mergeOptions(this._defaultOptions.merge(new RequestOptions({body: body})), options, RequestMethod.Put, url)));`
  `}`

_becomes..._

`put(url: string, body: any, options?: RequestOptionsArgs): Observable<Response> {`
`return this.request(new Request(mergeOptions(this._defaultOptions, new RequestOptions({ body: body }).merge(options), RequestMethod.Put, url)));`
 `}`

This more closely follows the pattern used in the working request overloads.

**Comment by DzmitryShylovich** [comment]
@mattheiler could u add a small plunker?

**Comment by mattheiler** [comment]
The plunkr provided by @ChrisMurphy is exactly what I'd provide, aside from a different `merge` implementation on `CustomRequestOptions`.

Look at the `AppModule` providers.

```
providers: [
    { provide: Config, useFactory: () => new Config('someValue', 'anotherValue') },
    { provide: RequestOptions, useClass: CustomRequestOptions, deps: [ Config ] }
]
```

I would expect the `RequestOptions` injected into the `Http` service is preserved -- or cloned -- during the merge process, so that the correct merge implementation is executed.

**Comment by DzmitryShylovich** [comment]
> The plunkr provided by @ChrisMurphy is exactly what I'd provide

it doesn't work

**Comment by mattheiler** [comment]
That would be a problem. Hold on a tick, I'll throw one together.

**Comment by mattheiler** [comment]
This should do it...
https://plnkr.co/edit/WMLNTB2Sv3UlJFDfg1qU?p=preview

**Comment by DzmitryShylovich** [comment]
@mattheiler thx. Will have a look.

**Comment by mattheiler** [comment]
I think what we're look for is to extract the property assignment from the merge, so that we can make a proper clone in the merge override.

Private methods like `_mergeSearchParams` are preventing us from do so.

```
export class RequestOptions {

    ...

    // new
    protected assign(target: RequestOptions, options?: RequestOptionsArgs): RequestOptions {

        target.method = options && options.method != null ? options.method : this.method;
        target.headers = options && options.headers != null ? options.headers : new Headers(this.headers);
        target.body = options && options.body != null ? options.body : this.body;
        target.url = options && options.url != null ? options.url : this.url;
        target.params = options && this._mergeSearchParams(options.params || options.search);
        target.withCredentials = options && options.withCredentials != null ? options.withCredentials : this.withCredentials;
        target.responseType = options && options.responseType != null ? options.responseType : this.responseType;

        return target;
    }

    // refactor
    merge(options?: RequestOptionsArgs): RequestOptions {
        return this.assign(new RequestOptions(), options);
    }

}

export class CustomRequestOptions extends BaseRequestOptions {

    private doThing(options?: RequestOptionsArgs): RequestOptionsArgs {
        return options;
    }

    merge(options?: RequestOptionsArgs): CustomRequestOptions {
        return this.assign(new CustomRequestOptions(), this.doThing(super.merge(options)));
    }

}
```

**Comment by DzmitryShylovich** [comment]
@mattheiler doesn't https://github.com/angular/angular/pull/13598/files#diff-136de8f15d596724aea913dcba575d2aR122 fix the issue?

**Comment by mattheiler** [comment]
It didn't fix my plnkr, no.

However, I'm thinking that the way the `RequestionOptions` is created is what's confusing for consumers and myself. I'm not so sure it should be a class method - something to be overridden. I see it as something like [Object.assign()](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object/assign).

I'd suggest making the merge method static and doing an assignment for each source to the target.
`RequestOptions.merge(target:RequestOptionsArgs, ...sources:RequestOptions[])`

To be used like in the following:
```
var options = RequestOptions.merge(/* new object */ { }, this._defaultOptions, options, { body: body, url: url });
return this.request(new Request(options));
```

The current implementation creates a new instance in the merge method of the default options instance and allows the merge method to be overridden, which again is the source of this issue.
```
return this.request(new Request(this._defaultOptions.merge(options)))
```

The implementation could then be a proper merge, rather than a factory-type method.

**Comment by mattheiler** [comment]
So, I think merge causes confusion more than this is an issue.

**Comment by mattheiler** [comment]
So, untested, but here's the idea...

```
export class RequestOptions {
    ...
    static merge(target: RequestOptionsArgs, ...sources: RequestOptionsArgs[]) : RequestOptionsArgs {
        for (let source of sources) {
            target.method = source.method;
            target.headers = source.headers;
            target.body = source.body;
            target.url = source.url;
            target.params = URLSearchParams.merge(target.params || new URLSearchParams(), source.params);
            target.withCredentials = source.withCredentials;
	    target.responseType = source.responseType;
    	}
  	return target;
    }
}
```

Which is more like a merge than the current implementation...

```
export class RequestOptions {
    ...
    merge(options?: RequestOptionsArgs): RequestOptions {
        return new RequestOptions({
            method: options && options.method != null ? options.method : this.method,
            headers: options && options.headers != null ? options.headers : new Headers(this.headers),
            body: options && options.body != null ? options.body : this.body,
            url: options && options.url != null ? options.url : this.url,
            params: options && this._mergeSearchParams(options.params || options.search),
            withCredentials: options && options.withCredentials != null ? options.withCredentials :
                                                                    this.withCredentials,
            responseType: options && options.responseType != null ? options.responseType :
                                                              this.responseType
        });
    }
}
```

**Comment by DzmitryShylovich** [comment]
So basically u want the ability to override [this](https://github.com/angular/angular/blob/master/modules/%40angular/http/src/http.ts#L21) method. I don't like this idea. it's already too much unnecessary coping and merging.

> The current implementation creates a new instance in the merge method of the default options instance and allows the merge method to be overridden, which again is the source of this issue
`return this.request(new Request(this._defaultOptions.merge(options)))`

but u use 
```
var expected = host + this.http['_defaultOptions'].merge({ url: url }).url;
```
as expected behavior. so it's not expected?

**Comment by DzmitryShylovich** [comment]
I don't understand why u want another `merge` method. With implementation like
```
return this.request(new Request(this._defaultOptions.merge(options)))
```
u have full control and u can override `merge` method like u want and return want u want.

**Comment by mattheiler** [comment]
No, @ChrisMurphy and I wanted to override [this](https://github.com/angular/angular/blob/master/modules/%40angular/http/src/base_request_options.ts#L121) method. I now realize that we were wrong to do that. I'm now arguing that method should not be exposed or therefore overridden. We can call this a non-issue or hide/staticize that method. It's not merging, it's creating and returning a new object that didn't have the implementation we provided, which was the source of this "issue".

**Comment by mattheiler** [comment]
Merge seems like it should be a utility rather than behavior. To get what I had wanted, I'd have to override merge like this:
```
@Injectable()
export class CustomRequestOptions extends BaseRequestOptions {

    ...

    merge(args: RequestOptionsArgs): CustomRequestOptions {

        var options = super.merge(args);

        var element = document.getElementsByTagName('base').item(0);
        if (element != null)
            options.url = element.href + (options.url || '');

        var clone = new CustomRequestOptions();
 
        // i can't return the result of super.merge(), since it is a new instance of the wrong type
        // i have to re-map everything
        // consumers shouldn't have to babysit this mapping...
        // we seem to be mixing cloning with merging

        clone.body = options.body;
        clone.headers = options.headers;
        clone.method = options.method;
        clone.responseType = options.responseType;
        clone.search = options.search;
        clone.url = options.url;
        clone.withCredentials = options.withCredentials;

        return clone;
    }

}
```

**Comment by DzmitryShylovich** [comment]
> export class CustomRequestOptions extends BaseRequestOptions

nobody forces u to extend BaseRequestOptions. 
Extend RequestOptions and do want you want inside merge. I don't get your point.

**Comment by mattheiler** [comment]
My point is that merge doesn't merge, it creates - it's a factory. It's not working as I expected and I only understood why after digging into the code. I'd expect it to work like [Object.assign()](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object/assign). I think the issue here is that the purpose of that function is confusing, because of the way it's defined. It should be in a utility and not exposed as a class-level function, in my opinion. Do with it what you want.

**Comment by haia212** [comment]
@mattheiler I am having the same issue and came to the same conclusion. How did you workaround this issue ?
@DzmitryShylovich what would be the (angular) way to change an http header ?

**Comment by mattheiler** [comment]
@haia212 I created an adapter.

```
import { Injectable } from '@angular/core';
import { Http, Request, RequestOptions, RequestOptionsArgs, Response } from '@angular/http';

import { Observable } from 'rxjs/Observable';

@Injectable()
export class HttpGateway {

    constructor(private http: Http) { }

    protected getUrl(url: string | Request): string {
        var element = document.getElementsByTagName('base').item(0);
        var prefix = element != null ? element.href : '';

        if (typeof url === 'string')
            return prefix + url;

        if (url instanceof Request)
            return prefix + url.url;

        console.log(prefix);

        throw new Error('url out of range');
    }

    request(url: string | Request, options?: RequestOptionsArgs): Observable<Response> {
        return this.http.request(this.getUrl(url), options);
    }

    get(url: string, options?: RequestOptionsArgs): Observable<Response> {
        return this.http.get(this.getUrl(url), options);
    }

    post(url: string, body: any, options?: RequestOptionsArgs): Observable<Response> {
        return this.http.post(this.getUrl(url), body, options);
    }

    put(url: string, body: any, options?: RequestOptionsArgs): Observable<Response> {
        return this.http.put(this.getUrl(url), body, options);
    }

    delete(url: string, options?: RequestOptionsArgs): Observable<Response> {
        return this.http.delete(this.getUrl(url), options);
    }

    patch(url: string, body: any, options?: RequestOptionsArgs): Observable<Response> {
        return this.http.patch(this.getUrl(url), body, options);
    }

    head(url: string, options?: RequestOptionsArgs): Observable<Response> {
        return this.http.head(this.getUrl(url), options);
    }

    options(url: string, options?: RequestOptionsArgs): Observable<Response> {
        return this.http.options(this.getUrl(url), options);
    }

}
```

**Comment by alxhub** [comment]
Overriding `merge` in `RequestOptions` is not a supported usage of the API. There will be a much better way of manipulating request options in upcoming HTTP APIs (interceptors).
