### ISSUE TITLE
Angular2- RC6 Custom Form Controls not working

### ISSUE THREAD

**Issue by ahmadqarshi** [angular/angular#11479]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**

After updating the Angular2 application from RC5 to RC6, custom form controls stopped working. The value entered in the custom form control is not reflected in the associated model. 

**Expected behavior**

The associated model should reflect the value entered/selected in the custom control.

**Reproduction of the problem**
I have used the plunker created by Thoughtram for Custom Forms Control. You can find the plunker at https://plnkr.co/edit/bLXWXn

This plunker is using RC5. To reproduce the issue please update the version information in the systemjs.config.js is to 

var ngVer = '@2.0.0-rc.6'; 
var routerVer = '@3.0.0-rc.2'; 
var formsVer = '@2.0.0-rc.6';

You will see that the selected value in the control is not reflected.

A question is already posted on StackOverflow http://stackoverflow.com/questions/39408419/angular2-rc6-custom-form-controls-not-working

**What is the motivation / use case for changing the behavior?**

**Please tell us about your environment:**

* **Angular version:** 2.0.0-rc.6
 
* **Browser:** [ Chrome 52.0.2743.116 m] 
 
* **Language:** [TypeScript 1.8 | ES6]

**Comment by VirrageS** [comment]
I have noticed that `registerOnChange` is fired twice in RC.6 wheras in RC.5 only once. This is connected with new code added in RC.6 starting from: https://github.com/angular/angular/blob/d2ad871279c410334314def0be5c5d0599f4368e/modules/%40angular/forms/src/directives/shared.ts#L68

Firstly, you assign proper function to `propagateChange` (same as RC.5) but then new code is firing `registerOnChange` again with another function which you assign again and then you are using wrong function as `propagateChange`.

Here is simple workaround (only for presentation purposes): https://plnkr.co/edit/MoSFkJPFdWP0fFyLyoZO?p=preview
But I believe that there is something wrong with new code.

**Comment by pkozlowski-opensource** [comment]
This is a side effect of d2ad871279c410334314def0be5c5d0599f4368e. After this change both `Validator` _and_ `ControlValueAccessor` have the same method in their interfaces (`registerOnChange`). Since the `CounterInputComponent` implements both `Validator` and `ControlValueAccessor` the `registerOnChange` method is called twice and the internal state gets messed up.

IMO the situation where we want to implement `Validator` and `ControlValueAccessor` on the same class is not that uncommon so it might be a good idea to rename one of the methods (`registerValidatorChange` ?). Unfortunately this would be a BC at this point....

A proper work-around for this case is to implement `Validator` and `ControlValueAccessor` on separate classes.

**Comment by kara** [comment]
Yeah, the naming of the two methods should be distinct because that's a common use case. On it.
