### ISSUE TITLE
Get hold of the currently relevant Module for Dynamic Component generation

### ISSUE THREAD

**Issue by simon-sharp** [angular/angular#11626]
**I'm submitting a ...**  (check one with "x")

```
[ ] bug report => search github for a similar issue or PR before submitting
[ x ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior** 
If I would like to generate a dynamic Component in the current version (RC6) I need to write a specific Module for the component, re-declare all components and dependencies and then load this Module with compiler.compileModuleAsync(NewModule). This is an overhead because the components are or might be already declared in the module that I am currently working in. As described in issue "https://github.com/angular/angular/issues/11277" I understand why this separation between Module and Component is necessary and can not be avoided. It's a good and necessary thing.

**Expected behavior**
When I look at the loading mechanism for a component in detail the class that I need from the module is a ModuleInjector.

```
this.compiler.compileModuleAsync(dynamicModule).then(
      factory => {
        let moduleInjector: any = factory.create(this.injector);
        this.component = this.dynComp.createComponent(moduleInjector.componentFactoryResolver.resolveComponentFactory(this.dynamicComponent));
        this.bindVariables();
      }
    );
```

and reduce it to this

```
this.component = this.dynComp.createComponent(loadModuleInjectorFromCurrentModule().componentFactoryResolver.resolveComponentFactory(this.dynamicComponent));
```

The ModuleInjector allows access to the ComponentFactories that then allow the generation of a dynamic component.

Technically the generation of a new Module over compiler.compileModuleAsync is not necessary if I could get hold of the Module or ModuleInjector that my class is currently operating in.

So the request is to provide a way to get hold of the current Module or ModuleInjector.

Components could be listed once (where they belong) and the overhead of generating a module for each component could be avoided. A way to do that could also be to save and load a module by name within a newly defined class.

**What is the motivation / use case for changing the behavior?**
It would make the generation of dynamic components very easy. IgorMinar describes the current procedure as much more difficult then before.
- **Angular version:** 2.0.0-rc.6
- **Browser:** [all] 
- **Language:** [all]

**Comment by DzmitryShylovich** [comment]
@cmiagssh is this still an issue? afaik compilation is sync now

**Comment by cmiagssh** [comment]
@DzmitryShylovich I assume this decision has been taken in the angular team.

We changed our project to run correctly. On the other hand it would save a lot of typing if you could load components from your current module without redeclaring the module.

**Comment by DzmitryShylovich** [comment]
@cmiagssh can you update the description with the new api?

**Comment by JoostK** [comment]
It is indeed true that dynamic component creation in Angular today does require the creation of an NgModule that declares that component, as the NgModule is responsible for providing the compilation scope for all its declarations. As far as the current module is concerned (assuming that current module means the closest `NgModuleRef` instance as provided by the DI system) any dynamically created component is not also declared in that current NgModule, hence the component doesn't get access to the NgModule's compilation scope.

Since Ivy, it has actually been possible to obtain a `ComponentFactory` from an `ComponentFactoryResolver` from an `NgModuleRef` that did not declare said component. Still, a dedicated NgModule would still be required to associate a compilation scope with that component, even in Ivy.

We are currently researching the ability to let components declare their own compilation scope, such that they become _standalone components_. without an owning NgModule This is still being experimented with and the outcome is not yet clear. This will be presented in an RFC when the time is right. Next, the concepts of _component factories_ and the like are being revisited as they are no longer required in Ivy.
