### ISSUE TITLE
Router: CanDeactivate guard doesn't fire on changing parent segment

### ISSUE THREAD

**Issue by aboris0v** [angular/angular#11664]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior** 
Having following routes 
export const routes: Routes = [
       .........
	path: 'order/:id', component: ExistingOrderComponent,
	children: [
		{ path: '', redirectTo: 'summary', pathMatch: 'full' },
		{ path: 'summary', component: SummaryComponent},
		{ path: 'edit', component: EditComponent, canDeactivate: [CanDeactivateGuard]	}
];
CanDeactivateGuard is being activated on changing route between children nodes (eg: order/1/edit -> order/1/summary), but it doesn't when parent is changed (eg: order/1/edit -> order/2/edit)

**Expected behavior**
I think that CanDeactivateGuard set on a children segment has to be fired when its parent segment is changed and as it seems to me it has to be fired before parent's guard (if specified)

**Reproduction of the problem**
demo of the problem is here http://plnkr.co/edit/4TT1iC?p=preview

* **Angular version:** 2.0.0 and below

**Comment by vsavkin** [comment]
I think you can get the behavior you need by using `canActivateChild` and `canDeactivateChild`. The `canActivateChild` is already in master, and `canDeactivateChild` is coming soon. 

Closing this issue.

**Comment by pshpak** [comment]
Could somebody provide an example how this can be resolved using canActivateChild and canActivateChild?

**Comment by tdsmithATabc** [comment]
@pshpak - It can't be resolved yet, because `canDeactivateChild` isn't released.

@vsavkin - Are you implying then that [the router documentation](https://angular.io/docs/ts/latest/guide/router.html#!#milestone-5-route-guards) is incorrect?

> We can have multiple guards at every level of a routing hierarchy. The router checks the `CanDeactivate` and `CanActivateChild` guards first, from deepest child route to the top. Then it checks the `CanActivate` guards from the top down to the deepest child route.

(I will note separately that the placement of `CanActivateChild` in that sentence doesn't seem correct, but that isn't what I'm highlighting.)

To my ear that implies that the router finds the common ancestor of the current route and the target route, walks *up* the tree checking `canActivate`s, then walks down from the ancestor to the target performing alternating `canActivateChild` and `canActivate` checks.

The actual behavior seems to be more like... deactivate the current leaf, then *leap* to the ancestor and try to descend through activations. (The behavior seems to be even stranger when changing route parameters, but I haven't gotten into investigating that fully...)

I plan to put together a plunker by EOD (CST).

**Comment by tdsmithATabc** [comment]
Also in regard to the current behavior, it doesn't seem like `canDeactivateChild` would help in the general case. If I have some deep child X I'm departing, the `canDeactivateChild` guard would need to live on X's parent, right? There's no guarantee that that "boundary" is the one that makes semantic sense for the wrap-up though.

**Comment by tdsmithATabc** [comment]
Ok in exploring the issue, it seems that my problem was slightly different and involved component-less routes, whereas this issue has to do with guards on reused nodes without changing parameters (whose parents *are* changing parameters).

I documented my problems separately in #12375, though certainly the behavior here is relevant to the same underlying `Preactivation#traverse` code.

**Comment by tdsmithATabc** [comment]
@pshpak, @aboris0v, anyone else looking for a temporary solution - here's what I've learned.

If a node in the target route has the same (shallow-equality) config as that node in the source route, it will *only* check its guards if it has parameters that differ. So in the example from the plunker:

```typescript
export const routes : Routes = [
// ...
{
	path: 'feed',
	component: FeedComponent,
	resolve: { orders: FeedResolver },
	children: [{
		path: 'order/:id',
		component: ExistingOrderComponent,
		resolve: { order: OrderResolver },
    children: [
  		{path: '', redirectTo: 'summary', pathMatch: 'full'},
  		{path: 'summary', component: SummaryComponent},
  		{path: 'edit', component: EditComponent, canDeactivate: [CanDeactivateGuard]}
		]
  }]
},
// ...
];
```

Moving from `feed/order/1/edit` to `feed/order/2/edit` would only trigger guards from the `order/:id` node, because the node was reused but the `:id` parameter changed. In the future, this is where `canDeactivateChild` would come in -- you could specify that on the `order/:id` node.

For now you could do a couple things:

- If you *aren't* using a resolver or anything that depends on the parameter in the parent, just move the parameter further "down the tree":

```typescript
children: [{
	path: 'order',
	component: ExistingOrderComponent,
//	resolve: { order: OrderResolver },  // NOTE: THIS WOULD BE A PROBLEM
  children: [
		{path: ':id', redirectTo: 'summary', pathMatch: 'full'},
		{path: ':id/summary', component: SummaryComponent},
		{path: ':id/edit', component: EditComponent, canDeactivate: [CanDeactivateGuard]}
	]
}]
```

- The [documentation for `Routes`](https://angular.io/docs/ts/latest/api/router/index/Routes-type-alias.html#!#componentless-routes) indicates that routes *without components* will have their `params`, `data`, and `resolve` merged into those of the children. So if you don't need a component at that layer, you can do something like this:

```typescript
children: [{
	path: 'order/:id',
	resolve: { order: OrderResolver },
	// no component here!! (move it up or down as appropriate)
  children: [
		{path: '', redirectTo: 'summary', pathMatch: 'full'},
		{path: 'summary', component: SummaryComponent},
		{path: 'edit', component: EditComponent, canDeactivate: [CanDeactivateGuard]}
	]
}]
```

Since the children now have inherited parameters, the parameter changes will cause the guards on those nodes to fire. (Also if you *did* need a component at that level, you could insert an extra parent above it with an empty path `path: ''`)

Cheers!

**Comment by fenderjair** [comment]
@tdsmithATabc  I have tried your solution and the can deactivate it's recognized as a canDeactivate route, but it is not called in the class where I implemented it, so I always get an undefined because the class where I implemented it does not call the method from the deactivate guard.

I don't know if it's because I don't follow well the example you wrote before or if it's because I have an error in the class where I implement the deactivate guard. Here it's my main routes:

`
export const mainRoutes: Routes = [

	{ path: 'home', component: CurationProcessComponent },
	{ path: 'home/document/:id', loadChildren: 'app/curation-process/document-sections/document-sections.module#DocumentSectionsModule' },
	{ path: 'home/document', component: DocumentListComponent, canDeactivate: [HideFormsGuard] },
  { path: '', redirectTo: 'home', pathMatch: 'full' },
  { path: '**', redirectTo: 'home', pathMatch: 'full' }
];
`

And my child routes:
`
const FORM_ROUTES: Routes = [

	{ path: '', component: DocumentSectionsComponent, children: [
    { path: '', redirectTo: 'test', pathMatch: 'full' },
    { path: 'test', component: DocumentSectionsComponent },
		{ path: 'gene/:id', component: GeneComponent},
    { path: 'gene', component: GeneComponent, canDeactivate: [HideFormsGuard]}
  ]}
];
`

Greetings.

**Comment by adickenscheidt** [comment]
@vsavkin Here we are, 1.5 **years** later and the feature is still implemented, yet this issue is closed. Any info on why such a straightforward use case is not yet included?
