### ISSUE TITLE
Multi Content/Slot Projection (ng-content) only works for very specific selectors

### ISSUE THREAD

**Issue by fourctv** [angular/angular#11680]
**I'm submitting a ...**  (check one with "x")
```
[X ] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior** 

When trying to use multi content projection (<ng-content select="xxx">), the compiler does not recognize slots names that are different from "header" or "footer".

**Expected behavior**

One should be allowed to use any names for multi content slots.

**Reproduction of the problem**
I've put out a plnkr that demonstrates the problem:
http://plnkr.co/edit/YwbpJ2seIf2gKJKrIfNf?p=preview

As it is there, the code works. But if you remove line n.19 in 'src/app.ts', you can reproduce the error. Removing that comment line enables the lines that access a content slot named 'foobar'.

* **Angular version:** 2.0.0-rc.X
2.0.0.

* **Browser:**
 all

* **Language:** 
 typescript.

**Comment by vicb** [comment]
Solution is given in the error message:

```
'foobar' is not a known element:
1. If 'foobar' is an Angular component, then verify that it is part of this module.
2. If 'foobar' is a Web Component then add "CUSTOM_ELEMENTS_SCHEMA" to the '@NgModule.schema' of this component to suppress this message.
```

And in already closed issues, you should search for them.

**Comment by ericmartinezr** [comment]
I think that's because [header](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/header) and [footer](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/footer) are existing html elements, while `foobar` doesn't and it's expecting you to provide it.

**Comment by fourctv** [comment]
First, that code works fine till RC5. It broke from RC6 and up.

The point is that I am providing a `foobar` element via `<ng-content select="foobar">`.

**Comment by fourctv** [comment]
@vicb if only existing html element names are valid as ng-content slot names, then make this a feature request.

In my real case, I use meaningful names for the slot sections, makes no sense to use pre-existing html element names

**Comment by vicb** [comment]
> In my real case, I use meaningful names for the slot sections, makes no sense to use pre-existing html element names

makes sense, look for the solution in the issue tracker

**Comment by choeller** [comment]
@fourctv I'm also suffering from this problem. As a workaround I created a mega-dumb directive looking like this:

```ts
@Directive({
  selector: 'panel-header'
})
export class PanelHeaderDirective {
}
```
to be able to use <panel-header> as multi-transclusion slot. This is quite ugly and also against the style-guide (dash-case selector for Directives) but at least it allows me to do multi-transclusion for now.

**Comment by tdsmithATabc** [comment]
FYI, there's a good response by @pkozlowski-opensource over at #11659. 

To expand a bit on that answer, there are two main fixes:

1. Configure your module's `schemas` property. This property helps configure the document *schema*, which defines which elements and properties are valid and can be bound to. As of 2.0.1, there are two values you can add to this array: [`CUSTOM_ELEMENTS_SCHEMA`](https://angular.io/docs/ts/latest/api/core/index/CUSTOM_ELEMENTS_SCHEMA-let.html), which allows elements and properties with hyphens, and [`NO_ERRORS_SCHEMA`](https://angular.io/docs/ts/latest/api/core/index/NO_ERRORS_SCHEMA-let.html), which suppresses *all* schema errors.

2. Alternatively, `ng-content`'s `select` attribute can take other CSS selector types than just elements. This means you could instead select it with `select=".classname"` and it would grab `<span class="classname">`.

@fourctv's approach works too of course, because selectors defined by loaded directives don't need to be checked against the DOM schema. It makes some semantic sense to define them alongside your component, but it does feel unnecessary to me. (You might also be able to do something crazy by dynamically generating empty directives with the selectors you need via a factory injector or something, but that feels like an abuse of the system.)

----

The outstanding question to me though is whether there will be future support for custom schema extensions. I'd love to take route 1, but explicitly add my tag names to the schema without allowing all hyphenated ones...

**Comment by vicb** [comment]
> there will be future support for custom schema extensions

yep, this is planned
