### ISSUE TITLE
AOT compilation for JS

### ISSUE THREAD

**Issue by deontologic** [angular/angular#11700]
**I'm submitting a ...** 

```
[ ] bug report => search github for a similar issue or PR before submitting
[ x] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior** 
Because ngc wraps tsc, it can only generate ngFactories for typescript files. 

**Expected behavior**
Ideally, typescript transpiling and ngFactory generation would be decoupled, so plain js (or languages other than ts that target js) can be used.

**What is the motivation / use case for changing the behavior?**
AOT compilation and treeshaking are important tools for production deployment, and should work with all languages supported by angular. 
- **Angular version:** 2.0.0
  
  
- **Language:** all

My apologies if this has been discussed before. I have been able to find no reference to this issue on SO, the google group, or in the issues (although github's search does not scale well with 1000+ open issues).

**Comment by spock123** [comment]
Hi @kantianethics 
- correct me if I'm wrong, but isn't the problem with plain js that it can't be statically analyzed?
Afaik there is now way the AoT compiler can do it's work without the metadata provided by Typescript?

**Comment by kantianethics** [comment]
What metadata are you specifically referring to? 

My understanding is that the NgFactories generated in-memory by the JIT are equivalent to those of the AOT. 

Thus if
 
```
import { Component } from '@angular/core';
@Component({
  selector: 'hero-view',
  template:
    '<h1>Hero: {{getName()}}</h1>'
})
export class HeroComponent {
  title = 'Hero Detail';
  getName() {return 'Windstorm'; }
}

```

and 

 ```
 function HeroComponent() {
    this.title = "Hero Detail";
  }

  HeroComponent.annotations = [
    new ng.core.Component({
      selector: 'hero-view',
      template:
        '<h1>Hero: {{getName()}}</h1>'
    })
  ];
  HeroComponent.prototype.getName =
    function() {return 'Windstorm';};
```

generate the same ngFactories in-memory, the AOT should be able to replicate this process.

**Comment by AugustNagro** [comment]
If AOT for JS is feasible (and doesn't require huge changes), I'd be interested in helping with this. 

I'm new to the compiler codebase though, and would need some direction.

**Comment by thelgevold** [comment]
AoT requires typescript, but you can at least do the Tree shaking part since it targets es2015 JS modules and not TypeScript. 
One example of a Tree shaker you can use is Rollup.
The Tree shaking section in the docs: https://angular.io/docs/ts/latest/cookbook/aot-compiler.html#!#tree-shaking 
applies to a plain JS project as well. Notice how the input is JS and not TS.

Obviously this is not as nice as being able to do both AoT and Tree shaking, but it's at least better than nothing :-)

**Comment by AugustNagro** [comment]
What makes AOT require TS? Just curious.

**Comment by thelgevold** [comment]
My understanding is that the ngc compiler is a wrapper/enhancement of the regular tsc compiler and therefore assumes TypeScript.

I still think it should be possible support AoT with JS though. It doesn't seem like the concept of AoT is tied to TypeScript for other reasons than current tooling. 

We will have to wait for feedback from the Angular team about how feasible this is though.

**Comment by AugustNagro** [comment]
If decoupling ngc from tsc requires a huge effort/rewrite, my use-case definitely doesn't merit it :)

**Comment by gbaldeck** [comment]
I have a use case for this. I'd like to make a Kotlin wrapper for Angular that uses AOT. Kotlin compiles down to ES5 so it would have to use an AOT compiler for JS. Is this in the works or is it something that won't be added?

**Comment by iFadey** [comment]
Any update on this? Is it possible to use AOT with JavaScript/Angular 4?

**Comment by cristian-mocanu-mob** [comment]
I would also be interested if there is any update on this ticket.

Kotlin is a much better language compared to TypeScript.

It's my current understanding that the ng compiler is tied to TypeScript.
I would love for the Angular team to provide the support that the community needs to come up with an Angular-Kotlin integration.

**Comment by trotyl** [comment]
@cristian-mocanu-mob What's the meaning for that? Angular itself is written in TypeScript, and the template cannot work without Angular runtime part.

**Comment by cristian-mocanu-mob** [comment]
@trotyl: I think you missed my point. Of course the **output** should be JavaScript (with or without a TypeScript intermediate step) because that's what the browsers run.
My point was about the **input**: using Kotlin as an input to the Angular compiler, instead of TypeScript.

**Comment by spock123** [comment]
@cristian-mocanu-mob Sounds like a great hobby project on the side :) . I'm sure there is more important stuff in the pipeline than rewriting the entire compiler...  I agree that in an ideal world, compilers for 22 languages would be nice - but what about 3rd party libs?

You also want all those in the World to be rewritten in Kotlin? Or do you want compiler that does both at the same time? I think there are practical implications in this that at least I don't quite grasp.

The idea is great, just don't think it's feasible imho.

**Comment by trotyl** [comment]
@cristian-mocanu-mob Angular compiler will only compiler HTML template while collecting metadata in TypeScript. It won't change any TypeScript code except the special handling for metadata part.

Even if it could extract metadata from Kotlin and then compile the HTML template, you'll still get logic code in Kotlin and generated JavaScript code in JavaScript/TypeScript.

So what you need are:

1. Bridge for extracting metadata from Kotlin (Angular compiler can already handle `.d.ts` with `.metadata.json` file, no need to provide actual logic);
2. Compile Kotlin to JavaScript **PER FILE** (Angular compiler produces modular source code, so you cannot bundle the other part);

**The real problem is the second, how can you make the single file compilation from Kotlin to JavaScript without bundling? That's a general problem for to-JavaScript compilation itself, not related to TypeScript.** If this problem not exist, like using CoffeeScript, then it's quite easy to support it by just wrapping the compiler.

**Comment by cristian-mocanu-mob** [comment]
@spock123: Let me start by saying that I have no idea how the angular compiler works. That said, the request is not for Angular compiler to support Kotlin directly, but rather to step aside and not be so tightly coupled to Typescript. This would allow any language that compiles to JavaScript to be supported.

Some time ago, I found some information about how to use Angular with plain JavaScript (e.g. how to "simulate" the annotations, etc.). I can't tell if the info applies to AngularJS or Angular, because of the very bad decision to keep the same name, even though it's a totally different framework.

To reiterate, Angular should work with plain JavaScript. When that's possible, then Angular will be able to work with any language that compiles to JavaScript, including Kotlin.

Someone more knowledgeable than me please add a comment stating:
- whether Angular supports plain JavaScript **instead of** TypeScript
- if so, how to do it
- it not, what needs to change in Angular to support this

**Comment by cristian-mocanu-mob** [comment]
@trotyl: because I'm not familiar with how the Angular compiler works, I don't fully understand your comment.
It seems to me that if the Angular compiler could be used with plain JavaScript (without any TypeScript), than any language compiling to JavaScript could be supported:
- step 1: compile language X to JavaScript
- step 2: invoke Angular compiler

Is this possible today?
If not, would it be a big effort to make this possible?

In the mean time, I guess I need to do some reading about the Angular compiler.

**Comment by trotyl** [comment]
@cristian-mocanu-mob Angular compiler do support but plain JavaScript as source code, but require companion `.d.ts` for signatures and `.metadata.json` for annotations.

All Angular libraries are shipped in JavaScript without TypeScript source code, clearly they're also supported.

So if you can generate `.d.ts` and `.metadata.json` from your own source code (no need for entire compiler, but still require a parser-like stuff), it will be possible to use it with Angular compiler.

**Comment by cristian-mocanu-mob** [comment]
Created a ticket on Kotlin issue tracker to see what the Kotlin team thinks about this: [Support Angular 2+](https://youtrack.jetbrains.com/issue/KT-21561)

**Comment by bashor** [comment]
@trotyl do I understand correctly that `.metadata.json` is kind of replacement of supporting decorators and if we generate it we should not generate code for decorators in the js code?

**Comment by trotyl** [comment]
@bashor Only true if you're genrating AOT-only library. You should leave the decorator (or change it to static properties) if you want to support JIT usage.

**Comment by dmellstrom** [comment]
One week left to get 12 more :+1:s  for this or it will be closed.

**Comment by gumdrop** [comment]
👍

**Comment by JoostK** [comment]
The usage of TypeScript as source language as its decorators and type annotations are a natural way to express Angular's features, which would not be available in JS.  Supporting a different language would therefore affect the syntax of how to write Angular applications, which moves it away from what Angular is today. Additionally, Angular is about providing a consistent developer experience: we wouldn't want to split the ecosystem with a different source language.

The JS examples I have seen in this thread are also not as recognizable, making it far more difficult to analyze statically for AOT compilations.

As a side note: although Angular's current tooling is built on top of the TypeScript compiler, that doesn't have to be the case. There are proposals like #43165 to achieve compilation with other tooling, but the source language and syntax would remain the same.
