### ISSUE TITLE
Input properties change detection: we need forceUpdate

### ISSUE THREAD

**Issue by PFight** [angular/angular#11704]
**I'm submitting a feature request**

**Current behavior** 
When an input property of component is array or complex object, it's changes do not detected until reference is same. And we have no any way to tell component, that value is updated, besides to change whole object (make it immutable, for example). See [other issue](https://github.com/angular/angular/issues/6458), [StackOverflow question](http://stackoverflow.com/questions/34796901/angular2-change-detection-ngonchanges-not-firing-for-nested-object).

**Details**
Imagine, I have child component, that binds it input property to my array `names`. I change my `names` array, by pushing some new element. I want to say to my child component "hey, `names` changed, update yourself". There is no way to do this, right now.

I do not want to make `names` immutable due to perfomance issues. I always know, when it is changed, and creating new array every time, when one element changed - it is stupid. I know, that `names` changed, I have ref to child component (ViewChild), so I do not need change detection at all. Just tell to child component to update.

I do not want to implement ngDoCheck in child component, because: 1) it is external component, I can't change it 2) I have no idea, how to implement it. I do not want implement change detection on `names`, I want just tell to child component to shut up, and update it inputs.

I  tried to call ChangeDetectorRef.detectChanged, markForUpdate on child component (thougth, it is hack, because child component is not mine, I should not change it), but it does not helped. Change detector detects only bindings of the component, and not input properties. I also tried call ChangeDetectorRef on parent component, it also not worked. 

Only dirty hack I found - call by hand ngOnChanges of the child component, because child component uses this function to process input:

```
@ViewChild('modelTree') modelTree: TreeComponent;

public updateNodes() {
    // Notify child compoennt, that nodes input property changed
    this.modelTree.ngOnChanges({
      options: { currentValue: this.modelTree.options },
      nodes: { currentValue: this.modelTree.nodes }
    });
  }
```

How do you like this code? Horrible. 

** Suggestion**

Add some way to notify component, that input properties has changed without change detection. Something like `forceUpdate` in ReactJS. Something like ChangeDetectorRef.markForUpdate for component bindings.

* **Angular version:** 2.0.0

* **Language:**  TypeScript

**Comment by gdi2290** [comment]
inject the `ApplicationRef` and run `tick()`
`appRef.tick()`

**Comment by pkozlowski-opensource** [comment]
> When an input property of component is array or complex object, it's changes do not detected until reference is same. And we have no any way to tell component, that value is updated, besides to change whole object

This is the default and correct behavior. If you want to deep-observe changes to the object / arrays themselves you can use `KeyValueDiffer` / `IterableDiffer`. You might check the `NgClass` implementation to see how to use the mentioned classes in practice: https://github.com/angular/angular/blob/master/modules/@angular/common/src/directives/ng_class.ts

**Comment by PFight** [comment]
> inject the ApplicationRef and run tick()

No effect.

> This is the default and correct behavior.

Yes, I know. It is not bugreport, it is **feature request**. I say, that there is no side-door to go over this behaviour and it is bad. Nor `KeyValueDiffer` / `IterableDiffer` are the solution, I have written why:

> I do not want implement change detection on names, I want just tell to child component to shut up, and update it inputs.

**My suggestion is:**

> Add some way to notify component, that input properties has changed without change detection. Something like forceUpdate in ReactJS. Something like ChangeDetectorRef.markForUpdate for component bindings.

**Comment by gdi2290** [comment]
what you're doing with `ngOnChanges` is correct to deal with components that don't manage state correctly or relies on mutations. At least the child component follows some angular conventions such as `ngOnChanges`. 

`forceUpdate` in React, forces a render without checking `shouldComponentUpdate`. `shouldComponentUpdate` is nearly the same as `ngDoCheck` but for change detection and it also invokes `ngOnChanges`. So the feature you're requesting is already there as `ngOnChanges` as you're using it which gives you more control over what to render rather than forcing everything to check. You can also mark the child component as dirty and run `appRef.tick()` which is what you want compared to React's rendering and Angulars which makes it more predictable for cascading mutations that might occur if you don't know that it might.

At the end of the day adding more easier features for applications that deal with mutations is probably not ideal as the differs feature and `ngOnChanges` are meant for this use case

**Comment by PFight** [comment]
> You can also mark the child component as dirty and run appRef.tick()

How can I mark the child as dirty? `cd.markForCheck()` on parent and on child with `appRef.tick()` has no effect. Is there another way to mark as dirty?

> what you're doing with ngOnChanges is correct

Alright, but it is horrible code! I should create some strange structure with "`currentValue`" fields inside... Calling service callback, like `ngOnInit`, `ngOnChanges`, `ngOnDoCheck`... by hand - is dirty hack anyway. They are supposed to be called by angular, not by user, and if I calling them, I feel dangerous.

May be some syntax sugar, some Injectable service like `ChangeDetectorRef`, that will incapsulate call of `ngOnChanges` inside itself?

**Comment by rmcsharry** [comment]
I would love this feature to be implemented because I certainly cannot figure out how to get a child component to re-render the view after a parent property has changed (ie a property inside a complex bound @Input object). The docs do not explain this very well at all.

What I find particularly strange is that using `[(ngModel)] `on a parent template-drive form does this quite easily...so why is it made nearly impossible with domain/model-driven forms?

[SO question](http://stackoverflow.com/questions/41645230/angular2-notify-child-that-parent-object-changed-so-child-can-refire-an-ngif-i/41645895#41645895) showing what I mean.

**Comment by rmcsharry** [comment]
[This question](http://stackoverflow.com/questions/34761224/angular2-child-property-change-not-firing-update-on-bound-property/) seems to describe a similar problem - but even if you write a service that then provides an emitter to notify the child that a deep property has changed, the view still does not update (the ngIf appears to be ignored).

**Comment by DzmitryShylovich** [comment]
> I certainly cannot figure out how to get a child component to re-render the view after a parent property has changed

You can use `KeyValueDiffer`. This is what `ngClass` does. Here's an example [link](https://github.com/angular/angular/blob/master/modules/%40angular/common/src/directives/ng_class.ts#L86)

**Comment by rmcsharry** [comment]
@DzmitryShylovich Thanks. After removing all my code and starting again it now works - the child is automatically updated without me having to do anything extra. I don't get it. I updated my SO question with the answer.

I just loop through the child properties updating them in the parent, and the child is now firing the ngIf for each one. I thought that was not possible as per this feature request. I don't get it at all now! lol
