### ISSUE TITLE
Bounds attributes `[attr.xxx]` do not trigger directives

### ISSUE THREAD

**Issue by bzums** [angular/angular#11716]
**I'm submitting a ...**  (check one with "x")

```
[ * ] bug report => search github for a similar issue or PR before submitting
[ * ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior** 
When specifying an attribute directive dynamically (using `[attr.attrName]=''`) on an element the directive is not "triggered" while it is when the attribute directive is added statically.

**Expected behavior**
It should not matter whether adding the attribute dynamically or statically.

**Reproduction of the problem**
http://plnkr.co/edit/WiCrCxlNrUgaBCXkEQkm?p=preview
Enter a value with leading or traling whitespaces and click save, in the console the value of the form is logged.

**What is the motivation / use case for changing the behavior?**

**Please tell us about your environment:**

- **Angular version:** 2.0.0-rc.X
  
  
- **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ] 
  
  
- **Language:** [all | TypeScript X.X | ES6/7 | ES5]
- **Node (for AoT issues):** `node --version` =

**Comment by vicb** [comment]
Just discussed with @tbosch - that probably something we can consider.
_(boolean attributes handling might need more discussion)_

**Comment by rolandjitsu** [comment]
I think this might be resolved. I have tried this with a select and it seems to be working.

**Comment by DzmitryShylovich** [comment]
@rolandjitsu don't think so. pls provide a demo on plunkr

**Comment by guzuomuse** [comment]
@DzmitryShylovich
any progress on this?
as the select is the basic element of form. I think this should be modified asap.

**Comment by guzuomuse** [comment]
i think it's a bad design for "select"  since it don't support attr.multiple 
ony with the selector "<select [multiple]>" is bad idea. for this we can't dynamic bind multiple property.

**Comment by tytskyi** [comment]
@guzuomuse AFAIK there is no progress on this, until then you could use 2 `<select>` with `*ngIf`

**Comment by guzuomuse** [comment]
@tytskyi  thanks for you replying.

but in some scenario. for example,we had customized a directive that dynamically set attributes(properties) with renderer's `setAttribute() `or `setProperty()`. so we must exclude The **multiple** poperty. for the `select`  element ; that 's tedious. why  not make it 'intelligent' since select element   used frequently and maybe it's not so difficult to improve it.

**Comment by mhevery** [comment]
Currently
1. `<div my-directive>` triggers `MyDirective`
2. `<div [attr.myDirective]="exp"` does not trigger `MyDirective`. 
3. `<div [attr.myDirective]="exp" my-directive` triggers `MyDirective` and it allows dynamically changing the attribute. This seems like a very easy work around to your need.

It seems like we are covering all of the cases in the sense that we can get angular to output any DOM and to decided wether a particular DOM should or should not trigger a directive.

If we change it to  
- `<div [attr.myDirective]="exp"` *triggers* `MyDirective`. 
than there are these consequences:
1. There is no way to add the attribute without also triggering the directive
2. Currently all selectors are static. Bringing semi-dynamic selector would beg the question wether the directive should be triggered conditionally, and that is something we would not implement.
3. `[attr.myDirective]` means bind to an attribute, but what if directive has `@Input() myDirective: string`. Do we want to perform property binding? Presumably yes, which means that now `attr` is binding to a property and that seems very wrong to me.

I think consequence 3 is what breaks it for me, and I don't think this should be implemented, because it would create inconsistency about the intention of attribute vs property binding. 

My vote is to close this as won't implement.

**Comment by CaerusKaru** [comment]
@mhevery I think the main concern for this issue is that users have no way of specifying that directives should be applied on the host component. E.g. the following will not work:

```ts
<app-some-component fxFlex>
	...
</app-some-component>
```

Thus, we need a way to add directives that should be compiled on the host. This issue might not be the ideal solution, but we need _a_ solution.

See related:
https://github.com/angular/flex-layout/issues/76
https://github.com/angular/flex-layout/issues/171

**Comment by darkbasic** [comment]
+1 I'm looking for a way to apply flex-layout directives to the host element.

**Comment by grosch** [comment]
It's not just flex-layout.  It should be anything.  For example, I'm generating an element via Renderer2 and I'm trying to write in an ngbTooltip.  It comes in as all lower-case when I do that, and I don't get any type of tooltip at that point.

**Comment by elazarza** [comment]
> It's not just flex-layout. It should be anything. For example, I'm generating an element via Renderer2 and I'm trying to write in an ngbTooltip. It comes in as all lower-case when I do that, and I don't get any type of tooltip at that point.

same issue here, i want to dynamically render matTooltip but it makes it all lowercase and therefor not working. is  there anything new with this issue?

**Comment by mhevery** [comment]
Closing this one, as we will implement something along https://github.com/angular/angular/issues/8785 instead.
