### ISSUE TITLE
 Tour of Heroes tutorial may have a bug about button

### ISSUE THREAD

**Issue by yiji** [angular/angular#11743]
**I'm submitting a ...**  (check one with "x")
```
hero-detail.component.html

<div *ngIf="hero">
  <h2>{{hero.name}} details!</h2>
  <div>
    <label>id: </label>{{hero.id}}</div>
  <div>
    <label>name: </label>
    <input [(ngModel)]="hero.name" placeholder="name" />
   </div>
  <button (click)="goBack()">Back</button>
  <button (click)="save()">Save</button>
</div>

```

**Current behavior** 

i write a real web api to test,when i click save button,the request cant sent to web api,
after test i find if i change button to span or add type attribute
```
 <span (click)="save()">Save</span>
or
 <button type="button" (click)="save()">Save</button>
```

**Comment by pkozlowski-opensource** [comment]
I'm sorry but it is not clear what your issue is all about... If you think that the documentation is wrong and needs updating please report it in https://github.com/angular/angular.io where the Tour of Heroes documentation is located.

If you've got a general help with your use case or using the framework please use one of the support channels:  https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
