### ISSUE TITLE
Blog - sidebar view design issue

### ISSUE THREAD

**Issue by FrancescoMussi** [angular/angular#11793]
Hi guys.
Little bug here.

This is how i see the angular blog - sidebar mode:
On the left the sidebar is unreadable 

![screen shot 2016-09-21 at 16 31 24](https://cloud.githubusercontent.com/assets/5312907/18715332/342d67d8-8019-11e6-8f98-864502ebf653.png)

I have a MacBook Pro 13,3-inch (1280 x 800)

**Comment by StephenFluin** [comment]
I need to close this issue because it's not related to the `angular` project (we don't have a Github repo for our blog).

@FrancescoMussi thanks for bringing this to our attention, we'll look to see what we can do about getting this fixed. For now I would recommend against using the Sidebar mode, as the bug appears to be specific to that view.
