### ISSUE TITLE
what happen when i use the ngc and scss?

### ISSUE THREAD

**Issue by wuzhouyang** [angular/angular#11815]
when i run `> ngc -p tsconfig.aot.json `
it log `Error: Compilation failed. Resource file not found: f:/web subject/optimize/NG2_CYErpPC/public/scss/_value  `

does the ngc support sass?

**Comment by gekallergis** [comment]
The same problem is present when using ng-xi18n to extract .xlf files from templates, since the extractor is utilizing the features of the compiler under the hood (e.g. see [this](http://stackoverflow.com/questions/39393344/ng-xi18n-script-is-failing-as-it-is-inspecting-scss-sass-files) question here).

**Comment by brandonroberts** [comment]
Compilation using `ngc` does not support sass. You must provide compiled css

**Comment by pkozlowski-opensource** [comment]
Thnx @brandonroberts

**Comment by teeSee** [comment]
@brandonroberts, thank you for the explanation.  I have two questions, 

1) Before the webpack plugin is ready that can handle sass with AoT can you suggest a  workaround for scss file using @import, since we are porting an existing app which has a lot of the @import. 

2) When will the sass with AoT webpack plugin will be ready? :)

**Comment by wuzhouyang** [comment]
@brandonroberts  ok...    i compile the sass advance...then i can use the AOT

**Comment by teeSee** [comment]
@wuzhouyang So you specify css instead of the scss in styleUrls?
Could you share more information? Thanks in advance.

**Comment by wuzhouyang** [comment]
@teeSee no,i use the css by import 'xxx.css' instead of use css in styleUrls...   like this
![image](https://cloud.githubusercontent.com/assets/12148043/18824557/8c9c2bc2-83f5-11e6-892d-23eb7763e003.png)

**Comment by teeSee** [comment]
Cool,  I will try this. Thanks!

**Comment by tomgeorge** [comment]
@wuzhouyang, have you tried to import css bundled by webpack in the `styleUrls` option of the Component decorator?  Right now my setup works if I `import` styles in the ts file, but I'd really like to load my styles "the angular way" if I could.

Right now I can use `stylesUrl` but I can't get it to resolve `url()` to import an image in css, because it's inlined as a string and all the module resolution context I had with webpack does not apply.

**Comment by wuzhouyang** [comment]
@tomgeorge yes i tried...but the `url()` in css will not be handled，so it can't find and show the image at result，although i really like to use the css by the angular way....

**Comment by wuzhouyang** [comment]
@tomgeorge 
Do you have any good idea？

**Comment by tomgeorge** [comment]
I've seen in the angularclass repo they don't use url in css, they put the image location in the component class that owns the image. That way, it has access to the runtime context/dependency graph that webpack creates.
