### ISSUE TITLE
Internet Explorer 'bug(s)'

### ISSUE THREAD

**Issue by goriunov** [angular/angular#11848]
Hello  i have an issue with Internet Explorer (ALL FROM 9 TO 11). It is not an Error , probably bug  it is not updating view when i navigate back(by using routerLink) and it is using old data with old arrays which should be populated with new information but nothing happen until i reload page fully. However when i open Dev tools in IE everything suddenly start work and update all data all works just perfect. What should i do with this ?

**Comment by goriunov** [comment]
Do not have any errors or warning from console

**Comment by Delagen** [comment]
IE throw out of stack error on page load. This cause angular/router, because it recognition stack is very heavy. 
Also i see loop on normalizeDirective* method, that produced incredible Promise.then chain

**Comment by goriunov** [comment]
So do we have any way to make it works ?

**Comment by Delagen** [comment]
I think while no large scale applications built on angular 2 IE will be supported as hello world sandbox

**Comment by DzmitryShylovich** [comment]
If u think u found a bug please fill the bug template and provide reproduction. Otherwise it's not actionable.

**Comment by pkozlowski-opensource** [comment]
@goriunov as @DzmitryShylovich pointed out this issue is not actionable as-is. Make sure that you've got all the required polyffils as described in https://angular.io/docs/ts/latest/guide/browser-support.html and if you still have problems please open small, focused issues with a clear reproduce scenario for each problem.

@Delagen if you've got reproduce scenarios for cases where IE fails with all the required polyfills included please open a separate issue with a clear reproduce scenario.
