### ISSUE TITLE
'afterViewChecked' lifecycle hook called multiple times

### ISSUE THREAD

**Issue by cartant** [angular/angular#11895]
**I'm submitting a ...**

```
[x] bug report
[ ] feature request
[ ] support request
```

**Current behavior** 

After a model change, the `afterViewChecked` lifecycle function is sometimes called once and is sometimes called multiple times.

I came across the #5572 issue (which was closed with a request for it be re-opened for version 2.0.0) when looking into multiple `afterViewChecked` calls for a `select` element in a unit test. In my unit test, I needed to make multiple calls to `whenStable` after a single change to the model.

**Expected behavior**

I would have expected `afterViewChecked` to have been called just once.

Whether or not the current behaviour is by-design is not apparent from the documentation, but the need for multiple `whenStable` calls makes this look like a bug, to me.

**Reproduction of the problem**

There is a Plunker [here](https://plnkr.co/edit/WOr9QRlhQjuNiGjSGGdr) that demonstrates the behaviour in 2.0.1.

**Please tell us about your environment:**
- **Angular version:** 2.0.1 
- **Browser:** Chrome 53, PhantomJS 2.1.1 
- **Language:** TypeScript 2.0.3

**Comment by tbosch** [comment]
So this is what happens:
- when you click on one of the letters, angular does a dirty checking run because of the click event. In your handler, you update the value that `ngModel` is bound to. This calls `ngAfterViewChecked` the first time.
- `ngModel` causes a second change detection run on purpose (see below), and therefore your `ngAfterViewChecked` is called the second time.

Why does `ngModel` do this? Here is why:
```
<div>{{myModel.valid}}</div>
<input [(ngModel)]="myValue" #myModel="ngModel">
```

I.e. `ngModel` can export itself on the element and then be used in the template.
Normally, this would result in expressions the `input` to have the wrong value as they have been dirty checked before. As this is a very common case for `ngModel`, we added this second change detection run. 

Please note that this extra run does not add up per `ngModel`, but it is just one extra run no matter how many `ngModel` have been changed.

So this is working as intended, although I agree it is not really expected.

**Comment by cartant** [comment]
@tbosch Cool. Thanks for the explanation.

**Comment by Diodeus** [comment]
I have run into this problem as well. I am trying to detect overflow on a title, and reduce the font-size if it overflows. I can't see the element's scrollHeight until this event fires. Even if I don't change the font size, the event keeps firing.
