### ISSUE TITLE
chore: display source details for unused imports

### ISSUE THREAD

**Issue by vicb** [angular/angular#1192]
It would really help to display the source line for such dartanalyzer error messages:

`dist/dart/angular2/:[hint] Unused import (/home/travis/build/angular/angular/dist/dart/angular2/test/directives/if_spec.dart, line 18, col 8)`

It would help fixing the code when Travis reports such an error in the dartanalyzer task.

**Comment by pkozlowski-opensource** [comment]
I hate adding +1 for GH comments but I will do it now :-)

**Comment by mhevery** [comment]
@kevmoo can you help?

**Comment by naomiblack** [comment]
@kegluneq assigning to you -- Kevin says this needs some scripting -- please reassign to @jakemac53 if you're overloaded :)

**Comment by kegluneq** [comment]
I'm going to take a quick stab and see if I can get this done in an hour rather than a day, but if that doesn't work this is behind a few other items priority-wise. I will reassign if I can't get to this before I leave.

For context, this is something we might add alongside `_AnalyzerOutputLine` in [dartanalyzer.js](https://github.com/angular/angular/blob/master/tools/build/dartanalyzer.js#L115). Maybe each line has-a `_AnalyzerSourceFile` with the contents of its source file.
