### ISSUE TITLE
[http] Headers toJSON consistency

### ISSUE THREAD

**Issue by Delagen** [angular/angular#11958]
**I'm submitting a ...**  (check one with "x")

```
[x ] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior** 
HTTP response header is: Date:Wed, 28 Sep 2016 08:36:24 GMT
in Headers map of Response it presented as

```
{"key":"date","value":["Wed, 28 Sep 2016 08:36:20 GMT"]}
```

When I call Headers.toJSON()
i receive it as

```
{"date":["Wed"," 28 Sep 2016 08:36:20 GMT"]}
```

Using this object to constuct base Headers

```
new Headers({"date":["Wed"," 28 Sep 2016 08:36:20 GMT"]})
```

cause it to be different when is was in source

**Expected behavior**
Consistent Headers<=>JSON conversion

**Comment by gdi2290** [comment]
The headers need to split by `';'` and join by `';'` rather than splitting by `','` and joining via `','` so it's a potential breaking change since some could have a server setup that is reading `','` rather than `';'`. For multiple headers usually browsers/etc can read either `,` or `;` in the case of a date where it uses `,` the browser/etc are able to read them correctly. We would want to use `;` as a way to specify the next header value or determine it's a date value via RegExp (the correct way) and ignore splitting that value.

The browser/framework/lib/etc is meant to handle the special case of dates having `, ` in them and it's easier just to switch to `;` which also works for multiple header values or just use a RegExp.

The PR should be easy enough if you can make one and add a date to the header example

`inputArr = ['application/jeisen', 'application/jason', 'application/patrickjs'];`
should be
`inputArr = ['application/jeisen', 'application/jason', 'application/patrickjs', 'Wed, 28 Sep 2016 08:36:20 GMT'];`
then add another test to check if the Map is correctly spliting 

If anyone wants to research this more google searching for "headers with multiple values" you will see the spec is advocating splitting by `,` where the implementation handles the edge case of dates

**Comment by alanhg** [comment]
similar error

```
TypeError: Cannot read property 'split' of null
    at http://192.168.1.141:3001/main.bundle.js:57609:75
    at Array.forEach (native)
    at http://192.168.1.141:3001/main.bundle.js:57609:20
    at Map.forEach (native)
    at Headers.webpackJsonpac__name_../node_modules/@angular/http/@angular/http.es5.js.Headers.toJSON (http://192.168.1.141:3001/main.bundle.js:57607:23)
    at HomeComponent.webpackJsonpac__name_../client/desktop/app/components/home/home.component.ts.HomeComponent.openAutoComplete (http://192.168.1.141:3001/main.bundle.js:4932:53)
    at HomeComponent.webpackJsonpac__name_../client/desktop/app/components/home/home.component.ts.HomeComponent.ngOnInit (http://192.168.1.141:3001/main.bundle.js:4791:14)
    at checkAndUpdateDirectiveInline (http://192.168.1.141:3001/main.bundle.js:47937:19)
    at checkAndUpdateNodeInline (http://192.168.1.141:3001/main.bundle.js:49316:17)
    at checkAndUpdateNode (http://192.168.1.141:3001/main.bundle.js:49284:16)
    at prodCheckAndUpdateNode (http://192.168.1.141:3001/main.bundle.js:49737:5)
```

**Comment by gizm0bill** [comment]
that is due to the fact that: 
```split.push.apply(split, v.split(','));``` on https://github.com/angular/angular/blob/master/packages/http/src/headers.ts#L160
which is simply shameful tbh

**Comment by alxhub** [comment]
Closing as this is obsolete (it concerns `@angular/http` which has been removed in favor of `@angular/common/http`).

I do not believe `HttpHeaders` in `@angular/common/http` suffers from this bug.
