### ISSUE TITLE
AOT Compiler requires public properties, while non-AOT allows private properties

### ISSUE THREAD

**Issue by schungx** [angular/angular#11978]
**I'm submitting a ...**  (check one with "x")
```
[X] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior** 
When writing a component, fields referred inside a template is allowed to be declared `private` and it will still work.

However, such `private` fields generate errors with the AOT compiler.  They must be turned `public`.

**Expected behavior**
Be consistent.  Either allow or not allow.

**Reproduction of the problem**
~~~~~ {.ts}
template: "<div>{{hello}}</div>"

class someModule {
    private hello: string;            <-- doesn't work with AOT compiler
}
~~~~~

**Please tell us about your environment:**
Windows 10.

* **Angular version:** 2.0.0

* **Browser:** all
 
* **Language:** TypeScript
 
* **Node (for AoT issues):** `node --version` =  v4.3.1

**Comment by robwormald** [comment]
This is the way it is because in JiT mode, we're not using Typescript - we're generating ES5 code, so there's no such concept as a "private" field.

Things that accessed from a template must be public, since they're being accessed outside of the class instance.

**Comment by aluanhaddad** [comment]
@robwormald Since a lot of official angular documentation uses `private`, isn't this a massive pit of failure for developers new to TypeScript? Considering that a component class is conceptually a cohesive unit, anyone not understanding that `private` properties are _not_ private at runtime will have no intuition as to why their code no longer works under AOT.

While I am not of fan of the TypeScript's `private` keyword, because it is somewhat misleading, it sounds like JIT compiled components are working precisely _because_ privacy is not enforced at runtime.

I would suggest removing the visibility modifiers on properties during AOT transformations and changing `private` to `public` for constructor parameter properties.

**Comment by achimha** [comment]
I agree this inconsistency is a nasty pitfall for developers. As @aluanhaddad says, a lot (most?) of the samples use `private` for DI in the constructor so developers get the habit especially since one is taught to never expose something that doesn't need exposing.

I believe this issue should be re-opened and addressed.

**Comment by aluanhaddad** [comment]
I another, deeper problem that is emerging here, and in many other issues, is that AoT Angular code can not be written in TypeScript. It is written in a subset of TypeScript which is not, as far as I have seen, formally specified, documented, or acknowledged in any capacity. 

This brings to mind a fair number of questions, including but not limited to the following:

  1. What is this language?
  
  2. When was this language introduced?

  3. Why was this language introduced?

  4. Who designed it? 
    a. What are their credentials?
    b. What other languages have they worked on?
    c. Is it intended to be a general purpose language or a domain specific language?

  5. How does it improve on TypeScript as a language?
    a. What new abstraction mechanisms does it offer?
    b. What tasks does it simplify?
    c. What are its motivating usecases?
  
  6. Where is it formally specified?

  7. When did I adopt it?

**Comment by RoxKilly** [comment]
related to #11422

**Comment by Foxandxss** [comment]
@aluanhaddad you have a big misunderstanding in here. There is no subset of Typescript in here. No one said that.

By using JiT (AKA the common way of doing Angular 2 since day 1), you transpile your code to ES5 to run it in the browser. Say you have:

```
@Component({
  selector: 'foo',
  template: '<div>{{name}}</div>'
})
export class FooComponent {
  private name = 'Hello';
}
```

That will generate, more or less something like:

```
define(["require", "exports"], function (require, exports) {
    "use strict";
    var FooComponent = (function () {
        function FooComponent() {
            this.name = 'Hello';
        }
        FooComponent = __decorate([
            Component({
                selector: 'foo',
                template: '<div>{{name}}</div>'
            })
        ], FooComponent);
        return FooComponent;
    }());
    exports.FooComponent = FooComponent;
});
```

Notice how `FooComponent()` contains a `name` property. It doesn't matter whether you put `public` or `private` at `name` because in ES5 that concept does not exist so you end with the same code.

When Angular runs that code, it will say. Ok, I have this html code, this template with a `{{name}}` and I can see a `this.name` in the ES5 code with a value, let's grab that and display it.

So far, so good.

So why do we have `private` and `public` if at the end the ES5 will not care? Well, the typescript compiler (and your editor) will complain if you try to access a private variable from where you can't do that:

```
class Foo {
  private bar = 10;
}

let f = new Foo();
console.log(f.bar);
``` 

Your editor will tell you that you cannot access `bar` and `tsc` (typescript compiler) will give you an error because you are trying to access a private variable.

Back in the component example, `tsc` doesn't complain because at compile time, no one tries to access that `name` field and the template will do the databinding at runtime where your code is not typescript anymore but ES5 and again, no visibility modifier in there.

---

That being said, with AoT, we sort of "convert" the template code to Typescript itself (again, Typescript, not any subset). Imagine the previous component, it will generate something like this:

```
createInternal(rootSelector:string):import3.AppElement {
  const parentRenderNode:any = this.renderer.createViewRoot(this.declarationAppElement.nativeElement);
  this._el_0 = this.renderer.createElement(parentRenderNode,'div',(null as any));
  this._text_1 = this.renderer.createText(this._el_0,'',(null as any));
  this._expr_0 = import7.UNINITIALIZED;
  this.init(([] as any[]),[
    this._el_0,
    this._text_1
  ]
  ,([] as any[]),([] as any[]));
  return (null as any);
}
detectChangesInternal(throwOnChange:boolean):void {
  this.detectContentChildrenChanges(throwOnChange);
  const currVal_0:any = import4.interpolate(1,'',this.context.name,'');
  if (import4.checkBinding(throwOnChange,this._expr_0,currVal_0)) {
    this.renderer.setText(this._text_1,currVal_0);
    this._expr_0 = currVal_0;
  }
  this.detectViewChildrenChanges(throwOnChange);
}
```

This is typescript code and it is our template converted to typescript code.

```
this._el_0 = this.renderer.createElement(parentRenderNode,'div',(null as any));
this._text_1 = this.renderer.createText(this._el_0,'',(null as any));
```

Here we create our `div` and a "placeholder" for a binding (AKA `{{name}}`).

A bit later we do:

```
const currVal_0:any = import4.interpolate(1,'',this.context.name,'');
```

We are accessing the `name` property from `context` where context is our `FooComponent`.

Then we do:

```
this.renderer.setText(this._text_1,currVal_0);
```

We get that placeholder from before and we assign to it the value of `name` AKA `Hello`.

Having this in mind, `name` has to be public, because if you set it private, `this.context.name` will raise an error since `name` is private and you cannot access it from outside the class.

---

So as TL;DR; there is no typescript subset. With JiT we convert all the code to ES5 and then in runtime we do the bindings. All the visibility modifiers are lost in that process, so it doesn't matter if you say public or private for that.

On the other hand, with AoT, we generate some typescript code for our templates, that will try to access those fields. If they are private, they simply cannot access those properties, hence, we have to put them as public.

---

@achimha All of this only applies to template <-> component interaction. A template is not part of the component class, so a template can only access to public properties from the component.

On the other hand, when we inject stuff using DI, we can use private because we only use that injected object within the component class and never in the template. That being said, if there is any use case where you need to inject something that needs to be used in the template, yes, you need public as well, but so far, that is not the case in any doc example.

**Comment by achimha** [comment]
@Foxandxss fantastic explanation, thanks for taking the time!

**Comment by aluanhaddad** [comment]
@Foxandxss Thank you for the clarification, but I believe that given what you say 
> That being said, with AoT, we sort of "convert" the template code to Typescript itself (again, Typescript, not any subset).

The TypeScript compiler does not emit TypeScript it emits JavaScript. By emitting TypeScript during AOT you have introduced an additional compilation phase which is only significant (and only a problem) because it has a different interpretation and affects the validity and static interpretation of code. 

This _is_ subsetting in the semantic sense because it means practically a user may not use TypeScript features, like the private modifier, in Angular components.

I think that either 1. the error should be suppressed, or 2. the AOT compiler should not emit TypeScript at all, or 3. the subset of language features available should be officially and formally documented.

**Comment by aluanhaddad** [comment]
Actually, for private properties at least, there is a way to provide correct static error checking, via TypeScript, that allows this error to surface correctly as part of the type level contract between the Angular `Component` decorator factory and the components they may be applied to. It is actually rather straightforward:
Angular should _require_ that all component properties be public.

Here is how this would work.
```ts
export declare function Component(options: ComponentOptions)
    : <Instance>(target: new (...args: any[]) => {
        [P in keyof Instance]: Instance[P]
    }) => typeof target | void;
```
Then when someone writes
```ts
import { Component } from './decorators';

@Component({}) export class MyComponent {
  p1: string;
  private p2: string;
}
```
they will receive the following error: 
```
Argument of type 'typeof MyComponent' is not assignable to parameter of type 
'new () => { p1: string; p2: string; }'.
  Type 'MyComponent' is not assignable to type '{ p1: string; p2: string; }'.
    Property 'p2' is private in type 'MyComponent' but not in type '{ p1: string; p2: string; }'.
```
Then you don't have a subset scenario (for private properties anyway) and you have made your API clearer, better, and more importantly transparent and easy to follow.

**Comment by DzmitryShylovich** [comment]
> Angular should require that all component properties be public.

why?

>  transparent and easy to follow.

it's already pretty easy to follow, just need to google 2-3 min...

**Comment by aluanhaddad** [comment]
> why?

Because it is better than working under JIT mode and failing under AOT.

> it's already pretty easy to follow, just need to google 2-3 min...

People shouldn't have to do that. APIs should express what they can. That is what types and documentation are about. Use them.

**Comment by DzmitryShylovich** [comment]
> Because it is better than working under JIT mode and failing under AOT.

there're ide, language service and codelyzer to report such issues. Plus they work to make aot a default so I don't see a problem here.

**Comment by aluanhaddad** [comment]
Why not express this in the Angular APIs? They don't express much as it is and could stand to express more.
A completely unrelated example is that `Component` currently looks like
 ```ts
export declare const Component: ComponentDecorator;
```
When it should look rougly like
```ts
export declare const Component: ComponentDecorator & SpecifiesTemplate;

export declare type SpecifiesTemplate = {
    template: string;
} | {
    templateUrl: string;
};
```
I can't think of a good reason not to do this.

Also, I don't use codelyzer since every time they update anything, which is frequent, it breaks tslint and tslint matters more.

**Comment by schungx** [comment]
Well, I second @aluanhaddad 's suggestion that `public` is required for Angular 2 components.  The fact that it works fine even when properties are declared `private` is an unfortunate by-product of Angular 2 emitting compiling to JavaScript which has no private properties.

A user of Angular 2 should not need to know that `private` is not supposed to work (but actually works due to the oddities of JavaScript).

Now, all `private` properties continue to work merrily, with the poor user writing millions of lines of Angular 2 code, only to find that when compiled AOT they suddenly generate thousands of errors!

Said poor user would then have to manually correct all the `private` properties into `public` ones... cursing all the way whoever who decided in the first place that documentation is not needed.

So, I believe somewhere in the Angular 2 docs should be words saying "WARNING: LARK'S VOMIT" in big bold letters, followed by: "DO NOT USE PRIVATE PROPERTIES FOR BINDING, OR AOT WON'T WORK.  YOU HAVE BEEN WARNED!"

**Comment by WilliamKoza** [comment]
I think you are right @schungx. So, maybe we can suggest adding a rule in guide style angular.io to explain this.

**Comment by aluanhaddad** [comment]
I think it is pretty simple. Put it in the `.d.ts` files. The compiler will complain, you will remove `private`, problem solved. All of this will happen in JIT mode so that your code is ready for AOT. I agree with @wKoza that it should be part of the style guide as well. However, I don't understand why the type declaration files need to be vacuous. The tools are there, they should be used.

**Comment by robwormald** [comment]
@aluanhaddad put what in the d.ts file? The basic issue here is that in JIT mode, angular's compiler runs *after* TS, and in AoT mode it runs before TS. JIT uses reflection, at runtime, long after the type information has been stripped out.

**Comment by aluanhaddad** [comment]
@robwormald put this into the `.d.ts` file
```ts
export declare function Component(options: ComponentOptions)
    : <Instance>(target: new (...args: any[]) => {
        [P in keyof Instance]: Instance[P]
    }) => typeof target | void;
```
This will cause a descriptive compile time error from TypeScript regardless of the compilation phase.

**Comment by aluanhaddad** [comment]
```ts
import { Component } from '@angular/core';

@Component({}) export class MyComponent {
  p1: string;
  private p2: string;
}
```
**ERROR**:
```
Argument of type 'typeof MyComponent' is not assignable to parameter of type 
'new () => { p1: string; p2: string; }'.
  Type 'MyComponent' is not assignable to type '{ p1: string; p2: string; }'.
    Property 'p2' is private in type 'MyComponent' but not in type '{ p1: string; p2: string; }'.
```

**Comment by DzmitryShylovich** [comment]
But I don't want to make **all** component fields public :)

**Comment by aluanhaddad** [comment]
The are all public at runtime, the APIs of components are rarely used by users, and it is better than the current situation.

**Comment by wKoza** [comment]
@robwormald  Do you think it would be correct to always advocate putting templates fields public ?

**Comment by robwormald** [comment]
As @DzmitryShylovich says, there are plenty of use cases for having private fields in components, especially when injecting/querying for parent/child components. Enforcing public for every property/method on a component defeats the purpose entirely. 

Our long term plan is to have AoT be the default here anyway. I don't think we're going to force this behavior on users. 

That said, it's worth documenting this more clearly. We'll look at that in the new year.

**Comment by aluanhaddad** [comment]
That is highly disappointing. Right now the tools that users have available to them do not tell warn them at all. You are creating a pit of failure for users instead of a pit of success. I don't understand why. The reasons you provide are insufficient. It is better for user code to have a slightly more cluttered public API than it is for user code to fail for reasons unbeknownst to them.

**Comment by DzmitryShylovich** [comment]
We just need to add this https://github.com/rangle/angular-2-aot-sandbox into docs

**Comment by aluanhaddad** [comment]
Finally some documentation. Sure looks like a subset to me...

**Comment by wKoza** [comment]
@robwormald  I'm all right when injecting/querying for parent/child components ...  it's a shame in this case.

**Comment by schungx** [comment]
Looking through the sandbox docs, and *now* I find out that default exports won't work...   [cry]

**Comment by aluanhaddad** [comment]
@schungx How could you possibly have known that the recommended [pattern when only exporting a single function or class in TypeScript](http://www.typescriptlang.org/docs/handbook/modules.html)
is incompatible would be a failure point?
> If you’re only exporting a single class or function, use export default

Seriously this is shameful. Angular 2 team tells people to use specific tools, tell them that those tools will help them catch errors, fails to document their own restrictions and dramatic semantic differences (`export function f` is not like `export var f = function`? broken), fail (or outright refuse) to leverage said tools to prevent these errors (even though error detection is the point of said tools), and then try to pull a fast.

**Comment by schungx** [comment]
Well, calm down.  I think they'll address these issues in good time...  Just that they are not working *now*...

**Comment by hokkaido** [comment]
While I don't think the Angular team owes us anything, I actually agree with that sentiment. I was at last year's AngularConnect in London: you had the Angular team hyping AOT (15KB claims) quite a bit, and making promises about improvements in documentation and having a saner versioning policy. 

Yet now here we are, there is AOT, released and out in the wild, yet it's barely documented, you need external community projects from companies like Rangle to figure out what works and what not. What about just not releasing this stuff until it's ready and adequately documented?

**Comment by Foxandxss** [comment]
Could you please specify what you find missing in the docs?

**Comment by felyperennan** [comment]
I think there is a severe problem in having component-specific stuff accessible to other components, because then you can have parent components tweaking those and making the internal component logic break, thus causing the component to be unreliable.
By the other hand, if you cannot access component-specific things from its template, then it's quite hard to, at all design the template.
And in angular logic, the component is a complete self-contained "thing", it's controller, view and model are still part of a same "whole", thus in theory having the template access component's private stuff makes a lot of sense and provides with well encapsulated self-responsible components.
For example, if I have a dialog-box.component, i want to expose functions that open and close it, in the open functions I want the title and description to be passed, if its an OK or YES/NO dialog, i want to receive a lambda for OK, YES and NO, but I don't want the external component to access the model directly or directly invoke OK/YES/NO functions, but I still need to access the model and those functions from the template so that the component works.
Does my point make any sense? I hope so.

**Comment by Wim-van-der-Veen** [comment]
I just recently ran into this problem, and completely agree with @felyperennan . Private definitions are there for a reason and should not be abandoned. As @Foxandxss already stated at 24 oct: 'the typescript compiler (and your editor) will complain if you try to access a private variable from where you can't do that'. Usefullness proven, me thinks.
If ES5 doesn't support privateness, AOT should provide a way to compile private declarations neatly, not mark it as an error. That's just giving up on a very useful construct!

**Comment by trotyl** [comment]
When using the native [JavaScript private property](https://github.com/tc39/proposal-class-fields) in the future, **it won't work in either JIT or AOT**, so the only way to keep consistency is to make it public, or there would be a new inconsistency between (real) JavaScript private property and (fake) TypeScript private property.

**Comment by Jopie64** [comment]
I agree with @felyperennan and @Wim-van-der-Veen . Isn't there a way that the component class can reference to its associated template, which is supposedly a new class, as friend like in C++? Or maybe the template could be compiled in a class that extends the component class so that the members can at least be declared protected instead of public?

**Comment by anjmao** [comment]
Philosophical questions. If AOT compiler does not allow private properties in template does this mean that component's template does not belong to it's component?...

**Comment by aluanhaddad** [comment]
> When using the native JavaScript private property in the future, it won't work in either JIT or AOT, so the only way to keep consistency is to make it public, or there would be a new inconsistency between (real) JavaScript private property and (fake) TypeScript private property.

@trotyl that is true. There is already going to be significant cognitive dissonance between TypeScript `private` and JavaScript `private` and it is going to cause a lot of pain for those invested in compile time privacy.

As you say, the best way to handle it is to not use `private` or `protected` at all. 

Writing less code will make the transition easier. `public` is the default and will continue to be in JavaScript.

**Comment by trotyl** [comment]
@aluanhaddad Actually (TypeScript's) `private` properties are supported in v6 with the new compiler/renderer structure. While I won't recommend that in near future, it will be possible to binding `private` properties in v6 app or v6-only libraries.

**Comment by thinkingmedia** [comment]
I've been struggling with this problem on a large Angular project. It becomes an issue for `exportAs` on components that contain methods that *mutate* the inner state. More precisely, **public** methods/properties used **only** by the template are being called by `exportAs` references from other template. The issue continues for components used in dependency injections.

As a programmer I can't safeguard my own components from abuse if everything is public. Other programmers assume the *autocomplete* features in their IDE show them a safe list of properties/methods.

I needed a solution to stop bugs and this is what I came up with. Like it or not it works.

```
interface ExampleView {
     title: string;
     onClick();
}

@Component({
       selector: 'example',
       template: `
              <span>{{view.title}}</span>
              <button (click)="view.onClick()"></button>
       `
})
export class ExampleComponent {
        protected title: string;
        protected onClick() { return; }
        public get view(): ExampleView { return <any>this; }
}
```

This is kind of a *dirty* hack to get around AOT compiling and type checking, but it's much easier to tell other developer. **DO NOT USE THE view PROPERTY**

This allows me to define everything guarded as protected and also export it to the template via `view` with little runtime overhead.

I hope this helps other people.

**Comment by cosminadrianpopescu** [comment]
What's wrong with changing the code that AoT is generating to this:

```
createInternal(rootSelector:string):import3.AppElement {
  const parentRenderNode:any = this.renderer.createViewRoot(this.declarationAppElement.nativeElement);
  this._el_0 = this.renderer.createElement(parentRenderNode,'div',(null as any));
  this._text_1 = this.renderer.createText(this._el_0,'',(null as any));
  this._expr_0 = import7.UNINITIALIZED;
  this.init(([] as any[]),[
    this._el_0,
    this._text_1
  ]
  ,([] as any[]),([] as any[]));
  return (null as any);
}
detectChangesInternal(throwOnChange:boolean):void {
  this.detectContentChildrenChanges(throwOnChange);
  const currVal_0:any = import4.interpolate(1,'',this.context['name'],''); // <-- notice the cange of the property
  if (import4.checkBinding(throwOnChange,this._expr_0,currVal_0)) {
    this.renderer.setText(this._text_1,currVal_0);
    this._expr_0 = currVal_0;
  }
  this.detectViewChildrenChanges(throwOnChange);
}
```

**Comment by trotyl** [comment]
@cosminadrianpopescu Then you loose type-checking completely.

**Comment by cosminadrianpopescu** [comment]
what type checking between the template and the component?

**Comment by trotyl** [comment]
@cosminadrianpopescu Given that it's already supported in ivy, it make no sense to find another worse solution for that.

**Comment by cosminadrianpopescu** [comment]
> Given that it's already supported in ivy, it make no sense to find another worse solution for that.

What exactly is available in `ivy`? Excuse my ignorance, I've just checked `angular ivy`, but just a quick view I don't exactly understand what you are saying. Could you please be more explicit?

PS: Thanks for taking the time to explain a little more in detail.

**Comment by trotyl** [comment]
> What exactly is available in ivy?

Accessing `private` component property in template is available, without losing type-checking.

**Comment by cosminadrianpopescu** [comment]
Aha. Ok. Thank you very much for info. So I suppose in Angular 6 this is not an issue anymore. Is good know.

**Comment by trotyl** [comment]
Likely ivy would not be turned on by default in v6 (but still behind a flag like now), it's a big refactoring and would require time to prove (to make sure everything works fine)...

**Comment by cosminadrianpopescu** [comment]
Since I don't find any official documentation of `Ivy`, do you have a link? I suppose `Ivy` is also AoT compiling, right?

**Comment by trotyl** [comment]
No, there is indeed no official documentation of Ivy, you're totally right about that... 😃 

<sub>Both AOT or JIT would still be there.</sub>
