### ISSUE TITLE
Angular 2 upgrade tools are incompatible with Content Security Policy

### ISSUE THREAD

**Issue by jonrimmer** [angular/angular#12001]
**I'm submitting a ...**

```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior** 

If the web server Content Security Policy for scripts does not contain "unsafe-eval" (as per [Google's security guidelines](https://developer.chrome.com/extensions/contentSecurityPolicy#relaxing-eval)), then apps bootstrapped using the Angular 2 upgrade tools do not work.

**Expected behavior**

It should be possible to use the Angular 2 upgrade alongside the a safe CSP.

**Reproduction of the problem**

https://github.com/jonrimmer/ng2-upgrade-csp-problem
- If you disable the upgrade bootstrapper and use the Angular 1 bootstrapper, the app works.
- If you add "unsafe-eval" to the CSP configuration for the webpack-dev-server, the app works.

Therefore, the problem is definitely a combination of using the upgrade tools and the CSP.

**What is the motivation / use case for changing the behavior?**

Security. Ease of upgrade.

**Please tell us about your environment:**

macOS 10.12
- **Angular version:** Angular 1 — 1.5.8, Angular 2 — 2.0.1
- **Browser:**  All

**Comment by fredericoramos78** [comment]
+1

**Comment by gkalpak** [comment]
UpgradeAdapter's `bootstrap()` method internally delegates to `angular.botostrap()` (after some preparation work), so it doesn't really make any difference. The violation is caused by Angular's JIT compiler (not AngularJS or ngUpgrade).

This is a known issue and has been reported before (e.g. #1744, #5956, #6361, #11939). Using the AoT compiler should avoid such issues. (Sidenote: AoT will soon be the default(/only?) mode.)

For hybrid apps, you need to use the [@angular/upgrade/static][1] package (instead of the old [@angular/upgrade][2]), which is AoT-compatible. The [upgrade guide][3] has more info on how to build AoT-compatible hybrid apps.

[1]: https://angular.io/api/upgrade/static
[2]: https://angular.io/api/upgrade
[3]: https://angular.io/guide/upgrade
