### ISSUE TITLE
WebWorker imperative Views

### ISSUE THREAD

**Issue by mhevery** [angular/angular#1207]
This issue discusses changes needed to #1088 in order to make it WebWorkers compatible. The sticking point is that the #1088 example injects `ShadowDOM` which has reference to DOM. The solution to this is to split the responsibility into two App Component part and Render Component part and then allow injecting the Render Component part communication channel into the App Component.

### App Side

```
@Component({
  selector: 'line-chart',
  bind: {
    'data': 'data'
  }
})
@View({
  renderer: 'LineChartRenderer'
})
class LineChart {
  constructor(bus: MessageBus) {
    bus.listen((data) {
      // do something when you get a message from the Rendere
    });
    
    bus.post('some serializable data');
    bus.post('init');
  }
}
```

### WebWorker Side

```
redererRegistry.register('LineChartRenderer', LineChartRenderer);

class LineChartRenderer {
  // fixed injection
  constructor(dom:RenderComponentDom, bus: MessageBus) {
    bus.listen((data) {
      if (data == 'init') {
        dom.root.innerHTML = '<div style="border: 1px solid red;"></div>
        var div =dom.root.firstChild;
        var content = dom.createContent(); // Must use this API to create '<content>'
        content.append(div); // project will works as expected.
        bus.post('done');
      }
    })
  }
}
```

**Comment by tbosch** [comment]
This is very close after the latest simplifications to the render layer.

The `LineChartRenderer` would extend from `DomRenderer`.

Instead of the MessageBus we will use actions or special bound element indices for app side -> render side, and events for communicating from render -> app side.

The general idea for this communication is to assume that parts of the template of a component can be "virtual" in that the element does not exist in the DOM but is used for communicating actions/property values to the renderer and receiving events from it.

**Comment by tbosch** [comment]
Implementation notes:

* Create a `RendererDispatcher` that also implements the `Renderer` interface and forwards calls to the right `Renderer` implementation.
* `RenderViewRef` / `RenderProtoViewRef` should already contain a `renderer` property so this dispatcher does not need to know anything about the concrete `ProtoView`/`View` classes.
