### ISSUE TITLE
Allow Pipes to be substituted with a passthrough in tests

### ISSUE THREAD

**Issue by chrisnicola** [angular/angular#12080]
**I'm submitting a ...**  (check one with "x")
```
[x] feature request
```

**Current behavior**
Currently pipes used by components have to be imported in the tests and declared as part of the testing module. Most of the time this isn't necessary for testing and in decreases isolation,

**Expected behavior**

I would like it if pipes could be easily substituted in tests with simple pass throughs or even just a custom transform function. It would help improve the isolation of component tests.

**What is the motivation / use case for changing the behavior?**

Less dependencies in tests.

**Comment by tbosch** [comment]
This is also true for directives. In your case the pipes might be not relevant, on other cases they are. E.g. the `async` pipe is changing the data type and just no oping it would break the template.

To make your tests simpler, define an own `NgModule` that already includes the pipe, ... and import that in your test module.

**Comment by chrisnicola** [comment]
I'm not saying that a no-op is the ideal solution, just one possibility for a default substitute. However pipes should allow for test substitutes to be provided. Not allowing for substitution of what is really a dependency seems to goes against the test-first principles that Angular 2 appears to promote.

**Comment by francosioquim** [comment]
**I'm submitting a ...**  (check one with "x")
```
[x] feature request
```

**Current behavior**
Currently pipes used by components have to be imported in the tests and  
declared as part of the testing module. Most of the time this isn't  
necessary for testing and in decreases isolation,


**Expected behavior**

I would like it if pipes could be easily substituted in tests with simple  
pass throughs or even just a custom transform function. It would help  
improve the isolation of component tests.

**What is the motivation / use case for changing the behavior?**

Less dependencies in tests.

-- 
You are receiving this because you are subscribed to this thread.
Reply to this email directly or view it on GitHub:
https://github.com/angular/angular/issues/12080
