### ISSUE TITLE
how to inject angular1 service into angular2 =2.0.0 test spec with jasmine

### ISSUE THREAD

**Issue by lokeshnagpal** [angular/angular#12110]
I upgraded my angular1 application to angular2, some of the services like angularcache in angular1 injected into angular2 component.It is working fine when running angular2 component.But while writing a test case for the same component then i am not able to inject it.

Getting an error:
"Error: No provider for AngularCacheService"

**Comment by DzmitryShylovich** [comment]
Your question sounds like a support request.
Please use the issue tracker only for bugs and feature requests.
Use [gitter](https://gitter.im/angular/angular) and [StackOverflow](http://stackoverflow.com/questions/tagged/angular2) for support request.

**Comment by francosioquim** [comment]
I upgraded my angular1 application to angular2, some of the services like  
angularcache in angular1 injected into angular2 component.It is working  
fine when running angular2 component.But while writing a test case for the  
same component then i am not able to inject it.

Getting an error:
"Error: No provider for AngularCacheService"

-- 
You are receiving this because you are subscribed to this thread.
Reply to this email directly or view it on GitHub:
https://github.com/angular/angular/issues/12110

**Comment by chuckjaz** [comment]
@francosioquim Please use the issue tracker only for bugs and feature requests.
Use [gitter](https://gitter.im/angular/angular) and [StackOverflow](http://stackoverflow.com/questions/tagged/angular2) for support request.
