### ISSUE TITLE
Animations not triggering when using ngFor with components

### ISSUE THREAD

**Issue by benetis** [angular/angular#12117]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**

Animations are not shown upon creation/deletion of component in ngFor.

**Expected behavior**

Animations should work the same for components and html elements in ngFor

**Minimal reproduction of the problem with instructions**

1. Add animation on component which is being created using ngFor

Example: https://plnkr.co/edit/yCIIunPdjf3TvokvrQ2z?p=preview

**Please tell us about your environment:**

macOS Sierra, Webstorm, 

* **Angular version:** 2.0.1

* **Browser:** [Chrome stable, Firefox stable]

 
* **Language:** Typescript 2.0.2

**Comment by matsko** [comment]
Looking into it. Thank you.

**Comment by matsko** [comment]
This is not a bug. This is just a shortcoming of Angular components. Since `c-li` isn't a known HTML tag (but a custom component), you need to put `c-li { display:block; }` somewhere within the global styles for the website (I put it into `index.html` file).

https://plnkr.co/edit/fevZLjFE0AS1HluhzjtE?p=preview
