### ISSUE TITLE
Pin Angular & dependency versions in plunkers for repros

### ISSUE THREAD

**Issue by StephenFluin** [angular/angular#12123]
When we refer developers to http://plnkr.co/edit/tpl:AvJOMERrnz94ekVua0u5?p=preview for reproducing issues, this currently refers to the latest npm release.

Instead, developers should be using a version of the plunker that is pinned to specific versions of Angular (eg 2.0.2 or 2.1.0-beta0) and all of its dependencies (rxjs, zones, etc).

This plunker could be auto-generated as part of our build/deployment process.

We will need to update the issue template to use these generated plunkers, or use an intermediate wiki or markdown page referring to the latest versions.

**Comment by gkalpak** [comment]
I think this is now obsolete. The Angular (and dependencies) versions should be taken care of by the StackBlitz Angular template.

If someone needs different versions, they are easy to change via StackBlitz's UI and this seems to have been working fine for a while (I haven't heard of any complains or run into difficulties myself).

Feel free to re-open, if you think otherwise or I've missed anything
