### ISSUE TITLE
When property is updated from outside the class, the view is not updated

### ISSUE THREAD

**Issue by plantain-00** [angular/angular#12143]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
When property is updated from outside the class, the view is not updated

**Expected behavior**
When property is updated from outside the class, the view is updated respectly

**Minimal reproduction of the problem with instructions**
http://plnkr.co/edit/cPV9YpiPomzJNDpBWlQJ?p=preview
the `messages` property is updated every 3s, the view should be updated too.

**What is the motivation / use case for changing the behavior?**
My data comes from a websocket connection, when I update the related property, the view didn't change. 

**Please tell us about your environment:**
Mac 10.10.5, VS Code, npm, nodejs

* **Angular version:**
2.0.2

* **Browser:** 
Chrome 53
 
* **Language:** 
TypeScript 2.0.3

**Comment by woppa684** [comment]
Everything you do from within your app itself runs in the Angular zone. The timeout is started from global space so it runs in the root zone.  If you make a websocket connection from within your application it will work as expected (except in IE due to this bug https://github.com/angular/zone.js/issues/468). If you need/want to create the connection from outside angular you need to either call change detection manually or run your 'func' in the NgZone like in this fork of your plnkr: http://plnkr.co/edit/l1K6ywQyLB6hVztjDlyX?p=preview

**Comment by plantain-00** [comment]
@woppa684 thanks, it works
My real case is more complicated, I used socket.io, not the raw websocket, it works in debug mode, when I use `enableProdMode();`, it will not work. NgZone can fix this.
