### ISSUE TITLE
AOT compilation produces failing JS output (ng_module_factory.js?95b1:13 Uncaught SyntaxError: Unexpected token import)

### ISSUE THREAD

**Issue by jetlogs** [angular/angular#12220]
**I'm submitting a ...**  (check one with "x")
```
[x ] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
the current app is a combination of the webpack + aot cookbook based on the angular docs
https://angular.io/docs/ts/latest/cookbook/aot-compiler.html
https://angular.io/docs/ts/latest/guide/webpack.html

I have a working POC where you can replicate the issue from this repo:
https://github.com/jetlogs/Angular2-AOT-Localization

after you've done the compilation / bundling, you can open the 2 files:
aot.html - this file fails with:
```
ng_module_factory.js?95b1:13 Uncaught SyntaxError: Unexpected token import
```

non-aot.html - this is the non-aot version of the same app, and it loads fine

**Expected behavior**
the expected behavior is that aot.html and non-aot.html should have the same behavior

**Minimal reproduction of the problem with instructions**

clone this repo:
https://github.com/jetlogs/Angular2-AOT-Localization

run these commands on the working directory:
```
npm install
npm postinstall
npm run build
```

then open aot.html to reproduce the issue

**What is the motivation / use case for changing the behavior?**
to be able to run AoT with webpack for localization

**Please tell us about your environment:**
OS: windows 10
* **Angular version:** 
2.0.0
* **Browser:** 
 all browsers
* **Language:** TS 2.0.2
* **Node (for AoT issues):** `node --version` =   node 6.7.0

**Comment by pkozlowski-opensource** [comment]
AoT is producing TypeScript that needs to transpiled / packaged before loading in a browser. The issue seems to be related to your tooling setup as I was getting through the https://angular.io/docs/ts/latest/cookbook/aot-compiler.html just yesterday and had everything with Rollup, ex.: https://github.com/pkozlowski-opensource/ng-bootstrap-aot

This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`. If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).

If you believe that the documentation should be updated please open a separate issue in https://github.com/angular/angular.io where documentation lives.
