### ISSUE TITLE
MicroTaskQueue

### ISSUE THREAD

**Issue by mhevery** [angular/angular#1224]
# Goal

To be able to execute Promises `then()` in the current VM turn.

* [x] Design `MicroTaskQueue`
* [x] Replace native `Promise` with a polyfill which uses `MicroTaskQueue`. The polyfill must use `MicroTaskQueue` on resolving the `Promise`.
* [x] Because native API uses native `Promise`s instance, we have to monkepatch native `Promise.prototype.then` to convert native to pol.
* [x] Have a `MicroTaskQueueZone` which captures and drains the `MicroTaskQueue` on VM turn end.
* [ ] Change `ChangeDetector` to drain the `MicroTaskQueue` every time we transition to child component sub-`ChangeDetector` (not child `ChangeDetector` in the current shadow DOM, ie `ForOf`)

## `MicroTaskQueue`

```
class MicroTaskQueue {
  static current:MicroTaskQueue;

  runAsync(unitOfWork:Function);
  
  drain();
}
```

## Polyfill `Promise`

We need a Promise, whoes `resolve`/`reject` method enques work on `MicroTaskQueue.corrent.runAsync()`. The enqued function then resloves the `Promise` synchronously. If `MicroTaskQueue.current` is not defined, then use normal system `Promise` resolution (ie default to macro task).

## `MicroTaskQueueZone`

We need a zone implementation which can create a new `MicroTaskQueue.current` for the current duration and drain it on the end and restore the value to previous state. 

## `ChangeDetector`

We need to be able to process `Promise`s quickly, and so they should be drained `MicroTaskQueue.current.draing()` at the begining of entering into a new component. (Don't drain on the current component sub views, such as ForOf loops). This means that a parent component can give a promise to a child, but not the way around. This is consistent with how data is propagated, and should not cause any surprises. (`Promise`s can be given to children but not to parents.)

**Comment by alexpods** [comment]
I really like some third part Promise libraries, such as [bluebird](https://github.com/petkaantonov/bluebird). It will be possible for me to use it? With `zone.js` I would have to patch its methods.

```js
import Promise from 'bluebird';

Zone.patchPrototype(Promise.prototype, ['then', 'catch', 'finally' ]);
```

t will be possible to patch it with microtask support?

**Comment by vicb** [comment]
Discussed this further with Misko. We'll do it in 2 phases:
- add support for (Promise only) microtasks,
- drain the microtask from the change detection once we are comfortable with it.

The support for microtasks needs to be built-in in zone.js because the Promise monkey patch (/polyfill) is tied with zone implementation.

@alexpods in the context of angular, the microtask queue draining is initiated by zone.js then there is no need to schedule tasks with any of "setTimeout/setImmediate/MutationObserver". Our will is that any 3rd party lib could be used on top of our Promise monkey patch (/polyfill) - as long as they do not overwrite the mkp/polyfill.

**Comment by vicb** [comment]
Closing as most todo items are part of #1574.
@mhevery what about opening an other issue if the change detector should drain the queue. As of today the queue is the broowser queue / the Dart queue and is not exposed to NgZone.
