### ISSUE TITLE
Angular LTS version

### ISSUE THREAD

**Issue by RatkoR** [angular/angular#12331]
**I'm submitting a ...**  (check one with "x")

```
[ ] bug report => search github for a similar issue or PR before submitting
[X ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**What is the motivation / use case for changing the behavior?**

We're building a rather large project that will take months (years) to finish. Although we're really pleased with the semver versioning and that you always list all potentially breaking changes it might be a big step to know that you're also thinking about LTS versions. Specially now that you have described the half-year cycle of big changes.

We try to pick LTS versions for servers, server side scripts, anything we work with. That's the only way to still have time and focus on developing our app for a longer period.

Angular is important and special (and a really great tool), but looking from our point of view it's _one_ of the tools. And if we were to update all of them at each new version, we wouldn't have time for anything else.

**Comment by spock123** [comment]
Sounds like 2.0.x to me...

**Comment by kylecordes** [comment]
I think most typically a project would select the "final", or close to it, version of a major version sequence as LTS. So maybe right before 3.0, the final 2.N might end up LTS?

For that matter, is there even be a need for any 2.x version to be LTS? If 3.x ends up backward-compatible (perhaps with deprecation warnings) with 2.x applications, may be the final 3.x will be the first time a version needs to be "promoted" to LTS.

**Comment by ufoscout** [comment]
We are facing the same issue.
We have an enterprise portal-like solution whose frontend is moving to Angular2. The portal has third party plugins and external modules. The six-months release cycle is too short for us as we cannot force all the plugin maintainers to rebuild every six months; at the same time not upgrading could lead to even bigger issues due to old/buggy external dependencies or due to a too fragmented ecosystem (what happens if library X has moved to ng3 but library Y is still on ng2? etc...).
An LTS release would be the natural answer for the needs of the enterprise world; it will permit framework and libraries maintainers to offer a "stable" and an "edge" release.

**Comment by evoratec** [comment]
@ufoscout You are absolutly right. The most terrible example of this is Angular Material.

**Comment by kylecordes** [comment]
A couple of weeks ago at ng-conf, the Angular team mentioned something about Angular 4 as the first LTS version. I don't see anything published on the Angular website or blog about it yet. I imagine the details will be worked out and published in the coming months... the whole idea of LTS is that it happens slowly!

**Comment by IgorMinar** [comment]
Our LTS commitment is documented here: https://github.com/angular/angular/blob/master/docs/RELEASE_SCHEDULE.md#long-term-supported-lts-versions
