### ISSUE TITLE
AOT does not generate code that typechecks the elvis operator

### ISSUE THREAD

**Issue by rkirov** [angular/angular#12352]
**I'm submitting a ...**  (check one with "x")

```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**

``` typescript
class Cmp {
  foo: {a: string};
  ...
}
```

template for Cmp

``` html
<div>{{foo?.crazyPropertyNameThatDoesntExist}}</div>
```

 compiles  with AOT compiler

**Expected behavior**
There should be a type error during AOT compilation.

/cc @tbosch

**Comment by tbosch** [comment]
@chuckjaz could you add a comment why we loose the types here, and your suggested solution?

**Comment by chuckjaz** [comment]
We currently lose the type when we have to save the intermediate result into a temporary variable as declaring the type of the temporary variable requires type information we don't have at the time we generate the code.

In this case, however, we don't need the temporary and we should be generating the expression `component.foo == null ? null : component.foo.crazyPropertyNameThatDoesntExist` so you should see the error.

**Comment by chuckjaz** [comment]
Playing with this a bit in TypeScript 2.0 I came up with the following:

Assume you have the following interfaces:
```ts
interface Zoo {
  s: string;
}

interface Goo {
  z: Zoo | undefined;
}

interface Bar {
  g: Goo | undefined;
}

interface Foo {
  b: Bar | undefined;
}
```

and you have a component with that is something like:
```ts
@Component({template: '{{getFoo()?.b?.g?.z}}'})
class MyComponent {
  getFoo(): Foo | undefined {
    ...
  }
}
```

We could generate the following:

```ts
function defined<T>(v: T | undefined | null): T { return undefined as any; }

var t1 = (undefined as any) && component.getFoo();
var t2 = (undefined as any) && defined(t1).b;
var t3 = (undefined as any) && defined(t2).g;
var t4 = (undefined as any) && defined(t3).z;

var value = (t1 = component.getFoo()) == null ? null : (t2 = t1.b) == null ? null : (t3 = t2.g) == null ? null : (t4 = t3.z) == null ? null : t4.s;  
```

In 1.8 we wouldn't need the `defined()` helper (nor would the `| undefined` be legal) so we could generate:

```ts
var t1 = (undefined as any) && component.getFoo();
var t2 = (undefined as any) && t1.b;
var t3 = (undefined as any) && t2.g;
var t4 = (undefined as any) && t3.z;

var value = (t1 = component.getFoo()) == null ? null : (t2 = t1.b) == null ? null : (t3 = t2.g) == null ? null : (t4 = t3.z) == null ? null : t4.s;  
```

Unfortunately, because `undefined` and `null` are not types in 1.8, there is no one version that works with both 1.8 and 2.0 with and without strict null checks.

This code has the draw-back that generates more code as it includes expression twice though one form will not be executed. It would be nice if [#6606](https://github.com/Microsoft/TypeScript/issues/6606) was implemented which would give us:

```ts
var t1: typeof component.getFoo();
var t2: typeof defined(t1).b;
var t3: typeof defined(t2).g;
var t4: typeof defined(t3).z;
```

I believe we can implement this immediately as we can detect which version of TypeScript `ngc` is using and then generate the correct version of the code above.

**Comment by JoostK** [comment]
This is supported in the Ivy template type checker and can be configured using the `strictSafeNavigationTypes` option.
