### ISSUE TITLE
Testing entry points are hard to configure via SystemJS

### ISSUE THREAD

**Issue by gionkunz** [angular/angular#12358]
```
[ ] bug report => search github for a similar issue or PR before submitting
[X] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
Currently all modules contain their core contents as well as testing content. This is somewhat a structural hack and leads to unecessary complexity when it comes to module loading. When publishing a library as a bundle, a package should always consist of one single entry module, where with the current structure this is not the case. In all modules the core content entry point is `./bundles/xxx.umd.js` but for testing we'd need to rely on `./bundles/xxx-testing.umd.js`.

If we're mapping top level paths this would look something like this:
`import {X} from '@angular/xxx' => './@angular/xxx/bundles/xxx.umd.js'`
`import {TX} from '@angular/xxx/testing' => './@angular/xxx/bundles/xxx-testing.umd.js'`

This could already lead to path mapping / resolution issues depending on the module loading system, since the de-normalized sub-path `xxx/testing` is pointing to a different bundle. Also I've noticed that each Angular module contains a file `testing.js` in the root folder next to the `index.js`. In there, there's an import `module.exports = require('./bundles/xxx-testing.umd.js/index');` which is adding further confusion. I'd expect this to be `./bundles/xxx-testing.umd.js`.

**Expected behavior**
I know this is again a lot of module overhead, but wouldn't it make much more sense to extract all testing into separate packages?

This way we would have `@angular/core`, `@angular/testing-core`, `@angular/compiler`, `@angular/testing-compiler` ... and so on.

Following this approach all packages would have the same structure and path resolution would be much simpler.

**Minimal reproduction of the problem with instructions**

**What is the motivation / use case for changing the behavior?**
Lot of trouble mapping paths while testing Angular2 with SystemJS
## **Please tell us about your environment:**
- **Angular version:** 2.0.X
  2.0.1
- **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]
  all
- **Language:** [all | TypeScript X.X | ES6/7 | ES5]
  all
- **Node (for AoT issues):** `node --version` =  
  any

**Comment by UXabre** [comment]
Hello,



Was curious to learn if there are work arounds for the issue you mentioned?

"Also I've noticed that each Angular module contains a file testing.js in the root folder next to the index.js. In there, there's an import module.exports = require('./bundles/xxx-testing.umd.js/index'); which is adding further confusion. I'd expect this to be ./bundles/xxx-testing.umd.js."

Currently I try to load these testing.umd.js files but I always get a 404 because of the /index behind it. No matter which change I make in the config.js; it never seems to work :s

**Comment by IgorMinar** [comment]
The reexport issue have been resolved since this bug was opened, see https://unpkg.com/@angular/core@5.1.2/

But I agree that the location of testing umd bundles makes it difficult to configure stuff via SystemJS. We'll consider changing the location but that would be a breaking change and would require changes to the Angular Package Format.

Moving the testing code into separate packages is not something we are considering because that would double the number of npm packages that Angular application developers would have to install and maintain.

**Comment by JoostK** [comment]
Closing as obsolete, as UMD bundles are no longer part of APF v13.
