### ISSUE TITLE
DynamicComponent annotation does not support one way binding to dynamically loaded components

### ISSUE THREAD

**Issue by wesleycho** [angular/angular#1236]
This seems to be a problem that was investigated by SekibOmazic on the Gitter - [here](http://plnkr.co/edit/vmyTMfgJptkdj3D1NJpu?p=preview) is a Plunker. Each of the color components has data that is supposed to be passed into the component and displayed. `PrivateComponentLoader` does not seem to support an optional option for binding properties on the dynamic component to selectors on the dynamically loaded components, which prevents the dynamically loaded components from ever getting updates.

**Comment by SekibOmazic** [comment]
Plunk is updated to alpha.20 (with `DynamicComponentLoader`)
http://plnkr.co/edit/OInwAD1uFYW4LLwMnGib

**Comment by mhevery** [comment]
Our current thinking is that the dynamic component should delegate the bindings to the private component. Angular should not do anything magically. Can you tell us why this solution does not work?

**Comment by SekibOmazic** [comment]
@mhevery I also expect that the dynamic component only delegate bindings to the component it loads, but that doesn't work. 

If you look at the example plunk and comment out the constructor for `Red` component (lines 14-16), it will break with 
```Shell
Cannot read property 'name' of undefined in [I am a {{model.name}} box in Red]
```
If the dynamic component had delegated the binding we would have seen `I am a Red box`.

**Comment by mhevery** [comment]
So I updated your plunk slightly. As far as I can tell it works as expected: http://plnkr.co/edit/svTr77TDHlwBiMtSzjN2?p=preview

Bindings do not work across dynamically loaded components, and need to be passed in explicitly. This is by design. 

Also I saw you head `[model]="component"` Not sure what that was meant for but it is a noop and I removed it. 

Can this issue be closed?

**Comment by SekibOmazic** [comment]
@mhevery Thanks a lot. 

"Bindings do not work across dynamically loaded components, and need to be passed in explicitly. This is by design." - that was missing part. I'd suggest to add it to the docs or to comment the source code.

This issue can be closed.

**Comment by DannyMeister** [comment]
I highly wish that bindings did work across dynamically loaded components.  Otherwise, the dynamic component is forced to know about all the binding needs of the client components.

I am going to try to work around this in my application by forcing client components which are to be loaded by my host dynamic component to implement some sort of interface to help facilitate the delegation.
