### ISSUE TITLE
Reduced visibility for template variables

### ISSUE THREAD

**Issue by lqbweb** [angular/angular#12394]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => search github for a similar issue or PR before submitting
[ x ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
This fails:

```
<my-app>
    <my-dir #var>
        <span>var: {{ var.getValue() }}</span>
    </my-dir>
    <my-dir #var>
        <span>var: {{ var.getValue() }}</span>
    </my-dir>
</my-app>
```

**Expected behavior**
I kind of understand the motivation behind, but it seems a bit inconsistent to me with the fact that local variables on structural directives are (of course) only visible for the template.

Perhaps we should have global template variables visible for the whole template, and element template variables visible only for the element and its children.

This would definitely help on writing more functional templates.

**Comment by ShiftySituation** [comment]
Declaring a component variable (#myApp) is available to all siblings and children within a template.  If you want global variables, I'd suggest creating a class which holds the properties and inject it everywhere you need it.  Since they get the same instance, as long as it is declared in the root app, any value changes will reflect throughout the app.

**Comment by DzmitryShylovich** [comment]
> Declaring a component variable (#myApp) is available to all siblings and children within a template.

nope. it available for te whole template http://plnkr.co/edit/ZJK3CYgXhmUKNG0jrg2W?p=preview

**Comment by ShiftySituation** [comment]
ahh, so it is.  Now I'm wondering if this is a new change or I was misinformed.  Thanks for the clarification.

**Comment by DzmitryShylovich** [comment]
> we should have global template variables visible for the whole template, and element template variables visible only for the element and its children.

why? just use a different name for a variable?

**Comment by vicb** [comment]
missing:
- current behavior,
- expected behavior,
- repro

Thanks for reporting this issue. However, you didn't provide sufficient information for us to understand and reproduce the problem. Please check out [our submission guidelines](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-submitting-an-issue) to understand why we can't act on issues that are lacking important information.

If the problem still persists, please file a new issue and ensure you provide all of the required information when filling out the issue template.
