### ISSUE TITLE
Implement Missing Features for View

### ISSUE THREAD

**Issue by mhevery** [angular/angular#1239]
NOTE: Please add use cases for anything not yet covered here that should be considered.

Features currently missing from `@View`:
* [ ] More than one `@View` for a component
* [ ] Move CSS from `<style>@import()</style>` into `@View` annotation.
  - Needed for inlining during build step
  - Often times same HTML may have different CSS for styling
* Selectors:
  - CSS (as in `<button>` vs `<button ios-style>`)
  - `platform` as in iOS, android, desktop
  - screen size

**Comment by vicb** [comment]
- do we want to support both `@import` and `cssUrls` or the latter only ?
- not sure about the screen size selector (what happen if we switch from portrait to landscape after the template has been instantiated)

**Comment by mhevery** [comment]
I know we have been flip-floping on `@import` and `cssUrls` What do you think we should do? I am fine with both.

You are right that once the template is selected it can not be changed due to landscape/portrait. So we can only have fixed queries in there.

**Comment by vicb** [comment]
> I know we have been flip-floping on `@import` and `cssUrls` What do you think we should do? I am fine with both.

Why not support both ? (unless there is a downside for supporting `@import` ?)

**Comment by mhevery** [comment]
@vicb in general, we prefer to do things only one way. How much more complexity does it add to support `@import` as well?

**Comment by vicb** [comment]
Actually I think we need to support `@import` even in cssUrls imported stylesheets because we need to transform the whole CSS when the emulated strategy is used.

The code is not very complex and [already exists](https://github.com/angular/angular/blob/41262f42650cfbf8fdd494120817da30af9fb80f/modules/angular2/src/render/dom/shadow_dom/style_inliner.js).

**Comment by mhevery** [comment]
@vicb ok, sounds good to me.

**Comment by yjbanov** [comment]
re `@import` vs `cssUrl`:

Let's remember that the plan is to also make Angular 2 more statically analyzable by 3rd-party tools. Even if it does not add much complexity to Angular's own code we should avoid passing the buck onto 3rd-parties. I think we should pick one way to do this, not two.

As for which one it should be, the only thing I can think of is that by decoupling the template from the css file (i.e. the `cssUrl` option) a tool that analyzes or perhaps replaces urls only needs to know how to parse our annotations. It does not need to also know how to parse our templates. So `cssUrl` might be the better option of the two.

**Comment by yjbanov** [comment]
re `@Template` or now `@View`:

Haven't we already decided not to allow this? I feel like we should close this issue until we have stronger use-cases.

**Comment by mhevery** [comment]
Moving it to `@View` is needed for in-linetemplates into js in the same way we inline HTML. @jelbourn has more use cases for theming as to why this is needed.

**Comment by ericmartinezr** [comment]
Hey there, I know this is an old issue but it's still open so I'm avoiding to create a new one.

I've been looking on how to load dynamically a templateUrl, but I haven't found anything.

The issue https://github.com/angular/angular/issues/1002 referenced on OP makes a good point : What is proposed it's too limiting. 

For what I see in this issue there will be (or there is already) an option to add more than one View annotation to a component but that's just useful for different screen sizes, it is still going to need a hardcoded template/templateUrl.

But what about dynamic URLs? Would it that be possible? Based on the #1002 dynamic URL proposal I would propose something like this :

In this case it shows a default tpl, and when it detects a change to the property holding it, it will update the view
```JavaScript
@View({
	templateUrl : 'myDynamicTplUrl', // references to component's property
	lazy : true // Since that the 'myDynamicTplUrl' cannot be detected at compile time (I assume that's the case), 
	            // so make the view lazy to detect changes on 'myDynamicTplUrl'
})
class MyClass {
	constructor() {
		this.myDynamicTplUrl = 'my-default.tpl.html';
	}
	onInit() {
		if(condition) {
			this.myDynamicTplUrl = 'my-conditional.tpl.html';
		}
	}
}
```

Another case (not dynamic template URL, but assignable from a property)

I have, say 5+ components used just to hold a templateUrl

```HTML
<my-cmp url="tpl1.html"></my-cmp>
<my-cmp url="tpl2.html"></my-cmp>
<my-cmp url="tpl3.html"></my-cmp>
<my-cmp url="tpl4.html"></my-cmp>
<my-cmp url="tpl5.html"></my-cmp>
```

It is too much work to write 5 different components just to do the same job. So, we could do this 

```JavaScript
@Component({
	selector: 'my-cmp',
	properties : ['tplUrl: url']
})
@View({
	templateUrl : 'tplUrl'
})
class TemplateHolderComponent {
}
```

Does that make sense to you guys? In my opinion that would be a great feature.

Another and final question : Is it possible to extend the View annotation (or any)? Maybe that would be another solution.

Thanks,
Eric.

PS: Sorry for my english

**Comment by mattvot** [comment]
Has there been any progress in supporting multiple `@View` annotations?

**Comment by connorwyatt** [comment]
I would also be interested to know if this is still on the roadmap :)

**Comment by mhevery** [comment]
Post v2.0

**Comment by sallampalli** [comment]
I am surprised to see this as a missing feature. This was so easy to do in Angular 1.x.x. in directives, There will be lot many use cases which drive conditional templates/multiple Views. I might need the same component, its data, config etc. but a slightly different view . Something like this would have been great 
/*Just making this up as an example */
@Component({
selector: 'sample-selector',
properties: ['mode'], 
template:function(){
if(this.mode==='simple'){return '<h1 ngFor="....">{{.....}}</h1>';}
else{return '<button ngFor="...">{{...}}<button>'}
}
});

Is there another way to deal to achieve this ?

**Comment by oliverjanik** [comment]
+1

**Comment by IHateGlamour** [comment]
I'm more interested in this for inheritance, so that if I have a lot of forms with common fields and and functionality, I could create a base class with a view, and then derive from it adding in the remaining fields.

**Comment by zoechi** [comment]
@IHateGlamour I wouldn't expect this to happen, at least not soon. This is a very complex topic. Where to place the content from the child and where to insert the added content? At one place, at different places. What about `ngContent` in such extended templates. 
Polymer tried in 0.5 and they removed it. They haven't given up on the idea but it's just difficult to build and also difficult to use because of the involved complexity.
I'd rather stick with composition here instead of inheritance.

**Comment by mcferren** [comment]
need conditional templates!!! No need to make identical components if they share all the same functions. We just need to be able to add a function for the template: key ( that returns ` ... ` markup )

**Comment by intellix** [comment]
On the note of conditional templates, I added some comments to here: https://github.com/angular/angular/issues/2753 in regards to dynamically loading in templates/components. I also want the ability to have dynamic templates, looked towards DynamicComponentLoader and found it also not really possible to dynamically load those in.

**Comment by brian428** [comment]
To add to what @intellix said. it seems like it would be very useful to expose a utility function somewhere that can translate string values for module path and/or class name into a Type reference that can be passed to DynamicComponentLoader. (Since loadIntoLocation requires a component Type reference.)

Currently, the only options for doing this seem to be:
* Big switch/case statements (either in the component or off in some factory class) that must be manually kept up to date.
* Or, via non-trivial SystemJS calls. (e.g. normalize a module path, import it, and extract the Type reference from the loaded module).

If there was a helper function that wrapped the creation of a Type reference, that would go a long way towards easing the whole process of dynamically including a component. (Which, honestly, already seems way more complicated than it should be).

If you'd like me to create a separate issue for this, let me know and I'd be happy to.

**Comment by PavelPZ** [comment]
Maybe similar issue as #2753, #7596, #5131.

**Comment by NextLevelNoob** [comment]
Here is my use case. I want to write an ecucational app, where various content, written in html (but with angular-custom tags), is placed into an < app-maincontent > - Component.

There will be hundreds of such content-files, all to be placed into the same < app-maincontent > - Component, written by various content-writers, with no background in programming, who ideally should only know about writing html with some new custom-tags.

One "solution" might be to write a preprocessing-routine making an component out of every html-file, but that does not sound ideal to me. So yes, it would be very helpful to have this somehow supported or made easy/uncomplicated or have a preferred way of dealing with this being documented. Or maybe the angular-team or others could offer such a preprocessing-routine, so that it is well included eg as an add-on/option for angular-cli?

**Comment by nawalgupta** [comment]
I want to use different template for Mobile and Desktop. All the other things remain same.

Similar to 

```
@component
template:function(){
if(this.mobile){return ''<mobile-card/>";}
else{return '<desktop-card/>'}
}
templateUrl:function(){
if(this.mobile){return 'mobile.html";}
else{return 'broswer.html'}
}


```
What is the recommended way for doing this ?

**Comment by mhevery** [comment]
This is obsolete, and no longer relevant / actionable. To keep our issues clean, we are aggressively closing them.

**Comment by brian428** [comment]
Miško, if you're closing this, can you add a bit more please? I'm not sure how/why this is "obsolete". Has something changed in RC3 that makes these concerns irrelevant?

**Comment by defyjoy** [comment]
I am kind of interested too . How this became irrelevant and non actionable . Is there any solution to it ? Understood that to keep issues clean we need to close them  . But what is the resolution for this issue ? At least we deserve an answer to that ?

**Comment by nicksloan** [comment]
@mhevery It's pretty unhelpful to close an issue as "obsolete, and longer relevant / actionable" with no explanation at all. Can you provide some context?

**Comment by DzmitryShylovich** [comment]
@nicksloan if you have a feature request pls file a new issue
