### ISSUE TITLE
Router: CanActivateChild guards triggered once for every descendant

### ISSUE THREAD

**Issue by tdhsmith** [angular/angular#12410]
**I'm submitting a ...**  (check one with "x")

```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
If a `CanActivateChild` guard is attached to a route with non-leaf children, upon activation the guard will fire multiple times: once for every generation/level below it in the new activated route chain.

**Expected behavior**
As a naive developer, I would not expect any guard to fire multiple times during a single activation sequence (unless it was defined in multiple parts of the tree).

**Minimal reproduction of the problem with instructions**
See http://plnkr.co/edit/ucRkHp1B299qpApww4Y5?p=preview

Both of the 3-level `root/branch/leaf` routes trigger the root's `CanActivateChild` guard twice, as visible in the log.  The 2-level `root/leaf` only triggers it once. Not shown, but a 4-level route would trigger it 3 times.

**What is the motivation / use case for changing the behavior?**
For side-effect-laden guard operations, unexpected extra runs can be problematic.

Also, it's probably never a problem in practice, but performance is better too... for a branch of N child-guarded nodes, the current behavior runs quadratic checks instead of linear. (And for the single child-guarded root, it runs linear rather than constant.) 😉 

**Please tell us about your environment:**
Mac OSX, Atom, npm, webpack, served via webpack-dev-server (dev) & nginx (prod).
- **Angular version:** 2.0.X, 2.1.X
- **Browser:** Only tested in Chrome 53, but should be relevant to all
- **Language:** TypeScript 2

**Comment by vicb** [comment]
What is the router version?

**Comment by vsavkin** [comment]
The canActivateChild guard is called for every child of the route where it is defined.  Or to be more specific it runs for every child that is being activated.  And this is by design. 

Look at the signature of CanActivateChild. The first parameter is a child route that is being activated. We could have changed it to make the first parameter the array of the routes that are being activated, but I think the dev ergonomics of such a design is worse.

```
export interface CanActivateChild {
  canActivateChild(childRoute: ActivatedRouteSnapshot, state: RouterStateSnapshot):
      Observable<boolean>|Promise<boolean>|boolean;
}
```

If you want a guard to be called only once during an activation, you can use `CanActivate`. You can also use `childRoute.routeConfig` to filter out all the routes you don't care about.

**Comment by royling** [comment]
I also got confused on my first observation of the behavior, and thought this could be a bug...
Though this is by design as @vsavkin explained, I can't get the reason behind this.
For example, when navigating from `/` to `/a/b/c`, if canActivateChild guard is defined on path `a`, the guard will be executed twice, most likely returning the same result, but this is not necessary for most cases, IMHO.
Though we can change it to canActivate guard, then what's a good use case of canActivateChild guard? I can't imagine a use case where it's necessary to invoke the guard for each level of nodes.
