### ISSUE TITLE
Suggestion: Create an API on FormControl to focus the input

### ISSUE THREAD

**Issue by third774** [angular/angular#12463]
**I'm submitting a ...**  (check one with "x")

```
[ ] bug report => search github for a similar issue or PR before submitting
[x] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Suggestion** 

Create an API on FormControl that would easily allow the input to be focused without having to resort to bringing in Renderer or ElementRef.

**What is the motivation / use case for changing the behavior?**
This could be used widely to either easily focus the first input in a form after it is rendered, or focus inputs which have invalid data entered into them.

**Comment by kara** [comment]
We’re trying to keep our forms modules light and fast, and so it’s important to balance additions to the API with keeping the bundle size manageable. In cases like this where a relatively straightforward API already exists, the balance shifts in favor of avoiding unnecessary bloat to the code size. Consequently, we’ve decided not to add these API changes and will be closing the issue.  But keep the suggestions coming.

**Comment by jen-judd** [comment]
What is the relatively straightforward API?

**Comment by pcroc** [comment]
Hi @kara, "a relatively straightforward API already exists".

Please can you show how I could give focus to an invalid form control? Thanks.

**Comment by rafaelbiten** [comment]
I was looking for an answer for this same question and, to my surprise, there was even an unanswered SO question about this.

After reading this issue, I suspect that by `relatively straightforward API` they mean using `ElementRef` and calling `focus()` on the native element yourself.

[I left an answer with more details on the SO I mentioned above](https://stackoverflow.com/questions/43101154/set-focus-in-input-element-after-submit-and-reset-form/44803306#44803306). Please feel free to correct me or give a different answer there if there's another `more relatively straightforward API` than this.

Tks!

**Comment by pcroc** [comment]
Unfortunately that requires declaring an ElementRef for each form control. In the case of reactive forms with a dynamic form array, that won't work.

**Comment by sakiv** [comment]
@pcroc, You can define both, i.e. ElementRef and FormControl for same element and use the features.

**HTML:**
          <input #schoolControl name="school" placeholder="{{ 'PLACEHOLDER_SCHOOL' | translate }}" type="text" required mdInput [disabled]="loading"
            [mdAutocomplete]="autoSchool" [formControl]="schoolFormControl" />

**TS**
  @ViewChild('schoolControl')
  schoolControl: ElementRef;
  schoolFormControl: FormControl;

**Comment by pcroc** [comment]
Thanks, but that approach becomes difficult or impossible to use in all but the simplest of scenarios. I have a FormArray representing rows in a table, and each row has multiple controls. Something like this:

```
<tr *ngFor="let row of rows.controls; let index = index" [formGroupName]="index">
  <td>
    <input type="text" formControlName="value1">
  </td>
  <td>
    <input type="text" formControlName="value2">
  </td>
  <td>
    <input type="text" formControlName="value3">
  </td>
  <td>
    <input type="text" formControlName="value4">
  </td>
  <td>
    <input type="text" formControlName="value5">
  </td>
  <td>
    <input type="text" formControlName="value6">
  </td>
  <!-- Potentially many more controls ... -->
</tr>
```

Imagine that value5 in row 10 is invalid. I can find the invalid FormControl by simply looping through the rows, and the controls for each row. But how I can find the input element that corresponds to that FormControl, in order to focus it? What if some of the value controls are missing in certain rows?

Yes we can give each of input elements a name and use `ViewChildren` to access them, and then use some (perhaps non-trivial) arithmetic to work out which element is which control, but what a pain that is to write and maintain!

Now imagine that this template is part of a child component that is used within a parent form, and it is the parent form that wants to focus the invalid control? `ViewChildren` and `ElementRef` won't work here because the control is not part of the parent form's template.

**Comment by Thiltal** [comment]
this.form.get('item').focus() ... please reconsider

**Comment by logic01** [comment]
Focusing on an element is fairly universal for all websites. The `relatively straight forward api' is not straight forward at all! It becomes very cumbersome when doing anything relatively complex as pcroc and others have pointed out.

I would like to have this issue re-opened and re-considered. The number of Stack Overflow questions about how to focus on a AbstractControl are numerous and diverse. 

The implementation I will have to write is going to be a pain in the butt with this `straight forward api`.

**Comment by jks211** [comment]
This is a problem, not "straightforward".

**Comment by Gerros** [comment]
I encounter an ExpressionChangedAfterItHasBeenCheckedError when I set the focus via the native element due to the ng-touched (touched) property of the form not being set properly. Setting them manually via myFormControl.markAsTouched() solves the problem not entirely... still get some ExpressionChangedAfterItHasBeenCheckedError in certain cases. 
So it would indeed be great to have a focus method on the form control which takes care of all the properties to be set accordingly

**Comment by reajuria** [comment]
A 'dirty' workaround for our app was:

**HTML**
`<input #inputTech name="tech" type="password" autofocus onfocusout="this.focus()" matInput placeholder="Tech ID" (keyup)="doSomething($event)" [(ngModel)]="tech">`

**TS**
`ngOnInit() {`
`    this.router.events.subscribe((route: NavigationEnd) => {`
`      if (route.url === '/login') {`
`        const inputTech: any = document.querySelector('input[name=tech]');`
`        inputTech.focus();`
`      }`
`    });`
`  }`

This for a login form, since we can't find a way to focus when app returns to login.

PD: We know isn't a good practice ;) & `querySelector('#InputTech')` won't work

**Comment by pstahmer** [comment]
As @pcroc mentioned the idea of declaring both a `FormControl` and an `ElementRef` for each input really isn't practical. In simple scenarios it's extra overhead in the form of extra variables to track each individual field. In complex scenarios it simply doesn't work (I'm in a similar case with a table). 

@kara please reconsider this issue, the API can only be considered "relatively straightforward" in simple cases. Being able to focus a form's input is a pretty direct ask for a form module.

**Comment by MickeyMullin** [comment]
So much would be solved with `FormController.getElement = () => { return this.$$element; }` (or possibly `getNativeElement()`) and `FormController.getControls = () => { return this.$$controls; }`. It sounds like all of the asked-for capabilities can be much more easily and elegantly handled from exposing those private variables.

Is the fear that external references to those items will be ham-fistedly manipulated, wrecking havoc within the form's innards?

**Comment by dave0688** [comment]
I really don't understand the approach on this issue. Many people are requesting a feature (which makes so much sense in my opinion). @kara is denying to implement it, referencing to some `relatively straightforward approach`. Many people are asking for that `relatively straightforward approach`, so it seems not to be that `straightforward` as @kara says. 
But instead of just stating your `straightforward` approach here, there's just silence?

Come on, that's not a good way of solving problems!

**Comment by joelebeau1** [comment]
I'd also like to voice my support for an implementation of the requested feature, just ran into an issue at work where I need that functionality and found this thread.

My thoughts: I'm surprised to even see the joint use the `FormControl` and `ElementRef` API's suggested as a permanent solution here since, per [the Angular docs on `ElementRef`](https://angular.io/api/core/ElementRef), >Use this API as the last resort when direct access to DOM is needed. Use templating and data-binding provided by Angular instead.

**Comment by marcusportmann** [comment]
I am in the same position where I am unable to set the focus for an invalid FormControl. It is impractical to create a corresponding ElementRef for each FromControl in my forms. It surprises me that there is not a better solution available in a framework as mature as Angular for what is clearly a common problem. @kara please reconsider this feature request.

**Comment by wlievens** [comment]
The absence of this feature and the lack of a reasonable way around it (declaring a @ViewChild for every single annotation is impractical at best, impossible at worst) really devalues the reactive forms system.

**Comment by Etchelon** [comment]
Still no reply from @kara or the angular team after 31 thumbs down? I haven't ever seen such a negative reaction to a github comment... but this doesn't seem to bother them.
I am also requesting this feature because I need to listen to DOM events on a form control's native element in a reactive angular form where I don't have any template available, so I can't event work my way around it with viewchilds or other template related hacks (I'm using ngx-formly).

**Comment by JunusErgin** [comment]
As this thread is ignored by the Angular team,

I decided to change the prototype of the FormControlDirective myself. It's not the best and not the most performant way, but it works without visible lags:
[https://github.com/angular/angular/issues/13158#issuecomment-346019580](https://github.com/angular/angular/issues/13158#issuecomment-346019580)


Best,
Junus

**Comment by Remco75** [comment]
> @pcroc, You can define both, i.e. ElementRef and FormControl for same element and use the features.
> 
> **HTML:**
> <input #schoolControl name="school" placeholder="{{ 'PLACEHOLDER_SCHOOL' | translate }}" type="text" required mdInput [disabled]="loading"
> [mdAutocomplete]="autoSchool" [formControl]="schoolFormControl" />
> 
> **TS**
> @ViewChild('schoolControl')
> schoolControl: ElementRef;
> schoolFormControl: FormControl;

How would this work for more dynamic situation? Like, focusing the first invalid field after submit?

**Comment by Remco75** [comment]
@chojrak11  I created a solution for setting focus in the first invalid field. I guess you can alter it to fit your needs (this a a directive you place on your form element):

`import { Directive, HostListener, ElementRef} from '@angular/core';

@Directive({
  selector: '[focusFirstInvalidField]'
})
export class FocusFirstInvalidFieldDirective {

  constructor(private el: ElementRef) { }

  @HostListener('submit')
  onFormSubmit() {
    const invalidElements = this.el.nativeElement.querySelectorAll('.ng-invalid');
    if (invalidElements.length > 0) {
      invalidElements[0].focus();
    }
  }
}`

**Comment by indywill** [comment]
My use case is pretty close to @pcroc 's - a table with potentially many hundred cells.
The solution I came up with was to assign an id to each cell, and then use document.getElementById().focus();

It's not glamorous, but it does what I want and it was, dare I say, fairly straightforward...
html:
`<tr *ngFor="let row of rows; let rownum = index">
  <td *ngFor="let col of row.columns; let colnum = index" id="{{'cell_' + rownum + '_' + colnum}}">{{col}}</td>
</tr>`
ts:
`  setCellFocus(rownum: number, colnum: number) {
    const cellId = 'cell_' + rownum + '_' + colnum;
    const elem = document.getElementById(cellId);
    if (elem && elem.focus) {
      elem.focus();
    }
  }`

**Comment by woogychuck** [comment]
Based on the continued comments here, I'm guessing this will just never get done eh?

Setting focus is a pretty critical UI feature, it's a shame that we have to use hacks to make it work.

**Comment by vishnu283** [comment]
my issue is I have n number of forms in my application.i want to set focus for the label when I click the  input field.i need a global solution to do this. Instead of going and adding to every form.Is there a way to do this in angular 6

**Comment by larscom** [comment]
IMO a focus() method should exist on `FormControl` | `AbstractControl`
Why is this getting ignored?

**Comment by clochi** [comment]
I think this is very good idea. I had a big trouble with this :P 
For my case I resolved using setTimeout and querySelector and it works like a charm!
I just needed that every time that a new input was inserted dynamically, focus that new input.

HTML:
`<div class="topics" formArrayName="topics">`
`<mat-form-field `
              `class="meeting__input-container"`
               ` *ngFor="let topic of meetingForm.get('topics')['controls']; let i = index">`
                `<input`
                 `minlength="6"`
                  `class="meeting__input"`
                  `matInput`
                  `placeholder="Tema a tratar"`
                  `[formControlName]="i"`
                  `(keydown)="enterPressed($event, i)">`

Typescript:
`addTopic() {`
    `this.topicsControl.push(new FormControl(''));`
  `}`

And this code is executed when a user press enter on a input element from the array to push a new input and focus it. 
`this.addTopic();`
      `setTimeout(() => {`
        `document.querySelector('.topics')`
          `.querySelector('.ng-pristine')`
            `.querySelector('input').focus();`
     `})`

**Comment by dudewad** [comment]
I think all of the hacks listed in thread show that there _is definitely not_ a "simple and straightforward" API.

Angular docs constantly harp on no accessing native elements unless absolutely necessary, yet you'll choose to leave out what would be a tiny method (seriously, `focus()` is supported back to IE8, it's not even a cross-browser issue) in the name of bundle size? You do understand that the bundle size for anyone needing to now work around this issue is going to be bigger than the angular native code that would be written to support this use case? Not to mention that focusing and blurring elements is a _core use case_ of form elements on the web.

This issue should be seriously reconsidered.

**Comment by chojrak11** [comment]
Don't get me started on this project's governance and Google in general... Never saw them listening to client's needs or wishes.

**Comment by logic01** [comment]
For anyone who is still following.

I have created a new feature request so we can push for this feature again since it was closed so long ago with insufficient reasoning.

https://github.com/angular/angular/issues/31133

**Comment by dudewad** [comment]
@logic01 I'm in. Good call.
