### ISSUE TITLE
The AOT subset of the TypeScript language is undocumented

### ISSUE THREAD

**Issue by aluanhaddad** [angular/angular#12465]
**I'm submitting a ...**  (check one with "x") - It could be either depending on interpretation.
```
[x] bug report => search github for a similar issue or PR before submitting
[x] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Actual behavior**

The Ahead Of Time Compiler is incompatible with a number syntactic and semantic features that are directly manifest in TypeScript, but I cannot find any official documentation on this. 
There is no formal specification that I could find.
There are numerous related issues including #11978, which demonstrates the problem very clearly.

**#11978 was closed entirely without justification**

I assert this based on the following assumptions regarding a professionally produced product used by millions of developers:

  1. The new language or subset is undocumented: the best thing I could find were some incomplete suggestions at the bottom of an unofficial [WebPack 2 + Angular repo's README](https://github.com/qdouble/angular-webpack2-starter#aot--donts).

  2. A subset of the TypeScript language has been defined by the AOT compiler. Introducing a new language within a large community of developers who had been writing, as per official recommendation, in TypeScript is a massive change.

  3. A programming language should have a formal specification

  4. A programming language should have an informal introduction

  5. A programming language should have a tutorial
  
  6. Diverging from existing standard tools that were officially promoted requires justification

**Expected behavior**

1. The introduction of a new language or subset is accompanied by official documentation

2. The introduction of a new language or subset is formally specified

3. The introduction of a new language or subset is accompanied by introductory material

4. The goals of the language or subset, its use cases, target developer audience, the problems it solves, and its intended scope are declared

**Minimal reproduction of the problem with instructions**
Not Applicable

**What is the motivation / use case for changing the behavior?**

  1. Being able to write correct code requires knowing what language one is writing in.

  2. Tools must be able to support it.
  
  3. A new language should have a name, it is completely unacceptable for a new language to refer to itself using the name of another language.

#### Tell use about you environment

* **Angular version:** >= 2.0.1
* **Browser:** all
* **Language:** TypeScript (all versions)

  **Update**: Added request for a language name and numbered list items for better reference.

**Comment by fxck** [comment]
There's quite a few things you cannot do when using AOT and as far as I know, there is no comprehensive list. 

Amongst other things:

- whatever you use inside the template cannot be `private`
- `@Input()` have to be public
- it doesn't understand this code

  ```typescript
  const effects = [ ef1, ef2, ef3 ];
  effects.map(effect => EffectsModule.run(effect)),
  ```
  you have to do
  ```typescript
  const effects = [ EffectsModuke.run(ef1), EffectsModuke.run(ef2), EffectsModuke.run(ef3) ];
  ...effects
  ```
  instead

- you cannot do `const foo = () => {}` you have to use `function foo() {}` instead 


It's quite off-putting.

**Comment by DzmitryShylovich** [comment]
> whatever you use inside the template cannot be private

Because the compiler generates a separate class that knows how to render the template (ngfactory), and it needs to reach into the context class (the component class you write) to get those fields.

> you cannot do const foo = () => {} you have to use function foo() {} instead

Your code has to be statically analyzable because ngc doesn't execute it

**Comment by aluanhaddad** [comment]
@DzmitryShylovich Example docs state they are written in TypeScript. This is perfectly valid TypeScript. Regardless, the difference between `const foo = () => {}` and `function foo() {}`, is that the latter is hoisted and mutable.

**Comment by vicb** [comment]
@robwormald do you expect any change in angular ? I tend to say that this is an issue for angular.io and should be closed here. WDYT ?

**Comment by robwormald** [comment]
Think we should leave this open here until we've solved it (it is a documentation issue indeed) - its something that comes up fairly regularly, so we can point to this rather than having repeated issues getting opened.

**Comment by vicb** [comment]
Issues in this tracker should be actionnable. Having more issues only make searching more difficult.

@aluanhaddad please re-open on https://github.com/angular/angular.io. Thanks

**Comment by aluanhaddad** [comment]
@vicb While this can technically be interpreted as a documentation issue, I doubt it can be resolved without the direct attention of core developers.

Specifically, I am asking for a technical specification of an implicitly defined language subset. I mean something at the level of the [TypeScript Language Specification](https://github.com/Microsoft/TypeScript/blob/master/doc/spec.md) or at the very least the [TypeScript Handbook](https://www.typescriptlang.org/docs/handbook/basic-types.html).

I am also asking why issues such as #11978 have been closed without being resolved. The reason given for closing these issues is always roughly something along the lines of "that is how AOT works". That is not satisfactory as there is not a resource defining AOT in a technical sense. Such a resource requires a level of detail analogous to the TypeScript documents linked above.

I am also asking why the existence of this subset language has not been more widely publicized, discussed, and promoted. That is a complicated question.

If all of these questions can be resolved by handling them at https://github.com/angular/angular.io, I will happily open an issue there.

**Comment by robwormald** [comment]
@aluanhaddad we're calling this a documentation issue because in general, this is a conceptual problem rather than a technical one.

For example - regarding private properties on classes: 

A simple component such as:
```ts
import {Component} from '@angular/core'

@Component({
	selector: 'my-app',
	template: `<h1>hello {{name}}</h1>`
})
export class App {
	name = 'rob'
}

```
When run through ngc, it is important to understand (and thus needs documenting) that the generated code does not modify or replace the original component - it acts as a "host" or a "wrapper" for the original component - it's job is to communicate between the DOM and your application code. 

```ts
class _View_App0 extends import1.AppView<import0.App> {
  _el_0:any;
  _text_1:any;
  /*private*/ _expr_0:any;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import3.AppElement) {
    super(_View_App0,renderType_App,import6.ViewType.COMPONENT,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckAlways);
  }
  //snip
  detectChangesInternal(throwOnChange:boolean):void {
    this.detectContentChildrenChanges(throwOnChange);
    // this.context is the component instance here
    const currVal_0:any = import4.interpolate(1,'hello ',this.context.name,'');
    if (import4.checkBinding(throwOnChange,this._expr_0,currVal_0)) {
      this.renderer.setText(this._text_1,currVal_0);
      this._expr_0 = currVal_0;
    }
    this.detectViewChildrenChanges(throwOnChange);
  }
}

```
Most would agree than upon seeing this code, its clearer as to why private properties don't work - because the component *must* expose those properties for them to be available to the host - this is 100% normal typescript semantics - we *generate* new TS code, and then that code runs through the vanilla typescript transpiler. 

This behavior is, in fact, how we get type checking of templates - because if I accidentally mistyped a binding in my template:
```html
`<h1>hello {{nome}}</h1>`
```
The generated factory would reference that property (as it's derived from the template):
```ts
const currVal_0:any = import4.interpolate(1,'hello ',this.context.nome,'');
```
which when run through vanilla typescript, fails (as expected) with a regular TS error:
```
Error: Error at ./src/app.ngfactory.ts:86:71: Property 'nome' does not exist on type 'App'.
```

To your request about creating an official IDE / plugin architecture, this is already in progress, and has been for many months - see https://github.com/angular/angular/issues/7482 for progress on that. It leverages the exact same toolchain as discussed above to provide a reusable LanguageService that these sorts of plugins can leverage.

The crux of all of this is static analysis, which is why your desired ability to override or modify the behavior of built-in decorators is currently unsupported, and why there are certain limitations on the kinds of things that you can do when including things into decorators like NgModule. 

Given 
```ts
@NgModule({
  imports: [ BrowserModule ],
  declarations: [ App ]
})
export class AppModule {}
```
Everything here is statically analyzable, and we *serialize* this into a portable JSON format which is shippable to NPM and consumable by the angular compiler:
```json
{
	"__symbolic": "module",
	"version": 1,
	"metadata": {
		"AppModule": {
			"__symbolic": "class",
			"decorators": [
				{
					"__symbolic": "call",
					"expression": {
						"__symbolic": "reference",
						"module": "@angular/core",
						"name": "NgModule"
					},
					"arguments": [
						{
							"imports": [
								{
									"__symbolic": "reference",
									"module": "@angular/platform-browser",
									"name": "BrowserModule"
								}
							],
							"declarations": [
								{
									"__symbolic": "reference",
									"module": "./app",
									"name": "App"
								}
							]
						}
					]
				}
			]
		}
	}
}
```

There is an option you can pass to the compiler - `strictMetadataEmit` that will warn when you're doing things that are not statically analyzable - 

> Such a resource requires a level of detail analogous to the TypeScript documents linked above.

Compile-time warnings, plus a list of common errors and suggested resolutions would be significantly more useful to developers than a complex language-level specification that basically nobody is going to read nor fully understand at this point.

There is a limited subset of simplification we can do (and again, this needs to be documented), in the same way that `RouterModule.forRoot([])` is a function call, and we investigate requests to enable such things on a case-by-case basis. 

The reason static analysis is the limiting factor is *precisely* because of the desire to have tooling/IDE support - executing your code to compute dynamic values is far slower than static analysis - consider how fast it has to be to support things like template autocompletion in your IDE - this is only possible via static analysis, operating at the AST level. 

The same limitation applies to your desire to override the built-in Angular decorators - doing some sort of wrapper decorator would generally require the decorator to be executed to compute the modified metadata to be used in code generation. 

I believe one use-case you discussed was enforcing uniqueness of selectors across an application - this is *exactly* the kind of thing we're looking to enable, but IMO it makes far more sense for that kind of check to be done via static analysis, so you don't pay a runtime cost for such checks. 

We absolutely want to enable extensibility into the compiler pipeline (there are a number of very interesting use cases we've publicly discussed, such as [template transforms](https://youtu.be/bVI5gGTEQ_U?t=916) - our i18n implementation is an early exploration of such a plugin architecture. However, we are being generally conservative in the early stages, as we want Angular to live for a long time, and we do not want to paint ourselves into a corner allowing a feature we'll have to support forever, nor do we want to have developers implementing plugins they would have to entirely rewrite until we've solidified the underlying architecture. 

> I am also asking why the existence of this subset language has not been more widely publicized, discussed, and promoted. That is a complicated question.

The answer to this is quite simple - its something we're still evolving, exploring, and learning about. We're doing something that is an entirely new model for front end web applications, and its a learning experience for everyone involved. For example, the ability to pass config into NgModules via static properties (a la `RouterModule.forRoot` ) is a direct result of developer feedback and collaboration with the core team. 

I hope this clarifies our thinking - we're absolutely on board with getting this better documented, and PRs / collaboration with the documentation team is greatly appreciated if this is something you care about making better for everyone. cc @wardbell - hopefully this wall of text can serve as the starting point for an explainer doc.

**Comment by vicb** [comment]
> While this can technically be interpreted as a documentation issue, I doubt it can be resolved without the direct attention of core developers.

I have much less doubts.
- the is first a documentation issue,
- then a tool issue, linter as the one for @mgechev will probably be able to help,
- there might be **specific** actionable to be addressed by the core, there it makes sense to open a specific & actionnable issue.

_(I guess Rob is saying similar things in his comment above)_

**Comment by aluanhaddad** [comment]
@robwormald Thank you for the information. I appreciate it.

>Most would agree than upon seeing this code, its clearer as to why private properties don't work - because the component must expose those properties for them to be available to the host - this is 100% normal typescript semantics - we generate new TS code, and then that code runs through the vanilla typescript transpiler.

I am sorry, but this is the definition of a leaky abstraction. That code with private members works fine in JIT mode highlights this very sharply. The choice to implement views by generating TypeScript code that acts as a proxy should be an implementation detail. Users are not writing this code directly but they are being given errors from it. TypeScript checks the generated views, code the developer did not write, and emits errors, in the name of static checking. In the meantime, TypeScript gives a pass to TypeScript the developer did write but will not work with angular because Angular is interpreting that TypeScript differently.
Hence the request for documentation regarding the new language. The semantics of the subset.
So when we are writing our views we get TypeScript error checking for the parts we did not write directly but we no longer get semantic checking for the typescript code we do write directly because ngc does not interpret it the same way. Because it is not emitting JavaScript. Because it is another tier, another language. Hence the request for acknowledgement, specification, and documentation of the subset.

>Compile-time warnings, plus a list of common errors and suggested resolutions would be significantly more useful to developers than a complex language-level specification that basically nobody is going to read nor fully understand at this point.

You do not need to write a specification, or an IDE if you don't introduce a new language. So why introduce a new, framework specific language? TypeScript already has compiler errors, static analysis and IDE support. It is already formally specified. Angular only lost these things when introducing AOT.

Where did TypeScript support go? 
Where is it noted that Angular 2 applications need to be written in an unspecified dialect of TypeScript that supports an arbitrary subset of its features and has arbitrary semantics for others?
Why would I want to learn a new language that only works with one framework?
Why does Angular 2 need its own programming language?
Is it offering so much more than its competitors that it warrants an entire toolchain involving multiple abstractions over multiple other languages. Angular 2 has a custom html parser that interprets another a non-standard dialect of html, and now a custom TypeScript compiler that generates _additional_ (thanks for explaining that) TypeScript.
It uses a custom subset of TypeScript that has no tools available. I say custom because it needs to talk to code that is being generated by Angular's TypeScript compiler, ngc which no one had heard of 6 months ago. Not to forget about needing to support Closure via tsickle and you end up with a massive number of transformations that are not hidden from the developer nor within their control.

What justifies this complexity?
This is a serious question.
The amount of complexity in Angular 2 is worrisome.
