### ISSUE TITLE
feat(platform-node): create platform-node based on angular/universal

### ISSUE THREAD

**Issue by jeffbcross** [angular/angular#12495]
Create platform-node inside this repository, to be consumed by Angular Universal and other packages that would rely on platform-node. By having it inside this repository, the package will be tested and updated alongside the core, and will be maintained by the core team.

The API should be generally compatible with the existing `[platform-node](https://github.com/angular/universal/tree/master/modules/platform-node)` inside the angular/universal repository so that Universal would ideally be able to just change its dependency to point at the `@angular/platform-node` npm package.

CC: @jeffwhelpley @gdi2290 @IgorMinar

**Comment by gdi2290** [comment]
notes:
* `platform-node/node-http should` be merged with `http` as main/browser fork
* `serialize` in NodePlatform shouldn't live in NodePlatform so you can mostly ignore this. Here's what's in the pipeline.
  * lifecycle hooks
  * view utils component id problems
  * check if the app is stable
  * injecting preboot
  * hydrate 
  * serialize document
* ignore `asyncPromiseSeries` as rxjs is the correct way to manage the pipeline rather than promises
* PlatformLocation can't live in platform due to the service having state 
* platformNodeDynamic was created in the way it was due to limitation of core
* 2.1.1 broke universal due to exports privates change with compiler
* NodeDomRenderer needs to be refactored to remove a lot of code dealing with converting props to attributes and ensuring that attributes are strings.  The whitelist needs to be reworked to reflect attributes when setting a prop.
* node-location there were problems dealing with baseUrl/requestUrl/originUrl 
* node-document should be merged with parse5 and `.head`, `.body`, `.title` need to grab new references (html component fix) and title needs to correctly set a text node.
* parse5-adapter has a zone.js workaround for context in it as it's impossible otherwise since there are a few methods that were not made with more than one document in mind. This sort of can be fixed by reworking some of the services but then core needs to be updated. getHistory, getCookie, etc are also impossible without our zone workaround


There should be a Context service for configuration with a ZoneContext to refactor the zone out the current solution. That way NodePlatform.withConfig can work and AoT still works. The problem you will run into with zone are providers being created during platform or application before bootstrap. This problem has been a pain for location state.

you can also view this old fork of commits that show how to convert a browser version to node
https://github.com/IgorMinar/new-world-test/pull/9/files

**Comment by gdi2290** [comment]
close for https://github.com/angular/angular/issues/13822

**Comment by DzmitryShylovich** [comment]
@pkozlowski-opensource ☝️ close
