### ISSUE TITLE
XHR Error (404 Not Found) loading http://localhost:3000/traceur(…)

### ISSUE THREAD

**Issue by mstrofbass** [angular/angular#12500]
**I'm submitting a ...**  (check one with "x")
```
[x ] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**

I am attempting to complete the Angular.io tutorial. I have made it through https://angular.io/docs/ts/latest/tutorial/toh-pt5.html. After completing the "Simulating the web API" in https://angular.io/docs/ts/latest/tutorial/toh-pt5.html the app fails and both the front end and backend console report a 404 for /traceur. My understanding is that this error pops up quite a bit for things unrelated to /traceur. Some potentially useful information follows.

First, here is the file (app.module.ts) I believe to be responsible:

```
import { NgModule }      from '@angular/core';
import { BrowserModule } from '@angular/platform-browser';
import { FormsModule }   from '@angular/forms';
import { HttpModule }    from '@angular/http';

import { AppRoutingModule } from './app-routing.module'

// Imports for loading & configuring the in-memory web api
import { InMemoryWebApiModule } from 'angular-in-memory-web-api';
import { InMemoryDataService }  from './in-memory-data.service';

import { AppComponent }   from './app.component';
import { DashboardComponent }   from './dashboard.component';
import { HeroDetailComponent } from './hero-detail.component';
import {HeroesComponent} from "./heroes.component";
import {HeroService} from "./hero.service";

@NgModule({
    imports: [
        BrowserModule,
        FormsModule,
        HttpModule,
        AppRoutingModule,
        InMemoryWebApiModule.forRoot(InMemoryDataService)
    ],
    declarations: [ AppComponent, HeroesComponent, HeroDetailComponent, DashboardComponent ],
    bootstrap:    [ AppComponent ],
    providers: [HeroService]
})

export class AppModule { }

```
Some debugging facts:

1. package.json was initially set to include "angular-in-memory-web-api": "~0.1.5". 
2. Commenting out "InMemoryWebApiModule.forRoot(InMemoryDataService)" from the @NgModule imports array fixed the error. 
3. Simply importing the module without calling "forRoot" (i.e., imports: [ InMemoryWebApiModule ]) does not fix the issue.
4. Reverting to release 0.1.10 fixes the problem.
5. The problem is present in 0.1.11.

**Expected behavior**

There would be no 404.

**Minimal reproduction of the problem with instructions**
Follow the instructions for the tutorial at: https://angular.io/docs/ts/latest/tutorial/

**Please tell us about your environment:**
OS X 10.11.6

```
{
  "name": "ipmanager-frontend",
  "version": "0.0.1",
  "scripts": {
    "start": "tsc && concurrently \"tsc -w\" \"lite-server\" ",
    "lite": "lite-server",
    "postinstall": "typings install",
    "tsc": "tsc",
    "tsc:w": "tsc -w",
    "typings": "typings"
  },
  "dependencies": {
    "@angular/common": "~2.1.0",
    "@angular/compiler": "~2.1.0",
    "@angular/core": "~2.1.0",
    "@angular/forms": "~2.1.0",
    "@angular/http": "~2.1.0",
    "@angular/platform-browser": "~2.1.0",
    "@angular/platform-browser-dynamic": "~2.1.0",
    "@angular/router": "~3.1.0",
    "@angular/upgrade": "~2.1.0",
    "angular-in-memory-web-api": "0.1.11",
    "bootstrap": "^3.3.7",
    "core-js": "^2.4.1",
    "reflect-metadata": "^0.1.8",
    "rxjs": "5.0.0-beta.12",
    "systemjs": "0.19.39",
    "zone.js": "^0.6.25"
  },
  "devDependencies": {
    "concurrently": "^3.0.0",
    "lite-server": "^2.2.2",
    "typescript": "^2.0.3",
    "typings": "^1.4.0"
  }
}
```

* **Angular version:** 2.0.X
See above (should be latest)

* **Browser:** 
all
 
* **Language:** [all | TypeScript X.X | ES6/7 | ES5]
Typescript > 2.0.3

* **Node (for AoT issues):** `node --version` =  6.7.0

**Comment by DzmitryShylovich** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).

**Comment by mstrofbass** [comment]
How the fuck is this not a bug report?

**Comment by ericmartinezr** [comment]
Here you may find some clues about your issue https://github.com/angular/angular/issues/11358

**Comment by DzmitryShylovich** [comment]
@mstrofbass if u think it's a bug then provide a working reproduction in plunkr.

**Comment by IgorMinar** [comment]
@mstrofbass please make sure that you don't have any ES6 imports or exports commented out in your code. 404 requests for /traceur means that sysmtem.js thinks that one of your files is an ES Module, which happens when you don't have your transpiler configured correctly (not likely if you are following the tutorial) or if you have some code comments that contain ES imports or exports (these don't get transpiled and confuse System.js).

Also please be aware that you have violated our [code of conduct](https://github.com/angular/code-of-conduct/blob/master/CODE_OF_CONDUCT.md). Please don't do that again.

**Comment by mstrofbass** [comment]
@IgorMinar Did you even read what I wrote?

**Comment by mstrofbass** [comment]
The issue is related to the configuration provided for the Quickstart, which needs to be corrected.

**Comment by DzmitryShylovich** [comment]
Feel free to file an issue on https://github.com/angular/angular.io/issues

**Comment by thelgevold** [comment]
We made a tweak to in-mem-web-api to better support tree shaking and AoT. This means the library is now published as esm code, which will cause the traucer error since it contains import statements. 

If you want to do a JiT build you can use the umd bundle instead.
 
Here is a sample systemjs confgiruation to use in-mem-web-api with JiT apps: https://github.com/angular/angular.io/blob/master/public/docs/_examples/_boilerplate/systemjs.config.js

**Comment by mstrofbass** [comment]
@DzmitryShylovich Given the amount of time I spent trying to debug the issue and the lack of interest by anyone associated with the Angular project in either ensuring that the basic tutorial is actually functional or helping solve related issues, I will pass.

**Comment by apm5127** [comment]
@mstrofbass :I had this same issue, and @thelgevold 's sample systemjs config was the solution. 

@IgorMinar : Since the change that @thelgevold mentioned affects the systemjs config, which is set up in the Angular.io "Get Started" page for beginners, this change would affect everyone trying to follow the tutorial.

As you can see here, https://angular.io/docs/ts/latest/quickstart.html#!#create-and-configure, the Get Started page uses the (now) incorrect way to load angular-in-memory-web-api.

**Comment by wardbell** [comment]
Weakness in the QuickStart doc is that it displays trimmed copies of the  `package.json` and `systemjs.config.js` that we actually use and we neglected to resync the copies. 

Sorry for your pains. We really do care.  We've [fixed](https://github.com/angular/angular.io/pull/2668) in latest `angular.io` which will republish soon.
