### ISSUE TITLE
i18n: plurals should replace expression with placeholder

### ISSUE THREAD

**Issue by mprobst** [angular/angular#12512]
Plurals should replace the expression with some placeholder. E.g. for this template:

``` html
<h3 i18n>{
    response.getItemsList().length,
    plural,
    =0 {Found no results}
    one {Showing one result}
    other {Found {{response.getItemsList().length}} results}
}</h3>
```

We produce this message:

``` xml
<msg id="ce4b410515b449bffcf4c150decbc036bd7c244e">{
    response.getItemsList().length, plural, =0 {Found no results} one {Showing one result} other {Found <ph name="INTERPOLATION"/> results} }</msg>
```

The `response.getItemsList().length` should be replaced with some form of placeholder message.

**Comment by vicb** [comment]
@gnoack do you have any example of where the expression is replaced by a placeholder ?
Not sure `<ph name/>` is supported here - the alternative might be to use the name only but it would special case the implementation.

**Comment by gnoack** [comment]
Quoting from another bug, for context:
"In plural messages, if it's feasible for you, try to pull out the response.getItemsList().length
and similar code from the translated message, so that it's not part of that.  Otherwise, you
will probably trigger a retranslation everytime that the variable or method names change."
