### ISSUE TITLE
Issue with Nested Module

### ISSUE THREAD

**Issue by kuntalkishore** [angular/angular#12538]
**I'm submitting a ...**  (check one with "x")
```
[x ] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**

I am using angular build 2.0.1 and having an issue with nested modules.

Here is the depiction of the structure

 App Module
(has app component with router-outlet defined)
 ----Group Module 
       (has group component with router-outlet)
       (has routerModule.forChild(grpROUTE) defined for the group module)
       -----GroupDetails Module
              (has groupDetails component with router-outlet)
               (has routerModule.forChild(grpDtlROUTE) defined)   
 
Trying to navigate to app/group/groupdetails always generate the below error
'router-outlet' is not a known element:'

I have ensured to include RouterModule is imported into groupDetails as well as Group module.

I have been struggling with this for past two days. Any help would be highly appreciated.
     
**Expected behavior**

Based upon all the search posts available online, this shouldn't be an issue and I haven't encountered any post having similar problem. I am lost where to go next with this.

**Minimal reproduction of the problem with instructions**

**What is the motivation / use case for changing the behavior?**

**Please tell us about your environment:**

* **Angular version:** 2.0.X

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

 
* **Language:** [all | TypeScript X.X | ES6/7 | ES5]

* **Node (for AoT issues):** `node --version` =

**Comment by vicb** [comment]
`'router-outlet' is not a known element:'` is probably due to the fact that the router module is not imported.

-- 

Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).

--

When submitting "real" issues pls provide a repro as requested in the issue template.
