### ISSUE TITLE
[BrowserStack] Timeout failures are very frequent

### ISSUE THREAD

**Issue by vicb** [angular/angular#12578]
/ref https://travis-ci.org/angular/angular/jobs/171182324

Since our Browser Stack account get "expired" and re-"activated" many runs end up with an error:

```
27 10 2016 18:58:52.380:INFO [karma]: Karma v0.13.20 server started at http://localhost:9876/
27 10 2016 18:58:52.421:INFO [launcher]: Starting browser iPhone 5S (ios 7.0) on BrowserStack
27 10 2016 18:59:02.786:INFO [launcher.browserstack]: iPhone 5S (ios 7.0) session at https://www.browserstack.com/automate/builds/0973e90b5d070d19fb077acc65007e3fe6f92117/sessions/7443d972c6c0acd106dea1116ab84c24886c20af
No output has been received in the last 10 minutes, this potentially indicates a stalled build or something wrong with the build itself.
The build has been terminated
```

Background info:
- We can not get BS to reply to our support requests.
- @IgorMinar was able to see that our account got an "expired" status and then a "activated" status but BS is very flacky since then.

/cc @naomiblack

**Comment by nakula** [comment]
@vicb I will get back on this.

**Comment by vicb** [comment]
Thanks @nakula, seems like @naomiblack has tried to contact Browser Stack over all possible channels without any chance !

**Comment by AnkurGel** [comment]
Hi @vicb, 
For the mentioned session `7443d972c6c0acd106dea1116ab84c24886c20af`, we observed that it took > 10 mins to give terminal to your Karma worker. This is possibly because you exceeded parallel limit at that time. Builds on travis gets stopped if it doesn't output anything in 10 minutes. Can you crosscheck if that's the case?

We also saw few sessions getting timed-out after browser launches. For them, we suggest to increase `browserNoActivityTimeout` in karma config from 1min to around 5mins. That should help in those cases.

We will keep a proactive watch for your such cases. Please let us know if you face more such issues. Happy to help :) // cc @naomiblack

**Comment by nakula** [comment]
hey @vicb @naomiblack - I see you are still facing both the issues. Can you guys please try

1. browserNoActivityTimeout to 5mins (11 / 28 timeouts are because of this)
2. You have 10 parallel runs right now - which is leading to high queue time for some runs. Are you folks running more than that? I can add more runs - just want to be sure, thats the case.

cc @vedharish @AnkurGel

**Comment by vicb** [comment]
@nakula We do have 10 parallel runs per PR and can have 3 PR in parallel, would it be possible to set the max to 30 ?

Thanks you very much for your support

cc @vedharish @AnkurGel

**Comment by vicb** [comment]
@nakula I got this error: `timeout: Cannot be greater than 1800` - https://travis-ci.org/angular/angular/jobs/174649027#L764

Any idea how to solve this ?

**Comment by AnkurGel** [comment]
@vicb Hey. We have increased your parallel limit to 30.

**Comment by vicb** [comment]
@AnkurGel Thanks, the situation seems to have improved on our side.

However we still have some issues, see https://travis-ci.org/angular/angular/jobs/174882908#L2182

Could this be solved by raising the number of concurrent build again ?

**Comment by vicb** [comment]
The issue seems to be solved for now. Thanks for your help @nakula @vedharish @AnkurGel
