### ISSUE TITLE
Add ability to add parameters to a route of route is created

### ISSUE THREAD

**Issue by chambersDon** [angular/angular#12645]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => search github for a similar issue or PR before submitting
[X] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

Add the ability to manually add parameters to a route.

**What is the motivation / use case for changing the behavior?**
I have this route config:

```
        path: 'app/:tenantId',
        children: [
           ...
 ```

This tenantId needs to be on all routes.  I would like to subscribe to navigateStart (or some other event) and add this ID to every route.  It eliminates the need to manually do it every time a router.navigate or routerLink is used.  Since i t's always there it makes sense to just do it in once place.

**Comment by AlmogShaul** [comment]
If you already navigated to app/:tenantId and you want to navigate forward, you don't need to write all the path in the navigation parameter , jus the relative path of the children.
If you didn't navigate already, you have to know where to navigate..

**Comment by vsavkin** [comment]
I think what you are looking for is relative navigation. If you use it, you won't have to provide the tenantId parameter, unless you actually change the tenant id. Another option is to use query parameters instead of matrix parameters because those can be preserved. Finally, you can decorate the router service to implement arbitrary navigation preprocessing. 

Closing this issue.
