### ISSUE TITLE
pressing enter key when input is focused 'clicks' first button on form

### ISSUE THREAD

**Issue by thewizarodofoz** [angular/angular#12643]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**

I have a form element with several inputs and buttons in it.
When an input is focused and I press the Enter key, the first button on the form is being clicked.
**Expected behavior**

Pressing Enter should not click the first button.
**Minimal reproduction of the problem with instructions**

http://plnkr.co/edit/0wQt4KTGL4cDsh3zeZ88?p=preview
**What is the motivation / use case for changing the behavior?**

In my form I have something like a 'chips' component, which allows adding token by pressing Enter on an input field.
**Please tell us about your environment:**

Mac, Webstorm, Webpack, Node
* **Angular version:** 2.1.2

* **Browser:** 
 Chrome, Firefox, Safari (all latest)
* **Language:** [all | TypeScript X.X | ES6/7 | ES5]
TypeScript 2.0.6
* **Node (for AoT issues):** `node --version` =

**Comment by jonrimmer** [comment]
This is standard HTML form behaviour, nothing to do with Angular. Pressing enter in a focused text input will click the first submit button in the form.

One way to avoid it is not to have any submit button in the form. In your plunker, adding ```type="button"``` attributes to each button element will prevent them being clicked when the user presses enter.

**Comment by yoat** [comment]
I had a Clear button (before the Submit button in the HTML) with no type specified.  Pressing Enter triggered the first button, being the Clear.  The Submit had a type="submit".  Once I set explicitly the Clear button to type="button" Angular then switched to triggering Submit on an Enter keypress.  Error by omission!

**Comment by jonrimmer** [comment]
@nharrer As I said in 2016, this part of standard HTML behaviour, nothing to do with Angular. If you feel it is incorrect, you should raise it with the people responsible for maintaining those standards at the [WHATWG](https://github.com/whatwg/html) / [W3C](https://github.com/w3c/html).

However, I can 100% guarantee that they will say that, regardless of its merits, this behaviour cannot be changed, because it has been part of the web platform for 20 years or more, and to alter it now would break too many existing websites.

When dealing with platforms as old as the web, these kind of things are just something we have to deal with occasionally.

**Comment by sureshapn** [comment]
> This is standard HTML form behaviour, nothing to do with Angular. Pressing enter in a focused text input will click the first submit button in the form.
> 
> One way to avoid it is not to have any submit button in the form. In your plunker, adding `type="button"` attributes to each button element will prevent them being clicked when the user presses enter.

hey super man.

**Comment by gururajmca** [comment]
By default enter makes first submit button in the form active, There are many ways we can control this flow.  
1. Simple way as @sureshpn suggested making button as "button" instead of submit.
2. Use form form module. which can give more options for validation, there you can control the submit.
3. Use $event.preventDefault()
4. tab-index switch (I have not tried it)

**Comment by prateekchitransh1907** [comment]
Adding type="button" fixed it for me. :)
