### ISSUE TITLE
FormGroup#controls HashMap to be an ES6 Map

### ISSUE THREAD

**Issue by rupebac** [angular/angular#12715]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => search github for a similar issue or PR before submitting
[ x ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
I am extending the functionality from FormGroup with my own type. But I have some re-usability problems.

Right now the constructor at FormGroup is like:

`constructor( public controls: {[key: string]: AbstractControl}, .....) {}`

which does not allow to delegate functions like insert, get and iterate on `controls` to my derived class. Why not receiving an ES6 Map instead?

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Map

Since "operators overloads" have been declined in Typescript ([here](https://github.com/Microsoft/TypeScript/issues/5407)), there is no nice way for me to, for instance, keep FormGroup children and FormControl on different objects.

I can submit a PR if you think it makes sense and I have a chance.

**Comment by wesleycho** [comment]
It should be noted that this is probably a breaking change, as there are likely users also injecting this in their own directives/components.

This can probably be worked around currently just by creating helper utils for working with objects, but switching that to a proper Map would be nice since it gives the ability to iterate in an ordered manner for free (order of insertion in the map). Ideally it would be a WeakMap, but unfortunately not all supported browsers support it.

**Comment by DzmitryShylovich** [comment]
> Ideally it would be a WeakMap, but unfortunately not all supported browsers support it and it is a feature that **cannot be polyfilled**.

?

**Comment by wesleycho** [comment]
@DzmitryShylovich WeakMap is an ES6 feature that cannot be polyfilled by browsers - it has to be supported natively because of its references being held weakly, unlike any other construct in JavaScript (minus WeakSet).

Looking it up, WeakMap does not have the iterable benefit though, so perhaps Map is the best construct here if it is desired to support iteration natively.

**Comment by lqbweb** [comment]
I have worked around by using a ES6 Proxy, but it is not nice I have to say.
