### ISSUE TITLE
API Reference - Missing Http Body documentation, no base classes or implemented methods

### ISSUE THREAD

**Issue by peku33** [angular/angular#12784]
I was directed here from https://github.com/angular/angular.io/issues/2780

The issue does not correspond to angualr itselt, but to the API Reference available at https://angular.io/docs/ts/latest/api/

In many Http examples, users use .text() and .json() method directly on Http.Response object.

I tried to find at least basic information about those methods in API Reference, but with no luck. In https://angular.io/docs/ts/latest/api/http/index/Response-class.html there is not a single word about those methods, except an example showing the usage.

I found a source of Response class in https://github.com/angular/angular/blob/master/modules/%40angular/http/src/static_response.ts

The Response class derives from Body class which provides .text() and .json() methods.

However, in API Reference there is no information about Body. There is also no information about base classes or implemented interfaces (probably for all classes, not only Response).

**Comment by vicb** [comment]
@petebacondarwin why @jeffbcross ?

We have `class Response extends Body {...}`, this issue is about merging `Body` docs into `Response` - here both class are documented but the docs does not get propagated nor you have any clues that Response extends Body.

I've cced you because of dgeni, let me know if I should bug someone else. Thanks.

_I think dart docs (not angular.dart) have the options to show/hide inherited members, that would be even better_

**Comment by petebacondarwin** [comment]
Oh I misunderstood the issue. I thought it was that the `Body` class was not documented.
The actual problem appears to be that `abstract` classes are not being included in the documentation.

**Comment by vicb** [comment]
@petebacondarwin could we close the issue here and create one where the issue is (dgeni repo ?)

**Comment by petebacondarwin** [comment]
Ironically the correct repo is angular.io

**Comment by vicb** [comment]
I'll re-open there then. thanks.
