### ISSUE TITLE
[router] PreloadAllModules subscription, callback or lifecycle

### ISSUE THREAD

**Issue by antonybudianto** [angular/angular#12836]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => search github for a similar issue or PR before submitting
[x] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
Currently there's no way to know when preloading is done, when I tried to inject the Router and get the config, I need to add `setTimeout` or otherwise the config is outdated

**Expected behavior**
Need a promise/observable/lifecycle for when preloading is done

**Minimal reproduction of the problem with instructions**
No repro, this is a feature request

**What is the motivation / use case for changing the behavior?**
My use case is to build a menu from registered routes

**Please tell us about your environment:**
All OS

* **Angular version:** 2.1.2, Router version 3.1.2

* **Browser:** [all  ]
 
* **Language:** [all ]

* **Node (for AoT issues):** `node --version` =  all

**Comment by antonybudianto7** [comment]
Currently I can get the routes from `_loadedConfig` variable inside routes but there's a bug where if I put a children with empty path, then I won't get the `_loadedConfig`

Repro: https://github.com/antonybudianto/cli-router-demo/blob/master/src/app/dashboard/dashboard-routing.module.ts#L13

Look at line13, please un-comment it and run, check the console, it'll not get the `_loadedConfig`

**Comment by antonybudianto7** [comment]
I've solved the issue, but is there a way to know/subscribe when the preload is done?
Thank you

**Comment by vsavkin** [comment]
1. I assume you're relying on "_loadedConfig". This is a private property, and thus is not meant to be used.
2. Because canLoad can prevent preloading, there is no single event that will indicate that the preloading is done. Different parts of the configuration can be preloaded as the user navigates through the app.
3. Preloading is supposed to be transparent. Emitting events would violate this property.

That's why I'm closing this issue.

This is how you can implement you want:
1. You can provide your own RouterPreloader, where you can implement the notion of completion suitable for your application. You can extend or decorate the existing router preloader.
2. You can define a provider in every lazy-loadable module responsible for a certain part of the menu. When the modules are loaded and instantiated, the providers can construct the menu. I think this option is preferable.

**Comment by antonybudianto** [comment]
@vsavkin , thanks for explanation 👍
