### ISSUE TITLE
ActivatedRoute.snapshot has old data when route changes

### ISSUE THREAD

**Issue by klinki** [angular/angular#12912]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
ActivatedRoute.snapshot has old data. When route changes, ActivatedRoute.snapshot has data from previous route.

**Expected behavior**
Documentation states that snapshot should be: "The current snapshot of this route."  (https://angular.io/docs/ts/latest/api/router/index/ActivatedRoute-interface.html)  Which it is not. 

**Minimal reproduction of the problem with instructions**
http://plnkr.co/edit/LThOFFTawaUYg7L9oIXg?p=preview

Click on "First component" in menu and then click on "Increment self" several times.

**What is the motivation / use case for changing the behavior?**
ActivatedRoute.snapshot should have current data even when route changes. It should not be delayed by 1 step.

* **Angular version:** 2.1

* **Browser:** [Chrome | Firefox | probably all]

* **Language:** [TypeScript]

**Comment by olegdunkan** [comment]
It seems to me that we can use ActivatedRouteSnapshot freely inside 'resolve' method of Resolver or when ngOnInit is called. But when we subscribe on data changes then we have a transition state of route inside a handler. This state is before the route becomes completed IMHO. 
It needs clarification also when and where we can use snapshot. Maybe it is bug.

**Comment by skreborn** [comment]
As far as I know, [`ActivatedRoute.params`](https://angular.io/docs/ts/latest/api/router/index/ActivatedRoute-interface.html#!#params-anchor) is indeed changed before routing is actually complete. You can subscribe to the actual router events using [`Router.events`](https://angular.io/docs/ts/latest/api/router/index/Router-class.html#!#events-anchor), and wait for [`NavigationEnd`](https://angular.io/docs/ts/latest/api/router/index/NavigationEnd-class.html). This seems to produce the results you are looking for. See the updated plunker [here](http://plnkr.co/edit/Rfc7J5OmkRKhTrvlhXWB?p=preview).

```
this._router.events.subscribe(event => {
  if (event instanceof NavigationEnd) { 
    // this._activatedRoute.snapshot is up to date
  }
});
```

**Comment by klinki** [comment]
That's interesting. Is there any documentation of order when those events occur?

**Comment by skreborn** [comment]
@klinki None that I could find. You might want to open an issue about that over at the [angular.io](https://github.com/angular/angular.io/issues) repository if you feel like this should be documented.

**Comment by slubowsky** [comment]
This really seems strange to me. We resolve data,  activated routes route.params and route.data are both updated with new data in the component - but the route is still not active. In my case I wanted to navigate further based on the data, and made the mistake of doing relative navigation when processing route.data. Resulting routes were relative to the old route, resolver wasn't called again on the resulting new routes, and everything was just generally messed up.
I think documentation should really highlight that when processing activatedRoute.data might not be the best time to actually update your component (unlike the example at https://angular.io/docs/ts/latest/guide/router.html#!#resolve-guard) since the route is not actually activated yet.

**Comment by vicb** [comment]
Looks like a bug in `advanceActivatedRoute()` where the snapshot is assigned at the end. Needs more investigation

**Comment by olegdunkan** [comment]
If it isn't bug then we have to have the proper way to handle this, but I didn't see the way. Let we need to get `params` and `data` together at a some place in code. 
First we try this:
````
   this.route.data.subscribe(data=>{
       const params = this.route.snapshot.params;
       //Now we have data and params together 
   });
````
but `params` are not current and let it be the as is. 
Because of `data` derives from `params` (https://github.com/angular/angular/issues/12767#issuecomment-260493205) we try doing:
````
   this.route.params.subscribe(params=>{
       const data = this.route.snapshot.data;
       //Now we have data and params together again
   });
````
But again `data` from last route.

Ok, let try to write: 
````
Observable.merge(this.route.data, this.route.params).bufferCount(2).subscribe(result=>console.log(result));
````
It is works but not properly because for first time we have `data` in `result[0]` but for second time `data` is swapped with `params` and now `data` are in `result[1]`. 

See https://plnkr.co/edit/NR2ZfY1H7n3XzMJZi89s?p=preview

That was true for the cases when we try changing route we are on it:
````
[
    {
        path:'',
        component:Main
    },
    {
        path:'sibling',
        component:Sibling
    },
    {
   
      path: 'parent',
      component: Parent, //in this place we try to change route to ./a 
      children:[
        {
          path: ':child',
          component: Child
          resolve:{
            data:Resolver
          }
        }
      ]
    }
  ]
````
 But if we try changing route from `sibling` to `parent`  then all will be right.
Will be waiting for fixing of this bug.

If someone knows the way to get `data` and `params` in strong fashion I will appreciate that.

**Comment by olegdunkan** [comment]
@vicb I have made some investigations, 
first, after redirects and all passed checks we create new router state:
https://github.com/angular/angular/blob/master/modules/%40angular/router/src/router.ts#L709

Then at:
https://github.com/angular/angular/blob/2.3.1/modules/@angular/router/src/create_router_state.ts#L30
we start to recursively recreate a new tree

And `createNode()` function does this:
````
    const value = prevState.value;    
    value._futureSnapshot = curr.value;
    const children = createOrReuseChildren(routeReuseStrategy, curr, prevState);
    return new TreeNode<ActivatedRoute>(value, children); //!!!problem is in here 
````
That is why each new node gets old value `prevState.value`.
Then this new state is used in:
https://github.com/angular/angular/blob/master/modules/%40angular/router/src/router.ts#L744

And finally we have it in `advanceActivatedRoute(this.futureState.root)` as a future state.
Maybe the simple fix will resolve it but it's need more time to explore all router in details.
The fix is:
````
//    const value = prevState.value;    
    value._futureSnapshot = curr.value;
    const children = createOrReuseChildren(routeReuseStrategy, curr, prevState);
    return new TreeNode<ActivatedRoute>(curr.value, children);

**Comment by olegdunkan** [comment]
In new version `master` we have working `RouteReuseStrategy` I think and hope it will resolve the issue automatically.

**Comment by olegdunkan** [comment]
Finally I've found out that `routeReuseStrategy.shouldReuseRoute` always returns `true`. In the  function two configs (future and current) are compared, but they are always the same. There is no way to substitute `ReuseStrategy` via `ExtraOptions` for now, but in future version maybe.

**Comment by DzmitryShylovich** [comment]
@olegdunkan 
> There is no way to substitute ReuseStrategy via ExtraOptions

u can provide your own `RouteReuseStrategy`. just `{provide: RouteReuseStrategy, useClass: CustomReuseStrategy}`

**Comment by olegdunkan** [comment]
@DzmitryShylovich thanks, it works. 
 
For now I have substituted only one method 
````
@Injectable()
export class CustomReuseStrategy implements RouteReuseStrategy {
 ...
 shouldReuseRoute(future: ActivatedRouteSnapshot, curr: ActivatedRouteSnapshot): boolean {
    return false;
  }
}
````
Now the problem has gone, see
https://plnkr.co/edit/BOoZobkwdYvFeorFT6vN?p=preview

But of course it's the temporary solution, because I think the default reuse strategy has to work.

**Comment by Alkasih** [comment]
This is what I dont like from angular to other SPA, different version, different buil-in function/syntac. Everything change and then new bug waiting for solution again.

**Comment by AlleXyS90** [comment]
Even if the thread is old, I found it searching for an answer at same problem.

The solution is simple because route.params detect the value changed of a parameter and you can call the action into route subscriber. For me, works fine in constructor.

```
constructor(private route: ActivatedRoute) {
route.params.subscribe(routeParam => {
      this.id = routeParam['id'];
      // do something
    });
}
```

Try to not call the method "do something" in ngOnInit, because this will be called two times.

**Comment by abdallahmaali** [comment]
> Even if the thread is old, I found it searching for an answer at same problem.
> 
> The solution is simple because route.params detect the value changed of a parameter and you can call the action into route subscriber. For me, works fine in constructor.
> 
> ```
> constructor(private route: ActivatedRoute) {
> route.params.subscribe(routeParam => {
>       this.id = routeParam['id'];
>       // do something
>     });
> }
> ```
> Try to not call the method "do something" in ngOnInit, because this will be called two times.

this is worked for me but it's make request multiple  time  because i  call a  function inside it  to get data from the server it's call  the function  multiple times

**Comment by codeepic** [comment]
@skreborn The `event instanceof NavigationEnd` doesn't work when user refreshes the page - I find myself having to merge two streams: router.events and activatedRoute.url - and do some clever filtering to prevent the function I want to run from firing maaaany times. Quite annoying.

**Comment by ChrisColeTech** [comment]
this bug still exists in angular 8.  maybe angular 9 will be fixed?
