### ISSUE TITLE
Usage of angular2/src/facade/*, and List, ListWrapper etc.

### ISSUE THREAD

**Issue by matthewjh** [angular/angular#1304]
Are these things I can (and should) use in my code? 

For example, I've been using `ListWrapper` because it seems useful, but having to import `List` for the sake of type annotations is annoying. I see [globals.ts](https://github.com/angular/angular/blob/master/modules/angular2/globals.ts), but how do I include it in my project? It's not in the npm distribution.

**Comment by pkozlowski-opensource** [comment]
@matthewjh facades are used in Angular2 repo since the same code base is transpiled to both ES6 and Dart. So you don't need to use those, unless you are creating your app for 2 platforms (JS and Dart).

NPM wasn't updated with the TypeScript goodies yet as this is still work in progress. You need to wait a bit more for this, I'm afraid.

Closing as TypeScript bits are worked on atm.
