### ISSUE TITLE
Incorrect decimal separator in CurrencyPipe BRL

### ISSUE THREAD

**Issue by dioubernardo** [angular/angular#13149]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
When using CurrencyPipe with currencyCode = BRL the decimal separator is incorrect, it is showing "." when it should be ","

**Minimal reproduction of the problem with instructions**
{{preco | currency:'BRL':true:'1.2-2'}} show R$5.00
the corret is R$ 5,00

**Please tell us about your environment:**
Chrome 54.0.2840.99 m (64-bit) in Windows 10 

* **Angular version:**
Angular 2.1.1 + Ionic Angular 2.0.0-rc.3

* **Browser:** I tested only in Chrome 54.0.2840.99
 
* **Language:**  I tested only in TypeScript 2.0.6

* **Node (for AoT issues):** `node --version` =  v6.9.1

**Comment by vicb** [comment]
Your problem here is that the number formatting does not depends on the currency but on the locale.

Let's say that the locale is `en` (which is the default that you happen to use), you want to display:
- $ 123.00
- R$ 456.00
ie the number formatting should not depend on the currency.

Could you please re-open your issue on angular/angular.io so that we document better this part.

Note: to override the locale, you should add a provider for the `LOCALE_ID` token.
