### ISSUE TITLE
Cannot reference local template variable to model controller if input has `formControlName` attribute.

### ISSUE THREAD

**Issue by unlight** [angular/angular#13151]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
https://plnkr.co/edit/ddQVpGuLg8nvOL450MqW?p=preview
`app/app.component.html` Line: 14-15
Cannot reference local template variable to model controller if input has `formControlName` attribute.
ERROR:
```
Template parse errors:
There is no directive with "exportAs" set to "ngModel"
```

**Expected behavior**
No errors or warnings.

**Minimal reproduction of the problem with instructions**
1. Open https://plnkr.co/edit/ddQVpGuLg8nvOL450MqW?p=preview
2. Open console (devtools)
3. Errors, `app/app.component.html` Line: 14-15

**What is the motivation / use case for changing the behavior?**
Purpose is to create short ref and use it, so just `streetRef.valid` instead of `myForm.controls.address.controls.street.valid`

* **Angular version:** 2.2.3

* **Browser:** all
 
* **Language:** TypeScript 2.1.1

**Comment by DzmitryShylovich** [comment]
I also have a related question. Why does [formControl](https://github.com/angular/angular/blob/master/modules/%40angular/forms/src/directives/reactive_directives/form_control_directive.ts#L67) is exported as `ngForm`? Should we export both formControl/formControlName as `ngModel`?

**Comment by kara** [comment]
Reactive form directives like `formControlName` and `formGroupName` aren’t exportable by design, and here’s why.

In template-driven forms, the source of truth is the template. Directives like `ngModel` do most of the heavy lifting for you, including creating `FormControl` instances for you under the hood that track value/validity/etc. So if you want to access form state, you always have to go through the directive. The best way, given the template-driven paradigm, is to export the **directive** into a template variable and pass it around as needed. This works because most of the directive’s properties will simply fall through to the `FormControl` instance below.

Reactive forms are built with a different paradigm. The source of truth is the component class, and this is where most of the work is done. You don’t need to delegate to directives because you already have direct access to the directives’ underlying `FormControl` instances - you created them yourself in the class (in your case, using `FormBuilder`). You can already traverse the form tree any way you like in the template - `form.get(‘address.street’)`, etc.  It doesn't make sense to export the directives to get access to controls you already have.

In the very valid case that you might want to create shorter references, the common practice is to adhere to the existing workflow and do so in the component class, not the template. Typically this means creating a simple getter:

```ts
get streetRef() {
   return this.myForm.get(‘address.street’);
}

```
I've [updated your plunker here](https://plnkr.co/edit/EA3wXEEZRogcfwTZrTBB?p=preview) with a working demo.

@DzmitryShylovich Top level reactive form directives like `formGroup` and `formControl` are still exportable because of the `submitted` property. This is a property that only makes sense on the top level, so it lives on the directive and not the control. Because it lives on the directive, the only way to access it is through exporting as `ngForm`. This is why we've kept the exporting around. In most cases, you'll want to use the same strategy as above.
