### ISSUE TITLE
Have an easy way of Components to publish themselves in the Injector

### ISSUE THREAD

**Issue by mhevery** [angular/angular#1319]
Currently there is no easy way for a component to publish itself into the `Injector` hierarchy.

## Proposal

* Add a new List property to `@Component` called `publishAs`. If supplied:
* Create a child app injector that publishes the component to child components inside its view (i.e. those that live in the shadow DOM)

## Example

```dart
import 'package:angular2/angular2.dart';

abstract class Container {}

@Component()
@View(
  directives: const [Parent],
  template: '<parent></parent>'
)
class MyApp {
}

@Component(
  publishAs: const [Parent, Container] // <== IMPLEMENT THIS
)
@View(
  template: '<child></child>',
  directives: [Child]
)
class Parent implements Container {
}

@Component()
@View(...)
class Child {
  Child(Container container) {
    // Can't get a hold of Container
  }
}

```

**Comment by naomiblack** [comment]
@yjbanov this is a high priority for @matanlurey. Status?

**Comment by yjbanov** [comment]
Status is that I haven't started yet.

**Comment by yjbanov** [comment]
@naomiblack, @matanlurey wants me to work on this next, so I'm starting now.

**Comment by mhevery** [comment]
Thanks!

**Comment by yjbanov** [comment]
Heads up, I'm about to update the original description for consistency and to reflect the current API. I will make the following changes:

* Rename `bind` to `injectables`
* Add `const Binding(Container, toAlias: Parent)`: this is because the child is injecting `Container` and in the example above `Container` is not bound to anything
* Use Dart in the example: the example is half-Dart half-TypeScript and interface types in TypeScript are erased, and therefore do not support this feature as described above

**Comment by yjbanov** [comment]
Now the real questions. According to the description we want to be able to allow a component to publish themselves to children in the light DOM. `injectables` publishes to shadow DOM only. In fact, we are pretty explicit about the fact that we do not support publishing to light DOM.

To support this feature as described we would first need to introduce support for publishing into the light DOM and then introduce the `SELF` binding. Is that what we want? What use-case are we trying to support with this?

**Comment by yjbanov** [comment]
Updated the proposal based on offline design discussions. Changes:

* We only publishing into the component view (i.e. shadow DOM, not light DOM)
* Parent bindings are not mixed with `injectables` because `injectables` are made available to the declaring component itself, so it is counter-intuitive to put the component in the same list.
