### ISSUE TITLE
Angular2 UpgradeComponent missing $injector ( in lazy loaded module )

### ISSUE THREAD

**Issue by vladotesanovic** [angular/angular#13279]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
Angular1 component trows error inside module that is lazy loaded. I am using Upgrade Module and Upgrade Component approach from Docs: https://angular.io/docs/ts/latest/api/upgrade/static/UpgradeComponent-class.html

I am using same bootstrapping process as from: https://github.com/angular/angular/blob/master/modules/%40angular/upgrade/test/aot/test_helpers.ts#L19

<img src="http://storage7.static.itmages.com/i/16/1206/h_1481057920_7019896_e7587c9748.png" />

**Expected behavior**
Angular1 component should appear

**Minimal reproduction of the problem with instructions**
Minimal angular-cli repo:
https://github.com/vladotesanovic/ui-grid-angular2

_Bootstrapping_: https://github.com/vladotesanovic/ui-grid-angular2/blob/master/src/main.ts
_Angular1 app_: ( with downgradeComponent ): https://github.com/vladotesanovic/ui-grid-angular2/blob/master/src/anglarjs.ts#L88

Non working on: /home/about ( lazy loaded )

URL ( works in AppModule ): http://ui-grid2.surge.sh/#/route1
URL ( does not work in HomeModule ): http://ui-grid2.surge.sh/#/home/about

Router config: https://github.com/vladotesanovic/ui-grid-angular2/blob/master/src/app/app.module.ts#L48

**What is the motivation / use case for changing the behavior?**
I want to use ui-grid component that is written for Angular1 in my Angular 2 application.

**Please tell us about your environment:**

* **Angular version:** 2.2.1

* **Browser:** [all | Chrome ]

 
* **Language:** [all | TypeScript]

* **Node (for AoT issues):** `node --version` =

**Comment by DzmitryShylovich** [comment]
Duplicate of https://github.com/angular/angular/issues/12965

**Comment by vladotesanovic** [comment]
It is not, my is connected with lazy loaded module

**Comment by jonrimmer** [comment]
@vladotesanovic Remove the UpgradeModule import from the Home module and your app should be work.

I think the problem is: The UpgradeModule's job is to get a reference to the ng1 injector and make it available to ng2 components via dependency providers, and vice-versa. But if you import UpgradeModule a second time, then this second instance's providers hide those from the first one, and since it is never bootstrapped, the injector instance that it provides is always null.

When you don't use lazy loading, multiple instances of UpgradeModule will sometimes work properly. I think because the code in angular1_providers will cache the first injector instance created by the first UpgradeModule and make it available to additional instances of UpgradeModule, even when they're not bootstrapped. Although you can still get the same error when you include HomeModule statically, if the "about" state is the first one loaded. I think when you lazy load a module, the SystemJS loader loads and runs a second copy of angular1_providers as well, which means the cached injector instance isn't available, and you see the error every time.

**Comment by vladotesanovic** [comment]
@jomeier :+1: 

You have :beer: from me.
