### ISSUE TITLE
Regression when using static method & ANALYZE_FOR_ENTRY_COMPONENTS

### ISSUE THREAD

**Issue by seanlandsman** [angular/angular#13307]
**I'm submitting a ...**  (check one with "x")
```
[ x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**

We develop a library that clients in turn use - when compiling the client code (for AoT) I get the following error:

Error: Error encountered resolving symbol values statically. Function calls are not supported. Consider replacing the function or lambda with a reference to an exported function, resolving symbol AppModule

**Expected behavior**

There should be no error when compiling.

**Minimal reproduction of the problem with instructions**

For version 2.1.0 the behaviour is as expected, but for 2.2.x onwards it seems to have regressed.

I have a created a stripped down version of the problem (taking the library domain logic out of the equation) - it can be found here:

https://github.com/seanlandsman/angular2-client-library

The library & client package.json will fail compilation  (using 2.3.0), but there are equivalent package.json.working files in each dir that work (using 2.1.0)

The library code has this:
```
export class GridModule {
    static withComponents(components: any[]):ModuleWithProviders {
        return {
            ngModule: GridModule,
            providers: [
                {provide: ANALYZE_FOR_ENTRY_COMPONENTS, useValue: components, multi: true}
            ]
        }
    }
}
```

And this appears to the problematic part of it.

**What is the motivation / use case for changing the behavior?**

This used to work and believe it should still work from what I've read in the docs

**Please tell us about your environment:**

OSX (sierra), Intellij (2016.3), NPM (3.10.9)

* **Angular version:** 2.0.X

Have tried with Angular 2.3.0, still a problem

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

Compilation stage problem - no browsers
 
* **Language:** [all | TypeScript X.X | ES6/7 | ES5]
Typescript 2.0.3

* **Node (for AoT issues):** `node --version` =   
6.9.1

**Comment by tbosch** [comment]
This could be related to https://github.com/angular/angular/issues/13327

**Comment by chuckjaz** [comment]
Seems unrelated.

**Comment by chuckjaz** [comment]
Actually it is related. This works in 2.2.4 but not in 2.3.0.

I will test this again with the fix for #13327

**Comment by chuckjaz** [comment]
This still reproduces with 2.3.1.

I will fix this but there are work-arounds below that will allow you to work in 2.3.0 and 2.3.1.

**What went wrong**
The reason we fail is because we changed to no longer user TypeScript to resolve the location of symbols but, rather, rely on the content of .metadata.json files which now encode enough information for us to resolve symbols.

If we run into a version 1 metadata file we will auto upgrade the metadata, copying the necessary information from the .d.ts files next to it into the metadata before we continue processing.

However, we neglected to auto-upgrade missing files. That is, if a .d.ts files has no .metadata.json file (which was valid for version 1 but is not longer valid for version 3) then we should "auto-upgrade" an empty metadata file instead of using an empty metadata file.

**Work around**
You have a couple of work-arounds for this.
1. RECOMMEND: change your main.d.ts to main.ts (replacing ./lib with ./src) and have `ngc` build the .metadata.json file  and the main.js file. This requires modifying the "main" and "typings" in your package to point to the generated files in "lib".

2. Include the .metadata.json file along side the main.d.ts that `ngc` would have produced.  Which is:
``` [{"__symbolic":"module","version":3,"metadata":{},"exports":[{"from":"./lib/cell.component"},{"from":"./lib/grid.component"},{"from":"./lib/grid.module"}]},{"__symbolic":"module","version":1,"metadata":{}}]```

I highly recommend doing (1) above because the metadata file will change and we plan to require .metadata.json files beginning with version 4.0.0. If you make the recommended changes you will be compatible with 4.0.0 without modification. If you use (2) you will need to update the metadata yourself if we start requiring a new version.

I have made the recommended modifications locally and can send you a PR to your repository with the changes if you like.

**Comment by seanlandsman** [comment]
Hi @chuckjaz thanks very much, that's great. I'd appreciate a PR if you have it all ready to go, that would definitely help.

Thanks again for looking at this - we really appreciate it.

**Comment by chuckjaz** [comment]
https://github.com/seanlandsman/angular2-client-library/pull/1

**Comment by seanlandsman** [comment]
thanks very much @chuckjaz - should I close this issue now?

**Comment by chuckjaz** [comment]
No. I am using this issue to track the underlying problem so other libraries will not need to work around this.
