### ISSUE TITLE
Proposal: Service for document head management (with support for title, meta, link, style etc) on all route changes

### ISSUE THREAD

**Issue by DzmitryShylovich** [angular/angular#13361]
**I'm submitting a ...**  (check one with "x")
```
- [ ] bug report => search github for a similar issue or PR before submitting
- [x] feature request
- [ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Expected behavior**

Proposed syntax:
```
const routes: Routes = [
  {
    path: 'home',
    component: HomeComponent,
    data: {
      head: {
        title: 'Home page',
        description: 'Description of the home page',
        meta: [
               {'name': 'description', 'content': 'My application'},
               {'property': 'og:type', 'content': 'article'}
        ]
      }
    }
  }
];
```
**What is the motivation / use case for changing the behavior?**

Make the document head management more declarative and simple.

Related to https://github.com/angular/angular/issues/7630

**Comment by zoechi** [comment]
What about providing a service that does that? Something like http://stackoverflow.com/questions/38644314/changing-the-page-title-using-the-angular-2-new-router/38652281#38652281 If it's not hardcoded in the router it's easier to customize/extend/....

**Comment by DzmitryShylovich** [comment]
yeah, component = service :)

**Comment by DzmitryShylovich** [comment]
@zoechi do u have any name suggestions?

**Comment by Louistiti** [comment]
If it can help Todd Motto wrote something about dynamic titles thanks to router events: https://toddmotto.com/dynamic-page-titles-angular-2-router-events.

For the name, maybe RouterHeadService ? :)

**Comment by laskoviymishka** [comment]
May be just HeaderService?

**Comment by laskoviymishka** [comment]
But that to boring. Need something more superheroic and with sense as well. What about

**Comment by laskoviymishka** [comment]
Something related to head but with POWER.
Suggestion list:

- [ ] burgonet
- [ ] helmet
- [ ] visor
- [ ] sallet

TDB

**Comment by buddyackerman** [comment]
@laskoviymishka chapeauservice

**Comment by artaommahe** [comment]
@DzmitryShylovich what about titles depended on route resolved data? E.x. i open an article page and title/metadata should reflect article title/data that is not static and is available in appropriate component that gets data from resolvers.

**Comment by DzmitryShylovich** [comment]
@artaommahe the impl will also work with resolved data

**Comment by intellix** [comment]
We're currently using a mix of what ToddMotto suggested and making API calls to fetch titles, meta tags via our CMS:
```typescript
this.router.events
  .filter(event => event instanceof NavigationEnd)
  .map(event => ({ url: event.url }))
  .switchMap(variables => this.apollo.query({ query, variables }))
  .subscribe(({data, loading}) => {
    this.titleService.setTitle(data.seo.title);
    // TODO: Meta service from ng4 when available
  });
```

Would love to have defaults defined on a route basis (as we're doing for our ng1 app). To be honest, even having the current state and it's data property on NavigationEnd would help me :)

**Comment by jedrichards** [comment]
Shouldn't this be declarative and in keeping with uni-directional flow? To me an ideal implementation would allow this sort of usage:

// ./home/home.component.html

```
<h1>Home page</h1>
<angular-helmet>
  <title>{{title}}</title>
  <meta name="foo" [content]="fooValue"></meta>
</angular-helmet>
```

So that when a `<angular-helmet>` component gets rendered or updated it updates the document head as a side effect. That way you can just bind to any outer component class values and so on. No need to integrate tightly with router, and you can render data coming into it naturally from route resolvers and so on. Listening to events and imperatively calling methods like `setTitle` seems to undermine the Angular 2+ component model.

This is similar to the `react-helmet` api. I'm assuming something like that should be possible?

https://github.com/nfl/react-helmet

**Comment by rafa-as** [comment]
Some news here?

**Comment by atscott** [comment]
Closing. We won't be implementing a service to manage meta, link, style, etc. since there are quite a few more unanswered questions about how this would work (especially with respect to the whole route tree) and if it should even be something managed by the router vs the pages themselves. However, we _will_ be creating a service in the same spirit to manage the page title only, tracked by #7630
