### ISSUE TITLE
Change log does not show breaking feature in major version change

### ISSUE THREAD

**Issue by reviling** [angular/angular#13498]
**I'm submitting a ...**  (check one with "x")
```
[x] feature request
```
RE: https://github.com/angular/angular/blob/01ca2db6aee13154f6d8b2afd9f83fc08cf80fc4/CHANGELOG.md

I see Angular is using SemVer, which means the bump to version 4 should have some breaking changes. The change log does not list the items that causes the break. Listing the breaking change would be nice so it's a little easier to make a time/effort estimate to update my code.

**Comment by DzmitryShylovich** [comment]
It's only the first beta release. It does't have any breaking changes (yet)

**Comment by mattlewis92** [comment]
I don't think there have been any breaking changes added yet, I believe the only one the team have planned is requiring typescript >= 2.0

Source: http://angularjs.blogspot.co.uk/2016/12/ok-let-me-explain-its-going-to-be.html

**Comment by pkozlowski-opensource** [comment]
It doesn't show anything since there are no breaking changes in 4.0.0-beta.0. Still, we _know_ that there will be at least one breaking change in the new release train (TS update) hence 4.0.x

Make sure to go over http://angularjs.blogspot.fr/2016/12/ok-let-me-explain-its-going-to-be.html and http://angularjs.blogspot.fr/2016/10/versioning-and-releasing-angular.html to have better overview of our versioning / releasing strategy.

**Comment by reviling** [comment]
Gotcha, thanks.
