### ISSUE TITLE
Zone.js and rxjs dependencies are causing issues when working with other 3rd party libraries

### ISSUE THREAD

**Issue by DavidGangel** [angular/angular#13518]
**I'm submitting a ...**  (check one with "x")
```
[X] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
I'm having dependency issues caused by zone.js and rxjs.
My package.json file is:
```
{
  "jspm": {
    "dependencies": {
      "@angular/common": "npm:@angular/common@^2.3.1",
      "@angular/compiler": "npm:@angular/compiler@^2.3.1",
      "@angular/core": "npm:@angular/core@^2.3.1",
      "@angular/platform-browser": "npm:@angular/platform-browser@^2.3.1",
      "@angular/platform-browser-dynamic": "npm:@angular/platform-browser-dynamic@^2.3.1",
      "@angular/router": "npm:@angular/router@^3.3.1",
      "angular2-google-maps": "npm:angular2-google-maps@^0.16.0",
      "core-js": "npm:core-js@^2.4.1",
      "hammerjs": "npm:hammerjs@^2.0.8",
      "ng2-simple-timer": "npm:ng2-simple-timer@^1.2.5",
      "reflect-metadata": "npm:reflect-metadata@^0.1.8",
      "rxjs": "npm:rxjs@5.0.0-rc.4",
      "zone.js": "npm:zone.js@^0.7.2"
    },
    "devDependencies": {
      "@types/core-js": "npm:@types/core-js@^0.9.35",
      "@types/node": "npm:@types/node@^6.0.52",
      "typescript": "npm:typescript@^2.1.4"
    }
  }
}
```

Now in the npm log I have:
```
npm WARN ng2-simple-timer@1.2.5 requires a peer of rxjs@5.0.0-beta.12 but none was installed.
npm WARN ng2-simple-timer@1.2.5 requires a peer of zone.js@^0.6.6 but none was installed.
npm WARN angular2-google-maps@0.16.0 requires a peer of zone.js@^0.6.25 but none was installed.
```

As you can see basically I should install rxjs@5.0.0-beta.12 and rxjs@5.0.0-rc.4
AND
zone.js@^0.6.6, zone.js@^0.6.25 and zone.js@^0.7.2
to be able to fulfill every dependency for every library that I use.
Now I have only 2 libraries. But how about if I would depend on 10 libraries?
I guess you see the point.

**Expected behavior**
Maybe it's not directly connected to angular2, but I also don't find any instructions on the net how to solve this issue.
It's also not a solution that I should go to those 3rd parties asking for an upgrade.
I should ask then 10 3rd party? What if the maintainer has gone away? (the code would just work fine with the upgraded zone and rxjs)
Once everybody has upgraded, and Angular moves forward the whole round begins from the beginning...

What I could imagine is that zone.js and rxjs shouldn't be dependencies (don't know that is it possible) at all for the 3rd party libraries.
But in such a case the documentation should strongly highlight it.

* **Angular version:** 2.3.1

**Comment by ashleymorris2** [comment]
I am also having this issue.

**Comment by PeterOsifeso** [comment]
Me too

**Comment by pkozlowski-opensource** [comment]
While everyone would love to use libraries and frameworks without any dependencies it is not realistic - we couldn't build any reasonably complex structure if we can't build on smaller primitives. So dependencies are here to stay and managing dependencies is part of the game.

While I agree that managing dependencies can be hard and sometimes you can go into conflicts that are hard to resolve in your particular case things are made harder than necessary by the 3rd party libraries you've chosen to use:

* ng2-simple-timer is declaring peer dependency on zone.js but it is not using it directly. It shouldn't do it - zone is angular peer dependency, no point of re-declaring this in a lib
* ng2-simple-timer uses very basic functionality of RxJS but declares very restrictive peer dependency. It should either use range or drop peer dependency altogether
*  angular2-google-maps is guilty of the same faults.

In both cases issues should be fixed in a corresponding library.

@IgorMinar this is probably one of the things that should be documented for "how to publish a library"  guide to which I could gladly contribute based on the work on ng-bootstrap.

**Comment by DavidGangel** [comment]
I'm fine if the library providers are able to write their code without those dependencies and you guys are providing documentation how to achieve that.
For now I'm going to raise one bug for each project and link them together.
Let's see what the owners thinks as well about it.

**Comment by DavidGangel** [comment]
@pkozlowski-opensource 
One of the library owner was able to overcame this issue.
However from ng2-simple-timer says:
Since my library is using RxJS, the dependency is required. I updated the library to use the latest version.

So in such a case what would be the long term solution?

Thank you.
