### ISSUE TITLE
When CanActivate guard redirects to / on initial load, router does not render component

### ISSUE THREAD

**Issue by nertzy** [angular/angular#13530]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
When a CanActivate guard navigates to the root path `/` on the initial load, the router does not render the root component. If the guard navigates elsewhere (e.g. `/elsewhere`) then it correctly renders the component for that route.

**Expected behavior**
Navigating to root should have the same behavior as navigating to any other route. It should always render.

**Minimal reproduction of the problem with instructions**
See https://github.com/nertzy/angular-issue-13530

**What is the motivation / use case for changing the behavior?**
This used to work in Angular 2.2.x. We want to redirect to the root path when a user is unauthenticated in our application.

* **Angular version:** We've seen it in 2.3.1 and 2.4.1

* **Browser:** all

* **Language:** TypeScript

**Comment by nertzy** [comment]
+cc @jlin-clgx

**Comment by WilliamKoza** [comment]
The first call to CanActivate return false, The component isn't load the first time. The second time, this is the same route , also the mechanism of instanciation is not fire.

**Comment by nertzy** [comment]
@WilliamKoza You're right. The second time the guard runs, it returns true.

We expect the second check that returns true to result in rendering the component. We see it work if we start at and end up on a non-root path, but not when the redirect ends on root.

For example, try this variation in our Plunker:
1. Click on the "go to something" like to get to `/something`
2. Click the refresh link to reload the app (your URL is still `/something`)
3. Type in `something` so that the guard redirects to `/something` (the same URL you are already at)
4. The component renders this time.

**Comment by nertzy** [comment]
Unfortunately, it's hard to reproduce this issue in Plunker.

The real issue we ran into in our real application is:
1. Navigate to `/search`
2. CanActivate guard redirects using `this.router.navigate([""])` to go to root path
3. Root component has no CanActivate guard
4. Root component does not render
5. The `this.router.navigate` promise is fulfilled as a success, even though the root component did not render.

**Comment by DzmitryShylovich** [comment]
@nertzy it's even harder to fix it without repro :)

**Comment by zaksyed** [comment]
I am also seeing the same issue, for me as well the steps to reproduce are the same as @nertzy mentioned above. In my application I have the canActivate guard on the login page and I am having it to redirect to the home page if the user is already logged in. The home page does not have any guards and similar to the issue mentioned above the home page does not render but the promise is fulfilled as a success.

**Comment by DzmitryShylovich** [comment]
@zaksyed can u add a small repro?

**Comment by kaznovac** [comment]
@nertzy please check your code for `router.navigate` on the initial web app load.

I've had the same symptoms while accessing/redirecting to guarded route; the initial navigation was cancelled by another `router.navigate` to '/' (which i've redirected to guarded path) and the component was never rendered.

**Comment by parys** [comment]
All good when I have already launched app and click on link, that navigates me to guarded route. But If at app start I paste a direct url to guard page and try to achieve it, app starts and redirects me(change url to proper root url) but component doesn't load.

My local code very close to https://plnkr.co/edit/1iBiXTwu5yOYMAL1x0eg?p=preview . For trying reproduce you should try to access url/guard at start.

**Comment by DzmitryShylovich** [comment]
@nertzy thx will take a look

**Comment by nertzy** [comment]
I've deployed it to a GitHub page as well: https://nertzy.github.io/angular-issue-13530/

The GitHub page shows that it still happens for the angular routing root when there is a `<base href>` set to a non-root path.

**Comment by DzmitryShylovich** [comment]
Looks like server config issue. 
With hash location strategy `RouterModule.forRoot(routes, {useHash: true}),` it works as expected (I believe :))

**Comment by anderflash** [comment]
Adding `{useHash: true}` works, but it inserts a weird `#/` in the URL. This problem doesn't happen on my previous project (A-Cli 1.0.0-beta.20-4 | A 2.2.1), but it happens with latest packages. I thought I was doing something wrong. +1 waiting a correction.
I tested with `ng serve` and a custom node server, and same problem happens.

**Comment by DzmitryShylovich** [comment]
https://plnkr.co/edit/qXH60zedNRpRUp0nHQxO?p=preview

**Comment by Luno** [comment]
I've encountered the same problem and created following workaround for the problem.

Instead of navigating to "/" in the CanActivate guard I'm navigating to "/home" path, which is just a "fake" path redirecting to "/".

**Comment by cburgdorf** [comment]
Hey @vicb we ran into the same issue in our Angular Master Class. I wonder who we could ping to look into it?

**Comment by bramdeba** [comment]
Having the same problem, and workaround by @Luno isn't working here.

**Comment by anderflash** [comment]
Try with `redirectTo` and `pathMatch` http://stackoverflow.com/a/39055118/4872010

**Comment by parys** [comment]
anderflash for what reason? I don't want any redirect except to /.  In SOF solution we can manually redirect by guard to "/someRoute" without redirecting to root.

**Comment by ofabricio** [comment]
Same problem here.

**Comment by Rezi** [comment]
Same issue

**Comment by bobby-ind** [comment]
I have a similar issue. I have used 'ng2-adal' for Azure AD authentication. The url before authentication is : http://localhost:31334/home. On the home page, I have the login button where I am authenticating against the Azure AD OAuth login page. CanActivate guard checks using ng2-adal if user if authenticated, then returns true else false. After successful login, I am returned back to url : http://localhost:31334/ instead of http://localhost:31334/home. This is causing CanActivate guard to return false on other routes at same level as I think Angular context is being reloaded and I am also not able to get the correct authentication status even after successful login.

**Comment by raja1988m** [comment]
I'm getting exactly same issue in angular 4.1.3,  ng2Admin application.  suggestions are appreciated and welcome  thanks...

**Comment by Sauruz** [comment]
I got the same issue in Angular 4. My guard was looking like this:

```
this._authService.isAuthenticated().subscribe(authenticated => {
          return authenticated;
});
```
Fixed it by doing this:

 return this._authService.isAuthenticated().map(authenticated => {
        return authenticated;
});

**Comment by grigorig** [comment]
I'm seeing this with a new app based on Angular 6. The problem occurs even if my AuthGuard `canActivate` function is extremely simple (`return false`).

**Comment by scartoalex** [comment]
@Injectable()

export class AuthGuard implements CanActivate {

auth: any = {};

constructor(private authService: AuthService, private router: Router) {

}

canActivate() {
    if (/*user is logged in*/) {
        this.router.navigate(['/dashboard']);
        return true;
    }
    else {
        this.router.navigate(['/Login']);
    }
    return false;
}
}

**Comment by kwkelly** [comment]
Still seeing this in angular 6 as well. @grigorig did you find a workaround?

**Comment by grigorig** [comment]
@kwkelly as a workaround I explicitly redirect to a fallback, just like in @scartoalex' post. It works, but seems suboptimal.

**Comment by tanansatpal** [comment]
+1

getting the same issue in my project

**Comment by perrosen** [comment]
Just ran into the same issue. Is the expectation now that we explicitly redirect in the guard rather than the router tries to match the next available route if one fails?

**Comment by sancaruso** [comment]
Same issue with Angular 7.

**Comment by fredsa** [comment]
Still seeing this with @angular/router 7.2.5

**Comment by lxREAPERxl** [comment]
Same for me. Just noticed it yesterday, but it gives me a lot of headaches. 
Due to strict NDA I am unable to provide full code samples, so I will try to describe the problem and code structure.

App: 
- login (no protection)
     - messages (protected by access guard)
             - messageDetail (protected by access guard)

example of routing module:

  {
    path: "login",
    component: LoginComponent,
  },
  {
    path: "messages",
    canActivate: [ AccessGuard, TermsAndConditionsGuard ],
    children: [
      {
        path: "",
        component: MessagesComponent,
      },
      {
        path: "",
        pathMatch: "prefix",
        outlet: "sideOutlet",
        component: SideOptionMessagesComponent,
      }
    ]
  },
  {
    path: "messages/:id",
    canActivate: [ AccessGuard, TermsAndConditionsGuard ],
    children: [
      {
        path: "",
        component: MessageDetailComponent,
      },
      {
        path: "",
        pathMatch: "prefix",
        outlet: "sideOutlet",
        component: SideOptionMessageDetailComponent,
      }
    ]
  },

Message contains <app-list> component, which renders list of <app-message-item>. Each Message item can perform router.navigate to a detail with specific ID. 

There is also header menu that contains <a routerLink="somePartOfTheApp" > to navigate through the app.

Each rendered screen (Message, message detail), has primary router-outlet (to render body) and secondary named router-outlet (that renders side menu).


Current behavior: 

1. build the app using npm start
2. login page is loaded (localhost ....)
3. fill in credentials and submit form (there is AWS cognito authentication)
4. when credentials are verified and user account doesn't require any other action (such as change default password or accept terms and conditions), app uses router.navigate to access Messages screen
5. messages screen is loaded with the appropriate side menu and list of messages is displayed as well
6. at this point, any action other than Logout doesn't work, at least not fully. If an message item is clicked, main router-outlet still keeps Messages list displayed, however side menu correctly renders message-detail-side component. The behavior is the same for any other link on the page.

However, if the page is refreshed, everything starts working as expected, all navigation components are routing to correct pages and both primary and secondary outlets are working.


So, to sum it up, after initial load and redirection to messages, it appears that routing is not working as expected and after refresh, everything works just fine.

Also, interestingly enough, Logout function works fine, basically, only thing it does is to clear storage (angular-persistence), logout cognito user and use router.navigate to move back to login.

packages.json config:

"dependencies": {
    "@angular/animations": "~7.2.7",
    "@angular/cdk": "^7.3.3",
    "@angular/common": "~7.2.7",
    "@angular/compiler": "~7.2.7",
    "@angular/core": "~7.2.7",
    "@angular/forms": "~7.2.7",
    "@angular/http": "~7.2.7",
    "@angular/material": "^7.3.3",
    "@angular/platform-browser": "~7.2.7",
    "@angular/platform-browser-dynamic": "~7.2.7",
    "@angular/router": "~7.2.7",
    "@ngx-translate/core": "^11.0.1",
    "@ngx-translate/http-loader": "^4.0.0",
    "amazon-cognito-identity-js": "^3.0.7",
    "angular-persistence": "^1.0.1",
    "classlist.js": "^1.1.20150312",
    "core-js": "^2.6.5",
    "hammerjs": "^2.0.8",
    "intl": "^1.2.5",
    "rxjs": "~6.4.0",
    "rxjs-compat": "^6.4.0",
    "web-animations-js": "^2.3.1",
    "zone.js": "~0.8.29"
  },
  "devDependencies": {
    "@angular-devkit/build-angular": "^0.13.4",
    "@angular-devkit/core": "^7.3.4",
    "@angular-devkit/schematics": "^7.3.4",
    "@angular/cli": "~7.3.4",
    "@angular/compiler-cli": "~7.2.7",
    "@angular/language-service": "~7.2.7",
    "@types/jasmine": "~3.3.9",
    "@types/jasminewd2": "~2.0.6",
    "@types/node": "~11.9.6",
    "codelyzer": "~4.5.0",
    "jasmine-core": "~3.3.0",
    "jasmine-spec-reporter": "~4.2.1",
    "karma": "~4.0.1",
    "karma-chrome-launcher": "~2.2.0",
    "karma-coverage-istanbul-reporter": "~2.0.5",
    "karma-jasmine": "~2.0.1",
    "karma-jasmine-html-reporter": "^1.4.0",
    "protractor": "~5.4.2",
    "ts-node": "~8.0.2",
    "tslint": "~5.13.1",
    "typescript": "^3.2.2",
    "webpack": "^4.29.6"
  } 


I know its not much to go on, but if anyone had encountered similar problem before and solved it, please let me know.
