### ISSUE TITLE
Attempting to Bind Two Dependent Inputs Disabled State in Reactive Forms Results in Stack Overflow

### ISSUE THREAD

**Issue by noamichael** [angular/angular#13570]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**

Attempting to bind two dependent inputs disabled state in a reactive form results in a stack overflow.

**Expected behavior**

(Given input A and B) 

Input A is disabled when B is present, and B is disabled when A is present.

**Minimal reproduction of the problem with instructions**

Example minimal plunkr:
http://plnkr.co/edit/30TjtFLSf7BmvElYTByf?p=preview

**What is the motivation / use case for changing the behavior?**

When constructing a form, it is very common to disable one input based on the presence of another. This is possible with template forms, but it is not possible with model forms. Issue #11271 suggests the only way to do this is by subscribing to the `valueChanges` property of a `FormControl` and manually calling `FormControl#disable`. However, this does not work because changes to input A's disabled state will infinity trigger input B's `valueChanges` subscribers and so on.

**Please tell us about your environment:**

* **Angular version:** 2.0.X

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

 
* **Language:** [all | TypeScript X.X | ES6/7 | ES5]

* **Node (for AoT issues):** `node --version` =

**Comment by DzmitryShylovich** [comment]
`FormControl.disable` method accepts sevelar args see [link](https://github.com/angular/angular/blob/master/modules/%40angular/forms/src/model.ts#L320) so u can disable it without triggering subscriptions. Example http://plnkr.co/edit/df3mlu6HXtNHPGb3pHJv?p=preview

**Comment by noamichael** [comment]
@DzmitryShylovich That does work as expected! We can use this in our project for the time being, but we have dozens of inputs that need to work in this way, so that may result in a large component class.. I'll see if I can make some generic utility that allows you to make a simple mapping of the inputs who disable each other.

**Comment by noamichael** [comment]
I created this generic utility function:
   
    /**
     * Creates a relationship between two inputs (A, B) where only one can be entered at a time.
     * @param mappings A key-value map of inputs to watch
     * @param form the container of the inputs
     */
    setupDisabledMappings(mappings: { [s: string]: string }, form: FormGroup) {
        function toggleSiblingOnValue(val1: FormControl, val2: FormControl) {
            val1.valueChanges.subscribe((value) => {
                if (value) {
                    val2.disable({ emitEvent: false });
                } else {
                    val2.enable({ emitEvent: false });
                }
            });
        }

        for (let mapping in mappings) {
            const val1 = form.get(mapping), val2 = form.get(mappings[mapping]);
            toggleSiblingOnValue(val1, val2);
            toggleSiblingOnValue(val2, val1);
        }

    }


Which can then be used like this:


    this.setupDisabledMappings({
            value1: 'value2',
            value2: 'value4'
    }, this.form);

**Comment by DzmitryShylovich** [comment]
cool. could u close the issue pls? thx

**Comment by pmulac** [comment]
I've been having the same problem, and I created a utility that is similar to @noamichael 's.  However, it doesn't seem to work with nested forms.  I have the following structure (all controls are required):

- root form
    - radio A
        - Subform 1
            - radio C
                - Subform 3
            - radio D
                - Subform 4
   - radio B
        - Subform 2

When a radio button is selected, its sibling's subform should be disabled.  For example, when `radio B` is selected, everything in `Subform 1` should be disabled.  This simple scenario works, but there are problems with more complex interaction.

Consider the following steps:

1. Select `radio A` to reveal `Subform 1` (and `Subform 2` is disabled)
2. Select `radio C` to reveal `Subform 3` (and `Subform 4` is disabled)
3. Complete `Subform 3` and entire form is now `VALID`
4. Select `radio B` and everything in `Subform 1` is disabled
5. Select `radio A` again.  The form should be in the same state as step 3 (`VALID`), but the triggered events cause `Subform 4` to be disabled and then immediately re-enabled from a cascading `valueChanges` event.  This causes the form to be `INVALID`.

It seems to me that the `enable()` and `disable()` calls require `{ emitEvent: true }` because the nested radio buttons need to recalculate their corresponding subform's status when their parent is re-enabled.  However, there is a cascading effect in which additional `valueChange` events fire, causing controls that should be disabled to become re-enabled.  

I'm curious if anyone else has run into this problem.  I think this use case of nested forms is pretty common.  I'm not sure how this can be solved, but perhaps if there was a way to enable/disable forms with the following constraints:

1. When a form control is enabled/disabled
2. Emit a `valueChange` so each control in the form can enable/disable itself
3. Do NOT fire any more cascading `valueChanges`.  When this happens, forms that were disabled in step 2 become re-enabled.

**Comment by noamichael** [comment]
@pmulac My case seems simple now compared to yours! Have you looked into `AbstractControl#updateValueAndValidity`? You may be able to use it to manually update your subforms validity and disabled state instead of relying on`{ emitEvent: true }`.

 I also think this use case can be made generic, like mine, so that you can just pass a tree structure into a function which will manage creating all the subscribers for you.

I love Angular 2, but I think we need better documentation on complex form definitions.
