### ISSUE TITLE
ngModel with select not updating select element value

### ISSUE THREAD

**Issue by xonuzofa** [angular/angular#13683]
**I'm submitting a ...**  (check one with "x")
```
[x ] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
The [(ngModel)] is not properly setting selectbox value to the model variable.

**Expected behavior**
The [(ngModel)] would properly set the selectbox value to the model variable.

**Minimal reproduction of the problem with instructions**
```
<select [(ngModel)]="model.category" (change)="onChangeCategorySelect($event)" name="category" class="form-control" required>
    <option value="default">Select category</option>
    <option *ngFor="let category of categories" [value]="category.id">{{ category.name }}</option>
    <option value="add">Add new category</option>
</select>

onChangeCategorySelect(event) {
        let value = event.target.value;

        if (value == 'add') {
            alert("add new cat");
            this.model.category = 'default';
        }

        //event.target.value = this.model.category;

        this.model.subcategory = 'default';
    } 
```
The select box does not change to option "default" (it does sometimes, its intermittent) unless uncommenting the line event.target.value = this.model.category.  This means that the [(ngModel)] is not setting the select box value correctly. I have tested this with 1 way binding [ngModel] to ensure its not setting the value after the function is called.  Setting the value of model.category inside the change function, same results. I can also confirm this because when I put a breakpoint in the browser at the onChange event, the model.category has changed to "default" but the select box value is still "add".  So when I click "default" option, I get a changed event even though it should already be set as "default".

**What is the motivation / use case for changing the behavior?**
For the selectbox to work properly with the 2 way binding of ngModel.

**Please tell us about your environment:**
MacOSX, lite-server, visual studio code, TS, gulp, system.js

* **Angular version:** 2.3.0

* **Browser:** 
Chrome
 
* **Language:** 
Typescript ES6

**Comment by DzmitryShylovich** [comment]
Add a small repro in plunkr

**Comment by xonuzofa** [comment]
https://plnkr.co/edit/b1vhcwKAytyQ49qnzpan?p=preview

**Comment by DzmitryShylovich** [comment]
> import {Component} from 'angular2/core';

...

Pls use this https://plnkr.co/edit/tpl:AvJOMERrnz94ekVua0u5 template

**Comment by xonuzofa** [comment]
https://plnkr.co/edit/68oaspPsIBuDkrDkQahX?p=preview

**Comment by DzmitryShylovich** [comment]
You should use `ngModelChange` event instead of native `change`. `change` is called before `ngModel` updates select value.

**Comment by xonuzofa** [comment]
`ngModelChange` gives the same results.

**Comment by DzmitryShylovich** [comment]
and what is the expected behavior?

**Comment by xonuzofa** [comment]
Here is the updated plunker. https://plnkr.co/edit/nYV2TXWuUU5piUh4na2D?p=preview.  I have added a button next to the select list.  The model.category starts as "default".  When you click the select list and click on add option, the value "add" is pushed to the function (ngModelChange).  Inside the function onChangeCategorySelect, if the value is "add", change the model to model.category = "default".  The model is now default (click on the button) but the select box value is still "add".  It does not update the value of the select box correctly.

**Comment by xonuzofa** [comment]
This is the expected behavior. https://plnkr.co/edit/68oaspPsIBuDkrDkQahX?p=preview.  Must manually set the select box value for it to work.  event.target.value = this.model.category;

**Comment by vfedoriv** [comment]
So, you have **two different objects**: event and this.model.
And "must manually set event.target.value = this.model.category "
You want set this automatically ?

**Comment by xonuzofa** [comment]
`event` is the event from the selectbox, `event.type` is change when using `(change)`.  `event.target` is the actual select box.  `event.target.value` is the select box value.  2 way bindings should automatically update the selectbox value whenever model.category is changed, correct?  `[(ngModel)]=model.category`.  So how come when you change this.model.category inside the change function, it does not update the select box value?  You have to manually set via the `event.target.value`.  This is a bug.

**Comment by alex88** [comment]
Same here, I've this markup:

```
          {{parentCategoryIdentifier|json}}
          <select name="category" [ngModel]="parentCategoryIdentifier" (ngModelChange)="parentCategoryChanged($event)" class="form-control">
            <option [ngValue]="undefined">Select a category</option>
            <option *ngFor="let category of categories" [ngValue]="category.identifier" [innerHTML]="category.name"></option>
          </select>
```

and even if `this.parentCategoryIdentifier === this.categories[12].identifier` is `true` (12 is the index of categories I've selected, the select is blank and no values have the selected attribute

**Comment by jasonaden** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).

**Comment by alan-ma** [comment]
Hey! I am having the same issue and I can't seem to find this anywhere else.

The goal is to choose an option from <select> and call a function through (ngModelChange).
The value bound to the <select> (in this case, model.category) is accessed and reassigned to the default value in the same function. The expected behaviour is that the <select> element shows the default value (since it is bound to model.category) and not the value that the user chose.

However, even though model.category is set, the <select> does not display this change (it shows the option that the user selected). In my case, printing (console.log) the value of model.category in the same function shows the default value (expected behaviour) – but the <select> element does not. I think the issue has to do with setting the value of model.category in the same event/cycle where it is changed.

My workaround is to reset the value of model.category asynchronously (maybe using a timeout function) – this works fine.

**Comment by spraju92** [comment]
@xonuzofa @alan-ma Hello, Any solution for this issue?? I'm also facing the same issue. 
Expected behavior:
When select an drop down element following function is going to set default option through model.category, so it should get updated to default option.

Actual behavior:
When setting default option trough model.category it's not getting updated and still it is displaying current selected option from the drop down.
Can any one help me, is it is a bug or doing some ting wrong with applying functionality.
