### ISSUE TITLE
Proposal: Add provider API for `useExisting` with a fallback

### ISSUE THREAD

**Issue by jelbourn** [angular/angular#13854]
In Material, there are a number of services we want to be singletons. If these services are provided as part of the NgModule, the application would end up with multiple instances of the service.

We could work around this by having each service inject its own ancestor instance and delegate to that ancestor's state, but this adds needless complexity to the code. Instead, we can do this through the provider like this:
```ts
export function VIEWPORT_RULER_PROVIDER_FACTORY(parentDispatcher: ViewportRuler) {
  return parentDispatcher || new ViewportRuler();
};

export const VIEWPORT_RULER_PROVIDER = {
  // If there is already a ViewportRuler available, use that. Otherwise, provide a new one.
  provide: ViewportRuler,
  deps: [[new Optional(), new SkipSelf(), ViewportRuler]],
  useFactory: VIEWPORT_RULER_PROVIDER_FACTORY
};
```

Obviously, this is a lot of boilerplate. This also disconnects from the DI system in an unhappy way (having to manually call `new` on the service, potentially forwarding parameters).

It would be much simpler to have a provider syntax that extended the `useExisting` mechanism with a fallback for when there is no existing provider. E.g.,
```ts
{provide: ViewportRuler, useExisting: ViewportRuler, fallbackClass: ViewportRuler},
{provide: ViewportRuler, useExisting: ViewportRuler, fallbackValue: new ViewportRuler()},
{provide: ViewportRuler, useExisting: ViewportRuler, fallbackFactory: () => new ViewportRuler()},
```

Material had been using a `forRoot` function on each module in an attempt to avoid this issue, but that ultimately defeated the point of having an `NgModule` import its dependencies, as you'd still wind up relying on the fact that the user diligently included the `forRoot()` module in bootstrap. 

This still doesn't completely solve the "I want a global singleton" problem, as one still might have the same provider defined in two sibling modules, but this would help.

@IgorMinar @vicb 

cc @pkozlowski-opensource @vsavkin, this might interest you

**Comment by PFight** [comment]
+1 to boolean useExisting, it is short and nice. Another variants:
1. rootProviders, that creates providers with useExisting by default true and should be used for providing application-level services.
2. scope: ServiceScope.Application - to explicitly say, that service is application-level singleton, and should not be dublicated on import.

**Comment by haschu** [comment]
I really like this proposal! Are there any plans to implement this feature in the near future?

**Comment by intellix** [comment]
I'd like to add our use-case as we're interested in this as well. We've got FeatureModules that we configure using DI:

**chat-config.value.ts**
```ts
import { InjectionToken } from '@angular/core';

export interface ChatConfig {
  showHeader: boolean;
}

export const CHAT_CONFIG = new InjectionToken<ChatConfig>('chat-config');
export const chatConfig: ChatConfig = {
  showHeader: true,
};
```

**chat.module.ts**
```ts
@NgModule({...})
export class ChatModule {
  static forRoot(config: ChatConfig = chatConfig) {
    return {
      ngModule: ChatModule,
      providers: [
        {
          provide: CHAT_CONFIG,
          useValue: config,
        },
      ],
    };
  }
}
```

You get the default by importing into AppModule: `ChatModule.forRoot()` and can override the config like: `ChatModule.forRoot({ showHeader: false })`

Problem is that when you lazily load it, you can no longer call forRoot and to provide that default config. You've got to manually provide it despite the ChatModule solely depending on it.

**Comment by emilio-martinez** [comment]
@jelbourn this perhaps is solved partially as a side effect of the "Tree-shakable Services" API? It still doesn't establish a fallback per se, but given that `provideIn: 'root'` ensures services are provided by the root injector, that would ensure singletons—even for lazy-loaded modules.

**Comment by jelbourn** [comment]
The `providedIn` syntax helps, but it's not usable in situations where you need `ComponentFactoryResolver`.

**Comment by magicmatatjahu** [comment]
Maybe it's an outdated issue but I have an idea to fix it by creating a helper function based on `useFactory` and hack Angular using provider definition:

```ts
function useFallbackExisting(provider: any) {
  return {
    provide: provider,
    useFactory: (parentProvider: any) => {
      // null is returned by NullInjector if provider doesn't exist in parent(s) injector
      if (parentProvider !== null) return parentProvider;
      // provider must be annotate by @Injectable() decorator so it works only with class provider, for useValue, useFactory we can add another `if`
      if (provider.hasOwnProperty("ɵfac")) {
        // we can add here also try {} catch {} etc to supports cases with optional deps etc...
        return provider["ɵfac"]();
      }
      return undefined;
    },
    deps: [[new Optional(), new SkipSelf(), provider]],
  }
}
```

It's a bad hack because we manually call internal `factory` function of provider, added by Angular compiler (it should be called by Angular itself).

Why this works? It's so complicated, but I try to explain: Angular in injection time use [`inject`](https://github.com/angular/angular/blob/master/packages/core/src/di/injector_compatibility.ts#L133) function. Each call of inject change context of resolution, it means change injector (check this https://github.com/angular/angular/blob/master/packages/core/src/di/injector_compatibility.ts#L44). In example which I provided, if you wanna create provider/component where you want use the `provider` type, then Angular runs above `useFactory` function, if found given provider in parent(s) injector then returns it, otherwise (due to `@Optional()` flag) returns null. Next, we check `ɵfac` static property of given provider and run it -> and here is the most important part. Angular when return `parentProvider` value (also null), change context of injection to context from your component/provider and run `ɵfac` factory, so we don't have to pass deps for `provider` like you @jelbourn said:

> having to manually call new on the service, potentially forwarding parameters

Also value is cached to the nearest injector.

Note: using pre-Ivy Angular, the function should looks:

```ts
function useFallbackExisting(provider: any) {
  return {
    provide: provider,
    useFactory: (parentProvider: any) => {
      if (parentProvider !== null) return parentProvider;
      if (provider.hasOwnProperty("ɵprov")) {
        return provider["ɵprov"].factory();
      }
      return undefined;
    },
    deps: [[new Optional(), new SkipSelf(), provider]],
  }
}
```

**Comment by waterplea** [comment]
Maybe we can add an optional factory function to `@Optional` decorator? So that we could define it where we inject it:
```ts
export class MyComponent {
  constructor(@Optional(() => new ViewportRuler()) ruler: ViewportRuler) {}
}
```

**Comment by magicmatatjahu** [comment]
@waterplea Hello! I don't think so that it is solution for described problem, due to fact that it can ends in some situation with multiple instances on relationship NodeInjector <-> Injector (module Injector) and you will create the value "outside" the DI.

Also, what do you want to do is at the moment possible in the Angular:

```ts
export class MyComponent {
  constructor(@Optional() private ruler: ViewportRuler) {
    this.ruler = this.ruler === null ? new ViewportRuler() : this.ruler;
  }
}
```


Maybe I don't understand your point of view correctly, but better will be have a provider's definition written in the injector records, not per single injection "session". I think that author of the issue wants to have logic in this way, that if given provider doesn't exists in the DI tree, then Angular should create the provider record for fallback and reuse it in other injections (not only in single).

**Comment by alxhub** [comment]
After discussing with @jelbourn we can resolve this as no longer an issue. The `providedIn: 'root'` pattern now completely covers this case.
