### ISSUE TITLE
Is the UpgradeModule supported in ie9?

### ISSUE THREAD

**Issue by d-nation** [angular/angular#13917]
I'm seeing unexpected behavior in all of my projects that use the UpgradeModule to upgrade Angular 1 -> 2. So first, is ie9 even supported in the upgrade story?  Details below.

[ x ] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question

**Current behavior**
In my hybrid apps, I load Angular 1 as js, and Angular 2 as compiled typescript.

All Angular 2 code behaves as expected in ie9, but adding in Angular 2 UpgradeModule as the bootstrapper for my Angular 1 apps causes various TypeErrors. 

The most common is **"TypeError: Unable to get value of the property 'ref': object is null or undefined"**. This particular error seems to be centered around angular 1 built-in directives (ng-model, ng-class, ng-click, ng-keyup, etc)

**Expected behavior**
Angular 1 and 2 to both work in an upgrade scenario in ie9 in perfect harmony.

**Minimal reproduction of the problem with instructions**
1. Create a hybrid app (I'm using angular-cli webpack to build the Angular 2 part) with ng-models and ng-clicks in the angular 1 code.
2. Open in ie9.
3. Interact with Angular 1 template elements (click, type, etc)

**What is the motivation / use case for changing the behavior?**
Have to support ie9 as app is b2b and some clients are stuck on ie9

**Please tell us about your environment:**
Problem Env:
Browser OS: Windows 7

Dev Env: 
Angular-cli with webpack (1.0.0-beta.19-3) mixed with gulp for the Angular 1 stuff

* **Angular version:** 2.0.X
Angular 1.5.8 and Angular 2.4.3

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]
IE9
 
* **Language:** [all | TypeScript X.X | ES6/7 | ES5]
Typescript compiled to ES5 and ES3 both produce these bugs

**Comment by mhevery** [comment]
Yes it should be support in ie9. Please provide a plunker which demonstrates the issue.

**Comment by d-nation** [comment]
Ok. I think I figured it out. The core-js shims are not all you need (contrary to the docs).

I dug some more and found that the error was happening in Zone.js, which led me to this repo: https://github.com/narainsagar/angular2-ie9-shims

Adding their shim for 2.1.2 prior to adding in the core-js shims allowed it to work.

Is this normal? If so, perhaps I can help add it to the docs somewhere?

**Comment by mhevery** [comment]
sounds right. @wardbell  do we have this doced?

**Comment by wardbell** [comment]
@mhevery Our documentation on browser support is here: https://angular.io/docs/ts/latest/guide/browser-support.html

This information was supplied to us. I don't know who is responsible for verifying and recommending shims. I don't know who has vetted the shim library mentioned by @d-nation. 

IMO, the docs group has no capacity to make this call. We probably should re-open the issue and then figure out how to respond adequately.

**Comment by d-nation** [comment]
@wardbell I would definitely have benefited from knowing that additional shims are needed.

I can't speak to the vetting of the shims I found. I just know that it made my app work on IE9.

Is there anything I can do to help with this, or better left to people more in the know than I?

**Comment by pkozlowski-opensource** [comment]
I just had a look at https://github.com/narainsagar/angular2-ie9-shims/blob/master/shims_for_IE.dev.js and basically it contains shims for the following functionality:
* `Function.name` - this should be [part of core.js](https://github.com/zloirock/core-js#ecmascript-6-function)
* `URL polyfill for SystemJS` - only relevant to SystemJS and not documented on https://angular.io/docs/ts/latest/guide/browser-support.html
* `classList` - documented on https://angular.io/docs/ts/latest/guide/browser-support.html
* `console` - not documented on https://angular.io/docs/ts/latest/guide/browser-support.html; also see #12169 (might be fixed by #12348)
* `requestAnimationFrame` - not documented on https://angular.io/docs/ts/latest/guide/browser-support.html

Based on the above the actionable items are:
* check the status of `window.console` and document need for a polyfill if we still need it;
* check the status of `requestAnimationFrame` - where it is used and document limitations / need for a polyfill;

I'm on a fence when it comes to SystemJS polyfill - we are using / recommending SystemJS for plunkers only so not sure we want to document it. But we should definitively add it to a plunker setup if needed. 

All in all I believe that this is a mix of investigation and documentation tasks. I'm going to re-open this issue so we can track those.

**Comment by d-nation** [comment]
@pkozlowski-opensource 
shims_for_IE.dev.js didn't work for me on 2.2.0. I used shims_for_IE@2.1.2.js

I'll take a look later today and try to pinpoint the exact shim I was missing.

**Comment by d-nation** [comment]
Ok, the one that did it for me was the RequestAnimationFrame polyfill
https://github.com/narainsagar/angular2-ie9-shims/blob/master/shims_for_IE%402.1.2.js#L114

```
//RequestAnimationFrame (IE9, Android 4.1, 4.2, 4.3)
/*! @author Paul Irish */
/*! @source https://gist.github.com/paulirish/1579671 */
// http://paulirish.com/2011/requestanimationframe-for-smart-animating/
// http://my.opera.com/emoller/blog/2011/12/20/requestanimationframe-for-smart-er-animating

// requestAnimationFrame polyfill by Erik Möller. fixes from Paul Irish and Tino Zijdel

// MIT license

(function() {
    var lastTime = 0;

    if (!window.requestAnimationFrame)
        window.requestAnimationFrame = function(callback, element) {
            var currTime = Date.now();
            var timeToCall = Math.max(0, 16 - (currTime - lastTime));
            var id = window.setTimeout(function() { callback(currTime + timeToCall); },
              timeToCall);
            lastTime = currTime + timeToCall;
            return id;
        };

    if (!window.cancelAnimationFrame)
        window.cancelAnimationFrame = function(id) {
            clearTimeout(id);
        };
}());

**Comment by wardbell** [comment]
Please see the [Browser Support](https://angular.io/guide/browser-support) page. If it covers your requirements great. If it doesn't, please open a new issue with the correction or, better yet, a PR suggesting a correction.
