### ISSUE TITLE
FormControl shortly valid between valueChanges and validation

### ISSUE THREAD

**Issue by david-bulte** [angular/angular#13920]
**I'm submitting a ...**  (check one with "x")
```
[x ] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**

I have a reactive form. One of the fields has a minimum length of 6. I'm not using the minLength directive for validation, as I only want to warn the user he hasn't typed enough characters when he leaves the field or stops typing for a couple of milliseconds (actually 400). Therefore validation is handled through subscribing to the field's valueChanges Observable:

```
     const ctrl = this.form.get('password');`
     ctrl
        .valueChanges
        .debounceTime(400)
        .distinctUntilChanged()
        .subscribe(val => {
          if (val && val.length < 6) {
            ctrl.setErrors({minlength: true});
          }
        });

```
This works, however I noticed that, on each "valueChange", the field is set to valid again. If I play with the debounceTime and set it to a 1 second, you clearly see the ngValid styling kick in after each keystroke. If you then wait typing for 1 second, the field is invalidated again.

**Expected behavior**

The field should remain invalid after each valueChange.

* **Angular version:** 2.4.0

**Comment by DzmitryShylovich** [comment]
Pls add a small repro in plunkr

**Comment by david-bulte** [comment]
Here you go: [https://plnkr.co/edit/lgW7pO5A75gpKxBhTpvy](https://plnkr.co/edit/lgW7pO5A75gpKxBhTpvy).

I couldn't immediately get debounceTime() get to work in plunker, but I put alerts before and after the `ctrl.setErrors({minlength: true});` part. You will notice that on each 'before' the FormControl is valid, and on each 'after' it is invalid. I can understand that the first time we arrive in the 'before' part, the FormControl is still valid, but why the second time, when it has been invalidated previously?

Here's that code again:

```
    const passwordCtrl = this.form.get('password');
    passwordCtrl
        .valueChanges
        /* can't get this to work in plunker?
        .debounceTime(400)
        .distinctUntilChanged()
        */
        .subscribe(val => {
          if (val && val.length < 6) {
            alert(`before, valid = ${passwordCtrl.valid}`);
            passwordCtrl.setErrors({minlength: true});
            alert(`after, valid = ${passwordCtrl.valid}`);
          }
        });
```

**Comment by devoto13** [comment]
Because value was changed, validation (required in your case) was rerun and all errors were reset?

**Comment by david-bulte** [comment]
Yes. If the debounceTime would work in the plunker, with each keystroke you'd see the input briefly turn green (because of the ng-valid css rule) before turning to red again.

**Comment by kara** [comment]
It looks like you're handling validation outside of our normal validator pipeline. Typically if you want to manage validation asynchronously, you'd use an async validator that wraps the debounce. That way, we can track when the validator is "pending" a response and can update the control status classes to reflect a PENDING state (rather than a prematurely valid one). However, when you don't pass in the async validator and manually override errors, validation doesn't know about your async use case and will run normal validation based on the validators it *does* know about. This is why your form is deemed valid. It *is* valid based on the validators you've passed in. So this is expected behavior.

Normally I'd suggest switching to an async validator, but in your case, I don't think getting the more correct PENDING state will actually help you. If I'm understanding correctly, you want the field to stay red or green until the debounce period has passed. In that case, I'd recommend using the normal minlength validator, but setting your own styles.  Generally speaking, validation runs when the value updates, but you control when and how the UI updates for the user. Rather than trying to set the errors after the value changes are debounced, I'd try setting your error styles instead. This would mean creating your own set of status classes and only activating them once the appropriate time has passed.

That said, I think the developer experience could use a lot of work. We should have a much easier and more obvious way to debounce user input on validation that doesn't require creating your own status classes. There are a few issues that exist already that encompass some of the shortcomings of using this pattern with forms (like #9119 and #6895). While this isn't technically a bug, it's pretty painful, so I'm going to keep this one open to make sure this use case is addressed. Thanks for the report.

p.s. your plunker was just missing some rx operators. Here is an [updated plunker that works](https://plnkr.co/edit/MHHdfuAYGXrHY7pud28q?p=preview).

**Comment by RKaczmarek** [comment]
I had the same problem. I wanted a solution for debouncing the input and only request the backend when the input changed.

All workarounds with a timer in the validator have the problem, that they request the backend with every keystroke. They only debounce the validation response. That's not what's intended to do. You want the input to be debounced and distincted and only after that to request the backend.

But the only way to prevent that the form is valid for a short period of time while typing is to use  a async validator.

My solution for that is the following (using reactive forms and material2):
The component
```ts
@Component({
    selector: 'prefix-username',
    templateUrl: './username.component.html',
    styleUrls: ['./username.component.css']
})
export class UsernameComponent implements OnInit, OnDestroy {

    usernameControl: FormControl;

    destroyed$ = new Subject<void>(); // observes if component is destroyed

    validated$: Subject<boolean>; // observes if validation responses
    changed$: Subject<string>; // observes changes on username

    constructor(
        private fb: FormBuilder,
        private service: UsernameService,
    ) {
        this.createForm();
    }

    ngOnInit() {
        this.changed$ = new Subject<string>();
        this.changed$
        
            // only take until component not destroyed
            .takeUntil(this.destroyed$)
            
            // at this point the input gets debounced
            .debounceTime(300)
            
            // only request the backend if changed
            .distinctUntilChanged()
            
            .subscribe(username => {
                this.service.isUsernameReserved(username)
                    .subscribe(reserved => this.validated$.next(reserved));
            });
            
        this.validated$ = new Subject<boolean>();
        this.validated$.takeUntil(this.destroyed$); // only take until component not destroyed
    }

    ngOnDestroy(): void {
        this.destroyed$.next(); // complete all listening observers
    }

    createForm(): void {
        this.usernameControl = this.fb.control(
            '',
            [
                Validators.required,
            ],
            [
                this.usernameValodator()
            ]);
    }

    usernameValodator(): AsyncValidatorFn {
        return (c: AbstractControl) => {

            const obs = this.validated$
                // get a new observable
                .asObservable()
                // only take until component not destroyed
                .takeUntil(this.destroyed$)
                // only take one item
                .take(1)
                // map the error
                .map(reserved => reserved ? {reserved: true} : null);
                
            // fire the changed value of control
            this.changed$.next(c.value);

            return obs;
        }
    }
}
```
The template
```html
<mat-form-field>
    <input
        type="text"
        placeholder="Username"
        matInput
        formControlName="username"
        required/>
    <mat-hint align="end">Your username</mat-hint>
</mat-form-field>
<ng-template ngProjectAs="mat-error" bind-ngIf="usernameControl.invalid && (usernameControl.dirty || usernameControl.touched) && usernameControl.errors.reserved">
    <mat-error>Sorry, you can't use this username</mat-error>
</ng-template>
```

**Comment by dylhunn** [comment]
As Kara said above, you should use the `AsyncValidator` API. In particular, this will give you access to a *pending* state, which you can style as you like (e.g. treat it as effectively invalid).
