### ISSUE TITLE
Add component hooks that reflect component DOM state

### ISSUE THREAD

**Issue by artaommahe** [angular/angular#13925]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report
[ x ] feature request
[ ] support request
```

**Current behavior**
Currently available component hooks `AfterViewInit` and `OnDestroy` does not reflect component DOM state, as it was revealed here https://github.com/angular/angular/issues/13921

**Expected behavior**
Add new hooks that will be called on component adding/removing from DOM to prevent a lot of excess checks and unnecessary work until component is really added in DOM.

**Minimal reproduction of the problem with instructions**
see https://github.com/angular/angular/issues/13921 plunkers and discussion

**What is the motivation / use case for changing the behavior?**
Currently available hooks does not reflect component DOM state and are misleading.

* **Angular version:** 2.4.3

**Comment by Toxicable** [comment]
>**What is the motivation / use case for changing the behavior?**

**Comment by artaommahe** [comment]
> What is the motivation / use case for changing the behavior?

Currently available hooks does not reflect DOM state and any DOM nodes access at them can provide unexpected errors despite `AfterViewInit` means that view is loaded and elements are available (e.x. your template does not have any `*ngIf` like directives so all reference should work at `AfterViewInit` hook, but it's not true)

**Comment by pkozlowski-opensource** [comment]
I agree with @Toxicable - it is not clear what you are trying to achieve... I went through #13921 and there is a lot of content there but no minimal, precise use-case. Also based on [this comment](https://github.com/angular/angular/issues/13921#issuecomment-272660678) it seems like the issue was resolved on your end. 

I'm going to close this issue as I don't think it is actionable in the current form. If this is still a problem for you please create a new issue with a _minimal_ use-case and an associated plunker. Thnx!
