### ISSUE TITLE
Improve errors reporting.

### ISSUE THREAD

**Issue by scheglov** [angular/angular#1401]
Currently Angular 2 throws an exception if any of the template expressions has a syntax error.
But this is not an ideal behavior for static analysis.

1. We need to show all the syntax errors to user. It is not good to show them one by one.

2. Exceptions don't include exact locations in a machine form, them have locations in the message, which would be fragile to parse.

**Comment by vsavkin** [comment]
I think linters and IDEs should provide such a feedback, not the framework. You want to get this information statically while editing the code, not after a page refresh.

It is possible though. We just need to change the compiler pipeline to collect errors and throw a composite error message at the end of the proto view construction.

@mhevery, @tbosch what do you think?

**Comment by vsavkin** [comment]
Talked to Misko about it. We should provide a linter that will provide such feedback. Not a high priority right now.

**Comment by yjbanov** [comment]
@vsavkin Some more context: this issue is to support Dart analyzer plugin for ng2, which will channel warning directly into any IDE that's integrated with Dart analyzer (which is practically every Dart-aware IDE). In order for the plugin to be able to reuse the ng2 compiler code the compiler needs to provide a good interface for the plugin to work with. Otherwise, the plugin will have to do its own parsing of the Angular code, which, as practice showed with AngularDart, quickly leads to the two implementations deviate to the point that the analysis is no longer useful.

Therefore, providing a linter does not solve the issue. We need to make the compiler suitable for static tools. That, btw, includes the transformer.

**Comment by mhevery** [comment]
@tbosch discussed this with the dart team, and it was decided that it would be best for the dart team to write their own parser/analyzer. There is no addition action on our side.

The situation will be much improved with #3605
