### ISSUE TITLE
ngc translation merging chokes on messages (from other frameworks) that it can't parse

### ISSUE THREAD

**Issue by vikerman** [angular/angular#14046]
The XMB/XTB can potentially contain messages that have not been added by Angular extraction in cases there are multiple frameworks that add to the messages in the XMB.

For ex. ngc chokes on the following message that has been added by a different framework because of the {{REGION_COUNT 2}...}.

<msg id="1185030469700784449" desc="[ICU Syntax] Some message">{REGION_COUNT_1,plural, =0{unused plural form}=1{1 region}other{{REGION_COUNT_2} regions}}</msg>

**I'm submitting a ...**  (check one with "x")
```
[X] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
ngc message merging fails with an error

**Expected behavior**
ngc is successfully able to merge translations without errors

**Comment by vicb** [comment]
The issue here is that Angular does not support referencing variables as `REGION_COUNT_2` in `{{REGION_COUNT_2} regions}}`. The way to do this in Angular would be to use an interpolation.

Because g3 xmb contain extraction from both soy templates and angular templates, we have to make sure that any construct used in soy templates can be parsed by angular even if angular will not be able to deal with that particular syntax.

The fix is to add an `ICU_REF` token to the lexer/parser. Expect the fix to land sometime next week.

**Comment by vicb** [comment]
Also need to add support for offset

`{REGION_COUNT_1,plural, offset:1 ...}`
