### ISSUE TITLE
UrlHandlingStrategy & UI-Router

### ISSUE THREAD

**Issue by prasannapattam** [angular/angular#14133]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => search github for a similar issue or PR before submitting
[x] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**

No proper migration strategy for migrating Angular 1 UI-Router based apps to Angular 2

**Expected behavior**

Angular 2 Router and UI-Router should run side by side

**Minimal reproduction of the problem with instructions**

**What is the motivation / use case for changing the behavior?**

I have some applications build using ui-router. I intended to migrate them over to Angular 2. I don't have a good replacement for this. ui-router folks are currently working with the new static upgrade. But I want to use the Angular 2 routing.

**Please tell us about your environment:**

Windows 10, Visual Studio 2017, IIS

* **Angular version:** 2.0.X

2.4

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

NA 

* **Language:** [all | TypeScript X.X | ES6/7 | ES5]
TypeScript 2.x

* **Node (for AoT issues):** `node --version` =

**Comment by DzmitryShylovich** [comment]
ui router is a 3rd party lib and not maintained by the core team. So I don't think it should be a part of the angular official docs.

**Comment by prasannapattam** [comment]
I believe most large applications are build using UI-Router as the Angular 1.x router is not versatile enough to support large application. As part of migration story, you need to support UI-Router based applications so that you can provide smooth migration to Angular 2. 

UI-Routing is providing a migration story for those using UI-Router. I guess I need to live with UI-Router after migrating to Angular 2.

**Comment by DzmitryShylovich** [comment]
there's a version of ui router for angular 2

**Comment by prasannapattam** [comment]
They still don't have a solution for the new static upgrademodule
https://github.com/ui-router/ng1-to-ng2/issues/26

**Comment by zaenk** [comment]
Alternatively, if you really want to migrate to Angular Router from UI Router, you can achieve some "interoperability" by:
* making a top level sibling `ui-view` and `router-outlet`
* providing `Router` and `UrlHandlingStrategy` for AngularJS on bootstrap
* redirecting unknown URL to a state with an empty view in UI Router
* manually calling `Router.navigate` from `$urlRouterProvider.otherwise` or from a custom directive for navigation

I tried to sketch it in some more details, but I'm not sure, how well would it scale for larger application:  https://gist.github.com/zaenk/21e8bee3071f339aed27f411822bb8d9

Although, the restriction, that the AngularJS states and Angular routes cannot have a common layout is probably a no-go for many devs.
