### ISSUE TITLE
feat: support i18n translation through google translate via command line 

### ISSUE THREAD

**Issue by born2net** [angular/angular#14145]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => search github for a similar issue or PR before submitting
[x ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
currently the i18n will generate xliff which the developer has to find a way to convert

**Expected behavior**
I would love to see ability to simply supply your google secure token and have it run through the google translator and provide with final translation file. 
even better would be to supply all locals (he, es, en) and have i18n create all the file locals that executed through the google translator. Now that would be awesome!

Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]
all
 

Angular 2 Kitchen sink: http://ng2.javascriptninja.io
and source@ https://github.com/born2net/Angular-kitchen-sink
Regards,

Sean

**Comment by ocombe** [comment]
Hello, this looks like a very nice tool to have, but it's being the framework capabilities.
A few existing service like this already exist, you can try crowdin for example which supports machine translations: https://support.crowdin.com/configuring-machine-translation-engines/

I agree that it is not automated for your project, but it is probably something that you can build yourself using the google translate API: https://cloud.google.com/translate/docs/

**Comment by martinroob** [comment]
I actually integrated such a feature into [xliffmerge](https://martinroob.github.io/ngx-i18nsupport). It can now use Google Translate to generate a fullly translated version of for XLIFF/XMB ng extracted file (it supports all ngx supported formats).

My translation webapp [TinyTranslator](https://martinroob.github.io/tinytranslator) also has this feature integrated. For demonstrationn purposes it is publish in a French and a Russian version, which are both fully automatically generated (the russian one I cannot even read because of the kyrilic characters).

**Comment by nfriend** [comment]
I had the same need, so I wrote a small command-line utility that auto-translates `.xlf` files using Google Translate: https://github.com/nfriend/google-translate-xlf.
