### ISSUE TITLE
ngModelChange does not update the input's value

### ISSUE THREAD

**Issue by michaelpwilson** [angular/angular#14251]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

I have a form which uses ```*ngFor``` to loop over an array to create an input field for each item.

This array starts with 1 item, but when a number is entered into one of the input fields, more items are added to the array based on this number.

I am using ```(ngModelChange)``` to push the new items to the array when the number is entered.

**Current behavior**

When binding the item's value it is present, but for some reason the input's value is blank.

**Expected behavior**

The input's value not to be blank.

**Minimal reproduction of the problem with instructions**

http://plnkr.co/edit/5P0nt68FSFH2UuEpJRnh?p=preview

* **Angular version:** 2.4.5

* **Browser:** all
 
* **Language:** TypeScript 2.0.2

**Comment by DzmitryShylovich** [comment]
http://plnkr.co/edit/f5lc5LtVa4Wp0bzq2UqM?p=preview

**Comment by michaelpwilson** [comment]
Hi @DzmitryShylovich, the plunker you've posted hasn't fixed the issue.

**Comment by DzmitryShylovich** [comment]
because all your inputs has the same name

**Comment by DzmitryShylovich** [comment]
http://plnkr.co/edit/f5lc5LtVa4Wp0bzq2UqM?p=preview

**Comment by michaelpwilson** [comment]
Ah I see, now it is working! Thank you!

**Comment by suchetaswabhav** [comment]
I want to change the count of the filterdata [i.e. [(ngModel)]="filterdata"] after the data has arrived in the tables. For Example:

![image](https://user-images.githubusercontent.com/37062796/40268278-1f52c9ce-5b88-11e8-84ef-6b9a9ded1fc1.png)


Initially in the text-box, i entered "experia" so all the data from the database that has experia appeared in the table. And the number of data is displayed on the right-hand of the table as you can see in the picture => "Number of searched data = 6". However, the issue is, if i enter text again in the search-text box and the data filters, but this filtered data number is not displayed, like "Number of searched data =4", of course this number will be less than the maximum number i.e.=6.It remains the same as >> "Number of searched data = 6" even though the total data displayed number is 4.

I have used an (ngModelChange) because i thought it might work, but it doesn't.

code:

transaction.component.html

  <input class="form-control" id="input1-group1" style="margin- 
   top:20px" type="text" name="search" placeholder="Enter Search Text"
              [(ngModel)]="filterdata"  (ngModelChange)= 
    "countFilter(filterdata)"(keyup.enter)="searchByText(filterdata)">

 //code

  <h2> Transaction  </h2>
  <label *ngIf="toShowCount" id="arrayCountId"> Number of searched 
  data  : {{arrayCount}}</label>



**transaction.component.ts**

 countFilter(filtData){

    console.log("inside countFilter = "+ filtData)
    this.countFilterData = filtData.length;

    if(this.arrayCount>=0){

      if(this.countFilterData<this.arrayCount){
         
      // console.log("inside if -arrayCount = "+ this.arrayCount)
      //   this.arrayCount=this.countFilterData;


      var result = [];
      var url = config.url;
      var port = config.port;
  
      this.http.post("http://" + url + ":" + port + "/transaction/masterSearchTransactionForm/", this.filterObj
      , { headers: new Headers({ 'Authorization': 'Bearer ' + localStorage.getItem('Token') }) })
      .map(result => this.result = result.json())
      .subscribe((res: Response) => {
        console.log("# DATE FILTER RESULT TRANSACTION  XXXXXXXXXXXX", res);
         this.records = res;

         this.toShowCount =true;
        console.log ("the result of SearchByText is =  ", this.result)
         this.arrayCount = this.result.length;
         console.log("ArrayCount = " , this.arrayCount)
         console.log("search-by-text  records = ",res)

        console.log("Search by Text result is : " + result)
        if (this.result.length > 0) {

          this.notify.Success("Data Displayed Successfully");
          this.loading = false;

        }
        else {
          this.notify.Error("No Matching Data Available")
          // this.dateTransactionForm.reset();
          this.loading = false;

        }
      });


      }
    }
