### ISSUE TITLE
Question on property binding in components

### ISSUE THREAD

**Issue by PascalPrecht** [angular/angular#1425]
There's seems to be a confusing thing.
 
We know that `<ANY [prop]="expr;">` writes to the element property of `ANY`.

However, in a component annotation, we actively have to declare:
```js
@Component({
  properties: {
    'prop': 'prop'
  }
})
````
Which actually makes sense, because we want the value that is written to the component's dom element to be reflected to the directive's property.

However, it turns out that no declared property of the component annotations is ever written to the component's dom element whatsoever (as long as it's not a standard HTML element property).

Which means, the dom element properties are actually never touched, so why do we have to explicitly declare `properties` then?

I could imagine that, if it turns out that the element is actually a directive, then there's no reason to write to the directive's dom element property, because the directive works with the directive property. But then again, why do we need to declare it like that, to make it work? Is it just to allow different naming? Like

```js
properties: {
  'internalProp': 'differentName'
}
```

Not sure why it is required to have `properties` to make it work at all then, because we already *do* write to element/directive properties with `[prop]` syntax...

**Comment by jelbourn** [comment]
The `properties` part of a Component's annotation deals with attributes on the _host element_ of that Component, which is not part of the component's template (and thus can't be dealt with via bindings).

You can imperatively set properties to the host element using `PropertySetter`. Currently, you inject one per property, like this: `@PropertySetter('tabindex') tabIndexSetter`. However, the API may be changing before too long.

Look for examples of `@PropertySetter` in the `examples/` directory (particular the material design components).

**Comment by PascalPrecht** [comment]
@jelbourn thank you for your quick answer.

>The properties part of a Component's annotation deals with attributes on the host element of that Component, which is not part of the component's template

That's clear.

>(and thus can't be dealt with via bindings)

That's not.

Isn't the whole idea behind `[*]=""` and `bind-*=""` syntax that we write to the (DOM element) properties of a component?

For example if this:

```
<ANY [prop]="foo">
```

Would be a Web Component, it would write to the custom element DOM property `prop`.

So I expect that if the same code would be a directive, that is writes to either the directive's property `prop`, or the underlying DOM element property `prop`. In the latter case, it *does* make sense to explicitly declare "please 'bind' this DOM element property, to that directive property".

But again, it turned out, that the value is *not* written to the DOM element's property. The question remains, why do we need to declare it then?

I really have problems getting the point of it :(

**Comment by jelbourn** [comment]
Say you have a component called `AwesomeRadioButton` that looks like this:
```js
@Component({   selector: 'awesome-radio' })
@View({ templateUrl: "radio.html" })
Class AwesomeRadio { /** Do some stuff */  }
```
```html
<!-- radio.html -->
<div class="radio-on" *if="checked"></div>
<div class="radio-off" *if="!checked"></div>
```

Great, you have a custom radio button. You put on one the page like this:
```html
<label for="radio-greeting">Hello</label>
<awesome-radio id="radio-greeting"></awesome-radio>  <!-- <<< host element -->
```

There's a problem, though. This element needs a `role` so that screen readers know it's a radio button. We _could_ do this:

```html
<label for="radio-greeting">Hello</label>
<awesome-radio role="radio" id="radio-greeting"></awesome-radio>
```
But it's super lame to have to manually put the `role` on the radio every time. The Component itself should be able to set this for you. This `awesome-radio` element, though, isn't _in_ the Component, it's the _host_ of the component. That's where `properties` and `ProperttySetter` come in- they give the component a way to set things on the host element so that the end-user doesn't have to (and in most cases, can't, such as for aria-checked). 

In general, bindings _are_ used to set properties to both Component instances and the underlying DOM element, but for its host element a Component needs to set them manually.

**Comment by PascalPrecht** [comment]
Wait, so does that mean that

```
properties: {
   internalName: 'domElementPropName'
}
```

Writes `internameName -> domElementName` ? Not the other way around?

**Comment by jelbourn** [comment]
If you have 
```js
@Component({
  selector: 'cool-checkbox',
  properties: {
    isChecked: 'checked'
  }
})
```

And then
```html
<cool-checkbox [checked]="isActive"></cool-checkbox>
```

Then both the DOM `checked` and the Component's `isChecked` will be updated whenever the binding changes.

However, if `inside` the Component, you write
```js
myClickHandler() {
  this.isChecked = !this.isChecked;
}
```

The `checked` property of the DOM element _won't_ be updated. You would have to use a `PropertySetter` to do that. This is due to the unidirectional, top-down nature of the change detection in Angular 2.

RELATED NOTE: very soon, `properties` is going to change from a map to an array, like this:
```js
@Component({
  selector: 'cool-checkbox',
  properties: ['checked']
})
```
And the Component class property will always be the same as the element attribute.

**Comment by PascalPrecht** [comment]
> Then both the DOM checked and the Component's isChecked will be updated whenever the binding changes.

That was also what I expected, but I couldn't see the property on the DOM element at all. So then, the way it works is really what I understood, the fact that the stuff didn't show up on the DOM element is a different issue...

**Comment by jelbourn** [comment]
I see; might be a bug then (we have plenty!). You _should_ be able to use plunker to demonstrate bugs now (though the version of angular 2 on there might be slightly stale at times).

**Comment by PascalPrecht** [comment]
Thank you for your fast replies Jeremy, now that I know that I understood thing actually right, I can finally move on!
