### ISSUE TITLE
4.0.0 beta6 @angular/core.umd global.rxjs_symbol_observable error

### ISSUE THREAD

**Issue by hstarorg** [angular/angular#14298]
```
[ x ] bug report => search github for a similar issue or PR before submitting
```

**Current behavior**
script error:  `Cannot read property '$$observable' of undefined , `

error in 
```javascript
function isObservable(obj) {
  return !!(obj && obj[rxjs_symbol_observable.$$observable]);
}
```

because:

```javascript
(function (global, factory) {
    typeof exports === 'object' && typeof module !== 'undefined' ? factory(exports, require('rxjs/symbol/observable'), require('rxjs/Subject'), require('rxjs/Observable')) :
    typeof define === 'function' && define.amd ? define(['exports', 'rxjs/symbol/observable', 'rxjs/Subject', 'rxjs/Observable'], factory) :
    (factory((global.ng = global.ng || {}, global.ng.core = global.ng.core || {}),global.rxjs_symbol_observable,global.Rx,global.Rx));
}(this, function (exports,rxjs_symbol_observable,rxjs_Subject,rxjs_Observable) { 'use strict';
```

that `global.rxjs_symbol_observable` is undefined.

**Expected behavior**
right run.

**How to fix?**

Adjust the rollup.config, add `symbol_observable` alias.

Need to : `global.Rx.Symbol`

**Comment by janousek** [comment]
The same problem in 2.4.6.

**Comment by hstarorg** [comment]
@janousek This is a history bug, that fix in some version.

**Comment by ushelp** [comment]
@hstarorg Which version fixed this bug?

**Comment by hstarorg** [comment]
@ushelp Maybe 2.3.x。

**Comment by hstarorg** [comment]
@ushelp There are a litter users use this style.

**Comment by janousek** [comment]
@hstarorg sorry, but 2.3.x is older then 2.4.6. How it can fix this issue?
The same problem is in current version (2.4.7).

**Comment by hstarorg** [comment]
@janousek Add some script after the Rx.jx loaded:
```javascript
Rx.Symbol.$$observable = Rx.Symbol.observable;
window.rxjs_symbol_observable = Rx.Symbol;
```

**Comment by ushelp** [comment]
@hstarorg 试了很多版本，包括最近的几个版本。plnkr 的 的 demo 是可以工作的，咋本地转换后也可以。现在出现这样问题的具体原因可能和加载有关。
纯 JS 的用例估计没有全面测试。

**Comment by hstarorg** [comment]
@ushelp plnkr used amd loader, so it work right.

When use global var, the problem will be reproduced.

**Comment by ushelp** [comment]
是的，对于全局方式加载存在问题。当前可以自行适配避免bug。
            On 02/15/2017 22:48, Jay.M.Hu wrote: @ushelp plnkr used amd loader, so it work right.
When use global var, the problem will be reproduced.

—You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/angular/angular","title":"angular/angular","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/angular/angular"}},"updates":{"snippets":[{"icon":"PERSON","message":"@hstarorg in #14298: @ushelp plnkr used amd loader, so it work right.\r\n\r\nWhen use global var, the problem will be reproduced."}],"action":{"name":"View Issue","url":"https://github.com/angular/angular/issues/14298#issuecomment-280029993"}}}

**Comment by hstarorg** [comment]
Angular的适配环境较多，难免测试不充分。这种小bug，还是蛮多的。

**Comment by hstarorg** [comment]
@uparlange  When I upgrade the angular version, I'll add some `rxjs-fix`, like: 
```
Rx.Symbol.$$observable = Rx.Symbol.observable;
window.rxjs_symbol_observable = Rx.Symbol;
window.rxjs_observable_merge = Rx.Observable;
window.rxjs_operator_share = Rx.Observable.prototype;
```
