### ISSUE TITLE
Angular 2 RC1 Version Expiry Date

### ISSUE THREAD

**Issue by Raghuram0106** [angular/angular#14476]
- Will Angular 2 RC1 version get deprecated in near future?
- Is there any way that we can get notified on deprecating older versions like Angular 2 RC1?
- Do we get support for Angular 2 RC1 issues in future?

**Comment by DzmitryShylovich** [comment]
> Will Angular 2 RC1 version get deprecated in near future?

http://angularjs.blogspot.com/2016/12/ok-let-me-explain-its-going-to-be.html

> Do we get support for Angular 2 RC1 issues in future?

nope. angular hasn't have LTS versions yet.

**Comment by RicardoVaranda** [comment]
Hi @Raghuram0106 , Is the a specific reason as to why you are not updating to the latest releases? 

With the upcoming release of Angular 4 I believe it will be really hard to have an effective solution that will fit all needs and thus the likeliness of older versions being deprecated is imminent especially RC.

In order to make use of latest technology it's important to keep applications up to date for both security and performance reasons.

I do like the second point you asked regarding the notification when using older versions of Angular that can be very insightful to let people know they are using a version which is out of date / not recommended.

**Comment by neilhem** [comment]
> Long Term Support planning
Have been talking to many enterprises who don't have ability to upgrade as often as we make major releases.
For these folks, we want to create LTS for AngularJS and Angular so they can feel comfortable deciding on a release to use across their enterprise for a longer period than our release schedule.
Currently deciding the details of how 'long' long will mean and what types of fixes.

From Angular Weekly Meeting Notes, January 30

**Comment by vicb** [comment]
Our plan for LTS are being defined. Most probably no LTS for 2.x but keep posted for the details.
