### ISSUE TITLE
Add canUse guard

### ISSUE THREAD

**Issue by vsavkin** [angular/angular#14515]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => search github for a similar issue or PR before submitting
[x] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

Currently we have two main types of guards:

* `CanLoad`: decides if we can load a module (used with lazy loading)
* `CanActivate` and friends. It decides if we can activate/deactivate a route.

So we always decide where we want to navigate first ("recognize") and create a new router state snapshot. And only then we run guards to check if the navigation should be allowed. 

This doesn't handle one very important use case where we want to decide where to navigate based on some data (e.g., who the user is).

I suggest to add a new guard that allows us to do that.

```
[
  {path: 'home', component: AdminHomePage, canUse: [IsAdmin]},
  {path: 'home', component: SimpleHomePage}
]
```

Here, navigating to '/home' will render `AdminHomePage' if the user is an admin and will render 'SimpleHomePage' otherwise. Note that the url will remain '/home'.

## Implementation Notes

* This should be handled in both applyRedirects and recognize.

**Comment by DzmitryShylovich** [comment]
Sounds similar to https://github.com/angular/angular/issues/12088

**Comment by vicb** [comment]
Sounds good, what about `when:` instead of `canUse:` ?

**Comment by alexbyk** [comment]
Another example when this feature will be useful.
Let imagine some social network where everyone can register a short url for his social page, for fan group, chatroom or even his cat .... `http://awesome/URL`, `http://awesome/URL/friends`,  `http://awesome/URL/photos`.

It would be great to have an ability to fetch data from a server (`{type: 'user'}`) only once and decide where to dispatch next instead of fetching something for every potential route.

**Comment by alexbyk** [comment]
Any progress on this feature?

**Comment by DzmitryShylovich** [comment]
> canUse: [IsAdmin]

is this supposed to be just a boolean? or injection token?

**Comment by royling** [comment]
as it's a guard, it's supposed to be injection token, right?

**Comment by itrethan** [comment]
LGTM, Approval

**Comment by ashclarke** [comment]
@atscott - You have my vote and that's the 20 hit 🚀

**Comment by atscott** [comment]
@ashclarke Thanks :) I have been working on this and just need to find time to clean it up and send it out for review.

**Comment by dylhunn** [comment]
@atscott I'm going to remove this from the candidates milestone for 14, since it's not a PR -- is there a corresponding PR that should be prioritized?

**Comment by atscott** [comment]
@dylhunn I've considered sending the PR out as blocked by https://github.com/angular/angular/pull/45023 due to not wanting to have too many in-flight reviews. Our bigger projects have held up some of these smaller tasks. I think this feature may be more straightforward than #45023 so I'll try to get it out for 14.1
