### ISSUE TITLE
Do we need `@Component(properties)`?

### ISSUE THREAD

**Issue by yjbanov** [angular/angular#1454]
The old `@Component(map)` from AngularDart served two purposes:

- map attribute name to setter name
- specify type of binding (`=>`, `@`, `<=>` etc)

These do not exist in ng2. We had pipes there, but they are gone now. The one last use-case this list serves is a sort of documentation of which setters can be bound to, but that seems too weak to be in the core API.

What if we simply allow developers to bind to any public setter of the component class?

Logging to start a discussion.

/cc @vsavkin @mhevery

**Comment by mhevery** [comment]
I think that would break static analysis since it would not be possible to know ahead of time which setters need to be generated.

Also in JS we have no private fields, so having an annotation makes the public list explicit.

My vote is to have public API fully described in the annotation for consistency and for tools.

**Comment by yjbanov** [comment]
We won't generate setters for bindings once we use generated change detectors. Right now we only do this because we use dynamic change detectors. Generated change detector code is derived from the _call site_.

I agree that they need to be there for ES5 and ES6. In Dart and TS they are redundant though.

**Comment by mhevery** [comment]
I don

**Comment by mhevery** [comment]
Closing, reopen if you feel.
