### ISSUE TITLE
Missing error message when bootstrap array is missing app component.

### ISSUE THREAD

**Issue by alexsapps** [angular/angular#14572]
Bug report.

Missing error message when bootstrap array is missing in app that's being upgraded to ng2.

Suppose you forget to add your top-level component AppComponent to your bootstrap array:

```
@NgModule({
  bootstrap: [
    // AppComponent,  // <--- MISSING
  ],
})
export class AppModule {
  // An override to prevent Angular 2 from bootstrapping itself.
  // This is required for apps being upgraded to ng2.
  // Since this method is provided, it doesn't trigger the usual bootstrapping error message.
  // https://angular.io/docs/ts/latest/guide/upgrade.html
  ngDoBootstrap() {}
}
```

And suppose your AppComponent's template is: `<router-outlet></router-outlet>`

As expected, `<router-outlet>` is not populated when the page loads.

Observed: no error message in console
Expected: helpful error message in console such as: "`<router-outlet>` element found in non-bootstrap component"
  
**Minimal reproduction of the problem with instructions**
1. Find an app that is being upgraded from ng1->2 that has the `ngDoBootstrap() {}` override.
2. Add angular2 routing according to:
https://angular.io/docs/ts/latest/guide/upgrade.html#!#dividing-routes-between-angular-and-angularjs
(especially add the `<router-outlet>` to an ng2 `AppComponent` that is put in `index.html`)
3. Remove the bootstrap array from the app module.

**What is the motivation / use case for changing the behavior?**
Better developer experience upgrading to ng2.

**Please tell us about your environment:**
AppEngine. Half upgraded from ng1 to ng2.
who/ajxtaylor

* **Angular version:**
google3 head

* **Browser:** 
chrome

* **Language:**
TS

**Comment by DzmitryShylovich** [comment]
@alexsapps pls provide a plunkr

**Comment by tbosch** [comment]
Using both, `@NgModule.bootstrap` and `ngDoBootstrap`, is an error (and we should warn about it). If you want to allow the router to create a component dynamically, put that component into `@NgModule.entryComponents` instead.

**Comment by gkalpak** [comment]
In this case, I don't think Angular can do something to help. Having an `ngDoBootstrap()` method and no `bootstrap` component is a valid setup and having `<router-outlet>` in a non-bootstrap component is valid as well.

WRT to the docs (although this is based on a [quite old version][1]), the guide [clearly mentions][2] that one should remove the `ngDoBootstrap()` method when adding a `bootstrap` component.

##
Closing this, because I don't think there is any action to take here.

[1]: https://v2.angular.io/docs/ts/latest/guide/upgrade.html
[2]: https://v2.angular.io/docs/ts/latest/guide/upgrade.html#!#create-the-_routing-module_
