### ISSUE TITLE
Pattern Validator: The RegExp object keeps track of the lastIndex where a match occurred, it can cause unexpected results

### ISSUE THREAD

**Issue by DzmitryShylovich** [angular/angular#14669]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
Regexps with `global` flag keep track of the `lastIndex` when a new match is found. This can cause unexpected results:
```
const reg = /abc/g;
reg.test('abcdefghi');    // => true
reg.test('abcdefghi');    // => false <=
```

**Expected behavior**
```
var reg = /abc/g;
reg.test('abcdefghi');    // => true
reg.test('abcdefghi');    // => true
```

**Comment by gkalpak** [comment]
Not sure why this should be `PatternValidator`'s concern. Does the `g` flag enable a usecase that is not possible without?

**Comment by DzmitryShylovich** [comment]
> Not sure why this should be PatternValidator's concern

probably yes... but it can be really unexpected https://github.com/angular/angular/issues/14028#issuecomment-281930733

And I don't see anything bad if we can workaround it inside angular so users don't need to bother about it.
do you think a warning will be better?

**Comment by gkalpak** [comment]
Yeah, if it does not allow an otherwise impossible usecase, I would avoid unnecessary magic under the hood. (Too much magic hasn't always served us well in the past.) A warning would be nice (as long as it is consistent with the overall dev experience - e.g. are there warnings for similar issues).

Just m2c.

<sub>For reference, in AngularJS we just have a warning in [the docs][1].</sub>

[1]: https://docs.angularjs.org/api/ng/directive/ngPattern

**Comment by AndrewKushnir** [comment]
We ended up documenting this behavior as well, here is a link: https://angular.io/api/forms/Validators#pattern-matching-with-the-global-or-sticky-flag. Closing this ticket for now. Thank you.
