### ISSUE TITLE
AoT compiles even when templates are accessing private properties

### ISSUE THREAD

**Issue by Shijir** [angular/angular#14739]
**I'm submitting a ...**  (check one with "x")
```
[ x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**

AoT compiles successfully without giving any warnings when templates are accessing private properties.

**Expected behavior**

AoT compilation is supposed to fail (or not?) when there are templates that access private properties.

References:
https://github.com/angular/angular/issues/11978
https://github.com/rangle/angular-2-aot-sandbox
http://stackoverflow.com/questions/34574167/angular2-should-private-variables-be-accessible-in-the-template

**Minimal reproduction of the problem with instructions**

It's easily reproducible in Angular CLI project (But I noticed this issue in my own project first which doesn't rely on angular cli). I tested it in a default Angular CLI project, where I made the `title` (accessed in the template) property private. After that, I run both `ng serve --aot` and `ng build --aot` one after another. In both cases, AoT was compiling without failure and complaining.

**What is the motivation / use case for changing the behavior?**

**Please tell us about your environment:**

macOS

* **Angular version:** 2.0.X

2.4.8

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

 
* **Language:** [all | TypeScript X.X | ES6/7 | ES5]

* **Node (for AoT issues):** `node --version` = 
v7.2.0

**Comment by DzmitryShylovich** [comment]
it's a cli issue. pls re-open it on https://github.com/angular/angular-cli/issues

**Comment by Shijir** [comment]
@DzmitryShylovich I don't think this is CLI issue. I faced this issue in my own project, which doesn't rely on CLI. Then, to check if this issue happens only in my project, I made the public properties private in a default Angular CLI project and was able to compile it with `ngc` without errors or warnings, which is not an expected behavior. I reproduced this issue again in angular2-seed project.

**Comment by DzmitryShylovich** [comment]
I've just teste it using https://github.com/AngularClass/angular2-webpack-starter and https://github.com/qdouble/angular-webpack2-starter and in both it throws an error http://prntscr.com/edv92i

This means it's a cli issue

**Comment by Shijir** [comment]
@DzmitryShylovich, thanks for looking into this issue. So I investigated the issue further. And I am speculating it's related to @angular/compiler-cli. 

I have actually reproduced the issue in this repo, https://github.com/Shijir/angular2-seed, which is the clone of https://github.com/angular/angular2-seed. So please take a look into the repo and try running  `./node_modules/.bin/ngc -p tsconfig.aot.json`.

The reason why I chose this repo is that it relies on neither webpack nor angular cli. As I mentioned before, this issue first came to my attention in my own project which doesn't use angular cli.

**Comment by DzmitryShylovich** [comment]
have you tried it with ng 4?

**Comment by chuckjaz** [comment]
Curiously if you execute `./node_modules/.bin/ngc -p tsconfig.aot.json` twice you will see an error.

**Comment by Shijir** [comment]
@chuckjaz Yes. I've noticed that and that's how we are doing our AoT sanity check by adding an extra layer of compilation with `ngc`. Baically, we are running `ngc` on the generated `*.ngfactory.ts` files to catch the errors. It would be ideal if `ngc` catch errors on the first run so we don't need to compile `*.ngfactory.ts` files again.

**Comment by youdz** [comment]
The problem comes from the fact that `ngc` squashes 2 very different operations together:
1. Compiling your modules and components to Typescript ngfactories.
2. Transpiling whatever input files you gave it from Typescript to Javascript.

But the thing is, the files you want to transpile to Javascript are **not** your modules and components, they're the ngfactories you just produced in step 1. The way the AoT documentation "solves" this is by giving as input to ngc both the raw source module and a a `main.ts` file that references a not-yet-existing ngfactory. The raw source modules is what makes step 1 happen, the `main.ts` is what makes step 2 happen. It relies entirely on the fact that the order of inputs determines the order of compilation, so by the time `ngc` handles the `main.ts` file, the factories are there. Not that this means IDEs will always throw errors on that `main.ts` file, which is pretty bad.

So what you're seeing when executing twice is just you running step 1 on the first go, but step 2 doesn't happen because you didn't provide a Typescript file that references these newly created factories. So when you run it a second time, if your input is some form of `*.ts`, it grabs these ngfactories and compiles them to typescript as `tsc` would do. Nothing to do with ngc, really. You can actually see that by running `ngc` then `tsc` on the ngfactories, you will also see the errors.

**Comment by jbarr33** [comment]
Can someone explain what the expected behavior is regarding these "AOT rules" and in the run-time app?

I have the latest version of cli and I created a project with "ng new MyApp".  I then created a new component with a **private** property and bound the property to a text input with [(ngModel)] in the template HTML. Then added a simple button to change the text in the input.

I built with "ng build --prod", which I believe is an AOT build by default now...and the app works fine.  Have the AOT rules changed?  Should something break in the app?

It's important to know what the expected outcome of an AOT build actually is.  If a rule is broken and it somehow still works, that's just as scary to me.

Thanks.

**Comment by DzmitryShylovich** [comment]
@Shijir according to https://github.com/angular/angular/issues/15451 it was fixed. can you confirm?

**Comment by trotyl** [comment]
Should already been solved in v5 (with the new transformer-based compiler).

**Comment by chuckjaz** [comment]
Yes. Requires turning on `"fullTemplateTypeCheck"`.

**Comment by Diluka** [comment]
`template` can not access its own `component`'s private properties with `--aot` in `v8`

- is `template` the part of `component`? 
- should `template` access its own `component`'s private properties?

**Comment by pkozlowski-opensource** [comment]
With Angular v9 running ivy we've got a very explicit error message indicating that private properties can't be accessed, ex.:

> src/app/app.component.html(1,27): error TS2341: Property 'name' is private and only accessible within class 'AppComponent'.

https://ng-run.com/edit/tRvgewL303O8M4Liabo9
