### ISSUE TITLE
All unit tests fail in ES6 due to prototype-less factory in jit compiler

### ISSUE THREAD

**Issue by EricABC** [angular/angular#14808]
**I'm submitting a ...**  (check one with "x")
```
[ X ] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

*Note: Related to #13614 and #13853*
Although arguably a duplicate, I filed this separate because it could be easily fixed by changing the signature to unblock unit tests separate from the underlying issue.  Also, I believe this shows that the unifying issue is ES6 implementation.

**Current behavior**
ES6 distributions will result in certain syntax of anonymous functions to not have a prototype.  The JIT compiler [here](https://github.com/angular/angular/blob/126fda2613b1ad87ff62591bb1d3a23cd8f369a1/modules/%40angular/compiler/src/jit/compiler.ts#L125) uses a signature for useFactory that fails all unit tests [here](https://github.com/angular/angular/blob/8b81bb1eb6b57afce4c384f7db2e734cab06421e/modules/%40angular/core/src/reflection/reflection_capabilities.ts#L249).

**Expected behavior**
First, to unblock ES6 unit tests.  Second, to handle factories without prototypes.

**Minimal reproduction of the problem with instructions**
Plunk [here](https://plnkr.co/edit/R78PQPY5MMMSUv5hWYPM?p=preview)
Shows failure in es6.  Change everything to es5 distributions and it works.

* **Angular version:** 4.0.0-rc.1

* **Browser:** [Chrome@latest, edge]
 
* **Language:** [ES6]

**Comment by tbosch** [comment]
Did this work in 2.x? As far as I know, our jit mode never worked with ES6 yet...

**Comment by EricABC** [comment]
Yup, we were at 6 and dropped to 5 for ng4.  I think if I recall JIT output es5 but worked fine with eS6, whereas AOT is outputing full es6 with class and super calls.  It's not devastating, but we do miss a few things like generators.

**Comment by tbosch** [comment]
Here is a plunker that works: https://plnkr.co/edit/CSZEZ1VtyWofjDcKgzaw?p=preview

The error that you are seeing is because the generated code tries to inherit from a class located in `@angular/core`. As our generated code is ES5, it just does a `<SuperCtor>.call(this, ...)`, which does not work with ES6.

This worked in v2.x though, as Angular used to shipp ES5 code with ESM (EcmaScript modules, i.e. `import` / `export`) for all `.js` files in the `@angular/*` npm packages (e.g. [@angular/core/src/animation_player.js](https://github.com/angular/core-builds/commit/f99a331d5fb1b3804b87c0318ea170d93f52eb55#diff-c6ea516b511dbfa21dbbdeb6ddd8c79d)).

In v4.x, Angular started to ship real ES6 code with ESM in the `*.js` files. We are still shipping ES5 + ESM code in `*.es5.js` files (this is what I changed in the plunker). 

To unblock you, please switch to these instead. Eventually, we will add a true ES6 emit for our jit compiler too, but we are not there yet. I created https://github.com/angular/angular/issues/15127 to track this.

**Comment by EricABC** [comment]
Thanks!

**Comment by tbosch** [comment]
Closing, and tracking ES6 output in #15127
