### ISSUE TITLE
Extend HostBinding syntax: reference other elements

### ISSUE THREAD

**Issue by DzmitryShylovich** [angular/angular#14815]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => search github for a similar issue or PR before submitting
[x] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
It's not possible to use `HostBinding` to bind classes/attributes to elements outside an angular app
such as `body` or `html`

**Expected behavior**
It should be possible to bind classes/attributes to `body`/`html` using `HostBinding`:
```
@HostBinding('body:class.test') bodyClass: boolean = true;
@HostBinding('html:class.test) htmlClass: boolean = true;
```

**What is the motivation / use case for changing the behavior?**
1. `body` and `html` are usually outside of an angular app and there's no cross platform way to access them.
2. To be consistent with `HostListener`

**Comment by lazarljubenovic** [comment]
We should really rename `HostBinding` into something else, it's super-misleading to re-define the target from `Host` (in decorator name) to `body` or `html` (in the string argument).

Maybe introduce `@Binding` and `@Listener` that would accept a string in form `target:name`, and then make `@HostBinding` and `@HostListener` a backward-compatible way (and most common use-case)?

---

Anyway, what happens when you specify the same target and same name in two separate components?

```ts
// in component A
@HostBinding('body:class.test') bodyClass = true

// in component B
@HostBinding('body:class.test') bodyClass = false
```

Can we make it deterministic? Can a developer rely on order of execution of those? What about order of updates? The CD cycle traverses the tree top-down, but what about sibling components? 

I'm not sure it makes much sense to have these as decorators. The same stands for the linked issue https://github.com/angular/angular/issues/11698 -- I was the one that opened it two years ago but I'm not so sure it's a good idea looking back on it. A **service** seems more appropriate for this kind of thing.

While it's not hard for a develop to make it, I think it's a good fit for the `@angular/common`, though. It should out-of-the box support for Universal and all that stuff that comes along.
