### ISSUE TITLE
[Dart] How to propagate change down to input

### ISSUE THREAD

**Issue by cgarciae** [angular/angular#1482]
How do I propagate the change in `name` due to the `button`'s click back to the `input` in this example? 

````html
<div>
  <h1>Hello {{ name.value }}</h1>
  <button (click)="name.updateValue('Cristian')">Cristian</button>
  <input type="text" [control]="name">
</div>
```
```dart
library testcomp;

import 'package:angular2/angular2.dart';

@Component(
  selector: 'my-app'
)
@View(
  templateUrl: 'components/test.html',
  directives: const[
    const[ //XXX: workaround for FormDirectives not being const.
      ControlGroupDirective,
      ControlDirective,
      CheckboxControlValueAccessor,
      DefaultValueAccessor],
    If]
)
class AppComponent {
  Control name = new Control('World');
}
```

**Comment by mhevery** [comment]
obsolete

**Comment by gdi2290** [comment]
@cgarciae the problem was that you were only updating the (js) model and not the element directly (input). this is fixed with `<input type="text" [(ng-model])="name>` (in next release) since it correctly wires data-binding.
If you don't mind javascript I have a small example showing how I updated both parts on form submission
[angular-class/angular2-webpack-starter/src/app/components/todo.ts#L68](https://github.com/angular-class/angular2-webpack-starter/blob/4d9645478a83c9e4a0a4a50fd7bb80286da28d60/src/app/components/todo.ts#L68)
