### ISSUE TITLE
aio: internal page links among the guides are incorrect

### ISSUE THREAD

**Issue by wardbell** [angular/angular#14850]
Generating incorrect doc references for converted docs

Repro:
1. http://localhost:4200/guide/learning-angular
2. Click the "setup" link, which is `http://localhost:4200/setup.html`
3. Delivers doc-not-found

The link should be `http://localhost:4200/guide/setup`

We'll need a formula for cleaning up the links as we convert.

**Comment by petebacondarwin** [comment]
This is a bit of a pain because the source contains relative links. In the example given the link is written using markdown:

```
[Setup](setup.html "Setup locally withe Quickstart seed")
```

Unfortunately the app runs with the `baseHref` set to '/', which causes all of these links to be relative to the baseHref.

In the AngularJS docs (and in AIO, outside the the docViewer) we have a directive that intercepts such links and navigates internally instead of allowing the browser to take over.

At this stage I don't see how we can run directives inside the DocViewer, since there don't appear to be an API for adding embedded directives rather than components. But perhaps I am missing something.

**Comment by petebacondarwin** [comment]
We have the same problem for internal links within a document (using `#fragments`).

**Comment by wardbell** [comment]
@petebacondarwin  I DO have an idea:  turn the `<a>` into an embedded component and let it figure out what to do.

The immediate problem is that anchors will be embedded in content projected within other embedded components and, officially, nesting of embedded components doesn’t work. This would be a problem even if we _did_ handle embedded directives.

In practice, the way we’ve implemented it, you can embed component A within B, C, D, etc. as long as A is listed before B,C,D in the array of embedded components. Our algorithm replaces all occurrences of A before all occurrences of B, …   So if we list the anchor component first, we should get away with it.

Too hacky?  We could teach our doc viewer to cope with embedded components properly. That's more complicated and dangerous when we aren't using an AST. I'd vote for trying the "hack" first.

**Comment by petebacondarwin** [comment]
This particular issue has been fixed via #15083
