### ISSUE TITLE
[4.0.0-rc.2] core.es5.js bundle contains ESM import statements

### ISSUE THREAD

**Issue by jsayol** [angular/angular#14909]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report
[ ] feature request
[ ] support request
```

**Current behavior**
The `@angular/core.es5.js` bundle distributed with the 4.0.0-rc.2 `@angular/core` package contains several ESM import statements:
```js
import { Observable } from 'rxjs/Observable';
import { merge } from 'rxjs/observable/merge';
import { share } from 'rxjs/operator/share';
import { $$observable } from 'rxjs/symbol/observable';
import { Subject } from 'rxjs/Subject';
```
See (lines 22-26): https://unpkg.com/@angular/core@4.0.0-rc.2/@angular/core.es5.js

These weren't present on RC.1.

**Expected behavior**
No import statements.

**Minimal reproduction of the problem with instructions**

**What is the motivation / use case for changing the behavior?**

**Please tell us about your environment:**

* **Angular version:** 4.0.0-rc.2

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

 
* **Language:** [all | TypeScript X.X | ES6/7 | ES5]

* **Node (for AoT issues):** `node --version` =

**Comment by jsayol** [comment]
Actually I just checked and all the RC.2 packages do, not just core.

**Comment by kylecordes** [comment]
I think this may be intentional. They are shipping:

* UMD bundle for direct use via SystemJS or script tag
* ES5 code in ES2015 modules ("bundle")
* ES2015 code in ES2015 modules ("bundle")

No longer shipping:

* A big pile of CommonJS files

It's great if you have new-sh build tooling. Could be a problem if you have older build tooling that understands CommonJS but not anything newer.

**Comment by thelgevold** [comment]
The new x.es5 bundles are expected to contain import/export statements. You can think of the new bundles as a rolled-up or "flat" version of the individual esm source files found in version 2.x.
The import/export statements are key to support tree shaking. 

I try to explain some of this a bit more here: http://www.syntaxsuccess.com/viewarticle/angular-bundling-formats

**Comment by jsayol** [comment]
Sorry for the confusion, I was under the impression that "flat ES modules" only referred to the `@angular/core.js` file in this case. If it works better this way then it works and that's it, I just found it a bit counter-intuitive that they're called ES5 modules when they contain ES6 statements.

I'll close this for now. Feel free to reopen if there needs to be any more discussion about it.

**Comment by thelgevold** [comment]
This format is often referred to as "esm". It's a hybrid format where you have regular ES5 JavaScript but add one feature from ES2015 (import and export statements).

Adding import/export statements makes the code Tree Shakable. During bundling the import/export statements fall out since you only include the code behind the import statements in the final bundle.

This means you are left with just plain ES5 in the end. No further down transpiration is needed to run the code.

**Comment by jsayol** [comment]
I've been doing some reading on the matter and the es5 code + es6 imports is definitely the recommended way, so color me a fool. I should have known better :)
