### ISSUE TITLE
Feature Request: ability to produce and load CSS via link tag in index.html

### ISSUE THREAD

**Issue by alxhub** [angular/angular#14914]
Currently CSS is built into NgFactory classes and added to the DOM during component instantiation (with deduplication). This CSS lives in the JS bundle as string constants and is shipped to the browser along with the rest of the application script.

This causes two problems:

- It delays parsing of the CSS until JS execution
- It causes the CSS bytes to be sent twice for server-side rendered pages (once as part of `<style>` tags, and again as part of the JS bundle). The browser pays the cost of parsing twice in this case, too.

I propose that `ngc` be optionally configurable to produce separate CSS files (for components with `ViewEncapsulation.None` or `ViewEncapsulation.Emulated`). We would need to do some work to figure out the exact mechanism - one CSS file per component? module? app? Do we need to run a CSS bundler? How is CSS loaded for lazy modules?

Ultimately, though, this would allow parallel parsing of CSS and JS code, leading to faster TTI. And in the case of Universal rendering, it would remove the overhead of sending two copies of the styles over the wire for every page load.

**Comment by tbosch** [comment]
See https://github.com/angular/angular/issues/11682

**Comment by pcroc** [comment]
We would *really* like the option of having `ng build` to output all styles (in our case, SASS) into a single .css file and not generate styles.bundle.js.

Our use case is a single app with no reusable components, and we would like to apply the same style sheet to server-rendered (non-Angular) error pages.

**Comment by naveedahmed1** [comment]
--extract-css is default in production mode in Angular cli but I still see styles added in head tag with SSR.

**Comment by trotyl** [comment]
@pcroc @naveedahmed1 The `--extract-css` is only for project styles (defined in `angular.json`), not component styles. There's no way to extract component styles as they're determined at runtime:

https://github.com/angular/angular/blob/81e975ad93bee06a80841f3e50b3d5879a05a1da/packages/platform-browser/src/dom/dom_renderer.ts#L43-L44

**Comment by naveedahmed1** [comment]
@trotyl most of the styles I see in head tag with SSR are the styles of Material components.

**Comment by adrianhdz2** [comment]
I would like to add that this implementation would also help start solving the strict CSP problem. [#26152](https://github.com/angular/angular/issues/26152). The big win of static component styles over using nonces is that there is no dependency on a back-end service. 

Having component _class_ styles that apply to all component instances would allow the angular compiler to have static css files because it knows all of the component classes . Therefore, ngc can develop unique hashes to keep encapsulation Ahead-of-Time(AoT) as far as component classes go.  Of course, deciding how to bundle and how much css should go in one file is definitely difficult to figure out. You could essentially just do one css file per js files. This doesn't seem to unreasonable... When to load the css files would also be worth thinking about too, but having link tags inserted into the head to load styles does not violate strict CSP.

Developers following strict csp would have to be mindful of these two limitations. 
1.) Component styles would be on a per class basis and not per instance. 
BUT you can use styles tags (or link tags?) directly in angular template. So you could potentially still design around static component styles with that.
2.) You might be constantly loading css more often then you'd like or front-load all css on initial download.
Although, I find that developers who aim to have a very secure application are already accustomed to size and speed tradeoffs to make that happen.

What do you all think?

**Comment by alxhub** [comment]
I'm closing this out as not feasible. Breaking the connection between component classes (in JS) and their styles would lead to a whole host of problems. Some of these problems would require a vastly different serving architecture to solve.
