### ISSUE TITLE
Improve error message when module imports decorator

### ISSUE THREAD

**Issue by DzmitryShylovich** [angular/angular#15013]
**I'm submitting a ...**  (check one with "x")
```
[x] feature request
```

**Current behavior**
```
@NgModule({imports: [NgModule]})
class SomeModule {
}
```
the above code throws `Unexpected value 'DecoratorFactory' imported by the module 'SomeModule'
`

**Expected behavior**
Should throw the error message containing decorator name

**Comment by pkozlowski-opensource** [comment]
The current error message makes it easier to locate the source of the problem, ex.:

> node_modules/@angular/core/core.d.ts(4270,22): error TS-991010: Value at position 1 in the NgModule.imports of AppModule is not a class

https://ng-run.com/edit/7Ki3LOPPfoshkqfAnKk2

What would be ideal, though, is to have the exact file path / line / column number to point to the exact place where the offending import was added.

**Comment by JoostK** [comment]
I agree with Pawel. In fact, that information should be the primary location of the error, as the `node_modules/@angular/core/core.d.ts` file is not something that can be changed to address the error. We can still include that information as additional information on the diagnostic, so that you get insight into both the usage as well as the declaration.
