### ISSUE TITLE
Components and modules exported from shared modules with forRoot option not available in lazy loaded module

### ISSUE THREAD

**Issue by preetham1290** [angular/angular#15024]
[ X] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see

**Current behavior**
I am exporting CommonModule from '@angular/core', some reusable custom components and custom services from SharedModule as static forRoot : ModuleWithProviders. I am importing SharedModule in AppModule by calling forRoot function. Now all the modules and components exported by SharedModule is available in AppModule and i am able use it in AppComponent. But when i try to import and use the same modules and components from lazily loaded module components i am getting error as
**error: Template parse errors:
Can't bind to 'ngIf' since it isn't a known property of 'p'. ("
</p>
<p [ERROR ->]*ngIf="test">App works if shown</p>**
This part is causing because CommonModule is also exported from SharedModule.
**<app-shared-component></app-shared-component>"): LazyLoadedModuleComponent@4:3
Property binding ngIf not used by any directive on an embedded template. Make sure that the property name is spelled correctly and all directives are listed in the "@NgModule.declarations". ("
</p>**
This is causing because SharedComponent is also exported from SharedModule. which is not available in lazy loaded module.
**Known solution is** : - If i import SharedModule in LazyLoadedModule then this error will not cause. But then i will be importing SharedModule module from many modules.

But services from shared module are available in every where and works fine.

**Expected behavior**
As described above if i import any modules like SharedModule in root module ie AppModule, all the exported modules and components from SharedModule, should be available in all child modules including lazy loaded modules as well. Seems like forRoot works only with services.

**Minimal reproduction of the problem with instructions**
Created plunker in 
https://plnkr.co/edit/8MJCwoFCZ7yniAHl2GYn?p=preview
I have commented 2 lines in LazyLoadedModuleComponent's template. so that it can work now. To test please remove comments so bug can be reproduced.
Also i have created Github repo with same code please have look at it need to work on local machine.
https://github.com/preetham1290/simple-demo

**What is the motivation / use case for changing the behavior?**
Typically few modules like CommonModule from 'angular/core', and reusable custom components, directives will be imported in most of the modules. So instead of importing it in each module we can import it in root module and hence can be used in all child modules.

**Please tell us about your environment:**
Ubuntu 16.x, IDE-Visual studio code

* **Angular version:** 2.0.X
from package.json
 "@angular/common": "^2.3.1",
    "@angular/compiler": "^2.3.1",

* **Browser:** [all]
 
* **Language:** [TypeScript X.X]

**Comment by DzmitryShylovich** [comment]
```
@NgModule({
  imports: [
    CommonModule
  ],
  exports:[CommonModule, SharedComponentComponent],
  declarations: [SharedComponentComponent]
})
export class SharedModule { 
```

and

```
@NgModule({
  imports: [
    LazyLoadedModuleRoutingModule,
    SharedModule 
  ],
  declarations: [LazyLoadedModuleComponent]
})
export class LazyLoadedModuleModule { }
```

Please read documentation before submitting issues. https://angular.io/docs/ts/latest/guide/ngmodule.html

**Comment by preetham1290** [comment]
Yeah i know that. But doesn't that load same module multiple times?

**Comment by preetham1290** [comment]
So then i will not be able to export all my reusable components and import only once in root module?
If i import this way will my lazy loaded chunk size increases?

**Comment by DzmitryShylovich** [comment]
Modules don't inherit access to the components, directives, or pipes that are declared in other modules. What AppModule imports is irrelevant to other modules.

**Comment by preetham1290** [comment]
Thanks for clarification.

**Comment by Gangadharbc** [comment]
'app-header' is not a known element:
1. If 'app-header' is an Angular component, then verify that it is part of this module.
2. If 'app-header' is a Web Component then add 'CUSTOM_ELEMENTS_SCHEMA' to the '@NgModule.schemas' of this component to suppress this message. ("[ERROR ->]<app-header></app-header>
<h2>Users</h2>
<router-outlet></router-outlet>

**Context**:
I have created a component of app-header which includes the routing part. If i include <app-header> in Home, Dashboard component it is working fine but if i include in User is through an error(user is a module which is implemented with lazyload). Can any one help to resolve this.

**Also tried with:**
-->Added the header component in User module, but landed with an error of:
Error: Type HeaderComponent is part of the declarations of 2 modules: AppModule and UserModule! Please consider moving HeaderComponent to a higher module that imports AppModule and UserModule. You can also create a new NgModule that exports and includes HeaderComponent then import that NgModule in AppModule and UserModule.
Error: Type HeaderComponent is part of the declarations of 2 modules: AppModule and UserModule! Please consider moving HeaderComponent to a higher module that imports AppModule and UserModule. You can also create a new NgModule that exports and includes HeaderComponent then import that NgModule in AppModule and UserModule.

-> Created a shared module and included the header component in it, but not succeeded 

Thanks,
Ganga

**Comment by lepabloski** [comment]
Hi there, i have the same problem, i have created the shared module ass docs indicates, and still can´t use de template of the component asociated to de shader module.

`import { NgModule } from '@angular/core';
import { AuthGuard } from './security/auth.guard';
import { BrowserModule } from '@angular/platform-browser';
import { ReactiveFormsModule, FormsModule } from '@angular/forms';
import { HttpModule } from '@angular/http';
// modulos
import { AccesoModule } from './acceso/acceso.module';
import { EgresoModule } from './egreso/egreso.module';
import { IngresoModule } from './ingreso/ingreso.module';
import { UsuariosModule } from './usuarios/usuarios.module';
// modulo de rutas
import { AppRoutingModule } from './app.routing.module';

import { HashLocationStrategy, LocationStrategy } from '@angular/common'
import { AppComponent } from './app.component';
import { NavbarComponent } from './acceso/navbar/navbar.component';
import { SharedModule } from './shared/shared.module';


@NgModule({
  declarations: [
    AppComponent,
    NavbarComponent
  ],
  imports: [
    BrowserModule,
    HttpModule,
    AccesoModule,
    EgresoModule,
    IngresoModule,
    UsuariosModule,
    AppRoutingModule,
    FormsModule,
    ReactiveFormsModule,
    SharedModule,
  ],
  providers: [{ provide: LocationStrategy, useClass: HashLocationStrategy }, AuthGuard],
  bootstrap: [AppComponent]
})
export class AppModule { }
`
thas is de appModule, the shadeModule:

`import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';
import { ShowErrorsComponent } from './../show-errors.component';

@NgModule({
  imports: [
    CommonModule
  ],
  declarations: [
    ShowErrorsComponent
  ],
  exports: [CommonModule, ShowErrorsComponent]
})
export class SharedModule {}`

and here is de ShowErrorsComponent code:

`import { Component, Input } from '@angular/core';
import { AbstractControlDirective, AbstractControl } from '@angular/forms';

@Component({
  // tslint:disable-next-line:component-selector
  selector: 'show-errors',
  template: `
    <small class="red" *ngIf="shouldShowErrors()">
      <p *ngFor="let error of listOfErrors()">{{error}}</p>
    </small>
  `,
})
export class ShowErrorsComponent {

  private static readonly errorMessages = {
    'required': () => 'Este Campo es requerido.',
    'minlength': (params) => 'El minimo numero de Caracteres es ' + params.requiredLength,
    'maxlength': (params) => 'El maximo numero de Caracteres es ' + params.requiredLength,
    'pattern': (params) => 'El siguiente patrón es requerido: ' + params.requiredPattern,
    'numero': (params) => params.message
  };

  @Input()
  private control: AbstractControlDirective | AbstractControl;

  shouldShowErrors(): boolean {
    return this.control &&
      this.control.errors &&
      (this.control.dirty || this.control.touched);
  }

  listOfErrors(): string[] {
    return Object.keys(this.control.errors)
      .map(field => this.getMessage(field, this.control.errors[field]));
  }

  private getMessage(type: string, params: any) {
    return ShowErrorsComponent.errorMessages[type](params);
  }

}
`

i got the same error over and over again...

> Uncaught Error: Template parse errors:
Can't bind to 'control' since it isn't a known property of 'show-errors'.
1. If 'show-errors' is an Angular component and it has 'control' input, then verify that it is part of this module.
2. If 'show-errors' is a Web Component then add 'CUSTOM_ELEMENTS_SCHEMA' to the '@NgModule.schemas' of this component to suppress this message.
3. To allow any property add 'NO_ERRORS_SCHEMA' to the '@NgModule.schemas' of this component. ("v>

any help?? thanks.

**Comment by lepabloski** [comment]
thanks!!!! i`ll try it.

**Comment by lepabloski** [comment]
this is what i get 
`Uncaught Error: Type ShowErrorsComponent is part of the declarations of 2 modules: Shared2Module and EgresoModule! Please consider moving ShowErrorsComponent to a higher module that imports Shared2Module and EgresoModule. You can also create a new NgModule that exports and includes ShowErrorsComponent then import that NgModule in Shared2Module and EgresoModule.`

**Comment by fofaria** [comment]
@DzmitryShylovich your answer

> yes, this is why it's called shared :)

doesn't answer to the question, because the concept of sharing may imply that i won't need to import it again because it's already being **shared**.
Your second explanation however was very good, so thank you for your time.

**Comment by Rishi0405** [comment]
@DzmitryShylovich
I am a little confused here, 

importing the shared module in each lazy-loaded module will increase the chunk size?

for eg: importing CommonModule vs SharedModule in each lazy-loaded module. Could you please give some explanations.

also, which is the best practice CommonModule imported and exported in SharedModule or CommonModule in each lazy-loaded module
