### ISSUE TITLE
Error: Upgraded directive 'ui-grid' contains unsupported feature: 'compile'

### ISSUE THREAD

**Issue by shnmkhk** [angular/angular#15102]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
While upgrading an existing angular1 directive like ui-grid in angular 2 application (since we don't have angular2 counter part for the same directive) using UpgradeComponent/ UpgradeModule approach (https://angular.io/docs/ts/latest/guide/upgrade.html), we are encountering following issue

`Error: Uncaught (in promise): Error: Upgraded directive 'ui-grid' (http://ui-grid.info/) contains unsupported feature: 'compile'`

**Expected behavior**
Smooth upgrade for the angular 1 directive, irrespective of the angular 1 features that it depends on.

**Minimal reproduction of the problem with instructions**
- Added angular 2 version 2.2.1 in package json
- Created an angular 2 typescript class for the angular 1 directive using `extends UpgradeComponent`
- Added the same typescript class in root module
- Bootstrapping the application using the following UpgradeModule approach
`
platformBrowserDynamic().bootstrapModule(AppComponentModule).then(platformRef => {
    const upgrade = platformRef.injector.get(UpgradeModule) as UpgradeModule;
    upgrade.bootstrap(document.body, ['app'], {strictDi: true});
});
`

**What is the motivation / use case for changing the behavior?**
While upgrading an application developed in angular1 to angular2, we could upgrade every single in-house built angular 1 components but a 3rdparty component like ui-grid (http://ui-grid.info/). 

**Please tell us about your environment:**
Windows 7, npm (v4.1.2), Tomcat (8.0+)

* **Angular version:** 2.2.1

* **Browser:** [all]
 
* **Language:** [TypeScript]

* **Node (for AoT issues):** `node --version` =   v6.2.2

**Comment by gkalpak** [comment]
Unfortunately it is not really possible to support `compile` or `pre-linking` for upgraded components, because the phases do not match close enough with Angular's.

We have opted for always failing explicitly instead of sometimes failing silently.

Note that AngularJs "components" (created using the `.component()` helper) do not support `compile`/`link` anyway, so these are very straight-forward to upgrade.

##
All that said, there are some directives out there that only use `compile` to return `postLinking` functions and these should work fine. This seems to be th case for ui-grid, as well.

If you are the author of a library featuring such a directive, you can make the life of you users easier, by replacing `compile: function() { return {post: function() { ... }}; }` with simply `link: function() { ... }`.

If you are the user of a library featuring such a directive, here are a few options off the top of my head (in no particular order):

1. Bug the author of the library to create an Angular version.
2. Bug the author of the library to make the directive upgradeble.
3. Create your own (upgradeable) wrapper directive that acts as a proxy between the non-upgradeable AngularJS directive and Angular.
4. Decorate the non-upgradeable directive, run its compile functions (assuming you have determined it is sideeffect-free), grad the returned post-linking function, attach it to the DDO, get rid of `compile`, profit ([demo][1]):

```ts
  decorator('testDirective', $delegate => {
    var linking = $delegate[0].compile();
    var postLink = linking.post || linking;

    delete $delegate[0].compile;
    $delegate[0].link = postLink;
    
    return $delegate;
  }).
```

<sub>(Finally, keep in mind that not all directives are upgradeable :smiley:</sub>

[1]: http://plnkr.co/edit/EvWUZ9NbheG2ayIc6W59?p=preview

**Comment by gkalpak** [comment]
This 4th option might be something worth doing in `ngUpgrade` itself (along with a warning that your directive might not work as expected), if that makes it easier for people to upgrade. But it is quite risky as well, so it is not something to take lightly.

**Comment by Codefans-fan** [comment]
`Upgraded directive 'uibAccordionGroup' contains unsupported feature: 'replace'.```

I get this problem, any suggest?

**Comment by gkalpak** [comment]
@Codefans-fan, you cannot upgrade directives with `replace: true`, so the only option is to wrap them in another component, upgrade that component and (if necessary) pass bindings to them through that wrapper component.

But this will probably not work in the case of `uibAccordionGroup`, because bootstrap's CSS relies on the exact DOM structure (so inserting a wrapper component in-between will likely mess things up).
(Thx @Foxandxss for clarifying that.)

**Comment by Foxandxss** [comment]
That being said, if any discover a way to avoid replace on any ui-bootstrap code, create a PR there, ping me (so I can see it) and we can create a new version without that.

**Comment by Codefans-fan** [comment]
@gkalpak  Thank you for reply,
I find I can use ngx-bootstrap instead of upgrading ` uibAccordionGroup.`

**Comment by gkalpak** [comment]
I am going to close this, since OP was able to find a solution and the current behavior is a known (and intentional) limitation of ngUpgrade.
