### ISSUE TITLE
Feature: override sub-component implementation

### ISSUE THREAD

**Issue by Juansasa** [angular/angular#15138]
Its possible to override a component but only on metadata level but sometime when change/mock the class implementation itself is needed, for example in this scenario.

`@ViewChild(MyComponent) component;`
`...`
`component.callfn();`

Right now Testbed overrideComponent only allow metadata modification, which makes it possible to modify/mock properties like template, services etc but its not possible to modify, mock or spy on class methods.

Please provide a way to override the class implementation itself.

**Comment by DzmitryShylovich** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).

**Comment by nickiewooster** [comment]
@DzmitryShylovich I changed to a feature request instead

**Comment by kenborge** [comment]
I'm having the same issue with this just with directives instead of components. And it's relevant for both children and parent components/directives.
If you have a directive using @ContentChildren to get a child or is injecting a parent directive in it's constructor, there isn't any way to mock the implementation of these for testing. 

I've read that the old TestComponentBuilder.overrideDirective allowed you to override the implementation of directive. But the new Testbed overrides only allow for metadata.

**Comment by schippie** [comment]
I wanted to voice my support for this ticket as well. As I'm running into a similar problem where I'm trying to override a component which the parent is using through `@ViewChildren` but while I can easily mock a component based on the selector there is no way to do this for the ones listed in annotations.

**Comment by sviat9440** [comment]
UP )

**Comment by JoostK** [comment]
This is where using DI is typically the right way to go, which is well supported in Angular tests.
