### ISSUE TITLE
Slight errors in the template have silent failures

### ISSUE THREAD

**Issue by matanlurey** [angular/angular#1516]
I wrote, on accident:

```html
(click="addPopup")
```

Looking at both the DOM and the console, there was 0 indication that I had done something illegal that caused the event to not wire up.

One more example is with `for`:

```html
*for="#item in items" 
```

Does nothing, because the correct term is `of` not `in`. No error.

**Comment by pkozlowski-opensource** [comment]
Oh, right, I think we can some checks on For syntax as well as "valid" event names (only lower-case letters?). On it.

**Comment by pkozlowski-opensource** [comment]
Hmm, so `<div (click="addPopup")>` is a "funny" one since a browser will parse it into the following attribute name => value pairs:
* `(click` =>,`addPopup`
* `)` => ``

Now, I don't think we should go into the logic of detecting `(click` as "invalid" attribute (not sure what would be a valid heuristic here...). We could eventually throw when encountering `)` - that is - expect to have at least one alphanumeric char in the attribute name. 

@matanlurey any thoughts on this one? What do you think would be an ideal error here?

**Comment by pkozlowski-opensource** [comment]
Oh, maybe we should assume that an attribute starts with `A-Za-z`?

**Comment by mhevery** [comment]
Will be solved by: https://github.com/angular/angular/issues/2014
