### ISSUE TITLE
google chrome 42.0.2311.90 (64-bit)

### ISSUE THREAD

**Issue by avdoshkin** [angular/angular#1523]
Error display in the browser google chrome
![2015-04-24 18 38 35](https://cloud.githubusercontent.com/assets/1705089/7317972/d34ccb68-eaa8-11e4-9441-e424c71c0719.png)

**Comment by pkozlowski-opensource** [comment]
I can't reproduce it on my end with the same version of Chrome (nor any other browser, for that matter). It looks like in your case angular is not booting up. Maybe it doesn't get downloaded due to some network settings / installed Chrome extensions?

In any case it looks like sth linked to your local environment.

**Comment by pkozlowski-opensource** [comment]
BTW, this is wrong repo, AngularJS 1.x is hosted here: https://github.com/angular/angular.js
This repo is for Angular 2.
