### ISSUE TITLE
<template [ngIf]> not working on directive used in contentchildren

### ISSUE THREAD

**Issue by LeResKP** [angular/angular#15358]
**I'm submitting a ...**  (check one with "x")
```
[X] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**

When applying a directive on <template [ngIf]="condition"> which is used in a component with contentchildren the condition is not taken into account. It only works when using *ngIf.

**Expected behavior**

The condition should work when using [ngIf] and I'm not sure it should work using *ngIf since it's not corresponding to the doc when using <template> (https://angular.io/docs/ts/latest/api/common/index/NgIf-directive.html)

**Minimal reproduction of the problem with instructions**

http://plnkr.co/edit/XP7SoJ2Wgl2dADJH5qqt?p=preview

item1 should not be displayed in this plnkr.

**What is the motivation / use case for changing the behavior?**

If in some case we should use [ngIf] on template and some other *ngIf it's very easy to make mistakes.

**Please tell us about your environment:**

Fedora

* **Angular version:** 2.0.X

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

 Chrome Version 56.0.2924.87 (64-bit)

* **Language:** [all | TypeScript X.X | ES6/7 | ES5]
TypeScript

* **Node (for AoT issues):** `node --version` =

**Comment by wKoza** [comment]
Concerning your first question, you don't use *ngIf with <template> element.

**Comment by pkozlowski-opensource** [comment]
@LeResKP I think that you are miss-interpreting how ` @ContentChildren(Item) items: QueryList<Item>;` works.

What is says is: "give me all the instances of the `Item` directive". The `Item` directive has a selector of `template[item]` and this directive matches on a `<template>` element. Presence of `ngIf` has nothing to do here - `ngIf` is just another directive that happens to "seat" on the same `<template>` element. `ngIf` is concerned with the presence / visibility of the _content_ of the `<template>` - not the element itself!

I'm going to close this one since it works as expected. If you want to "hide" `Item` instances from queries than do it like for the second item (`<template item="item2" *ngIf="false"></template>`). You might also want to read more on the template syntax and the meaning of `*` in front of structural directives: https://angular.io/docs/ts/latest/guide/structural-directives.html#!#asterisk

**Comment by LeResKP** [comment]
@pkozlowski-opensource: thks for taking time to explain me. Much clearer to me now.
