### ISSUE TITLE
Remove concept of Viewport directives?

### ISSUE THREAD

**Issue by tbosch** [angular/angular#1536]
Now that every directive can ask for a `ViewContainer`, can we kill `ViewPort` directives and just decorator directives? 

Some background:
Every directive can now ask for a `ViewContainer` that will insert a `View` next to its element.
`ViewPort` directives just happen to be on a `<template>` element (after normalization).
If we dropped the enforcement that `<template>` elements can't contains `Decorator` directives they could do the same job as `Viewport` directives.

Proposal:

1. Remove `defaultProtoView` from `ViewContainer` and make it direct injectable. With this, `If` and `For` would ask for `ProtoView` and would not work on non `<template>` elements
2. Delete `Viewport` directives and allow `Decorator` directives everywhere.

**Comment by tbosch** [comment]
Mental model:

`<template>` produces a `ProtoView`, i.e. a nested compiled view. This can be used by a directive like `If`, but it might also be used by a component that looks into its shadow dom for configuration (e.g. a table with a configurable header/footer template).

**Comment by mhevery** [comment]
I don't think it is that simple.  

`<div *if></div>`

is short for

```html
<template if>
  <div></div>
</templet>
```

Now the `if` lives on the `<template>`anchor not on the `<div>`.  With `@Decorator` the controller will live on the wrong element.

Also injecting `ViewContainer` is not sufficient. You also need to be able to inject a `ViewFactory` (or `ProtoView`). Currently the `ViewContainer` has the `ProtoView` but I think that is wrong due to:  https://github.com/angular/angular/issues/1492

I think we should discuss this on white board.

**Comment by tbosch** [comment]
This expansion into a `<template>` element is via `*` or a `template` attribute. The directive `if` does not need to have a special type for this.

I am just introducing `ViewManager`, and as a side effect the `ProtoView` will be injectable.

**Comment by mhevery** [comment]
Per discussion with @tbosch, @vsavkin we have agreed to kill it. The way we know that it is a template directive is that it will inject `TemplateRef` which will contain the `ProtoView` and `Context` which will also help with #1492.
