### ISSUE TITLE
Add url property to RouteConfigLoadStart and RouteConfigLoadEnd events

### ISSUE THREAD

**Issue by DzmitryShylovich** [angular/angular#15439]
**I'm submitting a ...**  (check one with "x")
```
[x] feature request
```

**Current behavior**
When we introduced 2 new events for lazy loaded routes (`RouteConfigLoadStart`/`RouteConfigLoadEnd`), we unintentionally introduced a breaking change. These events don't have `url` property, which breaks code like:
```
this.router.events.subscribe((event: Event) => event.url // error, url doesn't exist on type Event)
```

**Expected behavior**
Code like
```
this.router.events.subscribe((event: Event) => event.url)
```
should work without errors so I'm proposing to add `url` property to those events which will always be `null` but won't break typecheking.

@vicb what do you think?

**Comment by vicb** [comment]
I don't really see a point in adding a `null` url.
Wouldn't the user filter the events before subscribing ?

**Comment by DzmitryShylovich** [comment]
> Wouldn't the user filter the events before subscribing ?

usually, but I've already seen 5-6 issues on github/gitter where people don't filter anything. For example, https://github.com/angular/angular/issues/14901#issuecomment-284078392
`url` is the most useful property so would be convenient to be able to access it without any filtering

**Comment by vicb** [comment]
in this one `qs.url.split` would generate a runtime error

**Comment by DzmitryShylovich** [comment]
we will make the type `string|null` so `qs.url.split` will throw in strictNullChecks mode :)

**Comment by laco0416** [comment]
I agree with @vicb. not having the key is definitely different to setting `null`.

**Comment by kgtkr** [comment]
I am in the same situation

**Comment by irfanka** [comment]
We weren't filtering router events (in a pretty sizable app) because all of them had the url property.
Now we have to go back and add filters because the app won't even compile.
It would've been nicer if we didn't have to do that.

**Comment by vicb** [comment]
@irfanka Why would you want to accept all the events (what is your use case) ?

**Comment by dave11mj** [comment]
Hello !

I am glad I found this issue since I was about to report it on the `@angular/cli` issue channel .. I would vote for @DzmitryShylovich suggestion of adding the property `url` to `RouteConfigLoadStart / RouteConfigLoadEnd` .. I just update my project to use Angular 4 with @angular/cli 1.0.0 .. and even tho I am filtering the events for the `NavigationEnd` I still get error on my text editor and Webpack doesn't compile. Below are a couple screenshots to illustrate my specific issue. Along with a hack for anyone experiencing the same problem. ! ^^

#### Code I had before upgrading now with error about RouteConfigLoadStart / crashes on compile
![image](https://cloud.githubusercontent.com/assets/6619371/24317727/c3a2f2dc-10d0-11e7-9b57-84949feb024e.png)

#### Hack to access the url property, works same as it did before but bypasses typing validation
![image](https://cloud.githubusercontent.com/assets/6619371/24317746/00e9ea10-10d1-11e7-8206-20c9365c2e62.png)

Let me know if there is something wrong with my implementation of this issue could be avoided with a change to `@anguar/cli` default typings config files

**Comment by DzmitryShylovich** [comment]
@dave11mj specify the types explicitly. looks like ts can't infer the type which is strange.
```
router.events
  .filter((e: Event) => e instanceof NavigationEnd)
  .map(e: NavigationEnd) => //.test(e.url))
  .do((valid: boolean) => ...)
```

**Comment by irfanka** [comment]
@vicb we weren't​ really interested in all of them - we did in fact 'filter' the events in a way, but not using the RxJS .filter().
Instead, we were subscribing to all events, and then checking​ the event type inside of the  .subscribe() method's callback.

**Comment by dave11mj** [comment]
Thanks ! @DzmitryShylovich being explicit about the type seems to work too ! :D .. strange why it couldn't infer it as before tho. ^^

**Comment by maxruby** [comment]
Same here, our app which works fine with `v2.4`, after upgrading to latest `v4`, throws the `url property does not exist` error and therefore won't even run.

**Comment by puvaasam** [comment]
**Change the return type to any instead of Event**

`router.events.filter((evt: Event) => evt instanceof NavigationEnd).map((ev: any) => ev.url).subscribe(url =>{
          console.log('Router Link End @ ', url);
        });`

**Comment by jrevillas** [comment]
Try casting the event before accessing `url`.

```javascript
this.router.events
      .filter(event => event instanceof NavigationEnd)
      .subscribe(event => this.active = (event as NavigationEnd).url);
```

**Comment by saleemmalikraja** [comment]
@DzmitryShylovich DzmitryShylovich -Try unboxing them according to the type of router event that you choose .

Eg : 

> To access the 'url' property on NavigationStart

 (event as NavigationStart).url 

> To access error message on NavigationError

 (event as NavigationError).error.message

**Comment by atscott** [comment]
Closing as this won't be implemented. There are additional events emitted by the `Router` which also do not have the `url` property so filtering would be necessary regardless. Secondly, at the time of the event, the URL can be retrieved by reading the `Router.getCurrentNavigation()`
