### ISSUE TITLE
[@state]="true|false" should translate to "true" or "1" and "false" or "0"

### ISSUE THREAD

**Issue by matsko** [angular/angular#15433]
It's convenient for state changes to be converted to "true" and "false" if a boolean value is detected. But to support the existing functionality they should also fallback to "1" and "0".

Right now they are converted to "1" and "0", but this poses a problem when `state()` is used since it  used to refer to "true" and "false" back in NG2.

**Comment by emilio-martinez** [comment]
Continuing from #15479, I've represented the outcome of several of these use cases here: http://plnkr.co/edit/12iB5WLvRxl3MkoxOpkk?p=preview.

To echo what @matsko said, converting booleans is particularly convenient because they're commonly used to keep state, e.g., properties like `enabled: boolean`, `hidden: boolean`, and so on. It's a much smoother experience than having to do something like:
```ts
class MyComponent {
   enabled: boolean = true;
   get enabledState() { return this.enabled.toString() };
}
```
On the other hand, while I don't personally think that `1` and `0` should be converted because they're truthy/falsy rather than strictly `true` and `false`, I've also found that they behave unexpectedly; that is also represented in the use cases I show above.

**Comment by matsko** [comment]
Fixed by https://github.com/angular/angular/commit/16c8167886d63f5b4cf03d420478b64640e45654

**Comment by matsko** [comment]
So the way this is works is by comparing strictly against `boolean` typed values. If a boolean is detected then it first checks first for `1` and then `true` when true and `0` and then `false` for when false for both `state()` and `transition(...)` values.
