### ISSUE TITLE
aio: Create better content for the 404 page.

### ISSUE THREAD

**Issue by petebacondarwin** [angular/angular#15518]

**Comment by sjtrimble** [comment]
@petebacondarwin @wardbell I have something in mind that I can implement fairly quickly but would need help with the setup of the page -- I can't tell if it's currently coming from an .md file or from the document service, and it would be great to have the section tagged with the "page-not-found" (or something like that) ID instead of the path the user entered so that it can be styled appropriately.

**Comment by petebacondarwin** [comment]
This has been fixed
