### ISSUE TITLE
5 min quickstart app.es6 error

### ISSUE THREAD

**Issue by bl4de** [angular/angular#1575]
Hi,

In "5 MIN QUICKSTART"  (https://angular.io/docs/js/latest/quickstart.html) app.es6 contains:

```javascript
import {Component, Template, bootstrap} from 'angular2/angular2';

// Annotation section
@Component({
    selector: 'my-app'
})
@View({
    template: '<h1>Hello {{ name }}</h1>'
})
// Component controller
class MyAppComponent {
    constructor() {
        this.name = 'Alice';
    }
}

bootstrap(MyAppComponent);
```

But it's not working (eg. @View annotation isn't included in import section and this code throws an error) -  although change @View annotation to @Template like this:

```javascript
import {Component, Template, bootstrap} from 'angular2/angular2';

// Annotation section
@Component({
    selector: 'my-app'
})
@Template({
    inline: '<h1>Hello {{ name }}</h1>'
})
// Component controller
class MyAppComponent {
    constructor() {
        this.name = 'Alice';
    }
}

bootstrap(MyAppComponent);
```

provides that everything works fine :)

Is it a feature or a bug? :)

**Comment by pkozlowski-opensource** [comment]
@bl4de this is bug in the docs (actually, left-over from renaming). 

Since the quick start is based on alpha.14 we should be using `@Template` instead of `@View`. @naomiblack are we planning to update quick start to the latest alpha?

Concerned file: https://github.com/angular/angular.io/blob/master/public/docs/js/latest/quickstart.jade ?

**Comment by alexeagle** [comment]
The quickstart was replaced by typescript, and includes the renamings. Pls let us know if it's still not working.
