### ISSUE TITLE
RouterTestingModule should provide a way to set up snapshot data

### ISSUE THREAD

**Issue by juliemr** [angular/angular#15779]
Feature Request.

It would be nice to be able to set up route data and snapshots from the `RouterTestingModule`. The motivation here is something like a component which uses the route data in its init:

```ts
@Component({})
class MyComp {
  constructor(private route: ActivatedRoute) {};
  ngOnInit() {
    this.pizza = this.route.snapshot.data['pizza'];
  }
}
```

Currently, this can be tested by adding a provider to the `TestBed` to mock out `ActivatedRoute`, however it feels like something you should be able to do from the `RouterTestingModule`. Perhaps something like:

```ts
TestBed.configureTestingModule({
  imports: [
    RouterTestingModule.withRoutes([{
      path: '', // something to denote that this is the one that should be used?
      data: { pizzaToppings: ['mozzarella', 'onion', 'basil'] },
    }]),
  ],
});
```

cc @vikb, @vikerman

**Comment by vikerman** [comment]
cc @vicb

**Comment by juliemr** [comment]
Oops! Your name prefixes collided in my head :) Sorry about that.

**Comment by juliemr** [comment]
cc @jasonaden

**Comment by vsavkin** [comment]
First, let's define two types of tests we care about:

* Testing application sections (render multiple components, multiple guards). Not quite E2E tests, but similar.
* Testing individual routable components, guards, and resolvers.

## Testing Application Sections

RouterTestingModule solves the first problem fairly well.

```
it('should run tests with a router', fakeAsync(() => {
  @Component({selector: 'routable', template: '{{x | async}}'})
  class RoutableComponent {
    x = this.route.data.map(d => d.x);

    constructor(private route: ActivatedRoute) {
    }
  }

  @Component({selector: 'simple', template: '<router-outlet></router-outlet>'})
  class Container {}

  TestBed.configureTestingModule({
    declarations: [Container, RoutableComponent],
    providers: [
      {provide: SomeResolver, useValue: () => Promise.resolve(100) }
    ],
    imports: [
      RouterTestingModule.withRoutes([
        { path: 'routable', component: RoutableComponent, resolvers: {x: SomeResolver} }
      ])
    ]
  });

  const t = TestBed.createComponent(Container);
  const router: Router = TestBed.get(Router);

  router.navigateByUrl('/');

  tick();

  expect(t.nativeElement.innerHTML).toContain("100");
}));
```

Since the goal of such a test is to test how this component (or a tree of components) in a production-like env, it is hard to make this more concise as it mimic the prod code. One thing we can do away with is the container, but that's about it.


## Unit Testing Components

Where the router doesn't provide a good enough job is in testing individual components, resolvers, and guards. Let's look at a component first.

```
@Component({selector: 'routable', template: '{{x | async}} {{specialMode}}'})
class RoutableComponent {
  x = this.route.data.map(d => d.x);
  specialMode: boolean;

  constructor(private route: ActivatedRoute) {
    if (route.snapshot.url[0].path === 'special') {
      this.specialMode = true;
    }
  }
}
```

Unit testing this component is difficult and requires us to write something like this:

```
it('should run a component in isolation', fakeAsync(() => {
  TestBed.configureTestingModule({
    declarations: [RoutableComponent],
    providers: [
      {provide: ActivatedRoute, useValue: {data: of({x: 100}), snapshot: url: [{path: 'special'}} }
    ]
  });

  const t = TestBed.createComponent(RoutableComponent);
  // ...
}));
```

Creating such test doubles is brittle. It gets harder when we need a route that has children.

It gets even worse when testing resolvers and guards.

```
export SomeResolver implements Resolve<string> {
  constructor(http: Http) {}

  resolve(route: ActivatedRouteSnapshot, state: RouterStateSnapshot): Observable<string> {
    // this.http.
  }
}
```

Creating a test double for RouterStateSnapshot is even more brittle and difficult. This means that, in practice, all routable components, guards, and resolvers are tested in the fashion shown above--too much boilerplate!

If we look closer, we will see that the router is actually testable: ActivatedRouteSnapshot, RouterStateSnapshot, ActivatedRoute, RouterState are immutable data objects. So routable components, guards, and resolver should be trivial to test. The issue is that those routable objects are complex and we do not provide any way to create them in tests. Let's fix it!

Let's introduce 4 helper functions:

```
import {createRouteStateSnapshot, createRouteState, createActivatedRouteSnapshot, createActivatedRoute} from '@angular/router/testing';

const config = { path: 'routable', component: RoutableComponent, resolvers: {x: SomeResolver} };
      
const snapshot = createRouteStateSnapshot(config, '/routable;x=1');
const state = createRouteState(config, '/routable;x=2');
const routeSnapshot = createActivatedRouteSnapshot(config, '/routable;x=3');
const route = createActivatedRoute(config, '/routable;x=4');
```

With these 4 helper functions, writing our tests will get a lot easier:


```
it('should run a component in isolation', fakeAsync(() => {
  TestBed.configureTestingModule({
    declarations: [RoutableComponent],
    providers: [
      {provide: ActivatedRoute, useValue: createActivatedRoute({ path: 'routable', component: RoutableComponent, data: {x: 100} }, '/routable') }
    ]
  });

  const t = TestBed.createComponent(RoutableComponent);
  // ...
}));
```

We can simplify it by making the `component` properly optional, as it is really used.

```
it('should run a component in isolation', fakeAsync(() => {
  TestBed.configureTestingModule({
    declarations: [RoutableComponent],
    providers: [
      {provide: ActivatedRoute, useValue: createActivatedRoute({path: 'routable', data: {x: 100}}, '/routable') }
    ]
  });

  const t = TestBed.createComponent(RoutableComponent);
  // ...
}));
```

Testing resolver is easy now:

```
const s = new SomeResolver(fakeHttp);

const state = createRouteStateSnaphost({path: 'routable', data: {x: 100}, '/routable');
expect(await s.resolve(state.root, state)).toEqual('somevalue');
```

Finally, in addition to these 4 helper function, we need to provide a way to query router state, like this:

```
const state = createRouteStateSnaphost({path: 'routable', data: {x: 100}, '/routable');
state.query({path: 'routable'}); // a list of routes
state.query({component: MyComponent}); // a list of routes
```

## What Did We Achieve?

* It's much easier to unit test routable components
* It's much easier to unit test guards and resolvers
* It's much easier to write isolated tests (without angular)

## Implementation Notes

Router uses three functions: applyRedirects, recognize, and createRouterState. Implement createRouteStateSnapshot... should not be difficult because they will just invoke applyRedirects, recognize, and createRouterState.

**Comment by jasonaden** [comment]
@vsavkin Thanks for the detailed notes here. Overall I think the above is good and will help a lot with router testing.

I had a few comments/questions for now:

* If you look at your first example of the current way of unit testing components, it's quite verbose and you mention it will get worse with child components. Looking at the unit test code after the solution, it's only slightly less verbose. Perhaps there should be an additional helper function that simply ties a component to an ActivatedRoute (and other injectables).
* I would like to see if there's a way this solution could help with testing things such as changing data params and resolved values over time. If that's not part of this issue, we could push it out to another one later.
* In the implementation notes you mention we would run through applyRedirects, recognize, and createRouterState. I'm wondering if that's the right API for a unit test, or if the developer should just be able to pass in the end state and get back a valid RouterStateSnapshot. This way the component can be tested in isolation, separate from router configuration. Thoughts?

**Comment by juliemr** [comment]
Yup, thanks for the writeup!

I'd like if we could fit more of the setup into the RouterTestingModule, instead of the test author separately mocking ActivatedRoute and friends. To me, it feels more natural - it's odd to have this special RouterTestingModule but then still have to do all sorts of manual providing of overrides. 

(Many of these components will need to use the RouterTestingModule for components like routerLink, regardless of where the activated route comes from).

**Comment by vsavkin** [comment]
@jasonaden

>> If you look at your first example of the current way of unit testing components, it's quite verbose and you mention it will get worse with child components. Looking at the unit test code after the solution, it's only slightly less verbose. Perhaps there should be an additional helper function that simply ties a component to an ActivatedRoute (and other injectables).

Yup. It's still a bit verbose, but it's less brittle.

I think what you are suggesting is good and should be looked into, but it's not really a router issue. It's a TestBed issue. Perhaps, TestBed can have a function that combines `configureTestBed` and `createComponent`. Meanwhile, nothing prevent the end user from writing such a function themselves.



>> I would like to see if there's a way this solution could help with testing things such as changing data params and resolved values over time. If that's not part of this issue, we could push it out to another one later.

Good point.


>> In the implementation notes you mention we would run through applyRedirects, recognize, and createRouterState. I'm wondering if that's the right API for a unit test, or if the developer should just be able to pass in the end state and get back a valid RouterStateSnapshot. This way the component can be tested in isolation, separate from router configuration. Thoughts?

I thought about it. The reason why I didn't go that route is that I didn't want the developer to learn two separate APIs: one for writing prod code and one for unit tests. I thought it might be easier for the developer to just grab their existing router config. But I'm happy to explore this option though.

For instance, instead of this:

```
createActivatedRoute({ path: 'routable', data: {x: 100} }, '/routable') }
```

You will have this:


```
createActivatedRoute({
 url: [{path: 'routable'}],
 data: {x: 100},
})
```

**Comment by vsavkin** [comment]
Sorry, it's a long writeup. Hopefully it will clarify some things on how the router-heavy code should be tested.


 

## What are we testing?

It's important to clearly separate the following three things:

* Testing components
* Testing guards/resolvers
* Testing navigations


Individual components don't know what navigation triggered their instantiation. They also don't know what guards and resolvers ran during that navigation. I think it's good. Otherwise, it would be much harder to test those components in isolation. Individual guards/resolvers don't know what navigation invoked them. Once again, it's good because they can be tested in isolation.

Components, guards, and resolvers are units that can be tested in isolation. They are also the units we need to carefully design (for instance, by applying TDD). Such tests don't check if one Guard A returns true, and Resolver B returns 'bob', Component C will render 'Hello Bob'.  They check when Guard A returns true or false. They check when Resolver returns 'bob' and when it throws. 

A router navigation comprises running guards, resolvers, and instantiating components (in the router speak they are called preactivation and activation). It isn't a unit that can be tested without the guards, resolvers, and components involved. It cannot be tested in isolation. The router actually has to run to execute a navigation.


## How are we testing it?

I talked about the two types of tests in the comment above. What can we test with those?

```
                        Components    Guards    Navigations
Integration tests:          x           x           x
Unit tests:                 x           x
```

Integration tests allow us to test everything. We cannot test navigations with unit tests because router navigations aren't code units.

## Example

Say you have a module that looks like this:

```
@NgModule({
  declarations: [MyComponent],
  imports: [
    RouterModule.forChild([{
      path: 'my',
      component: MyComponent,
      canActivate: [PermissionsGuard],
      data: {iam: {prefetch: ['save']}},
      resolve: {
        'one': SomeResolver
      }
    }])
  ],
  providers: [PermissionsGuard, SomeResolver, CurrentUser]
})
class MyModule {}
```

What can be tested here and in what fashion?




### Integration Tests

First, we can write an integration test, like this:

```
@Component({
  selector: 'container',
  template: `<router-outlet></router-outlet>`
})
class Container {}

it('should render MyComponent', fakeAsync(() => {
  const r: Router = TestBed.configureTestBed({
    declarations: [Container],
    imports: [MyModule, RouterTestingModule],
    providers: [
      { provide: CurrentUser, useValue: {role: 'admin'}}
    ]
  }).get(Router);

  const c = TestBed.createComponent(Container);
  tick();

  r.navigateByUrl('/my');
  tick();

  expect(c.nativeElement).toContain('blah');
}));
```

Here we test the whole module--we only mock up the boundaries of the module (CurrentUser and the containing component). There is some boilerplate, but it is trivial to create a helper to remove most of it, like this:

```
function performNavigate(url: string, m: TestModuleMetadata): ComponentFixture<any> {
    @Component({
      selector: 'container',
      template: `<router-outlet></router-outlet>`
    })
    class Container {}

    const r: Router = TestBed.configureTestBed({
      declarations: [...m.declarations, Container],
      imports: [...imports, RouterTestingModule],
      providers: m.providers
    }).get(Router);

    const c = TestBed.createComponent(Container);
    tick();

    r.navigateByUrl(url);
    tick();
    
    return c;
}
```

With this helper in place, we can rewrite our test to look like this:

```
it('should render MyComponent', fakeAsync(() => {
  const c = performNavigate('/my', {
    imports: [MyModule],
    providers: [
      { provide: CurrentUser, useValue: {role: 'admin'}}
    ]
  });

  expect(c.nativeElement).toContain('blah');
}));
```

Note that the helper is generic and application-independent. We can design an application-specific helper that will remove the rest of the boilerplate. As you can see, the result test is concise--hence the router's support for integration tests is good.


### Unit Tests

Where I think the router is lacking is in its support for unit tests. We would like to test PermissionsGuard, SomeResolver, and MyComponent in the unit-test fashion, but it's very difficult due to the fact that we cannot construct state and route objects. And this is what I suggested above.

**Comment by vsavkin** [comment]
@juliemr I thought about it, and I didn't come up with a good way to do it. These are my thoughts:


## From Integration to Isolated

First, let me restate the point above: RouterTestingModule works well for writing integration tests or for testing router navigations. The phrase "integration tests" is extremely overused, so see the comment above, where I define what I mean by it: we actually call `router.navigate`. 

On the other side of the spectrum are isolated tests that might not (and in my opinion should not) use TestBed. It's not very common to test components in this fashion (even though I personally do it), but it is fairly common to test services, resolvers, and guards like that. Because this is a common use case, I think it's a good idea to have an option to write unit tests without using RouterTestingModule.


## One Limitation We Should Keep in Mind

RouterState is a tree of activated routes. We cannot create a tree of components corresponding to that tree of activated routes without actually performing a router navigation (TestBed describes one injector, and we need a tree of injectors to do that). So any time we want to test several components using activated routes at the same time, we have to resort to an integration test. This means that a unit test can only have a single component with an activated route.


## Options

I thought about reusing RouterTestingModule for unit tests, but I find it difficult for two reasons.

Say I have something like this:

```
TestBed.configureTestBed({
  declarations: [ComponentA, ComponentB],
  imports: [
    RouterTestingModule.withRoutesInAUnitTestFashion('/child', [ // I need to provision the URL here as we do not actually navigate anywhere and this is the only place to pass params
      {path: '', component: ComponentA, children: [
        path: 'child', component: ComponentB
      ]}
    ])
  ]
})

const a = TestBed.createComponent(ComponentA); // this doesn't actually create ComponentB
const b = TestBed.createComponent(ComponentB); // this gets the activated route for ComponentA
```

As I mentioned above, without actually navigating we can only create a single activated route. This is confusing the moment you have a router configuration with children.

I think it is clearer that you are just providing a single ActivatedRoute if you do it like this:

```
TestBed.configureTestBed({
  declarations: [ComponentA, ComponentB],
  imports: [RouterModule], // imports directive
  providers: [
    {
      provide: ActivatedRoute,
      useValue: createActivatedRoute('/child', [{path: '', children: [ path: 'child' ]}])
    }
  ]
})

const a = TestBed.createComponent(ComponentA);
```

Because createActivatedRoute is clearly a test helper creating an activated route object, there is no assumption that it will somehow instantiate ComponentB or will pass the right activated route to ComponentB. Also, because it is a test helper, we can make its schema more permissive. For instance, we don't need to pass components, so ComponentB doesn't even have to be provisioned.


We can, of course, do the same like this:

```
TestBed.configureTestBed({
  declarations: [ComponentA]
  imports: [
    RouterTestingModule.withActivatedRoute('/child', [{path: '', children: [ path: 'child' ]}])
  ]
})

const a = TestBed.createComponent(ComponentA);
```

I thought about it, but I find one thing about it problematic. Since RouterTestingModule is built for integration tests, it creates a real router. This means that when the component calls `router.navigate`, the router will try to navigate there. This means that the router configuration must support the target URL, which makes it harder to test components in isolation.

## Summary

* It's hard to reuse RouterTestingModule in unit tests, which don't call `router.navigation`. RouterTestingModule creates a router object and creates a tree of activated routes.

* I think it is clear that integration tests (that actually perform real router navigations) have some boilerplate. It's easy for the developer to write a helper to get rid of it (see the example in the comment above).  Maybe in addition to making unit tests simpler, we can provide a helper to make integration tests simpler (similar to the one I defined in the comment above)?

**Comment by juliemr** [comment]
I agree that having the functionality for unit tests is nice. Our problem is that we have integration tests that still need to mock out the ActivatedRoute. I think that having to do _both_ is confusing. 

The thing we're trying to test would be a large component which injects an activatedRoute and contains things like routerLinks and possibly routerOutlets for child routes inside it.

**Comment by vsavkin** [comment]
@juliemr  I agree. The developer should never do both at the same time.

## createActivatedRoute is required?

Since we should provide a way for folks to write isolated tests not using TestBed (very common for services, guards, etc), having something like `createActivatedRoute` seems required. This is a low-level primitive that is useful by itself, and can be used by the app developer to build more sophisticated test utilities. Right?

## Question

The question is could we do something on top of it to simplify testing of large components with router directives.

### Manual Mocking

This is what you will have to do right now:

```
TestBed.configureTestBed({
  declarations: [ComponentA],
  schemas: [NO_ERRORS_SCHEMA], // ignore routerLink and routerOutlet
  providers: [
    {
      provide: ActivatedRoute,
      useValue: createActivatedRoute('/child', [{path: '', children: [ path: 'child' ]}])
    }
  ]
})
const a = TestBed.createComponent(ComponentA);
```

And if the component inject the router, something like this: 

```
TestBed.configureTestBed({
  declarations: [ComponentA],
  schemas: [NO_ERRORS_SCHEMA], // ignore routerLink and routerOutlet
  providers: [
    {
      provide: ActivatedRoute,
      useValue: createActivatedRoute('/child', [{path: '', children: [ path: 'child' ]}])
    },
    {
      provider: Router,
      useValue: jasmine.createSpyObj('router', ['navigate'])
    }
  ]
})
const a = TestBed.createComponent(ComponentA);
```

The upside of this is that it is direct.

### Mocking Router 

We have have some sort of `RouterTestingModule.unitTest()` which will add the directives and will add will add an implementation of the router with mocked up `navigate`.

```
TestBed.configureTestBed({
  declarations: [ComponentA],
  imports: [RouterTestingModule.unitTest()],
  providers: [
    {
      provide: ActivatedRoute,
      useValue: createActivatedRoute('/child', [{path: '', children: [ path: 'child' ]}])
    }
  ]
})
const a = TestBed.createComponent(ComponentA);
```

You can even provide a syntax sugar, like this:

```
TestBed.configureTestBed({
  declarations: [ComponentA],
  imports: [RouterTestingModule.unitTest({url: '/child', activatedRoute: [{path: '', children: [ path: 'child' ]}])]
})
const a = TestBed.createComponent(ComponentA);
```

This works. The downside is that it may not be clear that `RouterTestingModule.unitTest` a test double router instead of a real router. And doesn't really execute a navigation.

**Comment by blacksonic** [comment]
Any update on this?

**Comment by LayZeeDK** [comment]
Until we figure out the appropriate scope for this update to the `RouterTestingModule`, consider using [Spectator's routing API](https://github.com/ngneat/spectator#testing-with-routing) for shallow routed component tests.

**Comment by LayZeeDK** [comment]
The original proposal is already in the `RouterTestingModule`.

```
TestBed.configureTestingModule({
  imports: [
    RouterTestingModule.withRoutes([{
      path: '', // something to denote that this is the one that should be used?
      data: { pizzaToppings: ['mozzarella', 'onion', 'basil'] },
    }]),
  ],
});
```

**Comment by LayZeeDK** [comment]
Given this example component:

```typescript
import { Component, OnInit } from '@angular/core';
import { ActivatedRoute } from '@angular/router';

@Component({
  template: `
    {{pizzaToppings}}
  `,
})
export class PizzaToppingsComponent implements OnInit {
  pizzaToppings: string;

  constructor(private route: ActivatedRoute) { };

  ngOnInit() {
    this.pizzaToppings =
      (this.route.snapshot.data.pizzaToppings as string[]).join(', ');
  }
}
```

There are two component testing approaches with the current API.

#<span></span>1 Root component fixture with routing, real `ActivatedRoute`, but fake route data

```typescript
import { Component } from '@angular/core';
import {
  ComponentFixture,
  fakeAsync,
  TestBed,
  tick,
} from '@angular/core/testing';
import { Router } from '@angular/router';
import { RouterTestingModule } from '@angular/router/testing';

import { PizzaToppingsComponent } from './my.component';

@Component({
  template: '<router-outlet></router-outlet>',
})
class TestRootComponent { }

describe('PizzaToppingsComponent', () => {
  beforeEach(async () => {
    const fakeRouteData = {
      pizzaToppings: ['mozzarella', 'onion', 'basil'],
    };

    TestBed.configureTestingModule({
      declarations: [
        TestRootComponent,
        PizzaToppingsComponent,
      ],
      imports: [
        RouterTestingModule.withRoutes([
          {
            path: '',
            component: PizzaToppingsComponent,
            data: fakeRouteData,
          },
        ]),
      ],
    });

    await TestBed.compileComponents();

    rootFixture = TestBed.createComponent(TestRootComponent);
  });

  beforeEach(fakeAsync(() => {
    const router = TestBed.inject(Router);

    rootFixture.ngZone.run(() => router.initialNavigation());

    tick();
    rootFixture.detectChanges();
  }));

  let rootFixture: ComponentFixture<TestRootComponent>;

  it('lists pizza toppings', () => {
    expect(rootFixture.nativeElement.textContent)
      .toContain('mozzarella, onion, basil');
  });
});
```

#<span></span>2 Component fixture with fake `ActivatedRoute`

```typescript
import { ComponentFixture, TestBed } from '@angular/core/testing';
import { ActivatedRoute } from '@angular/router';

import { PizzaToppingsComponent } from './my.component';

describe('PizzaToppingsComponent', () => {
  beforeEach(async () => {
    const fakeRoute = {
      snapshot: {
        data: {
          pizzaToppings: ['mozzarella', 'onion', 'basil'],
        },
      },
    };

    TestBed.configureTestingModule({
      declarations: [
        PizzaToppingsComponent,
      ],
      providers: [
        {
          provide: ActivatedRoute,
          useValue: fakeRoute,
        },
      ],
    });

    await TestBed.compileComponents();

    fixture = TestBed.createComponent(PizzaToppingsComponent);
    fixture.detectChanges();
  });

  let fixture: ComponentFixture<PizzaToppingsComponent>;

  it('lists pizza toppings', () => {
    expect(fixture.nativeElement.textContent)
      .toContain('mozzarella, onion, basil');
  });
});
```

**Comment by LayZeeDK** [comment]
The thing is: We could make it easier to fake route snapshot data, but this is a very narrow scope.

Other than route data, an `ActivatedRouteSnapshot` also has:
* Route config
* URL
* Route parameters
* Query parameters
* Query fragment
* Outlet name
* Activated component type
* Root route snapshot
* Parent route snapshot
* First child route snapshot
* Child route snapshots
* Every route snapshot from the root to this component
* Route parameter map
* Query parameter map

This is just the public API.

**Comment by atscott** [comment]
From what I understand and have seen, a vast majority of the unit testing tasks that require mocking the `ActivatedRoute` are to mock out the `data`, `queryParams`, and/or `params` observables. For these cases, it seems solving the [Allow Route Params to be Passed into Component @Inputs](https://github.com/angular/angular/issues/18967) feature request would make mocking that information obsolete. You would no longer have to inject `ActivatedRoute` at all because the `Router`/`RouterOutlet` would bind that information directly to the component inputs and the components could then be tested in the same way as all other components with inputs.

There are a _much_ smaller set of tests that create `ActivatedRoute` mocks to get access to other information in the interface, as listed in https://github.com/angular/angular/issues/15779#issuecomment-640273077. I don't feel these other properties should be mocked at all. If they're needed, the test should set up the `RouterTestingModule` with the correct routes and perform the navigations to get a real `ActivatedRoute` state. That said, there could be some published helper function to reduce the boilerplate needed to navigate within a test, for example:

```
@Injectable({providedIn: 'root'})
class RootFixtureService {
  fixture?: ComponentFixture<{}>;
}

@Component({
  standalone: true,
  template: '<router-outlet></router-outlet>',
  imports: [RouterOutlet],
})
class RootCmp {}

async function navigateForTest(url: string): Promise<{hostFixture: ComponentFixture<{}>, routedElement: DebugElement}> {
  
  const x = TestBed.inject(RootFixtureService);
  if (!x.fixture) {
   x.fixture = TestBed.createComponent(RootCmp);
  }
  const rootFixture = x.fixture;
  const router = TestBed.inject(Router);
  await router.navigateByUrl(url);
  const outlet = rootFixture.debugElement.query(By.directive(RouterOutlet)) as any as RouterOutlet;
  const el =  rootFixture.debugElement.query(By.directive(outlet.activatedRoute.component!))!;
  return {hostFixture: rootFixture, routedElement: el};
}
```

All that said, I don't think providing a way to mock `ActivatedRoute`/`ActivatedRouteSnapshot` is the right thing to do. Thoughts?
