### ISSUE TITLE
[Bug] Data is keep binded to the original variable inside the function also.

### ISSUE THREAD

**Issue by oztek22** [angular/angular#15843]
**I'm submitting a ...**  (check one with "x")
```
[. ] bug report 
```

**Current behavior**

I'm calling a function to replicate the data inside *ngFor loop like below.
`<li (click)="replicateTicket(data);">&nbsp; Replicate</li>`
Inside the function I'm updating name and Id of variable and  pushing it inside the array. (In given example I'm not pushing the data to explain the behavior more vividly.
```
replicateTicket(data:any){
          data.name = data.name + ' (Replicated)';
          console.log(this.ticketList[this.ticketList.length-1].id);
          data.id = 0;
          console.log(this.ticketList[this.ticketList.length-1].id);
}
```

**Expected behavior**

If id of original data is 5 than it should not change to 0.

**Minimal reproduction of the problem with instructions**

1. Run [plunker](https://plnkr.co/edit/HY8m6yuB6X5Wo1C9HlZV?p=preview)
2. click on 458 abc.
3. It should only update the new data and not the current one.

**What is the motivation / use case for changing the behavior?**

I want to replicate data and update new data without affecting the original data.

**Please tell us about your environment:**

windows 10

* **Angular version:** 2.4.10

* **Browser:** [all ]

 
* **Language:** [TypeScript 2.0.10 |  ES5]

**Comment by pkozlowski-opensource** [comment]
You need to fill in the "Minimal reproduction of the problem with instructions" part when opening new issues (well, the entire issue template really). Otherwise an issue like this is hardly actionable.

**Comment by oztek22** [comment]
I have updated the issue.

**Comment by Deltatiger** [comment]
@oztek22 This behavior is due to JS passing around data as references. In JavaScript everything is a reference (Just like in Java). So the for loop takes the reference to a value in the list and passes it to the handler function. You change the reference so the original is actually changed.

Now you are pushing the reference back in to the list which means you have two copies of the same object in the list. Hence you are getting a display of two same items.

Solution: Create copies before pushing it into the list. Change values in the copies if you do not want to mess with the original.

This is how JS behaves and it is not related to Angular ( AFAIK )

**Comment by oztek22** [comment]
I didn't check  the facts before asking the question. Sorry for  the inconvenience caused by this.
I guess You may close this bug now.
