### ISSUE TITLE
Testing - Async object not exists

### ISSUE THREAD

**Issue by nischi** [angular/angular#15889]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
I try to test a Service with a Http Request and an Observable. Try to test the length of an array in the Object from the Observable. But if the Array do not exsit the test will pass in any case, but should fail. See reproduction.

**Expected behavior**
If i test a length of an array which not existing should the test fail.
expect(myobject.array.length).toBe(20);

**Minimal reproduction of the problem with instructions**
`import ...
describe('...
  let service: myService;
  beforeEach(inject([myService], (service: myService) => {
    this.service = service;
  }));
  it('load one page with 10 entries', async(() => {
    this.service.load(1,10);
    this.service.myObservableFromHttp.subscribe((myObject: Object) => {
        expect(myObject.arraylength).toBe(10);
    });
  }));
.....`

**What is the motivation / use case for changing the behavior?**
I think an test to a number on an undefined Object should fail because its not a number.

**Please tell us about your environment:**

Windows 10,
Visual Studio Code,
Angular CLI
.NET Core REST Service

* **Angular version:** 2.0.X
Angular ^4.0.0
Jasmin ~2.5.2
Karma-Jasmin ~1.1.0

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]
All
 
* **Language:** [all | TypeScript X.X | ES6/7 | ES5]
TypeScript 2.2.1

* **Node (for AoT issues):** `node --version` =

**Comment by Toxicable** [comment]
Please make a  reproduction in plunkr, here's a template: http://plnkr.co/edit/Oqc2xFpd168zTSqx9dVf?p=preview

**Comment by nischi** [comment]
http://plnkr.co/edit/aStSgc
In this Plunkr it works like expected, but if i copy the code 1:1 in my angular application testing it wors as described above.

**Comment by tbosch** [comment]
@nischi could you then create a branch on Github to reproduce with a minimal application? Sorry, but without reproduction it's hard to look into this...

**Comment by nischi** [comment]
Here you have a reproducable version: https://github.com/nischi/angular-testing

I have only done following:

`ng new angular-testing`

Then add the "Observable Test"-Test to the app.component.spec.ts

I expect that jasmine say obj.data is not existing, because it's not existing (console.log). But they say the test is successfull.

**Comment by trotyl** [comment]
It's about **throwing in the subscribe() callback** without triggering expect(), not quote relevant to what the length is.

I have tried **upgrade rxjs version to 5.3.0 in your plunker**, like: http://plnkr.co/edit/pJjD6F?p=preview , it would **have the same problem**. The initial emerging of this problem can be determined to 5.0.3(right) -> 5.1.0(wrong).

So there is no difference between Angular CLI and plunker environments.

Even more, this problem still **exists after remove async() helper and Angular TestBed setup**, like: http://plnkr.co/edit/mCxS42?p=preview . So it **may not be a problem at Angular side**, seemingly it's just that rxjs breaks the compatibility of jasmine after 5.1.0 version.

I'm not sure what it is since rxjs and jasmine re-scheduled everything, it's hard to debug. I guess it is wise to remove the Angular part and raise it to rxjs or jamine?

**Comment by nischi** [comment]
Thanks for had a look. Whats the normal case, do you report that to rxjs or jasmine, because thats component you use in angular / angular cli. Or where should i report this problem?

**Comment by trotyl** [comment]
That's why minimal reproduction is required, if the minimal reproduction of a problem contains nothing of angular, how could it still be an angular issue? And what could angular team do for it?

But I thinks it's right to contact the direct vendor first if not sure what the problem is.

**Comment by nischi** [comment]
https://github.com/ReactiveX/rxjs/issues/2564
