### ISSUE TITLE
RedirectTo with auxiliary router gives an error

### ISSUE THREAD

**Issue by WiseBird** [angular/angular#15896]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```
 
**Current behavior**

Error `Only absolute redirects can have named outlets` is thrown when using aux router in `redirectTo`.

**Expected behavior**

Should navigate to used router

**Minimal reproduction of the problem with instructions**

https://plnkr.co/edit/vMezYa4A4n3l5USAvwKj?p=preview

**What is the motivation / use case for changing the behavior?**

Desire to have one specific router to be selected by default.

* **Angular version:** 4.0.1

* **Browser:** Chrome 57
 
* **Language:** TS 2.2.2

**Comment by skreborn** [comment]
Changing the `redirectTo` to `'/component-one(sidebar:component-aux)'` - [as per the docs](https://angular.io/docs/ts/latest/guide/router.html#!#secondary-route-navigation) - solves the issue for me. [Here's an updated plunker](https://plnkr.co/edit/Wj30vdrgynWysnBarPkm?p=preview). The route also needs to be absolute (start with a slash), like the error says.

**Comment by WiseBird** [comment]
Shame on me. Thank you.

**Comment by simeyla** [comment]
Your plunkr just says 'Hello world' so I can't put your actual code.

I had a similar problem but my parent route has an id - and redirecting to `/component-one/:id/(sidebar:component-aux)` isn't going to work because the child route doesn't have `:id` in context.

So my redirect in the parent had to become this to redirect immediately to the child while retaining the ID.

    { path: ':id', pathMatch: 'full', redirectTo: '/orders/:id/(detail:summary)' },

See full config here : https://stackoverflow.com/a/50382197/16940
