### ISSUE TITLE
Add task tracking to NgZone when Protractor is driving the page

### ISSUE THREAD

**Issue by juliemr** [angular/angular#15917]
We'd like to be able to give users good information if an end to end test times out (or if `Testability#whenStable` times out for any reason). Since we're using Zone.js, we can track tasks and output things that are still pending.

Zone.js already has a ZoneSpec for tracking tasks:  https://github.com/angular/zone.js/blob/master/lib/zone-spec/task-tracking.ts

Our proposal is to include that ZoneSpec in the default zone polyfills. If the test is being run via Protractor (e.g. has the NG_DEFER_BOOTSTRAP window name flag) Angular bootstrap will fork a tracking zone, and then for NgZone as a child of the tracking zone. We will need to modify the `whenStable` method to accept a timeout, so that it can check the tracking zone and return the useful information if the timeout is exceeded.

During this change, we should we should introduce a system for controlling which ZoneSpecs should be loaded in general during bootstrap (so that users could turn off LongStackTraces, for example).

(See https://github.com/angular/angular.js/issues/15585 for similar concerns in AngularJS).

cc @mgiambalvo

**Comment by jessicajaniuk** [comment]
Thanks for reporting this issue. This issue is now obsolete due to changes in the recent releases. Please update to the most recent Angular version.

If the problem still exists in your application, please [open a new issue](https://github.com/angular/angular/issues/new/choose) and follow the instructions in the issue template.
