### ISSUE TITLE
bug(animations): 'transform' not triggering with @HostBinding 

### ISSUE THREAD

**Issue by fknop** [angular/angular#15924]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**

When using a trigger with `@HostBinding`, the animations for the `transform` CSS property are not triggered.

**Expected behavior**

The transform animations should work on the host element.

**Minimal reproduction of the problem with instructions**

Simple reproduction of the bug: http://plnkr.co/edit/bMjxVZr77LDn4wl1Jyx7?p=preview

I added a 1second transition with a trigger on a div and a trigger on the host element.
You can see that the opacity transition is applied, but not the `translateY`. 

This is really a problem for the leave animations as it's not triggering with the trigger on the div element. 

My current workaround is to pass the condition of the `ngIf` as an `@Input` and apply this condition on the div inside the component.

* **Angular version:** 4.0.1

* **Browser:** [Chrome (latest) | Firefox (latest) ]

* **Language:** [TypeScript]

**Comment by matsko** [comment]
Because components in Angular are rendered as custom HTML elements, they, by default, have a display styling of `inline`. This means that transform won't work on them, unless they have `block`. Since a `host` binding is placed on the component element, the animation styling is applied on that element and, in the case of the `transform` style, it won't animate as expected.

Just add `styles: [':host { display: block }`]` to the component definition:
http://plnkr.co/edit/YJK1ss7q3IScCImjSExY?p=preview
