### ISSUE TITLE
Conversion from Response's ArrayBuffer to String

### ISSUE THREAD

**Issue by williamAlhant** [angular/angular#15932]
This concerns the text() method in angular/packages/http/src/body.ts

body.text() , when body is an instance of ArrayBuffer, does the following conversion : 
`String.fromCharCode.apply(null, new Uint16Array(<ArrayBuffer>this._body))`

Shouldn't it be Uint8 instead of Uint16 ? In my case, Uint8 gives the expected result while Uint16 returns a string of Chinese characters. Maybe this conversion assumes the string is UTF-16 encoded while my string was UTF-8/ASCII encoded, could that be the reason ?

**Comment by alxhub** [comment]
So, Angular's behavior here is arguably broken.

We handle neither UTF-16 nor UTF-8 for this conversion. Currently we (inadvertently) interpret the `ArrayBuffer` according to an old standard called UCS-2, which only supports the Basic Multilingual Plane of Unicode. It does overlap with UTF-16 for this plane, but we will do the wrong thing for surrogate pairs in UTF-16.

`Uint8Array`, btw, would interpret each byte as a separate character code in JS, which would essentially be ISO-8859 decoding. Critically this would _not_ be UTF-8 support - that would require decoding of multi-byte characters.

The fix I'm implementing is to add an optional `charsetHint` parameter to `Body.text()`. The default value will be `legacy` in order to not break the behavior today. `iso-8859` will be the other option, which will use `Uint8Array` for the conversion.
