### ISSUE TITLE
Language Service plugin does not respect `baseUrl` compiler options.

### ISSUE THREAD

**Issue by chuckjaz** [angular/angular#15974]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report
```

**Current behavior**

Using `baseUrl` will result in diagnostic error messages if `baseUrl` relative imports are used in metadata.

**Expected behavior**

No diagnostics.

**Minimal reproduction of the problem with instructions**

See https://github.com/angular/vscode-ng-language-service/issues/72

**Comment by asmolenic** [comment]
@chuckjaz Any ETA on when this fix will land in the  [ Visual Studio Code extension](https://marketplace.visualstudio.com/items?itemName=Angular.ng-template) ? It has been almost 2 months since this fix and I've been checking daily for updates on it with no luck. Maybe I'm missing the obvious and the language service has another usage now (without using that extension) ?

Thanks!

**Comment by chuckjaz** [comment]
I will land this later this week or early next week.

I was waiting on delivering this with the new architecture but it has been dragging on a bit so I will land this one early if necessary.

**Comment by DBosley** [comment]
@chuckjaz Thanks Chuck! Much Appriciated!
