### ISSUE TITLE
Revert only-element-selector restraint on Component selectors

### ISSUE THREAD

**Issue by jelbourn** [angular/angular#1602]
Use case: for `MdButton`, there are actually two components, `MdButton` and `MdAnchor`. They are differentiated as
`[md-button]:not([href])` and
`[md-button][href]`

Using only an element selector doesn't work for this.

**Comment by tbosch** [comment]
Not blocking GT today (just double checked), but might in the future.

**Comment by jbdeboer** [comment]
It is not blocking GT. I have also found that attribute selectors for components cause a lot of confusion and should be avoided.

e.g. We have a component ```g-button[button-style=action]``` and developers are confused when <g-button button-style={{expression}}></g-select> does not work. (I realize that particular syntax is deprecated in A2, but the point stands)

**Comment by DannyMeister** [comment]
When fixed, will it follow reasonable selector specificity rules if there are potential collisions?  For example, I would like to have a generic component for fields with a selector of `field` and more specialized components for some of them such as `field[type=boolean]`.  Given the host element `<field type="boolean">` both selectors would evaluate to true, but the second is the desired.

If selectors have to be mutually exclusive, it forces (at the very least) the more generic component to know about all the others, causing deployment of a new component to require code modifications outside of itself.  Not allowing this in order to help avoid collisions comes at the cost of extensibility (my components will have to remain open for modification).

**Comment by DannyMeister** [comment]
I've switched tactics from Component selectors to using DynamicComponentLoader to try to overcome the limitations with selectors.  That however, has been running into its own set of roadblocks, such as #1236
