### ISSUE TITLE
aio: flaky test failure detection

### ISSUE THREAD

**Issue by chuckjaz** [angular/angular#16058]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
```

**Current behavior**

The aio test report errors but only sometimes report the failure to CI.

Consider: https://travis-ci.org/angular/angular/jobs/222869060
And: https://travis-ci.org/angular/angular/jobs/222850246

They both show the same error messages in the log but the first reported success and the second reported failure.

**Expected behavior**

The test to always fail or always succeed.

**Minimal reproduction of the problem with instructions**

See the links above. The reporting is flaky.

**Comment by gkalpak** [comment]
@chuckjaz, what errors are you talking about? The failing build fails because of an error (which seems like a flake, but I haven't seen it before). I don't see the same error in the passing build (s passing is expected).

Are you talking about the "errors" produced by the `dgeni ./tools/transforms/angular.io-package` command (such as [this][1])? These are kind of expected (for the time being) and are not supposed to mke the build fail (so this part seems to work as expected atm).

[1]: https://travis-ci.org/angular/angular/jobs/222850246#L1361

**Comment by chuckjaz** [comment]
@gkalpak Ah, I missed the connection refused in the wall of red.
