### ISSUE TITLE
Should be able to load templateUrls in unit tests

### ISSUE THREAD

**Issue by juliemr** [angular/angular#1610]
Need something analogous to karma-ng-html2js-preprocessor for Angular1, which allows components using `templateUrl` to load their template for unit testing.

**Comment by jbdeboer** [comment]
We need this feature as well, since all of our components use templateUrl and we want to unit test them.

**Comment by matanlurey** [comment]
I implemented this internally by creating a Map<String, String> (templateUrl: HTML) via a build process, and using that with the test bed and a custom `TemplateLoader`. Angular may consider providing this out of the box.

**Comment by matthewjh** [comment]
It would be nice if there was a solution to this that didn't involve a build step, e.g.

````javascript
mockXhr.when('templates/(.*?).html').passThroughTo('base/templates/$1.html');
````

Then I could add `templates/**/*.html` to my karma.conf so that these files are served.

**Comment by naomiblack** [comment]
GT concur ok to push this out a week.

**Comment by vicb** [comment]
Note that this will probably be fixed via #2593

**Comment by naomiblack** [comment]
@juliemr @vicb could you update this issue with status? I've just slipped it to alpha-30.

**Comment by juliemr** [comment]
No update from me.

**Comment by juliemr** [comment]
@naomiblack Neither @vicb nor I have time to deal with this in the alpha-30 timeframe, due to vacations 'n' holidays. Vic's adding some context comments. Any chance we can find another owner?

**Comment by naomiblack** [comment]
Assigning to @sjelin. Need to find someone to pair with him on it as this is new angular 2 territory for him.

**Comment by matanlurey** [comment]
GT is no longer blocked on this, as we are using the Dart transformer. /unsub

**Comment by sjelin** [comment]
No progress yet.  I'll do this this week.

**Comment by sjelin** [comment]
I should hopefully have a version of this working by EOD (meaning midnight, not 5 PM), and on npm soon after

**Comment by jelbourn** [comment]
@sjelin any updates on this?

**Comment by jeffbcross** [comment]
@sjelin I moved this to alpha 35, but please remove or move the milestone if it won't land by this Wednesday.

**Comment by sjelin** [comment]
Hey, sorry.  My original approach didn't work at all & I haven't been able to make the meeting.  Anyway, I have something working here:

https://github.com/sjelin/karma-redirect-preprocessor

The API is essentially the same as karma-ng-html2js-preprocessor's ([example here](https://github.com/sjelin/karma-redirect-preprocessor/blob/master/test/e2e/karma.conf.js), documentation pending), but behind the scenes it works totally differently.  Caching the templates client side isn't feasible without an API like `$templateCache`.  Instead, the idea here is to make karma serve the templates at the same URLs that would be used in production.  This way they can be retrieved by Angular through AJAX like normal.  (Not sure how clear I'm being, it's 3 AM...)

If this makes sense to everyone I'll clean it up and throw it on NPM as soon as I can (I'm busy until Wednesday at 2 PM though).  Otherwise I think the only solution is to implement something like `$templateCache` for Angular2.

**Comment by sjelin** [comment]
I didn't get any feedback so I just went ahead an published to NPM: https://www.npmjs.com/package/karma-redirect-preprocessor

Let me know if this solves everyone's problems or I need to go do something else.

**Comment by jbdeboer** [comment]
Per @matanlurey 's July 1 comment, this is no longer an issue for GT. I removed it from the GT hotlist.

**Comment by tbosch** [comment]
Note that we are planning on precompiling templates, see https://github.com/angular/angular/issues/3605. We probably want to store the templates in this form...

**Comment by sjelin** [comment]
I think it should still work in that case.  If the templates are inline (as in the design doc example), this plugin is unnecessary.  If they're retrieved by AJAX, this plugin will allow the AJAX to work regardless of how the template is formatted.

I'm going to close this issue since I think it solves the problem and there don't seem to be any internal users to ask about it.  @zzo, can you update `karma-ng-html2js-preprocessor` telling them to use `karma-redirect-preprocessor` in angular2?

**Comment by zzo** [comment]
done.

**Comment by jelbourn** [comment]
@sjelin After trying this out today, I found that it's not the most idea solution for the angular2 codebase, at least. Similar to angular 1, angular2 uses a mock XHR implementation when running unit tests, so there aren't any real HTTP requests made for karma to handle. 

It's seeming more and more that we should have a tool that inlines template contents into the component's JS as some build step (i.e., `templateUrl` > `template` in the `@View` block). Dart already has something like this with the dart transformers.

**Comment by ludohenin** [comment]
I have this one working if you're interested in gulp tool to do that [https://github.com/ludohenin/gulp-inline-ng2-template](https://github.com/ludohenin/gulp-inline-ng2-template)

**Comment by tbosch** [comment]
I think we should precompile templates for unit tests as well. This way,
all templates and also styles will be loaded offline on the server and then
converted into a format that Angular already understands. See
https://github.com/angular/angular/pull/3165
