### ISSUE TITLE
Ban H1 elements (or single #) in document content

### ISSUE THREAD

**Issue by IgorMinar** [angular/angular#16193]
Some documents like [animation.md - see the "Contents" header](https://github.com/angular/angular/blob/800b1b060edfc05fde2172121a163a2e1c868ae2/aio/content/guide/animations.md) contain H1 headers which mess up UI and in the future also TOC generation.

It would be great to catch these errors in dgeni and fail a build if such errors are introduced.

**Comment by petebacondarwin** [comment]
It's a bit more tricky than that because we actually do want up to one h1 in a document. This is then used for the `title` property, which prevents the need for the `@title` tag in most cases. It also is crucial for supporting special cases like the home page and the 404 page.

For sure we could complain if there was more than one h1; and even if the title had been provided and there was also a h1.

**Comment by IgorMinar** [comment]
> For sure we could complain if there was more than one h1; and even if the title had been provided and there was also a h1.

that would be sufficient.

**Comment by wardbell** [comment]
FWIW, Animations no longer has multiple H1s
