### ISSUE TITLE
Problem with simple string attributes on downgraded component when `ng-if` is used

### ISSUE THREAD

**Issue by th0r** [angular/angular#16212]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**

Let's say you have ng1+ng4 application with `<test/>` component written in ng4 and downgraded to ng1.

This component has some string `input` binding so there are a few ways to pass a value there:
1. `<test input="value"/>`
2. `<test [input]="'value'"/>`

The thing is if you use `ng-if` either on this component or on any of it's parents and use first way to pass an `input` value (using simple string attribute) it will be `undefined` on the call to `ngOnInit` or on the first call to `ngOnChanges`. It will be set only on the second call to `ngOnChanges`.

But in the second case of `[input]` binding everything works as expected.

See reproduction: http://plnkr.co/edit/qpZwej5dypPblBafnCVp?p=preview

**Expected behavior**

`input` value should be set before the call to `ngOnInit` and first call to `ngOnChanges`.

**Minimal reproduction of the problem with instructions**

Reproduction: http://plnkr.co/edit/qpZwej5dypPblBafnCVp?p=preview

Open browser console and you'll see input values for different cases in different component lifecycle hooks.

Press `Toggle visibility` button to print logs again.

You can also remove `ng-if` from the parent `<div>` and see the bug disappears: after page refresh it'll show valid input values in all lifecycle hooks.

**What is the motivation / use case for changing the behavior?**

Current behavior is a bug.

**Please tell us about your environment:**

I think it doesn't depend on environment.

* **Angular version:** 4.0.2

* **Browser:** Tested in Chrome 57

 
* **Language:** TypeScript

* **Node (for AoT issues):** -

**Comment by gkalpak** [comment]
Interesting. I don't think `ngUpgrade` has any special handling for `[xyz]` vs `xys`. Investigating...

**Comment by gkalpak** [comment]
> I don't think `ngUpgrade` has any special handling for `[xyz]` vs `xyz`. 

It turns out it does :smiley: Changes to `xyz` attributes are tracked using `attrs.$observe()` ([here][1]), while `changes to `[xyz]` (which are typically expressions) are tracked using `scope.$watch()` ([there][2]).

Under the hood, `$observe()` calls `$evalAsync()`, which adds callbacks to the `asyncQueue`. These callbacks will be run at the beginning of the next `$digest` iteration.

Note that there is another `$watch`er for running `ngOnChanges` for example. So, when we are already in the middle of a `$digest` (as happens when using `ngIf`), the new `$watch`ers will be executed as part of the current `$digest` iteration, thus before the `asyncQueue` callbacks.

##
This is roughly equivalent to the following:

```ts
scope.$watch(..., () => {
  // The `ngIf` expression changed, let's insert the components...
  ...
  /* 1 */ scope.$evalAsync(/* Initialize the `xyz` attributes */);
  /* 2 */ scope.$watch(..., /* Update the `[xyz]` attributes */);
  /* 3 */ scope.$watch(..., /* Run `ngOnChanges()` */);
});
```

The above callbacks will be executed in the order: `2` -> `3` -> `1` -> `3`

When this all happens outside of a `$digest`, then everythng works as expected, because `asyncQueue` callbacks will be executed before the `$watch`ers on the next `$digest`.

##
Working on a fix...

[1]: https://github.com/angular/angular/blob/71f5b73296708014b740fb5dd0145c0599de7a19/packages/upgrade/src/common/downgrade_component_adapter.ts#L86
[2]: https://github.com/angular/angular/blob/71f5b73296708014b740fb5dd0145c0599de7a19/packages/upgrade/src/common/downgrade_component_adapter.ts#L101
