### ISSUE TITLE
AOT actually increases vendor file size?

### ISSUE THREAD

**Issue by dereklin** [angular/angular#16219]
I am using chance.js http://chancejs.com/

According to their claim: 
![chance-size](https://cloud.githubusercontent.com/assets/2231799/25256341/ed36e198-25e4-11e7-9a7e-d5adfbfc7ce9.PNG)

So it should less than 95KB

After AOT, the size is:
```
chance: 244.18 KB
```
So does AOT actually double (or more) the size of chance.js?

I am using Angular 4.0.2, webpack 2.4.1 using this starter as my base:

https://github.com/AngularClass/angular2-webpack-starter

**Comment by robwormald** [comment]
Using the JiT compiler incurs two costs:
- the several hundred KB of `@angular/compiler` that you have to ship over the wire
- the extra runtime work the compiler has to do before bootstrap.

When you AoT compile, you save on two costs:
- you no longer have to ship the compiler
- there's no runtime work to do to compile

The tradeoff is we're generating new code, so each individual component gets "bigger". You save on the *fixed* cost of the compiler (numbers made up for illustrative purposes)

| # of components | JIT   | AOT   |
|-----------------|-------|-------|
| 1               | 300KB | 100KB |
| 50              | 500KB | 200KB |
| 500             | 5000KB   | 6000KB   |

Nobody should be loading 500 components without lazy loading, but that's the general idea.

None of this has anything to do with third party dependencies - it's likely that what you're seeing is the generated component code added to your bundle, rather than changing the size of a 3rd party dependency.

`source-map-explorer` is useful for seeing whats in your bundles.

**Comment by dereklin** [comment]
@robwormald Thanks for the input.  I was digging around to see if I could do to shrink my build size.  And I saw chance.js being 244 KB while their site saying it was 95 KB.  I just tried a new angular-cli app exploration.  In the end, it turned out that chance.js is really that big: https://github.com/chancejs/chancejs/tree/master/dist

![chance-size](https://cloud.githubusercontent.com/assets/2231799/25260555/00e86032-2602-11e7-976f-430ea0f4ef20.PNG)

ts-xlsx, faker, ag-grid was all more than 1 MB, with other dependencies, my app is really big really fast...
