### ISSUE TITLE
aio: a link to an anchor in a different page problem

### ISSUE THREAD

**Issue by Foxandxss** [angular/angular#16242]
Going to `https://aio-staging.firebaseapp.com/guide/ts-to-js`

Then looking for the `@Input and @Output` link. If you click it, it navigates to a different page but not in the exact spot.

**Comment by petebacondarwin** [comment]
The reason for the problem is that the content is not completely rendered by the time we scroll to the element that matches the fragment. When the extra content is added the scroll position is no longer correct.

A simple workaround is to put a delay in the call to the `AutoScroller`, to ensure that the content has finished rendering before we scroll. But we should look into whether there is a more deterministic solution. From a brief look at the code, it seems that the calls to run the embedded component factories can be asynchronous and do not return a promise. Is this correct? Or is the problem that we are loading up images or something else async?
