### ISSUE TITLE
Router - Clarify params subscription behavior when deactivating a route

### ISSUE THREAD

**Issue by NetanelBasal** [angular/angular#16261]
```
[ x ] bug report
```

**Current behavior**
This is a quote from the official documentation - 

> The subscriptions are cleaned up when the component is destroyed, protecting against memory leaks, so you don't need to unsubscribe from the route params Observable.

The subscription is still active.

**Expected behavior**
Angular should unsubscribe from the params observable when the component destroyed. ( or change the documentation )

**Minimal reproduction of the problem with instructions**
You can test this behavior with the `delay` operator.

```ts
@Component({
 ...
})
export class TestComponent implements OnInit {
  params;
  constructor(private route: ActivatedRoute) { }

  ngOnInit() {
    this.params = this.route.params.delay(3000).subscribe(console.log);
  }
}

```

When navigates to a different route the handler is still running. 

You can verify this by calling explicitly to the `unsubscribe()` method.

```ts
ngOnDestroy() {
  this.params.unsubscribe();
}
```

Now you will see that the handler is not running. 

**Angular version:** 4.0.X

**Comment by mhevery** [comment]
@robwormald Can you comment on how you think this should work?

**Comment by tytskyi** [comment]
@mhevery @robwormald ping

**Comment by sod** [comment]
Plunkr https://plnkr.co/edit/ftZj8PPYV5lovmgpRXAT?p=preview

Seems not to work like documented in 2.0.0, 4.0.0 and 4.2.0. Interesting. I always took that for granted and never unsubscribed from params.

**Comment by ribizli** [comment]
> The `ActivatedRoute` and its observables are insulated from the `Router` itself. The `Router` destroys a routed component when it is no longer needed and the injected `ActivatedRoute` dies with it.

My understanding of this is that the source params/data/etc observables are garbage collected when the component and its injector with the `ActivatedRoute` gets garbage collected. No wording about `unsubscribe` or any cleanup.
It seems, that a delayed `Observable` still holds an active reference for a timeout callback or subscriber (??? I'm not aware about the internals) preventing it from garbage collection. After the timeout fires (or in real scenarios the HTTP returns), the `Observable` dies. Anyway I don't see this as a memory leak, rather just a specific case what should be handled manually.
But true, this should be well documented, since some HTTP call should be also cancelled to prevent from some side effects and save some resources.

Can someone confirm my assumptions?

**Comment by richarddavenport** [comment]
@sod @NetanelBasal Looking at that plnkr, it looks like only one message is being logged when switching between the XComponent and YComponent. This is with `4.2.0`, can either of you confirm that using that plnkr there is a problem?
![kapture 2017-09-15 at 11 24 13](https://user-images.githubusercontent.com/3596012/30493078-73efa778-9a08-11e7-9fb9-279ce6fbda44.gif)

**Comment by NetanelBasal** [comment]
Yes, there is a problem, when you unsubscribe from the Observable the handler should NOT run.

**Comment by bennadel** [comment]
I just stumbled upon a slightly different problem, kind of opposite. I am seeing very strange routable component destroy/re-create if I _don't include_ the `.delay()` option in the param subscription. But, not in all cases. Trying to get a reproduction.

**Comment by richarddavenport** [comment]
@bennadel are you saying that the component is being destroyed, but then recreated when the params are changed? But it only occurs when you don't include the delay?

**Comment by bennadel** [comment]
@richarddavenport yes, that is correct. As far as I have isolated, it appears to be when I have a synchronous navigation _away from the component_ from within the `paramMap.subscribe()` callback. I suspect that by adding the `.delay(0)`, it provides a ticket between the `paramMap` and my navigation event.

I hope to a working, isolated demo later today.

**Comment by bennadel** [comment]
@richarddavenport sorry, after further digging, it appears my issue has nothing to do with the `ActivatedRoute` at all. There is some race condition if you navigate away from the component *too close* to the `ngOnInit()` call. [I write it up on my blog](https://www.bennadel.com/blog/3361-view-components-may-get-unnecessarily-reinstantiated-under-certain-circumstances-in-angular-4-4-6.htm). Sorry for the distraction :)

**Comment by bennadel** [comment]
Ok, after more noodling, I think my issue _does_ have to do with `ActivatedRoute`, because the behavior can be shown even when I navigate away from a component that has been on the page for a long time.

**Comment by tproenca** [comment]
The router is not unsubscribing for params or queryParams only when I have more than 1 instance of the same component being rendered in the page.

**Comment by LucasFrecia** [comment]
Any update on this issue? 

I had to do a custom fix for this that adds some overhead but got the job done.... check the stack overflow link, I leave it here for anyone who needs a quick efficient fix for this:

https://stackoverflow.com/questions/49159416/url-change-not-firing-in-angular/49159722#49159722

**Comment by m0uneer** [comment]
I'm searching for a while for the best practices of unsubscribing from observable at Angular and I decided to share with you the result of my searches to correct me if I'm wrong. I see that this issue is related and decided to comment here instead of creating a question issue.

**Some of the best practices regarding observables unsubscriptions inside Angular components:**

A qoute from [`Routing & Navigation`](https://angular.io/guide/router)

> When subscribing to an observable in a component, you almost always arrange to unsubscribe when the component is destroyed.
>
> There are a few exceptional observables where this is not necessary. The ActivatedRoute observables are among the exceptions.
>
> The ActivatedRoute and its observables are insulated from the Router itself. The Router destroys a routed component when it is no longer needed and the injected ActivatedRoute dies with it.
>
> Feel free to unsubscribe anyway. It is harmless and never a bad practice.

And in responding to the following links:
- (1) [Should I unsubscribe from Angular 2 Http Observables?](https://www.seangwright.me/blog/development/unsubscribe-angular-2-http-observables/)

- (2) [Is it necessary to unsubscribe from observables created by Http methods?](https://stackoverflow.com/questions/35042929/is-it-necessary-to-unsubscribe-from-observables-created-by-http-methods)
- (3) [RxJS: Don’t Unsubscribe](https://medium.com/@benlesh/rxjs-dont-unsubscribe-6753ed4fda87)
- (4) [The easiest way to unsubscribe from Observables in Angular](https://medium.com/thecodecampus-knowledge/the-easiest-way-to-unsubscribe-from-observables-in-angular-5abde80a5ae3
)
- (5) [Documentation for RxJS Unsubscribing](https://github.com/angular/angular/issues/22410)
- (6) [Unsubscribing in a service is kind of pointless, since there is no chance of memory leaks](https://stackoverflow.com/a/40885304/3100587)

I collected some of the best practices regarding observables unsubscriptions inside Angular components to share with you:
- Never unsubscribe from an `http` observable as it is `finite` and it unsubscribes and cleans itself automatically [(1)](https://www.seangwright.me/blog/development/unsubscribe-angular-2-http-observables/), [(2)](https://stackoverflow.com/questions/35042929/is-it-necessary-to-unsubscribe-from-observables-created-by-http-methods).
- Use `AsyncPipe` as much as possible because it automatically unsubscribe the observable on component `destory`.
- Unsubscribe from the `ActivatedRoute` observables like `route.params` if they are subscribed inside a nested (Added inside tpl with the component selector) or dynamic component as they may be subscribed many times as long as the parent/host component exists. No need to unsubscribe from them in other scenarios as mentioned in the quote above from [`Routing & Navigation`](https://angular.io/guide/router) docs.
- Unsubscribe from global observables shared between components that are exposed through an Angular service for example as they may be subscribed multiple times as long as the component is initialized.
- No need to unsubscribe from service internal observables since an Angular service never get's destroyed, unless your entire application get's destroyed, there is no real reason to unsubscribe from it and there is no chance of memory leaks. [(6)](https://stackoverflow.com/a/40885304/3100587)
- Unsubscribe from every obsevable else as a memory-leak guard step untill Angular Docs explicitly tells us which observables are unneccisary to be unsubscribed (Check issue: [(5) Documentation for RxJS Unsubscribing (Open)](https://github.com/angular/angular/issues/22410)).
- Use an abstract technique to avoid any code mess that may be resulted from unsubscriptions. You can manage your subscriptions with `takeUntil` [(3)](https://medium.com/@benlesh/rxjs-dont-unsubscribe-6753ed4fda87) or you can use this `npm` [package](https://www.npmjs.com/package/ng2-rx-componentdestroyed) mentioned at [(4) The easiest way to unsubscribe from Observables in Angular](https://medium.com/thecodecampus-knowledge/the-easiest-way-to-unsubscribe-from-observables-in-angular-5abde80a5ae3).

**Comment by simeyla** [comment]
@m0uneer  I very much disagree with 

> Never unsubscribe from an http observable as it is finite and it unsubscribes and cleans itself automatically

While this is true from the perspective of resources it only tells half the story. Let's say we're talking about directly calling http from within a component, and the http response took longer than needed so the user closed the component. The `subscribe()` handler will still be called even if the component is closed and destroyed. This can have unwanted side effects and in the worse scenarios leave the application state broken. It can also cause exceptions if the code in the callback tries to call something that has just been disposed. However at the same time occasionally they *are* desired. Like let's say you're creating an email client and you trigger a sound when the email is done sending - well you'd still want that to occur even if the component is closed.

The point being never say never, and consider the effects of the 'subscribe callback' being run after the component is destroyed on a case by case basis. It may be better to 'unsubscribe', or it may be better to run the logic with some additional `if (this._isDestoyed) {...}` logic.

**Comment by m0uneer** [comment]
@simeyla, thanks for giving the time to review my comment and regarding the `http` observable, I agree with you :)

**Comment by raysuelzer** [comment]
I am not sure if this is related, but I've noticed that ngOnDestroy() is called after the nagivation events, which in my case means that anything subscribed to queryParams will be called when the page navigates.

**Comment by viperphase1** [comment]
I just noticed this too. I built the subscription on the assumption that ngOnDestroy would be called before route.params pushes out another change and now I'm having problems.

**Comment by hahn-kev** [comment]
Looks like the original issue here is still a problem. [Here's a reproduction in StackBlitz](https://stackblitz.com/edit/angular-router-basic-example-yn4yue?file=app/views/login/login.component.ts), if you open up the console you will see if you switch between the login page and something else, you will see that subscriptions keep getting created, but the subscriptions are never completed or unsubscribed. However per the docs [here](https://angular.io/guide/router#observable-parammap-and-component-reuse) it says:

> When subscribing to an observable in a component, you almost always arrange to unsubscribe when the component is destroyed.
> 
> There are a few exceptional observables where this is not necessary. The ActivatedRoute observables are among the exceptions.
> 
> The ActivatedRoute and its observables are insulated from the Router itself. The Router destroys a routed component when it is no longer needed and the injected ActivatedRoute dies with it.
> 
> Feel free to unsubscribe anyway. It is harmless and never a bad practice.

however it seems that is not true based on the above tests. Can someone confirm that I'm doing the right thing here to test this?

**Comment by Andrei0872** [comment]
@hahn-kev I'm pretty sure there will be no memory leaks.  That's because the entity, in this case a `BehaviorSubject`(`ActivatedRoute`'s properties are `BehaviorSubject` instances), is destroyed when the `ActivatedRoute` associated to that view is destroyed.

I've detailed [here](https://stackoverflow.com/a/63258734/9632621) why memory leaks occur when using a Subject. From my perspective, the Subject holds that subscribe's callback(it holds all the subscribers in a list) and when you unsubscribe, that subscriber(which indirectly links to the callback) is removed from the list. But if the thing that holds everything is destroyed, then I think there will be no memory leaks.

**Comment by atscott** [comment]
This appears to be working as intended and as @Andrei0872 noted, it isn't a memory leak. It doesn't appear that the [documentation](https://angular.io/guide/router-tutorial-toh#observable-parammap-and-component-reuse) is necessarily misleading, it's just that `rxjs` behavior is difficult to understand. A couple important things to note:

* The component is destroyed, meaning that all of its members will be destroyed as well, including any subscriptions to the route params
* This _does not_ mean that any `finalize` operators or `complete` on the subscription is called. This only happens if the source completes or you unsubscribe for the subscription. The documentation doesn't state that the `Router` will do this, though I can still understand why the behavior is confusing.

You can play around with these scenarios here:
https://stackblitz.com/edit/rxjs-hmpizx?devtoolsheight=60
* `complete` the source without unsubscribe: `next`, `complete` and `finalize` are all called, even when `complete` is called before the `next` from the `delay`
* `unsubscribe` from subscription without `complete` on the source: `finalize` happens, but the `complete` of the subscription does not, and neither does `next`

So even if the `Router` were to call `complete` on all of the `Observables` on an `ActivatedRoute`, you would see that any subscriptions with a `delay` operator would still get called.

I'm lowering the priority here since I believe this is working as intended but that the documentation can be clarified to recommend unsubscribing if you need/desire the subscriptions to `complete` and/or `finalize`.
