### ISSUE TITLE
Don't tie api filter query to location query

### ISSUE THREAD

**Issue by IgorMinar** [angular/angular#16316]
Similarly to the main search we should not reflect the api filter query in the location:

<img width="1482" alt="screen shot 2017-04-25 at 3 35 18 pm" src="https://cloud.githubusercontent.com/assets/216296/25388731/e6b142b2-29ce-11e7-8308-9a25f1efac70.png">

**Comment by petebacondarwin** [comment]
@IgorMinar why is this?
In the angular.io website we actually added this because it was quite common for someone to search for something (e.g. router), click on a potential API item, find it was not what they wanted, then click back hoping to try again. It was disconcerting for them to find that their filters had been reset from the previous viewing.

**Comment by petebacondarwin** [comment]
@wardbell also points out that it is quite common to deep link to this page with the query in place, since it is nice to be able to go straight to a filtered view for a single module for instance.

**Comment by wardbell** [comment]
@IgorMinar The ability to deep link to an API search is extremely valuable ... much as it is useful to email a link to a search or PRs meeting specific criteria. We have places in the docs where we provide such a link (e.g., an API filter for all pipes).

I agreed completely with removing the search criteria from the general search because that produces a rather chaotic and _in-your-face_ result. 

>You can actually do it - the page respects search criteria on arrival. But it doesn't "pollute" the address bar with a search parameter so it's a hidden feature.

**Comment by IgorMinar** [comment]
@wardbell @petebacondarwin ok. I verified that the history management works as expected in this case, in which case the feature is indeed useful. thanks for explanation!
