### ISSUE TITLE
AoT: inheritance error not reported correctly

### ISSUE THREAD

**Issue by dmitrysteblyuk** [angular/angular#16335]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
If a component extends a class with implemented lifecycle hooks, they're not being called when building with aot (both in prod and dev). It's alright though when running ng build --prod --aot=false

**Expected behavior**
Lifecycle hooks inheritance should be working

**Minimal reproduction of the problem with instructions**
```
import { Component, OnInit } from '@angular/core';

class Foo implements OnInit {
    ngOnInit() {
        alert('Foo initialized');
    }
}

@Component({
    selector: 'app-root',
    template: 'App works',
})
export class AppComponent extends Foo {}
```

**What is the motivation / use case for changing the behavior?**

**Please tell us about your environment:**
Windows 10

* **Angular version:** 4.0.3

* **Browser:** any
 
* **Language:** TypeScript 2.3.0

* **Node (for AoT issues):** `node --version` =  7.8.0

**Comment by dmitrysteblyuk** [comment]
I opened this issue before - #15756. It was thought it would be fixed by #15583 but the issue is still there.

**Comment by chuckjaz** [comment]
The is an error condition that is not being reported `ngc` nor by TypeScript as, by default, the `"declaration"` option is `false`.

An exported class must only extend exported classes. To have TypeScript report this case, change the `"declaration"` option to `true` in your `tsconfig.json` file.

To fix this in your code, add `export` in front of the declaration of `Foo`.

I am keeping this open as a bug because we should report this as an error in `ngc` even if TypeScript allows it.

REPO:
1. `git clone https://github.com/chuckjaz/e16335.git`
2. `cd e16335`
3. `yarn`
4. `ng build --aot`

Expected: Error report that `Foo` is not exported.
Received: Compiled successfully but produced incorrect code ("App works: not initialized" instead of "App works: initialized").

**Comment by dmitrysteblyuk** [comment]
Ok now I see what was the problem. I exported Foo from another file as a default export. It seems only then this issue takes place.

```
import { OnInit } from '@angular/core';

export default class Foo implements OnInit {
    ngOnInit() {
        alert('Foo initialized');
    }
}
```

```
import { Component } from '@angular/core';
import Foo from './foo';

@Component({
    selector: 'app-root',
    template: 'App works',
})
export class AppComponent extends Foo {}
```

Otherwise it's alright.

**Comment by chuckjaz** [comment]
@dmitrysteblyuk We don't currently support default exports. I will create a tracking bug for this issue and reference this issue to it to make sure we take this scenario into account.
