### ISSUE TITLE
Currency pipe and locale 

### ISSUE THREAD

**Issue by nlgi** [angular/angular#16374]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
I'm using locale (and i18n) in my app.
In app.module, I added :
`
    { provide: LOCALE_ID, useValue: (document['locale'] ? document['locale'] : 'en-US') }
`
document['locale'] is 'fr-FR'.

It works perfectly with number, date...
Ex.: 
`
    mydate | date:'shortDate'`

Is in french.

For currency, symbol is now on the right (ok), but I want to display euro symbol, not USD.
`
     mynumber | currency`
Return 24 000,00 USD : number format is ok, not the currency code. I don't want to put 'EUR' because locale is dynamic.

I think it's a bug, because the locale changes:
- number format in my amount
- currency code position

But still USD by default.

**Expected behavior**

EUR by default.

**Minimal reproduction of the problem with instructions**

See description.

**What is the motivation / use case for changing the behavior?**

Use locale currency.

**Please tell us about your environment:**

Windows / Visual Studio code

* **Angular version:** 4.1.0

* **Browser:** Chrome 58

 
* **Language:** TypeScript 2.2

* **Node (for AoT issues):** `node --version` =   6.10.1

**Comment by vicb** [comment]
Please add a plunker that reproduce the issue.

Also `useValue` should only be used when the value is known at compile time, you should use a factory here.

**Comment by nlgi** [comment]
Hm yes good idea.

I still made a plunker : https://plnkr.co/edit/ulUEXDavlwQw9s71OObe?p=preview
You can switch the locale id to 'en-US' to see changes.

With 'fr-FR' : number works perfectly, number too.
For currency, number format is ok, currency code is passed to the right... But still "USD".

**Comment by ocombe** [comment]
Hello,
the currency is a parameter of the currency pipe, by default the value is "USD", if you don't change the value it will always use "USD", it's not dependent on the locale, only the position depends on the locale.
The problem is that 1000$ is different from 1000€, it's not a matter of translation, the value is different (right now 1000$ = 915.80 €). The currency pipe should not change the symbol of the currency automatically, it makes no sense.
So yes, the position of the currency symbol changes but not the symbol itself, sorry. It is up to you to know if the number that you're showing is in $ or €.

**Comment by Serginho** [comment]
Same problem with the new API in angular 5.1.2. The number is formatted properly, but not the currency.

**Comment by vimalraj-a** [comment]
Can the currency derived from locale? or provide us option to set default current format

**Comment by ocombe** [comment]
You can use the api functions `getLocaleCurrencySymbol` (https://angular.io/api/common/getLocaleCurrencySymbol) and `getLocaleCurrencyName` (https://angular.io/api/common/getLocaleCurrencyName) for that

**Comment by rodrigoyoshida** [comment]
Since I already changed the LOCALE_ID it makes sense that the currency symbol changes automatically, because the users of my country can find the $ symbol alone a bit confusing, they will not know if it means the local currency or other one like dollar. Also my code looks ugly having all those currency symbols after the pipe, at least there should be a way to easily set the default currency symbol.

**Comment by rodrioce** [comment]
Same problem here, 
had to use an workaround creating a new pipe:

`import { Pipe, PipeTransform, LOCALE_ID, Inject } from '@angular/core';
import { getLocaleCurrencySymbol, getLocaleCurrencyName } from '@angular/common';

@Pipe({
  name: 'currencyGlobal'
})
export class CurrencyGlobalPipe implements PipeTransform {
  constructor(@Inject(LOCALE_ID) public locale: string){    
  }

  transform(value: number): any {    
    return getLocaleCurrencySymbol(this.locale)  + new Intl.NumberFormat(this.locale, { style: 'decimal', minimumFractionDigits: 2 }).format(value);
  }

}
`

Couldn't use the Intl style:'currency' because the getLocaleCurrencyName doens't return the same as the documentation says it does (https://angular.io/api/common/getLocaleCurrencyName), should be 'USD' but return 'US Dollar', so I did an workaround with currencySimbol + decimal.

Maybe it can help someone else

**Comment by ocombe** [comment]
Actually you're right the documentation needs to be updated, it does return "US Dollar", not "USD", but that's intended since it's the currency name (not the currency code which is "USD"), see here: https://github.com/angular/angular/blob/master/packages/common/locales/en.ts#L51

Would you mind opening a PR to fix that documentation error please?

**Comment by Lugriz** [comment]
I'm currently using Angular 7 and I think this problem can be solved like this:
`
import { Pipe, PipeTransform, LOCALE_ID, Inject } from '@angular/core';
import { formatCurrency, getLocaleCurrencySymbol } from '@angular/common';

@Pipe({
  name: 'localeCurrency'
})
export class LocaleCurrencyPipe  implements PipeTransform {

  constructor(
    @Inject( LOCALE_ID ) private _localeId: string
  ) {}

  transform(value: number, currencyCode?: string, digitInfo?: string): any {
    return formatCurrency(value, this._localeId, getLocaleCurrencySymbol( this._localeId ), currencyCode, digitInfo);
  }

}
`

**Comment by mlangwell** [comment]
This is a problem for our team. Our API calculates and returns the appropriate currency amount for our users. We need to be able to show our users the correct currency symbol based on the LOCALE_ID of the application. Why is the currencyCode param of the pipe undefined by default? For our implementation and what it looks like everyone else wants due to the workarounds listed above, I feel the default value should be the LOCAL_ID's currencyCode. If a developer wants to override that functionality, just simply pass the correct currenyCode in. So the following comment makes no sense to me, because our API is _always_ serving the correct currency amount whether it is in USD, EUR, etc.

> 
> 
> Hello,
> the currency is a parameter of the currency pipe, by default the value is "USD", if you don't change the value it will always use "USD", it's not dependent on the locale, only the position depends on the locale.
> The problem is that 1000$ is different from 1000€, it's not a matter of translation, the value is different (right now 1000$ = 915.80 €). The currency pipe should not change the symbol of the currency automatically, it makes no sense.
> So yes, the position of the currency symbol changes but not the symbol itself, sorry. It is up to you to know if the number that you're showing is in $ or €.

**Comment by ocombe** [comment]
We don't default to `LOCALE_ID` to avoid this mistake (where people don't even think about the fact that the value should be different with a different currency). We're taking the safe approach for the default here.

**Comment by mlangwell** [comment]
@ocombe I appreciate you guys trying to keep in mind the people that do not know what they are doing, but is that the right solution for everyone?

Think about it from a developers stand point that wants to use the Angular Framework. In my experience so far, localization has been one of the most challenging things to implement in our application. Our application is a global application that will be used in potentially over 40 different locales. So our team goes to the Angular Framework in hopes that it solves all of our localization needs. But oops turns out that some pipes support localization by default and some pipes do not. So now I have taken all of the time to properly set up my application by registering the appropriate locale(s) that I am using at bootstrap of the application and I cannot even depend on the localization that I spent time implementing. Now I have to create a wrapper around a framework which I went to in the first place to solve my problem. 

Do you see my dilemma here? Why protect the people that do not know what they are doing?

I vote that the Angular team makes the pipe take in applications localization by default, then developers can override from there. Anyone else agree?

**Comment by ocombe** [comment]
We are not going to make a breaking change for that, sorry.
What could be possible would be a provider option that would configure that. Something like `{provide: CURRENCY_PIPE_DEFAULT_LOCALE, useValue: true}`

**Comment by mlangwell** [comment]
@ocombe that is what major releases are for right? That is when breaking changes are introduced. I am not saying you guys have introduce a breaking change, but I think it would be wise to come up with a solution ASAP. Looks like there's enough people that want this functionality due to the workarounds.
