### ISSUE TITLE
Dependency injection creating new instances instead of sharing

### ISSUE THREAD

**Issue by dvlsg** [angular/angular#1639]
This may or may not be an issue, so feel free to tell me if my expectations are incorrect.

When using injectables across multiple components, if the injectable is included with both components, then multiple instances of the class may be instantiated by the dependency injection. I would expect the injectable/service to be a single instance, which appears to be how di.js handles it.

Here is a plunker showing the code in action: http://plnkr.co/edit/R9tZVbawT0hT7X4AnB4E?p=preview

You should be able to see both in the console that the class Service is created 6 times, as well as looking at the id for each service in the html. Upon removing Service from NameComponent's injectables (but keeping it inside the constructor so it still gets injected), there will only be one instance of Service created.

Is this a bug, or expected behavior across components? If it's expected behavior, is there a suggested way to share single instances of injectables across components? I ran across this while implementing angular components with a flux architecture and trying to use a Store across multiple components.

**Comment by matanlurey** [comment]
Any reason you can't put the Service binding in the bootstrap or in a common parent component?

**Comment by dvlsg** [comment]
Not any technical reason. It works fine that way, but feels unintuitive (IMHO). It would be the difference between importing services and listing them as injectables where they are needed, and importing *everything* required by your app in the top level components to ensure that services will always be single instances. Not the end of the world, by any means, and it's certainly simple to pull off with smaller applications.

To be honest, I'm surprised that the injectables array needs to be specified at all at the component level, after taking a closer look at di.js where including the type in the constructor or specifying an @Inject decorator with the class was enough information for the injection container.

**Comment by pkozlowski-opensource** [comment]
@dvlsg This works as expected. I've got an impression that you are confusing _registration_ of what is available in the injector (via `injectables`) versus _using_ (injecting) what is available. You can only inject what was registered before, so things need to be registered _somewhere_.

Now, as far as registration goes, in ng2 there is _hierarchy_ of injectors and you can register things on any level. By default each component is creating a sub-injector (a new entry in the hierarchy) and this new injector you are _registering_ a new entry using `injectables`.

As suggested by @matanlurey you could simply move registration to the bootstrap process (thus configuring the app's root injector)  

> I'm surprised that the injectables array needs to be specified at all at the component level

It is not quite accurate - you can register things at any level an child injectors (child components) will see everything that is registered in a parent (until overridden). So an alternative solution would be to register your service in a parent component, that is, in a `<display>`: http://plnkr.co/edit/vrv9mO80miHkgGygQ4iu?p=preview

**Comment by pkozlowski-opensource** [comment]
I'm going to close this one as things work as expected / designed. Having said this I can see this as a recurring "confusion point". @mhevery @vsavkin I'm not sure if we just need to have better docs for this, name things differently or re-work concepts, but I can see people bumping into this over and over again... 

Personally it is confusing to me why things are confusing to people, as for me the current design makes perfect sense and is easy to understand. But yeh, this one keeps coming back in questions...

**Comment by dvlsg** [comment]
Thanks for the clarification, I appreciate it.

I can't speak for anyone else, but my confusion probably stemmed from using other dependency injection methods which would only inject a single instance, even when parent/child relationships were used. Even in di.js and Angular 1.x, if I'm remembering correctly. I know the parent/child relationships in Angular 2.x are probably handled differently -- it just took me by surprise.

**Comment by sullivanpt** [comment]
I'm probably the only one who believes the hierarchical DI as implemented is overly clever?  Even the official ng2 tutorial is recommending we declare our providers as close to the leaves as possible because the root "doesn't and shouldn't need to know"; furthermore, it states this without even a footnote pointing out that you lose your app wide singleton as soon as you do this.  My prediction is there will be a landslide of "un-reusable" components that each declare their own "logging" provider.

**Comment by zoechi** [comment]
@sullivanpt If it didn't matter where to register providers they would have written "on the leaves" not "as close to the leaves as possible". 

If you want to share a service instance with the whole application it usually includes the root component anyway, therefore register it at the root.
If you don't want to share with the whole application, register the provider as close to the leaves as possible so that the subtree where you want to share it is covered.

If you think the docs need to be improved, please create an issue in the https://github.com/angular/angular.io repository where the docs and tutorials are maintained.

> implemented is overly clever

Where you register a provider defines it's scope. What's wrong with that?

See also #5458

**Comment by sullivanpt** [comment]
@zoechi thanks, I find your "If you want to share ... If you don't want to share... " statement to be much clearer than anything I've read in the official documentation.
