### ISSUE TITLE
@angular/core module has incorrect import in AOT compiled lazy loaded app

### ISSUE THREAD

**Issue by bryant-pham** [angular/angular#16553]
**I'm submitting a ...**  (check one with "x")
```
[ x ] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
Navigating to a lazy loaded route in a AOT compile app causes error:
![image](https://cloud.githubusercontent.com/assets/3394709/25722227/fec3b374-30d8-11e7-84c3-0f5763da7a17.png)

It occurs on this line:
![image](https://cloud.githubusercontent.com/assets/3394709/25722248/12fbc9f8-30d9-11e7-9325-1ad97022bad6.png)

From digging into import1, I can tell that it represents @angular/core because it contains core related classes:
![image](https://cloud.githubusercontent.com/assets/3394709/25722401/b3a60ef4-30d9-11e7-94f8-90b5a100d474.png)

I also see that import1 contains Éµcrt but not ɵcrt:
![image](https://cloud.githubusercontent.com/assets/3394709/25722270/2a947e52-30d9-11e7-81be-1e9d62d05359.png)

What may cause the discrepancy between those symbols after AOT compilation?

**Expected behavior**
Navigating to the route should load the lazy loaded component

**Minimal reproduction of the problem with instructions**

**What is the motivation / use case for changing the behavior?**

**Please tell us about your environment:**

OS: Linux Mint Rosa

* **Angular version:** 2.0.X

Angular version 4.1.0

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

Chrome
 
* **Language:** [all | TypeScript X.X | ES6/7 | ES5]
TypeScript

* **Node (for AoT issues):** `node --version` =  7.10.0

**Comment by tbosch** [comment]
This looks like you have missing utf8 support for e.g. your filesystem. Could you create a branch on Github that reproduces the problem?

**Comment by hill0826** [comment]
I'm running into this issue as well. It seems to only be triggered when I use a library that includes AoT code -- in my case, `ag-grid-angular`. I hesitate to post an issue on their page yet since this seems so closely related to the compiler, though.

One thing that I find very interesting is that the keys in `vendor.js` seem to vary based on the libraries included.

With `ag-grid-angular`, the key is `Éµcrt`:
![2017-06-09 01_34_45-institutional center](https://user-images.githubusercontent.com/3606315/26963956-10e4c14a-4cb5-11e7-96e4-c6225d7c56c9.png)

Without `ag-grid-angular`, the key is `F` for the same function:
![2017-06-09 01_42_13-institutional center](https://user-images.githubusercontent.com/3606315/26963960-1303c71e-4cb5-11e7-8c65-fee4afed46df.png)

This is interesting because `createRendererType2` is being exported as `ɵcrt` in `node_modules/@angular/core/src/codegen_private_exports.d.ts` already, so I'm not sure why it would ever show up as anything else. `ag-grid-angular` is clearly expecting `ɵcrt` since it's hard-coded into their AoT code.

Maybe somebody else would have some insight into that?

I haven't been able to successfully make a minimal reproducible example yet, but I'll post here if I ever figure the details out.

**Comment by hill0826** [comment]
Discovered the issue in my case. Definitely an encoding issue.

Two quick work around options:
1. (Client-side solution) Add `charset="utf-8"` to all eagerly-loaded `script` tags
2. (Server-side solution) Add `; charset=UTF-8` to the `content-type` response header

In my case, I'm using Angular CLI.

Module lazy-loading is done through Webpack itself (without external plugins). It interprets bundles as UTF-8 by default. [See relevant template code here.](https://github.com/webpack/webpack/blob/0dd0830478e5f5dd0e36930092e5ce6b6e6d3f39/lib/JsonpMainTemplatePlugin.js#L52)

However, the script tags generated by HtmlWebpackPlugin, whose template doesn't include a charset attribute, which means the client will use its default client encoding if the server doesn't specify one. [See relevant template code here.](https://github.com/jaketrent/html-webpack-template/blob/86f285d5c790a6c15263f5cc50fd666d51f974fd/index.html#L52)

This causes all eagerly-loaded scripts to be loaded as the default encoding (I'm guessing ISO-8859-1 in my case) and all lazily-loaded scripts to be loaded as UTF-8, hence the conflict between `Éµcrt` (ISO-8859-1) and `ɵcrt` (UTF-8).

I put an [issue down](https://github.com/angular/angular-cli/issues/6645) for Angular CLI for now.

It took way too long for me to figure all that out. Glad to finally have that done.

**Comment by vicb** [comment]
Seems like a configuration issue unrelated to angular.
