### ISSUE TITLE
es5 bundles export some strange mangled (internal?) symbols, that are picked up by IDE autocomplete

### ISSUE THREAD

**Issue by Necroskillz** [angular/angular#16583]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
The es5 bundles export some strange mangled (internal?) symbols. VS Code picks up typings from *.es5.js I guess, and you get this in intellisense:

![router_symbols_bug](https://cloud.githubusercontent.com/assets/346477/25745983/ab90ab7a-31a1-11e7-92fc-4bb1bc69a09c.png)

If you `import { ɵa } from '@angular/router'` it compiles.

**Expected behavior**
Looks like these are internal symbols, so either the bundle shouldn't expose them, or the editor should be forced to use `.d.ts` files.

**Minimal reproduction of the problem with instructions**
- `ng new app`
- open in VS Code
- `import { ɵa } from '@angular/router'`

**Please tell us about your environment:**
Windows 10

* **Angular version:** 4.1.1

* **Browser:** all
 
* **Language:** [ES5 / TS 2.3]

**Comment by IgorMinar** [comment]
The prefixed symbols are indeed private (see [documentation](https://github.com/angular/angular/blob/master/docs/PUBLIC_API.md)). The must be exported because they are being used by the code generated by the AOT compiler.

Typescript currently doesn't support another way of hiding these symbols, so we prefixed them with "barred latin O" to group them together and make them appear at the bottom of the sorted list displayed by IDE autocompletion. It's not ideal, but it doesn't seem that we have another way of doing this right now.

**Comment by IgorMinar** [comment]
This is still an issue, and after seeing people struggle with it quite a bit, I think we need to find a way to tackle it. There are some new options we have since the last time I commented on this.

One way would be to mark those symbols as internal so that they don't appear in d.ts files at all, and are available only at runtime. Another way would be to use a side channel in a form of a private entry point to share those symbols across packages.

**Comment by alxhub** [comment]
Closing as this isn't really reported much as an issue anymore - likely due to Ivy not generating random private symbols for user code.
