### ISSUE TITLE
Date pipe adds 2 hours to iso 8601 formatted date string in chrome and safari

### ISSUE THREAD

**Issue by Waterstraal** [angular/angular#16624]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
A iso 8601 formatted string formatted by using the date pipe get added 2 hours in chrome

**Expected behavior**
The iso 8601 formatted string is formatted without adding 2 hours in chrome

**Minimal reproduction of the problem with instructions**
The following:
```
{{'2017-05-07T22:14:39'| date:'dd-MM-yyyy HH:mm'}}
```
Outputs `08-05-2017 00:14` instead of `07-05-2017 22:14`

Plunker: http://plnkr.co/edit/pcoEmL1gR53tyqG9p6ZY?p=preview

**What is the motivation / use case for changing the behavior?**
Seems like a bug to me.

**Please tell us about your environment:**
Win 7, angular-cli 1.0, yarn

**Angular version:** 4.1.1

**Browsers:**  
- Chrome 57.0.2987.133
- Safari on macOS 10.12.5 (10.1.1)
- Safari on iOS 10.3.2

(Tested oké in Firefox 54.0a2, different issue in IE 11.0.9600.18639)

**Language:** TypeScript 2.2.1

**Comment by xedenis** [comment]
Experiencing a similar problem, Angular DatePipe sometimes adds or substracts 1 hour.

Tested in Eastern Time Zone, seems to be related to switch between daylight time and standard time

Plunker: http://plnkr.co/edit/icTKVsNTfuPpBIIXblsF?p=preview

**Comment by k-schneider** [comment]
You can see this same behavior if your input is a string.

According to the Angular docs: "When the expression is a ISO string without time (e.g. 2016-09-19) the time zone offset is not applied and the formatted text will have the same day, month and year of the expression."

This is not the case - see this plunker for example:

http://plnkr.co/edit/51hHWueatHqzMDpfWsH6?p=preview

**Comment by trkoch** [comment]
I'm observing possibly related offsets in date formatting.

    {{'1958-07-03' | date:'dd.MM.yyyy z'}}<br>
    {{'1958-07-03T00:00:00' | date:'dd.MM.yyyy z'}} (0:00)<br>
    {{'1958-07-03T00:59:00' | date:'dd.MM.yyyy z'}} (0:59)<br>
    {{'1958-07-03T01:00:00' | date:'dd.MM.yyyy z'}} (1:00)<br>

Results in

![image](https://user-images.githubusercontent.com/73974/27329665-c1307aa8-55b6-11e7-9289-61dcd4f5e938.png)

Curiously this offset is only applied to certain dates, e.g. `1958-01-01` is not affected.

**Comment by trkoch** [comment]
Turns out this is related to timezone handling, specifically daylight saving times in years where there was no daylight saving.

>  For instance, Germany introduced DST in 1916 only to abandon it in 1919 (*), reintroduce somewhat in 1940 (without any rolling back to normal time until 1942 and lots of twists), yet again abandon in 1945 and finally reintroduce in 1980. `*`) Perhaps this would have been the best moment in history for people to realize not to mess with time and never introduce such thing again. Alas…

Err? Moving on, when Angular formats a date, it delegates to `Intl.DateTimeFormat`. To construct a date without time from a string (input of filter) it extracts year, month and day and executes `new Date(y,m,d)`. Unless specified otherwise (which Angular isn't) `Intl.DateTimeFormat` assumes the runtime's default time zone (`Europe/Berlin` in case of Germany); `new Date()` creates a date with the local time zone. Sounds fine? Not so fast. There is one nasty gotcha! Lets roll back to, say, `1960-06-01T00:00` (remember, no DST!): Taking the current timezone into account, `new Date(1960,5,1)` provides us a **GMT+2** date which when formatted according to `Intl.DateTimeFormat` evaluates to 5/31/1960. The issue here is that `Intl` is in fact *aware* of the DST history of a given region while `Date()` is not. If it were it needed to provide us with a **GMT+1** date.

In code:

```js
var options = {year: 'numeric', month: 'numeric', day: 'numeric', hour: 'numeric', minute: 'numeric'}
new Intl.DateTimeFormat(
  'en-US', {timeZone: 'Europe/Berlin', ...options}
).format(new Date(1960,05,01))
-> 
```

`tldr;` `Intl.DateTimeFormat` outsmarts `Date` but leaves Angular confused.

**Comment by trkoch** [comment]
Pinpointing differences of `Intl` and `Date`:

```js
new Date(1960,05,01) // Wed Jun 01 1960 00:00:00 GMT+0200 (CEST)
new Date(1970,05,01) // Mon Jun 01 1970 00:00:00 GMT+0100 (CET)
new Date(1980,05,01) // Sun Jun 01 1980 00:00:00 GMT+0200 (CEST)
```

Interestingly `Date` knows DST was introduced in 1980, but incorrectly assumes it was present before 1970.

**Comment by trkoch** [comment]
I should add this also affects Safari but *not* Firefox. @Waterstraal Can you update the title to reflect this?

**Comment by Waterstraal** [comment]
@trkoch In what version of Safari did you test this?

**Comment by trkoch** [comment]
:x: Safari on macOS 10.12.5 (10.1.1)
:x: Safari on iOS 10.3.2
