### ISSUE TITLE
Angular 4 has breaking changes to change detection when initiated from an async context

### ISSUE THREAD

**Issue by WillooWisp** [angular/angular#16668]
**I'm submitting a ...**  (check one with "x")
```
[x ] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**

In two different scenarios, but with similar execution paths, angular 4 stops working silently without console errors (angular 2 works fine though). Setting a property on a "parent" component (in the context of a subscribe on an observable from an http request) bound to an input of a child component, that in turn causes an event emitter to tell the parent component that the work in the child component is finished. This output from the child component is bound to a property in the parent component that in turn is bound to an input property of a second component. The problem is that the property change notification never boils back up to the second child component, the parent component gets it, but here the change detection mechanism seems to break, silently. The UI stops working after this as well, with some menus never showing up on click and button states never changing when toggled.

If we instead change the same initial property causing these change of events to occur outside the context of a subscribe to the observable from the http request, it all works fine.

This all works fine in angular 2, but not in angular 4.0 and 4.1.

Adding this extra zone and change detection handling makes it work in angular 4.0+ as well.

`this.httpService.getSomething().subscribe((result: any) => {`
 `   this.zone.runOutsideAngular(() => {
        this.propertyBoundToInputOfFirstChildComponent = result;`
`    });`

`this.zone.run(() => {
        this.cdRef.detectChanges();
    });`
`});`

**Expected behavior**

The expected behavior is that all bindings and event emitter values should propagate down to child component 1 and up to parent and down to child component 2 even when the property bound to an input of child component 1 is changed in the context of a subscribe method on an observable from a http request.

**Minimal reproduction of the problem with instructions**

See explanation and code sample above.

**What is the motivation / use case for changing the behavior?**

No breaking changes related to change detection are mentioned in the release notes of angular 4.

**Please tell us about your environment:**

Windows 10, VS Code, yarn / npm

* **Angular version:** 2.0.X

Angular 4.1

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

 Chrome 57.0.2987.133 (64-bit)

* **Language:** [all | TypeScript X.X | ES6/7 | ES5]
TypeScript 2.3

* **Node (for AoT issues):** `node --version` =   
v6.10.0

**Comment by Toxicable** [comment]
Can you please make a minimal reproduction in plunkr, https://plnkr.co/edit/tpl:AvJOMERrnz94ekVua0u5 it's very hard to do anything without a reproduction on when the issue occurs

**Comment by Lyoko-Jeremie** [comment]
@Toxicable this issue are similar with #16047
and i got a solution from this issue for #16047 just now.

**Comment by jasonaden** [comment]
@WillooWisp Thanks for the details, but please get this put into a plunker ASAP. It appears to be a valid issue, but without a plunker issues are usually closed out.

**Comment by WillooWisp** [comment]
Okay, I will try reproduce it in plunker any time soon.

**Comment by WillooWisp** [comment]
I do think this represents the problem we are experiencing now in angular 4 compared to what just worked in angular 2, https://plnkr.co/edit/K1vLDkx108AD4kDfiMr7

**Comment by luji** [comment]
Same issue since I upgraded from 2.x to 4.x. It breaks silently and not always. Pretty hard to reproduce.

**Comment by wizarrc** [comment]
It looks like the `updateProp` function is updating the `view.oldValues` too early. The problem is the following functions are called once and before side-effects are handled i.e. `isLoading` event shown in the above repo. The effected code is never invalidated.

`view.oldValues[def.bindingIndex + bindingIdx] = value;`
https://github.com/angular/angular/blob/39b92f7e546b8bdecc0e08c915d36717358c122b/packages/core/src/view/provider.ts#L464

`changes = updateProp(view, providerData, def, i, values[i], changes);`
https://github.com/angular/angular/blob/39b92f7e546b8bdecc0e08c915d36717358c122b/packages/core/src/view/provider.ts#L220
https://github.com/angular/angular/blob/39b92f7e546b8bdecc0e08c915d36717358c122b/packages/core/src/view/provider.ts#L161

Here are the series of events and why it doesn't work:

```
**AppRef.detectChanges**
parent: checkAndUpdateView - updateDirectives
	Checking Child2 def
		parent.isLoading: true === child2.isRunning: true **no changes and no updating to the view.oldValues**
	Checking Child1 def
		parent.options: { name: "test" } !== child1.options { name: "test" } **different object reference**
			updateProp
				child1.options set
					isLoading.event.emit(false) -> parent.onIsLoading **side-effect**
						parent.eventHandler.markForCheck **never actually does detect changes becaue it's currently inside a detect changes**
						parent.isLoading = false **is never invalidated or checked again**
				update view.OldValues for parent.options
parent: checkAndUpdateView  - execComponentViewsAction
	Child2: checkAndUpdateView - updateDirectives
		Checking ngIf template def
			child2.isLoading: true === ngIf.isLoading: true **never updated after event, and already checked from before**
	Child2: checkAndUpdateView - execEmbeddedViewsAction - NgIf **never updated**
	Child1: checkAndUpdateView
**AppRef.checkNoChanges** - **fails**
```
To fix this, the `updateDirectives` function will have to include a dirty check that will be triggered by the event handler. The event handler will also determine if it's being called from within the `updateDirectives` function, and if so, do not `markForCheck` and instead flag the directive as dirty. After the function completes, check if dirty, and if so, repeat the check till no longer dirty.

@Toxicable @jasonaden Any ideas of what the code might look like to make these changes? Another flag in the NodeDef structures to indicate dirty? I was thinking adding a flag to `ViewState` such as `dirty`.

https://github.com/angular/angular/blob/39b92f7e546b8bdecc0e08c915d36717358c122b/packages/core/src/view/types.ts#L356

**Comment by wizarrc** [comment]
I want to note, if I swap the order of `my-child-one` and `my-child-two`, everything works, so it confirms that events in the a later child will never re-evaluate properties set in children components earlier in the view.

Maybe the title should be "Angular 4 - events handled in child components will ONLY update changed values after that child in view before crashing". Seems long but better descriptive of what the issue really is about.

**Comment by tovinayv** [comment]
Facing same issue..

**Comment by mhevery** [comment]
stale; won't fix
