### ISSUE TITLE
IOS 10 Safari errors [TypeError: null is not an object | this.router.serializeUrl is not a function]

### ISSUE THREAD

**Issue by kevinwardenga** [angular/angular#16717]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
I'm getting three errors on IOS 10 Safari (all other browsers and IOS versions < 10 are working fine) via Sentry, but i couldn't reproduce them, they're appearing only for a few users.

Stacktraces:
```
TypeError: null is not an object (evaluating 'this._viewContainer.clear')
  at _updateView(/lib.min.js:1:57443)
  at set(/lib.min.js:1:56796)
  at pn(/lib.min.js:1:98066)
  at an(/lib.min.js:1:95376)
  at Wn(/lib.min.js:1:110066)
  at fr(/lib.min.js:1:114221)
  at ? (/app.min.js:1:613371)
  at zn(/lib.min.js:1:109299)
  at rr(/lib.min.js:1:112122)
  at tr(/lib.min.js:1:111520)
  at zn(/lib.min.js:1:109417)
  at detectChanges(/lib.min.js:1:187677)
  at forEach([native code])
  at tick(/lib.min.js:1:157776)
  at ? (/lib.min.js:1:155673)
  at onInvoke(/lib.min.js:1:149438)
  at run(/lib.min.js:1:1529660)
  at next(/lib.min.js:1:155654)
  at ? (/lib.min.js:1:146228)
  at __tryOrUnsub(/lib.min.js:1:1223654)
  at next(/lib.min.js:1:1222940)
  at _next(/lib.min.js:1:1221984)
  at next(/lib.min.js:1:1221656)
  at next(/lib.min.js:1:1218290)
  at emit(/lib.min.js:1:146001)
  at checkStable(/lib.min.js:1:148969)
```
```
Uncaught (in promise): TypeError: null is not an object (evaluating 'this.location.injector')
activateWith@https://www.deswin.de/lib.min.js:1:402435
placeComponentIntoOutlet@https://www.deswin.de/lib.min.js:1:393978
activateRoutes@https://www.deswin.de/lib.min.js:1:393756
https://www.deswin.de/lib.min.js:1:392991
forEach@[native code]
activateChildRoutes@https://www.deswin.de/lib.min.js:1:392961
activateRoutes@https://www.deswin.de/lib.min.js:1:393835
https://www.deswin.de/lib.min.js:1:392991
forEach@[native code]
activateChildRoutes@https://www.deswin.de/lib.min.js:1:392961
activate@https://www.deswin.de/lib.min.js:1:392633
https://www.deswin.de/lib.min.js:1:386793
https://www.deswin.de/lib.min.js:1:1205241
__tryOrSetError@https://www.deswin.de/lib.min.js:1:1223764
next@https://www.deswin.de/lib.min.js:1:1222886
```

```
Uncaught (in promise): TypeError: this.router.serializeUrl is not a function. (In 'this.router.serializeUrl(this.urlTree)', 'this.router.serializeUrl' is 9.61947235e-316)
updateTargetUrlAndHref@https://www.deswin.de/lib.min.js:1:397201
https://www.deswin.de/lib.min.js:1:396361
__tryOrUnsub@https://www.deswin.de/lib.min.js:1:1223654
next@https://www.deswin.de/lib.min.js:1:1222940
_next@https://www.deswin.de/lib.min.js:1:1221984
next@https://www.deswin.de/lib.min.js:1:1221656
next@https://www.deswin.de/lib.min.js:1:1218290
https://www.deswin.de/lib.min.js:1:386869
onInvoke@https://www.deswin.de/lib.min.js:1:149438
run@https://www.deswin.de/lib.min.js:1:1529660
https://www.deswin.de/lib.min.js:1:1539166
onInvokeTask@https://www.deswin.de/lib.min.js:1:149342
runTask@https://www.deswin.de/lib.min.js:1:1530327
o@https://www.deswin.de/lib.min.js:1:1527411
invoke@https://www.deswin.de/lib.min.js:1:1536163
```

**Minimal reproduction of the problem with instructions**
I don't know how to reproduce this.

**Please tell us about your environment:**

* **Angular version:** 4.1.2

* **Browser:** iOS 10.3.1 Safari (10 & 10.1) &  iOS 10.0.1 Safari 10

 
* **Language:**  TypeScript 2.3

* **Node (for AoT issues):** `node --version` =   7.10

**Comment by jasonaden** [comment]
I'm sorry but we can't reproduce the problem following the instructions you provided.

If the problem still exists please open a new issue following [our submission guidelines](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-submitting-an-issue).

**Comment by awerlang** [comment]
On angular 4.3.2, same thing here regarding `this.router.serializeUrl is not a function` on User agent: `Mozilla/5.0 (iPhone; CPU iPhone OS 10_3_3 like Mac OS X) AppleWebKit/603.3.8 (KHTML, like Gecko) Version/10.0 Mobile/14G60 Safari/602.1`

Is is a bug on uglify perhaps? Building with cli `ng build --aot --prod -sm --vendor-chunk=false --output-hashing=none`. How otherwise `serializeUrl` would be a number like `4.35754516e-316` (there's different numbers each time)?

**Comment by bliDetch** [comment]
I'm having the same problem with Angular 4.3.2 using aot.  Browser: "Mozilla/5.0 (iPhone; CPU iPhone OS 10_3_3 like Mac OS X) AppleWebKit/603.3.8 (KHTML, like Gecko) Version/10.0 Mobile/14G60 Safari/602.1", the error is: Error: Uncaught (in promise): TypeError: this.router.serializeUrl is not a function. (In 'this.router.serializeUrl(this.urlTree)', 'this.router.serializeUrl' is 3.91318015e-316) updateTargetUrlAndHref ...

**Comment by lemoinem** [comment]
I just hit this same issue (using angular 4.3.2) and looked a bit into it. Maybe I'm way off, but here is what I found and what I think:

The error itself is deterministic (it's always the same error on the same line) but triggering it appears random.

The error is that a JS method (router.serializeUrl) seems to be overridden by a very small floating point value. As can be seen by the error message "'this.router.serializeUrl' is 3.8843346e-316"). The value itself changes each time the error is triggered, but it is always a very small (actually, subnormal) 64 floating point value.

This actually makes me think the value of the method itself is not overridden, but that an obscure bug in the Safari JavaScript interpreter reinterprets the function's 32 bits address as a 64 bits floating point value (which would actually match the architecture of the devices triggering this error iPad 4 in my case, but the other devices seem to all use 32-bit ARM CPUs with 64-bit floating point registers). Although since Javascript is managed, this would actually implies a deeper corruption of the Safari interpreter's memory state.

The bug itself might be triggered by the code generated during the TypeScript build (maybe by the uglifyJS step, which generates several variable names shadowing each other in quite complex ways).

Any change in angular (like an update) or in the set of packages bundled along it might change the code generated by uglifyJS in such a way that the Safari bug doesn't trigger anymore.
My advice to anyone hitting this bug would be to try and update angular or any other package, or to disable uglifyJS name mangling (at least for the function names).

**Comment by lemoinem** [comment]
PS: After further investigation, this can be reproduced in dev mode (therefore without name mangling)...
Back to square one...

**Comment by awerlang** [comment]
Reported to webkit: https://bugs.webkit.org/show_bug.cgi?id=180006

**Comment by oskvortsov-bmt** [comment]
I tried to reproduce this bug on IPad 4 and browsers(safari, chrome, firefox) no results. We have this bug in our project.

**Comment by AlvaHub** [comment]
I still face the same issue, after routing my Angular 4 app a few times either on Safari or Chrome on my iPhone I get the error:
Error: Uncaught (in promise): TypeError: this.router.serializeUrl is not a function. (In 'this.router.serializeUrl(this.urlTree)', 'this.router.serializeUrl' is 6.04722596e-316)

It doesn't occur on Android or desktop.

**Comment by awerlang** [comment]
Got a similar failure at another place (forms):

Message: `this.form.get is not a function. (In 'this.form.get(n.path)', 'this.form.get' is 6.480690937346189e-286)`

User agent: `Mozilla/5.0 (iPhone; CPU iPhone OS 10_3_3 like Mac OS X) AppleWebKit/603.3.8 (KHTML, like Gecko) Version/10.0 Mobile/14G60 Safari/602.1`

**Comment by dtslvr** [comment]
I got the same error in angular 5.1.1:
`Uncaught (in promise): TypeError: this.router.serializeUrl is not a function. (In 'this.router.serializeUrl(this.urlTree)', 'this.router.serializeUrl' is 1.50543731e-315)`

User agent: `Mozilla/5.0 (iPad; CPU OS 10_3_3 like Mac OS X) AppleWebKit/603.3.8 (KHTML, like Gecko) Mobile/14G60`

**Comment by AlvaHub** [comment]
What I did to overcome the problem, at least a workaround, was to call the router links inside a timeout function, and not directly on the html. 

//Timeout to prevent IOS bug
 redirect(path){ 
    setTimeout(() => {
         this.router.navigate([path]);
    }, 1);
  }

**Comment by milanffm** [comment]
I have the same Problem width angular 5.1.0. Solved it with @AlwaHub solution. But it would be better when it get fixed.
