### ISSUE TITLE
$injector of null when injecting downgraded ng2 services into ng1's run()

### ISSUE THREAD

**Issue by bdirito** [angular/angular#16767]
**I'm submitting a ...**  (check one with "x")
```
[ x ] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
A 
`Error: (SystemJS) Cannot read property 'injector' of null
is generated when a downgraded ng2 component is inserted as a di of an ng1 module's run() method. Ng1 components (that were not downgraded) are fine to inject. This also happens if the di is anywhere in the service's own di chain.

Looks to be the same as #10992. Opening new ticket though as that one was closed

**Expected behavior**
Downgraded Ng2 services should inject without issue - like ng1 services.

**Minimal reproduction of the problem with instructions**
https://plnkr.co/edit/fdOIZkgnVQubdx7fZQXu 

in app/main.ts there are two .run() methods that are commented out. If you comment them back in you will see the error in the console.

**What is the motivation / use case for changing the behavior?**
I am upgrading a ng1 app. Its too big for a rewrite.. Some parts of the code start intervals. These intervals prevent ng2 from ever stabalizing in a protractor environment. Thus I need to move the intervals outside the ng2 zone and so I want to inject NgZone into ng1 services (which are via chaining) injected into the ng1 module's run methods.

A possible workarround might be to not inject in the service's constructor but later at runtime. This however would be pretty ugly ...

**Please tell us about your environment:**
cat /etc/issue -> Ubuntu 16.04.2 LTS
emacs --version -> 25.1.2
npm --version -> 3.10.10
node --version -> v6.10.0
ionic [serve] --version -> 2.2.1 

* **Angular version:** 2.0.X
angularjs -> 1.6.1
angualr -> 4.1.2

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]
Chrome tested
 
* **Language:** [all | TypeScript X.X | ES6/7 | ES5]
Typescript & es5 tested

* **Node (for AoT issues):** `node --version` =   
n/a - using platform-browser-dynamic

**Comment by gkalpak** [comment]
This has been fixed in the new, static version of ngUpgrade (which is the recommended version to use for a while now). The old, dynamic vrsion has been deprecated.

In the static version, the generated AngularJS module (that contains the necessary providers to wire up the injectors) is [prepended to the rest of the AngularJS modules][1], thus its `config` and `run` blocks are executed first.

I doubt anyone is still affected by the broen behavior in th deprecated, dynamic version, but if they are, feel free to submit a PR making a similar change (i.e. prepending the generated module to the list of bootstrapped modules).

[1]: https://github.com/angular/angular/blob/b89e7c2cb76e8fe6bcd0b8b2293ca8eee308679a/packages/upgrade/src/static/upgrade_module.ts#L255
