### ISSUE TITLE
gulp validate-commit-messages processes all commits from master

### ISSUE THREAD

**Issue by bisubus** [angular/angular#16830]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**

When buffer limitation that causes #16829 is fixed, it becomes evident that `gulp validate-commit-messages` processes all existing commits from `master` when being run locally, down to `Initial commit`.

This results in error:

```
Examining 7544 commits between HEAD and master
INVALID COMMIT MSG: "Initial commit"
 => ERROR: The commit message does not match the format of "<type>(<scope>): <subject> OR revert: type(<scope>): <subject>"
Please fix the failing commit messages before continuing...
Commit message guidelines: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-commit-message-guidelines
```

**Expected behavior**

Only newer commits from currently checked out branch (HEAD) and `master` should be checked.

**Minimal reproduction of the problem with instructions**

```
git clone https://github.com/angular/angular
cd ./angular
npm i
gulp validate-commit-messages
```

```
git clone https://github.com/bisubus/angular
cd ./angular
npm i
git checkout fix-windows-symlinks-2
gulp validate-commit-messages
```

**Please tell us about your environment:**

Windows 7 x64
Node 6.10.3
NPM 3.10.10
git 2.9.0.windows.1

* **Angular version:** 4.2.0-beta.1

**Comment by gkalpak** [comment]
This doesn't indeed work as expected on Windows (but does work on other platforms). The reason is that on Windows `^` is the escape character, so the command `git log ... HEAD ^origin/master` is equivalent to `git log ... HEAD origin/master`, which essentially logs all commits.

On Windows, you have to escape the `^` (e.g. `git log ... HEAD ^^origin/master`). The easiest solution would be to use git's [double-dot range notation][1], which is an alias for the `^r1 r2` syntax and works correctly on all platforms:

```
git log ... origin/master..HEAD
```

[1]: https://git-scm.com/docs/gitrevisions#_dotted_range_notations
