### ISSUE TITLE
Can't set queryParams multiple times

### ISSUE THREAD

**Issue by kpudlik** [angular/angular#16881]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
`queryParams` stream from `Router` emits only the latest params even if we execute `router.navigate()` multiple times (previous queryParams are not emitted even if we have `queryParamsHandling` set to `'merge'`. So the console output is:
`{}`
`{ d: 1 }`

**Expected behavior**
`queryParams` should emit 4 times and the console output should be:
`{}`
`{ a: 1 }`
`{ a: 1, b: 1 }`
`{ a: 1, b: 1, c: 1 }`
`{ a: 1, b: 1, c: 1, d: 1 }`

**Minimal reproduction of the problem with instructions**

Look at `page.component.ts`. I execute `router.navigate()` 4 times to set query params for current path but only the latest param is going to be set. I provided Rx console logging subscription to show how it works now. 
https://embed.plnkr.co/ggDidxY6yyVktYXhgaja/

**What is the motivation / use case for changing the behavior?**

Setting default query parameters for page from multiple independent places "at the same time".

**Please tell us about your environment:**

- **Operating system:** macOS Sierra 10.12.4 (16E195)

* **Angular version:** 4.1.3

* **Browser:** all

Chrome
 
* **Language:** [all | TypeScript X.X | ES6/7 | ES5]
TypeScript 2.3

* **Node (for AoT issues):** -

**Comment by jasonaden** [comment]
It appears this behaves as expected. If you still feel there is an issue, please provide further details in a new issue.

<hr>

Because navigations are always async, you would need to wait for each navigation to succeed before running a new one. If you did that, the merge strategy should work. What's happening now is the new navigation is cancelling the old one and the query params you set never get applied, so there's nothing to merge.
