### ISSUE TITLE
possible bug with async pipe in *ngFor in ng-template when hide/show

### ISSUE THREAD

**Issue by ocarreterom** [angular/angular#16924]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**

The async variable used in `*ngFor` statement it's "reset" when used inside `ng-template` hidden/shown with `*ngIf`.

**Expected behavior**

To keep the previous state of the async variable after `ng-template` is hidden/shown.

**Minimal reproduction of the problem with instructions**

Steps following the demo:
1. Change the select value to 'drinks'
2. Select a drink
3. Remove the drink

Now the value selected is 'drink' but foods are displaying

Demo: http://plnkr.co/edit/Ax0v7UGVXBrAekQ8ZCBY

**What is the motivation / use case for changing the behavior?**

My concrete use case is something like the demo case.

* **Angular version:** 4.1.3

* **Browser:** All

**Comment by vicb** [comment]
Your question sounds like a support request.

Please use the issue tracker only for bugs and feature requests.

Use [gitter](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem) and [StackOverflow](http://stackoverflow.com/questions/tagged/angular) for support request.

**Comment by snemvalts** [comment]
To anyone that finds this later: 
Seems like the subscription is discarded when `*ngIf` on the parent is `false`, and reinstantiated when  `*ngIf` is `true`. Problem is, until no new data is sent, nothing is received by the subscriber and nothing is displayed. Fixed by piping the observable through `shareReplay`, to make sure that all new subscriptions get the last piece of data emitted.
