### ISSUE TITLE
AsyncPipe breaks change detection when emitting from ngOnInit of child component

### ISSUE THREAD

**Issue by piotrszymanski** [angular/angular#16921]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**

I have the following structure of components in my simple application:
* App
  * Container
    * Emitter

The App component shows an observable value using the async pipe: `{{ value | async }}`.
The Emitter component emits a message on said observable: `value.next('hello');`
The Container component simply shows the Emitter component.

`value` is an RxJs ReplaySubject. The message is emitted from the Emitter's `ngOnInit()` method. This causes an `ExpressionChangedAfterItHasBeenCheckedError` when the change detection cycle runs.

**Expected behavior**

The async pipe should be able to handle messages emitted at any time without causing the `ExpressionChangedAfterItHasBeenCheckedError`.

**Minimal reproduction of the problem with instructions**

See http://plnkr.co/edit/zcWwamXvuwUPubFHaxSX

Open the dev console to see the error.

**What is the motivation / use case for changing the behavior?**

If the observable was hooked up to directly modify a property in the parent component, then the error would be understandable. However, I think it should be the job of the async pipe to handle incoming messages in such a way as to update the view at the right time. Otherwise, this responsibility is shifted to the code that emits the message, and this code might not even know it is used together with Angular.

[Some comments](http://stackoverflow.com/questions/42190290/expression-has-changed-after-it-was-checked-when-child-component-emits-on-ngon) on StackOverflow suggest using `setTimeout()` as a workaround. I managed to solve it by wrapping the emission in `Zone.current.scheduleMicroTask()`, which is just a little bit nicer.

We encountered this problem when upgrading to Angular 4.1.3 from Angular 2.4.4, where it worked without any problems.

The problem also doesn't occur if the Emitter component is a child right under the App component (removing the Container component).

**Please tell us about your environment:**

* **Angular version:** 4.1.3

* **Browser:** Tested on Chrome 57.0.2987.133

 
* **Language:** TypeScript

**Comment by tytskyi** [comment]
@piotrszymanski the problem with your implementation is that the children affects parent when initializes. The children can affect only its own children when initializes. Otherwise it should be asynchronous task.

Imagine next structure: 

app -> container -> emitter -> h2

the whole app should be rendered from `app` to `h2` and stabilize, without affecting the state. 
Then if state changed by `emitter` - the sub-tree starting from `container` re-renders.

What you got - is you you changing the state during rendering (like in the middle of the process), when state is not yet stabilized. So that angular just helps you to spot the problem.

This is what i understand from the reproduction provided.

**Comment by bnfrnz** [comment]
Hi all, I'm getting the same error. 

I simply use `FirebaseObjectObservable` in my component and in my view use an async pipe ([like so](https://github.com/angular/angularfire2/blob/70367ce5273987caf008980618d9a7d2e363c610/docs/2-retrieving-data-as-objects.md#retrieve-data)), plus there are some *ngIf statements; example: `<img *ngIf="(userProfile | async)?.imgUrl"`.

Would any of you have a recommendation how to avoid the `ExpressionChangedAfterItHasBeenCheckedError` that I'm getting, specifically when reconnecting to the network (app goes from offline to online and displays the data for the first time)?

I've been reading dozens of threads with suggested workarounds such as `setTimeout()`. However, I have no event emitting child components or providers on which I could try those tweaks. I simply use async pipes for out-of-the-box AngularFire2 Observables. I'm new to Angular and to Observables. Am I doing it wrong? I'd be grateful for any tips/best practice as to how to properly bind, eliminating these `ExpressionChangedAfterItHasBeenCheckedError`.

**Comment by dovidweisz** [comment]
@bnfrnz would you be able to replicate the issue in a plunkr. I know it can be tedious and time consuming, but in the long run; adding examples to your issues make a great contribution to the community.
Dovid

**Comment by bnfrnz** [comment]
@dovidweisz thanks for responding! I'm quite swamped at the moment and won't be able to put something together right now. But when I was at it yesterday I found a solution that seems acceptable for now. Basically, I got rid of the `async` pipe and am always unwrapping the observables with `{ preserveSnapshot: true }` now. The error stopped occurring...

**Comment by ardeshirj** [comment]
Not sure if this is still an issue. However I had similar issue that I thought it was caused by async pipe, so I came across this async pipe issue.

In my case, the child component was emitting values asynchronous using EventEmitter to the parent components, and at some points the parent component would get the new state and send it down to the child component. However the async pipe was not receiving the new values that has been emitted from, but I could subscribe to the observable and see the new values. I thought it might related to async pipe but it turns out to be EventEmitter and changeDetection trick.

Thanks to this SO post [here](https://stackoverflow.com/questions/42190290/expression-has-changed-after-it-was-checked-when-child-component-emits-on-ngon), I learned EventEmitter constructor is accepting `isAsync` flag that indicate the values are being emitted async or not. According to the SO post:
>emitted values will be picked up on the next change detection cycle
This way changeDetection and async pipe works well together and component receives the new value.

I was hoping that I can find more information regarding `isAsync` flag in [Angular documentation](https://angular.io/api/core/EventEmitter#___isAsync), however there was no explanation regarding this flag 😞 . 

Hope this helps someone else you across this issue.

**Comment by vicb** [comment]
Could someone please create a repro for 5.x ?

**Comment by vicb** [comment]
Close as no feedback.
Please re-open with a repro on Angular 5.x if this is still an issue.

**Comment by ezequielzacca** [comment]
every time i encountered this error i solved it by piping a delay of 0 on the observable, i guess internally it uses settimeout
