### ISSUE TITLE
Material2 BrowserAnimationsModule must not import BrowserModule

### ISSUE THREAD

**Issue by maliksahil** [angular/angular#16949]
**I'm submitting a ...**  (check one with "x")
```
[ x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
Since BrowserAnimationsModule imports BrowserModule it is impossible to use BrowserAnimationsModule  in lazy loading or reusable libraries. It should take dependency on CommonModule not BrowserModule.

**Expected behavior**
We should be able to use reusable libraries such as BrowserAnimationsModule anywhere. Currently we cannot.

**Minimal reproduction of the problem with instructions**
Create an npm package that takes a dependency on BrowserAnimationsModule.
Use that package in another project - the other project already imports BrowserModule.
You'll see that you cannot re-import BrowserModule (which is expected).
However this prevents us from using BrowserAnimationsModule in either lazy loading or other npm packages.

**What is the motivation / use case for changing the behavior?**
To be able to use BrowserAnimationsModule in reusable code.

**Please tell us about your environment:**
Issue is in all angular environments.

* **Angular version:** 2.0.X
Angular version 4.1.3

* **Browser:** All

* **Language:** all

* **Node (for AoT issues):** `node --version` =   
v6.9.5

**Comment by MiszczProgramowania** [comment]
same issue

**Comment by matsko** [comment]
So if `BrowserAnimationsModule` is not used then any animation `@triggers` will fail to work. So you need to have animations in place. Using the Noop module to begin with should work, but that still downloads just about all the animation code anyway.

Unfortunately this won't get fixed in Angular 5.x, but later in 6.x+ there will be a mechanism in place for lazy loading animations. But this won't involve changing around `BrowserAnimationsModule`.

Closing for now, we will have info as to when the animation improvements come around for 6.x+.
