### ISSUE TITLE
Improve type checking to include checking model binding

### ISSUE THREAD

**Issue by 100cm** [angular/angular#16952]
> import {Component} from "@angular/core";
> import {CommonService} from "../service/common.service";
> @Component({
>     selector: 'testb',
>     template: '<div><button (click)="aa()">输出</button> <button (click)="bb()">切换</button>' +
>     ' <input [(ngModel)]="myh.n" #item (change)="cc(item.value)"/></div>',
> })
> export class TestB {
> 
>     constructor(private commonService: CommonService) {
> 
>     }
> 
> 
>     private mynumber: number;
> 
>     private myh: myObjct = new myObjct(3);
> 
>     aa() {
>         console.log(this.commonService.hello)
>     }
> 
>     bb() {
>         this.commonService.hello = "test  b hello"
>     }
> 
>     cc(v: number) {
>         this.myh.n =v
>         console.log(this.myh)
>        console.log( this.myh.n)
>         console.log(JSON.stringify(this.myh))
>     }
> 
> }
> 
> class myObjct{
>     private _n:number
> 
>     constructor(n: number) {
>         this._n = n;
>     }
> 
>     get n(): number {
>         return this._n;
>     }
> 
>     set n(value: number) {
>         this._n = +value;
>     }
> }

i must use +value to make my type to be number .or it will be string.

**Comment by trotyl** [comment]
`[()]` syntax is just a syntax sugar of **property binding** and **event binding**. The generalized problem here is that Angular does not provide type checking for events, nothing special to `ngModelChange`.

You should fill the issue template as a feature request, but this may not be possible for current mechanism, as it's just string comparison for event names.

**Comment by icepoint0** [comment]
i think when angular 2  set a property of object , its will not check the type, how to check this ?

**Comment by trotyl** [comment]
In the binding `(ngModelChange)="myh.n = $event"`, `myh.n` is the property you want to bind to, it's typed properly, but `$event` is always declared as `any`.
Theoretically the type of `$event` may be determined by the generic type of `EventEmitter`, but there may still be other conditions, like native DOM events and events provided by other `EVENT_MANAGER_PLUGINS`.
What's more for `ngModelChange` is that, there is no generic type used in the `EventEmitter` (in [ng_model.ts](https://github.com/angular/angular/blob/master/packages/forms/src/directives/ng_model.ts#L124)), the expected declared type it's determined by the `NG_VALUE_ACCESSOR`, not the `NgModel`.

So that's why I think this request is way to hard to implement this. Still, this is just my point of view.

**Comment by trotyl** [comment]
Possibly relates to https://github.com/angular/angular/issues/17483

**Comment by alxhub** [comment]
I'm going to close this as resolved, actually.

In Ivy under `strictTemplates`, the type of `$event` is correctly determined by the generic type of `EventEmitter` of the output in question. However, #13721 will likely need to be resolved as well, to truly solve the problem described in this issue.
