### ISSUE TITLE
Need native form validation alert without validation attribute in html template.

### ISSUE THREAD

**Issue by grapgrap** [angular/angular#17036]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => search github for a similar issue or PR before submitting
[x ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
If I show native form validation alert, I write form validator through `formBuilder` in `*.ts` file. Nevertheless, I write `ngNativeValidate` and validation attribute( `required`, `pattern`... etc.) in `*.html` again.

And then, If I change form validation, I change ts and html. It is too uncomfortable to do so.
**Expected behavior**
If I write form validator through `formBuilder` in `*.ts file` and write only `ngNavtiveValidate` in `*.html`, I wish to show native form validation alert.

I'm sorry I'm short of English.

**Comment by kara** [comment]
If I'm understanding correctly, you'd like to use native form validation with reactive forms without using native validation attributes (e.g. required).  This is currently not possible because native validation requires the attributes to work.  One option is for reactive forms to apply these attributes to the DOM for built-in validators automatically. We have an existing proposal for that [here](https://github.com/angular/angular/issues/9121), so let's track it in that issue.
