### ISSUE TITLE
RouterLink prevents middle button click event bubbling

### ISSUE THREAD

**Issue by artaommahe** [angular/angular#17067]
*I'm submitting a ...**  (check one with "x")
```
[ x ] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
Added to element `[routerLink]` directive prevents middle mouse button click event catching by `(click)` handler.

**Expected behavior**
Event bubble as usual.

**Minimal reproduction of the problem with instructions**
http://plnkr.co/edit/U5jrhOp8YJJAqzrFuJQs?p=preview

- run
- open console
- do regular click on link and see `CLICKED` in console
- do middle button click and see nothing in console

**What is the motivation / use case for changing the behavior?**
Currently it's hard to handle link middle mouse click (i have toasts that should be closed on any click event and currently cant properly handle this case)

* **Angular version:** 4.1.3

* **Browser:** Chromium Version 58.0.3029.110 Built on Ubuntu , running on Ubuntu 16.04 (64-bit)

**Comment by dloukadakis** [comment]
This is totally unrelated to routerLink as click event wont be triggered anymore for non primary button clicks.

For more info you can read:
https://developers.google.com/web/updates/2016/10/auxclick

**Comment by artaommahe** [comment]
@dloukadakis hm, but current implementation on RouterLink directive allow regular `click` event to bubble up and for some reason prevent bubbling for middle click only that looks strange. Also when there is will be new `auxclick` event this behavior  may remain the same (blocking event bubbling).

**Comment by dloukadakis** [comment]
I already explained why it doesn't work u can try replacing routerLink with href="#" and see it will still not be triggered as browsers don't trigger this event anymore for middle click, it used to be triggered 7 months ago before it was changed.

The routerLink directive just does a `return true` if button is not primary mouse button only because it was made to do so a year ago that click event was still being triggered for non primary button clicks (and probably is kept for compatibility) also return true in click listener means to not prevent default event so it simply has no effect on anything as the events will still be propagated.

**Comment by artaommahe** [comment]
@dloukadakis here is new plnkr http://plnkr.co/edit/FZt98DpfkG8qjTzJToMk?p=preview just try to handle middle button click on link element with attached `RouterLink` directive. I dont see any way for this.

**Comment by artaommahe** [comment]
Hm.. my mistake, `return false` fires not for middle click.

**Comment by artaommahe** [comment]
My bad, this issue is not related to ng, i just need to handle `mousedown`/`mouseup` events instead of `click`.

**Comment by dloukadakis** [comment]
Returning false does not stop propagation only default action.
