### ISSUE TITLE
Change detection not triggered after Http call

### ISSUE THREAD

**Issue by fatsu** [angular/angular#17089]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
Change detection not triggered after Http calls. View is not updated.
We have several views that don't refresh until Change-detection is manually triggered (keypress, mouse-click) by other components.

As I was unable to reproduce this with plunkr, I included a link to a github repo for reproduction. The new value is logged to the console but the view is not updated. Not even after mouse click of key-strokes.

I first thought this was related to the migration from v2 to v4 but I was able obtain similar behaviour from a vanilla angular-cli project.

Issue which describes similar problem: https://github.com/angular/angular/issues/15971 (closed)

**Expected behavior**
Change detection to be triggered and the view to be updated. 

**Minimal reproduction of the problem with instructions**
https://github.com/fatsu/ng-15971

Unable to reproduce using plunkr.

**Please tell us about your environment:**
Angular-CLI 1.0.6 on windows, running server with 'ng serve'.

**Angular version:** 4.1.3

**Browser:** [Chrome 58 | Firefox 45 | IE 11]
 
**Language:** [TypeScript]

**Comment by tytskyi** [comment]
@fatsu this is expected behavior. Quote that you provide: 

> Angular executes template expressions after every change detection cycle. Change detection cycles are triggered by many asynchronous activities such as promise resolutions, http results, timer events, keypresses and mouse moves.

It is correct for components with default change detection strategy. 

For the component with `ChangeDetectionStrategy.OnPush` change detection will be triggered only (AFAIK) when input changes, when user event happens (click etc), when children component fires event emitter. 

You are changing component state from the inside of component - this will not trigger change detection.
You are not supposed to use `ChangeDetectionStrategy.OnPush` on "containers" components. But it's ideal for components that only have inputs/outputs - but do not have their own internal state.

**Comment by fatsu** [comment]
@tytskyi Ok, thank you for clearing this up.
