### ISSUE TITLE
Angular directive overwrites its input attribute

### ISSUE THREAD

**Issue by pmilic021** [angular/angular#17138]
**I'm submitting a ...**  (check one with "x")
```
[ x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**

When I create img element with src (that has to be evaluated) and add directive to that img element which has as its @Input src, it will rewrite it as ng-reflect-src, and img element will no longer have src attribute (therefore no picture will be shown). If the src attribute was fixed, this wouldn't happen.

**Expected behavior**

Both ng-reflect-src and src should be present on the element.

**Minimal reproduction of the problem with instructions**

Here is plnkr: https://plnkr.co/edit/5AjZPeyEfd6IOqxQp3kq?p=preview

**What is the motivation / use case for changing the behavior?**

As described, one use case is when directive has to utilize its elements src attribute. My concrete use case was image onclick opening popup with large image.

**Please tell us about your environment:**

OsX Sierra, webstorm, npm

* **Angular version:** 2.0.X

4.1.2

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

 I tried only on Chrome Version 57.0.2987.133 (64-bit)

* **Language:** [all | TypeScript X.X | ES6/7 | ES5]
all

* **Node (for AoT issues):** `node --version` =

**Comment by vicb** [comment]
This is not a bug but the way Angular works.

- Any bound property are consumed by directives and not passed to the DOM element,
- `ng-reflect-src` is a dev helper only. Because Angular will bind the property (and not the attribute) you do not see the updated attribute when inspecting the page source. The `ng-reflect-src`is not added in production.

There are multiple ways to solve your issue according to what you want to do:
- inject the value of the attribute in your directive `constructor(@Attribute('src') src: string) {}` - static string,
- add a `@HostBinding` to the directive property `@Input() @HostBinding() src: string;`
- ...

**Comment by pmilic021** [comment]
Alright, thanks! One more question though, why does it consume `src` only when it has evaluated value (i.e. `src="{{imgUrl}}"`) but not when it is hardcoded value (i.e. `src="http://some-pic.com/link123"`)?
