### ISSUE TITLE
aoi: tabbed code block style updates

### ISSUE THREAD

**Issue by sjtrimble** [angular/angular#17217]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => search github for a similar issue or PR before submitting
[x] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
Tabs feel bare on code blocks relative to other title code block sections.
![image](https://cloud.githubusercontent.com/assets/2958442/26807992/d7614c20-4a0e-11e7-9b93-ad594e28a251.png)

**Expected behavior**
Add more defined visual styles to match other titled code block sections

**Minimal reproduction of the problem with instructions**

- Go to https://aio-staging.firebaseapp.com/tutorial/toh-pt4#review-the-app-structure
- Scroll down to code files section

**Comment by jenniferfell** [comment]
Related - make title area of code snippets the same visual impact/style for single-example and tabbed examples: https://github.com/angular/angular/issues/23984

Related - soften visual impact of code area titles so that they don't overwhelm overall page structure (subheadings): https://github.com/angular/angular/issues/23982

**Comment by JeanMeche** [comment]
I'm closing this issue as we're deprecating AIO.
