### ISSUE TITLE
aio: TOC active place should highlight upon landing on page

### ISSUE THREAD

**Issue by sjtrimble** [angular/angular#17219]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
Active table of content item does not highlight until a scroll event occurs.

Upon initial load of page:
![image](https://cloud.githubusercontent.com/assets/2958442/26808132/b099f2a8-4a0f-11e7-8740-d4bb2e763449.png)

Upon scroll down:
![image](https://cloud.githubusercontent.com/assets/2958442/26808139/be4aa67c-4a0f-11e7-83e2-2093526880a6.png)

**Expected behavior**
Initial section should be highlighted visually immediately upon landing on the page.

**Minimal reproduction of the problem with instructions**

- Example: https://aio-staging.firebaseapp.com/guide/setup
- Scroll down: See TOC title header 'Setup for local development' light up only upon scroll
- Scroll up: See TOC title header no longer visually identified as active

**Comment by gkalpak** [comment]
The reason it is not highlighted, is because it is not the active section :grin: (based on the criteria we have set). If you scroll [directly to that section][1] it gets highlighted correctly. This is more of an issue with scrolling (and top offsets).

It would be fixed by #17123 ([demo][2]), but now that the header placing is about to change, more fixing might be needed :smiley:

[1]: https://aio-staging.firebaseapp.com/guide/setup#setup-for-local-development
[2]: https://pr17123-afbb0926378f921e381a47ea1ce7a61f92bef33d.ngbuilds.io/guide/setup
