### ISSUE TITLE
Animation common scenario problem

### ISSUE THREAD

**Issue by Bretto** [angular/angular#17349]
**I'm submitting a ...**  (check one with "x")
```
[X] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**

The animation is not triggered

**Expected behavior**

The animation should be triggered

**Minimal reproduction of the problem with instructions**

http://plnkr.co/edit/aYx8BUSwvUHzJXI0Vaqg?p=preview

**What is the motivation / use case for changing the behavior?**

With the shiny new 4.2.0-rc2 animations it should be simple to do a transition between pages, but as you guest it I can't find a way to do it ! I have create this plunkr http://plnkr.co/edit/aYx8BUSwvUHzJXI0Vaqg?p=preview to show my struggle... I think the issue is because I am using the same component in my routes but this is such a common scenario that there must be a way to get this to work simply and so the bug report (It could be my ignorance though, let me know, but I have ask around and was recommended to log an issue...)

**Please tell us about your environment:**

os: linux x64

* **Angular version:** 2.0.X

@angular/cli: 1.1.1
@angular/animations: 4.2.0-rc.2
@angular/common: 4.2.0-rc.2
@angular/compiler: 4.2.0-rc.2
@angular/core: 4.2.0-rc.2
@angular/flex-layout: 2.0.0-rc.1
@angular/forms: 4.2.0-rc.2
@angular/http: 4.2.0-rc.2
@angular/material: 2.0.0-beta.6
@angular/platform-browser: 4.2.0-rc.2
@angular/platform-browser-dynamic: 4.2.0-rc.2
@angular/router: 4.2.0-rc.2
@angular/cli: 1.1.1
@angular/compiler-cli: 4.1.3
@angular/language-service: 2.4.10

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

 Chrome
* **Language:** [all | TypeScript X.X | ES6/7 | ES5]
TypeScript X.X

* **Node (for AoT issues):** `node --version` =   
node: 7.0.0

**Comment by mlc-mlapis** [comment]
@Bretto ... I think that the problem is related to the route
```
{
       path:"page/:pageId",
       component: PageComponent,
       ...
}
```
and how Angular instantiates the component `PageComponent` related to that route. Actually the components is instantiated only for the first turn ... `/page/x`. For any following turn `/page/y`, `/page/z`, ... the instance is reused and not created again. The re-initialization for the case in just on you (subscribing to `.params` observable on `ActivatedRoute` and running your code for each change of the param) and you can't use `OnInit` hook or `constructor` ...

So I think that this case is not about switching routes ... because you are still on the same route ... and then also animation between two routes is out of play if you are still on the same route.

**Comment by Bretto** [comment]
@mlc-mlapis @matsko Have a look at this one: http://plnkr.co/edit/iUPIWYbiQ9fP7bCmrgAj?p=preview
Now we have the same component but 2 hard coded url in the routes and the animation works...
(IMHO) I think there is an issue here that needs a solution. Url with params is the way, not hardcoding all the routes to have the transition working...

**Comment by mlc-mlapis** [comment]
Yes, the plunker with hardcoded routes has to work as expected because there are not used params.

New set of annimation features is just hot topic and I didn't have enough time to dive in yet. But I am sure that Mathias was aware of that case and there is built in solution already.

Mathias, can you look at the issue here and comment the situation? @matsko Thanks.

**Comment by Bretto** [comment]
Additionally what about this ?
```
routerCanReuse(){
    return false;
  }
```
I was thinking that this was the way to force a new instantiation of the component and thus force the animation, but I can't get it to work... I must be missing some secret sauce somewhere.  Thank you

**Comment by Bretto** [comment]
I have updated the plunkr to 4.2.2 and the issue is the same

**Comment by mlc-mlapis** [comment]
Hmm, I think that for this case ... subscribing to `params` a bit different config has to be used ... we need to wait for Mathias's response.

**Comment by Bretto** [comment]
Yes we need the help of someone knowledgeable on this very hot subject.

**Comment by matsko** [comment]
There are two problems here:

1) The state of the route isn't changing (because `animation: Math.random()` is going to be the same value each time. This is easy to work around since you can just grab the URL value directly:
```ts
  prepareRouteTransition(outlet: RouterOutlet): string | null {
    try {
      //page1 or page2 or whatever
      return outlet.activatedRoute.snapshot.url.join("");
    }
    catch(e) { return ""; 
  }
```
2) Since the route component `PageComponent` is the **same component**, the router will automatically reuse it. @vicb @jasonaden is this a bug? Shouldn't this be destroyed/created each time unless a custom reuse strategy is used?

So what's going on here is that the route is being reused (no new view is being attached / removed).

**Comment by Bretto** [comment]
@matsko Thank for the update.

**Comment by matsko** [comment]
Alright here's a working plunkr of your app:
http://plnkr.co/edit/33DeIY9JW6HoTXnYAyGp?p=preview

The problem here was that since the route definition was the same (same component different URL) the router just updated the content of the page. Therefore to make it animate you need to create your own `RouteReuseStrategy` which forces the route to always be reloaded.

The next thing is that the animation configuration state value is still going to be the same. Therefore your component router state preparation function needs to return a unique value based on the URL. What I added in the plunkr was a way that it can get ahold of the `pageId` value and return that.

All in all there is nothing wrong with the router nor animations here. You just need to do some extra work to get it to be operational.

**Comment by mlc-mlapis** [comment]
@matsko Yeap, ... custom `RouteReuseStrategy` is the key. I thought about but didn't finished the idea to the end. Thanks for your explanation. It would be very helpful certainly for many others here.

Maybe it would be a good idea to add this case explicitly to `angular.io` docs because I suppose many similar questions in future.

**Comment by Bretto** [comment]
@matsko Thanks for your time, but there may still be a deeper issue here... 
I have added your working example to my project and it didn't work. 

After investigation I think that the __problem__ was that the animation in my project was __not at the root but in a child component__. 
I have created a [plunkr ](http://plnkr.co/edit/QuxPdDVWDA9K8Q34BToU?p=preview) to illustate the issue. 

As you can see the components are being __re-created__ and the __animation configuaration__ is reflecting the current page, but __we have lost all the transition__. Am I still doing something wrong here ? Thank you for your ongoing support.
