### ISSUE TITLE
aio: fix footer overlap on smaller screen sizes

### ISSUE THREAD

**Issue by sjtrimble** [angular/angular#17341]
May need input from @IgorMinar on whether or not this is an issue as it might be a design preference. I believe this to be an acceptable solution for mobile view.

**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => search github for a similar issue or PR before submitting
[x] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
<img width="916" alt="screen shot 2017-06-08 at 11 16 16 am" src="https://user-images.githubusercontent.com/2958442/26943906-ff9b0148-4c3b-11e7-8bb5-9fbb74ca99f1.png">

**Expected behavior**
Footer should collapse to be seen fully (without disrupting the TOC) when screen is large enough (more than 600px) to fit the content.

**Minimal reproduction of the problem with instructions**
- Go to https://aio-staging.firebaseapp.com/tutorial/toh-pt2#the-road-ahead
- Scroll to the bottom
- Resize window to 1000px

**Comment by IgorMinar** [comment]
I can't reproduce this any more. If you still can, please file a new issue and document repro steps. thanks

**Comment by gkalpak** [comment]
The "issue" still exists (and the repro steps in the description still work).
(Whether we should change it or is fine as it is, is another story :grin:)

Currently:
![wide-footer](https://user-images.githubusercontent.com/8604205/33313885-abb92f60-d434-11e7-9961-5af9da7d22e8.png)

Proposed:
![narrow-footer](https://user-images.githubusercontent.com/8604205/33313898-b7b917da-d434-11e7-93a5-9a00a78c3102.png)

TBH, making it narrow looks likd of funny (with long ToC), but maybe that's just because I am used to the current layout.
