### ISSUE TITLE
Inconsistent `ngIf` vs interpolation expression behaviour - former throws `ExpressionChangedAfterItHasBeenCheckedError` error

### ISSUE THREAD

**Issue by christianacca** [angular/angular#17347]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
```

**Current behavior**
Changing a property on an object supplied as an`@Input` within an `ngOnChanges` lifecycle hook will  throw `ExpressionChangedAfterItHasBeenCheckedError` error in specific circumstances.

Specifically this error is thrown when a component template has an `*ngIf` expression whose value changes as a consequence of the update made by the `ngOnChanges` method of a child component.

In contrast: replace the `*ngIf` in the component template with an interpolation expression and the error is no longer thrown.

**Expected behavior**

There should be no difference between using an `*ngIf` and an interpolation expression in a template when a child component happens to change an object supplied as an `@Input` within it's `ngOnChanges` method.

Ideally, the `ExpressionChangedAfterItHasBeenCheckedError` error would not be thrown at all thus allowing a child component to safely change properties of object supplied as an `@Input` within it's `ngOnChanges` method.

**Minimal reproduction of the problem with instructions**

See the following plunker: https://plnkr.co/edit/cdh9ryNFqOnmnHaN8rl1?p=preview

With the browser console window open, click the button labelled 'Change' and observe the `ExpressionChangedAfterItHasBeenCheckedError` error logged.

In contrast see the same (working) example where the `ngIf` expressions is replaced with an interpolation expression: https://plnkr.co/edit/mtogqdbHmaSBHlwQZenL?p=preview

**What is the motivation / use case for changing the behavior?**

Predicable / consistent behaviour between `*ngIf` and interpolation expression.

**Possible related issues**

Maybe the following issue is related: https://github.com/angular/angular/issues/15634

* **Angular version:** 4.1.3

* **Browser:** [Chrome latest | IE 11 | Edge ]
 
* **Language:** all

**Comment by Toxicable** [comment]
Works fine here
https://plnkr.co/edit/nP4SjG9t5ImWp37DqLkB?p=preview

**Comment by christianacca** [comment]
Hi @Toxicable, you've changed the plunker a little bit. In your example, try changing 'New age' to 22 and then click the 'Change' button - you'll see the same `ExpressionChangedAfterItHasBeenCheckedError` error thrown

**Comment by alexzuza** [comment]
https://plnkr.co/edit/KbDN5IGSUeodT5zzV3ZE?p=preview

**Comment by christianacca** [comment]
Hi @alexzuza, you've deferred the update to the next turn of javascript - yup that is a *workaround* to the problem. However, that does not resolve the inconsistency between the behaviour of `ngIf` and an interpolation expression running in the same JS turn. That's the problem I'm reporting.

**Comment by christianacca** [comment]
Hang on a moment. Maybe your workaround is not resulting in the code to run on the next. Yes of course the code is now running asynchronously, but maybe still in the same JS turn. Care to comment?

**Comment by alexzuza** [comment]
You should abide by the unidirectional data flow. You're updating value in child component during change detection cycle after parent view with this value was checked.

**Comment by ccrowhurstram** [comment]
Yes, I agree but it still doesn't explain the inconsistent behavior that I'm reporting here.

**Comment by ccrowhurstram** [comment]
@alexzuza, one point to note about keeping to unidirectional data-flow: 

AFAICT the `ngOnChanges` code is running in the same turn as the button click handler that triggers the method to be called. On that basis, it should be OK to make changes to an object supplied as `@Input` within the `ngOnChanges` without violating the unidirectional data-flow principal.

This seems to be supported by the following statement from angular [training material](http://blog.angular-university.io/angular-2-what-is-unidirectional-data-flow-development-mode/#whatflowofdataarewereferringto):

> For example: If we trigger an event handler such as for example a button click handler, we can modify the data of the application as much as we want at any level of the component tree. But once the click handler code returns, the control is yielded back to the Angular framework.

**Comment by Toxicable** [comment]
No you are violating the unidirectional data-flow principal, you're changing the value of person during Change Detection (CD), this is your issue. Since the child is changing the value of person during CD when the second round of CD from debugging comes it rechecks that expression you got there and sees that it's been changed by something, this is why it throws the error, because your changing data in the parent directly from a child during a CD run.

**Comment by ccrowhurstram** [comment]
OK, fair enough, but still leaves the inconsistent behavior that I'm reporting as a bug

**Comment by chuckjaz** [comment]
@ccrowhurstram: As explained by @Toxicable above, https://plnkr.co/edit/cdh9ryNFqOnmnHaN8rl1?p=preview violates the unidirectional data-flow directly and is correctly reported as an error in design mode.

The second example, https://plnkr.co/edit/mtogqdbHmaSBHlwQZenL?p=preview, still violates the principle but in a way we tolerate because of the order change notifications are sent. We don't see this as a change because the change occurred before the view phase of change detection.

The assertion that these should be consistent is understandable but not something we promise nor can we guarantee because we must do the change detection in phases. There are, and must be, more limitation on what changes can be tolerated when deciding the structure of the template (that is, which templates are included in the render and how the templates are composed through projection) than when the view are being rendered (such as when interpolations are evaluated).
