### ISSUE TITLE
Applying the same stagger animation on multiple containers throws error

### ISSUE THREAD

**Issue by MrCroft** [angular/angular#17418]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report
```

**Current behavior**
Having more than one (of the same) container on which we apply the same stagger animation to animate it's children, throws error `query(":enter")` returned zero elements. (Use `query(":enter", { optional: true })`

**Expected behavior**
It should apply the stagger animation on each of the containers' children, each container independent of one another. Shouldn't it?

**Minimal reproduction of the problem with instructions**
https://plnkr.co/edit/kVB10OKKUQIDHPiZGKUD?p=preview

* **Angular version:** 4.2.1

* **Browser:** all

**Comment by matsko** [comment]
The problem here is that `:enter` only works on the container that is being inserted. Which means that **everything** inside of it could be considered an enter. So using an `:enter` query inside of an `:enter` transition is not allowed. You need to query by selecting the elements you want by using a regular query instead.

I have been meaning to have the animation engine throw an error when this happens.
