### ISSUE TITLE
aio: "get started" and "learn more" buttons not working on FF 

### ISSUE THREAD

**Issue by Foxandxss** [angular/angular#17448]
Those buttons on the home page doesn't work at all in FF. Also I noticed in Chrome that only a specific region of it does the click while the other doesn't.

**Comment by IgorMinar** [comment]
The problem is that we have a `<a>` tag nested in `<button>` - this html code is invalid. [According to MDN](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/button
), the only valid child of a button element is "[phrasing content](https://developer.mozilla.org/en-US/docs/Web/Guide/HTML/Content_categories#Phrasing_content)", which does include `<a>` but only if it's not interactive ([spec](https://html.spec.whatwg.org/multipage/form-elements.html#the-button-element
)). 

We have two options to resolve this:

- remove the need for the button element
- wrap the button element into anchor (the opposite of what it is now)

Both of these require CSS changes, so I'm going to leave this up to @sjtrimble or @gkalpak to handle.

**Comment by fatters** [comment]
I may as well piggy back off this issue. Using FF 53.0.3, none of the footer links are clickable either.

**Comment by gkalpak** [comment]
@fatters, this is a different issue. Can you open a new bug report, please?
