### ISSUE TITLE
Regression caused by the min/max validators in 4.2.0

### ISSUE THREAD

**Issue by rusev** [angular/angular#17491]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report
[ ] feature request
[ ] support request
```

**Current behavior**
Version 4.2.0 introduces [min and max validators](https://github.com/angular/angular/commit/81925fa66d2c930f68d3b6dd084c954ea1bab6b6). 
The issue arises when a custom component has `min` | `max` input property and that component implements `ControlValueAccessor` and is registered as a validator (custom validation logic requirements).

When the user wraps that component in a `FormGroup` the default `min|max` validators are always triggered and there is no way of instructing them that my component `min, max` properties are not meant to be validated.

This behavior will be also true if a custom component (which implements `ControlValueAccessor`) has input property that matches any of the built-in [validator directives](https://github.com/angular/angular/blob/master/packages/forms/src/directives/validators.ts). For example if my custom component has input properties such as: min, max, minlength, maxlength etc.

**Expected behavior**
There should be a way to suppress Angular validator directives for such properties if required by the component author.

**Minimal reproduction of the problem with instructions**
Prior version 4.2.0 - http://plnkr.co/edit/QDoXhau2e1SuAuJ7tOwk?p=preview - no validation errors
With version 4.2.0 - http://plnkr.co/edit/gqtdQqL7DlY0UC1H6M0R?p=preview - validation errors

**What is the motivation / use case for changing the behavior?**
There should be mechanism for preventing Angular validator directives for input properties that matches built-in validation directives. These input properties might have a bit different meaning in the component context.

* **Angular version:** 4.2.0

**Comment by tytskyi** [comment]
Good example on why some features should not be bundled into the core but go as a separate package.

**Comment by trotyl** [comment]
Seems that every new `directive`/`pipe` would be a regression then.

**Comment by kemsky** [comment]
Generic problem, we can not override directives at all. Imagine you are happily using forms module, but want to override `required` validator - you can not... One way is to create your own `my-required` or something. Angular could change selectors to use `:not(NgDisableRequired)`, but it is not elegant either.

**Comment by tytskyi** [comment]
Yep, additional attributes for turning off behaviour looks not friendly and will escalate the mess quickly.

As the current solution i propose to remove exports for `min/max` directives ASAP and any mentions in the docs. While not too late. But hold their code and then export them within new solution for directives scoping. (I understand it is a bit radical)

My further proposal is to separate things that are not essential out of core, OR at least out of Forms Module. 
And scope each directive under named module, like `ValidatorRequiredModule` (alternatively under npm package `@angular/contrib` with `ValidatorRequiredModule`).

Since only NgModule is true scope for the directives. This will unlock to "override" logic of directives that match names of standard html attributes and generally be more flexible with directives that are shipped with angular itself.

The downside of this would be frustration from existing users (I used to import only FormsModule, now i need to import 3 modules in order to use standard browser functionality!!! RAGE RAGE  RAGE  etc!)

Related issue that suffer from limitation of overriding directives: 

- https://github.com/angular/angular/issues/17296 - email validator - something that developers expect regardless of conforming to html5 spec

- https://github.com/angular/angular/issues/17485 - feat. request for adding delay timeout `routerLink` - doesn't look like good addition to the core, but would be cool to use different directive under the same name

**Comment by kara** [comment]
For now, we are going to remove the exports for the min/max validator directives, as their addition is a breaking change. At the least, we should wait to add them until major but we will have further discussion about what the best solution is going forward for all validators.

**Comment by saxicek** [comment]
@kara Can the discussion regarding the validator directives be followed somewhere? I need to make a decision whether to wait for Angular solution or to implement something myself. Thank you!

**Comment by henev** [comment]
Will min/max be introduced into the upcoming major version 5 or should we wait for the 6?

**Comment by danwulff** [comment]
@IgorMinar @kara Why are these not available in 5.0? (I'm currently using 5.0.2)
I was expecting min / max directives to be available as validators (template forms) after 4.x. Are they supposed to be available? Should I open a new issue? Thanks.

**Comment by Toxicable** [comment]
@danwulff it was never said they would be available for v5
They are and have been available to ReactiveForms but if the directives were re-implemented as they were before they'd cause a regression again, they need to be renamed or a another strategy needs to be thought of before doing this.

**Comment by JaapMosselman** [comment]
But the Angular Upgrade Guide is mentioning this for migrating from 4.4 to 5.0: 

> If you created a custom form control with min and max input properties, you will need to adapt to the new behavior by renaming them or using the native validators

Seems to be wrong?

**Comment by IgorMinar** [comment]
@StephenFluin can you please update the guide?

**Comment by cexbrayat** [comment]
@IgorMinar the plan is to reintroduce the directives in a future major update?

**Comment by Maximaximum** [comment]
So, we're now having angular 5.1.0, but the min and max validator directives are still not available. Is there going to be a fix for this one day? :)

**Comment by Maximaximum** [comment]
BTW, a possible solution for this issue might be to use this selector instead, so that the directives work solely for an `<input>`: `input[min][formControlName],input[min][formControl],input[min][ngModel]`

**Comment by Maximaximum** [comment]
Actually, it can be even more specific like: `input[type=number][min][formControlName],input[type=number][min][formControl],input[type=number][min][ngModel]` :)
