### ISSUE TITLE
Animation common scenario problem with child route

### ISSUE THREAD

**Issue by Bretto** [angular/angular#17517]
**I'm submitting a ...**  (check one with "x")
```
[X] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**

The animation is not triggered

**Expected behavior**

The animation should be triggered

**Minimal reproduction of the problem with instructions**

http://plnkr.co/edit/QuxPdDVWDA9K8Q34BToU?p=preview

**What is the motivation / use case for changing the behavior?**

__Note:__
@matsko, @mlc-mlapis Have already contributed to this issue, this is a follow up of as it was closed: https://github.com/angular/angular/issues/17349

With the shiny new 4.2.0-rc2 animations it should be simple to do a transition between pages, but as you guest it I can't find a way to do it ! I have create this plunkr http://plnkr.co/edit/QuxPdDVWDA9K8Q34BToU?p=preview to show my struggle... I think the issue is because I am using a child route but this is such a common scenario that there must be a way to get this to work simply and so the bug report (It could be my ignorance though, let me know, but I have ask around and was recommended to log an issue...)

**Please tell us about your environment:**

os: linux x64

* **Angular version:** 2.0.X

@angular/cli: 1.1.1
@angular/animations: 4.2.0-rc.2
@angular/common: 4.2.0-rc.2
@angular/compiler: 4.2.0-rc.2
@angular/core: 4.2.0-rc.2
@angular/flex-layout: 2.0.0-rc.1
@angular/forms: 4.2.0-rc.2
@angular/http: 4.2.0-rc.2
@angular/material: 2.0.0-beta.6
@angular/platform-browser: 4.2.0-rc.2
@angular/platform-browser-dynamic: 4.2.0-rc.2
@angular/router: 4.2.0-rc.2
@angular/cli: 1.1.1
@angular/compiler-cli: 4.1.3
@angular/language-service: 2.4.10

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

 Chrome
* **Language:** [all | TypeScript X.X | ES6/7 | ES5]
TypeScript X.X

* **Node (for AoT issues):** `node --version` =   
node: 7.0.0

**Comment by matsko** [comment]
The problem here seems to be that `MainComponent` is getting recreated every time a route changes due to the fact that you have two router-outlets. `:enter` and `:leave` will **always** be the topmost containers that are inserted and removed on the application. In this case the `<my-main>` component is being inserted each time by the topmost router-outlet and that's why `:enter` is returning zero results.

The child router thing here is what's causing your animation not to work. You can either reprogram your code to not cause a toplevel route change (only get the inner child to fire) or keep the existing logic and have the upper router call the inner router's animation code to fire once it is instantiated. The only downside with this approach is that `:enter` and `:leave` will not work because they are already assigned to the parent element(s) (in this case the `my-main` component).

Unfortunately there's another animation bug (PR = #17777) that's causing a bug for this to happen. I'll update this [plnkr](http://plnkr.co/edit/D5Ld5xTFc8KlHiya5mkb?p=preview) once that goes in,.

**Comment by Bretto** [comment]
Ok thank you for the update, I am looking forward to the best practice for this common scenario :+1:

**Comment by Bretto** [comment]
@matsko I have updated to 4.3.0-beta.1 but the out animation is not firing. 
http://plnkr.co/edit/pxdQbfuNCHnc98EtalrQ?p=preview

**Comment by Bretto** [comment]
@matsko I have updated to 4.3.0-rc.0 but the issue remains
http://plnkr.co/edit/xJXIsZbEsssh5GTicU55?p=preview

**Comment by mackelito** [comment]
@Bretto looks like you got it working? Have similar issues and trying to figure it out, any pointers?

**Comment by Bretto** [comment]
@mackelito no sorry I don't have any pointers as I am still trying to do this very example that is still not working. The current issue is that the leave animation is not being triggered, sorry. I am waiting for someone with a better understanding of the matter so I can build on solid ground my own understanding.

**Comment by mackelito** [comment]
I kind of solved it now.. had to have the animations set on the child component. I was kind of hoping to leave the child component clean and minimalistic. But I can find pros of keeping the animations on the child as well 👍  :)

**Comment by Bretto** [comment]
you got a plnkr to share ?

**Comment by mackelito** [comment]
Sadly no.. but it was quite easy.. just moved the trigger to the child and then used the :enter transition.

**Comment by matsko** [comment]
@Bretto let's start a new issue (since there are three issues that you've posted). There have been a few fixes with querying in the recent versions of Angular. Making a new issue can help us figure out exactly what's broken. Please create a new issue and I'll get to it right away.
