### ISSUE TITLE
Scroll position is not updated when url fragment changes by clicking on a fragment anchor

### ISSUE THREAD

**Issue by IgorMinar** [angular/angular#17521]
## Steps to repro
1. Edited a doc where I added a simple `<a href="#someFragmentAnchor">click here</a>`
2. Ensure that there is a anchor like that somewhere in the doc `<a name="someFragmentAnchor"></a>`
3. render the page and click on the link

## Expected Behavior
1. url in the address bar is updated
2. scroll position within the viewport is adjusted in the same way as when clicking on any of the TOC links
3. the active TOC item is updated to reflect the current scroll position

## Actual Behavior
1. url in the address bar is updated
2. scroll position or TOC active item are NOT updated

## Additional Context

Currently we don't have many links like this, and if there are any they are not functional. I came across this, when modifying the dgeni templates for API pages where I wanted to have inter-document links like this.

When implementing this, we should integrate this with the existing navigation flow and integrate into it.

@petebacondarwin do we need to consider how this affects the link verification? how would that work? Ideally all these fragment links would be validated just like any other links.

**Comment by wardbell** [comment]
Does dgeni get a look at this page in your repro? A bare `#bookmark` has **never worked.** But dGeni will convert all such links into the only form that actually does work: `-/the/page#bookmark`

**Comment by IgorMinar** [comment]
I've generated these links via dgeni template.html files. Is there anything
special that I need to do?

I'm a but surprised that there is a difference between the two url forms.
The relative urls should resolve to the same absolute url. No?

**Comment by petebacondarwin** [comment]
I think you are supposed to use id not name

**Comment by petebacondarwin** [comment]
https://stackoverflow.com/questions/484719/html-anchors-with-name-or-id

Anchors do not have name attribute in html5

**Comment by gkalpak** [comment]
AFAICT, the reason we can't use just `href="#foo"` (without the full path `/guide/http#foo`) is that we have `<base href="/" />`, which makes `href="#foo"` equivalent to `href="/#foo"` (navigating to `https://angular.io/#foo`).

Other than that (and the issue with named anchor mentioned above), everything should work as expected. Note that you can still use the short `href="#foo"` form in the actual templates, because dgeni will automatically expand them.

<sub>Closing, but feel free to reopen in case I missed something.</sub>
