### ISSUE TITLE
Improve the service worker update behavior

### ISSUE THREAD

**Issue by IgorMinar** [angular/angular#17539]
## Current behavior
Whenever we submit a change to angular.io (often multiple-time per day), we generate a new service worker manifest which is deployed along with the new build on the production servers.

The next time user reloads angular.io, the service worker picks up the manifest change, fetches the update, and stages it for activation.

We can't just activate the new version of the app because the current version is already running. Reloading the app at random times would result in a bad user experience, so we are avoiding it. Instead, we just use a [material snack bar](https://material.angular.io/components/component/snack-bar) to show a notification that an update is available.

The pop-up notifications are easy for people to overlook, or are annoying for those that do see them.

## Proposed behavior
- remove the snackbar notification
- add a simple update notification in the footer after the version number. e.g.: Version 4.2.3-build.31733+sha.64fa100 ([update available](url))
- if clicked, ~all active tabs~ the currently active tab with angular.io will be reloaded and the staged update will be activated
- lastly, once an update is staged, we'd start listening on the windown#unload event indicating tab being closed or reloaded, at this time, ~we'd force-reload *all* active angular.io tabs and activate the new update~ we'd activate the staged update.

The proposed behavior is aiming to:
- remove the annoyance that notification cause
- ensure that users use the latest version of the app as soon as possible without sacrificing offline capabilities, caching, and fast startup.
- bring back the refresh-to-update behavior that non-service worker apps have and users expect to work

I should point out that this kind of update strategy is not going to work for every app. Apps that don't have their full state persisted would lose data during the update (e.g. unsubmitted form, expanded menus, scroll position, etc). angular.io doesn't have much user-entered state, so the trade-off is worth it.

**Comment by IgorMinar** [comment]
@alxhub what do you think about the proposal?

One standing question we have is about the inactive tabs (in case a user has more than one tab open) - what happens to them when we activate the staged application.

It seems that currently they get into a state where they keep on running, but are being intercepted by the new service worker. This could result in data consistency issues, which are unlikely to manifest in angular.io but might be a real concern for other apps, especially those that rely on dynamic caching.

**Comment by gkalpak** [comment]
I played around with this and here are some thoughts:

1. Since activating the update is asynchronous, it is not always complete in time when initiated in the `unload`/`beforeunload` events. Most of the times, it requires two reloads to show the updated content.
  (`unload`/`beforeunload` are fine when navigating to a different page and then coming back.)

2. Activating a SW update will essentially update its caches. Since all open tabs share the same SW, activating the update on one tab, will affect the content served on other tabs, so we might end up in a situation where a tab show incompatible versions of the app vs content (e.g. old `styles.css` file with new `guide.json` file).

3. If we are OK with (2) above, we could as well activate the new content as soon as it is available (which would solve (1) too).

Neither solution I can think of is ideal. Other suggestions/ideas welcome :smiley:

**Comment by gkalpak** [comment]
We discussed it and here is the new plan:

1. Once an update is available, activate it immediately (but not reload any tab).
2. Notify all open tabs that an update has been activated (so they need to reload at an appropriate moment).
3. On every tab, as soon as the user navigates to a new document, we will do a full-page reload (instead of just loading the new doc).

Benefits of this approach:
1. The user always gets the latest content on reload (avoiding race conditions).
2. The app never serves incompatible/version-mismatchced content (on any tab).
3. No notifications or other distractions.
4. The users gets the latest content as soon as possible.

We need a way to signal to other open tabs that an update has been activated and let them reload on the next navigation.

**Comment by IgorMinar** [comment]
NgServiceWorker#updates has a event type `activation` that we can listen on to know when we need to do the full reload on the next navigation event.
