### ISSUE TITLE
Some Google links to Doc might be broken

### ISSUE THREAD

**Issue by MA-Maddin** [angular/angular#17542]
## I'm submitting a ...
<pre><code>[x] Documentation issue or request
</code></pre>

## Current behavior
googlig for `angular 2 style guide` etc. give us the old, broken link https://angular.io/styleguide

## Expected behavior
should be linking to https://angular.io/guide/styleguide

## Minimal reproduction of the problem with instructions
https://www.google.de/#q=angular+2+style+guide

## What is the motivation / use case for changing the behavior?
improved user experience 😄

**Comment by gkalpak** [comment]
It turns out that #17544 is not enough to fix this once the ServiceWorker has been installed, because it will [rewrite to `index.html`][1], so the request will never reach the Firebase redirect rules.

[1]: https://github.com/gkalpak/angular/blob/14bb345c0fe1c2f222dc46ed23d0697c82cb95d6/aio/ngsw-manifest.json#L19-L26
