### ISSUE TITLE
Hero editor tutorial issue

### ISSUE THREAD

**Issue by cfavano** [angular/angular#17554]
I'm learning angular and confused with the terminology here: 
[https://angular.io/guide/displaying-data](https://angular.io/guide/displaying-data)

Should my-app  be considered a CSS selector OR html5 element?

>  The CSS selector in the @Component decorator specifies an element named` <my-app>`. That element is a placeholder in the body of your index.html file:

```
<body>
  <my-app>loading...</my-app>
</body>
```

**Comment by dherges** [comment]
Both.

The element is named `<my-app>`.

The corresponding selector for that element is `my-app`.

The former is in the HTML, the latter is in the TypeScript decorator `@Component({..})`.

**Comment by Foxandxss** [comment]
We said `CSS Selector` because it is more generic than "html 5 element". The component selector can be an attribute, an element, and a bunch of more concrete selectors. All of them are CSS selectors (because the syntax used there is the CSS selectors syntax).

For example, when testing, you have access to the `By.css()` method and you can do stuff like:

By.css('element');
By.css('attribute');
By.css('....');

All of that is valid in the @Component selector as well.
