### ISSUE TITLE
Renderer2 is not always properly injected

### ISSUE THREAD

**Issue by adrienboulle** [angular/angular#17558]
## I'm submitting a ...
<pre><code>
[x] Regression (behavior that used to work and stopped working in a new release)
[ ] Bug report 
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior
Renderer is injected instead of Renderer2

## Expected behavior
Renderer2 should be injected

## Minimal reproduction of the problem with instructions
No idea :/

What I can say is that I have in the issue case this renderer object :

![capture d ecran 2017-06-16 a 09 40 42](https://user-images.githubusercontent.com/14262895/27217078-a955110a-5278-11e7-903a-678131858449.png)

If, in the given component, I specify in the providers `Renderer2`, it will work :

![capture d ecran 2017-06-16 a 09 37 27](https://user-images.githubusercontent.com/14262895/27217072-a6cb9f26-5278-11e7-87aa-075259220653.png)

<pre><code>
Angular version: 4.1.0

Browser:
- [x] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: 6.9.2
- Platform: Mac

**Comment by tytskyi** [comment]
related https://github.com/angular/angular/issues/17378

**Comment by chuckjaz** [comment]
Thanks for reporting this issue. However, you didn't provide sufficient information for us to understand and reproduce the problem. Please check out [our submission guidelines](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-submitting-an-issue) to understand why we can't act on issues that are lacking important information.

If the problem still persists, please file a new issue and ensure you provide all of the required information when filling out the issue template.

A plunker link and steps to to reproduce would help diagnose this issue.

**Comment by saithis** [comment]
We experience the same problem with angular 4.2.3. 

The component which needs Rednerer2 is used in 7 different places. In 6 places everything works, but in the 7th place Renderer is injected instead of Renderer2. Unfortunatelly i couldn't reproduce it in a plunkr yet.

**Comment by janousek** [comment]
@chuckjaz Unfortunately, I do not have repro. But I discovered what is the problem. 
There is a problem with method "visitExternalExpr" inside class "JitEmitterVisitor". It can produce duplicate names of arguments. This problem was already reported https://github.com/angular/angular/issues/8676 . And it should be already fixed but it is not.

There is an example from my application:
![jitemittervisitor](https://user-images.githubusercontent.com/304745/28239900-d8807af4-6976-11e7-912c-f69a25be75b2.jpg)

On the index 6, it is "Renderer2", and on the index 26 it is "Renderer". But, because of the way how are these names generated (`jit_${name}${id}`) the final name is in both cases "Renderer26".

I believe that this bug is in all versions of Angular. But it occur only in special cases, like I described.

**Comment by tytskyi** [comment]
@chuckjaz i got the working reproduction with `4.3.0`
http://plnkr.co/edit/XtbTcxOQh3XPst4Pexqf?p=preview

Which is absolutely wierd is that changing of any of that conditions fix the issue.
For example: removing any `*ngIf` - fixes, removing pipe - fixes, removing `ViewChild` - fixes, removing injection of `TestService` - fixes, reordering checkbox with custom control - fixes. 

I cannot really understand what are the causes. Just to note - the same code works with no problem in `4.2.6`

**Comment by alexzuza** [comment]
@janousek is right. I had similar issue in angular 2.x.x but the problem was nothing to do with renderer. My tokens just mixed up because compiler used `anonymous` with the same key. In the plunker provided by tytskyi we can observe it
![reproduction](https://user-images.githubusercontent.com/4223314/28270300-fd05f20a-6b15-11e7-90a3-ac2b8ff656af.gif)

**Comment by chuckjaz** [comment]
@tytskyi @alexzuza Thanks for the excellent work tracking this down!
