### ISSUE TITLE
short-circuit aio and core specific CI builds 

### ISSUE THREAD

**Issue by IgorMinar** [angular/angular#17552]
aio today doesn't use Angular builds produced by build.sh, because of this any changes to `/packages`/ can't affect `/aio/` tests. This is also true in the opposite direction - a change to `/aio/` can't break unit or e2e tests from `/packages`.

Because of this, I propose that we speed up our CI and reduce the impact of flakes, by skipping aio build and test CI scripts if aio can't be affected by changes in TRAVIS_COMMIT_RANGE.

We can detect the impact of the PR using similar technique that uses `git diff $TRAVIS_COMMIT_RANGE` as in https://github.com/angular/angular/pull/17222/files#diff-f94e51c275a246b1903df0122806b919R50

UPDATE(2020-05-15): this issue is still valid even now that we use CircleCI and use bazel. This is primarily the case because `aio` doesn't use bazel today. Until that changes, this issue will be valid and relevant.

**Comment by gkalpak** [comment]
For reference, we use the same technique in [deploy-preview.sh][1] to determine whether certain areas have been touched.

##
The speed-up would be nice indeed (flakes? what flakes?) 😛

One thing to keep in mind:
Changes in `/packages` may lead to docs changes. For that reason we need to deploy a preview, which involves building `/aio`. We can probably still skip the tests though. The docs-specific tests (that would catch dangling links etc) are run in a separate Travis job.

[1]: https://github.com/angular/angular/blob/956a7e95d72f2dc849076c54882f9e4eab62c379/aio/scripts/deploy-preview.sh#L16

**Comment by IgorMinar** [comment]
Part of this might have been already implemented. @gkalpak can you document the current status if you know?

**Comment by gkalpak** [comment]
I have documented the current status [here][1] (sorry, not public atm). There were some things I was not sure about (marked yellow-ish).

We do run some unnecessary operations/jobs, but nothing too dramatic (for the most common cases), I would say. Still, there is room for improvement.

[1]: https://docs.google.com/spreadsheets/d/113TG16dfQ4ImteY8jDfgP7BCL38JLyIYzGv1PoaTexI

**Comment by petebacondarwin** [comment]
Our imminent move of AIO builds/tests to CircleCI (https://github.com/angular/angular/pull/26377) this should be fixed, right @gkalpak ?

**Comment by gkalpak** [comment]
This issue is about skipping certain types of tests if they couldn't have been affected by the changes in a commit. The move to CircleCI does not improve anything in that regard. However, it will take care of only building Angular once (for all jobs in the workflow), which is the most time-consuming operation in the aio jobs that need it.

As mentioned above, we can hardly skip the `aio` tests for commits that touch `packages/` (which is the vast majority of commits).
But we could skip certain non-`aio` tests if we only touched `aio` files for example. So, there is room for improvement.

Bazel will automatically take care of all of this some day 😛

**Comment by jelbourn** [comment]
Closing since I believe bazel remote execution/caching has mostly solved this problem and selectively running tests on CI based on the content is generally problematic.
