### ISSUE TITLE
Animation style( " * " ) behave differently from expect

### ISSUE THREAD

**Issue by DanielYKPan** [angular/angular#17565]
## I'm submitting a ...

<pre><code>
[ ] Regression (behavior that used to work and stopped working in a new release)
[x] Bug report 
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior

I used  style(" * ") to revert all used styles in the animation back to their end state value. But it behaved differently than expect.

I used animation to rotate an object from 90deg to 180deg (clockwise). But when I used **style("*")**, the object did rotate  from 90deg to 180deg, but it rotated in a different direction.(counter-clockwise)

here is the [live demo](https://plnkr.co/edit/HRVphqdnplDtkRmlbxN3?p=preview) to demonstrate the issue.

## Please tell us about your environment

<pre><code>
Angular version: 4.2.2

Browser:
- [ X] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [X ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [X ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: XX 
- Platform:  Mac 

Others:

</code></pre>

**Comment by matsko** [comment]
The reason why the incorrect rotation occurs is because `*` styles are captured using `getComputedStyle`. When `getComputedStyle` is called it will return a transform matrix value for the transform style on the element. Transitioning back to the matrix value is then something done automatically by the browser (which in this case looks like a reverse rotation animation).

Since this is browser-level, there is no way around this by making a fix in the framework.

Having the hard coded transform value is the correct solution in your example. If you are using other styles in addition to transform then you can do this to combine them together:

```ts
style(['*', {transform: 'rotate(180deg) scale(1)'}])
```

**Comment by DanielYKPan** [comment]
@matsko 
Thanks for the explanation.

**Comment by DanielYKPan** [comment]
@matsko 
I have another test about this animation rotation.
This time I did not use the wildcard state `*`, and the rotate direction seems not right at certain degrees (In this demo, when the degree is 180, the rotation would change the direction).
Here is the [Demo](https://plnkr.co/edit/QUhF4GNssrJfvYLEtwGw?p=preview)
