### ISSUE TITLE
No exported member "eDomAnimationEngine"

### ISSUE THREAD

**Issue by hontrang** [angular/angular#17593]
Hi,
I'm using animation on angular 4.0.0 and manually install package "@angular/animation" but after that I got issue, could you point me what wrong am I and any solutions? I've appreciate.

![issue angular 2](https://user-images.githubusercontent.com/7942014/27257786-4188b5a8-540e-11e7-9a96-6c11fd66b747.JPG)

**Comment by hansl** [comment]
Hi. Could you copy-paste your package.json file here please? Or even better, have an example demo on github would be really useful. Thanks!

**Comment by matsko** [comment]
This error occurs when one dependency is higher/lower than the other. In this case `angular-platform-browser` is out of sync with `angular-animations`. Most likely `platform-browser` is outdated in your `node_modules/` folder and `angular-animations` got updated (I know this because `eDomAnimationEngine` is not around anymore).

So clear out your `node_modules/` directory and rerun `npm install`.

**Comment by matsko** [comment]
Please reopen if it's still an issue.
