### ISSUE TITLE
member variable of a component not accessible inside custom validator function via "this"

### ISSUE THREAD

**Issue by ngmgit** [angular/angular#17608]
## I'm submitting a ...

<pre><code>
[ ] Regression (behavior that used to work and stopped working in a new release)
[X ] Bug report 
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior

Except FormGroup variable (i.e registerForm as per plnkr provided) all other variables are accessible inside the custom validator function of a component. By making a conditional check this unexpected behavior can be avoided. But i think handling it via conditional statement should'nt be how it should be done.  

## Expected behavior

FormGroup variable (i.e registerForm as per plnkr provided) should be accessible without explicitly making a conditional check via if statement.

## Minimal reproduction of the problem with instructions

Here is a plnkr 
https://plnkr.co/edit/KkK5cbsJQOIzwxY8wUKA?p=preview

<pre><code>
Angular version: 4.2.3

Browser:
- [ X] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [X ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version:  v7.10
- Platform:  Linux

**Comment by alexzuza** [comment]
`registerForm` is not assigned yet while `fb.group` function creates model. `fb.group` calls `validate` method for control internally.

**Comment by ngmgit** [comment]
@alexzuza since we cant avoid this, i think conditional checking and `setValidators` is the only way to make it run.

**Comment by Toxicable** [comment]
@ngmgit you cannot access `this.registerForm` since updateValueAndValidity()  is called in the FormGroup's constructor which causes the validators to be run, meaning that they're run before `this.registerForm` is assigned

**Comment by kara** [comment]
We must run `updateValueAndValidity` when the `FormGroup` is created so that the validation status is correct at creation time. Not doing so would break a whole lot of forms because their status wouldn't be right, so this isn't likely to change. 

(FWIW, if you are trying to check the equality of two fields, there is a better way. In your current implementation, if the `test1` value changes, the validation function won't run and the status will be wrong. It's usually better to create a group validator one level up. That way, you can simply check `ctrl.get('test1').value === `ctrl.get('name').value`, rather than relying on a property in your component.)
