### ISSUE TITLE
Proposal: declaring rate-limited event handlers (debounce, throttle)

### ISSUE THREAD

**Issue by jelbourn** [angular/angular#1773]
It's very common to need to rate-limit DOM events that fire too quickly, such as `scroll` or `mousemove` for performance reasons. In the ES5 world, it is very easy to create this kind of handler. For example, if you were using underscore:

``` html
<widget (movemove)="checkHoverPosition($event)">
```

``` js
Widget.prototype.checkHoverPosition = _.debounce(function(event) {
  // ...
}, 300);
```

However, in ES6 / TypeScript, the `class` syntax does not have a way to define a method based on the output of some function like this. You can still use the ES5 syntax, but that totally kills the hip vibe. Not to mention that this doesn't work for Dart at all.

We could solve this by introducing rate-limiters (or any of kind of similar function) for event handlers into Angular itself with a syntax something like:

``` html
<widget (movemove)="checkHoverPosition($event) | debounce:300">
<widget (movemove)="checkHoverPosition($event) | throttle:300">
```

These rate-limiters are needed by the material components, so it's only a question of whether Angular will support them directly or if the components have to roll our own rate limiting.

**Comment by mhevery** [comment]
@vsavkin Do you have an opinion?

I think this should not be the concern of angular but rather of some third party plugin, as there could be lots of different ways you may want to limit this, and I would rather not get into this business. Also `|` is already used for pipe syntax so it can't be reused here.

**Comment by vsavkin** [comment]
Since there are few events that need to be handled this way (those are not really events, but rather continuous behaviors), I would prefer not to bake this mechanism into the framework unless we have to. Imo it should be done on a lower-level.

**Comment by matanlurey** [comment]
Jeremy, couldn't you create a function at runtime in ES6, e.g.?

```javascript
@View({
  template: '<widget (movemove)="onMouseMove($event)">'
})
class Widget {
  onMouseMove: Function;

  constructor() {
    this.onMouseMove = _.debounce(this.checkHoverPosition, 300);
  }

  checkHoverPosition(event) {
    ...
  }
}
```

**Comment by jelbourn** [comment]
The method has to be on the prototype, otherwise you're creating a copy of it for every component instance.

**Comment by gdi2290** [comment]
this is why decorators are awesome 
```es6
@View({
  template: '<widget (movemove)="onMouseMove($event)">'
})
class Widget {
  onMouseMove: Function;

  constructor() {
    this.onMouseMove = this.checkHoverPosition;
  }

  @debounce(300)
  checkHoverPosition(event) {
    //...
  }
}
```

**Comment by tbosch** [comment]
The only problem are zones. We don't want to trigger dirty checking when
the denouncing decides to ignore the event.

doing denouncing inside of an event handler in a directive or component
will always trigger change detection, as our event handlers run inside the
Angular zone.

So I think we need to think about this a little more...

**Comment by jelbourn** [comment]
@tbosch that's a very good point

@vsavkin this kind of rate limiting is *very* common. Looking at the current material design components, some uses:
- Text entry into the autocomplete
- Text entry into md-input (for auto-resizing a `textarea` element)
- Window resize events for several components (such as drawing ticks for a slider)
- Scrolling events for things (headers, etc) that are "stickied"
- For parent components doing something based on the addition or removal of a child (such as a re-layout)

**Comment by vicb** [comment]
If the implementation has not changed the event handler actually runs in the outer zone.

In the outer zone, we test if the event target is our actual element. Only when they match, we execute code in the angular zone which triggers the CD.

May be we can generalize the target = actual test some more generic predicate support that would also work w/ debounce ?

**Comment by naomiblack** [comment]
Misko agrees this should be in core because there are too many points where it intersects with zones/change detection for a  user like material to efficiently implement this themselves. Design needed.

**Comment by jelbourn** [comment]
@mhevery Thinking about this more, what do you think of this syntax:

```is
<input (input)="checkValue() >> debounce(100)">
```

**Comment by mhevery** [comment]
@jelbourn I think https://github.com/angular/angular/issues/1773#issuecomment-149885950 is not ideal because it implies that `checkValue()` will always be executed, but the `debounce` will throttle the output of the function. I think the syntax needs to make it clear that the 
1. `debounce` goes first 
2. that it is not part of normal expression. 

It also does not explain where the `debounce` comes from. Ideal syntax would make it clear which part is part is the guard and which is the expression.

**Comment by jpsfs** [comment]
Hi,

My 2cents on this subject.
I've done some examples with debouncing, and these are the alternatives I've thought.

```HTML
<input (input)="debounce(checkValue(), 100)">
```

# Pros:
* Very declarative, easy to read;
* Similar to approaches followed by other libs (underscore, lodash);

# Cons:
* Name colision with functions already present on the component itself;

An alternative could be:

```HTML
<input (input)="ngDebounce(checkValue(), 100)">
```
The name colision can still happen but it feels more clean.

Other alternative, following @jelbourn's approaches:
```HTML
<input (input)="debounce(100) >> checkValue()">
```
I personally think that introducing a new kind of operator ">>" is something that should be avoided but I see the reasoning behind it.
By reversing the order, I think it's now aligns better with @mhevery's concern (and that I also share).

**Comment by mhevery** [comment]
I have not figured out all of the details, but here is what I am thinking so far, and wanted to get some feedback

```
<input (input|userProcessor)="doFoo()"
```

Where `userProcessor` would be a developer declared function which would be declared in the UI thread and which would execute outside the zone. The idea here is that `userProcessor` would then be allowed to transform a stream of events in time and generate a new stream of events which would then be used to execute `doFoo()`

- It should be a named symbol rather then inline parameters so that it would be easy to apply to many different events and get same behavior. Easy to change it in one location applies everywhere.
- Maybe we could allow chaining as well? `<input (input|foo|bar)>`
- Canonical version `<input on-input--foo--bar="doFoo()">`

Still thinking about:
- How do we register `userProcessor` with the template

**Comment by vicb** [comment]
What about a syntax to **only** execute the callback outside of Angular. Then it's up to the user to do whatever fell like in the method. It would avoid overloading templates with logic and help with testing.

**Comment by mhevery** [comment]
Been doing some more thinking about this, and I think better way to think about it is that we could have synthetic event streams. For example: `<div (click)="do()">` will invoke `do()` on `click`. Similarly we could have `<div (click-throttled)="do()">` which will do the same on `click-throttled`. The trick becomes declaring a new event. One way to do that is that we could extend the capabilities of `Directive`s.

```
@EventDirective({
  selector: `(click-throttled)`,
})
class ThrottledEvent {
  @Output('input-throttled') emitter = new EvenEmitter();
  @EventListenner('click') onInput(event) {
    emitter.next(event);
  }
}
```

this would also solve: the issue where Ionic would like to create custom events or poly-fill events on  different platforms, or even redefine click on mobile to not wait 300 ms.

The advantage here is that this approach does not introduce new concepts, just extends an existing concept of directives.

Thoughts?

**Comment by vicb** [comment]
I need to think more about it also.

Caveats I can see with your proposal (let me know if I'm wrong):
- Needs one directive per event name, not possible to define re-usable behaviors (ie debounce, ...),
- Does not solve the ` runOutsideOfAngular` thing

**Comment by mhevery** [comment]
> Needs one directive per event name, not possible to define re-usable behaviors (ie debounce, ...),

This could be solved if the selector would be `(*-debounce)` we would have to then somehow extract the name from the `*`.

> Does not solve the runOutsideOfAngular thing

It would be assumed that all `EventDirective`s run outsize the zone

**Comment by tbosch** [comment]
@EventDirective would live on the app side. I.e. all events need to be
marshaled over in a WebWorker scenario.
Also, it's not clear how it relates to zones.

A better option would be to provide plugins for the renderer that deal with
this (based on the event name, independent of the current component).

**Comment by vicb** [comment]
At this point I'm not a big fan of the `EventDirective` option: it seems that the only purpose of having it is to have something similar to ` Directive`  so that we do not introduce new concepts but extend existing concepts.

I think users will have hard time remembering that they can use a `()` selector only with an `EventDirective`  and they can not use a `*-`  selector in a regular `Directive`.

`*-` selector could also be problematic wrt to name collision.

I actually preferred the previous proposal, ie `EventPipe`: (input|debounce:300)='onInput($event)'. @mhevery would there be a problem with this (vs `EventDirective`) ?

**Comment by jelbourn** [comment]
I like that the `EventPipe` concept is composable.

**Comment by mhevery** [comment]
I am still in the phase of throwing ideas out, and getting feedback. Sounds like we should be thinking about this in form of synthetic events, which are registered with Renderer???? That way we could short circuit the marshaling between the App and UI side.

thinking.....

**Comment by ericmartinezr** [comment]
I would say @gdi2290 https://github.com/angular/angular/issues/1773#issuecomment-102052192 solves @mhevery issues in this https://github.com/angular/angular/issues/1773#issuecomment-149963827

I don't really understand all the technical discussion here, but I think it would be much simpler to do 

```typescript
@Output('input', {debounce:XXXX})
@Output('mousemove', {throttle:XXXX})
```

Instead of extending the meaning of Directive, it would be nice to extend the use of Output and add it an extra param which will be an object and can contain certain properties.

With that approach, or the possible `@Debounce/@Throttle` we can keep the template clean and make everything in Component/Directive side.

Also remember that you've changed the term for "Event", so `EventPipe` or `EventDirective` should be called `OutputPipe/OutputDirective`

FWIW, my two cents.

*Throws smoke and dissapears*

**Comment by oliverjanik** [comment]
I'm just learning angular2 now so I might have a simplistic view on this. 

Doesn't Angular2 use Rx.js? That already has a debounce operator http://reactivex.io/documentation/operators/debounce.html. 

All we need is an easy way to treat event bindings as observables.

**Comment by robwormald** [comment]
@oliverjanek yup, see this issue https://github.com/angular/angular/issues/4062 - for this precise use case.

**Comment by oliverjanik** [comment]
I just found this article today, nicely shows how to achieve debounce and more: http://blog.thoughtram.io/angular/2016/01/06/taking-advantage-of-observables-in-angular2.html

**Comment by xeor** [comment]
Is there a way to work around this issue now? Any updates?

**Comment by jrolheiser-va** [comment]
I managed to use Manuel Rauber's solution pretty quickly from his blog. https://manuel-rauber.com/2015/12/31/debouncing-angular-2-input-component/

**Comment by baio** [comment]
Hey guys any progress on this ?

**Comment by gdi2290** [comment]
@baio if you want this I can create a module for angular decorators that run outside of zone.js

**Comment by baio** [comment]
@gdi2290 Hi Patrick, thanks but I basically want to try implement it by myself, if I will have troubles I would ask. If I use ChangeDetection.OnPush and Observables, I shouldn't worry about zoned change detections, am I correct ?

**Comment by baio** [comment]
This is my attempt to implement this with decorator.
https://github.com/baio/link-shortener/blob/master/src/app/utils/debounce-decorator.ts

**Comment by stalniy** [comment]
The most expected implementation would be to use `EVENT_MANAGER_PLUGINS`

**Comment by markcooper** [comment]
Please do this! This is a feature that is needed quite often

**Comment by andrevcf** [comment]
+1

**Comment by mhevery** [comment]
Closing in favor of https://github.com/angular/angular/issues/13248, which will support this and many other use cases.
