### ISSUE TITLE
aio: erroneous dgeni missing example file error

### ISSUE THREAD

**Issue by wardbell** [angular/angular#17753]
## I'm submitting a ...

<pre><code>
[ ] Regression (behavior that used to work and stopped working in a new release)
[x] Bug report 
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior

`yarn docs` reports this
```
error:   Missing example file... relativePath: "docs-style-guide/src/tsconfig.json". 
- doc "guide/docs-style-guide" (content)  - from file "guide/docs-style-guide.md" - 
starting at line 1
```
It's wrong on two counts:
1. The file exists. 
1. The location of the purported error is not "line 1"

Most importantly, dgeni fails to generate the code-snippet for this `tsconfig.json` file

Note that `src/tsconfig.json` is one of the boilerplate files. There would be an error if the boilerplate task had been neglected. But that is not the case when I get this error.

As an experiment, I copied `tsconfig.json` as `tsconfig.1.json` and adjusted the `code-pane` path accordingly. That works. Is `dgeni` ignoring boilerplate files for some reason?

**Comment by petebacondarwin** [comment]
Thanks for creating the issue @wardbell. Although this file exists (after one has added the boilerplate, it is ignored by dgeni because it matches the `.gitignore` rules. This is by design and we have come across this before, with the quickstart guide. The workaround that we decided upon was to create a version of the file that was appropriate for the content of the guide and name it `tsconfig.1.json`. See https://github.com/angular/angular/blob/master/aio/content/examples/quickstart/src/tsconfig.1.json

The error location is actually accurate if somewhat misleading. It is the line of the source file at which the document begins. In the case of guides this is always line 1. For API docs it is the line of the source file where the jsdoc comment begins.

In the future we ought to make this more clear.

**Comment by wardbell** [comment]
Thanks. In this case, it is not worth changing our practice. We're talking about the Authors Doc Guide which has a small audience. So I'll fix that.

The `.1` files are a PITA to maintain and have a history of causing us problems. But we'll worry about that another day.

A fix to the reporting of the errant line in the source file would be lovely.
