### ISSUE TITLE
@ViewChild annotated field stays undefined under certain circumstances

### ISSUE THREAD

**Issue by pawod** [angular/angular#17769]
## I'm submitting a ...

<code>
[X] Bug report
</code>

If this is not a bug, but my mistake, feel free to help me at stackoverflow:
https://stackoverflow.com/questions/44541805/angular-4-nested-viewchild-is-undefined

## Current behavior
A `@ViewChild` annotated field stays `undefined` under certain circumstances:

- Parent component of type `X` implements abstract base class of type `XBase`, which has three abstract fields
- Component of type `X` annotates these field with `@ChildView` of types `A`, `B` and `C`
- `C` in turn also extends `XBase`, but uses a different template and selector than `X`
- Fields of type `A` and `B` get propery initialized in component of type `X`
- Field of type `C` stays undefined

## Expected behavior
- The field of type `C` should not be `undefined`

## Minimal reproduction of the problem with instructions
https://embed.plnkr.co/083a5AnkaiCG796adTkR/

- Open up your browser's debug mode to see the console output
- Click on the "Drives" tab
- The console will print the `DriveMembersModalComponent`, it corresponds to component `C` mentioned above. The `grid` field is `undefined`. The print is executed in the `DriveViewComponent`'s `ngAfterViewInit()`.

## Please tell us about your environment

<pre><code>
Angular version: 4.2.1

Browser:
- [X] Chrome (desktop) version 58.0.3029.110 (64-bit)
- [X] Firefox version 54.0 (32-bit)
- [X] Edge version 38.14393.1066.0

**Comment by vicb** [comment]
Please provide a **minimal** plunker showing the error - it has to be the simplest possible code triggering the error.
Thanks

**Comment by pawod** [comment]
I've found the solution, it is not related to `@ViewChild`, but to a missing module export statement and the type of template selector (by attribute or tag). I still have to investigate whether this is a bug or not. If it is, I will open another issue.

**Comment by marcobarbero** [comment]
Sometimes, if the component isn’t jet initialized when you access to it, you get error that says that the chield component is undefined.

The first thing to consider is that you need to wait for the view to be initialized before you can access your @ViewChild, so you should access to the component in the AfterViewInit method.

However, even if you access to the chield component in the AfterViewInit, sometimes the @ViewChild was still returning null. The problem can be causedwas by the *ngIf or other directive.

The solution is to use the @ViewChildren instead of @ViewChild and subscribe the changes subscription that is executed when the component is ready.

For example, if in the parent component  ParentComponent you want to access the child component MyComponent.

```
import { Component, ViewChildren, AfterViewInit, QueryList } from '@angular/core';
import { MyComponent } from './mycomponent.component';

export class ParentComponent implements AfterViewInit
{
  //other code emitted for clarity

  @ViewChildren(MyComponent) childrenComponent: QueryList<MyComponent>;

  public ngAfterViewInit(): void
  {
    this.childrenComponent.changes.subscribe((comps: QueryList<MyComponent>) =>
    {
      // Now you can access to the child component
    });
  }
}

```
Form:
https://expertcodeblog.wordpress.com/2018/01/12/angular-resolve-error-viewchild-annotation-returns-undefined/

**Comment by vivaldus** [comment]
I'm using @ViewChildren as follows:

```ts  
@ViewChildren('somediv')
somedivs: QueryList<ElementRef>;
```

... in order to grab references to divs within an ngFor loop and ngIf that require a data service to first be injected before the DOM will update. As a result, when I run `ngAfterViewInit(){}`, I find that this.somedivs is still undefined, so there isnt even an observable in place that I can subscribe to. So I'm stumped as to how to trigger/wait for an event in order to act on the divs I want to access. Any suggestions?
