### ISSUE TITLE
Parallel (Asynchronous Non Blocking) Routing 

### ISSUE THREAD

**Issue by balangovindaraj** [angular/angular#17791]
The application has a page with 2 to 3 category buttons. Basically, button click will pull the list of items in each category, the page should be shown once API fetched data is available.

I have designed angular 2 app routes with resolve API calls and I should not block the entire page with spinner when a page loads as we are migrating the application functionality to angular 4.

When a user clicks on one category, if the response is delayed he may click the other category. When he navigates back he would be expecting the data to be loaded in previously clicked category but Angular 2/4 cancels the route due to Navigation ID does not match with the current route

<pre><code>
[ ] Regression (behavior that used to work and stopped working in a new release)
[X] Bug report 
[X] Feature request
[ ] Documentation issue or request

</code></pre>

http://embed.plnkr.co/UiyhZWCl63Tfq41WY48q

Click on the planet and people concurrently, observe that only one of the section loads and other section doesn't load the data. If you do inspect you can see NavigationCancel event is thrown

<pre><code>
Angular version: 4.0

</code></pre>

**Comment by jasonaden** [comment]
@balangovindaraj This is the expected behavior. A `resolve` should be used to provide values that must be present in order for the route to be instantiated. If the data you need isn't required for the route to be instantiated, you should probably load the categories from another service so it will not cancel when routing changes.
