### ISSUE TITLE
Cannot determine module for directive that extends another directive in a different package

### ISSUE THREAD

**Issue by jelbourn** [angular/angular#17849]
### Reproduction
* Clone `https://github.com/jelbourn/material2/tree/directive-extends-ngc-repro`
* Run `gulp aot:build`

In this case, the `MdTabLabel` directive in `@angular/material` extends `TemplatePortalDirective` from `@angular/cdk`. When running `ngc` on the `demo-app` (which consumes both material and cdk), I get
```
Cannot determine the module for class MdTabLabel in /usr/local/google/home/jelbourn/material2/dist/packages/demo-app/material/typings/tabs/tab-label.d.ts! Add MdTabLabel to the NgModule to fix it.
```

If I remove the base class from `MdTabLabel`, this works. If I add `MdTabLabel` to the declarations of _another_ module, `ngc` does correctly report that it is declared in two modules.

**Comment by jelbourn** [comment]
I found that this workaround leads to a successful build:
```ts
export const _MdTabLabelBaseClass = TemplatePortalDirective;

/** Used to flag tab labels for use with the portal directive */
@Directive({
  selector: '[md-tab-label], [mat-tab-label], [mdTabLabel], [matTabLabel]',
})
export class MdTabLabel extends _MdTabLabelBaseClass {
  constructor(templateRef: TemplateRef<any>, viewContainerRef: ViewContainerRef) {
    super(templateRef, viewContainerRef);
  }
}
```

**Comment by chuckjaz** [comment]
The issue is that the `material.metadata.json` does not include an `importAs` field so it is not considered a flag module index causing the compiler to look for symbols below the index include `tab-label.d.ts`. Because it inherits from `TemplatePortalDirective`, itself a directive, it inherits the that it is also a directive even though there is no `.metadata.json` file to declare it as such (the reason the other classes are not also reported).

The fix is to artificially include an `importAs` field with duplicates the `importAs` field in `index.metadata.json` in `material.metadata.json`. A similar fix needs to be in `cdk.metadata.json`.

**Comment by DevVersion** [comment]
@chuckjaz I just tried adding the `importAs` property to our metadata reexport file.

```json
{"__symbolic":"module","version":3,"metadata":{},"exports":[{"from":"./typings/index"}],"importAs":"@angular/material"}
```

After doing this, it looks like no export from Material can be read from NGC at all. 

```
Can't export value 
MdAutocompleteModule in XXX/material2/dist/packages/demo-app/material/typings/index.d.ts 
from DemoMaterialModule in XXX/material2/dist/packages/demo-app/demo-app-module.ts as 
it was neither declared nor imported!
```

[Here](https://github.com/angular/material2/blob/master/src/demo-app/demo-app-module.ts#L87-L124) is a link to the `DemoMaterialModule` that tries to re-export the individual Material modules (to avoid kitchen sink modules).

I also saw that there is a new metadata option called `flatModuleIndexRedirect` in `^4.2.0`. Unfortunately we are not able to use that option (since we support older NGC versions)

**Comment by chuckjaz** [comment]
@DevVersion I recommend you avoid using the redirect entirely. This was only intended to be used packages with multiple entry points. You can avoid this by not having a `typings` directory. There is no way to get what you want in older version of NGC as `flatModuleIndexRedirect` was intended to solve this issue.

**Comment by jelbourn** [comment]
We will have multiple entry-points in material eventually.

We can probably update to 4.2 (there was a regression blocking us, but I suspect it's been fixed by now)

**Comment by DevVersion** [comment]
@chuckjaz Yeah it would be easier if we would have it similar as for every other Angular package.

Unfortunately in Material we can't have another directory like `packages/XXX/src`/ (like [here](https://github.com/angular/angular/tree/master/packages/core)) since it would require us move a lot of files.
 
I wish we could actually just use the same pattern and have a `packages` directory so we can apply the same solutions Angular core applies.

Upgrading to a more recent version of the Angular Compiler CLI & tsc-wrapped would be definitely beneficial.
