### ISSUE TITLE
Raise error for missing exports when imported component does not use html tag for selector

### ISSUE THREAD

**Issue by pawod** [angular/angular#17874]
## I'm submitting a ...
<pre><code>
[X] Feature request
</code></pre>

## Current behavior
Angular does not raise any error when an imported component has not been exported by its module. This happens when no explicit html tag is used for the template of the imported component.

## Expected behavior
An error should be raised in such cases.

## Minimal reproduction of the problem with instructions

https://plnkr.co/edit/kPKSbPS86iJ1oVCA4WSj?p=preview

`ModuleA` is missing an export statement for `ComponentA`, which is imported and used in `AppModule`.  When no explicit html tag is used for the template of `ComponentA`, no error is thrown.  `App`'s `@ViewChild` stays undefined for no evident reason.

If you uncomment line 26 in src/module.ts, `App`'s `@ViewChild` will be properly rendered. An error is only raised if you change the template's <div> tag to <component-a>. Then Angular will complain about the unknown element and ask you to check, whether it is an Angular component.

## What is the motivation / use case for changing the behavior?
I could not find the reason for my `@ViewChild` staying undefined and it took me a LONG time to figure out I am just missing an export statement.

## Please tell us about your environment

<pre><code>
Angular version: 4.2.5

Browser:
- [X] Chrome (desktop) version 58.0.3029.110 (64-bit)
- [X] Firefox version 54.0 (32-bit)
- [X] Edge version 38.14393.1066.0
 
</code></pre>

**Comment by pkozlowski-opensource** [comment]
Here is a simplified reproduce scenario with Angular 9: https://ng-run.com/edit/rOihR3nj3V3kKoIB7Zqf?open=app%2Fapp.component.ts

This problem is not specific to queries but shows a general problem with directive matching to attributes. 

The essence of the problem here is that a directive with a selector matching an attribute (`[a-directive]`) can "silently fail" for multitude of reasons:
* a directive is not part of a module (as in the reproduction / scenario in this issue);
* there is a typo in an attribute.

Those problems are not new and we are already tracking challenging validation scenarios for attributes in #3425. I'm going to keep this issue open as it describes yet another scenario where directive matching can fail silently. Totally agree that it can be very confusing. 

Having said all this, it will be challenging to catch those types of error due to the current syntax + NgModule interactions.

**Comment by jessicajaniuk** [comment]
It appears this behaves as expected. If you still feel there is an issue, please provide further details in a new issue.

**Comment by alxhub** [comment]
To elaborate, this is the natural result of how attributes work in Angular - it's not illegal to have an unmatched attribute, so Angular cannot know whether the attribute was intended to match a component that's not in scope or is intended to just be present in the DOM (for example, to be matched with CSS). Therefore we can't make it an error.
