### ISSUE TITLE
MessageSpan contain the same value for startCol & endCol

### ISSUE THREAD

**Issue by ocombe** [angular/angular#17881]
## I'm submitting a ...
[x] Bug report

## Current behavior
For the [PR of the new migration tool](https://github.com/angular/angular/pull/17638) we generate a json file that contains the old / new messages. It includes information about the source files using their MessageSpans.
We noticed that the value for startCol & endCol are the same, which is obviously wrong.
See this file as an example: https://github.com/ocombe/angular/blob/6409883fe40fc9dcb82544990db8a9eb077698d6/packages/compiler-cli/integrationtest/src/mapping_v1_to_v0.json

## Expected behavior
endCol should be the real number of the column for the end of the message.

## Minimal reproduction of the problem with instructions
You can use this PR: https://github.com/angular/angular/pull/17638

## What is the motivation / use case for changing the behavior?
Having correct information

## Please tell us about your environment
Angular version: 4.3.0-beta.1

**Comment by petebacondarwin** [comment]
This is out of scope for the current range of development. The new extractor will not even attempt to store the end of a message in the generated translation files. I cannot find any information on the web about location metadata in formats such as XLIFF 2, XMB, etc. So I suspect that any metadata that we currently provide is proprietary anyway.

At this time, since we have no migration tool such as in #17638 we do not have this requirement.
