### ISSUE TITLE
ExpressionChangedAfterItHasBeenCheckedError doesn't give enough context

### ISSUE THREAD

**Issue by nertzy** [angular/angular#17887]
## I'm submitting a ...

<pre><code>
[ ] Regression (behavior that used to work and stopped working in a new release)
[ ] Bug report 
[x] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior
Today when I upgrade my application I see this in my console:
> Error: ExpressionChangedAfterItHasBeenCheckedError: Expression has changed after it was checked. Previous value: 'true'. Current value: 'false'.

## Expected behavior
More information should be provided, such as which element, attribute, and expression the error applies to. Something like:
> Error: ExpressionChangedAfterItHasBeenCheckedError: Expression has changed after it was checked. Previous value: 'true'. Current value: 'false'. Component \<my-component\>. Attribute [foo]. Expression "bar + 1".

## What is the motivation / use case for changing the behavior?
This is so that developers can understand what part of a complex application code base is causing the issue.

## Please tell us about your environment

<pre><code>
Angular version: 4.2.4

**Comment by vicb** [comment]
Please add a repro. Thanks.

**Comment by IgorMinar** [comment]
Thanks for reporting this issue. However, you didn't provide sufficient information for us to understand and reproduce the problem. Please check out [our submission guidelines](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-submitting-an-issue) to understand why we can't act on issues that are lacking important information.

If the problem still persists, please file a new issue and ensure you provide all of the required information when filling out the issue template.

**Comment by leocaseiro** [comment]
Hi @vicb and @IgorMinar,

I apologise for writing in a closed issue, but I was going to open a request for that.
 
Perhaps this plunker can give an example of the context provided by angular. http://plnkr.co/edit/mX6REf9oidrVeURCvTZG?p=preview
> This plunker is a fork from @adrienboulle from https://github.com/angular/angular/issues/14748#issue-210324703

I agree with @nertzy that the warning message `ExpressionChangedAfterItHasBeenCheckedError` is doing a nice job telling us what are the values before and after the change detection.

**However, we're never sure what object or property is referring to, while the lines are not reliable.**

In some cases, we use an array of objects and messages like so are provided:
```
ERROR Error: ExpressionChangedAfterItHasBeenCheckedError: Expression has changed after it was checked. Previous value: 'undefined'. Current value: '[object Object],[object Object]'.
    at viewDebugError (errors.ts:30)
    at expressionChangedAfterItHasBeenCheckedError (errors.ts:29)
    at checkBindingNoChanges (util.ts:145)
    at checkNoChangesNodeInline (view.ts:477)
    at checkNoChangesNode (view.ts:568)
    at debugCheckNoChangesNode (services.ts:557)
    at debugCheckDirectivesFn (services.ts:466)
    at Object.View_App_0._co [as updateDirectives] (App.html:7)
    at Object.debugUpdateDirectives [as updateDirectives] (services.ts:443)
    at checkNoChangesView (view.ts:378)
```

Well, I can see the file name is `App.html`, so I presume is something in my template, but it's not clear what it is. Also, note that my bug should be on line 2 (`<div *ngIf="testObject">`), and not on line 7 as mentioned by angular.

Perhaps, it would be nice adding to the warning message the property/object that has changed its value.

I would expect the warning message being something like so, instead:
```
ERROR Error: ExpressionChangedAfterItHasBeenCheckedError: 
Expression has changed after it was checked. 
Previous testObject value: 'undefined'. Current testObject value: '[object Object],[object Object]'.
```
PS: note the `testObject` key from my App class.

**In that case, it would be easier to debug that the object is `testObject`;**


If you comment line 33: `this.testObject = [{a: 1, b: 2}, {a: 3, b: 4}];`, you end up with another bug with the same issue, but now referring to the `getHeightPx()` method. 

```
App.html:9 ERROR Error: ExpressionChangedAfterItHasBeenCheckedError: 
Expression has changed after it was checked. Previous value: '0px'. Current value: '100px'.
```

In that case is much easier to debug. The line 9 is correct. 
Also, because of its values (`'0px'` and `'100px'`), it is easier to find the property. However, the message error could have the missing `getHeightPx()` method which would make the debugging easier.

**Comment by victornoel** [comment]
@vicb and @IgorMinar, here a repro is given: https://github.com/angular/angular/issues/17572#issuecomment-323465737 (a comment written by one of your co-worker @robwormald)

Could we reopen this issue? :)
