### ISSUE TITLE
Text Blurred on resources page

### ISSUE THREAD

**Issue by ubarsaiyan** [angular/angular#17907]
Text is blurred on this page: https://angular.io/resources when hovered over an item

## I'm submitting a ...

<pre><code>
[ ] Regression (behavior that used to work and stopped working in a new release)
[x] Bug report 
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior

Text is blurred

## Expected behavior

Text should not be blurred

## Minimal reproduction of the problem with instructions

Go to the above link and hover over any item.
## What is the motivation / use case for changing the behavior?

Text should always be readable.

## Please tell us about your environment

<pre><code>

Browser:
- [x] Chrome (desktop) version 59
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX

**Comment by gkalpak** [comment]
For reference, here is what I see (there is indeed a slight blurring):

Normal:
![unhovered](https://user-images.githubusercontent.com/8604205/27909289-a698593c-6258-11e7-8e23-ddb265ecc8d7.png)

Hovered:
![hovered](https://user-images.githubusercontent.com/8604205/27909292-aa66fb22-6258-11e7-914a-008859aef2fd.png)

**Comment by gkalpak** [comment]
I found that this is caused by [this transform][1]. It seems to be a known issue (see [here][2] for example).
Although most of the things suggested in the StackOverflow answers didn't help, changing `translate3d(0, -2px, 0)` to `translate3d(0, -4px, 0)` seems to make the blur go away (at least on my screen :grin:).

[1]: https://github.com/angular/angular/blob/35a2dfc1779235daef3ee93f6d90653bf4a52fa0/aio/src/styles/2-modules/_resources.scss#L211
[2]: https://stackoverflow.com/questions/6411361/webkit-based-blurry-distorted-text-post-animation-via-translate3d

**Comment by gkalpak** [comment]
Also, replacing `translate3d(0, -2px, 0)` with `translateY(-2px)` (which does the same thing), fixes the blur :confused:

**Comment by ubarsaiyan** [comment]
@gkalpak Yes, this resolves the issue. Though the text is blurred while translating it again becomes clear after translation stops.
