### ISSUE TITLE
Reactive form does not always reflect changes in the UI

### ISSUE THREAD

**Issue by peterbakonyi05** [angular/angular#17910]
## I'm submitting a ...
<pre><code>
[ ] Regression (behavior that used to work and stopped working in a new release)
[X] Bug report 
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior
You have a form that contains multiple form groups. You use `ChangeDetectionStrategy.OnPush`. You create separate component for each group and pass the reference of the relevant group as an input to the component that represents that group. Now if you set the controls touched and dirty manually, the form will have the correct state. However it won't reflect properly in the UI (even if you do `AppRef.tick`, `ChangeDetectorRef.markForCheck` etc...).

## Expected behavior
All of the inputs gets updated in the UI.

## Minimal reproduction of the problem with instructions
Open the plunker and start running. You will see the short description on how to replicate.

http://plnkr.co/edit/7CQokcBmFR7HiWCeGYlj

## What is the motivation / use case for changing the behavior?
You have a huge form. User presses enter in the first input field, you need to display the validation errors for all inputs to show the user the missing fields before the form can actually be submitted.

## Please tell us about your environment

<pre><code>
Angular version: latest (4.2.5), also tested with 2.4.8 and same behaviour.
Browser:
- [ x] Chrome (desktop) version 58
</code></pre>

**Comment by Toxicable** [comment]
The ref to `formGroup` on the child component did not change, therefore Change Detection (CD) is not run.

When using OnPush CD is only run when
 - @Input changes ref
 - A bound event occurs inside the component
 - `ChangeDetectorRef#markForCheck` is called in the component

Since you have done none of these CD will not be run

**Comment by kara** [comment]
@peterbakonyi05 In your plunker, the problem is that you're calling `markForCheck` on the wrong level (the parent component, not the child component). The keydown event will trigger change detection in the parent anyway, but it won't check the child in this run unless one of the conditions @Toxicable notes occurs. You can fix your example by calling `markForCheck()` on the CVA component itself when appropriate.

**Comment by magnattic** [comment]
So I am confused: What is the proper way to handle this?

I have a button which sets all FormControls of a FormGroup as touched with `markAsTouched()`. But because some of them are in a nested Component with `OnPush`, the state change is not reflected in the UI.

And because I cannot listen to `touched`, I cannot call `markForCheck()` when it is changed in the background.

It seems to me there is a serious design flaw here because FormGroups and FormControls are not really immutable and therefore don't play nice with the whole `OnPush` concept.

**Comment by DanielSchaffer** [comment]
This would be a lot easier to manage if there was an `EventEmitter` for all of the "state" changes (e.g. `touched`, `dirty`, etc).

**Comment by Humberd** [comment]
Refreshing the thread. This is a design flow. We need a solution for this.
