### ISSUE TITLE
Language Service: More forgiving support of union types in templates

### ISSUE THREAD

**Issue by michaelbromley** [angular/angular#17953]
## I'm submitting a ...
<pre><code>
[ ] Regression (behavior that used to work and stopped working in a new release)
[] Bug report 
[x] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior
When I have a variable in my component with a union type, the language service will complain if I reference any properties which are not common to all members of the union type. Sometimes it may be valid to try to reference these non-shared properties, e.g.:

```TypeScript
import { Component } from '@angular/core';

export interface Line {
  length: number;
  dimensions: number;
}

export interface Plane {
  area: number;
  dimensions: number;
}

@Component({
  selector: 'app-root',
  template: ` {{ shape.length || shape.area }}
              {{ shape.dimensions }}

              <div *ngFor="let item of collection">
                  {{ item.length || item.area }}
                  {{ item.dimensions }}
              </div>
`})
export class AppComponent {
  collection: Array<Line|Plane> = [];
  shape: Line|Plane;
}
```
Here is a screenshot of the output from VS Code using the language service plugin:

![language-service-error](https://user-images.githubusercontent.com/6275952/27905876-a918ca46-6241-11e7-8060-16355032f5bb.PNG)

## Expected behavior
I would expect to be able to use the above construction without errors.

## Minimal reproduction of the problem with instructions
1. Create a new angular CLI project with `@angular/cli 1.2.0`
2. Replace the contents of  app.component.ts with the code above
3. View in VS Code with the language service plugin enabled. My version of the plugin uses `@angular/language-service@4.1.0-beta`

## What is the motivation / use case for changing the behavior?
The example above illustrates a simple uses case. In my app I have a situation where I have a generic component which can be passed different types of object, and uses the `||` operator to display the first truthy value.

## Please tell us about your environment

<pre><code> 
For Tooling issues:
- Node version: 7.7.1
- Platform: Windows 10
- VS Code 1.13.1
- @angular/language-service@4.1.0-beta
- Typescript@2.1.5
</code></pre>

**Comment by chuckjaz** [comment]
This is equivalent to [this playground example](http://www.typescriptlang.org/play/#src=export%20interface%20Line%20%7B%0A%20%20length%3A%20number%3B%0A%20%20dimensions%3A%20number%3B%0A%7D%0A%0Aexport%20interface%20Plane%20%7B%0A%20%20area%3A%20number%3B%0A%20%20dimensions%3A%20number%3B%0A%7D%0A%0Alet%20item%3A%20Line%20%7C%20Plane%3B%0A%0Aconst%20v%20%3D%20item.length%20%7C%7C%20item.area%3B%0A%0A) in which TypeScript also reports an error.

As we improve type checking during AOT compilation this will be reported as an error in 5.0 as well as we will use TypeScript's type checker instead of our own.

**Comment by michaelbromley** [comment]
Thanks for the reply. I guess the difference is that in regular TS code I can cast before accessing the property, which I cannot do in the template.

```TypeScript
const v = (item as Line).length || (item as Plane).area;
```

I guess the way to do this now would be then to provide a method on the component which performs the cast and returns the appropriate value, and then just call this method in the template.

**Comment by chuckjaz** [comment]
That is certainly what we recommend. The templates expressions should be simple and any complicated logic should be in the component.

**Comment by albv** [comment]
@chuckjaz and what about tagged union types? For example:
```
interface PayPal {
    type: "paypal";
    email: string;
}

interface CreditCard {
    type: "creditcard";
    cardNumber: string;
    securityCode: string;
}

type PaymentMethod = PayPal | CreditCard;

@Component({
  selector: 'my-payment-method',
  template: `
    <div [ngSwitch]="paymentMethod.type">
      <div *ngSwitchCase="'paypal'">{{ paymentMethod.email }}</div>
      <div *ngSwitchCase="'creditcard'">{{ paymentMethod.cardNumber }}</div>
    </div>
  `
})
export class PaymentMethodComponent {
  @Input()
  paymentMethod: PaymentMethod;
}
```

Should we do type casting in component also? Like this:
```
@Component({
  selector: 'my-payment-method',
  template: `
    <div [ngSwitch]="paymentMethod.type">
      <div *ngSwitchCase="'paypal'">{{ paymentMethodAsPaypal.email }}</div>
      <div *ngSwitchCase="'creditcard'">{{ paymentMethodAsCreditCard.cardNumber }}</div>
    </div>
  `
})
export class PaymentMethodComponent {
  @Input()
  paymentMethod: PaymentMethod;

  get paymentMethodAsPaypal(): Paypal() {
    return this.paymentMethod as PayPal;
  }

  get paymentMethodAsCreditCard(): CreditCard() {
    return this.paymentMethod as CreditCard;
  }
}
```

**Comment by chuckjaz** [comment]
Interesting problem.  For this to work I need some way to declare the type relation between  `NgSwitch.ngSwitch` and `NgSwitchCase.ngSwitchCase`. For this I would need to add a type parameters to `NgSwitch` and `NgSwitchCase` such that it would look like:

```
export class NgSwitch<T> {
  ...
  @Input()
  set ngSwitch(newValue: T} {
    ...
  }
  ...
}

export class NgSwitchCase<T> {
   ...
  @Input() ngSwtichCase: T;
}
```

Following the pattern of #20702, I would then need to declare a guard for `ngSwitch` which is a bit odd since it the guard would need to be declared in `NgSwitchCase`, but, ignoring that for a bit, the guard might look something like,

```
  ...
  static ngSwitch_key_ngSwitchCaseTypeGuard = <T, K extends string, V extends S>(a: T, k: K, v: V) => a is T & {[T in K]: V};
  ...
```

which would then allow me to generate the following type-check block:

```ts
if (NgSwitchGuard.ngSwitch_member_ngSwitchCaseTypeGuard(component.paymentMethod, "type", "paypal") {
  component.paymentMethod.email;
}
```

A simplified version of this can be seen in the playground [here](http://www.typescriptlang.org/play/index.html#src=interface%20PayPal%20%7B%0D%0A%20%20%20%20type%3A%20%22paypal%22%3B%0D%0A%20%20%20%20email%3A%20string%3B%0D%0A%7D%0D%0A%0D%0Ainterface%20CreditCard%20%7B%0D%0A%20%20%20%20type%3A%20%22creditcard%22%3B%0D%0A%20%20%20%20cardNumber%3A%20string%3B%0D%0A%20%20%20%20securityCode%3A%20string%3B%0D%0A%7D%0D%0A%0D%0Atype%20PaymentMethod%20%3D%20PayPal%20%7C%20CreditCard%3B%0D%0A%0D%0Afunction%20m(p%3A%20PaymentMethod)%3A%20string%20%7B%0D%0A%20%20switch(p.type)%20%7B%0D%0A%20%20%20%20case%20%22paypal%22%3A%20return%20p.email%3B%0D%0A%20%20%20%20case%20%22creditcard%22%3A%20return%20p.cardNumber%3B%0D%0A%20%20%7D%0D%0A%7D%0D%0A%0D%0Afunction%20f%3CT%3E(v%3A%20T)%3A%20v%20is%20(T%20%26%20%7B%20type%3A%20%22paypal%22%7D)%20%7B%0D%0A%20%20%20%20return%20true%3B%0D%0A%7D%0D%0A%0D%0Avar%20p%3A%20PaymentMethod%3B%0D%0A%0D%0Afunction%20caseSelect%3CT%2C%20K%20extends%20string%2C%20V%20extends%20string%3E(a%3A%20T%2C%20k%3A%20K%2C%20v%3A%20V)%3A%20a%20is%20T%20%26%20%7B%5BT%20in%20K%5D%3A%20V%7D%20%7B%0D%0A%20%20%20%20return%20true%3B%0D%0A%7D%0D%0A%0D%0Aif%20(caseSelect(p%2C%20%22type%22%2C%20%22paypal%22))%20%7B%0D%0A%20%20%20%20p.email%3B%0D%0A%7D%0D%0A%0D%0A).

I currently can only get this to work for the string union types and deciding when and how to apply it is a bit tricky in general (the odd part ignored above) but this seems like we might eventually be able to do this.

Unfortunately, adding a type parameter to `NgSwitch` is a breaking change that will not be able to land until 6 but I probably would not get to this before 6 anyway so that is not blocker.

**Comment by chuckjaz** [comment]
I added #20780 to track this.

**Comment by albv** [comment]
Looking forward to see it landed. Thanks for the detailed response @chuckjaz

**Comment by dirkluijk** [comment]
Looking forward to see type guard support in language-service as well!

My simple use case:
```typescript
interface Animal {
  type: 'fish' | 'bird';
}

interface Fish extends Animal {
  type: 'fish';
  foo: string;
}

interface Bird extends Animal {
  type: 'fish';
  bar: string;
}

@Component({})
class MyComponent {
  animal: Animal;

  isFish(animal: Animal): animal is Fish {
    return animal.type === 'fish';
  }

  isBird(animal: Animal): animal is Bird {
    return animal.type === 'bird';
  }
}
```

Use case 1
```html
<app-fish *ngIf="isFish(animal)" [foo]="animal.foo"></app-fish>
<app-bird *ngIf="isBird(animal)" [bar]="animal.bar"></app-bird>
```

Use case 2
```html
<ng-container [ngSwitch]="true">
  <app-fish *ngSwitchCase="isFish(animal)"></app-fish>
  <app-bird *ngSwitchCase="isBird(animal)"></app-bird>
</ng-container>
```

Are both use cases covered in https://github.com/angular/angular/issues/20780?

**Comment by crutchcorn** [comment]
This does not seem to be fixed still. Type unions are still not working as expected in templates

**Comment by istvandesign** [comment]
`@Input() error: number | ErrorType = <ErrorType>{}; ` will cause template errors in vscode with Angular 6. Also vscode seems to be much slower for some reason with the template open.

**Comment by simeyla** [comment]
@albv Your code looks so freakishly like mine I actually got deja vu!
That is to say I'm working on the same problem with payment methods.

I modified your answer slightly, to what I think makes a little more sense if you don't want to change the object being 'switched' upon. In your case to achieve this you added `paymentMethodAsPayPal()` to the class (component) that actually contained the payment method.

I have an array of pure (from JSON) data representing a list of payment methods, so I couldn't add methods onto it. Instead you can create the following method and use it in the component:

    // convert a Braintree 'VaultedMethod' (interface) into a 'VaultedCreditCard'
    public asCreditCard(method: VaultedMethod) {
        return method as VaultedCreditCard;
    }

      <ng-container [ngSwitch]="method.type">

             <div *ngSwitchCase="'CreditCard'">

                  <strong>Ends in {{ asCreditCard(method).accountNumber }}</strong></span>  
                  <span>{{ asCreditCard(method).cardType }}</span>
                            
             </div>

     </ng-container>

This ends up looking more like a 'cast' within a block where you've clearly established the data type. 

If you really needed to you could do a check inside `asCreditCard` to make sure it really was the correct type
