### ISSUE TITLE
Router not navigating if matrix params change is inside an array.

### ISSUE THREAD

**Issue by aman05** [angular/angular#17966]
## I'm submitting a ...

<pre><code>
[ ] Regression (behavior that used to work and stopped working in a new release)
[x ] Bug report 
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior

Let's say you have a dict where you are storing your matrix params.
```
matrixParam['products'] = [];
matrixParam['products'].push(1);
this.router.navigate(['',matrixParam]) // works
matrixParam['products'].push(2);
this.router.navigate(['',matrixParam]) // does not work
```

## Expected behavior

It should navigate each time.

## Minimal reproduction of the problem with instructions
https://embed.plnkr.co/wb0lKdSlSpTQXZOB1Y1v/

Open this in windowed mode to see the route change, or rather the lack of route change.

## Please tell us about your environment

<pre><code>
Angular version: 4.2.5 //Same for router

Browser:
- [x] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [x ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: XX 
- Platform: 

Others:

</code></pre>

**Comment by aman05** [comment]
I think this is somewhat related to #17823

**Comment by jasonaden** [comment]
@aman05 This is intended behavior, since the actual value has not changed in this case. If you were to do a `===` comparison between the old params and the new params, you would get a `true` back.

If you changed the last line to something like this, you should see the navigation work:

`this.router.navigate(['', [...matrixParam]]) // should work`

**Comment by aman05** [comment]
@jasonaden I am little confused about what you mean when you say the actual value does not change 
```
matrixParams['products'] =[1]   //on first call
matrixParams['products'] =[1,2]   //on second call
```
But thanks for the reply, and 
```
this.router.navigate(['', ...matrixParam]) // works
```

**Comment by jasonaden** [comment]
Good it's fixed!

What I meant is that in your example, you used the array `.push()` method. While this adds an item to the array, it's still the same array. So:

```
let myArray = [1];
let secondCopy = myArray;
secondCopy.push(2);

expect(myArray === secondCopy).toBe(true);
expect(myArray.length).toBe(2);
```

Basically, you're mutating the array, but it's still the same array.

Using the `...matrixParam` syntax will take out the *values* of the `matrixParam` array rather than the array itself. Therefore if the values in the array have changed, we can detect those changes.
