### ISSUE TITLE
aio: Problem with animation when switching code tabs

### ISSUE THREAD

**Issue by dzhavat** [angular/angular#17998]
## I'm submitting a ...

<pre><code>
[ ] Regression (behavior that used to work and stopped working in a new release)
[x] Bug report 
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior

When toggling between code examples, the sliding animation doesn't run. 

![firefox](https://user-images.githubusercontent.com/1096332/27977337-8707f7b8-636a-11e7-8353-5d6abb46cd86.gif)

## Expected behavior

Sliding animation should run properly.

This is how it works in Chrome.

![chrome](https://user-images.githubusercontent.com/1096332/27977616-cdab67f8-636b-11e7-9da4-634e990ff754.gif)

## Minimal reproduction of the problem with instructions

* Go to a page in the docs with code examples separated in tabs (e.g. [this one](https://angular.io/tutorial/toh-pt3#review-the-app-structure))
* Click on the tabs 

## Please tell us about your environment

<pre><code>
Angular version: Latest

Browser:
- [x] Firefox version 54.0.1

Others:
Windows 10
</code></pre>

**Comment by matsko** [comment]
thank you @dzhavat for finding this. I will look into it.

**Comment by gkalpak** [comment]
This is actually not an issue with animations (or mdTabs), but with angular.io.

It happens because of [this line][1], which is supposed (based on the comment) to just remove the ripple effect (no idea why 😞), but is sure does more than that :smiley:
While animating, mdTab will set a `transform` style on the tab content element, which should have no effect (due to our `transform: none !important` style afaict), so Firefox seems to do the right thing. For some reason, Chrome doesn't respect the `!important` part and executes the animation anyway.

[1]: https://github.com/angular/angular/blob/cc611c93b6748717f660bc99124bb4f8b9bc0fa3/aio/src/styles/2-modules/_code.scss#L116-L118
