### ISSUE TITLE
(mouseleave) not called with *ngIf

### ISSUE THREAD

**Issue by alexsapps** [angular/angular#18066]
## Current behavior
(mouseleave) event on parent component doesn't get called when child components appear under the cursor while the mouse is in the component.

## Expected behavior
(mouseleave) handler should always be called when the mouse leaves the element.

## Minimal reproduction of the problem with instructions

Go here:

https://plnkr.co/edit/HiY2edMB7ZL9MTNCyxbD?p=preview

Move mouse around the "Moo...". Notice some lines stay green. The lines should only be green if they are being hovered over.

Note that the rows are independent. It still works if you change "Array(50)" to "Array(1)", just harder to see.

## Environment
Angular 4

Browser: Chrome (desktop)

**Comment by Toxicable** [comment]
Your issue isn't with `mouseleave` not being called with ngIf since  that itself dosen't work
Your issue is when you mouse over the items fast with corresponding ngIf content.
What I think is happening here is that you are mouse overing the item so fast that since it has to re-render the item it isn't in the DOM for a split second and therefore there is no element to emit the `mouseleave` event.
This is shown here: https://plnkr.co/edit/VkSJoZDeIvnPOD4YXdOp?p=preview
If you move you mouse rapidly over the left colunm you will see that it will behave as expeted since there is always content in the DOM to emit the event.
If you rapidly move your mouse over the `moooo...` then it will do the behaviour you are expecing since this item is removed from the DOM for a split second.

**Comment by alexsapps** [comment]
The element on which (mouseleave) is bound is always there, since the
(mouseleave) binding is on the element that is the parent of the element
that has  *ngIf, rather than (mouseleave) being inside the *ngIf.  It's
only the contents inside that is re-rendering. So it still seems like an
Angular bug to me.

Perhaps in Angular's implementation, it relies on mouse events of child DOM
elements to know when to call (mouseleave) handler for a parent element? If
so, I was guessing there is a bug in that logic. When the new content
appears due to (mouseenter), angular might not have registered a mouse
leave handler on that new content in time for the mouse to be already gone
on the next JS loop/tick.

**Comment by trotyl** [comment]
@alexsapps [This](https://plnkr.co/edit/jrmkbOONhdyMjPUoYRFi?p=preview) is a modified version that doesn't use NgIf, and still has the same problem, so I don't see how it comes to be a problem of Angular.

**Comment by alexsapps** [comment]
Interesting. I see someone else has reproduced it too outside of Angular completely:

https://stackoverflow.com/questions/29767524/mouseleave-not-firing-after-mouseenter-changes-html-within-anchor

Seems like a browser limitation then. In my actual app, I wanted to use *ngIf for performance reasons (less DOM) instead of using CSS to set display:none on different elements depending on the hover state of the outer element.

**Comment by Toxicable** [comment]
Since this is not an issue with the framework would you mind closing it then?

**Comment by alexsapps** [comment]
Here's the related bug in Chrome:
https://bugs.chromium.org/p/chromium/issues/detail?id=276329

And my own JS-only repo plunker:
https://jsfiddle.net/g8wzje83/
