### ISSUE TITLE
HttpInterceptor: Intercepted responses don't contain HttpResponse

### ISSUE THREAD

**Issue by chenkie** [angular/angular#18098]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior

The code found in the [test](https://github.com/alxhub/angular/blob/e37f23f52c0d46126c3d15f6dac2e573c838a353/packages/common/http/test/module_spec.ts#L31) for `HttpInterceptor` suggests that after calling `delegate.handle(request)` to handle the `HttpHandler`, we can `map` and get access to `HttpResponse` events. However, I'm only getting a simple object of `{ type: 0 }` in the `event`.

## Expected behavior

Per the `HttpInterceptor` [test](https://github.com/alxhub/angular/blob/e37f23f52c0d46126c3d15f6dac2e573c838a353/packages/common/http/test/module_spec.ts#L31), it looks like we should get an `event` that _could_ be an instance of `HttpResponse`. What are the circumstances that will give us this type?

## Minimal reproduction of the problem with instructions

Using 4.3.0-rc.0

Testing against a simple express API served locally on a different port.

```ts
intercept(request: HttpRequest<any>, delegate: HttpHandler): Observable<HttpEvent<any>> {
  // ...
  return delegate.handle(request).map(event => {
    console.log(event); // { type: 0 }
    return event;
  });
```

## Environment

<pre><code>
Angular version: 4.3.0-rc.0

Browser:
- [x] Chrome (desktop) version 59
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: XX  
- Platform:  

Others:

</code></pre>

**Comment by alxhub** [comment]
The 0 event is `Sent`, which indicates the request has been dispatched to the backend. Response events come later, when the request is actually fulfilled.

It seems like in this case the request is not actually responded to? Or perhaps an error comes back instead?

I'd need a repro test that actually flushes with a mock response to really investigate this problem. Something similar to the tests you linked above.

**Comment by chenkie** [comment]
In this particular case I'm trying to operate on any 401s that come back, which I assumed might be available on `event.status`. Perhaps I am missing a piece though. I'll get a Plunk going for you.

**Comment by NColey** [comment]
I'm having the same issue I believe, in that the [following information](https://github.com/angular/angular/blob/c9527e6309813ae49c70b4b4b8f20e0119d37d91/aio/content/guide/http.md#logging) from the Logging portion of the updated HTTP section of the guide suggests, as @chenkie pointed out that it is possible to receive an event that could be an instance of HttpResponse. 

The example from the guide I am referring to is here, but with mild edits (edited because the example is using a variable, `started` that is never declared. Not trying to be unhelpful by pointing that out I just wasn't sure how to create a PR to fix the typo since that code doesn't appear to be in master yet so I'll just update it here to illustrate the issue I think I and @chenkie are having):

```
import 'rxjs/add/operator/do';

export class TimingInterceptor implements HttpInterceptor {
  constructor() {}

  intercept(req: HttpRequest<any>, next: HttpHandler): Observable<HttpEvent<any>> {
    const started = Date.now();

    return next.handle(req).do((event: any) => {
      if (event instanceof HttpResponse) {
        const elapsed = Date.now() - started;
        console.log(`Request for ${req.urlWithParams} took ${elapsed} ms.`);
      }
    })
  }
}
```

After adding this interceptor to my application (which previously had 0 issues making http requests) and confirming it was hooked up properly (by adding a `console.log(req)`) right on the first line within the intercept function just to confirm it was the correct request and testing it out I noticed it never logs that message to the console because as pointed out already the event only ever appears to be a simple object of `{type: 0}`. A response is still returned (I updated my service to log the response to the console to confirm that there was in fact a response) it just seems to be picked up by the interceptor. I'm attempting to create a plunkr that will demonstrate this issue more clearly.

**Comment by NColey** [comment]
Just a quick update that I think will answer our confusion and provide a fix for @chenkie as well - I unfortunately wasn't able to create a plunker that would appropriately pick up the new HttpClientModule, however I realized that I had been testing (intentionally) this whole time with a request that would return a 401 error (basically hitting our backend while not logged in) because when reading [this comment](https://github.com/angular/angular/blob/master/packages/common/http/src/interceptor.ts#L34) in the new interceptor.ts code combined with the example that I linked to in my previous comment I interpreted that as if any kind of HttpResponse, including an HttpErrorResponse would be available within the `.map` function. 

I updated what I was testing with to look like the following:

```
  intercept(request: HttpRequest<any>, next: HttpHandler): Observable<HttpEvent<any>> {
    const started = Date.now();

    return next.handle(request).do((event: any) => {
      if (event instanceof HttpErrorResponse) {
        const elapsed = Date.now() - started;
        console.log(`Request for ${request.urlWithParams} took ${elapsed} ms.`);
      }
    }).catch(error => {
      debugger;
      return Observable.of(error);
    })
  }
```

and was able to catch the error just fine. I assume that once I hook back in the functionality to redirect to our backend login portal and no longer am receiving a 401 error I will be able to catch the HttpResponse just fine as well.

Apologies @alxhub for responding to this issue too quickly and assuming there was a bug before I had tested more options. Related though, when this portion of the guide is eventually released is there a chance that the wording will be updated or an example provided to demonstrate handling an HttpErrorResponse as well as an HttpResponse object? It took me an embarrassing amount of time to figure out that the comment in the interceptor.ts file I linked to above didn't apply to all responses - maybe this is something that could be clarified in the docs to make things clearer at first glance. Ultimately thanks so much for adding interceptors as a feature in the new HttpClientModule and sorry for the premature response to this issue.

**Comment by alxhub** [comment]
@NColey thanks, that confirms my suspicion.

@chenkie, a 401 response is "unsuccessful" and will thus come back over the `Observable`'s error channel, not as an event. To log it:

import 'rxjs/add/operator/do';

export class TimingInterceptor implements HttpInterceptor {
  constructor() {}

  intercept(req: HttpRequest<any>, next: HttpHandler): Observable<HttpEvent<any>> {
    const started = Date.now();

    return next.handle(req).do((event: HttpEvent<any>) => {
      if (event instanceof HttpResponse) {
        const elapsed = Date.now() - started;
        console.log(`Request for ${req.urlWithParams} took ${elapsed} ms.`);
      }
    }, (err: any) => {
      if (err instanceof HttpErrorResponse {
        const elapsed = Date.now() - started;
        console.log(`Request for ${req.urlWithParams} failed after ${elapsed} ms.`);
      }
    })
  }
}

I agree the guide needs a section on intercepting errors.

**Comment by chenkie** [comment]
Thanks @NColey and @alxhub.

That makes sense, should have tried that. Thanks for clarifying 👍

**Comment by MlleBeuze** [comment]
Hi everyone,

I don't get how to handle the result {type :0} in a else section? I don't want to receive this response when I subscribe. How can we get rid of it via the intercept class?

`import 'rxjs/add/operator/do';

export class TimingInterceptor implements HttpInterceptor {
  constructor() {}

  intercept(req: HttpRequest<any>, next: HttpHandler): Observable<HttpEvent<any>> {
    const started = Date.now();

    return next.handle(req).do((event: HttpEvent<any>) => {
      if (event instanceof HttpResponse) {
        const elapsed = Date.now() - started;
        console.log(`Request for ${req.urlWithParams} took ${elapsed} ms.`);
      } else { // Do not send {type: 0} as an response }
    }, (err: any) => {
      if (err instanceof HttpErrorResponse {
        const elapsed = Date.now() - started;
        console.log(`Request for ${req.urlWithParams} failed after ${elapsed} ms.`);
      }
    })
  }
}`

Thank you for your help :)

**Comment by velkumars** [comment]
Hi, 
I'm returning my error object from my API, how do i handled it inside catch? 

```
[HttpPost]
[Route("api/caller/save")]
public async Task<IActionResult> SaveCaller([FromBody]SaveCallerCommand command)
  {
       var result = await mediatr.Send(command);
       return result.ToActionResult();
  }
```

```
   public static class ResultExtensions
    {
        public static IActionResult ToActionResult(this XenResult result)
        {
            if (!result.IsFailure)
                return new OkResult();

            if (result.HasException)
            {
                //TODO what error reporting tool will we use to log errors?
               
            }
            return new BadRequestObjectResult(result.HtmlFormattedFailures);

        }
```
![image 1](https://user-images.githubusercontent.com/13570225/36895738-fe6a23f4-1e35-11e8-89eb-8611cc24536e.png)

**Comment by ulric03** [comment]
Thanks guys!

**Comment by jjdf01** [comment]
I am still getting a { type: 0 } object on the success channel of the observable for timouts

**Comment by nivle** [comment]
This is the working syntax for like rxjs 6+ I'm not sure what version they replaced "do" with pipe and tap. 
I'm using rxjs 6.3.3.

```
return next.handle(newRequest)
      .pipe(tap((response: HttpEvent<any>) => {
        console.log(response);
      },
        (error) => {
          console.log(error);
        }
      ));
```

**Comment by amineamami** [comment]
use catchError operator for handling errors
