### ISSUE TITLE
checkBindingNoChanges does not get unwrapped old values when checking for ExpressionChangedAfterItHasBeenCheckedError

### ISSUE THREAD

**Issue by victornoel** [angular/angular#18129]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior

When using impure pipes, the value is wrapped, for example with `async`.
Sometimes this makes the developer mode of Angular throw the error `ExpressionChangedAfterItHasBeenCheckedError` because `checkBindingNoChanges` gets a wrapped value as the old value and an unwrapped value as the new value even though they did not change (I simply looked at the values via the chromium debugger)

## Expected behavior

Either `checkBindingNoChanges` should unwrap values if needed or get unwrapped values from its caller.

## Minimal reproduction of the problem with instructions

Couldn't reproduce it: I think it happens in some complex scenario where the order of initialisation of the component and the moment data is received via an observable is not usual.

Note that my observables are initialized in `ngOnInit` and simply bound in the template via `obs$ | async` without anything else specific. I don't see how it could be simpler than that, none of the usual ways of fixing `ExpressionChangedAfterItHasBeenCheckedError` can even be applied!

I guess the problem existed before but since 4.2.x the checks are stricter and now the problem shows itself.

## Environment

<pre><code>
Angular version: 4.2.6

Browser:
- [x] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: XX  
- Platform:  

Others:

</code></pre>

**Comment by victornoel** [comment]
For the record, simply adding the following to `devModeEqual` (in `change_detection_util.ts`) fixes this problem:
```
    a = (a && a.wrapped) ? a.wrapped : a;
    b = (b && b.wrapped) ? b.wrapped : b;
```

**Comment by StevenLiekens** [comment]
I think ran into this bug today. Sorry, no simple repro, but I will describe my app.

I have an `Observable<Item[]`> that emits values from my ngrx store. I use it in a template along with an `async` pipe to initialize a child component.

```html
<!-- items$: Observable<Item[]> -->
<app-child-component [values]="items$ | async"></app-child-component>
```

The items Observable emits twice when the parent component is initialized. I don't know exactly why it emits twice, but the timing of the second emission seems to be the problem.

Order of events in my Parent and Child components:

1. Parent: OnInit
2. Parent: `items$` emits a value that is piped to `async`, pipe output is bound to Child
3. Child: OnInit
4. Parent: `items$` emits a value that is piped to `async`, pipe output is bound to Child
5. Child: AfterViewInit
6. Parent: AfterViewInit
7. Parent: ExpressionChangedAfterItHasBeenCheckedError

I think the 4th step is the breaking step because of the timing (between OnInit and AfterViewInit).

![image](https://user-images.githubusercontent.com/1583241/28413955-ca23a9c8-6d49-11e7-8ed3-509216e0b6a4.png)

I tried to step through `core.es5.js` but didn't understand much of what it does. From what I can tell, I'm seeing this error because `checkBindingNoChanges` does not unwrap values.

**Comment by StevenLiekens** [comment]
Update: my bad, the observable in my app emits twice because the Child component triggers a state change. It's simply a coincidence that the first and second value are identical.

Besides my mistake, I still believe that `checkBindingNoChanges` should unwrap instances of WrappedValue.

**Comment by victornoel** [comment]
@StevenLiekens yes, there could be many valid or invalid reason for an observable to emit twice, but angular should handle that without problems as you say :)
Let's hope this is fixed soon :)

**Comment by StevenLiekens** [comment]
My reason was definitely invalid. My Child component dispatches an ngrx action in its `OnInit` phase that results in a change to the bound value (because the observable emits a piece of ngrx state) before the Parent component can reach its AfterViewInit phase.

**Comment by victornoel** [comment]
@tbosch I'm trying to see if I can write a fix for this, and I understood you worked on the whole wrapped value thing. Do you see an obvious fix for this issue? I was browsing the code and wondered why `oldValues` in `ViewData` were sometimes stored as `WrappedValue`? Is there any use to that? If they were always stored as unwrapped values, wouldn't things work as expected? (and code would be simpler I suppose).

In particular, I'm confused by this function: https://github.com/angular/angular/blob/master/packages/core/src/view/util.ts#L30 both because I don't get where it is used and why it would reset the old value when unwrapping a value... at first I thought it wasn't related to this problem, but I noticed that if I comment the line where `oldValues` is reset, the errors disappear (even thought it may mean I broke the no changes mechanism :P).

There is also this line of code: https://github.com/angular/angular/blob/master/packages/core/src/view/util.ts#L94 that seems to do the same as what is already done by a function on its callstack in https://github.com/angular/angular/blob/master/packages/core/src/view/view.ts#L443

Or am I on the wrong track and the only important thing is to ensure, as proposed in the issue description, that the value themselves are compared when doing checks?

**Comment by victornoel** [comment]
Something else that is strange: my problem exhibits itself when the oldvalue is wrapped and new value is not wrapped. I wonder how this situation arises since, after some though, I understood that the value should always be either wrapped or not wrapped (at least when using async pipe).

**Comment by dmurat** [comment]
I've bean experimenting with plunker mentioned in a [comment](https://github.com/angular/angular/issues/15721#issuecomment-292274913) of related issue.

I think that a problem might be in `core/src/view/util.ts` in a function `unwrapValue` at the line 38 which states
`view.oldValues[globalBindingIdx] = new WrappedValue(oldValue);`

Since `unwrapValue` unwraps the current value, I believe that old value should also be stored as unwrapped variant instead as wrapped one. This can be achieved by replacing the line above with

`view.oldValues[globalBindingIdx] = oldValue;`

With this change, mentioned plunker works correctly and change makes sense to me.

**Comment by dmurat** [comment]
FWIW, just want to inform anybody interested that I tried the fix from above on pretty large project based on angular 4.3.2 without any obvious problems.

**Comment by nename0** [comment]
For me, I could fix it by never assigning a number to NaN. And as you can see in the screenshot above also empty strings seem to cause the problem. So it might be caused by a === vs a == , but that's just my theory.

**Comment by victornoel** [comment]
@robwormald I noticed you closed #17572 but did you see this issue? I think this is a bug and it's hitting many people, it would be great if it was fixed :)
Thanks!

**Comment by victornoel** [comment]
@alxhub is there any way to do something about that? :)

**Comment by victornoel** [comment]
Here is a counter-argument to this issue, mostly thinking out loud, but it may explain the situation and why this is not a bug.

1. Basically, this problem mostly appears when using the async pipe.
2. Most of the people seeing it, also often use the pipe with an observable coming from ngrx
3. Because of the way ngrx is used, it can happen than even if something changes in the store, a select query would produce an identical result.
4. Usually people exploits `distinctUntilChanged` to avoid that a new value is emitted.
5. Unfortunately, when the store starts to get complex and the values produced involve nested structures with arrays and objects, it becomes impossible to not produce a new value, even though it is semantically identical.
6. The `devModeEquals` method does a deep comparison, so we expect from it not to complain in that case.
7. But what we forgot, is that the async pipe uses wrapped values to explicitly specify that a value has changed: the async pipe is generic and from the point of view of an observable, a new value emitted is an important event, even if the value is semantically the same.
8. Hence, it is normal for angular to complain that something changed after it has already been checked, because something DID change, an event was emitted by the observable, and as said before, this is a meaningful event in most uses of observables.

The solution would thus be to refactor your store in order not to emit new values when nothing change. Or to rewrite your selectors with the same goal in mind.

Unfortunately, it is not easy and sometimes very cumbersome!

The problem is thus not a bug, but a question of design and if the use of ngrx, the async pipe, etc are justified and/or practicable!

@tbosch, @alxhub or @robwormald, it would be great if you could at least provide some feedbacks about this reasoning and if it is justified, we can close this issue (and then starts complaining about the inability of angular and ngrx to be combined together in complex scenario :P).

**Comment by victornoel** [comment]
By the way, what I just said is maybe wrong, because the async pipe does mark the change detection ref for check when new values are emitted by the observable… this is complex, I'm not sure :)

**Comment by SamVerschueren** [comment]
I'm having the same issues here with ngrx. I'm loading data in the `ngOnInit` of my child component, one of the results of the HTTP response is being shown in the parent component which results in the `checkBindingNoChanges` error. After looking at the examples and reading @robwormald his explanation [here](https://github.com/angular/angular/issues/17572#issuecomment-323465737) it makes sense.

A simple representation of the problem looks like this

**app.component.ts**
```ts
import { Component } from '@angular/core';
import { Store } from '@ngrx/store';

@Component({
  selector: 'app-root',
  template: `
    <div>
      Root counter: {{ counter$ | async }}

      <span *ngIf="counter$ | async">Not 0</span>
    </div>

    <counter></counter>
  `
})
export class AppComponent {
  counter$ = this.store.select(state => state.counter);

  constructor(
    private store: Store<any>
  ) { }
}
```

**counter.component.ts**
```ts
import { Component, OnInit } from '@angular/core';
import { Store } from '@ngrx/store';

@Component({
  selector: 'counter',
  template: `
    Counter {{ counter$ | async }}

    <button type="button" (click)="onIncrement()">+</button>
    <button type="button" (click)="onDecrement()">-</button>
  `
})
export class CounterComponent implements OnInit {
  counter$ = this.store.select(state => state.counter);

  constructor(
    private store: Store<any>
  ) { }

  onIncrement() {
    this.store.dispatch({
      type: 'INCREMENT'
    });
  }

  onDecrement() {
    this.store.dispatch({
      type: 'DECREMENT'
    });
  }

  ngOnInit() {
    this.store.dispatch({
      type: 'INCREMENT'
    });
  }
}
```

The cause of the error is the dispatch in the `ngOnInit` of the `CounterComponent`. Wrapping it in a `setTimeout` "works" but feels really hacky and looks like it defeats the purpose of using a Store.

So somehow I totally understand why it fails, because the check of the `app.component` has already passed and we're changing data which results in an update in the view. But on the other hand, it feels really weird when using ngrx because it's the single-source of truth. If the data in the store updates, it will result in an update in the view.

**Comment by guyjstitt** [comment]
Any update on the why this issue occurs or when it will be addressed? Ran across this bug today with the async pipe and can't quite comprehend why the previous value is still wrapped when change detection is run.

**Comment by StevenLiekens** [comment]
@guyjstitt there's a somewhat sensible explanation in [a previous comment](https://github.com/angular/angular/issues/18129#issuecomment-326801192). It took me some time to understand every part of it but it all sounds reasonable.

The fix is to just avoid the async pipe when you get hit by this issue... or write your own async pipe that doesn't wrap values.

**Comment by TrevorKarjanis** [comment]
In my case, moving the subject emission to the constructor solved the issue. Moving it to AfterViewInit did not.

**Comment by raduungurean** [comment]
It happened to me as well. It compares the old value (wrapped) with the current value (not wrapped). 

I am using angular 8.1.2

`<div>{{(items$ | async).length}}</div>`

In the ts file I have this:

```
constructor() {
  this.items$ = this.store.select(fromRoot.getAllItems);
}
```

**Comment by miguelalvarezi** [comment]
Just my two cents for others facing this issue: if it's an option for you to use the `OnPush` `ChangeDetectionStrategy` in your component, that's solved the `ExpressionChangedAfterItHasBeenCheckedError` issue for me when using complex ngrx selectors with the `async` pipe.

Credits go to [this answer in SO](https://stackoverflow.com/a/56664783/2747568).

**Comment by atscott** [comment]
Based on the discussion, I believe this is fixed in https://github.com/angular/angular/pull/36633. Also note that `WrappedValue` is now deprecated (see https://github.com/angular/angular/pull/36819) as it was essentially only present to support the async pipe. We could likely remove support for `WrappedValue` completely in change detection in the future.
