### ISSUE TITLE
Angular Release Schedule doc is out of sync

### ISSUE THREAD

**Issue by tytskyi** [angular/angular#18215]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Feature request
[x] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior

**Angular Release Schedule** https://github.com/angular/angular/blob/master/docs/RELEASE_SCHEDULE.md is out of sync

## Expected behavior

Version 4.3.0 expected at 2017‑07‑10, released at 2017‑07‑14. 4.3.0-beta/rc did not happen.
Version 5.0.0‑beta.0 did not happen at 2017‑07‑17.

## Minimal reproduction of the problem with instructions

See https://github.com/angular/angular/blob/4.3.0/docs/RELEASE_SCHEDULE.md

## What is the motivation / use case for changing the behavior?

I upgrade angular 2x to latest. Discovered bug in 4.3.0 (was earlier but fixed only after 4.3.0). Cannot properly plan when next release with the fix released so that i can bump to the version where bug is fixed.

## Environment
<pre><code>
Angular version: 4.3.0

Everything else is N/A

</code></pre>

**Comment by alxhub** [comment]
Hi @tytskyi,

Our releases do occasionally slip by a few days if CI is in a bad state, we have bugs that we want to get fixed in time, etc.

Also note that the column name of the date is titled `Week Of` - it's not the exact date we plan to release. 4.3.0 did go out the week of 2017-7-10, per our schedule. And I'm not sure what you mean by 4.3.0-beta/rc didn't happen:

```
$ npm view @angular/core versions | grep 4.3.0
  '4.3.0-beta.0',
  '4.3.0-beta.1',
  '4.3.0-rc.0',
  '4.3.0' ]
```

In general the schedule is a goal that we try to meet, not a guarantee. It's very rare for releases to slip more than a day or two.

**Comment by tytskyi** [comment]
@alxhub thank you, this totally makes sense. 

> And I'm not sure what you mean by 4.3.0-beta/rc didn't happen

My bad, i am checking only by CHANGELOG.md, not the npm itself.

**Comment by alxhub** [comment]
@tytskyi we're now merging all the beta/rc changes into the main release when it happens. 4.3.0 is the first one where we've done that.
