### ISSUE TITLE
Language service errors on possibly null binding when it's already checked

### ISSUE THREAD

**Issue by cyrilletuzi** [angular/angular#18248]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[X] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior
Given this component : 

```ts
@Component({
  template: `<div *ngIf="data"><p>{{data.title}}</p></div>`
})
export class TestComponent {
  data: SomeObjectInterface | null;
}
```

The language service raises the error `"The expression might be null"` on `data.title` but it's already checked by `*ngIf`.

## Expected behavior
Should not raise an error.

## Environment

<pre><code>
Angular version: 4.3.1
VS Code Angular Language Service extension 0.1.4
</code></pre>

**Comment by cyrilletuzi** [comment]
@chuckjaz Some news about this issue ?

**Comment by chuckjaz** [comment]
This will not be addressed until 6.0 as it will require a breaking change to the `NgIf` declaration that will not be ready in time for 5.0.

The template compiler does not know the runtime behavior of directives, including something as fundamental as `*ngIf`, therefore, there is currently no typing relationship that can be derived for `data` inside the template. This is similar to, for example, if you would have written the following in TypeScript:

```ts
function ngIf(condition: boolean, cb: () => void) { if (condition) cb()) }
ngIf(data, () => data.title);
```
[here](http://www.typescriptlang.org/play/#src=function%20ngIf(condition%3A%20boolean%2C%20cb%3A%20()%20%3D%3E%20void)%20%7B%20if%20(condition)%20cb()%3B%20%7D%0D%0A%0D%0Alet%20data%3A%20%7B%20title%3A%20string%20%7D%20%7C%20undefined%20%3D%20undefined%3B%0D%0A%0D%0AngIf(data%20%3D%3D%20null%2C%20()%20%3D%3E%20data.title)%3B%0D%0A) (turn on strict null option to see the error).

This will report that `data` could possibly be undefined in lambda because proving otherwise requires knowledge of the runtime behavior of `ngIf`.

To do this we could change the declaration of `NgIf` to something like what is implied by [this playground](http://www.typescriptlang.org/play/#src=class%20TemplateRef%3CT%3E%20%7B%20%7D%0D%0A%0D%0Atype%20NonNull%3CT%3E%20%3D%20T%3B%0D%0A%0D%0Adeclare%20function%20_NonNull%3CT%3E(t%3A%20T%20%7C%20null%20%7C%20undefined)%3A%20T%3B%0D%0A%0D%0Aclass%20NgIfContext%3CT%3E%20%7B%0D%0A%20%20%20%20%24implicit%3A%20NonNull%3CT%3E%3B%0D%0A%7D%0D%0A%0D%0Aclass%20NgIf%3CT%3E%20%7B%0D%0A%20%20%20%20constructor(templateRef%3A%20TemplateRef%3CNgIfContext%3CT%3E%3E)%20%7B%20%7D%0D%0A%0D%0A%20%20%20%20set%20ngIf(condition%3A%20T)%20%7B%20%7D%0D%0A%7D%0D%0A%0D%0Adeclare%20function%20_NgIf%3CT%3E(a%3A%20%7B%20condition%3A%20T%20%7D)%3A%20NgIf%3CT%3E%3B%0D%0Adeclare%20function%20_NgIfContext%3CT%3E(n%3A%20NgIf%3CT%3E)%3A%20NgIfContext%3CT%3E%3B%0D%0A%0D%0Alet%20data%3A%20string%20%7C%20undefined%3B%20%0D%0A%0D%0Aconst%20ngIf%20%3D%20_NgIf(%7B%20condition%3A%20data%20%7D)%3B%0D%0Aconst%20templateContext%20%3D%20_NgIfContext(ngIf)%3B%0D%0Aconst%20d%20%3D%20_NonNull(templateContext.%24implicit)%3B%0D%0A%0D%0A) (turn on strict null checks and see that `d` is inferred to be of type `string`).

This would be similar to rewriting the above as:

```ts
function ngIf<T>(condition: T | null  | undefined, cb: (condition: T) => void) {
  if (condition) cb(condition);
}

ngIf(data, data => data.title);
```

[here](http://www.typescriptlang.org/play/#src=function%20ngIf%3CT%3E(condition%3A%20T%20%7C%20null%20%20%7C%20undefined%2C%20cb%3A%20(condition%3A%20T)%20%3D%3E%20void)%20%7B%0D%0A%20%20if%20(condition)%20cb(condition)%3B%0D%0A%7D%0D%0A%0D%0Avar%20data%3A%20%7B%20title%3A%20string%20%7D%20%7C%20undefined%3B%0D%0A%0D%0AngIf(data%2C%20data%20%3D%3E%20data.title)%3B)

The new type checker is scheduled for 5.1 but this will not be included in it. As this is a breaking change it cannot happen till 6.0.

**Comment by cyrilletuzi** [comment]
Thanks for the detailed answer.

**Comment by thw0rted** [comment]
Hi, does this also apply to the case of type narrowing inside the if-condition itself, or is that a separate issue?

````
class Animal { }
class Bird extends Animal { public wingCount: number; }
    
@Component({
  template: `<div *ngIf="isBird(animal) && (animal.wingCount > 2)"><p>This is one crazy bird!</p></div>`
})
export class TestComponent {
  @Input() animal: Animal;
  isBird(a: Animal): a is Bird { return a instanceof Bird; }
}
````

In the current language service, the reference to `animal.wingCount` would be an error ("'Animal' does not contain such a member"), even though of course the AOT compiler gets through it just fine.

**Comment by cyrilletuzi** [comment]
Closing this as there are no errors anymore.

But for info, now it seems there is the opposite problem: object is not detected as potentially `null` when there is no `*ngIf`.

**Comment by thw0rted** [comment]
I don't think it's fixed on the templates, at least -- see my previous comment.  I don't run the language service directly (I guess via `tsc`?) but in VS Code (Salsa), I still get warnings in statements that would compile cleanly in non-template (`.ts` file) context.  In the above example, `*ngIf="isBird(animal) && (animal.wingCount > 2)` would have a red squiggle under `animal.wingCount` because `wingCount` is only defined on `Bird` and the language service doesn't treat `isBird` as narrowing the type, even though the actual compiler does.

Would it be better to re-open this issue, or to open a new issue specific to errors in the template itself?

**Comment by AnimaMundi** [comment]
@thw0rted The plugin for VSCode is using an older version of the Angular language service, so it would be better to open an issue here instead: https://github.com/angular/vscode-ng-language-service

See here: https://marketplace.visualstudio.com/items?itemName=Angular.ng-template

> This extension uses `@angular/language-service@5.2.2-250c8da` and `typescript@2.6.2`.

**Comment by fetis** [comment]
@cyrilletuzi I'm using the language service v6.0.6 in WebStorm and has this issue.

**Comment by inmogr** [comment]
@chuckjaz im having the same issue here

```
<div *ngIf="object">
	{{ object.someField }}
</div>
```

Could you please assist?

**Comment by youssefsharief** [comment]
I am having the same issue in 2019 with version 7
