### ISSUE TITLE
Child directive does not inherit parent directive's click handler

### ISSUE THREAD

**Issue by g1shin** [angular/angular#18331]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior

Child directive does not inherit parent directive's click handler.

## Expected behavior

Child directive should inherit parent directive's click handler.

## Minimal reproduction of the problem with instructions

http://plnkr.co/edit/6Q74FAmo9XkfIlYGaGt9?p=preview
Clicking on the base button logs 'click' on console, but clicking on the child button that extends the base button does not log 'click' on console.

## Environment

<pre><code>
Angular version: X.Y.Z

Browser:
- [x] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: XX  
- Platform:  

Others:

</code></pre>

**Comment by trotyl** [comment]
This is the expected behavior according to the [semantics described here](https://github.com/angular/angular/issues/11606#issuecomment-262315256):

> only use the last decorator of each kind (e.g. @component / ...)

The entire `@Directive` metadata on base class will be overwritten by `@Directive` defined in derived class.

When [changing to `@HostListener('click')`](http://plnkr.co/edit/cvoymb6a3VlC3CLBNPrC?p=preview) it will work as expected since it's a property decorator and didn't get overwritten.

"Fixing" this would be a breaking change for existing inheritance behavior.

**Comment by pkozlowski-opensource** [comment]
This works as expected in Angular v9 with ivy enabled: https://ng-run.com/edit/8KIr8DNkj82a7Fbj3Eyv
