### ISSUE TITLE
npm shrinkwrap modifying all the deps "from" in npm-shrinkwrap.json

### ISSUE THREAD

**Issue by vicb** [angular/angular#1834]
After I execute "npm shrinkwrap --dev" as indicated in the readme, all the deps have their from key modified:

```js
             "array-uniq": {
               "version": "1.0.2",
-              "from": "array-uniq@>=1.0.2 <2.0.0",
+              "from": "https://registry.npmjs.org/array-uniq/-/array-uniq-1.0.2.tgz",
               "resolved": "https://registry.npmjs.org/array-uniq/-/array-uniq-1.0.2.tgz"
             },
```

Any idea what's going wrong ?

**Comment by pkozlowski-opensource** [comment]
@vicb yeh, saw the same during 2 last updates to npm dependencies. At the beginning I thought it is due to npm version, but it seems like things are flipped back and forth between 2 different forms. Just compare my 2 PRs that were send in 2 consecutive days with the same npm version: e8ad0d177669cd7177d2f6936097831a5467a3c8 and f8f79dc76ce16b84b987ed3aef41480cca87cb7d.

Not sure what is going on here, I guess @IgorMinar might be more familiar with shrinkwrap quirks.

**Comment by vicb** [comment]
I've discussed with @IgorMinar: the changes in the shrinkwrap file are harmless and they do not occur in the clean version.

I leave this PR opened until @IgorMinar amend the readme with more info.
