### ISSUE TITLE
Animation Rotation Direction not correct in certain degrees

### ISSUE THREAD

**Issue by DanielYKPan** [angular/angular#18372]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ *] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior

In this demo, when the degree is 180, the rotation would change the direction.
Here is the [Demo](https://plnkr.co/edit/QUhF4GNssrJfvYLEtwGw?p=preview)
I have the similar issue when using wildcard `*`(this could referring to issue [#17565](https://github.com/angular/angular/issues/17565)

## Environment

<pre><code>
Angular version: 4.3.1

Browser:
- [*] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [*] Firefox version XX
- [*] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: XX  
- Platform:  

Others:

</code></pre>

**Comment by matsko** [comment]
This is unfortunately the problem of the web-animations API. Because it uses matrices, it will always transition to a destination matrix value and as a result the quickest path will be used. Therefore if a rotation is beyond 180 degrees then it will go from 180 -> 360 instead of 180 -> 0.

Unfortunately there's nothing that can be done about this. If you know of anything that's missing in the web-animations API that could help work against this default setting then that would be super helpful.

**Comment by DanielYKPan** [comment]
@matsko 
Thanks man
