### ISSUE TITLE
Broken link in docs

### ISSUE THREAD

**Issue by sdeering** [angular/angular#18415]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Feature request
[x] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior

When you go to this url it gives a 404 https://angular.io/guide/a1-a2-quick-reference

## Expected behavior

It redirects to the new page? is it this one? https://angular.io/guide/ajs-quick-reference

## What is the motivation / use case for changing the behavior?

Trying to learn the differences between ng2 and ng2

## Environment

<pre><code>
Angular version: X.Y.Z

Browser:
- [ ] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: XX  
- Platform:  

Others:

</code></pre>

**Comment by gkalpak** [comment]
@sdeering, where did you get that URL (https://angular.io/guide/a1-a2-quick-reference)?
It has been `ajs-quick-reference` on the site and I see it as `ajs-quick-reference` in the [old site][1] as well.

(Did it use to be `a1-a2-quick-reference` in the old site some time ago? That would explain ending up to `https://angular.io/guide/a1-a2-quick-reference`, because that is what `https://angular.io/docs/ts/latest/a1-a2-quick-reference.html` would be redirected to.)

[1]: https://v2.angular.io/docs/ts/latest/cookbook/ajs-quick-reference.html

**Comment by sdeering** [comment]
Yes i think it was an old link on a website. Thanks for fixing this up guys very much appreciated.
