### ISSUE TITLE
Documentation is difficult to scroll with a mouse on Windows

### ISSUE THREAD

**Issue by kglickman** [angular/angular#18426]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Feature request
[ X] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior

The scroll bar in the documentation is really skinny.  I have trouble keeping my mouse in it.  I finally gave up and had to read the doc on my tablet instead.

## Expected behavior

I am on Windows.  The scrollbar should be a normal Windows scroll bar.

## Environment
Windows
<pre><code>
Angular version: X.Y.Z  NA

Browser:
- [ X] Chrome (desktop) version 59.0.3071.115
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: XX  
- Platform:  

Others:

</code></pre>

**Comment by gkalpak** [comment]
The scrollbars are indeed pretty thin (at least on Windows), but I assumed this was a deliberate design decission (cc @sjtrimble, @IgorMinar).

That said, I rarely use the scrollbars for scrolling while reading through a document. I usually use mousewheel or up/down arrows.

**Comment by sjtrimble** [comment]
This was intentional but we can revisit to thicken a bit to make more usable.

**Comment by IgorMinar** [comment]
My understanding is that the scrolling can be controlled in several ways depending on the control device used:

- touch screen:
  - touch / flick
- touch pad:
  - touch / flick
  - scroll bars
- mouse
  - scroll wheel
  - scroll bars
- keyboard
  - up / down + page up / page down keys

the current design makes using scroll bars difficult to use, but given all the other options most of which provide much better control and UX, I don't believe that this is a big problem. In fact making the scroll bars bigger would make the UX worse for other workflows because of more visual space being used by the scroll bars.

**Comment by gkalpak** [comment]
We have reverted to using the default Windows scrollbars (instead of our thin, custom ones) some time ago, so this issue can be closed now.
