### ISSUE TITLE
Component stabilization/lifecycle hook.

### ISSUE THREAD

**Issue by matanlurey** [angular/angular#1842]
In Angular 1.0 Dart, there is an event called `attach` that can be used, e.g.

```dart
@Component(
  map: const {
    'allow-multi-select': '=>!allowMutliSelect',
    'items': '=>!items',
  }
)
class SelectComponent implements AttachAware {
  bool allowMutliSelect = false;
  List items;

 @override
  void attach() {
    // At this point, if 'allow-multi-select' and 'items' non-null, setters were called.
   doComponentInit();
  }
}
```

It's not clear how to reproduce this elegantly in Angular 2. One option would be using `onChange`:

```dart
@Component(
  properties: const {
    'allowMultiSelect': 'allow-multi-select',
    'items': 'items'
  },
  lifecycle: const [onChange]
)
class SelectComponent {
  bool allowMutliSelect = false;
  List items;

  void onChange() {
    // The difference between this and attach is this may be called multiple times.
    if (items != null) {
      doComponentInit();
    }
  }
}
```

Is something like 'attach' planned on being supported? Or we are expected to use onChange?

@yjbanov, who mentioned this offline. @jbdeboer may be interested.

**Comment by jbdeboer** [comment]
IIUC, the fundamental difference between ```attach``` and ```onChange``` is where the application's state is stored. With ```attach```, we compute and store state in the component during initialization.  With ```onChange```, the component is expected to react to any new data: the source of truth is elsewhere, not in the component.

Comparing the two, the ```onChange``` system is purer and more correct: components don't have stale data, therefore there are no inconsistencies in the app.

However, the down-side to ```onChange``` is that it makes components much more difficult to write as the component author needs to consider every sequence of data updates, most of which will never occur in a production application.

Because of this added complexity in ```onChange``` components, Angular should support ```attach``` as well.

To make the "stale state" bugs easier to detect, Angular could implement a check which gives a warning:
"The data dependencies of component X were updated, but your component did not react to that new data. Your app may be in an inconsistent state."

**Comment by yjbanov** [comment]
For this request to fit with ng2 we'd have to resurrect one-shot bindings. Do we want to do that?

**Comment by vicb** [comment]
James not sure what you mean by every sequence & onChange. The onChange would only be called when all the properties have been updated and not after each single property update of that helps.

**Comment by yjbanov** [comment]
@vicb, the issue is that `onChange` _can_ be called multiple times at all, which in ng2 is determined by the _user_ of your component, not by the component itself. This wasn't the case for `attach`. My view on this is that if the author of the component would like to receive bound values once and forbid any future updates, they could add an explicit guard in the `onChange` method. This workaround/pattern costs 3 lines of code, and therefore I don't think it's a big or urgent issue:

```dart
class MyComponent {
  bool _initialized = false;

  ... setters ...

  onChange(_) {
    if (_initialized) throw 'Only one-time bindings supported';
    _initialized = true;
    ... application logic ...
  }
}
```

**Comment by matanlurey** [comment]
Updates: 

1. Spoke with @rkirov and @vsavkin - they will be adding an `onInitialize` lifecycle event that will act similar to Angular 1's `AttachAware`. For the time being, we will use the boolean flag with `onChange` as a workaround.

2. Dart needs to use the interfaces, not `lifecycle: const [ ... ]` as the source of truth. Not doing so will result in dynamic call sites (bad) and will probably result in memory leaks as developers forget to set the lifecycle event, or extend from other components that need it without knowing.

**Comment by yjbanov** [comment]
>
>
>    1.
>
>    Dart needs to use the interfaces, not lifecycle: const [ ... ] as the
>    source of truth. Not doing so will result in dynamic call sites (bad) and
>    will probably result in memory leaks as developers forget to set the
>    lifecycle event, or extend from other components that need it without
>    knowing.
>
> I strongly agree. Current lifecycle is a workaround for JS (which doesn't
have reified interfaces) that makes no sense in Dart and is a needless
deviation from AngularDart's existing API.

**Comment by mhevery** [comment]
@vsavkin is Implementing this right now.

- Use implements in addition to `@Component.lifecycle`
- Create `InitAware.onInit()`
