### ISSUE TITLE
Angular triggers CORS on POST when it doesn't need

### ISSUE THREAD

**Issue by donkeybonks** [angular/angular#18450]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[X] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior
If you use `Http.post` it will trigger a pre-flight request. If your server doesn't support `OPTIONS`, you will get a `504` or similar error and it will fail. This is because it adds values to headers that are not allowed (`Accept` and `Content-Type` from what I can tell - see: https://developer.mozilla.org/en-US/docs/Web/HTTP/Access_control_CORS#Simple_requests ).

`Http.get` works fine out of the box.

## Expected behavior
Doesn't send `OPTIONS` request for a simple post.

## What is the motivation / use case for changing the behavior?
If you are using an external API and you can't just patch the server to support `OPTIONS`, this could be kind of annoying. The simple patch below saves an entire network round-trip for most requests.

## Workaround
If you add this to a `Http` interceptor, it will reset values to those that are allowed as mentioned above:
```
      req.headers.set('Accept', '*/*');
      req.headers.set('Content-Type', 'text/plain');
```
This fixed the problem for me.

**Comment by gkalpak** [comment]
There is not enough info for a proper investigation (e.g. a reproduction), but (as mentioned in the link you posted), setting `Accept` and `Content-Type` headers is fine, as long as `Content-Type` is one of `application/x-www-form-urlencoded`, `multipart/form-data` or `text/plain`. This would also explain, why explicitly setting the `Content-Type` header to `text/plain` might solve the issue.

If you don't set the headers explicitly, `HttpClient` will try to [detect the content type][1], based [on the request body][2]. In general, `HttpClient` will try to set reasonable defaults (based on common usages).

If you still think `HttpClient` should behave differently in a specific case, please post a concrete example or reproduction.

[1]: https://github.com/angular/angular/blob/9479a106bbc5a3fe99c6d80f12dbb3d23362f22a/packages/common/http/src/xhr.ts#L100-L101
[2]: https://github.com/angular/angular/blob/9479a106bbc5a3fe99c6d80f12dbb3d23362f22a/packages/common/http/src/request.ts#L267-L301

**Comment by kvanberendonck** [comment]
This very very basic example triggers pre-flight for me.
```
    return this.http
      .post('http://foo/bar', {})
```

**Comment by gkalpak** [comment]
<sub>(I just realized you could be using the old `Http` (from `@angular/http`), but the same rules apply more or less.)</sub>

So, since you are passing an object as `body` and do not set the `Content-Type` header explicitly, `Http` will try to [detect it based on the body][1]. And since your body is an object, `Content-Type` will default to `application/json`. This works as expected afaict, because that it the most common usecase (while posting JSON data to a cross-origin server that does not support OPTIONS, is a rather rare one).

Since `Http` is trying to optimize (e.g. reduce boilerplate) for the most common usecase, you have to do some extra work in your case:
1. Either explicitly set the `Content-Type` header to `text/plain`.
2. Or manually stringify the body (since passing a string as `body` will cause `Http` to detect the `Content-Type` header to `text/plain`).

[1]: https://github.com/angular/angular/blob/9479a106bbc5a3fe99c6d80f12dbb3d23362f22a/packages/http/src/static_request.ts#L109-L146

**Comment by kvanberendonck** [comment]
Using `''` instead of `{}` also worked for me, thanks.

**Comment by gkalpak** [comment]
> Even if `application/json` is the correct content type, `text/plain` is what most people will want in their production code, I would think.

I doubt that. (Keep in mind that the same rules apply to both same-origin and cross-origin requests - and the majority will be to same origin.)

cc @alxhub (who knows more about the `HttpClient` design)

**Comment by kvanberendonck** [comment]
ping @alxhub

**Comment by alxhub** [comment]
@donkeybonks Angular cannot know what the API you're using expects - if you hand it an object, it will serialize it as JSON, even if the object is empty.
