### ISSUE TITLE
How to access a singleton service from a custom class decorator

### ISSUE THREAD

**Issue by andrewvmail** [angular/angular#18565]
Is it possible to access a singleton service from a decorator function? i know decorator is run at build time. just wondering if there is a way. Im trying make a library and use the decorators syntax as the api.

Thanks in advance

**Comment by Toxicable** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).

---

If decorators are at build time as you say then how is it possible to access an instance of a class that's only instantiated at runtime?

**Comment by tytskyi** [comment]
@andrewvmail if you maintain your singleton manually, cheating Angular Dependecy Injection:
see https://github.com/kuuurt13/ng-block-ui/blob/v1.0.0-beta.12/lib/block-ui.module.ts#L10
and https://github.com/kuuurt13/ng-block-ui/blob/v1.0.0-beta.12/lib/decorators/block-ui.decorator.ts#L1

And please close the issue, since it is not an angular tracking issue.

**Comment by andrewvmail** [comment]
@tytskyi thanks thats what im looking for !
