### ISSUE TITLE
Template-defined form field validation persists when element is no longer present in DOM

### ISSUE THREAD

**Issue by cjc343** [angular/angular#18596]
## I'm submitting a...
<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[X] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior
When a form field's template defines that it is required, this validation requirement persists after the relevant field is no longer present in the DOM, but any bound criteria are no longer updated.

## Expected behavior
Template-defined validations are only applicable when present in the DOM **OR** bound criteria continue to be honored after removal.

## Minimal reproduction of the problem with instructions
http://plnkr.co/edit/RFtwDV2PxWUFeiV0tylN?p=preview

Click 'Toggle' twice. Required fields are shown and then hidden. Forms where controls were removed from the DOM remain in invalid state. Forms where controls remain in the DOM but are hidden by CSS continue to conditionally apply required state.

## What is the motivation / use case for changing the behavior?
Ability to conditionally set required state & hide or display form fields based on earlier choices.

## Environment

<pre><code>
Angular version: 4.3.3

Browser:
- [X] Chrome (desktop) version 60
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [X] Firefox version 54
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
</code></pre>

**Comment by kara** [comment]
If you want the existence of the input element in the template to affect the parent form's validity, it sounds like you want more of a template-driven approach.  In template-driven forms (FormsModule), the view is the source of truth, so if you remove a form control element from the DOM, its value is removed from the parent form and its validity no longer counts toward parent validity. See an example [here](http://plnkr.co/edit/r51ixZjf5m9e8aqEYIWU?p=preview) of what that looks like. The form is invalid when the input exists and invalid when it doesn't.

In reactive forms (ReactiveFormsModule), the source of truth is your form model (e.g. the `FormGroup` instance in your component class). Practically speaking, this means that your view does not necessarily represent the entirety of the form. So in your example, when you change the view, it's not expected that the model would remove that form control from validation. If you want that to happen, you must remove the form control programmatically with `removeControl` or `setControl` (then an `ngIf` expression could be bound to the existence of that control).

And by using the `required` attribute instead of `Validators.required`, you're using a template-driven validation approach with a reactive form. This means that the required validator won't be applied onto your form model until the form control element is added to the DOM by the ngIf.  That's why the form initially looks valid - because the form model doesn't know about your validator until the ngIf is toggled.  Generally, we don't recommend mixing approaches like this because it can have confusing results. Using `Validators.required` is more idiomatic for reactive forms and would result in your second recommendation (always honoring the bound value). See updated example [here](http://plnkr.co/edit/v1aSV7GFEnRmJDabEdu1?p=preview).

Closing, as this works as expected. To fix your problem, I'd recommend either switching to template-driven forms or adding in `Validators.required` to your existing reactive form.
