### ISSUE TITLE
history.pushState is not available in packaged apps

### ISSUE THREAD

**Issue by danny-swimmer** [angular/angular#18653]
## I'm submitting a...
[x ] Bug report

## Current behavior
I'm using angular 4.3.2. When running as a Chrome packaged app on a Chromebook, I get an annoying console error message every time I navigate to a new page. The error is "history.pushState is not available in packaged apps". 

## Expected behavior
This error should not be generated.

## What is the motivation / use case for changing the behavior?
The console is swamped with these errors.

## Environment
Angular version: 4.3.2
Chrome OS 59.0.3071.134

**Comment by vicb** [comment]
You should use your implementation of the Platform Location that do not use `history.pushState()`

**Comment by danny-swimmer** [comment]
Thanks @vicb for the suggestion.

According to the [router documentation](https://angular.io/guide/router#appendix-locationstrategy-and-browser-url-styles), pushState can be avoided by using the HashLocationStrategy:
"You can go old-school with the HashLocationStrategy by providing the useHash: true in an object as the second argument of the RouterModule.forRoot in the AppModule."

So that's exactly what I did:
  imports: [RouterModule.forRoot(routes, { useHash: true })],

However I still get the error "history.pushState is not available in packaged apps" in my chrome app.

**Comment by gkalpak** [comment]
AFAICT, this happens because of [this line][1]. In Chrome Packaged Apps, even trying to access the `pushState` property logs an error (which is harmless, but annoying).

For reference, [here][2] is how AngularJS tries to "sniff" Chrome Packaged Apps and avoid the warning/error (but it is not ideal either).

[1]: https://github.com/angular/angular/blob/56a5b02d047c4f490f2c2fc50af35b78ee30c0e2/packages/platform-browser/src/browser/location/history.ts#L10
[2]: https://github.com/angular/angular.js/blob/7019d9f27af2cba8e2760d40b330bd53333488eb/src/ng/sniffer.js#L23-L35

**Comment by jasonaden** [comment]
Closing as this was resolved above.
