### ISSUE TITLE
After Reactive form is disabled it makes the form invalid.

### ISSUE THREAD

**Issue by ylligashi** [angular/angular#18678]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior

When I disabled any control of the form ex:
<pre>this.form.controls['name'].disable(); </pre>
it makes the form invalid so the value: 
<pre> this.form.valid = false </pre>

## Expected behavior

The desired behavior would be to not change the validity of the form when the form is disabled.

## What is the motivation / use case for changing the behavior?

I am working with Reactive-form in case of submitting a form and communicate with service, and I want to disable the form while it is working with service and returning any response.

## Environment

<pre><code>
Angular version: 4.3.3

Browser:
- [ ] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: XX  
- Platform:  

Others:

</code></pre>

**Comment by kara** [comment]
@ylligashi There are four mutually-exclusive validation statuses: `valid`, `invalid`, `pending`, and `disabled`. When a form has the status "disabled", it is considered exempt from all validation checks. It cannot be both valid and disabled at the same time, so `form.valid` will always be false if the form is disabled.  In your case, it seems like you want to check the status property explicitly or gate your error messages on `invalid` instead of `!valid`. 

You can read more about statuses in the docs [here](https://angular.io/api/forms/AbstractControl#status).
