### ISSUE TITLE
Content projected into an ng-template should not be initialized without creating an embedded view

### ISSUE THREAD

**Issue by jelbourn** [angular/angular#18691]
In Angular Material, our tabs API looks like this:
```html
<md-tab-group>
  <md-tab label="Overview"> ... </md-tab>
  <md-tab label="API">      ... </md-tab>
  <md-tab label="Examples"> ... </md-tab>
</md-tab>
```

The template for the `<md-tab>` component looks like this:
```html
<ng-template><ng-content></ng-content></ng-template>
```

We then use this `<ng-template>` to manually create an embedded view based on which tab is active. However, the contents of each tab are _all_ initialized automatically before any embedded view is created. This can lead to less-than-ideal performance scenarios, since far more content than is necessary can be initialized. It's also worth noting that the "phantom" component instances in the content aren't destroyed immediately (even though they're not rendered anywhere), so they're likely taking up memory and cycles for no reason.

[Plunker example of this behavior.](http://plnkr.co/edit/I0LMK3CkkA319NxQeVMn?p=preview)

Chatted w/ @robwormald and @mhevery and both agreed that behavior does seem unexpected since `ng-template` is supposed to be inert until it is embedded. 

cc @pkozlowski-opensource who mentioned that this is of interest for ng-bootstrap as well.

**Comment by youdz** [comment]
I don't want to start long debates in GitHub issues, but I have to post here because I'm really surprised by the change of heart if this request is accepted.

As a consumer of component libraries, I have no idea whether the internal implementation of a third-party component projects my content "normally" or whether it projects it into an `<ng-template>`. If I write:
```html
<material-component>
  <my-component></my-component>
</material-component>
```
I cannot guess that `<my-component>` will be projected inside a template. So I have no idea whether my component will be instantiated zero times, one time or 42 times until I actually run the app. If Angular Material changes the internal implementation of the `<material-component>` from projecting into a template to not, or the reverse, I would have actual different behaviors in my app with no change at all on my side and these differences might severely impact performances since they're related to components lifecycle and eager instantiation.
What is preventing Material from simply asking the consumer for a template or a custom structural directive as part of their API?

I believe there was a firm stance on single-instantiation for ng-content, hence my surprise regarding @mhevery apparently approving this request.

**Comment by pkozlowski-opensource** [comment]
> I believe there was a firm stance on single-instantiation for ng-content, hence my surprise regarding @mhevery apparently approving this request.

@youdz we've discussed this extensively offline with @jelbourn and @mhevery and the status for now is that there is no "change of hearts". Actually arguments are _exactly_ the ones that you are bringing up here. So we are on the same page.

> What is preventing Material from simply asking the consumer for a template or a custom structural directive as part of their API?

IMO this is the crux of the issue - seems like syntax involving "a template or a custom structural directive" is not exactly the API that Material users want to see.

**Comment by mhevery** [comment]
I think we should close this issue to prevent confusion.
