### ISSUE TITLE
Angular Example - Dynamic Component Loader Plunker broken

### ISSUE THREAD

**Issue by DrMabuse23** [angular/angular#18697]
Hi i read (dynamic-component-loader )[https://angular.io/guide/dynamic-component-loader] and the plunkr doesnt work ! Maybe it would be nice to fix that. I try to fix it but i`am not familiar with Systemjs so i don`t no why he cant load the ad-banner.component

greetz

**Comment by aravindfz** [comment]
You can use this [blog post](https://medium.com/@aravindfz/load-modal-component-dynamically-in-angular-5fda8e1dc3e7) for reference.

**Comment by DrMabuse23** [comment]
yes but is this standard thats the examples on the official page doesn`t work ?

**Comment by mlc-mlapis** [comment]
@DrMabuse23 ... hmm, the problem is on the line with `ngAfterViewInit` in `ad-banner.component.ts`. There should be just `ngOnInit` instead. The explanation is that the plunker is using the LATEST version of Angular. The problem with `ExpressionChangedAfterItHasBeenCheckedError` appeared when some changes in previous version of Angular affected indirectly the plunker code in this case.

**Comment by DrMabuse23** [comment]
ok thanky you very much
