### ISSUE TITLE
Register Multiple Interceptors in NgModule in Angular

### ISSUE THREAD

**Issue by rahulrsingh09** [angular/angular#18696]
I am trying to register multiple Interceptor in NgModule , But only one seems to Fire the other just dosent work.

```
    { provide: Http, useClass: AuthenticatedHttpService },
    { provide: Http, useClass: LoaderHttpService }
```

If i remove any one of the them the other works but if not only LoaderHttpService Works.

The reason for Having two interceptors is that One is for Loader spinner and other for a 401 error response.

How to Make this work in Angular as it was with Angular JS

**Comment by Toxicable** [comment]
I think you might be getting a little confused on what Interceptors are in Angular.
What you are doing is providing a different class for the same token, this isn't providing a Interceptor.
Take a look here on how to use Interceptors https://angular.io/guide/http#intercepting-all-requests-or-responses
Take a look here for how providing works in NgModules
https://angular.io/guide/dependency-injection-in-action

**Comment by rahulrsingh09** [comment]
@Toxicable So what you are suggesting is that we can only have a single interceptor for all requests and do everything inside that ? as i am using the provide and use class by use two i am overriding the class above is that right ?

**Comment by erichfosse** [comment]
@rahulrsingh09 Your code snippet is trying to tell Angular to use AuthenticatedHttpService when you ask for Http in your app.

You can read it as "when Angular is providing 'Http', instead, use the class 'AuthenticatedHttpService'". This is not the way to register interceptors.

To register interceptors, you need to use the HttpClientModule instead of the older HttpModule, and when registering your interceptors you need to do the following:

```
@NgModule({
  providers: [{
    provide: HTTP_INTERCEPTORS,
    useClass: AuthenticatedHttpService,
    multi: true,
  },
  {
    provide: HTTP_INTERCEPTORS,
    useClass: LoaderHttpService,
    multi: true,
  }],
})
```

Note that the 'multi' property tells Angular that there are more than one interceptor.
Also note that the interceptors will be loaded in the order you provide them.

Hope this helps.
