### ISSUE TITLE
[i18n] follow up for PR 18284 (moving away from the Intl API)

### ISSUE THREAD

**Issue by vicb** [angular/angular#18763]
@ocombe 

Could you please generate a file named `locale_all.ts` in the folder `common/i18n-data` with the following structure:

```ts
// import all locales
import af from './locale_af';
import ardz from './locale_ar-DZ';


import {registerLocaleData} from '@angular/common';

let locale: any;

// add cases for each locale
switch (goog.LOCALE) {
  case 'af':
    locale = af;
    break;
  case 'ar_DZ':
  case 'ar-DZ':
    locale = ardz;
    break;
  default:
    locale = en;
}

registerLocaleData(locale);
```

The model is https://github.com/google/closure-library/blob/048a4c201e1b3c40ef55ba753aabe7287ce341a0/closure/goog/i18n/datetimepatterns.js#L2134

The rationale is that this file will be included automatically when building the `CommonModule` with closure. The effect will be that the data for the target locale will be included and all other files will be tree shaken away.

Edit: We probably do not want all the locales in the imports and switch case. Please add the ability to pass a list of locales to your generation script. Thanks !

**Comment by ocombe** [comment]
Fixed in https://github.com/angular/angular/pull/18284
Generated `locale_all.ts` file: https://github.com/ocombe/angular/blob/6c05b8ab37ad75f040b0344a89f658a36509ba9a/packages/common/i18n_data/locale_all.ts

You can call the gulp task with `gulp cldr:extract --locales=fr,en` to only generate the `locale_all.ts` file with the locales `fr` & `en`.
