### ISSUE TITLE
Allow state queries within animations: state('x', query(...))

### ISSUE THREAD

**Issue by intellix** [angular/angular#18775]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[x] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior

Currently there's no way to apply state to children through querying. So I have to apply the same triggers to each of the child elements.
```ts
trigger('fade', [
  state('yes', style({
    opacity: .5,
  })),
]),
```

```html
<div>
  <span [@fade]="side.amount === 0 ? 'yes' : 'no'">1</span>
  <span [@fade]="side.amount === 0 ? 'yes' : 'no'">2</span>
  <span [@fade]="side.amount === 0 ? 'yes' : 'no'">3</span>
  <span [@fade]="side.amount === 0 ? 'yes' : 'no'">4</span>
</div>
```

## Expected behavior

I'd like to be able to query children within a container. You can only query within a transition currently and then there's no state to hold them.
```ts
trigger('fade', [
  state('yes', [
    query('span', [
      style({
        opacity: .5,
      }),
    ]),
  ]),
]),
```

```html
<div [@fade]="side.amount === 0 ? 'yes' : 'no'">
  <span>1</span>
  <span>2</span>
  <span>3</span>
  <span>4</span>
</div>
```

## What is the motivation / use case for changing the behavior?

I want to fade out a couple of children within a container. I'd expect that I can just add a trigger to the parent and then query for the children and set their state. Then I can transition to them using the transitions and query.

**Comment by matsko** [comment]
So I thought about this for a while and decided not to do this. The reason being is that animation `@trigger` state styles (when the animation is done) are another layer of styling much like `style` is another layer atop of selectors. This has been easy to manage since `@trigger` states are just on a single element.

Adding query to this adds another dimension of complexity that is too cumbersome to deal with. Issues like CSS specificity, specificity among parent/sibling animations as well as parent animations that query into children and then set a queried end state as not trivial to solve. How do you know which one to use? The framework would ultimately need to devise a specificity ranking system. And that's not worth maintaining.

I did however think about how this can still be achieved using the current system. There are two ways:

1) Use a parent animation (like in your example) and set the default CSS styling on each of the elements inside. Then depending on what state gets hit you can add a different styling to it. Then you can change the styling to other values from the start of the animation and animate to the `*` auto value. Not ideal, but it works.

2) This is the better solution. Add a `@child` animation to each list item and specify the end state values using `state()` inside of that animation definition. If you need to use a dynamic value (something a binding value would pass into the animation) then you can do this:

```ts
state('yes', {
  opacity: "{{ opacity }}"
}, { params: { opacity: 1 }))
```

Then in the template you can pass that value via:

```html
<span [@child]="{value:'yes/no', params: { opacity: 0.5 }}"></span>
```

Once again the HTML is verbose, but this gives you the most flexibility.

Since this is using an animation trigger for each inner item, the parent animation can use `animateChild()` to allow each inner animation to run (or not run) and decide exactly when the end state is achieved.

**Comment by fxck** [comment]
I don't get it. What is `query` useful for then, if you can't make the transitioned state stick?

**Comment by fxck** [comment]
Also the "better" solution doesn't seem to work properly when used along staggers and delays.. https://stackblitz.com/edit/towerpark2-92yiwh?file=app/homepage-item/homepage-item.component.html @matsko

**Comment by fxck** [comment]
@matsko could you elaborate more on that second, better solution? I keep bumping into this..

**Comment by fxck** [comment]
Maybe I'm missing something, but it feels like there's simply no use of query when you can set the default state of queried elements..

**Comment by leonardopaiva** [comment]
I was looking for the same feature, i need set the final state from my query elements... so i will be trying matsko suggestions...

about what matsko said:
```
state('yes', {
  opacity: "{{ opacity }}"
}, { params: { opacity: 1 }))
```

any one having problem to make it work see my example:
https://github.com/leonardopaiva/angular-animation-basic-project/blob/master/src/app/project/animations.ts
@fxck that will help you if you didnt realised yet

**Comment by bobrosoft** [comment]
Just faced it now ... really, without possibility to use `query` inside `state` or possibility to stick on final animation step as with `animation-fill-mode: forwards`  makes `query` mostly unusable for complex animations 😭 😭   I have animating gifting box where box lid and internals should be animated in sequence one by one. All goes well until final step -- all animated pieces reset to initial positions and there's no way I found to prevent that...   "Solved" that issue atm by assigning different trigger to every box piece separately which seems not right imho 🤦‍♂️  Also because of that animation pieces become separated and should be controlled independently with delays :(

```
    trigger('box', [
      transition(':enter', [
        style({opacity: 0}),
        animate('600ms', style({opacity: 1}))
      ]),
    ]),
    trigger('boxTop', [
      state('opened', style({transform: 'rotateZ(75deg)'})),
      transition('closed => opened', [
        animate('1300ms cubic-bezier(0.645, 0.045, 0.355, 1)')
      ])
    ]),
    trigger('boxOverlay', [
      state('opened', style({opacity: '0'})),
      transition('closed => opened', [
        animate('2000ms 1300ms') // delay here to sync with boxTop
      ])
    ]),
```

**Comment by TehWazzard** [comment]
The topics closed, however, this seems to be the best resource on the topic. I have an interesting struggle that may support the idea (or perhaps there's a better way ?)

What I'm trying to do here is hide some table columns classed "full"  and then reduce the table width.  the endgame here is to reduce a full table to a side-by-side view with a list a detail panel.

I've defined the following trigger:

`trigger('tableAnimation',
    [
      state('full', style({
        width: '100%',
      })),
      state('shared', style({
        width: '25%',
      })),

      transition('full => shared', [
        group([
          query('.full', [
            animate('100ms', style({ opacity: 0 }))
          ]),
          query(':self', [
            animate('1s', style({ width: '25%' }))
          ])
        ])
      ]),
      transition('shared => full', [
        group(
        [
          query(':self',
          [
            animate('1s', style({ width: '100%' }))
          ]),
          query('.full',
          [
            animate('100ms', style({ opacity: 1 }))
          ])
        ])
      ]),
    ])`
