### ISSUE TITLE
Angular 4 - CSS and app breaks in browsers IE and Edge

### ISSUE THREAD

**Issue by karthikbhat46** [angular/angular#18806]
I am getting this error in "EDGE" 

> Uncaught (in promise): TypeError: Assignment to read-only properties is not allowed in strict mode
> TypeError: Assignment to read-only properties is not allowed in strict mode

And in "IE", the UI is breaking.

How can i solve this issue? Any idea?

**Comment by ericmartinezr** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).

**Comment by vicb** [comment]
@karthikbhat46 with so little context there is no way for us to know if the issue is from Angular or from your own code. If you can reproduce the issue in a minimal app and share the code we could help better (and fill out the issue template).

Please open a new issue when you can provide more context. Thanks.
