### ISSUE TITLE
HTML-tag attribute "template" removes the element

### ISSUE THREAD

**Issue by MickL** [angular/angular#18828]
## I'm submitting a...
<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[X] Bug report
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request
</code></pre>

## Current behavior
Using an html-element like `<i></i>` or `<custom-element></custom-element>` with the attribute `template` totally removes the HTML-element.

## Expected behavior
HTML-element should be rendered normally.

## Minimal reproduction of the problem with instructions
Add `<i template="normal">Hello!</i>` to a component's template

## What is the motivation / use case for changing the behavior?
I got a custom-widget from a third-party software company which looks like: 
```
<opta-widget template="normal" matchId="123"></opta-widget>
```

But it doesn't get added to the DOM because of the `template` attribute.

## Environment

<pre><code>
Angular version: 4.3.4

**Comment by pkozlowski-opensource** [comment]
In fact it doesn't _remove_ it but rather turns it into `<template><i></i></template>` - this is part of the syntax sugar for structural directives (see https://angular.io/guide/structural-directives#microsyntax for more info).

The good news is that this part of the micro-syntax got deprecated in Angular 4 and you should be getting run-time warning about usage of the `<template>` element (check http://plnkr.co/edit/tpl:AvJOMERrnz94ekVua0u5). In Angular 5 support for  the deprecated `<template>` gets removed altogether and the `<ng-template>` will be the only way to go.

Unfortunately we can't "fix" this in Angular 4 as it would be a breaking change. But what you can do is to pass the `enableLegacyTemplate`( equal to `false`) option to the Angular compiler to opt-out from messing with `template` elements and attributes.

I'm going to close this issue as it is fixed in Angular 5 and not-fixable in Angular 4 (but work-arounds exist).

**Comment by MickL** [comment]
Thanks for your detailed answer. Yes i was wondering about the template deprecated message. Thanks ill try the option!

**Comment by MickL** [comment]
@pkozlowski-opensource The options seem not to work currently: https://github.com/angular/angular/issues/15555

I tried to add it within main.ts an tsconfig.json

**Comment by MickL** [comment]
@pkozlowski-opensource I do now have the problem that i cant bind to the custom element. I tried:
```
<any-widget [matchId]="id"></any-widget>
```

and

```
<any-widget matchId="{{id}}"></any-widget>
```

Do you have any idea how to do it?
