### ISSUE TITLE
Implement `getLazyRoutes` in new compiler

### ISSUE THREAD

**Issue by filipesilva** [angular/angular#18834]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[x] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior

Obtaining the list of lazy routes in an Angular Program requires usage of a private api in `compiler-cli`:

```
import { __NGTOOLS_PRIVATE_API_2 } from '@angular/compiler-cli';
// ...
return __NGTOOLS_PRIVATE_API_2.listLazyRoutes({
	program: this._program,
	host: this._compilerHost,
	angularCompilerOptions: this._angularCompilerOptions,
	entryModule: this._entryModule
});
```

## Expected behavior
The `getLazyRoutes` in `compiler-cli/src/transformers/program` is implemented (https://github.com/angular/angular/blob/master/packages/compiler-cli/src/transformers/program.ts#L135).

## What is the motivation / use case for changing the behavior?

Providing a public API for this functionality.

/cc @tbosch

**Comment by robwormald** [comment]
I think should be `getLazyModules` - there are a ton of use cases where you'd want to lazy load NgModule(Factories) outside of the Router (dashboards, etc) - we should also move the `LAZY_ROUTES` token...

**Comment by Toxicable** [comment]
@filipesilva Forgive me if we're on different pages here but what do you mean by "Angular Program"? are you talking about the dev time, build time or after build (factories).
If you're talking about doing post build work on some factories then you can already achieve this by traversing the `ROUTES` tokens and resolving the `loadChildren`'s. I've actually built a little tool that does exactly that here 
https://github.com/Toxicable/universal/blob/routes-ls/modules/ng-ls-routes/src/ls-routes.ts
Either way I think this would be a great feature since you wouldn't need that tool I built anyway.
Also if it helps, the use case I built it for was when you want to `pre-render` all static routes of an App

**Comment by filipesilva** [comment]
@robwormald I agree that both of those should be addressed (https://github.com/angular/angular-cli/issues/4541 and https://github.com/angular/angular/issues/18093 go more in depth about this topic). At the moment I was only looking for feature parity though.

@Toxicable Angular v5 has a much improved `ngc` which I'm trying to integrate into Angular CLI. It includes a new API that has Angular specific counterparts of Typescript `program`, `compilerHost`, which allow for compiling Angular applications in a single go instead of using `ngc` and then `tsc`.

In Angular v4 we'd use that private API (`__NGTOOLS_PRIVATE_API_2.listLazyRoutes`) to get a map of lazy routes so that we can tell webpack which extra chunks should be generated (https://github.com/angular/angular-cli/blob/master/packages/%40ngtools/webpack/src/plugin.ts#L288-L305). But now a new API is available  and it has that stubbed method that should be used instead. I created this issue to track work on it.

**Comment by tbosch** [comment]
That new API is still private for now (as everything else in
@angular/compiler_cli), as we might need to change it between major
releases.
This is ok for the cli as we are working closely together

**Comment by gkalpak** [comment]
Since there is now a [listLazyRoutes()][1] method (which is also used by the CLI - e.g. [here][2]), so I believe this can be closed.

[1]: https://github.com/angular/angular/blob/96f15f0de92745a661b4e8cd19f33cffb9b3f42c/packages/compiler-cli/src/ngtsc/core/src/compiler.ts#L517
[2]: https://github.com/angular/angular-cli/blob/2e3b9541e7357e2512f6148183e15696a1ad9622/packages/ngtools/webpack/src/ivy/plugin.ts#L569
