### ISSUE TITLE
[i18n] AVAILABLE_LOCALES is too big (2700 Bytes)

### ISSUE THREAD

**Issue by vicb** [angular/angular#18855]
@ocombe `AVAILABLE_LOCALES` is ~2700B.

We really don't want this in all apps.

Could you work on removing this.

**Comment by ocombe** [comment]
I can remove it, but then it will change the behavior of `findLocaleData` because I will not be able to know if a provided locale is correct or not:
- I cannot throw when the locale is incorrect, I can just throw that I didn't find it and you should add locale data for it
- I cannot throw when a correct locale has no data IF its parent locale is registered, e.g. if data for "fr" is available and you ask for "fr-BE" it will not throw, it will just take "fr" data (the parent locale) even if you really should be using "fr-BE" data instead

If this seem ok for you, I can remove this list.

**Comment by ocombe** [comment]
which one do you prefer? not searching for a parent locale, ou defaulting to the parent is there is no data? (fr-BE --> fr)

**Comment by vicb** [comment]
Any good reason why `en` should be different  ? 
If not please use the parent when the finer one is not available.

**Comment by ocombe** [comment]
Because we default the LOCALE_ID to "en-US" which doesn't exist in CLDR data and we want Angular to work ;-)
Ok for the parent by default
