### ISSUE TITLE
Web component connectedCallback prevented in application root component

### ISSUE THREAD

**Issue by calebdwilliams** [angular/angular#18909]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[X] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior

**Angular 4.3.6**
Running a `customElement` inside of the application root component somehow blocks the element's `connectedCallback` (specifically regarding getting attributes) from executing; however, a `customElement` placed inside a router outlet works fine.

## Expected behavior

Elements created using the `CUSTOM_ELEMENTS_SCHEMA` and `customElement` should behave per the W3C spec regardless of location inside the application.

## Minimal reproduction of the problem with instructions

https://github.com/calebdwilliams/Angular-Web-component-bug/tree/master (repo)
https://calebdwilliams.github.io/Angular-Web-component-bug/ (GitHub pages)

Create a `customElement` and place it inside the application's root component. If the code inside the `connectedCallback` is set to execute immediately, any references to `HTMLElement.getAttribute` will fail to execute; however, wrapping the contents of the method in a `setTimeout` will work correctly.

## What is the motivation / use case for changing the behavior?

Not correcting the behavior would result in many W3C-compliant custom elements not working correctly if placed inside an application's root component.

## Environment

<pre><code>
Angular version: 4.3.6

Browser:
- [X] Chrome (desktop) version 60
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX

Others:

Using the `webcomponentsjs` npm package.
</code></pre>

**Comment by jcdalton2201** [comment]
This an major issue for us on a single page app with no route.

**Comment by robwormald** [comment]
I pulled your repro down and ran it locally. Angular doesn't do anything special for a custom element (over a DOM element)

Note that Angular is *imperatively* creating the elements under the hood, something like:
```ts
let el = document.createElement('my-element');
el.setAttribute('foo', 'bar');
```
so I'm not sure how we could be deviating from the spec here?

**Comment by calebdwilliams** [comment]
@robwormald, Is the router module creating these elements differently? It looks like attributes aren't getting set properly in the root component which is making the `connectedCallback` to behave incorrectly. Setting the timeout does cause it to work properly, so I would imagine there's some async issue/race condition going on.

**Comment by robwormald** [comment]
> It looks like attributes aren't getting set properly in the root component which is making the connectedCallback to behave incorrectly
I don't mean to be pedantic here, but as far as I can tell, it *is* behaving properly. It's called, by the *browser*, when the element is inserted into the DOM. It seems like you're relying on ordering? and getting an unexpected result. See https://jsfiddle.net/thk72sg8/ - lifecycle callbacks will fire in different orders depending on how the components are instantiated. 

The CE spec provides `observedAttributes` for this purpose - so you're not dependent on the order of things firing.

**Comment by robwormald** [comment]
See also https://developers.google.com/web/fundamentals/architecture/building-components/best-practices (specifically the lazy stuff) - cc @robdodson

**Comment by jcdalton2201** [comment]
I wonder how this is behaving properly? If you do a this.attributes in the connectionCallback you will see inner-text in the NameNodeMap including the _ngcontent-c*. (not sure why angular is adding _ngcontent to a element that is not part of its code).  but on the next line you try to get either one of these attributes with getAttributes or hasAtrributes you get null or false.  This works fine with a plain web app or recact. It would be different if the element was being added via javascript but this is in line html. unless the template engine is parsing this as an angular element instead of an web component.

**Comment by robwormald** [comment]
The element *is* being added via Javascript :) Angular templates are compiled into imperative JS code (that's what "compilation" is in Angular).

So - it's entirely possible that internally, we're generating code like
```ts
const el = document.createElement('x-foo');
parentEl.appendChild(el);
el.setAttribute('x-attr', 'blah');
```
Which would fire the connectedCallback before the attribute is set (giving you a `null` value...). One of the sticky things about Custom Elements is that there is *no spec* defining how the above is done. This falls into the realm of best practices for *authoring* Custom Elements. 

We're looking into better interop with CE (specifically around slots and the like), but defining what the "correct" behavior here is difficult, and there's no guarantee that any consumer of your CE would treat it the same way - this is why using the `attributeChangedCallback` is a good idea, because it will fire for each changed attribute, regardless of when in the lifecycle they are set.

**Comment by jcdalton2201** [comment]
so then the ng-router handle templates different from the main template engine?

**Comment by robwormald** [comment]
Potentially, yes. One is part of statically generated code, one is dynamically inserted. Both are inserted into the DOM via JS, however. Best not to rely on any specific behavior in either case.

**Comment by jcdalton2201** [comment]
should are you not set the attributes before appendchild is called?

**Comment by calebdwilliams** [comment]
@robwormald OK, I definitely see _why_ this is happening, but I would question if it _should_. Given the way the language works, it would be reasonable for a developer to assume that their custom element would behave the same way it would when added to HTML (since we are using html files for our templates and not some abstraction in JS).

At the end of the day, I won't argue with you about best practices, it should be on the author to make sure it works, but the same should be said for a framework author (especially one as widely-used as Angular is) to 
* understand how the framework's users will expect it to behave, if not, you should be explicit about proscribing best practices.
* be consistent in implementation; even if you choose not to pursue a fix for this defect, it stands to reason how Angular treats custom elements should be standardized so that elements in a root and in a route behave the same way.

I guess I'm just going to keep coming back to the point that I never intended to insert an element without an attribute, Angular made that decision for me. My intent, based on the HTML template, was clearly to add an element with an attribute. I don't necessarily want the overhead of the observed attribute watcher or to enable an API for my element that I don't need.

**Comment by robdodson** [comment]
> I don't necessarily want the overhead of the observed attribute watcher or to enable an API for my element that I don't need

I think you'll need to use `observedAttributes` regardless. Ignoring Angular for a moment, it's totally reasonable for a user of your element to do the following:

```
var el = document.createElement('abstract-button');
document.body.appendChild(el); // connectedCallback runs
el.setAttribute('inner-text', 'Hello, World!');
```

Without the `observedAttributes` array + `attributeChangedCallback` your element would appear to be in a failed state, even though the user did eventually set the attribute.

My advice, for primitive data (strings, numbers, booleans) is generally to follow a pattern like this:

```js
class MyElement extends HTMLElement {
  static get observedAttributes() {
    return ['foo'];
  }

  get foo() {
    const value = this.getAttribute('foo');
    return value === null ? 'some default value' : value;
  }

  set foo(value) {
    this.setAttribute('foo', value);
  }

  attributeChangedCallback(name, oldVal, newVal) {
    // Handle any side effects in here.
    if (name === 'foo') {
      // update your text content or do other fancy stuff
    }
  }
}
```

This has the effect of synchronizing your attributes and properties (setting `.foo` also sets the attribute and vice versa). And this is the model that modern HTML5 elements follow. A good example being the `.preload` property/attribute on `<video>`.

If it's any help [I did a talk at the recent Polymer Summit](https://www.youtube.com/watch?v=sK1ODp0nDbM) to try to identify some best practices and explain the reasoning behind them. At the end of the day, a custom element just needs to be super resilient because you never know what context it will be used in. But I think it's totally achievable, just takes a bit of work 😄

**Comment by calebdwilliams** [comment]
@robdodson @robwormald I'll accept that feedback as to the structure of my web components, but the point remains that Angular is attempting to emulate the feeling/behavior of writing HTML and it isn't delivering using this model, that _is_ an issue. This ultimately isn't a question about web components. It is, however, a question of how Angular renders web components.

If you let me write HTML and use my components, I should be reasonably sure that they will behave as if they were written in HTML. 

Expecting every user to ever use a custom element to conform to your notion of best practices—regardless of that point's merits or demerits—will only lead to a poor developer experience. Fixing the issue will, in the long term, benefit the framework.

**Comment by calebdwilliams** [comment]
@robdodson 
> Ignoring Angular for a moment, it's totally reasonable for a user of your element to do the following:
Like I said, you are right, a developer may do that, but Angular should not.

**Comment by tx-tim** [comment]
> I think you'll need to use observedAttributes regardless. Ignoring Angular for a moment, it's totally reasonable for a user of your element to do the following:

Really appreciate the clarification and the example @robdodson

I do find it troubling that a CE can be treated one way in the app-root and another way in app-router.  Nice observation @calebdwilliams

**Comment by robwormald** [comment]
@calebdwilliams it's important to understand that angular does not treat Custom Elements in any special way, and we do not have any custom handling for them (this is in fact, one of the early design principles of Angular). we treat them like every other DOM element, and thus your custom elements should act like any other DOM element, and should not require any custom handling. Keep in mind that the lifecycle may differ even in an Angular application - that is, we'd handle `<x-foo some-attribute="some string literal">` in a different fashion than `<x-foo [attr.some-attribute]="someBoundValue">` - the latter needs to be integrated into Angular's change detection cycle, whereas the former is static. 

as far as why the behavior differs between the root and elsewhere, we'll look into it, but having spoken to the compiler team, we're not going to guarantee any specific ordering or behavior - doing so would lock Angular into a pattern we'd have to support indefinitely, potentially preventing us from under-the-hood optimizations in the future.

**Comment by calebdwilliams** [comment]
@robwormald I understand what you're intending to do, but it feels like a fairly proscriptive take on rendering elements (there could be a legitimate reason for not wanting to allow an element to be reactive). But again, my belief is that if you're going to let users author their code in an HTML format, you need to be sure to emulate the behavior the browser would when parsing that HTML.

Ultimately, I completely agree with you and Rob's assertions about custom elements—and have actually changed the structure of my components accordingly—but this will give more than a few developers headaches in the future as custom elements become more widely used.

**Comment by mattdsteele** [comment]
Another data point: I just ran into this as well.

We were hoping to use attrs in our WCs for initialization only (and thus only check them in `connectedCallback`), and then keep things up to date via props. But Angular's algorithm breaks this, which was unexpected (especially given that I authored the HTML in the template as `<custom-el attr="blah">`).

**Comment by vinayk406** [comment]
What might be the reason for setting the attributes after attaching the node to the DOM instead of setting the attributes and then attaching to the DOM?

**Comment by robdodson** [comment]
> We were hoping to use attrs in our WCs for initialization only (and thus only check them in connectedCallback), and then keep things up to date via props.

An alternative would be to observe them with `attributeChangedCallback` and run some logic once everything is defined. This is not as straightforward as just doing it in connectedCallback, but as stated elsewhere in the thread, you never have a guarantee of how a user is going to use your element. To be robust, it should respond to change and handle being used in different ways. Imagine if you could only use built-in HTML elements if you added them to the page in just the right way.

**Comment by calebdwilliams** [comment]
While I agree that it is an alternative (and probably even a best practice), it shouldn't be a necessary one if we're to assume that we're writing HTML. 

Your abstraction layer should reflect the behavior of what you're abstracting.

**Comment by ctaepper** [comment]
I "fixed" this problem by adding a `*ngIf="true"` to the element

my webcomponent looks something like `<custom-element class="nice-class"></custom-element>`

somehow, in the root component, Renderer2 appends the element, before it is finished creating it.
a quick debug showed: 

in root component
- renderer creates element
- renderer adds scope attribute (eg _ngcontent-c1)
- renderer appends elements
- renderer adds class attribute with value `nice-class`

in routed component
- renderer creates element
- renderer adds scope attribute (eg _ngcontent-c1)
- renderer adds class attribute with value `nice-class`
- renderer appends elements

in our app, there is nothing else than `<router-outlet>` in the root component, so that structure prevents this bug... however, every component that we unit-test is basically a root component, so any tests that involve custom elements, that do any action within their `connectedCallback` will fail and break the tests

**Comment by rickhopkins** [comment]
I've got a custom element. In the connectedCallback function I'm using this.querySelector to find child elements and add some functionality to. It's reasonable that they should be there since the element is inserted all together. AngularX breaks this though since it seems to piece meal insert the children after the parent has been inserted. The custom element is working as the custom element should. I can use it in vanilla js, or an angular js app. I can't however use it in angular x because of this limitation in how it builds out the html. That's a bit frustrating, and putting a setTimeout inside it is a hack workaround.

**Comment by robdodson** [comment]
@rickhopkins does your custom element use shadow DOM? If so you'd want to wait till the `slotchange` event fires to look for children. Otherwise I think you'll want to add a MutationObserver and only touch children after that has been triggered.

**Comment by rickhopkins** [comment]
@robdodson No, this particular component is not using the shadow dom. I've been working on a design language system and hoping to use simple web components that basically enforce styles across both our new angular X apps as well as our old angular js apps. I don't always want the shadow dom because of it's restrictiveness...

**Comment by robdodson** [comment]
@rickhopkins that's understandable. I think you'll need to add a MutationObserver then. Otherwise you're relying on the fact that no one will ever dynamically insert a child into one of your custom elements and that's inherently fragile.

**Comment by robdodson** [comment]
I'm going to work on example to show how to do this with a custom element and a mutation observer, which i'll post back to this thread.

**Comment by robdodson** [comment]
I think this is what you would need to do to safely mess with an element's children if you're not using Shadow DOM and the `slotchange` event.

https://stackblitz.com/edit/js-wzb3y1?file=index.html

Depending on the order in which you load your JavaScript definition files, elements may be parsed and in the DOM before they're upgraded. Which means you'll need to process any existing children in your connectedCallback, and from then on you can rely on your MutationObserver to handle any new children. In the above example I check if I have any `x-bar` children, and if so, I change their `textContent`.

**Comment by vishranti5** [comment]
Hi, i am also facing same issue, any updates on same?
I have used angular element to create webcomponent and used this webcomponent in base application. while passing complex object from base application as input property, i get this object on Onchanges in webcomponent but Oninit it is undefined

**Comment by kolkov** [comment]
In my case only `constructor` works. :(

**Comment by pkozlowski-opensource** [comment]
With Angular 9 running ivy one can now read attributes in the `connectedCallback()` as Angular attaches elements to the DOM _after_ setting their attributes: https://ng-run.com/edit/xWl0GUV9XyqRbFINOSTd?open=app%2Fapp.module.ts

**Comment by eafiontzi** [comment]
Hello, thank you very much for all the details @pkozlowski-opensource should both the webcomponent (created with Angular 9) and the base application (in my case created by Angular 7) be updated to Angular 9 running Ivy for connectedCallback() to read attibutes?

**Comment by pkozlowski-opensource** [comment]
@eafiontzi the way I understand this issue is that it relates to the _consuming_ (application using a web component) side of the equation. In other words you need to upgrade an app / library where you use web components in an Angular template.

But hey, upgrading to Angular v9 is a good idea, anyway!
