### ISSUE TITLE
we really need an official native  framework like react native

### ISSUE THREAD

**Issue by guzuomuse** [angular/angular#18918]
angular is so great, i love it!
but i think a very important reason  people chose react because of react native!
i know for now we have choices：cordova ,ionic or nativescript
but if we had an **official native** framework "angular native" that  would be a game changer!
is there any plan on it?

**Comment by marcalj** [comment]
https://www.nativescript.org/ ?

**Comment by IgorMinar** [comment]
nativescript is currently the recommended solution if you want to build a native app with Angular.

**Comment by bryanrideshark** [comment]
@IgorMinar , is there any technical way that the Angular Compiler could target React Native as an output target?

The biggest issue with Nativescript is the lack of a strong community surrounding the project. Right now the only thing propping up the project is Angular. We aren't committed to technology stacks - we're committed to the best experience for the end user.

Right now my entire team is considering leaving Angular entirely, just because React Native provides a better story for mobile. It's something I really don't want to do; but we might be forced to if a higher quality mobile solution doesn't arise from the Angular side of things.

If we could target React Native as an output, or, if Nativescript had 100% parity with React Native, we'd no longer have a reason to consider leaving the Angular ecosystem.

**Comment by anandt2003** [comment]
@IgorMinar  Wish if Google can officially tag NativeScript as the Angular's native mobile app option to boost community interest(or build one for Angular) Hope Angular community is not hurt one day in favor of Google's Flutter(https://flutter.io/) , Google's React Native alternate, which is not using Angular, uses Dart to write app and still in Alpha release  @bryanrideshark @guzuomuse
