### ISSUE TITLE
Using router href directives with ngUpgradeLite 

### ISSUE THREAD

**Issue by rkirov** [angular/angular#18980]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Feature request
[x] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

NgUpgradeLite solves common performance issues with previous NgUpgrade scenarios by not allowing AngularJS directives to be created within the Angular part of the application. If one needs a directive that is in their control, they can migrate it to Angular. In a sense the migration path is bottom-up on the directive dependency tree. 

However, some directives are outside the users control. Commonly, if one still uses an AngularJS router, the ng-href and ui-href directives can be found anywhere in the app. Saying that those cannot be used in the Angular part of the application is overly prohibitive.

What we are left with is:

1) Since AngularJS injectables can still be freely injected in Angular, we can reimplement ng-href and ui-href within Angular. Does this mean then that old router will run in the Angular zone, thus hitting the same performance issues of NgUpgrade?
2) Start with two router solution from the get-go (an AngularJs router and an Angular router). Workout a standard strategy to pass off routes.

@gkalpak, @christopherthielen what are your thoughts on this?

**Comment by rkirov** [comment]
After a brief chat with @gkalpak a third option might be some safer form of UpgradeComponent.

**Comment by christopherthielen** [comment]
UI-Router's `ui-sref` directive does two things:

- renders an href for the linked state
- listens for clicks and calls $state.go(linkedState)

The directive supports _relative links_ meaning from a `foo.bar` state you can relatively link to `.baz` instead of absolutely to `foo.bar.baz`.  Because of this, the directive needs to know the state  context that it was rendered from.

The [UI-Router Angular Hybrid](https://github.com/ui-router/angular-hybrid) project enables UI-Router apps to use Angular `uiSref` directive for Angular code and AngularJS `ui-sref` directive for AngularJS code. It also includes an adapter which provides the state context from AngularJS to Angular.  The hybrid project supports bottom-up hybrid apps only, so it should work fine with `NgUpgradeLite`

**Comment by gkalpak** [comment]
As discussed offline, upgrading non-component directives (such as `ng-href` and `ui-sref`) is not (and never will be) possible. For such cases, one needs to provide an equivalent Angular directive.

For `ng-href`, this is trivial (and not even necessary), since all it does is update the elements `href` attribute.
For `ui-sref`, it might be more complicated (as it does more things under the hood), but as mentioned above `uiSref` (from the [UI-Router Angular Hybrid][1] project might be sufficient (depending on the usecase).

##
Leaving this open to get feedback from @rkirov whether this worked for them or they ran into more issues.

[1]: https://github.com/ui-router/angular-hybrid

**Comment by gkalpak** [comment]
No feedback 😛 Closing...
