### ISSUE TITLE
Structural directives need OnPush

### ISSUE THREAD

**Issue by youdz** [angular/angular#19098]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[x] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior

Currently, directives do not support a `changeDetection` property in their metadata to switch them to an OnPush strategy. I do understand that directives are not the nodes in CD tree, as stated in #14627, so the solution is normally to set the change detection strategy on their host. But for structural directives there can never be a component host, since they are only applied to `<ng-template>` elements. So structural directives currently always use the default change detection strategy, with no workaround.

## Expected behavior

Structural directives should be able to use `ChangeDetectionStrategy.OnPush` one way or another.

## Minimal reproduction of the problem with instructions

Here is a plunker showing how Angular iterates over the entire iterable given as an input, even though we only use the first item: https://plnkr.co/edit/3j9S1Gckw36NTdLlIUjx?p=preview
If you open the console, you will see that the iterable logs entire iterations several times.

## What is the motivation / use case for changing the behavior?

This prevents the possibility of structural directives that receive giant arrays as inputs, and only display parts of them. The constant re-iteration slows down the app to a halt if the array is too large.
Here is the same plunker as above with an array of 100k items, for which we only want to display the first item: https://plnkr.co/edit/Izvl8nK537FU4wgYlXGH?p=preview

## Environment

<pre><code>
Angular version: 4.3.6

Browser:
- All

Others:

</code></pre>

**Comment by Toxicable** [comment]
The reason why Angular is iterating those items in your first example is because we're in dev mode, when in dev mode Angular needs to check through array like structures to make sure they equal to a previous value or in other words: testing for ExpressionHasChangedAfterCheck error.
If you enabled prod mode like this here you'll notice that your `console.log()` is only called once
https://plnkr.co/edit/COAx3w990U6G8l4p8061?p=preview

With that understood now we take a look at what OnPush does.
In my own works what OnPush does is prevents the view of the Component's view from being dirty checked during CD, unless the CD Ref for that component is marked to be checked.
Therefore it would make no sense for a structural/or not directive be OnPush.
If you want the Directive to not be checked them simply make the host component OnPush, therefore CD will not dirty check that view unless it's marked for check

**Comment by youdz** [comment]
I actually found an explanation for what I'm seeing on the plunker here: https://stackoverflow.com/questions/37353790/angular2-detect-changes-using-value-equivalence-or-reference-equality

But it doesn't offer any workaround. In my case, the arrays are so big that I cannot iterate over them even in dev mode.

**Comment by mlc-mlapis** [comment]
@youdz ... so can't pass the whole array as an input to the children component. You have to use another way ... the exact way depends on your app's concept.

**Comment by youdz** [comment]
@mlc-mlapis: I'm not writing an app, I'm writing a library of reusable components. And one of them is a structural directive that works over an array of items, just like `*ngFor`. Passing anything other than an array as an input makes the syntax very weird, which is a huge hinder for a library.

The fact that I can ship with it in prod mode but have no way to run dev mode is a bit absurd. Prod mode checks reference equality, I get that dev mode tries to catch model-view inconsistencies, but is there any way to opt out of it for a specific directive? I can't have the entire library be dev-tested in prod mode just because of one directive.

**Comment by mlc-mlapis** [comment]
@youdz ... OK. As I know there is no way to opt out of it for a specific directive. This functionality is relative deeply hidden in the code. But generally it sounds as a reasonable solution to allow a developer to disable it per a case.
