### ISSUE TITLE
javascript documentation completion

### ISSUE THREAD

**Issue by bannazz** [angular/angular#19126]
Hello everyone,

I've seen a lot of issues that requested Javascript documentation completion; all of which got closed without any resolve of the issue (won't happen / will happen / happening now and will be released in the next version).

Now this is a very important request and I've been referred to MANY issues before that got closed.
So please refer me to the OPEN identical issue where I can monitor what the state of this is or just keep that issue open and update us on what's happening until this is resolved. (not until you reply)

**Comment by bannazz** [comment]
@khuongduybui @tilwinjoy

**Comment by bannazz** [comment]
@Foxandxss This goes specially to you.

Please don't interfere with this issue in anyway as your past comments were very misleading to me and to others in the community who issued the same question. not to mention you actually hiding an already closed thread because you don't want to have your actions seen by the rest of the community.

Now that this is out of the way at the start, we will wait for actual replies (not references to issues closed with no resolve)

**Comment by Foxandxss** [comment]
I am not misleading you, you just were shouting in the wrong place. Here you will have better attention than in the old repo, I just tried to help you.

**Comment by bannazz** [comment]
Your failed try is very much appreciated just....please....not here too.

**Comment by Foxandxss** [comment]
I am part of the docs team my friend, I have to comment.

**Comment by bannazz** [comment]
@Foxandxss Okay, Just let others who actually know how this will resolve comment too. or just don't interfere, its much more helpful not to interfere in case your interference will only be closing this issue before its resolved or having me referred to one of the many closed and unresolved clones of the issue.

This is open
This is not resolved
We need a resolve
Your help?

**Comment by mlc-mlapis** [comment]
@bannazz ... can I ask what type of JavaScript documentation you mean?

**Comment by bannazz** [comment]
The one I should reach when I use this https://v2.angular.io/docs/js/latest/ link.

Also, where can I reach this in angular 4?

I need to use pure javascript which is supported completely but not documented.

Typescript is not javascript. it doesn't run off the browser right away and it has many language differences. saying typescript compiles to javascript so its the same is like saying c compiles to assembly so its the same.

**Comment by Foxandxss** [comment]
In the old site we had TS / Dart / JS, in the new site just typescript.

**Comment by Toxicable** [comment]
@bannazz Please take a minute and read this here https://github.com/angular/code-of-conduct
After you've done that and cleared you head we'll discuss your issue.

The biggest thing here is that Angular needs TS for some of it's best features, for Example AOT which is absolutely essential for an Angular application and there is no reason to not have it.
So going forward I would very much suggest using TS, it dosen' take long to learn and with the CLI you don't even have to worry about compiling it.
Here's a 5 min queickstart on TS: https://www.typescriptlang.org/docs/handbook/typescript-in-5-minutes.html
Here's  the CLI installation https://github.com/angular/angular-cli#installation

**Comment by bannazz** [comment]
@Toxicable 

Sir, thanks for your honest reply.

I do not (and can not) compile a single bit of my code using a microsoft product, for security (and legal) reasons.

Its not always (they hate what they don't know) issue; typescript is simple. it just uncanny for usage in my case so a translator cookbook from ts to js won't make me use ts after a certain level of knowledge and comparison to the javascript language cycle in my mind.

will I be able to use this thing ever? is so, when or how?
That's the question of the issue.

**Comment by mlc-mlapis** [comment]
@bannazz ... I am afraid that the number of people who are coding Angular apps with just JS is very, very limited ...

**Comment by Toxicable** [comment]
@bannazz 
How is it a security and legal issue to use the TypeScript compiler provided by Microsoft?
I understand that there might be some issue with the licence for legal reasons, but security? How is security an issue with a compiler? As you example above it's like saying that `gcc` has security concerns (which it does not).
As I mentioned above, the teams core focus is on improving Angular for TypeScript since that's where all of our biggest features are, therefore that's where the focus of the docs team will be, there are many features in the works and many more to come which all need docs on.

**Comment by tilwinjoy** [comment]
@mlc-mlapis of course, What else do you expect when there is no documentation for JS? The number of people coding in JS for Angular 1 was very, very high you know?

**Comment by bannazz** [comment]
@mlc-mlapis 

Of course it is very limited because its a very hard job to code in a language without having most of its documentation published!

That's why I'm asking....when is this going to be published? is it going to be published at all?
a quick answer to that question will save a lot of people a lot of time they spend waiting for it to happen. Thus, the issue.

**Comment by bannazz** [comment]
@Toxicable 

Sir, again here is the question of the issue:

Will a javascript documentation for angular ever be published? if so when?

**Comment by mlc-mlapis** [comment]
@tilwinjoy ... we used AngularJS for 3 years so I know that there was only JS.

If I can guess then I don't believe that there will be JS docs for Angular in any time in future. Today I can't even imagine to code Angular apps just in JS.

**Comment by bannazz** [comment]
@mlc-mlapis 

Is that an official reply from the docs team? that it will not happen?

**Comment by mlc-mlapis** [comment]
@bannazz ... no, I am not a member of that team so it is just my personal guessing.

**Comment by bannazz** [comment]
@mlc-mlapis 

I think it's everybody's guess not just yours.

But this issue is open because of the need of a definitive answer from the team.

**Comment by khuongduybui** [comment]
No wonder why they dropped js from angularjs.
From what @Toxicable described, they are still catching up on Ts documentation, so they won't ever have time to support Js. Nor do they have any genuine interests.
So at this time, I think the answer is pretty conclusive.

I have moved on but still followed Angular development from time to time hoping js docs will happen. I will stop following now. Wish you all the best.

**Comment by bannazz** [comment]
@Foxandxss @Toxicable 

Is it going to happen or not? because you guys say in the currently published glossary page here:
https://angular.io/guide/glossary

"ECMAScript

The official JavaScript language specification.

The latest approved version of JavaScript is ECMAScript 2017 (also known as "ES2017" or "ES8"). Many Angular developers write their applications in ES8 or a dialect that strives to be compatible with it, such as TypeScript.

Most modern browsers only support the much older "ECMAScript 5" (also known as "ES5") standard. Applications written in ES2017, ES2016, ES2015, or one of their dialects must be transpiled to ES5 JavaScript.

Angular developers can write in ES5 directly."

So just, drop that last line from the glossary or tell us when are those docs going to be published.

Just reply....be plain simple (yes/no).

**Comment by bannazz** [comment]
and close that issue AFTER you resolve it (after you confirm or deny) not before please.

**Comment by Foxandxss** [comment]
There is nothing to confirm nor deny. As mentioned, there is still a lot to document for TS and that is the primary goal right now.

**Comment by bannazz** [comment]
@Foxandxss 

Yes there is!

Do you declare you no longer support a pure version javascript eventhough your website as I quoted up there says we can do everything in ecmascript 6 alone?

**Comment by bannazz** [comment]
@Foxandxss 

I'm not concerned about your focus on TS so please stop saying stuff about TS and not saying a word about JS.

This is big, don't act like it is nothing. the name angular is there because you choose javascript. changing a core language of a framework is a huge step. you need to at least be clear and honest about it. it should be in your FAQ page if you have one.

Just answer my question clear as crystal please so that we can have this issue finally resolved.

**Comment by Foxandxss** [comment]
Let me repeat. The most immediate focus is to write more TS where it is needed. What happens next is not up to me.

**Comment by bannazz** [comment]
@Foxandxss 
Let me repeat, I'm not concerned about what is up to you either. I'm concerned about what happens next if you don't know then don't reply. You will ruin that issue like all the others and nothing more.

Now for those who are on the team and actually knows the answer to that question....read the title.

**Comment by bannazz** [comment]
This issue resolves at a yes or a no.

**Comment by Foxandxss** [comment]
Its saturday and this is not a chat.

**Comment by bannazz** [comment]
@Foxandxss 

I'm sorry? who should say that? what you did basically is say indirect "no" in the middle of irrelevant sandwich of words.

you are absolutely right....this is not a chat, this is an issue request that needs a resolve and I have already asked you not to reply if you don't have enough knowledge to do so or if you are instructed not to say some things like "no we threw js in to the trash can deal with it".

Just abandon the issue, leave it for someone who knows; escalate it to someone who can declare a straight forward answer if you really need to help.

**Comment by tilwinjoy** [comment]
@Foxandxss 

> I am not misleading you, you just were shouting in the wrong place. Here you will have better attention than in the old repo, I just tried to help you.

So, I opened one of the issues mentioned here, someone closes it saying "please open in repo2".
I see already existing issues in closed state without any proper resolution, tries to resurrect them and you reply with a not-so-friendly comment along "We hear you, there is no need to comment on every issue"
which clearly does not resolve the issue. You did not reopen or make a statement in any of the issues.

After a while another discussion arises and you say "This is the wrong place, open in repo1".
I asked to reopen the issue I created in repo1 and nobody did.

You just closes the issues and tries to avoid making a statement by "This is wrong place".
You call this trying to help?

**Comment by Foxandxss** [comment]
I am sorry @tilwinjoy. I don't know which issue you are talking about.

**Comment by fxck** [comment]
How about you actually list and elaborate on those security and legal reasons instead of whining?

**Comment by tilwinjoy** [comment]
@Foxandxss  Here issue in angular repo: https://github.com/angular/angular/issues/13611,
Few of the Issues I tried to resurrect in angular.io after being told to reopen there: 
https://github.com/angular/angular.io/issues/919
https://github.com/angular/angular.io/issues/2989

**Comment by Toxicable** [comment]
@tilwinjoy that first issue is from over 9 months old, how we do docs since then has changed. We did have that other repo angular/angular.io but now docs issues should be in this repo.

**Comment by Foxandxss** [comment]
still, we are going over and over the same topic. Current focus for the next months is to complete the TS docs.

**Comment by tilwinjoy** [comment]
@Foxandxss  Good to hear that, so at the moment we are clear there won't be an JS docs for the "next" months. But still there is no official statement from someone with the say whether there will be JS docs in the coming months after you're done with TS.
I hope this issue will remain open until there is a clear Yes/No official response.

Have a good weekend.

**Comment by robwormald** [comment]
Here's an official statement: we are not planning on creating JS docs at any point in the foreseeable future. I realize this might make some folks angry, but our metrics show that when we had them, less than .1% of pageviews hit the JS documentation. It's an incredible amount of time (and thus money) for us to maintain just the TS docs, and we frankly don't have the capacity to support both JS and TS properly.

Additionally, Angular's entire architecture is really designed around Typescript - perhaps most importantly, the AoT compiler currently *requires* the use of Typescript, as the additional information in types and decorators allow us to do the kind of static analysis necessary. If you don't use AoT, you expose your users to both a poor user experience (because it's slow to boot, due to compiling in the browser) and the potential for security issues (as doing in-browser compilation has a much wider attack surface for exploits). Angular v5 moves towards making AoT the default experience, and our plan is to deprecate the JIT compiler over the longer term.

To be clear: we strongly recommend using Typescript with Angular, and strongly discourage using plain ES5. 

This may mean that certain people might not be able to use Angular - which is unfortunate and always a bummer for us, but we're committed to providing the best experience for Typescript developers. Internal to Google, we have the same policy - using Angular without Typescript is disallowed for the same reasons as above. As such, we don't have support for JS documentation or AoT compilation on our roadmap.

We regularly discuss this on the team, and evaluate where things are at. I'm happy to discuss this further, and I'm sure @DanielRosenwasser would be interested to hear specific objections from your company regarding the use of Microsoft/Typescript tech. We went through a huge amount of security and infrastructure (and legal!) review at Google, and as of today we allow unrestricted usage of Typescript for nearly any project at Google, which should give you confidence on using TS in your own projects.

To *everyone* in this thread, please treat each other with respect per our [Code of Conduct](https://github.com/angular/code-of-conduct/blob/master/CODE_OF_CONDUCT.md)

**Comment by khuongduybui** [comment]
I know the issue is close and the statement was very clear.

However, I would like to offer you a little piece of insights regarding your "metrics":
"when we had them, less than .1% of pageviews hit the JS documentation".

Did anyone ever raise the point that maybe the page views were so low because the pages themselves offer extremely limited information? You guys only offered the most basic getting started without even a guide for routing. The "tutorial" (which touched components, routing, services, and other foundational blocks for a single page application) was Ts only.

I understand and respect your workload. I also understand you are under no obligations to support Javascript. All we ever want is for you to acknowledge the fact that you are not SUPPORTING Javascript and stop claiming so across your website.

Thanks for all the great hard work otherwise :)

**Comment by DanielRosenwasser** [comment]
As Rob said, I would actually be more than happy to hear any and all concerns about using TypeScript. You can do so through MyFirstName.MyLastName@microsoft.com or a DM over Twitter.
