### ISSUE TITLE
(AOT): InjectionToken not work

### ISSUE THREAD

**Issue by reservoir-dogs** [angular/angular#19154]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x ] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior
InjectionToken work very well with JIT compilation. But not with AOT.

## Expected behavior
InjectionToken must work with AOT compilation.

## Minimal reproduction of the problem with instructions
LOCALE_ID use InjectionToken.

Add this in app.module
`{ provide: LOCALE_ID, useValue: window.navigator.language }`

Add this in app.component
`{{today |  | date}}`
today = Date.now()

Actual, i have an exception :
```
TypeError: Cannot convert undefined or null to object
    at new DateTimeFormat (native)
    at intlDateFormat (https://myurl.com/vendor.bundle.js:58132:12)
    at https://myurl.com/vendor.bundle.js:58193:45
    at dateFormatter (https://myurl.com/vendor.bundle.js:58205:16)
    at Function.webpackJsonp.../../../common/@angular/common.es5.js.DateFormatter.format (https://myurl.com/vendor.bundle.js:58248:16)
    at DatePipe.webpackJsonp.../../../common/@angular/common.es5.js.DatePipe.transform (https://myurl.com/vendor.bundle.js:58611:30)
    at checkAndUpdatePureExpressionInline (https://myurl.com/vendor.bundle.js:70968:38)
    at checkAndUpdateNodeInline (https://myurl.com/vendor.bundle.js:71669:17)
    at checkAndUpdateNode (https://myurl.com/vendor.bundle.js:71602:16)
    at debugCheckAndUpdateNode (https://myurl.com/vendor.bundle.js:72463:59)
```
Expected, in culture fr-FR, it displays '12 sept. 2017' and in culture en-US, it displays 'Sep 12, 2017'.

## What is the motivation / use case for changing the behavior?
I want use i8n and have easier configuration for my apps.

## Environment

<pre><code>
Angular version: X.Y.Z

Browser:
- [ ] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: XX  
- Platform:  

Others:

</code></pre>

**Comment by Toxicable** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).

--- 
values in metadata must be statically analyzable for AOT, since your code here is run in a node enviroment (which is where AOT us run), `window.navigator.language` does not exist

use a factory isntead

**Comment by reservoir-dogs** [comment]
Thanks, it's clear.
