### ISSUE TITLE
AOT is using random token when used token is not exported

### ISSUE THREAD

**Issue by Szpadel** [angular/angular#19176]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[X] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior
When do use InjectionToken in file in with there are other objects used as keys in DI (like ngModule) and this InjectionToken isn't exported, AOT compiler will use other token instead without generating any warning or error, that causes very difficult to debug issues.

## Expected behavior
AOT compiler should fail with message that explains that everything used in provide must be exported.

## Minimal reproduction of the problem with instructions
example: https://github.com/Szpadel/angular-aot-di-issue

<pre><code>
Angular version: 4.3.6

Browser:
any
 
For Tooling issues:
- Node version: v8.4.0
- Platform:  Linux
</code></pre>

**Comment by chuckjaz** [comment]
The problem here is that the metadata collector replacing references to `TOKEN` with the initializing expression. It shouldn't do this for expression with a side-effect (such as creating a token).

The work-around (as you discovered but I am repeating for people who find this bug) is to simply export the token.

I believe the fix should be, if a local symbol is initialized with a side-effecting expression (i.e. contains a call or new) the collector should recommend rewriting the expression into a shrouded exported variable and, otherwise, turn all references into an errors.

**Comment by JoostK** [comment]
I've been hit by this issue multiple times and it left me scratching my head for half an hour each time. The good news is that this is no longer an issue in Ivy.
