### ISSUE TITLE
Feature Request: Form Enable Promise

### ISSUE THREAD

**Issue by Neminus** [angular/angular#19193]
## I'm submitting a...
[x] Feature request

## Current behavior
Disabling the FormGroup of a large formular takes too long and produces wrong valid states for the FormGroup.

## Expected behavior
The 'enable' and 'disable' functions of a FormGroup should be returning promises, so you can be sure that the FormGroup is completly disabled/enabled if you want to check for validity.

## Minimal reproduction of the problem with instructions
Create a huge form (about 2.000 controls :-)) that has some invalid controls.

```
this.surveyForm.enable();
// returns true when the form is disabled, should return false after enable
console.log(this.surveyForm.valid);
this.surveyService.disable();
```

## What is the motivation / use case for changing the behavior?
I need a way to be absolutly sure that the enable or disable method has finished.

## Environment

<pre><code>
Angular version: 4.3.6

**Comment by Toxicable** [comment]
Can you please make a **Minimal** reproduction to show your issue?
From memory the `enable` and `disable` methods are run synchronously so there shouldn't be any issues here, that's why we're going to need a reproduction to investigate

**Comment by mbeckenbach** [comment]
Hi @Toxicable, 

i'm working at the same developer team as @Neminus and know his project.

Unfortunately it is not possible to create a **minimal** demo to show this and we may not upload our source code somewhere public. But I can give some more information and if needed we could also setup some kind of google hangout or so.

The problem only exists in a use case where we have a reactive form which has about 1.000 controls and several hundret valueChange subscriptions to enable or disable parts of the form depending on multiple values. Those controls are bound to angular material controls within several angular material tabs.

@Neminus needs to validate the form while it is in a disabled state, which will always result in a valid status. The user may save the (monster)-form in an invalid state. But as soon as it is valid, he may mark it as approved. 

So @Neminus enables the root form group, checks the status and then disables it. When we log out all status changes to the console, we can see, that LOTS of status change events are fired with status disabled before the status reaches the enabled state.
I think this is caused by the hundrets of valueChange subscriptions, which disable or anable some child form groups and add/remove validators at runtime.

Wrapping the valid check after enable() in a setTimeout for 200ms works in chrome. IE takes about 7000ms for all those status changes until the form state becomes stable enough to check the valid state.

@Neminus: A setTimeout cannot be the solution here.  Our customers do not have as fast PCs as you. :-)

For me it looks like the enable() method is running synchronously as it should. But all the valueChange subscriptions take to long to come to a stable form status until we check for a valid state.

What we would need in my opinion is a promise or event, which is getting resolved as soon as the form status changes from DISABLED to VALID **or** INVALID.

Something like
```
this.form.enable().isEnabled.subscribe(() => console.log('we should be stable now'))
```

@Neminus 
Anyway you should check why IE takes 7 seconds to enable your form. Thats way to long. :-)
Until there is a final solution: I think you could setup a subscription to statusChange of this.form with a filter operator to VALID **or** INVALID and a first operator. So you should be able to intercept the moment, when the form has been enabled and do your valid check here.
