### ISSUE TITLE
Introduce public/private element injector (rename Injectables to Injector)

### ISSUE THREAD

**Issue by mhevery** [angular/angular#1925]
# Goal
- Have a way for directives to configure types in the DOM injection hierarchy without needing to create directives for those types.
- Have the types be visible either in private view (encapsulation) or in light dom. i.e. private/public
- Align the naming terminology of the injectors.
- Make injection explicit (from which injector the types are being fetched from, we don't cross between injectors)

# Proposed Syntax
```javascript
@Component({
  appInjector: [
    // rename from injectables:
    // see open issue if we can get rid of this later.
    bind(Greeter).toClass(AlertGreeter)
  ]
  hostInjector: [
    // public to the hostElement
    bind(Greeter).toClass(ModalGreeter)
  ],
})
@View({
  injector: [
  ]
})
class MyComponent {
  constructor(@Self() modalGreeter: Greeter, alertGreeter: Greeter) {
    // Is created using the `hostInjector` so it can inject Greeter
  }
}
```

# Controlling Visibility

- `@Self()` lookup in current host injector
- `@Parent()` look up in parent host injector
- `@Ancestor()` look in any parent injector which does not cross shadow DOM boundaries.
- `@Unbounded()` look in any parent injector which does cross shadow DOM boundaries.
- (none) Use app
- NOTE: We have `@Optional()` which needs to now work on ElementInjector as well.

# PublishAs

-  Remove publishAs.

# Open issues
- Can we get rid of app level injector?

**Comment by matanlurey** [comment]
+1 to approach.

**Comment by naomiblack** [comment]
+1 to this from me too. But please do not land this until https://github.com/angular/angular/pull/1886 is closed, since we can't generate API docs to reflect the rename until it is in.

**Comment by jelbourn** [comment]
What is the use-case is for `@Self`

**Comment by yjbanov** [comment]
"Unbounded" sounds too much like "unbound". A new user might mistake it for "not having a binding". I propose:

s/Ancestor/LocalAncestor/
s/Unbounded/Ancestor/

**Comment by vsavkin** [comment]
Implemented in #1960

**Comment by PascalPrecht** [comment]
Despite the fact that `appInjector` should be removed anyway, could one of you please give a little explanation of what the difference between those are?

So I know that `bootstrap()` creates a root injector **and** an app injector (which is a child injector) for the component that is bootstrapped.

Currently, each sub component can define it's own `appInjector` bindings a la
```
@Component({
  appInjector: []
})
```
This allows us to override existing bindings. From what I understand, this actually creates yet another child injector for that component (and it's child components) right? However, based on the naming, it sounds more like those bindings are also passed to the app injector which is created by bootstrap. But since bindings are flattened, overriding wouldn't work. 

How do `hostInjector` and `viewInjector` relate to that? If `appInjector` creates a child injector anyway, isn't it just a matter of renaming `appInjector` to `hostInjector`?

`viewInjector` is still unclear to me.

**Comment by vicb** [comment]
host & view injectors are `ElementInjector`s (vs `Injector`).

I guess the current state is a little bit confusing for (almost) everybody, we will have to do a better at docs. Meanwhile you can find some info in the inline coments (API doc) and unit tests.

**Comment by PascalPrecht** [comment]
@vicb thanks! And can you confirm that `appInjector` creates a child injector for the component?

**Comment by vicb** [comment]
[if needed](https://github.com/angular/angular/blob/df6acedd25b690930148c7c3bae370f2def2feaa/modules/angular2/src/core/compiler/element_injector.ts#L740), ie when `appInjector` is not empty

**Comment by PascalPrecht** [comment]
Which is always the case when we use it, right? I mean, there's no reason to do:

```
@Component({
  appInjector: [] // without bindings
})
```

But thanks, at least that is clarified :)

**Comment by vicb** [comment]
> there's no reason to do...

If your component is simple, you might not need it. There are probably a few case in the examples.
