### ISSUE TITLE
Please support HttpParams set update instance

### ISSUE THREAD

**Issue by cller** [angular/angular#19285]
## 

<pre><code>
[x] Feature request
// Please support
    const params = new HttpParams();
    params.set('cellphone', cellphone);
    params.set('password', Base64.encode(password));
// But, Now only!  Although missing some code, used to set  return void~
    const params = new HttpParams()
      .set('cellphone', cellphone)
      .set('password', Base64.encode(password));
</code></pre>

**Comment by trotyl** [comment]
https://github.com/angular/angular/pull/18490 You can already pass an object directly.

**Comment by IgorMinar** [comment]
the HttpParams class is immutable by design. This is because the params can be passed through many interceptors which can mutate them. If the class was mutable, the interceptors would very easily get into a bad state.

I think that we should improve the documentation for this class to make this intention clear as it can be missed by some developers.

**Comment by JoostK** [comment]
The API docs were improved in #31613.
