### ISSUE TITLE
Angular Router(4+) loading angularjs(ng1) component

### ISSUE THREAD

**Issue by varmajaisai** [angular/angular#19326]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Feature request
[x] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior

At the moment, we have server based routing loading ng1 app. I'm planning to make it SPA by adding client side routing. We have a plan to migrate ng1 to ng+ soon. As initial step, I'm planning to add angular 4 router and load existing ng1 template. Is it the ideal way to step forward, or add ui-router(ng1) first and then migrate ng1 components to ng+ and at last add angular 4 router.

## Environment

<pre><code>
Angular version: X.Y.Z

Browser:
- [ ] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: XX  
- Platform:  

Others:

</code></pre>

**Comment by gkalpak** [comment]
Both approaches are valid. You should also look into `ngUpgrade` (if you haven' t already), which allows you to run Angular and AngularJS on the same app. You can look at the [dev guide][1] and these blog posts ([one][2], [two][3]) - among others - which highlight different upgrading techniques.

And you can always ask for help on the [general support channels][4] if you get stuck :smiley:

<sub>Closing, since this is not actionable on our part.</sub>

[1]: https://angular.io/guide/upgrade
[2]: https://blog.nrwl.io/two-approaches-to-upgrading-angular-apps-6350b33384e3
[3]: https://blog.nrwl.io/upgrading-angular-applications-upgrade-shell-4d4f4a7e7f7b
[4]: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
