### ISSUE TITLE
Checksum value of a Form input values (Feature request)

### ISSUE THREAD

**Issue by enishyseni** [angular/angular#19481]
I wish Angular(2) had a checksum value/field by default on every form. Basically I've been doing this a lot in Web Applications in general that helped me in CRUD methods.

Like for example:

If Form1 has 5 input fields, the checksum is generated based on value of fields. This is useful more in backends than in frontends.

**Comment by Toxicable** [comment]
What you're wanting is a deep object comparison. I don't think this is something that Angular should provide since it's an expensive operation can be misused causing slowdowns.
If you wish to do something like that then there are many libs that can do this sort of comparison for you, just compare the new values to the old ones to check if it's changed

**Comment by kara** [comment]
@enishyseni I have to agree that this feature seems outside the scope of core forms, but it would be great as a separate library.
