### ISSUE TITLE
INFO: toolbar-background Class name ng-reflect-klass typo confirmation

### ISSUE THREAD

**Issue by mokupindia** [angular/angular#19506]
## I'm submitting a...

<pre><code>

[x] Bug report  

</code></pre>

## Current behavior

Ionic team suggested to check with Angular team :) see below bug comment
https://github.com/ionic-team/ionic/issues/13023

<div class="toolbar-background toolbar-background-md" ng-reflect-**klass**="toolbar-background" ng-reflect-ng-class="toolbar-background-md"></div>

## Expected behavior

Wondering why ng-reflect-klass is spelled as KLASS and not Class?

## Environment

Others:

cli packages: 

    @ionic/cli-utils  : 1.12.0
    ionic (Ionic CLI) : 3.12.0

global packages:

    cordova (Cordova CLI) : 7.0.1 

local packages:

    @ionic/app-scripts : 2.1.4
    Cordova Platforms  : android 6.2.3
    Ionic Framework    : ionic-angular 3.6.1

System:

    Android SDK Tools : 25.2.5
    ios-deploy        : 1.9.1 
    ios-sim           : 5.0.8 
    Node              : v6.11.3
    npm               : 3.10.10 
    OS                : macOS Sierra
    Xcode             : Xcode 8.3.3 Build version 8E3004b 

Misc:

    backend : legacy
</code></pre>

**Comment by gkalpak** [comment]
This is because the `NgClass` directive uses `klass` as the property name of the input bound to the `class` attribute.

https://github.com/angular/angular/blob/0038712474cbc61f36dac10d43c6e7ab48929b4e/packages/common/src/directives/ng_class.ts#L51

Typically, such "misspellings" (e.g. `klass` or `clazz`) are used to overcome the fact that `class` is not a valid identifier name in JavaScript (since it is a keyword). When debug information is attached to an element, property names are prefixed with `ng-reflect-`, hence the `ng-refrect-klass` attribute.

Normally, you can just ignore these properties and they should have no effect on the behavior of components.

**Comment by trotyl** [comment]
> `class` is not a valid **identifier name** in JavaScript

That's not accurate enough, `class` is indeed a valid **identifier name**, but not a valid **identifier**, since:

> A reserved word is an `IdentifierName` that cannot be used as an `Identifier`.

Or:

>`Identifier`:
>   `IdentifierName` but not `ReservedWord`
