### ISSUE TITLE
Router animation not working if animated element are not set to position: fixed or absolute

### ISSUE THREAD

**Issue by rernens** [angular/angular#19501]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[X] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior

When routing animation is used to animate route :enter or leave, animate transition is not run if animated view is not positionned fixed or absolute.

The following animation will not work as expected

```
trigger('routerAnimations', [
 transition( '* <=> *', [
    group([
    query( ':leave', [
      animate('500ms ease-in-out',
        style( {
          opacity: 0,
        })
      )
    ],{ optional: true }),
    query( ':enter', [
        style( {
          opacity: 0,
        }),
        animate('2s 250ms ease-in-out',
          style( {
            opacity: 1
          })
        )
      ],{ optional: true }),
    ])
  ])
])
```

while the following animation works as expected

```
trigger('routerAnimations', [
  transition( '* <=> *', [
    query(':enter,:leave', [
      style({
        position: 'fixed'
      })
    ],{ optional: true }),
    group([
    query( ':leave', [
      animate('500ms ease-in-out',
        style( {
          opacity: 0,
        })
      )
    ],{ optional: true }),
      query( ':enter', [
        style( {
          opacity: 0,
        }),
        animate('2s 250ms ease-in-out',
          style( {
            opacity: 1
          })
        )
      ],{ optional: true }),
    ])
  ])
])
```

## Expected behavior

positionning the element should not be required to trigger animation

## Minimal reproduction of the problem with instructions

http://embed.plnkr.co/xwCLlw6VHGpRW2n1Q7Gj/

## What is the motivation / use case for changing the behavior?

forcing positionning fixed on the animated element might change its appearance during the animation compared to its normal appearance

## Environment

<pre><code>
Angular version: 4.4.4

Browser:
- [x] Chrome (desktop) Version 61.0.3163.100 (Build officiel) (64 bits)
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [x] Safari (desktop) Version 11.0 (12604.1.38.1.7)
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: 8.1 
- Platform:  MacOS Sierra 12.6

Others:

</code></pre>

**Comment by matsko** [comment]
This is unfortunately a shortcoming of the DOM than of the animation language, but there is a way to make this work without using `position: xxxxx`.

Because the views are component DOM nodes that do not exist in HTML, the browser renders them by default as `display:inline`. This means that animating opacity on them might not work as intended (for some bizarre reason). So the solution to make sure each of your views have `display:block` set in a global CSS setting (or using `:host` within your component styles).
https://plnkr.co/edit/tMTXANTnQTlRDXX6uJxf?p=info

Auto-configuring this is out of the reach of Angular unfortunately.

**Comment by rernens** [comment]
@matsko 

First thanks for this reply. 
Than sorry for giving late feedback on the tests I have made based on your recommandations.

using 
:host {
display: block
}

for each of the components does not change anything as you can see in the plunker.

I think though that there is a bug.

**Comment by Kromas** [comment]
This is still not working. Verified that this is a bug on march 2018

**Comment by nhhockeyplayer** [comment]
confirmed have yet to get mine to work either

**Comment by jfcere** [comment]
I would like to avoid using `position` css property because of the side effects that I sometimes bring in animated components. 

I thought that using `query` to apply `display: block` on animated elements would do the trick (see example below) but with no avail...

```js
query(':enter, :leave'), [
  style({ display: block })
]
```

Funny thing is adding `display: block` on the animated component host works!?

```css
:host {
  display: block;
}
```

Am I missing something?
