### ISSUE TITLE
Methods in templates don't understand Infinity value

### ISSUE THREAD

**Issue by tamtakoe** [angular/angular#19512]
## I'm submitting a...
Bug report 

```html
<button (click)="setMax(Infinity)"></button>
```

## Current behavior

`setMax` gets `undefined`

## Expected behavior

`setMax` has to get `Infinity`

## Minimal reproduction of the problem with instructions

http://plnkr.co/edit/GisrghRD3HQkn0wcRdR7?p=preview

## Environment

```
Angular version: 4.4.4

Browser: any
```

**Comment by ericmartinezr** [comment]
Why not simply use Infinity inside the function? I don't see the need to pass it as a parameter. Anyway, since angular is looking for a property named `Infinity` and it doesn't exist it returns undefined. Simply create a property named `Infinity` and assign `Infinity` to it. This is not really a bug..

Example
```
class MyComponent {
   Infinity = Infinity;
}
```

**Comment by mlc-mlapis** [comment]
@Methods ... you can't use a global thing for a direct template binding, only through a class's property.

**Comment by trotyl** [comment]
@mlc-mlapis but `undefined` is allowed in template, although other `[[global]]` properties are not.

**Comment by tytskyi** [comment]
@trotyl Isn't it side effect of how js works (i did not read ng source)?
```
var a = {}
a.undefined === window.undefined
```

**Comment by trotyl** [comment]
@tytskyi In Angular template `undefined` is treated specially like a keyword/literal (by lexer), changing the context value won't affect it. Similar to `context.true = false` won't change the meaning of `true` in template.

**Comment by trotyl** [comment]
Actually I have a PR https://github.com/angular/angular/pull/19356 for letting user know about this problem but I still don't know why Angular is doing so.

**Comment by tamtakoe** [comment]
Ok. I can set `null` and I will get `null` in the method. I don't know what is global thing or what Angular can parse or what not. I'm a stupid user. Just I set function parameter and I expect to see this parameter in arguments because it is common JavaScript (and more others) behavior

**Comment by trotyl** [comment]
@tamtakoe `null` is a keyword in JavaScript while `Infinity` is just a normal variable, it's also common behavior for restricting access to JavaScript variables from template.

**Comment by tamtakoe** [comment]
@trotyl I think, Angular team needs to make an exception for Infinity, because it is popular case for hardcode max or min values in templates (`setMax(Infinity)` == no maximum, `goToPage(Infinity)` == last page, etc.).

Of course you can have case if you have to hardcode e.g. `Math.PI` or `console.log` but they are realy rare

**Comment by lazarljubenovic** [comment]
Isn't it different because `NaN` and `Infinity` are global values defined on `window`? Indeed, `undefined` is also on `window`, but it's probably got special treatment because it _is_ a special case: it's _the_ `undefined`! Super-important concept in JS, irrelevant of existence of `window`.

I think that the confusion is that to us, in everyday speech, `NaN` and `Infinity` seem closer to values like `0`, `1`, or `-0` than to `null`, well in fact, to JS, `NaN`, `null` and `Infinity` are all properties found on `window`. 

That aside, I agree that Angular templates should have a whitelist of things we can access from `window`. Templates at the moment kinda lacking behind ES6 in general, looks like it's simply not a priority at the moment.

**Comment by trotyl** [comment]
`null` is a keyword, nothing related to `[[global]]`; `1`, `-1` are literal, same to `true`, `false`; `undefined`, `NaN` are identifiers. These are all different concepts.

`Window` is an HTML-defined interface acts as extension of `[[global]]`, which defines something like `setTimeout `, and that's not JavaScript. Angular is a platform-independent framework, so `Window` is not something needed to care about.

**Comment by lazarljubenovic** [comment]
I was trying to explain that the pattern I see in Angular templates is that things which live on `window` are not available in templates, except for `undefined`.

![image](https://user-images.githubusercontent.com/7661457/31089279-c6688ac6-a7a3-11e7-801a-3882fbf78bae.png)

**Comment by trotyl** [comment]
Template "variable"s are properties of context object, it's the nature of semantic for not having access to JavaScript `[[global]]` properties. Instead, properties on `__proto__` are always accessible, so it's a common case for using `constructor` template "variable" to access static properties like `constructor.name`.

I'm opposing to semantic-level exception in the template language just because something is a bit more common. [Adding support for `undefined`](https://github.com/angular/angular/commit/c85ab3a5a44c1596f7934cccab1a82e7fcf0c7ad) could just be a design mistake in early versions.

**Comment by trotyl** [comment]
A better way to go could be allow providing custom "global" variables like [$parseProvider#addLiteral](https://docs.angularjs.org/api/ng/provider/$parseProvider#addLiteral) in AngularJS.

**Comment by robwormald** [comment]
This is not something we're going to support, sorry. You may explicitly expose such variables via `this.Infinity = Infinity`, or better, do something like `doStuff('infinity')` and map it in the controller. Allowing access to arbitrary globals opens up a wide attack surface for all sorts of security issues.

**Comment by tamtakoe** [comment]
Node.js has no window but `Infinity`, `NaN`, `Math` etc. are available in the common scope
