### ISSUE TITLE
Downgrading Angular directive not working.

### ISSUE THREAD

**Issue by rajvirtual** [angular/angular#19609]
I am trying to downgrade an Angular element directive, to use with Angular 1.6, but it doesn't seem to do anything.
This is the Plunker i forked from a downgrade example.
http://plnkr.co/edit/d91NTCkvfF1glhiJpGhd?p=preview
You can see,the directive constructor is not firing.

**Comment by gkalpak** [comment]
I order to be able to downgrade a component, you need to add it to the `entryComponents` array of your `NgModule` (because it will be created by `ngUpgrade`, not as part of another Angular component's template).

But you can use directives as entry components. (Not sure why, but that is a different issue (not related to `ngUpgrade`).)

So, it seems you need to use a component (possibly with an empty template).
