### ISSUE TITLE
Strange word in documentation of structural directives

### ISSUE THREAD

**Issue by ha0x7c7** [angular/angular#19613]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Feature request
[ x] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior
I just don't know what the world is

![image](https://user-images.githubusercontent.com/10879511/31320387-9b799d78-ac80-11e7-86f4-8ef8bc117bed.png)

## Environment

<pre><code>
Angular version: X.Y.Z

Browser:
- [ ] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: XX  
- Platform:  

Others:

</code></pre>

**Comment by mlc-mlapis** [comment]
@ha0x7c7 ... `desugar` means `transalate`, `transform` or `interpret` ...

**Comment by lazarljubenovic** [comment]
There's a term "syntax sugar" that we often use in describing a certain structure of language to say "writing something in a prettier way so it is easier to read". Angular here offers a "syntax sugar": you do not have to write

```
<ng-template [ngIf]="condition">
  <span>foo</span>
</ng-template>
```

but instead just this is enough:

```
<span *ngIf="condition">foo</span>
```

So we say that `*` is a "sugared" syntax for `<ng-template [ngIf]>`.

When compiler goes through Angular code, it has to de-sugar it first in order to understand it. "De-sugaring" is an inverse process from "sugaring" code: it means to revert a pretty syntax to back to a more verbose one -- this is because, although for a human it's easier to read sugared code, machines prefer desugared one in order to understand it easier.

---

That said, you've come to a wrong place to ask such a question. Issues are for reporting bugs and requesting features in Angular and its documentation. _However_, this might mean that the docs team should include a link from the word "desugars" to a Wiki article or write a short explanation about the term. I agree that it can be confusion if you're not familiar with the term "syntax sugar" from before.

**Comment by robwormald** [comment]
thanks @lazarljubenovic - assigning this to the docs team to see if we can clarify it a bit.

**Comment by mlc-mlapis** [comment]
@lazarljubenovic ... `desugar` has also real meaning / understanding from the chemical world ... decompose a complex substance to simpler substances.
