### ISSUE TITLE
Routing doesn't trigger native hashchange event on the window when using hashstrategy

### ISSUE THREAD

**Issue by envyN** [angular/angular#19619]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior

Angular routing using the hash strategy doesnt trigger the native hashchange event which makes it difficult to detect when the hash changes. This is needed when the app is rendered in an iframe and the containing app needs to determine when the angular app changed its location.

## Expected behavior

Currently, it does not fire the hashchange event when using either [router-link] or through javascript using the Router service

## Minimal reproduction of the problem with instructions

http://plnkr.co/8Oo3qc?p=info
[embed version] http://embed.plnkr.co/8Oo3qc/

## What is the motivation / use case for changing the behavior?

A containing application which uses iframes to render sub-apps built with angular needs to subscribe to the location changes in the sub-applications.
Using <a href="#/first"></a> works for the use case but [router-link]="['/first]" or router navigations from Javascript do not trigger hashchange events on the window.
The embedded view of plnkr is a concrete example (not sure if its because of same). We dont see the location getting changed in the UI

## Environment

<pre><code>
Angular version: v4.4.4

Browser:
- [ ] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: XX  
- Platform:  

Others:

</code></pre>

**Comment by dloukadakis** [comment]
The only reason it works with href is because its supported by the browser to do so and angular only changes the router state because it listens for hashchange events in case user types the hash manually. Now on the other hand when routerLink is used then angular will directly modify the router state and use History.pushState() to modify the browser URL which does not fire hashchange event.

This is also documented behavior on:
- [W3 HTML5 Specification](https://www.w3.org/TR/html5/browsers.html#dom-history-pushstate)
`Since this is neither a navigation of the browsing context nor a history traversal, it does not cause a hashchange event to be fired.`
- [MDN web docs](https://developer.mozilla.org/en-US/docs/Web/API/History_API#The_pushState()_method).
`Note that pushState() never causes a hashchange event to be fired, even if the new URL differs from the old URL only in its hash.`

So i don't think this is an angular issue as its expected behavior of History.pushState() function. 

A possible workaround for your use case is setting Location.hash instead of using routerLink, that will trigger hashchange event properly.

**Comment by jasonaden** [comment]
It appears this behaves as expected. If you still feel there is an issue, please provide further details in a new issue.
