### ISSUE TITLE
Single bind to multiple events in template

### ISSUE THREAD

**Issue by tcober** [angular/angular#19675]
<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[X ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior
<code><div (mouseenter)="fooFighter()" (mouseleave)="fooFighter()"></code>

## Expected behavior
<code><div (mouseenter, mouseleave)="fooFighters()"></code>

## What is the motivation / use case for changing the behavior?
I think this has been requested before and shot down here: https://github.com/angular/angular/issues/6675
Sure I could make a directive, but why even have native event binding in the template if you can't natively bind to multiple events cleanly? Seems silly, but maybe there is something I am missing? Maybe it would be deceptively hard to implement? I don't know. Sorry if this is a waste of your time, but it seems like a lot of people would be happy if this was implemented.

**Comment by lifenstein** [comment]
I have a toggle icon which needs to be accessible via mouse and keyboard:
`<span (click)="buttonPressed()" (keyup.enter)="buttonPressed()" tabindex="0">Click</span>`

Would be nicer to be able to write `<span (click, keyup.enter)="buttonPressed()" tabindex="0">Click</span>` instead.

**Comment by Vikasg7** [comment]
This is the third time, I am coming to [#6675](https://github.com/angular/angular/issues/6675), hoping that Devs have had implemented this feature but despaired to see that no one from Angular team has even bothered to deny or accept this feature request.
This feature of binding the same handler to multiple events is more obvious thing that comes to my mind when writing code but unfortunately this feature isn't a reality yet.  :(
I hope to see this feature in the next builds.

**Comment by trotyl** [comment]
```html
<div (mouseenter, mouseleave)="fooFighters()">
```

This is not valid html (to what your need), it's equal to:

```html
<div (mouseenter,=""  mouseleave)="fooFighters()">
```

Where the attributes are: 

```json
{
  "(mouseenter,": "",
  "mouseleave)": "fooFighters()"
}
```

So you cannot write any space in between.

**Comment by stamminator** [comment]
Any updates on this in 2018?

**Comment by binDongKim** [comment]
This feature should be on the way!

**Comment by lifenstein** [comment]
@binDongKim Are you saying they *are* working on it, or that they *ought to be* working on it?

**Comment by kylekatarnls** [comment]
@trotyl Indeed, this limitation seems not breakable. I guess it could acceptable to get it without space:

```html
<div (mouseenter,mouseleave)="fooFighters()">
or
<div (mouseenter|mouseleave)="fooFighters()">
```

**Comment by aserraric** [comment]
+1

**Comment by ArneMisbaer** [comment]
+1

**Comment by mhevery** [comment]
Sorry, but I don't think we will be implementing this. The issue is well described [here](https://github.com/angular/angular/issues/19675#issuecomment-366281413). `(foo,bar)` it is very tempting to write `(foo, bar)` which completely changes the meaning as it breaks it up into two attributes. Given that there is a simple work around, I don't think this is complexity which Angular team is willing to take on.

**Comment by stamminator** [comment]
@mhevery It seems to me like there's too much flexibility given to what an attribute can be named. If a developer intentionally names an attribute `(mouseenter,` like in [trotyl's](https://github.com/angular/angular/issues/19675#issuecomment-366281413) example, they should be flogged and fined for crimes against humanity.

I know the point is moot because further limiting the characters allowed in an attribute name would be a major breaking change, but I think most developers would agree that applying some limitations to attribute names in order to allow nice syntax like `(foo, bar)` would be a net positive for Angular.

**Comment by mhevery** [comment]
@stamminator The issue is that `(foo, bar)` contains empty space `" "` which in the rules of HTML means that those are two separate attributes. For this reason the left hand side of the attribute should be a single word. Hence `(foo, bar)` is unlikely direction.

**Comment by digeomel** [comment]
@mhevery you keep mentioning a "simple workaround", but I couldn't find it in the comments, what did I miss? What's the workaround?

**Comment by mhevery** [comment]
Just bind to the events separately. `<div (foo)="work()" (bar)="work()">`

**Comment by digeomel** [comment]
@mhevery I wouldn't call this a workaround, that's the default way of doing things in Angular, but maybe that's just me 😄 
And I can't recall now the particular code that brought me here in the first place, but I suspect it had to do with DRY when you have a more complex call with lots of parameters, such as:

`<div (mouseenter)="longFunctionName(withParameterA, withParameterB, withParameterC)" (mouseleave)="longFunctionName(withParameterA, withParameterB, withParameterC)"></div>`

**Comment by kylekatarnls** [comment]
Completely agreewith @digeomel, obviously @mhevery we know we use N attribute for each events, but clearly, the aim of the proposal is to have clean code avoiding duplicate the attribute value expression many times.

**Comment by petebacondarwin** [comment]
Taking the example from the original issue, the suggested workaround to keep things DRY is to create a directive to keep all the events in one place: https://stackblitz.com/edit/angular-ivy-zsja4p?file=src/app/app.component.html

While there will definitely be some who can find fault with it (e.g. having to create a directive), it is definitely a solution that keeps things DRY and has the additional benefit of removing complexity from the template; and the directive is very small. 

Further you could even make the directive configurable if you wanted like: https://stackblitz.com/edit/angular-ivy-rbpbre?file=src%2Fapp%2Fapp.component.html

Since there are a number of workarounds, and that adding such support would add complexity to the compiler for limited benefit, and moreover add potential confusion since it is very likely that people would try to add whitespace between the event names, I am confident that this is not something that Angular should support in core.
