### ISSUE TITLE
Form validation of dynamically created input elements does not work

### ISSUE THREAD

**Issue by dedeibel** [angular/angular#19724]
## I'm submitting a...
<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request
</code></pre>

## Current behavior

When you create a simple form with two text input elements being "required" and the second input is created by a dynamic sub component, the validation check fails.

The following ``form.valid`` statement returns true even if both inputs are empty.

```
<button type="button"
          [disabled]="!edit.form.valid"
```

HTML Output of the app:

```
<app-root _nghost-c0="" ng-version="4.4.5"><h1 _ngcontent-c0="">Sub Form example with valid</h1>
<form _ngcontent-c0="" novalidate="" class="ng-dirty ng-invalid ng-touched">
  <div _ngcontent-c0="" class="form-group">
    <label _ngcontent-c0="" for="firstinput">First input</label>
    <input _ngcontent-c0="" class="form-control ng-dirty ng-invalid ng-touched" id="firstinput" name="firstinput" placeholder="First Input" required="" ng-reflect-required="" ng-reflect-name="firstinput" ng-reflect-model="">
  </div>

  <!----><app-sub _nghost-c1=""><div _ngcontent-c1="" class="form-group">
  <label _ngcontent-c1="" for="secondinput">Second input</label>
  <input _ngcontent-c1="" class="form-control ng-dirty ng-touched ng-invalid" id="secondinput" name="secondinput" placeholder="Second Input" required="" ng-reflect-required="" ng-reflect-name="secondinput" ng-reflect-model="">
</div>
</app-sub>

  <button _ngcontent-c0="" class="btn btn-primary" id="submit" type="button" disabled="">Commit
  </button>
</form>
</app-root>
```

## Expected behavior

Since both input elements are part of the referenced form, the value of ``form.valid`` should not be truthy if any of the elements are invalid.

## Minimal reproduction of the problem with instructions

1. Observe that the commit button is initially disabled
1. Enter something into the first input element
1. You will see that the commit button is now enabled although the second input is not filled. UNEXPECTED

http://plnkr.co/edit/A0GZ1Ri4mFvd3PF6wfFc?p=preview

## What is the motivation / use case for changing the behavior?

Having a simple way to prevent submitting invalid forms. The sub component is used to divide the form into manageable chunks based on choices inside of the form.

## Environment

<pre><code>
Angular version: 4.2.4

Browser:
- [x] Chrome (desktop) version 61.0.3163.100
- [ ] Chrome (Android) version XX _untested_
- [ ] Chrome (iOS) version XX _untested_
- [x] Firefox version 56
- [ ] Safari (desktop) version XX _untested_
- [ ] Safari (iOS) version XX _untested_
- [ ] IE version XX _untested_
- [ ] Edge version XX _untested_
 
For Tooling issues:
- Node version: v6.11.3
- Platform: Linux

Others:
Verified on coworkers computer.
</code></pre>

**Comment by alexzuza** [comment]
> Since both input elements are part of the referenced form

Indeed it's not true. Just add

`<pre>{{ edit.value | json }}</pre>`

to template to debug it.

http://plnkr.co/edit/4z26GHLfuQ4KaG8wPYIM?p=preview

As you can see `[ngModel][secondinput]` control is not added to `edit` form because ngModel directive is looking for adorned by Host provider

`@Optional() @Host() parent: ControlContainer,`

`NgForm` directive provides `ControlContainer` provider

I know two options to solve it:

1) Manually add ngModel to parent NgForm

**sub.component.ts**

`ViewChild(NgModel) ngModel: NgModel;`

**parent.component.ts**

```
@ViewChild('edit') ngForm: NgForm;
..
this.subFormComponent = this.subForm.createComponent(
      this.componentFactoryResolver.resolveComponentFactory(
        SubComponent));
this.ngForm.formDirective.addControl(this.subFormComponent.instance.ngModel);
```
http://plnkr.co/edit/i57JfRdx0I2JxdUDClDq?p=preview

2) Read this SO `[answer](https://stackoverflow.com/questions/39242219/angular2-nested-template-driven-form/46748943#46748943)` and add viewProviders to your child component:

`viewProviders: [ { provide: ControlContainer, useExisting: NgForm } ]`

http://plnkr.co/edit/ADAxPUqJI7lUgWvqCP3n?p=preview

**Comment by dedeibel** [comment]
wow, thanks. Guess I was assuming too much that it would use the html representation of the form as basis since all my statements are defined in the template.

Sorry for the noise.
