### ISSUE TITLE
CI uses unpinned version of local Chrome 

### ISSUE THREAD

**Issue by IgorMinar** [angular/angular#19793]
In #18307 @filipesilva removed all of our chrome installation scripts and replaced them Travis Chrome addon that installs the latest stable chrome when the VM boots up.

This is problematic because when Chrome version changes uncontrollably we can face tests failing or timing out unexpectedly as happened today.

The chrome version change #18307 has no reasoning or documentation so it's hard to tell why we did it this way. @mhevery doesn't know. @filipesilva do you know?

I checked the docs and the addon doesn't allow us to specify a concrete version, so I suggest we go back to the original way of installing local chrome via the script and pin it down to the most recent stable chrome.

**Comment by filipesilva** [comment]
@IgorMinar at the time the Angular CI was failing because of an old chrome version not being supported by Protractor's chrome driver. Removing the download script also seemed like it would help with CI startup times, so I changed it to use latest stable from Travis. I did not remember to check for version pinning at the time.

I don't foresee any problem with going back to the previous script. 

Another option is to use https://github.com/GoogleChrome/puppeteer instead. It would also permit pinning chrome by pinning to a version of Puppeteer, and would be carried over in the node_modules cache. The installed chrome can be accessed via `require('puppeteer').executablePath()`.

**Comment by IgorMinar** [comment]
There are several downsides for using puppeteer:
- the chrome version info is buried deep in logs (or package.json of that package)
- we'll be installing chrome locally on dev machines
- updating node dependencies without too much care can rev puppeteer, which could bring in different version of chrome, resulting in unexplainable errors.

Installing the browser on travis takes just a few seconds because it's essentially just download+unzip. If the time is significant, we can use travis/circleci cache.

Because of these reasons I'm leaning towards using the old set of scripts.

**Comment by gkalpak** [comment]
(The installation directory is also cached on Travis, so we don't even have to download :smiley:)
