### ISSUE TITLE
Error in @angular/router 4.1.2 

### ISSUE THREAD

**Issue by roshan3133** [angular/angular#19895]
I am using Angular 4.1.2 in @angular/router i am getting below error.

```
[at-loader] Checking finished with 1 errors
[at-loader] ./src/app/services/a.service.ts:10:30
    TS2339: Property '_routeConfig' does not exist on type 'ActivatedRouteSnapshot'.
```
my code is as below

```
import { Router, CanActivate, CanActivateChild, ActivatedRouteSnapshot, RouterStateSnapshot } from '@angular/router';
canActivate(route: ActivatedRouteSnapshot, state: RouterStateSnapshot):boolean {
    console.log(route._routeConfig.path); 
}
```
![capture](https://user-images.githubusercontent.com/7414497/31937130-2e32d4d4-b8d1-11e7-818a-1ae0747058e4.PNG)

The value "provisioning" getting correctly, but why I am getting error, it should not be.

**Comment by MartinJK** [comment]
Instead of accessing the _routeConfig member (which is a private member), you should only read properties / members that defined for the ActivatedRouteSnapshot class on the docs (https://angular.io/api/router/ActivatedRouteSnapshot) or in the source (https://github.com/angular/angular/blob/b14c2d1568f9cc634c18fe1ee77a647aa57a012a/packages/router/src/router_state.ts#L235)

Solution would be to use `console.log(route.routeConfig.path);`

**Comment by roshan3133** [comment]
Hi @MartinJK your iven solution is working, Thanks
