### ISSUE TITLE
Null pointer exception in template parser

### ISSUE THREAD

**Issue by crisbeto** [angular/angular#19906]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior
The compiler throws a null pointer [error that points to this line.](https://github.com/angular/angular/blob/b6431c60e66d0b4cdce17dff64872ddf86e70139/packages/compiler/src/template_parser/template_parser.ts#L894)

Full stack trace:
```
Error: TypeError: Cannot read property 'type' of null
    at C:\projects\material2\node_modules\@angular\compiler\bundles\compiler.umd.js:25385:26
    at Array.forEach (native)
    at removeSummaryDuplicates (C:\projects\material2\node_modules\@angular\compiler\bundles\compiler.umd.js:25384:11)
    at TemplateParser.tryParseHtml (C:\projects\material2\node_modules\@angular\compiler\bundles\compiler.umd.js:24393:51)
    at TemplateParser.tryParse (C:\projects\material2\node_modules\@angular\compiler\bundles\compiler.umd.js:24370:21)
    at TemplateParser.parse (C:\projects\material2\node_modules\@angular\compiler\bundles\compiler.umd.js:24332:44)
    at AotCompiler._parseTemplate (C:\projects\material2\node_modules\@angular\compiler\bundles\compiler.umd.js:29710:60)
    at AotCompiler._compileComponent (C:\projects\material2\node_modules\@angular\compiler\bundles\compiler.umd.js:29682:23)
    at C:\projects\material2\node_modules\@angular\compiler\bundles\compiler.umd.js:29528:55
    at Array.forEach (native)
```

## Minimal reproduction of the problem with instructions
1. Check out https://github.com/crisbeto/material2/tree/ng-5
2. `npm install`
3. `npm run demo-app`.

## Environment

<pre><code>
Angular version: 5.0.0-rc.4

For Tooling issues:
- Node version: 8.2.1
- Platform:  Windows
</code></pre>

cc @chuckjaz

**Comment by chuckjaz** [comment]
This is two problems that we are approaching independently.

1) There is an error during template validation that is being reported because the the configuration of the the project is unexpected. We are now validating templates and the we are not able to find some of the metadata during emit.

2) The error reporting is getting lost and resulting in the violation of an internal constraint (that is, the decorator array should never contain a `null`).

We are addressing (1) by tying template validation to `fullTemplateTypeCheck` which is `false` by default. Invoking `ngc` for libraries will revert to the `4.0.0` behavior (just generating metadata instead of trying to validate it). The templates will now only be validated when `fullTemplateTypeCheck` is enabled. @tbosch is working on this.

(2) is being addressed by reverting part of the change made to fix `getLazyRoutes` for JIT programs. We switched to an error collection model (used by the language service) instead of an exception reporting model. We are switching back to exceptions for `ngc` but will continue to use error collection for `getLazyRoutes` and the language service. @chuckj is working on this.

We should support the configuration of projects that material is using and will address that post `5.0.0`.

**Comment by tbosch** [comment]
Regarding (1): See https://github.com/angular/angular/pull/19909

**Comment by tbosch** [comment]
Closing as the corresponding PRs have landed on master.

**Comment by cormacrelf** [comment]
This is happening again with Ng-packagr v4, which has mysteriously enabled both skipTemplateCodegen and fullTemplateTypeCheck. Is that an inherently bad combination or a bug?

Reopen or new issue? @chuckjaz 

Tsconfig:
https://github.com/dherges/ng-packagr/blob/master/src/lib/ts/conf/tsconfig.ngc.json

Repro:

- check out the above PR (`dependabot/npm_and_yarn/ng-packagr-4.0.0` branch)
- `yarn` (v1.7.0)
- `yarn lerna run prepare`, which just cleans and runs ng-packagr on each
- fails only on the card-list package There’s only one component template and I don’t think it has any type errors.

**Comment by cormacrelf** [comment]
Also I didn’t mean to unassign @chuckjaz, maybe that’s a GitHub syntax thing.

**Comment by dherges** [comment]
In `TemplateParser#tryParseHtml` the values of `htmlAstWithErrors.errors` contain null values. That's all I found out so far.

```
Angular CLI: 6.2.2
Node: 10.10.0
OS: linux x64
Angular: 6.1.7
... animations, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.6.8
@angular-devkit/build-angular     0.6.8
@angular-devkit/build-optimizer   0.6.8
@angular-devkit/core              0.8.2
@angular-devkit/schematics        0.8.2
@angular/cdk                      6.4.7
@angular/cli                      6.2.2
@ngtools/json-schema              1.1.0
@ngtools/webpack                  6.0.8
@schematics/angular               0.6.1
@schematics/update                0.8.2
ng-packagr                        4.1.1
rxjs                              6.3.2
typescript                        2.9.2
webpack                           4.8.3
```

**Comment by dherges** [comment]
After trying and trying, my workaround is to set `fullTemplateTypeCheck: false` ... i opened an issue on ng-packagr ng-packagr/ng-packagr#1087
