### ISSUE TITLE
run BLACK_LISTED_EVENTS outside of ngZone Documentation missing

### ISSUE THREAD

**Issue by Zizzamia** [angular/angular#19989]
Ciao,

I'm trying to use `BLACK_LISTED_EVENTS` with `5.0.3`, but I feel it's missing the documentation to plug this feature in my production app.

## I'm submitting a...
<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Feature request
[x] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question

## Environment
Angular version: 5.0.3

**Comment by Zizzamia** [comment]
Ciao @JiaLiPassion, I'm trying to use `BLACK_LISTED_EVENTS` by following your example https://gist.github.com/JiaLiPassion/45664f6a28c8b522fca30c841610c6b4 with any success.

Can you please help us with more documentation about it.
Thank you

**Comment by alexzuza** [comment]
Seems it should look like

1. Before zone.js script
```
// black list scroll event handler for onProp
const targets = [window, Document.prototype, HTMLBodyElement.prototype, HTMLElement.prototype];
 __Zone_ignore_on_properties = [];
targets.forEach(function(target) {
  __Zone_ignore_on_properties.push({
    target: target,
    ignoreProperties: ['scroll', 'mouseenter', 'mouseleave', 'mousemove', 'mouseover', 'mouseout', 'mousewheel']
  });
});

// disable requestAnimationFrame
__Zone_disable_requestAnimationFrame = true;
```

After that all event that you declare like `document.onmousemove = ...` won't be patched by zonejs since they will be filtered by zone.js internally https://github.com/angular/zone.js/blob/326a07fb9095e4a87ff7561cb45fe1d4917c2174/lib/browser/property-descriptor.ts#L242-L293

2. Then import zonejs

3. Instantly after zone.js 

```
// black list scroll event handler for addEventListener
Zone[Zone.__symbol__('BLACK_LISTED_EVENTS')] = ['scroll', 'mouseenter', 'mouseleave', 'mousemove', 'mouseover', 'mouseout', 'mousewheel'];
```
This way all events for which **angular schedules** execution will be executed in root zone. https://github.com/angular/angular/blob/330bb2a360397e37cb8bf287fca0d8fec71bc4d5/packages/platform-browser/src/dom/events/dom_events.ts#L168

They are events like

```
@HostListener('document:scroll')

<div (mousemove)=""

renderer.listen(el, 'event')

host: {'(scroll)': 'onScroll($event)'},
```

If you add event through `document.addEventListener` or some of your library does it internally(`$(document.on('scroll')`) then this event can be executed inside angular zone (depends on in which zone event is added)

If you want all events will be executed outside angular zone you can take a look at this SO question https://stackoverflow.com/questions/43108155/angular-2-how-to-keep-event-from-triggering-digest-loop

@JiaLiPassion Please correct me if i'm wrong here

**Comment by JiaLiPassion** [comment]
@Zizzamia , @alexzuza , I will post a sample in github. thank you for do the research.

**Comment by JiaLiPassion** [comment]
I have made a sample, and `addEventListener` still run in `ngZone`, I have made a PR in `zone.js` to fix this one.

https://github.com/JiaLiPassion/blacklist

**Comment by Zizzamia** [comment]
Nice, I followed your repo and did this
```html
<script>
    var t = [window, Document, HTMLBodyElement, HTMLElement];
    var b = ['scroll', 'mousemove'];
    __Zone_ignore_on_properties = [];
    t.forEach(function (tar) { __Zone_ignore_on_properties.push({ target: tar, ignoreProperties: b }); });
    __zone_symbol__BLACK_LISTED_EVENTS = b;
    __Zone_disable_requestAnimationFrame = true;
  </script>
  <script src="<%= assets('vendor.js') %>"></script>
```

```js
  click1() {
    document.onmousemove = function() {
      console.log('on property in Zone', Zone.current.name);
    };
  }

  click2() {
    document.addEventListener('mousemove', function() {
      console.log('addEventListener in Zone', Zone.current.name);
    });
  }
```
After clicking on both and move my mouse around I got this
```
on property in Zone angular
addEventListener in Zone angular
```
Is it what I should aspect?

**Comment by JiaLiPassion** [comment]
@Zizzamia , did you use the latest version of `angular` and `zone.js`, now only `addEventListener` still in `angular` zone in my test repository.

**Comment by Zizzamia** [comment]
zone.js "0.8.18" and angular "5.0.3", I also don't use **angular cli**, I bundle everything with **webpack** and I code in **ES6**.
What `Zone.current.name` should look like?

**Comment by JiaLiPassion** [comment]
@Zizzamia , sorry, I forget I used a internal version of `zone.js`. please wait for the next version of `zone.js`.

**Comment by Zizzamia** [comment]
@JiaLiPassion when should be available the new version of `zone.js`?

**Comment by JiaLiPassion** [comment]
@Zizzamia, yes, it will be available when the next version of `zone.js`.
