### ISSUE TITLE
Compiler.compileModuleAsync related Issue - Memory Leak?

### ISSUE THREAD

**Issue by RajkumarSiva** [angular/angular#19997]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ x] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior

A Component is not getting destroyed completely (ngOnDestroy is getting called & it is also getting removed from DOM but it stays in memory) after invoking compileModuleAsync method.
Dynamically created components are getting destroyed completely, but **the one which created the dynamic component is not getting destroyed**. 

## Expected behavior

Component supposed to be destroyed from router outlet after navigating to another component.

## Minimal reproduction of the problem with instructions

I have clearly written the issue in stackoverflow [question](https://stackoverflow.com/questions/46984089/angular-dynamic-component-compiler-issue-memory-leak). I used chrome's developer tool to take snapshot of the memory to analyze memory.

http://embed.plnkr.co/EVFglgkp24hkRkpxrEGe/
https://stackoverflow.com/questions/46984089/angular-dynamic-component-compiler-issue-memory-leak

## What is the motivation / use case for changing the behavior?

creating components dynamically

## Environment

<pre><code>
Angular version: Latest

Browser:
- [x ] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: XX  
- Platform:  

Others:

</code></pre>

**Comment by alexzuza** [comment]
Hello! I think the main problem here is using `compiler.compileModuleAsync`

According to the [docs](https://github.com/angular/angular/blob/master/docs/PUBLIC_API.md#supported-public-api-surface-of-angular)

> One intentional omission from this list is @angular/compiler, which is currently considered a low level api and is subject to internal changes. 

So don't use it. 

To test memory leak i would advice you enable prod mode. 

Each time you call `compiler.compileModuleAsync` you add new key to `_tokenKeyCache` Map that is used internally.

**Comment by trotyl** [comment]
@alexzuza [Compiler](https://angular.io/api/core/Compiler) lies in `@angular/core`, not `@angular/compiler`.

**Comment by alexzuza** [comment]
@trotyl Yeah, you're right. And it throws error `Runtime compiler is not loaded` if we don't provide `JitCompiler` from `@angular/compiler`

**Comment by trotyl** [comment]
@alexzuza `JitCompiler` is provided from `@angular/platform-browser-dynamic`, user won't touch any symbol defined in `@angular/compiler`, everything is still under public API.

**Comment by alexzuza** [comment]
Thanks for pointing this out. It lies in `@angular/platform-browser-dynamic` only starting from 5.x.x

**Comment by trotyl** [comment]
`JitCompiler` provided by `@angular/platform-browser-dynamic` since the [very first version](https://github.com/angular/angular/blob/0cc77b4a6954e563b6eb7999c9d3f08e2ba7dfeb/packages/platform-browser-dynamic/src/compiler_factory.ts#L40-L44) of `@angular/compiler` & `@angular/platform-browser-dynamic` after the [splitting](https://github.com/angular/angular/commit/0cc77b4a6954e563b6eb7999c9d3f08e2ba7dfeb) from `@angular/core`.

**Comment by maximusk** [comment]
I've shown [here](https://stackoverflow.com/a/46992682/2545680) where the leaks come from. Basically these are:

```
export class JitCompiler {
  private _compiledHostTemplateCache = new Map<Type, CompiledTemplate>();
```
and 

```
const _tokenKeyCache = new Map<any, string>();
```
The `DynamicHtmlComponent` and `DynamicHtmlComponentFactory` are used as keys in those maps.

**Comment by zippos** [comment]
Any idea when will this be fixed? I'm stuck releasing due to this nasty bug.

**Comment by eric-simonton-sama** [comment]
My team was just bitten by this bug (or a similar one) in a new context: our Jasmine test suite. We are on Angular 1 and 5 in a hybrid app, and are still using `UpgradeAdapter`. Something during the bootstrapping process calls `PlatformRef.bootstrapModule`, which 16 calls up the stack gets to `tokenKey()` passing it e.g. an array of `ComponentFactory`s. This happens at the start of every test, so all those old `ComponentFactories` and many other things are kept in memory for the duration of the test suite.

Our suite no longer works because it runs the browser out of memory. We will work around it by splitting our suite into multiple smaller suites to run separately for now.

Please let me know if this belongs in a separate ticket, or if more specifics would be helpful. Thanks!

**Comment by getusroidoug** [comment]
@RajkumarSiva , has there been any progress on this issue? My team is now facing a similar problem.

In our particular case, we are dynamically rendering components like this:

`
const factory = resolver.resolveComponentFactory(component);
compRef = viewContainer.createComponent(factory);
`

**Comment by patcheng** [comment]
I noticed that `TestBed.configureTestModule` created a `DynamicTestModule` under the cover. And each instance of DynamicTestModule will be reference by the `_tokenKeyCache`.

And from https://angular.io/guide/testing#component-test-basics, each test case will call `TestBed.configureTestModule`. So each test case will be leaking an instance of `DynamicTestModule`.

Internally each `DynamicTestModule` instances a compiled list of providers. And if you use `ExistingProvider`, it will have a reference to an objects instead of a class.

So for a sizable test suites, this could add up.

**Comment by JoostK** [comment]
Still an issue in Ivy in Angular 9.0, although the source of the memory leak has changed.
