### ISSUE TITLE
Unable to resolve a Service provided by an NgModule

### ISSUE THREAD

**Issue by mockuniverse** [angular/angular#20043]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Feature request
[x] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior

I have an NgModule and it exposes a Service in its "providers" array.  Alternatively this could be a service returned in the "providers" array from forRoot() (returning ModuleWithProviders instance).

We can import the module and include it in an application NgModule imports.  This supposedly makes all of the imported module's exports (declarative stuff) available and makes the providers available for DI.  However, we cannot do the following, meaning we cannot use those assets:

import { MyService } from 'MyModule'

How is this supposed to work? How do we get components, filters, but most importantly services out of the module? Do we have to path to the node_modules folder and ferret around for the file? Hopefully that's not the case. 
 
## Expected behavior

Should be able to import services provided by a module. 

## Minimal reproduction of the problem with instructions

Publish a module that exposes services via its providers property, then try to use those services inside an application module that includes the service providing module. 

## What is the motivation / use case for changing the behavior?

Rational, simple, intuitive use of module assets. 

## Environment

<pre><code>
Angular version: 4.4

Browser:
- [ ] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: XX  
- Platform:  

Others:

</code></pre>

**Comment by Swellenator** [comment]
If you have a service in the providers section of an NgModule it will be available to all components within that module. You then need to add it as a parameter to a component so that it will be injected. You need to get the type to do that, so yes you need to import it, but this is just importing the type (class) not the injected instance from the module. So

import { MyService } from 'MyModule'

Should be 

import { MyService } from 'file path to exported class MyService'

If it is not a class you wrote your self and is coming from NPM then you would need to check their documentation about how to import the class.

**Comment by jasonaden** [comment]
The above seems to explain the issue. Sounds like you are using the imported service directly, rather than passing into the constructor of a Component. If that doesn't solve your issue, please create a reproduction. We suggest using [StackBlitz](https://stackblitz.com/fork/angular-gitter), [Plunker](http://plnkr.co/edit/tpl:AvJOMERrnz94ekVua0u5?p=catalogue) or [Github](https://github.com/new).
