### ISSUE TITLE
@HostListener('change') not fired at several latest browsers

### ISSUE THREAD

**Issue by everedifice** [angular/angular#20087]
## I'm submitting a...
<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior

If an component has input tag and implement `ControlValueAccessor`. 

Doing write value to input by using `ElementRef` or `FormControl` API in valueChanges handler.

then `@HostListener('change')` on other directive handler are not fired.

## Expected behavior

`@HostListener('change')` fired if component doing anything.

## Minimal reproduction of the problem with instructions

https://plnkr.co/edit/kYw0sV6Pmk72QJ1qha1m

I describe detail instructions to source code.

`src/changeDetection.ts` directive has `@HostListener('change')` handler that not fired on several latest browsers.

Chrome: No problem
Safari, Firefox, IE11, Edge: Has Problem

## What is the motivation / use case for changing the behavior?

When customer type some number for money data. I want to adding some ',' (comma) character for easy to read.

## Environment

<pre><code>
Angular version: 5.0.0

Browser:
- [x] Chrome (desktop) version Latest
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [x] Firefox version Latest
- [x] Safari (desktop) version Latest
- [ ] Safari (iOS) version XX
- [x] IE version 11
- [x] Edge version Latest
 
For Tooling issues:
- Node version: v6.11.2
- Platform:  Mac

Others:
</code></pre>

**Comment by gkalpak** [comment]
`@HostListener('change')` fires when the `change` event is fired by the browser. I.e. this is browser-dependent and not Angular-related. You can test it yourself with:

```js
var input = document.createElement('input');
document.body.appendChild(input);
input.addEventListener('change', function() { console.log('change'); });
```

All browsers I tested this on, the `change` event is fired when the element loses focus (older versions of Chrome might have different behavior). The spec is a little vague on when it should be fired, so browsers had deviated in their behavior in the past.

I am going to close the issue, since the different behavior is not affected by Angular afaict.

(BTW, you might want to look into the `input` event which fires any time the input values changes.)

**Comment by everedifice** [comment]
@gkalpak I've checked this issue one more time at my home. and It is works exactly same with your reply. I'll double check my implementation on tomorrow. thank you.

**Comment by michahell** [comment]
Currently experiencing a bug where we're running into this.
I can mention our Angular version (`6.1.7`) but since this is not Angular related it won't matter.
Nevertheless, this is still an ongoing issue that needs a fix or workaround. I'll post back if I find one.

**Comment by michahell** [comment]
We finally solved this by instead of listening the the Angular `(change)` listener on a custom `MatFormField` component implementing `ControlValueAccessor`, by listening in the **parent** component to the custom component `.statusChanges()` observable and emitting an update manually whenever the custom component validation status changed to `'VALID'`...

`omg` @ Angular custom components (underdocumented) and dealing with IE11 crap (omg)
