### ISSUE TITLE
Clarify `<template>` elements will be removed in v6

### ISSUE THREAD

**Issue by hotforfeature** [angular/angular#20151]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Feature request
[x] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior

From the CHANGELOG for v5:

**compiler:** the compiler option `enableLegacyTemplate` is now disabled by default as the <template> element was deprecated since v4. Use `<ng-template>` instead. The option `enableLegacyTemplate` and the `<template>` element will both be removed in Angular v6.

## Expected behavior

Documentation should explain what is happening by "template element will be removed". The `<template>` is a native HTML element, what will happen when it is encountered in an Angular component? 

Does this statement mean Angular will ignore `<template>` elements and create a native template element if it encounters one, or does it mean that it will become impossible to use native `<template>` elements in Angular v6?

## What is the motivation / use case for changing the behavior?

`<template>` elements are a key part of web components, and heavily used in [Origami](https://github.com/hotforfeature/origami), an Angular/Polymer compatibility library.

## Environment

<pre><code>
Angular version: 5.0.0

</code></pre>

**Comment by trotyl** [comment]
Sorry about the unclear words, this means that Angular will drop support for "`<template>` tag being recognized  as Angular template", so that it will become normal DOM element, then has whatever meaning offered by browser.

You can have a look of the original issue: https://github.com/angular/angular/issues/7974, "allowing `<template>` tag usage for web components" is the main reason for Angular drop `<template>` and introduce `<ng-template>` instead.

So no need to worry about that. (Could be a valid documentation request)

**Comment by hotforfeature** [comment]
Thanks for the clarification @trotyl! This was my assumption, but I wanted to make sure 👍

**Comment by vicb** [comment]
Thanks for the clear explanation @trotyl
