### ISSUE TITLE
[i18n] Current state & pain points

### ISSUE THREAD

**Issue by ocombe** [angular/angular#20193]
Hello everyone, I'd like to start a discussion on the current state of i18n in Angular.
Our goal is to make it as easy to use as possible, but we are aware that we still have some work to do on that.
I think that the main two issues right now are:
- having one bundle for all locales instead of one bundle/locale
- being able to use translations in your code (not just templates)

The first point is being addressed right now with what we call "runtime translations". And it's actually the first step for the second point which will be our main focus once runtime translations are done.

What we'd like to know if what else we can do to make it easier to use? Any feedback is appreciated.

You can find the list of things that we're working on or that we have planed here: https://github.com/angular/angular/issues/16477

**Comment by edmundo096** [comment]
Straightforward documentation would help, in my opinion.

Haven't checked the i18n docs since 2.0 RC times, but a complete coverage section or tutorial on the docs would be pretty much well appreciated to push more projects to begin using it.

I have seen the *ng2-translate* library being used much more than the official translation module, either because ionic or many web posts/tutorials use them instead of the official module. Maybe because (again) it's easier to start having simple translations on that library.

Anyways, glad to see you in the core team now :)

**Comment by ocombe** [comment]
@edmundo096 thanks for the feedback.
Check out the new i18n guide that we wrote for v5: https://angular.io/guide/i18n

**Comment by smoke** [comment]
I would love to have these also considered:
 - sort the messages not by the order of appearance in the code, but to an order that does not change when same message is used in new place or moved. For instance now if a message is used in some nested component, and then the same message is later added to an upper code - the file will have the message moved in upper lines - thus making it difficult to keep track of. For example if the messages are sorted by the ID this won't be an issue.
 - ability to disable writing the `<context-group purpose="location">` and other unrelated to source and target tags when extracting, so less noise is generated with new usages of same message.
 - ability to translate 3-th party provided components. Namely let's say a component is included from a package - it can ship translations, that can be overridden or complimented with new languages

**Comment by wartab** [comment]
One use case I have encountered is i18n in Angular's route names. Currently, my build phase needs to take care of this statically. It would be nice if it was somehow possible to have translated URLs.

**Comment by Maistho** [comment]
In general I would also like better tools for managing large translation files, and a way to easily view diffs. Finding unused translations in existing `xlf` files would also be useful.

Is it possible to improve working with ICU selects and booleans?

```html
<!-- This doesn't work -->
<p i18n>I {candy, select, true {want} false {don't want}} candy.</p>

<!-- This works, but feels very hacky -->
<p i18n>I {'' + candy, select, true {want} false {don't want}} candy.</p>
```

**Comment by ocombe** [comment]
@smoke:
- shouldn't be difficult to do
- we probably won't spend time on this sorry, too many cli options is not ideal, this would also requires an update to the cli
- this is coming with runtime translations

@wartab: a lot of people have requested this, I'll make sure that it's possible once we have code translations

@Maistho:
- there are tools that do that already, see https://www.oneskyapp.com/ https://crowdin.com/ https://www.textunited.com/ for example
- the select ICU has an official specification that says that it works with strings, not booleans, sorry...

**Comment by Maistho** [comment]
@ocombe:
Since numbers are allowed, perhaps converting booleans to numbers? So that it would be possible to do:
```html
<!-- This doesn't work -->
<p i18n>I {candy, select, =0 {don't want} =1 {want}} candy.</p>
```

I guess it might be a little bit too much "magic" though, probably better to just convert my boolean to a number manually, e.g.
```html
<p i18n>I {+candy, select, =0 {don't want} =1 {want}} candy.</p>

```

**Comment by abos** [comment]
One of my most important requirements is that I must be able to change the translated strings in the back-end and I am able to support new languages without being required to rebuild/redeploy the app. This is solved by ngx-translate by means of the TranslateLoader and works good for me. I would love to see that supported in angular.

**Comment by matthewharwood** [comment]
Request 1:
Having some kind of official workflow for updates to translations:

1. Extracting Translations
2. Sending and Receiving translations with vendor
3. Updating Code with new copy blocks.
_Updating will require_
4. Extracting again // point of failure
5. Sending and Receiving translations back
6. Repeat.


There are tools like https://github.com/martinroob/ngx-i18nsupport
But it would be great to have some kind of official support in ng-xi18n for this common workflow.
More context: https://stackoverflow.com/questions/45773699/angular-i18n-extract-clobbers-previous-changes

Request 2:
I like the flexibility of many bundles per locale as for generating static content this is somewhat needed for SEO purposes.  "Runtime translations" shouldn't be a dependency of being able to use translations in your code.  Maybe I'm not understanding but I often need access to a list of locales so that I can whitelist and blacklist content in my applications.

For example:
**Application level:** Your app only bundles into `['en_US', 'fr_fr', 'es_es']`
**Route level:** For app `es_es` do not render `/coupons` route.
**Component level:** For app `es_es` on `/homepage` do not render the 'coupons' component.
**Element level:** For `es_es` on `/homepage` switch affilates logo wall to `es_es` affilates logo wall.

I'm prob just a noob and this is all possible but I haven't found any docs on how to get these behaviors.

**Comment by zoonman** [comment]
Hi guys, I think Angular should have support of the following:

- [ ] bundling of a number of locales
- [ ] autodetection of browser's locale with fallback to default locale and ability to dynamically switch language within the app (e.g.: pick a language from the dropdown list or load language based on profile settings)
- [ ] autoupdate of messages.xlf and tracking of translation completeness (using `ng serve`)
- [ ] locales path, list and default locale options for `.angular-cli.json`
- [ ] store localizations in JSON file(s). It is much easier to work with JSON files and build tools to with that format. 

As developers we look how to build the app but our app's users don't want to know this. They want to open the app and see the application in the language they know. All of that leads to bundling the app with multitude of languages and locales. Don't forget, that Arabic languages have a different text direction and app has to switch graphics too.
The most painful stuff comes into play when Googlebot appears on the site. App has to understand route params to be able to show the app in many locales/languages to get itself indexed otherwise there will be no organic traffic. Also backend should be smart enough to understand `Accept-Language` header normally sent by browser or react on [geoip](http://nginx.org/en/docs/http/ngx_http_geoip_module.html) data. So in this case we need to find way to let Angular work in conjunction with backend services and the best we can do - to make sure that Angular Universal will be able to serve the correct localized version of the app. Also it has to be done in a way where Googlebot will be able to understand that this page are getting served based on the browser's locale and don't think that there is a cloaking technique was used.
I think, you have to take a look at [angular-translate](https://angular-translate.github.io/). It has a very practical approach and I used it earlier in one of my projects.

**Comment by jasedwards** [comment]
The big issue I have with v5 locale strategy is that my company supports 350 different cultures.  so it is not realistic to import each locale as docs suggest and it is also not realistic to do a separate build for each.  What would be nice is if we could somehow 'provide' the locale data for the pipes.  For example in AngularJs apps we would get the users culture and then download the correct $locale provider.  I see above you are working on one bundle for all locales which would also work but am also concerned about bundle size.

**Comment by ocombe** [comment]
Locale data can be lazy loaded at the bootstrap of your application (when you know which locale your app will use). I should add an example to the docs for that.

**Comment by jasedwards** [comment]
@ocombe  That would be perfect

**Comment by philjones88** [comment]
@ocombe that would be great. I could probably hack around it but our "user" object with the user's locale comes from a HTTP request, guessing that's too late for bootstrapping process. I guess a hack I could do would be to read the locale from a cookie perhaps our API sets....

**Comment by ocombe** [comment]
you can register the locale at any time, as long as it is before you use one of the i18n pipes, you can do it in a route resolver for example: https://angular.io/api/router/Resolve

**Comment by philjones88** [comment]
@ocombe an example combined with the `Date` pipe would be great. Reading the documentation it only talks about being able to set it in the app module ? https://angular.io/guide/i18n#setting-up-the-locale-of-your-app

**Comment by ocombe** [comment]
It can be used anywhere, as long as it's before you use one of the pipes.
Could you open an issue for that so that I don't forget to update the guide? And also so that we don't diverge too much from the original topic.

**Comment by philjones88** [comment]
@ocombe created https://github.com/angular/angular/issues/20500 hopefully describing what we discussed.

**Comment by intellix** [comment]
One thing that's driving me nuts is that when `<target/>` is missing, it's considered a compile error and you can't build:
```html
<trans-unit id="aeaddbca2acfb0f1e42e54d4d49d966d3f68e1d0" datatype="html">
  <source>Hello</source>
</trans-unit>
```

Couldn't that just be treated the same way as a missing translation? There aren't really any tools around and when you find out they've got their own quirk. SmartCat seems to be the best we've found for continuous project development as you can update strings with new ones..... but if you don't translate something, it's there in the XLF file and you get the compile error. Gotta fail the build until I can find the ones with missing `<target>` to manually remove them as they're not easy to search for

**Comment by vicb** [comment]
Closing as action items are tracked internally

/cc @ocombe

**Comment by cedvdb** [comment]
@ocombe any estimation for when runtime traduction will be released ?

**Comment by srikanthps** [comment]
Is there a way for angular LOCALE_ID to be set based on browser's locale?

**Comment by shobhit12345** [comment]
how we can switch between two language using Angular i18n feature , i am with refresh of URL, But how to store selected locale

**Comment by matthewharwood** [comment]
@shobhit12345 may try localstorage api?

**Comment by ahsinsiddique** [comment]
https://medium.com/frontend-fun/angular-introduction-to-internationalization-i18n-28226a85e04e 
this link will help you using i18n features. and how to set local_id, how to start app using local id.

**Comment by zoonman** [comment]
@ahsinsiddique  your article is a manual copycat. The current state of internationalization support is bad and not well-thought.
By default Angular app must be built with all defined languages and must be able to switch language on the fly using browsers locale or database settings or even server response.

**Comment by trotyl** [comment]
@zoonman It's fully possible in current Angular even with the view engine.

In current code-generation there're `ComponentFactory`s which reference to the `Component` types, but not the opposite way, means that a `Component` doesn't bound to any `ComponentFactory` at runtime, but can be shared between different `ComponentFactory`s, just not in the same time. (Same for `NgModule`s)

So that you can build all languages (actually one-by-one) and bundle them together with proper renaming process. (So sadly build time won't be saved)

Then at runtime just teardown current `ApplicationRef` and re-bootstrap the app like StackBlitz, but with a different `NgModuleFactory`.

Clearly this approach requires custom build steps (a custom builder in Angular CLI) and takes time (writing is always harder than speaking), but to find out what's the capability of Angular is you do need to go beyond the restriction of Angular CLI.

<sub>PS: I don't actually suggest doing it now (if you haven't) since ivy already makes good progress.</sub>

**Comment by actra-gschuster** [comment]
For runtime-i18n in AOT there's https://www.npmjs.com/package/@actra-development-oss/ng-i18n-aot-loader in combination with https://www.npmjs.com/package/@actra-development-oss/ng-i18n-aot-module

**Comment by digismack** [comment]
I've used the @actra-development-oss packages (with Angular 5.x), and they certainly do work as advertised, but I've since switched to @ngx-translate (with Angular 6.x) and haven't looked back.

Not having to tinker with webpack config files or ejected builds is much easier to work with.

**Comment by tpatterson34** [comment]
Hi, my team has successfully internationalized using i18n and ngx-translate.  This has handled the basics for us.  However, we produce system software that is delivered and ran by our customers, and we have an additional requirement that any text on our SPA can be customized by the customer but without any source code delivery.  Are there any plans to externalize the translation files (or any recommended best practice for doing so) such that the translations could be modified and built (if necessary) without requiring any of the original source code?

**Comment by ocombe** [comment]
it should be solved by the runtime service, probably by using multiple translation files (yours + the one the client provides)

**Comment by matthewharwood** [comment]
@ocombe with the new release of ivy and i18n will my 2 requests be considered/available? https://github.com/angular/angular/issues/20193#issuecomment-343671033

**Comment by tpatterson34** [comment]
Hi @ocombe, is that something on the Angular roadmap or are you suggesting a home-grown runtime service?  (I have considered a patch script that runs inside a docker container with our webserver and the input would be a customer-provided file in a mapped directory)

**Comment by ocombe** [comment]
@matthewharwood request 1 is not on the roadmap but it's also something that I'd like to solve at some point. Don't expect anything soon though.
For request 2: runtime i18n will be compatible with pre-rendering using platform-server (universal). That being said nothing will stop you from generating one bundle / language like you're doing right now.

@tpatterson34 I'm talking about the official angular service that we'll release to use runtime i18n

**Comment by tpatterson34** [comment]
@ocombe could you point me to any story/defect/document that describes that service?

**Comment by tpatterson34** [comment]
thanks @ocombe.  Any guess on timeframe for that?  Perhaps another way to ask -- if I have a delivery to make next August, should I bite the bullet now and do a homegrown tool, or would it be reasonable to wait a few months and expect something official might be released in time to use it for such a delivery?

**Comment by ocombe** [comment]
I'm pretty bad at time frames, last year I was sure that we would have something before v6, and look where we are now :D
Also i18n is probably something that you should integrate from the start, otherwise it becomes a real burden to integrate it.
Maybe you could try to create something that you could easily replace?
