### ISSUE TITLE
Router - redirectTo with query param can't pass route params (such as /:id)

### ISSUE THREAD

**Issue by Mysame** [angular/angular#20297]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report 
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior
Thanks to #9921 , it is now possible to pass queryParams on redirectTo.
However, on routes that match "/redirect/:id", redirecting to "/route?param=:id" creates "/route?param=undefined";

## Expected behavior
Route "/redirect/:id" with redirectTo "/route?param=:id" should properly fill in ":id"

## Minimal reproduction of the problem with instructions
http://plnkr.co/edit/D3IspqOdQTOwtxGEOxKS?p=preview

## What is the motivation / use case for changing the behavior?
It seems contradictory that one approach would work, whereas the other does not.

## Environment

<pre><code>
Angular version: 4.4.3 / latest (plunkr)

Browser:
- [x] All
</code></pre>

**Comment by matt-senseye** [comment]
Just come across this problem too - does anybody know a workaround?

**Comment by atscott** [comment]
The route parameters and query parameters occupy separate spaces of the URL conceptually and don't cross. You can copy query parameters to other query parameters in a redirect and route parameters to other route parameters but you can't copy between the two because names may not be unique.

If you want to copy between the two in a redirect, you can write a guard which returns a `UrlTree`: https://stackblitz.com/edit/angular-ivy-9sdrsq?file=src%2Fapp%2Fapp.component.html
