### ISSUE TITLE
Angular 5.0.x - commonly used locales with regions e.g. `es-ES`, `fr-FR`, etc are now not accepted and switched to language only e.g. `es`, `fr`

### ISSUE THREAD

**Issue by smoke** [angular/angular#20340]
## I'm submitting a...

<pre><code>
[x] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior

Prior Angular 5.0.0 using `ng build --locale es-ES` correctly keeps  and works with `es-ES` for `LOCALE_ID` however this is no longer the case since 5.0.0. A lot of locales e.g. `es-ES`, `fr-FR` are missing in https://github.com/angular/angular/tree/master/packages/common/locales where this code checks https://github.com/angular/angular-cli/blob/master/packages/%40ngtools/webpack/src/angular_compiler_plugin.ts#L227 and fullbacks to using just the language e.g. `es-ES` -> `es`, `fr-FR` -> `fr`, etc.

Note, that I am filling this in the @angular project, not in @angular/cli as this change was initiated by the @angular project.

## Expected behavior

I might be wrong as I can't fully grasp through http://www.rfc-editor.org/rfc/bcp/bcp47.txt, but to me and many others locales like `es-ES`, `fr-FR` should be valid values for `LOCALE_ID` and angular should be able to work flawlessly with them.

## Minimal reproduction of the problem with instructions

1. Have an @angular/cli >= 1.5.0 created project with angular >= 5.0.0
1. Have a component that requires @Inject(LOCALE_ID)
1. Do a build or serve `ng serve --locale 'es-ES'`
1. Notice the LOCALE_ID is set to `es` not as expected `es-ES`

## What is the motivation / use case for changing the behavior?

I might be wrong as I can't fully grasp through http://www.rfc-editor.org/rfc/bcp/bcp47.txt, but to me and many others locales like `es-ES`, `fr-FR` should be valid values for `LOCALE_ID` and angular should be able to work flawlessly with them.
At least this was the case prior 5.0.0, so this issue is worth being well discussed and documented.

## Others

Possible good fix could be having symlinks in @angular/common/locales for `fr-FR` -> `fr`, `es-ES` -> `es`, so that this is well resolved and utilized by current tooling.

**Comment by ocombe** [comment]
The CLDR data that we use now works like this:
- if a locale is the most used for a language, it becomes the default parent locale, for example "en" is equivalent to "en-US".
- if a regional locale is equivalent to the parent locale, then this regional locale is no longer listed (as it would be a duplicate), that's why you only have "en" and not "en-US", the same for french where you have "fr" but not "fr-FR"
- the default parent locale is not always equivalent to the country of origin of a language, for example "pt" for Portuguese is actually Brazilian Portuguese and not Portuguese as spoken in Portugal because there are more people speaking Brazilian Portuguese. That's why you don't have a "pt-BR" locale, but you have a "pt-PT" locale (since pt-PT !== pt).

Because this behavior might seem weird, we decided that by default if you ask for a regional locale that doesn't exists but you have provided the parent locale then it will be used instead. People will often use the complete locale id (parent + region) and not just the parent locale name because that's how it is detected. A browser will give you "fr-FR", which you will set as the app `LOCALE_ID`, and Angular will automatically use "fr" since "fr-FR" doesn't exist.
This can be a problem when people actually use the parent locale name assuming that it is equivalent (as it is in the case of "pt" and "pt-PT"), but 99% of the time it will be a correct assumption.
That's why the cli fallbacks to the parent locale when it inject the locale, and that's why we apply the same behavior in Angular itself: https://github.com/angular/angular/blob/master/packages/common/src/i18n/locale_data_api.ts#L513

That being said when you manually import the locale, you might be wondering why "fr-FR" is missing. We could duplicate those files (not use symlinks because this doesn't work well on Windows), but I'm not sure if it is really necessary ?

**Comment by trotyl** [comment]
I think it's more intuitive for using `en-US` as the single source of truth and then re-export in `en`, this enables:

+ Making no breaking change;
+ Gaining consistency for always using `en-US` everywhere;
+ Allowing searching file name for all locales;
+ Directly knowing what's the default for a language (by checking the `en` file);
+ Easing the debug circle (knowing that's being used without tracing the logic code, same of above?)

<sub>Since there's no re-export for default export yet, maybe just import & export manually?</sub>

**Comment by ocombe** [comment]
@vicb what do you think? Should we create files for "missing locales" (eg: creating a file for "en-US" that would just export the content of "en")

**Comment by josephliccini** [comment]
@ocombe that would work well for my situation, where we get locale ID at runtime, and we currently get ones like: `fr-FR`, and _not_ just `fr`.  I suppose we could do some custom logic to work as what you have described above, but I would prefer locale files for both `fr` and `fr-FR` to cover both situations, even if 1 is just a re-export

**Comment by ocombe** [comment]
Hello, we've reviewed the issue and we will do the following change in Angular: the `registerLocaleData` function will let you register locale data along with the locale id of your choice
We are also fixing the cli bug where it changes your `LOCALE_ID` : https://github.com/angular/angular-cli/pull/8604 it should be available in the next release

**Comment by jasedwards** [comment]
@ocombe Will this fix the issue where I get a culture from a user table such as de-DE, attempt to lazy load it and get an error because there is no de-DE file?  I had thought to just look if the language was same as culture and then use just the 'de' part but the comment above about there not being a pt-BR means that would not work either

**Comment by ocombe** [comment]
It will not fix your code, if you try to lazy load a file that doesn't exist then it will fail.

**Comment by jasedwards** [comment]
My hope was it would exist at some point.  Since I am doing this automatically I am not sure how I am supposed to account for every 'default' culture and then change what file I am trying to lazy load.  so if a user sets their culture to pt-BR I would expect that locale file to be available.  If not then I have to keep an array somewhere of the 200 something default cultures and change my value accordingly.

**Comment by ocombe** [comment]
we have a meeting about these issues (it's not the only one) tomorrow, I'll know more by then

**Comment by robinComa** [comment]
Hello @ocombe ! Have you got some news about this issue? For my project we have to use a lot of langage (14), this issue is currently fixed by importing dynamically `@angular/common/locales/${lang}.js` but "pt-br", "no", "zh-cn" and "zh-hk" are not supported so we need to add aliases and affect custom IDs.
Could you give to me a status of this issue? did you have your meeting?
