### ISSUE TITLE
docs(aio): Clearing array with new array instead of setting it's length to 0 

### ISSUE THREAD

**Issue by shavipathania** [angular/angular#20369]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Feature request
[x] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior

In following tutorial pages
- /toh-pt4/src/app/message.service.ts
- /toh-pt5/src/app/message.service.ts
- /toh-pt6/src/app/message.service.ts

For clearing arrays we are setting it's property to 0.
```
clear() {
    this.messages.length = 0;
}
```
Which is inefficent as per discussion with [Benedikt Meurer](https://twitter.com/bmeurer/status/929420630323290112)

## Expected behavior

```
clear() {
    this.messages = [];
}
```

## Minimal reproduction of the problem with instructions

It's hard to visualise the actual performance difference because of GC overhead. But anyhow here is the minimum reproduction
[Plunker](https://embed.plnkr.co/CedEygme2FoAc0hWLQJZ/)

## What is the motivation / use case for changing the behavior?

As lots developers learn to code well by seeing the code over websites likes angular.io. So, we should document the code which is faster and more efficient. It may be marginally well but writing
```
clear() {
    this.messages = [];
}
```
is short plus efficient.

> For reference: [] is turned into a sequence of around 15 machine instructions on x64 (if bump pointer allocation succeeds), whereas a.length=0 is a C++ runtime function call, which requires 10-100x as many instructions.
>      [Benedikt Meurer](https://twitter.com/bmeurer/status/929420630323290112)

## Environment

<pre><code>
Angular version: 5.0.1

Browser:
- [ ] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: XX  
- Platform:  

Others:

</code></pre>

**Comment by gkalpak** [comment]
Saying that it is more performant is an overexaggeration imo. The difference will be neither noticeable nor meassurable (since the non-predictable GC time will dominate the total time in both cases afaict).

I am fine with either way, but note that (even if both will work in this case) there is a fundamental difference in terms of semantics that makes them non-interchangeable (in general):

- `arr.length = 0` will keep the same array object, while `arr = []` will create a new one. This means that if a reference to the original array was held elsewhere in the app, this change would break that part of the code. (I am not implying that holding references to service properties is a good idea, just pointing out the fact that things might break.)

##
So, while I don't feel too compelled to make the change, if someone wants to submit a PR, I'd be happy to review :smiley:

**Comment by shavipathania** [comment]
@gkalpak you are right.. but i did't mean to over-exaggerate... clearing array with [] is just marginally efficient...
I just wanted angular developers should use what's best... 
I was just exploring which method is more efficient and i always think setting array length to 0 is more efficient but to my surprise, setting with new array was more efficient.

And for your concern that things might break... that wouldn't be good choice as suggested by you... so it seems setting it with [] is a better option.

As per your suggestion I have submitted a pull request too... :-)

**Comment by shavipathania** [comment]
@gkalpak thanks for your truly valuable assistance. And I will be coming up with new issue soon... :stuck_out_tongue_closed_eyes: 

@mhevery thanks for building truly amazing framework plus your videos on dependency injection provides great insights on making code truly testable.... :vulcan_salute:
