### ISSUE TITLE
Currency Pipe Changes - US vs AU vs NZ Dollars

### ISSUE THREAD

**Issue by Azsael** [angular/angular#20385]
## I'm submitting a...

<pre><code>
[x] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[x] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior

In the latest release, changes from using the i18n API to internal has stopped utilising locale for when displaying currency:
So 
<div>{{10 | 'AUD':'symbol':'1.0-2':'en-AU'}}</div> will display A$10
<div>{{10 | 'AUD':'symbol':'1.0-2':'en-AU'}}</div> will display NZ$10
<div>{{10 | 'USD':'symbol':'1.0-2':'en-AU'}}</div> will display $10
before this displayed as (default locale as en-AU)
<div>{{10 | 'AUD':'symbol':'1.0-2'}}</div> will display A$10
<div>{{10 | 'USD':'symbol':'1.0-2'}}</div> will display USD$10
<div>{{10 | 'NZD':'symbol':'1.0-2':'en-AU'}}</div> will display NZ$10

## Expected behavior

I would expect consistent behaviour or to utilise locale to display currency. If locale wasn't utilised I would expect 
<div>{{10 | 'USD':'symbol':'1.0-2':'en-AU'}}</div> will display US$10
otherwise I would expect utilise current locale setting.

The app I am working on handles all three currencies (NZD, AUD, & USD), and it utilised by people who travel so US customers to AUD products and vice versa are common, so clarity on currency is important.

## What is the motivation / use case for changing the behavior?

The app I am working on handles all three currencies (NZD, AUD, & USD), and it utilised by people who travel so US customers to AUD products and vice versa are common, so clarity on currency is important.

People book a wine tour from US for their visit to Australia, the people in the admin staff manage the tours through central app which has all NZ, US, & AU tours, etc.

## Environment

<pre><code>
Angular version: 5.0.1
Browser: N/A
 For Tooling issues: N/A
Others: N/A
</code></pre>

**Comment by ocombe** [comment]
I don't understand what the problem is, could you create a stackblitz (https://stackblitz.com/) showing the error please?
The behavior is supposed to be the following:
- if you don't provide a locale in the pipe, it will use the locale of the application
- the default locale for Angular is "en-US"
- you can change the default locale by providing the `LOCALE_ID` in your main module (or using `--locale` with the CLI in AoT mode)
- if you set the locale in the pipe it will use that and ignore the application locale

Is this not the behavior that you notice?

**Comment by Azsael** [comment]
Hey, sorry for being Confusing.

Here: https://angular-xkimgk.stackblitz.io

Problem is, locale isn't defining what "currency" symbol is being selected.

In CurrencyPipe (https://github.com/angular/angular/blob/161f88fe6f8399a92ed7ab120f0d4ec647f7b139/packages/common/src/pipes/number_pipe.ts), the findCurrencySymbol method is being called without defining what locale and if you follow code goes to generated currency code list (https://github.com/angular/angular/blob/079d884b6cbe179c3565d8db443d76b1ae041af7/packages/common/src/i18n/currencies.ts), where USD is defined only as $.

In previous version, by using the i18n libraries, if locale was en-AU, then australian (AUD) currency would be $10, and USD would be as USD$10, and vice versa if you swapped locale.

I am not using symbol-short as I need to deal with all three currencies in the app,, so would be good if we aren't considering locale in particular that the currency symbol we use is consistent/not country bias.

**Comment by ocombe** [comment]
Ok I understand the problem and you're right, according to CLDR data AUD is $ in en-AU: https://github.com/unicode-cldr/cldr-numbers-modern/blob/master/main/en-AU/currencies.json#L124
and it's A$ in en-US: https://github.com/unicode-cldr/cldr-numbers-modern/blob/master/main/en/currencies.json#L123

We've extracted the currencies based on "en-US" locales only because it takes a lot of place to store currencies in all of the locales and we didn't even think about those kind of use cases.
We could maybe add this in the "extra" package

**Comment by dgfranklin** [comment]
@ocombe: I'm a Googler and my team is also facing this issue. What are your plans and eta for dealing with this? I'm willing to contribute if you're out of bandwidth.

**Comment by ocombe** [comment]
We have a meeting to discuss this next Tuesday, it should not be very hard to resolve once we've agreed on the change.

**Comment by vicb** [comment]
@ocombe Could you please describe what we discussed during our meeting ?

IIRC we decided that:
1 - we will NOT include all the names for all the currencies in all the locales,
BUT
2 - we will update the pipe to take an optional override.
