### ISSUE TITLE
ngModelOptions 'overriding' is preventing the model from updating

### ISSUE THREAD

**Issue by pafrench** [angular/angular#20384]
## I'm submitting a...
<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior
Setting the ngModelOptions updateOn to blur in the custom textbox component works as expected. However, also setting the ngModelOptions updateOn to blur on an 'instance' of the custom textbox component prevents any changes.

## Expected behavior
The ngModelOptions specified on the component instance (the 'outermost' setting) should take precedence, and should not prevent the model from changing.

## Minimal reproduction of the problem with instructions
http://plnkr.co/edit/9DB4NMnemmseytWr6u25?p=preview

Both of the custom text boxes (inputs) point to the same model, but the second has an 'overriding' ngModelOptions specified. Changing the first input behaves as expected; changing the second does nothing (with no error reported).

## What is the motivation / use case for changing the behavior?
If any other developers use a custom component that already has ngModelOptions specified and then specify their own ngModelOptions, the component no longer works as expected.

## Environment

<pre><code>
Angular version: 5.0.0

Browser:
- [x] Chrome (desktop) version 61.0.3163.100
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: v8.9.0
- Platform:  Windows

Others:

</code></pre>

**Comment by kara** [comment]
The "updateOn: blur" functionality on the top level depends on the control value accessor underneath it implementing `registerOnTouched` properly. It looks like your custom component saves the callback, but never actually calls it. Since it's not called, the value doesn't update properly. I'd recommend adding a `(blur)="onTouchedCallback()"` to your CVA and it should work.

It appears this behaves as expected. If you still feel there is an issue, please provide further details in a new issue.
