### ISSUE TITLE
Get rid of RxJs 

### ISSUE THREAD

**Issue by AntoniBertel** [angular/angular#20390]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[x] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior
Please take a look at this expression and try to explain why it leads to memory leak:
<code>
this.store.select(gT).filter(n => n.status=='status').take(1).subscribe(n => console.log(n) );
</code>
</br>
This expression leads to memory leaks because of unclosed subscribers when 'filter' returns false and there are a lot of cases such this. I don't want to double care about my memory, JavaScript cares about it.
This is not native angular, but this is ngrx extension, which, I believe, was implemented because of Angular have started using Rx under the hood. 

## Expected behavior
Angular get rid of RxJs. (Replace to promises in native API?)

## What is the motivation / use case for changing the behavior?
I hope that there is the way to control backpressure and combine streams with smallest and simplest library than rx.

**Comment by Wykks** [comment]
This has nothing to do with angular. This code: `this.store.select(gT).filter(n => n.status=='status').take(1).subscribe(n => console.log(n) ); ` as you said is "not native angular". You are completely free to use something else than rxjs to do that...

That said, doing `take(1)` after a `filter` doesn't garanties that it's going to be unsubscribed. So why not doing it correctly ? Like a`takeUntil` just after the `select` for example ?

**Comment by ghetolay** [comment]
The problem with that code is that you're not following the best practice of always unsubscribing and your example is a good example to show why that best practice exist. You should always unsubscribe from observable because even if it seems useless at first look it may not be and a change somewhere along the observable chain later may make that unsubscribe mandatory.
Angular provides the async pipe to take of it for you, or you can use the pattern using `takeUntil/ngOnDestroy`.

Any framework, lib, language can be used wrongly and create bad behavior like memory leaks.

You're not providing any alternative, remove rxjs and then what ? use callbacks ?

In the end Angular will probably get rid of rxjs because [Observables are going to be part of ecmascript](https://github.com/tc39/proposal-observable) (another reason to use them).

**Comment by AntoniBertel** [comment]
@Wykks , 

How many developers have read the book about the reactive extensions? Not enough. How many of them pick tools are popular because they widely used in the community? Too much. Angular natively respond with Observable, for example, please take look at [Angular HTTP](https://www.google.com)[https://github.com/angular/angular/blob/master/packages/http/src/http.ts] and this makes popular all others extensions based on rx.
takeUntil forces me to introduce a new local variable and rely on 'ngOnDestroy' call, or use an additional decorator - not too good for performance. Too heavy just to make sure that my component will be destroyed by GC.

@ghetolay,
This is not easy to debug angular application to memory leaks, with rx it's almost impossible. If your application is huge, I promise you'll find more than 1.000 detached nodes after few pages iterations. Try to deal with that.
I personally like rx and benefits they are introducing, especially when I working with events, or combine streams, but to my mind, it should be optional. If there is a possibility to not increase a complexity of code, why to not use it? By the way, you can find set of articles like "Don't unsubscribe" with 'best practices'.

**Comment by Wykks** [comment]
The code you shared is using rxjs _independently_ of angular. I am aware that angular expose rxjs in is API.
I think you should open an issue to rxjs instead of angular. You may have more detailed answer.

I agree. It's hard to debug, and not easy to understand.
But, that's just how observable works. Without explicit operator you're saying "let's subscribe to this stream.. Forever". Maybe there's a better solution that magically unsubscribe for you. When? How? Try to answer that if you can, you will for sure help a lots of people...

**Comment by ghetolay** [comment]
> takeUntil forces me to introduce a new local variable and rely on 'ngOnDestroy' call, or use an additional decorator

I could agree here that Angular may provide something to easily works with observable inside component code, the equivalent of the async pipe for templates.

>Moreover, in the case above I don't need to keep Subscriber live in sync with the component lifecycle, I would like to destroy it ASAP to not keep in memory.

With both `take(1)` and `takeUntil()` you will unsubscribe when either you get a result or when the component is destroyed. If you want to unsubscribe at first emit no matter the filter result you should move your `take(1)` as the first operator of the chain. In that specific case where ngrx store is sync you wouldn't need to use `takeUntil()` or `unsubscribe()` but again it's not recommended.

> it should be optional. If there is a possibility to not increase a complexity of code, why to not use it?

You still didn't answer to what should be used instead if it becomes optional ?

> By the way, you can find set of articles like "Don't unsubscribe" according to "best practices".

You should read those articles and not just their titles. It's about not managing subscription and calling `Subscription.unsubscribe()` yourself but rather use operators to manage it for you (like `takeUntil()`).

**Comment by AntoniBertel** [comment]
@Wykks, better to not subscribe when I don't need to. Angular inflates the popularity of rx, but there is no needs to use it. There is a real problem projects spending hundreds of man-hours on fixing issues emerging from rx.

@ghetolay,
Good to hear you never met the difficulties with opened subscribers somewhere in an application. 
Based on your recommendations about 'unsubscribe and takeUntill', looks like you didn't get what I tried to show. The alternative can be an ES2015 compliant promise.

**Comment by Wykks** [comment]
Well If you don't need to subscribe, assuming you're using `ngrx` you can use `getState` and read your store directly without any subscription.
Just like `BehaviorSubject` where you can get the last value with `getValue()`.

**Comment by zoechi** [comment]
If you don't want to use RxJs just don't use it. It's really as simple as that.
Where Angular uses it implicitely, it takes care of unsubscribing as well.
Http requests always only emit one value, therefore you are safe here as well.

Your assumption that JS always takes care of your memory is not true.
If you use `addEventListener` or similar, you have the exact same issue eben without using any RxJs.

**Comment by fxck** [comment]
> I could agree here that Angular may provide something to easily works with observable inside component code, the equivalent of the async pipe for templates.

[Observable lifecycle events](https://github.com/angular/angular/issues/10185).

**Comment by AntoniBertel** [comment]
@zoechi, the complexity of unbinding events and closing streams is incomparable for me. 
There are few ways to remove all events handlers or part of them from the single entrance point - DOM node. 

@zoechi,
Probably you missed my comments above. RxJs in the core of Angular provokes the spread of the rx to all other parts. (ex - ngrx). I agree with you that Angular takes care of own streams.

Be ready to understand why you can't use EventEmitter in your services (Uses Rx.Observable), be ready to waste days of time trying to figure out which of components and why not being collected by GC, be ready apply decorators (and apply ngOnDestroy manually) and write: subscribe().unsubscribe(), be ready to dig into async pipe Github's issues and patch the library.

**Comment by zoechi** [comment]
> @zoechi, the complexity of unbinding events and closing streams is incomparable for me.

but they are

> Probably you missed my comments above

No, I didn't. Most devs love it. Some complain instead of investing their time in learning and understanding the benefits.

> Be ready to understand why you can't use EventEmitter in your services 

The weirdest thing about that is, that you tried. Nowhere in the Angular docs is it suggested.

You're beating a dead horse.

**Comment by jasonaden** [comment]
@AntoniBertel Thank you for the issue. Clearly this sparked a bit of a discussion around this topic.

As mentioned by others, it's probably best to report memory leaks with Rx, as well as to unsubscribe from streams OnDestroy.

That being said, for now packages such as HTTP, Router and Forms do rely on Rx's Observable and operators from Rx. That is unlikely to change in the immediate future due to other priorities for the team right now.

Core relies on Subject for EventEmitter. We've looked at getting rid of this dependency and creating a poly fill for Observable so if you don't want to, you could avoid using Rx completely.

At the same time, Rx has been going through some changes to make it easier to use, easier to treeshake, and to drastically shrink the size of the library. The shrinking work isn't done yet, but that will be coming, at which point the overhead for including Rx and operators will be extremely small.

For a tool like NgRX, app developers have to decide what libraries to use in their applications. It's not specifically pushed by the Angular team though.

I'm going to close this issue as it's not something that's on the roadmap at this point, other than removing the dependency on RxJS's Observable implementation specifically (still to be determined if this will happen, but it's an ongoing discussion).

**Comment by ohjames** [comment]
> Angular inflates the popularity of rx. There is a real problem projects spending hundreds of man-hours on fixing issues emerging from rx.

We're finding the opposite, using rxjs is saving my company a lot of time. The issue in the opening comment is immediately apparent to me. Sure rxjs is powerful and can be misused but once you learn the concepts thoroughly it's a massive productivity boost.

I do wish lifecycle events were provided as observables though as reconciling the world of @Input with observables can be difficult. With that it would also be trivial to write a utility to subscribe to an observable until the component is destroyed. Those are my only gripes.
