### ISSUE TITLE
aio: ux problem with interaction of site search field and browser search field

### ISSUE THREAD

**Issue by GoNode5** [angular/angular#20428]
## Current behavior
Chrome search on width screen >1280 overlaps search.
## Expected behavior
The search should be visible.  The SearchBar should not be right aligned.
Browser:
- [ X] Chrome (desktop) version XX
![image](https://user-images.githubusercontent.com/2210672/32794482-495c1ec0-c969-11e7-98ba-25469c70478d.png)

**Comment by gkalpak** [comment]
Why do you think that? It is a Chrome decision to display the browser search box in this way and it will inevitably obfuscate whatever is currently placed on the top rght corner of the page. I don't see this as a reason to keep the top right corner of the page empty.

**Comment by GoNode5** [comment]
Some people look at  responsive pages on a desktop computer , with Chrome, reading from left to right, on screens larger then 667px...

**Comment by gkalpak** [comment]
I still don't understand the reasoning. If you are not searching with Chrome, close the Chrome search box. If you are searching with Chrome, then you don't really care about our search box. I prefer to have the search box in a more predictable position, clearly decoupled from the nav items (but UX is not my strong suite :grin:).

What do others think?

**Comment by petebacondarwin** [comment]
I agree with @gkalpak - I don't see why you would need to leave the Chrome search box open when doing a site-wide search.

**Comment by GoNode5** [comment]
If you search and get a hit with a lot of items or a long pages I use page search CTR-F to search the page... If I wan to return to the searchbar as show to look at another item I cannot see the search anymore. @gkalpak UX is one of my stronger point :-)
![searchproblem](https://user-images.githubusercontent.com/2210672/32866758-94723a42-ca69-11e7-82a4-b99411ce0b9c.gif)

**Comment by petebacondarwin** [comment]
But if the Chrome search is in focus then simply hitting the escape key hides it.

**Comment by GoNode5** [comment]
@petebacondarwin I don't need a lecture on using Chrome after using it for almost 10 years...  I never had a problem with other >1..000 websites before. 
Maybe a UX designer  at Google or Angular could give an opinion?

**Comment by IgorMinar** [comment]
@GoNode5 your suggested change makes the search box look out of place for most desktop users:

<img width="1912" alt="screen shot 2017-11-22 at 3 06 06 pm" src="https://user-images.githubusercontent.com/216296/33153467-c0742060-cf96-11e7-91bf-1a419d68bc9b.png">

Can you please suggest an option that looks better than that? I'm not a designer :-)

Otherwise I'm inclined to say that this is a chrome bug, because it's chrome's UX that is obscuring and interfering with the content. I don't believe that applications should be making user agent specific UX accommodations. 

@sjtrimble do you have an opinion about this?

**Comment by GoNode5** [comment]
@IgorMinar there is another ux problem with search in the first place, because the search/filter closes,  you have search again. That's why there is a conflict with Chrome searchbar. While a good first try, I think the search capabilities need much improvement. Call it everytime a Chrome bug according to Angular, while Chrome is daily used by maybe a billion people daily is a bit  'we know it better'. Don't think Chrome is gone change this because an ux problem on 1 documentation site. Firefox has search in the bottom, the first time I thought find was not working, I didn't expect it to see at bottom, so I didn't noticed. Not really a solution either. This is mainly a problem with bigger screens (>=1920 + >=24inch).
I propose:

  @media >1280
aio-search-box.search-container {
    justify-content: flex-start; (instead of flex-end)

**Comment by petebacondarwin** [comment]
@GoNode5 - thank you for the suggestion. Please do put together a PR with this change so that we can review the preview that will be generated. If you have suggestions for how to improve the search workflow in general please do post them here too.

<sub>By the way, you can wrap your code snippets in triple backticks to render them in a fixed width font, which make for a better user experience in github.</sub>

**Comment by sjtrimble** [comment]
![chromebrowser-2](https://user-images.githubusercontent.com/2958442/59461132-862a9980-8dd5-11e9-9d2a-b78936155c2f.gif)

![chromebrowser-search](https://user-images.githubusercontent.com/2958442/59461125-81fe7c00-8dd5-11e9-857a-b7bfed6cec5a.gif)

Not sure if Chrome had this before but you can actually move the find box by adjusting the search bar width. Also looks like they may have moved the box to be right flush with the search bar instead of to the far right as the picture above shows.

Chrome Version for Reference: Version 75.0.3770.80 (Official Build) (64-bit)

@petebacondarwin @IgorMinar should we close this since the user can manually move the browser find/search box themselves where they want it?

**Comment by ajitsinghkaler** [comment]
@petebacondarwin @IgorMinar I think we can close this issue

**Comment by ajitsinghkaler** [comment]
@petebacondarwin @IgorMinar I think we can close this issue

**Comment by petebacondarwin** [comment]
Yes, thanks for the prompt @ajitsinghkaler - since there are workarounds and no PR for this, I agree.
