### ISSUE TITLE
BUG: service-worker not working correctly in firefox 

### ISSUE THREAD

**Issue by kukjevov** [angular/angular#20437]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[X] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior

When i run application which uses `ServiceWorkerModule` it works correctly in Chrome, but in Firefox only assets are cached and data are not stored in `Cache`. Also on first attempt it looks like it freezes and then it starts. It behaves weird in Firefox.

## Expected behavior

It should work same in both browsers or in all where it is supported :).

## Minimal reproduction of the problem with instructions
Here is repository which contains compiled application which does not work in firefox correctly https://github.com/kukjevov/ng-universal-demo/tree/ngswnoaotbin/1.0

In `wwwroot` is compilation result and you can run it by first running
`npm install connect && npm install serve-static && npm install connect-history-api-fallback && npm install http-proxy-middleware && npm install yargs && npm install body-parser && npm install webpack && npm install webpack-dashboard` and then run `npm run server` and at url `http://localhost:8888/ ` you will see that if you open it and then close server only assets are served from cache and any `/api` call fails.

Do not run `npm install` since it is dependent on packages which are not available on public NPM. 

## Environment

<pre><code>
Angular version: 5.0.1

Browser:
- [ ] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [X] Firefox version 57
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: 8.1.2
- Platform:  Windows

Others:

</code></pre>

**Comment by MatteoNY** [comment]
Also having issue with Firefox using Firebase. If I disable the service-worker then Firebase data appears. Chome has no issues. 

Angular CLI: 1.6.0-beta.0
Node: 8.9.0
OS: win32 x64
Angular: 5.0.2
... animations, common, compiler, compiler-cli, core, forms
... http, language-service, platform-browser
... platform-browser-dynamic, platform-server, router
... service-worker

@angular/cdk: 5.0.0-rc0
@angular/cli: 1.6.0-beta.0
@angular/material: 5.0.0-rc0
@angular-devkit/build-optimizer: 0.0.33
@angular-devkit/core: 0.0.20
@angular-devkit/schematics: 0.0.36
@ngtools/json-schema: 1.1.0
@ngtools/webpack: 1.9.0-beta.0
@schematics/angular: 0.1.5
typescript: 2.4.2
webpack: 3.8.1

Firebase:
"angularfire2": "^5.0.0-rc.4"
 "firebase": "^4.6.2"

When I unregister the "ngsw-worker.js" in Firefox (latest) Firebase/Firestore data works as expected otherwise page and links appear without data.  Chrome works as expected without any issues.

Firebase has no issues with Chrome. I have to assume if not cached by the service-worker then
it's dynamic data by default. Not too sure why Firefox has an issue dynamic data should be ignored. 

ngsw.json - I experimenting by adding "dataGroups" but it does not apear resolve the Firefox issue.
Clear documentation or a revised tool like  "ng-pwa-tools": "0.0.15".
re: Google I/O 2017 video with Stephen Fluin and Alex Rickabaugh. Would be great. 

With the ng-pwa-tools dynamic data was prepared along with router links. I'm not too sure about the new ngsw.json and how to prepare router links as well as Firebase (server-side dynamic data) that worked fine in Firefox using the ng-pwa-tools. 

I did attempt to use the ng-pwa-tools they no longer appear to work with latest Firebase/Firestore and produced an error in node_module. 

In addition, I've been following the Angular Connect 2017 video from Maxim Salnikov which got me into exploring the latest Angular CLI 1.6 build. 

I'm hoping for a newer Angular CLI 1.6 release to make service-workers a default.
I'm also hoping for documentation to describe how to use to cache static, router links, dynamic and push notifications from Firebase and node servers. Also Angular CLI SWTooling support to configure if needed.  In addition, how to manage SW updates as needed. Security is also importance. 

Thanks for your help.


EXAMPLE: ngsw.json with added dataGroups (did not help Firebase/Firefox issue not sure if correct as it's different then ng-pwa-tools)

{
  "index": "/index.html",
  "assetGroups": [
    {
      "name": "app",
      "installMode": "prefetch",
      "resources": {
        "files": [
          "/favicon.ico",
          "/index.html"
        ],
        "versionedFiles": [
          "/*.bundle.css",
          "/*.bundle.js",
          "/*.chunk.js"
        ]
      }
    },
    {
      "name": "assets",
      "installMode": "lazy",
      "updateMode": "prefetch",
      "resources": {
        "files": [
          "/assets/**"
        ]
      }
    }
  ],
  "dataGroups": [{
    "name": "api-freshness",
    "urls": [
      "https://myfirebaseApp.firebaseio.com"
    ],
    "cacheConfig": {
      "maxSize": 100,
      "maxAge": "3d",
      "timeout": "1m",
      "strategy": "freshness"
    }
  }
  ]
}

**Comment by andre-gois** [comment]
Having the same issue, has anyone found a fix?

**Comment by prashu2705** [comment]
Hi,

Is there any update on this bug, any timeframe by when the fix will be available?

**Comment by gkalpak** [comment]
I tried with the latest `@angular-service-worker` and data groups seem to be cached and served correctly.
If you are still seeing problems, please open a new issue with a minimal reproduction (using latest Angular versions).
