### ISSUE TITLE
**docs(aio):** Rename HttpClient.request's first parameter to method

### ISSUE THREAD

**Issue by mark-langer** [angular/angular#20481]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Feature request
[ x ] Documentation issue
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior
The documentation of the [HttpClient's request method](https://angular.io/api/common/http/HttpClient#members) lists the `first` parameter.

## Expected behavior
 Technically it makes more sense to call that parameter `method`. That's what it's called in the code too.

## Minimal reproduction of the problem with instructions
Open [the documentation](https://angular.io/api/common/http/HttpClient#members).

## What is the motivation / use case for changing the behavior?

Help everyone understand the API docs better.

## Environment
 not applicable

Others:

</code></pre>

**Comment by gkalpak** [comment]
The parameter is [actually called `first`][1] in code. The docs are automaticaly generated from the source code anyway.

The reason for using `first` is that this is an overloaded method and its first argument can be either a string (method) or an `HttpRequest` (a request).

Closing since the current behavior is intended.

[1]: https://github.com/angular/angular/blob/9de45fa65069af5015c33fee439776c1bf560af6/packages/common/http/src/client.ts#L333
