### ISSUE TITLE
Spelling error "appHightlight" on https://angular.io/guide/attribute-directives

### ISSUE THREAD

**Issue by Gi11i4m** [angular/angular#20581]
## I'm submitting a...
<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Feature request
[x] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior
On the Attribute Directives page (https://angular.io/guide/attribute-directives), appHighLight is spelled wrong in the first code example. You can find it at this anchor => https://angular.io/guide/attribute-directives#build-a-simple-attribute-directive

## Expected behavior
_appHighlight_ is spelled correctly.

**Comment by gkalpak** [comment]
This has been fixed on master by #20143 (as can be seen [here][1]).
It seems that the change hasn't been cherry-picked to the stable branch (where `angular.io` gets generated from).

@mhevery, was it intentional or something went wrong with the merge scripts?

[1]: https://next.angular.io/guide/attribute-directives#build-a-simple-attribute-directive

**Comment by mhevery** [comment]
it is cherry picked as a5a82296b7 in 5.0.x branch as of Nov 22nd.

**Comment by gkalpak** [comment]
Thx, @mhevery.
@Gi11i4m, the fix has been deployed to stable as well. Thx for reporting 👍
