### ISSUE TITLE
DatePipe format string is invalid

### ISSUE THREAD

**Issue by rsaenen** [angular/angular#20637]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior
With `{ provide: LOCALE_ID, useValue: 'fr-FR' }`   
`{{ '1989-01-02' | date: 'dd MMMM yyyy' }}` displays 02 janvier 1989. (0h00)   
`{{ '1989-10-27' | date: 'dd MMMM yyyy' }}` displays **26** octobre 1989. (23h00)   

## Expected behavior  
`{{ '1989-01-02' | date: 'dd MMMM yyyy' }}` displays 02 janvier 1989. (0h00)     
`{{ '1989-10-27' | date: 'dd MMMM yyyy' }}` displays **27** octobre 1989. (0h00)     
I don't get the issue with IE11.   

I use a new date pipe which is working with Chrome, FF and IE11:
```typescript
import { Injectable, Pipe, PipeTransform } from '@angular/core';
import { DatePipe } from '@angular/common';

@Injectable()
@Pipe({ name: 'customDate', pure: true })
export class CustomDatePipe extends DatePipe implements PipeTransform {
    transform(value: any, format: string): string {
        value = new Date(value);
        return super.transform(value, format);
    }
}
````

The difference comes when the date is parsed, Date.parse() is replaced by new Date().

## Environment

<pre><code>
@angular/cli: 1.2.0 (e)
node: 8.5.0
os: win32 x64
@angular/animations: 4.4.6
@angular/common: 4.4.6
@angular/compiler: 4.4.6
@angular/core: 4.4.6
@angular/forms: 4.4.6
@angular/http: 4.4.6
@angular/platform-browser: 4.4.6
@angular/platform-browser-dynamic: 4.4.6
@angular/router: 4.4.6
@angular/cli: 1.2.0
@angular/compiler-cli: 4.4.6
@angular/language-service: 4.4.6
@ngtools/webpack: 1.5.0

Browser:
- [x] Chrome (desktop) version 62.0.3202.94 
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version 11
- [ ] Edge version XX
 
For Tooling issues:
- Node version: 8.5.0
- Platform:  Windows 7

</code></pre>

**Comment by vicb** [comment]
It seems like this is an [expected behavior](https://github.com/angular/angular/blob/master/packages/common/src/pipes/date_pipe.ts#L150)

@ocombe could you please make sure there is no regression here between 4 and 5 ?
 I think this should also be documented at top level and visible on angular.io

root cause is:
```
> new Date('1989-01-27');
Thu Jan 26 1989 16:00:00 GMT-0800 (PST)
> new Date(1989, 01, 27);
Mon Feb 27 1989 00:00:00 GMT-0800 (PST)
```

**Comment by ocombe** [comment]
It's not a regression, it was the same code in v4: https://github.com/angular/angular/blob/master/packages/common/src/pipes/deprecated/date_pipe.ts#L106

The reason like the comment in the code explains is that we apply the timezone shift at the end. Since there's no way for us to know if '1989-10-27' if the date in a specific timezone or not, we do as if it had no timezone and we apply the locale timezone at the end.
But we know that this can be problematic for some people, that's why we added the timezone parameter to the date pipe in v5 so that you can fix the timezone yourself, see the docs: https://angular.io/api/common/DatePipe

https://stackblitz.com/edit/angular-nw1cea

**Comment by rsaenen** [comment]
Thanks, this help a lot.
I can't upgrade to v5 so I will set the timezone with another pipe to avoid this behavior.
Nevertheless, this will be usefull for my pet projects!
