### ISSUE TITLE
Warn if an unsupported future version of TypeScript is used

### ISSUE THREAD

**Issue by chuckjaz** [angular/angular#20669]
## I'm submitting a...

<pre><code>
[x] Feature request
</code></pre>

## Current behavior

If you 2.5 or 2.6 with `ngc`version 5.0.3 it will silently produce bad output in certain cases.

## Expected behavior

It should warn that the user is using an unvalidated combination of `ngc` and TypeScript.

Consider emitting an error unless `"disableTypeScriptVersionCheck"` is `true`.

**Comment by spock123** [comment]
I second this - cost me 2 days until I realized it was TS 2.5.2 that was the culpit.

**Comment by emilio-martinez** [comment]
I think this is pretty important and maybe the `@angular/cli` should follow this as well (cc @filipesilva) because there's such a high dependency on a typescript range.

For an example see https://github.com/angular/angular-cli/issues/8434#issuecomment-354728116. This makes it so that `typescript@next` (2.7-ish) has a fix for something seemingly generated somewhere around Angular CLI 1.6.0 (meaning that downgrading CLI fixes issue), but Angular Compiler doesn't support TS beyond 2.5, and at the same time the 1.6.x CLI release is tied to Angular 5.1.x. Ultimately, it puts somewhat of a dependency block until TS 2.7 is supported in both Angular and the CLI for something that is seemingly created.
