### ISSUE TITLE
Missing space between currency code and value in currency pipe

### ISSUE THREAD

**Issue by Lolash** [angular/angular#20708]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior
Now currency pipe, which is using default English locale and is set up to display currency code, formats the value this way:
USD100, PLN200, EUR300 etc.

## Expected behavior
According to grammar rules there should be a space between currency code and value.
http://publications.europa.eu/code/en/en-370303.htm

So above-mentioned values should be written like that:
USD 100, PLN 200, EUR 300

## What is the motivation / use case for changing the behavior?
Grammar correction.

## Environment

<pre><code>
Angular version: 5.0.3
Browser:
All browsers.

**Comment by vicb** [comment]
Angular follows the CLDR convention.
@ocombe could you please confirm the current format is correct per CLDR spec ?

**Comment by ocombe** [comment]
The currency pattern for english is `¤#,##0.00` which doesn't countain any space between the currency symbol (¤) and the numbers (https://github.com/unicode-cldr/cldr-numbers-full/blob/master/main/en/numbers.json#L109)
As a comparison, here is the pattern for french: `#,##0.00 ¤` (https://github.com/unicode-cldr/cldr-numbers-full/blob/master/main/fr/numbers.json#L109)

According to your article:
> In English texts, the ISO code ‘EUR’ is followed by a hard space and the amount: a sum of EUR 30

> However, the euro sign (when permitted) is followed by the amount without the intervening hard space: €2.50

So the rules seem to be: no space between symbol and number ($12) but space between currency code and number (USD 12).

You can find the same definition here: http://www.btb.termiumplus.gc.ca/tpv2guides/guides/wrtps/index-eng.html?lang=eng&lettr=indx_catlog_a&page=9IYDvHKNiH6Q.html
> In general texts, do not put a space between US and the dollar sign: US$2.50 (not US $2.50)
> In the area of finance, write the code first, followed by a non-breaking space and the dollar figure:    USD 350 million

Since CLDR doesn't contain formats for finance currencies, I don't think that we can fix that. They have formats for currency accounting, but it doesn't seem to be that.
The description for the currency pattern that we use is:
> Used for currency values. A currency symbol (¤) is will be replaced by the appropriate currency symbol for whatever currency is being formatted. The choice of whether to use the international currency symbols (USD, EUR, JAY, RUB,…) or localized symbols ($, €, ¥, руб.,…) is up to the application program that uses CLDR.

Which seem to point to the fact that we are indeed using the correct pattern.

**Comment by Lolash** [comment]
"Which seem to point to the fact that we are indeed using the correct pattern."

Unfortunately, you don't. You use the format provided by CLDR, which is not suited for displaying currency codes. Thus, Angular currency pipe does not work correctly for configuration with code.

**Comment by ocombe** [comment]
We've decided that we will be opening the current API used by pipes so that it is possible to provide new formats and additional data, which should make it possible to support things like this, I'll update this issue once I have more info about this

**Comment by wojofe** [comment]
A new flag for controlling the addition of a (nonbreaking) space would not be out of the question I hope?

**Comment by wojofe** [comment]
Is this going to happen in a reasonably near future or do you want people to implement their own currency code display?

**Comment by ocombe** [comment]
It's on my todo list for this week, but I'm not sure when it's going to be merged

**Comment by vicb** [comment]
Will be fixed when we open the API

**Comment by wojofe** [comment]
So, how is it coming along?

**Comment by johanssonmarcus** [comment]
Spaces could be added for currency codes (EUR) but not currency symbols (€) by changing the formatCurrency function. (This is if you want to fix it in Angular itself and not have everyone create their own pipes to solve it.)

https://github.com/angular/angular/blob/96b597cfd0935f58be689d957994a022e3601c41/packages/common/src/i18n/format_number.ts#L154-L157

change these lines to:
```
    // add spaces around currency codes (EUR) but not currency symbols (€)
    const spacedCurrency = currency.length > 1 ? ` ${currency} ` : currency;
    return res
        .replace(CURRENCY_CHAR, spacedCurrency)
        // if we have 2 time the currency character, the second one is ignored
        .replace(CURRENCY_CHAR, '')
        .trim();
```
Spaces are added to both side of the currency and then the final string is trimmed; to support both currency codes as a prefix and as a suffix. If you are more familiar with the code you can probably solve it in a prettier way.

**Comment by bazter** [comment]
For anyone looking for solution, since there's still no proper support for currencies without symbol (missing space problem): All the modern browsers (including IE11) support Intl.NumberFormat function, which handles currency formatting really well.

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/NumberFormat
