### ISSUE TITLE
Angular 4.3.x HttpClientModule cause 403 error with csrf security

### ISSUE THREAD

**Issue by faisalloe** [angular/angular#20718]
Angular 4.3.4 with spring csrf security turn on

so far i have been using HttpModule to request the rest service. server is csrf enable but Http service take care of automatically adding XSRF-TOKEN into the http request.

I decided to upgrade my HttpModule with HttpClientModule and changed Http to HttpClient and suddenly i start getting 403 error.

## Current behavior
With HttpClientModule rest service returns 403

## Expected behavior
HttpClientModule should work same as HttpModule, if i use Http service instead of HttpClient it works fine

## Environment
windows

<pre><code>
Angular version: 4.3.4

Browser:
- [X] Chrome (desktop) version XX
- [X] Firefox version XX

**Comment by Meligy** [comment]
If you have GET requests use SXRF protection, then the issue is probably https://github.com/angular/angular/issues/19885

Of course make sure you are using the now-separate `HttpClientXsrfModule` as [the docs say](https://angular.io/guide/http#security-xsrf-protection), and as explained in depth [in this post](https://www.gurustop.net/blog/2017/10/17/little-known-xsrf-defence-support-in-angular-httpmodule-v2-5-httpclientmodule-v4-3/).

**Comment by alxhub** [comment]
Closing as a duplicate of #19885.
