### ISSUE TITLE
Trying to add events in the constructor does not throw, but obviously won't work

### ISSUE THREAD

**Issue by matanlurey** [angular/angular#2074]
Example:

```html
<awesome-component (onCreated)="onComponentCreated"></awesome-component>
```

```js
@Component({
  selector: 'awesome-component',
  events: ['onCreated'],
})
class AwesomeComponent {
  constructor() {
    this.onCreated = new EventEmitter();
    this.onCreated.add(new SomethingEvent());
  }
}
```

**Comment by mhevery** [comment]
We should either queue it up, or throw. @vsavkin do you have an opinion?

**Comment by gdi2290** [comment]
Rx has a [ReplaySubject](https://github.com/Reactive-Extensions/RxJS/blob/master/doc/api/subjects/replaysubject.md) to replay events after subscribing. Since Observables are lazy this is "working as intended" since you're not subscribed to it at the time you are pushing a value into it. I noticed the same problem when I was working on an angular2 reactive example [models/CounterModel.ts#L39](https://github.com/angular-class/angular2-reactive-starter/blob/a5faad8ac977ff7766d5c917c8904386f7102132/src/app/models/CounterModel.ts#L39). Normally with Rx you would use a `ReplaySubject` of `1` so for me it would look like `public  subject: Observable = new Rx.ReplaySubject(1);` then when I subscribe to the Observable it will replay the last state on my model. Since I ended up using Rx to get my [`appState`](https://github.com/angular-class/angular2-reactive-starter/blob/22e07d540d8bcb1988f8e821eb8e32d3c8793c32/src/app/components/app.ts#L90) I may end up just using Rx Observables and updating the Async pipe to support it rather than extending angular's Observables.

**Comment by vsavkin** [comment]
This is by design. 

If you create an custom element and fire an event there, nobody will catch this event. This is because you could not call addEventListener until the custom element is constructed. It won't throw an exception either.

You can create a different implementation of EventEmitter (e.g., ReplaySubject) that will deliver the event. You can also use the onInit hook.
