### ISSUE TITLE
Literal Array trailing comma in expressions causes error

### ISSUE THREAD

**Issue by FrancescoBorzi** [angular/angular#20773]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior

The following works:

```
<div
  *ngIf="[
  'first value',
  'last value'
  ].indexOf(myVar) > -1"
></div>
```

the following gives error:

```
<div
  *ngIf="[
  'first value',
  'last value',
  ].indexOf(myVar) > -1"
></div>
```

the difference is the [trailing comma](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Trailing_commas) in the array of the `*ngIf` condition.

## Expected behavior

It should work still it's still valid javascript

## Environment

<pre><code>
Browser:
Chrome (desktop) Version:  62.0.3202.94 (Official Build) (64-bit)

Environment:

Angular CLI: 1.5.5
Node: 8.9.1
OS: linux x64
Angular: 5.0.4
... animations, common, compiler, compiler-cli, core, forms
... http, language-service, platform-browser
... platform-browser-dynamic, router

@angular/cli: 1.5.5
@angular-devkit/build-optimizer: 0.0.34
@angular-devkit/core: 0.0.22
@angular-devkit/schematics: 0.0.38
@ngtools/json-schema: 1.1.0
@ngtools/webpack: 1.8.5
@schematics/angular: 0.1.8
typescript: 2.4.2
webpack: 3.8.1

</code></pre>

**Comment by mgol** [comment]
It's not just `*ngIf` but any expression, e.g. an event handler.

Note that it works in AngularJS.

**Comment by eddybrando** [comment]
It's even not just arrays, but also objects.

The following returns a syntax error when parsing the template during `ng serve`:

```
<div [ngClass]="{
  'classFoo': foo,
  'classBar': !foo,
}">Lorem</div>
```

This is compiled without errors, tho:

```
<div [ngClass]="{
  'classFoo': foo,
  'classBar': !foo
}">Lorem</div>
```

Both are valid Typescript. Since Typescript 2.9 traling commas are not allowed, but only on rest parameters (see [breaking changes description](https://github.com/Microsoft/TypeScript/wiki/Breaking-Changes#trailing-commas-not-allowed-on-rest-parameters) and [related fix](https://github.com/Microsoft/TypeScript/pull/24672)).

Both should compile with errors, so I guess this is a bug with the way Angular compiles the templates.

**Comment by eddybrando** [comment]
@mhevery, I believe this is wrongly tagged as "feature" instead of "bug/fix" for the reasons exposed above.
