### ISSUE TITLE
HttpClient mapping to typescript types not working

### ISSUE THREAD

**Issue by TrentonAdams** [angular/angular#20770]
[widget.service.zip](https://github.com/angular/angular/files/1525443/widget.service.zip)

[widget.service.zip](https://github.com/angular/angular/files/1525442/widget.service.zip)
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[X] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior

With HttpClient automatically converting http responses to typescript types, it does not do any type casting to ensure that they are valid according to the defined types.  I presume this is happening because the final result is javascript, which doesn't enforce any type checking.

## Expected behavior

I would expect that a json "1" which is defined as a typescript "number" would be converted to said number, but instead it remains as a string "1".

## Minimal reproduction of the problem with instructions

* ng new invalidtypes
* cd invalidtypes
* copy widgets.service.ts and widgets.service.spec.ts into the app folder
* ng test

## What is the motivation / use case for changing the behavior?

The purpose of using typescript, is to have some sort of strict type checking, so as to avoid human errors.  It makes sense to ensure types are accurate internally as well, or there is confusion when things like this occur.

## Environment

<pre><code>
Angular version: 5.0.0 and 5.0.5

Browser:
- [X] Chrome (desktop) version 62.0.3202.89
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: XX  
- Platform:  
$ node --version
v8.9.0

$ uname -a
Linux trenta-VirtualBox 4.8.0-53-generic #56~16.04.1-Ubuntu SMP Tue May 16 01:18:56 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux

$ cat /etc/issue
Linux Mint 18.2 Sonya \n \l

Below is the widget service with a failing test comparing the id to 1, which should return true, but because the 1 is a string, it fails.

```
// widget.service.ts
import { Injectable } from '@angular/core';
import {Observable} from "rxjs/Observable";
import {HttpClient} from "@angular/common/http";

class Widget {
  id: number;
  title: string;
  widgetInfo: string;
  activityDate: Date;
  createDate: Date;
  user: number;
}

@Injectable()
export class WidgetsService {

  constructor(private http: HttpClient) { }

  getWidgets(): Observable<Widget[]>
  {
    return this.http.get<Widget[]>('/widgets');
  }
}
```

```
// widget.service.spec.ts
import {TestBed, inject, getTestBed} from '@angular/core/testing';

import {WidgetsService} from './widgets.service';
import {
  HttpClientTestingModule,
  HttpTestingController
} from "@angular/common/http/testing";
import {HttpClient} from "@angular/common/http";

describe('WidgetsService', () => {
  let widgetsService: WidgetsService;
  beforeEach(() => {
    TestBed.configureTestingModule({
      imports: [HttpClientTestingModule],
      providers: [WidgetsService]
    });
    let injector = getTestBed();
    widgetsService = injector.get(WidgetsService);

  });

  it('should be created', inject([WidgetsService],
    (service: WidgetsService) => {
      expect(service).toBeTruthy();
    }));

  it('should get widgets with proper types',
    inject([HttpClient, HttpTestingController],
      (http: HttpClient, httpMock: HttpTestingController) => {
        widgetsService.getWidgets().subscribe(widgets => {
          expect(widgets[0].id).toEqual(1);
        });

        const req = httpMock.expectOne('/widgets');
        expect(req.request.method).toEqual('GET');
        req.flush(
          [{
            "id": "1",
            "title": "a widget",
            "note": "the long text about the widget",
            "activityDate": "2017-11-27T13:44:50.750Z",
            "createDate": "2017-11-27T13:44:50.750Z",
            "user": null
          }, {
            "id": "2",
            "title": "another widget",
            "note": "the long text about the widget",
            "activityDate": "2017-11-27T13:44:50.751Z",
            "createDate": "2017-11-27T13:44:50.751Z",
            "user": null
          }]
        );
        httpMock.verify();
      })
  );
});
```

**Comment by matthew-ch** [comment]
I don't think it is the responsibility of Angular to check the validity of data types. The `HttpClient` just parses the response to a json object and handles it to your code. Your `Widget` interface should be modeled to fit the type of the object.

**Comment by TrentonAdams** [comment]
I'm a bit confused.

Angular accepts a type like this...
this.http.get<Widget[]>('/widgets');

Why does it do that, if it's not the intention of angular to provide mapping from json to typescript?  It certainly lead me into believing that it fully supported mapping json to typescript objects, but clearly doesn't.  That's fine if it doesn't, but it wasn't clear.

The Widget is indeed modeled to fit the type of the object that I want, it's just that the final result

**Comment by sarunint** [comment]
When you pass types into `HttpClient`, it provides you with type information when you use the result onwards. It prevents you from typing `result.wigtInfo`, for example.

**Comment by TrentonAdams** [comment]
So it's mostly meant as a way of enhancing IDE auto-completion only?

**Comment by sarunint** [comment]
In my opinion, yes, but it's *super useful*.

**Comment by TrentonAdams** [comment]
Oh, most definitely, I found that useful too.  It just ended up leading me to believe that the object I was using was type safe (the purpose of typescript), when it wasn't.  The purpose of generics is to create type safety, IDE auto-completion is just a convenient side affect of generics, not it's intended purpose. 

So, is there a way we could take it a step further, and incorporate some sort of mechanism to either ensure type safety, or provide JSON.parse() reviver functions to the process?

**Comment by mmanavaz** [comment]
I'm facing a similar issue where Typescript is not recognizing the any datatype. Not sure how to workaround this.

**Comment by alxhub** [comment]
@TrentonAdams yes - generate your interfaces from some backend schema and ensure your backend is following that same schema. A lot of projects within Google use this approach with `HttpClient`.

**Comment by TrentonAdams** [comment]
I'm not sure how that solves the problem, the intermediate transfer is still string based json, so the data will still get injected into the type safe object, and end up not being type safe.  Does your proposed solution address that?

**Comment by sarunint** [comment]
It's not TypeScript's job to recognise/convert data to the correct type. It's your job to ensure that the data returned from the API matches what you want.

**Comment by darin-cardin** [comment]
Im with @TrentonAdams . The syntax certainly gives the impression that the data returned would be of the type specified. (this.httpClient.get<User>('/user')).  From the comments above, i get the impression that this new syntax doesn't actually do anything. Thats too bad, as it would be quite useful.

**Comment by ignaciosolergarcia** [comment]
I agree with all the previous comments, I find the syntax misleading. I expect that 

`this.httpClient.get<Model>(url)`

verifies if the data coming from the get can be mapped to Model and if not then  throws. The current implementation looks and feels javascript, not typescript (imho).

**Comment by matthew-ch** [comment]
`TypeScript` only verifies the object interface at compile time. Any object that the code fetches at runtime cannot be verified by `TypeScript`.
`Angular` packages are merely a bunch of `.js` files and corresponding `.d.ts` declarations files. Magic (that `HttpClient` verifies your model) does not happen (without additional effort).
IMHO anyone with further questions should learn what `TypeScript` is.

**Comment by TrentonAdams** [comment]
If a piece of software uses TypeScript, *that* piece of software should also deal with the subtleties of TypeScript, or simple not use it.  Not doing so causes confusion.  One is professional, the other is not.

**Comment by iamwyza** [comment]
> `TypeScript` only verifies the object interface at compile time. Any object that the code fetches at runtime cannot be verified by `TypeScript`.

If this is the case, then things like HttpClient.Get<T> should not return Observable<T>.  It should return Observable<Object> because that's what is actually returned.  Trying to state that it returns T when it returns Object is misleading.  

the client's return says this:
```@return an `Observable` of the body as type `T`.``` 

In reality, it should say:
```@return an `Observable` of the body which might be `T`.``` You do _not_ get T back.  If you got T back, it would actually be T, but it's not.  



To look at it another way if I wrote this:

```typescript
export class Widget<T> {
    getValue(input: string): T {
         return new T(string);
    }
}

let thisShouldBeADate = new Widget<Date>().getValue("2017-01-01T02:00:00");
```

I would expect the call to the method to return a `Date` object.  If it for some reason returned a string, I'd be exceptionally confused. 

At the very least the JSDocs for HttpClient need to change to note that the generic is there purely for the IDE and has no meaningful impact on the actual object returned and that it's up to the developer to create translation objects/methods/interceptors for all their HttpClient calls the contain anything other than base types.

**Comment by TrentonAdams** [comment]
@iamwyza Interestingly your last paragraph reveals the anti-pattern of it all; which is something to compensate for a bad design pattern.  It's like saying "Because the angular developers decided they didn't want to do it the right way, the least they can do is let us know so we can hack around it".  I'm not saying that to be insulting, but that is indeed what's happening.

"An anti-pattern is a common response to a recurring problem that is usually ineffective and risks being highly counterproductive."
https://en.wikipedia.org/wiki/Anti-pattern

**Comment by matthew-ch** [comment]
@iamwyza Your code wouldn't pass `TypeScript` type-checking, because that's not how you use `T`.

Consider the following code:
```typescript
function foo<T>(x: any): T {
    return x as T;
}

const s = foo<string>(1);
const t = s.slice();
```
Now `TypeScript` decides both `s` and `t` have type `string`, and doesn't complain about anything.
But we all know that code will result in runtime error when executing `const t = s.slice()`.

From the documentation http://www.typescriptlang.org/docs/handbook/basic-types.html, search for *Type assertions*. You will find:
> Type assertions are a way to tell the compiler “trust me, I know what I’m doing.” A type assertion is like a type cast in other languages, but performs no special checking or restructuring of data. It has no runtime impact, and is used purely by the compiler. TypeScript assumes that you, the programmer, have performed any special checks that you need.

See, it is implied by `TypeScript` and the "JSDoc for HttpClient" doesn't have to do that.

**Comment by iamwyza** [comment]
You can use the exact same paragraph to argue the other way.  By asserting that HttpClient is saying "Trust me I know what i'm doing".  It all comes down to where the responsibility lies to ensure that the object you get back is what you expect it to be.  The way the documentation, examples, etc are laid out, it is inferred that you get back an object of type T when you use HttpClient with generic parameters.  I know that isn't the case, but the JSDocs state exactly the opposite of what you are saying.  

So 1 of 2 things should change.

1. The JSDocs should not say that it returns T.  This is dead simple to do, requires no coding changes, and doesn't change in any way how Angular works.  It purely helps new developers realize that generics don't work the same way in Typescript as in other languages and that Angular is passing the responsibility to the developer to take the thing that is similar to T and make it an actual T.  This is OK.  But if the docs says "Returns T", then it had better well return T.

2. The methods should actually return T.  This is harder, though I imagine the vast majority of the time, the most complex thing that can't be easily returned is the Date object.

**Comment by matthew-ch** [comment]
> By asserting that HttpClient is saying "Trust me I know what i'm doing".

That's not correct interpretation. The *me* refers to you, because it's you who can tell the compiler what your actual data structure is, not HttpClient.

I just grab this from HttpClient source code:
```typescript
  /**
   * Construct a GET request which interprets the body as JSON and returns it.
   *
   * @return an `Observable` of the body as an `Object`.
   */
  get(url: string, options?: {
    headers?: HttpHeaders | {[header: string]: string | string[]},
    observe?: 'body',
    params?: HttpParams|{[param: string]: string | string[]},
    reportProgress?: boolean,
    responseType?: 'json',
    withCredentials?: boolean,
  }): Observable<Object>;

  /**
   * Construct a GET request which interprets the body as JSON and returns it.
   *
   * @return an `Observable` of the body as type `T`.
   */
  get<T>(url: string, options?: {
    headers?: HttpHeaders | {[header: string]: string | string[]},
    observe?: 'body',
    params?: HttpParams|{[param: string]: string | string[]},
    reportProgress?: boolean,
    responseType?: 'json',
    withCredentials?: boolean,
  }): Observable<T>;
```

The JSDoc says "*interprets the body as JSON and returns it*".  So it's clear what HttpClient does.

The second `get` returns an an `Observable` of the body as type `T`, because you specifically tell the compiler the type of the `Object`, and you get type-checking when consuming the data.
For example, suppose `Model` has an property with name `stringProperty`,
```typescript
  this.httpClient.get<Model>(url).subscribe((model) => {
    const s = model.stringProperty;
  });
```

But if you omit the `Model`,
```typescript
  this.httpClient.get(url).subscribe((model) => {
    const s = model.stringProperty;
  });
```
TypeScript will emit an error saying "Property 'stringProperty' does not exist on type 'Object'."

It's true *generics don't work the same way in Typescript as in other languages*, but that's just the way it is.
It might be unrelated but I once saw in the movie that somewhere in Africa, the locals shake their heads left-and-right to express 'yes', while in many other cultures as I believe, that action means 'no'.

**Comment by iamwyza** [comment]
I disagree on who "me" is.  It's ambiguous.  If I wrote the method that had the generic, then yes, "me" would refer to myself.  However, If I'm consuming a method that someone else wrote, then "me" refers to that person unless otherwise specified. In the case of a framework, someone else is defined as the collective set of developers who worked on the framework. 

I never disagreed with what the JSDocs said about the non-generic form of get.  It's exactly correct.  The generic form of get is not.

Sadly it seems that we will not be able to move past this.  My stance is that the documentation should be more clear for newer entrants into the framework and your stance is that it is clear enough.

**Comment by matthew-ch** [comment]
If you write the method with generic type `T`, how would you know the exact type at runtime when someone else is using it? What you can do with arguments of type `T` is limited, because the actual type varies.
Likewise, you provide the actual type for `T` when you invoke a method with generic type that someone else wrote, because you know what you are doing, you know the structure of your data.

The `T` part of  the `get` method of HttpClient means, if the body contains JSON with structure like `T`, you get an `Observable<T>`. So you have to be sure to model `T` according to the data.

Suppose you are to use a framework written in C++, the author would assume you have the knowledge of C++, and the docs need not to include language tutorials.

It's not fair to blame Angular for not making the docs more clearer, because it assumes you know TypeScript already.

I'm no expert in any of these, and my explanations are not all correct. So I hope someone else can settle this.

**Comment by kimmoeklund** [comment]
My .2$ as someone coming from JVM world (Kotlin/Java) and still learning Angular and TypeScript: the syntax is misleading before one learns about TypeScript type assertions. All Java/Kotlin http-rest libraries I know would throw runtime exception when cast fails.

With this I don't mean TypeScript or HttpClient should work like JVM languages or libraries, simply saying that having a note about this in the docs would be a service to people coming from different backgrounds to Angular. For example https://angular.io/guide/http#type-checking-the-response doesn't mention anything about it. 

I for example learned this issue from this thread which I found after some searching while trying to understand code below (from the Heroes tutorial). What puzzled me was why `<Hero>` instead of `<void>` and why `<Hero>` doesn't produce runtime exception as I didn't expect rest-api to return deleted object in the response body.

```javascript 
  /** DELETE: delete the hero from the server */
  deleteHero (hero: Hero | number): Observable<Hero> {
    const id = typeof hero === 'number' ? hero : hero.id;
    const url = `${this.heroesUrl}/${id}`;
 
    return this.http.delete<Hero>(url, httpOptions).pipe(
      tap(_ => this.log(`deleted hero id=${id}`)),
      catchError(this.handleError<Hero>('deleteHero'))
    );
  }
```

**Comment by c4deszes** [comment]
Coming from Java Spring it's very misleading. Even with the examples you would expect it to return the correct type and not just the values. Is this a limitation of TS or just Angular?

**Comment by trotyl** [comment]
> Add or rely on run-time type information in programs, or emit different code based on the results of the type system. Instead, encourage programming patterns that do not require run-time metadata.

It's an [TypeScript's explicit non-goal](https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals#non-goals).

**Comment by TrentonAdams** [comment]
It has nothing to do with typescript, because typescript can't control what you do with the data.  Typescript is a wrapper for javascript, nothing more.  It truly is an angular issue.

**Comment by trotyl** [comment]
> Use a consistent, fully **erasable**, structural type system.

@TrentonAdams Do you have any idea what is **erasable**? The type information doesn't exist in runtime at all.

**Comment by darrenhollick** [comment]
I hate to even jump in on this discussion as it seems to have devolved into personal attacks but I am hoping that people on both sides can help me answer what I think is more real-world example of where some type checking would be extremely valuable.  Please consider the following example:

The following JSON is returned by a data service somewhere:
```json
{
    id: 1234,
    name: "Testy Testerson",
    createdUTC: "2018-07-12T16:00:00Z"
}
```
The following model exists in our project:
```typescript
export interface SimplePerson {
    id: number;
    name: string;
    createdUTC: Date;
}
```
The following code exists in our project:
```typescript
this.http.get<SimplePerson>(apiBase + "/person/1234").subscribe(person => {
    var x = person.createdUTC.getSeconds(); // This line will compile but will error at runtime
    var y = person.createdUTC.slice(4); // This line won't compile but would work at run time
});
```

- There isn't a problem at the server because it returned well formatted JSON that properly maps the expected object.
- There isn't a problem with the model, it perfectly matches what the data service returned.

### My Conclusion
Dates are where this issues comes alive in biggest way for me.  It would be amazing if Angular would take the returned data and since we've informed the HttpClient of the type we're expecting back attempt to map it correctly.  I'm not an expert, just a daily user and this is very common problem.

Suggestions welcome!

**Comment by trotyl** [comment]
@darrenhollick It fails because you declared the type to be `SimplePerson` while it wasn't. TypeScript could only check the type according to declaration, but cannot have if you provides the wrong type.

**Comment by TrentonAdams** [comment]
@trotyl I did not use the term erasable, so I'm not sure what you are referring to, nor do I see the statement you quoted within the issue comments.

**Comment by trotyl** [comment]
@TrentonAdams I mean please understand what TypeScript is before using it.

https://github.com/Microsoft/TypeScript/wiki/TypeScript-Design-Goals

**Comment by matthew-ch** [comment]
@darrenhollick 
> - There isn't a problem with the model, it perfectly matches what the data service returned.

There is a problem with the model.
Your JSON object has a property named `createdUTC` with type `string`, but your model says it's a `Date`.

**Comment by TrentonAdams** [comment]
@trotyl Are your insults intended to imply that this problem is not fixable within angular?  And if so, is the issue fixable at all?  And if so, why is not fixable within angular?  

I made no statements that even remotely indicated that I thought TypeScript had runtime type information. But, for some reason you continue to imply that I thought that, and setup a straw man for me; sorry not biting. :D  Perhaps you could just speak about the issue, rather than insulting another's intelligence?

**Comment by mlc-mlapis** [comment]
@TrentonAdams ... there is no issue. TS is compiled to JS and JS doesn't have any interfaces in run-time so typing is just a thing for your dev time in editors and for compiling TS to JS.

The compilation doesn't add to JS any extra mechanism which would do some run-time processing from that point of view. It would be a very big performance bottleneck in run-time if you imagine how the returned JSON could be variable in the structure and sizing.

You can certainly add some of your own code (using the `map` operator for example) to check and correct incoming data. There are also other way but still it is on your responsibility for doing it. Generally the idea is to suppose that your server returns correct data and that preposition is checked by integration tests or some schema validation on the server side.

**Comment by trotyl** [comment]
@TrentonAdams Could you please elaborate what is my `insult`s? I haven't change any words except typo.

**Comment by TrentonAdams** [comment]
@trotyl It's possible I just read into what you were saying.  If that's the case, I apologize.

**Comment by darrenhollick** [comment]
@trotyl and @matthew-ch Thank you for your responses.  Forgive me if I missed what you're proposing should be done.  You both implied that the model doesn't match the JSON but as far as I know it matches it as best it can.  Is there any other way to represent a date in JSON? (as far as I know there isn't)  Suppose that Model is shared in the projects between the client and server.  When the server creates the SimplePerson object to send to the client createdUTC is an actual javascript date.  Being transferred accross the internet as JSON serialized the object and now we can't tell the difference between a string and a date.. EXCEPT that since we have the type information we can.

Are you suggesting that any model that could ever be serialized should never have a Date type in it?

**Comment by trotyl** [comment]
@darrenhollick You can add some metadata during the serialization and provide an `HttpInterceptor` to preprocess it, like:

```json
{
    "$rtti": { "createdUTC": "Date" },
    "id": 1234,
    "name": "Testy Testerson",
    "createdUTC": "2018-07-12T16:00:00Z"
}
```

With:

```typescript
class DeserializeInterceptor implements HttpInterceptor {
  intercept(req: HttpRequest<any>, next: HttpHandler): Observable<HttpEvent<any>> {
    return next.handle(req)
      .filter(event => event instanceof HttpResponse)
      .map(res => {
        if (res.body && typeof(res.body) === 'object' && res.body.hasOwnProperty('$rtti')) {
          const definition = res.$rtti
          for (const [prop, type] of Object.entries()) {
            switch (type) {
              case 'Date':
                res.body[prop] = new Date(res.body[prop])
              // ...
            }
          }
        }
        return res.body
      })
  }
}
```

This is just an informative demo, and better to have an backend serialization process that adds that meta property automatically.

**Comment by darrenhollick** [comment]
@trotyl I get what you're saying and I just did some tests and I got something along these lines working.  I personally think that it would be amazing for Angular to handle this... but what do I know :-)

**Comment by iamwyza** [comment]
While I agree it'd be nice for it to handle it. I'd just be happy with the help docs not implying that it *is* handling it, when it isn't.

**Comment by SzabKel** [comment]
Easiest way to get around this is declaring the input format in your model as you see in your Json and then use a Pipe to transform the data.
For example, I converted my dates from string (Java Spring returns the dates using Jackson from OffsetDateTime objects) to Date objects:
```
@Pipe({name: 'toDate'})
export class StringToDatePipe implements PipeTransform {
  transform(value: string): Date {
    if (value) {
      return new Date(value);
    }
  }
}
```

When I use them: `{{ dataItem.createdAt | toDate }}`

**Comment by jarrettj** [comment]
Hi,

Thanks for this post, saved me a couple of hours. As an angular/nodejs newbie I assumed the same thing. In my .subscribe() function I merely did type checking of the data sent from server, if that helps anyone. Would be nice if it were in the angular TOH as well that the types are not enforced not converted. :)

Regards.

**Comment by timothyBrake** [comment]
Still no HttpClient auto-converting JSON to the actual TypeScript class. There is absolutely NO excuse that Angular hasn't provided this obvious professional feature yet. This has been implemented for YEARS in Java frameworks and as a reference see Java JAXB API and Jackson API and how it should be done. HttpClient should do ALL the magic and return the actual correct no matter how it is technically implemented or whatever excuse any developer can come up with. Make it happen Angular team.

**Comment by an-dr-eas-k** [comment]
My current solution for an array of Foo:
```
	getFoo(): Observable<Foo[]> {
		return this
			.http
			.get<Foo[]>("/url")
			.pipe(map(a => a.map(e => Object.assign(new Foo(), e))));
	}
```
Now I can use extension methods implemented for Foo.

**Comment by AlexDEVpro** [comment]
Correct me if I am wrong. It turns out that the typed methods from HttpClient work with the specified interface as an interface. But when specifying a class, it also works with it as an interface?
