### ISSUE TITLE
ci: pin all dependencies, have process to regularly upgrade them

### ISSUE THREAD

**Issue by gkalpak** [angular/angular#20860]
As discussed with @IgorMinar, in order to avoid random breakages on CI, we should eventually pin all dependencies that may affect the outcome of tests and CI builds.
In order to also ensure that we are testing against latest versions in our supported ranges (and catch any dependency regressions early), we should have a process (preferrably automated) to regularly (daily?) upgrade all such dependencies.

Action items (in random order):

- [ ] Document all currently unpinned dependencies in `docs/dependencies.md`.
       Currently known places where we use unpinned dependencies:
         - All aio examples e2e tests (in `aio/`).
         - Some integration tests (in `integration/`).
- [ ] Document the process of upgrading them.
- [ ] Pin them.
- [ ] Gather all hardcoded versions in as few places as possible (e.g. `yarn.lock`, `env.sh`) to make it easier to upgrade.
- [ ] Come up with a process to upgrade them.
- [ ] Automate the upgrade process.

**Comment by IgorMinar** [comment]
@alexeagle already started experimenting with renovate on angular/tsickle as a pilot for angular/angular.

**Comment by alexeagle** [comment]
We are ready to do this now, @rarkins wrote up a special on-boarding doc just for us 🌹  https://docs.google.com/document/d/1V-F4-VVVf4ZmjRE0nvjS5pQ2Q5FMKfyx0wIsatDSxd4/edit

@IgorMinar we just need to find some time

**Comment by alexeagle** [comment]
Just discussed in person with @ocombe and @IgorMinar 

We would like to start with renovate to solve the multi-repo CI problem, in a specific and limited capacity for angular/angular.

- In each `integration/*` folder in this repo, we'll have two package.json files (and two WORKSPACE files for bazel examples). One will be against latest snapshots of dependencies, the other will be latest release of dependencies (will probably start with one integration/foo folder to start)
- We'll configure renovate to update the two package.json files (and two WORKSPACE files) - probably only updating particular whitelisted deps we care about (projects under our own control)
- We don't need renovate to auto-merge on green because we'll set up our own bot to do that (we want non-renovate PRs to also auto-merge on green)
- We'll change the integration test runner so that it kicks off the test N times, once for each package.json file.

This basically gives us a test matrix of {integration scenario} x {released_deps, snapshot_deps}. User PRs against Angular will be red if they don't work with both kinds of deps, and Renovate PRs will be red if the deps broke any angular code.

**Comment by rarkins** [comment]
> One will be against latest snapshots of dependencies

Do I understand this flow correctly?

- New code lands on `angular/angular` master
- A snapshot build is pushed to `angular/core-builds`
- Renovate should submit a PR back to `angular/angular` updating the integrations `package.json` to point to the new commit?

And how exactly would it specify the "latest snaphot"? I notice that `angular/core-builds` seems to have both branches and tags, so I'm not sure I know what naming/tagging convention you have in use.

> We'll change the integration test runner so that it kicks off the test N times, once for each package.json file.

The package.json files will be within separate subdirectories within that particular "integration" folder?

**Comment by jelbourn** [comment]
@josephperrott is this still relevant?

**Comment by josephperrott** [comment]
Yes, the specifics have likely changed a bit, but the spirit is definitely still there.  It is a large enough effort that we likely should have it proposed and go through our backlog process.

**Comment by josephperrott** [comment]
This has been obtained with our renovate based update process.
