### ISSUE TITLE
FormGroup value does not changed when specified updateOn blur with child component

### ISSUE THREAD

**Issue by goto63** [angular/angular#20881]
## I'm submitting a...
<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior
FormGroup value does not changed when specified updateOn blur with child component. it will be change correctly, If do not use upateOn blur.

## Expected behavior
I think FormGroup value should be changed When using child component and UpdateOn blur are combined.

## Minimal reproduction of the problem with instructions
code: https://stackblitz.com/edit/angular-qx9tgq?file=app%2Fapp.component.ts

## What is the motivation / use case for changing the behavior?
When developing a screen, develop it separately into components. Therefore, I think it would be nice to cooperate with updateOn blur.

## Environment

<pre><code>
Angular version: 5.1.0

Browser:
- [x] Chrome (desktop) version 62.0.3202.94
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: v6.11.2
- Platform:  Mac

Others:

**Comment by kara** [comment]
The `updateOn: blur` feature works based off of the `registerOnTouched` method, which is a required method to properly implement `ControlValueAccessor`. It's your CVA's job to tell the forms API when the control has been touched/blurred so it knows to update the value/validation pipeline.  In your example, the `registerOnTouched`functionality hasn't been hooked up, which is why it's not working properly.  If you call the method on blur, it should work as you expect: https://stackblitz.com/edit/angular-frdeo1?file=app%2Fchild.component.ts
