### ISSUE TITLE
Angular binding problem (re open)

### ISSUE THREAD

**Issue by Zerokk** [angular/angular#20894]
Check this previous isssue: https://github.com/angular/angular/issues/20776

Everything was explained there, but the issue was closed for no reason. This far, after many research, I'm pretty sure that this is some kind of Angular core problem which we may have not realized before. And this is a serious thing, because this is a serious trouble in a serious, production application. I would like to get some insights on why my app is breaking when a third-party component uses JQuery for something...

Currently, I substituted the datepicker for one that doesn't us JQuery. Ok, fine. But now that I start to use Highcharts, this library uses JQuery for some purposes (not even a lot tho), so my modal component starts breaking again. 

Why does this happen?

**Comment by jasonaden** [comment]
@Zerokk I would suggest putting this question up on StackOverflow. If this is a commonly used date picker, I'm sure someone else has run into this same issue and StackOverflow is the right place to ask those questions.

It sounds more like you have an issue of interrop between many different libraries and UI components rather than an issue directly with Angular. There are many people out there using jQuery and Angular successfully together, so for your specific use case I think it's best to ask the community for help.

If you would like to file a new issue here, you may go ahead. But please review [our submission guidelines](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-submitting-an-issue) to understand why we can't act on issues that are lacking important information.

To give an isolated reproduction of the issue, we suggest using [StackBlitz](https://stackblitz.com/fork/angular-gitter), [Plunker](http://plnkr.co/edit/tpl:AvJOMERrnz94ekVua0u5?p=catalogue) or [Github](https://github.com/new). If you create this repro, please make an isolated use case rather than a whole application as this will help determine what the issue might be.

If this issue persists, please create a reproduction using one of the links above. Describe the difference between the expected and current behavior in a new issue with the reproduction linked.
