### ISSUE TITLE
Angular is running my-app more than once

### ISSUE THREAD

**Issue by supermoon123** [angular/angular#20971]
[ x ] Bug report  

Plunkr Case (Bug Reports)
https://plnkr.co/edit/wTnxEeG50tjW4OD2WAWk?p=preview

## Current behavior
Angular is running my-app **(4)** times instead of **(1)** time

## Expected behavior
Angular should only launch the app one time

## Minimal reproduction of the problem with instructions
https://plnkr.co/edit/wTnxEeG50tjW4OD2WAWk?p=preview

1.) Run Plnkr project in Chrome
2.) Chrome console log shows the app is running 4 times it should only run 1 time

![image](https://user-images.githubusercontent.com/13890896/33912627-ad0b60fa-df64-11e7-8291-9059c353b5d1.png)

## What is the motivation / use case for changing the behavior?
CPU usage and performance issues

## Environment
Angular Version:  5.1

Browser:
- [ x  ] Chrome (desktop)

**Comment by robwormald** [comment]
Not quite. 

Angular is creating your component once - what you're seeing is *change detection* running multiple times (in this case, two change detection runs, with two additional because of dev mode)

Angular basically diffs your data on each pass - when you bind to a function, eg ` {{ doStuff() }} ` - Angular *must* execute that function to know if the result has changed - which is why you're seeing that log.

In general, you should avoid binding to methods for this exact reason - running change detection should have no side effects - it shouldn't cause work to happen, it should just reflect existing state - it's inefficient to execute those functions on every pass.

**Comment by supermoon123** [comment]
Thank you for clarification of the log reporting the functions running 4 times vs 1 time. 

You mentioned binding function  {{ doStuff() }}  should be avoided.  but to run change detection should have no side effect.  I have look through several documentation on how not to bind a function. How can we run a function without binding it, We are having high cpu usage on our application when running through functions and or variables. with the angular framework
