### ISSUE TITLE
aio heading flashes during page transitions

### ISSUE THREAD

**Issue by IgorMinar** [angular/angular#20996]
I'm not sure what introduced this but as of recently (last day?) I noticed the following flashing/transition when loading the aio homepage:
![aio-home-flash](https://user-images.githubusercontent.com/216296/33968404-8ed0cdba-e01c-11e7-9a9b-25ebf0aaf6f5.gif)

as well as when transitioning between pages:

![aio-home-flash-2](https://user-images.githubusercontent.com/216296/33968410-930c9058-e01c-11e7-9946-98baf6eb28fb.gif)

The problem is especially visible when navigating from Resources to Docs:
![aio-home-flash-3](https://user-images.githubusercontent.com/216296/33968413-97822f3a-e01c-11e7-94ba-ef515e65b700.gif)

**Comment by gkalpak** [comment]
The first image is due to the fade-in animation in combination with that fact that on Home page the topbar is transparent.

The second image is due to the fade-in/out animations between pages (and works as expected). Note that it is not the topbar that "flashes", but the document's header).

The third image is due to incorrectly coordinating the sidenav animation with the transition between pages.
