### ISSUE TITLE
Feature request: Consider adding renovate to pin and track dependencies

### ISSUE THREAD

**Issue by Urigo** [angular/angular#21023]
After a successful addition to the [Angular Bazel example](https://github.com/alexeagle/angular-bazel-example/issues/17), I believe maybe we can talk about using the same tool for both the Angular monorepo itself and for all Angular users.

1. Angular monorepo:  The Angular monorepo itself has many dependencies scattered around the monorepo and I wonder how you keep track that everything works with the latest versions of all dependencies.
Also, inside Google you are always getting the latest master from internal dependencies but how are you aware when there is a new version of a dependency from outside Google?

2. Angular CLI:  I believe adding Renovate to the Angular CLI will help Angular users get the same benefits in their own app and also give the whole Angular community better and earlier understanding of changes from outside libraries, bugs and breaking changes they might have.

@alexeagle would love to hear your thoughts about your experience and the two use cases above?

cc @rarkins

**Comment by rarkins** [comment]
Renovate now supports maintaining `git_repository` and `http_archive` references in bazel `WORKSPACE` files too, thanks to @alexeagle's suggestion. Therefore references like https://github.com/angular/angular/blob/b89e7c2cb76e8fe6bcd0b8b2293ca8eee308679a/WORKSPACE#L45-L49 could be kept up-to-date via Pull Requests too.

**Comment by alexeagle** [comment]
Internally at google, we have a single version policy. You want to upgrade the version of underscore? Congratulations, you get to fix every broken build and test in the entire monorepo. So in practice we don't do this often, when we do it's because someone really needs a new feature or bugfix, and even then they have the option of patching our local fork.

Angular's userbase is where I'd consider this first. You get wide impact and I agree that CLI could help - in fact the CLI team is thinking about a different specific case, where the CLI helps you upgrade Angular itself.

It would be great to keep Angular's dependencies up-to-date. My main concern here is we have limited resources to run CI (we have a ton of testing and already many PRs) and no way to give lower QOS to a bot like Renovate.

**Comment by alexeagle** [comment]
I should add, the next place I'd like to use this is in https://github.com/angular/tsickle which is a nice small-scale testbed for the Angular team to get more experience, and where I'd like to keep the bazel rules up-to-date automatically. It's one of my main three downstream users that I need to keep green.

We'll need the new feature of sourcing the PRs from a different fork, so that we don't have to grant write access to any repos in the angular org, per Google policy.

**Comment by rarkins** [comment]
I've started testing out the read-only version of the app on my fork of angular/tsickle. You can preview what you'd see here: https://github.com/renovate-tests/tsickle/pulls

**Comment by IgorMinar** [comment]
I'll close this in favor of #21023

**Comment by Urigo** [comment]
@IgorMinar I'm sorry but I think I'm confused, it says that you closed this issue in favor of the same issue itself?  maybe I'm just not familiar with the new system?

**Comment by Urigo** [comment]
Ohh you meant https://github.com/angular/angular/issues/20860
never mind!
