### ISSUE TITLE
Importing angular libraries and bootstrap is messy

### ISSUE THREAD

**Issue by alexeagle** [angular/angular#21048]
Based on the comment here:

https://github.com/alexeagle/angular-bazel-example/pull/36/files/2869bfcbf56f40d6cc8d9e9f72b8d7538188fa1a#diff-0ea22445d900db774c8deb00f4a4df55

to use Angular with Bazel, you have to have lists in your code which should really come from upstream somewhere:

- list a bunch of zone.js scripts in the right order - I think there should just be a single zone-testing.js in the zone.js distro so the user just loads that one bootstrap script
- list the angular umd bundles needed for devserver and another list needed for karma tests

**Comment by JiaLiPassion** [comment]
@alexeagle , I would like to try to build a single `zone-testing` bundle. I will study your sample first.

**Comment by alexeagle** [comment]
Note, it's really a zone-node-testing bundle, as there are different
scripts to patch vs in the browser.
Another solution could be to include a BUILD.bazel file, that would solve
this only for the Bazel use case.

**Comment by JiaLiPassion** [comment]
@alexeagle , thanks, I will learn how to do it and let you know the update.

**Comment by pshields** [comment]
I have had issues whenever I've tried to add bundles to this list. In order to import `BrowserAnimationsModule` from `@angular/animations` into my `AppModule`, I added the two animations bundles I thought were necessary, only to see the cryptical `Uncaught ReferenceError: ɵc is not defined` console error when viewing the app using the devserver.

I also ran into issues trying to add the `angularfire2` (for Angular Firebase integration) to the bundles list. Including those bundles caused a "Uncaught Error: Mismatched anonymous define() module" console error.

Neither error looked straightforward to troubleshoot, so I'm hoping there's a way to improve this aspect of development (manually curating the bundles list.)

**Comment by JiaLiPassion** [comment]
@alexeagle , I made a PR in `zone.js`, https://github.com/angular/zone.js/pull/982, please review whether the idea is correct or not.

And I loaded following `test` modules 

```javascript
import '../zone-spec/long-stack-trace';
import '../zone-spec/proxy';
import '../zone-spec/sync-test';
import '../jasmine/jasmine';
import '../zone-spec/async-test';
import '../zone-spec/fake-async-test'
```

compare to your commit, I added `fake-async-test` and `long-stack-trace`, are those 2 modules needed?

**Comment by alexeagle** [comment]
Thanks @JiaLiPassion I think this is sufficient to resolve the issue - the bit users need to duplicate now just looks like

```
ANGULAR_TESTING = [
    "node_modules/@angular/*/bundles/*-testing.umd.js",
    # We use AOT, so the compiler and the dynamic platform-browser should be
    # visible only in tests
    "node_modules/@angular/compiler/bundles/*.umd.js",
    "node_modules/@angular/platform-browser-dynamic/bundles/*.umd.js",
]

filegroup(
    name = "angular_bundles",
    srcs = glob(
        ["node_modules/@angular/*/bundles/*.umd.js"],
        exclude = ANGULAR_TESTING,
    ),
)

filegroup(
    name = "angular_test_bundles",
    testonly = 1,
    srcs = glob(ANGULAR_TESTING),
)
```
which could probably still be improved but I think this is good enough.
