### ISSUE TITLE
[core] ngStyle doesn't remove nulled styles in IE11

### ISSUE THREAD

**Issue by arkon** [angular/angular#21064]
## I'm submitting a...
<pre><code>
[x] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior
Styles set using `[ngStyle]` do not get removed when their values become null in Angular 5.0.0+ in IE11.

This could affect earlier versions of IE as well. It appears to work as expected in the latest versions of Chrome and Firefox.

```ts
@Component({
  selector: 'my-app',
  template: `
    <div [ngStyle]="getStyle()">Text</div>
    <button (click)="toggleStyle()">Toggle style {{styleToggle}}</button>
  `
})
export class App {
  styleToggle: boolean = false;
  
  toggleStyle() {
    this.styleToggle = !this.styleToggle;
  }
  
  getStyle() {
    let color = null;
    
    if (this.styleToggle) {
      color = 'red';
    }
    
    return {
      color: color
    };
  }
}
```

## Expected behavior
The `null`-ed style should be removed.

## Minimal reproduction of the problem with instructions
Plunker: https://plnkr.co/edit/kcCH48on1MT6xShkU9Va?p=preview

## What is the motivation / use case for changing the behavior?
Regression; works as expected in earlier versions such as Angular 4.4.6.

Related issue: https://github.com/arkon/ng-sidebar/issues/131

## Environment

<pre><code>
Angular version: >= 5.0.0

Browser:
- IE version 11
</code></pre>

**Comment by ericmartinezr** [comment]
That's weird, this was fixed long ago, see https://github.com/angular/angular/issues/7916. This must be a regression.

The form `[style.color]="color"` still works with `null`, but ngStyle doesn't. I would've thought that both gets treated the same say. Here's a [stackblitz](https://stackblitz.com/edit/angular-kq4y5u?file=app/app.component.ts).

cc @vicb

**Comment by ericmartinezr** [comment]
The problem seems to be here

https://github.com/angular/angular/blob/efd9c094567b4ed91e46482b0124ca327565d3fc/packages/common/src/directives/ng_style.ts#L68

That line calls this one

https://github.com/angular/angular/blob/0f5c70d563b6943623a5940036a52fe077ad3fac/packages/platform-browser/src/dom/dom_renderer.ts#L187

In that case is assigning `null` to the style which doesn't work in IE.

I think the `_setStyle`  function in the first snippet should check if `value` is null, and if that's the case it should call `removeStyle` where's the fix for the problem.

https://github.com/angular/angular/blob/0f5c70d563b6943623a5940036a52fe077ad3fac/packages/platform-browser/src/dom/dom_renderer.ts#L191-L199

Something like (nothing tested)

```typescript
// Alternative 1
if(value) {
   this._renderer.setStyle(...);
} else {
   this._renderer.removeStyle(....);
}

// Alternative 2
this._renderer.setStyle(this._ngEl.nativeElement, name, value == null ? '' : value);
```

Now I'm not sure where to check for this in the Renderer3, I don't see any implementation for it. I only found this [piece of code](https://github.com/angular/angular/blob/5a7bf367231e1250c19386b20151b2bbef91c4bd/packages/core/src/render3/instructions.ts#L732) but I didn't get much of it.

**Comment by vicb** [comment]
Thanks @ericmartinezr for the great analysis !
The first alternative seems the best.
