### ISSUE TITLE
angular.io not working with Safari Developer Preview due to Service Worker issues

### ISSUE THREAD

**Issue by IgorMinar** [angular/angular#21139]
I'm not sure if we can work around this, but safari DP currently throws:

```
NotSupportedError: Passing MessagePort objects to postMessage is not yet supported
```

https://twitter.com/bencharbonnier/status/943821903847936000

We should first verify that this issue is still present with #19795 changes. My guess is that the issue is in service-worker component but we should track the aio issue separately.

**Comment by IgorMinar** [comment]
If this is not resolved by the time Safari ships service workers, angular.io will stop working on iOS.

**Comment by CDDelta** [comment]
This is actually already planned to be fixed, most likely before service worker is shipped in stable. https://bugs.webkit.org/show_bug.cgi?id=178940

**Comment by benouat** [comment]
Just some updates:

On https://angular.io the error I get actually changed since I reported the problem to @IgorMinar that opened the issue

<img width="506" alt="image" src="https://user-images.githubusercontent.com/1152740/34674094-e601e386-f484-11e7-8ef0-02ab656ce95b.png">

Testing on Safari DP Release 46 (Safari 11.1, WebKit 12605.1.18.2)

But on https://next.angular.io/ I still get the old one `NotSupportedError: Passing MessagePort objects to postMessage is not yet supported`

**Comment by gkalpak** [comment]
I assume this has been fixed, since the corresponding WebKit issue has been closed as _fixed_.
