### ISSUE TITLE
ngForm submit using enter keypress and multiple buttons

### ISSUE THREAD

**Issue by Gbacc** [angular/angular#21153]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior

When submitting a form containing 2 buttons using the "enter" keyboard button, the form is calling the 2 buttons "click" actions, even disabled or non type="submit" buttons.
It does not happen when having only 1 button, everything seems fine.

## Expected behavior

If the form is not valid it should not call anything.
The form should not call any other button then enabled type="submit" button.

## Minimal reproduction of the problem with instructions

Here is a plnkr : https://plnkr.co/edit/6KyMeICSbBluh3pnfDGZ?p=preview

## Environment

<pre><code>
Angular version: 5.1.2

Browser:
- [X] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: XX  
- Platform:  

Others:

</code></pre>

**Comment by kara** [comment]
It's [default HTML behavior](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/button) that buttons without a type are treated as "type: submit".  Submit buttons trigger synthetic click events on form submit by design, so this is expected.

Similarly, Angular doesn't prevent forms from submitting when invalid like AngularJS because `novalidate` is added automatically. You can override this behavior with `ngNativeValidate`. See more about this [here](https://github.com/angular/angular/issues/16481#issuecomment-300610623).
