### ISSUE TITLE
Child Routing for lazy loaded modules does not work as expected.

### ISSUE THREAD

**Issue by SrikanthP0893** [angular/angular#21181]
## I'm submitting a...

<pre><code>
[ ] Bug report 
</code></pre>

## Current behavior

Hi, we have a few lazy-loading modules and router's configured like below in:

app-router.module.ts

<pre><code>
import { NgModule } from '@angular/core';
import { RouterModule, Routes } from '@angular/router';
import { LoginComponent } from './auth/login/login.component';

const routes: Routes = [
    {path: '',redirectTo:'auth',pathMatch:'full'},
    { 
        path: 'auth',
        loadChildren: './auth/auth.module#AuthModule'
    },
    {
        path: '',
        canActivate:[AuthGaurdService],
        children: [
            { path: 'admin', loadChildren: './admin/admin.module#AdminModule' },
            { path: 'student', loadChildren: './student/student.module#StudentModule' }
        ]
    },
    { path: '**', redirectTo: 'auth' }
];
@NgModule({
    imports: [RouterModule.forRoot(routes)],
    exports: [RouterModule]
})
export class AppRoutingModule {}
</code></pre>

in auth-router.module.ts  have code like below:
<pre><code>
import { NgModule } from '@angular/core';
import { RouterModule, Routes } from '@angular/router';
import { LoginComponent } from './login/login.component';
import { ConfirmEmailComponent } from './confirm-email/confirm-email.component';
import { DashboardComponent } from './dashboard/dashboard.component';

const authRoutes: Routes = [
    { path: '',component:DashboardComponent,
        children:[
            { path: '', component: LoginComponent},
            { path: 'confirm', component: ConfirmEmailComponent},
        ]
    }
];

@NgModule({
    imports: [
        RouterModule.forChild(authRoutes)
    ],
    exports: [RouterModule]
})
export class AuthRoutingModule {}
</code></pre>

## Current behavior
Now if I go to http://localhost:4200 or http://localhost:4200/auth it is perfectly loading the LoginComponent. But if I want to load ConfirmEmailComponent by accessing the URL http://localhost:4200/auth/confirm it is redirecting to http://localhost:4200/auth

## Expected behavior
If I access http://localhost:4200/auth/confirm it should load the ConfirmLoginComponent.

## Environment

<pre><code>
Angular version:5.1.0

Browser:
- [ ] Chrome (desktop) version XX
- [ ] Firefox version XX
 
For Tooling issues:
- Node version:  v6.10.3
- Platform:  Windows
</code></pre>

**Comment by jasonaden** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).

<hr>

You could probably take this exact issue to StackOverflow and get a quick answer. If there's an actual bug here, please create a small, isolated reproduction of the problem and create a new issue. If you need to do so, use [StackBlitz](http://stackblitz.com) so it's easier for us to download and replicate.
