### ISSUE TITLE
Typescript error with HttpClient

### ISSUE THREAD

**Issue by philippfo9** [angular/angular#21220]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x ] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior

StackBlitz from the bug:
https://stackblitz.com/edit/angular-gitter-zzqh3o

You can see it in app/http.service.ts

I've discovered a bug.
With the new HttpClient, you can get full response only if you use in the options {observe: ‘response’}. That’s ok and works good. But if you want to build your application, I get a typescript error, because typescript doesn’t know that it gets a full response and can’t find the property status on the response. 

I’ve written a HttpService my own, which handles many things and one function named getOptions which return the options object dynamically and therefore typescript doesn’t know what comes back from the http method. So I can’t build my app anymore and I’m not up to insert everywhere statically. (which didn’t work either for me). For different status codes, I have different things to do.
I hope, someone can help me or one man of the Ionic team sees it.
And yes, I know it’s basically an angular problem.

## Expected behavior

No typescript error.

## Minimal reproduction of the problem with instructions

Just use the HttpClient (basic method like get), generate the options via a function (with observe: 'response'), and try to access status on the response and build your app.

## What is the motivation / use case for changing the behavior?

It will work then.

## Environment
MacOs

<pre><code>
Angular version: 5.1.1

Browser:
all
- [x] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: XX  
- Platform:  

Others:

</code></pre>

**Comment by Toxicable** [comment]
Can you make a code example?
Stack Blitz would be great, here's a template: https://stackblitz.com/fork/angular-gitter

**Comment by philippfo9** [comment]
I have made the code example on Stack Blitz.
https://stackblitz.com/edit/angular-gitter-zzqh3o
Here you can see, that I take the options from my getOptions function.
So typescript doesn't know that it returns the full response.

**Comment by alxhub** [comment]
Hello @philippfo9,

Due to the way you're passing `options` around in an untyped fashion, Typescript cannot infer which of the many signatures to `get` you intend to call, and so this code doesn't work.

The typical reason to have options computed elsewhere is you want to centralize construction of headers, parameters, etc. I recommend this approach:

* Keep `observe: 'response'` set at the time you call `http.get`, and use the object spread operator to mix in the other parameters.
* Keep the type of the other options `{}`, which tells Typescript you want to assert nothing about their structure. This helps the signatures match correctly:

In code that looks like this:

```javascript
getRequest(path, callback) {
    this.getOptions((options: {}) => {
      this.http.get<StandardResponse>(this.appConfig.apiEndpoint+path, {...options, observe: "response"}).subscribe((res) => {
```

I'm going to close this issue as the HTTP APIs rely on proper type information which is not being provided, so this isn't a bug, but let me know if this solution works for you.

**Comment by ddannenb** [comment]
SHOULD BE REPONED.  This is poor design and breaks the utility of TS.  There are very few cases where one can use the the various type signatures in real world and end up with just so many type casts  to <any> instead.  
Rename the request method each with different signature instead of all of the overloads. 
Simple example where the overload signature scheme causes an error ...

```
const execRequest$ =  () => {
            return this.httpClient.request(method, url, opts).pipe(
                map((res) => {
                    return res.body;
                }),
                catchError((err) => {
                    // TODO
                })
            );
        };
```

Yields TS error Property 'body' does not exist on type 'ArrayBuffer'
In which case opt.observe has been set to 'response' in the caller, amongst other of the options.
