### ISSUE TITLE
APP_INITIALIZER: rejected promise throws "Cannot read property 'ngOriginalError' of undefined"

### ISSUE THREAD

**Issue by SteveVanOpstal** [angular/angular#21252]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior
The following provider will cause Angular to throw an error.
``` TypeScript
const INIT_PROVIDER = {
  provide: APP_INITIALIZER,
  useFactory: initFactory,
  multi: true
};

function initFactory() {
  return () => init();
}

function init() {
  return new Promise((resolve, reject) => {
    reject();
  });
}
```

The error occurs here: https://github.com/angular/angular/blob/0cc77b4a6954e563b6eb7999c9d3f08e2ba7dfeb/packages/core/src/errors.ts#L25-L27

`ERROR_ORIGINAL_ERROR` (`'ngOriginalError'`) doesn't exist on `error` at this point.

Related: https://github.com/angular/angular/issues/18523

## Expected behavior
The error should not occur. Unsure on what should happen in case the `Promise` is rejected but logging an error and continue operating seems like a good solution.

## Minimal reproduction of the problem with instructions
https://stackblitz.com/edit/angular-gitter-p6cngp

Open up the console and following error will appear:
> Unhandled Promise rejection: Cannot read property 'ngOriginalError' of undefined

## Environment

<pre><code>
Angular version: 5.1.2

</code></pre>

**Comment by builtbyjay** [comment]
I'm also confused as how to handle a rejected promise in this case. Documentation regarding APP_INITIALIZER is not the best.

**Comment by MarkPieszak** [comment]
I believe (at least for the error above) is occurring because you passed an empty `reject()`.
If you pass something to it `reject('etc etc');`, the above error will go away, *but* the Application will still *not* bootstrap successfully.

Ideally when using `APP_INITIALIZER`, you want to have some sort of "backup" for when errors occur.  Let's say you called an API to get a JSON configuration that your application needs, in the `catch` try using `resolve({ /* basic app data */}` so that the application can start up (at least with some vague/basic data), you can attempt to fetch the correct data again later after bootstrapping. At least this way, you'll have the application starting up.

**Comment by StevenLiekens** [comment]
I definitely wouldn't want the app to continue starting when APP_INITIALIZER returns a rejected promise.

**Comment by mlc-mlapis** [comment]
@StevenLiekens ... promise rejection is a signal for your app to behave due to that situation ... like route to some component that will explain a user the situation and so ... that's why it is a controlled state.

**Comment by StevenLiekens** [comment]
The way I see it, apps should not start unless then can be initialized successfully. Is that unreasonable?

**Comment by mlc-mlapis** [comment]
@StevenLiekens ... but the formulation `initialized successfully` has a virtual sense ... what is it exactly? You can write code that uses positive / negative logic ... check many other conditions and there are many cases when both `resolve / reject` represent successful initialization in fact.

**Comment by StevenLiekens** [comment]
So how would you handle rejected promises? You can't return anything from an APP_INITIALIZER. How would you even know that it was rejected, let alone why?

**Comment by mlc-mlapis** [comment]
@StevenLiekens ... you know it here ...
```
export function appConfigServiceFactory(config: AppConfig): () => void {
	return () => config.load()
	.then(
		(status: ErrorResult) => {
			console.log('... APP_INITIALIZER resolve:', status);
			... // (status.errorcode = 0) or (....)
		},
		(status: ErrorResult) => {
			console.log('... APP_INITIALIZER reject:', status);
			... // (status.errorcode > 1000) or (status.errorcode < 0) or (...)
		}
	);
}
```

**Comment by StevenLiekens** [comment]
That then() runs while the app is still doing the app_initializer phase. That's not the right place and time for redirecting to an error page or executing retry logic.

**Comment by mlc-mlapis** [comment]
@StevenLiekens ... it was not meant to do it synchronously but emit something for later use when app is instantiating the main component. And also `APP_INITIALIZER` is `multi` so you can have more of them and you may need to decide on all their results if to continue and how and how to react to a user.

**Comment by StevenLiekens** [comment]
What you're describing sounds like a lot of custom code. Angular doesn't provide anything that could help us out with that.
I really don't want ignoring rejected promises to become the default behavior without better framework support for handling rejections.

**Comment by mlc-mlapis** [comment]
@StevenLiekens ... yep, agree. Both `resolve / reject` as `multi` providers could be saw somehow similar to `validators` on top of the whole app and have them accessible via DI to any other place ... so it can react accordingly then?

**Comment by thw0rted** [comment]
Did this get anywhere?  There's two problems here, the way I see it, and one meta-problem. First, APP_INITIALIZER isn't handling rejection of promises returned by the factory.  Second, rx is observing a promise and barfing an unhelpful stackdump when it rejects with no argument.

Of course, the meta-problem is that APP_INITIALIZER is [very poorly documented](https://angular.io/api/core/APP_INITIALIZER) so we don't know how to expect our returned promise to be treated.  What argument should I resolve with? Can I reject? What will happen to the argument I reject with, if that's acceptable?  None of this is documented anywhere.

**Comment by hevans90** [comment]
This needs more attention - should we even be using `APP_INITIALIZER` in its current state?

**Comment by BruneXX** [comment]
Hi guys, is there any update on this? will be great if you can expand the APP_INITIALIZER documentation.

**Comment by BruneXX** [comment]
NOTE: this issue is still happening when reject the promise using APP_INITIALIZER, I'm using **Angular 8.x** I think you guys (angular team) should take a look at this.. Since this issue posted by @SteveVanOpstal is related angular 5.1.2 a very old version.

**Comment by Totati** [comment]
@BruneXX put .catch() at the end of your promise. It will hide the error for you.

**Comment by thw0rted** [comment]
I found it!

[This StackOverflow answer](https://stackoverflow.com/a/56021193/26286) suggests handling the promise returned by `platformBrowserDynamic().bootstrapModule(AppModule)`.  I never really looked at this method previously because it's kind of part of the starter-project boilerplate that everybody inherits.  It turns out that `bootstrapModule` returns a promise that resolves after application startup *or rejects if startup fails*, including if `APP_INITIALIZER` fails asynchronously.  Handle that promise and you can gracefully fail when APP_INITIALIZER rejects.

**Comment by Totati** [comment]
> I found it!
> 
> [This StackOverflow answer](https://stackoverflow.com/a/56021193/26286) suggests handling the promise returned by `platformBrowserDynamic().bootstrapModule(AppModule)`. I never really looked at this method previously because it's kind of part of the starter-project boilerplate that everybody inherits. It turns out that `bootstrapModule` returns a promise that resolves after application startup _or rejects if startup fails_, including if `APP_INITIALIZER` fails asynchronously. Handle that promise and you can gracefully fail when APP_INITIALIZER rejects.

So, you disliked my answer and said the same. Nice 👎

**Comment by thw0rted** [comment]
Sorry Totati, in your comment I thought you meant to put a `catch` on the Promise that's passed out of the `APP_INITIALIZER` factory.  In other words, make sure your initializer promise never actually rejects, so that the error in the OP can be avoided.  I don't find that advice helpful because I *want* my initializer to fail spectacularly if it can't complete -- in that case, the app can't work at all.  Maybe that's not what you intended? 

I posted about `bootstrapModule` because I only just learned about how it works today.  Now, I can take action based on whether my app initializes successfully or not.  You're right that it does involve "a catch at the end of your promise", but it's a promise that has not been mentioned elsewhere in this issue.
