### ISSUE TITLE
It looks like angular.io may no longer be indexing

### ISSUE THREAD

**Issue by StephenFluin** [angular/angular#21272]
## I'm submitting a...

<pre><code>
[X] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior
Angular.io pages are not included or previewed in the google search index.

https://www.google.com/search?q=Angular+Language+Service+site%3Aangular.io&oq=Angular+Language+Service+site%3Aangular.io

## Expected behavior
Angular.io pages are included and previewed in the google search index.

## Minimal reproduction of the problem with instructions
Visit https://www.google.com/search?q=Angular+Language+Service+site%3Aangular.io

I've also noted this on several other sites, so it may be something on the Angular side of things.

https://www.google.com/search?q=site%3Afluin.io

## Environment

<pre><code>
Angular version: 5.x.x
</code></pre>

**Comment by IgorMinar** [comment]
I checked webmaster tools and here is what I see:

On the surface there doesn't *seem* to be any problem - the number of documents hosted on angular.io that are in the index is about the same as before.

When I however try to fetch the language service doc as the google bot, the rendering fails with error:
 `[DocViewer]: Error preparing document 'guide/language-service'.` and empty document viewer:

<img width="1386" alt="screen shot 2018-01-03 at 12 27 26 am" src="https://user-images.githubusercontent.com/216296/34513685-4789e934-f01e-11e7-866c-a295f78e7cc7.png">

There is no more info about what went wrong.

It's as if the request to fetch the json doc failed, but in that case, we usually render a "network error" page, but that is not happening here. I tried several other urls and most of them suffer from this issue (which would explain the low quality search results).

Example urls that don't render in Google bot:

- https://angular.io/guide/language-service
- https://angular.io/guide/security
- https://angular.io/guide/architecture
- https://angular.io/api/animations/group
- https://angular.io/guide/quickstart

Example urls that do render in Google bot:

- https://angular.io
- https://angular.io/events
- https://angular.io/api
- https://angular.io/resources
- https://angular.io/docs
- https://angular.io/features
- https://angular.io/about?group=Angular

The only thing that pages that do vs do not work have in common is the number of path segments in the url. Single path segment seems to work, multiple don't work. I don't know if this is just a coincidence or not.

Just to be clear: all of these urls were indexable in the past, so something in aio or in google bot must have changed to cause this regression.

@StephenFluin's repro also surfaced two related issues that we should also address:
- next.angular.io is being indexed, when it shouldn't be (similarly v2.angular.io and v4.angular.io should not be indexed)
- the 404 pages for some old urls for the previous angular.io site are being indexed as regular documents (we should setup redirects for these + ensure that bogus urls that render as 404 do not end up in the index)

**Comment by IgorMinar** [comment]
I was thinking that maybe the change that introduced lazy-loaded components could be responsible for this, but `/api` page indexes just fine and it does use a lazy-loaded component as far as I know.

**Comment by arjunyel** [comment]
Would potentially using Rendertron be a good fix for the Googlebot? https://angularfirebase.com/lessons/seo-angular-part-1-rendertron-meta-tags/

**Comment by IgorMinar** [comment]
@arjunyel angular.io is our proving ground for ensuring that Angular apps work well out of the box, so we want to avoid setting up custom infrastructure to make SEO work.

**Comment by IgorMinar** [comment]
Once we fix this we should change our error logging setup to send errors to some external storage when google bot is crawling the site. General instructions can be found here: https://developers.google.com/search/docs/guides/debug-rendering

**Comment by IgorMinar** [comment]
ok @gkalpak's PR is now in and we have more info about the problem. Here is what I got:

```
[DocViewer] Error preparing document 'guide/quickstart': TypeError: Cannot read property 'toLowerCase' of undefined at https://angular.io/0.f2591f718907b6ae5a8f.chunk.js:1:196 at Array.forEach (native) at l (https://angular.io/0.f2591f718907b6ae5a8f.chunk.js:1:158) at r (https://angular.io/0.f2591f718907b6ae5a8f.chunk.js:1:484) at new t (https://angular.io/0.f2591f718907b6ae5a8f.chunk.js:1:31662) at Ke (https://angular.io/main.bec31ad514fe5bf71717.bundle.js:1:83560) at qe (https://angular.io/main.bec31ad514fe5bf71717.bundle.js:1:82013) at In (https://angular.io/main.bec31ad514fe5bf71717.bundle.js:1:96674) at xn (https://angular.io/main.bec31ad514fe5bf71717.bundle.js:1:95462) at Object.Gn [as createRootView] (https://angular.io/main.bec31ad514fe5bf71717.bundle.js:1:102128)
```

**Comment by IgorMinar** [comment]
This stacktrace maps back to: 

https://github.com/angular/angular/blob/cdc66f616467e8623e04b49c2a029ba207a073bd/aio/src/app/shared/attribute-utils.ts#L6-L17

Specifically line:

https://github.com/angular/angular/blob/cdc66f616467e8623e04b49c2a029ba207a073bd/aio/src/app/shared/attribute-utils.ts#L15

**Comment by IgorMinar** [comment]
And this path gets invoked when we try to instantiate an embedded component with attributes like:

https://github.com/angular/angular/blob/cdc66f616467e8623e04b49c2a029ba207a073bd/aio/content/guide/security.md#L101-L103

**Comment by IgorMinar** [comment]
I debugged this more and found the root cause of the problem. When google bot evaluates:

```
 Object.keys(attrs)
```

for 

```
<code-example path="security/src/app/inner-html-binding.component.html"></code-example>
```

We get an array of `['0', 'length']` while in evergreen browsers we get just `['0']`.

When we then try to find the attribute with name `length` we get undefined and the rest of the code then fails.

**Comment by IgorMinar** [comment]
I have a fix https://github.com/angular/angular/pull/21305

**Comment by IgorMinar** [comment]
The fix is now in production:

<img width="1173" alt="screen shot 2018-01-04 at 1 18 43 pm" src="https://user-images.githubusercontent.com/216296/34584776-f38ef948-f151-11e7-8ff7-5a050c4f41c0.png">

I requested the reindexing of the site via webmaster tools

**Comment by IgorMinar** [comment]
we are back to normal: https://www.google.com/search?q=language+service+site%3Aangular.io

<img width="849" alt="screen shot 2018-01-05 at 3 16 25 pm" src="https://user-images.githubusercontent.com/216296/34632628-703fb4c6-f22b-11e7-8d3c-5f0589cf3214.png">

**Comment by IgorMinar** [comment]
I'm doing a bit more of post-mortem on this and what's odd is that the problematic code has been around since forever (and I'm quite certain that it's been in the execution path since the same time):

https://github.com/angular/angular/blame/cdc66f616467e8623e04b49c2a029ba207a073bd/aio/src/app/shared/attribute-utils.ts#L14-L15

<img width="1874" alt="screen shot 2018-01-06 at 9 47 24 am" src="https://user-images.githubusercontent.com/216296/34642372-d66a4b58-f2c6-11e7-9661-c859a10728e5.png">

But the search traffic was affected only in mid December:

<img width="1649" alt="screen shot 2018-01-06 at 9 49 41 am" src="https://user-images.githubusercontent.com/216296/34642378-f7611490-f2c6-11e7-99bf-29439f5140c3.png">

Now one could argue that the traffic hit sue due to holiday season, but in that case the slump should start later and be less abrupt. So I analyzed the google analytics data and noticed that we saw similar looking curve for over number of sessions at angular.io:

<img width="1592" alt="screen shot 2018-01-06 at 9 52 47 am" src="https://user-images.githubusercontent.com/216296/34642496-c8f49576-f2c8-11e7-9fc1-418eda976f62.png">

If we look at the breakdown of traffic sources we'll see that the top 3 sources are organic search, referrals (links from other sites), and direct traffic (people clicking on bookmarks or typing angular.io into the browsers):

<img width="693" alt="screen shot 2018-01-06 at 9 59 45 am" src="https://user-images.githubusercontent.com/216296/34642467-63ad6f62-f2c8-11e7-8fae-26333ba8967c.png">

As you can see the search traffic is the most important source of traffic contributing over 70% of all traffic. With such big contribution the search traffic alone can easily skew the overall session count curve.

So let's see what the curve looks like for for sessions originating from "organic search" alone:

<img width="1599" alt="screen shot 2018-01-06 at 9 56 57 am" src="https://user-images.githubusercontent.com/216296/34642485-bd5211da-f2c8-11e7-822c-6b9cd6feca02.png">

That's a similar looking curve!!

Now what about the curve for sessions acquired via referrals (links):

<img width="1595" alt="screen shot 2018-01-06 at 9 56 22 am" src="https://user-images.githubusercontent.com/216296/34642505-ebcddf08-f2c8-11e7-81e9-abdb8dfe3217.png">

That looks very different! With just a little bit of seasonality around holidays.

Now what about the directly acquired sessions:

<img width="1583" alt="screen shot 2018-01-06 at 9 56 39 am" src="https://user-images.githubusercontent.com/216296/34642513-075f94a0-f2c9-11e7-8d9e-365390def027.png">

That also looks quite normal, with just a bit of seasonality around holidays.

## Conclusion

Given that we haven't changed the problematic code in 8 months and that we experienced significant loss of traffic originating from search engines starting around December 11, 2017, I believe that something has changed in crawlers during this period of time which cased most of the site to be de-indexed, which then resulted in the traffic loss.

**Comment by MrCroft** [comment]
I just ran into the same problem.
While I didn't have any `Object.keys(obj).forEach()` in my test app, seeing your solution made me go into `polyfills.ts` and uncomment these 2 lines under `/** IE9, IE10 and IE11 requires all of the following polyfills. **/`:
```
import 'core-js/es6/object';
import 'core-js/es6/array';
```
Then, everything showed up fine in the Search Console (under both "how Google sees it" and "how a visitor sees it"), except one listing.
The only difference in that listing was that I was using the `index` in an `*ngIf`:
```
<div *ngIf="(favoriteVideos | async)?.items; let videos; else loading">
    <h1>Videos</h1>
    <div class="videos-listing">
        <mat-card *ngFor="let video of videos; index as i">
          <mat-card-content>
            <a [routerLink]="['/video', video.id, video.slug]">
              <img *ngIf="i < 6" [src]="video.image" [alt]="video.name" width="247" height="409">
              <img *ngIf="i >= 6" #lazyImage [attr.data-src]="video.image" [alt]="video.name" width="247" height="409">
            </a>
          </mat-card-content>

          <mat-card-footer>
            ...
          </mat-card-footer>
        </mat-card>
    </div>
</div>

<ng-template #loading>Loading Videos...</ng-template>
```
The content was showing up under "how Google bot sees it", but wasn't showing up under "how a visitor sees it"

Feeling crazy, I just tried replacing:
```
<img *ngIf="i < 6" [src]="video.image" [alt]="video.name" width="247" height="409">
<img *ngIf="i >= 6" #lazyImage [attr.data-src]="video.image" [alt]="video.name" width="247" height="409">
```
with:
```
<img [src]="video.image" [alt]="video.name" width="247" height="409">
```
And that did the trick. But I have no clue why? I mean, even before, I should at least see the first 6 videos under both "How Google bot sees it" and under "How a visitor sees it".

```
Angular: 5.2.7
```
