### ISSUE TITLE
Pristine/touched incorrect for test specs of template driven forms

### ISSUE THREAD

**Issue by camueller** [angular/angular#21285]
## I'm submitting a...
<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[X ] Bug report
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior
After entering values in a template driven form in a test spec the status of the form remains touched=false and pristine=true.

## Expected behavior
After entering values in a template driven form in a test spec the status of the form should change 
to touched=true and pristine=false.

## Minimal reproduction of the problem with instructions
http://plnkr.co/edit/05UZbeA9wkRRjRs1uBQq

## What is the motivation / use case for changing the behavior?
Evaluation of this pristine/touched is needed to check expected button states in test specs.

## Environment
<pre><code>
Angular version: 5.1.2

Browser:
- [X ] Chrome (desktop) version 63.0.3239.108
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: v8.9.3
- Platform:  Linux tpw520 4.4.0-104-generic #127-Ubuntu SMP Mon Dec 11 12:16:42 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux

</code></pre>

**Comment by kara** [comment]
A form control is only considered dirty if the *user* interacts with the UI somehow, and is not toggled by programmatic changes (see [docs](https://angular.io/api/forms/AbstractControl#pristine)). In your test, the value is changed programmatically, so this is expected behavior. 

You can fix your test by setting the value of the native element and dispatching the native event. See examples in our template driven forms spec here: https://github.com/angular/angular/blob/master/packages/forms/test/template_integration_spec.ts#L28
