### ISSUE TITLE
Why Can't `UserService` can't be injected into the `HeroService`?

### ISSUE THREAD

**Issue by spottedmahn** [angular/angular#21319]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Feature request
[X] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior
On [Angular DI -> Factory providers](https://angular.io/guide/dependency-injection#factory-providers), it says:

>Unlike `EvenBetterLogger`, you can't inject the `UserService` into the `HeroService`.

Why not?

## Expected behavior
Explain why `UserService` can't be injected into the `HeroService`

## What is the motivation / use case for changing the behavior?
To better understand Angular.

**Comment by jvquarck** [comment]
Maybe I'm wrong, but... technically you can, it's just that they are stating that the UserService won't be available from the HeroService, since you don't want the latter one to mangle with sensitive data (this is a common scenario), that is why since you need a flag from the UserService you will require this flag in the HeroService constructor, and from now on you will create new instances of this service with a provider, the factory function will have access to the UserService and will be able to pass the flag to the HeroService constructor. Did that make sense? (thoughtram dot io has some interesting posts about Angular DI that can shed more light)

Current explaination is:
>  The HeroService won't have direct access to the user information to decide who is authorized and who is not.

Maybe it would be simpler to understand with:
>  We don't want the HeroService to have direct access to the user information, otherwise it could decide who is authorized and who is not.

**Comment by kapunahelewong** [comment]
Regarding needing engineering input, can an engineer verify/elaborate on @jvquarck's explanation? I can edit the doc if needed.

**Comment by jbogarthyde** [comment]
This issue is addressed in a new rewrite of the entire DI guide that is currently in progress.

**Comment by spottedmahn** [comment]
that's great @jbogarthyde 👍!  I'll close this issue then...
