### ISSUE TITLE
Router Segments parsing error with =

### ISSUE THREAD

**Issue by thepian** [angular/angular#21381]
## I'm submitting a...
<pre><code>
[x ] Bug report  
</code></pre>

## Current behavior

If you set up a route to match the following example URL.

    https://test/info/password/de/MDAtMNTk=

The key passed will be `MDAtMNTk` without the equal sign.

## Expected behavior

The equals sign has no meaning in the path, it should only apply to parsing the query string. The
the value passed should be `MDAtMNTk=`.

## Minimal reproduction of the problem with instructions

You just need to add a test parsing an URL with an equal sign to trigger the issue.

      it('should pass the full path segment', () => {
        const t1 = serializer.parse('/password/de/MDAtMNTk=');
        const t2 = serializer.parse('/password/de/MDAtMNTk%3D');
        expect(containsTree(t1, t2, false)).toBe(false);
      });

## What is the motivation / use case for changing the behavior?

1) Putting base64 encoded strings in a URL is a common case.
2) Angular should support valid URLs

## Environment

<pre><code>
Angular version: 5.0.0

Browser:
- [x] Chrome (desktop) version XX

For Tooling issues:
- Node version: v8.0.0
- Platform:  Mac, Windows

</code></pre>

**Comment by jokecamp** [comment]
Looks like the segments get parsed in this method of url_tree.ts

`const SEGMENT_RE = /^[^\/()?;=&#]+/;
function matchSegments(str: string): string {
  const match = str.match(SEGMENT_RE);
  return match ? match[0] : '';
}`

Of course it won't be as simple as just removing the `=` from the regex. I'm not sure I know enough about all the url rule permutations to propose a fix.

**Comment by thepian** [comment]
I'm suspecting that this is a fundamental flaw in the implementation. It seems to use the same representation for incoming request URLs and URL routes configuration. I'll have to understand the codebase better with concepts such as segments and the like.

**Comment by raijitendra** [comment]
I am facing same issue when there is '=' symbol in path.
Is there any plan by when it will be addressed?

**Comment by zaheral** [comment]
Facing also the same issue with version 9.x.x
Created an example (check the comments): https://stackblitz.com/edit/angular-ivy-zhas4n?embed=1&file=src/app/app.ts

**Comment by TrevorKarjanis** [comment]
Having run into this issue, I investigated the validity of this syntax following a comment in the equivalent issue [31649](https://github.com/angular/angular/issues/31649#issuecomment-513484106), specifically whether the equals sign should be percent-encoded. Following the IETF [RFC 3986](https://tools.ietf.org/html/rfc3986) on the Uniform Resource Identifier (URI): Generic Syntax, the equals sign is a [reserved character](https://tools.ietf.org/html/rfc3986#section-2.2). However, these characters may not be, "defined as delimiters by the generic syntax, by each scheme-specific syntax, or by the implementation-specific syntax of a URI's dereferencing algorithm [...] If a reserved character is found in a URI component and no delimiting role is known for that character, then it must be interpreted as representing the data octet corresponding to that character's encoding in US-ASCII." [Section 3.3](https://tools.ietf.org/html/rfc3986#section-3.3) defines the forward slash "/" as the delimiter for the path component. It also states that reserved characters are often used in segments, "to delimit scheme-specific or dereference-handler-specific subcomponents.  For example, the semicolon (";") and equals ("=") reserved characters are often used to delimit parameters and parameter values applicable to that segment." I'm not sure if that implies equal signs can be reserved, because the HTTP scheme does not and its delimiting role is relative to the segment not the path. In either case though, reserved or data, a percent-decoded equals sign seems valid in the path component as per RFC 3986.

**Comment by shirkerohit** [comment]
Facing exact same issue, In my case the url has encrypted string appended and the last character generated is '=' however when angular is retrieving the parameter it is returning the string without equal sign!

Anyone else have any other solution? even tried base64 but unfortunately, it also generates the same character and it fails.

**Comment by gomezv9** [comment]
I have the same issue in Angular 12. Any solution ?

**Comment by gomezv9** [comment]
> ## I'm submitting a...
> ```
> 
> [x ] Bug report  
> ```
> 
> ## Current behavior
> If you set up a route to match the following example URL.
> 
> ```
> https://test/info/password/de/MDAtMNTk=
> ```
> 
> The key passed will be `MDAtMNTk` without the equal sign.
> 
> ## Expected behavior
> The equals sign has no meaning in the path, it should only apply to parsing the query string. The the value passed should be `MDAtMNTk=`.
> 
> ## Minimal reproduction of the problem with instructions
> You just need to add a test parsing an URL with an equal sign to trigger the issue.
> 
> ```
>   it('should pass the full path segment', () => {
>     const t1 = serializer.parse('/password/de/MDAtMNTk=');
>     const t2 = serializer.parse('/password/de/MDAtMNTk%3D');
>     expect(containsTree(t1, t2, false)).toBe(false);
>   });
> ```
> 
> ## What is the motivation / use case for changing the behavior?
> 1. Putting base64 encoded strings in a URL is a common case.
> 2. Angular should support valid URLs
> 
> ## Environment
> ```
> 
> Angular version: 5.0.0
> 
> Browser:
> - [x] Chrome (desktop) version XX
> 
> For Tooling issues:
> - Node version: v8.0.0
> - Platform:  Mac, Windows
> ```

I have the same issue in Angular 12. Did you find a solution ?

**Comment by darrenhollick** [comment]
This issue seems to still exist in Angular 13 as well.  Is there even a work around?

**Comment by amakhrov** [comment]
Another effect of this is that removing of the `=` sign happens after the matching has happened.
Example:
```
// router config
{
  path: "prefix/:slug",
  component: MyComponent
}
```
Opening a url `example.com/prefix/=` matches this route and renders MyComponent. However, inside the component ActivatedRoute has an empty (`""`) value for the `slug` parameter - which fails some runtime validation in our code and throws.

**Comment by ripper2hl** [comment]
Same problem if my URL ends with '=' query params are deleted to URL, 

Any workaround or solution without manipulation of the URL ?

**Comment by ripper2hl** [comment]
Same problem if my URL ends with '=' query params are deleted to URL,

Example:

Original URL:

www.example.com/hola=?one=1

Afert angular bug:

www.example.com/hola=

Any workaround or solution without manipulation of the URL ?

**Comment by DW8Reaper** [comment]
I signed up for “Become an open source contributor” at ng-conf next week and I will take a crack at this issue for my contribution. 

I noticed that the matchSegments call is used for segments and also for matrix parameters. The regex needs an = for matrix params but it does not for regular url segments.

(No promises it took me two evenings just to be able to build and test the angular repo so outlook grim?)
