### ISSUE TITLE
Fix our Travis configuration so caching doesn't hide failures

### ISSUE THREAD

**Issue by kara** [angular/angular#21397]
Last week, we had a payload size regression in CLI hello-world that wasn't immediately obvious because of caching. We need to figure out how to fix our setup to avoid problems with caching down the line.

cc @IgorMinar

**Comment by gkalpak** [comment]
Have we concluded that cache was indeed involved (and it was not a case of a new version getting released since last successful build)?

That would mean that yarn (when run without a lockfile) is happy to install an older cached version (that satisfies the range), even if a newer version (that satisfies the range) has been published (but is not yet cached). This is kind of unexpected (for me), but possible.
@IgorMinar, do you know if that is the case?

##
Anyway, if that is the case, one solution would be avoid using the yarn cache here:

https://github.com/angular/angular/blob/fa03ae14b0be19c2cb9d653b2b1d3cfa0ae25117/integration/ng-cli-create.sh#L63

(E.g. use something like `yarn install --emoji --cache-folder ../.yarn_local_cache`.)

**Comment by IgorMinar** [comment]
I was only told by Kara that blowing away the travis cache caused
previously green builds to fail. But you might be right that it might have
been just because of a release of some transitive unpinned dependency that
broke us.

**Comment by gkalpak** [comment]
This is now irrelevant, since the affected jobs have been moved to CircleCI (which handles caching differently) and the we do use a custom [cache folder for yarn][1]. Closing...

[1]: https://github.com/angular/angular/blob/dc300c5c4172e1f8a6f3f84da6797e427e3626c0/integration/run_tests.sh#L48
