### ISSUE TITLE
Mistake in Tutorial

### ISSUE THREAD

**Issue by jupie** [angular/angular#21408]
Hello, 

I try to learn angular yet. For this I try your Heroes Tutorial and I find a little mistake in it: 

https://angular.io/tutorial/toh-pt2

At the part displaying a list angular couldnt find the mock-hero Module. To fix this problem I wrote
`import {HEROES} from 'mock-heroes';` 
instead of this: 
`import {HEROES} from '../mock-heroes';`

to fix this problem.

**Comment by frederikprijck** [comment]
Hey @jupie ,

That's most likely because you didn't place the `heroes.component` inside a heroes folder.
If you look at the file paths, u'll c the following:

- src/app/heroes/heroes.component.ts 
- src/app/mock-heroes.ts

Now if u want to import the mock-heroes inside heroes.component, you do need to use `../mock-heroes`.
