### ISSUE TITLE
Better ViewChild support  for multiple instances of child component

### ISSUE THREAD

**Issue by danli-88** [angular/angular#21542]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[X] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior
When a parent component hosts multiple instances of the same child component type, it's unnecessarily difficult to obtain reference to a specific instance. The only way I'm aware of is with ViewChildren, so I have to traverse a list.

## Expected behavior
ViewChild should support directly addressing a component by some identifier, e.g. the view template reference.

**Comment by ericmartinezr** [comment]
You mean like ?
```
<child></child>
<child></child>
<child></child>
<child #thisOne></child>
@ViewChild('thisOne') child: Child;
```
Or you have something else in mind?

**Comment by theactiveactor** [comment]
@ericmartinezr This exactly what I was looking for. Thank you!

It wasn't clear from the docs if this was supported:
> You can use ViewChild to get the first element or the directive matching the selector from the view DOM.
https://angular.io/api/core/ViewChild

**Comment by pkozlowski-opensource** [comment]
Closing as a support request that was answered by @ericmartinezr (thnx!)

**Comment by izabellaszlosarczyk** [comment]
**Better ViewChild support for multiple instances of child component** I know that this issue is closed, but what @ericmartinezr  wrote is okay,  but not enough (at least for me :) ).  What about situation like this?
`<div *ngFor="let children of children">
    <child *ngIf="child.type == type1"></child>
    <child2 *ngIf="child.type == type2"></child2>
</div>`
I can instert #child1 and #child2 to <child> and <child2>.  But what it is giving me? I will still get first one,  how to get others?
And what about situation when these elements are undefined and the begining and I need write setter in component class.

**Comment by annaitcom** [comment]
Does anyone have an answer about it???

**Comment by MuhammadAsifAdnan** [comment]
following
