### ISSUE TITLE
ActivatedRoute not updated when navigation to same URL with onSameUrlNavigation = 'reload'

### ISSUE THREAD

**Issue by dcesiel** [angular/angular#21647]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[X] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior
ActivatedRoute is not updated when navigating to the same route when onSameUrlNavigation = 'reload' ExtraOption

## Expected behavior
This may have been a conscious design decision, but I would expect ActivatedRoute streams to publish the event when navigating to the same url. 

## Minimal reproduction of the problem with instructions
https://stackblitz.com/edit/onsameurlnavigation-activatedroute

## What is the motivation / use case for changing the behavior?
I think this should be done for consistency.  This could be confusing to developers that Router.events updates but not the ActivatedRoute streams like ActivatedRoute.url.

## Environment

<pre><code>
Angular version: 5.1.2
Still an issue in the most recent version of Angular.  

Browser:
- [X] Chrome (desktop) version XX
- [X] Chrome (Android) version XX
- [X] Chrome (iOS) version XX
- [X] Firefox version XX
- [X] Safari (desktop) version XX
- [X] Safari (iOS) version XX
- [X] IE version XX
- [X] Edge version XX
 
For Tooling issues:
- Node version: 8.9.4
- Platform:  Mac

Others:
None

**Comment by mlc-mlapis** [comment]
@dcesiel ... did you use `runGuardsAndResolvers` property on the route?

https://github.com/angular/angular/issues/21115#issuecomment-355103721

**Comment by dcesiel** [comment]
Thanks, @mlc-mlapis that fixed it for me.  I would not have connected the two configuration options based on what's in the Angular docs.

**Comment by dcesiel** [comment]
So I thought this issue was solved, but I spoke too soon.  If you take a look at the stackblitz I've set     enableTracing: false and runGuardsAndResolvers: 'always', yet the console.log() in AppComponent only fires once and not on each click.

**Comment by mlc-mlapis** [comment]
@dcesiel ... the way how to use of `ActivatedRoute` is a bit different (it has always sense only on the relevant component level) ... as I show in this Stackblitz demo https://stackblitz.com/edit/mlc-onsameurlnavigation-activatedroute?file=app%2Fproduct%2Fproduct.resolver.ts.

As you can see on the console ... repeated clicking on the button `go to HOME` always runs the guard and the related resolver and also the subscription to `data` observable on `ActivatedRoute` always returns actual data from the resolver. This is because that `data` are changing. This is similar to the behavior of a subscription to `params` observable on `ActivatedRoute` when using a route like `/product/:id` because the subscription also runs only when `id` is changed (it means routing from `/product/2` to `/product/6` for example ... the component itself in not re-instantiated).

Repeated clicking on the button `go to PRODUCT` runs also the guard and the related resolver **BUT** the subscription to `data` observable on `ActivatedRoute` returns data from the resolver only when you are switching the routes.

The difference between both is just and only that the `HomeResolver` always returns a different number (random) and `ProductResolver` returns always number 5. So there is the same logic and behavior as in `/product/:id` case described above.

**Comment by jasonaden** [comment]
Closing this as it was addressed by @mlc-mlapis above. If there's still something broken in Angular, please create a new issue.
