### ISSUE TITLE
How is the amount of training materials developed for Angular?

### ISSUE THREAD

**Issue by splincode** [angular/angular#21685]
Why are there only tutorials around React? I often send my students to study technology at:

1. https://www.freecodecamp.org/

![image](https://user-images.githubusercontent.com/12021443/35188227-d8e52a88-fe42-11e7-8b6a-e6e7e7181ddc.png)

2. https://www.codecademy.com/

![image](https://user-images.githubusercontent.com/12021443/35188263-55c58034-fe43-11e7-9e54-aaec8f539667.png)

But there are no tutorials on Angular

3. https://www.codeschool.com/

Very short video and just about simple things about Angular2 (systemjs), but we all usage Angular (with webpack from Angular CLI).

![image](https://user-images.githubusercontent.com/12021443/35188301-e858e5bc-fe43-11e7-83d7-f437c5b1f3e5.png)

4. I can not find anywhere a video about the Angular ecosystem (Universal, Ionic, NativeScript).

**Comment by mlc-mlapis** [comment]
@splincode ... some options:

* https://angular.io
* https://angular-university.io
* https://egghead.io
* https://www.pluralsight.com
* https://rangle.io
* https://youtube.com (presentations from Angular conferences)
* many blogs like https://blog.angularindepth.com
* ...

**Comment by IgorMinar** [comment]
@StephenFluin @robwormald

**Comment by StephenFluin** [comment]
I'm closing this issue. There are lots of great Angular training courses (also check out https://angular.io/resources) and we are actively working with many content authors (and we have 50+ GDEs  who are all writing and speaking and doing awesome things with Angular https://developers.google.com/experts/all/technology/angular) 

CodeSchool hasn't been updated in a while (for Angular or others I believe) because the founder Gregg left I believe. We chatted together when he was working on the original course.

Thanks @mlc-mlapis for the great list too, :). Feel free to submit any more you find here: https://github.com/angular/angular/blob/master/aio/content/marketing/resources.json
