### ISSUE TITLE
generate sitemap for angular.io

### ISSUE THREAD

**Issue by IgorMinar** [angular/angular#21684]
In order to improve search results, we should provide a sitemap file to crawlers so that they have an easier time understanding the site. This should be an easy task because it's just a different projection of the data we already have dgeni generate as navigation.json.

- [ ] modify dgeni to produce a sitemap file
- [ ] add metatag into the index.html to point to the new new sitemap file

**Comment by petebacondarwin** [comment]
There is one small hurdle to overcome, which is that sitemaps require fully qualified URLs such as `https://angular.io/about` rather than relative ones such as `./about` etc.

At doc-gen time we do not know the host name where this will be deployed since that is defined when building the AIO app (and transmitted to the app via ["environments"](https://github.com/angular/angular/tree/master/aio/src/environments)) at deployment time.

https://github.com/angular/angular/blob/master/aio/scripts/deploy-to-firebase.sh#L90

There are a few options:

1) We could generate multiple versions of the sitemap (one for each environment) in dgeni and the change the deployment script to include the relevant file in the upload.
2) We could generate a generic sitemap, using relative paths, and then prepend the deployment host into this sitemap at deployment time, in the deployment script.
3) We could use the same logic that the deployment script uses to determine the appropriate host while inside dgeni.

I think that the 2nd approach is the most straightforward.

Any thoughts @gkalpak or @IgorMinar ?

**Comment by gkalpak** [comment]
The 2nd approach sounds fine.
(Ideally, it should be part of the build step, but I can't think of straight forward way to do that, so at deployment sgtm.)

**Comment by IgorMinar** [comment]
We don't need site map for any other domain than the main angular.io. All
the other ones have robots.txt set to disallow crawling. So it's fine to
hard-coded the domain name.

**Comment by petebacondarwin** [comment]
> We don't need site map for any other domain than the main angular.io. 

Doh! I just implemented it in #21689 

I can remove it, since it adds unnecessary complexity to the tooling. But I'll wait for a go-ahead from you before doing so.

**Comment by petebacondarwin** [comment]
I created a second commit that strips out the replacing functionality.

**Comment by amannguptaggg** [comment]
**follow these steps to add sitemap.xml and robots.txt in your angular project**
[Add sitemap.xml and robots.txt in Angular CLI](https://aman-g.com/blog/post/add-sitemap.xml-and-robots.txt-in-Angular-CLI)
