### ISSUE TITLE
Trailing slash getting appended while serving same url

### ISSUE THREAD

**Issue by Sudheer-Reddy** [angular/angular#21741]
## I'm submitting a...

<pre><code>
[x] Regression 
</code></pre>

## Current behavior

My current route is `http://localhost:4200/products` and when i refresh the page or webpack refreshes the page upon some update in code, a trailing slash `http://localhost:4200/products/` is getting added at the last which angular is treating as a url instead of route.

## Expected behavior

It should treat it as a route and should load the respective lazyloadmodule.chunk.js file.
## Environment

<pre><code>
Angular version: 6.0.0-beta.0
Angular-Cli: 1.7.0-beta.1

**Comment by trotyl** [comment]
Angular is doing the opposite (#16051), if it's a backend redirection, please report to the server or dev-tool instead.

**Comment by Sudheer-Reddy** [comment]
Hi, 

I've recorded a video for above scenario, also to mention that i've not using any server other than webpack which is masked by angular cli. The same scenario used to work in earlier versions which after upgrading angular has broken. Please take a look at the screencast attached. Also the project i've tried is the one that is provided in angular.io docs [https://angular.io/guide/lazy-loading-ngmodules](url)
[Jan 24 2018 4_27 PM.webm.zip](https://github.com/angular/angular/files/1659548/Jan.24.2018.4_27.PM.webm.zip)

**Comment by jasonaden** [comment]
I'm sorry but reported issues require a reproduction of the issue. We suggest using [StackBlitz](https://stackblitz.com/fork/angular-gitter), [Plunker](http://plnkr.co/edit/tpl:AvJOMERrnz94ekVua0u5?p=catalogue) or [Github](https://github.com/new).

If this issue persists, please create a reproduction using one of the links above. Describe the difference between the expected and current behavior in a new issue with the reproduction linked.

<hr>

If you can reproduce the problem external from your own project, we should be able to look into it. Otherwise, it could be related to your specific environment, which wouldn't allow any debugging to happen.
