### ISSUE TITLE
NativeShadowDomStrategy

### ISSUE THREAD

**Issue by matanlurey** [angular/angular#2175]
Related to #2173: In code-gen mode, native shadow DOM is not working/resolving style URLs properly.

With the transformer disabled, a component's `<style>@import "shell.scss.css"</style>` becomes:
`http://localhost:8080/packages/crm.greentea.expfe21.entrypoint/src/shell.scss.css`

With it enabled, it becomes:
`http://localhost:8080/shell.scss.css`, which in invalid

cc: @kegluneq, @mhevery

**Comment by gdi2290** [comment]
I have this problem too so my solution was use webpack to manage the url etc [home/home.ts#L8](https://github.com/angular-class/angular2-webpack-starter/blob/5547869d0957f5ab95093637558ef170b57a2144/src/app/components/home/home.ts#L8).

I think the problem is in [compiler.ts#L72](https://github.com/angular/angular/blob/2.0.0-alpha.25/modules/angular2/src/core/compiler/compiler.ts#L72) where we are storing the baseUrl and here [compiler.ts#L211](https://github.com/angular/angular/blob/2.0.0-alpha.25/modules/angular2/src/core/compiler/compiler.ts#L211) where we are trying to get the component url but we're not using `RuntimeComponentUrlMapper` with `setComponentUrl` :/ so that's why it's not working

**Comment by matanlurey** [comment]
My temporary fix was to put the fully qualified dart package path and overriding UrlResolver to resolve properly. I'm assuming this is a simple bug  :facepunch:

**Comment by vicb** [comment]
@matanlurey could you please confirm that the problem occurs when the transformers are enabled ?
_in such a case, I would re-assign this to @kegluneq_

**Comment by matanlurey** [comment]
It's only happening in gen mode, yes.

**Comment by kegluneq** [comment]
Making sure I understand the fix:

The transformer needs to update urls in html templates to be relative to the application root rather than the html file itself.

Is that correct?

**Comment by kegluneq** [comment]
Assigning to @matanlurey for an answer.

**Comment by tbosch** [comment]
Please note that we are in the process of changing style loading / inlining: the compiler will load and inline styles for all shadow dom strategies soon (see https://github.com/angular/angular/pull/2459). With this, the transformer does not need to do anything special any more...

**Comment by tbosch** [comment]
@matanlurey Could you help @jakemac53 reproduce this?

**Comment by matanlurey** [comment]
GT is no longer using native.

**Comment by vicb** [comment]
FYI: I don't think this is related to `NativeShadowDom` only as urls are resolved whatever the strategy. However we already have other issues related to URL resolving. I am supposed to take a look this week.
