### ISSUE TITLE
Docs - Style Guide - Style 04-10 - "Avoid providing services in shared modules" is confusing

### ISSUE THREAD

**Issue by dubbha** [angular/angular#21911]
Actually repeating an old one left without an answer:
https://github.com/angular/angular.io/issues/3230#issuecomment-301257163

I find the Style Guide part Style 04-10 saying "Avoid providing services in shared modules" really confusing. And I've found the issue above trying to make sense of it, so I'll just repeat what @nikosgpet says there:

"I understand that we have to be very careful when providing services in shared modules. I don't understand though why we should altogether avoid providing services in shared modules, nor what we are supposed to do instead. It is especially confusing the fact that the example given is actually not following this advice (?!).

I understand that there is some logic behind this advice, but:

1. It should be explained better, perhaps in more length and more clearly.
2. The example should either follow the advice or it should be better explained why the example doesn't follow it."

**Comment by kapunahelewong** [comment]
Hi @dubbha and @nikosgpet! Thanks for bringing this up - I'll work to clarify this in the Style Guide. While I do that, maybe it would help to check out the new [Sharing NgModules doc with a section on just this](https://angular.io/guide/sharing-ngmodules#using-components-vs-services-from-other-modules). That's it very briefly - the reason you (usually) don't want provide services in a shared component is because it will create separate instances. 

For deeper info, you might also find helpful the page on [Providers](https://angular.io/guide/providers). There's a section on provider scope. Additionally, you might like [Singleton Services](https://angular.io/guide/singleton-services) which gives an alternative for providing services so that you don't get multiple instances. We've recently reworked those docs to help make these concepts clearer. I'd be very interested in your take.

That said, I think the reason that example is providing the service in the shared module is to show that it will create a new instance, but I need to look at it more closely, which I'll do when I work on it to clarify it. Maybe we need to clarify why it's like that and show the alternative.

Please let me know if this helps you. Thank you!

**Comment by jenniferfell** [comment]
docsarea=styleguide
docsarea=ngmodules
filename=https://angular.io/guide/styleguide#shared-feature-module
https://angular.io/guide/sharing-ngmodules#using-components-vs-services-from-other-modules

**Comment by kapunahelewong** [comment]
Working on this to make sure that I've got it right.

**Comment by kapunahelewong** [comment]
Closing because PR was merged. Thanks @dubbha
