### ISSUE TITLE
TS2451: Cannot redeclare block-scoped variable 'ngDevMode'.

### ISSUE THREAD

**Issue by crowmagnumb** [angular/angular#21925]
## I'm submitting a...

<pre><code>
[x] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior

From Angular 5.1.3 and before my compilation problem worked fine. Upon upgrading to 5.2.2 I now get ...

ERROR in [at-loader] ./node_modules/@angular/core/src/render3/ng_dev_mode.d.ts:9:11
    TS2451: Cannot redeclare block-scoped variable 'ngDevMode'.

ERROR in [at-loader] ../module/node_modules/@angular/core/src/render3/ng_dev_mode.d.ts:9:11
    TS2451: Cannot redeclare block-scoped variable 'ngDevMode'.

This is a continuation of issue [21670](https://github.com/angular/angular/issues/21670) with a now working repo.

## Expected behavior

No compilation error.

## Minimal reproduction of the problem with instructions

Check out this repo and follow the simple instructions...

https://github.com/crowmagnumb/ng-problem

## What is the motivation / use case for changing the behavior?

Broken

## Environment

<pre><code>
Angular version: 5.2.1
 
For Tooling issues:
- Node version: 8.2.1
- Platform:  Mac

Others:
</code></pre>

**Comment by rickvandermeij-aanzee** [comment]
I've had the same issue, because i used our own framework as a dependency. because the versions of both repo's had different angular versions i ended up with this error. When updated both repo's to the same angular version, the error disappeared.

**Comment by rickvandermey** [comment]
I've had the same issue, because i used our own framework as a dependency. because the versions of both repo's had different angular versions i ended up with this error. When updated both repo's to the same angular version, the error disappeared.

**Comment by chuckjaz** [comment]
The problem is fundamentally here,

```
"paths": {
            "Utils/*": ["../module/src/utils/*"]
        }
```

This causes TypeScript to bring in both the `@angular/core` from `../modules/node_modules/@angular/core` as well as the `@angular/core` from `./node_modules/@angular/core`.  This has never been supported and errors produced in this configuration are not considered regressions as the scenario is not support, it just happened not to break for you until 5.2. There are several cases where this would have broken your code earlier, you just didn't hit them.

To state this more clearly, we don't support having two different versions of angular definitions in the same compilation.

The simple way around this is to have module and app share the same copy of angular instead of having there own. In other words, move the package.json up one directory.

If you require to have a separate compilation then I recommend using something like `ng-packgr` to help build the `module` directory as a package. This package can then be installed into the `node_modules` of `app`.

We are working to improve the ergonomics of libraries and is one of our primary focuses for this release cycle. For now, however, you need to ensure that only one copy of angular is found by the compiler or separately compile the modules using `ng-packgr`.

**Comment by mariohmol** [comment]
Shouldnt this be open? cant solve it in this project https://github.com/mariohmol/ang-jsoneditor

**Comment by mariohmol** [comment]
Got this working, if u get here follow this discussion 👍 

https://github.com/angular/angular/issues/21670#issuecomment-370274821

thanks

**Comment by tyholby** [comment]
I fixed it by updating my typescript dependency to "typescript": "2.5.3".
(I'm on "@angular/core": "5.2.8")

**Comment by jensenv** [comment]
I ran into this issue as well today, and tyholby's solution (upgrade typescript to 2.5.3) fixed it.

**Comment by jagomf** [comment]
Happening as well when upgrading from Angular 5.2 to 6.2

**Comment by mal90** [comment]
can confirm . this is happening in angular 6.0.3 as well.

**Comment by alexonaci** [comment]
Can confirm too. Happening also on angular 6.0.4

**Comment by gustavogialim** [comment]
Same for the following:

```
"@angular/cli": "6.0.8",
"@angular/compiler-cli": "6.0.5",
```

**Comment by mariohmol** [comment]
have u guys tested/checked this https://github.com/angular/angular/issues/21670#issuecomment-370274821 ?

**Comment by gustavogialim** [comment]
My personal ones worked, I had a folder of node_modules in a previous project folder, this caused the error. It was this way:
```
Documents / project / node_modules (Correct)
Documents / node_modules (caused the error), only deleted this folder and it worked
```

**Comment by maurei** [comment]
Actually me it was also an error not related to angular-cli itself. I was using a custom npm library in which angular was imported. So im guessing it had to do with loading angular twice (?).

**Comment by matheuscaldasrj** [comment]
I had an Angular Library using @angular/core 6.0.7 and when upgrade my App from Angular 5 to Angular 6 I've had this error. Looking to my package.json file I noticed that all Angular dependencies were in versions 6.0.7.

So, I changed all versions from 6.0.9 to 6.0.7 and now it works.

How is the proper way to handle with it?

**Comment by rickvandermey** [comment]
I've added some logic to delete all node modules from my specific library which gives the error:

```
var rmdir = require('rmdir');
var path = 'node_modules/{{ library }}/node_modules';

rmdir(path, (err, dirs, files) => {
	console.log(dirs);
	console.log('all files are removed');
});
```

**Comment by vimalans** [comment]
@rickvandermey, thanks it worked!
