### ISSUE TITLE
componentFactoryResolver.resolveComponentFactory（“ComponentClassName”）

### ISSUE THREAD

**Issue by softboy99** [angular/angular#21986]
Currently dynamic component must dependent on the container component because the componentFactoryResolver.resolveComponentFactory method must have the component parameter. Is it possible to use ComponentClassName string instead?

**Comment by mlc-mlapis** [comment]
@softboy99 ... but something like `ComponentClassName string` doesn't exist at all in JS / TS ... so how can you use it ... it is not related to Angular.

**Comment by alexzuza** [comment]
You will lose that string after minification.

**Comment by softboy99** [comment]
Hi,
Is your entryComponents here is the one in NgModule?

**Comment by IgorMinar** [comment]
Thanks for filing the issue, but class name strings have two problems - they don't preserve namespace, and they are not minification safe.

**Comment by softboy99** [comment]
Hi
Thanks, i know your concern. Now, i use the static map variable in AppModule to do that:

export class AppModule {
  static entryComponents = {
    'UserComponent': UserComponent
  };
}

At other place, use AppModule.entryComponents[args.ClassName] in code

Currently, i do it manually. If CLI can do it automatically, It is perfect.

**Comment by IgorMinar** [comment]
This pattern looks very odd. I'm actually not sure what you are trying to
do but this doesn't look right.

**Comment by softboy99** [comment]
It's very important for dynamic component loading, Currently dynamic component must depend on the container component and import to the container component's TS file, when there're many components, It's very inconvenient to use. In my app, all of the components are dynamic loaded. It's very popular in normal desktop application like c#/delphi etc to use reflection.

**Comment by Tcharl** [comment]
I've the same use case in a microservice-oriented portal application.

Imagine you've tiles displayed in a dashboard, but their content is contributive (via microservice which registers tiles' content at bootstrap).
I'm used to use the component factory in order to create the tile's content (to populate the Tile ngTemplate), but if I could have loaded it with a string, I could have persisted the component name of that tile in the microservice's database.

The last issue would be the dynamic import of microservice modules (but this is another thread)

**Comment by mlc-mlapis** [comment]
@Tcharl ... you can load programmatically a module by the same way as Router is doing. And if you keep your own map (string key <-> component type) as a part of that module you can even use its component via their names.
