### ISSUE TITLE
.pipe operators on EventEmitter leaks subscriptions

### ISSUE THREAD

**Issue by jbedard** [angular/angular#21999]
## I'm submitting a...
<pre><code>[X] Bug report</code></pre>

## Current behavior
`EventEmitter` overrides `Subject.subscribe` to add `isAsync` support but doesn't take all `Subject.subscribe` param types into account. In this case `FilterSubscriber` (and probably other `Subscriber` types) filters correctly but does not cleanup on unsubscribe.

## Expected behavior
Methods available on `EventEmitter` should function and not leak.

## Minimal reproduction of the problem with instructions
```
it('should have no observers after .pipe(op).subscribe().unsubscribe()', () => {
  const ee = new EventEmitter();
  ee.pipe(filter(() => true)).subscribe().unsubscribe();
  expect(ee.observers.length).toBe(0);
});
```

## What is the motivation / use case for changing the behavior?
While I don't think this is a standard (or supported?) use case of `EventEmitter`, there are definitely [some use cases](https://github.com/valor-software/ng2-dragula/blob/v1.3.1/src/components/dragula.provider.ts#L6) out there. Or people could potentially be listening to outputs within their own components etc. Either way, if the standard `Subject` methods are available they should probably function correctly and not leak.

Changing `EventEmitter` to not extend `Subject` would be another solution which I know has been mentioned before.

**Comment by jbedard** [comment]
The material `MatDrawerContainer` reproduces this by [subscribing](https://github.com/angular/material2/blob/5.1.1/src/lib/sidenav/drawer.ts#L482) to the [Directionality.change](https://github.com/angular/material2/blob/5.1.1/src/cdk/bidi/directionality.ts#L42) output.

**Comment by jbedard** [comment]
Here's an example using material: http://plnkr.co/edit/RvLCnqc1yKc1tX8LKqop

Each time you toggle the `mat-drawer-container` it leaks the subscription mentioned above which references the `MatDrawerContainer` which references more etc. Click the button a few times, take a heap snapshot and search for "MatDrawerContainer"...

**Comment by jbedard** [comment]
Here's a potential fix + tests: https://github.com/jbedard/angular/commit/30e07b3fb78848af008320c7053d2777982e589b

This changes the `isAsync` handling to be at emit-time instead of subscriber-handler time. I was hoping to avoid such a change but I can't figure out how to fix this issue and keep `isAsync` support for the case where `subscribe(generator)` is used. One benefit (I think?) is that subscribers are no longer wrapped which I often find minorly annoying when debugging or inspecting stack traces.

An alternative might be using a scheduler? But it appears that schedulers do not make complete/error async which would be a breaking change.

**Comment by martinsik** [comment]
This is interesting because it really looks like it's a bug. If you do the same with `Subject` it works as expected and the observer is removed. I tried this demo with a couple of other variants: https://stackblitz.com/edit/angular-9kvrfk?file=src/app/app.component.ts

However the reason why it doesn't work as expected is different than you describe. It's not tied to any specific subscriber like `FilterSubscriber` or `MapSubscriber` but generally any `Subscription` instance. 

For example all of these work as should:

```
const ee1 = new EventEmitter();
ee1.subscribe().unsubscribe();
console.log(ee1.observers.length); // 0

const ee2 = new EventEmitter();
ee2.asObservable().pipe(filter(() => true)).subscribe().unsubscribe();
console.log(ee2.observers.length); // 0

const ee3 = new EventEmitter();
ee3.subscribe(val => console.log(val)).unsubscribe();
console.log(ee3.observers.length); // 0
```

Note that I can use `asObservable()` and then chain operators and they'll unsubscribe correctly.

The problem is in the way `EventEmitter` works with instances of the `Subscription` class. This includes `FilterSubscriber`, `MapSubscriber`, etc.

Right now `EventEmitter.subscribe()` takes the `Subscription` object and wraps all its methods with functions `schedulerFn`, `errorFn` and `completeFn` and then passes them as parameters into `super.subscribe(...)`. This calls `Observable.subscribe()` where these [functions are wrapped into another `Subscriber` object](https://github.com/ReactiveX/rxjs/blob/master/src/internal/Observable.ts#L196) which is then returned. But it doesn't do anything with the original `Subscription` object that came to `EventEmitter.subscribe()` at the first place. It only returns the wrapped `Subscription` from  `Observable.subscribe()` so when it comes to disposing the Rx chain the original `Subscription` is never disposed.

For example these two examples won't work as should:

```
const ee = new EventEmitter();
ee.pipe(map(() => true)).subscribe().unsubscribe();
console.log('EventEmitter', ee.observers.length); // 1 - wrong

// This simulates `FilterSubscriber` or `MapSubscriber`
const subscriber = new Subscriber(val => {});
subscriber.add(() => console.log('Subscriber disposed')); // This is never called - wrong
const ee2 = new EventEmitter();
ee2.subscribe(subscriber).unsubscribe();
console.log('EventEmitter - Subscriber', ee2.observers.length); // 0
// This did unsubscribe because we're holding the direct `Subscription` for `EventEmitter`
// but didn't trigger the teardown function. The teardown function is
// where it unsubscribes from its parent in `FilterSubscriber` or `MapSubscriber`.
```

I think the easiest way to fix this and keep the original functionality without introducing any possible breaking changes is to add the "new" `Subscription` to the "original" one. hen when disposing the chain it'll properly dispose all `Subscription`s.

```
subscribe(generatorOrNext?: any, error?: any, complete?: any): any {
    // ...

    const sink = super.subscribe(schedulerFn, errorFn, completeFn);

    if (generatorOrNext instanceof Subscription) {
      generatorOrNext.add(sink);
    }

    return sink;
}
```

**Comment by IgorMinar** [comment]
thanks for the excellent bug report. let's discuss more on the #22016 PR which seems promising.

**Comment by jbedard** [comment]
@martinsik thanks for the nice fix, that looks right to me.
