### ISSUE TITLE
Router: redirect during route resolution looses query params

### ISSUE THREAD

**Issue by ukrukarg** [angular/angular#21994]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior

1. I navigate to a/?project=a
2. Inside a Resolver I have
`router.navigate(['a', 'deep'], {queryParamsHandling: 'merge'})`
3. I end up on a/deep instead of a/deep?project=a

## Expected behavior
3. I end up on a/deep?project=a 

## Minimal reproduction of the problem with instructions
https://stackblitz.com/edit/angular-4mqvbc?file=app%2Fhello.component.ts

**Comment by ukrukarg** [comment]
Internal tracking: b/72861719

**Comment by jasonaden** [comment]
Likely related to #17023

**Comment by jasonaden** [comment]
This is due to the router mostly ignoring `NavigationExtras` for both `router.navigate` and `router.navigateByUrl` methods. This has been mentioned in a docs issue here: https://github.com/angular/angular/issues/22668

The best way to get the behavior you're looking for right now is to create a UrlTree. You can use `router.parseUrl` to do so. Something like this: https://stackblitz.com/edit/angular-wbbfh4?file=app/hello.component.ts

**Comment by ukrukarg** [comment]
This is very un-intuitive that method accepts params that it later ignores. Can the type of the method be updated to reflect which elements of extras it actually uses?
