### ISSUE TITLE
Configuration of Angular with WebPack for ASP.NET MVC 5

### ISSUE THREAD

**Issue by NikolayYeryomenko** [angular/angular#22086]
It would be nice to read an article about configuration of Angular with WebPack for ASP.NET MVC 5 in Visual Studio 2017.

There is no a complete documentation about this theme on internet.

This has to be the modern way of configuration, because Angular QuickStart Repo (https://github.com/angular/quickstart) is deprecated.

**Comment by frederikprijck** [comment]
@NikolayYeryomenko As a .NET developer, all I can say is it's a good idea to combine angular with WebAPI instead of MVC.

If you want to enable SSR (server-side rendering), you could have a look at https://github.com/MarkPieszak/aspnetcore-angular2-universal but keep in mind this doesn't allow you to use angular/cli. If you don't want to use SSR, you can still have a look at that repo how they combine Angular, ASP.NET and Webpack.

If you wanna use CLI + SSR, I think you need to use nodejs to host your application.

Never the less, I don't think the angular team can provide these kind of examples. So this doesn't belong in this repo.
If you have any .NET + Angular related questions, feel free to ping me at gitter https://gitter.im/angular/angular

**Comment by jenniferfell** [comment]
docsarea=webpack

**Comment by mgechev** [comment]
webpack is outside the scope of the Angular documentation. I'd suggest to keep integration content outside angular.io.
