### ISSUE TITLE
aio + docs/api: consider removing parenthesis from method headings

### ISSUE THREAD

**Issue by petebacondarwin** [angular/angular#22133]
In https://github.com/angular/angular/pull/21874#issuecomment-363543097 @gkalpak noted:

![image](https://user-images.githubusercontent.com/15655/36048075-4ba674c8-0dde-11e8-8b05-5a139723ac45.png)

**Ignore the red arrow :-) it was from another issue that is resolved**

Since the constructor signature is shown below, I find it a little confusing (and inconsistent with other sections; e.g. `Properties`). to have the [heading of the section](https://pr21874-14230fd.ngbuilds.io/api/forms/AbstractControl#constructor) be `constructor()` (which kind of looks like a constructor should be called with no arguments).

**Comment by petebacondarwin** [comment]
![image](https://user-images.githubusercontent.com/15655/36048136-7c8428ba-0dde-11e8-9123-17d7d99ead7a.png)

For similar reasons as with the constructor, I would consider dropping the parenthesis from [method names](https://pr21874-14230fd.ngbuilds.io/api/forms/AbstractControl#setErrors).

**Comment by petebacondarwin** [comment]
@jbogarthyde does not agree with this suggestion. See https://github.com/angular/angular/pull/21874#issuecomment-363861807

> Here I don't agree - it is a widely-used convention to identify fn/method names in text with empty parens. This is NOT parallel to Constructor/Properties/Methods - it is a subheading of Methods, and needs to be distinguished as a method name.

**Comment by sjtrimble** [comment]
I agree. The original design had the Constructor section title same as Properties, Methods, etc. see below. 

![aio-constructor](https://user-images.githubusercontent.com/2958442/36681244-f073d81a-1acc-11e8-9e6b-5e5e41ae6307.PNG)

Regarding the use of parenthesis in method name titles, I've seen both, although more often they _do not_ include the parenthesis. Up to you guys.

**Comment by petebacondarwin** [comment]
@IgorMinar and @jbogarthyde can you comment on whether we should get rid of the `()` from the method headers.

**Comment by jbogarthyde** [comment]
I like them - since the heading styles are not particularly distinguishable unless they are right next to each other, I think the parens help the reader maintain orientation in the nav. You immediately and intuitively understand that you are looking at an individual method within the Methods section, and  not some kind of descriptive section heading.

**Comment by gkalpak** [comment]
I believe there are other ways to help the user maintain orientation. For example, on wide screens the ToC will always be visible on the right and highlight the current method subsection, which will be under the `Methods` section.

Also, I suggest we put the method signature right below the heading (before the description), which makes it easy to see that this is a method. (Also note the methods section is currently very different from the properties section, where all properties are inside the same table, but I accept this might change in the future.)

It would look similar to the Java docs: 
![javasdocs](https://user-images.githubusercontent.com/8604205/36805675-b2c95aa2-1cc6-11e8-81e9-5367b853aabc.png)

Maybe we could have a layout like this:

1. Signature
2. Short description.
3. Params
4. Return value
4. Full description/Usage notes.
5. Examples.

##
All that said, I don't feel strongly about it. I myself always use `()` when I mention methods :grin:

The only reason I suggested dropping them here, is because in this context it is not clear whether this is just the method name or a full signature and if someone if not careful it might seem like the method should be called without any arguments.

But I don't think this will have any major impact anyway, so happy to go either way :smiley:

**Comment by petebacondarwin** [comment]
The layout is currently:

1. Name *(heading)*
2. Description
3. Signature
4. Params
5. Return Value
6. Usage Notes *(not currently implemented!)*

So unless the description is very short the signature could be off the screen.
@jbogarthyde was very sure she wanted the signature to be directly followed by the params and return value.

But I think we could follow in the footsteps of the class descriptions and split off the first paragraph to use as a shortDescription, which I would be happy to put just before or after the signature. Then move the rest of the description below everything.

**Comment by petebacondarwin** [comment]
In fact the more I look at examples the more I feel that the signature should come first followed by a one liner description then the params etc.

**Comment by petebacondarwin** [comment]
But this is getting off topic. I think that for now we should just leave the parens in place since it is not particularly confusing since the real signature is directly below.

**Comment by petebacondarwin** [comment]
I created a new issue to discuss the description ordering in #22500

**Comment by petebacondarwin** [comment]
The syntax is now only one paragraph away - since we have implemented the "short description" field.

See this screenshot:

<img width="1061" alt="screen shot 2018-03-07 at 21 06 38" src="https://user-images.githubusercontent.com/15655/37118252-8ee40b16-224b-11e8-9545-ff17690246f9.png">

**Comment by IgorMinar** [comment]
I also find the empty params a bit misleading. I looked around and I see that some API docs do it this way and others don't. e.g. MDN does use empty params https://developer.mozilla.org/en-US/docs/Web/API/XMLHttpRequest/send

Have we considered one of these two things:
1. move the syntax / signature to the heading and remove it from body? (this might be problematic for methods with long signature, but this should be rare and we should focus on minimizing these kind of apis because they are hard to use)
2. add `...` to parens for signatures that have options and suffix the heading with `: returnType` to make it more like a signature - very frequently it's the name and return value that allows me to determine if a method is of an interest to me, so highlighting the return value be useful.

**Comment by petebacondarwin** [comment]
There are a lot of methods with very long signatures so I believe it would be very distracting to include the entire signature in the heading.
Also what do we do about the many methods that have multiple overloads?

**Comment by IgorMinar** [comment]
oh.. could we then change `()` to `(...)`? what do you think about that?

**Comment by petebacondarwin** [comment]
So to be clear: add `...` if there is one or more parameter in the signature?

Do you still want to add the return value? This can also end up being quite long, if it is returning an anonymous object type.

**Comment by petebacondarwin** [comment]
One more suggestion: The class overview contains specially formatted members that are designed not to run to more than one line. They do this by replacing the contents of curly braces with `...`.

But this can still end up with very long signatures, which I think actually makes it even more difficult to parse visually.

Here are some examples:

```typescript
markAsTouched(opts: {...}): void
```

```typescript
patch(url: string, body: any | null, options: {...}): Observable<any>
```

```typescript
  control(formState: any, validator?: ValidatorFn | ValidatorFn[] | null, asyncValidator?: AsyncValidatorFn | AsyncValidatorFn[] | null): FormControl
```

```typescript
options?: {...}
```

**Comment by jenniferfell** [comment]
Google Dev Doc Style Guide recommends empty parens after method names: https://developers.google.com/style/code-in-text#method-names

**Comment by jenniferfell** [comment]
fwiw...I agree with Judy. Most API doc I've worked on has a simple () after method names. There's a difference between using the name and providing complete syntax, and I don't think users expect syntax in the name...esp when the name is used in a heading and the full syntax is close below. Doc users don't look at the TOC for context while they are reading, so I wouldn't rely on the right nav to be a key indicator that this is a method you're reading about. I would be careful about adding any special annotations in the method name beyond name(). It could start to blur the line between a name and syntax. It also becomes another convention that readers need to learn so they can use the doc.

**Comment by IgorMinar** [comment]
ok. let's leave it as is since nothing we propose seems to improve the current situation. I'm going to close this issue, we can reopen it if we have new proposals. or not ;-)
