### ISSUE TITLE
Angular throws `Can't resolve all parameters` in aot when parent component has `@Injectable()` decorator

### ISSUE THREAD

**Issue by WiseBird** [angular/angular#22153]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior

```
// base.component.ts

@Injectable()
export class BaseComponent {
  constructor(
    public comopnentService: ComopnentService,
  ) {
  }
}
 

// child-two.component.ts
...
export class ChildTwoComponent extends BaseComponent {
}


// intermediate.component.ts

export class IntermediateComponent extends BaseComponent {
  constructor(
    protected type: TypesEnum,
    comopnentService: ComopnentService,
  ) {
    super(comopnentService);
  }
}


// child-one.component.ts
...
export class ChildOneComponent extends IntermediateComponent {
  constructor(
    comopnentService: ComopnentService,
  ) {
    super(TypesEnum.One, comopnentService);
  }
}

```

In JIT without `@Injectable()` decorator on `BaseComponent` ChildTwoComponent can't be instantiated: 

```
Uncaught Error: Can't resolve all parameters for ChildTwoComponent: (?).
```

In AOT with `@Injectable()` decorator warning is shown in console: 

```
Warning: Can't resolve all parameters for IntermediateComponent in /home/sergey/projects/angular-inheritance-resolve-issue/src/components/intermediate.component.ts: (?, [object Object]). This will become an error in Angular v6.x
```

## Expected behavior

No warnings in AOT

## Minimal reproduction of the problem with instructions

[Reproduction](https://github.com/WiseBird/angular_inheritance_resolve_issue)

## What is the motivation / use case for changing the behavior?

This is confusing behavior

## Environment

<pre><code>
Angular version: 5.2.4

Browser:
- [x] Chrome (desktop) version 64.0.3282.119
 
For Tooling issues:
- Node version: 8.9.3

**Comment by dewwwald** [comment]
@WiseBird it seem to me as if there might be a slight misunderstanding here. Since angular is an opinionated framework there are some concepts that are cemented that you can't get around, this can be a good thing (having a common point of reference to point your team to). 

From my understanding your issue arises from the angular IOC container not knowing what to inject there are a few ways you can solve this problem. The approach that I am taking is in the commits I am adding to this pull request. https://github.com/WiseBird/angular_inheritance_resolve_issue/pull/1

Here I am adding a provider to help angular figure out what to do when it sees that dependency.
https://github.com/WiseBird/angular_inheritance_resolve_issue/pull/1/commits/026dcbba6ad98e481d5d67a181bf8b02f68b1a39

Here I am defaulting a dependency by injecting the value I would like to be the default using `@Inject`, note that at this point you don't need to do that. As you ar providing the dependency at run time. You basically need to have a inject on intermediate to help the IOC not crash. 
https://github.com/WiseBird/angular_inheritance_resolve_issue/pull/1/commits/dcd6cd9969a1355a85ed5c61aaf54dc213c40363

This would be better suited as a stack overflow question stating why does this happen, if you link it here I will add the answer there.

In your code example. The intermediate component is dependant on its child. This is bad MVC design. You need to refactor that. I would like to help you do that, however I need further understanding. Why does the Intermediate component need to inject an enum value? If you could  provide a more full solution on why it is doing that I could maybe point you in a direction that can solve the problem while still making use of IOC as intended.

**Comment by dewwwald** [comment]
@mhevery hey, I am new to the angular issues. Is there anything I can do to contribute here?

**Comment by WiseBird** [comment]
@dewwwald 
> From my understanding your issue arises from the angular IOC container not knowing what to inject there

Yes, actually its not IOC's business (values is passed from the child component) but it thinks it is because of `@Injectable()` decorator on `BaseComponent`. And I can't remove the decorator because then `ChildTwoComponent` stops working.

> Here I am adding a provider to help angular figure out what to do when it sees that dependency

It's wrong because you losing ability to create multiple descendants of `IntermediateComponent` with different `TypesEnum` values. And this is a purpose of `IntermediateComponent`'s existence.
The right fix would be to provide type via property:
```
export abstract class IntermediateComponent extends BaseComponent {
  abstract getType(): TypesEnum;
}
export class ChildOneComponent extends IntermediateComponent {
  getType(): TypesEnum {
    return TypesEnum.One;
  }
}

```

> The intermediate component is dependant on its child. This is bad MVC design

Please elaborate. It has no direct dependency on `ChildOneComponent`. And passing value to superclass in constructor is OOP basic operation.

**Comment by dewwwald** [comment]
You just need the inject on the intermediate component. It isn't needed on the Child component. That means you can have variations. Instead of passing type just use the `this.getType()`.

> Please elaborate. It has no direct dependency on ChildOneComponent. And passing value to superclass in constructor is OOP basic operation.

Sorry, I could have been more clear here. If you think about it. Intermediate component is rendering something most likely as a result of what happened in the child. This is actually not bad MVC design , I was wrong here. What I should rather have said was that you have alternatives to passing a value down.

The bug here is that the compiler tries resolving the component and the parent class, where it should not do that. For your sample to work it should determine the value from the child. What I am proposing to you is a temporary fix of setting a default through Inject on IntermediateComponent.

**Comment by dewwwald** [comment]
I have made another commit labeled fix on your repo. You can read that to understand how to have variations. It turns out you can not use this before the super call.
https://github.com/WiseBird/angular_inheritance_resolve_issue#1

**Comment by WiseBird** [comment]
@dewwwald Ok, thank you. I guess I will use the workaround to prevent warning from showing.

**Comment by chuckjaz** [comment]
@WiseBird To be clear what @dewwwald explained, this is how the  dependency injector works. If a class in @Injectable, Angular assumes all parameters to the constructor are determined by the injector. Since annotations are inherited, all descendants are injectable and follow the same rule.

**Comment by duyhoang** [comment]
I have almost the same problem. My base component is not injectable, but it does have a parameter of type Enum. It seems that the base class doesn't handle Enum as a parameter.

**Comment by dwhitla** [comment]
I get this issue even when the superclass is abstract and has only a protected constructor.
I would have thought having a protected constructor on an abstract superclass made it clear that the parameters are to be supplied by the concrete subclass. Why is the injector trying to supply parameters to such a constructor?
