### ISSUE TITLE
Provide routing details in router events

### ISSUE THREAD

**Issue by Airblader** [angular/angular#22177]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[X] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior
`Router#events` do not contain information on whether `skipLocationChange` or `replaceUrl` have been provided. 

## Expected behavior
Events such as NavigationEnd should contain these flags.

## What is the motivation / use case for changing the behavior?
This would be useful, e.g,. to track navigation events to build an internal history stack which can be used to implement a »back button« in the app. However, there may be components within a page that change the URL but are used with `replaceUrl` to prevent adding to the location history. In the router events, however, it is not possible to see whether these flags have been provided.

I also don't want to use `Location#back` because I'd like to provide an actual routerLink instead of a click handler such that the link is actually a proper link.

## Environment

<pre><code>
Angular version: 5.x
</code></pre>

**Comment by jasonaden** [comment]
Thanks for this issue. I can definitely see how this would be useful. Is this something you would like to create a PR for?

**Comment by Airblader** [comment]
I can't promise anything yet, but I will see if I find the time to file a PR soon-ish. Thanks!

**Comment by atscott** [comment]
Copying over the contents of my comment on the PR: https://github.com/angular/angular/pull/22739#issuecomment-647773274

If you subscribe to the events and filter to `NavigationEnd`, I believe you can call [getCurrentNavigation](https://angular.io/api/router/Router#getCurrentNavigation) to get information about the navigation that just completed.

Even though the `currentNavigation` is cleared immediately after the event is emitted, the subscriptions should still process first.
https://github.com/angular/angular/blob/5c40fd65fa89adcd879ae1496683a7f5bdd543e3/packages/router/src/router.ts#L1113-L1117

minimal repro: https://stackblitz.com/edit/rxjs-zdqcnk 
Using the actual router: https://stackblitz.com/edit/angular-ivy-router-base-mcueuc

Because this would be a breaking change, seems somewhat uncommon, and has a simple alternative available, I think we might close this feature request.

Does this seem reasonable? @Airblader

**Comment by atscott** [comment]
Closing, as this can be accomplished with existing APIs. It's not a priority at this time to invest in a migration to cover this case (especially since the information is already available) as the change here would be breaking (see https://github.com/angular/angular/pull/22739#issuecomment-647763873).

**Comment by Airblader** [comment]
I'm sorry I never got back to you on your reply before. Thanks for taking the time!
