### ISSUE TITLE
Having trouble with CLI Ivy Hello World - Cannot read property 'type' of undefined

### ISSUE THREAD

**Issue by StephenFluin** [angular/angular#22206]
## I'm submitting a...

<pre><code>
[X] Bug report  
</code></pre>

## Preconditions
1. New CLI project
```
ng new ivy
cd ivy
yarn add @angular/{animations,common,compiler,core,forms,http,platform-browser,platform-browser-dynamic,router,cli,compiler-cli,language-service}@next
```
2. enable Ivy
```
  "angularCompilerOptions": {
    "enableIvy": true
  }
```

3. Update boostrap
```
/*platformBrowserDynamic().bootstrapModule(AppModule)
  .catch(err => console.log(err));*/
  ɵrenderComponent(<any>AppComponent);
```
4. `ng serve`

## Current behavior
```webpack-internal:///./node_modules/@angular/core/esm5/core.js:18628 Uncaught TypeError: Cannot read property 'type' of undefined``` at runtime in the browser

## Expected behavior
Hello World application renders.

## Environment

<pre><code>
Angular CLI: 1.7.0-rc.0
Node: 8.4.0
OS: linux x64
Angular: 6.0.0-beta.3
... animations, common, compiler, compiler-cli, core, forms
... http, language-service, platform-browser
... platform-browser-dynamic, router

@angular/cli: 1.7.0-rc.0
@angular-devkit/build-optimizer: 0.3.1
@angular-devkit/core: 0.3.1
@angular-devkit/schematics: 0.3.1
@ngtools/json-schema: 1.2.0
@ngtools/webpack: 1.10.0-rc.0
@schematics/angular: 0.3.1
@schematics/package-update: 0.3.1
typescript: 2.5.3
webpack: 3.10.0

Browser:
- [X] Chrome (desktop) version 64
 
</code></pre>

**Comment by mhevery** [comment]
`ng serve` => `ng serve --aot`
edit `app.module.ts` remove `BrowserModule`

It should work. Can you verify?

**Comment by StephenFluin** [comment]
`ng serve --aot` throw compilation errors:

```
Date: 2018-02-13T21:38:16.255Z - Hash: 45a302de31fcd767d6fa - Time: 261ms          
5 unchanged chunks

ERROR in : Error: Feature host dependencies is not supported yet
    at unsupported (/usr/local/google/home/stephenfluin/workspace/ivy/node_modules/@angular/compiler/bundles/compiler.umd.js:29421:11)
    at createFactory (/usr/local/google/home/stephenfluin/workspace/ivy/node_modules/@angular/compiler/bundles/compiler.umd.js:29979:13)
    at compileDirective (/usr/local/google/home/stephenfluin/workspace/ivy/node_modules/@angular/compiler/bundles/compiler.umd.js:29346:44)
    at /usr/local/google/home/stephenfluin/workspace/ivy/node_modules/@angular/compiler/bundles/compiler.umd.js:32022:17
    at Array.forEach (<anonymous>)
    at AotCompiler._emitPartialModule (/usr/local/google/home/stephenfluin/workspace/ivy/node_modules/@angular/compiler/bundles/compiler.umd.js:32012:20)
    at /usr/local/google/home/stephenfluin/workspace/ivy/node_modules/@angular/compiler/bundles/compiler.umd.js:31985:35
    at Array.reduce (<anonymous>)
    at AotCompiler.emitAllPartialModules (/usr/local/google/home/stephenfluin/workspace/ivy/node_modules/@angular/compiler/bundles/compiler.umd.js:31984:22)
    at AngularCompilerProgram._emitRender3 (/usr/local/google/home/stephenfluin/workspace/ivy/node_modules/@angular/compiler-cli/src/transformers/program.js:175:37)
    at AngularCompilerProgram.emit (/usr/local/google/home/stephenfluin/workspace/ivy/node_modules/@angular/compiler-cli/src/transformers/program.js:164:55)
    at AngularCompilerPlugin._emit (/usr/local/google/home/stephenfluin/workspace/ivy/node_modules/@ngtools/webpack/src/angular_compiler_plugin.js:773:49)
    at Promise.resolve.then.then.then (/usr/local/google/home/stephenfluin/workspace/ivy/node_modules/@ngtools/webpack/src/angular_compiler_plugin.js:602:54)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)


webpack: Failed to compile.
```

**Comment by StephenFluin** [comment]
Removed from both ngModule and ES2015 imports, seems to have worked.

**Comment by Ploppy3** [comment]
@StephenFluin Hello, I'm trying to test the new Ivy renderer on my own to see the benefits. I get the same error as you have.

I have

- updated to angular cli 1.7.0
- executed `ng update --next`
- executed `yarn install`
- enabled Ivy in src/tsconfig.app.json
- removed `BrowserModule` from `import: []` as well as `import {}`

What I don't understand is what you did in step 3 `ɵrenderComponent(<any>AppComponent);`, if I have to do this, where do I import the `ɵrenderComponent` function?

Currently I still bootstrap like I did in the past and I think it's wrong.
`platformBrowserDynamic().bootstrapModule(AppModule);`

**Comment by trotyl** [comment]
> #### ____ doesn't work!!!
> That's why it's not done - **please don't file issues**.

https://github.com/robwormald/ivy-code-size#____-doesnt-work

**Comment by Ploppy3** [comment]
@trotyl Why be so picky??? First I did not open an issue, I'm talking on a closed issue because I know that I don't want to waste people's time. The linked project only partially answer the question because as I expected, it bootstraps a single component. 

nb: If you don't want to answer, just don't, there is absolutely no need to do it in patronizing way.

**Comment by IgorMinar** [comment]
@Ploppy3 @trotyl  let me step in for a bit. I see this happening all the time. So let's step back and see what might have happened.

- @Ploppy3 tries to build a small app with ivy to test things, but encounters an error. He/She suspects that the problem is related to ivy not being finished, but is not sure, and really would love to see the magic working, so they post a comment asking for help/confirmation.
- @trotyl sees the comment and wants to confirm that @Ploppy3's problem is related to feature incompleteness of ivy. Rather than writing a full message, he copy & pastes a section of FAQ from @robwormald's ivy demo.
- @Ploppy3 sees the comment and feels patronized because the comment is very brief and explicitly mentions that people don't file an issue if something is not working. @Ploppy3 then posts a new comment calling @trotyl "picky" and "patronizing".

Most of the conversations that go down like this happen because we assume intention where there was none. I don't believe that @trotyl was trying to be mean or patronizing. I see @trotyl comment on lots of issues and PRs, and sometimes when people post so frequently, they try to be as efficient as possible and use shortcuts to communicate the message (like copy&pasting existing documentation).

Github enables text-only communication form where no voice tone & emphasis, body language, or facial expressions can be observed by the message receiver. **It's these non-verbal communication channels that fill in the meaning, tone, and context in brief verbal interactions**. **In text communication**, like the one that happened on this issue, **we don't have these additional communication channels available**, which leaves brief text messages like the one from @trotyl, up for interpretation by the receiver (@Ploppy3). And often these interpretations are incorrect and result in a response that sends the whole conversation into downward spiral.

So where to go from here? I think that the following could help:

- @robwormald could improve his brief FAQ to be more easily used as a reference for further inquiries about ivy's feature completeness.
- @trotyl could be a bit more mindful about how his brief messages could be misinterpreted and try more to avoid that.
- @Ploppy3 could interpret brief messages with a benefit of doubt and not assume bad intent when the message is ambiguous. 

As I said, I see these kinds of interactions quite frequently, and I find it fascinating how different people handle them. I personally use https://www.npr.org/series/423302056/hidden-brain as a great resource to help me understand why is this happening. I highly recommend it.

Now to answer @Ploppy3's original question: ivy is not feature complete yet, so many things still don't work. You can follow the progress at [ivy.angular.io](http://ivy.angular.io). The bootstrap method has indeed changed and currently uses a private API called `ɵrenderComponent` which can be imported from `@angular/core`. We expect it to change by the time ivy is ready for prime time, so please keep in mind that this is [a private api (just as anything else prefixed with `ɵ`)](https://github.com/angular/angular/blob/master/docs/PUBLIC_API.md).
