### ISSUE TITLE
Angular 5 does not work in Augury

### ISSUE THREAD

**Issue by splincode** [angular/angular#22252]
https://github.com/rangle/augury/issues/1255

The task was opened in December last year. And soon the release of Angular 6. Is it planned to release normal dev tools for developers?

**Comment by devoto13** [comment]
The most fun part about your linked issue is "can't reproduce" label and nobody (including you) provided a reproduction, which Augury developers can use to reproduce and consequently fix the problem. And it was more than two months since you opened the issue! Instead of complaining try to ask yourself what you can do to help Augury team to solve your problem.
