### ISSUE TITLE
Docs: Link to stackblitz examples with filename on aio

### ISSUE THREAD

**Issue by StephenFluin** [angular/angular#22357]
## I'm submitting a...

<pre><code>
[X] Documentation feature request
</code></pre>

## Current behavior
When visiting any page with a stackblitz link such as https://angular.io/guide/router there is a link at the top to open a live example like this one: https://angular.io/generated/live-examples/router/stackblitz.html

This also opens main.ts in the editor.

## Expected behavior
It would be nice if the examples linked directly to a more relevant file from the example, such as app-routing.module.ts (https://stackblitz.com/angular/ovkvayplpbm?file=src%2Fapp%2Fapp-routing.module.ts).

## What is the motivation / use case for changing the behavior?
This would make it easier to engage with the examples more quickly, and to see what the example is attempting to demonstrate.

**Comment by gkalpak** [comment]
To add some context:
This is configurable via the `file` property in `stackblitz.json`.
For example, the [example][1] in the [Architecture Overview][2] guide, open `app.module.ts`. (And here is the corrsponding [stackblitz.json][3].)

Currently, if not otherwise specified, a live-example will open at `main.ts` by default.

##
So, we can configure specific files on a per-example basis and we can also change the default value to something else (e.g. `app.component.ts`).

[1]: https://angular.io/generated/live-examples/architecture/stackblitz.html
[2]: https://angular.io/guide/architecture
[3]: https://github.com/angular/angular/blob/6091a954cc3040c062a9f6b4041a496f4bd477e8/aio/content/examples/architecture/stackblitz.json#L8

**Comment by petebacondarwin** [comment]
Has this been implemented? If not, perhaps something that @brandonroberts could look at?

**Comment by brandonroberts** [comment]
Seems likes its already implemented. We could change the default so its not `main.ts` though

**Comment by sonukapoor** [comment]
@gkalpak As discussed offline, I am taking this one.

**Comment by gkalpak** [comment]
To clarify things a bit (for @sonukapoor or any future takers):

- The StackBlitz API (which we use to generate StackBlitz projects on the fly, when a user clicks on a live example link) allows specifying the file to open in the editor by passing a query param.

- If not file is specified, StackBlitz opens a default one. In the past, it used to be `main.ts` and nowadays it seems to be `app.component.ts`.

- Currently, one can specify a file per live example by setting the `"file"` property in the corresponding `stackblitz.json`.

- If `"file"` is not set in `stackblitz.json`, our StackBlitz builder will not specify a file, thus falling back on StackBlitz's default behavior.

##
There are two things that we need to fix as part of this issue imo:

1. Modify our StackBlitz builder to set its own default value (so that we do not rely on StackBlitz's default behavior, which might change unexpectedly). This could be changed somewhere around [here][1].

2. Specify a different `"file"` in `[*.]stackblitz.json` for live examples where it makes sense to use a different file than our default (for the reasons explained in https://github.com/angular/angular/issues/22357#issue-299173835).

[1]: https://github.com/angular/angular/blob/9b9116c79d626b6356f3dfe0d48c9d990ac412a2/aio/tools/stackblitz-builder/builder.js#L119-L144
