### ISSUE TITLE
Opening Auxiliary route removes query params from primary route

### ISSUE THREAD

**Issue by Epenance** [angular/angular#22369]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior
If you stand on a given route that has queryParams and open an auxiliary route on that page, the queryParams will be whiped from the URL.

An example is: The url `http://localhost:4000/filter?color=black&color=blue&brand=Armanito`will change to `http://localhost:4000/filter(dialog:home)` if you add the auxiliary route.

## Expected behavior
Using the same example as before I would expect the query params to stay, maybe looking something like this: `http://localhost:4000/filter(dialog:home)?color=black&color=blue&brand=Armanito` if you add the auxiliary route.

## Minimal reproduction of the problem with instructions
I have made a small example on stackblitz here: https://stackblitz.com/edit/angular-yhyqdq

Simply click the 3 buttons to add query params, and then click the open dialog button. As you see the query params are whiped from the url.

## What is the motivation / use case for changing the behavior?
We have a list of products on an ecommerce solution where we use the query params to set the initial filter state when the page is loaded. If a user makes changes to the filter, the query params are updated. But we also have a auxiliary outlet on the page to open dialogs in, and doing this will whipe the queryparams from the url making the filter page unlinkeable.

## Environment
<pre><code>Angular version: 5.2.X

Browser:
- [x] Chrome (desktop) version XX
- [x] Chrome (Android) version XX
- [x] Chrome (iOS) version XX
- [x] Firefox version XX
- [x] Safari (desktop) version XX
- [x] Safari (iOS) version XX
- [x] IE version XX
- [x] Edge version XX

**Comment by jotatoledo** [comment]
Thats the expected behavior according to the r[outerLink directive docs](https://angular.io/api/router/RouterLink).

Ill try to explain why:

1) Navigation is being triggered by the `routerLink` directive
2) The created instance of `routerLink` directive has no `queryParams`
3) The default `queryParamsHandling` method is take the ones defined in the directive => none
4) When navigation is triggered, the queryParams are handled according to the queryParamsHandling of the directive => use the ones from the directive => none

As it is, what you are trying to archive is **preserve** the `queryParams` in the URL, as the `routerLink` doesnt have any.

So the button decorated should look like:

`<button queryParamsHandling="preserve" [routerLink]="[{outlets: {dialog: 'hello'}}]">Open dialog</button>`

**Comment by Epenance** [comment]
I see, i was not aware of the queryParamsHandling, I tried looking over the documentation, but can't seem to find the possible options for `queryParamsHandling` is there any other that "none", "merge" and "preserve" ?

Thank you very much @jotatoledo

**Comment by jotatoledo** [comment]
Only those, see https://github.com/angular/angular/blob/5.2.6/packages/router/src/config.ts#L330
