### ISSUE TITLE
Cloning an Angular/node project 

### ISSUE THREAD

**Issue by KarlMorgen** [angular/angular#22444]
Hello everyone , 

I'm working on my end of studies project , which will be a project management web application , i found this project which seems very interesting https://github.com/AbhiRoy96/ActiveCollab

I have installed the npm on frontend but i'm stuck on login component couldn't navigate to other components can any body help me please to make it working because I started to study nodejs recently.

Thank you , Have a nice day

**Comment by gkalpak** [comment]
This repo is about the Angular platform. Since the problem you are facing is with the specific project (not Angular itself), you should try opening an issue on their repo (https://github.com/AbhiRoy96/ActiveCollab).

##
BTW, if have questions related to using Angular, you can post a question on [StackOverflow](http://stackoverflow.com/) using tag `angular` or ask on the [Angular channel on Gitter](https://gitter.im/angular/angular).

Good luck with your project 👍
