### ISSUE TITLE
Angular Tutorial "tour of heroes" routing documentation isn't accurate

### ISSUE THREAD

**Issue by Jonathan-Steinmann** [angular/angular#22460]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Feature request
[X] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior
Written documentation and code samples will not work as described in the tutorial.  It begins to breakdown at:

Add RouterOutlet

Error: Template parse errors:
'app-messages' is not a known element:

## Expected behavior
Step-by-step documentation that is accurate and incremental to build a working app

## Minimal reproduction of the problem with instructions
Follow the current tutorial

## What is the motivation / use case for changing the behavior?
A tutorial that is accurate and works for people interested in learning Angular

## Environment
n/a

<pre><code>
Angular version: 5.2.6

Browser:
n/a
 
For Tooling issues:
n/a

Others:
n/a
</code></pre>

**Comment by alexeagle** [comment]
could you provide more detail on how to reproduce this? You don't even say what instructions you are following.

**Comment by Jonathan-Steinmann** [comment]
https://angular.io/tutorial/toh-pt5
Add RouterOutlet

Basically, the whole routes section of this tutorial needs a rework.  My recommendation is to start from the complete code from the previous step, follow the tutorial, and note all of the places it breaks down.

**Comment by kapunahelewong** [comment]
Hey @Jonathan-Steinmann, thanks for bringing this up. I just worked through it and everything worked ok through the "Add RouterOutlet" section, and on through to the end. I've pushed up my version of the [Tour of Heroes Routing Test](https://github.com/kapunahelewong/toh-routing-test) that I built as I went through the instructions for your reference. I started with the completed version from the Services step. 

Could it be that somewhere in there that the instructions might not have been specific enough? If you'd like to compare what I've built to yours and let me know where you spot a difference, I can make sure the docs team is looped in so they can edit the steps if necessary.

**Comment by ajonesmulaire** [comment]
I just ran into this issue myself!

The tutorial doesn't leave precise instructions for including the AppRoutingModule in app.module.ts

Add instructions to insert 

import { AppRoutingModule }     from './app-routing.module';

and in @NgModule({
               imports:[
                  AppRoutingModule]
               ]})

Hope that helps!

**Comment by jenniferfell** [comment]
We recently went through the tutorial again to verify it with Angular 6.0.0, and everything worked for us. 

It looks like the correct instructions are here: 
https://angular.io/tutorial/toh-pt5#add-the-approutingmodule

ng generate module app-routing --flat --module=app
--flat puts the file in src/app instead of its own folder.
--module=app tells the CLI to register it in the imports array of the AppModule.

The doc could probably be more clear at this point by showing how the CLI changes the AppModule. app.module.ts is in the final files review, and it's correct there, but you make a good point that the doc could be more explicit about when "import { AppRoutingModule } from './app-routing.module';" is inserted. 

@chembu : When you get a chance, please review and confirm that the instructions work. If so, then let's change the label to "type: feature" to add more clarification on this point. Thanks!

**Comment by jenniferfell** [comment]
docsarea=tutorial
filename=https://angular.io/tutorial/toh-pt5#add-the-approutingmodule

**Comment by chembu** [comment]
Reviewed Routing section of the tutorial. The step by step instruction work. Also, when you are using to generate the module, it automatically imports app routing module and adds it to the imports array in app-module.ts.
