### ISSUE TITLE
iterate maps with ng-for

### ISSUE THREAD

**Issue by rolandjitsu** [angular/angular#2246]
I am trying to iterate over  [Map](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Map) values with the built in `ng-for`, but I can see that for some reason it is not working.

In the specs, you can iterate over a Map iterable with:
```js
let map = new Map();
let values = map.values();
for (let item of values) {
    console.log(item);
}
```

And none of the ES5 standard `for (...)`/`for (... in ...)` will work with that.

Does the built in `ng-for` actually support iterating over maps?

**Comment by mhevery** [comment]
Maps have no orders in keys and hence they iteration is unpredictable. This was supported in ng1, but we think it was a  mistake and will not be supported in NG2

The plan is to have a `mapToIterable` pipe

`<div *ng-for"var item of map | mapToIterable">`

**Comment by rolandjitsu** [comment]
@mhevery sounds fair enough. Can I already make use of a pipe inside `ng-for` that would transform that map into an array for instance? Or that has not been implemented yet?

**Comment by gdi2290** [comment]
@rolandjitsu this is kinda supported if you do it like this example
```html
  <ul>
    <li *ng-for="var item of myMap.values(); var i = index">
    {{ item | json }} {{ i | json }}
    </il>
  </ul>
  <ul>
    <li *ng-for="var item of myMap.entries(); var i = index">
    {{ item | json }} {{ i | json }}
    <br>
    {{ item[0] | json }} {{ item[1] | json }}
    </il>
  </ul>
```
```typescript
@Component({ selector: 'app' })
@View({ directives: [NgFor], template: template })
export class App {
  myMap: any;
  constructor( ) {
    this.myMap = new Map();
    this.myMap.set('Some Key', 'Some Value');
  }
}
```

@mhevery inside of `*ng-for` this doesn't work `var i = index; var mykey=item[0]; var value=item[1]`
```html
<li *ng-for="var item of myMap.entries(); var i = index; var mykey=item[0]; var value=item[1]">
  {{ key | json }}: {{ value | json }}
</li>
```
compiler blows up when it sees `[`. This example doesn't work with `JitChangeDetection` with `changeDetection: ON_PUSH` but the default one is fine. 

Oddly enough, the original example works in `changeDetection: ON_PUSH` and `JitChangeDetection` until ChangeDetection does another tick then it removes them
```
<li *ng-for="var item of values">

let map = new Map();
map.set('Some Key', 'Some Value');
this.values = map.values();
```

**Comment by rolandjitsu** [comment]
@gdi2290 I experience the same thing, it renders them but then they're gone.

**P.S.**:I do not fully understand the internals of the change detection (like when the next tick occurs).

**Comment by rosendi** [comment]
Can we reopen this issue? Iterating over `Map` and `Set` is a very common operation. Maybe `NgFor` could be a little bit smarter.

Before

```
items = new Map();

<li *ng-for="#item of items | toArray">...</li>
  ket: {{ item[0] }} {{ item[1].name }} {{ item[1].desc }}
</li>
```

or using wrapper (@mhevery comment https://github.com/angular/angular/issues/909#issuecomment-78205115)

```
<li *ng-for="#item of items | toArray">...</li>
  ket: {{ item.key }} {{ item.value.name }} {{ item.value.desc }}
</li>
```

After

```
items = new Map();

<li *ng-for="#item of items; #k = key">...</li>
  {{ i }} {{ item.name }} {{ item.desc }}
</li>
```

```
items = [];

<li *ng-for="#item of items; #i = index">...</li>
  {{ i }} {{ item.name }} {{ item.desc }}
</li>
```

**Comment by gdi2290** [comment]
Whenever you mutate the component, change the value of one of it's properties, then angular's change detection will be able to detect the changes in the component tree. If you want to learn more about [ChangeDetection](http://victorsavkin.com/post/110170125256/change-detection-in-angular-2) that's a post by Victor Savkin. I'm not sure why the side-effect above happens with JIT

**Comment by e-oz** [comment]
Not supporting this is a mistake in ng2. It's a *very* often case when you don't care about order, you just need indexes of object for direct access (to display value in "View" mode, such as `{{someList[someModel.id]}}`), and to show options for select, `<option *ng-for="#item of someList" [value]="item.id">{{item.title}}</option>`.

**Comment by obscur666** [comment]
try to use this pipe

    @Pipe({ name: 'values',  pure: false })
    export class ValuesPipe implements PipeTransform {
      transform(value: any, args: any[] = null): any {
        return Object.keys(value).map(key => value[key]);
      }
    }

    <div *ng-for="#value of object | values"> </div>

**Comment by e-oz** [comment]
@obscur666 thank you. I did it already, but it means we multiply *2 size of list in memory and had to use more lines of code.

**Comment by marcj** [comment]
> Not supporting this is a mistake in ng2

Jupp, especially when you take into consideration that all current modern browser sustain the key order of objects (except if you use numbers as key, but that is known). Libraries and developer are used to work with objects that way (especially for configurations). Angular's decision is based on theory, but the practice tells us something different. They should rather adjust the Javascript specification so Browsers officially aren't allowed to change the order *theoretically* anymore. ;)

**Comment by mhevery** [comment]
this can be better supported by a pipe which converts an object into array
and sorts the keys.

**Comment by jhiemer** [comment]
@obscur666 when using your Pipe I ran into:

`Expression 'entity.props | values in Component@140:26' has changed after it was checked.`

This whole tweaking really feels a bit buggy in Angular 2. Are there more solid approaches?

**Comment by mhevery** [comment]
@jhiemer if it is a bug, then it should be filed, and fixed, rather than worked around it.

**Comment by jhiemer** [comment]
@mhevery the thing is, reading through other tickets this does not seem to be a bug. When I get an object and transform it into a array I need to return a new object, which results into the error. 

http://stackoverflow.com/questions/34313743/expressionchangedafterithasbeencheckedexception-since-angular-2-beta

This behaviour is described in different tickets/stackoverflow entries.

**Comment by mhevery** [comment]
@vsavkin is working on a less strong dev mode, which will treat this as OK. But yes, in the strictest sense the pipe should make sure that it returns the same array.

**Comment by jhiemer** [comment]
@mhevery that would help a lot. The problem is see is getting an object with properties and returning an array. Normally I would tend to return a new array instead of changing the keys in the existing object. But that's definitely a matter of taste.

**Comment by laco0416** [comment]
@mhevery Hi.
I have trouble about a migration from `ng-repeat` to `ngFor`. 
If so it is the design, I think that a solution for the migration also should be in the design. I wrote a pipe, `objectToIterable`, for this. But it's hacky.
Shouldn't something for smooth migration be provided by the library?

**Comment by gdi2290** [comment]
I think the current design is fine. What's going on is that `ngFor` is enforcing the shape of your collection. The problem with `ng-repeat` was that it allowed for both objects and map which allowed more developers to shoot themselves in the foot (more often when they are concerns with the order). In Angular 1 a lot of the "perf" problems were due to developers overloading `ng-repeat` without considering what is really going on. With `ng-repeat` what you're doing in inverting control over your ViewModel to the directives (view) to compose behavior before you refactor into our own directive. With Angular 1 nearly no one took the time to take the next step of refactoring into components. So what `ngFor` is doing, this time, around is enforcing the best practices currently in Angular 1 today of managing the ViewModel in the component (controller) before passing it to the view. While this may hurt migration, it forces developers down the correct path. Some developers even go so far as to say if Angular 1 didn't have `ng-repeat` then we wouldn't have any performance problems since developers would have to think about managing their collections. This change may also hurt prototyping which was one of Angular 1's strongest strength but someone could also create a `ng-repeat` directive which has the same API as

**Comment by JesusisFreedom** [comment]
Maps iterate in order per https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Map
@mhevery

**Comment by colinjlacy** [comment]
If anyone's interested, I wrote up a blog post following the suggested Pipe solution made by @mhevery: https://webcake.co/object-properties-in-angular-2s-ngfor/

**Comment by user414** [comment]
Ran into this issue, and used the solution posted somewhere since the pipe by @mhevery seem to have the same downside as here
https://github.com/angular/angular/issues/6392

which is it makes it read only. Instead just used something that was suggested somewhere else, sorry can't find where. 

Add something like this in your class

```
@Input() jsonObject: Object;
...
keys() : Array<string> {
    return Object.keys(this.jsonObject);
}
```
Do something like this in the template
```
<template ngFor #currentKey [ngForOf]="keys()" #i="index">
      <div><strong>{{currentKey}}:</strong> {{jsonObject[currentKey]}}</div>
</template>
```

**Comment by IsaacBorrero** [comment]
Just checking if the mapToIterable pipe has been added to ng2?  Is there an issue item that I can track to get status updates?

**Comment by mhevery** [comment]
@IsaacBorrero It has not, could you like to make a PR?

**Comment by IsaacBorrero** [comment]
@mhevery I apologize, but what does that mean?  Please let me know and I will gladly do it...

**Comment by mhevery** [comment]
https://help.github.com/articles/creating-a-pull-request/

**Comment by amcdnl** [comment]
@mhevery @IsaacBorrero - here is what I am using - https://gist.github.com/amcdnl/202596c5b85cc66d7002d10bde3ab514

**Comment by pstephenwille** [comment]
This seems like a huge glitch.  Is it that ordering is inconsistent, in which case, does that matter? Or that looping at all is problematic?    At the minimum, I'd expect a default pipe to be available.

**Comment by svdb0** [comment]
@mhevery 
For what it's worth, as opposed to the order of properties in an object, the order of the elements of a Map has been strictly defined from the first version of ECMAScript which introduced it.

The standard uses a list type to describe it; adding a new element appends it to the end of the list of the key-value pairs, and changing the value of an element leaves the order intact.
See http://www.ecma-international.org/ecma-262/6.0/#sec-map.prototype.set for the Map.prototype.set() function. Other operations use the same list representation.

If there are no other reasons than the perceived inconsistent ordering, considering that iterating through Maps would be very convenient, maybe another look at this could be justified?

**Comment by megalucio** [comment]
So, for when are we going to have a mapToIterable pipe as a default in the angular2 commons?

**Comment by IsaacBorrero** [comment]
I agree with @megalucio ... Really looking forward to this, as it would allow me to take advantage of ES6 and build more robust collections.

**Comment by e-oz** [comment]
> What's going on is that ngFor is enforcing the developer to shape the collection correctly.

> So what ngFor is doing, this time around, is enforcing best practices currently discovered

Not in this case. Only thing we are doing in this case - write more code without any benefits.

**Comment by gdi2290** [comment]
(speaking for myself)
I good example of where we are reverting control over the ViewModel from a developer concern to the template is in this example. (assuming we have something like `keys` pipe)
```html
<ul>
  <li *ngFor="let key of asyncItems$ | async | keys">
    ?
  </li>
</ul>
```
`|async` is managing the subscription of the `asyncItems$` Observable and value that comes out of it over time. After the value is emitted we convert that Model into a ViewModel which is the keys of the Model. The problem occurs when you're trying to grab the Model.
```html
<ul>
  <li *ngFor="let key of asyncItems$ | async | keys">
    {{ key }} : {{ (asyncItems$ | async)[key] }}
  </li>
</ul>
```
To get the Model that the async pipe created in the template you now have to do the same operation for the template to grab the same value. Another problem occurs that the developer is unaware of and that the `asyncItems$` is being subscribed more than once here. For each `|async` request you're creating a new subscription. You can "fix" this with `asyncItems$` being telling the Observable it's a multicast Observable via `.share()`. Each time you subscribe to the same Observable you will receive the same reference of the first value.

If the developer controls the Model/ViewModel then we would create the subscription in our component and create a reference to our ViewModel from our  Observable
```typescript
@Component({
  template: `
<ul>
  <li *ngFor="let key of viewModel">
    {{ key }} : {{ model[key] }}
  </li>
</ul>
`
})
class Home {
  asyncItems$ = Observable.of(1, 2, 3, 4);
  model = {};
  viewModel = [];
  sub;
  constructor() {
    this.sub = asyncItems$.subscribe(model => {
      this.model = model;
      this.viewModel = Object.keys(model);
    });
  }
}
```
Notice how we're now able to reason about what's going on in our template since it's simpler to understand. We are handling the complexity of the async value in our component where we have full control over what we expose to our template. If we want to determine the order of our Model we would just create the order in the component either before the subscribe or after.

**Comment by coli** [comment]
let key of Object.keys(hash)

**Comment by pdavin** [comment]
Should this issue be closed?  On May 31 2015 @mhevery commented "The plan is to have a mapToIterable pipe". Is that still the plan?  If that work isn't being tracked in this (closed) issue, is there another place I can follow along?  Having it in ng2 core would be better than the many third party implementations getting propagated I think.
Thanks.

**Comment by DzmitryShylovich** [comment]
@pdavin https://github.com/angular/angular/pull/11319

**Comment by e-cloud** [comment]
I don't think #11319 fits for Map. [Keyspipe](https://github.com/harunurhan/angular/blob/7a4ee77071a62f062aa6c8a4c8f64c9b7a6acddf/modules/%40angular/common/src/pipes/keys_pipe.ts#L25) is only for Object. You can't iterate keys of map through `Object.keys()`.

```js
var map = new Map()
map.set(0, 1)
Object.keys(map) // output: []
```

**Comment by dlinx** [comment]
Map have its own `keys` method. Refer [this](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Map/keys).

```
var map = new Map()
map.set(0, 1);
map.keys() // output: 0
```

**Comment by e-cloud** [comment]
@dlinx, ironically, what you've post just proves my thought.

the output of `map.keys()` is an array. Keyspipe does't get its place.

**Comment by trotyl** [comment]
@e-cloud The output of `map.keys()` is not an Array, it's an Iterator.

**Comment by e-cloud** [comment]
you're right, sorry for my rudeness.

**Comment by shral** [comment]
I would expect iterating throw a Map like this:

            <div *ngFor="let key of myMap.keys()">
                key:{{key}} <br/>
                value: {{myMap.get(key)}}
            </div>

and that's working (I'm seeing the list) except that I'm having an "ExpressionChangedAfterItHasBeenCheckedError" error.

Similarly to that, I solved Iterating throw the Object with *ngFor by binding the "Object" to the component:

      @Component(...)
      export class MyComponent {
           Object = Object;
       //The rest of the Code....
       }
Than in my Template:

       <div *ngFor="let key of Object.keys(myObject)">
                key:{{key}} <br/>
                value: {{myObject[key]}}
         </div>
What do you guys think about this solution? I would expect to bee faster than the pipe solution but that need to bee verifyed.

**Comment by sk29110** [comment]
Why so complicate to iterate over map? my code seems not working.

component.ts
this.mapValue = new Map<number, string>();
this.mapValue.set(1, 'Some Value 3');
this.mapValue.set(2, 'Some Value 2');

html
<ul>
    <li *ngFor="let key of model.mapValue">
        {{key}}
    </li>
</ul>

result is displaying empty li.

**Comment by moravcik** [comment]
@mhevery 
As it was already said, the original question was about ES6 Map, which is ordered by its specification. You were describing unpredictable ordering of object keys , which is different case. 

Is iterating with `*ngFor` supported for ES6 Maps, or more generally, on objects implementing `[Symbol.iterator()]` ?

**Comment by trumbitta** [comment]
I'm doing it like this:

```TypeScript
this.vehicleTypes = vehicleTypesMap; // A map defined elsewhere
this.vehicleTypesKeys = Array.from(this.vehicleTypes.keys());
```

```HTML
<select>
    <option *ngFor="let type of vehicleTypesKeys" [value]="type">{{ vehicleTypes.get(type) }}</option>
</select>
```

**Comment by dalu** [comment]
This is very shortsighted, like so many things in new angular.
That means you're forcing a certain data model on every endpoint, regardless wether it's sensible or not.

**Comment by gordol** [comment]
this is utterly ridiculous
