### ISSUE TITLE
Validators default methods like required should return object including error message for easy translation

### ISSUE THREAD

**Issue by systemaker** [angular/angular#22478]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[x ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior

In package forms, in Validators class, methods like Required are returning a boolean or null object :
    static required(control: AbstractControl): ValidationErrors|null {
        return isEmptyInputValue(control.value) ? {'required': true} : null;
      }

## Expected behavior

a method for default validators like required should return an object including error message which can be translated like this way : 

    static required(control: AbstractControl): ValidationErrors | null {
        return isEmptyInputValue(control.value) ? { 'required': 'value is required' } : null;
    }

## What is the motivation / use case for changing the behavior?

For easy translation of invalid messages in template forms

## Environment

<pre><code>
Angular version: X.Y.Z

Browser:
- [ ] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: XX  
- Platform:  

Others:

</code></pre>

**Comment by mlc-mlapis** [comment]
@systemaker ... there are hundreds of different scenarios what data structure could be returned from validators ... and that could be dependent on concrete requirements of real apps and that's why Angular validator API defines just returning `null` (success) or an object like `{ 'anyValidatorName': any }` (error) where `any` could be just trivial value or a structural object with properties like `errorcode`, `errormesage` ... and it is totally on you how you would structure it. It is also supposed that you will wrap Angular standard validators to your own custom validators to keep returned values consistent and understandable cross your app.

**Comment by kara** [comment]
Agree with @mlc-mlapis on this one.  Custom validators would be the way to go if you want to customize these.
