### ISSUE TITLE
Add the ability to edit the page on the site

### ISSUE THREAD

**Issue by splincode** [angular/angular#22521]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[x] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

Similarly it is done on the Bazel site

![image](https://user-images.githubusercontent.com/12021443/36845230-f831f28e-1d66-11e8-9f8b-47641afc527f.png)

If you are developing a localization module, why it can not be applied on your site. So that you can write translations right here?

**Comment by gkalpak** [comment]
This is already available for API docs (and we are working on improving it - see #22379) and it is on our plans to implement it for guides as well.

Regarding translation, it is not so easy (because the content is auto-generated from source code comments and `.md` files checked into the angular/angular repo). We haven't come up with a good process for coordinating translations yet, but it is definitely something we are interested in (see #20542 for discussion).
