### ISSUE TITLE
[ngUpgrade] "[$rootScope:inprog] $digest already in progress" error when navigate to Angular2+ component from AngularJS component

### ISSUE THREAD

**Issue by alangria** [angular/angular#22576]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[X ] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior
"Digest in progress" is thrown when trying to navigate to Angular2+ component from AngularJS component. This issue is observed in **Firefox, IE and Edge** but not in Chrome.
 
Our app is a hybrid application:
- The majority components are still in AngularJS <version 1.5.8>
- We have shell component are run in Angular <version 5.1.1>

We are seeing Angular unhandled exception when navigating to Angular component from AngularJS component. 
The line of code which triggers the error is: from AngularJS
**$window.history.go(-1)** 

After the exception, all the animations seems to be affected and performance of the app degrade significantly.

Stack trace:
beginPhase (appportal.dependencies.externals.bundle.js#28113)

digest (appportal.dependencies.externals.bundle.js#27541)

subscription (web.bundle.js#45745)

schedulerFn (web.bundle.js#4930)

__tryOrUnsub (web.bundle.js#19087)

next (web.bundle.js#19034)
_next (web.bundle.js#18975)

next (web.bundle.js#18939)

next (web.bundle.js#26066)

emit (web.bundle.js#4898)

checkStable (web.bundle.js#5296)

onLeave (web.bundle.js#5375)

onInvokeTask (web.bundle.js#5325)

invokeTask (web.bundle.js#90098)

runTask (web.bundle.js#89866)

invokeTask (web.bundle.js#90173)

invokeTask (web.bundle.js#91214)

globalZoneAwareCallback (web.bundle.js#91251)

**navigateBack (appportal.web.bundle.js#23571)**

applyChanges (settings.js#3717)

applyChanges (settings.js#3701)

fn (SOURCEsource474#4)

expensiveCheckFn (appportal.dependencies.externals.bundle.js#25960)

callback (appportal.dependencies.externals.bundle.js#36327)

eval (appportal.dependencies.externals.bundle.js#27750)

apply (appportal.dependencies.externals.bundle.js#27850)

ngEventHandler (appportal.dependencies.externals.bundle.js#36332)

dispatch (appportal.dependencies.externals.bundle.js#4737)

handle (appportal.dependencies.externals.bundle.js#4550)

invokeTask (web.bundle.js#90099)

runTask (web.bundle.js#89866)

invokeTask (web.bundle.js#90173)

invokeTask (web.bundle.js#91214)

globalZoneAwareCallback (web.bundle.js#91240)

## Expected behavior

No unhandled exception 

## Environment

<pre><code>
Angular version: 5.1.1

The issue is still repro after we upgrade both Angular and AngularJS to the latest version

Browser:
- [ ] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ X] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ X] IE version XX
- [ X] Edge version XX
 
For Tooling issues:
- Node version: XX  
- Platform:  

Others:

</code></pre>

**Comment by gkalpak** [comment]
Thanks for reporting this issue. However, you didn't provide sufficient information for us to understand and reproduce the problem. Please check out [our submission guidelines](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-submitting-an-issue) to understand why we can't act on issues that are lacking important information.

More specifically, you didn't provide a way for us to reproduce the problem.

If the problem still persists, please file a new issue and ensure you provide all of the required information when filling out the issue template.

##
FWIW, similar issues have been reported in the past. In all cases, it turned out that the issue was in the application (or 3rd party) code. So, it is impossible to indentify whether this is an issue in `ngUpgrade` (or suggest a way to fix it) without a minimal reproduction. 

I also know that such issues (which often involve racing conditions) are often hard to reproduce in a minimal demo, but unfortunately there is no way to investigate them without a way to reproduce them.

**Comment by jbedard** [comment]
@gkalpak I've seen errors similar to this in logs for a long time and never been able to figure it out but I think I finally have repo steps.

It seems like this *sometimes* occurs if you invoke nested `NgZone.run` calls. For example I often (actually always) run `NgZone.runOutsideAngular` around `$.on` / `addEventListener` calls within my AngularJS app, mainly because those jQuery/native events were used specifically to escape the `$digest`. However that means sometimes we must manually invoke `$digest` where we should probably also re-enter the `NgZone`. However I don't (yet) understand why this only *sometimes* reproduces, maybe only the first time the nested calls occur?

See https://stackblitz.com/edit/upgrade-nested-events

**Comment by jbedard** [comment]
A little more info for my specific case:
1) DOM event listeners are setup in the parent zone to avoid $digest
2) DOM event listeners sometimes invoke $apply + enter the angular zone
3) leaving the angular zone invokes $apply again, while still within the $apply invoked in the parent zone

This could probably be avoided on my part by changing how step 2 is done, but this might be a valid case for ng-upgrade handling this...

**Comment by gkalpak** [comment]
I think this works as expected wrt your usecase :grin:
Calling `ngZone.run()` during a `$digest` that is running outside the Angular zone will have the effect you describe. In your case, wouldn't it be fine to just call `ngZone.run()` (and let `$digest()` be called `onMicrotaskEmpty`)?

BTW, the reason it only happens the first time, is described in #24680. 
(Essentially, throwing inside `onMicrotaskEmpty.subscribe(() => $rootScope.$digest())`, unsubscribes, so there are no more digests `onMicrotaskEmpty`.

**Comment by jbedard** [comment]
I might have to disagree :grin: 

What is wrong with calling `ngZone.run()` during a `$digest`? That sounds valid to me, and if you just happen to be outside the ngZone at that point then this error occurs...

In my case $apply + enter the Angular zone (+ running the DOM listeners outside the Angular zone) are all done in completely separated areas of the app/code. This case just happens to put them all together.

Another example...

```
function myAngularJSDirectiveLink() {
   ngZone.runOutsideAngular(() =>         //for performance
       $element.on("mouseenter", () => {  //use jQuery.on instead of ng-mouseenter for performance
           if (Math.random() = 0.42) {    //in some cases we need CD
              $scope.$apply(() => {
                $element.trigger("event-that-Angular-might-also-listen-to-in-the-ngZone");
              });
           }
       });
  });
}
```
(I think that would do it...)

**Comment by gkalpak** [comment]
> What is wrong with calling `ngZone.run()` during a `$digest`?

Generally, nothing. The problem happens when you manually escape the Angular zone.
`ngUpgrade` (non-lite) operates under the assumption that AngularJS runs inside the Angular zone. If you manually escape the zone, you are on your own 😛

> if you just happen to be outside the ngZone at that point

This doesn't "just happen". You have manually escape it (or use `jsonp` 😛).

##
In general, when you manually escape the zone+digest (for performance reasons) and then decide to run a digest, it is "in the spirit" of `ngUpgrade` (non-lite) to also trigger CD in Angular (i.e re-enter the zone).

So, it does sound like a good idea to wrap your `$apply()` in `ngZone.run()` (when manually escaped the zone). This way, you don't have to worry about what might happen in other parts of the app.

That said, I am not strongly opposed to switching to a "safe apply" `onMicrotaskEmpty` :wink:
<sub>(You might have to convince @petebacondarwin, though 😛 </sub>

**Comment by jbedard** [comment]
> So, it does sound like a good idea to wrap your `$apply()` in `ngZone.run()`

But for me the `$apply` and `ngZone.run` are completely unrelated. The `$apply` is in legacy AngularJS code that I don't want to touch, the `ngZone.run` is done automatically by by Angular/zone.js because a callback is invoked which was registered while in the `ngZone` (I think, it has been a while since I looked into this). This is what I was trying to show in the `trigger("event-that-Angular-might-also-listen-to-in-the-ngZone")` example above.

**Comment by gkalpak** [comment]
`ngZone.run()` inside an `ndZone.run()` does not trigger `onMicrotaskEmpty`. So, if you wrapped `$apply()` inside `ngZone.run()` then, `ngUpgrade` should not try to trigger another digest until `$apply()` is over.

**Comment by jbedard** [comment]
But my case is just `ngZone.run` invoked (indirectly) within `$apply`.  The `$apply` is in legacy code that knows nothing about zones/Angular...

**Comment by gkalpak** [comment]
I see. Is this because you monkey-patch jqLite/jQuery `.on()`?

**Comment by jbedard** [comment]
Yeah... because most of my uses of jqLite/jQuery `.on` were specifically to avoid the digest, so with ng-upgrade that means we must also avoid the ngZone. I also decorated `.$apply` and `.$digest` to run in the ngZone, so when one of those `.on` methods does do a digest it does it in the ngZone.

I think https://stackblitz.com/edit/upgrade-nested-events-jbmkrf shows this quite well (note that this link is slightly different then above, I think making it more like my app - just changing the apply/zone.run order in one spot).  Note that in my app all the `ngZone.*` calls are done elsewhere (the monkey patching).

Isn't this stackblitz example valid though?

**Comment by gkalpak** [comment]
But that latest link does not show the problem, does it?
<sub>
BTW, none of what you do with `ngUpgrade` is valid 😛
You are totally abusing your deep AngularJS knowledge 🤓 
</sub>

**Comment by jbedard** [comment]
Bah, I swear that was throwing this morning (but I was in a hurry!). See the first version then: https://stackblitz.com/edit/upgrade-nested-events

If you forget about my magic hacks and just look at that link... why isn't that valid? I think a user should be able to invoke `ngZone.*` however they want, in whatever order/nested mess they want...
