### ISSUE TITLE
Concept of Angular (ngZone + ChangeDetection) better than concept React, Vue (Virtual DOM)? 

### ISSUE THREAD

**Issue by splincode** [angular/angular#22587]
## I'm submitting a...

<pre><code>[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[x] Feature request
[x] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see 
</code></pre>

**I. Introduction**

I'm wildly sorry that I'm asking this question here. However, I do not know who can normally answer it. I wrote on many forums and chats (gitter.im/angular/angular). But no one can answer, maybe there is no answer to this question.  However, I preparing for speeches at conferences or meetup on Angular. I'm then constantly asked what is the advantage over the most popular frameworks. And people are just interested in the performance and ease of application optimization. I know Angular Ivy is coming out, but it's just an improved render function like React, but not a fundamental approach.

**II. Concept Prospects (documentation)**

Once I was answered to this comparison: "is chocolate ice cream better than vanilla ice cream?". But in my opinion this is not serious. To popularize Angular, I must somehow understand whether the concept  `ngZone + ChangeDetection` is an architectural failure or success?

@mhevery @IgorMinar @bradlygreen Is there any roadmap about this?

Joseph Liccini (Miscrosoft):

> I do see this question 'Why not a Virtual DOM in Angular?' quite often. Every few months or so it comes up. Might be worth doing a Framework design and comparison in Angular.io so people know why VDOM doesn't make sense for Angular's implementation. VueJS does a page in their docs: https://vuejs.org/v2/guide/comparison.html#ad

**III. Improved perfomance**

1. I see that the benchmarks are almost the same, but I would like to see coordinative breakthroughs.

![image](https://user-images.githubusercontent.com/12021443/36972468-385ed9fa-2080-11e8-8d4b-9cbc944e596b.png)

2. We know that for large applications, two-way data binding slows the application, why can not I just do it for the whole application, and not write for each component (if there are a lot of them)?

Why it is impossible to make on all application setting about disabling two-way data binding? How can this be done with the simplest preserveWhitespaces.

```json5
{
// ..
"angularCompilerOptions": {
    "preserveWhitespaces": false,
    "preserveCdDefaultStrategy": false, // add option default
 }
}
```

preserveCdDefaultStrategy (false) the default value strategy OnPush 

@mgechev on the contrary encourages the use of OnPush

**Comment by trotyl** [comment]
> Concept of Angular (ngZone + ChangeDetection) better than concept React, Vue (Virtual DOM)?

+ If you call something "view" and diff it, then it's Virtual DOM.
+ If you call something "view model" and diff it, then it's Dirty checking.

(Even they could be produce totally exact same call stacks).

Also virtual DOM is not a single implementation, even React and Vue are using quite different triggering mechanism. (manual `setState` invocation in React and intercepted `Object.definedProperty` in Vue).

Angular is also using `Object.definedProperty` in [`OnChange` life-cycle hook](https://github.com/angular/angular/blob/4f609687044a5b7cd15f796bce948e9385b70f7a/packages/core/src/render3/definition.ts#L92-L106) (rather than diffing) starts from Ivy.

> To popularize Angular, I must somehow understand whether the concept ngZone + ChangeDetection is an architectural failure or success?

`must is wrong, `Zone.js is not (officially) required [since `5.0.0-rc.0`](https://github.com/angular/angular/commit/344a5ca5452bc01a1e5ff8f04aa7a283ce4134cf), technically not using Zone.js is [supported]((https://github.com/krausest/js-framework-benchmark/blob/e8df2a52b3cb4a5213d97c9065da8043de04cb2f/angular-v5.2.2-no-zone-keyed/src/main.ts#L5-L12)) even before that.

But using `Zone.js` is the easiest way to combine with imperative state assignment. Otherwise you'll need to trigger the change detection [manually or making it reactive](https://stackblitz.com/edit/angular-no-zones?file=app%2Fapp.component.ts).

There's also a conventional API called `setState` to combine manual change detection triggering and state change, which is natively supported in [Dart version](https://github.com/dart-lang/angular/blob/94d48b5bce2aced72ca836986887b49dfb578125/angular/lib/src/core/change_detection/component_state.dart#L17-L20), also can be emulated in [TypeScript version](https://stackblitz.com/edit/angular-no-zones-setstate?file=app%2Fapp.component.ts). Some people would also calling it "reactive" even if it's still triggered manually.

The true reactive in Angular is using event stream (RxJS for now), theoretically it should works well without Zone.js (with `async` pipe), but actually not due to current scheduling implementation. It's already solved in Ivy and likely would be [bring back to current view engine](https://github.com/angular/angular/pull/22018#issuecomment-365680798).

> I see that the benchmarks are almost the same, but I would like to see coordinative breakthroughs.

The only defect as you can see if the diffing implementation, that's already tracked on https://github.com/angular/angular/issues/18178.

> We know that for large applications, two-way data binding slows the application

The so-called "two-way data binding" is only a syntactic sugar and does not exist in runtime. Angular will force one-way data flow by raising `ExpressionChangedAfterItHasBeenCheckedError` in dev mode.

**Comment by sandangel** [comment]
I really really want to give both @trotyl @splincode  a hug for bringing this out. This is freaking awesome.. 💕 💕 💕 💕 💕 💕 💕

**Comment by sandangel** [comment]
But I think the new [`time slicing` and `suspend`](https://reactjs.org/blog/2018/03/01/sneak-peek-beyond-react-16.html) concept  in React will make a big different in performance benchmark. Is that feasible with Ivy ?

**Comment by trotyl** [comment]
@sandangel The [goal](https://blog.angular.io/trip-report-from-ngatlanta-angulars-roadmap-inclusion-and-more-b6c8bae85417#611a) of (first version) Ivy is not to bring new features, better to track #19030.

**Comment by Toxicable** [comment]
@splincode Just like to bring your attention to the benchmarks you linked.
Just to clarify; they're know as microbenchmarks - measuring the framework at a very small level, how it handles primitive operators. I believe that there is a flaw in this becasue it does not show how a framework works at scale.
Sure, there's some merit to to them, since if it's wildly slow at the micro level it will unlikely scale very well.

The question I think you should be asking when it comes to performance is: at what rate does the time to render scale as the amount of DOM nodes increase for the same set of changes.
If the framework has no way to only check a subset of the DOM then there is no way it will scale in a sub-linear fashion, meaning as nodes increase so does render time, but what you really want is for render time to remain constant with an increasing number of nodes for the same set of changes.

Im not going to compared the frameworks on this since I don't know the others well enough to make a reasonable comparison on the merits of how they implemented what I've talked about above.
But I do believe this is a far better metric to look at for real world applications than microbenchmarks.

**Comment by splincode** [comment]
@trotyl @Toxicable If we are talking about real applications, then for some reason, comparing the same Angular 4+ things are not so good. With what it can be connected?

https://github.com/gothinkster/angular-realworld-example-app

![image](https://user-images.githubusercontent.com/12021443/36989910-21d37540-20b4-11e8-8798-dfe2fc9b0d9d.png)

https://medium.freecodecamp.org/a-real-world-comparison-of-front-end-frameworks-with-benchmarks-e1cb62fd526c

**Comment by IgorMinar** [comment]
@splincode that benchmark is flawed - the Angular app wasn't minified and it's running in dev mode: https://angular2.realworld.io/main.bundle.js

<img width="633" alt="screen shot 2018-03-06 at 10 22 29 pm" src="https://user-images.githubusercontent.com/216296/37076785-e77ecc6c-218c-11e8-8db6-033e881b4377.png">

----

Angular's dev builds are typically bigger than others, because we provide much more functionality out of the box. It's during the build step, that we remove the pieces that were not actually used. This works as expected because we aim to provide great developer experience and great user experience. Achieving that without a build step is not possible with today's technology. So one should never use dev builds to measure metrics related to user experience. It's just really not a useful comparison.

**Comment by jotatoledo** [comment]
> I think the article lied and they show us the JIT mode, but why then such modes are better for other frameworks, very strange.

Are they though? Considering that some of the live demos are running on dev mode, the meaning of the metrics could indeed be inverted:

- Size: larger is better, as it potentially means that dev tools + other goodies for dev experience were packaged.
- Performance (first paint): longer is better, meaning that stronger checks are being run on the background

**Comment by splincode** [comment]
@IgorMinar Why then the Angular team does not give a refutation? The network has a lot of bad articles with benchmarks, why your team on your blog will not analyze the production modes of all frameworks (on heroku for example), so that you can always send newcomers to study this moment.

**Comment by mlc-mlapis** [comment]
@splincode ... hmm, it is necessary to ask first for whom it would be determined and if it is worth to do it (because it is a complex thing) and mainly what are the cost for maintaining the permanent actual status of the whole ... because many things are changed every day.

**Comment by splincode** [comment]
Well, if we are looking for prod mode, will the new render provide an improved experience (ivy) for us?

1. angular.io

![image](https://user-images.githubusercontent.com/12021443/37102405-d203fa72-2238-11e8-9697-85b2f483b51e.png)

2. vuejs.org

![image](https://user-images.githubusercontent.com/12021443/37102990-40dbf192-223a-11e8-886f-0483eb78f6d7.png)

3. https://reactjs.org/

![image](https://user-images.githubusercontent.com/12021443/37103058-682253cc-223a-11e8-9139-9233960ea2f6.png)

ReactJS very quickly booted and rendered the page

**Comment by Toxicable** [comment]
@splincode You're comparing 3 totally different websites.
That is not a accurate comparison for time till interactive.

**Comment by splincode** [comment]
@Toxicable Yes, most likely this is wrong, but the appearance of the first screen is of great importance in terms of human perception.

**Comment by splincode** [comment]
![image](https://user-images.githubusercontent.com/12021443/37107684-10a8cc3c-2246-11e8-8359-f7b144462614.png)

@IgorMinar Angular does not use server-side rendering, while official sites use it, why?

**Comment by Toxicable** [comment]
@splincode Sure, I never said it wasn't important. My concern is that you're comparing different things then using the results as if they were an accurate comparison of the frameworks they were built with.

**Comment by mlc-mlapis** [comment]
@splincode ... so just the trivial tests using Lighthouse 2.5.1 in Chrome (version 64) ... and not sure what I can judge from such results:
![image](https://user-images.githubusercontent.com/5693835/37107676-42e5efa6-2235-11e8-841a-bfa3f915eb89.png)
![image](https://user-images.githubusercontent.com/5693835/37107801-9e1600dc-2235-11e8-937a-aef8f5c5d907.png)
![image](https://user-images.githubusercontent.com/5693835/37107839-ae09f660-2235-11e8-876e-a6570394957e.png)

**Comment by splincode** [comment]
@Toxicable Yes, I'm wildly sorry, a little later I'll try to deal with VirtualDOM and Zone.is + ChangeDetection
@mlc-mlapis Indeed, what benefit does the analyzer have in this sense is unclear?

**Comment by splincode** [comment]
@Toxicable I created examples (generated tree)
https://github.com/Angular-RU/change-detection-tree

**Comment by IgorMinar** [comment]
There are lots of nuances related to this topic and covering them in a issue discussion would result in only partial coverage of the problem space.

Maybe one day, someone will do a scientific comparative analysis of all the possible change-detection strategies popularized by a wide variety of web frameworks and libraries, but ideally it should not be done by any of the framework authors because otherwise you'll send up with a biased self-promoting marketing pitch that only confuses people more than educates them.

As framework authors we feel comfortable with the runtime performance of Angular today as measured by our benchmarks and real world applications built at Google. We have a few performance improvements in mind for the upcoming versions, and we'll keep on researching and experimenting with various implementation strategies to find the best solution for Angular developers. We however don't want Angular developers to be too attached to one strategy over the another. Angular is an evergreen, ever-evolving framework and if we conclude that a different change-detection strategy results in significant performance boost and real world benefits to Angular developers, we'll work on changing the internals of Angular to take advantage of that approach. That is not the case today.

What we are focused on today is the startup performance where we think we can do much better. This is what the project Ivy is all about.

PS: performance is a complex topic and it's impossible to have a single benchmark that captures the startup time, runtime, perf, interaction latency, etc. Even in the discussion on this issue I see people comparing things that should not be compared. We are committed to improving the performance of Angular in whatever way is necessary, but we don't want to get into flame wars about approach X or Y because that doesn't help anyone. We'll instead use our energy to make Angular better for users and developers. Thanks
