### ISSUE TITLE
Angular tutorial http session,  InMemoryWebApiModule.forRoot(InMemoryDataService, { dataEncapsulation: true })

### ISSUE THREAD

**Issue by ScottHuangZL** [angular/angular#22644]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Feature request
[x] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

[https://angular.io/tutorial/toh-pt6](https://angular.io/tutorial/toh-pt6)

**The app.module.ts file, the line**
    **InMemoryWebApiModule.forRoot(InMemoryDataService),**
need upgrade to below since angular-in-memory-web-api have a broken change since version **0.5.0**
    **InMemoryWebApiModule.forRoot(InMemoryDataService, { dataEncapsulation: true }),**

Detail can find from: 
https://www.npmjs.com/package/angular-in-memory-web-api

**Comment by jenniferfell** [comment]
When I look, the current example does not use the default; it explicitly sets dataEncapsulation to true: 
InMemoryWebApiModule.forRoot(InMemoryDataService, { dataEncapsulation: true })

I'll need to check and see what the intent was.

**Comment by ScottHuangZL** [comment]
https://github.com/angular/angular/pull/22645

I have a pull request, please review and merge to resolve this issue.

It is not true, below tutorial still not explictly sets dataEncapsulation to true, I have to baidu/google to find out the root cause and solve this issue when I follow up the tutorial :
https://www.angular.cn/tutorial/toh-pt6 (The Chinese version)

The online code https://www.angular.cn/generated/live-examples/toh-pt6/eplnkr.html also not add it.
(I think the reason is the zip in the tutorial still use under 0.5.0 version InMemoryWebApiMoudule,
But, it still cause my issue, since I use ng cli to create latest project, the default version in package.json is 0.5.3")

Or may be caused by English version and Chinese version did not sync timely.
Anyway, better correct/add explanation in tutorial, thanks.

**Comment by gkalpak** [comment]
The example on angular.io is correct (explcitly setting data encapsulation as needed). You can see the relevant code [here][1].

The tutorial you referring to (www.angular.cn) is an independent community effort and not maintained in this repo. I am not sure where you should file angular.cn specific issues; maybe https://github.com/angular/angular-cn?

##
Closing this issue, since it is already fixed on both master and 5.x.

[1]: https://github.com/ScottHuangZL/angular/blob/a2f43f5b7a4d0d3837a45916ce3015f1edb5f2ec/aio/content/examples/toh-pt6/src/app/app.module.ts#L37-L38
