### ISSUE TITLE
Have a single Component.host property which mimics HTML

### ISSUE THREAD

**Issue by mhevery** [angular/angular#2268]
# Goal

Simplify binding to the host element and get rid of `hostListeners`, `hostProperties`, 'hostActions` properties

```javascript
@Directive({
  host: {
    'attr-name': 'attr-value',
    '[property]': 'expression',
    '(event)': 'statement',
    '@action': 'statement'
  }
})
```

**Comment by gdi2290** [comment]
what's wrong with introducing another decorator annotation?

```es6
@Directive({
  selector: 'autofocus'
})
@Host({
    'attr-name': 'attr-value',
    '[property]': 'expression',
    '(event)': 'statement',
    '@action': 'statement'
 })
class Autofocus {}


@Component({
  selector: 'home'
})
@View({
  templateUrl: 'home.html',
  styleUrl: 'home.css'
})
@Host({
    'attr-name': 'attr-value',
    '[property]': 'expression',
    '(event)': 'statement',
    '@action': 'statement'
 })
class Home {}
```
Since the simple case wouldn't need `@Host` you wouldn't see it in all the examples but it also wouldn't be a surprise since we have the same composition effect with a `@Component` with a `@View` and without. I guess if you encouraging people to inherit angular annotations then it does make sense to overload `@Component/@Directive`

```es6
@DragAndDropDirective({
  selector: 'selection'
})
class Selection {}

@AndroidComponent({
  selector: 'home'
})
class Home {}
```
