### ISSUE TITLE
i18n Hebrew currency minus sign is backwards

### ISSUE THREAD

**Issue by ronzeidman** [angular/angular#22714]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[v] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior

using the currency pipe in the Hebrew language creates the following HTML:
```html
{{-5000 | currency:'USD':'symbol':'1.2-2'}}
&rlm;-5,000.00&nbsp;$
```
which is shown as
```
$ 5,000.00-
```
## Expected behavior

to show the result as
```
$ -5,000.00
```
(I'm not sure if the $ sign should be before or after the number in hebrew)

This simple pipe is my workaround
```ts
import { Pipe, PipeTransform } from '@angular/core';

@Pipe({
  name: 'fixRtl'
})
export class FixRtlPipe implements PipeTransform {
  transform(value: any): any {
    if (typeof value === 'string' && value.charCodeAt(0) === 8207 && value.charCodeAt(1) === 45) {
      return value
        .replace(`${String.fromCharCode(8207)}-`, String.fromCharCode(8207))
        .replace(String.fromCharCode(160), `-${String.fromCharCode(160)}`);
    }
    return value;
  }
}
```

## Minimal reproduction of the problem with instructions

use this template in the Hebrew locale:
```html
{{-5000 | currency:'USD':'symbol':'1.2-2'}}
```
## What is the motivation / use case for changing the behavior?

To show the right number in Hebrew locale and I guess other RTL languages such as Arabic.

## Environment

<pre><code>
Angular version: 5.x.x

Browser:
- [v] Chrome (desktop) version 64.0.3282.186 
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [v] Firefox version 58.0.2
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [v] Edge version 41.16299.248.0 (16.16299)
 

</code></pre>

**Comment by ocombe** [comment]
So I've been working on this the whole morning, here is a stackblitz reproducing the issue: https://stackblitz.com/edit/angular-ucrpd5?file=app%2Fapp.component.html
I've been reading this awesome article that explains how bidi (and LTR/RTL) works: https://www.w3.org/International/articles/inline-bidi-markup/uba-basics
I've consulted with @shairez, and came to the conclusion that you're right, it should display `-5,000.00 $` and not `5,000.00- $`.
But for some reason, the CLDR data that we use gives us the format `\u200f-#,##0.00 ¤` for hebrew currency, notice the `\u200f-` meaning that the minus symbol will be display at RTL, on the right of the number.
The hebrew format for numbers is `#,##0.###`, which means that there's no special treatment for the minus sign.
If you look at the arabic format for currencies it's `¤ #,##0.00`, no special minus RTL here either.
I believe that the CLDR data format for currencies is probably wrong, and shai agrees with me. Here is how money is displayed on an Israeli bank website: ![image 1](https://user-images.githubusercontent.com/265378/37333934-dc1bc50a-26aa-11e8-8845-7efb0b97d332.png)

That being said, the code in angular itself is correct, we get a RTL symbol in the format and we keep it, which will displays the minus symbol on the right side of the number.
Since formats are extracted from CLDR data, you need to fill a bug report there: http://cldr.unicode.org/index/bug-reports
Once they've fixed their data, we'll be able to incorporate it into Angular itself.

When you fill that issue on the CLDR website, link to that issue, and probably to https://unicode.org/cldr/trac/ticket/6078 as well (which seems to agree with all of that).

**Comment by ronzeidman** [comment]
https://unicode.org/cldr/trac/ticket/10993

**Comment by AlQuraian** [comment]
This is causing an issue in Arabic too. I get the digits and currency sign flipped.

**Comment by petebacondarwin** [comment]
This is still an issue in Angular 9.1.7. But this is still due to the data provided by CLDR. The CLDR issue linked about no longer worked since CLDR moved from Trac to JIRA. Here are two new links:

https://unicode-org.atlassian.net/browse/CLDR-10992 (marked ACCEPTED)
https://unicode-org.atlassian.net/browse/CLDR-10993 (marked DONE!)

It seems that the CLDR work was continued here : https://unicode-org.atlassian.net/browse/CLDR-6078#icft=CLDR-6078

It is not clear to me whether they have resolved the issue there or not.

If this is still a problem for people here, please follow up with CLDR. If there is then an action for the Angular framework (perhaps to interpret the CLDR data differently?) then please open a new issue here.
