### ISSUE TITLE
routing + lazy loading - angular is ignoring modules at the end of path

### ISSUE THREAD

**Issue by adoris** [angular/angular#22765]
<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior

I take sample from angular tour of heroes tutorial:
https://angular.io/generated/live-examples/router/stackblitz.html

After application start: if url "https://annnymdoaeg.angular.stackblitz.io/admin/heroes" will be called - AuthGuard redirect me to login page. 
After login i expect to be at "https://annnymdoaeg.angular.stackblitz.io/admin/heroes", but "https://annnymdoaeg.angular.stackblitz.io/admin" will be loaded.
In method AuthGuard.canLoad i expect, that route.path = "admin/heroes", but i see route.path = "admin".

This issue is similar with: https://github.com/angular/angular/issues/15851

## Expected behavior
After login i expect to be at "https://annnymdoaeg.angular.stackblitz.io/admin/heroes", but "https://annnymdoaeg.angular.stackblitz.io/admin" will be loaded.
In method AuthGuard.canLoad i expect, that route.path = "admin/heroes", but i see route.path = "admin".

## Minimal reproduction of the problem with instructions
I take official sample from angular tour of heroes tutorial:
https://angular.io/generated/live-examples/router/stackblitz.html

## Environment

<pre><code>
Angular version: X.Y.Z

Browser:
- [x] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [x] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [x] IE version XX
- [ ] Edge version XX
</code></pre>

**Comment by jasonaden** [comment]
It appears this behaves as expected. If you still feel there is an issue, please provide further details in a new issue.

<hr>

It looks like this is because the `canLoad` guard receives the `Route` object, not a snapshot through which you could get access to the full URL and provide a better redirect. `canLoad` can't get access to the snapshot because it hasn't been created yet at the time `canLoad` runs. Therefore you will need to get the redirect path from somewhere else, such as `Location.path()`. Here's an example:

https://stackblitz.com/edit/angular-rpe95u?file=src/app/auth-guard.service.ts
