### ISSUE TITLE
Travis CI JWT addon

### ISSUE THREAD

**Issue by csutorasr** [angular/angular#22928]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior

CI uses JWT addon that will be [discontinued on April 17, 2018](https://docs.travis-ci.com/user/jwt).

## Expected behavior

Use CircleCI secret environment variables instead.

I have started a PR to resolve this. #22909

**Comment by csutorasr** [comment]
I have created a [feature request](https://discuss.circleci.com/t/hideable-project-level-environment-variables/20941?u=csutorasr). I hope it will be accepted otherwise the preview builds should be amended or maybe even stopped. (I have not found out any better solution than this.)

**Comment by gkalpak** [comment]
I'm afraid that feature request is not exactly what we want.
In any case, I don't think the previews need to stop. Worsst-case scenario, we will require the `aio: preview` label to be added on any PR in order to show the preview. But that is something that can wait until after we migrate to CircleCI :smiley:

**Comment by gkalpak** [comment]
I am not sure I fully understand your suggestion. Who creates the new branch on the private repo? Who adds tags. What are tags? :grin:

Note that the problem we are trying to solve is associating an uploaded zip file (which contains the build artifacts) to the PR they originate from.

**Comment by csutorasr** [comment]
I meant the CI to do all those things.

Sorry, I thought the only problem is to hide the variables. I forgot about the vulnerability  that pr number can be replaced with any constant that has the flag.

**Comment by csutorasr** [comment]
The solution could be to start builds with given custom build parameters in a POST request.

A bot checks if 'trusted' tag is added. If it is added it runs the build with the api request and injected secret variables. [More here](https://discuss.circleci.com/t/api-trigger-build-of-pull-request-from-fork/7784)

If new code is pushed to the PR the 'trusted' tag MUST be removed.

**Comment by petebacondarwin** [comment]
The downside of starting builds via a bot is that all builds would then need to run twice, right? Once due to being triggered by a Github change and then again by the bot.

If we use the Artifacts feature of CircleCI, we can store the built items on every PR and then leave an external service that is triggered by CircleCI making a request to a webhook to make the decision about whether to a) pull in those artifacts and b) expose them via the preview server.

**Comment by csutorasr** [comment]
The bot could have stopped the running build, however I like your solution, too. As I see the artifacts can be downloaded for each build and this is maintained by CircleCI without any code from the PR.

This is also a safe solution.

**Comment by gkalpak** [comment]
This has been taken care of by moving the `aio` CI jobs (including previews) to CircleCI.
