### ISSUE TITLE
Custom toEqual matcher doesn't propagate custom equality testers

### ISSUE THREAD

**Issue by npc-g** [angular/angular#22939]
## I'm submitting a...
<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[X] Bug report
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior
The custom toEqual matcher in packages/platform-browser/testing/src/matchers.ts doesn't propagate custom equality testers that have been registered via jasmine.addCustomEqualityTester. 

## Expected behavior
The toEqual function should take a second argument (after "util") which is the list of registered customEqualityTesters, and include it in the array passed to util.equals. See the original jasmine implementation for an example: https://github.com/jasmine/jasmine/blob/master/src/core/matchers/toEqual.js

## Minimal reproduction of the problem with instructions
Register a custom equality tester with jasmine.addCustomEqualityTester that would return a different result than the regular toEqual logic, call toEqual with values that should trigger it, watch it fail.

## What is the motivation / use case for changing the behavior?
I would like my custom equality testers to work.

## Environment

<pre><code>
Angular version: X.Y.Z

Browser:
- [ ] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: XX  
- Platform:  

Others:

</code></pre>

**Comment by KevinVillela** [comment]
I looked into this a bit, and it seems like Angular [overrides the toEqual function](https://github.com/angular/angular/blob/c8a1a14b87e5907458e8e87021e47f9796cb3257/packages/platform-browser/testing/src/matchers.ts#L117) so it can pass a custom comparator for ES6 maps. I think the way this is done is outdated for 2 reasons:
1. jasmine now has the [addCustomEqualityTester](https://jasmine.github.io/2.0/custom_equality.html) method that could be used instead.
2. jasmine added [native support for ES6 maps](https://github.com/jasmine/jasmine/issues/1257) which was released in [2.7](https://github.com/jasmine/jasmine/blob/master/release_notes/2.7.0.md). Angular and the Angular CLI appears to use jasmine 2.8, so we should be able to take advantage of this functionality.

I propose removing the custom toEqual override. This should have the intended effect of propagating custom equality testers. Perhaps just as important, it will also enable the other feature that jasmine configures in [their toEqual method](https://github.com/jasmine/jasmine/blob/9cb2f06aa665870dbd5df5fd58a35863738961b3/src/core/matchers/toEqual.js): [pretty printing object diffs](https://github.com/jasmine/jasmine/issues/675).

The one thing I'm unsure about is that something sort of similar was [attempted before](https://github.com/angular/angular/commit/f580ffab4f004b5d3297d693429e0a5d1dd4345a), but [rolled back](https://github.com/angular/angular/commit/b804d4bde5471a55268983ded859b88fafadf7fe) because it "broke a few existing tests". If that's still the case, then this change will probably break existing tests as well, but it should presumably break them only if they are incorrect right now? I'll try my hand at my first Angular PR and see what happens.

**Comment by KevinVillela** [comment]
Looks like I was mistaken about the version Angular uses for jasmine - I think it's [2.4](https://github.com/angular/angular/blob/master/package.json#L83). I think the addCustomEqualityTester function should still exist there, so I'll try that next.

**Comment by Eyas** [comment]
Ping @IgorMinar @mhevery @jelbourn any input on this issue? It's affecting us writing tests using .toEqual.

**Comment by mhevery** [comment]
The writeup sounds reasonable. Would you be willing to do the PR to remove it?

**Comment by Eyas** [comment]
PR #22983 should solve this but I think it fell through the radar?

**Comment by KevinVillela** [comment]
You're killing me Misko! :P

**Comment by mhevery** [comment]
Sorry about not noticing it earlier, the change looks good, should get merged shortly.
