### ISSUE TITLE
[ReactiveForms] - Export FormControl/FormControlName in template

### ISSUE THREAD

**Issue by dev054** [angular/angular#22981]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[x] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior
Actually it's really verbose to get a specific `control` to check something you wish in template:

```
<form [formGroup]="formGroup">
  <input type="text" formControlName="test">
  <div *ngIf="formGroup.get('test').touched && formGroup.get('test').invalid">
    Invalid :(
  </div>
</form>
```

Ok, ppl may argue that we can create a method in `component` and call it in template, however I think it'd be really better if we could retrieve `formControl/formControlName` reference in template, so we can do the same as we already do for `ngModel`:

`<input type="text" [(ngModel)]="name" #ctrl="ngModel" required>`
// Note the assignment

## Expected behavior
Using `FormsModule` (specifically `ngModel`), we can do the following:

```
<form>
  <input type="text" [(ngModel)]="name" #ctrl="ngModel" required>
  <div *ngIf="ctrl.touched && ctrl.invalid">
    Invalid :(
  </div>
</form>
```

It'd be really great if we can assign a variable to `formControl/formControlName`, like this:

```
<form [formGroup]="formGroup">
  <input type="text" formControlName="test" #ctrl="formControlName">
  <div *ngIf="ctrl.touched && ctrl.invalid">
    Invalid :(
  </div>
</form>
```

## Environment

<pre><code>
Angular version: X.Y.Z
Doesn't matter, but 5.2.9.

Browser:
- [ ] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: XX  
- Platform:  

Others:

</code></pre>

**Comment by kara** [comment]
While I can see why you'd think exports are handy (they are great for template-driven forms), the functionality was removed deliberately from reactive form directives because it encouraged template-driven patterns in reactive forms (which is generally an anti-pattern that leads to bugs). For this reason, it's not likely these are coming back.

**Comment by grant77** [comment]
It is currently extremely cumbersome dealing with displaying error messages with reactive forms.  I wish the angular team had incorporated error messages at the validator level.  

For example, an extra parameter with the built in validators:
** Validators.min(10, 'The number must be greater than or equal to 10').  

Then a directive to display first error message:
** <div *ngErrorFor="'MyField'"></div>

I actually implemented the above, but it had some shortcomings due to the fact that you can have errors that come from sources other than just where you defined the validators.  By that I mean the NG_VALIDATORS injection token.

The HTML 5 validation attributes are one example where angular hooks in via NG_VALIDATORS .  Another example is the Angular Material MatDatepickerInput which validates itself and can potentially add these additional validation error keys: matDatepickerParse, matDatepickerMin, matDatepickerMax, matDatepickerFilter.  Since we have no control over the generation of the these validators we cannot add our own custom error messages.

So, I have gone back to displaying error messages for reactive forms with the anti-pattern.  Here is how I expose an export for FormControlName, FormGroupName, and FormArrayName:

```
import { Directive, Self } from '@angular/core';
import { FormControlName, FormGroupName, FormArrayName } from '@angular/forms';

@Directive({ selector: '[formControlName]', exportAs: 'ngForm' })
export class FormControlNameExport extends FormControlName {
    constructor(@Self() formControlName: FormControlName) {
        super(<any>null, <any>null, <any>null, <any>null, <any>null);
        return formControlName;
    }
}

@Directive({ selector: '[formGroupName]', exportAs: 'ngForm' })
export class FormGroupNameExport extends FormGroupName {
    constructor(@Self() formGroupName: FormGroupName) {
        super(<any>null, <any>null, <any>null);
        return formGroupName;
    }
}

@Directive({ selector: '[formArrayName]', exportAs: 'ngForm' })
export class FormArrayNameExport extends FormArrayName {
    constructor(@Self() formArrayName: FormArrayName) {
        super(<any>null, <any>null, <any>null);
        return formArrayName;
    }
}
```
