### ISSUE TITLE
Video muted attribute not working

### ISSUE THREAD

**Issue by taylorcain** [angular/angular#23009]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior

The muted attribute is not working
<video muted loop autoplay>
  <source src="/assets/video/video.mp4" type="video/mp4">
</video>

## Expected behavior

The video should be muted

## Environment

<pre><code>
Angular version: X.Y.Z

Browser:
- [x] Chrome (desktop) version 5.2.4
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: 9.4.0  
- Platform:  Mac 

Others:

</code></pre>

**Comment by jainanuj0812** [comment]
https://stackblitz.com/edit/angular-52vmm4

I have tested it over chrome and edge, it's working for me.

**Comment by ericmartinezr** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).

**Comment by taylorcain** [comment]
Thanks jainanuj0812, the [muted]="true" works but just muted does not.

Thanks!

**Comment by askilondz** [comment]
@surayashivji instead of using [muted]="true" i was able to get it to work on mobile by doing"
    
    ngAfterViewInit() {
        this.videoEl = this.document.querySelector('video');
        if (this.videoEl) {
            this.videoEl.muted = true;
        }
    }

**Comment by ArtDesire** [comment]
@jainanuj0812 @ericmartinezr please reopen the issue as the _muted_ attribute has stopped working in angular 6+, chrome 67+. The current workaround has been mentioned by @ghost.
I have been wondering why autoplay stopped working on muted videos in chrome but just now got my hands to it.

**Comment by GagikAbovyan** [comment]
@ViewChild('video') video: ElementRef;

this.video.nativeElement.muted = false; or = true;

**Comment by worthy7** [comment]
Not working in Angular 8.

I can see the issue clearly is that when Angular puts the <Video> bit into the dom, it seems to just ignore the muted flag alltogether. I tested the exact same code in standard HTML and within Angular.

The solution was to trick it, and add in the muted attribute `onloadedmetadata`.

Working standard html:

```
<html>
<video 
controls
        muted
        autoplay
        loop 
        playsinline
        src="usage.webm">
    </video>
    <html>
```

If you try this in an angular context, it won't autoplay, and the console will also tell you it is waiting for a user gesture to allow it to play (confirming that it is unaware that it is muted).

**The deciving part is that it WILL work if the angular server just refreshed your chrome page for you because you edited and saved a file in the project. If you then refresh the page manually, it won't autoplay.**

The solution to make it work in an Angular context every time:
`onloadedmetadata="this.muted = true"`
