### ISSUE TITLE
host-context() and AoT compiler

### ISSUE THREAD

**Issue by BorisKhapilin** [angular/angular#23034]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior

In my project i use ViewEncapsulation.Emulated. Several css styles is described as:
:host-context(app-internal-transfer .selectebled-card.cvcError .cvc) input { ... }.

When I use JiT compiler, styles at runtime will look like this:
```
app-internal-transfer[_nghost-c23] .selectebled-card.cvcError[_ngcontent-c23] .cvc[_ngcontent-c23] input[_ngcontent-c23], 
app-internal-transfer .selectebled-card.cvcError .cvc [_nghost-c23] input[_ngcontent-c23]
```
Whitespaces between classes are kept, as expected.

When I use AoT compiler, styles at runtime will look like this:
```
app-internal-transfer.selectebled-card.cvcError.cvc[_nghost-c50]   input[_ngcontent-c50], 
app-internal-transfer.selectebled-card.cvcError.cvc   [_nghost-c50]   input[_ngcontent-c50]
```
Whitespaces in the host-context() between classes are removed.

## Expected behavior

When I use AoT compiler, whitespaces in css styles will not be removed, like using JiT

## Environment

<pre><code>
Angular version: 5.2.7

</code></pre>

**Comment by MarkPieszak** [comment]
To go along with @BorisKhapilin information, here is a basic CLI repo where the issue can be reproduced. Just run `npm run start:prod`.

https://github.com/MarkPieszak/angular-aot-scss-hostcontext-issue

The issue seems to occur when there are _any_ spaces in the `:host-context()`, removing them and having a single element works. Note, the issue only occurs in AoT mode.

```ts
:host-context(.parent .child) {
    .this_component {
        background: red;
    }
}

// Note the below would work when running --prod AoT compilation
// It seems any "whitespace" in :host-context() is the culprit
/*
:host-context(.parent) {
    .this_component {
        background: red;
    }
}
*/
```

**Comment by vinayakpatil** [comment]
@mhevery Any updates on this?

**Comment by janneromell** [comment]
+1
Noticed quite a lot of styling was missing in my prod build.
Tracked it down to a few usages of :host-context(.one-class .second-class) { ...
Works as expected in dev (JIT) build but for AOT this CSS is gone missing - likely due to the space between .one-class.second-class removed - creating a whole different selector rule.

**Comment by msegers** [comment]
+1

**Comment by SebastianPodgajny** [comment]
Issue is in [CleanCssWebpackPlugin](https://github.com/angular/angular-cli/blob/master/packages/angular_devkit/build_angular/src/angular-cli-files/plugins/cleancss-webpack-plugin.ts) probably we need to disable some additional rule in clean-css

**Comment by SebastianPodgajny** [comment]
@alan-agius4 Can you or someone from CLI team could look into this? Also posibility to extend CleanCss would be great 
[here](https://github.com/angular/angular-cli/blob/58bc5b8f2a2a285f8e09ec05ef407fe32be3ef05/packages/angular_devkit/build_angular/src/angular-cli-files/plugins/cleancss-webpack-plugin.ts#L61) something like `...this._options.cleanCssOverride`

**Comment by alan-agius4** [comment]
Hi all, this seems like a bug in clean-css (https://github.com/jakubpawlowicz/clean-css/issues/1062), and since it's related to the CLI this is now being tracked here: https://github.com/angular/angular-cli/issues/13854

You can use special clean-css comments to stop `:host-context` selectors from being optimized.
See: https://github.com/angular/angular-cli/issues/13854#issuecomment-470831308
