### ISSUE TITLE
Why is the dom being tested in unit tests? Documentation is confusing on test practices 

### ISSUE THREAD

**Issue by dman777** [angular/angular#23067]
I am confused on why Angular 2 and greater is testing the dom in unit tests:

[from documentation](https://angular.io/guide/testing#why-not-rely-on-e2e-tests-of-dom-integration)

> Because of these many obstacles, you should test DOM interaction with unit testing techniques as much as possible.

I have a few questions about this:

1) For components - I see devs writing e2e tests instead of unit tests inside of unit tests. I don't see functions being invoked and asserted... just elements clicked on and asserted. This isn't really a unit test any longer.  **What about the unit test actually being a unit test and having the business logic tested**?

2) Because the dom is being tested in the unit test, this means complete overlap with the e2e test. Two e2e tests exists instead of a unit test and a e2e test. 

3) Angular clearly is still for e2e tests because of `ng e2e` and
   > E2E tests are great for high-level validation of the entire system
   
  So, again...we have complete overlap with dom testing in the unit tests and in the e2e

4) **Because Karma and Jasmine are not meant for e2e but are being used for e2e, I have failures on headless testing that I do not have on loca**l. This is most likely from race conditions where the elements are not ready yet on the headless test and karma does not give a way to slow down the test. Nor does Jasmine have a way to pause. Unlike Mocha, it's `done` function does not work in `setTimeout`. 

  [1]: https://angular.io/guide/testing#why-not-rely-on-e2e-tests-of-dom-integration

**Comment by KostyaTretyak** [comment]
@dman777, see [End to End Testing Angular 2, A Complete Guide (Part 1)](http://www.gistia.com/end-to-end-testing-angular-2-p1/).

There is a good indication of the difference between unit-testing and e2e-testing:
> We can run end to end tests on multiple browsers and find bugs that emerge in certain environments / browsers – such as… Internet Explorer.

So, event `click` inside unit-testing it's not exactly same event `click` from Chrome, Firefox, IE...

**Comment by dman777** [comment]
I don't think that is a good indication of the difference. If you are asserting a class in on a element in the unit test(which they do in Angular Material), then this is wrong in testing practices. It's testing the dom in a unit test instead of business logic.

> Because of these many obstacles, you should test DOM interaction with unit testing techniques as much as possible.

This is a strong difference in testing from Angular 1. The frame work changed from Angular 1 to Angular 2, but universal testing practices has not.  It would be nice if the Angular team would clarify their documentation on unit testing and e2e.

**Comment by BenRacicot** [comment]
I'm glad to see this issue raised. 
I'd like to weigh in to test my own assumptions (see what I did there?)

Angular changes a lot and there exists tools to help us update versions automatically. That being said I would have written the docs that way also. No such thing as 'too much testing'.

However, if you're a small team with no CI/CD setup it seems obvious to test template logic and even E2E.

If you're part of a team of teams with CI/CD there should be a QA process where that team is dedicated to E2E and business logic before deployment. Then we would focus on true unit testing, leaving DOM/template/Business logic to the dedicated team.

Is this a correct viewpoint?

**Comment by bampakoa** [comment]
I have recently revised the latest changes in the [Component Test Basics](https://angular.io/guide/testing#component-test-basics) section of the angular.io. The [Component DOM testing part](https://angular.io/guide/testing#component-dom-testing) part especially, puts is simply as to why we should use DOM testing in our unit tests so I think that this issue is no longer valid. What do you think?

**Comment by dman777** [comment]
eh.... not really convinced it is correct. The business logic that I do see tested almost borders on testing Angular apis which already have been tested by the Angular team. 

And this really bothers me....

```
it('should find the <p> with fixture.debugElement.query(By.css)', () => {
  const bannerDe: DebugElement = fixture.debugElement;
  const paragraphDe = bannerDe.query(By.css('p'));
  const p: HTMLElement = paragraphDe.nativeElement;
  expect(p.textContent).toEqual('banner works!');
});
```

1) If we are grabbing dom elements to assert text, it def should be in a e2e test. I don't see this as business logic being tested. If we asserting that Angular created a component... that was tested by Angular.  
2) The wording of a test should not be technical. It should be written so a non tech person would read it.... in this case something along the lines of `should show the user the banner works`

**Comment by srijanreddy98** [comment]
@dman777 I was facing this conundrum too. I hope this clears it up. Here is what I think:

A component consists of two main parts: the template and logic for that template. There won't be any function (or logic/ code) in the ts file that is not used by the template. And unit test must check whether or not the template and the logic file working well together. Because the component, which is the unit here, comprises of HTML (and CSS) and the TS. Let me clarify this with an example:
A component has two functions called A and B. A developer while writing some HTML, used a wrong function as the click handler. If he had to put A, he put B instead. Now considering that you only checked the ts file, i.e. the class only, you won't catch this error in the unit tests. But, in this case, the unit test should fail.

I am not saying that unit testing means checking some random text context. Instead, I think that if you are testing a function, why not just call it from DOM interaction (obviously functions like OnInit, OnDestroy don't come in this category). And while testing also check whether the relevant changes get updated in the DOM or not.

So something like this:
```
comp.someFunc();
expect(comp.someVar).toBe('something');
```
becomes:
```
someEl.click();
expect(relevantElement.textContext).toBe('something');
```

I am not telling that we should check the child elements or the parent elements, etc. That sort of integration is tested by e2e tests. But feel DOM testing is good, if not crucial, for component unit testing.
