### ISSUE TITLE
Run integration/ tests under Bazel

### ISSUE THREAD

**Issue by alexeagle** [angular/angular#23089]
All the tests in angular/angular/integration should be bazel targets so they're re-triggered when their inputs change.

**Comment by jelbourn** [comment]
@josephperrott this is still active, yes? Mainly for SauceLabs and Browserstack tests?

**Comment by josephperrott** [comment]
Based on how I read this, its specific to the integration tests, rather than the unit tests running in saucelabs.  With that being the case, I believe this is already addressed.  If we feel we need an issue open for tracking the changes around saucelabs testing, I think it should be a different issue.

**Comment by josephperrott** [comment]
Note: This was fixed by @gregmagolan
