### ISSUE TITLE
No ability to set validation status of AngularJS form from Angular component (ngModel, Upgrade Provider)

### ISSUE THREAD

**Issue by sharikovvladislav** [angular/angular#23085]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ X ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior

There is no possibility to set validity of NgFormController from Angular component (in case of using Angular Upgrade). 

## Expected behavior

I need ability to influence validity of parent AngularJS form from Angular component.

## What is the motivation / use case for changing the behavior?

I have AngularJS application. I have a lot of components using ngModel (since it is one of the core features in AngularJS). I rewrote some component to Angular. To simplify the process, I rewrite components "as is". So new component get/set data with ngModel directive. I used hookupNgModel from https://github.com/angular/angular/pull/10578 to achieve this. 

## Environment
<pre><code>
Angular version: 4.4.6
</code></pre>

**Comment by sharikovvladislav** [comment]
I can make pull request.

I suggest modify behaviour of `hookupNgModel` method. Code will be like:

```
export function hookupNgModel(ngModel: angular.INgModelController, component: any) {
  if (ngModel && supportsNgModel(component)) {
    ngModel.$render = () => { component.writeValue(ngModel.$viewValue); };
    component.registerOnChange(ngModel.$setViewValue.bind(ngModel));
    if (typeof component.registerOnTouched === 'function') {
      component.registerOnTouched(ngModel.$setTouched.bind(ngModel));
    }
    // What I suggest
    if (typeof component.registerSetValidity === 'function') {
      component.registerSetValidity(ngModel.$setTouched.bind(ngModel));
    }
  }
}
```

And main idea: to have this working component must implement `registerSetValidity` method. He will set some internal variable and component will call it when it needs changing of the validity state of the parent form.

Hope you can understand me.

**Comment by sharikovvladislav** [comment]
I need this feature in 4.4.6 and higher. Our project using this version of Angular. It is really huge and not flexible project so we are not able to migrate fast. How can we perform this?

**Comment by gkalpak** [comment]
Sorry for the late response, @sharikovvladislav.

It would indeed be nice to have better interoperability for `ngModel`'s validity state, although I am not sure this is possible (due to how differently validity is handled in the two frameworks).

Happy to review a PR, if you are still interested :wink:

**Comment by aghausman** [comment]
My scenario is a bit different, I have an Angular Component which is using inside an Angular JS form.

I want to highlight my input control (which is in Angular Component) if my component has any validation errors. 

I tried to inject NgControl in the constructor like @Self() control: NgControl to no effect because it is always returned as null. 
Had I got NgControl, I could have used control.errors. That's probably because in AngularJS host control is NgModelController. 

So I ended up highlighting my control with CSS styles. Say my component is <my-text-field> which has <input> control. On validation, my-text-field class is being set correctly to "ng-invalid" which I'm using to style input control.

```
my-text-field.ng-invalid input{
 border: 1px solid red !important;
}
```

Although I'm able to solve the problem in hand, my component is not aware of the validation status. It would be wonderful if I can inject NgModelController in the constructor or sync the validation status. 

Just out of interest, is it possible to extend Util class and update hookupNgModel function to also sync validation status?
