### ISSUE TITLE
Investigate strict deps not applied to correct library?

### ISSUE THREAD

**Issue by alexeagle** [angular/angular#23094]
During the sprint to release angular 6 rc.1 we noticed eg.
https://github.com/angular/angular/pull/23084/files#diff-2bdbdf11c76ed895a55e5b393bccd59b
which needs a dependency on `@rxjs//operators` - yet some `ts_library/ng_module` targets which import from that location did not require the dependency...

/cc @IgorMinar

**Comment by gregmagolan** [comment]
I looked into this and it looks like the strictDepsPlugin and the tsetse plugin are not turned on in `ng_module`. Only `ts_library` turns these in `tsc_wrapped.ts`:
```
  // Install extra diagnostic plugins
  if (!bazelOpts.disableStrictDeps) {
    const ignoredFilesPrefixes = [bazelOpts.nodeModulesPrefix];
    if (options.rootDir) {
      ignoredFilesPrefixes.push(path.resolve(options.rootDir, 'node_modules'));
    }
    program = strictDepsPlugin.wrap(program, {
      ...bazelOpts,
      rootDir: options.rootDir,
      ignoredFilesPrefixes,
    });
  }
  program = tsetsePlugin.wrap(program, disabledTsetseRules);
``` but that code path is not used by `ng_module`

**Comment by gregmagolan** [comment]
Also for the case `import {Observable} from 'rxjs';` in a `ts_library` that is also able to compile without a strict dep on `@rxjs` since typescript resolves the import to `external/npm/node_modules/rxjs/index.d.ts` (outside of the sandbox) and that path is allowed with `if (ignoredFilesPrefixes.some(p => declFileName.startsWith(p))) continue;`

**Comment by gregmagolan** [comment]
One possible solution since we want to keep backward compatibility for user's using the `node_modules` attribute is to not ignore the `node_modules` folder for strict deps if the user does not override the default `node_modules` value for ts_library (which just contains the typescript lib .d.ts files by default)

**Comment by gregmagolan** [comment]
npm strict deps are going to be turned on for ts_library with https://github.com/bazelbuild/rules_nodejs/pull/750. Reading over the comments here looks it won't apply to ng_module yet as ng_module does not turn on the strict deps plugin.

@alexeagle does that sound right to you? strict deps in ng_module is waiting on the refactor for ng_module to be a plugin to ts_library?

**Comment by alxhub** [comment]
Closing as obsolete - the Bazel builder and associated CLI functionality are deprecated and no longer supported.
