### ISSUE TITLE
Using @angular/compiler-cli throws a compile-time error because of missing declaration of NgTools_InternalApi_NG_2

### ISSUE THREAD

**Issue by mgechev** [angular/angular#23112]
## I'm submitting a...

<pre><code>
[x] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior

Currently, I'm using `@angular/compiler-cli` in [`ngast`](https://github.com/mgechev/ngast) which is a dependency of a couple of other projects. When I try to compile `ngast` with `@angular/compiler-cli@6.0.0-rc.1` I get:

```
node_modules/@angular/compiler-cli/index.d.ts(20,10): error TS2305: Module '"/.../ngast/node_modules/@angular/compiler-cli/src/ngtools_api"' has no exported me
mber 'NgTools_InternalApi_NG_2'.
```

I saw that `NgTools_InternalApi_NG_2` is marked as `@internal` and is currently deprecated.

Probably the `@angular/compiler-cli` should be updated to use `ngtools_api2`.

## Expected behavior

No compile-time error.

## Environment

<pre><code>
Angular version: 6.0.0-rc.1

**Comment by alexeagle** [comment]
Any idea if this is a regression introduced after 6.0.0-rc.0?

**Comment by hansl** [comment]
That API was non-public internal-only super-experimental, never intended to be used externally. I guess technically it's  not a regression, since we don't need to deprecate it. It was left as is for backward compatibility with CLI 1.x.

You should use the new shiny non-public internal-only super-experimental API: https://github.com/angular/angular/blob/5.2.x/packages/compiler-cli/src/ngtools_api2.ts

After discussing with @alxhub that one will probably be removed in Ivy. The good news is that for each rewriting of these non-public internal-only super-experimental APIs, we're getting closer to something we can actually make public.

**Comment by alan-agius4** [comment]
So from the `compiler-cli` none other than the new shiny private `ngtools_api2` can and should be used?

As now even something like the below is unusable due to the above mentioned error by @mhegazy 

```ts
import { VERSION } from '@angular/compiler-cli';
```

**Comment by alan-agius4** [comment]
I ended up doing ‘skipLibCheck’
