### ISSUE TITLE
New Feature:  BaseURL support on HttpClient

### ISSUE THREAD

**Issue by jega-ms** [angular/angular#23139]
Currently we have to write an interceptors for changing the BaseUrl of the HttpClient requests. Could you please provide us the base url setters or default environment level configuration (e.g properties file)?

**Comment by fireflysemantics** [comment]
This would be awesome.  When deploying to github pages, we have to set the `base` property to gh-pages repository.  

The `base` property URL value is prefixed onto all HttpClient requests, and when working with CORS requests from other resource servers this causes issues.

**Comment by fireflysemantics** [comment]
Described the issue fully here and provided Stackblitz examples:

https://stackoverflow.com/questions/59605333/not-using-the-base-attribute-when-making-domsanitizer-api-calls?noredirect=1#comment105374985_59605333

**Comment by petebacondarwin** [comment]
One of the requests in the StackOverflow issue is to set this differently for different instances of `HttpClient` but since `HttpClient` is provided by DI there is only one instance of it.

The most obvious workaround (other than using an interceptor) is to provide a subclass of `HttpClient` that sets the baseURL.

A built-in solution would, I guess, use DI to provide a `HTTP_CLIENT_BASE_URL` injectable that `HttpClient` would consume, via injection. But this would only solve the problem once for the whole app. Is that acceptable?

**Comment by Kstheking** [comment]
it is strange that this is still not a function after 3 years :(

**Comment by alxhub** [comment]
After discussion, we've unfortunately decided not to proceed with implementing this feature.

There are many subtle challenges that crop up when designing functionality like this, and design decisions that have to be made (for example: what constitutes an "absolute URL" is not a trivial question to answer). Interceptors provide a clean, reliable, and straightforward way for an application that wants this behavior to implement it with the exact behavior that's required. A native solution would not improve the developer experience appreciably over using an interceptor (in fact, if we implemented this feature natively, it would probably take the form of an interceptor).
