### ISSUE TITLE
Unnecessary calls to retrieve and shouldAttach in RouteReuseStrategy

### ISSUE THREAD

**Issue by imsingh** [angular/angular#23162]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior

When the first route is rendered. It has unnecessary calls to `retrieve`, even when `shouldReuseRoute` returns **true**.

## Expected behavior

It shouldn't run `retrieve` and `shouldAttach` at all. Apart from that, sequence of running these function is also wrong. `shouldAttach `should run first then `retrieve`. That's my understanding of course.

## Minimal reproduction of the problem with instructions

https://stackblitz.com/edit/angular-9yptbr
1. Open the stackblitz example
2. Check the console logs.
3. There are calls to retrieve and shouldAttach, which shouldn't be there at all

## Environment

<pre><code>
Angular version: 5.2.8

Browser:
- [x] Chrome (desktop) version 65.0.3325.181
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: XX  
- Platform: Mac 

Others:

</code></pre>
I am using CustomStrategy for RouteReuseStrategy, but it is exactly same as DefaultRouteReuseStrategy

**Comment by StevenLiekens** [comment]
I've been digging around a lot in this code lately (don't ask why). I found that `createRouterState` is the thing that calls `retrieve` when you don't expect it to be called.

This code should (partially) explain what you're seeing:
https://github.com/angular/angular/blob/4648597d14e843f75c5e9dd761af740c1c27b5c0/packages/router/src/create_router_state.ts#L22-L44

I expect `prevState` to be falsy for the first route, and that would explain why `retrieve` is called.

**Comment by nthornton2010** [comment]
Any updates on this? This is causing things to break because retrieve is called when routeReuseStrategy.shouldReuseRoute returns false in this case and setFutureSnapshotsOfActivatedRoutes throws an error that breaks our route reusability in some places, forcing us to disable reusing the route in those places. The cached route should not be retrieved if shouldReuseRoute returns false.

**Comment by Jakartoine** [comment]
@mgechev,

Could you please make things going forward with such a blocking point since almost 3 years?

Thanks in advance!  👍🏻

**Comment by atscott** [comment]
This will be fixed in #30263. There seems to be a bit of confusion here though around `routeReuseStrategy.shouldReuseRoute` and what that means for `routeReuseStrategy.retrieve/shouldAttach`. Please refer to @StevenLiekens's comment https://github.com/angular/angular/issues/23162#issuecomment-378612601. When `shouldReuseRoute` returns `false`, it means that the router should not reuse the currently activated route. The logic then continues to ask the `RouteReuseStrategy` if there is instead a stored route that was previously detached that should be reattached.
