### ISSUE TITLE
Tour of heroes tutorial: incompatible version of angular-in-memory-web-api being installed

### ISSUE THREAD

**Issue by jasonreed7** [angular/angular#23205]
I was following the Tour of Heroes Tutorial and in the HTTP section (part 8) I followed the instructions to install angular-in-memory-web-api with npm install angular-in-memory-web-api --save. This installed version 0.6.0 for me and it appears to be incompatible with angular 5 and rxjs 5. This caused the tutorial application to stop working. It took a while to track down the problem and fix by going down to version 0.5.4  of angular-in-memory-web-api. If other people are experiencing this it may make the HTTP section of the tutorial confusing.

**Comment by IgorMinar** [comment]
This is already fixed in master (https://next.angular.io). We need to backport the fix.

**Comment by gkalpak** [comment]
I don't think that backporting the fix is trivial (but I might be wrong).
Alternatively, we could just be explicit about installing `angular-in-memory-web-api@0.5` for the Angular v5.x docs (current stable), as discussed [here][1].

[1]: https://github.com/angular/angular/issues/22955#issuecomment-377823669

**Comment by jenniferfell** [comment]
Closed by https://github.com/angular/angular/pull/23242
