### ISSUE TITLE
Triage process: impact, LGTM, process

### ISSUE THREAD

**Issue by yjbanov** [angular/angular#2326]
Some questions/comments about the new issue triage process:

## Should we add impact (or severity) attribute?

Similar concepts in other bug trackers are "votes", "me-toos" and "stars" that signal that a feature is important to the users. Unfortunately, GitHub lacks this concept and our triage process is not compensating for it.

Priority is usually calculated as some function of effort and impact of the feature (or severity of the bug). Without the impact attribute one would need to read through comments to understand why the team decided to deprioritize an issue (it's low impact for the effort needed). It could also explain why the team decided to pursue a big-effort project (it's high impact enough to warrant the effort). Also, impact is something the users would have a lot of say in. `impact: negative` could be used to downvote a proposal because we believe that it is actually more trouble than it's worth.

## `pr_state: LGTM` and `pr_action: cleanup` too similar?

In both cases you are not yet allowed to merge and need to do some cleanup. I think if we renamed `pr_action: cleanup` to `pr_action: needs_work` it would put more distance between the too.

## Is end state of a PR always `pr_state: LGTM`?

A PR could also be obsolete or rejected or superseded by another PR.

## `comp: process`

I think we also need a meta-component for discussing team processes such as the triage process itself and processes related to releasing to npm and pub. Suggestions: `comp: process`, `comp: team`.

/cc @mhevery @IgorMinar

**Comment by naomiblack** [comment]
Since we're still in dev preview, not general release, the `cust:GT` and `cust:Ionic` fulfill the purpose of recording user pain to the extent that we're able to be responsive. I feel strongly that the github queue should reflect actual current process. 

I'd like us to try the current process for a few weeks before making any significant changes. I expect that this isn't final. There's some procedural pain associated with renaming labels in github, so I'd rather do it all in a large batch than on a highly iterative basis.

**Comment by mhevery** [comment]
Closing since inactive... / obsolete.
