### ISSUE TITLE
Dynamic component loading with Lazy support

### ISSUE THREAD

**Issue by santhosh-ktec** [angular/angular#23284]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[x] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior

Dynamic component loading using `ComponentFactoryResolver` requires to specify components in `entryComponents`

## Expected behavior

My expectation is to load component dynamically like a lazy load because I would have thousands of components added and growing. When I specify in `entryComponents` that will get loaded on client side and will render once i load the component.

All I want is to load the component dynamically from serverside like a ajax call. 

</code></pre>

**Comment by mlc-mlapis** [comment]
@santhosh-ktec ... not sure what exactly you want. Now `entryComponents` are some type of registry to list component that are used neither their tags in templates nor as routes so Angular compiler think that they are not use at the application at all ... because it is not possible to analyze your custom code to discover if you are or not loading them dynamically. So tree-shakeable process knows that you certainly want to keep those component in the final version of your optimized application.

... btw ... you can programmatically load any lazy loaded module (which contains one or more components) in any moment you want = on-demand so it is exactly `AJAX` call.

**Comment by mboughaba** [comment]
> ... btw ... you can programmatically load any lazy loaded module (which contains one or more components) in any moment you want = on-demand so it is exactly the AJAX call.

This is true, but it doesn't work outside of the angular router. So the question will be *How to lazy load dynamic components when your routes are also dynamic (or at least not pre-defined)*

@mlc-mlapis any code snippet or documentation reference will be very welcome. I am highly interested in this :)

**Comment by mlc-mlapis** [comment]
@mboughaba ... it works outside of Angular router because `ngc` compiler can compile any module and it doesn't matter if it is a lazy loaded one or not. Then you can programmatically load any of them.

> This is true, but it doesn't work outside of the angular router. ****

The other thing ... not related to Angular itself but just to CLI is that the current version of CLI creates lazy loaded modules / bundles on the base of defined routes. So in some cases you have to define dummy routes to allow CLI to understand what is what and correctly create those lazy loaded bundles. After that you can load them via Angular router directly (using the routes) or just programmatically (ignoring those routes).

The above thoughts don't include cases when you think about really dynamic creation of modules in run-time inside browser. This is totally different scenario ... and for it you need to use JitCompiler loaded to a browser ... combination of AOT (for base app) + JIT (for dynamic new modules and components just in run-time) together.

**Comment by irowbin** [comment]
@andrewseguin   I've been struggling to load lazy modules from a CDN  at runtime.  I've created a question at stackoverflow [how to loadchildren dynamically from different server or CDN at runtime](https://stackoverflow.com/questions/50343503/how-to-loadchildren-dynamically-from-different-server-or-cdn-runtime-using-ang) and it seems that there is no solution yet or i am not finding a proper example.🤔

**Comment by nefcanto** [comment]
I also need this feature. I also asked [this question on StackOverflow regarding this feature](https://stackoverflow.com/questions/48124682/is-there-a-way-to-lazy-load-components-not-modules-in-angular). We could do this in AngularJS. But in Angular we can't.

The point is, a lot of features might not work for this process, like tree-shaking. But it's OK. I'm not worried about that at all. All I want is to be able to load SPA pages and fragments dynamically, **AT A MORE GRANULAR LEVEL**, not at module level. I don't want to load an entire profile module, if user only wants to change his email address. Profile module contains email form, email validation, cell phone number form, cell phone number validation, two-factor authentication configuration, changing password, managing email preferences, changing profile picture, etc. I don't want to load all of that to only let user change his email address. That's apparently an overhead. This logic can be expanded to many many more modules. A user might be only working with one or two components from each module. I don't want to load 10 modules, each containing 15 components, that is 150 components for a user who works with only 20 components.

This is a hugely win for Angular and I highly encourage the team to think about it seriously. Thank you.

**Comment by nefcanto** [comment]
Another very important issue that I have to mention, is that a lot of optimizations like tree-shaking and AOT compilation are required because we load a huge amount of components into the browser. If we reduce that initial amount, then AOT and other performance tips won't be necessary anymore. It's just similar to old school of web, but instead of loading the entire application we only load the HTML fragment and related JS/CSS files which of course would be very fast because only 3 requests at max would be sent to the server and also on loading they won't occupy angular compiler that much.

**Comment by mlc-mlapis** [comment]
@nefcanto ... it looks that you are mixing a lot of things together and your arguments don't look really serious ... why do you do the counting - it doesn't have any sense. You still need some UI to allow a user his email address and somehow to save it and so on. So you create some code / component for it. The other thing is how do you organize those parts. You can load that parts via Angular router or just only programmatically where you have one component in one module (module means 5 code lines above the component code). Or you can mix AOT mode with using JIT compiler right now, so you can dynamically use any HTML code to render the UI.

Or you need to wait for Ivy renderer to get some extra ad-hoc things. You can follow the progress here: https://is-angular-ivy-ready.firebaseapp.com/#/status

**Comment by nefcanto** [comment]
@mlc-mlapis it doesn't make sense to wrap each component inside a 5 line code module. A module is by semantic definition a bunch of components. If we had one component per module, why did we bother to create the concept of module at all?
Yeah for changing email, I need to create an HTML file, and the accompanying TS/JS and SASS/CSS files. That's fair. But I don't want to load the entire profile module for the user, only for him to use a small part of it.
When you said we can dynamically use any HTML code to render the UI, what did you really mean? Can you provide a sample for that?

**Comment by albanx** [comment]
In my opinion lazy loading at component level is not needed, moreover that is an overkill, leading to abuse and having the reverse effect, by slowing down the performance of the application.

In the example @nefcanto made is an overkill, you want to lazy load every user component, but does it really worth. Do you have such huge components code that a single one needs lazy loading? I this case there seems to be some bloaters and you might that you might think splitting in a module separating concerns.

I am working on an AngularJS app right now in my job, I have a situation where in some parts of the app, every single component is lazy loaded, killing the app performance (having strange visual effects until everything is loaded), and that becomes more complicated having the code full of watchers and timeouts in an effort to improve the performance.

Lazy loading should be used with reasoning and parsimony, it does not make sense to have 100 request to load 100 components of 5kb each, rather having 10 request with 50kb each. We should a good reasonable balance when lazy load, example
 _if the user visits the profile page then there is a good chance he changes his password and email settings, or the 2 factor auth so let's lazy load all that module._ 

Said that is my opinion, sometime I see developers abuse of the freedom in the code, leading to rot and code smell...

**Comment by Pringels** [comment]
One can make the argument that _any_ feature of a framework might potentially be abused. In theory I could wrap every single component in a module and lazy-load all of them. 

Also, a component does not necessarily have to be very "big" to warrant lazy-loading; it could simply be pulling in fairly large dependencies that are not required anywhere else. 

My use case: I have a simple pdf viewer component that renders a PDF document client-side using `PDF.js`. (which is a fairly hefty dependency that only ever gets used in this component) I don't want to have to wrap the viewer component in an entire module just to enable code splitting. I would have to make significant changes to my current routing setup to enable that.

IMHO `Vue.js` has the simplest and most elegant solution to this problem:
https://vuejs.org/v2/guide/components-dynamic-async.html#Async-Components

I enjoy working with Angular a lot, and I respect the amount of knowledge and expertise that has gone into its development, but I often get the feeling that some things are over-engineered. (the module system in particular)

**Comment by mlc-mlapis** [comment]
@Pringels ... a new module could be created by 5 lines of code so what is the problem? There is some idea to introduce so called `default` module ... which would be the default context also ... so then adding just one component would be `module-less` ... but it is not on the table right now.

**Comment by Pringels** [comment]
@mlc-mlapis the problem is that it _isn't_ necessarily always just 5 lines of code. 

I just managed to get lazy-loading working after roughly 2 hours and about 200 lines of refactoring across 6 files. I had to hoist several shared component/directive declarations up into a new shared module, re-export them from there, and then import that module into both my containing feature module and the newly created lazy-loaded module. I also had to create a separate routing configuration for the lazy-loaded module. 

And that was all just to get _one_ component lazy-loaded. 

My point is that it's non-trivial process implementing lazy-loaded components in a large Angular application. I pointed to the `Vue.js` API as an example of a simple and intuitive way of achieving the same thing.

So big +1 from me on this feature request! :)

**Comment by mlc-mlapis** [comment]
@Pringels ... yep, transforming already existed app and separating already used components to standalone modules represent much more work. Previously I was talking about creating a new one.

Actually, Angular modules represent also the context, so it's not possible to throw them out.

**Comment by mlc-mlapis** [comment]
@chaosmonster ... you have to also remember on the organizational role of modules ... `imports`, `exports`, ...

**Comment by Pringels** [comment]
After watching the angular connect core team panel discussion I'm really glad that dynamic component imports are being seriously considered. Big props to the Angular core team for acknowledging the pain points associated with lazy loading modules and offering a simpler solution!

**Comment by jelbourn** [comment]
Tracking the main underlying concern here in #18093

**Comment by amitport** [comment]
@jelbourn ASAIKT https://github.com/angular/angular/issues/18093 only considers statically compiled and dynamically loaded components, while this also includes dynamic compilation (for example, loading angular source from db, or an online a form/editor that allows editing angular code fragments)
