### ISSUE TITLE
Prevent FormArray push to emit event

### ISSUE THREAD

**Issue by fttriquet** [angular/angular#23336]
## I'm submitting a...
<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Performance issue
[x] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
[ ] Other... Please describe:
</code></pre>

## Behavior
When pushing a FormGroup inside a FormArray, can it be possible to prevent the push to emit an event as it is on setValue.

`(myForm.get('control') as FormArray).push(new FormGroup(), { emitEvent: false });`

## What is the motivation / use case for changing the behavior?
When using formArray with a redux store, If I'm using valueChanges observable to dispatch the changed values in my store, the push of a new FormGroup will trigger an endless loop

**Comment by meriturva** [comment]
i guess it is similar to: https://github.com/angular/angular/issues/20439

**Comment by fttriquet** [comment]
It's pretty close, but I need to use FormGroup inside the FormArray in my case, preventing me from using add and set control methods.

**Comment by cpru2** [comment]
I was running into this same issue using observables to sync a form with another component. To get around it, I am manually pushing to the controls array directly. It's a bit hacky, but it works:

`let yourArray = new Form Array();
yourArray.controls.push(new Form Group());`

instead of:

`let yourArray = new Form Array()
yourArray.push(new Form Group())`

--which will throw you into an infinite loop, as you mentioned.

**Comment by ikourfaln** [comment]
So, guys, this features is important and still in the backlog !!
is there any workaround?

**Comment by tettusud** [comment]
For now I am having a flag at the top level  touched =false, and inside valueChanges ,

```
 if(!this.touched){
            // modify the form array
           (<FormArray>  this.formGroup).controls.push(new FormGroup({}));
         }else{
           // restore 
           this.touched = false;
         } 
```

**Comment by ahmadmu** [comment]
I tried adding the FormGroups to the FormArray by pushing them into the controls array, as @cpru2 mentioned. The groups get added but the formarray value doesn't update (my formgroups aren't empty). Is there a way to update the array value manually after adding the groups to the array?

**Comment by omar-dulaimi** [comment]
2020, had to switch back to template driven forms because of this issue!

**Comment by meomar** [comment]
> 2020, had to switch back to template driven forms because of this issue!

Me too :|

**Comment by zealves** [comment]
It works for me:

![image](https://user-images.githubusercontent.com/42573257/87531683-f6b38200-c689-11ea-8a3e-22eff8e58395.png)

**Comment by fbcarpinato** [comment]
Having this issue too

**Comment by astukanov** [comment]
Hi Guys (and @davinkevin ), how can it be that this issue is still open after 2 Years? Even though pull requests were done in the beginning. 
The functionality itself is crucial and leads to a lot of ugly unreadable code when avoiding it manually. Would it be possible to make it a higher priority? Can I somehow contribute to resolve it faster?

**Comment by gabdusch** [comment]
Agree, happy to contribute to help move this issue faster!

**Comment by AndrewKushnir** [comment]
Closing this ticket in favor of #20439, see https://github.com/angular/angular/issues/20439#issuecomment-763976919.
