### ISSUE TITLE
CLI Build Optimization cuts out dynamic enums

### ISSUE THREAD

**Issue by matsko** [angular/angular#23400]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
[ ] Other... Please describe:
</code></pre>

## Current behavior
For some reason if an enum is not a const enum and is also not publicly exported as apart of the public API (or if it's only used in one file), build optimization will turn it into an empty object.

## Expected behavior
Even if not const, the enum should stick around in the compiled JS when build optimized.

## Minimal reproduction of the problem with instructions
1. Clone this `https://github.com/andrewseguin/trying-snackbar`
2. Run `ng serve --prod` (this contains the build optimizer on by default)
3. Open `localhost:4200` in Safari (and watch the world burn)

This can be also tested via `ng build --prod` and looking at the `main-xx.js` file to see how the enum in the example (https://github.com/angular/angular/blob/master/packages/animations/browser/src/render/css_keyframes/css_keyframes_player.ts#L18) is wiped away (look for `.INITIALIZED` and `.DESTROYED` somewhere around an area where `buildStyler` is called.

## What is the motivation / use case for changing the behavior?
There might be other areas of Angular that are experiencing the same issue.

## Environment

<pre><code>
Angular version: HEAD

Browser:
Either Safari or Edge (to see the issue pop up).
 
For Tooling issues:
- Node version: 8.9.3
- Platform:  Mac
</code></pre>

**Comment by filipesilva** [comment]
I looked into this a bit today, and think I know what's happening.

The difference between a `enum` and a `const enum` in TS is that the latter isn't actually around in the transpiled JS. A `const enum` will be wholly replaced by its values everywhere, and its declaration removed from the JS output. You can test this by declaring a `const enum` in a TS file and transpiling it. 

So as far as Build Optimizer is concerned, it never sees or alters `const enums` because Build Optimizer operates on JS files, and `const enum`s don't exist in JS files.

So back to normal `enums`. We do declare normal enums and transform them in Build Optimizer. They go from:

```
export var AnimatorControlState;
(function (AnimatorControlState) {
    AnimatorControlState[AnimatorControlState["INITIALIZED"] = 1] = "INITIALIZED";
    AnimatorControlState[AnimatorControlState["STARTED"] = 2] = "STARTED";
    AnimatorControlState[AnimatorControlState["FINISHED"] = 3] = "FINISHED";
    AnimatorControlState[AnimatorControlState["DESTROYED"] = 4] = "DESTROYED";
})(AnimatorControlState || (AnimatorControlState = {}));
```

to

```
export var AnimatorControlState = /*@__PURE__*/ (function (AnimatorControlState) {
    AnimatorControlState[AnimatorControlState["INITIALIZED"] = 1] = "INITIALIZED";
    AnimatorControlState[AnimatorControlState["STARTED"] = 2] = "STARTED";
    AnimatorControlState[AnimatorControlState["FINISHED"] = 3] = "FINISHED";
    AnimatorControlState[AnimatorControlState["DESTROYED"] = 4] = "DESTROYED";
    return AnimatorControlState;
})({});
```

Where the declaration is assigned to the function call directly, and the function call marked pure. This way there if there is no usage of this variable elsewhere it can be dropped.

Or at least that is what should happen.

Right now it gets transformed into this instead:
```
export var AnimatorControlState;
/*@__PURE__*/ (function (AnimatorControlState) {
    AnimatorControlState[AnimatorControlState["INITIALIZED"] = 1] = "INITIALIZED";
    AnimatorControlState[AnimatorControlState["STARTED"] = 2] = "STARTED";
    AnimatorControlState[AnimatorControlState["FINISHED"] = 3] = "FINISHED";
    AnimatorControlState[AnimatorControlState["DESTROYED"] = 4] = "DESTROYED";
})(AnimatorControlState || (AnimatorControlState = {}));
```

A declaration, followed by a pure function. No assignment. This means the function can always be dropped, and that the variable will be empty.

This seems to happen because explicitly look for enums that start with the number zero. This enum starts with the number one instead. 

So it trips up our enum detection, causes the enum to be detected and processed by another optimization, and ends up broken.

**Comment by filipesilva** [comment]
I have a fix for this particular case in https://github.com/angular/devkit/pull/719.
