### ISSUE TITLE
Implement/port standard set of pipes

### ISSUE THREAD

**Issue by mhevery** [angular/angular#2340]
see https://docs.angularjs.org/api for the behaviro

* [ ] currency
* [ ] date
* [ ] filter
* [X] json
* [x] limitTo
* [X] lowercase
* [ ] number
* [ ] orderBy
* [X] uppercase

**Comment by gdi2290** [comment]
Originally I wanted to do them all but noticed these problems/blocked (listed below) which lead to this issue being opened https://github.com/angular/angular/issues/1625 for more questions about the direction etc. I should have updated it a bit more with questions like Function Bind Syntax, Array Comprehension, and arguments (not working atm)

[Function Bind Syntax (bind operator)](https://github.com/zenparsing/es-function-bind) that's in strawman phase at the moment. With syntax like function-bind then you may not need to use pipes for filters with something like [the examples](https://github.com/zenparsing/es-function-bind#examples)
```es6
import { map, takeWhile, forEach } from "iterlib";

getPlayers()
::map(x => x.character())
::takeWhile(x => x.strength > 100)
::forEach(x => console.log(x));
```
or something like [ng-lodash](https://github.com/rockabox/ng-lodash) in angular one where you allow the developer to provide their own iterator compatible library (just as memo or debounce decorators) rather then having it baked into the framework. 
another example (https://twitter.com/BenLesh/status/602923031934021633)
```es6
function customOp() {
  return this.map(x => 'custom  ' + x);
}

myObservable::customOp().subscribe(success);
```

[ES6 Array Comprehension](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Array_comprehensions)
There is also the question of es6 Array Comprehension in the template syntax but that's probably another directive
```es6
// syntax
[for (x of iterable) x]
[for (x of iterable) if (condition) x]
[for (x of iterable) for (y of iterable) x + y]
/* ... */
[for (i of [ 1, 2, 3 ]) i*i ]; 
```


I was only able to do the super easy ones since they don't have arguments or depends on other things.

currency: probably needs $locale-like-service (unless fine with mvp version)
date: probably needs $locale-like-service (unless fine with mvp version)
filter: need to be able to add arguments (unless file with `filter(arguments, arguments)` for now)
limitTo: need to be able to add arguments  (unless file with `limitTo(5)` for now)
number: probably needs $locale-like-service (unless fine with mvp version)
orderBy: we need something like $parse (Parser methods requires [element] location)

there is also a problem in the pipeline that I have an issue open for  https://github.com/angular/angular/issues/1680

also I can already use the feature of using parentheses for arguments 
[app/components/app.ts#L162](https://github.com/angular-class/angular2-reactive-starter/blob/2f29104a32df4bbbaff82fd28b65316cd92907f8/src/app/components/app.ts#L162) using [GetPipe](https://github.com/angular-class/angular2-reactive-starter/blob/2f29104a32df4bbbaff82fd28b65316cd92907f8/src/common/rxPipes.ts#L38)

**Comment by JohannesHoppe** [comment]
see https://github.com/angular/angular/pull/2956

> Let's not do this as part of angular core, as it won't work with the precompiled templates that we are about to do. Please feel free to publish this as a standalone directive.
-- <cite>@tbosch</cite>

is this really your last word regarding `orderBy`?!

**Comment by itslenny** [comment]
FYI - limitTo was replaced with slice and is finished see #3497 for details.

**Comment by gdi2290** [comment]
`orderBy` was removed
https://github.com/angular/angular/pull/2956
`date` and `number` are in
https://github.com/angular/angular/pull/2877
`filter` was removed
https://github.com/angular/angular/pull/2957
`currency` didn't make it
https://github.com/angular/angular/pull/2464
so the only one left in this list is `currency`

**Comment by itslenny** [comment]
It looks like `currency`, `decimal`, and `percent` pipes were all created as part of `number`.

https://github.com/piloopin/angular/commit/5f28d1473931e85c3c30d7585dd760389cad5e79

**Comment by gkalpak** [comment]
No `filter` and `orderBy` filters in ng2 ? :disappointed: 
(Seriously, is it just to avoid ng-wat (a filter named filter) ?)

**Comment by pkozlowski-opensource** [comment]
There were some problems with filter / orderby and types, don't remember the details, probably only in Dart. IMO we should have them, at least for JS / TS.

`date` and `number` work only in Chrome (due to the use of internationalization API) so they need more work before being usable in practice.

**Comment by flyingmutant** [comment]
Will this be done before the beta? It is hard to imagine any codebase not using `filter` or `orderBy`.

**Comment by JohannesHoppe** [comment]
Right now I'm ordering the array "by hand":

Example:
```
<book *ng-for="#book of books" [book]="book" (rated)="reorderBooks(book)"></book>
```

```
export default class BookRating {
  books: Array<Book>;

  constructor() {
    this.books = [];
  }

  add(title, comment) {
    var newBook = new Book(title.value, comment.value);
    this.books.push(newBook);
  }

  reorderBooks(book: Book) {
    this.books.sort((a, b) => b.rating - a.rating);
  }
}
```

That `rated` event is triggered on any value change. It works, but I'm not happy.
Full example here: https://github.com/Angular2Buch/angular-2-book-rating-app

**Comment by cexbrayat** [comment]
Shouldn't this issue be part of the beta milestone? Not having the `orderBy` and `filter` pipes is a bit painful right now...

**Comment by rosendi** [comment]
Should `SlicePipe` support `Observable`? What do you think?

**Comment by mhevery** [comment]
This is obsolete, and no longer relevant / actionable. To keep our issues clean, we are aggressively closing them.
