### ISSUE TITLE
ActivatedRoute Returns Wrong Values

### ISSUE THREAD

**Issue by danielstern** [angular/angular#23420]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ X ] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
[ ] Other... Please describe:
</code></pre>

## Current behavior

The following service subscribes to the `router.events` observable. Puzzlingly, when responding to this call, the `ActivatedRoute.url` value and the `router.url` value are not the same. No values obtained from `ActivatedRoute` are correct.

```
@Injectable()
export class SagasService {
    constructor(private http: HttpClient, private route : ActivatedRoute, private router : Router ){
        router.events
            .filter(e => e instanceof NavigationEnd)
            .subscribe(e=>{
                console.log(e);
                console.log(router.url);
                console.log(router.routerState);
                console.log(router.routerState.root);

                router.routerState.root.url.subscribe(p=>console.log(p[0].path));
                route.url.subscribe(a=>console.log(a[0].path));
            });
    }
```

## Expected behavior

Accessing ActivatedRoute should provide the correct values.

<pre><code>
Angular version: 5.2.9

Browser:
- [ x ] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: XX  
- Platform:  

Others:

</code></pre>

**Comment by jasonaden** [comment]
I'm sorry but reported issues require a reproduction of the issue. We suggest using [StackBlitz](https://stackblitz.com/fork/angular-gitter), [Plunker](http://plnkr.co/edit/tpl:AvJOMERrnz94ekVua0u5?p=catalogue) or [Github](https://github.com/new).

If this issue persists, please create a reproduction using one of the links above. Describe the difference between the expected and current behavior in a new issue with the reproduction linked.

<hr>

Looks to me like there might be an explanation for this behavior, but I can't tell because there's no reproduction attached. If you want to file a new issue with a repro, please feel free to do so so this can be looked at.
