### ISSUE TITLE
One way databinding bleeds back into parent

### ISSUE THREAD

**Issue by krodyrobi** [angular/angular#23489]
## Current behavior
Passing an array from the parent to the child and splicing the array modifies parents array.

## Expected behavior
One way should allow data to flow from parent to child only

## Minimal reproduction of the problem with instructions
https://github.com/krodyrobi/one-way-binding-ng5

## Environment
```
"@angular/animations": "^5.2.0",
"@angular/common": "^5.2.0",
"@angular/compiler": "^5.2.0",
"@angular/core": "^5.2.0",
"@angular/forms": "^5.2.0",
"@angular/http": "^5.2.0",
"@angular/platform-browser": "^5.2.0",
"@angular/platform-browser-dynamic": "^5.2.0",
"@angular/router": "^5.2.0",
"core-js": "^2.4.1",
"rxjs": "^5.5.6",
"zone.js": "^0.8.19"
```

 
For Tooling issues:
- Node version: v8.9.4
- Platform:  Windows

**Comment by mlc-mlapis** [comment]
@krodyrobi ... but the array is passed from the parent to the child as a reference so it is logical that if you mutate it inside the child the change affects also the same in the parent. What do you expect? That's why the name is `@Input()`.

If you expect that the child should create its own immutable version ... it is necessary to ask why that should be a default behavior (with potential of some performance effects) and not your code responsibility ... whether in the parent or in the child.

**Comment by krodyrobi** [comment]
@mlc-mlapis , thank you for your fast response! To my defence I've just got into using Angular and just now noticed this.

I read one way data binding as "data flows only from parent to child" I assumed that this is somehow guaranteed by the framework. (indeed the case of excessive clones could lead to performance issues, and I see why this would not be desirable as a default behaviour)
Maybe the docs could touch the subject in more detail.

So one way databinding is still affected by data being passed as a reference / value like in normal js.
Two way would then allow the child to change the reference to point to something else completely and have those changes reflected in the parent as well.

It I say this outloud it makes sense, plus if people needed to modify referenced objects without the sideeffects being visible upstream they could selectively choose to clone it.

Thanks again for the help, I think this can be closed (appart from the docs part) but other than that this is not a bug but wrong usage.

**Comment by mlc-mlapis** [comment]
@krodyrobi ... 👍  it is as you summarized. Just maybe good to mention that 2-ways data-binding is really rare in Angular in the most cases it is simply not good pattern which frequently leads to violation of uni-directional principle which is the general rule for Angular.

Change detection (CD) runs always from top to bottom of the tree so any opposite data flow often leads to problems and the a very known error `ExpressionChangedAfter...` because Angular in development mode checks conditions before CD and also after and detects if there are any places where components change their direct inputs during that CD ... which means a potential unstable state then.

**Comment by mlc-mlapis** [comment]
@krodyrobi ... ah, also close your issue. Thanks.
