### ISSUE TITLE
[IVY] Event bindings should trigger directives

### ISSUE THREAD

**Issue by vicb** [angular/angular#23560]
Behavior with the render 2:

```
// ts
@Directive({selector: '[myDir]'})
class MyDir {}

// html
<div (myDir)="..."></div>
```

The directive `MyDir` would be instantiated on the `<div>`.

See the [template parser spec](https://github.com/angular/angular/blob/1a44a0b4a87767236f6eea07deca5e4d8789572f/packages/compiler/test/template_parser/template_parser_spec.ts#L989) for more details.

Updates are required for:
- [x] the runtime (done in #23991)
- [ ] the compiler

**Comment by pkozlowski-opensource** [comment]
Runtime part was done in #23991

**Comment by studioTeaTwo** [comment]
I am trying to manually dispatch the analysis result of the *tagged template literal* to ivy.

This problem seems to prevent the listener from updating in `RenderFlags.Update`.
Because TNode.flags stands,  it assumes the directives exists. But it is'nt, so `generatePropertyAliases` in `listener()` will fail.

example
```
const nodeList = getNodeListFromTaggedTemplateLiteral();
let index = 0;
const apply = (_nodeList) => _nodeList.forEach(node => {
  if (node.nodeType === ELEMENT_NODE) {
    const element = node as Element;
    const attrs = getAttribute(element);
    if (renderFlag & RenderFlags.Create) {
      elementStart(index, element.nodeName, attrs);
    }
    if (eventListener) {
      listener(eventListener.eventName, eventListener.listenerFn); // It's OK if RenderFlags.Create. But ERROR if RenderFlags.Update.
    }
    index++;
    if (element.hasChildNodes()) {
      apply(element.childNodes);
    }
    if (renderFlag & RenderFlags.Create) {
      elementEnd();
    }
  }
});
apply(nodeList);
```

It's going to work if `listener ()` triggers a directive.
