### ISSUE TITLE
Add information about how to install beta and rc releases

### ISSUE THREAD

**Issue by jenniferfell** [angular/angular#23640]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Performance issue
[ ] Feature request
[ X] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
[ ] Other... Please describe:
</code></pre>

## Current behavior

The new content about Angular releases (releases.md) mentions our version number convention and release practices for Beta and RC releases, but we don't say here or in updating.md how to get, install, and find doc for those releases.  

We say this: "We bake quality into our releases&mdash;and let you preview what's coming next&mdash;by providing Beta releases and release candidates (RCs) for each major and minor release."

## Expected behavior

From @IgorMinar in review of that doc in PR https://github.com/angular/angular/pull/23551
I think we should tell people how to install these and where to find documentation for them.

Maybe a table with release type vs npm tag/cli flag used for installation, link to docs, github branch would help? I can make it for you when I'm in the office.

From me ( @jenniferfell )
I think this is a good addition, and perhaps affects updating.md as well, because the "how you do things" is there...so "how to find and install pre-release versions" might go there. Another idea might be to add a page just about pre-release versions, which can include numbering scheme, where to get them, and a reminder on how to submit feedback.

Creating this separate issue so we can release the current doc and spend the appropriate time to get this addition "right." 

## Environment

<pre><code>
Angular version: X.Y.Z

Browser:
- [ ] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: XX  
- Platform:  

Others:

</code></pre>

**Comment by IgorMinar** [comment]
we should also clarify the Angular Labs description because it currently says that labs projects must be in a separate repo or a branch, but for example @angular/bazel or ivy are not. Depending on the feature, we sometimes put the labs/unfinished feature behind a flag (ivy) or a separate (undocumented) package (@angular/bazel).

I think in the case of bazel, this might be confusing and we should figure out a way to to clarify this - one option would be adding a README.md file into the @angular/bazel package which documents this package as an Angular Labs project. This readme would then be part of our repo and would also show up on the npm package page: https://www.npmjs.com/package/@angular/bazel

**Comment by josephperrott** [comment]
Closing this issue as this issue is no longer relevant.  The related docs have been updated to cover the issues discussed.
