### ISSUE TITLE
Angular Tutorial --> 6. Services --> Error on ng serve --> rxjs/Rx"' has no exported member 'of'

### ISSUE THREAD

**Issue by soumenbarua** [angular/angular#23750]
ERROR in src/app/hero.service.ts(3,22): error TS2305: Module '"C:/Users//MyHandsOn/angular-tour-of-heroes/node_modules/rxjs/Rx"' has no exported member 'of'.

**Comment by soumenbarua** [comment]
ERROR in src/app/hero.service.ts(3,22): error TS2305: Module '"C:/Users/s6189449/Documents/Code/Temp/WebCampTrainingKit-2016.02.09/MyHandsOn/angular-tour-of-heroes/node_modules/rxjs/Rx"' has no exported member 'of'.

**Comment by soumenbarua** [comment]
I just followed the steps under:
https://angular.io/tutorial

And at the end of 6. Services --> https://angular.io/tutorial/toh-pt4 I get this error on using "ng serve" command.

**Comment by edwin-hendriks** [comment]
It seems the text in the tutorial:
```
import { Observable, of } from 'rxjs';
...
getHeroes(): Observable<Hero[]> {
  return of(HEROES);
}
```
should be changed to:
```
import { Observable } from 'rxjs';
...
getHeroes(): Observable<Hero[]> {
  return Observable.of(HEROES);
}
```
Works for me. Not sure but this seems due to version changes in a newer version of 'rxjs'.

**Comment by soumenbarua** [comment]
Hi edwin-hendriks, the fix suggested in the following post worked for me:
https://github.com/angular/angular/issues/23753

**Comment by mhevery** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).

**Comment by edwin-hendriks** [comment]
It seems okay to close this. The problem was introduced because I started with the tutorial on version 5.2.0 and in a period of 1 day both angular as well as the tutorial where upgraded to 6.0.0. I just upgrade to 6.0.0 as well and this has solved the issue for me as well. 

I really thought it to be an issue that needed to be solved and therefore reported it here. There may be way to prevent people from reporting issues, by preventing similar issues at all. Of course, I leave this up to the great Angular team 🥇
