### ISSUE TITLE
docs: add inherited members as key terms for search

### ISSUE THREAD

**Issue by petebacondarwin** [angular/angular#23800]
You ought to be able to find `ViewRef` by searching for `detach`.

**Comment by ericmartinezr** [comment]
Sorry for adding noise here, but what about searching for [`COMMON_DIRECTIVES`](https://github.com/angular/angular/blob/c8a1a14b87e5907458e8e87021e47f9796cb3257/packages/common/src/directives/index.ts#L42) or [`COMMON_PIPES`](https://github.com/angular/angular/blob/c8a1a14b87e5907458e8e87021e47f9796cb3257/packages/common/src/pipes/index.ts#L42) and similars. I should be able to get to their own docs (although it looks like they don't have their own) and to [`CommonModule`](https://angular.io/api/common/CommonModule) which exports them.

**Comment by petebacondarwin** [comment]
@ericmartinezr - that is indeed noise :-P
If I am correct, constants like `COMMON_DIRECTIVES` are not actually part of the public API, which is why they do not appear in the docs at all, let alone the search.

**Comment by ericmartinezr** [comment]
/cries
@petebacondarwin you can then delete these comments :P

**Comment by FrederikSchlemmer** [comment]
@petebacondarwin This seems to be a typical behaviour of classes which extend other classes. 

Example: 
- EmbeddedViewRef extends ViewRef
- ViewRef extends ChangeDetectorRef

Current behaviour:
All classes could only be found by their own implemented methods.

Expected behaviour:
All classes could be found by their own implemented methods and the extended methods.

Do you got some tips where to start?

**Comment by petebacondarwin** [comment]
I agree that we should also capture inherited members as key terms for search.
If you want to have a go at a PR then one place to look is https://github.com/angular/angular/blob/b6af8700ce8b5413decbd9fe3422b786ba864d78/aio/tools/transforms/angular-base-package/processors/generateKeywords.js#L100

**Comment by petebacondarwin** [comment]
I have a fix for this #26676
