### ISSUE TITLE
Annoying tooltip hiding the next menu

### ISSUE THREAD

**Issue by siva636** [angular/angular#23814]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Performance issue
[ ] Feature request
[x] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
[ ] Other... Please describe:
</code></pre>

## Current behavior

When hovering over a menu item, an annoying tooltip pops up and hiding the next menu.
(see the image bellow)

## Expected behavior

Tooltip must be disabled.

## Minimal reproduction of the problem with instructions
Visit https://angular.io/docs
Hover mouse pointer over a menu item
Watch the annoying tooltip hiding the other menu
![screenshot from 2018-05-10 09-59-13](https://user-images.githubusercontent.com/3191656/39852208-eb23f7be-5438-11e8-9777-1acdfedb017a.png)

## What is the motivation / use case for changing the behavior?

Developers use the doc site several times, this tooltip promptly annoys each and every time when hover over the menu.

## Environment

<pre><code>
Angular version: X.Y.Z

Browser:
- [x ] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [x] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: XX  
v8.9.1
- Platform:  
Linux
Others:

</code></pre>

**Comment by gkalpak** [comment]
This is "by design". The tooltip provides useful context regarding the hovered menu item. It only appears after some small delay, so it shouldn't appear unless you are hovering over an item unsure whether to click it or not :smiley:
Also, the tooltip's place is relative to the cursors position, so you could move the cursor to the right to avoid hiding the next item.

Theoretically, we could use a [Material tooltip][1], which would give us more options wrt to placing, styling, etc., but tbh I don't think it is worth the extra bytes and complexity.

[1]: https://material.angular.io/components/tooltip/overview
