### ISSUE TITLE
Router live example from 6.0 docs hangs

### ISSUE THREAD

**Issue by chalin** [angular/angular#23820]
## Current behavior && Minimal reproduction of the problem with instructions

1. Visit the [Routing & Navigation](https://angular.io/guide/router) docs.
2. Launch the [live example](https://angular.io/generated/live-examples/router/stackblitz.html).
3. In the app, click on the _Crisis Center_ tab.

Result: **The app "hangs"**.

This happens in the latest version of Chrome and Firefox:

<img width="1436" alt="screen shot 2018-05-10 at 10 08 06" src="https://user-images.githubusercontent.com/4140793/39949156-1552cb32-5547-11e8-9712-b5a5b940db64.png">

## Environments

- Angular version: 6.0.0
- Stackblitz
- MacOS 10.13.4:
  - Chrome (desktop) version 66.0.3359.139 (Official Build) (64-bit)
  - Firefox version 60.0 (64-bit)

Here is a screenshot of the app after clicking on the _Crisis Center_ tab. Notice that the both the _Crisis Center_ and the _Heroes_ tabs are shown as "active". Then the app doesn't make any further progress.

cc @kwalrath

**Comment by chalin** [comment]
Oops, I had forgotten the screenshot. I've added it to the original comment now.

Btw, I've tested all prior versions of the (online) app, and none of them work.

**Comment by brandonroberts** [comment]
Thanks @chalin. @EricSimons will you take a look into this issue?

**Comment by EricSimons** [comment]
@brandonroberts yes absolutely- I think this has to do with our teleport serializer for displaying the console logs/errors (i.e. if the logged data is massive it'll cause the browser to hang :(

Will circle back once I've confirmed & fixed 👍

**Comment by brandonroberts** [comment]
👍

**Comment by EricSimons** [comment]
My initial suspicion was correct :) I've set the max execution time to 50ms for serialization. However, there's still a noticeable lag (maybe 0.5s) when clicking on the "crisis center" simply due to how many logs are being outputted w/ _massive_ objects in the arguments.

To solve this, we could drop the max execution time further, but I fear this would cause negative UX on slower devices (mobile/etc). Most ideal option on our end would be cutting down the number of logs coming from this example/the size of the objects being passed as arguments to console.log

Would love to hear everyone's thoughts!

**Comment by chalin** [comment]
Thanks! The app isn't hanging anymore so I'll close this.

IMHO, the best solution is probably to drop some of the logging from the app. I'll let @brandonroberts et all tackle that if they'd like.
