### ISSUE TITLE
UrlMatcher does not pass correct path to lazy loaded module

### ISSUE THREAD

**Issue by dieguezz** [angular/angular#23866]
## I'm submitting a...

[ ] Regression (a behavior that used to work and stopped working in a new release)
[X] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
[X] Other... Please describe: Not sure if its a bug

## Current behavior
I am using a matcher to be able of sharing the same exact path for two different lazy loaded modules.
The matcher checks if there is a queryParam called `featureFlag=showBar` to show either `foo` module or `bar` module.

It works as expected for the main route, but if you try to navigate to a children path, the `foo-routing.module.ts` or `bar-routing.module.ts` (only foo in stackblitz example has a log output) should receive the route as normally expected. Instead its always receiving `[]`

## Expected behavior
modules should receive urlMatcherResult correctly

## Minimal reproduction of the problem with instructions
https://stackblitz.com/edit/angular-jgtlzw

Check console, and main logic is in:
`app/app-routing.routes.ts`
`app/foo/foo-routing.module.ts`

Angular version: 6.0.0

Browser:
- [X] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: 8.9.0 ? also stackblitz's version
- Platform: Mac

**Comment by danielelidio** [comment]
looking at the documentation at [](https://angular.io/api/router/UrlMatcher) it was not clear to me but looking at the internal code I could realize that in the matcher function you must return `null` value or the **portion of the url that was consumed** by your provided function so that **Angular knows that it should pass to the nested router only the remaining portion of the url.**

Checking your provided code I see that in your `fooMatcher` function **you are returning the whole consumed url**, so, Angular understands that the whole url was consumed and pass to the nested routere an empty array to be consumed.

if you change your `fooMatcher` to return only the portion of the url that was used there it works.
See: 
```

const fooMatcher = (url: UrlSegment[]) => {
  console.log(url);
  console.log('isRoute', isRoute(url, 'foo'))
  console.log('isFf', isFeatureFlag('showBar'))
  return (isRoute(url, 'foo') && !isFeatureFlag('showBar')) ? { consumed: [new UrlSegment(url[0].path, url[0].parameters)] } : null
}
```
Or you can see it at: [](https://stackblitz.com/edit/angular-vfvnldl)

**P.S:** In the internal code it is marked as experimental

I hope it helps! :)

**Comment by ahmedjaad** [comment]
@danielelidio  Maybe this should be reported as a separate issue so the docs can be updated with more information
