### ISSUE TITLE
Error: Runtime compiler is not loaded in angular6 --prod mode

### ISSUE THREAD

**Issue by pankajsri03** [angular/angular#23878]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ x] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
[ ] Other... Please describe:
</code></pre>

## Current behavior
I was dynamically creatingn a component in angular5 .After migrating my app to angular6 it doesnt work.

```js
export class HtmlOutletDirective implements OnChanges {
  @Input() html: string;
  constructor(private vcRef: ViewContainerRef, private compiler: Compiler, private translate: TranslateService) {
  }

  ngOnChanges() {
    const html = this.html;
    if (!html) { return; }

    @Component({
      selector: 'ccw-dynamic-component',
      template: `
        <div [innerHtml]="innerHtmlTemplate">
        </div>
        `
    })

    class DynamicHtmlComponent {
      private innerHtmlTemplate: any = '';
      constructor(private httpClient: HttpClient, private sanitizer: DomSanitizer) {
        this.httpClient.get(html, { responseType: 'text' }).subscribe((htmlContent) => {
          this.innerHtmlTemplate = sanitizer.bypassSecurityTrustHtml(htmlContent.toString());
        });
      }
    }

    @NgModule({
      imports: [CommonModule],
      declarations: [DynamicHtmlComponent]
    })

    class DynamicHtmlModule { }

    this.compiler.compileModuleAndAllComponentsAsync(DynamicHtmlModule)
      .then(factory => {
        const compFactory = factory.componentFactories.find(x => x.componentType === DynamicHtmlComponent);
        const compRef = this.vcRef.createComponent(compFactory, 0);
      });


  }
```

This used to generate a component for me based on path specified.It used to work perfectly in dev/prod both.However after updating the app to angular6. It is not working in production.
It gives me the below error:
Generic error: Runtime compiler is not loaded
logger.js:47 Error stack trace: Error: Runtime compiler is not loaded
    at Le (core.js:3286)
    at t.compileModuleAndAllComponentsAsync (core.js:3346)
    at l.ngOnChanges (html-outlet.directive.ts:52)

## Expected behavior
the dynamic component should load

## Environment

<pre><code>
Angular version: 6.0.0

Browser:
- [x ] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: 8.9.1
- Platform:  Windows

Others:

</code></pre>

**Comment by uma075** [comment]
facing same issue

**Comment by IgorMinar** [comment]
It sounds like you were running your application in the JIT mode in v5 but then switched over to the AOT mode in v6. The runtime compiler is not available and has never been available in the AOT mode unless you brought it yourself.

Can you please verify that you are bootstrapping your application with https://angular.io/api/core/PlatformRef#bootstrapModule (JIT mode) rather than https://angular.io/api/core/PlatformRef#bootstrapModuleFactory (AOT mode) or if you are using AngularCLI that you have AOT mode turned on in your angular.json, example: https://github.com/angular/angular/blob/23a98b9e5134df3b96dd932173ce86384d72ada0/aio/angular.json#L21

**Comment by marianobarbuscio** [comment]
> Do not and i repeat do not import your feature modules in app module and also when addressing feature modules in your routes use this format, this can save you several hours buddy
> 
> ```
> { path: 'auth', loadChildren: './modules/auth/auth.module#AuthModule' },
> { path: 'ingestion', loadChildren: './modules/ingestion-dashboard/ingestion-dashboard.module#IngestionDashboardModule'},
> ```
> Do not use function signature

The same was happening to me. @IgorMinar function signature breaks the aot build in prod mode. Should the issue be reopened?

**Comment by Tinadim** [comment]
> Do not and i repeat do not import your feature modules in app module and also when addressing feature modules in your routes use this format, this can save you several hours buddy
> 
> ```
> { path: 'auth', loadChildren: './modules/auth/auth.module#AuthModule' },
> { path: 'ingestion', loadChildren: './modules/ingestion-dashboard/ingestion-dashboard.module#IngestionDashboardModule'},
> ```
> Do not use function signature

Same thing happened to me. Nice catch @shanurrahman

**Comment by tzjoke** [comment]
Not work in angular7. Still get `Runtime compiler is not loaded` with lazy loading in prod mode. Is there any solution for ng7?

**Comment by sandisototo** [comment]
> ng7

Same here been investigating this for over 20 hours, I tried most of the suggestion in many forums none of them seem to work :'(

**Comment by mlc-mlapis** [comment]
@sandisototo ... there are issues already which describe how to do it. I used that in Angular 5 and 6. Not sure about Angular 7, I didn't test it with that.

**Comment by sandisototo** [comment]
@mlc-mlapis I have my ```app-routing-module.ts``` setup like this for all my routes( By the way I tried ```loadChildren: () => HomeModule)``` also)

![screen shot 2019-02-26 at 3 25 52 pm](https://user-images.githubusercontent.com/17904279/53416085-65cc0000-39db-11e9-84de-0ac9c42eab86.png)
![screen shot 2019-02-26 at 3 27 29 pm](https://user-images.githubusercontent.com/17904279/53416083-65cc0000-39db-11e9-914e-e1d6273dd641.png)

I get the same error:
<img width="695" alt="screen shot 2019-02-26 at 10 00 10 am" src="https://user-images.githubusercontent.com/17904279/53416201-a3308d80-39db-11e9-997d-703f0d962b68.png">

**Comment by alexzuza** [comment]
@sandisototo 
Using `loadChildren: () => HomeModule` requires jit compiler.
If you have a problem with `loadChildren` property that uses string then please create small reproduction

**Comment by sandisototo** [comment]
@alexzuza What do you mean by a small reproduction?

**Comment by mlc-mlapis** [comment]
@sandisototo ... as I said before ... search Angular issues for `JitCompiler` ... you should find how to go ...

**Comment by alexzuza** [comment]
@sandisototo I mean you could create a github repository with a minimum amount of code that uses Angular 7 and shows your issue.

**Comment by farajfarook** [comment]
**Just sharing my rare experience, it can help someone else.**

I had two submodules with the same path `./app/apps.module#AppsModule` in two different modules.
Due to a known issue in angular https://github.com/angular/angular-cli/issues/10128, I couldn't get this dynamically loaded using LoadChildren.

I tried to use `LoadChildrenCallback` as a work around. But as I use AOT in production, I couldn't get it done as well.

The workaround i did was to load the SubModules by navigating to the parent folder.
ie in my module `storage` I added the submodule `apps` as below
```
const routes: Routes = [
    { path: 'apps', loadChildren: "../storage/apps/apps.module#AppsModule" },
];
```

**Comment by puravupadhyay** [comment]
A suggestion for CLI - should flag-up when we build using --aot or --prod flag

**Comment by knnhcn** [comment]
> Do not and i repeat do not import your feature modules in app module and also when addressing feature modules in your routes use this format, this can save you several hours buddy
> 
> ```
> { path: 'auth', loadChildren: './modules/auth/auth.module#AuthModule' },
> { path: 'ingestion', loadChildren: './modules/ingestion-dashboard/ingestion-dashboard.module#IngestionDashboardModule'},
> ```
> 
> Do not use function signature

Just came across this issue but strangely in the official docs it's refering to use arrow function and not mentioning any problems with aot, see [https://angular.io/guide/lazy-loading-ngmodules#routes-at-the-app-level](Lazy Loading Feature Modules).

I remember some time ago that the official docs also stated to use lazy loading syntax like yours, but it looks like it has changed since.

**Comment by puravupadhyay** [comment]
Changed in Angular 8. Angular 7 docs still has that: https://v7.angular.io/guide/lazy-loading-ngmodules

**Comment by rcollette** [comment]
I'm confused.   The deprecated string syntax is the only one that works in Angular 7 when lazy loading and using AOT.

Is it a bug that the function style is not working in this mode and is that fixed in Angular 8?

**Comment by onderceylan** [comment]
In order to eagerly load modules with a function reference when AOT enabled for Angular v7 and below, you need to create an NgFactory module as you can see from this PR - https://github.com/angular/angular/pull/13909.

A working solution for me was creating a clone of my module and adding `.ngfactory` postfix to the filename and also adding `NgFactory` postfix to the module class name.

```typescript
import { FirstPageModuleNgFactory } from '../pages/first-page.module.ngfactory';
import { SecondPageModuleNgFactory } from '../pages/second-page.module.ngfactory';

export function loadFirstPageModule() {
    return FirstPageModuleNgFactory;
}

export function loadSecondPageModule() {
    return SecondPageModuleNgFactory;
}

const routes: Routes = [
    {
        path: '',
        component: HomePageComponent,
        children: [
            {
                path: '',
                redirectTo: 'first',
                pathMatch: 'full',
            },
            {
                path: 'first',
                loadChildren: loadFirstPageModule,
            },
            {
                path: 'second',
                loadChildren: loadSecondPageModule,
            },
        ],
    },
];
```

**Comment by akvaliya** [comment]
I am also using this method to add dynamic component & getting this error in Angular 8. How can i resolve it. Is there any way to make it work with aot?
