### ISSUE TITLE
"Expression form not supported." when compiling library project with InjectionToken

### ISSUE THREAD

**Issue by magnattic** [angular/angular#23904]
## I'm submitting a...
<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request 
</code></pre>

## Current behavior
When trying to build a new Angular CLI library that uses an InjectionToken, I get the following error:
> Error encountered in metadata generated for exported symbol 'TestLibComponent':
> Metadata collected contains an error that will be reported at runtime: Expression form not supported.

## Expected behavior
No error.

## Minimal reproduction of the problem with instructions
- ng new cli-test
- cd cli-test
- ng g library test-lib
- Change test-lib.component.ts to this: 
```
import { Component, OnInit, Inject, PLATFORM_ID } from '@angular/core';

@Component({
  selector: 'lib-test-lib',
  template: `
    <p>
      test-lib works!
    </p>
  `,
  styles: []
})
export class TestLibComponent implements OnInit {
  public x: object;

  constructor(@Inject(PLATFORM_ID) appId: object) {
    this.x = appId;
  }

  ngOnInit() {}
}
```
- ng run test-lib:build

Then the build error will appear. 
<details>
 <summary>Full error output</summary>

```
BUILD ERROR
C:/Users/.../code/Playground/cli-versions/cli-error/projects/test-lib/src/lib/test-lib.component.ts:3:1: Error encountered in metadata generated for exported symbol 'TestLibComponent':
 C:/Users/.../code/Playground/cli-versions/cli-error/projects/test-lib/src/lib/test-lib.component.ts:15:43: Metadata collected contains an error that will be reported at runtime: Expression form not supported.
  {"__symbolic":"error","message":"Expression form not supported","line":14,"character":42}
Error: C:/Users/.../code/Playground/cli-versions/cli-error/projects/test-lib/src/lib/test-lib.component.ts:3:1: Error encountered in metadata generated for exported symbol 'TestLibComponent':
 C:/Users/.../code/Playground/cli-versions/cli-error/projects/test-lib/src/lib/test-lib.component.ts:15:43: Metadata collected contains an error that will be reported at runtime: Expression form not supported.
  {"__symbolic":"error","message":"Expression form not supported","line":14,"character":42}
    at C:\Users\...\code\Playground\cli-versions\cli-error\node_modules\@angular\compiler-cli\src\metadata\collector.js:707:31
    at Array.forEach (<anonymous>)
    at validateMetadata (C:\Users\...\code\Playground\cli-versions\cli-error\node_modules\@angular\compiler-cli\src\metadata\collector.js:695:46)
    at MetadataCollector.getMetadata (C:\Users\...\code\Playground\cli-versions\cli-error\node_modules\@angular\compiler-cli\src\metadata\collector.js:550:21)
    at MetadataCache.getMetadata (C:\Users\...\code\Playground\cli-versions\cli-error\node_modules\@angular\compiler-cli\src\transformers\metadata_cache.js:86:41)
    at Object.getSourceFileMetadata (C:\Users\...\code\Playground\cli-versions\cli-error\node_modules\@angular\compiler-cli\src\transformers\compiler_host.js:112:56)
    at Object.readMetadata (C:\Users\...\code\Playground\cli-versions\cli-error\node_modules\@angular\compiler-cli\src\transformers\metadata_reader.js:46:37)
    at TsCompilerAotCompilerTypeCheckHostAdapter.getMetadataFor (C:\Users\...\code\Playground\cli-versions\cli-error\node_modules\@angular\compiler-cli\src\transformers\compiler_host.js:464:38)
    at StaticSymbolResolver.getModuleMetadata (C:\Users\...\code\Playground\cli-versions\cli-error\node_modules\@angular\compiler\bundles\compiler.umd.js:19516:45)
    at StaticSymbolResolver._createSymbolsOf (C:\Users\...\code\Playground\cli-versions\cli-error\node_modules\@angular\compiler\bundles\compiler.umd.js:19304:29)
```
</details>
I had similar problems with the usage of own InjectionTokens.

## Environment
<pre><code>
Angular version: 6.0.0
Angular CLI version: 6.0.0

For Tooling issues:
- Node version: 9.4.0
- Platform:  Windows 10

</code></pre>

**Comment by danielelidio** [comment]
I followed your steps and I got the same error in here.

Looking at the angular internals, more specifically at: `packages/core/application_tokens.ts:53` (please, see at this [link](https://github.com/angular/angular/blob/d4b6c41a5f8ca84082f90a5d738b23d3ba71bbb0/packages/core/src/application_tokens.ts#L53))

**The statement: `export declare const PLATFORM_ID: InjectionToken<Object>;` shows us that the  `PLATFORM_ID` token is defined as `Object` (with upper 'O')**

However, if we take a look at the generated `test-lib.component.ts:15` the statement `constructor(@Inject(PLATFORM_ID) appId: object)` shows the **`PLATFORM_ID` token is being injected into a variable which type is `object` with lower 'o'**, so it does not match right?

By changing `object` to `Object` it worked! \o/

**So that seems to be a bug on the angular generator.**
I tried to find at Angular CLI where does it is generated but I was not able to find (if someone knows I would be pleased to know).

Meanwhile, **just change `object` to `Object` and it will work!**

Have you a good night!

**Comment by phl3x0r** [comment]
Object should be with a capital O, but I don't know why you think that's a problem with the generator?
The above code is not generated.

**Comment by danielelidio** [comment]
Hi @phl3x0r, good morning! I followed the bug reproduction steps and I got  very same error that @magnattic described. I checked the file `test-lib.component.ts` on the line 15 and the `appId` being typed as `object`, and by changing it to `Object` it got it working.

As you can see, in the generated code I got `object` but in the angular internals the token is specified as being `Object` and that made me to suspect that the problem was it.

If that's is the bug, It could be solved by either:

1. Changing the generator (or whatever other thing that put that code in hahaha) to generate the specified statement using `Object` instead of `object`

2. Changing the angular token token specification to `export declare const PLATFORM_ID: InjectionToken<object>` instead of `export declare const PLATFORM_ID: InjectionToken<Object>`

As you mentioned, Typescript recommends using `object`, I agree with you and I would suggest the second option in correction of what I previously said.

**Comment by phl3x0r** [comment]
@danielelidio the only problem with this, is that the code you refer to (which contains the reference to Object) is not generated.
This is the generated code from `ng g library test-lib`:

```
import { Component, OnInit } from '@angular/core';

@Component({
  selector: 'lib-test-lib',
  template: `
    <p>
      test-lib works!
    </p>
  `,
  styles: []
})
export class TestLibComponent implements OnInit {

  constructor() { }

  ngOnInit() {
  }

}
```
So, there is no reference to Object (or the injection token) before you do the step:

- Change test-lib.component.ts to this:
```
import { Component, OnInit, Inject, PLATFORM_ID } from '@angular/core';

@Component({
  selector: 'lib-test-lib',
  template: `
    <p>
      test-lib works!
    </p>
  `,
  styles: []
})
export class TestLibComponent implements OnInit {
  public x: object;

  constructor(@Inject(PLATFORM_ID) appId: object) {
    this.x = appId;
  }

  ngOnInit() {}
}
```

**Comment by GeorgeKnap** [comment]
I am getting this in my librar and problem is in this typ component constructor: 
```
constructor(
    @Inject(MAT_DIALOG_DATA) public data: { widget:  GridsterWidget }
  ) { }
```

when I change it to this form, build succeeeds!
```
 constructor(
    @Inject(MAT_DIALOG_DATA) public data: DialogInputData
  ) { }     
 interface DialogInputData {
  widget: GridsterWidget;
}
```

**Comment by danielelidio** [comment]
Hi @GeorgeKnap !

Well, I could not reproduce what you mentioned. Please take a look at this [StackBlitz example](https://stackblitz.com/edit/angular-eouvim-kkdit6?file=app/dialog-data-example.ts) I've done for reference.

I would encourage you to provide more info about the error you've got.

**Comment by GeorgeKnap** [comment]
@danielelidio Hi! I'm curious how can you tell in stackblitz that it's working or not? How do you run library build?

**Comment by kctang** [comment]
I am having similar error with classes that injects dialog data. Sharing the workaround for this issue - add `// @dynamic` to such classes.

This solution was described in https://github.com/angular/angular/issues/18867.

**Comment by spenoir** [comment]
Just removing the type for data is a good enough temporary workaround for me

**Comment by ArmandoPerdomo** [comment]
I got this error because I had

`@Inject(MAT_DIALOG_DATA) public data: {title: string, items: string[]}`

I change it to 

`@Inject(MAT_DIALOG_DATA) public data: MyInterfaceData`

and it works

**Comment by JoostK** [comment]
With v12 now allowing libraries to be compiled with the Ivy compiler, this issue has been resolved.
