### ISSUE TITLE
Router replaces + by spaces in query params

### ISSUE THREAD

**Issue by victorlevasseur** [angular/angular#23989]
## I'm submitting a...

<pre><code>
[X] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
[ ] Other... Please describe:
</code></pre>

## Minimal reproduction of the problem with instructions
When opening an Angular 5 app with a query param containing a "plus" character, the router seems to replace it with a space character. Prior to this major version, it used to replace the plus with its encoded form (```%2B```).

Note: the URL is changed in the browser URL bar too.

## Environment

<pre><code>
Angular version: 5.2.10

Browser:
- [ ] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [X] Firefox version 60
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX

**Comment by jasonaden** [comment]
I'm sorry but reported issues require a reproduction of the issue. We suggest using [StackBlitz](https://stackblitz.com/fork/angular-gitter), [Plunker](http://plnkr.co/edit/tpl:AvJOMERrnz94ekVua0u5?p=catalogue) or [Github](https://github.com/new).

If this issue persists, please create a reproduction using one of the links above. Describe the difference between the expected and current behavior in a new issue with the reproduction linked.

<hr>

@victorlevasseur Thanks for the issue and it sounds like something we might need to look into. It could also be related to Firefox as it looks like that's the browser you're listing here. Just because this one is being closed doesn't mean it isn't an issue. So if you can create a StackBlitz showing the problem, that would be great. Then just create a new issue.
