### ISSUE TITLE
innerText does not work since Chrome 66

### ISSUE THREAD

**Issue by alagane** [angular/angular#23988]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[X] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
[ ] Other... Please describe:
</code></pre>

## Current behavior

`fixture.debugElement.query(By.css(selectorCss)).nativeElement.innerText` is not the value we should get, it seems to only give whitespaces, but innerHTML give the right value.

## Expected behavior

`fixture.debugElement.query(By.css(selectorCss)).nativeElement.innerText` should return the text in the element with eventually some effects (like uppercase the text).

## Minimal reproduction of the problem with instructions

In a unit test, I create a component fixture with Test bed, and I use this fixture: `fixture.debugElement.query(By.css(selectorCss)).nativeElement.innerText`, it stopped working since Chrome 66 and I don't really know where to look for.

## What is the motivation / use case for changing the behavior?

I think it is not the expected behavior so the bug should be corrected.

## Environment

<pre><code>
Angular version: 5.1.1

Browser:
- [X] Chrome (desktop) version 66
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: 8.11.2 
- Platform: Linux 

Others:

The tests not passing are here, and innerText is empty instead of containing the text, it worked before Chrome 66.
https://gitlab.com/linagora/petals-cockpit/blob/master/frontend/src/app/features/cockpit/workspaces/petals-content/petals-component-view/petals-component-operations/petals-component-operations.component.spec.ts
</code></pre>

**Comment by vicb** [comment]
@alagane could you please provide a repro as asked in the issue template ?

**Comment by alagane** [comment]
@vicb What is the best way to do it? Create a new project with minimum dependencies and tests to reproduce the bug? Can I run tests in tools like Stackblitz?

**Comment by gkalpak** [comment]
@alagane, you can either create a StackBlitz project that shows the issue or a repo thaty we can check out (along with the necessary steps to build and run the code). (Generally, it is easier for us to work with a StackBlitz project.)
In both cases, make sure you only include the minimal amount of code (including libraries, packages, etc) that are necessary to reproduce the problem.

If you want to take a stub at creating a StackBlitz project with tests, you can use the one provided in our [Testing][1] guide as a [starting point][2].

##
<sub>
BTW, I find it weird that `nativeElement.innerText` stopped working in tests, since (afaik) `nativeElement` refers to the "raw" DOM node.
</sub>

[1]: https://next.angular.io/guide/testing
[2]: https://next.angular.io/generated/live-examples/testing/specs.stackblitz.html

**Comment by alagane** [comment]
I can't reproduce it (I tried with same dependencies), so it must be very specific to our project. I close the issue then.
Thank you for your help ;)
