### ISSUE TITLE
angular's npm packaging structure is invalid

### ISSUE THREAD

**Issue by shlomiassaf** [angular/angular#24020]
Because resolving the **package.json** of a module is done using the file system the current structure of **secondary** packages (e.g. `@angular/core/testing`) is invalid.

When webpack/ts resolves `@angular/core/testing` it will get it from 

`node_modules/@angular/core/testing/package.json`

Which has `  "module": "../fesm5/testing.js" `

so the resolved module is:

`node_modules/@angular/core/fesm5/testing.js`

Later, when webpack wants to find the `sideEffects` it will search for **package.json** and the logic for that is simple, search for the file if not exist go up 1 folder and repeat.

This will end up with the **package.json** of `@angular/core`.

In practice this does not cause problems because the sideEffects is set on the root package.json and apply to all but if a sub-package will require specific setup it won't work.

Anyway, it's incorrect.

Fore more details see the issue I opened (webpack/webpack#7327) and @sokra s response.

**Comment by alan-agius4** [comment]
This seems to be a general problem with APF.

//cc @IgorMinar

**Comment by IgorMinar** [comment]
I've just looked into this and I think that saying that the structure is "invalid" is a bit too harsh because for most packages there is no harm.

The way webpack resolves the sideEffects flag is a bit inconsistent the normal resolution, but given that this resolution is the opposite of the normal module resolution, I understand that implementing the resolution from a module to package.json correctly would require extra machinery which is not needed most of the time.

My recommendation is to just ignore this, since all @angular/ framework packages are side effect free, and so should be most component libraries. 

If one really needs to declare that certain paths in a package have side effects, this can be done via the main package.json by declaring the `"sideEffects"` as an array that contains the list of the entry-points with side effects:

e.g.:

```
{
  "name": "your-project",
  "sideEffects": [
    "./some/entry-point-with-side-effects1",
    "./some/entry-point-with-side-effects2"
  ]
}
```

see: https://webpack.js.org/guides/tree-shaking/#mark-the-file-as-side-effect-free
