### ISSUE TITLE
Feature: ability to add a meaning/description to an ICU messages

### ISSUE THREAD

**Issue by jaska45** [angular/angular#24080]
I have the following string in a template

```html
<p i18n="plural|">I have {ski, plural, one {{{ski}} ski} other {{{ski}} skis}} and {car, plural, one {{{car}} car} other {{{car}} cars}}.</p>
```

When I run xi18n three unit elements are created. Only the first one has the meaning attribute.

## I'm submitting a...
<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
[ ] Other... Please describe:
</code></pre>

## Current behavior
Meaning attribute is added only to the first unit element

## Expected behavior
Meaning attribute should be added to all three unit elements

## Minimal reproduction of the problem with instructions
Add the following p element into a template and run xi18n

## Environment

<pre><code>
Angular version: 6.0.2

Browser: all

**Comment by vicb** [comment]
Please give a reproduction OR at least the exact template, the exact output and what output you expect. Thanks.

**Comment by jaska45** [comment]
https://plnkr.co/edit/UqTRzbqGRZcdnkjTiKBY?p=info

If you extract the string you will get three unit elements. Only first one has the meaning attribute. I tried to include XLIFF output here but this platform does not let me to include it such way that it would be readable.

Create a matching Angular project and run the extract tool to see the issue.

**Comment by jaska45** [comment]
Here is the screenshot about XLIFF output.

![untitled](https://user-images.githubusercontent.com/10090968/40520029-f6a205b4-5f77-11e8-9322-425653af0407.png)

**Comment by jaska45** [comment]
This sample has another issue. In the template we have one logical string. However once extracted it is split to three different units. A localization tool must try to parse them back into the logical string but that might not be possible. In above sample all three units are extracted into consecutive unit elements. However if some other string anywhere in the app uses the string any any of these three parts there is a string collision and both instances are mapped together and one of these part my be located on totally different part of the XLIFF.

**Comment by vicb** [comment]
Thanks for the clarification.
What happens when you have such a message a`<p i18n="plural2|">I have {ski, plural, one {{{ski}} ski} other {{{ski}} skis}} and {car, plural, one {{{car}} car} other {{{car}} cars.}}.</p>`

- We extract a string for the first ICU message `{ski, plural, one {{{ski}} ski} other {{{ski}} skis}}`
- We extract a string for the second ICU message `{car, plural, one {{{car}} car} other {{{car}} cars.}}`
- We extract a string with placeholders in place of ICU: `I have <ph ICU1> and <ph ref ICU2>.`

Then I think that what you are asking is the ability to add meaning/description/id to the ICU messages. Is my understanding correct ? (If that is the case, we might have an opened issue tracking this already)

**Comment by jaska45** [comment]
Thanks. You got it right.

**Comment by saithis** [comment]
@vicb Why is the message split into 3 parts in the first place? If I put them back together into one string after extraction, the translation still works.

Would it be possible to add an option to not split the message?
