### ISSUE TITLE
When template has an error, it breaks most of the page

### ISSUE THREAD

**Issue by mhevery** [angular/angular#2413]
When there is an error in the template, the CD stops and breaks the remainder of the page. Instead we should just publish the error and continue on processing the remainder of the page.

**Comment by mhevery** [comment]
@vicb is this still the case or should we close this issue?

**Comment by vicb** [comment]
Not sure, did you mean to ask @vsavkin ?

**Comment by mhevery** [comment]
sorry @vicb 
---
@vsavkin is this still the case or should we close this issue?

**Comment by pkozlowski-opensource** [comment]
IMO still an issue, we had a report of it recently in #9212. Here is a plunker to reproduce: https://plnkr.co/edit/iHDYpZ3fDlO6bhOtlTbQ?p=preview

**Comment by vicb** [comment]
Seems like the exception reporter is called but it continues working
https://plnkr.co/edit/pzRoDmUrOTyK4sZqgb4L?p=preview

**Comment by garethdn** [comment]
@vicb In the plnkr you linked, yes the exception is thrown but only thrown once. i.e repeatedly clicking `break it` will only throw the exception once. Also the view no longer updates on clicking of the `do it` button.

**Comment by LanderBeeuwsaert** [comment]
Same here. I encounter this throughout my app, even with a custom errorHandler. Some parts of the view (not all) will stop updating.

**Comment by AlexMinsk** [comment]
As I understand all happens in `angular/module/@angular/core/src/linker/view.ts`.

On `break it` the `this.cdMode = ChangeDetectorStatus.Errored` is set in class **DebugAppView** function **_rethrowWithContext**.

On `Do it`, when cdMode has status Errored, changes are not applied in class **AppView** function **detectChanges**, because cdMode is compared to ChangeDetectorStatus.Errored and function simply returns without invocation `this.detectChangesInternal(throwOnChange);`
So in case when cdMode = Errored changes are ignored.

**Comment by AlexMinsk** [comment]
And **exception** is thrown every time on clicking the button `break it`, but not written in the console since the ErrorHandler is unsubscribed after the first exception:
`core.umd.js: function onHandleError`
`rxjs/Subject.js: function Subject.prototype.next`
`rxjs/Subscriber.js: function SafeSubscriber.prototype.__tryOrUnsub`
`core.umd.js: function ErrorHandler.prototype.handleError`

**Comment by gbilodeau** [comment]
We would love to see this fixed - either through a less brutal built-in strategy or by allowing a custom ErrorHandler to implement a more lenient strategy. As it stands right now, any error thrown in a page makes the page unresponsive and forces the user to reload to resume his work.

**Comment by SirZach** [comment]
I'm on Angular 7 and just came across this. My template throws an error from referencing a non-existent property, it's caught in the global error handler, but the UI stops working. I am mostly using angular material components so maybe it's an issue there.

https://stackblitz.com/edit/template-error-breaks-ui is a stackblitz reproducing the issue. Click the first panel, notice it doesn't fully open. Click the second panel and it also doesn't fully open. If you click the second panel first, it will fully open.
