### ISSUE TITLE
Why does Directive have no styles?

### ISSUE THREAD

**Issue by iwe7** [angular/angular#24166]
I have a suggestion, Directive plus styleUrls or styles, so that I can easily carry out a number of topics to customize the related Directive, Component has restrictions that can not be repeated, Directive can be repeated, such as btn-lg, btn-small and so on! Although I can individually pack and publish or introduce CSS style to style.css, it's not very convenient! What do you think?

**Comment by ericmartinezr** [comment]
Dup of https://github.com/angular/angular/issues/17766

**Comment by iwe7** [comment]
That's what I did now.
```ts
@Component({
  selector: "iwe7-flex,am-flex,flex",
  template: `<ng-content></ng-content>`,
  styleUrls: ["./flexbox.scss"],
  providers: [Iwe7IcssService],
  encapsulation: ViewEncapsulation.None
})
@Directive({
  selector: "[iwe7Flex],[amFlex],[flex]",
  providers: [Iwe7IcssService]
})
export class AmFlexbox extends Iwe7BaseComponent {}
```

**Comment by splincode** [comment]
Please add example on stackblitz

**Comment by mhevery** [comment]
I am not sure what it would mean for a directive to add style. The issue is that such style would have to be encapsulated and so it is not clear who the owner of encapsulation would be.

It is unlikely that we would add such a feature.

Having said that you can have your own directive which does such a thing.
