### ISSUE TITLE
inconsistent behaviour of DefaultUrlSerializer since angular-router 5.2.9

### ISSUE THREAD

**Issue by mafo5** [angular/angular#24164]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
[ ] Other... Please describe:
</code></pre>

## Current behavior

```
const expected = '/a/b%3Fc%3Dd%26e%3Df/g?h=i&j=k';
const serializer = new DefaulUrlSerializer();
const actual = serializer.serialize(serializer.parse(url))

assertThat(expected, is(actual));
```
Test fails since 5.2.9 of `angular-router` see #22687

## Expected behavior

Test should not fail

## Minimal reproduction of the problem with instructions

Adding a `&` to the segment of a url causes inconsistent behaviour of the router.

## What is the motivation / use case for changing the behavior?

Both Functions describe their opposite. So calling both directly should result in the input value.

## Environment

<pre><code>
Angular version: 5.2.10

Browser:
- [x] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: v8.4.0  
- Platform:  Mac 
</code></pre>

**Comment by mafo5** [comment]
Its a breaking change and it may be ok for angular 6.x but not for 5.2.x

**Comment by jasonaden** [comment]
Thanks for the issue. The statement that calling both directly should result in the input value is not entirely correct though. Parsing the URL will decode the URL segments including matrix and query params plus auxiliary routes. Serializing will encode the decoded versions. Therefore it is possible to send in a URL where every character was `%` encoded. Would you expect parsing and re-serializing to result in a URL where very character remains encoded?

The parse logic is there to parse a URL and provide the decoded values. The serialization logic is there to safely serialize to a value that, when parsed again, will produce the same result it did previously.

The PR you refer to was done because a test of parse, serialize, re-parse, re-serialize, and compare the two serialized versions would sometimes fail:

```
const originalUrl = '/a/b%3Fc%3Dd%26e%3Df/g?h=i&j=k';
const serializer = new DefaulUrlSerializer();
const serialized = serializer.serialize(serializer.parse(originalUrl));
const reSerialized = serializer.serialize(serializer.parse(serialized));

assertThat(serialized, is(reSerialized));
```

The original change was not considered breaking because URLs should always be parsed before consuming, and the parsed version of the URL did not change.
