### ISSUE TITLE
Angular 6 - ServiceWorker not requesting gzipped content

### ISSUE THREAD

**Issue by adnan-kamili** [angular/angular#24227]
I recently added service worker to my Angular 6.0.3 app. Everything works great.

I observed a slight increased initial load time when app is loaded the first time and to my surprise, the mainxxxx.js file being downloaded was 3.1 MB.

Cloudfront gzips the js files reducing the size of main.xxx.js to around 500KB, but it will only gzip when the client will send the

`Accept-Encoding: gzip`

request header. The browser was sending this header, but service worker requests don't have this header, which is a big problem because angular build files have very large size.

Is this a bug which will be fixed or service workers don't support gzip which would be a big disappointment.

Chrome 66, MacOS

**Comment by gkalpak** [comment]
It seems that the SW is stripping headers (and other "metadata") from requests (e.g. [here][1] and other places as well). This is intentional (to a degree) to avoid things like credential inclusion in order _"to avoid issues with opaque responses"_.

We might be over-aggressive here (e.g. it might be OK to preserve (some) headers).
@alxhub should know more about what kinds of issues we are trying to avoid and if we can be less aggressive.

[1]: https://github.com/angular/angular/blob/2d9111bfb698aa1e418cbd73b33e3ef73209084e/packages/service-worker/worker/src/assets.ts#L145-L148

**Comment by wachri** [comment]
Any updates on that? Working with the service worker is great, but with this "bug" not so production ready....

**Comment by finnlake** [comment]
I am quite surprised that this feature has not been fixed, almost a year later. Should we start using Workbox instead?

**Comment by alxhub** [comment]
Sorry for the inactivity on this issue!

@gkalpak I think for same-origin requests (do we have a reliable way of detecting these? I don't remember) it makes sense to forward headers like `Accept-Encoding`.

**Comment by irbian** [comment]
Maybe related with this we are experimenting encoding changes by the ServiceWorker on our Content-disposition header (the one that cointains the filename)

**Comment by tayambamwanza** [comment]
Quite surprised about this, thanks for the work on this, would be amazing, of all the frameworks I've found angular the quickest to setup a good service worker and the consistency really helps.

**Comment by tinesoft** [comment]
Any update on this ? @alxhub ? team?
Would be a great addition to the SW setup..

**Comment by gkalpak** [comment]
@tinesoft, I am working on PR to fix this.
