### ISSUE TITLE
Deprecation notices point to @angular/* which is parsed as a separate JSDoc tag

### ISSUE THREAD

**Issue by alexeagle** [angular/angular#24237]
We use the TSLint `deprecation` rule https://palantir.github.io/tslint/rules/deprecation/
which parses the JSDoc tags to give a message.

In HTTP we have marked things with
`/** @deprecated use @angular/common/http instead */`

which is equivalent to
```
/**
 * @deprecated use
 * @angular/common/http instead
 */
```
so the deprecation text doesn't appear in the lint warning.

**Comment by alan-agius4** [comment]
I looked a bit into this, the only way I found to make the deprecation message visible is to change the message to 
```
 * @deprecated use &commat;angular/common/http instead
```

In the IDE it will show like such;
![image](https://user-images.githubusercontent.com/17563226/40835783-b8d4d298-6594-11e8-9691-eb777fef33b5.png)

While in the console when running tslint it will show like; 
```sh
RequestMethod is deprecated: use &#commat;angular/common/http instead
```

This is due to https://github.com/palantir/tslint/blob/master/src/rules/deprecationRule.ts#L70 as it's printing the `text` directly,

I am not sure if this is acceptable or not. I did a PR for this. https://github.com/angular/angular/pull/24249

Feel free to close it you think it's not enough

**Comment by alexeagle** [comment]
I think we should change it to just avoid the @ sign, it would be just as
readable (possibly more readable) to point to some documentation about the
http -> common/http migration, or link to https://angular.io/api/common/http

**Comment by alan-agius4** [comment]
I changed it to: `* @deprecated see https://angular.io/api/common/http`

**Comment by jenniferfell** [comment]
@petebacondarwin @jbogarthyde Bringing you into this thread to make sure what's proposed here has no impact on (or is compatible with) how we're handling deprecation in API refs (and related templates, dgeni, guidance/ed).

**Comment by petebacondarwin** [comment]
I think that a proposal to remove the `@` would be fine from a doc-gen point of view. FWIW I think that as long as the `@angular` doesn't actually start a new line then the dgeni tag parser would cope with it (unlike tslint). But we cannot guarantee this since the code formatting tool might decide to wrap the line if it appears too long.
