### ISSUE TITLE
feature: Single vue-like component

### ISSUE THREAD

**Issue by exotfboy** [angular/angular#24261]
I like the out-of-box fullstack solution like angular and have tried angular many times, however I can not insisit on it.

I can accept the concepts and lerning curve, but not for the `file hell`  described also at this [post](https://blog.hackages.io/angular-single-file-component-4a9eed8c80d5).

Althrough the author give a solution by using `inline-style` and `inline-templte`, there are still some cons:

1 Both the style and templte(inline) are mixed together INSIDE the javascript.

2 Synatx highlighting and formatting is not avaiable.

So I wonder if it is possible to create a plugin to support `vue-like` single file component where the `tempalte` , `style` and `javascript` are separated physically?

**Comment by jotatoledo** [comment]
Would you like to add the .spec file inside of a <spec> tag too? 😄

IMO this is a matter of pure taste. Consider extrem cases where a component is made of 200 html lines, 600 ts lines, and 150 css lines. Personally, I find 3 files better than 1 bloated with code that has different syntax/rules depending on the file section.

**Comment by exotfboy** [comment]
Yes, IMO traveling inside a single files is still better than between three different files. 😀

**Comment by lazarljubenovic** [comment]
You can have a SFC in Angular -- just inline the template and style, without using separate files (as you are already aware of and as the text you linked shows).

> 1 Both the style and templte(inline) are mixed together INSIDE the javascript.

So? The fact that they are mixed inside JavaScript means that you do not have to do weird things like IDE plugins in order to properly syntax highlight it. Why invent a new syntax when the existing standard already works?

> 2 Synatx highlighting and formatting is not avaiable.

It surely is possible to make it available. Get an IDE which understands JavaScript, TypeScript and/or Angular code better if you want advanced syntax highlighting.

**Comment by exotfboy** [comment]
That's OK. Sounds like this is the only choice. I will try adapting to it
