### ISSUE TITLE
Router's `url` property is actually an URI

### ISSUE THREAD

**Issue by iget-master** [angular/angular#24325]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
[ ] Other... Please describe:
</code></pre>

## Current behavior

When reading the value of Route's `url` property, it actually returns a URI (without the schema and domain) instead of a URL.

This might be a minor problem, but it's a problem since it's miss named.

## Expected behavior

The `url` property should return the full url, with schema and domain.

Also a `uri` property should be implemented in replacement for current `url` usages.

## Minimal reproduction of the problem with instructions

Not necessary.

## What is the motivation / use case for changing the behavior?

I'm trying to generate an URL for a given router page for share with other users for example, and it returns the URI instead. I know, I can query the browsers location to get it, but I want to keep inside the angular environment.

## Environment

<pre><code>
Angular version: 6.0.7

Browser:
- [x] Chrome (desktop) version 68
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: 8.11.2
- Platform:  Linux
</code></pre>

**Comment by jasonaden** [comment]
I'm not sure which `url` property you're referring to. For example, in the `ActivatedRoute.snapshot.url`, the property is an array of `UrlSegment`s.

I do agree there's likely some incorrect naming here. However, due to the number of places that would need to change in order to correct it and the breaking changes that would come with, I'm going to go ahead and close this issue as `Won't Fix`. However, if we and up doing any major refactoring with the router, this will be something to consider when laying out the updated API.
