### ISSUE TITLE
Service worker does not fetch new version of the app if the version is same as a previous version

### ISSUE THREAD

**Issue by arikanorh** [angular/angular#24338]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ X] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
[ ] Other... Please describe:
</code></pre>

## Current behavior

I build a sample hello world project with angular cli and add service worker. And i added update handler on my main project to show some notification. Lets say this is version A. I did a prod build and all is well. I changed to style css lets say body {background:red} and i build again (version B) while http-server is still up. I refreshed  page and service worker catched the diff and show the notication.So far so good,

Then i reverted css change and end up with a version C which is identical to version A in terms on file contents.

Then build and deploy again. At this time when i refresh the app, the service worker doesnt fetch the new files and still show the version B.

## Expected behavior

Service worker should fetch the version C and trigger an update  showing notification

## Minimal reproduction of the problem with instructions

1. Create a new app with angular cli and add service worker
2. Build for prod and serve with http-server
3. While http-server is up change style.css to backgroun:red
4. Build deploy
5. Refresh page and you will see red background
6. Then remove background:red and make the file exactly same as before
7. Build deploy
8. Refresh the page. At this time sw wont recognize new files even after several refreshes.

## What is the motivation / use case for changing the behavior?

Sometimes developers make a rollback after a detecting a fatal bug after a new release. With this bug, the revert wont go use

## Environment

<pre><code>
Angular version: 6.0.4

Browser:
- [ ] Chrome (desktop) version 69
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: XX  
- Platform:  

Others:

</code></pre>

**Comment by gkalpak** [comment]
Indeed, this happens due to this check:

https://github.com/angular/angular/blob/e0ed59e55f8740303fc93784548d81c2de210e7e/packages/service-worker/worker/src/driver.ts#L773-L776

I guess this is to account for proxies serving outdated content or something.
One solution I can think of is adding an extra field (e.g. "random" number or date) in the manifest and ensuring it is taken into account when computing the version's hash. This way we ensure (with a high enough probability) that each build will be distinguishable from all other builds.

(Taking this one step further, it would be even better if we kept the "uid" distinct from the hash, so that we could detect that the latest version is identical with a previous one and re-use that without having to re-fetch assets (even if from cache).)

**Comment by javierforero** [comment]
@gkalpak do you have any recommendations on how to fix this meanwhile your PR gets merged?

My service worker doesn't seem to recognize app updates if I roll back to an older version of the app I am working on. I'm new to PWA's so an advice would be greatly appreciated

**Comment by gkalpak** [comment]
Unfortunately, I can't think of any work around that would allow rool backs to work. The obvious (but tedious) solution is to change something in `ngsw-config.json` to make it different than the old one (if I'm not mistaken, it could be just something in [appData][1]).

[1]: https://angular.io/guide/service-worker-config#appdata

**Comment by XavierDupessey** [comment]
Bug still exists in Angular 7.1.1.

The workaround suggested by @gkalpak works: change anything in ngsw-config.json (ngsw.json in dist folder) > appData. Thanks !

**Comment by maxisam** [comment]
If you deploy your app with CI/CD, you can use it to replace the anything in ngsw.json to make this work like @gkalpak suggested.

Here is how to do it in Azure DevOps

![image](https://user-images.githubusercontent.com/456807/51876467-41262f00-232e-11e9-997c-babea2b9877f.png)

add variables like

![image](https://user-images.githubusercontent.com/456807/51876497-59964980-232e-11e9-87cc-a247625245b3.png)

because deploymentId will change when there is a deployment every time, so it can make rollback work properly.
