### ISSUE TITLE
angular 6 routing url array

### ISSUE THREAD

**Issue by denek01** [angular/angular#24420]
I can use like this 
/some-route?ids=1&ids=2&ids=3
but it must be  /some-route?ids=1,2,3
let objectNavigation = {};
    let arraySize = ["1","2","3"];
    let navSize: NavigationExtras = {
      queryParams: objectNavigation, queryParamsHandling: "merge" 

  };
    objectNavigation['ids'] =  arraySize;
 this.router.navigate([], navSize);

thank you
////////////////////////////////////////////////////////////////////////////////////

## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x ] Bug report  
[ ] Performance issue
[x ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
[ ] Other... Please describe:
</code></pre>

**Comment by jasonaden** [comment]
This issue is a little unclear, but I think what you want is to create a custom `UrlSerializer`. [Here's the documentation](https://angular.io/api/router/DefaultUrlSerializer) and a [StackOverflow answer](https://stackoverflow.com/questions/43399936/angular-2-implement-urlserializer)

<hr>

It appears this behaves as expected. If you still feel there is an issue, please provide further details in a new issue.
