### ISSUE TITLE
The brackets are automatically removed when the path parameter is contains parentheses

### ISSUE THREAD

**Issue by DreamLi1314** [angular/angular#24432]
# Environment:
- Google Chrome 65.0.3325.181 --- 64
- Angular 6
- Node 9.11.1
- NPM: 5.6.0

# Description:
When you enter the path manually and the path contains parentheses, the parentheses are automatically removed. Of course, I can't get parentheses, but when I use
``` Typescript
This.router.navigate(['view/aaa()'....
```
Or
``` Typescript
<a [routerLink]="'view/aaa()'">Angular router...</a>
```
You can get aaa().
**This is because Angular will encode the path when router, but manually entered path Angular does not encode it.**

# Demo
- Source Code: [https://stackblitz.com/edit/angular-qfja9x](https://stackblitz.com/edit/angular-qfja9x)

**Comment by DreamLi1314** [comment]
**I think it might be related to the this code in router.js:**
``` JavaScript
const SEGMENT_RE = /^[^\/()?;=&#]+/;
/**
 * @param {?} str
 * @return {?}
 */
function matchSegments(str) {
    const /** @type {?} */ match = str.match(SEGMENT_RE);
    return match ? match[0] : '';
}
```

**Comment by DreamLi1314** [comment]
My team found a solution:
``` Typescript
// app.module.ts
@NgModule({
   imports: [ BrowserModule, HttpModule, HttpClientModule, AppRoutingModule ],
   providers: [
      {
         provide: UrlSerializer,
         useClass: StandardUrlSerializer
      }
   ],
   declarations: [ AppComponent ],
```
```Typescript
// StandardUrlSerializer 
import { DefaultUrlSerializer, UrlSerializer, UrlTree } from "@angular/router";

export class StandardUrlSerializer implements UrlSerializer {
    private _defaultUrlSerializer: DefaultUrlSerializer = new DefaultUrlSerializer();

    parse(url: string): UrlTree {
       url = url.replace(/\(/g, "%28").replace(/\)/g, "%29");
       return this._defaultUrlSerializer.parse(url);
    }

    serialize(tree: UrlTree): string {
       return this._defaultUrlSerializer.serialize(tree);
    }
}
```

**But I still think that Angular should provide a consistent behavior when routing, ie navigate and manually enter urls should behave the same behavior.**

**Comment by jasonaden** [comment]
It appears this behaves as expected. If you still feel there is an issue, please provide further details in a new issue.

<hr>

As it turns out, parentheses are the default marker for auxiliary routes. Making a modification to the UrlSerializer is the correct solution. Note that your solution works for the current use-case, but if you use auxiliary routes, it's going to break when someone wants to load a url such as `http://mysite.com/users(modal:create)` as it's going to encode those parentheses. It might be better to specifically look for a set of empty parens such as `url.replace(/\(\)/g, "%28%29")`.

**Comment by DreamLi1314** [comment]
yes, all right.
