### ISSUE TITLE
Feature: a way to detect form control flags change in ControlValueAccessor

### ISSUE THREAD

**Issue by dawidgarus** [angular/angular#24444]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Performance issue
[x] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
[ ] Other... Please describe:
</code></pre>

## Current behavior
There is no way to detect if custom control flags has changed.

## Expected behavior
Maybe add to `ControlValueAccessor` new optional methods like `setPristineState(isPristine: boolean)?` etc.

## Minimal reproduction of the problem with instructions
https://stackblitz.com/edit/angular-pybpep
Enter some value to every input to mark it as dirty and the click "clear".
Inner controls are still dirty - that's expected. What's wrong however is that there is no simple way to appropriately change it.

## What is the motivation / use case for changing the behavior?
Look at the reproduction example. In my form, errors are shows only when control is dirty or touched (user somehow interacted with it). When I clear the form I want to set all controls state back to pristine and untouched. Unfortunately, there is no easy way to detect that my custom control (`NameInput`) status has changed and to inform inner controls to change it as well.

## Environment

<pre><code>
Angular version: 6.0.4
</code></pre>

**Comment by flensrocker** [comment]
When extending the `ControlValueAccessor` with such a function, please consider to superseed the `setDisabledState` with a function like `setStatus(status: "VALID" | "INVALID" | "PENDING" | "DISABLED")`, because "disabled" is just a part of the possible states that a control can have.

Additionally a `setTouchedState(isTouched?: boolean)` would be great, that get's called, if the program calls `markAsUntouched`. Of course it must not be called, if the touch-state changes, because the `ControlValueAccessor` called the registered `OnTouched` callback.

That would help to mirror the state of the underlying control to the control which is displayed in the UI.

**Comment by dylhunn** [comment]
We recently proposed #42862 in relation to another issue, but it would also be useful here. If there was one coherent observable for state changes on `AbstractControl`, the CVA implementation could just subscribe to it.

We should take this use case into account when working on #42862.
