### ISSUE TITLE
Example fails tslint on angular-tour-of-heroes 

### ISSUE THREAD

**Issue by douglaine** [angular/angular#24506]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x ] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
[ ] Other... Please describe:
</code></pre>

## Current behavior

When doing the tutorial, users will run into an issue here:
https://angular.io/tutorial/toh-pt6#add-heroserviceaddhero

Line 72: tap((hero: Hero) => this.log(`added hero w/ id=${hero.id}`)),
generates:
[tslint] Shadowed name: 'hero' (no-shadowed-variable) (parameter) hero: Hero
and the output hero.id is undefined.

## Expected behavior

It should provide the id of the new Hero
A simple fix is:

line 72: tap((newHero: Hero) => this.log(`added hero with id=${newHero.id}`)),

## What is the motivation / use case for changing the behavior?

Might confuse people learning Angular

## Environment

<pre><code>
Angular version: 6.0.3

Browser:
- [x ] Chrome (desktop) version 67.0.3396.87 (Official Build) (64-bit)
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: 10.4.0  
- Platform:  Windows 10

Others:

</code></pre>

**Comment by chembu** [comment]
Could not reproduce the error. The app does not throw an error while adding a new hero.

**Comment by tparikka** [comment]
I ran into this issue while going through the tutorial for Angular. My environment is:
Angular CLI: 7.1.4
Node: 10.15.0
OS: Win 10 x64 Build 1809
Angular: 7.1.4

New to all this but I believe the issue is that the arrow function's parameter of "hero" is shadowed by the method parameter of hero. If I change the parameter passed to the tap method to `_` instead of `hero` as the directions suggest doing for updateHero, getHero, and getHeroes the linting error goes away, the project compiles, and it runs. However, I noticed that when using eslint instead of tslint the use of `_` as the parameter returns `Parameter '_' implicitly has an 'any' type, but a better type may be inferred from usage.ts(7044)`. So, depending on whether the project wants to support tslint, eslint, or both the optimal result may vary. I am guessing that tslint is the standard but want to verify. I can submit a PR to fix the reported issue once I know for sure.

**Comment by IgorMinar** [comment]
I believe that his issue has been already resolved - looking at https://angular.io/tutorial/toh-pt6#add-heroserviceaddhero I see that all `tap` calls now use either `_` or `newHero`. 

@tparikka  eslint is not officially supported yet, but feel free to submit a PR  to update the examples to make them eslint compatible. thanks!
