### ISSUE TITLE
Missing AOT Documentation

### ISSUE THREAD

**Issue by dinony** [angular/angular#24514]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Performance issue
[ ] Feature request
[x] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
[ ] Other... Please describe:
</code></pre>

## Current behavior

The v6 [AOT documentation ](https://angular.io/guide/aot-compiler) does not provide information how to manually implement AOT using a custom build process. It is silently assumed that everybody uses the CLI.

## Expected behavior

Please provide detailed information about AOT compilation like in the [previous documentation](https://v4.angular.io/guide/aot-compiler).

## What is the motivation / use case for changing the behavior?

Do not silently assume that everybody uses or wants to use the CLI. A lot of library authors and companies have implemented custom build processes, therefore detailed information is still needed on AOT.

**Comment by alexeagle** [comment]
I think this is a fair point, however there are so few build system authors that I think we typically work directly with them. Also, we are currently re-working the compiler for Ivy in a way that's very breaking for build tooling, so this isn't yet a stable API we want the community to build on.
Note that build tooling can simply call the `ngc` binary we provide, this is the canonical way to invoke the Angular compiler and it properly hides our APIs and is stable.

Maybe sometime after Ivy ships, we can consider making the compiler-cli API more usable.

**Comment by dinony** [comment]
Issue closed, problem solved :) 
Sorry there seems to be a misunderstanding. 

The v6 docs do **not** contain the workflow information **anymore** how to bootstrap a jitted vs. aoted version of the application. That is information, which is not included anymore in the v6 docs! Please correct me, if I'm blind.

> Also, we are currently re-working the compiler for Ivy in a way that's very breaking for build tooling, so this isn't yet a stable API we want the community to build on.

Sorry, the AOT compiler is a **public** API since since v2, and the community builds on top of it already.
Let me put it very clear: AOT compilation is a **crucial** step when using Angular in **production** (jitted version is infeasible for production) and the strategy should be to provide the most **complete** documentation that is possible - not **removing** information and assuming everybody using the CLI.

**Comment by mscottnelson** [comment]
In v5, I had a custom Webpack build making use of the AngularCompilerPlugin as part of the toolchain. The documentation was always a little sparse and at times outdated, and there were non-obvious breaking changes because the AngularCompilerPlugin never really had a guaranteed interoperable API, and it made assumptions about the rest of the toolchain. I assume this is what you're referring to in this issue.

I think the Angular team is wrong to assume that they are working with "most of" the build system authors out there since a lot of Angular users are working in fairly strict proprietary IP environments...but it's right to remove the documentation if it was a mistake to make it a public API.

AngularCompilerPlugin should have always come with a warning. On the other hand, I *think* --eject did come with disclaimers. This is probably an area of communication that deserves some additional attention, particularly in regard to roadmap / expectation setting. Using `ngc` is canonical now (it's not so long ago that SystemJS, Rollup, and Webpack all existed in the documentation simultaneously as canonical to varying degrees). So, for example, can we count on @schematics being a way to canonically extend the framework, or is that more for developers closer to the Angular team?

**Comment by dinony** [comment]
Hi @mscottnelson 

>  I assume this is what you're referring to in this issue.

No, not exactly. I've not used webpack but I understand that folks using webpack also want more info on ngc/aot in general.

I meant missing "basic" information, like

- How to [compile](https://v4.angular.io/guide/aot-compiler#compile-with-aot) with ngc
- How to [bootstrap](https://v4.angular.io/guide/aot-compiler#bootstrap) an AOT compiled Angular application.
- Usage of ngc
- Missing docs on some [compiler options](https://angular.io/guide/aot-compiler#angular-compiler-options): e.g. [genDir](https://github.com/angular/angular/issues/24535), which is btw. breaking.

Besides that, it would be a good idea to still support folks using webpack and rollup etc. directly, by **keeping** information in the documentation :)

Btw. this is the information you get on ngc (=**central** and **public** AOT compilation tool) when currently searching in the docs:

<img width="1323" alt="screen shot 2018-06-25 at 19 22 50" src="https://user-images.githubusercontent.com/2547965/41865416-46ab2da8-78ad-11e8-99e2-a77bc845dc02.png">

One single mention in a info box :satisfied:
