### ISSUE TITLE
Support assigning expression result to local variable within templates

### ISSUE THREAD

**Issue by jeffbcross** [angular/angular#2451]
Particularly for use cases where piped output is bound to in many places within a template, it's beneficial to have a single piped expression. For example, this observable that's piped into a template:

``` html
<div>
  <ul>
    <div *ng-if="!(people | async)">
      Loading people
    </div>
    <div *ng-if="people | async">
      <li *ng-for="person of people | async">
        {{person.name}}
      </li>
    </div>
  </ul>
</div>
```

This would cause three subscriptions to be created for the people observable, which may re-do the work of getting the observable value if the observable is not a multicast observable. This is also problematic if inside of the ng-if that evaluates to true when the observable has emitted a value, there are expressions that assume people | async is not null, such as: `{{people | async.length }}`. This would raise an exception since the first value returned from the async pipe would be `null`.

@vsavkin and I put together a prototype directive, which I'm currently using in the [`http` example](https://github.com/angular/angular/blob/master/modules/examples/src/http/http_comp.ts) that supports assigning the result of a piped expression to a local variable within the template:

``` html
<div *assign-local="#unwrappedPeople to people | async">
  <ul *ng-if="unwrappedPeople" class="people">
    <li *ng-for="#person of unwrappedPeople">
      hello, {{person.name}}
    </li>
  </ul>
  <span *ng-if="!unwrappedPeople">
    Fetching people...
  </span>
</div>
```

This creates a single subscription and simplifies the rest of the template. Here is the implementation: https://github.com/angular/angular/blob/master/modules/examples/src/http/assign_local_directive.ts

I'd like to add this directive as a first-class directive in the angular2 module.

@vsavkin, @mhevery, @tbosch do you have any feedback on the implementation?

**Comment by tbosch** [comment]
Victor added `Directive.exportAs` recently. With this, you should be able to write an `assign-local` directive without the `*` as follows:

```javascript
@Directive({
  selector: 'assign-local'
  exportAs: 'assign',
  properties: ['value: assignLocal']
})
class AssignLocal {
  value: any;
}
```

```html
<div [assign-local]="people | async" #unwrapped-people="assign.value">
...
</div>
```

**Comment by mhevery** [comment]
I was under the impression that change detectors would coalesce multiple reads to the same expressions, so having `people|async` twice should not be an issue. 

To be self consistent with the rest of the templates new variables can only be declared on templates hence `*` or `template` would have  to be present in the template. Not sure if it is worth the trouble given that change detectors can (or should) coalesce.

**Comment by rosendi** [comment]
Local variable assignment could be also very useful in a combination with Firebase.

I've implemented LVA and it works. Here is the plunk - http://plnkr.co/edit/MWrKGahELHsq2kfu03Gh?p=preview. But it doesn't play nicely with a `ng-if` directive. I understand why it doesn't pass in the `Data 2` block: `assign-local` executes after `ng-if` and it doesn't know that the view has been cleared by a `ng-if` directive, and recreates it.

The question is: how it could be done without wrapping `ng-if` in a parent container? 

viz. refactor

``` 
<div *assign-local="#data to promise | async">
  <div *ng-if="data">
    Data 1: {{ data }}
  </div>
</div>
```
to
 
```
<div *assign-local="#data to promise | async" *ng-if="data">
  Data 2: {{ data }}
</div> 
```
Another point is that when I use `ng-if` and `assign-local` together on the same element, `assign local` evaluates expression again after each view creation by `ng-if` and in real example it would send another network request if custom `async` works like 

```
transform(value: string, args: string[]): any {
  ... send network request
}
```

**Comment by tycho01** [comment]
I could still access the referenced example [here](https://github.com/angular/angular/commit/21568106b114943b59ce37832d82c8fb9a63285b), but was having trouble getting that to work in the latest version (error `Invalid left-hand side in assignment`, though I'll admit I'm confused w.r.t. whether it should now be defined/invoked as `assignLocal` over `assign-local`). Anyway, looking forward to this feature as part of ng2 itself.

**Comment by primIl** [comment]
+1

**Comment by tycho01** [comment]
@tbosch: could you comment on whether something like that `AssignLocal` directive would still be possible since your [recent commit](https://github.com/angular/angular/commit/cacdead96dcfbb80dff899b5f5143b7c28c4d6dd) ditching `setLocal` in favor of `createEmbeddedViewRef`? I guess altering locals in an existing view is no longer supported?

**Comment by kylecordes** [comment]
I found a need for about the same thing as this issue asks for; I met it by create a variant of "ngFor" and "ngIf" which doesn't add the DOM until the data is available (like IF), but which also capture the value (like FOR). I called it ngWhen, based on the name of a similar feature in some other languages. I got it up and running as part of an early, pre-angularfire2 A2-firebase library I working on. You can see it in action here:

https://github.com/OasisDigital/angular2-firebase-demo/blob/master/app/weather/weatherPanel.ts#L17

I wonder if something similar (perhaps with better naming etc) ought to be "in the box".

**Comment by tycho01** [comment]
Link to that ngWhen [implementation](https://github.com/OasisDigital/angular2-firebase/blob/master/ts/ngWhen.ts#L68-L97).
Too bad this way using `$implicit` with a structural directive appears to be the only way now, notably since the limitation of one structural directive per element (iirc) means you're just clogging up your dom for each variable you'd wish to define. It made sense in kylecordes' "ngIf and variable assignment mashed into one" case, but if need just the latter, not so much.
We'll miss you, `setLocal`. :(

**Comment by kylecordes** [comment]
Right, I'm not proposing my ngWhen as an answer to all questions... just as an example of one thing someone could do to work around the lack of any obvious built-in way to capture the result of blah|async.

**Comment by nzjoel1234** [comment]
I agree some kind of variable assignment would be very nice.

One work around I have come across is this:

`<div *ngFor="let unwrappedPerson of [person | async]">{unwrappedPerson.name}</div>`

**Comment by vicb** [comment]
FYI this has been implemented for `ngIf` lately by @mhevery. Other directives should follow soon.

See https://github.com/angular/angular/pull/13297

**Comment by tycho01** [comment]
@vicb any consideration for a version akin to the `AssignLocal` so the general case would be handled as well?

**Comment by vicb** [comment]
No, no yet.
Probably something we can consider at a later point according to usage needs.

**Comment by tycho01** [comment]
Thanks for your quick response. :)

**Comment by eleddie** [comment]
Any update on this?

**Comment by code-tree** [comment]
@vicb  Could this be reopened? As it seems mainly to be about a general solution rather than tying it down to ngIf and ngFor etc.

It would appear to solve an issue I'm having with binding ngFor to a function result. The only alternative seems to be to create a separate component simply for the sake of storing the value of one expression.

**Comment by mischkl** [comment]
This would be really handy for dealing with async expressions without needing an `ngIf` or `ngFor`! for example the Angular 4 release [blog post](http://angularjs.blogspot.co.at/2017/03/angular-400-now-available.html) gives the following example:

```html
<div *ngIf="userList | async as users; else loading">
  <user-profile *ngFor="let user of users; count as count; index as i" [user]="user">
User {{i}} of {{count}}
  </user-profile>
</div>
<ng-template #loading>Loading...</ng-template>
```

What if I need to reference `users` in multiple places, somewhere that I don't need an ng-if wrapper? I shouldn't have to create an entire extra component and then a wrapper component just in order to get at my async data in an efficient manner. And using the subscription in the component is not only inelegant but very error-prone (forgetting to unsubscribe) and to top it off doesn't work in conjunction with OnPush change detection...

**Comment by ericeslinger** [comment]
Yeah, as an aside, I've been using `ngIf` assignments with my async data structures, which is fine most of the time. I just now ran into a pretty simple situation that makes this workaround annoying though: I'm trying to observe a boolean that represents state in a toggle. So I can't actually do 

```
<div *ngIf="favorited$ | async as favorited">
  <ion-icon name="{{ favorited ? 'star' : 'star-outline'}}">
</div>
```

since I want it to display even when the item is false. I'm working around by using ngElse directives (with the ion-icon fully expanded) instead of the ternary operator.

I mean, ultimately I *could* just throw a ton of | asyncs on the page, but it just feels a bit like ngLet or whatever would be a nice addition.

**Comment by misaizdaleka** [comment]
Couldn't you do:

```
<div>
  <ion-icon name="{{ (favorited$ | async) ? 'star' : 'star-outline'}}">
</div>
```

???

**Comment by ericeslinger** [comment]
That works for inline stuff, but not when I'm doing something like toggling a value. How would I do 

    <button (click)="toggleFavorite(favorited$ | async, $event)">toggle</button>
    

I can either do an ngIf like this:

    <button *ngIf="favorited$ | async; else notFaved" (click)="toggleFavorite(true, $event)">toggle</button>
    <ng-template #notFaved>
      <button (click)="toggleFavorite(false, $event)">toggle</button>
    </ng-template>

effectively hardcoding the current state into the html element. This works okay, but is kind of brittle - if I need to do other `ngIf` conditions (say, the button only renders in certain screen sizes), then the if-else thing does not help, because I'm actually combining view logic with state information, which is bound to be brittle.

I can instead write some stuff in my controller:

```
class Controller implements OnDestroy {
  _toggleClicked = new Subject<MouseEvent>();
  toggleClicked = this._toggleClicked.asObservable();
  toggleFavorite(e: MouseEvent) {
    this._toggleClicked.next(e)
  }
  constructor() {
    this.item$ = item.asObservable() // assume an observable data thing here
    this.toggleWatcher = Observable.combineLatest(this.item$, this.toggleClicked)
      .distinctUntilChanged((o, n) => o[1] === n[1]) // otherwise changes to item will trigger downchain
      .subscribe(([item, evt]) => /* here we know the state of item.favorited and can deal with it */);
  }
  ngOnDestroy() {
    this.toggleWatcher.unsubscribe();
  }
}
```
This is in fact what I end up doing. There's some extra cruft in that last bit - I usually use a .takeUntil in my in-class subscriptions, and then in ngOnDestroy() I emit on a `this.destroying` subject I set up, that way if I add more in-class subscriptions I can make sure they all get torn down when the component moves out of scope.

But this is still a *fair bit* of boilerplate. The nice thing about the async pipe is that it handles the boilerplate of subscribes and unsubscribes as appropriate. There does not seem to be any generally-useful workaround here. Maybe if I dig really far into directives I could write some local binding directive somehow, but this feels like it has a lot of parallels with the ng-model stuff from angular1, which I always felt was rather overused and abused.

For the time being, this is primarily a quality-of-life thing for me. In most scenarios, *ngIf works okay. If I can change the incoming data (from, say, a value to something like `{favorited: boolean}` which would be truthy even if favorited was false, I can use it even more often). Sometimes I can do inline template expansion with asyncs as @misaizdaleka pointed out. But sometimes I end up having to manually subscribe to a value in my controller, keep an eye on the source of that value (possibly unsubscribing and resubscribing to a new source in `ngOnChanges` if the component gets recycled (eg., as part of normal ngRouter behavior), and expose that value as a non-async value in the controller so I can get a handle on it in my view.

The alternative, something like

```
<button [ngLet]="{favorited: ctrl.favorited$ | async}" (click)="dispatch(favorited)">
```

would sure be rad, saving a ton of boilerplate. Alternatively, putting pipe template expansion in the parameter list of event handler functions would help, but I feel like that's even harder microsyntax.

**Comment by AustinMatherne** [comment]
I created* a ["let" structural directive](https://medium.com/@AustinMatherne/angular-let-directive-a168d4248138), which I've been successfully using in a large enterprise app. I'm using the "ng" prefix in the example, but obviously don't do that in your app if you decide to use it.

```ts
import {Directive, Input, TemplateRef, ViewContainerRef} from '@angular/core';

interface LetContext<T> {
    ngLet: T;
}

@Directive({
    selector: '[ngLet]'
})
export class LetDirective<T> {
    private _context: LetContext<T> = {ngLet: null};

    constructor(_viewContainer: ViewContainerRef, _templateRef: TemplateRef<LetContext<T>>) {
        _viewContainer.createEmbeddedView(_templateRef, this._context);
    }

    @Input()
    set ngLet(value: T) {
        this._context.ngLet = value;
    }
}
```

```html
<ng-container *ngLet="selectedUsers$ | async as selectedUsers">
  <app-user-details [users]="selectedUsers"></app-user-details>
</ng-container>
```

* It's just a duplicate of ngIf without the conditional logic.

**Comment by alexzuza** [comment]
https://stackoverflow.com/questions/38582293/how-to-declare-a-variable-in-a-template-in-angular2/43172992#43172992

**Comment by mytee306** [comment]
This is an awesome idea! Is the feature implemented yet, if so can someone please link to the docs?

**Comment by johntostring** [comment]
@mytee306 
https://angular.io/api/common/NgIf#storing-conditional-result-in-a-variable
https://angular.io/api/common/NgForOf#local-variables
