### ISSUE TITLE
RouterLink should support external URLs

### ISSUE THREAD

**Issue by jasonbaker** [angular/angular#24567]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Performance issue
[x] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
[ ] Other... Please describe:
</code></pre>

## Current behavior

Currently routerLink only works for URLs that are internal to the application. Unfortunately, it is not always possible to know ahead of time whether the URL is an internal link or an external link. This leads to hacks like below to accommodate this which leads to code duplication and poor performance:

```
<a href="link" *ngIf="externalLink">
  <ng-container *ngTemplateOutlet="myTemplate"></ng-container>
</a>
<a [routerLink]="link" *ngIf="!externalLink">
  <ng-container *ngTemplateOutlet="myTemplate"></ng-container>
</a>

<ng-template #myTemplate>
  <!-- Contents go here -->
</ng-template>
```

## Expected behavior

What would be nice is if routerLink had some logic to detect external URLs and make the link point to them instead of requiring developers to bypass routerLink altogether. That way, we could write something like this and it still works:

```
<a [routerLink]="http://github.com"></a>
```

**Comment by hosseinGanjyar** [comment]
I've got error:

> Quotes are not supported for evaluation!
  Statement: //github.com located at ng:///AppModule/AppComponent.html@68:35

**Comment by nhhockeyplayer** [comment]
this is a bit outrageous several publications on external link directives all fail
hours and days are spent trying to model external links in apps

is there a workaround?

**Comment by nhhockeyplayer** [comment]
Ok this publication works with latest angular 8

https://coryrylan.com/blog/managing-external-links-safely-in-angular

but he forgot to implement OnChanges for the directive

pheeeeww

thanks Cory

**Comment by nhhockeyplayer** [comment]
actually still struggling with this

**Comment by csimpi** [comment]
Up

**Comment by vishnu-dev** [comment]
This is open since 2018. Can we get any updates?

**Comment by nitindig** [comment]
This is very basic requirement. It would be really great if it start supporting external links as well.

**Comment by ChazUK** [comment]
I feel like there must be a simple way for this feature to be added? Surely a simple regex would work.

**Comment by stevermeister** [comment]
it's strange that this issue is still here for such a long time...

**Comment by amakhrov** [comment]
I feel the sheer fact this is an issue people want addressed manifests a larger problem: directives cannot be applied conditionally. So they are not well composed.

`routerLink` is just one specific use case. Another of this kind would be - using different versions of mat-button (mat-button / mat-raised-button etc) based on component input.

And now imagine we need to create a custom component that renders a link (either routerLink or href, based on the input), and applies different mat-button variant to it (mat-button or mat-raised-button). We've just got 4 *ngIfs in our template - because we cannot conditionally compose those directives.

It really prevents creating reusable composite components.

**Comment by ChazUK** [comment]
Every time I come back to this issue I die a little inside

**Comment by SchnWalter** [comment]
This breaks the security of all existing Angular websites and the terminology will start to be confusing:

* Why can't I use `<a routerLink="http://example.com" />`  without `@angular/router`?
* Is "routerLink" related to the app routing module or not?
* Why does `routerLink` accept external URLs but `this.route.xyz()` doesn't?

Right now, you can simply pass any local route to it, without worrying to much about phishing attempts. You can use a parameter from the URL (like destination from `/info?destination=new-page`) directly in the `routerLink`.

If external links support is added, then instead working around "broken" external links using a simple "*ngIf", in many cases you will need to validate that you don't expose your users to phishing attempts, and this will be considerably harder to catch and deal.

Then there are all the other related functions that currently work just like the router link, those will all need to be updated and maintained, just because we wanted to avoid some simple `*ngIf` instances in our template.

P.S. With this proposal `routerLinkActive` and some related features will no longer make sense. I think that you should just create your own directive and use that instead of `routerLink`.

@jasonbaker, can you please close this?

**Comment by atscott** [comment]
We've discussed this request in the last two triage meetings and have decided that this isn't suitable for the `routerLink` directive. @SchnWalter lays out all the points we discussed really well. Aside from the big security concern, we don't believe the router package is even the right place for handling an external link. The `@angular/router` is designed for and specifically scoped to handle internal application navigations. 

This feature is a good opportunity for a community library component. I created a rudimentary example [here](https://stackblitz.com/edit/angular-ivy-anylink?file=src/app/any-link.ts).

**Comment by csimpi** [comment]
It's so lame we have to code to open a single external URL guys, please :)

**Comment by ChazUK** [comment]
Agreed, very lame.

One of the most annoying things I've found with this "community library component" approach is that you have to factor in passing every single viable attribute to both links, which makes it way more cumbersome than just passing a link string.

**Comment by csimpi** [comment]
ahhh every time I read "good opportunity for a community library component" I feel pain... I see 235 unhandled issue reports, begging for maintenance when you'd upgrade etc... it's ridiculous
