### ISSUE TITLE
Error on production

### ISSUE THREAD

**Issue by piernik** [angular/angular#24584]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
[ ] Other... Please describe:
</code></pre>

## Current behavior
When I build app with `ng build` all works as it should.
When I build app with `ng build --prod --aot=off --build-optimizer=off` it has runtime in browser error (`Cannot read property 'error' of undefined`). (App is compiling)

Is it a `uglyfiy` bug?

BTW: 
Building app with `ng build --prod` doesn't even pass build process :/
I'm great fan on angular but building process should be last easy step, but it is always path through hell :/

## Expected behavior
Production building should not have bugs!

**Comment by jasonaden** [comment]
I'm sorry but reported issues require a reproduction of the issue. We suggest using [StackBlitz](https://stackblitz.com/fork/angular-gitter), [Plunker](http://plnkr.co/edit/tpl:AvJOMERrnz94ekVua0u5?p=catalogue) or [Github](https://github.com/new).

If this issue persists, please create a reproduction using one of the links above. Describe the difference between the expected and current behavior in a new issue with the reproduction linked.

**Comment by jasonaden** [comment]
@piernik Sorry, I have to close this as it doesn't have a repro. Also, it should be filed against the CLI project.

It sounds like there's something very specific to your setup that's causing the failure, since for most of the world the `ng build --prod` command is working. Thus why a repro is needed.

It also sounds like you might just want to post something on StackOverflow with the stack trace you're seeing in the error output. That might help find what the issue is.

To file this against the CLI project, please head over to the [Angular CLI](https://github.com/angular/angular-cli) project's Github page and file it there.
