### ISSUE TITLE
Add guide-angular.wishtack.io free french guide to angular.io/resources

### ISSUE THREAD

**Issue by yjaaidi** [angular/angular#24582]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Performance issue
[ ] Feature request
[x] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
[ ] Other... Please describe:
</code></pre>

Hi!
Is it possible to add https://guide-angular.wishtack.io _(which is a free french guide to Angular focused on best practices and pragmatism)_ to https://angular.io/resources?

Thank you in advance.

**Comment by gkalpak** [comment]
You can submit a pull request, adding the info in [resources.json][1]. 
See [resources-contributing.md][2] for more info.

<sub>
Closing this issue, since it is not actionable on our part, but feel free to continue the discussion (e.g. if you have any questions, etc.).
</sub>

[1]: https://github.com/angular/angular/blob/master/aio/content/marketing/resources.json
[2]: https://github.com/angular/angular/blob/5b76f04b7f6ec6125143daf4204f309b7878e323/aio/content/marketing/resources-contributing.md

**Comment by yjaaidi** [comment]
@gkalpak thank you and sorry for the trouble.
