### ISSUE TITLE
GIF animations not loading when using DomSanitizer and img load function

### ISSUE THREAD

**Issue by andyrichardson** [angular/angular#24688]
## I'm submitting a...
Bug report

## About
I've found what seems to be a bug when using a combination of the _bypassSecurityTrustResourceUrl_ function (from _DomSanitizer_) and the _load_ function on an image element.

## Minimal reproduction of the problem with instructions
[A full reproduction can be found here](https://github.com/andyrichardson/angular-issue-24688)

#### 1. Create a component which features a getter for retrieving a sanitized url

````
// app.component.ts
import { Component } from "@angular/core";
import { DomSanitizer } from "@angular/platform-browser";

@Component({
  selector: "app-root",
  templateUrl: "./app.component.html",
  styleUrls: ["./app.component.css"]
})
export class AppComponent {
  title = "app";
  loaded = false;

  constructor(private sanitizer: DomSanitizer) {}

  get animationUrl() {
    return this.sanitizer.bypassSecurityTrustResourceUrl(
      "https://media.giphy.com/media/jzaZ23z45UxK8/giphy.gif"
    );
  }
}

````

#### 2. Create a template which consists of an image element with a load function, and the src attribute set to the sanitized url.

````
// app.component.html
<img (load)="loaded = true" [src]="animationUrl" />
````

## Current behavior
Gif animation freezes.

## Expected behavior
Gif animation plays immediately when loaded.

## What is the motivation / use case for changing the behavior?
The issue seems to be unintended and causes unexpected results.

## Environment

<pre><code>
Angular version: 6.0.3

Browser:
- [ X ] Chrome (desktop) version 67.0.3396.79
 
For Tooling issues:
- Node version: 9.11.1
- Platform:  Windows 10, Fedora 28
</code></pre>

## Other info 
Removing the _load_ function from the image element fixes the issue.

Explicitly defining the image url as a string in the template (not using DomSanitizer) fixes the issue.

**Comment by robwormald** [comment]
You're causing an infinite loop, because of the getter. Angular's change detection must execute all getters (it has to, to be able to see if the value has changed!) - you then have a load event, which triggers a change detection run, which causes the getter to re-execute, creating a new reference - Angular sees this as a new URL, and the whole process repeats to infinity.

You should generally avoid calling methods or getters from the view, for this exact reason (it's also awfully inefficient to use a getter to continuously compute what is a static value...)

See https://stackblitz.com/edit/angular-jgaaxi?file=src%2Fapp%2Fapp.component.ts for a working version.

**Comment by andyrichardson** [comment]
Thanks @robwormald that makes a lot of sense.

Would it be bad practice to use a getter for use in the view when returning a string (or any non reference type)?

example:
```
public get fullName() {
    return `${this.title} ${this.firstName} ${this.lastName}`;
}
```
