### ISSUE TITLE
Improve KeyValueDiffers find() method documentation

### ISSUE THREAD

**Issue by ehayik** [angular/angular#24748]
## I'm submitting a...
<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Performance issue
[ ] Feature request
[x ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
[ ] Other... Please describe:
</code></pre>

It's not very clear with what purpose kv argument is used in find() method of KeyValueDiffers for return an instance of KeyValueDifferFactory.

For example:
What will happen if differs.find('hello').create() method it's called, twice?
 It'll create two instances of KeyValueDifferFactory, or it'll return the same instance the second time.

**Comment by trotyl** [comment]
The `.create()` is a method of [`KeyValueDifferFactory`](https://angular.io/api/core/KeyValueDifferFactory), has nothing to do with [`KeyValueDiffers`](https://angular.io/api/core/KeyValueDiffers).

How would `KeyValueDifferFactory#create()` returns is specific to the implementation, the `DefaultKeyValueDiffer` is stateful so that `KeyValueDifferFactory` must create a new instance each time.

But other 3rd-party `KeyValueDifferFactory` implementation could be different, returning same instance is also valid, it could be used for specific data structure rather than relying on general comparison operations.

**Comment by jenniferfell** [comment]
https://angular.io/api/core/KeyValueDiffers#find
https://angular.io/api/core/KeyValueDifferFactory#create
