### ISSUE TITLE
NgModel.viewToModelUpdate does not work after upgrading to Angular 6

### ISSUE THREAD

**Issue by lainiwakurafan** [angular/angular#24783]
## I'm submitting a...

<pre><code>
[ x] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
[ ] Other... Please describe:
</code></pre>

## Current behavior

ngModel.viewToModelUpdate does not update model.

## Expected behavior

ngModel.viewToModelUpdate should update model.

## Minimal reproduction of the problem with instructions

You can check following demos with identical code, but different Angular versions. And see that directive in later of them does not update the model, while the other one do the thing.

Angular 4 demo
https://stackblitz.com/edit/angular4-viewtomodelupdate?file=app%2Fmask.directive.ts

Angular 6 demo
https://stackblitz.com/edit/angular6-viewtomodelupdate?file=app%2Fmask.directive.ts

## What is the motivation / use case for changing the behavior?

I upgraded Angular from 4.4.3 to 6.0.7 and my custom directives completely broke.

## Environment

<pre><code>
Angular version: 6.0.7

**Comment by trotyl** [comment]
Expected behavior from https://github.com/angular/angular/pull/21514, which is a [documented breaking change](https://github.com/angular/angular/blob/master/CHANGELOG.md#possible-breaking-changes). Please be aware that `Observable` is fully synchronous, and all your logics are handled before the original `viewToModelUpdate` and would be override without scheduler.

Also please do **NOT** fool people in reproduction, if you want to some directive to make effect, add it to `declarations` first:

![image](https://user-images.githubusercontent.com/6059170/42419381-86f3399e-82e6-11e8-8a89-7d80c8e9474b.png)

**Comment by trotyl** [comment]
This is about formatter implementation and should be put together at https://github.com/angular/angular/issues/3009

**Comment by kara** [comment]
As @trotyl mentioned, this is working as intended. See #21514 for the rationale /upgrade path. In your case, I would try using a `ControlValueAccessor` while waiting for parser/formatter support.
