### ISSUE TITLE
How to work with complex json objects on QueryParams and Http get requests

### ISSUE THREAD

**Issue by betosalvador** [angular/angular#24868]
## I'm submitting a...
<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Performance issue
[x ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
[ ] Other... Please describe:
</code></pre>

## Current behavior
I'm trying to send complex json objects on QueryParams like this
```
    let params = {
      search: {
        name_eq: 'John',
        status: 'active'
      },
      sort: {
        name: 'ASC'
      },
      page: 2
    }
    this.router.navigate(['/clients'], { queryParams: params });
```
When I follow this route, this is my url result:
http://localhost:4200/clients?search=%5Bobject%20Object%5D&sort=%5Bobject%20Object%5D&page=2

And my log print this:
```
{search: "[object Object]", sort: "[object Object]", page: "2"}
```

The same occurs when I try to make a 
```
    let params = {
      search: {
        name_eq: 'John',
        status: 'active'
      },
      sort: {
        name: 'ASC'
      },
      page: 2
    }
    this.http.get(url, {params: params})
```

My server receives a param "search" with a string json object inside, a param "sort" with a string object too and a param "page" with correct value (in this case => '2').

## Expected behavior
For the URL, I expect this:
http://localhost:4200/clients?search[name_eq]=John&search[status]=active&sort[name]=ASC&page=2

And for HTTP quest, I expect to receive param the same way above.

## What is the motivation / use case for changing the behavior?
I work with ruby on rails API, and is very common to receive search params in this format. 

## Environment

<pre><code>
Angular: 6.0.2

Browser:
- [x] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node: 8.11.2
- Platform:  Windows 

Others:
- API Server - Rails 5.2 (with Ransack for Searchs)
</code></pre>

Thanks in advance for the great work!

**Comment by betosalvador** [comment]
Did I do something wrong?

**Comment by timjklein36** [comment]
@betosalvador I don't think you did anything wrong, pre se, but your desired behavior isn't really supposed to be done with query parameters.

If all you are trying to accomplish is to relay all the information in this way, then you should simply "stringify" it that way.

A JavaScript object, when being represented this way, will always come out as `[object Object]` because `toString()` is called on the object and the default implementation simply returns that string.

In order to change this behavior, you could add a `toString()` method on your object so that something meaningful gets added to the query params, or you could use `JSON.stringify(object)` to normalize it before adding it to the params object.

Point being, you have to do this yourself.

If you want an object to display like the following:

```
search[name_eq]=John&search[status]=active&sort[name]=ASC&page=2
```

then you have to parse it to display this way. For example, if you have the object like so:

```javascript
const obj = {
    search: {
        name_eq: "John",
        status: "active"
    },
    sort: {
        name: "ASC"
    },
    page: 2
};
```

then you will need to write something, like the following, to parse it into the appropriate flat representation for the query params:

```javascript
let result: string = "";
for (const key in obj) {
    if (obj.hasOwnProperty(key)) {
        for(const subKey in obj[key]) {
            if (obj[key].hasOwnProperty(subKey)) {
                result = result.concat(key + "[" + subKey + "]=" + obj[key][subKey] + "&");
            }
        }
    }
}

console.log(result);
```

And you get: `search[name_eq]=John&search[status]=active&sort[name]=ASC&`.

**Comment by alxhub** [comment]
@timjklein36 is correct, query parameters don't really provide a mechanism for deep or structured data.

**Comment by betosalvador** [comment]
hello everyone

@timjklein36 
thank you very much for your sugestion

I will do this.

Sorry for delay in my reposnse

again, thank you guys!

**Comment by vankaiser** [comment]
I'm also facing the same issue, if I change it to post request it will work.

Works:
`return this.http.post<any>(environment.API_URL + '/contracts/', datatableRequest );`

Doesn't work:
`return this.http.get<any>(environment.API_URL + '/contracts/', { params: datatableRequest  } );`

I was expecting the query parameters to be serialized like jquery's $.param() function but I guess nested objects and arrays isn't serialized properly in angular's get request and have to be done manually.
