### ISSUE TITLE
Empty array query params are only in params the instance they are added

### ISSUE THREAD

**Issue by zlepper** [angular/angular#24993]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
[ ] Other... Please describe:
</code></pre>

## Current behavior
When the query params are set to an empty array programmatically Angular adds the query param to the internal router query param list. However when the page is refreshed, those params ofcause doesn't exist anymore, since they were not actually on the route in the first place. 

## Expected behavior
If Angular detects an empty array given as query parameter, then it shouldn't propagate it along to listeners. That would make the behavior consistent between reloads and just page changes. 

## Minimal reproduction of the problem with instructions
https://stackblitz.com/edit/angular-gl3dlc

## What is the motivation / use case for changing the behavior?
It caused a pretty subtle bug in some code we have related to reading how many query parameters are currently active, and then writing it to the page. We just checked the number of keys, instead of actually testing the values. 

## Environment

<pre><code>
Angular version: 6.0.9 (Seems to be the latest version at the time of writing)

Browser:
- [x] Chrome (desktop) version 69
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 

</code></pre>

**Comment by jasonaden** [comment]
Sorry this has been sitting here. I'm not really sure what to do about this issue. I believe this is up to the UrlSerializer you're using. The behavior you're describing is likely with the DefaultUrlSerializer, but it could always be overridden.

Additionally, if you're using the [`ParamMap`](https://angular.io/api/router/ParamMap) APIs (recommended), you would use the `getAll` function and behavior should be consistent.

I'm glad you filed the issue, but just thinking about it a bit more I don't believe this is a bug we can or should fix since not propagating an empty array could be a pretty big breaking change for existing apps.

I hope that explains it. If you still feel there's an issue here, please create a new issue and you can refer to this one. Thanks!
