### ISSUE TITLE
redirectTo absolute path in root routes path causing children redirectTo not work

### ISSUE THREAD

**Issue by liuwei108** [angular/angular#25177]
I have routes like this:

```
const routes: Routes = [
    { path: "", redirectTo: "/home", pathMatch: "full" },
    {
        path: "home", component: HomeComponent, children: [
            { path: "", redirectTo:"body", pathMatch: "full" },
            { path: "body", component: HelloComponent}
    ] }
];
```
with `redirectTo: "/home"`, the `redirectTo:"body"` don't work if I access `http://localhost:8080/`, it only redirect to `http://localhost:8080/home` , not `http://localhost:8080/home/body`
but if I use relative redirectTo path in the root: `redirectTo: "home"`, accessing `http://localhost:8080/` will redirect to `http://localhost:8080/home/body`

Please refer the [demo](https://stackblitz.com/edit/angular-d2jkgh)

**Comment by ponkys** [comment]
You have a typo here
```
 { path: "", redirectTo:"body", pathMatch: "full" },
```

 it's "/body"

**Comment by liuwei108** [comment]
no it is not typo, `body` is routing child of `home`

**Comment by jasonaden** [comment]
I'm sorry but reported issues require a reproduction of the issue. We suggest using [StackBlitz](https://stackblitz.com/fork/angular-gitter).

If this issue persists, please create a reproduction using one of the links above. Describe the difference between the expected and current behavior in a new issue with the reproduction linked.

<hr>

Please follow the issue template, which requires detailed steps to reproduce and the expected behavior and the actual behavior clearly defined.
