### ISSUE TITLE
TypeError: this is undefined

### ISSUE THREAD

**Issue by chaseWillden** [angular/angular#25201]
## I'm submitting a...
<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
[ ] Other... Please describe:
</code></pre>

## Current behavior

When building an app with ```ng build --prod``` and running the application in Firefox 47.0 on windows, I get an error that says: ```TypeError: this is undefined``` which points to [bootstrapModuleFactory](https://github.com/angular/angular/blob/c95437f15df93e2ca735ebf015acb20be597bb6a/packages/core/src/application_ref.ts#L217)

## Expected behavior

I expected the application to run like normal. 

## Minimal reproduction of the problem with instructions

1. Build an angular 6 app using ```ng build --prod```
2. Run the application on windows firefox 47.0

## What is the motivation / use case for changing the behavior?

Browser support

## Environment

<pre><code>
Angular version: 6.1.x

Browser:
- [ ] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [x] Firefox version 47
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: v8.11.2  
- Platform: Mac  

Others:

</code></pre>

**Comment by josephliccini** [comment]
It won't reproduce on Stackblitz because it's only for production builds.

We have a thread here: https://github.com/angular/angular-cli/issues/9340

It's due to some FF 45-50 incompatibilities with UglifyES.

If you follow the workarounds to downgrade your UglifyJsWebpackPlugin to 1.1.5 it goes away.

Our site caters to a lot of businesses who are stuck with older Firefox ESR releases due to investments in Firefox add-ons, so the downgrade fixed it for us, but a long term fix from Angular will probably be a minifier change.  I'm not sure when that will land..

**Comment by IgorMinar** [comment]
I'm not sure if there is much we can do right now as explained in https://github.com/angular/angular-cli/issues/9340#issuecomment-406598199

In addition to Filipe's comment, another suggestion would be that since affecting only FF I suggest filing an issue against Firefox. Sorry.
