### ISSUE TITLE
[innerHTML] triggers CSP alert/report in Firefox

### ISSUE THREAD

**Issue by thesam** [angular/angular#25214]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[X] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
[ ] Other... Please describe:
</code></pre>

## Current behavior
If [innerHTML] is used in a component and the Content-Security-Policy does not allow inline styles, a CSP violation will be reported by Firefox (but not by Chrome).

This is similar to AngularJS issue https://github.com/angular/angular.js/issues/16463 (also reported by me) and I think the current behaviour was introduced in https://github.com/angular/angular/pull/17019 .

## Expected behavior
It should be possible to use [innerHTML] in all supported browsers without automatically triggering a CSP violation.

## Minimal reproduction of the problem with instructions
See: https://stackblitz.com/edit/angular-gitter-8kfndn

1. Set a Content-Security-Policy which does not allow inline styles.
2. Use [innerHTML] in a component
3. Open with Firefox.

Note: Some CSP violations are generated by Stackblitz itself and should be ignored. If the example div with [innerHTML] is removed the last two CSP violations will disappear.

## What is the motivation / use case for changing the behavior?
In our application we want to use a strict CSP which does not allow inline styles. We also want CSP reports (via report-uri) whenever the CSP is violated. The current behaviour generates a large number of false positives since all our Firefox users always send a CSP report.

## Environment

<pre><code>
Angular version: 6.1.0

Browser:
- [ ] Chrome (desktop) version 68.0.3440.75
- [X] Firefox version 62.0b12

**Comment by peruukki** [comment]
Like mentioned in the Angular.js issue https://github.com/angular/angular.js/issues/16463#issuecomment-594025179, this CSP violation now appears in other browsers too, at least in Chrome.

I went through the details I could find on this:

- the Angular.js commit that introduced the CSP violation in angular-sanitize: [fix($sanitize): use appropriate inert document strategy for Firefox and Safari](https://github.com/angular/angular.js/commit/7673ca7d158fffdd8cd0e8ecb1f36901fb471c84)
- the Angular pull request that introduced this CSP violation: [fix(core): use appropriate inert document strategy for Firefox & Safari](https://github.com/angular/angular/pull/17019)
- related "Details about the Security Issue" section in [DOMPurify 0.6.7 release notes](https://github.com/cure53/DOMPurify/releases/tag/0.6.7)
- related Firefox bug report [HTML Parser ambiguity with inline svg and nested styles](https://bugzilla.mozilla.org/show_bug.cgi?id=1205631)

How to possibly remove the CSP violation: It doesn't seem that the inline `style` tag used in the Firefox bug detection is relevant; if I replace it with `span`, the bug is still detected in Firefox (and not in Chrome or Safari). I verified it by adding a `console.log` after `if (inertBodyElement.querySelector('svg img')) {` (in the Angular.js code) and `if (this.inertBodyElement.querySelector && this.inertBodyElement.querySelector('svg img')) {` (in the Angular code).

Also the related unit test description is "should not allow JavaScript hidden in badly formed HTML to get through sanitization (Firefox bug)", and none of the related discussions really mention the style tag. The bug is more related to the HTML structure than the actual tags if I understood correctly (though some tags like `img` may still be relevant).
