### ISSUE TITLE
Service Worker with Critical lib

### ISSUE THREAD

**Issue by fabienbranchel** [angular/angular#25267]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
[ ] Other... Please describe:
</code></pre>

## Current behavior
I use the Critical lib. When I use it, it's break the Angular Service Worker.

When using Critical, this is logs from Network panel : 

<img width="534" alt="capture d ecran 2018-08-02 a 15 41 44" src="https://user-images.githubusercontent.com/23743473/43587855-7532ef86-966b-11e8-901d-72b2d9b0d5cd.png">

When not using Critical, this is logs from Network panel :

<img width="529" alt="capture d ecran 2018-08-02 a 15 40 07" src="https://user-images.githubusercontent.com/23743473/43587909-94e8b022-966b-11e8-81a5-32565f002441.png">

As you may know, Critical handle the CSS. The script I use is just replace some CSS relative lines in my index.html. When using it, it's like preventing the SW to do all his work.

The issue is when we go offline, the refresh doesn't work, nothings seems to be cached by the SW.

## Expected behavior
Using Critical and SW is ok with that.

## Minimal reproduction of the problem with instructions
You can use this repo : 
https://github.com/fabienbranchel/angular-sw-critical-css

In order to have this issue, you can use this following command (make an app build prod and apply Critical script) : 
<pre><code>npm run branchel-prod-critical</code></pre>

In order to have the classic behavior, you can use this following command (make an app build prod) :
<pre><code> npm run branchel-prod</code></pre>

## What is the motivation / use case for changing the behavior?
Working stuff. :-)

## Environment

<pre><code>
Angular version: 6.1.0

Browser:
- [X] Chrome (desktop) version 68.0.3440.84 (64 bits)
- [X] Chrome (Android) version 67.0.3396.87

 
For Tooling issues:
- Node version: 10.6.0
- Platform:  macOS 10.13.6, Android 8.0.0

**Comment by gkalpak** [comment]
This happens, because the SW keeps a list of hashes for the known files (including `index.html`) and when receiving a file from the server compares the stored hash with the hashed content to see if they match. (The hash is based on the content, so if Critical is modifying the content after the hash has been computed (during `ng build --prod`) there will be a hash mismatch.)

This is currently working as expected. Maybe you could open an issue on CLI to add support for a way to hook into the build process at specific times (i.e. after `index.html` has been generated, but before the hash is computed).

As a work-around, you could run the following command at the end to re-compute the hashes (but it might have unexpected side-effects - I haven't thooroughly tested it):

```
./node_modules/.bin/ngsw-config <path/to/project/dist> src/ngsw-config.json
```
