### ISSUE TITLE
FileReader.load doesn't work!

### ISSUE THREAD

**Issue by butaixianran** [angular/angular#2533]
When reading a file from client side with Angular2 and Typescript, 

I try to use FileReader in this way:

```` javascript
var fileReader = new FileReader();
fileReader.onload = function(e) {
   console.log("run fileReader.onload");
   //  ......
}
````

But it doesn't work at all, this "fileReader.onload" function will never be called.

Really need a solution for reading files, please help. 
If, it's a bug, then, is there any work around for now?

Thanks

**Comment by pkozlowski-opensource** [comment]
@butaixianran AFAIK you can't use this API directly, you need to get instance of `FileReader` from a browser (ex. input field). 

Hard to say what is going on here without seeing a runnable example (plunker / jsbin would help here). I'm going to close this one as I can't see any evidence that this issue is Angular2 related - this sounds like a generic support question and as such should be asked using one of the support channels: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question

**Comment by butaixianran** [comment]
I finally find a way to build a online example with Typescript.

Check this from an online IDE:

preview:
https://angular2-butaixianran.c9.io/src/index.html

editor:
https://ide.c9.io/butaixianran/angular2

I do post a topic on google group, but no one answer it...
https://groups.google.com/forum/#!topic/angular/FxJrARtvZpU

**Comment by pkozlowski-opensource** [comment]
@butaixianran :
* once again, I don't think you can create instances of `FileReader` by hand, like this
* did you try to make it work in pure JavaScript, without Angular 2, TypeScript etc.? I'm asking since for me it looks like invalid API usage
* to see your example code in the editor (https://ide.c9.io/butaixianran/angular2) I'm being asked to register / log in which won't help you to get answers

My advice: first try to make it work in pure JS without any frameworks and only then post an issue

**Comment by butaixianran** [comment]
HI, thanks for your patience, here are some examples can easily play with:

First of all, as you mentioned: FileRead with pure javascript, works fine:
http://codepen.io/butaixianran/pen/gpxpww

With angular2, ES5 javascript (generate by TypeScript), doesn't work:
http://plnkr.co/edit/1MTFbVCKGGOU9XPcNVit?p=preview

With angular2 and typescript at codepen:
(Typescript with .t.d file won't work at codepen, following link just show you the TS source code)
http://codepen.io/butaixianran/pen/XbabaO

Online IDE (c9.io), sandbox with Angular2 and TypeScript, doesn't work:
(can login with github account)
https://ide.c9.io/butaixianran/angular2

Preview offered by this online IDE:
https://angular2-butaixianran.c9.io/src/index.html

Blame to TypeScript, I find that an online IDE is the the way to share an Angular2  issue with others for now. All other sandboxes just don't work well.

**Comment by robwormald** [comment]
I can replicate this outside of TypeScript - the event is firing fine, but it doesn't look like Zone is picking it up. Also, triggering a timeout-hack inside of the onload callback doesn't appear to work either, so it must be well and truly out-of-the-zone. http://plnkr.co/edit/glcsfUFJo8RlE1sn55Cr?p=preview

Side note - in Angular 1.x, ng-src wouldn't try to fetch undefined values, that doesn't appear to be the case for 2.0 w/ [src]

**Comment by vicb** [comment]
If this is a problem with zone, please create an issue on https://github.com/angular/zone.js
A small repo case with zone.js only would help (bonus point for a PR with a failing TC).
Thanks.

**Comment by butaixianran** [comment]
I learned Angular2 by following official site and docs, I have no idea what a Zone is and what's its relationship with Angular2. For now, I can only sure it's a problem with Angular2. 

If anyone can be sure it is an issue with Zone, please help to report this issue to Zone project.
FileReader is an important API for many cases, we need to make it work.

Thanks!!

**Comment by robwormald** [comment]
@vicb added a couple of specs and had a (probably misguided) attempt at fixing it : https://github.com/angular/zone.js/issues/136

**Comment by mhevery** [comment]
closing because this is zone issue: angular/zone.js#136
