### ISSUE TITLE
style guide: provide more explanation for interface naming recommendations in 03-03

### ISSUE THREAD

**Issue by themaawaa** [angular/angular#25399]
In the style guide under the topic 'interfaces' and style 03-03, there is mention of the [`Following guidelines`](https://github.com/Microsoft/TypeScript/wiki/Coding-guidelines). The reference in question does say that everything contained appends to **contributors of angular**, and not as a guideline for community use.

I propose to either include the reasoning for `Why? TypeScript guidelines discourage the I prefix.` inside the style guide, or remove this topic.

**Comment by jenniferfell** [comment]
Thanks for submitting this issue. I've taken a look. 

- The Angular Style Guide does not prohibit using the I prefix. This guideline says "consider", meaning the guideline should generally be followed. It is neither a "do" (must do) nor "avoid." You can do what makes sense for your app and organization, but the Angular team has offered their recommendation here. 

- Why? Angular is built on top of TypeScript, so I think the reason is sufficient. Where possible, Angular recommends following TypeScript best practices. 

I do, however, see your point that TypeScript describes their guideline as being for "contributors to TypeScript". From their site (thanks for the link): "We have chosen many of them for team consistency. Feel free to adopt them for your own team. AGAIN: This is NOT a prescriptive guideline for the TypeScript community."

Both sites are consistent in that neither prohibits the I prefix for interface names. 

I'm not sure that an Angular style guide change is necessary. Angular makes a recommendation, with supporting link to TypeScript. 

That said, I'm going to let @IgorMinar weigh in on this.

**Comment by jenniferfell** [comment]
filename: https://angular.io/guide/styleguide#interfaces

request: provide more information about these sentences: 
Consider naming an interface without an I prefix.
Why? TypeScript guidelines discourage the I prefix.

**Comment by themaawaa** [comment]
Thank you for your feedback.

**Comment by brandonroberts** [comment]
Specific coding conventions such as discouraging use of I for interfaces has been removed in #29331
