### ISSUE TITLE
Angular.io documentation - Reattaching a detached component - has wrong example

### ISSUE THREAD

**Issue by cmer4** [angular/angular#25495]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Performance issue
[ ] Feature request
[x] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
[ ] Other... Please describe:
</code></pre>

## Current behavior
currently here: https://angular.io/api/core/ChangeDetectorRef#reattaching-a-detached-component the example provided in the last section is just a duplicate of previous section (detach change detector)

## Expected behavior
the section about reattaching change detection should feature relevant code sample

## Minimal reproduction of the problem with instructions
go here: https://angular.io/api/core/ChangeDetectorRef#reattaching-a-detached-component
observe duplicate sample and not relevant sample

## What is the motivation / use case for changing the behavior?
confusing documentation. even if this is a minor issue.

## Environment
N/A

Browser:
- [ x] Chrome (desktop) version 68
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX

**Comment by jenniferfell** [comment]
Confirmed
https://angular.io/api/core/ChangeDetectorRef#detach-change-detector-to-limit-how-often-check-occurs
has the correct example for that section. 

https://angular.io/api/core/ChangeDetectorRef#reattaching-a-detached-component repeats that same example instead of showing a new example for attaching.

Quick summary of options: 
1) Minimally, we need to remove where example is duplicated into incorrect section. 
2) Next LOE is to see if we have the right example ready to insert here. If so, insert existing docregion. If not, see 3 below.
3) If there is no existing example to insert, then--after doing 1 and 2--this becomes a feature request for a new example.

**Comment by jenniferfell** [comment]
@jbogarthyde Hi. I see that you updated API doc for ChangeDetectorRef in July. When you get a chance, could I ask you to take a look at this? Thanks!

**Comment by dariobraun** [comment]
I think this was fixed, so the issue can be closed, no?

**Comment by gkalpak** [comment]
Fixed in ##25582.
