### ISSUE TITLE
Introduce ngOnAttach/ngOnDetach lifecycle hooks

### ISSUE THREAD

**Issue by vakrilov** [angular/angular#25521]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Performance issue
[x] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
[ ] Other... Please describe:
</code></pre>

## The Problem
Currently, when components are detached/attached using a custom [`RouteReuseStrategy`](RouteReuseStrategy) there is no easy API to execute logic when the component has been detached/reattached. The most common case is that you want to re-fetch/refresh data whenever the component has beed re-attached. Usually, the `ngOnInit` hook is used for that, but since the component is reused - it is not fired. Also, you might want to unsubscribe from observables on detaching, but you cannot do that on `ngOnDestroy` as it is not fired.

Here is simple [stackblitz example](https://stackblitz.com/edit/router-reuse-strategy-g3vmza?embed=1&file=app/details/details.component.ts), where we want to be able to start/stop a timer only when a component is attached.

>Note: [NativeScript Angular](https://github.com/NativeScript/nativescript-angular) apps use a custom `RouteReuseStrategy` by default, which integrates with the native mobile navigation stack (this is used to cache native components). This can cause a confusion between a default Web Angular app and a default NativeScript Angular app.

## Proposed Solution
Introduce two new lifecycle hooks - `ngOnAttach`/`ngOnDetach`. They will be fired whenever the component has been attached or detached to the component tree. The main difference with `ngOnInit`/`ngOnDestroy` is that the attach/detach hooks can be called multiple times in the lifetime of a component.

The new lifecycle hooks should be fired recursively for child components that are being attached and detached with their parent too.

Here is a state diagram of components, along with the events fired when switching between states. 

```

ctor()   ┌─────────────┐  ngOnInit() ┌──────────┐ ngOnDestroy() ┌───────────┐
───────> │ constructed │ ──────────> │ detached │ ────────────> │ destroyed │
         └─────────────┘             └──────────┘               └───────────┘
                                         │ ∧
                            ngOnAttach() │ │ ngOnDetach()
                                         ∨ │
                                     ┌──────────┐
                                     │ attached │
                                     └──────────┘          
```

In the above stakplitz example you would be able to use the `ngOnAttach()`/`ngOnDetach()` hooks to subscribe and unsubscribe. In fact in apps that do not utilize a custom `RouteReuseStrategy`, these events would be equivalent to `ngOnInit()`/`ngOnDestroy()`. So these will be a good alternative to use when you have projects that share code base between web and mobile (using NativeScript).

**Comment by trotyl** [comment]
It would also benefit the "content projection to `<ng-template>`" case like https://github.com/angular/angular/issues/13921, where the projected components will be created on detached DOM elements.

**Comment by montella1507** [comment]
@trotyl  hi regarding this issue i have a question...do not  you think this is serious issue on angular design... ? At the moment is is definitively not possible to write components that depend on DOM - Graphs, maps, canvas... because... usually you start scripting your component in current hoooks (OnI it, AfterViewInit,...). But as you know it wont work when is your component used in anything using ng-content,...and this is literally big issue... just try to use captcha/maps/graphs components in any Tabs component - for example... mat-tabs component...it will not work because code is fired regardless component is in DOM or not... 

I lived in false meaning AfterViewInit is a proof that m component is in DOM but this is not true in content projection... how shoukd we write bulletproof components depending on DOM without this...i think template and templateoutlet is not bulletproof solution. Thx for answer... i just think this festure is underestimated

**Comment by montella1507** [comment]
@trotyl  i am still not sure we are on the same page...  Example:

LIBRARY:
-------------

1) //chart.component.html 
  <svg class="chart-to-init"></svg>
2) // chart.component.ts 
 ngAfterContentInit(): void {
        this.svg = this.svg != null ? this.svg : d3.select('svg.chart-to-init');
        this.draw();   // draw via d3.js api
 }
 
3) content.component.html
  <ng-container *ngIf="enabled">
     <ng-content></ng-content>
  </ng-container>
  <button (click)="enabled=true">ENABLE</button>

4) content.component.ts
   enabled = false;
  ...

USAGE:
----------
<content>
  <chart></chart>
</content>

SUMMARY:
------------
D3 (and other libraries) are not declarative based (in html) so you cannot use binding = you have to select existing SVG and apply methods of D3 API. But...  graph will not be rendered, because of ng-content in IF.

How will you solve this issue without attach /detach hooks?

**Comment by montella1507** [comment]
@mlc-mlapis  you are wrong, anything that is transcluded via ng-content is instantiated with component it is used.. so in my case:

a.component.html
<content>
  <xyz></xyz>
</content>

XYZ is instantiated with  A, not with CONTENT.. But i am talking and questioning existence in DOM.. because d3.select() is querying DOM. This is WHY we need to be sure, if something is / is not in DOM..  I know it is bad practice to depend on DOM, however we really need to use 3rd party libraries in angular..  and they are  depending on DOM.

**Comment by mlc-mlapis** [comment]
@montella1507 ... I thought that it's instantiated together with the component which template contains `<ng-content>` and I understood that it is `ContentComponent`. I am not sure what is `A` component, you didn't mention it before.

And also you can use a setter `@ContentChild('myChart') set myChart(value) { ... };` for getting the right moment.
```
<content>
  <chart #myChart></chart>
</content>
```

**Comment by montella1507** [comment]
@mlc-mlapis  

And also you can use a setter @ContentChild('myChart') set myChart(value: ChartComponent) { ... }; for getting the right moment = when the component is placed into the DOM on the base of *ngIf.

<content>
  <chart #myChart></chart>
</content>


this is not SOLVING issue... look.. i gave you simplified example...  but you can just imagine typicall TABS component...
<tabs>
  <tab>
     <chart></chart>
  </tab>
</tabs>

where <tab> component is using <ng-content> and *ngIf="active":
// tab.component.html
 <ng-container *ngIf="active">  // put in DOM <chart> (in chart is that SVG) only when this tab is active
 <ng-content>
</ng-content>
</ng-container>


... TAB component doesnt know ChartComponent.. it is universal component...  so i cannot use ContentChild ;-)

**Comment by mlc-mlapis** [comment]
@montella1507 ... but it's your component ... that `<tab>` or `<tabs>` right, so if you use and place `@ContentChild(...) set myChart(value: ...) { ... };` in it, it would work, right? For the structure as ... would be necessary to have the possibility to get all `<chart>` component probably.
```
<tabs>
  <tab ngProjectAs="chart">
     <chart></chart>
  </tab>
</tabs>
```
I don't want to say that the suggested new hooks `attach/detach` wouldn't be perfect, only to mention the actual possibilities.

**Comment by montella1507** [comment]
I just want to say to developers,  importance of having DOM attach / detach lifecykle hooks or something similar is way more bigger than they propably think, because if you want to use several 3rd party libraries not written entirely in angular, you have to got certainty an element is in DOM  - or to know - when it is attached / detached  to/from DOM.   Because 3rd party library is querying document tree...


In 90% of cases it works at the moment without these new Hooks, because you will put that "dom dependent code" in ngAfterContentInit or similar,.. however it doesnt work in ng-content  in situations like this:
`
<ng-container *ngIf="active">
<ng-content>
</ng-content>
`

because AfterContentInit (or ViewInit - doesnt matter) are called, but "your html is not in DOM" - so your 3rd party library call (for example d3.select()) will fail... 

At the moment we have to workarround this and call manually something like "repaint()" when tab's got active (and <svg> is in DOM).. but this is not right way..

**Comment by mlc-mlapis** [comment]
... then `MutationObserver` https://developer.mozilla.org/en-US/docs/Web/API/MutationObserver would be also the way how to get the right moment.

**Comment by klinki** [comment]
I like this idea, I think it would be a great addition to Angular. I'm familiar with a similar concept from Aurelia (and I believe this concept is used also in other frameworks) and this would make it easier for developers coming from these frameworks to use Angular.

And of course, it would significantly improve interoperability with libraries using DOM.

**Comment by trotyl** [comment]
@montella1507 I mean you cannot rely on Angular to check anyway.

The root Angular component may not be inside `document` either:

```typescript
const myComponentRef = myComponentFactory.create(injector, undefined, document.create('div'))
appRef.attachView(myComponnetRef.hostView)
```

Also the element may be controlled by 3rd-party library:

```html
<div class="third-party-modal-content">
  <my-component></my-component>
</div>
```

Attached to parent doesn’t mean being a descendant of `document`, and vice versa. You will always need to guard it yourself if you require some element to be in `document`.

**Comment by montella1507** [comment]
Well.. to be honest i found another way to make it work now - concretely i made D3 work.. 

OLD:
this.svg = d3.select('svg.chart-to-init') // querying document node. 

NEW:
// html
<svg    #svg>
// ts
 @ViewChild('svg') svgElement: ElementRef;
ngAfterViewInit() {
this.svg = d3.select(this.svgElement.nativeElement;
}

But it needs further testing.. If i am right, common solution is to make "boundary" arround 3rd party library's querying in document and eliminate it. Hmm?

**Comment by hrabia9933** [comment]
I have some CustomReuseStrategy that I found somewhere some time ago, which supports this kind of solution. What you need to do is to simply put a function in your component called ngOnAttach or ngOnDetach and put your logic inside:

`import {
    ActivatedRouteSnapshot,
    DetachedRouteHandle,
    RouteReuseStrategy
} from '@angular/router';
import { ComponentRef } from '@angular/core';

interface DetachedRouteHandleExt extends DetachedRouteHandle {
    componentRef: ComponentRef<any>;
}

interface RouteCacheRecord {
    handle: DetachedRouteHandleExt;
    /**
     * For unclear reasons, when the navigation starts, `retrieve` is called
     * without calling `shouldAttach` first (from `createRouterState`).
     * This flag is used to ignore those calls. :-\
     * */
    shouldAttachCalled: boolean;
}

export class CustomReuseStrategy implements RouteReuseStrategy {
    private routeCache = new Map<string, RouteCacheRecord>();

    shouldDetach(route: ActivatedRouteSnapshot): boolean {
        const shouldDetach = !this.isToBeIgnored(route, 'shouldDetach');
        return shouldDetach;
    }

    store(route: ActivatedRouteSnapshot, detachedTree: DetachedRouteHandleExt | null): void {
        const key = this.getSnapshotKey(route);

        if (!detachedTree || this.isToBeIgnored(route, 'store')) {
            return;
        }

        const previousStored = this.routeCache.get(key);
        if (previousStored) {
            if (!(previousStored.handle.componentRef === detachedTree.componentRef)) {
                previousStored.handle.componentRef.destroy();
            }
        }

        this.routeCache.set(key, {
            handle: detachedTree,
            shouldAttachCalled: false
        });

        if (detachedTree) {
            this.callHook(detachedTree, 'ngOnDetach');
        }
    }

    shouldAttach(route: ActivatedRouteSnapshot): boolean {
        const key = this.getSnapshotKey(route);
        const stored = this.routeCache.get(key);
        const destroyed = !!(
            stored && stored.handle.componentRef.hostView.destroyed
        );
        const msgStatus = destroyed ? 'DESTROYED' : stored ? 'FOUND' : 'NOT FOUND';
        const shouldAttach =
            !destroyed && !!stored && !this.isToBeIgnored(route, 'shouldAttach');
        if (shouldAttach) {
            stored.shouldAttachCalled = true;
        }
        return shouldAttach;
    }

    retrieve(route: ActivatedRouteSnapshot): DetachedRouteHandleExt | null {
        const key = this.getSnapshotKey(route);
        const stored = this.routeCache.get(key);
        const destroyed = !!(
            stored && stored.handle.componentRef.hostView.destroyed
        );
        const shouldBeRetrieved =
            !destroyed && !!stored && stored.shouldAttachCalled;

        if (destroyed) {
            this.routeCache.delete(key);
        }

        if (shouldBeRetrieved) {
            stored.shouldAttachCalled = false;
            if (this.isToBeIgnored(route, 'retrieve')) {
                return null;
            }
            const detachedTree = stored.handle;
            this.callHook(detachedTree, 'ngOnAttach');
            return detachedTree;
        }

        if (this.isToBeIgnored(route, 'pre-retrieve')) {
            return null;
        }

        return stored ? stored.handle : null;
    }

    shouldReuseRoute(future: ActivatedRouteSnapshot, curr: ActivatedRouteSnapshot): boolean {
        const result = future.routeConfig === curr.routeConfig; // from DefaultRouteReuseStrategy
        return result;
    }

    private getSnapshotKey(snapshot: ActivatedRouteSnapshot): string {
        return snapshot.pathFromRoot.join('->');
    }

    private isToBeIgnored(route: ActivatedRouteSnapshot, msg: string) {
        if (!route.routeConfig) {
            return true;
        }

        if (route.routeConfig.loadChildren) {
            return true;
        }

        if (route.children.length) {
            return true;
        }

        return false;
    }

    private callHook(detachedTree: DetachedRouteHandleExt, hookName: string): void {
        const componentRef = detachedTree.componentRef;
        if (
            componentRef &&
            componentRef.instance &&
            typeof componentRef.instance[hookName] === 'function'
        ) {
            componentRef.instance[hookName]();
        }
    }
}

`

**Comment by bryanrideshark** [comment]
I am running into an issue in Angular 10, when using `cdk-virtual-scroll`. since it detaches views and we do not have this hook, visual artifacts are left behind. These list items each show a route on an interactive map; when the list is removed or recycled, the routes remain behind as `ngOnDestroy` is not called and there is currently no hook.

I will be forced to work with DOM Events to try and workaround this glaring omission from Angular. Now that Ivy is done, can we finally get this feature?

**Comment by pilz97** [comment]
@hrabia9933 I have implemented a similiar solution, but now i have a problem with the child components, they don't get the ngOnAttach only the parent component does.

**Comment by FortinFred** [comment]
@hrabia9933 
Thanks for the workaround.  It has greatly inspired me to make one myself.

I've improved it by putting the logic in a distinct service so that I don't have to replicate the logic in multiple strategies.  I'm not fully satisfied because it feels a bit like a hack but isolating the logic will make it easier to "unplug" it when this feature request gets implemented.


The thing is I needed a lifecycle hook after the DOM was reloaded with the component (Some legacy code bridging requirement involving jQuery's DataTables and column adjustments)

Anyway I implemented two hooks **ngBeforeAttach** and **ngAfterAttcach**.

**_TODO_**: Implement **ngBeforeDetach** and **ngAfterDetach**

The **ngBeforeAttach** will be called at the same moment as your code.
The **ngAfterAttach** will be called after the next **NavigationEnd** event. (**ActivationEnd** was triggering multiple times)


In your AppModule
```
  providers: [
    AttachDetachHooksService,
    { provide: RouteReuseStrategy, useClass: AllRouteReuseStrategy },
    { provide: APP_INITIALIZER, useFactory: initAttachDetachHooks, deps: [Router, RouteReuseStrategy], multi: true}
  ]

```

```
import { Component, ComponentRef, Injectable } from '@angular/core';
import { ActivatedRouteSnapshot, ActivationEnd, DetachedRouteHandle, NavigationEnd, Router, RouteReuseStrategy } from '@angular/router';

interface DetachedRouteHandleExt extends DetachedRouteHandle {
  componentRef: ComponentRef<Component>;
}

/**
 * Intercepts calls to the RouteReuseStrategy
 * and will trigger 'ngBeforeAttach' and 'ngAfterAttach' custom hooks
 */
@Injectable()
export class AttachDetachHooksService {

  private pseudoSuper: {
    retrieve: (route: ActivatedRouteSnapshot) => DetachedRouteHandleExt,
    shouldAttach: (route: ActivatedRouteSnapshot) => boolean
  };

  private currentHandle: DetachedRouteHandleExt;
  private pendingBeforeAttach: boolean;

  constructor(router: Router, reuseStrategy: RouteReuseStrategy) {

    // Init intercepts
    this.pseudoSuper = {
      shouldAttach: reuseStrategy.retrieve.bind(reuseStrategy),
      retrieve: reuseStrategy.retrieve.bind(reuseStrategy),
    };

    reuseStrategy.retrieve = this.retrieve.bind(this);
    reuseStrategy.shouldAttach = this.shouldAttach.bind(this);


    // Router events
    router.events.pipe().subscribe(event => {
      if (event instanceof NavigationEnd && this.currentHandle) {
        this.callHook(this.currentHandle, 'ngAfterAttach');
      }
    });
  }


  private retrieve(route: ActivatedRouteSnapshot): DetachedRouteHandleExt {
    this.currentHandle = this.pseudoSuper.retrieve(route) as DetachedRouteHandleExt;

    if(this.pendingBeforeAttach) {
      this.callHook(this.currentHandle, 'ngBeforeAttach');
      this.pendingBeforeAttach = false;
    }

    return this.currentHandle;
  }

  private shouldAttach(route: ActivatedRouteSnapshot): boolean {
    this.pendingBeforeAttach = this.pseudoSuper.shouldAttach(route);
    return this.pendingBeforeAttach;
  }

  private callHook(detachedTree: DetachedRouteHandleExt, hookName: string): void {
    if(detachedTree && detachedTree.componentRef) {
      const componentRef = detachedTree.componentRef;
      if (
          componentRef &&
          componentRef.instance &&
          typeof componentRef.instance[hookName] === 'function'
      ) {
          componentRef.instance[hookName]();
      }
    }
  }
}
```

Feedback is more than welcome :)

**Comment by DmitryBrus** [comment]
@FortinFred 
thanks for the idea.
could you please share more code: initAttachDetachHooks class, AllRouteReuseStrategy ...

**Comment by FortinFred** [comment]
@DmitryBrus 

I've updated my previous comment with the **initAttachDetetachHooks** factory function. 

As for the **AllRouteReuseStrategy** this is a compliant RouteReuseStrategy that really has nothing to do with the hook logic.  Whatever ReuseStrategy you implement should work with the AttachDetetachHooks service.

**Comment by DmitryBrus** [comment]
@FortinFred thank you

BTW, I also can't understand why `retrieve` called twice.  I found the same question but no any clear answer.

**Comment by montella1507** [comment]
@alxhub  i dont think this should be closed in https://github.com/angular/angular/commit/4f3beffdbfa974b380b2225f163d363dd17e10bd

Main reason to provide Attach/Detach is not routing, but ng-content with ngIF and other situations...  That commit adds hooks that are called only by router?   But what about:


// a component
<b>
  // ng-content
  <c></c>
</b>

//b component
<ng-content *ngIf="show">
<ng-content>


// component
ngOnAttach() {
   // now i should be called when attached to DO - propably after SHOW is set to true in B component
}

this is very common issues - for example - any component like popup / accordion / tooltip if it is using ng-content and not templateRef.

**Comment by colinbr96** [comment]
This StackOverflow thread provides a few good solutions as well:
https://stackoverflow.com/questions/46519512/angular2-routereusestrategy-lifecycle-hooks
