### ISSUE TITLE
include json file in ng-packagr build error

### ISSUE THREAD

**Issue by morzyns** [angular/angular#25560]
## I'm submitting an error

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
[ ] Other... Please describe:
</code></pre>

## Current behavior

> Cannot find module 'error TS2307: Cannot find module './translations/en-US.json'.

## Expected behavior
As VS Code linter doesnt show any issues i expect the module to be build without issues.

## Minimal reproduction of the problem with instructions
I added typings.d.ts in the /library directory
with:
```
declare module "*.json" {
  const value: any;
  export default value;
}
```

The tsconfig.lib.json looks like:

```
{
  "extends": "../../tsconfig.json",
  "compilerOptions": {
    "outDir": "../../out-tsc/lib",
    "target": "es2015",
    "module": "es2015",
    "moduleResolution": "node",
    "declaration": true,
    "sourceMap": true,
    "inlineSources": true,
    "emitDecoratorMetadata": true,
    "experimentalDecorators": true,
    "importHelpers": true,
    "lib": [
      "dom",
      "es2015"
    ]
  },
  "angularCompilerOptions": {
    "annotateForClosureCompiler": true,
    "skipTemplateCodegen": true,
    "strictMetadataEmit": true,
    "fullTemplateTypeCheck": true,
    "strictInjectionParameters": true,
    "flatModuleId": "AUTOGENERATED",
    "flatModuleOutFile": "AUTOGENERATED"
  },
  "exclude": [
    "src/test.ts",
    "**/*.spec.ts"
  ]
}

```

The way i import:

```
import * as enUS from './translations/en-US.json';
import * as plPL from './translations/pl-PL.json';

```
## What is the motivation / use case for changing the behavior?

I need to import translation files in angular library, generated with angular cli / using ngPackager
json files needed to ngTranslate module in Angular library.

## Environment

<pre><code>
Angular version: ^6.0.1

Mac/ typescript 2.7.2

**Comment by morzyns** [comment]
Any comment to help with this?

**Comment by jasonaden** [comment]
@morzyns I'm not sure what's happening with your example here. This is much more of a support request than a bug report though, and should be sent over to [StackOverflow](http://stackoverflow.com/) using tag `angular`. If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).

If you think there's an actual bug here, you need to send in steps to reproduce and a running reproduction. You can use [StackBlitz](https://stackblitz.com/fork/angular-gitter) and submit a new issue.
