### ISSUE TITLE
ngClass directive removes class duplicates

### ISSUE THREAD

**Issue by bvdmitri** [angular/angular#25659]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
[ ] Other... Please describe:
</code></pre>

## Current behavior

ngClass directive removes class duplicates, it can be essential when using css frameworks such as SemanticUI.

E.g.

`<button class="ui button right labeled right floated" [ngClass]="{'disabled':false}">`

in runtime will convert to

`<button class="ui button right labeled floated" ...ng-related-stuff... >`

'right' css modifier in 'right floated' rule is missing now.

## Expected behavior

ngClass directive should not modify the original class rules.

## Minimal reproduction of the problem with instructions

[StackBlitz](https://stackblitz.com/github/bvdmitri/angular-ngclass-bug)
[GitHub](https://github.com/bvdmitri/angular-ngclass-bug)

## Environment

<pre><code>
Angular version: 6.1.4

Browser:
- [x] Any

</code></pre>

**Comment by pkozlowski-opensource** [comment]
Thnx @trotyl for confirming - this is what I was expecting.
@bvdmitri as @trotyl pointed out any operation on `classList` will remove duplicates - there is simply no way of expressing things like "add / remove first `right` class but not the others".

As such, in current browsers, usage of `classList` _will_ remove duplicates. There is nothing Angular can do about it. And we definitively _want_ to use `classList` for fast CSS class name manipulation.

One could imagine a different implementation of `ngClass` that is doing string manipulation instead of `classList` but it would be pretty inefficient and memory-hungry. As such we can't do it in Angular.

If you absolutely want / need to use a CSS framework that _requires_ duplicate CSS class names you will have to:
* roll out your own equivalent of `ngClass`
* stop using `[class.foo="exp"` bindings.

Closing as won't fix in Angular.
