### ISSUE TITLE
keyvalue pipe wrong sorting result

### ISSUE THREAD

**Issue by jimmy29347** [angular/angular#25667]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ x] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
[ ] Other... Please describe:
</code></pre>

## Current behavior

wrong order when there are more than 10 elements in keyvalue pipe

## Expected behavior

should return in unsorted order when an object has more than 10 elements

## Minimal reproduction of the problem with instructions

https://stackblitz.com/edit/angular-xfodd8

## Environment

<pre><code>
Angular version: X.Y.Z

Browser:
- [ ] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: XX  
- Platform:  
windows chrome

Others:

</code></pre>

**Comment by dawidgarus** [comment]
I don't think that's possible:
1. Array's sort function that pipe uses doesn't have to perform stable sorting. When Your compare function always returns 0, sort function treats all items as equal, so it could really return items in any order. You could replace it with custom implementation that performs stable sorting but it wouldn't matter because...
2. JavaScript object doesn't have to remember order of the keys. Even if You define object as literal: `{"a": 0, "b": 0, "c": 0}`, when You iterate over it's keys "b" can come before "a". That's how JS works.

**Comment by manklu** [comment]
As alternative you could use a map and write a custom version of keyvalue pipe which doesn't sort. Looking at the source, this shouldn't be too hard.

**Comment by jmac11** [comment]
My fualt

**Comment by Toxicable** [comment]
The `keyvalue` pipe uses the `Array#sort` method, if you have an issue then it's with JS not the pipe.
You can see more docs here: 
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/sort
And here's the src where the sort fn is applied: 
https://github.com/angular/angular/blob/master/packages/common/src/pipes/keyvalue_pipe.ts#L81

**Comment by jimmy29347** [comment]
thanks for the suggestions. I finally resolved the problem by adding my own order property to the object
