### ISSUE TITLE
Test fails when calling HttpTestingController.expectOne and rxjs from() with a Promise

### ISSUE THREAD

**Issue by seangwright** [angular/angular#25733]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ X] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
[ ] Other... Please describe:
</code></pre>

## Current behavior
When using the rxjs operator `from` with a promise in an interceptor my unit test fails when I call `HttpTestingController.expectOne('url');`.
The test fails despite the `HttpClient` having made a request to the matching url.

If I remove the use of `from(promise)` in my interceptor the test passes.

## Expected behavior
The test passes

## Minimal reproduction of the problem with instructions
Here is a repo of the issue.
Clone, `npm i`, `npm run test` and you'll see the error.
The interceptor and test are named `promise.interceptor.ts` and `promise.interceptor.spec.ts`

https://github.com/sgwatgit/ng-promise-interceptor-test-bug

Here are others that are experiencing the same issue:
https://stackoverflow.com/questions/51047227/could-not-test-angular-http-interceptor-with-karma-and-jasmine

```typescript
// Interceptor
const promise = Promise.resolve('abcd');
return from(promise).pipe( // <-- replacing from(promise) with of('abcd') will allow the test to pass
  flatMap(bearerToken => {
    if (bearerToken) {
      req = req.clone({ setHeaders: { Authorization: `Bearer ${bearerToken}` } });
    }
    return next.handle(req);
  }));
```

```typescript
// Test
it('should set authorization headers with a bearer token', (done: DoneFn) => {
    client.get<{ test: boolean }>('/').subscribe(done);

    const testRequest = controller.expectOne('/'); // <-- fails here
```

## What is the motivation / use case for changing the behavior?
There are authZ/authN npm packages for Angular that have services returning promises for things like Bearer tokens or authentication state.

If I want to attach a Bearer token from one of these services to an outgoing http request I want to use an interceptor. To get the promise value into my Observable pipeline I need to use `from`.

Now if I want to test this interceptor it makes sense to use `HttpTestingController` and call `.expectOne('url');` after my `HttpClient` makes the request.

## Environment

<pre><code>
Angular CLI: 6.1.5
Node: 10.8.0
OS: win32 x64
Angular: 6.1.4
... animations, common, compiler, compiler-cli, core, forms
... http, language-service, platform-browser
... platform-browser-dynamic, router

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.7.5
@angular-devkit/build-angular     0.7.5
@angular-devkit/build-optimizer   0.7.5
@angular-devkit/build-webpack     0.7.5
@angular-devkit/core              0.7.5
@angular-devkit/schematics        0.7.5
@angular/cli                      6.1.5
@ngtools/webpack                  6.1.5
@schematics/angular               0.7.5
@schematics/update                0.7.5
rxjs                              6.2.2
typescript                        2.7.2
webpack                           4.9.2

Browser:
- [X] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: 10.8.0
- Platform:  Windows

</code></pre>

**Comment by LM-G** [comment]
I have exactly the same problem. In my case i use a `from` followed by a switchMap making an HTTP call. The  HTTP call get canceled instantly but i think this is a rxjs bug.

**Comment by jziggas** [comment]
Dang wish I checked GH issues earlier! I am experiencing this as well. In my case there is an interceptor set up to refresh an auth token before handling the request. So it looks like:

```
from(this.refreshAuthToken()).then(() =>
    return next.handle(request)).source
```

The http subscription never gets fired in the unit test despite it reaching the interceptor and `next.handle` getting called.

**Comment by pawelkondraciuk** [comment]
Facing the same issue while using `@auth0/angular-jwt` with Promise as tokenGetter.

**Comment by djosemartine** [comment]
Try 
it('should set authorization headers with a bearer token', **async**(() => {
    client.get<{ test: boolean }>('/').subscribe(done);

    const testRequest = controller.expectOne('/');
})):

**Comment by Blackbaud-PaulCrowder** [comment]
Chiming in here because I have the same issue.  I have an interceptor that goes and gets a bearer token from a remote source, then adds the `Authorization` header to the request before invoking it.  

Here's a link to the interceptor code.  Note the use of `tokenProvider` to get the bearer token.  I mock this out during my test so that it immediately resolves.

https://github.com/blackbaud/skyux-http/blob/master/src/app/public/modules/auth-http-client/auth-interceptor.ts#L97

And here's an example test that fails because the request isn't invoked until after the `expectOne()` call.  `svc.getNavigation()` is a method that calls `HttpClient.get()`:

```
    it('should build the appropriate URL based on the provided service ID', () => {
      const svcId = 'ab%&c';
      const svcIdEncoded = encodeURIComponent(svcId);

      const expectedUrl = `${getNavigationBaseUrl}?svcid=${svcIdEncoded}`;

      svc.getNavigation(svcId, undefined, undefined, undefined, false, undefined)
        .subscribe();

      httpMock.expectOne(expectedUrl);
    });
```

If I don't provide the HTTP interceptor in my application, this test passes.  My workaround is to wrap the `expectOne()` in a `setTimeout()`:

```
    it('should build the appropriate URL based on the provided service ID', (done) => {
      const svcId = 'ab%&c';
      const svcIdEncoded = encodeURIComponent(svcId);

      const expectedUrl = `${getNavigationBaseUrl}?svcid=${svcIdEncoded}`;

      svc.getNavigation(svcId, undefined, undefined, undefined, false, undefined)
        .subscribe();

      setTimeout(() => {
        httpMock.expectOne(expectedUrl);
        done();
      });
    });
```

**Comment by rjsteinert** [comment]
I ran into this issue because my service gets a couple things out of the Promise based PouchDB library in order to form some parts of the HTTP request. Is it safe to say that it's likely that Promises will be involved in services and the above work around should be documented [here](https://angular.io/guide/http#testing-http-requests)?

**Comment by thibaud-sanchez** [comment]
I got the same problem, I have to flush multiple requests that are executed successively with promises.
It should be useful to put a timeout  value on expectOne that wait for x second before throwing error...
For now I will use spyOn instead of expectOne, because it's too restrictive.

**Comment by alxhub** [comment]
This is not an issue with `HttpTestingController`, but rather with the nature of asynchronous testing in general.

Any time a `Promise` is involved, its resolution is asynchronous. Therefore immediately after calling `HttpClient.get(...).subscribe()`, the request will not have reached the backend, because the interceptor is waiting on the `Promise` to resolve before forwarding the request.

To deal with this asynchronicity it is necessary to use asynchronous testing techniques such as `fakeAsync`:

```typescript
it('should set authorization headers with a bearer token', fakeAsync((done: DoneFn) => {
    client.get<{ test: boolean }>('/').subscribe(done);

    // Flush the microtask queue, which resolves the Promise, causing the interceptor
    // to forward the request to the backend where it can then be expected by the testing
    // controller.
    flush();

    const testRequest = controller.expectOne('/');
    const request = testRequest.request;

    expect(request.headers.has('Authorization'));
    expect(request.headers.get('Authorization')).toBe(`Bearer ${bearerToken}`);

    testRequest.flush({ test: true });
  }));
```

I'm going to leave this issue open as a point of confusion - maybe we can improve our documentation on interceptors/HTTP testing to point out this potential hazard.

**Comment by trevoreyre** [comment]
Maybe I'm missing something, but @alxhub example above doesn't work for me. I can't wrap my test in `fakeAsync` and also use Jasmine's `done` function, because it's undefined if I wrap the test in the `fakeAsync` function. Is that working for other people? Do I need to update versions or something?

**Comment by ramses512** [comment]
I have the same problem, and nothing working for me.

**Comment by JoostK** [comment]
This is essentially the same as #25965, so closing this one in favor of that issue.
