### ISSUE TITLE
Run JavaScript tests in the strict mode

### ISSUE THREAD

**Issue by vsavkin** [angular/angular#2575]

**Comment by IgorMinar** [comment]
in browser tests we emit strict mode code, but in cjs we don't because typescript doesn't support it at the moment. See: https://github.com/Microsoft/TypeScript/issues/3576.

we could hack this by prefixing all the cjs build artifacts with 'use strict' at least until typescript fixes the issue in the emitter.

**Comment by IgorMinar** [comment]
@caitp can you add a replace pass into the node tree that does this, please?

**Comment by caitp** [comment]
You just want the tests running in strict mode, and not the module code right? `modules/angular2/src/util/decorators.js` tries to block-scope function declarations and v8 doesn't like this.

**Comment by caitp** [comment]
actually I spoke too soon, tests fail this too

**Comment by caitp** [comment]
If there are other JS test runs that still need this, please re-open
