### ISSUE TITLE
angular/forms and StrictFunctionTypes in TypeScript

### ISSUE THREAD

**Issue by rkirov** [angular/angular#25824]
@kara and I looked into some real-world errors of users of forms API with TS strictFunctionTypes.

This issue records the current status, recommended workarounds and future direction for improvements.

The core issue is that `ValidatorFn` takes an `AbstractControl`, often people provide validations functions that can only accept a subtype like `FormControl`.

We experimented with some improved typing on the framework side along the lines of this pattern.

```typescript
type ValidatorFn<T=Base> = (c: T) => void;

abstract class Base {
  a = '';
  cl?: ValidatorFn<this>;
  constructor(cl?: ValidatorFn) {
    this.cl = cl;
  }
  setValidator(cl: ValidatorFn<this>) {
    this.cl = cl;
  }
}

class D extends Base  {
  constructor(cl?: ValidatorFn<D>) {
    super(cl as any);  // not good, but needed :(
  }
  b = '';
}

let d = new D((d: D) => {});
d.setValidator((d: D) => {});
```

But ultimately decided it is would not be worth the effort to fix on the frameworks side at this point. The recommended solution is to simply write all validator functions as consuming AbstractControls, and downcast when needed:

```typescript
let validator: ValidatorFn = function(c: AbstractControl) {
  let group = c as FormGroup; 
}
```

or the safer variant 

```typescript
let validator: ValidatorFn = function(c: AbstractControl) {
  if (c instanceof FormGroup) {
    // c is FormGroup here.
  }
}
```

**Comment by thw0rted** [comment]
I just started using `strictFunctionTypes` and I'm getting bitten by this all over.

I guess wrapping each function in a spurious runtime type guard like `if (c instanceof FormGroup)` probably won't have huge performance implications but it does seem like it'd be easy to improve.  The second argument to `new FormGroup(myControls, myValidator)` definitely shouldn't be `(c: AbstractControl) => ValidationErrors | null`, it should be `(c: FormGroup) => ValidationErrors | null`.  The validator is guaranteed to only ever be passed a FormGroup and should be declared as such.  This also holds true for `new FormControl(value, validator)` -- that function will never be passed any implementation of `AbstractControl` other than `FormControl`, right?

**Comment by manueledones** [comment]
I think that ng new --strict published on Angular 10 release note/blog will bring a lot of people (including me) around this issue. 
Enabling strictFunctionType (or strict) I start having errors like the one described here:

_Type '(formGroup: FormGroup) => { ... }' is not assignable to type 'ValidatorFn'_

because I created a ValidatorFn accepting a formGroup (which is a subtype of AbstractControl)

Started reading about what --strictFunctionType flag does, why it even exists ([here is a FAQ](https://github.com/Microsoft/TypeScript/wiki/FAQ#why-are-function-parameters-bivariant).
I think it may be useful some details of the documentation / upgrade notes.

I'll apply the downcast for my custom form validators. Thanks @rkirov

**Comment by thw0rted** [comment]
I think this might be related to #17000, which links to #13721.  Generally speaking all of this would be resolved if it Reactive Forms passed through more generic parameters -- keeping type information about the structure of FormGroups, value-types of FormControls, etc.

**Comment by AndrewKushnir** [comment]
Hi, I'm closing this ticket for now, but leaving a link to the #13721 that talks about strong types for forms, so we can consider doing that as a part of a larger effort. Thank you.
