### ISSUE TITLE
Custom input init value not available OnInit

### ISSUE THREAD

**Issue by piernik** [angular/angular#25836]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
[ ] Other... Please describe:
</code></pre>

## Current behavior
I'm using `ControlValueAccessor` with `ngModel`. When I set initial value of `ngModel` it is not available on `OnInit`.

## Expected behavior
Initial value should be available `OnInit`

## Minimal reproduction of the problem with instructions
https://stackblitz.com/edit/angular-custom-input-init-value?file=src%2Fapp%2Finput-field.component.ts

Please open console to see comments

## What is the motivation / use case for changing the behavior?
When using setters for `Input()` their values are always available `OnInit`. The same should be with `ngModel` and `ControlValueAccessor`

**Comment by kara** [comment]
@piernik This is actually expected behavior, given that template-driven forms are asynchronous. `ngModel` cannot set the value immediately to avoid change detection errors. See the doc for [data flow in template-driven forms](https://angular.io/guide/forms-overview#data-flow-in-template-driven-forms) for more info.
