### ISSUE TITLE
docs: angular/aio/content/guide/

### ISSUE THREAD

**Issue by serhioV** [angular/angular#26052]
## I'm submitting a...

<pre><code>
[x] Documentation issue or request
</code></pre>

## Current behavior
The Internationalization (i18n) [documentation](https://angular.io/guide/i18n) states

> To set your app's locale to another value, use the CLI parameter --configuration with the value of the locale id that you want to use:
> 
> `ng serve --configuration=fr`

probably some prerequisites are needed, cause this gives the following error:
```
>ng serve --configuration=fr
Configuration 'fr' could not be found in project 'MyApp'.
Error: Configuration 'fr' could not be found in project 'MyApp'.
```

## Expected behavior
ng sould start serving the application, using the French locale

## Environment

<pre><code>
Angular version: 6.1.8
Angular CLI version: 6.1.5

Browser:
- [x] Chrome (desktop) version XX
 
For Tooling issues:
- Node version: 8.11.1 
- Platform:  Windows 10

Others:

</code></pre>

**Comment by ocombe** [comment]
@brandonroberts can you take a look at this please?

**Comment by wulfsberg** [comment]
The aio docs strongly makes it sound like `--configuration=...` should just work automagically, but I assume the issue is that you still need to write the actual configuration in `angular.json`, as per https://github.com/angular/angular-cli/wiki/stories-internationalization
This ties in with https://github.com/angular/angular-cli/issues/10612, about the configuration file exploding almost exponentially as you need to mix all options.
