### ISSUE TITLE
Not work spread when I set options to HttpClient.get after migrate to v.6

### ISSUE THREAD

**Issue by AstRonin** [angular/angular#26069]
## I'm submitting a...
<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x ] Bug report 
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
[ ] Other... Please describe:
</code></pre>

## Current behavior

I call my base function:
```
protected get(url: string, options?: any): Observable<HttpResponse<any>> {
    return this.http.get(url, {...options, observe: 'response'});
}
```
When **http** is HttpClient.
I get error:
>  Type 'Observable\<ArrayBuffer\>' is not assignable to type 'Observable\<HttpResponse\<any\>\>'.

I try change call of function, added **\<any\>**:
```
this.http.get<any>(url, {...options, observe: 'response'})
```
And get error:
> Type 'Observable\<HttpEvent\<any\>\>' is not assignable to type 'Observable\<HttpResponse\<any\>\>'.

## Expected behavior

But, if I remove options and spread:
`this.http.get(url, {observe: 'response'})`
It works as expected and in v.5 and latter...

## Environment

<pre><code>
Angular version: 6.1.8

Browser:
- [x] Chrome (desktop) version last
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: 8.11.1
- Platform:  Windows

**Comment by VeldMuijz** [comment]
Did you try setting the ReponseType to `'json'`?

**Comment by AstRonin** [comment]
yes, I tried with ReponseType and without Observe, behaviour is the same...

**Comment by VeldMuijz** [comment]
To confirm, you tried it like so:
`protected get(url: string, options?: any): Observable<HttpResponse<any>> {

    return this.http.get(url, {options: {observe: 'response', responseType: 'json'} });

}`

Because depending on what options you set the HttpClient returns different objects. The above snippet should return a `HttpResponse<any>`.

See the overloads of get here:
[Angular HttpClient.get() docs](https://angular.io/api/common/http/HttpClient#get)

**Comment by AstRonin** [comment]
Please look to my block **Expected behavior** in description of issue.
I wrote, without **spread** all works fine.
But, I need use **spread**. But, I do not why, this behavior failed after update to angular 6 with other connected libraries.

**Comment by alxhub** [comment]
This is some strange behavior, for sure!!

What's actually happening is that because your `options` object has type `any`, then the result of the spread operation `{...options, observe: 'response'}` actually has type `any` as well. `any` is pretty infectious in TypeScript. This means that TS will just take the first signature of `get` (because `any` matches anything!) which happens to return an `Observable<ArrayBuffer>`.

What you should do is type the `options` parameter to your function more aggressively - I always try to avoid `any` where possible in my TS code. If you give this parameter a correct type, your spread operation will work as expected.
