### ISSUE TITLE
Currency pipe not working for Singapore dollar, Brunei dollar

### ISSUE THREAD

**Issue by dhanarajp** [angular/angular#26131]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
[ ] Other... Please describe:
</code></pre>

## Current behavior
Unable to get symbol for Singapore dollar, Brunei dollar in our project using currency pipe
`{{ '1000' | currency:'SGD' : 'symbol' }}` is rendered as 'SGD1000'
`{{ '1000' | currency:'BND' : 'symbol' }}` is rendered as 'BND1000'

## Expected behavior

we were expecting 
`{{ '1000' | currency:'SGD' : 'symbol' }}` to be rendered as 'S$1000'
`{{ '1000' | currency:'BND' : 'symbol' }}` to be rendered as 'B$1000'

when we use 'symbol-narrow', we're getting only '$'.

## Environment

<pre><code>
Angular version:  6.1.0
Angular CLI: 6.1.5

Browser:
- [x] Chrome (desktop) version XX
- [x] Chrome (Android) version XX
- [x] Chrome (iOS) version XX
- [x] Firefox version XX
- [x] Safari (desktop) version XX
- [x] Safari (iOS) version XX
- [x] IE version XX
- [x] Edge version XX
 
For Tooling issues:
- Node version:8.10.0
- Platform:  OS: win32 x64

Others:

</code></pre>

**Comment by manklu** [comment]
@dhanarajp

What locale do you use?

**Comment by saif003** [comment]
i am also experiencing the same behavior. I haven't changed any locale info, so I figure its the default "en-us".

**Comment by manklu** [comment]
@saif003 According to the CLDR data version 34 the symbols for Brunei dollar are BND and $ and for Singapore dollar they are SGD and $.

http://st.unicode.org/cldr-apps/v#/en/C_SEAsia/

**Comment by ocombe** [comment]
Yes, the Singapore dollar is listed as "BND" for the symbol and "$" for the symbol narrow. I agree that the narrow symbol for that currency when the locale is en-US should probably be "S$" to avoid any confusion.

But the rules definitely depend on the locale, if you change the locale to french, the symbol becomes "$BN" for example.

But because Angular uses [CLDR](http://cldr.unicode.org/) data for all i18n values, if you believe that this is a mistake, please open an issue on the CLDR repository: http://cldr.unicode.org/index/bug-reports

Thanks!
