### ISSUE TITLE
Unwanted tooltip with duplicated information hiding the sample source code

### ISSUE THREAD

**Issue by siva636** [angular/angular#26174]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Performance issue
[ ] Feature request
[x ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
[ ] Other... Please describe:
</code></pre>

## Current behavior

When hover over the sample source code in any documentation article, an unwanted tooltip with duplicated information hiding the sample source code. The same information in the tooltip is already in the title of the source code pane.
See the image bellow:

#
![image](https://user-images.githubusercontent.com/3191656/46240139-c7eaef80-c3c0-11e8-9dd7-b7eaae12faf7.png)

# Expected behavior

The tooltip should not show up, or if it shows up, it should have non duplicate useful information.

## Minimal reproduction of the problem with instructions

Just hover over the sample source code in any documentation article.

## What is the motivation / use case for changing the behavior?

To improve the UX.

## Environment

<pre><code>
Angular version: X.Y.Z

Browser:
- [ x] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ x] Firefox version XX
- [ ] Safari (desktop) version XX
- [x ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: v8.11.4  
- Platform:  
Mac

Others:

</code></pre>

**Comment by gkalpak** [comment]
Good point! This is an unwanted side effect of the fact that the [code-example][1] and [code-pane][2] elements as well as the [@example] dgeni tag-def expect the example's header to be defined via the `title` attribute (which has a special meaning in browsers).

##
The proper solution would be to change the `title` attribute to something else (e.g. `header`), but that might affect many files through-out the code base (I haven't actually checked how many examples use titles).

A less intrusive alternative would be to have the components remove the `title` attribute from the host element once they read the value (which should be fine because the title cannot change dynamically anyway).

[1]: https://github.com/angular/angular/blob/2ad1bb4eb905b7d4982e6f82eb17da8d860a67e2/aio/src/app/custom-elements/code/code-example.component.ts#L43-L51
[2]: https://github.com/angular/angular/blob/2ad1bb4eb905b7d4982e6f82eb17da8d860a67e2/aio/src/app/custom-elements/code/code-tabs.component.ts#L80
[3]: https://github.com/angular/angular/blob/2ad1bb4eb905b7d4982e6f82eb17da8d860a67e2/aio/tools/transforms/examples-package/inline-tag-defs/example.js#L27

**Comment by gkalpak** [comment]
@siva636, is this something you would be interested to work on?
