### ISSUE TITLE
MatAutocompleteTrigger method openPanel() not opening the panel. Angular 6, Material Design v6.4.7

### ISSUE THREAD

**Issue by rishilongia** [angular/angular#26378]
## I'm submitting a ...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
[ ] Other... Please describe:
</code></pre>

## Current behavior
Using Angular 6, Material Design V6.4.7, the MatAutocompleteTrigger under AutoComplete has a method called openPanel() which is suppose to open the suggestion panel. But its not. 

## Minimal reproduction of the problem with instructions
here is the link to stackblitz, please check the html file under the app folder, there is a button, when clicked, should open the panel.
https://stackblitz.com/edit/angular-rjebzg

## Environment

<pre><code>
Angular version: 6.1.0

Browser:
- [x] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: 8.11.1

**Comment by alexzuza** [comment]
This issue is not suitable for this repository. Please open this issue on https://github.com/angular/material2/issues
Or use stackoverflow for such kind of questions. 
https://stackoverflow.com/questions/46426748/how-to-use-the-mdautocomplete-openpanel-method

Here's your forked example https://stackblitz.com/edit/angular-rjebzg-nprmc7?file=app/autocomplete-overview-example.html

**Comment by pkozlowski-opensource** [comment]
Thnx @alexzuza
