### ISSUE TITLE
router navigation not triggered on history.back()

### ISSUE THREAD

**Issue by rbedemann** [angular/angular#26398]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
[ ] Other... Please describe:
</code></pre>

## Current behavior

Router events on triggering history.back() do not get fired.

## Expected behavior

Router events on triggering history.back() should get fired every time.

## Minimal reproduction of the problem with instructions

https://plnkr.co/edit/xC2TJQDfe14SXcFsRqnL

## What is the motivation / use case for changing the behavior?

Need of proper router events for every location change.

## Environment

<pre><code>
Angular version: 6.1.10

Browser:
- [x] Chrome (desktop) version 69
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [x] Safari (desktop) version 12
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 </code></pre>

**Comment by manklu** [comment]
@rbedemann 
Your problem is that you use the location service which only changes the url but doesn't trigger navigation. 
If you remove `this.currentPath = subPath;` you will see that your navigation doesn't work at all.

Use the router and it works as expected: https://stackblitz.com/edit/angular-wrqbey

**Comment by r4vn** [comment]
@manklu it seems like his issue is not about navigating. as far as i understand it, it is more about how the router reacts to changes from the history.

you're right that when using `router.navigate` it works perfectly fine.

however, i think he doesn't want to navigate on purpose and only wants to manipulate the history, therefore he uses `location.go`. for example he doesn't want to run resolvers.

[i added a `console.log` to his example plunker](https://stackblitz.com/edit/angular-issue-26398?embed=1&file=src/app/page/page.component.ts) in order to easily visualize the router events. and indeed, there are no router events fired when only calling `location.go` once and then going back in the history.

i don't know if this is on purpose, but in my opinion this is also unintended behaviour.

**Comment by manklu** [comment]
>  i think he doesn't want to navigate on purpose and only wants to manipulate the history

I bet he thinks he's still on  page one because nobody told him otherwise.

**Comment by jasonaden** [comment]
In order to implement this behavior, you would need to add some custom code to react to changes such as this. For example, the code in `@angular/router/upgrade` does something similar. In this case it's reacting to AngularJS events: https://github.com/angular/angular/blob/master/packages/router/upgrade/src/upgrade.ts#L73
