### ISSUE TITLE
angular 5 compile multi-page product web

### ISSUE THREAD

**Issue by tonyshare** [angular/angular#26438]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Performance issue
[x ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
[ ] Other... Please describe:
</code></pre>

## Current behavior

 the  angular version of my website is  5.2.11, and i create multi-page angular web site. Every thing is ok in development environment. for example i can access the web page:
http://my.web.site/
http://my.web.site/blog
etc.

When i use the command:
`ng build --prod --build-optimizer
`
compile the web, it runs ok.
and i only can access the url >  http://my.web.site/

i can not access the other url> http://my.web.site/blog
and others like this

## What is the motivation / use case for changing the behavior?

use angular for multi-page website

## Environment
debian
<pre><code>
Angular version: 5.2.11

Browser:
- [] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: 8.11.3  
- Platform:  

Others:

</code></pre>

**Comment by lazarljubenovic** [comment]
You need to configure your server to return `index.html` when you request `my.web.site/blog` -- then Angular's router will pick up the URL from the address bar and use it to deduce which "page" to show to the user via JavaScript. The `blog.html` file doesn't exist on the server, which is why it's not working for you. 

This is, however, intended behavior as it's the case with every single-page application which uses non-hash-based routing strategy.

**Comment by tonyshare** [comment]
thanks for your help, it works .
