### ISSUE TITLE
upgrade-static.umd.js:1614 $digest already in progress (does not check if in progress already)

### ISSUE THREAD

**Issue by ronbnsim** [angular/angular#26542]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
[ ] Other... Please describe:
</code></pre>

## Current behavior
we are using ngUpgrade with ng1.6 and ng6.
while upgrading our communication module we moved from $http to httpClient.
After connection login success we do $state.go to a page. then we get a "$digest already in progress" which was initiated from the "upgrade-static.umd.js"

![image](https://user-images.githubusercontent.com/7254575/47158499-77e2b700-d2f4-11e8-8a0d-e3efedfd3141.png)

## Expected behavior
from my understanding, before calling $rootScope.$digest(); it should check if $rootScope.$$phase exists that way it wont throw the "already in progress" error.

## Minimal reproduction of the problem with instructions
this is a complex ng upgrade with both ng1.6 and ng6 with use of httpClient and ui-router

## What is the motivation / use case for changing the behavior?

while going through upgrades it is impossible to upgrade to httpClient without suffering with this initialization exception.

## Environment

<pre><code>
Angular version: 6.1.0 + 1.6

Browser:
- [x] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: XX  
- Platform:  

Others:

</code></pre>

**Comment by gkalpak** [comment]
Similar issues have been raised before. We are deliberately not checking for `$rootScope.$$phase`, because these errors should never happen if everything is set up correctly (and doing the check might shadow programming errors).

If you can provide a minimal reproduction of the problem (e.g. on StackBlitz), I would be happy to take a look.
You can use one of one these templates as a starting point: [ngUpgrade with UpgradeModule][1], [ngUpgrade with downgradeModule][2]

[1]: https://stackblitz.com/edit/ngupgradestatic-playground
[2]: https://stackblitz.com/edit/ngupgradelite-playground

**Comment by pkozlowski-opensource** [comment]
Closing for now as we haven't heard back with a minimal reproduce scenario
