### ISSUE TITLE
router needs type definitions to accompany router bundle

### ISSUE THREAD

**Issue by IgorMinar** [angular/angular#2659]
https://github.com/borisyankov/DefinitelyTyped/blob/master/angular2/angular2.d.ts doesn't contain any info about router or http services, which makes them hard to use from a bundle.

**Comment by rolandjitsu** [comment]
Besides that, I think that having everything under `angular2/angular2` is not a very good idea because in the components we write some of us import from specific modules (e.g. `import { NgControlName } from 'angular2/forms'`). When we compile our TS files we then get a lot of errors because the module definition `angular2/forms` does not exist.

**Comment by dsebastien** [comment]
Hello,

I agree with @rolandjitsu; It would be nice to have an organization of the modules such as angular2/<component_name> and have that organization be aligned whether for ts typings, jspm, etc; it would be more straightforward.

For the time being, is there a ts typings file somewhere for these? I've currently got a working setup of gulp + jspm + SystemJS + TypeScript + Angular 2 but I'd like to integrate the new router

**Comment by rolandjitsu** [comment]
@dsebastien I have a setup where I just made a custom typings file where I have the definitions I need for the [router](https://github.com/rolandjitsu/ng2-play/blob/master/src/_typings/custom.d.ts#L194) and other things.

**Comment by dsebastien** [comment]
Thanks!

**Comment by jeffbcross** [comment]
@alexeagle is there a script to generate the type definition, or would I just copy the d.ts files for http and router into the DefinitelyTyped bundle?

**Comment by alexeagle** [comment]
the angular2 build system can generate the .d.ts files during docs generation.
I imagine we should have different type definition files for each module in angular2.
I have time to help with it this week.

**Comment by jeffbcross** [comment]
I think the fact that http isn't in the DefinitelyTyped repo is just because the new angular2.d.ts wasn't copied over during our release process. But router is intentionally excluded from the angular2 bundle, so there should be a separate DefinitelyTyped definition for that. 

When Http moves out of angular2 (#2680), it should get its own definitions. 

Opened https://github.com/borisyankov/DefinitelyTyped/pull/4702 to update definitions with Alpha 27

**Comment by jeffbcross** [comment]
@alexeagle is working on updating the DefinitelyTyped definitions as part of #2686, which contains the Http definitions, but not router definitions yet. 

@petebacondarwin I tried tinkering with [createTypeDefinitionFile.js](https://github.com/angular/angular/blob/master/docs/dgeni-package/processors/createTypeDefinitionFile.js) to make it output the `angular-router.d.ts` as well, but couldn't get it to cooperate. Would you mind updating the process to output angular-router.d.ts?\

**Comment by naomiblack** [comment]
@alexeagle is this fixed now...?

**Comment by alexeagle** [comment]
I don't think it has been done.

**Comment by petebacondarwin** [comment]
I will look at this today

**Comment by petebacondarwin** [comment]
I have provided a pr.
