### ISSUE TITLE
AnimationPlayer onStart and onDone events emit only once

### ISSUE THREAD

**Issue by MurhafSousli** [angular/angular#26630]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
[ ] Other... Please describe:
</code></pre>

## Current behavior

AnimationPlayer `onStart` and `onDone` events emit only once, a new player has to be created to get the events to work again

## Expected behavior

AnimationPlayer `onStart` and `onDone` events should work again after the first play

## Minimal reproduction of the problem with instructions

```ts
  this.animationBuilder.build([
      query(
        '.child-element',
        [
          stagger(100, [useAnimation(animation)])
        ]
      )
    ]);
    this.player = builder.create(this.el.nativeElement);
    this.player.onStart(() => {
      console.log('animation onStart');
    });
    this.player.onDone(() => {
      console.log('animation onDone');
    });
```
https://stackblitz.com/edit/angular-bynhgg?file=src/app/app.component.ts

## What is the motivation / use case for changing the behavior?

Be able to reuse the player

## Environment

<pre><code>
Angular version: 7.0.0

Browser:
- [x ] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: 8  
- Platform:  Windows

Others:

</code></pre>

Could be related to #26095

**Comment by crushjz** [comment]
This is really annoying, as it defeats the reusability purpose of the AnimationPlayer. 

Angular 8.0 issue reproduced here: https://stackblitz.com/edit/angular-na3vhi

**Comment by peternixey** [comment]
I've discovered that you can make the same player emit again but you need to register the callback for every single play. 

```ts
this.releasedOver$.subscribe(() => {
  this.animation.play()
  this.animation.onDone(() => this.animation?.reset())
})
```

I'm rolling with this as a solution for the time being but if and when you solve this problem it would be great if it ships with a deprecation warning so that I (/we) don't end up with memory leaks. Thank you!

**Comment by dario-piotrowicz** [comment]
Hello, I have opened an attempt to fix this issue, what I came up with was allowing the callbacks to be called after the animation gets reset

So for example this is the current behavior:
![before](https://user-images.githubusercontent.com/61631103/173671441-efa0e042-391d-438d-b340-f7083106da0d.gif)

Which I updated to this:
![after](https://user-images.githubusercontent.com/61631103/173671482-24f75b2e-fffd-4104-9f59-837c09281d0c.gif)


I could have changed things so that the callbacks would be always called without the need to reset the animation, but that would basically auto-reset the animation after it has completed, which I'd imagine we don't want (and would make the reset function almost noop).

So I think/hope this makes sense and hopefully it can help with the situations described in this thread :slightly_smiling_face: , please let me know what you think :pray:
