### ISSUE TITLE
Current state of Angular New Router

### ISSUE THREAD

**Issue by Alber70g** [angular/angular#2673]
What is the current state of Angular New Router (https://github.com/angular/router) since that repository has been moved to angular/angular.

**Can we still use it for when 1.5 comes out or will it be never available for ng1?**

**Comment by kpko** [comment]
I would really like to know that, too, since this is basically the most important feature for me at the time.

This question has been asked several times in the old router repository but has never been officially answered. Could somebody elaborate a little bit on the state of the router?

**Comment by hannahhoward** [comment]
https://github.com/angular/router/issues/335
https://github.com/angular/router/issues/317

I am a huge huge Angular supporter but there has been a bit of breakdown in transparency on this. The big direction/message at ng-conf as I understood it was "The router is your transition path" and then since then things have gotten progressively more murky and unclear. I went ahead and even added support for the router in A1AtScript, my NG 1.x to 2.x transition library, but now that whole repository seems defunct. There were lots of PR's and contributions early on but since communication essentially stopped there's really no way to help out. I think it would really, really help the Angular team to make some kind of public statement about what's going on with the router, if it's coming to NG 1.x, why things have gotten so unclear, and your commitment to delivering the router as a transition tool (or providing some other transition tool instead). Thanks so so much!

**Comment by mjw56** [comment]
This came up at the Angular U conference last week. Someone asked about it during the keynote, it's at the 49 minute mark of this video https://angularu.com/VideoSession/2015sf/angular-2-roadmap-update

**Comment by Alber70g** [comment]
@IgorMinar Please, give some clarification

**Comment by mhevery** [comment]
We are working on the router here: https://github.com/angular/angular/tree/master/modules/angular2/src/router Sorry about the lack of transparency, it was not intentional. We are trying to figure out how to make upgrade path simple, and so we are moving things around. It will be part of the Angular2. It is hard to predict future, se we don't speculate when it will be ready.  You may be interested in the latest thinking we have on [upgrade path](https://docs.google.com/document/d/1xvBZoFuNq9hsgRhPPZOJC-Z48AHEbIBPlOCBTSD8m0Y/edit#heading=h.xgjl2srtytjt). We are thinking of making the upgrade path even more granular with components in addition to the router.

(Closing, since this is a question rather then a bug we have to track)

**Comment by kenkouot** [comment]
So is it safe to say we will not be getting a standalone router (for the purposes of using future-forward routing in Angular 1.x apps) before 2.0?

Should developers **not** be using new router? (angular/router)

**Comment by duluca** [comment]
@kenkouot Excellent question and the answer to it should be stated here as clearly as possible. Reading the upgrade path document I glean that only one framework can be active at any given time, so expecting the router to perform some kind of magic and be able to route to both ng1 and ng2 components is unrealistic. Furthermore, the angular/router repository hasn't seen a code commit in a long while, and as @mhevery confirms, development of it is undergoing in the angular2 repo. As-is the new router is still a pretty good router and organizing ng1 code in the component way is an overall positive. It'd be nice if the documentation was updated to highlight that the new router is a potential dead end.

**Comment by mhevery** [comment]
Having the code base be part of angular2 and having it be stand alone are two separate independent questions. 

1) router is part of the angular2 repo.
2) It is our intention that the new router be usable in both Angular1 and Angular2.

**Comment by duluca** [comment]
@mhevery You're absolutely right. Thanks for the clarification. And I know realize the readme.md on angular/router was indeed up to date with a clear warning 3 weeks ago, my eyes just failed (refused?) to read it :)
