### ISSUE TITLE
Support the id referance on svg element when in the hash location strategy 

### ISSUE THREAD

**Issue by qingniaotonghua** [angular/angular#26745]
## 
In order to facilitate the development of the separation of the front and end, my project uses a hash location strategy. In a project module, the following bubble diagram effect needs to be implemented: the label is located at the center of the bubble, and when the label is too long, Clipped with his bubble to ensure that the label does not extend beyond the bubble. like this: https://beta.observablehq.com/@mbostock/d3-bubble-chart
I intend to use svg's clip-path property to implement, thus I need to use a form similar to `url (http://abc.com/index.htmlpage//path#id)` to reference the bubble defined earlier, but this reference method is not working in when using hash location strategy because the reference to the clipping path is like this:
`url(http://abc.com/index.html#/page//path#id)`, there are two '#' characters, the browser can't parse normally.
![image](https://user-images.githubusercontent.com/10780785/47496177-a0d0f200-d888-11e8-9516-f87b9c54972a.png)

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Performance issue
[x] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
[ ] Other... Please describe:
</code></pre>

## Current behavior

  the clip path can not work when in the hash location strategy;
## Expected behavior

the clip path can work when in the hash location strategy;

## Environment

<pre><code>
Angular version: 4.4.6

Browser:
- [x] Chrome (desktop) version 69.0.3497.100
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: XX  
- Platform:  

Others:

</code></pre>

**Comment by DaniilVysotskiy** [comment]
bump

**Comment by atscott** [comment]
Closing as I was able to get `clipPath` to work with the `HashLocationStrategy`: https://stackblitz.com/edit/angular-ivy-router-base-5k2k2b?file=src%2Fapp%2Fapp.module.ts

Example taken from https://developer.mozilla.org/en-US/docs/Web/SVG/Element/clipPath

The difference here from what I see in the image is that the example uses `url(#myClip)` rather than the full path but it seems in that image, you should be able to do that as well.

If you still feel there is an issue, please provide further details in a new issue with a reproduction.
