### ISSUE TITLE
paramMap routing documentation typo

### ISSUE THREAD

**Issue by karthick-manoharan** [angular/angular#26831]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Performance issue
[ ] Feature request
[x] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
[ ] Other... Please describe:
</code></pre>

## Current behavior
Following instruction for using `paramMap` from [router documentaion](https://angular.io/guide/router) says

```
Remember: you only get the initial value of the parameter map with this technique. 
Stick with the observable paramMap approach if there's even a chance 
that the router could re-use the component.
```

## Expected behavior

The above statement does not convey the user that, it is always advisable to use `paramMap` even when the component is not reusing the component.  Need to include `not` to convey the expected.

```
Remember: you only get the initial value of the parameter map with this technique.
Stick with the observable paramMap approach if there's even a chance
that the router could not re-use the component.
```

## What is the motivation/use case for changing the behaviour?
Possible typo in documentation.

## Environment

<pre><code>
Angular version: 7.01

**Comment by theodorejb** [comment]
This isn't a typo. It's correct to say that the `paramMap` observable should be used if there's any chance the router could re-use the component.

Changing the wording to "if there's even a chance that the router could not re-use the component" doesn't make sense, since it would contradict the previous two paragraphs in the documentation which state that it's acceptable to use the snapshot if you know for certain that a component "will never, never, ever be re-used."

**Comment by theodorejb** [comment]
It suggests to use the observable approach unless "you know for certain that a HeroDetailComponent instance will never, never, ever be re-used."

Most of the time you don't know this for certain, and thus should use `paramMap`. That's why the documentation says to stick with `paramMap` "if there's even a chance that the router could re-use the component."

But in some cases you know for certain it will never be reused, and can make the code a lot simpler using the snapshot. This is perfectly acceptable - the snapshot exists to be used in situations like this.

**Comment by byronmejia** [comment]
The documentation appears to be correct, and the issue seems to be subjective. I have to agree with @theodorejb .

If you read from [param api](https://angular.io/guide/router#parammap-api) onwards, you will understand that it is advised to use the observable. Nothing to do with using `paramMap` or not.

I would never encourage the use of 'not' in instruction manuals/documentation. As much as programmers love using the `!` operator, we should avoid using negation in English syntax. Using affirmation in documentation will always convey the intentions better.  [An Example](https://www.btb.termiumplus.gc.ca/tpv2guides/guides/wrtps/index-eng.html?lang=eng&lettr=indx_catlog_c&page=9-8PgTLwxx40.html)

**Comment by brandonroberts** [comment]
Closing as won't fix.
