### ISSUE TITLE
Feature request: Can we execute APP_INITIALIZERS before AppModule is injected?

### ISSUE THREAD

**Issue by rmorrise** [angular/angular#26883]
## I'm submitting a...
<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Performance issue
[x] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
[ ] Other... Please describe:
</code></pre>

## Current behavior

1. AppModule is constructed and injected. Any dependencies injected into AppModule are also constructed.
2. APP_INITIALIZER factory is injected and invoked.

## Expected behavior

1. APP_INITIALIZER factory is invoked.
2. AppModule is constructed and injected afterwards. AppModule dependencies are not constructed until the promise returned from APP_INITIALIZER is resolved.

## Minimal reproduction of the problem with instructions

https://github.com/rmorrise/ng-redux-init

## What is the motivation / use case for changing the behavior?

1. APP_INITIALIZER loads JSON config data from the server and overwrites environment.ts: a "build-once, deploy-anywhere" setup.

2. The app is using @angular-redux/store, combined with redux-observable epics. As per the docs, the epic middleware is constructed in the AppModule constructor. When AppModule is constructed, any dependencies used by the epic middleware are also constructed. Some of these dependencies refer to environment.ts in their constructors.

Currently, the middleware dependencies are constructed before the APP_INITIALIZER invocation, which causes the default environment config to be used.

I thought of some possible workarounds, but none of them seem ideal:
- Use a more complex APP_INITIALIZER that explicitly invokes the Angular injector to set up redux after the config is loaded
- Avoid using environment.ts in our services; use a wrapper service that provides the config instead
- Avoid using environment.ts in service constructors; have each service implement a lazy property getter

I am hoping for an implementation that doesn't require us to change how individual service implementations use environment.ts.

Suggestions welcome!

## Environment

<pre><code>
Angular version: 6.0.3

Browser:
- [x] Chrome (desktop) Version 67.0.3396.79 (Official Build) (64-bit)
</code></pre>

**Comment by rmorrise** [comment]
@kara Updated with a simple app to reproduce the issue

**Comment by KlausHans** [comment]
Just stumbled over this. I thought this is a bug. I our case it is not only some environment information that needs to be set in a constructor of a service, but also our logger, that uses this.constructor.name as identifier. The logger depends on the environment that is loaded via APP_INITIALZER.

It wouldn't be an issue if ngOnInit would work in services.

**Comment by trotyl** [comment]
The feature is not viable. 

The injector and the provider carrier (any class with `providers` in its metadata) instance must be created at same time. in the DI system, provider carrier  itself is also an eager provider, meaning you can have:

```typescript
@NgModule({
  providers: [
    { provide: APP_INITIALIZER, useExisting: forwardRef(() => AppModule), multi: true },
  ],
})
export class AppModule {
  constructor() {
    return () => console.log('NgModule as an APP_INITIALIZER')
  }
}
```

This is working today: https://stackblitz.com/edit/angular-yycdgu?file=src%2Fapp%2Fapp.module.ts

Even no one will make `AppModule` an `APP_INITIALIZER` in practice, but please be aware there's a frequently used pattern known as instance sharing (possibly only I call it this name), like:

```typescript
@NgModule({
  providers: [
    { provide: FooService, useExisting: forwardRef(() => AppModule) },
    { provide: BarService, useExisting: forwardRef(() => AppModule) },
  ],
})
export class AppModule implements FooService, BarService {
  //...
}
```

So that `AppModule` being the implementation of `FooService` and `BarService` (the `Service` here doesn't really mean a functional service, likely to be static data source like `XXXConfig`, `XXXConfigurator`).

Of course you can make `FooService` or `BarService` a dependency of your `APP_INITIALIZER` (or they can be your deep dependency you don't even aware of), then `AppModule` must be instantiated.

The only way to fulfill your proposal is **NOT allow any dependency in `APP_INITIALIZER`**, which would break lot of use case today thus unlikely to happen.

For this use case, your should just have [ApplicationInitStatus](https://angular.io/api/core/ApplicationInitStatus) and wait for it:

```typescript
class AppModule {
  constructor(initStatus: ApplicationInitStatus) {
    initStatus.donePromise.then(() => {
      // code runs after APP_INITIALIZER
    })
  }
}
```

**Comment by mhevery** [comment]
Closing as not feasible. It would be very breaking change with limited benefit.
