### ISSUE TITLE
NoAnnotationError when passing Router into top level App constructor

### ISSUE THREAD

**Issue by mjw56** [angular/angular#2689]
Hi,

I am trying to pass router into my top level app component using .27. The code looks something like this:

```js
import {bootstrap, Component, View} from 'angular2/angular2';
import {RouteConfig, RouterOutlet, RouterLink, Router} from 'angular2/router';
import {Home} from './components/home/home';
import {Foo} from './components/foo/foo';

@Component({
  selector:'app'
})
@View({
  directives: [ RouterOutlet, RouterLink ],
  template: `
    <router-outlet></router-outlet>
  `,
})
@RouteConfig([
  { path: '/', component: Home, as: 'home'  },
  { path: '/foo', component: Foo, as: 'foo' }
])
export class App {
  router: Router;

  constructor(router: Router) {
    this.router = router;
  }
}

```

however when I do this I get the following error message:

![image](https://cloud.githubusercontent.com/assets/161528/8294824/095435f6-190d-11e5-8ea4-87caecc3866a.png)

I've passed routerInjectables into my bootstrap. I'm probably doing something wrong. Any help would be appreciated.

**Comment by rolandjitsu** [comment]
If you are compiling this using babel or traceur, you need to use `ComponentAnnotation` instead of `Component`. I've had the same issue at some point. And it applies for all annotations. I usually just `import { ComponentAnnotation as Component } from ...;` and so on. If you use TS, the issue is with a missing annotation, maybe the `RouteConfig`?
