### ISSUE TITLE
append DOM elements into component view

### ISSUE THREAD

**Issue by rolandjitsu** [angular/angular#2693]
I've asked a similar question [before](https://github.com/angular/angular/issues/2491) and I also looked at [#2476](https://github.com/angular/angular/issues/2476), but I still do not get how you append a DOM element into a component view (or a directive).

Say I have the following component:
```js
import { Component, View } from 'angular2/annotations';
import { ViewContainerRef } from 'angular2/core';

import { supportsNativeShadowDOM } from 'common/shadow_dom';
import { IconStore } from 'app/services';

@Component({
	selector: 'icon',
	properties: [
		'src'
	]
})

@View({
	templateUrl: 'app/components/icon/icon.html', // remove once the relative resolve of styles will work properly
	styles: [
		'@import "icon.css";'
	]
})

export class Icon {
	el;
	constructor(private viewContainer: ViewContainerRef, public icon: IconStore) {
		this.el = this.viewContainer.element.domElement;
	}
	set src(src: string) {
		let that: Icon = this;
		let root;
		if (supportsNativeShadowDOM) root = this.el.shadowRoot;
		else root = this.el; 
		this.icon.get(src).then((svg) => {
			root.appendChild(svg);
		});
	}
}
```
This works fine, but is there an API that would allow me to append the DOM element inside the view without me having to check if there is a `shadowRoot` or not?

**Comment by vicb** [comment]
Note that view are cached and if you add an element "manually" it will persist in the cached version. Why not using a component ?

**Comment by rolandjitsu** [comment]
@vicb I use the `IconStore` to get svg icons from some url and then I get the `<svg>` node, after that I have to append it somehow to the DOM. That's the only reason I need to do it that way. Do you have any other suggestions or ways to achieve this?

**Comment by mhevery** [comment]
I think you should get a hold of an element in the view, and then get an element from there. That way you can always append as sibling wether or not there is shadow DOM.

I am closing because we are not planning on doing any work on making this simpler.

**Comment by bestander** [comment]
@vicb could you please point me to a doc or a discussion about what is recommended way to do native DOM manipulation in Angular 2?  
  
I understand that it would work fine when using templates and bindings of Angular but sometimes people want to integrate with thirdparty libraries like D3 or a jquery plugin.

What I learned is that `@Component`s are cached and whatever I append manually in `element.nativeElement` I must undo in `onDestroy` callback.
A few questions:  

1. Is it (will it be) allowed to inject `private element: ElementRef` in a `@Component` constructor, then add a DIV to it during the lifecycle and then clear it in `onDestroy`? 
2. Should I better use `@Directive` for managing DOM manually?  
3. Which way is more preferable if there is any difference:  
```
    private element;
    constructor(private viewContainer: ViewContainerRef) {
        this.element = viewContainer.element;
    }
```
or
```
   constructor(private element: ElementRef) {
    }
```

I understand you are very busy and if this has been asked before I would appreciate a link to where I could find it out.
Thank you.

**Comment by mburger81** [comment]
@bestander did you found a solution, or a best practice for this?
I need to copy my element and paste it into the dom. But i found nothing about that until now. Can you help me?

**Comment by bestander** [comment]
No, sorry, completely forgot what I ended up with 8 months ago.
Eventually I did get access to the element somehow.
Maybe asking on StackOverflow?
I learned that GitHub issues is really not optimal for questions and discussions like that hence I did not receive an answer here

**Comment by mburger81** [comment]
But you resolved it right?



2016-03-29 18:24 GMT+02:00 Konstantin Raev <notifications@github.com>:

**Comment by bestander** [comment]
some hacky way, yeah

**Comment by bwells78** [comment]
I'm curious about your hacky way (or the best way if someone can help us)... I am building an app that needs to host legacy content driven by jQuery UI widgets.  

On first load of a legacy page, the widget loads correctly and inserts all its needed DOM elements.  If I then switch to another page (route change) and then go back, I want for the previously loaded DOM to return (its state to be persisted).  But all the markup is gone since I'm intentionally preventing a full re-init of the jquery widget.  

Definitely a collision of philosophies between Angular and jQuery and I'm still learning Angular's approach, but hoping there is a way to pull this off efficiently-

**Comment by zoechi** [comment]
@bwells78 have you tried [CanReuse](https://angular.io/docs/ts/latest/api/router/CanReuse-interface.html) not sure if this helps in your case though.

**Comment by bwells78** [comment]
@zoechi Thank you, I'll sleep better tonight. From the doc that looks like exactly what I'm looking for.  Looking forward to giving it a shot tomorrow-

**Comment by zoechi** [comment]
@bwells78 [this issue](https://github.com/angular/angular/issues/7784) contains lots of details about `CanReuse`

**Comment by bwells78** [comment]
@zoechi As it turns out, routerCanReuse is only invoked if the next route's component is the same as the current.  If the next route is a different component, the CanReuse check doesn't take place. 

Here's what I'm hoping to accomplish:

1. User navigates to /book and BookListPanelComponent is initialized. This is a legacy panel that requires invoking the BookListPanel jQuery UI widget.  This is done and the DOM within BookListPanelComponent is built up with jQuery.  This works.

2. User navigates to /contacts and ContactListPanelComponent is initialized.  Same story for legacy component and jQuery UI widget takes care of build up DOM.  This works.

3. User navigates back to /book.  This does not work.  The previously loaded DOM has been lost and I'd need to re-init the widget to get it back... but I don't want to.  I want state to be persisted.

CanReuse doesn't seem to be an option for me here because I'm switching between two different routed components.  

I tried changing my approach to use a common LegacyPanelComponent that takes a route param to indicate which widget should drive it... but in this scenario, I actually _don't_ wan't to reuse because that will prevent support more than one legacy widget.

I'm wondering if I need to treat the generated DOM like data that should be persisted via singleton service.  But that seems messy.  Honestly, having to support jQuery widgets in an Angular app _is_ messy, but that's my requirement.  Appreciate any guidance-
