### ISSUE TITLE
[Documentation Error] Routing & Navigation - Milestone 5. Route Guards

### ISSUE THREAD

**Issue by matronator** [angular/angular#26962]
# 📚 Docs or angular.io bug report

### Description

Right before the start of the next part of Milestone 5, there's this paragraph:

> Register a /login route in the auth/auth-routing.module.ts. In app.module.ts, import and add the AuthModule to the AppModule imports.

However, following the Route Guards Milestone from the start, there is absolutely no mention nor steps creating/talking about AuthRoutingModule (auth/auth-routing.module.ts).

### What's the affected URL?**

https://angular.io/guide/router#canactivate-requiring-authentication

### Expected vs Actual Behavior**

Could it be that the module at the end was just accidentally miss-named, but is the same as the one actually appearing throughout the chapter? Maybe instead of the original:

> Register a /login route in the auth/auth-routing.module.ts. In app.module.ts, import and add the AuthModule to the AppModule imports.

It should have been this:

> Register a /login route in the **admin/admin-routing.module.ts**. In app.module.ts, import and add the AuthModule to the AppModule imports.

## 📷Screenshot
<img width="1279" alt="confused" src="https://user-images.githubusercontent.com/5470780/48087088-af12fc80-e1fe-11e8-9eaf-a515ac3ffb79.png">

**Comment by jinbeomhong** [comment]
No, it's not miss-named. In the [live example](https://angular.io/generated/live-examples/router/stackblitz.html), you could see there are two modules(admin, auth).

But, the document associated with routing, are messed terribly. Especially, most of intermediate code snippets are wrong, out of order, and show the future one(final code).

**Comment by kapunahelewong** [comment]
Thanks for all the helpful info, @matronator. (I love screenshots. 🏆) We are currently working on refactoring that router tutorial And will fix this when we redo the route guards part.

@srcdes, thanks so much for your insight. If you have more ideas you would like to share, I'd love to hear them. I'm linking to this issue from the docs team work item so that we can refer to it as we consider the new structure. So you know, we are working on a re-factor of the all of documentation that entails a number of the points that you have made. So we agree and are definitely trying to implement these changes. Please also feel free to comment on any of the docs team PRs since your thoughts are really important (that's an open invitation to everyone!).

Status: Docs team router tutorial Jira:  [DOCS-879](https://angular-team.atlassian.net/browse/DOCS-879)

**Comment by atscott** [comment]
Relates somewhat to #17794. The milestones don't have clear boundaries and fixing that would help bring problems like this to the surface with a more straightforward way to fix them.

**Comment by JeanMeche** [comment]
The related docs has changed, the issue is no longer relevant.
