### ISSUE TITLE
fullTemplateTypeCheck doesn't work

### ISSUE THREAD

**Issue by user753** [angular/angular#26977]
### Description

I created a new project with `ng new`
I added 
```
  "angularCompilerOptions": {
    "fullTemplateTypeCheck": true
  }
```
in `tsconfig.json`
and 
```{{foo.bar}}```
in
```app.component.html```

```ng build --aot``` shows the error
```
ERROR in app/app.component.html(1,68): : Property 'foo' does not exist on type 'AppComponent'.
```
but
```ng build``` doesn't show any errors

**Angular Version:**
<pre><code>
Angular CLI: 7.0.4
Node: 8.9.3
OS: linux x64
Angular: 7.0.2
... animations, common, compiler, compiler-cli, core, forms
... http, language-service, platform-browser
... platform-browser-dynamic, router

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.10.4
@angular-devkit/build-angular     0.10.4
@angular-devkit/build-optimizer   0.10.4
@angular-devkit/build-webpack     0.10.4
@angular-devkit/core              7.0.4
@angular-devkit/schematics        7.0.4
@angular/cli                      7.0.4
@ngtools/webpack                  7.0.4
@schematics/angular               7.0.4
@schematics/update                0.10.4
rxjs                              6.3.3
typescript                        3.1.6
webpack                           4.19.1

</code></pre>

**Comment by dawidgarus** [comment]
That's how it works. Template typcheck is a feature of AOT compilation: https://angular.io/guide/aot-compiler#fulltemplatetypecheck

**Comment by user753** [comment]
@dawidgarus but with AOT the error occur even without `fullTemplateTypeCheck`. 
Is there any way to enable it for JIT?

**Comment by dawidgarus** [comment]
@user753 Some errors are checked with AOT anyaway because you get it for free. With **full**TemplateTypeCheck it's just more throughout. It's not possible with JIT, because templates are compiled in browser after your code gets compiled from TS to JS, so there are no types to check against. Also there would be no point of JIT compilation if it were doing all the same thing as AOT only in browser and you had to wait for project to compile every time you reload page.
