### ISSUE TITLE
new HttpParams doesn't encode equal sign

### ISSUE THREAD

**Issue by MattTreichelYeah** [angular/angular#26979]
# 🐞 bug report

### Affected Package

 The issue is caused by package @angular/common/http

### Is this a regression?

 I assume not.

### Description

 

An `HttpParams` object created with `fromObject` encodes its properties, including pre-encoded characters, but doesn't encode `=`.

## 🔬 Minimal Reproduction

```    
    let params = new HttpParams({fromObject: {
        param1: 'app=excess'
    }});
```
`param1` stays `app=excess`.

```    
    let params = new HttpParams({fromObject: {
        param1: 'app%3Dexcess'
    }});
```
`param1` becomes `app%253Dexcess`

## 🌍  Your Environment

**Angular Version:**
<pre><code>Angular CLI: 6.2.2
Node: 11.0.0
OS: darwin x64
Angular: 6.1.4
... animations, common, compiler, compiler-cli, core, forms
... http, language-service, platform-browser
... platform-browser-dynamic, router

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.7.5
@angular-devkit/build-angular     0.7.5
@angular-devkit/build-optimizer   0.7.5
@angular-devkit/build-webpack     0.7.5
@angular-devkit/core              0.7.5
@angular-devkit/schematics        0.8.2
@angular/cli                      6.2.2
@ngtools/webpack                  6.1.5
@schematics/angular               0.8.2
@schematics/update                0.8.2
rxjs                              6.2.2
typescript                        2.7.2
webpack                           4.9.2
</code></pre>

**Comment by ChrisDahmCS** [comment]
@kara 

I don't believe the Angular libs are expecting an encoded URI to be passed in. Part of the docs suggest it serializes the body to an encoded string (via the toString method, [read more here](https://github.com/angular/angular/blob/master/packages/common/http/src/params.ts#L174)).

If you have to have the encoded value already, a solution would be to wrap your param value in the decodeURIComponent method:
`
const params = new HttpParams({
	fromObject: {
		param1: decodeURIComponent('app%3Dexcess')
	},
});
`

Alternatively, you can pass in your own encoder:
`
const params = new HttpParams({
	fromObject: {
		param1: decodeURIComponent('app%3Dexcess')
	},
	encoder: {
		encodeKey(key: string): string {
			//your custom encoding here
		},
		encodeValue(value: string): string {
			//your custom encoding here
		},
		decodeKey(key: string): string {
			//your custom decoding here
		},
		decodeValue(value: string): string {
			//your custom decoding here
		}
	} as HttpUrlEncodingCodec
});
`

@IgorMinar - linking you to see if this is considered a bug or if this is the expected functionality, and if the proposed resolutions are acceptable.

**Comment by MattTreichelYeah** [comment]
Using `decodeURIComponent` is functionally equivalent to my first example, is it not? Just putting in the equal sign as is. 

I didn't think an equal sign was a valid character in a query parameter value because it's used already to separate the key and value, but maybe it's fine. Chrome dev tools seems to parse it.

Appears inconsistent to encode `%` and block you from encoding it yourself, but not encode certain things like `=`. But if it doesn't _need_ to be encoded, I _guess_ that's fine.

**Comment by ChrisDahmCS** [comment]
Yes, that'll end up being the same as the first example after it decodes. I think it ends up being valid as an encoded string because the query params themselves use = not the %3D correct? So `https://my.example.request?test=zzz%3Dzzz` where `test` would be `zzz=zzz` when decoded?

Maybe the stranger question is something along the lines of "what if my string is %3D and that does not mean the = sign?" In this case, angular would correctly encode that so it's not converted back to = erroneously. I can understand in your case it can be frustrating though, can I ask why you have to use possibly already encoded parameters?

**Comment by MattTreichelYeah** [comment]
I'm not sure if you fully understand my issue or not. I'm saying this method of creating the HttpParams allows me to have a URL like `https://my.example.request?test=zzz=zzz` in my first case, which seems invalid (but maybe it is).

My reaction to seeing that led me to try my second example, which just muddles it further. I'm then stuck with doing it the first way. Which is fine if it's valid, it just doesn't look valid.

**Comment by ChrisDahmCS** [comment]
Oh, ok I was thinking this was way stranger than it actually is. Yeah even though that does look strange, it's valid.

Back to the angular conversation, I am on board with where you are now (thanks for the patience). 

Per [the docs](https://github.com/angular/angular/blob/master/packages/common/http/src/params.ts#L24-L29), it's suggested the HttpUrlEncodingCodec is using just encodeURIComponent. However, the actual implementation removes most of the added encoding from encodeURIComponent [as seen here](https://github.com/angular/angular/blob/master/packages/common/http/src/params.ts#L57-L68). 

Does anyone know why the standardEncoding method reverts most encoding from encodeURIComponent that is added on top of encodeURI? It's keeping # and & encoded, but nothing else added by encodeURIComponent. Is this because these are the only things actually required to be encoded to not make the param values invalid (& because of param parsing, and # because of ID scrolling or potential hash location strategy)?

There may be better references: [encodeURI](https://www.w3schools.com/jsref/jsref_encodeURI.asp) and [encodeURIComponent](https://www.w3schools.com/jsref/jsref_encodeURIComponent.asp).

This may be splitting hairs, but I'm wondering more about having two replaces on top of encodeURI instead of 9 on top of encodeURIComponent-

```
encodeURIComponent(",/?:@&=+$#")
      .replace(/%40/gi, '@')
      .replace(/%3A/gi, ':')
      .replace(/%24/gi, '$')
      .replace(/%2C/gi, ',')
      .replace(/%3B/gi, ';')
      .replace(/%2B/gi, '+')
      .replace(/%3D/gi, '=')
      .replace(/%3F/gi, '?')
      .replace(/%2F/gi, '/')
```

becomes 

`",/?:@%26=+$%23"`

```
encodeURI(",/?:@&=+$#")
      .replace(/&/gi, '%26')
      .replace(/#/gi, '%23')
```
becomes
`",/?:@%26=+$%23"`

**Comment by alxhub** [comment]
This is working as intended - our encoder does not encode `=` by design. Also, there is no way for the encoder to know if a `%` escaped sequence is a pre-encoded character or the literal character `%` followed by numbers - in general encoders don't usually support recognizing whether something is already escaped or not.

**Comment by albyrock87** [comment]
@alxhub can you explain this "by desgin"? What's the idea behind this design?

How can it by "by design" to make it _impossible_ to encode special characters ( `@ : $ , ; + = ? /` )?

Of course it is possible to provide a different encoder that uses only the standard `encodeURIComponent`, but why that is not the default implementation?

Thanks

**Comment by hugodes** [comment]
@alxhub 

> This is working as intended - our encoder does not encode `=` by design. 

What do you mean ?
