### ISSUE TITLE
Missings informations about Angular Elements

### ISSUE THREAD

**Issue by Korigoth** [angular/angular#26981]
# 📚 Docs or angular.io bug report

### Description

I think the AngularElements documentation is not well explained and the example is stuck in an Angular environment... Where i think the most usefull case for AngularElements is for people "outside" of angular...   (Jquery app, React, VueJS, Plain HTML/JS)..

I doesn't understand why we would want to use AngularElements in an Angular app....
It need more polyfills instead of using directly Angular...

I was so happy to find the Popup Service example but then... i find it is in Angular... nothing usefull in the demo...

### Expected vs Actual Behavior**

Expected:
First, we need more informations about:

- what is currently doable with AngularElements. (everything that is possible... plz...)
- what is not possible to do with AngularElements. ( and why if possible)
- what is on the road map or in the futur vision of AngularElements. (is it complete and nothing more is going to be added ?)

An example like the Popup Service used in a  plain HTML/JS-Jquery world...

You should add real usecase to the demo, (not inside angular)

Explain what is possible to do with Directive, Pipe, Service for external user.
I mean by this, used by end-user of your angular-elements lib (not inside AngularElements).

### Anything else relevant?

We created a very big library for Angular and our main concern is about that we have a lot of system that cannot migrate to be in angular... We want to build a lib that we can import everywhere without building it from scratch with angular... So we have all our applications behave the same in the organisation.

AngularElements is the way to go actually but it seem's to be missing a lot of informations.
Trying to find anything on Google, is a mess.... we cant find any usefulll information because it collide with AngularJS, Angular and nothing about AngularElements directly.

**Comment by elepner** [comment]
Wanted to report the same issue, but fortunately the author did it for me.
I want to add that it's really hard to start using elements capability of angular because one has to gather information piece by piece from different parts of the internet. 
Current examples work only in simple scenarios but fail due to the bug #24181 which can be fixed only using #26112.
Also there're troubles when loading Angular custom element into Angular app with conflicting zones.
Thanks to @manfredsteyer and his example with widgets. Without his example we would be succeed with elements.
So, in addition to the original post, it would be nice to clarify
1. What if one wants to place many different angular custom elements on the same page. It means that runtime (angular + zonejs) can be loaded once. So we need somehow get rid of them during build time. I looked at ngx-build-plus but didn't manage to make it work.
1. Is it possible to hook into elements loading process and configure services it?

**Comment by elepner** [comment]
@Korigoth,
> You should add real usecase to the demo, (not inside angular)

If you want quite good example with real use case (not just a popup service) you may refer to [this ](https://github.com/manfredsteyer/angular-elements-dashboard) repo. However it suffers from #24181.

**Comment by Korigoth** [comment]
@elepner thanks for your informations.

**Comment by mgechev** [comment]
Although we really wish we could document all possible use cases for Angular, that's impossible. Large strength of Angular is the fantastic community. I'd strongly recommend you look for further reference at community resources by our GDEs and contributors.

I'll close the issue for now, but in case I'm missing anything major which is lacking on angular.io regarding Angular Elements, I'd recommend you to open another one.
