### ISSUE TITLE
@angular/bazel usage requires fetching the whole Angular repo

### ISSUE THREAD

**Issue by jbedard** [angular/angular#27007]
# 🐞 bug report

### Affected Package
`@angular/bazel`

### Is this a regression?
Yes, the previous version in which this bug was not present was: 6.1.x

### Description
In v6 the `@angular/bazel` npm package contained the .bzl files, in v7 they are gone.

## 🔬 Minimal Reproduction
package.json
```
"@angular/bazel": "7",
```

WORKSPACE
```
local_repository(
    name = "angular",
    path = "node_modules/@angular/bazel",
)

load("@angular//:index.bzl", "ng_setup_workspace")
ng_setup_workspace();
```

## 🌍  Your Environment

**Angular Version:**
<pre><code>7.x</code></pre>

**Anything else relevant?**
Is this an incorrect way of consuming `@angular/bazel`? A lot of demos just fetch the full angular git repo, but that makes it a little awkward syncing version numbers across WORKSPACE + package.json etc. Or maybe npm shouldn't be used at all and everything should just be build from source? It's still nice having the `node_modules` there though :/

FYI @filipesilva this is what we were discussing at AC

**Comment by filipesilva** [comment]
@alexeagle can you add some context to this change please?

**Comment by alexeagle** [comment]
Hi @jbedard - this was an intentional breaking change, though I don't think we documented a migration step for it.
Here's our observation: distributing `.bzl` files over npm is broken in the use case where the `WORKSPACE` file calls a repository rule (like `ng_setup_workspace`) and you want Bazel to manage the node_modules. Bazel expects the loaded rules to be available during the loading phase, but it hasn't done the yarn/npm install yet at that point.
So we now do "idiomatic install" which is to say, JavaScript files come from npm using the idiomatic way to install them, and Starlark code `.bzl` comes from `http_archive` rules in the WORKSPACE.
So yes, right now you do have to fetch the Angular repo to get these files.
We should publish an artifact with each Angular release that has just the starklark code, I think.

**Comment by jbedard** [comment]
Yeah I was starting to expect that, especially after switching to bazel managed npm where there's no assumption about `node_modules/@angular/bazel` already existing for a `local_repository` to consume.

Is the `@angular/bazel` npm package used for anything then? Same with `@bazel/typescript`...?

Can probably close this then?

**Comment by kyliau** [comment]
Closing this, since issue has been solved with the introduction of `bazelWorkspaces` in `package.json`. Bazel dependencies no longer have to be built from source.
https://github.com/angular/angular/blob/master/packages/bazel/package.json#L22
