### ISSUE TITLE
Relative route navigation failure after first use of ion-back-button (Ionic v4) with relative route

### ISSUE THREAD

**Issue by TiVoMaker** [angular/angular#27050]
# 🐞 bug report

### Affected Package

 The issue is caused by package @angular/angular

### Is this a regression?

 Unknown

### Description

 See the README in the repository. In summary, angular/packages/router/src/create_url_tree.ts, function replaceSegment, appears to rely on comparing object references when navigating a router outlet to a new URL, when it should be comparing the actual URLs. The Ionic application in the repository reproduces the failure.

## 🔬 Minimal Reproduction

 The problem is reproduced in an Ionic v4 based repository, which is unsupported by either Plunkr or stackblitz. The repository can be found here: https://github.com/TiVoMaker/Angular-Routing-Bug

See the README in the repo.

## 🔥 Exception or Error
<pre><code>

</code></pre>

## 🌍  Your Environment

See the repo for the package.json and angular.json files.

**Angular Version:**
<pre><code>

</code></pre>

**Anything else relevant?**

**Comment by atscott** [comment]
Thanks for reporting this issue. It appears this been fixed in one of the recent releases. Please update to the most recent version to resolve the problem.

If after upgrade the problem still exists in your application please [open a new issue](https://github.com/angular/angular/issues/new/choose) and follow the instructions in the issue template.
