### ISSUE TITLE
Service worker returns a different url value for XHR than Fetch

### ISSUE THREAD

**Issue by esanzgar** [angular/angular#27100]
# 🐞 bug report

### Affected Package
The issue could be caused by package:
* @angular/pwa, or
* @angular/common/http

### Is this a regression?
No tested in previous versions.

### Description
When the service worker request a URL that returns a 30* the response returns different url value if the request is done via XHR or Fetch.

The following piece of code returns different url values if the application runs with a service worker registered (only visible in Chrome):
```
this._http.get('https://httpbin.org/redirect-to?url=https://httpbin.org/get', { observe: 'response' })
    .subscribe(response => console.log(response.url));
```

## 🔬 Minimal Reproduction
Example can be found here:
https://esanzgar.github.io/ng-sw-problem/

## 🔥 Exception or Error
None. It simply inconsistent

## 🌍  Your Environment

**Angular Version:**
<pre><code>
Angular CLI: 7.0.5
Node: 11.1.0
OS: darwin x64
Angular: 7.0.3
... animations, common, compiler, compiler-cli, core, forms
... http, language-service, platform-browser
... platform-browser-dynamic, router, service-worker

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.10.5
@angular-devkit/build-angular     0.10.5
@angular-devkit/build-optimizer   0.10.5
@angular-devkit/build-webpack     0.10.5
@angular-devkit/core              7.0.5
@angular-devkit/schematics        7.0.5
@angular/cli                      7.0.5
@angular/pwa                      0.10.5
@ngtools/webpack                  7.0.5
@schematics/angular               7.0.5
@schematics/update                0.10.5
rxjs                              6.3.3
typescript                        3.1.6
webpack                           4.19.1
</code></pre>

**Anything else relevant?**
This issue is only visible in Chrome (because it uses fetch).

**Comment by gkalpak** [comment]
Thx for reporting this issue.

Interestingly, using `fetch()` from the page works correctly but `XMLHttpRequest` (which is what `HttpClient` is using under the hood) does not: [demo][1]
(Note that StackBlitz uses a SW too.)

**What this is not:**
- This is not an `HttpClient` issue, since the same thing happens with vanilla XHR.
- This is not an `@angular/service-worker` issue, since the same thing happens with StackBlitz's ServiceWorker as well (and I suspect with any other SW that has a `fetch` handler).
- This is not a ServiceWorker issue, since it works fine on Firefox.

**What is this, then?**
- This seems to be a Chrome bug, specific to XHR+`ServiceWorker#fetch()`+redirects.

##
Based on the above, I am going to close this (as it doesn't seem to be related to Angular). I suggest you submit a bug report to the [Chromium project][2] (if one does not already exists - I couldn't find anything, but I only looked superficially).

[1]: https://stackblitz.com/edit/ng-issue-27100?file=src/app/app.component.ts
[2]: https://bugs.chromium.org/p/chromium/issues/list

**Comment by esanzgar** [comment]
You are right it is an issue with Chrome and the service worker functionality `event.respondWith` method.

I filled an [issue](https://bugs.chromium.org/p/chromium/issues/detail?id=907123) with chromium.
