### ISSUE TITLE
Router change interceptor

### ISSUE THREAD

**Issue by eliasjnior** [angular/angular#27186]
# 🚀 feature request

### Description
I'm looking like an HTTP Interceptor, but for Angular routes. I couldn't find anything related, so I think doesn't exists.

I implemented a redirect system in Node that will redirect a list of URLs. But of course that Node can't redirect when it's on Angular.

First I tried to use canActivate/canDeactivate, but for that I needed to set:

```
@NgModule({
  imports: [
    RouterModule.forRoot([
      {
        path: "",
        children: MY_ROUTES,
        canDeactivate: [ RedirectGuard ],
      },
    ],
  ],
  providers: [
    RedirectGuard,
  ],
})
```

This doesn't works because the canActivate/canDeactive isn't triggered always that I navigate. So the second solution would be use HttpInterceptor, but it's only for HTTP, not for route changes.

My third solution would be subscribe to events from Router, but I would like to intercept before route change, not while changing. If i `subscribe` to any event, I will make my method parallel with route loading, and I would like to cancel sometimes.

Last method in my mind is to override the Route, overriding `.navigate` and `[routerLink]`, but this doesn't look a good option.

### Describe the solution you'd like

Some interceptor like HttpInterceptor would be great. A RouterChangeInterceptor :P

### Workaround

My workaround now is using Resolver. I created a function to add a custom Resolver to all routes and call that before setting the routes. It's not the best option I think, but it's working.

**Comment by ChrisDahmCS** [comment]
@eliasjnior it's possible to use both canActivateChild and canDeactivate on the set of child routes depending on what you need for the route. Can you please provide a scenario or two where the canActivateChild/canDeactivate aren't quite what you need, as well as the code for canActivateChild/canDeactivate?

You said this path didn't work because the canActivateChild/canDeactivate isn't triggered always that you need to navigate, can you please expand more on this?

**Comment by eliasjnior** [comment]
@ChrisDahmCS I didn't see that we have `canActivateChild`, I saw only `canActivate` in documentation. 

Anyway, for example, I have a module PageModule that will get from my API `http://example.com/api/v1/post/{id}` when access any page `http://example.com/page/{id}`. If I navigate between multiple ids, will this `canActivateChild` be trigged?

**Comment by ChrisDahmCS** [comment]
@eliasjnior with your example, I believe the canActivateChild guard(s) will be triggered on every child navigation. Going on that, I did this to test:

```
npm i -g @angular/cli@latest
ng new test-project
  ? configure routing ? - y
cd test-project
ng g c first-page
ng g c second-page
ng g g activate-child
```

Modify activate-child.guard.ts -
```
import {Injectable} from '@angular/core';
import {ActivatedRouteSnapshot, RouterStateSnapshot} from '@angular/router';
import {Observable} from 'rxjs';

@Injectable()
export class ActivateChildGuard {
  canActivateChild(route: ActivatedRouteSnapshot, state: RouterStateSnapshot): Observable<boolean>|Promise<boolean>|boolean {
    debugger;
    return true;
  }
}
```

Modify app-routing.module.ts -

```
import {NgModule} from '@angular/core';
import {Routes, RouterModule} from '@angular/router';
import {FirstPageComponent} from './first-page/first-page.component';
import {SecondPageComponent} from './second-page/second-page.component';

const routes: Routes = [
  {
    path: '',
    canActivateChild: [ActivateChildGuard],
    children: [
      {path: 'first', component: FirstPageComponent},
      {path: 'second', component: SecondPageComponent},
    ]
];

@NgModule({
  imports: [RouterModule.forRoot(routes)],
  exports: [RouterModule]
})
export class AppRoutingModule {}
```

Modify app.component.html -
```
<a [routerLink]="'/first'">First Page</a>
<a [routerLink]="'/second'">Second Page</a>
<h1>Above the router outlet</h1>
<router-outlet></router-outlet>
<h1>Below the router outlet</h1>
```

`npm start`

Open debug tools, each time I nav to a child, the canActivateChild was stopped at the debug point for me. Now to be thorough, let's modify this example to test a level deeper in navigation.

Modify first-page.component.ts and second-page.component.ts -
```
<p>
  <a [routerLink]="'/second/1'">Go to 1</a>
  <a [routerLink]="'/second/2'">Go to 2</a>
  <a [routerLink]="'/second/3'">Go to 3</a>
</p>
```

Modify routes in app-routing.module.ts - 
```
  {
    path: '',
    canActivateChild: [ActivateChildGuard],
    children: [
      {path: 'first', component: FirstPageComponent},
      {
        path: 'second',
        canActivateChild: [ActivateChildGuard],
        children: [
          {path: ':id', component: SecondPageComponent},
        ],
      },
    ],
  }
```

`npm start`
Navigating to first triggers that ActivateChildGuard, and navigating to second triggers that ActivateChildGuard twice (because two parts of the router tree are calling it). I found [this](https://blog.angularindepth.com/the-three-pillars-of-angular-routing-angular-router-series-introduction-fb34e4e8758e) a great article for getting more familiar with some of that process.

So, this should give you the freedom to have more guards for different depths of your navigation tree. Does this work for you?

**Comment by jasonaden** [comment]
Thanks for the detailed explanation @ChrisDahmCS! This is great!

Closing this as it appears to be answered here. Please open a new issue if needed
