### ISSUE TITLE
Hello, my binding background-image: URL ({{img}}) in html is useless, but I still use DomSanitizer.

### ISSUE THREAD

**Issue by bestbelief** [angular/angular#27182]
code: 
     html:
             ` <div class="aa" style="background-image: url({{img}})">
                 <h1 class="dd text-white">AA</h1>
            </div>`

    component.ts:

export class SceneComponent implements OnInit {

    public img;

  constructor(public productService: ProductService,
    public sidebarService: SidebarService,
    public _sanitizer: DomSanitizer) {
        // this.img = '../../../assets/images/bg11.jpeg';
        // this.img = this._sanitizer.bypassSecurityTrustUrl('../../../assets/images/bg11.jpeg');
        this.img = this._sanitizer.bypassSecurityTrustStyle('../../../assets/images/bg11.jpeg');
        console.log('img: ' + this.img);
     }

log:

img: SafeValue must use [property]=binding: ../../../assets/images/bg11.jpeg (see http://g.co/ng/security#xss)

Please help me analyze the reason. Thank you.

**Comment by bestbelief** [comment]
<div class="aa" style="background-image: url({{img}})">
<h1 class="dd text-white">智能让生活更简单，更快捷，更放心</h1>
</div>

**Comment by okeefem2** [comment]
It would be very helpful if you provided some more information about your issue. Please see the link below.
https://github.com/angular/angular/blob/master/CONTRIBUTING.md#submit-issue

For the reasoning, I would imagine it is because the `bypassSecurityTrustStyle` function returns  `SafeStyle` object that is now wrapping the value passed to it. In order for Angular to properly parse this (unwrap the value, and tell the built in sanitizer not to run on the value) you need to use the property binding syntax. otherwise you would just be dumping the `SafeStyle` Object directly into your style property.

I am interested in knowing why you need to disable the sanitizer on a static asset? Is this required?

**Comment by bestbelief** [comment]
Thank you. It's not necessary. It's just a test to explain my questions. My code is too cumbersome to explain.

**Comment by okeefem2** [comment]
@bestbelief Okay! Is your question answered? If you do not want to have to use `bypassSecurityTrustStyle` One thing you could also try (If you have not already) is something like 

`
<div class="aa"  [ngStyle]="{ 'background-image': 'url(' + img + ')'}"> <h1 class="dd text-white">AA</h1> </div>
`

Where img is just the path/url to the image without it being wrapped in a `SafeStyle`.

**Comment by mhevery** [comment]
Thanks for reporting this issue. However, you didn't provide sufficient information for us to understand and reproduce the problem. Please check out [our submission guidelines](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-submitting-an-issue) to understand why we can't act on issues that are lacking important information.

If the problem still persists, please file a new issue and ensure you provide all of the required information when filling out the issue template.

**Comment by bestbelief** [comment]
Thank you. My problem has been solved. Thank you again for your help.
