### ISSUE TITLE
Proposal: make use of native dom elements in templates explicit

### ISSUE THREAD

**Issue by tbosch** [angular/angular#2721]
# Update by @mhevery

We should use explicit binding as such,
```
<input #user="element">{{user.value}}
```

## Proposal

Right now, users can write the following:
```
<input #user>{{user.value}}
```

Which will just echo the input value in the text node. Looking at the template, it is not obvious, that the value of `user` is a DOM element.

This issue proposes the following syntax:
```
<input #user>{{user.$native.value}}
```
The value of the variable `user` would then be an `ElementRef` (which would have a getter `$native` to get the actual DOM elements), instead of the DOM element itself.

## Why

Some users want to prevent direct access to the DOM in their templates:

- Users who plan to use WebWorkers in the future, as synchronous reads don't work
- Users that want to prerender on the server (i.e. their app runs on the server and client), as the native elements differ on the server and on the client

For these users, it is important to manually (e.g. in a code review) and automatically check that the template does not reference a DOM element. New users of Angular would also benefit from this explicit usage, as it would reveal a performance problem in the above code (it dirty checks a property on a DOM element, which is slow).

These users still need a way to reference elements via variables (e.g. to query for them or hand them into methods on the component), and would probably expect to get an `ElementRef` as value of the variable (see e.g. #2461). `ElementRef` as value seems like a good idea as all Angular APIs use it as well to reference elements (e.g. the `Renderer`, `ViewManager`, `DynamicComponentLoader`.

/cc @matanlurey 
/cc @mhevery

**Comment by vicb** [comment]
could we change `.$native` to something more explicit ie `.$el` or `$(elementRef)` ?

**Comment by tbosch** [comment]
Sure. I chose the prefix `$` as we already use this for `$event` as well to signify to users that this is a native thing they are interacting with.

Note that this issue is still a proposal and not decided yes.

**Comment by matanlurey** [comment]
What would `user` be, something similar to an `ElementRef`?

**Comment by matanlurey** [comment]
Would `$native` be optional or a required syntax for everyone?

**Comment by tbosch** [comment]
@matanlurey the idea of this issue is to make this required for everyone, so that linters and users can detect direct dom access early.

**Comment by rolandjitsu** [comment]
I personally think that using `<input #user>{{user.value}}` is lot better than `<input #user>{{user.$native.value}}` which just adds up to the things I have to remember.
If the docs clearly specify that the use of `#binding` on an `<input>` (or other tag) bind to the native element and they can access any properties on it, then that should be enough and I think it's more natural to expect the first case rather than the second.

**Comment by mhevery** [comment]
- The syntax should be `<input #user="element">{{user.value}}` not `<input #user>{{user.$native.value}}` since `user` may not have `$native` field if it is an angular component.

- I am a bit on fence on this, but I think we can give this a try, and if we don't like it we can roll back. I don't see a lot of down side to giving it a try and collecting more data.

**Comment by tbosch** [comment]
We are close to final, so let's not do this now.
