### ISSUE TITLE
One time subscription http

### ISSUE THREAD

**Issue by freeintelligence** [angular/angular#27255]
Hi. How's it going.

I'm trying to make a request http get to an endpoint in an api. The problem is that the first connection arrives at the server but in the second (hereafter) it does not connect to the server but responds according to the cache.

It is obvious that it would work like this since this is how the 'observable' system works, then how would it always connect to the api server, regardless of whether the request was already made?

My idea is that only one function returns a promise with the result, not returning the observable.

This does not work (code):

https://pastebin.com/Ggwm1cTC

It's not a cache problem in the browser.

> Angular CLI: 7.0.6
Node: 10.5.0
OS: linux x64
Angular: 7.1.0

**Comment by Airblader** [comment]
Quoting the support request issue template:

> Please do not file questions or support requests on the GitHub issues tracker.
> 
> You can get your questions answered using other communication channels. Please see: 
https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
> 
> Thank you!

**Comment by freeintelligence** [comment]
Did you look at the code? In theory, it should work. I posted it here because it can be a bug.

**Comment by mlc-mlapis** [comment]
@freeintelligence ... there should be something else. It's obvious that there is caching logic on browsers level if you load `*.js` (bundles, ...) files and that's why all bundles generated by CLI have unique names for each build ... but you are talking about XHR requests (GET, POST - by default not cached at all, ...) and when working with them you use standard headers to protect against caching. So what you are looking for?

**Comment by ericmartinezr** [comment]
Considering that the Http module uses XMLHttpRequest, this can help https://developer.mozilla.org/en-US/docs/Web/API/XMLHttpRequest/Using_XMLHttpRequest#Bypassing_the_cache. Now, googling "Cache Busting" can help too.

**Comment by jasonaden** [comment]
Closing based on above.
