### ISSUE TITLE
valueChanges stop work with reactive form after upgrade from angular 7.0.4 to 7.1.0

### ISSUE THREAD

**Issue by ofirrifo** [angular/angular#27287]
# 🐞 bug report

### Affected Package

 The issue is caused by package @angular/....
I think the issue related to package: @angular/forms
the module >> ReactiveFormsModule

### Is this a regression?

Yes it worked in angular 7.0.4 and stop work in angular 7.1.0

### Description
the valueChanges observable stop work when I use the
{ updateOn: 'submit' }
it work when I use angular 7.0.4 but stop after I upgrade to 7.1.0

 A clear and concise description of the problem...

## 🔬 Minimal Reproduction
https://stackblitz.com/edit/angular-cioopj?file=src%2Fapp%2Fapp.component.ts
 https://stackblitz.com/...

## 🌍  Your Environment

**Angular Version:**
<pre><code>

Angular CLI: 7.1.0
Node: 9.7.1
OS: darwin x64
Angular: 7.1.0
... animations, common, compiler, compiler-cli, core, forms
... http, platform-browser, platform-browser-dynamic
... platform-server, router, service-worker

Package                            Version
------------------------------------------------------------
@angular-devkit/architect          0.10.7
@angular-devkit/build-angular      0.10.7
@angular-devkit/build-ng-packagr   0.7.5
@angular-devkit/build-optimizer    0.10.7
@angular-devkit/build-webpack      0.10.7
@angular-devkit/core               0.6.8
@angular-devkit/schematics         7.1.0
@angular/cdk                       7.1.0
@angular/cli                       7.1.0
@angular/language-service          7.1.0
@angular/material                  7.1.0
@ngtools/json-schema               1.1.0
@ngtools/webpack                   7.0.7
@schematics/angular                7.1.0
@schematics/update                 0.11.0
ng-packagr                         4.4.0
rxjs                               6.3.3
typescript                         3.1.6
webpack                            4.19.1

</code></pre>

**Comment by ChrisDahmCS** [comment]
@ofirrifo It seems like your demo is working as the docs indicate it should work- [here is the example](https://github.com/angular/angular/blob/master/packages/forms/src/model.ts#L835-L840) that has pretty much what you are showing. Since there is no submit event going out, this won't update. 

Since this is being set at the group level, all child controls will be defaulted to the same updateOn. If you want a child to have a different updateOn, you can define it separately on the child. When the child's updateOn fires, it will trigger the parent's updateValueAndValidity because the child's updateValueAndValidity is called. [Here is a more in depth explanation](https://github.com/angular/angular/commit/ff5c58be6b843bc8f79613dbefc5e4951c125f3d).

Editing your stackblitz to build the FormControl differently:
`new FormControl('', {updateOn: 'change'})` has the effect where the FormControl changing now updates the FormGroup as well, ultimately updating the text from the interpolation. Will this work for you?

**Comment by kara** [comment]
@ChrisDahmCS Thanks for the investigation / detailed explanation.

@ofirrifo I took a look too and agree with @ChrisDahmCS that this is working as intended.

**Comment by ofirrifo** [comment]
@ChrisDahmCS  
the problem that it works before in angular 7.0.4 and earlier versions.
is this breaking change?

**Comment by kara** [comment]
Testing in both versions, it works the same for me (which is expected, since we haven't made any changes to this functionality in over a year).
