### ISSUE TITLE
question: any reason why styles property in @View is a list?

### ISSUE THREAD

**Issue by PascalPrecht** [angular/angular#2730]
We have a couple of different ways to apply styles to our components in Angular 2. One of them is using the `styles` property of `@View` decorators.

Is there any specific reason why that property has to be a list (as defined here: https://github.com/angular/angular/blob/master/modules/angular2/src/core/annotations_impl/view.ts#L60) ?

I see that I can do things like:

```
styles: ['.zippy { background: green; }']
```
But also
```
styles: [
  '.zippy {background: green; }',
  '.zippy__content { background: white; }'
]
```

The latter feels quite uncomfortable, which is why I would prolly do something like:

```
styles: [`
   .zippy { ... }
   .zippy__content { ... }
`]
```
Any thoughts?

**Comment by gdi2290** [comment]
it's a list so you can compose styles
```es6
styles: [
  require('./flexbox-grid.styl'), // our base styles
  require('./theme.blue.styl'), // our color theme
  require('./zippy.styl')  // developer's custom styles
]
```

we can upgrade this by having defaults using `@BaseView` when that PR is merged

**Comment by PascalPrecht** [comment]
@gdi2290 interesting! You're using `.styl` extensions there. Is there also a preprocessor pipeline in the making?

**Comment by gdi2290** [comment]
@PascalPrecht  oh, no sorry that was Webpack. Personally I don't think it should be the framework's job to handle files so I'm using Webpack's preprocessor pipeline in that example

**Comment by PascalPrecht** [comment]
Alright, that clears things up! Thanks man

**Comment by vicb** [comment]
Actually the main use case for `styles` is to inline all the styles (from the html, styleUrls) during a build step so that we don't have to fetch urls or `@import` at compile time.

Notes:
- using `require()` will not work when transpiling to Dart (which may or may not be a problem for you),
- when we have the build step inline all styles to `styles`, we will probably disable the processing of the the styles there (as they would already have been processed by the build step) - this means that we will not inline `@import` rules nor scope the selector in case of a emulated + scoped strategy.

Conclusion: I'm not sure if using `require()` is safe long-term - there should be no problem if you add css text.
