### ISSUE TITLE
Make it easier to extend / compose directives?

### ISSUE THREAD

**Issue by billccn** [angular/angular#2732]
In Angular 1, it was quite difficult to reuse functionality provided by other directives. All the ways composition are either slightly inefficient (e.g. string template compilation cost) or cumbersome (hacking compile and link functions to invoke another directive). Facilities for extensions are almost nonexistent.

Can Angular 2 improve on this by:

1. Making it easier to invoke another directive programmatically (including the ability to pass arguments).
2. Introducing some more structure into directive classes (e.g. force directives to break their functionality into standard methods calls that match interfaces), so it is practical to extend directives.
3. Making it possible to extend directive meta-data
4. Designing the built-in directives to be more extensible and compose-able as an example to third-party developers
5. Provide better documentation and guidelines that encourage code-reuse

(Arguably, I am asking for the React templating approach to be implemented in Angular, but I believe this makes better use of the object-oriented paradigm and greatly improves maintainability. The Angular 1 directives really looks like those write-only C code from the previous century.)

See also: [Whether to abstract small repeating code segments in HTML templates?](http://programmers.stackexchange.com/q/280249/44660)

**Comment by bgourlie** [comment]
Composition is and has always been pretty easy.  Extending, not so much, and I would go as far as to say it's an anti-pattern in angular.

**Comment by billccn** [comment]
Composition is only easy for directives that can be used as "elements". For the ones that have to be used as attributes, the options are sometimes limited. For example, say I want to create a directive to add `ng-disabled` to `<input>` elements with a certain CSS class, I cannot use a template to achieve this and must hack this in through the `compile` function. (Wrapping the `<input>` is also not practical as I would have to pass all the attributes in.)

For the extending part, could you please elaborate why is it an anti-pattern? For me, it should be one of the basic features of software frameworks (especially in the OO world).

**Comment by bgourlie** [comment]
> For example, say I want to create a directive to add ng-disabled to <input> elements with a certain CSS class

I'm not sure how I'd address your specific example, because creating a directive to add another directive based on it having a particular css class seems unnatural.  I suspect there is a more natural way to accomplish your end goal.

As far as composition with attribute selectors, we do it all the time in angular 1.  It's not uncommon to have `ng-hidden` and `ng-class`, `ng-repeat` or any other number of directives on a single element.

**Comment by mhevery** [comment]
I believe Angular 2 already does all of the above. 

Because these are requests in the land of opinions, rather than measurable yes/no answers, it would be hard for us to clearly say we have done all of the above. This means that this would never get closed. For this reason we are aggressive about closing issues which don't have clear deliverables.
