### ISSUE TITLE
Life cycle - ControlValueAccessor 

### ISSUE THREAD

**Issue by ezhuikova** [angular/angular#27348]
Hi!

if i use ngControl like this:

```
export class AnyComponent implements ControlValueAccessor {
   constructor(@Self() public controlDir: NgControl) {
      controlDir.valueAccessor = this;
  }
}
```
The life cycle looks like this:
**WriteValue
OnInit**

I think this is incorrect behavior. (correctly in my opinion OnInit and then  writeValue) Or am I doing something wrong? Please help me

Thanks

**Comment by okeefem2** [comment]
Hi @ezhuikova! In the future could you please follow the [guidelines for submitting an issue](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#submit-issue)?

It looks like the behavior you are describing is happening because your code is executing in `constructor` and not in `ngOnInit`, the constructor is called [before any of the lifecycle events](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#submit-issue).

**Comment by kara** [comment]
Closing this issue as it does not follow the issue template. Please file a new issue that follows the template, which gives the team the information needed to investigate.
