### ISSUE TITLE
Currency pipe, digits info with either 0 or 2 decimals (but not 1)

### ISSUE THREAD

**Issue by WanderG** [angular/angular#27391]
# 🚀 feature request

### Relevant Package
This feature request is for @angular/common

### Description
In many use cases where showing currency, it looks better to not show any decimals when there aren't any to show. So "€100" instead of "€100.00". However when the price is 99.99 you do want to show the decimals. What you don't want is when the price is 99.90, to have it shown as 99.9.

This means that none of the number formats "1,0", "1.2" or "1.0-2" have the desired effect.

### Describe the solution you'd like
To be able to specify 2 options for decimals, for instance: "1.0|2".

So that:
- `1.0 | currency : 'EUR' : 'symbol' : '1.0|2' ` -> €1
- `1.1 | currency : 'EUR' : 'symbol' : '1.0|2' ` -> €1.10
- `1.11 | currency : 'EUR' : 'symbol' : '1.0|2' ` -> €1.11

**Comment by ocombe** [comment]
Hello, I'm sorry but we will not implement this feature request as it is very specific to your personal preference.
That being said, it's very easy to create your own currency pipe that does what you want.
You can copy the code of the existing currency pipe: https://github.com/angular/angular/blob/master/packages/common/src/pipes/number_pipe.ts#L136-L224 and then change it to post process numbers exactly the way you want.

**Comment by ChrisDahmCS** [comment]
I know this is closed but @WanderG:

Create your own pipe that injects the currency pipe. In your transform, test the value to see if value % 1 > 0. If so, use the currencyPipe's transform with it's regular digitsInfo format (the 1.2-2). If not, pass in your 1.0-0 format.

This feature does not feel like a generic feature because the currencyPipe's transform follows the [ISO 4217 format](https://en.wikipedia.org/wiki/ISO_4217) ([read more here](https://datahub.io/core/currency-codes)) which requires the decimal numbers (or minor units) to be shown.
