### ISSUE TITLE
Angular - Pipes issue

### ISSUE THREAD

**Issue by mwolczyk** [angular/angular#27435]
### Description

In the paragraph "Parameterizing a pipe" in example of the code from "src/app/hero-birthday2.component.ts" you give an example of new Date(1988, 3, 15) while describing the month as April :) 

### What's the affected URL?**
https://angular.io/guide/pipes

### Reproduction Steps**
Go to said above link and see "Parameterizing a pipe" paragraph and the code from src/app/hero-birthday2.component.ts (class).

### Expected vs Actual Behavior**
Change "new Date(1988, 3, 15)" to "new Date(1988, 4, 15)"

## 📷Screenshot
![image](https://user-images.githubusercontent.com/26229172/49401849-a273bc80-f748-11e8-9094-884acf198630.png)

</code></pre>

### Browser info
Newest Chrome (I hope)

### Anything else relevant?
None

**Comment by JoostK** [comment]
Months in JS are 0-based. Yes, it's strange indeed.

Could you submit a PR to perhaps change it to become `new Date(1988, 4 - 1, 15) // April 15, 1988` as you're not the first to fall for this.

**Comment by gkalpak** [comment]
`4 - 1` would be equally puzzling imo. Maybe an explicit comment? (`new Date(1988, 3, 15)  // April 15, 1988  (Note: The month index is 0-based.)`
I am going to cloe this, since it is correct as it is, but feel free to open a PR if you can come up with a way to make this less confusing for unsuspecting victims :smiley:

**Comment by ericmartinezr** [comment]
Probably a link to https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date#Parameters would be enough
