### ISSUE TITLE
Angular Build enhancement

### ISSUE THREAD

**Issue by rojan507** [angular/angular#27455]
# 🚀 feature request

### Relevant Package

Angular Build enhancement 

### Description
 A clear and concise description of the problem or missing capability...
2 Reason for a Angular Build enhancer 

1)One of the main problem in angular development with large teams is that lazy loading is being broken by team members and this can only be found when specifically check the modules in browser lazy loading.
Attached Example shows how lazy loading is broken by bad code practise 
instead of exporting components I have embedded components in multiple packages
2)Also circular dependency is being handled by angular in Runtime.It when you build the project nobody know if the project has circular dependency.when you click on specific link angular  throws error for CD.This is inefficient . It would be better if we could highlight this as warning in Build time

### Describe the solution you'd like
 If you have a solution in mind, please describe it.

If build command can find the above issues it would be great. Attached example shows the 2 scenarios.

[src.zip](https://github.com/angular/angular/files/2643858/src.zip)
<img width="1260" alt="screen shot 2018-11-19 at 13 36 09" src="https://user-images.githubusercontent.com/8436978/49440929-ee604900-f7bc-11e8-8546-7daccd87fac9.png">

### Describe alternatives you've considered
 Have you considered any alternative solutions or workarounds?

**Comment by ChrisDahmCS** [comment]
Hey @rojan507!

These are definitely tricky tasks to overcome, and frustrating! There are a few ways to combat this on projects of all sizes.

First I'm trying to design components/modules/libs similar to how the [Angular Material team created many small libraries](https://github.com/angular/material2/tree/master/src/lib).

Ex: 
```
imports: [ MomentPipeModule, FancyComponentModule, GreenBeerModule ],
```
instead of
```
declarations: [ MomentPipe, FancyHeaderComponent, FancyFooterComponent, FancyBodyComponent, FancyModalComponent, BeerComponent, ColoredBeerComponent, GreenBeerComponent ],
exports: [ MomentPipe, FancyHeaderComponent, FancyFooterComponent, FancyBodyComponent, FancyModalComponent, BeerComponent, ColoredBeerComponent, GreenBeerComponent ],
```

This does become a little less straight forward from typical online examples, but it then moves to you having the ability to create your own packages/libs for smaller pieces/lazy modules. Conflicts are likely to decrease drastically, and (in my opinion) better feature separation practices will exist naturally.

The more difficult step is whomever doing the code reviews (if the group does this) needs to remain vigilant on enforcing these separations. Your team(s) will likely have to discuss how it will work for your process etc. It could be possible to utilize the budgets in the CLI to try and enforce a real max size as well.

The final issue is trying to get the flow of components to be in such a way that nested components aren't causing the circular dependencies. Personally, in most cases I attempt to stick with the container/presenter model (with heavier usage of template and transclusion). The containers have the services, and the presenters only have I/O. If different things need nested inside of presenters, transclude them via `ng-content` instead of nesting them in the presenter's html if possible.

For example, nesting three presenters deep that all connect to the container can look like:
(inside container html)
```
<pres-one [dataForPresOne]="presOneData" (eventForPresOne)="presOneEvent($event)">
    <pres-two (someReaction)="handlePresTwoReaction($event)">
        <pres-three [dataForPresThree]="presThreeData" (presThreeSubmit)="submitted($event)">
        </pres-three>
    </pres-two>
</pres-one>
```

This allows for extremely deep presenter building all from the container alone (less need for presenter html tags inside of other presenter html files). Another option is working with [templates / template outlets](https://blog.angular-university.io/angular-ng-template-ng-container-ngtemplateoutlet/).

--

For issue 2, I agree this gets quite unwieldy for large applications- but does anyone know if the build can see this from lazy loaded modules?

**Comment by rojan507** [comment]
Thanks for adding this to backlog.

**Comment by petebacondarwin** [comment]
Regarding the circular dependencies - there is actually an option in the CLI build job for displaying these:

```
--showCircularDependencies=true\|false
Show circular dependency warnings on builds.Default: true
```

(See https://angular.io/cli/build)

I expect this was added since this issue was created.
