### ISSUE TITLE
Feature: Injectable decorator handling multi-provider tokens

### ISSUE THREAD

**Issue by GavinHohenheim** [angular/angular#27477]
# 🚀 feature request

### Relevant Package
This feature request is for @angular/core

### Description
I would like to use the `@Injectable()` decorator to provide injectables for multi-provider tokens directly, instead of configuring them in a module. 

### Describe the solution you'd like
I assume the result is going to look something like this:
```typescript
@Injectable({
  providedIn: 'multi-token',
  attachedTo: HTTP_INTERCEPTORS,
  attachedAfter: [
    AuthenticationInterceptor,
    AuthorizationInterceptor
  ]
})
export class ErrorInterceptor implements HttpInterceptor {
// ...
```

### Describe alternatives you've considered
The current way works fine, although implementing this would probably help to get people to adopt the fancy, new `@Injectable({providedIn: ...})` syntax faster.

Also, I'm not sure about the `attachedAfter` part. Interceptor sequence ordering matters, but there probably are better solutions to that detail than I am suggesting here.

**Comment by trotyl** [comment]
Not feasible, unless you have direct reference to `ErrorInterceptor`, otherwise it will be tree-shaken and removed from runtime. Any decorator in Angular is pure and won't perform any side-effect.

**Comment by alxhub** [comment]
Unfortunately @trotyl is correct - this isn't really feasible in Angular. The decorator can't patch the multi-provider token in a tree-shakeable way.

**Comment by dwiyatci** [comment]
@trotyl @alxhub I guess I've got the reasoning behind this infeasibility on the "direct reference"/explicit import part, i.e. where the multi-provider injection token is injected/imported, it won't have references to the service classes that make up the token - that's why it cannot be tree-shaken correctly. But I'm sorry I still don't get the relation between "side-effect" and "patch" wordings being used here. When we do:

```typescript
@Injectable({ providedIn: 'root' })
export class XService() {}
```

or

```typescript
@Injectable({ providedIn: SomeModule })
export class XService() {}
```

Doesn't "patch" here mean it does some "side-effect" as well, e.g. by registering the class (`Type`?) as token to `'root'` or `SomeModule`?

**Comment by trotyl** [comment]
@dwiyatci `@Injectable({ providedIn: SomeModule })` only make side effects to `XService`, not `SomeModule`, so that you must manually reference to `XService` to make it work. However, when used for a multi-provider token, the `XService` implementation class will no longer be used directly, making it unavailable.
