### ISSUE TITLE
Are there any plans to have a directive like ng-include?

### ISSUE THREAD

**Issue by peter-svintsitskyi** [angular/angular#2753]
I'm looking for a feature that will allow to have dynamic templates for a component.
For example, I'm loading a text by ajax means and displaying it. Then I also want to attach click event handlers to a certain words using directives.
For example I have a parent component that makes an ajax request to a server and  a server returns the following text in response:
``` 
Foo bar baz <c>foo</c> bar baz
```
I'd like to render that response as an html and have a directive with the selecor "c" that will handle clicks for the word.

**Comment by mhevery** [comment]
`ng-include` will not be added as it has security issues which can not be resolved without breaking its semantics. 

This use case will need to be handled by custom renderer.

**Comment by alexpods** [comment]
@peter-svintsitskyi Look at [this plunker](http://plnkr.co/edit/8mna5McKeq72qH8QlZbi?p=preview). You can render template dynamically by using [DynamicComponentLoader](https://angular.io/docs/js/latest/api/core/DynamicComponentLoader-class.html)

```js
this.laoder.loadIntoLocation(
  toComponent(template, directives), 
  this.elementRef,
  'container'
);

function toComponent(template, directives = []) {
  @Component({ selector: 'fake-component' })
  @View({ template, directives })
  class FakeComponent {}
  
  return FakeComponent;
}
```

@mhevery Could you resolve my doubts: this is correct use of DynamicComponentLoader, or it's a some dirty dirty hack that must never be used?

**Comment by peter-svintsitskyi** [comment]
Yes, I was using the similar approach but without the DynamicComponentLoader. But it looks like the compiled templates are cached somewhere per class. So I came to even more hacky solution :)

```typescript
            // Faking class declaration by creating new instance each time I need.
            var component = new (<Type>Function)();
            var annotations = [
                new Component({
                    selector: "foo"
                }),
                new View({
                    template: text,
                    directives: [WordDirective]
                })
            ];

            // I know this will not work everywhere
            Reflect.defineMetadata("annotations", annotations, component);
    
            // compile the component
            this.compiler.compileInHost(<Type>component).then((protoViewRef: ProtoViewRef) => {
                this.viewContainer.createHostView(protoViewRef);
            });
```

**Comment by drew-moore** [comment]
@alexpods +1, I'm wrestling with a similar use case, taking more or less the same approach and have the same doubts. 

@mhevery - any insights into the "Angular2 way" of doing this would be most appreciated.

**Comment by TBurk83** [comment]
So, something as simple as dynamically setting a URL based on, say, a JSON response from a service, and passing that to @View is not possible? That seems fairly shortsighted and silly to me.

**Comment by zman13** [comment]
Make that @drew-moore +2

**Comment by lupinglade** [comment]
Would like to see ability to select template dynamically as well. It is a very useful feature when all you want to alter is the template, but reuse the component implementation.

**Comment by Gaulomatic** [comment]
Same for me.

**Comment by vishalmanchanda** [comment]
yes please.me too looking for the same.

**Comment by AleRob90** [comment]
+1 here. I wanna create reusable components too. Don't like hacking them and have problems later

**Comment by michalstepien** [comment]
+1

**Comment by prokher** [comment]
+1

**Comment by waeljammal** [comment]
+1 for this, I've resorted to hacks too.

**Comment by piernik** [comment]
Another one +1 - please reopen this issue. It's needed.

**Comment by djarnop** [comment]
+1

**Comment by amcdnl** [comment]
I think everything that is in Angular1 that is not going to be implemented ( such as this ) should have notes in the docs and comparable custom approaches.

**Comment by drew-moore** [comment]
@amcdnl +1

**Comment by chinookproject** [comment]
Having no way of dynamicaly including html (and make it part of the current page Components scope) is really a show stopper for us. Using a `DynamicComponentLoader` is way too strict since you need to specify (hard code) what templates/components you want to include. We really need a true dynamic way, like you could do in Angular 1.

So a +1 from me as well. Really need this functionality...

**Comment by jimitndiaye** [comment]
Trying to figure out a way of using `DynamicComponentLoader` to accomplish the same but it seems to be a non-starter as there doesn't seem to be a way of wiring up inputs and outputs as you can in a template. All you can do is inject the raw component(s) with no configuration.

**Comment by zoechi** [comment]
@jimitndiaye 
You can use a shared service (also shared only between injecting parent and injected child). Also the promise returned from 
```ts
dcl.add...(...).then(component => {
  component.input1 = someValue 
  component.output1.subscribe(...)
  ...
})
```
allows you to pass values and listen to ouputs. 
Just declarative binding isn't supported (yet?)

**Comment by mbcooper** [comment]
+1.   I need a way of letting a "master class" select a template and bind it to a model.  This allows me to have a configurable application.

**Comment by intellix** [comment]
Also using this heavily in NG1. I'm trying to create an Angular-CMS where the frontend developer creates "template definitions" in the database and then provides a template that loops through the data provided to it. The templates would be shared between frontend and CMS so you get a live-preview.

You can see an example of it here (Click `+ New Space` next to Banner): 
http://codepen.io/intellix/full/KpjNrJ

```html
<template-space data="space.data" slug="{{space.template.slug}}"></template-space>
```

I'm trying to expand this further so you create whole pages by add rows/columns and then populating columns with widgets/template-definitions.

Without this I guess I'll have to do something like (of which I imagine isn't possible due to security concerns either):

```html
<template-{{space.template.slug}}></template-{{space.template.slug}}>
```

**Comment by jbenezech** [comment]
+1

**Comment by intellix** [comment]
I've played around with the DynamicComponentLoader, and to be able to load in a component I need to pass in the Class Type as the first argument, which means I can't pass it in dynamically as a string from the database. To hack/get around this for now I'm doing this:

```
import {Button} from '../button/button';
import {Thingy} from '../thingy/thingy';

let componentType;
switch (field.type) {
  case 'Button':
    componentType = Button;
    break;
  case 'Thingy':
    componentType = 'Thingy';
    break;
}

dcl.loadIntoLocation(componentType, this.elementRef, 'container');
```

Which means it's currently not possible to *dynamically* load in a Component, unless you can get a Class reference from a string. 

Created a plnkr here: http://plnkr.co/edit/16XEOBS23L1oQhPwufVh?p=preview

**Comment by zoechi** [comment]
@intellix I haven't tried this myself because I don't use TS (only Dart) but might be useful for you http://stackoverflow.com/questions/35436681/angular2-manually-resolve-a-type-by-string-name#35436681

**Comment by intellix** [comment]
I guess that could work, but would mean registering all of my components into the Injector. Thought this  would only be desirable for singleton services?

**Comment by zoechi** [comment]
This question was about injector, no need to use the injector in your case. The relevant part is to get the type from a string. I assued `m.UserService` could be written as `m['UserService']`. Not tried though. 

If you want to get the type from DI you would need to register the type with a token. This wouldn't cause issues with singletons.

```
bootstrap(AppComponent, provide('Comp1', {useValue: Comp2}),provide('Comp2', {useValue: Comp1}), ...])

constructor(private injector:Injector) {}
someMethod() {
  var comp = this.injector.get('Comp2');
  this.dcl.loadIntoLocation(comp, this.elementRef, 'container');
}
```
Alternatively you could pass them as a map
```
bootstrap(AppComponent, provide('Components', {useValue: {'Comp1': Comp1, 'Comp2' : Comp1, ...}})])

constructor(@Inject('Components') private components) {}
someMethod() {
  this.dcl.loadIntoLocation(this.components['Comp2'], this.elementRef, 'container');
}
```

**Comment by PavelPZ** [comment]
Sorry for my totally stupid question: Can Angular 2 solve such a simple problem as Product Catalogue? Without a need of a special component for each product? Product descriptions and layouts vary a lot. In Angular terminology they all have totally different templates.
I came to angular from react and after a few weeks of satisfying experiments I met this problem (actually I am not solving Product Catalogue but an eLearning course with a lot of exercises - but the problem is the same).

I cannot believe that this complicated issue concerns my simple problem. Maybe I missed something essential regarding dynamic content loading in Angular. Didn't I?

**Comment by mhevery** [comment]
The way to support that is to have each layout be a separate component. Then load it using the `DynamicComponentLoader`

This is the only way to do it in a safe way with offline compile for the templates.

**Comment by iyobo** [comment]
But this means ALL components that could ever be used will have to first be statically imported into that file as opposed to dynamically loading the component from a string path.
This defeats the whole point of dynamic component loading.

I don't think the DynamicComponentLoader was designed very well. 
It seems to me Angular 2 seems to be going backward and not forward.

This just makes more reason why I prefer [AureliaJS](http://aurelia.io/) with new projects.

**Comment by Gaulomatic** [comment]
Bashing is not constructive, Iyobo. Nevertheless, the current architecture leaves you with the only option to do JavaScript-based server-side rendering to serve a page and shorten the (visual) bootstrap time on the client. If one (like me) has to use another technology, such like Java or ASP, you are pulled out until you use very freaky tricks, which indeed work, but feel like a workaround for a problem the team should really take a look on.

I am developing modules for DNN, Angular will always run from zero if a round trip occurs, there is no real site-wide SPA, only parts of it are. To put Angular2 in place you can choose the following: Accept a nearly doubled load time of a page or use the server side rendered HTML and "inject" it as a string (!) manually as the template for the root component. That works, but - with all respect - I feels painful.

One mighty say, hey - use Angular 1 for that purpose. But, no - I don't want to. Why? Because it simply makes much more fun to use Angular 2 for many obvious reasons.

The Angular team should take the usage of other optimized server-side-rendering technologies like ASP, Java, Ruby or even PHP (just for the record) into account even if those do not fit that smart with Angular itself like the JavaScript-based server-side rendering. Yes, this solution looked very cool when I first saw it, but the existing technologies have their own tier of advantage or - very simple - you are stucked at them just like me.

**Comment by iyobo** [comment]
It seems my last comment angered a few folk. As such I have adjusted it to cater to peoples sensitivities, but this does not make take anything away from the fact that the removal of dynamic template inclusion (like ng-include allowed) leaves something of an architectural handicap for certain applications.

**Comment by CaptainCodeman** [comment]
I agree, just as important as the promises of what it *will* do are the limitations of what it *won't* do, especially when they represent a change from Angular 1.

https://github.com/angular/angular/issues/4735#issuecomment-213817084

**Comment by bastienJS** [comment]
There exist now: ngTemplateOutlet http://5thingsangular.github.io/2016/04/18/issue-2.html see this demo: https://plnkr.co/edit/HxAxUtBwPHFyYU79V0yl?p=preview

**Comment by user414** [comment]
@bastienJS Thank you for that hadn't seen that coming in, does exactly what I would have wanted it to do. Allows to clean all the cut and paste in the ngSwitch and other place where a full component does not make sense, great stuff.

**Comment by roysubhra** [comment]
@bastienJS - the plunker does not work 
Is there a working demo somewhere?

**Comment by ivanmayes** [comment]
+1 on an answer here

**Comment by rsaf** [comment]
+1

**Comment by mhevery** [comment]
`ngComponentOutlet` is the closest to`ng-include`. There are no plans to have `ng-include`

**Comment by theredpea** [comment]
alexpods' answer has a URL (for Dynamic-Component-Loader) which doesn't work for me; instead I used this URL: https://angular.io/docs/ts/latest/cookbook/dynamic-component-loader.html

**Comment by KarlXOL** [comment]
The componentloader as the recommended solution by the angular team is not practicable. It doesn't allow to implement a generic solution for dynamic components. For each component you have also to create a dynamic module which has to provide all imports, exports, ... for the generic component.
Again, if angular 2 can't be the solution for a simple product catalog it is a mickey mouse framework and not for real world business applications.

**Comment by mhevery** [comment]
@KarlXOL i am sorry that the framework does not fit your needs. I understand that would be frustrating to you. Please find a positive way of funneling your frustration instead of name calling, which is not in the spirit of the code of conduct for our community. 

Positive ways may include:

1. Create an new issue which presents clear arguments which have not been already covered here. 
2. Creating a well documented work around.
3. Create a fix with clear tests demonstrating the issue.

**Comment by anandchakru** [comment]
This [SO answer](http://stackoverflow.com/questions/40418598/cant-get-ngtemplateoutlet-to-work) seems to provide a decent direction. 

**Note:** Yet to try it myself
