### ISSUE TITLE
Script elements in template files should be innert

### ISSUE THREAD

**Issue by IgorMinar** [angular/angular#2766]
Given a template:

```html
    some component template containing script tag
    <script>
      console.log('dfsdf');
      alert("hello");
   </script>
```

associated with a component:

```js
@Component({
  selector: 'test-component'
})
@View({
  template: 'test-component.html'
})
...
```

when the component is instantiated the script executes.

The root cause of this issue appears to be that we use `document.importNode(node, true)` when importing contents from the template into the main document. During this import the script element is revived and once appended to the document it's executed.

In Angular component templates this behavior is undesirable since the script is very limited in what it can do (it has no access to the context, di, etc) and only exposes large security vulnerability surface.

Tested with alpha-28.

**Comment by tbosch** [comment]
Related, as it allows to clone templates via `element.innerHTML` which does not trigger script elements: https://github.com/angular/angular/issues/3364

**Comment by mhevery** [comment]
I think we should just remove `<script>` tags in compilation. (Optionally move them into HEAD if that is want.)

**Comment by pkozlowski-opensource** [comment]
I would vote for removing those tags altogether as I don't think we want to act as a "poor's man" loader via templates. Will send a first-shot PR so we can discuss.

**Comment by mhevery** [comment]
@pkozlowski-opensource SGTM

**Comment by ianbelcher** [comment]
I know that this is an old thread but I believe that the proposal to make script tags _inert_ was the correct design decision as opposed to _removing_ them all together.

As discussed [here](http://stackoverflow.com/questions/38088996/adding-script-tags-in-angular2-component-template/38090157), removing script tags removes the ability for angular2 apps to implement structured data in the way that google [recommends it](https://developers.google.com/search/docs/guides/intro-structured-data).

There are likely other use cases and implementations apart from JSON-LD where the presence of script tags is required or useful and there may be more in the future as well.

Otherwise, is there a suitable workaround to be able to include such data within an app, whether rendered on the client or via universal?

**Comment by IgorMinar** [comment]
@ianbelcher can you please open a new issue requesting JSON-LD support and reference this issue there? thank you!
