### ISSUE TITLE
why private properties in .ts file are not accessible via .html files? 

### ISSUE THREAD

**Issue by elyasnew** [angular/angular#27819]
I am wondering why private properties in .ts file are not accessible via .html files (in one component)? moreover what's the purpose of defining private properties in typescript then?

**Comment by pkozlowski-opensource** [comment]
> I am wondering why private properties in .ts file are not accessible via .html files (in one component)? 

This is due to the way we generate code for compiled templates. See more detailed discussion in #27760

> moreover what's the purpose of defining private properties in typescript then?

So they are not "visible" from other TS class / functions? The same principle as in any language that supports concept of private fields. I agree that the fact that a template needs component fields declared as public make matters more complicated blurry.

Anyway, this is already being discussed in #27760 so closing this one as a duplicate.
