### ISSUE TITLE
Property is always a string

### ISSUE THREAD

**Issue by woppa684** [angular/angular#2787]
In the example below 'value' is a number which I want to increment. But, when I press the button I get '41', '411' etc. It appears that the property  'value' is always a string. No matter what kind of type I give it in my component. What would be the correct way to handle this? If I add a minusOne method by the way and add it to a button it DOES work as intended. If I press the plusOne button again then it will actually work. Only pressing the plusOne button first treats my field as a string...

```typescript
/// <reference path="typings/angular2/angular2.d.ts" />
import {Component, View, bootstrap} from "angular2/angular2";

@Component({
    selector: "c",
    properties: [
        'value'
    ]
})
@View({
    template: `<button (click)="plusOne()">{{value}}</button>`
})
class C {
    private value: number = 0;

    plusOne(): void {
        this.value = this.value + 1;
    }
}

@Component({
    selector: "app"
})
@View({
    template: `<c value="4"></c>`,
    directives: [C]
})
class App {
}

bootstrap(App);
```

**Comment by pkozlowski-opensource** [comment]
could you try `<c [value]="4"></c>`?

**Comment by pkozlowski-opensource** [comment]
Some more context: in your very specific case (`<c value="4">`) we are are not having an expression, but a literal value only. But this literal value is taken from HTML where everything is a string. By doing `<c [value]="4">` you are passing the `4` value through the expression parser where it is interpreted as number literal.

In short: if you want to enforce types, use the expression-binding syntax. Otherwise everything is a string.

**Comment by woppa684** [comment]
Ah, that clears some things up for me ... Thanks!
