### ISSUE TITLE
@angular/language-service doesn't understand type guards in binding expressions

### ISSUE THREAD

**Issue by fr0** [angular/angular#27891]
# 🐞 bug report

### Affected Package

 The issue is caused by package @angular/language-service

### Is this a regression?

Unknown.

### Description

Given the following code:

```ts
import {Component, Input} from '@angular/core';

export interface KeyValuePair {
  name: string;
  value: any;
}

@Component({
  selector: 'adt-test-component',
  template: `
    <div *ngIf="item && item.name">{{item.name}}</div>
  `
})
export class TestComponent {
  @Input() item: KeyValuePair | false;
}
```
The Angular language service underlines `item.name` in red, with the error:

```
ng: Identifier 'name' is not defined. '<anonymous>' does not contain such a member
```

The expression is valid and should not be an error. If the expression were in TypeScript instead of in a binding, the TypeScript compiler would not complain.

## 🔬 Minimal Reproduction

https://stackblitz.com/edit/angular-issue-repro2-vqmp9j

## 🌍  Your Environment

```
Angular CLI: 7.1.1
Node: 10.14.1
OS: darwin x64
Angular: 7.1.1
... animations, cli, common, compiler, compiler-cli, core
... elements, forms, http, language-service, platform-browser
... platform-browser-dynamic, router

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.11.1
@angular-devkit/build-angular     0.11.1
@angular-devkit/build-optimizer   0.11.1
@angular-devkit/build-webpack     0.11.1
@angular-devkit/core              7.1.1
@angular-devkit/schematics        7.1.1
@ngtools/json-schema              1.1.0
@ngtools/webpack                  7.1.1
@schematics/angular               7.1.1
@schematics/update                0.11.1
ng-packagr                        4.4.5
rxjs                              6.3.3
typescript                        3.1.3
webpack                           4.23.1
```

Editor: WebStorm 2018.3.2, on Mac OSX

**Comment by Airblader** [comment]
For someone reading this and thinking that the assertion in the OP is incorrect as I initially thought: key here is that the type is `KeyValuePair | false` and not `KeyValuePair | boolean`. The latter would correctly be a type error, but the former indeed isn't since `item` narrows the type to something non-falsy and thus `KeyValuePair` can be inferred already.

**Comment by fr0** [comment]
It would be nice if the language service could also infer that the `{{item.name}}` interpolation will only execute in the `KeyValuePair` case since the `*ngIf` is already guarded against the `false` case. I'm not sure if it's possible for the checker to be that sophisticated, though.

**Comment by vgb1993** [comment]
Definitely a must have feature since StrictCompilerOptions came around. Making use of $any() is dangerous and annoying. 

In our case we have hundreds of types with discriminated unions, and we’d love to see out types correctly detected. 

@alxhub have you done any progress with this feature? Also, I remember you explained in a conference how you where using TypeScript to type check the templates right? So I wondered, how come not all TypeScript type-cheching features are working property in our templates? 

Greetings!

**Comment by JoostK** [comment]
This is now working as expected with the Ivy language service, as the compiler's template type-checking machinery is used to produce diagnostics identical to regular builds.
