### ISSUE TITLE
ServiceWorker: Standard NavigationUrls do not respect baseHref 

### ISSUE THREAD

**Issue by alan-agius4** [angular/angular#27953]
Copied from https://github.com/angular/angular-cli/issues/13368

//cc @DanielHabenicht

### Bug Report or Feature Request (mark with an `x`)
```
- [x] bug report
- [] feature request
```

### Command (mark with an `x`)
```
- [ ] new
- [x] build
- [ ] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] xi18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc
```

### Repro steps
```
ng new repro-app
ng add @angular/pwa
ng build --prod --baseHref /coolapp/
```

### The log given by the failure
No failure log. 
But the ngsw.json has the following output:
```
...
"navigationUrls": [
    {
      "positive": true,
      "regex": "^\\/.*$"
    },
    {
      "positive": false,
      "regex": "^\\/(?:.+\\/)?[^/]*\\.[^/]*$"
    },
    {
      "positive": false,
      "regex": "^\\/(?:.+\\/)?[^/]*__[^/]*$"
    },
    {
      "positive": false,
      "regex": "^\\/(?:.+\\/)?[^/]*__[^/]*\\/.*$"
    }
  ]
...
```

### Desired functionality
The service worker should be scoped to the baseHref location provided in the `ng build` command. 
This way other resources on the same domain can still be loaded without beeing interfeered by the service worker. 

The desired ngsw.json would be:
```
...
"navigationUrls": [
    {
      "positive": true,
      "regex": "^\\/coolapp\\/.*$"
    },
    {
      "positive": false,
      "regex": "^\\/(?:.+\\/)?[^/]*\\.[^/]*$"
    },
    {
      "positive": false,
      "regex": "^\\/de\\/ \\/(?:.+\\/)?[^/]*__[^/]*$"
    },
    {
      "positive": false,
      "regex": "^\\/de\\/ \\/(?:.+\\/)?[^/]*__[^/]*\\/.*$"
    }
  ]
...
```

### Mention any other details that might be useful
My Use Case:
We have an app that is shipped in multiple languages. Every language is served under a different path, e.g.:
```
https://coolapp.com/en/
https://coolapp.com/de/
```
When changing the language both service workers do collide in their responsibility, as both match their pattern: 
```
    {
      "positive": true,
      "regex": "^\\/.*$"
    }
```
and want to serve their `index.html`. By scoping them to their respective location on the server they do not collide anymore. 

### Workaround (nasty)
Define different `"ngswConfigPath": "src/ngsw-config.json"` (full duplicates) in your `angular.json` for each environment and specify the `navigationUrls` accordingly:
```
"navigationUrls": [
    "/de/**",
    "!/**/*.*",
    "! /**/*__*",
    "! /**/*__*/**"
  ]
```

**Comment by gkalpak** [comment]
Sorry, @DanielHabenicht, I don't understand how this is a problem.

First of all, currently `@angular/service-worker` does not support having a different SW on different subpaths of the same domain. #27080 will fix that, but until then it is broken anyway.

And even once #27080 is merged, the [isNavigationRequest()][1] method would not match a request to `https://coolapp.com/de/` if the SW scope is `https://coolapp.com/en/` (because it [does not strip][2] the `https://...` part, so it would compare the full URL against `^/.*$`).

##
Closing, but feel free to continue the discussion below in case I've missed anything.

[1]: https://github.com/angular/angular/blob/45880532bffb5012a9b5da6da95e18688f4da10b/packages/service-worker/worker/src/app-version.ts#L180-L195
[2]: https://github.com/angular/angular/blob/45880532bffb5012a9b5da6da95e18688f4da10b/packages/service-worker/worker/src/app-version.ts#L190

**Comment by gkalpak** [comment]
(BTW, you are always free to overwrite the `navigationUrls`, if you are not happy with the defaults.)
<sub>(Not implying we should not have the most reasonable defaults.)</sub>
