### ISSUE TITLE
Reactive Forms Add FormGroup to Form Array

### ISSUE THREAD

**Issue by markofranjic** [angular/angular#27951]
Hi Team,
(Sorry if that problem is resolved but I didn't find it)

Reproduction: https://stackblitz.com/edit/angular-snnzhc?file=src%2Fapp%2Fapp.component.ts

Problem:
I have FormArray and in other method I have FormGroup which will populate FormArray.(order-form.service.ts)
When I click **onAddItem()** then I update table with order items. But when item has been added and you type new name/price of item, that values will be changed of FormArray.

Why I need that style:
I want to avoid when I add new item to that will be generated new input types.

Thanks

**Comment by manklu** [comment]
https://stackblitz.com/edit/angular-kwhp8g?file=src%2Fapp%2Forder-form.service.ts

**Comment by kara** [comment]
@markofranjic It's not really clear to me what the issue is based on that description (in the future, following the issue template really helps), but it seems like @manklu has helped you resolve your problem?  If that's not the case, please open a new issue that follows our template so we have enough context to debug.
