### ISSUE TITLE
Bazel schematics for Angular CLI throws tsconfig options mismatch

### ISSUE THREAD

**Issue by mgechev** [angular/angular#28034]
# 🐞 bug report

### Affected Package

 The issue is caused by package `@angular/bazel`

### Is this a regression?

 No

### Description

Bazel overrides some of the properties set in `tsconfig.json`. We should remove them from `tsconfig.json`:

## 🔬 Minimal Reproduction

```
ng new bzl --collection=@angular/bazel
cd bzl && yarn
bazel build //src:src
```

## 🔥 Exception or Error

```
WARNING: your tsconfig.json file specifies options which are overridden by Bazel:
 - compilerOptions.target and compilerOptions.module are controlled by downstream dependencies, such as ts_devserver
 - compilerOptions.typeRoots is always set to the @types subdirectory of the node_modules attribute
 - compilerOptions.rootDir and compilerOptions.baseUrl are always the workspace root directory
```

## 🌍  Your Environment

**Angular Version:**

7.2.0

**Comment by alexeagle** [comment]
I know I'm late to this party, but I think maybe the answer here was to fix the way we do warnings instead of work around it. What's the point of a warnings system if we turn it off?

If we do want to turn it off, the right way is to just add `"bazelOpts": { "suppressTsconfigOverrideWarnings": true}` to the tsconfig
https://github.com/bazelbuild/rules_typescript/blob/master/internal/tsc_wrapped/tsconfig.ts#L124-L127

could we talk about this one today?

**Comment by alexeagle** [comment]
discussed over Slack - we don't want to add the suppress key because then the user might make changes that don't take effect
