### ISSUE TITLE
chore(http): assert that url is present in RequestOptions when creating a Request

### ISSUE THREAD

**Issue by jeffbcross** [angular/angular#2806]
```typescript
//Input object should contain a url, currently not enforced.
var req = new Request({body: 'hi'});
```

**Comment by mhevery** [comment]
Shouldn't this be part of type definition so that TypeScript can assert that?

**Comment by mgechev** [comment]
@mhevery I think that we need to enforce both - compile-time type checking but also run-time type checking for ES5 DSL users.

However, there’s small problem for enforcing compile-time type checking by using mandatory `url` field in `RequestOptionsArgs` because it is used in both:
- `Request` and…
- Http method aliases like `get`, `post`, etc. where we pass the url as first argument and we don’t need it in the second parameter which is of type `RequestOptionsArgs`

As a solution we can refactor `RequestOptionsArgs` to be an interface and make the `url` mandatory. After that we can extend it like this:

```ts
export interface RequestOptionsAliasArgs extends RequestOptionsArgs {
  url?: string;
}
``` 

This way we can request second parameter of type `RequestOptionsAliasArgs` to `get`, `post`, etc. and use `RequestOptionsArgs` for `Request`. And from semantical point of view I think makes sense since `RequestOptionsArgs` is more generic compared to `RequestOptionsAliasArgs`.

The run-time type checking we can enforce with:

```ts
if (!options.url) {
  makeTypeError(‘…’);
}
```

As drawback I see one more interface to be documented but I don’t see any other clean way for doing this.

@jeffbcross @mhevery what are your thoughts on this? I can open a pull request if you think it sounds fine.

**Comment by jeffbcross** [comment]
@mgechev yes, makes sense to have multiple interfaces. What do you think about:

```typescript
// Required structure when constructing new RequestOptions();
interface RequestOptionsArgs {
  url?: string;
  method?: string | RequestMethods;
  search?: string | URLSearchParams;
  headers?: Headers;
  body?: string;
}
// Required structure when constructing new Request();
interface RequestArgs extends RequestOptionsArgs {
  url: string;
}
```

Regarding whether or not we should have a runtime error, we should be consistent with the rest of the framework, which I think generally strays away from runtime type checking. So by splitting interfaces, we accomplish the original objective of the issue. PR welcome!

**Comment by mgechev** [comment]
Okay, I'll take this one.

**Comment by jeffbcross** [comment]
@mgechev I've self-assigned just to show that there's an owner.

**Comment by mgechev** [comment]
It is still possible to create request with an empty URL if you want to by:

```ts
new Request(new RequestOptions());
```

However, by passing object literal TypeScript won't compile:

```ts
new Request({body: 'hi'});
// Argument of type '{ body:string; }' is not assignable to parameter of type 'RequestArgs'. Property 'url' is missing in type '{ body: string }'. 
```
