### ISSUE TITLE
Provide a 'whenStable' to asynchronously notify unit tests when Angular is ready

### ISSUE THREAD

**Issue by naomiblack** [angular/angular#2808]
e.g. an "onStable" task available for testing. This should include the ability to also check for events that are relevant to unit tests, but aren't part of change detection (e.g. animations).

c.f. internal bug https://b2.corp.google.com/issues/21869180

Also see related issues #428 and #1978.

**Comment by juliemr** [comment]
@hankduan could you take a look at this one? My understanding is that this issue is about finishing all tasks specifically for unit tests, but it's related to then `whenStable` API that we'd like to make for testability

**Comment by juliemr** [comment]
We should do this by making a private API in LifeCycle, and exposing it via Testability. We've decided that the same API can be used for (asynchronous) unit tests and end to end tests.

**Comment by yjbanov** [comment]
Closed this via #2980: `overrideOnEventDone` hook in `NgZone` is more reliable than `LifeCycle` because `LifeCycle.tick` may be called multiple times during a single event and it does not guarantee that everything stabilized. Only `NgZone` has that information.

**Comment by hankduan** [comment]
@yjbanov I don't think the current structure does exactly this, namely it doesn't notify if angular is not currently processing any events at the moment. For example, if I override OnEventDone, but angular is not currently processing any events, I will wait forever (it is already done, and will not ever notify me that it is done). 

Instead, what about the API `onEventDone(cb)`. It will check if angular is currently doing anything, and if not call back immediately. Otherwise, once angular settles, it will callback and unregister the call back (i.e. you'll have to call this API every time you want to know if angular is stable instead of just once). The downside is performance, but I don't see tests needing to call this so frequently that performance would matter.

**Comment by yjbanov** [comment]
@hankduan, in a normal situation Angular installs a zone at the root level and therefore _always_ processes _every_ browser event. It would therefore call `OnEventDone` every time. If you are running code outside the angular zone (e.g. via `NgZone.runOutsideAngular`) then, of course, it's up to you, because Angular is not even aware of what you are doing and cannot possibly notify you of anything (that's the idea behind running outside Angular).

If you want the logic to be:

```
if (angularIsRunning) {
  install on event done
} else {
  invoke callback immediately
}
```

You could do something like this:

```
bool angularIsRunning = false;
ngZone.overrideOnTurnStart(() {
  angularIsRunning = true;
});

void oneTimeOnEventDone(cb) {
  if (angularIsRunning) {
    install on event done
  } else {
    invoke callback immediately
  }
  angularIsRunning = false;
}
```

**Comment by hankduan** [comment]
I guess I was worried that we might miss the turnStart event, but now that I think about it, I guess if we inject zone into testability (https://github.com/angular/angular/blob/44891996b592cbbeafb3a6f45a27d8d943895bab/modules/angular2/src/core/testability/testability.ts#L14), we would never miss it. Thanks, this is good as is.
