### ISSUE TITLE
Error reporting errors on angular.io

### ISSUE THREAD

**Issue by IgorMinar** [angular/angular#28106]
Something is causing our error reporting to Google Analytics to fail in certain cases. We should fix it so that we understand the unrelying error that we currently fail to report. See the number 1 error record:

```
Object expected TypeError: at e.prototype.reportError@main.14be4badac296faa979e.js:1:493477 
e.prototype.handleError@main.14be4badac296faa979e.js:1: | 15,925(6.42%)
```

~The spike in error rate is not real - there were fewer errors in the last month because of lower traffic due to holidays.~ There was an error spike just after New Year but that’s unrelated, see 
https://github.com/angular/angular/issues/28114

![733e1c45-bf4c-4208-b606-5f0b0a9b8fe3](https://user-images.githubusercontent.com/216296/51078751-5c771600-166f-11e9-9e9d-bfb274e73879.png)

**Comment by gkalpak** [comment]
Do we know what browsers the errors come from? These sound like IE/Edge error messages :grin:

In any case, we should probably be able to handle errors [other than `string` or `Error`][1], because we are using our `ReportingErrorHandler` as [global ErrorHandler][2], which accepts [any value as argument][3].

[1]: https://github.com/angular/angular/blob/da2880d7c495022405102f89b8c641b23516388d/aio/src/app/shared/reporting-error-handler.ts#L20
[2]: https://github.com/angular/angular/blob/da2880d7c495022405102f89b8c641b23516388d/aio/src/app/app.module.ts#L163
[3]: https://github.com/angular/angular/blob/da2880d7c495022405102f89b8c641b23516388d/packages/core/src/error_handler.ts#L45
