### ISSUE TITLE
docs: Clarify that an angular library cannot live outside an angular app

### ISSUE THREAD

**Issue by ruimarques** [angular/angular#28125]
# 📚 Docs or angular.io bug report

### Description

We could make it clear in the library docs that an angular library cannot live outside an angular app (unless all its dependencies are added to the host app). 

A use case for an angular library to be useful outside an angular app would be a library of angular elements. But trying to do that with an angular library is not going to do it.

Define "Angular Library" in more detail in the overview, including that they are built for use with Angular. Also consider mentioning Angular Elements libraries or referencing the Elements docs.

### What's the affected URL?**
httos://next.angular.io/guide/libraries 

### Anything else relevant?

CC: @Splaktar

**Comment by Splaktar** [comment]
Fixed URL from OP is https://next.angular.io/guide/libraries.

This is now highlighted at the bottom of the https://angular.io/guide/libraries page:
![Screen Shot 2019-07-14 at 03 03 12](https://user-images.githubusercontent.com/3506071/61180415-f5b5c380-a5e3-11e9-9f51-fa2f50b1f9d5.png)
Which links to https://angular.io/guide/elements.

Fixed in PR https://github.com/angular/angular/pull/28476 as part of `8.0.0`.

The [glossary for "library"](https://angular.io/guide/glossary#library) was also updated in `8.1.0` via PR https://github.com/angular/angular/pull/26963.

@kapunahelewong or @jbogarthyde can you please close this out?

**Comment by kapunahelewong** [comment]
Got it. Thanks, @Splaktar. 🙂
