### ISSUE TITLE
Regression(build): Broken annotationsAs in es5 release files

### ISSUE THREAD

**Issue by trotyl** [angular/angular#28122]
# 🐞 bug report

### Affected Package

 The issue is caused by build process

### Is this a regression?

Yes, the previous version in which this bug was not present was: 6.1.7, 7.0.0-beta.3

Introduced in 6.1.8, 7.0.0-beta.4

### Description

 A clear and concise description of the problem...

All umd, esm5, fesm5 files in an Angular packages are now built with `annotationAs: 'decorator'` rather than `annotationAs: 'static fields'`.

All JIT apps not using Metadata Reflection API polyfill are now broken (when using ES5).

Most likely caused by https://github.com/angular/angular/commit/29761ea5f8e4bae68442236f4a0abc1666487a35, which turn off `tickicle` processing by default, but as [esm5 build process](https://github.com/angular/angular/blob/da2880d7c495022405102f89b8c641b23516388d/packages/bazel/src/esm5.bzl#L60) is not using [`tsconfig-build.json` file](https://github.com/angular/angular/blob/da2880d7c495022405102f89b8c641b23516388d/packages/common/tsconfig-build.json#L19), making tsickle being switched off in all official es5 release.

## 🔬 Minimal Reproduction

 https://stackblitz.com/...

https://unpkg.com/@angular/common@6.1.8/fesm5/common.js (`__decorate`)
https://unpkg.com/@angular/common@6.1.7/fesm5/common.js (`.ctorParameters`)

## 🔥 Exception or Error
<pre><code>

N/A
</code></pre>

## 🌍  Your Environment

**Angular Version:**
<pre><code>

</code></pre>

**Anything else relevant?**

**Comment by alexzuza** [comment]
I also noticed it here https://github.com/angular/angular/issues/27584#issuecomment-446462051

**Comment by trotyl** [comment]
@alexzuza Thanks for the link, I don't think it's a intended change for how it happened (and never documented)

**Comment by alxhub** [comment]
I talked with @alexeagle about this change when we made it. It's intended for ES2015 code to be built with tsickle, with downleveled annotations, and for ES5 code to be built using `__decorate`. JIT applications need to use a reflection polyfill (such as the one the CLI includes automatically)

**Comment by IgorMinar** [comment]
This change was introduced in https://github.com/angular/angular/pull/25649

This was an intentional change and that we should have documented better because you are right the unfortunate side-effect of this change is that the Reflect.metadata polyfill is now strictly required for JIT apps.

The reasoning for this change was that having tsickle in the @angular/compiler-cli build pipeline was problematic because tsickle currently supports only one version of TypeScript (usually the latest) while the @angular/compiler-cli supports multiple to remain backwards compatible for users that don't update typescript as new versions are allowed, but allow users that care to update to new typescript quickly. We can't make tsickle support multiple versions of typescript, so we decided to yank the dependency from the es5 build.

We did keep tsickle in the 2015 build pipeline for angular packages, just because we need it to do the very same down-leveling you pointed out as missing in order to make Closure compiler tree-shake things for the very few projects that use the closure compiler outside of Google.

That's a lot of context... and might not be relevant for too many people, I'm just trying to explain why we made this choice and why we can't easily add tsickle back.

That being said, we always documented Reflect.metadata polyfill as a required polyfill for JIT use-cases, so it is surprising to me that some developers expected it to work. If this ever worked, it was by accident and not intention and because the number of developers affected by this change as far as we know is very very low, I'm sorry to say that we won't be trying to fix it unless we find out that the user impact is much bigger than currently understood.

One thing we'll try to do much better, is document these changes in the changelog so that we don't surprise you. Thanks for understanding.
