### ISSUE TITLE
docs: improve "Library typings" section

### ISSUE THREAD

**Issue by IlCallo** [angular/angular#28126]
# 📚 Docs or angular.io bug report

### Description

@Splaktar 
As from [twitter request](https://twitter.com/Splaktar/status/1084557668960952322)

"[Library typings](https://next.angular.io/guide/using-libraries#library-typings)" section isn't really clear about which actions are referencing library code and which application code.

An example (but all the section is like this):

> Types defined in the library need to be added to the TypeScript configuration for the project that uses it.

This sentence doesn't state clearly if we are talking about the application tsconfig or the library one.
Right after, it's referenced `src/tsconfig.app.json`, so I guess we are talking about the app one? But maybe it's called like that just for consistency, because it makes much more sense to be defined inside the library tsconfig.

### What's the affected URL?**
https://next.angular.io/guide/using-libraries#library-typings

**Comment by alan-agius4** [comment]
This is actually explaining how to add a library and global library in the application.

Typings for library is slightly different, if they are not from `@types` and not for a devDependency. They should be not be added via tsconfig but rather via the triple slash reference. So that eventually these typings get processed and emitted as part of the bundle, so that consumers won't need to re-write those typings or use skipLibCheck to use your library.

**Comment by IlCallo** [comment]
Sorry, I cannot understand if you are supporting this issue or if you are saying it's not necessary to be more specific 🤔
Also, your explanation seem to target a different problem from what I highlighted here (but shall probably be added to the guide somewhere).

**Comment by alan-agius4** [comment]
Hi, the story here https://next.angular.io/guide/using-libraries#using-published-libraries is more for the application as a matter of fact most of the page is and even in the intro it states  "When building Angular applications...". That said, of course some of this contents there applies for libraries, since a library is another compilation module.

That said, maybe explaining better the difference between a library vs application would be beneficial.

1 `@types` in a library when you'd need to add this as a `dependency` instead of a `devDependency`. 

1. How to create and consume a self written types in a library. At the moment, in the docs, it's specifically for an application.

**Comment by alan-agius4** [comment]
@IlCallo, by the way "Types defined in the library..." meaning An `@types` library.

**Comment by alan-agius4** [comment]
Maybe changing 
`"Types defined in the library need to be added to the TypeScript configuration for the project that uses it."`

 to "Types defined in an `@types/` package need to be added to the TypeScript configuration for the project that uses it." 


Makes it easier to understand?

**Comment by jbogarthyde** [comment]
Fixed in https://github.com/angular/angular/pull/28410
