### ISSUE TITLE
Dynamic module loading 

### ISSUE THREAD

**Issue by vasicvuk** [angular/angular#28180]
# 🚀 feature request

### Relevant Package

@angular/core

### Description

I am missing a simple way to load module dynamically from file on server. Using compileModuleAndAllComponentsAsync with route lazy loading does not provide same result as putting Module in imports.

### Describe the solution you'd like
I would like a simple method that will load module from file with same behavior as it is loaded over import in main AppModule.

### Describe alternatives you've considered

I tried to create this using next things:
- SystemJS.import, compileModuleAndAllComponentsAsync and loadChildren.
- ngModuleFactory.create with injector from AppModule

I used umd bundle for JS that is imported.

The problem with first one is that i don't want lazy loading i want a module to be loaded just like the other modules but in runtime. Also this requires me to have different code (for routing) in case of normal and lazy loaded module.

The problem with second one is that for some reasons routes are not added at all and also some imports are creating duplicated services. This is not happening when the module is directly put in imports section of AppModule.

I looked at a simular issues and also looked for a lot of articles but none of them are not really solving this issue.

Angular version: 7.2.0

**Comment by mlc-mlapis** [comment]
@vasicvuk ... you can't use `compileModuleAndAllComponentsAsync` because of there is no Angular compiler loaded in run-time ... AOT ahead-of-time of compilation + optimization + bundling.

But you can load any module entirely programmatically by your code without Angular router. Btw ... you use the same code as the router is using in fact. This theme was discussed many times, and there are also many comments on issues. Try to search a bit them ...

**Comment by vasicvuk** [comment]
@mlc-mlapis I already use **compileModuleAndAllComponentsAsync** with **AOT** and it works without any problem. 

Here is a working example repository: https://github.com/lmeijdam/angular-umd-dynamic-example

 Anyway this is not working as same as specifying module in imports.

**Comment by mlc-mlapis** [comment]
@vasicvuk ... ah, so you are loading JIT Compiler into the AOT app. OK, then it's possible.

Look at: https://github.com/angular/angular/issues/14324#issuecomment-438197339

**Comment by vasicvuk** [comment]
@mlc-mlapis  Yes i already viewed this video. What i don't like about it is that it seems to me that you need to create component or load all components through router. I want to be able to load all declared components just like specifying in import.

This runtime loading of modules is really pain for Angular when using it in Micro service architecture when you want to have micro-apps  (per each microservice) combined together to one interface

**Comment by mlc-mlapis** [comment]
@vasicvuk ... but you should differentiate between a programmatic way of a module/component loading (which is fully available through ... as the video/picture shows) and run-time compilation for which you need Angular compiler.

![image](https://user-images.githubusercontent.com/5693835/51257065-17bce900-19a7-11e9-82fb-cee7c15df843.png)

Now, with **Ivy locality principle** I can see an easy and fully transparent way to do all (including your dynamic ad-hoc modules which you need to compile it in run-time) things really on a server and always load already compiled modules.

Because of even a completely new and not used module yet could be compiled on a server first and then transparently loaded ... and the client would not see any difference. Even the performance should be much better... because of you do it on a server-side (once time only)  instead of on a client-side (repeatedly).

**Comment by vasicvuk** [comment]
I am glad that this feature will come with Ivy compiler. I hope that this use case of loading compiled modules from server will be documented well since i am not sure i understand how this will work. Every example i find with Ivy compiler just imports the module and instances a component, I am still not sure if this import is same as import inside @NgModule definition

**Comment by mlc-mlapis** [comment]
@vasicvuk ... do you mean importing the routes on the same level together with the main module?

**Comment by vasicvuk** [comment]
I mean on the same level like importing another module with routes in main module.

**Comment by mlc-mlapis** [comment]
@vasicvuk ... the nesting is affected by the logic and hierarchy principle of injectors ... because a lazily loaded module has its own child injector.

Notes:
* Why is it so important for you to get all routes on the same level?
* Also, how would be solved potential collisions?
* Maybe the planned feature call `default` module would solve the situation ... it allows also to load only one component in time instead of a whole module ... because all of them will be registered under that `default` module.

**Comment by vasicvuk** [comment]
I expect same behavior with loading module in runtime as loading module with import in NgModule. And i would like to keep this simple.

I want to have same development cycle and code for an module that is loaded in runtime and the one that is built with application.

**Comment by pkozlowski-opensource** [comment]
Many things will get simpler with ivy but there will never be 1:1 parity of JIT compilation in a browser and AOT compilation at the build time (I presume that this is what you mean by runtime / built with application).

We are all for simplicity but loading a compiler in a browser _has_ performance implications so we need to balance developer expectations with the final user experience.

Anyway:
* things will get simpler with ivy;
* we are not stopping here and will continue to simplify things;
* the discussion above is a good summary what is available today and what will happen in the future.

I don't think that there is anything immediately actionable here so for now - we are aware of the bigger-picture issues and working towards resolving them.

**Comment by vasicvuk** [comment]
Having compiler in runtime has performance implications but that is why we need to have a way to build AOT module and load AOT complied module in existing AOT application in runtime.

**Comment by mlc-mlapis** [comment]
@vasicvuk ... what do you mean by:

> that is why we need to have a way to build AOT module and load AOT compiled module in existing AOT application in runtime

We have that functionality already, right?

**Comment by mlc-mlapis** [comment]
@vasicvuk ... ah, so you are asking about the real practical case. Actually in the situation, when during an app building, there is created a super optimized bundle of all used Angular code (tree-shaking code) and is supposed that this code is the only code which is necessary from Angular packages side (from all existed app modules), you have these options:

1) ... always build a module in the context of the whole app, which is a standard way (is related to the watch mode of TS) and when done, you can load the app first and then such a module in any time, and it represents a standard lazily-loading module (either using a route or fully programmatically),

2) ... don't use Angular CLI and use some custom building + loading full UMD Angular packages (separately), because it allows you to compile your app without any Angular code so such a module can contain any functionality and you can compile it in any time and load it also in any time. The logical result is that you can even have many apps but those UMD packages can be loaded only once because of a browser cache you share those in its memory without repeating the loading from a server.

**Comment by mlc-mlapis** [comment]
@vasicvuk ... yep, there is really huge space for extendability, for sure.

ad 2) The main idea of that was to allow distributed teams (one is maintaining the main app and the rest develop and maintain other lazily-loaded modules as plug-ins) to work without the necessity to re-build the main app each time when any lazily-loaded module is changed. Of course, all teams have access to the project repository. Each developer is able to build the app but the important part is just a single lazily-loaded module which can be versioned separately -> without touching the rest of the project.

The switch ` --build-optimizer=false` is here for sure but I am not sure if it allows building a lazily-loaded module separately and replace only such a bundle under the whole app without touching it at all. I never tried that way.
