### ISSUE TITLE
feat(http): helpers/guides for short polling

### ISSUE THREAD

**Issue by jeffbcross** [angular/angular#2822]
Short polling consists of an application requesting data from the same endpoint at a specified interval (i.e. request any new comments on this github issues every 10 seconds), as opposed to long polling, which consists of making a request, and the backend waiting to complete that request until there's data to send. (i.e. request new comments on a github issue, wait until comments are returned, then open a new request). 

With RxJS, short polling is relatively easy to do, if one understands semantics of Rx well enough. 

Example (Some Http APIs shown here are not yet implemented):
```typescript
var lastCommentsUpdatedTime = '';
var requestOptions = new RequestOptions({
  url: 'https://api.github.com/repos/angular/angular/issues/123/comments',
  params: {
    sort: 'updated',
    since: lastCommentsTime
  }
});
// Create an observable that emits a new value every 5 seconds
Rx.Observable.interval(5000)
  //Create new http request, automatically cancel any pending requests.
  .flatMapLatest((_) => {
    var request = new Request(requestOptions.merge({
      params: {
        since: lastCommentsTime
      }
    }));
    //Return Observable
    return http.request(request);
  })
  //Get the response body
  .map(res => res.json())
  //Set the timestamp of last comments updated
  .do(comments => this.lastCommentsUpdatedTime = comments && comments.length ? comments[0].updatedAt : this.lastCommentsUpdatedTime)
  //Give the new or updated comments to the view to handle displaying the comments.
  .subscribe(comments => this.appendOrMergeComments(comments));
```

The only part about this that I think requires deeper Rx understanding is the creation of the interval observable and piping it into the function to generate the request. Perhaps this could be made simpler, and could also be made to provide similar functionality to Dart Streams.

In addition to providing framework help, there should be good docs on how to properly do polling with `Http`.

**Comment by blesh** [comment]
Why not have a custom operator on your Request observable type? Let's call it `poll`...

```js
myRequest.poll(5000); 
```

This could actually return a BehaviorSubject or the like, so it's a "hot" observable, and when you subscribe to it, you get the most recent response. One tricky bit about polling is you want to make sure the previous one completes before you do the next one. Otherwise you could have a 5 second polling interval, where nothing ever completes in under 5 seconds so everything is `flatMapLatest`-ed away.

[Here are two examples in a JSBin of different approaches to polling](http://jsbin.com/dolakinobi/3/edit?js,console,output)

The basic idea is to do one of two things, either:

1. Wait for the response to come back, then set up a delay and request again. (`poll` in the JSBin)
2. Wait for either the interval to be up AND the response to come back, then request again. (`poll2` in the JSBin.

Here's the code from the bin for posterity:

```js

var poller = request::poll2(3000, 4000);

// subscribing more than once to show single subscription behavior
poller.subscribe(x => console.log(x), err => console.error(err), () => console.log('done'));
poller.subscribe(x => console.log(x), err => console.error(err), () => console.log('done'));



function poll(interval, timeout=30000) {
  console.log('polling with a delay of ' + interval + 'ms and a ' + timeout + 'ms timeout');
  var subject = new Rx.BehaviorSubject(null);
  return this.timeout(timeout).delay(interval).repeat().multicast(subject).refCount().skip(1);
}


function poll2(interval, timeout=30000) {
  console.log('polling with a wait of ' + interval + 'ms and a ' + timeout + 'ms timeout');
  var subject = new Rx.BehaviorSubject(null);
  return Observable.timer(interval).zip(this, (_, x) => x).timeout(timeout).repeat().multicast(subject).refCount().skip(1);
}
```

I feel like `poll2` is probably the preferred behavior.

**Caveat** in current RxJS, `multicast` returns a ConnectableObservable that *cannot* be resubscribed to. RxJS 3 has solved that by improving and simplifying multicast.

**Comment by robwormald** [comment]
This issue was moved to angular/http#73
