### ISSUE TITLE
ivy: ngcc does not append the inputs that has same name with selector

### ISSUE THREAD

**Issue by thesayyn** [angular/angular#28226]
# 🐞 bug report

### Affected Package
@angular/compiler
@angular/router

### Is this a regression?
No

### Description
Ngcc does not append the inputs which suit with the directive selector. 

## 🔬 Minimal Reproduction
https://github.com/thesayyn/ivy-repro

## Current behavior 
Ngcc generates directive def like so
```typescript
RouterLink.ngDirectiveDef = ɵngcc0.ɵdefineDirective({
    ...
    inputs: {
      // Expected routerLink input
        queryParams: 'queryParams',
        fragment: 'fragment',
        queryParamsHandling: 'queryParamsHandling',
        preserveFragment: 'preserveFragment',
        skipLocationChange: 'skipLocationChange',
        replaceUrl: 'replaceUrl',
        state: 'state'
    }
});
```

## Expected behavior
```typescript
RouterLink.ngDirectiveDef = ɵngcc0.ɵdefineDirective({
    ...
    inputs: {
        routerLink: 'routerLink',
        queryParams: 'queryParams',
        fragment: 'fragment',
        queryParamsHandling: 'queryParamsHandling',
        preserveFragment: 'preserveFragment',
        skipLocationChange: 'skipLocationChange',
        replaceUrl: 'replaceUrl',
        state: 'state'
    }
});
```

**Comment by alexzuza** [comment]
I would add that this applies to all accessor decorators like:

**router-link.ts**
```
@Input()
set routerLink(commands: any[]|string) {
  ...
}

@Input()
set preserveQueryParams(value: boolean) {
  ...
} 
```

Since they become in generated js both:  CallExpression members and decorators

```
// members
Object.defineProperty(RouterLinkWithHref.prototype, "routerLink", {
    set: function (commands) {...},
    enumerable: true,
    configurable: true
});
Object.defineProperty(RouterLinkWithHref.prototype, "preserveQueryParams", {
    set: function (value) {....},
     enumerable: true,
    configurable: true
});

...
// decorators
__decorate([
  Input(),
  __metadata("design:type", Object),
  __metadata("design:paramtypes", [Object])
], RouterLinkWithHref.prototype, "routerLink", null);
__decorate([
  Input(),
  __metadata("design:type", Boolean),
  __metadata("design:paramtypes", [Boolean])
], RouterLinkWithHref.prototype, "preserveQueryParams", null);
```
Esm2015ReflectionHost loops over those members, removes each key from `decoratorsMap` and tries to retrieve class member.
https://github.com/angular/angular/blob/a0cdefb5fbfc1f6f3509cdbcd3eba85f5b2b124a/packages/compiler-cli/src/ngcc/src/host/esm2015_host.ts#L99-L106

But it can't since it's not class member but rather CallExpression

https://github.com/angular/angular/blob/a0cdefb5fbfc1f6f3509cdbcd3eba85f5b2b124a/packages/compiler-cli/src/ngcc/src/host/esm2015_host.ts#L727-L737

@petebacondarwin Please take a look. I think you know more)

**Comment by petebacondarwin** [comment]
Thanks for this report. I will look into it on Monday.

**Comment by petebacondarwin** [comment]
A quick check seems to show that it is fine for ES2015 files but is a problem with ES5 files.

And as @alexzuza suggests the problem is that in ES2015 the `setter`  property looks like


```ts
    set routerLink(commands) {
        if (commands != null) {
            this.commands = Array.isArray(commands) ? commands : [commands];
        }
        else {
            this.commands = [];
        }
    }
```

whereas in ES5 it is a call to `defineProperty` which we are not reading as a "member" of the class.

```ts
Object.defineProperty(RouterLink.prototype, "routerLink", {
  set: function (commands) {
      if (commands != null) {
          this.commands = Array.isArray(commands) ? commands : [commands];
      }
      else {
          this.commands = [];
      }
  },
  enumerable: true,
  configurable: true
});
```


We need to teach the `Esm5ReflectionHost` how to read these members of a decorated class.
