### ISSUE TITLE
Adding :id to guarded component path causes infinite loop

### ISSUE THREAD

**Issue by oleersoy** [angular/angular#28223]
@jasonaden the first sentence in the SO link has the Stackblitz demo:

https://stackblitz.com/edit/angular-ngrx-slice-demo-guard?file=src%2Fapp%2Fbooks%2Findex.ts

https://github.com/angular/angular/issues/27920

**Comment by ChrisDahmCS** [comment]
@jasonaden @oleersoy 

I don't believe this is an Angular issue per [this answer on the SO question](https://stackoverflow.com/a/54261035/10747134).

@oleersoy in order to help the Angular team troubleshoot/fix issues, it's important to make a minimum reproduction of the issue [more about that in this wall of text](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#submit-issue).

> We will be insisting on a minimal reproduction scenario in order to save maintainers time and ultimately be able to fix more bugs. Interestingly, from our experience users often find coding problems themselves while preparing a minimal reproduction. We understand that sometimes it might be hard to extract essential bits of code from a larger code-base but we really need to isolate the problem before we can fix it.

**Comment by oleersoy** [comment]
@ChrisDahmCS This is the reproduction:
https://stackblitz.com/edit/angular-ngrx-slice-demo-guard?file=src%2Fapp%2Fbooks%2Findex.ts

And this is the minimal part of it:
```
{ path: ':id', component: HelloComponent, canActivate: [AuthGuard] },
{ path: '', component: CollectionPageComponent, canActivate: [AuthGuard] }
```

Here's another demo that with the same type of configuration, but older Angular version, where the same setup works:

https://stackblitz.com/edit/akita-books-store?file=example-app%2Fapp%2Fbooks%2Fbooks-routing.module.ts

**Comment by oleersoy** [comment]
@ChrisDahmCS I examined the SO new answer a little closer, and it makes sense.  I'll tweak the book module with the suggested changes and cross my fingers.  Thanks for double pointing it out to me.  Have a great weekend.

**Comment by ChrisDahmCS** [comment]
@oleersoy I apologize I was in a little bit of a hurry earlier, and wasn't entirely fair in the last response (could have been more helpful).

I did see both of the examples, and I think the main difference is that the book module wasn't imported into the app module in the old version, but it is within the new version.

Since the app module is using RouterModule.forRoot, and the book module is using RouterModule.forChild, both are adding to the ROUTES provider. Since that is provided with the `multi` property ([they both use this method to create the providers](https://github.com/angular/angular/blob/master/packages/router/src/router_module.ts#L241-L246)), it adds them together when they're both in the same module (this happened because book module imports book routing module, which exports router module).

About the minimum reproduction > 
I think the goal with this is to have as simple of a project generated by angular as possible that shows the issue. I think your older example was actually pretty close, so I'll also apologize for splitting hairs about it! [Here's a minimum reproduction](https://stackblitz.com/edit/angular-routing-guard-example?file=src/app/app.module.ts) with a step showing the example (I should have done this in the first comment).

Hopefully you already have figured the issue out, and I hope you have a great weekend too- happy coding!
