### ISSUE TITLE
Using angular element in react with react-scripts v2.x.x won't work on production build

### ISSUE THREAD

**Issue by thisisgit** [angular/angular#28267]
# 🐞 bug report

Hi, I actually think that this is an issue on react-scripts so have reported the same issue in here: https://github.com/facebook/create-react-app/issues/5976
But got no progress on it since last 2 weeks so posting the same thing here since it's related to both angular and react.

To give summary of the issue, I'm using angular element to build a custom element that can be used in both angular and react applications. It used to work fine on react-scripts v1.x.x but started to throw error on v2.x.x when built with production script.

I'm not sure if it's **create-react-app**'s responsibility to fix this breaking change or **angular**'s responsibility to make it compatible to new react-scripts v2.x.x

### Affected Package
@angular/elements

### Is this a regression?

It used to work on react-scripts v1.x.x but starts to fail starting v2.x.x

## 🔬 Minimal Reproduction
Repo of angular element: https://github.com/thisisgit/test-ng-elements
Repo of sample react app that uses above repo: https://github.com/thisisgit/test-react/tree/master
(The working one is on master branch, and the failing one is on branch **scripts-v1.x.x**)

Failing demo when using react-scripts v2.x.x: https://test-web-app-bd61f.firebaseapp.com/
Working one when using react-scripts v1.x.x: https://test-web-app-2.firebaseapp.com/

**Comment by robwormald** [comment]
My suspicion is this is more related to webpack conflicts than anything else - typically, webpack adds a global variable that acts as the module registry / shared communication channel across chunks.

 If you build two applications independently with Webpack, and then load them in the same page, the globals (that by default have the same name...) get shadowed / conflicted and things go really wrong, because the registry is getting overwritten. 

I'm not sure if CRA exposes any configuration options here. We don't in Angular CLI, but you *can* set it up via [https://github.com/manfredsteyer/ngx-build-plus](https://github.com/manfredsteyer/ngx-build-plus). The setting you'd need to tweak is detailed here - https://webpack.js.org/configuration/output/#output-jsonpfunction

**Comment by robwormald** [comment]
See also - https://github.com/angular/angular/issues/23732 - same root cause
