### ISSUE TITLE
Router: CanLoad Guard can't return UrlTree

### ISSUE THREAD

**Issue by christianlundberg** [angular/angular#28306]
### Affected Package
angular/router

### Description

The `CanActivate `interface allows returning a `UrlTree`, but the `CanLoad `interface only allows `boolean`, `Observable<boolean>` or `Promise<boolean>`

## 🌍  Your Environment

**Angular Version:**
<pre><code>
Angular CLI: 7.2.1
Node: 8.10.0
OS: win32 x64
Angular: 7.2.0
... animations, common, compiler, compiler-cli, core, forms
... http, language-service, platform-browser
... platform-browser-dynamic, router

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.12.1
@angular-devkit/build-angular     0.12.1
@angular-devkit/build-optimizer   0.12.1
@angular-devkit/build-webpack     0.12.1
@angular-devkit/core              7.2.1
@angular-devkit/schematics        7.2.1
@angular/cdk                      7.2.1
@angular/cli                      7.2.1
@angular/flex-layout              7.0.0-beta.23
@angular/material                 7.2.1
@ngtools/webpack                  7.2.1
@schematics/angular               7.2.1
@schematics/update                0.12.1
rxjs                              6.3.3
typescript                        3.2.2
webpack                           4.23.1

</code></pre>

**Comment by vinagreti** [comment]
Hey guys.
Is there any news about this issue? Is it going to be implemented?

**Comment by MitchTalmadge** [comment]
Surprised that this is not supported

**Comment by simeyla** [comment]
I'm not sure exactly when most people are using `canLoad` vs. `canActivate` but my specific case (and solution) is as follows:

- I have a login dialog that gets displayed from inside my `AuthGuard` service. The `AuthGuard` shows the dialog but does not return true/false until the user has tried to log in.
- The `AuthGuard` service returns `UrlTree` if the login fails and the user needs to be redirected to a particular page (such as support page)
- My '/account` route is lazy loaded and may take a couple seconds to load
- I want the login dialog to appear *instantly* when the user clicks 'Account' hence adding `CanLoad`
- Therefore what I did was to put the same logic into my `canLoad` handler. This means the `canLoad` will also show a dialog box if it gets hit first. 
- I left my `canActivate` guard to run the exact same logic (don't worry - you won't ever see two dialogs)

For this case I found it easiest to do the following in `canLoad`:

 ```
canLoad(route: Route, segments: UrlSegment[])
    {
        const currentNavigation = this.router.getCurrentNavigation();
        const isInitialNavigation = !currentNavigation.previousNavigation;

        if (isInitialNavigation)
        {
            return true;   // always allow load for first navigation (avoids other complications)
        }
        else {

            // returns Observable<boolean | UrlTree> 
            return showLoginDialog().pipe(map(result => {

                if (typeof result === 'boolean') {
                   return result;
                }
                else {
                      // we have a URL tree
                     // wait for the expected NavigationCancel event and then navigate
                     this.routerEvents.navigationCancel$.pipe(take(1)).subscribe(() =>
                     {           
                        this.router.navigateByUrl(result); 
                     });
                    return false;
                 }
            });;    
        }
}
```

I also have a `RouterEvents` service where I have

      navigationCancel$ = this.router.events.pipe(filter((e): e is NavigationCancel => e instanceof NavigationCancel));


Note: watch out if you choose not to include the `isInitialNavigation` check. If your redirect is trying to redirect to the homepage then it won't work because the router thinks you're already there. You can solve this with a `/redirect_home` route that just redirects to homepage - or change the `onSameURLNavigation` setting.

**Comment by rakishii13** [comment]
Will this be released in a 9.x version or in V10?
