### ISSUE TITLE
Error, that is thrown by timeout, is not handled by catchError inside a http interceptor

### ISSUE THREAD

**Issue by sychd** [angular/angular#28468]
# 🐞 bug report

### Affected Package

I assume, that problem is in @angular/common/http
### Is this a regression?

Can't say whether it was before or not 

### Description

Rxjs `timeout` is  added for 10 millis (so, it would throw timeout error) for the request and also `console.log`  is added  in `catchError` callback in http interceptor. When there is timeout error, interceptor's catcher is not fired. But,seems, it should be caught, because timeout throws an exception. 

## 🔬 Minimal Reproduction
To reproduce:
1. open stackblitz and devtools
2. click test button to emit the request
3. check console.logs 
expected: console.log  both from interceptor and subscription is fired
actual: only callback from subscription is fired

Please, see stackblitz - https://stackblitz.com/edit/angular-z1uujx

## 🌍  Your Environment

**Angular Version:**
<pre><code>

ng version

Angular CLI: 6.2.8
Node: 8.12.0
OS: win32 x64
Angular: 7.0.0
... animations, compiler, core, forms, platform-browser
... platform-browser-dynamic, router

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.8.8
@angular-devkit/build-angular     0.8.8
@angular-devkit/build-optimizer   0.8.8
@angular-devkit/build-webpack     0.8.8
@angular-devkit/core              0.8.8
@angular-devkit/schematics        0.8.8
@angular/cdk                      7.2.0
@angular/cli                      6.2.8
@angular/common                   7.2.2
@angular/compiler-cli             7.2.2
@angular/http                     7.2.2
@angular/language-service         7.2.2
@ngtools/webpack                  6.2.8
@schematics/angular               0.8.8
@schematics/update                0.8.8
rxjs                              6.3.3
typescript                        3.2.4
webpack                           4.16.4
</code></pre>

**Comment by alan-mroczek** [comment]
Hi @sychd. This error isn't with @angular/common/http package itself. It's due to the way that your code works. I've added one more line to your stackblitz with a console.log to clarify situation a little bit, and moved timeout logic to interceptor:

https://stackblitz.com/edit/angular-abvqhq?file=src%2Fapp%2Fapp.component.ts

If you add timeout to pipe on http request in your code it causes whole subscription to fail (it wasn't an error, it was you that canceled request by passing pipe that unsubscribed from source Obervable after timeout, so interceptor won't catch that) within the timeout that you provided (you can check that if you remove pipe timeout, and check error type in console - it differs - with a pipe it's TimeoutErrorImp, without it's an actual HttpErrorResponse, and is handled in interceptor). What that means? It's outside of scope for HttpClient. You just end listening for response, so Angular won't fire any more events for you. To fix that you would need to do something more like in my stackblitz.

That way, your error handling lives inside of scope of your interceptor, hence it can be caught gracefully in predictable manner with timeout set globally for your app.

Hope it clarifies.

**Comment by sychd** [comment]
Hi @alan-mroczek, thank you for the answer. So, if I got you right - you want to say that intrceptor's cathError is targeted only on HttpErrorResponse and TimeoutErrorImp (or any other throw) should not be caught in interceptor? So, techically in interceptor we can handle only HttpErrorResponse error or errors that were occured "locally" - inside its own pipe?

**Comment by alan-mroczek** [comment]
@sychd interceptor's catchError is targeted on any kind of error, but it must occur inside it's own code (for example pipe as you said) or be triggered via some kind of error thrown by HttpClient. Your `timeout(10)` was causing an error, but it wasn't neither, It was just throwing on "listener", not inside of it's actual logic.

Second statement that you've posted is right, first should be expanded to all kind of errors. My pointing to error types maybe was bit misleading so sorry for that. I was trying to show rather which error occurs were, and what handles which (as they were two kind of errors in two places, it was only correlated).
