### ISSUE TITLE
Mismatch of dependencies in controller declaration causes bizarre error, ''TypeError: object is not a function'

### ISSUE THREAD

**Issue by bjones6** [angular/angular#2855]
Perhaps I'm misunderstanding how controllers should be declared but I came across a particularly large snake in the grass that took me awhile to solve.

Aforementioned error is caused by the following code:

```javascript
.controller('RegisterController', ['$scope', '$rootScope',  "ModelFactory", '$location',  '$firebaseArray',
        function($scope, $rootScope, $firebaseArray, $location, ModelFactory){
            console.log($firebaseArray); // outputs the ModelFactory object    
       }
]);
```
It would seem that parameters are passed to the function argument in the order they are declared in the array.  Such that:

```javascript
.controller('RegisterController', ['$scope', '$rootScope', '$firebaseArray', '$location', 'ModelFactory', function($scope, $rootScope, $firebaseArray, $location, ModelFactory){
            console.log($firebaseArray); // outputs the firebaseArray object properly.    
       }
]);
```

Is this by design? I find it a miracle that nowhere else in my codebase did I miss order the dependencies and the passed function parameters. 

In insight into this would be much appreciated.

**Comment by gdi2290** [comment]
Yo, this is the angular2 codebase and you're looking for the angular1 codebase [angular/angular.js](https://github.com/angular/angular.js/issues/new). With that said yes this is by design and personally you shouldn't manually annotate your controller. Please consider adding [ng-annotate](https://github.com/olov/ng-annotate) in your build step
