### ISSUE TITLE
official app for angular documentation in mobile

### ISSUE THREAD

**Issue by KeerthiYeruva** [angular/angular#28676]
# 🚀 feature request

### Relevant Package

 This feature request is for @angular

### Description
 Can you please create an official mobile app for angular documentation/guide

**Comment by gkalpak** [comment]
Since the [docs app][1] is a [PWA][2], you can install it on your homescreen (via the browser menu).
It will also work offline but in a limited fashion (e.g. only docs you have visited before will be available).

(Adding full offline support for all docs is tracked in #27492. See there for a hack/workaround to get all docs offline today.)

##
I am going to close this, since creating a mobile app for the docs in not in our plans atm. (We might revisit in the future.)

That said, I would be interested to hear what usecases (if any) are not covered by the current PWA approach. Feel free to comment below.

[1]: https://angular.io
[2]: https://developers.google.com/web/progressive-web-apps/
