### ISSUE TITLE
Component beforeCreation proposal

### ISSUE THREAD

**Issue by lansana** [angular/angular#28781]
# 🚀 feature request

### Relevant Package

This feature request is for @angular/core

### Description

The ability to have similar functionality to route resolving of data, but at the component level.

### Describe the solution you'd like

```
import { Component, BeforeCreation, OnInit } from '@angular/core';

import { DataService } from 'core';
import { Data, Error } from 'shared';

@Component({
    selector: 'my-component'.
    template: ''
}) 
export class MyComponent implements BeforeCreation, OnInit {
    data: Data;
    err: Error;

    constructor(private dataService: DataService) {}

    ngBeforeCreation() {
        console.log('ngBeforeCreation');
        this.dataService.load().subscribe(
            (data: Data) => this.data = data,
            (err: Error) => this.err = err
        );
    }

    ngOnInit() {
        console.log('ngOnInit');
        console.log(this.data);
        console.log(this.err);
    }
}

// ngBeforeCreation
// ngOnInit
// {message: 'Hello, world'}
// undefined
```

**Comment by jinbeomhong** [comment]
I don't think it is needed. You can call `dataService`'s method in `ngOnInit()`. What you want is `ngOnInit()`.

Read a https://angular.io/guide/lifecycle-hooks#oninit

> An `ngOnInit()` is a good place for a component to fetch its initial data.

**Comment by lansana** [comment]
The point is to defer the creation of the component until the completion of a synchronous `ngBeforeCreation`.

**Comment by spock123** [comment]
@jinbeomhong  ngOnInit is not run before the component is created.

It's actually a great request imho. Putting that logic in the router is the wrong place imho.

**Comment by pkozlowski-opensource** [comment]
@lansana I don't think we want to add this to the core of the framework as this use-case can be easily handled with the `ngIf` around your component that you want to delay, ex.:

```html
<my-delayed-component *ngIf="data != null" [data]="data"></my-delayed-component>
```

Generally speaking components that just receive data that they are interested with (rather than fetching it inside)  are easier to maintain and reason about. 

Angular already has quite a bunch of lifecycle hooks and adding one more would be probably too confusing to users. 

I'm going to close this as won't fix for now but happy to discuss more based on real-life use cases.
