### ISSUE TITLE
Roll back to ES6+. Make TypeScript optional!

### ISSUE THREAD

**Issue by devapp24** [angular/angular#28793]
# 🚀 feature request

### Relevant Package

Angular core

### Description

Why are all Angular developers forced to use TypeScript? 

TypeScript is making Angular much less popular and profitable. Not many business owners want to use TypeScript in their projects. For that reason, AngularJS 1.x is still more popular than Angular 2+ w/ Typescript. The majority of companies, I say over 90%, will still choose ES6+ over typescript. 

### Describe the solution you'd like

We need ES6+ option in Angular. Please let developers choose between ES6+ and Typescript when starting an Angular project. This is a very urgent update we need in Angular 8. Even if you guys create Angular 10, without ES6+ support, Angular still won't become more popular than AngularJS 1.x. That's completely abnormal. Current job market for Angular 2+ is horrible. It doesn't seem to be profitable at all. 

### Describe alternatives you've considered

I've been developing with React. It's been more stable experience because it's based on JS and more business owners want React now. However, I would still like to see Angular with ES6+ support.  In my opinion, TypeScript is destroying Angular.
Look, now we have Angular 7. But there are still more companies which prefer to use AngularJS 1.x. 
This is not very funny. Pushing typescript to Angular was apparently corporation's choice, not community's.  

TypeScript is an advanced language but it's not endorsed by the majority of businesses out there. I don't understand why Google want all Angular developers to use typescript?
Please admit Angular with TypeScript is a big failure.. it will never beat AngularJS 1.x and React. Honestly, I feel the whole Angular community is isolated due to TypeScript. Why do we need this when ES6+ can solve any problem and there are more job positions for it? 

I'm sure the developer community will welcome ES6+ based Angular 8.
This typescript nonsense should stop here. We need normal/compatible Angular back to community.

**Comment by alfaproject** [comment]
No one is stopping you from using ES2015+. You do know that TypeScript transpiles to ES5, right?

You can even use decorators if that's what's bugging you: https://babeljs.io/docs/en/babel-plugin-proposal-decorators

**Comment by mlc-mlapis** [comment]
@devapp24 ... really not sure where do you get the info about `The majority of companies, I say over 90%, will still choose ES6+ over typescript.`. Can you tell us some important data, based on which you build your statement?

**Comment by devapp24** [comment]
> 
> 
> @devapp24 ... really not sure where do you get the info about `The majority of companies, I say over 90%, will still choose ES6+ over typescript`. Can you tell us some important data, based on which you build your statement?

I see you're based in Czech Republic. I have no information about web development job market in Czech Republic. I've never been there.  

Here in US, out of 300 local web dev jobs, you'll find about 10 Angular front end positions. About 2 out of that 10 positions will demand Angular with typescript.  Others will give you an option to use Angular 2+ or just stick with AngularJS 1.x.  You'll find maybe 40+ ReactJS positions out of the 300, and 10+ for VueJS. The rest of them may not depend on frontend frameworks and use Wordpress, Drupal, etc. 

TypeScript should be completely optional... it should come as a module that you can install to ES6+ based Angular. Average companies will not require TypeScript.

**Comment by mlc-mlapis** [comment]
@devapp24 ... hmm, OK, that argumentation sounds certainly valid from your point of view. But there should also be some different point of views (around the whole world) then because if you go through most of the comparisons and analysis, developer studies, ... especially from the mid and large enterprise teams point of view, the fact that Angular is based on TS is always on top of its best features. You can see the same trend in Vue (where the new version will be fully based on TS also) and React actually. So from that point of view, the request to use Angular with only pure ES6+ coding sounds like a minority really.

**Comment by devapp24** [comment]
@mlc-mlapis 

Well, React has a TypeScript npm package you can install. I've seen a few React projects which use TypeScript.  I think Angular should come with ES6+ core and give you an option to install TypeScript npm package.

**Comment by mlc-mlapis** [comment]
@devapp24 ... I mean that Angular is fully written (and Vue will be in a short time) in TS ... and it means also full support for typing through the all its code. So do you really mean that it should be re-written to ES6+ code?

**Comment by devapp24** [comment]
> 
> 
> @devapp24 ... I mean that Angular is fully written (and Vue will be in a short time) in TS ... and it means also full support for typing through the all its code. So do you really mean that it should be re-written to ES6+ code?

Ideally we can request two versions of Angular. ES6+ version and TypeScript version...

**Comment by dawidgarus** [comment]
@devapp24 Ideally ngc should statically analyze JS as it does with TS and generate ngfactory files (or whatever it generates with Ivy). I'm pretty sure this should be possible with es modules using es6 syntax. TypeScript compiler would still be required, but you could write code in pure JS and it would be possible to use Babel.

**Comment by devapp24** [comment]
FACT: Typescript will never beat Javascript in popularity... that won't happen. Too much have been accomplished/established using JS. It's very rational to make ES6+ based Angular and make typescript support as an installable package.

**Comment by sarunint** [comment]
Actually, Angular has been shipping ES2015 code since version 2. There is also UMD bundles for you to throw that in the script tag and start using Angular in the old way.


But to take the advantage of AoT, you need TypeScript compiler. If you look closely, the only place in Angular that requires TypeScript is `@angular/compiler-cli`. (Yes, even the compiler itself does not require TypeScript.)

**Comment by devapp24** [comment]
TypeScript is a cult created by Microsoft. No companies actually need TypeScript to develop a web application.

**Comment by manklu** [comment]
@devapp24 Nobody actually needs a language to write software. Hex codes are more than enough.

If you don't like it, don't use it.

**Comment by devapp24** [comment]
> 
> 
> @devapp24 Nobody actually needs a language to write software. Hex codes are more than enough.
> 
> 

In the end, this Typescript drama is about two corporations forcing users to use language they have developed & invested in. But in the end, it won't work out.

**Comment by bvdmitri** [comment]
Actually, almost all features of TypeScript in Angular project is fully optional (decorators is the only exception here). You can simply ignore the fact you are coding in a different programming language because the syntax between TypeScript and ES6+ are the same.

You can also create your TSLint rules to forbid using TypeScript additional features in your project.

**Comment by dawidgarus** [comment]
> TypeScript is a cult created by Microsoft. No companies actually need TypeScript to develop a web application.

Not true. I work for large IT company (6000 employees) and we use TypeScript (frontend Angular app) and ES6 (toolset and stub server for development) and everyone agrees that TS rocks and we should migrate all our code to TS. There are number of bugs we could have prevented with static typing, not to mention productivity boost due to code completion.
From my experience: once you go TypeScript, you'll never go back.

**Comment by devapp24** [comment]
A lot of Google employees are commenting here.. but I stand with the normal business owners and other normal companies. 

Angular 2+ is the least popular frontend framework. VueJS will become more successful than Angular 2+. It's time for Google to offer ES6+ based Angular with an option to add TypeScript module. 

#boycottTypeScript #boycottAngular

**Comment by jotatoledo** [comment]
Bla bla bla, you make a lot of points with no base.

[The state of javascript 2018](https://2018.stateofjs.com/javascript-flavors/typescript/) collected some data about ts, that provides a base to counter argument most of your ideas. Typescript has already grown in popularity over time, and it will keep on going.

I think its time to close this joke of an issue.

**Comment by devapp24** [comment]
My opinions are based on legitimate observations. 

https://www.kelltontech.com/kellton-tech-blog/top-5-front-end-javascript-frameworks-2018

VueJS and ReactJS are now way more popular than Angular 2+.
AngularJS used to be a leading framework... typescript ruined the whole AngularJS ecosystem. 
Google should bring back JS to Angular. They will do whatever it takes to convince more developers to use their TypeScript... but it will fail.  Soon, you'll see Angular version 10 that is still much less popular than their original AngularJS 1.x. This is utter nonsense.

**Comment by bvdmitri** [comment]
@devapp24 https://en.m.wikipedia.org/wiki/Dunning–Kruger_effect

**Comment by devapp24** [comment]
> 
> 
> @devapp24 [https://en.m.wikipedia.org/wiki/Dunning–Kruger_effect](https://en.m.wikipedia.org/wiki/Dunning%E2%80%93Kruger_effect)

Wow, I want to show that to TypeScript developers! Thanks for the link.

**Comment by bvdmitri** [comment]
@devapp24 it was about you, btw

**Comment by devapp24** [comment]
> 
> 
> @devapp24 it was about you, btw

You too ;)

**Comment by IgorMinar** [comment]
Thanks for the feature request. There are however several issues with it and mainly due to your combative argumentation style which has no place on our issue tracker and violates our [code of conduct]https://github.com/angular/code-of-conduct) I'm going to close it.

But before I do here are some facts:

1. authoring Angular apps in typescript is optional, you can use ES5, ES2015, or ES2016 (fun fact: officially there is no such thing as ES6). We documented all options in early days just to realize that most people cared only about the typescript option. If we haven't yet we will soon deprecate the ES5 DSL and remove the support for ES5.
2. Enterprises and poweruser prefer typescript.
3. New developers prefer typescript if they are working in a project that has the build pipeline preset for them. This is mainly due to autocompletion and ide support.
4. Typescript is one of the fastest growing languages on GitHub
5. Many react and Vue users are converting to use typescript.
6. Vue development has moved over to typescript.
7. Most of new FE development at Google is done in typescript.
8. Angular is more popular than AngularJS ever has been.
9. We appreciate your feedback. Every feedback whether we like it  or not contains some usefult info.
10. We care about people, our community, and our team and their well-being. And we won't tolerate combative arguments, disrespectful comments, and bullying. We hope that you can step back, look over your comments and recognize that your current behavior is violating our code of conduct and we hope to see you back on GitHub contributing in a respectful and cooperative and constructive way.

Until then I'm closing this thread. If more unconstructive comments are posted here, we'll lock this thread, please don't force us to do that.

I get that it's easy to lose your cool when you feel strongly about something. Passion or anger can cause us to say or write things we would normally not say. So please take some time to reflect and think about what is the thing you care the most about (it seems to be the es2015 support) and come back to discuss that in a constructive and positive way. Thanks ❤️
