### ISSUE TITLE
Service worker should self destruct on 302 Answers

### ISSUE THREAD

**Issue by DanielHabenicht** [angular/angular#28803]
# 🚀 feature request

### Relevant Package

 The issue is caused by package @angular/service-worker

### Description

At the moment the [Angular documentation](https://angular.io/guide/service-worker-devops#safety-worker) states that Service Workers do only self destruct if the request of the `ngsw.json` file returns a 404.
https://github.com/angular/angular/blob/6b511a33f6c340cf2f8cf06b4feddb163b61d1c5/packages/service-worker/worker/src/driver.ts#L682-L690

As [Angular Apps should fallback to `index.html`](https://angular.io/guide/deployment#routed-apps-must-fallback-to-indexhtml) if I make the `ngsw.json` file unavailable by:
 - moving it to a different location or 
 - renaming it or
 - moving the whole app in the file structure, for example instead of `example.com/` to `example.com/app1/`

The Server hosting my app returns a 302 to indicate that it is falling back to the `index.html` and then serves it. 
In this case, no `ngsw.json` file exists but the service worker does not self destruct, because the file was "moved". 

### Describe the solution you'd like
As self-destruction of the service worker on redirects is no feasible alternative. The easiest solution would be to check the format of the `ngsw.json`, and if it is malformatted the service worker should self destruct. 

### Describe alternatives you've considered
Make a static entry in your file hosting application to return a 404.

**Comment by gkalpak** [comment]
IMO, a more reasonable server configuration is to only serve `index.html` for URLs that do not contain a file extension in the last segment (because such requests typicaly point to files  - images, JS scripts, JSON data, etc. - for which it doesn't make sense to serve `index.html`). With that, removing or renaming `ngsw.json` will work as expected.

Of course, we could change the SW implementation to make it more aggressive in unregistering itself. But since this is a heuristic anyway, there is no perfect way to detect when it should be unregistered or there is an itermittent issue (e.g. no network or corrupted response). Whatever we choose will work better for some usecases and worse for others.

I will leave it open as a (low priority) feature request, but it might just be better to update the example server configurations in the docs.

**Comment by valgussev** [comment]
According to the [documentation](https://angular.io/guide/service-worker-devops#safety-worker) update there is another way of self destructing which is by using `safety-worker.js`.

**Comment by gkalpak** [comment]
As mentioned in my previous comment, changing the implementation would work better for some usecase and worse for others (i.e. it would not be a net win). Given that and the low demand for this feature, I am going to close it.

**Comment by DanielHabenicht** [comment]
Thanks for going through the issues by hand, instead of closing them automatically.
