### ISSUE TITLE
pass the data to transcluded component

### ISSUE THREAD

**Issue by mfsi-nirmitm** [angular/angular#28815]
i tried this method , but not working .

code -
component1.html ->
```
<div>
<ng-content [value]="'test'" select=[selector]></ng-content>
</div>
```

component2.html ->
```
<component1 >
    <component3 
        [value]="value">
    </component3>
</component1>
```

but it is giving me the following error ->

Can't bind to 'value' since it isn't a known property of 'ng-content'.

1. If 'value' is an Angular directive, then add 'CommonModule' to the '@NgModule.imports' of this component.
2. To allow any property add 'NO_ERRORS_SCHEMA' to the '@NgModule.schemas' of this component. ("

][value]="'value'" select="[selector]" >

It is related to an old issue which was closed without solution - https://github.com/angular/angular/issues/8006

**Comment by pkozlowski-opensource** [comment]
@mfsi-nirmitm #8006 was closed since people since we [haven't heard back with a reproduce scenario for almost 2 months](https://github.com/angular/angular/issues/8006#issuecomment-223282429). We can't act on issues we can't reproduce or understand and will be closing those.

Now, coming back to your issue report and suggestion:

> 1. If 'value' is an Angular directive, then add 'CommonModule' to the '@NgModule.imports' of this component.

There are several conceptual problems with it. Firstly you can have several siblings directives in a content, ex.:

```html
<component1 >
    <component3 [value]="value"></component3>
    <component3 [value]="value"></component3>
    <component3 [value]="value"></component3>
</component1>
```

Should `<ng-content [value]="'test'" select=[selector]>` bind to the first instance? All of them? 

Then, you might nodes with _unrelated_ directives that _happen_ to have the same binding, ex.:

 ```html
<component1 >
    <component2 [value]="value"></component2>
    <component3 [value]="value"></component3>
    <component4 [value]="value"></component4>
</component1>
```

Those components might be _totally_ unrelated hence binding to them would be very confusing.

All in all it boils down to the fact that you don't know what you are going to get as projected content. As such you shouldn't be making any assumptions about what kind of elements / directives you will get and what bindings make sense on them. Based on this I don't think that we want to support such construct in Angular.

It is hard for me to suggest an alternative approach as I'm not clear what you are trying to achieve. As such I'm going to close this ticket as a support request. I can _try_ to help you achieve the desired result if you can provide a minimal stackblitz illustrating a real-life use case.
