### ISSUE TITLE
typo in explanation of the RouterOutlet

### ISSUE THREAD

**Issue by jhabba** [angular/angular#28828]
# 📚 Docs or angular.io bug report

### Description

Docs says, "The RouterOutlet is one of the router directives that became available to the AppComponent because AppModule imports AppRoutingModule which exported RouterModule."
But according to the code, it should say,
"The RouterOutlet is one of the router directives that became available to the AppComponent because AppModule imports **RouterModule** which exported **AppRoutingModule** ."

### What's the affected URL?**
https://angular.io/tutorial/toh-pt5#add-routeroutlet

## 📷Screenshot

![angular-typo](https://user-images.githubusercontent.com/32630059/53025074-e90eb400-3425-11e9-81b6-8a428b34cc19.PNG)

## 🔥 Exception or Error
<pre><code>

</code></pre>

**Comment by jinbeomhong** [comment]
Is the statement wrong? IMHO, it doesn't seem to be a problem. The `AppRoutingModule` exports `RouterModule`:

```ts
// https://angular.io/tutorial/toh-pt5#add-the-approutingmodule

import { NgModule }             from '@angular/core';
import { RouterModule, Routes } from '@angular/router';

@NgModule({
  exports: [ RouterModule ]
})
export class AppRoutingModule {}
```

Because if the routing module didn't export `RouterModule`, components of the app module, which is importing `AppRoutingModule`, can't reference any declarable classes included in `RouterModule`(e.g. router directives). As shown in `RouterModule`s implementation, the router module exports router directives making them public — If a `NgModule` don't export declarable classes, they are private by default(only visible in itself):

```ts
// https://github.com/angular/angular/blob/7.2.5/packages/router/src/router_module.ts#L135

// ...
@NgModule({
  declarations: ROUTER_DIRECTIVES,
  exports: ROUTER_DIRECTIVES,
  entryComponents: [EmptyOutletComponent]
})
export class RouterModule {
  // ...
}

// ...
```

Finally, the app module imports `AppRoutingModule`:

```ts
// https://angular.io/tutorial/toh-pt5#final-code-review
// src/app/app.module.ts

// ...
@NgModule({
  imports: [
    BrowserModule,
    FormsModule,
    AppRoutingModule
  ],
  declarations: [
    // ...
  ],
  bootstrap: [ AppComponent ]
})
export class AppModule { }
```

**Comment by jhabba** [comment]
Looks good. I understand.
