### ISSUE TITLE
updateOn: blur for input type="checkbox" does not update value in Safari or Firefox

### ISSUE THREAD

**Issue by sngan-buildium** [angular/angular#28830]
# 🐞 bug report

### Affected Package
The issue is caused by package @angular/forms

### Is this a regression?
Not sure

### Description
Given a form group set to {updateOn: 'blur'}, an input type='checkbox' form control inheriting this will not be updated when toggled in Safari or Firefox.

The same behavior works in Chrome (after clicking a checkbox, click something else to "blur")

Workaround:
Set {updateOn: 'change'} for the checkbox form control.

## 🔬 Minimal Reproduction
https://stackblitz.com/edit/angular-ibmibc

## 🔥 Exception or Error
No exception or error

## 🌍  Your Environment

**Angular Version:**
<pre><code>
Angular CLI: 7.0.4
Node: 10.0.0
OS: win32 x64
Angular: 7.0.3
... animations, cdk, common, compiler, compiler-cli, core, forms
... http, language-service, material, material-moment-adapter
... platform-browser, platform-browser-dynamic, router

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.12.2
@angular-devkit/build-angular     0.12.2
@angular-devkit/build-optimizer   0.12.2
@angular-devkit/build-webpack     0.12.2
@angular-devkit/core              7.2.2
@angular-devkit/schematics        7.0.4
@angular/cli                      7.0.4
@ngtools/webpack                  7.2.2
@schematics/angular               7.0.4
@schematics/update                0.10.4
rxjs                              6.3.3
typescript                        3.1.6
webpack                           4.28.4

</code></pre>

**Anything else relevant?**
Does not work:
Safari: Version 12.0.1 (14606.2.104.1.1)
Firefox: Version 65.0.1 (64-bit)

Working: 
Chrome: Version 72.0.3626.109 (Official Build) (64-bit)

**Comment by kara** [comment]
@sngan-buildium Are you testing on Mac OS?  If so, this is due to a difference in how events fire in Firefox/Safari vs. Chrome. In Firefox/Safari on OSX, checkboxes cannot be focused by click, so they cannot be blurred by clicking again.  See some existing Webkit tickets about this behavior [here](https://bugzilla.mozilla.org/show_bug.cgi?id=756028) and [here](https://bugs.webkit.org/show_bug.cgi?id=13724). Unfortunately, there's not much we can do to react in angular/forms if the event is never being fired.

**Comment by sngan-buildium** [comment]
I was testing on Mac OS.

Thanks for the info!
