### ISSUE TITLE
service worker doesn't cache endpoints

### ISSUE THREAD

**Issue by trayanr** [angular/angular#28988]
# 🐞 bug report

### Affected Package

 The issue is caused by package @angular/pwa

### Is this a regression?

No.

### Description

 ngsw caches only some API calls. I have created a project where I have an angular front end and AWS lambda/golang back end. The service worker seems to overlook all API endpoints that are of lambda but caches all that are not. 

## 🔬 Minimal Reproduction

 
[Here](https://github.com/kinghunter58/pwa-cahche-error) is a link for reproduction. It uses two endpoints one is the https://api.chucknorris.io/random/joke test api and the other is my own api endpoint.

## 🌍  Your Environment

**Angular Version:**
<pre><code>
Angular CLI: 7.3.3
Node: 10.15.1
OS: linux x64
Angular: 7.2.6
... animations, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router, service-worker

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.13.3
@angular-devkit/build-angular     0.13.3
@angular-devkit/build-optimizer   0.13.3
@angular-devkit/build-webpack     0.13.3
@angular-devkit/core              7.3.3
@angular-devkit/schematics        7.3.3
@angular/cli                      7.3.3
@angular/pwa                      0.12.4
@ngtools/webpack                  7.3.3
@schematics/angular               7.3.3
@schematics/update                0.13.3
rxjs                              6.3.3
typescript                        3.2.4
webpack                           4.29.0
</code></pre>

**Anything else relevant?**

 I know this is not because missing https because I tested on production server with ssl.

**Comment by gkalpak** [comment]
Thx for reporting this. This happens, because data-groups will only cache non-mutating requests (specifically: GET and HEAD).
So, the current behavior is by design, but we should mention it in the docs.

@kinghunter58, would be up to submitting a PR to update [this guide][1]?

[1]: https://angular.io/guide/service-worker-config

**Comment by slishnevsky** [comment]
> non-mutating requests

what does it mean exactly?
are these mutating or non-mutating requests?

https://baseurl/api/users
https://baseurl/api/users/${userId}/posts
https://baseurl/api/posts/${postId}/comments

Is it going to work offline properly if I define
`
"dataGroups": [
    {
      "name": "api",
      "urls": [
        "https://baseurl/api/**",
      ],
      "cacheConfig": {
        "strategy": "freshness",
        "maxSize": 1,
        "maxAge": "3d",
        "timeout": "5s"
      }
    }
  ]
`

**Comment by gkalpak** [comment]
>> non-mutating requests (specifically: GET and HEAD)
>
> what does it mean exactly?

I was referring to the [HTTP method][1] used. So, only GET and HEAD requests are cached (but not POST, PATCH, DELETE, etc).

[1]: https://developer.mozilla.org/en-US/docs/Web/HTTP/Methods

**Comment by gkalpak** [comment]
You are right, @trayanr, that the current approach does not offer much flexibility. This is by design.

In a nutshell:
When `@angular/service-worker` came out, the SW APIs where still in flux and changing very rapidly. We didn't want to offer people a lot of ways to shoot themselves in the foot. Nor did we want to have to maintain backwards compatibility for a large public API surface against a constantly shifting underlying platform.

Now that the SW APIs are more stable and mature, we are exploring ways to make `@angular/service-worker` more flexible/extensible.
