### ISSUE TITLE
[Feature Request] Logical / Virtual Modules

### ISSUE THREAD

**Issue by oleersoy** [angular/angular#29007]
### Relevant Package

Angular/core

Suppose we have a component that we want to publish on NPM and all it does is say hello.  I think the DRYest way to do this is just publish the component with one core component file.

So where is the module?  The module would be implied and created at runtime for the component.  Now if we specifically wanted to include / assign the component to a module it could be done in the annotation:

```
@component(moduleId: '@angular/material/extension')
```

[This could be complementary to this](https://github.com/angular/angular/issues/28826) in the sense that now neither `entryComponents` or `declarations` are necessary as components always have an understanding of what module they belong to since it either has to be annotated on the component or in the module.

**Comment by oleersoy** [comment]
https://github.com/angular/angular/issues/28826

**Comment by JoostK** [comment]
Heya, since Ivy it is accepted to have components which have not been declared in an NgModule. These components won't have access to other declarables at the moment, but a simple Hello World component as you mentioned would work. We are exploring ways of expanding these capabilities in a project known as "optional NgModules", which may eventually allow a component to "import" other components.

Regarding your idea about "virtual" NgModules, that would concern the _bootstrapping_ of an application, where an NgModule is currently used at runtime to create the module injector from (for DI purposes). We want to simplify the bootstrapping process of applications to also allow just rendering a component completely without an NgModule, but this is not yet actively worked on at the moment.
