### ISSUE TITLE
Clarification needed regarding how to load routing config using .forRoot()

### ISSUE THREAD

**Issue by jforjava1981** [angular/angular#29002]
# 📚 Docs or angular.io bug report

### Description
on page describing @NgModule it is mentioned that :
Only call and import a .forRoot() result in the root application module, AppModule. Importing it in any other module, particularly in a lazy-loaded module, is contrary to the intent and will likely produce a runtime error. For more information, see Singleton Services.
which is not exactly true where its possible to use forRoot() to be used in a seperate module and import that module into root module 

However it is possible to load Routing config using forRoot() in a seperate routing module 
 A clear and concise description of the problem...
As shown below in minimal reproduction code section and as  is followed by many teams including ours without any problems. So some clarification is needed regarding the part where it is mentioned that **forRoot() is not intended** to be used in **any other module than root module or app module**.

### What's the affected URL?**
https://angular.io/guide/ngmodule-faq

### Reproduction Steps**
import { NgModule } from '@angular/core';
import { RouterModule, Routes } from '@angular/router';

import { LoginComponent } from './user/login/login.component'; //your component

const routes: Routes = [
    { path: 'login', component: LoginComponent}
  ];

@NgModule({
  imports: [ RouterModule.forRoot(routes) ],
  exports: [
      RouterModule
   ] 
})
export class RoutingModule { };

import { RoutingModule } from './routing.module';

@NgModule({
  declarations: [],
  imports: [
    RoutingModule
  ],
  exports: [],
  providers: [],
  bootstrap: [AppComponent]
})
export class AppModule {}

### Expected vs Actual Behavior**
Expected : There should be problems or run time errors as forRoot() is used in Routing module and not in app ,odule/root module even though indirectly probably at run time is is loaded in app module?

Actual Behavior:
there is no such run time error when loaded in a separate module other than app module.

**Comment by jenniferfell** [comment]
@kapunahelewong : Do you know (or could you check) if this is a docs issue or a code issue? Thanks!

```
Expected : There should be problems or run time errors as forRoot() is used in Routing module and not in app ,odule/root module even though indirectly probably at run time is is loaded in app module?

Actual Behavior:
there is no such run time error when loaded in a separate module other than app module.
```

Sounds like an error is expected, which makes me think this is both...perhaps a code change but shorter term more explanation would help avoid the problem?

**Comment by jforjava1981** [comment]
I don't suppose this is code issue. I believe so because we have been using that some previous minor version and even in Angular 5 in other team so kind of long its been working without issues. 
maybe documentation should explain if there are any specific scenarios in which this will error OR its just that even though it might work its not guaranteed and should not be relied on.

**Comment by kapunahelewong** [comment]
@jenniferfell, the language just needs to be cleared up. 

What the paragraph is alluding to is the injector tree hierarchy, and without going down the rabbit hole, the original writer implied this point in the scenario of lazy loading but as @jforjava points out there's more going on here (and that's the [rewrite of the Hierarchical Injectors doc](https://github.com/angular/angular/pull/28700)). So, just as @jforjava1981 says, there isn't an error when you use `forRoot()` elsewhere, and that's because of the `ModuleInjector` tree. In the code snippet @jforjava1981 cited above works because that `AppModule` and `RouterModule` are using the same `ModuleInjector`.

I'm adding a link from the NgModule FAQ in question to a new section about `forRoot()` in the [28434](https://pr28434-12a23ef.ngbuilds.io/guide/singleton-services#the-forroot-pattern). @jforjava1981, let me know if you still have questions or feedback. I'm happy to submit another PR to help make sure this point is clear.

**Comment by jforjava1981** [comment]
@kapunahelewong i tried to follow the link to PR however i get 404 error. I will read on the topics regarding the tree injector and how it plays in this scenario but if the new changes make it more clear nothing like it. thanks for the response. :)
