### ISSUE TITLE
ViewChildren collection is not changed after removing elements

### ISSUE THREAD

**Issue by dxvladislavvolkov** [angular/angular#29090]
# 🐞 bug report

### Is this a regression?

No

### Description

I use ViewChildren to get the QueryList of elements. And I check the count of elements. After removing elements count of QueryList doesn't change. 

## 🔬 Minimal Reproduction

 https://stackblitz.com/edit/angular-ddwjwu

I this example you can click on the show button to check the count of QueryList.
After you can click on delete button to remove an element and then check the count of QueryList again. You will see that count doesn't change.

## 🔥 Exception or Error
<pre><code>

</code></pre>

## 🌍  Your Environment

**Angular Version:**
<pre><code>
    "@angular/animations": "^7.0.0",
    "@angular/common": "^7.0.0",
    "@angular/compiler": "^7.0.0",
    "@angular/compiler-cli": "^7.0.0",
    "@angular/core": "^7.0.0",
    "@angular/forms": "^7.0.0",
    "@angular/http": "^7.0.0",
    "@angular/platform-browser": "^7.0.0",
    "@angular/platform-browser-dynamic": "^7.0.0",
    "@angular/platform-server": "^7.0.0",

</code></pre>

**Anything else relevant?**

**Comment by pkozlowski-opensource** [comment]
> After you can click on delete button to remove an element and then check the count of QueryList again. You will see that count doesn't change.

This is expected as you are doing low-level DOM manipulation (element removal) and not going through Angular mechanisms. Angular is not "observing" DOM but tracks model bindings and its internal data structures.

You are finding yourself in a inconsistent state where you are using Angular half-way. You need to either go all-in and use only Angular to add remove elements or go to the low-level DOM manipulation and stick with it (this would mean doing DOM query instead of `ViewChildren`).

Closing this as works as designed / support request.

**Comment by dxvladislavvolkov** [comment]
@pkozlowski-opensource  Should I use renderer2? I tried but I get the same result.

**Comment by pkozlowski-opensource** [comment]
> Should I use renderer2?

Not sure what you mean? Using `Renderer2` to delete nodes won't change anything (it is just a facade to DOM manipulation). You need to either:
* use `NgIf` / `NgFor` to create nodes (views) to have Angular queries pick them up;
* if you want to delete DOM nodes directly (and this includes deleting nodes through  `Renderer2`) than you need to use DOM queries.

Anyway, at this point it starts to sound like a support request so I would suggest moving this conversation to StackOverflow.
