### ISSUE TITLE
Issue: template ref with ng-If

### ISSUE THREAD

**Issue by smkrn110** [angular/angular#29181]
Not working code

```
<div ng-if="condition">
 <input #tempRef .. />
</div>
<div>
 <input (onclick)=save(tempRef) ../>
</div>
```

Working code when not with ng-if

```
<div>
 <input #tempRef .. />
</div>
<div>
 <input (onclick)=save(tempRef) ../>
</div>
```

- Angular : v5.2.0

**Comment by pkozlowski-opensource** [comment]
Not sure what `ng-if` supposed to mean (it is not Angular v5.2.0 syntax...) but if you've meant `*ngIf` like so:

```html
<div *ngIf="condition">
 <input #tempRef .. />
</div>
<div>
 <input (onclick)=save(tempRef) ../>
</div>
```

you need to observe 2 things:
* local variables (`#tempRef`) are _scoped_ (visible only within) a given `<ng-template>` block;
* `*ngIf` is just a sugar syntax for:

```html
<ng-template [ngIf]="condition">
   <div>
    <input #tempRef .. />
  </div>
</ng-template>
<div>
 <input (onclick)=save(tempRef) ../>
</div>
```

As you can see `#tempRef` is inside `<ng-template>` and is _not_ visible outside of it (hence not accessible in ` (onclick)=save(tempRef) `.

Having said this it _feels_ like you are trying to use your DOM as model and what you probably want to do is to use `ngModel` on your input, collect data and use data in your `save` method (instead of a DOM element). Anyway, this starts to sound like a support request and as such doesn't belong here - please use an appropriate support channel as requested in the issue template.
