### ISSUE TITLE
build file size of Ivy project  is too much !

### ISSUE THREAD

**Issue by nitishk72** [angular/angular#29201]
Angular CLI: 8.0.0-beta.5
I create a hello world project with `--enable-ivy` flag and build the project. I am not seeing any difference in file size. 

What is the problem here ?

![image](https://user-images.githubusercontent.com/15886737/54071198-65f7b580-428f-11e9-80d9-2ac289103550.png)

**Comment by alexeagle** [comment]
The size savings from Ivy are in the generated JS files for your templates. Given some size of HTML templates, the prior compiler created much larger multiplier of JS output size compared with Ivy.

If you don't have some critical mass of HTML templates, you won't see that size improvement. This app looks tiny?

Note also that there's a known issue with the framework code itself currently being *larger* under Ivy than before. We plan to fix this before 8.0 final ships.

**Comment by Mohendran** [comment]
@alexeagle  This issue is still there. Im using Angular 8.2.0

**Comment by petebacondarwin** [comment]
There have been improvements in the build size of the core Angular libraries over the last few months. Closing due to a lack of activity on this issue.

If you find you have an app that experiences significant size increase with the latest v9 release candidates then please file a new issue with a reproduction. Thanks!
