### ISSUE TITLE
Form validation - a way to execute only some validators

### ISSUE THREAD

**Issue by BatshevaKl** [angular/angular#29275]
#🚀 feature request

### Relevant Package
@Angular 5+

### Description
In an angular form, I have one control ("first") with 2 custom validators on it.

One of the validators is an async validator that goes to the server to check validation of the field (needs to be chcked with the DB).

```
    this.mainForm.controls['first'].setAsyncValidators([customAsyncValidator()]);
    this.mainForm.controls['first'].setValidators([customValidator(this.mainForm.controls['second'])]);
```

On an update of a different field in the form ("second"), I need to run the customValidator on the "first" control, as the "customValidator" validates the value depending on what is the value in the "second" control.

On the blur of "second" control, I just validate the first one.

    `this.mainForm.controls['first'].updateValueAndValidity();`

What's not good in the above solution, is that it executes all the validators of the "firts" control, **including the async validator which really takes some time and not necessary in that case** (only when the value in the "first" control is being changed).

What I wondered - **Is there any way to excecute not all validators of a control, but just some of them?**

### Describe the solution you'd like
Need a way to execute only some validators on a form control
something like this:

    `this.mainForm.controls['first'].updateValueAndValidity([customValidator,...])`

### Describe alternatives you've considered
I can remove the validators that I don't need to check now from the control before calling the updateValueAndValidity and re-assign them after calling it.

**Comment by thefliik** [comment]
I just made a proposal which addresses this issue over in #31963. I'd be very interested in any feedback you might have. Specifically, it allows a service to add/remove errors from a control. Because errors are keyed to the service which adds them, one service cannot overwrite another's errors. 

An example using debounce time is (I also include a stackblitz demo over in #31963):

```ts
const usernameControl = new FormControl();

usernameControl.valueChanges
  .pipe(
    tap(() => usernameControl.markPending('userService', true)),
    debounceTime(500),
    switchMap(value => this.userService.doesNameExist(value)),
    tap(() => usernameControl.markPending('userService', false)),
    map(response => ({
      sources: ['MyUserService'],
      type: 'errors',
      value: response.payload ? { userNameExists: true } : null, <-- this is an error (or null)
    })),
  )
  .subscribe(usernameControl.source);
```

Here, the stream of value changes from the `usernameControl` is piped to the `userService` through `debounceTime`. The service marks the control as pending while it performs validation and then returns any errors or `null`. The usernameControl then subscribes to this errors output (thats the `.subscribe(usernameControl.source)` line at the end).

You could easily change this example to examine the input and, based on it's value, decide to run validation or not. More broadly, this allows you to programmatically add errors to a control however you see fit, either synchronously or asynchronously (in addition to using `ValidatorFn` / `AsyncValidatorFn`).
