### ISSUE TITLE
Input checked attribute is not present in markup

### ISSUE THREAD

**Issue by mboughaba** [angular/angular#29502]
Dear,

# 🐞 bug report
Checkbox checked attribute is not set.

### Is this a regression?
Not sure

### Description

"checked" attribute is not present in mark-up when using attribute binding.

## 🔬 Minimal Reproduction
https://stackblitz.com/edit/angular-checked-binding-not-persisted-in-template

## 🔥 Exception or Error
When clicking the toggle button, the checkbox state will change however the "checked" attribute will not be added to the HTML input element.
Occurs also when clicking the input itself.

![image](https://user-images.githubusercontent.com/3800584/54907613-3d55f980-4ee6-11e9-9643-68d432acc504.png)
![image](https://user-images.githubusercontent.com/3800584/54907626-4777f800-4ee6-11e9-9fbc-06afef939971.png)

## 🌍  Your Environment

angular 7.2.10

# Motivation

This might look like a cosmetic issue, however, it is blocking our QUA team from validating the behavior of our app.

Thanks for consideration.

**Comment by pkozlowski-opensource** [comment]
Please note that Angular is binding to _properties_ (like `[value]`) and browsers might _chose_ to reflect this property state to an attribute. many properties _are_ reflected by some not. This works perfectly fine and you only problem is that you are trying to assert on the generated DOM (and not the UI that a user is  seeing).

Your second example "works" since you are just adding a static attribute and don't have any binding. 

There is a fundamental difference between:
* `<input value="1">` - this means, create an input with a given value _attribute_
* `<input [value]="expressions">` - this means - update input's _property_ in response to `expression` changes (this will _not_ set an attribute!)

If you really, really want to dynamically set an attribute you can use `<input [attr.value]="expressions">` : https://stackblitz.com/edit/angular-checked-binding-not-persisted-in-template?file=src%2Fapp%2Fapp.component.html

Going to close this issue as it seems to be about confusion regarding properties and attributes.

**Comment by mboughaba** [comment]
My bug report was about `checked` attribute which is a HTML attribute that support minimization, same as readonly and disabled. I don't know why you are referring to value.

![image](https://user-images.githubusercontent.com/3800584/54953861-8723fb80-4f49-11e9-9ba5-4b1d9360f320.png)
readonly and disabled states are reflected properly, but checked is not.

> If you really, really want to dynamically set an attribute you can use <input [attr.value]="expressions">

binding to `<input [attr.checked]="expresssion">` is a bad idea because any non empty string will evaluate to true and thus your state is messed-up.

=> So basically the `checked` attribute not being reflected in the markup is a normal browser behavior. 

> Going to close this issue as it seems to be about confusion regarding properties and attributes.

Sure! But I don't think it is a confusion problem.

**Comment by pkozlowski-opensource** [comment]
> My bug report was about checked attribute which is a HTML attribute that support minimization, same as readonly and disabled. I don't know why you are referring to value.

Sorry, I've used `[value]` but the _same_ principles apply to `[checked]` - this is _exactly_ the same explanation, just a different attribute / property name.

**Comment by mboughaba** [comment]
OK, I get your point.
  The `checked` property is set on HTMLInput but not reflected to the `checked` attribute (browser).
however inspecting it won't help 
![image](https://user-images.githubusercontent.com/3800584/54955257-0f57d000-4f4d-11e9-9167-59014719e3c3.png)
But that's a browser behavior/issue and has nothing to do with angular.

Thanks @pkozlowski-opensource for your time.
cheers
