### ISSUE TITLE
Automatic Routes 

### ISSUE THREAD

**Issue by simmy12** [angular/angular#29519]
🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑

Please help us process issues more efficiently by filing an
issue using one of the following templates:

https://github.com/angular/angular/issues/new/choose

Thank you!

🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑

**Comment by simmy12** [comment]
angular can built an automatic routing.
by writing the name of the component to route, the component will be switch to that component.
if it is needed for params, it will send. 
for what to white the object of routes?

**Comment by gkalpak** [comment]
It is not clear what you are asking. It sounds like this is a feature request for some simpler way to define routes (as component decorators?) or something.
It might be a interesting feature, but it is really impossible to tell. I am going to close this, but feel free to open a new issue and follow the appropriate template: https://github.com/angular/angular/issues/new/choose
<sub>It is important that everyone follows the template, so that we can effectively triage and act on the issues. Thx!</sub>

**Comment by simmy12** [comment]
Here I see. Yes, I meen a new feature. I see the link to use for suggesting
a new feature.  Thank you for the quick and the right answer. You may close
the issue.  Simi

‫בתאריך יום ג׳, 26 במרץ 2019 ב-13:46 מאת ‪George Kalpakas‬‏ <‪
notifications@github.com‬‏>:‬
