### ISSUE TITLE
Angular animation: :leave animation starts at wrong position

### ISSUE THREAD

**Issue by mfursov** [angular/angular#29526]
### Affected Package
@angular/animations

### Description
:leave animation has incorrect initial position for the animated elements.

## 🔬 Minimal Reproduction
https://stackblitz.com/edit/angular-fqxnxd?file=src%2Fapp%2Fapp.component.ts

Follow  the steps in the demo. Notice that only first element exits correctly.

## 🌍  Your Environment
Chrome v73

**Angular Version:**
"@angular/animations": "^7.2.10",
"@angular/common": "7.2.5",
"@angular/compiler": "7.2.5",
"@angular/core": "7.2.5"

**Comment by malieop** [comment]
The problem only happens when you reverse your list order.

**Comment by marcusrettig** [comment]
I have the same issue, here are my conclusions so far:
- The issue is actually that the `:enter` transition runs instead of `:leave`.
- It only happens when `:enter` is after `:leave` in the array passed to `trigger(..)`.
- It still happens if you completely remove the `:leave` transition.

**Comment by dario-piotrowicz** [comment]
Hi @mfursov and all, I've just created a PR with the fix 🙂 👆 

The issue is as @marcusrettig suggested that `:enter` runs instead of `:leave`, that is because when the elements in the list are moved their DOM elements are removed and re-inserted
<sub>(PS: when reversing the array the last one is an exception since it, as a side effect gets moved/pushed down by the other n-1 items, that is why the last item in the reversed list doesn't present the issue)</sub>

The real issue here is that the reordering "triggers" the leaving of the elements, but then cancels it (you don't see them disappear or anything), as a side effect however it loses the trigger's value.

To explain better, please have a look at this [updated stackblitz with logs](https://stackblitz.com/edit/angular-ce12vv)

when you add the 3 items in the console you can see that normal transitions from `void` to `null` occur (and remember that `void => *` matches `:enter`), when you reverse the list you will see 2 (and not 3, as I mentioned earlier) transitions from `null` to `void` (which match `:leave`) but the items haven't actually left the DOM, now if you remove the 3 items, the first one works fine (`null` to `void`) but the other 2 transition from `void` to `void` (the first `void` should be `null`, but the `null` got lost during the reordering), remember that `void` to `*` matches `:enter`, we can see why the `:enter` transition is executed instead of `:leave` (since the first successful `transition` cancels the others) _(__note:__ `void` to `void` also matched `:leave`/`* => void` so, if you switch the `transition`s in the array everything would work as expected even without my PR's fix)_

_(also feel free to experiment with the stackblitz, this also happens if we bind some value to the trigger, not only if the value is `null`)_

I hope this helps clarifying things 🙂
