### ISSUE TITLE
Better error messages when Component property is misspelled in binding

### ISSUE THREAD

**Issue by irfantusneem** [angular/angular#2963]
When a directive is missing from the @View directives property the following error message is displayed.

Can't bind to 'essContext' since it isn't a know property of the 'ess-form' element and there are no matching directives with a corresponding property

Change this to.

Can't bind to 'essContext' since it isn't a know property of the 'ess-form' element and there are no matching directives with a corresponding property.  Please check if the directives attributes for the View defines all the necessary components.

Or it can display the current list the directives and say that a directive for essContext is missing.

After a while people will get used to the original error message but the first time you see it, it is hard to understand what it is trying to say.

**Comment by pkozlowski-opensource** [comment]
@irfantusneem thnx for the suggestions, but I don't think we can change the error messages exactly as you are proposing:

> Can't bind to 'essContext' since it isn't a know property of the 'ess-form' element and there are no matching directives with a corresponding property. Please check if the directives attributes for the View defines all the necessary components.

The issue here is that this error can be thrown if you misspell (or fail to declare) a property of a directive. So lack of the directive or lack of a property gives the same error. 

Could you think of a different error massage that would capture this other case as well? We want to have extra-awesome error messages, that is why we want to hear what error messages people would like to see. At the same time we need to make sure that those error messages are accurate.

BTW, I'm working on a different check that will try to detect non-standard elements (like your `ess-form`) without a corresponding @Component directive and will throw an error in that case. The suggested error message for now would be: "The non-standard 'ess-form' element is not a web component and wasn't matched by any directive. Maybe you've misspelled the name or forgotten to add a directive to the `directives` list in @View".

This error would be thrown before the property binding one. WDYT?

**Comment by naomiblack** [comment]
obsolete. will not fix.
