### ISSUE TITLE
feat(router): implement otherwise/routeNotFound hook

### ISSUE THREAD

**Issue by btford** [angular/angular#2965]
We need some way to deal with the following cases:

- Route doesn't match
- CanActivate returns `false`
- CanDeactivate returns `false`

This might not all be implemented the same way.

**Comment by IgorMinar** [comment]
Scenario to support: canActivate returns false because it's tried to fetch a data and the data was not found. now rather than displaying the component we want to redirect to an item not found view that can be parameterized with item ID/name.

**Comment by tamascsaba** [comment]
My use case: I want to redirect to Login page, when CanActivate returns ```false```

**Comment by tamascsaba** [comment]
@btford when you'll have time resolve this issue?

**Comment by btford** [comment]
@tamascsaba maybe early next week. I'll update this issue as I make progress.

**Comment by rolandjitsu** [comment]
@tamascsaba I have the same scenario in mind, this feature would be very nice to have :+1:

**Comment by Krustie101** [comment]
I do not think the "is authenticated" check should be done in the CanActivate handler. It is not the concern of the CanActivate handler of a specific component. And you would have to put it on every component that is a routing target. And how would you distinguish between a "no data present" and a "not authenticated" event?

In the ui-router you have a stateChangeStart event. A similar concept seems to be  missing in the angular 2 router, maybe for good reasons? After all, it is already possible to listen to "navigation finish" events.

But I would be wary of giving access to the Router service in  a handler (CanActivate or startNavigation handler) in order to change the routing, this could get tricky. At first glance, it seems cleaner if such a navigationStart handler should be able to return something that the router resolves to a new (navigation) Instruction that overrides the original one in exceptional case like an authentication check.

**Comment by janneromell** [comment]
Agree with @Krustie101. Why put a decorator like CanActivate on every component. And also, doing this there seems to be no way to do a redirect to say a login page (since I cannot DI a router etc).
Why not instead put all this into the router definitions and the router configuration?
Let me specify which routes needs authentication, or even better - more generic - which routes I would like to provide a hook to. Then let me add this hook to the router config.

I'm not sure I'm not stepping on anyone toes, but I think the way Aurelia has implemented this looks nice. See http://aurelia.io/docs.html#customizing-the-navigation-pipeline

**Comment by btford** [comment]
> Why put a decorator like CanActivate on every component

You wouldn't have to put this on every component. You can always make a "parent" route that has this behavior.

> Let me specify which routes needs authentication, or even better - more generic - which routes I would like to provide a hook to. Then let me add this hook to the router config.

This is precisely why we have child routes.

Listening to global events and firing off redirects would break encapsulation.

**Comment by janneromell** [comment]
Ok, fair enough with where to put CanActivate, it's not a big issue.

But I must admit I didn't get the rest of your reply.

Let me explain a bit more practical what we're trying to solve, and what I think more people in the thread asked about (and a bunch of discussions on other pages).

If a user types in any URL, and is not authenticated. I interpreted CanActivate as a place to check for if authenticated and if not return false. However, I would also like to redirect the user to a login page when this happens. (Note: not using this for "real" security, more as a view filter. Data is secured by server). I can do this by extending RouterOutlet and overrride activate and then use the router to navigate somewhere else. However this seems wrong for several reasons; one being it's to late, the view will have rendered and will flash very quickly on the screen before the login.
When the user then has logged in, I would like to navigate to the first typed URL.

What is CanActivate for then, and how to use it? 
Can't get to the Router in CanActivate decorator since it doesn't support DI)

Interpreted Igor's post above that CanActivate is to redirect to another view when the component decorated can't get it's data.

I still feel it would be elegant if the router could handle all this by configuration.
Any best practice how to do the scenario above?
Is it too early, given the alpha status?

Keep up the good work!

**Comment by fxck** [comment]
I can relate to @janneromell 

I would have liked this approach more https://github.com/Narzerus/angular-permission where you define whether a (predefined) role can activate the component in `RouteConfig`, and if not, where to redirect him.

```
        permissions: {
          only: ['logged_in'],
          redirectTo: 'login'
        }
``` 

replicating that in angular2 shouldn't even be that hard, but as far as I know, you can't really hook into and prevent route change and handle it yourself.. since, uh, we have CanActivate.

**Comment by dbettini** [comment]
@btford Not sure if I understand, but when you say "parent route that has this behavior", are you referring to creating a class which will be extended by all protected routers? For example, let's say we have our App router on root level, which has 3 child routers (/protected1/..., /protected2/..., /public/...). Would I have to put CanActivate on both Protected1 and Protected2, or would it be possible to create a BaseProtected which would be extended by both, and put the behavior there? I'm asking this because decorators can't be inherited as far as I know, so I don't see a way to do that, but I'm new to decorators so maybe I'm wrong.

**Comment by pebezo** [comment]
@mhevery Was this feature "lost" in the beta 2-3 transition? It looks like it was assigned to beta.02, but that milestone has passed...

**Comment by tamascsaba** [comment]
Good question @pebezo, i'm interested in too :+1:

**Comment by shawn-northrop** [comment]
New to the Party, and Angular2, But I am also looking for an implementation as described by @janneromell

> If a user types in any URL, and is not authenticated. I interpreted CanActivate as a place to check for if authenticated and if not return false. However, I would also like to redirect the user to a login page when this happens. (Note: not using this for "real" security, more as a view filter. Data is secured by server).

**Comment by wardbell** [comment]
There are answers to the question "How do I use `CanActivate` to handle authentication?" in issue #4112.

You can redirect from within `CanActivate` with `router.navigate([`SomeRoute'])`.  This presupposes that you have access a router ... which is also explained in #4112.

I don't mean to suggest that these approaches are ideal ... or even acceptable. But you can do it.

**Comment by steven-fernandez** [comment]
Isn't this done by setting the route path to: " path: /** " (without the quotes)   ?
Can anyone confirm?

**Comment by mhevery** [comment]
This is obsolete, and no longer relevant / actionable. To keep our issues clean, we are aggressively closing them.

Covered by the latest router.
