### ISSUE TITLE
ivy-ngcc (8.0.0-beta.11): ng2-dragula.js.__ivy_ngcc_bak with an ngcc back up file, which is disallowed

### ISSUE THREAD

**Issue by vladimiry** [angular/angular#29703]
# 🐞 bug report

### Affected Package

 The issue is caused by package @angular/compiler-cli (ivy-ngcc)

### Description

`npx ivy-ngcc -l debug` execution ends up with the following output:
```
Compiling @angular/core : fesm2015 as esm2015
Compiling @angular/core : fesm5 as esm5
Compiling @angular/core : esm2015 as esm2015
Compiling @angular/core : esm5 as esm5
Compiling @angular/common : fesm2015 as esm2015
Compiling @angular/common : fesm5 as esm5
Compiling @angular/common : esm2015 as esm2015
Compiling @angular/common : esm5 as esm5
Compiling @angular/common/http : fesm2015 as esm2015
Compiling @angular/common/http : fesm5 as esm5
Compiling @angular/common/http : esm2015 as esm2015
Compiling @angular/common/http : esm5 as esm5
Compiling @angular/common/http/testing : fesm2015 as esm2015
Compiling @angular/common/http/testing : fesm5 as esm5
Compiling @angular/common/http/testing : esm2015 as esm2015
Compiling @angular/common/http/testing : esm5 as esm5
Compiling @angular/common/testing : fesm2015 as esm2015
Compiling @angular/common/testing : fesm5 as esm5
Compiling @angular/common/testing : esm2015 as esm2015
Compiling @angular/common/testing : esm5 as esm5
Compiling @angular/core/testing : fesm2015 as esm2015
Compiling @angular/core/testing : fesm5 as esm5
Compiling @angular/core/testing : esm2015 as esm2015
Compiling @angular/core/testing : esm5 as esm5
Compiling @angular/platform-browser : fesm2015 as esm2015
Compiling @angular/platform-browser : fesm5 as esm5
Compiling @angular/platform-browser : esm2015 as esm2015
Compiling @angular/platform-browser : esm5 as esm5
Compiling @angular/platform-browser-dynamic : fesm2015 as esm2015
Compiling @angular/platform-browser-dynamic : fesm5 as esm5
Compiling @angular/platform-browser-dynamic : esm2015 as esm2015
Compiling @angular/platform-browser-dynamic : esm5 as esm5
Compiling @angular/platform-browser/testing : fesm2015 as esm2015
Compiling @angular/platform-browser/testing : fesm5 as esm5
Compiling @angular/platform-browser/testing : esm2015 as esm2015
Compiling @angular/platform-browser/testing : esm5 as esm5
Compiling @angular/compiler/testing : fesm2015 as esm2015
Compiling @angular/compiler/testing : fesm5 as esm5
Compiling @angular/compiler/testing : esm2015 as esm2015
Compiling @angular/compiler/testing : esm5 as esm5
Compiling @angular/platform-browser-dynamic/testing : fesm2015 as esm2015
Compiling @angular/platform-browser-dynamic/testing : fesm5 as esm5
Compiling @angular/platform-browser-dynamic/testing : esm2015 as esm2015
Compiling @angular/platform-browser-dynamic/testing : esm5 as esm5
Compiling ng2-dragula : fesm2015 as esm2015
Compiling ng2-dragula : fesm5 as esm5
Compiling ng2-dragula : esm2015 as esm2015
Compiling ng2-dragula : esm5 as esm5
Compiling ng2-dragula : fesm2015 as esm2015
Error: Tried to overwrite /dev/temp/ivy-ngss-duplicated-entries/node_modules/ng2-dragula/dist/fesm2015/ng2-dragula.js.__ivy_ngcc_bak with an ngcc back up file, which is disallowed.
    at InPlaceFileWriter.writeFileAndBackup (/dev/temp/ivy-ngss-duplicated-entries/node_modules/@angular/compiler-cli/ngcc/src/writing/in_place_file_writer.js:37:23)
    at /dev/temp/ivy-ngss-duplicated-entries/node_modules/@angular/compiler-cli/ngcc/src/writing/in_place_file_writer.js:31:69
    at Array.forEach (<anonymous>)
    at InPlaceFileWriter.writeBundle (/dev/temp/ivy-ngss-duplicated-entries/node_modules/@angular/compiler-cli/ngcc/src/writing/in_place_file_writer.js:31:30)
    at /dev/temp/ivy-ngss-duplicated-entries/node_modules/@angular/compiler-cli/ngcc/src/main.js:95:36
    at Array.forEach (<anonymous>)
    at Object.mainNgcc (/dev/temp/ivy-ngss-duplicated-entries/node_modules/@angular/compiler-cli/ngcc/src/main.js:67:21)
    at /dev/temp/ivy-ngss-duplicated-entries/node_modules/@angular/compiler-cli/ngcc/main-ngcc.js:60:20
    at /dev/temp/ivy-ngss-duplicated-entries/node_modules/@angular/compiler-cli/ngcc/main-ngcc.js:4:17
    at Object.<anonymous> (/dev/temp/ivy-ngss-duplicated-entries/node_modules/@angular/compiler-cli/ngcc/main-ngcc.js:10:3)

```

## 🔬 Minimal Reproduction

1. create package.json:
```json
{
  "name": "ivy-ngss-duplicated-entries",
  "version": "1.0.0",
  "main": "index.js",
  "license": "MIT",
  "dependencies": {
    "@angular/common": "8.0.0-beta.11",
    "@angular/compiler": "8.0.0-beta.11",
    "@angular/core": "8.0.0-beta.11",
    "@angular/platform-browser": "8.0.0-beta.11",
    "@angular/platform-browser-dynamic": "8.0.0-beta.11",
    "rxjs": "6.4.0",
    "zone.js": "0.9.0"
  },
  "devDependencies": {
    "@angular/compiler-cli": "8.0.0-beta.11",
    "@types/node": "8.9.4",
    "ng2-dragula": "2.1.1",
    "typescript": "~3.3.3333"
  }
}
```
2. install dependencies (yarn / npm i)
3. execute `npx ivy-ngcc -l debug`

**Anything else relevant?**

- See attached [entryPoints-debug.png](https://user-images.githubusercontent.com/1560781/55541228-38a2f980-56cd-11e9-97bf-d869b5ea9ca1.png) and [entryPoints-output.json.txt](https://github.com/angular/angular/files/3042483/entryPoints-output.json.txt) files (debug screenshot and `entryPoints` array dump).
- See `ng2-dragula` files listing here https://yarnpkg.com/en/package/ng2-dragula?files

So it looks like `entryPoints` array includes duplicated `ng2-dragula` entries (see 2 last items of the array).

CC @petebacondarwin

**Comment by petebacondarwin** [comment]
This is due to the ng2-dragula package unfortunately having two copies of `package.json` and `ng2-dragular.metadata.json` which both point to the same files. One is at the root of the package and one is in the `dist` folder. This makes the `ng2-dragular/dist` an Angular entry-point as well.

Because they both point to the same source files, ngcc is trying to compile the same source twice.

I think the right solution would be to ask `ng2-dragular` to release a version that only has one lot of `package.json` files.

**Comment by petebacondarwin** [comment]
Or perhaps it is time for us to implement the `.ivy-ngcc.json` file that allows us to configure ngcc.

This case would be covered by an array of file paths (globs?) to ignore, so that we don't pick them up as entry-points.

@alxhub what do you think?

**Comment by vladimiry** [comment]
> ng2-dragula package unfortunately having two copies of package.json and ng2-dragular.metadata.json

I see only one `ng2-dragular.metadata.json` file. But I understand that it's being resolved twice due to the following logic: https://github.com/angular/angular/blob/b6f48dbe19eac8bce7b33e15e334fb2fd6739e67/packages/compiler-cli/ngcc/src/packages/entry_point.ts#L91

**Comment by petebacondarwin** [comment]
Right. Yes @vladimiry - you are correct. The problem is caused by the second `dist/package.json`, which is referring to the same files as the top level package.json.

The good news, in the short-term, is that the ngcc compilation does complete. Even if it didn't a workaround is to run ngcc a second time, in which case the ng2-dragula will be skipped as it has now been compiled and any further packages that ngcc never go to on the first run will be compiled.

I think we will implement an option to ignore such unwanted package.json files.

**Comment by vladimiry** [comment]
I just placed related issue here https://github.com/valor-software/ng2-dragula/issues/951 Let's see maybe package.json has been shipped twice without specific intention.

**Comment by konsultaner** [comment]
I'm not sure wether this is related but I get the following error:

```
Compiling @angular/material/form-field : es2015 as esm2015
Date: 2019-06-04T09:33:19.041Z - Hash: 4a3e090265fc644f2d3c - Time: 38204ms
6 unchanged chunks

ERROR in Tried to overwrite c:/<path to ptoject>/node_modules/@angular/material/form-field/typings/error.d.ts.__ivy_ngcc_bak with an ngcc back up file, which is disallowed.
i ｢wdm｣: Failed to compile.
```

Any idea where to start from here to find the issue?

**Comment by petebacondarwin** [comment]
What version of Angular are you using? For trying out IVY you need to use `@angular/compiler-cli@next` etc - i.e. not 8.0.1.

**Comment by konsultaner** [comment]
I did use `@angular/compiler-cli@next`

**Comment by fclemonschool** [comment]
I have same error with ngx-simple-modal.

I use this versions.
```
"@angular/core": "^8.1.0-rc.0
"@angular/compiler-cli": "https://github.com/angular/compiler-cli-builds
"ngx-simple-modal": "^1.3.13
```

**Comment by leblancmeneses** [comment]
I'm using ng-packagr to package my library following this reference sample:
https://github.com/ng-packagr/ng-packagr/tree/master/integration/samples/secondary

This allows me to setup a similar format to angular material exports:

```
import {FlipBoxModule} from 'fxme/flip-box';
import {PrettyBoxModule} from 'fxme/pretty-box';
import {ParallaxModule} from 'fxme/parallax';
```

The above works without ivy.

Enabling Ivy results in similar error message as described by OP.

The sample shows all the package.json files that will be put into dist.  Simply removing them ```  find . -mindepth 2 -name \"package.json\" -type f -delete  ``` results in other errors "Cannot find module" later.

I would prefer an explicit solution as described in https://github.com/angular/angular/issues/29703#issuecomment-479968051 that would allow me to override the default behavior.

for now I disable ivy because it works without it.

Thanks

**Comment by petebacondarwin** [comment]
The configuration option mentioned in https://github.com/angular/angular/issues/29703#issuecomment-479968051 is actually available and works for ng-dragula.  You can place the following in a file called `ngcc.config.js` at the root of the application project:

```ts
module.exports = {
  packages: {
    'ng2-dragula': {
      entryPoints: { './dist': { ignore: true, } },
    },
  }.
};
```

And ngcc will ignore the "false" entry-point under `dist`.

@leblancmeneses - if you are using ngpackagr with standard settings then the output should be compatible with ngcc.  Can you provide a reproduction of the problem for us to look into?

**Comment by alessiostalla** [comment]
I was getting the same error: `ERROR in Tried to overwrite /home/alessio/projects/portofino5/ui/dist/portofino/lib/portofino.service.d.ts.__ivy_ngcc_bak with an ngcc back up file, which is disallowed.`. My project was created with Angular 6 (IIRC), then a library added manually (there were no schematics yet) and the project ported to Angular 7, then 8, over time, with ng update.

I tried with your `ngcc.config.js` suggestion. However, I had to use `'./dist/<lib-name>'` instead of `'./dist'` alone. With that, the "ngcc back up file" error goes away. However, then I get a number of warnings like `WARNING in /home/alessio/projects/portofino5/ui/projects/portofino/src/lib/content.directive.ts is part of the TypeScript compilation but it's unused.` and when launching the app with `ng serve` I get: `Error: StaticInjectorError(Platform: core)[CompilerFactory]: NullInjectorError: No provider for CompilerFactory!` so something is definitely not working as it should.

**Comment by gkalpak** [comment]
While ng2-dragula@2.1.1 is [still shipping][1] with two `package.json` files, it now seems to be compiling fine, but fails at runtime with `ReferenceError: global is not defined` (according to the CI logs in the [ngcc-validation][2] repo - e.g. [build 1083#1][3]).

[1]: https://unpkg.com/browse/ng2-dragula@2.1.1/
[2]: https://github.com/angular/ngcc-validation
[3]: https://circleci.com/gh/angular/ngcc-validation/1083#tests/containers/1

**Comment by petebacondarwin** [comment]
The `global is not defined` error is expected because we have not configured the test project correctly. See https://github.com/valor-software/ng2-dragula#1-important-add-the-following-line-to-your-polyfillsts

**Comment by vladimiry** [comment]
> While ng2-dragula@2.1.1 is still shipping with two package.json files, it now seems to be compiling fine

> The global is not defined error is expected

The issue is considered as resolved then.
