### ISSUE TITLE
Reactive form child ControlValueAccessor control's pristine is broken when parent group is disabled and reenabled

### ISSUE THREAD

**Issue by nader-eloshaiker** [angular/angular#29759]
# 🐞 bug report

### Affected Package
@angular/forms

### Description
The issue I am observing is that the pristine property of a custom formControl component (containing a collection of formControls in a child formGroup) using CVA does not update under a specific scenario.

The scenario being, if the parent formGroup that the custom control resides in, is disabled on ```ngOnInit``` and then later enabled with user interaction.

The workaround I have used is to execute ```markAsPristine()``` when the parent formGroup is reset and when enabling based on the pristine value of the child formGroup.

## 🔬 Minimal Reproduction
- Create a parent class with a formGroup in a reactive form.
- Attach a custom formControl using a CVA component to the formGroup.
- In the parent class containing, disable the formGroup using ```formGroup.disable()```
- Add a button to enable the formGroup.
- When the user clicks the button to enable the group, the child CVA component will show that that it is NOT pristine even though it has not been modified or touched.

A working example to demonstrate the issue:
* I have reactive form called "billing-info" with a parent formGroup called "netedForm".
* I have a custom form control using CVA called "basic-info" that resided inside the "nestedForm" group.
* Clicking on enable still shows the "basic-info" as NOT pristine.
https://stackblitz.com/edit/angular-nested-forms-cva-z2ch7f

## 🌍  Your Environment

**Angular Version:**
<pre><code>
Angular CLI: 7.2.4
Node: 9.11.2
OS: darwin x64
Angular: 7.2.12
... animations, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.12.4
@angular-devkit/build-angular     0.13.8
@angular-devkit/build-optimizer   0.13.8
@angular-devkit/build-webpack     0.13.8
@angular-devkit/core              7.2.4
@angular-devkit/schematics        7.2.4
@angular/cdk                      7.3.7
@angular/cli                      7.2.4
@angular/flex-layout              7.0.0-beta.24
@angular/material                 7.3.7
@ngtools/webpack                  7.3.8
@schematics/angular               7.2.4
@schematics/update                0.12.4
rxjs                              6.4.0
typescript                        3.2.4
webpack                           4.29.0
    

</code></pre>

**Anything else relevant?**

**Comment by kara** [comment]
@nader-eloshaiker This seems to be due to how your CVA is set up. You have the `registerOnChange` callback hooked up to the `valueChanges` observable, so every time valueChanges emits an event, you tell the forms API that a change has occurred in the UI (which marks the form dirty).  

In `writeValue`, the CVA correctly sets `emitEvent` to false (this keeps it from becoming dirty on initialization), but when you disable the control in the CVA's `setDisabledState` method, the `emitEvent` option isn't passed.  So a valueChanges event is emitted, which sets your form to dirty.

You can fix it by passing the option, see https://stackblitz.com/edit/angular-nested-forms-cva-51zhu4?file=src/app/basic-info/basic-info.component.ts
