### ISSUE TITLE
TypeScript + AtScript instead of ES7?

### ISSUE THREAD

**Issue by diestrin** [angular/angular#2977]
I new the reasons you guys decided to pick TS+@script instead of plain javascript, even when there's an option to write NG2.0 in plain javascript.

But given that ES7 has @decorator syntax, can just Angular move to standard instead of using an external tool?

If not, what are the reasons?

**Comment by vicb** [comment]
ES6 has just been approved (e/o June) and no current browser fully supports it.

While ES release cycles should be faster starting from now, ES7 is not a thing today - there is no other option as using a transpiler for now.

**Comment by caitp** [comment]
The (various, changing) decorators proposals (i.e. https://github.com/wycats/javascript-decorators) are in their early stages, and may not necessarily ever be ratified.

That said, projects like Angular2, Ember, Aurelia, and plenty of others, which choose to rely on these features through compile-to-js toolchains (like TypeScript), help inform the technical committee that there's a (admittedly questionable) need for these features. So you could say angular2 is helping to push the proposal along and helping it to gain wider adoption, so that in the future these toolchains aren't needed. That's worth something, right?

**Comment by diestrin** [comment]
@vicb yeah I know that browser support is not optimal right now, but even using it and using Babel as the transpiler, gives a much more wider support to ES6/7 now. 
Check https://kangax.github.io/compat-table/es6/ and you'll see Babel has more support than Typescript.

Difference? Babel uses actual standard syntax instead of custom Typescript syntax.
