### ISSUE TITLE
Router should be able to mix path and hash routing strategy

### ISSUE THREAD

**Issue by Akxe** [angular/angular#29833]
# 🚀 feature request

### Relevant Package
This feature request is for @angular/router

### Description
Sometimes you might want the app to use both locations strategies.
`example.com/rootFolder/images/gallery?sort=mane#/lightbox/file`

### Describe the solution you'd like
```{
		path: '#/lightbox/!fileSlug,
		component: LightBoxComponent,
		outlet: 'light-box',
},```

### Describe alternatives you've considered
I have tried using URLMatcher, fought on doing it manually, but it has many flaws. I searched for 
`mix path and hash routing strategy` and similar.

**Comment by jasonaden** [comment]
Thanks for the feature request. However, the location strategy is built in at a pretty low level. I think in order to build what you're looking for, it would require a new location strategy that can somehow support both.

You should feel free to create this and use it in your application. However, path and hash strategies satisfy most use cases that are requested by the framework.
