### ISSUE TITLE
Rename form validation error for requiredTrue Validator

### ISSUE THREAD

**Issue by nayfin** [angular/angular#29836]
# 🚀 feature request

### Relevant Package

 This feature request is for @angular/forms

### Description
The `required` and `requiredTrue` validators send the same error object when the form control is invalid. We are setting up a system to map the validator error object to a library of form messages, with current naming conventions the is not a way for us to differentiate between these two form errors and map the messages properly.

### Describe the solution you'd like
I would like to rename the error object from `required` to `requiredTrue` for the `requiredTrue` `Validator`. I can take this on, as it is a simple fix. It will create breaking changes for anyone using error key to form validation messages, though it would be a quick fix for those users and further empower them to  display accurate error messages.

### Describe alternatives you've considered
Currently we are using a custom Validator that is a copy/paste of the source for `requiredTrue` validator with the suggested changes.

**Comment by kara** [comment]
@nayfin Unfortunately, I think this would be quite a large breaking change for the community. We would need to see more buy-in from others that this is something many projects want before breaking everyone.  Since there hasn't been any traction or comments in a few months, I don't think this meets the threshold, so I'm closing this issue for the time being.  If we see that this is a larger user request later on, we can always re-open it.
