### ISSUE TITLE
Shady DOM breaks angular router in Edge

### ISSUE THREAD

**Issue by Kartik1607** [angular/angular#29900]
Referencing https://github.com/webcomponents/shadydom/issues/330 since not sure if issue related to ShadyDOM or Angular.

**Comment by pkozlowski-opensource** [comment]
There is no point of tracking the same issue in 2 repositories - you've determined that the problem in the Angular app happens upon including the mentioned library and the issue is tracked in there.

We are more than happy to investigate if you can reproduce this bug in Angular alone, without 3rd party deps.
