### ISSUE TITLE
Lazy-loading with new import syntax throws in AoT when routes are exported

### ISSUE THREAD

**Issue by cexbrayat** [angular/angular#29959]
# 🐞 bug report

### Affected Package
The issue is caused by package @angular/compiler

### Is this a regression?

No

### Description

When using the new lazy-loading import syntax with VE, if the lazy-loaded route is declared in a separate file, then the AoT compilation fails.

## 🔬 Minimal Reproduction

A repo is available to reproduce: https://github.com/cexbrayat/lazy-laoding-import

Running `ng build --aot` will trigger the error.

Basically, the problem happens when the routes are declared in a separate file:
https://github.com/cexbrayat/lazy-laoding-import/blob/master/src/app/app.routes.ts#L3-L6

Note that if the routes are declared directly in `app;module.ts` the error does not occur.

## 🔥 Exception or Error
<pre><code>
ERROR in src/app/app.module.ts(14,26): Error during template compile of 'AppModule'
  Function expressions are not supported in decorators in 'ROUTES'
    'ROUTES' contains the error at src/app/app.routes.ts(5,29)
      Consider changing the function expression into an exported function.
</code></pre>

## 🌍  Your Environment

**Angular Version:**
<pre><code>
Angular CLI: 8.0.0-beta.15
Node: 11.11.0
OS: darwin x64
Angular: 8.0.0-beta.13
... animations, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.800.0-beta.15
@angular-devkit/build-angular     0.800.0-beta.15
@angular-devkit/build-optimizer   0.800.0-beta.15
@angular-devkit/build-webpack     0.800.0-beta.15
@angular-devkit/core              8.0.0-beta.15
@angular-devkit/schematics        8.0.0-beta.15
@angular/cli                      8.0.0-beta.15
@ngtools/webpack                  8.0.0-beta.15
@schematics/angular               8.0.0-beta.15
@schematics/update                0.800.0-beta.15
rxjs                              6.4.0
typescript                        3.4.3
webpack                           4.29.6
</code></pre>

**Anything else relevant?**

This is about the VE support, the Ivy version works fine.

cc @filipesilva as we talked about on Slack.

**Comment by alexzuza** [comment]
Angular compiler supports lowering expessions like useValue, useFactory, data, id and loadChildren.

What happens here is that if you keep loadChildren expression in `app.module.ts` file or more precisely inside decorator (@NgModule)  then compiler extracts your loadChildren expression in exported variable before processing AOT.

```

export const ɵ0 = () => import('./admin/admin.module').then(m => m.AdminModule);

@NgModule({
  ...
  imports: [
    ...
    RouterModule.forRoot([
      { path: '', loadChildren: ɵ0  }
    ])
  ],
})
export class AppModule { }
```
On the other hand, if you keep it as a part of exported variable in app.routes.ts file then compiler can't lower it due to the this restriction:

https://github.com/angular/angular/blob/83291f01b084b834d8375ff5ac2366fb47ca15c0/packages/compiler-cli/src/transformers/lower_expressions.ts#L226-L228

How can we remedy this? 

With a simple hack:

**app.routes.ts**
```
const ROUTES: Routes = [
  // { path: '', loadChildren: './admin/admin.module#AdminModule' }
  { path: '', loadChildren: () => import('./admin/admin.module').then(m => m.AdminModule) }
];

export { ROUTES };
```
This way compiler will lower loadChildren expression since it is not part of exported variable in AST structure.

**Comment by alexeagle** [comment]
The issue is that latest release of Angular CLI updates all the old string-typed loadChildren when you run `ng update` so we need a principled replacement that is easy to perform and doesn't make a mess in users code.
Maybe your trick to move the `export` keyword to a separate statement is a way forward.

**Comment by filipesilva** [comment]
I think @alexzuza's approach is pretty nice. But if that's what a user should do to get around the `ngc` limitation, then the `ngc` should suggest this approach explicitly. Users making new routes will also run into this in the future.

**Comment by alexeagle** [comment]
I think the error reporting in ngc needs to be improved too.
Optionally we could make the fixer smarter so that users don't end up with these dynamic imports.

**Comment by chan18** [comment]
I want to fix this can I?

**Comment by cexbrayat** [comment]
Should be fixed by #30038 which will be available in `8.0.0-rc.0`. I'll reopen if that's not the case.

**Comment by alastair-todd** [comment]
@cexbrayat I think this needs to be reopened for the use-case when the module that is being imported is coming from a shared library:

> ERROR in ./src/app/app-routing.module.ts
> Module not found: Error: Can't resolve './../../../../dist/shared-modules/lib/auth-n/auth-n.module.d.ngfactory' in 'C:\_dev\my-workspace\projects\elc\src\app'

Only when using `ng build` with  `--configuration production`

from code

```
{
    path: "auth",
    loadChildren: () => import("shared-modules").then(m => m.AuthNModule)
}
```
where `shared-modules` is a library, and that is the `path `in `tsconfig` and

`export * from "./lib/auth-n/auth-n.module";`

is in the shared-modules `public-api.ts`

FWIW `auth-n.module.d.ngfactory` really doesn't exist in that dist folder, but `auth-n.module.d.ts` does.

> Angular CLI: 8.0.4
> Node: 10.16.0
> OS: win32 x64
> Angular: 8.0.3
> ... animations, common, compiler, compiler-cli, core, forms
> ... language-service, platform-browser, platform-browser-dynamic
> ... router
>

**Comment by filipesilva** [comment]
@alastair-todd I don't think that case ever worked really. We've had https://github.com/angular/angular-cli/issues/6373 open for a while. I think it will work out of the box with Ivy though, but haven't tested.

**Comment by alastair-todd** [comment]
@filipesilva is it possible any other way - that is, lazyloading a local library module? I think the use-case is fine - its an Authentication and Authorization module used by all of our apps...

I seem to remember being forced down the import route in the first place as the classic lazyload syntax was failing for libraries too....in the latest ng 8.0

**Comment by filipesilva** [comment]
I think the usecase is very legitimate, it's just that we never managed to get it working well without Ivy, and then with Ivy there shouldn't be a problem. The last comment (https://github.com/angular/angular-cli/issues/6373#issuecomment-453006158) also has a workaround for now that should work. Basically wrapping the lib module import in an app lazy module.

**Comment by gioragutt** [comment]
@filipesilva I'm now facing the same problem. I've trying to implement a lazy-loading solution for feature modules (think of combining @ngrx/effects and @angular/router). When I compile with AOT,
The `import` does not return an NgModuleFactory, and I can't use the `Compiler` because this is AOT.

Just for comparison, this is the source module code:

```typescript
import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';
import { Feature1FormComponent } from './feature1-form/feature1-form.component';
import { LazyFeatureConfig, LazyFeatureModule } from 'projects/lazy-feature';

const featureModuleConfig: LazyFeatureConfig = {
  forms: [
    {
      category: 'Category 1',
      component: Feature1FormComponent,
      name: 'Feature1FormComponent',
    }
  ],
};

@NgModule({
  declarations: [Feature1FormComponent],
  imports: [
    CommonModule,
    LazyFeatureModule.forFeature(featureModuleConfig)
  ],
  entryComponents: [Feature1FormComponent],
})
export class Feature1Module { }
```

Whereas the bundled file contains no such code:

```
(window.webpackJsonp = window.webpackJsonp || []).push([
  [3],
  {
    hzZp: function(n, u, o) {
      'use strict';
      o.r(u),
        o('s6Gf'),
        o.d(u, 'Feature1Module', function() {
          return t;
        });
      var t = (function() {
        return function() {};
      })();
    },
  },
]);
```

Seems like it's getting rid of the ENTIRE module :(
[This is my repo](https://github.com/gioragutt/lazy-loaded-feature-modules-poc/tree/aot-fixes), specifically in the `aot-fixes` branch.

I'd like to discuss about this if possible.

**Comment by gioragutt** [comment]
@filipesilva see #32194
