### ISSUE TITLE
docs: add future deprecations to Deprecation Summary

### ISSUE THREAD

**Issue by jenniferfell** [angular/angular#30100]
# 📚 Docs or angular.io bug report

### Description
There are a few places in the guides and API comments where we forecast possible deprecations. One example is in Router guide. Another is here: 'angular/packages/core/src/render3/definition.ts'

Should we include them in Deprecation Summary?
Should we have a state such as "likely to be deprecated in the future" or just commit to these as okay or deprecated. No in-between forecast state?

 A clear and concise description of the problem...

### What's the affected URL?**
 https://angular.io/...

## 🔥 Exception or Error
<pre><code>

</code></pre>

**Comment by jenniferfell** [comment]
See https://github.com/angular/angular/pull/26733#discussion_r278042074

**Comment by kapunahelewong** [comment]
Status: docs team will need to partner with an engineer on what to add, if there could/should be a cycle of adding them, and where to add them.

**Comment by AndrewKushnir** [comment]
From engineering perspective we put all deprecations-related info to the https://angular.io/guide/deprecations page. The `packages/core/src/render3/definition.ts` file (mentioned in the issue description) contains some ideas about future deprecations, but it's not actionable at this moment, so this information should not be referenced anywhere yet.

I will close this ticket for now (since there is a place for deprecation info), please reopen if needed. Thank you.
