### ISSUE TITLE
ReactiveForms formGroup.reset doesn't set value to default

### ISSUE THREAD

**Issue by GeorgeTailor** [angular/angular#30147]
# 🐞 bug report

### Affected Package
@angular/forms

### Is this a regression?
No.

### Description

`formGroup.reset()` can accept an object with values of form controls to reset them to. When setting value for `<input type="date"/>` it doesn't work.

## 🔬 Minimal Reproduction
https://stackblitz.com/edit/angular-ehihba?file=src%2Fapp%2Fapp.component.ts

Click `reset form` and the default value will not be applied.
As a side note: when you manually change the value and then click `reset` it will fall back to default value, but if you click it again it will remove input value.

## 🌍  Your Environment

**Angular Version:**
<pre><code>
Angular CLI: 7.3.5
Node: 10.10.0
OS: darwin x64
Angular: 7.2.12
... animations, common, compiler, compiler-cli, core, forms
... http, language-service, platform-browser
... platform-browser-dynamic, router

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.13.5
@angular-devkit/build-angular     0.13.8
@angular-devkit/build-optimizer   0.13.8
@angular-devkit/build-webpack     0.13.8
@angular-devkit/core              7.3.5
@angular-devkit/schematics        7.3.5
@angular/cdk                      7.3.7
@angular/cli                      7.3.5
@angular/material                 7.3.7
@angular/pwa                      0.13.8
@angular/service-worker           7.2.13
@ngtools/webpack                  7.3.8
@schematics/angular               7.3.5
@schematics/update                0.13.5
rxjs                              6.4.0
typescript                        3.2.4
webpack                           4.29.0

</code></pre>

**Comment by Airblader** [comment]
Your code has two issues:

1. You shouldn't use *both* `value` and `formControlName` as they both try to set the same property.
2. The main issue, however, is that `input[type="date"]` expects `value` to be a *string* in the format `yyyy-mm-dd`, but you are trying to pass an instance of `Date`. This is simply not allowed¹.

In other words, no bug here, just an incorrect usage of `input`. Note that there isn't anything Angular can do: if the ControlValueAccessor were to accept `Date` inputs, we'd still not be able to convert view changes from a string to such an object (since the CVA cannot know what the user wants, and always choosing `Date` would be a breaking change), so while it would fix *writing* the value, it would just cause further issues down the road.

If you want to use it with Date objects, you could simply write your own ControlValueAccessor for these inputs (Angular will prefer any custom CVA over its own) which does the proper conversions as you like. This is pretty straight-forward.

¹ https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/date

**Comment by GeorgeTailor** [comment]
I am not passing instance of date, but a string with a help of interpolation and date pipe 
`value="{{form.get('dateControl').value | date:'yyyy-MM-dd'}}"`.
I disagree that there is nothing to do on behalf of angular, as I mentioned in the bug report, when the date is set and I click on `reset` button the date is properly set to default value specified in object supplied to `reset` function. But when the value itself is a default one Angular simply removes it.

**Comment by Airblader** [comment]
`formControlName` already activates the ControlValueAccessor which writes the form value into the component. By adding an extra `value` you are just implementing a second way to write the value, which will likely just break things.

**Comment by Airblader** [comment]
You *could* get it to work if you removed `formControlName`, keep your `value` and also add a `(input)` binding which parses the DOM string to a `Date` and calls `form.get('dateControl').patchValue`.

That's pretty hacky, though, and you'd be much better off implementing your own ControlValueAccessor for this.

**Comment by GeorgeTailor** [comment]
Ok, thanks for your input, I'll try it out on Monday.

**Comment by Airblader** [comment]
Here's a quick and dirty proof of concept: https://stackblitz.com/edit/angular-3xjuqx

**Comment by Airblader** [comment]
A proposal for Angular itself would perhaps be to implement such a specific ControlValueAccessor, but extend its selector to match on some `ngInputDate` attribute to preserve compatibility. Not sure the core team would like this, though.

**Comment by Airblader** [comment]
… at which point this becomes a duplicate of #8203

**Comment by GeorgeTailor** [comment]
@Airblader any example with a reactive input without ngModel ? I would like to avoid mixing template and reactive driven forms.

**Comment by Airblader** [comment]
Can you elaborate? I don't understand your question.

**Comment by GeorgeTailor** [comment]
Much cleaner solution - https://stackblitz.com/edit/angular-9gbgka?file=src%2Fapp%2Fapp.component.ts.
Passing date string to `formControl` with help of `import { formatDate } from '@angular/common';`. If the date object is needed then it would be as trivial as `new Date(this.form.get('dateControl').value)`

**Comment by GeorgeTailor** [comment]
No, I wanted `form.reset()` to set default value for `<input type="date"/>`.

I disagree that 40 lines of hard-to-read code is a clean solution. Main reasons are:
1) Rarely used API;
2) Mixing template-driven and reactive-driven forms;
3) A lot of code (directly affects the time someone needs to understand what the hell is going on here + it needs to be covered with tests).

**Comment by Airblader** [comment]
> Mixing template-driven and reactive-driven forms;

I still don't understand this point. ControlValueAccessor is used for both types of forms, it's not exclusive to template-driven ones.

> Rarely used API;

Rarely used? You use it every single time you add ngModel or formControlName. And personally I work on a UI library where a lot of components require this, not to mention I have an open source library where I implemented some as well. *shrugs*

---

In any case, I'm happy it works to your liking when using a string rather than a Date object as your form model. For anyone who would prefer a Date object (or even something else, like a Moment object), they can use a CVA.
