### ISSUE TITLE
feat(service-worker): Support ignoring specific URLs

### ISSUE THREAD

**Issue by aSegatto** [angular/angular#30195]
# 🚀 feature request

### Relevant Package
This feature request is for @angular/service-worker

### Description

While forcing the SW to ignore specific URL is now possible adding http header `ngsw-bypass` or `ngsw-bypass=true` as query param, it's not possible to specify some URLs to be ignored. This would be very useful when dealing with SDKs like Firestore, that don't allow to edit the http requests. 

### Describe the solution you'd like

As discussed in  #21191 some workarounds are possible :  [#21191 (Comment)](https://github.com/angular/angular/issues/21191#issuecomment-484586484) or [21192 (Comment)](https://github.com/angular/angular/issues/21191#issuecomment-487404742). 

Second comment also contains a suggestion on how to modify SW in order to implement the requested feature. This would mean accepting messages to allow to set a list of URLs to ignore.

**Comment by petersalomonsen** [comment]
As mentioned in https://github.com/angular/angular/issues/21191#issuecomment-487404742 I would try intercepting. If intercepting using https://angular.io/api/common/http/HttpInterceptor or the example with `XmlHttpRequest` does not work if Firestore is using the Fetch api, I believe it should be possible to intercept the Fetch api too.

Posting a map of URL's may not be sufficient either as in some cases you don't know the URL, because it's given to you as a response from another call. An example is one of my own use-cases where I'm using git for offline storage in the browser and git LFS for dealing with large files. To get the upload URL (which I want the serviceworker to bypass), I need to make a post request first, which returns the upload URL. You can see where it happens here: https://github.com/fintechneo/angular-git-filebrowser/blob/master/src/lib/gitbackend/gitbackend.service.ts#L898

In this case it's easy for me to send headers, either by intercepting or modyfing the library itself of course, but a URL map wouldn't help much. Also when introducing URL maps, you'd probably soon discover that just matching URL's isn't enough. You'd want to match URL patterns, which method is used etc. We'd end up with lot's of logic in the serviceworker for handling this, while it could probably be solved more easily in the client. In the client code you can have tailored code for intercepting and checking requests.

Thinking out loud, there's a another alternative though instead of sending a map of URL's to bypass, you could send function code to the serviceworker that it should use to check the requests. I haven't thought through what side-effects that could cause, but that would at least give you full control over the logic for bypassing the serviceworker. @aSegatto @gkalpak

**Comment by aSegatto** [comment]
I thought that sw had already some sort of glob logic, to know how to handle data api requests but if it has not, i agree it's a lot of work to do ... maybe just adding or removing urls dynamically from the map in the sw could do the trick, but of course you need to know the exact url.

**Comment by gkalpak** [comment]
Yeah, sending a function for the SW to evaluate is probably not a good idea :grin:

##
To recap:

The decision about whether to handle the request of not has to be made in a way that does not violate the following assumptions:
1. [The decision is made synchronously.][1]
2. [The SW script remains independent of the app version.][2]

One way to achieve this is by making the decision on the app side and communicating it to the SW via some form of metadata embedded into the request itself (e.g. custom query param or header - this is already supported). This will work in cases where you can control the URL/request, but there are still cases where this isn't possible (which is what this issue is about).

[1]: https://github.com/angular/angular/pull/23025#issuecomment-376662562
[2]: https://github.com/angular/angular/issues/21191#issuecomment-482197496

**Comment by petersalomonsen** [comment]
So this is where one probably could consider adding "SDK features" to the serviceworker module, so that it would be possible to compile your own `ngsw-worker.js` for plugging in URL exceptions like requested here, and / or other serviceworker features (e.g. if you want to use it for any of the use-cases described here: https://serviceworke.rs/).

This would maybe involve additions to the CLI, and also is much about documentation (serviceworker cookbook).

Is that an idea?

**Comment by petersalomonsen** [comment]
Another idea:

Add property in `ngsw-config.json`pointing to a `.js` file containing app-specific code to be executed in the serviceworker (onFetch event). That would be a simple but powerful addition that keeps the SW script independent of the app version, and does not involve code evaluation on the fly.

**Comment by gkalpak** [comment]
WRT https://github.com/angular/angular/issues/30195#issuecomment-492373860:
Although there are no immediate plans, we are considering/investigating ways to make the SW more flexible and extensible. It will take a significant refactoring, though, so not going to happen overnight :grin:

WRT https://github.com/angular/angular/issues/30195#issuecomment-492383256:
Anything involving `ngsw-config.json` is async (i.e. the SW needs to retrieve the config from the `Cache`) and thus can't be used to make a sync decision in `onFetch`.

**Comment by gkalpak** [comment]
Given the relatively low demand for this feature and the fact that there doesn't seem to be a good solution (that doesn't require a SW re-write :grin:), I am going to close this.

For anyone that absolutely needs this with the Angular ServiceWorker, there are the work-arounds referenced in the issue description (such as https://github.com/angular/angular/issues/21191#issuecomment-484586484). The more generic feature of making it possible to extend/modify the ServiceWorker logic is being tracked in other issues; in particular #21197 (and also #24387 and #26413 for the specific case of overriding `push` handling).
