### ISSUE TITLE
Classes added during AfterContentInit disappear when using interpolation for class property

### ISSUE THREAD

**Issue by MightyRevenge** [angular/angular#30199]
# 🐞 bug report

### Affected Package
@angular/core

### Is this a regression?
Unsure if it worked in previous versions.

### Description
Say in my component class I had
`nspace = 'some-unique-classname'`

In the component template:
`<div class="{{nspace}} some-class" #content>`

If I try to access the `classList` in `ngAfterContentInit` using:
`this.content.nativeElement.classList.add('new-class')`

`new-class` doesn't get added! However, if I change the component template to:
`<div [ngClass]="[nspace, 'some-class']" #content>`

Then the DOM manipulation works fine! Quite strange...

## 🔬 Minimal Reproduction
https://stackblitz.com/edit/angular-issue-repro2-nkn6lc?file=src%2Fapp%2Fapp.component.ts

## 🌍  Your Environment

**Angular Version:**
<pre><code>
Angular CLI: 7.3.7
Node: 8.15.0
OS: darwin x64
Angular: 7.2.11
... animations, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router
</code></pre>

**Comment by Airblader** [comment]
This is correct behavior. The interpolation binds the entire class list, so when change detection runs the class list is set again which removed the class you added programmatically.

**Comment by matsko** [comment]
`ngClass` is quite unpredictable and it's hard to know when it updates values because it doesn't care what existing values are on the element. This is unfortunately the state with Angular right now (pre IVY).

Ivy does this properly with all styling bindings: `[class]`, `[class.name]`, `[style]`, `[style.prop]` and also static style values. And this will be apart of Ivy once it's ready.

Closing this for now. Thank you for bringing this up.
