### ISSUE TITLE
[documentation of Upgrading from AngularJS to Angular] libraries to load in the browser

### ISSUE THREAD

**Issue by eetievent** [angular/angular#30249]
### Description
When upgrading from AngularJS to Angular, it may be needed to declare the libraries to load in the browser in _angular.js / build.options.scripts_ , including _angular.js_.
This could be added to the documentation? (Indeed the examples given are based on SystemJS but we don't use it because Angular uses already Webpack).

### What's the affected URL?
https://angular.io/guide/upgrade#bootstrapping-hybrid-applications

### Reproduction Steps
upgrade to AngularJS 1.7
remove Grunt and use angular-cli
use ngUpgrade (app.module.ts and app.module.ajs.ts)
removed _require("angular")_ (use of the AngularJS global _angular_)

### 🔥 Exception or Error
_Angular 1.x not loaded !_
generated by <code>this.upgrade.bootstrap(document.body, [App])</code>

### Anything else relevant?
More details here:
https://stackoverflow.com/questions/54807576/upgrading-to-an-angular-angularjs-hybrid-application-getting-typescript-errors/

**Comment by gkalpak** [comment]
The official docs do not use (or assume) the use of `@angular/cli` (or webpack) yet (unfortunately) and that is the main issue. (This is mostly because the cli wasn't a thing back when the docs where created.)

I know it is on the roadmap to update the `ngUpgrade` docs and show a cli-based/-compatible approach (but is not a high priority atm).
@jenniferfell, is this tracked tracked somewhere?

**Comment by eetievent** [comment]
I would suggest to state explicitly that the doc is based on SystemJS and that the use of the @angular/cli is not documented yet. Thank you.

**Comment by atscott** [comment]
Closing as obsolete. With the removal of AngularJS support and imminent removal of the upgrade support, documentation is generally in an LTS state (as-is and will only be updated when absolutely necessary)
