### ISSUE TITLE
Forms validations are broken when used not in modules/examples

### ISSUE THREAD

**Issue by vsavkin** [angular/angular#3026]
It looks like iterableToList returns an array of undefined.

**Comment by gdi2290** [comment]
@vsavkin I ran into this problem while trying to fix the https://github.com/angular/angular/pull/2856 it turned out everything worked once I included all the directives. For some reason only including one creates this side effect. Here's my test to try to reproduce the undefined array https://github.com/angular/angular/pull/2884 (worked locally but not in travis)

**Comment by vsavkin** [comment]
Fixed via https://github.com/angular/angular/commit/13b1d850586dab3d02ba0b06dc417a29203933fe
