### ISSUE TITLE
OnChanges "Suggest Edit" link broken

### ISSUE THREAD

**Issue by MaximoB** [angular/angular#30292]
# 📚 Docs or angular.io bug report

### Description

The "Suggest Edit" pencil icon in the upper-right corner of the Angular documentation for OnChanges leads to a 404 page.

### What's the affected URL?**
https://angular.io/api/core/OnChanges

### Expected vs Actual Behavior**
Expected: The "Suggest Edit" link would bring you to a GitHub page where you can fork and edit the file.
Actual: The "Suggest Edit" link opens the GitHub 404 page.

### Browser info
Using Firefox 66.0.4

**Comment by gkalpak** [comment]
This is because the `lifecycle_hooks.ts` file has been moved. It is now in [packages/core/src/interface/lifecycle_hooks.ts][1]. You can find the old file on [the 7.2.x branch][2] (and you can find the latest links on next.angular.io).

Having the links point to master (or any branch for that matter) entails the risk of broken links when the files are moved (or the target lines change), but having them point to a specific commit is not possible (for editing).

##
We could still point to the branch (instead of master) and that would lower the risk of changes that would result in 404s, but then it would be a little more confusing if someone wanted to submit a PR against master.

Seems like we are between a rock and a hard place :grin:
@petebacondarwin, wdyt?

[1]: https://github.com/angular/angular/edit/master/packages/core/src/interface/lifecycle_hooks.ts?message=docs(core)%3A%20describe%20your%20change...#L9-L37
[2]: https://github.com/angular/angular/edit/7.2.x/packages/core/src/metadata/lifecycle_hooks.ts?message=docs(core)%3A%20describe%20your%20change...#L21-L48

**Comment by petebacondarwin** [comment]
It is a tricky one, since in general we do want PRs against master but most people are viewing the docs on angular.io which will always point to a non-master branch...

Actually I think it might be best to change it to the actual branch. My thinking is that someone who clicks that button is not doing general PRs against angular/angular, they are wanting to change something that is wrong with the docs that they are viewing. If it turns out that it should be against master then we can fix that later during PR review.

Moreover, perhaps we could add something to the top of the PR template to tell the author that they should check to see if they have chosen the correct branch for this PR, and that they should consider the `master` branch perhaps?

**Comment by dario-piotrowicz** [comment]
Hi Guys I just wanted to mention that this currently looks fine on the site and it is pointing to master (https://github.com/angular/angular/edit/master/packages/core/src/interface/lifecycle_hooks.ts?message=docs(core)%3A%20describe%20your%20change...#L9-L37)

So I would actually imagine that this issue can be closed?

**Comment by petebacondarwin** [comment]
The problem only really appears in the few cases where something has moved in the docs. Since this is fairly uncommon, I agree that we should stick with targeting master for docs PRs, and then help out contributors if they hit one of these scenarios.
