### ISSUE TITLE
Improvement recommendations to doc structure, esp. ViewChild api doc

### ISSUE THREAD

**Issue by KyleVassella** [angular/angular#30343]
Just look at the official documentation for the @ViewChild decorator. There's no way your average angular dev can go to that page and come away knowing what @ViewChild does: https://angular.io/api/core/ViewChild

How about a section on each page with a high level definition or use case? Nothing on that page tells you conceptually what @ViewChild is supposed to accomplish. You don't have to describe Angular's framework magic to us in the definition - leave that part for the advanced definition and give us a use case definition at the top. 

Angular.io needs a major overhaul in every area to be more simply understood.

**Comment by Airblader** [comment]
While I somewhat understand and agree that the documentation could improve, so could your tone. It would also be good if you respected the issue templates.

**Comment by Saurabh11Sharma** [comment]
Their is always room for improvement. No one is perfect, same for this documentation. This doesn't mean we can shout out to any one who did his best efforts to make something that helps all the dev all around the world. Please be polite it never harms anyone. You can also contribute to documentation if you feel its not up to the mark.

**Comment by kapunahelewong** [comment]
Hi @KyleVassella, would you like to submit a PR? We'd love to see your thoughts fleshed out and we're constantly working to improve the docs. Your perspective could be a great discussion point on the docs team.

**Comment by lordfriend** [comment]
Find Neither the `@ViewChild` document nor the `ViewConainerRef` document provide instruction for developers to show how to obtain a ViewContainerRef through `@ViewChild` from a template reference.

for example
```
@Component({
   selector: 'some-comp',
   template: `
        <div class="other-stuff">
        </div>
        <div class="some-container" #someContainer>
            <!-- I want  to insert a component dynamically into this -->
        </div>
   `
})
export class SomeComp implements OnInit {
    @ViewChild('#someContainer', {read: ViewCointainerRef}) someContainer: ViewContainerRef;
    constructor(private _componentFactorResolver: ComponentFactoryResolver){}
    ngOnInit(): void {
        this.someContainer.createComponent(SomeOtherComponent);
    }
}
```

I think there is no way for a developer to know this usage. except for asking somewhere or looking into some angular/component implementation.

**Comment by jbogarthyde** [comment]
Perhaps it will help to understand the doc design goals -- as is standard practice for software documentation, we try to separate the *API Reference* doc from more conceptual/cookbook doc with extended examples. The API Reference pages are meant to provide specific syntax details and syntax examples, so that they can be used for *reference*. They should, whenever possible, contain links or references to the kind of conceptual explanation to be found in the *subject-matter guides* (which is to say, the documentation pages meant to teach specific areas).

In practice, we haven't reached this state yet. In some cases, we are missing the link to a related guide in the API Reference entry, and in some cases the related conceptual material is missing from where it should be.  So the `@ViewChild` API page should have a link to a discussion in the Routing and Navigation guide -- but that discussion is also missing.

This is a good example of a specific documentation suggestion that can be acted on:
*  Add a conceptual discussion of navigating the view hierarchy (presumably in the Routing and Navigation guide) 
--AND-- 
* Add a link to that discussion in the relevant API pages.

Angular covers a lot of ground, and is constantly expanding, so the documentation is always a work in progress. We are working hard on making it as complete and helpful as possible.  We really do welcome and appreciate suggestions and contributions from the community.

**Comment by kapunahelewong** [comment]
Status: Docs team, we can move forward per the above info. Engineering input probably not necessary except for an occasional question. Thanks so much, @jbogarthyde ❤️

**Comment by Chealer** [comment]
@angular-robot this is not a feature request.

**Comment by Chealer** [comment]
I recommend to remove "structure" from this ticket's title (I'd suggest "Improvement recommendations to documentation, esp. @ViewChild").
@KyleVassella would you agree to add @ViewChildren to this ticket's scope? @ViewChildren is very related and in my humble opinion its specification is nearly as bad.

Without being exhaustive, the issues in @ViewChild's documentation certainly exceed structure:

1. The only subsection in _Usage notes_ is _Example 2_.
2. The only documentation in all examples is "child is set".
3. Example 2 is completely abstract.
4. The first example is way more complicated than it should be.
5. "See more..." links to... pretty much itself.
6. The _Options_ section is empty.
7. There is no definition of "view query".
8. The synopsis doesn't provide a functional definition (just like the description), but goes into internals.

I managed to (mostly) understand @ViewChild and @ViewChildren thanks to [this _much_ clearer LogRocket post](https://blog.logrocket.com/understanding-the-viewchild-and-viewchildren-decorators-in-angular-10/).



This ticket was probably not phrased optimally in its initial form, but it can't be denied that @ViewChild's documentation must have been terrible (I'd still qualify it that way in its current state). I would say this is _appalling_ considering this component is marketed as mature and there is no disclaimer whatsoever. I am new to Angular, but if this aspect is somewhat representative of Angular's documentation, I would recommend filing a new ticket (if there isn't already one) and exploring ways to communicate this status to prevent deceiving potential new users.

**Comment by jessicajaniuk** [comment]
There's an ongoing effort to improve the documentation. So we're going to close this as there's no measurable action here other than "improve the docs".
