### ISSUE TITLE
@angular/service-worker SwPush.requestSubscription not working in Firefox 60.6.1esr

### ISSUE THREAD

**Issue by borch84** [angular/angular#30552]
# 🐞 bug report

### Affected Package

 The issue is caused by package @angular/service-worker

### Is this a regression?

 No

### Description

I am implementing a PWA application with @angular/service-worker. So far in google chrome I can receive messages, but when I request the subscription object in firefox got an exception error.

## 🔬 Minimal Reproduction

The portion of the code I run in order to get the subscription is:

```
 async requestSubObject() {
    await this.swPush.requestSubscription({
      serverPublicKey: this.VAPID_PUBLIC_KEY
    })
    .then(sub => {
      console.log('****subscription object: ',sub.toJSON());
    }).catch(err => console.error('****requestSubscription Error: ',err));
  }
```

https://stackblitz.com/edit/angular-twyy5q

## 🔥 Exception or Error
<pre><code>
requestSubscription Error: 
TypeError: e is undefined
Stack trace:
/e.prototype.requestSubscription/<@http://localhost:8080
</code></pre>

## 🌍  Your Environment

**Angular Version:**
<pre><code>

Angular CLI: 7.3.9
Node: 10.15.3
OS: linux x64
Angular: 7.2.14
... common, compiler, compiler-cli, core, forms, http
... language-service, platform-browser, platform-browser-dynamic
... router

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.13.8
@angular-devkit/build-angular     0.13.8
@angular-devkit/build-optimizer   0.13.8
@angular-devkit/build-webpack     0.13.8
@angular-devkit/core              7.3.8
@angular-devkit/schematics        7.3.8
@angular/cli                      7.3.9
@angular/fire                     5.1.3
@angular/pwa                      0.12.4
@angular/service-worker           7.2.15
@ngtools/webpack                  7.3.8
@schematics/angular               7.3.8
@schematics/update                0.13.9
rxjs                              6.5.1
typescript                        3.1.6
webpack                           4.29.0

</code></pre>

**Anything else relevant?**
 Firefox 60.6.1esr

**Comment by gkalpak** [comment]
This happens because `navigator.serviceWorker.pushManager` is undefined (probably due to the default settings).
So, it is expected that `SwPush` does not work, but we should have a more descriptive message.

Right now, we expect that all browsers that support `navigator.serviceWorker` will also support `PushManager` (according to the spec, I guess), but if this is not always the case we could offer a better error to help identify the issue.

I am going to close this, but please open a new issue about improving the error message when `navigator.serviceWorker.pushManager` is undefined (or even better submit a pull request with a fix :wink:).
