### ISSUE TITLE
Side effects test needs more details 

### ISSUE THREAD

**Issue by kara** [angular/angular#30570]
We recently ran into this test failure on CI:

https://circleci.com/gh/angular/angular/328483#tests/containers/3

It's not clear from this message what actual side effects were added (nothing is printed) and it's also not clear what actions need to be taken.

There is this sentence on the bottom, but it doesn't contain a command:

> To update the expectations, run this command again with the --update flag.

I assume it's this from above?
> check-side-effects --test side-effects.json --pure-getters

We should print the full command to run like we do for the symbol tests.

**Comment by filipesilva** [comment]
@ocombe recentely had some trouble with the low level of detail for this check in https://github.com/angular/angular/pull/30562.

His PR caused the ESM and FESM to emit different code, but both are compared against the same snapshots. But since there's no diff and update functionality updates the snapshot in place, he was never able to see the difference.
