### ISSUE TITLE
Cannot set property scrollRestoration of [object History] which has only a getter.

### ISSUE THREAD

**Issue by mvrcrypto** [angular/angular#30629]
# 🐞 bug report

### Affected Package

The issue is caused by package @angular/common. There is a method named _setHistoryScrollRestoration_ in the **viewport_scroller.ts**.

### Is this a regression?

I don't think so.

### Description
Not much, i only got this error from ErrorHandler from some particular IP adresses.

## 🔬 Minimal Reproduction

It's weird but i can't reproduce this error. However, i get this error from IP addresses corresponding to 66.102.8.* and it seems to be _google-proxy-66-102-8-88.google.com_
Also for further details i found a similar error here: [https://github.com/taion/scroll-behavior/issues/126](https://github.com/taion/scroll-behavior/issues/126).

## 🔥 Exception or Error
<pre><code>

TypeError: Cannot set property scrollRestoration of [object History] which has only a getter

</code></pre>

## 🌍  Your Environment

**Angular Version:**
<pre><code>

</code></pre>

**Anything else relevant?**
User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/73.0.3683.103 Safari/537.36

**Comment by petebacondarwin** [comment]
There is a proposed PR for this at #30630

**Comment by petebacondarwin** [comment]
It seems from https://github.com/taion/scroll-behavior/issues/126 that this issue is caused by specialised browsers that do not support scroll restoration (e.g. some web crawlers). Given that we already sniff the browser to see if it has the `window.scrollTo` method, I think it would also be reasonable to check whether `window.history.scrollRestoration` is writable too.
