### ISSUE TITLE
Failed to load my.component.html

### ISSUE THREAD

**Issue by sviat9440** [angular/angular#30668]
# 🐞 bug report
### Affected package
@angular/core
### Description
When i try to extends built-in Angular decorator ```Component```, application was crashed with error: ```Failed to load my.component.html (404 Not Found)```.

Here is my code of decorator:
```
export function MyComponent(cfg: Component): TypeDecorator {
  const decorator = Component(cfg);
  return function (cls: Type<any>) {
    return decorator(cls);
  };
}
```
Here's its usage:
```
@MyComponent({
  selector: 'app-my-component',
  templateUrl: './my.component.html',
  styleUrls: ['./my.component.scss'],
})
export class MyComponent {
}
```

I found out that if you use the standard ```Component``` decorator, then meta.templateUrl will resolve in meta.template. But if i use custom directive, nothing happend. Application trying to get ```my.component.html``` from ```http://localhost/my.component.html``` by xhr request, and crashed when receive error 404.

Why this happens I do not understand, most likely it is a bug.

Here is my dependencies: 
```        "@angular/animations": "^7.2.7",
        "@angular/common": "^7.2.7",
        "@angular/compiler": "^7.2.7",
        "@angular/core": "^7.2.7",
        "@angular/forms": "^7.2.7",
        "@angular/http": "^7.2.7",
        "@angular/platform-browser": "^7.2.7",
        "@angular/platform-browser-dynamic": "^7.2.7",
        "@angular/router": "^7.2.7",```

**Comment by IgorMinar** [comment]
I'm sorry, but this is not intended to work. 

The Angular decorators are non-extensible because they are actually strippped off during the AOT compilation and build optimization steps.

If we allowed extending the decorators we'd actually have to run them when the application starts which would slow things down (decorators can be slow) and increase the payload size (most of the metadata and all the decorator code is not needed at runtime)
