### ISSUE TITLE
ivy providers don't work with config object passed to forRoot

### ISSUE THREAD

**Issue by mattlewis92** [angular/angular#30726]
# 🐞 bug report

### Affected Package

@angular/compiler

### Is this a regression?

No, it's ivy only

### Description
I tried out ivy on my project and the only error I got was 
```
ERROR in Invalid map access: [] dot eventTitleFormatter
```

The issue is caused by this line: https://github.com/mattlewis92/angular-calendar/blob/try-ivy/projects/angular-calendar/src/modules/calendar.module.ts#L56

Where I pass a config object of providers
```
export class CalendarModule {
  static forRoot(
    dateAdapter: Provider,
    config: CalendarModuleConfig = {}
  ): ModuleWithProviders {
    return {
      ngModule: CalendarModule,
      providers: [
        dateAdapter,
        config.eventTitleFormatter || CalendarEventTitleFormatter,
        config.dateFormatter || CalendarDateFormatter,
        config.utils || CalendarUtils
      ]
    };
  }
}
```

Removing it and the app compiled and everything else worked great, very impressive to see the commitment to backwards compatibility 🎉 

## 🔬 Minimal Reproduction

Checkout this branch:
https://github.com/mattlewis92/angular-calendar/tree/try-ivy
```
npm i
npm start
```

and you'll see the error

## 🔥 Exception or Error
<pre><code>
ERROR in Invalid map access: [] dot eventTitleFormatter
</code></pre>

## 🌍  Your Environment

**Angular Version:**
<pre><code>
Angular CLI: 8.0.0
Node: 12.1.0
OS: darwin x64
Angular: 8.0.0
... animations, cdk, cli, common, compiler, compiler-cli, core
... forms, language-service, platform-browser
... platform-browser-dynamic, router

Package                            Version
------------------------------------------------------------
@angular-devkit/architect          0.800.0
@angular-devkit/build-angular      0.800.0
@angular-devkit/build-ng-packagr   0.800.0
@angular-devkit/build-optimizer    0.800.0
@angular-devkit/build-webpack      0.800.0
@angular-devkit/core               8.0.0
@angular-devkit/schematics         8.0.0
@ngtools/json-schema               1.1.0
@ngtools/webpack                   8.0.0
@schematics/angular                8.0.0
@schematics/update                 0.800.0
ng-packagr                         5.2.0
rxjs                               6.5.2
typescript                         3.4.5
webpack                            4.30.0
</code></pre>

**Anything else relevant?**
Nope

**Comment by JoostK** [comment]
Could you test with `next` packages? That error should no longer occur as of #30247.

**Comment by mattlewis92** [comment]
Nice, thanks for the fast reply!

<img width="509" alt="Screenshot 2019-05-29 at 13 25 52" src="https://user-images.githubusercontent.com/6425649/58577830-509e8180-8215-11e9-9e2b-e160d6c765c6.png"> 

`next` is currently set to `8.0.0` so I can't try it, but if it was merged 13 days ago wouldn't it have been included in `8.0.0` as there's been several releases cut since then?

**Comment by JoostK** [comment]
`next` not being available as 8.1.x seems to be an oversight. Since the release of 8.0.0-rc.0 about a month ago, the master branch has already been designated for 8.1.x development. Since work on Ivy is typically only merged to master, the patch branch has been missing out on the latest fixes.

Please see https://github.com/angular/angular/issues/29564#issuecomment-496809489 for an alternative approach on how to run from `master`.

**Comment by mattlewis92** [comment]
Ah gotcha, makes sense. I tried the version from the cli builds on github and I'm getting the same error. I looked at the source and that patch is 100% in my node_modules:

<img width="904" alt="Screenshot 2019-05-29 at 13 58 52" src="https://user-images.githubusercontent.com/6425649/58579881-ecca8780-8219-11e9-874c-6bc3502a4ac1.png">

You can play with it yourself here to verify: https://github.com/mattlewis92/angular-calendar/tree/try-ivy

Thanks!

**Comment by JoostK** [comment]
Ah thanks, that helps a lot. I misjudged the actual problem here, which is that it is currently not allowed to read a non-existent property from an object. Since that has well-defined behavior in JavaScript, we should just evaluate it as `undefined`.

When replacing the `throw new Error(...)` with simply returning `undefined` the app does compile, with heaps of template type errors. There's #30675 to fix some, but others look legit ;) The new template type checking should be more accurate, but if you spot false positives please let us know.

If you feel like it, you could open a PR with a fix for the static evalutor. If you need help with that or are not interested, let me know :)

**Comment by mattlewis92** [comment]
Sure, I'd be happy to contribute! Could do with some pointers for writing a failing test case 😄

**Comment by JoostK** [comment]
Nice! For a test case, how about declaring a variable that is initialized to an object literal (that would be the first arg to `evaluate`) and then reading a non-existent property from that variable in the second arg. The outcome is expected to be `undefined`.

You can run that specific testsuite using `yarn test-ivy-aot packages/compiler-cli/src/ngtsc/partual_evaluator/test`, optionally with `--config=debug` to be able to attach a debugger from `chrome://inspect`.

**Comment by mattlewis92** [comment]
Sweet, thanks for the help, here you go: https://github.com/angular/angular/pull/30738
