### ISSUE TITLE
NgModel does not work with custom angular components

### ISSUE THREAD

**Issue by vsavkin** [angular/angular#3076]
Fix it
```
<some-custom-angular-component currency=" [(ng-model)]="dollars">
</some-custom-angular-component>
```

**Comment by vsavkin** [comment]
Turns out it is not an issue

**Comment by danicomas** [comment]
How did you solve this @vsavkin ?

**Comment by danicomas** [comment]
Other question. Update control in NgModel doesn't invoke

ngOnChanges(changes) {
       debugger;
   }

?

**Comment by templth** [comment]
@danicomas In fact you can leverage bidirectional binding on custom components but you don't need to use `ngModel`. For this, just define input and output parameters for your field:

    @Component({
      selector: 'my-component'
    })
    export class MyComponent {
      @Input() inputText : string;
      @Output() inputTextChange = new  EventEmitter();
    }

With this, you will be able to use the syntax `[(inputText)]` when using your component:

    <my-component [(inputText)]="something"></my-component>

Hope it helps you,
Thierry

**Comment by danicomas** [comment]
@templth I don't want to have an emit I want to update the ng-model @vsavkin

**Comment by zoechi** [comment]
@danicomas That sounds defiant ;-) Why do you want to update the ng-model?

**Comment by danicomas** [comment]
@templth @zoechi I would prefer to do this process:

1) call to WS and populare this.data
2) input text with ng-model=data.name
3) send this resource (this.data) to put WS

As you can see you wouldn't have to do other related process (mapping this.data with your event emitter delegates)

**Comment by antonmoiseev** [comment]
@danicomas regarding your question on `ngOnChanges()`. According to the docs it's triggered when an input property is changed via the data binding. Take a look at [this example](http://plnkr.co/edit/1qxL7ykCQWo7Ppjs7rbq?p=preview). Both `greeting` and `search` properties are used with `[(ngModel)]` to sync data between the input element and the component's _own_ property. However only `greeting` triggers `ngOnChanges` in the `ChildComponent` since it's passed from the parent component through the _property data binding_ (line 25).

**Comment by danicomas** [comment]
@antonmoiseev Good answer about binding ngOnChanges. It is a little bit strange because ng-model could be considered a binding.

Now we will have to solve the ng-model in child components...
