### ISSUE TITLE
2.0.0-alpha.31 didn't make it to pub

### ISSUE THREAD

**Issue by yjbanov** [angular/angular#3077]
/cc @rkirov

**Comment by jeffbcross** [comment]
Thanks for pointing that out. I've published from the 2.0.0-alpha.31 tag and verified. I also added steps to our release doc to make sure the releaser checks npm and pub after running scripts. I forgot that the script has an issue where it doesn't actually follow through with publishing, presumably because we're not passing -f on this line, and `pub publish` prompts before actually publishing: https://github.com/angular/angular/blob/master/scripts/publish/pub_publish.sh#L36

I'll submit a PR to fix.
