### ISSUE TITLE
Ng serve -o unable to load app in IE edge 25.x and IE edge HTML 13.x using angular 8 browser list .

### ISSUE THREAD

**Issue by bgjadhav** [angular/angular#30817]
# 🐞 bug report

### Affected Package

browserlist

### Is this a regression?

No

### Description
When we create a new angular V8 App using ng new appname and we run it using ng serve -o with browser default to IE edge , we see a blank page with following error in the console. 

```
HTML1300: Navigation occurred.
localhost:4200
SCRIPT1006: Expected ')'
polyfills.js (2979,40)
SCRIPT1006: Expected ')'
vendor.js (290,22)
```

## 🔥 Exception or Error
<pre><code>
HTML1300: Navigation occurred.
localhost:4200
SCRIPT1006: Expected ')'
polyfills.js (2979,40)
SCRIPT1006: Expected ')'
vendor.js (290,22)

</code></pre>

## 🌍  Your Environment

**Angular Version:**
<pre><code>

Angular CLI: 8.0.1
Node: 10.15.3
OS: win32 x64
Angular: 8.0.0
... animations, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.800.1
@angular-devkit/build-angular     0.800.1
@angular-devkit/build-optimizer   0.800.1
@angular-devkit/build-webpack     0.800.1
@angular-devkit/core              8.0.1
@angular-devkit/schematics        8.0.1
@angular/cli                      8.0.1
@ngtools/webpack                  8.0.1
@schematics/angular               8.0.1
@schematics/update                0.800.1
rxjs                              6.4.0
typescript                        3.4.5
webpack                           4.30.0
</code></pre>

**Anything else relevant?**

No

**Comment by Alex-Torres** [comment]
https://github.com/angular/angular-cli/issues/14455

**Comment by gkalpak** [comment]
This works as intended. See angular/angular-cli#14455 (as @Alex-Torres mentioned above) for details and work-arounds.

**Comment by benouat** [comment]
@gkalpak could you please be more specific regarding  "_this works as intented_" ? Because to me it's not 😞 

Let me detail a bit.

`ng build` is working fine. with differential loading, it uses 2 different builds, and generates an `es2015` build and a `es5` one. Both `dev` and `prod` build work like that.

Below is the output of this behaviour from an freshly scaffolded app with angular-cli

<img width="915" alt="image" src="https://user-images.githubusercontent.com/1152740/58829233-ab860d80-8647-11e9-80e3-dd15d518f19a.png">

<img width="1035" alt="image" src="https://user-images.githubusercontent.com/1152740/58829283-c5275500-8647-11e9-8f95-58658adf46c0.png">

Based on that, I would **assume** and **expect** that `ng serve` is also working like that, even more, I would think it is built on top of that... But apparently it's not 😞. 

<img width="1137" alt="image" src="https://user-images.githubusercontent.com/1152740/58829433-11729500-8648-11e9-8b2c-f36cc2093331.png">

As you can see on the above screenshot, `ng serve` is doing a weird single build with only the polyfills to be built in `es2015` and `es5`. What about the other bundle ?

How come is it possible ? I am really confused about that strange behaviour... especially that, if we consider `angular.json` and the way architect is working (or at least the way I think, or should I say, I tought it is working) `serve` is supposed to be based on `build` ?

<img width="681" alt="image" src="https://user-images.githubusercontent.com/1152740/58829765-f05e7400-8648-11e9-9d9a-32326827ff85.png">

Is the "ngcli8:build" correspond to the above defined "build" ? or because the builder is "dev-server" it is using something else ?

I am a bit puzzled and confused here... to me _intented_ is not really defined by what I just described. Anyhow I am just trying to figure out what's going on.

--- 

One last point, looking a bit at what is generated inside `index.html`, both in `ng-serve` and also in karma for `ng test` it appears that the code generated only declare a `nomodule` but no `type="module"`. All bundles seems to be loaded as es2015 without `type="module"`. Isn't it a bit strange ?

https://github.com/angular/angular-cli/blob/6ec09919b5c2695dee784ce0c3accee7f9754bb0/packages/angular_devkit/build_angular/src/angular-cli-files/plugins/karma-debug.html#L31-L39

Angular supports IE 11, 10 and 9 as stated [here](https://angular.io/guide/browser-support) hence AngularCLI can't assume that `ng serve` should only build `es2015`...

**Comment by gkalpak** [comment]
@benouat, have you read https://github.com/angular/angular-cli/issues/14455#issuecomment-493739768?
I don't know much about how the cli works under the hood, but I know `ng serve` only does an es2015 build by default (possibly for speed?).

I suggest you ask cli-specific questions (including architect, builders, etc.) on the [cli repo][1], since people there are much more knowledgeable on these subjects :grin:

[1]: https://github.com/angular/angular-cli

**Comment by benouat** [comment]
@gkalpak I have read the comment prior to post my comment here, and thought you would know! I'll go to CLI repo then. Thanks!
