### ISSUE TITLE
Document how to compile an Angular application from the NPM distro, without DefinitelyTyped

### ISSUE THREAD

**Issue by jpsfs** [angular/angular#3082]
Hi!

Would it be possible to automatically include, on each release, the correspondent typings file?

The current process of pushing the files to https://github.com/borisyankov/DefinitelyTyped is good, specially because we can use tsd to get them, but it's not in sync with your release process.

@alexeagle @jeffbcross 

Cheers!

**Comment by masaeedu** [comment]
There seem to be .d.ts files that define the contracts exposed by the module in the root of the npm package, although I can't really figure out how to use them, since they don't seem to wrap their exports into a named external module. You have to reference the .d.ts files by path, which is inconvenient. Perhaps someone more familiar with TypeScript can comment on the correct way to use these.

**Comment by jpsfs** [comment]
Hi @masaeedu,

The angular2.d.ts on the npm package directly results of the compilation of ts/angular2.ts. It's not a usable set of **angular2 typings** .

To my knowledge you can't use it 'as is'.

angular2.d.ts should be something similar to https://github.com/Fincodr/DefinitelyTyped/blob/master/angular2/angular2.d.ts

Cheers,

**Comment by alexeagle** [comment]
We have an open research topic to determine how you could use the files distributed via npm as inputs to typescript compiler, along with your sources, to do the Right Thing. It should be possible with only the `.ts` files in the distribution, since they provide typings as well as implementation.

I am planning to figure this out sometime.

**Comment by masaeedu** [comment]
@alexeagle @jpsfs In case you're interested, I've managed to find a slightly hackish workflow that allows me to use the .d.ts files from the npm package directly. I create a symlink named `angular2` adjacent to my tsconfig.json, pointing to the subdirectory where the angular2 npm package resides (I'm using jspm, so for me this is under <project root>/jspm_packages/npm/angular2@<version number>). This allows TypeScript's built in ES6 module resolution to find the .d.ts files in the NPM package folder and makes compilation and intellisense work (in VS Code and atom-typescript that I know of). Using the definition files directly from the NPM package works much better than the DefinitelyTyped file, which I believe is a bit out of date.

There's probably a way to map subfolders to a top level namespace using your tsconfig (or if there isn't this would make a good feature request), which would avoid the necessity of the symlink. Overall, I don't think there's anything that necessarily needs to be changed in the angular package itself.

**Comment by alexeagle** [comment]
Thanks, that's really good info. We have an open Feature Request to the
typescript team to support multiple include paths, which I think would
achieve the same thing as your symlink.

**Comment by alexeagle** [comment]
Looking into this today with @mprobst and we've been emailing with the VSCode team. I'd like to fully understand our options. I'll write something up.

**Comment by alexeagle** [comment]
The outcome is:
- TypeScript ecosystem doesn't have a good general-purpose solution for this. I'll follow-up separately.
- For angular 2 specifically, we will distribute the bundled angular2.d.ts in the npm package, and *remove* the `.d.ts` files which are currently distributed. We'll add the `typescript

**Comment by ComputerWolf** [comment]
@alexeagle, unfortunately it seems that the bundled files are still added to tsd.d.ts when I do a `tsd install` or reinstall to install my other needed typings. Is there a way to prevent this?

**Comment by johnpapa** [comment]
Referencing this issue, which would be helpful so we can put typings in a custom location. 

https://github.com/DefinitelyTyped/tsd/issues/216

**Comment by alexeagle** [comment]
I agree with @johnpapa that we need a fix for that tsd problem, but if you are happy having the typings/ folder in the root of your project, then let's see where it breaks:
```
$ mkdir tmp; cd tmp
$ npm install angular2 # this is the only place where we need to worry about versioning
$ tsd init
$ tsd link
$ cat typings/tsd.d.ts

/// <reference path="../node_modules/angular2/bundles/typings/angular2/angular2.d.ts" />
/// <reference path="../node_modules/angular2/bundles/typings/angular2/http.d.ts" />
/// <reference path="../node_modules/angular2/bundles/typings/angular2/router.d.ts" />

# So far, this seems to be working okay, but we're about to have trouble because of:
$ grep \<reference node_modules/angular2/bundles/typings/angular2/angular2.d.ts
///<reference path="../es6-promise/es6-promise.d.ts"/>
///<reference path="../rx/rx.d.ts"/>
```

Because TypeScript reference's are relative, and TypeScript doesn't yet support multiple include paths, this breaks - those files are not present under the path `../node_modules/angular2/bundles/typings/`

We could distribute a copy of those two dependencies in the NPM distro, so long as the licenses permit it. That would be clean also because we don't get any version skew, which DT tends to gloss over.

otherwise we would need some change in the behavior of `tsd link` to repair these references, or use symlinks (problematic for Windows users)

**Comment by alexeagle** [comment]
TypeScript 1.6 includes a module resolution feature which mirrors Node. So we can now do this.

In https://github.com/angular/angular/commit/3dd9919bbdbe7f4bd820e6c1bd27f7c16ee61b40 I changed how Angular depends on ts2dart typings, as a proof of concept. Next step is to update angular package.json and do the documentation/examples for users.

**Comment by alexeagle** [comment]
Update, I have written a doc proposing that we switch to the built-in support for distributing typings in TS 1.6.
https://docs.google.com/document/d/1jiB1SHfM2AXacKdTbQBoPyKlp7ZSH-LBbfc5gzeMKVY/edit#
This could be in addition to providing a bundled typings file, or could replace it. We'll discuss that next week at Microsoft.

There are a few steps listed in the doc, which I'll start sending PRs for.

**Comment by alexeagle** [comment]
Hi all, this is now almost ready to ship. Comments welcome:
https://github.com/alexeagle/angular2-distro/blob/master/README.md
