### ISSUE TITLE
Allow to use SSR pages when online, and fallback to cached index.html when offline

### ISSUE THREAD

**Issue by GuerricPhalippou** [angular/angular#30861]
# 🚀 feature request

### Relevant Package
This feature request is for @angular/service-worker

### Description

I expect the service worker package to allow for the following behavior:
- When online, serve the server-side rendered pages for maximum first paint speed (then the client side takes over)

- When offline, fallback to the cached `index.html` in order to use the cached client app

The problem is that `ngsw-worker.js` and its configuration file `ngsw-config.json` doesn't provide a high enough granularity level to achieve that.

### Describe the solution you'd like
Change the `navigationUrls `configuration section to a `navigationUrlGroups` section similarly to `assetGroups `and `dataGroups`. This configuration section would allow to define multiple URL groups and their associated behavior, especially a boolean (could be named `enableCaching`) that would allow to set whether the URL group should be served by the server or redirected to `index.html`.
When `enableCaching` set to `true`,  the behavior would be: serve the page from the server, and fallback to `index.html` if not possible for any reason.

### Describe alternatives you've considered
I don't have any alternative solution or workaround in mind. My attempt to get the desired behavior led me to try this configuration:

    {
      "index": "/index.html",
      "assetGroups": [
        {
          "name": "app",
          "installMode": "prefetch",
          "resources": {
            "files": [
              "/favicon.ico",
              "/index.html",
              "/*.css",
              "/*.js"
            ]
          }
        },
        {
          "name": "assets",
          "installMode": "lazy",
          "updateMode": "prefetch",
          "resources": {
            "files": [
              "/assets/**",
              "/*.(eot|svg|cur|jpg|png|webp|gif|otf|ttf|woff|woff2|ani)"
            ]
          }
        }
      ],
      "dataGroups": [
        {
          "name": "backend",
          "urls": [
            "/backend/**"
          ],
          "cacheConfig": {
            "maxSize": 100,
            "maxAge": "3d",
            "strategy": "freshness"
          }
        },
        {
          "name": "serverSideRenderedPages",
          "urls": [
            "/**"
          ],
          "cacheConfig": {
            "maxSize": 100,
            "maxAge": "3d",
            "strategy": "freshness"
          }
        }
      ],
      "navigationUrls": [
        "!/**"
      ]
    }

It provides a behavior close to the one I seek to achieve, but when I refresh the app in offline mode, it works only when the page has been refreshed (thus cached) in online mode before.

**Comment by alan-agius4** [comment]
Hi, the above should already be possible, by using an App Shell together with service workers. (https://angular.io/guide/app-shell)

In a nutshell:
1) Offline users will be served the App Shell by the Service Worker.
2) Online users will always use the SSR'd view

**Comment by GuerricPhalippou** [comment]
Hi, since the app-shell is built at run time, it doesn't work for user-specific data. Shouldn't it be considered?

**Comment by alxhub** [comment]
Thank you for the feature request!

One problem here is that "online" is not a boolean state, but a sliding scale of connection quality, ranging from no connection to poor connection to a quality connection. The browser does attempt to provide some information about the current connection quality via the `navigator.connection` API, but for an _initial_ connection this information is not very reliable.

This means that choosing to make a request to the server (for SSR) is a risk. If the connection is good (local network), it might end up being faster to SSR than to render on the client. But if the connection is at all unreliable, local rendering will probably end up being faster, and waiting on SSR would actively slow things down.

The Angular Service Worker is designed to deliver a _reliable_ experience as well as a fast one. Therefore, we err on the side of client-side rendering, since we know for sure we have all the cached resources we need locally, and there will be no network round trip at all.

Additionally, if the SW goes to the server for SSR, there's no guarantee the server will be running the same application version as the client has cached. It wouldn't be safe to use any of the cached resources with the returned HTML in that case. This again breaks the SW's #1 goal of total reliability.

A case where the SW would cache multiple pre-rendered pages is interesting to think about. It'd be technically pretty challenging but I could see that kind of solution working well.

**Comment by youkouleley** [comment]
OK fair enough, thanks for the explanation!

**Comment by romanovma** [comment]
I have the same request with the difference that it's not about SSR but I want my users to get a fresh version of the app when they navigate to it.

I'm caching index.html with a service worker in order to support a fully offline mode.

At the same time if I deploy an update while the user's browser/tab is closed then whenever s/he opens an app service worker renders an outdated cached version. 

What I am interested in is setting a `freshness` strategy to the index.html so that it's available offline and still users always get an up-to-date version of the app by simply navigating to the home page at the beginning of their work session.

**Comment by r3plica** [comment]
Are you saying that if we want SSR, we should not use PWA?

**Comment by Guerric-P** [comment]
I'll let the contributors answer, but AFAIK if you want to use SSR for SEO you can still use PWA aside, but if you want SSR for maximum first paint speed, that's currently not a use case covered by the framework because it's impossible to know if the page will render faster with the service worker cache, or with the server-side rendered page.

The risk is that the page hangs because the network quality is bad, while the page could be served by the service worker.
Another thing to consider is that it breaks the "update in background" mechanism as the server-side rendered pages always refer to the latest version of the JavaScript files

**Comment by gkalpak** [comment]
It is now possible to specify a [navigationRequestStrategy][1] that tries to serve navigation requests from the server first (falling back to the cached `index.html` when offline.

While this has some drawbacks (as explained in previous comments), it might be a viable solution in specific usecases.
The default (and recommended) behavior, however, remains to serve the cached `index.html` first (and use the app-shell pattern whenever possible).

[1]: https://angular.io/guide/service-worker-config#navigation-request-strategy
