### ISSUE TITLE
Service worker not registrated when importing firebase performences

### ISSUE THREAD

**Issue by Lagistos** [angular/angular#31011]
After i upgraded to angular 8 from 7 i added firebase performances to my app, then i noticed that the service worker doesn't register, then i started to play with new angular projects and i realize that even in a new blanc angular project if i'm adding service worker (with ng add @angular/pwa) and then adding firebase performances (with angularfire ng add @angular/fire) the service worker stop register but when i remove the performences module the sw start register again.

Angular: 8.0.0
Firebase: 6.1.1
AngularFire:5.2.1

**Comment by gkalpak** [comment]
This is probably because Firebase adds a long-running or recurrent task, which prevents the app from stabilizing. For performance reasons, the SW waits for the app to stabilize before registering itself, so if the app never stabilizes, the SW will not be registered.

See [SwRegistrationOptions#registrationStrategy][1] for an explanation and possible solutions.

[1]: https://angular.io/api/service-worker/SwRegistrationOptions#registrationStrategy
