### ISSUE TITLE
migration guide

### ISSUE THREAD

**Issue by maxisam** [angular/angular#31015]
# 📚 Docs or angular.io bug report

### Description

When someone want to update an app from v6 to v7 after v8 is released, they will have problem when they follow the guide by doing this one

>Update to v7 of the core framework and CLI by running ng update @angular/cli @angular/core in your terminal.

It will take the app to V8.

### What's the affected URL?**
https://update.angular.io/#6.0:7.0

**Comment by DmitryEfimenko** [comment]
I second this. Since Angular recommends incremental steps (first from 6 to 7, then from 7 to 8), the upgrade steps on https://update.angular.io should reflect that.

Also, a lot of steps go something like: "We changed this. `ng update` will update it for you".
However, there isn't a separate step for running the `ng update` on its own. Some steps are like `ng update @angular/cli @angular/core`, but I believe it's not the same as running `ng update` on its own? I'm confused.

**Comment by rockument69** [comment]
@kapunahelewong, @StephenFluin and @jbogarthyde : Any progress on this? Thanks!

**Comment by StephenFluin** [comment]
I believe this was fixed in https://github.com/StephenFluin/angular-update-guide/commit/27140cba128159b1410844bdecb92d5dd8e74e81, by making it so that users are recommended to use @6 or @7 etc for old versions.

**Comment by kapunahelewong** [comment]
Thank You for submitting this issue, @maxisam. If you have any more questions regarding this topic feel free to re-open this issue and to tag me.
