### ISSUE TITLE
http text linking to http API

### ISSUE THREAD

**Issue by sjtrimble** [angular/angular#31012]
# 📚 Docs or angular.io bug report

### Description

"http" text for example purposes in the Location Strategy API page (http://localhost:4200/api/common/LocationStrategy#description) description is linking to the HTTP API (http://localhost:4200/api/common/http)

### What's the affected URL?**
http://localhost:4200/api/common/LocationStrategy#description

### Reproduction Steps**
- Go to http://localhost:4200/api/common/LocationStrategy#description
- Click on 'http' in http://example.com#/foo or http://example.com in description paragraph

### Expected vs Actual Behavior**
I would expect it to not go to the http API as it is just 'example text' and not pertaining to the http API

## 📷Screenshot
<img width="617" alt="Screen Shot 2019-06-12 at 12 47 47 PM" src="https://user-images.githubusercontent.com/2958442/59381613-b5c39e00-8d10-11e9-8b3e-6c00718658b1.png">

**Comment by gkalpak** [comment]
This is sort of a known limitation of our auto-linking feature (which is heuristic-based).
As a work-around, you can use `<code class="no-auto-link">Code here</code>`.

Since in this case we can reliably detect that `http://...` does not refer to the `http` package, we should be able to improve our heuristics to exclude such code snippets from matching auto-linking (I've found 11 occurrences of this across all guides and API docs from a quick search).

##
If anyone wants to take this on, that would be 👌
