### ISSUE TITLE
Testing chapter has 2 sample apps which are confusing

### ISSUE THREAD

**Issue by siva636** [angular/angular#31020]
# 📚 Docs or angular.io bug report

### Description

 

The Testing chapter provides two (similar) sample apps to download, one is named as 'Sample App' and the other is 'Tests'. It is interesting to note the 'Sample App' is also having spec files so as 'Tests'. 

Providing two similar sample apps are unnecessary and confusing.

**Comment by Embiggenerd** [comment]
Not to mention neither of them work.

**Comment by kapunahelewong** [comment]
@Embiggenerd, thanks for bringing this up. I've asked around and after some investigation, @gkalpak has submitted #31937 to fix things. For these two particular examples, we're removing the download option because they are built especially to run in StackBlitz.

@siva636 thanks for the feedback. All of the examples on angular.io will include tests because each one is an actual Angular app, so it's normal that both of these have them. These two examples do different things and if we combined them into one app, it would be harder to maintain and clarity would suffer (and we'd have to write tests that test our tests about tests 😁). It's easier to understand concepts when they are isolated. You do have a valid point though, that maybe one guide should have only one example. Most of the time, this is what we're aiming for, though there are guides that have multiple examples. In this case though, I'll make sure to share the idea with Docs Management about the request for a clear solution. The first possibility that comes to mind is possibly breaking the doc into two, each with its own example, since there are two topics being covered there. I can't promise it'll be right away, but I can definitely bring it up in the next docs meeting.

**Comment by Embiggenerd** [comment]
@kapunahelewong Before testing section, things were going really smooth, and so that both apps didn't work was really tilting. Kind of throws off the flow of learning. 

That the testing section has similar but not exactly the same app as TOH is actually kind of nice, because it makes testing TOH a little more work instead of copy and pasting.

Having said that, the testing section could be broken up into smaller pieces with more in depth examples and explanations. For instance, there's nothing about HttpTestingController in the testing guide, but it comes in very handy to test the heroes service in TOH.

**Comment by kapunahelewong** [comment]
@Embiggenerd thanks for your thoughtful feedback. I like your idea of breaking the steps up into smaller pieces. We definitely want to keep the learning process flowing and clear. That's a good tip on `HttpTestingController`, too. This is really helpful. I'll be sure to share with the team. 🙂

**Comment by kapunahelewong** [comment]
Status: Docs team Is currently working on a refactor of the docs. Added this issue to [DOCS-784](https://angular-team.atlassian.net/browse/DOCS-784) for context.

Thanks everyone here for your input as it will help inform what we do with the testing re-work.
