### ISSUE TITLE
Angular 8 form controls freezing when list is loading

### ISSUE THREAD

**Issue by comlabmohan** [angular/angular#31336]
# 🐞 bug report

### Description

 

Hi i am facing one issue in angular like i have page which is having the basic angular form as well two independent component which is basically loading the list from API like comments[500+records], posts[500+records].

Issue:

When a trying to enter value to forms while list is loading, basically **it is not able to do key/check/uncheck/select events** .

After the **comments,posts loaded only page is allowing to do stuffs in forms .**

Is this excepted behavior?.

**I just want decouple the process like loading the list(posts,comments) should not affect the angular form/html form to entered.**

Tried with` trackBy, async pipe` also nothing helped 

Kindly help me to resolve this issue.

## 🔬 Minimal Reproduction

 https://stackblitz.com/edit/angular-ngfor-issue

## 🌍  Your Environment

**Angular Version:**
<pre><code>
Angular 5+
</code></pre>

**Anything else relevant?**

**IE11/Chorme both is having the issue .**

**Please download the project and run in IE11 browser issue will be reproducible.**

**Comment by jasonaden** [comment]
Unfortunately I'm not able to reproduce this, and the link you sent renders fine and doesn't seem to have any noticeable lag.

I would suggest a couple things. First, use Chrome Dev Tools to profile the application and determine where the slow is happening. Perhaps the rendering you're doing requires quite a bit of CPU when 500 records are displayed, and there might be a better way to render the rows. Stamping out 500 rows shouldn't be a problem in most cases though, so I would look for time spent doing things like calculations for each record that's rendered as this could be slowing the rendering.

If this slowness can't be avoided, I would suggest loading on demand rather than rendering rows off screen.

Sorry I can't be of more help here, but I'm not seeing the issue locally with this example.
