### ISSUE TITLE
Need a way to add response headers to service worker responses

### ISSUE THREAD

**Issue by vinay-akkipet** [angular/angular#31330]
# 🚀 feature request

### Relevant Package

 This feature request is for @angular/pwa

### Description
 Need a way to add response headers to responses cached and returned by service worker responses. While using service workers with a CSP, we can run into issues like the one described [here](https://qubyte.codes/blog/content-security-policy-and-service-workers) whose solution is to add a different CSP header for responses returned by service workers as described [here](https://twitter.com/jaffathecake/status/988402162312114177).

I am facing a similar issue as described in the first link above and if can add a header like 'Content-Security-Policy: connect-src *;' to the cached responses returned by the service worker it should solve the problem.

### Describe the solution you'd like
A way to add response headers for responses returned by a service worker

### Describe alternatives you've considered

1. Tried using angular HttpInterceptors to see if I could intercept the service worker response and add the appropriate header.
2. Using plain JS instead of the angular package to have more control over the service worker responses.

**Comment by gkalpak** [comment]
If I understand the linked resources correctly, the solution is not to set special headers to responses from inside the SW script (that wouldn't help, since the request would have failed in the first place).

The solution is to set special CSP headers _**on the server**_ to the response for the SW script. I.e., when the browsers requests `ngsw-worker.js` (the default name for the Angular SW script), the server should attach special CSP headers (e.g. `Content-Security-Policy: connect-src *`) to the response.

##
I am going to close this, since there is nothing to fix inside the Angular SW script, but feel free to continue the discussion below (or point out any mistakes in my understanding of the issue).

**Comment by vinay-akkipet** [comment]
@gkalpak Thanks a ton for adding that comment before closing!! My bad I misconstrued the issue.
