### ISSUE TITLE
package.json in guide/elements download

### ISSUE THREAD

**Issue by o-alexandre-felipe** [angular/angular#31332]
# 📚 Docs or angular.io bug report

### Description
In the guide about angular/elements there is an example, the issue is related to the code available for download in the end of the session https://angular.io/guide/elements#example-a-popup-service.

While the code itself works, the package.json needs to be updated.

## 🔬 Minimal Reproduction
1) Download the code from the the link int the page, pointing to https://angular.io/generated/zips/elements/elements.zip.
2) Extract the zip in a new folder.
2) npm install
3) ng serve

The package @angular/elements is missing.
the package 
`    "angular-in-memory-web-api": "github:brandonroberts/in-memory-web-api-bazel#50a34d8"
`
require versions < 8.0.0 of some angular packages, it seems that in the mean time the package was added to npm, and now it can be changed to
`    "angular-in-memory-web-api": "0.8.0"`

### What's the affected URL?**
 https://angular.io/guide/elements

I have noticed a comment in the github source about needing polyfills but in the page it was not clear if any additional step would be required after downloading. Since it is a guide it is supposed to be followed by beginners, and I believed it was something that worth to report.

**Comment by gkalpak** [comment]
Good catch, @o-alexandre-felipe :+1: Thx for reporting!

Indeed, according to https://github.com/angular/angular/pull/31198#issuecomment-505941484, we need to update the dependency in [aio/tools/examples/shared/package.json][1]. Would you be interested in making this change and submitting a pull request?

[1]: https://github.com/angular/angular/blob/c6b29f4c6d23b1510db3434cb030203d5bdea119/aio/tools/examples/shared/package.json#L35

**Comment by sparshag21** [comment]
Can I work on it if no one else is? I'd love to do it as my first contribution so that I can get familiar with the process!

**Comment by o-alexandre-felipe** [comment]
Ok @sparshag21, I wish you a good contribution :)-

**Comment by sparshag21** [comment]
Thank you, @o-alexandre-felipe

**Comment by kapunahelewong** [comment]
@sparshag21, if you're still planning on doing this, will you tag me?

**Comment by Armor-cn** [comment]
Upgrade the "angular-in-memory-web-api" version to 0.9.
![image](https://user-images.githubusercontent.com/31821714/66695321-e46b7880-ecf2-11e9-8de8-83bf67af963a.png)

**Comment by gkalpak** [comment]
Reading the issue description again, I now realize there are two issues discussed here:

1. An outdated version of `angular-in-memory-web-api` in the examples' `package.json`.
2. The `@angular/elements` dependency missing from the `elements' example's `package.json`.

The first issue has already been fixed (see https://github.com/angular/angular/commit/393398e6f#diff-835d685609901b14699e46f15601e9f0).

For the second, we need to introduce a new `elements` example type and specify that the `elements` example is of that type. We actually had such a type in the past, but it was removed in 661a57d9e. So, we basically need to re-introduce it.

It is likely not a good first contribution candidate, but if anyone wants to take a stub at it, we basically need similar changes to 1c533c913 (the commit that introduced it originally), except that instead of a custom `aio/tools/examples/boilerplate/element/tsconfig.json` we now need a custom `aio/tools/examples/boilerplate/element/package.json` (which lists `@angular/elements` as a dependency). This would be very similar to the `package.json` for [`service-worker` example type][1] (except that we would have `@angular/elements` instead of `@angular/service-worker`).

[1]: https://github.com/angular/angular/blob/c88305d2e/aio/tools/examples/shared/boilerplate/service-worker/package.json

**Comment by yallen011** [comment]
Can I take a stab at the `@angular/elements` dependency fix. The explanation given by @gkalpak  of what needs to be done seems clear and I would love to do this as my first open source contribution, as well as for Hacktoberfest 😄

**Comment by gkalpak** [comment]
Sure, go for it, @yallen011. (fyi @kapunahelewong (who's currently assigned) to avoid duplication of work)
@yallen011, feel free to ping @kapunahelewong or me if you have questions/run into difficulties.

**Comment by yallen011** [comment]
@gkalpak @kapunahelewong  ok, great. working on it
