### ISSUE TITLE
Forced to use bypassSecurityTrustResourceUrl to avoid getting (WARNING: sanitizing unsafe URL)

### ISSUE THREAD

**Issue by ralzohairi** [angular/angular#31361]
# 🐞 bug report

### Description

So, I'm trying to download a base64 file from the client app, say a pdf file or a word document. In order to achieve this I would have to set the href attribute of an "a" tag with the base64 value of the file.

This causes a warning [WARNING: sanitizing unsafe URL]. The logical solution for this would be to sanitize the file in order to ensure no XSS is possible and to stop getting the error. 

So, I tried using the sanitize function as the following:
`const sanitizedURL = this.domSanitizer.sanitize(`
`SecurityContext.URL /* context to sanitize */,`
`unsafeURL);`

However, this wouldn't work. I still get the same error. 

I searched online and everyone kept saying to use the bypassSecurityTrustUrl function, which I did. I sanitized the file using sanitize function then went along and passed it to the bypassSecurityTrustUrl to inform it that it's safe URL. However, it still wouldn't work.

The only way for me to get rid of the error is to use bypassSecurityTrustUrl on the un-sanitized URL of the file, which doesn't really make sense. This will still make my app vulnerable to XSS attacks.

I'm trying to follow the safe approach for this, but it feels like I'm being forced to use bypassSecurityTrustUrl on it's own for it to work, which is not the behavior I want as that URL is always from the user.

## 🔥 Exception or Error
<pre><code>
WARNING: sanitizing unsafe URL
</code></pre>

## 🌍  Your Environment

**Angular Version:**
<pre><code>
Angular CLI: 7.3.7
Node: 8.9.1
OS: darwin x64
Angular: 7.2.11
... animations, common, compiler, compiler-cli, core, forms
... http, language-service, platform-browser
... platform-browser-dynamic, router

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.6.8
@angular-devkit/build-angular     0.6.8
@angular-devkit/build-optimizer   0.6.8
@angular-devkit/core              0.6.8
@angular-devkit/schematics        7.3.7
@angular/cdk                      7.3.7
@angular/cdk-experimental         7.3.7
@angular/cli                      7.3.7
@angular/platform-server          7.2.15
@ngtools/webpack                  6.0.8
@schematics/angular               7.3.7
@schematics/update                0.13.7
rxjs                              6.4.0
typescript                        3.2.4
webpack                           4.8.3
</code></pre>

**Comment by BlindDespair** [comment]
I have the same problem. And actually I am pretty convinced this is a bug in sanitize function. I have an `https://...` url that I am trying to insert into `src` of an `iframe`. And I created pipe that does next: `return this.sanitizer.sanitize(SecurityContext.URL, url);` as recommended by security guidelines. However I still get the same error. Now I have nothing better to do than just exposing my app to xss attacks. That url is a user input.

**Comment by petebacondarwin** [comment]
URLs that contain content like a base64 PDF are considered `RESOURCE_URL` types from a security context point of view.

As described in the [docs](https://angular.io/guide/security#sanitization-and-security-contexts):

> sanitizing resource URLs isn't possible because they contain arbitrary code. 

It is not possible for Angular to automatically prove that an arbitrary resource URL is safe. So you are responsible for making that decision in your application. If you trust your users (perhaps it is an internal application), or if the user is only able to select URLs from a server that you control and whose content you trust, then you just bypass the security checks on these URLs as described in this issue. Otherwise it is up to you to somehow check (or sanitize) the value of the resource URL within the context of your application.

So this is basically working as expected. If you do not trust the source of the resourceURL then you must find a way to sanitize it yourself and then mark it as safe via the `bypassSecurityTrustResourceUrl()` method.

Related to #18950
