### ISSUE TITLE
@ViewChild with { static: false } breaking unit tests

### ISSUE THREAD

**Issue by AndreyWV** [angular/angular#31386]
After updating to Angular 8 (8.0.3) and change ViewChild behavior to `{static: false}` I change access to children component in `ngAfterViewInit` hook. In develop and prod mode it's OK, but in **unit testing** instance of children component doesn't exist in `ngAfterViewInit`.

Abstract example:
```
@Component(...)
export class AppComponent implements AfterViewInit {
  @ViewChild('form', { static: false }) form;

  ngAfterViewInit() {
    this.form.focus();
  }
}
```
Error text:
```
TypeError: Cannot read property 'focus' of undefined
```

But with
```
 ngAfterViewInit() {
    setTimeout(() => {
      this.form.focus();
    });
  }
```
works fine.

And with `{ static: true }` works fine too.

**Comment by AndreyWV** [comment]
Fixed in `8.1.0`.
I close this issue.

**Comment by pepper2108** [comment]
Hey @AndreyWV , 
Could you please elaborate a bit on how you mock `ViewChild` components in your unit tests?
I came across this issue today after app upgrade to Angular 8.1.2 and can't find a solution so far. I am using `jasmine.createSpyObj()` to mock child component and then assign the spy to the component property in `beforeEach()`. This is a common approach and it worked like a charm before, but after upgrade the property is assigned as intended in `beforeEach()` and becomes `undefined` in the tests. All the other properties, however, remain unchanged. If the `ViewChild` is accessed in `onAfterViewInit`, the test fails even if I assign the spy to a component fixture right before the expectation. This affects about 1/10 of app unit tests and is sooo frutstrating.

@alxhub I would like to reopen this issue is possible.

**Comment by pepper2108** [comment]
I found a workaround: you can `spyOn` `ngAfterViewInit` and do `callFake` copy-pasting there the initial `ngAfterViewInit` implementation, replacing `this` with `fixture.component`. But it's inconvenient to say the least so looking forward for the fix.

**Comment by AndreyWV** [comment]
@pepper2108 We create mocks of children components like:
```
@Component({
  selector: 'mock',
  template: '',
})
class MockComponent {}
```

And declare it:
```
TestBed.configureTestingModule({
  // ...
  declarations: [
    TestedComponent,
    MockComponent,
  ],
  // ...
```
