### ISSUE TITLE
CanDeactivate guard is triggered again by its own UrlTree return

### ISSUE THREAD

**Issue by jvquarck** [angular/angular#31385]
# 🐞 bug report

### Affected Package

 The issue is caused by package @angular/router

### Is this a regression?

 Unclear, we didn't use this feature in previous angular versions.

### Description

When returning a UrlTree from a CanDeactivate guard, the same guard is executed again

## 🔬 Minimal Reproduction

https://stackblitz.com/edit/angular-8-candeactivate-guard-error-infinite-loop

**Steps for reproduction:**
* Ignore anything in the UI
* Click on the `Go to login-2` anchor
* Infinite navigation loop is triggered

## 🔥 Exception or Error
∞ loop

## 🌍  Your Environment

**Angular Version:**
<pre><code>
8.0.0
</code></pre>

**Anything else relevant?**

In my opinion returned UrlTree should not trigger again the guard returning it, otherwise that will force to keep logic (or even state) into the guard to control when to return UrlTree, which might lead into coupling.

**Apologies if this is the desired behavior, if that is the case maybe the documentation should state that.**

**Comment by jvquarck** [comment]
Please let me know if I can provide any other information or just help in any other way regarding this issue. Thanks in advance.

**Comment by felipedsc** [comment]
I was trying to manage this to work and had the same issue. 
I just wanted to understand how it works, it is not for a real application, but it is bothering me.
And, well... I don't know if I'm using it right way, but it seems to be working fine with CanActivate but not with CanDeactivate.
So the only way I found to "make it work", is by using this workaround on my canDeactivate method:
      
    canDeactivate(
        component: OnComponentDeactivate,
        currentRoute: ActivatedRouteSnapshot,
        currentState: RouterStateSnapshot,
        nextState: RouterStateSnapshot
    ): Observable<boolean | UrlTree> | Promise<boolean | UrlTree> | boolean | UrlTree {
        const response = component.canDeactivate();
        
        if (response instanceof UrlTree 
            && nextState.url == response.toString()) {
            return true;
        }

        return  response;
    }

I noticed that the nextState receives the correct url on the first time, so on the second time it should be the same as the urlTree I returned before.

**Comment by atscott** [comment]
This seems to make sense to me based on the docs: 

> If any guard returns a UrlTree, current navigation will be cancelled and a new navigation will be kicked off to the UrlTree returned from the guard.

It seems like you'd still be deactivating the current route in the new navigation. It may be that the intended use for this would be to first modify the state such that when `canDeactivate` runs in the new navigation, it returns `true`. Also see somewhat related discussion [here](https://github.com/angular/angular/issues/9530#issuecomment-228572000). It's from 2016 so some of the statements are slightly outdated, but some still hold true. "Running guards is a part of a navigation." and "every navigation is independent"

**Comment by jvquarck** [comment]
I don't think that the documentation clearly states that returning a `urlTree` might retrigger this guard and possibly create an infinite loop. This usage case of the `canDeactivate` guard is like an interceptor. You are modifying this request/navigation based on certain conditions. If we translate this current behavior to interceptors it would mean that you'd need to keep state in every interceptor in the stack, since every interception would trigger again the entire interceptor stack and you'd need to check if you have modified the request already or not.

**Comment by atscott** [comment]
@jvquarck Can you describe a situation where it makes sense to return a `UrlTree` from the `canDeactivate` guard and why it doesn't make sense to add a check in the guard to verify you're not already navigating to that route? How does your guard behave if the user is already navigating to the `UrlTree` that you're returning? Shouldn't it be checking for that case and returning `true` instead of a `UrlTree` anyways?

**Comment by asvishnyakov** [comment]
The issue is more general: CanDeactivate guard is calling every time when any guard return UrlTree and NavigationCancel+NavigationStart events occurs

**Comment by atscott** [comment]
> CanDeactivate guard is calling every time when any guard return UrlTree and NavigationCancel+NavigationStart events occurs

This really seems like it's working as intended and documented though. Returning a `UrlTree` isn't a redirect that continues the previous navigation. Again, the docs state

> If any guard returns a UrlTree, current navigation will be **cancelled** and a **new navigation will be kicked off** to the UrlTree returned from the guard.

A new navigation _would_ trigger all deactivate guards related to the previous route as well as the activate guards for the route that gets activated by the `UrlTree`. I've filed this as a feature request for an option to not trigger some guards in some cases because as I understand things, the current behavior is not a bug.

**Comment by asvishnyakov** [comment]
>  Again, the docs state

> the current behavior is not a bug.

It's just architecture bug. Guards exists not just because they should exists, they resolve some problems. `CanActivate` often used for permissions checking, `CanDeactivate` - to prevent user data lost. I'm not saying it's the only cases, but we shouldn't say "it's ok, because of architecture". No. Architecture for development, not vers a versa. And while you need to check activation guards every time, because you will have different navigation every time, you need only single call of CanDeactivate in any series of navigations: you already has confirmation from user or developer that you may leave this route.

**Comment by Syntastic** [comment]
I am trying to use the deactivate guard to prompt users save or discard their changes on a record. On save I would let them continue to where they were routing, and on discard I would re-route them to a record list view. Having the ability to make canDeactivate return a UrlTree on the surface seemed to be exactly what I needed, but as reported here, this won't work. 

Which is fine, I can solve this other ways. But now I can help but wonder when would it ever make sense to return a UrlTree from a deactivate guard. Was this added to canDeactivate just because canActivate got it?
