### ISSUE TITLE
Cannot find module '@angular/upgrade/static'.

### ISSUE THREAD

**Issue by ronakpandya7** [angular/angular#31448]
Hello,

We are using Bazel v0.27.0 for building our Angular app v8.0.6.

We use the following command to build our app:
`bazel build --incompatible_new_actions_api=false //src:prodapp`

• Attempt 1: We got the following error on the first build:

```
INFO: Analyzed target //src:prodapp (0 packages loaded, 0 targets configured). 
INFO: Found 1 target... 
ERROR: /home/ilink/hybridapp/hybridApp/src/BUILD.bazel:24:1: Compiling Angular templates (ngc) //src:src failed (Exit 1) 
src/app/app.module.ts(3,52): error TS2307: Cannot find module '@angular/upgrade/static'. 
src/app/app.module.ts(4,36): error TS2307: Cannot find module '@angular/upgrade/static'. 
src/app/app.module.ts(5,26): error TS2307: Cannot find module 'angular'.
```
• Attempt 2: We installed @angular/upgrade module, re-built the app using the same command and got the following error:

```
FAILED: Build did NOT complete successfully (38 packages loaded, 157 targets configured) 
    Fetching @build_bazel_rules_sass_deps; Running yarn install on @io_bazel_rules_sass//sass:package.json 
    Fetching @build_bazel_rules_nodejs_rollup_deps; Running yarn install on @build_bazel_rules_nodejs//internal/rollup:package.json 
/Users/lifewood/work/ng-bazel-sample/node_modules/@bazel/bazel/node_modules/@bazel/bazel-darwin_x64/bazel-0.26.1-darwin-x86_64 failed with code 1.
```
It remained in the "Fetching State" only.

• Attempt 3: We upgraded @angular/cli to 8.1.0-rc. It solved "Fetching State" issue, but caused the issue in the Attempt 1 to re-appear.

I've attached the package.json and tsconfig.json files for your reference.

[package_json.txt](https://github.com/angular/angular/files/3367312/package_json.txt)
[tsconfig_json.txt](https://github.com/angular/angular/files/3367313/tsconfig_json.txt)

We are not able to figure out whether this is a bug in Bazel or in Angular 8? 
This issue is very urgent for us to get solved. Any help in this regard would be highly appreciated!

Thanks & Regards,
Ronak Pandya

**Comment by gkalpak** [comment]
@ronakpandya7, it is impossible to tell what the issue might be without a minimal reproduction. It could be anything from `bazel` to `cli`, to the `bazel`/`cli` integration, to your configuration.

I am going to close this issue, because it is not actionable in its current state, but feel free to open a new issue with the necessary info for us to (minimally) reproduce the problem.

**Comment by ronakpandya7** [comment]
Hello @gkalpak,
Which kind of information you want?
We mentioned the versions of bazel and angular as well as we provide the package.json and tsconfig.json.

So what else you want us to reproduce this bug?

Thanks

**Comment by santoshyadav198613** [comment]
Hi @ronakpandya7 ,
By reproduction we mean a small application use stackblitz also run ng --version and provide the value which is printed on the console.

**Comment by ronakpandya7** [comment]
ng --version

**Comment by santoshyadav198613** [comment]
And a repo with minimum configuration to reproduce.

**Comment by gkalpak** [comment]
@ronakpandya7: To add to what @santoshyadav198613 said, we basically need a way to reproduce the problem in a minimal way (i.e. run a command and see the error ourselves).

While you did provide some info (`tsconfig.json` and `package.json`) that was not enough for us to reproduce the problem. Example missing info:
- How did you install bazel? (Globally? Through npm?)
- Are you using the `bazel`/`cli` integration or are you using bazel independently?
- What does your bazel configuration look like?
- What does your code look like? (E.g. what imports do you have?)

A reproduction helps us see the problem ourselves, investigate to find the root-cause (e.g. add breakpoints, attach debuggers, etc.) and verify possible fixes (i.e. ensure they actually fix the problem).

Depending on the case, a suitable reproduction could be a [StackBlitz project][1], a GitHub repo (we can checkout and run) or a set of exact instructions to follow to get the problem). Of course, the simpler/quicker it is for us to reproduce the problem, the sooner we will get to fixing it (because we have limited resources and need to be optimal in how we spend them).

Finally, for the reasons mentioned above, the reproduction should be minimal (in the sense that it should only include the minimum amount of code (including dependencies) necessary to showcase the problem). If a problem can be reproduced with a small project with one file and 10 lines fo code, we don't want to have to go through hundreds of lines of codes and dozen of dependencies to see how each line or dependency might affect or cause the problematic behavior.

[1]: https://stackblitz.com/fork/angular

**Comment by ronakpandya7** [comment]
Hello @gkalpak @santoshyadav198613,

> How did you install bazel? (Globally? Through npm?)

`npm -g i @bazel/bazel`

> Are you using the bazel/cli integration or are you using bazel independently?

`We are using bazel independently`

> What does your bazel configuration look like?

`You can find bazel configuration in attached code`

Please find attached code here.
[hybriddemo.zip](https://github.com/angular/angular/files/3372331/hybriddemo.zip)

Thanks in advance,
Ronak Pandya

**Comment by gkalpak** [comment]
@ronakpandya7, `Cannot find module '@angular/upgrade/static'` error you are getting is because `@angular/upgrade` is not specified as a dependency in a bazel target. E.g. in `ng_module(name="src"`:

```diff
 ng_module(
     name = "src",
     ...
     deps = [
         ...
+        "@npm//@angular/upgrade",
         ...
     ]
 )
```

Once I fixed that, I was getting another error that again sounds like a configuration issue. Since your issue doesn't fall into the bug report or feature request category and this issue tracker is not suitable for support requests, I suggest you repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular` or ask on our [gitter channel](https://gitter.im/angular/angular).

<sub>If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).</sub>
