### ISSUE TITLE
docs-infra: class/interface overview styling has changed

### ISSUE THREAD

**Issue by petebacondarwin** [angular/angular#31494]
The styling of the overview for classes, interfaces etc has changed.

* The linenums are now in a strong colour that makes them stand out harshly (they used to be light grey - and in fact in v5 were not there at all).
* The spacing between overview items has increased, which gives too much space for what is essentially just a navigation list.

## 🔬 Minimal Reproduction

Consider the following page over different versions:

* https://v5.angular.io/api/router/ActivatedRoute
* https://v6.angular.io/api/router/ActivatedRoute
* https://angular.io/api/router/ActivatedRoute

**Comment by sjtrimble** [comment]
1. I agree with the spacing.
2. Although I really like the subtle gray, it does not meet accessibility standards which is why we went darker. Therefore, I like having no numbers for these overview blocks.
<img width="721" alt="Screen Shot 2019-07-12 at 3 01 59 PM" src="https://user-images.githubusercontent.com/2958442/61160860-1a138200-a4b6-11e9-8165-d381cb4b0928.png">

I'll submit a PR for an update.

The links really helped, thanks! :)

**Comment by Orodan** [comment]
What's the status of this issue ?

From what I can see, there is still more space between the class/interface name and it's tag than it used to be in the previous versions. This looks like this is due to the anchor button (which appears on hovering) being display on the right of the name, while it was displayed on the left before. 

So the question is : is it a wanted behavior or not ? If not, there is a fix to do :)

**Comment by petebacondarwin** [comment]
@sjtrimble - do you have an update on this?

**Comment by ajitsinghkaler** [comment]
@petebacondarwin most of it is done just ci issues left on the pull request I think which can be resolved by rebasing on master
