### ISSUE TITLE
Multiple instances of a web component with routing

### ISSUE THREAD

**Issue by popsovy** [angular/angular#31587]
I created a simple component with routing and bootstrapped this component using Angular Elements. I then included multiple instances of the resulting web component on a page:

Here is the demo: http://routerissue.s3-website.us-east-2.amazonaws.com
Here is the source: https://github.com/popsovy/RouterIssue

The problem is that only the last component receives the router-outlet, meaning it doesn't matter from which instance of the component I navigate from, the "routed to" component always gets loaded in the router-outlet of the **last instance** of the component on the page.

 I would expect that each instance of a web component should navigate to its own router-outlet.

**Comment by popsovy** [comment]
Is that possible to tell how long before the issue gets triaged?

**Comment by gkalpak** [comment]
This works as expected afaict. Given that both elements share the same injector, there is one router it can ony have one outlet with a given name. Since you do not specify a name, [`'primary'` is used by default][1], so each subsequent outlet [overwrites the previous one][2].

This is not related to Angular Elements btw. The same happens if you have multiple primary outlets in a regular Angular app: [StackBlitz demo][3]

##
I am not sure whether this is intended Router behavior (I assume it it), so I'll let someone more familiar with `@angular/router` to confirm.

[1]: https://github.com/angular/angular/blob/d1ea1f4c7f3358b730b0d94e65b00bc28cae279c/packages/router/src/directives/router_outlet.ts#L55
[2]: https://github.com/angular/angular/blob/d1ea1f4c7f3358b730b0d94e65b00bc28cae279c/packages/router/src/directives/router_outlet.ts#L56

https://stackblitz.com/edit/ng-issue-31587?file=src/app/app.component.ts

**Comment by atscott** [comment]
Everything @gkalpak said is true -- the router really wasn't meant for this use-case and it's effectively the same as defining multiple router outlets as in his stackblitz demo.

I'm filing this as a use-case for now, as it's not exactly a bug (things are working as expected and designed). I don't see this changing at any point in the future.

**Comment by atscott** [comment]
Who knows how well this works in practice and in different complicated scenarios, but here's a custom router outlet that supports more than one outlet with the same name:
https://stackblitz.com/edit/ng-issue-31587-sqiwuc?file=src%2Fapp%2Fapp.module.ts
I only spent a little while playing with it and it seems to do the trick but I cannot begin to guess what weird scenarios you might run into if used. Other than that, this should more or less be fine. I only used public APIs and the type hackiness around `onChildOutletCreated` could be avoided by providing a custom implementation of `ChildrenOutletContexts` which accepts the custom outlet type.

**Comment by atscott** [comment]
Closing as a use-case that should be solved with a custom outlet as in the example above (https://github.com/angular/angular/issues/31587#issuecomment-660378081). The type hackiness mentioned can now be avoided, as custom outlets are fully supported by implementing the [RouterOutletContract](https://angular.io/api/router/RouterOutletContract)
