### ISSUE TITLE
Google Translate

### ISSUE THREAD

**Issue by WH-Ali** [angular/angular#31623]
I tried to translate the Angular website to another languages through Google Translate but it does not work. Many web developers use Google translate into their website to translate the Website to other languages, if it does not work at Angular, then many people who can not speak English can not use the website and Angular products. How can i use Google translate or any website translator for my projects? 

![2019-07-18_15-41-47](https://user-images.githubusercontent.com/35031580/61462304-ae785b80-a972-11e9-8a84-91bda1f1ccb9.png)

**Comment by gkalpak** [comment]
Thx for reporting. Unfortunately, I have no clue why it doesn't work, nor is there any actionable error on the page. My guess is that Google translate can't correctly load Single Page Applications (but it might be something else).

If anyone has an idea about what we could do to allow Google translate to work like this, we would be happy to look into it. In the meantime, loading the page as usual, right-clicking on the page and choosing "Translate to <YOUR_LANGUAGE>" seems to work fine (as fine as Google translate can work :wink:).

##
Closing, because this is not actionable atm.
