### ISSUE TITLE
WebCrypto.subtle.generateKey runs outside of current zone

### ISSUE THREAD

**Issue by rgammans** [angular/angular#31690]
I believe the WebCryto.subtle API is in need of extra handling by zoneJs. 
From my somewhat naive analysis some functions ; notably elements run 'after' (eg; from the then() of the promise) generateKey seem to be running outside of the zone they were called in.

To confuse matter a little I'm using the newer async syntax from typescript, as I find it more readable.

My evidence for this is the follow specs. (You should be able to drop them as-is into an empty angular.io project to run them)

> cryptozone.spec.ts

```typescript

import { async, fakeAsync , tick } from '@angular/core/testing';

function delay(t, v) {
   return new Promise(function(resolve) { 
       setTimeout(resolve.bind(null, v), t)
   });
}

describe('Some test for how wepcrypto, zones and async style interact : ', () => {


   it(' when import key is incorrectly called async in a fakeAsync zone; an exception should still propagate', fakeAsync ( () => {
       expect(  fakeAsync ( async () => {
            const x = await window.crypto.subtle.importKey(
                    "jwk", //can be "jwk" (public or private), "spki" (public only), or "pkcs8" (private only)
                    {   //this is an example jwk key, other key types are Uint8Array objects
                        kty: "RSA",
                        e: "AQAB",
                        n: "======",  // Invalid modulus to force exception
                        alg: "RS256",
                        ext: true,
                    },
                    {   //these are the algorithm options
                        name: "RSASSA-PKCS1-v1_5",
                        hash: {name: "SHA-256"}, //can be "SHA-1", "SHA-256", "SHA-384", or "SHA-512"
                    },
                    false, //whether the key is extractable (i.e. can be used in exportKey)
                    ["verify"] //"verify" for public key import, "sign" for private key imports
                )

       })).toThrow();

   }));

   it(' using a chain of awaits to chain promise ; exceptions/error from the final function should still propagate',  () => {
       const fn = async () => {
                throw new Error("bar");
            };
       expect( fakeAsync ( async () => { 
            const t = await delay(2000,1);
            const y = await fn(); 
    })).toThrow();

   });



   it(' should propagate a rejected Promise thrown in an awaited function even if after a generateKey call',  () => {
       const fn = async () => {
                throw new Error("bar");
            };
       expect( fakeAsync ( async () => { 
            const x = await window.crypto.subtle.generateKey(
              {
                name: 'RSASSA-PKCS1-V1_5',
                modulusLength: 2048, // can be 1024, 2048, or 4096
                publicExponent: new Uint8Array([0x01, 0x00, 0x01]),  // 65537
                hash: {name: 'SHA-256'}, // can be "SHA-1", "SHA-256", "SHA-384", or "SHA-512"
              },
              true, // whether the key is extractable (i.e. can be used in exportKey)
              ['sign', 'verify' ]
            );
            const y = await fn(); 
    })).toThrow();

    });

});
```
(Compiled with typescript 3.2.2 ; running karma 3.1.4; jasmine 2.8.0; on firefox 60 and Chrome 71)

The first two tests pass showing the async functions and some of the crypto api work as one would expect, but the final slightly a more complex test with generateKey fails to catch the exception ; although the browsers console does show it was thrown but not caught by the expectation.

Since the Zone is left before the expectation is evaluated; I believe this means the resolution of generateKey is outside of the zone generateKey was called in.

If I've missed anything in this analysis ; it would be great to know so I can understand zone better.

**Comment by alxhub** [comment]
Closing for insufficient votes. We can't provide patches for every API out there with zone.js, but it should be straightforward to implement such a patch should you need it.

**Comment by Mekacher-Anis** [comment]
@alxhub 
sorry for reopening this issue, but I'm also facing the exact same problem, my unit tests are failing because `flushMicrotasks` and `flush` and `fixture.whenStable` all return before the calls to `crypto.subtle` are resolved and hence all my `expect`s are running before the crypto functions are finished and I didn't know how one could patch those functions as all tests run synchronously.
Any suggestions on how one might go around patching these functions for unit tests ?
thanks in advance

**Comment by JiaLiPassion** [comment]
@rgammans, sorry for the late reply, the test case you wrote is not working because 
1. `fakeAsync` can be only used to a `testMethod`, not inside a `testBody`.
```
it('test', fakeAsync(() => { // this is ok
  expect(fakeAsync(() => {})).toBeSomething()) // you can not use fakeAsync here.
}))
```
2. The test case 1 `when import key is incorrectly called async in a fakeAsync zone; an exception should still propagate` passed since the `crypto.subtle` logic is not being executed at all.
3. And even `zone.js` patch `crypto` API, the test case still will not being executed correctly since the `crypto` API return a `native Promise` instead of a `JS Promise`, and the `native promise` like `async/await` is non patchable for `zone.js`, so to test your app with `crypto API`, you need to use `èxpectAsync` https://jasmine.github.io/api/3.4/async-matchers.html

@Mekacher-Anis , if your case is different issue, please create a new issue with sample code, and I will check it.
