### ISSUE TITLE
Cordova needs to be patched for events - pause, resume, activated, documentready

### ISSUE THREAD

**Issue by malladis** [angular/angular#31728]
Hey guys,

I am looking at this issue reported a while ago and closed with a patch -
https://github.com/angular/zone.js/issues/758 but looks like only a part of the problem was fixed but not the EventListener. When I navigate between angular webviews, the page is not getting rendered. None of the angular actions/bindings are working..

Need to patch document.addEventListener() specifically for the following Cordova events: pause, resume, activated, documentready (and possibly more - these are at least the ones for iOS). These events are specifically intercepted by Cordova before reaching the underlying (already-patched) APIs, and also do not run in the correct zone.

**Comment by jpduckwo** [comment]
Have a look at this. I believe it fixes the issue. I just wonder if this is something that might not be required with new versions of Angular?
https://weblogs.thinktecture.com/thomas/2017/02/cordova-vs-zonejs-or-why-is-angulars-document-event-listener-not-in-a-zone.html

**Comment by jessicajaniuk** [comment]
Thanks for reporting this issue. This issue is now obsolete due to changes in the recent releases. Please update to the most recent Angular version.

If the problem still exists in your application, please [open a new issue](https://github.com/angular/angular/issues/new/choose) and follow the instructions in the issue template.
