### ISSUE TITLE
[BUG] IE11 -> Can't execute code from a freed script

### ISSUE THREAD

**Issue by lifaon74** [angular/angular#31723]
**Context:**
- angular 5.0.0-rc3
- zone.js 0.8.18
- IE 11

I tried to update from zone 0.8.4 (current official angular 5 tutorials version) to 0.8.18, and get at some point with IE 11 the following error: `Can't execute code from a freed script`. This is a really imprecise error, that I didn't manage to find the origin but is due for sure from zone.js.

EDIT: after testing => appear from 0.8.12 (working) to 0.8.13 (no more working on IE 11)

**Comment by JiaLiPassion** [comment]
@Deepakm1051, please provide a reproduce repo, thanks.

**Comment by Deepakm1051** [comment]
@JiaLiPassion we found this issue bcoz of window.addEventListener(). We have a requirement like 
1. open two tabs and log in with the same account
2. logout in one tab and another tab also should logout automatically.
Thanks.

**Comment by eafiontzi** [comment]
In Angular 8, the polyfills.ts file specifically explains to create a new file in the same directory as polyfills.ts and add the zone checks in there. Then import it to the polyfills.ts file before zone.js. 
Quote from the file:
`/**
 * By default, zone.js will patch all possible macroTask and DomEvents
 * user can disable parts of macroTask/DomEvents patch by setting following flags
 * because those flags need to be set before `zone.js` being loaded, and webpack
 * will put import in the top of bundle, so user need to create a separate file
 * in this directory (for example: zone-flags.ts), and put the following flags
 * into that file, and then add the following code before importing zone.js.
 * import './zone-flags.ts';
 *
 * The flags allowed in zone-flags.ts are listed here.
 *
 * The following flags will work for all browsers.
 *
 * (window as any).__Zone_disable_requestAnimationFrame = true; // disable patch requestAnimationFrame
 * (window as any).__Zone_disable_on_property = true; // disable patch onProperty such as onclick
 * (window as any).__zone_symbol__UNPATCHED_EVENTS = ['scroll', 'mousemove']; // disable patch specified eventNames
 *
 *  in IE/Edge developer tools, the addEventListener will also be wrapped by zone.js
 *  with the following flag, it will bypass `zone.js` patch for IE/Edge
 *
 *  (window as any).__Zone_enable_cross_context_check = true;
 *
 */`

**Comment by gayankasun** [comment]
I couldn't find such a registry entry for Latest IE on Windows 10

**Comment by danielehrhardt** [comment]
Same Issue here

**Comment by AndrewKushnir** [comment]
Closing this ticket, since the reported problem was only present in IE11 and Angular no longer supports IE.
