### ISSUE TITLE
default Pipes not on by default 

### ISSUE THREAD

**Issue by jhades** [angular/angular#3173]
In alpha 31, the default pipes are not on by default. In an application bootstrapped without any extra configuration, the following code:

    {{'Hello World!' | uppercase}}

gets rendered as `Hello World!` instead of `HELLO WORLD!`. This is in a typescript setup, the problem can be reproduced like this:

- clone the [angular2-seed](https://github.com/mgechev/angular2-seed)
- npm install / gulp serve.dev
- add the code above on `home.html` - the string does not get uppercased

Apparently the default pipes should be (as indicated [here](https://github.com/angular/angular/blob/3bf8c18c56598e92b4c9055f9337a4da0ff37fb2/modules/angular2/src/change_detection/change_detection.ts)):

    export const defaultPipes: Pipes = CONST_EXPR(new Pipes({
      "iterableDiff": iterableDiff,
      "keyValDiff": keyValDiff,
      "async": async,
      "uppercase": uppercase,
      "lowercase": lowercase,
      "json": json,
      "limitTo": limitTo,
      "number": decimal,
      "percent": percent,
      "currency": currency,
      "date": date
    }));

**Comment by jessegood** [comment]
@jhades: I noticed that the uppercase and lowercase pipes work by adding 
`changeDetection:ON_PUSH` in your `@Component`.
However, it should still work with the default I believe.

**Comment by gdi2290** [comment]
@jhades @jessegood this was my fault sorry about that. I pushed up a PR with the correct fix https://github.com/angular/angular/pull/3189. The problem was that I was doing more work than I should by only transforming on reference change. This is why `changeDetection: ON_PUSH` would allow it to work since you're providing a new reference to the bindings which would correctly transform the value

**Comment by gkalpak** [comment]
FWIW, I don't think the issue was checking against the last input value, but the fact that in case of a match you would return the input value (not the transformed output).
Since these transforms are very cheap anyway, it's not worth having such an optimization in place anyway.

**Comment by gdi2290** [comment]
The problem was that I used `ObservablePipe` as reference since it was the only real pipe at the time. Then there was also an api changed to remove having to return `NO_CHANGE` reference when the transformation didn't need to happen (now changed to use `WrappedValue`). I was also doing smoke tests for the prototype pipe in an app that optimized the change detection for reference checks and the old pipe api. 
[change_detection/pipes/observable_pipe.ts](https://github.com/angular/angular/blob/b8e82e4db31bd44eec4488f8b77366c78ba92a8e/modules/angular2/src/change_detection/pipes/observable_pipe.ts#L47...L64)
`ObservablePipe` has to maintain reference of the Observable and has essentially 4 states in which the transform does something different that causes side effects: Observable without a subscription, Observable with a subscription, current value/returned value are the same, and current value/returned value are different. I only know this because I had to create an `ObservablePipe` that prevented a cycle from happening when a change returns a new Observable reference. So there's actually a potential bug where the first state should return the returned value and the returned value should be dereferenced during the onDestroy Pipe lifecycle rather than the Observable reference lifecycle. With all that said I should have went back to refactor the pipes so that's my bad

**Comment by gkalpak** [comment]
Looking at the commit that closed this issue (4dc6d74), I thought it was the fact that the [untransformed value][1] was returned after the initial invokation.
<sub>
But I don't know much about pipes, so I probably misread that :disappointed:
Sorry for the noise :smiling_imp: 
</sub>

[1]: https://github.com/angular/angular/commit/4dc6d748a9272f4105d730fa4e78f62167d196aa#diff-2647cb0e5e52196de97c3197818af858L37
