### ISSUE TITLE
script loaded via dynamically script tag injection is not in the zone

### ISSUE THREAD

**Issue by zhy2002** [angular/angular#31748]
If I load a script file this way:

```
      function loadScript() {
        Zone.current.fork({name : 'dynamic'}).run(function() {
          console.log('loading zone', Zone.current);
           var script = document.createElement ("script");
           script.type = "text/javascript";
           script.src = "dynamic-script.js"; 
           document.body.appendChild(script);
        });

      }
```

The output is:

```
loading zone Zone {_properties: Object, _parent: Zone, _name: "dynamic", _zoneDelegate: ZoneDelegate}
dynamic-script.js:3 loaded zone: Zone {_properties: Object, _parent: null, _name: "<root>", _zoneDelegate: ZoneDelegate}
```

Is this the expected behaviour?

See plunker: http://plnkr.co/edit/0OfIJ2QyY0g1aaVfU2rp

**Comment by mleibman** [comment]
@JiaLiPassion, sorry for the delayed response.

I ended up resolving this in a similar fashion for an internal project at Google, so let me share some comments and overall things that need to be taken care in a solution to this.

**Security**

First of all, unlike regular `<script>` tags, fetching the script using either `fetch()` or `XmlHttpRequest` is subject to Cross-Origin Resource Sharing (CORS) policy, so this approach isn't something that can be done universally w/o either a CORS proxy or control over the server configuration.


**Patching**

Patching the `HTMLScriptElement.prototype.src` isn't enough since there are other ways in which it scripts can be injected or in which the `src` can be set - `setAttribute()` (and other attribute APIs such as `Attr`), `cloneNode()`, `insertAdjacentHTML()`, etc. You also need to handle some browser quirks like it always ignoring any changes to the `src` attribute after it has initially been set.

**Loading & performance**

Fetching the script source does utilize the browser's file cache, but the evaluation part is an issue. Any way to alter the script source results in the code cache (AST cache) getting dropped (see https://v8.dev/blog/code-caching-for-devs). Based on my benchmarking, this isn't a significant issue however. Still, evaluating the script using `Function()` is less than ideal since it requires decoding the fetch response and allocating additional memory. My solution was to load the source as a blob, then use the `Blob()` constructor (https://developer.mozilla.org/en-US/docs/Web/API/Blob/Blob) to append some code before and after w/o having to decode the response and convert it to a string. The blob is then turned into an object URL via `URL.createObjectURL()`. Finally, we set the `src` of the `<script>` element to that instead of the original script URL.

In my case, the same script URL can be loaded multiple times, so we cache the mapping of script URLs to wrapped object URLs. This way the code cache gets utilized on the next load, and no additional memory gets used.

**Evaluation**

In addition to requiring extra memory allocation compared to the blob + object URL approach, your proposed way of evaluating the script doesn't quite work with the script declaring global variables in non-strict mode:

```javascript
// In non-strict mode, top-level declared variables become globals.
window.func = Function('a = 123; var b = 456;');
window.func();

// prints 123, undefined
console.log(window.a, window.b);
```

The only way I found to preserve them is to evaluate them in a `try-finally` block:

```javascript
try {
  // <enter the zone>
  // <script source>
} finally {
  // <exit the zone>
} 
```

**Developer experience**

Scripts are often served with trailing `sourceMappingURL` marker comment (https://developer.mozilla.org/en-US/docs/Tools/Debugger/How_to/Use_a_source_map):

`//# sourceMappingURL=http://example.com/path/to/your/sourcemap.map`

By wrapping the original script, the comment is no longer at the end where it needs to be, so some additional processing needs to be done to copy it to the original spot. This can be done efficiently by only looking at the last ~500 bytes of the response blob.

Also, when debugging the app in Dev Tools, it is difficult to tell what script URL the object URL script corresponds to, so you should add a comment with the original URL at the top of the wrapped blob.

**Comment by JiaLiPassion** [comment]
@mleibman , thank you very much for the detailed research, I will check them too, it maybe a little tricky to resolve all those cases. will report back to you when I have some progress.

**Comment by alxhub** [comment]
Closing due to lack of feature votes, and this does seem like the expected behavior.
