### ISSUE TITLE
Angular-8: missing `node_modules\@angular\core\src\di ...`folders

### ISSUE THREAD

**Issue by dsuwirya** [angular/angular#31826]
Hello,

I have an older angular library (built using Angular 6) that's somehow has the following import in its .module.d.ts file:
`provide: import("@angular/core/src/di/injection_token").InjectionToken<(() => void)[]>;`

This is broken since I'm upgrading my app (which is using the above library) to Angular-8 as it seems most of folders/files under the `node_modules\@angular\core\src\...` are no longer there now. I checked and they are still there up to latest version of Angular-7.

Would it be possible to restore all the folder/files under that src folder in Angular-8 too so it can be still backward compatible?

Thanks.

**Comment by alxhub** [comment]
Hi @dsuwirya, thanks for bringing this issue to our attention. It looks like is the result of .d.ts bundling which landed in recent Angular releases. Unfortunately it's not really possible to make this change in a backwards-compatible way. The good news is that recompiling the library should immediately fix the problem.

**Comment by alxhub** [comment]
I've actually decided to close this issue, after I thought some more about this and came to a realization: Angular's exact .d.ts structure cannot be considered public API, because our internal directory layout can be refactored at any time. Libraries should not be relying on specific imports into the .d.ts tree.
