### ISSUE TITLE
Assign form value to model object

### ISSUE THREAD

**Issue by 13590dhimant** [angular/angular#31964]
🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑

User:user;
 constructor(private fb: FormBuilder) {
    this.createForm();
  }

  createForm() {
    //form control name should match with User class property name
    this.userForm= this.fb.group({
      name: ['', Validators.required ],
      street: '',
      ..other property
    });
  }

  submit() {

// This line doesn't give the update value of form if I have change any of them
   this.user = userForm.value;
   
// If I do below one by one for each property, then it gives the update value
   this.user.Name = this.userForm.get('name').value;
   ..do for all property 
  }

PROBLEM : Sometimes form have 20 or more than that fields and in that case then I have to write 20 statement to get the update value for each property.
🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑

**Comment by AndrewKushnir** [comment]
@13590dhimant, it looks like this ticket doesn't contain enough information and doesn't follow the template. I'm closing this ticket due to insufficient info provided, please create a new one with additional information (by following the Feature Request template), so the team and community members can have a look. Thank you.
