### ISSUE TITLE
Template error: Can't bind to 'ngForOf' since it isn't a known property of 'tr'. - ERROR in In Ivy 

### ISSUE THREAD

**Issue by webmasters964** [angular/angular#31994]
Template error: Can't bind to 'ngForOf' since it isn't a known property of 'tr'.   this issue 

![image](https://user-images.githubusercontent.com/4738163/62426135-9d637480-b6fe-11e9-8cb1-36020bcfa05c.png)

import the BrowserModule in app module
```

import { BrowserModule } from '@angular/platform-browser';
import { BrowserAnimationsModule } from '@angular/platform-browser/animations';

@NgModule({
  declarations: [
    AppComponent    
  ],
  imports: [
    BrowserModule, BrowserAnimationsModule,
  ],
  exports: [],
  providers: [],
  bootstrap: [AppComponent],
  schemas: [CUSTOM_ELEMENTS_SCHEMA]
})
```

**Comment by JoostK** [comment]
This was likely fixed in #31913 which will be included in `9.0.0-next.1` once it's released. Therefore, closing for now. Feel free to open a new issue if you experience the same problem with the new release (once it's available).

@webmasters964 I would kindly request you to fill out the issue template when opening issues, as this issue's description does not provide the information that's needed to investigate your problem. Please check out [our submission guidelines](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-submitting-an-issue) to understand why we can't act on issues that are lacking important information.
