### ISSUE TITLE
ngcc - handle deep imports during dependency resolution

### ISSUE THREAD

**Issue by petebacondarwin** [angular/angular#32097]
Recently we have been failing to compile some ngcc target packages because the package has a deep import into another package. Previously we would log this with a warning but continue regardless. Now ngcc appears to crash instead.

In the case that the deeply imported package is not even an Angular compiled library, it makes not difference whether the package is imported deeply or not.

Ngcc should be more resilient to this kind of thing. In particular it should walk up the directory tree to find the nearest package.json and use that as the entry-point - possibly warning that this is a deep import.

Examples of this behaviour are `ngx-swiper-wrapper` (https://github.com/zefoy/ngx-swiper-wrapper/issues/226) and `delonabc` (https://github.com/mgechev/ngcc-validation/issues/110).

**Comment by JoostK** [comment]
The issue reported in zefoy/ngx-swiper-wrapper#226 can be attributed to this issue and I verified that with PR #32181 ngcc is able to process the `ngx-swiper-wrapper` package successfully.

For mgechev/ngcc-validation#110 however, the issue with `date-fns` is different. The reason is that `date-fns` is split into small entry-points, each having a dedicated `package.json` file. So, the imports are not actually deep imports. ngcc fails to process those entry-points as the `package.json` file of all entry-points are very minimal, for instance:

```json
{
  "typings": "../typings.d.ts"
}
```

This is problematic for ngcc, as it currently requires at least one of `fesm2015`, `fesm5`, `es2015`, `esm2015`, `esm5`, `main`, or `module`. We can workaround the issue using ngcc's configuration files, although currently it requires to configure each and every secondary entry-point as ignored (of which there's 155 of within `date-fns`!), as ignoring a full package is not (yet) possible.

**Comment by lppedd** [comment]
@Jacksunwei yeah, I had to specify a `main` entry point for all of the `date-fns` sub-modules.

**Comment by tomastrajan** [comment]
@lppedd can you please elaborate bit more about the fix ? also where is `ngcc.config.js` ?

**Comment by lppedd** [comment]
@tomastrajan sure. The `ngcc.config.js`  should be located in the root of your Angular project.
An example content for `date-fns` might be
```
module.exports = {
  packages: {
    'date-fns': {
      entryPoints: {
        '.': {
          override: {
            main: 'index'
          }
        },
        './add_days': {
          override: {
            main: 'index'
          }
        },
        './add_hours': {
          override: {
            main: 'index'
          }
        },
...
```

**Comment by JoostK** [comment]
@lppedd @tomastrajan It's no longer needed since #32303 was merged, but I don't think that has been released yet. Will be in 9.0.0-next.4, which is expected to be released soon.

**Comment by tomastrajan** [comment]
@JoostK what about 8.x line ?

**Comment by lppedd** [comment]
@JoostK Oh thank you! That library has hundreds of sub-modules...  
@tomastrajan In my case I will simply upgrade to 9 as soon as it's out, it should be transparent.

**Comment by JoostK** [comment]
@tomastrajan Ivy fixes are not backported to 8.x, as Ivy is still in preview.

**Comment by tomastrajan** [comment]
@JoostK yes, but there was some announcement that the Ivy will be enabled by default from 8.3 which kinda got us scared and hectic in terms of preparation ?

**Comment by JoostK** [comment]
@tomastrajan Do you remember information about that announcement? If so, could you share details with @StephenFluin?

**Comment by tomastrajan** [comment]
@JoostK @StephenFluin will search for the tweets / changelogs and post links here soon

**Comment by tomastrajan** [comment]
@JoostK @StephenFluin pffu can't find anything anymore but me and my colleague both saw it somewhere like 2 days ago, maybe it was mistaken tweet which was taken down, dunno, very strange, anyway if this is the case than that's amazing and we can give ivy a bit more time in the organization...
