### ISSUE TITLE
Forward declaration of parent child dependency injection not user friendly?

### ISSUE THREAD

**Issue by jomeier** [angular/angular#3216]
#2660

describes a problem I also have with Visual Studio 2013 and Typescript 1.5. 

The solution is using 

```
    constructor( @Ancestor @Inject(forwardRef(() => MyAppComponent)) my: MyAppComponent) {
       ...
```

but I don't think this is very user friendly cause it should be a normal use case that a parent component uses a child component and if this child component tries to inject it's parent component that this will result in a forward declaration which requires the above line of code.

This leads to constructors which will always need ```forwardRef```.

Is this the preferred way to handle Parent/Child DI or is there a better way to do this with TS?

Thanks and best regards,

Josef

**Comment by mhevery** [comment]
This is a limitation of JS and how the function declarations get hoisted. Whenever you have a circular dependency you will need `forwardRef` :-( I just don't see a away around it.

I would argue that you should not be in situation where your parent needs to know about the children and children need to know about parent. `@Query` should take care of most of the use cases.

I am sorry, but while I agree this is a pain in some rare cases, I don't see a way out of it, and hence this issue is not actionable, will close.

**Comment by gionkunz** [comment]
@mhevery I agree this is expected behaviour when working within a single file and referencing a Class from further down in the file. Since classes get de-sugared without function declarations, they will not be hoisted, so the order of will play a role when referencing classes within the same file.

However, currently using SystemJS with TypeScript, this is also a problem for circular references between modules. However, I thought the ES6 module loader specification is dealing with this using a zebra-striping technique (https://github.com/ModuleLoader/es6-module-loader/wiki/Circular-References-&-Bindings) ? So why do we need to use `forwardRef` in circular reference situations? Is this a TypeScript issue?

**Comment by mhevery** [comment]
This is a language issue. Classe do not get hoisted in ES6 like functions declarations do.

**Comment by gionkunz** [comment]
Yes, but as I said, this is relevant for class declarations within the same file. But shouldn't be an issue for cross-module dependencies, right?

**a.js**
```javascript
  import { B } from './b.js'

  export class A {
    static name() {
      return 'A';
    }

    constructor() {
      const b = new B();
      b.sayHello('Hey there!');
    }
  }
```

**b.js**
```javascript
  import { A } from './a.js';

  export class B {
    sayHello(what) {
      console.log(`${A.name()} says: ${what}`);
    }
  }
```

Those classes will not be declared within the same closure so their hoisting is independent. It's up to the module loader how to resolve this circular reference problem and it has nothing to do with hoisting, no?

**Comment by mhevery** [comment]
i believe you are correct.

**Comment by gionkunz** [comment]
The above example works with TypeScripe and SystemJS, but only because the dependency to `A` from `B` is not used within the module body directly.

The problem occurs if you have two dependencies `A` and `B`, both importing each other, and both using each other within the immediate call stack of the module body execution. If you import `A` from `C` then `B` will not know `A` within the module body. If you import `B` from `C` then the module `A` will not know `B` within the module body. I guess that's a limitation of the ES6 module loader specification.

Since decorators get executed within the same call stack as the module body execution, circular module dependencies will be uninitialized within one of the module. :-( Also, due to the nature of decorators, it probably won't be possible to desugar to something more lazy that will unwrap the whole decorator parameters during reflection.

The only option left seems to be to defer unwrapping the reference which can only be done by creating a function, like `forwardRef`.
