### ISSUE TITLE
Shorthand syntax for `ng-container` and `ng-template`

### ISSUE THREAD

**Issue by superamadeus** [angular/angular#32191]
# 🚀 feature request

### Relevant Package
This feature request is for @angular/core

### Description
`ng-container` and `ng-template` are incredibly useful tools, but their selectors are extremely verbose when you consider how fundamental they are.

### Describe the solution you'd like
A possible solution would be to add a shorthand tag names for these. I propose: `@` for `ng-container` and `#` for `ng-template`.

It would turn this contrived example:

```
<ng-container *ngIf="book">
    <ng-container *for="let chapter of book.chapters">
        {{ chapter.name }}
        <ng-container *ngIf="!chapter.locked; else previewLocked">
            <div class="chapter-preview">
                {{ chapter.preview }}
            </div>
        </ng-container>
    </ng-container>
</ng-container>

<ng-template #previewLocked>
    <div class="chapter-preview-locked">
        Sign up to read this chapter!
    </div>
</ng-template>
```

into this:

```
<@ *ngIf="book">
    <@ *for="let chapter of book.chapters">
        {{ chapter.name }}
        <@ *ngIf="!chapter.locked; else previewLocked">
            <div class="chapter-preview">
                {{ chapter.preview }}
            </div>
        </@>
    </@>
</@>

<#previewLocked>
    <div class="chapter-preview-locked">
        Sign up to read this chapter!
    </div>
</#>

```

### Describe alternatives you've considered
1. Writing a preprocessor to do this to my projects.
2. Dealing with the verbosity.

**Comment by mlc-mlapis** [comment]
@superamadeus Because of the `<... #anyname>` is already used for defining a local template variable and it would be misleading/unreadable to use the same syntax for both of them.

What about: `<ng-container>` -> <ng@>` and `<ng-template>` -> <ng#>`? 🛩

**Comment by superamadeus** [comment]
@mlc-mlapis I recognized this concern when I first ran into it but I don't think it would be _that_ bad. Considering that this is describing a shorthand for optionally declaring a TemplateRef template variable, its similarity/use of the same symbol may be more intuitive. 

Obviously it can get ugly when you have a case like this (assuming `myDirective` exports as `"myDirective"`):
```<# myDirective #theTemplate #theDirective="myDirective"></#>```
That said, I think that is less common than simply declaring a template and creating a template variable. Also, in this case, you can forego using the shorthand syntax.

**Comment by Airblader** [comment]
I don't see the issue that is being solved here. It's more syntax, more learning curve and more complexity for no functional gain. If you want to type less, IDEs provide a lot of functionality for you like autocompletion or macros.

**Comment by superamadeus** [comment]
I find it hard to believe that `<#myTemplate></#>` is "unreadable" or so complex that one line of documentation would not be able to make up for it. I understand the desire to not add more syntax but I don't think it's very complex. It's just foreign because it's not part of the current syntax. Would any of you say the same thing about the `*` shorthand for structural directives if it were being introduced at this point? 

```
<ng-template [ngIf]="condition">
    <div>Content to render when condition is true.</div>
</ng-template>

<ng-template ngFor let-book [ngForOf]="books" let-i="index" [ngForTrackBy]="trackByFn">
  <a-book [model]="book"></a-book
</ng-template>
```

vs.

```
<div *ngIf="condition">Content to render when condition is true.</div>
<a-book *ngFor="let book of books; let i = index; trackBy: trackByFn" [model]="book"></a-book>
```

The issue it solves is one of verbosity. It makes it slightly more ergonomic to use templates + template/component outlets.

```
<my-header>
    <@ *ngIf="isLoggedIn; then: loggedInMessage; else: loggedOutMessage"></@>
</my-header>

<#loggedInMessage>Welcome back!</#>
<#loggedOutMessage>Sign up to read more.</#>
```

**Comment by trotyl** [comment]
The first character of an element must be alphabetic letter, which is the [requirement of HTML syntax](https://html.spec.whatwg.org/#parse-error-invalid-first-character-of-tag-name).

![image](https://user-images.githubusercontent.com/6059170/63398101-194c0500-c3ff-11e9-8d13-f4f1d544d44f.png)

**Comment by superamadeus** [comment]
The selector would be transformed before ever becoming an element. This is what is done with transforming `<div *ngIf="...">....` -> `<ng-template [ngIf]="..."><div>...</div></ng-template>`, correct?

That said, I recognize this would make the template allow a special case of invalid html syntax.

**Comment by trotyl** [comment]
> This is what is done with transforming `<div *ngIf="...">`.... -> `<ng-template [ngIf]="..."><div>...</div></ng-template>`, correct?

Negative, `<div *ngIf="...">` itself is in valid HTML syntax, that's why it can be put in a `.html` file and utilize existing syntax highlighting and formatting without any knowledge of Angular.

**Comment by superamadeus** [comment]
@trotyl Just trying to make sure I fully understand; there's no transformation of `<div *ngIf="...">...` to the `ng-template` before it becomes an HTMLElement in the DOM?

**Comment by trotyl** [comment]
> there's no transformation of `<div *ngIf="...">`... to the `ng-template` before it becomes an HTMLElement in the DOM?

There’s indeed **no such transformations**, the expansion of microsyntax is a post-parsing task that happened at AST, not source code, and it will never be serialized to HTML again, but to JavaScript.

As you can see in your template file, the content is `<div *ngIf="...">`, what it logically means is a semantic stuff, and if you want to name it `foo.component.html`, it need to be conforming to HTML syntax for editor compatibility.

**Comment by hakimio** [comment]
Ok, here are few issues with this kind of syntax:

1. It's actually **slower** to type/has **worse ergonomics.** Right now I can just type "<ng-c" and IDE will autocomplete the rest without ever moving my palms. Typing "<ng-@" is a lot more cumbersome because at least on "en-US" keyboard layout you have to use right "Shift" key plus move both of your hands from their normal typing position. Same with "#".
2. It looks **ugly** and makes the html template harder to read for someone just starting to learn Angular. It increases learning curve for no good reason.
3. Nobody uses 80 column screen anymore, so minor difference in line length is not something most people are concerned about. If you are using a lot of nesting in your template , most likely it's time to refactor and extract some parts to new components.

**Comment by lazarljubenovic** [comment]
> Typing "<ng-@" is a lot more cumbersome because at least on "en-US" keyboard layout you have to use right "Shift" key plus move both of your hands from their normal typing position. Same with "#".

Are you really bringing up the "shift key" argument? You're pressing that key for every capital letter, for every `(){}!"` you type in code (all extremly common)... It's absolutely not "a lot more cumbersome" to type in a common ASCII character just because it uses a shift character...

> It looks ugly

That's subjective. I find a bunch of `ng-template` and `ng-container` uglier over a symbol. We're trained to recognize symbols easier than words. It's must easing to spot a `@` than a word `template` or `container` in the middle of template.

> makes the html template harder to read

Angular already uses `[]`, `()`, `{{ }}`, `*` in templates, which are all symbols. Heck, even HTML is full of symbols `<`, `>`, `=`, `"`. By your logic, this is ugly:

```
<div *ngIf="foo.bar == 1">{{ baz }}</div>
```

and this is pretty:

```
start opening html tag
div 
structural directive ngif 
property access foo bar 
equals 
one 
end opening html tag
start interpolation
baz 
end interpolation 
start closing html tag 
div 
end closing html tag
```

Developers already recognize thousands of symbols in different contexts: `*` can easily mean "multiplication", "match any character", "match the character none or many times" or "angular structural directive". When you see `<div>` you don't think that someone is trying to do a comparison `1 < div > 3`, you know from context what the symbol means.

>  for someone just starting to learn Angular

You cannot tailor your API to be suitable to beginners and only beginners. Everything useful will always have more advanced things which take time to learn. Just because something isn't easily digestible by a random person on the street in five minutes, doesn't mean it's not useful for a developer.

I really don't see how anyone can say that this:

```html
<*ngFor="let item of array">
  <*ngIf="foo">
    <*ngTemplateOutlet="tpl"/>
  </*ngIf>
</*ngFor>
```

is somehow less attractive than this:

```html
<ng-container *ngFor="let item of array">
  <ng-container *ngIf="foo">
    <ng-container *ngtemplateOutlet="tpl"></ng-container>
  </ng-container>
</ng-container>
```

I understand other reasons, such as:

- it strays too far from HTML (and that's not what the team wants)
- it brings too much complexity into the Angular template parser with no obvious benefit
- it's not a priority

But arguing that it's "more difficult to grasp", "more difficult to type", "looks ugly" is just plain ridiculous.
