### ISSUE TITLE
Bootstrap error when InjectionToken token is used with Angular Elements

### ISSUE THREAD

**Issue by popsovy** [angular/angular#32280]
I am bootstrapping a module as web components using createCustomElement. The module also includes a provider used for external redirects. 

```
import { BrowserModule } from '@angular/platform-browser';
import { NgModule, Injector, InjectionToken } from '@angular/core';

import { AppRoutingModule } from './app-routing.module';
import { AppComponent } from './app.component';
import {createCustomElement } from '@angular/elements';
import { ActivatedRouteSnapshot } from '@angular/router';

@NgModule({
  declarations: [
    AppComponent
  ],
  imports: [
    BrowserModule,
    AppRoutingModule
  ],
  providers: [
    {
    provide: new InjectionToken('externalUrlRedirectResolver'),
    useValue: (route: ActivatedRouteSnapshot) => {
    }
  }
],
  entryComponents: [AppComponent]
})

export class AppModule {
  constructor(private injector: Injector) {
  }

  ngDoBootstrap(){
    customElements.define('my-app', createCustomElement(AppComponent, {injector: this.injector}));
  }
}
```

When serving with **ng serve**, it works with no problems.

After building for production (**ng serve --prod** or **ng build --prod**), I get a runtime error:

> ERROR Error: The module Function was bootstrapped, but it does not declare "@NgModule.bootstrap" components nor a "ngDoBootstrap" method. Please define one of these.

When building for production and disabling AOT and optimizations, it works fine (i.e. **ng build --prod --aot=false --buildOptimizer=false**).

Commenting out the provider solves the runtime error meaning **ng build --prod** works with optimizations enabled. It's something about having that provider that messes up the production build.

The complete source is here -- https://github.com/popsovy/NoBootstrapError

**Comment by JoostK** [comment]
Well, this is an awkward bug 😲

I am quite surprised at this setup, though. What are you trying to achieve with this provider registration:

```ts
{
    provide: new InjectionToken('externalUrlRedirectResolver'),
    useValue: (route: ActivatedRouteSnapshot) => {
}
```

I don't see how the injection token that is provided here can ever be requested somewhere, as no one has a handle on the injection token itself it can never be recovered from the `Injector`.

Anyway, the code works as-is in the new Ivy renderer that has been released as part of Angular 9.0. For older versions, there is an easy workaround: move the `new InjectionToken('externalUrlRedirectResolver')` to an exported variable:

```ts
export const externalUrlRedirectResolver = new InjectionToken('externalUrlRedirectResolver');
```

and replace the provider using:

```ts
{
    provide: externalUrlRedirectResolver,
    useValue: (route: ActivatedRouteSnapshot) => {
}
```

Since the issue has been resolved with Ivy, I am closing this issue.
