### ISSUE TITLE
Incorrect default output path for `ng xi18n`

### ISSUE THREAD

**Issue by mirismaili** [angular/angular#32386]
# 📚 Docs or angular.io bug report

### Description

As I tested in my new Angular project, the `messages.xxx` file is generated in the root directory of the project, not `src/` folder that is said [here](https://angular.io/guide/i18n#create-a-translation-source-file):

> By default, the command creates a file named `messages.xlf` in your `src/` folder.

The other point is that the extension of the file is not `.xlf` always, as you know.

### Reproduction Steps**
```bash
> ng new TempProject
   ...
> cd TempProject
> ng xi18n

> ls src
> ls .
```

### Expected vs Actual Behavior**
> **By default, the command creates a file named `messages.XXX` in your project's root directory.**

## 🌍  Your Environment

```
node: v12.6.0

@angular/common: v8.2.3,
@angular/compiler: v8.2.3,
@angular/core: v8.2.3,

@angular-devkit/build-angular: v0.803.0,
@angular/cli: v8.3.0,
@angular/compiler-cli: v8.2.3,
@angular/language-service: v8.2.3
```

**Comment by kapunahelewong** [comment]
Thanks for the repro steps. I followed them and got `.xlf`. What are the other file extensions, and what determines them being different, @mirismaili?

**Comment by jbogarthyde** [comment]
@mirismaili The doc is correct in stating that command creates a file with this extension **by default**. In the later "Output options" section, it explains how you can provide the `--i18n-format` option to choose a different format, which would create a file with a different extension.

Since the file location error has been fixed by the referenced PR, I'm closing this -- please reopen and comment if you don't agree.
