### ISSUE TITLE
ivy loses query results in abstract @Directive() when CLI rebuilt (file change)

### ISSUE THREAD

**Issue by elvisbegovic** [angular/angular#32416]
# 🐞 Bug report

### Command
```
- [x] serve
```

### Description
In IVY v9 ([see here](https://github.com/angular/angular/commit/405515091040759c1e65e79b0dde3ab77e04975e)), we'll need to add abstract `@Directive()` on abstracts classes we extends that contain Angular stuff (like Input, ViewChild, DI).
After add `@Directive()` on my abstract class and run `ng serve` everything works well. 
But If I edit abstract directive file and save, browser autoreload but query results are not resolved anymore ?!?! 

## 🔬 Minimal Reproduction
One line repro : 
`git clone https://github.com/elvisbegovic/issue-ivy-abstract-directive.git && cd issue-ivy-abstract-directive && npm i && ng s`

Open browser localhost:4200, open devtools console, you will see consoel without error, viewchild is available.

Edit or comment anything in [any-abstract-class.ts](https://github.com/elvisbegovic/issue-ivy-abstract-directive/blob/master/src/app/any-abstract-class.ts#L10-L21) file (cli rebuild + autoreload browser) you can see error at runtime that viewchild `this.myList` is undefined.

GIF:
![ivyrebuild](https://user-images.githubusercontent.com/2789203/64019596-dccf8600-cb2f-11e9-8d0c-83661c5dba21.gif)

## 🔥 Exception or Error
After browser auto reload :
<pre><code>
ERROR TypeError: Cannot read property 'name' of undefined
    at AppComponent.ngOnInit (any-abstract-class.ts:11)
    at AppComponent.ngOnInit (app.component.ts:17)
    at callHook (core.js:7864)
    at callHooks (core.js:7828)
    at executeInitAndCheckHooks (core.js:7769)
    at refreshView (core.js:12199)
    at renderComponentOrTemplate (core.js:12288)
    at tickRootContext (core.js:13648)
    at detectChangesInRootView (core.js:13683)
    at RootViewRef.detectChanges (core.js:15205)
</code></pre>

In CLI console : 
` ERROR in src/app/app.component.ts(8,5): error TS8001: 'my-list' is not a valid HTML element.`

## 🌍 Your Environment
<details>
<summary>See environment</summary>
<pre><code>
Angular CLI: 9.0.0-next.2
Node: 12.9.1
OS: win32 x64
Angular: 9.0.0-next.4
... animations, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.900.0-next.2
@angular-devkit/build-angular     0.900.0-next.2
@angular-devkit/build-optimizer   0.900.0-next.2
@angular-devkit/build-webpack     0.900.0-next.2
@angular-devkit/core              9.0.0-next.2
@angular-devkit/schematics        9.0.0-next.2
@angular/cli                      9.0.0-next.2
@ngtools/webpack                  9.0.0-next.2
@schematics/angular               9.0.0-next.2
@schematics/update                0.900.0-next.2
rxjs                              6.4.0
typescript                        3.5.3
webpack                           4.39.3
</code></pre>

</details>

**Anything else relevant?**
Problem is only when you edit `any-abstract-class.ts` file, if after first build you edit other file = no error.

If I add `selector` to Directive and add it to NgModule` declarations[]`, all works as before.

This is working in View Engine (jit and aot and without decorating abstract classes) 

Maybe related to https://github.com/angular/angular/issues/31560 and all referenced issues

Maybe this can live on angular/angular ?

**Comment by petebacondarwin** [comment]
I think the solution would be for ngtsc to include all ancestors of components as dependencies that would trigger a rebuild of that component.

**Comment by alxhub** [comment]
This shouldn't _need_ to be the case (for locality) but probably should be because of type-checking.

**Comment by elvisbegovic** [comment]
Will this be solved for 9.0 final?

**Comment by petebacondarwin** [comment]
I think it should. We just need someone with time to look into it. :-/

**Comment by brgrz** [comment]
This also happens when no Directives are involved (only components). I have a setup of AppComponent and LayoutComponent and only included the LayoutComponent within the AppComponent markup and the project runs fine immediately after ng serve then breaks down (meaning noth in LayoutComponent gets rendered) after the first CSS/Less/HTML change in any of the two components. 

Thankfully setting `enableIvy `to `false `solves this.

**Comment by JoostK** [comment]
Here's a breakdown of the issue:

Abstract directives are not registered with an NgModule, so if the directive is updated the NgModule is not invalidated. The component subclass however is correctly tracked as being dependent on its parent. During incremental state reconciliation, this means that the change to the abstract directive has this effect:

1. Metadata for the abstract directive is dropped, as the directive has changed.
1. Metadata for the component is dropped, as one of its dependencies has changed.
1. Metadata for the NgModule is kept, as no dependent file was changed.

During the subsequent compilation, the NgModule is considered to be safe to skip, which means that none of its metadata is analyzed and registered with `LocalModuleScopeRegistry`. Basically, this code is not executed:

https://github.com/angular/angular/blob/a42057d0f8ea3f8bd7c0afc2b92a29f1800cf787/packages/compiler-cli/src/ngtsc/scope/src/local.ts#L113-L119

Notice how this is responsible for the knowledge of which declarations correspond with which NgModule.

The abstract directive and component _are_ reanalyzed, because their source file is correctly deemed unsafe to skip analyzing. Consequently, the component requests its module scope:

1. the `LocalModuleScopeRegistry` does not have the required information, as the NgModule was not analyzed so no metadata is present locally.
1. the `IncrementalState.getScopeForComponent` is considered, however the scope info that was set aside during the first compilation here:

https://github.com/angular/angular/blob/a42057d0f8ea3f8bd7c0afc2b92a29f1800cf787/packages/compiler-cli/src/ngtsc/scope/src/local.ts#L129-L131

is no longer available, as the component resides in a file for which no metadata was copied over during incremental state reconciliation as its metadata was deemed outdated (because of the dependency on the abstract directive).
