### ISSUE TITLE
NgFor (and IterableDiffer) should support Map as input

### ISSUE THREAD

**Issue by paulferaud** [angular/angular#32446]
# 🚀 NgFor should support Map as input (it’s iterable)

### Relevant Package
`@angular/core`

### Description
When passing a Map to `ngFor`, you get: `Cannot find a differ supporting object '[object Map]' of type 'object'`.

This is confusing, since a Map *is* Iterable, and (AFAICT) adheres to the `NgIterable` interface. I’d expect the `ngFor` to "just" iterate on the `[key, value]` array.

I believe the issue is within IterableDiffer.

### Describe the solution you'd like
I’d like to be able to pass a `Map` to `IterableDiffers.find` (or `ngFor`) and for it to work.

### Describe alternatives you've considered
You could try to use the `keyvalue` pipe but:

- It does not preserve order (http://go/ngissue/31420)
- The pipe is not pure, and can be somewhat heavy duty

You could also just use `myMap.entries()`, but this returns a new object on every call, which could create some churn during change detection.

**Comment by mhevery** [comment]
See https://angular.io/api/common/KeyValuePipe

**Comment by mlc-mlapis** [comment]
@mhevery There is `KeyValuePipe`, but still the direct support for `Map` or `Set` has serious advantages and should be included for sure.

**Comment by trotyl** [comment]
@mhevery The problem is not about iterating `Map` being suggested or not, but `Map` being a deliberate exclusion from `Iterable`:

https://github.com/angular/angular/blob/04d4fea3e8784ea81916b24f3b153331967bad71/packages/core/src/change_detection/change_detection_util.ts#L70

This won't be consistent in any sense, either `Map.prototype.entries` as well as custom equivalent `Map` implementation (including ponyfill) will work, only the nominal global `Map` instance doesn't.
