### ISSUE TITLE
Strange routing / query behaviour with Location.go

### ISSUE THREAD

**Issue by Errors4l** [angular/angular#32469]
# 🐞 bug report

### Affected Package

The issue is caused by package @angular/router or @angular/common.

### Is this a regression?

No.

### Description

When using Location.go (`@angular/common`), Angular's routing starts behaving strangely when using the browser's back and forward button.

After calling `location.go`, using the browser back button doesn't register query changes. I expected this behaviour because I'm not using the router to navigate.  

However, using the browser forward/back buttons after this **does** register query changes. The same happens when calling `location.go` twice before using the browser buttons.

I can understand the routing may be needed because you could use the history to navigate to a different page, but then I'd expect the same behaviour on the first entry (on the first location push and the first back press).  

In my use case, I am trying to catch the pop state manually when within the same page. This works nicely for every entry added, but the inconsistent behaviour of the router is getting in the way. When navigating to the same url (with a different query), I'd like to prevent Angular's routing and handle it myself with `location.subscribe`.  
Perhaps this is possible by manipulating the history state using `history.pushState`? My attempts there failed.

## 🔬 Minimal Reproduction

https://stackblitz.com/edit/angular-router-basic-example-5kgjqs

> Note: the embedded demo seems to behave differently and starts reloading the page entirely, which I assume is a stackblitz problem. **Please view the demo at https://angular-router-basic-example-5kgjqs.stackblitz.io/start**, which behaves the same as my local project (on Chrome, Firefox and Edge).

*  Press <kbd>Push</kbd> to add a new query to the browser history using `location.go`.
* Press the browser back button and witness no query change.
* Press the browser forward/back buttons and witness a query change every time you navigate.

## 🌍  Your Environment

**Angular Version:**
<pre><code>
@angular-devkit/architect         0.802.1
@angular-devkit/build-angular     0.802.1
@angular-devkit/build-optimizer   0.802.1
@angular-devkit/build-webpack     0.802.1
@angular-devkit/core              8.2.2
@angular-devkit/schematics        8.2.2
@angular-devkit/schematics-cli    0.802.2
@angular/cdk                      8.1.2
@angular/cli                      8.2.1
@angular/http                     7.2.15
@ngtools/webpack                  8.2.1
@schematics/angular               8.2.1
@schematics/schematics            0.802.2
@schematics/update                0.802.1
rxjs                              6.5.2
typescript                        3.5.3
webpack                           4.39.2
</code></pre>

**Anything else relevant?**
Not that I'm aware of.

**Comment by atscott** [comment]
It appears this behaves as expected. If you still feel there is an issue, please provide further details in a new issue.

What you're seeing is that the `queryParamMap` is firing for the initial state when the component initializes because it's implemented as a `BehaviorSubject` and will emit when you subscribe to it. `location.go` "changes the browser's URL to a normalized version of a given URL, and pushes a new item onto the platform's history." The browser back/forward buttons are causing the page to load anew (and thus destroys and recreates the whole page) while `location.go` does not.

**Comment by Errors4l** [comment]
@atscott Apologies if I'm misunderstanding, but that explanation does not seem to be in line with what's going on in the demo.
I'm talking about the difference between calling `location.go` one or two+ times before using the browser buttons. The browser buttons do fire query changes in normal situations after using `location.go`, just not after using `location.go` _once_.

Here's a small recorded example of the issue:
![](https://i.imgur.com/nT1dAt2.gif)

In this example calling location.go once will not trigger a query change when going back. Calling location.go twice will cause both clicks to trigger a query change (as I expected).

That said, this isn't really _too_ important since normal navigation with the Angular router works fine and covers 99.99% of all use cases. We just happened to run into an edge case situation where we wanted to push a page to the history without routing, while supporting routing/query changes once the user navigates using the browser buttons. Location.go seemed like a good way to accomplish this at the time, minus this hiccup.

**Comment by atscott** [comment]
I see - running it on stackblitz in the side-by-side mode was producing different behavior. What's happening here is that the queryParamMap is not emitting when it thinks the params have not changed from what they were previously. Because `Location.go` is not handled by the router, when you click the back button after one push, the navigation is ignored because you have the same URL as the router saw in the last navigation: https://github.com/angular/angular/blob/24b2f1da2bfaa8afa6e01920d94e00574fd4d5a3/packages/router/src/router.ts#L1075-L1081
So I still think this is working as intended. But it seems like what you're asking for is a feature: "we wanted to push a page to the history without routing, while supporting routing/query changes once the user navigates using the browser buttons". The "without routing" part may need some more explanation. What exactly did you need to avoid that would have happened if you used `router.navigate`? Could you file a new ticket to describe this use-case and we can triage it as a feature request?

**Comment by Errors4l** [comment]
That explanation does make sense, thank you. I just thought that even though it's not part of the router, the routing would pick it up as a change since I was using the injected `Location` class (instead of using `window.location` outside of Angular).

As for what I was actually trying to accomplish, it's been a few months so I don't remember the exact details. Basically, in a previous structure of a project we weren't properly utilizing routing. A lot of state was handled by the component(s) and these components would lose a lot of information when the user refreshed the page (i.e. search parameters for a grid).
The goal was to support refreshing the page in its current state (<kbd>F5</kbd>), without spending all too much work on fixing the actual problems we should've been focusing on.

I later suggested to solve the underlying problem by properly using routing in those components. With normal routing there's no need for this 'fix' I attempted months ago.

Thank you for your time and looking into this. I will not be submitting a new ticket because the solution is simple: stick to using the `Router` :).
