### ISSUE TITLE
New Angular CLI project no working on IE

### ISSUE THREAD

**Issue by movadee** [angular/angular#32593]
When I install angular cli and created a new proect i open it in IE and it didnt work. It works on o9ther browsers.

**Comment by alxhub** [comment]
Hello @movadee,

We're going to need a little more information to diagnose this problem:

1) have you enabled the correct polyfills for IE, per https://angular.io/guide/browser-support?
2) can you provide a repository or a stackblitz with the correct polyfills enabled, which reproduces the issue on IE?
3) which version(s) of IE are you testing on?
4) what does "it didn't work" mean? what error do you get?

**Comment by alan-agius4** [comment]
@movadee, can you please elaborate which command are you using? If you are using `ng serve` it is expected that by default it doesn't work on IE. This is because by default the CLI will build using ES2015 syntax and modules which are not supported by IE.

To enable serving for legacy browsers you need to follow these steps;
https://angular.io/guide/deployment#local-development-in-older-browsers

**Comment by pkozlowski-opensource** [comment]
Going to close this one as we haven't heard back from the issue author.
