### ISSUE TITLE
Step missing in Getting Started documentation

### ISSUE THREAD

**Issue by ChuckBevitt** [angular/angular#32648]
In Getting Started / Your First App / Input, the documentation does not include adding the new product-alerts component to the app.module.ts (import and declare the new component). The example will not work without this.

**Comment by wabudd1** [comment]
This is only an issue if you don't use the component generator in StackBlitz.  Not sure if the Google Gods intended it that way or not.

**Comment by triple0t** [comment]
Hello @ChuckBevitt, 

This particular example was made with Stackblitz in mind. 

Stackblitz does help you add the newly generated component to the App Module (app.module.ts)  when using the Angular Generator as indicated on the guide.

@kapunahelewong Do you want the Guide to be updated?

**Comment by ChuckBevitt** [comment]
I think it would be helpful at that point to mention:
- That the new component must be imported and declared in app.module.ts
- That the online Angular Generator is automatically doing so.
- When working locally, can do the same thing with _ng generate component_

Thanks.

**Comment by kapunahelewong** [comment]
Thanks for the notes, @ChuckBevitt. To answer @triple0t's offer (thank you, @triple0t!!), I'm working on going through the Getting Started and clarifying points (as well as making the example downloadable via the guide rather than having to go to StackBlitz to get), so I'll keep these points in mind as I go through. So yes, we do want them updated but I'm on it as we speak. :) @ChuckBevitt, the Getting Started is intentionally based on using StackBlitz, rather than the CLI. Have you tried the [Tour of Heroes](https://angular.io/tutorial)? That tutorial builds everything using the CLI. I totally get you though, and will work to clear up any ambiguities.
