### ISSUE TITLE
Anuglar 8.2.6 Ivy render issue.

### ISSUE THREAD

**Issue by nanixne** [angular/angular#32744]
code like this, .html template

```
<div *ngFor="let group of groupList">
    <ng-container *ngIf="{open: false} as tmp">
        <div (click)="tmp.open = !tmp.open">
            <span *ngIf="tmp.open">-</span>
            <span *ngIf="!tmp.open">+</span>
            <label> {{ group.group }} </label>
        </div>
        <ng-container *ngIf="tmp.open">
            something here
        </ng-container>
    </ng-container>
</div>
```
without ivy, each group can open/close individually, but when ivy enabled, all groups open/close together.

## 🌍  Your Environment
**Angular Version:** 8.2.6

**Comment by mhevery** [comment]
This issue seems abandoned without any reproducible instruction.  We are closing the issue. If you have reproducible instructions please file a new issue.

**Comment by mhevery** [comment]
We need a stackblitz repro

**Comment by alxhub** [comment]
Confirmed as reported, with the following reproduction:

```typescript
import {Component, NgModule} from '@angular/core';
import {CommonModule} from '@angular/common';

@Component({
  template: `
<div *ngFor="let group of groupList">
    <ng-container *ngIf="{open: false} as tmp">
        <div (click)="tmp.open = !tmp.open">
            <span *ngIf="tmp.open">-</span>
            <span *ngIf="!tmp.open">+</span>
            <label> {{ group.group }} </label>
        </div>
        <ng-container *ngIf="tmp.open">
            something here
        </ng-container>
    </ng-container>
</div>
`,
  selector: 'cmp',
})
export class Cmp {
  groupList = [{group: 'a'}, {group: 'b'}];
}

@NgModule({
  declarations: [Cmp],
  imports: [CommonModule],
})
export class Module {
}
```

The reason this doesn't work as you expect is that the object literal `{open: false}` is treated as a constant, and optimized in a way that causes it to be shared between views. This is likely a bug, and I've filed an internal issue [https://angular-team.atlassian.net/browse/FW-1633](https://angular-team.atlassian.net/browse/FW-1633) for us to look into this.

As a workaround, if you add a property `f = false` to your component class, and write `*ngIf="{open: f} as tmp"` instead, it will likely work as expected since Ivy will no longer optimize the object literal into a constant.

**Comment by pkozlowski-opensource** [comment]
#33705 should fix this issue

**Comment by crisbeto** [comment]
Closing since #33705 was merged in.
