### ISSUE TITLE
[Ivy]  Problem in enableIvy  mode

### ISSUE THREAD

**Issue by abadakhshan** [angular/angular#32765]
I get this error when i **serve** my project with **enableIvy:true**

` ERROR in Unexpected value in spread expression: [object Object]`

## 🌍  Your Environment

**Angular Version:**

```
 "@angular/animations": "~8.2.5",
"@angular/cdk": "^8.0.0",
"@angular/common": "~8.2.5",
 "@angular/compiler": "~8.2.5",
 "@angular/core": "~8.2.5",
 "@angular/flex-layout": "^8.0.0-beta.26",
 "@angular/forms": "~8.2.5",
 "@angular/material": "^8.0.0",
 "@angular/platform-browser": "~8.2.5",
 "@angular/platform-browser-dynamic": "~8.2.5",
 "@angular/router": "~8.2.5",

"@angular-devkit/build-angular": "~0.803.4",
"@angular/cli": "~8.3.4",
"@angular/compiler-cli": "~8.2.5",
```

Samle Repo:

> https://github.com/abadakhshan/testNarikIvy

**Comment by spock123** [comment]
Have you tried with Angular9-next.7?

**Comment by abadakhshan** [comment]
@spock123 

Yes, I did. But the error still exists.


New Angular versions:

```
"@angular/animations": "9.0.0-next.7",
"@angular/cdk": "^8.0.0",
"@angular/common": "9.0.0-next.7",
"@angular/compiler": "9.0.0-next.7",
"@angular/core": "9.0.0-next.7",
 "@angular/flex-layout": "^8.0.0-beta.26",
"@angular/forms": "9.0.0-next.7",
"@angular/material": "^8.0.0",
"@angular/platform-browser": "9.0.0-next.7",
"@angular/platform-browser-dynamic": "9.0.0-next.7",
"@angular/router": "9.0.0-next.7", 


 "@angular-devkit/build-angular": "0.900.0-next.5",
"@angular/cli": "^9.0.0-next.5",
"@angular/compiler-cli": "9.0.0-next.7",
"typescript": "~3.5.3"
```

**Comment by SantiagoIlli** [comment]
Hi, I tried to reproduce the error by using stackblitz, problem is that it cannot find some of the dependencies in npm (such as narik-ui-lib).

You can see it in stackblitz: https://stackblitz.com/github/abadakhshan/testNarikIvy

**Comment by abadakhshan** [comment]
Hi @SantiagoIlli 

**"narik-ui-lib"** is a path that I have defined it on ts.config.
It seems that **stackblitz** has problem with it.

Anyway I removed it and replaced with original dependency path.

**Comment by SantiagoIlli** [comment]
Thanks!

I've clone the project into my computer and it also fails with the same error. Anyway, it looks that a lot a warnings appear as well, such as:

`WARNING in Entry point 'narik-common' contains deep imports into 'projectAbsolutePath/node_modules/rxjs/internal/operators/takeWhile'. This i
s probably not a problem, but may cause the compilation of entry points to be out of order.
`
The strange thing it's that stackblitz run the project without problems.

Let's hope this to be resolved soon with v9, I have a similar problem in one of my projects.

**Comment by JoostK** [comment]
Hi @abadakhshan,

you are experiencing a change in functionality with respect to how Ivy's compiler evaluates code statically. Pre-Ivy, a library would bundle metadata about the values within the program, so library consumers were able to statically evaluate expressions that read values from a library, as those values had been captured in the metadata. With the Ivy compiler, expressions are evaluated directly from source, however that also means that values exported from libraries are no longer available: all that a library exposes is its declaration files.

The reason for this change is due to Ivy's design principles, which is fundamentally that library consumers need not depend on the internals of a library, only on things that it declares publicly (and are therefore present in the `.d.ts` declaration files). This enables better scaling of large compilations, as internal changes to a library would not require a full recompilation of all dependent libraries, as none of the declarations would have changed. If, on the other hand, it were possible to refer to internal values as was possible pre-Ivy, this invariant would break.

The error you are seeing definitely needs to be improved. The logic to statically evaluate expressions from source code has a mechanism to convey *dynamic values*, i.e. expressions that cannot be interpreted statically, together with the reason why and the exact source code that was traversed to arrive at the problematic code. At the moment however, there's still some hard exceptions like this one that cause the full evaluation to crash. We should refactor these exceptions to start using the dynamic value mechanism, as it enables the above benefits. For completeness, please note that we don't currently do much with the dynamic values, so the benefits I mentioned above are not yet visible.

---

For reference, this change is documented [in this doc](https://docs.google.com/document/d/1Dije0AsJ0PxL3NaeNPxpYDeapj30b_QC0xfeIvIIzgg/preview). Here's the relevant bits:
> Foreign functions or foreign constants in decorator metadata aren't statically resolvable (previously, you could import a constant or function from another compilation unit, like a library, and use that constant/function in your NgModule definition).

_Foreign_ in this context means everything from a different compilation unit, which basically means library code.

**Comment by abadakhshan** [comment]
@JoostK 
Thank you for your comment.
I read it but I could not  understand what real problem is.

After many attempts I cloud find that if I remove any dependencies to "narik-ui-material" (one of my dependencies) this error disappears!

There are four positions that this dependency is used.

1- https://github.com/abadakhshan/testNarikIvy/blob/master/src/app/modules/share/share.module.ts#L34

`NarikUiMaterialModule`  has been imported as a module.

2-https://github.com/abadakhshan/testNarikIvy/blob/master/src/app/modules/share/general-list/general-list.component.ts#L11

`NarikUiListForm ` from this dependency  has been used a a base class.

3-https://github.com/abadakhshan/testNarikIvy/blob/master/src/app/modules/share/general-detail/general-detail.component.ts#L10

`NarikUiDetailForm`  from this dependency  has been used a a base class.

4-https://github.com/abadakhshan/testNarikIvy/blob/master/src/app/app.module.ts#L31

`FORM_ITEM_DEFAULT_CLASS` from this dependency  has been used a a InjectionToken.


I should remove all of these elements to remove this error.

Even If I use only No 4 (FORM_ITEM_DEFAULT_CLASS)  this error remains!

How can I understand what the real problem is and how can I solve it?

**Comment by JoostK** [comment]
Hi @abadakhshan,

I forgot to mention the cause of the error in your application. In reality, it's not the application that fails to build, but rather the Narik library itself. The failure is due to this pattern:

https://github.com/NarikMe/narik-angular/blob/467bacc34f7b9b8c1f00a8ff91ea031efb414a16/projects/narik-ui-material/src/lib/narik-mat-auto-complete/narik-mat-auto-complete.component.ts#L35-L39

Notice how the inputs of the `NarikMatAutoComplete` component refer to import from a different library:

```typescript
import {
  NARIK_DATA_DISPLAY_VALUE_INPUTS,
  NARIK_DATA_DISPLAY_VALUE_OUTPUTS,
  NARIK_AUTOCOMPLETE_INPUTS
} from "narik-ui-core";
```

From Ivy onwards, the compiler is no longer able to read the actual values represented by these exports, as they are contained within a different compilation unit. This is a problem, as inputs are required to be known at compilation time.

**Comment by abadakhshan** [comment]
@JoostK 
I very much appreciate your help with this matter. 

But what is the best solution in this situation?
I use these arrays in many libraries. and I will be forced to copy them in each of them.

**Comment by alxhub** [comment]
@abadakhshan,

Yes, specifying the values in the same compilation unit is the best option. This is the only way our compiler will be able to know the values. You might be able to hack around this in your build system using `rootDirs` or similar tricks to share a TS file between many compilations.

An alternative would be to have a base class `@Directive` which declares the inputs, and inherit from that. However, you're using some sort of mixin system which our compiler will also be unable to understand, so I don't think that would work in this case (even though it would work at runtime).
