### ISSUE TITLE
Need a way to deploy a single module alone

### ISSUE THREAD

**Issue by 3gwebtrain** [angular/angular#32879]
Hi there, In my enterprise application, it has totally 13 modules. each of them are very large sizes. now i requested to deploy the first module which we completed, by parallel other modules on development. I could not isolate a module and deploy alone it.

It's being very big blocker. now I am finding a solution for this. may be i require to keep 13 different application?  how about shared modules??

**Comment by mlc-mlapis** [comment]
@3gwebtrain You can't. Remember that because of tree shaking, any additional code feature from Angular packages used in any module can affect the building process -> what has to be included in the main bundle.

For many apps built from the same code base -> using a mono-repo principle is the best way.

**Comment by atscott** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).
