### ISSUE TITLE
Handling each chuncked http response separately

### ISSUE THREAD

**Issue by ciprimatei** [angular/angular#32906]
```
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Performance issue
[X] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
[ ] Other... Please describe:
```
This feature request is for @angular/common/http/HttpRequest

### Description
The HttpResponse with chunked transfer encoding should be served individually rather than a block of previous + current response. The same request was made by another user here: https://github.com/angular/angular/issues/26289 . Unfortunately that issue was closed without a satisfactory solution, although it was supported by several other users. Currently there is a double penalty processing streams of chunked responses from angular, concatenating the responses and then processing the block of responses to extract the last event using interceptors. 

### Describe the solution you'd like
 Maybe the introduction of an option to chose how an user prefers to handle these kind of responses would solve this.

**Comment by alxhub** [comment]
Hi @ciprimatei,

I definitely understand where you're coming from, it's annoying to have to keep track of that stuff. There are two challenges here:

1. The underlying `XMLHttpRequest` API in the browser works this way (which is why `HttpClient` does what it does). Thus, it's _always_ going to be expensive to split apart a stream of chunked responses - there's no way to avoid this.

The `fetch` API does have streaming responses via `ReadableStream`, but it's not supported yet across all of the browsers that Angular supports.

2. Angular doesn't know what the framing of the response chunks is.

The browser makes no guarantees that any "chunk" of bytes sent by the server will be delivered as a single progress event. For some data streams this is okay, but others make use of a protocol that wraps each message in a frame of some sort (e.g. newline separated JSON).

My instinct here is that Angular should eventually provide a primitive for streaming chunks, and leave it up to the user to parse that stream out into frames. It would also be nice if this work could happen outside of the application zone, so change detection only runs on an actual message, not on every chunk of data.

I'll leave this issue open as a feature request for a nicer API around streaming, but it's unlikely that we'll be able to do anything in the core framework until `fetch` and `ReadableStream` are better supported.

**Comment by trotyl** [comment]
@ciprimatei Please also be aware there is **NO** 1:1 mapping between data chunk and partial text, because a single (multi-byte) character can be split in several chunks, so when decoding a chunk to text you may end up with broken text at boundary:

![image](https://user-images.githubusercontent.com/6059170/66889395-cf555900-f014-11e9-919e-c92a5e6cdbeb.png)

https://stackblitz.com/edit/typescript-fu44wc

For safely getting the text, you'll still need to bring your own streaming decoder.

**Comment by petebacondarwin** [comment]
Closing as this has received no votes.
