### ISSUE TITLE
angular2  Chinese input

### ISSUE THREAD

**Issue by hanxinimm** [angular/angular#3296]
![image](https://cloud.githubusercontent.com/assets/13499426/8890531/d9d2cf60-3336-11e5-8842-a40594dcb5b0.png)

like that ， input More characters

**Comment by xsilen** [comment]
It is no problem. keyboard event can be detected, but input value will be changed after ime complete(press space or enter).

**Comment by hanxinimm** [comment]
it no change, you can try it.
![image](https://cloud.githubusercontent.com/assets/13499426/8894768/e9011708-33f4-11e5-8c90-042f2a56b26d.png)

**Comment by mhevery** [comment]
It does not look like an angular issue. My guess is that you don't have right encoding or something like that in your HTML. Angular is only concerned with reading the data and that is not the issue here. 

Disable angular and see if it works. If it is still broken then it is not angular.

Please provide an plunker and reopen if you think this is a framework issue.

**Comment by hanxinimm** [comment]
Here is the plunker : http://plnkr.co/edit/K7ZW4e?p=preview   
![bug1](https://cloud.githubusercontent.com/assets/13499426/8953836/fec7a5b8-3613-11e5-818f-6bc4ea34a67a.png)
![bug2](https://cloud.githubusercontent.com/assets/13499426/8953846/09acade8-3614-11e5-849e-ce79174dd9e9.png)
I Think The Input Value Change After a KeyPress Event.
