### ISSUE TITLE
Input pseudo-event (keyup.enter) don't works anymore on iOS 13

### ISSUE THREAD

**Issue by ivanolarocca** [angular/angular#32963]
### Description
On Apple devices that are currently upgrading to new iOS 13 the pseudo-events have stopped working. (keyup.enter) or (keydown.enter) don't works but only the simple events like (keyup) work.

Do you have info about it or do you have any idea what happened?

Below a demo to test the problem on ios devices. Under normal conditions, pressing the Enter key on the keyboard the 2 event counters increase together. On an iphone or an ipad with the latest version of ios 13 the counter linked to the pseudo-event (keyup.enter) does not work

### 🔬 DEMO
https://stackblitz.com/edit/angular-keyup-enter-ios13

**Comment by ayazhafiz** [comment]
What version of iOS do you have? I cannot repro this on iOS 13.1.2 (17A861).

**Comment by thomasm** [comment]
This happened to me too after the iOS13 update. Switching to (keydown.enter) seems to have fixed the issue for now in my project.

**Comment by trotyl** [comment]
The issue is that ⇧(Shift) being activated automatically, so that the pressed key becomes `shift+enter` rather than `enter`, if you go to `Settings` -> `General` -> `Keyboard` -> `English` and disable `Auto-Capitalization` it will then work fine. (Also, non-English keyboard may not have this issue)

Hard to say it's a BUG in Angular, `shift+enter` is indeed technically different input than `enter`, and it can indeed be captured by `*.shift.enter`. It's more likely an iOS BUG should emit the `shift+enter` input.

<img src="https://user-images.githubusercontent.com/6059170/66126955-3c342080-e61d-11e9-8026-064c87e3d0bf.png" width="200">

<br>

<img src="https://user-images.githubusercontent.com/6059170/66127087-81f0e900-e61d-11e9-9229-34bd345f6073.png" width="200"><img src="https://user-images.githubusercontent.com/6059170/66127116-8fa66e80-e61d-11e9-96ec-5e96e007fed6.png" width="200"><img src="https://user-images.githubusercontent.com/6059170/66127133-96cd7c80-e61d-11e9-839b-e1ccb4b93e65.png" width="200">

**Comment by mhevery** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).

**Comment by herrernst** [comment]
You can also use `<input autocapitalize="none">` if you don't need it.
