### ISSUE TITLE
weird plus syntax in route doc

### ISSUE THREAD

**Issue by hematy61** [angular/angular#33001]
# 📚 Docs or angular.io bug report

### Description

 In the routing documentation there is a weird plus syntax which doesn't make sense at all. 

### What's the affected URL?**
https://angular.io/start/routing

## 📷Screenshot

![image](https://user-images.githubusercontent.com/27248171/66217219-843e5c00-e68c-11e9-9b44-4b8c791dd9aa.png)

## 🔥 Exception or Error
<pre><code>

</code></pre>

**Comment by trotyl** [comment]
`+` operator convert a `string` value to a `number` value.

**Comment by ericmartinezr** [comment]
To complement @trotyl's answer https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Arithmetic_Operators#Unary_plus_()

**Comment by AnthonyLenglet** [comment]
Would it be clearer to perhaps use
```ts
ngOnInit() {
  this.route.paramMap.subscribe(params => {
    this.product = products[Number(params.get('productId'))];
  });
}
```
instead ?

**Comment by hematy61** [comment]
@trotyl @ericmartinezr thanks a billion. looks I need to refresh my JS foundations. I knew that "!" would turn a value to a boolean but never thought about + or - operators. that's pretty neat.

@AnthonyLenglet I think that 's better to keep it there as everyone knows what Number() is doing, but doesn't know about +. However adding some sub-notes to describe what + is doing would be awesome. and probably, prevent opening another issue by someone else for the same topic. right?

**Comment by Airblader** [comment]
Angular is complex enough, I'd try to not also explain JS in the docs as well and instead just use the easier to understand approach using the Number constructor.

**Comment by lazarljubenovic** [comment]
> as everyone knows what Number() is doing, but doesn't know about +

> there is a weird plus syntax which doesn't make sense at all

The problem with these statements is that everyone can say that for any two things. I'd never consider using the simplest unary operator something people don't know about. The documentation is for a JavaScript framework, and basic knowledge is required in order to understand it. Explaining JavaScript along the way would just make the docs more bulky.

**Comment by hematy61** [comment]
@lazarljubenovic well, I'm a big fan of + sign now :100: . and nobody can say that they're master in a language (at least this is what I think). using the + sign is redundant here as JS arrays are gonna coerce their indexes into String. therefor there isn't any difference between arr["2"] and arr[2].

**Comment by Airblader** [comment]
> using the + sign is redundant here […]

In JavaScript, maybe, but in TypeScript with `--noImplicitAny` this is a type error.

**Comment by hematy61** [comment]
well I'm new to TS, and you must be right. however I removed the plus sign on StackBlitz and the component still working. any idea why?

**Comment by sdavids** [comment]
> The documentation is for a JavaScript framework, and basic knowledge is required in order to understand it.

Well, you forget the following:

- sometimes it is JavaScript syntax/idiom/wtf
- sometimes it is TypeScript syntax/idiom
- sometimes it is an [Angular Expression](https://docs.angularjs.org/guide/expression)
- sometimes it is a [microsyntax](https://angular.io/guide/template-syntax#microsyntax)

For beginners it is really hard to distinguish those.

Also, it is really hard to search for `+`, that is one of the reasons why operator overloading is so insidious.

Scala:

```scala
val b = 0 +: a
```

Have fun trying to find out what it does ...

**Comment by lazarljubenovic** [comment]
That's why you need to learn to use something before you use it.

![image](https://user-images.githubusercontent.com/7661457/78663307-2bb57900-78d2-11ea-8e84-742d6b4b15c6.png)

Good luck searching for anything here. And yet for centuries people have been happily using this kind of mathematical notation. Chemistry has no problems with `H He Li Be B C N O F Ne Na Mg Al Si P S` and stoichiometry equations. Physics has no problems with various conventions, greek letters, bars, superscripts and subscripts. And you know what, even latin-based languages have no problem with B/8, l/I/|/1, p/q/d/b, D/O/C, E/F. Japanese have no problem with 待/侍.

And yet whenever syntax comes up in online discussions for web-related technologies, everyone is suddenly confused by symbols. I wonder why. It's not hard at all to search for it. "javascript unary plus", "javascript plus in front of string", etc will all pretty quickly lead you to the answer.

Also I searched "scala plus colon" and got [this](https://stackoverflow.com/questions/41346590/lists-in-scala-plus-colon-vs-double-colon-vs). Obviously it means nothing to be because I have never used Scala in my entire life. If I have, I'd probably have learned about `+:` at some point as well.

**Comment by sdavids** [comment]
> That's why you need to learn to use something before you use it.

Some people read the JavaScript language spec.
Memorize it.
Read the JavaScript standard library.
Memorize it.
Read the TypeScript language spec.
Memorize it.
Read the [template expressions syntax](https://angular.io/guide/template-syntax#template-expressions).
Memorize it.
Read the [ngFor microsyntax](https://angular.io/guide/template-syntax#microsyntax).
Memorize it.

Only then they feel ready for Angular ...

Other people read "JS in 24h" and try to create their first website with Angular—when they stumble upon something unfamiliar they try to find it in the docs or via a search engine.

Other people just copy/paste and don't think about why there is a seemingly random `+`:

![image](https://user-images.githubusercontent.com/201931/78703801-232d6480-790b-11ea-9b2a-cfa597aba084.png)



People are different.

For some English is not their native language.

Some remember random stuff like:

> JS arrays are gonna coerce their indexes into String [but in] TypeScript with `--noImplicitAny` this is a type error."

Some learn one mathematical notation in school ... move to a different country as an exchange student having to learn a new notation for the same concepts ... go back to their original country and go to college having to learn yet another notation for the same concepts ...

I advocate for tutorials to mention everything not obvious or to do it in an obvious way.

And yes, one cannot explain everything and "obvious" is relative 😉

**Comment by lazarljubenovic** [comment]
You don't memorize the spec, you reference it.

“Obvious” is relative, indeed -- relative to the conext of the article and to the target audience. It's “obvious” that 2 + 3 is 5 to most grown ups, and it's “obvious” that sqrt(9) is 3 to most people who browse GitHub. It's also “obvious” to most people using Angular that `foo()` is syntax for a fuction call. _Of couse_ there's a lot of knowledge behind each of these concepts, and it even depends on how deep you wanna go (theres whole books on rigurously proving that 1 + 1 is 2).

I just don't understand where you draw the line. Because the screenshot posted uses...

![image](https://user-images.githubusercontent.com/7661457/78870740-e6ff1e80-7a46-11ea-8b6a-1fa3bfb2620e.png)

- method declaration with no arguments (In the routing documentation there is a weird pair of parenthesis which doesn't make sense at all)
- fat-arrow function (In the routing documentation there is a weird arrow which doesn't make sense at all)
- using single quotes instead of more commonly used double quotes in other languages (In the routing documentation single quotes are used for string which doesn't make sense at all)

So are we just waiting for someone to open all of these, and then change the docs accordingly? Am I going to open Angular docs in 5 years and see every article starting with and explanation on how to use every part of JavaScript syntax, because these types of accepted issues have accumulated?

OP is using RxJS and dependency injection in that screenshot. It's _expected_ to know what unary operator `+` is at that point. Just like you're expected to know how to perform addition of fractions by the time you're learning about differentials. Obviously, it can happen that you somehow skip this "quirk" of JavaScript -- then you go ahead and do a search for "javascript unary plus with string".

There's nothing wrong with not knowing these things; my question is how do we decide how far to go in explaining things in the docs? What's the criteria to make a difference between these:

> this person is confused by something and we suspect that more people might be as well, so let's explain it in more detail

and

> this person is an outlier for getting this far without learning things in order, let's explain this to him in the issue, let's open a StackOverflow question and provide a good answer, but keep the current wording, as we believe it keeps a good balance between "understandable" and "not overexplaining things unrelated to the topic"

**Comment by Airblader** [comment]
On the off-chance of an unpopular opinion, but I agree with @lazarljubenovic. The Angular docs shouldn't make things unnecessarily complex, but it should be expected that the developers know the language. I don't think anyone is doing themselves a favor by trying to learn Angular if they don't know JavaScript.

**Comment by alan-agius4** [comment]
Closing as this has already been addressed.
