### ISSUE TITLE
ngSwitch not using the `*` syntax ?

### ISSUE THREAD

**Issue by cexbrayat** [angular/angular#3306]
As `ngIf` or `ngFor`, `ngSwitch` is manipulating the DOM. 
But, unless I miss something, it can only be called using `[ng-switch]` and not `*ng-switch` like we do for `ngIf` or `ngFor`.

```
<div [ng-switch]="value">
  <div *ng-switch-when="'1'">is 1</div>
  <div *ng-switch-when="'2'">is 2</div>
  <div *ng-switch-default>is another value</div>
</div>
```

Maybe it would make more sense to have something like:

```
<div *ng-switch="value">
  <div *ng-switch-when="'1'">is 1</div>
  <div *ng-switch-when="'2'">is 2</div>
  <div *ng-switch-default>is another value</div>
</div>
```

which would be closer to what we do for `ngIf` or `ngFor`:

```
<div *ng-if="test">..</div>
<li *ng-for="#user of users">{{user}}</li>
```

**Comment by matanlurey** [comment]
The reason `ngSwitch` does not use the `*` syntax is that `*` is specifically a reserved indicator for the sugar of `<template my-directive></template>` and conditionally revealing content or stamping it out multiple times. I think there is a proposal to remove requiring the `*` syntax, so it may be possible to go the other way.

**Comment by pkozlowski-opensource** [comment]
Hmm, actually, if we want to enable people to switch-when on several sibling elements we should be using a `template` tag, no?

**Comment by matanlurey** [comment]
Ah, maybe you're right. I'm not sure exactly how it's implemented in Angular 2. @tbosch

**Comment by mhevery** [comment]
This works as intended. I know it is a bit strange. But if we change it to 

```
<ul *ng-switch="value">
  <li *ng-switch-when="'1'">is 1</li>
  <li *ng-switch-when="'2'">is 2</li>
  <li *ng-switch-default>is another value</li>
</ul>
```

What it would say is that `<ul>` should not be created until `ng-switch` decides it needs to be created. That means that the nested `ng-switch-when` would never be created. If `ng-switch` would somehow skip itself, it would remove `<ul>` which would change the user behavior.  So there is no simple way to create nesting.

Think of `ng-switch` as a container. It always is there, and think of `ng-switch-when` as templates which may or net may be there. The container can not be removed, and hence can not have `*`

**Comment by bernardyen** [comment]
Has anyone actually tried the combination of [ng-switch] and *ng-switch-when in an actual application or test? I've been trying various combinations, and when I put a breakpoint on NgSwitch's setValue() and NgSwitchWhen's setValue(), I always only see the NgSwitch setValue() being called. The NgSwitchWhen one never hits.

As a result, I always see all the ng-switch-when elements not be added regardless of whether they match. I've not been able to find examples outside of this forum that shows this syntax working, so I'm curious if I'm missing something or if it's a bug.

**Comment by vicb** [comment]
@bernardyen You can have a look at the [unit tests](https://github.com/angular/angular/blob/master/modules/angular2/test/core/directives/ng_switch_spec.ts) and there is the pending PR https://github.com/angular/angular/pull/4423 that adds doc with a plunker example. Hope this helps.

**Comment by bernardyen** [comment]
Thanks. I did look at the doc before posting my comment, but I still cannot
get this to work when I use it in AngularDart. I'm not sure if it's a Dart
translation issue or ng2 issue, so posting here first. If it turns out that
it's a Dart issue, I can repost.

But basically, the combination of [ng-switch] and *ng-switch-when does not
recall in a call to NgSwitchWhen's methods even when the value match, and I
cannot get anything to show. The fact that I can't find many AngularDart
references to this syntax anywhere except in the forum is suspicious, but
it could still be that I missed something.

**Comment by diestrin** [comment]
Really old issue, but I have one related with this.
I understand @mhevery point about not having the ngSwitch in the `<ul>`, but this is my scenario.

```
<ul>
  <template ngFor #item [ngForOf]="items">
    <li class="some-list-of-classes" *ngSwitchWhen="1">List type 1</li>
    <li class="some-other-list-of-classes" *ngSwitchWhen="2">List type 2</li>
    <li class="some-random-list-of-classes" *ngSwitchDefault>List type 3</li>
  </template>
</ul>
```

And well, as you know, I can't use the `[ngSwitch]` in the `<template>` created for the *ngFor*. And can't put it in the `<ul>` since I need to switch based on some *#item* value.
So my only option in here, is to create just one `<li>` using *ngClass* to change a large list of classes, and then put the *ngSwitchWhen* in a template. But this doesn't feel like the right way to do it.

I think the better way for this, would be

```
<ul>
  <template ngFor #item [ngForOf]="items">
    <template [ngSwitch]="item.value">
      <li class="some-list-of-classes" *ngSwitchWhen="1">List type 1</li>
      <li class="some-other-list-of-classes" *ngSwitchWhen="2">List type 2</li>
      <li class="some-random-list-of-classes" *ngSwitchDefault>List type 3</li>
    </template>
  </template>
</ul>
```

instead of

```
<ul>
  <template ngFor #item [ngForOf]="items">
    <li [ngSwitch="item.value"] class="{
      'some-list-of-classes': item.value ===  1,
      'some-other-list-of-classes': item.value === 2,
      'some-random-list-of-classes': item.value !== 1 && item.value !== 2
    }">
      <template [ngSwitchWhen]="1">List type 1</template>
      <template [ngSwitchWhen]="2">List type 2</template>
      <template [ngSwitchDefault]>List type 3</template>
    </li>
  </template>
</ul>
```

or

```
<ul>
  <template ngFor #item [ngForOf]="items">
    <li class="some-list-of-classes" *ngIf="item.value === 1">List type 1</li>
    <li class="some-other-list-of-classes" *ngIf="item.value === 2">List type 2</li>
    <li class="some-random-list-of-classes" *ngIf="item.value !== 1 && item.value !== 2">List type 3</li>
  </template>
</ul>
```
