### ISSUE TITLE
More inclusive language in the docs

### ISSUE THREAD

**Issue by thsudo** [angular/angular#33209]
# 📚 Docs or angular.io bug report

### Description

 There are quite a few instances of words like "simple" in the documentation. Unfortunately, words like this can be disheartening to people who are newer or who don't find things described as "simple" to be simple, myself included even though I've worked with Angular for nearly two years. Often this can be remedied by removing those words or adjusting them slightly, like changing "simple example" to "minimal example". Here's a talk by Jim Fisher called [Don't Say Simply](https://www.youtube.com/watch?v=gsT2BBWBVmM) that discusses it further.

### What's the affected URL?**
 This is one example but it happens on multiple docs: https://angular.io/guide/http 

### Reproduction Steps**

Do a search on the page for "simple" and you'll that many times, it's unnecessary within the sentence or can be swapped for a less potentially condescending word.

## 📷Screenshot

![ngdocs_screenshot](https://user-images.githubusercontent.com/13527090/66963154-37656880-f030-11e9-9f78-54f970e88dd8.png)

## 🔥 Exception or Error
<pre><code>

</code></pre>

### Anything else relevant?

I would love to try my hand at reducing occurrences of words like this in the docs to make them more user-friendly and accessible!

**Comment by lazarljubenovic** [comment]
In your screenshot, all instances of the word are in fact used to describe why believing that it's too simple will lead you to wrong conclusion of _simply_ using `Http.get`. It never says that something is simple to do, and nowhere does it imply that you're "bad" at development if you don't understand it immediately -- if this was the case, that would be problematic, but it's just not. It's literally telling you "hey things aren't this simple in real-life apps, be careful not to get carried away". It's warning you against the exact trap that you're trying to describe here.

Furthermore, some things in development are indeed "simple", and it's sometimes worth making sure that the user remembers that it's indeed a simple thing and that there's no need to try to overthink a certain part of the docs or stay on one chapter for too long. For example, when you say "even in simple cases like this one", the implication in the context is that you should create a service instead of calling `.get` directly, _even_ when a function is, as you say, "minimal" (or, as most people would say, "simple").

**Comment by gkalpak** [comment]
I am afraid, I have to disagree, @lazarljubenovic. The use of the word "simple" in the screenshot above are indeed used to say that something (usually the example) is simple (and that it a real app might not be that simple, which again implies that the example _is_ simple).

I think the confusion stems from the fact that "simple" can have several meanings:
1. easily understood or done; presenting no difficulty
2. plain, basic, or uncomplicated in form, nature, or design; without much decoration or ornamentation

I believe the docs use "simple" in the second sense (something consisting of few parts, little code/data-structures), but it is easy for someone the interpret it as @thackley said ("presenting no difficulty"). We can't say that something is objectively, unequivocally easy, especially in development. It depends on a lot of things and saying that an example is easy assumes certain context about the reader's level of knowledge and familiarity with the tools and technologies used.

Again, I don't believe the docs use "simple" in that sense (of "presenting no difficulty"), but in the sense of being uncomplicated/consisting of few parts. But given the fact that "simple" can be misinterpreted like that, I think it is reasonable to replace it with less ambiguous words to make it easier for people (including non-native speakers) to understand the actual meaning :smiley:

Just my two cents :smiley:

Leaving it to the docs team to decide, but (fwiw) it sounds reasonable to me 👍

**Comment by lazarljubenovic** [comment]
> that the example _is_ simple

Because it _is_ simple indeed. There are simple things and advanced things, and things in-between. The example in the docs is simple. I don't see how anyone can get offended by a tutorial stating that something is simple, nor how that's the issue of the documentation (and not that person's issue).

**Comment by gkalpak** [comment]
Not sure were you got the impression anyone is offended by the word "simple". OP used "disheartening" and "condescending" (which have a very different meaning than "offending").

As mentioned in my previous comment, the word "simple" has multiple meanings, so there are things that might be simple in one sense but not in another. In other words, "simple" (in this context) is ambiguous. Which in turn means that it can be interpreted with the wrong meaning (instead of the intended one) and make people feel disheartened.

I am quite surprised you don't see that, because it is...pretty simple (pun intended 😛)

Anyway, I don't see any point in keeping arguing whether something is simple or not, when we've already established that "simple" can have multiple meanings :grin:

We can just agree that we disagree on this one :smiley:

**Comment by thackley** [comment]
Hi! I'm happy to provide a screenshot of other examples, this one (to me) felt like it might best demonstrate the point because it uses simple in a few different ways. For example, the first sentence could be rewritten to say, "In this basic example" or "In this minimal example" because it's referring to the relative size / how fundamental the given example is. The second use of simple seems appropriate but could be changed to say "straightforward," for example. Like the first, the third could provide more context and be swapped for "basic" or "minimal." Often times, simple is also a filler word which seemed to happen a few times in the docs as well.

I think we can all agree programming is hard, even though it's gotten probably gotten easier for many of us through experience. But things that are "simple" to one person may not be "simple" to someone else, especially a beginner or someone new to something. For example, I wouldn't tell someone who doesn't understand OOP that it's simple because to them, it's not, otherwise they would've gotten it. Viewing something as simple comes from experience or comparing it to something more complex, in which case it makes more sense to focus on the more complex idea.

My hope here, and I'll refer to the docs maintainers to have the final say, is to make the documentation more inviting and inclusive to people regardless of where they may be in their programming or Angular journey.

**Comment by kapunahelewong** [comment]
@thackley thanks for pointing this out and for offering more articulate and inclusive alternatives. Would you be interested in submitting a PR? I'd be happy to help you through the process and collaborating. I could take it myself but have a bunch of stuff in the works that I'm working through at the moment so if I took it, it might be a while before I could get into it. What do you think?

**Comment by thackley** [comment]
@kapunahelewong That sounds great, I'd love to submit a PR for this!

**Comment by kapunahelewong** [comment]
@thackley excellent! I'd start small, because the smaller ones are easier/quicker to move through the process. And of course it's totally on your timeline, so whenever you're ready, please tag me. I'm also available on [twitter](https://twitter.com/kapunahele) if you want to DM/run ideas/need pointers about where stuff is, etc. Any question valid. 😊And I have [my notes on my own workflow](https://gist.github.com/kapunahelewong/567c30f7b353fd1c39bbf6d8343e2dca) for working on the docs that you might find helpful. I'm here. 🌸

**Comment by kara** [comment]
For what it's worth, I agree with @gkalpak and think @thackley's idea is a good one. If we can make programmers reading our docs feel more comfortable and our docs less scary, why not do it?

**Comment by lazarljubenovic** [comment]
> For example, I wouldn't tell someone who doesn't understand OOP that it's simple because to them, it's not, otherwise they would've gotten it. 

In a book about OOP, the basis for measuring what's simple and what's not is drawn from the context of the book. You're expected to have some knowledge about programming in general before diving into OOP. A function which prints "hello world" would be described as "simple".

If someone sees "simple" next to something that they don't understand, it's a sign that they need to take a step back and relearn something they skipped. 

I don't know how to drive a car because I ever went to driving classes. For me it's not a simple thing but I'm perfectly aware of my surroundings and I can see most people driving cars, hence it's a simple task that people eventually take for granted. Should I be offended next time someone says that driving a car is simple?

How would "basic" be an improvement over "simple"? It would still mean that it's basic/simple/easy to understand and could make someone go "oh no this is basic but I don't get it".

Also "straightforward" is a very heteronormative word and wouldn't be LGBTQA+ inclusive. Since Angular got rid of "blacklist" and "whitelist" in a similar "issue" a while ago, the same should be done to all words that include "straight".

**Comment by lazarljubenovic** [comment]
It's a public issue tracker where everyone is allowed to express their opinion in a polite way. I simply find it mind-blowing that an issue about a word "simple" somehow being offensive to literally anyone is immediately being acted upon, while these are the dates of the most liked issue, which describe bugs that have been present for 3 years.

![image](https://user-images.githubusercontent.com/7661457/67104802-e2f4f100-f1c7-11e9-8418-66349f3e380e.png)


This issue has been marked as "confusing", which is the same level of severity as, for example, https://github.com/angular/angular/issues/21329, which talks about actual error messages while developing. Two likes. Completely ignored by the development team. 

In the meantime, someone creates an "issue" about a common English word found _everywhere_ (it's [among the **1000 most commonly used words**](https://www.wordfrequency.info/free.asp?s=y) in the language), inserts the word "inclusive" in the title and _bam_ you have a "Committed - Selected for development" because heavens forbid that the documentation about the most complex front-end framework currently available assume that firing a trivial request to the server is "simple".

I don't care about this change. I'm in no way going to stand in the way of implementing this change in the documentation. I'm just wondering where's the line with the current trend of finding everything offensive and paying attention to it immediately while ignoring issues about the framework itself.

Oh and by the way, don't take the following as a serious response, it's just an illustration of why I think these changes are ridiculous:

> simply going to make some people happier,

"Simply? Are you assuming that making a PR is _simple_? It's not simple to everyone."

**Comment by kapunahelewong** [comment]
Hey @lazarljubenovic, I just happened to be working on catching up with triage and community support yesterday. The rate at which issues/PRs are handled varies because there are different teams and people who take them. So, for example, I go through all the `comp: docs` ones, and the rate I move through them would have no influence on `comp: anything else`. The _Committed: Selected for Development Category_ is a way for the docs team (which is me and one other person, both part time) to organize the issues and PRs so we can keep track of them. It really is just the two of us trying out GitHub's project board to help us get through the backlog. In this case, since the OP is willing to create a PR, that's a commitment, so I moved it into that column on our project board. When I go into an issue/PR, even just for triage, I usually try to review/get it to the next step, but that's my own style of working. 

And with this issue, I got a few notifications about it yesterday, so naturally, it got my attention. 

On the labels, such as `severity`, for main docs triage, we use the general labels (that were originally intended for code related PRs/issues). So, sometimes they are a little odd, like using `type: bugfix`. Though this is obviously code related, we use it to describe docs issues that are things to be fixed (typos, clarity, etc), whereas if someone requests that something be documented that isn't, that would `type: feature`.

For `severity` in terms of docs and `frequency`, it's a little hazy, but I try to be logical/systematic. They can mean at the lower numbers that it's not an emergency, or that it's a small fix that people can probably still work successfully through with whatever the current status is. A higher number would be something that maybe makes it so that the documentation is incorrect or maybe that a page isn't rendering properly because of some messed up markdown. None of the labels applied to to docs issues/PRs actually have anything to do with code, but are only in the scope of documentation and we've borrowed the categories liberally.

Other areas or Angular use the labels differently. I have to apply certain labels to get issues/PRs out of "Needs Triage" so they are automatically bumped up into "Backlog". Once they're there, we can sort and organize them.

Hope this helps clear the workflow/process up.

**Comment by bradtaniguchi** [comment]
@lazarljubenovic
I'd say your right on a lot of things here. **That unfortunately isn't the point.** The amount of effort being put into this PR's push back for what I consider to be grammatical changes fascinates me. 
1. It improves the framework if helps 1 person, it should be done. There is no scenario where this "hurts" someone.
2. The framework **can always be improved**. To consider something acceptable is hubris.
3. No breaking changes
4. Super low bar of entry for the fix. 

> I'm just wondering where's the line with the current trend of finding everything offensive and paying attention to it immediately while ignoring issues about the framework itself.

Its very possible the OP cares more, and no one cared about it enough to open a PR. Not because their view is wrong, but because their view is different. 
Yes documentation choices are less important and impactful than direct framework fixes/changes, but that isn't the point. I'm not sure of the technical abilities of this person, nor do I believe its everyone's job to fix everything. **Just because something else is more important doesn't mean something less important can't be fixed.** (you could call this [wataboutism](https://en.wikipedia.org/wiki/Whataboutism) which is a logical fallacy)

>  inserts the word "inclusive" in the title and bam you have a "Committed - Selected for development" because heavens forbid that the documentation about the most complex front-end framework currently available assume that firing a trivial request to the server is **"simple".**

First, its another fallacy to assume including the word "inclusive" directly correlates to the fact this PR was selected for development. We all know why this was selected for development, is because its easy and simple fix to integrate, review, and work on.

> I'm in no way going to stand in the way of implementing this change in the documentation.

I mean I guess? There is resistance is there not? Its one thing to provide your own view on the subject where you see these changes as excessive, ridiculous, unnecessary, then provide reasoning behind all those claims and **then then say your not standing in the way of implementing it**. I don't think that's how things work, and has unintended consequences directly tied with the underlying issue with the docs in the first place and that is **hubris**.

**Finally, please stop making this issue more than it is.** Its an issue for grammatical changes to parts of the docs so they are less harsh to beginners. No one brought up "offended", so claiming as such is yet another [logical fallacy](https://en.wikipedia.org/wiki/Straw_man). Same goes for bringing up the blacklist/whitelist issue, where bringing that sort of issue up here is only relevant due to making it relevant. 
😞

**Comment by rickhanlonii** [comment]
We added this to [React Native](https://github.com/facebook/react-native-website/pull/1337) and it made the docs better in every way because in addition to being more welcoming to new learners, we now use more correct and unambiguous language.

For example, when we said "simple" we almost always meant "basic". "Simple" can be read a characteristic of knowledge, while "basic" is always a characteristic of form. We never meant to imply that React Native knowledge was simple, only the form of some aspects. So for us, changing to reflect what we actually meant was a valuable and welcomed improvement.

I also appreciate that there's a whole thread of people here who understand why this matters, and as a third-party I can say that they have more than adequately explained any concerns 👍✨

**Comment by lazarljubenovic** [comment]
How precisely did you measure that this change made the docs "better"?

**Comment by rickhanlonii** [comment]
I explained how in the same sentence.

**Comment by Splaktar** [comment]
> Completely ignored by the development team

> while ignoring issues about the framework

> I think these changes are ridiculous

@lazarljubenovic your responses have been a bit short on "courtesy and respect". I know that you are trying to walk along the line of the [Code of Conduct](https://github.com/angular/angular/blob/master/CODE_OF_CONDUCT.md) while not crossing it, but you are already very close to crossing the line, if you haven't already.

Please be aware that the development team is not ignoring issues. The various development teams involved are prioritizing issues and working on priorities that are defined by them and their team leads, with input from the community.

If you would like to provide direct input on how you think the priorities should be modified, please email devrel@angular.io. An issue where a community member asks for guidance on how they can contribute to improving the documentation is not the best place to bring up or discuss the overall priorities of the Angular team.

Thank you for [your contributions](https://github.com/angular/angular/pulls?utf8=%E2%9C%93&q=is%3Apr+author%3Alazarljubenovic) to Angular Forms. It's unfortunate that your PRs haven't been triaged and reviewed quickly. It's an area that the team is working on improving. I responded to one of them to hopefully allow you to get the PR ready for review. I also opened an issue and a PR to improve some of the docs around contributing to Angular.

**Comment by rockument69** [comment]
@kapunahelewong -- I don't think a PR has been created yet. However, I think a PR just for "simple" as described in this issue is not needed. We are currently working on refactoring most of the documents for Angular.io, and attention to the use of this word is part of our new style guide. We now adhere to the Google Developer Documentation Style Guide, which lists "simple, simply" as "What might be simple for you might not be simple for others. Try eliminating this word from the sentence because usually the same meaning can be conveyed without it."

**Comment by rockument69** [comment]
In other words, the doc team is already working on this on a topic-by-topic basis.

**Comment by Airblader** [comment]
This isn't a docs question, but will `SimpleChange` and `SimpleChanges` be renamed then as well? It's a breaking API change, but it follows the same issue: it suggests something being simple. And, FWIW, they're misnomers anyway since there are no "ComplexChange"s.

**Comment by aikidave** [comment]
Closing this issue because we are already working on improvind the clarity of the documentation. Issues like this fall under that scope of work. While I appreciate the debate regarding terms such as "simple," the reality is that these terms often add very little value to user comprehension. And fewer words are often better!
