### ISSUE TITLE
Page should start at top when URL is changed in browser bar as in in-app route changes via links

### ISSUE THREAD

**Issue by sjtrimble** [angular/angular#33260]
# 📚 Docs or angular.io bug report

### Description
When I enter a different URL in the URL bar once inside of AIO, the scroll location is kept. 

## 🔬 Minimal Reproduction
Scroll a bit down on a page and then change the URL in the ULR browser bar. See repro steps below.

### What's the affected URL?**
All

### Reproduction Steps**
- Go to https://www.angular.io/tutorial/toh-pt5
- Scroll a bit down
- Change URL to https://www.angular.io/tutorial/toh-pt2
- See that document page starts at the same scroll location as last page, not at the top as expected

### Expected vs Actual Behavior**
A user might expect that when a URL route change happens (as when you click on links) that they start at the top of the page.

**Comment by dannyskoog** [comment]
Sounds like the scroll position is stored in session storage upon each scroll event. And then applied upon future page loads.

Some ideas:
- Don’t store scroll position at all (if possible)
- Clear scroll position in session storage upon page load
- Clear scroll position in session storage upon `onbeforeunload` event

**Comment by SeasonLeee** [comment]
@dannyskoog 

I think why the scroll position is stored in the first place is because

**Better UX**
When I open the doc in mobile phone, and I put the browser into background by switch app or simply switching the tab because I want to check out something else in another tab opening in the same browser, there are cases when the tab/browser contains the angular doc will be closed because the tab/app we switch to consume too much space in cpu, in a low cpu device, system will make choice for the current running so it will temporarily close the browser/tab that contains the angular doc. 

When this case happens, for a better user experience, for example, when I switch back to browser/tab containing the doc, I must want the previous page I visited remain in the same place, right?

So, I think the better solution will be cleared the session storage when the url is refreshed. Because doc is a single page application, the change it make to the url is not refreshing the address bar, I think.

The fact that you locate where the scroll position is stored is amazing! Good job! And thank you!😄

**Comment by dannyskoog** [comment]
I see :) Thanks for explaining a use case where one might want to store the scroll position!

Honestly, everything I wrote was just assumptions since I’m on my phone atm :)

**Comment by sjtrimble** [comment]
The desired outcome is to ***not*** store the scroll position when navigating to a different URL.

**Comment by dannyskoog** [comment]
Yes, I know @sjtrimble :) And that’s what I gave a few suggestions on how to achieve further up.

**Comment by ishan-srivastava** [comment]
@sjtrimble , what about a feature that we specify while adding routes in the project that:

{
    path: 'user/:userId', component: UserInfoComponent, preserveScrolls : true
}

1. Whenever we reach a route and this route had a preserveScrolls true, then
    scroll upto the position that was saved(if any) and on each scroll event update it.
2. Whenever we reach a route and this route had a preserveScrolls false.
    we delete the stored scroll position (if any), and *DO NOT* update it.

**Comment by trotyl** [comment]
> @sjtrimble , what about a feature that we specify while adding routes in the project that:
> 
> {
> path: 'user/:userId', component: UserInfoComponent, preserveScrolls : true
> }
> 
> 1. Whenever we reach a route and this route had a preserveScrolls true, then
>    scroll upto the position that was saved(if any) and on each scroll event update it.
> 2. Whenever we reach a route and this route had a preserveScrolls false.
>    we delete the stored scroll position (if any), and _DO NOT_ update it.

@ishan-srivastava This issue is a documentation issue not relates to the Angular project, the behavior is not caused by Angular router, but [angular.io's own scrolling implementation](https://github.com/angular/angular/blob/c529be9f2427d7bd1b0fded23dca58019634f8cd/aio/src/app/shared/scroll.service.ts#L57-L78).

**Comment by ishan-srivastava** [comment]
@trotyl , yep that makes sense. They have an explicit logic for that. 👍
