### ISSUE TITLE
Error occured after adding webworkers

### ISSUE THREAD

**Issue by logicalravii** [angular/angular#33290]
After adding webworkers, when i try to ng server, it is producing this error. Please help me ASAP

ERROR in ./src/app/app.worker.ts (./node_modules/worker-plugin/dist/loader.js?{"name":"0"}!./src/app/app.worker.ts)
Module build failed (from ./node_modules/worker-plugin/dist/loader.js):
Error: ../node_modules/@agm/core/directives/info-window.d.ts:68:14 - error TS2304: Cannot find name 'Node'.

68     content: Node;
                ~~~~
../node_modules/@agm/core/directives/polygon.d.ts:130:28 - error TS2304: Cannot find name 'MouseEvent'.

130     polyDrag: EventEmitter<MouseEvent>;
                               ~~~~~~~~~~
../node_modules/@agm/core/directives/polygon.d.ts:134:31 - error TS2304: Cannot find name 'MouseEvent'.

134     polyDragEnd: EventEmitter<MouseEvent>;
                                  ~~~~~~~~~~
../node_modules/@agm/core/directives/polygon.d.ts:138:33 - error TS2304: Cannot find name 'MouseEvent'.

138     polyDragStart: EventEmitter<MouseEvent>;

**Comment by kukjevov** [comment]
You have to have separate `tsconfig.json` for your webworkers and you have to exclude all web workers sources in main application `tsconfig.json` and vice versa in `tsconfig.json` for web worker you have to exlude all main application sources.

**Comment by logicalravii** [comment]
Thanks for quick reply, i have generated web workers through angular command  "ng generate web-worker app", so it automatically creating files as it should, i also want to notify you that i have just updated from angular 7.

so as soon as you instructed, i have commented extends  from "tsconfig.worker.json", i thought may be it is importing tsconfig data, and yes now its working fine.
but i don't know as when we create a angular 8 project same thing is happening when we create web workers and its working fine. So no idea its a good approach or not.

this is my worker tscofig file ""tsconfig.worker.json".

// "extends": "./tsconfig.json",
  "compilerOptions": {
    "outDir": "./out-tsc/worker",
    "lib": [
      "es2018",
      "webworker"
    ],
    "types": []
  },
  "include": [
    "src/**/*.worker.ts"
  ]

**Comment by SantiagoIlli** [comment]
Hello!

I'm working with web workers as well.

I've experiment some issues like the one you're describing here.

Without digging into it, it looks like some problem with the imports you have in your worker. I found out that you cannot import in your worker anything that uses something related to the view (as it's another thread, makes kind of sense for me). I don't really know the theory about how this work like this.

In order to resolve the issue, may help to remove all imports that includes things like: window, ElementRef, alerts, etc.

In case the problem remain, can you provide a repo with a minimal reproduction?

**Comment by logicalravii** [comment]
Hello @SantiagoIlli 

I have just added simple web workers for testing and doesn't have any code in it. And the problem disappear as soon as i have commented  "  // "extends": "./tsconfig.json", " from my tsconfig.worker.json. And i don't know is this a right approach or not.

this is my worker tscofig file ""tsconfig.worker.json".

// "extends": "./tsconfig.json",
"compilerOptions": {
"outDir": "./out-tsc/worker",
"lib": [
"es2018",
"webworker"
],
"types": []
},
"include": [
"src/**/*.worker.ts"
]

**Comment by SantiagoIlli** [comment]
Not sure why that worked, and i think it may bring you problems in the future. I'm using a worker with behaviour in one of my projects and my tsconfig.worker.json extends tsconfig.json.

Anyway, the best way to solve an issue like this in my opinion it's to use a minimal reproduction of the error. It's very difficult to talk about the problem without being able to see it. That's why angular have a template for issues that ask you for it.

So if you can provide a repo with a minimal reproduction would help a lot.

**Comment by logicalravii** [comment]
@SantiagoIlli Sorry for late reply, because of busy schedule i wasn't able to produce the minimal build, but as soon as i would have time, i sending that.
Thanks.

**Comment by IgorMinar** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).
