### ISSUE TITLE
target-language was not needed in VE but seems to be required on Ivy i18n

### ISSUE THREAD

**Issue by filipesilva** [angular/angular#33323]
# 🐞 bug report

### Affected Package

 The issue is caused by package @angular/localize

### Is this a regression?

 No

### Description

`target-language` was not needed in VE but seems to be required on Ivy.

@clydin looked into this and it seems like the xliff 1.2 parser lists it as optional in http://docs.oasis-open.org/xliff/v1.2/os/xliff-core.html.

But `@angular/localize` will throw if it's not there: https://github.com/angular/angular/blob/ec482dadb19eea5cd247eb7428a5d88640bd38f8/packages/localize/src/tools/src/translate/translation_files/translation_parsers/xliff1/xliff1_translation_parser.ts#L56

@petebacondarwin can you shed some light on this? Is this intended, and if so, is there documentation telling users they must do it?

## 🔬 Minimal Reproduction
The e2e test in https://github.com/angular/angular-cli/pull/15913

## 🔥 Exception or Error
<pre><code>

</code></pre>

## 🌍  Your Environment

**Angular Version:**
<pre><code>
@angular/localize@9.0.0-next.12

</code></pre>

**Anything else relevant?**

**Comment by IgorMinar** [comment]
We discussed this in the tooling sync and concluded that if the xliff spec doesn't require the language to be specified inline, we should not require it as otherwise we'd be making existing translation files without the property incompatible.

Instead, we should allow for the locale id / language id to be set via a command line flag. And error only if it was not provided inline or on the command line. The CLI already passes the locale info into the localize code, so no special work is needed on the CLI side.

**Comment by petebacondarwin** [comment]
I will deal with this in the next few days but not in time for RC.
