### ISSUE TITLE
[Feature] Allow to switch Service Worker to offline mode forcibly

### ISSUE THREAD

**Issue by danilvalov** [angular/angular#33384]
# 🚀 feature request

### Relevant Package
@angular/service-worker

### Description
Sometimes for PWA apps in the standalone mode (installed) I need to force switch to the offline mode and use the cache only without network requests (for example, if I want to add an online/offline switcher to my app or another). Now we can't control it.

### Describe the solution you'd like
Maybe we can add a condition to functions `saveFetch` with checking some parameter.

### Describe alternatives you've considered
I tried to stop any requests in the app level (using interceptors). But it ignores assets and other non-api resources.

**Comment by akshaydeep06** [comment]
Can you upload an image or video preferably which actually shows that you force switch to the offline mode ? Actually I am new to this so just want to understand the problem better. 

And what I understand is that you want a feature which by default checks whether you are offline / online and accordingly works. So basically you want that any user should not be asked to force switch to the offline mode rather it should automatically happen ? Please clarify in detail so that I can think of a solution to this. Thanks

**Comment by akshaydeep06** [comment]
Also please clarify what is PWA App? I also want to understand the problem

**Comment by gkalpak** [comment]
This feature request sounds a little too specific for `@angular/service-worker`. If you have such specific requirements, you might be better off using a more configurable implementation (such as Workbox).

Given that and the low demand for this feature, I am going to close this for now.
