### ISSUE TITLE
[Docs] Move dependencies to devDependencies

### ISSUE THREAD

**Issue by AndreMaz** [angular/angular#33465]
# 📚 Docs

### Description

I didn't found any docs or references so: what would happen if I manually move Angular's dependencies from `dependencies` to `devDependencies`? Will CLI still work properly?

### Context
I've generated a project with the Angular CLI `ng new my-dream-app` and I've noticed that I get the following dependency structure in `package.json`
```json
{
  "dependencies": {
    "@angular/animations": "~8.2.11",
    "@angular/common": "~8.2.11",
    "@angular/compiler": "~8.2.11",
    "@angular/core": "~8.2.11",
    "@angular/forms": "~8.2.11",
    "@angular/platform-browser": "~8.2.11",
    "@angular/platform-browser-dynamic": "~8.2.11",
    "@angular/router": "~8.2.11",
    "rxjs": "~6.4.0",
    "tslib": "^1.10.0",
    "zone.js": "~0.9.1"
  },
  "devDependencies": {
    "@angular-devkit/build-angular": "~0.803.14",
    "@angular/cli": "~8.3.14",
    "@angular/compiler-cli": "~8.2.11",
    "@angular/language-service": "~8.2.11",
    "@types/node": "~8.9.4",
    "@types/jasmine": "~3.3.8",
    "@types/jasminewd2": "~2.0.3",
    "codelyzer": "^5.0.0",
    "jasmine-core": "~3.4.0",
    "jasmine-spec-reporter": "~4.2.1",
    "karma": "~4.1.0",
    "karma-chrome-launcher": "~2.2.0",
    "karma-coverage-istanbul-reporter": "~2.0.1",
    "karma-jasmine": "~2.0.1",
    "karma-jasmine-html-reporter": "^1.4.0",
    "protractor": "~5.4.0",
    "ts-node": "~7.0.0",
    "tslint": "~5.15.0",
    "typescript": "~3.5.3"
  }
}
```

Now imagine that I'm using the CLI generated project with a backend framework (e.g., expressjs) that handles static assets.
Furthermore, imagine that I want to deploy my app at some cloud service.
 
I can build locally the static assets and then move the entire project to the cloud where I would run `npm i --production` to install only the dependencies and then run `npm start`
However, I don't want to install any Angular-related libs at cloud. I only want to install strictly what's necessary to run my app (`express`, `body-parser`, `cookie-parser` etc.).

### Question 

Will CLI still work properly if I manually move Angular's `dependencies` to `devDependencies`? Things like `ng update`? Would it move back some dependencies from `devDependencies` to `dependencies`? Would it create duplicate entries?

Is it safe to do this?

**Comment by dannyskoog** [comment]
You shouldn’t have to deal with these sort of things at all. Preferably you would build (`ng build`) your application first, either locally or on a build server. And then deploy the contents of the output (i.e. the `dist/FOO` folder) to an application server (cloud, on premise, etc.)

**Comment by AndreMaz** [comment]
Thanks for response.
I agree that it would be a much cleaner option. However, it's not possible, at least a this moment. 

Do you know it moving deps to `devDependencies` would break things?

**Comment by dannyskoog** [comment]
As a thumbrule all packages specified under `dependencies` are required at runtime. So yes, moving them to `devDependencies` should effectively break your application.

In short terms - don’t do it :smiley:

**Comment by AndreMaz** [comment]
I think I wasn't clear enough in my original question. Imagine an `angular+express` project and a `local` and `cloud` environments. Now imagine the following deployment chain:

1. [at `local` env] run `npm i` and install `dependencies` and `devDependencies`. This would contain all Angular's deps and all express deps. Locally I would develop my app to a point that I'm happy with it.
2. [at `local` env] run `npm build` to build a bundle and generate output files at some dir `dist/FOO`
3. [at `local` env] run some `deploy` command that copies my dir to `cloud` env
4. [at `cloud` env] run `npm i --production` to install exclusively what's necessary to run my app, i.e., `express` and all backend related packages. In `cloud` env there is no need to install any angular-related packages because it has been previously bundled at `local` env.
5. [at `cloud` env] run `npm start` to start my app.

Because of this chain I'm considering to move angular's `deps` to `devDeps`. It will work fine in `local` env and it would not install any unnecessary package in `cloud` env.

At the same time, I don't want to lose all the goodies of angular's CLI. However, I don't know if it likes this kind of changes. Hence, the question: will it break the things?

**Comment by dannyskoog** [comment]
Thanks. Now I have a better picture.

In theory the above should work, yes. And that’s because webpack (which is used by CLI under the hood) doesn’t care about whether a node package is declared as a dependency or devDependency. What it cares about is bundling your specified source code and all packages it’s dependent on.

So your step 2 should create chunks with all required packages included. And I assume your `npm build` script runs `ng build —prod` behind the scenes.

In regards to whether `ng update` will shuffle the packages around or not - I don’t know to be honest since I have never experienced your scenario :) But I guess that’s the least of your problems. Plus that’s as simple as you verifying it locally.

**Comment by AndreMaz** [comment]
Thanks for the response :smile: 
I've already done some local tests and `ng update` seems to working fine. It doesn't shuffle things.

Nevertheless, it would be much reassuring if someone could confirm that this approach works with all CLI commands.

**Comment by filipesilva** [comment]
So the whole `dependencies` vs `devDependencies` boils down to `npm install` vs `npm install --production` (that also happens automatically if NODE_ENV environment variable is set to production).

The idea is that you could do `npm install --production` and get less packages, and thus a faster install. This makes a lot more sense for node apps than it does for browser apps, because a browser app is usually built and bundled, not using anything in node_modules.

So for a new CLI project that actually means that everything is a devDependency, insofar as there are no dependencies needed to run it. But to build it you actually need the CLI, the compiler, typescript, etc. And conceivable if your CI also does unit tests and linting, you need everything else too.

So I don't think there's any real distinction for CI as used today with browser apps. For server (node, via universal) apps we also bundle everything so there's no point to prod dependencies either.

In general you should only care about that distinction if you have an environment where you want to do `npm install --production`.
