### ISSUE TITLE
[AOT/IVY/9.0.0-rc.0] Unable to compile application with imports from non-compiled library in monorepo.

### ISSUE THREAD

**Issue by JonWallsten** [angular/angular#33562]
# 🐞 bug report

### Affected Package

 The issue is caused by package @angular/compiler(?)

### Is this a regression?

 No

### Description

We're unable to compile (AOT/IVY) our application with imports from a non-compiled library in monorepo. I'm met with `ERROR in Unable to write a reference to...`

## 🔬 Minimal Reproduction

 Reproduction: https://github.com/JonWallsten/monorepo-repro
```
#install deps
npm run full-install

#start dev server
npm run dev

#go to browser
localhost:8888
```

## 🔥 Exception or Error
<pre><code>
ERROR in Unable to write a reference to MaxCharactersPipe in packages\web-app-angular\node_modules\web-lib-angular\src\pipes\max-characters.pipe.ts from C:/Users/me/repo/monorepo-repro/packages/web-app-angular/node_modules/web-lib-angular/src/pipes/pipes.module.ts
</code></pre>

## 🌍  Your Environment

**Angular Version:**
<pre><code>
Angular CLI: 9.0.0-rc.0
Node: 10.16.3
OS: win32 x64
Angular: 9.0.0-rc.0
... animations, cdk, cli, common, compiler, compiler-cli, core
... forms, material, platform-browser, platform-browser-dynamic
... router

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.900.0-rc.0 (cli-only)
@angular-devkit/build-optimizer   0.900.0-rc.0
@angular-devkit/core              9.0.0-rc.0 (cli-only)
@angular-devkit/schematics        9.0.0-rc.0 (cli-only)
@angular/http                     8.0.0-beta.10
@ngtools/webpack                  9.0.0-rc.0
@schematics/angular               9.0.0-rc.0
@schematics/update                0.900.0-rc.0 (cli-only)
rxjs                              6.5.3
typescript                        3.6.4
</code></pre>

**Anything else relevant?**
We're using latest webpack and AngularCompilerPlugin from @ngtools/webpack to compile our application.

Relates to: https://github.com/angular/angular/issues/33482 and https://github.com/angular/angular/issues/29361

**Comment by saithis** [comment]
I found this post, that helped me: https://dev.to/negue/angular-ivy-overcome-the-first-obstacles-400n

Just add 
`"rootDir": ".",`
to your tsconfig compilerOptions and it works again.

**Comment by gnomeontherun** [comment]
Please also see https://github.com/gnomeontherun/monorepo-library-errors for a pure CLI based demo with clear steps to get from a new project to failure points.

**Comment by JonWallsten** [comment]
@saithis: Unfortunately that did not help. Still the same error.

**Comment by alxhub** [comment]
Hello @JonWallsten,

The configuration here seems really confused and unnecessarily complex to me.

* `web-app-angular` attempts to depend on `web-lib-angular` in 3 different ways:

- via a path mapping in its `tsconfig.json`
- by including the library sources directly into its compilation in `tsconfig.json`
- by installing the raw library sources as into its `node_modules` via a dependency in `package.json`

* there is a path mapping for `@angular/*` into `node_modules/@angular/*`, which is unnecessary as TypeScript should already know how to resolve Angular via node module resolution.

* each package (app and lib) has its own `package.json` and its own `node_modules`. I would expect `node_modules` to be shared across the monorepo.

In general, a lot of configuration goes into making a monorepo work correctly. It's slightly more complicated in Ivy due to the need for each package's compilation to depend on the compiled output of its dependencies, not the sources.

I'm working on a doc for our docs site which describes a proper monorepo setup. Feel free to [look through the prototype doc](https://hackmd.io/zhu28RUcRiaG0DZq5bLy1A?view) and let me know if you can follow it to set up a compilation in your monorepo. I'll be continuing to add new info to the doc over time.

**Comment by JonWallsten** [comment]
@alxhub: Thanks for taking the to looking into this! There are a few reasons why things are what they are if I'm not mistaken. It mostly has to do with how VSCode is doing things and then some with the current state of our application. We have a monorepo with both AngularJs and Angular due to legacy applications. This is the reason why most of the depenedecies are in the monorepo root and some are in the application. But I could try to move the them into the root anyway if that would solve this.

The reason for the "paths" thing is because we got the deep imports in some cases when using autocomplete/intellisense to import modules from angular. It had to do with the symlinking in our monorepo. It also has to do with declaration source maps, to allow us to Ctrl+click to any source file in our code from any package in the monorepo (we ended up in node_modules/@monorepo/package instead of the real path and got conflicts with our own files). All the strange things you see is probably connected to that. We had a lot of issues the symlinked local packages without all these things. Although I haven't touched this since I got everything to work more than a yeah ago. I can try to remove some "unnecessary" stuff and see if it still works. 

The include of the library source in the app I guess is because it won't end up in the compiler if it's not included since I exclude node_modules for performance reasons.

So even if things looks weird everything is there for a specific reason to solve an annoying problem for the our devs.

Would this be solved if I compiled the lib instead of importing the sources directly? I can easily add a simple webpack config to compile it instead if that's needed.

**Comment by alxhub** [comment]
> (note that some of the things here only concerns our real monorepo, not the repro one)

Just a note, if you have some time and could make the repro more faithful to the original repo, that would be super helpful for me as I put together documentation to guide developers on how to set these kinds of things up. In particular I've found `npm link` to be particularly problematic when working in setups like this.

> So even if things looks weird everything is there for a specific reason to solve an annoying problem for the our devs.

Oh, for sure. But often a better foundation can greatly reduce the amount of workarounds required to set things up correctly. 

> Would this be solved if I compiled the lib instead of importing the sources directly? I can easily add a simple webpack config to compile it instead if that's needed.

Generally, you should have one build per "package", and depend on the compilation output of any dependencies when building each package. The goal of the split editor/build tsconfigs is to allow the editor to see a dependency on sources (which makes cross-project "go to declaration" work well) while the compile of a package depends on the compiled version of each dependency. This also allows the editor to navigate through the whole repo without first building all the library packages, which is a drawback of plain TS project references.

With this setup, declaration source maps will be unnecessary.

> After reading through your guide there are a few things that isn't as easy as I would like. A single top-level tsconfig is not possible since our packages requires differrent tsconfig settings. For example our new apps/lib uses "strictNullChecks" but to enable that for our old libs would takes weeks of work. This is causing an issue with the "paths" in the root level tsconfig since they will be inherited by the app/lib's tsconfig, and I guess the path will no longer be correct.

It's fine to have a separate editor configuration per package, which extends from the top level one and sets any package-specific options.`baseUrl` should be set to `"."` in the top-level one and be left unchanged elsewhere.

> The declaration files no longer ends up where they should. I think it related to that rootDir and baseUrl is removed from each package's tsconfig.

I'm not sure what's going on here. Without further rearrangement of files, TS will always emit declaration files immediately next to the source files, which is what we want.

> Imports from other packages nog longer works as it should (this is what I was afraid of). I now have two copies of each exported thing. One is pointing to the source, one is pointing to the dist typings and when I import it I don't get the package name as src but the realtive path in the monorepo. How did you guys solve this? 

There are two ways TS can learn about a file.

1. Having the file directly included in the sources of a combination.

This can happen because it's listed in `files` or `includes` of a tsconfig. Your first example was doing this by listing `"../web-lib-angular/src/**/*.ts"` in the `includes` of the `web-app-angular` tsconfig.

2. Being imported by a file which _is_ already in the project.

To get the experience in the IDE that we want, we need our editor to not include the `dist` files in the project. If they do get vacuumed into the tsconfig, then TS will discover _two_ ways to import from them - directly (mechanism 1 above), and via the path mapped imports (when it encounters them - mechanism 2 above).

The easiest way to do this is to set `outDir: "dist"` in the top-level editor configuration. Because `outDir` is automatically excluded from the project via mechanism 1, TS will only learn about the existence of these files via the imports that we want it to use. Does that make sense?

Again, I would really love to understand your requirements for symlinking packages. All of my experiences with them have been profoundly negative, and I've developed the opinion that they should be avoided in almost all circumstances.

**Comment by JonWallsten** [comment]
Sure! I'll prepare two repos, one with out existing way of doing thing, and then one with the new implementation based on your pointer, docs and Angular's repo. Then you can see how it did work, and how it works now. Although I will make them private and add you as a collaborator so I don't have to spend more than then necessary on renaming and clearing out any traces to our project. But I will remove all real code and just keep a few generic imports to show what kind of dependencies we have. When I done we can look at annoying stuff with the imports and such.

**Comment by JonWallsten** [comment]
@alxhub: I'm almost finished stripping the app and adding example components/directive. It has taken me a full day so far. However, I've just gotten an error I didn't see yesterday. And I'm not sure if it's something that changed between rc.0 and rc.1 or something that happened with my code.

I currently get his error message in the browser. And I'm pretty sure we've been running AOT since forever.
![image](https://user-images.githubusercontent.com/5993909/68397923-3974a000-0174-11ea-8cc6-565f3ee4b4d3.png)

Also get a bunch of these: 
```
 | ERROR in node_modules\@angular\platform-browser\animations\animations.d.ts(37,22): error TS-996002: Appears in the NgModule.imports of MaterialDesignModule, but could not be resolved to an NgModule class
```

From my webpack config:
```
From my webpack: 
...
new AngularCompilerPlugin({
    tsConfigPath: helpers.rootPath('tsconfig.build.json'),
    mainPath: helpers.rootPath('src/main.ts'),
    sourceMap: true,
    compilerOptions: {
        enableIvy: true,
        
    }
})
...
{
    test: /(?:\.ngfactory\.js|\.ngstyle\.js|\.ts)$/,
    use: '@ngtools/webpack',
    include: helpers.includeTS
}
...

```

**Comment by JonWallsten** [comment]
@alxhub: I guess you're busy. But I just wanted to follow up and make sure you got the invites to the repos.
