### ISSUE TITLE
Compatibility Compiler Fails When Dependency has Multiple Modules with Same Named Pipe

### ISSUE THREAD

**Issue by sourdoughdetzel** [angular/angular#33593]
# 🐞 bug report

### Affected Package

 The issue is caused by package @angular/compiler

### Is this a regression?

 Unfortunately, I am not sure. My first attempt at using Ivy has been with `next.15` and `rc.0`. I have experienced the issue in both.

### Description

 When an app pulls in a node module that has multiple modules in it, and those modules define their own pipes that have the same name, `ngcc` fails. Ex. `CoolPackage` has `ModuleA` with pipe called `CoolPipe` and `ModuleB` with pipe also called `CoolPipe`. 

## 🔬 Minimal Reproduction

Please pull down the repo [here](https://github.com/sourdoughdetzel/angular-compat-compiler-bug) and follow the `README` instructions. 

## 🔥 Exception or Error
**From our live app:**
<pre><code>

ERROR in ../node_modules/@local/angular-pattern-library/multi-select-inline-search/multi-select-inline-search.module.d.ts:3:25 - error TS7016: Could not find a declaration file for module '../fesm2015/angular-pattern-library'. 'C:/app-path/node_modules/@local/angular-pattern-library/fesm2015/angular-pattern-library.js' implicitly has an 'any' type.

3 import * as ɵngcc2 from '../fesm2015/angular-pattern-library';
</code></pre>

**From the demo app above:**
<pre><code>
ERROR in Cannot resolve type entity ɵngcc2.ɵb to symbol
</code></pre>

## 🌍  Your Environment

**Angular Version:**
<pre><code>

Angular CLI: 9.0.0-rc.0
Node: 10.16.0
OS: win32 x64
Angular: 9.0.0-rc.0
... animations, cdk, cli, common, compiler, compiler-cli, core
... forms, language-service, platform-browser
... platform-browser-dynamic, router

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.900.0-rc.0
@angular-devkit/build-angular     0.900.0-rc.0
@angular-devkit/build-optimizer   0.900.0-rc.0
@angular-devkit/build-webpack     0.900.0-rc.0
@angular-devkit/core              9.0.0-rc.0
@angular-devkit/schematics        9.0.0-rc.0
@angular/http                     7.2.15
@ngtools/webpack                  9.0.0-rc.0
@schematics/angular               9.0.0-rc.0
@schematics/update                0.900.0-rc.0
rxjs                              6.5.3
typescript                        3.6.4
webpack                           4.41.2
</code></pre>

**Anything else relevant?**

Although it may be the case that the pipes probably shouldn't have the same exact name, the fact that they are contained to the modules would make me think it shouldn't matter.

**Comment by petebacondarwin** [comment]
I have been looking into this. The problem primarily arises from the fact that the package has a flat ESM2015 format (i.e. all the JS source squashed into one file) while the typings is a non-flat format (i.e. a tree of `.d.ts` files).

In the flat ESM2015 format the second `TestPipePipe` is renamed to `TestPipePipe$1` to prevent collisions  with `TestPipePipe`, and then they are exported as "private exports": `TestPipePipe as ɵa` and `TestPipePipe$1 as ɵb`.

In the typings file tree there is no reference at all to `TestPipePipe$1`.

When ngcc does its processing it must update the `.d.ts` files with extra typing information about the types of the declarations of NgModules. For example the `TestOneModule` typings file goes from:

```ts
export declare class TestOneModule {
}
```

to

```ts
import * as ɵngcc0 from '@angular/core';
import * as ɵngcc1 from './test-one.component';
import * as ɵngcc2 from './test-pipe.pipe';
import * as ɵngcc3 from '@angular/common';
export declare class TestOneModule {
    static ɵmod: ɵngcc0.ɵɵNgModuleDefWithMeta<TestOneModule, [typeof ɵngcc1.TestOneComponent, typeof ɵngcc2.TestPipePipe], [typeof ɵngcc3.CommonModule], never>;
    static ɵinj: ɵngcc0.ɵɵInjectorDef<TestOneModule>;
}
```

If the JS format has the same layout (e.g. non-flat) as the typings files then it is possible to match the names of the types in the JS files to the names of the types in the typings files quite accurately.

If the formats are different (e.g. JS is flat and typings are non-flat) then it has to do its best by matching the name of the identifier from the JS (e.g. `TestPipePipe` in the first module and `TestPipePipe$1` in the second module) to a name found in the typings file tree.

In this case there is no mention of `TestPipePipe$1` in the typings tree and so it is not possible to match. 

Ngcc does its best because it knows that in the JS this identifier is exported as `ɵb` and so tries to create an imported type for that - `import * as ɵngcc2 from '../fesm2015/test-package';` - but actually this is completely wrong since the typings never exported this symbol either (note the import from the fesm) and so we should error out at this point of ngcc's processing (or at least log a warning).  The resulting typings file for `TestTwoModule` looks like:

```ts
import * as ɵngcc0 from '@angular/core';
import * as ɵngcc1 from './test-two.component';
import * as ɵngcc2 from '../fesm2015/test-package';
import * as ɵngcc3 from '@angular/common';
export declare class TestTwoModule {
    static ɵmod: ɵngcc0.ɵɵNgModuleDefWithMeta<TestTwoModule, [typeof ɵngcc1.TestTwoComponent, typeof ɵngcc2.ɵb], [typeof ɵngcc3.CommonModule], never>;
    static ɵinj: ɵngcc0.ɵɵInjectorDef<TestTwoModule>;
}
```

**Comment by petebacondarwin** [comment]
I will attempt a fix in ngcc...
