### ISSUE TITLE
9.0 rc ngInjectorDef/ɵinj breaking change

### ISSUE THREAD

**Issue by mhartington** [angular/angular#33673]
# 🐞 bug report

### Affected Package

 The issue is caused by package @angular/....
9.0.0-rc.0

### Is this a regression?

 Yes, the previous version in which this bug was not present was:  8.x

### Description

 A clear and concise description of the problem...
When building a library that ships injectables, if you build against 9.0 with Ivy disabled, the underlying `@Injectable` decorator will not work in an 8.x environment. 

We were seeing this while testing Ionic with v9 rc. When inspecting the compiled code, it seems https://github.com/angular/angular/pull/33151 is the cause.

```js
// V8
Config.ngInjectableDef = ɵɵdefineInjectable({ factory: function Config_Factory() { return new Config(); }, token: Config, providedIn: "root" });

// V9
Config.ɵprov = ɵɵdefineInjectable({ factory: function Config_Factory() { return new Config(); }, token: Config, providedIn: "root" });
```

Specifically `Config.ɵprov` in V9. 

While Ivy is disabled, I would expect apps that built against v8 to still use non-ivy compile libraries even if it's built V9.

## 🔥 Exception or Error

```
NullInjectorError: StaticInjectorError(AppModule)[IonRouterOutlet -> Config]: 
  StaticInjectorError(Platform: core)[IonRouterOutlet -> Config]: 
    NullInjectorError: No provider for Config!
```

## 🌍  Your Environment

**Angular Version:**
<pre><code>
@angular/core@9.0.0-rc.0
</code></pre>

cc @StephenFluin

**Comment by IgorMinar** [comment]
We can't guarantee that a library compiled with vN will be compatible with application compiled with vN-1.

We do our best to guarantee that the reverse is true (lib compiled with vN-1 OR vN is compatible with application compiled with vN).

So, I'm afraid that while we could fix this one individual issue, there likely will be many others that will prevent this setup from working, because it was never meant to work this way (e.g. typescript @ vN could emit d.ts files that are incompatible with typescript version used by the app @ vN-1).

**Comment by IgorMinar** [comment]
I'll go ahead and close this one. I hope my explanation makes sense.
