### ISSUE TITLE
HttpClient generic methods should expect text responseType when generic type is number/string/boolean

### ISSUE THREAD

**Issue by The-MAZZTer** [angular/angular#33972]
# 🚀 feature request

### Relevant Package
This feature request is for @angular/http

### Description
The functionality of HttpClient.get<T>/.post<T> etc is unintuitive when using generic type number/string/boolean.

Generics are typically intended to strongly type a class/function, and if there's an ungeneric version typically it's expected to act the same way except without strong typing. However HttpClient does not act that way which may cause unexpected behavior.

Specifically while JSON (or another syntax) would clearly be needed to parse complex objects out of an API, simple types like string, boolean, and number might be intuitively expected to be parsed as text, not json.

Issue #18672 showcases the confusion possible as does this stackoverflow post: https://stackoverflow.com/questions/49771603/types-of-property-responsetype-are-incompatible

### Describe the solution you'd like
When these types are specified, HttpClient should default to "text" responseType option. Normally the generic version of these functions always expects JSON text. A user can still override the responseType back to "json" for the old behavior to shim old code.

### Describe alternatives you've considered
This solution could potentially cause breaking changes. number and boolean types would likely be unaffected as json and text forms of these types are identical. However string types are the general problem. That said, are there really any APIs that return a quoted string for Angular to parse as JSON? Who knows...

Other alternative is to maintain this behavior. The current documentation at https://angular.io/guide/http#requesting-non-json-data covers this case but perhaps could be expanded on to explicitly warn that use of the generic versions of these functions requires the API to return JSON. Currently it says there "is no need" to use it for string types which implies it might still work when it doesn't.

**Comment by alxhub** [comment]
It's an interesting idea, but unfortunately it can't actually be implemented.

At runtime, `HttpClient` needs to decide how to parse the response. The default behavior is to parse it as JSON unless you specify (via `responseType`) to do otherwise. At runtime, `HttpClient` also has zero information about which generic type you've specified, so it cannot make decisions based on the programmer's expressed intent with types.

The most we could probably do is prohibit you from doing `.get<string>(url)` without specifying `responseType: 'text'`. However, that's actually valid - some JSON APIs return a JSON-serialized string, and `HttpClient` would otherwise decode it that way.

So I'm going to close this as infeasible, unfortunately, but thank you for the suggestion!
