### ISSUE TITLE
ERROR in templateUrl must be a string in Angular 9.0.0-rc.3

### ISSUE THREAD

**Issue by cocolink021195** [angular/angular#34028]
# 🐞 bug report

### Is this a regression?

 Yes, the previous version in which this bug was not present was: 8.2.14

### Description
This error appears at `templateUrl`. Although I fixed it with `template: require(template + '')` but the error still exists.
<pre><code>export class DynamicListService {
  addComponent(name, template: string) {
    @Component({
      selector: "app-tmp-" + name,
      templateUrl: (template + '')
      ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    })
</code></pre>

## 🔥 Exception or Error
<pre><code>ERROR in templateUrl must be a string
</code></pre>


## 🌍  Your Environment

**Angular Version:**
<pre><code>Angular CLI: 9.0.0-rc.3
Node: 13.0.1
OS: win32 x64
Angular: 9.0.0-rc.3
... animations, cli, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router, service-worker

Package                            Version
------------------------------------------------------------
@angular-devkit/architect          0.900.0-rc.3
@angular-devkit/build-angular      0.900.0-rc.3
@angular-devkit/build-optimizer    0.900.0-rc.3
@angular-devkit/build-webpack      0.900.0-rc.3
@angular-devkit/core               9.0.0-rc.3
@angular-devkit/schematics         9.0.0-rc.3
@angular/cdk                       8.2.3
@angular/material                  8.2.3
@angular/material-moment-adapter   8.2.3
@ngtools/webpack                   9.0.0-rc.3
@schematics/angular                9.0.0-rc.3
@schematics/update                 0.900.0-rc.3
rxjs                               6.5.3
typescript                         3.6.4
webpack                            4.41.2
</code></pre>

**Comment by mlc-mlapis** [comment]
@cocolink021195 Where did you see, that syntax like `templateUrl: (template + '')` is available to use?

**Comment by cocolink021195** [comment]
Because, My ListComponent always changes by module so `(template + '')` is `template.html` in `/asset`

**Comment by mlc-mlapis** [comment]
@cocolink021195 My question was not about why did you do it, but where did you read, that it is possible. It looks like you skipped some important parts of docs on https://angular.io, which describe the whole architecture and the fact that all is compiled to JavaScript and finally packed to the optimized bundles. This is done statically -> ahead of time.

You also mentioned that it was possible in version 8.2.14, but it's not true. It was never possible with Angular. The only operation in relation to `templateUrl` property is using the ternary operator, but still with static logic.

**Comment by cocolink021195** [comment]
I know the doc on [https://angular.io](url) doesn't have this way. Because my project has so many different `template` in `ListComponent` and I can't create hundreds of `component` in my project.

**Comment by mlc-mlapis** [comment]
@cocolink021195 You would have to re-think the primary concept of your application then. Mainly there is the question: `What is the main reason, that you have hundreds of different templates. Where do they come from, and how they are differentiated?`

**Comment by cocolink021195** [comment]
The `template` in my `ListComponent` changes according to `FormID`. My company produces ERP software so there are a lot of different lists for each form details. Therefore, it is pointless to try to create hundreds of `ListComponent` just because it is different from 'template'.

**Comment by cocolink021195** [comment]
> @cocolink021195 You would have to re-think the primary concept of your application then. Mainly there is the question: `What is the main reason, that you have hundreds of different templates. Where do they come from, and how they are differentiated?`

The `template` in my `ListComponent` changes according to `FormID`. My company produces ERP software so there are a lot of different lists for each form details. Therefore, it is pointless to try to create hundreds of `ListComponent` just because it is different from `template`.

**Comment by mlc-mlapis** [comment]
@cocolink021195 What is the `ListComponent` exactly? Can you show an example of it? I am not sure what you mean saying: `a lot of different lists for each form details`.

**Comment by DenysVuika** [comment]
How that even works in the production mode?

**Comment by mlc-mlapis** [comment]
@cocolink021195 Angular concept is based mainly on pre-defined components, and not on HTML code from outside. It's possible to render external pure HTML code via `[innerHTML]` binding, of course, but there is the principal limit that you can't use any Angular binding inside it, just pure HTML code.

The standard logic is that the outside world publishes structured data (like JSON), and the Angular application renders it via pre-defined components. Because of using Typescript, all of that data should be strictly typed, so you can use all of the advantages either in code or in templates.

**Comment by cocolink021195** [comment]
@DenysVuika I can't give you detailed information. Basically, I create a `component` in `DynamicListService` and then create 'component' with [https://angular.io/guide/dynamic-component-loader](url).

**Comment by cocolink021195** [comment]
@mlc-mlapis But if you do it my way then you can use anything in the project like `Components`, `Directives`, `Pipes`....

**Comment by cocolink021195** [comment]
> @cocolink021195 Angular concept is based mainly on pre-defined components, and not on HTML code from outside. It's possible to render external pure HTML code via `[innerHTML]` binding, of course, but there is the principal limit that you can't use any Angular binding inside it, just pure HTML code.
> 
> The standard logic is that the outside world publishes structured data (like JSON), and the Angular application renders it via pre-defined components. Because of using Typescript, all of that data should be strictly typed, so you can use all of the advantages either in code or in templates.

@mlc-mlapis But if you do it my way then you can use anything in the project like `Components`, `Directives`, `Pipes`....

**Comment by DenysVuika** [comment]
@cocolink021195 In my opinion, you should have 1 component that dynamically changes its content (an so has single template/templateUrl), rather than hundreds of dynamically generated components. But it's your call anyway.

**Comment by mlc-mlapis** [comment]
@cocolink021195 Nobody wants your real code! Just dummy example of the basic structure. Using the logic described in https://angular.io/guide/dynamic-component-loader is fine. But you are still creating (by dynamic way of course) your pre-defined components. It is the concept, which was used also on https://angular.io before it was moved to the techniques based on web components (Angular components).

It looks, you are mixing several ideas together. Really not sure, what you are trying to do, but the one thing is clear, you can't use the dynamic calculation of `templateUrl`, because Angular is unable to compile the production AOT application.

**Comment by cocolink021195** [comment]
> @cocolink021195 In my opinion, you should have 1 component that dynamically changes its content (an so has single template/templateUrl), rather than hundreds of dynamically generated components. But it's your call anyway.

@DenysVuika  I don't understand your `template/templateUrl`

**Comment by DenysVuika** [comment]
@cocolink021195 please take into account, that during compilation process of Angular components, the templates are inlined. So the `templateUrl` gets transformed into the `template`. When you create the component dynamically, you need to provide the `template`, not `templateUrl`. In your case, you could solve the issue by fetching and providing the `template` value I believe.

**Comment by mlc-mlapis** [comment]
@DenysVuika But then it's necessary to inject JitCompiler in run-time and compile such a template dynamically. It's called mixing AOT & JIT. Generally possible, but not recommended because of the performance and security point of view. There are also new horizons with Ivy in Angular 9, but it's another story.

**Comment by DenysVuika** [comment]
@mlc-mlapis yes, I fully agree. I am personally against the whole idea of having 1000 list components compiled at runtime. Either introducing some notation/configuration to build the list dynamically based on column schema (pretty easy) or in the worst case, having a tool to generate components at a build stage.

**Comment by cocolink021195** [comment]
@DenysVuika @mlc-mlapis Haiz. I understand your comment. But that only applies to regular projects. Again, my project has hundreds of `ListTemplate` and customers can edit the `template` of `List` to their liking. 
Ex: [Image 1](https://www.google.com/imgres?imgurl=https%3A%2F%2Fd2odgkulk9w7if.cloudfront.net%2Fimages%2Fdefault-source%2Fdefault-album%2Fselecting.gif%3Fsfvrsn%3D5e1e0dfe_0&imgrefurl=https%3A%2F%2Fwww.nativescript.org%2Fblog%2Fhow-to-build-a-pwa-an-ios-app-and-an-android-app-from-one-codebase&docid=qz1GZ9dmO6QAmM&tbnid=uz3VTwHdiP3mUM%3A&vet=10ahUKEwjY8MH61YXmAhXNzDgGHUofBdMQMwiBASglMCU..i&w=1061&h=700&bih=625&biw=1366&q=template%20list%20%20native%20app&ved=0ahUKEwjY8MH61YXmAhXNzDgGHUofBdMQMwiBASglMCU&iact=mrc&uact=8#h=700&imgdii=uz3VTwHdiP3mUM:&vet=10ahUKEwjY8MH61YXmAhXNzDgGHUofBdMQMwiBASglMCU..i&w=1061) [Image 2](https://www.google.com/imgres?imgurl=https%3A%2F%2Fd2odgkulk9w7if.cloudfront.net%2Fimages%2Fdefault-source%2Fdefault-album%2Fselecting.gif%3Fsfvrsn%3D5e1e0dfe_0&imgrefurl=https%3A%2F%2Fwww.nativescript.org%2Fblog%2Fhow-to-build-a-pwa-an-ios-app-and-an-android-app-from-one-codebase&docid=qz1GZ9dmO6QAmM&tbnid=uz3VTwHdiP3mUM%3A&vet=10ahUKEwjY8MH61YXmAhXNzDgGHUofBdMQMwiBASglMCU..i&w=1061&h=700&bih=625&biw=1366&q=template%20list%20%20native%20app&ved=0ahUKEwjY8MH61YXmAhXNzDgGHUofBdMQMwiBASglMCU&iact=mrc&uact=8#h=700&imgdii=iKgzm4g_IMwSwM:&vet=10ahUKEwjY8MH61YXmAhXNzDgGHUofBdMQMwiBASglMCU..i&w=1061)
You can't create hundreds of `ListComponent` and then modify it according to customer needs. Because many customers use the software, you cannot fix it for each customer and if you do, each software upgrade is a nightmare.
You also can't use `innerHTML` because `ListComponents` needs to use `Components`, `Directives`, `Pipes`. I thought you would think of using `javascript` but that was terrible.
Currently, my project compiles with production AOT. And `file.html` of ` templateUrl: (template + '')` I have my own security measures.
I think that if you tell your boss that you can't do it according to the customer's request because as your comment above, I think you're a bad developer.

**Comment by mlc-mlapis** [comment]
@cocolink021195 What I can see and understand till the moment doesn't block you to create some general component (+ some type dynamic styling, probably using CSS custom properties), which allows you to satisfy your customer's needs. All without the necessity of processing dynamic HTML code.

You need to re-think the whole thing in a more abstract way and create a general interface that allows you to cover the combination on the customers' side and keep the necessary level of integration on your backend. Such an interface offers your customers UI tools/widgets for creating a full spectrum of different list layouts but still covered by a small number of Angular key components (+ internal directives, pipes, ...). It'll be with some limits, of course, but still very broad for any of your customers.

Again, you are still talking a lot about `ListComponent` but I don't think that's your key problem. The problem is, that you are fixed to the idea of hundreds of standalone templates (probably on the base of your previous background).

Customers' requests are one thing but on the other side, you have to be able to abstract those requests to the usable and functional solution. I am not sure what you want to reach. Without Angular compiler in run-time, you can't compile HTML code together with components, directives and so. And if you inject it, you have a problem with performance, security, testing, and so on.

**Comment by djleonskennedy** [comment]
@cocolink021195 As in here https://github.com/angular/angular/issues/15275, if you need dynamically load a template, then you have a mistake in your architecture, rethink what/how you need to do your task without this stupid idea that called `dynamic template loading`

**Comment by pkozlowski-opensource** [comment]
Sounds like a support request / misunderstanding that was clarified by others.

**Comment by cocolink021195** [comment]
> @cocolink021195 As in here #15275, if you need dynamically load a template, then you have a mistake in your architecture, rethink what/how you need to do your task without this stupid idea that called `dynamic template loading`

Thank you very much, your support is greatly appreciated. Now I know that Angular will not support this feature. I should find another framework.
