### ISSUE TITLE
Footer not working correctly

### ISSUE THREAD

**Issue by ajitsinghkaler** [angular/angular#34038]
# 🐞 bug report

### Description

Go to https://angular.io/api/router/ActivatedRoute then the footer is not working responsively.

## 🔬 Minimal Reproduction
![Desktop screenshot (9)](https://user-images.githubusercontent.com/39260684/69565630-62ea5400-0fdb-11ea-8590-2b41ece51761.png)

The side menu is coming above the footer componenet

**Anything else relevant?**
Related issues:
- #17341
- #18411

**Comment by ajitsinghkaler** [comment]
Please tell me if I can be of any help

**Comment by gkalpak** [comment]
That's strange. It works fine for me:
![aio-footer](https://user-images.githubusercontent.com/8604205/69570561-bb642600-0fc8-11ea-8684-b16bea85fb00.png)

@ajitsinghkaler, does it happen when you Ctrl+Reload (click the reload button while holding the Ctrl key)?
Also, what OS, browser version, screen resolution are you on?

**Comment by ajitsinghkaler** [comment]
@gkalpak I 've tried a hard reload I've tried incognito mode and I tried it on Mozilla too getting the same error everywhere. Following are my details.

OS  Details:
Distributor ID:	Ubuntu
Description:	Ubuntu 18.04.3 LTS
Release:	18.04

Browser(Google Chrome) :Version 78.0.3904.87 (Official Build) (64-bit)

Screen Resolution: 1366*768(16:9)

**Comment by gkalpak** [comment]
You are right. Our footer can get hidden by the sidenav drawer on some resolutions. I think the solution would be to move the footer inside the `mat-sidenav-content`, so that it grows/shrink as necessary to account for the sidenav drawer opening/closing.

Could you create a PR and see if any styles need adjusting?

**Comment by ajitsinghkaler** [comment]
@gkalpak the footer component is not wrapped in mat-sidebar-container So we may have to put it in the sidebar container but doing so makes a lot of space at the right because of our right side nav component. So just wrapping it up will not do we may have to handle it in a different way with js.

![Desktop screenshot (10)](https://user-images.githubusercontent.com/39260684/69659643-a3fa6b00-10a4-11ea-805a-aa6dffb3ee15.png)

**Comment by gkalpak** [comment]
Argh 😠 True. This is not as simple as I thought.
I would rather not use JS for sizing (unless necessary), so we should try to play around a bit and see if we can pull this off using CSS.

**Comment by ajitsinghkaler** [comment]
@gkalpak I tried some things like making small changes in the dom and some styles if I find a solution I'll update you on that.

**Comment by ajitsinghkaler** [comment]
@gkalpak I think we cannot solve it without using js or we may have to think upon a new structure

**Comment by gkalpak** [comment]
Yes, we probably have to restructure things a bit. This is not trivial (neither to implement nor to review) given that we have to ensure that the visual result stays the same (or that any changes are intentional), so I suggest putting it aside for now (since there are higher priority things that need to be sorted out first).

In any case, thx for all the time you put into investigating this.

**Comment by ajitsinghkaler** [comment]
Thanks we can put it in the backlog

**Comment by gkalpak** [comment]
BTW, this is related to #17341 and #18411.

**Comment by gkalpak** [comment]
Fixed by #44236.
