### ISSUE TITLE
Benchpress does not work in Chrome 45 as the events changed

### ISSUE THREAD

**Issue by tbosch** [angular/angular#3411]
Benchpress does not report script time or gc in the upcoming Chrome 45. Changes to their tracing events:

script time:
Is reported with category `devtools.timeline,v8` and name `FunctionCall` (used to be other category).

gc time:
Is reported via category `devtools.timeline,v8` and name `MinorGC` / `MajorGC` (used to be other category and different name). Also, the name `majorGC` is not reported for category `v8` any more.

**Comment by tbosch** [comment]
Maybe change the parsing of categories to detect multiple categories in the `cat` property of an event...

How can we keep track of these changes, without us debugging the tracing events manually? Maybe find the place in Chrome Telemetry where they are reading these events as well...

**Comment by jeffbcross** [comment]
(per IRL conversation with @tbosch)

Since the names don't change that often (I think they've been stable for over 6 months), and since the devtools are likely to change file locations and structures, it's probably a better solution to just add some logic to examine the structure of data returned from Chrome to figure out if it's named the old names or new names. According to Tobias, we're still getting all the data back with the current implementation, we're just not parsing it correctly because of the name mismatch. Right, Tobias?

**Comment by tbosch** [comment]
Yes, we are still getting all the data, it only has different categories now...

**Comment by tbosch** [comment]
Should be done in a way that it still works with older chrome versions.

**Comment by goderbauer** [comment]
Category names in Chrome were changed here: https://codereview.chromium.org/1150033002

Identified changes so far:
* `("disabled-by-default-devtools.timeline", "GCEvent")` has been removed, instead use `("devtools.timeline,v8", "MinorGC")` and `("devtools.timeline,v8", "MajorGC")`
* `("v8", "minorGC")` is now `("devtools.timeline,v8", "MinorGC")`
* `("v8", "majorGC")` is now `("devtools.timeline,v8", "MajorGC")`
* `("disabled-by-default-devtools.timeline", "FunctionCall")` is now `("devtools.timeline,v8", "FunctionCall")`
* `("disabled-by-default-devtools.timeline", "Layout")` is now `("devtools.timeline", "Layout")`
* `("disabled-by-default-devtools.timeline", "UpdateLayerTree")` is now `("devtools.timeline", "UpdateLayerTree")`
* `("disabled-by-default-devtools.timeline", "Paint")` is now `("devtools.timeline", "Paint")`
* `("disabled-by-default-devtools.timeline", "RecalculateStyle")` is now `("blink,devtools.timeline", "UpdateLayoutTree")`

I am working on a PR to incorporate change into Benchpress.

**Comment by tbosch** [comment]
Michael, could you try to ping the Chrome team as to whether they could
actively tell us when they change the protocol? Maybe they have a mailing
list / ... for this already...

**Comment by goderbauer** [comment]
Answer from the chrome team: They do not announce changes to the events because they are not regarding them as a public interface yet. However, we could contribute a Layout test that checks for events we expect (something along the lines of https://code.google.com/p/chromium/codesearch#chromium/src/third_party/WebKit/LayoutTests/inspector/tracing.html) and add ourself to the watch list for that test and its expectations (see https://code.google.com/p/chromium/codesearch#chromium/src/third_party/WebKit/WATCHLISTS).

I am opening a separate issue for this.
