### ISSUE TITLE
Ivy - Map values are not working with ngClass expressions

### ISSUE THREAD

**Issue by vinayk406** [angular/angular#34264]
With Angular Ivy(version: 9.0.0-rc.5) Map values are not working with ngClass expressions. 
This is working without Ivy. 

- Minimal steps to reproduce
```js
@Component({
  selector: 'app-root',
  template: `
    <button [ngClass]="clsMap">Hello World</button>
  `,
  styles: [
    `
      .btn {
        min-width: 100px;
        padding: 10px;
      }

      .btn.btn-primary {
        background-color: teal;
      }
    `
  ]
})
export class AppComponent {
  title = 'ng-cls-map-issue';

  clsMap = new Map([
    ['btn', true],
    ['btn-primary', true]
  ])
}
```
Output with Ivy:
![image](https://user-images.githubusercontent.com/5180606/70308270-dccada80-1830-11ea-86b5-ed0052336aff.png)

Output without Ivy:
![image](https://user-images.githubusercontent.com/5180606/70308121-9d03f300-1830-11ea-8a0f-bfff388805c3.png)

**Comment by mlc-mlapis** [comment]
@vinayk406 I am hearing for the first time that using `Map` is possible somewhere. It's a bit surprising that it works at all (doesn't matter in which variant).

**Comment by matsko** [comment]
Doesn't look like this is supported in the documentation: https://angular.io/api/common/NgClass

The `ngClass` setter also doesn't support it: https://github.com/angular/angular/blob/master/packages/common/src/directives/ng_class.ts#L110

I think what's happening is that because `Map` is the same as `Set`, older versions of Angular would allow it to be processed in the same way.

**Comment by ajitsinghkaler** [comment]
@matsko I think we can close this issue

**Comment by pkozlowski-opensource** [comment]
I believe that this was fixed in RC.11
