### ISSUE TITLE
How to make ngModelGroup optional in Angular forms ?

### ISSUE THREAD

**Issue by gopinathshiva** [angular/angular#34324]
I'm facing issue with adding optional ngModelGroup in angular forms. I do know about the usage of ngModelGroup in angular forms, but struggling to find a way to make it optional.

I tried passing false, null, undefined and still not working

Please find the code sample below and stackblitz link

expected form object

`{
"firstName": "",
"lastName": "",
"zip": "",
"street": "",
"city": ""}`

stackblitz link for reference: https://stackblitz.com/edit/angular-ngmodelgroup

  so how to make ngModelGroup optional here ????

**Comment by ajitsinghkaler** [comment]
https://www.telerik.com/blogs/nested-forms-in-angular-6 I think this can help you

and I don't think this is an issue with the angular repo. Why do you want o give form group null give it a name it won't be a problem.

**Comment by DiedrikDM** [comment]
@gopinathshiva I assume the reason you want this behavior is because you want to dynamically add and remove a form-group surrounding the zip-street-city; but the three fields need to be there in every case. In other words something like this: if you have a name (address) it goes to
`{ "firstName": "", "lastName": "", "address": { "zip":"", "street": "", "city": "" }}`
if you don't have name it goes to
`{ "firstName": "", "lastName": "", "zip": "", "street": "", "city": ""}`

If that's the behavior you want, it won't be an easy solution like what you're showing in your example. The default behavior is that the `NgModelGroup` directive will add a form-group (the new field with the name "_address_") to the parent form-group. And removing it dynamically is (as far as I know) not simple to do. My easiest solution I found is something like this:

```
@Component({
  selector: 'address',
  template: `

    <fieldset *ngIf="addressShown;else withouthAddress" [ngModelGroup]="'address'">
      <div>
        <label>Zip:</label>
        <input type="text" name="zip" ngModel>
      </div>
      <div>
        <label>Street:</label>
        <input type="text" name="street" ngModel>
      </div>
      <div>
        <label>City:</label>
        <input type="text" name="city" ngModel>
      </div>
    </fieldset>
    <ng-template #withouthAddress>
      <fieldset>
      <div>
        <label>Zip:</label>
        <input type="text" name="zip" ngModel>
      </div>
      <div>
        <label>Street:</label>
        <input type="text" name="street" ngModel>
      </div>
      <div>
        <label>City:</label>
        <input type="text" name="city" ngModel>
      </div>
    </fieldset>
    </ng-template>
  `,
  viewProviders: [ { provide: ControlContainer, useExisting: NgForm } ]
})
export class AddressComponent  {
  @Input()
  addressShown: boolean = true;
 }
```

But I am assuming a couple of things right now and I'm not sure if that's what you want. If you want to leave out "address" in every case, you can remove the `ngModelGroup` directive, because it is not a mandatory directive.

**Comment by gopinathshiva** [comment]
@DiedrikDM Appreciate the reply. Yes `*ngIf` works but at the cost of duplicate html code. I was under the impression it could be possible thats why I have raised this issue.

**Comment by AndrewKushnir** [comment]
Hi, I'm closing this ticket as resolved, based on the discussion in this thread. Please reopen if the problem still exists. Thank you.
