### ISSUE TITLE
A little mistake

### ISSUE THREAD

**Issue by RicoAlv16** [angular/angular#34400]
Hello,
i'am very happy to learn Angular on angular.io, it was a great experience for me. Thanks
I just want notice a little mistake on the site: it's written PANE instead of PAGE, in Deployment
 session (share your application) at point 2.

**Comment by kapunahelewong** [comment]
Hi @RicoAlv16! Thanks for looking out for the docs. I'm so glad you're finding them helpful and sharing your thoughts. I think the instance of "pane" that you've noted is intentional because a section of a window can be called a pane. Even so, we want the docs to be clear, and if "pane" even _seems_ like a typo, we should consider changing it. Since it's not really another "page" would you have any other suggestions? "Section" maybe? What do you think?

([Here's where I'm looking](https://angular.io/start/deployment#share-your-application) just to make sure you and I are looking at the same thing.)

**Comment by RicoAlv16** [comment]
I got it, itsn't really a mistake. Sorry for a confusion

**Comment by kapunahelewong** [comment]
Oh, it's ok! Other issues have been filed like this for other word choices in the docs. It's actually important because we want people to be able to easily read through without stumbling. There was another earlier this year where the docs said "stable of heroes" and it was intentional but someone pointed it out thinking it had been intended to be "table", as in tabular data - which makes sense, especially in dev. "Stable" of anything could be considered a colloquialism, and we want to standardize them when we come across them. I'm particularly interested in catching these especially for non-native English speakers, so thank you, @RicoAlv16,  for bringing this up. 🌈

**Comment by ShubhrankR** [comment]
Hi all! 
I have renamed the 'pane' to 'page' for better understanding.

link to the PR - https://github.com/angular/angular/pull/34490

**Comment by kapunahelewong** [comment]
Thank you, @ShubhrankR! I've approved and marked for merge to help your PR land.

**Comment by ShubhrankR** [comment]
@kapunahelewong Thanks :)
