### ISSUE TITLE
Feature request : Allow properties Injection

### ISSUE THREAD

**Issue by mascoun** [angular/angular#34425]
# 🚀 feature request
```
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Performance issue
[x] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
[ ] Other... Please describe:
```

### Description
Give the possibility to inject somthing without using constructor

### Current behavior
All the dependencies must be injected in constructor:

### Expected behavior
Add new annotation ```@Autowire``` for the property which can be present with ```@Optional```, for example:
```
export class MyClass {
  @Autowire
  private mainClass: MainClass;
}
```
### Current solution

1. Defining a class SingletonLocator
```
export class SingletonLocator {
  public static injector: Injector = undefined;
}
```
2. Add in AppModule
```
export class AppModule {
    constructor(injector: Injector) {
        SingletonLocator.injector = injector;
    }
}
```
3. Retrive Singleton in a Component
```
@Component(..)
export class MyComponent {
 
    private myService: MyService;

   constructor() {
     this.myService = SingletonLocator.get(MyService);
  }
}
```

**Comment by ajitsinghkaler** [comment]
What value does it add. If you can give a good use case only then it will be implemented.

**Comment by xumepadismal** [comment]
Well, here is the use case:

1. I have `Logger` service which can be injected in any service/component on demand
2. I want to introduce some `abstract class AbstractFormComponent` with some common logic for all the forms in app
3. I want to inject `Logger` service into `AbstractFormComponent`
4. Meantime I want derived classes to be able to inject services but don't want to force them to inject also `Logger` (because child class likely won't need it)

Just imagine that abstract class has 5 dependencies, not only `Logger`...

Currently you have two options:

1. Inject `Logger` in all derived classes' constructors (at least if you has to inject some other service)
2. Use a hacky workaround as @mascoun described (actually we use something similar in out project currently)

And indeed it would be very useful to implement injection via decorator!

**Comment by kemsky** [comment]
There is one more option, you can create single facade service which wraps all your dependencies and pass only one service to abstract class.

**Comment by xumepadismal** [comment]
@kemsky you can and furthermore you can even just inject `Injector` service instead of creating facade but...

- ...what if abstract class is part of a third-party library?
- ...classes can have complicated hierarchy with different dependencies
- ...and it's not super convenient to introduce facade service and refactor all classes in heirarchy just because you need to inject `Logger` into one concrete class of this hierarchy

**Comment by splincode** [comment]
@mascoun https://www.npmjs.com/package/@angular-ru/autowired

**Comment by mascoun** [comment]
@splincode Thank you it's working 🙏

**Comment by alxhub** [comment]
This is on our roadmap :)

**Comment by yjaaidi** [comment]
🎉 Fixed by https://github.com/angular/angular/pull/45991 thanks to @alxhub

**Comment by JoostK** [comment]
Closing as available in v14 with the `inject` function, which can be used in the constructor/field initialisers of injectables/components/directives/pipes.

**Comment by splincode** [comment]
I wanna use it inside decorators 😩

**Comment by angelaki** [comment]
Just out of curiosity: I have a component base class that I'd like to always be able to access it's `ChangeDetectorRef`. So could using `readonly cdr = inject(ChangeDetectorRef);` in almost every component have a bad performance impact?

**Comment by meriturva** [comment]
Same question here @angelaki , actually `ChangeDetectionRef` was not usable from the current `Injector`, what about `inject()` function? See: https://github.com/angular/angular/issues/14656#issuecomment-293429316

**Comment by angelaki** [comment]
@meriturva yeah, it's working now! I'm just not sure if I could really inject it in **all** of my components. Are there any side-effects I'm not aware of? I've just asked this question in Stackoverflow, maybe someone is interested / has an idea: https://stackoverflow.com/questions/72818023/inject-changedetectorref-in-almost-every-component
