### ISSUE TITLE
Form properties dirty,valid etc not updated if elements injected with <ng-content> 

### ISSUE THREAD

**Issue by anbaran** [angular/angular#34423]
# 🐞 bug report

### Affected Package

The issue is caused by package @angular/forms

### Is this a regression?

No

### Description

When I create my own element with html content like:
```
<form #innerForm="ngForm" autocomplete="none">
    <ng-content></ng-content>
</form>
```
and then use it like:
```
<my-form #myForm>
  <input [(ngModel)]="value" minlength="10">
</my-form>
```
the form properties like dirty, valid are not updated.

I could find on stackoverflow a "workaround" to manually add controls to form like:
https://stackoverflow.com/questions/40843307/q-how-to-use-angular-2-template-form-with-ng-content
```
ngAfterViewInit(): void {
    //to let the inner form see elements added via projection i.e. <ng-content></ng-content>
     this.models.forEach(model => {
       this.form.addControl(model);
     });
  }
```
Eventhough this fix seems to work I am not conviced with it as it cause 
_function cleanUpControl(control, dir)_ from Angular framework to be called twice. 

Besides, I think the default behaviour should be to treat injected elements with <ng-content> as same as if they were passed as usual to the form.

# 🔬 Minimal Reproduction

Here I prepared a minimal app to reproduced that behavior. 
https://stackblitz.com/edit/angular-form-with-ng-content

## 🔥 Exception or Error
<pre><code>

Form properties like dirty, valid are not updated

</code></pre>

## 🌍  Your Environment

**Angular Version:**
<pre><code>

8

</code></pre>

**Anything else relevant?**

**Comment by chris13524** [comment]
I have a similar issue with a custom modal component `<modal>`. Its template looks like this:

```
<form>
  <ng-content></ng-content>
</form>
```

And you would use it like this:

```
<modal>
  <input [(ngModel)]="...">
</modal>
```

----

Here's a summary of my research into this issue:

When a form *input* element is created, it uses dependency injection to obtain a reference to its parent `ControlContainer` [here](https://github.com/angular/angular/blob/5cecd97493025cd940c9ade4ea9f1836d5b05cc8/packages/forms/src/directives/ng_model.ts#L205). When a *form* element is created, it provides itself as an instance of a `ControlContainer` [here](https://github.com/angular/angular/blob/5cecd97493025cd940c9ade4ea9f1836d5b05cc8/packages/forms/src/directives/ng_form.ts#L23). This is how `<input>`s are linked to their parent `<form>` and validation is done.

However, this only works when the `<input>` is a child of `<form>` as far as dependency injection is concerned.

When you define elements inside a component (e.g. (`<modal><input></modal>`), those elements are children of the `<modal>` and not the child of anything inside the view/template of `<modal>` (e.g. a `<form>`) for dependency injection purposes.

I presume this decision was made because in the case of `<ng-content>`, components are initialized before they are projected (see [this](https://stackoverflow.com/questions/54096484/image-inside-ng-content-ngif-false-still-causes-network-request) and [this](https://stackoverflow.com/questions/44929726/angular4-ng-content-gets-built-when-ngif-is-false) for context). So while the `<modal>` component is initialized before content to-be-projected (i.e. `<input>`), anything in the template of `<modal>` (i.e. `<form>`) hasn't been created yet and thus can't provide anything for dependency injection.

However, I'm unsure why this behavior is the same for `<ng-template>` and `*ngTemplateOutlet` in which the template contents (i.e `<input>`) would be created after the parent component's template (i.e. `<form>`).

----

So the workaround here is in our custom component (i.e. `<modal>`), define a custom provider to re-provide our form and use a template to project the contents inside. We need the template to ensure the contents are created after the form.

In the custom component:

```
<form #form="ngForm">
  <ng-container *ngTemplateOutlet="template"></ng-container>
</form>

providers: [{
  provide: ControlContainer,
  useFactory: (component: ModalComponent) => component.form,
  deps: [forwardRef(() => ModalComponent)]
}]

@ViewChild("form")
form: NgForm;

@ContentChild(TemplateRef)
template: TemplateRef;
```

And in the implementation:

```
<modal>
  <ng-template>
    <input [(ngModel)]="...">
  </ng-template>
</modal>
```

This becomes uglier if our `<form>` is inside a template itself.

----

I agree with @anbaran in that this behavior is weird and should be mitigated in a better fashion (for instance if the content of the form is dynamic). Possible solutions:

  - When using template outlets, dependency injection will inherit from the view of the component (i.e. `<modal>` and thus `<form>`).
  - Support a method to initialize `<ng-content>` after the parent component's (i.e. `<modal>`) template is created. I.e. some sort of "lazy projection". This would functionally be the same as the previous solution with `<ng-template>`, but would be more ergonomic.

**Comment by AndrewKushnir** [comment]
Just [tested this use-case](https://stackblitz.com/edit/angular-ivy-34423?file=src/app/app.module.ts) with the latest versions of Angular packages (v10.1.0) and Ivy (previous repro used View Engine), the behavior is still the same.

**Comment by anbaran** [comment]
I found a solution to that issue. Projecting into forms should be done differently, like
```
<!-- my-form.component.html -->
<form>
   <div *ngTemplateOutlet="template*></div>
</form>

<!-- my-form.component.ts -->
export class MyForm {
   @ViewChild(NgForm) form: NgForm;
   @ContentChild(TemplateRef) template: TemplateRef<any>;
}

<!--usage-->
<my-form>    
  <ng-template>
         <!--here place your content-->
   </ng-template>
</my-form>
```

You can find the explanation to the above code in this excellent talk: https://www.youtube.com/watch?v=CD_t3m2WMM8&t=2608s

Or listen to the whole talk: https://youtu.be/CD_t3m2WMM8
