### ISSUE TITLE
feat(router-link): Accept UrlTree as input

### ISSUE THREAD

**Issue by samuelfernandez** [angular/angular#34468]
# 🚀 feat(router-link): Accept UrlTree as input

### Relevant Package
This feature request is for @angular/router

### Description
Currently [`[routerLink]`](https://github.com/angular/angular/blob/master/packages/router/src/directives/router_link.ts#L142) directive accepts either an array of commands or a string. Since angular uses `UrlTree` as a model to store urls, it'd be great to extend this directive so that in addition it accepts a `UrlTree`.

### Describe the solution you'd like
Let `[routerLink]` input accept `commands: any[]|string|UrlTree`.

### Describe alternatives you've considered

* A different directive for this purpose. But having already a directive for that it'd be great to just extend the API.
* A pipe that converts a `UrlTree` into a string. The problem is that the params that a `UrlTree` might include should be extracted and put in their respective inputs. So that doesn't play nicely with all the features `UrlTree` have.

**Comment by samuelfernandez** [comment]
If this gets approved I can try to submit a PR! 😄

**Comment by Airblader** [comment]
UrlTree also holds things like query params etc. Would these be respected? If so, what if the queryParams input on the directive is also set?

It seems like semantically UrlTree is a mismatch for routerLink and some in between type would be needed.

**Comment by samuelfernandez** [comment]
We could merge the query params that come from the UrlTree with the ones of the input if provided. I see the potential benefit of simplifying the bindings of the routerLink by using a UrlTree that encapsulates everything in a single model. I feel that adding a between type might go against this simplification and could be over-scoped.

**Comment by mikelgo** [comment]
👍

**Comment by esoubiran-aneo** [comment]
Is there any way to pass this "/route?query=string" to routerLink without a serialization?

[routerLink]="['/route?query=string']" will return "/route%3Fquery%3Dstring"

Not very convenient

**Comment by lincolnthree** [comment]
Still need this in 2023

**Comment by samuelfernandez** [comment]
> If this gets approved I can try to submit a PR! 😄 

Still available 😅

**Comment by Stas-tolpekin** [comment]
Still need this in 2024

**Comment by Erbenos** [comment]
Problem I have is that I have no idea how one would correctly "deconstruct" the UrlTree path into "commands" routerLink input? Query params and fragment is fine-ish, but the path itself is more tricky especially due to the possible non-trivial commands such as aux routes. You would have to come up with some heuristics or only support subset of possible commands as there doesn't seem to be any sort of API provided by Angular by which one could do this conversion.

**Comment by lincolnthree** [comment]
> Problem I have is that I have no idea how one would correctly "deconstruct" the UrlTree path into "commands" routerLink input? Query params and fragment is fine-ish, but the path itself is more tricky especially due to the possible non-trivial commands such as aux routes. You would have to come up with some heuristics or only support subset of possible commands as there doesn't seem to be any sort of API provided by Angular by which one could do this conversion.

What about `UrlTree` makes it tricky to deconstruct into the `commands` that `routerLink` expects? If a `UrlTree` can be built deterministically from commands, surely the inverse must be true, no? Otherwise how would Angular's internal router be able to know what a `UrlTree` referred to, and know what to display?

**Comment by samuelfernandez** [comment]
@lincolnthree @Erbenos router link directive internally already parses commands into a url tree and the triggers navigation. Supporting that should be fairly simple, just a matter of triggering the navigation directly (I am oversimplifying a bit, also need to build the href attribute)

**Comment by samuelfernandez** [comment]
Would a contrib be welcomed? 😅 Cc @JeanMeche

**Comment by Erbenos** [comment]
I know I was just wondering out loud about how one would get the commands back from URL tree. If you solved that you would be able to do something hack-ish like this:

```ts
@Directive({
  selector: '[urlTreeLink]',
  standalone: true,
  hostDirectives: [
    {
      directive: RouterLink,
      inputs: ['queryParamsHandling: queryParamsHandling', 'state: state', 'relativeTo: relativeTo']
    }
  ]
})
export class UrlTreeLinkDirective {
  private readonly urlTreeUtils = inject(UrlTreeUtilsService);
  private readonly routerLinkDirective = inject(RouterLink);

  @Input() public set urlTreeLink(urlTree: UrlTree | null) {
    // how would one get "commands" well?
    const url = urlTree ? this.urlTreeUtils.deconstruct(urlTree) : null;
    this.routerLinkDirective.queryParams = url?.queryParams;
    this.routerLinkDirective.fragment = url?.fragment ?? undefined;
    this.routerLinkDirective.routerLink = url?.commands;
    // Magic
    // https://github.com/angular/angular/blob/3c3a947778fc2941b035e9e6efb6fb883a4dd79c/packages/router/src/directives/router_link.ts#L239
    // eslint-disable-next-line @typescript-eslint/ban-ts-comment
    // @ts-ignore
    this.routerLinkDirective.ngOnChanges();
  }
}
```

But of course, this is quite bad, and it would be much better if the [routerLink] supported it directly so that we don't need to do either this ugly workaround or create our own link directive without attempting to extend [routerLink].

**Comment by samuelfernandez** [comment]
Thanks @atscott!

**Comment by lincolnthree** [comment]
Yesssss!! Thank you @atscott :D 🔥  🍾
