### ISSUE TITLE
Support `onbubble-event` as alternative to `(^event)`

### ISSUE THREAD

**Issue by manfredsteyer** [angular/angular#3448]
Hi,

I've talked to Victor and we think that we need an alternative syntax for binding to bubble-events.

Currently there is on-event="x()" as an alternative to (event)="x()" but no alternative for (^event)="x()". 

Wishes,
Manfred

p. s.: perhaps on-bubble-event="x()" would be a good alternative ...

**Comment by pkozlowski-opensource** [comment]
@manfredsteyer this is probably (?) not what you are looking for, but `on-^event="x()"` works today. Don't see much problem (apart from introducing yet-another-way-of-doing-things) with adding `on-bubble-event="x()"`

**Comment by gdi2290** [comment]
The idea for the alternative syntax is legacy html and user familiarity. For example, we're able to create components/directives that work both in angular 1 and angular 2 following the same interface. This is due to the fact that angular 1 didn't enforce any conventions (since no one knew what the best practices were for component/directives 6 years ago). So we can actually take advantage of this 
(I gave a subtle nod to a migration technique during [ng-vegas](https://youtu.be/x296y5mErWI?t=9m36s))

ng1 https://github.com/gdi2290/ng-vegas-angular2-d3/blob/master/angular1/app.js#L10
ng2 https://github.com/gdi2290/ng-vegas-angular2-d3/blob/master/app.ts#L60

essentially we can create a directive that works in both ng1 and ng2 with this example

```html
<bar-graph
  bind-data="graphData"
  width="500"
  height="130">
</bar-graph>
``` 

Notice how we're using the alternative syntax but we can do this for angular 1 today using the alias
`scope: { data: '=bindData' }`. We create a directive for each event already in angular 1 (legacy) so it does make sense to continue down that path. Doing this allows you to delete half your code when switching to angular 2 now that we know what the best practices are

**Comment by mhevery** [comment]
This should be `onbubbel-event`same as `(^event)`
