### ISSUE TITLE
CurrencyPipe not show all symbols for It language

### ISSUE THREAD

**Issue by giusliso** [angular/angular#34509]
# 🐞 bug report

### Affected Package

 The issue is caused by package @angular/....

### Is this a regression?

 In 5.0.0 it works correctly

### Description

For many currencies like USD the correct sibolus is not shown when using the CurrencyPipe pipe

## 🔬 Minimal Reproduction

 https://stackblitz.com/...
See reproduction there:
[https://stackblitz.com/edit/angular-currency-pipe-gipfyg](https://stackblitz.com/edit/angular-currency-pipe-gipfyg)

## 🔥 Exception or Error
<pre><code>

</code></pre>

## 🌍  Your Environment

**Angular Version: 8.0.0.
<pre><code>

</code></pre>

**Anything else relevant?**

**Comment by GuillaumeVerdon** [comment]
Hi !

It seems you now need to pass `symbol-narrow` to the pipe like this:

`myValue | currency : 'USD' : 'symbol-narrow'`

Though, I don't know if it's wanted or a regression. Doc needs to be updated anyway.

Regards

**Comment by petebacondarwin** [comment]
This is working as expected. The breaking change to use `symbol` as the default was in v5.0.0 - see https://github.com/angular/angular/commit/079d884b6cbe179c3565d8db443d76b1ae041af7

I see in Stackblitz that we still see `$` even in 5.0.0 - but this might be due to the data provided by CLDR for that version.

As @GuillaumeVerdon suggests you should use `symbol-narrow` if you want to force the pipe to render only the symbol.
