### ISSUE TITLE
feat(platform-browser) provide `Link` service

### ISSUE THREAD

**Issue by d-koppenhagen** [angular/angular#34605]
# 🚀 feature request

### Relevant Package

This feature request is for @angular/platform-browser

### Description
Similar to the provided [class `Meta` within it's interface `MetaDefinition`](https://angular.io/api/platform-browser/Meta
) there should be a service to add and modify HTML `<link>` elements in the `<head>`.
This is essential to add for example dynamically canonical URLs without touching the DOM directly in the App.

### Describe the solution you'd like
I would like to have two things:

- [x] `Link` class with the public methods:
  - [x] `addLink`
  - [x] `addLinks`
  - [x] `getLinks`
  - [x] `getLinks`
  - [x] `updateLink`
  - [x] `removeLink`
  - [x] `removeLinkElement`
- [x] `LinkDefinition` type / interface

### Describe alternatives you've considered
 Have you considered any alternative solutions or workarounds?
not yet.

**Comment by pkozlowski-opensource** [comment]
We've considered this feature request and decided against implementing it: https://github.com/angular/angular/pull/34606#issuecomment-729270727 

But this service might be actually useful in the scope of the optimized image directive we are working on. To be confirmed.

**Comment by ChristopherPHolder** [comment]
I would assume you mean to add preload links to the head of the document @pkozlowski-opensource ?

But why would that be implemented inside of the optimized image directive? Is it not clearly link tag management? Which clearly has its use in download optimization? 

Additionaly if you have on angular app which has multple enviroments and different websites it can be used to manage more things to, removing them from the index file itself, at least for ssr apps.

**Comment by AndrewKushnir** [comment]
@ChristopherPHolder as @pkozlowski-opensource mentioned, there was a case in the optimized image directive (which is still in progress) to check whether there are preconnect links for certain type of images, but it was solved in a context of that directive for now. There was no need to update/delete tags, only to retrieve a list of link tags, so that implementation can not be used as a generic solution.

We had a conversation about this feature with the team once again and came to the same conclusion as described in https://github.com/angular/angular/pull/34606#issuecomment-729270727 - we do not plan to add extra APIs to manage link tags at this moment.
