### ISSUE TITLE
Unable to read custom header in HttpClient 

### ISSUE THREAD

**Issue by Rashid75** [angular/angular#34671]
Hi

I am trying to read custom header in my angular 8 project, sent from (Node js) api. Can anyone help me, how can i read it, i guess we can read in http module, not sure in httpClient.

I have tried getting using underneath way but could not get. 

response.header.get('x-access-token')
response.header.getAll('x-access-token')

**Comment by dhiasaadlaui** [comment]
Have you exposed the X-Token from server side using access-control-expose-headers? because not all headers are allowed to be accessed from the client side, you need to expose them from the server side

Also in your frontend, you can use new [HTTP ](https://angular.io/guide/http#reading-the-full-response) module to get a full response using {observe: 'response'} like

```
http
  .get<any>('url', {observe: 'response'})
  .subscribe(resp => {
    console.log(resp.headers.get('X-Token'));
  });
```

**Comment by AndrewKushnir** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).
