### ISSUE TITLE
@angular/router or Cordova white screen

### ISSUE THREAD

**Issue by CrackerakiUA** [angular/angular#34684]
# 🐞 bug report

### Affected Package
"@angular/cdk": "^8.2.3"
"@angular/core": "~8.2.0"

### Description
Initial problem is that after simple build of latest angular project with `<base href="./">` we have white screen on cordova project and probably electron also.

### Workouts
1) switch `target` in `tsconfig.json` to `'es5'` which didn't fix the issue
2) remove all `type="module"` and `nomodule` from index.html after build which fix the white screen problem but after that, angular router is not working, pages is not switching after initial page load.

P.S. as possible solution would be to use something different from `@angular/router` if there is such out there.

**Comment by JCornat** [comment]
Hello, 

In my opinion, it is not really a bug from Angular, but a more like a specificity of Cordova, because the Cordova browser is loading the app via a local path pointing to the index.html and not an url.

I had the same issue, and I solved it by adding a script tag in the top of header in `index.html` :

```
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <title>Title</title>
  <script>document.write('<base href="' + document.location + '" />');</script>
  ....
</head>
<body>
....
```

This way, when index is loaded, it takes the current location of the index.html, and the base is now relative to this point, and the app works like on classic browser.

If you want to try this workaround :
Be careful to add this previous script, only if you are compiling for Cordova, it will not work if you are using a classic browser.

My way to do that is :
- copying `index.html` to `index.cordova.html`.
- in `angular.json`, duplicate the project, chose a name and replace the old project name by the new one, and just set the `index` property to `index.cordova.html`.

Hope it helps :)

**Comment by atscott** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).
