### ISSUE TITLE
Routing Tutorial

### ISSUE THREAD

**Issue by eyesuphere** [angular/angular#34738]
Seems to be an issue with this tutorial. Maybe I am doing something wrong but the products.ts does not have a product id variable in its array and basically the end result is this tutorial does not completely work.

**Comment by eyesuphere** [comment]
<div *ngFor="let product of products; index as productId">

  <h3>
    <a [title]="product.name + ' details'" [routerLink]="['/products', productId]">
      {{ product.name }}
    </a>
  </h3>

</div>

Also, this seems to only work when change productId to product.id and also when you put id in the products.ts array starting at 0.

**Comment by troelslenda** [comment]
Correct. The `productId` is not part of `products.ts` However the `productId` is declared in `product-list.component.html:4` as the index of the `ngFor` iteration.
In `product-details.component.ts:34` you can see how the selected id is used to extract the product-item.

**Comment by Naxirdan** [comment]
@eyesuphere your vision is correct, this **productId** will be item position in array, but like @troelslenda says in the next step we have the same Array called **products** where we can rescue the position from url and we can extract the same product because if we don't change anything in **products** will be okay:

Piece of code where we can extract only the product:
```
ngOnInit() {
  this.route.paramMap.subscribe(params => {
    this.product = products[+params.get('productId')];
  });
}
```

**Comment by kapunahelewong** [comment]
@eyesuphere, do @troelslenda and @Naxirdan's explanations help clear up the issue for you?

**Comment by troelslenda** [comment]
Basically everything works as intended. I believe what lead to the confusion was the missing identifier on each product. I kinda agree with @eyesuphere. The array of products could be extended with an id for easier readability and avoid using the index in the template iteration. It would make more sence for this tutorial to simplify this part.
I'd be happy to take on the task.

**Comment by Naxirdan** [comment]
You can use custom productID as @eyesuphere said to simplify this part but maybe another one don't have productID value, have an UUID, ISBN, HASH... or something like that, will be confusing for that people... but the ID is more common.

If you to use productID and don't make a new request using existing Array maybe you can use:
`var product = products.filter( res => { return res.productID === productIdRoute});`

**Comment by gkalpak** [comment]
To sum up:
- The current implementation is correct and works as expected.
- It might be more intuitive, if `productId` came from an `id` property on the `product` object instead of being the index of a `product` in the `products` list.

I took a quick look through the tutorial nothing else would be affected (so it should be a straight-forward change). If anyone wants to take it on, go ahead.
