### ISSUE TITLE
Angular Double Submit Cookie patterns for CSRF suffers from sub-domain cookies overwrite?

### ISSUE THREAD

**Issue by lijunhaoabroad** [angular/angular#34752]
🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑

Please read https://angular.io/guide/security#report-issues on how to disclose security related issues.
As the https://angular.io/guide/security page said:
In a common anti-XSRF technique, the application server sends a randomly generated authentication token in a cookie. The client code reads the cookie and adds a custom request header with the token in all subsequent requests. The server compares the received cookie value to the request header value and rejects the request if the values are missing or don't match.

I assume angular only asks the server to compare the value of XSRF-Token cookie to the value of X-XSRF-TOKEN request header. This is the double submit cookie strategy , right ?

What happened if the attacked owns the sub-domain, and overwrites the XSRF-TOKEN cookie and forge the request? Why Angular didn't use Synchronizer Token Pattern to prevent CSRF attacks?

🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑

**Comment by gkalpak** [comment]
As explained here, the **Synchronizer token pattern** is a little more complex for the server (e.g. you will need to keep the token in the user's session info on the server in order to verify each request). It is more suitable for HTML-based applications that use forms to submit requests.

SPAs (which is what you usually build with Angular) do not typically rely on forms for submitting requests and there is no clear, generic way of setting up the **Synchronizer token pattern**. Of course, it is possible to implement it in our app (in a way specific to your app).

In contrast, the **Cookie-to-header token** technique that Angular uses by default (which is slightly different than the **Double Submit Cookie** technique) can be implemented in a way that is generic (i.e. fits most (all?) apps built with Angular) and can be easily utilized by JS (which does the heavy-lifting in SPAs). It is also simpler to implement the server part.

Finally, you can configure the cookies sent by the server to not be accessible on subdomains (if you don't control them). For more details, see [this StackOverflow answer][2].

##
Closing the issue, since everything seems to work as expected, but feel free to continue the discussion below.

<sub>BTW, if you think you have identified an actual security vulnerability in Angular, please report it following the instructions [here][3].</sub>

[1]: https://en.wikipedia.org/wiki/Cross-site_request_forgery#Prevention
[2]: https://stackoverflow.com/questions/18492576/share-cookie-between-subdomain-and-domain#answer-23086139
[3]: https://angular.io/guide/security#report-issues
