### ISSUE TITLE
Missing item variable / item is not defined

### ISSUE THREAD

**Issue by marquezm2410** [angular/angular#34762]
# 📚 Docs or angular.io bug report

### Description

 A clear and concise description of the problem...

### What's the affected URL?**
https://angular.io/guide/structural-directives

### Reproduction Steps**

**Go To:**
Writing your own structural directives
These microsyntax mechanisms are also available to you when you write your own structural directives. For example, microsyntax in Angular allows you to write <div *ngFor="let item of items">{{item}}</div> instead of <ng-template ngFor [ngForOf]="items"><div>{{**item**}}</div></ng-template>. The following sections provide detailed information on constraints, grammar, and translation of microsyntax.

**item is not defined**

missing item variable

## 🔥 Exception or Error
<pre><code>

</code></pre>

**Comment by vpetrusevici** [comment]
You just didn't add variable item in template

**Comment by marquezm2410** [comment]
I know, I'm just alerting you that the documentation has that error!

**Comment by kapunahelewong** [comment]
Hey thanks, @marquezm2410. Could you write out how it should be or explain it to me specifically? (The fix isn't obvious to me.) 

Also maybe it helps to know that that particular example isn't meant to run on its own, it is purely a reference to syntax. So `item` won't be defined unless you define it. For example, this `*ngFor` part in the example app's template for that doc:

```
<ul>
  <li *ngFor="let hero of heroes">{{hero.name}}</li>
</ul>
```
requires that it be defined in the template:

```
import { Hero, heroes } from './hero';
...
export class AppComponent {
  heroes = heroes;  // <--here
  hero = this.heroes[0];
```

Notice that `Hero` and `heroes` are imported from `hero.ts`:

```
export class Hero {
  id: number;
  name: string;
  emotion?: string;
}

export const heroes: Hero[] = [
  { id: 1, name: 'Dr Nice',  emotion: 'happy'},
  { id: 2, name: 'Narco',     emotion: 'sad' },
  { id: 3, name: 'Windstorm', emotion: 'confused' },
  { id: 4, name: 'Magneta'}
];
```
So that's why those work and the small inline snippet wouldn't &mdash; there is no place where `items` is defined. You'd have to have each of those pieces in your app. The word `item` is used in the same way that one might use `foo` to explain a concept.

I [created a StackBlitz](https://stackblitz.com/edit/angular-5ajr8n) to help clarify. Does this help? If I've missed your meaning, would you be interested in submitting a PR or creating a StackBlitz?

**Comment by ericmartinezr** [comment]
He means this snippet (see [here](https://angular.io/guide/structural-directives#writing-your-own-structural-directives))

```
<ng-template ngFor [ngForOf]="items"><div>{{item}}</div></ng-template>
```

is missing a `let-item`.

```
<ng-template ngFor let-item [ngForOf]="items"><div>{{item}}</div></ng-template>
```

**Comment by kapunahelewong** [comment]
Oh, thank you for clarifying, @ericmartinezr 🌺
