### ISSUE TITLE
The command ng serve is not responding to changes to ng module

### ISSUE THREAD

**Issue by wagnermaciel** [angular/angular#34813]
# 🐞 Bug report

### Command

- [ ] new
- [ ] build
- [x] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] xi18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc

### Description

`ng serve` either is not responding to changes made to the `declarations` property of an `NgModule`.

## 🔬 Minimal Reproduction
1. `ng new pokemon --routing=false --style=css`
2. `ng generate component pokedex`
3. set up `pokedex` to be used by the root component
4. `ng serve`
5. remove `pokedex` from the `declarations` field of the `NgModule` in `app.module.ts`

### Expected
The app crashes
### Actual
The app continues working

### Additional Information
Restarting `ng serve` fixes the issue.
This also works vice-versa, so if the application is crashing due to `pokedex` _not_ being in the `declarations` of `app.module.ts`, adding it without restarting `ng serve` will still be crashing.

## 🌍 Your Environment
![image](https://user-images.githubusercontent.com/25158423/70344220-fe669a80-180d-11ea-87ef-afb74aacd87a.png)

## Demo
I've created a demo project [here](https://github.com/wagnermaciel/Pokedex).
To reproduce this issue
1. `git clone https://github.com/wagnermaciel/Pokedex.git`
2. `npm install`
3. `ng serve`
4. Go to http://localhost:4200/pikachu
4. remove `PokedexComponent` from the `declarations` of the `NgModule` in `src/app.app.module.ts`

**Comment by dgp1130** [comment]
@wagnermaciel, wasn't there a way to run `ng serve`, make a change, and the automated rebuild would succeed, but then a subsequent `ng serve` would fail? That sounds like a CLI issue. What were the steps to reproduce that problem?

**Comment by wagnermaciel** [comment]
Yes, the issue here is not that the build fails or succeeds. The issue is that an iterative rebuild can look like everything is working just fine but killing and restarting the server will show that the app is actually crashing, or vice-versa.

**Comment by alxhub** [comment]
Confirmed as reported in rc.9.

There are actually two bugs here!

1) it's not a compiler error that `PokedexComponent` uses a pipe that's not defined (if it's not in the `AppModule`, it doesn't have `AsyncPipe` in its scope). This should be caught by template type-checking. I'll need to investigate this.

2) the rebuild does indeed not catch that `PokedexComponent` needs to be rebuilt.

**Comment by alxhub** [comment]
I've reproduced this in the compiler's incremental build tests now.

The general flow of the bug is:

1. We detect that the component's previous record isn't reusable, as the component's file previously depended on the module's file, which has changed. So far, so good.

2. We successfully analyze/resolve the component in its new context, with no associated module. Also as expected.

3. We close out the analysis phase by reporting success to the incremental build subsystem, which transitions from a "pending" to an "analyzed" state. This involves using the newly completed dependency graph (for the current program) to determine which files need to actually be emitted.

Here's where things go off the rails. If the component had been moved from one module to another, it would have a dependency on its new module's file, which would have changed (to add the component). This would trigger an emit of the component.

But because the component now has _no_ associated module, it now has no outgoing dependency edges to anything that's changed. Therefore, the incremental build engine decides that the component isn't stale after all, and does not require a re-emit.

---

What's missing from this picture is the understanding that not depending on a module is, in fact, a change. Somehow, we need to carry forward the information that the component file still depends on the module file in the new program, because the removal of the component from the module is still a change which affects the component.

I'll have to think about how to express this cleanly.
