### ISSUE TITLE
`ChangeDetectorRef` resolved to `ViewRef`

### ISSUE THREAD

**Issue by gempain** [angular/angular#34825]
# 🐞 bug report

### Affected Package
- @angular/angular@9.0.0-rc.9
- @angular/angular@9.0.0-rc.1

### Is this a regression?

Yes

### Description

`ChangeDetectorRef` is resolved to `ViewRef`

## 🔬 Minimal Reproduction

[Stackblitz](https://stackblitz.com/edit/angular-pyczvr?file=src%2Fapp%2Fapp.component.ts)
[Demo Github Repo](https://github.com/gempain/angular-core-9-rc.9)

Or manually: 
```
npm i -g @angular/cli@9.0.0-rc.9
ng new tmp
cd tmp
npm start
```
add the following to `app.component.ts`:
```
  constructor(private cdref: ChangeDetectorRef) {
    console.log(cdref);
  }
```
go to `http://localhost:4200`.

## 🔥 Exception or Error
The console logs `ViewRef` instead of `ChangeDetectorRef`.

![Screenshot 2020-01-17 at 09 10 49](https://user-images.githubusercontent.com/13135149/72595757-d4bf8980-390a-11ea-85f5-0efee5eaa843.png)

## 🌍  Your Environment

**Angular Version:**
```
9.0.0-rc.9
```

### Notes
@angular/angular@9.0.0-rc.1 seems to be affected as well.

**Comment by alexzuza** [comment]
Actually, in ViewEngine you get `ViewRef_` as well. Because ChangeDetectorRef is an abstract class and originally was also known as ViewRef.

ViewEngine
https://github.com/angular/angular/blob/c60d7563a812e1f02707603564a1e0eef801d5b0/packages/core/src/view/refs.ts#L230-L232

Ivy
https://github.com/angular/angular/blob/f2df1c79d2b44c103c36a4132d93e4491cc825aa/packages/core/src/render3/view_engine_compatibility.ts#L384-L386

**Comment by gempain** [comment]
Good to know, thanks for the answer !
