### ISSUE TITLE
Issue with Scroll in angular.io

### ISSUE THREAD

**Issue by abhinav-goyall** [angular/angular#34918]
# 📚 Docs or angular.io bug report
When i am going through docs , i came across that when i scroll down to the last , summary never gets highlighted as other items do in the right panel and that;s because scroll is coming before the content of the page is over. When clicked on summary it got highlighted and then even a little scroll makes it gone again and previous items got highlighted again even i am reading summary.

### What's the affected URL?**
https://angular.io/tutorial/toh-pt2

### Reproduction Steps**
You just need to scroll down to the summary.

### Expected vs Actual Behavior**
Summary should always be visible like the other items and should get highlighted if a user is going through it.It should not hinder by the scroll.

## 📷Screenshot
![angular_io_bug](https://user-images.githubusercontent.com/47552229/72959674-22d40180-3dd1-11ea-8c92-17a04509fc30.PNG)

**Comment by naingaungphyo** [comment]
Weird, it is working perfectly in my monitor/pc only with normal scroll though.
![image](https://user-images.githubusercontent.com/5661543/72960701-0f855e00-3df2-11ea-998c-a9352ec4f5aa.png)

**Comment by abhinav-goyall** [comment]
No , i can scroll more but then the some of the left items get behind under the footer component.
![angular_io_1](https://user-images.githubusercontent.com/47552229/72962594-c7a70c80-3dda-11ea-84a3-c07a0bafc951.PNG)

**Comment by naingaungphyo** [comment]
Ah, I see. 
I think that is because you have less width than mine.
You can scroll to summary by hovering inside inner frame. 
Do you see inner scroll frame on the right side of your red arrow? How about hovering on it and then scroll to bottom.

**Comment by naingaungphyo** [comment]
I reproduce your issue by resizing my browser. 

In 1st photo, toc-container height is 253 and everything is OK.
![image](https://user-images.githubusercontent.com/5661543/72968129-3188db80-3e06-11ea-85a5-88d1bd0c68ea.png)

Then, in 2nd photo, toc-container height is changed to 153 but it is not maintaining to show summary as it was in 1st photo after auto resize.
![image](https://user-images.githubusercontent.com/5661543/72968351-a2c88e80-3e06-11ea-80f6-a92b94b52b3c.png)

I don't think it is a bug though. But it will be nice maintaining to show summary in toc-container even after auto resize.

**Comment by abhinav-goyall** [comment]
But it will be nice maintaining to show summary in toc-container even after auto resize.---> Exactly my point.

**Comment by naingaungphyo** [comment]
There will be no problem with browsers(windows) whose max-height  is >= 720px.

**Comment by abhinav-goyall** [comment]
Yeah you are right, but it would be good if its responsive across various resolutions.

**Comment by abhinav-goyall** [comment]
Thanks naingaungphyo for acknowledging the feedback. I raised a similar thing for angular/components as well. It might be same or may be something different.

**Comment by abhinav-goyall** [comment]
https://github.com/angular/components/issues/18236   .. Sorry, i forgot to mention the link

**Comment by gkalpak** [comment]
If I understand correctly, there are two issues discussed here:

1. The issue mentioned in the issue description (https://github.com/angular/angular/issues/34918#issue-553949638) is that a section is not highlighted until it reaches a certain distance from the top of the viewport.
    This works as intended. There is not 100% accurate way to know what section you are looking at, so we need to employ a heuristic to determine that. The current algorithm checks whether the header of a section is within 50px from the top bottom of the top bar ([relevant code][1]). OP mentioned the last section, but this is the same for any section.
    In addition to that, the last section is special, because if it is short enough it means that its header can never be scrolled high enough to reach 50px from the bottom of the header. Therefore, there is an extra rule that says that if the page is scrolled all the way to the bottom, then the last section is considered active, even if it is not within 50px ([relevant code][2]).
    Note that in OP's first screenshot, they last section header is not high enough in the viewport _and_ the page is not scrolled all the way to the bottom. Eveything works as intended here afaict.

2. The second issues discussed here is that when scrolling towards the bottom of the page, the ToC on the right gets "squashed" to accomodate the footer that scrolls into the view and this can lead to the active/highlighted section to get out of view.
    There is code that ensures that a ToC item is scrolled into view as soon s it becomes highlighted ([relevant code][3]), but if the ToC keeps shrinking, then it can indeed get out of view.

##
So, afaict, this second issue is something that we could improve upon. I.e. we would need to figure out a (performant) way for ToC component to scroll the active/highlighted item itno view (if necessary) every time [its height is updated][4].

That said, this sounds like a very low priority issue, because:
- It occurs when the window height is small (but at the same time the width is big enough to have a ToC on the right).
- It only affects the last section.
- Even when it happens, it is just slightly inconvenient.
- Fixing it (in a way that does not negatively affect performance), might not be very straight-forward.

If anyone whats to take a stub at it, though, I won't stand in your way :wink:

[1]: https://github.com/angular/angular/blob/32b72f39f/aio/src/app/shared/scroll-spy.service.ts#L173
[2]: https://github.com/angular/angular/blob/32b72f39f/aio/src/app/shared/scroll-spy.service.ts#L87-L116
[3]: https://github.com/angular/angular/blob/32b72f39f/aio/src/app/custom-elements/toc/toc.component.ts#L72-L76
[4]: https://github.com/angular/angular/blob/32b72f39f/aio/src/app/app.component.ts#L359
