### ISSUE TITLE
InsertRemoveComponent not shown into the stock demo on StackBlitz

### ISSUE THREAD

**Issue by pasha-bolokhov** [angular/angular#34940]
# 📚 Docs or angular.io bug report

### Description

The `InsertRemoveComponent`, while included and imported into the demo package itself, is not shown in the actual demo — have to add it manually

There is one *weirdness* about it, from my understanding this may be a bug — if you double-click on the "Toggle Insert/Remove" button quickly, you'll see multiple instances of the text being shown/removed

### What's the affected URL?**
https://angular.io/generated/live-examples/animations/stackblitz.html
referred from
https://angular.io/guide/transition-and-triggers#use-of-ngif-and-ngfor-with-enter-and-leave

## 🔥 Exception or Error
<pre><code>

</code></pre>

**Comment by sonukapoor** [comment]
@pasha-bolokhov I see the component as part of the module. I assume you mean that the selector is not added to any template?

**Comment by pasha-bolokhov** [comment]
That's one problem, maybe they did not want to include all components into the demo. That could be alright, as I can do it myself
However, there is some weirdness in its behaviour, please read what I described above

**Comment by kapunahelewong** [comment]
@pasha-bolokhov, do you mean the "Toggle Animations" button? I don't see one that's "Toggle Insert/Remove".

**Comment by pasha-bolokhov** [comment]
Yes because that component is not included into the demo. You need include it, then you will see the toggle button
And then when you click fast enough you'll see the "glitch". I'm not sure whether the cause is Stackblitz or Angular itself, I did not clone that whole demo locally

**Comment by kapunahelewong** [comment]
Ah, I understand now. I added it and can see what you mean. I'm fixing now and will have a PR soon. Thank you!!

**Comment by kapunahelewong** [comment]
Ok, so the reason it was doing that glitchy thing where multiple `div`s would show up is because toggling it on sets `isShown` to `true` (the default is `false`) but the animation time is currently set to 5 seconds. By clicking repeatedly on the button we can toggle `isShown` more rapidly than the `div` is removed from the DOM. Each click that sets `isShown` to `true` is actually inserting the `div` anew into the DOM. When we click to remove the `div` the animation takes the full five seconds to remove it and when we click to insert it it doesn't check to see if there's one already in there. It just adds a new div. Thus the cascading effect. You can see this if you watch the Elements tab in the dev tools and click repeatedly.

When I reduce the time to 100 ms it seems to clear up the problem (just because of speed). We could add styling to the host and child views, but I think that would complicate the example. As it is, the strange behavior seems to me to be a logical extension of how the element is being animated, added, and removed from the DOM.

I don't see a reason for that animation to be five seconds, but if anyone else does or knows of a better way for me to fix this please let me know.

**Comment by kapunahelewong** [comment]
@pasha-bolokhov would you like to review my PR? I've added a link in the comments to the PRs version of the example. It should now have the missing component and clicking rapidly should just cause the div to come and go. https://github.com/angular/angular/pull/35046

**Comment by pasha-bolokhov** [comment]
I thought that it could have just been doing ok, and the behaviour is normal, as long as one understands what's going on — that the animation is long. And, if there was a reason for making the animation long, and this extra DOM "feature" may have some "educational" value, then we could keep it at 5 seconds. I'm fine either way.. Thanks for clearing this out!

**Comment by pasha-bolokhov** [comment]
Since I'm at here, wanted to ask the following question. The doc style that Angular uses is also kind of used by RxJS and possibly other libraries or frameworks. Is it possible to reuse (with some customization) your doc style, is there any copyright? I understand cloning the repo would work, but it's quite large, and changing it all at once might be difficult. Plus, you're actually typesetting in Markdown. Is there a quick starter for all of that? Sorry if this is not the right place to ask this

**Comment by kapunahelewong** [comment]
Regarding copyright, I believe it is completely free for you to use however you like. Here is the [link to the license ](https://github.com/angular/angular/blob/master/LICENSE)which mentions the documentation specifically. To run the app locally I have [my own notes](https://gist.github.com/kapunahelewong/567c30f7b353fd1c39bbf6d8343e2dca#angulario-local-setup) I share with others that you might like. 

As for how to actually modify the app, maybe @gkalpak or @petebacondarwin could tell. They know it inside and out.
