### ISSUE TITLE
undecorated-classes-with-di: libraries generated with CLI versions older than v6.2.0 break

### ISSUE THREAD

**Issue by thefliik** [angular/angular#34985]
# 🐞 Bug report

### Command (mark with an `x`)

- [x] update

### Is this a regression?

unknown

### Description

When using `ng update @angular/core --force --migrate-only --from=8`, I received the following error:

```bash
TypeScript project "lib/tsconfig.lib.json" has configuration errors. This could cause an incomplete migration. Please fix the following failures and rerun the migration:

error TS100: Angular compiler option "flatModuleIndex" requires one and only one .ts file in the "files" field.
```

I tracked the error down to the inclusion of 

```json
"angularCompilerOptions": {
    "flatModuleId": "AUTOGENERATED",
    "flatModuleOutFile": "AUTOGENERATED"
  }
```

In one of my library's `tsconfig.lib.json` files. I tried deleting both

```json
    "flatModuleId": "AUTOGENERATED",
    "flatModuleOutFile": "AUTOGENERATED"
```

And the migration completes successfully. 

I believe both `"flatModuleId"` and `"flatModuleOutFile"` were added by a previous version of the angular CLI (version 7?) when I generated this library (via `ng g library`). If these compiler options are no longer needed by the current CLI, I would expect the migration to remove them without error.

The error was made more confusing because the error message references an angular configuration option that is not actually present in my tsConfig file: `"flatModuleIndex"`.

## 🔬 Minimal Reproduction

A reproduction repo can be found here: https://gitlab.com/service-work/is-loading/tree/angular-update-issue

From the repo root, run

1. `yarn install`
2. `yarn ng update @angular/core --force --migrate-only --from=8`

## 🔥 Exception or Error
<pre><code>TypeScript project "lib/tsconfig.lib.json" has configuration errors. This could cause an incomplete migration. Please fix the following failures and rerun the migration:
    error TS100: Angular compiler option "flatModuleIndex" requires one and only one .ts file in the "files" field.
</code></pre>

## 🌍 Your Environment
<pre><code>
Angular CLI: 9.0.0-rc.10
Node: 10.16.0
OS: darwin x64

Angular: 9.0.0-rc.11
... common, compiler, compiler-cli, core, language-service
... platform-browser, platform-browser-dynamic
Ivy Workspace: Yes

Package                            Version
------------------------------------------------------------
@angular-devkit/architect          0.900.0-rc.10
@angular-devkit/build-angular      0.900.0-rc.10
@angular-devkit/build-ng-packagr   0.900.0-rc.10
@angular-devkit/build-optimizer    0.900.0-rc.10
@angular-devkit/build-webpack      0.900.0-rc.10
@angular-devkit/core               9.0.0-rc.10
@angular-devkit/schematics         9.0.0-rc.10
@angular/cli                       9.0.0-rc.10
@ngtools/webpack                   9.0.0-rc.10
@schematics/angular                9.0.0-rc.10
@schematics/update                 0.900.0-rc.10
ng-packagr                         9.0.0-rc.7
rxjs                               6.5.4
typescript                         3.6.5
webpack                            4.41.2
</code></pre>

**Anything else relevant?**

**Comment by rhalff** [comment]
Had the same error and also removed the entries as suggested by @thefliik which seems to fix those errors. The particular migration where this occurs is: `migration-v9-undecorated-classes-with-di`

**Comment by devversion** [comment]
I had a look at this issue. The options for `flatModuleId` and `flatModuleOutFile` had been removed in the CLI with https://github.com/angular/angular-cli/commit/718ee15b9a1d7b9d7ad520f25c67b8659059a33a. This has been done because `ng-packagr` (which is used to build the libraries) automatically set these options when it compiles the library.

I think a migration hasn't been created for this because there was no actual need to get rid of this. Keeping the options in the library `tsconfig` does not cause any problems unless the `tsconfig` is used outside of `ng-packagr`. This was not anticipated, but now is common in `ng update` migrations.

The `ng update` migrations try to create an instance of the `AngularCompilerProgram` by simply parsing the `tsconfig`. The migrations make the assumption that `tsconfig` files are not incomplete/invalid. They _definitely_ are in the file system, but it works since ng-packagr in-memory completes the invalid `tsconfig` that can be passed to `@angular/compiler-cli`.

We can't have this logic in the `ng update` migrations because it's out-of-scope for individual migrations to distinguish between libraries and applications. Also it would be out-of-scope to parse the `ng-packagr` configuration and handle the tsconfig in-memory completion.

As a workaround we could in-memory remove the `flatModule*` options in the migrations. This should be acceptable since we don't emit the program and don't rely on flat module bundling.
