### ISSUE TITLE
FormControls updateOn property should be able to set

### ISSUE THREAD

**Issue by bjornandersson** [angular/angular#35005]
# 🚀 feature request

### Relevant Package
This feature request is for @angular/forms

### Description
The only way to set a FormControl's updateOn property is in the constructor. In my case I'm writing an app and a library of controls for myself and my team to use. We have a set of custom validators that all are supposed to work with `updateOn: 'blur'` and so in my BaseValidator (which all validators extend) I want to force `updateOn: 'blur'`. However, the FormControl is defined in the app that consumes the BaseValidator.

### Describe the solution you'd like
```
const fc = new FormControl('');
fc.setUpdateMethod('blur');
```

### Describe alternatives you've considered
I've tried to work around the issue by using setControl but to no avail.

**Comment by bene-starzengruber** [comment]
This would be very appreciated.
As a workaround it is currently possible to do something like this

```
Object.defineProperty(this.formGroup, 'updateOn', {
      get: () => wantedUpdateStrategy,
      configurable: true
    });

```

**Comment by fimius23** [comment]
It can be a good user experience to validate once you know the user's intention (e.g. for text fields updateOn: 'blur'), but then hide any error messages once the user has fixed the issue (i.e. updateOn: 'change'). Because there is no way to dynamically change the updateOn this can be cumbersome when instantiating a FormControl everytime just to change the updateOn, and having to copy over as much state as possible (i.e. value, dirty, etc.)

So please consider making this change.
