### ISSUE TITLE
"validate-commit-message" lint check should only verify commits that belong to a given PR 

### ISSUE THREAD

**Issue by AndrewKushnir** [angular/angular#35021]
Currently the "validate-commit-message" lint check for PRs verify all commits from v9.0.x to HEAD (which is ~850 commits atm). Instead, the "validate-commit-message" lint check should only verify messages for commits that belong to a given PR.

**Comment by gkalpak** [comment]
FWIW, the reason it checks all commit since 9.0.x (i.e. the reason it considers the 9.0.x branch to be the base branch) is that `package.json > version` on master still points to 9.0.0-rc.1, instead of 10.0.0-beta.0 or something.

<sub>This has caused a couple of issues in the past, but it seems that it is not part of our process when creating an RC branch to update `package.json > version` on master to reference the next version 🤷‍♂</sub>

**Comment by AndrewKushnir** [comment]
I believe this is not happening right now, so I'm closing this ticket.
