### ISSUE TITLE
Make ViewEncapsulation.NONE the default component behavior.

### ISSUE THREAD

**Issue by jelbourn** [angular/angular#3505]
Say we have a component like this:
```ts
@Component({
  selector: 'slider',
  host: {
    'class': 'md-slider'
  }
})
@View (...)
class MdSlider { ... }
```
used in a template like this:
```html
<style>
  .md-slider {
    color: red;
  }
</style>

<md-slider [value]="testValue"></md-slider>
```
For the developer that has never touched the Shadow DOM before, the fact that this `<style>` doesn't work is a frustrating mystery. Given the state of the Shadow DOM draft and its and lukewarm reception, emulation should be an _opt-in_ feature.

**Comment by tbosch** [comment]
I don't agree. A developer that does not know about style encapsulation would put the `<style>` tag probably into a stylesheet and put it into the `<head>` of his `index.html`, instead of adding an inline `<style>` tag into the template of a component.

Making styles that are mentioned in the template of a component local to that component is logical in that all other things that are mentioned in the annotations of that component are also local to that component.

**Comment by mhevery** [comment]
I think you get both. If you put `<style>` in component than it is encapsulated, if you put it in head it is not.  I vote for keeping the current behavior.

Will close, please re-open if you have new use cases which should be considered.
