### ISSUE TITLE
Ivy template type checking doesn't narrow types in output positions

### ISSUE THREAD

**Issue by DavidANeil** [angular/angular#35073]
# 🐞 bug report

### Scope
@angular/compiler-cli
Specifically: Ivy template type checking

### Is this a regression?
No.

### Description / Reproduction
Given a template such as
```
<some-component
    *ngIf="myVar"
    [anInput]="myVar.otherVal"
    (anOutput)="myFunc(myVar)"
></some-component>
```
And the owning component class contains
<pre><code>    public myVar?: {otherVal: number};
    public myFunc(aDefinedVal: {otherVal: number}) {}
</code></pre>

The type checker will correctly know that `myVar.otherVal` is a safe operation under `strictNullChecks` because of the `*ngIf`, but the checker will incorrectly throw an error on the `myFunc(myVar)`, claiming that `myVar` is of type `{otherVal: number} | undefined` which is not assignable to type `{otherVal: number}` (diagnostic code `NG2345`).

## 🌍  Environment
"@angular/common": "9.0.0-rc.11",
"@angular/compiler": "9.0.0-rc.11",
"@angular/compiler-cli": "9.0.0-rc.11",
"@angular/core": "9.0.0-rc.11",

Compiled using Bazel and `--define=angular_ivy_enabled=True`

**Comment by DavidANeil** [comment]
I dropped the following test into packages/compiler-cli/test/ngtsc/template_typecheck_spec.ts to verify the issue.
```
fit('ngIf should narrow on output types', () => {
  env.write('test.ts', `
    import {Component, Directive, NgModule, EventEmitter, Output} from '@angular/core';

    @Component({
      selector: 'test',
      template: '<div *ngIf="prop" dir (foo)="func(prop)"></div>',
    })
    class TestCmp {
      prop?: string
      func(str: string) {}
    }

    @Directive({selector: '[dir]'})
    class TestDir {
      @Output() foo: EventEmitter<void>;
    }

    @NgModule({
      declarations: [TestCmp, TestDir],
    })
    class Module {}
  `);
  env.tsconfig(
    {fullTemplateTypeCheck: true, strictOutputEventTypes: true});
    const diags = env.driveDiagnostics();
    expect(diags.length).toBe(0);
    // console.error(diags[0].messageText);
});
```

The issue happens both with and without `strictOutputEventTypes`

**Comment by JoostK** [comment]
The issue here is that TypeScript's CFA (Control Flow Analysis) does not retain the narrowing result of a non-const variable inside of a closure, as the value may have changed before the closure is invoked. More info can be found in numerous reported TypeScript issues, refer to microsoft/TypeScript#7719, microsoft/TypeScript#10357, microsoft/TypeScript#9998 and various others for more detail.

In below samples, let's assume the following code snippet:

```ts
interface Person { name: string }

@Component({
  template: '<div some-dir (click)="handleEvent(person.name, $event)" (dirOutput)="handleEvent(person.name, $event)"></div>',
})
class AppComponent {
  person: Person | null;

  handleEvent(person: Person, $event: MouseEvent): void {}
}

@Directive({ selector: '[some-dir]' })
class SomeDirective {
  @Output()
  dirOutput = new EventEmitter<MouseEvent>();
}
```

I see two possibilities to address this limitation:

1. Introduce a `const` variable for each property read from the component, and relay reads to this variable in the type-check block. This approach should benefit from retaining the narrowing result because of the `const`ness of the variable:

```ts
function tcb(ctx: AppComponent): void {
  const person = ctx.person;
  const dir: SomeDirective;
  if (person !== null) {
    // DOM event
    document.addEventListener('click', function($event) { ctx.handleEvent(person, $event); });

    // Directive output
    dir.dirOutput.subscribe(function($event) { ctx.handleEvent(person, $event); })
  }
}
```

2. Avoid using function callbacks for checking events altogether. We do use a callback function currently to infer the type of `$event` based on `document.addEventListener`/`EventEmitter.subscribe`, but we can use an alternative approach to infer the type of `$event`:

```ts
function tcb(ctx: AppComponent): void {
  const dir: SomeDirective = null!;
  if (ctx.person !== null) {
    // DOM event
    {
      const $event: HTMLElementEventMap['click'] = null!;

      ctx.handleEvent(ctx.person, $event);
    }

    // Directive output
    {
      const $event: typeof dir.dirOutput extends EventEmitter<infer T> ? T : Parameters<typeof dir.dirOutput.subscribe>[0] = null!;

      ctx.handleEvent(ctx.person, $event);

      // Note: the `extends EventEmitter<infer T>` conditional type trick is present to solve the problem for which we currently emit a call to `_outputHelper` into the type-check block.
    }
  }
}
```

**Comment by alxhub** [comment]
I can't think of any way of doing type inference for `$event` without actually being inside the closure, and I don't want to give that up.

The closest I could get is:

```typescript
type $event = HTMLDivElement['addEventListener'] extends (ev: 'progress', fn: ($event: infer E) => any) => void ? E : never;
```

which illustrates how I think one would "ask the question". However, this returns only `Event` since it always matches the fallback. If I remember right, the multiple signatures in TS are this special kind of type which isn't really reflected well in the "visible" type system.

I don't think option 1 works, actually. It does for your example because the guard is simple: `person !== null`. If the template did `*ngIf="person.name"` instead:

```typescript
function tcb(ctx: AppComponent): void {
  const person = ctx.person;
  const handleEvent = ctx.handleEvent;
  const dir: SomeDirective = null!;
  if (person.name !== null) {
    document.addEventListener('click', function($event) {
      // error: person.name no longer narrowed (same problem as before).
      handleEvent(person.name, $event);
    });
  }
}
```

There's also option 3: repeat the guards within the event closure:

```typescript
function tcb(ctx: AppComponent): void {
  const person = ctx.person;
  const handleEvent = ctx.handleEvent;
  const dir: SomeDirective = null!;
  if (person !== null) {
    // DOM event
    document.addEventListener('click', function($event) {
      if (person !== null) {
        handleEvent(person, $event);
      }
    });

    // Directive output
    dir.dirOutput.subscribe(function($event) {
      if (person !== null) {
        handleEvent(person, $event);
      }
    });
  }
}
```

This is I think my favored approach; however, it's not trivial to implement since the guards may have been generated at a much higher level. We'll have to keep track of the currently active guards and be able to repeat them on demand.

**Comment by JoostK** [comment]
Hi @DavidANeil, thanks for the report and the testcase! I have a PR that implements Alex's proposal to repeat the template guards within the event handlers, so their narrowing effect will be in effect.

**Comment by DavidANeil** [comment]
Thanks for the quick work!
I'm glad the resolution didn't involve entirely rewriting the type checker.
