### ISSUE TITLE
Lazy load module via http-request at runtime 

### ISSUE THREAD

**Issue by kschwidder** [angular/angular#35081]
# 🚀 feature request

Currently angular and ivy are capable to lazy load routing modules and via the import('module') instruction. The compiler generates bundles for the module only and only if a quoted string is passed to import.

A high-level interface to load a module on demand at runtime from the file system or via http call would be beneficial.

### Relevant Package

 This feature request is for @angular/....
@angular/core compiler and loader

### Description
 A clear and concise description of the problem or missing capability...

A module can be imported via import('module'). The 'module' has to be a string and can not be a variable as the compiler is unable to detect and to generate the appropriate module chunks.

### Describe the solution you'd like
 If you have a solution in mind, please describe it.
it should be possible to load via import a module over http or from the file system as follows:

loadModule( path: string ) {
  await import(path).then(...)
}

### Describe alternatives you've considered
 Have you considered any alternative solutions or workarounds?
The only capable solution is to use SystemJS loader. As some of the interfaces are deprecated with angular 9 a solid solution is required from within the framework. It would be excellent if a high-level API is provided which can load the module via http and then instantiate the desired component etc. 

This will truly enable dynamic module instantiation at runtime while compiling modules in separate projects beforehand.

**Comment by mlc-mlapis** [comment]
@kschwidder Actually, there is already dynamic import available and its syntax `() => import('./modules/any/any.module').then(m => m.AnyModule)`, which is available for Angular 8 or higher.

**Comment by kschwidder** [comment]
The import statement as mentioned compiles the chunk due to the given string. 
If you create a library with ng generate library nodes; do an ng build nodes and try to load the module as follows

Const path = ‚/modules/generated/nodes.umd.js‘
import(path).then(...)

It will not load the module as the runtime complains that nodes can not be found even if tibia present.

As what I understood is that the angular ivy compiler analyzes the import string to detect which module has to be build as a chunk. 

I have googled the universe and there is no simple way to generate a module and load it at runtime if it is compiled separately.

**Comment by mlc-mlapis** [comment]
@kschwidder Ah, separately, like plugins, right? And you mean that it is still an Angular module. Yep, it's a real problem, because there are many edge cases when those separated modules use something from Angular core-libs. It means, that you either have to include all that duplicity many times or you have to include the full Angular core-libs into the main bundle, so no tree-shaking. And still with the primary condition, that all parts use the same Angular version.

`Angular Elements` was introduced to solve the problem as the web components concept. We will see what IVY brings on the table.

**Comment by KarlXOL** [comment]
Working with on demand/lazy modules and components is still a pain!

The application and business logic get wasted by loading logic (to some degree) and the need to reflect the module, folder structure in your code.

So far Ivy hasn't brought real improvements to this topic. I really hope Ivy(10) fullfills some of the promises they have been made

**Comment by FooBrak** [comment]
I've achieved this by using SystemJS and Angular's ViewEngine by using plugin's UMD files and works great. From what I have seen and searched, Ivy doesn't seem to offer this flexibility because it doesn't support shared runtime dependencies, everything must be known at compile time mainly for tree-shaking and reducing bundle size. Have to stay on ViewEngine for this reason.

Being able to build plugins outside of the scope (build) of the main application is somewhat a very interesting feature for micro frontends architecture... even if this means having a large main bundle size. 

Being able to load dynamically angular modules from plugins enables a whole set of possibilities compared to Angular elements, correct me if I am wrong.

A related post for Ivy on twitter from maintainer of SystemJS:
[https://twitter.com/Joelbdenning/status/1253781652486017024](https://twitter.com/Joelbdenning/status/1253781652486017024)

**Comment by petebacondarwin** [comment]
I believe that webpack 5 federated modules might be the solution you need.

**Comment by FooBrak** [comment]
@petebacondarwin 
Wow thanks, I didn't saw this when I started my architecture with plugins at the beginning of last year... but this is exactly what I am searching for, and from what I see it will be easy to hook up since the concept fits all into place in my stuff. Looking forward for this. The only question I have is if a microfrontend plugin component can be injected with services provided from a host module with the use of injection tokens? This is really useful for interacting between plugin components.

**Comment by petebacondarwin** [comment]
This is all something that @alxhub has been investigating recently. He may be able to comment further.

**Comment by grzhan** [comment]
@petebacondarwin , any updates on this?  We really need this feature :)

**Comment by alxhub** [comment]
We have a longer-term effort to study use cases for features such as this, in the context of scalable architectures like microfrontends. It's currently on our [Roadmap](https://angular.io/guide/roadmap#investigate-micro-frontend-architecture-for-scalable-development-processes), so I'm marking this feature request as a project in progress.

That does not mean that we'll eventually implement such APIs - we're going to study these kinds of problems and decide if and how Angular should solve them.

**Comment by Aeseir** [comment]
@alxhub that is great initiative to have microfrontends architecture as part of the roadmap. My experience and personal opinion is since Angular is a framework, having the ability to create microfrontend structure same way you can currently monorepo structure, using best practices and packages within Angular, will elevate the framework to the next level.
Using 3rd party packages, while they are powerful in a lot of cases, makes you wonder if there is a better way to do these things, and most importantly if it is future proof. At enterprise level, future proofing (at least to a degree) is a big ticket item in a lot of conversations.

**Comment by alxhub** [comment]
I'm going to close this tracking issue, for a couple reasons:

1) we're trying to ensure that the features flowing through our feature request process are discrete projects that we can implement (or not) independently. since this request is tied to a much larger effort (module federation), it's not something we can track/implement separately.

2) Angular as a framework is agnostic of the bundling/linking process - it doesn't care where code comes from. As long as you can provide a reference to a component or NgModule that's using the same instance of the `@angular/core` runtime, it can be rendered.

Truly dynamic loading of a library like this is thus a _bundling_ problem, not a framework problem. That is, this kind of functionality would need to be supported by the bundler in question (e.g. Webpack in the Angular CLI).
