### ISSUE TITLE
angular.io homepage doesn't load without cookies enabled

### ISSUE THREAD

**Issue by mverver-google** [angular/angular#35104]
# 📚 Docs or angular.io bug report

### Description

When the browser is configured not to accept cookies, the angular.io homepage shows a blank page without any content.

(I previously filed bug #33795 for this, but it was closed without the issue ever being resolved, and I don't have permission to reopen the bug.)

### What's the affected URL?**
https://angular.io/

### Reproduction Steps**
Disable cookies in your browser, or block cookies for the angular.io domain only. Then visit https://angular.io/

### Expected vs Actual Behavior**
Expected behavior: static content is visible as normal.
Actual behavior: page shows no content at all.

## 📷Screenshot
The page is completely blank; I don't think a screenshot would clarify the issue.

## 🔥 Exception or Error
In Chrome, the Javascript console contains some errors related to Window.sessionStorage (which isn't available when cookies are disabled, apparently), and some other errors which I'm not sure if they're related.

Details: https://gist.github.com/mverver-google/11f8b2239bdaaf1cc986d37d68632985

### Browser info
Issue is reproducible in both Chrome and Firefox.

**Comment by gkalpak** [comment]
This has been fixed in #33829. The fix has been deployed to https://next.angular.io/, but not to https://angular.io/ yet. It will be deployed to angular.io once 9.0.0 is released (unless the fix is backported to 8.2.x).

The reason it took so long to deploy the fix to angular.io is that v9 has remained in RC much longer thn initially anticipated. Sorry for the confusion this has caused .At this point (with the release of 9.0.0 just around the corner), it probably doesn't make sense to backport the fix to 8.2.x.

@mverver-google, please use next.angular.io for the next few days (until 9.0.0 is released and deployed to angular.io). (If anyone feels strongly about it, feel free to submit a PR backporting #33829 to the 8.2.x branch :grin:)

**Comment by mverver-google** [comment]
Aha. Thanks for clarifying that. (I didn't expect bug fixes to take so long to be released to production!)

The issue does appear to be fixed on https://next.angular.io/.

**Comment by mverver-google** [comment]
It looks like the update was pushed live, and the site now loads with cookies disabled, but there's still a small bug: at the top of the page, there's a "go to survey" banner that is always visible (but it's not present when loading the site with cookies disabled). Clicking the link or the X to close the banner doesn't do anything.

Screenshot:

![screenshot-angular io-2020 02 18-23_02_43](https://user-images.githubusercontent.com/51914656/74836044-e1c30480-531e-11ea-94a0-3029ae3fa7f1.png)

**Comment by gkalpak** [comment]
Thx, @mverver-google! I'll take a look 😞
