### ISSUE TITLE
Angular 2.0 alpha 34 error loading router.dev.js

### ISSUE THREAD

**Issue by hitmanmcc** [angular/angular#3528]
Hello,

I was just changing my app from alpha 33 to alpha 34 and when I tried to load it, it wouldn't work and produced the following error message:
```
Error: System.get(...).retrieveGlobal is not a function
	Error loading http://localhost:63057/app/app.js
    at https://code.angularjs.org/2.0.0-alpha.34/router.dev.js:5:41
    at u (http://localhost:63057/dependencies/systemjs-0.18/system.js:4:19870)
    at a (http://localhost:63057/dependencies/systemjs-0.18/system.js:4:18435)
    at Object.Promise.all.then.execute (http://localhost:63057/dependencies/systemjs-0.18/system.js:4:23255)
    at b (http://localhost:63057/dependencies/systemjs-0.18/system.js:4:7874)
    at S (http://localhost:63057/dependencies/systemjs-0.18/system.js:4:8253)
    at p (http://localhost:63057/dependencies/systemjs-0.18/system.js:4:6131)
    at h (http://localhost:63057/dependencies/systemjs-0.18/system.js:4:6516)
    at http://localhost:63057/dependencies/systemjs-0.18/system.js:4:4822
    at Zone.run (https://code.angularjs.org/2.0.0-alpha.34/angular2.dev.js:136:17)
```
Which the message indicates that it stems from the following line of code:
```javascript
return System.get("@@global-helpers").retrieveGlobal(__module.id, false);
```
I perused through the rest of the files and I see that retrieveGlobal, along with prepareGlobal, are defined in the angular2.sfx.dev.js file, which I have never used. Correct me if I'm wrong but that file is meant for people writting code in ES5 spec and I'm writing ES6 code.

Has anyone stumbled upon this yet or am I the only one with this problem?

Best regards,
André

**Comment by pkozlowski-opensource** [comment]
This one is "interesting" - what is going on here is that SystemJS builder is auto-detecting https://github.com/angular/angular/blob/master/modules/angular2/src/router/route_definition.ts as a file with "global module" system. This happens since https://github.com/angular/angular/blob/master/modules/angular2/src/router/route_definition.ts is "empty" - that is - it contains only TS interface definitions so after transpilation to JS it is effectively empty.

I guess this started to be a problem after TS or SystemJS version update, since the "empty" file was there from like 2.0.0-alpha.32 (4d28167bc075a57fd204d23abbf4e408b78a406c).

@hitmanmcc as a work-arround you can add "global" plugin to your SystemJS config.
@btford I guess this should have med / high priority as I guess it will break people's code quite often...

**Comment by hitmanmcc** [comment]
@pkozlowski-opensource Thank you very much for the explanation and the workaround. :)
I'll try it out as soon as I can and report back.

**Comment by hitmanmcc** [comment]
Hello again @pkozlowski-opensource, I was wondering if you could elaborate a bit on your workaround. I was trying to do what you told me but I'm not so familiar with how SystemJS works so I'm pretty sure I'm doing something wrong. Would you please post the line I need to add to config.js to load the global plugin? Thanks in advance.

**Comment by pkozlowski-opensource** [comment]
> I'm not so familiar with how SystemJS works so I'm pretty sure I'm doing something wrong. Would you please post the line I need to add to config.js to load the global plugin? 

@hitmanmcc the problem is that we are using a relatively old version of the SystemJS builder so config is a bit involved and probably not the easiest to explain to something new to module loading / systemjs. What you can do instead is to remove the offending line from https://code.angularjs.org/2.0.0-alpha.34/router.dev.js

Just replace `return System.get("@@global-helpers").retrieveGlobal(__module.id, false);` with `return {};`, see: http://plnkr.co/edit/8yAktull0fFQIW82hZOU?p=preview

I'm looking at the root cause of this issue as we speak

**Comment by hitmanmcc** [comment]
Thanks for the quick reply @pkozlowski-opensource but alas, that did not work as well.
I have two sample applications where I tried loading a local version of the router.dev.js script with the modification you instructed me to perform. Both of them produced the same error, that states that there is no provider for the Router.
![image](https://cloud.githubusercontent.com/assets/3464842/9172281/7e82ee3e-3f6a-11e5-931a-bcd194c7ffc3.png)

![image](https://cloud.githubusercontent.com/assets/3464842/9172294/8dc41db4-3f6a-11e5-8ad3-1215d74ea2c8.png)

If there's anything I can do to assist you in tracking down the issue, feel free to ask.

**Comment by pkozlowski-opensource** [comment]
@hitmanmcc I've identified the root cause (see https://github.com/systemjs/builder/issues/271) and will have a PR for angular repo shortly. So the pb with the build is well identified and we don't need help tracing it, thnx.

Regarding the error you are getting - I'm not sure I can help more without having access to your setup. I've got the impression that the error you are getting is not related to the loading problem we are discussing here. 

The best I can do is to share with you a plunker with a version of a Router build locally. As you can see router loads without pbs in this plunk: http://plnkr.co/edit/TGWFcnQC5f3jrPmdnwXZ?p=preview

Try to demonstrate the issue in this plunk, maybe someone will be able to help you then.
