### ISSUE TITLE
lazy module components are missing in chunk bundle after ng build v9

### ISSUE THREAD

**Issue by mlakmal** [angular/angular#35314]
We have lazy modules loaded dynamically in our application. components in these modules are not referenced by another route level component since those components are dynamically generated after manually lazy loading the module.

after v9, it seems like build optimization process is striping/tree shaking out the components that are not referenced in a template. all our lazy module bundles are generated without the components in them and this is breaking our dynamic loading support. Do we have an option to make sure components are always included in a bundle?

```javascript
//lazy module with component not referenced by another component template
@NgModule({
  imports: [CommonModule],
  declarations: [
    InterestQuestionsComponent
  ],
  entryComponents: [
    InterestQuestionsComponent
  ],
  exports: [
    InterestQuestionsComponent
  ]
})
export class EngageModule {
  static forRoot(): ModuleWithProviders<EngageModule> {
    return {
      ngModule: EngageModule,
      providers: [
        InterestQuestionModel
      ]
    };
  }
}

//route definition
{
    path: 'engage-lazy',
    loadChildren: () => import('./../../lazy-modules/engage/engageModule').then((m) => m.EngageModule)
  }
```

after "ng build", bundle for above 'engage-lazy' route does not include "InterestQuestionsComponent". “ng serve” works without any issue.

we are using typescript v3.8.0-dev.20200207 since compiler is slow due to below issue. rolled back to 3.7.5 and issue still exists.
https://github.com/angular/angular/issues/34699

**Comment by JoostK** [comment]
The fact that components are tree-shaken away when not referenced is by design. Normally, the lazy loaded modules references components in a `Router.forChild` call, causing the components to be referenced and therefore not tree-shaken away. In your situation, no such reference exists so there is no way to get access to the components, so they are not present in the bundle.

**Comment by mlakmal** [comment]
@JoostK thanks for the explanation. 
i am going to add below "static entrycomponents" property, which should resolve it on our end temporally.
```javascript
export class EngageModule {
  static entryComponents = [InterestQuestionsComponent];

  static forRoot(): ModuleWithProviders<EngageModule> {
    return {
      ngModule: EngageModule,
      providers: [
        InterestQuestionModel
      ]
    };
  }
}
```

is their better way to handle this  ? (ex: using a decorator on a component, so i don't have to define the components like above... i am not sure how tree shaking identify component should not be skipped)

**Comment by JoostK** [comment]
Defining a decorator alone would not solve the issue, as it does not introduce a reference from the ECMAScript module you lazily import to the ECMAScript module where the component is declared. Although the NgModule references the component class in its declarations, the Ivy compiler will fully remove those references to achieve its tree-shaking goal. In your sample above, the `entryComponents` field will not be removed by the Ivy compiler, so the references stay intact.

From the framework perspective there's no action item here, this works as intended. If you have additional questions, feel free to continue the thread.

**Comment by mlc-mlapis** [comment]
@JoostK I am a bit lost with your explanation. The reason why `entryComponents` existed before was the fact that such components were used only by the dynamic (programmatic) way (like dialogs), so they weren't explicitly placed to any template or used in any route. What has been changed / how Angular compiler is smarter than before, that in Angular 9 there isn't a necessity to use `entryComponents` metadata?

**Comment by JoostK** [comment]
The `entryComponents` array as it was required in ViewEngine has to do with the `ComponentFactoryResolver` API. This API was the only way to obtain the ngfactory code for a component, and the AOT compiler would generate an instance of `CodegenComponentFactoryResolver` that contains a `Map` of all component declarations to their ngfactory code. The ViewEngine compiler would detect which components are actually used from within templates, these would be added to the `Map` automatically. The `entryComponents` API was present to force a component to be added to that `Map`, so that it could be loaded dynamically at runtime.

In Ivy, the ngfactory is stored directly on the component class as a static property, so there's no global `Map` to track all components. Instead, having access to the component itself is enough to render it dynamically, so the reason why `entryComponents` existed is no longer applicable. From that perspective, I'm actually confused as to how @mlakmal is able to render a component dynamically if there's no reference to the component class available somewhere.

I recommend watching @alxhub's [presentation at Devoxx 2018](https://youtu.be/lg7l8quJuS4), as he explains this exact topic. This topic in particular is discussed [around 31:30](https://youtu.be/lg7l8quJuS4?t=1890), but you may want to watch it in full ;)

**Comment by mlakmal** [comment]
@JoostK  thanks for the additional details. 
we are using a decorator on each component to keep track of the class/type against string literal (like below). when we want to dynamically generate below component we look for the type against string 'ComponentB' and dynamically generate the component. this seems to work perfectly in v8 (with having same component listed under NgModule entryComponents array). looks like with v9 it does not include the entrycomponents in optimized bundle by default (per your explanation above). we will handle this change on our side to support v9.

```javascript
@DynamicComponent({
name: 'ComponentB',
type: ComponentB
})
@Component() 
export class ComponentB{}
```

**Comment by mlc-mlapis** [comment]
@JoostK Thank you for refreshing me. With @mlakmal additional explanation, that they have used literal string lookups, to get component types for their later dynamic instantiating, it's also clear what kind of problem they have in Angular 9. If they had used only standard imports, then even those components would be linked somewhere, and the Angular building path could understand that they are used somewhere, and that's why they shouldn't be removed from the final bundles. But with string literals, it's a problem to do the same.
