### ISSUE TITLE
Omitting / misspelling directive selector fails silently

### ISSUE THREAD

**Issue by pkozlowski-opensource** [angular/angular#3533]
Can you quickly spot a problem?

```javascript
import {Component, Directive, View, bootstrap} from 'angular2/angular2';

@Directive({
  slector: '[test]'
})
class Test {
  constructor() {
     console.log('Activating Test');
  }
}  

@Component({
    selector: 'hello'
})
@View({
    template: `<div test></div>`,
    directives: [Test] 
})
class Hello {
}

bootstrap(Hello);
```

It took me ~10 mins to figure out that `@Directive`'s `selector` property is misspelled, effectively removing selector from a directive. We should throw clear error message in such a case.

**Comment by pkozlowski-opensource** [comment]
This happens in JS, didn't test in Dart. But I guess we've got the same pb for other properties of decorators.

**Comment by mhevery** [comment]
This will be handled with https://github.com/Microsoft/TypeScript/issues/4152 and https://github.com/Microsoft/TypeScript/pull/3823 described here: https://github.com/Microsoft/TypeScript/wiki/Breaking-Changes#strict-object-literal-assignment-checking

I think that should be sufficient. Can we close the issue?

**Comment by pkozlowski-opensource** [comment]
@mhevery Indeed, it looks like Microsoft/TypeScript#4152 should fix it. IMO we can close this one but I'm a bit worried that we are not tracking (or maybe we do?) updates to next TS version. From what I can see we are still pointing to @alexeagle fork.

@alexeagle what is the plan (if there is one) of updating TS versions / moving to a npm-released one?

**Comment by alexeagle** [comment]
We are currently on a minimal delta from released 1.5.3.
I've already done some work to upgrade to 1.6, which contains the fixes we
need, so unless we need some other bleeding-edge fix, we should be able to
update to 1.6 as soon as it's released.
We got an indication that may be soon (long enough before AngularConnect
that we might be able to use the new features by then).

(We can't update to 1.6 now because that would require our users to also
upgrade, and we don't want to be in that state when ng2 goes beta)

**Comment by pkozlowski-opensource** [comment]
@alexeagle thnx for the update! I'm going to close this one for now and will re-test as soon as we are on 1.6. Thnx again.

**Comment by alexeagle** [comment]
It would be cool to have a 1.6 version of our JS build on Travis. But it's
not easy to have both versions listed in package.json. Let me know if you'd
like to pick that up
