### ISSUE TITLE
service worker: Allow to override strategy for each request

### ISSUE THREAD

**Issue by cghislai** [angular/angular#35337]
The current service worker already provides two strategies for data asset: freshness and performance. Which is great.

It would be great to be able to override the strategy used on a request basis at runtime.

Our use case is as follow:
We fetch a list of referenceA from some endpoint, then for each referenceA we fetch the corresponding entityA, relying on the `performance` strategy of the service worker cache.
We display those entities in a table, and in some cell we have a component that fetch another entityB referenced from entityA.
All entitiesA displayed in the table may reference the same entityB, so we rely on the service worker cache to send a single network request for that one.

Now another client updates an entityA, and the server send us back an entityAUpdateEvent. At that point, we would like to force the sw to fetch and cache a new copy of a given entityA. AFAIK, this is currently not possible.

Im thinking of an header/query param like `ngsw-bypass` that would allow to override the configured strategy (so that we could use freshness in our usecase) - or just send a network request and cache it. If im not mistaken, requests sent using ngsw-bypass will not be cached. 

This would probably allow other use cases like those described in #20402 as well: To implement a response that emit the cache value then the network value, you could concat/merge a request made using the performance strategy with one using the freshness strategy.

**Comment by gkalpak** [comment]
Thx for opening the issue, @cghislai. 
Leaving it open as a feature request, but (just to set expectations) there are no plans to get to this in the near future.

**Comment by gkalpak** [comment]
Given the low demand for this feature, I am going to close this (since we are unlikely to ever get around to implementing it).

As a work-around, one might be able to define duplicate data-groups (differentiated by a query param) with different strategies. Something like:

```json
{
  ...
  "dataGroups": [
    {
      "name": "data-fresh",
      ...
      "urls": [
        "https://some/endpoint/**?fresh"
      ]
    },
    {
      "name": "data-perf",
      ...
      "urls": [
        "https://some/endpoint/**"
      ]
    }
  ]
}
```

This allows switching to a "network-first" request strategy by appending the `fresh` query parameter.
<sub>(This is just a POC. A more production-ready implementation would take into account the fact that `fresh` might not be the only/first query param.</sub>

This is not the ideal ideal solution (as it will, for example, cache requests twice (once for each data-group) and you need extra logic in the app to append the query param to related requests and deal with the fact that the resource might only be available in one of the data-groups' cache when offline), but might be good enough as a work-around for specific usecases.
