### ISSUE TITLE
AbstractButton is not declared in any Angular module

### ISSUE THREAD

**Issue by splincode** [angular/angular#35360]
### Affected Package

Maybe affected with Angular language service for IDEA support

### Is this a regression?

Not sure

### Description

After updating code inspections in IDEA show errors

## 🔬 Minimal Reproduction

Angular 8

```ts
type ButtonSizeType = 'big' | 'small';

export class AbstractButton {
    @Input() public disabled: boolean = false;
    @Input() public full: boolean = false;
    @Input() public size: ButtonSizeType = 'big';
    @Output() public onClick: EventEmitter<void> = new EventEmitter();
}

@Component({
    selector: 'add-button',
    templateUrl: './add-button.component.html'
})
export class AddButtonComponent extends AbstractButton {}


@NgModule({
  declaration: [ AddButtonComponent ],
  exports: [ AddButtonComponent ]
})
export class ButtonModule {}
```

```
$ ng update
```

Angular 9

```ts
@Direcitve() // <----   auto decorated after update 
export class AbstractButton {
    @Input() public disabled: boolean = false;
    @Input() public full: boolean = false;
    @Input() public size: ButtonSizeType = 'big';
    @Output() public onClick: EventEmitter<void> = new EventEmitter();
}

@Component({
    selector: 'add-button',
    templateUrl: './add-button.component.html'
})
export class AddButtonComponent extends AbstractButton {}


@NgModule({
  declaration: [ AddButtonComponent ],
  exports: [ AddButtonComponent ]
})
export class ButtonModule {}
```

![image](https://user-images.githubusercontent.com/12021443/74313856-84124380-4d85-11ea-9811-6a78cde91f35.png)

I tried to clear the cache and reindexing, but this does not help

## 🌍  Your Environment

- Last Angular versions (v9.0.0)
- Intellij IDEA 2019.3

**Comment by ayazhafiz** [comment]
The language service has made this diagnostic a suggestion rather than an error, which should ease the burden: https://github.com/angular/angular/pull/34115 (original issue: https://github.com/angular/vscode-ng-language-service/issues/150)

I think IntelliJ uses their own language service implementation to provide Angular language features (https://www.jetbrains.com/help/idea/angular.html). You may wish to file a ticket with them.

Closing for now; feel free to comment or open a new issue if you are experiencing any other problem.
