### ISSUE TITLE
sanitizeHTML incorrectly strips <tr> (and more tags) in IE, FF, Edge

### ISSUE THREAD

**Issue by kvetis** [angular/angular#35387]
# 🐞 bug report

### Affected Package

 The issue is caused by package `@angular/core`

### Is this a regression?

 I cannot tell. But appears already in v. 8 on stackblitz.

### Description

`sanitizeHtml` (or binding to `[innerHtml]`) strips out `<tr>` or other table related tags in Firefox, Internet Explorer, Edge. ~But working in Chrome.~ **Edit:** As of Angular 11.1.2 not working in Chrome anymore.

It can be demonstrated by following:

```
<table [innerHTML]="'<tr><td>Hello</td><td>World</td></tr>'"></table>
```

Seems the problem lies in `getInertBodyElement_DOMParser` which tries to parse the content into DOM, but directly adds the content into `body`, while adding `<tr>` into body is invalid in some browsers, resulting in stripping the elements.

Additionaly, no warning about stripped content is produced, because this happens before calling the `sanitizer` itself in `_sanitizeHtml`

## 🔬 Minimal Reproduction

 
[https://stackblitz.com/edit/angular-qbswrh?file=src%2Fapp%2Fapp.component.html](https://stackblitz.com/edit/angular-qbswrh?file=src%2Fapp%2Fapp.component.html)
Open in Firefox.

Angular 11 stopped working in Chrome as well:
https://stackblitz.com/edit/angular-zrwgse?file=src%2Fapp%2Fapp.component.html

```
<table [innerHTML]="'<tr><td>Hello</td><td>World</td></tr>'"></table>
```

## 🌍  Your Environment

**Angular Version:**
<pre><code>
@angular-devkit/architect         0.900.1
@angular-devkit/build-angular     0.900.1
@angular-devkit/build-optimizer   0.900.1
@angular-devkit/build-webpack     0.900.1
@angular-devkit/core              9.0.1
@angular-devkit/schematics        9.0.1
@angular/cli                      9.0.1
@angular/flex-layout              9.0.0-beta.29
@ngtools/webpack                  9.0.1
@schematics/angular               9.0.1
@schematics/update                0.900.1
rxjs                              6.5.4
typescript                        3.7.5
webpack                           4.41.2
</code></pre>

**Anything else relevant?**

Problem occurs in
Firefox 72.0.2
IE 11
Edge 44

**Comment by smile2014** [comment]
`<table [innerHTML]="'<tr><td>Hello</td><td>{{value}}</td></tr>'"></table>`

**Comment by smile2014** [comment]
<div [innerHTML]="'<p>{{value}}</p>'"></table>

**Comment by smile2014** [comment]
<table [innerHTML]="'<div>{{value}}</div>'"></table>

let value ='abc'

**Comment by mlc-mlapis** [comment]
[**@smile2014**](https://github.com/smile2014) The value passed to `[`innerHTML\] can't contain any Angular binding. There isn't any compiler that would compile in AOT mode.

**Comment by kvetis** [comment]
This issue now affects chrome as well (a regression omewhere around Angular 11.1.2)
https://stackblitz.com/edit/angular-zrwgse?file=src%2Fapp%2Fapp.component.html

**Comment by petebacondarwin** [comment]
I think the fact it is now also doing this on Chrome is caused by the fact that we now use the `DOMParser` to sanitize HTML in Chrome as well as other browsers. And AFAICT:

```ts
const body = new window.DOMParser().parseFromString('<tr><td>Hello</td><td>{{value}}</td></tr>', 'text/html').body;
```

results in a `body` element where these `tr` and `td` tags are stripped.

**Comment by petebacondarwin** [comment]
I think this is because `<tr>` elements are not valid outside of a table.
A workaround would be to ensure that any innerHTML strings that you want to be sanitized is valid HTML on its own.

**Comment by zarend** [comment]
That's right Pete, this happens because `<tr>` cannot be used on their own. They need to be inside of a `table` element.

We use DOMPurify to sanitize our HTML, and if we wanted to allow `tr` tags on their own, we could look into implementing a DOMPurify hook. I would be very careful about that because we don't want to change the sanitization behavior and break apps or introduce security issues. Here's a DOMPurify bug report on using dom snippets with DOMPurify. [Can't sanitize some DOM snippets, e.g. <td>text</td> #190
 ](https://github.com/cure53/DOMPurify/issues/190)
 
@kvetis , here' a work-around to try 🤞 

Wrap the innerHtml in a `table` element styled as `display:contents;`
```<table [innerHTML]="'<table style=\'display:contents;\'><tr><td>Hello</td><td>World</td></tr></table>'"></table>```

**Comment by petebacondarwin** [comment]
So having looked into a potential fix for this, I have decided that this is too problematic to try to do in a generic way.
This is also the case for the leading sanitizer DOMPurify, which suggests that you work around this by using "hooks".


Angular sanitization does not have hooks but you can still work around this. Here is an example: https://stackblitz.com/edit/angular-ivy-2yrwc7?file=src%2Fapp%2Fapp.component.ts

Note that the inner table string is still sanitized as expected but the `<tr>` and `<td>` are not stripped.

Since this can be worked around fairly easily, and that there is no reliable fix that can be done generically inside the sanitizer, I am going to close this.
