### ISSUE TITLE
Unit Tests - Overriding large modules slows down createComponent

### ISSUE THREAD

**Issue by ChristopherKiss** [angular/angular#35395]
# 🐞 bug report

### Affected Package

 The issue is caused by package @angular/core/testing

### Is this a regression?

 Yes, the previous version in which this bug was not present was: ....
This is a regression from:

https://github.com/angular/angular/pull/33787
https://github.com/angular/angular/issues/33735

### Description

 A clear and concise description of the problem...
The angular style guide recommends using shared modules for re-usable features.
https://angular.io/guide/styleguide#shared-feature-module

As a result, in our production app, we have very large shared modules containing many components, pipes, services, directives, common imports for angular material, etc.

When testing one of our feature component outside the shared module, it takes 8-9 seconds to create the component when we use overrideModule.

Our use case is as follows.

- Lazy Loaded Module
-- Module 1
-- Module 2 - imports module 1, shared module, declares feature component, but doesn't export it
--- Feature Component Being Tested - spec file imports module 2, overrides module 2 to export feature component
- Shared Modules
-- contains lots of components, service, pipes, etc...

Our spec file contains 21 unit tests and these are the times for each test being run.

This is logging just the createComponent function.

![image](https://user-images.githubusercontent.com/24984762/74381599-e0399e00-4e3f-11ea-8ec3-dc314b133492.png)

This is performance tab for just 1 unit test.
![image](https://user-images.githubusercontent.com/24984762/74381639-f5aec800-4e3f-11ea-8b2e-438b2aa68f67.png)

## 🔬 Minimal Reproduction
We are unable to share our production application, however I have a minimal reproduction, the scope is smaller, but still represents the slow down factor even for a small shared module.

The order of the tests being run and the component caches affects the times, but this shows with both the fast test running first and the slow test running first.

![image](https://user-images.githubusercontent.com/24984762/74381294-4671f100-4e3f-11ea-8235-86be54738b44.png)

![image](https://user-images.githubusercontent.com/24984762/74381315-4ffb5900-4e3f-11ea-8c1f-34e7aeed5e55.png)

https://github.com/ChristopherKiss/angular-unit-test-repo

* run `npm i`
* run `ng test`
* open console and note the timings
* refresh to run tests a few times

For reference the tests are being run from `src/app/test/test/test.component.spec.ts`

## 🔥 Exception or Error
<pre><code>

</code></pre>

## 🌍  Your Environment

**Angular Version:**
<pre><code>

     _                      _                 ____ _     ___ 
    / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
   / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | | 
  / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | | 
 /_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
                |___/
    

Angular CLI: 9.0.1
Node: 12.13.1
OS: win32 x64

Angular: 9.0.0
... animations, cdk, common, compiler, compiler-cli, core, forms
... language-service, material, platform-browser
... platform-browser-dynamic, router
Ivy Workspace: Yes

Package                           Version
-----------------------------------------------------------     
@angular-devkit/architect         0.900.1
@angular-devkit/build-angular     0.900.1
@angular-devkit/build-optimizer   0.900.1
@angular-devkit/build-webpack     0.900.1
@angular-devkit/core              9.0.1
@angular-devkit/schematics        9.0.1
@angular/cli                      9.0.1
@angular/flex-layout              9.0.0-beta.29
@ngtools/webpack                  9.0.1
@schematics/angular               9.0.1
@schematics/update                0.900.1
rxjs                              6.5.4
typescript                        3.7.5
webpack                           4.41.2
</code></pre>

**Anything else relevant?**

Our shared module components make heavy use of angular material components in them.

**Comment by ChristopherKiss** [comment]
I was going to include it originally, but I forgot about it.

If I remove the override (export the component from the module instead of using override to add the export), the times to createComponent are much more reasonable.

![image](https://user-images.githubusercontent.com/24984762/74387826-c2733580-4e4d-11ea-9737-f978aa3f0553.png)

**Comment by AndrewKushnir** [comment]
Hi @ChristopherKiss, thanks for reporting the issue and detailed description of the problem.

I've created a [PR with proposed fix](https://github.com/angular/angular/pull/35454). PR still requires review and final implementation might change, but I'd like to ask if you could test your app with the changes from that PR and see if performance issue is resolved. I tested the changes from the mentioned PR with a repro that you provided and the difference between "slow" and "fast" tests was minor. Note: there is still a slight overhead when `TestBed.overrideModule` is used, since it requires scope recalculation, but it should be insignificant.

To test your app with the changes from PR #35454, you can follow an instruction in [this document on how to use PR artifacts](https://github.com/angular/angular/blob/master/docs/DEVELOPER.md#archives-for-each-package). An archive with updated `@angular/core` package that contains changes from the PR is available [here](https://625000-24195339-gh.circle-artifacts.com/0/angular/core-pr35454-7f25b3351a.tgz) (please make sure you update other `@angular` packages to `9.0.1` to avoid version conflicts). **Note**: the mentioned archive with updated `@angular/core` package is for **testing purposes only** and not suitable for production usage (that archive will be removed once PR is closed).

Thank you.

**Comment by ChristopherKiss** [comment]
@AndrewKushnir,

Thank you for the quick PR, it's currently saturday morning in Australia, so will test this first thing monday morning when I'm back at work.

Looking forward to seeing the results.

**Comment by ChristopherKiss** [comment]
@AndrewKushnir,

Confirming that your PR brings the times for `createComponent` back into a reasonable amount when using `overrideModule`.

![image](https://user-images.githubusercontent.com/24984762/74613131-ca89e880-515f-11ea-94da-518008adc707.png)

Looking forward to this landing into a release. Much appreciated.

**Comment by AndrewKushnir** [comment]
Hi @ChristopherKiss, thanks for checking the behavior with the fixes and sharing results. We'll follow our regular review/testing procedures and to land PR #35454. Thank you.

**Comment by kara** [comment]
Fixed by https://github.com/angular/angular/pull/35454
