### ISSUE TITLE
Add guidance to avoid using the webpack comment syntax for naming bundles

### ISSUE THREAD

**Issue by johnpapa** [angular/angular#35408]
Since the CLI may not support it officially.

**Comment by filipesilva** [comment]
I feel a bit torn on this one. Yes, we don't really support this. But saying we don't support something we never purported to support is a bit weird.

The bigger topic is then "does angular cli generally support the underlying features of its build system". This build system happens to be webpack, and webpack has some features, like these magic comments, that users can try to avail of on their source code.

Our official stance is that we don't offer support for build-system specific stuff. Whatever isn't a configuration option on angular.json, we don't really support.

We take this stance because we might move build systems and want the move to be as transparent to the user as possible. If we were to support these webpack specific features that are only configurable via code, we'd have to support them in the future too (or at least attempt to), with potentially different build systems.

This same rationale is why we don't support loader syntax in imports. Loader imports are webpack-specific and wouldn't work in other build environments.

**Comment by johnpapa** [comment]
I hear you. Rough call. 

But - since webpack syntax does work today and it is also supported in vue and react, i be people just assume it will work. And that it won’t suddenly stop working. That’s more of my concern.  Preventing people from a sudden failure in the future.

**Comment by mgechev** [comment]
I see your point. I'd suggest to keep this outside the documentation scope for now because we haven't seen many folks hit that edge case for now.
