### ISSUE TITLE
Unable to use singleton platform injector service shared by all applications on the page

### ISSUE THREAD

**Issue by saeed-ahmed** [angular/angular#35429]
# 🐞 bug report

### Affected Package

 Using angular 9.0.0 release version.

### Is this a regression?

 No

### Description Unable to create the singleton service and use across multiple angular elements on the same page when it is decorated as  **providedIn:platform**  

 

Please see the below image which summarizes the whole flow;

![image](https://user-images.githubusercontent.com/6238592/74475396-5dcbd100-4e75-11ea-8363-b13f428dd21b.png)

## 🔬 Minimal Reproduction

 

1-Create an angular library project which only have one angular service which uses **providedIn: 'platform'**. The service has two method getTitle and setTitle, which are just getter and setter for the service property named **title**.
2-Create a new angular element app and use the service created in step-1. Create a button(Set Title) in component and call the service's setTile method by passing the value "Setting title from element1".
3-Create another new angular element app and use the service created in step-1. Create a button (Get Title) in component and use the getTitle method of the service.
4-Create a new angular container app or in index.html which uses both angular elements created in step 2 & 3. And now press "Set Title" and then press "Get Title" buttons. 

## 🔥 Exception or Error
<pre>No<code>
</code></pre>

Expectation: As per documentation, there should be a single instance of the service should exists but two separate instances of the service are created for each element.
Pressing "Get Title" button should return "Setting title from element1" text, but it is returning blank.

Documentation Links:
https://next.angular.io/api/core/Injectable

https://dev.to/christiankohler/improved-dependeny-injection-with-the-new-providedin-scopes-any-and-platform-30bb

## 🌍  Your Environment

**Angular Version:**
<pre><code>

</code></pre>

**Anything else relevant?**

**Comment by saeed-ahmed** [comment]
Attachment contains:
1-Common service library angular project  (store-app)
2-Two angular elements apps (app3 & app4)
3- Main angular container (main-container-app)
[ProvidedInPlatform.zip](https://github.com/angular/angular/files/4201011/ProvidedInPlatform.zip)

**Comment by flash-me** [comment]
Heyo,

pretty much the case what I was expecting. 😄 <br> Your StoreModuleLibService Code is compiled both into App3 and App4 bundles. 

--> Each of them creates its own StoreMOduleLibService
Just have a look in the "main-es2015.js" bundles of each app.

![image](https://user-images.githubusercontent.com/5240450/74580231-142cd480-4fa2-11ea-9d79-e48902d0c786.png)

cheers
flash

**Comment by vkvarma** [comment]
@flash-me what is the better way to create single instance of the service across platform using platform provided in in v9 ? We are trying to get service shared between two elements ? please suggest if you have some better way to do ?

**Comment by saeed-ahmed** [comment]
@falsh-me Understand, it is creating two instances, the whole issue is around this. When use **providedIn:platform** in the service as per doc it should create a single instance, not the two, when use in a same app. 
Trying to use a shared service in two angular elements, and use those two elements in index.html/angular-app, the expectation is single instance of the service should be shared among two angular elements, which is not happening.

**Comment by flash-me** [comment]
@vkvarma @saeed-ahmed 

Good messages! Yep, there are better ways to accomplish this. Its even possible to share not only your custom code, but all of the complete angular runtime, which in turn means you just need to compile only your part and leave out everything else. This will lead to [pretty small bundle sizes](https://twitter.com/simsek_dev/status/1168163228574277639) 😎 

### Easy way
It's not very clear at first and the documentation indeed lacks about this, but all you need is to compile your "apps" as angular libraries, too and make use of the `umdId` and `umdModuleIds` properties of the [ng-packagr configuration](https://github.com/ng-packagr/ng-packagr/blob/master/src/ng-package.schema.json). 🤷‍♂ 

### Hard way
Modifying the [browser](https://github.com/angular/angular-cli/blob/master/packages/angular_devkit/build_angular/builders.json#L9) angular-cli builder of the [@angular-devkit/build-angular](https://github.com/angular/angular-cli/tree/master/packages/angular_devkit/build_angular) package. You can achieve this by [passing a transform object](https://github.com/angular/angular-cli/blob/master/packages/angular_devkit/build_angular/src/browser/index.ts#L227) with the according webpack configuration.

This is the result when I compile my angular elements:
![jLfYRmj4Ob](https://user-images.githubusercontent.com/5240450/74597169-91b41b80-505a-11ea-88cc-3e35907d5ba5.gif)

I'm still thinking about publishing all the tools that I have created in order to build performant & optimizied micro frontends with angular, but the community just f--- me up more and more, giving me a reason not to. These hints should be enough to find the right solution. [Hacking the renderer and injecting JS code that has been loaded from somewhere](https://github.com/angular/angular/issues/35328) must be far better anyway. :wink:

Cheers
flash :zap:

**Comment by vkvarma** [comment]
@flash-me very very thanks for your valuable suggestion We don't want to intercept the webpack bundling / build process if it hurts the natural flow of angular/webpack and it seems there is no official way to achieve the work we listed above .
We will definitely try this out with transformed object or making **custom builder** to achieve this.
@robwormald @manfredsteyer @IgorMinar any more suggestions .

**Comment by saeed-ahmed** [comment]
@pkozlowski-opensource  @AndrewKushnir any updates on this issue?

**Comment by flash-me** [comment]
Here you https://twitter.com/simsek_dev/status/1232700522655862784 

and boilerplate code https://github.com/flash-me/angular-micro-frontends

Sorry for stealing everyones show, but I like to keep things simple.

Have fun folks

Cheers 

flash :zap:

**Comment by vkvarma** [comment]
@flash-me thanks for your hard work really appreciated  . We will take a look and will get back to you.

**Comment by flash-me** [comment]
Unfortunately there are some issues, if the usage of angular material is intended. 
- [18652](https://github.com/angular/components/issues/18652)
- [18655](https://github.com/angular/components/issues/18655)
- [35765](https://github.com/angular/angular/issues/35765)

Workarounds are possible, though. Made a small script to create the bundle, if needed in case:
https://gist.github.com/flash-me/f6c01079db0c7830016127d46679b43d

cheers
flash :zap:

**Comment by hebronivy** [comment]
I had the same problem. providedIn: 'platform' not work when running two angualr app in the same page.Heap snapshot shows there are tow instance.The official documents are very confusing.

**Comment by flash-me** [comment]
All of the issues have been resolved. It is now possible without workarounds. 

Great job and thanks to @alan-agius4 and @devversion for taking their time!

cheers
flash ⚡️

**Comment by vkvarma** [comment]
@flash-me thanks for informing so it means the fix is now merged with latest version of angular 9 ?

**Comment by flash-me** [comment]
@vkvarma The issues I mentioned [here](https://github.com/angular/angular/issues/35429#issuecomment-593143473), yes.
They have been merged. (Angular 9.0.6 and ng-package 9.0.3)

If you are relating to the whole topic here created by @saeed-ahmed, then no, since this is not an issue imo.

cheers
flash :zap:

**Comment by saeed-ahmed** [comment]
@flash-me  you are right, the issue which I created didn't work for me in version Angular 9.0.6

**Comment by flash-me** [comment]
It is **not** an issue. If you compile your app with the `@angular-devkit/build-angular` builder, then webpack is used to bundle your application, which includes every dependency into the bundle. This is why you have redundant code for each angular element. 

This is different when you make use of the library compilation. Here, the `@angular-devkit/build-ng-packagr` will be used, which in turn will **exclude** every package and expects them to be available at runtime.

Thats how they are configured by default for the @angular-cli and **not an issue**. You can make the webpack exclude the dependencies when bundling your package, but for this you have to use third party packages or build your custom builder as I mentioned [here](https://github.com/angular/angular/issues/35429#issuecomment-586655547).

cheers
flash :zap:

**Comment by gkalpak** [comment]
This is essentially the same as #36028. Let's track this usecase in #36028, so we have a single point of reference.

**Comment by tettusud** [comment]
> All of the issues have been resolved. It is now possible without workarounds.
> 
> Great job and thanks to @alan-agius4 and @devversion for taking their time!
> 
> cheers
> flash ⚡️

flash thanks for detailed explanation, does this solve duplicate issue [36028](https://github.com/angular/angular/issues/36028)
