### ISSUE TITLE
angular 9 elements/webcomponents with formControlName fails to render

### ISSUE THREAD

**Issue by robjames** [angular/angular#35448]
# 🐞 bug report

### Affected Package

 The issue is caused by package @angular/....
Not sure

### Is this a regression?

Unclear. I could not reproduce on stackblitz, so I downloaded the source from statckblitz to run locally - the project wouldn't run as Stackblitz had some old versions of dependencies listed in the project (7) so I updated. It then ran, and the error is then reproducible.

### Description

 A clear and concise description of the problem...
I am trying to display a form within an angular element.
It is all working fine until I use `formControlName`. This stops rendering the page after that element (and angular is not running anything) there is no error shown in the console.
If I remove this attribute (or rename to `name`), it renders fine - but obviously the ReactiveFormsModule does not connect to the input field.

## 🔬 Minimal Reproduction

 
https://github.com/robjames/angularElementsFormControlName

## 🔥 Exception or Error
<pre><code>

There is no error shown
</code></pre>

## 🌍  Your Environment

**Angular Version:**
<pre><code>

Angular CLI: 9.0.2
Node: 10.16.0
OS: win32 x64

Angular: 9.0.1
... animations, common, compiler, compiler-cli, core, elements
... forms, language-service, platform-browser
... platform-browser-dynamic, router
Ivy Workspace: Yes

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.900.2
@angular-devkit/build-angular     0.900.2
@angular-devkit/build-optimizer   0.900.2
@angular-devkit/build-webpack     0.900.2
@angular-devkit/core              9.0.2
@angular-devkit/schematics        9.0.2
@angular/cli                      9.0.2
@ngtools/webpack                  9.0.2
@schematics/angular               9.0.2
@schematics/update                0.900.2
rxjs                              6.5.4
typescript                        3.7.5
webpack                           4.41.2
</code></pre>

**Anything else relevant?**

Currently using Chrome, but I have done the necessary work to make it compatible back to ie11

**Comment by gkalpak** [comment]
There are two parts to this problem:

1. The first one is that errors thrown inside the root module's constructor function are not surfaced to the user. This is tracked in #29211. Interestingly, updating the code to run after error handling has been properly set up would also address the second issue (see below), so any of the methods listed in https://github.com/angular/angular/issues/29211#issuecomment-637737111 should be viable work-arounds.

2. The second issue is that calling `customElements.define()` inside the root module's constructor function, will transitively try to bootstrap the Angular component syncronously and thus potentially before the root module has been fully initialized.
  - In Angular v9 and earlier, this seemed to have been a problem, because the code would try to inject dependencies into the component before `NgModuleRef`'s [_r3Injector][2] property was initialized, causing an error. 
  - In Angular v10, this seems to have been fixed (with both Ivy (the new compiler/renderer) and ViewEngine (the legacy compiler/renderer)).

Based on the fact that the second issue has been fixed in the latest Angular version (see above) and the first issue is tracked in #29211, I am going to close this. If you are still running into problems with the latest version, please open a new issue.

[1]: https://github.com/angular/angular/blob/88d68d2d216dba744dff7cc1ef93c8441d68c6a3/packages/core/src/render3/ng_module_ref.ts#L58-L66
[2]: https://github.com/angular/angular/blob/88d68d2d216dba744dff7cc1ef93c8441d68c6a3/packages/core/src/render3/ng_module_ref.ts#L34
