### ISSUE TITLE
Add support for custom search terms to Angular.io

### ISSUE THREAD

**Issue by aikidave** [angular/angular#35449]
# 📚 Docs or angular.io bug report

### Description
Sometimes, users request we add documentation that already exists on Angular.io. The issue is that the user is unable to find it. 

To help address this issue, we should support custom search terms. One possible way to do this is with a custom search tag:

{@searchTerms term 1, term 2, … }

## 🔬 Minimal Reproduction
n/a

### What's the affected URL?**
 All of https://angular.io/.

### Reproduction Steps**
n/a
### Expected vs Actual Behavior**
n/a

## 📷Screenshot
n/a

## 🔥 Exception or Error
n/a

### Browser info
n/a

### Anything else relevant?
no

**Comment by sonukapoor** [comment]
@aikidave I would be happy to help with this feature implementation.

**Comment by aikidave** [comment]
Awesome. Can you collaborate with @petebacondarwin? I believe he is looking into this also.

**Comment by sonukapoor** [comment]
Sure @aikidave. 

@petebacondarwin, please let me know how to proceed with this feature request. If needed, I am available on gitter to discuss offline.

**Comment by petebacondarwin** [comment]
@sonukapoor - that would be great. I am not working this week. But you can start to look into it. I foresee three or four parts to the implementation:

1) Define the new inline jsdoc tag `{@searchTerms "phrase one" "phrase two" term3}`, where I think we should parse the tag content so that we can have phrases in quotes.
2) Create a dgeni processor that runs after the inline jsdoc tag extraction and before the keyword extraction, which will attach these terms to a property (e.g. `doc.searchTerms`) on the document. (It might be that this can be done inside the inline tag handler.
3) Update the keyword extraction processor so that it includes these search terms in the object that will be sent to the search indexing engine.
4) Update the lumr search engine so that it can use these new search terms and prioritise them over other searches (similar to what we do for title search terms now).

The goal would be that if you use one of these terms in a search query on the site, the related document will be at the top of the results list.

I'll catch up with you on Monday next week to see how it is going.

**Comment by sonukapoor** [comment]
Thanks a lot for the detailed instructions @petebacondarwin. 

I will take a look and let you know if I have any questions. 

@aikidave can you please assign this issue to myself?

**Comment by aikidave** [comment]
Done! Thanks to both of you for the help. Let me know if I can assist in any way.

**Comment by sonukapoor** [comment]
@aikidave draft PR created for @petebacondarwin to review next week.
