### ISSUE TITLE
style hostbinding doesn't work the way it was in Ivy

### ISSUE THREAD

**Issue by maxisam** [angular/angular#35458]
# 🐞 bug report
Before Ivy
this following code works
```js
  @HostBinding("style")
  style: SafeStyle = this.sanitizer.bypassSecurityTrustStyle(
    "background: green; color: white; display: block;"
  );
```
https://stackblitz.com/edit/angular-oqwzqb?file=src%2Fapp%2Fapp.component.html

After Ivy, it doesn't.  

### Is this a regression?
No

**Comment by kara** [comment]
Closing this issue as it does not follow the issue template. Please file a new issue that follows the template, which gives the team the information needed to investigate.

Specifically, it would help if you could clarify the expected behavior vs actual behavior (ie. what you mean when you say it "doesn't work".

**Comment by maxisam** [comment]
@kara sorry, I was a bit hurry on Friday, but I also wanted to push this out asap so it might spare other people time for this one. ( I imaged people would spent the weekend to play with the new version.)  I guess my example was a bit unclear on the issue since I can't figured out how to set enableIvy as true on stackblitz.  Anyway, here is the new issue #35476. I have updated all my open source libraries and one of my application for production to Ivy. This is the only issue I got so far. Good work on IVY!
