### ISSUE TITLE
docs: add missing stackblitz/download links and standardize across docset

### ISSUE THREAD

**Issue by kapunahelewong** [angular/angular#35459]
# 📚 Docs or angular.io bug report

### Description

Currently, we have some docs that use code samples from the aio example apps, but there's no way for a reader to get to the actual example to see it in action, that is a stackblitz or download link. As a developer, I need to see a feature working in order to process, understand, and build on what I've just read.

### What's the affected URL?**

I've noticed it in:

- https://angular.io/guide/dependency-injection-provider
- https://angular.io/guide/architecture-components
- https://angular.io/guide/architecture-services
- Each page of the Getting Started (reader should be able to jump in as if having done all the steps prior to any step or download the whole completed app).
- TOH has these links, but only at the end, not the beginning for the last step. Nicer UX if you're ushered through and know you're taken care of. Step 6 has both.)
- https://angular.io/guide/elements (It's there but in the middle of the page and the formatting is not standard. Should be at top, too.)
- https://angular.io/guide/forms-overview (Has inline code, too, which should be refactored to be code samples because we need to know it compiles.)
- The one in https://angular.io/guide/forms needs to be fixed as it reads "You can run the live example / download example in Stackblitz and download the code from there." You can download it from the "download example" link without having to go to StackBlitz.
- Again, one at the end: https://angular.io/guide/form-validation If it's at the beginning too, the reader can follow along and experiment while working through the guide, which emphasizes multiple modes of learning (kinetic/active visual + passive visual).
- https://angular.io/guide/bootstrapping
- https://angular.io/guide/transition-and-triggers
- https://angular.io/guide/complex-animation-sequences
- https://angular.io/guide/reusable-animations
- https://angular.io/guide/route-animations
- Needs to be standardized if downloading is an option: https://angular.io/guide/i18n
- Link is too far down, should be at beginning too: https://angular.io/guide/accessibility
- All of the service worker docs are missing the download/stackblitz link https://angular.io/guide/service-worker-communications
- Universal/server side rendering: https://angular.io/guide/universal
- While not vital to understanding info, we might want to have a download link in the upgrade guide so that readers can practice on a sample app, before trying it on a real app, especially since we have code snippets from an example: https://angular.io/guide/upgrade
- Schematics has a zip? https://angular.io/guide/schematics-for-libraries (zip link)We might want to make it available here too: https://angular.io/guide/schematics-authoring
- We should say where this source code link is taking people: https://angular.io/guide/cli-builder
- https://angular.io/guide/web-worker
- It'd be nice to have an example for Building and Serving as all that code is inline https://angular.io/guide/build

### Reproduction Steps**

Go to most of the above pages and look for download link. When it's there, its placement isn't obvious or is non-standard. A number of them are missing.

### Expected vs Actual Behavior**

When I'm learning a concept (or troubleshooting something in the docs) I rely on a working example so that I can see it in action. This gives the code snippets context and for going straight to a particular point, it speeds up the process so you don't have to read through the doc to build the app to the place in question.

## 🔥 Exception or Error
<pre><code>

</code></pre>

**Comment by gkalpak** [comment]
I generally agree with all you said :100:

I just want to point out that some example apps are not in a "shareable" state (i.e. this is not just a matter of adding the `<live-example>` tag in all guides). Some example apps need work in order to be helpful as standalone example apps. (Fortunately, that only applies to few of them, but we should check case-by-case when adding `<live-example>` tags.)

**Comment by kapunahelewong** [comment]
Yes, this is true! Thank you, @gkalpak, for making sure it is pointed out. For whoever picks it up (if it's not me! 😁), the `<live-example>` tags can't just be added to all docs. When we go through, we'll need to look at a case by case basis to determine the scope as some will be a greater level of effort than others. We also need to make sure that it makes sense in the context of each doc and check that all the included `<code-example>` tags still make sense. This would be best done in a number of smaller PRs rather than one big one.

**Comment by ajitsinghkaler** [comment]
@kapunahelewong @gkalpak can I work on this

**Comment by kapunahelewong** [comment]
Wow, sure, @ajitsinghkaler! It may be helpful to do them in small PRs, one doc at a time. I imagine that this issue would take one PR or more for each of the points above. Does that help? Thank you!

**Comment by sonukapoor** [comment]
@ajitsinghkaler Just wondering if you are working on this. If not, I can help out.

**Comment by sonukapoor** [comment]
@kapunahelewong The first link is missing the `s` in the end. It should be `https://angular.io/guide/dependency-injection-providers`

**Comment by ajitsinghkaler** [comment]
I'm on a holiday for 10 days and I'll only start working on it after that you can start working on this. No problem

**Comment by sonukapoor** [comment]
@ajitsinghkaler Sounds good. I can create a few PRs for it and we can probably split the work when you are back.

**Comment by sonukapoor** [comment]
@kapunahelewong / @gkalpak How about taking this one step further and we display a download icon next to the pencil icon in the top right corner of the document. 

Something like this:

![image](https://user-images.githubusercontent.com/59734/76612229-3c044f00-64f2-11ea-941c-f901798744de.png)

This will be cleaner and help us to avoid creating new content sections that basically would just say "Download accompanying code from here". 

WDYT?

**Comment by gkalpak** [comment]
There is not necessarily a 1-to-1 relations between guides and archived examples, so I believe having such a link is the wrong abstraction (that will make things more complicated for docs authors.

**Comment by sonukapoor** [comment]
I have started on this and to keep track of the files that have changed, I have modified the original list from @kapunahelewong to a to-do list. @ajitsinghkaler, if you work on this, please mark the task when you start on it. Thanks 👍 

- [ ]  https://angular.io/guide/dependency-injection-provider
- [ ]  https://angular.io/guide/architecture-components
- [ ]  https://angular.io/guide/architecture-services
- [ ]  Each page of the Getting Started (the reader should be able to jump in as if having done all the steps prior to any step or download the whole completed app).
- [ ]  TOH has these links, but only at the end, not the beginning for the last step. Nicer UX if you're ushered through and know you're taken care of. Step 6 has both.)
- [ ]  https://angular.io/guide/elements (It's there but in the middle of the page and the formatting is not standard. Should be at the top, too.)
- [ ]  https://angular.io/guide/forms-overview (Has inline code, too, which should be refactored to be code samples because we need to know it compiles.)
- [ ]  The one in https://angular.io/guide/forms needs to be fixed as it reads "You can run the live example / download example in Stackblitz and download the code from there." You can download it from the "download example" link without having to go to StackBlitz.
- [ ]  Again, one at the end: https://angular.io/guide/form-validation If it's at the beginning too, the reader can follow along and experiment while working through the guide, which emphasizes multiple modes of learning (kinetic/active visual + passive visual).
- [ ]  https://angular.io/guide/bootstrapping
- [ ]  https://angular.io/guide/transition-and-triggers
- [ ]  https://angular.io/guide/complex-animation-sequences
- [ ]  https://angular.io/guide/reusable-animations
- [ ]  https://angular.io/guide/route-animations
- [ ]  Needs to be standardized if downloading is an option: https://angular.io/guide/i18n
- [ ]  Link is too far down, should be at the beginning too: https://angular.io/guide/accessibility
- [ ]  All of the service worker docs are missing the download/stackblitz link https://angular.io/guide/service-worker-communications
- [ ]  Universal/server side rendering: https://angular.io/guide/universal
- [ ]  While not vital to understanding info, we might want to have a download link in the upgrade guide so that readers can practice on a sample app, before trying it on a real app, especially since we have code snippets from an example: https://angular.io/guide/upgrade
- [ ]  Schematics has a zip? https://angular.io/guide/schematics-for-libraries (zip link)We might want to make it available here too: https://angular.io/guide/schematics-authoring
- [ ]  We should say where this source code link is taking people: https://angular.io/guide/cli-builder
- [ ]  https://angular.io/guide/web-worker
- [ ]  It'd be nice to have an example for Building and Serving as all that code is inline https://angular.io/guide/build

**Comment by ajitsinghkaler** [comment]
@sonukapoor I'm taking the 5th and the 6th one

**Comment by ajitsinghkaler** [comment]
@sonukapoor @kapunahelewong how is it done I did not find any <live-example> tags in the files that @sonukapoor has not tucked do we have to create the zip files too.

**Comment by sonukapoor** [comment]
@ajitsinghkaler In some of the docs, you will find sections allowing the user to download the stackblitz example. These sections need to be standardized and moved to somewhere at the top. 

The docs that don't have these will most likely have hard-coded examples, that need to be converted at some point to proper examples. 

For the files that have the download sections,  we will need to move them to the top. You can look at some of my PRs to see how I did that.

**Comment by ajitsinghkaler** [comment]
@kapunahelewong @sonukapoor 

 https://angular.io/guide/dependency-injection-providers
https://angular.io/guide/dependency-injection

Share the example do we need to put same link everywhere or do we need to make a separate example for each one. means put different example codes in different stackblitz.

**Comment by sonukapoor** [comment]
@ajitsinghkaler The idea for this issue is to use the example from within the doc and place it somewhere near the top to make it easily accessible. 

- If you see a guide where an example is mentioned but not provided, then you can always create a new issue and create a PR against that. 
- If you find a guide where an example is missing but found one from another guide, then you can link it to the guide as well.

Let me know if that answers your question.

**Comment by kapunahelewong** [comment]
Yes, just as @sonukapoor says, @ajitsinghkaler. And sometimes there isn't one. It's ok to skip those because we still have to figure out how we want to handle those and some of them might require planning and discussion throughout to get them right (that is, those are way more work 🙂).

**Comment by kapunahelewong** [comment]
Status: giant team effort still under way. Thank you, @ajitsinghkaler and @sonukapoor!! 🏆

**Comment by alxhub** [comment]
This is fixed with angular.dev!
