### ISSUE TITLE
Router State Tree drops Params returned by matcher function when internal router of lazy-loaded module takes over

### ISSUE THREAD

**Issue by SachinShekhar** [angular/angular#35471]
# 🐞 bug report

### Affected Package

 The issue is caused by package @angular/router

### Is this a regression?

 No.

### Description

I lazy-load modules based on `matcher` pattern. When lazy-loaded module's internal routing module takes over, router state tree drops the `params` set by `matcher` function.

## 🔬 Minimal Reproduction

 https://github.com/SachinShekhar/angular-matcher-params-bug

I've added proper router links and router state on the homepage so that you can visualize the bug clearly.

## 🔥 Exception or Error

No exception or error. It just happens.

## 🌍  Your Environment

**Angular Version:**
<pre><code>

Angular CLI: 9.0.2
Node: 12.6.0
OS: win32 x64

Angular: 9.0.1
... animations, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router
Ivy Workspace: Yes

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.900.2
@angular-devkit/build-angular     0.900.2
@angular-devkit/build-optimizer   0.900.2
@angular-devkit/build-webpack     0.900.2
@angular-devkit/core              9.0.2
@angular-devkit/schematics        9.0.2
@angular/cli                      9.0.2
@ngtools/webpack                  9.0.2
@schematics/angular               9.0.2
@schematics/update                0.900.2
rxjs                              6.5.4
typescript                        3.7.5
webpack                           4.41.2

</code></pre>

**Anything else relevant?**

No.

**Comment by atscott** [comment]
Hi @SachinShekhar, thanks for the report and github demo. Can you please list steps to reproduce the issue and what you expect vs what is actually happening?

**Comment by SachinShekhar** [comment]
@atscott Look at the matchers here: https://github.com/SachinShekhar/angular-matcher-params-bug/blob/master/src/app/app-routing.module.ts

```typescript
{
    matcher: (url: UrlSegment[]) =>
      url.length > 0 && url[0].path.startsWith('@')
        ? {
            consumed: [url[0]], // Passing the first segment to keep it from hijacking internal router of the lazy-loaded module
            posParams: {
              userId: new UrlSegment(url[0].path.substr(1), url[0].parameters)
            }
          }
        : null,
    loadChildren: () => import('./user/user.module').then(m => m.UserModule)
  }
```
I have also returned `posParams` (having `userId` param) from the matcher function.

I expect `userId: angular` param to always remain in `activatedRoute` state tree if I visit `@angular/xyz/123`. But, what is happening is that this param remains in the tree only if I visit `@angular`. Visiting `@angular/xyz` and `@angular/xyz/123` both drops this param from the tree.

This makes working with `matcher` + `modules` impractical. Serve the app to see everything I said in action.

**Comment by atscott** [comment]
Hi @SachinShekhar, this doesn't appear to be an issue with lazy loaded modules - you can convert the routes to be regular 'children' instead and will see the same result. Additionally, this appears to be working as intended on the router side - what you are observing is a result of how `ss-ngrx-router-store-state` builds the state. The [searchRouterStateTree](https://github.com/SachinShekhar/ss-ngrx-router-store/blob/master/projects/ss-ngrx-router-store/src/lib/ss-ngrx-router-store.serializer.ts#L25-L40) code specifically only includes params on routes that have no children. If you put a breakpoint in the `serialize` method there, you can see that the `userId` param is available on the route which activates the `UserComponent`. Because that route has a child, the `userId` is not added to the return object.

If you still feel there is an issue, please provide further details in a new issue.
