### ISSUE TITLE
debugger;  // Left intentionally for better debugger experience.

### ISSUE THREAD

**Issue by RomanHubyak** [angular/angular#35470]
Please, remove this debugger.

https://github.com/angular/angular/blob/9bd959076730c4e22ceadda73694198b4f01b9e0/packages/core/src/render3/errors.ts#L59

**Comment by JoostK** [comment]
Could you elaborate on why you want it removed?

**Comment by elgerm** [comment]
Because there should **never** be debugger statements in production code. I can't believe how this got into a production build. 

[](http://jslint.fantasy.codes/all-debugger-statements-should-be-removed)

[](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/debugger)

**Comment by Airblader** [comment]
It's not in production code. `ExpressionChangedAfterItHasBeenCheckedError is only thrown in development builds as it requires a second run of the CD.

**Comment by elgerm** [comment]
Three things on this: 

1. Angular 9 ships with a debugger statement in it. You can argue what we mean by production code but I think that's a production release. Debugger statements don't belong there.

2. So you mean the debugger statement is still in the code, but only because ExpressionChangedAfterItHasBeenCheckedError is never thrown, the debugger statement won't hit?
Or: ng build --prod removes all debugger statements altogether? I'm asking because in rc9, this statement was hit on a production build with developer tools open.

3. It's not a good 'developer experience'. This debugger statement always hits when you least need it, it would be much better to just log the error to the console. Propname is always 'undefined' and there's a bunch of boolean values to look into. I don't see the point.

To be clear: I really appreciate your work, and I don't mean to troll you guys on this. But to me it this solution looks more like a novice programming mistake.

**Comment by Airblader** [comment]
I don't disagree, I too find it an odd decision. Debugging into internals of Angular is not helpful and if it was the stack trace allows setting the breakpoint just as well.

**Comment by montella1507** [comment]
debugger;  in code... whyyyyyy , Please remove that.

**Comment by Semchik** [comment]
Hi!
ExpressionChangedAfterItHasBeenCheckedError does not break application logic, and could be in some old code or somewhere. And it's very annoying to get unexpectedly stopped by debugger when you just do something in your app.
Please, remove it and let it to us to decide, where we want a breakpoint) :)
Best wishes!

**Comment by mhevery** [comment]
I am really confused by this request.

1. The `debugger` statement is not present in production code because in production code when `ngDevMode=false` it is tree shaken away. So if you do a prod build there is no `debugger` left.
2. The `ExpressionChangedAfterItHasBeenCheckedError` is only thrown in non-prod build.
3. The `debugger` statement is there only if an exception is thrown which is fatal, and we consider `ExpressionChangedAfterItHasBeenCheckedError` fatal. But it sounds like in your application you have whole bunch of `ExpressionChangedAfterItHasBeenCheckedError` which you just ignore and consider non-fatal? That does not seem like a good practice.

Am I understanding the request right?

**Comment by mhevery** [comment]
> * ng build --prod removes all debugger statements altogether? I'm asking because in rc9, this statement was hit on a production build with developer tools open.

Yes `ng build --prod` should remove it. If it does not that is a bug and should be fixed.

**Comment by montella1507** [comment]
@mhevery  problem may be not in your code, it may be even not-resolvable - for example NGPrime is full of these errors ...   Who wants to break debugger every time? Let developer decide... 

You may find "debugger;" in code ont he list of the worst practices, dont you agree?

**Comment by mhevery** [comment]
Can you post some of the stack traces of these errors?

**Comment by Airblader** [comment]
> and we consider ExpressionChangedAfterItHasBeenCheckedError fatal

Fatal errors should probably cause the application to "exit", though, and also shouldn't be ignored in prod builds then. Otherwise they're not really fatal. I would have to agree that in my experience not taking these errors seriously is a common practice (and no, I don't like that either). 

I'm also not yet clear on how the debugger statement actually helps the developer. It just breakpoints into Angular internals, which isn't helpful. Anything the developer can see at that breakpoint could also trivially just be part of the error message. Ideally the error should say which component, which binding, which expression and from/to which value. 

When the error is thrown I have a trace in my console and can easily set that debugger statement anyway should I for some reason care about it.

**Comment by mhevery** [comment]
> I'm also not yet clear on how the debugger statement actually helps the developer. It just breakpoints into Angular internals, which isn't helpful. Anything the developer can see at that breakpoint could also trivially just be part of the error message. Ideally the error should say which component, which binding, which expression and from/to which value.

The error is in angular internals but if you go up the stack trace you will have your application. This will allow you to see what expression was being executed when the error happened. Not only can you see the expression you would be able to examine the values of the expression .Having stack trace is not as good as having break point because with breakpoint you can examine variable state and restart a stack frame under different conditions.

**Comment by RomanHubyak** [comment]
One more... This is a nightmare...

https://github.com/angular/angular/blob/ee8b8f52aa63f18e90534e4efed366fdf6987720/packages/core/src/util/assert.ts#L97

**Comment by elgerm** [comment]
> 3\. But it sounds like in your application you have whole bunch of `ExpressionChangedAfterItHasBeenCheckedError` which you just ignore and consider non-fatal? That does not seem like a good practice.

Putting debugger statements in code and release it is the ‘not good practice’ here. I don’t understand why we even have to discuss this. There is another way and that is logging to the console, that way you can easily put a breakpoint if you are ready to debug. This debugger statement is also a precedent for more in the angular code. Also, if you use third party libraries you don’t always have control over the so called ‘fatal’ error which will lead you to the angular internals again and again. Yes, great developer experience!

**Comment by Airblader** [comment]
Another option would be to make it conditional on a flag. For two debugger statements that isn't worth it, so the question (@mhevery) is whether Angular wants to make it a pattern to introduce such statements. Because then it might be worth doing so.

My other point would still be: if Angular considers these fatal errors, they should be *fatal*. A fatal error aborts the program. But then this change should be introduced carefully and with upfront information.

**Comment by montella1507** [comment]
+ it will freeze your Console for 8sec, because of debugger;  - needs to show X MB javascript in console.

**Comment by Splaktar** [comment]
I like the idea of having a flag to enable/disable this new debugger behavior.

As mentioned in https://github.com/angular/angular/issues/35470#issuecomment-588379296, there are some benefits to this approach, but they aren't well defined in the current `// Left intentionally for better debugger experience.` code comment and the comment doesn't point to a documentation page/guide that helps developers learn how to fully take advantage of this new debugging experience.

If such a debugging guide existed and was linked via the debugger statement comment, it could provide a better developer experience.

For the `ExpressionChangedAfterChecked` errors specifically, it would be beneficial to have a full guide in the docs to explain various use cases where it can occur and how to solve it. So far we've tried to comment on it in GitHub and various blog posts exist, but it's still a big problem that many Angular developers don't have the capability/knowledge to solve.

**Comment by Adelaiten** [comment]
I know it's not solution, but till it's not deleted by angular developers, you can always delete it yourself in your project.
/node_modules/@angular/core/esm2015/src/render3/error.js

![image](https://user-images.githubusercontent.com/38323826/75135394-b145e680-56e1-11ea-84f0-d0dd248f93bc.png)

**Comment by mhevery** [comment]
I would like to explore two ides:
1. Could we have a flag which this would disable.
2. Is this issue for `ExpressionChangedAfterItHasBeenCheckedError` only? Or do people see this issue in other places. I think it would be reasonable to drop `ExpressionChangedAfterItHasBeenCheckedError` from the `debugger` case since people point out correctly that it is not really fatal.

**Comment by Ledzz** [comment]
I'm using `@angular/cdk-experimental` for dialogs with custom DialogContainer. And every time when I open a dialog, debugger pops out. I know that it's my fault or someone's who wrote dialogs', but its very annoying

**Comment by FDIM** [comment]
This is definitely an interesting choice. I do agree that this error/warning needs something to attract attention so that it would be looked at, but this may be too much. Especially if it originates in a library.

Could we maybe in the future opt-in (or out) and make this error critical somehow so that app would break?

For the time being I'll be monkey patching in post install script and removing them :) (and address the actual issues a bit later)

**Comment by mhevery** [comment]
I would be very supportive if we could make it more opt-in/out kind of mode. I have this on my TODO list, but if someone wants to take a crack at it feel free.

**Comment by LosD** [comment]
> I would like to explore two ideas:
> 
> 1. Could we have a flag which this would disable.
> 2. Is this issue for `ExpressionChangedAfterItHasBeenCheckedError` only? Or do people see this issue in other places. I think it would be reasonable to drop `ExpressionChangedAfterItHasBeenCheckedError` from the `debugger` case since people point out correctly that it is not really fatal.

It needs to die in a fire. And it needs to die in every. single. place. You should never EVER be ripped into the debugger, even when testing a development build. If someone wants to be dropped into the debugger, they can easily add breakpoints, so to me, a flag is rather useless.
