### ISSUE TITLE
Cannot attach animation trigger using @HostBinding - renderer is undefined

### ISSUE THREAD

**Issue by greyskulll** [angular/angular#35501]
# 🐞 bug report

### Affected Package

angular/core ?
Exactly similar to this issue here - https://github.com/angular/angular/issues/35342, however i am able to reproduce it with Angular - 9.0.1

### Is this a regression?

Yes, works as expected in Angular 8.x

### Description

Using the `@HostBinding` decorator to attach animation triggers to the host element does not work.

## 🔬 Minimal Reproduction

1) Clone this repo https://github.com/greyskulll/angular-animation-directive-hostbinding-issue
2) `ng serve` and check the browser console

In short, using `@HostBinding('@<animation trigger name>')` fails

## 🔥 Exception or Error
In Chrome
<pre><code>
core.js:5845 ERROR TypeError: Cannot read property 'listen' of undefined
    at isProceduralRenderer (core.js:4338)
    at elementPropertyInternal (core.js:12342)
    at Module.ɵɵupdateSyntheticHostBinding (core.js:25196)
    at SmoothHeightChangeDirective_HostBindings (uik-smooth-height-change.directive.ts:6)
    at setHostBindingsByExecutingExpandoInstructions (core.js:11385)
    at refreshView (core.js:11752)
    at refreshComponent (core.js:13145)
    at refreshChildComponents (core.js:11436)
    at refreshView (core.js:11757)
    at renderComponentOrTemplate (core.js:11831)
</code></pre>

In Firefox
<pre><code>
ERROR TypeError: "renderer is undefined"
    Angular 3
        isProceduralRenderer
        elementPropertyInternal
        updateSyntheticHostBinding
</code></pre>

## 🌍  Your Environment

**Angular Version:**
<pre><code>

     _                      _                 ____ _     ___
    / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
   / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
  / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
 /_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
                |___/

Angular CLI: 9.0.2
Node: 12.14.1
OS: darwin x64

Angular: 9.0.1
... animations, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router
Ivy Workspace: Yes

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.900.2
@angular-devkit/build-angular     0.900.2
@angular-devkit/build-optimizer   0.900.2
@angular-devkit/build-webpack     0.900.2
@angular-devkit/core              9.0.2
@angular-devkit/schematics        9.0.2
@angular/cli                      9.0.2
@ngtools/webpack                  9.0.2
@schematics/angular               9.0.2
@schematics/update                0.900.2
rxjs                              6.5.4
typescript                        3.7.5
webpack                           4.41.2

</code></pre>

**Anything else relevant?**
Was working as expected prior to IVY.

**Comment by kara** [comment]
@greyskulll The fix for #35342 should become available in `9.0.2` (it just missed the `9.0.1` release). When it comes out this week, can you try again with that version to see if you still have an issue?

**Comment by AndrewKushnir** [comment]
Hi @greyskulll, thanks for reporting the issue.

We performed additional investigation and found out the problem was related to the fact that `@HostBinding` with animation property was used on a Directive (this was not handled correctly in Ivy).

I've created a [PR with proposed fix](https://github.com/angular/angular/pull/35568). PR still requires review and the final implementation might change, but I'd like to ask if you could test your app with the changes from that PR to make sure the fix covers the case that you have in the app and everything works as expected. You can follow an instruction in [this document on how to use PR artifacts](https://github.com/angular/angular/blob/master/docs/DEVELOPER.md#archives-for-each-package). An archive with updated `@angular/core` package that contains changes from the PR is available [here](https://629519-24195339-gh.circle-artifacts.com/0/angular/core-pr35568-57c98b670f.tgz) (please make sure you update other `@angular` packages to `9.0.2` to avoid version conflicts). **Note**: the mentioned archive with updated `@angular/core` package is for **testing purposes only** and not suitable for production usage (that archive will be removed once PR is merged to master or closed).

Thank you.

**Comment by greyskulll** [comment]
Hi @AndrewKushnir , thanks for the quick PR !

I have verified the changes with the provided `@angular/core` artifact.
Everything is working as expected. :)

**Comment by AndrewKushnir** [comment]
Thanks for the update @greyskulll. We'll follow our regular review/testing procedures to land PR #35568 and I will keep this thread updated. Thank you.
