### ISSUE TITLE
ERROR in Failed to resolve styles[0] to a string

### ISSUE THREAD

**Issue by nageshdudam** [angular/angular#35523]
Hello Team,

I am using angular 9.0.1 and stuck at below error...

**ERROR in Failed to resolve styles[0] to a string**

Earlier I had upgraded to version 8 successfully.....but now i am trying to upgrade to version 9 and found to be stuck at above error.

There are no proper pointers available out there to fix it.

Please help to resolve this...!!!!

**Comment by ericmartinezr** [comment]
Dup of https://github.com/angular/angular/issues/35521 and https://github.com/angular/angular/issues/34389

**Comment by JoostK** [comment]
The error will properly point to the culprit once #35244 has landed. Otherwise, this issue does not follow the issue template and valuable information to diagnose is missing, so I'll close this issue. If you do have additional information feel free to open a new issue and providing the information as requested in the issue template.
