### ISSUE TITLE
Child injector created by Injector.create() should be able to provide dependencies needed by parent

### ISSUE THREAD

**Issue by Maximaximum** [angular/angular#35548]
# 🚀 feature request

### Relevant Package
This feature request is for @angular/core

### Description
*Please see https://stackblitz.com/edit/angular-providing-dependency-in-child-injector for the demo app.*

It would be great to be able to dynamically create service instances by providing their dependency values at arbitrary moments during the lifetime of an application.

I thought it should be a pretty common use case for the Angular DI system. I'd like to register a provider for a service (`Service2` in the demo app) declaratively at compile time. This service would have a dependency (`SERVICE2_MODE`) that doesn't have a provider registered at compile time.

At a certain moment during the application runtime I have a value for that missing dependency (`SERVICE2_MODE`) and now I need to instantiate the service (`Service2`) using that specific value.

I would expect that Angular supports a possibility to do this by manually creating a child injector for the root injector, giving the child injector a provider for `SERVICE2_MODE`, and then calling `childInjector.get(Service2)`. However, this does not work, because the `Service2` provider is registered at the root injector, and when the root injector tries to instantiate it, it is unaware that the child injector has a provider for that dependency.

### Describe the solution you'd like
It would make sense if each dependency provider lookup would go through the full injector hierarchy, starting from the `childInjector`, until it reaches the null injector. Currently, if a provider is not registered at `childInjector`, the lookup continues at the parent injector, but the dependencies for that provider are never tried to be resolved at the `childInjector` level.

### Describe alternatives you've considered
Currently in our production app, we simply don't use Angular DI for such cases. `Service1` and `Service2` are not decorated with `@Injectable()` and are manually instantiated inside `Service1FactoryService`.

But this means: tight coupling, inability to properly test Service1FactoryService, inability to handle complex dependency hierarchies.

**Comment by Maximaximum** [comment]
Note: an alternative solution might be to allow to get an array of registered providers. Then, the childInjector could be created this way (effectively by cloning the original injector:
```typescript
    Injector.create({
      providers: [
        ...this.injector.providers
        { provide: SERVICE2_MODE, useValue: mode }
      ]
    });
```

**Comment by mlc-mlapis** [comment]
@Maximaximum Like:
```
private createInjector(injections: Map<Type<any>, any>, _injector: Injector) {
		const tokens = new WeakMap();
		if (injections) {
			for (const [type, ref] of injections) {
				tokens.set(type, ref);
			}
		}
		return new PortalInjector(_injector, tokens);
	}
```

**Comment by Maximaximum** [comment]
@mlc-mlapis what is a `PortalInjector`? Where is it defined?

**Comment by mlc-mlapis** [comment]
@Maximaximum CDK

**Comment by mlc-mlapis** [comment]
@Maximaximum `import {PortalInjector, ComponentPortal} from '@angular/cdk/portal';`

**Comment by Maximaximum** [comment]
@mlc-mlapis We're not using angular material or cdk in our project. We could include it though, it's not a huge deal. But I guess it's something different from what we need? 

The docs for the `PortalInjector` say it's a *Custom injector to be used when providing custom injection tokens to components inside a portal.*. But the required functionality actually has nothing to do with components. We need to use it in a service, it has nothing to do specifically with components or UI at all.

**Comment by mlc-mlapis** [comment]
@Maximaximum I may don't understand exactly what did you mean previously. But from the `Injector` point of view: The injector is still injector, it doesn't matter if you use it in a component or a service.

**Comment by flash-me** [comment]
> I thought it should be a pretty common use case for the Angular DI system. I'd like to register a provider for a service (`Service2` in the demo app) declaratively at compile time. This service would have a dependency (`SERVICE2_MODE`) that doesn't have a provider registered at compile time.
> 
> At a certain moment during the application runtime I have a value for that missing dependency (`SERVICE2_MODE`) and now I need to instantiate the service (`Service2`) using that specific value.
> 
> I would expect that Angular supports a possibility to do this by manually creating a child injector for the root injector, giving the child injector a provider for `SERVICE2_MODE`, and then calling `childInjector.get(Service2)`. However, this does not work, because the `Service2` provider is registered at the root injector, and when the root injector tries to instantiate it, it is unaware that the child injector has a provider for that dependency

This works. Just don't provide your service on the root Injector.

**Comment by flash-me** [comment]
[Stackblitz example](https://stackblitz.com/edit/angular-pjrlzz). You're welcome.

Cheers
flash :zap:

**Comment by mlc-mlapis** [comment]
@Maximaximum If you meant the possibility to add a new singleton service in run-time, then there is still the possibility to use a lazily-loaded module and define a new service (with `providedIn: 'root'`) inside in it. And if this service is not linked in any way to the eagerly loaded part of the app, then it remains as a part of that lazily-loaded module. If the module is loaded and instantiated later, the service is instantiated as a singleton. It means as a part of the root injector, and not as a part of the lazily-loaded module.

**Comment by mlc-mlapis** [comment]
@flash-me `ReflectiveInjector` has been DEPRECATED since Angular 5 and will be removed in Angular 10.

https://angular.io/api/core/ReflectiveInjector#reflectiveinjector
https://github.com/angular/angular/blob/58f10026c4d1d55a96f517ee721ac694602a34c4/aio/content/guide/deprecations.md

**Comment by flash-me** [comment]
@mlc-mlapis Yeah, my fault. Fixed it to **Injector.create**. Thx for mentioning. Works as same as before. 

> If you meant the idea to add a new singleton service in run-time, then there is still the possibility to use a lazily-loaded module and define a new service (with providedIn: 'root') inside in it.

You may *either* use the `providedIn` way (since anguar v6) **OR** provide the service through an `NgModule`. Using both is not necessary. In fact, there is a good reason, why the newer `provdedIn` property was introduced.

> And if this service is not linked to the eagerly loaded part of the app in any way, then it remains as a part of that lazily-loaded module. If the module is loaded and instantiated later, the service is instantiated as a singleton

Mainly because of this. If you choose the `NgModule` syntax, your service will remain in your bundle, no matter if it is used by your app or not, because at bundle-time there will be an import statement to the service by your `NgModule`, so it can't be tree-shaked through the bundler. 

By using the `providedIn` syntax you avoid the import reference to your service and it can be tree-shaked. Unless you actually inject and use it somewhere. Typical use case for this are libraries that come with plethora of services from which you only use just a few --> anything else won't land in your bundle.

We still have both possibilites, because they  are covering different use cases. Given that, using the `providedIn` syntax with the purpose of dynamically injecting it at runtime could end with the service itself already been tree-shaken away from the bundle. e.g. If you do not use the class token but a string which the bundler cannot link to the service.

cheers
flash :zap:

**Comment by mlc-mlapis** [comment]
@flash-me Yep. Thanks. You added more explanation info. What I wanted to mainly express, was the fact, that using `providedIn: 'root'` syntax inside lazily-loaded modules it's possible to reduce the main bundle size and still have to possibility to get instancies of root injector singletons.

**Comment by Maximaximum** [comment]
@flash-me thank you for your stackBlitz!

There is an issue with it, though. 

It would be much, much more convenient if it was possible to define all the known providers in the eagerly loaded module, ie `AppModule`, and only add the missing providers (`SERVICE2_MODE` in case of my demo app) when needed. 

Otherwise (according to your suggested solution) I would have to declare ALL the services that have `Service2` in their dependency graph, in the `Injector.create()` call. In my demo app, this means I would need to register providers for `Service1`, `Service2` and `SERVICE2_MODE`. It might seem not to be a huge deal, but in my production application the dependency graph is much more complicated than that. 

Another issue is that while calling `Injector.create()` I have to manually provide the `deps` property, so every time I update my code I have to make sure that the order of the elements in `deps` for each of the providers corresponds to the actual order of the service constructor arguments. In case of a relatively big dependency graph, this complicates dependency management exponentially. And effectively this means that we cannot use any of the benefits of the automatic DI management system that Angular already has.

**Comment by Maximaximum** [comment]
@mlc-mlapis actually I would love to have a possibility to create not just a *singleton* service, but rather multiple instances of a service whenever needed (including a possibility to have multiple service instances at the same time somewhere in my code, e. g. in the `StoreService`). This use case is not fully explained in my demo app (and it's not the primary concern of this feature request), but it would really make the Angular DI system robust enough to use it extensively

**Comment by flash-me** [comment]
> It would be much, much more convenient if it was possible to define all the known providers in the eagerly loaded module, ie `AppModule`, and only add the missing providers (`SERVICE2_MODE` in case of my demo app) when needed.

Nothing holds you back from providing those in your AppModule in its `provders` property. You can even provide stuff when bootstrapping a platform. 

> Otherwise (according to your suggested solution) I would have to declare ALL the services that have Service2 in their dependency graph, in the Injector.create() call. In my demo app, this means I would need to register providers for Service1, Service2 and SERVICE2_MODE. It might seem not to be a huge deal, but in my production application the dependency graph is much more complicated than that.

As said, you can provide everything else as usual, you just have to ensure the Injector has knowledge of the tokens at creation time. 

> Another issue is that while calling Injector.create() I have to manually provide the deps property, so every time I update my code I have to make sure that the order of the elements in deps for each of the providers... 

This is not an issue, this is how DI works, esp. if you need runtime injection. Also this sounds like you want to solve everything with this approach. Maybe you should reconsider your use case and think about other ways? Having a dependency on something that will receive its config a posteriori sound quite dirty, don't you think? There are often more than one way to solve problems. 

 E. g. instead of providing different values you could implement a service which in turn manages such values. This way other consumers just need to inject this particular service and get their stuff from it. 

Typically providing different tokens are used for one time configurations (build, test, etc) or different environments (local, staging, prod, etc.).

cheers
flash :zap:

**Comment by Maximaximum** [comment]
@flash-me 

> Nothing holds you back from providing those in your AppModule in its provders property. You can even provide stuff when bootstrapping a platform.

> As said, you can provide everything else as usual, you just have to ensure the Injector has knowledge of the tokens at creation time.

Probably I don't understand something. Would you mind to provide a stackblitz example based on my stackblitz? As I have explained in my original post, it is impossible to register all the providers in `AppModule` and only provide a value for `SERVICE2_MODE` at a later time. It does not work, as you can see in my sample app.

>Also this sounds like you want to solve everything with this approach.

I just know that the Angular DI system is quite powerful, but it seems to lack some minor features that would allow it to be used in a much broader variety of use cases. And there are clear reasons why I'd like to use this approach. 

> Having a dependency on something that will receive its config a posteriori sound quite dirty, don't you think?

Why would you think it's dirty? The `StoreService` does not need a `Service1` instance at bootstrap time. It only needs to get `Service1` instances at certain moments (e.g., when user clicks a button). Why isn't that a valid use case? I know, this is not a **primary** use case for the Angular DI, but why not provide developers with a little bit wider range of possibilities?

> Maybe you should reconsider your use case and think about other ways?

There are only 2 ways I can think of. 

The first is the one that we use currently in our production app. You can see this approach here: https://stackblitz.com/edit/angular-providing-dependency-in-child-injector-workaround Basically, we're manually instantiating each dependency in the dependency graph. There are a lot of issues with this approach though: the dependencies are not mockable (and therefore the `Service1FactoryService` is not testable), we have to manually take care of instantiating every dependency needed, we also have to take care of the instantiation order etc. Generally, we're getting all the issues that Angular DI has been designed to actually solve.

The other way is to register all the providers that Service1 contains in its dependency graph, in the `Service1FactoryService.createService1()` method, see https://stackblitz.com/edit/angular-providing-dependency-in-child-injector-workaround2 In case of the demo app, it means that we have to manually register 3 providers isntead of 1. In our production app this would mean manually re-registering more than 10 different providers. This solution actually has mostly the same drawbacks as the first one. The dependencies are not mockable (therefore `Service1FactoryService` is still not testable). We have to take care of manually providing all the dependencies contained in the dependency graph. This approach gives us a small benefit that we don't need to take care about the *instantiation order*, but we still have to take care of all the dependencies manually. The `deps` property, btw, is extremelly annoying, since we have to manually maintain this property for each of the providers in a relevant state.

> E. g. instead of providing different values you could implement a service which in turn manages such values. This way other consumers just need to inject this particular service and get their stuff from it.

This might work if we needed a singleton `Service1` instance. But in our case we need to be able to have multiple `Service1` instances simultaneously.

> Typically providing different tokens are used for one time configurations (build, test, etc) or different environments (local, staging, prod, etc.).

I'm sorry, I don't understand what you mean here.

Thank you!

**Comment by flash-me** [comment]
Hi @Maximaximum!

Sorry for the delayed answer. But there is sth called life that I have to consider. 😅 First I want to point out that
- I spend time writing this message because I it is **fun for me to solve things and all I want is to help**, so if sth of what I have written sounds offensive, be sure, **it is not**
- everyone can do whatever one wants to. Solve all the things in a way one wants to. Isn't this kind of freedom one of the main reasons why everyone of us became a developer? :smile:

As you already described [here](https://github.com/angular/angular/issues/35548#issuecomment-589147892), a DI system does have its downsides. 

> And there are clear reasons why I'd like to use this approach. 

This was the point I wanted to address. There are plethora of ways in how to solve things. But in the end, it's **your decision** which way you are going to take. Some may fit better than others. Some are more "cool" than others. And some of this ways unfortunately come with constraints, not **issues**.

> Also this sounds like you want to solve everything with this approach

I may show you what I wanted to tell. **You may consider, that this example is based on assumptions I have taken out of this discussion and must not be correct for your use case. Furthermore there are lot more ways, this example is not the only one**.

### Your current approach

![image](https://user-images.githubusercontent.com/5240450/75628100-0ef09c00-5bd6-11ea-8d6f-0d2c492ad438.png)

In every Service a configuration / value will be injected and the service will do something with that configuration. Looking at your first example, it is a getter `name` that will be called. Depending on that configuration, this getter will return different results, right?

### Why not like this?

![image](https://user-images.githubusercontent.com/5240450/75628227-3c8a1500-5bd7-11ea-85f3-5dbca186eed1.png)

1. Instead of a service fabric there is a config manager which can provide configurations for everyone
2. At a given time your service needs to its first job and asks the config manager for the next configuration 
3. At a given second time your service needs to do its next job and asks the config manager for the next configuration

This way you don't need to play around with the DI. 

cheers 
flash :zap:

**Comment by flash-me** [comment]
Damn. The second figure looks like a stickman. Just realized :sob:

cheers
flash :zap:

**Comment by alxhub** [comment]
This is not a feature of any DI system of which I'm aware, and generally goes against the idea of hierarchical injectors. As others have mentioned, there are ways of resolving this issue by importing the right providers into the child injector instead of expecting them to be provided from child to parent.
