### ISSUE TITLE
ES6 Template literals inside angular expressions

### ISSUE THREAD

**Issue by Akxe** [angular/angular#35563]
# 🚀 feature request

### Relevant Package
This feature request is for @angular/compiler

### Description
Add the ability to use `` `template literals ${onceReady$ | async}` ``.

This is reopening of #12914, because that was from 2016 when angular was at version 2!

### Describe the solution you'd like
I would like it not to break compiler...

### Describe alternatives you've considered
The old ways of writing strings...

**Comment by Airblader** [comment]
The old issue was closed because

> This has been rejected because it would not work with inline templates

From what I can see that is very much still an issue today. What has changed in your opinion?

**Comment by Akxe** [comment]
@Airblader I might be understanding it wrong, but if you use inline template, escaping inner template string is painful, but not impossible. 

And well, compiler switched twice from that time...

**Comment by eemt** [comment]
I would like to add to this a particular use case which I am sure is not unique.  

Most of my templates have a page title/ dialog box title, etc.  Therefore, the text will be in title case.

I also need to localize those titles.  What I would like to be able to do is something like this:
```<h2>{{$localize`:@@LogOut:log out` | titlecase}}</h2>
```

Without the template:
`<h2>{{'log out' | titlecase}}</h2>`
works fine.  But using the tagged template syntax breaks the parser.  

An obvious alternative is:
`<h2 i18n="@@LogOut">Log Out</h2>`
But I reuse the phrase "log out", and would rather avoid having two phrases to translate, one in title case and one not. 

My solution for now is to add a member to the template's component class:
logOut = $localize:":@@LogOut:log out";
Then in my template I can have: 
`<h2>{{logOut | titlecase}}</h2>`

Overall, it means adding quite a few member variables to express strings which really belong in the template.

**Comment by petebacondarwin** [comment]
Within inline templates you can already use template literals expression as long as they contain statically analysable values.
See https://stackblitz.com/edit/angular-ivy-eam5wt?file=src%2Fapp%2Fhello.component.ts.

This is just how strings work in TypeScript - but obviously this would not work in an external template, which is not parsed as a backticked string by TypeScript.  I believe that this has only become possible since Ivy, which introduced more sophisticated static analysis of the template expression.

What won't work is treating these template literal expressions as dynamic binding, which Angular should monitor and update. E.g. `` `template literals ${onceReady$ | async}` ``. This is what Angular interpolation is for.

With this in mind, be aware that tagged template literals are not statically analysable since the compiler cannot know what the tag handler function might do, so `$localize` tagged strings cannot be used in such expressions.

One workaround for the scenario given by @eemt would be to use directives to manipulate the text content of the element rather than a pipe. Then you could have something like:  `<h2 i18n="@@LogOut" titleCase>log out</h2>`.
