### ISSUE TITLE
minLength(1) validator returns invalid on a valid input

### ISSUE THREAD

**Issue by edoxthebest** [angular/angular#35591]
# 🐞 bug report

### Affected Package

 The issue is caused by package @angular/forms

### Description

 Validators.minLength(1) on a form field that has number as type returns invalid when the number entered is 0.

## 🔬 Minimal Reproduction

 https://stackblitz.com/edit/angular-gjs5kh

## 🌍  Your Environment

**Angular Version:**
<pre><code>

8.2.14

</code></pre>

**Comment by Mewster** [comment]
Wouldn't the length of the string "0" be 1? Shouldn't you be using the validator "min" instead?

**Comment by vmuresanu** [comment]
@edoxthebest I tried your minimal reproduction, analyzed how minLength works and I think I found the issue. 
First of all, you are using `input type='number' ` in your code, which converts the value to number. This means that whatever char you are typing, it will be a number. 
Second, looking at Angular Validators source code https://github.com/angular/angular/blob/master/packages/forms/src/validators.ts, specifically on line 287 we have the minLength function. And on line 292 we have this code : `const length: number = control.value ? control.value.length : 0;`. As our `control.value` is number, and specifically 0, the `Boolean(0)` is false, which will always resolve `length` variable with 0, thus it will always Invalid.
So I think the solution would call toString on control.value check 
 `const value = control.value.toString();
const length: number = value ? value.length : 0;`
But this is a change in angular forms code.

**Comment by praveen-sivadasan** [comment]
Seeing the above-proposed solution I believe it's better to consider the following cases before implementing the solution:
1. Number with decimals. Decimal will be counted towards length
2. Negative numbers. The sign will go towards the length.
3. For large number inputs getting stored in exponential format.
4. User input 0 will have a length of 1 using control.value.toString() but input 0123 will have length 3 and not 4.
5. Performance using the toString() method.

**Comment by vmuresanu** [comment]
@praveen-sivadasan 
Number (or amount) fields are very tricky. In our case we ended up dropping the input type number because it gave us a couple of problems. First of all our user didn't like that he could enter 'e' symbol. He understands that this is the way it works, but nevertheless it's shouldn't be accepted by business. Also input type number acted strange on Firefox and IE. 
We end up using a custom decimal input directive on form field (for preventing user to enter chars) with the help of HostListener, together with decimal number custom validator.

It would appear that minLength validator is intended to work with strings. And to use a floating point decimal validation, e.g. allow 2 decimal only, you could use Validators.pattern(/^\d+\.\d{2}$/) again with strings only, because if you have input type number, value "2.00" will be converted to "2" as number and it would fail the Validators.pattern validation.

**Comment by sonukapoor** [comment]
I will take a look at this issue.

**Comment by sonukapoor** [comment]
@edoxthebest We have looked into this issue and the forms source-code - `minLength` and `maxLength` both are **_only_** applicable to strings and arrays. As mentioned by @vmuresanu, for your use-case it would be best to use a string input and a regular expression pattern. 

Something like this would work:

```typescript
profileForm = this.fb.group({
  number: ['', Validators.pattern('[0-9]{1,}')]
});
```

If you need to use an input type of number, you could use a custom validator function and implement the logic. You can find more details [here](https://angular.io/guide/form-validation#custom-validators).

**Comment by petebacondarwin** [comment]
It should also be noted that the current `minlength` and `maxlength` do not actually work for number fields anyway. The validator will always indicate no error for a non-zero number and error for a zero number, whatever the setting of the validator. So there is no point in using it in an application.
