### ISSUE TITLE
docs: getting started guides aren't grouped together in the search results

### ISSUE THREAD

**Issue by Splaktar** [angular/angular#35676]
# 📚 Docs or angular.io bug report

### Description

The getting started guides aren't grouped together in the search results.

### What's the affected URL?**
https://angular.io/

### Reproduction Steps**
1. Click into the search box and type "deployment"

### Expected vs Actual Behavior**
Expected that all "Getting Started with Angular: x" docs would be found under the "START" list.

Actual is here:
![Screen Shot 2020-02-24 at 17 23 51](https://user-images.githubusercontent.com/3506071/75196658-7320e500-572a-11ea-9042-8b945f1b7a1f.png)

It seems like "Getting Started with Angular: Your First App" should be under "START" instead of "OTHER" in the search results for "deployment"?

### Browser info
Chrome 80

### Anything else relevant?
Related to https://github.com/angular/angular/pull/35457#issuecomment-590580142

**Comment by sonukapoor** [comment]
I can take a look at this one. @Splaktar / @gkalpak Please assign to me.

**Comment by sonukapoor** [comment]
@gkalpak / @Splaktar / @aikidave 

The issue of why we are not seeing `Getting Started with Angular: Your First App` in the `start` group is because of the `path` to that page. The `path` is set to `/start`. The function that extracts the group is based on the path. You can see the function here:

https://github.com/angular/angular/blob/master/aio/src/app/shared/search-results/search-results.component.ts#L78

The function will split the path and take the top-level folder as the group. However, this only works if the result of the split has at least 2 entries. In the above `path` this is not the case. I will change the `path` from '/start` to '/start/start-intro` if you are OK with that.

**Comment by aikidave** [comment]
No objections here.

**Comment by gkalpak** [comment]
No, please do not change the URL. This follows our standard practice with `index.html` files (as we do for the other areas: `tutorial`, `cli`, `api`, etc.). Also, we need to maintain a list of redirects for URL changes (both on the server config and in the ServiceWorker), which is not great.

The correct fix imo is to add `start` (and also `api` and `cli`) in the list of `topLevelFolders`: 

https://github.com/angular/angular/blob/5bc39f8c8d5238a9be9bd968cf18ea4b738bd6be/aio/src/app/shared/search-results/search-results.component.ts#L33

**Comment by sonukapoor** [comment]
@gkalpak got it.  Will try this out tonight.
