### ISSUE TITLE
Angular 8 to 9 Variable inside i18n attributte cause error

### ISSUE THREAD

**Issue by pacocom** [angular/angular#35689]
# 🐞 bug report

### Affected Package

 The issue is caused by package @angular/....
![image](https://user-images.githubusercontent.com/7735329/75363113-f6247580-58b9-11ea-803b-35b97a1cc541.png)

### Is this a regression?

 Yes, the previous version in which this bug was not present was: Angular 8.

package.json
```
"dependencies": {
    ...
    "@angular/animations": "^8.2.5",
    "@angular/cdk": "^8.1.4",
    "@angular/common": "^8.2.5",
    "@angular/compiler": "^8.2.5",
    "@angular/core": "^8.2.5",
    "@angular/forms": "^8.2.5",
    "@angular/material": "^8.2.3",
    "@angular/platform-browser": "^8.2.5",
    "@angular/platform-browser-dynamic": "^8.2.5",
    "@angular/router": "^8.2.5",
    "@nrwl/angular": "^8.4.13",
    ...
}
"devDependencies": {
    ...
    "@angular-devkit/build-angular": "^0.803.23",
    "@angular/cli": "^8.3.15",
    "@angular/compiler-cli": "^8.2.5",
    "@angular/language-service": "^8.2.5",
    "@nrwl/cypress": "8.4.13",
    "@nrwl/express": "^8.11.0",
    "@nrwl/jest": "8.4.13",
    "@nrwl/node": "^8.11.0",
    "@nrwl/workspace": "8.4.13",
    ...
}
```
angular.json
```
"default": {
    "fileReplacements": [
        {
            "replace": "apps/client/src/environments/environment.ts",
            "with": "apps/client/src/environments/environment.prod.ts"
        }
    ],
    "optimization": false,
    "outputHashing": "none",
    "sourceMap": true,
    "extractCss": true,
    "namedChunks": true,
    "aot": true,
    "extractLicenses": true,
    "vendorChunk": true,
    "buildOptimizer": false,
    ...
}
```

### Description
Variable inside angular i18n tag cause error:

xlf file:
```
<trans-unit id="pdf.user-data.landline-calls.billing-period" xml:space="preserve">
  <source>Consumption of voice minutes in the last months.</source>
  <target>Consumption of voice minutes in the last {{ period }} months.</target>
</trans-unit>
```
when Angular 8 detect {{ variable }} inside target it worked fine  **but in Angular 9 cause error**.
`ng serve --configuration="default"`:
![image](https://user-images.githubusercontent.com/7735329/75362771-83b39580-58b9-11ea-9f9b-0f6910a027d1.png)
![image](https://user-images.githubusercontent.com/7735329/75362831-975efc00-58b9-11ea-91b7-b6fe55277b6a.png)

## 🔬 Minimal Reproduction

 https://stackblitz.com/...

## 🔥 Exception or Error
<pre><code>

</code></pre>

## 🌍  Your Environment

**Angular Version:**
<pre><code>

</code></pre>

**Anything else relevant?**

**Comment by AndrewKushnir** [comment]
Hi @pacocom, thanks for reporting this issue. Adding extra text bindings in translations (like you described in your message) would not work in Ivy due to the fact that the i18n model has changed.

In View Engine translations were embedded into a template first and compilation happened after that for each locale (which was time and resource consuming). In Ivy the model is different and template compilation is performed first and translation happens after that. As a result in Ivy translations should not contain extra constructions like text bindings. The proposed solution is to refactor the logic in a template (may be split original i18n block into chunks, use ICU syntax or have an extra element with `*ngIf`) to avoid the need to add extra text bindings in translations.

The error that you mentioned in your message was caused by the fact that i18n runtime logic tried to parse the `{{ period }}` in translated message as an ICU and failed. I've just created a PR https://github.com/angular/angular/pull/35923 to verify whether ICU parsing was successful before ICU processing to provide more descriptive error message.

Thank you.
