### ISSUE TITLE
Incorrect number format for de-CH

### ISSUE THREAD

**Issue by DmitryEfimenko** [angular/angular#35748]
# 🐞 bug report

### Affected Package

 The issue is caused by package @angular/....

### Description
The `number` pipe formats number incorrectly for `de-CH` locale.

## 🔬 Minimal Reproduction
https://stackblitz.com/edit/angular-zzhimc

## 🌍  Your Environment

**Angular Version:**
<pre><code>Angular 9.0.4
// used stackblitz - so can't run `ng version`
</code></pre>

**Comment by petebacondarwin** [comment]
You must load the correct locale file. Your example is loading the generic `de` locale. Then when you ask for `de-CH` in the pipe, since the specific locale (`de-CH`) is not loaded it falls back to the generic (`de`) that is loaded.

The fix is to change this line to:

```ts
import localeDe from '@angular/common/locales/de-CH';
```

See https://stackblitz.com/edit/angular-dooqf2?file=src/app/app.module.ts
