### ISSUE TITLE
Maybe there's an inconsistent with style.width binding

### ISSUE THREAD

**Issue by tonivj5** [angular/angular#35838]
# 🐞 bug report

### Affected Package

 The issue is caused by package @angular/core (?)

### Is this a regression?
I don't know

### Description

I think there is an inconsistency with style bindings in properties such as height, width, etc. with number values. While I was writting a tests I had noticed that if you use `0` as value (`[style.width]="0"`) the bind value is `0px`, but it only works with `0` value, if I use any other number it simply no reflect any value (the same behavior as `null` and `undefined` value). I think the reproduction is clear enough of what I'm trying to describe :sweat_smile: 

## 🔬 Minimal Reproduction

https://ng-run.com/edit/fpseYtEgOOY7KpkTXd7k?open=app%2Fapp.component.html (ng-run :100:)

## 🌍  Your Environment

**Angular Version:**
<pre><code>
Angular CLI: 9.0.4
Node: 13.7.0
OS: linux x64

Angular: 9.0.4
... animations, cli, common, compiler, compiler-cli, core, forms
... language-service, localize, platform-browser
... platform-browser-dynamic, router
Ivy Workspace: Yes

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.900.3
@angular-devkit/build-angular     0.900.4
@angular-devkit/build-optimizer   0.900.4
@angular-devkit/build-webpack     0.900.4
@angular-devkit/core              8.3.25
@angular-devkit/schematics        8.3.25
@angular/cdk                      9.1.0
@ngtools/webpack                  9.0.4
@schematics/angular               9.0.4
@schematics/update                0.900.4
rxjs                              6.5.4
typescript                        3.8.2
webpack                           4.41.2

</code></pre>

**Anything else relevant?**
If it is the desired behavior, feel free to close it :+1:

**Comment by kara** [comment]
@tonivj5 Thanks for taking the time to file the issue. I took a look and these behaviors are working as intended. Here's why:

- Setting any style to `null` will remove that style, whereas setting any style to `undefined` will delegate to any conflicting styles with the next highest priority. You can read more about this distinction and why it exists in the [style precedence docs](https://angular.io/guide/template-syntax#delegating-to-styles-with-lower-precedence).

- `[style.width.px]` generally accepts a number input and will work with any number (e.g. both 0 and 10) because Angular will append the unit to the number provided at runtime. `[style.width]` is different from `[style.width.px]` in that it directly writes to the style property without any processing (i.e. does not append a style suffix).  Writing "0" will work and apply the style (since CSS accepts 0 without a unit), but writing "10" will not apply the style (because CSS requires a unit for non-zero values).

**Comment by tonivj5** [comment]
Thanks @kara for the fast reply and clarification! Glad that it isn't a bug :tada:
