### ISSUE TITLE
Renderer2 skipping and appending to wrong element

### ISSUE THREAD

**Issue by Aegis18** [angular/angular#35921]
Affected Package
@angular/Renderer2
### Description

I am trying to use Renderer2 to wrap each child of my `<ng-content>` in a `div` element

```  
ngAfterContentInit(): void {
    let container = document.getElementById('smart-container-id');
    let content: HTMLCollection = container.children;
    let count = content.length;
    console.log('There are ' + count + ' children')
    for (let i = 0; i < count; i++) {
      let wrapper = this.renderer.createElement('div');
      wrapper.id = 'foo' + i;
      this.renderer.appendChild(wrapper, content.item(i));
      this.renderer.appendChild(container, wrapper);
    }
```

I expect each of the 6 children components to be wrapped with a `div` and an id of `fooX`

when I run this code I get

![image](https://user-images.githubusercontent.com/27922019/76126920-645dec00-5fce-11ea-8700-df9c821e77f6.png)

As you can see 3 of the children have not been wrapped, as well as div `foo2` is now a child of `foo4` and `foo4` being a child of `foo5` 

🔬 Minimal Reproduction

My code:
`app-smart-container.component.ts`
```
import {AfterContentInit, Component, OnInit, Renderer2, TemplateRef} from '@angular/core';

@Component({
  selector: 'app-smart-container',
  templateUrl: './smart-container.component.html',
  styleUrls: ['./smart-container.component.scss']
})
export class SmartContainerComponent implements OnInit, AfterContentInit {
  
  constructor(private renderer: Renderer2) {
  }

  ngOnInit() {
  }

  ngAfterContentInit(): void {
    let container = document.getElementById('smart-container-id');
    let content: HTMLCollection = container.children;
    let count = content.length;
    console.log('There are ' + count + ' children')
    for (let i = 0; i < count; i++) {
      let wrapper = this.renderer.createElement('div');
      wrapper.id = 'foo' + i;
      this.renderer.appendChild(wrapper, content.item(i));
      this.renderer.appendChild(container, wrapper);
    }
  }
}
```

`app-smart-container.component.html`:
```
<div id="smart-container-id" class="container">
    <ng-content></ng-content>
</div>
```

`app.component.html`

```
<app-smart-container>
  <div style="background: red">
    &nbsp;
  </div>
  <div style="background: orangered">
    &nbsp;
  </div>
  <div style="background: orange">
    &nbsp;
  </div>
  <div style="background: yellow">
    &nbsp;
  </div>
  <div  style="background: blue;">
    &nbsp;
  </div>
  <div  style="background: blueviolet;">
    &nbsp;
  </div>
</app-smart-container>
```

🌍  Your Environment

**Angular Version:**
<pre><code>
Angular CLI: 9.0.4
Node: 10.15.3
OS: win32 x64

Angular: 9.0.4
... animations, cli, common, compiler, compiler-cli, core, forms
... language-service, localize, platform-browser
... platform-browser-dynamic, router
Ivy Workspace: Yes

Package                            Version
------------------------------------------------------------
@angular-devkit/architect          0.900.4
@angular-devkit/build-angular      0.900.4
@angular-devkit/build-optimizer    0.900.4
@angular-devkit/build-webpack      0.900.4
@angular-devkit/core               9.0.4
@angular-devkit/schematics         9.0.4
@angular/cdk                       9.1.0
@angular/elements                  9.0.5
@angular/material                  9.1.0
@angular/material-moment-adapter   9.1.0
@ngtools/webpack                   9.0.4
@schematics/angular                9.0.4
@schematics/update                 0.900.4
rxjs                               6.4.0
typescript                         3.7.5
webpack                            4.41.2

</code></pre>

**Comment by JoostK** [comment]
I am fairly certain that the behavior you are observing is because [`HTMLCollection`](https://developer.mozilla.org/en-US/docs/Web/API/HTMLCollection) is a live view, and therefore updated as you makes changes to the DOM.

You can work around it by copying the collection into an array before processing the DOM updates.

I am closing this issue per the above, if you are still experiencing issues please comment here so we may reopen.

**Comment by Aegis18** [comment]
@JoostK Yup that fixed my issue thank you!

But I don't understand how that fixed it. I tell the `renderer` to appendChild of the container 
(` document.getElementById('smart-container-id');`). I could understand if everything wasn't in the right order but, the nesting is what confused me

Thanks again

**Comment by JoostK** [comment]
It's quite tricky, but the gist of it is that this line:

```ts
this.renderer.appendChild(container, wrapper);
```

takes the wrapper element that contains `children.item(i)` and appends it as last DOM node in the container. This will cause the original `children.item(i)` to be moved, because it is contained within the DOM element that was appended, and as an `HTMLCollection` is _live_, it will immediately update to reflect the change. Therefore, reading `children.item(i)` will now actually refer to a different element (the subsequent one) and you'll eventually end up selecting a wrapper element as `i` increases past the number of original elements that have already been wrapped. At that point, you'll start to wrap already wrapped items.
