### ISSUE TITLE
typedefinition: TestBed.inject(T) should return jasmine.SpyObj<T>

### ISSUE THREAD

**Issue by hamzahamidi** [angular/angular#35944]
# 🐞 bug report

### Affected Package

 The issue is caused by package @angular/....
@angular/core testing
I was playing with the [test project of Angular](https://angular.io/generated/live-examples/testing/specs.stackblitz.html)  and I noticed that the [TestBed.inject(service) method ](https://angular.io/api/core/testing/TestBed#inject) is returning the `service`  whereas it should be returning a `jasmine.SpyObj<service>`
Can you check the type definition of the method please or maybe I misunderstood the definition?

**Comment by jnizet** [comment]
`TestBed.inject()` returns the service provided under the given type/token in the testing module. It could be an actual instance of a service (if that's what is provided), or a spy (if you provided a spy instead of an actual service when configuring the testing module). 

So there's no reason for the method's return type to be a jasmine.SpyObj.

**Comment by JoostK** [comment]
Hello @hamzahamidi,

@jnizet is correct here, it depends entirely on what is provided. As such, the return type of `TestBed.inject` cannot be assumed to be a `jasmine.SpyObj`.

**Comment by hamzahamidi** [comment]
But if it's not a spyObj how do you access attributes such as mock.calls ...

**Comment by JoostK** [comment]
You'd need to cast it:

```ts
TestBed.inject(MyService) as jasmine.SpyObj<MyService>;
```

Note that there's no guarantee that this is a safe cast; this is inherent to using a dependency injection container where the registration of a service is separate from the usage of it. Any usage that assumes a certain implementation (or a mock, in this case) may be incorrect.

Also, can you show where in the StackBlitz you found this pattern? I couldn't find it myself.

**Comment by hamzahamidi** [comment]
That's what I did to correct the test. That's why I was thought maybe we need to add spyObj as a possible return value:
```typescript
inject<T>(token: Type<T> | InjectionToken<T> | AbstractType<T>, notFoundValue: null, flags?: InjectFlags): T | jasmine.SpyObj<T> | null 
```
You can find the code in ``demo.testbed.spec.ts``  line 86 & 100

**Comment by JoostK** [comment]
Are you suggesting the StackBlitz demo does not compile as is? In that case, it needs to be corrected.

Other than that, the crux is in this line:
```ts
{ provide: ValueService, useValue: spy }
```

This is the logic that _provides_ the spy for the `ValueService` token. This means that from that point onward, asking for `ValueService` will give the spy. In theory however, _any_ type can be provided here, not just a `jasmine.SpyObj`.

Even if `TestBed.inject` were changed as you suggest, the return type `T | jasmine.SpyObj<T>` still does not guarantee a `jasmine.SpyObj`, because it could also be just a `T` (so you'd still need the cast).

**Comment by hamzahamidi** [comment]
Is there a git repository of the test project? All I could find was the StackBlitz demo. Thanks

**Comment by JoostK** [comment]
Yes, it's in this repo: https://github.com/angular/angular/tree/master/aio/content/examples/testing

**Comment by hamzahamidi** [comment]
Thanks I'll send the pr to fix the test

**Comment by bryanforbes** [comment]
I'm trying to do something similar to the code in the test project and I'm getting a compiler error when I try to assign `TestBed.inject(ValueService)` to `valueServiceSpy`. And it really _should_ be a compiler error. The only reason the StackBlitz demo works is because the compiler can't find a definition for `jasmine.SpyObj`, so it sets the type of `valueServiceSpy` to `any` and then allows the assignment. Unless I'm missing some sort of compiler flag in my project that adds logic to the compiler to add additional type info to `TestBed.inject()` after a `TestBed.configureTestingModule()`, the code in the demo project won't compile in a normal environment.

**Comment by omnibrain** [comment]
I'm also facing this problem. While I agree that returning jasmine.SpyObj<T> from TestBed.inject is definitely not a good idea, some guidance would be helpful as this is a very standard use case in unit tests. In the project I'm currently working on we have more than 200 occurrences of this. 

So far the only solution I've come up with for this problem is 

```javascript
serviceMock = (TestBed.inject(MyService) as unknown) as SpyObj<MyService>;
```

... but it's very verbose and error probe.
