### ISSUE TITLE
Programatic Pipe creation with angular

### ISSUE THREAD

**Issue by UdayAppam** [angular/angular#35948]
Hi
I would like to request you to give the feasibility to create the Pipe programatically.

https://stackoverflow.com/q/60544411/6687096

**Comment by petebacondarwin** [comment]
It doesn't make sense to generate Pipe classes dynamically since in Angular (except in the now uncommon JIT mode) all templates are compiled ahead of time and there is no possibility of modifying them to inject a different pipe at runtime.

The answer in the stackoverflow that you link gives some ideas of alternative strategies.
Further, if you are providing a system where you want your developers to be able to generate pipes themselves within a larger project you could consider creating an Angular CLI Schema to do so.
