### ISSUE TITLE
Issue with strictTemplates and input events

### ISSUE THREAD

**Issue by IgorMenshikov** [angular/angular#35958]
# 🐞 bug report

### Description

I have upgraded my application to Angular 9 and tried to enable strictTemplates checks. One of templates I have has

```
<input type="text" (input)="onChange($event.target.value)">
```

Someday I took that logic from:
https://stackoverflow.com/questions/35359358/angular-2-change-event-on-every-keypress

and it works well.

## 🔥 Exception or Error
On "ng serve", I get: error TS2339: Property 'value' does not exist on type 'EventTarget'.

But value exists because callback function receives it.

## 🌍  Your Environment

Angular 9.0.5

**Comment by EmaGht** [comment]
You can bypass Ivy's strict check if you want:

<input type="text" (input)="onChange($any($event.target).value)">

**Comment by petebacondarwin** [comment]
According to our docs we should support this type: https://angular.io/guide/template-syntax#event-and-event-handling-statements. Can you confirm what the declaration of your `onChange()` method is?

**Comment by JoostK** [comment]
This is actually expected. The `$event.target` property is declared in TypeScript's DOM typings as follows:

```ts
readonly target: EventTarget | null;
```

<sup>[Source](https://github.com/microsoft/TypeScript/blob/8d63a7a842c6322211b4e125c25bacf0941928b9/src/lib/dom.generated.d.ts#L5452)</sup>

The `EventTarget` type is a generic base interface for things that can be a target, where `HTMLInputElement` is one of its subclasses. However, the typings don't tell that it's this particular subtype, because the `InputEvent` interface doesn't redeclare `target` to be of type `HTMLInputElement`.

I have discussed this case with @alxhub when implementing event binding checking, and we didn't come up with a safe way of providing better ergonomics here. The main issue is that DOM events can bubble, in which case it would be very hard to determine the actual type of the `target` property.

The suggestion by @EmaGht is actually the workaround for this. The `$any` cast is necessary to indicate that you know/assume that the target is in fact a `HTMLInputElement` so that reading the `value` property is okay.

**Comment by JoostK** [comment]
Btw, checking of DOM events was initially disabled, even with `strictTemplates`. In fact, the comment is still there:

https://github.com/angular/angular/blob/99ce015f42a7a59636705a901f52228c3f287890/packages/compiler-cli/src/ngtsc/core/src/compiler.ts#L415-L419

However it looks like this check has in fact been enabled for `strictTemplates` sometime after its inception.

**Comment by JoostK** [comment]
Apart from the `$any` workaround, you could also disable DOM event checking altogether using the `strictDomEventTypes` compiler option. It allows to use `strictTemplates` but without strict DOM event type checking.

**Comment by petebacondarwin** [comment]
@JoostK I think this should be documented somewhere around https://angular.io/guide/template-syntax#event-and-event-handling-statements

**Comment by JoostK** [comment]
@petebacondarwin Agreed! I have thought until now that this check was actually still disabled :-)

**Comment by IgorMenshikov** [comment]
Thanks for the workaround and configuration option.

Just few notes:

1. If you cannot really check EventTarget, maybe it is better just skip it from check like "any". At least, until you find some good solution. "False positive" errors is not something you expect working with so popular library as Angular.

2. It is good to have that documented at:
https://angular.io/guide/template-typecheck

Many "old" users of Angular won't read https://angular.io/guide/template-syntax#event-and-event-handling-statements with every new version release.

**Comment by alxhub** [comment]
@IgorMenshikov glad you could work around this!

> If you cannot really check EventTarget, maybe it is better just skip it from check like "any". At least, until you find some good solution. "False positive" errors is not something you expect working with so popular library as Angular.

It's actually not up to Angular. When it comes to DOM events, we're using the same type for `$event` that you would get from doing `element.addEventListener('someEvent', ($event) => {...})`. If you wrote this code in plain TypeScript, you'd end up with the same type error.

This is also actually a real error in some cases, as @JoostK mentioned, because events in the DOM can bubble. It might not be safe to assume that `$event.target` really is the same type as the element which registers the listener.

> It is good to have that documented at: https://angular.io/guide/template-typecheck

 It's documented here actually: https://angular.io/guide/template-typecheck#troubleshooting-template-errors. `$event.target` is called out as one of the edge cases that might be surprising.

Cheers!

**Comment by IgorMenshikov** [comment]
I thought it is Angular specific because we enable strictTemplates at angularCompilerOptions section.

You are right about documentation. I read it and missed that point.

if I understand "bubble" problem correctly, events go from child to parent. But in case of last-child we may be safe to find out what EventTarget is. At my example, input control has no any children, so all events to it should have EventTarget to be this input control.

Anyway, you have documentation for $event.target and there is a workaround. I think it is reasonable to close the issue.
