### ISSUE TITLE
Update lighthouse in aio to v5.7.0

### ISSUE THREAD

**Issue by IgorMinar** [angular/angular#35965]
this version of lighthouse fixes the issue with `img[loading=lazy]`, see: https://github.com/angular/angular/pull/34900#issuecomment-594091352

**Comment by sonukapoor** [comment]
@IgorMinar Does it just need an upgrade in the `package.json` or is there more to be done here?

**Comment by gkalpak** [comment]
@sonukapoor, it depends on what has changed in Lighthouse since the currently used version. I usually look through the Lighthouse changelog/release notes and if there are no changes we need (or could benefit from) adapting to, then it is just updating the version in `aio.package.json` (and `aio/yarn.lock`).

The script we use to run Lighthouse is [aio/scripts/audit-web-app.js][1], so if other changes are needed it would be in that script.

[1]: https://github.com/angular/angular/blob/13495c64f7b245fd4828b998858f1dc9030c2454/aio/scripts/audit-web-app.js

**Comment by sonukapoor** [comment]
According to @IgorMinar's [comment](https://github.com/angular/angular/issues/35965#issue-578060853), this is a fix we need. I will try that out.

**Comment by sonukapoor** [comment]
@gkalpak The version 5.7.0 is actually not out yet. I will monitor the package and update the `aio/package.json` and `aio/yarn.lock` when it's released. Could you assign this issue to me?

**Comment by ajitsinghkaler** [comment]
@sonukapoor latest version is released you can work on this
