### ISSUE TITLE
Ivy regression: TypeError: el.setAttribute is not a function

### ISSUE THREAD

**Issue by ItielBeeri** [angular/angular#35994]
# 🐞 bug report

### Is this a regression?
Yes, it worked well on Angular 8, and still works well on Angular 9 when disabling Ivy.

### Description
In a routed component, when applying a specific directive (`kendoGridSelectAllCheckbox`) on `ng-template`, an error is thrown: `TypeError: el.setAttribute is not a function`.
Again, this occurs only in a _routed_ component: if the same template is used directly in the AppComponent (or any other component that explicitly belongs to the root component tree), the issue is gone.

## 🔬 Minimal Reproduction
An extremely simplified reproduction is in [this GitHub repository](https://github.com/ItielBeeri/ng9-kendo-grid-problem).
1. Clone that repository
2. Run `yarn`
3. Run `ng s` and navigate to `/list` route

### Actual behavior
The above error is thrown and nothing rendered.

### Expected behavior
No errors. Since the grid isn't fed with data, the string `No records available.` should be rendered.
You can see this expected behavior just by disabling Ivy.

## 🔥 Exception or Error
<pre><code>
ERROR TypeError: el.setAttribute is not a function
    at DefaultDomRenderer2.setAttribute (platform-browser.js:1151)
    at elementAttributeInternal (core.js:12989)
    at Module.ɵɵattribute (core.js:19843)
    at SelectAllCheckboxDirective_HostBindings (index.js:17657)
    at setHostBindingsByExecutingExpandoInstructions (core.js:11453)
    at refreshView (core.js:11820)
    at refreshComponent (core.js:13213)
    at refreshChildComponents (core.js:11504)
    at refreshView (core.js:11825)
    at refreshDynamicEmbeddedViews (core.js:13138)
</code></pre>

## 🌍  Your Environment

**Angular Version:**
<pre><code>
Angular CLI: 9.0.5
Node: 12.14.0
OS: win32 x64

Angular: 9.0.5
... animations, cli, common, compiler, compiler-cli, core, forms
... language-service, localize, platform-browser
... platform-browser-dynamic, router
Ivy Workspace: Yes

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.900.5
@angular-devkit/build-angular     0.900.5
@angular-devkit/build-optimizer   0.900.5
@angular-devkit/build-webpack     0.900.5
@angular-devkit/core              9.0.5
@angular-devkit/schematics        9.0.5
@ngtools/webpack                  9.0.5
@schematics/angular               9.0.5
@schematics/update                0.900.5
rxjs                              6.5.4
typescript                        3.7.5
webpack                           4.41.2
</code></pre>

**Comment by pkozlowski-opensource** [comment]
A simpler reproduce scenario: https://ng-run.com/edit/klKBOX1JNrET1nlYADik?open=app%2Fapp.component.ts

I can confirm that this is a bug and the crux of it that if we've got a directive with a host binding writing to an attribute _and_ we put this directive on `<ng-template>` (and probably `<ng-container>`!) it will throw.

In VE such errors would be silently ignored since since host bindings were part of the usage template so VE _knew_ if it makes sense at all to have a binding on `<ng-template>` / `<ng-container>`.

We could "fix" it ivy by ignoring bindings on  `<ng-template>` / `<ng-container>` but one could also argue that this is invalid directive usage - here `[kendoGridSelectAllCheckbox]` expects to be put on a regular element (since it wants to set attributes) but it is used on `<ng-template>`. I don't know enough abut Kendo impl but the example given puts the mentioned directive on an `<input>` element: https://www.telerik.com/kendo-angular-ui/components/grid/selection/#toc-select-all-feature

@ItielBeeri  do you think that usage of `[kendoGridSelectAllCheckbox]` on `<ng-template>` is a valid one?

**Comment by ItielBeeri** [comment]
@pkozlowski-opensource you're right. Moving the directive to the inner input solved the error. Thank you :)
Unless this is still considered a bug for general compatibility reasons, it can be closed.

**Comment by pkozlowski-opensource** [comment]
> Moving the directive to the inner input solved the error.

Good, thnx for coming back to me with this info! 

> Unless this is still considered a bug for general compatibility reasons, it can be closed.

I will keep it open for a bit to see if there are more similar issues coming in so we can decide if we want to fix it.
