### ISSUE TITLE
Including (instagram) Scripts breaks Angular Router

### ISSUE THREAD

**Issue by Highklaas** [angular/angular#36019]
# 🐞 bug report

### Affected Package

The URLs of the website are changing when clicking on router links, but the application is not loading a new page.

### Description

My customer wants to include an Instagram Module that shows different pictures and opens a modal on click. (we tried https://getflowbox.com/ and https://squarelovin.com/ )

Nothing fancy, but something that we cant just use an iframe for because of its "global" impact like opening a modal etc.

## 🔬 Minimal Reproduction

Our Application is pretty extensive. Theres also no way for me to legally show you the code. But its an angular application, the error also occurs if you exclude everything else on the side. Happens for multiple scripts.

## 🔥 Exception or Error

Clicking on links does not redirect you. No console errors, loads page if you do a hard reload.

## 🌍  Your Environment

**Angular Version:**
Angular 8.2

**Anything else relevant?**
Chrome 80.0

**Comment by AndrewKushnir** [comment]
Hi @Highklaas,

Thanks for reporting this issue. However, you didn't provide sufficient information for us to understand and reproduce the problem. Please check out [our submission guidelines](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-submitting-an-issue) to understand why we can't act on issues that are lacking important information.

Could you please provide a minimum repro (using fake/test components and modules) using https://stackblitz.com/ or in a form of Github repository, so that we can perform further investigation?

Thank you.

**Comment by Highklaas** [comment]
Hi Andrew,

i created a  Stackblitz example: https://stackblitz.com/edit/angular-t1svna

You can find the link by scrolling all the way down. The images you see are created by the script. While creating this example i tested it without using the angular-router and it works fine. Maybe that helps you narrowing down the area of conflict.

**Comment by atscott** [comment]
Hi @Highklaas, the stackblitz example doesn't seem to be working. Would you mind creating a GitHub repo instead if you can't get one to work on stackblitz?

**Comment by atscott** [comment]
Thanks for reporting this issue. However, you didn't provide sufficient information for us to understand and reproduce the problem. Please check out [our submission guidelines](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-submitting-an-issue) to understand why we can't act on issues that are lacking important information.

If the problem still exists in your application, please [open a new issue](https://github.com/angular/angular/issues/new/choose) and follow the instructions in the issue template.
