### ISSUE TITLE
ngcc: should support `browser` property

### ISSUE THREAD

**Issue by KingSora** [angular/angular#36062]
Good day!

I'm the author of the [OverlayScrollbars](https://github.com/KingSora/OverlayScrollbars) library and I'm providing a Angular wrapper. This wrapper is written in TypeScript but isn't using ng-packagr for building. Instead I've written my own build script, and I'm compiling it with `ngc` the repo can be found [here](https://github.com/KingSora/OverlayScrollbars/tree/master/packages/overlayscrollbars-ngx). 
The wrapper isn't very complex and also isn't using any special, exotic or deprecated features of Angular.

Since Angular9 user have reported issues ([here](https://github.com/KingSora/OverlayScrollbars/issues/190) and [here](https://github.com/KingSora/OverlayScrollbars/issues/141)) with the wrapper, which are related to ivy. After a bit of experimenting I found out, that you have to run `npx ngcc` to make it function (at least its working in my project).

My question is, how do I prevent this? I know that Angular is running the `ngcc` command if you compile your project with `ng serve` but for some reason this isn't enough for my library. I have to run it manually in order to not getting a error in the browser console.

I checked the `package.json` before and after running `ngcc` manually and the difference is small, but there is a difference in the `__processed_by_ivy_ngcc__` section:
**Before running ngcc manually:**
```json
"__processed_by_ivy_ngcc__": {
  "module": "9.0.6",
  "typings": "9.0.6"
}
```
**After running ngcc manually:**
```json
"__processed_by_ivy_ngcc__": {
  "main": "9.0.6",
  "module": "9.0.6",
  "typings": "9.0.6"
}
```
How can I tell angular to run ngcc also on the main module without executing `ngcc` manually, or how can I solve the whole issue differently?

**Comment by petebacondarwin** [comment]
Taking a look...

**Comment by petebacondarwin** [comment]
So when you run `ng serve` I can see that the CLI is asking ngcc to process the `module` entry-point, which is the ESM5 format: 

```
$ ng serve
0% compiling
Compiling @angular/core : es2015 as esm2015
Compiling @angular/common : es2015 as esm2015
Compiling @angular/platform-browser : es2015 as esm2015
Compiling @angular/platform-browser-dynamic : es2015 as esm2015
Compiling overlayscrollbars-ngx : module as esm5

chunk {main} main.js, main.js.map (main) 58.4 kB [initial] [rendered]
chunk {polyfills} polyfills.js, polyfills.js.map (polyfills) 140 kB [initial] [rendered]
chunk {runtime} runtime.js, runtime.js.map (runtime) 6.15 kB [entry] [rendered]
chunk {styles} styles.js, styles.js.map (styles) 9.72 kB [initial] [rendered]
chunk {vendor} vendor.js, vendor.js.map (vendor) 3.05 MB [initial] [rendered]
Date: 2020-03-13T20:14:04.072Z - Hash: a4fc2b6742b8d033234f - Time: 27098ms
** Angular Live Development Server is listening on localhost:4200, open your browser on http://localhost:4200/ **
: Compiled successfully.
```

But then when you look at the bundle that the CLI build (i.e. webpack) is producing, it appears to have used the `main` entry-point instead (which was not processed by ngcc).

**Comment by petebacondarwin** [comment]
<img width="476" alt="Screenshot 2020-03-13 at 20 23 43" src="https://user-images.githubusercontent.com/15655/76656917-8e805280-6568-11ea-8518-e0cab43f31ab.png">

**Comment by petebacondarwin** [comment]
Ahah! It There is also a `browser` property in `package.json`, which is pointing to the UMD package. 

It appears that ngcc does not include `browser` as a supported format. See https://github.com/angular/angular/blob/e0a35e13d57f5c4ba3d6c87231e0dd6e0cafd923/packages/compiler-cli/ngcc/src/packages/entry_point.ts#L76

So even though the CLI is passing it as a possible property to process, ngcc quietly ignores it and goes to the next property it recognises which is `module`.

A quick workaround for you would be to remove the `browser` property from your `package.json`. This is actually in keeping with the spec: https://github.com/defunctzombie/package-browser-field-spec

> If your module is pure javascript and can run in both client and server environments, then you do not need a browser field.

I think that, given you code is not targeting the server then you do not need this field.

**Comment by petebacondarwin** [comment]
Meanwhile we should look into changing ngcc to handle `browser` - at least the simple case where it is a string.

**Comment by KingSora** [comment]
@petebacondarwin Thanks for your quick response! The `browser` property wasn't initally part of my `package.json`, but a user added it via [this](https://github.com/KingSora/OverlayScrollbars/pull/166) PR to address his issues. Do you have also a solution / suggestion for his case?

**Comment by clydin** [comment]
The browser entry point is intended to only guarantee that the code does not use any Node.js specific APIs.  It does not provide any guarantees as to the ES variant used by the code.  In this case pointing the browser entry point to the UMD bundle happened to work since it also was ES5 compatible code but this is not something that can be relied upon generally.
Non-ESM code can and will prevent a large class of optimizations to be performed on the code and can lead to significantly larger output bundle file sizes.  Since the browser entry point is by default favored over others when bundling, the majority of users' applications will be affected by this.

There are two options to solving the problem outside of the browser entry point.  The first is more ideal (more optimized output especially for modern browsers) but may require the user to setup their build system appropriately.  The second requires little to no setup for the user.  The second involves ensuring that the code referenced by the module entry point is ES5 compatible code but with ES modules.  A change to the libraries build process would most likely be necessary to achieve this.  This will allow bundlers to generate code that is compatible with older browsers and still allow optimizations such as tree-shaking.
In contrast, the first option would have the module entry point use code targeting ES2015 (including ES modules).  This would then require the application's build system to down-level the code to support the application's required browsers (the Angular CLI does this via differential loading).  This allows the bundler to perform all the ES module related optimizations as well as not penalizing modern browsers by including code (e.g., down-leveled class constructs) only needed by older browsers.

**Comment by petebacondarwin** [comment]
So @KingSora it seems that adding the `browser` was not necessarily the correct solution to that person's problem. One idea could be to use ng-packagr to package up your library. It is easy to use and provides a distributable that will work well with the other Angular tooling (i.e. CLI and ngcc).

For our part we are tracking adding "some" support for `browser` in ngcc at FW-2001 (thank you HAL) - although I doubt we will support the more complex object based `browser` properties.
