### ISSUE TITLE
Class Decorators causing DI to break in NG9 production builds

### ISSUE THREAD

**Issue by martin31821** [angular/angular#36120]
# 🐞 Class Decorators causing DI to break in NG9 production builds

### Affected Package

Should be caused by either ivy or the build tooling, @angular/compiler-cli, @angular-devkit/build-angular.

### Is this a regression?

Yes, the previous version in which this bug was not present was: 8.2.13

### Description

When applying a class decorators to an @Injectable(), the dependencies of the Injectable won't get resolved by the Dependency injection.
I'm hitting the issue with MultiWindowService [here](https://github.com/EmbeddedEnterprises/ng6-golden-layout/blob/ng8-electron/projects/ngx-golden-layout/src/lib/multiwindow-service.ts#L25)
I know it's a fairly extensive use case, but it used to work up to ng8. 

## 🔬 Minimal Reproduction
A reproduction can be found [here](https://github.com/EmbeddedEnterprises/ng6-golden-layout).
Steps to reproduce: 
Run `npm ci`, then `ng build ngx-golden-layout`, then `ng-serve`.
Within the browser devtools, you see a console statement saying `FooService: object Object`

If you run `ng-serve --prod` it says `FooService: undefined`.
(Console statement is [here](https://github.com/EmbeddedEnterprises/ng6-golden-layout/blob/ng8-electron/src/app/app.module.ts#L79))

## 🌍  Your Environment

**Angular Version:**
<pre><code>
Angular CLI: 9.0.2
Node: 13.11.0
OS: linux x64

Angular: 9.0.1
... animations, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router
Ivy Workspace: Yes

Package                            Version
------------------------------------------------------------
@angular-devkit/architect          0.900.2
@angular-devkit/build-angular      0.900.2
@angular-devkit/build-ng-packagr   0.900.2
@angular-devkit/build-optimizer    0.900.2
@angular-devkit/build-webpack      0.900.2
@angular-devkit/core               9.0.2
@angular-devkit/schematics         9.0.2
@angular/cli                       9.0.2
@ngtools/webpack                   9.0.2
@schematics/angular                9.0.2
@schematics/update                 0.900.2
ng-packagr                         9.0.0
rxjs                               6.5.4
typescript                         3.7.5
webpack                            4.41.2
</code></pre>

**Anything else relevant?**
I'm aware that I'm pushing angular to its limits here, but nevertheless, I'd like to see this working again.

**Comment by JoostK** [comment]
The issue here is that you're swapping out a service with a completely new constructor, effectively creating a new class. This means that the AOT compilation output for the original service is no longer available, as it's shadowed by the dynamic constructor.

The same problem also occurs in JIT mode, if the `@MultiWindowService` decorator is above the `@Injectable` decorator (I noticed you had to swap them in the repro to make it work in JIT). This makes sense, given that decorators execute bottom-to-top, so if `@MultiWindowService` is at the bottom it will swap out the constructor, which will then be prepared for JIT compilation using the `@Injectable` decorator that executes after it.

This used to work in ViewEngine as providers were compiled into the NgModule definition using their original token, so any constructor override would still allow accessing the metadata (given that the original class is used as the token). The Ivy runtime however stores the compiled provider on the class itself, so replacing that class hides the metadata from the runtime.

To fix the issue, you'd need to copy over all properties from the original class over to the new class after creating `newConstructor`:

```ts
   for (const prop in constr) {
      if (constr.hasOwnProperty(prop)) {
        newConstructor[prop] = constr[prop];
      }
    }
```

---

From a framework perspective, it doesn't seem to me that we can do anything about this. The workaround actually seems like a proper fix here, without it you'd also be hiding things like static properties on the class.
