### ISSUE TITLE
AsyncPipe subscribe in NgZone

### ISSUE THREAD

**Issue by xiaoxiangmoe** [angular/angular#36139]
# 🐞 bug report

### Affected Package

 The issue is caused by package @angular/common

### Is this a regression?

 Yes, the previous version in which this bug was not present was: ....

No

### Description

AsyncPipe subscribe in NgZone, will cause useless change detection.

## 🔬 Minimal Reproduction

see: https://github.com/xiaoxiangmoe/angular-async-inner-check/blob/master/src/app/child-view/child-view.component.ts#L7

If we change `<div> a = {{ a$ | asyncInnerCheck }} </div>` to `<div> a = {{ a$ | async }} </div>`, ngAfterViewChecked for ChildViewComponent and AppComponent will be triggered.

If we are in a giant angular app, a small `async` pipe binding will cause the Change Detection of the entire app to be triggered. 

## 🌍  Your Environment

**Angular Version:**
<pre><code>Angular CLI: 9.0.7
Node: 13.5.0
OS: darwin x64

Angular: 9.0.7
... animations, cli, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router
Ivy Workspace: Yes

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.900.7
@angular-devkit/build-angular     0.900.7
@angular-devkit/build-optimizer   0.900.7
@angular-devkit/build-webpack     0.900.7
@angular-devkit/core              9.0.7
@angular-devkit/schematics        9.0.7
@ngtools/webpack                  9.0.7
@schematics/angular               9.0.7
@schematics/update                0.900.7
rxjs                              6.5.4
typescript                        3.7.5
webpack                           4.41.2
</code></pre>

**Anything else relevant?**

**Comment by sod** [comment]
Maybe too late for an existing app as you may rely heavily on global change detection. But when we rebuilt our website we started with setting the root component to `OnPush`. This disables all the default change detection and will only check components during a tick, that you explicitly `markForCheck` (which the async pipe automatically does). So with that pattern, the async pipe will indeed only update the source template - plus every child templates where inputs change.

**Comment by xiaoxiangmoe** [comment]
Is it reasonable to use asyncInnerCheck pipe for an existing app?

**Comment by petebacondarwin** [comment]
Just to clarify what @xiaoxiangmoe is suggesting....

Currently we have in `AsyncPipe`:

```ts
  private _subscribe(obj: Observable<any>|Promise<any>|EventEmitter<any>): void {
    this._obj = obj;
    this._strategy = this._selectStrategy(obj);
    this._subscription = this._strategy.createSubscription(
        obj, (value: Object) => this._updateLatestValue(obj, value));
  }
```

And the proposal is to run the creation of the subscription outside the zone:

```ts
  private _subscribe(obj: Observable<any> | EventEmitter<any>): void {
    this._obj = obj;
    this._strategy = this._selectStrategy(obj);
    this._ngZone.runOutsideAngular(() => {
      this._subscription = this._strategy.createSubscription(
        obj,
        (value: any) => this._updateLatestValue(obj, value)
      );
    });
  }
```

**Comment by petebacondarwin** [comment]
Personally this seems very sensible to me, and in keeping with the idea that `async` pipe is designed to avoid unnecessary change detection...

That being said, I am concerned that anything downstream of this `async` pipe would also not have any change detection triggered. Is that correct? In which case, we might miss a rendering update? I updated the original repo to try to test this: https://github.com/xiaoxiangmoe/angular-async-inner-check/pull/1. But it appears still to work fine, so it appears that the 

```
this._ref.markForCheck();
```

in the `AsyncPipe._updateLatestValue()` method is enough to ensure that the change is detected.

**Comment by xiaoxiangmoe** [comment]
@petebacondarwin What I need to do now is to wait for the engineer to review? Do I need to provide more information?

**Comment by petebacondarwin** [comment]
Basically I have asked internally whether there is something that we are missing that might be important.

@jelbourn suggested that this might be a big breaking change for projects that somehow rely upon that change detection cycle happening on each event on the observable.

I'll see if anyone else has any thoughts and get back to you next week. I suspect we might have to put this behind a flag in order to land it...

**Comment by xiaoxiangmoe** [comment]
@petebacondarwin Any update?

**Comment by petebacondarwin** [comment]
The general feeling I got, specifically from @jelbourn and @pkozlowski-opensource, is that this could be a big breaking change for projects that expect that CD and have hooks running based in the item arriving on the Observable; and that as you demonstrated it is not too hard to create your own pipe that works this way.

I will bring it up at our Framework meeting tomorrow, but I am not sure it will be accepted.

**Comment by xiaoxiangmoe** [comment]
But if we create this pipe ourselves, we may lose type checking (it may be improved after language service is switched to ivy).
And this piece of code is far from the business, it seems that this should be maintained by the framework developers, should not be maintained the business developers?

**Comment by petebacondarwin** [comment]
To further the discussion I have created a Stackblitz: https://stackblitz.com/edit/ivy-n5q9ix?file=src%2Fapp%2Fapp.component.html

This allows us to trigger emission from within the NgZone (by clicking the buttons); and also outside the NgZone (from the console).

The results of the `async` and `customAsync` pipes are interesting...

* Clicking the buttons updates all the interpolations as expected and also updates the `logs` iteration.

![Screenshot 2020-06-07 at 10 58 19](https://user-images.githubusercontent.com/15655/83965849-7fcae280-a8ae-11ea-9f24-3f204fb062f2.png)

* Emitting items on to the observables outside the zone (from the console) for the `async` pipes don't appear to trigger any change detection at all: no changes to the interpolations and no update to the `logs` interpolation!
* Emitting items on to the observables outside the zone (from the console) for the `customAsync` pipes appears to update the interpolations and trigger child component change detection but not change detection for the current component, which means the `logs` iteration is not updated.

![Screenshot 2020-06-07 at 10 54 15](https://user-images.githubusercontent.com/15655/83965855-89544a80-a8ae-11ea-94ed-e78e734ed7ac.png)

**Comment by intellix** [comment]
Was literally just crawling the net thinking how to achieve this and figured markForCheck -> detectChanges is what I needed. 

We've got countdown components which are updating every 16ms and causing unnecessary change detection to run for the whole CD path to update a single number. Example, which the above fixes for me: https://stackblitz.com/edit/angular-ivy-bjbamb?file=src%2Fapp%2Finner%2Finner.component.html

**Comment by petebacondarwin** [comment]
We discussed this in the team meeting today.

It is felt that changing the behaviour of this pipe like this would undoubtedly break a number a projects, since it is quite likely that some projects rely upon the CD cycle that is triggered by the `async` pipe subscribing to an observable.

Moreover, it is felt that there is no single approach to the `async` pipe that will satisfy all the potential use cases in this regard; and it is very hard to determine what is the best choice for any one scenario.

So this would result in the `async` pipe having to be configurable; and for developers to find it difficult to decide which to use.

It was pointed out that an alternative solution would be to be able to isolate a single component so that only its change detection is triggered for a particular dirty mark. There is a design in process to modify how change detection works so that it should be possible to achieve this: https://docs.google.com/document/d/1ciKBdPnEzOLruX2kHeITCScMlv6JEj0WxLSnIb_0LoQ. Please do take a look at this design and comment.

In the meantime, the workaround is to write a custom pipe that subscribes outside of the NgZone. I have updated my Stackblitz example to avoid relying upon any private APIs: https://stackblitz.com/edit/ivy-n5q9ix?file=src%2Fapp%2Fcustom-async.pipe.ts

I will leave this issue open for now since we hope to solve the problem via the design mentioned above.

**Comment by JeanMeche** [comment]
I just encountered a major performance issue on my app becase of this. 

- I was expecting the `async` pipe to have no side effects on a `OnPush` component. Yet this was not true, since the pipe subscribing within an NgZone, it triggers the CD. 

Shouldn't this at least be specified in the documentation ? 

While I complety understand modifying the current async pipe would break some apps, l would also pretty much welcome another async pipe which runs outside the angular zone !

**Comment by dylhunn** [comment]
This is working as intended.
