### ISSUE TITLE
Custom Element output events not firing during initialization lifecycle hooks

### ISSUE THREAD

**Issue by antch** [angular/angular#36141]
# 🐞 bug report

### Affected Package
The issue is caused by package @angular/elements

### Is this a regression?
No

### Description
Event listeners on Custom Element component outputs don't fire during `ngOnChanges` (initial call), `ngOnInit`, `ngAfterViewInit`, or `ngAfterContentInit`.

## 🔬 Minimal Reproduction
https://github.com/antch/angular-elements-lifecycle-hooks
For both the Custom and Native element there is a list which should be appended with the fired events. For the native element, we can see the callback fires during initialization of the component, but this doesn't happen for the Custom Element.

You can look in the console to see the execution of the lifecycle hooks.

The reproduction uses artifacts from a [CI build](https://circleci.com/gh/angular/angular/657041#artifacts/containers/0) associated with #36114.

## 🌍  Your Environment

**Angular Version:**
*Warning:* This is a build off of CI assets, so this isn't entirely accurate.

<pre><code>
Angular CLI: 9.0.6
Node: 10.14.2
OS: darwin x64

Angular: 9.1.0-next.4
... animations, common, compiler, compiler-cli, core, elements
... forms, language-service, platform-browser
... platform-browser-dynamic, router
Ivy Workspace: Yes

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.900.6
@angular-devkit/build-angular     0.900.6
@angular-devkit/build-optimizer   0.900.6
@angular-devkit/build-webpack     0.900.6
@angular-devkit/core              9.0.6
@angular-devkit/schematics        9.0.6
@angular/cli                      9.0.6
@ngtools/webpack                  9.0.6
@schematics/angular               9.0.6
@schematics/update                0.900.6
rxjs                              6.5.4
typescript                        3.6.5
webpack                           4.41.2
</code></pre>

**Comment by gkalpak** [comment]
From a quick look, this happens, because `NgElementImpl` [subscribes to events][1] after calling [ngElementStrategy#connect()][2], which is where the [initial change detection][3] takes place (running the lifecycle hooks).

I need to take a proper to determine whether we can fix this without a breaking change or a change to the public API.

[1]: https://github.com/angular/angular/blob/c0143cb2abdd172de1b95fd1d2c4cfc738640e28/packages/elements/src/create-custom-element.ts#L167-L170
[2]: https://github.com/angular/angular/blob/c0143cb2abdd172de1b95fd1d2c4cfc738640e28/packages/elements/src/create-custom-element.ts#L164
[3]: https://github.com/angular/angular/blob/c0143cb2abdd172de1b95fd1d2c4cfc738640e28/packages/elements/src/component-factory-strategy.ts#L158

**Comment by gkalpak** [comment]
Should be fixed by #36161 (no breaking change \o/). Could you test that too on your project, @antch 🙏

**Comment by antch** [comment]
Looks good 👍

**Comment by gkalpak** [comment]
FYI, we had to revert the fix, because it turned out to be a breaking change. More specifically, if someone was using their own `NgElementStrategy` that did not initialize the `events` property before calling its `connect()` method (with @remackgeek's [ElementZoneStrategy][1] being a common one), `@angular/elements` would break because it would try to subscribe to the strategy's `events` while it was undefined.

Therefore this fix has to wait for v11, unless we can fix it in a non-breaking way (which I think it possible). I will update with more info in the coming days.

[1]: https://github.com/remackgeek/elements-zone-strategy/blob/f1b6699495a8c0909dbbfbdca12770ecca843e15/projects/elements-zone-strategy/src/lib/element-zone-strategy.ts

**Comment by antch** [comment]
Thanks for your continued work on these Elements issues @gkalpak!

**Comment by gkalpak** [comment]
For reference: #37570
