### ISSUE TITLE
ngcc error on package @sitecore-jss/sitecore-jss-angular

### ISSUE THREAD

**Issue by EvtK** [angular/angular#36164]
# 🐞 bug report

### Affected Package
@sitecore-jss/sitecore-jss-angular

### Description

Trying to update an NX repo running the npm run update command. This results in trying to upgrade to angular 9, which was the ultimate goal.

Along the way I get this error:

Error: Error on worker #3: Error: Tried to overwrite <removed>/node_modules/@sitecore-jss/sitecore-jss-angular/dist/components/file.directive.d.ts.__ivy_ngcc_bak with an ngcc back up file, which is disallowed.

I have already tried clearing npm node_modules, clean install etc. No effect.

## 🔬 Minimal Reproduction

This can be repro-ed by installing the @sitecore-jss/sitecore-jss-angular package and the running the following command:

`ngcc --properties es2015 browser module main --first-only --create-ivy-entry-points
`

## 🌍  Your Environment

**Angular Version:**

`Updating package.json with dependency @nrwl/angular @ "9.1.2" (was "8.12.1")...
`
The NX update process tries to update as follows:

```
Updating package.json with dependency @angular/cli @ "9.0.1" (was "8.3.3")...
    Updating package.json with dependency @angular/language-service @ "9.0.7" (was "8.2.8")...
    Updating package.json with dependency @angular-devkit/build-angular @ "0.900.1" (was "0.803.3")...
    Updating package.json with dependency @angular/compiler-cli @ "9.0.7" (was "8.2.8")...
    Updating package.json with dependency @angular/animations @ "9.0.7" (was "8.2.8")...
    Updating package.json with dependency @angular/common @ "9.0.7" (was "8.2.8")...
    Updating package.json with dependency @angular/core @ "9.0.7" (was "8.2.8")...
    Updating package.json with dependency @angular/forms @ "9.0.7" (was "8.2.8")...
    Updating package.json with dependency @angular/platform-browser-dynamic @ "9.0.7" (was "8.2.8")...
    Updating package.json with dependency @angular/platform-browser @ "9.0.7" (was "8.2.8")...
    Updating package.json with dependency @angular/compiler @ "9.0.7" (was "8.2.8")...
    Updating package.json with dependency @angular/router @ "9.0.7" (was "8.2.8")...
```

I'm not sure whether I should file the report here or on the sitecore-jss repo. If this is the wrong place, please let me know.

**Comment by JoostK** [comment]
This package appears to incorrectly include two `package.json` files. These are processed by ngcc individually, but they target the same files. ngcc disallows this; files should only be processed once.

Can you try ignoring the `package.json` in the `dist` directory by creating a `ngcc.config.js` file next to your `package.json`:

```js

module.exports = {
  packages: {
    '@sitecore-jss/sitecore-jss-angular': {
      entryPoints: {
        './dist': {
          ignore: true,
        },
      },
    },
  },
};
```

If I didn't make a mistake in typing that, it should start to work. I do recommend to clear `node_modules` once more before trying again.

**Comment by EvtK** [comment]
Hallo Joost! 🇳🇱

Bingo! 10 points!.. 

Now I am wondering, this jss-angular package is build with ng-packager. It think, instead of fixing this per each project using this package, it should be fixed within the package itself. Might there something be misconfigured with the ng-packager configuration? If so I can open up a PR to have it fixed on their side.

thanks for the quick assistance, btw!

**Comment by JoostK** [comment]
Their ng-packagr output in `dist` is correct, it's that they publish the project root instead of `dist` that is problematic. It's only because they have manually included all APF (Angular Package Format) related properties [in their project's `package.json`](https://github.com/Sitecore/jss/blob/469f21111d2e0985d1e183eedc2c42f7cc8f6cc1/packages/sitecore-jss-angular/package.json#L56-L66) that it works, but that should not be managed manually (ng-packagr automatically extends the original `package.json` files with the necessary properties).

I would open an issue with them and propose two possibilities:
1. Adjust their publishing to only publish `dist`. They're using Lerna where this was not possible in the past, but I do recall them adding support for that at some point.
2. Include an ngcc configuration file in their repo next to `package.json` so that not every consumer has to do it manually. Note that this file would have to be slightly different:

```js
module.exports = {
  entryPoints: {
    './dist': {
      ignore: true,
    },
  },
};
```

Alternatively, we can ship default configs with ngcc itself _however_ we typically only do that for obsolete packages that haven't received updates in a long time. It's preferred that the original package is fixed instead.

**Comment by EvtK** [comment]
Hi Joost, thanks again. I have opened up an issue on the sitecore-jss-angular issue tracker. I'll close this one up here.
