### ISSUE TITLE
Dynamic imports not working for libraries

### ISSUE THREAD

**Issue by fkolar** [angular/angular#36209]
# 🐞 bug report

### Is this a regression?
No. New thing

### Description
Dynamic imports works ok in the application but when you try to use them inside sharable library to cover more advance usecases, I cant seems to make it work. 

Let's say you want to use this simplified component that can accepts path to import and component name you want to insert this instantiated component to the view:

```html
<m-renderer [name]="'MyInputComponent'" [path]="'@dynamic-renderer/ui-lib'">
</m-renderer>
```
or

```html
<m-renderer [name]="'MatInput'" [path]="'@angular/material/input'">
</m-renderer>
```

Simple usecase to create something more generic. You can think of it like in more advanced scanarios you would read some metadata to turn them into visual representation. 

## 🔬 Minimal Reproduction

here is the git repo `https://github.com/ngx-meta/dynamic-renderer`

In this repo, there is a lib folder where:

**core**: Contains dynamic renderer  that accepts import path and uses `ComponentFactoryResolver` and `ViewContainerRef ` to add component to the screen
**ui-lib**: Simple input field

```
npm install
ng build core && ng build ui-lib, ng serve
```

**Comment by mlc-mlapis** [comment]
@fkolar The Angular compiler creates all necessary code during compilation on the base of the very exact syntax in the source code. Your issue doesn't meet that syntax for sure, so it can't work.

**Comment by fkolar** [comment]
Can you elaborate more on this? This all comes down to enterprise usecase to be able to create programatically UI based on metadata and this is one piece of the puzzle. 

Are you saying that imports cannot work with examples and must have exact path? This is what are you saying?

**Comment by mlc-mlapis** [comment]
@fkolar Yep. It's limited in using right now, I know. What is on the way, is some new APIs, that includes HoC and also more dynamic flexibility when creating component instances dynamically (but not by patching way). It was mentioned many times from Angular core team, that these things come after Ivy.

Actually, there is the Angular 9.1 on the way, which makes Ivy really stable and eliminates some partial problems that were found out in version 9.0. So it's possible to expect that the mentioned above is probably behind the corner already.

**Comment by JoostK** [comment]
I only looked at the code briefly but there appears to be a bug in the renderer:

https://github.com/ngx-meta/dynamic-renderer/blob/61f88bb4d6874a1cf3b18420143fdb64bbb59ed9/libs/core/src/lib/renderer/renderer.component.ts#L79-L93
```ts
export class RendererComponent {
 // ...
  protected resolveComponentType(): any {
    const type = this.doLoadType(this.name, this.path);
    console.log('type: ', type);
    return type;
  }

  private async doLoadType(name: string, path: string) {
    const m = await import(/* webpackIgnore: true */ path);
    return m[name];
  }


  protected componentReference(): ComponentReference {
    const currType = this.resolveComponentType();
    const componentFactory: ComponentFactory<any> = this.factoryResolver.resolveComponentFactory(currType);
    // ...
  }
  // ...
}
```

Notice how `doLoadType` is async, so it returns a `Promise`, which is cast to `any` in `resolveComponentType` and then fed into `this.factoryResolver.resolveComponentFactory`, still being promise. That cannot work, as `currType` will definitely be a `Promise` that Angular can't create a component factory for.

You didn't post any errors and I haven't run the repro, so I don't know how it currently fails. I would expect this error:

> Type passed in is not ComponentType, it does not have 'ɵcmp' property.

**Comment by fkolar** [comment]
@JoostK I havent got beyong this line ` const m = await import(/* webpackIgnore: true */ path);` 

When you look at this code https://github.com/ngx-meta/dynamicinput/blob/master/src/app/app.component.ts, then imports works correctly, whatever I pass in, in library code whatever you pass in it does not return anything.

**Comment by pkozlowski-opensource** [comment]
@fkolar did you managed to resolve this issue? I've read through the comments in the issue but it sounds to me more like a support request and I think that @JoostK provided some guidance here. 

If you still bump into problems please provide a _minimal_ reproduce scenario using stackblitz or similar - it is very hard for us to debug entire apps, I'm afraid. But would be more than willing to help if you can reduce the scenario.

**Comment by fkolar** [comment]
@pkozlowski-opensource thats for comming back to me. yes there is a still a issue. What I can do I can update the POC sample I did for this and paste the link again here. What @JoostK was refering and point out the `Notice how doLoadType is async, so it returns a Promise` issue - there is definitelly issue with that line, but I have never to manage to get past this line as it even fails to return the promise for the import when used inside the library.

**Comment by pkozlowski-opensource** [comment]
@fkolar here is a bare-bones stackblitz representing what (I think) you are trying to do: https://stackblitz.com/edit/angular-zwkyvs?file=src%2Fapp%2Fapp.module.ts
Is this is your use-case (it will only work with ivy of course)?

**Comment by fkolar** [comment]
Yes, This is exactly the case, when I used this identical code inside the app, it works, if I used this code inside library, that I import into the project, it does not.

**Comment by JoostK** [comment]
Sorry for not getting back here. I suppose the root issue is that the dynamic import doesn't resolve correctly in the browser, as the module specifier like '@angular/material/input' cannot be resolved.  This is expected to me, given that there's no Node module resolution behavior in the browser, you'd have to be loading a module using a relative path that is served from a server.

This article may give some more insight: http://dplatz.de/blog/2019/es6-bare-imports.html

I am not too familiar with Webpack and dynamic imports, but the `webpackIgnore` makes me believe that Webpack takes its hands off the import, so that you're responsible for serving it correctly yourselves.

My take on it is that this is not a bug in Angular framework, as the framework is not involved in the dynamic import in any way. I could see how this could be a feature request for the CLI, though.

**Comment by fkolar** [comment]
On the app leve when I used this, all works finn. 

```ts
@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.css']
})
export class AppComponent implements OnInit {
  title = 'dynamicinput';
  value: any = 'asdf';

  @ViewChild('minput', {read: ViewContainerRef, static: false})
  inputContainer: ViewContainerRef;


  constructor(private cf: ComponentFactoryResolver, private injector: Injector) {
  }

  ngOnInit(): void {
    this.showInput();
  }


  async showInput() {
    const aAA = await import('@angular/material/input');
    const factory = this.cf.resolveComponentFactory(aAA['MyInputComponent']);



    const {instance} = this.inputContainer.createComponent(factory, null,
      this.injector);

    console.info('asdfas');
    console.info(instance);

    instance['value'] = 'My First text';
    instance['readonly'] = false;
    instance['disabled'] =  false;

  }
}
```

You are right, I dont think it must be in Angular, more underlying tools NG is using and they might not support these things.

**Comment by JoostK** [comment]
Changing Pawel's repro to use a non-statically analyzable import (making it truly dynamic) also fails:

```
    let mod = './lazy';
    import(mod).then(...)
```

The error is different due to a different module bundler setup, but the effect is the same.

**Comment by pkozlowski-opensource** [comment]
From your description it sounds to me like the main issue here is that actual loading (dynamic `import(...)` to get ES module instance, right? If so, the exact setup will heavily depend on your packaging, build etc. You need to prepare for a bit of fiddling given all possible setups.

Also please not that the workflow that you are trying to implement is not currently "officially" supported since there are so many loose ends that a regular user would bump into (NgModule, packaging etc.). I'm pretty positive that it _can_ be done but there are so many steps in the toolchain and so many settings that it is very brittle in practice.

This is a pattern we definitively want to support in the long run but we are not here. Again, I think that it can be done but currently you have to be prepared for a lot of investigations into the existing toolchain, different settings etc.

As @JoostK pointed out this is not strictly linked to Angular core but all the lazy-loading and packaging setup. 

I'm inclined to mark it as a use-case - we want to support this workflow in the future out-of-the-box but we are not there. I don't think we can afford debugging your particular setup so I'm afraid that you will have to dig into it on your own or ... wait till it is supported in the CLI.

**Comment by fkolar** [comment]
Cuz then the problem comes down, that you cannot have really some dynamic renderer that can lazily load components based on the configuration (as library), you will always need to import all the components that are you going to use inside your app. which pitty.

**Comment by fkolar** [comment]
```
I'm inclined to mark it as a use-case - we want to support this workflow in the future out-of-the-box but we are not there. I don't think we can afford debugging your particular setup so I'm afraid that you will have to dig into it on your own or ..
```

I fully agree. I am not sure what you can do with this at the moment.

**Comment by jelbourn** [comment]
Tracking the main underlying concern here in #18093
