### ISSUE TITLE
Tree Shaking providers methods which are not used in application.

### ISSUE THREAD

**Issue by rahultokase** [angular/angular#36239]
# 🚀 feature request
Hi 
In angular we do have a support for Tree Shaking for Providers. Can we extend this support to provide the support the providers methods as well. Non used Methods should be removed during tree shaking.

### Relevant Package

 This feature request is for @angular/....
Not-Known

### Description
 A clear and concise description of the problem or missing capability...
Hi

We are using the generating the Angular services from yml files and these yml files can be shared between front end and backend. 

One YML file = One service

User can define many methods inside the yml files and very can be used in the UI. So if we have a the support for Tree Shaking the Providers methods then we can remove this not used/ Dead code/method from the generated angular service.

### Describe the solution you'd like
 If you have a solution in mind, please describe it.

### Describe alternatives you've considered
 Have you considered any alternative solutions or workarounds?

**Comment by lazarljubenovic** [comment]
Tree-shaking class methods in general is a difficult task ([example](https://github.com/rollup/rollup/issues/349)). Adding dependency injection to the mix increases the difficulty by an order of magnitude.

For the exact same reason (easier tree-shaking), RxJS got rid of methods and introduced `pipe`. If you're already doing codegen, you can probably utilise a similar strategy relatively easily by changing how you codegen. The compiler should then exclude any _functions_ (not methods) that you don't happen to call.

**Comment by alxhub** [comment]
Angular actually does not do any tree-shaking on its own. The CLI makes use of tools in the web ecosystem (e.g. Terser/Rollup/Webpack/etc) which all perform various optimizations relating to the removal of unused code. The framework itself is designed to be as optimizable as possible by such tooling.

As @lazarljubenovic mentions, there's generally really good reasons web tooling doesn't support tree-shaking of methods very well - because JavaScript is such a dynamic language, it's very hard if not impossible to implement such optimizations.

A notable exception here is Google's Closure Compiler, which _can_ perform dead code elimination at the method level using typed optimizations. The only reason this is possible is because of the burden Closure Compiler places on its users to submit correctly typed code, not only for your application but for every single dependency that is included. This is extremely burdensome for apps in the NPM ecosystem, since very few NPM packages ship with Closure typings included.
