### ISSUE TITLE
Issue when upgrading to ng 9.1

### ISSUE THREAD

**Issue by LanderBeeuwsaert** [angular/angular#36248]
# 🐞 bug report

### Affected Package

 The issue is caused by package @angular/....

probably angular-cli 9.1

### Is this a regression?

 Yes, the previous version in which this bug was not present was: ....

yep

### Description

 A clear and concise description of the problem...

When upgrading to angular 9.1, only when deploying to production (so optimization, AoT and all that on) I get:

![image](https://user-images.githubusercontent.com/1098243/77585470-da29e900-6ee4-11ea-9802-1edd1a1f06b9.png)

**Comment by kaito3desuyo** [comment]
I have a same issue, but this issue seems to be due to @angular/material-moment-adapter.

We have prepared a minimal reproduction repository.
https://github.com/kaito3desuyo/angular-test

How to reproduce
1. clone this repository
2. ``ng build --prod``
3. ``npm i -g http-server``
4. move root directory to ``dist/angular-test`` Folder
5. ``http-server``
6. open ``http://localhost:8080``

**Comment by LanderBeeuwsaert** [comment]
Closing for the reason that @kaito3desuyo made a more accurate ticket.
