### ISSUE TITLE
HttpClient is parsing a response to JSON ignoring the content-type

### ISSUE THREAD

**Issue by houbi56** [angular/angular#36274]
Using angular 8.2.14

Error: http.get<string>(url) fails to parse response data. 

Request headers: 
Accept: application/json, text/plain, */*

Response headers:
Content-Type: text/plain; charset=utf-8

Response data: S89

{error: SyntaxError: Unexpected token S in JSON at position 0
    at JSON.parse (<anonymous>)

WHY is JSON parsing done for response content type: text/plain?
This goes against all expectations.

**Comment by mlc-mlapis** [comment]
@houbi56 Read the official docs on https://angular.io/guide/http. The main logic is to control what's coming on on a client-side and not to accept anything from a server-side. You have to set that incoming data is not JSON.

**Comment by quentin-ma** [comment]
Please read the following pattern for any issues https://github.com/angular/angular/issues/new/choose

**Comment by alxhub** [comment]
Angular doesn't use the response `Content-Type` for any purpose. This was a design choice made for `HttpClient`.

The reason is that we wanted a typed API, where the type of the `Observable` for your response is strongly defined (not `any` as it had been in the past). The only way to do this is if you tell Angular/TypeScript what kind of response you expect in advance - by the time the response comes back with a `Content-Type`, it's too late.

We _could_ throw an error if the `Content-Type` doesn't match what you've told us to expect, but I think that's a slippery slope. There are plenty of misconfigured APIs out there - APIs that return JSON data with a `text/plain` MIME type for example.

I don't think we should be in the business of validating the correctness of APIs - if you tell Angular to handle the response as JSON, we should attempt to do so.

**Comment by jessicajaniuk** [comment]
It appears this behaves as expected. If you still feel there is an issue, please provide further details in a new issue.
