### ISSUE TITLE
provide: import("@angular/core/src/di/injection_token").InjectionToken<string>;

### ISSUE THREAD

**Issue by liyang010813** [angular/angular#36292]
![微信图片_20200328165251](https://user-images.githubusercontent.com/31497640/77819314-f744fe80-7114-11ea-9bd9-136c8978186e.png)
🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑

Please do not file questions or support requests on the GitHub issues tracker.

You can get your questions answered using other communication channels. Please see: 
https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question

Thank you!

🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑

**Comment by gkalpak** [comment]
This seems to be an issue in `@clr/angular` v1.x (e.g. [@clr/angular@1.3.6/.../dropdown-focus-handler.service.d.ts][1]) - i.e. having deep imports instead of importing from a package's public API.

The issue has been fixed in `@clr/angular` v2+ (e.g. [@clr/angular@2.3.9/.../dropdown-focus-handler.service.d.ts][2]).

[1]: https://unpkg.com/browse/@clr/angular@1.3.6/popover/dropdown/providers/dropdown-focus-handler.service.d.ts
[2]: https://unpkg.com/browse/@clr/angular@2.3.9/popover/dropdown/providers/dropdown-focus-handler.service.d.ts

**Comment by liyang010813** [comment]
@gkalpak thank you
