### ISSUE TITLE
inject() must be called from an injection context

### ISSUE THREAD

**Issue by splincode** [angular/angular#36309]
# 🐞 bug report

### Affected Package

The issue is caused by package @angular/core

### Description

Hello, I wrote a decorator that dynamically injects services using this decorator. But unfortunately, it works strangely for tests.

https://github.com/Angular-RU/autowired

```ts
@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.css']
})
export class AppComponent implements OnInit {
  @Autowired() public app: AppService;

  public title = '';

  public ngOnInit(): void {
    this.title = this.app.hello();
  }
}
```

```ts
@Injectable()
export class AppService {
  @Autowired() public my: AnyService;

  public hello(): string {
    return this.my.title;
  }
}
```

```ts
@Injectable()
export class AnyService {
  public title: string = 'App';
}
```

```
ng serve
```

![image](https://user-images.githubusercontent.com/12021443/77859861-71a87800-7214-11ea-9819-d471263c7835.png)

It works great!

But if I try write test

```ts
describe('Simple usage @Autowired', () => {
  it('should be correct ensure service', () => {
    @Injectable({ providedIn: 'root' })
    class AppService {
      public get name(): string {
        return 'appName';
      }
    }

    @Component({
      selector: 'app',
      template: ''
    })
    class AppComponent {
      @Autowired() public app: AppService;

      public appRef() {
        return this.app;
      }
    }

    TestBed.configureTestingModule({
      declarations: [AppComponent],
      providers: [AppService]
    }).compileComponents();

    const app = TestBed.createComponent(AppComponent);
    console.log('app', app.componentInstance.appRef());
  });
});
```

```ts
 PASS  projects/autowired/tests/simple.spec.ts
  Simple usage @Autowired
    ✓ should be correct ensure service (66ms)

  console.log projects/autowired/tests/simple.spec.ts:34
    app undefined

Test Suites: 1 passed, 1 total
Tests:       1 passed, 1 total
Snapshots:   0 total
Time:        3.918s

```

I decided to figure it out, but for some reason, when I run the tests, I get such an error when catching:

```
inject() must be called from an injection context
```

![image](https://user-images.githubusercontent.com/12021443/77859935-dcf24a00-7214-11ea-8fbc-60fc5e25f406.png)

@mhevery @JoostK Could you tell me what I'm doing wrong when I try to get an injector and then get a service?

## 🔬 Minimal Reproduction

```
$ git clone https://github.com/Angular-RU/autowired.git
$ yarn install
$ yarn start # for see good work @Autowired() decorator

$ jest # for see @Autowired() decorator doesn't work
```

## 🌍  Your Environment

**Angular Version:**

Angular 9.1.0

**Comment by JoostK** [comment]
This logic happens lazily so it depends on the time it is first accessed what the injection context is:

```ts
localInjector = directiveInject(INJECTOR) || createInjector(INJECTOR);
```

Because of the lazy access, this logic is only triggered in the spec when there's no invocation context available:

```ts
console.log('app', app.componentInstance.appRef());
```

But besides that, there's a couple of flaws in this design; This code is not executed when you think it is:

```ts
      const instance = factory(target.constructor as any);
      localInjector = directiveInject(INJECTOR);
      return instance;
```

This will only get triggered once the `meta` service is instantiated, but that only happens upon lazy access of the `Autowired` fields. This is why `localInjector` is not set as you'd expect.

The biggest problem however is this piece of code:

```ts
    meta.ɵfac = () => {
      const instance = factory(target.constructor as any);
      localInjector = directiveInject(INJECTOR);
      return instance;
    };
```

This lets the static factory function be a closure closing over the `injectService` invocation for `target`, which means it's no longer static. In fact, you have likely created a memory leak of `target` because of the closure, as well as made `localInjector` correspond with the most recently instantiated instance, not the one specifically for _this_ target.


I am going to close this issue as there is no Angular bug here.

**Comment by splincode** [comment]
@JoostK Is there any public API that would allow working with meta-information in Angular?

```
The workaround is simple: convert he lazy access into a greedy access within that factory closure. 
```

Please, show me, how?

**Comment by JoostK** [comment]
Not that I know of, at the moment.

It should be this simple:

```ts
export function injectService<T>(target: Object, key: Key, meta: InjectableMeta<T>): void {
  const classRef: ClassRef<T> = getReflectType<T>(target, key);
  const factory = meta.ɵfac;
  meta.ɵfac = (t: any) => {
    const instance = factory(t);
    instance[key] = directiveInject(classRef);
    return instance;
  };
}
```

Again, the disclaimer: this is in no way supported and may stop working at any time.

**Comment by splincode** [comment]
@JoostK But why `meta.ɵfac` is undefined when I runned `ng test` (Karma or Jest). AOT not supported for tests?

**Comment by JoostK** [comment]
Whether `ɵfac` is present or not should not depend on AOT vs JIT AFAIK.

**Comment by splincode** [comment]
Then why is it missing when I run the test?

**Comment by JoostK** [comment]
A few observations:

- I had to manually run ngcc to switch the Angular sources over to Ivy.
- The property decorator executes before the `@Injectable` decorator, so the JIT compilation will not have been executed as you swap out the factory.
- the `ɵfac` property is write-only and requires the usage of `Object.defineProperty` to reconfigure it.
- If you introduce the `Promise.resolve` trick, the original factory will already have executed before you are able to patch it. Only if you await the tick before instantiating the component will it start to work.

**Comment by splincode** [comment]
@JoostK Thank you very much for helping in this matter.

```ts
I had to manually run ngcc to switch the Angular sources over to Ivy.
```

What do you mean? Did I also need to do this somehow?

```ts
The property decorator executes before the @Injectable decorator, so the JIT compilation will not have been executed as you swap out the factory.
```

That is, it is impossible for JIT?

```ts
the ɵfac property is write-only and requires the usage of Object.defineProperty to reconfigure it.
```

That is, I should notice my code for this?

```ts
Object.defineProperty(meta, 'ɵfac', { ... });

// instead
meta.ɵfac = function(t) {}
```

```ts
If you introduce the Promise.resolve trick, the original factory will already have executed before you are able to patch it. Only if you await the tick before instantiating the component will it start to work.
```

That is, it does not make sense?

**Comment by JoostK** [comment]
> @JoostK Thank you very much for helping in this matter.
> 
> ```ts
> I had to manually run ngcc to switch the Angular sources over to Ivy.
> ```
> 
> What do you mean? Did I also need to do this somehow?

I guess you do indeed need to run ngcc manually, because the CLI isn't used for tests (I didn't run the build target before, that may make a difference).

> 
> ```ts
> The property decorator executes before the @Injectable decorator, so the JIT compilation will not have been executed as you swap out the factory.
> ```
> 
> That is, it is impossible for JIT?

Property decorators are emitted and therefore executed prior to the class decorators. [TypeScript playground example](https://www.typescriptlang.org/v2/en/play?noEmitHelpers=true&ssl=3&ssc=17&pln=3&pc=20#code/AIEQpgxg9gTghgF1gCgJQCgwA8AOsEAEEANnAM5kEAqAlgsWAMpgwBuNEYBA3ugQcAAKMKDjQEcInAC4CcAHYBPANzoAvkA).

You can probably work around this using a custom decorator at the class level that executes after the compilation has occurred (i.e. above the Angular decorator) to apply the side-effect of the properties that have been decorator (you'd need to keep track of the decorators somehow in that case)

> 
> ```ts
> the ɵfac property is write-only and requires the usage of Object.defineProperty to reconfigure it.
> ```
> 
> That is, I should notice my code for this?
> 
> ```ts
> Object.defineProperty(meta, 'ɵfac', { ... });
> 
> // instead
> meta.ɵfac = function(t) {}
> ```

Correct.

> 
> ```ts
> If you introduce the Promise.resolve trick, the original factory will already have executed before you are able to patch it. Only if you await the tick before instantiating the component will it start to work.
> ```
> 
> That is, it does not make sense?

I would indeed say that the extra tick does not make sense.
