### ISSUE TITLE
angular 9 lib can't be used in angular 8 app as expected

### ISSUE THREAD

**Issue by admir86** [angular/angular#36354]
# 🐞 bug report

### Affected Package

 The issue is caused by package @angular/core (not sure)

### Is this a regression?

Yes, the previous version in which this bug was not present was: 8.0.x

### Description

I have an angular library (v8.0.0) which contains only services (generated by [nswag](https://github.com/RicoSuter/NSwag)) all services with `providedIn: 'root'`. This library is published on an inhouse npm store (proget) and used in an angular v8.2.x project. Everything worked fine. 
Now I'm preparing to upgrade to angular 9. So I created a new angular 9 library (used as template) where the generated services comes in. Ivy is disabled:
```json
  "angularCompilerOptions": {
    "enableIvy": false
  }
```
The problem now is, that this library (now based on angular 9) no longer works in my angular v8.2.x project. When I build my project with --prod (and only then!) the services from the lib are not available. I get a `NullInjectorError` error.

When I install the same library in angular project v9 it works as expected.

## 🔬 Minimal Reproduction

I could share the empty library template if needed but not my real consumer app. Anyway is simple to reproduce:

1. create a new angular app with angular cli 8.0.1
```
ng new consumerApp
```
2. create a new angular lib with angular cli 9.1 
```
ng new ng-api-client --create-application=false
cd ng-api-client
ng generate library service
```
3. remove sample component and module (not the sample service)
4. build the lib with --prod
5. publish the lib somehow somewhere
6. install the lib in the consumerApp
7. inject the sample service from the lib in the  app.component
8. start the app with `ng serve --prod`

## 🔥 Exception or Error
<pre><code>
NullInjectorError: StaticInjectorError(Li)[Pi -> e]: 
  StaticInjectorError(Platform: core)[Pi -> e]: 
    NullInjectorError: No provider for e!
</code></pre>

## 🌍  Your Environment

**Angular Version:**
angular: described above
nodejs: v12.13.1
</code></pre>

**Anything else relevant?**

**Comment by JoostK** [comment]
This is expected, actually. Angular is generally backwards compatible, but there is no guarantee on forwards compatibility. Even in ViewEngine compilations (Ivy disabled) you'll find generated code in the compiled output, for tree shakeable providers. The generated code was changed in Angular 9, but older versions are unable to deal with the new compilation output.

As a library developer, you'd always need to compile using the oldest version you need to support, so that you rely on backwards compatibility of the platform, not forwards compatibility.
