### ISSUE TITLE
【Error】There is a small error in angular documents

### ISSUE THREAD

**Issue by zaranetCore** [angular/angular#36408]
🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑
About an error in the document  on  https://angular.io/start/start-routing
There are some errors in the following code...

ngOnInit() {
  this.route.paramMap.subscribe(params => {
    this.product = products[+params.get('productId')];
  });
}

Should be changed to index minus one code

ngOnInit() {
    this.route.paramMap.subscribe(param =>{
      this.product = products[parseInt(param.get('productId'))-1];
    });
  }

🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑

**Comment by BohdanChernivtsi** [comment]
But doesn't it get the same result?
It works fine both ways

**Comment by zaranetCore** [comment]
> But doesn't it get the same result?
> It works fine both ways

no,Because the table below the data id in project.json starts at 0

**Comment by juanri0s** [comment]
> > But doesn't it get the same result?
> > It works fine both ways
> 
> no,Because the table below the data id in project.json starts at 0

Isn't the original issue then that the products in products.ts start at index 0, so the first product is shown when you use the route param of 0. If we just add -1, then we'll get undefined when the first product is selected since it'll be index -1. In it's current form, the code works. Also using the unary `+` is okay here.

**Comment by griosb8711** [comment]
I have the similary problem with the example https://angular.io/start/start-routing not show the fields detail product, help me please somebody

**Comment by juanri0s** [comment]
> I have the similary problem with the example https://angular.io/start/start-routing not show the fields detail product, help me please somebody

Hi try out this stackblitz example and let me know what specific issue you are running into. 
https://start-routing-docs-example.stackblitz.io

navigating to https://start-routing-docs-example.stackblitz.io/products/0 in the stackblitz browser should show the first products values since it's index 0.

**Comment by griosb8711** [comment]
> I have the similary problem with the example https://angular.io/start/start-routing not show the fields detail product, help me please somebody

I found the solution to my error, I only lacked in the view include *ngFor="let product of products; **index as productId**"

**Comment by kapunahelewong** [comment]
Status: Docs team, holding this one open for a bit to give @zaranetCore a chance to reply. 💻

**Comment by atscott** [comment]
Closing, as this appears to be working as expected and there have been no additional updates.
