### ISSUE TITLE
[Angular 9 - i18n] Cannot use empty strings as translations anymore

### ISSUE THREAD

**Issue by bravier** [angular/angular#36476]
# 🐞 bug report

### Affected Package

The issue is caused by package `@angular/localize` and/or Ivy (not sure).
The crash happens here: https://github.com/angular/angular/blob/416c786774dccc20d824737207be4e55cb53c9cc/packages/core/src/render3/hooks.ts#L74

### Is this a regression?

Yes, the last previous version in which this bug was not present was: Angular 8.2.14.

### Description

When translating an app in different locales, it may be wanted to translate some strings to `""`.
With Angular 8, it was possible to let some translation `<target status="final">` with empty value in XLIFF 1.2 files. The result would be an empty HTML element.
But with Angular 9, it seems not possible anymore. When a `<target>` is left empty and the corresponding bundle generated, [the app crashes at this line](https://github.com/angular/angular/blob/416c786774dccc20d824737207be4e55cb53c9cc/packages/core/src/render3/hooks.ts#L74) when the page containing the empty target is rendered:

    TypeError: Cannot read property 'directiveStart' of null

Please note that this crash only happens when the empty `<target>` concerns an HTML tag content. When the empty `<target>` concerns an HTML *attribute* translation, the app won't crash.

## 🔬 Minimal Reproduction

Minimal reproduction available at: https://github.com/bravier/ng9-i18n-empty-xliff-target

I've generated this example using `ng new myapp` and added `@angular/localize` using the [official documentation](https://angular.io/guide/i18n).
The `i18n` tagged span is [here](https://github.com/bravier/ng9-i18n-empty-xliff-target/blob/2cd013ac5f5e225895269fce9f34d874aceac5c8/src/app/app.component.html#L308).

Build steps:
- `npm install`
- `npm run build`
- `http-serve dist/myapp`
- Navigate to the `/fr/` build and look at the console.

## 🌍  Your Environment

**Angular Version:**
<pre><code>
Angular CLI: 9.1.0
Node: 10.15.0
OS: linux x64

Angular: 9.1.0
... animations, cli, common, compiler, compiler-cli, core, forms
... language-service, localize, platform-browser
... platform-browser-dynamic, router
Ivy Workspace: Yes

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.901.0
@angular-devkit/build-angular     0.901.0
@angular-devkit/build-optimizer   0.901.0
@angular-devkit/build-webpack     0.901.0
@angular-devkit/core              9.1.0
@angular-devkit/schematics        9.1.0
@ngtools/webpack                  9.1.0
@schematics/angular               9.1.0
@schematics/update                0.901.0
rxjs                              6.5.5
typescript                        3.8.3
webpack                           4.42.0
</code></pre>

**Comment by adrienverge** [comment]
Hello,

I have the same problem: `Cannot read property 'directiveStart' of null` with since Angular 9.

The crash happens because [inside `ɵɵelementEnd()`](https://github.com/angular/angular/blob/416c786774dccc20d824737207be4e55cb53c9cc/packages/core/src/render3/instructions/element.ts#L131), `previousOrParentTNode.parent` is `null` (a type forcer `!` is added to override this case, but it happens to be `null` anyway).
Then, `registerPostOrderHooks()` is [called with `previousOrParentTNode = null`, which shoudn't happen and creates the crash](https://github.com/angular/angular/blob/416c786774dccc20d824737207be4e55cb53c9cc/packages/core/src/render3/hooks.ts#L74).

The following diff in `@angular/core` suppresses the crash, but results in some HTML tags being closed prematurely:
```diff
--- a/packages/core/src/render3/instructions/element.ts
+++ b/packages/core/src/render3/instructions/element.ts
@@ -126,6 +126,8 @@ export function ɵɵelementEnd(): void {
   ngDevMode && assertDefined(previousOrParentTNode, 'No parent node to close.');
   if (getIsParent()) {
     setIsNotParent();
+  } else if (!previousOrParentTNode.parent) {
+    return;
   } else {
     ngDevMode && assertHasParent(getPreviousOrParentTNode());
     previousOrParentTNode = previousOrParentTNode.parent !;
```

@benlesh I think you wrote that code in commit 5a724b3, do you have any hints so we can debug further?

Thanks in advance.

**Comment by AndrewKushnir** [comment]
Hi @bravier and @adrienverge, thanks for reporting the issue and additional information on how to reproduce it.

I've created a [PR with proposed fix](https://github.com/angular/angular/pull/36499). PR still requires review and final implementation might change, but I'd like to ask if you could test your apps with the changes from that PR to check if apps work as expected with the fix.

I tested the fix with the repro provided by @bravier (thanks for creating it 👍) and it works correctly.

To test your app with the changes from PR #36499, please follow an instruction in [this document on how to use PR artifacts](https://github.com/angular/angular/blob/master/docs/DEVELOPER.md#archives-for-each-package). An archive with updated `@angular/core` package that contains changes from the PR is available [here](https://675319-24195339-gh.circle-artifacts.com/0/angular/core-pr36499-2576f36edf.tgz) (please make sure you update other `@angular` packages to `9.1.1` version to avoid version conflicts).

**Note**: the mentioned archive with updated `@angular/core` package is for **testing purposes only** and is not suitable for production usage (that archive will be removed once PR is closed).

Thank you.

**Comment by adrienverge** [comment]
Hello @AndrewKushnir, thanks for the rapid answer.

I couldn't test your change using the proposed method, because my app is not on 9.1.1 (I have to stay on 9.0 for other reasons). So I made the following patch from your PR (only the relevant parts), and applied it to my `node_modules`: [handle-empty-translations-correctly-pr36499-angular9.0.7.patch.txt](https://github.com/angular/angular/files/4448524/handle-empty-translations-correctly-pr36499-angular9.0.7.patch.txt)
For users that have the same problem, you can apply it directly for Angular 9.0 using:

    patch -p0 < handle-empty-translations-correctly-pr36499-angular9.0.7.patch.txt

Result: it works :tada: No more crash, and generated HTML is fine (no tags being closed prematurely).
Thanks @AndrewKushnir!

**Comment by bravier** [comment]
Hi @AndrewKushnir,

I was able to test your fix using @adrienverge's patch (I am still on 9.0.7) and I have the exact same results: no more crash and generated HTML looks as it was before in Angular 8.

Thank you for fixing it so quickly.

**Comment by AndrewKushnir** [comment]
Thanks for checking the fix @bravier and @adrienverge! 👍
I will keep this thread updated with the progress of the PR #36499.
