### ISSUE TITLE
bootstrapWebWorker is transpiled to bootstrapWebworker, which throws a TypeError. 

### ISSUE THREAD

**Issue by manekinekko** [angular/angular#3658]
Hi,
I just noticed something weird when playing around with the Web Worker modules. It is about `bootstrapWebWorker`.

The TypeScript function name is called `bootstrapWebWorker` (with two capital "W") but the generated JavaScript name seems to turn to `bootstrapWebworker` (one capital "W") which throws a TypeError.

Here is how to reproduce this:

#### bootstrap.ts
```typescript
/// <reference path="../typings/_custom.d.ts" />
import {bootstrap} from "angular2/src/web-workers/ui/application";
bootstrap('loader.js');
```

#### loader.ts
```typescript
/// <reference path="../typings/_custom.d.ts" />
import './worker';
```

#### worker.ts
```typescript
/// <reference path="../typings/_custom.d.ts" />
import {bootstrapWebWorker} from "angular2/src/web-workers/worker/application";
import {httpInjectables, formInjectables} from 'angular2/angular2'
import {routerInjectables} from 'angular2/router';

/*
 * App Component
 */
import {App} from './app';

bootstrapWebWorker(App, [httpInjectables, formInjectables, routerInjectables]);
// Uncaught TypeError: application_1.bootstrapWebWorker is not a function
```

See screenshot below.

![image](https://cloud.githubusercontent.com/assets/1699357/9286448/102d7b4c-42f4-11e5-963c-9165fedeb33f.png)

 I don't know if this is a TypeScript or Angular2 bug.

##### Versions information
- angular@2.0.0-alpha.34
- typescript@1.5.3

**Comment by jteplitz602** [comment]
Hey @manekinekko, how are you transpiling angular? Are you using our gulp tasks or running it through the TypeScript compiler yourself?

**Comment by manekinekko** [comment]
Hi @jteplitz602  I am using [angular-class repo](https://github.com/angular-class/angular2-webpack-starter). It uses webpack and the tasks are defined in the [package.json](https://github.com/angular-class/angular2-webpack-starter/blob/master/package.json#L6)

**Comment by jteplitz602** [comment]
It looks like this is an issue with our npm release. I'll investigate on Monday. For now, the easiest way for you to work around it is to build angular from source since this doesn't appear to be a problem when you build angular directly.:

1. Clone github.com/angular/angular
2. cd angular && npm install
3. gulp build.js.dev
4. Replace your current angular source with the source code generated in dist/js/dev/es5 | es6

**Comment by jteplitz602** [comment]
Sorry, this actually isn't a bug. We renamed bootstrapWebWorker in a1c53eec6bccaec145a7daef3f5211c4f9cb77eb, which hasn't landed in npm yet. This should be fixed in the alpha35 release.

WebWorker support is still under active development so we're going to be making breaking changes to it for a while. I'd recommend you build from source as part of your app's build pipeline if you plan to use WebWorkers because things are changing so frequently.

**Comment by manekinekko** [comment]
Sure! I understand. It is actually part of the [Universal](https://github.com/angular/universal/issues/85) project I'm contributing to.
