### ISSUE TITLE
AIO feature request: Add bold monospace within code examples

### ISSUE THREAD

**Issue by jbogarthyde** [angular/angular#36669]
# 📚 Docs or angular.io bug report

### Description
Requesting a markdown extension that would allow us to embed bold-monospace styling into a code example or snippet that is otherwise plain monospace font.

In code snippets and examples, it would be helpful to display some portions of the code in bold.
We would like to use bold to, for example, emphasize lines or options that are being added in an extended tutorial example, or emphasize specific structure or syntax in a conceptual discussion.

**Comment by petebacondarwin** [comment]
This feature is technically quite difficult to achieve - it has not been implemented by any standard markdown parser as far as I can tell, so there is no standard syntax to lean on.

In the AngularJS docs we had some ability to do this but it was awkward because the highlighted code blocks had to be specified "out of band" of the actual code block, which made it difficult for authors to maintain.

Possibly, when extracting doc-regions from external code blocks, we could come up with some way to mark up parts of the code that should be highlighted but again, this would be unwieldy.

There seems to be some views that instead of showing large blocks of code with highlights, it is actually better to UX to show smaller snippets with commentary, which is already well supported in our doc-gen.

So I am going to close this as something we are unlikely to implement.
