### ISSUE TITLE
Angular SSR

### ISSUE THREAD

**Issue by hugoebarboza** [angular/angular#36663]
Hi,

I build with (SSR) with Angular Universal, I get the below error.
********************************************************************************
ERROR in error TS6053: File 'C:/xampp/htdocs/odisdkp/src/server.ts' not found.
npm ERR! code ELIFECYCLE, errno 1
npm ERR! Exit status 1
npm ERR! Failed at the odisdkp@0.0.0 build:ssr script.
npm ERR! This is probably not a problem with npm. 
npm ERR! A complete log of this run can be found in:
npm ERR! C:\Users\Hugo Barboza\AppData\Roaming\npm-cache\_logs\2020-04-16T12_34_35_799Z-debug.log
********************************************************************************

But, this [guide](https://angular.io/guide/universal) describes the folder structure and its no in 'src/'

Best regards,
Hugo

**Comment by gkalpak** [comment]
The SSR guide is a little outdated wrt v9. This will be fixed by #36483.

Until #36483 is merged, you can use the PR preview: https://pr36483-928dd02.ngbuilds.io/guide/universal
<sub>(Once the PR is merged, the preview will be deleted, but you will be able to see the guide on angular.io as usual.)</sub>
