### ISSUE TITLE
animation sequence not running in sequence

### ISSUE THREAD

**Issue by fxck** [angular/angular#36671]
### Description

Wrapper div with `@animation`, two inner divs with flipped `*ngIf` condition.

Expected behaviour of sequence would be:
First div is transitioned away THEN second div is transitioned in.

Actual behaviour: 
Second div is added immediately, first div fades away (but is still present in dom), second div flashes away and fades in, first div is removed from dom.

## 🔬 Minimal Reproduction
https://stackblitz.com/edit/angular-animation-sequence-1?file=src/app/app.component.ts

## 🌍  Your Environment

**Angular Version:**
9.2.0

**Comment by matsko** [comment]
This is expected. Any call to `sequence()` will execute things in a serial fashion one step after another. Because the calls to `query()` are fired one after the other and because the first `query()` has an `animate()` step before the next element is animated, the `:enter` element is just rendered onscreen as is (it's inserted into the DOM at the start of the animation).

The solution to this is to decorate the call to the `:enter` element with `style()` call to hide it: 
https://stackblitz.com/edit/angular-animation-sequence-1-1vpatw?file=src/app/app.component.ts

Closing.
