### ISSUE TITLE
Add FormControl to FormArray

### ISSUE THREAD

**Issue by souhailharrati** [angular/angular#36695]
I have a problem of adding FormControl to FormArray without FormBuilder:
-  the 2 nd FormControl takes the values of the previous FormControl

**in component ts:**
```
 const EMPLOYEE_FORM = {
    firstName: new FormControl('', Validators.required),
    lastName: new FormControl('', Validators.required)
}
const COMPANY_FORM = {
  employees: new FormArray([], [Validators.required])
}


constructor() {
   this.form = new FormGroup(COMPANY_FORM);
 }
  get employees(): FormArray {
    return this.form.get('employees') as FormArray;
  }

addEmployee() {
      const employee = new FormGroup(EMPLOYEE_FORM);
      this.employees.push(employee);
  }
```

**In component html**
```

<div *ngFor="let item of employees.controls;">
<form [formGroup]="item">
<input type="text"  formControlName="firstName" class="form-control" placeholder="FirstName">
<input type="text"  formControlName="lastName" class="form-control" placeholder="LastName">
  </form>
</div>
 <button (click)="addEmployee()">add new employee</button>

```
- See this link: https://stackblitz.com/edit/add-input-to-formarray-without-frombuilder

but if i use the FormBuilder everything is going well
- example: https://stackblitz.com/edit/add-input-to-formarray-with-frombuilder

**Comment by AndrewKushnir** [comment]
Hi @souhailharrati,

I looked at the code and it seems to be working as expected. The problem is that the `EMPLOYEE_FORM` object (and as a result, `FormControl` instances) are reused for all items in the `employees` array. The problem doesn't happen with `FormBuilder`, since new instances of the `FormGroup` are created based on the spec defined as an array.

In order to fix the problem, you can update the `EMPLOYEE_FORM` object to a function that would return the necessary object, for example like this:

```typescript
const getEmployeeForm = () => ({
    firstName: new FormControl('', Validators.required),
    lastName: new FormControl('', Validators.required)
});
```
and after that call this function in the add employee function:
```typescript
addEmployee() {
    const employee = new FormGroup(getEmployeeForm());
    this.employees.push(employee);
 }
```
Thank you.

**Comment by souhailharrati** [comment]
Hi @AndrewKushnir 
everything is clear thank you very much
