### ISSUE TITLE
No documentation on how to exclude certain routes from prerender. Angular Universal 9

### ISSUE THREAD

**Issue by VenomApps** [angular/angular#36728]
# 📚 Docs or angular.io bug report

### Description

 A clear and concise description of the problem...

### What's the affected URL?**
 https://angular.io/...

## 🔥 Exception or Error
<pre><code>

</code></pre>

**Comment by dgvozd** [comment]
👍

**Comment by kapunahelewong** [comment]
Thanks for this, @VenomApps! Would you have any more thoughts, such as specific questions you'd like to see answered in the new documentation? This is totally new info for me, so the more I have to work with the more efficient I can be there helping this move. (This invitation stands for anyone else who visits this issue too!)

Status: docs team will need engineering SME to create new documentation on this.

**Comment by Mario0419** [comment]
Any status on this? I'm also looking for a way to exclude certain routes from angular. I want angular to ignore specific sub-routes, so I can use other applications (wordpress) with it.

**Comment by jankalthoefer** [comment]
@kapunahelewong So for my usecase I have an existing angular app which I want to extend with some static pages (simple landingpages in my case). My first idea was to build these static pages and prerender only these routes. 
The problem is I couldn't find out how to render only specific pages nor how I could exclude pages from being prerendered.

If anyone else has any advice I would be super happy ✌🏼

**Comment by helix46** [comment]
@jankalthoefer same here, exactly my case
Until that is possible I use 
https://github.com/chrisguttandin/angular-prerender

**Comment by aikidave** [comment]
Thank you for this information! I've taken note of this issue and I've put in our documentation backlog so I can discuss it with the product team.

**Comment by bierzorutas** [comment]
I am also very interesting in this feature

**Comment by wagnermaciel** [comment]
Hi everyone! I'm going to start working on this but in the meantime, the best "documentation" for how to do this can be found here: https://github.com/angular/universal/blob/master/modules/builders/src/prerender/schema.ts

Those are all the options you can pass in via angular.json. The ones that are probably most helpful to you all are `routes`, `routesFile`, and `guessRoutes`. You can define those options via your `angular.json` file like this:

```json
"prerender": {
        "builder": "@nguniversal/builders:prerender",
        "options": {
                "browserTarget": "demo:build:production",
                "serverTarget": "demo:server:production",
                "routes": [],
                "routesFile": "./routes-file.txt",
                "guessRoutes": false,
        },
        "configurations": {
                "production": {}
        }
}
```

While there's no option to exclude specific routes, you can instead specify what routes you'd like to prerender via the `routes` option or the `routesFile` option (if you have a lot of routes). I'd also recommend setting `guessRoutes` to false so that you are only prerendering the routes you are explicitly defining.

If having an option like `excludedRoutes` is something that interests you, I would suggest opening a feature request issue in the Angular Universal repo: https://github.com/angular/universal/issues
