### ISSUE TITLE
Angular9 Upgrade | Build Prod Failed

### ISSUE THREAD

**Issue by HanaaGhasoub** [angular/angular#36727]
Angular Version: 9
After upgrade from 8 to 9 the build its working fine locally, **but when run build prod it fails**.
Please help me with that as soon as.
![image](https://user-images.githubusercontent.com/30862539/79797298-4cacae00-8357-11ea-9787-82099759868a.png)

My tsconfig.ts
![image](https://user-images.githubusercontent.com/30862539/79797470-939aa380-8357-11ea-843d-2d0c85ddf896.png)

Package.json build scripts
![image](https://user-images.githubusercontent.com/30862539/79797535-b4fb8f80-8357-11ea-827f-489499308cc7.png)

**Comment by AndrewKushnir** [comment]
Hi HanaaGhasoub,

Thanks for reporting this issue. However, you didn't provide sufficient information for us to understand and reproduce the problem. Please check out [our submission guidelines](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-submitting-an-issue) to understand why we can't act on issues that are lacking important information.

Could you please provide a minimum repro in a form of GitHub repo, so that we can try to reproduce the issue?

**Comment by HanaaGhasoub** [comment]
Hi @AndrewKushnir,
Thanks for your notes. I had faced the problem with a package not supported by angular 9 which the project modules depend on it, so I did a workaround for it and its working great now for local build or production build.
The package caused the problem is "**TimeAgoPipe**".
The solution:

- Declare pipe depend on TimeAgoPipe as below
![image](https://user-images.githubusercontent.com/30862539/80028624-b064e180-84e5-11ea-8016-39b7e0d4ad20.png)

- Add the custom "**TimeAgoExtendsPipe**" to the app module declaration instead of "**TimeAgoPipe**".
![image](https://user-images.githubusercontent.com/30862539/80028701-cf637380-84e5-11ea-9495-b08f6b87606a.png)

The Result: Angular build prod succeed.
