### ISSUE TITLE
Dynamically created components do not raise reactive form events

### ISSUE THREAD

**Issue by jonnysmith1981** [angular/angular#36740]
# 🐞 bug report

### Affected Package
@angular/forms

### Is this a regression?

Unknown

### Description

We have a set of custom components that implement the ControlValueAccessor interface. When we add these controls at design-time to a form, all the value accessor and validation functions work fine.
When these controls are created at run time and added to the FormGroup, the initial value is not set and validation and valueChange events do not get raised.

## 🔬 Minimal Reproduction
Stackblitz demo can be found here: https://stackblitz.com/edit/dynamic-component-validation

The demo has one component added at design time and one at run time. The component added at runtime does not show the correct number of stars and the validator function never fires.

## 🔥 Exception or Error
No errors are thrown.

## 🌍  Your Environment

**Angular Version:**
From package.json
<pre><code>
    "@angular/animations": "9.1.0",
    "@angular/common": "^9.1.0",
    "@angular/compiler": "^9.1.0",
    "@angular/core": "^9.1.0",
    "@angular/forms": "^9.1.0",
    "@angular/platform-browser": "^9.1.0",
    "@angular/platform-browser-dynamic": "^9.1.0",
    "@angular/router": "^9.1.0",
    "core-js": "^3.6.4",
    "rxjs": "^6.5.4",
    "tslib": "^1.10.0",
    "zone.js": "^0.10.3"
</code></pre>

**Comment by destus90** [comment]
I wonder why this should work? It seems, to me, that you just set the input property `formCotnrolName`. The corresponding `FormControlName` directive class  is never created. I think you can create a dynamic component  using it inside the `<ng-template>` element. The working demo can be found here https://stackblitz.com/edit/dynamic-component-validation-r5dxvt?file=src/app/app.component.ts

**Comment by jonnysmith1981** [comment]
If i need to explicitly put the component into the template then it's no longer dynamic.

**Comment by AndrewKushnir** [comment]
Hi @jonnysmith1981, thanks for providing a repro.

The approach that you have would not work, since you set `formControlName` property in `ngOnInit` hook when all directive matching already happened based on the information in the template. The use-case that you described reminds me of the [Dynamic Forms guide](https://angular.io/guide/dynamic-form) that you can look at to see if it fits your requirements. There is also a solution provided by @destus90, which also seems to work.

It looks like there are no action items for Framework in this case, so I'm closing this ticket.

Thank you.
