### ISSUE TITLE
enableIvy: true Hostlistener is not working

### ISSUE THREAD

**Issue by cihankaya77** [angular/angular#36782]
# 🐞 bug report

### Description

  
**"enableIvy: true"**
Hostlistener is not firing when eventemitter and hostlistener are on the same component.
**"enableIvy: false"**
Hostlistener is firing when eventemitter and hostlistener are on the same component.

## 🔬 Minimal Reproduction
 https://stackblitz.com/edit/angular-4ziymy

## 🔥 Exception or Error
<pre><code>

</code></pre>

## 🌍  Your Environment

**Angular Version:**
<pre><code>

     _                      _                 ____ _     ___
    / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
   / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
  / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
 /_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
                |___/
    

Angular CLI: 9.1.1
Node: 12.13.1
OS: win32 x64

Angular: 9.1.2
... animations, common, compiler, compiler-cli, core, forms
... localize, platform-browser, platform-browser-dynamic, router
Ivy Workspace: Yes

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.901.1
@angular-devkit/build-angular     0.901.1
@angular-devkit/build-optimizer   0.901.1
@angular-devkit/build-webpack     0.901.1
@angular-devkit/core              9.1.1
@angular-devkit/schematics        9.1.1
@angular/cli                      9.1.1
@angular/http                     7.2.16
@ngtools/webpack                  9.1.1
@schematics/angular               9.1.1
@schematics/update                0.901.1
rxjs                              6.5.5
typescript                        3.8.3
webpack                           4.42.0
</code></pre>

**Anything else relevant?**

**Comment by AndrewKushnir** [comment]
Thanks for reporting the issue @cihankaya77 and providing a repro.

This issue might be related to #36716.

**Comment by pkozlowski-opensource** [comment]
Here is a slightly modified / simplified reproduction: https://stackblitz.com/edit/angular-4ziymy?file=src%2Fapp%2Fapp.component.ts

I looked a bit into this issue and we do indeed have discrepancy with older Angular versions (VE) behaviour. having said this, I would argue that Angular v9 with ivy enabled behaviour "makes more sense". I'm saying this since it is very easy for a component / directive to "listen to its own events". More than this - it is _easier_ for a component / directive to just call a method in a directive / component instead of going through the indirection layer of EventEmitter and host listener. 

Here is a way of doing the same thing that would work in both VE and ivy (and is simpler imo):
https://stackblitz.com/edit/angular-ctctma?file=src/app/app.component.ts

@cihankaya77 does the above works for you?

**Comment by jessicajaniuk** [comment]
It appears this behaves as expected. If you still feel there is an issue, please provide further details in a new issue.
