### ISSUE TITLE
Event binding syntax sugar for references; e.g. `<foo (myEvent)="myVar">`

### ISSUE THREAD

**Issue by tiziano88** [angular/angular#3680]
I would expect that `<foo (myEvent)="myVar">` should desugar to something like `<foo (myEvent)="myVar = $event">` if RHS is a ref. AFAICT this is more or less what already happens for "fake" two-way bindings such as `<foo [(myEvent)]="myVar">`, but more generic (works for one-way bindings).

If implemented, this pattern would then appear be very useful for propagating data one-way from children to parent components.

**Comment by mhevery** [comment]
1) I think you mean `<foo (my-event)="myVar">` since DOM attributes are case insensitive.
2) I think auto assigning `$event` to the expression is too much magic, and I don't think it would be that useful for most events.  If that is what you are looking for use `[()]` syntax which does that.

For now we prefer explicit over implicit magic, so we will pass on this.

**Comment by tiziano88** [comment]
For the record, an alternative, more explicit syntax for one-way event-driven bindings could be the following `<foo ((my-event))="myVar">`, which would translate directly into `<foo (my-event)="myVar = $event">`, and would nicely complement the existing one- and two-way bindings. Probably not very relevant anyway unless many users ask for it or we can come up with a more compelling use case.
