### ISSUE TITLE
MessageBus should be abstract

### ISSUE THREAD

**Issue by jteplitz602** [angular/angular#3683]
Currently, MessageBus is an interface which means that we can't bind to it with DI. TypeScript 1.6 adds abstract classes to the language, so once that is released we should make MessageBus an abstract class.

**Comment by mhevery** [comment]
FYI: You should not name things as `IFoo` or `FooInterface`

**Comment by jteplitz602** [comment]
@mhevery What should they be named?

**Comment by mhevery** [comment]
I am refactoring this code now. In general It is `List` not `ListInterface` since concrete classes are `ArrayList`, `LinkedList` not `ListImpl`. If all you have is `IFoo` and `FooImpl` then there is no need for an interface. If you have hard time for coming up with a abstract name for interface then it is a sign there should not be an interface.
