### ISSUE TITLE
Number decimal separator and grouping separator

### ISSUE THREAD

**Issue by adrian-pavel** [angular/angular#36880]
Hello,

For en-150 (English Europe) shouldn't the number format be 123.456,789 , instead of 123,456.789 ?

https://github.com/angular/angular/blob/49be32c9315a5c7ff155c5b88191e504006f595b/packages/common/locales/en-150.ts#L46

**Comment by petebacondarwin** [comment]
According to https://www.ctrl.blog/entry/en-001.html 

> “English (Europe)”, or en-150, as defined in CLDR is equivalent to “English (world)” with the following exceptions:
> 
> Uses a comma instead of a period for decimal separator.
> Uses a 24-hour instead of 12-hour time format.
> Currency symbol is ¤ instead of US$.

But https://github.com/unicode-cldr/cldr-numbers-modern/blob/master/main/en-150/numbers.json seems to think otherwise, regarding the decimal separator.

```json
        "symbols-numberSystem-latn": {
          "decimal": ".",
          "group": ",",
          "list": ";",
          "percentSign": "%",
          "plusSign": "+",
          "minusSign": "-",
          "exponential": "E",
          "superscriptingExponent": "×",
          "perMille": "‰",
          "infinity": "∞",
          "nan": "NaN",
          "timeSeparator": ":"
        },
```

If the former is correct then it would also need to define a new grouping separator, since the "world" grouping separator is `,` which would be confused with the decimal separator. (See https://github.com/unicode-cldr/cldr-numbers-modern/blob/master/main/fr/numbers.json for an example.) I don't read anywhere in the first article about changing the grouping separator and certainly not to the `.` character.

In any case, since Angular simply uses whatever is in the CLDR, any issue with locale data must be taken up with the CLDR project.
