### ISSUE TITLE
Problem with 'few' value using NgPlural

### ISSUE THREAD

**Issue by juanjinario** [angular/angular#36935]
# 🐞 bug report

### Affected Package

 The issue is caused by package @angular/../i18n/localization

### Description

 
I am using the directive [ngPlural] my code is as follows 
```
<label [ngPlural]="viewFlight.nights">
   <ng-template ngPluralCase="=1" i18n="@@predictor_itinerary_night">noche</ng-template>
   <ng-template ngPluralCase="few" i18n="@@predictor_itinerary_nights">noches</ng-template>
</label>
```
According to the documentation (https://angular.io/api/common/NgPlural) The code should work

Also in angular.json> build> options> I have set the default language of the application as:
`"i18nLocale": "es"`
I don't know if this is important since I can't think of anything else.,

## 🔥 Exception or Error
<pre>Error: No plural message found for value "3"<code>
// The error appears with any value greater than 1

</code></pre>

## 🌍  Your Environment

**Angular Version:**
<pre>9.0.5<code>

</code></pre>

**Anything else relevant?**

**Comment by petebacondarwin** [comment]
I think the problem is with the documentation.

First of all, if none of the cases match then it will try to match `other` and throw otherwise. If you add an `other` case then it will not crash: https://ng-run.com/edit/YhQbM22gRfQ3892eM4eN

Second, the default locale ("en-US") and the "es" locale have very simple `plural()` functions, which do not support "few":

[en-US](https://github.com/angular/angular/blob/ecffc3557fe1bff9718c01277498e877ca44588d/packages/core/src/i18n/locale_en.ts#L15-L18):

```
function plural(n: number): number {
  let i = Math.floor(Math.abs(n)), v = n.toString().replace(/^[^.]*\.?/, '').length;
  if (i === 1 && v === 0) return 1;
  return 5;
}
```

[es](https://github.com/angular/angular/blob/ecffc3557fe1bff9718c01277498e877ca44588d/packages/common/locales/es.ts#L14-L17):

```
function plural(n: number): number {
  if (n === 1) return 1;
  return 5;
}
```

So the `few` option will never match.

**Comment by juanjinario** [comment]
Simply put, the problem is in the documentation. Yesterday debugging I realized that in the locations function it compares the prural against "other"
```
key = ngLocalization.getPluralCategory(value, locale);
  if (cases.indexOf(key) > -1) {
    return key;
  }
  if (cases.indexOf('other') > -1) {
    return 'other';
  }
  throw new Error(`No plural message found for value "${value}"`);
```

**Comment by kapunahelewong** [comment]
cc @rockument69 

Status: docs team, I believe there's enough here to update the docs. Thank you, @petebacondarwin and @juanjinario!

**Comment by rockument69** [comment]
The [i18n guide](https://angular.io/guide/i18n#regular-expressions-for-plurals-and-selections) mentions `few` but does not try to show which pluralization categories are supported/not supported for each language. I don't know of such a list.

The API doc for [ngPlural](https://angular.io/api/common/NgPlural) does not mention `few`. It provides a link to the plural rules ([Unicode CLDR](http://cldr.unicode.org/index/cldr-spec/plural-rules)), where some different language exceptions are noted. 

The solution may be to add the link for [choosing plural category names](http://cldr.unicode.org/index/cldr-spec/plural-rules#TOC-Choosing-Plural-Category-Names) to both the [i18n guide](https://angular.io/guide/i18n#regular-expressions-for-plurals-and-selections) and the [ngPlural](https://angular.io/api/common/NgPlural) API doc.

@petebacondarwin : Need engineering to confirm this solution.

**Comment by petebacondarwin** [comment]
@rockument69 - I think adding these links would be helpful, but we should make it clear that most locales do not support many of the options. We should also point out that `other` should always be implemented since that is the standard fallback for a missing option.

The detail is that the case is computed by calling the `getPluralCase()` function:

```ts
const pluralMapping = ['zero', 'one', 'two', 'few', 'many'];

/**
 * Returns the plural case based on the locale
 */
export function getPluralCase(value: string, locale: string): string {
  const plural = getLocalePluralCase(locale)(parseInt(value, 10));
  const result = pluralMapping[plural];
  return (result !== undefined) ? result : 'other';
}
```

You can see that this will return one of `['zero', 'one', 'two', 'few', 'many']` or `'other'` based on a call to the function returned from `getLocalePluralCase()`. This function is defined in the locale data file of the given locale. For example, in the [ar-AE locale file](https://github.com/angular/angular/blob/d1ea1f4c7f3358b730b0d94e65b00bc28cae279c/packages/common/locales/ar-AE.ts#L14-L21):

```ts
function plural(n: number): number {
  if (n === 0) return 0;
  if (n === 1) return 1;
  if (n === 2) return 2;
  if (n % 100 === Math.floor(n % 100) && n % 100 >= 3 && n % 100 <= 10) return 3;
  if (n % 100 === Math.floor(n % 100) && n % 100 >= 11 && n % 100 <= 99) return 4;
  return 5;
}
```

Note that the numbers returned correspond to the index into the `['zero', 'one', 'two', 'few', 'many']` array.

But also note that the vast majority of locales implement a much more simple `plural()` function such as:

```ts
function plural(n: number): number {
  let i = Math.floor(Math.abs(n)), v = n.toString().replace(/^[^.]*\.?/, '').length;
  if (i === 1 && v === 0) return 1;
  return 5;
}
```

See that in this case the function will only ever return `1` (`'one'`) or `5` (`'other'`).

**Comment by rockument69** [comment]
@petebacondarwin : Thanks! Now I understand what to add to the i18n doc -- PR [36924](https://github.com/angular/angular/pull/36924) (docs: Refactor-i18n-DOCS-758). The ngPlural API doc doesn't mention these options, but I can propose adding a link in that doc to point to the i18n doc for details.

**Comment by rockument69** [comment]
PR [36924](https://github.com/angular/angular/pull/36924) (docs: Refactor-i18n-DOCS-758) now has improved description in the "Mark plurals" section:

> <div class="callout is-important">
> <header>Locales may not support some pluralization categories</header>
> 

> Many locales don't support some of the pluralization categories.
> For example, the default locale (`en-US`) and other locales (such as `es`) have very simple `plural()` functions that don't support the `few` category.
> The following shows the [en-US](https://github.com/angular/angular/blob/ecffc3557fe1bff9718c01277498e877ca44588d/packages/core/src/i18n/locale_en.ts#L15-L18) `plural()` function:
> 
> ```
> function plural(n: number): number {
>   let i = Math.floor(Math.abs(n)), v = n.toString().replace(/^[^.]*\.?/, '').length;
>   if (i === 1 && v === 0) return 1;
>   return 5;
> }
> ```
> 
> The function will only ever return 1 (`one`) or 5 (`other`).
> The `few` category will never match.
> If none of the pluralization categories match, Angular will try to match `other`. 
> Use `other` as the standard fallback for a missing category.
> 
> For more information about pluralization categories, see [Choosing plural category names](http://cldr.unicode.org/index/cldr-spec/plural-rules#TOC-Choosing-Plural-Category-Names) in the CLDR - Unicode Common Locale Data Repository.
> 
> </div>

**Comment by rockument69** [comment]
PR [36924](https://github.com/angular/angular/pull/36924) (docs: Refactor-i18n-DOCS-758) closes this issue.
