### ISSUE TITLE
Components that extend JS's `Array` class cause two issues

### ISSUE THREAD

**Issue by vinayluzrao** [angular/angular#37059]
# 🐞 bug report

### Affected Package
The issue is caused by package @angular/core.

### Is this a regression?
I don't know if the `.slice()` issue is a regression. The `@ViewChild` issue was happening in angular 8 as well.

### Description
1) When annotating a component that extends JS's `Array` class, `@ViewChild` fails to grab the reference (the property remains undefined).

2) When calling `.slice()` on a component that extends JS's `Array` class, the component's class's constructor is called with 0 as its only argument, instead of calling the `.slice()` method.
## 🔬 Minimal Reproduction
https://github.com/vinayluzrao/angular-issue-component-that-is-subclass-of-array-minimal-reproducible-example

To reproduce the issues, run ng serve. The console logs make them explicit.

## 🌍  Your Environment
**Angular Version:9.02**
<pre><code>
     _                      _                 ____ _     ___
    / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
   / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
  / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
 /_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
                |___/
    

Angular CLI: 9.0.3
Node: 12.16.1
OS: linux x64

Angular: 9.0.2
... common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router
Ivy Workspace: Yes

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.803.25
@angular-devkit/build-angular     0.900.3
@angular-devkit/build-optimizer   0.900.3
@angular-devkit/build-webpack     0.900.3
@angular-devkit/core              9.0.3
@angular-devkit/schematics        9.0.3
@angular/cli                      9.0.3
@ngtools/webpack                  9.0.3
@schematics/angular               8.1.3
@schematics/update                0.900.3
rxjs                              6.5.4
typescript                        3.7.5
webpack                           4.41.2
</code></pre>

**Anything else relevant?**
No.

**Comment by pkozlowski-opensource** [comment]
@vinayluzrao there is quite a bit going on in the linked reproduction repository and it seems like you are reporting 2 separate problems in one issue, which is confusing.

Let me focus on the first problem here: 

> When annotating a component that extends JS's Array class, @ViewChild fails to grab the reference (the property remains undefined).

I've checked your repo and I'm _assuming_ that we are talking about the `@ViewChild` query here:
https://github.com/vinayluzrao/angular-issue-component-that-is-subclass-of-array-minimal-reproducible-example/blob/master/src/app/my-array.component.ts#L11

If so, I'm confused since this component's template only has `<p>` tag and there is no `DynamicComponentHostDirective ` matching in this template. As such the query in question can't pick up anything... 

Could you please try to:
* provide us with the live reproduce scenario using https://stackblitz.com/
* simplify the reproduce scenario (please focus on one problem at the time);
* make sure that you are checking with the latest version of Angular.

This issue, as it stands tight now, is rather confusing and hard to move forward on our end.

**Comment by pkozlowski-opensource** [comment]
I'm going to close this issue for now as I haven't heard back from the author.
