### ISSUE TITLE
Weird Interaction with $location.hash() and Chrome/Firefox

### ISSUE THREAD

**Issue by bobber205** [angular/angular#372]
When I enter the following into Chrome
```
http://www.example.com/enter/contest#top
```
it turns into

```
http://www.example.com/enter/contest/#top
```

This also happens when just running ```$location.hash("top")``` without any hashes in the URL.

This causes ```$location.hash()``` to be ```""```. I need this check because if I do ```$location.hash("top")``` in any repeated function I get ```#top#top```. I have a simple "is it already ```'top'``` if check but since chrome messes with the url, it's always blank.

```
$location.hash("top");
$anchorScroll();
```
makes the url fwiw

```
http://www.example.com/enter/contest/#top#top
```

Any ideas of a work around?

**Comment by caitp** [comment]
@bobber205 do you think you could re-open this issue on https://github.com/angular/angular.js? That would be fantastic =)

We are definitely doing the wrong thing with this rewriting, because we're changing a file URL into a directory URL, which backends won't always (or even usually) treat as identical. So, this probably warrants some investigation.

**Comment by bobber205** [comment]
Now lives at https://github.com/angular/angular.js/issues/10659 :)

**Comment by caitp** [comment]
:sparkles:
