### ISSUE TITLE
HTML element inside svg:foreignObject  throw error

### ISSUE THREAD

**Issue by vraddy** [angular/angular#37218]
### Description
Adding HTML element inside svg foreignObject is throwing error
Template parse errors:
':svg:div' is not a known element:
1. If ':svg:div' is an Angular component, then verify that it is part of this module.
2. To allow any element add 'NO_ERRORS_SCHEMA' to the '@NgModule.schemas'

Adding angular component inside svg foreignObject doesn't throw error but component is not displaying, component is complied but looks not appended to DOM.

https://stackblitz.com/edit/angular-issue-repro2-bs4jyv

Adding HTML elements inside svg foreignObject in HTML page works fine(non angular project)
https://www.w3schools.com/code/tryit.asp?filename=GEZ53W6RC4Z1

## 🌍  Your Environment

Angular: 6
Browser: Chrome 81

**Comment by pkozlowski-opensource** [comment]
A simpler reproduce scenario (to have it exactly corresponding to the linked scenario without Angular): https://stackblitz.com/edit/angular-ivy-jmk9kp

I can confirm that it looks like a valid bug in Angular template parser. Thnx for reporting!

**Comment by vraddy** [comment]
Thanks! i have more importance to angular component inside svg:foreignObject not displayed.
following is the reproduce link of this in simple version.
https://stackblitz.com/edit/angular-issue-repro2-8v1ovo

**Comment by pkozlowski-opensource** [comment]
> svg:foreignObject not displayed following is the reproduce link of this in simple version.

@vraddy we are confusing the conversation here a bit by discussing 2 separate issues, I'm afraid. So, the problem that you are raising here is that Angular will create a HTML element corresponding to a component (`<svg-test>` in your example) that we call host element. The issue is that `<svg-test>` is not a valid element that can be used with SVGs hence a browser doesn't render it. This is a well known issue with SVG support in Angular. It can be worked around by using an attribute selector for a component:
https://stackblitz.com/edit/angular-issue-repro2-kmk65j?file=src%2Fapp%2Fapp.component.ts

To sum, we've got 2 problems here:
* Angular creating host element that doesn't play nice with SVG use-cases
* Angular template parser bug when ones put a `<div>` inside `<foreignObject>`. Reproduction:  https://stackblitz.com/edit/angular-ivy-jmk9kp

**Comment by vraddy** [comment]
Sorry to put two issues in one thread @pkozlowski-opensource , 
my actual issue was host component was not rendering inside svg:foreignObject(since i was not aware of svg support in angular only as attribute, i was trying to do it in foreignObject as element) from your example it is clear now.. i can get this working by attribute selector, problem solved!

about the <div> inside <foreignObject>, this is not my actual issue, since host component was not rendered inside foreignObject, i was trying to experiment with HTML element and caught this comparison working in HTML page and not working in angular project given that information as extra in bug report.

To sum:
Angular creating host element that doesn't play nice with SVG use-cases - attribute component works, solved for me!
Angular template parser bug when ones put a <div> inside <foreignObject> - I don't have any use case of this, it was extra information for bug report.

Thanks!

**Comment by Abk-MI** [comment]
**Hello, you just need to add the xhtml to any html element inside the <foreingObject> like this <xhtml:p> type any text here.... </xhtml:p> or <xhtml:div class=""> ..... </xhtml:div>**


`<svg viewBox="0 0 200 200" xmlns="http://www.w3.org/2000/svg">
        <path fill="blue" d="M140 31c10 13 14 28 19 41 5 14 12 27 12 39-1 12-9 24-18 33-10 9-22 15-34 18-13 3-26 4-38 1s-24-9-36-18-25-20-29-34 1-30 8-46 15-32 28-43C64 11 82 6 99 8c16 2 32 11 41 23z"/>
        <foreignObject x="10" y="50" width="160" height="160" xmlns="http://www.w3.org/1999/xhtml">
            <xhtml:p>
                Hello, try this one...
            </xhtml:p>
        </foreignObject>
    </svg>`
