### ISSUE TITLE
JIT Compiler Bug : ViewChild not work

### ISSUE THREAD

**Issue by BubbleLeaf** [angular/angular#37244]
### Description
hi，I compil a component in the runtime with JIT compiler . The code is is listed below :

```
render() {
    var template: string = `
    <div #demo1>11</div>
    `
    class dynamicComponent implements OnInit {
      constructor() {
      }

      ngOnInit() {
        console.log(this.demo1.element);
      }


      @ViewChild('demo1', { read: ViewContainerRef, static: false })
      demo1: ViewContainerRef;
    }

    Component({
      selector: 'demo',
      template: template,
      styles: [``]
    })(dynamicComponent);

    class dynamicModule {
    }

    NgModule({
      imports: [CommonModule],
      declarations: [dynamicComponent],
      entryComponents: [dynamicComponent]
    })(dynamicModule);
    const all = this.compiler.compileModuleAndAllComponentsSync<any>(dynamicModule);
    const componentFactory = all.componentFactories.find(factory => factory.componentType === dynamicComponent);
    let com = componentFactory.create(this.injector);
    this.container.insert(com.hostView);
  }

```

I use ViewChild to get the element demo1,but I get undefined . I look into the code compiled , I found it treat my component as a directive and never ran the code that to find the demo1 element .  This is terrible .
![image](https://user-images.githubusercontent.com/16011072/82579747-d18e2000-9bc0-11ea-9ede-e86adb6c5995.png)

## 🌍  Your Environment

**Angular Version:**
<pre><code>
Angular CLI: 9.1.6
Node: 12.16.2
OS: win32 x64

Angular: 9.1.7
... animations, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, router
Ivy Workspace: Yes

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.901.6
@angular-devkit/build-angular     0.901.6
@angular-devkit/build-optimizer   0.901.6
@angular-devkit/build-webpack     0.901.6
@angular-devkit/core              9.1.6
@angular-devkit/schematics        9.1.6
@angular/cdk                      9.2.3
@angular/cli                      9.1.6
@ngtools/webpack                  9.1.6
@schematics/angular               9.1.6
@schematics/update                0.901.6
rxjs                              6.5.5
typescript                        3.8.3
webpack                           4.42.0
</code></pre>

**Anything else relevant?**
The code compiled is here .
```
var template = `
    <div #demo1></div>
    `;
        class dynamicComponent {
            constructor() {
            }
            ngOnInit() {
                //console.log(this.tw.stop());
                // ViewChild('demo', { read: ViewContainerRef, static: true })(dynamicComponent, 'demo');
                // console.log();
                console.log(this.demo1.element);
            }
        }
        dynamicComponent.ɵfac = function dynamicComponent_Factory(t) { return new (t || dynamicComponent)(); };
        dynamicComponent.ɵdir = _angular_core__WEBPACK_IMPORTED_MODULE_0__["ɵɵdefineDirective"](
            { type: dynamicComponent, 
                viewQuery: function dynamicComponent_Query(rf, ctx) {
                     if (rf & 1) {
                _angular_core__WEBPACK_IMPORTED_MODULE_0__["ɵɵviewQuery"](_c0, true, _angular_core__WEBPACK_IMPORTED_MODULE_0__["ViewContainerRef"]);
            } if (rf & 2) {
                var _t;
                _angular_core__WEBPACK_IMPORTED_MODULE_0__["ɵɵqueryRefresh"](_t = _angular_core__WEBPACK_IMPORTED_MODULE_0__["ɵɵloadQuery"]()) && (ctx.demo1 = _t.first);
            } } 
        });
        Object(_angular_core__WEBPACK_IMPORTED_MODULE_0__["Component"])({
            selector: 'demo',
            template: template,
            styles: [``]
        })(dynamicComponent);
        class dynamicModule {
        }
        Object(_angular_core__WEBPACK_IMPORTED_MODULE_0__["NgModule"])({
            imports: [_angular_common__WEBPACK_IMPORTED_MODULE_3__["CommonModule"], _angular_forms__WEBPACK_IMPORTED_MODULE_2__["FormsModule"], ng_zorro_antd__WEBPACK_IMPORTED_MODULE_1__["NgZorroAntdModule"]],
            declarations: [dynamicComponent],
            entryComponents: [dynamicComponent]
        })(dynamicModule);
        // const all = this.compiler.compileModuleAndAllComponentsSync<any>(dynamicModule);
        // const module = all.ngModuleFactory.create(this.injector);
        // const componentFactory = module.componentFactoryResolver.resolveComponentFactory(dynamicComponent);
        const all = this.compiler.compileModuleAndAllComponentsSync(dynamicModule);
        const componentFactory = all.componentFactories.find(factory => factory.componentType === dynamicComponent);
        this.container.createComponent(componentFactory, 0, this.injector);
```

**Comment by alxhub** [comment]
Hello @BubbleLeaf, thanks for the bug report. Angular's behavior here is actually "correct", but I can see why this is a little confusing!

You're compiling this code with AOT (`ngc`), and the AOT compiler is actually looking at the `dynamicComponent` class and compiling it. The AOT compiler sees it as an undecorated class declaration with an Angular-decorated field (the `@ViewChild`). The main use case for such classes in View Engine was as base classes for directives and components. To handle that case, the AOT compiler turns this class into an "abstract" directive, just as if it had an `@Directive()` annotation with no arguments on it. That's why you're seeing a directive definition on the class - the fact that you later invoke the `Component` decorator manually on it for JIT compilation makes no difference.

The fix here is to prevent the AOT compiler from attempting to compile `dynamicComponent` in the first place. There are two ways to do this:

1) you can move the invocations of the `Component` and `NgModule` decorators into real decorators on the classes, and add `jit: true` to tell the AOT compiler to leave them alone:

```typescript
Component({
  selector: 'demo',
  template: template,
  styles: [``],
  jit: true,
})
class dynamicComponent implements OnInit {
  constructor() {}

  ngOnInit() {
    console.log(this.demo1.element);
  }

  @ViewChild('demo1', { read: ViewContainerRef, static: false })
  demo1: ViewContainerRef;
}

@NgModule({
      imports: [CommonModule],
      declarations: [dynamicComponent],
      entryComponents: [dynamicComponent],
      jit: true,
})
class dynamicModule {}
```

2) You can tell the AOT compiler to ignore _all_ classes not declared at the top level, by setting the `compileNonExportedClasses` option to `false` in `"angularCompilerOptions"` inside your tsconfig.

Both of these will allow those particular classes to survive AOT compilation with their decorators intact, and be compiled at runtime by JIT.

I hope this explanation helps!
-Alex

**Comment by BubbleLeaf** [comment]
Sorry , this is my mistake . Thanks for your help.
