### ISSUE TITLE
Object expected error thrown in angular 9 application - In IE11

### ISSUE THREAD

**Issue by djleonskennedy** [angular/angular#37252]
# 🐞 bug report

### Affected Package
The issue is caused by package @angular/zonejs

### Is this a regression?
No

### Description
Object expected error thrown in angular 9 application
https://github.com/zloirock/core-js/issues/812#issue-602118611
according this topic problem could be with zonejs

## 🔬 Minimal Reproduction
https://github.com/zloirock/core-js/issues/812#issue-602118611

## 🔥 Exception or Error
<pre><code>
Object doesn't support this action
</code></pre>

## 🌍  Your Environment

**Angular Version:**
<pre><code>
Angular: 9.1.0
... animations, cli, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router
Ivy Workspace: Yes

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.901.0
@angular-devkit/build-angular     0.901.0
@angular-devkit/build-optimizer   0.901.0
@angular-devkit/build-webpack     0.901.0
@angular-devkit/core              9.1.0
@angular-devkit/schematics        9.1.0
@angular/cdk                      9.0.1
@angular/flex-layout              9.0.0-beta.29
@angular/material                 9.0.1
@ngtools/webpack                  9.1.0
@schematics/angular               9.1.0
@schematics/update                0.901.0
rxjs                              6.5.4
typescript                        3.8.3
webpack                           4.42.0
</code></pre>

**Anything else relevant?**
browser: IE11

**Comment by awthwathje** [comment]
That is a particularly elusive bug! Had to replace all object [ngClass] with string expressions to make IE11 happy. Any indication when this could be fixed upstream?

**Comment by JiaLiPassion** [comment]
@awthwathje , could you provide a reproduce repo? thanks

**Comment by djleonskennedy** [comment]
@JiaLiPassion Have you checked that ? https://github.com/zloirock/core-js/issues/812#issue-602118611

**Comment by JiaLiPassion** [comment]
@djleonskennedy , sure, I will try to check it, but it will be easier if there's a repo.

**Comment by JiaLiPassion** [comment]
I can reproduce now, and this issue has nothing to do with `zone.js` or `core-js` or `rxjs`, the error happened in `to-integer.js`, and the reason is `isNaN` becomes `undefined`, in fact, not only `isNaN`, all global object inside `iframe window` object becomes `undefined`, I don't know it is the spec of IE or not, it seems , after `iframe window unload`, the window clear itself by setting all it's properties to `undefined`. And since `hubconnection.stop()` is async operations, so it happened after `unload`. 
Also I don't think the comment https://github.com/dotnet/aspnetcore/issues/20959#issuecomment-618061167 is correct, since `Array.prototype.slice()` allow pass no parameters, it will just clone the whole array, and also the error stack trace is not from `zone.js`, it is from `rxjs`, but still I don't think it is any lib's issue, it is just a IE behavior.

So in @djleonskennedy your case, I think maybe you can try to add `beforeunload` event, and then stop the connection in it, since `stop()` is a promise, you can cancel the `beforeunload` event and wait for the hub connection to really stop then close the window.

**Comment by JiaLiPassion** [comment]
@awthwathje , I am not sure what is your case, if you can provide a reproduce repo, I can help to debug.

**Comment by djleonskennedy** [comment]
@JiaLiPassion Thank you!
