### ISSUE TITLE
Images aren't getting cached by service worker

### ISSUE THREAD

**Issue by ghost** [angular/angular#37277]
### Bug Report or Feature Request (mark with an `x`)
```
- [x] bug report -> please search issues before submitting
- [ ] feature request
```

### Command (mark with an `x`)
```
- [ ] new
- [x] build
- [ ] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] xi18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc
```

### Versions

```
$ node --version
v8.11.3

$ npm --version
5.6.0

$ ng --version

     _                      _                 ____ _     ___
    / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
   / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
  / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
 /_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
                |___/


Angular CLI: 6.0.8
Node: 8.11.3
OS: win32 x64
Angular: 6.0.7
... animations, common, compiler, compiler-cli, core, forms
... http, language-service, platform-browser
... platform-browser-dynamic, platform-server, router
... service-worker

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.6.8
@angular-devkit/build-angular     0.6.8
@angular-devkit/build-optimizer   0.6.8
@angular-devkit/core              0.6.8
@angular-devkit/schematics        0.6.8
@angular/cdk                      6.3.3
@angular/cli                      6.0.8
@angular/material                 6.3.3
@angular/pwa                      0.6.8
@ngtools/webpack                  6.0.8
@schematics/angular               0.6.8
@schematics/update                0.6.8
rxjs                              6.2.1
typescript                        2.7.2
webpack                           4.8.3
```

### Repro steps

1. Serve an image from `localhost/api/users/profile-picture/1`
2. Add a data group to cache images
```
{
    "name": "profile-pictures",
    "urls": [
        "/api/users/profile-picture/*"
    ],
    "cacheConfig": {
        "strategy": "freshness",
        "maxSize": 300,
        "maxAge": "1d"
    }
}
```
3. Build for production
4. Serve app from `localhost:4000`
5. Make sure service worker is installed
6. Open the app in offline mode

### The log given by the failure

There's not really a log.

### Desired functionality

My images will be cached for offline use.

### Mention any other details that might be useful

My other api calls with json resources are cached just fine but for some reason the images aren't cached at all. I've searched the repo but haven't really found any similar issues.

**Comment by gkalpak** [comment]
I am afraid this issue is not actionable in its current state. There original post is two years old now (and a lot have changed in the meantime). I have tried the reproduction steps from the original post and the images are cached correctly.

Others have been reporting issues with similar symptoms, but most likely different root causes. In some cases, I noticed that the patterns used are incorrect. Note that while the SW config accepts glob-like patterns, they are not regular globs and for some fields there are special semantics. For example, `?` generally matches exactly one character, but in data-group `urls` it is [matched literally][1].

If you are still having this problem, please open a new issue with a minimal reproduction.

[1]: https://angular.io/guide/service-worker-config#urls
