### ISSUE TITLE
CICD builds are very slow. Please provide compile caching

### ISSUE THREAD

**Issue by craig-dae** [angular/angular#37297]
This is half bug, half feature request. Angular builds are slow, which have been noted in other tickets. The first build is very slow, needing to compile a lot of things that do not change in subsequent builds. In CICD, every build is the first build, so every build is very slow. This puts a minimum of 7 minutes at the front of all my CICD integration tests, just to build an app, when it could be re-built in less than a minute. This also means that CICD pipelines have to be more complicated. I have to have one job to create the frontend, which feeds into other jobs to run tests. 

Please provide some way of caching build artifacts in cicd, with particular attention to the "Compiling ..." steps that happen at the beginning. I'm using GitHub Actions for this. 

The goal is to run integration tests as quickly as possible, instead of taking from 7m before the first test.

**Comment by alxhub** [comment]
Hi @craig-dae,

Without knowing your specific setup, it's hard to know if the compilation times you're seeing are reasonable or whether they're related to the main compilation (unlikely) or to ngcc running against dependencies (most likely). But I agree, this is a confusing aspect of Angular and we could offer a lot better guidance.

Github does have a "cache" action, and projects (including https://github.com/angular/angular) will cache things like `node_modules` using the `package-lock.json` or `yarn.lock` files as cache keys. For a large Ivy project, it might make sense to:

1) invoke `ngcc` manually (in its async mode, for maximum performance).
2) cache the resulting `node_modules` in between CICD runs, to avoid `ngcc` needing to run on every invocation.

**Comment by craig-dae** [comment]
@alxhub GitHub does have a cache action: https://github.com/actions/cache/blob/master/examples.md#node---npm

```
- uses: actions/cache@v2
  with:
    path: ~/.npm
    key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
    restore-keys: |
      ${{ runner.os }}-node-
```

However, notice is just caches the ~/.npm folder, not the entire node_modules folder. 

"Note: It is not recommended to cache node_modules, as it can break across Node versions and won't work with npm ci"

So, are you saying that you would recommend caching the entire `node_modules` folder anyway, using package-lock.json to invalidate? I ruled out the idea since they recommend not doing that, but I can do it anyway.

**Comment by craig-dae** [comment]
Ok, did this. Build time dropped considerably. From 7m to 4m.

- npm ci -> npm i: 1m -> 17s
- build: 6m30s -> 3m45s

If you think this is reliable, I'll stick with it. I prefer to use `npm ci` though, to make sure that package versions aren't changing from development to cicd.

**Comment by FDIM** [comment]
We do the same on our build agent (non cloud...) - we cache node modules folder (as a zip) and use sha256 hash of package lock(+ node version as suffix) for cache key.

It seems to work reliably so far. I do have to admit that we trigger npm run postinstall to make sure that extra tasks are executed to match local setup.

Aside of that after doing a small timing test, zip file turned out to be faster to deflate than copying all files from host to docket instance.

**Comment by spock123** [comment]
We do the same for Circle CI, works fine.

Cache node_modules, use package-lock hash as key.

**Comment by Serginho** [comment]
@craig-dae Same problem. How do you cache yarn dependencies in the workflow to make ngcc not recompile everything? In my case, always recompile. I tried to cache yarn cache and node_modules, same behavior.

In my local machine, recompiles every time a package is installed. Not sure if works well. There are some related issues like: [36076](https://github.com/angular/angular/issues/36076)

**Comment by petebacondarwin** [comment]
@Serginho - when you add a new dependency (i.e. install a new package) ngcc does indeed need to process this package. Moreover, often the whole of node_modules is reset when you update or add a new dependency (commonly when you use yarn). This results in ngcc having to reprocess everything in the node_modules again.

I appreciate that this is not an ideal developer experience at the start of a project when you might be adding new dependencies quite often. We are looking at ways to mitigate this, such as https://github.com/angular/angular/pull/37075

But from a CI/CD point of view, it should not be as impactful, since most of the time the CI should either use a cached node_modules or would want to cleanly rebuild everything from scratch anyway. (The cache discussed here is not the "yarn cache" which is a global cache of downloaded packages, and is not accessible for ngcc - nor should it be since ngcc would be modifying packages that might be used differently in a completely different project).

**Comment by craig-dae** [comment]
Guys, I'm closing this because the solution of caching `node_modules` worked for me. However, GitHub warns against doing this. If it creates problems in the future, I'll re-open or create a new ticket.
