### ISSUE TITLE
Links feature request

### ISSUE THREAD

**Issue by Shivere** [angular/angular#37345]
# 📚 Docs or angular.io bug report

### Description

This is more of a feature request than a bug. Links in the documentation could be set to open in new tabs so that one could easily progress with the documentation rather than having to press the back button.

### What's the affected URL?**
 https://angular.io/...

### Reproduction Steps**
Click on any link in the documentation other the one for stackblitz

## 🔥 Exception or Error
<pre><code>

</code></pre>

### Browser info
Chrome

### Anything else relevant?
Very good documentation!

**Comment by petebacondarwin** [comment]
Browsers already have the ability to do this in an opt-in manner:

* On OS/X you generally click the link while holding the Cmd key
* On Windows you generally click the link while holding the Ctrl key.
* On Mobile a tap and hold brings up a context menu where the user can choose to open in a new tab.

Forcing links to open in a new tab constrains the user since there would be no way to choose to open them in the same tab.

**Comment by pkozlowski-opensource** [comment]
I don't think we should be changing anything about default behaviour of links as it would be very surprising. As @petebacondarwin pointed out, there is a well established way of getting requested behaviour already.

**Comment by Shivere** [comment]
Sure. Thanks.
