### ISSUE TITLE
Sourcemaps don't work for the angular2 codebase

### ISSUE THREAD

**Issue by jelbourn** [angular/angular#3737]
When running `test.unit.js`, `serve.js.dev`, etc., source maps do not work. 

Looking at the output code, it seems that sourceMappingURL is set twice. Not sure if this is related, but it's odd.
```
//# sourceMappingURL=element_injector_spec.js.map

//# sourceMappingURL=./element_injector_spec.js.map
```

When I run the tests in Firefox, Karma reports a ton of 404s for the `.map` files (which doesn't happen in Chrome).

**Comment by mhevery** [comment]
known issue due to Traceur.

**Comment by Ablu** [comment]
I am not sure if this is related to this issue... But I am having issues to get to the right code when debugging a test. I added a `debugger;` statement in this code: http://sprunge.us/IBOY?diff. But chrome breaks here:
https://dl.dropboxusercontent.com/u/45541625/2015-08-28-202928_831x401_scrot.png

Is that due to this issue or is it a different problem?

**Comment by pkozlowski-opensource** [comment]
It is related. Sadly we don't have good source map setup for the unit test infrastructure, I'm afraid.

**Comment by vsavkin** [comment]
Fixed here https://github.com/angular/angular/commit/87d56acdaa0a57b8781809a9bc17ba94965647ad
