### ISSUE TITLE
Starting navigation on NavigationEnd messes up the currentNavigation

### ISSUE THREAD

**Issue by kvetis** [angular/angular#37460]
# 🐞 bug report

### Affected Package

The issue is caused by package __@angular/router__

### Description

The problem occurs while triggering new navigation on `NavigationEnd`. Then while reading subsequent `ResolveEnd`, the `router.getCurrentNavigation()` will be `{ finalUrl: {...} }` missing other properies from `Navigation` interface. Probably somewhere the new `currentNavigation` is set to `null `right after `NavigationEnd` is broadcasted. Therefore resulting in invalid `currentNavigation` while the second navigation is happening.

## 🔬 Minimal Reproduction

 https://stackblitz.com/edit/angular-ivy-zgcupb?file=src%2Fapp%2Fb%2Fb.component.ts
1) Click the second link that includes the "redirect"
2) Observe console.

```
this.router.events
      .pipe(
        filter(e => e instanceof NavigationEnd),
        take(1)
      )
      .subscribe(() => {
        this.router.navigate(["a"]);
        this.router.events
          .pipe(
            filter(e => e instanceof ResolveEnd),
            take(1)
          )
          .subscribe(() => {
            console.log('this is weird Navigation:', this.router.getCurrentNavigation())
          });
      });
```

## 🔥 Exception or Error
This causes an error when using Akita Router Store, which expects `Navigation.extras` to be present
<pre><code>

Cannot read property 'state' of undefined
    at RouterService.serializeRoute (datorama-akita-ng-router-store.js:413)
    at RouterService.resolveEnd (datorama-akita-ng-router-store.js:389)
...
</code></pre>

## 🌍  Your Environment

**Angular Version:**
<pre><code>
Stackblitz  --- Angular 9.1.9

@angular-devkit/architect         0.901.4
@angular-devkit/build-angular     0.901.4
@angular-devkit/build-optimizer   0.901.4
@angular-devkit/build-webpack     0.901.4
@angular-devkit/core              9.1.4
@angular-devkit/schematics        9.1.4
@angular/cdk                      9.2.2
@angular/flex-layout              9.0.0-beta.29
@ngtools/webpack                  9.1.4
@schematics/angular               9.1.4
@schematics/update                0.901.4
rxjs                              6.5.5
typescript                        3.8.3
webpack                           4.43.0

</code></pre>

**Anything else relevant?**

**Comment by atscott** [comment]
Yep, I actually ran into this 10 minutes ago myself. The issue is that new navigations cancel the previous one (via the `switchMap`) and the `finalize` stage of that cancelled navigation clears the `currentNavigation`:
https://github.com/angular/angular/blob/cc49a91de7e228c6bdff8ca58936f05abe0ceb9f/packages/router/src/router.ts#L756
And then the `finalUrl` part:
https://github.com/angular/angular/blob/cc49a91de7e228c6bdff8ca58936f05abe0ceb9f/packages/router/src/router.ts#L506-L509
A potential fix might be to only set `currentNavigation` to `null` if the cancelled transition's `navigationId` is equal to the one on `currentNavigation`. At first glance, this seems like the correct fix, but maybe I'm missing something - I'd like to assume there was a reason it wasn't written that way from the beginning.
