### ISSUE TITLE
i18n-placeholder to placeholders assigned by variables

### ISSUE THREAD

**Issue by brognilucas** [angular/angular#37485]
# 🚀 feature request

### Relevant Package
 This feature request is for @angular/localize

### Description
When you have a placeholder that's assigned by a variable, the translation doesn't work even if you use the `$localize`String`` on the variable at typescript and also use the i18n-placeholder on input. 

I have the following case here as example: 

``` 
<fieldset>
        <label [for]="const.key" i18n>{{ const.label }}</label>
        <input
          [type]="const.type"
          [placeholder]="const.label"
          [formControlName]="const.key"
          [id]="const.key"
          *ngIf="const.type === 'text' || const.type === 'number'"
          [attr.disabled]="!allowEdit ? '' : null"
          i18n-placeholder
        />
</fieldset>
``` 

```
{
 key: 'supplementaryInformation',
 label: $localize`Supplementary Information`,
 type: 'text',
 ignore: false,
}
```

And when the application is rendered it doesn't work. 
![Capturar](https://user-images.githubusercontent.com/20867062/84033516-57ef8380-a96f-11ea-8076-3884d8f22289.PNG)

**Comment by AndrewKushnir** [comment]
Hi @brognilucas, thanks for creating a ticket.

The i18n extraction mechanism (invoked by `ng xi18n`) doesn't extract messages based on the bindings (since they are dynamic by nature), i.e. in the case below the `placeholder` would **not** be extracted:
```
  <input
      [placeholder]="const.label"
      i18n-placeholder
  />
```
If you want the `placeholder` to be translated, the best way would be to use upcoming `$localize` feature and define a translation in component's TS file as you pointed out (in this case the `i18n-placeholder` attribute is not needed). Note: the `$localize` feature is not fully finalized and the `ng xi18n` command doesn't extract `$localize`-based messages from TS files yet. There is a work in progress PR that would add extraction logic, see https://github.com/angular/angular/pull/32912 (please subscribe to that PR to receive further updates). Thank you.

**Comment by petebacondarwin** [comment]
I think you are very close to getting this to work. Using `$localize` is the key.

Here is an example of it working: https://github.com/petebacondarwin/issue37485

Try `npm run start` to see the English version and `npm run start-fr` to see the French version.
Run `npm build` to build the English and French versions.
