### ISSUE TITLE
On input of type number, adding 2 or more dots validate the field in contradiction with the pattern validator

### ISSUE THREAD

**Issue by rangzen** [angular/angular#37507]
# 🐞 bug report

### Affected Package

Probably @angular/forms.

### Is this a regression?

I don't know.

### Description

If I add "number" type in an input with a formcontrol with a pattern validator, adding 2 dots or more validate the field. Without `type="number"`, the field validates input correctly.

## 🔬 Minimal Reproduction

Check : https://stackblitz.com/edit/angular-ivy-3whjjx
In the input field, type '22' then '..' the field should have 7 digits but is valid.
Delete the line with `type="number"`, type '22' then '..', the field is incorrect and it's in coherence with the pattern `Validators.pattern('[0-9]{7}')`

## 🔥 Exception or Error

Nope.

## 🌍  Your Environment

**Angular Version:**
<pre><code>
Angular CLI: 9.1.7
Node: 12.17.0
OS: linux x64

Angular: 9.1.9
... common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router, service-worker
Ivy Workspace: Yes

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.901.7
@angular-devkit/build-angular     0.901.7
@angular-devkit/build-optimizer   0.901.7
@angular-devkit/build-webpack     0.901.7
@angular-devkit/core              9.1.7
@angular-devkit/schematics        9.1.7
@angular/cli                      9.1.7
@ngtools/webpack                  9.1.7
@schematics/angular               9.1.7
@schematics/update                0.901.7
rxjs                              6.5.5
typescript                        3.8.3
webpack                           4.42.0
</code></pre>

**Anything else relevant?**

Nope.

**Comment by AndrewKushnir** [comment]
Hi @rangzen, thanks for reporting the problem.

I performed additional investigation and here are the results:

- I've created pure HTML/JS version with the `<input type="number">` element, [you can find it here](https://stackblitz.com/edit/js-rmqlvu?file=index.html). The log under the input box displays the current value of the input after each key press. If you type "22..", the value becomes an empty string. This is the default behavior without any Angular logic on that page.
- What happens with the `pattern` validator is that it's not triggered for empty input (to allow for optional controls) and as a result, once the input value turns into an empty string, validator's logic is not invoked. If you change the type to "text" as you mentioned - the value of the input box will just contain all types characters and the `pattern` validator is invoked.
- Given the information above, possible solutions are:
  - Use the `<input type="text">` instead of type "number" and apply the necessary (more granular) rules.
  - Also add the `Validators.required` validator to the form control, so that the empty string is considered invalid (that would make the field required though).
  - Develop a new validator that would contain some specific logic (to see if the value is a correct representation of a number).

Since there are no action items for Framework, I'm closing this ticket.

Thank you.

**Comment by rangzen** [comment]
Thank you so much @AndrewKushnir !
First, for the explanations and the StackBlitz.
Second, for the insight on how to dig and think about problems like this one.
Thank you!
