### ISSUE TITLE
Unwanted padding around links on angular.io

### ISSUE THREAD

**Issue by IgorMinar** [angular/angular#37520]
# 📚 Docs or angular.io bug report

### Description

There is some unexpected padding around links at https://pr37331-d6e7954.ngbuilds.io/guide/build#allowing-commonjs-dependencies as seen here:

<img width="781" alt="Screen Shot 2020-06-09 at 6 21 22 PM" src="https://user-images.githubusercontent.com/216296/84216355-1bf71400-aa7e-11ea-8ecb-19be770efc13.png">

it might be specific to `div.alert.is-important`.

@ajitsinghkaler is this something you could look into please?

**Comment by ajitsinghkaler** [comment]
@IgorMinar after looking into this I found out that this is happening because of line 61 on _alert.scss https://github.com/angular/angular/blob/35502c739c70427bfcee239882d91ba0f4285cf9/aio/src/styles/2-modules/_alert.scss#L61

n further investigation I came to know that this should not happen as dgeni wraps our alerts in p tags I don't know how this is happening @petebacondarwin can throw some light on it.

After watching carefully the actual pr I saw that @aikidave forgot to add  a new line after the alert is-important div tags because of which dgeni cannot wrap it into a p tag

I've already added review comments on that pr for @aikidave to see

**Comment by ajitsinghkaler** [comment]
@petebacondarwin is the best person for dgeni related things if we can do anything on this he'll be the best person to tell us about this. If he says that we cannot do anything about it than we can close this issue.

@petebacondarwin thoughts ?

**Comment by petebacondarwin** [comment]
Here is my response :-)

https://github.com/angular/angular/pull/37331#discussion_r438682861

If we decided to make a dgeni inline tag handler then we should open an new issue/PR for it.
You can see an example of how it would be implemented here: https://github.com/angular/dgeni-packages/blob/master/jsdoc/processors/inline-tags.spec.js#L77-L122

I would envisage the usage looking like:

```
{@alert is-important"}
A bunch of **markdown** that will be guaranteed to be wrapped in a `<p>` tag.
{@endalert}
```

**Comment by gkalpak** [comment]
The problem with the unwanted padding seems to have been fixed in https://next.angular.io/guide/build#configuring-commonjs-dependencies. Do we still need this issue?

![important-alert](https://user-images.githubusercontent.com/8604205/94580123-3568d980-0282-11eb-986a-48a83a997ae1.png)

**Comment by ajitsinghkaler** [comment]
there is no need for this issue it is open only because we have not finalized if we want to implement any of the solutions suggested by @petebacondarwin

**Comment by petebacondarwin** [comment]
I don't feel we should implement further dgeni tags
