### ISSUE TITLE
Chrome specific runtime variables throw error - @types/w3c-web-usb

### ISSUE THREAD

**Issue by noelelias** [angular/angular#37572]
# 🐞 bug report

### Is this a regression?

Seems to be an ongoing issue: https://github.com/angular/angular/issues/4902

### Description

```
navigator.usb.requestDevice({
    filters: [{}]
});
```

Will work but it throws the following error:

>  Property 'usb' does not exist on type 'Navigator'.

and if you use more of the w3c-web-usb types

> Cannot find name 'USBDevice'.

## 🔬 Minimal Reproduction
https://github.com/noelelias/angular-usb-issue

## 🔥 Exception or Error
>  Property 'usb' does not exist on type 'Navigator'.

## 🌍  Your Environment

Angular CLI version 9.1.6
Angular: 9.1.11

**Comment by JoostK** [comment]
I have a feeling there is a commit missing in https://github.com/noelelias/angular-usb-issue, as that look to be only the result of `ng new`. Anyway, I expect this to be some misconfiguration in your tsconfig, unrelated to Angular.

**Comment by noelelias** [comment]
@JoostK sorry forgot to commit. https://github.com/noelelias/angular-usb-issue/blob/master/src/app/app.component.ts
You should be able to just git clone and ng serve

**Comment by JoostK** [comment]
Thanks. The reason the `@types/w3c-web-usb` package is not automatically included is because `src/tsconfig.app.json` specifies `"types": []`, I'm guessing because it excludes testing related types from being visible in production code. Because of this configuration, TS will not automatically include any types in `./node_modules/@types/`. If you add `"w3c-web-usb"` to that array (also in `tsconfig.spec.ts` ) it will start to work.

The is a bit about typings in https://angular.io/guide/typescript-configuration however the scenario where global ambient files are used is not documented there. So from that perspective the docs could be extended to mention this case.

**Comment by noelelias** [comment]
Thank you :+1: that works perfectly.

**Comment by aikidave** [comment]
@JoostK Could you let me know how we should update the docs to address this issue? I'd be happy to take care of it.

**Comment by JoostK** [comment]
@aikidave I have opened #42417 to clarify this. PTAL.
