### ISSUE TITLE
Update service worker registration docs to reflect update interval fixes

### ISSUE THREAD

**Issue by epelc** [angular/angular#37580]
# 📚 Docs or angular.io bug report

A few years ago when you started using service workers + checking for updates using an interval you quickly ran into a bug which caused the service worker to never register since the app wouldn't become stable(due to interval). That has been fixed through a few PRs but the docs on these PRs by themselves are now incorrect and do not clarify a few things:

[`SwRegistrationOptions`](https://angular.io/api/service-worker/SwRegistrationOptions) docs need to be updated for the `registrationStrategy` key.

- The default registration strategy is now wait for app to stabilize or 30 seconds whichever comes first. It does not mention this very important second part about the 30 second timeout.
- `registerWhenStable` actually supports `registerWhenStable:<timeout>`, this is how the above is implemented. See here for internally using [this](https://github.com/angular/angular/blob/master/packages/service-worker/src/module.ts#L104)
- It should be safe to use the example [here](https://angular.io/guide/service-worker-communications#checking-for-updates) due to the above default strategy change. This should be noted if you use a custom strategy that it can potentially break things.
  - Previously the examples using intervals were unsafe

Currently you have to go down a rabbit hole of issues and PRs to figure out that it is actually now safe to use interval to check for updates. I am happy the actual code is fixed but it would be nice to get the docs updated to reflect this more clearly.

Related issues

https://github.com/angular/angular-cli/issues/13351

https://github.com/angular/angular/issues/34464

https://github.com/angular/angular/commit/29e8a64cf02fa9b80d38c30091e0b730403c54c8#diff-d3f0f5f34efd2b679fc85854b84a281a

**Comment by gkalpak** [comment]
The `registerWhenStable:<timeout>` is only supported on v10. Therefore, angular.io (which corresponds to the currently stable version, v9) does not contain the update. [next.angular.io][1] (which corresponds to master) does mention the new `<timeout>` option.

You are correct that the docs for the default value are not updated. I noticed that a couple of days ago :grin:
This will be fixed by #37555 (but again, only for the v10+ version).

##
The above should take care of your first two points.

I am not sure what you mean/suggest with the third point :confused:
There is an alert below the example you linked to explaining the issue with `interval()`. Are you suggesting that it is not enough (or not in the right place)?

[1]: https://next.angular.io/api/service-worker/SwRegistrationOptions#registrationStrategy

**Comment by epelc** [comment]
Thanks @gkalpak! I forgot to check v10 docs.

Looks like #37555 fixes all the docs issues. Also disregard my third point, It was a little confusing trying to get everything together.

I'll leave open for now until #37555 is merged unless you think otherwise.

**Comment by gkalpak** [comment]
Thx, @epelc! Closing since #37555 is now merged.
