### ISSUE TITLE
Tutorial suggests a change in code, that makes the default tests fail

### ISSUE THREAD

**Issue by Danon** [angular/angular#37652]
# 📚 Docs or angular.io bug report

### Description

When following "Tour of heroes" tutorial, I found out that tutorial suggests a change that immediately makes the tests fail. I found it, because i had `ng test` command running, which turned red immediately after I introduced the change. The tutorial says nothing about the failing tests, nor saying how to fix it.

### What's the affected URL?**
https://angular.io/tutorial/toh-pt0

### Reproduction Steps**
Follow the "Tour of heroes" tutorial

### Expected vs Actual Behavior**
I would expect that if tutorial suggest to go with `ng new example` (which creates default tests), and also suggests to change the structure of the `app` template, then it should also mention this change in test.

How to fix the tests, so they follow the tutorial:

Change this:
```ts
expect(compiled.querySelector('.content span').textContent).toContain('example app is running');
```
to this:
```ts
expect(compiled.querySelector('h1').textContent).toContain('Tour of Heroes!');
```

## 📷Screenshot

![image](https://user-images.githubusercontent.com/13367735/85204601-de17ac80-b315-11ea-944b-41a20c63787e.png)

**Comment by s-gbz** [comment]
That is a good point! Proper testing is a major part of Software Engineering. Albeit it feels a bit neglected sometimes.
Maybe because it can feel overwhelming at first.

I can imagine that most beginners look for a simple tutorial to get a basic grip of the framework.
Including tests in ToH might seem out of the blue, unrelated and "too much" considering that the topic spans multiple pages (see screenshot below).

![grafik](https://user-images.githubusercontent.com/23424538/87398530-46287e00-c5b6-11ea-9e7b-82088958edf0.png)

That's just my opinion though. I'm happy to participate in the discussion and help out with a PR if we somehow go for it.

**Comment by Danon** [comment]
Maybe small notification/info box at the bottom of the page, instructing how to fix the tests would be enough? :)

**Comment by s-gbz** [comment]
That's a great idea for execution! I personally still think it might seem a out of place though. Testing is not mentioned nor covered in the whole series. Maybe we could use your idea to provide small testing bits throughout the lessons.

We should definetly consult someone senior like @kapunahelewong or @jbogarthyde :)

PS: Is Brandon Roberts still associated with the Docs?

**Comment by Danon** [comment]
How many other tutorials are there, apart from "Tour of heros"? @kapunahelewong or @jbogarthyde 

I'm a TDD/tests enthusiasth myself, and it really bothers me that the tutorials ends in applications with failing tests. If there are less than 5-6 tutorials, I am willing to accept the responsibility of adapting the tests and suggesting my contrubution to the tutorials as PRs with the descriptions on how to make them pass.

Or, perhaps an additional tutorial on how to test components all together.

**Comment by kapunahelewong** [comment]
This is such a helpful thread! And, as you two noticed, the testing info is undergoing some re-thinking. 

Regarding the tutorials, we are in the process of identifying tutorials throughout the docs and moving them into a new tutorials section. Sometimes, it's a little bit tricky because some of the current documentation has conceptual information  mixed in with longer tutorials. Because of this, you'll see some things being moved and then after the move someone goes in to sort out the actual content with a finer approach. We are doing it this way so that we can really see what's present in the docs and what we need to add, or in some cases clear out. We're also trying to keep docs PR scope really focused, so that's why you'll see incremental PRs.

cc @aikidave, our docs team lead for more context. 🌟

@s-gbz, regarding your Brandon has since left the docs and I miss him!

**Comment by aikidave** [comment]
@kapunahelewong, as is so often the case, correct! 

I think adding testing to tour of heroes (and maybe the stackblitz-based tutorial as well?) would be a great thing to do. @Danon, I think both of your ideas are good: making sure the tests pass(!) and also looking into adding additional tutorials on testing. What's the best way for us to connect to discuss this further?

**Comment by Danon** [comment]
@kapunahelewong I am happy to see you appreciate the value of common contribution as well as proper TDD!

I am available on Discord and Google Meets, but I can also join other media of communication. 

As of me, I've been working with Vue and React/Jsx a lot lately (something like 2 years), but I've had angular at the back of my head often. Now, that I've trird it, I see its value more and more - Yes, it does required more effort to start, but it offers much more and I feel it is (to conparison) much more mature.

In addition, I'm a TDD enthusiast, and I have a quite feeling that Angular maintainers and doc authors are too, that's why I'm more than happy to contribute and suggest ideas.

**Comment by s-gbz** [comment]
So cool to see this happen! Have a good one @Danon ! Feel free to contact me if there's something I can help with :)

**Comment by aikidave** [comment]
@Danon Sounds good! Send me a message (my contact info is in my profile) and let's see what we can do to improve the docs!

**Comment by bob-watson** [comment]
Ended up adding a note about how the Tour of Heroes doesn't support the test files.
It'd be nice to add this some day. In the meantime, this note should prevent future surprises by people who want to go above and beyond the tutorial.
