### ISSUE TITLE
ngcc --async takes too long every time

### ISSUE THREAD

**Issue by splincode** [angular/angular#37702]
# 🐞 bug report

### Affected Package

The issue is caused by package @angular/compiler

### Is this a regression?

Not sure

### Description

On my CI, the installation of packages takes a very long time, more precisely postinstall with `ngcc --async`

## 🔬 Minimal Reproduction

```
$ git clone https://github.com/Angular-RU/angular-ru-sdk.git
$ cd angular-ru-sdk
$ yarn install
```

First yarn install:

```
...
Compiling @angular/router/testing : esm2015 as esm2015
Compiling @angular/router/testing : esm5 as esm5
Compiling @angular/router/testing : main as umd
Compiling ngx-toastr : fesm5 as esm5
Compiling ngx-toastr : esm2015 as esm2015
Compiling ngx-toastr : esm5 as esm5
Compiling ngx-toastr : main as umd
✨  Done in 110.03s.
```

```
$ rm yarn.lock
$ yarn install
```

Second yarn install:

```
...
Compiling @angular/router/testing : esm2015 as esm2015
Compiling @angular/router/testing : esm5 as esm5
Compiling @angular/router/testing : main as umd
Compiling ngx-toastr : fesm5 as esm5
Compiling ngx-toastr : esm2015 as esm2015
Compiling ngx-toastr : esm5 as esm5
Compiling ngx-toastr : main as umd
✨  Done in 130.03s.
```

```
$ rm yarn.lock
$ yarn install
```

`N+` yarn install:

```
...
Compiling @angular/router/testing : esm2015 as esm2015
Compiling @angular/router/testing : esm5 as esm5
Compiling @angular/router/testing : main as umd
Compiling ngx-toastr : fesm5 as esm5
Compiling ngx-toastr : esm2015 as esm2015
Compiling ngx-toastr : esm5 as esm5
Compiling ngx-toastr : main as umd
✨  Done in 1250.03s.
```

In my last `ngcc` 1250.03s. - why?

## 🌍  Your Environment

**Angular Version:**

Angular 9.1.11
LernaJS monorepo

**Comment by petebacondarwin** [comment]
Taking a look...

**Comment by petebacondarwin** [comment]
I couldn't reproduce this. Each time I ran `yarn` I got values around 220 secs but it did not go up in the way described here.

If you change `ngcc` to `ngcc -l debug` you can get more insight into the time it takes to actually run `ngcc` rather than the total including `yarn`. I note you are using lerna and, I think, yarn workspaces. But in this case I don't this should affect the processing time.

For example in three consecutive runs I saw:

ngcc time (s) | total yarn time (s)
----------|-----------
182 | 213
170 | 226
174 | 236

I note that while the ngcc time is pretty constant here, the overall yarn time is increasing slowly.

Is it possible that there is some file cache going on that means that each time you run `yarn` there is less working memory available causing disk swapping?

**Comment by splincode** [comment]
interesting behavior yarn
