### ISSUE TITLE
(dart/transformer): Support for multiple directives for a class 

### ISSUE THREAD

**Issue by keertip** [angular/angular#3771]
The directive metadata visitor does not support a class having multiple directives 
https://github.com/angular/angular/blob/master/modules/angular2/src/transform/common/directive_metadata_reader.dart#L112, whereas this use case is seen in user code. 

Seems like the visitor should be able to handle this use case.

**Comment by jakemac53** [comment]
What is the priority on this, can it wait until @kegluneq is back?

**Comment by kegluneq** [comment]
@keertip , can you show me an example of where this is present in user code? My original implementation supported multiple directives and it was removed in review because angular2 (at that time, at least) supported only one (see the first review comment [here](https://github.com/angular/angular/pull/1349))



btw, transformer code has been moved: [new link](https://github.com/angular/angular/blob/master/modules_dart/transform/lib/src/transform/common/directive_metadata_reader.dart#L111)

**Comment by keertip** [comment]
Sorry, looks like the example was angular1 code. As this is not angular2 code, closing the issue.
