### ISSUE TITLE
ng update @angular/cli also updates angular core

### ISSUE THREAD

**Issue by markgoho** [angular/angular#37741]
Upgrade instructions read: `ng update @angular/cli @angular/core` but it would appear that the `@angular/core` part is redundant and is updated along with the cli. This can lead to confusion. Are we intentionally asking users to enter commands that aren't needed?

**Comment by IgorMinar** [comment]
As of v9 (https://github.com/angular/angular-cli/commit/be210778f4f3f75639554846f7297b48ba382987#diff-078217c29c514afed6a8d9ef7a0ebd74R89) the cli has an indirect peer dep (via @angular-devkit/build-angular) on @angular/compiler-cli which depends on @angular/core.

Because of this change, we no longer need to specify both @angular/core and @angular/cli in the `ng update` command.

**Comment by alan-agius4** [comment]
@IgorMinar, should we update the docs and update guide?

**Comment by IgorMinar** [comment]
Does `ng update @angular/core` also update both the FW and CLI?

I haven't tested it but it might work.

If it does then it would be better to document that so that it's clear that you are updating the core and its dependencies and not just the CLI.

**Comment by alan-agius4** [comment]
> Does ng update @angular/core also update both the FW and CLI?

No, because `@angular/core` don't have a peer dependencies on Angular CLI.

**Comment by alan-agius4** [comment]
Closing as this seem not to warrant a docs change since the activity ion this issue is very low.
