### ISSUE TITLE
Can't inject AsyncTestCompleter in beforeEach

### ISSUE THREAD

**Issue by jelbourn** [angular/angular#3777]
Trying to inject `AsyncTestCompleter` into a `beforeEach` block results in an `InstantiationError`.
```ts
    beforeEach(inject([TestComponentBuilder, AsyncTestCompleter], (tcb, atc) => {
      builder = tcb;
      async = atc;
    }));
```
```
Error: Error during instantiation of AsyncTestCompleter!.
```

It would allow tests to be significantly cleaner by supporting this, as it would prevent a lot of duplication in writing each test (`inject`ing `AsyncTestCompleter` into each `it`).

**Comment by vicb** [comment]
@jelbourn this is so because `AsyncTestCompleter.done()` actually calls `done()` which is an argument to `it()` functions.

See [the source code](https://github.com/angular/angular/blob/a9ce454b2176514e1b655d7b005c32f0aa14ab98/modules/angular2/src/test_lib/test_lib.ts#L141) for more details.

As I don't think there is a lot we can do here, I'm closing this issue. Feel free to re-open if you feel like it's worth more investigation.
