### ISSUE TITLE
Angular copy to clipboard icon clicks gets page movement in IE 11

### ISSUE THREAD

**Issue by vesivagu** [angular/angular#37796]
https://angular.io/start

![image](https://user-images.githubusercontent.com/25737946/85929678-6aa50a80-b8d4-11ea-8cf7-d39427f1f36f.png)

when click copy option as highlighted in yellow in attached document the page gets goes to end of the page. the page movement shouldnt be there, it is a ux issue.

environment : windows 10
browser: IE11

**Comment by petebacondarwin** [comment]
While we are looking at IE11 support, I see that our "external link" icons are broken too...

![Screenshot 2020-06-28 at 10 00 08](https://user-images.githubusercontent.com/15655/85943183-4114cf00-b926-11ea-87dc-9f5734a7c018.png)

**Comment by saifabusaleh** [comment]
Hi,

@gkalpak @petebacondarwin I took a look on the original issue

Its because of this: https://github.com/angular/angular/blob/f8096d499324cf0961f092944bbaedd05364eea1/aio/src/app/shared/copier.service.ts#L46

seems like `.select()` is causing the browser to scroll to the bottom
I still didn't find any workaround to fix this in IE11

Any suggestions?

thanks

**Comment by gkalpak** [comment]
Hm...good sleuthing. Unfortunately, the only work-around I can think of is to store the window's scroll position and scroll back to it after calling `.select()`. Something like:

```ts
const [x, y] = [window.pageXOffset, window.pageYOffset];
this.fakeElem.select();
window.scrollTo(x, y);
```

But I am a little wary of adding such a hack 🤔

**Comment by saifabusaleh** [comment]
@gkalpak ,
I found the issue is not from `.select()` but its from .`removeChild()`
https://github.com/angular/angular/blob/f8096d499324cf0961f092944bbaedd05364eea1/aio/src/app/shared/copier.service.ts#L52

If I remove the above line, it doesn't reproduce

Also I tried to reproduce the issue in minimal project and its not reproducible.

I managed to fix this in another way:

I added id to the `pre` element here:
https://github.com/angular/angular/blob/f8096d499324cf0961f092944bbaedd05364eea1/aio/src/app/custom-elements/code/code.component.ts#L38

And then instead of `.appendChild` and `.removeChild` to happen on `document.body`, Its now happening on the `pre` element that I got by `document.getElementById`

This caused in IE11 to scroll to the pre element ( the code div) instead of the bottom of the page, no effect on other browsers

What you think?

**Comment by gkalpak** [comment]
Thx for looking into this, @saifabusaleh! I looked into it some more and (thanks to your drawing my attention to angular/components#20073 :tada:) I found out that the odd IE11 behavior is due to removing the temporary `<textarea>` element while is has the focus (which implicitly happens when calling `.select()` on it).

I have created #38244 with the fix (and some other minor improvements to `CopierService`). PTAL and let me know if it works for you too.
