### ISSUE TITLE
Angular copy to clipboard icon missing its top portion

### ISSUE THREAD

**Issue by vesivagu** [angular/angular#37816]
https://angular.io/start

![image](https://user-images.githubusercontent.com/25737946/85985049-b86e5f80-ba07-11ea-9172-b17262f59476.png)

It is a ux issue - icon needs to be corrected in below platforms

windows 10
IE 11 browser

**Comment by gkalpak** [comment]
The styling is indeed not 100% correct on IE. Since IE is rarely the primary browser used by developers (and the docs are mainly intended for developers), our support for IE is on a best effort basis.

So, this is a low priority, but if anyone feels like picking it up, I would be happy to review a fix :wink:

**Comment by saifabusaleh** [comment]
Hi @gkalpak , Can I take this issue?

**Comment by gkalpak** [comment]
It's all yours, @saifabusaleh :smiley:
