### ISSUE TITLE
DomSanitizer doesn't work for background-image URLs

### ISSUE THREAD

**Issue by foxfire** [angular/angular#37877]
# 🐞 bug description
I have issues in Angular 10 with the sanitation of URLs on Background-images on DIV-elements. On a regular IMG tag the sanitation works. But on Background-images the URL doesn't get rendered. At the place were the path should appear in the console there is just an 'undefined'. No error gets logged. The URLs that should be rendered are System paths. The Angular app is embedded inside an Electron app.

**app.component.ts**
` sanitize(imgURL) {
    return this.sanitizer.bypassSecurityTrustUrl(imgURL);
  }`

And the corresponding HTML with the IMG - Tag working:
 `<img class="image" [src]="sanitize(imgURL)"/>`

And this is a similar HTML configuration but with background-image in a div instead of an IMG tag. 

` <div class="image box{{i}}"  [ngStyle]="{'background-image': 'url(" + sanitize(imgURL) + ")'}"></div>` 

### Affected Package
I think the issue is with the DomSanitizer which resides in @angular/platform-browser

### Is this a regression?
This feature regarding online forums did work in the past.

### Github Repository
[ImageWall](https://github.com/foxfire/ImageWall)

**Comment by jelbourn** [comment]
@IgorMinar do you know why we support sanitized urls for `HTMLImageElement.src`? AFAIK this isn't a vector for XSS attacks.

**Comment by IgorMinar** [comment]
As of v10, styles are no longer sanitized. Previously they were sanitized because of an IE vulnerability but that one is no longer relevant.

The full write up on this is here: https://hackmd.io/_sF2TzXLSiuuYbY88MpdQA?view

I verified that this is indeed the case: https://stackblitz.com/edit/angular-ivy-3atw1a?file=src%2Fapp%2Fapp.component.html

So please don't use the sanitizer to process the values before binding to them.

One more thing to note:

```
<div class="image box{{i}}" [ngStyle]="{'background-image': 'url(" + sanitize(imgURL) + ")'}"></div>
```

is incorrect use of the sanitizer because it tries to concat SafeUrl value with is not supported. But again, if you don't use the sanitization at all, everything will work.
