### ISSUE TITLE
HammerJS stops working after removing hammerjs imports (after upgrade to Angular 10)

### ISSUE THREAD

**Issue by darkoandreev** [angular/angular#37907]
Hello everyone,

**Description**
After upgrading my library project to Angular 10, I removed all the **hammerjs**  imports and I replaced them with **HammerModule** (imported in root module **app.module.ts**). I saw, that hammerjs will be removed automatically during the migration to Angular v9, but in my project that wasn't the case and I removed the hammerjs imports manually as it is suggested [HERE](https://github.com/angular/components/blob/master/guides/v9-hammerjs-migration.md) 

I also get a warning message and because of it I actually removed the imports 
`app.module.ts depends on 'hammerjs'. CommonJS or AMD dependencies can cause optimization bailouts.`
Unfortunately after removing the hammerjs imports, all the gestures stopped working.
They're working only if I have both the imports (hammerjs and HammerModule).

I just want to mention that the hammerjs package is still installed and it's not removed from the project and package.json file.

Thanks in advance!

**Comment by devversion** [comment]
Hello! I'm trying to look into this issue, but it's unclear to me what the problem is. Can you please provide more details?

> After upgrading my library project to Angular 10, I removed all the hammerjs imports and I replaced them with HammerModule (imported in root module app.module.ts)

I'm confused by this. You are removing HammerJS imports, but add imports to `HammerModule`? If you do not use hammerjs anymore, then you should not use the `HammerModule` at all.

>  I saw, that hammerjs will be removed automatically during the migration to Angular v9, but in my project that wasn't the case and I removed the hammerjs imports manually as it is suggested HERE

It _should_ be, but only if your application does not use any of the HammerJS gestures _manually_. If your app only relied on HammerJS for Angular Material, then the migration will remove hammer automatically. If this doesn't work, that is surprising and we would like to look into it, but need a reproduction (our tests seem to work as expected; and the migration ran in v9 already too)

> I also get a warning message and because of it I actually removed the imports
app.module.ts depends on 'hammerjs'. CommonJS or AMD dependencies can cause optimization bailouts.

That seems like a different issue. The Angular CLI as of version 10 will warn about commonjs/AMD dependencies. You can disable this warning though as I don't think there is a more optimizable version of HammerJS. https://angular.io/guide/build#configuring-commonjs-dependencies

> Unfortunately after removing the hammerjs imports, all the gestures stopped working.

Please clarify, what gestures are you referring to? Angular Material gestures? or custom gestures? If you use HammerJS gestures manually in your application, then HammerJS should not be removed at all.

**Comment by darkoandreev** [comment]
Hello @devversion 
I will try to explain the issue again. So, in my project I have both `import 'hammerjs';` and `HammerModule` in my root module (it doesn't matter actually which module I choosed). From the documentation [HERE](https://github.com/angular/components/blob/master/guides/v9-hammerjs-migration.md) I understood that I should remove the `import 'hammerjs';` and it should work only with **HammerModule** import and actually it didn't work.
It only works if there are both HammerModule and hammerjs imported.

I'm using hammerjs gestures in my application and I'm not talking about removing the hammerjs library, I'm talking about removing `import 'hammerjs';` from my application.

I will post a minimal example of the problem for better understanding.

In one of my modules, I have the following HammerJS config:

`export class ExampleHammerConfig extends HammerGestureConfig {
  overrides = {
    pinch: { enable: false },
    rotate: { enable: false }
  };
}`

And then I have HammerModule import:

`@NgModule({
  declarations: [...],
  imports: [CommonModule, HammerModule]
})
export class ExampleModule {
  static forRoot(): ModuleWithProviders {
    return {
      ngModule: PsCarouselModule,
      providers: [{ provide: HAMMER_GESTURE_CONFIG, useClass: ExampleHammerConfig }]
    };
  }
}`

This configuration **DON'T WORK** if i have only `HammerModule` imported and I **MUST** have `import 'hammerjs';` in the module.

**Comment by devversion** [comment]
Thanks @darkoandreev for getting back so quickly!

> From the documentation HERE I understood that I should remove the import 'hammerjs'; and it should work only with HammerModule import and actually it didn't work.

This is the part I'm confused about. The migration guide is specific to Angular Material consumers, and it says that the import to `hammerjs` should _only_ be removed if HammerJS is not used in your application. That is also what the automatic migration is supposed to do. Based on the code you shared though, it seems like you are explicitly using `hammerjs` (even with a custom gesture config). Since that is the case, the import to `hammerjs` should not be removed and the whole migration does not apply to you.

**Comment by johannesjo** [comment]
@devversion what was irritating to me is, that there is a warning showing up after the migration if you don't add `hammerjs` to the`allowedCommonJsDependencies`. Don't know what brought the others here, but I removed hammerjs at first, because of exactly that warning and because I read somewhere (sorry, don't remember where) that it isn't required any more..

**Comment by darkoandreev** [comment]
@devversion @johannesjo Now I read the documentation again, and you're right and it's related to Angular Material. The yellow warning was also irritating to me and that's the question here - it says 'please remove the hammerjs import' and when I remove it my gestures stops working. Why do I need both hammerjs and HammerModule imports, so that gestures start working? Can you just import the hammerjs library into HammerModule and then we'll just import HammerModule and everything will be fine.
Again - do we have an example for custom hammerjs gestures with only HammerModule imported, because warning says 'please remove hammerjs imports'.

**Comment by johannesjo** [comment]
> Again - do we have an example for custom hammerjs gestures with only HammerModule imported, because warning says 'please remove hammerjs imports'.

@darkoandreev to my understanding this is not possible. `hammerjs`is still needed if you want to make touch gestures work.

**Comment by devversion** [comment]
@johannesjo Yeah, that's a good observation. The fact that in v10, a warning will be printed for HammerJS is slightly confusing. It should be documented on how this can be fixed: https://angular.io/guide/build#configuring-commonjs-dependencies

It's also true that HammerJS is not required anymore, but that is only for Angular Material and already started with version 9. The migration guide for that, and the migration have been added in Angular Material v9, but the migrations re-runs in v10 another time.

> 'please remove the hammerjs import'

I don't know of any warning printed like that. Only in a few cases where the migration is not able to automatically remove HammerJS if it was purely needed for Angular Material, a warning is printed. Those warnings state:

```
<..> Please manually check if you can remove HammerJS from your application.
```

Could you please point me to the warning that asked you to remove the Hammer imports? I haven't been able to spot something as you mentioned. Sorry for this being a bit confusing. Unfortunately the migration we provided in Angular Material is quite complex and I want to make sure we don't miss anything.

> Why do I need both hammerjs and HammerModule imports, so that gestures start working? Can you just import the hammerjs library into HammerModule and then we'll just import HammerModule and everything will be fine.

That seems like a different conversation. Angular does not want to be responsible for loading HammerJS. It should be up to the consumer when he wants to load HammerJS. There are ways to load it lazily or blocking on initialization. Hence Angular does nothing more than just setting up the template event bindings when the `HammerModule` is added. Previously these event bindings were always set up automatically, but we no longer do this as not everyone uses HammerJS and this adds unnecessary size.

**Comment by devversion** [comment]
I think this is working as intending (see my comments above). If one could point me to sources of confusion in e.g. messaging or docs, please let me know. I'd be super happy to clean this up. Right now I'm not seeing any problem here. Also feel free to send a pull request with proposed changes. The migration for HammerJS as said is in the `angular/components` repository.
