### ISSUE TITLE
Allow caching of NGCC files for CI/CD using npm ci

### ISSUE THREAD

**Issue by villelahdenvuo** [angular/angular#37942]
# 🚀 feature request

### Relevant Package
This feature request is for @angular/compiler-cli.

### Description
Copy of #37297 that was closed: "CICD builds are very slow. Please provide compile caching"

### Describe the solution you'd like
I think there should be a configuration option, for example in ngcc.config.js to set a cache directory where ngcc related files will be stored after compilation. That way the CI can be instructed to cache that directory.

### Describe alternatives you've considered
Caching the node_modules folder in CI, however it does not work with `npm ci` command which is the recommended way of installing dependencies in CI.

P.S. Perhaps I can look into making a PR if you are okay with this idea.

**Comment by petebacondarwin** [comment]
We have looked into ways to do this in the past. In fact I even started a branch along these lines: https://github.com/petebacondarwin/angular/tree/ngcc-cache

The problem is primarily how to invalidate the cached data, since it is not simply a case of checking the versions of the packages, since things like ngcc.config.js can affect what and how packages are processed.

At the moment we do not intend to implement such a strategy. We have done a lot of work recently to try to speed up ngcc processing, particularly the "noop/hot processing" scenario. Further our longer term goal is to move away from needing ngcc, by providing a library format that can be published to npm that does not need ngcc processing. So our efforts are now focussed on that work.

**Comment by villelahdenvuo** [comment]
@petebacondarwin the point about in validation is valid, but I think if you opt for custom caching you should be responsible for the invalidation. For example, use the hash of the package lock file plus a custom version number (that's what we do with our dependencies). That way if any package changes it invalidates and if we need to change the ngcc config we can manually invalidate the cache by bumping the version number.

**Comment by petebacondarwin** [comment]
This should be solved by the ng-linker being developed to replace the need for ngcc. Please follow along with the development here: https://github.com/orgs/angular/projects/2
