### ISSUE TITLE
The way how to merge several TemplateRefs

### ISSUE THREAD

**Issue by tamtakoe** [angular/angular#37960]
# 🚀 feature request

### Relevant Package

 This feature request is for @angular/core

### Description

E.g. I want to make `MyTable` component with infinity scroll. I wrap `cdk-virtual-scroll` inside my component
```html
@Component({ 
selector: 'my-table',
template:
`<cdk-virtual-scroll-viewport [itemSize]="30">
    <ng-container *cdkVirtualFor="let item of _dataSource">
        <ng-template
          [ngTemplateOutlet]="rowTemplate"
          [ngTemplateOutletContext]="{
            $implicit: item
          }">
        </ng-template>
    </ng-container>
</cdk-virtual-scroll-viewport>`
...
```

And use it this way
```html
<my-table>
    <ng-template #col1><td>1</td></ng-template>
    <ng-template #col2><td>2</td></ng-template>
    <ng-template #row><tr></tr></ng-template>
</my-table>
```

There is one problem. I have several TemplateRefs `col1`, `col2`, `row`, but I need one `rowTemplate` which should be `row` with  `col1` and `col2` templates inside. There is no way to reach this in Angular. I can't merge templates as strings with HTML and I also can't extract the new `rowTemplate` from some temporary outlet.

### Describe the solution you'd like
 Not universal. We can add
`TemplateRef.append`, `TemplateRef.prepend`, `TemplateRef.insert`, etc. methods to merge templates

### Describe alternatives you've considered
 Or use something looks like React way for work with templates. Angular way is too complicated for component creation. That is why we still have no adequate multiselect, infinity-table etc. Angular components.

**Comment by jelbourn** [comment]
The way you would accomplish something like this is to grab the `TemplateRef` via `@ContentChildren` in your component, and then stamp them out where you want in your component's template. This is what we do in the cdk/table. The main difference with what you have in your example above is that, instead of using the declarative `ngTemplateOutlet` directive, you would want to manually call `createEmeddedView` to stamp out each of your templates inside the table row, most likely by adding a custom directive to which you can pass individual templates.

Concatenating templates like this wouldn't align well with Angular's application model, since template are tied to a specific _binding context_ and to a particular location in the change detection tree. Arbitrarily merging templates would really confuse this.
