### ISSUE TITLE
Browser crashes in async mode when generating promises repeatedly

### ISSUE THREAD

**Issue by ewinslow** [angular/angular#3798]
This humble code will cause your browser to completely lock up (copy pasted from current docs and adjusted only slightly for async mode):

```ts
/// <reference path="typings/angular2/angular2.d.ts" />

import {Component, View, bootstrap} from 'angular2/angular2';

@Component({
  selector: 'my-app',
  changeDetection: 'ON_PUSH',
})
@View({
  template: `<h1>{{title|async}}</h1>`,
})
// Component controller
class MyAppComponent {
  get title() {
    return Promise.resolve('Hello, World!');
  }
}

bootstrap(MyAppComponent);
```

See the problem?

I suspect it's the way Angular is doing dirty-checking on `{{title|async}}`. Since the `get title()` getter returns a new promise *each time it is called*, angular gets all confused, even though the promise resolves to the same value every time.

Seems like this is async-mode specific, because when I just use regular non-async mode, I see `[object Object]` and the browser remains responsive.

Here's what the fixed version looks like:
```ts
/// <reference path="typings/angular2/angular2.d.ts" />

import {Component, View, bootstrap} from 'angular2/angular2';

@Component({
  selector: 'my-app',
  changeDetection: 'ON_PUSH',
})
@View({
  template: `<h1>{{title|async}}</h1>`,
})
// Component controller
class MyAppComponent {
  // Saving a reference to the promise helps
  title: Promise;
  
  constructor() {
    this.title = Promise.resolve('Hello, World!');
  }
}

bootstrap(MyAppComponent);
```

now the code works as expected.

**Comment by gdi2290** [comment]
I ran into something like this too with Falcor in the past. 



[change_detection/pipes/observable_pipe.ts](https://github.com/angular/angular/blob/b8e82e4db31bd44eec4488f8b77366c78ba92a8e/modules/angular2/src/change_detection/pipes/observable_pipe.ts#L47...L64)
`AsyncPipe` maintains reference of the Strategy and has essentially 4 states in which the transform does something different to cause side effects: 
 * Strategy without a subscription,
 * Strategy with a subscription,
 * CurrentValue/ReturnedValue are the same
 * CurrentValue /ReturnedValue are different

I only know this because I had to create an `RxPipe` that prevented a similar cycle from happening when a change returns a new Observable reference. So there's actually a potential problem where the first state should return the returned value and the returned value should be dereferenced during the onDestroy Pipe lifecycle rather than the Observable reference lifecycle.

Here's my code for the RxPipe (this is the old way to make a Pipe)

```typescript
export function isObservable(obs) {
  return obs && obs.subscribe && typeof obs.subscribe === 'function';
}

export class RxPipe {
  _ref: ChangeDetectorRef;
  _promise: Promise<any>;

  _latestValue: Object;
  _latestReturnedValue: Object;


  _immediateScheduler: any;
  _subscription: any;
  _observable: any;
  _pending: any;

  constructor(ref: ChangeDetectorRef) {
    this._ref = ref;
    this._latestValue = null;
    this._latestReturnedValue = null;
    this._immediateScheduler = null;
    this._subscription = null;
    this._observable = null;
    this._pending = null;
  }

  supports(obs): boolean { return isObservable(obs); }

  onDestroy(): void {
    if (isPresent(this._subscription)) {
      this._dispose();
    }
    this._latestReturnedValue = null;
    this._latestValue = null;
    this._pending = null;
  }

  transform(obs: any): any {
    if (isBlank(this._subscription)) {
      this._subscribe(obs);
      return this._latestReturnedValue;
    }

    if (isBlank(this._latestReturnedValue)) {
      this._pending = obs;
    } else if (obs !== this._observable) {
      this._dispose();
      return this.transform(obs);
    }

    if (this._latestValue === this._latestReturnedValue) {
      return this._latestReturnedValue;
    } else {
      this._latestReturnedValue = this._latestValue;
      return WrappedValue.wrap(this._latestReturnedValue);
    }
  }

  _subscribe(obs: any): void {
    this._observable = obs;
    this._immediateScheduler = (<any>Rx.Scheduler).immediate;
    this._subscription = obs.
      observeOn(this._immediateScheduler).
      subscribe(value => this._updateLatestValue(value));
  }

  _dispose(): void {
    if (isPresent(this._subscription)) {
      this._subscription.dispose();
    }
    // this._latestValue = null;
    this._subscription = null;
    this._observable = null;
    this._immediateScheduler = null;
  }

  _updateLatestValue(value: any): void {
    this._latestValue = value;
    if (isPresent(this._ref)) {
      this._ref.requestCheck();
    }
    if (isPresent(this._pending)) {
      this._dispose();
      let obs = this._pending;
      this._pending = null;
      this.transform(obs);
    }
  }
}

```
For my workaround I created a `_pending` ref in order to ensure there was a value before the transform logic will resolve the cycle :/ the problem I see here is that we're back to Angular1 digest cycles since we're giving the control over the bindings to the Observable/Promise. There's a new way to manage the bindings that Meteor uses so there might be a better way to handle async bindings.


also related https://github.com/angular/angular/issues/2449

cc @vsavkin

**Comment by mhevery** [comment]
So unfortunately this works as expected. :-( Yes not the best user experience.

Angular runs CD and sees new instance of promise every time. (At this point we should flag an error but, we don't because of https://github.com/angular/angular/issues/2830)

Then the promise resolves, and we trigger new CD, which recreates the problem.

There is no way of preventing this. We do have https://github.com/angular/angular/issues/2830 which will flag that `title` always produces an value, so once https://github.com/angular/angular/issues/2830 is fixed you will get a proper error.

**Comment by ewinslow** [comment]
I don't understand how that ticket relates to this one but I'll trust for now that you've got a plan and will circle back again later to see what the status is.
