### ISSUE TITLE
feat: create `Element` DI

### ISSUE THREAD

**Issue by adamdbradley** [angular/angular#3801]
In many examples I'm using `ElementRef` just so I can get `nativeElement`, such as: 

```
export class AwesomeCmp {
  constructor(elementRef: ElementRef) {
    this.ele = elementRef.nativeElement;
  }
}
```

I realize we should stay away from direct DOM elements, but there are still many cases where we still need direct access.

**Comment by PascalPrecht** [comment]
AFAIK injecting an element ref through `ElementRef` type is already a type of DI for elements. @adamdbradley could you elaborate on what specifically you're requesting here?

**Comment by adamdbradley** [comment]
@PascalPrecht Really just a shortcut to make it easier to get ahold of the native element. So instead of:

```  
 constructor(elementRef: ElementRef) {
    this.ele = elementRef.nativeElement;
  }
```
It could be:

```  
 constructor(element: Element) {
    this.ele = element;
  }
```

`ElementRef` would continue to do it's job and still provide `nativeElement`.

**Comment by PascalPrecht** [comment]
I'm not really into the application vs render layer logic, but I could imagine that this would introduce a certain amount of complexity to support this, since we would then have a very concrete interface (which probably won't work with the web worker env).

In most of the cases we'd have to do `this.element = elementRef.nativeElement` anyways to work with the native element across component methods. This vs `this.element = element` is prolly not worth the complexity.

I'm sure @tbosch is a better person to talk about that.
