### ISSUE TITLE
templateStr in the Component decorator does not accept Array.join() as a value

### ISSUE THREAD

**Issue by wagnermaciel** [angular/angular#38028]
# 🐞 bug report

### Description

In a component decorator, something like
```ts
@Component({
  selector: 'app-root',
  template: getHtml(),
  styles: [],
})
```
will work if `getHtml` is defined as something like
```ts
function getHtml(): string {
  return '<span>Test</span>';
}
```
BUT, if `getHtml` is defined as
```ts
function getHtml(): string {
  return [1,2,3].join();
}
```
you will get this error: `error NG1010: template must be a string`.

## 🔬 Minimal Reproduction
https://stackblitz.com/edit/angular-ivy-ixdal3

## 🔥 Exception or Error
```
error NG1010: template must be a string
```

**Comment by JoostK** [comment]
Hi @wagnermaciel,

during AOT compilation, the compiler has to determine the template string using static evaluation of the code. This has some limitations, which are documented in [the AOT compilation guide](https://angular.io/guide/aot-compiler#foldable-syntax). The explanation is somewhat outdated since Ivy, as the Ivy compiler has a vastly different static analyzer, however the syntax kinds it supports is mostly equivalent to what View Engine was able to.

Your example could theoretically be statically analyzed, and there's #21265 to track the support of these methods. Could you capture your use-case in that issue so that its relevance can be better understood? Thanks!
