### ISSUE TITLE
Attribute [for] to label doesn't exist

### ISSUE THREAD

**Issue by danicomas** [angular/angular#3803]
```html
<label [for]="controlPath">{{controlPath | uppercase}}</label>
```

```js
controlPath: string;
```

Error shown: EXCEPTION: Can't bind to 'for' since it isn't a known property of the '<label>' element and there are no matching directives with a corresponding property

**Comment by pkozlowski-opensource** [comment]
Right, there is no `for` _property_ on label, there is only an _attribute. You have to use `<label [attr.for]="controlPath">` to bind to attributes.

**Comment by danicomas** [comment]
Thanks @pkozlowski-opensource

**Comment by martinsik** [comment]
I wonder why at the same time I can use other attributes like `name="{{ myName }}"` but `for` attribute inside `<label>` throws error `<label for="{{ myId }}"></label>`:

>Can't bind to 'for' since it isn't a known property of the '<label>' element and there are no matching directives with a corresponding property

**Comment by pkozlowski-opensource** [comment]
@martinsik you are _never_ binding to attributes, but _always_ to properties. You can write `[name]="foo"` since an element that you are using has a `name` property: https://developer.mozilla.org/en-US/docs/Web/API/Element/name

In short: ng2 is _always_ binding to properties and a given DOM element must have this property (there is no point of changing a property that doesn't exist / is not supported).

**Comment by PascalPrecht** [comment]
@martinsik FYI this is explained here: http://blog.thoughtram.io/angular/2015/08/11/angular-2-template-syntax-demystified-part-1.html
