### ISSUE TITLE
Pipe is called three times

### ISSUE THREAD

**Issue by danicomas** [angular/angular#3807]
I have created this Pipe:

```js
@Pipe({name: 'capitalize'})
export class CapitalizePipe {  
  capitalize(value) {
    return value.charAt(0).toUpperCase() + value.slice(1);
  } 
  
  transform(value):string {
    return this.capitalize(value);
  }
}
```

And added in these components:

```js
@Component({selector: 'input-text', properties: ['controlPath: control', 'value: data']})
@View({
  template: `
    <div class="form-group">
      <label [attr.for]="controlPath">{{controlPath | capitalize}}</label>
      <input type="text" class="form-control" [id]="controlPath" [placeholder]="controlPath" [(ng-model)]="value">
      <show-error control="{{controlPath}}" [errors]="['required']"></show-error>
    </div>
  `,
  directives: [ShowError, FORM_DIRECTIVES],
  pipes: [CapitalizePipe]
})
class InputText {
  controlPath: string;
  value: string;

  constructor() { }
}
```

```js
@Component({
  selector: 'my-app',
  viewBindings: [HTTP_BINDINGS]
})
@View({
  template: 
  `<form (ng-submit)="onSubmit(form)" [ng-form-model]='form'>
    <img [src]="data.avatar_url ? data.avatar_url : ''" width="100" height="100"/>
    <input-text control="name" [data]="data.name"></input-text> 
    <input type="submit" class="btn btn-primary"/>
  </form>`,
  directives: [FORM_DIRECTIVES, ShowError, NgIf, InputText]
})

// Component controller
class MyAppComponent {
  data: Object;
  form:ControlGroup;
  constructor(@Inject(Http) http:Http) {
    this.data = {};
	  this.form = new ControlGroup({
      name: new Control("", Validators.required)
    });
    http.get('https://api.github.com/users/danicomas').toRx().map(res => res.json()).subscribe(response => this.data = response);
  }
  
  onSubmit(f) {
    console.log(f);
    console.log(f.controls.name.valid);
    console.log(this.data);
  }
}

bootstrap(MyAppComponent);
```

Then I have debugged the transform pipe function and it is called 3 times :S

**Comment by mhevery** [comment]
Can you put this on plunker (http://plnkr.co/edit/tpl:BrUl7z1vvZBGWBfSGS8D?p=preview) so we have a repro case?

**Comment by vicb** [comment]
That's probably linked to #3701

**Comment by danicomas** [comment]
@mhevery here the plunker:
http://plnkr.co/edit/o9T9rrJ9mysDZlcLnqSt?p=info

2 times called in load and 1 in an async request :S

**Comment by mhevery** [comment]
@danicomas Thanks for the plunker.

Here is the analysis: for `{{name | capitalize}}`

1. expected: called as a consequence to `bootstrap`. At this point the `name` has not be set yet and it is `undefined`. It seems that Compiler creates a promise, and since the promise is created within the `NgZone` it should have it's digest delayed, but since there are no more promise resolutions, the digest runs here.
2. unexpected: One more digest happens here. I can not account for the reason as to why, but chrome dev tools show that it is because of the same promise call as in step 1. It seems that somehow `NgZone` detects end of changes twice and double executes the digest. 
3. expected: Called as a consequence to `setTimeout`

@vicb Since you know better zones, could you look into what is going on? There is definitely one too many digests going on in there.

**Comment by vicb** [comment]
I'll definitely look into that.
I did actually start looking at that last week but as the bootstrap is getting refactored, I'll probably wait for it to be in unless it takes too much time.

**Comment by danicomas** [comment]
Status of that @vicb @mhevery  ?

**Comment by jeffbcross** [comment]
As an aside, `capitalize` could now be implemented as a pure pipe, which would cause transform to only be called when the input has changed.
https://github.com/angular/angular/commit/a8bdb693b9d9df82c0078eb327ba6f9fe0e8ca0a

**Comment by danicomas** [comment]
Status of that @vicb @mhevery @jeffbcross ?

**Comment by danicomas** [comment]
Closed in alpha 19 works well :D
