### ISSUE TITLE
Service using providedIn: root build with v10/v9 not working in v8 app

### ISSUE THREAD

**Issue by gmfun** [angular/angular#38107]
# 🐞 bug report
When a library is build in angular@9 or angular@10, lazy loaded services using `providedIn: root` does not work when used in another application on angular@8. 

The same library and same service works fine if the library is build with angular@8 or the application is at angular@9

The library is build in prod mode so that it built with view engine

### Affected Package

 The issue is caused by package @angular/core v9 and v10 both

### Is this a regression?

 Yes, the previous version in which this bug was not present was angular v8

### Description

Lazy loaded service using 'providedIn: root` should not throw `NullInjectorError: No provider for <Service>`

## 🔬 Minimal Reproduction

[ivy-issue.zip](https://github.com/angular/angular/files/4935841/ivy-issue.zip)

The above folder has reproduction of the issue

## 🔥 Exception or Error
<pre><code>

app.component.html:344 ERROR NullInjectorError: StaticInjectorError(AppModule)[AppComponent -> NgService]: 
  StaticInjectorError(Platform: core)[AppComponent -> NgService]: 
    NullInjectorError: No provider for NgService!
</code></pre>

**Comment by JoostK** [comment]
This is expected, actually. Angular is generally backwards compatible, but there is no guarantee on forwards compatibility. Even in ViewEngine compilations (Ivy disabled) you'll find generated code in the compiled output, for tree shakeable providers. The generated code was changed in Angular 9, but older versions are unable to deal with the new compilation output.

As a library developer, you'd always need to compile using the oldest version you need to support, so that you rely on backwards compatibility of the platform, not forwards compatibility.

<sup>Copied from https://github.com/angular/angular/issues/36354#issuecomment-606754233</sup>
