### ISSUE TITLE
scrollPositionRestoration enabled by default

### ISSUE THREAD

**Issue by AnoopSasidharan** [angular/angular#38113]
scrollPositionRestoration option in routing should be the default behaviour in routing unless it is disabled. This is a helpful behaviour that a web application can have. Please consider this for next release

**Comment by essana3** [comment]
I doesn't work when I enable it

**Comment by AnoopSasidharan** [comment]
By enabling the property scrollPositionRestoration to enable wont work .

You have to custom implement the scroll behaviour in the component where
you need the scoll behavior.

This is the example given in doc,

class AppModule {
   constructor(router: Router, viewportScroller: ViewportScroller) {
     router.events.pipe(
       filter((e: Event): e is Scroll => e instanceof Scroll)
     ).subscribe(e => {
       if (e.position) {
         // backward navigation
         viewportScroller.scrollToPosition(e.position);
       } else if (e.anchor) {
         // anchor navigation
         viewportScroller.scrollToAnchor(e.anchor);
       } else {
         // forward navigation
         viewportScroller.scrollToPosition([0, 0]);
       }
     });
   }
}

**Comment by essana3** [comment]
I implemented a loading bar to track the navigation progress and used scrollToPosition in the NavigationEnd event to restore it to the top.
Still nothing.

**Comment by AnoopSasidharan** [comment]
please follow this link

https://github.com/angular/angular/issues/24547

one suggestion worked for me is ,

router.events.pipe(
      filter((e: RouterEvent | Scroll): e is Scroll => e instanceof Scroll)
    ).subscribe(e => {
      if (e.position) {
        setTimeout(() => { viewportScroller.scrollToPosition(e.position);
}, 0);
      } else if (e.anchor) {
        setTimeout(() => { viewportScroller.scrollToAnchor(e.anchor); }, 0);
      } else {
        setTimeout(() => { viewportScroller.scrollToPosition([0, 0]); }, 0);
      }
    });

**Comment by DeanPDX** [comment]
@essana3 there are many things that could be causing the behavior you're seeing. Can you create a stackblitz that illustrates your problem? If I had to guess, it *sounds* like perhaps your body element isn't the scrolling element in your app, so `BrowserViewportScroller` is calling `this.window.scrollTo` (see [implementation here](https://github.com/angular/angular/blob/d1ea1f4c7f3358b730b0d94e65b00bc28cae279c/packages/common/src/viewport_scroller.ts#L104)) but it's not scrolling your content due to the fact that window scroll is already at 0 top. This is pretty common if you're using Angular Material. One possible fix is to implement your own `BrowserViewportScroller` and that way you can have it do whatever you want. See [my comment on the issue AnoopSasidharan mentioned](https://github.com/angular/angular/issues/24547#issuecomment-648525026) for details and a working example of how to do this.

**Comment by essana3** [comment]
@DeanPDX Thank you so much, I targeted mat-sidenav-content when scrolling to top and now it works.
