### ISSUE TITLE
Plural expression within `ng-container` with `ngIf` prevents following markup from being rendered

### ISSUE THREAD

**Issue by anton-github** [angular/angular#38144]
# 🐞 bug report

### Affected Package

It seems like any angular version with Ivy enabled is affected.

### Is this a regression?

Since Ivy is enabled by default in the newer versions I would say yes, it's a regression.

### Description

Plurals ICU expressions prevent following markup from being rendered when used within `ng-container` with `ngIf` on it. **For version 10 it's true only for subsequent renderings**, see examples in the next section.
Short code example:
```
  <ng-container *ngIf="true">
    you have {{ 1 }} {1, plural, one {task} other {tasks}} to do
  </ng-container>
```
On subsequent renderings the code above will render `you have 1 task`

## 🔬 Minimal Reproduction
Toggle block visibility by clicking button to see how the result is changed

https://stackblitz.com/edit/plural-ng8 - all is OK
https://stackblitz.com/edit/plural-ng9rc1 - is OK with Ivy disabled, otherwise the behavior is wrong for both first and subsequent renderings
https://stackblitz.com/edit/plural-ng10 - is OK with Ivy disabled, otherwise the behavior is wrong only for subsequent renderings

## 🔥 Exception or Error
Nothing is logged

## 🌍  Your Environment

**Angular Version:**
Please see stackblitz examples dependencies above

**Comment by RahmatAliMalik5** [comment]
Any solution? I am getting bundles of errors after upgrading to 10 from 9.

**Comment by petebacondarwin** [comment]
It appears that in the `ɵɵtext()` instruction for the `" to do "` string, the call to `appendChild()` fails because it is not able to find a `renderParent` - (`getRenderParent()` returns `null`).

**Comment by petebacondarwin** [comment]
Actually that is a redherring, since at the point the `appendChild()` is called, this node is not yet attached to the node tree, since it is part of an `ngIf`, which has not yet been applied.

On further digging, I see that on the first rendering, the `tNode.next` for the ICU does have a reference to the text node, but on the second rendering this property is null.  So we need to work out why the ICU tNode is losing the link to the following text tNode on second rendering.
