### ISSUE TITLE
Conflicting binding syntax between properties and regular attributes makes text values for property binding impossible

### ISSUE THREAD

**Issue by stevenroose** [angular/angular#3817]
Currently, this is how attribute binding works
```html
// regular attribute plain text value
<input value="Some Value">
// regular attribute binding with local variable inside component
<input value="{{someValue}}">
// property-attribute binding with local variable inside component
<custom-input [valueProp]="someValue">
// IMPOSSIBLE: property-attribute plain text value
<custom-input [valueProp]="Some Value">
```

This means that depending on what type of attribute you are making a binding for, the syntax depends:
```html
value="{{someValue}}"
[value]="someValue"
```

The last use case above is not so rare and I don't even know how to do it properly without dedicating a static variable just for the sake of getting the value in the attribute value.

What is the reason why the `[propertyBinding]` attributes don't need the double mustaches?

Since the Guidelines tell me I should suggest a fix for the problem: I'd say just drop the exceptions. Too many exceptions and specialities can overkill. We are used to use `{{ }}` for including code in HTML files, why make an exception for the new attribute types?

**Comment by mhevery** [comment]
I think you are miss-understanding the the above examples.

`<input value="Some Value">` means set attribute `value` to `Some Value`, but DOM will reflect that to the property `value` and set it there as well.

`<input [value]="expression">` tells angular to set property `value` to evaluation of `expression`. In this case we bypass the attribute because it is not useful. DOM properties is all that matters.

`<input value="Hello {{exp}}">` is short hand for `<input [value]=" 'Hello ' + exp ">` it is a common form of interpolation.

If you wish to set popertey `valueProp` to literal just do this:

`<custom-input value-prop="Some Value">` It will work as expected. Yes you have to go dash-case because HTML attributes are case insensitive.

This was discussed #133
