### ISSUE TITLE
Unable to see source of Angular TS classes in IDE's (e.g. WebStorm or VS Code)

### ISSUE THREAD

**Issue by christaclaessonatdeltekdotcom** [angular/angular#38172]
Hi :)

When using Angular it is very unfortunate that we cannot see the code behind the Angular TS classes. We can see the class declarations in WebStorm and VS Code but not the code behind the methods. It's only when debugging and setting breakpoints that the IDE´s show the code behind the classes (they get it from the source maps).

So my question is: would it not be possible to create a set of Angular packages that embeds the class sources for Angular and not just the class declarations ? This would make it much easier to understand and debug the finer points og Angular and Angular components. 

The above also applies to the Angular Material components, it's not just the Angular core that is at issue here.

Yours
Christa :)

**Comment by petebacondarwin** [comment]
This is actually a limitation of the way Typescript works. At compile time (and in IDE), the only information available to the application for libraries is the "typings" information. In other words the contents of the `.d.ts` files. The reason you are able to get into the TS source during debugging is down to the source-mapping information.

I guess it is possible that the TS team or the IDE teams could try to search source-maps when looking at imported code, but this is definitely not something that can be fixed in the Angular code, or any similar project.
