### ISSUE TITLE
Angular typescript concatenating numbers instead of adding

### ISSUE THREAD

**Issue by pixieaka** [angular/angular#38171]
**Class**
```
  title = 'app';

  a: number = 0;
  b: number = 0;

  c: number;

  calc(): void {
    this.c = this.a + this.b;
  }
```
**View**
```
<input type="text" [(ngModel)]="a" (keyup)="calc()">
<input type="text" [(ngModel)]="b" (keyup)="calc()">
<p>{{c}}</p>
```
**Return**
if `a = 1` and `b = 2` for example it equal `c = 12`, it should be `3` and when i try `parseInt(this.a)` it result error Argument of type 'number' is not assignable to parameter of type 'string'.

**Solution**
change input type to `type="number"`

**how is that happen angular should respect typescript rules ( variables types ) and parsed to number in background. because when i change type to number template design and css selectors will change also.**

**Comment by petebacondarwin** [comment]
So from a JavaScript point of view this is working as expected. The `input[type=text]` element produces a string value and so that is what gets written to the property on the component. I guess we could try to do better with our type checking of this sort of binding to ngModel at compile time to highlight that it is trying to assign a string to a number.

**Comment by JoostK** [comment]
I'd consider this to be an issue with forms not being strictly typed; the `ngModel` is typed as `any` so the compiler does not have any information to detect an error here.

**Comment by JoostK** [comment]
Actually there is an old issue with the same request: #16952. Closing this one as duplicate.
