### ISSUE TITLE
PreserveSymlink doesn't work with Ivy

### ISSUE THREAD

**Issue by gilsdav** [angular/angular#38193]
# 🐞 bug report

### Affected Package

 The issue is caused by package Ivy

### Is this a regression?

 
It works when I set `"enableIvy": false`.

### Description

If I create an Angular library into a project and want to use it without deploy it (in dev mode) in an other project.
* project1/projects/**library1**
* project2/**src**

I use `npm link ...` (or a typescript `path`) to add the library to the project.

It doesn't take in consideration the  angular.json option `"preserveSymlinks": true` on ngcc build (Ivy prebuild) so everything is broken because it's not the same references.
If I remove the `node_modules` of project1 (alternative to preserveSymlinks), the build of `project2` says that @angular/core is missing.

## 🔬 Minimal Reproduction

Need multiple project so it's not possible to create a Stackblitz

## 🌍  Your Environment

**Angular Version:**
Tested into Angular 9 and 10

**Anything else relevant?**

Mac OSX + VS Code

**Comment by petebacondarwin** [comment]
Yes, I'm afraid that ngcc does not follow symlinks by design. This is because ngcc overwrites files in the libraries that it processes, and it cannot be sure that it is not damaging files owned by another system etc.

Is your library going to be published to npm? If not then you are free to build it with ivy enabled and then consume the ivy code directly in your application project.

**Comment by gilsdav** [comment]
Cool, I didn't test with the library built in Ivy mode. It seems to work.
So I can:
- build without Ivy to deploy the lib
- build with Ivy for local development

Thank's 👍
