### ISSUE TITLE
Multiple angular elements app doesn't work on same page

### ISSUE THREAD

**Issue by sonali395** [angular/angular#38237]
I am trying to build a project with multiple angular elements application but when I use it on a plain html outside of the project. I get this error on console

![image](https://user-images.githubusercontent.com/21099519/88486442-c7501f80-cf7d-11ea-976b-1c03b2060c89.png)

I changed the builder to 
```"architect": {
        "build": {
          "builder": "@angular-builders/custom-webpack:browser",
          "options": {
            "customWebpackConfig": {
              "path": "webpack.config.js"
            },
```
But I faced this error while I build my elements application in prod mode
![image](https://user-images.githubusercontent.com/21099519/88486406-a091e900-cf7d-11ea-8159-abd054e43adb.png)

Please check the following code to repro my issue. https://github.com/sonali395/angular-test

Note: I don't face any of these issue if both the elements are defined and built in the same application project.

**Comment by gkalpak** [comment]
@sonali395, this error you are getting seems to be somehow related to the use of `output.library` in `webpack.config.js`. I don't fully understand the purpose and bahvior of `output.library` by reading [the docs][1], but I assume the issue related to how this option interacts with default values or other values set in the final Webpack config.

I any case, by removing the `library: '...'` line from [webpack.config.js#L6][2], I was able to build `elements` and `elements2` successfully and get `output/index.html` to work.

##
Since this seems to be related to Webpack configuration and thus not something we can fix on our end, I am going to close this issue (but feel free to continue the discussion below).

[1]: https://webpack.js.org/configuration/output/#outputlibrary
[2]: https://github.com/sonali395/angular-test/blob/8314a71956d21490f3309146d38e24c6ff3aff71/webpack.config.js#L6

**Comment by sonali395** [comment]
@gkalpak Yes it worked. Thank you 👍
