### ISSUE TITLE
test_lib.d.ts is missing

### ISSUE THREAD

**Issue by IgorMinar** [angular/angular#3824]
Currently we don't generate it during our build. This causes issues when using TestComponentBulider in tests with TS.

**Comment by IgorMinar** [comment]
this has been fixed already

**Comment by rolandjitsu** [comment]
@IgorMinar but it does not look like it made it to DT yet.

**Comment by IgorMinar** [comment]
I believe we stopped publishing d.ts files into definitely typed in favor
of distributing them via npm. @alexeagle can you confirm?

**Comment by alexeagle** [comment]
We have still been publishing to DefinitelyTyped for each angular release. I'm tracking work to make it *possible* to depend on angular typings through NPM here: https://github.com/angular/angular/issues/3082  but we haven't decided if we will still publish to DefinitelyTyped as well.
However I don't see `test_lib.d.ts` in the `bundles/typings/angular2/` folder of latest angular2 npm (alpha 37) either.
Note that we haven't done a release in a couple weeks because we have a lot of breaking changes to resolve in alpha 38. Running `gulp docs/typings` in the angular build, I do see `dist/docs/typings/angular2/test_lib.d.ts` so once we finally cut the release this file will be published to DefinitelyTyped, at least until we make some decision about publishing typings in the NPM package *exclusively*.

**Comment by rolandjitsu** [comment]
@alexeagle thanks. I was just curious about it since this issue was closed and I could not see the typings anywhere yet. Looking forward to the next release though :)
