### ISSUE TITLE
angular2.dev.js contains incorrect SystemJS config

### ISSUE THREAD

**Issue by IgorMinar** [angular/angular#3826]
At the end of the file we have:

```
System.config({"paths":{"*":"*.js","angular2/*":"angular2/*"}});
```

I'm not sure how we ended up with the `"*":"*.js"` mapping, but we shouldn't be configuring paths not belonging exclusively to Angular.

This is especially confusing as of a SystemJS 0.17 when `defaultJSExtension` [was flipped to false](https://github.com/systemjs/systemjs/releases/tag/0.17.0).

**Comment by pkozlowski-opensource** [comment]
I agree with @IgorMinar - I don't see any reason for this config after migration to a never SystemJS. More generally, I don't think we should be in business in providing System config. Going to send Pr to remove this.

**Comment by jpsfs** [comment]
Just a quick question, using the new version of SystemJS shouldn't all modules be registered with the JS extension?

Example:

Before (system ~0.16)
```
System.register("angular2/src/di/metadata", ...)
```

After (system ~0.18)
```
System.register("angular2/src/di/metadata.js", ...)
```

@pkozlowski-opensource

**Comment by pkozlowski-opensource** [comment]
@jpsfs while it is true that never systemjs moves to URLs as module modifiers it doesn't matter much in a bundled version since everything is pre-loaded and no HTTP / Ajax request should be done at runtime for ng2-specific resources.

We _could_ register things with .js extension but this would be non-trivial (?) with out current setup in the repo where imports are shared between *.ts and *.dart files.

**Comment by rkirov** [comment]
I added that line, as the original goal of the bundle was to make getting off the ground as quick as painless as possible. That allowed for demoes to have zero `system.config`, and jump straight to `System.import`.

So why not replace it with the 0.18 version `defaultJsExtension: true`, so that demo users don't feel like they need to learn system.js.

**Comment by pkozlowski-opensource** [comment]
@rkirov I see your point about trying to make it easier on users. The pb I can see with this approach is that we are enforcing config that impacts all dependencies / everything that goes through SystemJS. So I'm afraid that it might mess up things for more experienced SystemJs users.

I'm not against adding `defaultJsExtension: true` but I would prefer that we, as Angular, don't try to enforce config for an app-global / wide loader.

**Comment by IgorMinar** [comment]
the thing is that the bundle should be usable even without systemjs and in that case the config doesn't do anything.

I approved the PR to remove this. If this causes more friction elsewhere we need to find a different solution.

**Comment by jpsfs** [comment]
@pkozlowski-opensource I'm not an expert on SystemJS, please correct me if I'm wrong, but if the modules are not registered with ".js", then using **defaultJsExtension: true**, SystemJS will try to look for the modules with the extension and will not find them.

Actually,I think this is not happening right now because of
```
System.config({"paths":{"*":"*.js","angular2/*":"angular2/*"}});
```
When you remove it, the problem I just describe will appear.

Example:
```
import * from "angular2/src/di/metadata";
```
will trigger a search for "angular2/src/di/metadata.js" (because of the **defaultJsExtension: true** flag) and that will not be registered. (if you don't use the "*":"*.js" config)

My vote would be to generate the bundle with the .js extension on the register. Something like:
```
System.register("angular2/src/di/metadata.js", ...);
```

**Comment by pkozlowski-opensource** [comment]
@jpsfs I don't think it works like this. SystemJS will first consult its internal registry to see if a dependency is there. Only if a dependency is _not_ registered SystemJS will try to fetch it and this is where `defaultJsExtension` comes into play. 

Did you run into actual problems somewhere? If so, could you share a plunk demonstrating those?

**Comment by jpsfs** [comment]
@pkozlowski-opensource yes, you are right. But the fact is that a dependency named _"angular2/src/di/metadata.js"_ *is not* registered, only _"angular2/src/di/metadata"_ is.

I will try to reproduce this is in a plunk asap.

**Comment by rkirov** [comment]
@IgorMinar sounds good, lets revisit if we end up having to remind people to set `defaultJsExtensions: true`.

**Comment by IgorMinar** [comment]
I think that using defaultJsExtensions is now discouraged. I'm looking into
this stuff this week.
