### ISSUE TITLE
Use Angular's testability API to wait for end of e2e tests

### ISSUE THREAD

**Issue by tbosch** [angular/angular#3829]
Right now, we rely on a hack to wait for the end of e2e tests: We wait until the "loading..." text disappears. However, Angular exposes an API to know when bootstrap is done via `global.getAllAngularTestabilities()` (see https://github.com/angular/angular/blob/master/modules/angular2/src/core/testability/get_testability.ts). We should use this API to prevent future breakages / hard to explain errors...

**Comment by tbosch** [comment]
The hack was introduced here: https://github.com/angular/angular/pull/3822

**Comment by mlaval** [comment]
Not as easy as it seems since we have tests which need to wait for Angular 2, and some that don't.
If waiting can be done with the Testability API, we need a way to find out if a particular a test needs to wait.

@tbosch Any suggestion on how to achieve that in a generic way please? I.e. without setting a flag or doing it in each test?

**Comment by tbosch** [comment]
I think for the examples/benchmarks that don't use `bootstrap` we should just create the `Testability` registry manually in the example/benchmark, so that the integration works for all e2e tests.

**Comment by juliemr** [comment]
FYI, this should eventually be done in Protractor. Setting up the next Protractor release to take care of it.
