### ISSUE TITLE
Angular Docs Misguiding Report

### ISSUE THREAD

**Issue by kannanwisen** [angular/angular#38302]
# 📚 Docs or angular.io bug report

### Description

I think, the below statement is misguiding the concept

You can't use the local variable technique if an instance of the parent component class must read or write child component values or must call child component methods.

For example

<wisen-child #child>  &lt;/wisen-child>

<button (click)="buttonClicked(child)">Click&lt;/button>

In the parent component, using the child local variable as parameter we can read or write child component values or even we can call the child component method.

### What's the affected URL?**
https://angular.io/guide/component-interaction#parent-calls-an-viewchild

## 🔥 Exception or Error
<pre><code>

</code></pre>

**Comment by MrJithil** [comment]
@kannanwisen You are right. We will get the instance of a child component using the _local variable_ technique.

But, for that, we need the _template support_. Also, this _child component instance_ will not be available everywhere in the component. To solve this issue, we can use the _ViewChild_ decorator.

So, we can rewrite the sentences you mentioned below. You can't use the local variable technique if an instance of the parent component class must read or write child component values or must call child component methods **_globally_**.

Here I added the word `globally` to correct the intention of the statement. Please review. So that I can create PR.

CC: @kapunahelewong @gkalpak @jbogarthyde @wardbell @IgorMinar

**Comment by kannanwisen** [comment]
@MrJithil 

Perfect.
