### ISSUE TITLE
Interface R3ComponentMetadata contains invalid comment or type when using strict TS

### ISSUE THREAD

**Issue by SchnWalter** [angular/angular#38407]
# 📚 Docs or angular.io bug report

### Description

While reading about the new RFC, I saw that the `R3ComponentMetadata` interface contains an error, it's either a comment error or the type for [template.ngContentSelectors](https://github.com/angular/angular/blob/3a4e1b8f860eb7449144a0866de750d9e18d2501/packages/compiler/src/render3/view/api.ts#L133-L137) needs to be updated to include a `null` selector. (see code block bellow)

### What's the affected URL?**
N/A

### Reproduction Steps**
N/A

### Expected vs Actual Behavior**
N/A

## 📷Screenshot
N/A

## 🔥 Exception or Error
```ts
export interface R3ComponentMetadata extends R3DirectiveMetadata {
  // ...
  template: {
    // ...
    /**
     * Any ng-content selectors extracted from the template. Contains `null` when an ng-content
     * element without selector is present.
     */
    ngContentSelectors: string[];
  }
  // ...
}
```

### Browser info
N/A

### Anything else relevant?

Judging that `$ngDeclareComponent` might become a Public API after #38366, this should be fixed soon.

**Comment by JoostK** [comment]
Heya, you're technically correct that the type of `ngContentSelectors` is inaccurate (the comment itself is accurate). The reason for the type to be inaccurate is because of some code that was written in the early days of Angular where strict null checks were not yet a thing, and the data in this property interacts with this older code. This is something that needs to be aligned going forward, but hasn't been done because of the impact it has on the View Engine compiler that is still around.

Regarding your comment about `$ngDeclareComponent`; the `R3ComponentMetadata` interface in itself is not exactly the linker metadata. For example, `R3ComponentMetadata.template` contains the parsed template AST nodes, whereas the linker will simply encode the template as its original string (otherwise the whole AST representation would have to be stable). If you're interested, you can find a spike for the linker [in the spikes/linker branch here on Github](https://github.com/angular/angular/commits/spikes/linker), in particular [this file](https://github.com/angular/angular/blob/5a2e78ccbe9e74b058a27f667c92023976602ad6/packages/compiler-cli/linker/src/linker.ts) that implements the transformation from linker metadata into `R3ComponentMetadata`.
