### ISSUE TITLE
Add "external link" icon to Blog link in main nav toolbar

### ISSUE THREAD

**Issue by sjtrimble** [angular/angular#38412]
# 📚 Docs or angular.io bug report

### Description
It is unexpected for the user to be taken outside of the AIO experience (and domain) to the Medium domain within the same window.

Recommend adding the "open_in_new" icon next to the text "Blog" in nav to indicate to the user that it is an external link.

![Screen Shot 2020-08-11 at 11 00 46 AM](https://user-images.githubusercontent.com/2958442/89932404-6dc53300-dbc2-11ea-9e57-ff6b4c0e821c.png)

- Add `<i class="material-icons">open_in_new</i>` inside of `nav-link-inner` `<span>` element
- `margin-left: 0.5rem;` and `opacity: .8;` on `<i>` icon element
- Add `display: flex;` and `align-items: center;` to `aio-top-menu ul li a.nav-link .nav-link-inner` element

**(CC: @gkalpak Need help with this one as the nav content gets pulled in dynamically and does not support icons at the moment.)**

### What's the affected URL?**
All URLs

### Reproduction Steps**
Main nav toolbar on all pages

## 📷Screenshot
Current view:
![Screen Shot 2020-08-11 at 11 02 48 AM](https://user-images.githubusercontent.com/2958442/89932259-35bdf000-dbc2-11ea-8b18-3c3a1e56f979.png)

**Comment by gkalpak** [comment]
We could add a style similar to [src/styles/0-base/_typography.scss#L208-L219][1], but instead fo targeting `<aio-docs-viewer>` we could target `<aio-top-menu>` or something.

[1]: https://github.com/angular/angular/blob/8366effeec8e74c1a11d2a6e1a48d42e849e4653/aio/src/styles/0-base/_typography.scss#L208-L219

**Comment by dario-piotrowicz** [comment]
@gkalpak I tried with your styles suggestion but it was problematic since the docs links have the icon outside the `a` itself whilst here given the hover styling I think we need the icon to be inside of the `a`. Moreover the styling in the nav required some tweaking specific for that element (and the doc link icons already have some tweaking of their own, so there isn't really that much to reuse there).

Anyways I am still using the same icon so it shouldn't really be too bad that we are not reusing that style :slightly_smiling_face: 

I hope that is fine :slightly_smiling_face:

**Comment by gkalpak** [comment]
Thx for looking into this, @dario-piotrowicz. Let's discuss on the PR.
