### ISSUE TITLE
service-worker: npm property "sideEffects": false -> remove serviceworker from prod build in main.*.js

### ISSUE THREAD

**Issue by software-engineering** [angular/angular#38427]
# 🐞 bug report

### Description

service-worker module is missing if i use the npm property "sideEffects": false 
the think the tree-shaking removes the serviceworker from prod build main.*.js
**THX for your TIME & HELP**

## 🔬 Minimal Reproduction

Github: 
`git clone git@github.com:software-engineering/angular-service-worker--npm-side-effects-false.git`
`cd angular-service-worker--npm-side-effects-false`
`npm install`
`npm run build -- --prod`

> ...
> chunk {1} main.0a5528dd4fc41fa38628.js (main) 625 bytes [initial] [rendered]
> ...

missing serviceworker loading in code, seach ->  "ngsw-worker.js"
Didn't work with npm sideEffects: false

**or all cli commands:** 

`ng new test-sw --create-application false --strict`
`cd test-sw`
`ng generate application demo --strict`

> ? Would you like to add Angular routing? (y/N) Y
> ? Which stylesheet format would you like to use?
> ❯ SCSS   [ https://sass-lang.com/documentation/syntax#scss 

`ng add @angular/pwa --project demo`

Add to package.json following line
`"sideEffects": true,`
`npm run build -- --prod`

> ...
> chunk {1} main.25699e2b034468f910e4.js (main) 226 kB [initial] [rendered]
> ...

serviceworker loading script exists in code, search : ngsw-worker.js
Work with npm sideEffects: true

Change in package.json following line
`"sideEffects": false,`
`npm run build -- --prod`

> ...
> chunk {1} main.0a5528dd4fc41fa38628.js (main) 625 bytes [initial] [rendered]
> ...

missing serviceworker loading script in code, seach ->  "ngsw-worker.js"
Didn't work with npm sideEffects: false

## 🌍  Your Environment

**Angular Version:**
<pre><code>

❯ ng --version

     _                      _                 ____ _     ___
    / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
   / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
  / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
 /_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
                |___/
    

Angular CLI: 10.0.5
Node: 14.8.0
OS: linux x64

Angular: 10.0.8
... animations, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, router
Ivy Workspace: Yes

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.1000.5
@angular-devkit/build-angular     0.1000.5
@angular-devkit/build-optimizer   0.1000.5
@angular-devkit/build-webpack     0.1000.5
@angular-devkit/core              10.0.5
@angular-devkit/schematics        10.0.5
@angular/cli                      10.0.5
@ngtools/webpack                  10.0.5
@schematics/angular               10.0.5
@schematics/update                0.1000.5
rxjs                              6.5.5
typescript                        3.9.7
webpack                           4.43.0

-----------------------------------------------------------

</code></pre>

**Comment by alan-agius4** [comment]
Hi @software-engineering, 

Can you please clarify where are you adding the `"sideEffects": false` property? If you are adding it in the root level `package.json` it is expected that the application will break, because `main.ts` does contain side-effects.

Hence, the `sideEffects: false` flag is present in `projects/demo/src/app/package.json`

**Comment by alan-agius4** [comment]
Hi again @software-engineering,

Just realised you provided a reproduction. 

Looking at this https://github.com/software-engineering/angular-service-worker--npm-side-effects-false/blob/2bf5cb047859e11c4c4ddf1416edf65f25dd0fe5/package.json#L4 you are indeed setting that the entire workspace is sideEffect free which is not the case because `main.ts` has side effects (https://github.com/software-engineering/angular-service-worker--npm-side-effects-false/blob/2bf5cb047859e11c4c4ddf1416edf65f25dd0fe5/projects/demo/src/main.ts#L7-L12) and therefore the application is breaking. 

Only files under the `app` folder are side effects free, and therefore this package manifest exists .https://github.com/software-engineering/angular-service-worker--npm-side-effects-false/blob/master/projects/demo/src/app/package.json
