### ISSUE TITLE
JSONP injected script did not invoke callback.

### ISSUE THREAD

**Issue by mikelurquia** [angular/angular#38434]
I am trying to consume the following JSONP file with angular 10.0.8 and httpclient:
[https://opendata.euskadi.eus/contenidos/ds_informes_estudios/calidad_aire_2020/es_def/adjuntos/estaciones.json](https://opendata.euskadi.eus/contenidos/ds_informes_estudios/calidad_aire_2020/es_def/adjuntos/estaciones.json)

The following is my service class:

```
import { Injectable } from '@angular/core';
import { HttpClient, HttpClientJsonpModule } from '@angular/common/http';
import { Observable } from 'rxjs';
import { Revision } from '../models';
 
@Injectable()
export class RevisionService { 

   baseURL : string = "https://opendata.euskadi.eus/contenidos/ds_informes_estudios/calidad_aire_2020/es_def/adjuntos/estaciones.json";
 
   constructor(private http:HttpClient){}
 
   getRevision (): Observable<Revision[]> {
       return this.http.jsonp<Revision[]>(this.baseURL, 'jsoncallback');
   }

}
```
Whis is consumed by:

```
import { Component }       from '@angular/core';
import { RevisionService } from '../../../core/services/revision.service';
import { Revision }        from '../../../core/models/revision';

@Component({templateUrl: './dashboard.component.html'})

export class DashboardComponent  {

    revisions : Revision[] = [];
    errorMessage;

    constructor(private revisionService : RevisionService) {
    	this.getRevision();
    }

    public getRevision() {
     	  this.revisionService.getRevision().subscribe((jsonCallback) => {
    		this.revisions    = jsonCallback;
      	  }, (error) => {
    		this.errorMessage = error.message;
    	  }, () => {});
    }
}
```
Every time I try to make the request, I get the following error:

```
Error: JSONP injected script did not invoke callback.
    at HTMLScriptElement.onLoad (http://localhost:4200/vendor.js:9516:22)
    at ZoneDelegate.invokeTask (http://localhost:4200/polyfills.js:3586:173)
    at Object.onInvokeTask (http://localhost:4200/vendor.js:86608:25)
    at ZoneDelegate.invokeTask (http://localhost:4200/polyfills.js:3586:56)
    at Zone.runTask (http://localhost:4200/polyfills.js:3336:39)
    at ZoneTask.invokeTask [as invoke] (http://localhost:4200/polyfills.js:3681:28)
    at invokeTask (http://localhost:4200/polyfills.js:5212:12)
    at HTMLScriptElement.globalZoneAwareCallback (http://localhost:4200/polyfills.js:5243:11)
```

Looking at the URL generated by the request, I see:
`https://opendata.euskadi.eus/contenidos/ds_informes_estudios/calidad_aire_2020/es_def/adjuntos/estaciones.json?jsoncallback=ng_jsonp_callback_0`

Which doesn't look bad at all. The request is also properly executed, and the response I get is the actual file:

```
jsonCallback([ {
  "Name" : "3 DE MARZO",
  "Province" : "Araba/Álava",
  "Town" : "Vitoria-Gasteiz",
  "Address" : "Plaza Tres de Marzo, s/n",
  "CoordenatesXETRS89" : "527141,4365",
  "CoordenatesYETRS89" : "4744882,8893",
  "Latitude" : "42,85604797053618",
  "Longitude" : "-2,667784994714487"
}, ... ]);
```
Am I missing something here? The documentation on [angular http](https://angular.io/guide/http) mentions setting the callback function as a parameter, which I surely do. I've been banging my head against a wall for a couple weeks now to no avail.

**Comment by JoostK** [comment]
This appears to be working as expected.

The callback you provide corresponds with the query parameter that the API accepts to change the function name in the response. In this case, the server responds with a call to `jsonCallback`, so that function is called when the requests completes. However, Angular expects that `ng_jsonp_callback_0` is called, as that is the unique response handled for this request. These have to be unique in order to support concurrent requests, where it would otherwise be impossible to correlate responses with requests.

Typically, JSONP endpoints accept a query parameter that indicates what callback function to call. The name of that query parameter is what you specified in `this.client.jsonp(url, 'jsoncallback')`, so that's why Angular adds `?jsoncallback=ng_jsonp_callback_0` to the URL. It is then up to the server to use the provided callback name in the response, which is not what's happening here. I don't know if this particular API does allow the callback function to be modified using some different query parameter. If it does not, I'm afraid that `HttpClient` cannot be used for this case.

**Comment by mikelurquia** [comment]
Thanks for the reply.

Now I think I understand how it works. At first I thought angular was the one tasked with taking the API's callback function and modify it internally to match its own callback in order to support concurrent requests. It seems it actually works the other way around and I was wrong.

I am afraid the API is not mine to tweak, so I shall try with a different library. I am closing the issue.

Thank you so much!
