### ISSUE TITLE
docs: update Ivy compatibility guide to mention DebugElement behavior difference related to styling

### ISSUE THREAD

**Issue by turtledev1** [angular/angular#38451]
# 🐞 bug report

### Affected Package
Ivy renderer

### Is this a regression?
It's working with ivy disabled

### Description

 A clear and concise description of the problem...

## 🔬 Minimal Reproduction
In my component:
`<span [style]="colorStyle"></span>`

`public get colorStyle(): { [key: string]: string } {
    return { 'background-color': '#026cdf' };
}`

In my test:
`it('should display the open color', () => {
            expect(getElement().styles['background-color']).toBe('#026cdf');
        });`

## 🔥 Exception or Error
`Error: Expected 'rgb(2, 108, 223)' to be '#026cdf'`

## 🌍  Your Environment

**Angular Version:**
<pre><code>

     _                      _                 ____ _     ___
    / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
   / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
  / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
 /_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
                |___/
    

Angular CLI: 9.1.12
Node: 12.3.1
OS: darwin x64

Angular: 9.1.12
... animations, cli, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, router
Ivy Workspace: Yes

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.901.12
@angular-devkit/build-angular     0.901.12
@angular-devkit/build-optimizer   0.901.12
@angular-devkit/build-webpack     0.901.12
@angular-devkit/core              9.1.12
@angular-devkit/schematics        9.1.12
@angular/cdk                      9.2.4
@angular/material                 9.2.4
@ngtools/webpack                  9.1.12
@schematics/angular               9.1.12
@schematics/update                0.901.12
rxjs                              6.5.3
typescript                        3.7.3
webpack                           4.42.0
</code></pre>

**Anything else relevant?**

**Comment by AleksanderBodurri** [comment]
This is not a bug, nor does it have anything to do with Angular or Ivy. Angular uses the `.style` DOM property to set css styles.
https://github.com/angular/angular/blob/6768fe9927ad4b9b81c5f8094c42c771d1047f56/packages/platform-browser/src/dom/dom_renderer.ts#L231

Browsers serialize the input value according to the CSS Object Model spec:

https://drafts.csswg.org/cssom/#css-declaration-blocks

> To update style attribute for declaration block means to run the steps below:
> 
> 1. Assert: declaration block’s computed flag is unset.
> 2. Let owner node be declaration block’s owner node.
> 3. If owner node is null, then return.
> 4. Set declaration block’s updating flag.
> 5. Set an attribute value for owner node using "style" and the result of **serializing declaration block**.
> 6. Unset declaration block’s updating flag.

https://drafts.csswg.org/cssom/#serializing-css-values 


> If \<color\> is a component of a resolved or computed value, then return the color using the rgb() or rgba() functional notation as follows:
If the alpha component of the color is equal to one, then return the serialization of the rgb() functional equivalent of the opaque color.
If the alpha component of the color is not equal to one, then return the serialization of the rgba() functional equivalent of the non-opaque color.

**Comment by turtledev1** [comment]
If it doesn't have anything to do with Ivy, how come the result is different if I activate/deactivate Ivy?

Without Ivy I have to assert on the hex color, and with Ivy activated I have to assert on the rgb color.

**Comment by AleksanderBodurri** [comment]
@turtledev1 could you make a minimal reproduction app on stackblitz?

**Comment by turtledev1** [comment]
https://stackblitz.com/edit/angular-ivy-vpg67q?file=tsconfig.json

Just change the `"enableIvy": false,` to true, and test will fail

**Comment by AleksanderBodurri** [comment]
Thanks for making the reproduction app! Heres what I found,

Without Ivy the PRE_R3 debug element stores the raw style value. `debugEl.styles[style] = value;`. `debugEl.styles` is just a regular javascript object.
https://github.com/angular/angular/blob/6768fe9927ad4b9b81c5f8094c42c771d1047f56/packages/core/src/view/services.ts#L818-L824

With Ivy, the POST_R3 debug element's `styles` property shadows the `style` property on the actual DOM node.

<img width="358" alt="Screen Shot 2020-09-15 at 1 22 33 PM" src="https://user-images.githubusercontent.com/39253660/93243705-95c22c00-f756-11ea-8042-76700896a93e.png">

This is why `fixture.debugElement.query(By.css("span")).styles["background-color"]` returns different values. Without Ivy the look up is done on a regular javascript object that has the raw style value. With Ivy the look up is done against the `CSSStyleDeclaration` object on the actual DOM node (in this case the browser serialization that I described above applies).

You'll notice that in both cases, the actual inline style on the dom node is the same.

Without Ivy:
<img width="519" alt="Screen Shot 2020-09-15 at 1 27 36 PM" src="https://user-images.githubusercontent.com/39253660/93244159-46c8c680-f757-11ea-9d54-c1fa0daef0f5.png">
With Ivy:
<img width="563" alt="Screen Shot 2020-09-15 at 1 27 17 PM" src="https://user-images.githubusercontent.com/39253660/93244191-547e4c00-f757-11ea-94d8-09fa11f68c59.png">

I would argue that the DebugElement behaviour in Ivy is preferable because it more closely adheres to the behaviour you would expect to see in your browser.

**Comment by atscott** [comment]
As mentioned by @AleksanderBodurri, this was an intended change in Ivy to move away from the proxy tracking for `DebugElement`s in VE and instead use the native values in Ivy. That said, this should likely be included in the Ivy [compatibility guide](https://angular.io/guide/ivy-compatibility).

**Comment by AleksanderBodurri** [comment]
@atscott my guess is that since https://github.com/angular/angular/pull/43860 we no longer need this issue open. Going to close. If i'm mistaken we can reopen.
