### ISSUE TITLE
NgForm renders form controls slower than expected

### ISSUE THREAD

**Issue by anphamv** [angular/angular#38478]
# 🐞 bug report

### Affected Package

 The issue is caused by package @angular/forms

### Is this a regression?
No

### Description
Unable to access controls object of NgForm when Angular starts rendering component

## 🔬 Minimal Reproduction

If you access the controls object of NgForm like this:
![image](https://user-images.githubusercontent.com/59089308/90311698-01cb2d80-df28-11ea-9fa2-aa46d6dcf8c3.png)

When Angular starts rendering my component, it said that there's no such properties like i have in my form controls:
![image](https://user-images.githubusercontent.com/59089308/90311713-3b039d80-df28-11ea-8d4d-5e3f2a97da65.png)

I console.log() the controls of NgForm, at first, it has nothing like you guys see an empty object in my console, but then chrome developer tool tells 'Value below was evaluated just now'. Does that mean when Angular starts rendering my component and access the form controls, the form controls haven't been there yet?

## 🔥 Exception or Error
![image](https://user-images.githubusercontent.com/59089308/90311776-093f0680-df29-11ea-975c-3ac6136bca5e.png)

<pre><code>

</code></pre>

## 🌍  Your Environment

**Angular Version:**
<pre>Angular CLI: 10.0.6
Node: 12.16.3      
OS: win32 x64      

Angular: 10.0.9
... animations, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, router
Ivy Workspace: Yes

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.1000.6
@angular-devkit/build-angular     0.1000.6
@angular-devkit/build-optimizer   0.1000.6
@angular-devkit/build-webpack     0.1000.6
@angular-devkit/core              10.0.6
@angular-devkit/schematics        10.0.6
@angular/cli                      10.0.6
@ngtools/webpack                  10.0.6
@schematics/angular               10.0.6
@schematics/update                0.1000.6
rxjs                              6.5.5
typescript                        3.9.7
webpack                           4.43.0<code>

</code></pre>

**Anything else relevant?**

**Comment by AndrewKushnir** [comment]
Hi @anphamv, thanks for reporting this issue. However, you didn't provide sufficient information for us to understand and reproduce the problem. Please check out [our submission guidelines](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-submitting-an-issue) to understand why we can't act on issues that are lacking important information. Could you please provide a repro using [Stackblitz](https://stackblitz.com/) so that we can have a look? Thank you.

**Comment by anphamv** [comment]
Thanks for replying, this is a repo for reproduction: https://stackblitz.com/edit/angular-ivy-xj5dck?file=src/app/app.component.html

**Comment by jnizet** [comment]
The workaround is to introduce template variables for your fields, and refer to those variables instead of using `f.controls.xxx`, using `#ngModel="email"` for example.

See https://stackblitz.com/edit/angular-ivy-rzkev5?file=src/app/app.component.html

**Comment by indraraj26** [comment]
but why above approach is not working ?

**Comment by jnizet** [comment]
As far as I understand it, here's what happens, chronologically:

- The change detection happens for the app component
- As part of this change detection, the expressions in its template are evaluated. That fails because `f.controls` doesn't contain the child controls yet. 
- If the previous step didn't fail, then the change detection would then be triggered for the directives and components used inside the template.
- As part of these change detections, the `ngOnChanges`method of the child ngModel directives would be called, and that's what would register the child controls into their parent NgForm directive.
