### ISSUE TITLE
Contributions made simpler

### ISSUE THREAD

**Issue by waterplea** [angular/angular#38486]
I just finished my first contribution to the framework with a bugfix. I have a feeling the process could be improved.

# CI builds were failing because linting did not pass or files were not properly formatted

Formatting files could be automated on precommit hook. Same goes for linting. It could be autofixed or if it failed to do so, it could tell me there are issues before I've committed and pushed my changes. Not only this speeds things up for me as a contributor but it also does not waste CI resources on the cloud. There are multiple packages out there that do so, I'm sure. In my projects I use Prettier and lint-staged to only process the files that were changed in the commit.

# CI builds were failing because of wrong commit message format

Pretty sure this could also be checked on precommit hook, but I have no suggestions on the tools here. Would be better to not allow people to make wrong commit rather than force them to use advanced git techniques to revert commits and force push.

**Comment by JoostK** [comment]
@josephperrott has you covered:

- #38402: auto-format stages files when committing (recently landed)
- #38457: wizard for building commit message (still open)

I do believe that commit messages are already validated upon commit. Note that just auto-formatting may still allow the linting job to fail, if e.g. semicolons are missing, so that may be an area that may be improved even further.

**Comment by waterplea** [comment]
Right. Looks like it is covered indeed. Thank you!
