### ISSUE TITLE
ViewContainerRef on Portal Overlay createComponent() fails.

### ISSUE THREAD

**Issue by zehavibarak** [angular/angular#38490]
reproduction: https://stackblitz.com/edit/angular-ivy-mcndqk?file=src/app/first-component/first-component.component.ts
no exception thrown. no tag added to dom.

**Comment by JoostK** [comment]
Hello, it is really not clear what you're trying to report. Please open a new issue and fill in the issue template. Crucially, there's currently no reproduction steps and actual vs expected behavior, which means I have not clue what the StackBlitz is trying to convey.

**Comment by kenaidri** [comment]
No by mistake i did that sure im not meaning that he is treated badly with me , sory

Nasser alkonidri
best regards

On 17 Aug 2020, at 10:27, Joost Koehoorn <notifications@github.com> wrote:

﻿

Closed #38490<https://github.com/angular/angular/issues/38490>.

**Comment by kenaidri** [comment]
No by mistake i did that sure im not meaning that he didn’t treated badly with me , sory

Nasser alkonidri
best regards

On 17 Aug 2020, at 10:27, Joost Koehoorn <notifications@github.com> wrote:

﻿

Hello, it is really not clear what you're trying to report. Please open a new issue and fill in the issue template. Crucially, there's currently no reproduction steps and actual vs expected behavior, which means I have not clue what the StackBlitz is trying to convey.
