### ISSUE TITLE
Documents translation contribute

### ISSUE THREAD

**Issue by nhaancs** [angular/angular#38503]
Hello,  how can I contribute a Vietnamese translation for docs at https://angular.io/docs.
Thank you

**Comment by Splaktar** [comment]
I am not aware of anyone starting the effort. I would suggest that you organize some friends or a meetup group to help with it, since it is not a small effort.

So far, these efforts have all happened in separate repos since the AIO site isn't set up for i18n and using different language files.

For example:
- Spanish got started recently, you can talk to me about it - https://github.com/angular-hispano/angular
- The Japanese version has been around for a good while and @lacolaco can talk to you about it - https://github.com/angular/angular-ja
- The Chinese version has also been around for a long time - https://github.com/angular/angular-cn/tree/aio

**Comment by Splaktar** [comment]
@nhaancs sorry for the delay in responding. Yes, you can fork one of the existing translation repos (best if you know Spanish, Mandarin, Japanese, or Korean) or fork the main `angular/angular` repo.  You'll need to translate some of the `.md` files if not everyone on your team speaks/reads English. But then most of the content is found in the `aio/` folder. Most of the translations are in `.md` files, but some are in JSON (like navigation).
