### ISSUE TITLE
Router doesnt update URL for known routeguarded routes with HashLocationStrategy

### ISSUE THREAD

**Issue by geometricpanda** [angular/angular#38531]
# 🐞 bug report

### Affected Package

 The issue is caused by package @angular/router@10.0.10 (may have been present previously)

### Is this a regression?

 Unknown

### Description
Issue is only present when using the HashLocationStrategy.

When accessing a route within the same lazy routing module which has a guard returning a URL tree within the same routing module, the route is updating however the URL is not.

For example visit: https://angular-routeguard-redirect.netlify.app/#/register
Manipulate the URL to be: https://angular-routeguard-redirect.netlify.app/#/register/two
The guard will return a URL Tree redirecting you to `['/','register']`
The route at https://angular-routeguard-redirect.netlify.app/#/register will be rendered
The URL will still be https://angular-routeguard-redirect.netlify.app/#/register/two 

Refreshing causes the redirect to occur.

Routes `/register`, `/register/two`, `/register/three` are all part of the same routing module (https://github.com/geometricpanda/routeguard-redirect/blob/master/src/app/pages/register/register-routing.module.ts)
which is loaded here https://github.com/geometricpanda/routeguard-redirect/blob/master/src/app/app-routing.module.ts

## 🔬 Minimal Reproduction
https://github.com/geometricpanda/routeguard-redirect
hosted at https://angular-routeguard-redirect.netlify.app/#/register

## 🔥 Exception or Error
None Reported

## 🌍  Your Environment

**Angular Version:**
<pre><code>

     _                      _                 ____ _     ___
    / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
   / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
  / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
 /_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
                |___/
    

Angular CLI: 10.0.6
Node: 14.2.0
OS: darwin x64

Angular: 10.0.10
... animations, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, router
Ivy Workspace: Yes

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.1000.6
@angular-devkit/build-angular     0.1000.6
@angular-devkit/build-optimizer   0.1000.6
@angular-devkit/build-webpack     0.1000.6
@angular-devkit/core              10.0.6
@angular-devkit/schematics        10.0.6
@angular/cli                      10.0.6
@ngtools/webpack                  10.0.6
@schematics/angular               10.0.6
@schematics/update                0.1000.6
rxjs                              6.5.5
typescript                        3.9.7
webpack                           4.43.0
</code></pre>

**Anything else relevant?**

**Comment by atscott** [comment]
Hi @geometricpanda, can you test this out in the 10.1 rc? I updated the router package in your example to `10.1.0-rc.0` and it seemed to work as expected.

**Comment by geometricpanda** [comment]
No luck i'm afraid
Assuming i've done the upgrade right ([PR here](https://github.com/geometricpanda/routeguard-redirect/pull/1))?
I've got a quick Netlify hosting of that branch [here](https://5f4d583e5e74c900079d5a28--angular-routeguard-redirect.netlify.app/#/) 

I've uploaded a video to Youtube [here](https://www.youtube.com/watch?v=1u7IbNdZLZ0) showing the issue against that branch
- sorry about my terrible screen presenting skills

**Comment by atscott** [comment]
Ah, yea this is definitely a bug. The logic which handles the redirection from the returned `UrlTree` assumes that the browser address bar was not yet updated (which would be the case if navigation were instead triggered through `router.navigate`). 

The scheduled navigation from the redirect gets ignored because the router thinks that the `browserUrlTree` already matches the attempted navigation. This is only partially accurate -- while the navigation shouldn't occur (we're already on the `/register` page since we never really navigated to `/register/two`), the browser url still needs to be synced with the internal state.

**Comment by atscott** [comment]
Closing since I think this was likely fixed by https://github.com/angular/angular/commit/286b2807de61dcd6e24ced5c142fbc6eda9dfbec#diff-03cb1ea13f0b5890eb24ce6fef7a42eed85429da0a90cdb48ab06b58c30cb1c1 and/or https://github.com/angular/angular/commit/0e8548f667e5fdefa3ac7cdf1ba47e3e17011ffc#diff-03cb1ea13f0b5890eb24ce6fef7a42eed85429da0a90cdb48ab06b58c30cb1c1 
Since there's not a stackblitz, I can't quickly verify. Please let me know if the issue still exists in v13
