### ISSUE TITLE
Script to update all golden files at once

### ISSUE THREAD

**Issue by sonukapoor** [angular/angular#38632]
# 🚀 feature request

### Description

When working on `core` changes, sometimes you will need to update multiple golden files. It would be great to have a script that allows you to update all golden files at once without going through them one at a time.

**Comment by AndrewKushnir** [comment]
Just to add more context: currently we need to run commands to update test apps individually like this:
```
yarn bazel run --config=ivy //packages/core/test/bundling/hello_world:symbol_test.accept
yarn bazel run --config=ivy //packages/core/test/bundling/animation_world:symbol_test.accept
yarn bazel run --config=ivy //packages/core/test/bundling/hello_world_i18n:symbol_test.accept
...
```

The problem is that the list of apps change over time, so it's not convenient to just save the list of these commands somewhere.

The proposal is to have an ability to just run one command that would take care of checking/updating all apps at once, something like this:

```
yarn bazel run --config=ivy //packages/core/test/bundling:symbol_test.accept
```
