### ISSUE TITLE
Remove the first element or replace by the first child element (Replace prop in @View)

### ISSUE THREAD

**Issue by danicomas** [angular/angular#3866]
The code rendered of my component is the following:

```html
<ngdialog class="ng-binding">
   <div class="ng-binding">
    dialog
   </div>
</ngdialog>
```

By I want this:

```html
   <div class="ng-binding">
    dialog
   </div>
```

Now is it possible? We need some property for example replace in @ View?

```js
@Component({
  selector: 'ngdialog'
})
@View({
  template: 
  `<div>
    {{title}}
  </div>`,
  replace: true
})
```

**Comment by danicomas** [comment]
I have found a way:

Property host

```js
@Component({
  selector: 'ngdialog',
  host: {
    class: 'dialog-container'
  }
})
@View({
  templateUrl: 'dialog.html'
})

// Component controller
class Dialog {
  title:string;
  constructor() {
    this.title = "dialog"
  } 
}
```

```htlml
<ngdialog class="ng-binding">  
    dialog
</dialog>
```

**Comment by ceolter** [comment]
+1

i would like to either a) see 'replace' in the component view. problem is with style, eg:

```
<my-grid style='width: 200px;'>
```
here, my-grid is my component, but because the component is not a valid html dom element, the width attribute is ignored, so no way to set the width here. angular 1 dealt with this by using 'replace' and all the attributes from the directives tag were copied down.

**Comment by gionkunz** [comment]
Replace was deprecated in Angular 1, probably because of some architectural issues of removing the DOM element that originally was linked to the directive. I guess, even only because of not re-introducing a previously deprecated features, this could be problematic. Also thinking of shadow root and host element, I guess this could be even more of a problem.

In general I think `replace` wasn't a very good idea to begin with. It's totally against a clean DOM structure and if you're structuring your components well, there shouldn't be a need for that at all.

@ceolter in modern HTML there isn't really a "invalid dom element" if you think in terms of custom element specification. The issue you're having is related to the fact that the browser will default to `display: inline` on unknown elements and those can't have certain box properties. Just give it a `display: block` style and you should be fine.

**Comment by pkozlowski-opensource** [comment]
@gionkunz is right - the current thinking is that we don't want to re-introduce `replace: true` as it makes it hard to reason about directives and components matching the same host element. From the cases presented so far it looks like there is always a better approach with host attributes / properties.

Closing for now, happy to re-visit if different cases arise.

**Comment by ceolter** [comment]
@pkozlowski-opensource Excellent, makes sense. I shall try that. Many thanks.

**Comment by Andy1605** [comment]
@danicomas Could you please post the dialog.html as well, because i do not really understand what this class 'dialog-container' references to... Sorry, i guess i didn't get the entire host property thing at all for that matter

**Comment by zoechi** [comment]
If you want to keep the tag but make it a custom element just use an attribute selector

    <div my-button>xxx</div>
    
    @Component({selector: '[my-button], ...})

**Comment by Andy1605** [comment]
@zoechi Thanks for your answer, but this wasn't exactly what i was asking for, sorry.
I am aware of this approach which is not a proper solution for me because the user of my components could change the behavior/appearance of those components by not using the element i was intending to use as root element and even if i choose the selector like this 'table[my-table]', the user would have to know that he needs to use a <table> for that. Which kind of obfuscates the view code as well, since i have to look for the component attribute within a div or a table or whatever it is. This secondly produces interface integrity problems IMHO since i could change my component selector from table to another super fancy component and the user would have to change his view code as well or am i wrong here. That is for example exactly what i have to do now when i port my angular 1.x components and views.

Even if i wouldn't care about another wrapping element, the user of the component would have to make sure that he uses display: block style on that component to make the style work and this is just in case a div-like behavior is appreciated.

That is why i am interested in this **host ** solution of **danicomas ** which obviously solved that problem for him.

**Comment by lsilva-kununu** [comment]
Sitll without any resolution? I dont like attribute selectors :'(
