### ISSUE TITLE
Investigate sharding the build

### ISSUE THREAD

**Issue by alexeagle** [angular/angular#3869]
Our build is slow. Maybe we could be parallelizing tests, or maybe we are needlessly waiting for something to finish and could have already started something else (figure out the critical path)

from https://github.com/angular/angular/commit/30bd2a3fc72f8f1cdb0ffc4b9d11b4ca42e9ece7#commitcomment-12705576
see https://stripe.com/blog/distributed-ruby-testing as a success story

**Comment by NathanWalker** [comment]
+1 I am trying to help contribute at the moment, but the build and running tests thrashes my system:
MacBook Pro 2.8 GHz Intel Core i7 with 4 GB RAM.

I'm trying to do a rather easy 1 hr estimate Issue but I'm staring at `Starting broccoli.js.dev` for an incredibly unreasonable amount of time. It's going to end up taking me 3 hours to complete the task in order to run the build and test it where I was done with the code 2 hours ago. :(

**Comment by alexeagle** [comment]
Your description is a lot more extreme than what we've experienced, or what this bug is referencing.
Can you double-check that you have the right versions of things (node 4, npm, etc?) which the build script will warn you about.
Try opening the Activity Monitor and see what is eating CPU? My guess is that you have less RAM than many of us on the team - try freeing some up by closing whatever apps you can?

**Comment by NathanWalker** [comment]
Thanks @alexeagle and sorry if this adds noise to this issue or any misunderstanding.
I'm excited for `beta` and want to help in anyway to push it there.
Here's my versions:
![screen shot 2015-10-26 at 1 59 13 pm](https://cloud.githubusercontent.com/assets/457187/10743309/7ec56270-7bef-11e5-9a5b-2a84cdb84f33.png)

Which also brings up point of confusion. Your `package.json` points to `gulp` `3.8.8` and upon a fresh install (no `node_modules`) folder, it installs `3.8.8` as expected. However your `gulpfile.js` contains `ES6` semantics. And supposedly only `>=3.9.0` works with `ES6`. So right from the start, I was unable to run `gulp build` (using the locally installed gulp) because it complatined of `=>` character. That was frustrating. Eventually I got it to run but only by using my globally installed `3.9.0`.

Then when I finally got `gulp build` to run, the `gulp` task takes nearly up to `1 GB` of RAM to run. Not too big of deal and certainly wouldn't think it would be hard on my system with `4 GB`. At any rate, it was slow.
![screen shot 2015-10-26 at 2 03 19 pm](https://cloud.githubusercontent.com/assets/457187/10743401/f69af602-7bef-11e5-9c97-341b5f5ff30f.png)

I have a lot of patience and again, want to help, so I waited it out. Then I wanted to test out my code by running unit tests in watch mode via `gulp test.unit.js`, and that was also pretty painful...
![screen shot 2015-10-26 at 2 33 40 pm](https://cloud.githubusercontent.com/assets/457187/10743427/2a9c603a-7bf0-11e5-8e7b-14ba68b7d291.png)

..nonetheless, it finally ran, woohoo! But, then I made a change to the test file to see live results and it picked up the changed file but the Chrome instance it had launched never reconnected and therefore I could never get unit testing in live mode to run. I tried several times :(

Anyway, amidst much frustration and patience, I was able to get this PR out, hopefully it helps :+1: 
https://github.com/angular/angular/pull/4905

I imagine a lot of others have run into similar experience in trying to help and probably gave up. My hunch is that if a couple things were either faster or simpler with the build, it may increase the amount of contributions, not sure.

I look forward to helping more when I can.

**Comment by alexeagle** [comment]
Thanks for digging in further. Indeed, it is hard to contribute right now and that's not good for the project, so we want to take this seriously.
@IgorMinar any other data points would be useful to diagnose?

**Comment by IgorMinar** [comment]
What HW are you running this on? Can you give us full spec, especially info about the disk.

**Comment by NathanWalker** [comment]
@IgorMinar 
MacBook Pro (13-inch, Late 2011)
2.8 GHz Intel Core i7
4 GB 1333 MHz DDR3
Intel HD Graphics 3000 384 MB

Disk:
TOSHIBA MK7559GSXF:

  Capacity:	750.16 GB (750,156,374,016 bytes)
  Model:	TOSHIBA MK7559GSXF                      
  Revision:	GQ108B  
  Serial Number:	Y18TT898T
  Native Command Queuing:	Yes
  Queue Depth:	32
  Removable Media:	No
  Detachable Drive:	No
  BSD Name:	disk0
  Rotational Rate:	5400
  Medium Type:	Rotational
  Partition Map Type:	GPT (GUID Partition Table)
  S.M.A.R.T. status:	Verified
  Volumes:
EFI:
  Capacity:	209.7 MB (209,715,200 bytes)
  BSD Name:	disk0s1
  Content:	EFI
  Volume UUID:	BDC1974F-6B8C-3DAE-9DB2-3AA3C17BF506
disk0s2:
  Capacity:	749.3 GB (749,296,615,424 bytes)
  BSD Name:	disk0s2
  Content:	Apple_CoreStorage
Recovery HD:
  Capacity:	650 MB (650,002,432 bytes)
  BSD Name:	disk0s3
  Content:	Apple_Boot
  Volume UUID:	049DD97F-8706-3783-8FCE-503F40B6AD40

**Comment by breath103** [comment]
any update on this? i'm using MacBook Air (13-inch, Mid 2011), 1.7 GHz Intel Core i5, 4GB 1333 MHz DDR3

and this is like painfully slow. i can't really test things after making change cause it's too slow on build and testing.

**Comment by mhevery** [comment]
This is obsolete, and no longer relevant / actionable. To keep our issues clean, we are aggressively closing them.

Working on a new build system.
