### ISSUE TITLE
Update guide says there should be a tsconfig.base.json

### ISSUE THREAD

**Issue by Waterstraal** [angular/angular#38743]
# 📚 Docs or angular.io bug report

### Description

In the [Angular Update Guide](https://update.angular.io/#9.1:10.0) it states that after upgrading there should be a `tsconfig.base.json`:

> Angular now recommends the use of a tsconfig.base.json to help organize the various typings contexts (shared, unit tests, end to end tests, application, etc). ng update will migrate you automatically.

## 🔬 Minimal Reproduction

open an Angular 9 directory and run `ng update @angular/core @angular/cli`

### What's the affected URL?**
https://update.angular.io/#9.1:10.0

### Expected vs Actual Behavior**
I would expect either a `tsconfig.base.json` file after the update, or a correct message on update.angular.io that does not mention a `tsconfig.base.json`

## 🌍  Your Environment
Win 10
node 12.4.0

**Comment by Waterstraal** [comment]
As an aside, I tried creating an old ng9 project by running `npx -p @angular/cli@9 ng new ng9-app --interactive=false`, but this generated an Angular 10 project. Does this not work anymore, or am I doing something wrong?

**Comment by gkalpak** [comment]
AFAICT, having a `tsconfig.base.json` used to be true for version 10.0 (which is what the update guide refers to, but was reverted (because it was causing other UX issues) in 10.1. This is why you are not getting a `tsconfig.base.json` file with `ng update @angular/core @angular/cli` (which updates to the latest stable version by default - currently 10.1.0).

So, the real issue here is that the update guide does not yet contain instructions for version 10.1.
Could you please open an issue on the [update guide repo][1] for this (and post it here for reference)?

<sub>Closing this issue, since there is nothing that needs to be done on this repo afaict.</sub>

[1]: https://github.com/StephenFluin/angular-update-guide/issues

**Comment by Waterstraal** [comment]
Thanks, I didn't know the update guide is in a seperate repo. 

I created a ticket in the update guide repo: [here](https://github.com/StephenFluin/angular-update-guide/issues/87)
