### ISSUE TITLE
feat(compiler): Support destructured variable assignment in structural directives

### ISSUE THREAD

**Issue by Babeetlebum** [angular/angular#38807]
# 🚀 feature request

### Relevant Package
This feature request is for @angular/common

### Description
Using the keyvalue pipe on a Map loses all naming and makes the template difficult to read 

**Example**
```typescript
@Component{...}
export class MyComponent {
    countryPoiMap = Map<Country, Poi>();
}
```
```html
<div *ngFor="let countryPoi of countryPoiMap | keyvalue">
   <!-- key is a country -->
   <div>{{ countryPoi.key.name }}</div>
   <!-- value is a poi -->
   <div>{{ countryPoi.value.name }}</div>
</div>
```

### Describe the solution you'd like
It would be great to be able to alias the result of a keyvalue pipe

**Example**
```html
<div *ngFor="let countryPoi of countryPoiMap | keyvalue:country:poi">
   <div>{{ country.name }}</div>
   <div>{{ poi.name }}</div>
</div>
```

**Other syntax**
```html
<div *ngFor="let { key as country, value as poi } of countryPoiMap | keyvalue">
   <div>{{ country.name }}</div>
   <div>{{ poi.name }}</div>
</div>
```

**Other syntax**
```html
<div *ngFor="(let countryPoi of countryPoiMap | keyvalue) as [country, poi]">
   <div>{{ country.name }}</div>
   <div>{{ poi.name }}</div>
</div>
```

### Describe alternatives you've considered
Implementing an `*ngLet` directive could alleviate this issue (#15280)

**Example**

```html
<div *ngFor="let countryPoi of countryPoiMap | keyvalue"
    *ngLet="countryPoi.key as country"
    *ngLet="countryPoi.value as poi"
>
   <div>{{ country.name }}</div>
   <div>{{ poi.name }}</div>
</div>
```

**Comment by petebacondarwin** [comment]
This is quite an interesting idea. It is worth noting that one the Ivy language service is rolled out we might have better intellisense of the "type" of the key and value properties, which might be enough to solve this problem for you?

In any case if we did implement it then we have to take into account that `KeyValuePipe` already takes a `compareFn` parameter, and that additional parameters would need to be strings for it to work. E.g.

```
<div *ngFor="let countryPoi of countryPoiMap | keyvalue:undefined:'country':'poi'">
```

**Comment by Airblader** [comment]
While the idea sounds nice I can't see how this could be typed such that the resulting aliases remain type safe, but if someone does know how that would work I'm happy to hear about it.

> Implementing an *ngLet directive could alleviate this issue (#15280)

That example wouldn't work because you cannot have multiple structural directives on one element. Unless ngLet is baked into the compiler as special syntax.

**Comment by Airblader** [comment]
Actually the primary proposed syntax just isn't possible with the current pipe mechanism as a pipe cannot create local variables. The best a pipe could do is

```
<div *ngFor="let countryPoi of countryPoiMap | keyvalue:country:poi">
   <div>{{ countryPoi.country }}</div>
   <div>{{ countryPoi.poi }}</div>
</div>
```

but I don't think this can be typed properly, see my comment above.

The second proposed syntax (alternative 1) would be closer to destructuring syntax (maybe changing it to that would be even better?) and not specific to KeyValuePipe but rather more general. I haven't checked but I'd assume this has been requested already somewhere?

The third proposed syntax doesn't really work IMO because it relies on object properties being ordered which is only true in ES2015 and later.

**Comment by petebacondarwin** [comment]
I think the only way this might be supported would be via the second proposed option - destructured variable assignment:

```html
<div *ngFor="let { key as country, value as poi } of countryPoiMap | keyvalue">
   <div>{{ country.name }}</div>
   <div>{{ poi.name }}</div>
</div>
```

I am going to retitle this issue, with this in mind, since implementing that feature would actually be more general than just the keyvalue pipe, and is more relevant to any structural directive that assigns a value to local context.

**Comment by petebacondarwin** [comment]
This is being tracked in the aggregate issue of #43485 for which we need to create a project proposal.

**Comment by alxhub** [comment]
Closing as a duplicate/specific case of #43485.
