### ISSUE TITLE
After upgrade, I receive this warning message:  router.js:2122 A router outlet has not been instantiated during routes activation. URL Segment:

### ISSUE THREAD

**Issue by tp1906** [angular/angular#38804]
# 🐞 bug report

### Affected Package
Can you pin-point one or more @angular/* packages as the source of the bug? 
router.js

### Is this a regression?

Did this behavior use to work in the previous version?
Yes, the previous version in which this bug was not present was: 9.1

### Description

 A clear and concise description of the problem...
 I receive this warning message:  router.js:2122 A router outlet has not been instantiated during routes activation. URL Segment:

## 🔥 Exception or Error
router.js:2122 A router outlet has not been instantiated during routes activation. URL Segment:

## 🌍  Your Environment

**Angular Version:**

Angular CLI: 10.1.0
Node: 12.18.0
OS: win32 x64

Angular:
...
Ivy Workspace:

Package                      Version
------------------------------------------------------
@angular-devkit/architect    0.1001.0
@angular-devkit/core         10.1.0
@angular-devkit/schematics   10.1.0
@schematics/angular          10.1.0
@schematics/update           0.1001.0
rxjs                         6.6.2

**Comment by AndrewKushnir** [comment]
Thanks for reporting this issue. However, you didn't provide sufficient information for us to understand and reproduce the problem. Please check out [our submission guidelines](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-submitting-an-issue) to understand why we can't act on issues that are lacking important information.

Could you please provide a minimal repro using [Stackblitz](https://stackblitz.com/) or in a form of Github repo, so that we can reproduce the problem?

**Comment by mereshow** [comment]
I don't know if I should intrude in another person bug report, but I created a demo for another bug report (flex-layout related) and it displays the problem @AndrewKushnir is reporting.

I created a demo in stackblitz: [demo](https://angular-ivy-8g5kxd.stackblitz.io/pages/dashboard)
And a [Github repo](https://github.com/mereshow/flex-layout-demo)

I tried to clone the repo several times from zero (to reproduce it as you would) but got an error when doing `npm install`. It works correctly if run as sudo (or npm clean-install).

**Comment by gallow** [comment]
Same issue using @angular/router@10.1.1
The issue was not present in 10.0.14

**Comment by nutza249949** [comment]
i

**Comment by nutza249949** [comment]
j

**Comment by nutza249949** [comment]
y

**Comment by ahugoss** [comment]
Hi, I was having this warning after migrating from Angular 7 to 10.1. My initial page (component) to be loaded is the login page and I was having this warning and solve it by putting the <router-outlet></router-outlet> tag.

I don't quit remember if I had this warning on Angular 7, but I know that I have the router-outlet tag in more that one page, at least on the first page that gets loaded (app.component.html) and on other page Dasboard with a side navigation (navigation content).

So, putting the router-outlet tag on the html solves this warning, I just wonder if it is really needed. For instance, on the login page I will not display any child component, so do I need a router-outlet?

**Comment by rprylowski** [comment]
Hi. I got the same error in 10.1.1 version: _"A router outlet has not been instantiated during routes activation. URL Segment: ''_. After downgrading to 10.0.0 everything works as expected.

**Comment by marleypowell** [comment]
@tp1906 @ahugoss @rprylowski I think this was intentional: #30246

**Comment by steynvanesveld** [comment]
I was facing the same issue since the Angular 10.1 update, posting the fix that worked for me for future google searches of others.

Turns out the error had nothing to do with the components on the mentioned route, but with the components navigating to this route. 


Multiple components were navigating the router, and I tested this navigation with the following code:

    `spyOn(component.router, 'navigate').and.callThrough();`


This actually calls the navigation, but that's not necessary. 
A mocked resolve of the navigate promise is enough. New version:

    `spyOn(component.router, 'navigate').and.resolveTo();`


And all the warning disappeared.

**Comment by Enngage** [comment]
This is happening if you have multiple `<router-outlet></router-outlet>` and use `ngIf` directive. For example, this template produces this warning:

 ```
<div *ngIf="isTrue">
   <router-outlet></router-outlet>
</div>
<div *ngIf="!isTrue">
   <router-outlet></router-outlet>
</div>
```

All routes work ok though.

One caveat - the warning is not logged when switching routes within the same module. It only happens when switching to routes in different modules. I also use lazy loaded modules, not sure if that affects anything.

**Comment by Moik** [comment]
Can confirm, warning shows up when a structural directive is used in combination with lazy loading. For example in one of my projects i have code like this:
```
<ng-container *appLoading="isModuleLoading">
  <router-outlet></router-outlet>
</ng-container>
```
After removing the directive warning disappears. What is the best way to resolve this issue?

**Comment by erictor** [comment]
In my scenario, I have a parent component providing a side menu and a child component providing content based on the menu selection.  Usually, I have a router-outlet in the parent component for the content that the child component provides.  But this time, I wanted to send data to the child component using an @Input variable, so instead of router-outlet, I instead put the selector for the child component in its place.  This works fine, I'm seeing the full view rendered as intended, but there's no router-outlet involved (at least at this level of the application).  I'm seeing the "A router outlet has not been instantiated..." warning in the browser dev console.  I suppose I could just ignore it.  Should I?

**Comment by kunal999666** [comment]
Have the same issue and Its still the same no change.

**Comment by atscott** [comment]
This warning was added in https://github.com/angular/angular/commit/1609815743323f17aa19309af32dd3af74bbfb17 as an attempt to be more clear when a route gets activated but a matching `router-outlet` could not be found for it. This seems to create a lot of noise, most frequently in tests. This would also happen when the router outlet is not immediately available (as in `*ngIf`), even though this is valid/intended, as the outlet will activate itself on init.

This thread indicates the warning should be rolled back, as it creates more confusion than it solves and also warns for valid use-cases. I can create a PR to roll this back for the upcoming release myself, but if someone in this thread wants to contribute, this would be a nice opportunity for a community contribution.

**Comment by marleypowell** [comment]
> This warning was added in [1609815](https://github.com/angular/angular/commit/1609815743323f17aa19309af32dd3af74bbfb17) as an attempt to be more clear when a route gets activated but a matching `router-outlet` could not be found for it. This seems to create a lot of noise, most frequently in tests. This would also happen when the router outlet is not immediately available (as in `*ngIf`), even though this is valid/intended, as the outlet will activate itself on init.
> 
> This thread indicates the warning should be rolled back, as it creates more confusion than it solves and also warns for valid use-cases. I can create a PR to roll this back for the upcoming release myself, but if someone in this thread wants to contribute, this would be a nice opportunity for a community contribution.

I will have a go at contributing!

**Comment by mernen** [comment]
In my case, routing actually stopped working under certain circumstances with Angular 10.1; I got this error message whenever I tried to load a new URL, so I thought it was related. It works with 10.0.8, but breaks with anything as early as 10.1.0-next.1. I'll later try to produce a reduced test case and file a new bug, then.

**Comment by ieozt38** [comment]
> In my case, routing actually stopped working under certain circumstances with Angular 10.1; I got this error message whenever I tried to load a new URL, so I thought it was related. It works with 10.0.8, but breaks with anything as early as 10.1.0-next.1. I'll later try to produce a reduced test case and file a new bug, then.

And did you find any fixes? It stops my routing also on Ionic with the same error message the first time when I install the app.

**Comment by atscott** [comment]
@ieozt38 @mernen these cases would be a completely separate issue. The message was only a warning and would not cause any functional changes. Please open a new issue with a reproduction.

This warning message has been removed so this issue can be closed.
