### ISSUE TITLE
AngularFireAuth.SignOut() doesn't work.

### ISSUE THREAD

**Issue by BIGWarriorSoftware** [angular/angular#38824]
Dear Support,

I have a Firebase-based Angular application with authentication page (Sign in-Sign out are included).
During browsing in bug reports connected to this problem, there is no solution for it yet. So please, fix this problem.
Steps to reproduce:
```
...
import { AngularFireAuth } from '@angular/fire/auth'; //<-import this package
...
@Injectable({
  providedIn: 'root'
})
export class AuthService {

constructor(private afAuth: AngularFireAuth, private router: Router) { } //<-- add AngularFireAuth as dependency injection
...
signOut() {
this.afAuth.signOut(); //<- this line is added, but it doesn't work.
}
```

**Comment by JoostK** [comment]
Heya,

`@angular/fire` is maintained independently from the Angular framework in [angular/angularfire](https://github.com/angular/angularfire). So I'll go ahead and close this issue here, as it's not actionable for us.

I'll add that in the current state, this issue will also not be actionable for the Angular Firebase folks, as it's lacking important details about _what_ is not working, version details, etc. Ideally you're able to prepare a minimal reproduction to share.
