### ISSUE TITLE
formatDate: Incorrect month-based week number value

### ISSUE THREAD

**Issue by prashanttholia** [angular/angular#38826]
### Affected Package
@angular/common

### Is this a regression?
Do not think so.

### Description
formatDate('2011-05-11', 'W', 'en') returns '2', when it should return 3.

## 🔬 Minimal Reproduction
See description.

## 🌍  Your Environment

**Angular Version:**
10.1.1

**Comment by AleksanderBodurri** [comment]
The relevant code is here

`/packages/common/src/i18n/format_date.ts`
```ts
function weekGetter(size: number, monthBased = false): DateFormatter {
  return function(date: Date, locale: string) {
    let result;
    if (monthBased) {
      const nbDaysBefore1stDayOfMonth =
          new Date(date.getFullYear(), date.getMonth(), 1).getDay() - 1;
      const today = date.getDate();
      result = 1 + Math.floor((today + nbDaysBefore1stDayOfMonth) / 7);
    } else {
      const thisThurs = getThursdayThisWeek(date);
      // Some days of a year are part of next year according to ISO 8601.
      // Compute the firstThurs from the year of this week's Thursday
      const firstThurs = getFirstThursdayOfYear(thisThurs.getFullYear());
      const diff = thisThurs.getTime() - firstThurs.getTime();
      result = 1 + Math.round(diff / 6.048e8);  // 6.048e8 ms per week
    }

    return padNumber(result, size, getLocaleNumberSymbol(locale, NumberSymbol.MinusSign));
  };
}
```

Specifically

```ts
    if (monthBased) {
      const nbDaysBefore1stDayOfMonth =
          new Date(date.getFullYear(), date.getMonth(), 1).getDay() - 1;
      const today = date.getDate();
      result = 1 + Math.floor((today + nbDaysBefore1stDayOfMonth) / 7);
    } 
```

When the first day of the month is a Sunday, `nbDaysBefore1stDayOfMonth` (not sure what this name is supposed to convey but it seems this is the week day of the first day of the month minus one) evaluates as `0 - 1` (https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date/getDay).

From there `1 + Math.floor((today + nbDaysBefore1stDayOfMonth) / 7)` evaluates to `1 + Math.floor((11 + (-1)) / 7)` which is how a value of 2 is calculated.

If `nbDaysBefore1stDayOfMonth` instead evaluated to 7 in this case we would  have `1 + Math.floor((11 + (7)) / 7)` and the result would be 3.

I'm not sure if ISO 8601 explicitly states whether to start a week on a Sunday (current behaviour) or a Monday (your desired behaviour). I can see how the calculated number may seem counter intuitive though.

**Comment by prashant-tholia** [comment]
@AleksanderBodurri I agree with you that the issue is caused when the first day of the month is a Sunday.

I think the variable nbDaysBefore1stDayOfMonth stores the number of days in the week before first day of this month, so as to include those days in month week number calculation. So, when the first day of the month is a Sunday it would give -1, Monday -> 0, Tuesday -> 1 and so on.

For date 2011-05-11 (First day of the month is a Sunday), the expression `1 + Math.floor((today + nbDaysBefore1stDayOfMonth) / 7)` would evaluate to 1 + Math.floor((11 + (-1)) / 7) which is 1 + 1  -> 2.
And for date 2020-02-11 (Same date value, but first day of the month being a Saturday), the expression would evaluate to `1 + Math.floor((11 + 6) / 7)` which would be 1 + 2 -> 3.

ISO 8601 does state that the week starts on Monday. (Section 3.1.2.16, [ISO 8601-1](https://www.iso.org/obp/ui/#iso:std:iso:8601:-1:ed-1:v1:en)

I believe, therefore, how it needs to be implemented here, is a call that needs to be taken by the repository maintainers.

**Comment by petebacondarwin** [comment]
Tracking here #39606.
