### ISSUE TITLE
Unexpected directive value 'undefined' on the View of component 'TodoApp'

### ISSUE THREAD

**Issue by akhilclarion** [angular/angular#3885]
Hi,

I started with AngularJS2, but i am getting this error.

Please tell, why this error comes.

**Comment by pkozlowski-opensource** [comment]
Most probably you've put something in a directive list that doesn't exist. Most of the time this is due to a missing / misspelled import, ex:

```
import {ImNotHere} from 'somewhere';

@View({
    directives: [ImNotHere]
})
```

Hard to say more without more context. Please try a support forum (https://gitter.im/angular/angular) for those types of questions - we want to keep GitHub issues for bug reports / feature requests. Thnx!

**Comment by akhilclarion** [comment]
Thanks for your help. i got the issue.
