### ISSUE TITLE
Production mode "No component factory found error"

### ISSUE THREAD

**Issue by bayramucuncu** [angular/angular#38864]
# 🚀 feature request

### Relevant Package

 This feature request is for @angular/cli

### Description
 I am using angular 8 application and I will move it to angular 10. But I noticed an issue with working dynamic components.

I have multiple components that will be dynamically compile on runtime.

- FirstComponent
- SecondComponent
- ThirdComponent
- .......

I am selecting one of them from a configuration JSON that saved on my database. And I am using following code to find class name.

```
  private getComponentFactory(name: string, resolver: ComponentFactoryResolver) {
    const factories = Array.from<any>(resolver['_factories'].keys());

    const factoryClass = <Type<any>>factories.find((item: any) => item.name === name);

    return resolver.resolveComponentFactory(factoryClass);
  }
```
This  code works while developing application. But when I build application using `--prog` parameter, it throws an error:

> Error: No component factory found for undefined. Did you add it to @NgModule.entryComponents?

I think the application prod mode uglifies the component name, but my component `name `parameter is not uglified. Because name parameter is coming from databse as JSON. 

Is there any suport to use dynamic components with name?

**Comment by JoostK** [comment]
There is an existing request for this at #33715.

> I think the application prod mode uglifies the component name, but my component name parameter is not uglified. Because name parameter is coming from databse as JSON.

Yes, that is exactly the case. Depending on the class name for such registration is not stable due to minification.

Additionally, `resolver['_factories']` is tapping into private API and this has changed in Angular 9 with Ivy, so that will no longer work.

My recommendation would be to register components from NgModule's as a multi-provider and using a custom service to resolve them from this provider.
