### ISSUE TITLE
can't run multiple ngcc builds in parallel from a single node_modules

### ISSUE THREAD

**Issue by elesueur** [angular/angular#38875]
# 🐞 bug report

### Affected Package

@angular/compiler-cli

### Is this a regression?

Technically, no, but things like this used to work just fine with older versions of Angular.

### Description

Oftentimes, running npm install is a long pole task when running CI/CD jobs. In my case, I have a monorepo from which I build many libraries. I have a pipeline that has a prepare stage/job, which runs npm install into a common node_modules directory, and then I spawn about 20 different jobs in parallel which build the libraries. Currently, things are not working well with Angular 10 because the lock file path is hard-coded into the node_modules directory, and ngcc seems to randomly fail when it sometimes finds a lock file already in place.

The location of the lock file is hard-coded in https://github.com/angular/angular/blob/d1ea1f4c7f3358b730b0d94e65b00bc28cae279c/packages/compiler-cli/ngcc/src/locking/lock_file.ts#L11

It would be great if this could either be configurable, or not inside node_modules, but instead in a tmp directory near where the ng build command is being executed.

## 🔥 Exception or Error

Error: Lock found, but no process with PID 40 seems to be running.
(If you are sure no ngcc process is running then you should delete the lock-file at /builds/core-build/vmw-ngx-components/node_modules/@angular/compiler-cli/ngcc/__ngcc_lock_file__.)
    at new TimeoutError (/builds/core-build/vmw-ngx-components/node_modules/@angular/compiler-cli/ngcc/src/locking/async_locker.js:18:51)
    at AsyncLocker.<anonymous> (/builds/core-build/vmw-ngx-components/node_modules/@angular/compiler-cli/ngcc/src/locking/async_locker.js:111:47)
    at step (/builds/core-build/vmw-ngx-components/node_modules/tslib/tslib.js:140:27)
    at Object.next (/builds/core-build/vmw-ngx-components/node_modules/tslib/tslib.js:121:57)
    at /builds/core-build/vmw-ngx-components/node_modules/tslib/tslib.js:114:75
    at new Promise (<anonymous>)
    at Object.__awaiter (/builds/core-build/vmw-ngx-components/node_modules/tslib/tslib.js:110:16)
    at AsyncLocker.create (/builds/core-build/vmw-ngx-components/node_modules/@angular/compiler-cli/ngcc/src/locking/async_locker.js:68:28)
    at AsyncLocker.<anonymous> (/builds/core-build/vmw-ngx-components/node_modules/@angular/compiler-cli/ngcc/src/locking/async_locker.js:51:59)
    at step (/builds/core-build/vmw-ngx-components/node_modules/tslib/tslib.js:140:27)
An unhandled exception occurred: NGCC failed.

## 🌍  Your Environment

**Angular Version:**

10

**Comment by JoostK** [comment]
How are you running ngcc? Are you invoking the ngcc binary manually in your pipeline, or is it triggered from within a CLI build?

**Comment by elesueur** [comment]
@JoostK I am just using `ng build` ...

**Comment by petebacondarwin** [comment]
Are you running each build on a different machine (or virtual machine)? I.e are you sharing the node_modules between machines? This might explain why the process ID in the lockfile is not found on another machine...

**Comment by elesueur** [comment]
@petebacondarwin yes, as stated in the OP, I am sharing a node_modules directory. Each build is running in its own docker container, but node_modules is mounted as a docker volume into each container. The goal is to avoid running npm install 20 times in each different container.

**Comment by petebacondarwin** [comment]
So the workaround in your case will be to run `ngcc` as a postinstall step before you begin the builds. Something like:

```
  "scripts": {
    "postinstall": "ngcc --properties es2015 browser module main --first-only --create-ivy-entry-points"
  }
```

But you might want to tweak that depending upon your setup.

**Comment by elesueur** [comment]
thanks @petebacondarwin let me give that a try.

**Comment by elesueur** [comment]
@petebacondarwin maybe you can explain a bit why this would solve my problem? My understanding is that ngcc is creating a lock file to avoid running multiple compilations in parallel in using the same node_modules directory, which is _exactly_ what I am trying to do. I presume that ngcc will be used when I compile my library. So how does doing this precompile step avoid the problem of multiple ngcc processes attempting to create the same lock file?

**Comment by JoostK** [comment]
@elesueur ngcc does indeed prevent multiple instances from operating on the same node_modules directory, as that will result in duplicate processing which results in errors. That's why the lock file exists, which should typically allows ngcc to wait for other instances and pick up work if still necessary. In your case, this doesn't work out due to running the jobs in isolated containers, while operating on a shared `node_modules`. That means that there's no signalling possible between the various ngcc instances, which results in the error you're experiencing.

The proposal by @petebacondarwin is to run ngcc during the setup phase in a postinstall script. This should then process all of `node_modules` before spawning the individual jobs, which should allow the individual jobs to operate without needing additional ngcc processing (ngcc will only request a lock if it needs to do some work).

What could be the case is that the initial run of ngcc does not process all library bundles that are later requested by the individual jobs, in which case some jobs might still request the lock and find that's already taken. This may be due to the `--first-only` flag, which means that ngcc will stop processing once the first bundle format that was specified in `properties` has been processed. You could try removing that flag to see if it makes a difference, although it does make processing more expensive (as it will not longer skip several bundles). Unrelated: please do update to 10.1.2 as you'll find that ngcc runs much quicker.

**Comment by elesueur** [comment]
@JoostK thanks for the details. I have adjusted the ngcc command to remove the --properties flag and also remove the --first-only flag. I still see the same failure in the e2e job when it's running in parallel with the unit test job. Any other ideas? I really don't want to have to avoid sharing the common node_modules directory.

**Comment by JoostK** [comment]
Hmm, I'm a bit out of ideas I'm afraid. You could look into the logging of the individual jobs to search for a "Compiling" message, as that indicates that ngcc needs to do something which is unexpected. You might also want to verify that the lock file is actually deleted as the install phase completes (if not; you'll never find the "Compiling" message as that is logged while holding the lock). If there is such a message, it should tell what is being processed which may be useful for further troubleshooting.

> mounting the docker volume in the worker containers as an overlay volume, so that writes essentially layer on top of the base node_modules directory, thus allowing each worker container to think it has its own copy of node_modules

That's an interesting idea!

---

It's way too late here already, I'l sign off for now.

**Comment by petebacondarwin** [comment]
So one thing that occurred to me is that even though ngcc has processed all the entry-points, the CLI will still trigger ngcc at the start of each build just to check that all is processed. This "noop" check should take a very small amount of time (like <100ms) but this could result in the lockfile being set and checked. If you happened to trigger your parallel builds at the exact same time then there is a small chance that they will collide.

As a workaround you could try adding a small delay to each of your parallel jobs so that they start a second or so apart, which might alleviate the problem.

I wonder if we should consider reverting this commit https://github.com/angular/angular/commit/561c0f81a0d62b84fa47a98226eeb85eda864ffd, which checks to see if the PID is currently running and aborting ngcc if not, since this is an optimisation that doesn't work in such scenarios where the `node_modules` is shared across "machines" that have different sets of running processes.

Or perhaps we could be clever and add some machine identifier to the lockfile, as well as the PID, so we could check whether ngcc was running elsewhere and not abort.

**Comment by sod** [comment]
Building multiple builds in parallel works fine for us since angular 9 up to currently 10.1.0. We do just `node_modules/.bin/ngcc -p=module` postinstall. And then multiple webpack builds in parallel to use up all the cpu cores. 

We don't use the cli though. Don't know if that does locks things up on top of the plugin & loader.

**Comment by petebacondarwin** [comment]
Yeah, the CLI runs an initial async ngcc process before starting its build, which your custom setup is not doing. I think this is the cause of the crashes on multiple docker containers.

**Comment by elesueur** [comment]
@petebacondarwin it's certainly possible that my jobs are hitting that ~100ms window ... the two jobs are spawned by gitlab pretty much instantaneously and they immediately run ng e2e or ng test, they don't have to run npm install first.

**Comment by tanepiper** [comment]
+1 for this.

We have a Jenkins pipeline that builds a git tagged version of our app that deploys to both staging and production at the same time, which means we need to compile each app with a `ng build --configuration=<stage,prod>`, outputting to a different folder in the dist folder.

The repo has the preinstall setup, but still when running as a parallel task we get the same PID problem so we have to build in sequence, deploy in parallel.

**Comment by yannickglt** [comment]
+1
We have the same problem while running parallel builds or e2e tests on the CI. Is there any workaround?

**Comment by petebacondarwin** [comment]
A potential workaround is to delay one of the parallel builds be a second or so, to allow the first one to complete its initial ngcc check before triggering the same with the second one.

**Comment by dimitar-toshevski** [comment]
+1
We have the same problem while running parallel builds and both locally or in Jenkins the builds fail because of the ngcc issue
