### ISSUE TITLE
Support shadowDOM in chromedriver

### ISSUE THREAD

**Issue by tbosch** [angular/angular#389]
@vojtajina Could you add the contact persons that already tried to get this working?

**Comment by tbosch** [comment]
@juliemr It would be great if you could have a look how we can get this into chromedriver. Please talk to @IgorMinar and @vojtajina

**Comment by juliemr** [comment]
Looks like progress is happening (https://codereview.chromium.org/480483002/) - but not yet released. I will get more details and follow up here.

**Comment by tbosch** [comment]
Wow, cool!

**Comment by juliemr** [comment]
Update - the newest release of ChromeDriver (2.14) has shadow dom support, but I am seeing issues with it. I have filed an issue with chromedriver: https://code.google.com/p/chromium/issues/detail?id=458815

**Comment by juliemr** [comment]
Since this is now done in chromedriver 2.14, using `by.css('* /deep/ .myClass') will work! (Note that the latest Protractor release installs chromedriver 2.13, so you'll have to manually upgrade).

TODOs
 - Update Protractor with new default version
 - Consider creating helper element locator, such as `by.deepCss('.myClass') // equivalent to `by.css('* /deep/ .myClass')`

**Comment by tbosch** [comment]
FYI. Thanks Julie for digging into this!!

**Comment by tbosch** [comment]
I've release a new version of Protractor which installs chromedriver 2.14
when you do 'webdriver-manager'. I'll look in to updating angular2 to use
this today!

**Comment by juliemr** [comment]
Done!
