### ISSUE TITLE
Ability to pass options to service worker's fetch request(s).

### ISSUE THREAD

**Issue by ghost** [angular/angular#38907]
### Versions
```
Angular CLI: 1.7.3
Node: 8.11.1
OS: darwin x64
Angular: 5.2.9
... animations, common, compiler, compiler-cli, core, forms
... http, language-service, platform-browser
... platform-browser-dynamic, router, service-worker

@angular/cdk: 5.2.4
@angular/cli: 1.7.3
@angular/flex-layout: 5.0.0-beta.14
@angular/material: 5.2.4
@angular-devkit/build-optimizer: 0.3.2
@angular-devkit/core: 0.3.2
@angular-devkit/schematics: 0.3.2
@ngtools/json-schema: 1.2.0
@ngtools/webpack: 1.10.2
@schematics/angular: 0.3.2
@schematics/package-update: 0.3.2
typescript: 2.6.2
webpack: 3.11.0
```

### Observed behavior
Our app is located behind a security gateway and is using a service worker. The service worker was integrated following [this guide](https://angular.io/guide/service-worker-getting-started). Because of the fact that *any* request is passed through the security gateway we had to provide additional options to the construction of any `Request` object, namely `credentials` and `mode`, when a service worker is requesting its manifest from the server. Otherwise manifest fetch fails with CORS error:

> No 'Access-Control-Allow-Origin' header is present on the requested resource.

### Desired behavior
If I could use the `ngsw-config.json` file, or some other means of configuration, to set some global options which in return are applied to any fetch request. Like so:
```
{

  "index": "index.html",
  "request-options": {
    "credentials" : "same-origin",
    "mode": "cors"
  },
  "assetGroups": [
    {
      "name": "app",
      "installMode": "prefetch",
      "resources": {
        "files": [
          "/assets/images/favicon.png",
          "/index.html"
        ],
        "versionedFiles": [
          "/*.bundle.css",
          "/*.bundle.js",
          "/*.chunk.js"
        ]
      }
    },
    {
      "name": "assets",
      "installMode": "lazy",
      "updateMode": "prefetch",
      "resources": {
        "files": [
          "/assets/**"
        ],
        "urls": [
          "https://fonts.googleapis.com/**"
        ]
      }
    }
  ]
}
```

**Comment by gkalpak** [comment]
Sorry for the late response 😞
I was just made aware of this issue and I am having some difficulties understanding the underlying problems. For example:

- In https://github.com/angular/angular/issues/38907#issue-704888816, @ghost says they want to configure the request with `credentials : same-origin` and `mode: cors`. But these are the default values (when creating a request using the `Request` constructor, which is what the SW does), so these should be the values one gets anyway 😕

- In https://github.com/angular/angular/issues/38907#issuecomment-437317434, I am not sure what _"CORS headers"_ @bjornharvold refers to. The `Access-Control-Allow-Origin` is missing from the _response_, not the _request_ 😕

- In https://github.com/angular/angular/issues/38907#issuecomment-458870667, I am not sure exactly what the problem was and thus how it could be addressed in the SW.

- In https://github.com/angular/angular/issues/38907#issuecomment-535246061, @Trent-Matthias says they fixed their issue by adding a `crossorigin` attribute on their `<link />` element, but that should not affect how the SW requests the manifest 😕

I do get that it might be a problem that the SW is dropping the request headers, as mentioned by @Jack-Sparrow in https://github.com/angular/angular/issues/38907#issuecomment-458870667. This is being tracked in #24227.

##
Based on the above (and the fact that the issue was opened ~2.5 years ago - a lot of SW issues have been fixed since, both in browsers and in Angular), I am going to close the issue.

If the problem you are facing is related to the SW's removing request headers, let's continue the discussion in #24227.
If the problem is different, please open a new issue (providing a clear description of the usecase and if possible a minimal reproduction).

Thank you all!
