### ISSUE TITLE
Improve built-in i18n "runtime translation" support

### ISSUE THREAD

**Issue by jimbarrett33** [angular/angular#38953]
# 🚀 feature request

### Relevant Package

 This feature request is for @angular/localize (and possibly @angular/cli, @angular/compiler-cli)

### Description
 
@petebacondarwin This is a follow-up feature request based on your comment https://github.com/angular/angular/issues/16477#issuecomment-585198070 to check if there are plans or progress on "runtime translation" as you describe below, without having to rely on www.locl.app (which is not available yet anyway).

"This is what we mean in the core Angular framework as runtime translation. But please not that the final outcome of this is effectively the same as translation at compile time. The translation happens only once; if you want to change the language at runtime then you must restart the whole application (e.g. via a reload). This has the benefit of allowing the project to deploy a single distributable with numerous translation files, which is helpful in a small number of use cases where you do not want to generate all the different translations up front."

To give you a scenario, we are building Ionic apps using Angular so the "allowing the project to deploy a single distributable with numerous translation files" would be a great benefit to us. We are OK with reloading the app, although some built-in way to do this as the app bootstraps (or soon after) would be great to avoid workarounds etc..

### Describe the solution you'd like

A single build/bundle with the ability to switch locales at runtime via a seamless reload of the app. Seamless means a way to reload the correct locale app at the early possible time based on either device info, user input, and/or locale storage (realizing that would be app specific code but some built-in hook would be great).

Since we already do the translations "up front" via xliff files, some way of hooking into those translations would be awesome. Without know the internals of Angular, a possible design for this is a single build in `/dist` with the translations (originating from the xliff files) distributed to `dist/<locale>`, with the `/dist` root defaulting to the `sourceLocale` in angular.json. Possibly there is an index.html file in each `dist/<locale>` that when requested by the web browser gets the main bundles from `/dist` but "swaps" the locale code from the current `dist/<locale>` folder request. I could be way off here :).

### Describe alternatives you've considered

We will have to distribute all full locale builds on the device and manually reload via code (don't have a sample of this just yet). Really (really, really, ...) do not want to us ngx-translate.

**Comment by petebacondarwin** [comment]
I agree that we should have a story for doing this just with the Angular packages. Looking into it...

**Comment by CDDelta** [comment]
> I agree that we should have a story for doing this just with the Angular packages. Looking into it...
Hey @petebacondarwin, is this issue still being looked into?
It would be immensely helpful to have some documentation to use this powerful feature. 😄

**Comment by petebacondarwin** [comment]
I'm afraid that I don't have the time to work on this documentation right now.

**Comment by alexcotelin** [comment]
Hi @petebacondarwin, I have a [demo repo](https://github.com/alexcotelin/angular-i18n/tree/using-angular-i18n-runtime) where I'm doing the runtime translations, I used it for a meetup presentation, I'd love to hear your thoughts on it and eventually ways to do it better and improve it. Thanks!

**Comment by petebacondarwin** [comment]
Hi Alex - perhaps we should talk about working together to provide an official demo / guide?

**Comment by alexcotelin** [comment]
That would be great!

**Comment by napei** [comment]
I have successfully used https://ngneat.github.io/transloco/ in production a bit. Something like this built into Angular would be awesome.

**Comment by petebacondarwin** [comment]
@napei - thanks for chiming in here. I would be interested to hear from you what, as well as dynamic locale switching, transloco has provided for you over what the built-in i18n support does?

**Comment by napei** [comment]
> @napei - thanks for chiming in here. I would be interested to hear from you what, as well as dynamic locale switching, transloco has provided for you over what the built-in i18n support does?

@petebacondarwin sure, hope I don't ramble too much.

The site I'm working on has most of its content primarily driven from an API, which actually means that the impact of which i18n system I chose was minimal. Nonetheless I went with transloco for several reasons, namely the dynamic switching. If only some aspects of my site are static like header menus, buttons, ToS, UI stuff, then reloading the entire application just to facilitate changing a language seemed excessive to me, when I would have to reload content from the API anyway. So using NGRX as a state factory let's me just reload the content when the language changes. 

I will point out what was mentioned in another comment (https://github.com/angular/angular/issues/16477#issuecomment-585245902) that language switching doesn't necessarily have to happen all that often, and in my case users of my site will browse in a particular language and never change it. But, I was naive and just decided to introduce the extra overhead of dynamic switching 😄 

I also found a lack of documentation to help with default i18n. Some of it was vague, some of it was hard to understand. Transloco was simpler. 

At its core, my decision was generally based off `ease-of-use` and `ease-of-implementation`.

**Disclaimer: I did this about 2 years ago now and have stuck with it since (I believe I started in Angular `v8` or `v9`, production is now `v11`, dev is `v12`). I don't really know how i18n inside Angular has changed/improved if at all.**

So essentially I chose to use transloco for a number of reasons:
- dynamic locale switching (of course)
- one build output, many languages (faster build times)
- JSON language files. I had a hard time getting used to XLIFF and making i18n tools work with it, I also confused other people that worked with me with XLIFF as its not necessarily the prettiest thing. JSON also integrates much nicer with external tools (when I started using it I chose to deploy `weblate`)
- I can get translation data from inside `TS` which helps for stuff like dynamic buttons or other messages. I've since moved away from putting strings in `TS` but it was a thing I could do, so I used it.
- Lazy-loading translations along with lazy-loaded routes. Completely irrelevant with non-runtime methods because it's all static content and probably wasteful but still, useful to normalise how things are done along with lazy-loading modules in Angular.
- Observables. I can subscribe to language changes, look at the current language, do things to state in NGRX etc.
- No redirects, language is set from a user account/localStorage and loaded first without redirecting to locale-specific sites `/en` or `/id` etc. This also simplified deployment (`firebase`) beccause I don't have to do anything extra in server-land. It's not an SSR app so I don't have access to, for example, determining the `Accept-Language` header and redirect before serving. (Maybe there's other ways but never was bothered to look).

Hopefully that's useful info. Let me know if you want me to elabourate.

**Comment by petebacondarwin** [comment]
That is great feedback, thank you @napei. I am pleased to say that many of your points are actually supported (if not well documented) by the built-in i18n now:

- **dynamic locale switching (of course)**
  *Indeed this will not be supported natively in Angular.*

- **one build output, many languages (faster build times)**
  *This is now the default for i18n since Ivy*

- **JSON language files. I had a hard time getting used to XLIFF and making i18n tools work with it, I also confused other people that worked with me with XLIFF as its not necessarily the prettiest thing. JSON also integrates much nicer with external tools (when I started using it I chose to deploy weblate)**
  *Built-in i18n now supports consuming and extracting to two JSON formats: a simple key-value one, and the slightly more sophisticated ARB format.*

- **I can get translation data from inside TS which helps for stuff like dynamic buttons or other messages. I've since moved away from putting strings in TS but it was a thing I could do, so I used it.**
  *Since Ivy this is also now supported in the form of static backtick strings that are "tagged" with `$localize`.*

- **Lazy-loading translations along with lazy-loaded routes. Completely irrelevant with non-runtime methods because it's all static content and probably wasteful but still, useful to normalise how things are done along with lazy-loading modules in Angular.**
  *It is actually now possible to lazy load translations, if you are willing to do the translation of messages in the browser rather than getting the benefit of compile-time translation. This is an area that is not well documented, but @alexcotelin is working on an example and some docs for this.*

- **Observables. I can subscribe to language changes, look at the current language, do things to state in NGRX etc.**
  *As a corollary to no-dynamic locale switching, this will not be supported built-in.*

- **No redirects, language is set from a user account/localStorage and loaded first without redirecting to locale-specific sites /en or /id etc. This also simplified deployment (firebase) beccause I don't have to do anything extra in server-land. It's not an SSR app (yet) so I don't have access to, for example, determining the Accept-Language header and redirect before serving. (Maybe there's other ways but never was bothered to look).**
  *As part of the ability to do the translation in the browser, mentioned above, it is possible to set the locale at bootstrap time based on something other than the URL, so this is also effectively supported.*

**Comment by napei** [comment]
@petebacondarwin well that's great to hear. Thanks for the info. I definitely need to look into i18n now and thanks for clarifying.

**Comment by stefan-schweiger** [comment]
@petebacondarwin @alexcotelin do you have any update on example projects or a documentation?

I've tried to get a very simple project which was using AOT localization before running with runtime localization.

https://github.com/stefan-schweiger/angular-runtime-i18n

When I just start the project the runtime localization works ok, but as soon as I try to start it with `--configuration=de` or `--configuration=en` the AppModule doesn't seem to initialize and the app doesn't work. But the code in `main.ts` run and the additional localizations get loaded over the network.

When I build the project with `--localize` and serve it myself the runtime localizations don't seem to do anything but at least the app works again...

Do you have any insight why this is happening or how a proper project should be set up? I don't care about being able to switch languages during runtime, so precompiling it before hand and then simply loading whatever "addtional" translations there are is fine for me, but I can't even get that working.

**Comment by alexcotelin** [comment]
Hi @stefan-schweiger , I'm not sure I understand what you want to achieve. It looks like you're using a mixture of both worlds. Are you looking for runtime or build time localization?

**Comment by stefan-schweiger** [comment]
@alexcotelin I've since played around a bit more with runtime i18n and now it's clearer to me how it works and what it can't do.

So you can't use any localization configurations because this would "remove" `$localize` during compilation.

If I still want to keep routes with `/<iso_code>/<route>` I need to check the current location in `main.ts` and load the language I want. Then do some Router magic to ignore the language part of the route, and do a hard reload if it changes.

Another discovery which should probably be documented is that you can't load translations during `APP_INITIALIZATION`. Even though it would feel like the right place to do it.

**Comment by TheSlimvReal** [comment]
Similar issue to #43796 as I feel like your goal is to have a single application with multiple languages and not multiple applications with a single language

**Comment by DaSchTour** [comment]
I think one importent point is missing here. Form what I remember SSR with angular localization is a pain, because you have to create server applications for every localization.

**Comment by gotwig** [comment]
Where can I vote for this feature?... Its not OK in my opinion to rely on external i18n tools to make Angular compatible with multiple languages. Its almost 2 years since this bug was brought up and as far as I know there is still no runtime translation out-of-the-box possible with Angular. Why? If the architecture is wrong it needs to be rebuild, this is a completly normal usecase.

And I also believe that angular.io itself needs to offer multiple languages to improve the adaption.

**Comment by stefan-schweiger** [comment]
@gotwig runtime translation with @angular/localization is absolutely possible. We've been using it in production for some time now. It's just really, really poorly documented. I will try to create a sample repository for you later.

**Comment by stefan-schweiger** [comment]
@gotwig you can look into my example here https://github.com/stefan-schweiger/ng-runtime-i18n

Depending on your use use case I'm sure some of the path/language detection handling needs to be adapted to your needs but it should help to give you the idea how the runtime translation works. One caveat is to change language you still need to do a full reload since the translation files get loaded in `main.ts`. I haven't found a way around that yet.

But at least for me that's fine as I find it much more important to be able to load my translations during runtime from an API/external source without having to recompile and redeploy the whole frontend.

**Comment by ennovum** [comment]
> One caveat is to change language you still need to do a full reload

So it is not really "runtime".

**Comment by gotwig** [comment]
> > One caveat is to change language you still need to do a full reload
> 
> So it is not really "runtime".

Im doing Angular professionally for several years.. and sadly what I understand is that they dont listen to their community

**Comment by stefan-schweiger** [comment]
> > One caveat is to change language you still need to do a full reload
> 
> 
> 
> So it is not really "runtime".

It's runtime in the sense that the translations are not baked in during compilation, but loaded dynamically during the startup of the application.

**Comment by cjsase** [comment]
For reference i also made a simple demo here: https://github.com/cjsase/angular-i18n-demo
(loading Translations with `APP_INITIALIZER` is possible 👍)
(You do not have to provide a translation file for english when you write your app in english 😉)

I really do not see a problem that a full page reload is necessary, since a user usually changes the language maybe once.

The only problems i have with the current solution are:
- you can not set a custom identifier for ICU expressions (look at the last commit in my repo to see why that is a problem)
- you can not use ICU expressions in TS code
- There is no integrated way to convert xliff (or other formats) to json, for use in the browser. Either you only use json (translators will hate you if you do) or you have to find your own solution to convert the translations to json.

Implementing Internationalization correctly is an extremely challenging task.
I am working on a software for translators and having to support every possible language is realy hard. Some languages do not have pluralization at all, some have a weird system for when they use specific post- or prefixes, etc. realy long list 🥲

The solution we got integrated in Angular is actually quite good compared to other frameworks, though the documentation is really quite lacking...

If you absolutely need dynamic translations without reloading, i think ngx-translate is still a valid option one can use (if it will further be supported for newer Angular version). We have used it for years before switching to the integrated solution.

We are using the integrated solution in production since about a year. So i would say it is production-ready ;)

**Comment by stefan-schweiger** [comment]
> (loading Translations with `APP_INITIALIZER` is possible 👍)

Awesome that you figured this out! Still does not give runtime language change, but at least it makes the translation handling easier to follow.

> (You do not have to provide a translation file for english when you write your app in english 😉)

I would still go for translation files for english, because else you need to rebuild the application to do small changes your texts (e.g. typos or when marketing decides they want to change a wording...).

> - you can not set a custom identifier for ICU expressions (look at the last commit in my repo to see why that is a problem)
> 
> - you can not use ICU expressions in TS code
> 
> - There is no integrated way to convert xliff (or other formats) to json, for use in the browser. Either you only use json (translators will hate you if you do) or you have to find your own solution to convert the translations to json.

We've used lokalise.com in the past, they now finally allow to define custom placeholder formats. But yes switching between formats is always a bit cumbersome. It would help if it was at least possible to have better support for the ADB json format.

> We are using the integrated solution in production since about a year. So i would say it is production-ready ;)

We also have been using it for about 6 month and it works at least as well for us as using AOT i18n.

**Comment by TheSlimvReal** [comment]
The following snippet is quite good at converting `xliff` to `json`. I managed to convert my whole xliff file this way (during runtime or compile time both works).

```javascript
import { MessageId, TargetMessage } from "@angular/localize/src/utils";
import xliff from "xliff";

export async function parseTranslationsForLocalize(
  translations: string
): Promise<Record<MessageId, TargetMessage>> {
  const parserResult: any = await xliff.xliff12ToJs(translations);
  const xliffContent: any = parserResult.resources["ng2.template"];

  return Object.keys(xliffContent).reduce(
    (result: Record<MessageId, TargetMessage>, current: string) => {
      if (typeof xliffContent[current].target === "string") {
        result[current] = xliffContent[current].target;
      } else if (Array.isArray(xliffContent[current].target)) {
        result[current] = xliffContent[current].target
          .map((entry: string | { [key: string]: any }) =>
            typeof entry === "string"
              ? entry
              : "{$" + entry.Standalone["id"] + "}"
          )
          .map((entry: string) => entry.replace("{{", "{$").replace("}}", "}"))
          .join("");
      } else {
        console.warn("this is probably an error", xliffContent[current]);
        result[current] = xliffContent[current].target.Standalone["equiv-text"];
      }

      return result;
    },
    {}
  );
}
```
You can use it like this:
```javascript
  fetch("/assets/locale/messages." + locale + ".xlf")
    .then((response) => {
      if (!response.ok) {
        throw new Error("HTTP error " + response.status);
      }
      return response.text();
    })
    .then((res) => parseTranslationsForLocalize(res))
    .then((json) => loadTranslations(json));
```

**Comment by TheSlimvReal** [comment]
I am still having problems with runtime translations.I tried both @cjsase and @stefan-schweiger approach but I keep getting the default language for all strings that are from files that are "plain"/"static" javascript and not a Angular class, meaning classes or objects which are exported without any decorators:
```javascript
export const config = {
  key1: $localize`label for key 1`,
  key2: $localize`label for key 2`
}
```
The values of `key1` and `key2` keep being in the default language. Using compile time translation this works correctly.
Any idea what might be the issue for this behavior? Do I have to re-apply the translation again later or earlier?

**Comment by Hafnernuss** [comment]
Maybe [this](https://glitchtip.com/blog/2022-06-29-i18n)could be helpful @TheSlimvReal:

**Comment by ChBernat** [comment]
@cjsase You can move your initializeLanguage code to a Resolver.

Add routing, add a routing parameter to the routing and you can pretty much load translations based on the chosen route.

ie. `/en-US/users`.

I may provide a demo repo later this week if this is still something relevant.

**Comment by ChBernat** [comment]
Whoever could be potentially interested in the "runtime" translations, here's the repo: https://github.com/ChBernat/angular-i18n-showcase

It's NOT perfect, it still requires reloading the entire app via `window.location.reload()`, but this is the LEAST hacky way we managed to come up with at [Inside Labs](https://github.com/inside-labs). This solution will break only if the Angular team will change something really major in i18n as we use their public API.

We are currently working on a more "hacky" way that would involve manually and lazily loading components on the change of a route, but I do not recommend going this way - there are many things that may break when updating NG.

**Comment by slava-zadorozhniy** [comment]
> dynamic locale switching (of course)
Indeed this will not be supported natively in Angular.

Hi @petebacondarwin, @napei, in fact, Angular supports it thanks to the `clearTranslations` and `loadTranslations` functions from the [@angular/localize](https://angular.io/api/localize) package.
There is only one limitation - you should not use translations in a component template (`i18n` and `i18n-*` attributes).

I've created a demo repository to show how it can be achieved - [ng-i18n-dynamic](https://github.com/viatcheslav-zadorozhniy/ng-i18n-dynamic).
@ChBernat please take a look at my solution, if you are interested in.

**Comment by vbraun** [comment]
If you get the wrong language just think of `$localize` as a function call. You only get the correct language if you have set it before the call. If you want to use it in the initializer of a module level global
```
const foo = $localize`Foo`;
```
then the `loadTranslations` has to be called before that (taking js bundling into account, which can reorder import statements). So either 
* synchronously place it before the initializer (in particular you cannot asynchronously load the language json), or 
* make sure the module with the initializer is lazy-loaded after `loadTranslations`, or
* do not use $localize in global initializers

We also noticed that template i18n attributes are effectively evaluated from global initializers, so you have to set the desired language before lazy loading the component and it cannot be changed later. If that could be fixed (i.e. provide a way to reevaluate the i18n-strings in templates) then I would consider that sufficient for dynamic translation.

**Comment by AndrewKushnir** [comment]
Hello everyone! Based on the note from Pete (https://github.com/angular/angular/issues/38953#issuecomment-862492065) and comments in this thread, we are closing this ticket in favor of https://github.com/angular/angular/issues/46851, which proposes to add more docs for the runtime translations feature. If someone is interested in contributing a section/guide to the docs (based on the experience using runtime translations), we'll be happy to help with the review. Thank you.

**Comment by TheSlimvReal** [comment]
@AndrewKushnir thanks for referencing my issue. As mentioned there I am happy to create the doc section once I have green light and it seem like it still needs engineering input.
