### ISSUE TITLE
Losing `@types/*` packages types on second+ server rebuild

### ISSUE THREAD

**Issue by artaommahe** [angular/angular#38979]
# 🐞 Bug report

### Command (mark with an `x`)

- [ ] new
- [ ] build
- [x] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] xi18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc

### Is this a regression?

 Yes, the previous version in which this bug was not present was: 9.x

### Description

Somehow typescript loses `@types/*` types on second+ angular app rebuild. It works fine on devserver start, first rebuild and on build command.
We faced this for `require` and some webpack typings in our apps after update ng9 -> ng10.

## 🔬 Minimal Reproduction

- clone https://github.com/artaommahe/angular-cli-missing-types-on-rebuild
- open app.component.ts
- start dev server
- no errors
- trigger rebuild (e.g. add comment)
- no errors
- trigger second rebuild
- see type error

Adding `types: ['node']` solves `require` type error, but you need to add all `@types/*` packages for big projects. `@types/*` should work fine without any additional actions.

## 🔥 Exception or Error
<pre><code>
    ERROR in src/app/app.component.ts:2:1 - error TS2580: Cannot find name 'require'. Do you need to install type definitions for node? Try `npm i @types/node`.
    
    2 require('./test.svg');
      ~~~~~~~
</code></pre>


## 🌍 Your Environment
<pre><code>
PS D:\projects\issues\angular-cli-missing-types-on-rebuild> yarn ng version
yarn run v1.16.0
$ ng version

     _                      _                 ____ _     ___
    / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
   / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
  / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
 /_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
                |___/
    

Angular CLI: 10.1.2
Node: 12.18.1
OS: win32 x64

Angular: 10.1.2
... animations, cli, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, router
Ivy Workspace: Yes

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1001.2
@angular-devkit/build-angular   0.1001.2
@angular-devkit/core            10.1.2
@angular-devkit/schematics      10.1.2
@schematics/angular             10.1.2
@schematics/update              0.1001.2
rxjs                            6.6.3
typescript                      4.0.3
</code></pre>

**Anything else relevant?**

**Comment by JoostK** [comment]
Confirming as reported, it's indeed a bug in ngtsc (the Ivy compiler).

The issue occurs due to how template type checking is done; a `ts.CompilerHost` is created to expose the type check files:

https://github.com/angular/angular/blob/9e8fa0748f1f8b3b83c0dae8b829bb712241dd69/packages/compiler-cli/src/ngtsc/typecheck/src/host.ts#L17

This host does not implement all optional methods, one of which is `directoryExists`, so that `@types` discovery does not trigger here. This type check program is then reused for the the next compilation, resulting in the primary emit program from also missing these types (I think because module resolution results were reused).

In ngc I'm seeing every other compile to fail, as the failure throws away any reuse program as it's deemed invalid. This allows the next compilation to succeed again. I didn't test with the CLI but it may not show that behaviour and always fail instead.
