### ISSUE TITLE
Angular 8 - How to dynamically add children routes coming from a service to a parent routing module 

### ISSUE THREAD

**Issue by mvargasv95** [angular/angular#38989]
I'm using Angular 8. I have some modules, for instance client-migration.module.ts , which are being lazily loaded in app-routing.module ts. 
In the parent component routing module, client-migration-routing.module.ts , I need to load the children routes that are coming from a service (the components are already created) . How can I achieve this? I already asked everywhere and I'm here since this is almost my last resort. Hope somebody can help :)

**Comment by JohnnyDevNull** [comment]
I don't know if this would help you but maybe you get an idea. I'am working on a huge warehouse application with over 200 lazy loaded modules. We setup all routes together so that we don't have to add them dynamically, thats also better for the compilation so that nothing gets missed. Now to be sure that the user can only route to the components he is allowed to you have two ways. The first one is securing the routes via `canActivate` Guards which is the most common and the most simple way. The second way would be to remove all routeConfigs from the router which the user is not allowed to route to, but this needs more logic to implement in your main router Module to cleanup and reset the routes every time a user is logged in or out.

Adding routes dynamically: https://stackoverflow.com/a/42928292/3634274

**Comment by atscott** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).
