### ISSUE TITLE
Binding error w/ bad message when 2 components talk through mixed case variable name

### ISSUE THREAD

**Issue by wardbell** [angular/angular#3901]
Mentioned to @vsavkin on 8/29 who asked that I open as "P1"

Use Case:  A parent "Heroes" component lists heroes and shows a current hero in the child "Hero" detail component.  One of the properties communicated from parent to child was named "userName".

    <hero [hero]="currentHero" [userName]="userName" (delete)="onDelete()"></hero>

That binding failed w/ message

    EXCEPTION: Can't bind to 'username' since it isn't a known property of the '<hero>' element 

Notice that the message shows the variable name in *lower case*. This problem goes away if I rename the child property to all lower case.  Any of these variations are fine: "username", "user", "xxx", "xyx".  

But any mixed-case name failed in an similar way. For example

    <hero [hero]="currentHero" [xYx]="userName" (delete)="onDelete()"></hero>

Failed w/ message

    EXCEPTION: Can't bind to 'xyx' since it isn't a known property of the '<hero>' element 

I have the repro in another github repository if needed.

**Comment by ericmartinezr** [comment]
Hey @wardbell 

This is a known case, see this https://github.com/angular/angular/issues/1447

**Comment by pkozlowski-opensource** [comment]
@ericmartinezr is right - the problem here is that it is a browser lower-casing property attribute names _before_ ng2 compiler runs. We can't prevent this lower-casing from happening with the current compiler and this is why we've got a convention where snake-case is converted to camelCase. In your particular case you could access mixedCase variable names by doing: `<hero [hero]="currentHero" [user-name]="userName">`

The good news is that the compiler is being reworked from operating on the DOM parsed by a browser to HTML text, so this lower-casing won't be happening and we have more options of handling / reporting this situation. I'm going to close this one as this is a known issue and a better solution is in the pipe.

@mhevery @tbosch is the plan for a new text-based compiler to handle mixedCase attribute names out of the box? Or do we still want to mimic browser's behaviour here?

**Comment by wardbell** [comment]
We can document but few will find it. May I suggest that the reported error either me too this possibility or, perhaps better, link to an article on typical binding resolution failures and solutions.

    EXCEPTION: Can't bind to 'xyz'. See <link> for more information and possible solutions.
