### ISSUE TITLE
Cannot set base providers error using 'ng test' after Angular v9 upgrade

### ISSUE THREAD

**Issue by dcp3450** [angular/angular#39271]
I've got all of my unit tests updated and passing after an upgrade from v8 to v9. However, now I'm getting the following error:

Cannot set base providers because it has already been called

Research suggested that I had `BrowserDynamicTestingModule `or `platformBrowserDynamicTesting()` called twice in my application. I searched my whole app and only found them once in my test.ts file:

```
// This file is required by karma.conf.js and loads recursively all the .spec and framework files

import 'zone.js/dist/zone-testing';
import { getTestBed } from '@angular/core/testing';
import { BrowserDynamicTestingModule, platformBrowserDynamicTesting } from '@angular/platform-browser-dynamic/testing';

declare const require: {
  context(
    path: string,
    deep?: boolean,
    filter?: RegExp
  ): {
    keys(): string[];
    <T>(id: string): T;
  };
};

// First, initialize the Angular testing environment.
getTestBed().initTestEnvironment(BrowserDynamicTestingModule, platformBrowserDynamicTesting());
// Then we find all the tests.
const context = require.context('./', true, /\.spec\.ts$/);
// And load the modules.
context.keys().map(context);
```
I'm not sure where else the error could come from.

`ng --version` output:
```
Angular CLI: 9.1.12
Node: 12.16.1
OS: win32 x64

Angular: 9.1.12
... animations, cli, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, router
Ivy Workspace: Yes

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.1001.6
@angular-devkit/build-angular     0.901.12
@angular-devkit/build-optimizer   0.901.12
@angular-devkit/build-webpack     0.901.12
@angular-devkit/core              10.1.6
@angular-devkit/schematics        9.1.12
@angular/cdk                      9.2.4
@angular/flex-layout              9.0.0-beta.31
@angular/language-service         8.2.14
@angular/material                 9.2.4
@ngtools/webpack                  9.1.12
@schematics/angular               9.1.12
@schematics/update                0.901.12
rxjs                              6.5.5
typescript                        3.8.3
webpack                           4.42.0
```

**Comment by AndrewKushnir** [comment]
Hi @dcp3450, the mentioned error is thrown from the [initTestEnvironment function](https://github.com/angular/angular/blob/master/packages/core/testing/src/r3_test_bed.ts#L217) in case it's called more than once. You can try to add a breakpoint there and see where the calls are coming from and update the code to remove one of them. If the problem still exists, please provide a minimal repro (in a form of a GitHub repository) so that we can investigate. Thank you.

**Comment by dcp3450** [comment]
@AndrewKushnir can you give me some direction? I'm using VS Code. Not sure how to add a breakpoint that will trigger when running the test command.

**Comment by dcp3450** [comment]
I don't have a `src` dir under my testing folder either. Even searching for the error text returns no results...

**Comment by AndrewKushnir** [comment]
@dcp3450 thanks for the reply.

I think you can try running unit tests in a browser and put breakpoints there using DevTools. I'd suggest posting a question on [StackOverflow](http://stackoverflow.com/) using tag `angular` to get additional help regarding your local setup.

I will close this ticket for now since there is no repro, thus we can not perform further investigation. If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).

Feel free to reopen this ticket (or create a new one) once more information (and/or a repro) about this problem is available.

Thank you.
