### ISSUE TITLE
docs: Improve Angular compiler options guide

### ISSUE THREAD

**Issue by alan-agius4** [angular/angular#39354]
# 📚 Docs or angular.io bug report

At the moment the [Angular compiler options guide](https://angular.io/guide/angular-compiler-options#angular-compiler-options) doesn't include all compiler options.  Some of the options are instead included only in [Template type checking guide](https://angular.io/guide/template-typecheck#troubleshooting-template-errors).

## Expected vs Actual Behavior
I'd expect that the `Angular compiler options` guide contains a list of all the available options.

**Comment by iRealNirmal** [comment]
@alan-agius4 here you want to just updated code section  of  [https://angular.io/guide/angular-compiler-options#configuration-inheritance-with-extends](https://angular.io/guide/angular-compiler-options#configuration-inheritance-with-extends) right ? Because in bottom section I see all template  options explained in the page.
