### ISSUE TITLE
[GitHub] angular-automatic-lock-bot has broken link to automatic conversation locking policy

### ISSUE THREAD

**Issue by danieldanielecki** [angular/angular#39358]
# 🐞 Bug report

- [ ] new
- [ ] build
- [ ] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] xi18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc

### Is this a regression?

I think so.

### Description

The [angular-automatic-lock-bot](https://github.com/apps/angular-automatic-lock-bot) returns [404 link](https://github.com/angular/angular/blob/67d80f/docs/GITHUB_PROCESS.md#conversation-locking) to `automatic conversation locking policy` once closing conversation.

## 🔬 Minimal Reproduction

For reference see [#16348 (comment)](https://github.com/angular/angular-cli/issues/16348#issuecomment-571043522), [#18782 (comment)](https://github.com/angular/angular-cli/issues/18782#issuecomment-708980812).

## 🔥 Exception or Error
<pre><code>
404, Page Not Found
</code></pre>

## 🌍 Your Environment
<pre><code>
GitHub Angular's repo
</code></pre>

**Comment by alan-agius4** [comment]
I also see the same thing in the other repos, material, universal, framework and cli.

It also looks like there are some warnings as the config contains invalid inputs.

```
.github#L1
Unexpected input(s) 'lock-bot-key', valid inputs are ['github-token', 'locks-per-execution']
```

**Comment by gkalpak** [comment]
The warning is because [lock-closed/action.yml][1] was not updated to mention `lock-bot-key` as a valid input in angular/dev-infra#40. But that doesn't seem to cause issues (just a warning).

##
The actual problem is that angular/dev-infra#77 only updated `policyUrl` in the source file ([src/main.ts][2], but not the built file that is actually used when running the action ([lib/bundle.js][3]).

There is a [pre-commit git hook][4] to build the `lock-closed` action, but since I submitted the PR via the GitHub UI, it was not triggered.

##
Working on a fix...

[1]: https://github.com/angular/dev-infra/blob/414834b2b24dd2df37c6ed00808387ee6fd91b66/github-actions/lock-closed/action.yml#L4-L10
[2]: https://github.com/angular/dev-infra/blob/414834b2b24dd2df37c6ed00808387ee6fd91b66/github-actions/lock-closed/src/main.ts#L35
[3]: https://github.com/angular/dev-infra/blob/414834b2b24dd2df37c6ed00808387ee6fd91b66/github-actions/lock-closed/lib/bundle.js#L26099
[4]: https://github.com/angular/dev-infra/blob/414834b2b24dd2df37c6ed00808387ee6fd91b66/scripts/pre-commit.sh#L5

**Comment by gkalpak** [comment]
Once all of the below PRs are merged the issue should be fixed:
- angular/angular#39371
- angular/angular-cli#19165
- angular/components#20848
- angular/universal#1868

(If there are more Angular repos affected and I missed them, please lmk.)

##
I am going to close this issue now, but feel free to open a new if the problem persists on a repo after the corresponding PR has been merged.

Thx again for bringing this to our attention, @danieldanielecki :+1:
