### ISSUE TITLE
service worker won't register after .unregister()

### ISSUE THREAD

**Issue by mackelito** [angular/angular#39377]
### Bug Report or Feature Request (mark with an `x`)
```
- [ x ] bug report -> please search issues before submitting
- [ ] feature request
```

### Area
```
- [ x? ] devkit
- [ ] schematics
```

### Versions

node --version v8.11.2
npm -v 6.1.0

### Repro steps

on logout we do:
````
          // unregister service worker
          navigator.serviceWorker.getRegistrations().then(function (registrations) {
            for (const registration of registrations) {
              registration.unregister();
            }
          });
````
Then we reload the site.. when user loggs back in there is no service worker registered

### Desired functionality

Service worker should register

### Mention any other details that might be useful

If we manually do this in the console:

````
navigator.serviceWorker.register('/ngsw-worker.js')
````
then things start working again

**Comment by gkalpak** [comment]
There could be a number of reasons why the SW has not been registered, unrelated to calling `.unregister()`. For example, it might be related to the app's not stabilizing in combination with the [registrationStrategy][2] used for the ServiceWorker.

Unfortunately, there is not much we can do without a reproduction. Given that and the fact that this issue is over 2 years old (i.e. pertaining to an older version of Angular), I am going to close it as non-actionable.

If you are still running into similar problems, please open a new issue providing a minimal reproduction (for example, in the form of a GitHub repo we can check out and build to see the problem in action).
(cc @malek0512)

[1]: https://angular.io/api/core/ApplicationRef#isstable-examples-and-caveats
[2]: https://angular.io/api/service-worker/SwRegistrationOptions#registrationStrategy
