### ISSUE TITLE
expose LocaleDataIndex enum to support override default values for a locale

### ISSUE THREAD

**Issue by alyahmedaly** [angular/angular#39428]
# 🚀 feature request

I'm not sure what is the best way to override default locale symbols globally in angular app

We can hack it using registerLocaleData sense it's public API of angular/common but the parameter is any.

so we use it with angular 8 but when updating to angular 10 the type of data changes, and we had an issue.

Is it possible to have types for `registerLocaleData` function or at lease export `LocaleDataIndex` from the public api, so we can use it like the following

```ts
import enUsLocal from '@angular/common/locales/en-US-POSIX';
import { registerLocaleData } from "@angular/common";

const mylocale = [...enUSlocale];
mylocale[LocaleDataIndex.CurrencyCode] = 'test';

registerLocaleData(mylocale, 'en-US');
```

### Relevant Package
`@angular/common`

**Comment by petebacondarwin** [comment]
As you say `LocaleDataIndex` is not exposed publicly. This is because the format of these locale files is supposed to be an internal implementation.  I accept that if you wish to provide your own locale data file (which I have occasionally recommended) one does need to know this information.  So we should consider exporting this enum.

For the moment you could work around this by using the "private" export of `ɵLocaleDataIndex` from `@angular/core`. Be aware this is not officially supported.

**Comment by petebacondarwin** [comment]
We discussed this feature and decided it is not something we want to support right now.
The internal layout of these locale files is not trivial and we don't want to make that public.

To do this properly we would need to provide some kind of API that allows developers to modify the contents of a locale, without exposing the internal structure. This would be a significant project and then require ongoing maintenance. Given that there has been no additional votes for this feature, that extra support cost is not acceptable.

In the meantime, you can continue to use the private APIs discussed above, but we make no guarantees that these will not change between releases, so you will need to ensure you have your own tests in place to ensure that you custom locales are working as expected.
