### ISSUE TITLE
Angular Service Worker does not update cached files even when new version is fetched

### ISSUE THREAD

**Issue by fikkatra** [angular/angular#39426]
## Description
We use angular 10 with the cli's built-in service worker for a PWA. A new version v2 of the app was published. The built-in service worker is not behaving as expected: _sometimes_, the old version v1 of the app is displayed even when v2 has been loaded previously by the same browser. The following steps illustrate the odd behaviour (although it occurs rather randomly):

- open the app: old version v1 is shown. This is still OK, as it is served up by the SW from its cache (although I would expect that if the user is online and v2 is available, v2 is displayed).
- reload the page: new version v2 is displayed => OK
- close the tab
- open a new tab and browse to the app. Old version v1 is displayed again. Why? At this point, the service worker should have updated its cache and display v2, right?

It seems the service worker does not update its cache, even when a page reload is done. We see this behaviour occurring very randomly. Often the new version is displayed, and sometimes the old version suddenly pops up.

We observed this behaviour in Chrome and Samsung Internet.

## Desired behaviour
Once the new version v2 is loaded by the browser, the old version v1 should never be displayed again.

## Versions
Angular CLI: 10.0.4
Node: 12.18.3
OS: darwin x64

Angular: 10.0.5
... animations, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router, service-worker
Ivy Workspace: Yes

Package                            Version
------------------------------------------------------------
@angular-devkit/architect          0.1000.4
@angular-devkit/build-angular      0.1000.4
@angular-devkit/build-optimizer    0.1000.4
@angular-devkit/build-webpack      0.1000.4
@angular-devkit/core               10.0.4
@angular-devkit/schematics         10.0.4
@angular/cdk                       10.1.0
@angular/cli                       10.0.4
@angular/material                  10.1.0
@angular/material-moment-adapter   10.1.0
@angular/service-worker         10.0.5
@ngtools/webpack                   10.0.4
@schematics/angular                10.0.4
@schematics/update                 0.1000.4
rxjs                               6.6.0
typescript                         3.9.7
webpack                            4.43.0

**Comment by gkalpak** [comment]
Thx for opening this issue, @fikkatra.

The behavior you describe is indeed unexpected. I can't think of why the ServiceWorker might be behaving like that, but I'm afraid there is not much for us to investigate without a reproduction 😕

It might be helpful if you could try debugging the situation and gather some more info. For example, what does [/ngsw/state][1] show on two tabs, one that correctly loads the 2nd version and one that unexpectedly loads the 1st (i.e. old) version at the same time?

Also, one question, when you said "reload the page" (in your second bullet point above) did you mean a normal reload or a "hard refresh" (for example, via <kbd>Ctrl</kbd> + <kbd>F5</kbd>)?

[1]: https://angular.io/guide/service-worker-devops#locating-and-analyzing-debugging-information

**Comment by fikkatra** [comment]
Hi @gkalpak, I'm afraid I can't give you detailed debugging information yet. However, I can tell you that:

- it was a normal reload
- when the old page was displayed, we observed that the SW did in fact fetch the new files. However, the browser did not display them. This might be normal behaviour, because we didn't subscribe to SW events to manually reload the page? But in any case, the SW did not update its cache for future page loads, which definitely isn't desired behaviour.

After manually removing the SW in DevTools in some of our browsers, we were unable to reproduce the issue in those browsers. Of course, this is something we can't ask our users to do.

**Comment by spock123** [comment]
@fikkatra having precisely this issue also. Difficult tobsay why, and hard to reproduce, but I can only reproduce it on mobile chrome

**Comment by fikkatra** [comment]
We finally managed to reproduce and debug the issue with the help of /ngsw/state. It showed a hash mismatch on index.html, which was caused by modifying a `<meta>` tag in index.html _after_ the build step (and thus after hash calculation).

I guess this could explain the behaviour we observe, although it is pretty strange that the faulty behaviour occurs only randomly, while the hash mismatch was always present.

**Comment by gkalpak** [comment]
Yeah, that makes sense. When fetching the new version fails, the ServiceWorker instance will enter a degraded mode where it serves only existing clients. However, since such errors could be transient (e.g.  network issues), the ServiceWorker will still keep the old version as the latest known working version.

So, while that ServiceWorker instance is "alive", new tabs will not be served by the ServiceWorker (and will thus get the latest version from the server). As soon as the current ServiceWorker instance is destroyed (which happens automatically by the browser after some period of inactivity to save resources, for example), then the next tab that is opened will result in a new ServiceWorker instance being created, which will serve the latest known good version from its cache (i.e. the old version).

This behavior is not ideal for this scenario, but it would be desirable in other scenarios. I am afraid there is no strategy that would be perfect for each usecase.

The good news is that as long as the latest version on the server is valid, the SW should work fine 😅

##
I am going to close this issue, since everything seems to work as expected, but feel free to continue the discussion below.
