### ISSUE TITLE
Access to humans.txt

### ISSUE THREAD

**Issue by mhipo1364** [angular/angular#3945]
Hi guys

I have a situation

I need to access to `humans.txt` and `robots.txt` using `www.mydomain.com` , but in angular, url manager don't let me to access it, how can I access to these files?

**Comment by PascalPrecht** [comment]
@mhipo1364 can you be a bit more specific about what doesn't work? What do you mean with "url manager doesn't let me access it" ? Are you requesting those files per Ajax?

More information needed.

**Comment by mhipo1364** [comment]
@PascalPrecht : thanks for respond, humans.txt and robots.txt should be accessible via domain name, but when I add humans.txt at the end of domain name, it automatically redirect to home url, and actually I never access to these files.

**Note**: I use html5 for removing # from url and `state` for url manager

**Comment by PascalPrecht** [comment]
Okay a couple of things:

- This sounds a bit like AngularJS 1.x / UI-Router code, but this is the repository for Angular 2. If that's the case, this would rather be an issue for http://github.com/angular/angular.js

- If you do use push state API and HTML5 mode, your server needs to be configured to always serve your `index.html` file, so that your SPA is served in any case.

- As soon as you use did that, the client is responsible for that particular URL, so you'd need to configure a state for `/humans.txt` which requests that data from the server.

- Or better, tell your server to always serve `index.html` except when `/humans.txt` and `/robots.txt` is requested. Then just serve those. But this of course, depends on what you actually want to do with that content.

Please verify if this is really an issue for the Angular 2 repo. If not, close this issue. Thanks!

**Comment by mhipo1364** [comment]
@PascalPrecht : yeah, it's for angular 1.x

Honest mistake
