### ISSUE TITLE
Update Support policy and schedule for angular 11

### ISSUE THREAD

**Issue by xiaoxiangmoe** [angular/angular#39559]
# 📚 Docs or angular.io bug report

### Description

see https://angular.io/guide/releases#support-policy-and-schedule

VERSION | STATUS | RELEASED | ACTIVE ENDS | LTS ENDS
-- | -- | -- | -- | --
^10.0.0 | Active | Jun 24, 2020 | Dec 24, 2020 | Dec 24, 2021
^9.0.0 | LTS | Feb 06, 2020 | Aug 06, 2020 | Aug 06, 2021
^8.0.0 | LTS | May 28, 2019 | Nov 28, 2019 | Nov 28, 2020

Can we update it to VERSION ^11.0.0?

**Comment by Airblader** [comment]
Angular 11 is not yet released.

**Comment by gkalpak** [comment]
As @Airblader said, v11 is not yet released. Once it is released (in a few days), it will follow the standard schedule: 6 months in active development and 1 year after that in LTS.

I am going to close the issue, since there is nothing to fix atm. Check back in a week or so (and feel free to open a new issue if the schedule has not been updated once v11 is released) 😉

**Comment by xiaoxiangmoe** [comment]
@Airblader @gkalpak Thank you for your reply. Do you know the release date in angular team's schedule?

**Comment by gkalpak** [comment]
If nothing changes, somewhere around the mid of November probably.
