### ISSUE TITLE
FormControl statusChanges are not emitted when binding to input

### ISSUE THREAD

**Issue by keatkeat87** [angular/angular#39588]
# 🐞 bug report

### Affected Package

 The issue is caused by package @angular/forms

### Is this a regression?

 don't know.
Update: this is **not** a regression, same problem happens in `10.2.0` version.

### Description

 
![image](https://user-images.githubusercontent.com/8691013/98360799-73b59d80-2065-11eb-85e6-acd1045dd95f.png)
a formControl with async validator. when no binding to input, everything work fine. 
subscribe will be call. but after binding to <input [formControl]="formControl">, the subscribe not be call any more.
p.s maybe relate with https://github.com/angular/angular/issues/14542

## 🔬 Minimal Reproduction

 [https://stackblitz.com/github/keatkeat87/angular-form-control-status-changes-no-emit-after-binding-to-input](https://stackblitz.com/github/keatkeat87/angular-form-control-status-changes-no-emit-after-binding-to-input)
![dada4](https://user-images.githubusercontent.com/8691013/98361024-c727eb80-2065-11eb-938b-cdd4a45a8461.gif)

## 🔥 Exception or Error
<pre><code>

</code>no error</pre>

## 🌍  Your Environment

**Angular Version:**
<pre>
Angular CLI: 11.0.0-rc.2
Node: 12.18.0
OS: win32 x64

Angular: 11.0.0-rc.2
... animations, cli, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, router
Ivy Workspace: Yes

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1100.0-rc.2
@angular-devkit/build-angular   0.1100.0-rc.2
@angular-devkit/core            11.0.0-rc.2
@angular-devkit/schematics      11.0.0-rc.2
@schematics/angular             11.0.0-rc.2
@schematics/update              0.1100.0-rc.2
rxjs                            6.6.3
typescript                      4.0.5
<code>

</code></pre>

**Comment by AndrewKushnir** [comment]
Hi @keatkeat87, thanks for reporting the issue and providing a repro, I was able to replicate it. More investigation is needed to find a root cause, but I want to mention that this is *not* a regression, sine the same problem can be reproduced in `10.2.0` version. Actually in `10.2.0` the behavior is worse where validator is not invoked even if there is no `[formControl]` binding. Thank you.

**Comment by AndrewKushnir** [comment]
I've performed further investigation and I'd like to share results.

What prevents an event to be emitted into `statusChanges` is the following logic in the `form_control_directive.ts` file:

https://github.com/angular/angular/blob/bdce7698fc2a49d31d90ae15a4f5629d00dd3085/packages/forms/src/directives/reactive_directives/form_control_directive.ts#L119-L126

This line has the `emitEvent` set to `false`, thus no events are emitted at this point. Also during the `updateValueAndValidity` function invocation there is a logic that cancels existing async validator subscription (since the results may no longer =be accurate):

https://github.com/angular/angular/blob/bdce7698fc2a49d31d90ae15a4f5629d00dd3085/packages/forms/src/model.ts#L781-L786

and as a result, the async validator that was invoked during the `FormControl` initialization never emits.

The `updateValueAndValidity` call with the `emitEvent` flag set to `false` was added a few years ago, so this issue is not a recent regression. Note: changing the `emitEvent` to `true` would not be a viable solution (it'd cause unnecessary events to be triggered), so more investigation is needed to find a suitable one.

**Comment by fallXone** [comment]
Is there any update on this issue? I was just about to file a new issue, but I believe this is the same thing I'm experiencing. I have a simple input bound to a formControl and the input is required. The initial status is "VALID", but after looking at the form group, the control is "INVALID" with errors since it's required. I am not seeing the "INVALID" status being emitted by statusChanges. Here is a stackblitz I created demonstrating the issue https://stackblitz.com/edit/angular-zjbbzb?file=src/app/app.component.ts

**Comment by antoci-alin** [comment]
Hello guys! 
Any updates on this topic? :)

**Comment by JeanMeche** [comment]
FWIW I think ##55134 can be a fix for it.

**Comment by JeanMeche** [comment]
Even though this issue is a bit older, #41519 has had more activity recently and had the same root issue. 
Let's continue over there.
