### ISSUE TITLE
AIO Facelift Request

### ISSUE THREAD

**Issue by dabalyan** [angular/angular#39595]
# 📚 Docs or angular.io feature request

### Description

Ever since Angular got released around 2015, angular.io has always looked the same, which is fine.
But at the risk of sounding petty, I think it has started to show it's age now, design wise, it feels too 2015.

I know Angular team has more important things to do then prettify the website, but I think it matters how the website looks, because a developer coming for the first time to the website might not get the feeling of super amazing framework that Angular is. It doesn't give the same confidence that it should.

### What's the affected URL?**
 https://angular.io/...

### Expected vs Actual Behavior**
Doesn't look modern, probably should look modern :)

## 📷Screenshot

This is just random minor modifications in colors and shadows, it's not necessarily the preferred design, it's just an example.
I'm just a developer, I know almost nothing about design principles.

![Screenshot 2020-11-07 045554](https://user-images.githubusercontent.com/17353112/98431436-8d7ed100-20b5-11eb-8d06-4c4835e60ccd.png)

### Anything else relevant?

I'm not sure if this has been requested before, or even qualifies as a request, but I think it'd probably make a big impact.

**Comment by gkalpak** [comment]
Thx for the suggestions, @dabalyan!
There is some UI improvement work going on in #36045 and #38750, but (as you guessed) this is not a high priority atm. Currently, we are focusing more on the content (ensuring it is clear, concise, complete and well organized) and also looking at improving the on-boarding experience of newcomers.

I am going to close this issue, since it is not directly actionable. We definitely welcome specific suggestions for things that can be improved, so keep 'em coming :smiley:

**Comment by dabalyan** [comment]
hey @gkalpak my pleasure :)

I see the list of improvements is long, and there are already good folks working on it.
I can understand that content has a higher priority, but I guess we could give the UI also some love while we're at it.
Just 2 cents, Angular team knows better, obviously :)

Makes sense, it's okay to close this one.
I wish I could contribute design wise, but alas I'm not very good at it 😑 😄
