### ISSUE TITLE
S1086: An accessor cannot be declared in an ambient context.

### ISSUE THREAD

**Issue by jayjupdhig** [angular/angular#39674]
Hi there!!

I try to build an ngx-admin-based angular web app that was created by one of your former employee. The time he has developed that project was from March 2019 to April 2019.

So i think he used Node.JS v10.x. 

And, so i saw, the 10.x Version of NodeJS is still supported & developed, last version is from October 2020:
https://nodejs.org/en/download/releases/

And that's the version i tried to build with - without any success.

My steps:

Before uninstalling the current version (it tried ALL of them, not just v10.x -> v11.x, v12.x, v13.x, v14.x, v15.x), i genereally execute that windows batches:

all.bat:

```
@echo on

call clean_before_uninstall.bat
call npm_uninstall.bat

runas /profile /savecred /env /user:WORKGROUP\user1 "C:\Tools\NPM_clean\clean_after_uninstall.bat"
```

clean_before_uninstall.bat

```
@echo on
cls

@echo off
rem call npm_function.bat npm uninstall cordova-plugin-build-architecture
rem timeout /T 2 /nobreak > nul 2>&1

rem call npm_function.bat npm uninstall -g native-run
rem timeout /T 2 /nobreak > nul 2>&1

rem call npm_function.bat npm uninstall -g cordova
rem timeout /T 2 /nobreak > nul 2>&1

rem call npm_function.bat npm uninstall -g @ionic/cli
rem timeout /T 2 /nobreak > nul 2>&1
@echo on


call npm_function.bat npm cache clean --force > nul 2>&1
timeout /T 2 /nobreak > nul 2>&1

call npm_function.bat npm uninstall -g windows-build-tools > nul 2>&1
timeout /T 2 /nobreak > nul 2>&1

call npm_function.bat npm uninstall -g @angular/cli > nul 2>&1
timeout /T 2 /nobreak > nul 2>&1

call delete_npm_directories.bat
```

delete_npm_directories.bat:

```
@echo on

rd /s /q "C:\Users\%USERNAME%\AppData\Roaming\npm" > nul 2>&1
timeout /T 2 /nobreak > nul 2>&1

rd /s /q "C:\Users\%USERNAME%\AppData\Roaming\npm-cache" > nul 2>&1
timeout /T 2 /nobreak > nul 2>&1

del /f /q "C:\Users\%USERNAME%\AppData\Local\Temp\npm-*" > nul 2>&1

if exist "C:\Users\%USERNAME%\.windows-build-tools" (
  timeout /T 2 /nobreak > nul 2>&1
  rd /s /q "C:\Users\%USERNAME%\.windows-build-tools" > nul 2>&1
)

pause
```

npm_uninstall.bat (depends what version is installed), which uninstalls node.js:

```
@echo on

MsiExec.exe /i {43342FBE-702A-4921-B19C-131087A3264B} > nul 2>&1
MsiExec.exe /i {86D77F05-3A56-4240-B704-128C4B5E73FD} > nul 2>&1
MsiExec.exe /i {6483D1C8-84CF-4BDE-8CFA-F1B11D7FE1E6} > nul 2>&1

pause
```

after node.js uninstall, i also run clean_after_uninstall.bat:

```
@echo on
cls

del /f /q /s "C:\Program Files\nodejs\*.*" > nul 2>&1
timeout /T 2 /nobreak > nul 2>&1

rmdir /q /s "C:\Program Files\nodejs" > nul 2>&1

pause
```

Then i installed many different NodeJS versions (almost everything, as already said).

After that i do that standard steps:

```
1.) npm install -g npm
2.) npm install -g @angular/cli
3.) cd PROJECT_FOLDER
4.) npm install
5.) ng build
```

Then i get that errors in red font in console:

1.) ERROR in node_modules/ng2-ckeditor/ckeditor.component.d.ts(34,9): error TS1086: An accessor cannot be declared in an ambient context.
2.) node_modules/ng2-ckeditor/ckeditor.component.d.ts(35,9): error TS1086: An accessor cannot be declared in an ambient context.

Thank you for your feedbacks.

I just want to change a (one) resource text entry - but i'm on that issue since monday. Now, it's firday and my chief gets insane soon...

Thank you for your feedbacks.

With best regards from Switzerland,
Jan

**Comment by JoostK** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).

---

The TS1086 indicates to me that `ng2-ckeditor` depends on a version of TypeScript that is newer than the version used in the project, it is independent from the Node version. This is likely due to the `ng2-ckeditor` version not being pinned in either a lockfile or the `package.json` file, such that you're installing a much newer version than was available at that time.

**Comment by selangley-wa** [comment]
Check if your problem is due to an upgrade of the typescript version which changed how accessor methods are mapped
 https://www.typescriptlang.org/docs/handbook/release-notes/typescript-3-7.html#37-breaking-changes

See if you can change your access to the variable from a get accessor method to directly accessing the variable as a public property.

**Comment by jmar83** [comment]
this is my personal account. thank you very much - will look about it.

**Comment by jayjupdhig** [comment]
https://github.com/chymz/ng2-ckeditor/issues/304

**Comment by jayjupdhig** [comment]
Z.B. sowas, WOW!! :-)

https://www.fairaudio.de/wp-content/uploads/2017/08/luxmann-14.jpg

Lieber SFr. 6900 als SFr. 690 - dafür hat man dann wenigstens was "richtiges" !!

**Comment by jayjupdhig** [comment]
https://github.com/npm/cli/issues/2187

**Comment by jayjupdhig** [comment]
https://github.com/npm/cli/issues/2187
