### ISSUE TITLE
Issue with locale sv.ts where jan. feb. '.' appears at the end

### ISSUE THREAD

**Issue by Ckolhari5353** [angular/angular#39753]
Please refer the below link where the highlighted line of code has this ['jan.', 'feb.', 'mars', 'apr.', 'maj', 'juni', 'juli', 'aug.', 'sep.', 'okt.', 'nov.', 'dec.'].
Our Swedish customers have reported an issue saying that 'nov.' is a typo because it ends with '.' is there any reason for having this '.' at the end of few moths in the above array? 
https://github.com/angular/angular/blob/master/packages/common/locales/sv.ts#L32
   
![image](https://user-images.githubusercontent.com/63306303/99622470-392e0680-2a50-11eb-89cd-76aed5c02f03.png)

**Comment by AndrewKushnir** [comment]
Hi @Ckolhari5353, thanks for providing additional information.

Angular i18n uses CLDR data and I checked that they have the same set of values ([see here](https://github.com/unicode-org/cldr/blob/master/common/main/sv.xml#L2483-L2494)). If you wish this to change it would need to be by getting CLDR to update their data. You can start by looking in their bug tracker here https://unicode-org.atlassian.net/secure/Dashboard.jspa

I'm closing this ticket because this can not be updated on Angular side.

Thank you.
