### ISSUE TITLE
Angular 11 - router.navigate with queryParamsHandling 'merge' or 'preserve' does not preserve parameters

### ISSUE THREAD

**Issue by Dlacreme** [angular/angular#39803]
# 🐞 bug report

### Affected Package
angular/router v11.0.0

### Is this a regression?
Yes. It was working fine on V10

### Description

router.navigate with options queryParamsHandling set to 'merge' or 'preserve' does not preserve parameters.

## 🔬 Minimal Reproduction
https://github.com/Dlacreme/angular-navigate-repro

this is a minimal app where app.component#on-init redirect to a different component using this:
this.router.navigate(['/', 'home'], {queryParamsHandling: 'merge'});

yet if you start http://localhost:4200?hello=world the app redirect to http://localhost:4200/home

## 🔥 Exception or Error
No JS error nor anything to note.

## 🌍  Your Environment

App generated with angular-cli v11.0.1
node v 14.4.0
App running with the latest version of angular 11.

**Anything else relevant?**

**Comment by atscott** [comment]
Hi @Dlacreme, could you provide a reproduction where this works as you'd expect in v10? When I downgrade your example, the behavior is the same.

In particular, the `queryParamsHandling: preserve` _does_ appear to work in both v10 and v11 when not in the `ngOnInit`. Presumably, triggering a navigation before the initial navigation completes causes the router to not be able to pick up on the current query params (again, because the first navigation has not yet completed).

**Comment by Dlacreme** [comment]
Hi @atscott,
You are right, I've also tried with angular 9 and the behavior seem to be the same. I guess I will just wait for the first navigation to be completed before triggering the redirection then.

In my opinion, this is a bug, because even though the first navigation is not completed, the parameters are already available in the URL therefore should be forwarded by the router. But since it seem the be the expected behavior, I will close this ticket.

Thanks,
