### ISSUE TITLE
Check control type using constructor.name does not work when deployed on server

### ISSUE THREAD

**Issue by msleiman2** [angular/angular#39814]
## 🔥 No visible Exception or Error
<pre><code>
let controlNames = Object.keys(this.form.controls);    
    controlNames.forEach(controlName => {
      let ctrl = this.form.controls[controlName];
      
     if (ctrl.constructor.name == 'FormGroup') {
// Code here is not being reached when deploying on server
     }
    });
</code></pre>

## 🌍  Your Environment

**Angular Version:** 9.1.12

**Comment by JoostK** [comment]
Hello, this happens because an optimizer has renamed symbols where possible to reduce the bundle size. In this case you could probably use the following:

```ts
let controlNames = Object.keys(this.form.controls);    
    controlNames.forEach(controlName => {
      let ctrl = this.form.controls[controlName];
      
     if (ctrl instanceof FormGroup) {
        // ...
     }
    });
```

It's not the responsibility of the framework to detect these kinds of things; maybe a linter could. Anyway, I'll close this as non-actionable for the framework.
