### ISSUE TITLE
It would be so nice if $localize could translate variables instead of just raw strings

### ISSUE THREAD

**Issue by hessamhoseinkhani** [angular/angular#39817]
# 🚀 feature request
I want to be able to use parameters as $localize input to get translated!

For example:

```
const list = ['translate this A' translate this B,translate this C];
getTranslated() {
     return list.map(item => $localize(item));
}
```

### Relevant Package
@angular/localize

### Description
 A clear and concise description of the problem or missing capability...
we cannot use $localize as a function that could accept a variable to translate.

### Describe the solution you'd like
 If you have a solution in mind, please describe it.
no idea yet.

### Describe alternatives you've considered
 Have you considered any alternative solutions or workarounds?
maybe making a pipe which has if statements inside.

**Comment by petebacondarwin** [comment]
Hi @hessamhoseinkhani - unfortunately the way that `$localize` is designed to work requires that its messages are easily statically analysable (even after minification). This sort of dynamic approach can not support compile-time translation. So it is not a feature that can be added. One should not think of `$localize` as being a function that can be called - instead think of it as a way to mark a string as needing translation.  In fact the way you have described it wouldn't work anyway since the signature of a tagged template handler is very different - `$localize(messageParts: TemplateStringsArray, ...expressions: readonly any[]): string`.

(Interestingly, if you do "runtime" translation - i.e. do not translate the `$localize` tagged strings, then you loaded the translations at runtime, and used the complicated signature above, you could get this to work. But it really isn't worth it).
