### ISSUE TITLE
Add support for square, and curly brackets in ngClass

### ISSUE THREAD

**Issue by JoshuaAlzate** [angular/angular#39835]
# 🚀 feature request

### Relevant Package
This feature request is for @angular/common

### Description
Currently, we do have a lot of syntaxes supported on ngClass. But there's no way to mix up the `[]`, and `{}` syntax. There are scenarios that we will need a ternary operator to choose between two sets of classes dynamically, and there's also chances that we just need one.

### Describe the solution you'd like
I setup a [sample](https://stackblitz.com/edit/angular-ivy-gkhqfc?file=src/app/app.component.html) where I describe the solution I like.

As you can see in there, I am comparing the key name of the object by putting it in square brackets. And when the condition false to any of the class stated, it will be return as a property key name.

```
<hello name="{{ name }}" [ngClass]="{
  [myCheckBox ? italic: underline]: true, 
  red: myCheckBox2, 
  serif: true}">
</hello>

<input type="checkbox" [(ngModel)]="myCheckBox" /> Style
<input type="checkbox" [(ngModel)]="myCheckBox2" /> Colour
```

This is what I have in mind, but it would be cleaner if we can handle it without explicitly putting `true` on it.

### Describe alternatives you've considered
Currently, the workaround for this is to put it on a square bracket array syntax and pass an empty class in case the condition falls to the other condition.
```
<hello name="{{ name }}" [ngClass]="[myCheckBox ? 'italic': 'underline', myCheckBox2 ? 'red' : '', 'serif' ]">
</hello>
```

**Comment by Dlacreme** [comment]
This seem extremely confusing for no reason and not that easy to implement. Why don't you simply use a function which returns the correct list of classes?
In my opinion, HTML should not hold so much logic

**Comment by petebacondarwin** [comment]
I agree with @Dlacreme here. The `NgClass` directive syntax is already complex (and confusing) enough - `ngClass` is one of the most searched for terms related to Angular!

The broader feature request, here, is to support computed property names in Angular template expressions. Since, as @Dlacreme, points out the idea is to avoid too much logic in templates, I don't think that this is something that we are likely to implement in Angular core.

**Comment by Joshanity17** [comment]
> This seem extremely confusing for no reason
On which part? So I could clarify it more.

> not that easy to implement
I would love to work with this once we consider to support this proposed solution.

> Why don't you simply use a function which returns the correct list of classes?
That's one of the solutions that we can do apart from the example workaround solution that I have provided which is great for complex and complicated operation.

> In my opinion, HTML should not hold so much logic
Well, I agree to you as well on this one. But there are also not so complicated scenarios that can be easily done with `ngClass` with a purpose of dynamically set CSS classes on an HTML element by databinding an expression that represents all classes to be added.

> The NgClass directive syntax is already complex (and confusing) enough
I believe it is because we handle multiple syntaxes, but once you get the idea of it, it isn't that confusing.

> points out the idea is to avoid too much logic in templates
Yes, I agree with you on this that it is a bad practice to bloat a lot of logical operation on the `HTML`; however, like on the example that I have provided, it is just a simple operation. And since you have mention that `ngClass` is complex, one thing that we can do to make it simple by putting this kind of syntax that will make it cleaner and increase readability.

**Comment by ulrikwalter** [comment]
I think, it's better way:

`<hello name="{{ name }}" [ngClass]="{
  italic: myCheckBox,
  underline: !myCheckBox,
  red: myCheckBox2, 
  serif: true}">
</hello>`

**Comment by shivamd20** [comment]
> This seem extremely confusing for no reason and not that easy to implement. Why don't you simply use a function which returns the correct list of classes?
> In my opinion, HTML should not hold so much logic

I prefer to keep all knowledge about styling in the HTML file itself. It plays nicely with tools like PurgeCSS.

**Comment by jessicajaniuk** [comment]
@JoshuaAlzate It unfortunately didn't get the required amount of votes to be considered. Our feature request process requires at least 20 community upvotes before we add it to be considered.

**Comment by JoostK** [comment]
Support for the computed property name syntax is tracked in #43485.
