### ISSUE TITLE
Slots broken in Angular Elements

### ISSUE THREAD

**Issue by nvsravank** [angular/angular#39869]
# 🐞 bug report
### Affected Package

No. First place would be to look at @angular/elements

### Is this a regression? 
Did not test in previous versions.

### Description
 A clear and concise description of the problem...
A slot is not effective.
When I run the example application I am expecting the slot to be overridden by the content being passed.
The end result is that it is not being overridden and the default value of the slot is always shown.
Can be seen using simple ng build and opening the index.html in the dist folder in any browser.
To simplify the repository below includes the dist folder as well.

Interesting thing is that if I put a lot of characters in the override slot in the index.html and refresh the browser multiple times, i can see the the slot is being overridden and then the default value is drawn back.
You can see the video of it in the dropbox location.
https://www.dropbox.com/s/olw2xof7y76441e/Angular%20Elements%20Slot.mp4?dl=0
You can see this multiple times in the video like between 3.09 and 3.10 (seconds)

## 🔬 Minimal Reproduction
https://github.com/nvsravank/angular-elements

## 🔥 Exception or Error
No Exceptions occur

## 🌍  Your Environment

**Angular Version:**
Angular CLI: 11.0.2
Node: 15.3.0
OS: win32 x64

Angular: 11.0.2
... animations, cli, common, compiler, compiler-cli, core
... elements, forms, platform-browser, platform-browser-dynamic
... router
Ivy Workspace: Yes

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1100.2
@angular-devkit/build-angular   0.1100.2
@angular-devkit/core            11.0.2
@angular-devkit/schematics      11.0.2
@schematics/angular             11.0.2
@schematics/update              0.1100.2
rxjs                            6.6.3
typescript                      4.0.5

**Anything else relevant?**
No.

**Comment by gkalpak** [comment]
Slots are not handled specially by the Angular compiler. You can use `<ng-content>` if you want content projection to work with your component by default (both when it is used as a regular component and as a custom element).

If you want to use `<slot>` (which is something that is handled by the browser), you have to use [ShadowDom][1] for your component's `ViewEncapsulation`:

```ts
@Component({
  ...
  encapsulation: ViewEncapsulation.ShadowDom,
})
```

[This StackBlitz][2] showcases using slots.

##
I am going to close this, since everything seems to work as expected, but feel free to continue the discussion below.
Also, if you think there is a place in the docs that it would be useful to mention that, please submit a new issue (or better yet a pull request :wink:).

[1]: https://angular.io/api/core/ViewEncapsulation#ShadowDom
[2]: https://stackblitz.com/edit/ngelements-issue-39869?file=src/app/app.component.ts
