### ISSUE TITLE
Cannot run ng serve

### ISSUE THREAD

**Issue by RVT123123** [angular/angular#39880]
🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑

[angular-errors.log](https://github.com/angular/angular/files/5612828/angular-errors.log)

🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑🛑
ng serve is not working for me

    OS: Win32 x64
    Node: 13.14.0
    npm: 6.14.9

**Comment by patilpatil101** [comment]
Try to delete that "angular/cli": "1.0.0-beta.28.3", in the devDependencies it is useless , and add instead of it "@angular/compiler-cli": "^2.3.1", (since it is the current version, else add it by npm i --save-dev @angular/compiler-cli ), then in your root app folder run those commands:

rm -r node_modules (or delete your node_modules folder manually)
npm cache clean (npm > v5 add --force so: npm cache clean --force)
npm install

**Comment by lazarljubenovic** [comment]
This is neither a bug report or feature request. This GitHub issue tracker is not suitable for support requests. Please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

**Comment by alan-agius4** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular-cli`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular-cli/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).
