### ISSUE TITLE
HTTP_INTERCEPTORS Angular 11

### ISSUE THREAD

**Issue by saddem1990** [angular/angular#39988]
# 🐞 bug report
HTTP_INTERCEPTORS work only in app.module dosent work in lazy module

**Comment by jnizet** [comment]
You have probably made an error in your code, like importing the HttpClientModule in your lazy module, and thus causing a second HttpClient to be used  for the lazy module, not using the one already configured with interceptors in the root module.

But of course, this is just a conjecture, since you chose to disregard the instructions of the issue template and thus didn't provide an stackblitz reproducing the error, making it impossible for anyone to reproduce and explain the issue you're facing.

If you only imported HttpClientModule in your root module, then it's another issue, but you should start by asking a question on StackOverflow, with a complete minimal reproduction, because I doubt it's an Angular issue: I (and probably thousands of other developers) successfully use http interceptors in lazy modules with Angular 11.

**Comment by atscott** [comment]
Thanks for reporting this issue. However, you didn't provide sufficient information for us to understand and reproduce the problem. Please check out [our submission guidelines](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-submitting-an-issue) to understand why we can't act on issues that are lacking important information.

If the problem still exists in your application, please [open a new issue](https://github.com/angular/angular/issues/new/choose) and follow the instructions in the issue template.

**Comment by lycwed** [comment]
Hi guys I'm facing the same issue that @saddem1990 is talking about it appears when I migrate from angular 9 to 11. It's failing with interceptors and I was also using HttpClient get method to retrieve blob but failing know... I will try to give you stackblitz example to reproduce this issue.
