### ISSUE TITLE
NG0200: Circular dependency in DI detected，Why and How to do?

### ISSUE THREAD

**Issue by Bluntc** [angular/angular#40068]
Dear，ALL：

**I want inject ParentCompoent to ChildComponent，**

But have a error is：

Error: NG0200: Circular dependency in DI detected for ParentComponent

parent Component：

```
@Component({
  selector: 'cy-parent',
  templateUrl: './parent.component.html',
  styleUrls: ['./parent.component.scss'],
  providers: [
    {provide: ParentComponent, useExisting: forwardRef(() => ParentComponent)}
  ]
})

export class ParentComponent {
  constructor() { }
}
```

child component：

```
@Component({
  selector: 'cy-child',
  templateUrl: './child.component.html',
  styleUrls: ['./child.component.scss'],

})
export class ChildComponent implements OnInit {
  constructor(
    @SkipSelf() @Optional() public _parentComp?: ParentComponent
  ) {
   
   }
}
```

**Comment by JoostK** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).

---

You should be able to get this to work by deleting the following bit from `ParentComponent`:

```ts
  providers: [
    {provide: ParentComponent, useExisting: forwardRef(() => ParentComponent)}
  ]
```

The component instance will be available to subclasses, even without the explicit provider. In fact, the explicit provider is currently providing a token as itself, which is why the circular error occurs.
