### ISSUE TITLE
Array<string> is not working in multi-style binding according to angular example.

### ISSUE THREAD

**Issue by ErVishalM** [angular/angular#40147]
Hi,

I was reading Angular attribute docs and I wanted to see the example of multi-style binding a . According to Angular [docs](https://angular.io/guide/attribute-binding#binding-to-multiple-styles) example.

![image](https://user-images.githubusercontent.com/43669644/102330414-7f26ad80-3faf-11eb-9a7e-6d4591f888dc.png)

This is not working or may be i am doing something wrong.
`Multi-style binding | Array<string> | ['width', '100px']`
[Stackblitz example is here](https://stackblitz.com/edit/angular-biyc5t?file=src%2Fapp%2Finput-overview-example.ts)

**Comment by JoostK** [comment]
That example looks a bit broken, it should be `['width: 100px']` in that case (using a single string)

**Comment by lazarljubenovic** [comment]
Should also probably be `['width: 100px', 'height: 100px']` to match the two examples above it.

**Comment by ErVishalM** [comment]
> That example looks a bit broken, it should be `['width: 100px']` in that case (using a single string)

Hi @JoostK I tried this but it is not working [Stackblitz example is here](https://stackblitz.com/edit/angular-biyc5t?file=src/app/input-overview-example.ts)

**Comment by ErVishalM** [comment]
> Should also probably be `['width: 100px', 'height: 100px']` to match the two examples above it.

Hi @lazarljubenovic I tried this but it is not working [Stackblitz example is here](https://stackblitz.com/edit/angular-biyc5t?file=src/app/input-overview-example.ts)

**Comment by petebacondarwin** [comment]
From looking at the ivy code handling these style bindings, it looks to me like this is actually a bug in the renderer.
This is the relevant line of code: https://github.com/angular/angular/blob/3b2e5be6cb5ee7d0d7630a6cc3a2d7111dc3dad9/packages/core/src/render3/instructions/styling.ts#L588

It seems to me that the only stylings that could be set by this array form would be booleans...

**Comment by petebacondarwin** [comment]
Indeed there is a unit test that seems to indicate that this is by design: https://github.com/angular/angular/blob/54303688fa28b9a57f51a48cbd064b1b70240d0a/packages/core/test/render3/instructions/styling_spec.ts#L401-L405

But that doesn't seem to be much use in practice?? I think it is more useful for class bindings not styles...

**Comment by mhevery** [comment]
I think this is an issue with documentation. The expected input for style is: 
https://github.com/angular/angular/blob/3b2e5be6cb5ee7d0d7630a6cc3a2d7111dc3dad9/packages/core/src/render3/instructions/styling.ts#L97-L99

The above does not include an array. 

There is a confusion because `style` and `class` share a lot of common code. So `<div [class]="['A', 'B']">` makes sense but `<div [style]="['A', 'B']">` does not. Which is whyt `style` takes a object: `<div [style]="{key: 'value'}">`. But that is wrong too as there is on `key` style. So a proper format is `<div [style]="{color: 'red'}">`. 

There could be argument made that because `<div [style]=" 'color: reg' ">`. Is valid one could argue that  `<div [style]=" [ 'color: red' ] ">` should be valid as well. But that will require that the code would parse the expression. In which case what about this? `<div [style]=" [ 'color: red', 'width: 100px; height: 200px' ] ">` Do we allow combination?

I think the simplest answer here is to just update the documentation that the above is not supported.

Would you have a use cases which would argue that supporting something like this is useful?

**Comment by petebacondarwin** [comment]
Thanks for the explanation @mhevery. So it just happens that `[style] = "[...]"` ends up running the same logic as `[class]="[...]"`, which is why it was confusing in the runtime. I'll make a change to that docs to remove the array form of the style binding.

I wonder if we could catch this in the AOT compiler, perhaps we could use type checking to ensure that `[style]` bindings can only be strings or objects and not arrays?  @JoostK or @alxhub?
