### ISSUE TITLE
Question: What's #f='form' ?

### ISSUE THREAD

**Issue by manfredsteyer** [angular/angular#4017]
Hi,

the template-driven-forms-sample defines a control-group using a form-tag with #f='form'. Now I'm wondering what that really means and whether this is some short-cut for a longer syntax. At first sight, it seems a bit strange, that a handle gets a value. I would have expected something like #f without an assignment.

What are the ideas behind this?

Wishes,
Manfred

**Comment by PascalPrecht** [comment]
Hi Manfred,

If you have `#f="form"` this basically means that you're assigning the instance of a component to that local `#f` variable. Why the `="form"`?

Well, if you have an element/component with more than one directive on it, how should angular know which instance you want to get a reference from? That's why there's a `exportAs` property on the `@Component` annotation that allows you to export a directive's instance under a specific name (in that case `form`).

Hope that clarifies it.

**Comment by manfredsteyer** [comment]
Hi Pascal,

thanks for your quick reply and this great explanation.

Wishes,
Manfred
