### ISSUE TITLE
Duplicated content projection in downgraded components during HMR

### ISSUE THREAD

**Issue by let00** [angular/angular#40201]
# 🐞 bug report

### Affected Package

@angular/upgrade

### Is this a regression?

No, afaik

### Description
I am running a hybrid angular app that has a downgraded Angular 2 component with an ng-content tag. When running in HMR mode, the downgraded component is nested inside the ng-content tag, resulting in duplicated components.

## 🔬 Minimal Reproduction

https://stackblitz.com/edit/angular-5qna3t-oqmr2b

For example, try changing the background color in https://stackblitz.com/edit/angular-5qna3t-oqmr2b?file=src%2Fapp%2Fdowngraded%2Fdowngraded.component.css.
Instead of updating the original background color, the changed component is added inside the ng-content tag.
https://imgur.com/a/3m3ndF4

## 🌍  Your Environment

**Angular Version:**
11.0.5

**Anything else relevant?**

**Comment by gkalpak** [comment]
There are a couple of issues here. 

##
First, having projected content in `index.html` is something that is not supported by our HMR. In general, projecting content from outside an Angular app is something that is not supported in Angular (2+) anyway, so this wouldn't work in a pure Angular (non-hybrid) app either.

The easy work-around here is to move the `<downgraded-ng2-component><app-root></app-root></downgraded-ng2-component>` into a simple AngularJS component and use that in `index.html` (see below for a working example).

##
The second issue is were you place the definition of the downgraded component (i.e. the `.directive('...', downgradeComponent(...))` call. One thign that you have to keep in mind with HMR is that some parts of the code (e.g. some files) maybe executed on an HMR update, but other won't.

In this case, with the definition of the downgraded component in `app.module.ts`, that definition would be executed everytime something would cause `app.module.ts` to be executed. If the same update would not cause `app.module.ajs.ts` to be executed again, what would happen is that the downgraded component would be defined on the existing `sampleApp` AngularJS module, which already contained a definition of the downgraded component. As a result, there would be two (identical) directives matching `downgraded-ng2-component`, which would result in douple-compilation (and thus projecting the content twice, which in turn would lead to duplication of the projected content).

A work-around here is to move the definition of the downgraded component somewhere that is guaranteed to execute only when the AngularJS module is defined, such as in `app.module.ajs.ts`. This way, you can be sure that the `.directive()` call will not happen on an existing AngularJS module that already has a definition on the downgraded component.

##
I hope that clarifies things a bit. You can see the above suggestions in action in this [StackBlitz demo][1].

Also, keep in mind that hybrid apps are not a great candidate for HMR, since you have to separate frameworks interacting and also AngularJS is not built with HMR in mind. Things might mostly work, but I am sure there are cornercases that will break.

I am going to close this as there is not something we can fix here (afaict), but feel free to continue the discussion below.

[1]: https://stackblitz.com/edit/ngissue-40201?file=src%2Fapp%2Fapp.module.ajs.ts
