### ISSUE TITLE
Proposal: Component AbortSignal Support

### ISSUE THREAD

**Issue by lacolaco** [angular/angular#40247]
# 🚀 Feature Proposal

### Relevant Package

 This feature request is for @angular/core

### Description

This proposal adds the first-class support of the [`AbortSignal`](https://developer.mozilla.org/docs/Web/API/AbortSignal) web standard.
AbortSignal is not only for Fetch API but will be used for unregistering DOM event listeners. 

[add signal to addEventListener by benjamingr · Pull Request \#919 · whatwg/dom](https://github.com/whatwg/dom/pull/919)

AbortSignal will become a new web-standard for various async tasks. If a component exposes its signal on destroyed, developers can use it for interop to other web-compatible (abortable) APIs.

RxJS team is also considering adding support of AbortSignal for automatic unsubscribing subscriptions.

[Discussion: AbortSignal approach · Issue \#5863 · ReactiveX/rxjs](https://github.com/ReactiveX/rxjs/issues/5863)

### Describe the solution you'd like

This is still a rough idea. I think `ElementRef` can expose its aborting signal.

```ts
@Component()
export class SomeComponent {

  constructor(private elRef: ElementRef) {}

  ngOnInit() {
    const signal: AbortSignal = this.elRef.abortSignal;

    // DOM event
    window.addEventListener('keyup', ..., { signal });

    // Fetch
    fetch(url, {signal}).then(...);

    // RxJS
    someStream$.subscribe(handler, { signal });
  }
}
```

**Comment by thw0rted** [comment]
I think before the issue is voted on some more detail would be useful.  What does the new signal do?  When does it fire?  Is this effectively just the below?

````ts
class MyComponent implements OnDestroy {
  private readonly controller = new AbortController();
  public get signal() { return this.controller.signal; }

  ngOnDestroy() { this.controller.abort(); }
}
````

Ben Lesh had a whole thing a few years back about having components fire a Subject when destroyed so that owned observables could use `takeUntil(destroyed)` instead of having to call `unsubscribe` in the `onDestroy` lifecycle event.  This does have the advantage of interoperating with native code that has adopted AbortSignal, but you'd get that "free" with Ben's idea if RX integrates AbortSignal directly.

**Comment by Airblader** [comment]
Related to #10185

**Comment by pkozlowski-opensource** [comment]
I can see how this could be a useful alternative to `ngOnDestroy` but at this point we are not ready to commit to the proposed API.

As indicated in https://github.com/angular/angular/issues/40247#issuecomment-855703974 the desired behaviour could be achieved - although with more code. 

We will be looking into making the hooking into component destruction easier - but the `AbortSignal` is not the path we want to take at the moment.
