### ISSUE TITLE
Subscribe error may be done like try catch in c#.

### ISSUE THREAD

**Issue by teocto** [angular/angular#40249]
```
 this.visitorService.getAllCurrentVisitorsList(this.query).subscribe( (data) => {
      this.visitors = data;
      this.isLoadingTable = false;
    }, error => {
      this.isLoadingTable = false;
    });
```
this.isLoadingTable = false; - repeating code. I wish if it could look like try{} catch{} function in c#. Is it possible?

```
this.visitorService.getAllCurrentVisitorsList(this.query).subscribe( (data) => {
      this.visitors = data;
    }, error => {
    },
    {
      this.isLoadingTable = false;
     }
);
```

Thank you for attention!

**Comment by petebacondarwin** [comment]
I think what you mean is the `try-finally` pattern, rather than`try-catch`. I believe that this is already possible using the [`finalize`](https://rxjs.dev/api/operators/finalize) operator. In reactive programming it is important to think more about the pipeline than just the final subscription.

In any case this code is part of the RxJS library and is not part of Angular directly so this is not the correct place to report this request.
