### ISSUE TITLE
make test results are visible on the CircleCI web application

### ISSUE THREAD

**Issue by AlexElin** [angular/angular#40255]
make test results are visible on the CircleCI web application
`store_test_results` should be configured to achieve this.
See CircleCi docs for more details https://circleci.com/docs/2.0/configuration-reference/#store_test_results

**Comment by josephperrott** [comment]
Unfortunately the results of our tests are not currently outputted in a format which CircleCI is able to parse and render to the UI.  Additionally, since many/most of our test runs are cache hits, the result which would be stored is actually not for the run which occurred.

At this point this is just a limitation of the setup we use.
