### ISSUE TITLE
docs(typings): make typings match bundles

### ISSUE THREAD

**Issue by jeffbcross** [angular/angular#4026]
Blocked by #4023 and #4025

Angular's typings files should match our bundles 1:1. See #3458 for more info about bundles.

 * angular2.d.ts (includes core, http, router)
 * core.d.ts
 * http.d.ts
 * router.d.ts
 * testing.d.ts
 * web_worker.d.ts
 * web_worker_ui.d.ts

Also make sure the typings get added to DefinitelyTyped, and get documented in our release process.

**Comment by jeffbcross** [comment]
@mhevery: @IgorMinar and I were just talking about changing the angular2 bundle to not provide an `angular2/angular2` import path, but would still include core, router, and http dependencies, which could be imported from their documented export: `angular2/core`, `angular2/http`, `angular2/router`. This would remove some ambiguity for docs, so that we don't have two messages about where to import things from.

This would be a breaking change, because no consumer could import from `angular2/angular2` anymore. I think it makes things simpler, and falls in-line with the discussions you and I have had about de-coupling concerns with bundles, sources, and imports. Do you see any issues with this change?

CC: @yjbanov @rkirov

**Comment by mhevery** [comment]
@jeffbcross I thought that we will break up, but still keep `angular2/angular2` as a super bundle. so you could still import from there. Looks like we need to chat some more about this.

**Comment by pkozlowski-opensource** [comment]
@jeffbcross I'm experimenting with CJS bundles as discussed yesterday and one thing that comes to my mind now, as we discussing splitting code is this: if we move to CJS and want to have separate bundles for core, http etc. I guess we need to make sure that other bundles (ex. http) only import from "public" part of the core, no? Otherwise we would end up pulling the same code into multiple bundles. 

For example, looking at https://github.com/angular/angular/blob/master/modules/angular2/src/http/http.ts we can see imports like `angular2/src/core/facade/async` or `angular2/src/core/facade/lang`. Those would be totally fine with System.register but we need to think harder about those problems when moving to CJS, no?

Sorry, didn't want to hijack the thread, but since we are talking about splitting bundles and what gets exported where, we need to take this into account.

**Comment by jeffbcross** [comment]
@mhevery that was still the assumption you and I were operating under. @IgorMinar and I were just re-considering what value was added by letting users import from `angular2/angular2` vs importing from `angular2/core`, 'angular2/http`, and `angular2/router`. angular2.js would still be a super bundle, it just wouldn't re-export its contents as `angular2/angular2`. We can chat in the office.

**Comment by jeffbcross** [comment]
@pkozlowski-opensource I think you're correct that modules should require public APIs. Http should be easy because facades could all be removed, given that it no longer supports Dart.

**Comment by jeffbcross** [comment]
I think the best use case for the angular2.js bundle is prototypes and reproductions. Given that I don't think it should be the default recommended way to use angular in production, I don't think we should standardize our docs and examples on the `angular2/angular2` import.

**Comment by pkozlowski-opensource** [comment]
@jeffbcross I agree that just sticking to public API of the core would be doable for http, probably harder for other parts (router, animation), though.

>  Given that I don't think it should be the default recommended way to use angular in production, I don't think we should standardize our docs and examples on the angular2/angular2 import.

@jeffbcross what would be your recommended setup then? People bundling they app + framework with things like webpack / browserify / systemjs? Or serving non-bundled files thnx to the HTTP2 goodies? Or sth else?

Once

**Comment by alexeagle** [comment]
Since we are moving away from the typings bundles and tsd/DefinitelyTyped, it would be good for this to work with the individual per-module `.d.ts` files now produced by the compiler.

I think we need a couple more files added to the new `test.typings.npm` task from the `typing_spec` directory. router is there already, we should add the other use cases we expect users to want like http.

**Comment by alexeagle** [comment]
in alpha.41, this will work without any typings distribution:

```
import {Component, bootstrap, View} from 'angular2/angular2';
import {RouteConfig, ROUTER_DIRECTIVES, ROUTER_BINDINGS} from 'angular2/router';
import {ConnectionBackend} from 'angular2/http';
import {AsyncTestCompleter} from 'angular2/test_lib';
import {AnimationBuilder} from 'angular2/animate';
import {DoCheck} from 'angular2/lifecycle_hooks';
import {MockViewResolver} from 'angular2/mock';
import {AbstractControl} from 'angular2/web_worker/worker';
import {WebWorkerApplication} from 'angular2/web_worker/ui';
```

So I think we could close this. If/when we provide bundled typings again, we'll have to decide the entry points that produce the bundles.

**Comment by alexeagle** [comment]
There is some good discussion here about bundling, but based on discussion this morning at standup, we don't need to do anything for typings right now, so I'll close this. Please re-open (or file more specific issues) if there is remaining stuff to discuss or do.
