### ISSUE TITLE
multiple NG9 angular elements consuming a service as a singleton using providedIn:platform

### ISSUE THREAD

**Issue by mamasdev** [angular/angular#40301]
# 🐞 bug report

### Affected Package
@angular/core

### Is this a regression?
No
### Description

I was working on a personal project and had a use case where I needed to share a single instance of service (library) between multiple angular elements...

I understand that angular 9 came up with a new flag for the Injectable decorator (providedIn:platform) which is mainly to share one single instance of service (library) between multiple angular elements (applications). I wasn't able to find any sample project explaining how to use the flag.

According to angular documentation for the providedIn flag:

'platform' : A special singleton platform injector shared by all applications on the page.

However, as each angular element bundle was containing the service code within it individually, the flag didn't work for me.

I read in a github issue thread that I need to use ngx-build-plus to externalize the library, I externalized the library from the angular element and then had it as a global umd bundle.

I'm not seeing any of the service code within the angular element bundle, but still, I can see multiple instances of the service are running even when using the (providedIn:platform) flag, I suppose it's a bug.

I've seen people asking the same question on this forum and in StackOverflow as well but not getting proper guidance, I've tried it all, that's why if anyone can point to a sample project that we can learn from, or let me know what I'm missing, it would be very beneficial, thanks!

## 🔬 Minimal Reproduction

a page with two angular elements trying to consume an externalized umd library 'similar to RxJS', but not able to consume a single instance of it using (@injectable({providedIn:'platform'})

## 🔥 Exception or Error
No Error, but the service has multiple instances.

## 🌍  Your Environment

**Angular Version:**

Angular9

**Comment by mlc-mlapis** [comment]
@mamasdev The documentation for `{providedIn:'platform'}` is really very unclear. It looks that it is intended only for special cases, but it's unknown what conditions have to be satisfied. It certainly doesn't work for your described case when you have two really independent instances because nothing can interconnect them, and none of them knows anything about the other.

Maybe it's related only to the case, when you create one platform `const platform = platformBrowserDynamic([AnyService]);`, where `AnyService` is that shared service instance, and then you use its `bootstrapModuleFactory` method to instantiate two application, like (https://angular.io/api/core/PlatformRef):
```
platform.bootstrapModuleFactory(FirstAppFactory);
platform.bootstrapModuleFactory(SecondAppFactory);
```

**Comment by mlc-mlapis** [comment]
@mamasdev You can look at https://github.com/flash-me/angular-micro-frontends, which contains a sample case of how to use it.

There were also some issues eliminated in Angular 9.0.6 and ng-package 9.0.3. More discussions here:
https://github.com/angular/angular/issues/35179
https://github.com/angular/angular/issues/35429
https://github.com/angular/angular-cli/issues/19164

**Comment by jelbourn** [comment]
@gkalpak do you know more about `providedIn: platform`? I'm not super familiar with the API.

**Comment by flash-me** [comment]
As the names indicates, the services will be provided at platform level. Your intention is correct. However, there are two details in my mind, that you’re probably missing / doing wrong.

1. Providing at platform level is useless, when the apps are in different platforms. You can find an example on how to reuse existing platforms [here](https://github.com/flash-me/angular-micro-frontends/blob/rollback/projects/first/first.mfe.ts#L29)
2. Behind the scenes, a platform is just a variable holding a reference. Since the default platform is [hardcoded in the library](https://github.com/angular/angular/blob/6a9e3284329baf1bb6b621a8840ace629eb4b16e/packages/platform-browser/src/browser.ts#L66), you have to ensure not to load multiple bundles of the angular libraries. There are many ways, some are easier, others are more complex. @mlc-mlapis linked a repo with one of the eaiser one. No third party deps required.

cheers
flash ⚡

**Comment by gkalpak** [comment]
@jelbourn: I don't know much about `providedIn: 'platform'`, but my understanding is that it works as @mlc-mlapis described in https://github.com/angular/angular/issues/40301#issuecomment-754003162.

I believe OP's issue has to do with bundling multiple Angular Elements as independent bundles (i.e. not as part of the same app). There is no ideal or officially recommended solution for this yet (afaik), but there are several discussions/approaches to achieve this (some using 3rd-party libs), as mentioned by @mlc-mlapis and @flash-me in https://github.com/angular/angular/issues/40301#issuecomment-754052305 and https://github.com/angular/angular/issues/40301#issuecomment-757082772.

**Comment by flash-me** [comment]
> @jelbourn: I don't know much about `providedIn: 'platform'`, but my understanding is that it works as @mlc-mlapis described in [#40301 (comment)](https://github.com/angular/angular/issues/40301#issuecomment-754003162).
> 
> I believe OP's issue has to do with bundling multiple Angular Elements as independent bundles (i.e. not as part of the same app). There is no ideal or officially recommended solution for this yet (afaik), but there are several discussions/approaches to achieve this (some using 3rd-party libs), as mentioned by @mlc-mlapis and @flash-me in [#40301 (comment)](https://github.com/angular/angular/issues/40301#issuecomment-754052305) and [#40301 (comment)](https://github.com/angular/angular/issues/40301#issuecomment-757082772).

Yes, there is. It is even officially the first choice tool besides the webpack builder for angular: **ng-packagr**, which uses rollup behind the scenes.
 Everything outside of the compilation root are regarded as externals and thus will not be included in the bundle. You don’t have to bother about the right setup etc. just follow the official docs on how to build libraries and you’re done 🙂

**Comment by flash-me** [comment]
You will likely need to play around with UMD and their ids. A good explanation what this is and why they are important can be found [here](https://github.com/ng-packagr/ng-packagr/issues/1757#issuecomment-756946148). 
The context might be different, but the information applies here, too

cheers
flash ⚡

**Comment by mamasdev** [comment]
> @mamasdev You can look at https://github.com/flash-me/angular-micro-frontends, which contains a sample case of how to use it.
> 
> There were also some issues eliminated in Angular 9.0.6 and ng-package 9.0.3. More discussions here:
> #35179
> #35429
> [angular/angular-cli#19164](https://github.com/angular/angular-cli/issues/19164)

Thanks for the sample code and project, once I had the elements within same platform, only a single instance of the externalized service was shared.

**Comment by jelbourn** [comment]
This sounds like it's resolved, then.

**Comment by mlc-mlapis** [comment]
@jelbourn But probably it leads to a request for adding some details and explanations to the docs. Because of the core layer and correct formulation, this should be added by some core team members.
