### ISSUE TITLE
Confusing compiler error message for malformed expression

### ISSUE THREAD

**Issue by jelbourn** [angular/angular#40398]
### Reproduction
https://stackblitz.com/edit/angular-smg75b?file=src%2Fapp%2Fbutton-overview-example.ts

### Current behavior
Having a template like this:
```html
<a [href]="a:">Link</a>
```

gives an error like:
```
Quotes are not supported for evaluation!
Statement: located at ng:///AppModule/ButtonOverviewExample.html@0:11
```

### Expected behavior
I would expect an error message along the line ``"Unexpected character ":" in expression``

**Comment by petebacondarwin** [comment]
Just some background here. We support a thing called "quoted expressions" which are triggered by the expression containing a `:` colon character. See https://github.com/angular/angular/commit/b6ec2387b31ad1f51b95c8fac8f2a60b2de855f6, where it was introduced.

So arguably the error message is accurate but confusing, since it doesn't explain what a "quote" is in this context.
