### ISSUE TITLE
Chrome: Angular Service worker offline mode doesn't work with Subapp

### ISSUE THREAD

**Issue by parasharsh** [angular/angular#40431]
In Chrome Angular Service worker doesn't work in offline mode if the application is accessed as a subapp. It does work fine with Firefox. The sample application is available at  https://github.com/parasharsh/serviceworker/ 

If we run the httpserver from dist folder the service worker does not work (We get 504 error in the browser) whereas if the httpserver is started from the application folder inside the dist then it does work fine.  Any thoughts what configuration I am missing?

**Comment by gkalpak** [comment]
In order for the SW to be able to work offline, the generated `ngsw.json` config needs to contains correct URLs for the cached files. By default, it expects that the files are served from the top-level of the origin (e.g. `https://examples.com/<file/path>`).

If you are going to serve the app from a sub-path, you need to pass the `--base-href` flag when building. This will allow the CLI to generate the `ngsw.json` conrrectly. For example: `ng build --prod --base-href=/base/path/`

In your case, you would need to run: `ng build --prod --base-href=/angular-starter/`
Alternatively, you can use `--base-href=./`, which would allow the SW to work for any sub-path.

##
BTW, the `scope` property in your [manifest.webmanifest][1] is invalid (which will cause the browser to ignore it). When the `scope` property is a relative URL, it is resolved relative to the manifest URL ([MDN][2]).

So, with a manifest at `/angular-starter/manifest.webmanifest` and a `scope` of `./angular-starter/`, the resolved URL will be `/angular-starter/angular/starter/`. Since the `start_url` is `./`, which resolved relative to the manifest URL becomes `/angular-starter/`, it is outside the resolved scope. This in turn renders the `scope` invalid and the browser will ignore it.

If you want to specify a `scope` (which is generally a good idea), you must set it to `/angular-starter/` (without the leading `.`) or `./`.

##
I am going to close this issue, because everything seems to work as expected, but feel free to continue the discussion below.

[1]: https://github.com/parasharsh/serviceworker/blob/28f71743acb7659f6e4fb4248ef4b74fb89113f9/src/manifest.webmanifest#L7
[2]: https://developer.mozilla.org/en-US/docs/Web/Manifest/scope
