### ISSUE TITLE
Error when trying to add/remove class to element from directive code using Renderer2

### ISSUE THREAD

**Issue by platon-rov** [angular/angular#40432]
# 🐞 bug report

### Affected Package

The issue is caused by package **@angular/core**

### Is this a regression?

No

### Description

When trying to use **Renderer2** to add/remove class to directive host element - error is shown, class is not added/removed. When doing the same from component's code - OK.

## 🔬 Minimal Reproduction

[StackBlitz](https://stackblitz.com/edit/angular-ivy-n7gvzt?file=src/app/app.component.ts)

## 🔥 Exception or Error

<pre><code>ERROR DOM Exception: Failed to execute 'add' on 'DOMTokenList': The token provided must not be empty.
...
ERROR DOM Exception: Failed to execute 'remove' on 'DOMTokenList': The token provided must not be empty.
</code></pre>

## 🌍  Your Environment

**Angular Version:**
<pre><code>11</code></pre>

**Comment by JoostK** [comment]
Heya, it looks the problem here is that the `focusable` attribute binds an empty string to `FocusableDirective.focusable` as it is declared as an input, such that subsequently adding/removing the class fails as it's illegal to add an empty string.

As far as I can tell this is working as expected, so I'll close this issue. Feel free to continue the discussion below.
