### ISSUE TITLE
Support override of bindings in `TestComponentBuilder` (alpha-36)

### ISSUE THREAD

**Issue by wardbell** [angular/angular#4044]
Today we have `overrideTemplate`, `overrideDirectives`, and `overrideViewMetadata`.

But there is no `overrideBindings` and (I'm pretty sure) that means we cannot mock a DI binding that is mentioned in the `bindings` or `viewBindings` properties of `@Component`.

Why? Because those properties set bindings in the component's child injector which is inaccessible to the test developer.

Would love to be wrong about this.

**Comment by PascalPrecht** [comment]
You are not. I also check the source code of TCB. I think it's not even super hard to implement this, unfortunately i'm a bit packed right now. Thanks for opening this.

**Comment by vicb** [comment]
we have `beforeEachBindings()` for that, see it in action in [integration_spec](https://github.com/angular/angular/blob/70f6a46f1cbe090c946fd5ffea13f78be216ac05/modules/angular2/test/core/compiler/integration_spec.ts#L100).

**Comment by PascalPrecht** [comment]
@vicb `beforeEachBindings()` doesn't help here. This we can use to setup general bindings for our tests. But as soon as a component that needs to be tested comes with it's own bindings, we're not in control anymore on what they look like.

@wardbell is correct that we need to extend the TCB to support `overrideBindings` as well, otherwise we can't setup mock bindings for child injectors.

**Comment by PascalPrecht** [comment]
@wardbell FYI: there's a pending PR right here! ~ https://github.com/angular/angular/pull/4052

\o/
