### ISSUE TITLE
Angular elements input property bindings with ng-container wrapper problems

### ISSUE THREAD

**Issue by intellix** [angular/angular#40452]
# 🐞 bug report

### Affected Package

The issue is caused by package @angular/elements or @angular/core

### Is this a regression?

Don't know

### Description

 A clear and concise description of the problem...
When using @angular/elements and you have an outer/inner component, with an ng-container wrapper, the input property bindings don't apply to the element, despite getters/setters running. If you remove the wrapping ng-container then the input bindings work.

## 🔬 Minimal Reproduction

https://stackblitz.com/edit/angular-ivy-inner-outer-element-cd

## 🌍  Your Environment

**Angular Version:**
<pre><code>

@angular/animations 11.0.8
@angular/common 11.0.8
@angular/compiler 11.0.8
@angular/core 11.0.8
@angular/elements 11.0.8
@angular/forms 11.0.8
@angular/platform-browser 11.0.8
@angular/platform-browser-dynamic 11.0.8
@angular/router 11.0.8
@webcomponents/custom-elements 1.4.3
rxjs 6.6.3
tslib 2.1.0
zone.js 0.11.3
</code></pre>

**Comment by gkalpak** [comment]
The problem stems from the fact that you use the same string for both the Angular selector of the components and the tag name of the corresponding Custom Elements.

Since you are using the Custom Elements in an Angular app, `my-outer`/`my-inner` can match both the Angular components _and_ the defined Custom Elements. This, in turn, can lead to trying to apply the same component twice on the same DOM element (including processing its contents twice) and mess things app.

If you switch to using different tag names for the Custom Elements than the components' selectors, everything works fine (afaict): [Updated StackBlitz][1]

##
I am going to close this, since everything seems to work as expected, but feel free to continue the discussion below.

[1]: https://stackblitz.com/edit/ngelements-issue-40452

**Comment by intellix** [comment]
Great, thanks for looking into it and allowing me to move forward with my project :) 

I think it'd be good to show a notice/hint/warning in the Elements docs about having to have a different tag registered to the component's selector. 

Moving forward, would it perhaps be something to allow using the same selector as defined on the component or to throw an error if you declare one that already exists in the "Angular selector registry"?

We're migrating a set of CMS components from Components to Elements and already have a lot of code and e2e tests that depend on those selectors. I guess the best way for us would be to rename the Component selector to prevent this so Elements can use those tags:

```ts
@Component({
  selector: 'app-header-cmp',
  ...
})
export class HeaderComponent { ... }
```

**Comment by gkalpak** [comment]
> I think it'd be good to show a notice/hint/warning in the Elements docs about having to have a different tag registered to the component's selector.

Good call! I created #40510.

##
> Moving forward, would it perhaps be something to allow using the same selector as defined on the component or to throw an error if you declare one that already exists in the Angular selector registry?

That is an interesting idea. However, I am afraid we should not make this a hard restriction. For example, Angular Elements are not necessarily used exclusively in Angular apps and people might want to intentionally use the same selector. (Also, I am not sure there is one "Angular selector registry", especially in some of the scenarios where Angular Elements are used (such as micro-frontends, CMS, etc.).)

##
> I guess the best way for us would be to rename the Component selector to prevent this so Elements can use those tags

Sounds about right :smiley:

##
> My jest snapshots have changed now as well and it makes me wonder if I should be testing the component using Elements as that's the primary way I'm using it?

I can't really comment on that. Personally, I would go for using the `Component` in unit tests (since that gives you access to more testing APIs) and testing the Custom Element via e2e tests. But it ultimately depends on your exact setup and needs.
