### ISSUE TITLE
Sanitizer is injected as null when Ivy is enabled

### ISSUE THREAD

**Issue by thesam** [angular/angular#40627]
# 🐞 bug report

### Is this a regression?
Yes, if Ivy is disabled (enableIvy: false) if works as it did before. We discovered the problem when trying to switch from View Engine to Ivy.

### Description
When trying to inject a variable of type Sanitizer (from @angular/core, base class of DomSanitizer) into a component, the value null is injected instead. 

I would except an error/exception to be thrown if a value of type Sanitizer cannot be injected. Now null is injected (without any error thrown) and the component crashes in runtime when trying to use the Sanitizer (since it is null).

If Ivy is disabled, a Sanitizer object is injected and can be used properly.

## 🔬 Minimal Reproduction
https://stackblitz.com/edit/angular-ivy-yvvpwx?file=src/app/app.component.html

## 🌍  Your Environment

**Angular Version:**
<code><pre>
Angular 11.0.8 (see Stackblitz reproduction)
</code></pre>

**Comment by petebacondarwin** [comment]
You can see why the Sanitizer is not being provided by default in these lines of code: https://github.com/angular/angular/blob/3e1e5a15ba1d5a08daf9179083e3394df10299bb/packages/platform-browser/src/browser.ts#L45-L58

Instead in Ivy its provider is defined on the class itself: https://github.com/angular/angular/blob/d1ea1f4c7f3358b730b0d94e65b00bc28cae279c/packages/core/src/sanitization/sanitizer.ts#L20-L24

This was implemented here: https://github.com/angular/angular/commit/2e4d17f3a9fe856f28f4c5c31d3f914df77faca5

So this clearly is by design but doesn't appear to have been captured in our breaking changes notes for migrating to Ivy.

**Comment by thesam** [comment]
I see. Thank you for clearing this up! We will inject DomSanitizer instead.
