### ISSUE TITLE
Runtime Errors (Template parse errors) are not logged any more as Errors but regular info

### ISSUE THREAD

**Issue by sinisarudan** [angular/angular#40628]
# 🐞 bug report

### Is this a regression?

Yes

### Description

Run time errors (more specifically 'Template parse errors' at least) are not logged in Dev Console as Errors or Warning any more, but as regular text, thus being harder to noticed.

So, the following error is not displayed at all if we turn off "Info" from the default levels of Console logging:

```
Error: Template parse errors:
Can't have multiple template bindings on one element. Use only one attribute prefixed with * ....
```

## 🔬 Minimal Reproduction
```
<div *ngIf="true" *ngFor="let a of ['foo']">
```

**Comment by petebacondarwin** [comment]
Thanks for reporting this issue. However, you didn't provide sufficient information for us to understand and reproduce the problem. Please check out [our submission guidelines](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-submitting-an-issue) to understand why we can't act on issues that are lacking important information.

I guess you are using JIT compilation, otherwise there should be no compilation at runtime. Moreover you have not specified the version of Angular where this does not work.

**Comment by AndrewKushnir** [comment]
Closing this ticket as non-actionable without a repro. If the problem still exists, please create a new ticket and provide a repro, so that we can investigate the issue.
