### ISSUE TITLE
docs: code section font doesn't look good

### ISSUE THREAD

**Issue by eneajaho** [angular/angular#40666]
# 📚 Docs or angular.io bug report

### Description
Code section font on the documentation doesn't look good (chars get some bold parts). Sometimes the code becomes hard to read because of it. 
If you zoom in 150% the font looks ok.

### Expected vs Actual Behavior
Choosing some other font for the code sections or fixing the current one. 

## 📷Screenshot
- Doesn't look ok
![image](https://user-images.githubusercontent.com/25394362/106621749-2b7a1e80-6573-11eb-975b-63286cfab235.png)

- This looks good (zoomed in 150%)
![image](https://user-images.githubusercontent.com/25394362/106621692-18ffe500-6573-11eb-81d7-31f677177bff.png)

### Browser info
Both Chrome and Edge (Chromium)
Resolution: 1920 x 1080

**Comment by gkalpak** [comment]
It seems that currently we use `Droid Sans Mono` (style specified [here][1], font loaded [there][2]).
It might make sense to switch to `Roboto Mono`, since we are using `Roboto` as our main font.

Would be interested in submitting a pull request, @eneajaho?

[1]: https://github.com/angular/angular/blob/d754cc1ea56efc771867ac288e25a1968fd314fe/aio/src/styles/_constants.scss#L3
[2]: https://github.com/angular/angular/blob/d754cc1ea56efc771867ac288e25a1968fd314fe/aio/src/index.html#L29

**Comment by eneajaho** [comment]
I'm submitting a pull request now.
