### ISSUE TITLE
fix(Component with async service): TypeError: jasmine.createSpyObj is not a function

### ISSUE THREAD

**Issue by dianmonblan** [angular/angular#40705]
# 📚 Docs or angular.io bug report

### Description

  Fix example in documentation Component with async service

### What's the affected URL?**
 https://angular.io/guide/testing-components-scenarios#component-with-async-service

### Reproduction Steps**

 

- Make use of jasmine.createSpyObj for any testing scenario

### Expected vs Actual Behavior**

 Correct operation vs TypeError: jasmine.createSpyObj is not a function

## 📷Screenshot

[Component with async service -> Testing with a spy](https://imgur.com/gI8kwQC)
[TypeError: jasmine.createSpyObj is not a function](https://imgur.com/b2spzRT)

## 🔥 Exception or Error
<pre><code>

 TypeError: jasmine.createSpyObj is not a function
</code></pre>

### Anything else relevant?

Jest doesn't have a function named [createSpyObj()](https://stackoverflow.com/questions/52191258/typeerror-jasmine-createspyobj-is-not-a-function) like default jasmine has , please visit this link Jest createSpyObj which is a custom createSpyObj function in jest or just switch to jasmine instead.

**Comment by gkalpak** [comment]
It is not 100% clear what steps you are following to get the error. Based on the info you provided, it sounds like you are trying to use Jest for testing. While that is definitely possible, the default test runner for Angular apps (and the one discussed in the testing guides) is Jasmine (which does have a `createSpyObj()` method).

Code written for one test runner (or assertion library or other testing tool) is not guaranteed to work for another equivalent runner or tool. If you want to use a different tool, you need to adapt your code to be compatible with that tool.

##
I am going to close this, since everything works as expected afaict, but feel free to continue the discussion below.

**Comment by dianmonblan** [comment]
@gkalpak thanks for your reply.

**Resolved!**

The problem is NX!
