### ISSUE TITLE
Memory Leak on Mouse Move and on Route Change

### ISSUE THREAD

**Issue by tshakeel18** [angular/angular#40722]
# 🐞 bug report

### Affected Package

 The issue is caused by package @angular/....

### Is this a regression?

No, I have tested that with angular 9,10 and 11. Each and every version has same issue.

### Description

 Created a new angular app by using ng new command with scss and routing enabled.
 Added two lazy load routes with default html no logic in the component.
 While switching from one route to another route continuously more than 10 times. I have noticed that memory footprint in chrome task manager is using more and more memory continuously without releasing the unused memory.
 And also on just moving the mouse on the page, I have noticed the memory keeps increasing. 
 here u can see the gif and spike in memory footprint.
 
![memory-leak](https://user-images.githubusercontent.com/38935214/107028485-71cbb980-67cf-11eb-8e1a-fb0ab0233f76.gif)

## 🔬 Minimal Reproduction

[Github Repo Url](https://github.com/tshakeel18/memory-leak-demo)

## 🔥 Exception or Error
<pre><code>

</code></pre>

## 🌍  Your Environment

**Angular Version:**
<pre><code>

</code></pre>

**Anything else relevant?**

**Comment by atscott** [comment]
Hi @tshakeel18 - Please provide a reproduction for this issue in order for us to investigate the root cause.

**Comment by tshakeel18** [comment]
> Hi @tshakeel18 - Please provide a reproduction for this issue in order for us to investigate the root cause.

Updated the description with github repo for minimal reproduction.

**Comment by jelbourn** [comment]
I cloned the repo here and took a look. As far as I can tell, there is no memory leak. For investigating this type of memory usage, the Chrome task manager doesn't provide an accurate picture of the app itself because any number of things going on in that tab can affect the memory usage, including extensions. Using the memory profiler in devtools, I saw no evidence of a memory leak in the application itself.
