### ISSUE TITLE
Guide Suggestion: How to build a Serverless CMS-Powered Angular App

### ISSUE THREAD

**Issue by moluwole** [angular/angular#40779]
# 📚 Docs

### Description

Hi there, I would like to contribute a guide/post on how to build a Serverless CMS-Powered application with Angular and ButterCMS Api for the background. 
We would also like to link some of our resources [here](https://buttercms.com/blog/tag/angular/) on the Angular resources Page

Thanks

**Comment by jelbourn** [comment]
@moluwole thanks for the suggestion, check out our contributing guidelines for the resources page here:
https://github.com/angular/angular/blob/master/aio/content/marketing/resources-contributing.md

Closing this issue since we don't have anything specific to track here, but feel free to send a PR and we'll take a look.
