### ISSUE TITLE
ExpressionChangedAfterItHasBeenCheckedError why is thrown Error and not some specific Exception

### ISSUE THREAD

**Issue by sysmat** [angular/angular#40839]
# 🚀 feature request

### Relevant Package
ng v 11

### Description
NG0100: ExpressionChangedAfterItHasBeenCheckedError:  this should be dedicated exception

### Describe the solution you'd like
create an exception which extends Error

**Comment by petebacondarwin** [comment]
Could you expand on this request. What is the reason for the request? What benefit do you see in having the error being a subclass of Error?

**Comment by lazarljubenovic** [comment]
One benefit that comes to mind would be that it's easier to filter errors caught by the global error handler by checking if they're `instanceof AngularError`, although maybe there's a different mechanism to check if an error is an Angular error that I'm not aware of.

**Comment by sysmat** [comment]
- As in other languages if you catch or throw only general error your code is limited. 
- as @lazarljubenovic you can filter or do something else 
- AngularError I would like it finer graded, not just  AngularError

**Comment by AndrewKushnir** [comment]
Just a quick comment: we've introduced [the `RuntimeError` class](https://github.com/angular/angular/blob/master/packages%2Fcore%2Fsrc%2Ferrors.ts#L83) recently to have a consistent way of formatting error messages (include an error code) at runtime. Parts of the codebase already adopted it, but there are still places where plain `throw new Error(...)` is in use. The `RuntimeError` class is currently private. Once we are closer to switching majority of code to use the `RuntimeError` - we'll consider making it public, so that it can be used in applications code to detect Angular-specific errors.

**Comment by JeanMeche** [comment]
There hasn't been no strong signal from the community yet for making RuntimeError public. 

Also we don't have plans to introduce different error classes for each situation - that'd be hard to maintain.
