### ISSUE TITLE
Angular issue with removing duplicated elements when moved around in DOM

### ISSUE THREAD

**Issue by MichaelOdumosu57** [angular/angular#40843]
# Error Report

## Questions

Please fill out answers to these questions, it'll help us figure out
why things are going wrong.

- **What did you do?**

* I hit the remove button in  my custom made dropdown
this dropdown is not
```html
<select>
	<options></options>
	<options></options>
	<options></options>
</select>
```
it's
```html
<div>
	<a>Select Item</a>
	<a>1</a>
	<a>2...</a>
</div>
```
* the orgignal element was ```<a>Select Item</a>``` and directives were use to create the dropdown feature
* I hit the remove button to remove the element and an ngOnDestroy would fire to remove the additional elements that achieved its dropdown feature in ngOnInit

- **What did you expect to happen?**

* I expected the element and its auxillary to be removed from the DOM
* The news has been right the learning curve is getting ridiculous for Angular, beginners and advanced should be told at face value what Angular is all about I am a strong supporter for Angular, and I cannot tolerate React to its core, but this is a sad fact I now had 1 rant over Angular. I learned in ngOnDestroy you had to get @ViewChildren.changes, if you want to modify the DOM tree, observable.subscribe has a next,error,complete, which you can take advantage of in subjects, ChangeDetection.onPush should be the default strategy as its running all the time. Angular has been getting irrelevant it its features, which builds on itself in complexion while going nowhere

- **What happened instead?**

* the DOM threw an error claiming the angular code was trying  to
```
parent.insertBefore('comment','dropdown-container')
```
* the dropdown-container IS NOT a direct child of parent which is the component element 

- **Have you tried any solutions posted on similar issues in our issue tracker, stack overflow, or google?**

* I've tried many manipulations of renderer2, ChangeDetectorRef, 
* I would love to flip the couse and call ngOnDestroy then remove the element but thats not how Angular works, besides it gets called again and even though it changes the reference to null, when talking about scaling and future Angular version this is not the way to go

![](https://github.com/MichaelOdumosu57/Judima-Framework/blob/master/AngularApp/issues/Angular_issue_with_removing_duplicated_elements_when_moved_around_in_DOM/zoom_0.gif?raw=true)
<img src="https://github.com/MichaelOdumosu57/Judima-Framework/blob/master/AngularApp/issues/Angular_issue_with_removing_duplicated_elements_when_moved_around_in_DOM/zoom_0.gif?raw=true" width="40" height="40" />

## Backtrace

```
core.js:6150 ERROR DOMException: Failed to execute 'insertBefore' on 'Node': The node before which the new node is to be inserted is not a child of this node.
    at DefaultDomRenderer2.insertBefore (http://localhost:8000/vendor.js:124979:16)
    at nativeInsertBefore (http://localhost:8000/vendor.js:91073:14)
    at applyToElementOrContainer (http://localhost:8000/vendor.js:90504:7)
    at applyNodes (http://localhost:8000/vendor.js:91389:11)
    at applyNodes (http://localhost:8000/vendor.js:91366:13)
    at applyView (http://localhost:8000/vendor.js:91398:3)
    at addViewToContainer (http://localhost:8000/vendor.js:90596:3)
    at ViewContainerRef.insert (http://localhost:8000/vendor.js:109890:9)
    at ViewContainerRef.createEmbeddedView (http://localhost:8000/vendor.js:109827:12)
    at http://localhost:8000/vendor.js:140230:45

core.js:6150 ERROR TypeError: Cannot read property 'context' of null
    at NgForOf._applyChanges (ng_for_of.ts:255)
    at NgForOf.ngDoCheck (ng_for_of.ts:220)
    at callHook (core.js:2525)
    at callHooks (core.js:2492)
    at executeCheckHooks (core.js:2424)
    at refreshView (core.js:9416)
    at refreshEmbeddedViews (core.js:10527)
    at refreshView (core.js:9431)
    at detectChangesInternal (core.js:10755)
    at ViewRef.detectChanges (core.js:22750)

core.js:6150 ERROR DOMException: Failed to execute 'insertBefore' on 'Node': The node before which the new node is to be inserted is not a child of this node.
    at DefaultDomRenderer2.insertBefore (http://localhost:8000/vendor.js:124979:16)
    at nativeInsertBefore (http://localhost:8000/vendor.js:91073:14)
    at applyToElementOrContainer (http://localhost:8000/vendor.js:90504:7)
    at applyNodes (http://localhost:8000/vendor.js:91389:11)
    at applyNodes (http://localhost:8000/vendor.js:91366:13)
    at applyView (http://localhost:8000/vendor.js:91398:3)
    at addViewToContainer (http://localhost:8000/vendor.js:90596:3)
    at ViewContainerRef.insert (http://localhost:8000/vendor.js:109890:9)
    at ViewContainerRef.createEmbeddedView (http://localhost:8000/vendor.js:109827:12)
    at http://localhost:8000/vendor.js:140230:45

ERROR TypeError: Cannot read property 'context' of null
    at NgForOf._applyChanges (ng_for_of.ts:255)
    at NgForOf.ngDoCheck (ng_for_of.ts:220)
    at callHook (core.js:2525)
    at callHooks (core.js:2492)
    at executeCheckHooks (core.js:2424)
    at refreshView (core.js:9416)
    at refreshEmbeddedViews (core.js:10527)
    at refreshView (core.js:9431)
    at detectChangesInternal (core.js:10755)
    at ViewRef.detectChanges (core.js:22750)		
```

## Environment

* OS
```
os: Microsoft Windows 10 Pro
text editor : Microsoft VS Code 1.53.0
node : 14.15.4
```

* package.json
```json
{
  "name": "angular-app",
  "version": "0.0.0",
  "scripts": {
    "ng": "ng",
    "start": "ng serve",
    "build": "ng build",
    "lint": "ng lint"
  },
  "private": true,
  "dependencies": {
    "@angular/animations": "~11.2.0",
    "@angular/common": "~11.2.0",
    "@angular/compiler": "~11.2.0",
    "@angular/core": "~11.2.0",
    "@angular/forms": "~11.2.0",
    "@angular/platform-browser": "~11.2.0",
    "@angular/platform-browser-dynamic": "~11.2.0",
    "@angular/router": "~11.2.0",
    "@deck.gl/core": "^8.4.1",
    "@deck.gl/google-maps": "^8.4.1",
    "@deck.gl/layers": "^8.4.1",
    "ag-grid-angular": "^25.0.1",
    "ag-grid-community": "^25.0.1",
    "angular-hammer": "^2.2.0",
    "rxjs": "~6.6.0",
    "socket.io": "^2.4.1",
    "tslib": "^2.1.0",
    "zone.js": "~0.10.2"
  },
  "devDependencies": {
    "@angular-devkit/build-angular": "~0.1102.0",
    "@angular/cli": "~11.2.0",
    "@angular/compiler-cli": "~11.2.0",
    "@types/node": "^12.19.16",
    "codelyzer": "^6.0.0",
    "ts-node": "~8.3.0",
    "tslint": "~6.1.0",
    "typescript": "~4.0.2"
  }
}
```

**Comment by petebacondarwin** [comment]
@MichaelOdumosu57 - I am sorry that you are frustrated by the errors you are getting. I suspect that you are manipulating the DOM elements directly(?) but it is not possible to tell without seeing the code that you have written. Please can you provide a runnable example of this problem that we can look at to help diagnose the issue here.

**Comment by MichaelOdumosu57** [comment]
Sure I will be going to bed in my timezone, I will try to write a mininal repoduction
However the between-the-lines-issues with minimal reproduction.

It always works fine, but when its time to scale, the issues arise
a preview of the invloved code


### component.html
```html
<ng-container *ngFor = 'let aa of a.quantity[1];let bb = index;' >
	<ng-template *ngIf= "aa ===null else elseBlock1">

	</ng-template>
	... more elements
    <ng-template #elseBlock7  >
		<a
			appNest [nest] = "ryber.appAvailble( a.extras[1][bb], 'appNest')"
			appDeltaNode [deltaNode] = "ryber.appAvailble( a.extras[1][bb], 'appDeltaNode')"
			appLatch [latch] = "ryber.appAvailble( a.extras[1][bb], 'appLatch')"
            #myVal
            *ngIf= "a.bool[1][bb] ==='a'"
            [innerHTML] = 'a.text[1][bb].item'>
        </a>
    </ng-template>
<ng-container>
```


### remove button directive.ts
```ts
rUD({
	symbol:y,
	type:"remove",
	co
})

function rUD(devObj)=>{
	// where symbol is unique
	let {symbol,type,co} = devObj
	if(type === "remove"){
		let symbolIndex =  		a.quantity[1].indexOf(symbol)

		a.quantity[1][symbolIndex] = null
		//BTW THIS IS WHERE THE ERROR HAPPENS
		
		//  EXEPCTED:element leaves DOM and proceeds to remove element in dropdown createion

		// Actual : angular try to place a comment in place of the removed element however thinks  the parent is still the component (formCO0),  and is dropdown container is still a direct child, meanwhile I used this.renderer2.appendChild, to move the dropdown target into the container in the first place


		// if we splice out the index the element the directives above will transfer to the once before it to fill the void, we dont want that so we make a void
	}
}
```


### latch directive
```ts
ngOnDestroy(){
	// obviously i pulled it from the component.ts as well as change.detector
	if(this.feature.type === "dropdown"){


		let setupToGetValue = @ViewChildren(#myVal)
		setupToGetValue.changes
		.pipe(
			first(),
		)
		.subscribe({
			next:(result:any)=>{
				zSymbols
				.forEach((x:any,i)=>{
					rUD({
						symbol:x,
						type:"remove",
						co
					})
				})
				this.ref.detectChanges()
			},
		})
	}
}
```

**Comment by MichaelOdumosu57** [comment]
Greetings I have been able to make a minified reproduction of the issue, this certainly takes the problem in the gif and makes it standalone 
[reproduction.zip](https://github.com/angular/angular/files/5979611/reproduction.zip)

## Instructions
* run
```sh
npx ng serve -c=play
```
* dropdowns are in the openened state so you can see that the app sucessfully removes dropdowns on its own and its not the error of the end-developer
* in the angular app you will see a dropdown nested in a yellow flexbox container (div) and anther component below with a dropdown seemingly top-level in the DOM
* open the browser devTools, pay attention to the console, it will guide you on how the directives come together to achieve the desired effect
* the add and remove button only duplicate the dropdown that belong to the same component as theirselves
* play with the second component and observe the console.log 
	* see how there are no errors and the dropdown comes and goes as instructed

* clear the console
* play with the first component add,then remove as desired
	* observe the error on remove, even put a breakpoint, you will find that the error occurs on 
```js
parent.insertBefore(newChild,refChild)
```
* where parent is the component element, newChild is a #comment node and refChild is the container of the dropdown, which is not a direct child of the componenet element

**Comment by petebacondarwin** [comment]
The problem occurs at this line: https://github.com/angular/angular/commit/44150ecaccb30da5cc7cac71e7e46d04e9d4800d#diff-f2bb60ef38f35f7d41b0ac0868cc4267738c5e4c78e044336aec52d86a6e2d29R855

Previously if the template was inline (or indirect) the `templateUrl` was `""`, which is arguably wrong. But didn't break things because we ended up with a new source file in the compilation that contained the string of the template but had no URL.

After the change above the URL is now (arguably) correctly set as `template.resolvedTemplateUrl` but the contents of that file is (incorrectly) only the inline template string and not the whole source file that contained the original component source.

A simple fix tor reverse this regression would be to set this templateUrl value to `""` if the template is inline (indirect).

A better fix might be to actually follow the resolution of the indirect expression and then pass a proper `templateRange` to the template parser so that parsed AST nodes point to the actual resolved string. But I am not sure if this is really possible, since we cannot necessarily guarantee that the indirect expression was not computed somehow from numerous other expressions, which would require significantly more effort to handle in the template parser.

**Comment by MichaelOdumosu57** [comment]
You must have been looking at template.component.ts, which is not being used at all in the application. you were to look at form/form.component.ts and see that the templateUrl was
```ts
@Component({
    selector: 'app-form',
    templateUrl: '../template.component.html',
    changeDetection: ChangeDetectionStrategy.OnPush
})
```
referring to  the actual html template for the component(and the whole app).
Are you saying that each component has its own deferred/unique html. There is nothing inline concerning the html template. 

I am not understanding the context of the solution well, is this referring to 
* previous and current commits on @angular/core 
* a modifiation or automatic inlining of template.component.html
* the movement of the element meant movement of it's respective template string but for one reason or another (and possible reason that when I remove an element its replace by an empty ng-template) decided to disregard parsing when the element was moved into a sibling according to template.component.html. Because according to that template component all elements start out as siblings one of another under the component element

you seem to mention regression, which means there was an update made some  point in time to break the very feature im trying to implement, it would stand to reason renderer2 would rend out those regressive bugs.

My conclusion (correct me if I am wrong). Is that there is nothing inline concerning ,ts and html, there is plenty of two-way binding and inline css. I feel that there is more to ng-container and ng-template that meets the eye and the way that I am using ng-template to remove elements by providing an empty one with the *ngIF asking if the value is null like so
```html
		<ng-template *ngIf= "aa ===null else elseBlock1">

		</ng-template>
```
would stand to confuse the template parser because in html this is an element but not quite for angular, however its not nothing and angular is trying to do something with it. 
When elements are dynamic removed in angular it seems a comment takes its place, however when an element is moved around in the DOM its not reflected in this angular tree which still feels in this case the target is a direct child of the component 
The template parser seems not smart enough to deal with this kind of situation however I removed the very html snippnet and the same issue arises.

What resuorces are availble to learn about the template Parser, I better feel that this should be fixed, because if its circumstances for a simple case of elements leaving and entering the DOM, the intermediate cannot be expected to go to such lengths to interfere

**Comment by petebacondarwin** [comment]
Sorry @MichaelOdumosu57 - I posted this explanation to the wrong issue!! I'll take a look at this issue tonight or tomorrow.

**Comment by MichaelOdumosu57** [comment]
Much relief and appreciation and many thanks. Angular is 1000% better than React, if this were React my computer would catch fire. Sooner than later Angular will take I believe that

**Comment by petebacondarwin** [comment]
@MichaelOdumosu57 - I started to look at your reproduction. It is still hugely complicated and contains lots of stuff that I am sure are not relevant to this issue. To speed up resolution of your issue it is vital that you provide a "minimal" reproduction. Otherwise we have to waste a lot of time digging through all the extra code.

**Comment by petebacondarwin** [comment]
Without being able to go into any details I see that you are manually modifying the DOM outside of Angular (i.e using `renderer2` and `nativeElement`. I get the feeling that you basically fighting against how Angular works rather than working with it. There should be very few scenarios (almost none) where you need to do this much direct DOM manipulation.

Therefore it is not surprising that the Angular runtime gets confused when it is trying to do its job and finds that the DOM is not as it expected.

As I said above, it is almost impossible to identify if there is actually a bug in Angular or just a bug in the way you are using Angular from this very complex example.

If you believe that there is a bug in the framework, please can you cut your example down to that absolute minimal reproduction, that contains nothing else - no external libraries, no HTTP, ideally no Observable manipulation, etc.

**Comment by MichaelOdumosu57** [comment]
Greetings,
I have done further reductions, removed HTTPLibraryModule, and left the operations important to the proper formatting ,regristering and managing of the elements necessary for the minification. 



The application is built to be feature, and data management friendy, (because formatting is such an issue in browsers(flexbox and css grid)), here we have a scalable system, where as many features can come onto the element. yet the application does not require css nor css classes or id's to properly format the UI. With that said I hope this is mininal enough "external libraries, no HTTP, ideally no Observable manipulation" .

[reproduction (2).zip](https://github.com/angular/angular/files/5987363/reproduction.2.zip)

In conclusion I think there is a bug in Angular that we'll find if I do another minification in that case throwing out the application logic and just doing a barebones custom dropdown duplicating/nesting and trying to remove it. However the bigger issue is that there isn't an intended way in using renderer2, ng serve, lifecycleHooks, 

mabye there a bug
```ts
if(IsDefined === undefined){
     //code that runs sucessfully
}
```
but aren't services used as application logic, we used it as central for form control and providing metadata to the application on how to classify the component and elements it sees in the DOM
but aren't directives used to extend an element, and we use it button get directives to indicate they are used for duplication, we use it on element to make them a parent of another element
so now the exceptions to the rule that were coming across, are they bugs or  I am just doing things the wrong way

 concerning obserable manipulation, angular should not be affected when i say ".pipe(first()), .pipe(last()), ", if the only thing I do subscription  is ```ts renderer2.setStyle(element,"color","green")```. If not I will just have to literally make the dropdown standalone, duplicate it , nest the target in the container with renderer2, try to remove it  and get the same error and if you feel the minification done here  was not enough I will go to that length, but then again, would I use renderer2 or write out html, with 2-way binding to create the dropdown. The issue is with renderer2

concerning renderer2.
was it not in the docs that said, renderer2 is the preferred way of DOM manipulation, if your's was the case the docs should deprecate it or at least say don't use it. 
verbatim in the docs "Use a custom renderer to bypass Angular's templating and make custom UI changes that can't be expressed declaratively.", like repeating an element x amnt of times  see because I am not modifying renderer2 internally, so now renderer2 does something, bypass Angular's templating 
nothing said now I cant go back  once I use renderer2, 
nothing said @ViewChildren will have an issue with renderer2,
nothing said you cant use renderer2 in services, 

In the docs it seems like renderer2 is just a normal part of angular but really (as with every product from Google), its powerful but its only intended for use the way the creators designed it,(intended is never mentioned in the documentation of Google products)
 
We use renderer2 because like the dropdown element we can see were not going to make a template string combination for every possible parent child relationship a developer may use. <div><h1><div> , <div><h2></div> ... . We both agree that it be the pinnacle of failure for a company, to write out something that you can repeat.

Concerning Angular and the learning transparency 


its not a component its really a view
it 's not *ngFor its a structural directive, ngForOf
@HostListener is an observable but its really not, you don't have to unsubscribe from it
ng build is the production step, no its not its an architect name, which can be named anything
QueryList not a synchronous ArrayLike<ElementRef>, its an object you need to subscribe to  QueryList.changes and use like so
...
the notion we have to tell the public "its something other than what it is" no, tell me what it is, I'm grateful I learned Angular the way I did, but Angular's true face, doesn't even look like Angular. The community will be fine if it learned what Angular was at face value

**Comment by petebacondarwin** [comment]
@MichaelOdumosu57 - I appreciate that you are frustrated. I want to help find if there is a problem in Angular, so that we can fix it. I feel there are two issues here:

1. You are getting an unexpected error that may be a bug in Angular.
2. You feel that there is not enough guidance around using the `Renderer2` service in Angular.

---

Regarding the first one. The fastest way to a resolution of this is to provide a barebones reproduction as you accept in this comment:

> In conclusion I think there is a bug in the way that I am using Angular we'll find if I do another minification in that case throwing out the application logic and just doing a barebones custom dropdown duplicating/nesting and trying to remove it.

That is the most likely way to get help. There simply is not time to dig through hundreds of lines of code to identify what might be causing the problem. Moreover, sometimes when cutting down your example to provide the reproduction, people find that there is something they have done which causes the error and that there is not a bug.

Take a look at @mhevery's recent blog post about how to file effective issues: https://blog.angular.io/how-to-file-an-issue-715391a093d2. In particular:

> If example code is a part of the steps then it isn’t helpful to dump your existing codebase into the issue. It’s better to spend some time to whittle down the example until nothing more can be removed. The less code in reproduction the better chance that the issue can be identified quickly.

---

Regarding the second one, the "Angular Way" is to try to be declarative as much as possible. Perhaps we need to be more clear the in the docs about this. One should try as best as possible to avoid manipulating the DOM directly. Even if declarative template approaches are not possible. Even complex structural directives like `NgForOF` do not use the renderer directly. 

The `Renderer2` interface is provided for unusual edge cases that just cannot be done in a declarative manner or by using things like view containers and template refs. Note that the docs, as you quoted say:

> Use a custom renderer to bypass Angular's templating and make custom UI changes **that can't be expressed declaratively**.

The bit about "that can't be expressed declaratively" is the key here.

As soon as you modify the DOM directly, then you must take full ownership of that part of the DOM and cannot expect Angular mechanisms like listeners and view queries to work as expected. `Renderer2` is a kind of foot-gun that we would rather not expose, since it allows people to do things the non-Angular way, but is sometimes necessary for a narrow set of use cases.

---

I'll try to take another look at your reproduction, but I immediately see that there is still a service (`RyberService`) that uses the `Renderer2` but contains over 700 lines of code. This just adds too much overhead to the effort of someone who does not know your code-base to search through and identify what is Angular's fault and what is not.

**Comment by petebacondarwin** [comment]
I tried to look through the provided code again. It is super complicated. All I can say is that it appears that the items you are adding to the nested container are actually being placed at the top level of the DOM below the form component, rather than within the nested container. I think this is related to why there is only a problem when the items are expected to live in a nested container, compared to directly under the form component. At this stage, the code is simply too complex for me to spend any further time debugging. If you would like me to look at it again, please remove absolutely everything that is not necessary to reproduce the error.

**Comment by MichaelOdumosu57** [comment]
Hey how are you 
as I typed I wondered if I was coming off a bit strong. I may have come down harsh but its never out of frustration, Angular was made to defeat the hideous chaos that is web development and javascript.
I am always in support of Angular, its just the way that its taught
The things were taught have no place in Angular and even though it has a bootstrap feel, the bootstrap turns into "can I configure this? yes I can, by the next statement",
Things we're not taught are the things were using in Angular but they are not being called by their true name.

Our team knows Angular is the solution and our team just wants better for Angular that's all, We know the Angular team works hard with literally the weight of the world on their shoulders. I want to let you know I admire the work and support Angular as it becomes 1st place in the software industry

**Comment by petebacondarwin** [comment]
@MichaelOdumosu57 - don't worry. I know how it feels when I am using a tool that I don't own and I am not getting the result I want. We do want to help but you can make it much easier for us to do so if your issues contain succinct and simple reproductions.

**Comment by petebacondarwin** [comment]
> Hey im mike's coworker, I read the issue and wanted to add that the NestDirective is the only class using renderer2 to only place nest element one in another in the DOM, the renderer2 in the RyberService, was only used to add external 3rd party scripts. we never used renderer2 to remove DOM elements, in removing elements we set the index of the array in the template html to null.

Hi Mike's co-worker. If the `RyberService` (and other directives and services) are not needed to reproduce this issue, then they should not be part of the example you provide. It just adds noise and confusion to the problem at hand.

**Comment by alxhub** [comment]
I'm going to close this issue, as there hasn't been an update in over a year and Angular has changed substantially since then. The last reproduction is not a simple demonstration of the issue but a complex application with a lot of unnecessary code, making it hard for us to debug. If you're still encountering this problem, feel free to open a new issue, and it would be very helpful if you put together a reproduction of the problem with no unnecessary code or application structure. Often issues like this are reproducible with 1-2 components or directives.
