### ISSUE TITLE
API docs: there's no Optional, Self and SkipSelf decorators

### ISSUE THREAD

**Issue by AlexElin** [angular/angular#40851]
# 📚 Docs or angular.io bug report

### Description
[API docs for @angular/core](https://angular.io/api/core#decorators) don't contain descriptions for Optional, Self and SkipSelf decorators

### What's the affected URL?**
https://angular.io/api/core#decorators

### Expected vs Actual Behavior**
**Actual**: see description section above
**Expected**: there're descriptions for Optional, Self and SkipSelf decorators

## 📷Screenshot
![no_self_optional](https://user-images.githubusercontent.com/13061803/107925241-37a7a800-6f85-11eb-840c-9515f5faedb1.jpg)

**Comment by destus90** [comment]
Those decorators are presented in v10 API docs
https://v10.angular.io/api/core/Optional
https://v10.angular.io/api/core/Self
Not sure why this is dropped now.

**Comment by petebacondarwin** [comment]
`Optional` etc are documented but it appears that their "doc-type" has changed from `decorator` to `class`. I'll look into it.

**Comment by petebacondarwin** [comment]
OK, so I believe this commit - https://github.com/angular/angular/commit/6cff877f4f48cfe8460b0262d04ea333b79dd56a - is what broke the doc-gen. Previously the doc-gen identified that a decorator by the call to `makeParamDecorator()` but after this commit, this function call is wrapped in another call to `attachInjectorFlag()`. See https://github.com/angular/angular/blame/master/packages/core/src/di/metadata.ts#L108.

The fix is to update the dgeni processor where decorators are identified. See https://github.com/angular/angular/blob/38084164796d02f70b8dba1f770c4b22f8fbb1c6/aio/tools/transforms/angular-api-package/processors/mergeDecoratorDocs.js#L56
