### ISSUE TITLE
Ability to provide IANA time zone for date formatting

### ISSUE THREAD

**Issue by dimakuba** [angular/angular#40865]
# 🚀 feature request

### Description
Ability to provide [IANA](https://en.wikipedia.org/wiki/Tz_database) time zone for date formatting.

### Describe the solution you'd like

before:
```
const date = new Date();
const format = 'short';
const locale = 'tr';
const timezone = '+3'; // offset from GMT

formatDate(date, format, locale, timezone);
```

after:
```
const date = new Date();
const format = 'short';
const locale = 'tr';
const timezone = 'Europe/Istanbul'; // IANA time zone

formatDate(date, format, locale, timezone);
```
For now it's possible to provide time zone offset from GMT (such as `'+0430'`), but would be great to have an option to provide IANA time zone with `Intl.DateTimeFormat` instance.

**Comment by petebacondarwin** [comment]
I think that this is fairly easily achieved at the application level.

Here is a demo of how one could do this: https://stackblitz.com/edit/angular-ivy-qruv7h?devtoolsheight=33&file=src/app/app.component.ts This demo uses an internal copy of the `tease` library, which can be found on npm. I had to inline it because there were some issues with using it in Stackblitz. But I believe that it would work fine in a normal project.

Adding this in the Angular framework is possible, and we could make it tree-shakable by making a similar free-standing function to return the actual offset. But making it work without such a function would require some complexity such as registering the timezone data as a side-effectful import. This would make it less easy to understand by developers. In any case, there would be additional tooling required on our side to keep this list up to date.

Since it is a fairly easy thing to provide in an application I do not think that we will add this to the framework.

**Comment by dimakuba** [comment]
> I think that this is fairly easily achieved at the application level.
> 
> Here is a demo of how one could do this: https://stackblitz.com/edit/angular-ivy-qruv7h?devtoolsheight=33&file=src/app/app.component.ts This demo uses an internal copy of the `tease` library, which can be found on npm. I had to inline it because there were some issues with using it in Stackblitz. But I believe that it would work fine in a normal project.
> 
> Adding this in the Angular framework is possible, and we could make it tree-shakable by making a similar free-standing function to return the actual offset. But making it work without such a function would require some complexity such as registering the timezone data as a side-effectful import. This would make it less easy to understand by developers. In any case, there would be additional tooling required on our side to keep this list up to date.
> 
> Since it is a fairly easy thing to provide in an application I do not think that we will add this to the framework.

Thanks for demo. `tease` is awesome, but would be great to have it outside of the box :) besides it can be achieved with native api.

**Comment by petebacondarwin** [comment]
Could you provide a stackblitz version of my demo using native APIs?

**Comment by dimakuba** [comment]
https://stackblitz.com/edit/angular-ivy-g7emjo?file=src/app/app.component.ts

**Comment by petebacondarwin** [comment]
Nice! I see that it is possible (if a little ugly) in modern browsers. But unfortunately, IE11 which we still must support does not support IANA timezone names: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date/toLocaleString#browser_compatibility

So we would still have to polyfill that. I think someone publishing a small library would be a good way to go to provide this.
