### ISSUE TITLE
Show warning/error if NgModel.name is not unique in form

### ISSUE THREAD

**Issue by thesam** [angular/angular#40960]
# 🚀 feature request

### Relevant Package

 This feature request is for @angular/forms.

### Description
The "name" of an NgModel in an NgForm must be unique, and this is explained in the Angular documentation. However, if the name is NOT unique, Angular will not complain and simply use one (the last one?) of the NgModels, displaying the same value to the user everywhere even if there are multiple NgModels with different values.

For example: https://stackblitz.com/edit/angular-ivy-lichgx?file=src/app/app.component.html

This has been a problem for us when we create forms dynamically and must take great care to make sure all names are unique.

### Describe the solution you'd like
It would be very helpful if Angular would show a warning or throw an error/exception if "name" is not unique within a form. 

For example: If "name" is missing, TemplateDrivenErrors.missingNameException() shows a helpful Error. It would be great if there was an TemplateDrivenErrors.nameNotUniqueException().

### Describe alternatives you've considered
Our current workaround is to generate globally unique names for all our NgModels, but we must remember to use them everytime we add a new NgModel.

**Comment by indraraj26** [comment]
I think work around that you have proposed it needs to be change little bit.
Our current workaround is to generate <strike>globally</strike> component  unique names for all our NgModels, but we must remember to use them everytime we add a new NgModel.

I can have same name in other components too.

**Comment by AndrewKushnir** [comment]
@thesam thanks for creating this feature request.

There are situations when having multiple `ngModel`s with the same name is needed, for example with radio buttons ([see this example](https://stackblitz.com/edit/angular-ivy-wvck4p?file=src%2Fapp%2Fapp.component.html)). Since the use-case might depend on input type (and custom components), we can not put it to the `NgModel` class level to make it generic for all cases. Closing this ticket since the current behavior looks correct.

Thank you.
