### ISSUE TITLE
add javascript support to angular components

### ISSUE THREAD

**Issue by talley** [angular/angular#40973]
Please add JavaScript support to angular components
For example if i have a user component in my project it will be nice to have these structures

user.component.css
user.component.html
user.component.js ---  feature request
user.component.spec.ts 

Thank You
Talley

**Comment by SimonSimCity** [comment]
Tell us about your motivation for this feature request.

**Comment by RyannGalea** [comment]
Javascript is supported in your .ts files.

**Comment by itea-dev** [comment]
@talley You can change the file extensions of your Javascript files from **.js** to **.ts**.

Typescript is an extension of Javascript. All Javascript code is valid Typescript code.

**Comment by petebacondarwin** [comment]
It is actually just about feasible now if you handcraft `__decorator()` calls onto your JS classes that provide the necessary metadata - although this also requires the `@angular/compiler` to be loaded at runtime in the browser to process them.

But vanilla JavaScript support is not a direction we are looking to take Angular, so this use case is not recommended and barely supported (if at all).

Closing since the original reporter has not responded with any further clarification; and as it stands this is not something we are going to increase support for.

@talley - if we misunderstood what you were requesting, please open a new issue with a concrete example of how such a feature would work.
