### ISSUE TITLE
ngcc does not expand * when computing base-paths

### ISSUE THREAD

**Issue by sviat9440** [angular/angular#41014]
# 🐞 bug report

### Affected Package

`@angular/compiler-cli`

### Is this a regression?

Yes (it works fine on angular v9)

### Description

Reopening: #40357, #40352
https://github.com/angular/angular/issues/40926#issuecomment-786653555

@petebacondarwin
What version of @angular/compiler-cli fixes this (#40376)?

![image](https://user-images.githubusercontent.com/13107421/109312355-0322ce80-7858-11eb-9ba0-90f351bbcc83.png)

## 🔬 Minimal Reproduction
https://github.com/sviat9440/ivy-ngcc-bug-reproduce

## 🔥 Exception or Error

```
Error: Unexpected value 'NumberFormatterTestingPipeModule' imported by the module 'DynamicTestModule'. Please add an @NgModule annotation.
```

## 🌍  Your Environment

**Angular Version:**

Angular CLI: 11.2.2
Node: 12.16.3
OS: win32 x64

Angular: 11.2.3
... animations, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router
Ivy Workspace: Yes

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1102.2 (cli-only)
@angular-devkit/build-angular   0.1102.2
@angular-devkit/core            11.2.2 (cli-only)
@angular-devkit/schematics      11.2.2
@angular/cli                    11.2.2
@schematics/angular             11.2.2
@schematics/update              0.1102.2
ng-packagr                      11.2.4
rxjs                            6.6.3
typescript                      4.0.7

**Comment by petebacondarwin** [comment]
Please can you provide a reproduction of the error that we can investigate.

**Comment by sviat9440** [comment]
@petebacondarwin okay, I attached a repository

**Comment by petebacondarwin** [comment]
Thanks! I'll take a look

**Comment by petebacondarwin** [comment]
@sviat9440 - thank you for providing the reproduction. This allowed me to quickly diagnose the problem.

Running `ngcc` in debug mode gives us an early indication:

```
Debug: The basePath "/Users/pete/dev/angular/tmp/ngcc-issue-41014/dist/ui-" computed from baseUrl "/Users/pete/dev/angular/tmp/ngcc-issue-41014" and path mapping "dist/ui-*" does not exist in the file-system.
It will not be scanned for entry-points.
```

A bit of background:

* When processing "local" libraries (e.g. ones that are build into `dist` rather than `node_modules`) ngcc must be able to compute the "package path" (e.g. `dist/ui-pipes`) from the entry-point path (e.g. `dist/ui-pipes/testing`).
* It does this by traversing up the tree to find the highest `package.json` before hitting a "base path".
* A standard base bath is `node_modules` but since local libraries are not under this directory it needs to work out what the other base paths are.
* These other base paths are computed by reading the path-mappings in the `tsconfig.json` file.
* In this case `paths` contains `dist/ui-*`, but ngcc does not understand how to expand this to find "real" directories, so it ignores this path-mapping.
* Because it does not have any `dist` base paths, it fails to compute the package path for secondary entry points of local libraries (e.g. `ui-pipes/testing`) and so does no process this entry-point correctly.

A workaround for now is to enumerate the paths more fully. For example, I got it to work by changing it to:

```
        "paths": {
            "@front-polis/ui-count-to": [
                "dist/ui-count-to"
            ],
            "@front-polis/ui-pipes": [
                "dist/ui-pipes"
            ],
            "@front-polis/ui-pipes/testing": [
                "dist/ui-pipes/testing"
            ]
        }
```

This is not necessarily the best configuration, I'll leave that for you to work out.

But we should indeed attempt to fix this.

**Comment by sviat9440** [comment]
It really looks better this way. But I have more than 20 packages in the repository, which has at least two entry points. This will be a very large config...

**Comment by sviat9440** [comment]
@petebacondarwin I found another issue.
Modules inside typescript namespaces, also not compiled by `ngcc`.
I updated the example in the repository.

**Comment by petebacondarwin** [comment]
Please can you open a different issue for that, since it has a different root cause. It is easier to track the fixes separately.
