### ISSUE TITLE
Remove unmaintained projects from resources page

### ISSUE THREAD

**Issue by Airblader** [angular/angular#41030]
# 📚 Docs or angular.io bug report

### Description

The following resources listed are, as far as I can tell, unsupported and should be considered for removal. Resources listed on the Angular website get featured prominently and thus will be taken as direct recommendations.

1. Augury: Has not been updated since Jan 2020 and doesn't work with Ivy
2. UI-jar: Maintainer removed himself from the README, last commit before that is from 2019 and according to issues it doesn't work with at least Angular >= v9.

### What's the affected URL?**

https://angular.io/resources?category=development

**Comment by gkalpak** [comment]
I checked with @twerske ([internal discussion][1]) and she confirmed it sounds reasonable to remove Augury (esp. since it has also be removed from the `ng new` schematic: angular/angular-cli#20139).

Regarding UI-jar we should first try to reach out to the maintainer and confirm they do not intend to update it to support Ivy.

@Airblader, are these something you would be interested to take on?

[1]: https://angular-team.slack.com/archives/C18F9SF3L/p1614599093002800

**Comment by Airblader** [comment]
I've pinged the maintainer in the already open issue https://github.com/ui-jar/ui-jar/issues/80#issuecomment-791905432.

**Comment by Airblader** [comment]
As for PRing the actual changes I'll defer this to any willing contributors looking for an easy ticket to get involved.

**Comment by SagarPandita0** [comment]
Hello @Airblader, I am new to opensource and would love to contribute!

**Comment by Airblader** [comment]
@SagarPandita0 Great, feel free to take this to remove Augury. For UI-jar I guess we need to wait a little while still.

**Comment by gkalpak** [comment]
Since we haven't heard from the maintainer of `ui-jar` for a month (https://github.com/ui-jar/ui-jar/issues/80#issuecomment-791905432), I think we should remove it from resources. (They can always add it back when/if they make it compatible with the latest Angular version and Ivy.)

**Comment by SagarPandita0** [comment]
Hi @gkalpak ! I would love to take this up.

**Comment by gkalpak** [comment]
Feel free to take it, @SagarPandita0 🚀
