### ISSUE TITLE
Ivy ignored modules inside namespace

### ISSUE THREAD

**Issue by sviat9440** [angular/angular#41037]
# 🐞 bug report

### Affected Package

`@angular/compiler-cli`

### Is this a regression?

Yes, the previous version in which this bug was not present was: 9.1.12

### Description

Modules inside namespaces does not compiled by `ngcc`. So when i try to import this module, i see an error.

## 🔬 Minimal Reproduction

https://github.com/sviat9440/ivy-ngcc-bug-reproduce

## 🔥 Exception or Error
<pre><code>Error: Unexpected value 'TestModule' imported by the module 'DynamicTestModule'. Please add an @NgModule annotation.</code></pre>

## 🌍  Your Environment

**Angular Version:**
<pre><code>

Angular CLI: 11.2.2
Node: 12.16.3
OS: win32 x64

Angular: 11.2.3
... animations, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... platform-server, router
Ivy Workspace: Yes

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.901.12
@angular-devkit/build-angular   0.1102.2
@angular-devkit/core            9.1.12
@angular-devkit/schematics      11.2.2
@angular/cli                    11.2.2
@nguniversal/builders           9.1.1
@schematics/angular             11.2.2
@schematics/update              0.1102.2
ng-packagr                      11.2.4
rxjs                            6.6.3
typescript                      4.1.5
webpack                         4.44.1

</code></pre>

**Anything else relevant?**

I'm fixed this problem by declaring module outside namespace, and exporting inside.

**Comment by petebacondarwin** [comment]
Thanks @sviat9440.
Since this is a fairly rare use case, I have marked it as P4. But I will try to take a look at some point this week to work out how much effort it would be to fix it.

**Comment by petebacondarwin** [comment]
Discussing this with the rest of the compiler team. Wrapping components, etc, in a namespace has never been something that we officially supported and there are no test cases in the whole project for such a scenario. That it worked with View Engine was probably through luck as much as anything.

Trying to support this would involve a lot of work, and given how uncommon this use-case is, we don't expect to add support to it for Ivy. I'm afraid you will need to refactor this aspect of your codebase in order to upgrade to Ivy.

Closing as a "won't fix".
