### ISSUE TITLE
Stop doing a release every week

### ISSUE THREAD

**Issue by nbittich** [angular/angular#41084]
It's very annoying to follow your updates guys. can't you just do one release every month or every two weeks? I can't even see what has changed between minor releases.

**Comment by mlc-mlapis** [comment]
@nbittich It's not necessary to do it on your side. It's only your decision. I think that the rest of the Angular community appreciate a weekly period as a compromise to get the latest updates, test them and react as soon as possible. With a longer period, it would mean that many things would concentrate on one point. Remember that the whole process also works as the third level of acceptance in the real world, based on thousands and thousands of apps.

**Comment by nbittich** [comment]
> @nbittich It's not necessary to do it on your side. It's only your decision. I think that the rest of the Angular community appreciate a weekly period as a compromise to get the latest updates, test them and react as soon as possible. With a longer period, it would mean that many things would concentrate on one point. Remember that the whole process also works as the third level of acceptance in the real world, based on thousands and thousands of apps.

No I don't think so. It's not my decision. If I don't update as often as possible, it will be a much bigger pain in the future (I know that by experience with angular). Every time a new version is released, I have to make sure the other libraries I'm using are also updated and/or not broken. It happened to me that a minor release broke the ng build --prod because I was using an "old" version of typescript in my package.json! (under v4 if I remember, but still 3.X smth, it was like 1-2 months ago). 

I had to make a new release to fix the prod. It's always LOTS of time lost and LOTS of stress for nothing. Maybe it works for basic project, but it definitely doesn't work for something running in production. More stress, more work, no idea what it does, this is my feeling about the current situation.

**Comment by mlc-mlapis** [comment]
@nbittich Hmm, then I don't understand the difference if you do the same once a week or once two weeks. The Angular part is just one building block inside of the whole frame of how the NodeJS world works. You can accept it or not. We also even use the exact version for each package mentioned in `package.json` and manually increase them together with all tests, building phase, and runtime behavior check.

**Comment by nbittich** [comment]
nope, the NodeJs world doesn't work like that. Only in the angular world. 

I wish I could just switch to react or vue as the other folks does.

I wrote an app written in react 6 months ago. Version I'm using is 17.0.1. Didn't have to update since then. It's amazing how stable they are.

**Comment by Airblader** [comment]
React also has hundreds of open issues. If you consider not releasing stable, just don't update Angular ever again and it's as stable as can be.

Also, which is it: you want to update often to keep updated small, or you want releases to be more rare and bigger?

Seriously, though, releasing often is an industry standard best practice and it isn't going to change because you get a few too many emails. You can watch releases in a number of different ways, you don't need to subscribe to the emails.

**Comment by mgechev** [comment]
@nbittich as other folks in the thread mentioned, you don't have to keep up to date with the individual patch releases if this introduces extra burden to your process. I'd still recommend keeping an eye on the changelog to make sure you don't miss a security fix by accident, but such changes are usually rare. We're working on making the update process as straightforward as possible with tools such as `ng update` and have predictable releases that people can easily follow.

In my personal projects, I'm using tools such as dependabot or renovatebot to automatically update my dependencies with a PR when there's a new version available. This would be my recommendation because you get the best form both worlds - you're always on the most performant and secure version without having to worry about manual updates or following changelogs. Combining this experience with `ng update` across minor/major releases should make your process as smooth as possible.
