### ISSUE TITLE
Integers parsed as strings in HTTP Post/Put body

### ISSUE THREAD

**Issue by HaydenBycroft** [angular/angular#41109]
# 🐞 bug report

### Affected Package
The issue is caused by @angular

### Is this a regression?
Unsure

### Description
When trying to send integer values to a .net core web API, Angular **_stupidly_** and quite randomly converts numbers to a string and therefore causing intermittent and unstable exceptions at the API's controller level and this is extremely unacceptable for any production ready product.

## 🔬 Minimal Reproduction
- Create a http request and add a json object to the body with some KeyValuePairs using NUMBERS for the values.
- Angular will convert the numbers to strings and cause exceptions for any service expecting an integer.

## 🔥 Exception or Error
<pre><code>

</code></pre>
![image](https://user-images.githubusercontent.com/19830824/110260759-4409a880-7ff9-11eb-8c6a-dacde3d70d1e.png)
![image](https://user-images.githubusercontent.com/19830824/110260785-5e438680-7ff9-11eb-9af5-325c8fb70673.png)

## 🌍  Your Environment

**Angular Version:**
<pre><code>

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1100.7
@angular-devkit/build-angular   0.1100.7
@angular-devkit/core            11.0.7
@angular-devkit/schematics      11.2.2
@angular/cdk                    11.2.2
@angular/cli                    11.2.2
@angular/material               11.2.2
@schematics/angular             11.2.2
@schematics/update              0.1102.2
rxjs                            6.6.6
typescript                      4.1.5
</code></pre>

**Anything else relevant?**

**Comment by jnizet** [comment]
Angular relies on the browser-provided `JSON.stringify()` function to transform the object that your code provides into JSON. So, there are 2 possibilities

- all applications on earth running in the same browser as yours are broken due to a browser bug, but you're the first to notice
- your own code is passing a string where a number is expected

I would bet on the second one. 
It's always tempting to think that a bug is caused by external code rather than ours. Been there, done that. But my experience has alwo shown that it's almost never the battle-tested, used by billions, library code that has a problem, but rather the code I wrote. 

If you really think it's an Angular or browser bug, you shoud provide a minimal example reproducing the issue.

**Comment by petebacondarwin** [comment]
Indeed here is an example of Angular behaving expectedly: https://stackblitz.com/edit/angular-ivy-vpjsqu?file=src%2Fapp%2Fapp.component.ts

See that the request body contains a number not a string...

![Screenshot 2021-03-08 at 08 00 06](https://user-images.githubusercontent.com/15655/110291876-50cfd180-7fe4-11eb-9cfe-f289468dac01.png)
