### ISSUE TITLE
Wrong display of negative values in currency pipe

### ISSUE THREAD

**Issue by ensnared** [angular/angular#41110]
# 🐞 bug report

### Affected Package
The issue is caused by package @angular/common

### Is this a regression?
Not as far as I know.

### Description
When formatting output in a template of a negative value using the currency pipe, the negative sign is placed in front of the symbol rather than in front of the digits.
With nb (Norwegian) locale, the currency pipe will display a negative value like this:
```−kr 1 000,00```

The correct way to display it is however like this:
``` kr −1 000,00```

This is locale specific, but it's not exclusive to Norwegian.

## 🔬 Minimal Reproduction
https://stackblitz.com/edit/angular-ivy-d41ezr

## 🔥 Exception or Error
None

## 🌍  Your Environment

**Angular Version:**
<pre><code>Angular CLI: 11.2.3
Node: 15.11.0
OS: linux x64

Angular: 11.2.4
... animations, common, compiler, compiler-cli, core, forms
... language-service, localize, platform-browser
... platform-browser-dynamic, router
Ivy Workspace: Yes

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1102.3
@angular-devkit/build-angular   0.1102.3
@angular-devkit/core            11.2.3
@angular-devkit/schematics      11.2.3
@angular/cdk                    11.2.3
@angular/cli                    11.2.3
@angular/google-maps            11.2.3
@angular/material               11.2.3
@schematics/angular             11.2.3
@schematics/update              0.1102.3
rxjs                            6.6.6
typescript                      4.1.5

</code></pre>

**Anything else relevant?**

**Comment by gkalpak** [comment]
Thx for reporting this. However, Angular uses the [Google Closure I18N library][1] to generate its own I18N files. This means that any changes to locales need to go through that library first (and Angular will get the update the next time that we import the library). So, if you want to propose a change, I suggest you open an issue or submit a patch to the I18N project directly.

For reference, you can see that neither the [`no` locale number format config][2] nor the [`nb` locale number format config][3] specify a negative currency pattern, which means that they fall back to the default behavior of prepending the positive currency pattern with the `MINUS_SIGN` symbol.

See the [`de_CH` locale number format config][4] for an example of a locale providing a negative currency pattern.

##
I am going to close this issue, since it is not directly actionable for us. If you open an issue or submit a patch to the Google Closure I18N library, feel free to post the link here for reference.

[1]: https://github.com/google/closure-library/tree/master/closure/goog/i18n
[2]: https://github.com/google/closure-library/blob/61eef0f7ac67618a504c976a0bdb4f124f7eaa86/closure/goog/i18n/numberformatsymbols.js#L2063
[3]: https://github.com/google/closure-library/blob/61eef0f7ac67618a504c976a0bdb4f124f7eaa86/closure/goog/i18n/numberformatsymbols.js#L1971
[4]: https://github.com/google/closure-library/blob/61eef0f7ac67618a504c976a0bdb4f124f7eaa86/closure/goog/i18n/numberformatsymbols.js#L623

**Comment by ensnared** [comment]
Thank you, I have posted an issue there.

Link: https://github.com/google/closure-library/issues/1124
