### ISSUE TITLE
iframe.name attribute is not visible within the iframe as window.name - only when it's bound to the iframe but not when hardcoded

### ISSUE THREAD

**Issue by AlfaJJ** [angular/angular#41114]
# 🐞 bug report

### Affected Package
Unknown.

### Is this a regression?
I don't know. Probably not.

### Description
When creating an `iframe` element within a component the `name` attribute is not being passed to the iframe when it's bound but not when it's hardcoded.
 
I've created simple example on stackblitz - a component with two iframes: 
```
<iframe name="hardcodedname" src="http://localhost:8001/alertname.html"></iframe>
<iframe [attr.name]="windowName" src="http://localhost:8001/alertname.html"></iframe>
```

Content of the alertname.html:
```
<html>
<body>
<script>
	setTimeout(() => {
		alert("Window.name: " + window.name);
	}, 1000);
</script>
</body>
</html>
```

Two alerts will be shown:
1. "Window name: hardcodedname"
2. "Window name:"

And that's the point of my problem. I wan't the name to be passed to the iframe.

## 🔬 Minimal Reproduction
Reproduced at the stackblitz:
https://stackblitz.com/edit/angular-ivy-c4v3py?file=src/app/app.component.html

## Angular Version
Version: 11.0.8. 
My original project is built on top of 5.2.3 and behavior is the same.

**Comment by Airblader** [comment]
A piece of very incomplete information: this might be browser-dependent, see for example https://bugzilla.mozilla.org/show_bug.cgi?id=161061 which also references a tweet indicating that this doesn't work in Chrome (or didn't anymore in 2013).

**Comment by AlfaJJ** [comment]
Didn't find this but I was feeling it's due to render/bind order. It that's the case - is it possible to insert the element with already bound attributes?
Should it be done via `innerHTML` or by manually inserting it using `createElement/appendChild`?

**Comment by gkalpak** [comment]
I am going to close this, since everything seems to work fine as far as Angular is concerned. The fact that an updated `name` attribute value is not reflected in the window's name is a browser behavior (for example, it works in Firefox but not in Chrome).

There is no way to insert the element with pre-bound attributes via an Angular template, so if you need to bind attributes before inserting the element into the DOM you have to directly manipulate the DOM (for example, using `innerHTML` or `appendChild()`. (FYI, you can grab the DOM element of the containing component by injecting `ElementRef` and using [ElementRef#nativeElement][1].)

[1]: https://angular.io/api/core/ElementRef#nativeElement
