### ISSUE TITLE
Angular should support all the official HTML Entities

### ISSUE THREAD

**Issue by patxbert** [angular/angular#41186]
# 🐞 bug report

### Affected Package
Unsure

### Is this a regression?
No

### Description
Angular should support all the official HTML Entities found at: https://html.spec.whatwg.org/multipage/named-characters.html#named-character-references

## 🔬 Minimal Reproduction
`<code>&lt;app-my-comp &lbrack;user&rbrack;="user""&gt;&lt;/app-my-comp&gt;</code>`
https://angular-ivy-fcccys.stackblitz.io

## 🔥 Exception or Error
<pre><code>
Error in src/app/app.component.html (1:23)
Unknown entity "lbrack" - use the "&#<decimal>;" or "&#x<hex>;" syntax
</code></pre>

## 🌍  Your Environment

**Angular Version:**
<pre><code>

     _                      _                 ____ _     ___
    / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
   / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
  / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
 /_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
                |___/
    

Angular CLI: 11.1.1
Node: 15.7.0
OS: win32 x64

Angular: 11.1.0
... animations, cdk, common, compiler, compiler-cli, core, forms
... localize, platform-browser, platform-browser-dynamic
... platform-server, router, service-worker
Ivy Workspace: Yes

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1101.1
@angular-devkit/build-angular   0.1101.1
@angular-devkit/core            11.1.1
@angular-devkit/schematics      11.1.1
@angular/cli                    11.1.1
@angular/pwa                    0.1101.1
@schematics/angular             11.1.1
@schematics/update              0.1101.1
rxjs                            6.6.3
typescript                      4.1.3
</code></pre>

**Anything else relevant?**

**Comment by jelbourn** [comment]
It looks like this is the relevant code location:
https://github.com/angular/angular/blob/66c27ffdfc0e4f0a37a375a453d368c8ef13e326/packages/compiler/src/ml_parser/tags.ts#L71

The comment here says that this list is intentionally not comprehensive. @alxhub what's your philosophy on which entities are captured here?

**Comment by patxbert** [comment]
I personally do not understand the reasons behind not allowing all named entities. If someone could explain it more than the comment in the code that @jelbourn linked, that would be fantastic.

**Comment by jelbourn** [comment]
I chatted with @alxhub about this and it's not clear to us why we have this validation in the first place rather than just passing the values through. @petebacondarwin mentioned that there is a small optimization where we can sometimes replace an encoding with the (smaller) unicode representation, but that shouldn't preclude using unknown encodings. 

@koto would you happen to know if there are any security reasons Angular should restrict the types of HTML entities users can specify?

**Comment by koto** [comment]
There should not be any security reasons to limit what HTML entities are allowed, I guess if you can't figure out why the code was added, it's good to remove it :)

**Comment by tplk** [comment]
> optimization where we can sometimes replace an encoding with the (smaller) unicode representation, but that shouldn't preclude using unknown encodings

I've been working on migrating our codebase from Pug to HTML templates and was surprised that Angular is able to parse templates containing html entities inside angular expressions, i.e.
```html
<p *ngIf="1 &gt; 0">this is a valid template</p>
```

Here's a [working stackblitz example](https://stackblitz.com/edit/angular-html-entity-inside-expression-uenwsg?devtoolsheight=33&file=src/app/app.component.html)

Is it possible that the mentioned optimisation causes this to work?

**Comment by petebacondarwin** [comment]
> Angular is able to parse templates containing html entities inside angular expressions

I believe this is actually a bug in our template parsing!

**Comment by crisbeto** [comment]
I've been looking into it and the reason why we have to map entities to unicode, instead of just passing them through, is because we render text using `document.createTextNode` or `element.textContent` which won't decode HTML entities. We could use `innerHTML` instead, but that'll have performance and security implications. I think that the best way forward would be to expand the mapping to cover all entities from the spec. I've submitted #42818 to add all the missing mappings.
