### ISSUE TITLE
injecting something into a service with type annotations

### ISSUE THREAD

**Issue by robianmcd** [angular/angular#4120]
I asked a question here (https://github.com/Microsoft/TypeScript/issues/4737) about how to get Typescript to include runtime type annotations (to be used for DI in Angular2) and I learned that it will only include them on classes that have decorators. This is fine for components as they will already have decorators but how should I inject something into a service?

Should I use @Inject to manually specify the dependencies or create some no-op decorator to trigger typescript's runtime types or is there some workaround for this?

Thanks

**Comment by robwormald** [comment]
@robianmcd the `@Injectable()` decoration works nicely for this. Same problem over in https://github.com/angular/angular/issues/2788, but in theory *any* decorator should work. I'm not super stoked on it as a solution though, it would be great to be able to opt-in in the TypeScript compiler ("--alwaysEmitDecoratorMetadata") or something.

**Comment by robianmcd** [comment]
@robwormald thanks for the info. I'll use the `@injectable()` annotation for now but I agree that it would be nice if Typescript could support this without the need of a class decorator. I reopened my Typescript issue to ask if they could support this.

**Comment by mprobst** [comment]
@robwormald: just my 2¢, but in Java Guice, injecting classes that do not have a `@Injectable` or (in Guice) `@Inject` annotation is deprecated, as it turned out to be a source of bugs, where classes would more or less accidentally be injected in some code.

E.g. you have some classes that gets mentioned in some other constructor. If the framework just happily comes along and instantiates the class, it might get a bunch of things wrong, in particular the object's lifetime (singleton, per request), or the class might not be designed to be injected at all. The resulting errors can be very hard to debug.

Whether a class can or should be constructed by injection should be determined by the class itself, not by the code using it. So I think this should be WAI.

**Comment by mhevery** [comment]
@mprobst `@Inject` and `@Injectable` are two very different things. One is saying I can be injected, the other is saying inject into me. We only have `@Injectable` in Angular.

We need to have some annotation so that TypeScript preserve the type information, we use `@Injectable` for that purpose.

Yes as https://github.com/angular/angular/issues/4120#issuecomment-139700784 suggest we could have TypeScript always generate the type information, but that would bloat the amount of code generated. So the annotation is a compromise.

**Comment by PascalPrecht** [comment]
@mhevery are we going to stick with @Injectable then, or do we want to introduce yet another one for this specific use case.

Either way, this needs to be documented in the DI guide
