### ISSUE TITLE
EventEmitter subscription is not called when it is fired in timeout on a component that has *ngFor with new objects

### ISSUE THREAD

**Issue by cronon** [angular/angular#41315]
# 🐞 bug report

### Affected Package

 The issue is caused by package @angular/core

### Description

 I have three components. AppComponent renders FieldComponent and passes there "items" property. Every time it passes a new array with new objects. FieldComponent renders ItemComponents with *ngFor. When user clicks on ItemComponent it emits an event inside timeout. But subscription inside FieldComponent is not called.

## 🔬 Minimal Reproduction

 https://stackblitz.com/edit/angular-bqlubz?file=src%2Fapp%2Fapp.component.ts

## 🌍  Your Environment

**Angular Version:**
<pre><code>
@angular-devkit/architect          0.901.12
@angular-devkit/build-angular      0.901.12
@angular-devkit/build-ng-packagr   0.901.12
@angular-devkit/build-optimizer    0.901.12
@angular-devkit/build-webpack      0.901.12
@angular-devkit/core               9.1.12
@angular-devkit/schematics         9.1.13
@angular/cli                       9.1.13
@ngtools/webpack                   9.1.12
@schematics/angular                9.1.13
@schematics/update                 0.901.13
ng-packagr                         9.1.5
rxjs                               6.5.5
typescript                         3.8.3
webpack                            4.42.0
</code></pre>
It also reproduces in stackblitz with angular 11

**Anything else relevant?**
I know that passing new objects each time is an antipattern. I'm writing a library and prefer my users to experience worse performance when they do that mistake instead of my library being broken with no clue what was wrong in their code

**Comment by PierreDemailly** [comment]
This is due to `setTimeout()`. If you remove them all it's working as expected.

**Comment by JoostK** [comment]
I'd say this is working as expected. The `setTimeout` is delaying the even until after the DOM has been rerendered, and because the object instances are not stable it will have torn down and recreated the DOM, thereby removing the listeners to the component that was destroyed. So the emitted event goes unnoticed, as the corresponding listener has been unsubscribed. The framework should be unsubscribing events when a component is destroyed as to avoid leaking subscriptions, and it can't possibly know that you continue to have a handle to the component after it's been destroyed. As an alternative, a service could be used to dispatch the events to.

Closing as working as expected, but feel free to continue the discussion below.

**Comment by cronon** [comment]
Thank you!
