### ISSUE TITLE
[BUG]: unobvious injection behavior - inject() must be called from an injection context

### ISSUE THREAD

**Issue by splincode** [angular/angular#41397]
# 🐞 bug report

### Affected Package

`@angular/core`

### Is this a regression?

No

### Description

When we used inject in component  that this doesn't work

```ts
import { Component, inject, Injectable } from '@angular/core';


@Injectable()
class A {}

@Injectable()
class B {}

@Component({
  selector: 'my-app',
  templateUrl: './app.component.html',
  styleUrls: [ './app.component.css' ],
  providers: [A, B]
})
export class AppComponent  {
   public a!: A;
   public b!: B;

   constructor() {
     this.a = inject(A);
     this.b = inject(B);
   }
}
```

![image](https://user-images.githubusercontent.com/12021443/113157570-aeea8000-9243-11eb-80df-6d2165aa2f09.png)

But if we use service

```ts
import { Component, inject, Injectable } from "@angular/core";

@Injectable()
class A {}

@Injectable()
class B {}

@Injectable()
class Etc {
  public a!: A;
  public b!: B;

  constructor() {
    this.a = inject(A);
    this.b = inject(B);
  }
}

@Component({
  selector: "my-app",
  templateUrl: "./app.component.html",
  styleUrls: ["./app.component.css"],
  providers: [A, B, Etc]
})
export class AppComponent {
  constructor(etc: Etc) {
    console.log(etc);
  }
}

```

this work

![image](https://user-images.githubusercontent.com/12021443/113158138-30daa900-9244-11eb-9da0-3f281c15a4e2.png)

@mhevery @petebacondarwin @JoostK why?

## 🔬 Minimal Reproduction

https://stackblitz.com/edit/inject-component?file=src%2Fapp%2Fapp.component.ts

## 🔥 Exception or Error
<pre><code>
inject() must be called from an injection context
</code></pre>

## 🌍  Your Environment

**Angular Version:**

latest

**Comment by splincode** [comment]
but https://stackblitz.com/edit/inject-component-qoovmk?file=src%2Fapp%2Fapp.component.ts

```
import {
  Component,
  inject,
  Injectable,
  VERSION,
  ɵɵdirectiveInject as directiveInject
} from "@angular/core";

@Injectable()
class A {}

@Injectable()
class B {}

@Component({
  selector: "my-app",
  templateUrl: "./app.component.html",
  styleUrls: ["./app.component.css"],
  providers: [A, B]
})
export class AppComponent {
  public a!: A;
  public b!: B;

  constructor() {
    this.a = directiveInject(A);
    this.b = directiveInject(B);
  }
}
```

working, why?

**Comment by flash-me** [comment]
Is there a reason for not using parameter properties?

The only difference that comes to my mind is that you don't have to pass them as args to the constructor. 
But `A` and `B` still need to be provided in both cases, anyway.

cheers
flash ⚡

**Comment by AndrewKushnir** [comment]
Hi @splincode,

The `inject` function that you refer to in the issue description is a part of testing API ([see here](https://angular.io/api/core/testing/inject#description) and also [function declaration here](https://github.com/angular/angular/blob/master/packages/core/testing/src/test_bed.ts#L683-L702)), which is not intended to be used in apps code directly. The `ɵɵinject` function is an internal API which retrieves tokens from DI in a context of the current injector ([see here](https://github.com/angular/angular/blob/master/packages/core/src/di/injector_compatibility.ts#L70-L89)), but since it's a private API, it's not recommended for use in apps code directly.

I believe in your scenario you may look into injecting an Injector and access tokens via `get` method, for example:

```
  import { Injector } from '@angular/core';

  // ...

  constructor(injector: Injector) {
    this.a = injector.get(A);
    this.b = injector.get(B);
  }
```

I will close this ticket for now, since there are no action items for the framework.

Thank you.
