### ISSUE TITLE
How to initialize values for different datatypes?

### ISSUE THREAD

**Issue by thirumanidev** [angular/angular#41446]
Hi,
This is my Angular & Typescript version.
![image](https://user-images.githubusercontent.com/55808656/113513224-39a1e680-9586-11eb-864d-d333cd94f6e5.png)

@ViewChildren("stakeRef") myValue: QueryList<ElementRef> = null;
If I use the above code an error occurs as below
Type 'null' is not assignable to type 'QueryList<ElementRef>'

How to initialize values for different datatypes?

**Comment by krilllind** [comment]
My guess is that you have the `strictNullChecks` option set to true which means that null is indeed not assignable to a property of type `QueryList`. Something marked with `@ViewChild(ren)` or `@ContentChild(ren)` does not need to be initialized to any value as it will be overwritten by Angular. Please see [this great comment](https://github.com/Microsoft/TypeScript/issues/8322#issuecomment-214928203) on what the `strictNullChecks` option is

**Comment by mukulkadel** [comment]
With `@ViewChildren` you don't have to initialize it with any value.

**Comment by thirumanidev** [comment]
Yes, I enabled strictNullChecks as true, I wish to continue my projects with strict mode.

![image](https://user-images.githubusercontent.com/55808656/113551350-1de42200-9612-11eb-94ba-d78ecda6f04f.png)
Please see my issue. FYI, I'm using @ViewChild, not @ViewChildren.

How to know what values should be initialized for different data types.

To make it clear, please let me show you some samples..

If we use array of int, we can initialize empty array like this
intArr: number = []; // Here no error, I know, what values I can use []

But for these kind of following property declarations & initializations, I do not know what values could I use it.
@ViewChild('contentModal1') myModal: ElementRef; // Here the error occurs(screenshot), I do not know what values can I use.

Could you point out how to fix it?

**Comment by thirumanidev** [comment]
FYI, I'm using ng-bootstrap and its Popup Modal. If I use <any> type instead of <ElementRef> the error doesn't occurs.

`@ViewChild('contentModal1') myModal: any;`

But if I try to access the variable, it says as undefined.
console.log(this.myModal); // undefined

**Comment by thirumanidev** [comment]
![image](https://user-images.githubusercontent.com/55808656/113553201-05c1d200-9615-11eb-9b95-298ceaece4ee.png)

Hi @mukulkadel 
Please check my screenshot, I'm getting the same error with @ViewChildren even I don't initialize values.

**Comment by destus90** [comment]
@thirumanidev 
read about non-null assertion operator in TypeScript. Something like 
`@ViewChild('contentModal1') myModal!: ElementRef;`

**Comment by mukulkadel** [comment]
`@ViewChild('contentModal1') myModal?: ElementRef;`

You can try by adding a '?' symbol before the colon sign. It'll let the compiler know it's nullable.

**Comment by thirumanidev** [comment]
So we can't initialize values for these types? Instead initialize we have to add these operators to define a property as non-nullable(!) or nullable(?).

FYI, the error is not appears now. but the template local variable couldn't access it still, I meant, it still gives undefined.

`console.log(this.myModal); // BUT, its result is undefined`

FYI, My html template is
<ng-template #contentModal1 let-modal let-c="close" let-d="dismiss">
 <div class="modal-header">
  <h1>My Header</h1>
 </div>
 <div class="modal-body">
  <p>My Body content</p>
 </div>
</ng-template>

![image](https://user-images.githubusercontent.com/55808656/113558255-f2b30000-961c-11eb-8bb5-3ed590f9010b.png)

**Comment by krilllind** [comment]
To start off with, this is not really a bug and in the future I recommend you to ask your questions over at stackoverflow or join the [Angular discord server](https://discord.gg/5dKcMwPm7V) where people can help you out much faster.

For now, I'll try to answer your question as good as possible based on the information you have given.

In later TypeScript versions, you must add the `!` or `?` character at the end of your property to tell TypeScript that this value will not be null or that it can be null. Properties decorated with for example `@ViewChild` should not have a default value as these property values will be overwritten by the result from Angular after performing a query on the template.

In your case, it looks like you are trying to query (using `@ViewChild`) an `ElementRef` which will yield you undefined because the `#templateRef` you are using is poining to an `ng-template` element. This element won't exists in your template as it's never rendered (by design).

If you want a reference to this `ng-template` you can use the following property definition.
`@ViewChild("contentModal1, { read: TemplateRef }) prop!: TemplateRef<any>`

If you want to query for an element in you template, you must make sure that:
1. Your `#templateRef` is on an HTML element and not `ng-template` or `ng-container`
2. Supply the `{ read: T }` option to `@ViewChild` if you are trying to read an `ElementRef<T>` on something like a component
3. Access your value in the [ngAfterViewInit](https://angular.io/api/core/AfterViewInit) lifecycle hook. If you don't specify the `{ static: true }` option to `@ViewChild`, your property will only be set once this hook is called (by default).

I hope this helps you out

**Comment by atscott** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).

**Comment by thirumanidev** [comment]
Thank you @krilllind and all.
It works well.

@atscott OK, I'll do for future questions. :)
