### ISSUE TITLE
Validators Email

### ISSUE THREAD

**Issue by ealvarez968** [angular/angular#41588]
# 🐞 bug report

### Affected Package

 The issue is caused by package @angular/....

### Is this a regression?

 Yes, the previous version in which this bug was not present was: ....

### Description

 A clear and concise description of the problem...
The Validators for email allow myemail@mydomain as valid without the last top level domain

## 🔬 Minimal Reproduction

 https://stackblitz.com/...

## 🔥 Exception or Error
<pre><code>

</code></pre>

## 🌍  Your Environment

**Angular Version:**
<pre><code>

</code></pre>

**Anything else relevant?**

**Comment by stefanoww** [comment]
I am not sure whether anything will change there due to the fact that current validator is compatible to the all of the standards of validating emails.

https://www.w3.org/Bugs/Public/show_bug.cgi?id=15489
https://html.spec.whatwg.org/multipage/input.html#valid-e-mail-address

But you can create your custom validator for the email using [Pattern Validator](https://angular.io/api/forms/PatternValidator)

**Comment by AndrewKushnir** [comment]
Closing this issue based on the comment from @stefanoww above.
