### ISSUE TITLE
Intersection Observer API

### ISSUE THREAD

**Issue by mclr47** [angular/angular#41770]
https://stackblitz.com/edit/intobs
https://stackblitz.com/edit/intobs

Please look at app.component.ts lines 56- 60

The example is taken from :

 https://developer.mozilla.org/en-US/docs/Web/API/Intersection_Observer_API

.....and adapted for Angular

## What is the problem?

entry.target.style.backgroundColor    
not working , but only 
 entry.target.parentElement.style.backgroundColor
..........in Angular

## What did you expect to see?

I want to style the element not its parent

**Comment by gkalpak** [comment]
The example is a little confusing (for example, there are a lot of pieces of code that are not used), but there is nothing in Angular that would prevent `entry.target.style` from working the way you show.

I have created a simplified example that shows `entry.target.style.backgroundColor` working fine: [StackBlitz project][1]

##
I am going to close this, since everything works as expected afaict, but feel free to continue the discussion below.

[1]: https://stackblitz.com/edit/ngissue-41770?file=src/app/app.component.ts
