### ISSUE TITLE
"export 'ɵɵstaticViewQuery' (imported as 'ɵngcc0') was not found in '@angular/core'

### ISSUE THREAD

**Issue by yjyyyyyok** [angular/angular#41809]
# 🐞 bug report

### Affected Package
"@angular/animations": "~10.2.0",
"@angular/common": "~10.2.0",
"@angular/compiler": "~10.2.0",
"@angular/core": "~10.2.0",
"@angular/forms": "~10.2.0",
"@angular/platform-browser": "~10.2.0",
"@angular/platform-browser-dynamic": "~10.2.0",
"@angular/router": "~10.2.0",
"ng-zorro-antd-mobile": "^4.0.0"

### Is this a regression?

yes

### Description

when I exec ng add ng-zorro-antd-mobile ,after  create an empty angular-project

## 🔥 Exception or Error
<pre><code>

</code></pre>

## 🌍  Your Environment

Angular CLI: 10.2.1
Node: 14.16.1
OS: win32 x64

Angular: 10.2.5
... animations, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, router
Ivy Workspace: Yes

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1002.1
@angular-devkit/build-angular   0.1002.1
@angular-devkit/core            10.2.1
@angular-devkit/schematics      10.2.1
@angular/cli                    10.2.1
@schematics/angular             10.2.1
@schematics/update              0.1002.1
rxjs                            6.6.7
typescript                      4.0.7

**Comment by petebacondarwin** [comment]
What version of `@angular/compiler-cli` are you using? It looks like you have a version skew.

**Comment by yjyyyyyok** [comment]
Angular CLI: 10.2.1

> What version of `@angular/compiler-cli` are you using? It looks like you have a version skew.

**Comment by petebacondarwin** [comment]
That is strange. `ɵɵstaticViewQuery` was removed in Angular 11.2.0 in this [commit](https://github.com/angular/angular/commit/d5161138032c54057d819a8fd52159ce5b75ac18).
So that implies that the version of `@angular/core` in your application build is at 11.2.0 or greater, while the version of your `@angular/compiler` (or at least the version used to run the ngcc for this library) is still on 10.x.

Can you check the actual versions of all your Angular packages (by looking at their package.json files in node_modules). Also check that this library was not processed by ngcc on a different machine/project that had a different set of Angular versions.

**Comment by JoostK** [comment]
[`ng-zorro-antd-mobile` specifies `@angular/animations` as a direct dependency instead of a peer dependency](https://unpkg.com/browse/ng-zorro-antd-mobile@4.0.0/package.json) so it gets its own copy of Angular 11 that is not compatible with the version of Angular that is part of your workspace. Since you are still on Angular 10 you should be using version ^3.0.0 of `ng-zorro-antd-mobile`. That version also has `@angular/animations` as a direct dependency but its version range should align with the workspace version, allowing the dependency to be shared. You may need to remove `package-lock.json` and/or `yarn.lock`. Additionally, please report an issue with `ng-zorro-antd-mobile` to change their `dependency` into `peerDependency`.

**Comment by petebacondarwin** [comment]
> "ng-zorro-antd-mobile": "^4.0.0"

Nice spot @JoostK
