### ISSUE TITLE
Show Custom Component Inside Root or as Root Sibling Before Bootstrap

### ISSUE THREAD

**Issue by Halfist** [angular/angular#41823]
# 🚀 feature request

### Relevant Package

This feature request is for:
"@angular/core": "~11.0.5"

### Description
I have a loading spinner component, which I want to show in 2 cases (because I don't want to duplicate the code):
1. Before app bootstrap.
2. During HTTP calls.

The second is fine, but the first appears to be a real problem.

The idea was to use a technique that allows to put content inside `<app-root></app-root>` in `index.html`, which disappears after app bootstrap.

While simple `<app-root>Loading...</app-root>` works well, I didn't find any way to use custom component instead of plain `Loading...` text.

There are many examples like the following, but, as I said, I don't want to duplicate code, so, markup and styles are in one place.
```
<app-root>
  <style>/* fancy styles */</style>
  <div><!-- fancy markup --></div>
</app-root>
```

### Describe the solution you'd like
What have I tried:

1.
```
// app.module.ts
imports: [SpinnerModule]

// index.html
<app-root>
  <loading-spinner></loading-spinner>
</app-root>
```

Nothing happens. It seems that component wasn't shown at all.

2.
```
// app.module.ts
imports: [SpinnerModule]

// index.html
<app-root>
  <ng-container *ngTemplateOutlet="spinner"></ng-container>
</app-root>
<ng-template #spinner>
  <loading-spinner></loading-spinner>
</ng-template>
```

Nothing happens. It seems that component wasn't shown at all.

3. 
```
// app.module.ts
imports: [SpinnerModule],
bootstrap: [SpinnerComponent]

// index.html
<app-root></app-root>
<loading-spinner></loading-spinner>

// main.ts
platformBrowserDynamic().bootstrapModule(AppModule).then((): void => {
  const loadingSpinner: Element = document.getElementsByTagName('loading-spinner')[0];
  document.body.removeChild(loadingSpinner);
});
```

Component was shown for a second, but it seems that it appeared together with `AppComponent`. I double checked this by wrapping `platformBrowserDynamic().bootstrapModule(AppModule)` with `setTimeout()`. In this case it doesn't make sense to show it at all, since it should be shown **during** `AppComponent` load, not **after**.

### Describe alternatives you've considered
Well, I'd need to either abandon showing the spinner before app bootstrap or duplicate its markup and styles in both `loading-spinner.component.html` and `index.html`. I was also thinking that maybe it's possible to kind of pre-compile `SpinnerComponent`, but I'm not sure how to do that.

**Comment by jnizet** [comment]
The content placed inside the `app-root` element is only displayed *before* the Angular application has started. The Angular application needs some time to start because downloading, parsing and executing the JavaScript files takes some time. 

The corollary is that, since the Angular application has not started yet when this content is displayed, you can't possibly use an Angular component there: for the Angular component to be displayed, the JavaScript code would need to be downloaded, parsed and executed already.

What you should strive for, IMHO, is to avoid having to display a loading spinner in the first place, by using lazy loading, and trying to have a main module that is as small as possible. That's what will make it possible to start the Angular really fast, and to have a root component that can be displayed almost instantly.

**Comment by gkalpak** [comment]
As @jnizet explained, it is not possible (by definition) to show an Angular component before the Angular app bootstraps.
You can either use a standalone spinner (that does not depend on Angular) or look into [server-side rendering (SSR)][1].

[1]: https://angular.io/guide/universal
