### ISSUE TITLE
Angular 2 version-alpha 37 :: can not use one component in another component  

### ISSUE THREAD

**Issue by shatakshidixit** [angular/angular#4188]
I am trying to import my Home component in my main component but its not working in alpha 37.

Here is my plnkr http://plnkr.co/edit/mTeZnwI7Ty79DYC1lYtb?p=preview

**Comment by pkozlowski-opensource** [comment]
Strictly speaking this is a question about SystemJS usage (https://github.com/systemjs/systemjs) and has not much to do with Angular itself. The problem is that SystemJS can't find referenced files (see 404 errors on your console). One way of solving this is to explicitly add extensions in import paths: http://plnkr.co/edit/0dnW8xUUXMevt99iHJdd?p=preview 

Refer to https://github.com/systemjs/systemjs if you need more info.
