### ISSUE TITLE
Allow trailing dollar-sign for two-way-bindings

### ISSUE THREAD

**Issue by angelaki** [angular/angular#41961]
Just like documented, for two-way-bindings working correctly, the `@Output()` EventEmitter must be named `[property]Change`. Since I add a trailing dollar sign to all my observables (what EventEmitters are), I'd like to call it `[property]Change$`. But since this would be a breaking change and checking for both properties seams unnecessarily costly I guess that naming pattern won't make it to Angular? Or can this be done / checked at compile time?

**Comment by petebacondarwin** [comment]
If you only want your internal properties to end in $ then you can do:

```ts
Output('propertyChange') propertyChange$ = new EventEmitter();
```

See https://stackblitz.com/edit/angular-nhqur1-sdgppf?file=src/app/sizer/sizer.component.ts

Is that sufficient for you?

**Comment by angelaki** [comment]
Absolutely! Thank you very much - and sorry for not checking it!

**Comment by petebacondarwin** [comment]
You are welcome to use `$` in your own outputs. See https://stackblitz.com/edit/angular-ivy-ecasfl?file=src%2Fapp%2Fapp.component.ts

We just don't intend to add `...Change$` as an option for two-way data-binding.

**Comment by angelaki** [comment]
Yes, but why not thinking about allowing it for two-way data-bindings?

**Comment by petebacondarwin** [comment]
Can you clarify exactly what you are requesting? Do you want `$` in the template or code-behind, or both? And only for banana-in-a-box bindings, or for all outputs?

**Comment by angelaki** [comment]
Yeah, sorry ... Getting a bit confusing.

I want to use the `$`-naming convention for my `EventEmitters` in the code-behind files but still be able to use the events (banana-in-a-box and output only) without the trailing `$` in the UI.

Right now I rename all my `@Output()` (e.g. `@Output('event') event$`) but it feels very inconvenient.

**Comment by petebacondarwin** [comment]
I am sure we will not allow `@Output()` to be able to default to either the name of the property or the the name with `$` appended. This would add too much magic and could be confusing: what if you used both `(foo)` and `(foo$)` in your template? Moreover, I don't think this is a common requirement. If you want your outputs to have a different name in the template than in the component, the facility is there to rename them.

Regarding the two-way-binding naming. Currently the desugaring of `[(foo)]="value"` is to `[foo]="value" (fooChange)="value=$event"`. I think you are suggesting that this should be changed so that if the compiler finds a `foo$` rather than a `fooChange` then the desugaring becomes `[foo]="value" (foo$)="value=$event"`. This would allow you to write in your code:

```ts
class MyComp {
  @Input() foo;
  @Output() foo$;
}
```

rather than currently:

```ts
class MyComp {
  @Input() foo;
  @Output('fooChanges') foo$;
}
```

Personally, I think this is just a special case of the scenario above, where you want to rename your outputs to remove the `$` in the template, and I don't believe we should support this. The reasons are a) only one person has requested this (you) and b) it would add additional magic to the framework that would need documenting and maintaining.

**Comment by angelaki** [comment]
```
class MyComp {
  @Input() foo;
  @Output() foo$;
}
```

Yes, that's the behavior I'd like to see. But guess you're right, the _automagic_ desicion was made for `prop` and `propChange`. Is your `fooChange**s**` a typo or does change **and** changes work? If both work, why not add the trailing dollar? If it was a type - guess we're done here and **propChange** it is 😄

**Comment by petebacondarwin** [comment]
Sorry it was a typo :-)

**Comment by angelaki** [comment]
Haha, too bad... there goes my hope for aliases 😉
Never mind, so `propChange` it is 👍

**Comment by petebacondarwin** [comment]
Thanks for your understanding and this very interesting discussion!

**Comment by angelaki** [comment]
Thank you for your fast and kind support! 👍
