### ISSUE TITLE
Event Properties Consistency

### ISSUE THREAD

**Issue by TiagoBraga39** [angular/angular#4207]
Hi everyone!

Properties and Events have different alias behaviour.

If I want to alias a property with hyphens I use:
```javascript
properties: ['selectedValue: selected-value'],
```

But If I want to alias an event with hypens:
```javascript
events: ['valueUpdate: selected-value'] // this won't work... 
//events: ['valueUpdate: selectedValue'] // this works
And then I can use (selected-value)="event"
```

Working plnkr: http://plnkr.co/edit/TnUqxetDhbgcO1ZEX63U?p=preview

Best regards,
Tiago Braga

**Comment by mhevery** [comment]
This works as intended, even thought it is confusing. That is because `<div (selected-value)="...">` binds to what event? Because we don't have casing in HTML, we have to assume that it binds to `selectedValue` event since that is the convention we use for converting skewer-case to camelCase. Therefore `['valueUpdate: selectedValue']` is correct.

**Comment by TiagoBraga39** [comment]
I understand it is correct. It is about consistency.
I just think that an alias to a property should be similar to an event.
An alias works as an outside way to use a property.

In property aliases we use the hyphens and works.
Not the case with events. We need the alias to be camel case.

As I understood:
<property/event> : <alias to use from the outside>
