### ISSUE TITLE
reportProgress does not return data progressively

### ISSUE THREAD

**Issue by thirumanidev** [angular/angular#42073]
Hi,
I'm trying to display progress bar of uploading image in my website.
**My code is**
```
this.http.post<any>('http://localhost/api/user-photo/add', uploadData, {
      reportProgress: true,
      observe: 'events'
    } ).subscribe(data => {console.log(data);});
```
But I'm not getting the "loaded" value progressively in the HttpEvent response, so I'm not able to show the progress bar in website progressively.
See this screenshot, this is what I'm getting the response.
**Response in console window:**
![image](https://user-images.githubusercontent.com/55808656/118091477-7f08cd80-b3e8-11eb-8ac8-21395763838c.png)

I followed some youtube videos, they are getting the response of "loaded" value constantly increasing and I could see that they are getting multiple returns in the console window, but I'm getting only one, and the "loaded" & "total" values are same, so If I couldn't  calculate the progress value.
This is the screenshot of their response, and it's working properly, I need it like this.
![image](https://user-images.githubusercontent.com/55808656/118092279-84b2e300-b3e9-11eb-8c12-ddec64dbdaf5.png)

https://www.youtube.com/watch?v=YkvqLNcJz3Y&t=598s
https://www.youtube.com/watch?v=rKvDmzcEros&ab_channel=ThomasOliver

Could you give me any suggestion to get the "loaded" value progressively?

Thanks & Regards
Thirumani

**Comment by petebacondarwin** [comment]
Angular has no control over how many progress events are triggered. It appears that the browser controls this and may be triggered no more often than every 50ms. See https://xhr.spec.whatwg.org/#ref-for-event-xhr-progress%E2%91%A1

Perhaps your upload is too fast? What happens if you upload an image that is 10x the current size? The example you give suggests the image is only ~189K, which could quite possibly be uploaded very quickly.

In any case, I'm afraid that this issue doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](https://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question).

**Comment by JoostK** [comment]
Alternatively you can simulate slower networks in Chrome, see [the docs on throttling support in Chrome devtools](https://developer.chrome.com/docs/devtools/network/#throttle). This would affect all network traffic, not just the upload.

**Comment by thirumanidev** [comment]
Hi,
I can see the counts constantly increasing in my console window now.
Thank you @JoostK I love the trick.
@petebacondarwin thank you for your quick reply.

But I have a question.
After getting the UploadProgress's response done, it waits for some seconds to receive the HttpHeaderResponse. May I know what it means, the file has been uploaded or not when I got the final UploadProgress's response?

I need to know that when I should show as 100% the upload process has been completed on my website? After getting the final UploadProgress's response or after getting the HttpHeaderResponse?

I checked in my uploading file directory(I'm using AWS S3 bucket), I didn't receive the file yet even when I got the final UploadProgress response, it says loaded=2292777 and total=2292777, so as per the Angular document it says if both values are same, the upload has been completed.
See these lines on that page:
```
const percentDone = Math.round(100 * event.loaded / event.total);
return `File "${file.name}" is ${percentDone}% uploaded.`;
```
https://angular.io/guide/http

FYI, I got the file once I received the HttpHeaderResponse only, not after the UploadProgress.
![image](https://user-images.githubusercontent.com/55808656/118149218-f9f4d700-b42e-11eb-80ad-610932c43c7b.png)
