### ISSUE TITLE
bug(service worker): unrecoverable state observable isn't emitted, chunk loading error

### ISSUE THREAD

**Issue by nitoloz** [angular/angular#42094]
# Bug Report

### Affected Package

The issue is caused by package @angular/service-worker

### Is this a regression?

Not sure if it's a regression since the `readonly unrecoverable: Observable<UnrecoverableStateEvent>` is only available since angular v11. 

### Description
After redeployment of web application to production service worker doesn't notice that severe changes have happened in lazy-loaded chunks and doesn't emit `swUpdate.unrecoverable` Observable. I'm relying on this Observable together with `swUpdate.available` to decide if I need to refresh the page after `activateUpdate` (meaning `this.swUpdate.activateUpdate().then(() => {document.location.reload(); })`) or if I can just activate it silently in the background and let users continue working without interruption (meaning just `this.swUpdate.activateUpdate()`). 

As long as I don't receive `swUpdate.unrecoverable` Observable emition I simply `activateUpdate()` without page reload and then suddely get the error that one of my lazy-loaded chunks isn't found (`ChunkLoadError: Loading chunk 33 failed`).

## Minimal Reproduction
Unfortunately can't reproduce it on a different setup, but hope that details below would help.

## Exception or Error
<pre><code>
main.99eb717a74ada4ed1190.js:3 ERROR Error: Uncaught (in promise): ChunkLoadError: Loading chunk 33 failed.
(error: https://develop.myserver.com/33.fee445daf61001f16f44.js)
ChunkLoadError: Loading chunk 33 failed.
(error: https://develop.myserver.com/33.fee445daf61001f16f44.js)
    at Function.c.e (runtime.75b926f943bfd962db06.js:1)
    at loadChildren (42.8020b6e24a56a9bb40f8.js:1)
    at Qt.loadModuleFactory (main.99eb717a74ada4ed1190.js:3)
    at Qt.load (main.99eb717a74ada4ed1190.js:3)
    at c.project (main.99eb717a74ada4ed1190.js:3)
    at c._tryNext (main.99eb717a74ada4ed1190.js:3)
    at c._next (main.99eb717a74ada4ed1190.js:3)
    at c.next (main.99eb717a74ada4ed1190.js:3)
    at e._subscribe (main.99eb717a74ada4ed1190.js:3)
    at e._trySubscribe (main.99eb717a74ada4ed1190.js:3)
    at T (polyfills.9204e7b4b7a45b852e79.js:1)
    at T (polyfills.9204e7b4b7a45b852e79.js:1)
    at polyfills.9204e7b4b7a45b852e79.js:1
    at u.invokeTask (polyfills.9204e7b4b7a45b852e79.js:1)
    at Object.onInvokeTask (main.99eb717a74ada4ed1190.js:3)
    at u.invokeTask (polyfills.9204e7b4b7a45b852e79.js:1)
    at s.runTask (polyfills.9204e7b4b7a45b852e79.js:1)
    at b (polyfills.9204e7b4b7a45b852e79.js:1)
    at f.invokeTask [as invoke] (polyfills.9204e7b4b7a45b852e79.js:1)
    at v (polyfills.9204e7b4b7a45b852e79.js:1)
</code></pre>

## Your Environment

**Angular Version:**
<pre><code>
Angular CLI: 11.2.11
Node: 14.15.1
OS: darwin x64

Angular: 11.2.12
... animations, common, compiler, compiler-cli, core, forms
... localize, platform-browser, platform-browser-dynamic
... platform-server, router, service-worker
Ivy Workspace: Yes

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1102.11
@angular-devkit/build-angular   0.1102.11
@angular-devkit/core            11.2.11
@angular-devkit/schematics      11.2.11
@angular/cdk                    11.2.11
@angular/cli                    11.2.11
@angular/material               11.2.11
@schematics/angular             11.2.11
@schematics/update              0.1102.11
rxjs                            6.6.7
typescript                      4.0.7
</code></pre>

**Anything else relevant?**
Here are some code snippets related to the way how I work with service worker.
`app.module.ts`
<pre><code>
ServiceWorkerModule.register('ngsw-worker.js', { enabled: environment.production, registrationStrategy: 'registerImmediately' })
</code></pre>

`main.ts` (because of the isse mentioned here https://github.com/angular/angular-cli/issues/13351)
<pre><code>
platformBrowserDynamic().bootstrapModule(AppModule).then(() => {
  if ('serviceWorker' in navigator && environment.production) {
    navigator.serviceWorker.register('/ngsw-worker.js');
  }
}).catch(err => console.log(err));
</code></pre>

`service-worker.effects.ts`
<pre><code>
 public swUpdateAvailable$ = createEffect(() => this.swUpdate.available.pipe(
    tap(() => this.swUpdate.activateUpdate()),
  ), { dispatch: false });

  public unrecoverableUpdateAvailable$ = createEffect(() => this.swUpdate.unrecoverable.pipe(
    map(() => askUserToRefreshAction()), // showing a modal dialog and then activating update with page reload 
  ));
</code></pre>

**Comment by gkalpak** [comment]
This sounds like a variation of #28114. We've been gathering debug information to investigate this in #41117 (so you can follow that for progress).

As mentioned in [the docs][1], an `UnreceverableStateEvent` is emitted when the SW cannot retrieve a resource that it knows it should exit (such as a resource from a hashed resource of an asset group). But based on the info gathered in #41117, what I believe happens is that the page is assigned an app version that does not have the missing asset in its hashed resources list. So, from the perspective of the SW, this does indeed not qualify as an unrecoverable state.

It seems that somehow the client is switched between app versions when it shouldn't, but I haven't yet been able to figure out if that's indeed the case or why it happens.

##
I am going to close this, since we are already tracking the missing resource error in the issues mentioned above and the unrecoverable state event emission works as expected in this case.

If you have more questions, feel free to continue the discussion below and if you have info that you think may help diagnose the underlying problem, please post it on one of the other issues :pray:

[1]: https://angular.io/guide/service-worker-communications#handling-an-unrecoverable-state
