### ISSUE TITLE
Animations callbacks triggered regardless of the event fired

### ISSUE THREAD

**Issue by 4javier** [angular/angular#42125]
# Bug Report

### Affected Package
The issue is caused by package @angular/animations

### Description
Bounding animations to `:leave` and `:enter` transition aliases of an element, gets their callbacks triggered even for events that should not.
Setting up these animations
```ts
	trigger('fromLeft', [
		transition(':enter', [
        ...
        ...
        ...
        trigger('fromRight', [
               transition(':leave', [
```
to this element
```html
<div [@fromLeft] [@fromRight]
 (@fromLeft.start)="mylog('DYNAMIC ENTER START', $event)" 
 (@fromRight.start)="mylog('DYNAMIC LEAVE START', $event)" 
 (@fromLeft.done)="mylog('DYNAMIC ENTER DONE', $event)" 
 (@fromRight.done)="mylog('DYNAMIC LEAVE DONE', $event)" >
 ```
Will print every log on all events. 
On element creation `leave` logs will be printed too, and on element destruction same thing will happen with `enter` logs.
This happens both with content projected by `<ng-content>` both with static elements.
Proof is into the logged event, like:
```
DYNAMIC LEAVE START
disabled: false
element: HTMLDivElement
fromState: "void"
phaseName: "start"
toState: null
totalTime: 0
triggerName: "fromRight"
```
As you can see an event from `void` to `null` triggered the callback for an animation bound to `:leave` alias

## Minimal Reproduction
Here you can find a SB showing both static both dynamic behaviour
https://stackblitz.com/edit/angular-ivy-w67tm2

## Your Environment

**Angular Version:**
<pre><code>
Angular CLI: 11.2.10
Node: 14.16.0
OS: linux x64

Angular: 11.2.11
... animations, common, compiler, compiler-cli, core, forms
... language-service, localize, platform-browser
... platform-browser-dynamic, router
Ivy Workspace: Yes

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1102.10
@angular-devkit/build-angular   0.1102.10
@angular-devkit/core            11.2.10
@angular-devkit/schematics      11.2.10
@angular/cdk                    11.2.10
@angular/cli                    11.2.10
@schematics/angular             11.2.10
@schematics/update              0.1102.10
rxjs                            6.6.7
typescript                      4.1.5

</code></pre>

**Comment by crisbeto** [comment]
I _think_ this is working as expected since `:enter` and `:leave` are just shorthands for `void => *` and `* => void`, they aren't supposed to map to `.start` and `.done`. There's more information in the docs: https://angular.io/guide/transition-and-triggers#enter-and-leave-aliases.

**Comment by 4javier** [comment]
@crisbeto 
I don't get it.
Precisely because `:leave` is just a shortand for `* => void` I would expect its callback not being fired by a `void => null` event.
Maybe there's a wrong management of the `null` value?

**Comment by dario-piotrowicz** [comment]
Hi @4javier I looked into this and for what is worth I just wanted to say that I am really pretty sure it is an actual bug and not the expected behavior

From the source code I can see the issue is that the `fromRight` trigger player gets included in the animations flush, it gets correctly skipped as the transition does not match but it is still included in the `skippedPlayers` array which triggers the callbacks (but you can intuitively see that it is getting skipped in your console logs, as the animation events printed there for that have a `totalTime` of `0`):
![Screenshot at 2021-12-04 17-39-45](https://user-images.githubusercontent.com/61631103/144719149-a8c4d6af-2007-4cb3-8dd7-676d147804ff.png)

So I think that the only clean solution would be to prevent the instruction to be added to the instructions queue during trigger initialization (so that is will not get detected and added to the skipped players).

But the issue is that there I cannot see any useful information that can help us discern that the instruction should not be queued...
(there we simply get the trigger and cannot rely on its transitions to see if it is for leaving elements as the trigger can anyways have multiple transitions...)

I'll try to look more into it, but fixing this may be tricky :sweat:

**Comment by dario-piotrowicz** [comment]
Hi @4javier I've been looking into this and believe that the current behavior is totally working as expected (but for different reasons than @crisbeto)


My reasoning is that if you look at the [animations docs](https://angular.io/guide/transition-and-triggers#animation-callbacks) it does specify that:
 >  The animation __trigger()__ function emits callbacks when it starts and when it finishes.

(which is also evident from the fact that we use the trigger name for the callbacks)
 
 So basically the callbacks indicate then the __trigger__ starts and finished, and __not__ the single transitions in it, basically the callbacks apply when the trigger starts to animate and when if finishes (meaning all its transitions) so in your case the `fromRight` trigger takes `0` time to complete when the `:leave` transition doesn't apply, but it is still "run" so you do get the callbacks called as expected.
 
For example see this stackblitz: [noop animation trigger example](https://stackblitz.com/edit/angular-ivy-y5dkdk?file=src%2Fapp%2Fapp.component.ts), as you can see there are no transitions or anything associated to the `noopAnimation` trigger, but in the console you will see logs for start and done when you click the button.

What can throw you off is the fact that your triggers have each a single transition, but angular doesn't know the semantic/meaning of your triggers, it cannot discern which it needs to run or not depending on their content, all of them are run, but (like in your leave case) they can have no animations played, regardless it still makes sense to run the callbacks as the trigger was run/executed 

I hope this helps, please let me know what you think :slightly_smiling_face: 

___
 
<sup> ps: I put a comment in the thread before saying that I thought it was an actually bug, if you saw that just ignore it, I was barking up the wrong tree :sweat_smile: </sup>

**Comment by 4javier** [comment]
HI @dario-piotrowicz 
It took some time to reply because your first message lately edited confused me a bit.
Next time, better add a new one with your errata. :relaxed:
Btw, I read it more than once, and sincerely can't find anything new than what was already clear.

The fact that every triggers' callback gets called regardless they have a transition involved or not into the event, sounds conceptually wrong.

First thing coming to mind:
why the need to specify `(@triggerName.start)` when every other triggers' callback will be called anyway?
At that point, a static `(animation.start)` would have been enough.

The way it is now is counterintuitive, like if the original idea of the author was different than the current implementation.

**Comment by dario-piotrowicz** [comment]
@4javier I am so sorry, the old message was there for rather short time so I didn't think anyone would even read it, besides it was totally off the mark so I didn't see any benefit in keeping it in :stuck_out_tongue_winking_eye: sorry about the confusion

About your first comment, I am sorry if I stated the obvious, based on how the issue was phrased I assumed you were saying that each transition has it's own callback (an error which I have seen other people make)

Regarding your second comment about `(animation.start)`, I disagree, for example because:
 - triggers can be added/removed from the dom (e.g. `*ngIf`, `*ngFor`, etc...)
 - the callbacks provide an [`AnimationEvent`](https://angular.io/api/animations/AnimationEvent), which provides useful information which you can use to discern what animation just started, how long is going to take, is the animation is disabled or not

Also please note that the callbacks are indeed called on disabled animations too and since there is a
`disabled` field in the `AnimationEvent` it does give me the impression that this is the expected behavior

**Comment by 4javier** [comment]
> I am so sorry, the old message was there for rather short time so I didn't think anyone would even read it, besides it was totally off the mark so I didn't see any benefit in keeping it in stuck_out_tongue_winking_eye sorry about the confusion

No problem.

> triggers can be added/removed from the dom (e.g. *ngIf, *ngFor, etc...) (so it's not like all of them all always start, some may not start as their elements are not in the dom)

How would this be different if instead of `@specificTriggerName.start`, api would expose a generic view scoped `animation.start`?
All the animations callbacks bound to element present in the view at that moment would fire up.
Exactly how it is now.

The point is that at the state of the art, if I have different triggers, it makes no difference to bound an handler to `@trigger_A.start` or `@trigger_B.start`.
It would be started anyway on every animation triggering, be it the one bound or the other.

> the callbacks provide an AnimationEvent, which provides useful information which you can use to discern what animation just started, how long is going to take, if the animation is disabled or not

I'm not an expert and I didn't puzzle around with animations in some time now, but I see it's marked as internal.
That's probably used just to automatically call the `NoopAnimationPlayer` controller when the animation is disabled.

**Comment by dario-piotrowicz** [comment]
maybe this unit test (added by the creator of the animations package in PR #15170) can convince you that this is the expected behavior? :slightly_smiling_face: 

https://github.com/angular/angular/blob/b31973c176f67fda563e77c8c5d59ae45881de4c/packages/core/test/animation/animation_integration_spec.ts#L2864

**Comment by 4javier** [comment]
Yes.
That's the proof this is the expected behaviour.
Thanks for your effort tracking it down.
Thus, this is clearly not a bug, but I keep missing the sense of this functionality.
It breaks the possibility to separate the callbacks of different triggers.
Probably it has been created keeping in mind just the usecase of triggers actually bound to a value, and not the one where you have more than one trigger simply firing up on component lifecycle.

**Comment by jessicajaniuk** [comment]
It appears this behaves as expected. If you still feel there is an issue, please provide further details in a new issue.
