### ISSUE TITLE
Admin rights required for Node and Angular commands

### ISSUE THREAD

**Issue by AnkitVNTT** [angular/angular#42141]
Hi Team,

We are working on Angular 11 on Windows 10 virtual machines inside our organization. We are not able to execute Node and Angular command in Visual Studio Code terminal and Node.js command prompt without admin rights on our virtual machines. It always give "‘ng’ is not recognized as an internal or external command" in both Visual Studio Code terminal and Node.js command prompt. But it is working fine if we have admin rights on our virtual machines. 

As per our communication with our Windows team, they are not able to provide admin rights to all users for Node/Angular command execution due to organization security reasons. 

We wanted to check if there any Windows/PC setting we can remains open to get rid from this admin rights issue, or any suggestion for smooth execution of Node/Angular command on our virtual machines without admin rights. 

Please suggest on over this.

**Comment by crisbeto** [comment]
I think that the only case where admin rights are required is if you want to install the `ng` command globally. You can also have it use your local installation by defining an npm script for it in your `package.json`. E.g.

```
"scripts": {
  "serve": "ng serve"
}
```

Now running `npm run serve` will reference the CLI installed in your repository.

**Comment by gkalpak** [comment]
AFAICT, this is not an Angular-specific issue. It is about installing/using Node.js/npm without admin right (i.e. sounds more like a Node.js/npm configuration issue).

You can look into installing Node.js/npm for the local (non-admin) user. There are several resources on that online ([example][1]).
It might also just be a matter of configuring your local user's path to include the location where npm installs globally installed packages (and their executables). By default, it puts the globally installed executables alongside the Node.js executable, but maybe it is configured differently in your case.

It might also be worth asking on StackOverflow or our Discord server. See [Got a question or problem?][2].

##
I am going to close this issue, since I don't think there is something to be fixed in Angular/Angular CLI, but feel free to continue the discussion below.

[1]: https://stackoverflow.com/questions/37029089/how-to-install-nodejs-lts-on-windows-as-a-local-user-without-admin-rights#57327530
[2]: https://github.com/angular/angular/blob/6d1477664b33556c9c0e811fc1be01af0622acc9/CONTRIBUTING.md#question
