### ISSUE TITLE
App-shell or Universal apps are unable to set css variables in document

### ISSUE THREAD

**Issue by richardsengers** [angular/angular#42170]
# Bug Report

### Is this a regression?

No

### Description
Unable to set css variables in documentElement for app-shell or universal

## Minimal Reproduction
https://github.com/richardsengers/theming

```ng run app-shell```

## Exception or Error
<pre><code>
ERROR TypeError: Cannot read property 'type' of undefined
    at TokenStream.LA (C:\sources\playground\dynamic-theming\dist\dynamic-theming-demo\server\main.js:1204:30)
    at TokenStream.advance (C:\sources\playground\dynamic-theming\dist\dynamic-theming-demo\server\main.js:1077:20)
    at Parser._readDeclarations (C:\sources\playground\dynamic-theming\dist\dynamic-theming-demo\server\main.js:3796:42)
    at Parser.parseStyleAttribute (C:\sources\playground\dynamic-theming\dist\dynamic-theming-demo\server\main.js:3975:22)
    at parseStyles (C:\sources\playground\dynamic-theming\dist\dynamic-theming-demo\server\main.js:38557:10)
    at CSSStyleDeclaration.value (C:\sources\playground\dynamic-theming\dist\dynamic-theming-demo\server\main.js:38676:22)
    at ThemingService.setColorVariable (C:\sources\playground\dynamic-theming\dist\dynamic-theming-demo\server\main.js:57644:45)
    at C:\sources\playground\dynamic-theming\dist\dynamic-theming-demo\server\main.js:57546:22
    at Array.forEach (<anonymous>)
    at C:\sources\playground\dynamic-theming\dist\dynamic-theming-demo\server\main.js:57541:26
    at Array.forEach (<anonymous>)
    at ThemingService.setupMainPalettes (C:\sources\playground\dynamic-theming\dist\dynamic-theming-demo\server\main.js:57535:45)
    at SafeSubscriber._next (C:\sources\playground\dynamic-theming\dist\dynamic-theming-demo\server\main.js:57524:18)
    at SafeSubscriber.__tryOrUnsub (C:\sources\playground\dynamic-theming\dist\dynamic-theming-demo\server\main.js:40357:16)
    at SafeSubscriber.next (C:\sources\playground\dynamic-theming\dist\dynamic-theming-demo\server\main.js:40296:22)
    at Subscriber._next (C:\sources\playground\dynamic-theming\dist\dynamic-theming-demo\server\main.js:40246:26)

</code></pre>

## Your Environment

**Angular Version:**
<pre><code>

Angular CLI: 11.0.1
Node: 14.17.0
OS: win32 x64

Angular: 11.0.0
... animations, cdk, common, compiler, compiler-cli, core, forms
... material, platform-browser, platform-browser-dynamic, router
Ivy Workspace: Yes

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1100.1
@angular-devkit/build-angular   0.1100.1
@angular-devkit/core            11.0.1
@angular-devkit/schematics      11.0.1
@angular/cli                    11.0.1
@angular/platform-server        11.0.9
@schematics/angular             11.0.1
@schematics/update              0.1100.1
rxjs                            6.6.3
typescript                      4.0.5

</code></pre>

**Anything else relevant?**
This has also been described in this issue: https://github.com/angular/angular/issues/36137

**Comment by petebacondarwin** [comment]
Should this issue be on the https://github.com/angular/universal repo?

**Comment by richardsengers** [comment]
Yes maybe you are right. @petebacondarwin  do you want me to put it there?

**Comment by petebacondarwin** [comment]
I'll ask @alan-agius4  to transfer it.

**Comment by alan-agius4** [comment]
Likely this is platform-server/domino issue and hence this is the right repo for the issue.

It’s on my list of items to investigate.

**Comment by alan-agius4** [comment]
This indeed appears to be an issue with [Domino](https://github.com/fgnass/domino), which doesn't support the latest browser features.

Therefore, this is blocked until we switch over to a new JavaScript DOM API.

**Comment by uciaczek** [comment]
To those that are still struggling with this: I have added a "try-catch"-block around the statement where i set the custom property. Of course the type error still occurs, but the script is executed correctly (I have my properties in the DOM).
This is of course a major hack but might be helpful until that [Domino](https://github.com/fgnass/domino) dependency is removed.

**Comment by Roman-Simik** [comment]
We needed to make it work in SSR, because the HTML generated from SSR, would be otherwise broken due to css vars not applied.

How we managed to make it work (Instead of calling `element.setProperty(xxx, xxx)`):

```
// dynamically create CSS var declaration like in css

const styleString = '--var-xx: blue; --var-xxx: 10px'

// then  apply it to some html element
// note that TS will complain, that the style property is readonly and cannot be changed, 
// so you need to bypass it by @ts-ignore
htmlElement.style = styleString

//or create style element. and add it into dom
const styleElm = document.createElement('style')
styleElm.style = styleString

document.body.appendChild(styleElm)
```

This will ensure the css styles are correctly applied also in the generated html which is returned from SSR.

**Comment by crisbeto** [comment]
Cross-posting my findings from #47928 here:

I spent some time investigating it, and it looks like this is a problem with the `domino` renderer that Angular uses for its server-side DOM implementation. Domino doesn't support CSS variables and some CSS properties like `clip-path`, e.g. if you try doing `element.style.setProperty('--foo', '1px')`, the value just gets dropped. We work around it by writing directly to the `style` attribute instead: https://github.com/angular/angular/blob/main/packages/platform-server/src/server_renderer.ts#L298

The error in this specific case happens, because when the `--vh` variable is set, the element looks like `<app-root style="--vh:1vh"></app-root>`, but later on the Angular animations module tries to set `el.style.display = 'none'` on the same element. This tells Domino to parse the `style` attribute and it leads to the error, because Domino doesn't know how to deal with a property starting with `--`. It happens in the specific combination of the Material form field + CSS variables, because Material uses the Angular animations module to animate the error/hint messages, but it can also be reproduced with the following unit test:

```ts
it('fails', fakeAsync(() => {
  @Component({template: 'hello', selector: 'app-root'})
  class AppRoot {
    @HostBinding('style.--height') height = '100px';
  }

  @Component({
    template: '<app-root [@test]="animationState"></app-root>',
    animations: [trigger(
        'test',
        [
          state('enter', style({opacity: 1})),
          transition('void => enter', [style({opacity: 0}), animate('300ms linear')]),
        ])],
  })
  class MyApp {
    animationState = 'enter';
  }

  TestBed.configureTestingModule({declarations: [MyApp, AppRoot]});
  const fixture = TestBed.createComponent(MyApp);
  fixture.detectChanges();
  flush();
}));
```

The only workaround I've found, that doesn't involve an upstream fix in Domino, has been to ensure that at least one non-variable property is written to the DOM before any CSS variables. E.g. in your case you can work around it by adding a dummy host binding like `@HostBinding('style.color') color = 'inherit'` before the `@HostBinding('style.--vh')`. This workaround can be baked into Angular's server renderer as well, but it feels a little hacky.

**Comment by Tom4U** [comment]
Thanks @crisbeto for your further investigation. I can confirm, this workaround did it.

**Comment by alan-agius4** [comment]
This issue has been fixes in version 16 which is currently in pre-release.

If the problem persists in your application after upgrading, please open a new issue, provide a simple repository reproducing the problem, and describe the difference between the expected and current behavior. You can use `ng new repro-app` to create a new project where you reproduce the problem.
