### ISSUE TITLE
Create documentation for recommended CI pipeline configurations to take advantage of build cache

### ISSUE THREAD

**Issue by NateRadebaugh** [angular/angular#42219]
# Feature Request

### Description
Upgrading to angular 12 has had a 3x build-time decrease in my Azure DevOps CI pipeline. I don't know why this happened, but there must be something misconfigured on my end. I assume there's a caching mechanism with the new webpack 5 integration that I should be taking advantage of but I don't know how.

### Describe the solution you'd like
It'd be great if there was a section of the documentation site for various popular CI systems for how to best integrate the angular builds for the fastest DX.

### Describe alternatives you've considered
I've considered using the custom webpack plugin and trying to integrate with esbuild to improve build times but that doesn't seem like something people are doing.

**Comment by mgechev** [comment]
Thank you for the request! Angular is orthogonal to CI pipelines and we prefer to be agnostic on how to configure your build. If you're looking for an inspiration, I'd recommend checking our setup in [this monorepo](https://github.com/angular/angular) or [Angular DevTools](https://github.com/rangle/angular-devtools).

The current repository primarily uses Bazel and Remote Build Execution, so it's an example of a more sophisticated build pipeline.

I'd close the feature request since it seems to be outside of the scope of the project.
