### ISSUE TITLE
emitEvent option in forms broken in Angular 12

### ISSUE THREAD

**Issue by GeorgeKnap** [angular/angular#42237]
# Bug Report

### Affected Package
`@angular/forms`

### Is this a regression?
Yes, it was working for us in ng11

### Description
after upgrading to Angular 12 we started to have a problem with our material date range component. My investigation leads me to using `emitEvent: false`  option in (form control).setValue method which now doesn't prevent the event to be emitted.

Please see the stackblitz reproduction below.
There is a setter 
```
 private set selectedRange(dateRange: DateRange) {
    this.dateRangeForm.setValue(
      {
        start: dateRange.start,
        end: dateRange.end
      },
      {
        emitEvent: false,
        onlySelf: true
      }
    );
  }
```
which when called triggers valuechanges event and causing infinite loop of events, Just change the date or daterange in the stackblitz example.

## Minimal Reproduction
https://stackblitz.com/edit/date-range-weird-behavior?file=src/app/app.component.ts

## Your Environment

**Angular Version:**
<pre><code>

     _                      _                 ____ _     ___ 
    / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
   / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | | 
  / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | | 
 /_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
                |___/
    

Angular CLI: 12.0.0
Node: 14.16.1
Package Manager: npm 6.14.12
OS: win32 x64

Angular: 12.0.0
... animations, cdk, cli, common, compiler, compiler-cli, core
... elements, forms, language-service, material
... platform-browser, platform-browser-dynamic, router
... service-worker

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1200.0
@angular-devkit/build-angular   12.0.0
@angular-devkit/core            12.0.0
@angular-devkit/schematics      12.0.0
@angular/flex-layout            12.0.0-beta.34
@schematics/angular             12.0.0
rxjs                            6.6.3
typescript                      4.2.4

</code></pre>

**Anything else relevant?**

**Comment by mittalshubham093gmailcom** [comment]
Hi @GeorgeKnap ,
Please check at line number 128, 
Whenever you are changing the dates, it hits your zip method which has given in ngonInit, and call your "changeDate()" functions again. Not quite sure how it was working in an older version of angular, because as per the behavior of this method, it will automatically call once you will change both dates.

**Comment by Marcus095** [comment]
> Hi @GeorgeKnap ,
> Please check at line number 128,
> Whenever you are changing the dates, it hits your zip method which has given in ngonInit, and call your "changeDate()" functions again. Not quite sure how it was working in an older version of angular, because as per the behavior of this method, it will automatically call once you will change both dates.

Hi, I'm also working with @GeorgeKnap and can explain why it was working.
As you said the `changeDate()` is called in the subscription, however in angular 11 the value change event wasn't triggered since we set `{emitEvent: false}`, so it was being changed and that was it. Now for some reason the event is emitted even though we still have it set to not emit.

By changing the code to listen to the `valueChanges` directly from the form instead of the controls it works, however I still think that something changed/broke in angular 12 since our code was working fine with the previous versions

**Comment by mittalshubham093gmailcom** [comment]
This issue is occurring when you are not settling emit false right?
Because after removing below line it's working fine for me.

      {
        emitEvent: false,
        onlySelf: true
      }

**Comment by GeorgeKnap** [comment]
> This issue is occurring when you are not settling emit false right?
> Because after removing below line it's working fine for me.
> 
> ```
>   {
>     emitEvent: false,
>     onlySelf: true
>   }
> ```

So this confuses me completely. It doesn't emit the event when this option is not defined, but when it is set to false it does emit the event.  

The  [docs says:](https://angular.io/api/forms/FormControl#setValue)
```
emitEvent: When true or not supplied (the default), both the statusChanges and valueChanges observables emit events with the latest status and value when the control value is updated. When false, no events are emitted.
```

that is not what I see in the demo happening.

**Comment by iRealNirmal** [comment]
@petebacondarwin I can work on this, can you assign this ticket to me ?

**Comment by petebacondarwin** [comment]
Done

**Comment by iRealNirmal** [comment]
@GeorgeKnap I  did some modification in your stackblitz and problem might have resolved. Can  you visit below stackblitz and let me know

[https://stackblitz.com/edit/date-range-weird-behavior-ziencu?file=src%2Fapp%2Fapp.component.ts](https://stackblitz.com/edit/date-range-weird-behavior-ziencu?file=src%2Fapp%2Fapp.component.ts)

**Comment by Marcus095** [comment]
> @GeorgeKnap I did some modification in your stackblitz and problem might have resolved. Can you visit below stackblitz and let me know
> 
> https://stackblitz.com/edit/date-range-weird-behavior-ziencu?file=src%2Fapp%2Fapp.component.ts

Hi, I'm replying since I'm part of the same team. What you did was just comment out `this.changeDate(selectedDate);` in the `subscribe` which breaks the functionality of the range picker (if selecting dates manually with the picker).

The issue we had is that the default behaviour of `emitEvent` has changed, thus breaking a code that was working fine before the Angular update.

We have found a solution to our problem, however that doesn't change the fact that `emitEvent` doesn't behave as expected

**Comment by Marcus095** [comment]
> Hey @Marcus095 thanks for quick response, for me this seems bug from angular/component.
> 
> Check below links.
> [angular/components#20218](https://github.com/angular/components/issues/20218)
> [angular/components#22158](https://github.com/angular/components/issues/22158)
> 
> But if you think this is angular forms issue, can you help us to reproduce this issue without angular/material.
> 
> cc : @petebacondarwin @AndrewKushnir

Thanks @iRealNirmal , I guess it's the same or similar issue. Weird thing is, as I said, that it was working properly with angular and material 11 then it broke.

The solution that works is subscribing to the `FormGroup` instead of the controls 

https://stackblitz.com/edit/date-range-weird-behavior-bg7uxz?file=src/app/app.component.ts

So it makes even less sense for the 2 to work in different ways

**Comment by iRealNirmal** [comment]
Yes @Marcus095 it's actually same issue, and also @AndrewKushnir have done investigation in past and concluded that
` logic in Material Components invokes Forms API that triggers these valueChanges events.` [Link Here](https://github.com/angular/components/issues/22158#issuecomment-796395179) .

Regarding your question of  it working for FormGroup but not in FormControl so it's basically they might be invoking again changeDetection.

Regarding this issue if you are able to reproduce this issue with angular/forms I will be  able to help here, else It would be  great if you can give your consent for closing the issue.

**Comment by Marcus095** [comment]
@iRealNirmal thank you for all the info. I think we can close this issue then @GeorgeKnap

**Comment by GeorgeKnap** [comment]
Fine, it's tracked in material repo so let's close this one here. Thanks for your investigation @iRealNirmal
