### ISSUE TITLE
Router navigate doesn't work on version 7.0

### ISSUE THREAD

**Issue by Gen0106** [angular/angular#42242]
Hello.
I am working on a project that uses angular 7.0.

# Bug Report
Let's say the home page url is /profile now.
Then I edit the page url as /profile/1 and this works. Of course, I programmed this.
But after that, I edit the page url as  /profile/2 and this doesn't work.
I put the console log before router.navigate and I could confirm this console log and then I could never any console log and any action on the browser.
Please let me know how to fix this problem.

Thanks.

### Affected Package
The issue is caused by package @angular/router.

## Your Environment

**Angular Version:*7.0*

**Comment by mittalshubham093gmailcom** [comment]
Hi @Gen0106 ,
As per my understanding, you have an home component /profile and another component page /profile/{id}..
You are navigating from home page to the details page with id parameter with query string.
If you are changing the parameter from URL then it won't log it because you didn't hit the navigation method from your home page event.
Please let me know if you have different doubt about this issue?

**Comment by zarend** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](https://stackoverflow.com/) using tag `angular`.
