### ISSUE TITLE
Why the change detection is not fire with fromEvent and runOutsideAngular?

### ISSUE THREAD

**Issue by wizardnet972** [angular/angular#42241]
Not sure if it's bug somehow. But I would appreciate the help here. 

In my angular application I listen to `resize` event and update the breakpoint name in `breakpointChanged` subject:

```
  breakpointChanged = new Subject();

  resize$ = fromEvent(window, "resize").pipe(
    startWith(() => []),
    map(() => [window.innerHeight, window.innerWidth]),
    tap(([height, width]) => {
      const name = this.breakpoint(width);

      this.breakpointChanged.next(name);
    })
  );
```

Base on the breakpoint name I decided when the drawer should be open or not:
```
drawerOpened$ = this.breakpointChanged.pipe(
    distinctUntilChanged(),
    map((breakpointName) => {
      return breakpointName !== "xs"; // if it's not xs breakpoint then it's true mean it's open.
    })
  );
```
I also want to use `distinctUntilChanged` because if the breakpoint not changed I don't want to activate the stream.

And in `ngOnInit` I subscribe to the resize stream. And I do it in `runOutsideAngular`, so I won't trigger change detection every time the resize happens.
```
this.zone.runOutsideAngular(() => {
   this.resize$.subscribe();
 });
```
The problem is the view doesn't update.

Only when I wrap the `this.breakpointChanged.next(name);` with `this.zone.run(() => {})` it's works but if I do that I'll trigger change detection - always when the resize happens. ** which is bad thing.**

Any idea how to solve this problem and make it nice and clean?

In the same context, how async pipe doesn't make change detection? the value is changing and async should subscribe and trigger when it's the value changes.

[codesandbox.io](https://codesandbox.io/s/snowy-sun-o3ft2?file=/src/app/app.component.ts)

**Comment by JoostK** [comment]
Please refer to https://github.com/angular/angular/issues/37223#issuecomment-786131699 and the mentioned StackBlitz for an example of how to have control over NgZone activations in observable pipelines.

> In the same context, how async pipe doesn't make change detection? the value is changing and async should subscribe and trigger when it's the value changes.

Although the subscription in the async pipe updates causes the pipe's internal state to be updated, the "trigger" did not originate from within the Angular zone because it originates from the resize handler that was installed outside of the zone. As a consequence, Angular itself is not aware that any state may have changed so no change detection is run, which is necessary to propagate the async's internal state to the rendered view.

I'll close this as there is no bug here and questions like these are better suited for StackOverflow or Discord.
