### ISSUE TITLE
`ControlValueAccessor`'s `setDisabledState` should be called before the `validate` function is called

### ISSUE THREAD

**Issue by skrtheboss** [angular/angular#42343]
# Bug Report

### Affected Package
The issue is caused by package `@angular/forms`

### Is this a regression?

No.

### Description
 Implement a `CVA` like it is done in this [blog post](https://blog.angular-university.io/angular-custom-form-controls/#file-22-ts).
 Call disable on an outer form, then call enable, now the form is invalid.
 The problem is, that the setDisabledState is called only after the validation check has been perfomed.

## Minimal Reproduction
Open the [stackblitz](https://stackblitz.com/edit/angular-tkkbvg), click on disable and then on enable, and the form will still be invalid.

## Your Environment

**Angular Version:**
See in stackblitz ( 12.0.1 )

**Anything else relevant?**
I have done some debugging, and think the root cause is the order of those [function calls](https://github.com/angular/angular/blob/a92a89b0eb127a59d7e071502b5850e57618ec2d/packages/forms/src/model.ts#L667-L680).

**Comment by petebacondarwin** [comment]
I have to admit I am very confused by this example. Are you mixing Reactive and Template driver forms in the same example?

Putting that aside, it seems to me that you are relying upon the validity of the `form` control within the custom validator but ignoring whether it is disabled or not...

```ts
  validate(control: AbstractControl) {
    console.log('Form status on validate call ', this.form.status);
    console.log('Form valid on validate call ', this.form.valid);

    return this.form.valid ? null : { testError: true };
  }
```

There is a question of whether the `validate()` method should even check the validity of `this.form` if it is disabled.
According to [this code comment](https://github.com/angular/angular/blob/a92a89b0eb127a59d7e071502b5850e57618ec2d/packages/forms/src/model.ts#L328-L330) "Disabled controls are exempt from validation checks and are not included in the aggregate value of their ancestor controls." So perhaps you should not check the validity of your child `this.form` if it is currently disabled?

**Comment by AndrewKushnir** [comment]
@skrtheboss as you pointed out the problem in your example was caused by the fact that the `setDisabledState` and `validate` are called in a specific order. Specifically, when you call [the `enable()` method](https://github.com/angular/angular/blob/a92a89b0eb127a59d7e071502b5850e57618ec2d/packages/forms/src/model.ts#L667-L680):

- the `validate` gets invoked first as a part of the `updateValueAndValidity` call [here](https://github.com/angular/angular/blob/a92a89b0eb127a59d7e071502b5850e57618ec2d/packages/forms/src/model.ts#L676)
- after that once all updates are completed the logic goes through all registered `setDisabledState` callbacks

I think the solution is to update the code of your custom `ControlValueAccessor` to handle this sequence. For example, you can turn your validator into an async validator - that'd delay the actual execution until after the updates are completed. Here is [an updated version](https://stackblitz.com/edit/angular-z2rsfa?file=src%2Fapp%2Ftest-control-value-accessor.ts) of your example code.

Thank you.
