### ISSUE TITLE
Angular2 Injectors errors

### ISSUE THREAD

**Issue by talgleichger** [angular/angular#4240]
When trying to inject a service, with "viewInjector" or others an error will occur that isn't in the right context. I.e: 

EXCEPTION: No provider for ngService

But when changing to "bindings" i.e
```
@Component({
    selector: "home"
    bindings: [ngService]
})
```

It will work like a charm, but on the documentation there are no explanation for the differences or which one is deprecated.

**Comment by gdi2290** [comment]
"viewInjector" was renamed to "viewBindings"
"hostInjector" was renamed to "bindings"
"appInjector" was removed in favor of bootstrap's appInjector

are you referring to the documentation on angular.io or in the source code? if on angular.io then the website is outdated still

**Comment by pkozlowski-opensource** [comment]
@gdi2290 this issue is more about error messages that we are getting here - we should try to improve those if possible

**Comment by PascalPrecht** [comment]
@pkozlowski-opensource the error message sounds fine to me here. Due to @talgleichger using `viewInjector` which isn't a property on `@Component` configuration anymore, there's basically no binding for `ngService` which means Angular can't find a provider.

@talgleichger as @gdi2290 `viewInjector` is `viewBindings` now. If you want an explanation of why `bindings` and `viewBindings`, you might want to read this http://blog.thoughtram.io/angular/2015/08/20/host-and-visibility-in-angular-2-dependency-injection.html

You basically configure the visibility of your bindings in your injector tree.

**Comment by pkozlowski-opensource** [comment]
@gdi2290 @PascalPrecht all you are saying is true and the crux here is not to solve the pb but rather provide an error msg that can be understood by a newbie in like 30 secs max. For me a message like 

> Unknown property `viewInjector` of the `@Component` decorator. Available properties are: ...

**Comment by jomeier** [comment]
@pkozlowski-opensource: +1

**Comment by mhevery** [comment]
TypeScript v1.6 will solve this issue.
