### ISSUE TITLE
Broken error message when ng-for and ng-if are on the same element

### ISSUE THREAD

**Issue by IgorMinar** [angular/angular#4246]
see: http://plnkr.co/edit/FnmjWBd6flYiyUTkXuTs?p=preview

```
EXCEPTION: Only one template directive per element is allowed: ng-if true and ng-for cannot be used simultaneously in null
...
EXCEPTION: TypeError: Cannot read property 'elementBinders' of undefined
```

- why do we print `ng-if true` rather than just `ng-if`
- why is there `null` at the end of error message?
- what's up the second `elementBinders` exception?

**Comment by pkozlowski-opensource** [comment]
* "why do we print ng-if true rather than just ng-if" => sent a PR #4249 to fix it
* "why is there null at the end of error message?" => duplicate of #3506 (even if doesn't look like it at the first sight, it has the same root cause)

"what's up the second elementBinders exception?" remains to be investigated.

**Comment by vicb** [comment]
fixed in master
