### ISSUE TITLE
Named RouterOutlets don't appear to work when they are inside a subcomponent

### ISSUE THREAD

**Issue by cholt0425** [angular/angular#42483]
# Bug Report

### Affected Package
{
  "name": "angular",
  "version": "0.0.0",
  "private": true,
  "dependencies": {
    "@angular/animations": "^11.0.8",
    "@angular/common": "^11.0.8",
    "@angular/compiler": "^11.0.8",
    "@angular/core": "^11.0.8",
    "@angular/forms": "^11.0.8",
    "@angular/platform-browser": "^11.0.8",
    "@angular/platform-browser-dynamic": "^11.0.8",
    "@angular/router": "^11.0.8",
    "rxjs": "^6.6.3",
    "tslib": "^2.1.0",
    "zone.js": "^0.11.3"
  },
  "scripts": {
    "ng": "ng",
    "start": "ng serve",
    "build": "ng build",
    "test": "ng test",
    "lint": "ng lint",
    "e2e": "ng e2e"
  },
  "devDependencies": {
    "@angular-devkit/build-angular": "~0.1100.4",
    "@angular/cli": "~11.0.4",
    "@angular/compiler-cli": "~11.0.4",
    "@types/jasmine": "~3.6.0",
    "@types/node": "^12.11.1",
    "codelyzer": "^6.0.0",
    "jasmine-core": "~3.6.0",
    "jasmine-spec-reporter": "~5.0.0",
    "karma": "~5.1.0",
    "karma-chrome-launcher": "~3.1.0",
    "karma-coverage": "~2.0.3",
    "karma-jasmine": "~4.0.0",
    "karma-jasmine-html-reporter": "^1.5.0",
    "protractor": "~7.0.0",
    "ts-node": "~8.3.0",
    "tslint": "~6.1.0",
    "typescript": "~4.0.2"
  }
}

### Is this a regression?
Not sure

### Description
If you create a named router outlet in a subcomponent (not app.component) it fails to operate when routes are directed at it.

## Minimal Reproduction
[https://angular-ivy-tyw9hr.stackblitz.io](url)

The example shows that named routes work as long as the named route-outlet is in the main app.component.  Otherwise, they do not.

## Exception or Error
No error occurs and the route is matched properly.  However, the component just doesn't show up in the browser.

## Your Environment

**Angular Version:**
Version 11 in StackBlitz demonstrates the issue.  See reproduction step.

**Anything else relevant?**
This behavior seems to be consistent across Chrome.  I have not tried other browsers.

**Comment by atscott** [comment]
This is working as expected. There are a couple issues with the route configuration:

* The `router-outlet` named `subOutlet` is in the component `PrimaryComponentComponent` that is part of the activated primary route. This means that `subOutlet` has to be activated through the `children` of the route for `PrimaryComponentComponent`.
* Your `PrimaryComponentRoutingModule` defines `forChild` routes but the module isn't loaded in a `loadChildren`. This means that its routes will simply be appended to the root level routes. 
* This isn't going to work for the `**` route because the wildcard fallback effectively consumes all the remaining segments and does not allow for `children` or `loadChildren` with additional routes.

Here's a demo with an example of a correct configuration: https://stackblitz.com/edit/angular-ivy-qcvanr?file=src%2Fapp%2Fapp.routing.ts. This could also be modified to move the children of `path: 'sub',` to the child module and change that config in the root to be `path: 'sub', loadChildren: () => import...`
