### ISSUE TITLE
Pipe "keyvalue" should not sort by default.

### ISSUE THREAD

**Issue by y0nd0** [angular/angular#42490]
# Issue / Improvement / Feature Request

### Relevant Package
`@angular/common` ([source](https://github.com/angular/angular/blob/master/packages/common/src/pipes/keyvalue_pipe.ts))

### Description
Currently the `keyvalue` pipe sorts the keys. This result in e.g. 

```text
1, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 2, 20, 21, ...
```

Because it's not natual sorted. ...

### Describe the solution you'd like
 It should not sort by default. Respect the original object state.
It's annoying to declare a no sort method to each component which uses keyvalue. (function that returns `0` for no sort.)

### Describe alternatives you've considered
Provide predefined sort functions. The parameter of `keyvalue` could be a string or function. The string is the name of the predefined buildin function of Angular. Like: 

```js
keyvalue: 'natural'
keyvalue: 'sort' // the current sort behavior
keyvalue: mySort // a custom function
keyvalue // default no parameter, no sort.
```

Or we could invert the logic so that no parameter means the current behvaior but `keyvalue: 'none'` disables the sort. For downwards compatibility. If you care about. But in my opinion we should ignore that. A tiny breaking change. The migration is simple: Just add `'sort'` to the keyvalue pipe. So I still prefer my solution: Don't sort by default.

**Comment by splincode** [comment]
@y0nd0 

![image](https://user-images.githubusercontent.com/12021443/120930062-5c6e8980-c6f4-11eb-909b-4403206a11c1.png)

You can use function references for your own sorting types

![image](https://user-images.githubusercontent.com/12021443/120930084-76a86780-c6f4-11eb-8f8e-51f848493302.png)

**Comment by mlc-mlapis** [comment]
@splincode Yep, it's elegant but still, it means about one sorting phase more than necessary.

**Comment by y0nd0** [comment]
Interesting solution with the natural sorting with "modern" built in stuff. Thanks for that. Seriously nice input.

But note that this issue is about using `keyvalue` without any setup. Means no custom implementation to disable or change the default sort behavior. 

This pipe should not sort by default. It should just use the object as it is. 
I wonder, why did the Angular team or collaborators decided to automatically sort the keys?
It's easier not to sort anything. ...

The icing on the cake, the `keyvalue` pipe could provide some preset sort like in my initial post described. 
We could use your solution with `Intl` for the `keyvalue: 'natural'` solution. Or just set `keyvalue: 'sort'` and use the natural sorter (if supported, fallback the simple sort). Zero setup. No additional stuff needed for that. Because in the most cases, we don't want that `keyvalue` sorts the object. It's really annoying to add a compare function that returns zero `0` or whatever to disable the default behavior of this pipe. ... Or is there an advantage that I didn't see?

So the simplest solution is to remove the default sort. And optional work: Accept a string as argument for a built-in compare function.

Example:

```html
<!-- No sort (only the JS behavior for objects.) -->
<div *ngFor="let item of items | keyvalue">
  <pre>item | json</pre>
</div>

<!-- Angular sort. (The current default behavior or 'natrual' sort?) -->
<div *ngFor="let item of items | keyvalue: 'sort'">
  <pre>item | json</pre>
</div>

<!-- Custom compare function. (Like already possible.) -->
<div *ngFor="let item of items | keyvalue: mySort">
  <pre>item | json</pre>
</div>
```

I would prefer to just remove the default sort and not replace by a more complex sorter (natrual sort). Because for performance reasons. The developer should be explicit enable the sort. It would be very comfortable if the pipe also accepts a string. The name of the Angular built-in compare function.
For the very first step the keyvalue pipe could just evaluate the parameter as boolean and use the [defaultComparator](https://github.com/angular/angular/blob/master/packages/common/src/pipes/keyvalue_pipe.ts#L106-L131). But keep allowing to pass a custom comparator. 

I hope I was able to explain my issue in an understandable way. English is not my main language. So please just ask if something is unclear. 🙂

**Comment by petebacondarwin** [comment]
I believe that this behaviour goes back to the early days when different JS engines iterated over object keys in a non-deterministic order.

**Comment by dario-piotrowicz** [comment]
That's an interesting aspect I hadn't considered :)

Based on that, I don't believe that the order of the iteration of object keys is in the ecmascript specs is it?

If it's not, then would not be safer to not make assumptions around the JS engine and just assume that a non-deterministic order is possible?

**Comment by mlc-mlapis** [comment]
https://stackoverflow.com/questions/30076219/does-es6-introduce-a-well-defined-order-of-enumeration-for-object-properties

**Comment by dario-piotrowicz** [comment]
Thanks @mlc-mlapis good to know, sorry for making a wrong assumption, thanks for your input

**Comment by JoostK** [comment]
The sorting behavior of Maps is tracked #31420.

**Comment by petebacondarwin** [comment]
The proposal for this is to add a `null` value for the `compareFn` which indicates "no sort".
Changing the default would be a big breaking change, which we don't want.

**Comment by petebacondarwin** [comment]
Let's track this in the older issue: #31420.

**Comment by infacto** [comment]
You really want a default behavior like this?

```ts
import { Component } from '@angular/core';

@Component({
  selector: 'my-app',
  template: `
    <div *ngFor="let item of (items | keyvalue)">
      {{ item.key }}
    </div>
  `
})
export class AppComponent {
  items = {
    one: 'one',
    two: 'two',
    three: 'three',
    0: '0',
    1: '1',
    2: '2',
    10: '10'
  };
}
```

Result:

```text
0
1
10
2
one
three
two
```

I really doubt anyone will miss that.

**Comment by mlc-mlapis** [comment]
@infacto But the key point is to get the best performance on already pre-sorted maps.

**Comment by infacto** [comment]
I don't understand. Why is the current sorting for best performance on already pre-sorted maps? I would expect a non-sort behavior is for the best performance. Keep the default sort like it is. Don't touch the object / order.

**Comment by infacto** [comment]
Ok I can live this:

```html
<div *ngFor="let item of items | keyvalue: null">{{ item.key }}</div>
```

But I still don't understand why you stick to the bad default sorting behavior. The votes speak for this change. What benefits has the current sort behavior?

**Comment by mlc-mlapis** [comment]
@infacto Yep. It's all about it. Introducing `null` as the optional value of `compareFn` will do it. The rest is simply about not introducing a serious breaking change.

> Don't touch the object / order.

So, it's now: Don't touch the map object and use its default sorting.

**Comment by petebacondarwin** [comment]
I agree that if we were to implement this pipe from scratch now then we would have no-sort as the default.
The problem with changing to that now is that it is a breaking change.

That being said, I was thinking about this a bit more, and I think we could write a migration that would mitigate the breaking change:

- publicly expose the current default `compareFn`
- find all usage of `keyvalue` pipe in templates, where the `compareFn` option is not specified
- add in the default `compareFn` to each of these instance

As a breaking change this would need to land in a major version (e.g. 13.0.0 or 14.0.0). I am not sure that we have time to achieve this goal for 13.0.0. So the compromise of introducing `null` as a configuration option would at least unblock developers from getting access to the original sort order, and can be landing in any minor version (e.g. 13.0.0, 13.1.0, etc).

We could land that as an interim step, and the look at switching the default to `null` in a later major version.

How does that sound?

**Comment by infacto** [comment]
But [Map](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Map) or simple object has no difference. Both will sort like in my prev example [post](https://github.com/angular/angular/issues/42490#issuecomment-920707569). So keeping the default sort will touch the order. Also for Maps.

**Comment by petebacondarwin** [comment]
And to avoid confusion, I think that this issue better captures what we want to achieve. So I am actually going to reopen this issue and close the other one!

**Comment by infacto** [comment]
Thanks, I really think that keeping the original order is what the most user expects for its objects (incl. Maps etc). Especially for already sorted objects. ...

Btw. the initial post of this issue suggested some predefined sorts which are set as name (string) like:

> ```js
> keyvalue: 'natural'
> keyvalue: 'sort' // the current sort behavior
> keyvalue: mySort // a custom function
> keyvalue // default no parameter, no sort.
> ```

What do you think about that? It's easier as creating a new property (mySort) to the Component class.
So the migration is just: `keyvalue` > `keyvalue:'sort'`. It's about less code and work as possible (incl. DRY).

Or what do you mean with: 
> add in the default compareFn to each of these instance

Because currently you need to set a sort function to it, which needs to be a property of the Component class. It's a bit more complicated as just adding `keyvalue: 'sort'` (predefined option).
We could split the pipes in `sortedkeyvalues` (btw. why not camelCase `keyValue` if adding more words ^^) and `keyvalue`.

I would be interested in how many even notice that change. I doubt that someone likes the default sort behavior. 
The best solution is to keep it simple on both sides... Just some loud thoughts.

**Comment by petebacondarwin** [comment]
I am not in favour of having "predefined" `compareFn`s that are mapped to string identifiers.
But I had forgotten that in order to pass the `compareFn` to the pipe it needs to be a property on the component...
The migration is still possible but it would add boilerplate to the component classes...

**Comment by mlc-mlapis** [comment]
@petebacondarwin The `compareFn` is optional. Do you think it's impossible to extend the design and also accept the `null` value and not only a function? It would eliminate the necessity of adding class property in each place.

**Comment by petebacondarwin** [comment]
It depends upon what `null` refers to... If `null` means "no sort", then we can add that right now, without a breaking change and with no migration.

If we want a way to change the default sorting, then we could consider that `null` is the "default sort". Then the migration would once again be trivial (just adding the `null` everywhere). But this feels awkward since `null` does not intuitively map to "sort alphabetically".

We could "possibly" have a compromise, which is that `compareFn` could be one of `Function|undefined|'lexical'`, which introduces a single string based identifier but only to help with the this backward compatibility. But I would definitely not like to add further string based sorts...

**Comment by infacto** [comment]
Note that `keyvalue: null` is already possible. This is the current easy workaround for this issue. (Tested in Angular 11+). No changes needed, right? It's only about the default behavior. The sort is just annoying / unexpected and adding `null` every time to fix a weird behavior is also not the best solution in my opinion.

Some possible solutions: 

**a)** Just remove the sort and do nothing further. Don't care about... I don't think that someone cares about this "breaking change". Do someone requires this sort behavior?

**b)** Allow `keyvalue: 'sort'` (or something like this) to easily allow sorted keys. But again the current (non-natural) sort is not really good. Is someone here how like this?

**c)** Add a new derived pipe like `sortedKeyValue`. The user could also wrap it in a new pipe. But this issue is also about avoiding additional code for such basic pipes.

**d)** Drop this. Just use `keyvalue: null` which already works, right? Looks ugly and might confuse until you study it but it works.

**e)** Set the default behavior globally. Set a compareFn globally for all keyvalues.

**f)** Any other solution? Ideas are welcome.

I would not use `null` for sort. Then rather `'sort'` or `true` as value. I prefer **a)** or **b)**. Or just **d)** as good to know? (Should be added to the docs.)

In a real world application we would use a natural sort fn. ... I also would prefer to configure the keyvalue with options like `'sort'` like described above. Instead of adding a compareFn in every component. Maybe the solution **e)** is a good solution to avoid code (DRY).

**Comment by infacto** [comment]
Ah ok. 😄 Indeed:

>  Caught unhandled error: TypeError: The comparison function must be either a function or undefined

Then we should handle it if we want this. But do we want `null` as valid value to disable it? Since `undefined` enables the default sort. Both nullish values. Hmm... 🤔

**Comment by mlc-mlapis** [comment]
From the sort point of view, the' null' value looks fine in the sense of **don't apply any rule**.

**Comment by petebacondarwin** [comment]
I think that semantically:

- `undefined` -> do the default sort
- `null` - do no sorting

works for me.

I feel that this is the right first step.
Then we can look into making no sort the default and how we would migrate people who want the current default sort.

**Comment by infacto** [comment]
Bump

**Comment by guptmay02** [comment]
Works well in Firefox and Chrome with this solution,

```HTML
<li *ngFor="let category of healthCategoriesMap | keyvalue: asIsOrder; let i=index"></li>
```

```JS
/*
   * This is used to override the default comparator function of keyvalue pipe in angular - https://angular.io/api/common/KeyValuePipe 
   */
  asIsOrder() {
    return 0;
  }
```

**Comment by marin-takanov-maersk** [comment]
I'm using Angular 16 and this is still an issue. I've implemented the `asIsOrder` solution in order to preserve the key order of `Map`. Can anyone from the Angular team look at this?

**Comment by isbullaml** [comment]
> I'm using Angular 16 and this is still an issue (more than 2 years now). I've implemented the `asIsOrder` solution in order to preserve the key order of `Map`. Can anyone from the Angular team look at this?

Same here

**Comment by twoco** [comment]
I would also rather use ˋnullˋ than add an unnecessary method to my component. I think it‘s a harmless implementation.

**Comment by passee** [comment]
What is the current status here?
Looks like this still doesnt work in 2024, Angular 18...

**Comment by passee** [comment]
> ```js
> /*
>    * This is used to override the default comparator function of keyvalue pipe in angular - https://angular.io/api/common/KeyValuePipe 
>    */
>   asIsOrder() {
>     return 0;
>   }
> ```

You are returning 0, another user before wrote return 1. Which one is correct, do both work or whats the difference?

**Comment by jonaskuske** [comment]
> You are returning 0, another user before wrote return 1. Which one is correct, do both work or whats the difference?

Zero (or NaN) should be correct:
![image](https://github.com/user-attachments/assets/b2fb54df-94a7-451d-a707-2df4bc5d0118)
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/sort#parameters

**Comment by JeanMeche** [comment]
For the same reason the `track` option of `ngFor` couldn't accept a key string, it is not possible to have a string for `keyvalue . This is because some manglers can aggressively change key names, so that wouldn't be safe to do. 

But I could see adding `null` to the typings to disable the default sorting.

**Comment by sbarfurth** [comment]
I created a PR with the `null` typing. Seems like a fairly simple, backward compatible change that should make using the pipe easier in many cases.

We also have quite a few places where we added a `compareFn` to keep natural sorting so this will also make our lives easier.

**Comment by sbarfurth** [comment]
My PR that allows using `null` to disable sorting is merged. While I still agree that no sorting by default seems sensible, this now makes it super easy to disable the default key sorting.

**Comment by JeanMeche** [comment]
Changing the default will too much of a churn, now that we have an acceptable alternative (in v19), we can close this.
