### ISSUE TITLE
More details for for one of the steps in update angular from 11 to 12

### ISSUE THREAD

**Issue by ofirrifo** [angular/angular#42498]
# Docs or angular.io Bug Report

### Description

I'm working on upgrade an angular project from version 11 to 12.
I'm using this [Angular Update Guide](https://update.angular.io/?l=3&v=11.0-12.0)
There is one step which I don't understand what does it mean and should I check it.

The step
```
Make sure you don't rely on Angular's UMD bundles in your build pipeline because they will no longer be part of the v12 distribution.
```

Does it relevant to third party I'm consuming for example lodash  as use theme in the `ng-package.json` under `umdModuleIds`

**Comment by JoostK** [comment]
Thanks for reporting. That step is actually incorrect by itself, as mentioned in #42081. Only minified UMD bundles are removed in Angular 12.

FYI, the UMD bundles allow using Angular and other packages with just `<script>` includes, instead of relying on a separate compilation step that bundles an app and the packages it depends on together; this is taken care of by the CLI. You are very likely not using the minified UMD bundles, so you can ignore this step.

I'm closing this as fixing the message itself is covered by #42081.
