### ISSUE TITLE
Website angular.io not responding

### ISSUE THREAD

**Issue by Vevl** [angular/angular#42518]
I'm just referring to a closed bug with some answers:

Unfortunately, there is not much we can do without more concrete info (or a repro).

However, I would very much like to get to the bottom of such issues (which are potentially related to #28114). In fact, we just recently put [code in place][1] to print more debug info to help diagnose similar problems.

So, if you run into this again, please open a new issue and provide as much info as possible, such as:
- any console logs
  ![Log errors](https://user-images.githubusercontent.com/35180926/121203188-35d85c00-c876-11eb-9622-999ecb3bd2a0.png)

- any error stack traces
  ![Network cache error](https://user-images.githubusercontent.com/35180926/121203403-5b656580-c876-11eb-95da-e4da8d7b2a43.png)

- what actions led to the problem:
    - Did you have other tabs open on angular.io?
      - It's not happening when another angular.io tab is open
    - If not, how long ago had you visited angular.io?
      - Time plays no role in this case
    - How did you try to navigate to the failing page (google search, link from a different page, link in angular.io, navigation on the same tab or opening a new tab, etc.)?
      - This problem happens whenever I open a link from google search response (I'm not sure about other use-cases)
      - Same tab or new tab it doesn't matter also happens when trying to open it by PWA

I'm able to reproduce this a bunch of times in a row and after a while, it's not happening. I was also trying other browsers but everything works just fine now. Actually, I'm primary using `Chrome v93.0.4530.5 dev`.
One interesting thing on it, sometimes when I leave this not responding page alone, after a while its reload correctly.

I have been encountering this problem for about 3-4 months.

-------------------
I think this isn't a bug on Angular team site, it's probably bound to **Chrome dev**. Because I've encountered it again and try it out in Chrome and it works like a charm.

[1]: https://github.com/angular/angular/blob/5eb7f3491f37a8f71717525b0d0e901c00a8c4e8/aio/src/app/layout/doc-viewer/doc-viewer.component.ts#L257-L314

_Originally posted by @gkalpak in https://github.com/angular/angular/issues/41301#issuecomment-803958798_

**Comment by gkalpak** [comment]
Thx for reporting this, @Vevl! The issue seems to be caused by a bug in Firebase hosting:

When `cleanUrls` is set to `true` in the hosting configuration in `firebase.json`, it seems that Firebase hosting implicitly redirects `/index.html` and `/index` to `/`. This works fine when there is no query in the URL: The request returns a 301 response with the `Location` header set to `/`.

However, when there is a query in the URL (for example, `/index.html?foo` or `/index?foo`), an infinite redirect occurs. The 301 response returned by Firebase has a `Location` header set to `?foo` (instead of `/?foo`). This is then resolved relative to the request URL, which results in the same URL, thus leading to the an infinite redirect (until the browser errors with a "TOO MANY REDIRECTS" error).

I have reported this to Firebase, but in the meantime I will send a PR with a temporary workaround.

**Comment by gkalpak** [comment]
OOC, does this still happen if you clear all site data for angular.io in `DevTools > Application > Storage`, @Vevl?

**Comment by Vevl** [comment]
@gkalpak it seems okay now, I will let you know if I notice something.
