### ISSUE TITLE
Introduce ChangeDetectionStrategy.OnWatch and @Watch() annotation

### ISSUE THREAD

**Issue by QuentinSup** [angular/angular#42591]
I use Angular for years with complex applications, and i've still troubles with performance on big page with many components !
I'm aware with usual tricks (ChangeDetector, trackBy, mutability, etc..), but it's not enough. To my mind, it's the limit of Angular and i'm asking to myself to better use VueJS or React (what a shame).

I think that actual Change Detection Strategies are not enough and we should go further.
I think that global strategy is good, but we should be able to be more specific on wich property should be watched (and maybe set a different strategy for each property should be better). Because on complex object, we need to use properties for private and local use only, and there is no needto watch them).

My proposal : 
- Introduce ChangeDetectionStrategy.OnWatch : when set, we need to set manually if a property must be watched or not (by default, same behavior as default, but do not watch all properties of the components to detect changes).
- Add new Watch() annotation which can be used on class properties. For complex object, maybe a 'deep' attribute can be used to define if only the ref should be watched, or all the properties of the object property).

This way is similar to OnPush Strategy / @Input() annotation, but introduce more flexibility (to my mind), and prevent Angular to trigger detect changes for everything if not needed.

**Comment by flash-me** [comment]
Couldn’t this accomplished by detaching the component and manually triggering change detection in combination with setter properties?

**Comment by QuentinSup** [comment]
Obviously, but you also replace OnPush strategy by detach() and trigging change detection in combination with @Input setter properties :)

It just more complex and complicated to do, and you can also miss something.

My point is that un a class component, by default all the properties are watched and that's cool for small component. But in complex application, you need to manage work or cache properties : imagine that you update a large deep object => you don't wan't to change all the detect change strategy of your component for this. The best way is to exclude it from Angular detect change (black list of watching, or as suggested a white list of property to watch using @Watch annotation).

**Comment by flash-me** [comment]
Another options are running stuff outside of Zone.js or splitting the component â la divide and conquery. Latter one introduces overhead through additional hierarchies, though... 

But I get your point. Somehow interested in what the responses are :) 

cheers
flash ⚡

**Comment by bryanrideshark** [comment]
I think this is in line with the request to support Observables as @Input properties. Recently that was closed due to not wanting to introduce a dependency on rxjs (???????) but let's not bring that can of worms back up.


Essentially, you're wanting the change detection strategy to be made more granular, down to an individual input level. Not a bad idea but the behavior has to be explicitly defined. Probably would need a new type of observable property to be defined.

**Comment by QuentinSup** [comment]
Here an example of what I'm thinking :

```javascript
@Component
export class standardClass {

// Input var
@Input text: string

// model var : use internally only
modelValue: Model[] = [];

// typical internal and private property only
__handleTimeout: number;

}
```

By default, each time I change text, modelValue, or __handleTimeout, it will trigger change detection for each component of the three.

But I dont wan't trigger it for __handleTimeout (for example), so the only solution is to switch change detection strategy to OnPush.

```javascript
@Component({
    changeDetection: ChangeDetectionStrategy.OnPush,
})
class standardClass {

// Input var
@Input text: string

// model var : use internally only
modelValue: Model[] = [];

// typical internal and private property only
__handleTimeout: number;

}
```

From now, each time I change text, it will still trigger change detection for each component of the three. But not for modelValue and __handleTimeout. But to trigger change detection when updating modelValue, I will need to use manually cd.detechChanges() each time I need it...

I could add @Input to modelValue, but this is not something I wan't to use in this case, because I dont wan't that property to be showed as an input value.

**Suggested solution**

```javascript
@Component({
    changeDetection: ChangeDetectionStrategy.OnWatch,
})
class standardClass {

// Input var
@Input text: string

// model var : use internally only
@Watch modelValue: Model[] = [];

// typical internal and private property only
__handleTimeout: number;

}
```

So now, text behaviour is still the same (watched by default, so no need to add @Watch), modelValue will also have the same behaviour in the detection change strategy (except It will not be showed as an input available value for the component), and __handleTimeout will not trigger any change detection !

**It is a simple example, but imagine the gain of time detection with complex class, with dozen properties, inputs, outputs, cached property values, function handlers, etc...**

**Comment by bryanrideshark** [comment]
Will your @Watch() property be overriding the getters and setters and introducing a hidden private backing field?

I imagine that is what it would be doing.

I have done something similar with the following in-house decorator:


````
@ObservablePropertyAccessor({
    makeUnderlyingObservablePublic: true
  })
  private _prop$ = new BehaviorSubject<T | null>(
    null
  );
  prop$: Observable<T | null>;
  prop: T | null;
````

In this case, I am automatically creating the getter and setter, as well as a getter for the observable, off of a BehaviorSubject.

I think the best behavior for @Watch(), would be to automatically wire an Observable (or EventEmitter, I understand Angular and rxjs aren't friends anymore? What is this nonsense) to the Change Detector Ref.  So, then my code would transform to this:


````
@ObservablePropertyAccessor({
    makeUnderlyingObservablePublic: true
  })
  private _prop$ = new BehaviorSubject<T | null>(
    null
  );
  @Watch()
  prop$: Observable<T | null>;
  prop: T | null;

````

What do we think about that proposal?

**Comment by alxhub** [comment]
This is a very interesting idea, and sparked some great discussions at our feature request review.

I want to clarify one point above:

> Here an example of what I'm thinking :
> 
> ```js
> @Component
> export class standardClass {
> 
> // Input var
> @Input text: string
> 
> // model var : use internally only
> modelValue: Model[] = [];
> 
> // typical internal and private property only
> __handleTimeout: number;
> 
> }
> ```
> 
> By default, each time I change text, modelValue, or __handleTimeout, it will trigger change detection for each component of the three.
> 

This is a bit confused - change detection doesn't watch component fields (even `@Input`s) at all, only expressions within the template. Each CD pass, those expressions are evaluated (which might involve reading from the component's properties) and any required updates are written into the inputs, DOM properties, etc. specified in the bindings.

When we discuss the mechanics of change detection, we tend to focus on two fundamental questions, the combination of which determines how change detection works overall:

1. What triggers a change detection pass to run in the application?
2. Which parts of the application are checked as a result of that pass running?

Currently, the answer to question 1 is zone.js. zone.js sits between your application and the browser, and whenever an event occurs (button click, HTTP response, etc), zone.js fires an event to Angular, and Angular schedules a new change detection pass.

Question 2's answer is a little more complicated, since components can declare themselves to be `OnPush` and opt out of checking by default. `OnPush` components and their descendants are left out of change detection passes by default. They must explicitly be "marked" for checking, and then they'll be checked in the next pass. This marking can happen in one of a few ways:

* If a binding to an `OnPush` component's input is changed, that component will be marked for checking, and the change detection pass will descend into the `OnPush` component.
* A DOM event firing within a component's template will mark that component and all of its ancestors for checking.
* A component can be manually marked, via the `ChangeDetectorRef.markForCheck()` API. This is why `AsyncPipe` bindings in `OnPush` components still update the template - when the monitored `Observable` emits, the `AsyncPipe` will mark its host component for checking.

Our current roadmap involves the exploration of question 1 in more detail - what would it look like if zone.js is not the driver (or maybe not the only driver) of change detection? Ideas like `@Watch` are very interesting in this context, but because we don't intend to implement this proposal as described, I'm going to go ahead and close it out.
