### ISSUE TITLE
Wrong selected item in navigation sidebar

### ISSUE THREAD

**Issue by looshch** [angular/angular#42652]
# Docs or angular.io Bug Report

### Description

When you click on `Understanding Angular — Components — Sharing data between child and parent directives and components` in navigation sidebar, another item gets selected: `Understanding Angular — Templates — Inputs and Outputs`.
Both of them are linked to the same page. Should the item highlighting logic be re-designed or is there any error?

## Minimal Reproduction

https://angular.io/guide/inputs-outputs

### What's the affected URL?

https://angular.io/guide/inputs-outputs

### Reproduction Steps

1. Open https://angular.io/guide/inputs-outputs
1. Look at the navigation sidebar selected item

### Expected vs Actual Behavior

EB: `Sharing data between child and parent directives and components` is selected
AB:  `Inputs and Outputs` is selected

## Screenshot

<img width="650" src="https://user-images.githubusercontent.com/45432373/123308508-6b46a000-d52c-11eb-8a91-ec2c54e1d7d9.png">

### Anything else relevant?

The bug was introduced by #39170, maybe #39119 is relevant, too

**Comment by gkalpak** [comment]
Thx for reporting this, @looshch :+1:

It seems indeed that we have to sidenav entries that point to the same guide: [here][1] and [there][2]
(This was indeed introduced in #39170.)

I can't be sure whether this change was intentional in #39170 or not. I'll let the docs team decide which entry we want to keep.
(BTW, the angular.io app does not currently support that having two entries point to the same guide. If we really need that, we need to add support for it in the app.)

[1]: https://github.com/angular/angular/blob/4e46aef17bc21489863aeee32294a1a12263cc17/aio/content/navigation.json#L135
[2]: https://github.com/angular/angular/blob/4e46aef17bc21489863aeee32294a1a12263cc17/aio/content/navigation.json#L206

**Comment by looshch** [comment]
ok, thanks!

wanted to make my first contribution but it seems like not today. Better luck next time

**Comment by gkalpak** [comment]
The simplest fix would be to remove on of the two entries from `navigation.json` (see my previous commnetn).
You are more than welcome to submit a PR for this, @looshch. (Just pick one of the two entries to remove - worst case scenario, a reviewer will request that you remove the other one :grin:)

**Comment by looshch** [comment]
yeah, I thought about the worst case too but tried to get the answer beforehand

thanks, I’m on it
