### ISSUE TITLE
Entering invalid value in template drive form showing valid status

### ISSUE THREAD

**Issue by ChellappanRajan** [angular/angular#42670]
# Bug Report

### Affected Package

 The issue is caused by package @angular/forms

### Is this a regression?
 No 

### Description 
  When we have min validator on input element and entering invalid character sets formControl valid status to true.

## Minimal Reproduction

 Reproduction
https://stackblitz.com/edit/angular-ivy-g1zbbb?file=src/app/app.component.html

## Your Environment

**Angular Version:**
<pre>Angular: 12<code>

**Comment by jnizet** [comment]
This looks correct to me. `1-` is not a number and you have an input of type number. So the value of the control is not a number: it's `null`. So it's neither greater nor lower than 5: there is no value at all. If you want such an absence of value to make the control invalid, then the `required` validator should be added to the control.

**Comment by ChellappanRajan** [comment]
Thanks @jnizet adding required working as expected. But Why there is difference in DOM state and formControl object state?

**Comment by jnizet** [comment]
The browser input needs you let type invalid stuff for example, because to be able to type the valid number -1, you need to first type `-`, which is not a valid number). 
The Angular form control works at a higher level: since it's bound to an input of type number, it know that what you want is a number, not a string. So every string that isn't a valid number is turned into a null value.
The DOM API is quite close to what Angular does, BTW, the HtmlInputElement's value, when you type `-` or `1-` is not `'-'` of. `'1-'`: it's the empty string.

**Comment by ChellappanRajan** [comment]
Thanks @jnizet . If this is expected behavior please feel free to close the issue.
