### ISSUE TITLE
Array sorting combined with animation trigger results in broken state

### ISSUE THREAD

**Issue by brianmtreese** [angular/angular#42750]
# Bug Report

### Affected Package
@angular/animations

### Is this a regression?
Not that I know of

### Description
When using `*ngFor` to loop over an array of objects, if those items contain conditional elements that have animation triggers on them, they will be in a broken state after triggering a sort on the array. In the example included below, you can see that if you trigger a sort on the array and then try to trigger the conditional mark up in the list items by clicking on them, you can see the content in both the "if" and "else" templates. This appears to be caused simply by adding an animation trigger to the conditional elements.

## Minimal Reproduction
https://stackblitz.com/edit/array-sort-animation-bug?file=src/app/app.component.ts

## Your Environment

**Angular Version:**
<pre><code>Angular CLI: 12.0.2
Node: 14.17.0
Package Manager: yarn 1.22.5
OS: win32 x64

Angular: 12.0.2
... animations, cdk, cli, common, compiler, compiler-cli, core
... forms, language-service, localize, platform-browser
... platform-browser-dynamic, platform-server, router
... service-worker

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1200.2
@angular-devkit/build-angular   12.0.2
@angular-devkit/core            12.0.2
@angular-devkit/schematics      12.0.0
@nguniversal/builders           12.0.1
@nguniversal/common             12.0.1
@nguniversal/express-engine     12.0.1
@schematics/angular             12.0.2
rxjs                            6.6.3
typescript                      4.2.4
</code></pre>

**Comment by paulinak-dev** [comment]
I handled this with adding void to my closed/folded state definition
state('closed, void', style({ overflow: 'hidden', opacity: 0, height: 0 }))

**Comment by dario-piotrowicz** [comment]
@brianmtreese I think you forgot to implement the `trackByFn` :slightly_smiling_face: 

I added it at the bottom of the `app.component.ts` file and it does fix the issue, check out my updated [stackblitz](https://stackblitz.com/edit/array-sort-animation-bug-8zkjur?file=src%2Fapp%2Fapp.component.ts) :slightly_smiling_face: 

I am not sure why (I can have a deeper look if you think it being necessary) but I guess that the combination of an untracked `*ngFor` with animations caused this bizarre behavior (probably the animations caused the modification/creation of nodes that you were loosing control over because of the lack to the `trackByFn`)

**Comment by petebacondarwin** [comment]
Closing as working as expected. The TrackByFn docs state:

> In all of these scenarios it is usually desirable to only update the DOM elements associated with the items affected by the change. This behavior is important to:
> * enable animation of item addition, removal, and iterable reordering

Perhaps the animations guides could be improved to highlight this requirement?
