### ISSUE TITLE
Provide image component similar to next/image

### ISSUE THREAD

**Issue by prabh-62** [angular/angular#42765]
# Feature Request

### Relevant Package
- @angular/image

### Description
> Since version 10.0.0, Next.js has a built-in Image Component and Automatic Image Optimization.
- [Next.js - Image Component](https://nextjs.org/docs/basic-features/image-optimization)

In Angular land, user has to first navigate to [squoosh.app](https://squoosh.app/) and shrink/resize the image before placing it under the `assets` folder

### Describe the solution you'd like
Provide an angular component for image optimization similar to [Next.js Image](https://nextjs.org/docs/api-reference/next/image)

### Describe alternatives you've considered
Manually optimize JPG/PNG/WebP images using [squoosh.app](https://squoosh.app/) and SVG using [SVGOMG](https://jakearchibald.github.io/svgomg/)

**Comment by splincode** [comment]
Maybe relate to `@angular/cdk/image`?

**Comment by flash-me** [comment]
> Maybe relate to `@angular/cdk/image`?

Yes or even `@angular/cli` because the optimization of `next/image` happens on service side with a node instance that serves the next app. It's not just a react component, there is more behind it.

For additional information: https://nextjs.org/docs/basic-features/image-optimization 

cheers
flash ⚡

**Comment by alan-agius4** [comment]
There are multiple aspects to this feature, how it works also dependent on which image providers are used. This is because certain image providers (CDN) offer image optimisations out-of-box.

1) When using one of the supported image providers, queries are added to the request, this is done so that the image is resized and optimised directly the provider. 
2) When the image is remotely stored but the provider is not supported during request time the the image is downloaded, optimized, cached and served.
3) When the image from the local FS, similar to remote images, during request time the the image is read, optimised, cached and served.

While the first can be archived using a purely client side component, The latter two would need to be handled during SSR.

**Comment by samuelfernandez** [comment]
I'd be happy to help in contributing this after a technical discussion

**Comment by conradkirschner** [comment]
@atscott Are here any updates?

**Comment by HamzaMoiyadi** [comment]
This would be a great feature to implement!
Any updates? Would love to contribute as well

**Comment by otodockal** [comment]
@HamzaMoiyadi @conradkirschner https://angular.io/guide/roadmap#improve-image-performance

**Comment by pkozlowski-opensource** [comment]
We do have [NgOptimizedImage](https://angular.io/guide/image-directive) directive starting from Angular 14.2
