### ISSUE TITLE
Async Pipe unexpected behaviour

### ISSUE THREAD

**Issue by AndreyChayko** [angular/angular#42774]
During coding some stuff regarding multiple nexts for Observable we found some unexpected behaviour for the async pipe.

When new values are produced inside subscribe there is a situation when controller state is not consistent with template

Consider the code.

Controller:

```
constructor() {
    this.count$.subscribe(val => console.log('subscribe', val));

    this.count$.pipe().subscribe((count: number) => {
      if (count % 5 < 4) {
        console.log('pipe', this.count$.value + 1);
        this.count$.next(count + 1);
      }
    });
  }
```

some click to perform next for counter:

```
 click() {
    console.log('onClick', this.count$.value + 1);

    this.count$.next(this.count$.value + 1);
  }

```

Template to render the value:

```
  <h1>
    Welcome to {{ count$ | async }}!
    <div *ngIf="count$ | async as cnt">{{cnt}}</div>
  </h1>
```

In such situation async pipe won't render the most recent value for view, first click will produce `5` for the view, but inside dev console I will see

`
onClick
5
subscribe
5
pipe
6
subscribe
6
pipe
7
subscribe
7
pipe
8
subscribe
8
pipe
9
subscribe
9
`

Which seems a kind of weird behaviour, but adding `debounceTime(1)` for `pipe` fixes the problem and the code starts working as expected, both controller and template will be in sync

Any clarifications here?

A live example could be found on [stackblitz](https://stackblitz.com/edit/angular-ivy-b8vnrr)

**Comment by JoostK** [comment]
This is due to subscription ordering: any subscriptions that are made after the subscription that nexts into the input Observables will replay the events in reverse order:

```ts
    this.count$.subscribe(val => console.log('subscribe before', val));

    //add debounceTime(1) to pipe to make it work in sync
    this.count$.subscribe((count: number) => {
      if (count % 5 < 4) {
        console.log('pipe', this.count$.value + 1);
        this.count$.next(count + 1);
      }
    });
    this.count$.subscribe(val => console.log('subscribe after', val));
```

<img width="131" alt="image" src="https://user-images.githubusercontent.com/123679/124482447-95f4ec00-dda9-11eb-8b84-d0ae3e9196c8.png">

This happens because observable pipelines are depth-first; later observers see a value after earlier observers. In this case, the earlier observers pushes a new value into the pipeline which will be handled by the later subscriptions before the outer emitter has notified all its observers of the incoming value. I realize that sentence probably makes little sense but it's tricky to explain what exactly is happening here.

In any case, this is unrelated to the async pipe so I'm closing this here, but feel free to continue the discussion below.

**Comment by AndreyChayko** [comment]
@JoostK thanks for the clarification, dude, so the original behaviour comes from RxJS as I understand. May be for better understanding I can debug source code from RxJS subscribe/next
