### ISSUE TITLE
docs-infra: make it obvious when content is overflowing horizontally

### ISSUE THREAD

**Issue by hssanbzlm** [angular/angular#42789]
In ng build documentation [ng build doc](https://angular.io/cli/build) in options, --output-hashing, docs mention only three values : none|all|media . Yet there is a fourth value which is bundles .

**Comment by petebacondarwin** [comment]
All four are actually there:

<img width="941" alt="Screenshot 2021-07-07 at 16 05 48" src="https://user-images.githubusercontent.com/15655/124783785-3a5b6780-df3d-11eb-8079-990883c55149.png">

But the last can be hidden by the table of contents on the right. (Try scrolling the contents section to the right).

I will tags this as a docs-infra bug, since we should wrap or make it more obvious if content is falling off the page like this.

**Comment by petebacondarwin** [comment]
Re-opening to track the docs-infra issue.

**Comment by iRealNirmal** [comment]
@petebacondarwin in case responsive right side bar is also overlapping, if that you think can be  covered together as well.
<img width="937" alt="Screenshot 2021-07-08 at 7 32 17 PM" src="https://user-images.githubusercontent.com/4091874/124935504-576a6600-e023-11eb-9711-dad9054eb435.png">

**Comment by gkalpak** [comment]
The overlap with the Table of Contents on the right will be fixed by #42884.
Leaving this open to track the issue of making it more obvious when there is content that is overflowing horizontally (although tbh I have no idea what is a good way to address that UX-wise 😅).
