### ISSUE TITLE
Angular router not working as expected with lazy loaded modules and auxiliary route outputs

### ISSUE THREAD

**Issue by jrdutton** [angular/angular#42793]
# Bug Report

### Description
 I am trying to get auxiliary route outputs working with lazy loaded modules and a relatively complex route configuration. I have attached an example that shows two four route endpoints, two with an id. Neither of these works as expected. In both cases, I am expecting the menu with id component to be displayed. In fact, one of them matches the menu without id, the other throws an error.

## Minimal Reproduction
 https://stackblitz.com/edit/github-z1qmq1

## Your Environment

**Angular Version:**
<pre><code>
Angular CLI: 12.1.1
Node: 14.17.0
Package Manager: npm 6.14.13
OS: win32 x64

Angular: 12.1.1
... animations, cli, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1201.1
@angular-devkit/build-angular   12.1.1
@angular-devkit/core            12.1.1
@angular-devkit/schematics      12.1.1
@schematics/angular             12.1.1
rxjs                            6.6.7
typescript                      4.3.5
</code></pre>

**Comment by atscott** [comment]
This appears to be working as expected. Your named outlet is nested under the primary so you need to write your link like this:
```
        [routerLink]="[
          {
            outlets: {
              primary: [
                'feature1',
                {
                  outlets: { primary: ['12345'], menu: ['123456'] }
                }
              ]
            }
          }
        ]"
```

As for the question about "one of them matches the menu without an id", this is because you have an empty path outlet configuration, so that's what's matching there:
```
      {
        path: "",
        component: Feature1MenuComponent,
        outlet: "menu"
      },
```

In the future, please first post your support requests on [StackOverflow](http://stackoverflow.com/) using tag `angular` until you have determined that it is a bug in the Angular code.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).

**Comment by jrdutton** [comment]
Thank you very much for your time in answering this.
