### ISSUE TITLE
Opening https://angular.io/api/forms/FormArray in firefox (89.0.2) hangs.

### ISSUE THREAD

**Issue by FrankL-git** [angular/angular#42836]
### Description

Opening the url above hangs. In the console an error is displayed:
`Uncaught SyntaxError: missing } after property list
note: { opened at line 1, column 6
`

### What is the affected URL?

see above

### Please provide the steps to reproduce the issue

Simply try to open the url in firefox. I tried version 89.0.2

### Is this a browser specific issue? If so, please specify the device, browser, and version.

```true
Yes it's specific for firefox. In chrome the url can be opened.
```

**Comment by gkalpak** [comment]
It works fine for me on Firefox 89.0.2 and 90.0 (on Windows). Can you make sure it is not an extension that is causing this error?
(I am going to close this, since there doesn't seem to be any issue on our side, but feel free to continue the discussion below (and I'd be happy to re-open and investigate if it turns out there is something we can fix on our side).)

**Comment by FrankL-git** [comment]
Thanks a lot for your hint. I had to qualify angular.io as "Trust site"  by ghostery, now it works.
