### ISSUE TITLE
Animations inside forms redirect if method does not return false

### ISSUE THREAD

**Issue by KrasnovR** [angular/angular#42850]
### Which @angular/* package(s) are the source of the bug?

animations

### Is this a regression?

No

### Description

I use primitive animation on ngif. The nuance is that if the animation contains state handling **':leave'** and the method is called inside the form, then after the animation is completed, there will be a redirect.

Example: 
**was** - localhost:123/hello
**became** - localhost:123/hello?

I tried to disable the parent ([@ .disabled] = "noAnimation") after the animation (@ firstForm.done) = "onAnimationDone ()", but that didn't help either.

If the method is called outside the form, then there will be no redirect.

**I also found that if in the method that is called inside the form, return false, then there will be no redirect**

In the example stackblitz, I created 2 forms for the test

### Please provide a link to a minimal reproduction of the bug

https://stackblitz.com/edit/angular-ivy-bs8pus

### Please provide the exception or error you saw

```true
I would like to understand if this is a bug or not, if not, why is this happening ?
```

### Please provide the environment you discovered this bug in

```true
Angular CLI: 11.0.4
Node: 14.16.1
Package Manager: npm 6.14.12
OS: WIN10 x64

Angular: 12.1.0
... animations, cli, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1100.4
@angular-devkit/build-angular   12.1.0
@angular-devkit/core            12.1.0
@angular-devkit/schematics      12.1.0
@schematics/angular             12.1.0
rxjs                            6.6.0
typescript                      4.1.2
```

**Comment by dario-piotrowicz** [comment]
Hi @KrasnovR the issue here is that the buttons are not of type `button` (they are, per default `submit`), so they trigger a submission, which (natively) results in a page reload.

If the click event returns `false` then the event propagation stops and the submission is not actually executed (https://www.geeksforgeeks.org/when-to-use-preventdefault-vs-return-false-in-javascript/) which is why you don't see the page refreshing in that case. On the contrary in your first case you don't return `false` and the submission goes through and the page reloads.

You can see what I mean in this [fork of your stackblitz](https://stackblitz.com/edit/angular-ivy-fhakcg?file=src%2Fapp%2Fapp.component.html), there I just added native `onsubmit` handlers to the various forms so that they console log and return `false`, preventing the refresh of the page.

As you can see there, you are triggering the native form submissions, this is actually rather strange as you'd imagine that Angular would catch and handle that for you (allowing you to tap into the `ngSubmit`), I believe this is not happening because your animations keep the form in the DOM for an extra bit of time after it's actual removal, but in that extra bit of time Angular has already stopped handling the form for you (Angular has "disconnected" to the form, leaving only it's DOM element present), so what actually happens is that the native DOM form gets the event and handles it natively.

I'll dig a bit dipper to see if that's actually the case, but it would certainly explain the strange behavior (as I highly doubt the animations code can actually cause the form submission by itself).

I'll keep you posted :slightly_smiling_face:

**Comment by dario-piotrowicz** [comment]
By the way, not sure you are interested in workarounds, in any case I believe that there are many of them, for example you can set your buttons' types to `button` and trigger the forms submissions manually or tap into the native `onsubmit` handler as I did in the stackblitz to always return `false` and prevent the page reload (this is pretty ouside the Angular scope so I would not actually suggest it).

**Comment by dario-piotrowicz** [comment]
Yes that looks to be exactly it, the function removing the form's listener is:
https://github.com/angular/angular/blob/544e6a5ca15c6e7be3e113dca4e2f789cc91c53a/packages/core/src/render3/node_manipulation.ts#L448-L449

which as you can see from this gif, gets called before the onsubmit call:
![Peek 2021-11-27 19-20](https://user-images.githubusercontent.com/61631103/143719640-ee199a8e-ef3c-4647-8ef4-eed6f73db925.gif)

**Comment by dario-piotrowicz** [comment]
@AndrewKushnir where do you think this should be handled?

This is caused by having animations but it doesn't really seem to be caused by the animations package, we could add a check in the animations package so that if a form is in its leaving animation then native submissions are ignored, but that would really really be terribly hacky and can't imagine that being the solution we'd want to go for :thinking: 

Any suggestion on how this could be handled/fixed? :slightly_smiling_face:

**Comment by AndrewKushnir** [comment]
@dario-piotrowicz sorry for the delay and thanks for the investigation. I'm still a bit unclear which part of the animations engine causing this behavior. Given that there are reasonable solutions/workarounds, I'm setting the priority to P4 and we can do further investigation at some point based on the priority. Thank you.

**Comment by dario-piotrowicz** [comment]
@AndrewKushnir thanks for the reply (no worries for the delay :smiley:)

As I said I think this may be more of a core (or core + animations) issue than an animation one (although I don't think there are real-life non animations related ways to trigger it)

anyways yeah I guess P4 makes sense, thanks :slightly_smiling_face::+1:

**Comment by dario-piotrowicz** [comment]
@AndrewKushnir I've changed my mind and I think that it actually makes sense to handle this in the animations code as the element's actual removal is done there :slightly_smiling_face: 

PR coming in a bit :smile:

**Comment by crisbeto** [comment]
We talked through it in our team meeting and we decided that this use case is too specific to bake into the framework. Furthermore, we already have all the necessary APIs to do this yourself.
