### ISSUE TITLE
feat(router): Ability to specify route on Component

### ISSUE THREAD

**Issue by jrote1** [angular/angular#4298]
It would be cool to be able to specify a route on a component for easy reference of what the route is. So possibly a Route attribute with the same parameters for a single route in RouteConfig attribute minus the component type.

**Comment by PascalPrecht** [comment]
@jrote1 I assume with "attributes" you mean decorators. 

Decorators are used to add meta data to your code which is then used by the framework to do various different things. Having a new `@Route` decorator that's basically the same as `@RouteConfig` except that you as a developer can immediately see what route this component represents, doesn't seem the right thing to do IMO.

So the question really is, what is it that you want to achieve? What's the value that is added here. If it's really just seeing what route this current configuration is, that a comment would also do the job?

Also, when it comes to nested/aux routes, a component with a configuration that is reusable might have a different semantic meaning in one context than in the other (because it's being reused). So you might not even be able to specify what route the current component is.

**Comment by jrote1** [comment]
@PascalPrecht 

Sorry yes I mean Decorator, Dart is not my main language to sometimes call the wrong name.

And yes a comment could work but if you change the route you would always forget to change the comment so unless you are strict about it you would always forget.

Yes I see what you mean that it might get a bit confusing/unusable but possibly with a bit of work I think it could be a useful addition. But obviously it would be optional for the user to use it. So it won't work in their situation then they don't use it.

**Comment by PascalPrecht** [comment]
@jrote1 My main concern is that this wouldn't add any value to the framework itself. Why exactly can't you just use `@RouteConfig` for that?

**Comment by mhevery** [comment]
reopen when more data is provided
