### ISSUE TITLE
Rewrite Benchpress in AtScript

### ISSUE THREAD

**Issue by yjbanov** [angular/angular#430]
This includes making sure that it can run benchmarks written in AtScript.

Depends on #429

**Comment by tbosch** [comment]
Also use a more general design that allows to use Benchpress with repeatable benchmarks and non repeatable benchmarks:

Basic abstractions
--------------

StopWatch
- start(markName, metrics)
- stop(markName, forceGc)
  * forceGc: whether a gc should be forced before marking the timeline
- split(markName, forceGc):
- getMeasureValues()
  * measure values for all calls to start/stop/split
  * does not return a value for a start without a stop/split!
  * for splits: return measure values for every lap, but also for time since start

==> geared towards not needing to get results in realtime but in batches!

PerflogNormalizer:
- normalizes differences in the perflogs of different browsers
- eventually this should go into the implementation of the different webdriver drivers...

Helpers
---------

BrowserReadyWait
- wait(silenceDelay):
  - waits until there was no script and no network activity since silenceDelay
  - uses stopWatch.split / getMesaureValues() to collect a stream of measure values...

BenchmarkLoop:
- repeat a benchmark multiple times without reloading the window and wait until the numbers get stable (e.g. by measuring the regression line slope)

Reporters:
- ConsoleReporter
- CloudReporter: reports to BigQuery
- Google internal reporters

Statistics
- regressionSlope, mean, error calculation

**Comment by tbosch** [comment]
Done
