### ISSUE TITLE
Docs generation tooling doesn't handle multiple signature methods on interfaces correctly

### ISSUE THREAD

**Issue by crisbeto** [angular/angular#43001]
### Description

`TestBed.initTestEnvironment` has a couple of different signatures: one where the last parameter is `options: { teardown?: ModuleTeardownOptions }` and another one which is `aotSummaries?: () => any[]`. When these signatures get rendered to AIO, the top overview in the page shows the first signature while clicking on the method shows the second one.

![Angular_-_TestBed_-_Google_Chrome_2021-07-20_18-36-06](https://user-images.githubusercontent.com/4450522/127689629-660b2112-09db-402c-922c-4918baa1eab3.png)
![Angular_-_TestBed_-_Google_Chrome_2021-07-20_18-36-19](https://user-images.githubusercontent.com/4450522/127689638-c95f5605-6326-4e7c-be7b-37a2a3640818.png)

Source code: https://github.com/angular/angular/blob/12.1.4/packages/core/testing/src/test_bed_common.ts#L73-L157

### What is the affected URL?

https://angular.io/api/core/testing/TestBedStatic

**Comment by petebacondarwin** [comment]
Although the associated PR fixes the problem for `TestBedStatic`, there is still a problem for `TestBed` since this is a weird hybrid of a class/interface/constant that Dgeni struggles to interpret: it sees it as a class and so will not display the "implementation" overload, as is normal for classes.
