### ISSUE TITLE
Define ngcc cache location for faster CI builds

### ISSUE THREAD

**Issue by muuvmuuv** [angular/angular#43038]
### Which @angular/* package(s) are relevant/releated to the feature request?

compiler-cli

### Description

Our team has limited pipeline resources (BitBucket), so each month we can only have lets say 2000 build minutes. We are already caching `.npm` dir and use `npm ci --prefer-offline` which works quite well and keeps us safe. Unfortunately what we are really struggling with is our huge dependency tree which ngcc needs to compile in every build we do *and this* takes a lot from our build minutes.

With some kind of caching this could reduce build minutes by a good amount. 

### Proposed solution

Create something like `.angular/ngcc/<package-hash>/fesm...` and store compiled dependencies there with the same hash as they were stored by npm lock to protect the cache. When using it later we just need to compare the package lock hash with the one cached by ngcc and can "copy" the files into node_modules.

### Alternatives considered

I do not know enough about ngcc compilation but I think it is just a smart wrapper around tsc so maybe we can open a ticket on TypeScript to support "caching" or some kind of.

**Comment by JoostK** [comment]
Please refer to #37942 for an earlier discussion on this topic.

If you want to cache ngcc's output, the current best approach is to cache all of `node_modules`. As Pete mentioned in #37942 we do not intent to expand ngcc with caching logic.

**Comment by muuvmuuv** [comment]
@JoostK sorry for the dup. I searched for ngcc caching but GitHub didn't came up with issues (closed too). Maybe my internet. Anyway thanks for the ref. Is there some official source for ng-linker and what it does instead of ngcc? Caching the node_modules folder would be a security risk and is not allowed at our company. Guess then we will stick for basic caching for now and wait for ng-linker?

**Comment by JoostK** [comment]
There was an RFC for the linker in #38366. It has since shipped in Angular 12 and some libraries are already taking advantage of it. Angular itself switches over in v13. The way the linker operates is a lot simpler than ngcc in the way it compiles libraries, as full AOT compilation can happen from just a single file (unlike ngcc, which requires transient dependencies _and_ all other source files in the lib). This is why it can be trivially cached by build tooling such as babel, as the output is guaranteed to be identical if the input file (and some config options) have not changed.
