### ISSUE TITLE
@Input. With first using component, default value rewrite sended value.

### ISSUE THREAD

**Issue by asemikolenov** [angular/angular#43098]
### Which @angular/* package(s) are the source of the bug?

@angular/core

### Is this a regression?

No

### Description

Decorator @Input with first use set value as default, but is wrong. 
In example:
Now:
Value: default
Value: new value1
Value: new value2

Expected result:
Value: new value0
Value: new value1
Value: new value2

P.S.: Sorry for the minimalistic description, my English is bad. View minimal reproduction link please.

### Please provide a link to a minimal reproduction of the bug

https://stackblitz.com/edit/angular-ivy-yeojkk?file=src%2Fapp%2Fapp.component.html

**Comment by JoostK** [comment]
This is indeed very unexpected behavior. Looking more closely though it does make sense to me, but it is _very_ subtle.

The root cause is how the `AppModule` specifies two bootstrap components:

```ts
  bootstrap: [AppComponent, CheckComponent]
```

First `AppComponent` will bootstrap itself onto the `<my-app>` host element in `index.html`, rendering the `<app-check>` host elements and their components. Once this has finished the `CheckComponent` component bootstraps itself onto the page. It queries the DOM for the first `app-check` element and boostraps a new component instance into that location. It does not realize that there is already an Angular component hosted at that location. The attributes from the host element are also not bound because of #1858.

Does that make sense? I'm not sure whether to classify this as bug, but nonetheless it is indeed confusing.

**Comment by asemikolenov** [comment]
Adding this component in bootstrap is my stupid mistake. I remove CheckComponent from this example,  and it is worked! Thanks!
