### ISSUE TITLE
feat: preserve scrollbar (from overflow) state scrollable items on the page

### ISSUE THREAD

**Issue by mrmokwa** [angular/angular#43116]
### Which @angular/* package(s) are the source of the bug?

router

### Is this a regression?

No

### Description

- I have a app that navigate from route Foo to Bar.
- I'm working with RouteReuseStrategy to reuse all components
https://github.com/mrmokwa/router-reuse-strat-overflow-bug/blob/main/src/app/router-reuse-strategy.ts

#### Steps to Reproduce

1. I scroll down in Foo component and click to detail a row. Check the scrollbar position.
2. I view de detailed information and click to go back.
3. Check the scrollbar position. It didn't preserve it's original position.

![router-reuse-bug](https://user-images.githubusercontent.com/12090931/129029625-4855613c-7746-4e66-b769-e6069462ed5e.gif)

### Please provide a link to a minimal reproduction of the bug

https://github.com/mrmokwa/router-reuse-strat-overflow-bug

### Please provide the exception or error you saw

```true
The scrollbar moved to top. 
It should be in the same position as before the navigation, since it's re-using the component.
```

### Please provide the environment you discovered this bug in

```true
Angular CLI: 12.1.4
Node: 14.15.4
Package Manager: npm 6.14.10
OS: win32 x64

Angular: 12.1.5
... animations, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1201.4
@angular-devkit/build-angular   12.1.4
@angular-devkit/core            12.1.4
@angular-devkit/schematics      12.1.4
@angular/cli                    12.1.4
@schematics/angular             12.1.4
rxjs                            6.6.7
typescript                      4.3.5
```

**Comment by atscott** [comment]
Scroll restoration is outside the scope of what `RouteReuseStrategy` is designed to do. The elements still have to be recreated in the DOM, so it's not as though elements on the page are restored exactly as they were. It's just the component classes that get reused.
In addition, scroll restoration for individual containers on the page isn't something that can feasibly be implemented within the framework. If you wanted to enable this type of thing for a given component/element you could do something such as:

  1. add a listener for the `scroll` event
  2. save the `scrollTop` position
  3. set the `scrollTop` for the element in `ngDoCheck`

The above would work with `RouteReuseStrategy` because the component class is reused so the `scrollTop` value that you saved in the component will not be lost.

There are several articles online as well that discuss scroll restoration for particular containers.

**Comment by mrmokwa** [comment]
I thought that RouteReuseStrategy did some magic to "hide" the element in the view and them re-use it.
Understood, thanks for the clarification.

**Comment by mrmokwa** [comment]
For anyone facing the same issue, as solution, I made a directive that tracks the navigation and adjusts the scrollbar

```
import { Directive, ElementRef, OnDestroy, OnInit } from '@angular/core';
import { ActivatedRoute, NavigationEnd, Router, RoutesRecognized } from '@angular/router';
import { Subject } from 'rxjs';
import { takeUntil } from 'rxjs/operators';

@Directive({
   selector: '[appTrackScrollbar]',
})
export class TrackScrollbarDirective implements OnInit, OnDestroy {
   position = 0;
   destroy$ = new Subject();

   constructor(private router: Router, private el: ElementRef, private activatedRoute: ActivatedRoute) {}

   ngOnInit() {
      const path = '/' + this.activatedRoute.parent.snapshot.routeConfig.path;

      this.router.events.pipe(takeUntil(this.destroy$)).subscribe((event) => {
         if (event instanceof RoutesRecognized) {
            if (event.urlAfterRedirects !== path) {
               this.position = this.el.nativeElement.scrollTop;
            }
         }

         if (event instanceof NavigationEnd) {
            if (event.urlAfterRedirects === path) {
               this.el.nativeElement.scrollTop = this.position;
            }
         }
      });
   }

   ngOnDestroy() {
      this.destroy$.next();
      this.destroy$.complete();
   }
}
```
