### ISSUE TITLE
add common js bundles output

### ISSUE THREAD

**Issue by rkirov** [angular/angular#4315]
- [x] make e2e examples use bundles (otherwise we have no automated testing for the bundles)
- [ ] decide which tool to produce a CJS bundle (webpack vs browserify vs systemjs builder)
- [ ] add the CJS bundle to the build (while keeping system bundle)

// cc @pkozlowski-opensource @vsavkin @IgorMinar @jeffbcross

**Comment by rkirov** [comment]
This takes over the first proposal in #4278

**Comment by IgorMinar** [comment]
@juliemr is looking into upgrading systemjs builder which can generate both system.register as well as cjs bundles (https://github.com/angular/angular/issues/4278#issuecomment-145279354)

**Comment by pkozlowski-opensource** [comment]
@IgorMinar @juliemr could you please have a look at [my comment](https://github.com/angular/angular/issues/4278#issuecomment-145273941) regarding the CJS output? From my investigations it might look like CJS bundles would be huge for http / router (well, any non-core module) since I'm not sure if we can do proper bundle arithmetic when using the CJS format.

Also please also see https://github.com/angular/angular/issues/4495

Available to help / chat if needed.

**Comment by rkirov** [comment]
https://github.com/angular/angular/commit/f7b75330e020d942be21fa704b02c57ec59a4f59 took care of the first checkbox. This means that any further work on bundles will actually have to make sure the bundles work with the e2e tests :)

**Comment by juliemr** [comment]
cc @robwormald is working on the CJS stuff.

**Comment by juliemr** [comment]
I think it makes more sense for @pkozlowski-opensource to own this at this point :)

**Comment by robwormald** [comment]
i think this is superseded by https://github.com/angular/angular/issues/5223 anyway?

(better him than me)

**Comment by juliemr** [comment]
Agreed - I'll tentatively close.
