### ISSUE TITLE
How to resolve this issue whether I am using ng serve

### ISSUE THREAD

**Issue by JKAngular** [angular/angular#43197]
### Which @angular/* package(s) are the source of the bug?

service-worker

### Is this a regression?

Yes

### Description

![image](https://user-images.githubusercontent.com/59573064/129946524-ff2e5c0b-b9d2-4c3b-acb8-f94e0a73c780.png)

### Please provide the exception or error you saw

```true
Hi
I have using the command npm install it is working good

after I trying ng serve --open  it shows this issue.

how to resolve it?
```

**Comment by JKAngular** [comment]
Hi
I have tried also 

npm install --save angular-webstorage-service

**Comment by itea-dev** [comment]
@JKAngular

The library ngx-webstorage-service is outdated, it hasn't been updated in two years.

Try this other library instead:

https://github.com/PillowPillow/ng2-webstorage#readme

**Comment by itea-dev** [comment]
@JKAngular

BTW, this is not an issue in Angular.

**Comment by gkalpak** [comment]
It is not clear what package is causing the issue, but based on your comments it seems to be `ngx-webstorage-service`. This is a 3rd-party package (not maintained by the Angular team), so you either need to contact the project's maintainers (e.g. file an issue on their issue tracker) or use a more up-to-date package (if `ngx-webstorage-service` is not maintained any more).

Closing this issue, since there is nothing we can do on our side.
