### ISSUE TITLE
Should we rename `@HostBinding` to `@HostProperty`

### ISSUE THREAD

**Issue by vicb** [angular/angular#4320]
"binding" is mostly used in the context of the DI (`bindings`, `viewBindings`) and IMO `@HostBinding` can be confusing.

What about renaming `@HostBinding` to `@HostProperty` ?

/cc @vsavkin @mhevery @IgorMinar

**Comment by pkozlowski-opensource** [comment]
+1 for the proposed rename. We should really find 2 different names as not confuse DI and property bindings.

**Comment by mhevery** [comment]
@vsavkin can you comment?

I don`t think we should use `@HostProperty` since it would imply that it has same semantics as `@Property`, which it does not. `@Property` copies data from the binding to the component, where as `@HostProperty` would create a binding which would update the DOM. Can you suggest something other than `@HostProperty`?

**Comment by IgorMinar** [comment]
+1 for rename

I think that `@HostProperty` is a good name, we should add a note about the different semantics compared to `@Property`. It's not that different though.

**Comment by pkozlowski-opensource** [comment]
> It's not that different though.

Yeh, when I saw +1 for the rename I was thinking "at the end of the day we are setting a property". It is very true that we either setting this property on a DOM element or a directive, but in both cases we are updating a property in response to model changes.

**Comment by IgorMinar** [comment]
@mhevery your use of the term "binding" is confusing (which is related to what this issue is trying to fix)

**Comment by mhevery** [comment]
I am fine with rename, but I think renaming to `@HostProperty` is a mistake, so let's brainstorm some other names. 

@IgorMinar as I said before `@HostProperty` is wrong since it has completely different semantics to `@Property` when you add prefix you are clarifying something. So it is not just a property, it is a special `Host` property, except in this case it would be something completely different. Just like `Listen` and `Emit` are different so is `Property` and `Binding` (or whatever else we should call it.)

**Comment by vicb** [comment]
Some brainstorming:

- `@LinkHostProperty`
- `@MirrorToHostProperty`

**Comment by PascalPrecht** [comment]
I'd actually also vote for `@HostProperty` ... @mhevery if the main semantic difference is that this decorator causes a write to a DOM property (rather than a component property), what about `@DOMProperty` then? We just need to keep in mind to update the desugared version too.

OTOH, I'm not sure if that proposal would work in all scenarios. Do we have/use host properties in web worker world where no DOM exists? Then `@DOMProperty` might not be a good idea..

**Comment by mhevery** [comment]
@PascalPrecht We can't have `DOM` in the name as the render may be native.

@vicb Appreciate your suggestions https://github.com/angular/angular/issues/4320#issuecomment-142651575. I believe fewer words are better then 3 or 4. Can you think of something shorter?

`@Property` means that you are declaring a property. Which may or may not be data bound to. But it is part of the public API of the component. Component reads this property only, and expect data to come in here.

`@HostBinding` is very different. It is not a declaration as much as a action. Please do something for me. This is private not public. Here we write to the property and expect it to be mirrored to the host element. It always has a dirty checking cost. 

Having `@Property` and `@HostProperty` have a same ending is extremely confusing since they are nothing alike. Public vs private, input vs output, zero cast vs never-zero cost. Possible expression vs copy.

I am fine with rename, but using `Property` suffix is wrong, we need to find some other word to describe this.

**Comment by gdi2290** [comment]
`@PublicProperty` (host)
`@PrivateProperty` (view)
we already do this with TypeScript

**Comment by PascalPrecht** [comment]
Not sure if `"Private"` should be in the name either. This could confuse ppl as well, since what we're actually doing is exposing a property binding to the outside world. Ppl might that this is `@PublicProperty` then.

**Comment by vicb** [comment]
`@UpdateHost`, `@ToHost` ???

**Comment by PascalPrecht** [comment]
The more I think about the suggested names and the reasoning behind renaming the original one at all, the more I think `@HostBinding` is the best fit. Thing is that even ppl like us that know sort of what's happening behind the scenes, came up with `@HostProperty` or anything `@xxxProperty` in the first place, even though it's semantically different from what `@Property` does.

Think about what users of the framework, that are not so familiar with the internals, would expect. They'd prolly also expect `@HostProperty`. If we do sth. like `@UpdateHost` or `@ToHost` it feels like there's something missing, namely the "where exactly does it go?"-part.

So maybe we should just go with the cost that `@HostBinding` could be confused with DI binding and stick with it? It feels like the most closest to me...

**Comment by IgorMinar** [comment]
In the light of #4416 which renames all di binding terminology to di provider, which frees up "binding" to be used only as data-binding, this API name might remain as is.

**Comment by mhevery** [comment]
Closing per @IgorMinar comment https://github.com/angular/angular/issues/4320#issuecomment-144549957
