### ISSUE TITLE
Forcing null as a type in async pipe

### ISSUE THREAD

**Issue by ArielGueta** [angular/angular#43249]
### Which @angular/* package(s) are relevant/releated to the feature request?

language-service

### Description

The type of the async pipe is nullable, which isn't correct in some cases. I don't think the framework should define the type for the consumers. For example, we can use sync observable like `of`, and it'll not be `null`.

Typing it as `| null` forces us to use the non-null assertion type in every similar use case. This isn't very pleasant:

```html
<app-bar  [foo]="(sync$ | async)!"></app-bar>
```

### Proposed solution

Remove the `null` type, and move the responsibility to the consumer. 

### Alternatives considered

Remove the `null` type, and move the responsibility to the consumer.

**Comment by JoostK** [comment]
This has been proposed before in #33704 and unfortunately it is unknown in the type-system that an Observable is meant to emit synchronously. Simply removal the `null` type is not really desirable either as the `async` pipe _does_ produce a `null` value for async observables. If you know that an observable is in fact synchronous, then using the `!` operator to quantify that is actually appropriate to me (although a little annoying). Additionally, it captures that it is in fact an unsafe operation, as the observable may easily be changed to become asynchronous without affecting its type and subsequently cause downstream issues for the `null` value.

As mentioned in #33704 the current workaround may be to set `"strictNullInputTypes": false` instead of incorporating the `!` operator in templates, but that will also silence other invalid nullable bindings.

**Comment by JoostK** [comment]
(I closed this as it's already been discussed in #33704)

**Comment by ArielGueta** [comment]
Thanks for the answer.
