### ISSUE TITLE
`Unhandled Navigation Error` error shown when I use --base-href with cdn address instead of --deploy-url

### ISSUE THREAD

**Issue by simplejason** [angular/angular#43303]
# 🐞 Bug report

### Command (mark with an `x`)

- [ ] new
- [x] build
- [ ] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] extract-i18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc

### Is this a regression?

 Yes

### Description

 As this PR(angular/angular-cli/pull/21537) said, we can set `--base-href` to the CDN address  because `--deploy-url` will be deprecated next version. So I follow this to change the command of building application.
Here is the cmd:
`node --max_old_space_size=4096 ./node_modules/.bin/ng build --prod --base-href=//mycdn.com/xxx`
When I try to use `http-server` to start it, the error `Unhandled Navigation Error` shown. **I'm not sure if I missed something or set wrong configurations in my application.**

## 🔬 Minimal Reproduction

<pre><code>
// app.module.ts
...
  providers: [
    { provide: APP_BASE_HREF, useValue: '/' }
   ...
  ],
...

// app-routing.module.ts, `loadChildren` in routes 
...
@NgModule({
  imports: [
    RouterModule.forRoot(routes, {
      useHash: true,
      preloadingStrategy: PreloadAllModules,
      relativeLinkResolution: 'legacy'
    })
  ],
  exports: [RouterModule]
})
...

// build cmd
node --max_old_space_size=4096 ./node_modules/.bin/ng build --prod --base-href=//mycdn.com/xxx

// start server
http-server --proxy xxxx
</code></pre>

## 🔥 Exception or Error
<pre><code>

Unhandled Navigation Error:                main-es2015.5fc8829f03fd1c12af29.js:formatted:15045 
......
</code></pre>

## 🌍 Your Environment

<pre><code>

Angular CLI: 12.2.3
Node: 14.17.5
Package Manager: npm 6.14.14
OS: darwin x64

Angular: 12.2.3
... animations, cdk, cli, common, compiler, compiler-cli, core
... forms, localize, platform-browser, platform-browser-dynamic
... router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1201.1
@angular-devkit/build-angular   12.2.2
@angular-devkit/core            12.1.1
@angular-devkit/schematics      12.2.3
@schematics/angular             12.2.3
rxjs                            6.6.7
typescript                      4.3.5
</code></pre>

**Anything else relevant?**

**Comment by atscott** [comment]
`APP_BASE_HREF` wasn't really intended to work this way for `HashLocationStrategy`. It's meant to support old server configurations and the `APP_BASE_HREF` is meant only to prepend a local server path to the app paths, following the `#`. 

There are a couple possible solutions here: 

1. Use `PathLocationStrategy`
2. Create your own `LocationStrategy` for your specific use-case. In particular, you'll want to adjust the `prepareExternalUrl` method. You could/should also do this now as a fix for you application while you wait for a change on the Angular side (if we choose to make one).
3. Update `HashLocationStrategy` to have special handling for when `APP_BASE_HREF` is a valid URL on its own rather than a relative path. If we did this, it looks like we would also have to adjust the location shim in the upgrade package to not prepend protocol, hostname, etc. when the base href already has those https://github.com/angular/angular/blob/478131c519cd3e12fbede458d5c6ecdc1ca0c9ce/packages/common/upgrade/src/location_shim.ts#L307-L308

@alan-agius4 How common do you think it will be for developers to encounter this issue? Is this something we should address or is it so uncommon that we should have application developers write custom location strategies to handle domain-specific requirements?

**Comment by alan-agius4** [comment]
@atscott, users might encounter this more in v13 due to the deprecation of the `deployUrl` flag in the CLI.  More context https://github.com/angular/angular-cli/pull/21537

None-the-less this issue occurs only when combining 2 legacy/old techniques together which I'd say is not as common, and therefore I am inclined in saying that we should not handle it and users should move towards a modern setup.

The mentioned old techniques are;
1) **Hash location strategy**, as you mentioned this is supported for old server setup and no a days most users should have transitioned towards the path location strategy. 
2) **CDN for assets only**. This is also a relatively old technique which we don't recommand, we strongly recommand that  the entire application is hosted on a CDN.

**Comment by atscott** [comment]
Closing after discussing with @alan-agius4. This should be solved by creating an application-specific `LocationStrategy` rather than updating `HashLocationStrategy` to try to handle this uncommon edge case.

**Comment by simplejason** [comment]
Thanks for your update, I think building with cdn and using docker to deploy(pull all cdn files including js&assets) is not `uncommon edge case`, I will try to use `PathLocationStrategy` and `APP_BASE_HREF` to check if this can sovle my problem, thanks again :)

**Comment by simplejason** [comment]
> So it appears that the `APP_BASE_HREF` will be appended to the DOM base href when the `useHash` is set to true.
> 
> ```
> e = DOMException: Failed to execute 'replaceState' on 'History': A history state object with URL 
> 'http://cdn.com/#https://angular-ivy-iznjka.stackblitz.io/demo/demo2' cannot be created in a document with origin 
> 'https://angular-ivy-iznjka.stackblitz.io' and
>  URL 'https://angular-ivy-iznjka.stackblitz.io/#https://angular-ivy-iznjka.stackblitz.io/demo/demo2'. at BrowserPlatformLocation.replaceState 
> ```
> 
> Transferring to the FW repo since it looks more of a router issue.

@alan-agius4 I faced the same error, as you said above, we will only need to create `LocationStrategy` to replace the origin `deployUrl` and not achieve the same behavior with the existing configuration in V13? Or angular will fix it next version? I'm not sure if I need to create a new issue for this.

**Comment by alan-agius4** [comment]
@simplejason, If you are using `HashLocationStrategy`, you need to create your own `LocationStrategy` that handles this use-case, particularly you want to amend this method https://github.com/angular/angular/blob/478131c519cd3e12fbede458d5c6ecdc1ca0c9ce/packages/common/src/location/hash_location_strategy.ts#L73-L76, particularly you want to omit the base href.

Our recommendation however, would be to move away from the legacy `HashLocationStrategy` and use `PathLocationStrategy` instead.
