### ISSUE TITLE
Possible Improvement to findAnchorFromDocument function

### ISSUE THREAD

**Issue by dario-piotrowicz** [angular/angular#43348]
### Which @angular/* package(s) are the source of the bug?

common

### Is this a regression?

No

### Description

@atscott I've found this comment of yours regarding the `findAnchorFromDocument` function, I was just wandering if we could make this change during the jump to v13

https://github.com/angular/angular/blob/8d0511d009aa01fbebdb61ca4a97dd48d5d1929d/packages/common/src/viewport_scroller.ts#L123-L125

___

I would be more than happy to pick it up! :smile:

**Comment by atscott** [comment]
I don't think this is actually a reasonable change to make. Instead, I would have the function be renamed to something that doesn't imply it only scrolls to anchors (like `scrollToFragid` since that's what they call it in the spec). I don't think that change is worth the effort for cleanup either. Could you send a PR to remove the `TODO`?

**Comment by dario-piotrowicz** [comment]
Ok if no changes are actually needed I'll just create a PR to remove the TODO :slightly_smiling_face: :+1:
