### ISSUE TITLE
Performance issue after upgrading to hybrid AngularJS + Angular

### ISSUE THREAD

**Issue by victorlbitten** [angular/angular#43402]
Hey, there!
I work on a large AngularJS application and we've recently moved it into a hybrid AngularJS + Angular application. The application is bootstrapped via Webpack, who calls the Angular part, which bootstraps the AngularJS part(99% of the application as of right now).

The migration to a hybrid application went ok, but after some weeks we began to receive a lot of complaints on performance. We've turned off all of Zone.js events and performance is a bit better now, but the application is still very slow.

Any tips on how to proceed?
Thanks in advance!

**Comment by Kr0san89** [comment]
I think for big application and specially with performance issues it is recommended the other way around: https://angular.io/guide/upgrade-performance
At Least on my last upgrade Project we did bootstrap AngularJS and downgraded Angular into it.

**Comment by gkalpak** [comment]
It is hard to tell what might be the cause of the slow-down (especially if it is a significant one). Some slow-down is expected, because there is usually more change-detection on both sides (AngularJS and Angular), since one framework tries to notify the other side of its changes. But there could be extreme cases where a 3rd-party lib performs some async operations (that would not trigger change detection in a pure AngularJS or Angular app), but it does cause in a hybrid app (for example, due to Zone.js picking up all async operations).

As @Kr0san89 mentioned, there is a different ngUpgrade "mode" that is geared more towards performance: https://angular.io/guide/upgrade-performance
So, maybe that is worth looking into if you are having performance issues.

(However, if you are seeing a significant slow-down, it might be worth profiling the app and trying to identify the root cause before investing in a specific solution.)
