### ISSUE TITLE
[FormArray] :  ExpressionChangedAfterItHasBeenCheckedError

### ISSUE THREAD

**Issue by indraraj26** [angular/angular#43474]
### Which @angular/* package(s) are the source of the bug?

forms

### Is this a regression?

No

### Description

Only occurred when i am working with formArray.

app.component.html
```
<!-- No error if you comment out this  -->
<pre>{{myForm.value | json}}</pre>
```

Playground structure:
child component - contains child form and it has generic-form which actually generate the control and push it to parentForm.
generic-form component - loop through data and create field/control for child component  

### Please provide a link to a minimal reproduction of the bug

https://stackblitz.com/edit/angular-ivy-kb5gdh?file=src%2Fapp%2Fapp.component.html

### Please provide the exception or error you saw

```true
ERROR
Error: NG0100: ExpressionChangedAfterItHasBeenCheckedError: Expression has changed after it was checked. Previous value: '{
"childForm": {
"name": "indra",
"range": []
}
}'. Current value: '{
"childForm": {
"name": "indra",
"range": [
{
"first_name": null,
"last_name": null
}
]
}
}'.. Find more at https://angular.io/errors/NG0100
```

### Please provide the environment you discovered this bug in

```true
Angular : 12.1.X
```

**Comment by j2L4e** [comment]
Not a bug, just a not-so-friendly reminder from angular.

If you add this to your AppComponent ...

```
constructor() {
    console.log(JSON.stringify(this.myForm.value))
    this.myForm.valueChanges.subscribe(x => console.log(JSON.stringify(x)));
}
```
... you'll see that adding controls dynamically automatically emits values:
```
{}
{"childForm":{"name":"indra","range":[]}}
{"childForm":{"name":"indra","range":[{"first_name":null,"last_name":null}]}}
ERROR
```
Angular's change detection relies on template-bound data not being mutated during a change detection run, so that a single traversal of the component tree is sufficient. You're violating this concept by synchronously changing data (and binding it to the template) in `OnInit`.

This wouldn't be an error in production, change detection just wouldn't pick up the new value until the next cycle.

You could get around this by using 

```
  value$ = this.myForm.valueChanges.pipe(auditTime(0));
```

and binding `value$ | async` to the template. However what seem to be trying to do needs to be thought-out well. You should take a look at the code of angular's template-driven forms to get an idea.

**Comment by indraraj26** [comment]
i thought it is do something with .push().

Thanks for your explanation. Got it  🎉
