### ISSUE TITLE
NavigationExtras skipLocationChange preserveFragment second click

### ISSUE THREAD

**Issue by andrerferreira** [angular/angular#43608]
### Which @angular/* package(s) are the source of the bug?

core

### Is this a regression?

No

### Description

The following code will not add the fragment to the URL and function on 1st click, however, if the user scrolls back to this link and clicks it again, no scroll occurs.

`<a [routerLink]="'.'" [skipLocationChange]="true"  fragment="anchorPrerequisites">Prerequisites verification</a>`

I've then tried to ensure the fragment wasn't preserved, however it also didn't do the trick. 

`<a [routerLink]="'.'" [skipLocationChange]="true"  [preserveFragment]="false" fragment="anchorPrerequisites">Prerequisites verification</a>`

### Please provide the exception or error you saw

```true
No error
```

### Anything else?

It wasn't clear to me why skipLocationChange doesn't work (the fragment gets added to the URL), if used this way:

`a [routerLink]=" ['.', { skipLocationChange: true }]" fragment="anchorPrerequisites">Prerequisites verification</a>`

**Comment by atscott** [comment]
I suspect you need to set `onSameUrlNavigation: 'reload',`. While you did set `skipLocationChange: true`, the router still needs to keep track of its own representation of the internal state. For example, if you navigated to a totally separate path, but used `skipLocationChange: true`, we still need to track that we are somewhere different than what the browser url says. Because `skipLocationChange: false` is the default, when you try to navigate again, the Router determines that it's the same URL as before and does not process the navigation at all.

https://stackblitz.com/edit/angular-ivy-router-base-j1thjh?file=src%2Fapp%2Fapp.module.ts
