### ISSUE TITLE
tick() without parameters not working with rxjs timer()

### ISSUE THREAD

**Issue by jhyot** [angular/angular#43625]
### Which @angular/* package(s) are the source of the bug?

core

### Is this a regression?

No

### Description

`fakeAsync` tests with `tick()` (without parameter) seems not to work when rxjs `timer` observable is used.

Code in component:
```
timerComplete = false;
  
startTimer(): void {
  timer(1000).subscribe(() => this.timerComplete = true);
}
```

working test:
```
  it('working with tick(number) as it should', fakeAsync(() => {
    component.startTimer();
    tick(1000);
    expect(component.timerComplete).toBeTrue();
  }));
```

**not** working:
```
  it('NOT working with tick() but should', fakeAsync(() => {
    component.startTimer();
    tick();
    expect(component.timerComplete).toBeTrue();
  }));
```

### Please provide a link to a minimal reproduction of the bug

https://stackblitz.com/edit/angular-ivy-y4g8n6?file=src%2Fapp%2Fhello.component.spec.ts

### Please provide the exception or error you saw

```true
Test fails, and additionally the following error is shown:
`1 periodic timer(s) still in the queue.`
```

### Please provide the environment you discovered this bug in

```true
Angular 12.2.7
```

**Comment by petebacondarwin** [comment]
This is working as expected, as far as I can tell.
If you do not provide a `millis` argument it is equivalent to setting it to `0`.
The `tick()` function will run any outstanding tasks that are due within the period from `now` to `now + millis`.
In this case the `timer()` is creating a `setInterval()` that is not due to run for 1000ms. As such its task is not due for 1000ms and so `tick(0)` will not trigger it to be flushed.

**Comment by jhyot** [comment]
Thanks for clarifying. I indeed misunderstood what `tick()` is doing. I think it stems from some unfortunate incorrect info on Stackoverflow that I once had read: https://stackoverflow.com/questions/56498799/what-is-the-difference-between-tick-and-flush-in-angular-testing#comment99589780_56499466

Sorry for the noise :)
