### ISSUE TITLE
Cannot inject FormControlName into control

### ISSUE THREAD

**Issue by CobusKruger** [angular/angular#43667]
### Which @angular/* package(s) are the source of the bug?

forms

### Is this a regression?

No

### Description

I created a simple project with a custom attribute directive that can be applied to a control similarly to how the `formControlName` attribute is applied:

```html
<app-tester fakeControlName="One"></app-tester>
<app-tester fakeControlName="Two"></app-tester>
```

I am then able to inject that directive into my component and read that name property:

```typescript
constructor(private formControlName: FormControlName) {}
ngOnInit() {
  if (this.formControlName) {
    this.name = this.formControlName.name.toString();
  }
}
```

This works well. Here is the link to the working project:
https://stackblitz.com/edit/angular-ivy-7wgr8j?devtoolsheight=33&file=src%2Fapp%2Ftester%2Ftester.component.ts

I then forked the project and replaced my own directive with `FormControlName`.

```html
<form [formGroup]="form">
  <app-tester formControlName="field1"></app-tester>
  <app-tester formControlName="field2"></app-tester>
</form>
```

```typescript
constructor(private formControlName: FormControlName) {}
ngOnInit() {
  if (this.formControlName) {
    this.name = this.formControlName.name.toString();
  }
}
```

As soon as I add `FormControlName` to the constructor parameter, I get this gem of an error:

```
ERROR
Error: NG0200: Circular dependency in DI detected for TesterComponent.
Find more at https://angular.io/errors/NG0200
```

This error message takes me to a cool documentation page where I can learn about debugging it. This video (at around the fifteen-second mark) mentions a warning that will show the exact dependencies causing the trouble, but the warning doesn't appear in the console.

Here is the link to the non-working project:
https://stackblitz.com/edit/angular-ivy-zhgdug?devtoolsheight=33&file=src/app/tester/tester.component.ts

### Please provide a link to a minimal reproduction of the bug

https://stackblitz.com/edit/angular-ivy-zhgdug?devtoolsheight=33&file=src/app/tester/tester.component.ts

### Please provide the exception or error you saw

```true
Error: NG0200: Circular dependency in DI detected for TesterComponent.
Find more at https://angular.io/errors/NG0200
```

### Please provide the environment you discovered this bug in

```true
On Stackblitz:

Angular CLI: 12.2.7
Angular: 12.2.4
animations, cli, common, compiler, compiler-cli, core, forms, platform-browser, platform-browser-dynamic
```

**Comment by JoostK** [comment]
There _is_ a cyclic dependency here, so the failure itself is expected. It does appear that the cycle path is not tracked for providers that are resolved from element injectors; only the module injector appears to do that.

Finding the cycle can be done by setting a breakpoint in `throwCyclicDependencyError` and looking at the stack frames:

<img width="493" alt="image" src="https://user-images.githubusercontent.com/123679/135662070-e2bd59ab-bfc7-4fc8-b1da-6badcf7bb71d.png">

This shows that `TesterComponent_Factory` ends up invoking `FormControlName_Factory` which requests a multi provider that is being resolved (near the top of the stack). That multi provider is for the `NG_VALUE_ACCESSOR` token, for which `TesterComponent` provides itself using the `useExisting` proxy. That's the cycle in this situation.

---

If you do in fact need this reference then one way to avoid the cycle could be to inject `Injector` instead of `FormControlName`. You can then get `FormControlName` from within `ngOnInit`, as that will have broken the cycle during construction of the instances (so you can't inject it from within the constructor, that would still be cyclic).

Does that solve the issue you had? I would suggest to raise the missing cycle path as a feature request to improve the DX for this case.

**Comment by CobusKruger** [comment]
@JoostK Nice detective work! Without the `NG_VALUE_ACCESSOR` dependency, injection also fails. Your advice about injecting `Injector` and getting `FormControlName` from there, works like a charm.

I'm closing this, because yours is a solid solution. Thank you 😁
