### ISSUE TITLE
angular io is not properly loading

### ISSUE THREAD

**Issue by ValentinBossi** [angular/angular#43677]
reported issue as suggested in the console -> If you see this error, please report an issue at https://github.com/angular/angular/issues/new?template=3-docs-bug.md including the above logs.
--------------------
NGSW Debug Info:

Driver version: 12.1.1
Driver state: EXISTING_CLIENTS_ONLY (Degraded due to: Hash mismatch (cacheBustedFetchFromNetwork): https://angular.io/generated/docs/guide/web-worker.json: expected 1d221cfcf0dedc4741189deff2e7aea44c972ea0, got 698e1f9131f9e5fe13e5894fb666ca025ee0372f (after cache busting)
Error: Hash mismatch (cacheBustedFetchFromNetwork): https://angular.io/generated/docs/guide/web-worker.json: expected 1d221cfcf0dedc4741189deff2e7aea44c972ea0, got 698e1f9131f9e5fe13e5894fb666ca025ee0372f (after cache busting)
    at LazyAssetGroup.<anonymous> (https://angular.io/ngsw-worker.js:818:39)
    at Generator.next (<anonymous>)
    at fulfilled (https://angular.io/ngsw-worker.js:22:32))
Latest manifest hash: fa62d8cde64e1c68e29c52a2d0965ba12313477f
Last update check: never

=== Version 8c1969a77d204f334092bc618f64892c0523c366 ===

Clients: de81add1-414d-435f-b9e4-7142a4eae35f

=== Version fa62d8cde64e1c68e29c52a2d0965ba12313477f ===

Clients: 

=== Idle Task Queue ===
Last update tick: 33u
Last update run: never
Task queue:
 * init post-load (update)
 * init post-load (cleanup)
 * initialization(8c1969a77d204f334092bc618f64892c0523c366)
 * initialization(fa62d8cde64e1c68e29c52a2d0965ba12313477f)
 * check-updates-on-navigation

Debug log:

**Comment by gkalpak** [comment]
Thx for reporting this, @ValentinBossi 🥇
We think we have identified the issue (see https://github.com/angular/angular/issues/28114#issuecomment-923122967 for more details, if you're interested) and it has been fixed in `@angular/service-worker` package with #43518 (which is now available in v12.2.8).

We are about to update angular.io to the new version, so this is hopefully the last time you saw this error 🤞 
But if you see this again after next week, please do report it 🙏
