### ISSUE TITLE
End Of Life for AngularJS is December 31st, 2021

### ISSUE THREAD

**Issue by itsmedeepakupadhya** [angular/angular#43699]
End Of Life for AngularJS is December 31st, 2021 . I am using Angular 9.1 . So Do i need to migrate my angular SPA to some other technologies like REACT / VUE ?

please clarify

**Comment by gkalpak** [comment]
[AngularJS][1] refers to the old, 1.x version. This is the version that is in Long-Term Support mode, which ends on Dec 31, 2021.
Versions 2+ are referred to as [Angular][2] (without the `JS` suffix) and Angular is still actively maintained and developed.

So, since you are using Angular, you are not affected by the End Of Life of AngularJS.

[1]: https://angularjs.org/
[2]: https://angular.io/
