### ISSUE TITLE
Angular Service Worker flawless and silent upgrade

### ISSUE THREAD

**Issue by rozzs74** [angular/angular#43709]
### Which @angular/* package(s) are relevant/releated to the feature request?

service-worker

### Description

What I want to achieve to have better experience from the user where in the update of service worker will be a silent upgrade in background without refreshing the page flawlessly. The actual process is right now is by automatically reloading the page. This is poor user experience in real world scenario.

1. Does Angular supports silent upgrade?

2. Is the service worker can be customize to achieve flawless and silent upgrade of the service worker?
I would like to share the current code that I am using to get the latest version of the app which then showing a snackbar that latest version is available and do a refresh.

```
runNewAppVersionNotifier() {
        const self = this;
        console.log('log notifier 1', self.swUpdate.isEnabled);
        if (self.swUpdate.isEnabled) {
            console.log('log swUpdate 2', self.swUpdate.isEnabled);
            self.swUpdate.available.subscribe((event) => {
                console.log('log notified available', event);
                self.matSnackBar.openFromComponent(JepSnackbarComponent, {
                    duration: 0, data: { text: "New version available. Please reload the page to get the latest update.", withButton: true, customTextButton: "RELOAD", status: "info" }
                }).afterDismissed().subscribe((result: any) => {
                    console.log('log swupdate fire', result);
                    self.swUpdate.activateUpdate().then((value) => {
                        window.location.reload();
                        const hostname = window.location.hostname;
                        let c = new CookieStorage({ domain: hostname === "localhost" ? "localhost" : ".jepto.com", secure: hostname === "localhost" ? false : true, path: "/" });
                        c.clear();
                    });
                    // if (result === true) {

                    // }
                });
            });
        }
    }
```

### Proposed solution

Can `SwUpdate` supports automatically received the latest version of the app without calling `window.location.reload()`?
Appreciate the help.

### Alternatives considered

For now, the alternative solution is to utilise websocket connection for notification change then apply DOM API specific to this
https://developer.mozilla.org/en-US/docs/Web/API/Service_Worker_API

**Comment by gkalpak** [comment]
Well, there are two different concepts here:
1. There is the version of the app that the current tab is executing (i.e. the JS from a specific `main.<some-hash>.js` file and other JS scripts).
2. There is the version that the SW uses to serve requests from the current tab.

The `SwUpdate` APIs really affect the second. But that only changes what files will be served to future requests by the tab. It is not possible for the ServiceWorker (or any other API afaik) to "unload" the JavaScript code that the browser has already executed for this tab and replace it with new JavaScript code (and update the UI to much what it would have been if the new JS code was loaded from the beginning).

If you only care about future requests being served files from the latest version (which is more or less what would happen if you didn't have a ServiceWorker), then `SwUpdate#activateUpdate()` (without reloading) is enough. However, this is a risky state, because some of the files from the new version (for example, a lazy-loaded module) might not be compatible with the old code that is already being executed on the tab (i.e. from the old `main.js` file). Use this method only if you understand the implications and know that it is safe for your particular usecase.

If you care about updating the current executing JS, then I believe that is not possible (even outside Angular/ServiceWorkers).

One last thing:
There are different ways to handle version updates. You can read a bit about this [here][1].

##
I am going to close this issue, since there is no action for us (afaict), but feel free to continue the discussion below.

[1]: https://stackoverflow.com/questions/55494181/what-is-the-purpose-of-swupdate-activateupdate-in-angular/59175788#59175788

**Comment by rozzs74** [comment]
Thank you @gkalpak for detailed response, I will be implementing the third choice you have put in this topic https://stackoverflow.com/questions/55494181/what-is-the-purpose-of-swupdate-activateupdate-in-angular/59175788#59175788

The browser will reload, when navigating to the app. Thank you again for sharing ideas, more power to Angular team.
