### ISSUE TITLE
Cut, Copy, Paste using angularjs

### ISSUE THREAD

**Issue by Bhimisetty** [angular/angular#438]
Is there any possibility to perform Cut, Copy and Paste using the anuglarjs. I have seen the ng-clip to copy the data into the clipboard.But that copies total model. I want to work with selected text need to be cut and copy and need to paste that in the particular control after the cursor focused.And it should works in all browsers

**Comment by pkozlowski-opensource** [comment]
@Bhimisetty wrong repo, I guess you wanted to open this issue here: https://github.com/angular/angular.js

But to be honest support questions like this one are not the best fit for GitHub issues, please use one of the support channels listed here: https://github.com/angular/angular.js/blob/master/CONTRIBUTING.md#question
