### ISSUE TITLE
[router]: using @inject for ROUTE_DATA

### ISSUE THREAD

**Issue by cexbrayat** [angular/angular#4392]
Don't you think that having to use @Inject for ROUTE_DATA is a bit surprising compared to RouteParams which gives us a service? I think this is a very rare case (the only one?) where we can't rely on Type annotation in an app for something provided by the framework. And we obtain an object, whereas RouteParams provides a get method.

    constructor(routeParams: RouteParams, @Inject(ROUTE_DATA) routeData) {
      let id = routeParams.get('id');
      let name = ROUTE_DATA.name;
    }

A less surprising (and more coherent and friendly in my opinion) would be:

    constructor(routeParams: RouteParams, routeData: RouteData) {
      let id = routeParams.get('id');
      let name = routeData.get('name');
    }

(this is a follow up issue from #3541)

**Comment by cexbrayat** [comment]
cc @btford @TommyM @PascalPrecht

**Comment by gdi2290** [comment]
The injector allows for any token include types. I agree with @cexbrayat that we should allow the type token `RouteData` on the merit that it's a valid token. I guess naming conventions should also have ref in the name `RouteParamsRef` and `RouteDataRef`. The real problem here is that `ROUTE_DATA ` can only guarantee a shallow copy (since only two types are allowed array|object) as it's unaware of the types you provide. Unless data is a factory

```typescript
@RouteConfig([
  {
    path: '/metadata',
    component: MetaDataCmp,
    data() {
      return new AwesomeData('wat');
    }
  }
])
```
if not `RouteData` than perhaps `RouteConfigRef`

```typescript
constructor(routeParams: RouteParams, routeConfigRef: RouteConfigRef) {
  let id = routeParams.get('id');
  let name = routeConfigRef.get('data').name;
}
```

or perhaps the bindings in router-outlet is missing `bind(ComponentInstruction).toValue(nextInstruction)` and `RouteConfig` needs to include `bindings` prop. Adding these two seems to be the best option since anyone can create their own conventions

**Comment by mhevery** [comment]
:+1: for having `RouteData` type so that it can be cleanly injected.

**Comment by btford** [comment]
I think I'm convinced a type would be better.

PR welcome :)

**Comment by cexbrayat** [comment]
@mhevery @btford Thx for your answers.

Do we agree on a  ̀RouteData` type that we can inject, and which would offer a getter (as `RouteParams` does)?

    constructor(routeParams: RouteParams, routeData: RouteData) {
      let id = routeParams.get('id');
      let isAdmin = routeData.get('isAdmin');
    }

If so, I guess a `Route` data should be a simple object, like:

    new Route({path: '/user/:id', component: UserCmp, data: { isAdmin: true }})

Would that be OK?

**Comment by cexbrayat** [comment]
(I opened a related PR #4428 to start the discussion, feedback welcome)

**Comment by PascalPrecht** [comment]
@cexbrayat thanks for starting this, I already took a look and it LVGTM!
