### ISSUE TITLE
BrowserModule has already been loaded error when importing an angular library that imports BrowserModule

### ISSUE THREAD

**Issue by jbistis** [angular/angular#44015]
### Which @angular/* package(s) are the source of the bug?

platform-browser

### Is this a regression?

No

### Description

I am trying to use a component from an angular library (SharedModule) and get the console error:

**BrowserModule has already been loaded. If you need access to common directives such as NgIf and NgFor from a lazy loaded module, import CommonModule instead.**

Both the SharedModule from the library and the AppModule in the app have the imports
import { BrowserModule } from '@angular/platform-browser'; import { BrowserAnimationsModule } from '@angular/platform-browser/animations';

The library is imported into the AppModule using
import { SharedModule as pdlSharedModule } from 'pdl';

If I remove the Browser imports from SharedModule and try to use CommonModule instead, I get the console error message NullInjectorError: R3InjectorError(t)[y -> y -> y -> y]: when I try to access

If I remove the Browser imports from AppModule that gets the same NullInjectorError but on the first page.

[user.module.ts.txt](https://github.com/angular/angular/files/7460392/user.module.ts.txt)
[app.module.ts.txt](https://github.com/angular/angular/files/7460399/app.module.ts.txt)
[shared.module.ts.txt](https://github.com/angular/angular/files/7460419/shared.module.ts.txt)

This configuration worked in a9. 

### Please provide the exception or error you saw

```true
ERROR Error: Uncaught (in promise): Error: BrowserModule has already been loaded. If you need access to common directives such as NgIf and NgFor from a lazy loaded module, import CommonModule instead.
Error: BrowserModule has already been loaded. If you need access to common directives such as NgIf and NgFor from a lazy loaded module, import CommonModule instead.
    at new qe (main.js:1)
    at Object.qe.ɵfac [as factory] (main.js:1)
    at I3.hydrate (main.js:1)
    at I3.get (main.js:1)
    at main.js:1
    at Set.forEach (<anonymous>)
    at I3._resolveInjectorDefTypes (main.js:1)
    at new Wg (main.js:1)
    at If.create (main.js:1)
    at i.project (main.js:1)
    at A (polyfills.js:1)
    at A (polyfills.js:1)
    at polyfills.js:1
    at h.invokeTask (polyfills.js:1)
    at Object.onInvokeTask (main.js:1)
    at h.invokeTask (polyfills.js:1)
    at h.runTask (polyfills.js:1)
    at m (polyfills.js:1)
    at h.invokeTask [as invoke] (polyfills.js:1)
    at y (polyfills.js:1)
```

### Please provide the environment you discovered this bug in

```true
Angular CLI: 12.2.6
Node: 12.19.0
Package Manager: npm 6.14.8
OS: darwin x64

Angular: 12.2.6
... animations, cli, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router
```

**Comment by JoostK** [comment]
Please provide a reproduction.

**Comment by jbistis** [comment]
We are working on a small reproduction of the issue.

**Comment by jbistis** [comment]
You can see the issue in this simple app at repository https://github.com/jbistis/my-workspace.git.  To recreate, just click on the settings button.  The shared module in the library imports BrowserModule.  Without that import, the click errors with NullInjectorError: No provider for a!.  With the import, the click errors with BrowserModule has already been loaded.  This worked in angular9.

**Comment by petebacondarwin** [comment]
I think that this is indeed a bug in how the Angular expression is being converted to TS in the ivy handler.

The following expression

```ts
a?.fn(test(form.get('test')?.value))
```
is converted to
```ts
let tmp_b_0;
ctx.a == null ? null : ctx.a.fn(ctx.test((tmp_b_0 = tmp_b_0) == null ? null : tmp_b_0.value));
```

while the following expression
```ts
test(form.get('test')?.value)
```
is converted to
```ts
ctx.test((tmp_b_0 = ctx.form.get("test")) == null ? null : tmp_b_0.value);
```


Note that in the first case we have:

```ts
ctx.test((tmp_b_0 = tmp_b_0) == null ? null : tmp_b_0.value)
```

while in the second:

```ts
ctx.test((tmp_b_0 = ctx.form.get("test")) == null ? null : tmp_b_0.value);
```

So in the first case tmp_b_0 is always `undefined`...

**Comment by JoostK** [comment]
@petebacondarwin I think you wanted to comment #44069.

**Comment by petebacondarwin** [comment]
> @petebacondarwin I think you wanted to comment #44069.

Yep. Moved my comment there. 😅

**Comment by JoostK** [comment]
This seems to be working as expected. The usage of `BrowserModule` in the lazily loaded `SharedModule` is indeed not supported, which the error message is correctly telling you. The solution to this error is to remove `BrowserModule` from `SharedModule` (not `AppModule`!).

As for the injection error, that's also expected to me. `SettingsContainerComponent` renders `InputTextComponent` in its template, which injects the `FormContainerComponent` component as a dependency in its constructor. The `FormContainerComponent` is not an ancestor of `FormContainerComponent`, however, so the injection fails. I don't see how this could have worked in Angular 9 as you mentioned, as this setup appears to be broken.

Unrelated, it appears that the project has been updated without `ng update`, resulting in some migrations not to have run. This causes your `ng serve` to result in a production build, which is why you get the somewhat unreadable `NullInjectorError: R3InjectorError(t)[y -> y -> y -> y]` as the `y` token is a minified class name (which is actually the `FormContainerComponent` class). Running the migrations gets you a development build, as expected: 

```
ng update @angular/cli --from 11 --to 12 --migrate-only
```

If you share a reproduction of the Angular 9 situation I can have another look, as without it I can't tell how this used to work. Please ensure that it's the exact same setup, other than the Angular version.
