### ISSUE TITLE
[ngFor] trackby equivalent ?

### ISSUE THREAD

**Issue by cexbrayat** [angular/angular#4402]
I don't think there is an equivalent of AngularJS 1.x `trackBy` for `ngFor` right now (alpha-37). 
Is there a way to do the same (maybe using a custom `IterableDiffers`, but that looks like a bit difficult...), or is it a feature planned for later?

**Comment by PascalPrecht** [comment]
I think more interesting here is, if this feature is still needed in A2

**Comment by mhevery** [comment]
The feature is needed and needs to be implemented.

**Comment by mhevery** [comment]
Plunker demonstrating the need for track by: http://plnkr.co/edit/HHGDsAg2ioTfOsfNcMPU

**Comment by Schnueggel** [comment]
I would need this too. I want to work with a state tree that reflect the current state of the app. At the moment this is not possible with ngFor because it always recreates a component when the reference changes. With Immutable Objects this is always true. It would be good if changes can be tracked with different strategies. Lets say I track by id and the reference to an item changes but the id will remain only the locals of the view will update which means the inputs of this component change.

If for example your component listen on a blur event of a input which will trigger a state changes but also has a click listener on a other part. The click listener will never get called when you click, if the blur event also happens, because the blur change the state and this will force the recreation of the component. 

At the moment I see in the NgFor only the option for recreation, removing, reordering and do nothing but not updating the locals

**Comment by mhevery** [comment]
@kara will be working on this as a start project.

**Comment by mhevery** [comment]
## Proposed API for `ngFor`

```
@Component(
  template: `<div *ngFor="var item in items; trackBy=customTrackBy">{{item}}</div>`
)
class MyCoponent {
  customTrackBy(index: number, obj: any): any {
    return index;
  }
}
```

Initial implementation: https://github.com/mhevery/angular/tree/trackByStarter

**Comment by PascalPrecht** [comment]
That's awesome!

**Comment by cexbrayat** [comment]
Issue can be close now that @kara merged the PR

**Comment by kara** [comment]
Usage:

```
@Component(
  template: `<template ngFor #item [ngForOf]="items" [ngForTrackBy]=customTrackBy">{{item}}</template>`
)
class MyComponent {
  customTrackBy(index: number, obj: any): any {
    return index;
  }
}
```

**Comment by Meligy** [comment]
Hi @mhevery and @kara,

Would it make sense to change the trackBy syntax to be more like Angular 1 (and even Angular 2 event handlers)?

I mean making it a function call instead of a function definition.

Then the example that Kara put will be simplified to:

```
@Component(
  template: `
   <div *ngFor="#item of items; trackBy: index">
      {{item}}
   </div>
   `
)
class MyComponent {
}
```

A simple property accessor, or simply an index reference, is likely to be a common usage scenario. It'll be call if we don't have to create functions for them. I worked with Polymer for a while and having to create functions for everything was a bit silly.

Is that a good suggestion? Do you think I should create a new issue for it or so?

Thanks a lot, for all the awesome work on Angular :-)

**Comment by Meligy** [comment]
Hi @mhevery and @kara,

Would it make sense to change the trackBy syntax to be more like Angular 1 (and even Angular 2 event handlers)?

I mean making it a function call instead of a function definition.

Then the example that Kara put will be simplified to:

```
@Component(
  template: `
   <div *ngFor="#item of items; trackBy: index">
      {{item}}
   </div>
   `
)
class MyComponent {
}
```

A simple property accessor, or simply an index reference, is likely to be a common usage scenario. It'll be call if we don't have to create functions for them. I worked with Polymer for a while and having to create functions for everything was a bit silly.

Is that a good suggestion? Do you think I should create a new issue for it or so?

Thanks a lot, for all the awesome work on Angular :-)

**Update:**

I realise this might change the order `trackBy` is evaluated, as it will have to be after the identifiers for loop item, and index, etc are defined already. I'm not sure of how simple or even feasible this may be, but I sure hope it's not a deal breaker.

**Comment by nuthalapativarun** [comment]
Hey @kara @mhevery , I'm trying to implement inline editing in Angular2 and i'm using ngFor and ngModel combined to implement this. But when i'm trying to iterate through the array and trying to edit, I can only enter or remove one letter. I've attached the working problem: https://plnkr.co/edit/7SSpZDec2N2zjrSUM04X?p=preview . Can you please help me here.

Thanks.
