### ISSUE TITLE
chore(decorators): rename @Injectable decorator

### ISSUE THREAD

**Issue by PascalPrecht** [angular/angular#4404]
When building Angular 2 apps in TypeScript, we have cases where we need to enforce metadata generation by adding **any** decorator to a class. This is explained in detail here: http://blog.thoughtram.io/angular/2015/09/17/resolve-service-dependencies-in-angular-2.html

For example, the following services (just a class) has a dependency, but TS doesn't emit decorator metadata, because there are no decorators on that class:

```
class DataService {

  constructor(http: Http) {

  }
}
```

We can enforce TS to emit metadata by adding a decorator to that class:

```
@Foo()  // causes TS to emit metadata
class DataService {

}
```

Of course, using just **any** decorator feels hacky. Angular already has a decorator `@Injectable()` that is actually used for Dart. Currently we use that one to that use case:

```
@Injectable()  // causes TS to emit metadata
class DataService {

}
```

It turns out that "Injectable" as a word doesn't really fit to what is happening here and that confuses users. Based on the name one can think that we make `DataService` an injectable service, but in fact we actually want to say something like "Hey TS, please emit metadata for this class".

I'm not sure if `@Injectable()` has a special meaning in Dart, or if it's also yet another decorator that is used to generate some metadata. If the former is the case, we should consider introducing a new decorator with a better name. Otherwise we should rename `@Injectable()` to something more appropiate.

Here are some suggestions:

- `@InjectedParameters`
- `@HasInjectables`
- `@HasInjects`
- `@Injected`
- `@EmitMetadata`
- `@GenerateMetadata`

This change could also be considered a **BREAKING CHANGE**.

Ideally, TS is going to get better at this and we could remove `@Injectable()` (or the new name) entirely, since that's actually unrelated to Angular. But it doesn't look like TS is going to introduce anything like that in the near future.

@mhevery @vsavkin would love to hear your thoughts on this.

/cc @wardbell @cburgdorf

**Comment by vicb** [comment]
We're not using reflection in Dart because it would metadata for **all** the classes. The `@Injectable()` annotation is used by the transformer to trigger metadata generation.

That's quite similar to why `@Injectable()` is required in TS (while it could be any decorator for TS).

IMO `@Injectable` is a reasonable name.

**Comment by wardbell** [comment]
"*`@Injectable` is a reasonable name.*"

I guess I see where you're coming from.  But the objection is reasonable.

In fact, the  `@Injectable` decoration really means that this thing expects to have *its own* dependencies injected.  

The problem with `@Injectable` is that it means ***exactly the opposite of what it does**. It means that the decorated class *can be injected into something else*. It is "capable of being injected." Something "touchable" can be touched. Something "injectable" can be injected.

That isn't what this decoration means at all. When I write
```
@Injectable()
class Foo{ }
```
it would seem that I'm adding the decoration to tell Angular (and the reader) that `Foo` can be injected.

That is false. The decoration is completely unnecessary. `Foo` is injectable in something else with or without that decoration.

I only need this decoration if the class has a constructor with dependencies that should be injected into it.

The following class requires the `@Injectable` decoration because its constructor expects a dependent `Foo` instance to be injected into it.
```
@Injectable()
class Bar{ 
  constructor(foo:Foo) { }
}
```
A more accurate (if horrible) decoration name might be `@HasDependencies` 

The naming catches the developer off-guard. S/he thinks s/he has to add `@Injectable()` to every class that might be injected. In fact, s/he only needs to add that decoration if the class has an injected dependency of its own.

One could argue for keeping the name `@Injectable" as follows:
1. It's done; too late
1. It is harmless to add it to a class with a parameterless ctor
1. It only matters if I'm going to inject the target class into something else. I won't actually be able to do that ... the `Bar` class can't be injected ... isn't "injectable" ... unless its own dependencies are injected. Otherwise, the Injector can't construct it.

#3 is the decisive part of the argument.  The addition of the `@Injectable` decoration makes it possible for the Injector to construct a `Bar` and inject that into some consumer of `Bar`.

Therefore, I move that we accept the present state of things and move on.

Pascal and Christoph will have to find a way to explain this to the reader.

**Comment by vicb** [comment]
```
@Injectable()
class Foo{ }
```

> In fact, this decoration is completely unnecessary. Foo is injectable into something else with or without that decoration.

I'm probably biased by my Angular Dart background: in Dart there is no way to know if the class has dependencies unless you have some kind of reflection info that is `Foo.length` is not available in Dart & `@Injectable()` isn't optional.

**Comment by jessegood** [comment]
Why not make create another separate decorator for TS use and leave `@Injectable()` for ts2dart only?

**Comment by dsebastien** [comment]
It's kind of funny how naming things is actually one of the hardest things in IT :)

With Spring in Java, we have the @Autowired annotation for the same purpose (not anything related to metadata generation, but simply as a means to state that dependencies of the annotated class should be injected by the DI system): http://docs.spring.io/autorepo/docs/spring-framework/3.0.x/api/org/springframework/beans/factory/annotation/Autowired.html

@RequiresDependencyInjection or @RequiresDI could be another meaningful name for this.

**Comment by mgechev** [comment]
The issue makes sense to me. Here are my thoughts on the suggested names:

- `@InjectedParameters` - I like it but also find it a little bit confusing because of the past tense.
- `@HasInjectables` - I like it, makes sense.  Not sure how clear it is that the DI is required for resolving the arguments of the constructor.
- `@HasInjects` - `Injects` is a bit confusing for me.
- `@Injected` - It doesn't carry enough semantics.
- `@EmitMetadata` - It is too abstract, developers should be aware of how the DI works.
- `@GenerateMetadata` - Same as the one above.
- `@RequiresDI` - I like it, makes sense. Not sure how clear it is that the DI is required for resolving the arguments of the constructor.
- `@RequiresDependencyInjection` - Same as above but too verbose.
- `@HasDependencies` - It doesn't carry enough semantics, it doesn't indicate that the dependencies should be injected.

One more suggestion `@AcceptsInjectables`.

**Comment by PascalPrecht** [comment]
> I believe @Injectable() was never intended to be used by framework consumers.

@jessegood It was surely not the intention, but it just happens that it's a decorator lying a round there, that can be used to workaround the issue. We **do** need a way to enforce TS to emit metadata.

> @EmitMetadata - It is too abstract, developers should be aware of how the DI works.

@mgechev sure they have to, but in the end it's a thing that TS should do (even if we're not using Angular's DI). So it maybe something generic like `@EmitMetadata()` is a good fit. Because that what it enforces TS to do after all.

**Comment by TommyM** [comment]
Some more suggestions:

@Populate
@PopulateInjections
@EnableDI
@NeedsInjections
@InjectDependencies

**Comment by ericmartinezr** [comment]
I think we should stop thinking about the word Injection. That's limiting the options. The purpose of @PascalPrecht proposal is to emit the metadata to bind a class into some component. In most cases we use for Services, so what about `@Service()`? Or maybe something more generic, thinking that it will be injected into `bindings/viewBindings`, like `@Bindable()`.

**Comment by TommyM** [comment]
@ericmartinezr The decorator is not needed to make the class itself injectable/bindable, which is why ```@Injectable``` is not a great name and why @PascalPrecht is suggesting to rename it. We actually need the decorator to have DI be able to inject into the constructor of the class itself. ```@Bindable```, just like ```@Injectable``` also gives us the impression that we make the class itself injectable/bindable.

@PascalPrecht 's blogpost http://blog.thoughtram.io/angular/2015/09/17/resolve-service-dependencies-in-angular-2.html explains this very well.

**Comment by mgechev** [comment]
@PascalPrecht with `@EmitMetadata()` we're getting tightly coupled to the underlaying language used for the implementation (i.e. TypeScript).
It might be a good idea to have such decorator for enforcing the meta data generation in the general case but when talking about dependency injection something more specific could be more suitable.

**Comment by pkozlowski-opensource** [comment]
I must say that I kind of like the `@Service` idea from @ericmartinezr .

I saw a similar approach in Spring framework where there are annotations like `@Service`, `@Controller` etc. Those annotations don't do much but serve 2 important purposes:
* allow DI to consume those
* add more "documentation" / context to what a given class does / what it the purpose of it.

I agree that `@EmitMetadata` (and similar proposals) is too low-level / TS-specific.

**Comment by TommyM** [comment]
I like ```@Service``` as well. It describes the purpose of the class, and fits nicely in the list of ```@Component```, ```@View```, ```@Directive``` etc.

**Comment by ericmartinezr** [comment]
@TommyM You could say that of any proposed naming, so I think the main issue is the fact that "is not needed", probably this issue should be tackled from another angle : force the user to add some decorator in the classes being injected through `binding/viewBindings`, this way metadata will be emitted no matter what.

So, if we have something like this

```typescript
class DataService {}
bindings : [DataService]
```
it should throw something like 

```
Oh noes! You forgot to add @TheNeededDecorator, pls add!
```

Because so far every proposed name will fail the same way, if it is not added it will blow up your entire machine. 

I think it should be even more specific, if I add `@Injectable` it should not work, but if I add `@Service` should work nicely, because, again, so far any decorator would do the trick.

**Comment by PascalPrecht** [comment]
Having sth. like @Service might encourage ppl to *always* put @Service on a
service class because... Well, it's a service. This would take us to the
original problem that metadata is generated even though it's not needed.

Which means we have to explain in any case why and when this @Service
decorator needs to be added and when not. And as soon as we do that, we're
talking about the underlying nature of TS anyways.

That's why I'd vote for something that isn't necessarily framework
specific. But I'm happy to get more arguments that speak *for* @Service

**Comment by robwormald** [comment]
Ha, I just posted "services" as the replacement for bindings over in #4416, so +1 on `@Service` for me.

**Comment by robwormald** [comment]
@PascalPrecht 
> Which means we have to explain in any case why and when this @Service
decorator needs to be added and when not. And as soon as we do that, we're
talking about the underlying nature of TS anyways.

Fair point, but my answer to that is kind of "so what?" It's a lot better to have a bit of extra metadata than have the whole thing blow up without it. I dunno.

**Comment by mhevery** [comment]
1) I am fine for renaming
2) None of the suggestions so far are objectionably any better then what we currently have

So unless we could come up with good alternative we are stuck with status quo. 

My rules:
1) Less words is better `Injectable` is better then `EmitMetadata`

**Comment by wardbell** [comment]
I vote to keep `@Injectable` and move on.  As I am the person who objected to this name early on this I am now filled with regret.

First, we wouldn't have to worry about this if there were pragmas (per @robwormald ).  But we don't have it.

Second, if we must have it, the name should convey what in means to the developer, not how it works. Therefore, I am opposed to anything like "emit metadata".

Third, `@service` is kind of nice but is limited to something that the developer thinks of as a service.  I'd more inclined toward `@dependency` ... if I wanted to change it at all.

Fourth, I fully understand the objection that the decoration helps the injector inject into the thing. I made that objection myself. But the fact is that we only care about whether the injector can inject something into the class if we ALSO intend to inject this class into something else.  In short, we only bother to put this decoration on the class if we intend to inject this class into something else ... which is to say, if we intend for this class to be injectable.  **Therefore, `@Injectable` is accurate w/r/t my intentions**.

Fifth, as @robwormald observes, it is almost irrelevant if the unwary developer decorates a class with `@Injectable` unnecessarily.  The amount of extra metadata material generated into the JS is tiny compared to the boat-load of crappola that gets generated anyone just to support `class`.

On balance, given the ramifications of changing, the lack of clear benefit, and the tremendous amount of real work we have yet to do ... I say keep it as it is.

**Comment by robwormald** [comment]
I'm filled with regret for even mentioning the word "pragma" anywhere near a JS project, so we're even.

> what it means to the developer rather than how it works

That's sort of why I suggested "service". It keeps the "things in Angular you build" scoped to 'Component', 'Directive', and 'Service' - which is a reasonably simple thing to grok.

**Comment by PascalPrecht** [comment]
> Fifth, as @robwormald observes, it is almost irrelevant if the unwary developer decorates a class with @Injectable unnecessarily. The amount of extra metadata material generated into the JS is tiny compared to the boat-load of crappola that gets generated anyway just to support class.

Keep in mind that this isn't just code size. It can also have impact on the applications runtime performance since there are unnecessary calls to `__metadata()`.

**Comment by wardbell** [comment]
@PascalPrecht I might. One might list "Remove unnecessary `@Injectable` decorations" among the perf optimization techniques.  The bigger problem is finding a term that won't trigger the dev to apply this decoration anyway "as a precaution". I'm not sure that is solvable.

**Comment by robwormald** [comment]
Valid point.

Just to murky the waters a biiiit more, the issue that this little hack is solving isn't making it "injectable" or a "dependency" - its notating that it "injects" or that it "has dependencies" 

/me ducks

**Comment by wardbell** [comment]
"@HasDependencies" was my favorite but I think we have bigger fish to fry.

**Comment by mhevery** [comment]
We are going to stay with `@Injectable` since no proposal is materially different.

**Comment by dabalyan** [comment]
I am probably too late but what about
**`@Dependent`** :  simply means it depends on something, meaning that it has dependecies
or
**`@Injectables`** (with an 's'):  could mean that it expects Dependencies( Injectable Services) to be injected
