### ISSUE TITLE
Question: Preferable to perform JSON parsing based on server provided content type?

### ISSUE THREAD

**Issue by msbit** [angular/angular#44108]
### Which @angular/* package(s) are the source of the bug?

common

### Is this a regression?

No

### Description

This is not a bug, simply a question.

I was fooling around with a local server and receiving parse errors due to the server returning responses with `Content-Type: text/plain` always, and saw that, at:

https://github.com/angular/angular/blob/8a99ef18b4ae58736f0b7457e88908d3adcad613/packages/common/http/src/xhr.ts#L160

the nominated type of the request is checked (`req.responseType === 'json'`) not the actual content of the response (which would be available via `headers.get('Content-Type')` at that point).

Wouldn't it make more sense to check the content type the server is providing for the response, even if it doesn't match the expected response type?

Thanks for your consideration ✌️

### Please provide the environment you discovered this bug in

```true
12.2.13
```

**Comment by petebacondarwin** [comment]
Hi @msbit - thanks for the question. It is a good one.

As far as I understand it, this is a design decision. There are servers that return JSON but do not mark the type in a response header. The aim here is to provide the most flexibility and power over the widest range of servers.

By allowing the user of `HttpClient` to specify the response type, the library is able to override what is sent back from the server, while also providing better type narrowing of the response object itself.

Further, the request object can be modified by HttpInterceptors. Here you could check things like the headers or the actual value and update the response type accordingly if desired.

Finally, the fact that the JSON processing is somewhat hard-coded into the library is a legacy concern that perhaps should have been avoided; but changing this now is difficult since it could cause extensive breaking changes across many projects.

I hope this gives enough insight into the design and answers your question. I'll close this issue for now, as the issue tracker is already overloaded with bugs and feature requests, and we are trying to keep the list as focussed as possible. If you have further questions please post them here.

**Comment by msbit** [comment]
Thanks @petebacondarwin for a well thought-out response;  that all makes sense. I will take a look through the `HttpInterceptor`s to see how to customise this behaviour for my purposes.
