### ISSUE TITLE
Animation not working when combined query selector with tokens

### ISSUE THREAD

**Issue by thirumanidev** [angular/angular#44101]
### Which @angular/* package(s) are the source of the bug?

animations

### Is this a regression?

No

### Description

I'm trying to animate child element with query selector(class name) & token(:enter),
but it throws error as follwoing
_ERROR
Error: Unable to process animations due to the following failed trigger transitions
@animation1 has failed due to:

- `query(".text4:enter")` returned zero elements. (Use `query(".text4:enter", { optional: true })` if you wish to allow this.)_

**I mean it:**
https://angular.io/api/animations/query#usage-notes

### Please provide a link to a minimal reproduction of the bug

https://stackblitz.com/edit/angular-ivy-rtayah?file=src/app/app.component.ts

### Please provide the exception or error you saw

```true
ERROR
Error: Unable to process animations due to the following failed trigger transitions
@animation1 has failed due to:

- `query(".text4:enter")` returned zero elements. (Use `query(".text4:enter", { optional: true })` if you wish to allow this.)
```

### Please provide the environment you discovered this bug in

```true
Angular CLI: 11.2.7
Node: 14.17.4
OS: win32 x64

Angular:
...
Ivy Workspace:

Package                      Version
------------------------------------------------------
@angular-devkit/architect    0.1102.7 (cli-only)
@angular-devkit/core         11.2.7 (cli-only)
@angular-devkit/schematics   11.2.7 (cli-only)
@schematics/angular          11.2.7 (cli-only)
@schematics/update           0.1102.7 (cli-only)
```

**Comment by mslooten** [comment]
I think you need to either let the animation control the visibility of your child element (look into sequence or stagger), or create a separate trigger for your element. Right now, within your current animation the element is not found because Angular doesn't render it yet (because of the if-statement). Your example looks like it should all be controlled from the animation, like a sequence of events. However, if you just want a condition to control the animation, you can add a separate trigger: https://stackblitz.com/edit/angular-ivy-vsa8b4

**Comment by thirumanidev** [comment]
Hi @mslooten, thanks for your quick reply.

I think, the token(:enter, :leave) can control the visibility or presence in the DOM for an element.
And according to the angular.io document, it should have worked, right?

**Comment by mslooten** [comment]
Hi @thirumanidev, ah I understand. Looking at the docs it should be possible, the usage notes example is basically what you're trying to do.

Edit:
I did manage to get it working in your example by moving the timer function to the ngOnInit hook instead of having it in the constructor. I think that's better anyway. In this case, because the code is in the constructor, it's running before Angular has finished initialising all data-bindings.

**Comment by thirumanidev** [comment]
Hi @mslooten,
I tried your idea in my example, moved the timer call from constructor to ngOnInit, it doesn't work.

**Comment by dario-piotrowicz** [comment]
Hi @thirumanidev please check your stackblitz and notice that the error in the console appears right away and not when you set `boo` to true (setting boo to `true` doesn't actually trigger and sort of animation as you are not bounding `boo` to your trigger in any way)

So when your `div` component enters the DOM, its `* => *` transition gets triggered and in it the queries will be executed, including the `query(".text4:enter", [` but at that point the `.text4` element isn't actually present (because `boo` starts as `false`), so I think this is totally the expected behaviour

Am I missing something? :thinking: 

___

PS I am not too sure what you mean with the following:
> I think, the token(:enter, :leave) can control the visibility or presence in the DOM for an element.
And according to the angular.io document, it should have worked, right?
but the `query` function only "queries"/"looks for" element, it doesn't affect at all it's presence or lack thereof in the DOM

**Comment by jessicajaniuk** [comment]
It appears this behaves as expected. If you still feel there is an issue, please provide further details in a new issue.
