### ISSUE TITLE
Child Animation works without calls of animateChild() if the child element having *ngIf condition

### ISSUE THREAD

**Issue by thirumanidev** [angular/angular#44100]
### Which @angular/* package(s) are the source of the bug?

animations

### Is this a regression?

No

### Description

`<div class="content" @animationForParent>
  <div @animationForChild >
    <h3>Without *ngIf condition, animation(Yellow BG color) doesn't applied.</h3>
  Lorem ipsum dolor sit amet consectetur adipisicing elit. Corporis repellat labore molestias enim tempora autem placeat quisquam recusandae. 
</div>
  <div @animationForChild *ngIf="boo">
    <h3>With *ngIf condition, animation(Yellow BG color) applied.</h3>
    Lorem ipsum dolor sit amet consectetur adipisicing elit. Corporis repellat labore molestias enim tempora autem placeat quisquam recusandae. 
  </div>
</div>`

In above code, you could see 2 div elements contains the @animationForChild trigger, but
this div doesn't applied animation=> <div @animationForChild ></div>
but this div applied animation=>   <div @animationForChild *ngIf="boo"></div>

https://angular.io/guide/transition-and-triggers#parent-child-animations
As per your document, it says as while parent animation gets priority, the child's animation will be blocked, but it works as you said unless it doesn't have *ngIf condition.
May I know, why?

### Please provide a link to a minimal reproduction of the bug

https://stackblitz.com/edit/angular-ivy-jhd2ys?file=src/app/app.component.ts

### Please provide the environment you discovered this bug in

```true
Angular CLI: 11.2.7
Node: 14.17.4
OS: win32 x64

Angular:
...
Ivy Workspace:

Package                      Version
------------------------------------------------------
@angular-devkit/architect    0.1102.7 (cli-only)
@angular-devkit/core         11.2.7 (cli-only)
@angular-devkit/schematics   11.2.7 (cli-only)
@schematics/angular          11.2.7 (cli-only)
@schematics/update           0.1102.7 (cli-only)
```

**Comment by dario-piotrowicz** [comment]
@thirumanidev The reason as to why the second element is animating but the first is not is because you have a `* => *` transition for the `animateForChild` trigger:

![Screenshot at 2021-11-21 16-25-01](https://user-images.githubusercontent.com/61631103/142770412-99e01073-1447-425b-ae4c-287ffc52e5fb.png)

the second element, appearing after some time triggers that transition since it is entering the DOM, the first element is already there from the start so it is not animated

This really really looks like the expected behaviour to me, could you please explain what you would expect to happen instead? :thinking:

**Comment by jessicajaniuk** [comment]
It appears this behaves as expected. If you still feel there is an issue, please provide further details in a new issue.
