### ISSUE TITLE
Service Worker performance strategy ignores images

### ISSUE THREAD

**Issue by fstorz** [angular/angular#44246]
### Which @angular/* package(s) are the source of the bug?

service-worker

### Is this a regression?

Yes

### Description

When adding service worker to angular app and configure `dataGroups` cache `strategy` to `performance`, matching images are not cached. When using the same project with `strategy` set to `freshness`, images are cached for offline use.

```json
  "dataGroups": [
    {
      "name": "images",
      "cacheConfig": {
        "maxAge": "10d",
        "maxSize": 10,
        "strategy": "performance",
        "timeout": "10s"
      },
      "urls": [
        "https://**/*.jpg"
      ]
    }
  ]
```

To Reproduce:
* clone linked repo (Angular CLI project enhanced with `ng add @angular/pwa`)
* build project: `ng build` (no `--prod` needed as production build is the default)
* serve build files by e.g. http-server (`http-server dist/Image-Cache-Service-Worker`)
* open browser on http://localhost:8080
* Check in DevTools that image is not cached

![image](https://user-images.githubusercontent.com/27813536/142867704-06697203-e286-499f-a972-b9e08d1b39d7.png)

When following above steps but changing the cache strategy to freshness, the image is cached (at least after one reload of the page).

![image](https://user-images.githubusercontent.com/27813536/142868218-c7e8f6b0-7b6b-4886-a7f3-df5563579604.png)

### Please provide a link to a minimal reproduction of the bug

https://github.com/fstorz/angular-service-worker-image-cache-bug-demo

### Please provide the environment you discovered this bug in (run `ng version`)

```true
Angular CLI: 12.2.13
Node: 17.0.1 (Unsupported)
Package Manager: npm 8.1.0
OS: darwin x64

Angular: 12.2.13
... animations, cli, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, router
... service-worker

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1202.13
@angular-devkit/build-angular   12.2.13
@angular-devkit/core            12.2.13
@angular-devkit/schematics      12.2.13
@schematics/angular             12.2.13
rxjs                            6.6.7
typescript                      4.3.5
```

**Comment by gkalpak** [comment]
Thx for reporting this, @fstorz!

This is indeed a bug. The reason this works differently depending on the strategy is that the internal [handleFetchWithFreshness()][1] and [handleFetchWithPerformance()][2] methods treat opaque responses differently. The former calls [safeCacheResponse()][3] with the `okToCacheOpaque` argument set to `true`, while the latter calls it with the `okToCacheOpaque` argument set to `false` (leading in ignoring opaque responses (such as the one you get here) and not caching them).

[1]: https://github.com/angular/angular/blob/62146365804ba4f50fb87f3173792d7a1dd3f97f/packages/service-worker/worker/src/data.ts#L379
[2]: https://github.com/angular/angular/blob/62146365804ba4f50fb87f3173792d7a1dd3f97f/packages/service-worker/worker/src/data.ts#L340
[3]: https://github.com/angular/angular/blob/62146365804ba4f50fb87f3173792d7a1dd3f97f/packages/service-worker/worker/src/data.ts#L449-L451

**Comment by gkalpak** [comment]
I was thinking some more about this today and I believe the current behavior is intentional:

When we get an opaque response, we cannot tell whether the request was successful or not (i.e. if we got the requested data or an error response, such as 404).

For data-groups with the `freshness` strategy, it doesn't matter if we cache an error response, because the data will be requested anew every time (and we will only fall back to the cached response when offline/on a slow connection).

For data-groups with the `performance` strategy however, caching an error response would be quite problematic, because the SW will continue to serve the error response until `maxAge` expires (even if the error was due to a temporary network or server issue).

##
So, here are the options I am thinking about now:

1. Document this behavior and explain the reasoning behind it. People can then choose to either implement CORS (if they control the origin) or put requests affected by this issue to a separate data-group with the `freshness` strategy and probably a small timeout (potentially 0).

2. In addition to documenting it, add a new option to the data-group [cacheConfig][1] object to allow configuring how to handle opaque responses. The defaults will still be "cache" for `freshness` and "don't cache" for `performance`, but people will be able to override that for specific groups.

##
@fstorz, wdyt? Does that sound reasonable?

[1]: https://angular.io/guide/service-worker-config#cacheconfig

**Comment by fstorz** [comment]
@gkalpak From my perspective it would be the best option to allow most flexibility as far as possible, which would fit to your 2nd option. It would be great (if not yet there) that your explanation would be added to the documentation of the cacheConfig :)
