### ISSUE TITLE
Lazy loading at component level

### ISSUE THREAD

**Issue by zehavibarak** [angular/angular#44284]
### Which @angular/* package(s) are relevant/releated to the feature request?

common, compiler, core

### Description

We have a project with components that dependes on other packages.

The current lazy loading is built on top of the @angular/router package. 
However, in our scenario, these components are embedded by demand at runtime using ViewContainerRef.createComponent() and cannot be splited into router paths.

### Proposed solution

Enable component to provide dependency modules
```
@Component({
   dependencies: [ChartModule]
})
``` 
This should work when using ViewContainerRef.createComponent() as well.

The cli should be anable to split code into chunks. 

### Alternatives considered

Manually split code to chunks and add scripts from server on demand.

**Comment by alan-agius4** [comment]
Hi,

With Standalone Components feature which was in discussion up until a couple of weeks ago ([see RFC](https://github.com/angular/angular/discussions/43784)) it should be possible to get better ergonomics to load Components (see the `Components: lazy loading and instantiation` section of the RFC).

Closing this for now since this falls part of the Standalone Components feature.
