### ISSUE TITLE
Properties of class hidden for the trackby function

### ISSUE THREAD

**Issue by jeromflo** [angular/angular#44307]
### Which @angular/* package(s) are the source of the bug?

common

### Is this a regression?

Yes

### Description

if set a properties of class with the value of acces on trackby, trackby can't acces of him properties. For example, this: 

```
sameDaddy(index, item) {
    console.log(this.elementCompareToogle);
    if (this.orderReturnValue) {
      return item.value[this.elementCompareToogle];//dentro de la funcion no carga el elementCompareTrackBy 
    } else {
      return item.value['pos1'];
    }
  }
```
I think that the function send for reference and have different scope than this.elementCompareToogle. Because if i called the funcion on template with interpolation the function grab well the value of properties,  The same pass with the child trackby.
Class of use: 
```
import { BaseTableComponent } from './../base-table/base-table.component';
import { Component, OnInit, Output, EventEmitter } from '@angular/core';

@Component({
  selector: 'app-table-map',
  templateUrl: './table-map.component.html',
  styleUrls: ['./table-map.component.css']
})
export class TableMapComponent extends BaseTableComponent implements OnInit {
  @Output() onClickButton = new EventEmitter();
  constructor() {
    super();

  }

  ngOnInit(): void {
  }
  handlerAccion(data) {
    this.onClickButton.emit(data);
  }
  sameDaddy(index, item) {
    console.log(this.elementCompareToogle);
    if (this.orderReturnValue) {
      return item.value[this.elementCompareToogle];//dentro de la funcion no carga el elementCompareTrackBy 
    } else {
      return item.value['pos1'];
    }
  }
  sameChild(index, item) {
    super.sameChild(index, item);
  }
}
```

The html:
`<div *ngIf="mostrarError==0">
    <ftcomun-alert-message [msg]="tittleError" [type]="'error'"></ftcomun-alert-message>
</div>
<div *ngIf="orderReturnValue">
    <table datatable [dtOptions]='dtOptions' [dtTrigger]="dtTrigger" class="table table-striped table-responsive ">
        <thead>
            <tr>
                <th class=" align-middle">Seleccionar</th>
                <th class="align-middle" *ngFor="let item of headTable|keyvalue;let i =index">

                    <span> {{item.value}}
                    </span>

                </th>

            </tr>
        </thead>
        <tbody>

            <tr *ngFor="let itemDad of data|keyvalue; let i=index;**trackBy:sameDaddy**">
                {{sameDaddy(i,itemDad)}}
                <td class="align-middle">
                    <input [attr.disabled]='disableCheckBox(itemDad)' (click)="toogleCheck(itemDad.value)" type="checkbox" />
                </td>
                <td class="align-middle" *ngFor="let itemChild of itemDad.value|keyvalue;let j=index;trackBy:sameChild;">
                    {{itemChild.value?itemChild.value:"Sin valor"}}
                </td>
                <td class="align-middle">
                    <button (click)="handlerAccion(data[i])" class="btn "><span style='color: rgb(148, 138, 138)'><i
                                class='fas fa-map-marker-alt'></i></span></button>
                    
                </td>
            </tr>
        </tbody>
    </table>

    <app-table-button (onButton1)='handlerEmitirSeleccionadosButton1()' (onButton2)='handlerEmitirSeleccionadosButton2()' [valueButton1]='valueButton1' [valueButton2]='valueButton2'>

    </app-table-button>
</div>`

### Please provide the exception or error you saw

```true
Without exceptions
```

### Please provide the environment you discovered this bug in (run `ng version`)

```true
_                      _                 ____ _     ___ 
    / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
   / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | | 
  / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | | 
 /_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
                |___/
    

Angular CLI: 12.2.13
Node: 14.17.6
Package Manager: npm 6.14.15
OS: win32 x64

Angular: 12.2.13
... animations, cli, common, compiler, compiler-cli, core, forms
... localize, platform-browser, platform-browser-dynamic, router

Package                         Version
---------------------------------------------------------       
@angular-devkit/architect       0.1202.13
@angular-devkit/build-angular   12.2.13
@angular-devkit/core            12.2.13
@angular-devkit/schematics      12.2.13
@angular/cdk                    12.2.12
@schematics/angular             12.2.13
rxjs                            6.6.7
typescript                      4.3.5
```

### Anything else?

No more

**Comment by jeromflo** [comment]
the sameChild is this: 
 ```
sameChild(index, item) {

    return item.value;
  }
```

**Comment by JoostK** [comment]
This is not an Angular bug, it's how JavaScript works.

A class method behaves the same as a regular function, where the `this` pointer is dependent on how the function is called. Class members are typically called using `this.foo()` or `car.getEngine()`, where the _receiver_ of the call (`this` in the first example, `car` in the second example) becomes the `this` pointer in the method call.

By passing just the method `sameDaddy` as `trackBy` function to `NgFor`, the `NgFor` instance never gets access to the component instance. As a consequence, its invocation of the method will _not_ have the component instance as `this` pointer. Instead, the method ends up being called as a context-free function, such that `this` within the method would be the window object instead of the component instance.

One way to avoid this problem is to change the method into a property with an arrow function:

```ts
sameDaddy = (index, item) => {
    console.log(this.elementCompareToogle);
    if (this.orderReturnValue) {
      return item.value[this.elementCompareToogle];//dentro de la funcion no carga el elementCompareTrackBy 
    } else {
      return item.value['pos1'];
    }
  };
```

Arrow functions don't have a `this` pointer based on the receiver, instead it resolves `this` from the lexical scope. Since the arrow function exists as a field of a class, the field ends up being assigned within the constructor of that class where `this` refers to the component instance. Consequently, the function can be called with any receiver (or as context-free function as `NgFor` does) and the arrow function would still be able to access the component instance as it captured `this` from the constructor.

Please see [MDN](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/this) for more info.

**Comment by jeromflo** [comment]
Hi JoostK, really thanks for the answer and the explication. I didn't realize that was the problem.  I know the arrow functions, but didn't realize can use on class because I came from java, and never change the form of write the class. You openned my eyes. Thanks

**Comment by JoostK** [comment]
Don't worry, this stuff is confusing in JavaScript!
