### ISSUE TITLE
Library built with ng12 does not work in app built with ng13 via platformBrowserDynamic().bootstrapModule();

### ISSUE THREAD

**Issue by christopherthielen** [angular/angular#44323]
### Which @angular/* package(s) are the source of the bug?

core

### Is this a regression?

Yes

### Description

If a library is built using Angular 12 (via `ng-packagr` in  case it is relevant) and then loaded in an Angular 13 application using `platformBrowserDynamic().bootstrapModule()` the library doesn't compile because it's missing the `'ɵmod'` property.

If the library is built using ng13, it works in both ng12 and ng13 apps.

I found this problem when upgrading the ui-router Angular+AngularJS hybrid library.  To mitigate, I rebuilt the libraries using ng13.

### Please provide a link to a minimal reproduction of the bug

https://github.com/ui-router/angular-hybrid/tree/ng12-library-in-ng13

### Please provide the exception or error you saw

```true
Uncaught Error: Type Ng12LibModule does not have 'ɵmod' property.
    at getNgModuleDef (app.js:83458)
    at recurse (app.js:104438)
    at recurse (app.js:104449)
    at registerNgModuleType (app.js:104434)
    at new NgModuleFactory (app.js:104560)
    at compileNgModuleFactory__POST_R3__ (app.js:108603)
    at PlatformRef.bootstrapModule (app.js:108856)
    at Object../src/app.ts (app.js:3679)
    at __webpack_require__ (app.js:118204)
    at app.js:119272
```

### Please provide the environment you discovered this bug in (run `ng version`)

```true
app: Angular 13.0.2 (non-cli webpack build)
lib: Angular 12.2.13
```

### Anything else?

To reproduce the problem:

```shell
git clone https://github.com/ui-router/angular-hybrid -b ng12-library-in-ng13 ng12-library-in-ng13; 
cd ng12-library-in-ng13; 
./run.sh
```

**Comment by JoostK** [comment]
The build appears to be using a custom Webpack setup, not the CLI (as you noted in the issue description as well). As a result, you'll have to take care to manually run ngcc (Angular Compatibility Compiler) in order to convert libraries from ViewEngine format to Ivy. This was not a problem in earlier versions of Angular, as `@angular/core` and relatives were still built using ViewEngine themselves: if ngcc was omitted then the app would simply run using the ViewEngine renderer. Since v13 however, Angular's packages are natively distributed in Ivy format which now requires ngcc to be run for libraries that are still published using ViewEngine format.

Ivy's distribution output has been available since Angular 12, so you could switch the library to using that instead of ViewEngine. Please see [the docs](https://angular.io/guide/creating-libraries#publishing-libraries) for more info.

Alternatively, you may want to run `ngcc` as postinstall script. That would be necessary for any other libraries that you may use that are still published using ViewEngine's format.

**Comment by alan-agius4** [comment]
Closing since custom webpack configurations are not supported by the Angular team.

**Comment by christopherthielen** [comment]
got it, thanks for the detailed explanation!
