### ISSUE TITLE
 formatDate One year missing 

### ISSUE THREAD

**Issue by lichanglong2015** [angular/angular#44350]
### Which @angular/* package(s) are the source of the bug?

common

### Is this a regression?

Yes

### Description

angular pipe  One year missing
example: 
 {{'**2021**-1-1' | date: "YYYY-MM-dd"}} =>**2020**-01-01
formatDate('**2021**-1-1', 'dd-MMM-YYYY', 'en-US'); =>  01-Jan-**2020**

### Please provide the exception or error you saw

```true
{{'2021-1-1' | date: "YYYY-MM-dd"}} =>2020-01-01
```

**Comment by Olster** [comment]
`yyyy-MM-dd` should be the correct format.

According to [DatePipe docs](https://angular.io/api/common/DatePipe), `YYYY` is so called "Week-numbering year" -- which after some googling shows that it handles special cases for leap years.
And because 2020 was a leap year, 1. Jan 2021 is considered week 53 of 2020 ([tested with this calculator](https://myweb.ecu.edu/mccartyr/isowdcal.html)), so that's why 2020 is shown on the page.
If you try `{{'2020-1-1' | date: "YYYY-MM-dd"}}` or `{{'2019-1-1' | date: "YYYY-MM-dd"}}` you'll see the right year -- which proves the above.

**Comment by AndrewKushnir** [comment]
Closing this ticket based on https://github.com/angular/angular/issues/44350#issuecomment-984801853 (thanks @Olster for the reply).
