### ISSUE TITLE
Error: Cannot find module from import in component

### ISSUE THREAD

**Issue by Adibla** [angular/angular#44364]
### Which @angular/* package(s) are the source of the bug?

core

### Is this a regression?

No

### Description

Hi, I've an issue when I try to import from a component external js file, which path is passed as Input property. Using directly a string causes no problem, and module is correctly imported.  

### Please provide a link to a minimal reproduction of the bug

https://codesandbox.io/s/priceless-mirzakhani-t50f0?file=/src/app/sample.component.ts

### Please provide the exception or error you saw

```true
Error: Cannot find module
```

**Comment by JoostK** [comment]
This is not something that is currently supported, as dynamic imports need to have static module specifiers in order to bundle everything correctly.

Certain bundlers such as Webpack [can be instructed to deal with this (with some constraints)](https://webpack.js.org/api/module-methods/#dynamic-expressions-in-import). If you're using the CLI, please be aware that its usage of Webpack is an implementation detail, the CLI might transition to different bundling strategies in the future.
