### ISSUE TITLE
Angular 13 Build Times increased a lot

### ISSUE THREAD

**Issue by danielehrhardt** [angular/angular#44372]
### Which @angular/* package(s) are the source of the bug?

compiler-cli, compiler, core

### Is this a regression?

Yes

### Description

Since I upgraded some Projects from Angular 12 to Angular 13 the build times increased by factor 3x.

Same Project (Build by Github Actions):
Angular 12 ➤ 6 min 
Angular 13 ➤ 18 min

I can see this in multiple Angular Projects. I did the upgrade with ng update. 

### Please provide the exception or error you saw

```true
No errors.
```

### Please provide the environment you discovered this bug in (run `ng version`)

```true
Angular CLI: 13.0.2
Node: 16.13.0
Package Manager: npm 8.1.3
OS: darwin arm64

Angular:
...

Package                      Version
------------------------------------------------------
@angular-devkit/architect    0.1300.2 (cli-only)
@angular-devkit/core         13.0.2 (cli-only)
@angular-devkit/schematics   13.0.2 (cli-only)
@schematics/angular          13.0.2 (cli-only)
```

**Comment by JoostK** [comment]
Could you please share a reproduction of some sorts, a CPU profiling or anything else that might help us determine what is going on here; without this information we won't be able to help you here.

**Comment by Rush** [comment]
If `babel` is needed for every build now, this is what is contributing to long build times https://github.com/angular/angular/issues/44026#issuecomment-986472833

Babel having to parse every line of code is a HUGE cpu cycles waste.

**Comment by Rush** [comment]
@JoostK Are you saying that the Angular team didn't observe any regressions when it comes to build times? Do you measure it? Did you expect the build times to decrease or increase when releasing Angular 13?

**Comment by danielehrhardt** [comment]
> Could you please share a reproduction of some sorts, a CPU profiling or anything else that might help us determine what is going on here; without this information we won't be able to help you here.

Do you have some instructions?

**Comment by JoostK** [comment]
Does this help? https://github.com/angular/angular-cli/issues/8259#issue-269908550

**Comment by spock123** [comment]
@Rush I observed faster building times when I went from 12->13. This is a project with i18n in 5 languages.

**Comment by DavideViolante** [comment]
@danielehrhardt can you check if you relate to [this](url)?

**Comment by danielehrhardt** [comment]
Build times went down again. After 13.1

**Comment by LironHazan** [comment]
mine was actually takes longer now since upgraded from 12 to 13.1

C02Y504VJHD3:mgmt-console lironh$ ng version

     _                      _                 ____ _     ___
    / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
   / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
  / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
 /_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
                |___/
    

Angular CLI: 13.1.4
Node: 16.10.0
Package Manager: npm 7.4.3
OS: darwin x64

Angular: 13.1.3
... animations, cdk, common, compiler, compiler-cli, core, forms
... language-service, material, platform-browser
... platform-browser-dynamic, platform-server, router
... service-worker

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1301.4
@angular-devkit/build-angular   13.1.4
@angular-devkit/core            13.1.4
@angular-devkit/schematics      13.1.4
@angular/cli                    13.1.4
@schematics/angular             13.1.4
rxjs                            6.6.7
typescript                      4.5.5


(esbuild in package.lock --> 0.14.11)
the build time was increased in 2 min! any clues why?

**Comment by DavideViolante** [comment]
@LironHazan provide a reproduction repo where the issue happens and where it doesn't. Open a new issue in case.

**Comment by LironHazan** [comment]
@DavideViolante Unfortunately I can't expose the repo it's a private large scale / enterprise application. and I don't find a point in opening 2 basic repos one using 13.1.4 and the other 12.2.0, I assume the Angular team tests themselves.. 

I can just tell that running same command --> `ng build app-x --configuration=production  --source-map=false` 
in git actions now takes 7 min instead of 5 (which is a lot in both cases IMO)

Another differentiator is the npm + node versions I'm using,
with 12.2.0 I used node 14.15 and npm 6 and now I'm using node 16.10 with npm 7.4.3

I'll keep investigating.. thanks

**Comment by DavideViolante** [comment]
Can you try removing source-map=false? Does it also happen in configuration=development? Does it happen with v13.0? You need to provide as much info as possible or is very difficult even for Angular team to find out the issue. I [also had a similar issue](https://github.com/angular/angular-cli/issues/22472#issuecomment-1005045938) in a private repo but I investigated until I found the exact line that was causing the perf increase.
Btw I recommend to open a new issue if you are sure that just the upgrade from v12 to v13 caused a performance drop.

**Comment by LironHazan** [comment]
@DavideViolante sure I can test it without the source-map=false though it makes more sense that if no source map creation it should be quicker (minor optimisation), I actually just upgraded from 12.2.0 directly to 13.1, started the upgrade 2 days ago and had to resolve some other issues as usual when upgrading a large project :) so I didn't have too much time investigating the prevues version, I'll probably keep that as last process when done with other dependencies upgrades, thanks for sharing your issue as a lead
