### ISSUE TITLE
Tabs in documentation should all be displayed when printed

### ISSUE THREAD

**Issue by SetTrend** [angular/angular#44388]
### Description

In the Angular documentation, tab strips don't print well.

See [here](https://angular.io/guide/pipes#using-a-pipe-in-a-template) for reference.

Only the first tab is getting printed:

![Printed pipes example](https://user-images.githubusercontent.com/9283914/144919442-f48b3209-29ad-4aac-b03c-308a6b04379c.png)

Please amend the `print` media rules to gracefully print all tabs of a tab strip, vertically stacked.

### What is the affected URL?

https://angular.io/guide/pipes#using-a-pipe-in-a-template

### Please provide the steps to reproduce the issue

Print the above mentioned Angular documenation web page.

### Please provide the expected behavior vs the actual behavior you encountered

When printing an Angular documentation web page for offline reading, I'd expect to see all content. This includes the content of all of a tab strip's tabs:

![Proposed tab printing](https://user-images.githubusercontent.com/9283914/144927038-058d0377-47ca-4b53-aaf9-b9444c49ee47.png)

Currently, only the first tab's content is being rendered.

**Comment by gkalpak** [comment]
Thx, @SetTrend. That's a reasonable improvement.

Unfortunately, the Angular Material `<mat-tab-group>` does not support that (mainly because it would hurt performance by having to render the contents of all tabs all the time - see angular/components#6399).

Maybe we could update our [CodeTabsComponent][1] to store the contents of all tabs in the DOM (hidden) and only display it for print. We can probably get away with that, because the tab content is static, but we should still investigate the performance/memory implications.

I'll leave this open as a potential future enhancement (but it is a low priority atm).

[1]: https://github.com/angular/angular/blob/52a73c6b14af3dafe22df9a0f289ceef91b10bc7/aio/src/app/custom-elements/code/code-tabs.component.ts#L48

**Comment by SetTrend** [comment]
Hi @gkalpak,

> (mainly because it would hurt performance by having to render the contents of all tabs all the time - see [angular/components#6399](https://github.com/angular/components/issues/6399)).

I noticed that all tabs' content is initially loaded with the page:

https://user-images.githubusercontent.com/9283914/145106731-1c2b0202-cad2-4ee8-9ee9-2f5bea52c80c.mp4

Perhaps you might want to use the [`windows.onbeforeprint`](https://developer.mozilla.org/en-US/docs/Web/API/WindowEventHandlers/onbeforeprint) event handler to decide whether to output all tabs?

**Comment by gkalpak** [comment]
Oh, interesting 🤔 I didn't know about the `beforeprint`/`afterprint` events (and they have been there since IE6 🤯).
That might be a viable way to implement this (most probably in our own `CodeTabsComponent`, not in `MatTabGroup`).

(As I mentioned in my previous comment, this is low priority, but if anyone wants to take a stab at it I would be happy to help/review :wink:)

**Comment by JeanMeche** [comment]
Hi, we're looking at deprecating angular.io in favor of https://angular.dev/.
Feel free to drop any suggestions for the new doc site, thank you.
