### ISSUE TITLE
Angular rendering a space when there is a line break before and after double braces bindings in html

### ISSUE THREAD

**Issue by Kateriine** [angular/angular#44459]
### Which @angular/* package(s) are the source of the bug?

core

### Is this a regression?

No

### Description

I use an Angular html formatter in vsCode, and sometimes it automatically adds line breaks before and after bindings.
The problem is that it seems that Angular renders these line breaks into spaces. No space should be rendered.

### Please provide a link to a minimal reproduction of the bug

https://stackblitz.com/edit/angular-le3xbj?file=src%2Fapp%2Fapp.component.html

### Please provide the environment you discovered this bug in (run `ng version`)

```true
Angular CLI: 12.1.4
Node: 12.16.3
Package Manager: npm 6.14.4
OS: darwin x64
```

**Comment by JoostK** [comment]
This is working as designed, as HTML is sensitive to whitespace (with complicated rules).

There is an existing issue #37635 that requests an improvement to the whitespace collapsing logic, but even if that were implemented you'd still see the differences as you reported here, because the whitespace _is_ significant in your case.
