### ISSUE TITLE
Extending DOM Elements

### ISSUE THREAD

**Issue by TiagoBraga39** [angular/angular#4446]
Hi all!

Is it possible to extend DOM Elements with Angular 2?
In a way I can use it like:
```html
<button value="Click!" is="extended-button" />
```

Thanks in advance,
Tiago Braga

**Comment by TiagoBraga39** [comment]
Aparently it's not standard, so the answer is probably not.
Not present here: http://www.w3.org/TR/html-markup/global-attributes.html
Neither here: http://www.w3.org/TR/html-markup/input.text.html

Can anyone just confirm these assumptions?
Then close this any time you want :)

**Comment by pkozlowski-opensource** [comment]
You can do `<button extended-button>Click!</button>` today, where `extended-button` is a custom directive. This should cover most of the use-cases (adding new properties / events, changing properties of the underlying button etc.).

Closing for now, share a concrete use-case if you believe that things are missing here.

**Comment by Kim-Andersen** [comment]
Isn't this a standard by now?
https://developers.google.com/web/fundamentals/web-components/customelements#extendhtml

Custom Elements/Web Components are gaining traction and it's a pitty Angular is not supporting the is="extended-button" syntax.

**Comment by sliceofbytes** [comment]
Second this. Would be useful functionality for using extensible components cross framework.

**Comment by steveblue** [comment]
I just gave a talk about this at Angular Portland. This could be possible with Angular Elements, however not implemented (yet) because `NgElement extends HTMLElement` only, meaning the API only allows for defining Autonomous custom elements. Not sure if there are plans to allow for Custom built-in elements, but according to the IVY roadmap class composition is supported, so it could be possible for Angular to support Custom built-in elements. I think all that is required is possibly some community contribution to Angular Elements to make this happen.

**Comment by Kim-Andersen** [comment]
> I just gave a talk about this at Angular Portland. This could be possible with Angular Elements, however not implemented (yet) because `NgElement extends HTMLElement` only, meaning the API only allows for defining Autonomous custom elements. Not sure if there are plans to allow for Customized built-in elements, but according to the IVY roadmap class composition is finally supported, so it could be possible for Angular to support Customized built-in elements. I think all that is required is possibly some community contribution to Angular Elements to make this happen.

So you mean with Ivy, according to the roadmap, **vanilla** extended native HTML elements could be supported without any Angular/Elements -specific code?

**Comment by steveblue** [comment]
What I am saying is Component Composition is supported in IVY and implemented according to this:

https://github.com/angular/angular/blob/master/packages/core/src/render3/STATUS.md

What I am not saying is this will work out of the box with Customized built-in elements, however things are converging to make this a reality.

**Comment by steveblue** [comment]
The main blocker is with Angular Elements only supporting `HTMLElement`. The Angular Elements package would probably also need to export classes that extend the rest of the HTML elements too.

**Comment by Kim-Andersen** [comment]
It depends on the use case, I think. Custom elements can be brought in and work in Angular, true. But not extended native elements. Maybe we're on the same page, but let me explain just to be sure...

I'm creating framework-agnostic custom elements (basically a design system), like this simplified example:

`class FancyButton extends HTMLButtonElement {
...
}`
`customElements.define("fancy-button", FancyButton, {
    extends: "button"
  });`

(The important part there is _{ extends: 'button' }_.)

Then I want to use that in any web framework/view library, like so:
`<button is="fancy-button">Fancy button</button>`

That native "is" attribute is not working in Angular templates.

**Comment by steveblue** [comment]
Oh, did you import `CUSTOM_ELEMENTS_SCHEMA` into the app.module.ts NgModule like so?

```
mport { BrowserModule } from '@angular/platform-browser';
import { NgModule, CUSTOM_ELEMENTS_SCHEMA } from '@angular/core';
import { FormsModule } from '@angular/forms';
import { HttpModule } from '@angular/http';

import { AppComponent } from './app.component';


@NgModule({
  declarations: [
    AppComponent
  ],
  imports: [
    BrowserModule,
    FormsModule,
    HttpModule
  ],
  providers: [],
  bootstrap: [AppComponent],
  schemas: [ CUSTOM_ELEMENTS_SCHEMA ]
})
export class AppModule { }
```

**Comment by Kim-Andersen** [comment]
Yes, I included the CUSTOM_ELEMENTS_SCHEMA. That's not the problem.

This [stackblitz](https://stackblitz.com/edit/angular-hwtj2s) shows the problem. Interesting bits in _index.html_ and _app.component.html_.

My take on it is that Angular "hijacks" the "is" attribute on the `<button is="fancy-button-extended">Not working :(</button>` element and applies it after the node is attached to the DOM (component life cycle stuff). And I think that "is" attribute HAS to be set when the node is attached to the DOM for the extention to work, not after.

**Comment by steveblue** [comment]
" 'is' attribute HAS to be set when the node is attached to the DOM for the extention to work" is not entirely accurate. The browser constructs the instance of the customized built-in element when the document is parsed. Angular has yet to even bootstrap, let alone create the host element for the Component you are working with. So for this use case you must dynamically create the customized built-in element. 

This may be possible with a custom Renderer as some have suggested on Stackoverflow, but even that is not necessary to get customized built-in elements working in Angular.

According to the W3C spec there are 2 ways to dynamically create customized built-in elements after the HTML is parsed. https://html.spec.whatwg.org/multipage/custom-elements.html#custom-elements-customized-builtin-example

So in the context of an Angular component you can do something like this:

```
export class AppComponent implements AfterViewInit {
  title = 'customized-built-in-elements';
  constructor(private _ref: ElementRef) {}
  ngAfterViewInit() {
    const fancyButton = document.createElement('button', { is: 'fancy-button' });
    this._ref.nativeElement.querySelector('.button-container').appendChild(fancyButton);
  }
}
```

Interestingly enough, with this implementation the 'is' attribute is not needed. As you can see in this Stackblitz your issue is resolved @Kim-Andersen 

https://stackblitz.com/edit/angular-1qt5e7?file=src/app/app.component.ts

**Comment by Kim-Andersen** [comment]
Ok yeah, so it can be done that way. Thanks for that finding.
However, that's quite a lot of ceremony for something that you would expect to work out of the box. Also, one thing is getting the extended custom element into the DOM. Then the problems begins when you want to interact with the element in Angular templates, setting props etc. 
Not an intuitive developer experience to use this custom element.

I think Angular needs to fix this "fundamentally", hopefully with Ivy.

**Comment by Kim-Andersen** [comment]
@pkozlowski-opensource Can we reopen this issue?

**Comment by steveblue** [comment]
Yeah, there are several problems that could arise from this approach. It doesn't consider the innerHTML of the custom element or any observedAttributes. It would be nice if Angular could just correctly interpret this part of the w3c spec.
