### ISSUE TITLE
Overridden internal methods show up in API docs

### ISSUE THREAD

**Issue by AndrewKushnir** [angular/angular#44468]
### Description

Currently, overridden internal methods of classes show up in the API docs. For example, see [the FormControl page](https://angular.io/api/forms/FormControl). Methods that start with underscore (such as `_updateValue`) are marked as `@internal` ([example](https://github.com/angular/angular/blob/master/packages/forms/src/model.ts#L1352-L1355)), so they should not appear in API docs. However, `@internal` methods that do not have the `override` keyword are not present on the page ([for example this one](https://github.com/angular/angular/blob/master/packages/forms/src/model.ts#L1397-L1403)), so I guess the problem is isolated to the inherited `@internal` methods.

### What is the affected URL?

https://angular.io/api/forms/FormControl

**Comment by petebacondarwin** [comment]
I suspect dgeni is checking flags on the AST node for internal, with being resilient to multiple flags?

E.g. `node.flags === INTERNAL` rather than `node.flags | INTERNAL`

**Comment by gkalpak** [comment]
The problem seems to be that `dgeni-packages` [uses TypeScript 3.2.x][1], which does not understand the `override` keyword.

As a result, it interprets `override someMethod() {}` as an `override` property and a `someMethod` method and therefore any preceding comment [is matched][2] to the `override` "property" and not the `someMethod` method.

You can see the difference in TS behavior [here][3] (notice how the AST changes when switching to v3.x).

##
I will look into updating `dgeni-packages` to a more recent version of TS (but I have no idea how this might affect other users 😱). I assume we would have to release a new minor version.

[1]: https://github.com/angular/dgeni-packages/blob/22993b68c72d46abbc1fd2ccc27ee467d1d4cd2d/package.json#L61
[2]: https://github.com/angular/dgeni-packages/blob/22993b68c72d46abbc1fd2ccc27ee467d1d4cd2d/typescript/src/services/TsParser/getContent.ts#L48
[3]: https://ts-ast-viewer.com/#code/MYGwhgzhAEBiD29oFMAeAXZA7AJjA8gEYBWyw60A3gFDR3QD0AVE9AMrwC2y0wX3WCkwa168AG7IATlICWOHunht0crAHMAFAEoq0KcnQBXKVmgBycwG5oAX2r2gA

**Comment by gkalpak** [comment]
Here is a fix for `dgeni-packages`: angular/dgeni-packages#318
You can see how that PR would affect the generated angular.io docs here: angular/dgeni-packages@16c63e6fc1febb7a8688a63be88209f23948ad79

**Comment by devversion** [comment]
FYI @gkalpak, in the components repo we already use a Yarn resolution to update the underlying TS version, so from the COMP side, an update would be appreciated!
