### ISSUE TITLE
feat(router): binding from router-outlet to child component

### ISSUE THREAD

**Issue by btford** [angular/angular#4452]
For example:

```ts
@Component({ selector: 'foo-cmp' })
@View({
  template: `<router-outlet [prop-passed-to-child]="parentParams"></router-outlet>`,
  directives: ROUTER_DIRECTIVES
})
@RouteConfig([
  { path: '/', component: ChildCmp }
])
class ParentCmp {
  constructor(params: RouteParams) {
    this.parentParams = params;
  }
}
```

`RouterOutlet` should be able to pass the `prop-passed-to-child` binding to `ChildCmp`.

**Comment by gdi2290** [comment]
:+1:

**Comment by jakubsta** [comment]
:+1:

**Comment by PascalPrecht** [comment]
Perfect! As a current workaround, @cburgdorf and I introduced and are using "state" components. Those state components are just simply wrapper components that we navigate to and have the actual component that needs data through a binding as view child.

**Comment by btford** [comment]
I need help from someone more familiar with Angular Core– so @tbosch, @mhevery, @rkirov, or @vsavkin on how to approach this.

**Comment by mrydecki** [comment]
:+1:

**Comment by Antiavanti** [comment]
:+1:

**Comment by filipows** [comment]
:+1:

**Comment by cburgdorf** [comment]
I don't mean to ruin the party but since there may be several routes and therefore several completely different components behind `<router-outlet>` Each of those components would want to bind different properties. It may be that I'm getting it wrong but the way it stands now it seems to be only useful if all my routes take the same properties which is most likely not the case. 

That is why we recently introduced the concept of state components for a demo app. This is what @PascalPrecht was referring to.

https://github.com/thoughtram/ng2-contacts-demo/blob/9fe0dcb838121294f48584592933db349a6b921c/app/components/contact-detail-state/contact-detail-state-component.ts

The reason we did that is so that we can build components that are kept free from routing concerns (e.g. `<contact-list data="listOfContacts"></contact-list>`).

**Comment by rosendi** [comment]
:+1:

**Comment by rosendi** [comment]
I totally need this feature or any idea how it could be implemented. 

Here is a plunk - http://plnkr.co/edit/ZCjWxIz1RSQtIqPfXps8?p=preview. The point is how `character` from `CharacterDashboard` could be passed to children components (`ShowCharacter`, `EditCharacter`).

**Comment by naomiblack** [comment]
@vsavkin could you look into this and pair with Brian on the best way to move forward?

**Comment by btford** [comment]
@vsavkin @yjbanov @IgorMinar and I just chatted about how to implement this. It'll take some changes to how `DynamicComponentLoader` works to implement for routing.

@yjbanov – can you please explain the approach?

**Comment by evanplaice** [comment]
It would work currently because the `<router-outlet>` element shows up in the source of the route output. 

Is this a bug?

**Comment by yjbanov** [comment]
## Goal

`ParentCmp` would like to pass some data to `ChildCmp`. We also would like `<router-outlet>` to be unaware of this contract between parent and child (single responsibility principle). Finally, we would like the child component to be unaware of the type of the parent component (perhaps the child component is reusable and therefore can have different types of parents).

## Problem

`<router-outlet>` sits between the `ParentCmp` and `ChildCmp`, and because the router instantiates `ChildCmp` dynamically there's no element in the template to bind parent data to the child in a type-safe fashion.

One way we could deal with this problem is have parent publish the data via DI for child to inject instead of data binding. There are several problems with this:

1. usually the router would instantiate one of several types of child components. Otherwise, why use router at all? If a child requires one piece of data, while another one requires a different piece of data, proactively publishing all possible data would be wasteful, and to prevent eager loading via indirection requires much more boilerplate.
1. DI happens only once. If data changes over time, the child component would need to be destroyed and recreated to pass new values.
1. DI is a bit verbose, with parent having to bind it in addition to setting up the actual data, and child having to inject it via constructor.

## Proposal

`<router-outlet>` directive takes a callback `route-will-load` as `@Input`. When `DynamicComponentLoader` instantiates the child, but before we run change detection on the child, we call the callback passing it a reference to the child component. What the callback does with the child component is not `router-outlet`'s concern. It's entirely between `ParentCmp` and `ChildCmp` (or any other child type that can appear).

Example:

```
@Component({ selector: 'foo-cmp' })
@View({
  template: `<router-outlet [route-will-load]="passParams"></router-outlet>`,
  directives: ROUTER_DIRECTIVES
})
@RouteConfig([
  { path: '/', component: ChildCmp }
])
class ParentCmp {
  constructor(params: RouteParams) {
    this.parentParams = params;
  }

  passParams(child: ChildCmp): void {
    child.parentParams = this.parentParams;
  }
}
```

The implementation of `passParams` is very simple for this use-case, but one can imagine more advanced use-cases. Perhaps `router-outlet` could host multiple types of child components and the parent would need to supply _different_ values to different types.

**NOTE**: an alternative to a callback is to use an `(event)` for parent to react to. The limitation of an event is that it flows up. A callback could be called synchronously so the entire sequence of route change + child instantiation + passing values + UI update happens in a single change detection pass.

**Comment by jelbourn** [comment]
```ts
@Component({ selector: 'foo-cmp' })
@View({
  template: `<router-outlet></router-outlet>`,
  directives: ROUTER_DIRECTIVES
})
@RouteConfig([
  { path: '/', component: ChildCmp }
])
class ParentCmp {
  constructor(params: RouteParams) {
    this.parentParams = params;
  }

  @RouteLoading(ChildCmp)
  passParams(child: ChildCmp): void {
    child.parentParams = this.parentParams;
  }
}
```

**Comment by jelbourn** [comment]
cc @yjbanov @vsavkin @IgorMinar for thoughts on a) whether `@ViewChild` + `afterViewInit` is enough for now, and b) for the second API

**Comment by timkindberg** [comment]
+1 @jelbourn idea

**Comment by bluehayes** [comment]
:+1: for something along these lines to pass data between routed components.

**Comment by timkindberg** [comment]
Couple Ideas:

1) One approach I created for [this @State decorator](https://github.com/hannahhoward/a1atscript/wiki/Using-A1AtScript-With-UI-Router) for a1atscript was just passing in all the state data via a state input. It had all state params and resolved datas. Like this: 

```js
@Component({
   inputs: ['state']
})
class MyPage {
   state: { params: any, resolves: any}
}
```

2) Another new idea is a declarative approach, perhaps where you nest the routed components inside router-outlet and they are used like a configuration. I envision needing access to local convenience vars like $params. Like this: 

```js
@Component({ selector: 'child' })
class ChildCmp {
  @Input() name;
}

@Component({ selector: 'foo' })
class FooCmp {
  @Input() bar;
}

@Component({ 
  selector: 'parent',
  template: `
  <router-outlet>
    <child name="$params.name"></child>
    <foo id="$params.id"></foo>
  </router-outlet>`
})
@RouteConfig([
  { path: '/child/:name', component: ChildCmp },
  { path: '/foo/:id', component: FooCmp }
])
class ParentCmp {}
```

**Comment by btford** [comment]
I think this can be closed for now. It might be worth revisiting later, but for now the pattern @jelbourn showed can be used to accomplish what was originally described.

I suspect that we'll want to add better syntax sugar later, but I think we should wait until we have a bit better idea of application needs.

**Comment by timkindberg** [comment]
@btford to be clear, are you talking specifically about this pattern?

> Overall this doesn't seem like any less work than setting up a @ViewChild query for the component and setting the data on afterViewInit.

**Comment by jelbourn** [comment]
@timkindberg Yep. Here's the relevant unit test that demonstrates the concept:

https://github.com/angular/angular/blob/master/modules/angular2/test/router/integration/bootstrap_spec.ts#L207

**Comment by rosendi** [comment]
@jelbourn How could I query components that implement same interface using `@ViewChild(?)`? Sorry, I didn't find a proper solution. 

Example:

```
interface C {
}

@Component(...)

class A implements C {
}

@Component(...)

class B implements C {
}

@Component(...)

class D { // with a RouterOutlet directive
  @ViewChild(?) viewChild: C;
}
```

**Comment by jelbourn** [comment]
@rosendi Unfortunately you can't query by interface; TypeScript does not keep interfaces around at run-time.

**Comment by rosendi** [comment]
@jelbourn of course, I know it. In example above I used it just to show that the components A and B have some similar functionality. For example each component has `itemId` property:

```
@ViewChild(A | B ???) viewChild: { itemId: string };

ngAfterViewInit() {
  viewChild.itemId = 'some item id';
}
```

The question is how I can query this components by a single query.

**Comment by rosendi** [comment]
@jelbourn may be it's related to https://github.com/angular/angular/issues/1828

**Comment by jelbourn** [comment]
@vsavkin what would you suggest here since giving a name to the routed component isn't an option?

**Comment by radek-holy** [comment]
I cannot make it work. I took the example from the unit test and it throws: `TypeError: Cannot set property 'message' of null`. Any help would be appreciated: http://plnkr.co/edit/xVSwPA7MA9cCctaTMjSE

**Comment by rosendi** [comment]
@jelbourn what was your temporary solution? https://github.com/angular/angular/issues/1828#issuecomment-107630276

**Comment by rosendi** [comment]
@btford @jeffbcross I've just imagined how it could be achieved:

```
interface C {
  property: string;
}

class A implements C {
}

class B implements C {
}

@ViewChild(RouterOutlet) routerView: RouterOutlet<C>;

ngAfterViewChecked() {
  routerView.componentRef.instance.property = '...';
}
```

```
export abstract class ComponentRef<T> {
  instance: T;
}
```

1. Why is `componentRef` of the router outlet private? 
2. Can `ComponentRef` and `RouterOutlet` be generic?

**Comment by radek-holy** [comment]
So, I implemented a ton of workarounds to achieve this. Fortunately, they naturally converged to the same as @PascalPrecht and @cburgdorf [call](https://github.com/angular/angular/issues/4452#issuecomment-148406518) "state components". But in contrast to @PascalPrecht, I think that this is the proper and clean solution to the need to pass data to routed components. I'd welcome a syntactic sugar to avoid the need to write `template: "<contact-detail-component [contact]="contact" (back-clicked)="onBackClicked()"></contact-detail-component>"` but the rest is fine.

**Comment by radek-holy** [comment]
@rosendi, to implement your Star Wars website [above](https://github.com/angular/angular/issues/4452#issuecomment-151618421), I'd do this: http://plnkr.co/edit/xGU8xWwH71hrbtinbk8z?p=preview

**Comment by rosendi** [comment]
@radek-holy yep, I know about this solution. I don't like it. The @jelbourn solution is much cleaner and it's universal.

But my proposal is about how a complex querying could be achieved without a component name. See https://github.com/angular/angular/issues/4452#issuecomment-162976989

P.S.:  The SW implementation isn't question for me anymore.

**Comment by radek-holy** [comment]
Yes, as long as the child components implement the same interface, it might be cleaner...

**Comment by horyd** [comment]
Is there an equivalent pattern for resolving this if you're using the component router in Angular 1.5?

**Comment by gionkunz** [comment]
The route outlet should obviously not be used to propagate bindings to instantiated components. What about the @RouteConfig and by specifying a `hostTemplate` ?

https://github.com/angular/angular/issues/5875

**Comment by IvanRave** [comment]
or something like this
```
<div>
  {{city | json}}
  <div *ngIf="routePath === '/regions'">
    <region-list [cityId]="city.id"></region-list>
  </div>
  <div *ngIf="routePath === '/region/:id'">
     <region-detail [id]=":id" [city]="city"></region-detail>
  </div>
</div>
```

**Comment by eXaminator** [comment]
I just came across this issue as I was looking for a way to pass data to a routed child component.

The given workaround above doesn't seem to work in dev mode as I get an exception when changing the child's property in `ngAfterViewInit`:
`Expression 'prop in ChildComponent@2:19' has changed after it was checked.`

I'm not sure if I've done anything wrong, but if not this issue is pretty important and should be addressed soon. It seems this was also discussed in #6094.

I would also like to propose another syntax:
```typescript
@RouteConfig([
  { path: '/child/:name', component: ChildCmp, bindings: {'[childProp]': 'parentProp'} },
])
class ParentCmp {
  parentProp: string = 'Hello World';
}
```
This would allow to bind any input the child component might have just like you would if you would use the component right in the template.

**Comment by EgorkZe** [comment]
And what is solution for it? How can i get access navbar in childs from <router-outlet [navbar]="vc"></router-outlet>   ?

**Comment by zoechi** [comment]
@EgorkZe https://angular.io/docs/ts/latest/cookbook/component-communication.html#!#bidirectional-service

**Comment by michal-filip** [comment]
@zoechi I'd hate to hijack the thread but is there any similar approach for angular 1.5 where we can't create service instances for a specific component tree?

**Comment by zoechi** [comment]
@michal-filip Sorry, no knowledge about 1.5

**Comment by maximedupre** [comment]
@jelbourn  
> Overall this doesn't seem like any less work than setting up a @ViewChild query for the component and setting the data on afterViewInit.

I tried implementing your solution, but I don't think it's feasible. The `ViewChild` component can't be found because it is instantiated and/or placed in the DOM later by the `router-outlet`. `@ViewChild(MyComponent) child: MyComponent;` is always `undefined`.

**Comment by ericmartinezr** [comment]
The old new router has been deprecated, so it shouldn't be a issue anymore. You can't query dynamic loaded routes anymore since beta.16

>e.g. for router-outlet: loaded components can't be queries via @ViewQuery, but router-outlet emits an event activate now that emits the activated component

That `activate` event emites the current instruction -> `<router-otulet (activate)="..."></router-outlet>`.

If you need to pass data to your routed componentes you must use services.

But again, this old new router has been deprecated, stay tuned for the new new router.

**Comment by maximedupre** [comment]
@ericmartinezr Thanks for the response. It has cleared up some things, but made others more confusing.

1. What do you mean by old new router? Does that mean that I shouldn't be using `router-outlet` anymore?
2. There is no non-deprecated router as of now?
3. Why should I use a service to pass data vis service if I now have access to a routed component via the activate event? Because this is the old new router and that it is deprecated?

**Comment by CaptainCodeman** [comment]
The "router formerly known as new" is no more. It is deprecated. It is an ex-router. It has ceased to be.

(the name switch-a-roo is happening right now)

The new "alt" router which will henceforth just likely be called "router" is similar in some ways, different in others. Until it's done and available to use it's hard to say what it will be exactly but it looks like there will still be router-outlets and the need to pass things via services.

**Comment by ericmartinezr** [comment]
@maximedupre answering your questions

1. The router is currently being rewritten (see for example https://github.com/angular/angular/pull/8173)
2. @CaptainCodeman answered the two first questions, I saw it while I was writing!
3. The main issue in this issue (?) is to pass data from a parent component to a child component loaded by routing and the only way is by using services. I mentioned the `activate` event because of your comment to @jelbourn 's solution which doesn't work anymore. Those are two different things, sorry if I mixed them up.

**Comment by maximedupre** [comment]
What about using the child component that was received in the `activate` event to pass data? I just tried it and it works, but is it a bad practice?

**Comment by ericmartinezr** [comment]
@maximedupre to be honest this issue shouldn't be used a conversation forum, if you have any doubts about how to use the router you could go to gitter's chatroom and ask over there (https://gitter.im/angular/angular). This issue is closed and it will be buried with time.

**Comment by sharpmachine** [comment]
Need something like `@ViewChild` except it can be used in a child rather than a parent...like `@ViewParent`. Really need to pass data from the parent to the child using `<router-outlet></router-outlet>` in the parent template.

**Comment by zoechi** [comment]
@sharpmachine use a shared service

**Comment by sharpmachine** [comment]
@zoechi How? If I'm not using a selector for a component because I want to use router-outlet, then how can I use a service to shared data?

**Comment by zoechi** [comment]
I don't see how using a selector is related. See https://angular.io/docs/ts/latest/cookbook/component-communication.html. If the component is added to a router-outlet and has a constructor parameter then DI looks up the parent components for a provider. If it finds one it requests its instance and passes it to the constructor.

**Comment by sharpmachine** [comment]
@zoechi I'm lost I'm doing that and it's not working for me.

Parent:
```
@Component({
  moduleId: module.id,
  template: `
    <nsg-workspace>
      <nsg-subject-card [subject]="subject"></nsg-subject-card>
      <router-outlet></router-outlet>
   </nsg-workspace>`,
  directives: [
    ROUTER_DIRECTIVES,
    NsgSheetComponent,
    NsgWorkspaceComponent,
    NsgToolbarComponent,
    NsgSubjectCardComponent
  ],
  providers: [SubjectService]
})
@Routes([
  { path: '/profile', component: SubjectDetailComponent }}
])
export class SubjectComponent implements OnInit {
  subject: Subject;

  constructor(
    private _subject: SubjectService,
    private _segment: RouteSegment
  ) { }

  ngOnInit() {
    this.getSubject();
  }

  getSubject() {
    let id = this._segment.getParam('id');

    this._subject.get(+id)
      .subscribe(subject => this.subject = subject);
  }

}
```

Child:

```
@Component({
  moduleId: module.id,
  template: `
    <nsg-toolbar [title]="subject?.name"></nsg-toolbar>
    <nsg-sheet>
      <div class="well well-sm">
        <pre>{{subject | json}}</pre>
      </div>
    </nsg-sheet>`
  directives: [
    NsgSheetComponent,
    NsgToolbarComponent,
  ],
  providers: [SubjectService]
})
export class SubjectDetailComponent {
  constructor(
    private _subject: SubjectService
  ) { }
}
```

This doesn't work. I can't get subject in the SubjectDetailComponent. I could call the same service method (`get(id)`), but the child doesn't have access to the parents route param...

**Comment by zoechi** [comment]
@sharpmachine

don't add `providers: [SubjectService]` on `SubjectDetailComponent` or it wull get a new instance.

This is not the right place for such discussions. Please post further questions at StackOverflow, Gitter, Google groups,...

**Comment by sharpmachine** [comment]
@zoechi I will do a stackoverflow but if it's not possible to do this via router-outlet, then it's an issue that needs to be discussed here.

**Comment by chenyingyin** [comment]
![default](https://cloud.githubusercontent.com/assets/24284270/20781492/33c247d2-b7be-11e6-861a-54e091818bca.png)
![Uploading 图片.png…]()

**Comment by gmsergiov** [comment]
I'm facing the exact same issue. I've a resolver which resolves the first parameter info related and in the second resolver the param is not present. 
is there any update i'm not aware of?
Is there any issue with jusing locatStorage to store the data?, I don't see any approach following this idea.
