### ISSUE TITLE
Angular 12 DecimalPipe doesn't work on input

### ISSUE THREAD

**Issue by elinake** [angular/angular#44522]
### Which @angular/* package(s) are the source of the bug?

core

### Is this a regression?

Yes

### Description

In Angular 8 I successfully used number pipe with Angular FormControl and Ionic input like this:
```
 <ion-input
    [formControlName]="parameterName"
    type="number"
    [value]="value | number"
  ></ion-input>
```
In Angular 12 same setup does not work for numbers 0.99999999999999994 or smaller, and it keeps all the decimals. In a non-input like `<p>`, number pipe works correctly for those numbers. I also tried defining digits explicitly, that didn't work either.  Same issue exists also in Angular 11.

Angular 12 example: https://stackblitz.com/edit/angular-ivy-mzzkoy
Angular 8 example: https://stackblitz.com/edit/angular-8-getting-started-5ybszd

### Please provide a link to a minimal reproduction of the bug

https://stackblitz.com/edit/angular-ivy-mzzkoy

**Comment by j2L4e** [comment]
Likely a change in ion-input from `@angular/ionic`.
Also using the value input and a value accessor at the same time seems very smelly to me. I'd be surprised if this was a well-defined thing to do.
What you're seeing is the form control value rather than the one you pass to `[value]`. If you remove `[formControlName]` you should see the rounded value is displayed.
This isn't a bug but likely that you're using `ion-input` in an unintended way.
One more thing: The number pipe returns a string. Passing that to an input of type number doesn't seem right.

I think what you actually want to do here is round the value the way you need it before passing it to the FormControl in the first place.

**Comment by elinake** [comment]
I can't round the actual number, because I'm doing calculations and converting numbers to different units and showing a metric value I picometers etc. I can't make a random decision to cut the decimals without losing accuracy, but the user doesn't need to see a value like 0,300000000000009 that is due to floating point number calculation imprecision.

**Comment by Airblader** [comment]
@j2L4e is correct: using reactive forms _and_ binding the value at the sake time doesn't make sense and has never been intended or defined behavior.
