### ISSUE TITLE
Live demo in ChangeDetectorRef documentation is outdated

### ISSUE THREAD

**Issue by QichenZhu** [angular/angular#44553]
### Description

The [live demo](https://plnkr.co/edit/GC512b?p=preview) for [ChangeDetectorRef#use-markforcheck-with-checkonce-strategy](https://angular.io/api/core/ChangeDetectorRef#use-markforcheck-with-checkonce-strategy) is using the deprecated Angular version `2.0.0-alpha.37`.

Related to #21525, #22370.

### What is the affected URL?

https://angular.io/api/core/ChangeDetectorRef#use-markforcheck-with-checkonce-strategy

**Comment by dario-piotrowicz** [comment]
@QichenZhu yeah you're right, good catch 🙂:+1:

@gkalpak I've looked into it and the thing is that we have an hardcoded link to a plnkr in the ts code:
https://github.com/angular/angular/blob/8c71b9fc42e1aa898200b2b3ebb54d6faf0fa645/packages/core/src/change_detection/change_detector_ref.ts#L36

I started trying to migrate that to a standard aio example, but after a bit I realized that that doesn't actually really look like a good idea, as this is in the core package, so I think it would be pretty messy to have core code linking to an aio example

As far as I can tell we don't really have live demos in the packages code anyways ( only this one and also [another one](https://github.com/angular/angular/blob/a92a89b0eb127a59d7e071502b5850e57618ec2d/packages/core/src/render3/STATUS.md?plain=1#L7) ) 

So I would actually suggest to simply remove the live demo link from the ts file as that in my opinion doesn't really add much value to the api docs anyways

What do you think? 🙂 

___

By the way, this made me look into the aio guides and I don't think there is a dedicated live example nor guide focused on change detection (as far as I can tell change detection is only just brefly mentioned in the [lifecycle hooks guide](https://angular.io/guide/lifecycle-hooks#lifecycle-hooks)), maybe we could look into adding one? 🤔 

___

Also, what about the [other one](https://github.com/angular/angular/blob/a92a89b0eb127a59d7e071502b5850e57618ec2d/packages/core/src/render3/STATUS.md?plain=1#L7), besides being an hardcorded linkto a firebase app, it currently actually points to a 404 page, so that also needs to be fixed 😓

**Comment by cjosue15** [comment]
@bob-watson or @dario-piotrowicz I would like to help with this issue, maybe removed the 2 urls from the ts code, or I can add a simple stackblizt example to change the plnkr of the ChangeDetectorRef, in the case of the firebase application I am not sure how to proceed but I can figure it out :o, what do you guys think?
