### ISSUE TITLE
Tree shakeable components/directives/pipes

### ISSUE THREAD

**Issue by pauldraper** [angular/angular#44586]
### Which @angular/* package(s) are relevant/releated to the feature request?

compiler

### Description

Angular mutates classes with properties like so:

```
class LowerCasePipe {
    transform(value) {
        if (value == null)
            return null;
        if (typeof value !== 'string') {
            throw invalidPipeArgumentError(LowerCasePipe, value);
        }
        return value.toLowerCase();
    }
}
LowerCasePipe.ɵfac = i0.ɵɵngDeclareFactory({ minVersion: "12.0.0", version: "13.1.1", ngImport: i0, type: LowerCasePipe, deps: [], target: i0.ɵɵFactoryTarget.Pipe });
LowerCasePipe.ɵpipe = i0.ɵɵngDeclarePipe({ minVersion: "12.0.0", version: "13.1.1", ngImport: i0, type: LowerCasePipe, name: "lowercase" });
i0.ɵɵngDeclareClassMetadata({ minVersion: "12.0.0", version: "13.1.1", ngImport: i0, type: LowerCasePipe, decorators: [{
            type: Pipe,
            args: [{ name: 'lowercase' }]
        }] });
 ```

This prevents tree shaking.

Demonstration with rollup, webpack, uglify, terser: https://github.com/pauldraper/angular-doesnt-tree-shake

### Proposed solution

If Angular compiler emitted static class members, instead of mutating classes, tree shaking would work.

### Alternatives considered

I noticed the angular/angular-cli project has a "@angular-devkit/build-optimizer" package.

However, it's undocumented, and after playing around with it, AFAIK works only for @angular-scoped npm packages, requries packages be installed in a certain location....has a whole mess of issues.

My best alternative solution is probably forking that.

I think the best solution however is to just have ngtsc emit tree shakeable code from the start.

**Comment by JoostK** [comment]
Once the `ɵɵngDeclare*` calls have been "linked" to become their fully-compiled `ɵɵdefine*` counterparts will those properties be marked as `/*@__PURE__*/ `, restoring the ability to tree-shake. The partial declarations are not designed to be tree-shaken, as e.g. NgModule declarations retain _all_ components/directives/pipes in scope and depend.

It's a reasonable request to emit these as actual static fields, as long as we take into account that ES5 outputs continue to need the field assignments to be outside of the class.

**Comment by pauldraper** [comment]
> The partial declarations are not designed to be tree-shaken

I'm having trouble reading this....

Are you saying @angular/common, @angular/material, etc. are not designed to tree-shaken?

**Comment by JoostK** [comment]
> Are you saying @angular/common, @angular/forms, @angular/material, etc. are not designed to tree-shaken?

Only once they have been "linked": library code is using a stable representation (partial declarations) that is forwards-compatible, with some additional design requirements such as `TestBed` and JIT compiler compatibility. Partial declarations have to be linked to get the code-size benefits, as otherwise `@angular/compiler` is needed as JIT fallback.

> What still uses ES5?

Any application that configures `"target": "es5"`.

**Comment by pauldraper** [comment]
> Any application that configures "target": "es5".

Ha, I suppose so.

> Only once they have been "linked":

Thnaks. I updated the [example repo](https://github.com/pauldraper/angular-doesnt-tree-shake) to use `@angular/compiler-cli/linker/babel`. That did help with size, though of course the class mutations still prevent tree shaking.

This is a well-known issue. For example, Babel (and TypeScript too I think?) emits ES5 classes as IIFEs with `PURE` annotation.

**Comment by alxhub** [comment]
TypeScript does not emit `PURE` annotations (although it will use an IIFE for classes in ES5 mode).

The issues around tree-shakers and static properties are, as you say, well-known, and extend far beyond Angular's compiler output for Angular-decorated classes. Previously we had a plugin known as `build-optimizer` to address some of these issues - since then, it's been decomposed into a suite of Babel plugins (such as the one for static properties: https://github.com/angular/angular-cli/blob/master/packages/angular_devkit/build_angular/src/babel/plugins/adjust-static-class-members.ts).

Together, these plugins bridge the gap between what compilers generate (and therefore, random code that's published on NPM) and the capabilities of an optimizer like Terser.

**Comment by alxhub** [comment]
I'm going to close this as it's not really actionable for us - if there are specific incantations that would make sense for us to append to better support a specific optimizer, we can consider those as feature requests, but otherwise it's outside our scope to restructure how classes are generated.
