### ISSUE TITLE
updating to 13.0.3 breaks ng-mocks library

### ISSUE THREAD

**Issue by LPCmedia** [angular/angular#44629]
### Which @angular/* package(s) are the source of the bug?

compiler

### Is this a regression?

Yes

### Description

After updating to angular 13.0.3 our test which rely on ng-mocks are failing. This can be traced to the removal of MockNgModuleResolver in d2cf130. 

more information https://github.com/ike18t/ng-mocks/issues/1427 

if this is not accidental, it is unclear why such a breaking change would happen on a patch version ? 

see repro and reset HEAD~1 or revert to ng 13.0.2 for working version. 

### Please provide a link to a minimal reproduction of the bug

https://github.com/LPCmedia/sanitizer-test-issue.git

### Please provide the exception or error you saw

```true
FooComponent declaration has been passed into ng-mocks without Angular decorators. Therefore, it cannot be properly handled. Highly likely, jest.mock() has been used on its file, or ng-mocks is not in JIT mode. Otherwise, please create an issue on github: https://github.com/ike18t/ng-mocks/issues/new?title=False%20positive%20ng-mocks%20not%20in%20JIT. Thank you in advance for support.

      at ../../../libs/ng-mocks/src/lib/common/error.missing-decorators.ts:4:9
      at Object.<anonymous>.exports.default (../../../libs/ng-mocks/src/lib/common/core.reflect.body-catch.ts:12:27)
      at ../../../libs/ng-mocks/src/lib/common/core.reflect.directive-resolve.ts:10:74
      at decorateClass (../../../libs/ng-mocks/src/lib/mock-component/mock-component.ts:205:43)
      at MockComponent (../../../libs/ng-mocks/src/lib/mock-component/mock-component.ts:240:3)
      at src/app/app.component.spec.ts:9:49
      at ../../node_modules/tslib/tslib.js:117:75
      at new ZoneAwarePromise (../../node_modules/zone.js/bundles/zone-testing-bundle.umd.js:1347:33)
      at __awaiter (../../node_modules/tslib/tslib.js:113:16)
      at src/app/app.component.spec.ts:7:25
      at ZoneDelegate.Object.<anonymous>.ZoneDelegate.invoke (../../node_modules/zone.js/bundles/zone-testing-bundle.umd.js:407:30)
      at ProxyZoneSpec.Object.<anonymous>.ProxyZoneSpec.onInvoke (../../node_modules/zone.js/bundles/zone-testing-bundle.umd.js:3765:43)
      at ZoneDelegate.Object.<anonymous>.ZoneDelegate.invoke (../../node_modules/zone.js/bundles/zone-testing-bundle.umd.js:406:56)
      at Zone.Object.<anonymous>.Zone.run (../../node_modules/zone.js/bundles/zone-testing-bundle.umd.js:167:47)
      at Object.wrappedFunc (../../node_modules/zone.js/bundles/zone-testing-bundle.umd.js:4250:34)
```

### Please provide the environment you discovered this bug in (run `ng version`)

```true
Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1300.3
@angular-devkit/build-angular   13.0.3
@angular-devkit/core            13.0.3
@angular-devkit/schematics      13.0.3
@schematics/angular             13.0.3
rxjs                            7.4.0
typescript                      4.4.4
```

### Anything else?

if this is not accidental, it is unclear why such a breaking change would happen on a patch version ?

**Comment by JoostK** [comment]
This is indeed exactly the problem for ng-mocks: https://github.com/ike18t/ng-mocks/issues/1427#issuecomment-986797816

The `@angular/compiler` package, and its `@angular/compiler/testing` entry-point are not public API of Angular. We're generally thoughtful of changing stuff as we're aware of custom tooling that does use private symbols from `@angular/compiler`, but internal compiler services such as `MockDirectiveResolver` are not among those services that we're careful of not to change.

Specifically, `MockDirectiveResolver` was part of the ViewEngine compiler infrastructure. Since ViewEngine has been deprecated for a while and is no longer available for anything since Angular 13, we're actively removing its implementation infrastructure.

I am going to close this as we won't be bringing back the ViewEngine implementations. We can sympathize that this is undesirable for ng-mocks and we're happy to assist in finding a solution for Angular Ivy; feel free to follow up below with any questions there may be.

**Comment by DaSchTour** [comment]
@JoostK well, I think that from the number of votes in this very short time and the number of comments at the ng-mocks issue you can see, that there are a lot of people stuck with Angular 13.0.2 till this get's resolved. Please don't leave us behind.

**Comment by LPCmedia** [comment]
@JoostK @jelbourn  I realize that depending on non public api's is not ideal. I agree 110% with your response. The issue lies with the ng-mocks library that has not updated to Ivy compilation.  As well to complicate things, they are supporting angular versions that are no longer LTS for some reason.

Yet as a "downstream" consumer of angular + ecosystem, it's always surprising and a colossal pain to have this kind of change show up in a patch version. I would expect this to surface when upgrading a major version ( ex from 12 -> 13 ). From  experience, the ecosystem will lag and fail on major's. It seems that this cleanup was not done in time for 13.0.0 and squeezed into 13.0.3, casually and with no mention in [changelogs](https://github.com/angular/angular/blob/master/CHANGELOG.md#1303-2021-12-01). 

From our perspective, other than the wasted time on trying to resolve the tests etc, it erodes confidence in our ui team which is the worst side effect. Given the response on the initial issue we are not the only ones. With this in mind I wonder:

- Is the angular team still committed to semantic versioning ? with transparent changelogs ?
- Is there any strategy / rfp's on how we can make the angular ecosystem more robust ? 

And last but not least ( probably a separate discussion... ) : 

- **Is there anything in the pipeline to improve testing ?**  
  - Can we have means to mock dependencies easily ? 
  - The fact that we end up relying on ng-mocks in the first place is a bit absurd ( sorry @satanTime ).  Is this something that could be baked in ? 
  - Angular components have harnesses, but with the base framework it can be difficult write robust and significant tests. 
  - Some "shallow tests" examples are showing up as a way around the ng testing api. Is this the way forward ?

**Comment by cedbesafilm** [comment]
I agree with you @LPCmedia the main actual problem when testing angular components with nested components is the need to stub / mock the nested components and the examples in this section https://angular.io/guide/testing-components-scenarios#nested-component-tests rely on manual stubbing or to force to ignore the errors.
But a safer way would be needed to create these mocks so that the interface is respected automatically and not based only on manual actions (hence the current need for ng-mocks for many developers)
I think improvements in TDD processes should be put at the top of the roadmap

**Comment by DaSchTour** [comment]
@LPCmedia just a quick note to the "shallow tests" are showing around. Just today I found a nice example why shallow test might lead to bad code. You loose the possibility of components interacting through the template. One example is the usage of form validator directives. If you test without template you will always end up adding FormValidators programatically and actually adding them twice. Adding them programatically inside your Controller then only serves the purpose of satisfing shallow tests while creating unexpected effects and errors.

**Comment by LPCmedia** [comment]
@DaSchTour I agree 110%. I want to be in that sweet spot between pure unit tests and full on ui tests. I want my tests to interact with the template so they describe actual/meaningful behaviors. I also want them isolated without having to import the whole world in the test bed. Sure, I could stub, mock and use a NO_ERRORS_SCHEMA but then you lose the contract aspect your test has with its dependencies.
