### ISSUE TITLE
Update outdated information in the documentation

### ISSUE THREAD

**Issue by SetTrend** [angular/angular#44665]
Much of the [Routing information](https://angular.io/guide/router) suggests to use `forRoot()` or `forChild()`. However, in [Singleton services](https://angular.io/guide/singleton-services) you write:

> since Angular 6.0, the best practice for providing services is with the `@Injectable()` `providedIn` property as it makes your services tree-shakable.

The contradiction also applies to other Angular features, e.g. [`entryComponents`](https://angular.io/guide/entry-components).

I propose to revise the documentation to not contradict itself and to provide updated information in all pages. Or, alternatively, to specify, e.g., why the Router is an exception to the rule.

**Comment by aikidave** [comment]
Hi @SetTrend! Thanks for this issue! We'll take a look at it and see how we can address this.

**Comment by SetTrend** [comment]
> more than 20 upvotes

I believe this huge amount of upvotes is unfair for documentation issues as I tend to believe it's impossible to reach.

Let's be honest: How many actors in this repository will even read this issue? And how many of them are going to care about documenting their own repository? And how many of them will have the apprentice's view in mind?

**Comment by aikidave** [comment]
@SetTrend I think you're right in this case--I'll talk to our infrastructure folks to see if we can adjust this.

I do have this issue on our list to review and prioritize.

**Comment by SetTrend** [comment]
When you're about to update the documentation, would you mind reducing its magnitude significantly?

Currently, the Angular documentation alone takes almost **1,200 printed pages** to read:

![Angular-WebPack books - 1](https://user-images.githubusercontent.com/9283914/160567589-ca458523-5bd9-46d8-a27c-6498b7bb6d7d.png)

I believe this is by far too much amount of information to read to be able to handle Angular on a professional basis.

This issue is particularly unbearable as TypeScript and WebPack also come with similar exuberant documentation oeuvres.

[![PDF32](https://user-images.githubusercontent.com/9283914/160566043-0ffeb85b-cfc2-4415-be86-3f68a0b64680.png) Table of Contents.pdf](https://github.com/angular/angular/files/8369320/2.-.Inhaltsverzeichnis.pdf)

**Comment by alxhub** [comment]
I don't fully understand the concern between router and services - `RouterModule.forRoot` and `RouterModule.forChild` are the right way to configure the Angular router, and `providedIn: 'root'` is the preferred way of providing a service. These aren't contradictory: using `RouterModule.forChild` isn't setting up a service to be provided, it's configuring the router with new routes. It's a helper function for declaring a provider that sets the `ROUTES` token to a user-defined value.

I'm going to close this issue, as the specific confusion between routing and singleton services isn't really relevant, and it's otherwise not actionable for us. We're constantly evaluating and improving our documentation, and we're always grateful for feedback on specific issues, so feel free to open a new issue if you find other contradictions in the docs.

**Comment by SetTrend** [comment]
Hi @alxhub:

I believe the contradiction is between:

> ## The forRoot() pattern
> [RouterModule](https://angular.io/api/router/RouterModule) provides the [Router](https://angular.io/api/router/Router) service, as well as router directives, such as [RouterOutlet](https://angular.io/api/router/RouterOutlet) and [routerLink](https://angular.io/api/router/RouterLink)

… and …

> you can use this technique to separate them out and you may see this pattern in legacy applications. However, since Angular 6.0, the best practice for providing services is with the @[Injectable](https://angular.io/api/core/Injectable)() providedIn property.

What is "this technique" referring to in the documentation? Probably the warning annotation doesn't fit where it currently is.
