### ISSUE TITLE
Service Worker error on Android devices

### ISSUE THREAD

**Issue by nicolas-garcia-kintai** [angular/angular#44673]
### Which @angular/* package(s) are the source of the bug?

service-worker

### Is this a regression?

No

### Description

Hello Everyone,

2 or 3 months ago we implemented service worker in our dashboard project. So far, it works really really great except for these 2 exceptions that I'm going to ask help.

In our project, we also implemented Rollbar to have a more detailed error tracking and in the last 2/3 weeks we received an error in ServiceWorker registration process:

`Error: Rejected (Most recent call first)`

`File (unknown) line 85 col 432 in ServiceWorkerContainer.<anonymous>
File (unknown) line 32 col 138 in ServiceWorkerContainer.register
File https://xyz.com/main-es2015.979a4121e45f0a929103.js  line 1 col 2902094 in d._next
File https://xyz.com/main-es2015.979a4121e45f0a929103.js  line 1 col 315169 in d.__tryOrUnsub
File https://xyz.com/main-es2015.979a4121e45f0a929103.js  line 1 col 314390 in d.next
File https://xyz.com/main-es2015.979a4121e45f0a929103.js  line 1 col 313561 in c._next
File https://xyz.com/main-es2015.979a4121e45f0a929103.js  line 1 col 313335 in c.next
File https://xyz.com/main-es2015.979a4121e45f0a929103.js  line 1 col 617063 in l._next
File https://xyz.com/main-es2015.979a4121e45f0a929103.js  line 1 col 313335 in l.next
File https://xyz.com/main-es2015.979a4121e45f0a929103.js  line 1 col 274756 in l.notifyNext`

This error happened twice already, but the catch about it is that, thanks to rollbar, we can see that it happened only in Android devices. First with Samsung Internet browser and then happened with Chrome Mobile browser.

Investigating earlier I had read that it has to do MAYBE with how user sets the privacy of the browser so thats why service worker cant get registered.

But in this or any other case, is there a way to implement a catch on SW Registration errors so we can handle it better?

Thanks in advance

**Comment by gkalpak** [comment]
Yes, as you said it can be something related to the user's settings. It is currently not possible to catch ServiceWorker registration errors (unless you do something hacky, like monkey-patching `console.error()` 😱).

Since (a) ServiceWorkers are typically not a critical component for the app to work (they're just an enhancement/nice-to-have) and (b) there is not much you can do with the registration errors (for example, you can really know why it failed), we didn't see much value in allowing to handle the error (so we just log it to the console).

If you feel strongly about it, you could, however, register the SW yourself (and then you could handle the error as you wish). If you want to see how Angular registers the SW, the relevant code is here: https://github.com/angular/angular/blob/8ba43a1a1ea811ad25d6af4384e1cce5a53b0baf/packages/service-worker/src/module.ts#L80-L136
