### ISSUE TITLE
Why use "done" in Testing services doc

### ISSUE THREAD

**Issue by dereklin** [angular/angular#44756]
### Description

In the Testing services doc: https://angular.io/guide/testing-services, the example uses `done`

```
  it('#getObservableValue should return value from observable',
    (done: DoneFn) => {
    service.getObservableValue().subscribe(value => {
      expect(value).toBe('observable value');
      done();
    });
  });
```

There are situations where done can lead to unnecessary unit test delays, as described here: https://www.piotrl.net/angular-testing-avoid-done/

We can avoid using done by writing the test this way:

```
  it('#getObservableValue should return value from observable', () => {
    let result;
    service.getObservableValue().subscribe((value) => {
      result = value;
    });
    expect(result).toBe('observable value');
  });
```

And if `service.getObservableValue()` is asynchronous, we can use fakeAsync:

```
  it('#getObservableValue should return value from observable', fakeAsync(() => {
    let result;
    service.getObservableValue().subscribe((value) => {
      result = value;
    });
    tick(); // or tick(whatevertimeneeded); whatevertimeneeded being a number representing milliseconds
    expect(result).toBe('observable value');
  }));
```

I think done should be avoided in Angular unit tests since we have better alternatives.  I am curious about what the Angular team and the Angular community think.

### What is the affected URL?

https://angular.io/guide/testing-services

### Please provide the steps to reproduce the issue

take a look at the doc

### Please provide the expected behavior vs the actual behavior you encountered

don't use done

### Please provide a screenshot if possible

![image](https://user-images.githubusercontent.com/2231799/150183061-4ac01d4a-463e-4d01-85dd-c28f22a61592.png)

**Comment by Airblader** [comment]
> I am curious about what the Angular community think.

I'm worried about the fact that this promotes what is an antipattern and one of, if not _the_, most common beginner mistakes with RxJs. It's basically impossible to properly convey to the reader here that this is only OK because of fakeAsync.

**Comment by dereklin** [comment]
@Airblader Could you elaborate on the anti-pattern?

**Comment by Airblader** [comment]
@dereklin Well, exactly the version you are proposing to use. It works only if the observable is synchronous, which observables typically are not, and will only be in tests due to fakeAsync. Outside of tests, writing the code this way is essentially always wrong, and there are hundreds of questions on Stack Overflow about it.

**Comment by dereklin** [comment]
@Airblader I see. fakeAsync/tick is the perfect solution for testing async observables in the case of the test doc.  It lets you mimic and control time passage without incurring any delay penalties like done might cause.  Unit test code is different from actual applicable code.  In unit test code, I think it's perfectly fine to make it as easy to follow as possible.

My biggest concern with the doc is that it does assertions inside of the subscribe block.  As the code lives on and new developers touch the code, the done function might be removed and the test will continue to pass even when the assertion is no longer valid, because without the done function, the assertion will just be skipped.

I am open to other solutions that doesn't put the assertions inside of the subscribe block.

**Comment by Airblader** [comment]
I didn't want to start a bigger discussion here, so I'll refrain from driving that further; but just an unopinionated note that there is precedence for your suggestion in Angular already, see https://angular.io/api/core/testing/fakeAsync#example.

For the sake of beginners I'd personally like to see there being utilities such as a function that subscribes to an observable and collects all values and returns them. Ideally this could detect that it is run in fakeAsync and throw a helpful error otherwise; that way the problematic pattern is hidden from the user, it looks better in code and it is protected against usage outside fakeAsync. But such an idea is outside the scope of this issue.

**Comment by flash-me** [comment]
I'm totally with @Airblader,

because the "natural" way of writing reactive code (rxjs), whether it's async or not is 

```ts
service.getObs().subscribe(value => {
   // handle emits
})
```

and therefore writing test should be familiar to that approach, which is

```ts
  it('#getObservableValue should return value from observable',
    (done: DoneFn) => {
    service.getObservableValue().subscribe(value => {
      expect(value).toBe('observable value');
      done();
    });
  });
```

Introducing the usage of `fakeAsync` for tests is imho a breach of style and doesn't resemble the patterns, one would use in the actual code. Even more this two different approaches for actual code and tests would rather lead to confusion for beginners than remaining consistent.

cheers
flash ⚡

**Comment by JeanMeche** [comment]
I agree, using `done()` is perfectly legitimate and matches the pattern of observables. I'll close this issue.
