### ISSUE TITLE
Error: "Caught Attempt to detect changes on a dehydrated detector." is common & very difficult to debug

### ISSUE THREAD

**Issue by jbdeboer** [angular/angular#4486]
c.f: internal bug id  24619573

**Comment by naomiblack** [comment]
This may be resolved by the new compiler. Checking with internal teams to verify.

**Comment by tandu** [comment]
angular 46. Have faced with this error too. Any suggestions how to debug it and what is casing that issue?

**Comment by tbosch** [comment]
@vsavkin worked on this recently

**Comment by vsavkin** [comment]
The issue happens when Angular internal data structures get into an invalid state. There were a couple of reasons where this could happen. I fixed those a few days ago.

Now, you should not never see this exception unless you use Angular 2 private APIs and get the internal data structures into inconsistent state yourself. We cannot really do much about it.

So I am closing this now. If you see this exceptions when using only public APIs, please open a new issue with a new repro case.

**Comment by jasonslyvia** [comment]
For anyone come across this, please refer to #6786
