### ISSUE TITLE
Angular13.1.2 works well in production mode but throws error in development mode

### ISSUE THREAD

**Issue by luozt** [angular/angular#44992]
### Which @angular/* package(s) are the source of the bug?

compiler

### Is this a regression?

No

### Description

```js
// ...
            "development": {
              "buildOptimizer": false,
              "optimization": true, // if set it to `false`, app throws error
              "vendorChunk": true,
              "extractLicenses": false,
              "sourceMap": true,
              "namedChunks": true
            },
```

My project has been constructed on the basis of Angular2(beta) since 2016。 Now I prepare to upgrade it from Angular8 to Angular13. After updating angular and related npm packages, and adjusting so much code, the app works well! But only in production mode, which means I have to set "optimization" to `true`.

If I set "optimization" to `false`, after the app navigated from home page to any other route, it would throw an error in the console:

```
Uncaught (in promise): TypeError: Cannot read properties of undefined (reading 'ɵmod')
```

So is there a bug in Compiler or Router? Or any problem in my way?

### Please provide the exception or error you saw

```true
Error: Uncaught (in promise): TypeError: Cannot read properties of undefined (reading 'ɵmod')
TypeError: Cannot read properties of undefined (reading 'ɵmod')
    at getNgModuleDef (core.mjs:1120:29)
    at recurse (core.mjs:21703:21)
    at recurse (core.mjs:21714:17)
    at recurse (core.mjs:21714:17)
    at registerNgModuleType (core.mjs:21699:5)
    at new NgModuleFactory (core.mjs:21821:13)
    at Compiler.compileModuleSync (core.mjs:25011:16)
    at Compiler.compileModuleAsync (core.mjs:25017:37)
    at router.mjs:3982:43
    at doInnerSub (mergeInternals.js:19:19)
    at resolvePromise (zone.js:1213:31)
    at resolvePromise (zone.js:1167:17)
    at zone.js:1279:17
    at ZoneDelegate.invokeTask (zone.js:406:31)
    at Object.onInvokeTask (core.mjs:25415:33)
    at ZoneDelegate.invokeTask (zone.js:405:60)
    at Zone.runTask (zone.js:178:47)
    at drainMicroTaskQueue (zone.js:582:35)
    at invokeTask (zone.js:491:21)
    at ZoneTask.invoke (zone.js:476:48)
```

### Please provide the environment you discovered this bug in (run `ng version`)

```true
Angular CLI: 13.1.3
Node: 12.20.1
Package Manager: npm 6.14.10
OS: Windows10 x64


+-- @angular-builders/custom-webpack@13.0.0
+-- @angular-devkit/build-angular@13.1.3
+-- @angular/animations@13.1.2
+-- @angular/cli@13.1.3
+-- @angular/common@13.1.2
+-- UNMET PEER DEPENDENCY @angular/compiler@13.1.2
+-- @angular/compiler-cli@13.1.2
+-- UNMET PEER DEPENDENCY @angular/core@13.1.2
+-- @angular/forms@13.1.2
+-- @angular/platform-browser@13.1.2
+-- @angular/platform-browser-dynamic@13.1.2
+-- @angular/router@13.1.2
+-- @compodoc/compodoc@1.1.18
+-- @types/jasmine@3.10.3
+-- @types/jasminewd2@2.0.10
+-- @types/node@12.20.41
+-- @types/qrcode@1.4.2
+-- angular-tree-component@8.5.6
+-- blueimp-md5@2.19.0
+-- bootstrap@3.4.1
+-- co-body@6.1.0
+-- codelyzer@5.2.2
+-- cookie-parser@1.4.6
+-- UNMET PEER DEPENDENCY core-js@3.20.2
+-- cross-env@6.0.3
+-- crypto-js@3.3.0
+-- echarts@4.9.0
+-- ejs@2.7.4
+-- express@4.17.2
+-- fs-extra@8.1.0
+-- html-webpack-plugin@3.2.0
+-- http-proxy@1.18.1
+-- husky@3.1.0
+-- UNMET PEER DEPENDENCY jasmine-core@3.4.0
+-- jquery@1.12.4
+-- jsencrypt@3.2.1
+-- karma@6.3.11
+-- karma-chrome-launcher@3.1.0
+-- karma-coverage@2.1.0
+-- karma-coverage-istanbul-reporter@2.0.6
+-- karma-jasmine@4.0.1
+-- karma-jasmine-html-reporter@1.7.0
+-- karma-mocha-reporter@2.2.5
+-- karma-sourcemap-loader@0.3.8
+-- lint-staged@9.5.0
+-- minimist@1.2.5
+-- moment@2.29.1
+-- ng-zorro-antd@13.0.0
+-- ngx-echarts@4.2.2
+-- prettier@1.19.1
+-- pug@2.0.4
+-- pug-html-loader@1.1.5
+-- qrcode@1.5.0
+-- raw-loader@4.0.2
+-- rxjs@7.4.0
+-- sa-sdk-javascript@1.21.3
+-- serve-favicon@2.5.0
+-- stylelint@12.0.1
+-- stylelint-config-prettier@7.0.0
+-- svgo@1.3.2
+-- tslib@2.3.1
+-- tslint@5.20.1
+-- typescript@4.5.4
+-- UNMET PEER DEPENDENCY webpack@^1.0.0 || ^2.0.0 || ^3.0.0 || ^4.0.0
+-- xlsx@0.15.6
`-- zone.js@0.11.4
```

**Comment by luozt** [comment]
To click ` at registerNgModuleType (core.mjs:21699:5)` can locate in: 

```typescript
// core.mjs Line 21697
function registerNgModuleType(ngModuleType) {
    const visited = new Set();
    recurse(ngModuleType); // <------------------ located here
    function recurse(ngModuleType) {
        // The imports array of an NgModule must refer to other NgModules,
        // so an error is thrown if no module definition is available.
        const def = getNgModuleDef(ngModuleType, /* throwNotFound */ true);
        const id = def.id;
        if (id !== null) {
            const existing = modules.get(id);
            assertSameOrNotExisting(id, existing, ngModuleType);
            modules.set(id, ngModuleType);
        }
        const imports = maybeUnwrapFn(def.imports);
        for (const i of imports) {
            if (!visited.has(i)) {
                visited.add(i);
                recurse(i);
            }
        }
    }
}
```

**Comment by luozt** [comment]
Angular CLI: 13.1.3
Node: 12.20.1
Package Manager: npm 6.14.10
OS: win32 x64

Angular: 13.1.2
... animations, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1301.3
@angular-devkit/build-angular   13.1.3
@angular-devkit/core            13.1.3
@angular-devkit/schematics      13.1.3
@angular/cli                    13.1.3
@schematics/angular             13.1.3
rxjs                            7.4.0
typescript                      4.5.4

**Comment by JoostK** [comment]
This typically happens when there's a circular import cycle somewhere in your application. This cycle might disappear in production builds due to optimization passes dropping dead code (and therefore allow certain imports to be removed as well).

You may be able to find all cycles by setting `"showCircularDependencies": true` in the build architect of the project in `angular.json`.

**Comment by luozt** [comment]
Thanks, JoostK! You are right! My application does have circular import cycles. I need to figure out them by setting `"showCircularDependencies": true` you said. Thank you again!

**Comment by luozt** [comment]
However, I find that there are too many circular dependencies in the application. 

Is there a option in `angular.json` that can also pass dropping dead code or ignore circular dependencies in dev mode of Angular13? As in earlier version of Angular, circular dependencies do not break the app or result in error in development mode.

**Comment by JoostK** [comment]
I don't quite understand what you're asking for. Cyclic imports in ES modules have to broken _somewhere_, potentially resulting in `undefined` bindings if a symbol is used in a top-level statement. Angular decorators are top-level constructs, so references to symbols in other modules may end up being `undefined` if they are part of an import cycle. AFAIK there is no tooling to detect situations like these except for those that report any import cycle, which is what `showCircularDependencies` does (although that option is deprecated and being removed in Angular 14, as it has severe performance overhead and it's more of a linting concern).

You might be able to use `forwardRef` to avoid a top-level reference (it would be wrapped into a closure instead) to a symbol that is part of an import cycle, but I don't have a good approach to determine when that is needed. In general it's desirable that there are no cyclic module imports at all, but I realize that can be challenging to achieve sometimes (but certainly not impossible).

I do see a potential improvement here, where the runtime could report an error message (in development builds only to avoid code size overhead) when it encounters an unexpected `undefined` value. Still, such an error wouldn't be able to tell exactly what is wrong and an `undefined` value may not even be due to cyclic imports, but it may be able to provide hints and possible resolutions instead of resulting in a `TypeError`.

**Comment by luozt** [comment]
Sorry JoostK, I should make it clearer.

The fact is, in my application, there are more than 100 circular dependency warnings like:`Warning: Circular dependency detected:
src\config\api-config.ts -> src\config\api-config-items\index.ts -> src\config\api-config-items\a-index.ts -> src\config\api-config-items\checkCrdtadventrusts.ts -> src\config\index.ts -> src\config\api-config.ts`

It is unrealistic to fix all those warnings. 

As the application works well in Angular8 although with those circular dependencies, I just want to find a way to let the app run well in Angular13 in development builds, without fixing the warnings.

**Comment by JoostK** [comment]
I can's say why it worked in Angular 8. As I mentioned, I don't know of a way to identify which cycle is causing the problem here. From the cycle paths you might spot an edge from some module A file to some module B file; you can then change module A to use `forwardRef(() => ModuleB)` to hide the top-level reference in a closure, which avoids an `undefined` there.

**Comment by luozt** [comment]
Oh, things seems a little bit tough. I continue to study that error of "emod". Wish finding a way to resolve it. If I succeed, I comment my resolution here. If not, I close this issue.

**Comment by JoostK** [comment]
If you set an exception breakpoint, the debugger will automatically stop there when the errors occurs. You can then explore the stack frames above the current frame, which will give some insight in which NgModule's imports array contains the `undefined` value.

**Comment by luozt** [comment]
According to:

```
Error: Uncaught (in promise): TypeError: Cannot read properties of undefined (reading 'ɵmod')
TypeError: Cannot read properties of undefined (reading 'ɵmod')
    at getNgModuleDef (core.mjs:1120:29)
```

I located in the code and set debugger:

```typescript
function getNgModuleDef(type, throwNotFound) {
    const ngModuleDef = type[NG_MOD_DEF] || null; // I set debugger here
    if (!ngModuleDef && throwNotFound === true) {
        throw new Error(`Type ${stringify(type)} does not have 'ɵmod' property.`);
    }
    return ngModuleDef;
}
```

Then, I found that the function `getNgModuleDef` would be called many times but something strange happened:

In the case of navigating from login page to home page, even if the argument `type` of the function `getNgModuleDef` is `undefined`, the app does not throw errors. 

But in the case of navigating from home page to business page, when the `type` is `undefined`, the app immediately throws an error of `TypeError: Cannot read properties of undefined (reading 'ɵmod')`. 

That is so strange!

**Comment by luozt** [comment]
Happy Chinese Lantern Festival！
