### ISSUE TITLE
Interpolation in Router-Templates not working with SystemJS

### ISSUE THREAD

**Issue by Belkar** [angular/angular#4504]
I have a simple Application with a router. The router currently has 2 Pages. The pages only consist of a simple binding with `{{name}}`. The problem is, that the whole object containing this binding is empty when the router loads the page up. (`<p>I am {{name}}<p>` becomes `<p class="ng-binding"></p>`)

The intressting thing hereby is that this issue only occures if I use SystemJS to load Angular2. As soon as I add a `<script>`-Tag pointing to https://code.angularjs.org/2.0.0-alpha.37/angular2.min.js the bindings are working as they should.

Here is a link to my repository:
https://github.com/Belkar/CampinaAsAService/

**Comment by alexpods** [comment]
Try to add `import 'zone.js';` right after `import 'reflect-metadata';` [here](https://github.com/Belkar/CampinaAsAService/blob/master/src/CampinaAsAService/app/main.ts#L1)

**Comment by Belkar** [comment]
WOW that was a fast response.
That did the trick. Thanks :-)

**Comment by rchodava** [comment]
This happened to me too even with 2.0.0-beta.0 of the framework. Interpolation is broken when it is in a component routed to - if I use the component directly in another template, it works fine - when it is routed to using router, the whole element content in which the interpolation exists is blank. Adding zone.js worked - is the issue here that zones are not available? It seems like if that is the case, at the least, there should be an error - there is nothing in the logs indicating anything is wrong - interpolation just doesn't work.

**Comment by jmcooper** [comment]
I'm seeing this same behavior in 2.0.0-beta.0.  I have created a small git repo that reproduces the problem here: https://github.com/jmcooper/ng2beta-seed.  I tried reproducing this in a plunker, but interestingly the systemjs config I was using there didn't reproduce the problem.

**Comment by jmcooper** [comment]
Ah, I was missing: <script src="node_modules/angular2/bundles/angular2-polyfills.js"></script>.  When I added that it started working.  I was also missing rxjs, but this wasn't causing a problem.  Not sure what parts of Angular require rxjs.
