### ISSUE TITLE
Link to source code is broken

### ISSUE THREAD

**Issue by nseni** [angular/angular#45119]
### Description

https://angular.io/api/common/AsyncPipe
click the top right button "View Source"

### What is the affected URL?

https://angular.io/api/common/AsyncPipe

### Please provide the steps to reproduce the issue

Click the top right button "View Source"

### Please provide the expected behavior vs the actual behavior you encountered

I assume it should lead to https://github.com/angular/angular/blob/13.2.x/packages/common/src/pipes/async_pipe.ts#L54-L154
Instead, it leads to https://github.com/angular/angular/tree/13.2.3/packages/common/src/pipes/async_pipe.ts#L54-L154

### Please provide a screenshot if possible

![image](https://user-images.githubusercontent.com/47851128/154431991-23ab1a3a-febb-4d2a-9a51-f365c99d7521.png)

**Comment by JoostK** [comment]
This is likely due to how the 13.2.3 release has failed _after_ the release commit was made in #45116, so we're now in an inconsistent state where angular.io believes that 13.2.3 is available but that version hasn't actually been tagged on NPM/Github yet.

This will resolve itself once the release of 13.2.3 is re-attempted.

**Comment by nseni** [comment]
The button works fine now.
