### ISSUE TITLE
testing library name is used inconsistently

### ISSUE THREAD

**Issue by IgorMinar** [angular/angular#4512]
we have:
- `test_lib.d.ts` that declares `angular2/test_lib` module
- `test_lib.dev.js` that registers `angular2/test` module

can we unify these?

@jeffbcross, I thought that we settled on `angular2/testing` as the final name during the big package rename. wasn't that the case?

**Comment by rolandjitsu** [comment]
I actually just stumbled upon this issue as well while running some unit tests.

**Comment by IgorMinar** [comment]
I fixed this partially in #4556 without a breaking change by aligning everything with `test_lib`

We should still follow up on this in alpha-41 with a breaking change that renames the module to `testing`

**Comment by rolandjitsu** [comment]
@IgorMinar [4556](https://github.com/angular/angular/pull/4556) did not make it into alpha `39`. Also, what about `angular2/src/test_lib/e2e_util`, will that be exposed as public API? Because I do use `verifyNoBrowserErrors` in E2E tests.

**Comment by IgorMinar** [comment]
@rolandjitsu it's part of a40 due tomorrow-ish.

wrt `verifyNoBrowserErrors` that's not a public api at the moment. @juliemr can you make a note of this in the testing API doc? I think it's a useful api, but we need to look into if it can be made public as is or if some changes are needed.

**Comment by rolandjitsu** [comment]
@IgorMinar I see, looking forward to it :+1: 

I figured it is not, but as you said, it might prove useful to some users, I know it is for me. It would be great to have it public.

**Comment by juliemr** [comment]
Sorry, I'm not sure what the decision was on the naming here. Can we clarify? 

- We have a public testing library, which is currently the `angular2/test_lib` module
- We have an internal to angular core testing module, which is currently `angular2/test` module

I do not think these should be unified, since we may be using internal things in testing which should not be publicly exported. I think the naming should be clarified and made more specific. I'd propose:

- Make test internal say so clearly: `angular2/test_internal`
- The public can be renamed to `angular2/testing`, I don't really care here.

**Comment by naomiblack** [comment]
@IgorMinar is taking this one to think through whether it is a breaking change or not. We're trying to land it before Angular Connect.

**Comment by juliemr** [comment]
One proposal at https://github.com/angular/angular/pull/4697 - I'll take a look at the ci errors (unhappy dart analyzer) in the morning, if we like the rename.

**Comment by juliemr** [comment]
Closed with f529236bfc7868c3c53438c1b20d821c12bb8d4a
