### ISSUE TITLE
CSP trusted types error: "This document requires 'TrustedScriptURL' assignment." with service worker

### ISSUE THREAD

**Issue by kolkov** [angular/angular#45145]
### Which @angular/* package(s) are the source of the bug?

Don't known / other

### Is this a regression?

No

### Description

I try to use Content security policy with Angular service worker enabled, but got console error messages.

### Please provide a link to a minimal reproduction of the bug

https://online.freicon.ru/

### Please provide the exception or error you saw

```true
main.29cfcfcc259c26c9.js:formatted:2634 [Report Only] This document requires 'TrustedScriptURL' assignment.
```

### Please provide the environment you discovered this bug in (run `ng version`)

```true
Angular CLI: 13.2.3                                             
Node: 17.5.0 (Unsupported)
Package Manager: npm 6.14.16
OS: win32 x64

Angular: 13.2.2
... animations, common, compiler, compiler-cli, core, forms     
... language-service, platform-browser, platform-browser-dynamic
... router, service-worker

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1302.3
@angular-devkit/build-angular   13.2.3
@angular-devkit/core            13.2.3
@angular-devkit/schematics      13.2.3
@angular/cdk                    13.2.3
@angular/cli                    13.2.3
@angular/pwa                    0.803.29
@schematics/angular             13.2.3
ng-packagr                      13.1.3
rxjs                            7.4.0
typescript                      4.4.4

Warning: The current version of Node (17.5.0) is not supported by Angular.
```

### Anything else?

![image](https://user-images.githubusercontent.com/3740898/154826683-817aca10-a61c-4c9f-b010-be389da4188c.png)

My Nginx headers for Content security policy:
`add_header Content-Security-Policy-Report-Only "require-trusted-types-for 'script'";`

**Comment by gkalpak** [comment]
Since `navigator.serviceWorker.register()` is considered an [injection sink][1] and you are using Trusted Types in your app, you must ensure that the string used to specify the SW script is trusted. How to do this depends on how you implement your policies.

For an example, you can see how we do this in the angular.io app using the [safevalues][2] package (but that not the only way):
https://github.com/angular/angular/blob/5957ff4163f55d814be2cf80b9909244f1ce5262/aio/src/app/app.module.ts#L158-L161

##
Closing the issue since this is something that needs to be taken care of in the app (not in `@angular/service-worker`), but feel free to continue the discussion below.

[1]: https://w3c.github.io/webappsec-trusted-types/dist/spec/#injection-sink
[2]: https://www.npmjs.com/package/safevalues
