### ISSUE TITLE
Vulnerable libraries angular JavaScript angular.js 1.5.3 SNYK-npm 

### ISSUE THREAD

**Issue by hathemi** [angular/angular#45151]
### Which @angular/* package(s) are the source of the bug?

animations, Don't known / other

### Is this a regression?

Yes

### Description

i tried to publish an updated version of my android apk, but i had this error and my updated apk get rejected about vulnerable libraries angular !

`* JavaScript angular.js 1.5.3 SNYK-npm:angular:20171018, SNYK-npm:angular:20180202 assets/www/lib/angular-sanitize/angular-sanitize.js, assets/www/lib/ionic/js/angular/angular-animate.min.js, assets/www/lib/ionic/js/angular/angular-animate.js, assets/www/lib/angular-animate/angular-animate.min.js, assets/www/lib/angular/angular.js, assets/www/lib/angular-sanitize/angular-sanitize.min.js, assets/www/lib/angular-animate/angular-animate.js, assets/www/lib/ionic/js/angular/angular.min.js, assets/www/lib/ionic/js/angular/angular-sanitize.min.js, assets/www/lib/ionic/js/angular/angular-resource.js, assets/www/lib/ionic/js/angular/angular.js, assets/www/lib/ionic/js/angular/angular-resource.min.js, assets/www/lib/ionic/js/angular/angular-sanitize.js, assets/www/lib/angular/angular.min.js`

this is the first time i had faced this kind of problem! any help please ?

### Please provide the environment you discovered this bug in (run `ng version`)

```true
ng version
Your global Angular CLI version (13.1.4) is greater than your local version (6.2.9). The local Angular CLI version is used.

To disable this warning use "ng config -g cli.warnings.versionMismatch false".

     _                      _                 ____ _     ___
    / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
   / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
  / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
 /_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
                |___/


Angular CLI: 6.2.9
Node: 16.13.2
OS: win32 x64
Angular: 6.1.10
... animations, common, compiler, compiler-cli, core, forms
... http, platform-browser, platform-browser-dynamic

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.8.9
@angular-devkit/build-optimizer   0.0.35
@angular-devkit/core              0.8.9
@angular-devkit/schematics        0.8.9
@angular/cli                      6.2.9
@schematics/angular               0.8.9
@schematics/update                0.8.9
rxjs                              6.6.7
typescript                        3.9.7
webpack                           5.69.0
```

**Comment by gkalpak** [comment]
This repository is for Angular v2+. The old AngularJS 1.x version is [here][1].
Note that v1.5.3 has not been a supported version for a very long time. The AngularJS v1.x project is currently at End-Of-Life and no longer maintained/supported (see [there][2]), but the last version that was supported (up until a couple of months ago) is 1.8.x. If you can't upgrade to the latest 1.8.x version (due to breaking changes or other limitations), maybe you could at least try updating to the latest 1.5.x version (v1.5.11).

In any case, closing since this it not the right repository and the AngularJS v1.x project is no longer maintained anyway.

[1]: https://github.com/angular/angular.js
[2]: https://docs.angularjs.org/misc/version-support-status
