### ISSUE TITLE
This constructor is not compatible with Angular Dependency Injection because its dependency at index 0 of the parameter list is invalid.

### ISSUE THREAD

**Issue by infacto** [angular/angular#45155]
### Which @angular/* package(s) are the source of the bug?

core

### Is this a regression?

No

### Description

Following eslint no-useless-constructor and JavaScript behavior, an empty constructor is not required to be defined, since JavScript automatically handles it. Same for the mandory super call for derived classes.

But in Angular it seems that this does not work. Angular always want the same constructor again and again for every derived class.

Example: 

```ts
export abstract class AbstractMyService {
  constrcutor(private anotherService: AnotherService) {}
}

@Injectable({ providedIn: 'root' })
export class MyService extends AbstractMyService  {
  /** no empty / useless constructor here. JS handles it. */
}
```

But Angular throws an error on runtime: 

> This constructor is not compatible with Angular Dependency Injection because its dependency at index 0 of the parameter list is invalid. This can happen if the dependency type is a primitive like a string or if an ancestor of this class is missing an Angular decorator.

It works only if I provide the "useless" constructor.

```ts
@Injectable({ providedIn: 'root' })
export class MyService extends AbstractMyService  {
  constrcutor(private anotherService: AnotherService) {
    super(anotherService);
  }
}
```

Btw. adding `emitDecoratorMetadata` to tsconfig does only change the error message, but does not fix the problem.

```
Angular 12.x
```

**Comment by JoostK** [comment]
This is working as designed. If `AbstractMyService` wants to participate in Angular's DI mechanism, then it needs to be decorated with `@Injectable()` to capture the necessary constructor metadata. The subclass that is decorated does not capture such metadata if there is no constructor, it will instead depend on the metadata of the base class. The subclass cannot replicate the metadata from the parent class by itself, because 1) the parent class may exist in a different compilation unit, and 2) because the parent class may use types that are internal to the source file of that parent class.
