### ISSUE TITLE
`postinstall: ngcc` required or not in Angular 13 Ivy app consuming Ivy library

### ISSUE THREAD

**Issue by sahilbabbar** [angular/angular#45165]
### Which @angular/* package(s) are the source of the bug?

compiler-cli

### Is this a regression?

No

### Description

**Observation 1:** After upgrading an Ivy application to v13, `postinstall: ngcc` wasn't removed automatically during update steps.

**Observation 2:** When a new v13 application is created, `postinstall: ngcc` is not present.

**Query 1:** Is `postinstall: ngcc` required in v13, if the application as well as the library are at the exact same versions of Angular and the corrosponding dependencies and both are Ivy enabled?

**Query 2:** On building an Ivy library, the output `package.json` contains a script that blocks `npm publish`. This has been the behaviour for the past few releases of Angular and now also in v13. Is it due to the on-going development in Ivy area? And do the previous discussed [solution ](https://github.com/angular/angular/issues/41048#issuecomment-791445840)holds true for v13 as well?

**Query 3:** Would it cause any harm(given the above scenario) if we don't use `postinstall: ngcc`? (Also observed that the build time with `ngcc` is around 2.7x as compared to build time without it).

### Please provide the exception or error you saw

```true
No error.
```

### Please provide the environment you discovered this bug in (run `ng version`)

```true
Angular CLI: 13.2.3
Node: 14.15.1
Package Manager: npm 6.14.8
OS: win32 x64

Angular: 13.2.2
... animations, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1302.3
@angular-devkit/build-angular   13.2.3
@angular-devkit/core            13.2.3
@angular-devkit/schematics      13.2.3
@angular/cli                    13.2.3
@schematics/angular             13.2.3
rxjs                            6.6.3
typescript                      4.4.4
```

**Comment by alan-agius4** [comment]
**Postinstall NGCC**
The requirement to run NGCC as a postinstall hook was removed in version 9.  When using the Angular CLI to build your applications and libraries NGCC will be invoked on demand when depending on a library which have been built and published in ViewEngine format. Our recommendation was and still is not to invoke NGCC manually unless it is absolutely needed.

**Publishing Ivy libraries**
As of version 13 Ivy libraries can be published on NPM. In fact building the library using ViewEngine is no longer possible. However, this needs to be compiled in partial mode as otherwise the tooling will block `npm publish` via the mentioned script. You can learn more about this in here: https://angular.io/guide/creating-libraries#publishing-libraries
