### ISSUE TITLE
Angular 13.2.5: Input Pattern empty string or undefined results error with native validation

### ISSUE THREAD

**Issue by achackr1900** [angular/angular#45193]
### Which @angular/* package(s) are the source of the bug?

Don't known / other

### Is this a regression?

Yes

### Description

If you want to set the [pattern] property with a variable and the default value of the variable is an empty string, you do not have the chance to enter some valid data. With native validation enabled, the browser denies any value with format error like doesn't match the pattern. 
The expected behavior should be not "rendering" the pattern attribute if it's undefined or empty. That was also the behavior before 13.2.5 (13.2.1 was also okay). 

### Please provide a link to a minimal reproduction of the bug

[go to Stackblitz](https://angular-ivy-wndzik.stackblitz.io)

### Please provide the environment you discovered this bug in (run `ng version`)

```true
_                      _                 ____ _     ___
    / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
   / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
  / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
 /_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
                |___/
    

Angular CLI: 13.2.5
Node: 14.17.4
Package Manager: npm 8.3.0
OS: darwin x64

Angular: 13.2.4
... animations, cdk, common, compiler, compiler-cli, core, forms
... material, platform-browser, platform-browser-dynamic, router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1302.5
@angular-devkit/build-angular   13.2.5
@angular-devkit/core            13.2.5
@angular-devkit/schematics      13.2.5
@angular/cli                    13.2.5
@schematics/angular             13.2.5
rxjs                            7.5.4
typescript                      4.5.5
```

**Comment by AndrewKushnir** [comment]
@achackr1900 thanks for providing a Stackblitz demo. I've looked at the template and found this code:
```
<input [pattern]="pattern" />
```
Since there are no other Forms-related attributes (like `ngModel` or `formControl`), this is treated as a regular binding with an empty string and an attribute is added to the DOM, so this seems to be worked as expected.

As a possible solution, I'd propose using `'.*'` as a default value for pattern instead of an empty string.

I'm closing this issue for now, please reopen if the problem still exists.

Thank you.
