### ISSUE TITLE
NgModuleRef.destory() doesn't clean up providers for freshly initialized Angular project

### ISSUE THREAD

**Issue by alshdavid** [angular/angular#45353]
### Which @angular/* package(s) are the source of the bug?

core

### Is this a regression?

No

### Description

I have a use case where I need to completely tear down my Angular application then bootstrap it again as if Angular was never bootstrapped there in the first place (I know it's wacky).

It appears the `.destroy()` method leaves behind the providers for subsequent Angular initializations to use.

If I have an application that has an external counter and dependency injects the value of the counter into the application, tearing down and bootstrapping the whole application whenever there is a new value on the counter - consumers of that dependency will always get the first value provided - even if the instance consuming that value has been `.destroy()`ed

```typescript
let i: number = 0;
let ngRef: NgModuleRef | undefined

setInterval(async () => {
  i++;

  if (ngRef) {
    ngRef.destroy();
    ngRef = undefined;
  }

  document.body.appendChild(document.createElement('app-root'))

  const staticProviders: StaticProvider[] = [
    { provide: 'setInterval', useValue: i },
  ]

  ngRef = await platformBrowserDynamic(staticProviders)
    .bootstrapModule(AppModule);
}, 5000);
```

```typescript
@Component({
  selector: 'my-app',
  template: '<p>Count: {{ count }}</p>', // I expect this to count "1", "2", "3"... but it will always render "1" no matter the real value
})
export class AppComponent {
  constructor(@Inject('setInterval') public count: number) {}
}
```

### Please provide a link to a minimal reproduction of the bug

https://stackblitz.com/edit/angular-ivy-j98gpu?file=src%2Fmain.ts

### Please provide the environment you discovered this bug in (run `ng version`)

```true
Angular CLI: 13.2.6
Node: 16.13.0
Package Manager: pnpm 6.25.0
OS: darwin x64

Angular: 13.2.6
... animations, cli, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1302.6 (cli-only)
@angular-devkit/build-angular   13.2.6
@angular-devkit/core            13.2.6 (cli-only)
@angular-devkit/schematics      13.2.6 (cli-only)
@schematics/angular             13.2.6 (cli-only)
rxjs                            7.5.5
typescript                      4.5.5
```

**Comment by JoostK** [comment]
This is working as expected; destroying the `NgModuleRef` is not sufficient to teardown everything, in particular the `PlatformRef` is retained. It's exactly that `PlatformRef`'s injector that has your DI services, as `staticProviders` is passed to `platformBrowserDynamic(staticProviders)`. That call returns a `PlatformRef` that needs to be destroyed, instead of only destroying the `NgModuleRef` that is created as a child.

The fix is to capture the return value of `platformBrowserDynamic(staticProviders)` and destroy that, not just the `NgModuleRef` (the `NgModuleRef` would be destroyed together with `PlatformRef` if you destroy the `PlatformRef`).
