### ISSUE TITLE
Test Injector should not by default mock out Compiler's XHR service

### ISSUE THREAD

**Issue by IgorMinar** [angular/angular#4539]
If I want to test a component with external templates, I need to reach into Angular's privates to override the XHR provider (nee di binding):

```
import {XHR} from 'angular2/src/core/compiler/xhr';
import {XHRImpl} from 'angular2/src/core/compiler/xhr_impl';

…

beforeEachBindings(() => {
    return bind(XHR).toClass(XHRImpl);
  });
```

The default is useful only for testing Angular Compiler but not for testing Angular applications, so we should change this so that by default the XHR service is not mocked out and only in the Angular core suite we override the provider with mock.

cc: @wardbell @johnpapa

**Comment by juliemr** [comment]
@IgorMinar so if I understand correctly, now we don't bind XHR to MockXHR, but we don't bind it to XHRImpl either. I don't think this really solves the problem, because a user still needs to reach into Angular privates in order to get the actual XHRImpl. Am I misunderstanding, or should we reopen this?

**Comment by IgorMinar** [comment]
oh crap. we we need to fix this.
