### ISSUE TITLE
ProvideIn singleton service among multiple angular instances

### ISSUE THREAD

**Issue by vugar005** [angular/angular#45403]
### Which @angular/* package(s) are relevant/related to the feature request?

core

### Description

Hello team,
Right now we do not have a way to have a **singleton** service among multiple angular instances. This is crucial when implement microfrontends. 
Let's say we have shell microfrontend which has service AuthService, the remote angular element microfrontends also should be able to have acess to service in singleton way. 

![tempsnip](https://user-images.githubusercontent.com/28726265/159176529-3337b61e-cb83-42ca-8895-37ed82a63825.png)

I thought it could be done via `providedIn: 'platform'` but it appears that it is intended to be for multiple angular modules. Thanks to [comment](https://github.com/angular/angular/issues/45399#issuecomment-1073747516). So it does not suite this case. If we use  providedIn: 'platform'`  the service is gonna be instantiated multiple times in shell and custom angular microfrontend element.
Sample repo for playground:  https://github.com/vugar005/youtube-webapp-turborepo/pull/22 

### Proposed solution

We can propose new key something like  `provideIn: "true-platform"` to solve this case.

### Alternatives considered

No suitable alternatives found so far for dependency injection.

**Comment by AleksanderBodurri** [comment]
This is a cool use case, I wonder if it makes sense for this to be handled by the framework though. Managing a kind of global injector that is tied to the webpage instead of individual angular instances seems like something better handled by a meta framework. I'm unaware of anything that does this. I'll detail a hack solution below that you can use to achieve this but I do not recommend that you do this in production.

I want to **strongly stress** that before going down this approach, you should consider if it is necessary for your use case. My understanding is that one of the principles of good micro-frontend design is that each application is independently deployable. To ensure this, it is good to make sure that remote applications do not depend on any runtime data structures created by other remotes or the shell (notice how this can be different than sharing common dependencies). My suggestion is provide a separate instance of your service in your remote. If you need to use services to store data that you want to share from your shell, consider if the remote application that is consuming the data is really a remote, or if it should just be part of the shell.

How to implement hack:
1. When your shell AppModule is bootstrapped, in the constructor, inject NgModuleRef (module injector) and expose it to the global object (window).
2. For each remote AppModule, in the module constructor, inject NgModuleRef and traverse its parent injectors until you reach the platform injector. Manually patch the platform injector to have its parent injector be the NgModuleRef you exposed in the step 1.

The reason this shouldn't be done for anything that isn't experimental is because patching the internals of the platform injector to point to your exposed module injector requires patching private APIs, which could potentially **lead to catastrophic breakages when you next update your Angular version (or permanent version locking)**.

**Comment by vugar005** [comment]
Hi @AleksanderBodurri ,
Thanks for reply. Yes I strongly agree with you that microfrontends should be independent from each other. Hence it is my aim , the repote apps on above mentioned repo are fully independent. But there are some scenarios(auth in this case) that I believe should be solved via singleton and those services should be readonly(only get methods). Wihout dependency injection, to resolve authentication state, I would pass the state (including access token) via input property to remote angular microfrontend element but I think it is a bit bad practice. The workaround you provided I guess might the best suit for internal applications. For publis applications, that solution would block server side rendering since window object is not available on SSR. So I am looking for  js or angular way to achieve that. I wonder if Google internal apps are using microfrontend using custom elements, how do they resolve this? 
Thanks in advance.

**Comment by AleksanderBodurri** [comment]
@vugar005 There should be ways of solving this specific problem without relying on sharing services between multiple Angular instances, like storing auth state in a cookie or localStorage/sessionStorage. Both approaches have different trade offs than storing auth state in memory, but seem more suited to this use case IMO.

For the general problem of sharing services between Angular instances: my feeling is that orchestrating any kind of interaction between multiple Angular instances is best handled by tooling outside of the framework (if it is necessary). For example, APIs like Web Storage or Indexed DB can be used to cache data from HTTP requests so that remotes don't have to refetch anything that was previously fetched from the shell or some other remote. Any cache miss could be handled by the remote fetching that data from the server. This way, your remotes stay independently deployable.

This makes more sense to me than creating a global injector for each angular instance on a web page, where you'd have to consider things like:
- What if a remote is loaded with a mismatched Angular version from your shell?
- What if a remote loads in a new service with the proposed `provideIn: "true-platform"`? Would we have to reconfigure the "true-platform" injector with the new service? If yes:
  -  What happens when a remote that provided a new service with `provideIn: "true-platform"` is destroyed? How will we clean up the injector? What happens to other remotes that are still referencing the new service?

Because service instances are runtime data structures, it is trickier to share them between application instances that are supposed to be decoupled (even if it is technically possible to couple them together). These considerations can be avoided by sharing serialized data instead, like in the Web Storage / Indexed DB example I gave above.

These are just my opinions 😄  Lets see what others think

**Comment by vugar005** [comment]
Thanks @AleksanderBodurri . Yes, as you mentioned storing shared data in cookies/indexDB is good but has trade offs. For example, it is a bit against the practice to store access token in local storage instead of memory.
* What if a remote is loaded with a mismatched Angular version from your shell?
We can prevent that by checking whether angular plattform exist then prevent another angular version instance. For example,
```
const ngVersion = VERSION.full;
(window as any).plattform = (window as any).plattform || {};
let platform = (window as any).plattform[ngVersion];
if (!platform) {
  platform = platformBrowser();
  (window as any).plattform[ngVersion] = platform;
} else {
  throw ('Please use same Angular version')
}
platform.bootstrapModule(AppModule).catch((err: any) => console.error(err));
```
* What if a remote loads in a new service with the proposed provideIn: "true-platform"? 
Yes I agree, this is a bit tricky but its developer responsibility imho. When we use 'true-platform' we should know what is this and how we should use that.
* What happens when a remote that provided a new service with aka `provideIn: "true-platform" `is destroyed?
When we use aka `'true-platform' `, we should only register in Shell app, when shell is destroyed all apps(shell + remotes) should be destroyed.

For now I guess as you also suggested, I can proceed with browser storage(cookies, indexdb). But still wonder how we can resolve this for storing sensitive data such as tokens. Looking forward for more answers)
Thanks again for nice points and potential drawbacks)

**Comment by mlc-mlapis** [comment]
@vugar005 Have you looked https://github.com/angular/angular/issues/40301?

**Comment by alxhub** [comment]
> Managing a kind of global injector that is tied to the webpage instead of individual angular instances
This is the intention behind Angular's platform - it's supposed to contain services which are singletons on the page. For example, the `PlatformLocation` service which interacts with the URL bar needs to be a singleton - there's only one URL bar on the page, regardless of how many Angular applications are running there.

Angular does not have first-party support for microfrontends. There are varying levels of isolation which can be enforced between multiple frontends on the page - they can either share the core platform, or be independent of it.

If independent platforms are used, I don't think Angular should have any built in mechanism to circumvent that isolation (and it's unclear how that would even work - how would the multiple frontend bundles even know about each other?). Instead, this is something an application can do manually, by configuring a `providedIn: 'platform'` provider with a factory that returns a globally constructed singleton instance. Sharing objects across multiple Angular versions should be done carefully - there is no guarantee that different versions of the runtime will be able to consume each other's services.
