### ISSUE TITLE
HTTP client stripping trailing whitespaces in URLs when there are no query parameters

### ISSUE THREAD

**Issue by lcanet** [angular/angular#45418]
### Which @angular/* package(s) are the source of the bug?

common

### Is this a regression?

No

### Description

When issuing an HTTP GET query with HttpClient, trailing whitespaces are stripped when there are no query parameters. However if there's at least one request param,the whitespace is properly encoded (%20)

Reproduction :
```
let params = new HttpParams();
this.http.get('/test ', {params}).subscribe( (res) => {
}, (err) => {
});
```
Observe in browser console; an HTTP request to '/test' is issued, stripping the white space

Add some parameter :
```
let params = new HttpParams();
params = params.set('hello', 'world');
this.http.get('/test ', {params}).subscribe( (res) => {
}, (err) => {
});
```
Request  issued is **/test%20?hello=world**

Expected behavior : stripping or encoding should be consistent if there are parameters or not

### Please provide the environment you discovered this bug in (run `ng version`)

```true
Angular CLI: 13.3.0
Node: 12.22.7
Package Manager: npm 6.14.15
OS: linux x64

Angular: 13.3.0
... animations, cdk, cli, common, compiler, compiler-cli, core
... forms, language-service, localize, platform-browser
... platform-browser-dynamic, router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1303.0
@angular-devkit/build-angular   13.3.0
@angular-devkit/core            13.3.0
@angular-devkit/schematics      13.3.0
@schematics/angular             13.3.0
ng-packagr                      13.3.0
rxjs                            6.6.7
typescript                      4.6.2
```

**Comment by andreistefanwork** [comment]
Hi @lcanet 

I am also able to reproduce this behaviour. I prepared a setup on stackblitz that illustrates the issue: https://stackblitz.com/edit/angular-ivy-nefcsv?file=src/app/app.component.ts

From my research, when you send an HTTP request with HttpClient, the request URL is computed inside HttpRequest in the if-else block here: https://github.com/angular/angular/blob/76f5a559e8047113985b5bc2741b96264da32eb9/packages/common/http/src/request.ts#L248

Building on your example:
- when no query parameters are provided, the computed URL will be `/test `
- when query parameters are provided, the computed URL will be `/test ?hello=world`

Then, the resulted URL is used to send an XMLHttpRequest here: https://github.com/angular/angular/blob/76f5a559e8047113985b5bc2741b96264da32eb9/packages/common/http/src/xhr.ts#L63

Turns out the behaviour of XMLHttpRequest open() is to perform a trim + encode operation on the received URL; this results in:
- `/test ` => `/test` //will work
- `/test ?hello=world` => `/test%20?hello=world` //will fail

I worked out on a [PR](https://github.com/angular/angular/pull/46097) where I'm trimming the base URL before the concatenation with query parameters takes place. This way, sending an HTTP request stays consistent, regardless of whether or not query parameters are utilized

Please have a look if everything looks alright

**Comment by jessicajaniuk** [comment]
Thanks for digging into this. We really appreciate the time and effort here. This is actually intentional behavior. When there are query parameters, we can't assume anyone wants whitepace removed as they may be intentionally part of the URL and parameters. When there's no query string, it's safe to trim. We don't want to be attempting to interpret people's behavior with whitespace here, and so we just accept what the browser does for that reason. Again, we really appreciate your time and effort to look into this.
