### ISSUE TITLE
When a component is imported from an `index.ts` it shares with its module, the module's dependencies are imported implicitly

### ISSUE THREAD

**Issue by RobertAKARobin** [angular/angular#45532]
### Which @angular/* package(s) are the source of the bug?

router

### Is this a regression?

No. Also found in v12.

## Setup

https://stackblitz.com/edit/angular-implicit-module-import?file=src%2Fapp%2Fapp.module.ts

Given an app structure like this:

```
src/
├── app
│   ├── app.component.ts
│   ├── app.module.ts
│   └── child
│       ├── child.component.ts
│       ├── child.module.ts
│       └── index.ts
```

And given `ChildComponent` is a child route, but `ChildModule` **is not included in `imports`**:

```ts
@NgModule({
  declarations: [AppComponent],
  imports: [
    BrowserModule,
    RouterModule.forRoot([
      {
        path: '',
        component: ChildComponent,
      },
    ]),
  ],
  bootstrap: [AppComponent],
})
export class AppModule {}
```

Finally, given that `child/index.ts` exports both `ChildModule` and `ChildComponent`:

```ts
export * from './child.component';
export * from './child.module';
```

## The bug

When `ChildComponent` is imported from `child/child.component`, compilation fails as expected: `ChildModule` is not initialized and `ChildComponent`s dependencies can't be found.

But when `ChildComponent` is imported from `child/index.ts`, compilation is successful, even though `ChildModule` is still not initialized -- put a `console.log` in its constructor and it won't appear in the console.

I would expect a component and its dependencies to compile successfully only if its module is imported.

### Please provide a link to a minimal reproduction of the bug

https://stackblitz.com/edit/angular-implicit-module-import?file=src%2Fapp%2Fapp.module.ts

### Please provide the environment you discovered this bug in (run `ng version`)

```true
$ ng version

     _                      _                 ____ _     ___
    / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
   / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
  / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
 /_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
                |___/
    

Angular CLI: 13.3.1
Node: 14.18.1
Package Manager: npm 7.5.6
OS: darwin x64

Angular: 13.3.1
... animations, cli, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1303.1
@angular-devkit/build-angular   13.3.1
@angular-devkit/core            13.3.1
@angular-devkit/schematics      13.3.1
@schematics/angular             13.3.1
rxjs                            7.5.5
typescript                      4.6.3
```

**Comment by JoostK** [comment]
This is essentially the same situation as described in #17446. It is because of the nature of NgModules; they serve as metadata to define the compilation scope of a component (which directives, pipes etc. are visible to it) at compile time, and then at runtime they can provide DI tokens for a module injector. You're seeing the effect of the _compilation metadata_ because the source file is seen by the compiler; the missing import does not cause a hard runtime failure but it may mean that DI tokens end up missing at runtime.

The [standalone components project](https://github.com/angular/angular/discussions/43784) aims to avoid these problems. This is actively being worked on at the moment; there will be an update on how it integrates with the router in the near future.

**Comment by RobertAKARobin** [comment]
Thanks, @JoostK !
