### ISSUE TITLE
old versions of doc url is working but 404 for sub content

### ISSUE THREAD

**Issue by sonyshankar2k** [angular/angular#45553]
### Which @angular/* package(s) are the source of the bug?

Don't known / other

### Is this a regression?

No

### Description

hit this url https://v2.angular.io/api/common/NgClass and you can see 404 in the body and no content is being display.
refer the screen shot
![image](https://user-images.githubusercontent.com/931375/162053353-bde8f876-388b-439c-91f8-5532979943e2.png)

### Please provide a link to a minimal reproduction of the bug

https://v2.angular.io/api/common/NgClass

**Comment by gkalpak** [comment]
This mostly affects the v2 version, because it has a very different layout than v4+ versions. There is not much we can do about it. For example, the `NgClass` API docs for v2 are [here][1].

If you need to look for v2 docs, your best bet is to go to the [API index page][2] and use the search.

[1]: https://v2.angular.io/docs/ts/latest/api/common/index/NgClass-directive.html
[2]: https://v2.angular.io/docs/ts/latest/api/
