### ISSUE TITLE
Wrong result in View Encapsulation document

### ISSUE THREAD

**Issue by rasool2348** [angular/angular#45611]
### Description

Hi,
I tried the example on stackblitz website and saw the result is different from what told on documentation.
I put the link of stalkblitz here and you can see the result and compare to documentation. Also put the related wrong phot
![Capture](https://user-images.githubusercontent.com/33632858/163113449-978af71f-19ce-4328-8193-98d3d7978c99.JPG)
o

https://stackblitz.com/edit/angular-hhekly?file=src/app/emulated-encapsulation.component.ts
please check the photo and link and let me know if I'm right or wrong thanks.

### What is the affected URL?

https://angular.io/guide/view-encapsulation

### Please provide the steps to reproduce the issue

I added the link in Description and added here too,

https://stackblitz.com/edit/angular-hhekly?file=src/app/emulated-encapsulation.component.ts

### Please provide the expected behavior vs the actual behavior you encountered

the component with noEncapsulation is dominant and no matter it was a child of shadowDomEncapsulation component or parent of it. in both case noneEncapsulation style is dominant and override shadowDomEncapsulation component.

my stalkblitz link and photo from angular.io guide are clear

### Please provide a screenshot if possible

![Capture](https://user-images.githubusercontent.com/33632858/163114278-3b91bd0c-cc98-4fd2-9701-1af3c3240cd0.JPG)
![Capture](https://user-images.githubusercontent.com/33632858/163114402-84596c72-0b12-48bb-b896-2875656ec3c5.JPG)

### Please provide the exception or error you saw

```true
no error occurred. we have wrong result.
```

### Is this a browser-specific issue? If so, please specify the device, browser, and version.

```true
no
```

**Comment by gkalpak** [comment]
You are right. It seems that the photo is only true if the `<app-no-encapsulation>` component is also present in the DOM outside `<app-shadow-dom-encapsulation>` component, because that causes the `<app-no-encapsulation>` global styles to be added at the top of `<app-shadow-dom-encapsulation>`'s ShadowRoot (before its own styles). But if `<app-no-encapsulation>` is only present inside the `<app-shadow-dom-encapsulation>` component, then its styles are added after (and thus override) the ones from `<app-shadow-dom-encapsulation>`.

I believe the docs should be updated to clarify that.

**Comment by AleksanderBodurri** [comment]
Duplicate https://github.com/angular/angular/issues/45462

**Comment by jessicajaniuk** [comment]
Closing as duplicate
