### ISSUE TITLE
formcontrolname attribute doesn't exist in FormArray controls

### ISSUE THREAD

**Issue by andreevsm** [angular/angular#45631]
### Which @angular/* package(s) are the source of the bug?

forms

### Is this a regression?

No

### Description

Hello guys! 👋🏻 
I'm not sure it's a bug, for me it's more a question

I'm trying to implement autoscrolling to a field with validation error. To do this, I'm looking for html elements by `'[formcontrolname].ng-invalid'`

For the form control we have `formcontrolname` attribute in `input` element:
<img width="649" alt="image" src="https://user-images.githubusercontent.com/26060516/163364022-495e98f5-f2f8-41f9-9f36-819c71e454d7.png">

But when the form control is under `formArrayName` we don't:
<img width="688" alt="image" src="https://user-images.githubusercontent.com/26060516/163364347-cb8f2f1f-1859-4e2f-9dbe-12f7618fac38.png">

So, is it fine or there should be `formcontrolname` attribute? 🤔 

### Please provide a link to a minimal reproduction of the bug

https://stackblitz.com/edit/angular-ivy-yxf1wp

### Please provide the environment you discovered this bug in (run `ng version`)

```true
Angular 13.2.0
```

### Anything else?

Sorry guys if it's not a big question. I'm just curious and wanna know if I need to find another solution 🤕

**Comment by AndrewKushnir** [comment]
@andreevsm I think you can use the [`@ViewChildren` decorator](https://angular.io/api/core/ViewChildren) instead of a DOM API query to get the list of all inputs, i.e. something like this:
```
  @ViewChildren(FormControlName, {read: ElementRef}) controlInputs: QueryList<ElementRef>;
```
and traverse the list and check which CSS class elements have:
```
controlInputs.forEach(inputRef => {
  if (inputRef.nativeElement.classList.contains('ng-invalid')) {
    // ...
  }
});
```
I will close this ticket as it doesn't fall into the bug report or feature request category. You can repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular` to get additional answers.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).

Thank you.
