### ISSUE TITLE
The globToRegex conversion results in unmatchable regular expression if string contains dollar sign ($)

### ISSUE THREAD

**Issue by jekru** [angular/angular#45737]
### Which @angular/* package(s) are the source of the bug?

service-worker

### Is this a regression?

No

### Description

If a URL in the service worker config contains a dollar sign ($), the globToRegex conversion is not working as expected and results in a regular expression that is unmatchable.

**globToRegex(glob: string, literalQuestionMark = false): string**  _(service-worker/config/src/glob.ts)_

Input: `https://example.com/$value`
Result: `https:\/\/example\.com\/$value`

The dollar sign in a regular expression matches the end-of-line. The resulted regular expression will be unmatchable because no string can contain `value` after the end of the string. The expected result is `https:\/\/example\.com\/\$value`, in other words: the dollar sign has to be escaped.

[Real world example](https://docs.microsoft.com/en-us/graph/api/profilephoto-get?view=graph-rest-1.0)

### Please provide a link to a minimal reproduction of the bug

https://stackblitz.com/edit/angular-sw-regex-issue

### Please provide the environment you discovered this bug in (run `ng version`)

```true
Angular CLI: 13.2.5
Node: 16.14.2
Package Manager: npm 8.7.0
OS: win32 x64

Angular: 13.2.4
... animations, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, router
... service-worker

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1302.5
@angular-devkit/build-angular   13.2.5
@angular-devkit/core            13.2.5
@angular-devkit/schematics      13.2.5
@angular/cli                    13.2.5
@schematics/angular             13.2.5
rxjs                            7.5.4
typescript                      4.5.5
```

**Comment by gkalpak** [comment]
This is a valid concern :+1:

Unfortunately, fixing it at this point would be a breaking change and I don't think it is worth it at this point. There are valid cases where one might need to use `^` and `$` with their special regex meaning. Besides that there are several special regex characters that we are not escaping, so fixing `$` but not others hardly helps.

A much better alternative would be to support proper regexes (instead of custom glob patterns) in `ngsw-config.json` (but that's a different discussion). BTW, this is being discussed in #45280.

In the meantime, how about we document the current behavior. This avoids the breaking change and better equips people to come up with the pattern they need. For example, if they need to match a literal `^` or `$`, one could escape it: `"https://example.com/\\$value"`

WDYT, @jekru?

**Comment by jekru** [comment]
> WDYT, @jekru?

Sounds good!
