### ISSUE TITLE
APP_BASE_HREF doesn't work with routes which starts with the same text part

### ISSUE THREAD

**Issue by Dolgovec** [angular/angular#45744]
### Which @angular/* package(s) are the source of the bug?

router

### Is this a regression?

No

### Description

If route starts with the same part as `APP_BASE_HREF`, the route becomes broken. E.g.:

app.module
```
{
      provide: APP_BASE_HREF,
      useValue: '/ru'
    }
```

app-routing
```
{
    path: 'rules',
    loadChildren: () => import('./pages/text-pages/rules/rules.module').then(m => m.RulesModule)
  },
```

And if you try to navigate `example.com/rules` you will get `example.com/ru/les`

Please, take a look at the stackblitz reproduction below.

### Please provide a link to a minimal reproduction of the bug

https://stackblitz.com/edit/angular-ivy-68vpxc?file=src%2Fapp%2Fapp-routing.module.ts

### Please provide the exception or error you saw

```true
ERROR
Error: Uncaught (in promise): Error: Cannot match any routes. URL Segment: 'les'
Error: Cannot match any routes. URL Segment: 'les'
```

**Comment by atscott** [comment]
This is being caused by the `Location` class, specifically the `stripBaseHref` logic: https://github.com/angular/angular/blob/50004c143ba9b1e041c7b30caf98f6582d3d26d4/packages/common/src/location/location.ts#L301-L303

Interestingly, `APP_BASE_HREF` is not used unless `RouterModule` or `UpgradeModule` is being used: https://github.com/angular/angular/blob/50004c143ba9b1e041c7b30caf98f6582d3d26d4/packages/common/src/location/location_strategy.ts#L48-L53

**Comment by atscott** [comment]
As a workaround, you can provide your own `Location` (copy-paste the existing implementation and adjust the `normalize`/`stripBaseHref`)

**Comment by Dolgovec** [comment]
@atscott Thx for your answer and explanation! Workaround works fine for me
