### ISSUE TITLE
loadComponent in new standalone apis doesn't load component on page refresh

### ISSUE THREAD

**Issue by eneajaho** [angular/angular#45803]
### Which @angular/* package(s) are the source of the bug?

router

### Is this a regression?

No

### Description

Hello, 
I've been tinkering with the new standalone apis, and I encountered a bug with the router.

Bug: 
In the reproduction link I've attached, if I navigate to a lazy route `/lazy1` and then refresh the page, after the page refreshes, the component is not loaded. For it to load I need to click again on the links that sends you to the path. 

Stackblitz install steps: 
```
cd testv14
yarn
ng serve
```

### Please provide a link to a minimal reproduction of the bug

https://stackblitz.com/edit/node-35swv3

### Please provide the exception or error you saw

```true
None.
```

### Please provide the environment you discovered this bug in (run `ng version`)

```true
Package Manager: npm 7.17.0 
OS: linux x64

Angular: 14.0.0-next.15
... animations, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1400.0-next.12
@angular-devkit/build-angular   14.0.0-next.12
@angular-devkit/core            14.0.0-next.12
@angular-devkit/schematics      14.0.0-next.12
@angular/cli                    14.0.0-next.12
@schematics/angular             14.0.0-next.12
rxjs                            7.5.5
typescript                      4.6.3
```

### Anything else?

The new apis are 🔥.  Thank you.

**Comment by atscott** [comment]
So this is actually because the initial navigation is not happening. 

The initial navigation is an `APP_INITIALIZER` which needs to be provided in the `bootstrapApplication` call. I think you suspected that was the correct place for the `RouterModule.forRoot` call based on the comment in your `main.ts` but it wasn't working because of the `Uncaught Error: Invalid provider for the NgModule 'undefined'`.

If you change 
```
  {
    providers: [importProvidersFrom([RouterModule.forRoot(routes)])],
  }
``` 
to
```
  {
    providers: [...importProvidersFrom([RouterModule.forRoot(routes)])],
  }
```
then everything works as expected. @AndrewKushnir fixed this issue in https://github.com/angular/angular/pull/45789 but it hasn't made it into a release yet.

**Comment by eneajaho** [comment]
Thanks, it worked correct with the spread syntax. Closing the issue.
