### ISSUE TITLE
ko-KR - Korean translation for AM/PM in data pipe

### ISSUE THREAD

**Issue by m-wasiak** [angular/angular#45813]
### Which @angular/* package(s) are the source of the bug?

localize

### Is this a regression?

No

### Description

Hi, 
ko-KR localize has wrong translations for AM/PM key. If you could change 
'AM' -> '오전'
'PM'-> '오후' 
Thank you!

### Please provide a link to a minimal reproduction of the bug

https://ibb.co/Qks33j5

**Comment by gkalpak** [comment]
The locale files used by Angular are generated from data downloaded from the [CLDR project][1]. If the CLDR data is incorrect, then you should submit an issue there. (Once the data is fixed there, the Angular locale files will be updated the next time we update the version of CLDR we use to generate them.)

Closing, since it is not actionable on our side.

[1]: https://cldr.unicode.org/
