### ISSUE TITLE
Wrong `date` pipe documentation

### ISSUE THREAD

**Issue by avi12** [angular/angular#45866]
### Description

The pipe also accepts `[number] | [number, number] | [number, number, number]` as seen [here](https://codesandbox.io/s/angular-11-playground-forked-yhcyki?file=/src/app/app.component.html)

### What is the affected URL?

https://github.com/angular/angular/blob/3a60063a54d850c50ce962a8a39ce01cfee71398/packages/common/src/pipes/date_pipe.ts

### Please provide the expected behavior vs the actual behavior you encountered

Mention the other accepted formats:
```ts
[number] // year
```
```ts
[number, number] // year, month
```
```ts
[number, number, number] // year, month, day
```

**Comment by JoostK** [comment]
An array is _not_ supported; it only happens to work because [the `Date` constructor](https://github.com/angular/angular/blob/3a60063a54d850c50ce962a8a39ce01cfee71398/packages/common/src/i18n/format_date.ts#L791) interprets an array in a certain way but the pipe's signature is leading here; you'll get template type check errors (at least when using `strictTemplates`) for invalid inputs.
