### ISSUE TITLE
FormBuilder#group incorrectly infers type if union type is passed in

### ISSUE THREAD

**Issue by bgotink** [angular/angular#45912]
### Which @angular/* package(s) are the source of the bug?

forms

### Is this a regression?

No

### Description

The `group` function expands passed-in union types, which it shouldn't do:

```ts
const groupControl = formBuilder.group({
    value: '' as string | number,
});

// Expected type:
//    FormControl<string | number>
// Actual type:
//    FormControl<string> | FormControl<number>
const valueControl = group.controls.value;
```

<img width="412" alt="image" src="https://user-images.githubusercontent.com/821510/167164420-43821d55-2c40-4ef6-95b0-3f6c543c3c91.png">

### Please provide a link to a minimal reproduction of the bug

https://stackblitz.com/edit/angular-ivy-ao4sne?file=src%2Fapp%2Fapp.component.ts

### Please provide the exception or error you saw

```true
n/a
```

### Please provide the environment you discovered this bug in (run `ng version`)

```true
Unable to run ng version in stackblitz

Happens in 14.0.0-next.16
```

### Anything else?

This is caused by the type mapping in 

https://github.com/angular/angular/blob/3f3812e20ab3d3d79cb6bb81a6769fe913c8aea1/packages/forms/src/form_builder.ts#L45-L62

Typescript expands the type union in the type map, because different parts of the type union might end up in different branches of the type map.
Here's a minimal example ([playground](https://www.typescriptlang.org/play?#code/C4TwDgpgBAkgzgOQK4FsBGEBOAeAKgPigF4pcoIAPYCAOwBM4obUNMoB+KYTJaALigAzAIYAbOBADcAKGkB6OULETpoSKQhxgARmJRYiFlmxbMASxoBzfDPmLuvVeGi5NwAEx74ydMea-MG1kFKDQAezDRCGEaJ3VXLQBmL0MAk24LSygAHyYjQMkgA))

```ts
type IsNumber<T> = T extends number ? true : false;

// false
type Test1 =  IsNumber<string>;

// true
type Test2 = IsNumber<number>;

// boolean
type Test3 = IsNumber<string | number>;
```

This can be solved by wrapping the type in the map with `[]` ([playground](https://www.typescriptlang.org/play?#code/C4TwDgpgBAkgzgUQB4EMDGwA2IByBXAWwCMIAnAHgBUA+KAXigG1KBdKCJYCAOwBM4m3QiVJsA-FGCk80AFxQAZikxwIAbgBQGgPTbFy1RtCQolCHGABGelFiJUGbPmJlyF0gEtuAc2qadelIyRuDQZhYATDbwyOhYuMKuQi6kflq6+ioQISbhwADM0fZxTokU7l7eUAA+UMkifkA)):

```ts
type IsExactlyNumber<T> = [T] extends [number] ? true : false;

// false
type Test1 =  IsExactlyNumber<string>;

// true
type Test2 = IsExactlyNumber<number>;

// false
type Test3 = IsExactlyNumber<string | number>;
```

**Comment by dylhunn** [comment]
TypeScript behaves this way in general due to [some rather complicated details about distributive conditional types](https://www.typescriptlang.org/docs/handbook/2/conditional-types.html).

It's surprising that we can force a different behavior using the `[]` trick, and it very much seems like an open question whether it would be preferable. Could you describe in more depth why you prefer to have a union of values instead of a union of controls? Note that in many practical cases, it should not matter much (e.g. `group.value` is the same in both cases).

**Comment by dylhunn** [comment]
I believe #45942 should fix the problem. Thanks for catching this. 

Typescript's support for unifying distributive types is shockingly good. Even with the previous bug, this still compiled:

```
const c = fb.group({foo: 'bar' as string | number});
let newCtrl: FormControl<string|number> = c.controls.foo;
```

because Typescript will perform the distribution when assigning to `FormControl<string|number>`. Hence, this is actually really hard to catch in action causing problems. The cases do exist though:

```
// fc gets an inferred distributive union type `FormControl<string> | FormControl<number>`
let fc = c.controls.foo;
// Error: Type 'FormControl<string | number>' is not assignable to type 'FormControl<string> | FormControl<number>'.
fc = new FormControl<string|number>('', {initialValueIsDefault: true});
```
