### ISSUE TITLE
Lazy Load Guards

### ISSUE THREAD

**Issue by hisham** [angular/angular#45981]
### Which @angular/* package(s) are relevant/related to the feature request?

router

### Description

Angular supports lazy loaded modules, but if you have a guard for that route, the guard is not lazy loaded but bundled in the parent module. 

The problem is the guard itself can have bloated code/libraries, so why bundle the guard code in the main app if it's not run until the user clicks on a route? 

I am implementing an auth guard, and using aws amplify-js for it, and their method that checks if user is logged in adds 333.82kb to the main bundle - see https://github.com/aws-amplify/amplify-js/issues/9817#issuecomment-1123013402

### Proposed solution

Guards should be lazily loaded. 

### Alternatives considered

Add the canActivate setting in the child route paths and not the parent route path.

**Comment by meriturva** [comment]
Why don't you add the guard to the local/lazy router module?

**Comment by hisham** [comment]
Yes that's what I'm doing. Any disadvantage of that though?

**Comment by atscott** [comment]
Guards are asynchronous so you can load whatever code you need lazily in the `canActivate` itself.

Another option would be to create a parent route with the path you want and then put the route with `providers` inside a `loadChildren` with an empty path.

https://stackblitz.com/edit/angular-ivy-udcr8u?file=src%2Fapp%2Fapp.module.ts,package.json,src%2Fapp%2Flazy.ts,src%2Fapp%2Foption2.ts,src%2Fapp%2Fapp.component.html,src%2Fapp%2Fhello.component.ts

Closing since this can be achieved with existing APIs

**Comment by hisham** [comment]
Thanks @atscott & @meriturva. I ended up using a dynamic import like what @atscott suggested and it is working so far! 

My auth code was encapsulated in an angular service, so I ended up lazily loading and injecting this service like so: 

```
    const { MyAuth } = await import(
      'projects/shared/auth/my-auth.service'
    );
    const myAuthService = this.injector.get(MyAuthService);
    await myAuthService.getCurrentAuthenticatedUser()...etc...
```
