### ISSUE TITLE
ENVIRONMENT_INITIALIZER is eagerly loaded

### ISSUE THREAD

**Issue by ArielGueta** [angular/angular#45988]
### Which @angular/* package(s) are the source of the bug?

core

### Is this a regression?

No

### Description

When using the ENVIRONMENT_INITIALIZER token in a lazy loaded component, the expected behaviour is that it should run the provider only when the path matches. 

```ts
    {
    path: 'posts',
    loadComponent: () => import('./posts.component').then(m => m.PostsComponent),
    children: [
      {
        path: ':id',
        loadComponent: () => import('./post.component').then(m => m.PostComponent),
        providers: [{
          provide: ENVIRONMENT_INITIALIZER,
          multi: true,
          useValue() {
            console.log('loaded')
          }
        }]
      }
    ]
```

Why in this case, I see the log when navigate to `posts`. I should see it only when navigating to `posts/:id`.

### Please provide the environment you discovered this bug in (run `ng version`)

```true
14.0.0-next.16
```

**Comment by atscott** [comment]
Right, so the current implementation creates the `EnvironmentInjector` as soon as the route _attempts_ a match. There's no technical reason we can't wait until after a match is confirmed. I'll work on making this change today.

The reason `':id'` injector is created even when just navigating to `posts` is that the children as still checked since they might contain an empty `path`.

**Comment by ArielGueta** [comment]
Thanks for the quick fix.
