### ISSUE TITLE
Feature: hot reload support?

### ISSUE THREAD

**Issue by EricTsangX** [angular/angular#4606]
Hey guys, right now I am playing with react and webpack, I found the hot-reload feature is extremely powerful while developing apps. I can edit HTML DOM and preserve js variables. 
Does angular2 architecture support it now? If not, I hope angular2 can adapt that feature.

**Comment by mgechev** [comment]
I believe hot reloading with Angular 2 is doable, however, I this issue seems out of the scope of this repository. May be we can discuss this in gitter?

**Comment by pkozlowski-opensource** [comment]
Yeh, there are many parts of the workflow that we didn't quite figure out yet, "hot reload" being one of them. We do understand the importance of the kicking-ass workflow and there is a lot of work going on into it. At the moment our priority is to figure out proper packagining / bundling story, though.

I'm going to close this one since this is not immediately actionable, but this is on our radar for sure.
