### ISSUE TITLE
Support the Navigation API

### ISSUE THREAD

**Issue by LifeIsStrange** [angular/angular#46136]
### Which @angular/* package(s) are relevant/related to the feature request?

router

### What is the new or updated feature that you are suggesting?

Chromium 102 has been released stable, which means that Chrome, Edge, Opera, Brave, Vivaldi, etc and Electron supports the Navigation API
https://chromestatus.com/feature/6232287446302720
The Navigation API is the successor of the History API and is better suited for SPAs.
Therefore, routers should allow to target and leverage it.

### Why should this feature be included?

> The existing window.history API is hard to deal with in practice, especially for single-page applications. In the best case, developers can work around this with various hacks. In the worst case, it causes user-facing pain in the form of lost state and broken back buttons, or the inability to achieve the desired navigation flow for a web app.

### Proposed solution

see the spec https://chromestatus.com/feature/6232287446302720

### Alternatives considered

codemning users to stay on the History API, with all its limitations.

**Comment by atscott** [comment]
We're definitely aware of this and have been involved in the design. "Supporting the Navigation API" isn't something we can just do though. We're looking at ways to slowly start integrating with it. Because browser support is limited at the moment, those opportunities are less abundant right now. There's no polyfill and we need to ensure that the experience between browsers is consistent enough that there aren't surprising bugs/differences in behavior when interacting with a site on different browsers.

 That said, as we look at a more complete re-architecture of the Router, we'll be keeping this in mind (for example, making the interaction with the browser history something that can be controlled completely by developers).

**Comment by LifeIsStrange** [comment]
Note that many Electron apps do not have the web-interop concern and could be from now on (well when the next electron version will be released). Providing an optin flags should be doable and I'm not advocating for making it the default behaviour, unless polyfills/web support if widespread enough.
