### ISSUE TITLE
side effects modules not included in bundle

### ISSUE THREAD

**Issue by vankop** [angular/angular#46219]
# 🐞 Bug report

full description https://github.com/webpack/webpack/issues/15882

I'm not much familiar with angular, so description could be unclear.. In case:

`app.component.ts`
```ts
import { AfterViewInit, Component } from '@angular/core';
import { FormControl, FormGroup } from '@angular/forms';

@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.css'],
})
export class AppComponent implements AfterViewInit {}
```

`app.module.ts`
```ts
import { NgModule } from '@angular/core';
import { ReactiveFormsModule } from '@angular/forms';
import { BrowserModule } from '@angular/platform-browser';

import { AppComponent } from './app.component';
import { CustomControlStatusDirective } from './utils/forms'; // here is reexport with side effect ( sideEffects flag is set to true )

@NgModule({
  declarations: [AppComponent, CustomControlStatusDirective],
  imports: [BrowserModule, ReactiveFormsModule],
  providers: [],
  bootstrap: [AppComponent],
})
export class AppModule {}
```

results of loaders run for `app.module`
```js
import { ReactiveFormsModule } from '@angular/forms';
import { BrowserModule } from '@angular/platform-browser';
import { AppComponent } from './app.component';
import * as i0 from "@angular/core";
// no CustomControlStatusDirective import
```

and `app.component` looks like
```js
import { FormControl, FormGroup } from '@angular/forms';
import * as i0 from "@angular/core";
import * as i1 from "@angular/forms";
import * as i2 from "./utils/forms/custom-control-status.directive";
// import of CustomControlStatusDirective. Note! original import had side effect!!!
```

so when bundle this side effects modules will not be included

### Command (mark with an `x`)

- [ ] new
- [x] build
- [ ] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] extract-i18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc

### Is this a regression?

not

### Description

full description https://github.com/webpack/webpack/issues/15882

## 🔬 Minimal Reproduction

https://github.com/amitbeck/ng-webpack-sideEffects-repro

## 🔥 Exception or Error

side effects code not included in bundle

</code></pre>

## 🌍 Your Environment

```
Node: 16.13.2
Package Manager: npm 8.1.2
OS: darwin arm64

Angular: 13.2.7
... animations, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1303.7
@angular-devkit/build-angular   13.2.6
@angular-devkit/core            13.3.7
@angular-devkit/schematics      13.2.6
@angular/cli                    13.2.6
@schematics/angular             13.2.6
rxjs                            7.5.5
typescript                      4.5.5
```

**Anything else relevant?**

This should be solved by respecting side effects or better just to preserve import module. webpack@5 can easily handle reexport by itself.

**Comment by alxhub** [comment]
In general, relying on destructured/namespace imports to run side effects isn't a great idea. Angular _does_ change the import to a direct deep import when it expands the component's dependencies, because we want to produce the most specific import possible. We _could_ reuse the existing import, but this would risk producing cycles (and triggering our cycle deoptimization) when it's not really necessary, and I don't think the benefits are worth this tradeoff.

The downstream tooling does end up eliding the import in the NgModule file, as it's no longer "used". The right way to mark an import as side-effectful (and prevent such elision) is to use a side-effectful import:

```typescript
import './utils/forms';
```

I believe all of our tooling understands this import as side-effectful and will leave it alone.

Note that unused import elision has nothing to do with the `sideEffects` flag in `package.json`, which concerns whether top-level functions imported _and actually used_ from that module should be treated as side-effectful.

**Comment by alxhub** [comment]
@vankop yes, but this import:
```typescript
import { CustomControlStatusDirective } from './utils/forms';
```
is a destructuring import, not a side-effectful import. Almost every bundler/optimizer in the ecosystem assumes such imports can be removed if the imported symbol(s) are not referenced.
