### ISSUE TITLE
feat(router): links without a leading slash

### ISSUE THREAD

**Issue by btford** [angular/angular#4623]
@matsko and @IgorMinar and I talked about this in the past.

Currently, we require all `router-link`s to have their first element to start with either `/` or with `./`:

```
<a [router-link]="[ '/MyCmp' ]"></a>
```

For apps with one level of routing, the distinction between routing to a child and routing to a sibling is irrelevant. It'd be nice to omit the leading `/` or `./`:

```
<a [router-link]="[ 'MyCmp' ]"></a>
```

We should change the behavior of generating the instruction (and subsequent link) to match a link DSL array with no leading `./` or `/` as follows:

For `[router-link]="[ 'FooCmp' ]"`
1. Look for a child route named `FooCmp`
2. Look for a sibling route named `FooCmp`
3. If both exist, throw an error explaining the the developer must provide a leading `/` or `./` so that the link is unambiguous.
4. Otherwise, if one exists, use the resolved instruction.
5. If neither route matches, we throw an error telling the developer so.

This will help address some of the developer confusion WRT routes that's come up in our hackathons.

**Comment by PascalPrecht** [comment]
The following question might just simply stupid but I'll give it a try:

If the leading slash is going to be "optional" for one level routing, and we can just go with `[router-link]="['Cmp']"` couldn't we make a shorthand syntax for it, which is a bit more intuitive and looks sth. like this `[router-link]="Cmp"`.

I might totally miss something here, but maybe this simplifies some use cases. Otherwise, we'd need to explain upfront that there's this DSL that is way more powerful than what we actually need in this particular case, and that's why we have to stick with the brackets now.

Again, I'm just thinking out loud, wouldn't be surprised if there are 10 reasons why this can't work.

**Comment by btford** [comment]
The RHS of the binding needs to be a JS literal, so that wouldn't work.

We shouldn't get too tricky with the sugar until we have a proper DSL.

Note that this does not make `/` optional, but rather adds a new option of "link without leading slash" that has its own distinct semantics.

**Comment by PascalPrecht** [comment]
> Note that this does not make / optional, but rather adds a new option of "link without leading slash" that has its own distinct semantics.

Ah of course! Hey thanks for clarifying!
