### ISSUE TITLE
Currency pipe formats wrong tg locale

### ISSUE THREAD

**Issue by Ilkhom-S** [angular/angular#46254]
### Which @angular/* package(s) are the source of the bug?

common

### Is this a regression?

Yes

### Description

When use tg (Tajikistan) locale currency symbol should be 'сомонӣ' and number formatting with . for fraction part.
Example: 
Should be: 
11 111.98 сомонӣ

I get : 
11 111,98 сом.

Also in russian and english locale symbol should be 'сомони' and 'somoni' from right side. But I get from left side. 

Russian locale currency TJS should be: 
11 111.98 сомони
I get: 

11 111,98 TJS   (should be dot not comma)

English locale should be : 
11,111.98 somoni

But I get: 
TJS11,111.98

### Please provide the environment you discovered this bug in (run `ng version`)

```true
Angular CLI: 13.3.7
Node: 16.15.0
Package Manager: yarn 1.22.18
OS: win32 x64

Angular: 13.3.10
... animations, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, platform-server
... router, service-worker

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1303.7
@angular-devkit/build-angular   13.3.7
@angular-devkit/core            13.3.7
@angular-devkit/schematics      13.3.7
@angular/cdk                    13.3.8
@angular/cli                    13.3.7
@schematics/angular             13.3.7
rxjs                            6.6.7
typescript                      4.6.3
```

**Comment by jessicajaniuk** [comment]
We recently updated to the CLDR v41 release, and it's likely this is an upstream bug with the CLDR itself. @devversion does this look familiar to you?

**Comment by devversion** [comment]
Seems like you are still on Angular v13. We just updated to CLDR 41 in v14. We updated to CLDR 39 in v13 IIRC though. All the formatting seems correct according to the specification in CLDR/Unicode:

* https://github.com/unicode-org/cldr/blob/7a8465f619ab03ec9892696c269f6fddc0662ef3/common/main/tg.xml#L2200-L2203
* https://github.com/unicode-org/cldr/blob/7a8465f619ab03ec9892696c269f6fddc0662ef3/common/main/tg.xml#L2064-L2065

Angular fully leverages this data for the date, currency formatting. If you think the rules/data here is incorrect, please report this to CLDR/Unicode as we don't have control over this and also cannot easily tell what's the correct formatting here.

cc. @gkalpak (since you also know CLDR)

**Comment by Ilkhom-S** [comment]
Thanks for your answer, It seems problem relies on repo you using.  I will write there.

**Comment by devversion** [comment]
Thank you @Ilkhom-S
