### ISSUE TITLE
Passing data into "router-outlet" child components

### ISSUE THREAD

**Issue by cesco69** [angular/angular#46283]
### Which @angular/* package(s) are relevant/related to the feature request?

core

### Description

I want a simple way to pass data into "router-outlet" child components

### Proposed solution

```ts
@Component({
  selector : 'main',
  template : `<router-outlet [data]="data"></router-outlet>`
})
export class MainComponent {
    data = 'test';
}
```

Retrive the data into the routed component

```ts
import {ROUTER_DATA, Component, Inject } from '@angular/core';

@Component({
  selector: 'child',
  template: `{{data}}`
})
export class ChildComponent {
  constructor(@Inject(ROUTER_DATA) public data: any) { }
}
```

### Alternatives considered

Nothing

**Comment by K-RutviK-K** [comment]
I don't want to fire multiple API calls. is there any Alternative solution?

**Comment by yasammez** [comment]
@K-RutviK-K there are two I can think of.

1. Have two selectors: one which gets you the loading state and another which gets you the result and undefined when the result isn't available (or null, it won't matter). Then do something in the order of:

```
// Outer component
<ng-container *ngIf="(loading$ | async) === 'FINISHED'>
  <router-outlet></router-outlet>
</ng-container>
```

This way your inner components can just use the second selector and not deal with the "loading hasn't finished yet" case at all, since in that case they wouldn't even be mounted.

This has the drawback that taking one of those components and putting it somewhere else in the App might break things in rather ugly ways. This is why I went for the next variant.

2. Only have one selector, that gives you a sum type `type MyState = { state: 'LOADING' } | { state: 'FINISHED' } & MyData` (add additional states like `ERROR`, `UNINIT` or even a progress indicator as needed). Then write a small outlet component (basically implement this feature for your one type).

```
@Component({
  selector: 'app-outlet',
  template: `
    <div *ngIf="(state$ | async).state === 'LOADING'>Loading&nbsp;&hellip;</div>
   <!-- fancy spinners, error messages, etc. -->
    <ng-container *ngTemplateOutlet="templateRef; context: {$implicit: state.data}</ng-container>
  `
})
export class OutletComponent {

  state$;

  @ContentChild(TemplateRef)
  templateRef: TemplateRef<any>;

  constructor(private store: Store<MyState>) {
    store.dispatch(LoadMyData()); // The corresponding effect takes care of caching and/or not duplicating requests with the rxjs switchMap operator
    this.state$ = store.select(selectMyState);
  }
}
```

You can then use this component as a guard whenever you need the data and don't want to care about how it gets there or what to do when you don't get it by using the might of ngTemplateOutlet:

```
<app-outlet>
  <ng-template let-data> <!-- binds the $implicit object from the context above to a variable named data -->
    <app-my-view-component [data]="data"></app-my-view-component> <!-- Use data and sleep well, knowing it will always be there from now on -->
  </ng-template>
</app-outlet>
```

If you need more than one item passed down into your view components, you can also do that with the context object of ngTemplateOutlet but you lose that neat "$implicit" which just allows you to bind the "default" variable.

**Comment by mdarif** [comment]
What's the latest on the feature request?
