### ISSUE TITLE
Angular 13 - yyyy/MMM/dd Date format - not working for Sepetember month in en-GB LOCALE_ID

### ISSUE THREAD

**Issue by wessisaac** [angular/angular#46293]
### Which @angular/* package(s) are the source of the bug?

core, localize

### Is this a regression?

No

### Description

In angular 13, yyyy/MMM/dd - Date format - not working for September month in en-GB LOCALE_ID

In en-GB LOCALE_ID culture, yyyy/MMM/dd - Date format is not working for September month. Other than September month, it is working properly  in all dates.

### Please provide the exception or error you saw

```true
In yyyy/MMM/dd dateformat, for September month, the date will be generated as 2022/Sept/02
```

**Comment by JoostK** [comment]
This is expected for the en-GB locale, where September is abbreviated as _Sept_ instead of _Sep_ (if that is what the issue is about, it is unclear what your expected behavior is here). This data is sourced from [the CLDR dataset](https://github.com/unicode-org/cldr/blob/7a8465f619ab03ec9892696c269f6fddc0662ef3/common/main/en_GB.xml#L1907).

**Comment by wessisaac** [comment]
Hi JoostK, for example, If I am passing the date, **_2022/Sept/15_** as input parameter to my API service, it is failed to convert as date.  Like the same way if I pass the date **_2022/Sep/15_** as input parameter to my API service it works properly.
