### ISSUE TITLE
Update Docs for Typed FormArray

### ISSUE THREAD

**Issue by arambazamba** [angular/angular#46337]
### Description

I think the samples in the docs for typed forms are too simple. For example I cannot find docs on how to type a FormArray that containers two FormControls lets say name and age. What would that look like?

  public skillForm : FormGroup<{
    person: FormControl<string | null>;
    children: FormArray<????>
  }>;

### What is the affected URL?

https://angular.io/api/forms/FormArray

**Comment by dylhunn** [comment]
> I cannot find docs on how to type a FormArray that containers two FormControls lets say name and age

This is not well-supported by typed forms. Imagine what such a type would look like: perhaps `FormArray<FormControl<string|number>>`? This is absolutely possible with today's API, and you can do it if you want, but the types you get are just not very useful. In particular, adding controls will be a pain, due to the way invariance works -- all child controls will need to support `string|number` values, because they could be read out of the array later. Thus, I don't want to suggest that this is supported in the docs.

In general, you should use `FormArray` for *homogenous* arrays, and `UntypedFormArray` for *heterogenous* arrays.
