### ISSUE TITLE
Missing? documentation for localize in angular libraries.

### ISSUE THREAD

**Issue by eestein** [angular/angular#46339]
### Which @angular/* package(s) are the source of the bug?

localize

### Is this a regression?

No

### Description

I've read a lot of articles, including some issues here on GitHub (like this one https://github.com/angular/angular/issues/29536 ) regarding using `@angular/localize` with libraries. But I couldn't find official documentation regarding this process, is it available?

Currently I have a few questions:

- How do I let the library know which language is being used? Maybe something like `MyLib.forRoot({defaultLang})`? What if the language changes, observable?
- I have a main project (no worksapce) with 2 libraries loaded as submodules. That means they don't have their `angular.json` file. How would it work for that case? How do I define the translation files being used?

### Please provide the exception or error you saw

```true
No error, just can't find the documentation for my specific case.
```

### Please provide the environment you discovered this bug in (run `ng version`)

```true
Angular CLI: 14.0.1
Node: 14.17.0
Package Manager: npm 6.14.13
OS: darwin x64

Angular: 14.0.1
... animations, cli, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1400.1
@angular-devkit/build-angular   14.0.1
@angular-devkit/core            14.0.1
@angular-devkit/schematics      14.0.1
@schematics/angular             14.0.1
ng-packagr                      14.0.2
rxjs                            7.5.5
typescript                      4.7.3
```

**Comment by alan-agius4** [comment]
Hi @eestein, 

This is related to https://github.com/angular/angular/issues/36757 and https://github.com/angular/angular-cli/issues/17140. 

> How do I let the library know which language is being used? Maybe something like `MyLib.forRoot({defaultLang})`?

Translations are configured at application level and a library doesn't need any special handling. This is because translations are inlined in the bundle during the application build. 

> What if the language changes, observable

The application will be re-bootstrapped since in this case the there would be a page reload.

> I have a main project (no worksapce) with 2 libraries loaded as submodules. That means they don't have their angular.json file. How would it work for that case? How do I define the translation files being used?

Typically translations are configured by the consuming application. 

Closing as this is being tracked in the above mentioned issues.
