### ISSUE TITLE
JSON Pipe fails to display properties of type MAP

### ISSUE THREAD

**Issue by kishor-p** [angular/angular#46353]
### Which @angular/* package(s) are the source of the bug?

common

### Is this a regression?

No

### Description

**GIVEN:**
An Object with a property of type MAP.

**WHEN:**
Displayed in HTML using JSON pipe

**THEN:**
Values of property of type MAP does not show up

![image](https://user-images.githubusercontent.com/14179249/173430696-abbeaff2-2381-4eb2-9bc3-447ebc0d49e4.png)

### Please provide a link to a minimal reproduction of the bug

https://stackblitz.com/edit/angular-ivy-jbvazd?file=src/app/app.component.html

### Please provide the exception or error you saw

```true
No Exception
```

**Comment by jessicajaniuk** [comment]
Thanks for reporting this, @kishor-p. This is actually not an issue with Angular or the Angular JSON pipe, but is due to the native behavior of JavaScript's `JSON.stringify` with native Maps. If you update your stackblitz, you can see that behavior. The Map exists just fine, but JSON.stringify essentially drops that value and returns an empty object. There's a bunch of stack overflow issues of Maps and JSON and stringify. There's a few potential solutions for you here. Definitely check out stack overflow for your options.
