### ISSUE TITLE
Missing docs on expected service worker behavior

### ISSUE THREAD

**Issue by andreaslarssen** [angular/angular#46445]
### Description

I have an Angular PWA app, and I run a PUT request in my app. It receives a 504 response (from the service worker) when not online. I'm trying to figure out what's causing this, and if that's expected behavior from the service worker, but I can't find anything in the docs about this.

[This](https://angular.io/guide/service-worker-config#urls) documentation says:

> A list of URL patterns. URLs that match these patterns are cached according to this data group's policy. Only non-mutating requests (GET and HEAD) are cached.

This leads me to think that a PUT request will be relayed through the service worker to the API (but not cached), and that the response also will on the way back.

What really happens is that the service worker responds with a 504 Gateway Timeout. If I bypass the service worker, I get a status code 0 (which is what I was expecting because I read it somewhere in the Angular docs I think, though I can't find it again).

Can anyone shed some light on how one is supposed to handle detecting that the app is missing connection?
- Are you supposed to bypass the service worker to be able to detect this?
- If not, is a 504 response code from the service worker expected for a PUT method when offline? Or am I missing something?
- Is 504 a better way of detecting network issues than 0 (as it seems like code 0 is a generic error code)?

It would be great if this behavior would be documented on the referred page. If this isn't related to the Angular implementation of the service worker, but more a question about how service workers are supposed to work in general, let me know. I couldn't find any good resources on the subject.

### What is the affected URL?

https://angular.io/guide/service-worker-config

**Comment by andreaslarssen** [comment]
@UchihaYuki @gkalpak @jekru @alxhub Do you guys have any insights to this?

**Comment by gkalpak** [comment]
@andreaslarssen, the 504 status code does indeed come [from the Angular ServiceWorker][1].
The [504 Gateway Timeout][2] HTTP status code essentially indicates that the upstream server could not be reached (i.e. it is what you would get if the server was down).

This way the SW emulates not being able to connect to the server (regardless if it is due to the client being offline or the server being down). Theoretically, this should not affect your app (i.e. the app should be able to handle problems on the server side and respond accordingly). That said, the behavior you see with the ServiceWorker activated is slightly different when offline compared to when there is not ServiceWorker. In the latter case, the HTTP request would be rejected with a `TypeError` instead of completing with 5xx status. (But, again, this should not cause problems in the app.)

If you want to specifically detect when the client is online/offline, you can use the [navigator.onLine][3] (and/or the `online`/`offline` Window events).

Does the above explanation make sense?

##
BTW, I am not sure what you mean by the 0 status code and what part of the docs it is mentioned. It would help if you could provide more details.

[1]: https://github.com/angular/angular/blob/bdf57ab14a310f6e6811d9f990cbbd3612bde538/packages/service-worker/worker/src/assets.ts#L491
[2]: https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/504
[3]: https://developer.mozilla.org/en-US/docs/Web/API/Navigator/onLine

**Comment by andreaslarssen** [comment]
@gkalpak Thanks. 

What I want to do is to prompt the user with a message saying that they're not online when they're trying to run a PUT request.

When running through SW:

```
this.httpClient.put('some/resource', {data: 'data'}).pipe(
  catchError((error: any) => {
    console.log(error.status); // 504
   }),
).subscribe();
```

When bypassing SW:
```
this.httpClient.put('some/resource', {data: 'data'}, {headers: new HttpHeaders().set('ngsw-bypass', 'true')}).pipe(
  catchError((error: any) => {
    console.log(error.status); // 0
   }),
).subscribe();
```
So when I bypass the SW I get an opaque response, yielding status code 0.

As I mentioned, I can't find it again, but I was so certain I read somewhere in the Angular docs that checking for opaque response status code (0) was the way to go to see if the request failed due to missing connection. But I guess I've dreamed it.  

In conclusion I guess there's no real way of knowing if the request failed because of the user being offline, but the 504 is as close as you'll get. I ended up using that, and if that means that I report to the user that they're offline one too many times (when in fact something else is causing the 504), that's just something I think I have to live with for my app.

I have looked in to `navigator.onLine` (and the `window` event), but it's not reliable as to whether the user is online or not. Also, I want to determine if the request failed due to missing connection, and that's not something I could do 100% even if 
`navigator.onLine` was reliable.

As for the issue, it would be good to have some documentation around good / best practice when it comes to handling mutating requests (as they're proxied through the SW though not cached).

**Comment by bob-watson** [comment]
Assigned P2 doc update as this seems like useful information and an easy thing to add.

**Comment by andreaslarssen** [comment]
@bob-watson I don't think we need to relate it to the actual feedback text, and also not include anything about `window.navigator.onLine`.

I think something like this would help me a lot when I first started reading about the SW:

## Handling errors when the server can't be reached

All mutating requests proxies through the service worker (unless the `ngsw-bypass` request header / query parameter is added). 

When a server can't be reached and the request times out, the service worker returns a [504 Gateway Timeout](https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/504) status. Because this can happen either when the client _or_ the server is offline, there's no way of detecting through the service worker that the request failed due to the client being disconnected.

**Comment by gkalpak** [comment]
Thx for summarizing it, @bob-watson.
I agree with @andreaslarssen, that getting to specific and mentioning `navigator.onLine` are out of scope for the Angular docs.

##
> As for the issue, it would be good to have some documentation around good / best practice when it comes to handling mutating requests (as they're proxied through the SW though not cached).

I am not sure I understand this suggestion, @andreaslarssen. Could you please clarify a little more.
For example, why are mutating requests special? Don't the same practices apply to all requests?

> All mutating requests proxies through the service worker

Again, I am not sure it is a good idea to mention mutating requests specifically. In general, this is how Service Workers work. All requests are passed through the SW. (The SW can decide what to do with them, but all requests will go through it.)

> there's no way of detecting through the service worker that the request failed due to the client being disconnected.

This also confuses me. AFAICT, this is not specific to the SW. There is not 100% reliable way to tell if you are online or offline anyway. It is true that the SW may alter the status code that you will get back, but not in a way that could not happen without the SW (under certain circumstances).

**Comment by andreaslarssen** [comment]
@gkalpak 
There's nothing special about mutating requests, really. It's just that the docs say:
> Only non-mutating requests (GET and HEAD) are cached.

If you do not have experience with SW from before (like me), there's nothing in the docs (as far as I can see) that indicates that all requests are being passed through the SW (why should they?). So rather than saying that mutating requests (also) are passed through, maybe just mention that _all_ the requests are passed through the SW?

That info alone is not valuable, but like you say, the SW may alter the status code that you will get back, and that's what's really nice to know. And to start to understand that, you need to understand that also POST, PUT etc are passed trough the SW.

Now that you mention it, it would be great to have a few words about why and how the SW alters the request/response. That's really what it all boils down to. 

When it comes to the "detect if the app is offline", my assumption was that you could (somehow), cause I thought that the SW would have to in order to work. How else would it know when to serve the cache? After working with it for a while, I guess it just follow the cache rules that you set, and that _you_ in fact that way tell the SW what _you_ consider being offline. That's something that I needed to learn that would be better to just read.

How about something like:

## Handling errors when the server can't be reached
All requests are passed through the service worker (unless the ngsw-bypass request header / query parameter is added).

When a server can't be reached and the request times out, the service worker returns a [504 Gateway Timeout](https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/504) status. Because this can happen either when the client or the server is offline, there's no way of detecting through the service worker that the request failed due to the client being disconnected.

Something about how and why the SW alters the request/response (related to the 504 response, but also if there's other stuff worth mentioning).

**Comment by gkalpak** [comment]
Thx for sharing your thoughts, @andreaslarssen :heart:
I am addressing some of your points in more detail below. (Sorry for the lengthy reply 😇)

While I am against some of your suggestions, I hear you that there may be some gaps in explaining how the SW behaves in various scenarios and how each configuration option may affect its behavior. I am keen on addressing these points, but I would try not to expose implementation details or focus on the online/offline state (for reasons explained below).

I definitely don't hold these views strongly and could be convinced otherwise (for example, on what constitutes an implementation detail).

##
> there's nothing in the docs (as far as I can see) that indicates that all requests are being passed through the SW

In the [SW intro guide][1], it says that:
_"Service workers function as a network proxy. They intercept all outgoing HTTP requests made by the application and can choose how to respond to them."_
:smiley:

Also, keep in mind that explaining how SWs work in general is outside the scope of the Angular docs. The Angular docs should only explain what the Angular SW does and how to use it. People that want to use the Angular SW are expected to have an understanding of what a SW is/how it works.

We also provide links in the intro guide to resources where people can learn more about SWs (for example, [this link][2]).

##
> So rather than saying that mutating requests (also) are passed through, maybe just mention that all the requests are passed through the SW?

It is not saying that only non-mutating requests pass through :smiley:
It says that only non-mutating requests are _cached_ by the SW (which is true). _All_ requests pass through the SW (by virtue of how SWs work), but non-mutating ones are _not cached_ by the Angular SW.

##
> Now that you mention it, it would be great to have a few words about why and how the SW alters the request/response.

TBH, I'd rather keep this out of the docs. This is an implementation detail and should not be documented.
The SW may indeed alter the responses but only in a way that could happen without the SW as well. So, your app should be able to handle these responses fine (as it may encounter the same responses without the SW).

##
> When it comes to the "detect if the app is offline", my assumption was that you could (somehow), cause I thought that the SW would have to in order to work.

It sounds to me like you put too much value on the notion of being offline/online 😛
Unfortunately, as seen with `navigator.onLine`, not even the browser can 100% reliably determine that :grin:

It is also not a binary state thing. The real question is not whether the client is offline or online, but whether the client can get a successful response from the server (in a reasonable amount of time). Being online (as in "the client being connected to the internet") does not guarantee that a successful response will be received. There are many reasons why an "online" client could get errors/failed responses, such as:
  - The server is down and sends 5xx responses.
  - The server is overloaded and cannot respond in time, so requests time out.
  - A CDN is having issues and causes requests to fail.
  - The network connection is super slow, taking an unacceptable amount of time to get a response to the client.
  - The network connection is spotty (i.e. the client frequently gets briefly disconnected from the network), causing random requests to fail.
  - Etc.

So, I don't think that the status code of a request is a good way to detect the online/offline status of a client, no that the online/offline status (if it could be determined) is of great value.

Therefore, I would rather not document any "best practices" around detecting that or how the SW can play a role there :smiley:

That said, if you think there are improvements we can make in explaining how the SW caching works and what each option does (in a way that could help people better understand its behavior in various situations), I would be all for it 🚀 

[1]: https://angular.io/guide/service-worker-intro
[2]: https://developer.chrome.com/docs/workbox/service-worker-overview

**Comment by andreaslarssen** [comment]
@gkalpak A lengthy reply is good. I appreciate you taking the time to respond. 

> In the [SW intro guide](https://angular.io/guide/service-worker-intro), it says that:
"Service workers function as a network proxy. They intercept all outgoing HTTP requests made by the application and can choose how to respond to them."

You're absolutely right. I've read it, but I guess since it's the introduction, I only read it once, and forgot about it. I would then suggest to repeat it further down the docs as a reminder. Instead of this:

> ... Only non-mutating requests (GET and HEAD) are cached.

... rather this:
> ... All requests are passed through the SW, but only non-mutating requests (GET and HEAD) are cached.

When it comes to offline/online :
> It sounds to me like you put too much value on the notion of being offline/online

Well, the whole reason anyone would enable SW functionality is to handle online/offline status. It's the sole reason we have SW. I wanted to know if it was possible to notify the user about connection because my client wanted their users to know. It took me some time to figure it out because there are no obvious resources in the docs or external (as far as I have found) that handles the topic in a detailed way. 

One sentence that there's no reliable way of doing that, and that the 504 response code is what you get through the SW when the client is offline (though it can happen for other reasons as well) would probably save me a few days of work. And that, I think, is worth it.

I absolutely agree with you that Angular should not document general SW behavior, but when it comes to implementation details on how it handles (and alters) the response I find that 100% interesting and helpful. 

> So, your app should be able to handle these responses fine (as it may encounter the same responses without the SW).

The thing is, w/o passing the request through the SW, any number of reasons to get a 504 status can happen (of course), but it won't happen because the client is offline. 

This on the other hand:
> That said, if you think there are improvements we can make in explaining how the SW caching works and what each option does (in a way that could help people better understand its behavior in various situations), I would be all for it

... is the subject of a new issue I'll post at some point.
