### ISSUE TITLE
TestBed overrideComponent module doesn't import module providers

### ISSUE THREAD

**Issue by ArielGueta** [angular/angular#46535]
### Which @angular/* package(s) are the source of the bug?

common

### Is this a regression?

No

### Description

```ts
@Component({
  standalone: true,
  imports: [HttpClientModule],
  templateUrl: "./todos.component.html",
})
export class TodosComponent {
  constructor(http: HttpClient) {}
}

TestBed.overrideComponent(TodosComponent, {
  remove: {
    imports: [HttpClientModule],
  },
  add: {
    imports: [HttpClientTestingModule],
  },
});
const fixture = TestBed.createComponent(TodosComponent);
component = fixture.componentInstance;
fixture.detectChanges();
const controller = TestBed.inject(HttpTestingController);
```

I'm getting the error:

`NullInjectorError: No provider for HttpTestingController!` although the `HttpClientTestingModule` exposes this service in providers.

### Please provide the environment you discovered this bug in (run `ng version`)

```true
Angular v14.
```

**Comment by jnizet** [comment]
Hi @ArielGueta 

You're importing the HttpClient(Testing)Module at the component level (which is a bad idea BTW, see later), so it's not available from the root testing module's injector. Only from the component's injector. You should be doing

```ts
const controller = fixture.debugElement.injector.get(HttpTestingController);
```

It's a bad idea because if you use that component in a lazy-loaded module, then you'll have a second instance of HttpClient, not reusing the same interceptors/configuration as the HttpClient used in the root module. Import the HttpClientModule at the root, and not in any other module or component. It doesn't provide any component or directive, so importing it in a component is useless.

**Comment by ArielGueta** [comment]
Thanks
