### ISSUE TITLE
Problem in the code example for Angular Elements

### ISSUE THREAD

**Issue by BigPackie** [angular/angular#46629]
### Description

On the documentation page [https://angular.io/guide/elements](https://angular.io/guide/elements )  there seems to be an issue in the `showAsElement` of `popup.service.ts`, the element should be created using `createCustomElement()`, this step is left out. 

The same issue is present at section [https://angular.io/guide/elements#typings-for-custom-elements](https://angular.io/guide/elements#typings-for-custom-elements).

Version 14.0.5-local+sha.a183a2df50.

### What is the affected URL?

https://angular.io/guide/elements

### Please provide the expected behavior vs the actual behavior you encountered

If I am mistaken, the documentation should state that the  `createCustomElement()` function is called implicitly,  otherwise the examples should be fixed. 

### Please provide a screenshot if possible

<img width="505" alt="image" src="https://user-images.githubusercontent.com/17480316/176522569-1e9dba90-7ec2-4a48-8ebe-f911d7b7de1d.png">

<img width="430" alt="image" src="https://user-images.githubusercontent.com/17480316/176523307-d2380706-2980-4b2f-800c-fd6fb6dc3a5f.png">

**Comment by gkalpak** [comment]
Thx for reporting an issue, @BigPackie :+1:

I am not sure what you mean by _"in the `showAsElement()` [...] the element should be created using `createCustomElement()`"_. If you mean that `createCustomElement()` should be called (in order to add the Custom Element to the browser's `CustomElementRegistry`) before calling `document.createElement('popup-element')`, then you are right. But `createCustomElement()` is called in `app.component.ts` (i.e. it is not the `PopupServices`' responsibility to register the Custom Element.
(If you mean something else, please clarify :smiley:)

##
Regarding the [Typings for custom elements][1] section, it only shows how to work with types. This section is not supposed to show other application code that is involved in defining, registering and adding the Custom Element.

##
I hope these explanations make sense. (If not feel free to continue the discussion below.)

I am going to close this issue as I believe it is not actionable for us. But if you have specific suggestions on how to improve the Custom Element guide, please open a new issue or (better yet) send a pull request :pray:

[1]: https://angular.io/guide/elements#typings-for-custom-elements
