### ISSUE TITLE
refreshAheadMs missing on serviceWorker config

### ISSUE THREAD

**Issue by yelhouti** [angular/angular#46729]
### Which @angular/* package(s) are relevant/related to the feature request?

service-worker

### Description

The option `refreshAheadMs` is not copied to the the ngsw.json in this code:
https://github.com/angular/angular/blob/3a60063a54d850c50ce962a8a39ce01cfee71398/packages/service-worker/config/src/generator.ts#L89-L103

### Proposed solution

Add it there and the schema https://github.com/angular/angular/blob/253ac15ae89755f6830f3cf567c80de20d013663/packages/service-worker/config/schema.json

### Alternatives considered

Have a block that is copied as is or have fields modified without recreating the config to avoid issues when new features are added to the service worker config. ie: clone the object before modifying it (calling parseDurationToMs...) to avoid loosing options... and have a looser schema

**Comment by yelhouti** [comment]
@jessicajaniuk after more reading of ngsw-worker.js I think this is a bug, since:

https://github.com/angular/service-worker-builds/blob/174187efb087cbc8e848bad3a47ee68b112b8cab/ngsw-worker.js#L711-L718
```typescript
    async handleFetchWithPerformance(req, event, lru) {
      var _a;
      const okToCacheOpaque = (_a = this.config.cacheOpaqueResponses) != null ? _a : false;
      let res = null;
      const fromCache = await this.loadFromCache(req, lru);
      if (fromCache !== null) {
        res = fromCache.res;
        if (this.config.refreshAheadMs !== void 0 && fromCache.age >= this.config.refreshAheadMs) {
```
Tries to use this value that cannot be set because it is not defined the schema and not copied by the generator.
Do you think we could switch to bugReport ?

**Comment by gkalpak** [comment]
Oh, interesting. This seems to be an undocumented, half-implemented feature :smiley:

We should either remove all references altogether or properly implement it. In order to do that, we would need to:
- [ ] Decide where it should appear in the `ngsw-config.json` (i.e. inside or outside the `dataGroup > cacheConfig` property).
- [ ] Update [generator.ts][1] to copy it to `ngsw.json`.
- [ ] Add it to [schema.json][2].
- [ ] Document it in the [service-worker-config.md][3] guide.
- [ ] Add tests for it (probably in [data_spec.ts][4]).

##
@yelhouti, would you be interested in working on PR by any chance? :smiley:

[1]: https://github.com/angular/angular/blob/a003dd8dc2ad50db20c684d5a2b1e748ad339a42/packages/service-worker/config/src/generator.ts#L89-L104
[2]: https://github.com/angular/angular/blob/a003dd8dc2ad50db20c684d5a2b1e748ad339a42/packages/service-worker/config/schema.json
[3]: https://github.com/angular/angular/blob/a003dd8dc2ad50db20c684d5a2b1e748ad339a42/aio/content/guide/service-worker-config.md
[4]: https://github.com/angular/angular/blob/a003dd8dc2ad50db20c684d5a2b1e748ad339a42/packages/service-worker/worker/test/data_spec.ts

**Comment by dylhunn** [comment]
We should either fix this or remove as per George's comment.

**Comment by yelhouti** [comment]
@dylhunn I am under too much work for now, I want be able to fix it, sorry :s

**Comment by robertIsaac** [comment]
> Oh, interesting. This seems to be an undocumented, half-implemented feature 😃
> 
> We should either remove all references altogether or properly implement it. In order to do that, we would need to:
> 
> * [ ]  Decide where it should appear in the `ngsw-config.json` (i.e. inside or outside the `dataGroup > cacheConfig` property).
> * [ ]  Update [generator.ts](https://github.com/angular/angular/blob/a003dd8dc2ad50db20c684d5a2b1e748ad339a42/packages/service-worker/config/src/generator.ts#L89-L104) to copy it to `ngsw.json`.
> * [ ]  Add it to [schema.json](https://github.com/angular/angular/blob/a003dd8dc2ad50db20c684d5a2b1e748ad339a42/packages/service-worker/config/schema.json).
> * [ ]  Document it in the [service-worker-config.md](https://github.com/angular/angular/blob/a003dd8dc2ad50db20c684d5a2b1e748ad339a42/aio/content/guide/service-worker-config.md) guide.
> * [ ]  Add tests for it (probably in [data_spec.ts](https://github.com/angular/angular/blob/a003dd8dc2ad50db20c684d5a2b1e748ad339a42/packages/service-worker/worker/test/data_spec.ts)).
> 
> @yelhouti, would you be interested in working on PR by any chance? 😃

I'd like to work on it
but did you decide yet which path to take?
I see there are two unanswered questions
1. remove all references altogether or properly implement it?
2. Decide where it should appear in the ngsw-config.json?
