### ISSUE TITLE
docs: replace "view" term with more explicit "rendered DOM structure" or equivalent term

### ISSUE THREAD

**Issue by bob-watson** [angular/angular#46723]
### Description

Update the documentation to change current references to _view_ with more explicit terminology.
The [Glossary definition of _view_](https://angular.io/guide/glossary#view) should be updated to reflect the new terminology first.

After the Glossary has been updated, references in the AIO documentation can be updated as required.

### What is the affected URL?

https://angular.io/guide/glossary#view

### Please provide the steps to reproduce the issue

N/A

### Please provide the expected behavior vs the actual behavior you encountered

To encounter the clearer language in the docs.

**Comment by bob-watson** [comment]
@jelbourn @josmar-crwdstffng  I created this to document the change in terminology.
Can you please add additional information about the need for this change?

**Comment by josmar-crwdstffng** [comment]
@jelbourn @bob-watson 
The updated usage pattern for the documentation was brought into scope as part of the Component content updates.

https://github.com/angular/angular/pull/45501#discussion_r892923834

The preference is the following.

Avoid the use of  the `view` term as much as possible.
Define the `view` term and use it where relevant for code examples, such as `ViewChildren`.

Use a more broadly understood term or phrase.
Otherwise, use one of the following phrases.

*   the rendered DOM structure
*   the DOM of the component
*   the HTML template

Per acronym expansion patterns, replace the 1st instance of `DOM` with `document object model (DOM).

**Comment by pkozlowski-opensource** [comment]
A drive-by comment - the `view` concept shows up in many of our APIs (ex. `ViewContainerRef`, `ViewRef` etc.) and is a pretty fundamental concept in the framework. Also a `view` is much more than DOM so we might give people incorrect mental model.

**Comment by jelbourn** [comment]
Yeah, Pawel has a good point. My take on this is that any introductory / explanatory content should avoid "View", but we should still define the term when we do have to explain dynamic component instantiation or queries.

**Comment by JeanMeche** [comment]
I'll close this as we don't have a glossary anymore.
