### ISSUE TITLE
AOT Cannot assign value "$event" to template variable "item". Template variables are read-only.

### ISSUE THREAD

**Issue by JiaLinYou** [angular/angular#46797]
### Description

After I upgrade Angular 8 to Angular 9 or Angular10, and enable the AOT, If I use "npm run build -- -c prod" to build the code, I will get this error:
    "Cannot assign value "$event" to template variable "item". Template variables are read-only."

![image](https://user-images.githubusercontent.com/96672802/178471858-98470586-d6ea-425b-b841-a97e5087112e.png)

If I just disable the AOT, use the JIT to build the code, I will not get this error.

I try to set "fullTemplateTypeCheck": true, in tsconfig.json

![image](https://user-images.githubusercontent.com/96672802/178471356-9cbd546f-73e4-4424-a63b-79dc6be539e5.png)

then i will get some other error, after fixed them, The previous error disappeared, and i also can build successful, but i did not found some error about previous "$event" , what is the reason?

This error will occur no matter whether I compile with ES5 or ES6 in tsconfig.json. ("target": "es5")

![image](https://user-images.githubusercontent.com/96672802/178471150-731b5d41-3576-401a-ae98-36bbf98b515a.png)

### Please provide the steps to reproduce the issue

1. Upgrade Angular to version 9 or 10, and enable AOT compile
2. Use  "npm run build -- -c prod" to compile code

### Please provide the expected behavior vs the actual behavior you encountered

Use Angular9 AOT 
"target": "es5"，
"npm run build -- -c prod" command compile could successful.

### Please provide a screenshot if possible

![image](https://user-images.githubusercontent.com/96672802/178473420-ffbec2b0-f355-4d57-af0f-3b07cedbb16d.png)

### Please provide the exception or error you saw

```true
Cannot assign value "$event" to template variable "item". Template variables are read-only.
```

### Is this a browser-specific issue? If so, please specify the device, browser, and version.

```true
No
```

**Comment by JoostK** [comment]
Since Angular Ivy it is no longer possible to assign to template variables, as noted in [the Ivy compatibility guide](https://v9.angular.io/guide/ivy-compatibility#less-common-changes):

> It is now an error to assign values to template-only variables like item in [ngFor](https://v9.angular.io/guide/api/common/NgForOf)="let item of items" (previously, the compiler would ignore these assignments).

Please note that there have been many changes to improve template type-checking and compiler errors in recent versions of Angular, and version 9 is no longer supported.

**Comment by JiaLinYou** [comment]
Sure, I think your mean is can not assign values to item like item=$event?  But how can I locate the code with the problem ? 

In fact, I have checked my code and could not find some code like this.

After I use "fullTemplateTypeCheck": true, I just found some code like [(ngModel)] = "item", and I have fixed them, the error is gone, but I think it is not right, because I really can not find  item=$event.

Would you please kindly tell me how could I do ?

**Comment by JiaLinYou** [comment]
This package.json file FYI

![image](https://user-images.githubusercontent.com/96672802/178638621-647b7f66-07d9-4d50-9706-efd8dad2262b.png)

**Comment by JoostK** [comment]
Assigning `item = $event` should be okay, it's the opposite that is not possible. FYI, `[(ngModel)]="item"` is shorthand syntax for `[ngModel]="item" (ngModelChange)="item = $event"`.

> Sure, I think your mean is can not assign values to item like item=$event? But how can I locate the code with the problem ?

Since it's a hard crash this is not straight-forwards unfortunately. It might not be in your own code, but in some library code instead.

Like I mentioned, there have been a lot of improvements to error reporting in later versions of Angular, so  I'd advice that you update to a supported version of Angular.

**Comment by JiaLinYou** [comment]
Thank you so much, I will double check if there any code like $event = item, or the error  just from some library code.

**Comment by SirDneial** [comment]
Have you had any luck on this I ran into the same issue and have been stuck all day on this.
