### ISSUE TITLE
chore(router): rename RouterOutlet to RouterViewport

### ISSUE THREAD

**Issue by PascalPrecht** [angular/angular#4679]
`RouterOutlet` has been called `RouterViewport` before. We had to change this, because A2 also introduced a concept of "viewport" directives, which are directives that allow structural changes to the DOM (`*ng-for`, `*ng-if`, ...). To avoid confusion we came up with a new name for `RouterViewport` which was `RouterOutlet`. You can read the discussion here: https://github.com/angular/router/issues/264

"Viewport" directives as a terminology don't exist anymore. Those are just directives that have a template reference. I'd therefore like to propose `RouterViewport` as the new name for `RouterOutlet` again.

@btford wdyt?

**Comment by btford** [comment]
I tasked @johnpapa with determining the new name for this. John, what were your conclusions?

@PascalPrecht – I'm not interested in making this breaking change before Angular Connect.

**Comment by PascalPrecht** [comment]
Understood. We can totally do this after angularconnect.

**Comment by johnpapa** [comment]
I've polled a lot of devs informally and the resounding answers folks liked:

1. `router-view`
2. `router-viewport`
3. `view-port`


they cited that they liked router-view as it was similar to ui-view and ng-view.

We can do a formal poll if you like. Where do you want to go from here?

I dont think the name is that critical. I'll call it whatever, but I do prefer a name that makes sense. both of the above seem good to me.

**Comment by PascalPrecht** [comment]
> I dont think the name is that critical. I'll call it whatever, but I do prefer a name that makes sense. both of the above seem good to me.

I agree. And as long as we have a chance to make names nicer, I think we should do that. I like `router-view` too. Both, `router-viewport/router-view-port` and `router-view` are better than `router-outlet` in my opinion.

**Comment by btford** [comment]
I'm good with the first two. I'm worried that the last one is going to be confusing between `<viewport>` and `<view-port>`. I have a slight preference for `<router-view>`.

**Comment by PascalPrecht** [comment]
Cool, then let's just go with `router-view` (post AngularConnect ofc)?

**Comment by johnpapa** [comment]
i like `router-view` the best, personally.

**Comment by gdi2290** [comment]
:+1: `router-view`

**Comment by Gillespie59** [comment]
:+1:  for `router-view` also. Similar to our previous `ui-view` and `ng-view`. So all newcomers will understand easily the meaning of this component !

**Comment by mgechev** [comment]
My favorite is `router-view` as well.

**Comment by juergenzimmermann** [comment]
:+1: router-view

**Comment by PascalPrecht** [comment]
Okay, I think we agreed on that now. PR coming.

**Comment by gkalpak** [comment]
Too late to the party, but I wanted to speak up for those in favor of `router-viewport` (apparently that's just me :smiley:): 

It's a nice name !

**Comment by mhevery** [comment]
I don't think it is `router-view`, because the directive does not represent a view. Which is why I think something which contains a view is a better name. `router-viewport` would be my choice. Plus we are not really dealing with views, but with components `router-component-anchor` (not serious), but the point is that that would be a properly descriptive name. Even `router-outlet` is more clear then `router-view` It may be that view is a common terminology, but it is not strictly speaking correct. 

the directive is an anchor or a container into which other components get loaded. It is not the component.  That would be like calling a garage a car because that is where the car goes.

**Comment by johnpapa** [comment]
@mhevery  Yes, you are right of course. But being exactly accurate is less important than communicating effectively with developers who use it. I don't think `router-view` leads anyone down a bad path. And it is what most folks I spoke to seemed to click with.

That said, I'm fine with `router-viewport`. It works for me.

**Comment by rolandjitsu** [comment]
I think that `router-viewport` would be better than `router-view`. `viewport` suggests that it's a window or a frame for something, could be anything, could be a lot of things. But just `view` suggests that it the router's view, or that is how I see it. From [Google](https://www.google.dk/search?q=what+is+a+viewport&oq=what+is+a+viewport+&aqs=chrome..69i57j0l5.2914j0j7&sourceid=chrome&es_sm=119&ie=UTF-8), in computing, a `viewport` is `a framed area on a display screen for viewing information.`.

**Comment by gdi2290** [comment]
mind the component is created next to the `router-outlet`. [loadNextToLocation](https://github.com/angular/angular/blob/c3ab20cc87dd016517c8945b8fe0adab455cc6ed/modules/angular2/src/router/router_outlet.ts#L65)
for example

```html
<router-outlet></router-outlet>
<home></home>
```
it's not created inside of `router-outlet`
```html
// ng1 style
<ng-view>
  <home></home>
</ng-view>
```
the change was made for animating views (switching from old and new). Technically viewport doesn't make sense with this behavior while outlet does

**Comment by rolandjitsu** [comment]
@gdi2290 that is true. But technically speaking, and outlet is also something that you plug into not next to.

**Comment by PascalPrecht** [comment]
So `router-viewport` it is then?

**Comment by btford** [comment]
Yes, `viewport` makes most sense.

Please keep in mind that we'll implement this with a deprecation so that both `router-outlet` and `router-viewport` work, then remove `router-outlet` at a later time.

**Comment by jvandemo** [comment]
Technically the directive represents an insertion point instead of a wrapper (as @mhevery and @gdi2290 noted).

Semantically a name like `router-insertion-point` would be a good choice. In computer interfaces insertion points are often represented by a cursor so `router-cursor` would also make a good semantic name.

However, developer experience would probably be a lot higher with `router-viewport` as it sounds much more familiar with current terminology (`ui-view`, `ng-view`, ...)

The catch there it that it may surprise developers that the content is not rendered within the directive, but next to it (same for `router-outlet`).

**Comment by mhevery** [comment]
@btford can you see if this is still relevant and close?

**Comment by mhevery** [comment]
This is obsolete, and no longer relevant / actionable. To keep our issues clean, we are aggressively closing them.
