### ISSUE TITLE
updating the page all the time looking for the new version - SwUpdate - @angular/service-worker

### ISSUE THREAD

**Issue by andrejm7** [angular/angular#46878]
### Which @angular/* package(s) are the source of the bug?

service-worker

### Is this a regression?

No

### Description

Hello friends,

I updated my project to angular 14..
localhost everything was fine.. but when I took it to production, something that was normal before, the application was always updating the page...

I believe the problem is with SwUpdate

below my code that worked fine.

```
  constructor(
    public utils: UtilsService,
    private updates: SwUpdate,
    private appRef: ApplicationRef
  ) {
    this.utils.mostraNavBar = false;
    this.updateClient();
    this.checkUpdate();
  }

  ngOnInit() {
  }

  updateClient() {
    if (!this.updates.isEnabled) {
      console.log('not enabled');
    }

    this.updates.versionUpdates.pipe(
      filter((evt): evt is VersionReadyEvent => evt.type === 'VERSION_READY'),
      map(evt => ({
        type: 'UPDATE_AVAILABLE',
        current: evt.currentVersion,
        available: evt.latestVersion,
      })));

    this.updates.versionUpdates.subscribe((event) => {
      // console.log('current ', event.currentVersion, 'available ', event.latestVersion);
      this.updates.activateUpdate().then(() => window.location.reload());
    });

    // this.updates.activated.subscribe((event) => {
    //   console.log('current ', event.previous, 'available ', event.current);
    // });
  }

  checkUpdate() {
    this.appRef.isStable.subscribe((isStable) => {
      if (isStable) {
        const timeInterval = interval(500000);

        timeInterval.subscribe(() => {
          this.updates.checkForUpdate().then(() => console.log('checked'));
        });
      }
    });
  }
```

### Please provide the exception or error you saw

```true
updating the page all the time looking for the new version
```

### Please provide the environment you discovered this bug in (run `ng version`)

```true
Angular: 14.0.6
... animations, cli, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... pwa, router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1400.6
@angular-devkit/build-angular   14.0.6
@angular-devkit/core            14.0.6
@angular-devkit/schematics      14.0.6
@angular/service-worker         14.0.6
@schematics/angular             14.0.6
rxjs                            7.5.6
typescript                      4.7.4
```

**Comment by andrejm7** [comment]
I returned the version
from 
"@angular/service-worker": "^14.0.6",

for
"@angular/service-worker": "^13.3.10",

problem solved.. but is there any bug in this new version?

**Comment by gkalpak** [comment]
Thx for reporting this issue, @andrejm7!

I looked through the changes of the `@angular/service-worker` package and could not identify something that would cause this issue (on its own). At this point, it feels more like something else is going on (outside the control of `@angular/service-worker`). It could be something in your configuration, you application code or your server.

You might want to try debug this further and post more detailed info. See [here][1] for some tips on debugging the Angular SW.

##
BTW, I noticed a couple of problems with the code you shared:

1. In `updateClient()`, you are piping `versionUpdates` through some RxJS operators (i.e. to filter `VersionReadyEvent`s) and in doing so you create a new observable. However, on the next line, you subscribe to the original `versionUpdates` observable, which means that you are calling `activateUpdate()` on every `VersionEvent` (not just `VersionReadyEvent`s).
    Suggested fix:

    ```diff
     this.updates.versionUpdates.pipe(
       filter((evt): evt is VersionReadyEvent => evt.type === 'VERSION_READY'),
       map(evt => ({
         type: 'UPDATE_AVAILABLE',
         current: evt.currentVersion,
         available: evt.latestVersion,
    -  })));
    -
    -this.updates.versionUpdates.subscribe((event) => {
    +  })),
    +).subscribe((event) => {
       // console.log('current ', event.currentVersion, 'available ', event.latestVersion);
       this.updates.activateUpdate().then(() => window.location.reload());
     });
    ```

2. In `checkUpdate()`, you are creating a new `interval()` every time the app stabilizes. Instead you should be creating one `interval()` the first time the app stabilizes. See [here][2] for the recommended way to handle periodic checks for updates.

##
Based on the above, I am going to close this issue (since it is not actionable for us in its current state). However, feel free to continue the discussion below or open a new issue if you can provide more details.

[1]: https://angular.io/guide/service-worker-devops#debugging-the-angular-service-worker
[2]: https://angular.io/guide/service-worker-communications#checking-for-updates
