### ISSUE TITLE
Attach router-outlet's name to `NavigationEnd`

### ISSUE THREAD

**Issue by alexciesielski** [angular/angular#46891]
### Which @angular/* package(s) are relevant/related to the feature request?

router

### Description

I implemented a secondary named router-outlet, which I use to display a sidebar in.
On (primary) navigation I would like to automatically close that sidebar.

Simply using 

```ts
router.events.filter(evt => evt instanceof NavigationEnd)
```

is not enough anymore, since that emits for both primary and named router-outlets, and the `NavigationEnd` instance does not contain any information about which `router-outlet` has produced the navigation.

### Proposed solution

Attach a `outletName: string` property (or similar) to the `NavigationEnd` (or maybe even the `RouterEvent`?) class to be able to differentiate what `router-outlet` has produced the navigation.

### Alternatives considered

I am using the following snippet to be able to react to the primary router-outlets changes, but it seems not to work for every navigation.

A native solution on the above mentioned classes would be preferred.

```ts
readonly primaryOutletUrl$: Observable<UrlSegment[]> = 
   this.childrenOutletContext.getContext(PRIMARY_OUTLET)!.route!.url;
```

**Comment by atscott** [comment]
The outlets themselves have activate and deactivate events: https://github.com/angular/angular/blob/0e3a2759b0eb555fec9f9bc5db9af0585a1d7093/packages/router/src/directives/router_outlet.ts#L170-L171

Are those not enough to accomplish what you're looking for here? 

The proposed feature here doesn't really fit well either. One `NavigationEnd` event happens for a navigation which may have activated or deactivated _multiple_ outlets. In addition, you might have a primary outlet under a named outlet so an array isn't sufficient either. In order to get the fully correct answer, we'd end up with the same tree structure as the `ActivatedRoute`.

**Comment by alexciesielski** [comment]
That doesn't work for my use-case since I'm navigating deep in nested child routes, and it looks like the `activateEvents` emitter fires only for top-level navigation events. 

At least I'm not getting any emissions when navigating in the child routes.

I *could* try and get a reference to the router-outlet in question, but that seems like a hassle to track it in a service and it also stops working when navigating on different levels - unless I track those outlets, too.

What I'm saying is it's possible to find a workaround, but it seems like a big deal for something that imho could be done ootb.

**Comment by alexciesielski** [comment]
Right, I did not think about the case of having another primary outlet inside a named one. That obviously breaks the initial idea.

Thanks for the suggestion of using the URL to listen for primary outlet events, covers my usecase perfectly.
