### ISSUE TITLE
Behaviour change between Angular 13 and Angular 14

### ISSUE THREAD

**Issue by Eldriann** [angular/angular#46972]
### Which @angular/* package(s) are the source of the bug?

router

### Is this a regression?

Yes

### Description

In angular 14 an exception will be thrown if a route has no `component` / `loadComponent ` / `redirectTo` / `children` / `loadChildren` defined but has a guard that always redirects the user in a lazy loaded route in development mode.
In angular 13 this was not the case and the user was correctly redirected after the guard was played.
This was useful for having a single guard redirecting the user on a correct child component based on some API call results for multiple pages and having a single route that only existed to redirect that would be used in other parts of the application for readability.
I suppose this is due to the change causing lazy loaded route to be validated once loaded and it being considered invalid but how can I achieve the same effect without assigning a useless component to the constantly redirecting route?

### Please provide a link to a minimal reproduction of the bug

https://stackblitz.com/edit/angular-ivy-gdwqjj?devToolsHeight=33&file=src/app/pages/lazy-loaded/lazy-loaded.routes.ts

### Please provide the exception or error you saw

```true
Error: Uncaught (in promise): Error: Invalid configuration of route 'lazy-loaded//'. One of the following must be provided: component, loadComponent, redirectTo, children or loadChildren
Error: Invalid configuration of route 'lazy-loaded//'. One of the following must be provided: component, loadComponent, redirectTo, children or loadChildren
```

### Please provide the environment you discovered this bug in (run `ng version`)

```true
The link above is the environment on stackblitz
```

**Comment by rchod** [comment]
no need for a dummy component, you can make your original code work by adding an empty children
```

      {
        path: '',
        pathMatch: 'full',
        children: [],
        canActivate: [StatusRedirectGuard],
      },
```

**Comment by atscott** [comment]
That’s correct, this is an intended breaking change and listed in the notes for v14. Previously, lazy loaded configs were not validated but now they are. This was never really allowed but you could get away with it since the configs weren’t validated. 

As mentioned by @rchod, you can use an empty list of children as a workaround. 

The correct solution to this is https://github.com/angular/angular/issues/13373. I’m waiting on this until the feature for functional guards and resolvers is merged. https://github.com/angular/angular/pull/46684  After that, a functional redirect would be quite natural in the API surface for Route.
