### ISSUE TITLE
configurable key for ngsw-bypass in service-worker

### ISSUE THREAD

**Issue by 9thQuadrant** [angular/angular#46984]
### Which @angular/* package(s) are relevant/related to the feature request?

`@angular/pwa`

### Description

A customizable key for `ngsw-bypass` would be great if we can include some set of headers from `ngsw-config.json`
Also exclude URLs for API calls would be very helpful

### Proposed solution

A field in `ngsw-config.json` giving option to omit in `ngsw-worker.js`

### Alternatives considered

Right now, Im replacing the `ngsw-bypass` with `Authorization` to by pass all our API calls

**Comment by nikithamunigala193** [comment]
Waiting for resolution

**Comment by bluestar39** [comment]
+1

**Comment by gkalpak** [comment]
Unfortunately, this is not possible at the moment. The reason is that the `ngsw.json` manifest that corresponds to each client is retrieved asynchronously, while the decision on whether to bypass the service worker or not has to be made synchronously.

Therefore, the logic for deciding this needs to be embedded into the service worker code and cannot depend on the configuration. #21197 will provide a way to address this, but there are not concrete plans on implementing it.

I am going to close this issue (in favor of #21197), but feel free to continue the discussion below.

**Comment by 9thQuadrant** [comment]
What I meant is the string `ngsw-bypass` inside the generated service worker must be dynamic and configurable from `ngsw-config.json`. This change would not be runtime, just a build time.

**Comment by gkalpak** [comment]
The SW script is fixed and does not change at build time. The only thing that happens at build time is that `ngsw-config.json` is processed and converted to `ngsw.json`. The the SW will retrieve and use `ngsw.json` at run time.

So, without #21197, there is no way to modify the SW script at build time.
