### ISSUE TITLE
Breaking undocumented change from Angular 13 to 14 in custom PreloadingStrategy. "preload"-method is called despite a set canLoad-guard.

### ISSUE THREAD

**Issue by 5te1n** [angular/angular#47003]
### Which @angular/* package(s) are the source of the bug?

core, router

### Is this a regression?

Yes

### Description

In Angular 13.3.10 the "preload"-Method in a custom PreloadingStrategy is not called for routes with a set canLoad-guard.
https://stackblitz.com/edit/angular-ivy-wf131m?file=src/app/app-routing.module.ts
This is also mentioned in the documentation: https://angular.io/guide/router-tutorial-toh#canload-blocks-preload

In Angular 14.0.0 this behaviour changed. The "preload"-method is called despite a set canLoad-guard. This change was not mentioned in the changelog and is the opposite of what is written in the documentation. Is this an intended change?
https://stackblitz.com/edit/angular-ivy-nabdle?file=src/app/app-routing.module.ts

### Please provide a link to a minimal reproduction of the bug

https://stackblitz.com/edit/angular-ivy-nabdle?file=src/app/app-routing.module.ts

### Please provide the exception or error you saw

```true
The "preload"-method is called despite a set canLoad-guard in angular 14.
```

**Comment by atscott** [comment]
Version 14 introduced the `loadComponent` for routes, which is not blocked by `canLoad` guards. This is why the `preload` method is still called. That said, the `loadChildren` _is not_ called if there is a `canLoad` guard so I would not consider this a breaking change.

The documentation could use an update and I will also adjust the code to not call the `preload` method in cases where there is a `canLoad` and no `loadComponent`. In this scenario, there is no need to call the `preload` method since nothing will be done with the result.

**Comment by 5te1n** [comment]
@atscott Thank you. That sounds like a good solution. In my case, I wanted to preload the modules only after the user logged in. So I removed the canLoad-guards after the login and called Router.preload() manually.
