### ISSUE TITLE
Allow custom required validators or add conditional required.

### ISSUE THREAD

**Issue by infacto** [angular/angular#47080]
It's about `forms`.

I found out that the `Validators.required` function adds the `required` attribute to the html input element. But I cannot find any related code. I just found the validator it self. But I guess that there is some code what checks if exactly **this** validator is set and binds the required attribute to it. But how to register an own custom required validator?

https://github.com/angular/angular/blob/0abb67af59a92a2b29082a259aa9f4ea3fbaab7d/packages/forms/src/validators.ts#L209-L211

I'm currently working on a custom required validator this an conditional callback function. Btw. it would be great if Angular provides an build-in validator for this by extending this validator like: 

```ts
this.form = new FormGroup({
  name: new FormControl(null, { validators: Validators.required(() => this.isNameRequired()) })
})

// this.isNameRequired checks other form controls like a checkbox and returns true on checked state.
// One known issue: The validator is not updated on form changes. We need to update and validate method manually.
```

This is either an feature to add an conditional required validator or to allow custom required validators with automatic required attribute on the input element. I also wonder where the magic happens (in code). It's no question for StackOverflow. ...

The current alternative is to subscribe to valueChange and change validators, which is a bit ugly way to do that.

**Comment by AndrewKushnir** [comment]
@infacto the code that sets the `required` attribute is located here: https://github.com/angular/angular/blob/main/packages/forms/src/directives/validators.ts#L360.

You can find additional information on how to create custom validators (for both template-driven and reactive forms) here: https://angular.io/guide/form-validation#defining-custom-validators

Since this ticket doesn't fall into the bug report or feature request category, I'm closing it. You could get additional support by reposting your question on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).

Thank you.

**Comment by infacto** [comment]
@AndrewKushnir Thanks for the info. Actually, my proposed feature is a conditional validator as described above. What do you think about that idea? I may reduce a lot of code on value change subscriptions. Currently validators are only triggered on control touches. It does not act if another value changed. So I think the implementation is maybe more complex as expected. A conditional validator is written in a few lines. But needs the adaption to the required attribute directive and change detection. Anyway, I'm fine with that closed state. I just wanted to trigger some thought about. I also found an existing library for conditional required validator. See [rxweb/reactive-form-validators](https://github.com/rxweb/rxweb/tree/master/client-side/angular/packages/reactive-form-validators#conditional-validation) But this does also not handle the required attribute. And I still not quite understand this required directive. So it would be great if Angular officially supports such conditional validator. So, feel free to do whatever you want. It's just an idea... Meanwhile, I'll take a look to the validators-directive and find out how to automatically bind the required attribute with my custom required validator. ...
