### ISSUE TITLE
Angular Elements does not work with Primeng

### ISSUE THREAD

**Issue by Jad31** [angular/angular#47106]
### Which @angular/* package(s) are the source of the bug?

elements

### Is this a regression?

No

### Description

I'm trying to create an Angular Elements using Primeng components. When I run the Angular app everything works just fine. However, once I build and use my Angular Elements containing my Primeng button component, it breaks.

This is what is in my component:

```html
<button pButton type="button" label="Click"></button>
<p-button label="Click"></p-button>
```

And here is how a build my Angular Element:

```ts
import { Injector, NgModule } from '@angular/core';
import { createCustomElement } from '@angular/elements';
import { BrowserModule } from '@angular/platform-browser';
import { BrowserAnimationsModule } from '@angular/platform-browser/animations';

import { ButtonModule } from 'primeng/button';
import { AppComponent } from './app.component';
import {
  PrimengButtonElementModule,
  PrimengButtonElementComponent,
} from '../../../primeng-button-element/src/public-api';

@NgModule({
  declarations: [AppComponent],
  imports: [
    BrowserModule,
    BrowserAnimationsModule,
    PrimengButtonElementModule,
    ButtonModule,
  ],
  bootstrap: [AppComponent],
})
export class AppModule {
  constructor(private injector: Injector) {
    const myCustomElement = createCustomElement(PrimengButtonElementComponent, {
      injector: this.injector,
    });

    customElements.define('my-custom-element', myCustomElement);
  }
}

```

I tried to use differents `ViewEncapsulation` in the component.

I also tried in `main.ts`

```ts
platformBrowserDynamic().bootstrapModule(AppModule, [
  {
    defaultEncapsulation: ViewEncapsulation.native
  }
]
```
Nothing worked.

## Steps to reproduce:

Clone the minimal reproduction of the bug repository: https://github.com/Jad31/primeng-in-angular-elements-issue

1. `yarn`: to install dependencies
2. `yarn run ng serve elements`: To demonstrate that primeng button works well in Angular application
3. `yarn run elements:build`: build the Angular Elements, make it a single **js** file and place it in the assets of the application (here named using-elements) that will use the Angular Element
4. `yarn run ng serve`: serve using-elements application

### Please provide a link to a minimal reproduction of the bug

https://github.com/Jad31/primeng-in-angular-elements-issue

### Please provide the exception or error you saw

```true
Angular Elements not working with Primeng.
```

### Please provide the environment you discovered this bug in (run `ng version`)

```true
Angular CLI: 13.3.9
Node: 16.16.0
Package Manager: yarn 1.22.17
OS: darwin x64

Angular: 13.3.11
... animations, common, compiler, compiler-cli, core, elements
... forms, platform-browser, platform-browser-dynamic, router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1303.9
@angular-devkit/build-angular   13.3.9
@angular-devkit/core            13.3.9
@angular-devkit/schematics      13.3.9
@angular/cli                    13.3.9
@schematics/angular             13.3.9
rxjs                            7.5.6
typescript                      4.6.4
```

### Related Issues
- https://stackoverflow.com/questions/73303622/angular-elements-does-not-work-with-primeng
- https://github.com/primefaces/primeng/issues/11811

**Comment by gkalpak** [comment]
I tried out the demo and it seems to work for fine for me. I.e., when I inspect the DOM of the page, I see that the `<my-custom-element>` element is correctly expanded to the `PrimengButtonElementComponent` template etc.

The only difference is that the PrimeNG styles are not applied. That is because you apply the necessary styles in the [`elements` project][1], but not in the other projects.

##
I am not sure what is the best way to bundle/include the PrimeNG styles. Maybe, for this usecase, it might be a good idea to include the styles in the `PrimengButtonElementComponent`'s `@Component > styleUrls` property.

But it depends on how the PrimeNG styles are structured and your usecase. (For example, are there shared PrimeNG styles that are intended to be shared among components? Do you want to allow consumers of the custom element to override styles? Etc.). I think it is worth discussing this on the PrimeNG issue tracker.

BTW, it might be worth checking out some of the 3rd-party tutorials that discuss ways of bundling Angular Elements for re-use outside an Angular application. For example the [one from Angular Architects][2].

##
Based on the above, the problem doesn't seem to be a related to `@angular/elements`. Therefore, I am going to close this issue, but feel free to continue the discussion below.

[1]: https://github.com/Jad31/primeng-in-angular-elements-issue/blob/6bd7ead0fa34a054f48bd045c6bf35628f871b4d/angular.json#L165-L168
[2]: http://www1.angulararchitects.io.dedi1415.your-server.de/aktuelles/angular-elements-part-i/

**Comment by collettemathieu** [comment]
Here you can find a solution with angular elements and primeNg => https://gitlab.com/collettemathieu/prime-ng-angular-elements

```bash
yarn run build:elements

yarn run start
```

I think you can improve the system if you want by sharing themes (scss files) from primeNg among apps and maybe that (https://medium.com/netanelbasal/getting-to-know-the-createapplication-api-in-angular-f1c0a2685047) could be of interest to you in order to avoid to create a complete app to use angular elements. But it depends on your needs.

Best regards!
