### ISSUE TITLE
Routes not working after deployment when using custom router reuse strategy

### ISSUE THREAD

**Issue by mellunar** [angular/angular#47206]
### Which @angular/* package(s) are the source of the bug?

router

### Is this a regression?

No

### Description

I was working on a custom router reuse strategy that works locally with no issues, but when I deploy it to services like Cloudflare Pages, Vercel or Netlify, the app routing does not work. I click on router links to change the page, but the page component is not properly loaded, unless I reload on that route.

Code can be seen here, where it also works: https://stackblitz.com/edit/angular-ivy-khhfeq

Command line for deploying: `ng build --configuration production --base-href /`

### Please provide a link to a minimal reproduction of the bug

https://angular-router-reuse.pages.dev/

### Please provide the environment you discovered this bug in (run `ng version`)

```true
Angular CLI: 13.3.0
Node: 16.15.0
Package Manager: npm 8.3.1
OS: Windows 10 x64
```

**Comment by JoostK** [comment]
You're using the component's class name as a lookup key in the route reuse implementation:

```ts
const path = route.routeConfig.component.name;
```

In production builds however you'll find that class names will have been minified/mangled. In particular, class names are not guaranteed to be unique like they used to be (assuming classes are not declared in the same scope), which breaks the assumption of your route reuse implementation.

---

Unrelated, but your reuse strategy is also depending on private API, by accessing `DetachedRouteHandle.componentRef` in `deactivateOutlet`:

```ts
  private deactivateOutlet(handle) {
    const componentRef: ComponentRef<any> = handle.componentRef;
    if (componentRef) {
      componentRef.destroy();
    }
  }
```

This is accepted by TypeScript because `handle` is typed as `any` here, but accessing `componentRef` from `DetachedRouteHandle` is not guaranteed to work (since `DetachedRouteHandle` is an opaque type, meaning that it can store anything).
