### ISSUE TITLE
Alt + shift + key keydown combo should work on Mac

### ISSUE THREAD

**Issue by Jacobra93** [angular/angular#47256]
### Which @angular/* package(s) are the source of the bug?

core

### Is this a regression?

No

### Description

Trying to use HostListener and Angular pseudo events to listen to `window:keydown.alt.shift.d` on Mac. If you just have `window:keydown.alt.shift` without any extra combo, it works. Just stops working when you try to add any other key afterwards.

I see this other similar issue that looks like it was resolved:
https://github.com/angular/angular/issues/45992

But that issue was lacking as many combination keys as my issue. 

### Please provide a link to a minimal reproduction of the bug

https://stackblitz.com/edit/angular-mac-alt-shift-keydown-issue?file=src%2Fapp%2Fapp.component.ts,src%2Fapp%2Fapp.component.html

### Please provide the environment you discovered this bug in (run `ng version`)

```true
Angular CLI: 13.0.1
Node: 16.14.2
Package Manager: npm 8.5.4
OS: darwin x64

Angular:
...

Package                      Version
------------------------------------------------------
@angular-devkit/architect    0.1300.1 (cli-only)
@angular-devkit/core         13.0.1 (cli-only)
@angular-devkit/schematics   13.0.1 (cli-only)
@schematics/angular          13.0.1 (cli-only)
```

**Comment by jessicajaniuk** [comment]
This was resolved with 14.2, which was released in the last week. You can use `keydown.code.shiftleft.altleft.keyd` as your binding. This binds to the `code` field on the keyboard event rather than the `key` field and avoids the MacOS problem.  [The documentation](https://angular.io/guide/event-binding#binding-to-keyboard-events) has been updated to show how to properly use this new behavior. Once you update to latest, you should be good.
