### ISSUE TITLE
ngOnDestroy not called when component is created with createComponent

### ISSUE THREAD

**Issue by scaljeri** [angular/angular#47315]
### Which @angular/* package(s) are the source of the bug?

core

### Is this a regression?

No

### Description

This issue seems identical to [ComponentRef<T> onDestroyed() callback does not get called ](https://github.com/angular/angular/issues/39365) except that I create components dynamically with  `createComponent` instead of `ComponentFactoryResolver` . Here is my reproduction code:

    @Component({ ... })
    export class AppComponent implements AfterViewInit {
       @ViewChild('container') c: ElementRef;
       showFoo = true;

      constructor(
          private appRef: ApplicationRef,
          private injector: Injector,
          private envInjector: EnvironmentInjector ) {}

      ngAfterViewInit() {
          const ref = createComponent(FooComponent, {
             environmentInjector: this.envInjector,
             elementInjector: this.injector,
             hostElement: this.c.nativeElement,
         });

         this.appRef.attachView(ref.hostView);
      }

In the component's HTML I can remove the dynamically created component as follows

    <button (click)="showFoo = false">cleanup</button>

    <div *ngIf="showFoo" #container></div>

Now, when the `app-foo` component is removed from the view, its `ngOnDestroy` method is not called. This issue also occurs, for example, if the parent component is removed in which components were rendered this way (dynamically)
 

### Please provide a link to a minimal reproduction of the bug

https://stackblitz.com/edit/angular-ivy-zqbdsl?file=src%2Fapp%2Fapp.component.ts

### Please provide the environment you discovered this bug in (run `ng version`)

```true
Angular CLI: 14.2.0
```

**Comment by JoostK** [comment]
This seems to work as expected to me. A component that has been created and mounted through `createComponent` on top of a host element does not magically get destroyed whenever that host element is unmounted. You have to manage the lifecycle of the component and its view manually, unlike using `ViewContainerRef.createComponent` where the lifecycle is controlled by the `ViewContainerRef`.

**Comment by scaljeri** [comment]
Is there a way to connect the dynamically created component  to the lifecycle of its parent?

Calling the `ngOnDestroy` yourself is no problem, but if this component renders components too, I don't see how you can call those `ngOnDestroy` methods too?

Does this mean that in my case, I should use `ViewContainerRef.createComponent` instead of `createComponent`?

**Comment by JoostK** [comment]
The `createComponent` function returns a `ComponentRef` which has a `destroy` method; it will initiate proper destruction  of the view tree starting from that component.

"Connecting" lifecycles is typically achieved by storing the `ComponentRef` in a field and then destroying it in the `ngOnDestroy` hook of the component that created it. In your case this isn't quite correct as the view is attached to a host element inside an embedded view, where you'll want to connect it to the lifecycle of _that_ embedded view (instead of the whole component). To my knowledge there is no event for when an embedded view is restored, although you _could_ attach a directive to the host element such that the directive's `ngOnDestoy` becomes the hook to use.

I don't know why you're manually mounting a component instead of inserting it into/creating it from a `ViewContainerRef`, as the latter approach will naturally connect both the lifecycle hooks _and_ the change detector.

**Comment by scaljeri** [comment]
Thnx Joost, we're just a couple of kilometers apart :) 

I'm manually mounting because it looked much simpler than with `ViewContainerRef` and I did not realise/understand the differences between `createComponent` and `ViewContainerRef`. 

But, as you said, using `ref.destroy()` does exactly what I need, thanks for that ([demo](https://stackblitz.com/edit/angular-ivy-zqbdsl?file=src%2Fapp%2Fapp.component.ts,src%2Fapp%2Fapp.component.html,src%2Fapp%2Ffoo%2Ffoo.component.html))
