### ISSUE TITLE
docs: Horizontal alignment issue in https://angular.io/guide/what-is-angular angular

### ISSUE THREAD

**Issue by abergquist** [angular/angular#47423]
### Describe the problem that you experienced

Not a big issue, but thought I'd mention that there is a horizontal alignment issue in https://angular.io/guide/what-is-angular (angular / aio / content / guide / what-is-angular.md in angular:main).

The following pairs of text are not exactly horizontally aligned:

- '[ng build](https://angular.io/cli/build)' and 'Compiles an Angular app into an output directory.'
- '[ng serve](https://angular.io/cli/serve)' and 'Builds and serves your application, rebuilding on file changes.'
- '[ng generate](https://angular.io/cli/generate)' and 'Generates or modifies files based on a schematic.'
- '[ng test](https://angular.io/cli/test)' and 'Runs unit tests on a given project.'
- '[ng e2e](https://angular.io/cli/e2e)' and 'Builds and serves an Angular application, then runs end-to-end tests.'

### Enter the URL of the topic with the problem

https://angular.io/guide/what-is-angular

### Describe what you were looking for in the documentation

That the following pairs of text are exactly horizontally aligned:

- '[ng build](https://angular.io/cli/build)' and 'Compiles an Angular app into an output directory.'
- '[ng serve](https://angular.io/cli/serve)' and 'Builds and serves your application, rebuilding on file changes.'
- '[ng generate](https://angular.io/cli/generate)' and 'Generates or modifies files based on a schematic.'
- '[ng test](https://angular.io/cli/test)' and 'Runs unit tests on a given project.'
- '[ng e2e](https://angular.io/cli/e2e)' and 'Builds and serves an Angular application, then runs end-to-end tests.'
![Angular CLI](https://user-images.githubusercontent.com/7118508/190003680-a4082989-1651-482b-b2fc-2b1893ed6fc1.png)

### Describe the actions that led you to experience the problem

I went to https://angular.io/guide/what-is-angular and noticed the lack of horizontal alignment.

I'm including another screen shot from the same page because it also displays/illustrates the same lack of horizontal alignment.
![First-party libraries](https://user-images.githubusercontent.com/7118508/190004455-1b3524ab-4fa4-485a-b9d2-7d1ac302c5dd.png)

### Add a screenshot if that helps illustrate the problem

![Angular CLI](https://user-images.githubusercontent.com/7118508/190004574-1ff82151-27fd-4f9f-993b-ceccc1e89a6b.png)
![First-party libraries](https://user-images.githubusercontent.com/7118508/190004594-0c07c47d-14f1-482b-8e23-13c7d2230c3c.png)

### Provide any additional information here in as much as detail as you can

```true
I had done a quick right-click and Inspect; it appears that the issue can easily be resolved if you eliminate the following line from _typography.scss:

    vertical-align: top;

What I don't know, though, is if doing that adversely affect anything else.

Having both columns be horizontally aligned along their centers would be the ideal.
```

**Comment by dario-piotrowicz** [comment]
Hi @abergquist I've created a PR for this I hope you don't mind :slightly_smiling_face: 

However I think that the right solution here is to use `text-top` instead of completely remove the vertical alignment, as your solution would change how the tables look (breaking the design).

What I mean is that this is how the tables look now:
![Screenshot at 2022-09-15 22-34-35](https://user-images.githubusercontent.com/61631103/190514553-327ea3f8-1d64-4053-85ce-a9140081dab5.png)

This is how they look if we removed the vertical alignment:
![Screenshot at 2022-09-15 22-34-52](https://user-images.githubusercontent.com/61631103/190514748-3ffa3d92-a9dd-4063-b80e-4c23ae015d0f.png)

(not that the vertical alignment is anyways lost when we have multiple rows)

And this is how they look with `text-top`:
![Screenshot at 2022-09-15 22-35-08](https://user-images.githubusercontent.com/61631103/190514878-19794540-60c6-4681-80fb-f452051598b9.png)

I believe that this is the nicest way to fix your issue without breaking/changing the designs :slightly_smiling_face: 

What do you think? :slightly_smiling_face:

**Comment by dario-piotrowicz** [comment]
by the way, also the removal of the vertical alignment can really create a big difference in other tables, for example here:
![Screenshot at 2022-09-15 22-50-21](https://user-images.githubusercontent.com/61631103/190515322-fbc32519-e15f-4c61-89da-7a15d25529ab.png)

versus:
![Screenshot at 2022-09-15 22-50-33](https://user-images.githubusercontent.com/61631103/190515330-cde2d967-86ac-4702-8ca5-f070c1308e5f.png)

**Comment by abergquist** [comment]
Yes, [dario-piotrowicz](https://github.com/dario-piotrowicz); yours is a wonderful idea. Can we go with that?
