### ISSUE TITLE
@angular/router: ActivatedRoute.snapshot.title is always undefined

### ISSUE THREAD

**Issue by markostanimirovic** [angular/angular#47459]
### Which @angular/* package(s) are the source of the bug?

router

### Is this a regression?

No

### Description

When the title is added as follows:

```ts
{
  path: '',
  component: HelloComponent,
  title: 'HELLO',
}
```

and we try to access it via `route.snapshot.title`:

 ```ts
export class HelloComponent implements OnInit {
  constructor(private readonly route: ActivatedRoute) {}

  ngOnInit(): void {
    console.log(this.route.snapshot.title); // undefined
  }
}
```

it will be `undefined`. However, we can still get the route title from `route.snapshot.data`:

```ts
const routeTitleKey = Object
  .getOwnPropertySymbols(this.route.snapshot.data)
  .find((symbol) => symbol.toString() === 'Symbol(RouteTitle)');

console.log(this.route.snapshot.data[routeTitleKey]); // HELLO
```

### Please provide a link to a minimal reproduction of the bug

https://stackblitz.com/edit/angular-ivy-hqjky1?file=src%2Fapp%2Fhello.component.ts

### Please provide the environment you discovered this bug in (run `ng version`)

```true
Angular 14.2.2
```

**Comment by atscott** [comment]
Confirmed. This isn't working because the title is treated as resolved data, which is mutated on the snapshot and not available at the time of class creation. Fixing this will technically be a breaking change (since there's no way to have an optional getter function) so it won't be available until v15. In the meantime, you can use the `Observable` title on `ActivatedRoute` to get the correct value.
