### ISSUE TITLE
Usage of ChangeDetectionStrategy.OnPush

### ISSUE THREAD

**Issue by rosendi** [angular/angular#4746]
I've just read article by @vsavkin "CHANGE DETECTION IN ANGULAR 2" and I'am little bit confused on the usage of `ChangeDetectionStrategy.OnPush`. As I understood component has to be changed if and only if the some property has been replaced. But in the example below the result is list of Dimitri and Laura divs, although `names` array hasn't been replaced.

```
@Component({
  selector: 'app',
  changeDetection: ChangeDetectionStrategy.OnPush
})

@View({
  template: `
    <div *ng-for="#name of names">{{ name.name }}</div>
  `
})

class App {
  @Input() names: { name: string } = { name: "Dimitri" }

  constructor() {
    setTimeout(() => {
      this.models.push({ name: "Laura" });
    }, 1000)
  }
}
```

**Comment by rolandjitsu** [comment]
`this.models` is probably `this.names`. Also `@Input() names: { name: string } = { name: "Dimitri" }` if `names` is an array, would be better defined as `@Input() names: { name: string }[] = [{ name: "Dimitri" }]`. And the array has been modified whenever you do a `.push()` or things that alter the array, so that would in theory trigger the change detection.

**Comment by rosendi** [comment]
I've tried many variants in order to understand how change detection works, so sorry for small bugs. According to article OnPush strategy forces that component depends only on its input properties, and they are immutable.  Therefore `names` should be immutable, for example `Immutable.List<String>`. Immutable data cannot be changed once created, push instead return a new immutable collection. 

```
  this.names = this.name.push({ name: "Laura" })
```

In my previous example I use mutable collection with `ChangeDetectionStrategy.OnPush`. If I understand it correctly, change detection occurs only if the some property (`names` in our case) has been replaced, not mutated.

**Comment by rosendi** [comment]
just found a live example from angular source code - http://plnkr.co/edit/GC512b?p=preview.

**Comment by rolandjitsu** [comment]
Yes, but doing `this.names = this.names.push({ name: "Laura" })` is actually changing the input, so that would trigger the change detection, but simply doing `this.names.push({ name: "Laura" })` should not if the definition says that it will not act on changes to the data as it is expected to be immutable.

**Comment by rolandjitsu** [comment]
In the example you posted `this.ref.markForCheck();` manually triggers the change detection. Actually it just lets angular know that when the next event occurs in the current zone, it should trigger a change on the components that are marked for check. At least that is my understanding. You can also see a bit more [here](https://github.com/angular/angular/blob/b96784756ced8ae5caf8ad9a3a61206372c23baf/modules/angular2/src/core/change_detection/change_detector_ref.ts), maybe this will be of more use.

**Comment by rosendi** [comment]
@rolandjitsu have u read the article by @vsavkin "CHANGE DETECTION IN ANGULAR 2"?

Here is an example with immutable structures http://plnkr.co/edit/oT8F8m?p=preview. Change detection occurs only if I manually call `markForCheck()` after data property has been replaced. Maybe I'm wrong, however OnPush strategy should detect input replacement automatically. Please, take a look at the example.

**Comment by rolandjitsu** [comment]
@rosendi yes, I have :) You are right, it should trigger change detection if you replace the input (value). It may be a bug as @mhevery has labeled this, but it may also be expected behaviour. @vsavkin can surely tell us what is going on there.

**Comment by rosendi** [comment]
@rolandjitsu Have a look at the new plunk (http://plnkr.co/edit/9WaxndBHzjT5SrvilRKd?p=preview).

It has two components named `Parent` and `Child`. The `Parent` component is a host component that fils in the data (`characters` in our case). The `Child` component has a bound (here is where a binding occurs `<child [characters]='characters'>`) input property `characters`. I purposely use mutable data structures to track that object mutation on `OnPush` strategy doesn’t trigger any change detection. In this scenario `OnPush` strategy works as expected viz. component has to be changed if and only if some property has been replaced.

The issue still couldn't be closed since in the previous plunk (http://plnkr.co/edit/oT8F8m?p=preview) replacing an object  entirely in `Child` component (`Cmp` named there) doesn’t trigger change detection, and it might be unexpected behavior. 

@vsavkin Could you clear it out?

**Comment by vicb** [comment]
With the `OnPush`strategy, the component will be checked once and the mode will be set to `Checked`. It will then [not be checked](https://github.com/angular/angular/blob/785abe5a1d035beb78aa9e7bcc9f2625c12404db/modules/angular2/src/core/change_detection/abstract_change_detector.ts#L82) before `markForCheck()` is called. This is what you observe in your first examples.

I believe the last example (Parent / Child / ng-for) works because the `NgFor` itself uses the default strategy - not because of the `Child`.

I think you are expecting a behavior similar as `OnPushObserve` (ie running the cd only when the property triggers a change event) but this is implemented for Dart only ATM.

I agree that the name (`OnPush`) might be confusing and @vsavkin could probably clarify this. We must also work on improving the documentation in this area.

**Comment by vicb** [comment]
@rosendi to answer your last comment: `OnPush` will only trigger change detection when an input property has been changed as the result of changing the change detection.

In your first plunk, you have `<child [characters]='characters'></child>` so when `characters` (of Parent) is updated, this will [trigger the check for the Child](https://github.com/angular/angular/blob/de6774cd97b9cc69441b633f2ca3cfa82cb6ab5c/modules/angular2/src/core/change_detection/dynamic_change_detector.ts#L155).

In your second plunk there is no way to know that the input has changed (because we do not dirty check the `Child` unless input properties have changed) and you should call `markAsCheckOnce()` to explicitely trigger the change detection.

One last thing: if the `Child`changes as a result of an event, ng2 would [automatically dirty check it.](https://github.com/angular/angular/blob/de6774cd97b9cc69441b633f2ca3cfa82cb6ab5c/modules/angular2/src/core/change_detection/dynamic_change_detector.ts#L61).

Hopefully this answers all your questions.

**Comment by rosendi** [comment]
@vicb thank you for your detailed explanation! I close the discussion now until there is no improved documentation.

**Comment by rlegrand** [comment]
Hi,
Could someone tell me more about CheckOnce and Checked, I don't find any information about that. 
Is it only used internally and should we only consider Detached/OnPush/CheckAlways?

Thanks in advance

**Comment by ericmartinezr** [comment]
@rlegrand read this comment https://github.com/angular/angular/issues/7311#issuecomment-189418835

**Comment by rlegrand** [comment]
@ericmartinezr Ok thanks!
