### ISSUE TITLE
ComponentRef setInputs support

### ISSUE THREAD

**Issue by AsmisAlan** [angular/angular#47506]
### Which @angular/* package(s) are relevant/related to the feature request?

@angular/core

### Description

Hi! angular team! 

In the last angular release you added a new method to the ComponentRef called "SetInput" that allows to change **one** input property of the component. 

 This new feature works well, but when we need to update more than one input "at the same time" the ngOnChanges is executed multiple times (one for each property updated). 

### Proposed solution

I propose to change the method input in order to allow a Record (where the key is the name of the property) and of course rename the method to "setInput**s**". 

### Alternatives considered

No alternatives for now.

**Comment by pkozlowski-opensource** [comment]
This feature requests is build on the assumptions that doesn't hold true.

> This new feature works well, but when we need to update more than one input "at the same time" the ngOnChanges is executed multiple times (one for each property updated).

This is not what happens - you can set as many inputs (via setInput) as many times as you need. The `ngOnChanges` hook runs _only once_ when change detection runs, see:
https://stackblitz.com/edit/angular-standalone-zlpq7n?file=src%2Fmain.ts

I'm going to mark this as "needs reproduction" since the current behaviour of the framework seems to be expected and correct.

**Comment by pkozlowski-opensource** [comment]
@AsmisAlan I haven't heard back from you and according to my reproduction stackblitz things work as intended. I'm going to close this issue for now but happy to reopen if / when you've got more info.
