### ISSUE TITLE
Reactive Form - Formbuilder section

### ISSUE THREAD

**Issue by jtc10005** [angular/angular#47535]
### Describe the problem that you experienced

In angular.io's guide on reactive-forms the formbuilder service section has text that is cut off. 
You can highlight and the text will scroll to the right, but there are no scroll bars.
![image](https://user-images.githubusercontent.com/16569775/192038897-1d17b89e-0818-43ef-a73f-418b338ae620.png)

I tried to search for open issues about this but did not find any.
I also did verify that my screen resolution did not seem to have any impact.

### Enter the URL of the topic with the problem

https://angular.io/guide/reactive-forms#using-the-formbuilder-service-to-generate-controls

### Describe what you were looking for in the documentation

Just trying to read all of the text for the FormBuilder service section.

### Describe the actions that led you to experience the problem

Trying to research FormBuilder service implimentation.

### Add a screenshot if that helps illustrate the problem

![image](https://user-images.githubusercontent.com/16569775/192039022-dba0362f-a240-4051-8b9f-c47690977444.png)

**Comment by geromegrignon** [comment]
It sounds like it's due to mat-group-header on code snippets.
By removing it, it's fine.

<img width="728" alt="image" src="https://user-images.githubusercontent.com/32737308/192147491-3ad10852-add1-4aae-a6ea-031c126fdadf.png">

**Comment by MuhammadAakash** [comment]
@geromegrignon 
I would like to work on this issue.

**Comment by geromegrignon** [comment]
Hi @MuhammadAakash, I just commented on this issue to help, and I'm not part of the Angular team.
But as they added a 'help wanted' tag, sure go ahead. Thanks for bringing your help too!

**Comment by MuhammadAakash** [comment]
Sure, @geromegrignon 
Thanks for mentioning it, I will start working on this.
And also can you please mention the file name where changes are needed? It helps me a lot while working on it.

**Comment by geromegrignon** [comment]
The documentation markdown file is this one: https://raw.githubusercontent.com/angular/angular/main/aio/content/guide/reactive-forms.md

It contains the code snippet part:

```html
<code-tabs> <code-pane header="src/app/profile-editor/profile-editor.component.ts (instances)" path="reactive-forms/src/app/profile-editor/profile-editor.component.1.ts" region="formgroup-compare"></code-pane> <code-pane header="src/app/profile-editor/profile-editor.component.ts (form builder)" path="reactive-forms/src/app/profile-editor/profile-editor.component.2.ts" region="formgroup-compare"></code-pane> </code-tabs>
```

You will find documentation about code-tabs here: https://github.com/angular/angular/blob/main/aio/content/guide/docs-style-guide.md#code-tabs

Hope it'll help, find it by exploring the project.

**Comment by MuhammadAakash** [comment]
Thanks, @geromegrignon  sir for the help. I will start exploring the project after cloning it.

**Comment by MuhammadAakash** [comment]
Hi @geromegrignon.
Can you please give me some hints about what should I do because this is just a markdown file and the text which is cutting is just simple text.
Thanks.

**Comment by MuhammadAakash** [comment]
Hi @geromegrignon, @dylhunn 
Gerome You were right, this problem is on tabs. I have tested it with a single code snippet and it's working fine.
So, now what should I do, as mentioned in the doc we are comparing the form builder with manually created instances, so in this case, both tabs are required. And if we think to add any other solution where we compare both, according to me we should have to change the tabs into two different code snippets.
Is there any other approach that I am not thinking about? 
Please guide me further on this

**Comment by MuhammadAakash** [comment]
Hi @jessicajaniuk Can you please assist me furture on this issue, becuase I haven't got reply from @geromegrignon and @dylhunn

**Comment by geromegrignon** [comment]
Hi @MuhammadAakash.
In my opinion the solution is about updating the css part, not about changing the content itself.

**Comment by MuhammadAakash** [comment]
@geromegrignon 
yeah sure.

**Comment by jroxbury** [comment]
It seems the problem is that tables by default have table-layout: "auto" which will adjust to the size of the content in a cell. So, if a cell is bigger than the main container the table will overflow. 

The problem with mat-table-header is that it needs it's parent to be a fix width. A table with `table-layout: auto`, that is not the case, the table will grow to be same size as child. To show the pagination, mat table header compares the child to the host element. 
this.tabListInner.nativeElement.scrollWidth > this.elementRef.nativeElement.offsetWidth;

One option to fix this is to set the table layout to fixed, make table 100% so it doesn't overflow main container, set the first column width to something reasonable like 10% and then add word-break so large words don't overflow.  

I would be curious if anyone else knows any tricks to keep the table width fixed but have that column use auto scaling.
```
table {
    table-layout: fixed;
    width: 100%;
}

th {
   width: 10%;
   word-break: break-all; 
}
```
This is with fixed layout changes.
![table-layout-fixed](https://user-images.githubusercontent.com/11640126/202927184-536f7fae-c805-4c4b-93e4-54e07f99352b.jpg)


Maybe we need a different design, it seems like have large tab component in table doesn't work great.

I noticed a few other places at certain resolution where there is a similar problem.

1. Grouping form controls
![Grouping form controls](https://user-images.githubusercontent.com/11640126/202925999-642114ab-56a3-4f27-8245-46cb612d37b5.jpg)

2. Using the FormBuilder service to generate controls
![Using the FormBuilder service to generate controls](https://user-images.githubusercontent.com/11640126/202926003-742ee818-01b8-497b-952f-a7c330d924d7.jpg)

3. Creating dynamic form
![Creating dynamic forms](https://user-images.githubusercontent.com/11640126/202926013-fc883051-4298-4ea5-a289-418f4726a631.jpg)

**Comment by JeanMeche** [comment]
We're looking at deprecating the angular.io documentation in favor of https://angular.dev. 

Feel free to open an issue dedicated for the new doc site if you have suggestions, thank you.
