### ISSUE TITLE
*ngif (observable | async) cannot display Dom after add pipe() to observable

### ISSUE THREAD

**Issue by tonyshare** [angular/angular#47587]
### Which @angular/* package(s) are the source of the bug?

common, core

### Is this a regression?

No

### Description

In the following component I create a `inferReady` subject variable, and two observable function, if `inferReady` add `pipe()`. The html Dom will not be displayed in browser. Is it a bug of angular?

```
@Component({
  selector: 'my-app',
  template: `
    <p *ngIf="inferRight(1) | async">this can be displayed</p> 
    <p *ngIf="inferError(1) | async">this cannot be displayed</p> 
  `,
  styleUrls: [ './app.component.css' ]
})
export class AppComponent implements AfterViewInit {
  public inferReady = new Subject<boolean>();


  ngAfterViewInit() {
    this.inferReady.next(true);
  }

  inferError(id: number): Observable<boolean> {
    return this.inferReady.pipe(
      switchMap(() => {return of(true)})
    )
  }

  inferRight(id: number): Observable<boolean> {
    return this.inferReady;
  }
}
```

I compared two functions, `inferError` didn't work, the `inferRight` is correct. I confused with this, what's the difference between the two function?

### Please provide a link to a minimal reproduction of the bug

 https://stackblitz.com/edit/angular-ivy-ngif-async-example-cugjrx?file=src%2Fapp%2Fapp.component.ts

### Please provide the exception or error you saw

```true
There is no exception related to this bug.
```

### Please provide the environment you discovered this bug in (run `ng version`)

```true
Angular CLI: 10.2.4
Node: 12.22.9
OS: linux x64

Angular: 10.2.5
... animations, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router
Ivy Workspace: Yes

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1002.4
@angular-devkit/build-angular   0.1002.4
@angular-devkit/core            10.2.4
@angular-devkit/schematics      10.2.4
@angular/cli                    10.2.4
@schematics/angular             10.2.4
@schematics/update              0.1002.4
rxjs                            6.5.5
typescript                      4.0.8
```

**Comment by alxhub** [comment]
Angular is working as intended here. The example has the same fatal problem as #47484 (which I describe [here](https://github.com/angular/angular/issues/47484#issuecomment-1251315810)): `inferError` creates a new `Observable` _every time it is called_, which happens on every change detection. So the `async` pipe can never render a value, because every time the `Observable` emits, change detection runs, `inferError` runs again and returns a different `Observable` for the `async` pipe to subscribe to.

**Comment by tonyshare** [comment]
@alxhub but the `inferRight ` running right, only add after pipe() it get no value?

**Comment by tonyshare** [comment]
@alxhub the problem #47484 is not the same as my question, my question has no errors in the console, can you take serious at my question?

**Comment by JoostK** [comment]
> @alxhub the problem #47484 is not the same as my question, my question has no errors in the console, can you take serious at my question?

Alex's answer is entirely accurate here; `inferReady` might emit at one point in time (but never more than once) but `inferError` is resubscribed each and every time again (because a new `Observable` instance is created in `inferError`) but the timeout signal is never resubmitted, so Angular will never witness that signal.
