### ISSUE TITLE
[Alpha 42][Router] Query Param String "1" and Arrays

### ISSUE THREAD

**Issue by binarious** [angular/angular#4760]
**Potential Bug**:
The string `"1"` results in query param value `true`:
```js
this.router.navigate([
    '/UserList',
    {page: '1'}
]);

// --> /users/?page      (actual)
// --> /users/?page=1  (expected)
```

**Question**:
*Update: Duplicate of https://github.com/angular/angular/issues/2959*.
Is it intended that more complex query params aren't supported? Example:
```js
this.router.navigate([
    '/UserList',
    {
        filtering: {
            name: 'Andrew',
            age: 22
        }
    }
]);

// --> /users/?filtering=[object%20Object]                 (actual)
// --> /users/?filtering[name]=Andrew&filtering[age]=22  (expected)
```

**Comment by btford** [comment]
The first looks like a legit issue, the second is not implemented yet– there's another open issue on passing complex objects as params in navigation.

**Comment by marcalj** [comment]
With my experience, since every backend language use a different deserialization logic for query string (and you can use your own), it's better to pass one single param on query string with the complex object in JSON encoded string.

Thanks! :)

**Comment by ocombe** [comment]
In the same idea, I have a problem with some "special" characters:
`this.router.navigate(['./Show', {id: "The Player (2015)"]);`
---> works on first try
---> doesn't work on page refresh returns "The Player " (instead of "The Player (2015)")

And when I try to URI encode them:
`this.router.navigate(['./Show', {id: encodeURIComponent("The Player (2015)")]);`
---> doesn't works on first try (route params return "The%20Player%20")
---> doesn't work on page refresh returns "The%20Player%20" (instead of "The%20Player%20(2015)")

**Comment by binarious** [comment]
This is a duplicate of the recently fixed https://github.com/angular/angular/issues/5346.
