### ISSUE TITLE
Implementation of ng-for to only render in DOM the rows shown

### ISSUE THREAD

**Issue by danicomas** [angular/angular#4773]
In mobiles the performance is much better if only we render the items that we need. It would be amazing for lists with a lot of rows.

Look a the implementation of ionic collection-repeat in ng1: https://github.com/driftyco/ionic/blob/af1bfef327e685585244c6051c4d38b98aa6c62a/js/angular/directive/collectionRepeat.js

@adamdbradley @perrygovier @mhevery

**Comment by mhevery** [comment]
That would be amazing, but unfortunately there is no easy way to know when something is below fold. Ionic can guess on that because it controls the whole rendering and it knows how big the rows are. The only way for ng-repeat to know that would be to run the browser layout engine, which is extremely expensive. 

It is unlikely that we will be able to deliver such a feature.
