### ISSUE TITLE
string and RegExp are not logically consistent

### ISSUE THREAD

**Issue by xiexiaobo135** [angular/angular#47802]
### Which @angular/* package(s) are the source of the bug?

forms

### Is this a regression?

No

### Description

https://github.com/angular/angular/blob/0d65e1de2c8ea76a5e48df227638cdeabac82c42/packages/forms/src/validators.ts#L534
Hello~
```
let test1 = "\\d{2}";
let test2 = /\d{2}/;  // or new RegExp(test1)
...
Validators.pattern(test1);
// !==, without ^ and $ ??? Do string and RegExp need to be consistent?
Validators.pattern(test2);
```

### Please provide a link to a minimal reproduction of the bug

https://github.com/angular/angular/blob/0d65e1de2c8ea76a5e48df227638cdeabac82c42/packages/forms/src/validators.ts#L548

### Please provide the environment you discovered this bug in (run `ng version`)

```true
Angular CLI: 14.2.6
Node: 16.14.2
Package Manager: npm 8.19.2
OS: win32 x64

Angular: 14.2.6
... animations, cli, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1402.6
@angular-devkit/build-angular   14.2.6
@angular-devkit/core            14.2.6
@angular-devkit/schematics      14.2.6
@schematics/angular             14.2.6
rxjs                            7.5.7
typescript                      4.7.4
```

**Comment by JoostK** [comment]
This is working as documented:

https://github.com/angular/angular/blob/4e46370a44cecf54a28f6880150a94cc045f7a4f/packages/forms/src/validators.ts#L381-L384

Regex support was requested in #10150 and implemented in #12323 precisely to differentiate between the `^` and `$` prefix/suffix that would otherwise get added automatically for strings, as mirrored from the HTML5 `pattern` validation attribute for inputs. [Described on MDN](https://developer.mozilla.org/en-US/docs/Web/HTML/Attributes/pattern#constraint_validation) as follows:

>  The pattern's regular expression, when matched against the value, must have its start anchored to the start of the string and its end anchored to the end of the string, which is slightly different from JavaScript regular expressions: in the case of pattern attribute, we are matching against the entire value, not just any subset, as if a ^(?: were implied at the start of the pattern and )$ at the end.

So yes, the difference is intentional.
