### ISSUE TITLE
Dynamic component broken when using Standalone + aot: false 

### ISSUE THREAD

**Issue by JeanMeche** [angular/angular#47996]
### Which @angular/* package(s) are the source of the bug?

compiler

### Is this a regression?

No

### Description

Suppose this single standalone component with a dynamic component inside : 

```
@Component({
  selector: "app-root",
  template: "<div #container>OK</div>",
  standalone: true,
})
export class AppComponent implements OnInit {
  @ViewChild("container", { read: ViewContainerRef, static: true })
  container!: ViewContainerRef;

  ngOnInit() {
    const component = Component({
      template: "test no",
      styles: [":host {color: red; padding-left: 8px; display:block; }"],
    })(class {});
    this.container.createComponent(component);
  }
}
```

With `aot: false`, we get an error : `The component '' needs to be compiled using the JIT compiler, but '@angular/compiler' is not available.` at runtime. 

**BUT**:
The error does not happen **IF** `platformBrowserDynamic().bootstrapModule({} as any)` is present in [main.ts](https://github.com/JeanMeche/angular-change-detection/blob/broken-standalone/src/main.ts) (but not called), everything works fine.

### Please provide a link to a minimal reproduction of the bug

https://github.com/JeanMeche/angular-change-detection/tree/broken-standalone

### Please provide the environment you discovered this bug in (run `ng version`)

```true
Angular 14.2.9
```

**Comment by JoostK** [comment]
I'm confused, this seems expected to me. The local, anonymous component declaration isn't supported for AOT compilation so it remains present for the JIT compiler to pick up, and the error is reported to indicate that the JIT compiler is not available.

Just the import from `@angular/platform-browser-dynamic` contains a transitive import for `@angular/compiler`, which contains a side-effectful module that makes the compiler available globally. So it's not because `platformBrowserDynamic().bootstrapModule({} as any)` is included in the bundle, but rather that an import for `@angular/platform-browser-dynamic` is present (the "dynamic" part in the platform-browser name refers to its behavior of bringing in the JIT compiler)

**Comment by JeanMeche** [comment]
Yeah, I had the feeling that a transitive import would  be the underlying reason. Thx for pointing it out. 

So this means, currently JIT compiling is not expected to work out of the box when using standalone components only. 

How would one, only import the compiler into a project ?

**Comment by JoostK** [comment]
> So this means, currently JIT compiling is not expected to work out of the box when using standalone components only.

I'm not sure what you mean by "standalone components", as it's not what Angular describes as its standalone components using the `standalone: true` flag.

> How would one, only import the compiler into a project ?

Using a direct import of `@angular/compiler`. Please be aware that including the JIT compiler has bundle size and performance overhead, as well as requiring the use of `eval` which introduces a security risk.

**Comment by alxhub** [comment]
This is working as intended - to disable AOT and use JIT compilation, the Angular compiler must be imported dynamically:

```typescript
import '@angular/compiler';
```
