### ISSUE TITLE
Improve errors for multiple template directives on one element

### ISSUE THREAD

**Issue by brandyscarney** [angular/angular#4817]
Using multiple template directives on the same element throws errors related to the code itself, but Angular doesn't report any errors.

Would be nice to have an error that tells us we can't use two template directives on one element.

See this comment: https://github.com/angular/angular/issues/4792#issuecomment-148867688
And this plunker: http://plnkr.co/edit/ozJydSz1XqiNtrVCUfm1?p=preview

**Comment by pkozlowski-opensource** [comment]
This is the same as #4246 and I believe it is fixed with the new compiler. Closing as duplicate / solved.

**Comment by zoechi** [comment]
@pkozlowski-opensource that doesn't seem to be the case. I tried in RC.1 and I don't get an error for `*ngFor` and `ngIf` on the same element but it also doesn't work properly.

In this Plunker https://plnkr.co/edit/fEXnRQ5ILVQteRJ30za0?p=preview the items are initially shown because the condition for `*ngIf` is `true`, when the button is clicked `show` becomes `false` and the items are hidden, but toggle back to `true` doesn't show them. 

I think it should throw but it doesn't.

**Comment by zoechi** [comment]
Plunker doesn't work for me today therefore I couldn't verify it in Plunker, only locally.
