### ISSUE TITLE
Number Pipe not working with persian numbers

### ISSUE THREAD

**Issue by hosseinGanjyar** [angular/angular#48250]
### Which @angular/* package(s) are the source of the bug?

common

### Is this a regression?

No

### Description

I have used number pipe for show list of numbers, but I have got a persian/farsi number like '۲۰' alongside other items in my data and got an error with type 'InvalidPipeArgument'.      
Is there a way to manage this non-english numbers?    
**I would not convert data before binding.**   

### Please provide a link to a minimal reproduction of the bug

https://stackblitz.com/edit/angular-ivy-n1wrjy

### Please provide the exception or error you saw

```true
ERROR
Error: NG02100: InvalidPipeArgument: '۲۰ is not a number' for pipe 'DecimalPipe'
```

### Please provide the environment you discovered this bug in (run `ng version`)

```true
Angular: 14.x
```

### Anything else?
update: I've solved this problem by add a function to my component:

```
 transformNonNumber(number: string): string {
    const persianNumbers = ['۰', '۱', '۲', '۳', '۴', '۵', '۶', '۷', '۸', '۹'];

    for (var i = 0; i < 10; i++) {
      let reg = new RegExp(persianNumbers[i], "g");
      number = number.replace(re, i.toString());
    }

    return number;
  }
```
Please add this method to number pipe for easier using in future. Thanks

**Comment by JeanMeche** [comment]
`NumberPipe` relies on `Number()` which doesn't support persian numbers: `Number("۲۰") // NaN`

I don't think the pipe will support it until there is native support (link for example with `Intl.NumberFormat()` : 

`new Intl.NumberFormat("fa").format("20") // '۲۰' `

**Comment by hosseinGanjyar** [comment]
@JeanMeche Thanks for reply, but as you seen I need to convert Persian number to the English number, so `new Intl.NumberFormat("fa").format("20") // '۲۰'` couldn't help in this situation.   

**I need a code like this:** 
`new Intl.NumberFormat("en").format("۲۰") // '20' , but output is Nan !`

**Comment by jnizet** [comment]
the number pipe *formats* numbers, in the JavaScript sense of the word "number". What you want is to *parse* a string to a number (that you can then format in another way).
The number pipe also doesn't support numbers formatted the English way. For example, pass it the string `'1,234.5'`, and it will fail too.

**Comment by hosseinGanjyar** [comment]
@jnizet but I don't want to convert a type of number for example Decimal, I want to convert a number from another language (Persian) to the English one.   
"۲۰" => "20"

**Comment by jnizet** [comment]
@hosseinGanjyar that's fine, and you're free to do that, but just don't expect the number pipe to do that for you, because it's purpose is to *format* a JavaScript number. Not to *parse* a string representing a number in Persian. So it's not the right tool for the job. Just like you wouldn't take a car to cross the sea. You would need a boat to do that.

**Comment by hosseinGanjyar** [comment]
@jnizet right, but I think Angular could handle this exception inside their core code. If there is a way for me to do this, help me.

**Comment by pkozlowski-opensource** [comment]
>  I don't want to convert a type of number for example Decimal, I want to convert a number from another language (Persian) to the English one. "۲۰" => "20"

@hosseinGanjyar what is going on here is that you are providing JavaScript string _representing_ a number. The number formatting pipe is supposed to work with numbers (that is JavaScript objects of type number). It [does have some logic to deal with strings](https://github.com/angular/angular/blob/main/packages/common/src/pipes/number_pipe.ts#L303-L315) but this is very simplistic and I wish we haven't had it in the first place. In any case this logic is limited to what native JavaScript `Number(...)` call can handle.

What you are looking for is the _parsing_ functionality and this is outside of the scope of the existing _formatting_ pipe. You would have to parse things on your end, potentially using a 3rd party library: https://stackoverflow.com/questions/55364947/is-there-any-javascript-standard-api-to-parse-to-number-according-to-locale

Going to close this issue here as parsing numbers in any locale is not something we plan to support in the framework.
