### ISSUE TITLE
Rework bootstrapping, imports and bundles.

### ISSUE THREAD

**Issue by mhevery** [angular/angular#4834]
Full [design doc](https://docs.google.com/document/d/1rbVTKTYLz6p2smQNYI8h4-QN-m2PS6F3iQIDmSzn0Ww/edit#heading=h.6cxvr9awtf5r).

- [x] Support configuring of platform Directives/Pipes. #4857
- [x] Have `PlatformRef` inject `EAGER_SERVICES` so that we can auto-init `Reflector`
- [x] Refactor so that we bootstrap using DI bundles.
  - [x] `boostrap(c, b) => platform([BROWSER]).application([HTTP, ROUTER, b]).component(c)`
- [x] Realign imports
  - [x] ~~Rename all `FOO_PROVIDERS` to `FOO`. (to make the bootstrap process less verbose)~~ **Update: we decided not to do this**
  - [x] Move imports per this [spreadsheet](https://docs.google.com/spreadsheets/d/1XO0WjhRF8JR3NcxwevlsG1Qiunu9LP28rgbrDNCKYQc/edit#gid=808327765).
- [x] Create platform bundles
  - [x] SFX bundles which exports to `ng` namespace in additive fashion.
  - [x] commonJS bundle.
  - [x] all bundle which contains `bootstrap`

**Comment by pkozlowski-opensource** [comment]
I believe that our UMD bundles could replace the current SFX bundles as they are already doing what is described in this issue. I would suggest "killing" our existing sfx bundles and keep umd ones only.

@IgorMinar I did some work on this topic and could continue, but maybe there is another plan here since it was assigned to you.

**Comment by pkozlowski-opensource** [comment]
I believe that this is now fixed via fb4f1e8dc9f3f8135b37f8b4dce7b7b7f74df96b - we've got one UMD bundle that acts as SFX, exports things on the ng.* namespace and works for browser platform.
