### ISSUE TITLE
Something goes wrong when I uglify my scripts

### ISSUE THREAD

**Issue by answer1991** [angular/angular#484]
Hi, 
my scripts works well before I `uglify` them, however,  it goes wrong when I run the `uglify` task. Flowing is my code.

![image](https://cloud.githubusercontent.com/assets/2566352/5937888/205498ee-a730-11e4-987c-23a4ffd26a4a.png)

![image](https://cloud.githubusercontent.com/assets/2566352/5937933/a08de196-a730-11e4-925c-e3b1609e620a.png)

![image](https://cloud.githubusercontent.com/assets/2566352/5937939/ae95b16a-a730-11e4-922b-8686326e388a.png)

Before I `uglify` my codes, it works very well.
![image](https://cloud.githubusercontent.com/assets/2566352/5937959/e0f99248-a730-11e4-8554-af01d8d6a396.png)

However, it goes wrong after I `uglify` my scripts.
![image](https://cloud.githubusercontent.com/assets/2566352/5937966/0f65a928-a731-11e4-9ff3-3f72365a638b.png)

![image](https://cloud.githubusercontent.com/assets/2566352/5937975/355bb2b2-a731-11e4-96b6-057d47ecdc37.png)

the code after `uglify`:

angular.module("ngtestApp").provider("testService",[function(){var a={};this.addPluginFactory=function(b,c){a[b]=c},this.$get=["$injector",function(b){var c={};return angular.forEach(a,function(a,d){c[d]=b.invoke(a)}),{getPlugin:function(a){return c[a]}}}]}]);

**Comment by caitp** [comment]
angular/angular is the new repository for work on the next version of angular, this is more for angular/angular.js.

Support questions should not be asked on github, as more in-depth, hands on and helpful support can be obtained on places like [#angularjs](http://webchat.freenode.net/?channels=angularjs) on freenode, or [stackoverflow](http://stackoverflow.com/questions/tagged/angularjs).

That said, the issue here is that you are not annotating the "plugins" you're registering in your config block. To solve this, it should look more like

```js
  testServiceProvider.addPluginFactory('hello', ['$log', function($log) {
    return {
      hello: function() {
        $log.log('hello');
      }
    };
  }]);

  testServiceProvider.addPluginFactory('hello2', ['$log', function($log) {
    return {
      hello: function() {
        $log.log('hello2');
      }
    };
  }]);
```
