### ISSUE TITLE
What are Angular Team recommendations about OnPush change detection strategy ?

### ISSUE THREAD

**Issue by jean-philippe-aubineau** [angular/angular#48467]
### Describe the problem that you experienced

Hi there,

Following some heated debates within our company regarding which Angular change detection strategy should be used by default in our applications, we cannot agree on which strategy to use.

Some argue for the use of the default change detection strategy (ChangeDetectionStrategy.Default) because it is the one offered by default by the framework.
Others argue instead for the use of the OnPush change detection strategy (ChangeDetectionStrategy.OnPush) on all components to optimize application performance.

What are the **best practices recommended** by the Angular development team **regarding change detection strategy**? Should we leave it as default or should we turn to the OnPush strategy?

Regards,

Jean-Philippe

**Comment by mlc-mlapis** [comment]
@jean-philippe-aubineau The default CD strategy was chosen for better comprehensibility for newcomers and not for better performance. The issue of changing the default settings to `OnPush`, or adding the possibility of changing the default settings for the entire project, has already been discussed several times. Still, no final decision has been taken in this direction.

**Comment by lukasmatta** [comment]
Hello, during the Angular v15 Launch Event, one of the viewers asked if the OnPush will ever become the default change detection strategy and Angular core team member Alex Rickabaugh gave an interesting answer:

https://www.youtube.com/watch?v=j2_NnV7nU6s&t=3356s

He said that usually, when there is a performance issue with an Angular app, it's because change detection is running too much, not because it's too expensive. From my experience, I agree with the statement.

It's also worth mentioning that according to the [Angular Roadmap](https://angular.io/guide/roadmap), we might expect improvements regarding the change detection performance.

**Comment by Wykks** [comment]
> He said that usually, when there is a performance issue with an Angular app, it's because change detection is running too much, not because it's too expensive. From my experience, I agree with the statement.

That's a weird answer. Because OnPush purpose is to actually mitigate the "change detection is running too much" issue

**Comment by pkozlowski-opensource** [comment]
As @lukasmatta pointed out we are unlikely to have a hard & fast rule along the lines of "always use X". Both strategies exist for a reason: OnPush trims component tree traversal when running change detection but it might shield components that are not designed to work within the OnPush parents.

We do recommend OnPush for "leaf" components / other components trees that are under your control. But this rule should be used in context.

**Comment by jean-philippe-aubineau** [comment]
Thanks guys for explanation 👍
