### ISSUE TITLE
Using animation params in states produces runtime build errors

### ISSUE THREAD

**Issue by bernatgy** [angular/angular#48565]
### Which @angular/* package(s) are the source of the bug?

animations, platform-browser

### Is this a regression?

No

### Description

Tried to follow the [reusable animations guide](https://angular.io/guide/reusable-animations), with the exception that I'm using states in my animations, which produces [undocumented](https://angular.io/errors) _NG03404_ & _NG03008_ error codes.

~~Defining defaults as a requirement is **in itself** undocumented, but the error remains the exact same even after defining them as the second parameter of `animation(...)` and also the second parameter of `useAnimation(...)`.~~

Same behavior on Angular 15, 14, 13 and 8.

### Please provide a link to a minimal reproduction of the bug

https://stackblitz.com/edit/angular-ivy-3a87uc?devToolsHeight=33&file=src/app/app.component.ts

### Please provide the exception or error you saw

```true
> RROR Error: Uncaught (in promise): Error: NG03404: The animation trigger "hintChanges" has failed to build due to the following errors:
> - NG03008: state("void", ...) must define default values for all the following style substitutions: velocity, fromColor
> - NG03008: state("*", ...) must define default values for all the following style substitutions: toColor
> - NG03008: state("void", ...) must define default values for all the following style substitutions: velocity, fromColor
> - NG03008: state("*", ...) must define default values for all the following style substitutions: toColor
```

### Please provide the environment you discovered this bug in (run `ng version`)

```true
Angular CLI: 14.2.7 (and the one on the repro)
Node: v18.12.0
Package Manager: yarn@3.2.4


"@angular/animations": "^14.2.8",
"@angular/common": "^14.2.8",
"@angular/compiler": "^14.2.8",
"@angular/core": "^14.2.8",
"@angular/platform-browser": "^14.2.8",
"@angular-devkit/build-angular": "^14.2.7",
"@angular/compiler-cli": "^14.2.8",
"typescript": "~4.6.4"
"ts-node": "~3.2.0",
```
```


### Anything else?

Worth mentioning, the default stackblitz angular project seems to have weird versions in it's package.json (both 15 and 14).

**Comment by dario-piotrowicz** [comment]
Hi @bernatgy I do think that what you're describing is indeed a bug but I am not really sure if it is a regression, I've copy-pasted your stackblitz and reproduced the same in [angular 13](https://stackblitz.com/edit/angular-13-bnh4vf) and [angular 8](https://stackblitz.com/edit/angular-8-app-example-ju25nr)

I think the bug you are pointing out here is that the params are not recognised when used in a `state`, if you use the params directly in transitions things do work ok, as you can see [here](https://stackblitz.com/edit/angular-ivy-6cxuxb?devToolsHeight=33&file=src%2Fapp%2Fanimations.ts) for example.

In the [reusable animations guide](https://angular.io/guide/reusable-animations) they are not using `state` which lead me to believe that maybe this never actually worked...

Anyways I just wanted to share my two cents to hope to clear some things up 🙂 (please let me know if you disagree 🙂)

I'll look into the bug at soon anyhow 🙂, if you agree with what I said I think it would be nice if you could update the issue's title/description accordingly 🙏

**Comment by bernatgy** [comment]
Hey!
Yeah I think you might be right!

My original use case was quite more complicated so I did narrow it down but obviously not enough to find the source of the issue here.
> Side note: I need to get a much better understanding of animations... didn't even think you could use it without states... though that seems to be a pretty limiting way to use them. But I digress, back to the point.

Gonna update the issue accordingly. 😄

**Comment by dario-piotrowicz** [comment]
Hey @bernatgy I've looked into things and I realized/remembered something.

I don't think that you should use `state` calls inside reusable animations since `useAnimation` sort of applies an actual animation when you call it, it is not a declarative tool like state (which you apply it and it applies its styles when Angular thinks it is more appropriate).

For example lets take this stackblitz: [trigger with states example](https://stackblitz.com/edit/angular-ivy-q3u9do?file=src%2Fapp%2Fapp.component.ts)

You can see that if we try to move the `state`s inside the reusable animation things stop working: [trigger with states in useAnimation](https://stackblitz.com/edit/angular-ivy-cxpswo?file=src%2Fapp%2Fapp.component.ts)
(note that there isn't even any param there at all)

So if you need to make `state`s reusable I believe that that needs to be done directly without using `useAnimation` for example in the following way: [trigger with reusable states](https://stackblitz.com/edit/angular-ivy-cx8tmi?file=src%2Fapp%2Fapp.component.ts)

___

So I think that the whole issue here is the use of the `state` inside the reusable animation and that should not be done (we should probably throw an error in that case to let the developer know of it instead)

what do you think? Could you refactor your code so that it doesn't contain the `state`s in the reusable animation?

**Comment by bernatgy** [comment]
Thank you for looking into it! I very much appreciate it.

Have to say, your explanation and reasoning still baffles me after re-reading the animation guides and what you wrote...
I can understand that... well, there's reasons. I do think this must be explained with a custom error message at the very least. Preferably - if there's a way - even changed, but if not, documented on the reusable animations page as well!

In the end, this usage turned out to be even more preferable to my specific use case though, which would be closer to a [solution like this](https://stackblitz.com/edit/angular-ivy-xwnj4l?file=src/app/animations.ts).
Couple of notes:
- `useAnimation( ... )` turned out to be completely useless in this, as it will not send the params over to the states, and the only thing it abstracts is an `animate( ... )` call, which now I can even make at the same place where the rest of the animation is located.
  - Guess I don't really understand why it exists, or didn't come across a real need for it.
  - Yes, I thought the only way to have params was to use `useAnimation( ... )`
    - _As context; I jumped from Angular 8 to 14 just a month ago, I don't think there were params yet then, or a way to consistently reuse animations._
> I sure hope this'll work in my environment too... didn't test yet.

**Comment by dario-piotrowicz** [comment]
@bernatgy I'm sorry my reasoning baffles you, I am not the one who wrote it so I may be wrong but based on past experiences with the animations package I do feel like things are actually how I've stated (but again, I may be just wrong) 🤷 

Regarding the error I do agree, I will look into it and see if it can be added, ideally I think that the state should have a type definition that is incompatible with the actual animation metadata so that typescript would right away complain about it, but I am quite sure that it is very much too late for that...

Regarding changing it, I am not sure about making it working (even if that were possible).... 
let's take for example the following:
```ts
  transition('* => *', [
    state('red', style({backgrundColor: 'red'})),
    state('green', style({backgroundColor: 'green'})),
    state('blue', style({backgrundColor: 'blue'})),
    animate(1000),
  ])
```
even if it worked as you'd expect I would find it like a very confusing (if not straight out wrong) piece of dsl, because to me it says something like this:
```
 - when transitioning from * to *
 - do:
    - when. the state is 'red'
       -  apply a red background
    - when. the state is 'green'
       - apply a green background
    - when the state is 'blue' 
       - apply a blue background
    - animate the state change
```
which to me it just feels quite wrong, and the code should instead be:
```ts
  state('red', style({backgrundColor: 'red'})),
  state('green', style({backgroundColor: 'green'})),
  state('blue', style({backgrundColor: 'blue'})),
  transition('* => *', [
    animate(1000),
  ])
```
which would translate to:
```
 - when. the state is 'red'
    -  apply a red background
 - when. the state is 'green'
    - apply a green background
 - when the state is 'blue' 
    - apply a blue background
 - when transitioning from * to *
    - animate the state change
```
which is much more clear and makes much more sense (to me)

(again above I am not mentioning the params as I think that those not working is just a side effect of the state not actually working like an "actual animation")
___

Regarding your solution, I do like it! 😃 silly me for not thinking of a factory function 😝 

Regarding why `animation` and `useAnimation` exist, I am not 100% sure, my best guess is that it is just a utility that helps you reuse animations without the need to create factory functions (which may start to become annoying if you need to apply params in the decorators?).... I think!?.... 🤷  

Please let me know if your solution works out fine 🙂

**Comment by bernatgy** [comment]
Hey!
Sorry for the delay, and thank you very much for your attention. Especially considering the timing! :)

Had the chance to test it out well enough and it does work out! Even in production builds, which was my main concern, but I guess since AOT by default and Ivy, there shouldn't have been any problems either way.

Not sure what should happen to the issue as both of our opinions on the matter require some sort of modification. You tell me!

**Comment by dario-piotrowicz** [comment]
Hey @bernatgy, no problem at all, I hope I did manage to be of any help 🙂 

I'm very glad you got things working! 😄 🥳 

I think I will try to see if I can get the states implementation a bit better so that at the very least it either works better or produces easy to understand warnings.

So, I think you could update this issue's title and description to something that conveys the following generic idea:
`Animation states produce unintuitive behaviors and can cause difficult to debug runtime errors`
and then I can see what I can do to improve the situation. Or you can close this issue (as not planned I guess) and I can create my own new issue (which can have a link to this one), I'm totally fine with both, do whatever you think is better 🙂

**Comment by bernatgy** [comment]
Hey, I think I'll just close this one, so you can "do your magic" on a clean plate.
Good luck, and thanks again!
