### ISSUE TITLE
Are there any plans to improve the Angular docs? It needs revision

### ISSUE THREAD

**Issue by tes-balo** [angular/angular#48626]
I find the current Angular docs to be unnecessarily complicated, especially for beginners. Some of the prominent issues I have faced with the website include:

* The Tour of Heroes tutorial assumes that the reader is familiar with the concept of Observables.

* Instead of briefly defining some concepts before using them, the tutorial just provides hyperlinks. These concepts include the **property-binding syntax** and **Input decorator**. A reader who's learning Angular should be told what these do in addition to placing links in case the reader wants to study them extensively.

* I often find myself googling some concepts which are poorly explained in the docs. For example, the documentation on `**Content Child**` says that "Content Child is used for getting the first element or the directive matching the selector from the content DOM". **What is the content DOM?** It doesn't say. To make things worse, it doesn't even say what  **Content Child** does in simple terms which is to **grab elements between the opening tags of a host element**. Similarly, View DOM is mentioned in the **View Child** documentation w/o stating what View DOM is.

* [SUGGESTION]: There should be a tutorial on building a CRUD app like a todo app in the docs too. This would be a nice way to introduce the strengths of Angular. Plus, this is how other frameworks like React present themselves.

The Angular docs should be thoroughly revised unless it is assumed that most readers come from professional backgrounds which I doubt is the case.
Angular is an interesting framework and it would be a shame if people shy away from it because the docs look scary.

**Comment by bob-watson** [comment]
Thanks for the feedback--and I agree completely.
So, the short answer to your question is, **Yes** there are plans to improve the docs, in general, and the learning Angular tutorials, specifically. 
We are in the process of creating a new tutorial series that addresses your concerns, which should be coming out later in Jan 2023.
I'll keep this issue open and assign it to me as I work on the new tutorials.

**Comment by EmixamZ** [comment]
Hi @bob-watson, 
Do you plan on writing the new tutorials based only on standalone components or will it still use angular modules?
Thank you in advance for your work !

**Comment by csisy** [comment]
I'd like to add to this topic.

The standalone components are not very well documented, and since it's already in stable, and lightly forced, I think its documentation should be extended. There is a migration guide and a brief explanation, but I personally miss some more advanced usage tips. To name a few:
- With `NgModule`s one could create a private component that is visible only in that module, [see FAQ](https://angular.io/guide/ngmodule-faq#what-should-i-export). Now, what is the proper way to solve this using standalone components?
- How do standalone components work as dynamically loaded components? Think of a dialog, for example.
- In addition to the previous one, should the user import XY module (e.g. `DialogModule`) in their standalone components?
- How to handle the previous `forRoot` pattern? Or how to enforce that the `EnvironmentProviders` are provided only once (and more importantly, in the bootstrapping section). For `NgModule`s, see [FAQ](https://angular.io/guide/ngmodule-faq#how-can-i-tell-if-an-ngmodule-or-service-was-previously-loaded) and [Guide](https://angular.io/guide/singleton-services#prevent-reimport-of-the-greetingmodule)

**Comment by alxhub** [comment]
Closing thanks to angular.dev ❤️
