### ISSUE TITLE
leave-animation not triggered when injecting ViewContainerRef into component

### ISSUE THREAD

**Issue by zetti-caletti** [angular/angular#48667]
### Which @angular/* package(s) are the source of the bug?

animations

### Is this a regression?

No

### Description

leave-animation not triggered when injecting ViewContainerRef into component. When commenting out the injection in the constructor, the leave-animation works as expected.

Tested it in Angular 15.04 and Angular 9.1.13. Both don't work.

### Please provide a link to a minimal reproduction of the bug

https://stackblitz.com/edit/angular-ivy-f8qyay

### Please provide the exception or error you saw

```true
No exceptions or errors.
```

### Please provide the environment you discovered this bug in (run `ng version`)

```true
Angular CLI: 15.0.4
Node: 16.16.0
Package Manager: npm 8.11.0
OS: linux x64

Angular: 15.0.4
... animations, cli, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, router
... service-worker

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1500.4
@angular-devkit/build-angular   15.0.4
@angular-devkit/core            15.0.4
@angular-devkit/schematics      15.0.4
@angular/cdk                    14.2.7
@angular/material               14.2.7
@angular/pwa                    0.5.3
@schematics/angular             15.0.4
rxjs                            7.4.0
typescript                      4.8.4
```

**Comment by JeanMeche** [comment]
I've got [another repro case](https://stackblitz.com/edit/angular-ivy-jfrjia). 

It's likely to come from : #28162

From what I get, this is because `isHostElement` is false here : 

https://github.com/angular/angular/blob/9fc950daaffb690852a9e6801328e6a0e8e9535e/packages/animations/browser/src/render/transition_animation_engine.ts#L756-L761

the false being set here : 

https://github.com/angular/angular/blob/9fc950daaffb690852a9e6801328e6a0e8e9535e/packages/core/src/render3/node_manipulation.ts#L63-L75
