### ISSUE TITLE
Current navigation is null in nested route since angular 15

### ISSUE THREAD

**Issue by molnarm** [angular/angular#48744]
### Which @angular/* package(s) are the source of the bug?

router

### Is this a regression?

Yes

### Description

When navigating to a route that is a child of another, `router.getCurrentNavigation` no longer has a value in the constructor of the child component.

Working in Angular 14: https://stackblitz.com/edit/angular-ivy-n1mf23 (click on the link on the root page, see message on the resulting page)

Broken in Angular 15: https://stackblitz.com/edit/angular-ivy-hx1q5h (click on the link on the root page, see no message on the resulting page)

I assume this has something to do with [one of the listed breaking changes](https://angular.io/guide/update-to-version-15#breaking-changes-in-angular-v15) in Angular 15, but that only mentions that it "could affect production code" without explanation or providing steps to fix.

### Please provide a link to a minimal reproduction of the bug

https://stackblitz.com/edit/angular-ivy-hx1q5h

### Please provide the environment you discovered this bug in (run `ng version`)

```true
See the stackblitzes above.
```

**Comment by JeanMeche** [comment]
Yeah, it seems the #46554 broke that. `router.getCurrentNavigation` returns `null` because the component is created after the navigation has ended.

**Comment by atscott** [comment]
That's correct, this is due to #46554. The breaking change note's example applies exactly to this situation (`getCurrentNavigation`) though it mistakenly was put with the test code sentence. The steps to fix vary based on use-case. In your case, all you're doing is getting the state from the navigation. Instead, you should retrieve this from [`Location.getState`](https://angular.io/api/common/Location#getState).
