### ISSUE TITLE
statusText of HttpErrorRespone is empty string in win10

### ISSUE THREAD

**Issue by G-Shriya** [angular/angular#48751]
### Describe the problem that you experienced

My organization uses angular 1.2.16. We are using "loginResult.statusText" to print an error message. But the statusText is empty in Win10 but gives the expected output in Win7(statustext is not empty in win7). 

loginResult(in win10) is something like this:

![image](https://user-images.githubusercontent.com/71445998/212743661-b4fd8fed-7379-472d-9fe4-6337b71092d1.png)

I need to understand why statusText prints correct msg in win7 but an empty string in win10.

### Describe what you were looking for in the documentation

I was looking for statusText of HttpErrorResponse being sensitive to OS. (Win 7 and Win 10). I could not find any relationship between os and statustext.

### If the problem is browser-specific, please specify the device, OS, browser, and version

```true
OS: Win 10
browser: chrome and edge
version angular: 1.2.16
```

**Comment by JoostK** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).

---

`statusText` is directly taken from the `XMLHttpRequest`, any difference in behavior is not caused by Angular's HttpClient. Please see e.g. [this SO post](https://stackoverflow.com/questions/41632077/why-is-the-statustext-of-my-xhr-empty) for potentials reasons.
