### ISSUE TITLE
provideRouter: there is no option for `errorHandler`

### ISSUE THREAD

**Issue by CSchulz** [angular/angular#48759]
### Which @angular/* package(s) are relevant/related to the feature request?

router

### Description

This is a followup of #48295.

There is no replacement for ExtraOptions with new `provideRouter`
eg

```
RouterModule.forRoot(APPLICATION_ROUTES, {
        errorHandler: (error: any) => console.error('Router Error Occured', error)
      }),
```

The linked issue mentioned you can use the Router.events with NavigationError but this is not usable for all variants of handling navigation errors.
The defaultErrorHandler is throwing the error and can't be overwritten:

https://github.com/angular/angular/blob/61e69c87e6b577f1c5a71fb5c39c3bd6125c4b91/packages/router/src/router.ts#L169-L171

https://github.com/angular/angular/blob/61e69c87e6b577f1c5a71fb5c39c3bd6125c4b91/packages/router/src/router.ts#L977-L987

For the moment the best way is to use an own provide for the ROUTER_CONFIG injection token.

### Proposed solution

Add new settings to Router config

```
 provideRouter(APPLICATION_ROUTES, withRouterConfig({
        errorHandler: (error: any) => console.error('Router Error Occured', error)
    })),
```

### Alternatives considered

There is non if you want to fluent API.

**Comment by atscott** [comment]
`withNavigationErrorHandler` will be available in 15.2: https://next.angular.io/api/router/withNavigationErrorHandler

> The `defaultErrorHandler` is throwing the error and can't be overwritten:

Correct. Changing this behavior will not be possible. A navigation error is a navigation error. Recovering from one is possible but the ability to update the promise to resolve instead of reject on an error is going away.

**Comment by CSchulz** [comment]
Is this a kind of breaking change? People relying on the possibility to omit an error propagation will have a breaking behavior.
In our case the error propagation stops the navigation listener and the application isn't usable anymore.

**Comment by atscott** [comment]
> Is this a kind of breaking change? 
Yes, it will be considered a breaking change / API removal so it will not be removed for at least 2 major versions.

> In our case the error propagation stops the navigation listener and the application isn't usable anymore.
Can you provide a stackblitz example to demonstrate this? I was not aware of any code that relied on this behavior and would be interested in the use-case.

**Comment by atscott** [comment]
@CSchulz Would you mind opening another issue to specifically discuss the deprecation of `ErrorHandler` rather than the availability in `provideRouter`? It's a nuanced difference, but I am specifically curious about use-cases that are using the `errorHandler` in a way that cannot be done by listening for `NavigationError` alone. I had not found any teams doing this internally and if there's a use-case in the external ecosystem that wasn't accounted for, it may indicate the need to remove the deprecation or provide different alternative.

**Comment by CSchulz** [comment]
@atscott I have done it in #48902
