### ISSUE TITLE
HashLocationStrategy returns empty string for LocationStrategy.getBasePath()

### ISSUE THREAD

**Issue by yohny** [angular/angular#48783]
### Which @angular/* package(s) are the source of the bug?

common

### Is this a regression?

No

### Description

When an app is build with `--base-href=/subfolder/` the LocationStrategy behaves inconsistent between `PathLocationStrategy` and `HashLocationStrategy`.
I have an app that is build with above base-href configuration. In it there is an `AppComponent` with the following code to log relevant info:
```ts
export class AppComponent {
  constructor(platformLocation: PlatformLocation, locationStrategy: LocationStrategy) {
    console.log("platformLocation.href:", platformLocation.href);
    console.log("platformLocation.getBaseHrefFromDOM():", platformLocation.getBaseHrefFromDOM());
    console.log("platformLocation.pathname:", platformLocation.pathname);
    console.log("locationStrategy.path():", locationStrategy.path());
    console.log("locationStrategy.getBaseHref():", locationStrategy.getBaseHref());
  }
}
```
If in `AppModule` the RouterModule is imported as `RouterModule.forRoot([])` and I visit `localhost:4200/subfolder/` the following is logged in console:
```
platformLocation.href: http://localhost:4200/subfolder/
platformLocation.getBaseHrefFromDOM(): /subfolder/
platformLocation.pathname: /subfolder/
locationStrategy.path(): /subfolder/
locationStrategy.getBaseHref(): /subfolder/
```
which is what is to be expected. However when RouterModule import is changed to `RouterModule.forRoot([], {useHash: true})` and the same URL is visited, the log is as follows:
```
platformLocation.href: http://localhost:4200/subfolder/
platformLocation.getBaseHrefFromDOM(): /subfolder/
platformLocation.pathname: /subfolder/
locationStrategy.path(): <empty string>
locationStrategy.getBaseHref(): <empty string>
```
Notice that `locationStrategy.getBaseHref()` returns an empty string, when one would expect that it would be `/subfolder/, same as in previous case as the same base-url is configured

### Please provide the environment you discovered this bug in (run `ng version`)

```true
Angular CLI: 15.1.2
Node: 16.19.0
Package Manager: npm 8.19.3
OS: linux x64

Angular packages 15.1.1
```

**Comment by JeanMeche** [comment]
In the HashLocationStrategy, the baseHref is defined by the `APP_BASE_HREF` injection token. 

Do you use a `<base href> ` in your document ? 

Could you provide a complete working repro case ?

**Comment by atscott** [comment]
Yea, so this is really working as expected. `PlatformLocation` is exactly what the browser understands - it's directly the `document.location.[pathname/href/etc]`. `HashLocationStrategy` is completely different in that it instructs the _router_ and _application_ to use only the hash part of the URL for application paths. This is fundamentally incompatible with the browser's interpretation of the `base href` element. We also cannot simply assume `base href` should also be interpreted as the `APP_BASE_HREF` for all cases because people _do_ want these to be different in some cases. 

I can certainly see an argument for updating the documentation to make this more clear and would be happy to review a PR that improves it. As it is though, this behavior is working as expected so I'll close this issue.
