### ISSUE TITLE
Component Class is undefined by using any other ClassDecorator on Component

### ISSUE THREAD

**Issue by anschm** [angular/angular#48792]
### Which @angular/* package(s) are the source of the bug?

core

### Is this a regression?

Yes

### Description

I wrote a method subformComponentProviders which generates the providers for the control value accessor pattern. The method is implemented like:

```
export function subformComponentProviders(component: any): {
  provide: InjectionToken<ControlValueAccessor>;
  useExisting: Type<any>;
  multi?: boolean;
}[] {
  return [
    {
      provide: NG_VALUE_ACCESSOR,
      useExisting: forwardRef(() => component),
      multi: true
    },
    {
      provide: NG_VALIDATORS,
      useExisting: forwardRef(() => component),
      multi: true
    }
  ];
}
```
The method is used like:
```
@Test()
@Component({
  selector: 'chips-autocomplete-input',
  templateUrl: './chips-autocomplete-input.component.html',
  styleUrls: ['./chips-autocomplete-input.component.scss'],
  providers: subformComponentProviders(ChipsAutocompleteInputComponent),
  changeDetection: ChangeDetectionStrategy.OnPush
})
```
After migrating to angular 15.1.1 in my case the component class parameter from the method subformComponentProviders is undefined if I put another CLassDecorator on my component. Example for class decorator:
```
function Test(options: any): ClassDecorator {
  return () => {
    console.log(options);
  };
}
```
If I delete @Test() the method subformComponentProviders gets the component class.

### Please provide the environment you discovered this bug in (run `ng version`)

```true
Angular: 15.1.1
```

**Comment by JoostK** [comment]
The `forwardRef(() => component)` isn't having any effect; it only defers reading the value of `component` but that value is eagerly available as it is parameter value. It's the caller that should guard the access to `ChipsAutocompleteInputComponent` by wrapping it within a `forwardRef`.

Having the decorator would likely result in slightly different code that impacts how the forward-reference behaves, but it's otherwise a red-herring as the reference within `providers: subformComponentProviders(ChipsAutocompleteInputComponent)` is already a forward ref that cannot be relied upon.
