### ISSUE TITLE
Provide a `this` keyword in the html bindings

### ISSUE THREAD

**Issue by kasperpeulen** [angular/angular#4880]
In an event callback, I often would like to have access to the `this` keyword. What I mean with this, is things like:

```
<div #focusablediv (click)="focusablediv.focus()">
<input #input (input)="inputHandler(input.value)">
```

This is of course all fine, but if you only need this `#` for the element itself (and not for other elements), it seems more natural, to write something like:

```
<div (click)="$this.focus()" tabindex="0" >
<input (input)="inputHandler($this.value)">
```

So less names, to think about :)

I guess, I could also write:
```
<div (click)="$event.target.focus()" tabindex="0" >
<input (input)="inputHandler($event.target.value)">
```

So basically, `$this` could then be seen as a shortcut for `$event.target`.

**Comment by martinmcwhorter** [comment]
Maybe it should be called `$target` instead of `$this`. `$this` sounds like it should be the instance of the component.

**Comment by pkozlowski-opensource** [comment]
`this` is definitively not a good name since it might be confused with template instance, directive instance and probably 100 other things.

As for the proposed sugar: I'm not sure it buys enough to justify a new concept. Both `<div (click)="$event.target.focus()">` and `<div #mydiv (click)="mydiv.focus()">` are reasonable IMO.

Going to close for now, but we can re-visit it later if there is high demand for such sugar.
