### ISSUE TITLE
`ng g @angular/core:standalone` only updates test files in a CLI project

### ISSUE THREAD

**Issue by cexbrayat** [angular/angular#48844]
### Which @angular/* package(s) are the source of the bug?

core

### Is this a regression?

No

### Description

In a CLI project, the new standalone migration schematics only update spec files

```
ng new standalone-migration --defaults
cd standalone-migration
ng update @angular/core@next @angular/cli@next --force
ng g @angular/core:standalone --mode convert-to-standalone --path ./
```

results in:
```
UPDATE src/app/app.component.spec.ts (984 bytes)
```

and the component itself is not impacted

### Please provide the environment you discovered this bug in (run `ng version`)

```true
Angular CLI: 15.2.0-next.1
Node: 16.17.0
Package Manager: npm 8.19.3
OS: darwin arm64

Angular: 15.2.0-next.2
... animations, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1502.0-next.1
@angular-devkit/build-angular   15.2.0-next.1
@angular-devkit/core            15.2.0-next.1
@angular-devkit/schematics      15.2.0-next.1
@angular/cli                    15.2.0-next.1
@schematics/angular             15.2.0-next.1
rxjs                            7.6.0
typescript                      4.8.4
```

**Comment by crisbeto** [comment]
What does the project look like? The migration only runs on files that were resolved through the `tsconfig.json`.

**Comment by crisbeto** [comment]
I looked into it and it's working as expected. It's because the first step won't convert the root module to standalone since we would also have to change `bootstrapModule` to `bootstrapApplication` which is a bit more involved. I've sent out https://github.com/angular/angular/pull/48848 which has the last step of the migration. 

That being said, the way the test file is being modified is incorrect, because the component that was moved into `imports` wasn't converted to standalone. I'll address this separately when I start bug fixing.
