### ISSUE TITLE
Directive not instantiating in native html

### ISSUE THREAD

**Issue by tejji** [angular/angular#4887]
Hi,

Directive is not instantiating on native html. Refer to plnkr link below

http://plnkr.co/edit/YFeWpujEp1rzznpOC1yi?p=preview

Thanks

**Comment by PascalPrecht** [comment]
Hey @tejji the plunk you've posted doesn't really help. It simply bootstraps an application an everything seems to work fine. 

Could you provide a plunk that illustrates your issue? Thanks!

**Comment by tejji** [comment]
I am trying to use angular2 on native element in html file (index.html). 

Issue: when I click on button onClick() is not executing. Nor the constructor LogOnClick is called

How do I use angular2 on native element in html file (index.html)

**Comment by thelgevold** [comment]
I might be misunderstanding the question, but the are you asking abut applying Angular directives to elements outside the bootstrapping point (my-app)?
It would be helpful to see the actual use case, but your Angular code begins inside the app element, so you can't apply Angular code to elements outside my-app. Meaning you can't call on Angular directives in index.html.

**Comment by tejji** [comment]
May be I have not understood well how angular2 works. Let me clarify...

Is there a way to access & manipulate DOM elements outside of my-app?

**Comment by thelgevold** [comment]
Hm... I have an example here http://www.syntaxsuccess.com/viewarticle/using-jquery-with-angular-2.0
Basically this article shows how to get access to the underlying DOM element backing your Angular directive. Once you have a handle to the DOM you can use standard DOM manipulation techniques like jquery or regular JS to manipulate elements up the ancestor tree.

Something like this:
```
jQuery(this.elementRef.nativeElement).closest('.some-parent');
```
That said, I strongly discourage this pattern as a norm since it creates a tight coupling between your DOM and your Angular app. One of the advantages of Angular is decoupled models that don't assume a fixed DOM structure. As soon as you start reaching into the DOM directly you are imposing a rigid relationship between your models and the DOM around it.

**Comment by tejji** [comment]
Understood! 
Thanks for guiding me.

Many a times data is embed in HTML. If I have use approach recommended by you then what is recommended way to pass data to angular component?

1. use <script type="application/json" /> to embed data in html
2. use GET to get data from server in JSON format
3. some other approach

**Comment by pkozlowski-opensource** [comment]
@tejji could we move the discussion about usage / best practices to https://gitter.im/angular/angular? Thnx!
