### ISSUE TITLE
Provide way to identify Router navigation errors in the global ErrorHandler

### ISSUE THREAD

**Issue by CSchulz** [angular/angular#48902]
### Which @angular/* package(s) are relevant/related to the feature request?

router

### Description

This is a followup of #48759, especially https://github.com/angular/angular/issues/48759#issuecomment-1397190231.

The use case of the own ErrorHandler in the Router prevents delegating the error to the @angular/core ErrorHandler.
In this scenario normally the NavigationService handles all navigation errors.
All other errors should be handled by the GlobalErrorHandler.

https://stackblitz.com/edit/angular-dob9kc?file=src/main.ts

### Proposed solution

Keep the existing possibility to overwrite the behavior how the router handles a NavigationError.

### Alternatives considered

none.

**Comment by atscott** [comment]
I see. It appears that the real issue is that `errorHandler` currently provides a way to handle navigation errors separately from other errors. Since there is no clearly identifiable information in the error thrown by the default error handler, the only way to handle navigation errors separately from other errors is to use a custom `errorHandler` in the router config so that the error never reaches the globally configured `ErrorHandler` from `@angular/core`. 

This is a fixable problem that doesn't require retaining the `errorHandler` configuration in the Router. Before this feature is removed, we'll make sure there is a replacement for this use-case.
