### ISSUE TITLE
Tree-shaking of templates

### ISSUE THREAD

**Issue by mateuszo** [angular/angular#49023]
### Which @angular/* package(s) are relevant/related to the feature request?

compiler

### Description

The issue I'm writing about might not be so common in Angular projects. However, it is quite common in projects that use [SAP Spartacus](https://github.com/SAP/spartacus) libraries or other component libraries.

Spartacus is providing logic and components for building storefront applications. In implementation projects, we usually customize its services and replace some of the components with our custom ones. Standard practice is to extend a component from Spartacus to inherit the logic and replace the template. This approach allows us to write less and get automatic upgrades when we upgrade the Spartacus package. However, the problem is that the template of the parent component ends up in the bundle even though it's not used at all. Often, this makes the bundle size quite big negatively affecting performance.

Maybe this could also affect other projects.

### Proposed solution

It seems to be quite hard to determine whether the template will be actually used or not. The only case that comes to my mind is when the class is used only in the context of extension or implementation. In that case, the compiler could potentially remove the `@Component` directive from the parent class.

Another solution would be to be able to instruct a compiler not to compile templates for specified components. 

### Alternatives considered

An alternative would be that the component library (e.g. Spartacus) splits the components into smart and dumb components. The dumb component would then have the `@Component` decorator and would extend from the smart component which would contain logic only. However, this produces a lot of boilerplate and may cause trouble with other decorators.

Another solution that we've tried is to patch the compiled code and remove the unused templates manually.

**Comment by JoostK** [comment]
I think what I'd do in this case is to split the component into an abstract directive and a concrete component, where inheritors would then have to extend the directive instead of a component. This makes sense, as directives are components without templates.

This does require that you manually author the code in such way, but doing this in an optimisation pass would not be semantics-preserving, as components would have to be downgraded to directives. With component factories no longer necessary to create a component instance, we have to assume that any reference to the component type could be used to render the component.

**Comment by Platonn** [comment]
@JoostK I agree.
The solution is to craft the library consciously so each component's logic is moved an abstract component class. And each actual component (with templates) would `extend` (in Typescript sense) their abstract component counterpart. Then export both classes (component and abstract component), so the consumers of the library can choose which to use: original component or just the abstract class (for the user's customization purposes).

If you're a library author, you don't need to worry about backward compatibility when moving all logic from your components to new abstract classes. This is not a breaking change for consumers of your library.

Unfortunately it requires an architectural deliberate decision and implementation from the library authors. Then the library consumers are doomed, if the library authors don't make this decision. Then when consumers extend a library's component, then the default templates will land in their production bundle unnecessarily.

Alternatively, consumers can copy-paste the TS code of original components from library's source code. But that is not an appreciated solution, because the cost of further maintenance of such class is moved from library authors to the consumers. Moreover, they don't get new features, when library adds new functionality to such a class.

**Comment by alxhub** [comment]
I'm closing out this issue as it's something we fundamentally cannot support. Tree-shaking is based on references, and unfortunately using a component as a base class and using a component to render its template somehow are both references to the component's class. The solutions described above (adjusting the architecture to use abstract directive base classes instead) is the best way to achieve this behavior.
