### ISSUE TITLE
@ViewChild is called multiple times for overriden properties

### ISSUE THREAD

**Issue by angelaki** [angular/angular#49127]
### Which @angular/* package(s) are the source of the bug?

core

### Is this a regression?

No

### Description

When overriding a baseclasses' property and setting `@ViewChild` again, the setter is getting called twice. I think Angular show notice it and call the setter only once.

If this is an intendet behavior, where to put `@ViewChild`? In the base or concrete class? Right now I'm repeating it, since it feals more obvious to me.

### Please provide a link to a minimal reproduction of the bug

https://stackblitz.com/edit/angular-9etyr6

### Please provide the exception or error you saw

```true
In the repro you can see the console output getting triggered twice. Imho Angular should notice this and only call the setter once.
```

### Please provide the environment you discovered this bug in (run `ng version`)

```true
Angular 15
```

**Comment by JeanMeche** [comment]
What about only having the overriding setter without the annotation ? You'll still get the behavior from the parent class and less code duplication (and no double call).

**Comment by JeanMeche** [comment]
Just commenting on the techincal aspect not the feature part : They not the same property because they are on 2 differents classes. 
An abstract class in TS will be transpiled to a standard class in JS, so you will have 2 classes on which the decorator will be run ! 

[Playground demo](https://www.typescriptlang.org/play?#code/MYewdgzgLgBANiA5gEQKagE4EMoEtwwC8MAFAJREB8pwcWAXvQFwxZgCeANDAA4Yg8WbdhULVQkEHFQA6BIhIADAMJ0IEFgBIA3rQb0ZE6BgCuwKCAwywWALaoAvjAC0MAAr9BMHXwEPFZADcAFDBWABGxljmMHrqMABiICAw2sEwMAAC8miYOPhg5OkwAGbJRDAA5GUglSEOoXEQMABCWBgwqAAeUKhgACbNSSlpGdlIuZb54EUZNRWV4e11xUsdxIvL9aGhQA)

**Comment by destus90** [comment]
The same happens here https://github.com/angular/angular/issues/39225.

**Comment by angelaki** [comment]
Ok, so it is _working as intended_. Guess logic for checking override decorators would be too expensive / not worth the effort.
