### ISSUE TITLE
[web_workers] Can't load more than one component with templateUrl

### ISSUE THREAD

**Issue by ericmdantas** [angular/angular#4930]
Alright, here's the repo with the error: https://github.com/ericmdantas/ng2-worker - clone it, run tsc and then run `live-server`.

I have a main component called `app_cmp.ts` that is the component responsible for wrapping and exposing the other components of my app - in thise case, a simple todo_app.

You'll see everything is working fine. But if you go to `app/app_cmp.ts` and uncomment `TodoListCmp`, you'll see the application simply disappears and no errors are thrown.

Now, if you go to `app/todo/todo_list_cmp.ts` and change `templateUrl` to simply `template`, things will work just fine.

Seems to be a weird and silent error. Any idea?

**Comment by ericmdantas** [comment]
After trying out a bit more, I realized that sometimes, even when using templateUrl in more than one component, the app *does* work - after refreshing the page many times, for example.

Which leads me to believe it's a *concurrency* problem.

**Comment by ericmdantas** [comment]
I'll update it to beta1 and see how it goes.

**Comment by mdaveynis** [comment]
I also can reproduce this issue in beta 15, see http://plnkr.co/edit/OZJFO4m97jkfmXGwj9q1?p=preview

Issue occurs when multiple templates load concurrently using templateUrl in web worker. Root cause is related to xhr request does not resolve promise when concurrent requests complete close to each other. In the example above three components are loaded at the same time from app.ts. With breakpoint on line 19990 of worker/worker.dev.js (start of `TemplateNormalizer.prototype.normalizeTemplate` function) only, problem will go away. While with only breakpoint on 19996 (on xhr promise resolve) problem persists and it will be hit less than 3 times.

**Comment by ericmdantas** [comment]
Good to know I'm not the only one 😆

**Comment by splincode** [comment]
@ericmdantas Is the issue relevant?

**Comment by ericmdantas** [comment]
@splincode well, it's been almost 3 years since the bug was found. Back then it was relevant, not sure now - specially because of all the changes that happened in the mean time.

**Comment by splincode** [comment]
@ericmdantas Maybe, can be close it?

**Comment by ericmdantas** [comment]
@splincode Sure.
