### ISSUE TITLE
implement lazy loading of markup for improving optimization

### ISSUE THREAD

**Issue by vladyslavmalamuzh** [angular/angular#49323]
### Which @angular/* package(s) are relevant/related to the feature request?

upgrade

### Description

This feature would increase perfomance of Angular application. 
We already had functionality which help us to lazy load components, images, but I suggest to implement functionality which will lazy load divs and any markup also. 

### Proposed solution

It could be a directive.
This will decrease amount of request when page loading, speed of rendering page.
This functionality can be implemented through the Intersection observer itself. But it would be nice to have it out of the box and in the framework functionality itself

### Alternatives considered

An alternative would be to render html with | async only when the user screen is in scope.
This functionality would be very useful

**Comment by prabhakarand7** [comment]
@vladyslavmalamuzh @jessicajaniuk We already have the component and module level lazy loading but if we are applying to div or any HTML markup tags its a tedious and mess because if you take any component in the HTML page we have hundreds and thousands of divs and markups so it will be really a complicated to do this.

My suggestion would be instead doing all the div or tags(markups), we will introduce new attribute that will support the lazy loading when the attribute is added to the specific div or tags.

Note: We already have bindings and async pipe in our angular component, so we need to consider while doing this implementation to avoid data and events losses.  

@vladyslavmalamuzh  let me your thoughts.

**Comment by rlmestre** [comment]
Probably related to https://github.com/angular/angular/issues/43120 and/or https://github.com/angular/angular/pull/48580

**Comment by vladyslavmalamuzh** [comment]
@prabhakarand7 Implementing lazy loading divs with an attribute would be a great idea. And then many people would be able to optimize the application even more for themselves and use it in specific "hard" places on the page. I would be very happy to see this pre-setuped in the framework itself

**Comment by pkozlowski-opensource** [comment]
As of today the only  reasonable code-splitting point is a [dynamic import](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/import). To support the use-case described here we would have to generate code with dynamic imports and thus make parts of runtime dynamic / asynchronous. 

Given the above it is not something we want to support in the core of the framework, especially that there are possible solutions in the user land.
