### ISSUE TITLE
Language service does not analyze types properly in templates

### ISSUE THREAD

**Issue by g-cheishvili** [angular/angular#49340]
### Which @angular/* package(s) are the source of the bug?

language-service

### Is this a regression?

No idea, probably no

### Description

First of all, Thank you, everyone! This is the best overall framework out there, period! And it is being improved marginally on every release as if it was a new thing, amazing!

Now, about the issue:

There are two types of issues here:
- When you merge an interface and a class, and not implement anything in a class, templates lose intellisense.
- If you have an Enum and use a template literal to take its values only and use them as a union, templates are losing intellisense, kinda, you need to check out the example below to get this fully.

Both are working as intended in the TS files

I tested on VSCode and IntelliJ platform IDES and I believe this is coming from here.

I have provided the stackblitz snippet, you can download it and play with it locally.

### Please provide a link to a minimal reproduction of the bug

https://stackblitz.com/edit/ng15-language-service-problem?file=src/main.ts

### Please provide the exception or error you saw

```true
No errors, just does not work
```

### Please provide the environment you discovered this bug in (run `ng version`)

```true
Angular CLI: 15.2.1
Node: 16.18.1
Package Manager: npm 8.19.2
OS: darwin arm64

Angular: 15.2.1
... animations, cli, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1502.1
@angular-devkit/build-angular   15.2.1
@angular-devkit/core            15.2.1
@angular-devkit/schematics      15.2.1
@schematics/angular             15.2.1
rxjs                            7.8.0
typescript                      4.9.5
```

**Comment by g-cheishvili** [comment]
FYI Ionic autocompletion has a similar issue. If you create an ionic project and then use any of the components, the input names will be detected, but not the value options. That happens there because they merge typings when they compile their stencil code to be an Angular wrapper.

**Comment by atscott** [comment]
Hi, thanks for the report and reproduction. It seems like there are several different issues being reported here, which makes it a bit difficult to triage. 

* Suggestions for enums not working is already open here: https://github.com/angular/vscode-ng-language-service/issues/1740
* The declaration merging with the class/interface appears to be an issue with the compiler in general, not the language service. `ng build` works when it shouldn't due to an invalid type. Can you please submit a separate issue in the main angular/angular repository for this?
* Inline templates generally appear to be not working well in this reproduction. Moving the template of `AppComponent` to an external template file results in a better experience. I'm going to do a bit more investigation and open a new issue for this.

I believe that's all of them, but please do open a new issue if there's a bullet I missed.

**Comment by g-cheishvili** [comment]
> 

I believe that the issue, which you referred is a different issue, not related to this. Thanks for reaching out so fast. I will create separate issue for:
- string literals as types
- about the language service not reporting back about the merged declarations(compilation is a different problem, I think)

And will fork out the example I provided into different topics

**Comment by atscott** [comment]
> about the language service not reporting back about the merged declarations(compilation is a different problem, I think)

Compilation would be the same problem. The Angular compiler is used directly under the hood to power the language service features. If the Angular compiler isn't getting the correct typings, neither would the language service.

**Comment by g-cheishvili** [comment]
> > about the language service not reporting back about the merged declarations(compilation is a different problem, I think)
> 
> Compilation would be the same problem. The Angular compiler is used directly under the hood to power the language service features. If the Angular compiler isn't getting the correct typings, neither would the language service.

So, should I open the issues or you will do it? I have examples ready to deployed

**Comment by atscott** [comment]
> So, should I open the issues or you will do it? I have examples ready to deployed

If you've got them ready to go, feel free to open them!

**Comment by atscott** [comment]
@g-cheishvili Apologies for the confusion about the repository! I opened this report from my notifications feed and didn't realize it was already in angular/angular rather than the [language service repo](https://github.com/angular/vscode-ng-language-service). I've opened another issue there with a minimal reproduction for the inline template issue: https://github.com/angular/vscode-ng-language-service/issues/1872
