### ISSUE TITLE
component template uses the get() method without  nullcheck need reported error

### ISSUE THREAD

**Issue by scarqin** [angular/angular#49385]
### Which @angular/* package(s) are the source of the bug?

compiler

### Is this a regression?

Yes

### Description
source code： https://github.com/Postcatlab/postcat/commit/ba45a59c7b63ae2b129d6c71590422f120195d76

If I don't add a question mark to the variable inside get(), the page template will be wrong, and the console will not report an error.

<img width="1378" alt="image" src="https://user-images.githubusercontent.com/15225835/224311663-448b17a4-48e8-46a5-bfbe-5c279b7bb1b4.png">

<img width="565" alt="image" src="https://user-images.githubusercontent.com/15225835/224293733-932793db-1587-4784-9242-adeffb159a60.png">

error page without error log
![image](https://user-images.githubusercontent.com/15225835/224293777-fd633ba9-b0ef-4327-b3fc-b8cc163733e0.png)

tsconfig
```
"angularCompilerOptions": {
    "enableIvy": true,
    "strictTemplates": true,
    "fullTemplateTypeCheck": true,
    "annotateForClosureCompiler": true,
    "strictInjectionParameters": true,
    "skipTemplateCodegen": false,
    "skipMetadataEmit": false,
    "disableTypeScriptVersionCheck": true,
    "enableI18nLegacyMessageIdFormat": false,
    "strictInputAccessModifiers": true
  }
```

### Please provide a link to a minimal reproduction of the bug

https://github.com/Postcatlab/postcat/pull/251/commits/16d383f8e2087901fd7174fcf9b5d32c4850fc33

### Please provide the exception or error you saw

```true
Devtools/strictTemplates will throw error
```

### Please provide the environment you discovered this bug in (run `ng version`)

```true
"@angular-cli/base-href-webpack": "1.0.16",
    "@angular/animations": "15.2.2",
    "@angular/common": "15.2.2",
    "@angular/compiler": "15.2.2",
    "@angular/core": "15.2.2",
    "@angular/forms": "15.2.2",
    "@angular/language-service": "15.2.2",
    "@angular/platform-browser": "15.2.2",
    "@angular/platform-browser-dynamic": "15.2.2",
    "@angular/router": "15.2.2",
    "@angular/upgrade": "^15.2.2",
```

### Anything else?
<img width="1465" alt="image" src="https://user-images.githubusercontent.com/15225835/224312595-4d0ec276-455f-4551-8a51-019568d0161f.png">
correct page

**Comment by JoostK** [comment]
I don't understand what this issue is reporting, could you please clarify?

**Comment by scarqin** [comment]
@JoostK Sure,i have change my description.

**Comment by JoostK** [comment]
This is because `ActivatedRouteSnapshot.queryParams` is of type [`Params`](https://angular.io/api/router/Params), which is defined particularly unsafe as an indexed type with `any` as value. If the property is not present you'll get `undefined`, which is why your could could crash without using optional chaining syntax.

This pitfall can be avoided by switching to `ActivatedRouteSnapshot.queryParamMap`, which exposes the query parameters as a [`ParamMap`](https://angular.io/api/router/ParamMap), which is more strict in the sense that its `get` method can return `null`.

**Comment by scarqin** [comment]
@JoostK Thanks for the reply, is there a way to detect this at runtime? When debugging, it is difficult to locate the problem when encountering such a problem.

**Comment by JoostK** [comment]
It's typically helpful to run with a debugger (open Chrome's Web Inspector, for example) and enable "Pause on caught exception"; that will stop execution whenever an error occurs, which in this case would have led you to the point where `.includes` was read from the `undefined` value.

![image](https://user-images.githubusercontent.com/123679/224329879-06c96581-b866-4531-94dc-573e0777fdbe.png)

I am otherwise going to close this, as there is no issue with template type-checking here.
