### ISSUE TITLE
Set standalone: true globally

### ISSUE THREAD

**Issue by spock123** [angular/angular#49667]
### Description

When creating an application entirely without modules, we have to specify `standalone: true` in every single component.
This creates more boilerplate and makes the code less readable.

### Proposed solution

Would it be possible to create a flag (for example `standalone: true`) that is set during application bootstrap? This would make it possible to set this standalone globally and thereby avoiding adding the dreaded value to every component in the application.

Or even better, make it possible to set a default `standalone` value globally, and then let those components who wish to diverge from that, use their local `standalone` prop to override the global default.

This way we can write entire applications without ever using the standalone prop in components. And we can mix and match if needed, using the local component to override the global default.

### Alternatives considered

Writing `standalone:true` in every component

**Comment by JeanMeche** [comment]
I don't speak for the team, but I pretty much expect that `standalone:true` to be the default value in a future version (v17 ?) and non standalone would require `standalone: false`.

**Comment by spock123** [comment]
@JeanMeche yeah that would be nice, however I think some people would not like having to add "`standalone: false`" to all their components (schematic or no, it adds stuff to the component code that is not needed imho).

**Comment by pkozlowski-opensource** [comment]
@spock123 we completely understand the friction of dealing with `standalone: true`, however there are reasons we can't do it currently:
* the setting must be per component since a library author might have authored a component with one idea in mind and application could disagree; 
* the above could be mitigated by having this setting per compilation unit but this wouldn't work in JiT.

Also, some of the tooling depends on this explicit flag.

We will be looking at the adoption of standalone and flip the defaults in the future if most of the authored components are standalone.
