### ISSUE TITLE
@Component needing an @Injectable but not bootstrap?  Providor not found

### ISSUE THREAD

**Issue by Kikketer** [angular/angular#5002]
Attempting to walk through a simple scenario where I have a Component that relies on a service (say to pull data).

So I see the use of &commat;Injectable to make a class injectable into my \@Component's constructor.  But I'm running into the situation where it'll throw the "Provider not found" error:
http://plnkr.co/edit/HNUte0Bajnu6odugYlsC

Here's a "working" version but I had to modify the bootstrap:
http://plnkr.co/edit/s28zl1t9H6SBx3QdyYGq
It seems unmanagable to have to add every service to this array and I would need to import every single file at the top.  Wouldn't someone want to just be able to inject an \@injectable into their class without having to worry about the bootstrap?

Also \@Injectable made no difference when it was added to the bootstrap.

**Comment by ericmartinezr** [comment]
@Kikketer
 
First of all `@Injectable()` is not necessary to inject it into the component, see this article
http://blog.thoughtram.io/angular/2015/09/17/resolve-service-dependencies-in-angular-2.html and this discussion https://github.com/angular/angular/issues/4404 and overall this comment https://github.com/angular/angular/issues/4404#issuecomment-143920530

To inject the Service into your component you must use `providers/viewProviders` that's why is working when you use it in the bootstrap.

So you can remove it from the bootstrap and make it part of your component

```
@Component({
  selector: 'content',
  providers : [Service],
  template: '<h1>Yay</h1>'
})
```

**Comment by pkozlowski-opensource** [comment]
Thnx for helping out with the issues @ericmartinezr - your answer is spot on!

**Comment by Kikketer** [comment]
@ericmartinezr  Fantastic thanks for the quick response.  This worked!
