### ISSUE TITLE
DevTools builds but throws error when loaded in Chrome

### ISSUE THREAD

**Issue by JeanMeche** [angular/angular#50048]
### Is this a bug report or a feature request?

- [X] Bug Report
- [ ] Feature Request

### Please provide the steps to reproduce the issue [Bug Report only]

* Build the devTools with `devtools:build:chrome`
* zip the content of `dist/bin/devtools/projects/shell-browser/src/prodapp`
* Drag & drop the zip into the extension page (`chrome://extensions`)
* Debug an angular app with the devTools
* Check the extension page for errors : 

![Screenshot 2023-04-27 at 21 55 19](https://user-images.githubusercontent.com/1300985/234976515-d039ca59-892b-4bac-88ed-1ccb716184a4.png)

`Uncaught EvalError: Refused to evaluate a string as JavaScript because 'unsafe-eval' is not an allowed source of script in the following Content Security Policy directive: "script-src 'self'".`

Afaik there has been no changes since the release of `1.0.7`. So I'm a bit clueless. 

Poke @AleksanderBodurri If you have any idea !

**Comment by AleksanderBodurri** [comment]
This has to do with a recent change in the APF (Angular Package Format) and some configuration in https://github.com/angular/angular/blob/main/devtools/tools/esbuild/esbuild-base.config.mjs that needs to be updated as a result. 

Since DevTools' Angular framework dependencies are built from local files, they are always up to date. [Recently](https://github.com/angular/angular/pull/49332) these dependencies started being published as fesm2022 instead of fesm2020. We also have an Angular dependency `ngx-flamegraph` that was built and published as fesm2020.

The easiest fix to make sure all of our Angular based dependencies are processed by the linker would be to update the filterPaths field in that file from `/fesm2020/` to `/fesm2020|fesm2022/`. When v16 releases, we can update ngx-flamegraph and publish it with the new APF, letting us change filterPaths to just `/fesm2022/`.

Will open a PR for this soon.

**Comment by JeanMeche** [comment]
Thanks for the investigation !
