### ISSUE TITLE
Enhancement: Allow conditions in effect declaration for reactive updates

### ISSUE THREAD

**Issue by dondelice257** [angular/angular#50250]
### Which @angular/* package(s) are relevant/related to the feature request?

Angular signals

### Description

Currently, the effect declaration in my code works as follows:
myEffect = effect(() => {
  // Do something
});

I am proposing an enhancement to allow adding a condition inside the parentheses, so that the effect only triggers when a specific value changes. Here's an example of the suggested syntax:

myValue = 4;
myValue.update((n: number) => n + 1);
myEffect = effect((myValue: number) => {
  console.log('You just changed me!');
});

By implementing this enhancement, it will provide more control over when the effect should execute based on specific conditions.

Proposed solution:
The proposed solution involves modifying the effect declaration syntax to accept a condition within the parentheses. This allows the effect to trigger only when the specified value changes.

Alternatives considered:
The current approach:

myEffect = effect(() => {
  // Do something
});

vs.
The proposed approach:

myValue = 4;
myValue.update((n: number) => n + 1);
myEffect = effect((myValue: number) => {
  console.log('You just changed me!');
});

Please review and consider implementing this enhancement if you find it helpful. Thank you.
my email : dondelicedushime@gmail.com

**Comment by pkozlowski-opensource** [comment]
> Proposed solution:
The proposed solution involves modifying the effect declaration syntax to accept a condition within the parentheses. 

This wouldn't work since the argument to the `effect` has meaning already (it is used to register cleanup functions). 

Exact syntax aside - for now we want the dependencies to be auto-detected, both in computed and effect. If you want to trigger an effect with a specific value change - just read it in the effect function. If you want to read a value but _not_ trigger the effect - you can use `untracked`.

Thnx for the suggestion but we are going to keep the existing behaviour for now since there are already means of achieving the desired behaviour.
