### ISSUE TITLE
Provide token to hook into hydration lifecycles

### ISSUE THREAD

**Issue by yharaskrik** [angular/angular#50292]
### Which @angular/* package(s) are relevant/related to the feature request?

platform-browser

### Description

It would nice to be able to have hooks that we could provide functions (like: `BEFORE_APP_SERIALIZED`) where we could run logic after an app has been hydrated.

### Proposed solution

Provide an injection token like `BEFORE_APP_SERIALIZED` that allows us to provide functionality for logic that happens after hydration:

```typescript
const AFTER_APP_HYDRATED = new InjectionToken<(() => void) | (() => void)[]>('after-app-hydrated');

{
  provide: AFTER_APP_HYDRATED,
  useValue: () => console.log('Hydrated!'),
  multi: true
}
```

### Alternatives considered

/shrug

Not sure what other options there would be here.

**Comment by AndrewKushnir** [comment]
Closing this ticket, since the `afterRender` and `afterNextRender` hooks were introduced in PR https://github.com/angular/angular/pull/50607 and they'll be included into v16.2.0 release. Please reopen the ticket or create a new one if there are some use-cases that can not be covered by those hooks. Thank you.
