### ISSUE TITLE
(input) event does not fire in Firefox under certain conditions

### ISSUE THREAD

**Issue by Leon3131-ux** [angular/angular#50344]
### Which @angular/* package(s) are the source of the bug?

forms, Don't known / other

### Is this a regression?

No

### Description

When building a custom `ControlValueAcessor` implementation that builds upon an exsting `ControlValueAcessor` implementation, the `(input)` event of the underlying `<input>` field does not fire under certain conditions.
There's a lot that needs to happen for this bug to appear but I'll try my best to explain.

There needs to be an implementation of `ControlValueAcessor` that contains an `<input>` field. This input fields needs to transmit the value via a `[value]` binding and `(input)` event. It also needs to have a `(keydown)` event.
I'll call this implementation the child `ControlValueAcessor`.

Now you need to have a second implementation of `ControlValueAcessor` that uses the child `ControlValueAcessor` in combinations with an `[(ngModel)]` binding and `(ngModelChange)` event.
This second implementation then needs to be defined as a `FormControl` in a `FormGroup`.
The `FormControl` needs to have an error in the `errors` attribute.

You now need to have a third component that takes the `errors` from the `FormControl` and renders them in an HTML element with `display: block`.

If all conditions are met then the user is no longer able to enter anything into the `<input>` field. However, spamming the keys on my keyboard did work and I was able to get some characters to appear in the `<input>` field.

I used Firefox 113.0 (32-bit) and Firefox Developer Edition 110.0b9 (64-bit) to test the bug.
I also used Chrome 113.0.5672.93 to test it.
As far as I can tell, this bug only affects Firefox (both editions).

I unfortunately couldn't get a Stackblitz to run but I will link a GitHub repository with the code used to produce the bug.

If anybody else experiences this bug (which I doubt) there is a workaround as far as I've found.
In the component that renders the `errors` you just have to implement `OnChanges` with `SimpleChanges` and do a deep copy of the `errors` to a local variable and use that to render. You could also not use `display: block`.

### Please provide a link to a minimal reproduction of the bug

https://github.com/Leon3131-ux/angularBug

### Please provide the exception or error you saw

```true
The user is unable to type anything into the `input` field. Spamming the keys on the keyboard seems to work to a certain extent, since you can get some characters to appear.
```

### Please provide the environment you discovered this bug in (run `ng version`)

```true
Angular CLI: 15.2.8
Node: 16.17.0
Package Manager: npm 8.15.0
OS: win32 x64

Angular: 15.2.9
... animations, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1502.8
@angular-devkit/build-angular   15.2.8
@angular-devkit/core            15.2.8
@angular-devkit/schematics      15.2.8
@angular/cli                    15.2.8
@schematics/angular             15.2.8
rxjs                            7.8.1
typescript                      4.9.5
```

**Comment by garrettld** [comment]
What a crazy bug! I've narrowed this down quite a bit and figured out that this is a Firefox issue that has nothing to do with Angular.

For starters, here's an Angular StackBlitz that shows a trimmed-down version of your reproduction: https://stackblitz.com/edit/angular-hgtm33?file=src/app/app.component.ts

Notice that there's no Angular forms code at all (no FormsModule, ReactiveFormsModule, `ControlValueAccessor`s, `ngModel`, nor `formControlName`). There's also no nested components.

Your description of the workarounds points to the root cause, which is that the `*ngFor` in this reproduction recreates its DOM nodes on each change detection pass, and change detection is triggered on each keydown event. This is the correct behavior from Angular's point of view given this code, but for some reason this DOM manipulation causes Firefox to not emit the InputEvent when it should.

This led me to try doing the same thing with basic DOM APIs (no Angular), and I was still able to reproduce the bug, as shown in this StackBlitz: https://stackblitz.com/edit/typescript-exmjmi?file=index.html,index.ts

I don't see anything obvious like the KeyboardEvent getting cancelled or the input element getting recreated, so I'm not sure what's going on. I think this should be referred to the Firefox team.

**Comment by Leon3131-ux** [comment]
Thank you for taking the time to look at this :)
I guess I'll report this to Bugzilla within the next few days when I have some spare time. For now I'll close this issue as it's not relevant to Angular.
