### ISSUE TITLE
Error in an async lifecycle hook and router `ResolveFn` crashes Angular 16 universal server

### ISSUE THREAD

**Issue by pjms** [angular/angular#50457]
### Which @angular/* package(s) are the source of the bug?

platform-server

### Is this a regression?

Yes

### Description

<img width="582" alt="스크린샷 2023-05-25 10 34 04" src="https://github.com/angular/angular/assets/1370225/845378b6-0a66-44e1-bd67-d69b8a325218">

The node server built by nguniversal/express-engine crashes seems to be failing to handle errors correctly.

### Reproduction
1. ng add @nguniversal/express-engine
2. Throw an error in any async function
```ts

export class AppComponent implements OnInit {
  async ngOnInit() {
    throw new Error('');
  }
  // or
  ngOnInit() {
    new Promise((_, reject) => reject(''));
  }
}
```
3. Build and run the universal server (i.e. `npm run serve:ssr`)
4. The node server crashes when it tries to run the code.

The same procedure the dependencies of Angular 15 does not crash the server.

### Please provide the exception or error you saw

```true
Node.js v18.16.0
A server error has occurred.
node exited with 1 code.
```

### Please provide the environment you discovered this bug in (run `ng version`)

```true
Angular CLI: 16.0.2
Node: 18.16.0
Package Manager: npm 9.5.1
OS: darwin arm64

Angular: 16.0.3
... animations, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, platform-server
... router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1600.2
@angular-devkit/build-angular   16.0.2
@angular-devkit/core            16.0.2
@angular-devkit/schematics      16.0.2
@angular/cli                    16.0.2
@nguniversal/builders           16.0.2
@nguniversal/express-engine     16.0.2
@schematics/angular             16.0.2
rxjs                            7.8.1
typescript                      5.0.4
```

### Anything else?

```ts
  ngOnInit() {
    throw new Error('');
    // or
    throwError(() => '').subscribe();
  }
```
In case of "sync" function or an observble, the server does not crash and serves the html just fine. 

<img width="538" alt="스크린샷 2023-05-25 10 49 43" src="https://github.com/angular/angular/assets/1370225/f4547464-5321-4915-b27f-6db2fd62cf35">

**Comment by pjms** [comment]
This bug also affect router `ResolveFn`s. Any error that is not catched inside of it will crash the server, regardless of its return type(both sync and async).

**Comment by alan-agius4** [comment]
Hi @pjms, 

In both cases the problem is caused by a change in zone.js https://github.com/angular/angular/pull/49144 (//cc @JiaLiPassion). Interesting, prior this change in zone.js the error was completely ignored and not even displayed in the server console.

That being said, the lifecycle hook are not meant to be "async", and two "async" patterns highlighted above have some problems.

- `async ngOnInit`, this is never await and causes a floating promise as `ngOnInit` is sync.
- `new Promise((_, reject) => reject(''));` This also causes a floating promise which in general is a bad practice and does not guaranteed to be resolved prior to Node.js terminates the process. See: https://github.com/nodejs/node/issues/22088

I did have a chat about supporting async logic in lifecycle hook with @AndrewKushnir and we will discussion this more next week.

**Comment by pjms** [comment]
Thanks @alan-agius4,
I appreciate your detailed and helpful explanation.
During the reproduction process, I was also able to confirm that these errors were indeed ignored until zone.js 0.13.0.

May I ask for advice on figuring out a workaround?

---

With your comment, now I'm trying to mitigate the issues on my project.
I first discovered this behavior not in a lifecycle hook, but in router's `resolve`/`canActivate`.
```ts
const resolver: ResolveFn<any> = (route, state) => {
  // any of those statements will make the server eventually crash
  return throwError(() => ''); // [1]
  return new Promise((_, reject) => reject('')); // [2]
  return await new Promise((_, reject) => reject('')); // [3]
  throw new Error(''); // [4]
};
```
`ResolveFn` is allowed to be either sync or async, thus should have nothing to do with the floating promises.
After some basic debugging, to my understanding, any return value of `ResolveFn` will eventually turn into an Observable by `wrapIntoObservable()`, which kind of makes sense.
However, this was not the case with the statement [4], which crashed at the stage of `closestInjector.runInContext()`, even before `wrapIntoObservable()` kicks in.

Is there an effective way I can avoid crashing the server when an error is thrown either in a `resolveFn` or `canActivateFn`, other than catching all the exceptions?
Or is it just that they are never meant to throw an error in the first place, making it an Angular Universal pitfall here?

**Comment by alan-agius4** [comment]
All of the above `ResolveFn` cases will cause an `unhandledRejection`, because the router currently has some floating promise. The culprit of this problem is:

- https://github.com/angular/angular/blob/3a05e4cca1b3eda743a8646a102a77e5bdecd55a/packages/router/src/router.ts#L417

I see a couple of possible solutions. 
1. Catch the rejection and log it. 
```ts
this.scheduleNavigation(urlTree, source, restoredState, extras).catch(e => this.errorHandler.handleError(e));
```

2. Catch the rejection and change the `defaultErrorHandler` and capture log it  
```ts
private coreErrorHandler = inject(ERROR_HANDLER);

errorHandler = this.options.errorHandler ?? function defaultErrorHandler(error: unknown): never {
   this.coreErrorHandler.handle(error);
   throw error;
}
...
this.scheduleNavigation(urlTree, source, restoredState, extras).catch(() => {});
```

The above somewhat aligns with what you want to do in https://github.com/angular/angular/pull/48910 but it does not remove the `throw` yet.

3. Catch the error and register a default `NavigationErrorHandler` when none is provided. 
```ts
export function provideRouter(routes: Routes, ...features: RouterFeatures[]): EnvironmentProviders {
  const providers: Provider[] = [
    {provide: ROUTES, multi: true, useValue: routes},
    typeof ngDevMode === 'undefined' || ngDevMode
      ? {provide: ROUTER_IS_PROVIDED, useValue: true}
      : [],
    {provide: ActivatedRoute, useFactory: rootRoute, deps: [Router]},
    {provide: APP_BOOTSTRAP_LISTENER, multi: true, useFactory: getBootstrapListener},
    features.map((feature) => feature.ɵproviders),
  ];

  if (!features.some(f => f.ɵkind === RouterFeatureKind.NavigationErrorHandlerFeature)) {
    providers.push(
      withNavigationErrorHandler((e) => inject(ErrorHandler).handleError(e)).ɵproviders
    );
  }

  return makeEnvironmentProviders(providers);
}
....
this.scheduleNavigation(urlTree, source, restoredState, extras).catch(() => {});
```

In the mean time as an interim workaround, you can place the below code in your `server.ts`

```ts
process.on('uncaughtException', (err, origin) => {
  console.error(err)
});
```

**Comment by CarlosTorrecillas** [comment]
Hi @alan-agius4,

The only problem I see with this workaround - and correct me if I am wrong - is that the application does not crash but it does not render though. I tested locally and I get the error logged and the application still runs. The trouble is that the purpose of SSR is gone since the components in reality fail and the HTML is not rendered for web crawlers.

Do you expect to have this addressed soon?

Thanks,
Carlos.

**Comment by alan-agius4** [comment]
@CarlosTorrecillas, in your case it is slightly different since there is no error but the Promise which is return from `ngOnInit` is not awaited prior of rendering. This is somewhat expected as the `ngOnInit` is a sync hook. But, I do see that this is a somewhat a common pattern. 

Previously, this used to work because Zone.js patched the entire promise on Node.js.

Regarding timeframes, I am hoping to continue discussing this with @AndrewKushnir later today.

**Comment by Yberion** [comment]
Hello,

I also faced this problem on Angular `15.2.9` after switching to functional Resolver + `zone.js` update.

Before the switch the resolver was extending an abstract resolver, I switch it to composition + `environmentInjector.runInContext(() => ...);`.

We also `this.router.navigate(...)` in the `ngOnInit` hook, which if I properly read, might cause the problem.

I downgraded to `zone.js` `0.12.0` and everything works as expected. I'll wait this to be fixed as well before migrating to Angular 16 as we need the SSR to work as before.

**Comment by Yberion** [comment]
@alan-agius4 Sorry, I misspoke, there's nothing new compared to https://github.com/angular/angular/issues/50457#issuecomment-1563015430, I wanted to say that we were also facing the same problem with Angular 15 + zone.js 0.13.0 because we're using `router.navigate(...)` in `ngOnInit`.
