### ISSUE TITLE
RouterLinkActive fails to set CSS class when used via directive composition

### ISSUE THREAD

**Issue by miklosbecsei** [angular/angular#50551]
### Which @angular/* package(s) are the source of the bug?

core, router

### Is this a regression?

No

### Description

I've created a component which is meant to be used on an `<a>` element, responsible for applying RouterLink and RouterLinkActive directives via the directive composition API.
RouterLink is applied properly and it works well, however RouterLinkActive is not.
See the Stackblitz project for a minimal reproduction.

### Please provide a link to a minimal reproduction of the bug

https://stackblitz.com/edit/stackblitz-starters-rkgzzd?file=src%2Fnavbar-item%2Fnavbar-item.component.ts

### Please provide the environment you discovered this bug in (run `ng version`)

"@angular/core": "16.0.3"

**Comment by JoostK** [comment]
This is working as designed; `inputs: ['routerLinkActive: activeClass']` forwards the `routerLinkActive` input to correspond with the `activeClass` _input_ of `NavbarItemComponent`, not _field_. It works for `'routerLink: route'` case since `NavbarItemComponent.route` is actually an input that is bound from the `navbar.component.html` template, but `activeClass` is not bound from that template.

You could inject `RouterLinkActive` into `NavbarItemComponent` and set the input programmatically as an alternative.

**Comment by miklosbecsei** [comment]
Thanks for the clarification!
