### ISSUE TITLE
feat(devtools): add total time for a component type during a change detection run

### ISSUE THREAD

**Issue by eneajaho** [angular/angular#50555]
### Which @angular/* package(s) are relevant/related to the feature request?

common

### Description

NIT: There's no devtools in the selections for a feature requests so I choose common 😬.

Seeing the time it takes for a component where it's used during a change detection is great, there are cases where we want to see the total time for all the component instances during a change detection run. 

Would a feature like this make sense for general usage? And should I send a PR with my changes? 
If yes, what would be the suggested way to go forward (UX wise)? 

### Proposed solution

Having a table or a filtered table where we can select the component type and where we can see the total time of all the component instances would be great. 

This is needed in cases we want to enable change detection on push or when optimizing the performance of a component and this way we can easily see how we improve the change detection cycle time. 

In the example below I've updated the devtools code to add the total time for all the directives in that CD run. 

![image](https://github.com/angular/angular/assets/25394362/f083a41f-8e63-47c4-aaac-0dffb76f097b)

### Alternatives considered

Sum the total of all component instances times one by one by selecting them in the graph.

**Comment by AleksanderBodurri** [comment]
Hey @eneajaho! This is a cool idea. I'll add this as a discussion item for the next DevTools sync so we can discuss how to best implement this. Will get back to you with details soon 🙏

**Comment by AleksanderBodurri** [comment]
We discussed this feature and have a good idea on how to implement it. Instead of creating another panel on side that contains this information in the flamegraph visualizer, we will instead display this information in the Bar chart visualizer.

**Current state**: Bar chart visualizer displays a bar for every component instance and sorts them in order from the longest time spent in change detection to the shortest.

Notice how this is very close to the feature you're proposing. We propose that the bar chart behaviour be changed to "flatten" instances into component types, so that the new behaviour becomes,

**Desired state**: Bar chart visualizer displays a bar for every component type and sorts them in order from the longest time spent in change detection to the shortest.

Since the flamegraph can already inspect component instance level change detection timings, we don't lose much by changing the bar chart visualizer in this way. Users could use the bar chart visualizer to see timings at the component type level, and the flamegraph visualizer to see them at the component instance level.

Let me know if you want to work on this and I'll assign it to you 🙏

**Comment by eneajaho** [comment]
Hello @AleksanderBodurri 
Great! I'll take it!
