### ISSUE TITLE
Style child component ViewEncapsulation.Emulated

### ISSUE THREAD

**Issue by tandu** [angular/angular#5064]
How to change styles in child component from parent when ViewEncapsulation.Emulated? I think it is a common thing that happens with reusable component. For example, my-button component can have different background color:
parent component:
```css
/*button color in parent component is red*/
my-button {
  background-color: red;
}
```
my button component
```css
/*button is yellow by default*/
:host {
  background-color: yellow;
}
```
Right now it doesn't work. All styles are encapsulated and can only affect components in which they are defined.

**Comment by gnomeontherun** [comment]
Have you tried this?

```css
my-button::shadow {
  background-color: red;
}
```

**Comment by tandu** [comment]
No, thank you for pointing out. Actually `my-button` styles work without ::shadow as well. My example was too simple. Let's say that button has `span`. When I try either `my-button::shadow span` or `my-button span::shadow` it doesn't work.

**Comment by gnomeontherun** [comment]
Do you have a code example somewhere to view? I'm looking at similar things and trying to understand how styles are rendered in different encapsulation modes. It would be useful to see a working example.

**Comment by tandu** [comment]
http://plnkr.co/edit/xeRFuLpdQdzNnmZBiOAE?p=preview

**Comment by gnomeontherun** [comment]
This seems like a bug in the way that selectors are rendered.

Anytime you try to do multiple selectors, it applies the same custom attribute (which appears to be incorrect). So doing this doesn't work because the same attribute doesn't exist on all children in the template. It doesn't matter how you write the selector, Angular adds the wrong attribute.

<img width="1146" alt="screen shot 2015-11-02 at 12 27 54 pm" src="https://cloud.githubusercontent.com/assets/79500/10890361/3de906a8-815d-11e5-91a0-281bb2b9cba6.png">

```
//our root app component
import {Component, View} from 'angular2/angular2'
@Component({
  selector: 'my-button'
})
@View({
  template: `
    <div>
      <span>text</span>
    <div>
  `,
  styles: [`
    :host span {
      color: red;
    }
  `]
})
export class MyButton {
}

@Component({
  selector: 'my-app'
})
@View({
  template: `
    <my-button class="first"></my-button>
    <my-button class="second"></my-button>
  `,
  styles: [`
    my-button.second span {
      color: blue;
    }
  `]
  directives: [MyButton]
})
export class App {
}
```

**Comment by tandu** [comment]
It is intended behavior when css encapsulation is enabled to isolate css styles to component on which they are defined, but there should be a way to set child component styles from its parent otherwise it is hard to reuse component in another application or another place in the same application that requires it to look differently.

**Comment by HoBi** [comment]
Is there any hope somebody fix this (I hope I talk about the same thing)? 

If I use similar selectors (for example classes like `.block`, `.input` or so) in multiple elements and then use some of elements inside another, all styles from parent element are rendered to the child elements. Also the styles from parent elements rewrites styles from child elements.

I also can not use the Shadow DOM ViewEncapsulation, because it is not well supported (http://caniuse.com/#feat=shadowdom).

I would like to have some way I can only change styles inside elements (e.g. `ng-content`) using something like `::shadow` or `::content` pseudo elements.

---

So this code will only affect the first element with class `.text` -> "lorem ipsum".

```html
<my-alpha>
  <span class="text">Lorem ipsum</span>
  <my-alpha>
    <span class="text">Dolor sit amet</span>  
  </my-alpha>
</my-alpha>
```

```css
my-alpha .text {
  color: red;
}
```

**Comment by bennylut** [comment]
+1 This is an important issue in my eyes, it actually makes ViewEncapsulation.Emulated inapplicable in many cases..

**Comment by soumya92** [comment]
> it is hard to reuse component in another application or another place in the same application that requires it to look differently

Absolutely! I've encountered this in a simple graph component that spits out some SVG. Ideally styles like:
`simplegraph { stroke: red, stroke-weight: 4, fill: yellow }` could be inherited, or at least queried within the component, so that the generated `<path d="...">` can be styled appropriately.

**Comment by tandu** [comment]
@HoBi In your case you need to use shadow dom emulation `ViewEncapsulation.Emulated`. Or use another css:
```css
my-alpha>.text {
  color: red;
}
```
This thread is about `ViewEncapsulation.Emulated` mode limitation.

**Comment by zoechi** [comment]
`/deep/`and `::shadow` are deprecated since a while and will be removed. The purpose of view encapsulation is to prevent styles from outside bleeding in. If you want this, set encapsulation to `None`, otherwise add the styles directly to the component. 
Polymer uses CSS variables and mixins to create hooks elements to be styled from the outside. This might be an interesting option for Angular as well for dynamically styling elements at runtime.

**Comment by tandu** [comment]
`Emulated` allows to simplify css rules and encapsulates rules within components, I don't want to switch back to `None` to style components from outside, I need such feature in `Emulated` mode.

**Comment by zoechi** [comment]
Sure, but you seem to want encapsulation **and** styling from the outside. This was dropped from the custom elements spec for good reasons, and it seems Angular tries to align with that spec.

**Comment by tandu** [comment]
I understand that styles are encapsulated, there need to be a way to style internal component elements, for example, as it was suggested above use `::shadow` or any other custom rule that might be parsed by compiler in css.
```css
my-button.second::shadow span {
  color: blue;
}
```

**Comment by zoechi** [comment]
`/deep/` and `::shadow` was explicitly removed from web components because it was considered a bad idea. 
What do you actually try to accomplish? 
Maybe `:host(.someClass) {}` can solve your problem? 
See also http://stackoverflow.com/questions/34979260/angular-2-apply-conditional-style-to-a-directives-child-html-element

**Comment by tandu** [comment]
No, `host:` is used to define styles on root dom element of component itself. The example of what I need is:
You have created custom button component. Then you create 2 instances of it and what one of it to be red and another blue. Later you copy component to another project and want it to be purple. All of this should be made without changes in component itself so that it is really portable component. Styles need to be applied to component internal elements.

**Comment by zoechi** [comment]
Import a style file containing different styles into the button component and choose the concrete style by adding a class to the button. If the button should use different styles in another project modify the external styles file.

**Comment by tandu** [comment]
Thank you. I will use class to change component styles. But ideally I still would like an ability to edit its styles the way the component doesn't know about it so that if I remove let's say parent component with green button there is no need to go to button component and remove green style from its css.

**Comment by zoechi** [comment]
dup of #6511?

**Comment by ehsanul** [comment]
I'm experiencing a similar situation. I have a component attached to a route, with several child paths pointing at different components. All these components should have the same style for their h1s, but I don't want to repeat the style on each child component.

I thought I could apply the style to the parent component, since all children of that parent component should share style, but it's now obvious to me that that can't possibly work while keeping the encapsulation working as expected for all other cases. It would be nice if I could specify via some mechanism that a particular style is meant for child components.

**Comment by zoechi** [comment]
`>>>` and `/deep/` were added a while ago. See the issue #6511 (I linked in my comment above)

I guess this issue can be closed.

**Comment by Draethorian** [comment]
This is stupid, can't we just declare inheritance in the component?

`@Component({
  moduleId: module.id,
    selector: 'math',
  templateUrl: 'math.component.html',
styleInheritance: parent
`

**Comment by dhrumil4u360** [comment]
+ 1 for this. No doubt that Emulated mode encapsulate the styles. But Encapsulation should maintain parent child hierarchy. It's expected behavior. So, definitions should flow top to bottom. Encapsulation will of course stops flow from bottom to top.

**Comment by dhrumil4u360** [comment]
@zoechi  I understand when you mention that you can't have encapsulation and styling from outside together. I  also understand that specification thought that "The purpose of view encapsulation is to prevent styles from outside bleeding in."

Shouldn't the purpose be "to prevent bleeding out" instead of "bleeding in" ? I think, we don't want to replace other component's style accidentally and that is the purpose, right ? So, parent style can get in but component styles should not affect outer world.

If I would have wanted completed isolated area, I would rather go for "Native" option. Because that will create native shadow DOM and none of parent style will get inside unless explicitly specified.
