### ISSUE TITLE
Stated generated boilerplate not present (for empty constructor, `ngOnInit`  interface or `ngOnInit` method)

### ISSUE THREAD

**Issue by mangelozzi** [angular/angular#50825]
### Describe the problem that you experienced

Reading through the great docs, but when I got to:

https://angular.io/start#pass-data-to-a-parent-component says:

> In new components, the Angular Generator includes an empty constructor(), the [OnInit](https://angular.io/api/core/OnInit) interface, and the ngOnInit() method. Since these steps don't use them, the following code examples omit them for brevity.

I have been following the example, but I can't see an empty constructor, `ngOnInit`  interface or `ngOnInit` method. Maybe I am not looking in the right place (`product-alerts.component.ts`), in which case maybe add some clarification where this code is, or maybe they are no longer generated? Or Option C I am totally missing something obvious.

Cheers!

### Enter the URL of the topic with the problem

https://angular.io/start#pass-data-to-a-parent-component

### Describe what you want to experience that would fix the problem

Trying to follow along

**Comment by sunilbaba** [comment]
Hi @mangelozzi,

 As stated in the documents: https://angular.io/start#pass-data-to-a-child-component while creating a new component using the Angular CLI command mentioned under section 2: `ng generate component product-alerts` 
 
  Angular will generate a new component and add it to the associated module. Below is the code Angular generator will generate 
 ```
import { Component, OnInit } from '@angular/core';

@Component({
  selector: 'app-product-alerts',
  templateUrl: './product-alerts.component.html',
  styleUrls: ['./product-alerts.component.css']
})
export class ProductAlertsComponent implements OnInit {

  constructor() { }

  ngOnInit() {
  }

}
```
The generator code includes ngOnInIt, the constructor, and their imports.  As mentioned in the documents Since these steps don't use them, the following code examples omit them for brevity.

**Comment by JeanMeche** [comment]
@sunilbaba This is not true since v15. The schematics won't create an empty constructor or an empty `ngOnInit()`

**Comment by sunilbaba** [comment]
@JeanMeche  - Yes you are correct. Schematics won't create an empty constructor or empty ngOnInit(). 

 Should I raise a PR by removing the below information from that page ? 
 
 In new components, the Angular Generator includes an empty constructor(), the [OnInit](https://angular.io/api/core/OnInit) interface, and the ngOnInit() method. Since these steps don't use them, the following code examples omit them for brevity.

**Comment by JeanMeche** [comment]
@sunilbaba Yes, we should remove that warning ! Feel free to open a PR 👍

**Comment by cbuahin** [comment]
Am

**Comment by sunilbaba** [comment]
Hi @JeanMeche 

Fix is merged to master. Can we close this issue
