### ISSUE TITLE
[transpiler] Wrong handling of string templates

### ISSUE THREAD

**Issue by yjbanov** [angular/angular#509]
In Dart string interpolation works regardless of quote style. In ES6 string templates perform interpolation and old-style strings do not. The transpiler is unaware of that and therefore produces wrong result.

This:
```
var a = 1;
var s1 = '${a}';
var s2 = `${a}`;
```

Transpiles to this:

```
var a = 1;
var s1 = '${a}';
var s2 = '''${a}''';
```

Which is wrong. I believe this currently results in a bug with `$event` in DOM event binding.

**Comment by alexeagle** [comment]
I tried reproducing this issue in the existing tests, in lang_spec.js
```javascript
it('string interpolation quote style', function() {
      var a = 1;
      var b = `${a}`;
      var c = '${a}';
      expect(b).toEqual('1');
      expect(c).toEqual('${a}')
    });
```
However, the test passes incorrectly. The reason is that the test is run through the transpiler as well, so the assertion executed in the test becomes
```javascript
it('string interpolation quote style', () {
      var a = 1;
      var b = '''${a}''';
      var c = '${a}';
      expect(b).toEqual('1');
      expect(c).toEqual('${a}');
    });
```

in other words, the bug is applied to the expected as well as the actual.

I think the right solution is a new test fixture which allows us to simply execute the compiler on a small snippet, and assert what dart code it produces, without executing it. That should just run in node, not in a browser. So I think we could use Mocha as the test runner and add a simple test case for this.
(That has the added advantage of being easy to debug, since it doesn't transpile the test. Now I can easily step through the transpiler in webstorm, which isn't possible in the gulp+transpile+karma setup.)

Will send a PR for that.
