### ISSUE TITLE
Unable to avoid flickers even though I applied hydration

### ISSUE THREAD

**Issue by hebaibrahim76** [angular/angular#50936]
### Which @angular/* package(s) are the source of the bug?

platform-browser

### Is this a regression?

No

### Description

I have the following angular ssr application https://github.com/hebaibrahim76/my-angular-ssr-project
**I have applied hydration to my project** and it's working as expected (the console prints the hydration message)
I created a switch between dark and light mode
If i switch to dark and then reload the page, for a short time, light mode appears, and then dark mode gets applied
So there is a flicker going on, I expected that hydration would fix this flicker but it didn't

**Comment by AndrewKushnir** [comment]
@hebaibrahim76 thanks for providing a repro. As @JeanMeche mentioned above, the behavior (flicker) is expected in the described scenario, since the server renders a light mode version on the server and after that on the client, the mode switches to the dark one when JS is loaded. The solution might be to update the code of the application to render the currently active mode that a user selected. As a possible solution, you can store the mode setting in a cookie, check for its value on the server ([somewhere here](https://github.com/hebaibrahim76/my-angular-ssr-project/blob/main/server.ts#L42)), pass this value as a special injection token and take the value into account while rendering.

I'm closing this ticket, since there the changes are required in the app code, not the framework.
