### ISSUE TITLE
booleanAttribute transform functions yields incorrect results for `'null'` and `'undefined'`

### ISSUE THREAD

**Issue by sunilbaba** [angular/angular#50984]
### Which @angular/* package(s) are the source of the bug?

common

### Is this a regression?

No

### Description

As part of angular 16, we have a few predefined transform functions we're provided as ready to use. 

booleanAttribute returning the result as **true** for null and undefined for value property.

Is there any specific reason for not having a double equal operator check for null in booleanAttribute function, as well as check for undefined as well.

export function booleanAttribute(value: unknown): boolean {
  return typeof value === 'boolean' ? value : (**value !== null** && value !== 'false');
}

### Please provide a link to a minimal reproduction of the bug

https://stackblitz.com/edit/stackblitz-starters-jkh8jt

**Comment by JeanMeche** [comment]
The code behind `booleanAttribute` is older than the transform feature, see #42803. 

Changing that would probably break many apps in subtle ways.

**Comment by sunilbaba** [comment]
Yes, @JeanMeche. Created strings with values of null and undefined as below. Whereas same works for numberAttribute but not for booleanAttribute

booleanAttribute('undefined'); -> result : **true**

numberAttribute('undefined'); -> result: **NaN**

**Comment by JoostK** [comment]
This isn't a bug. These functions are intended to cover the case where an attribute like `disabled` is present without a value, where `disabled` is consumed as a directive/component input of type boolean. The presence of the `disabled` attribute then writes an empty string into the binding, which should be interpreted as `true` since the attribute is present.

Alternatives like `disabled="disabled"` appear in the wild, since the XHTML days required that all attributes had a value. For arbitrary reason it became a convention that the name of the attribute was simply repeated as value, but _any_ value suffices in order to activate that behavior from HTML's perspective. Hence, the strings `'null'` and `'undefined'` are just as well values that should initiate the presence of the attribute, hence being represented as `true`.
