### ISSUE TITLE
`canceledNavigationResolution: computed` + `canDeactivate: false` results unexpected behavior

### ISSUE THREAD

**Issue by JounQin** [angular/angular#50983]
### Which @angular/* package(s) are the source of the bug?

router

### Is this a regression?

Yes

### Description

https://github.com/angular/angular/assets/8336744/e7bc4922-fd69-4e64-badf-e76a494fefd8

When clicking `back` button in `/edit` page, the location is changed to `/list` unexpectedly.

### Please provide a link to a minimal reproduction of the bug

https://stackblitz.com/edit/stackblitz-starters-rxjjhw

### Please provide the environment you discovered this bug in (run `ng version`)

```true
Angular CLI: 16.1.3
Node: 18.16.0
Package Manager: yarn 1.22.19
OS: darwin arm64

Angular: 16.1.3
... animations, cdk, cli, common, compiler, compiler-cli, core
... forms, language-service, platform-browser
... platform-browser-dynamic, router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1601.3
@angular-devkit/build-angular   16.1.3
@angular-devkit/core            16.1.3
@angular-devkit/schematics      16.1.3
@schematics/angular             16.1.3
ng-packagr                      16.1.0
rxjs                            7.8.1
```

**Comment by garrettld** [comment]
This appears to be happening when you use location.back() or the browser back button to go back to the first page you loaded.

The browser page id isn't being set on the first navigation, and the logic that restores the URL on cancelled navigation appears to depend upon it being set. If you navigate once to another page before following your reproduction steps, the 'back' works fine because you're no longer going back to the initial navigation.

I was able to work around this by doing an extra navigation when the app loads by calling `this.router.navigateByUrl(this.router.url)` in your root component's constructor.

**Comment by JounQin** [comment]
Any luck to resolve this issue?
