### ISSUE TITLE
Inputs on Child Components given as method calls inside templates break in production

### ISSUE THREAD

**Issue by AndreiSerbanJLG** [angular/angular#51020]
### Which @angular/* package(s) are the source of the bug?

core, elements

### Is this a regression?

No

### Description

First of all, sorry if the explanation will not be exactly technical. I will try to explain as best I can what is happening and where the breaking points may be so that you may investigate further.

Context: There are two components: **ParentComponent**, with irrelevant content, containing a **NestedDropdownComponent** which receives as input a list of _Items_ from the **ParentComponent**.

**ParentComponent** gets a list of _fields_ from the backend, but for the **NestedDropdownComponent** to work, these _fields_ need to be mapped to _items_, which is done through an injected mapper service, called simply **MapperService**.

There are two ways this can be done:

`1)`
**ParentComponent.ts**

`ngOnInit() {`
`this.fields$ = getFieldsAsObservable();`
`this.fields$.subscribe(fields => this.items = mapperService.map(fields));`
`}`

**ParentComponent.html**

`<tk-nested-dropdown [items] = "items"> </tk-nested-dropdown>`

------------------------------------------------------------------------------------------------------------------------

`2)`
**ParentComponent.ts**

`ngOnInit() {`
`this.fields$ = getFieldsAsObservable();`
`}`

**ParentComponent.html**

`<ng-container *ngIf="fields$ | async; let fields">`
`<tk-nested-dropdown [items] = "mapperService.map(fields)"> </tk-nested-dropdown>`
`</ng-container>`

**In dev environment** (ng served), both implementations work as intended with no issues whatsoever. 

**In prod environment** (ng build), implementation `2)` stops working. When trying to select an item from the `NestedDropdownComponent`, the item is not selectable.

From my investigation, the click event does not register on the element upon inspection, however on click the focus jumps on a "child" element simply named comment. 

**Before click**
![image](https://github.com/angular/angular/assets/139352684/0bc47fe3-f231-4103-9fc4-10290246094f)

**After click**
![image](https://github.com/angular/angular/assets/139352684/682c8630-1b9e-4d04-894d-fa749978d816)

### Please provide the environment you discovered this bug in (run `ng version`)

```true
Angular CLI: 15.0.3
Node: 18.12.1
Package Manager: npm 8.19.2
OS: win32 x64

Angular: 15.0.3
... animations, cli, common, compiler, compiler-cli, core, forms
... localize, platform-browser, platform-browser-dynamic, router
```

**Comment by JoostK** [comment]
Calling `mapperService.map(fields)` from a template will execute the `map` method on each change detection cycle, resulting in recreating the output array and all its items. Consequently, `ngFor` observes a completely new array with new items each time, and because there is no `trackBy` logic to identity the different item instances this results in complete teardown of the DOM each and every time, causing the listeners to be destroyed along with it.

---

Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).
