### ISSUE TITLE
Signal subscription counter

### ISSUE THREAD

**Issue by muhamedkarajic** [angular/angular#51167]
### Description

My scenario is that we have a store and when you use the object in a lot of places at some point you want to check if its still needed and if not garbage collect that object by remove it from the list and freeing up memory.

We use ofc Behavior/ReplaySubject-s for it however I wonder if it would be possible to do it with signals since they are going to be long term a better and more performant solution.

### Proposed solution

signalObject.subscriptionCount //gives you the number of subscriptions that the signal holds
signalObject.subscriptionChangeEvent //some event that will let you know if the subscription number has changed so you can update your view, create new Date etc

### Alternatives considered

Please consider that this is really really mandatory for some enterprise solution cause in other way I would have to still keep using the Subjects patterns to monitor how many things are subscribed/unsubscribed and when the subscriptionCount fell to 0.

Or offer me some alternative solution but I kind of don't like the option to transform it to a observable and then in each component transform it back to an signal. Sounds pretty memory intensive pattern.

**Comment by simeyla** [comment]
Signals don't have 'subscribers' in the same way that RxJS Observables do. 
They have consumers and producers tracked by a 'ReactiveNode' (see [graph.ts](https://github.com/angular/angular/blob/main/packages/core/src/signals/src/graph.ts) and the original [RFC](https://github.com/angular/angular/discussions/49684)).

But since they're tracked by WeakRefs there wouldn't ever be a **guarantee** of number of subscribers even if they did expose something like `hasProducers` or `hasConsumers` or even `isOrphaned`. 

As an aside I'd personally appreciate access into some of the internals of a signal for debugging purposes. There is other VERY useful data hidden away such as the number of 'versions' a `computed` has produced and how many times the calculation has been run. Right now the only way to access them is via the `SIGNAL` symbol, which is impossible to access outside devtools.

I'd love to see something like for debugging: 

```
signalMetadata(signal: Signal<T>) => 
     { hasConsumers: boolean, hasProducers: boolean, calculationCount: boolean, versionCount: boolean }
```

Even if this was added, they'd never expose the counts because they'd be misleading and never up to date.

So I think what you're looking for is basically impossible to add. Consider the dependencies of a computed. As you know a `computed` won't always have the same dependencies over its lifetime. (This is a *bit* like a switchMap in that sense). 

    themeColors = computed(() => theme() == 'dark' ? darkTheme() : lightTheme())

`darkTheme` is only tracked by the `computed` if `theme()` is currently dark. So `lightTheme` right now has no connection in the graph to any other signals. But does that mean it's unused? If you deleted it then as soon as the theme changed it wouldn't be there anymore. This is clearly nothing like your code but I think this general idea would apply to you too. The point being the dependencies only exist because of the weak graph and signals can't offer the metadata you want in any kind of reliable way. 

I think you'll need to create a completely different tracking mechanism. Possibly using WeakRef, but that's rarely actually the right solution even if it may sound appealing at first. 

Two of many things I've learned with migrating from RxJS to Signals is 1) you have to be very careful 2) you have to be willing to throw out old code. You may find a much better way to organize things than you already have.

**Comment by JeanMeche** [comment]
Hi, I'll close this as it has already been discussed in #50182.
