### ISSUE TITLE
ActivatedRoute.url not emit new value when child route has change after upgrade v16

### ISSUE THREAD

**Issue by xujing0521** [angular/angular#51439]
### Which @angular/* package(s) are the source of the bug?

router

### Is this a regression?

Yes

### Description

```
{
        path: 'workspace',
        component: WorkspaceComponent,
        children: [
            { path: 'list', component: ListComponent },
            { path: 'detail', component: DetailComponent },
        ]
}
```

This code snippet worked fine in v15 in WorkspaceComponent, when i switch in list and detail，can subscribe value in next handler， but v16 cannot
```
 this.route.url.subscribe(data => { 
  // ...
  }) 
```

### Please provide the exception or error you saw

```true
"@angular/router": "^16.2.1"
"@angular/core": "^16.2.1",
```

### Please provide the environment you discovered this bug in (run `ng version`)

[https://stackblitz-starters-hlct4x.stackblitz.io/](url)

**Comment by atscott** [comment]
Please provide an example stackblitz

**Comment by xujing0521** [comment]
https://stackblitz-starters-hlct4x.stackblitz.io
the v15 dependencies in v15.json

**Comment by xujing0521** [comment]
> Please provide an example stackblitz

https://stackblitz-starters-hlct4x.stackblitz.io/
the v15 dependencies in v15.json

**Comment by JeevanMahesha** [comment]
@xujing0521 please share the stackblitz alone with the code which you done the link you share is only shows the output. please correct me if I'm wrong

**Comment by atscott** [comment]
@xujing0521 Thank you for the reproduction. As it turns out, v16 is more correct. The observables on the `ActivatedRoute` are only meant to emit when something has changed. Even in v15, you'll notice that if you change your links to be relative rather than from root (remove the `/workspace/` from the links), you'll see the observable does not emit. If you need to know whenever a navigation happens, you can subscribe the the router events instead.
