### ISSUE TITLE
Cold Signals?

### ISSUE THREAD

**Issue by ShacharHarshuv** [angular/angular#51542]
### Which @angular/* package(s) are relevant/related to the feature request?

core

### Description

One of the things I like about the Angular's signal API, is how the `computed` signal is both lazy (runs only if needed) and shared (results are not recalculated between consumers). 

As I imagine the future of using signals as a replacement of RxJS (at least, in most cases), I was wondering how would an HttpClient that returns a signal will look like. 

Of course - we can wrap the HttpClient with `toSignal` to return a signal, but the problem is that that would make an immediate subscription that will cause a request to be sent, even before the signal was used. Ideally, we would want to create signals, and have them send the request only when needed (aka - lazily).

I [tried to work around ](https://stackblitz.com/edit/stackblitz-starters-c1pndt?file=src%2Fmain.ts) this issue using `computed`, but it didn't work as creating "setting a signal" is not allowed inside a computed callback. 

### Proposed solution

One option is to allowed writing to signals inside a computed, like can be allowed with effects:

```
effect(() => {
...
}, {
  allowSignalWrites: true,
})
```

So the workaround will work.

Another option is to allow for cold signals in the `toSignal` callback:

```ts
toSignal(myObseravble$, { lazy: true })
```

In this option - the observable will be subscribed to only on the first time that the signal is read. 

### Alternatives considered

See multiple options in proposition above.

**Comment by pkozlowski-opensource** [comment]
> As I imagine the future of using signals as a replacement of RxJS (at least, in most cases), I was wondering how would an HttpClient that returns a signal will look like.

We don't intended signals to be a replacement for RxJS. More specifically, signals are not a good fit for a `HttpClient` return value as HTTP request is more of a one-off event rather than a value over time. It is a different concept.

> In this option - the observable will be subscribed to only on the first time that the signal is read.

This wouldn't quite work as a signal needs a value. Here the read of a signal would cause an async operation and wouldn't provide value that signal needs.

We will continue to explore patterns around asynchronous operations (including `HttpClient`) and share those as soon as we have something workable. But I don't think that "cold" signals are the answer here as it would invalidate some of the fundamental assumptions - assumptions that make signals so attractive.

I'm going to close this issue for now as there is nothing immediately actionable for us here. We do continue exploring patterns around signals usage, though.

**Comment by ShacharHarshuv** [comment]
I imagined that signals that hold values that are from the server would hold a "loading" state when the value is not there, no? That makes sense from a UI perspective because you can use that value to display a loader. 

I'm definitely interested to see how the more modern patterns with the HttpClient will look like. Seems like converting every stream to signal could be problematic because it could cause eager loading of the data.
