### ISSUE TITLE
stopImmediatePropagation not working when triggering (click) with the keyboard

### ISSUE THREAD

**Issue by fdeslandes-wk** [angular/angular#51608]
### Which @angular/* package(s) are the source of the bug?

Don't known / other

### Is this a regression?

No

### Description

When using "Enter" on the keyboard to click a focused element with the (click) listener and using stopImmediatePropagation to prevent parents from receiving the event, a parent element with the (keydown) listener will still receive the event.

### Please provide a link to a minimal reproduction of the bug

https://stackblitz.com/edit/angular-fs11qt?file=src%2Fmain.ts

### Please provide the environment you discovered this bug in (run `ng version`)

```true
Angular 16.2.3
```

**Comment by jessicajaniuk** [comment]
This is WAI. Here's what's happening in this case. The keyboard event is actually bound to the parent button and is fired by the parent button. When you hit enter on the inner button it's actually firing two events, one click event for the inner button and one keyboard event for the parent button. The click event is being stopped by the `stopImmediatePropagation`, but the keyboard event is not because of the scoping here.

Also worth noting that the stackblitz example has invalid HTML. You cannot put a button inside another button. Natively a click is fired when Enter is pressed on a button. So that's why a click is firing at all when Enter is pressed on the nested button. If it's changed to a span with a tabindex, the click event does not fire.
