### ISSUE TITLE
Keyboard events on div are not fired.

### ISSUE THREAD

**Issue by tandu** [angular/angular#5168]
I've tried to listen to keyboard events in component that way:
```html
<div (keyup)="handleKey($event)"></div>
```
but `handleKey()` method is never called. The only way to handle keyboard that I have found is to add event listener to `document`:
```typeScript
  private handleKeyBind: {()};

  constructor() {
    this.handleKeyBind = this.handleKey.bind(this);
    document.addEventListener('keyup', this.handleKeyBind, false);
  }

  private handleKey(event: KeyboardEvent) {
    switch(event.keyCode) {
      case 37: console.log(37) break; // left arrow
    }
  }

  onDestroy() {
    document.removeEventListener('keyup', this.handleKeyBind, false);
  }
```
Am I missing something or is it the official way to handle keyboard events in component?

**Comment by ericmartinezr** [comment]
I've been looking at this and I found out one thing

- You can't listen to key events on a div by default, you must set `tabindex` to make it selectable/focusable, see this [SO answer](http://stackoverflow.com/questions/3149362/capture-key-press-or-keydown-event-on-div-element) and [this one](http://stackoverflow.com/a/1718035/4933038)

With an `input ...text` it will work with no problems
```
`<input type="text" (keyup)="handleKey($event)" />
```

And you can see here some shortcuts for using key events https://github.com/angular/angular/commit/8fa1539bacd454635d1f78ab056e2017929d0634

Your solution worked because your were listening to it in the document, while in your template your were listening it in the div.

**Comment by pkozlowski-opensource** [comment]
@ericmartinezr is right - `div` won't fire key events without `tabindex`. 
@ericmartinezr thnx so much for helping out with issues - this is very much appreciated!
