### ISSUE TITLE
Bun 1.0 is possible to be used with Angular

### ISSUE THREAD

**Issue by muhamedkarajic** [angular/angular#51694]
### Description

Since Angular came a long way I would like to suggest that we consider making it possible to use alternatives to nodejs such as bun. 

This would allow more havy functionalities for the Angular CLI as well as quicker compile times.

### Proposed solution

Offer a pluggable way for nodejs alternatives if possible.

### Alternatives considered

Maybe its not streight forward and the angular team will have to 'support' such options similar to the esmodue builds.

**Comment by JeanMeche** [comment]
Hi, this subject has been discussed in #46719. See the rationale over there, to why it's not supported.

**Comment by CMiksche** [comment]
> Hi, this subject has been discussed in #46719. See the rationale over there, to why it's not supported.

But first of all the discussion was based on a old Bun version which didn't support so many node APIs and caused problems this way and secondly, #46719 is mostly about SSR while Bun could be used for so much more (testing, bundling,...)

We could replace Jasmine, Webpack and more with Bun. A first integration of Bun doesn't mean we have to use it for everything - we could start with one small part of the functionality Bun offers. The compatibility with node is the great thing about it

**Comment by jdgriffith** [comment]
@alan-agius4 @JeanMeche Could we keep one of these issues open? Bun could definitely be used to improve the DX and I agree with @CMiksche, it does not have to be used for everything. Please consider re-opening one of the issues and taking a good look at where bun is today.

**Comment by alan-agius4** [comment]
@jdgriffith, we definitely will keep an eye on Bun and the JavaScript eco system as a whole. 

That said, supporting Bun is not something that we have planned in the near future. Furthermore, using Bun as a test runner and/or bundler does not align with the design CLI goals, to make Angular more environment/runtime agnostic.

Additionally as mentioned in previous comments, Bun does not support patching which for Angular is critical due to Zone.JS and how it works.

Hence, re-opening this issue provides little to no value.

**Comment by jdgriffith** [comment]
@alan-agius4 Thanks for the quick response! 

Our team experiences excruciating build times in our CI pipeline for our monorepo, which is why I would like to understand this better. The build times are not even close to being inline with modern tooling and expected development flows and experience (granted, there could be _some_ things/alternatives we could try to help this).  

If patching and Zone.js is not relevant to the bundling process, couldn't bun replace esbuild even in your latest application builder (16.2 and above)? Forgive me if I'm missing something here.

**Comment by CMiksche** [comment]
> That said, supporting Bun is not something that we have planned in the near future. Furthermore, using Bun as a test runner and/or bundler does not align with the design CLI goals, to make Angular more environment/runtime agnostic.

Every single company I ever worked for replaced at one time the standard Angular test runner. Jest / Vitest are just so much faster than Jasmine and the fact that the standard TestBed also tests the DOM doesn't make any sense in 99% of the cases.

I think you should make a survey and ask your users, how many of them use your standard CLI tooling and how many already switch to things like Jest and Vite.

> Our team experiences excruciating build times in our CI pipeline for our monorepo

Same here. I seriously think Bun should be given a try or the community will anyway find a way to replace the standard bundler / test runner similar like it happened with https://github.com/thymikee/jest-preset-angular or with Vite

**Comment by alan-agius4** [comment]
Bun is not the silver bullet! 

The Angular CLI does provide 1st party integration of so called fast and modern building tools like Jest, Vite and Esbuild. While IO can be a bottleneck, especially if you are using Windows. Unfortunately, in many cases this is not the biggest problem in large applications as other underlying tools, such as Sass, TypeScript, Babel which will still be needed if Bun is used as a bundler can cause these fast tools to become slow.

If you are experiencing slow compilation time, I suggest that you open an issue containing a CPU profile so that we can investigate and determine if there is something out or the ordinary.

As a side note: It is totally okay and encouraged for the community to try new tools and expand Angular tooling.  There are a ton of great examples such as Analogjs and Jest present that you mentioned.

**Comment by jdgriffith** [comment]
I am too far in my career to believe in silver bullets 😂 

I am not suggesting this is a silver bullet. I completely realize any new thing could take considerable effort without much gain and there could be complexities and nuance here I'm unaware of.

What I am recommending is Bun should be seriously explored by the Angular team to see where improvements could be made. It is about twice as fast as esbuild currently and possibly will continue with performance improvements. And esbuild is only one spot where there could be improvements in the bundling steps - what if there are multiple areas where performance gains could not only be measured but also perceived by angular developers?

**Comment by muhamedkarajic** [comment]
Thank you for the detailed answers and quick responses. Appreciate it!

**Comment by guzmanoj** [comment]
Honestly, why is this closed? Please have a look into Bun and the benefits for DX that it could bring. Let's avoid the same mistakes again, Bun is trending (and making developers to love it) for a reason.
