### ISSUE TITLE
Reactivity: OnPush components change-detected even if nothing changed

### ISSUE THREAD

**Issue by pkozlowski-opensource** [angular/angular#51797]
### Which @angular/* package(s) are the source of the bug?

core

### Is this a regression?

No

### Description

In the current integration of signals into Angular the OnPush components are marked for check even if none of the underlying signals changed. This can happen with the longer reactivity chains where one of the computed signals is marked for re-computation but when recomputed it returns the same value. In this situation we should skip dirty-checking of such views.

Here is a minimal stackblitz demonstrating the situation: https://stackblitz.com/edit/stackblitz-starters-bxm5fu?file=src%2Fmain.ts

Given the above stackblitz, notice that the OnPush component is change detected even if non of the displayed values change. This is because components are marked for check in the signals notification phase, without any further verifications on the values produced by signals accessed in a template. 

### Please provide a link to a minimal reproduction of the bug

https://stackblitz.com/edit/stackblitz-starters-bxm5fu?file=src%2Fmain.ts

**Comment by sdedieu** [comment]
After a quick dive into the code, I can see that `this.counter.update((c) => c + 1);` triggers internally `signalUpdateFn` ([code](https://github.com/angular/angular/blob/fe81ff8cd6948bea5a6212721ea920a8572248e1/packages/core/src/signals/src/signal.ts#L135)) then `signalSetFn` ([code](https://github.com/angular/angular/blob/fe81ff8cd6948bea5a6212721ea920a8572248e1/packages/core/src/signals/src/signal.ts#L123)).
```
function signalValueChanged<T>(node: SignalNode<T>): void {
  node.version++;
  producerNotifyConsumers(node);

  postSignalSetFn?.();
}

function signalSetFn<T>(this: SignalFn<T>, newValue: T) {
  const node = this[SIGNAL];
  if (!producerUpdatesAllowed()) {
    throwInvalidWriteToSignalError();
  }

  if (!node.equal(node.value, newValue)) {
    node.value = newValue;
    signalValueChanged(node);
  }
}

function signalUpdateFn<T>(this: SignalFn<T>, updater: (value: T) => T): void {
  if (!producerUpdatesAllowed()) {
    throwInvalidWriteToSignalError();
  }

  signalSetFn.call(this as any, updater(this[SIGNAL].value) as any);
}
```
Then since we compare old version and new version of the counter value (which changed), we call for `signalValueChanged`  ([code](https://github.com/angular/angular/blob/fe81ff8cd6948bea5a6212721ea920a8572248e1/packages/core/src/signals/src/signal.ts#L116)) and then `producerNotifyConsumers` ([code](https://github.com/angular/angular/blob/fe81ff8cd6948bea5a6212721ea920a8572248e1/packages/core/src/signals/src/graph.ts#L232)) which marks every `node.liveConsumerNode` to dirty if they're not.
Problem is that we never check if `liveConsumerNode. computation()` returned a different result with the new value. 
Which should be that which mark dirty to true instead of false.
```
/**
 * Propagate a dirty notification to live consumers of this producer.
 */
export function producerNotifyConsumers(node: ReactiveNode): void {
  if (node.liveConsumerNode === undefined) {
    return;
  }

  // Prevent signal reads when we're updating the graph
  const prev = inNotificationPhase;
  inNotificationPhase = true;
  try {
    for (const consumer of node.liveConsumerNode) {
      if (!consumer.dirty) {
        consumerMarkDirty(consumer);
      }
    }
  } finally {
    inNotificationPhase = prev;
  }
}
```

I wonder if a solution could be to affect the oldNode into a variable, send to the `producerNotifyConsumers` function the old and the new node and mark as dirty only if `oldLiveConsumerNode.computation() !== newLiveConsumerNode.computation()` ?
