### ISSUE TITLE
Add option to skip the initial view transition to avoid flicker-like appearance of initial content render

### ISSUE THREAD

**Issue by naveedahmed1** [angular/angular#51815]
### Which @angular/* package(s) are the source of the bug?

router

### Is this a regression?

Yes

### Description

The recently introduced View Transition API support in the Router is fantastic. However, when working with server-rendered responses, it introduces a noticeable flickering effect. Here's what happens: when server-side rendering (SSR) is enabled and the client receives a server-rendered markup, the browser starts rendering the page on the client side.

Simultaneously, the Angular bundles are downloaded on the client. If we're using the router with `withViewTransitions`, the View Transition is applied. This transition aims to switch from the view painted using the SSR response to the view painted by the client app. Since both views are essentially the same, it results in an unwanted flickering effect. Even with the default cross-fade view transition, we observe the same page fading out and then fading back in, contributing to the flickering issue.

### Please provide the environment you discovered this bug in

```true
Angular 17.0.0-next.4
```

**Comment by AndrewKushnir** [comment]
Hi @naveedahmed1, thanks for creating a ticket.

We've perform an investigation and here are the results:

- We were unable to reproduce the problem with SSR'ed page. Since the content of a page doesn't change during hydration process, no transitioning happens. Transition may happen though for the parts of an application that is different between the client and the server (imagine a situation where an `*ngIf` has a different value on the client and on the server), but in this case the transition is expected, since there is a difference between an old and a new content.
- When you perform a client-only rendering (both for an initial or a subsequent navigation) - transition does happen, but this is also expected (animating a new content rendered on a page).

We've also looked at the https://www.mustakbil.com/ and found out that:
- the transition doesn't happen after an initial page load after SSR, if the ServiceWorker has an empty cache
- the transition happens after a page refresh, when a content is being served from the ServiceWorker cache -- in this case Angular performs a client rendering

If you observe a different behavior and a view transition happens on an SSR'ed page after hydration, please let us know. It'd be helpful to have a repro in this case, so that we can perform further investigation.

Thank you.

**Comment by naveedahmed1** [comment]
Thank you so much @AndrewKushnir for your reply.

The reason you are not seeing it on https://www.mustakbil.com/ is because we have added a css class to html element:

`<html lang="en" prefix="og: http://ogp.me/ns#" class="app-start">`

```
.app-start {
  view-transition-name: app-start;
}
```

This skips the View transition when this class is applied on the html element.

On client side, in AppComponent we remove this class from html element on first user interaction. So that on subsequent client side navigations, the View Transitions work normally.

One more thing, on development environment I see the transition being applied even before the hydration message is printed on console.

`Angular hydrated 40 component(s) and 1432 node(s), 0 component(s) were skipped. Note: this feature is in Developer Preview mode.`


Let me see if I can share the reproduction repo.

**Comment by naveedahmed1** [comment]
@AndrewKushnir I have added you to a private repo. Using that repo you should be able to reproduce the issue.

This issue will go away if you open `critical.scss` file and uncomment the class `.app-start` at the end of this file.

**Comment by naveedahmed1** [comment]
@atscott I have added you as well.

**Comment by atscott** [comment]
@naveedahmed1 I'm not sure that's what we've observed. When javascript is disabled, the application renders as a blank page (in the router-outlet content) due to the service worker. So from what we can see, it's not a "flicker" but rather a transition in of the first content.

Regardless, I think it's a reasonable request to skip the transition on the initial load.

**Comment by naveedahmed1** [comment]
Thank you @atscott for this addition.

Is there any public api that allow use to enable or disable view transitions on demand for example for particular navigations?

**Comment by atscott** [comment]
>Thank you @atscott for this addition.

> Is there any public api that allow use to enable or disable view transitions on demand for example for particular navigations?

This should be covered by #51827. It would be a bit awkward as an option in the call to `router.navigate` in that it's meaningless when the feature isn't enabled but I'm totally open to further discussion about what other APIs we could have for this.
