### ISSUE TITLE
Implement ng-control-array for template driven forms

### ISSUE THREAD

**Issue by choeller** [angular/angular#5185]
Currently ControlArrays are connected to the form via the ng-control-group Directive. This works fine, when using the model-driven approach. 

When using template-driven approach there is currently no way to create ControlArrays declaratively. So it is not possible to create arrays of values in this scenario.

**Comment by choeller** [comment]
Hmm, 

so when thinking about this a little further, I realized, that this is not too easy. So in template-driven approach, the controls are created automatically from the ng-control-group and ng-control directives in the template. But how could that work with ControlArrays? So I see no clean way of adding a Control to a ControlArray via template... 

So does that mean, that the template-driven approach is only making sense when using ng-model as the driver for rendering controls in an array? Would be cool to hear other opinions about that.

**Comment by tycho01** [comment]
I was just considering this as well.
If I'm following your train of thought correctly, if we currently had an `ngControlArray` directive, we'd be at the point where we could add a button with like `(onClick)="ctrlArr.push(ctrl)"`.

That does still feel awkward to me as well, since I imagine the common use-case for `ControlArray` would be to say have one `Control` blueprint baked in so as to add a control from that when clicking on some `+` button. I'd feel inclined to subclass it with a `ControlList` with no-param `push()` that'd take such a blueprint in its constructor; a corresponding directive for use from the template could perhaps allow specifying this as a parameter as well.

Assuming this *would* facilitate the majority of use-cases of people resorting to `ControlArray` though, it would be nice to see something like it supported by Angular itself as well, be it as an optional constructor parameter for `ControlArray` or as a higher-level subclass.

If so, this could use some feedback though... too bad the Angular team seems swamped by the number of outstanding issues. `:(`

**Comment by tycho01** [comment]
Sorry, correction -- based on the [official plunker](http://plnkr.co/edit/23DESOpbNnBpBHZt1BR4?p=preview) demonstrating `ControlArray`, it seems that `ngControlGroup` just doubles as an `ngControlArray`. As to that pushing example I gave, so this the plunk does so through their `addCity`. I just tried replacing the `addCity()` in that template with `addCity`'s `citiesArray.push(new Control(''))` so as to test out your idea, but yeah, that part doesn't work; I'm not sure as to specifics, but I'm aware context in the templates is very limited, so I'm pretty sure it's currently crashing on that `new Control` part -- on either keyword or both.

You could try my suggestion of sub-classing `ControlArray` so as to get a parameter-less method on it, though this'd just shift the problem to having to inject the `Control` into the `ControlList`'s (or whatever you're gonna call it) constructor, so either way that's currently still gonna be outside of the template...

Might be possible to device a way to be able to somehow have that logic in the template, but this'd sorta beg the question, why bother?

**Comment by kara** [comment]
This looks like a stale version of https://github.com/angular/angular/issues/9615, so closing as a duplicate. Thanks for reporting!
