### ISSUE TITLE
NgFor with index & input event-binding messes up UI

### ISSUE THREAD

**Issue by choeller** [angular/angular#5188]
When using a NgFor loop to create a list of input fields, and then trying to fill those fields, the UI behaves quite strange. In this plnkr:

http://plnkr.co/edit/fpAfetTUKeYlfDcr7cf9?p=preview

Press the "Add Tag" Button twice. Then fill the first Field and afterwards click into the second. 

In this case the value entered into the first field gets displayed in the second one. The model nevertheless is correctly filled.

**Comment by pkozlowski-opensource** [comment]
@choeller your plunk is .. kind of massive... Could you please:
* update it to alpha.45
* strip it down to the absolute minimum (most notably - do we need all the 3rd party deps to reproduce the problem?)

It is _really_ hard to see what is going on with all the code right now.

**Comment by choeller** [comment]
@pkozlowski-opensource oops sorry: I just reused some plnkr I had lying around. So I just strip it down to just show the problem:

http://plnkr.co/edit/fpAfetTUKeYlfDcr7cf9?p=preview

**Comment by wesleycho** [comment]
To make it a little more obvious [here](http://plnkr.co/edit/1y0SBPmttDlufET3qhaT?p=preview)

- Add three inputs
- Type "test" in the first input
- Click outside of any element

If one has the console open, one can see that the `i` is `0`, but the DOM node for `$event.target` is the one with `id` equal to `1`. This implies that the change event was fired from the input in the middle position...which is incorrect - it turns out it always does this for inputs with index 1 greater than the input one entered text in.

**Comment by choeller** [comment]
So I think the problem is, that - by updating the string at position "i" - I "steal" the identity of the current ng-for element, that is used for iteration. 

My original attempt was to "simulate" two-way databinding for plain string-lists. Is there another way to achieve this? Behaviour is still pretty confusing.

**Comment by wesleycho** [comment]
I have a suspicion what is happening is that input at index i gets updated -> change detection reuses nodes but shuffles the node one position to the right -> update bindings.

This would make the bindings correct, but the DOM node incorrect as currently observed. This would also imply that the algorithm for shuffling the DOM elements is incorrect. The culprit would either be in the NgFor directive or DefaultIterableDiffer.

The reason I suspect that this is happening is that I wrote a test for the current behavior I am observing, and it still passes, so I believe the bindings will remain correct, but the DOM nodes themselves are the problem.

**Comment by wesleycho** [comment]
Did a little digging, with a console.log I was able to find that DefaultIterableDiffer's `check` function is the culprit. It is returning incorrect diffs - this shouldn't be too bad to fix

**Comment by rkirov** [comment]
This is not an issue with change detection. The issue that we reuse DOM when moving ng-for children around. The <input> box is stateful and since noone binds into its value, the old value is shown.

["", ""] -> two empty input boxes
["foo", ""] -> input with value "foo", input with value ""

change detection kicks in and tells ng-for [remove at index 1, insert at index 0], which correspondingly tells the renderer to pop the first input and insert a new copy at the end.
However, for optimization we reuse the DOM nodes that were removed and then reinserted and just repopulate all the bindings. In general this is very efficient and a good idea, however, here we have a stateful <input> that doesn't get cleaned up during the removal and insertion.

@tbosch how can they turn off view pooling to get around this issue?

**Comment by tbosch** [comment]
Bind `APP_VIEW_POOL_CAPACITY` from `angular2/src/core/linker/view_pool` to
the value 0.

Note: The ViewPool will probably go away soon.

**Comment by alxhub** [comment]
This is https://github.com/angular/angular/issues/4478 :)

**Comment by pkozlowski-opensource** [comment]
Guess it is solved now since we longer reuse nodes, see #4478

**Comment by rajeev14ranjan** [comment]
using trackBy function of *ngFor fixed that issue for me
