### ISSUE TITLE
Problems with Signal of Map/Map Iterator 

### ISSUE THREAD

**Issue by Nikovic** [angular/angular#51938]
### Which @angular/* package(s) are the source of the bug?

core

### Is this a regression?

No

### Description

I'm trialing Signals in an application I'm building, and I came across the following:
In a component, I have a signal of a Map, `map = signal(new Map<string, number>())`. I somehow fill the map (in the reproduction, with `mutate` in the component constructor).

When I iterate over it in the template using `*ngFor="let id of map().keys()"`, I get NG0100: ExpressionChangedAfterItHasBeenCheckedError. That alone is unexpected to me, I'm not doing any of the things that the documentation says may cause that error.

In trying to get rid of that error, I created `keys = computed(() => map().keys())`
Iterating over _that_ with `*ngFor="let id of keys()"` gives... nothing. The Iterator is always "empty". This seems like a clear bug to me.

I found I could circumvent both problems with `keys2 = computed(() => [...map().keys())]` and `*ngFor="let id of keys2()`. I assume however that this comes with a performance penalty. In the actual application I'm building, performance will likely be an issue, so I'd prefer not to have to rely on that workaround.

Best regards,
Niki Herl

### Please provide a link to a minimal reproduction of the bug

https://stackblitz.com/edit/stackblitz-starters-bt1rkd?file=src%2Fapp%2Fapp.component.html,src%2Fapp%2Fapp.component.ts

### Please provide the exception or error you saw

```true
NG0100: ExpressionChangedAfterItHasBeenCheckedError

or the map iterator being empty ("Map Iterator {  }")
```

### Please provide the environment you discovered this bug in (run `ng version`)

```true
Angular CLI: 16.2.3
Node: 18.17.1
Package Manager: npm 10.0.0
OS: win32 x64

Angular: 16.2.6
... animations, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1602.3
@angular-devkit/build-angular   16.2.3
@angular-devkit/core            16.2.3
@angular-devkit/schematics      16.2.3
@angular/cli                    16.2.3
@schematics/angular             16.2.3
rxjs                            7.8.1
typescript                      5.1.6
zone.js                         0.13.3
```

**Comment by garrettld** [comment]
I believe this is working as intended. In the first case, the `ExpressionChangedAfterItHasBeenCheckedError` error is correct -- you're creating a new iterator with each call to `map().keys()`.

In the second case you're reusing the same iterator, but unlike arrays, low-level iterators like the `IterableIterator` returned from `Map#keys()` can only be iterated once, by definition. The reason you see an empty list is because the NgFor directive initially renders the list items correctly, then on the second change detection pass it removes them again, because the iterator is now "done" because it's already been iterated. This isn't just a dev mode problem, it would happen in production if the component was ever change detected without recreating the iterator.

**Comment by alxhub** [comment]
Agreed, this is working as intended.

> I assume however that this comes with a performance penalty.

It shouldn't have a performance impact. `computed` signals are memoized, so the computation will only run and the array will only be copied if the `map` signal changes.
