### ISSUE TITLE
Add window DI Token for use with Universal/SSR

### ISSUE THREAD

**Issue by MickL** [angular/angular#52182]
### Description

Angular provides a [DOCUMENT](https://angular.io/api/common/DOCUMENT) DI token that returns either the browsers `document` or an instance of `domino` for use on the server side.

Therefor it is not possible to use `window.getComputedStyle()` or react to `window.resize` event.

### Proposed solution

Angular should also provide a `WINDOW` DI token returning either `window` or the domino window instance.

### Workaround
We can create our own DI token that makes use of the `DOCUMENT` DI token created by Angular:

```
import {inject, InjectionToken} from '@angular/core';
import {DOCUMENT} from '@angular/common';

export const WINDOW = new InjectionToken<Window>('Global window object', {
  factory: () => {
    const document = inject(DOCUMENT);
    return document.defaultView!;
  }
});
```

**Comment by pkozlowski-opensource** [comment]
I believe that you can get a window object from a document? https://stackoverflow.com/questions/1338224/how-do-i-get-the-window-object-from-the-document-object 

Having said this I don't think you want to run `window.getComputedStyle()` on the server - sounds like logic that should be wrapped in the `afterRender` hook?

**Comment by MickL** [comment]
You dont want to use `document` on the server side as well, still there is domino providing both `window` and `document`, and Angular added `DOCUMENT` DI token. 

Here is a use case where none of the functions are actually used but domino is required to not have any compiler errors:
 
```
export class MyService {
     escKey$ = fromEvent<KeyboardEvent>(this.document, 'keyup')
     windowResize$ = fromEvent<Event>(this.window, 'resize');

    constructor(@Inject(WINDOW) private window: Window, @Inject(DOCUMENT) private document: Document) {}
}
```

**Comment by JeanMeche** [comment]
The workaround for this is the use `HostListener`. 
`@HostListener('window:resize', ['$event'])` works fine with SSR/Prerendering.

**Comment by MickL** [comment]
Thanks for your solutions guys but this issue is not about solving specific usecases like window resize, it was just meant as an example of what would trigger a compiler error even tho window is not used.

**Comment by alan-agius4** [comment]
Thanks for this feature request.

In general, using Window is not advisable when using SSR. When you really need to do it, it’s recommended that you do in the `afterNextRender` and `afterRender` hooks.

While currently Window is available in SSR when using Domino, this is not guaranteed in the future. 

In additional since this token is not used by the framework and creating this token is trivial I feel that we should not add this as part of the framework as this would also incur an unneeded increase in the API surface, which also incurs maintenance and documentation costs.

**Comment by MickL** [comment]
It is not about "using" `window` when using SSR, it is about any occurance of `window` in the code or for example `getComputedStyle()` results in errors while SSR even tho it is not used.

To fix this with occasions of `document` Angular provides an injection token, and I would ask to also add a `window` injection token and please reopen this feature request. Otherwise, for consistency, the document injection token should be removed.

**Comment by alan-agius4** [comment]
The DOCUMENT token was not created as a solution to get around errors. It’s a token that can be used to provide an arbitrary document value which is needed for SSR. Meaning that `inject(DOCUMENT)` is not guaranteed to be equal to `document`.

I suspect that the errors you are getting are `windows is not defined` this is because while the code is not used, it’s still part of the parsed because it’s in the execution path. Using the above mentioned hooks should solve the problem without the needed of an additional DI token.

**Comment by alan-agius4** [comment]
If that does solve the issue, please open an issue with a minimal reproduction.
