### ISSUE TITLE
Router - SecurityError: Failed to execute 'pushState'

### ISSUE THREAD

**Issue by jvbianchi** [angular/angular#5218]
Hello,

When using PathLocationStrategy I get the error:

```
EXCEPTION: SecurityError: Failed to execute 'pushState' on 'History': A history state object with URL 'http://about-us/' cannot be created in a document with origin 'http://localhost:3000'.
```

When I use HashLocationStrategy it works fine. 

I'm working with angular 2.0.0-alpha.45

Thanks

**Comment by ericmartinezr** [comment]
@jvbianchi it sounds like you are missing something. The URL that is trying to create [it should be relative to your path](http://stackoverflow.com/questions/20079704/javascript-history-pushstate-not-working). Did you specify `<base href="..." />` tag? Or at least `APP_BASE_HREF`? It looks like it needs it, showing us your code would be super useful :)

**Comment by jvbianchi** [comment]
After take a look in my code again, I saw that I didn't specify the base href like you said, sorry.
Thanks.

**Comment by luongvancuong** [comment]
Uncaught SecurityError: Failed to execute 'pushState' on 'History': A history state object with URL 'file:///E:/design' cannot be created in a document with origin 'null' and URL 'file:///E:/important/html_website_gtg/html/animation.html'

who can help me? Please. Thanks so much.

**Comment by zoechi** [comment]
@luongvancuong use an HTTP server instead of direct file access

**Comment by damnko** [comment]
I am having the same issue while trying to pack an app with Electron. It occurs both with `{ useHash: true }` and `{ useHash: false }`. Using an HTTP server solves the problem but I would prefer to avoid this solution as I would need to ship that too with Electron.

@zoechi do you know if there's any other solution? Any hint of what's the root cause of the problem? Is the angular `router` causing it? Testing Electron with other apps with no navigation gives me no problem so I was wondering why it's happening on mine.

@luongvancuong did you manage to solve it without an HTTP server?

Thanks!
