### ISSUE TITLE
Add selector (part of angular signals)

### ISSUE THREAD

**Issue by birkskyum** [angular/angular#52193]
### Description

i basically need this:

https://github.com/solidjs/solid/blob/4968fe26a03b03ff71699ec7567e3a15039dc72f/packages/solid/src/reactive/signal.ts#L778-L843

### Proposed solution

see link

### Alternatives considered

see link

**Comment by alxhub** [comment]
Hi @birkskyum,

This feature request is very minimal and doesn't include any detail. Can you clarify what it is you're trying to do and what limitations or restrictions you're encountering? Angular signals have a different design than SolidJS signals and often will be applied differently to solve the same problem.

**Comment by birkskyum** [comment]
Let's leave the batch for a second and focus on the **_selector_**.

If you have a list of items, and it should be possible to select one, which is quite common, what I do is this:

```ts
export class AppComponent {
  selectedItemId = signal<number | undefined>(undefined);

  select(id: number) {
    this.selectedItemId.set(id);
  }

}
```
```html
<ul >
  <li *ngFor="let item of items; trackBy: itemById" [class.active]="item.id === selectedItemId()"  (click)="select(item.id)">{{item.label}} </li>
</ul>
```

If I could have a _**selector**_ then I could do this:

```ts
export class AppComponent {
  selectedItemId = signal<number | undefined>(undefined);

  select(id: number) {
    this.selectedItemId.set(id);
  }

  isSelected = selector(selectedItemId);

}
```
```html
<ul >
  <li *ngFor="let item of items; trackBy: itemById"  [class.active]="isSelected(item.id)"  (click)="select(item.id)">{{item.label}} </li>
</ul>
```

And as explained in the solid comment, that operation would be O(2) instead of O(n)

**Comment by garrettld** [comment]
To explain why this is useful, the problem with a template like this:

```html
@for (item of items; track: item.id) {
  <li [class.active]="item.id === selectedId()">...</li>
}
```

is that every embedded view (every `<li>`) will be change-detected whenever the `selectedId` signal is updated, which could potentially be expensive for very long lists.

If rendering a huge list of expensive-to-change-detect items is unavoidable, one way to solve for this is to make an "isSelected" signal for each item in the list, and only update the signals that change from `true` to `false` or vice-versa. So for example if the selected id changes from 5 to 7 you might do this:

```typescript
const idSelectedSignals = new Map<number, Signal<boolean>>(...);

onSelectedIdChange(oldId: number, newId: number) {
  idSelectedSignals.get(oldId).set(false);
  idSelectedSignals.get(newId).set(true);
}
```

There's overhead involved in creating all those signals, but if it meant less re-rendering it might be a worthwhile trade-off depending on the use case.

This is effectively what `createSelector` does, by building the `Map` for you under the hood and exposing a function that takes in an id, finds the relevant signal in the `Map`, and returns its boolean value, all while avoiding a logical dependency between the template and the source signal.

I've thrown together a simplified example of how this might work in Angular here: https://stackblitz.com/edit/ng-create-selector-rmro8g?file=src%2Fmain.ts

You could also create a directive that does this for each item individually, which would make it easier to avoid the stale reference / memory leak issue that `createSelector` has.

All that said, I'm not sure how useful an API like `createSelector` is at the moment. In a zoneless future where embedded views are change detected individually based only on their signals (see "Granularity of local change detection" here: https://github.com/angular/angular/discussions/49684), I think this type of optimization could work, but in the example StackBlitz above, all the list items get checked every time anyway because of Angular's top-down change detection.

**Comment by EmmanuelRoux** [comment]
Maybe you can do what you want with `computed` ?
https://angular.io/api/core/computed

**Comment by birkskyum** [comment]
As @garrettld mention, this proposal makes more sense signals rather than zone.js can drive the reactivity, so it's a bit too early.
