### ISSUE TITLE
Error: Can't resolve '~ng-zorro-antd/ng-zorro-antd.css'

### ISSUE THREAD

**Issue by ninggaoqian** [angular/angular#52308]
### Which @angular/* package(s) are the source of the bug?

compiler-cli

### Is this a regression?

Yes

### Description

Why did the path of the less file change after the update? Our local file-relative path has not been modified
![image](https://github.com/angular/angular/assets/129500618/81c56aa3-21d9-4540-aea5-5596a9793549)

**Comment by JoostK** [comment]
Thanks for reporting this issue. However, you didn't provide sufficient information for us to understand and reproduce the problem. Please check out [our submission guidelines](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-submitting-an-issue) to understand why we can't act on issues that are lacking important information.

If the problem still exists in your application, please [open a new issue](https://github.com/angular/angular/issues/new/choose) and follow the instructions in the issue template.

---

The `~` import syntax is non-standard and support for it has been phased out in the CLI. `ng-zorro-antd` v16 provides export maps for its CSS files, which should allow you to import using `ng-zorro-antd/ng-zorro-antd.css` (it maps to the `ng-zorro-antd.min.css` file, so indeed it could be that your original import is broken because they changed the file)
