### ISSUE TITLE
control flow: weird behavior of ng-template migration

### ISSUE THREAD

**Issue by zip-fa** [angular/angular#52518]
### Which @angular/* package(s) are the source of the bug?

core

### Is this a regression?

No

### Description

Hi. Migration of *ngFor block inside ng-template works weird.

Initial template:

```
<ng-container *ngIf="cond; else testTpl">
bla bla
</ng-container>

<ng-template #testTpl>
  <div class="test"
      *ngFor="let item of items"
    ></div>
</ng-template>
```

Result:

```
@if (cond) {
bla bla
} @else {
<div class="test"
  *ngFor="let item of items" <--- why this was not migrated
  ></div>
}

<ng-template #testTpl>
  @for (item of items; track item) { <--- while this was
  <div class="test"></div>
}
</ng-template>
```

### Please provide the environment you discovered this bug in (run `ng version`)

Angular CLI: 17.0.0-rc.3
Node: 18.18.1
Package Manager: npm 9.8.1
OS: win32 x64

```
Angular: 17.0.0-rc.2
... animations, cdk, common, compiler, compiler-cli, core, forms
... localize, material, platform-browser
... platform-browser-dynamic, platform-server, router
... service-worker

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1700.0-rc.3
@angular-devkit/build-angular   17.0.0-rc.3
@angular-devkit/core            17.0.0-rc.3
@angular-devkit/schematics      17.0.0-rc.3
@angular/cli                    17.0.0-rc.3
@angular/ssr                    17.0.0-rc.3
@schematics/angular             17.0.0-rc.3
rxjs                            7.8.1
typescript                      5.2.2
zone.js                         0.14.0
```

**Comment by zip-fa** [comment]
New observation: *ngIf gets ignored too.

**Comment by jessicajaniuk** [comment]
This is expected, but not ideal. The migration processes top to bottom. So it sees the ngIf / else before the ngtemplate and processes that first, moving the content up from the ngTemplate. Since migrations are processed based on the _original_ template contents, it doesn't know that the moved content from the ngTemplate has anything in it. It just knows the template contents later on has control flow to address. I think the proper solution is to migrate ngTemplates first before the rest of the file, so when this happens, the templates are already addressed. I'll take a look.
