### ISSUE TITLE
control flow: Property '$index' does not exist on type 'TestComponent'.

### ISSUE THREAD

**Issue by zip-fa** [angular/angular#52528]
### Which @angular/* package(s) are the source of the bug?

core

### Is this a regression?

No

### Description

Hi.

Working code:

```
@for (transaction of transactions; track $index) {
  123
}
```

Invalid code:

```
@for (transaction of transactions; track $index; let index = $index) {
  123
}
```

Is it expected?

### Please provide the environment you discovered this bug in (run `ng version`)

```true
Angular: 17.0.0-rc.2
... animations, cdk, common, compiler, compiler-cli, core, forms
... localize, material, platform-browser
... platform-browser-dynamic, platform-server, router
... service-worker

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1700.0-rc.3
@angular-devkit/build-angular   17.0.0-rc.3
@angular-devkit/core            17.0.0-rc.3
@angular-devkit/schematics      17.0.0-rc.3
@angular/cli                    17.0.0-rc.3
@angular/ssr                    17.0.0-rc.3
@schematics/angular             17.0.0-rc.3
rxjs                            7.8.1
typescript                      5.2.2
zone.js                         0.14.0
```

**Comment by e-oz** [comment]
Community opinion was asked by @JeanMeche , so here is my opinion: it would be more intuitive and less fragile if this syntax created aliases.

**Comment by pkozlowski-opensource** [comment]
I will re-open it so we can discuss more

**Comment by zip-fa** [comment]
This looks really counter-intuitive. Maybe allow track by $index with aliases?

**Comment by pkozlowski-opensource** [comment]
Coming back to this issue in preparation for graduating control flow from developer preview. 

To sum up what is going here, it seems to confuse people that the implicit `$index` variable can't be used in the tracking expression when aliased. That is, given:

```
@for (transaction of transactions; track $index; let index = $index) {
  ...
}
```

the ` let index = $index` aliasing "steals" the implicit `$index` variable. The reasoning for the current logic is that alias makes it ... an alias - if one maps a variable to a different name than the mapped name should be used.

Having said this I can see how this could be confusing, especially if one operates with the JavaScript's `let` model where both the new and and assigned variables are "visible". At the same time we couldn't go with the `let` mental model since it would mean that `$index` is _always_ available and "shadows" a component's property named `$index`. This is a real problem since, all of the sudden the `$index` would not be accessible from a template.

What we _could_ do, though, is to expose `$index` in the tracking expression (and not in the template) even if aliased. So far we didn't do so since this is a special case that would need explaining, documentation etc.

Hope that this comments explain our reasoning so far and actually demonstrates a straightforward mental model here. Still, I'm going to keep this issue open to see how many people bump into it. If this is a common source of confusion we can consider adding `$index` as always present in the tracking expression.
