### ISSUE TITLE
Switch ShadowDOM strategy to emulated by default

### ISSUE THREAD

**Issue by naomiblack** [angular/angular#526]
We must also update benchmarks for this change, and check the ToDo App example.
@vsavkin  has a doc that outlines options.

**Comment by vicb** [comment]
@rkirov I think this one depends on #499 where the strategy is made global.

Currently there are 2 strategies:
- native,
- emulated.

Something that we could do is to bind the strategy to native when shadow dom is supported or emulated when not. What do you think ?

**Comment by rkirov** [comment]
Yes, I should get #499 in ASAP. Given our shim is not build to be 100% compatible, switching between native and emulated per browser is something we want to avoid.

An app developer might only test on Chrome and when they ship their app might be completely broken on Firefox because of limitations of the emulated mode.

**Comment by rkirov** [comment]
I have a prototype of the change. Good news is emulated shadow dom works for all examples and benchmarks. Bad news is that it is 4x slower. 

tree benchmark
native:
 js.ng2.tree |              |     38.61±5%  (script time)
emulated:
 js.ng2.tree |              |    139.80±7%  (script time)

**Comment by vsavkin** [comment]
@rkirov I'll look into it today

**Comment by jelbourn** [comment]
I just tried out binding ShadowDomStrategy to EmulatedShadowDomStrategy in the root bindings in application.js and then loading some simple components. The components work with the native strategy, but emulated make them crash the browser (Chrome and Firefox).

**Comment by mhevery** [comment]
@rkirov could you please do status update

**Comment by vicb** [comment]
The issue reported by @jelbourn should not be a pb any more as the strategy as been moved to the application level injector (from root bindings)

**Comment by vicb** [comment]
@rkirov not sure if it's worth doing it now as the strategies API (ctor) will change (see #772) and we will have to change again once the PR has landed.

**Comment by rkirov** [comment]
@vicb yes, I will handle it after #786 is merged. It is also blocked on adding the DOM read-write queue (I am getting close being done on it), because without it emulated strategy is a bit slower than native on the tree benchmark.

Finally, there are a few features missing/bugs with emulatedShadowDomStrategy that would need fixing before we do the final switch. see: 
https://github.com/angular/angular/blob/master/modules/angular2/test/core/compiler/shadow_dom/shadow_dom_emulation_integration_spec.js#L169
