### ISSUE TITLE
Lack of version selector on angular.dev

### ISSUE THREAD

**Issue by akshay3001** [angular/angular#52618]
### Describe the problem that you experienced

The current state of the [angular.dev](https://angular.dev/overview) documentation page presents a significant usability issue for users. It lacks a version selector feature, making it impossible for visitors to switch between different Angular versions while accessing the documentation.

### Enter the URL of the topic with the problem

https://angular.dev/overview

### Describe what you were looking for in the documentation

Looking for different angular version in new docs.

**Comment by JeanMeche** [comment]
Angular.dev will document the upcoming versions from v17 onwards. 

For previous versions, please refer to Angular.io.

**Comment by twerske** [comment]
Thanks for your feedback!

Angular.dev will be the documentation for Angular for v17 and forward. Since at release, the docs only represent v17, there are no other versions to select from so we disabled the version picker until we launch as stable with v18. See: https://github.com/angular/angular/blob/9cac4eea5b692dd55e43ebcf8237d78777b0deb0/adev/src/app/core/layout/navigation/navigation.component.html#L128

Angular.io's version picker will remain the source for documentation for Angular v1-v17. Angular.dev will start at v17+ (once there are multiple versions and these docs are no longer beta.)

Thanks again!
