### ISSUE TITLE
docs-infra: emoji's missing from code export

### ISSUE THREAD

**Issue by alyssamichelle** [angular/angular#52637]
# Communicating with `@Output` tutorial
## [Reveal Code Answer & Export](https://angular-dev-site.web.app/tutorials/learn-angular/output)

![280073377-468abaef-2ffc-4501-9000-91b8fbac8f1e](https://github.com/angular/blossom/assets/1058831/c008d5c3-5d36-4132-b63d-94861e51d070)

 If you export the code from this tutorial and open it, you'll see in both ts files, the emoji's are missing. In `child.component.ts` and `app.component.ts` the 🐢 emoji was replaced with `="` 

![image](https://github.com/angular/blossom/assets/1058831/e364543b-3c54-4098-9ade-6708846d3114)

**Comment by Captainnik53** [comment]
@twerske  I would like to work on this issue. Please assign this to me

**Comment by twerske** [comment]
> @twerske I would like to work on this issue. Please assign this to me

Done!

**Comment by hansireit** [comment]
@josephperrott I checked this out, the emojis are corrupt because the `binary` flag is set to `true` when creating the zip file. I tested it with the flag removed, works fine.

[zip.utils.ts:](https://github.com/hansireit/dev-infra/blob/f2dbdeb62601fa259e10be581758fc147eb75094/docs/utils/zip.utils.ts#L18)
```ts
for (const file of files) {
  zip.file(file.path, file.content, {binary: true }); // <- Remove the binary flag
}
```

I also noticed that the encoding when reading files is set to 'utf-8' in [filesystem.utils.ts](https://github.com/hansireit/dev-infra/blob/f2dbdeb62601fa259e10be581758fc147eb75094/docs/utils/filesystem.utils.ts#L41), which could lead to problems when reading binary images.
```ts
const content = await fs.readFile(fullPath, 'utf-8');
files.push({content, path: fullPath});
```

**Comment by dolanmiu** [comment]
This issue seems to be resolved, can close?

# Steps

1. Go to https://angular-dev-site.web.app/tutorials/learn-angular/9-output
2. Click `Reveal Answer` to fill in the 🐢 emojis etc.
3. Click on export
    ![image](https://github.com/user-attachments/assets/8113cb3e-5cdb-49d7-a43f-d65f0f464274)
5. Looks fine with 🐢 emojis in in `child.component.ts` and `app.component.ts`
    ![image](https://github.com/user-attachments/assets/eba74efd-1dbf-44e8-8a8b-a5e596bca7b7)
