### ISSUE TITLE
Standalone pipe providers

### ISSUE THREAD

**Issue by marcindz88** [angular/angular#52789]
### Which @angular/* package(s) are relevant/related to the feature request?

core

### Description

Standalone pipes cannot have providers.
Defined decorator type is: 
```
export interface Pipe {
  name: string;
  pure?: boolean;
  standalone?: boolean;
}
```

While migrating pipe modules to standalone I saw that the provider for some date processing service was missing, and it is not possible to define it on a standalone pipe.

### Proposed solution

add providers option to Pipe decorator type

### Alternatives considered

I can stick with the NgModule based solution.

**Comment by alxhub** [comment]
This is working as intended - a design goal of standalone was to uncouple template dependencies on components/directives/pipes from application DI configuration (which was also provided through NgModules).

You have three potential solutions here:

1. (recommended) Make your service `@Injectable({providedIn: 'root'})` so that you can inject it without needing to provide it anywhere explicitly.

2. Document that users of your pipe need to configure/provide the service somewhere.

3. Continue using NgModules.
