### ISSUE TITLE
Angular transformer is adding extra lines to Dart files -- the line number in stack traces do not match our source code

### ISSUE THREAD

**Issue by jbdeboer** [angular/angular#5281]
The Angular transformer is Component templates in the Dart files as a string of HTML.

This is causing the line numbers reported in stack traces to be incorrect.

Steps to reproduce:

pub serve test <test target>

In Dartium, open the component's Dart file, notice that the file numbers are shifted.

============

Suggested fix: include the HTML and CSS as strings at the end of the file.  Reference those strings from the @Component, taking care not to alter the line count.

**Comment by kegluneq** [comment]
This is due to a test-only feature implemented in [inliner_for_test/transformer.dart](https://github.com/angular/angular/blob/master/modules_dart/transform/lib/src/transform/inliner_for_test/transformer.dart).

@jbdeboer your suggested fix is a good idea, but I don't have time to make the change atm.
