### ISSUE TITLE
@nguniversal 17

### ISSUE THREAD

**Issue by PieterjanDeClippel** [angular/angular#52950]
### Which @angular/* package(s) are the source of the bug?

Don't known / other

### Is this a regression?

No

### Description

`@nguniversal/express-engine` is not yet available for 17.

I posted it here because the [angular/universal](https://github.com/angular/universal) repo doesn't seem to contain any bugs/pull-requests

**Comment by JoostK** [comment]
Please see the [README of angular/universal](https://github.com/angular/universal/blob/main/README.md).

**Comment by anisabboud** [comment]
Angular Universal was replaced with @angular/ssr https://angular.dev/guide/ssr
`ng update` should perform the migrations to the new package for you automatically.

You can also create a new project:
`ng new a17 --ssr` (with standalone components), or:
`ng new a17m --ssr --no-standalone` (with NgModule)
So that you can compare the files in your projects with the files in a fresh Angular 17 project, and perform any additional adjustments.
