### ISSUE TITLE
Ng-for behaves incorrect when class 'ng-animate' is added

### ISSUE THREAD

**Issue by mathcals** [angular/angular#5296]
When using the class 'ng-animate' on an ng-for-element and updating the corresponding list, some of the updated items are removed.

The problem is illustrated by this example: http://plnkr.co/edit/5qkFpT
In the example the list ['a','b','c'] is displayed using ng-for. After 2 seconds the list is replaced by the list ["e","f","g","h","i"]. The expected behavior would be that this list is now displayed using ng-for.
However, only the items "h" and "i" are shown. Without the class 'ng-animate', the problem doesn't occur.

**Comment by mhevery** [comment]
can you better explain what is the expected behavior vs what actually happens. It is not clear to me what I should be seeing instead.

**Comment by mathcals** [comment]
I updated the description to include expected behavior and actual result.

**Comment by gionkunz** [comment]
I was running into this too. Here's an other example: http://plnkr.co/edit/nI7gHCPsqYFU7NgKkPA0?p=preview.

**Comment by Hendrixer** [comment]
right, so the expected behavior is for `ngFor` to act as normal. But instead what happens when you add the `ng-animate` class to an element that also has the `*ngFor` directive, it renders incorrectly. When an item is added to the collection, all other items in the collection are removed from the DOM.

**Comment by vicb** [comment]
outdated
