### ISSUE TITLE
Support `@loading` block on `@for` block

### ISSUE THREAD

**Issue by xXNickznXx** [angular/angular#53185]
### Which @angular/* package(s) are relevant/related to the feature request?

core

### Description

It would be a great addition if the `@for` block would support the `@loading` block with the same functionality as on the `@defer` block.
This would be useful for cases where data is loaded asynchronously.

### Proposed solution

Very simple example:
```js
@for (entry of entries | async; track entry.id) {
  <p>{{ entry.title }}</p>
} @loading (minimum 200ms) {
  <p>Loading</p>
} @empty {
  <p>No entries</p>
}
```

### Alternatives considered

I tried using the `@defer` block, but that didn't work as intended:
```js
@defer {
  @for (entry of entries | async; track entry.id) {
    <p>{{ entry.title }}</p>
  } @empty {
    <p>No entries</p>
  }
} @placeholder (minimum 200ms) {
  <p>Loading</p>
}
```

**Comment by pkozlowski-opensource** [comment]
@xXNickznXx I can see how this could be useful in this particular scenario. But in general this feature request is problematic since it makes an assumption that `null` indicates the "loading" state. This can get confusing pretty quickly as a reference to a collection could become `null` without any "loading" operation.

We think that the loading indicator logic is best handled outside of the control flow so we will skip this suggestion. Thnx for sharing your ideas, though!
