### ISSUE TITLE
tour of heroes - navigation

### ISSUE THREAD

**Issue by Rumpelnation** [angular/angular#53206]
### Describe the problem that you experienced

section 5 navigation: `ng generate module app-routing --flat --module=app`  it leads to: 

```
Specified module 'app' does not exist.
Looked in the following directories:
    /src/app/app-routing
    /src/app/app
    /src/app
    /src
```

when i generate app-routing.moduls.ts without --module=app

in https://angular.io/tutorial/tour-of-heroes/toh-pt5#:~:text=src/app/app%2Drouting.module.ts%20(updated) the routing  doesn't work (http://localhost:4200/heroes)
`{ path: 'heroes', component: HeroesComponent }` should move to app.routes.ts (i think) when it works by me

[EDIT] 

ok, here are more issues: 
if i genereate: `ng generate component dashboard`
intellij says: DashboardComponent is not declared in any Angular module 
i know standalone is the new default, but i'm a bit confused, i'm new to angular 17, can i ignore it or it's better to make the tutorial as no-standalone-app?

### Enter the URL of the topic with the problem

https://angular.io/tutorial/tour-of-heroes/toh-pt5

**Comment by Tweniee** [comment]
@alan-agius4 can i work on this?

**Comment by alan-agius4** [comment]
@Tweniee, sure please feel free to open a PR.

**Comment by Tweniee** [comment]
> section 5 navigation: `ng generate module app-routing --flat --module=app` it leads to:
> 
> ```
> Specified module 'app' does not exist.
> Looked in the following directories:
>     /src/app/app-routing
>     /src/app/app
>     /src/app
>     /src
> ```


@alan-agius4 As you're aware, in version 17, the default is standalone, which is why there's no `app.modules.ts`. I've consequently removed these lines from the documentation. I'd like to confirm if this implementation is correct.
![image](https://github.com/angular/angular/assets/93429474/a0321a9c-478b-4c6b-877d-ca4150057adc)
![image](https://github.com/angular/angular/assets/93429474/cf853267-d06c-488f-a887-188363d78d53)

Do we really need to remove it? Standalone is the default with v17, but on the other hand, v16 works perfectly fine with this `ng generate module app-routing --flat --module=app`.

Suggestion: Can't we add a Note specifying that it is for v16 only, and you do not need to use the --module=app flag in v17 and above?

**Comment by alan-agius4** [comment]
These tutorials are strictly for standalone, for version 16 users can also use https://v16.angular.io/.

The fix itself, is more complex than just removing those 2 files, as it looks like https://angular.io/tutorial/tour-of-heroes/toh-pt5 has not been migrated to standalone. Therefore the entire doc needs to be updated.

**Comment by Tweniee** [comment]
> These tutorials are strictly for standalone, for version 16 users can also use https://v16.angular.io/.
> 
> The fix itself, is more complex than just removing those 2 files, as it looks like https://angular.io/tutorial/tour-of-heroes/toh-pt5 has not been migrated to standalone. Therefore the entire doc needs to be updated.
> 
> Let me know, if you are still inteerested in taking this on.

definitely, i will

**Comment by JeanMeche** [comment]
Hi, we're looking at deprecating angular.io in favor of https://angular.dev.  
Feel free to drop any suggestions for the new doc site, thank you.
