### ISSUE TITLE
docs: cli-reference for `ng new` incorrectly shows --standalone as defaulting to false

### ISSUE THREAD

**Issue by mvdluit** [angular/angular#53241]
### Describe the problem that you experienced

The cli reference (adev) for the the `new` command lists the `--standalone` flag,  mentioning it defaults to `false`. In v17 standalone is the default behavior. Note that on https://angular.io/cli/new the `--standalone` flag correctly says that it defaults to `true`.

The `--no-standalone` flag is missing (also on angular.io) and IMO could be listed in place of the `--standalone` flag since that is default behavior now.

### Enter the URL of the topic with the problem

https://angular.dev/cli/new

### Describe what you want to experience that would fix the problem

- Update the `--standalone` flag to correctly show it's the default behavior (e.g default true). (or maybe replace it with the `--no-standalone` as it's now the default behavior.)

- Add `--no-standalone` flag to inform how to create a project based on `NgModules`. (both on .dev and .io).

**Comment by alan-agius4** [comment]
For context: `--no` is available to all boolean options. As described in https://angular.io/cli#boolean-options

**Comment by mvdluit** [comment]
@alan-agius4 Thank you for pointing that out. This explanation about `--no` being available on boolean values does not seem to be present on [angular.dev](https://angular.dev/cli). In fact, the entire overview page on adev is missing the explanation on the basics of the CLI. Should I make a separate issue for this?

Some context as to why I would like to see an explicit mention of `--no-standalone`: Since standalone became the default, people asking about missing modules is a daily recurring event on the [Angular Discord](https://discord.gg/angular). A lot of people starting out with Angular are still following `NgModule` based courses/guides, and it's hard for them to discover how to generate a project with modules. Having at least the CLI reference explicitly mention the possibility of generating a `NgModule` project would therefore be helpful in my opinion.

I (and other people involved with the discord) fully support standalone being the defalt and are trying to get people to try it out, but it will probably take some time for courses/guides to catch up. (When Angular turned on TS strict by default, it also took nearly 2 major versions for the questions about it to become less 😬)

**Comment by JeanMeche** [comment]
I don't think we should recommend people to go with `--no-standalone` and not mentionning it would be the right direction to do so. 

With the time we'll see more and more content that will drop the ngModules.

**Comment by mvdluit** [comment]
@JeanMeche I agree that a specific mention of `--no-standalone` is not necessary (we solved it with a `/standalone` bot command on discord so we don't have to spend too much time on these questions). 

A lot of the information from the overview page for the CLI is still missing though: https://angular.io/cli
ADEV only shows commands and some basic explanation could be useful.

**Comment by CarlosLiberJesus** [comment]
Just looking for answers too... just booted the WSL to start work, did a normal ng g c ... and the standalone: true started to appear as the warning message! Even in older projects that I wasn't toutch, addind in ~\.angular.config.json did not work...

The best I could so far, was in project forder angular.json:
"@schematics/angular:component": {
          "style": "scss",
          "standalone": false
        },
        
that managed to create well the components, but the warning message does not go away and my autism doesnt like it

**Comment by mvdluit** [comment]
@CarlosLiberJesus What is the exact warning message and what version of Angular are you using (both the project version and the version of the global installed cli)?

It would also be better to ask questions like these in the [Angular Community Discord](https://discord.gg/angular), as issues aren't really intended to provide support.

**Comment by CarlosLiberJesus** [comment]
I'll go and do that! Thank you, I'll respect the time and place...
but I'm getting old, keeping up with evolution in all stacks, 10 sites to be on xD :funny not-funny: 
Friday was fine, for Monday boot xD

I think I understand the theory, that Angular17 is pushing module deprecation, but we can discontinue at once team old-habbits, and lots of working libraries. Everything still transpiling, I was just wondering the warning, and if I could turn it off for a while... Dont want to one epic become 2 epics xD I think I can also revert back to 16

But since you asked:
bewhy@BEWHY-HUB:~/libertarios/frontend$ ng version
Workspace extension with invalid name (standalone) found.
...
Angular CLI: 17.3.8
Node: 18.19.0
Package Manager: npm 10.2.5
OS: linux x64

Angular: 17.3.11
... animations, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1703.8
@angular-devkit/build-angular   17.3.8
@angular-devkit/core            17.3.8
@angular-devkit/schematics      17.3.8
@angular/cli                    17.3.8
@schematics/angular             17.3.8
rxjs                            7.8.1
typescript                      5.2.2
webpack                         5.92.1
zone.js                         0.14.7

**Comment by alan-agius4** [comment]
Closing as the docs are not correct.

**Comment by mvdluit** [comment]
@CarlosLiberJesus If you're referring to this warning: `Workspace extension with invalid name (standalone) found.`, this has nothing to do with standalone components. Your project is probably upgraded a number of times from older Angular versions and `angular.json` still contains a field `defaultProject` that was deprecated a while ago. If you remove that field, the warning will disappear.
