### ISSUE TITLE
Form control's pristine attribute is not updated properly.

### ISSUE THREAD

**Issue by tijoforyou** [angular/angular#5328]
I have a component that uses forms API. I use the `pristine` attribute of the control to check if data has been changed or not. But looks like it returns me *dirty* only after a second change.

Example: I have a textbox where just blank spaces are not allowed. Right now, if I type just one space, then during validation, the control says that it is pristine. After any other change, the control becomes dirty, as far as the validators are concerned.

**Comment by tijoforyou** [comment]
@vsavkin

**Comment by brian428** [comment]
Seeing this as well. For some reason, the Control's pristine field doesn't become false until the second change.

**Comment by kara** [comment]
I'm having a hard time replicating this.  Is this still a problem in rc.1?   An example plunker would help.

**Comment by robertdp** [comment]
This is still a problem, and I've just run into it on my app.

I'm attempting to use `ChangeDetectionStrategy.OnPush` in all my components, and the easiest workaround I've found so far is to embed `{{form.valueChanges.mapTo(null) | async}}` somewhere in the template to force the view update after the input event, instead of before.

**Comment by robertdp** [comment]
Removing `ChangeDetectionStrategy.OnPush` makes the problem go away, and reinstating it brings the problem back. And each view update `form.dirty`, `form.pristine`, etc. are always set to what their values should have been _before_ the latest keypress.

**Comment by robertdp** [comment]
Going even deeper down the rabbit hole: heavy use of console logging in seemingly relevant places has led me to the actual order of events.

For each event for the inputs in my app, the following happens:

`view.markPathToRootAsCheckOnce()` from https://github.com/angular/angular/blob/bb8976608db93b9ff90a71187608a4390cbd7a07/modules/%40angular/compiler/src/view_compiler/event_binder.ts#L78
`control.updateValue()` from https://github.com/angular/angular/blob/0a872ffd387f59b18128dc31d7fa874766bc22af/modules/%40angular/common/src/forms/model.ts#L294
`valueAccessor.onChange()` from https://github.com/angular/angular/blob/bb8976608db93b9ff90a71187608a4390cbd7a07/modules/%40angular/common/src/forms/directives/shared.ts#L38

This sequence repeats once more, running a total of 2 times (identical values both times, is this doubling-up a bug?), followed by a single value being emitted from `form.valueChanges`.

There are no calls to `view.markPathToRootAsCheckOnce()` or `view.markAsCheckOnce()` after the form model/control group has finished updating. Triggering a call to `view.markPathToRootAsCheckOnce()` manually by moving focus or any other method immediately updates the view with the correct form data.

**Comment by kara** [comment]
Can you please provide an example plunker?

**Comment by kara** [comment]
Okay, I think I see what you mean.  Are you checking the pristine property in a subscription to valueChanges?    If you print the property to the screen with {{ }}, the pristine property updates right away (which is what I checked before), but if you check as part of valueChanges, it won't be correct right away because the order of the calls.  I think we should be able to just invert them.  Looking into it.

**Comment by nuvoPoint** [comment]
This is still a problem in Angular 7

**Comment by Nimmi92** [comment]
I face the same problem with Angular 7.  Anyone has got a solution?
