### ISSUE TITLE
Add support to return different Http Status Code e.g. 404, 301 Redirect and Custom Headers e.g. NoIndex header in renderApplication

### ISSUE THREAD

**Issue by naveedahmed1** [angular/angular#53314]
### Which @angular/* package(s) are relevant/related to the feature request?

platform-server

### Description

Returning different HTTP status codes from the `renderApplication` call is not supported at this moment, it would be really useful to add support for:

1. Returning custom status codes e.g. 404 status code for not found, 503 e.g. in case an API call returns 503 status code.
2. Returning 301/302 redirect status code, with option to set redirect url as well. 
3. Return custom headers e.g. NoIndex headers to let search engines know that this page should not be indexed.

### Proposed solution

What if the `renderApplication` could return a response object with properties:

1. Body
2. Status Code
3. Redirect URL (Optional)
4. Headers

### Use case:

I tried using Angular App on Cloudflare Pages/Worker. It works for most of the parts, but when it comes to setting the http status code or custom headers it doesnt seem to work.

I generated a test app using the Cloudflare CLI. The CLI generates an Angular 17 app with below server.ts file:

```
import { renderApplication } from "@angular/platform-server";
import bootstrap from "./src/main.server";

interface Env {
    ASSETS: { fetch: typeof fetch };
}

// We attach the Cloudflare `fetch()` handler to the global scope
// so that we can export it when we process the Angular output.
// See tools/bundle.mjs
async function workerFetchHandler(request: Request, env: Env) {
    const url = new URL(request.url);
    console.log("render SSR", url.href);

    // Get the root `index.html` content.
    const indexUrl = new URL("/", url);
    const indexResponse = await env.ASSETS.fetch(new Request(indexUrl));
    const document = await indexResponse.text();

    const content = await renderApplication(bootstrap, {
        document,
        url: url.pathname,
    });

    // console.log("rendered SSR", content);
    return new Response(content, indexResponse);
}

export default {
    fetch: (request: Request, env: Env) =>
        (globalThis as any)["__zone_symbol__Promise"].resolve(
            workerFetchHandler(request, env)
        ),
};
```

So apparently there's no way to pass the status code or custom headers to the worker `workerFetchHandler` since `renderApplication` just retuns a string.

**Comment by alan-agius4** [comment]
Although there's room for enhancing the process of defining status codes, such as for error pages and redirects, currently setting of status codes and headers is possible through Dependency Injection (DI).

tokens.ts
```ts
const RESPONSE_INIT_OPTIONS = new InjectionToken<ResponseInit>('RESPONSE_INIT_OPTIONS');
```

server.ts
```ts
const responseInitOptions: ResponseInit = {};
const content = await renderApplication(bootstrap, {
  document,
  url: url.pathname,
  platformProviders: [
    { provide: RESPONSE_INIT_OPTIONS, useValue: responseInitOptions },
  ],
});

return new Response(content, responseInitOptions);
```

app.component.ts
```ts

@Component({
  ...
})
export class AppComponent {
  private readonly responseInitOptions = inject(RESPONSE_INIT_OPTIONS, {
    optional: true,
  });

  constructor() {
    if (!this.responseInitOptions) {
      return;
    }

    this.responseInitOptions.status = 404;
  }
}

```

**Comment by naveedahmed1** [comment]
Thank you so much @alan-agius4 it works perfectly for 404, can you please confirm its thread safe? I mean is there any possibility that two concurrent requests read the same status code?

Secondly, can you please add example of 301 redirect and adding custom headers as well?

I tried setting headers:

`this.responseInitOptions.headers.append('X-Robots-Tag', 'noindex');`

> But its throwing error property append doesnt exist on `Headersinit`.

Thank you!

**Comment by alan-agius4** [comment]
> Thank you so much @alan-agius4 it works perfectly for 404, can you please confirm its thread safe? I mean is there any possibility that two concurrent requests read the same status code?

Yes.

> But its throwing error property append doesnt exist on Headersinit.

Are you initialising the `responseInitOptions.headers`?

```ts
const responseInitOptions: ResponseInit = {
  headers: new Headers()
};
```

**Comment by naveedahmed1** [comment]
Thank you so much!

**Comment by naveedahmed1** [comment]
`ResponseInit` doesnt contain `Location` property. So for 301 redirects I tried setting `statusText` to the redirect url in my component and then in server.ts I tried:

```
if (responseInitOptions.status == 301) {
  return new Response().redirect(responseInitOptions.statusText, 301);
}
```

This didn't work and and was throwing error:
`TS2551: Property 'redirect' does not exist on type 'Response'. Did you mean 'redirected'?`

Even though both MDN and CloudFlare docs suggest `Response().redirect()`:

https://developer.mozilla.org/en-US/docs/Web/API/Response/redirect_static
https://developers.cloudflare.com/workers/examples/redirect/


So as a workaround, I set the `Location` header in my component:

```
    this.responseInitOptions.status = 301;
    let newHeaders = {
      'Location': redirectURL
    };

    this.responseInitOptions.headers = newHeaders;
```

And in server.ts:

`  return new Response(content, responseInitOptions);`

Which seems to be working fine.

**Comment by alan-agius4** [comment]
@naveedahmed1, as the docs suggest the `redirect` is a static method thus it should be accessed like

```ts
return Response.redirect(responseInitOptions.statusText, 301);
```

**Comment by Gold3nFox** [comment]
> ```ts
> const responseInitOptions: ResponseInit = {};
> const content = await renderApplication(bootstrap, {
>   document,
>   url: url.pathname,
>   platformProviders: [
>     { provide: RESPONSE_INIT_OPTIONS, useValue: responseInitOptions },
>   ],
> });
> 
> return new Response(content, responseInitOptions);
> ```

@alan-agius4  Where exactly should we add this part ? I know I need to add it to server.ts but now its something likes this:

`
import { APP_BASE_HREF } from '@angular/common';
import { CommonEngine } from '@angular/ssr';
import express from 'express';
import { fileURLToPath } from 'node:url';
import { dirname, join, resolve } from 'node:path';
import AppServerModule from './src/main.server';
const routes = [
  "/",
  "/register*",
  "/login*",
  "/i/*",
  "/e/*",
  "/register/freelancer*",
  "/search*",
  "/jobs/*",
  "/mobile-search*",
  "/services*",
  "/edu*",
  "/freelancer*",
  "/hire*",
  "/freelance-jobs*",
  "/plans*",
  "/how-it-works*",
  "/categories*",
  "/FAQ*",
  "/review*",
  "/projects*",
  "/profile*",
  "/post-job*",
  "/forgot-password*",
  "/set-password*",
  "/terms*",
  "/contact*",
  "/panel*",
  "/about*",
  "/content*",
  "/landing/nowruz99",
  "/local-jobs*",
  "/graphic-design*",
  "/worksample*",
  "/web-design*",
  "/projectslanding*",
  "/ecommerce-website*",
  "/programming*",
  "/translation*",
  "/referral*",
  "/subscription*",
  "/skills*",
  "/photography*",
  "/application*",
  "/introduction*",
  "/quizzes*",
  "/quiz*",
  "/404*",
  "/500*"
];

// The Express app is exported so that it can be used by serverless Functions.
export function app(): express.Express {
  
  const server = express();
  const serverDistFolder = dirname(fileURLToPath(import.meta.url));
  const browserDistFolder = resolve(serverDistFolder, '../browser');
  const indexHtml = join(serverDistFolder, 'index.server.html');

  const commonEngine = new CommonEngine();

  server.set('view engine', 'html');
  server.set('views', browserDistFolder);

  // Example Express Rest API endpoints
  // server.get('/api/**', (req, res) => { });
  // Serve static files from /browser
  server.get('*.*', express.static(browserDistFolder, {
    maxAge: '1y'
  }));

  // All regular routes use the Angular engine
  server.get(routes, (req, res, next) => {
    const { protocol, originalUrl, baseUrl, headers } = req;

    try {
      commonEngine
        .render({
          bootstrap: AppServerModule,
          documentFilePath: indexHtml,
          url: `${protocol}://${headers.host}${originalUrl}`,
          publicPath: browserDistFolder,
          providers: [{ provide: APP_BASE_HREF, useValue: baseUrl }],
        })
        .then((html) => {
          res.send(html);
        })
    } catch (err) {
      next(err);
    }
  });

  return server;
}

function run(): void {
  const port = process.env['PORT'] || 4000;

  // Start up the Node server
  const server = app();
  server.listen(port, () => {
    console.log(`Node Express server listening on http://localhost:${port}`);
  });
}

run();

`
Where exactly should I add this part?
`
const responseInitOptions: ResponseInit = {};
const content = await renderApplication(bootstrap, {
  document,
  url: url.pathname,
  platformProviders: [
    { provide: RESPONSE_INIT_OPTIONS, useValue: responseInitOptions },
  ],
});

return new Response(content, responseInitOptions);
`

**Comment by naveedahmed1** [comment]
@Gold3nFox the code sample @alan-agius4 shared in above comment is for Cloudflare Workers. Are you hosting your Angular App on Cloudflare Page/Workers?

**Comment by Gold3nFox** [comment]
@naveedahmed1 No my app is deployed on physical servers in our data center, I'm trying to set 404 status for dynamic routes (which by default enter server.ts and I understand they are 404 after API response) and there are some redirects that we handle in angular (which again I understand they should be redirected after API response).

In older Angular version I used Angular Universal this line existed `res.status(404).render("index", { req });` but it doesn't exist in Angular new SSR.

The only solution I found was this and I don't know how to use it on normal Angular app.

**Comment by Gold3nFox** [comment]
@naveedahmed1 Thanks for your response.

The response on Stackoverflow is what works on older version. You can see that they used `import { RESPONSE } from '@nguniversal/express-engine/tokens';` which is from angular universal and I used to work with that. now that it is removed and I use built-in SSR and nguniversal has stopped at version 16 I can't do that.

those two issues are unsolved and there's no solution for me in them.

**Comment by naveedahmed1** [comment]
@Gold3nFox Yes you are right, I had an idea that's why I mentioned other github issues (which of course are still unresolved).

But as per the https://github.com/angular/angular-cli/issues/26323 it seems that the issue where injection tokens are null occurs only on development i.e. `ng serve`, in production it should work fine, right?

**Comment by Gold3nFox** [comment]
@naveedahmed1  Thanks, Yeah finally after 4 days I could get it to work on production.
This answer really helped me [https://stackoverflow.com/a/77459798/10087419](https://stackoverflow.com/a/77459798/10087419) and one thing that might help other people that have the same problem is you cant use the injected response and request normally because of their type but if you use `(this.response as any)` the status and redirect functions will work fine.

**Comment by naveedahmed1** [comment]
I'm glad you are finally able to solve the issue :)

**Comment by alan-agius4** [comment]
Closing as this has been tackled with the new `@angular/ssr` API that is currently in developer preview in version 19.
