### ISSUE TITLE
Smart quote breaks code block on Sharing Logic page

### ISSUE THREAD

**Issue by mflorida** [angular/angular#53486]
### Describe the problem that you experienced

In the angular.dev docs, a smart quote character is present in the "How to use a service" code block on the "Sharing Logic" page. This breaks syntax highlighting in the code block as well as allowing a reader to copy broken code that will generate a syntax error if used.

The offending character is highlighted in the screenshot below:

<img width="726" alt="image" src="https://github.com/angular/angular/assets/4173034/37dbb6fd-1368-4378-85d8-93f3e88c645c">

### Enter the URL of the topic with the problem

https://angular.dev/essentials/sharing-logic

**Comment by madangopal16072000** [comment]
hello everyone, I am new to this project. I would like to contribute can you please assign this to me.

**Comment by Valentinnin** [comment]
Hello. Im not sure how because its me First contribute. and i cant fork here like i should wwritten on the https://github.com/firstcontributions/first-contributions/blob/main/README.md 
Thats why i send the made code into here. maybe someone can get me the link where i can see how to contribute here? Kind Regards!

**Comment by JeanMeche** [comment]
@Valentinnin Thx for your help, we already have an open PR for it though. (#53488)

**Comment by alxhub** [comment]
#53488 has been merged.
