### ISSUE TITLE
ng-model doesn't change the value of input tag (case type is hidden)

### ISSUE THREAD

**Issue by m-amr** [angular/angular#536]
i have an input tag type='hidden' ng-model='name' 
Inside the controller i changed the value of name variable 
$scope.name='test-1';
i found that the value attribute in this input tag is not updated
but it works when i used ng-value
input tag type='hidden' ng-value='name' 

Should ng-model directive update the value attribute of the input tag (in case type is hidden ) ?

**Comment by pkozlowski-opensource** [comment]
Wrong repo, I guess you wanted to open the issue in https://github.com/angular/angular.js

But spare yourself the effort, `ngModel` is not supposed to work on `hidden` elements. The reason is that `ngModel` is there to handle 2-way data binding but you can't have 2-way data binding on hidden elements (users can't interact with them).

Just use interpolation on the `value` attribute, use `ngValue` or ngAttrs
