### ISSUE TITLE
UpperCasePipe needs further details

### ISSUE THREAD

**Issue by aosaf-ershad-chowdhury** [angular/angular#53708]
### Describe the problem that you experienced

In the section of formatting the hero name with an Uppercase Pipe, the code actually gives an error because `CommonModule` is actually not imported when the project is initially generated.

### Enter the URL of the topic with the problem

https://angular.io/tutorial/tour-of-heroes/toh-pt1

### Describe what you were looking for in the documentation

The tour of heroes tutorial

### Describe the actions that led you to experience the problem

I was going through the tutorial step by step

### Describe what you want to experience that would fix the problem

Users should be informed about the requirement of importing `CommonModule`

### Add a screenshot if that helps illustrate the problem

![image](https://github.com/angular/angular/assets/64976142/5670a290-8f89-4d18-8143-9f9acef82723)

**Comment by bougwal** [comment]
If you are in a non-standalone mode, using `@NgModules` first scaffolding will not import `CommonModule` for you and other battery-included features / module (because by default the assumption is that you do not need them). Only **BrowserModule** is added to your AppComponent class imports array by default like so: 

`
@NgModule({
  //other stuff
  imports: [
    BrowserModule
  ]
})
export class AppModule { }
`

Hence, this is applicable to other built-in features. when you are in a non-standalone mode, you should add `CommonModule` manually to the imports array. But if you are in a standalone mode you can import the pipe itself directly instead of the whole module, like so: 


`
@NgModule({
  //other stuff
  imports: [
    UpperCasePipe
  ],
 standalone: true
})
export class AppModule { }
`

The schematics will add it by default to your feature modules as well. And in some cases you can drop it from the default generation if your standalone component does not depend on it (does not need any utilities from it).

For full list of exportable utilities [you can read here on the docs you referenced about the CommonModule](https://angular.io/api/common/CommonModule) Or [you can read here on the new revamped Angular docs](https://angular.dev/guide/ngmodules/faq#should-i-import-browsermodule-or-commonmodule)


For standalone mode [you can read here on the same doc you are using](https://angular.io/guide/standalone-components)

**Comment by bougwal** [comment]
If you are in a non-standalone mode, using @NgModules first scaffolding will not import CommonModule for you and other battery-included features / module (because by default the assumption is that you do not need them). Only BrowserModule is added to your AppComponent class imports array by default like so:

@NgModule({some-stuff ... ,  imports: [ BrowserModule ] }) export class AppModule { }

Hence, this is applicable to other built-in features. when you are in a non-standalone mode, you should add CommonModule manually to the imports array. But if you are in a standalone mode you can import the pipe itself directly instead of the whole module, like so:

@NgModule({some-stuff... ,  imports: [ UpperCasePipe ], standalone: true }) export class AppModule { }

The schematics will add it by default to your feature modules as well. And in some cases you can drop it from the default generation if your standalone component does not depend on it (does not need any utilities from it).

For full list of exportable utilities [you can read here on the docs you referenced about the CommonModule](https://angular.io/api/common/CommonModule) Or [you can read here on the new revamped Angular docs](https://angular.dev/guide/ngmodules/faq#should-i-import-browsermodule-or-commonmodule)

For standalone mode [you can read here on the same doc you are using](https://angular.io/guide/standalone-components)

**Comment by bougwal** [comment]
If you are in a non-standalone mode, using `@NgModule `first scaffolding will not import `CommonModule` for you and other battery-included features / module (because by default the assumption is that you do not need them). Only `BrowserModule` is added to your `AppComponent` class imports array by default like so:

`@NgModule({some-stuff ... , imports: [ BrowserModule ] }) export class AppModule { }`

Hence, this is applicable to other built-in features. when you are in a non-standalone mode, you should add `CommonModule` manually to the imports array. But if you are in a standalone mode you can import the pipe itself directly instead of the whole module, like so:

`@NgModule({some-stuff... , imports: [ UpperCasePipe ], standalone: true }) export class AppModule { }`

The schematics will add it by default to your feature modules as well. And in some cases you can drop it from the default generation if your standalone component does not depend on it (does not need any utilities from it).

For full list of exportable utilities [you can read here on the docs you referenced about the CommonModule](https://angular.io/api/common/CommonModule) Or [you can read here on the new revamped Angular docs](https://angular.dev/guide/ngmodules/faq#should-i-import-browsermodule-or-commonmodule)

For standalone mode [you can read here on the same doc you are using](https://angular.io/guide/standalone-components)
