### ISSUE TITLE
Possibility to migrate only one component at a time using the control-flow migration

### ISSUE THREAD

**Issue by eneajaho** [angular/angular#53851]
### Which @angular/* package(s) are relevant/related to the feature request?

core

### Description

I want to be able to create a VSCode task that runs the migration on the file directly. But the `path` option accepts a folder path and not a single file path. 

```json
    {
      "type": "shell",
      "label": "Angular: Migrate component to new control flow",
      "command": "npx ng g @angular/core:control-flow --path ${file} --format --interactive",
    },
```

### Proposed solution

Allow the path to be a file path and migrate only that file only. 

### Alternatives considered

None.

**Comment by jessicajaniuk** [comment]
We actually already have [a test in the migration test suite](https://github.com/angular/angular/blob/main/packages/core/schematics/test/control_flow_migration_spec.ts#L106) that specifically runs against one ts file. So this should already be supported. It may be an `npx` limitation rather than the control flow migration itself. We've seen other cases where `npx` was the source of the issue specifically with path identification. Can you attempt running it with just the angular CLI in that case and see what happens?

**Comment by eneajaho** [comment]
Thanks @jessicajaniuk 

Found out the issue was passing the full path instead of relative path. 

The correct solution was to use `relativeFile`

```json
  {
      "type": "shell",
      "label": "Angular: Migrate component to new control flow",
      "command": "npx ng g @angular/core:control-flow --path ${relativeFile} --format --interactive",
    },
 ```

Leaving this here incase someone wants to use it. 

Closing the issue!

**Comment by cskiwi** [comment]
getting some errors here, any suggestions @eneajaho ? 

```
 NX   Debug Failure. Expected C:/<ommited>/libs/frontend/components/src/something/something/something.component.html === C:\<ommited>\libs\frontend\components\src\something\something\something.component.html. 
```

This is on windows 10, using bash shell (same result with command prompt, powershell, ...)
