### ISSUE TITLE
Review ComponentFixture and DebugElement API

### ISSUE THREAD

**Issue by juliemr** [angular/angular#5385]
The current method is pretty wordy and annoying to work with, for instance:

```
fixture.debugElement.componentInstance
```

Seems wordier than it should be. This issue is to review the API.

cc @rkirov

**Comment by juliemr** [comment]
cc @wardbell I know you have thoughts here as well!

**Comment by juliemr** [comment]
Note: up until https://github.com/angular/angular/commit/787d1f955f4f52be2f47d96111ce0299581a3900, `ComponentInstance` extended `DebugElement`. I'm not sure why it was removed, but it's possible that putting it back could solve some of the complaints.

**Comment by juliemr** [comment]
See discussion at https://github.com/angular/angular/commit/787d1f955f4f52be2f47d96111ce0299581a3900#commitcomment-14516403 for why `ComponentInstance` was changed to not inherit from `DebugElement`.

**Comment by wardbell** [comment]
I agree that this is wordy and unexpected (until you think twice and remember that we attach the component to the element so I should be able to find it there).

It isn't obvious that it should extend `DebugElement` either so I'm cool with that long ago change. 

Why can't it be available directly from``fixture`? That's the TCB right?  Or would that be just way too much common sense.

p.s.: I don't care that I'd then be able to get it from two places: the TCB and the `DebugElement`. That happens other places too.

**Comment by juliemr** [comment]
So a simple proposal:

```js
fixture.componentInstance == fixture.debugElement.componentInstance;
fixture.nativeElement == fixture.debugElement.nativeElement;
```

**Comment by IgorMinar** [comment]
@juliemr +1, it actually used to be this way before but because of several refactorings we ended up with the current state. the inheritance thing we had before doesn't make sense, but exposing these two properties directly via fixture is fine.

**Comment by IgorMinar** [comment]
btw the impact on g3 will be 0 because the plan is not to remove these apis from `debugElement`, but only reexport them via `fixture`, right?

**Comment by juliemr** [comment]
@IgorMinar correct, no impact to g3!

**Comment by rkirov** [comment]
+1 for the simple proposal. I am starting to wonder if debugElement is useful as public API at all?

**Comment by juliemr** [comment]
I think debugElement is only useful for authors of components which are meant to be used on more than one platform. Those authors would care about the `ElementRef` and associated queries. But I think most authors just want the `nativeElement` if they're only working on one platform (e.g. web).

That's enough interest for me, I'll go ahead and make a PR.

**Comment by juliemr** [comment]
I wonder if we should provide a different platform-specific debug element tree - a lot of confusion seems to stem from the fact that `DebugElement` follows the `ElementRef` tree of bound elements, not the DOM tree that users expect. So elements without directives or bound attributes, and even simple text bindings, don't show up in `DebugElement#query()` or `DebugElement#children`.

The advantage over just using the native element apis (e.g. `querySelector`) would be awareness of angular attributes when applicable, so we could do `superDebugElement.query(By.directive('myDir'))` or `superDebugElement.query(By.binding('foo'))`. This would also be useful for e2e tests.

**Comment by IgorMinar** [comment]
@tbosch <= what do you think?

Encouraging use of native element apis seems better to me, but I understand that the current api can be misleading.

**Comment by wardbell** [comment]
I'm with you Julie, on the need. What is missing from `NativeElement` that makes your proposal attractive?

**Comment by cexbrayat** [comment]
I refactored my unit tests (around 300) to rely on native elements APIs instead of `query(By.css())` and `componentViewChildren` and that make them much more easy to read.
The only use case I really see for `query` is when we want to grab a reference to the component instance of a child to test some property of this child, or emit an event.

With `fixture` exposing the `componentInstance` and the `nativeElement`, that looks good!

**Comment by juliemr** [comment]
Here's the use case I see for having a `By.binding` or `By.directive` query that's useful to users. If you have a complex template, maybe like:
```html
<div>Container
  <div><span>Food to buy</span>
    <ol>
      <li>Milk</li>
      <li>Butter</li>
      <li>{{otherFoodItem}}</li>
    </ol>
  </div>
</div>
```

Then in the test
```js
fixture.debugElement.query(By.binding('otherFoodItem'));
```
seems cleaner than
```js
fixture.nativeElement.querySelector('ol li:nth-child(2)');
```

But you could say that's just a sign that your template needs useful classes or IDs.

**Comment by juliemr** [comment]
It would also be nice for debugging (e.g. via chrome devtools) to be able to inspect `<span>MysteryString</span>` and be able to figure out where that binding came from. At the moment, `ng.probe` can't do that because there's no associated `DebugElement`.

**Comment by wardbell** [comment]
I LOVE being able to hunt for something by binding rather than spelunking with querySelector. But then I'm typically testing my component/template interaction which is usually through the component api via a binding. When looking for these kinds of things, I'd think that my test was easier to read because it concentrates on the purpose of my test. 

The querySelector is my last resort, most likely for testing a directive that has some effect on the layout or appearance that is hard to see through the component api ... something that was done by the directive to the element.  Then I need to go native.

Evidently @cexbrayat and I are testing for different things ... and that is just fine.

**Comment by cexbrayat** [comment]
By.binding would indeed be useful. (but I think that's not possible right now because simple bindings like that are not in componentViewChildren, hence the issue #4573 I opened).

**Comment by gionkunz** [comment]
Maybe this is a bit off topic, but since the title suggest this is a review of `DebugElement` I'm posting here. How about a property `directiveInstances` on ` DebugElement`? Currently in RC1 I need to do something like `fixture.debugElement.query(By.directive(ABC)).injector.get(ABC)` in order to get a child directive instance. Would be much nicer if there's a `HashMap` on `DebugElement.directiveInstances`. I could then just do: `fixture.debugElement.query(By.directive(ABC)).directiveInstances.get(ABC)`. I know the length of the code is almost the same, however, it will provide some extra semantics and context.

**Comment by aciccarello** [comment]
I'm just looking into the `ComponentFixture` api docs for the first time and was confused about the similar properties. Relationships between the properties of the class are not clear when looking at the property descriptions. As I dug into the types and the implementation it became more apparent, but improving the property descriptions would be easier for developers than having to dig into every property type.

## Current property descriptions:

> - `componentRef`: The ComponentRef for the component.
> - `componentInstance`: The instance of the root component class.
> - `elementRef`: The ElementRef for the element at the root of the component.
> - `nativeElement`: The native element at the root of the component.
> - `debugElement`: The DebugElement associated with the root element of this component.

If you already understand a `ComponentRef`, `ElementRef` and `DebugElement` types then this may be clear, but until someone learns those interfaces it is unclear which property to use.

In some ways adding the `componentInstance` and `nativeElement` is easier b/c those are interfaces most developers already know, but it also left me wondering why the other properties were there. Just changing the descriptions to something like 
> `componentInstance`: The instance of the root component class. Also available on the ComponentRef.

Would help explain the relationship between properties.


_Disclaimer: This is my first impression before writing tests._

**Comment by vicb** [comment]
@juliemr can this be closed ?
