### ISSUE TITLE
Angular Getting started docs needs to be updated for standalone components

### ISSUE THREAD

**Issue by RobertRacklBMW** [angular/angular#53895]
### Describe the problem that you experienced

The [Angular Getting Started guide](https://angular.io/start) needs to be updated to reflect the updates for [Standalone Components](https://angular.io/guide/standalone-components).

The Getting Started Guide mentions command like "ng create component cart". This nowadays by default creates a standalone component. That needs to be included in a different way. Not in ngModules as described in the guide.

The Guide sais "The generator automatically added the ProductAlertsComponent to the AppModule to make it available to other components in the application.". But this is not true anymore. The "ng create component <component-name>" command by default creates a standalone component and does not add anything to the `app.module.ts`   The documentation in the guide needs to be updated.

### Enter the URL of the topic with the problem

https://angular.io/start

### Describe what you were looking for in the documentation

The documentation needs to be updated to reflect Standalone Components as created by ng create component by default.

### Describe the actions that led you to experience the problem

Working through the Getting Started Guide. In the provided StackBlitz environment.

### Describe what you want to experience that would fix the problem

The code as shown in the guide should work :-)

### If this problem caused an exception or error, please paste it here

```true
This is the error message that the angular compiler shows, when you try to include the component as currently described in the Getting Started guide:


Component ProductAlertsComponent is standalone, and cannot be declared in an NgModule. Did you mean to import it instead?
```
```


### If the problem is browser-specific, please specify the device, OS, browser, and version

```true
any browser or OS
```

### Provide any additional information here in as much as detail as you can

```true
It would be very nice if you find the time to update the Getting Started Guide. This would help a lot of Angular Beginners.  THX!
```

**Comment by danieljancar** [comment]
Hey @RobertRacklBMW,
Thanks for the issue, will work on it. ❤️

**Comment by danieljancar** [comment]
Since StackBlitz is working on a new feature of being able to open Github repositories straight through the website/editor, we could rethink the **Getting Started** workflow.

![image](https://github.com/angular/angular/assets/112062588/72b5a085-4818-406f-b8ed-a12cd5842953)

What might be an option for the walkthrough, considering the current *beta feature* in StackBlitz, is creating a new `getting-started` repository and optionally a `product-app` repository, which is the finished version of the `getting-started` repo.
This would provide an easier and more up-to-date workflow for Angular beginners, where they can easily use the sample `getting-started` repository or even make a fork of it, if they want to work on it further and have more control. 

The new StackBlitz editor is a web-version of VSC and would give more comfortability and a probably known UI to get started with Angular.

Here you can see a personal Angular project in the new StackBlitz editor, opened directly from my Github repository:

![image](https://github.com/angular/angular/assets/112062588/8c31193d-275e-4fd9-bbb0-8a13c53cf4b8)

What do you think?
