### ISSUE TITLE
Custom validator

### ISSUE THREAD

**Issue by behzadeshan** [angular/angular#5389]
Please look at this code:
http://plnkr.co/edit/0Jazt5t523uh40R9F7Pk?p=preview

in input tag `type` attribute does not work. How should I write two validation for one element?  I have another question, in this code there is a password input that has no validator in code, it's validator has been set in markup, but still I have to define its control in ControlGroup, is there a way to mix local template validators with code-side validators and remove those definitions from code? because this has made my code very long, defining control for each input in a form with 30 input. something like this: `<input ng-control="password" #password="formGroup" required>`

**Comment by rosendi** [comment]
here we are http://plnkr.co/edit/zXz7UFY7XBZK6clOg8s9?p=preview

**Comment by behzadeshan** [comment]
@rosendi PERFECT, thank you. Aren't HTML5 type attributes validated by Angular 2 by default and I should manage them myself? I have another question I added another validation rule to EmailValidator, how can I show different messages for these two rules? is there a way to write something like these: `{{email.isUnique}}` and `{{email.isValid}}`?
http://plnkr.co/edit/Ak2tJ0GFS4XWjCFwa1sy?p=preview
I also prefer not to write another validator class for solving this issue if it possible.

**Comment by rosendi** [comment]
Currently Angular's built-in validators are `required`, `minlength` and `maxlength`. 

1. Yep, you have to implement your custom validator for email inputs and any other regex-based inputs. It seems logical to me since email validation is a little bit tricky in each case. Just a small remark, I agree with this article http://davidcel.is/posts/stop-validating-email-addresses-with-regex/.

2. On the one hand while checking email format is a synchronous process, an uniqueness validator is asynchronous and it should be implemented in a different way (https://github.com/angular/angular/pull/5020): 

```
@Directive({
  selector: '[uniq-login-validator]',
  providers: [provide(NG_ASYNC_VALIDATORS, {useExisting: UniqLoginValidator, multi: true})]
})
class UniqLoginValidator implements Validator {
  validate(c) { return someFunctionReturningPromiseOrObservable(); }
}
```
On the other hand I think it's much better to avoid any monolithic classes. The testing of such classes is much more complicated and code looks overloaded as well.

P.S. You can compose validators https://github.com/angular/angular/blob/master/modules/angular2/src/common/forms/validators.ts#L81

**Comment by behzadeshan** [comment]
@rosendi  thank you for your clear and helpful answer.
