### ISSUE TITLE
Selectors after :host are not properly shimmed

### ISSUE THREAD

**Issue by rkj** [angular/angular#5390]
my css on a component:

```
:host .foo .bar {
  color: red;
}

.foo .bar {
  color: green;
}
```

it gets translated into:

```
[_nghost-shh-2] .foo .bar {
  color: red;
}

.foo[_ngcontent-shh-2] .bar[_ngcontent-shh-2] {
  color: green;
}
```

it is a great missing feature if this is indeed working as intended - but on the first look it seems like a bug to not shim add the shimmed attribute onto classes after :host.

**Comment by tbosch** [comment]
Before this, we should introduce the `/deep/` and `>>>` selector, see https://github.com/angular/angular/issues/7562

**Comment by zoechi** [comment]
`/deep/` and `>>>` are deprecated in shadow DOM. Why not implementing CSS variables and mixins like Polymer does?

**Comment by tbosch** [comment]
@zoechi `/deep/` and `>>>` are very simple to emulate and can be done in a static way, i.e. there is no performance penalty. Emulating css variables is quite a bit of work... We might tackle it later, but not now.

**Comment by zoechi** [comment]
@tbosch but they won't be available in encapsulation `Native`. The availability of these combinators lures people to work in ways that are not future proof. It probably also will lead to a lot of confusion whether they should be used or not.

**Comment by Blasz** [comment]
FYI #7562 is now resolved, just making sure this is still on the radar.

**Comment by brianmtreese** [comment]
It would be great if now that `/deep/` and `>>>` are supported that selectors after`:host` and `:host-context` could be properly shimmed. This actually becomes a significant issue with style bleed when using  `:host` and `:host-context` in conjunction with slotted components and nested components. For example in the following example I've created a parent component with a content slot that contains another component, the styles applied from the parent apply to those below: https://plnkr.co/edit/yS39UjxpPC84NFnZkUzG?p=preview

**Comment by ocombe** [comment]
Omg why but why ? All the styles of my app are a mess now... I have to add /deep/ eveywhere

**Comment by brianmtreese** [comment]
This solution is very much needed because the styles were not properly scoped. Any time you used :host or :host context you were intentionally or unintentionally piercing the "shadow boundary". With this fix you now have the option and flexibility to continue to do so with the use of /deep/ or you can properly leverage scoping using :host/:host-context without affecting the components nested within.

**Comment by ocombe** [comment]
I get it, but it's a huge breaking fix for me :(

**Comment by vicb** [comment]
> Omg why but why ? I have to add /deep/ eveywhere

I you don't need encapsulation just don't use it.

**Comment by kemsky** [comment]
Could you put issues like this under Breaking Changes section next time?

**Comment by vicb** [comment]
This is definitely a fix when you think about the difference in behavior we had wrt the native implementation.

That being said, I agree, we should probably have done a better job communicating this and announcing the fix as a BC would have help.

Your feedback help us improve. Thanks.

**Comment by ocombe** [comment]
By the way @vicb not sure if this is considered a bug or not, but using `/deep/` on a style outside of `:host` makes it becoming global as soon as the component is loaded.
For example, if I have a page with a `/deep/` style on `h3`, once this page has been loaded, all my `h3` throughout my entire app are restyled until I reload my app
Thinking about it, it makes sense because `/deep/` removes the element hoisting, but when you actually use it, it looks like a bug.
In my opinion `/deep/` should only work if there is already a parent selector: `:host /deep/` or `.someclass /deep/`

**Comment by vicb** [comment]
the current shim impl has limitations because we use to shim "live" (as the webcomponent.js where the source originated).

we have 2 options going forward:
- better doc for the "limitations",
- better shimming as it is done as compile time hence "free" in AoT.

Could you create a "CSS shimming issues/limitations" here to start referencing those. Thanks.
