### ISSUE TITLE
https://angular.dev/resources

### ISSUE THREAD

**Issue by amaiques** [angular/angular#53957]
### Describe the problem that you experienced

page not found

### Enter the URL of the topic with the problem

https://angular.dev/resources

**Comment by JeanMeche** [comment]
The issue is on : https://angular.dev/tools/libraries/using-libraries

**Comment by danieljancar** [comment]
Hey @amaiques,
I guess you want to have the same format of resources at https://angular.dev/resources like on https://angular.io/resources. 

@JeanMeche : I don't think we have a similar implementation of the resources on `adev` like we have on `aio`?

I'd take on implementing this, as soon as the `adev` environment can be run locally. 😉

**Comment by bencodezen** [comment]
Thanks for filing the issue @amaiques! I'll bring this request back to the team and will let you all know what the plan is for this page on angular.dev going forward.

**Comment by bencodezen** [comment]
@amaiques As promised, I wanted to provide an update on the Resources page.

After maintaining the Resources page on Angular.io for the past years, the team has determined that these resources are best maintained by the company rather than the team. 

I'd recommend reinvigorating projects like https://github.com/PatrickJS/awesome-angular which can be community led and managed. 

Hope this helps and thanks for being a part of the Angular community!
