### ISSUE TITLE
Not being able to change a signal input from within the component results in more complexity vs the old approach

### ISSUE THREAD

**Issue by TomTomB** [angular/angular#53982]
### Which @angular/* package(s) are relevant/related to the feature request?

core

### Description

Consider creating some kind of accordion element with a `isExpanded` input. It is pretty common to change this input's value internally e.g. when the user clicks on the accordion header. Using the old decorator version this would result in much less code, since the input's value can simply be changed.

```ts
  @Input()
  isExpandedOld = false;

  toggleExpandedOld() {
    this.isExpandedOld = !this.isExpandedOld;
  }
```

Now switching to signal inputs there is the need for an extra `effect` as well as a extra `signal`.

```ts
  isExpanded = input(true);
  isExpandedManual = signal(false);

  toggleExpanded() {
    this.isExpandedManual.set(!this.isExpandedManual());
  }

  constructor() {
    effect(
      () => {
        this.isExpandedManual.set(this.isExpanded());
      },
      { allowSignalWrites: true },
    );
  }
```

### Proposed solution

Keep the old behavior of being able to change the inputs value from within the component. This would also make the migration to signal inputs easier, once they are out of developer preview.

### Alternatives considered

None.

**Comment by Harpush** [comment]
Can we update an input from inside to affect the outside? 🤔
Model inputs as far as I understand replace the input + output (`isExpanded` and `isExpandedChange`) pair for banana in the box two way binding (just sugar syntax).

As far as I understand this issue is about changing the input from inside without affecting the outside. The `isExpanded` is initial state and later he reuses the same input as just an internal variable unrelated to the outside. Am I missing something?

If I am correct that doesn't sound like a good practice.

**Comment by TomTomB** [comment]
This kind of behavior is rather common. A less abstract example can be found in the angular/components repo. The expansion panel has a [toggle](https://github.com/angular/components/blob/29a1e5d8a13e1e81b9aa2e1dd89d54fb063fc191/src/material/expansion/expansion-panel.ts#L206) method, that toggles the [expanded input](https://github.com/angular/components/blob/29a1e5d8a13e1e81b9aa2e1dd89d54fb063fc191/src/cdk/accordion/accordion-item.ts#L63).

**Comment by Harpush** [comment]
First it uses getter setter and does emit change event. 
Second from my experience if you update the input internally it updates the UI but if the outside didn't change the input binding due to change event you are out of sync in state.
The new input way seems to me better. Input is read-only set from outside. If you want to update it from inside emit an event and let the outside update the input (easier with future model).
Temporary state that doesn't affect the outside should live in another variable. Otherwise you can't know what is the internal temp state compared to the outside state passed as input.

**Comment by isgj** [comment]
I don't think `input` should be changed.
One can write a simple helper like
```ts
function merge<T>(source: Signal<T>) {
  const s = signal(source());
  effect(() => {
    s.set(source());
  });
  return s;
}
```

and then use it

```ts
isExpanded = input(true);  // readable, always has the provided value
isExpandedManual = merge(this.isExpanded) // writable, has the last input change or the value by `.set` or `.update`
```

**Comment by TomTomB** [comment]
@Harpush I've chosen this example because it's essentially the same thing. In the end a setter is used to set a private member. There's only some logic inside the setter that could just as well live inside a effect function (I wouldn't recommend that though. It should be pretty obvious, that the angular/components repo was created when the term "signal" wasn't even a thing to begin with).

And to your second point:
I don't think it would result in a good user experience, if the consumer of my accordion component would also need to add state & event bindings to their own component. Just imagine importing a 3rd party accordion component just to notice you need to provide a expanded input and there's also this magic toggleExpanded event you need to listen to. And to expand further on this let's say there's a "FAQ" page, where you will certainly have more than one accordion. This would result in a lot of code that wasn't needed before. 

@isgj Abstracting it away of cause helps, but you are still stuck with 2 signals. This makes the component harder to understand. What value am I supposed to use for this new feature xyz I have to implement? You could maybe change the name from isExpanded to doNotUseIsExpanded and then aliasing it to isExpanded. This way we could rename isExpandedManual to simpy isExpanded. But all of this sounds like a lot of work for a simple problem that just wasn't a problem before. 

It will be interesting to see, if this is getting solved by model inputs. As far as I can remember you could just omit the "banana" / event part from the template binding to ignore the change events.

**Comment by ahmed-a-ibrahim** [comment]
I faced this and, I had to update the writableSignal inside the input transform function, that's the right way?

` _expanded = input(booleanAttribute(false), {
    transform: (value) => {
      const booleanValue = booleanAttribute(value);
      this.expanded.set(booleanValue);
      this.expandedChange.emit(booleanValue);

      return booleanValue;
    },
    alias: 'expanded',
  });`

**Comment by n614cd** [comment]
> First it uses getter setter and does emit change event. Second from my experience if you update the input internally it updates the UI but if the outside didn't change the input binding due to change event you are out of sync in state. The new input way seems to me better. Input is read-only set from outside. If you want to update it from inside emit an event and let the outside update the input (easier with future model). Temporary state that doesn't affect the outside should live in another variable. Otherwise you can't know what is the internal temp state compared to the outside state passed as input.

This round robin seems like the ideal in the academic setting, but adds significant complexity and boiler plate code to many projects. Due to the implied boomerang logic it will likely have a performance impact with a fair amount of round robin processing. In addition to the complexity, it will cause logic problems and errors where the linkage between the internal/external aspects are missed. 

In the existing structure, the inbound Input does not have to have a corresponding Output; if the calling component does not care about the variable state after initialization. The accordion status is a perfect example where the parent component may care about the initial state and not after. 

Having played a little with Signals, I think the overall approach is interesting and can help in many situations. In this case, the problem is less with Signals and more that this is only half the puzzle. As pointed out above by @JoostK  https://github.com/angular/angular/issues/53982#issuecomment-1899938802  Models will solve the accordion issue. 

The only issue I foresee is if Signals for inputs is released before Models. This will cause a lot of issues, I think these two features must go together.

**Comment by Akxe** [comment]
@n614cd Well, it seems they did not, and it just got me to find this issue. I can understand the perspective of both sides, and I think an option should be added to the `input` function in order to enable the internal updates of the input. In case it does not I will use the approach with setter and getter.

```
export class DateDisplayComponent {
	readonly #showAs = signal<'time-ago' | 'date'>('time-ago');
	@Input() set showAs(value: 'time-ago' | 'date') {
		this.#showAs.set(value);
	}
	get showAs() {
		return this.#showAs();
	}

	@HostListener('click') onClick() {
		this.showAs = this.showAs === 'time-ago' ? 'date' : 'time-ago';
	}
	
	// ...
}
```

----- 

The added option could be used by angular analytics to measure how often an input is internally changed too. Maybe it could be an interesting hint for the team.

**Comment by inmativ** [comment]
We can look at the problem more abstractly. The signal syntax allows us to implement combineLatest, but does not allow us to do merge.
Yes, we can apply effect with the allowSignalWrites flag, but [AngUniversity](https://blog.angular-university.io/angular-signals/) this suggests that setting to signal inside effect is a sign of bad imperative architecture. And indeed it is. But the signal syntax is not as rich as rxjs. And it is not enough for a full-fledged declarative architecture.

From here many problems will appear, similar to the one described at the beginning. Mixing signals and rxjs looks monstrous and dirty. Therefore we have to choose. But in components we cannot make a choice in favor of rxjs, since signals now dominate there. However, signals do not allow you to write so declaratively.

Probably, we need to somehow simplify the logic. But I don't understand how. What does a good architecture look like that would allow a large application to minimize the use of allowSignalWrites?

**Comment by Iosif380** [comment]
@TomTomB , This seems to be a very simple solution to your problem

[stackblitz](https://stackblitz.com/edit/stackblitz-starters-ckey7a?description=An%20angular-cli%20project%20based%20on%20@angular/animations,%20@angular/common,%20@angular/compiler,%20@angular/core,%20@angular/forms,%20@angular/platform-browser,%20@angular/platform-browser-dynamic,%20@angular/router,%20core-js,%20rxjs,%20tslib%20and%20zone.js&file=src%2Fmain.ts,src%2Fglobal_styles.css&template=node&title=Angular%20Starter)

**Comment by TomTomB** [comment]
Indeed, with Angular 17.2 this is now possible using model() instead of input(). To achieve the "old" behavior we can simply drop the "banana" part from the binding so e.g. [(isOpen)]="value" should be [isOpen]="value". This also has the added flexibility to explicitly determine, if we care about our "initial value" changing by re-adding the "banana" part. 

With these tools in mind, I think this issue is now resolved.
