### ISSUE TITLE
Unclear usage of effect to retrieve data in async way

### ISSUE THREAD

**Issue by TarsisDragomir** [angular/angular#54047]
### Describe the problem that you experienced

I'm really enthusiastic about the new features in angular 17, but I'm unsure on how to use the new effects. It seems the new way to make an application reactive (without the need for rxjs mostly), but if I look at the official [angular.dev](https://angular.dev) explanation on effect it states "Effects are rarely needed in most application code" which feels a bit strange. Does this mean angular prefers us to stick with rxjs streams for reactivity and fetching data?
On the other hand I find plenty of other examples on blogs/X/... where effect are used to initiate retrieving data and setting other signals their value (since it's an async process writing to signal just works without errors there). Even initiatives like [computedAsync](https://ngxtension.netlify.app/utilities/signals/computed-async/) are based on that pattern. If we work like that, are we ignoring angular best practices? Or is this allowed/the future of reactivity in angular?

### Enter the URL of the topic with the problem

https://angular.dev/guide/signals

### Describe what you were looking for in the documentation

Probably I overlooked, but on angular.dev I find no example at all on how to trigger an http get call to retrieve data and how to store that data (in signals).

### Describe the actions that led you to experience the problem

Upgrading and adapting to angular 17, but became confused by official statements on angular.dev and examples elsewhere (because of the lack of examples on angular.dev itself).

### Describe what you want to experience that would fix the problem

A clear statement from the angular team on this topic :)

### Provide any additional information here in as much as detail as you can

I've setup a stackblitz to show 3 different approaches I see now, probably we can find even more variations, but really wondering what to choose/which is the 'default angular way'...
https://stackblitz.com/edit/stackblitz-starters-bg7wyc?file=src%2Fmain.ts

**Comment by TarsisDragomir** [comment]
@pkozlowski-opensource would really appreciate your thoughts on the above

**Comment by HammamBM** [comment]
From my experience using effects, most effect can be reduced by atomizing components and changing the effect to a @Input set or something similar.

**Comment by TarsisDragomir** [comment]
@HammamBM thx for quick reply, but I'm afraid my question is not clear enough when I read your answer, I tried to change the title and hope it becomes more clear. 
I want to know if it's OK to use an effect for retrieving data (and setting other signals). A pattern that almost every application needs, but according to the angular.dev documentation, it doesn't appear to be intended for such purposes. On the other hand I've noticed people utilizing it for exactly that. That way they can avoid extensive use of rxjs.

**Comment by HammamBM** [comment]
@TarsisDragomir I think the same still applies. At least, that's what I try to do. Use the observable with ASYNX pipe on my @Input. The issue with effect for that is that you have to "cheat" setting allowSignalWrites to true.

**Comment by Hafnernuss** [comment]
I don't think that effects, used with `allowSignalWrites` are a valid/good usecase for retrieving data from an API. 
Signals are a good paradigm to react on ui clicks, input changes etc. but not for managing/reloading data imho. I'd stick to observables for this.

I've glanced over the docs, but could not find a clear statement about this either.

**Comment by TarsisDragomir** [comment]
I'm nowhere using `allowSignalWrites` in the effect approach, that would indeed feel wrong. Did you check the stackblitz? I'm using explicitly `untracked` around the async part, which is even not really necessary as long as you are sure it is async. But in a normal application the http.get would be hidden in a service and if that service builds in caching or something the subscribe can be executed in a synchronous way, that's why I would still put `untracked` around it to make it clear that effect dependency tracking has to stop there.
In fact; if you look at the toObservable implementation, the exact same flow is used (effect + declare dependencies + untracked). To continue on that; the first 2 approaches in my stackblitz have 3 effects running hidden in the background, whereas the 3rd approach by writing the effect ourself, there is only 1. No longer a stream of data, but just a writable signal that gets (re)filled whenever needed. I feel that will be understood more easily by newer (angular) developers. 
I work for an organization with many developers that - how to say it politely - have very different experience levels and we are trying to 1) stick as close as possible to angular rules/best practices and 2) keep it as simple/maintainable/readable as possible. So I'm trying to figure out the options we have before we go for a massive angular 17 rollout.
I would really appreciate feedback from core team members on the vision/future of reactivity in angular to be unblocked in our rollout process.

**Comment by Zooce** [comment]
We use `effect` to do this fetch-some-new-data-when-a-signal-changes-and-store-it-in-another-signal pattern in several places with the use of `untracked` and it works great. We do all of this in services and testing is also fine with the use of `TestBed.flushEffects()`.

I find it kind of unfortunate that the use of effects are discouraged because they're very useful. Any mechanism provided by the framework can be abused - so I think the documentation would be better off educating users on how effects work versus making scary claims that they shouldn't use it if they don't have to.

**Comment by hoangvutruong513** [comment]
> We use `effect` to do this fetch-some-new-data-when-a-signal-changes-and-store-it-in-another-signal pattern in several places with the use of `untracked` and it works great. We do all of this in services and testing is also fine with the use of `TestBed.flushEffects()`.
> 
> I find it kind of unfortunate that the use of effects are discouraged because they're very useful. Any mechanism provided by the framework can be abused - so I think the documentation would be better off educating users on how effects work versus making scary claims that they shouldn't use it if they don't have to.

My team was also using the pattern you describe above. I would say it probably works 99% of the time, until we hit an issue with race condition that took us so many days to replicate and troubleshoot.

So the basic code would look like this:

```ts
...
http = inject(HttpClient);
pageIndex = signal(1);
list = signal([]);

fetchEffect = effect(async () => {
  const fetchedList = await this.http.get(`path/to/item/${this.id()}`);
  untracked(() => this.list.set(fetchedList));
});

changePage(newPage: number) {
  this.pageIndex.set(newPage);
}
...
```

The problem is that, if the user changes the `pageIndex` too fast by clicking the button that performs the `changePage` function, that would cause multiple Http Request to be fired, which could lead to out-of-order updates of the `this.list` signal. 

If you are lucky, all the Http Requests complete in their initial firing order, you won't have a problem. OTOH, if just 1 Http Request completes out of order, you would have a stale list. But overall, you would end up hurting the UX anyway, because you are firing all these Http Requests without canceling the previous Request.

We could pass in a cleanup function in the `effect` callback to cancel the previous Http Request before firing a new one. There are ways around this.

If you have some React experience and know that using the `useEffect` hook to fetch data could sometimes lead to `useFootgun()` scenarios, the example above would really hit home.

So I would recommend not using `effect` to fetch/refetch data from API, upon signal changes.

**Comment by pkozlowski-opensource** [comment]
Angular v19 will include experimental `resource` that is catering to this need: https://github.com/angular/angular/pull/58255
