### ISSUE TITLE
Zone.js propagates false positive unhandled rejections

### ISSUE THREAD

**Issue by ldellorto** [angular/angular#54175]
### Which @angular/* package(s) are the source of the bug?

zone.js

### Is this a regression?

Yes

### Description

When catching a promise rejection with a traditional try catch block, zone.js still considers the rejection as unhandled.
Very easily reproduceable with the provided reproduction link.

Zone.js incorrectly thinks this rejection is unhandled:
```
try {
	await Promise.reject(Error("rejected in promise!"));
} catch(e) {
	console.log("caught error in try catch: " + e);
}

```
It works as expected when the catch block is setup on the promise itself:
```
await Promise.reject(Error("rejected in promise!")).catch(function (e) {
	console.log("caught error in promise catch block: " + e);
});
```

### Please provide a link to a minimal reproduction of the bug

https://stackblitz.com/edit/stackblitz-starters-hewzwo?file=src%2Fmain.ts

### Please provide the exception or error you saw

```true
preview-70b26ed60029a.js:2 Error: rejected in promise!
    at doRejection (main.ts:23:26)
    at Object.eval (main.ts:29:1)
    at eval (main.ts:29:15)
    at eval (main.ts:29:15)
    at eval (<anonymous>)
    at Qt (webcontainer.a8c70b9797689ab630bc39693935365c46b0aa9d.js:15:30145)
    at webcontainer.a8c70b9797689ab630bc39693935365c46b0aa9d.js:15:38799
    at U (webcontainer.a8c70b9797689ab630bc39693935365c46b0aa9d.js:15:13565)
    at webcontainer.a8c70b9797689ab630bc39693935365c46b0aa9d.js:15:13207
    at boot (boot:9:3)
```

**Comment by JiaLiPassion** [comment]
@ldellorto 
I run your sample in local, it can not be reproduced, it seems stackblitz not transpile `async/await` to `Promise`. Could you try it in your local?

**Comment by JeanMeche** [comment]
+1 This is a stackblitz issue. 

Stackblitz does't convert `await` into a generator function when targeting ES2017 and above.

**Comment by kamtschatka** [comment]
I think you are misunderstanding the issue here.
The fact that Stackblitz doesn't convert `await` into a generator function does not matter. We came across this issue, because we are writing code that runs side-by-side with an Angular application (which I guess does this transpilation, eventhough technically Angular seems to only support browsers that have native `Promise` support) and the ZoneJS behavior causes issues in our code (and ultimately in the Angular application, because they show an error screen whenever an uncaught exception happens. In the code it is not actually uncaught, ZoneJS just changes the behavior).

Seems like when ZoneJS is on the page, it currently requires ALL the code on the page to have `await` transpiled into a generator function, which should not be a requirement.

**Comment by JoostK** [comment]
Is this the same problem as reported in https://github.com/angular/angular/issues/51328?

**Comment by kamtschatka** [comment]
Yeah that seems to be the same issue. thx.
