### ISSUE TITLE
Update Styleguide Style 07-04 and mention `inject()`

### ISSUE THREAD

**Issue by d-koppenhagen** [angular/angular#54220]
### Describe the problem that you experienced

The Angular Styleguide recommends in **Style 07-04**, to use the `@Injectable()` class decorator instead of the `@Inject` param decorator. This recommendation seems to be partially outdated since it still shows the constructor injection way of DI.
In my opinion more and more people are switching to use `inject()` since it has some advantages compared to the other approaches:

- It's more universal and can be used in other [Injection Contexts](https://angular.dev/errors/NG0203#) as well and not only within the constructor
- When looking at a whole application, a mix of constructor injections and injections via `inject()` (e. g. in functional interceptors or resolvers) causes confusion and makes the overall codebase harder to understand. It's simply more consistent
- it doesn't collide with the native JS implementation for classes (keyword: `useDefineForClassFields`).

### Enter the URL of the topic with the problem

https://angular.dev/style-guide#style-07-04

### Describe what you were looking for in the documentation

https://angular.dev/errors/NG0203#

**Comment by alxhub** [comment]
Recommending `@Injectable` over `@Inject` is definitely outdated - Since v9/Ivy, Angular has _required_ `@Injectable` (or another Angular decorator) for all DI-participating classes. The alternative of using `@Inject` on parameters only is not supported, so we can probably delete this whole recommendation.

**Comment by d-koppenhagen** [comment]
Great!
And what about recommending `inject()` over constructor injection? Is there some downside I didn't see? I think it could be worth to add a style guide recommendation for it.

**Comment by jperezruiz** [comment]
Why should Angular recommend using the `inject()` instead of the constructor? I personally still prefer using the constructor, as it's less "magical" (`inject()` only works in the injection context).

I had projects where I had to move services away from angular, and because I was using the constructor, I had no problem moving the class outside angular ecosystem.

Also, using the constructor make it easier to test services, as they really don't require the Angular DI to be tested.
