### ISSUE TITLE
QueryList is not a Iterable

### ISSUE THREAD

**Issue by filipesilva** [angular/angular#5437]
Trying to use a `QueryList` in a `for ... of` loop in typescript yields the following compilation error:

```
Type 'QueryList<MyHero>' is not an array type or a string type.
```

Usage example:
```
@ViewChildren(MyHero) myHeroes: QueryList<MyHero>;
recallAllHeroes(){
  for (let myHero of this.myHeroes) {
    // ...
  }
}
```

Adding @vsavkin for reference.

**Comment by araujoigor** [comment]
Try changing your typescript settings to es6. Anyway, even after that, the tsc will complain about QueryList not having a "'\[Symbol.iterator\]()' method that returns an iterator". Funny thing is that [it implements a getSymbolIterator method](https://github.com/angular/angular/blob/e7470d557df0400a812d84551524970cb5f12eee/modules/angular2/src/core/linker/query_list.ts#L64) that is not being exposed on the d.ts. I tried to play around with the .d.ts file, trying to add the getSymbolIterator definition, but it didn't work. I also added a Symbol.iterator but it obviously didn´t work because the source code itself does not have the method definition.

Any words from Angular team?

**Comment by zoechi** [comment]
Is this a dup of #7022 
see also PR #6314, #6341

**Comment by araujoigor** [comment]
Thanks @zoechi. 
By the way,  I managed to bypass typescript checking by adding the line `[Symbol.iterator](): any;` to query_list.d.ts. During runtime, javascript will be able to iterate over the QueryList items just fine.

I think that would be a temporary solution.

**Comment by pkozlowski-opensource** [comment]
Closing as dup of #7022
