### ISSUE TITLE
Async pipe continuously reloads url when used to call url passed in method

### ISSUE THREAD

**Issue by matthewdenobrega** [angular/angular#5442]
I'm not sure if this is intentional, but it seems counter-intuitive to me. 

If I do 

    *ng-for="#person of people | async"

with 

    people = http.get(url).map(res: Result => res.json)

then if people is requesting an invalid resource (for example one that 404s), one request is made and  the process stops.

If I do 

    *ng-for="#person of getPeople() | async"

with 

    getPeople() {return http.get(url).map(res: Result => res.json)}

then if people is requesting an invalid resource, the request is refired immediately after the error, and this continues indefinitely.

Plunkr is here: http://embed.plnkr.co/CzqcWUAtYNNxqtLb1hzF/preview

I can see that binding straight to people is cleaner, but I imagine many people are used to doing things like peopleService.getPeople(), and I think handling this case is better than just retrying the request repeatedly. 

Supporting method calls also allows for parameter passing:

    *ng-for="#person of getPeople(searchParams) | async"

**Comment by robwormald** [comment]
the problem with this syntax is that each time change detection fires, you are receiving a new instance of the promise (because the getPeople() method *must* be fired, or there's no other way of detecting if the value has changed....) - and therefore refiring the request - it's nothing to do with the pipe specifically. 

This behavior would be the same in angular1, fwiw, and should be avoided where possible, as it is much less performant than using normal values. 

Does that make sense?

**Comment by matthewdenobrega** [comment]
Thanks, makes sense - I imagine the underlying thing here is to avoid returning an Observable from a method that will be called in the change detection cycle. Happy to close.
