### ISSUE TITLE
add `strictUnusedTemplate` to template type checker

### ISSUE THREAD

**Issue by sod** [angular/angular#54626]
### Which @angular/* package(s) are relevant/related to the feature request?

compiler

### Description

referencing `@angular/compiler 17.2.0`

I like your addition of lint like features to your template compiler, listed on https://angular.dev/tools/cli/template-typecheck#troubleshooting-template-errors

Another warning it could throw. Unused templates:

```html
<ng-template #foo>contents</ng-template>
```

If nobody accesses `foo` in the template or no `@ViewChild('foo')` annotation exists, this could be an error.

This could catch errors that happen because someone removed `*ngTemplateOutlet` but forgot to either remove or use the template otherwise.

**Comment by alxhub** [comment]
This is a little difficult to conceive, since it's hard to tell if the `<ng-template>` is used or not. It might be in the projected content of another component, where it could be queried by the name `foo` or simply `TemplateRef`. The compiler could theoretically know which content would be projected and thus subject to querying, but that's getting very nuanced. I think this is a good candidate for a lint error.

**Comment by sod** [comment]
I thought it was possible, as my intellij IDEA grays out unused templates:
![CleanShot 2024-02-28 at 12 20 08@2x](https://github.com/angular/angular/assets/905328/e17e11b6-f65c-45bc-8dca-51b809133d26)

But I admit it's not 100% accurate.

If you think it's not possible, feel free to close.
