### ISSUE TITLE
zone.js breaks on iOS 16 , starting at v0.13.0

### ISSUE THREAD

**Issue by just-toby** [angular/angular#54867]
### Which @angular/* package(s) are the source of the bug?

zone.js

### Is this a regression?

Yes

### Description

starting with v[0.13.0](https://www.npmjs.com/package/zone.js/v/0.13.0) , importing zone.js into our [web app](https://github.com/Uniswap/interface) causes the page to crash before it loads. this we've only confirmed this happening on iOS 16.2. it is not happening on iOS 17.

### Please provide a link to a minimal reproduction of the bug

https://github.com/just-toby/zonejs-ios-repro

### Please provide the exception or error you saw

```true
`SyntaxError: Unexpected token '{'`

which links to the zone.js source code in the bundle.js file
```

### Please provide the environment you discovered this bug in (run `ng version`)

```true
reproduced on iOS 16.2 Safari
with zone.js versions:
0.14.4
0.14.2
0.14.0
0.13.0
```

**Comment by JeanMeche** [comment]
This is due to the [static initialization block](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Classes/Static_initialization_blocks), only supported from Safari 16.4 onwards.

https://github.com/angular/angular/blob/da906fdafcbb302fa280a162d1c1f04369be2efa/packages/zone.js/lib/zone.ts#L725
