### ISSUE TITLE
Recursive loadChildren fails in 17, but worked in 16

### ISSUE THREAD

**Issue by WhatsThatItsPat** [angular/angular#54898]
### Which @angular/* package(s) are the source of the bug?

core, zone.js

### Is this a regression?

Yes

### Description

In Angular 16 (with a standalone app), I am able to recursively route to the same lazily loaded component, infinitely. The use case is something like Facebook, where you can infinitely route forward through pages of different friends. I've been able to do this in versions prior to 16 as well.

The routes for the pages look something like this:

```ts
// some-other.component.ts
[
  {
    path: '',
    component: SomeOtherComponent
  },
  {
    // SomeOtherComponent loads the first instance of RecursiveComponent.  
    path: 'recursive',
    loadChildren: () => import('./recursive.component')
  }
]

// recursive.component.ts
[
  {
    path: '',
    component: RecursiveComponent
  },
  {
    // RecursiveComponent is able to load another version of itself. 
    path: 'recursive',
    loadChildren: () => import('./recursive.component')
  }
]
```

Here's an [example of this working in Angular 16](https://github.com/WhatsThatItsPat/recursive-ng16). The example is meant to mimic a tabbed Ionic app.

From any tab, you can tap the `recursive N` button. The URL will continue to grow as `recursive` is added as a URL segment.

But it [doesn't work in Angular 17](https://github.com/WhatsThatItsPat/recursive-ng17).   You can route to the first instance of the `RecursiveComponent`, but the first attempt at recursion fails with:

  > `ERROR ReferenceError: require_recursive_component is not defined`.

### Please provide a link to a minimal reproduction of the bug

https://github.com/WhatsThatItsPat/recursive-ng17

### Please provide the exception or error you saw

```true
ERROR ReferenceError: require_recursive_component is not defined.
```

### Please provide the environment you discovered this bug in (run `ng version`)

```true
Angular CLI: 17.3.0
Node: 20.11.0
Package Manager: npm 10.2.4
OS: darwin x64

Angular: 17.3.0
... animations, cli, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1703.0
@angular-devkit/build-angular   17.3.0
@angular-devkit/core            17.3.0
@angular-devkit/schematics      17.3.0
@schematics/angular             17.3.0
rxjs                            7.8.1
typescript                      5.3.3
zone.js                         0.14.4
```

### Anything else?

I'm not sure what to answer for "Which @angular/* package(s) are the source of the bug?" Core and Zone.js are both in the callstack.

**Comment by atscott** [comment]
This seems likely to be an esbuild issue rather than anything to do with framework specifically. Note that your `loadChildren` does not _have_ to be an `import` statement and in your case, there's no value in it since the file is already loaded. You can just change the `loadChildren` function to return the routes variable again: https://stackblitz.com/edit/stackblitz-starters-bgjmmw

@clydin Any additional thoughts here?

**Comment by WhatsThatItsPat** [comment]
Wow, I've never seen `loadChildren` without an `import`. Thanks for the solution.

I've been doing it my previous way for a few years and was surprised when it didn't work. I'll leave it up to y'all to decide if this is a real issue to fix.

**Comment by hiepxanh** [comment]
Wew it was introduce in angular 15 but esbuild broken lazyload

**Comment by clydin** [comment]
As mentioned above, since the module is importing itself, there is no lazy loading in the recursive scenario. The ES module is already loaded and all members are available for direct access.  There's no benefit to self importing. Circular imports are generally discourage as well. ES modules are also effectively singletons so the comment from the code of `load another version of itself` is technically not correct either.
However, while this does appear to be a defect in the bundler, this will most likely remain a low-priority defect as there appears to be no real world use case for this construct.

**Comment by atscott** [comment]
Thanks @clydin. I’m going to closing this then as an issue with the bundler with an easy workaround.
