### ISSUE TITLE
Observable sequence for click events using RxJS

### ISSUE THREAD

**Issue by varghesep** [angular/angular#5489]
Using this [rx.angular.js](https://github.com/Reactive-Extensions/rx.angular.js) library, the click events can be turned to an observable sequence. I think this library works with **angular1** only.

Can I achieve the same in angular2 with internal **EventEmitter** or should I integrate with **RxJS**?

Example from the **rx.angular.js** library:

```javascript
/*
      Creates a "click" function which is an observable sequence instead of just a function.
    */
    $scope.$createObservableFunction('click')
      .map(function () { return $scope.search; })
      .flatMapLatest(searchWikipedia)
      .subscribe(function(results) {
        $scope.results = results;
      });
```

**Comment by maxdignan** [comment]
You could #reference the DOM node you want to add a click event to. Then import Observable from angular2/angular2. Then give Observable.fromEvent(this.reference.onclick) a try.

**Comment by varghesep** [comment]
I posted a question in the [RxJS](https://github.com/ReactiveX/RxJS/issues/811) about this. What you suggested may be a right approach.

**Comment by maxdignan** [comment]
In terms of EventEmitters however. If you are familiar with Rx.Subject, EventEmitter is very similar in Angular2. That could make this whole thing easier. Have a (click) event fire a .next(value) on your EventEmitter.

**Comment by robwormald** [comment]
EventEmitter (currently) is literally an Rx.Subject, so that's the easiest way to accomplish that currently as @maxdignan suggests - long term, that may not be the case and it would be advisable to simply use a Subject.

```
this.clickStream = new Subject();
this.clickStream.subscribe(v => console.log(v));
```
```
<button (click)="clickStream.next($event)">Click Me</button>
```

See also https://github.com/angular/angular/issues/4062 for a related proposal.

@varghesep please try asking these questions on our gitter channel - https://gitter.im/angular/angular - before opening an issue here, as we try to keep Github issues for actionable issues and feature requests, rather than how-to's. Cheers!
