### ISSUE TITLE
Upgrade from 12.2.0 to 14.2.7

### ISSUE THREAD

**Issue by BlinovaK** [angular/angular#54962]
### Which @angular/* package(s) are the source of the bug?

core

### Is this a regression?

Yes

### Description

Application successfully builds and ng serve runs. But when I start builded application - I have this exception:
![image](https://github.com/angular/angular/assets/93737017/6dcb4d11-677e-48ce-904e-c7826a2b0b10)
Green is succeeded, red is failed.

I saw the same problem #45265, but in my case all versions a same. I try reinstall all node_modules and have same result

### Please provide the exception or error you saw

```true
ERROR TypeError: p.ɵɵelementStart(...) is not a function
    at template (vlt.js?hash=0b1975a4496b70a3a7a5218fd430f5ea:1:3552527)
    at Ja (scripts.js:886:15814)
    at Ya (scripts.js:886:13798)
    at Iu (scripts.js:886:25408)
    at scripts.js:886:13997
    at Ya (scripts.js:886:14008)
    at t.create (scripts.js:1387:14596)
    at e.initializeComponent (scripts.js:2500:285)
    at scripts.js:2492:1779
    at e.runInZone (scripts.js:2500:2180)
```

### Please provide the environment you discovered this bug in (run `ng version`)

```true
Angular CLI: 14.2.7
Node: 14.18.1
Package Manager: npm 6.14.15
OS: win32 x64

Angular: 14.2.7
... animations, cdk, cli, common, compiler, compiler-cli, core
... elements, forms, localize, material, platform-browser
... platform-browser-dynamic

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1402.7
@angular-devkit/build-angular   14.2.7
@angular-devkit/core            14.2.7
@angular-devkit/schematics      14.2.7
@schematics/angular             14.2.7
rxjs                            7.8.0
typescript                      4.6.4
```

**Comment by JoostK** [comment]
Please study the output of `npm ls @angular/core`, as I suppose there's multiple copies of Angular core being included. This is otherwise a support request.

---

Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).
