### ISSUE TITLE
Using Angular2 and RxJS functional way

### ISSUE THREAD

**Issue by varghesep** [angular/angular#5496]
I posted some sample code in the [RxJS Github](https://github.com/ReactiveX/RxJS/issues/811) that shows the integration of **Angular2** and **RxJS http** for a list view with paging support.

Is there some guidelines on using reactive principles in angular2 components?

**Comment by nigeman** [comment]
+1 this!

**Comment by PascalPrecht** [comment]
@varghesep based on the current Http implementation, your code looks good to me! I don't think that there are any specific guidelines on how to use reactive APIs in Angular.

Angular uses Rx under the hood for some certain things like Http, Forms and Content/View children. Other than that, you should be able to integrate Rx APIs seamlessly.

I'm sure @robwormald has some thoughts on this.

**Comment by robwormald** [comment]
I'm waiting till release to write a book so you can all buy it ;-)

Here's a quick and dirty version http://plnkr.co/edit/x5H7nJRxNQtDnKrG9fZE?p=preview

**Comment by xstof** [comment]
@varghesep : any specific reason you decided to subscribe to the observable in your component code rather than have the view do it through the ... | async pipe please?  For paging, I can imagine you'd maybe want to expose an observable with available page numbers; each page number accompanied by another observable that provides data for the page? I'd love to see some best practices emerge.
