### ISSUE TITLE
routerLinkActiveOptions fragment add option to not match when no fragment is used

### ISSUE THREAD

**Issue by mebibou** [angular/angular#54977]
### Which @angular/* package(s) are relevant/related to the feature request?

router

### Description

Consider the following example:
```html
<a routerLink="./" [routerLinkActiveOptions]="{fragment:'exact'}" routerLinkActive="link-active"></a>
<a routerLink="./" fragment="fragment1" [routerLinkActiveOptions]="{fragment:'exact'}" routerLinkActive="link-active"></a>
```

If you go on the page `./`, only the first link will get the `link-active` class. If you go on `./#fragment1`, both links will get the `link-active` class.

While that might be the desired effect for some, it is not necessarily always desired.

### Proposed solution

Add another option to `IsActiveMatchOptions.fragment`, like `exact-required`, that would say:
- if the link has the same `fragment`, it is a match
- if the link has a different `fragment` or **does not have** a `fragment`, it is not a match

Which would differ from the current `exact` that behaves like:
- if the link has the same `fragment` or **does not have** a `fragment`, it is a match
- if the link has a different `fragment` it is not a match

### Alternatives considered

Maybe this is a bug and the `exact` option should say "if there is no fragment, it is not exact, and therefore should not be a match"

**Comment by atscott** [comment]
The issue here is that you actually have to provide the _entire_ `IsActiveMatchOptions` interface (more specifically, this is determined at runtime by the presence of `paths` in the object. You should be getting a compiler error here, as seen in https://stackblitz.com/edit/stackblitz-starters-cyrv6i if you attempt to provide just `fragment`. It seems you probably have strict templates turned off.

Closing as working as expected (should be producing a compiler error but does not due to compiler options).

**Comment by mebibou** [comment]
@atscott sorry for not providing the full options, I thought it was enough to highlight the point. See #54992, where I provided it fully
