### ISSUE TITLE
Components with a 'required' signalized input can not be dynamically created with createComponent

### ISSUE THREAD

**Issue by PowerSupply** [angular/angular#55071]
### Which @angular/* package(s) are relevant/related to the feature request?

core

### Description

Components with a 'required' signalized input can not be created with createComponent without triggering [NG0950](https://angular.io/errors/NG0950).

I guess the idea is that you should use the [setInput method](https://angular.io/api/core/ComponentRef#setInput) to set a value for the required input. But the problem is that there is no way to know what inputs are required or not. This is due to an input being required or not is not part of the [ComponentMirror](https://angular.io/api/core/ComponentMirror) interface  as previously reported https://github.com/angular/angular/issues/52117.

Having to know what inputs are required or not greatly limits the ability of createComponent to actually work as a dynamic component factory. As it stands right now only components without required signal inputs can be dynamically created.

### Proposed solution

I see two solutions to this:

1. Don't error (like when @Input({ required: true }) is used)
2. Add information to each input if it is required or not to the ComponentMirror interface

### Alternatives considered

The alternative is that you can not use signal inputs and stick with the old way.

**Comment by alxhub** [comment]
Components with required inputs can be dynamically created, just make sure those inputs are set via `.setInput()` before the component is change detected.

Note that it's not possible to dynamically create an _arbitrary_ component in a guaranteed correct way. Any component can have assumptions about how it'll be created:
* with certain DI providers available
* with certain inputs available (required inputs)
* what types of values it accepts for its inputs
* as a child of a specific other component
* with specific content children
* with a certain directive applied (not possible to do dynamically)

To correctly create a component, you need to meet these requirements. I don't think having the required status of inputs available via `ComponentMirror` is sufficient. For example, since you don't know the types of such inputs, how can you expect to create the component correctly?

**Comment by alxhub** [comment]
Closing as answered - I don't think there's any more action we can take with this issue.

**Comment by PowerSupply** [comment]
Hi,
Thanks for reading my issue and sorry for the late reply, I've been a bit busy.

I understand that the ComponentMirror interface will never bu fully sufficient to create an arbitrary component. But that begs the question: What decides what information goes into the interface and what information is left out?

I understand why compile time information like types can not be in the interface. But what makes, for example, [templateName](https://angular.io/api/core/ComponentMirror#inputs) more useful to have in the interface than if an input is required? In my opinion it is not.

If I would have to guess; I think that the original aim of the ComponentMirror interface was to provide all the runtime information that is available about a component. But the interface was not extended when required inputs was introduced as runtime information. I believe this is a mistake, but welcome any explanation that would change my conclusion.
