### ISSUE TITLE
Recursive template with @defer

### ISSUE THREAD

**Issue by olegdunkan** [angular/angular#55332]
### Which @angular/* package(s) are the source of the bug?

core

### Is this a regression?

No

### Description

```
@Component({
  selector:'page',
  standalone:true,
  imports:[NgTemplateOutlet],
  template:`
  <ng-container *ngTemplateOutlet="tpl; context:{$implicit:0}"></ng-container>
  
  <ng-template #tpl let-page>
    <h1>№{{getPage(page)}}</h1>
    @defer(on viewport) {
      <ng-container *ngTemplateOutlet="tpl; context:{$implicit:page + 1}"></ng-container>
    }
    @placeholder {
      <h1>Loading</h1>
    }
  </ng-template>
  `
})
export class PageComponent {
  getPage(page:number) {
    console.log(page);
    return page;
  }
}
```

Method _getPage()_  are executed more times than expected.
Output from _getPage()_ like this:
0
0
1
0
1
2
0
1
2
3
...
but expected like this:
0
1
2
3
...

### Please provide a link to a minimal reproduction of the bug

https://stackblitz.com/edit/stackblitz-starters-l13k96?file=src%2Fmain.ts

### Please provide the environment you discovered this bug in (run `ng version`)

```true
Angular CLI: 17.3.3
Node: 20.10.0
Package Manager: npm 10.2.3
OS: darwin x64

Angular: 17.3.2
... animations, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1703.3
@angular-devkit/build-angular   17.3.3
@angular-devkit/core            17.3.3
@angular-devkit/schematics      17.3.3
@angular/cli                    17.3.3
@schematics/angular             17.3.3
rxjs                            7.8.1
typescript                      5.4.3
zone.js                         0.14.4
```

**Comment by JoostK** [comment]
This happens because the `IntersectionObserver` used to implement the `on viewport` trigger is asynchronous, so each level introduces its own microtick delay and therefore an additional round of change detection.

The documentation also states that the `on viewport` trigger is driven by `IntersectionObserver`, confirming its asynchronous behavior, so this isn't a bug per se. That said, I can see how a "preflight" viewport test might help avoid the additional microtick latency and its associated change detection cycle.

**Comment by JoostK** [comment]
Even that isn't great really, as it would result in a forced layout.

**Comment by olegdunkan** [comment]
I reopen the issue because I need some clarification from angular team.
Is it ok to execute template expression O(n^2) times in the case of defered recursive template?

**Comment by alxhub** [comment]
I'm going to close this as working-as-intended.

In general, using `@defer` recursively this way will do N change detections as it's truly a waterfall of rendering:

1. A `@defer` block is rendered and creates the placeholder element in the first change detection.
2. `IntersectionObserver` asynchronously observes the placeholder in the layout and fires an event.
3. That event triggers the `@defer` block, and the next round of change detection runs, creating the next `@defer` block (goto 1)

Each template expression will be executed O(N) times - once for each step in the waterfall.

You observe your logging statement being called O(N^2) times because each instance of the template has its own logging binding, so you end up with N instances * O(N) calls per instance.

**Comment by olegdunkan** [comment]
> In general, using @defer recursively this way will do N change detections as it's truly a waterfall of rendering
@alxhub May I conclude that using recursive template is anti-pattern in angular?

**Comment by alxhub** [comment]
Recursive templates aren't really related to this issue. They don't by themselves cause waterfalls, and it's easy to rewrite the example into a waterfall without recursive templates at all.

**Comment by olegdunkan** [comment]
@alxhub now I see, the problem is we can't render all `ng-template` embedded views in one changes detection round because `IntersectionObserver` triggers that, other rounds. But if use recursive `ng-template` without `@defer` angular renders it with help of only one changes detection round.
Unfortunately we can't prevent execution of template expressions previously created (by `IntersectionObserver's` changes detection rounds) embedded views because there is no way to control changes detection strategy per embedded view. 
As I know signals will be able to mark view for check and we will be able to avoid situation like above. Is that related to embedded view also or it is related only to component level view?
