### ISSUE TITLE
Incorrect namespace applied when binding to xlink:href attribute in SVG 'use' elements

### ISSUE THREAD

**Issue by larrifax** [angular/angular#5548]
I'm attempting to bind values to the ```xlink:href``` attribute of a ```<use>``` element contained inside a ```<svg>``` element like so:
```
<svg>
   <use [attr.xlink:href]="url"></use>
</svg>
```
This does not work in either alpha 47 or alpha 46, as no SVG image is displayed. See the following plunk, which illustrates the problem: http://plnkr.co/edit/ELcnoTe2CE5v5r9FUD0c?p=preview

It looks like the ```xlink:href``` attribute is missing the correct namespace when binding to it. Executing the following statement in the Chrome developer console when targeting the ```<use>``` element fixes the problem:
```$0.setAttributeNS("http://www.w3.org/1999/xlink", "xlink:href", "assets/icons/icons.svg#icons--alert")```

**Comment by larrifax** [comment]
This still applies to beta 0. Plunkr is updated with the latest version.

**Comment by ivansieder** [comment]
As even with ng2 beta 6 the bug seems to presist (`[attr.xlink:href]` doesn't seem to load the resource correctly), I found, that adding an empty regular html-tag `xlink:href=""` works around the the issues and the specified id of the svg loads correctly.

Now instead of this:

`<svg viewbox="0 0 8 8"><use [attr.xlink:href]="'sprite.svg#' + item.icon"></use></svg>`
The code has been changed to this (just added an empty `xlink:href=""`):

`<svg viewbox="0 0 8 8"><use [attr.xlink:href]="'sprite.svg#' + item.icon" xlink:href=""></use></svg>`

**Comment by pkozlowski-opensource** [comment]
Fixed by c517141

**Comment by rphansen91** [comment]
The recommended solution still is not working for me. However I was able to work around it by creating a Directive.

I posted the code and explanation to [StackOverflow ](http://stackoverflow.com/a/38600444/5552799) it will load svg's and parse it for <use> ;) similar to SVG4Everybody.
