### ISSUE TITLE
declare peer dependencies as peer dependencies

### ISSUE THREAD

**Issue by jeffbcross** [angular/angular#5560]
Our package.json lists many peer dependencies as just dependencies, but should be reflected as peer dependencies:
 * reflect-metadata
 * rxjs
 * zone.js
 * es6-shim

This is to make sure duplicates don't end up in bundles, and to make sure Angular is sharing the same instances of modules. This is particularly important with RxJS where importing operators has a side effect of monkey-patching the `Observable` imported from `rxjs/Observable`.

**Comment by jeffbcross** [comment]
@IgorMinar what about es6-shim?

**Comment by IgorMinar** [comment]
that too

**Comment by IgorMinar** [comment]
all of our dependencies are peer dependencies

one thing to point out is that this will have an impact on getting started experience, because `npm install --save angular2` will no longer be sufficient. I think that while getting started experience is important, setting up the dependencies correctly is even more important. We could file a bug against npm to have an option to install and save peer dependencies automatically.

**Comment by rkirov** [comment]
Not sure how much it matters given that for the webpack workflow seems to work just fine with deps instead of peer deps - https://github.com/pkozlowski-opensource/ng2-webpack-play. 

> We could file a bug against npm to have an option to install and save peer dependencies automatically.

I don't think you want to open that can of worms again - https://github.com/npm/npm/issues/6565

**Comment by IgorMinar** [comment]
if you use  a seed or CLI then you will not be affected. it's only if you
start your project from scratch via npm init or npm install angular2 --save
that you will need to do more.

I think it's ok to make "starting from scratch" more difficult because we
don't expect many people to do that.

**Comment by wardbell** [comment]
What is the revised install experience without cli? Might have a workaround or try to find one. Not everyone will go for the cli.

**Comment by IgorMinar** [comment]
something like: npm install --save angular2 rxjs es6-shim zone.js

**Comment by IgorMinar** [comment]
of course things might get tricky if angular2 requires versions of peer
dependencies that are older than the latest version

**Comment by pkozlowski-opensource** [comment]
> something like: npm install --save angular2 rxjs es6-shim zone.js

@IgorMinar I don't think it is that simple as we might have a situation where all the latest versions (ones resolved and installed by npm when no version is specified) might not work together. RxJS is the one that worries me the most here. I guess we are in the special period where several projects (zone, Rx, ng2) are moving very fast so probability of getting into troubles is higher. Unless we "lock" peer dependencies to a very narrow range.

I would vote for differing decision on  deps vs. peerDeps till we've got bundling story figured out since we need to look into the entire experience with ng2.

**Comment by IgorMinar** [comment]
Right the peer deps have to have narrow version range for now. That's the
penalty for living on the edge. But that's a good thing because people
won't be able to accidentally use angular with wrong dependencies.

**Comment by IgorMinar** [comment]
I sent out a PR. can someone review please
