### ISSUE TITLE
I smell a rat, stop ruining angular

### ISSUE THREAD

**Issue by Milldrew** [angular/angular#55676]
### Which @angular/* package(s) are the source of the bug?

core

### Is this a regression?

Yes

### Description

The angular project is becoming worse.

the angular team is adding multiple syntaxes for doing the same thing.

for example the new way to write logic in the html template.

and stand alone components

these idiotic attempts to make things easier add complexity.

it is better to have one solution to one problem. 

People will now have to study each different method and be prepared for multiple syntax for the same situation.

many angular developer experts might benefit from the complexity by being able to sell more YouTube videos or lessons.

This destroys the angular project. 

For example, the NGrx project is completely unnecessary.
Angular is infinitely more scalable and less complicated when you don’t use NGRX. And NGRX was a copy cat of redux, which is a react package that was created for issues with react state management not angular. And some angular teachers scam and teach this product even though it’s completely unnecessary. 

Also, the NX project is a scam and completely unnecessary and works worse than the normal angular commandline and yet a lot of angular teachers teach this instead of teaching, how to use the angular command line better

My point is is that angular the framework has existing patterns and strategies that we are using already, and it would be better to popularized the existing strategies rather than make  new redundant strategies and add complexity.

There’s plenty of work to be done on the project. For example, the angular material components are very useful and very popular. This project has a lot of potential to grow and improve the angular framework exponentially

Please do not fix problems that don’t exist and add complexity to the framework you’re ruining it

Please get rid of the rats that are coming up with these terrible ideas

### Please provide a link to a minimal reproduction of the bug

https://angular.io/

### Please provide the exception or error you saw

```true
There are some people that are destroying the angular project
```

### Please provide the environment you discovered this bug in (run `ng version`)

```true
Angular when they started standalone components, messed up dependency injection and added multiple ways to do the same thing
```

### Anything else?

Please stop destroying the project. Please make better choices.

Standalone components messed up dependency injection patterns

**Comment by rhutchison** [comment]
@Milldrew I think your account got hacked.

**Comment by JelleBruisten** [comment]
NGRX is not maintained by the angular team, neither is nx.

And about standalone and the new control flow I disagree:

- making components standalone had several benefits and should be the recommended way of doing things ( while supporting older projects that got created before standalone components)
- control flow makes it so we import less in our components and a clearer syntax beside providing a way forward for zoneless ( they mentioned the older structural directives would not function correctly in a zoneless application )

**Comment by alxhub** [comment]
@Milldrew before anything else, your comments are in violation of our community [Code of Conduct](https://github.com/angular/angular/blob/main/CODE_OF_CONDUCT.md), which is in effect on this issue tracker. Please communicate here with respect and empathy and refrain from insults.

Our process for making larger changes to Angular, like standalone, control flow, signals, etc, always involves a community [RFC](https://github.com/angular/angular/discussions/categories/rfcs), where we explain our intention and solicit feedback from any interested developers. This feedback can result in substantial updates to our plans. For example, the control flow syntax changed significantly from the initial proposal entirely due to feedback on the RFC.

If you have strong opinions about the evolution of Angular, I would encourage you to participate in the RFC process for upcoming changes (while following the code of conduct). There is always room for healthy debate in our community. That said, I'm going to close this issue as it doesn't contain any constructive feedback. You did mention problems with standalone and dependency injection - feel free to open any new issues with details if you think there is a design problem or a bug we should investigate.

**Comment by Milldrew** [comment]
Your RFC for control flown in html didn’t even mention the existing ng-container pattern!

🤦

And yes, I’m not alone. I have been discussing this on LinkedIn, and just elevating it here you guys need to get it together.

You’re welcome
