### ISSUE TITLE
Add signals reflecting state of the AbstractControl

### ISSUE THREAD

**Issue by e-oz** [angular/angular#55672]
### Which @angular/* package(s) are relevant/related to the feature request?

forms

### Description

Please make it possible to watch the state of the `AbstractControl` sub-classes using readonly signals.

### Proposed solution

Please add fields (`Signal<boolean>`) to `AbstractControl`:
* isVisible
* isInViewport
* isPristine
* isDirty
* isValid
* isPending
* isEnabled
* isTouched
* hasErrors
* isHovered
* isFocused

and a few non-boolean signals:
* currentErrors: Signal< ValidationErrors>
* currentValue: Signal<T | undefined>
* currentRawValue: Signal<T | undefined>
* currentValidators: Signal<Array<ValidatorFn | AsyncValidatorFn>>

The prefix "current" here is only used to avoid naming conflicts with existing fields, and perhaps there are better options for this prefix, or perhaps all of these fields should be grouped inside another field.

### Alternatives considered

Some of it can be implemented in the user code by monitoring `statusChanges` and `valueChanges`, but not everything. 
Some of these fields, if implemented in user code, would require monkey-patching of the `AbstractControl` methods, and we all know it's not a good idea.

**Comment by JoostK** [comment]
This is being tracked in #53485.

**Comment by e-oz** [comment]
I was aware of the issue you linked, but it doesn't list any fields. Additionally, fields like `isInViewport` or `currentValidators` are not within the scope of that issue.

**Comment by michael-small** [comment]
> Some of it can be implemented in the user code by monitoring statusChanges and valueChanges, but not everything.

The unified control events PR in the 18 release candidate exposes more events to tap into: https://github.com/angular/angular/pull/54579. I am as hyped as you for a formal signals + forms API, but this unified events API is one of the coolest things since typed/nonnullable for forms in my opinion. You can get kind of close to forms + signals with these events and interops and helper functions. In a project of mine I made utils that expose `value`/`status`/`touched`/`pristine` as both RxJS and signals using the various emitted events. Both value and raw value among other things, as well as potentially accomplishing some of the things in that bulleted list. 

Stackblitz example of the events API being `console.log`ed that I made from a Matthieu Riegler Stackblitz. https://stackblitz.com/edit/v18-unified-control-state-change-dhiz7f?file=src%2Fmain.ts,tsconfig.app.json.

Matthieu has been open to adding on more events. There is an open PR for form `submit` and `reset`: https://github.com/angular/angular/pull/55667. And errors are in the backlog: https://twitter.com/Jean__Meche/status/1786578893584925151
