### ISSUE TITLE
[testing] inject could have a better name now that it solves the async problem also

### ISSUE THREAD

**Issue by cexbrayat** [angular/angular#5570]
With `injectAsync` deprecated, I've got a lot of tests that looks like:

````
describe('RaceService', () => {
  let service;
  beforeEachProviders(() => [RaceService]);
  beforeEach(inject([RaceService], raceService => service = raceService));

  it('should return a promise of 2 races', inject([],() => {
    service.list().then(races => {
      expect(races.length).toBe(2);
    });
  }));
});
````

Works great, but it feels awkward that the test has to use a method called `inject`, not because the test needs to have something injected but to be sure the asynchronism is correctly handled.
Maybe that should be decoupled in another function with another name?

cc @juliemr @wardbell

**Comment by juliemr** [comment]
You could just write this as:

```js
describe('RaceService', () => {
  beforeEachProviders(() => [RaceService]);

  it('should return a promise of 2 races', inject([RaceService],(service) => {
    return service.list().then(races => {
      expect(races.length).toBe(2);
    });
  }));
});
```

But I see your larger point. I imagine that it would be more mental overhead to have to sometimes use `inject` but other times remember to use `runWithAsyncErrorCatching` (or a better name). Do you have a suggestion of what it should look like?

**Comment by cexbrayat** [comment]
I did not add a suggestion because I was not really sure what would be the best :)
I wouldn't mind having 2 functions each dedicated to their purpose: one for injection, one for running an async test.

For a sync test, we would have:

```javascript
describe('RaceService', () => {
  let service;
  beforeEachProviders(() => [RaceService]);
  beforeEach(inject([RaceService], raceService => service = raceService));

  // sync test and service already injected, no need to wrap with async or inject
  it('should return a promise of 2 races', () => {
    let races = service.list();
    expect(races.length).toBe(2);
  });
});
```

```javascript
describe('RaceService', () => {
  let service;
  beforeEachProviders(() => [RaceService]);

  // sync test and service needed, we wrap with inject
  it('should return a promise of 2 races', inject([RaceService], (service) => {
    let races = service.list();
    expect(races.length).toBe(2);
  }));
});
```

For async tests, maybe we should have an `async` function like:

```javascript
describe('RaceService', () => {
  let service;
  beforeEachProviders(() => [RaceService]);
  beforeEach(inject([RaceService], raceService => service = raceService));

  // async test and service already injected, no need to wrap with inject
  it('should return a promise of 2 races', async(() => {
    service.list().then(races => {
      expect(races.length).toBe(2);
    });
  }));
});
```

```javascript
describe('RaceService', () => {
  let service;
  beforeEachProviders(() => [RaceService]);

  // async test and service not already injected, need to wrap with inject and async
  it('should return a promise of 2 races', async(inject([RaceService], (service) => {
    service.list().then(races => {
      expect(races.length).toBe(2);
    });
  })));
});
```

**Comment by juliemr** [comment]
cc @vikerman

**Comment by gsans** [comment]
Having Jasmine's asynchronous handling already with done this seems unnecessary unless I'm missing something.

**Comment by ocombe** [comment]
I'm with @gsans on this, why don't you just use the "done" callback ?

**Comment by choeller** [comment]
@ocombe @gsans Can you explain how this could be done in beforeEach? I want to create the component under test in beforeEach and only get it running with `injectAsync`:

```ts
  beforeEach(injectAsync([TestComponentBuilder, TaskService],
    (_tcb : TestComponentBuilder, _taskService: TaskService) => {
      taskService = <any> _taskService;
        return _tcb
          .overrideDirective(TaskItem, RouterLink, DummyRouterLink)
          .createAsync(TaskList)
          .then(f => fixture = f);
  }));
```
trying to use done I always get:

`     Error: Timeout - Async callback was not invoked within timeout specified by jasmine.DEFAULT_TIMEOUT_INTERVAL.
`

```
  beforeEach((done) => {
    inject([TestComponentBuilder, TaskService],
      (_tcb : TestComponentBuilder, _taskService: TaskService) => {
        taskService = <any> _taskService;
        _tcb
          .overrideDirective(TaskItem, RouterLink, DummyRouterLink)
          .createAsync(TaskList)
          .then(_fixture => {
            fixture = _fixture;
            done();
          });
      })});
```

also I like the comprehensive version of `injectAsync` so I'm wondering why it is deprecated.

Thanks 
Christoph

**Comment by ocombe** [comment]
`done` only works for tests (with `it`), not in beforeEach

**Comment by choeller** [comment]
Thanks for the answer! So here:

http://jasmine.github.io/2.4/introduction.html#section-Asynchronous_Support

it is also described for beforeEach, but I know that Angular reimplemented those functions, so maybe it's not implemented (yet?). 

So, currently there is no other way then `injectAsync` to do async stuff in `beforeEach`, right? So why is it  considered deprecated?

**Comment by ocombe** [comment]
Ah my bad, you're right it is available in beforeEach (at least in jasmine 2.4).
I'm not sure why it doesn't work for you then. You should call @juliemr for help :)

**Comment by choeller** [comment]
@ocombe, ok - thank again! @juliemr: help! ;) 

So is there a way to execute async stuff in `beforeEach` unless `injectAsync`? And: why is `injectAsync` considered deprecated? I find it super useful... 

Thanks
Christoph

**Comment by vikerman** [comment]
@juliemr and I are working on this.

Splitting the concerns between sync/async and inject sounds like a good idea.

With the upcoming zone change we will be creating 3 separate test execution environments - sync, async and fakeAsync.

- async would allow tests to execute as regular asynchronous code and uses zone hooks to automatically call the jasmine done()/done.fail() method when all pending tasks are completed(successfully or errored)

- sync would execute the test in an environment that enforces that no asynchronous code(No promises or timeout. Event callbacks are fine) gets executed in the test or the component under test. The jasmine test will be executed synchronously.

- fakeAsync would execute the test in an environment where asynchronous registration is intercepted and added to an alternate task queue that can be controlled using tick([delay]) and flushMicrotasks() allowing for synchronous control of asynchronous operations. The jasmine test will be executed synchronously.

Instead of inject() and injectAsync() which handle both the execution environment as well as injection and is confusing - we can have three functions async(), sync() and fakeAsync() that would take in a function as argument and run it in the respective environments. This would make the intention of the test very clear depending on whether it's enclosed in a sync, async or fakeAsync function.

For the injection part we can have an inject() method as @cexbrayat suggested. This inject method wouldn't concern itself about sync/async issues - just does the injection.
The code would look like
```
it('fakeAsync test with injection',
    fakeAsync(inject([TestComponentBuilder, RaceService], (tcb, service) =>  {
  ...
})));
```

For tests that don't need injection they can drop the inject() method and just have the test function as

```
it('fakeAsync test without injection', fakeAsync(() =>  {
  ...
})));
```

I can think also think of one more shorthand that may or may not be confusing. We can have overloaded versions of sync, async and fakeAsync that optionally take in tokens to be injected and remove the need for a separate inject() function. So the above examples would look like

```
it('fakeAsync test with injection',
    fakeAsync([TestComponentBuilder, RaceService], (tcb, service) =>  {
  ...
}));
```

```
it('fakeAsync test without injection', fakeAsync(() =>  {
  ...
})));
```
This is then just a friendlier renamed version of inject, injectAsync and may have the same mixing of concerns as before but maybe easier to understand with the new names.


Comments?

**Comment by tbosch** [comment]
+1

**Comment by juliemr** [comment]
I like this plan. I wonder if we should stay away from `async` as a name, if it becomes a keyword in ES7.

**Comment by juliemr** [comment]
Maybe `runSync()`, `runAsync()`, and `runFakeAsync()`?

**Comment by mhevery** [comment]
I am not convinced that async is a reserved keyword. This would break the web, so I think we can have `async()` method call.

**Comment by gsans** [comment]
@vikerman makes a lot of sense separating the two.

Regarding the overloaded fakeAsync example I would recommend to refactor
the inject during beforeEach() instead as a more standard approach and to
avoid falling for an API with mixed concerns.

**Comment by vikerman** [comment]
@gsans - Agreed. Makes more sense to keep them separate.

**Comment by wardbell** [comment]
**I love this proposal. _When can I have it?_**  

I say "yes" to the inject variation rather than the separate `inject` fn. I'd rather NOT have the `inject` function if we can dispense with it.

I agree with @mhevery that we should not fear the `async()` method which no decent agent would confuse with the `async` key word.

**Comment by vikerman** [comment]
@wardbell - Soon :) We will resolve it before RC since it's potentially a breaking change.

Having inject() separately would avoid having to handle inject for every new test environment method - current and future. If inject had to take more options for some reason in the future it would make it much easier to just change it one place in the inject method. My hope is also that we will be able to actually write tests which mostly avoids DI for the test methods themselves so that the need for inject() is much lesser and needed only for special cases - because in my personal opinion DI for test methods themselves do not provide much value. So we would have economy of expression by mostly avoiding inject.

**Comment by cexbrayat** [comment]
Looks good! Thanks for considering my proposition.

I like the overloaded versions, it will keep tests shorter. And I side with @wardbell , I don't think it is confusing.

About the `sync()` function: is it necessary? Can't that be the default behavior?

**Comment by gsans** [comment]
Sorry, maybe I'm missing something on the overload @wardbell and @cexbrayat. I understand that moving the inject() to beforeEach() is a common refactor. 

So instead of doing any of these
```
describe('suite', () => {
  //setup
  beforeEachProviders(() => [myService]);
  //specs
  it('should ...', injectAsync([myService], service => { }));
  it('should ...', async(inject([myService], service => { })));
  it('should ...', async([myService], service => { }));
```
We would be doing something like
```
describe('suite', () => {
  let service;
  //setup
  beforeEachProviders(() => [myService]);
  beforeEach(inject([myService], s => {
    service = s;
  }));
  //specs
  it('should ...', async(() => { })); //zones
  it('should ...', done => { });  //jasmine
```
I see the overload proposal as a new shape of injectAsync() which I don't think is what we should be using as it mixes concerns.

**Comment by vikerman** [comment]
@cexbrayat - sync() would definitely be optional. It would provide an extra assertion that everything in the test is synchronous and makes the intention of the test clearer. I don't think we want it to be the default though since you could potentially still write an async test without using aysnc().

**Comment by jeffbcross** [comment]
For tests that may still have async behavior that zone can't predict, such as a `WebSocket` or `WebWorker`, there should still be an escape hatch to get a hold of jasmine's `done` when using `inject`. In a quick discussion with @juliemr, we considered having it as the last parameter inside the injectable function:

```typescript
it('should receive a messages', inject([Dep1], (dep1, done) => {
  var socket = new WebSocket(url);
  socket.onmessage = (msg) => { 
    expect(msg).toEqual({...}); 
    socket.close();
    done();
  };
}));
```

**Comment by juliemr** [comment]
I'll be working on this after we can pull in a zone.js release that contains the new async ZoneSpec - see https://github.com/angular/zone.js/commit/aeeb05c6949f0a670fd9c6690f30b5f3eed4d7c6

**Comment by mhevery** [comment]
We could also just do `Zone.current.get('jasmineDone')()`.

**Comment by juliemr** [comment]
Done with 8490921fb355821f3f2f44e5c88bfb900b22f971
