### ISSUE TITLE
[testing] Http testing is really verbose 

### ISSUE THREAD

**Issue by cexbrayat** [angular/angular#5575]
Up to alpha-47, a typical Http test looks like:

````TypeScript
describe('RaceService', () => {

  beforeEachProviders(() => [
    MockBackend,
    BaseRequestOptions,
    provide(Http, {
      useFactory: (backend, defaultOptions) => new Http(backend, defaultOptions),
      deps: [MockBackend, BaseRequestOptions]
    }),
    RaceService
  ]);

  it('should return an Observable of 2 races', inject([RaceService, MockBackend], (service, mockBackend) => {
    // fake response
    let hardcodedRaces = [new Race('London'), new Race('Lyon')];
    let response = new Response(new ResponseOptions({body: hardcodedRaces}));
    // return the response if we have a connection to the MockBackend
    mockBackend.connections.subscribe(connection => connection.mockRespond(response));

    service.list().subscribe(races => {
      expect(races.length).toBe(2);
    });
  }));
});
````

This is really verbose and not especially beginner friendly.
It's also not so easy to have several mocked requests in the same test and to test which URL and HTTP verb it was.
Am I missing something, or is there a plan to have something like `$httpBackend` to make this kind of test easier? A single class to inject would be great (`MockHttp`?), with utility method like we had (`expectGet()`, `expectPost()`, etc...).

cc @juliemr @jeffbcross

**Comment by PascalPrecht** [comment]
The provider setup (at least) can be a predefined list as we do for `HTTP_PROVIDERS` and `ROUTER_PROVIDERS`. So maybe `HTT_MOCK_PROVIDERS` makes sense.

> Am I missing something, or is there a plan to have something like $httpBackend to make this kind of test easier?

I think that `MockBacked` is pretty much the equivalent of `$httpBackend` in this case. Or rather the fact that we have:

```
provide(Http, {
      useFactory: (backend, defaultOptions) => new Http(backend, defaultOptions),
      deps: [MockBackend, BaseRequestOptions]
    }),
```

Because this sets up the Backend.

I do agree that convenient methods like `expectGet()` etc. would be very helpful. And on a second thought, it might make sense to have an additional object for that (instead of just whatever is provided as `Backend`), because if we want all backends to implement the same interface, this would mean that a normal actual backend needs to implement things like `expectGet()` too. But we want these APIs only for testing.

Interested in what @jeffbcross things about that.

**Comment by cexbrayat** [comment]
Thanks for your input @PascalPrecht 

In my ideal scenario, I'd like something like

````TypeScript
describe('RaceService', () => {

  beforeEachProviders(() => [
    // MockHttp should be loaded by the test injector by default
    // or it could even replace Http automatically
    provide(Http, { useClass: MockHttp }), 
    RaceService
  ]);

  it('should return an Observable of 2 races', inject([RaceService, MockHttp], (service, mockHttp) => {
    // fake response
    let hardcodedRaces = [new Race('London'), new Race('Lyon')];
    mockHttp.expectGet('/api/races').respond(hardcodedRaces);

    service.list().subscribe(races => {
      expect(races.length).toBe(2);
    });
  }));
});
````

And it would automatically fail if the test ends with the request not matching the verb and URL.
All this is doable manually right now, but quite cumbersome to write, quickly ends up in copy/pasting in a big app. I think some sugar would be great!

**Comment by robwormald** [comment]
@cexbrayat agreed this needs some sugar, and i'm open to suggestions for sure.

With your specific example though, it doesn't make semantic sense - your application code would typically do the transformation from raw json -> js objects -> instances of a class, and so returning mock already-instantiated-objects would be quite difficult to make work as you have it described. It's important to know *what* you're trying to test here, as you're expecting one thing (a request) but mocking another (the data presumably transformed in the service, rather than the raw response to that request)

Angular1 provides two basic methods of $httpBackend 
- expectation mode - where you make assertions that things *should* happen, and tests fail if they don't - responses are optional here.
- passthrough mode - where you simply say "if this happens, respond with that"

Both of these should be covered, and I'd very much like to hear ideas for more sugar to make this sort of thing easier.

**Comment by cexbrayat** [comment]
You're right, my response should be a json object, I wrote my sample a bit too fast, sorry about that. My point was more about the general flow of the test as you imagine. 

I usually rely on expect/respond for unit test to be sure that all the requests expected are triggered. The pass-through mode could also be useful, especially to fake the backend for e2e test (even if I did not try that in Angular 2 yet).

**Comment by asvifi85** [comment]
How to write jasmine test case for the following class having constructor which is having dependency on http?

import {Injectable} from 'angular2/core';
import {Http, HTTP_PROVIDERS} from 'angular2/http';

@Injectable()
export class MockUserService {
    items:Array<any>;

    constructor(http:Http){
        http.get('http://127.0.0.1:8080/src/data/names.json')
        .subscribe(res => {
            this.items = res;
            console.log('results found');
        })
    }
Below is my test file
import {it, describe, expect, inject,injectAsync, beforeEachProviders} from 'angular2/testing';

import {provide} from 'angular2/core';
import {Http, BaseRequestOptions} from 'angular2/http'; 
import {MockBackend} from 'angular2/http/testing';
import {UserInfo,MockUserService} from '../src/app/service/userservice';


describe('Testing of user info', () => {
let http:Http;
let  mockUserService:MockUserService = new MockUserService(http);
 beforeEachProviders(() => [
    UserInfo,
   
  Http,
    MockBackend,
    BaseRequestOptions,
    provide(Http, {
      useFactory: (backend, defaultOptions) => {
        return new Http(backend, defaultOptions);
      },
      deps: [
        MockBackend
      ]
    })
  ]);

   it('Testing user login', inject([MockUserService], (mockUserService:MockUserService) => {
   let http:Http;
		let mockUserService: MockUserService = new MockUserService(http);
	 expect(1+1).toEqual(2);
   
  });
  );
  
  });

**Comment by robwormald** [comment]
This issue was moved to angular/http#58

**Comment by kalahari** [comment]
The linked issue is in a private repo, is there any way to see current status?

**Comment by cexbrayat** [comment]
Yes the issues for Http were migrated than closed...

As a first step for this issue, I proposed https://github.com/angular/angular/pull/13044 to simplify the setup. I'm waiting the feedback from the team.
