### ISSUE TITLE
Integration of Angularjs 1.5 with Angular2 (typescript)

### ISSUE THREAD

**Issue by ultrasonicsoft** [angular/angular#5595]
Hi There,

As Angularjs 1.5 is built with keeping component based architecture as of Angular2, is there any example of how Angular1.5/1.4 can exists in same application of Angular2?

Thanks!

Best Regards,
Balram

**Comment by zachrip** [comment]
I was able to find this, may help: http://angularjs.blogspot.com/2015/08/angular-1-and-angular-2-coexistence.html

**Comment by PascalPrecht** [comment]
@ultrasonicsoft Angular 1.5 introduces a new `.component()` API which is simply a facade around `.directive()` making it not anything more special than any of the APIs that you had before, it's really just a convenient helper to build directives with isolated scopes.

However, this doesn't have anything to do with running Angular 1 and Angular 2 side by side, so you can totally run both version side by side even without Angular 1.5. In addition it's worth mentioning that also `.component()` doesn't help you with upgrading, it's really just a helper API to do something you can do since a long time.

What helps with upgrading is what @zachrip linked to in his comment. `ngUpgrade` is a module that allows you to bootstrap A2 components inside your A1 app and making them interoperate. A more detailed guide on upgrading in general and ngUpgrade can be found here: http://blog.thoughtram.io/angular/2015/10/24/upgrading-apps-to-angular-2-using-ngupgrade.html

I hope these resources give you a more concrete idea on how this topic can be approached. In addition, please ask these kind of "support" questions in our social channels like http://gitter.im/angular/angular as we want to keep issues for actionable feature requests and bug reports.

Thank you! :)

**Comment by ultrasonicsoft** [comment]
Thanks zachrip and PascalPrecht.
It helps a lot.

@PascalPrecht, yes did post this question on gitter but didn't get response so got bit reckless. Sorry!

Thanks again.
