### ISSUE TITLE
Angular 2 plans for Virtual DOM

### ISSUE THREAD

**Issue by demisx** [angular/angular#561]
Per [this suggestion](https://github.com/angular/angular.js/issues/10993), I am transferring this issue to 2.x project.

I am an active member of Southern California Angular community. I've noticed the trend lately that Angular starts loosing traction to ReactJS. The impression that's being formed in the minds of developers that Angular is too slow for large apps due to its direct DOM manipulation.

Are there any plans for Angular to switch to the virtual DOM (or maybe better technology) in the view layer similar to how ReactJS does this? I think this would be a huge win that will minimize the number of developers we may loose to frameworks like React. Please share your vision, so I can share it with the SoCal Angularians.

Thank you.

**Comment by TommyM** [comment]
I am not an Angular 2 developer but I wanted to give you my experience with building large applications in Angular 1.x so far. 

What I have experienced is that the performance problems with big Angular 1.x applications are not really due to the DOM operations, but rather due to the way that change detection and the bindings are implemented, as well as the inability to disconnect certain parts of the UI from that change detection (resulting in huge digest loops). AFAIK (by reading the design docs as well as having read all the source code in the repo of Angular 2.0) both these problems will be heavily addressed in Angular 2.0.

Now of course there might be some gains to be made by having something like the Virtual DOM of React, but I think these would be very minor and won't result in much better/more performant user experiences.

Of course some developers run into performance problems with Angular 1.3, and are unable to work around them because of their inability to figure out why these performance problems happen, then blame it on the framework (for which in this case they might be right to do so), and then move onto the next shiny framework. I fail to see why this is a problem for the Angular community though. These same developers will run into different performance (or other) problems in these new shiny frameworks sooner or later and be in the same scenario again. Maybe losing these developers is not that much of a loss to the community...

Of course this is just my opinion based on my experience with developers and frameworks for the last ~12 years. I believe that any respectable application developer who really understands how the browser rendering and javascript engines work should be able to make an application performant in any framework.

I am curious to hear what members of the core Angular team answer to your question as having something like a Virtual DOM might actually be a cool thing, especially since all the interaction with the DOM is handled through a facade already. Also if I understand correctly they will have to get the compiler to work on the server without DOM available, which is in some way related to this as well.

**Comment by demisx** [comment]
@TommyM Thank you for sharing your feedback. I think if we explain and show developers how this will be addressed in 2.0, we more likely to retain the talent. Of course, framework chasers will switch anyway, but a big portion of quality developers will have a greater confidence about their investment into Angular.

On a separate note, will one-time bound expressions help you disconnect certain UI parts from the watch array? My understanding this was the intention. Of course, they are only available in 1.3+

**Comment by petebacondarwin** [comment]
@demisx - thank you for asking this question. It is concerns over things like performance and maintainability in large applications that has driven much of the development effort for Angular 2.

@TommyM - thank you for your views on this. They make a lot of sense and as application developers we should find a balance between expecting the framework we are using to provide good performance options and making wise decisions in our own applications to make the most of these options.

Rather than focus on the question of whether Angular 2 will implement feature X from framwork Y, what the team has done is spend a lot of time designing a better system that will be highly performant and maintainable.

A lot of these ideas are going to be expanded upon in the coming months, especially at ng-conf, but you can read about our new approach to change detection in Victor Savkin's excellent blog post: http://victorsavkin.com/post/110170125256/change-detection-in-angular-2.  This describes how the "reactive" structure of Angular 2 apps, combined with intelligent disconnecting of components that do not need to be checked, will give us fantastic performance gains.

Hope that helps.

**Comment by demisx** [comment]
@petebacondarwin Thanks Pete. I will definitely read this later today and broadcast further out. 

As far as DOM manupulations go, do you guys forsee any major changes/improvements in 2.0?  The common complaint I hear is that long web forms and pages with lots of UI elements greatly affect 1.x performance. This is when React/Flux with its Virtual DOM is usually pitched as an alternative. You are right. It's not a question will or not Angular use the Virtual DOM. It's a question of what Angular 2 plans on doing to make the DOM manipulations superior. Thank you.

**Comment by TommyM** [comment]
@petebacondarwin - Thanks for linking to that blog post! I hadn't read that yet.

@demisx - On that separate note, sometimes you want to disconnect things from the watch that aren't necessarily one-time bound. Think of tabs, or complete views in the UI that aren't visible in some UI states. You want to ability to disconnect and reconnect them to speed up change detection. You can do this in Angular 1.3, but it is rather hacky (you can see an example of this in Angular Material implementation of tabs). Victor's blogpost and the source code of the (yet again) completely reimplemented change detection show how this will be solved in Angular 2.0. This combined with a much better implemented change detection in general will result in huge performance wins.

We can even take this a step further and try to get to a point where we only let data flow in one direction. This would result in a scenario where you only have to run digest loops once. This could be done if we for example not use two-way data binding, but rather get data from the ui state through helper methods, like in the new implementation of forms that landed in the angular codebase today.

To get back on-topic. I do believe it is important to retain talent within the community, and this should done by explaining why angular 1.3 is sometimes not performant and how this will be improved/fixed in Angular 2.0.

**Comment by TommyM** [comment]
@demisx - Only saw your response after I wrote my previous. I might be wrong, but in my experience the reason that these long web forms and pages with lots of UI elements greatly affect performance are often not because of DOM manipulations, but due to those pages generally resulting in huge tree's which result in slow change detection. 

Of course you always have to be careful not to create big (relative) DOM structures, since they will result in slower browser layouts when you perform DOM operations on this DOM tree. Usually I work around this by disconnecting parts of the DOM by setting their position to absolute. For example stretch your scrollable content area by using position: absolute; top: 0: right: 0; bottom: 0; left: 0; This will prevent any manipulations to the DOM inside to cause a browser layout for the whole page, thus resulting in much faster manipulations! Shadow/Light DOM will probably also help prevent huge browser layouts (I havent tested this yet though).

Another problem that people often run into is reading and writing multiple times to the DOM within one rendering frame of the browser. Every time you read something from the DOM, all the pending writes have to be applied and then a layout recalculation has to be done. If you do this many times within one frame this will result in your application feeling sluggish. The benefit of something like the Virtual DOM in React is that they will apply DOM changes all at once, thus shielding the developer from having to think about stuff like this. You can however prevent this from happening yourself by doing all the DOM reads first, then apply all the DOM writes. The browser will automatically queue all these writes till the end of the frame, apply them and do one layout recalculation resulting in a much smoother user experience. Of course this usually only applies to people creating custom components or directives and the people writing frameworks and shouldn't be a concern for developers using Angular 1.3 or other frameworks, but it is something to always keep in mind.

In general I believe that it is a responsibility of all application developers to learn about the platform (in our case this is the browser) that we write our applications in. This will help you to write performant applications regardless of the framework you use.

p.s. Sorry for the long rants... I have worked on and with frameworks for a long time now and sometimes it gets tiresome to see developers blame frameworks for their inability to use them properly. I think it is great that you are trying to convince these developers to stay in the community by explaining to them why they run into these problems!

**Comment by demisx** [comment]
@TommyM Yeap, you make a good example of the disconnects and I totally see the value in doing that. Also, thank you for the DOM disconnect tips. Appreciate your time writing this all out. I will make sure to share this with my counterparts. This is great stuff to know.

And thank you @petebacondarwin and everyone who's chiming in. This is great info and will help us to explain better to the community what's being done to address the current shortcomings, why 2.0 is such a major breaking redesign and how great it is going to be. There are so many great Angular developers out there and I want them to continue feel superheroic.

**Comment by mhevery** [comment]
Not actionable

**Comment by acpower7** [comment]
^Can you further explain why this isn't actionable?

**Comment by DzmitryShylovich** [comment]
Angular uses a different strategy. We keep track of the old values for every binding to the view, and so we can detect which pieces of the view changed and update them in the real DOM.
Virtual DOM diffs the view, angular diffs the model.
From a performance standpoint neither approach is strictly better than the other. There are certain scenarios in which either approach has a slight advantage.
