### ISSUE TITLE
Add better way to get signal value without calling it like method

### ISSUE THREAD

**Issue by Lev09** [angular/angular#56190]
### Which @angular/* package(s) are relevant/related to the feature request?

core

### Description

Calling a signal like a method breaks widely used coding/naming conventions and makes it harder to distinguish from a regular method.

### Proposed solution

My suggestion is to add a `.get()` method to signals, as we already have `.set()` method I think it will be convenient.

### Alternatives considered

As an alternative we could have `.value` getter and setter.

**Comment by pkozlowski-opensource** [comment]
As mentioned in my [previous comment](https://github.com/angular/angular/issues/56190#issuecomment-2141388720) the API shape of the signal read was discussed extensively in the past. Since then there was no additional information / insight that would change the equation. 

Moreover the alternative proposed here is more verbose as compared to the original API. 

We do appreciate the suggestion but going to keep the existing API as-is for now - until new information surfaces.
