### ISSUE TITLE
Hello World Project is not Downloading from website.  

### ISSUE THREAD

**Issue by AbulBashar38** [angular/angular#56404]
### Which @angular/* package(s) are the source of the bug?

Don't known / other

### Is this a regression?

Yes

### Description

I am Learning angular and when i open angular docs and then i try to download Hello World project. But it was not download. then i check the console of my browser and found error.
setImmediate is not defined
![Uploading Screenshot 2024-06-12 at 6.29.06 PM.png…]()

### Please provide a link to a minimal reproduction of the bug

Image link: https://drive.google.com/file/d/1Q8_cpPOkGE_A1ZI7GFhCzS3ckTt2FMxF/view?usp=sharing

**Comment by mvdluit** [comment]
@AbulBashar38 Not sure if you were already able to follow the tutorial, but you can follow these steps to create a project similar to what's used in the tutorial while the download is not working.

In your terminal, run `npx @angular/cli@latest new first-app --inline-template --skip-tests --no-ssr --style css` (feel free to change `first-app` to a name you want to give it). This will generate a project in a folder with the name you picked and with the same setup as the tutorial: single page application with inline template, css styles and no tests.
Once this command finishes,  you can open the project in your editor and go to `src/app/app.component.ts` and change the code in the `template` to match that in the first step of the tutorial and you will be set to go.

**Comment by forestfish12** [comment]
Same issue still exists. Attempted using Chrome and Firefox on Fedora Linux. Also attempted on windows 11 Firefox. getting the same `setImmediate` error. 
![image](https://github.com/angular/angular/assets/59574979/2eb981a9-f7f5-44dd-9145-bc1454451901)

**Comment by jdegand** [comment]
`setImmediate` is deprecated.  [Stack Overflow](https://stackoverflow.com/questions/74195710/what-is-the-setimmediate-equivalent-that-is-supported-by-browsers) for alternatives.

**Comment by mvdluit** [comment]
Thank you for the PR to fix this @JeanMeche. I came back to this issue because we had a couple of people asking about the download on discord today. 

In addition to fixing the .zip download, would it make sense to also show people how they can create the project themselves through the CLI? The "First App" tutorial already assumes NPM is installed, so instead of people always having to rely on the download to start coding along, offering them some instructions on how to generate the project makes sense IMO.

`npx @angular/cli@latest new ng-tutorial --inline-template --skip-tests --no-ssr --style css` basically gives you the exact same project setup, with exception of some minor changes to the `AppComponent` template.

**Comment by JeanMeche** [comment]
Ben just opened #56816 to add an instalation guide. Should we maybe link to this new page ?

**Comment by mvdluit** [comment]
> @bencodezen just opened #56816 to add an instalation guide. Should we maybe link to this new page ?

Just quickly looked at the PR. I think it's good to link to it for general information on creating a new project through the CLI, but it will not show how to generate the exact same project as is seen in the tutorial (e.g. inline templates, no tests, no ssr, css styles). For beginners it's important that what's generated is exactly the same as what is shown.
