### ISSUE TITLE
docs(Observable): document how to compose operators

### ISSUE THREAD

**Issue by thelgevold** [angular/angular#5642]
After upgrading to alpha.48 I noticed that the http module no longer can stand on its own...
According to the examples we now have to import ```rxjs/operators/map``` to even get access to the essential map() method.

I am wondering, isn't this a bit clunky and unnecessary? Why reveal the dependency on rx.js like this?
Shouldn't this be abstracted from us? Seems like we also have to include rxjs separately in addition to Angular 2??

If rx is this visible in Angular 2.0, why provide map() etc via the http module at all? Can't you just use rx.js directly?

P.S. This is not listed as a breaking change in the change log :-)

**Comment by deeleman** [comment]
+1

**Comment by SebastianStehle** [comment]
I also have the problem that I cannot find the operators folder in the rxjs package (it is named "operator") and therefore browserify fails:

"Error: module "rxjs/operators/toPromise" not found from "node_modules\angular2\src\facade\async.js"

Perhaps it is an similar issue.

**Comment by PascalPrecht** [comment]
This change was part of reducing the file size of the overall default rx
dependency.

**Comment by rolandjitsu** [comment]
Also, to import `import 'rxjs/operators/map';` we need extra SystemJS config as well, so maybe this is not the best idea. On top of that, IDEs like VSC will also complain of that import not existing, and the TS compiler as well (if using `moduleResolution` as `node`).

**Comment by kylecordes** [comment]
@thelgevold Under what circumstances do you actually need to ```import rxjs/operators/map```? I have various codes sitting here, running on Alpha 48, using http("something").map(fn), and while that module does get bundled or loaded, I never need to do so explicitly. Both the runtime (systemjs) and development tools (vscode) have no problem letting me call map.

@PascalPrecht I was actually wondering about this exact point over one the work was going on to reduce that Rx dependency. That works successfully reduced the hard, compile time dependency. But I don't think it made nearly as much impact in the actual semantic dependency; I think most nontrivial Annular 2 programs will end up using (bundling/shipping) a decent swath of Rx library code, regardless of whether Angular 2 itself directly encodes such a dependency.

**Comment by thelgevold** [comment]
My understanding of this is that the now have to load operators like map separately for them to be added to the observable returned by http.get(''). 

@PascalPrecht: 
Sounds like a good idea to reduce the bundle size, but aren't we just adding back the same bytes when the rx module is added at run time? Is it part of a lazy loading strategy for the bootstrapping? Http seems so fundamental to most apps though, so does it even make sense to lazy load it as most apps would probably need it right away anyway.

**Comment by thelgevold** [comment]
Based on what I am reading on Gitter and other places this approach seems to still be in flux, so I think I will sit alpha.48 out and wait for a solution in alpha.49.

**Comment by kylecordes** [comment]
I agree about waiting for Alpha 49, but the following might be useful for anyone else who comes along and reads this issue. Here is the resolution to the difference above, or I had pointed out that I could use http.get().map() without any extra import, while the import seems to be necessary to make map available in that prototype. The behavior I pointed out is what happens when you use the systemJS bundles that ship with Angular 2 in its NPM package. That package includes/loads map somewhere, landing it on the prototype, making it work. But if instead you are using Angular 2 without that bundle (regardless of whether you're doing so using JSPM/System JS or webpack) then you observe the need to explicitly load map. I think many people coming into this development space will find that behavior surprising.

**Comment by jeffbcross** [comment]
@thelgevold 
> I am wondering, isn't this a bit clunky and unnecessary?

A bit clunky, yeah. We're working on ways to make it less clunky to add common operators while still maintaining a minimal core. We also need to better document where we ended up on the implementation. The background of why we've been moving to a bare `Observable` in Angular is two-fold. 

 1. Modularity was a goal of the new RxJS project from the start, and it wasn't until recently that we started really getting serious about composing operators instead of relying on tiered distributions of Rx. With the current state of the JS language, without nice features like [function bind](https://github.com/zenparsing/es-function-bind), there isn't an elegant way of importing operators ad-hoc and using them in a left-to-right fashion. (i.e. `source::map(fn)` with function binding vs `map.call(map.call(source, projection1), projection2);`. This function binding syntax sugar is already possible to use with Babel, and will hopefully come soon in TypeScript (they are waiting on TC39 consensus).
 2. We want the Angular core API surface to be as tiny as possible, so that byte-sensitive applications can make choices about what optional dependencies they want to bring in. We have no idea what proportion of applications will use the features of Rx, or will just use it as a simple async delivery mechanism. In the absence of smart dead code removal tools, we have to err on the "minimal" side.

We worked with the TypeScript team to determine our current solution, which is to create modules in RxJS that, when imported, automatically patch an operator onto the `Observable` prototype. In future versions of TypeScript, there will be support for re-opening types using this approach, which would then show the imported operators as available methods wherever the `Observable` is used.

> Why reveal the dependency on rx.js like this?

We don't have a goal of hiding the dependency on Rx. That would require a lot of duplication of effort in terms of documentation and support.

> P.S. This is not listed as a breaking change in the change log :-)

@robwormald is fixing that. It seems our script didn't pick up the change because it was a `refactor` commit. I opened https://github.com/angular/angular/issues/5672 to track.

> If rx is this visible in Angular 2.0, why provide map() etc via the http module at all? Can't you just use rx.js directly?

The `Http` module produces `Observable`s, so it has a dependency on `rxjs`. There's no reason not to use rxjs directly in apps. In fact, it is being declared as a peer dependency in #5649 to ensure that angular and applications will use the same version of `rxjs`.

@rolandjitsu 
> On top of that, IDEs like VSC will also complain of that import not existing, and the TS compiler as well (if using moduleResolution as node).

This issue will go away when `rxjs` is a `peerDependency`, right?

I'm going to work on better API docs for `Observable` now that we're closing in on how to compose.

**Comment by robwormald** [comment]
@thelgevold just to answer the "but aren't we just adding back the same bytes when the rx module is added at run time?" question - no - and that's the real goal here. This strategy allows you to import *only* the operators you're using, without bringing in the full ~250kb that all of Rx includes.

**Comment by thelgevold** [comment]
@robwormald I think that makes sense, but my point is that lazy loading may hit a point of diminishing returns for very commonly used parts. One example: Will there ever be a case where someone would make an http call and not make use of map()?

**Comment by thelgevold** [comment]
Thanks @jeffbcross/ @robwormald for taking the time to address this and write down a detailed explanation :-)

**Comment by IgorMinar** [comment]
+1 to all the @jeffbcross said.

We are currently erring on the conservative side. It's easier to ask developers to be slightly more explicit, and remove that requirement in the future if deemed unnecessary. It will be almost impossible to do the opposite once more code is written.

I also believe that with function bind, importing operators in each file will be the right way to deal with this. Until then we will try to use semi-great workarounds.

**Comment by thelgevold** [comment]
Yeah, it's probably a good approach all things considered. Currently I just import these extra operators once in my root module, which hides the pain from all downstream components.
