### ISSUE TITLE
Page scrolls always in the same link

### ISSUE THREAD

**Issue by bampakoa** [angular/angular#56446]
### Describe the problem that you experienced

When I try to navigate to any link inside a page, it always scrolls to the link which is the one before the last link. For example:

- https://angular.dev/guide/forms/template-driven-forms#submit-the-form-with-ngsubmit redirects to the **Summary**.
- https://angular.dev/guide/directives#listing-items-with-ngfor redirects to the **Using NgSwitch**.

**Comment by ViktorTyultinov** [comment]
From what I checked the issue comes from the fact that initially the redirection pushes you towards: 

https://angular.dev/guide/forms/template-driven-forms/#submit-the-form-with-ngsubmit

instead of 

https://angular.dev/guide/forms/template-driven-forms#submit-the-form-with-ngsubmit

This happens on refresh or when you enter the URL for the first time.

The `/#submit-the-form-with-ngsubmit` is not found and this is why we have the strange behavior but I don't know how to remove this `/` from the redirection. If anyone has a clue I would be happy to fix this and put it on PR
