### ISSUE TITLE
change preposition in ng-for expression to 'in'

### ISSUE THREAD

**Issue by trinarytree** [angular/angular#5659]
'In' is the standard english preposition when you are trying to describe the relationship between an object and a container, not 'of'.  Every other programming language I can think of uses 'in':

java: `for (String x : y)`
This is the for-each syntax.  Look at the language Oracle uses - 3rd paragraph: https://docs.oracle.com/javase/1.5.0/docs/guide/language/foreach.html
":" is pronounced "in".

python: `for x in y`

javascript: `for x in y`

angular 2: `*ng-for="#x of y"`  wtf??

Please change it to 'in' before the malediction spreads.

**Comment by dsebastien** [comment]
ES2015 has introduced the for..of statement. Take a look at these to see the difference:
* https://developer.mozilla.org/en/docs/Web/JavaScript/Reference/Statements/for...of
* https://developer.mozilla.org/en/docs/Web/JavaScript/Reference/Statements/for...of

Given that Angular iterates over the values of the collections, for..of is actually the good choice here.

The malediction is more linked to the fact that one cannot rewrite history and repurpose for..in statement in JavaScript to make it loop over values rather than keys.. =)

**Comment by robwormald** [comment]
what @dsebastien said.

tl:dr;
```javascript
var foos = ['a','b', 'c'];

for(var foo of foos){
  console.log(foo);
}
//a
//b
//c

for(var foo in foos){
  console.log(foo);
}
//0
//1
//2
```

see also discussion in https://github.com/angular/angular/issues/909

**Comment by trinarytree** [comment]
i see.  thanks for the pointers.  i guess this is a bowing down to javascript then.
using dart + angular (not js), i will probably wind up committing the error several times / day.  :-(
