### ISSUE TITLE
Type 'Observable<any[]>' is not assignable to type 'any[]'.

### ISSUE THREAD

**Issue by karthigamahe** [angular/angular#56821]
### Which @angular/* package(s) are the source of the bug?

core

### Is this a regression?

Yes

### Description

on angular 16 rowdata declared as observable showing error

this is how i declared rowData

`  rowData = new Observable<any[]>();
`

### Please provide the exception or error you saw

```true
error TS2322: Type 'Observable<any[]>' is not assignable to type 'any[]'.

56     <ag-grid-angular id="ga_Grid" style="width: 100%;height:100%" class="ag-theme-alpine" [rowData]="rowData"
```

### Please provide the environment you discovered this bug in (run `ng version`)

```true
Angular cli- 16.2.12
```

**Comment by JoostK** [comment]
Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).

---

It appears that you'll have to use the `async` pipe when binding to the `[rowData]` input of `ag-grid-angular`, to subscribe to the `Observable` and write the resulting data into the input, instead of the `Observable` itself.
