### ISSUE TITLE
Feat: HttpClient based on Signal instead of Observable

### ISSUE THREAD

**Issue by cesco69** [angular/angular#56823]
With Signal I can build an application without use anymore RxJS. But, if I use HttpClient, I still import RxJS because it is based on Observable. For **optimize tree shaking and final bundle size**, I think it is a good idea provide an alternative HttpClient based on Signal.

### Proposed solution

From observable
```ts
@Component({
  template: `
    <ng-container *ngIf="user$ | async as user">
      <p>Name: {{ user.name }}</p>
      <p>Biography: {{ user.biography }}</p>
    </ng-container>
  `,
})
export class UserProfileComponent {
  @Input() userId!: string;
  user$!: Observable<User>;
  constructor(private http: HttpClient) {}
  ngOnInit(): void {
    this.user$ = this.http.get<User>(`/api/user/${this.userId}`);
  }
}
```

to Signal

```ts
@Component({
  template: `
    <ng-container *ngIf="user">
      <p>Name: {{ user().name }}</p>
      <p>Biography: {{ user().biography }}</p>
    </ng-container>
  `,
})
export class UserProfileComponent {
  @Input() userId!: string;
  user!: Signal<User>;
  constructor(private http: HttpClientSignal) {}
  ngOnInit(): void {
    this.user = this.http.get<User>(`/api/user/${this.userId}`);
  }
}
```

**Comment by JeanMeche** [comment]
Hi, 
You're mentionning 2 issues here: 

* Reducing the dependency to RxJS, this is a long term topic that the team is looking to address: providing APIs that don't rely by default on RxJS and provide the right interop apis via the `rxjs-interop` package. 
* Having a pattern around signals and data loading. The way we see it, is that the HttpClient is a async APIs that isn't well suited directly for a usage with signals. Instead the team is looking to provide new patterns that will allow you to load data and assign them to signals while also addessing several concerns (loading state, writability of signals, integration into the Http stack, testing etc). 

That being said, this issue is not addressable directly so I'll close it but be ensured that the Angular team is aware of those concerns and plans to provide new possibilities around them.
