### ISSUE TITLE
Signal update not registered when called inside async function

### ISSUE THREAD

**Issue by muuvmuuv** [angular/angular#57219]
### Which @angular/* package(s) are the source of the bug?

core

### Is this a regression?

Yes

### Description

When trying to update a signal value after an API request that is triggered by a template button click the dependents does not get the update.

### Please provide a link to a minimal reproduction of the bug

https://stackblitz.com/edit/stackblitz-starters-4fewka?file=src%2Fmain.ts

### Please provide the exception or error you saw

```true
None
```

### Anything else?

Using `.set()` to reset it works but information gets lost.

**Comment by JoostK** [comment]
The async part is irrelevant here; your update callback returns the exact same array reference, so the signal doesn't consider itself to have changed. This can be achieved using a custom equality function that may be passed as option when creating the signal.

**Comment by JoostK** [comment]
In this particular case the component is not within an `OnPush` boundary, so it will always be updated when a change detection round is initiated regardless of any change notification from the signal (which doesn't fire). The listener event automatically schedules change detection for you.

Normally, microticks (i.e. Promises or await points) also initiate change detection but that is not the case here, due to angular/angular-cli#27486 that takes effect. The result is an application bundle where native async/await syntax is being used, which is untrackable by zone.js. Moving the `import 'zone.js'` into `angular.json` as `"polyfills": ["zone.js"]` switches back to the "old" behavior where async/await is downleveled to generator functions that use the `Promise` constructor, which can be patched by zone.js.

**Comment by muuvmuuv** [comment]
Ok I understand, makes sense. Also tried using OnPush and exp. zoneless just to test but this does not fire either.

Only way was using custom equal function.. is this something that can be considered? Arrays are special I know but it could be a simple Array.isArray(a) check here: https://github.com/angular/angular/blob/main/packages/core/primitives/signals/src/equality.ts

```ts
  isEqual(a:unknown,b:unknown): boolean {
    if (Array.isArray(a) && Array.isArray(b)){
      return a.length !== b.length
    }
    return Object.is(a, b)
  }
```

**Comment by JoostK** [comment]
We don't have any intention to extend the default equality function, no. It is generally insufficient to account for any array updates; internal changes to items won't be notified as change, nor will replacing an item with a new one be considered because the array's length would end up the same. The mental model of `Object.is` equality is easy to explain and reason about.

**Comment by muuvmuuv** [comment]
Ok, understand. Just thought that this would make adding/removing a bit better but true, changing an inner array entry would still not be reqognised. Maybe something to add to the docs so others will know that for arrays it needs a custom equality function with an example for length as I described above?
