### ISSUE TITLE
ng-repeat elements flickering issue with animations onload

### ISSUE THREAD

**Issue by susisumesh** [angular/angular#5744]
Dealing with a flickering issue on dom elements animation.

I am loading a list of nested html elements in ng-repeat. On pageload event hiding few elements from the list using css3 animation hide. those elements gets hided on page load.. but a flickering shows up.

.hide{
  -webkit-animation-name: hide 0.01s;
  animation-name: hide 0.01s; 
-webkit-transform-style: preserve-3d;
-webkit-backface-visibility: hidden;
 -webkit-transform: translate3d(0,0,0);
 
}

Is this due to ng-repeat rendering model or animation transition issue?

**Comment by pkozlowski-opensource** [comment]
> Is this due to ng-repeat rendering model or animation transition issue?

Hard to say, since there are definitively not enough details to reproduce. See our bug submission guidelines:  https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-submitting-an-issue

Having said this it _sounds_ like you are using Angular 1 and this repo is for Angular2. Angular 1 resides in https://github.com/angular/angular.js but _please_ go over submission guidelines before opening issues in there.
