### ISSUE TITLE
style binding syntax stopped working in newer Angular versions

### ISSUE THREAD

**Issue by simon-boskovic** [angular/angular#57864]
### Which @angular/* package(s) are the source of the bug?

common, core

### Is this a regression?

Yes

### Description

In previous versions of Angular, the following syntax for binding to the style attribute worked as expected:

`<div [style.padding-top.%]="isActive && size"></div>`

This worked fine when isActive was true, but in newer versions, if isActive is set back to false, the size value continues to be applied to the style, and the padding does not disappear as expected.

To make it work as intended, we now have to use a more explicit ternary operator:

`<div [style.padding-top.%]="isActive ? size : 0"></div>`

This change in behavior differs from previous versions, where simple logical expressions were sufficient. Could you please clarify if this is an intentional update or a potential bug?

### Please provide a link to a minimal reproduction of the bug

https://stackblitz.com/~/github.com/simon-boskovic/angular-style-binding?file=src/app/app.component.html

### Please provide the environment you discovered this bug in (run `ng version`)

```true
"dependencies": {
    "@angular/animations": "^18.0.0",
    "@angular/common": "^18.0.0",
    "@angular/compiler": "^18.0.0",
    "@angular/core": "^18.0.0",
    "@angular/forms": "^18.0.0",
    "@angular/platform-browser": "^18.0.0",
    "@angular/platform-browser-dynamic": "^18.0.0",
    "@angular/router": "^18.0.0",
    "rxjs": "~7.8.0",
    "tslib": "^2.3.0",
    "zone.js": "~0.14.3"
  }
```

**Comment by JoostK** [comment]
In which version did this work according to your expectations?

**Comment by simon-boskovic** [comment]
17.3

**Comment by JeanMeche** [comment]
I couldn't make it work in v17 neither.

**Comment by simon-boskovic** [comment]
I’ve figured out why it wasn’t working. In our case, we always re-render our components, so the initial value is set correctly when it first loads. However, it should still work properly when switching the value between true and false. Ideally, the style should update dynamically without requiring a full re-render, so it seems like there’s still an issue with how Angular handles these changes.

**Comment by garrettld** [comment]
I thought maybe this had regressed when style sanitization was removed, but it doesn't work in v9, either: https://stackblitz.com/edit/angular-9-starter-cxikit

What's happening is that the style binding ends up calling `element.style.setProperty('padding-top', 'falsepx')` or `element.style.setProperty('padding-top', '100px')`. Angular just stringifies the value and appends the suffix unless the value is null or undefined ([ref](https://github.com/angular/angular/blob/main/packages/core/src/render3/instructions/styling.ts#L964-L986)), which is why we get the string "falsepx" when the expression evaluates to false.

The browser ignores the invalid "falsepx" value, so once the expression evaluates to "100px" the first time, it just stays that way. This explains why deleting and re-rendering the entire element works as expected.

**Comment by pkozlowski-opensource** [comment]
I was _just_ about to post a _very_ similar comment to the one [shared](https://github.com/angular/angular/issues/57864#issuecomment-2358600367) by @garrettld (thnx for this!).

Once can check it by doing the following in the console of a browser of choice:

```
div = document.createElement('div');
div.style.paddingTop = '5px';
div.style.paddingTop = 'falsepx';
div.style.paddingTop // evaluates to '5px'
```

I don't think there was any change of behaviour on the Angular side - if anything changed it must have been a browser version. I'm going to close this one as there is nothing actionable for us here.
