### ISSUE TITLE
viewChild.required() is lying about its type - please remove this API while it's still in developer preview!

### ISSUE THREAD

**Issue by NicBright** [angular/angular#57879]
### Which @angular/* package(s) are the source of the bug?

core

### Is this a regression?

Yes

### Description

I was both shocked and amused about how `viewChild.required()` handles the case when it's accessed too early.

An exception is thrown, pointing to https://angular.dev/errors/NG0951

While that's better than nothing, I still have to ask: why does `viewChild.required()` lie about its type? It's nice to try to guarantee that it can't be null (or undefined). But in fact, you just can't guarantee that: **so please remove `viewChild.required()`** as it tricks developers into falsely thinking that the ViewChild is there and accessible while in fact it's not (and it can't be guaranteed). There's still time to do so because `viewChild.required()` is still in developer preview!

After all, the TypeScript type should reflect the reality and not something along the lines "it's not correct now, but will be in the future when the necessary lifecycle has finished". 

So please: consider removing `viewChild.required()`. It's much better to be honest about the type and let the developers use optional chaining. Because of the Signal based nature I suppose everybody can live with an initial `null` (or `undefined`) value and wait a little bit until the viewChild arrives. Especially because this is how `@ViewChild()` works and everybody was fine with it. It's far better to expect the `undefined` (or `null` value) than to spam NG0951 exceptions into the application.

**Comment by alxhub** [comment]
From a pure TypeScript perspective, the type of `viewChild.required` (or `input.required`, etc) is not a lie - it does in fact guarantee that accessing the value will never return `undefined`. The fact that a function might throw an exception is not a part of its type signature.

Think of it this way: what should code do when accessing a query result where you need its value? Safe navigation is one option:
```ts
element()?.focus();
```
That works, but silently ignores the case where you accidentally perform this operation when the value isn't available. It also doesn't work well in situations where you're unconditionally using the result:
```ts
doSomething(element()?.value); // might not accept undefined
```
Another option is to non-null assert:
```ts
doSomething(element()!.value);
```
This will error in the case of a logic bug, but the error is likely going to be "cannot read property value of undefined" which is not the most useful for debugging. An even better option is to actually assert the value is defined:
```ts
assertIsDefined(element); // narrows element to `Signal<T>`, removing undefined
doSomething(element().value); // now safe to access
```
Now you don't have to non-null assert or safe navigate _and_ you get a clear error message if the precondition of the result being available turns out to be incorrect.

`viewChild.required` is this exact pattern - a built-in assertion that the query result is available when you go to access it. It's a safer form of non-null assertion, because it generates a clear error message when the result isn't available.

**Comment by diesieben07** [comment]
@NicBright Your argument could equally be applied to _any_ function/method that throws any kind of exception. You are arguing this should never be done, because it cannot be caught by the compiler, instead the function should have an optional return type, so that users of the function have to handle that case. I don't think this is a helpful programming pattern. It also reminds me of Java's checked exceptions, whose goal it is to force developers _at compile time_ to handle the problems that can occur. It is wildly understood that this was a bad decision and modern languages (even on the JVM, see Kotlin) do not follow this pattern for this very reason.
I don't think it is a good idea to bring this pattern to TypeScript and/or Angular.

`viewChild.required` exists for the case where you _know_ that the element exists. If you use the API correctly it will not throw exceptions. If you use it wrong (i.e. you access view queries before results are ready or you use `viewChild.required` for optional elements) the API will throw an exception. This is true for any properly designed API: When it is used wrong, it will throw an exception.

**Comment by alxhub** [comment]
I don't think there's much more to be said here. You mention that a non-null assertion is in your opinion the correct approach when you _know_ a query result is available. That's all `.required` is - a non-null assertion with a better error message. You're promising "this result won't be `undefined` when I read it".

We discussed this at our team sync and decided that `viewChild.required()` is behaving as we intend, and we're satisfied with the DX in comparison to always returning `undefined`. One person noted they'd observed a real bug in an applications where a developer wrote `someElement?.focus()` but the code ran before the element was available, making the attempt at focusing a silent failure/no-op. We see `.required()` as a clear improvement over this behavior.

Given this decision to keep the API, I'll go ahead and close this issue, but feel free to continue discussion - we value the feedback!
