### ISSUE TITLE
more time click,more time cost

### ISSUE THREAD

**Issue by wxyer** [angular/angular#57968]
### Which @angular/* package(s) are the source of the bug?

zone.js

### Is this a regression?

Yes

### Description

![屏幕截图 2024-09-26 150555](https://github.com/user-attachments/assets/baaf7440-1fac-407f-a6fd-19f443dcc1e3)
i pop a modal by using cdk in code,
![屏幕截图 2024-09-26 151604](https://github.com/user-attachments/assets/fc920426-907d-46b8-8de2-47f07e41928d)

popup code below
`
![屏幕截图 2024-09-26 151712](https://github.com/user-attachments/assets/b71b6a46-da4d-43d2-9ed1-bd9956c9014e)
`

### Please provide the exception or error you saw

```true
the funcion calling costs so much times, and with more time i popup the modal,more time needed,
```

### Please provide the environment you discovered this bug in (run `ng version`)

```true
Angular CLI: 18.2.0
Node: 20.9.0
Package Manager: pnpm 8.10.5
OS: win32 x64

Angular: 18.2.0
... animations, cli, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1802.0 (cli-only)
@angular-devkit/build-angular   18.2.0
@angular-devkit/core            18.2.0 (cli-only)
@angular-devkit/schematics      18.2.0 (cli-only)
@angular/cdk                    18.1.2
@angular/localize               18.1.2
@angular/material               18.1.2
@schematics/angular             18.2.0 (cli-only)
rxjs                            7.8.1
typescript                      5.5.4
zone.js                         0.14.10
```

**Comment by JoostK** [comment]
You should detach previously attached portals to clean them up, otherwise you're accumulating multiple portals that have likely gone unused.

---

Hello, we reviewed this issue and determined that it doesn't fall into the bug report or feature request category. This issue tracker is not suitable for support requests, please repost your issue on [StackOverflow](http://stackoverflow.com/) using tag `angular`.

If you are wondering why we don't resolve support issues via the issue tracker, please [check out this explanation](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem).
