### ISSUE TITLE
 error NG4005: Angular compiler option "extendedDiagnostics.checks" has an unknown check: "interpolatedSignalNotInvoked"

### ISSUE THREAD

**Issue by splincode** [angular/angular#58007]
### Which @angular/* package(s) are the source of the bug?

compiler-cli, compiler

### Is this a regression?

No

### Description

I have default tsconfig between many projects

https://github.com/taiga-family/configurations/blob/main/projects/tsconfig/tsconfig.json#L24

But when I want add `interpolatedSignalNotInvoked` and other new checks then I have problem in project which using Angular 16

<img width="1271" alt="image" src="https://github.com/user-attachments/assets/e7ea9bc2-6667-4d81-abe8-b68e42efd0c5">

why angular compiler can't just ignore these properties for older versions of angular projects?

**Comment by faresbouzayen** [comment]
Hi @splincode! 👋

Thanks for bringing this issue to our attention. It seems like you're trying to use the interpolatedSignalNotInvoked check, but it's causing problems in your Angular 16 project.

Here are a few steps you might consider to resolve this issue:

Check Angular Version Compatibility: Ensure that the interpolatedSignalNotInvoked check is supported in Angular 16. If this feature was introduced in a later version, that might be the root cause of the error.

Update Dependencies: Make sure all your Angular packages are updated to the latest version compatible with Angular 16. Sometimes, mismatches in package versions can lead to unexpected errors.

Review Your tsconfig.json: Double-check the configuration in your tsconfig.json. You can try removing the interpolatedSignalNotInvoked check temporarily to see if the project compiles without it, and then reintroduce it if needed.

Look for Documentation Updates: Check the official Angular documentation or changelog for any notes regarding new checks or configurations that might affect your setup.

**Comment by JeanMeche** [comment]
The `interpolatedSignalNotInvoked` extended diagnostic was introduced in v17. This is expected to throw in prior versions.

**Comment by splincode** [comment]
@JeanMeche I understand that was introduced in v17. But I use one sharable tsconfig file between many project. I want reuse between any angular v15, v16, v17+ projects without error. Why can't I just ignore the lack of errors?

```json5
        "extendedDiagnostics": {
            "defaultCategory": "error",
            "ignoreUnknownChecks": true, // <- here
            "checks": {
                "optionalChainNotNullable": "error",
                "nullishCoalescingNotNullable": "error",
                "missingControlFlowDirective": "error",
                "textAttributeNotBinding": "error",
                "missingNgForOfLet": "error",
                "invalidBananaInBox": "error",
                "suffixNotSupported": "error"
            }
        }
```

**Comment by JoostK** [comment]
There's a trade-off here; silently ignoring unknown properties is undesirable in terms of the potential for typos or other misconfigurations, versus being maximally compatible usable across multiple projects with different versions. Reusing tsconfigs across projects is not something we optimize for, and there's potential forward compatibility concerns that complicate such approach. If you want to use a tsconfig across projects you'd have to ensure to use the common denominator of versions, which is typically the oldest version you intend to support.

**Comment by JeanMeche** [comment]
It's also worth mentionning that you can extend that common tsconfig in each app to address their specificity.
