### ISSUE TITLE
Could you accept both camelCase and dash-case in HTML?

### ISSUE THREAD

**Issue by tak-onda** [angular/angular#5812]
> case-sensitive camelCase templates (kebab-case removal)

This breaking change introduced in alpha-52 has big impact, could you accept both style, new camelCase and old kebab-case (dash-case)? 

jQuery converts kebab-case style data-* attributes to camelCase names automatically in [`data`](http://api.jquery.com/data/) method, most people are familiar with the same converting name behavior.

Or if it's difficult to change behavior, please tell me the reason why this change is introduced.
I read these documentations, but I can't find why kebab-case is bad.

* https://github.com/angular/angular/blob/master/CHANGELOG.md
* https://github.com/angular/angular/blob/master/modules/angular2/docs/migration/kebab-case.md
* https://github.com/angular/angular/issues/4923

Of course I know Angular 2 is in alpha stage and breaking changes are inevitable, but I'd like to know in which case previous kebab-case (dash-case) causes any problems.

Sorry for bothering you.
I'm a big fan of Angular 2, creating Angular 2 application is very fun for me.
I'm creating Angular 2 application and it's planed to release next month, January.

Regards,

**Comment by wesleycho** [comment]
I dislike this change greatly, and we have some misgivings about it on the ng-bootstrap team.

Stuff like `selector` in the directive and component decorators now move farther away from the expectation that users generally have from the DOM API from HTML being case insensitive (minus SVG), as well as CSS. the querying API (i.e. `querySelector`, `querySelectorAll`) also does not recognize that syntax, which adds to confusion.

This breaks user understanding that they can draw from with standard APIs provided by the browser to developers, and creates a strange hybrid state. Little decisions like this have a big overall impact to the overhead of working in the Angular ecosystem, and IMO this is one that moves away from simplicity for little reason.

**Comment by ericmdantas** [comment]
Pretty much what @wesleycho said.

**Comment by wesleycho** [comment]
So I talked with @pkozlowski-opensource about this, and I am ok with this change, but I think this might require some detailed explanation, or a link (or links) to the reasons for it.

Can't say I love the situation though.

**Comment by thelgevold** [comment]
I actually like the new syntax better, but I guess that is subjective...
It seems worse than it really is. I just upgraded my sample project, which is of decent size now, and a few global search and replaces was all it took :-)

**Comment by vicb** [comment]
> Of course I know Angular 2 is in alpha stage and breaking changes are inevitable, but I'd like to know in which case previous kebab-case (dash-case) causes any problems.

Before the change `dash-case` attribute names were implicitly converted to camelCase. 

One problem with the implicit conversion is when listening to event: `(some-event)="action()"` would bind to the `someEvent` event. Meaning there is no way to listen to the "some-event" event - remember that in JS your can name your custom events whatever you want.

When it comes to property bindings, a few have tried `[someProp]="exp"` and spend quite some time before realizing that they should actually write `[some-prop]="exp"` (that was before the change). Because case sensitivity had been introduced for event bindings it makes sense to use it here as well.

Now because property bindings are case sensitive `[ngif]="exp"` would not bind to the `ngIf` input (notice the lower case "i" in the former). But as you can have a `@Directive({selector: '[ngIf]'})` on this element it would be weird to trigger the directive whatever the name casing while the input binding would be sensitive to the name casing. This is why we made the selector also case sensitive. 

It took the team quite some discussion before any decision was made. I was really not convinced at first but after having considered the different options I think that we have picked the best one and I now find it quite elegant.

> This breaking change introduced in alpha-52 has big impact, could you accept both style, new camelCase and old kebab-case (dash-case)?

If by "accepting both style" you mean allowing both `ngIf` and `ng-if` to trigger **the same directive**, no this is not possible (see my comments in the previous section).

However nothing prevents you from using dash-case for your own directives/components if that's what you  prefer. You could write a `tak-onda` directive (`<div takOnda></div>` would not trigger it,  `<div tak-onda></div>` would). It would event be possible to come with vintage `ng-if`, `ng-for`, ...

Hope this helps.

**Comment by tak-onda** [comment]
Thank you for explanation.

>  remember that in JS your can name your custom events whatever you want.

In JavaScript we can't use `dash-case` names as identifiers directly, but we can use `dash-case` names via decorator `@Output("dash-case")` or `outputs` property of `@Component`, right? 

> When it comes to property bindings, a few have tried [someProp]="exp" and spend quite some time before realizing that they should actually write [some-prop]="exp" (that was before the change). Because case sensitivity had been introduced for event bindings it makes sense to use it here as well.

I understand why the team introduced case sensitivity. 

One more question please.

Why did you change angular's directives and components selectors to camelCase?
There are many documents and sample codes, or programs using old `dash-case` style name already, including unpublished books.
If selectors were `dash-case`, we need not to change current codes and documents that uses `ng-if`, `ng-model`...

Many people are familiar with previous `dash-case` names like `ng-if`, and `dash-case` names are very popular as id or class attributes of HTML. 

How about keeping selectors of standard components and directives to `dash-case` like `[ng-if]`?

**Comment by vicb** [comment]
> `In JavaScript we can't use dash-case names as identifiers directly, but we can use dash-case names via decorator @Output("dash-case") or outputs property of @Component, right?`

That is true in the context of Angular this is also true outside of Angular where you can do `new Event('what-ever-name)`. 

Would this have been true in the context of angular only, it would have been easy to enforce lower or camel case event names.

> Why did you change angular's directives and components selectors to camelCase?

`<because *it-is="a" [matterOf] CONSISTENCY></because>`

We have considered keeping `ng-if` `ng-if` but it would have lead to mixed formatting as above which is even worse. 

As you mention, it breaks a few things but we think it's the best thing to do for Angular in the long run.

**Comment by tak-onda** [comment]
Thanks you very much for explanation.
