### ISSUE TITLE
Inconsistent recommendation for HostBinding vs host in styleguide and docs

### ISSUE THREAD

**Issue by kaisnb** [angular/angular#58134]
### Describe the problem that you experienced

The Angular docs say ["Always prefer using the host property over @HostBinding and @HostListener. These decorators exist exclusively for backwards compatibility."](https://angular.dev/guide/components/host-elements#the-hostbinding-and-hostlistener-decorators:~:text=Always%20prefer%20using,for%20backwards%20compatibility.) but the Angular style guide says ["Consider preferring the @HostListener and @HostBinding to the host property of the @Directive and @Component decorators."](https://angular.dev/style-guide#style-06-03:~:text=Consider%20preferring%20the,decorators.).

This sounds contradictive to me and I wonder what the official recommendation is.

### Enter the URL of the topic with the problem

https://angular.dev/guide/components/host-elements#the-hostbinding-and-hostlistener-decorators:~:text=Always%20prefer%20using,for%20backwards%20compatibility.

https://angular.dev/style-guide#style-06-03:~:text=Consider%20preferring%20the,decorators.

**Comment by JoostK** [comment]
Please see https://github.com/angular/angular/issues/56170#issuecomment-2138398981. The style guide is being overhauled and will be updated on this.

**Comment by johncrim** [comment]
In the meantime (while we're waiting for the style guide update), can you explain why `host` is preferred over `@HostBinding()` ? 

`host` can include functions, eg signals, which is a pro; but `@HostBinding()` is typesafe and easier to read/understand due to locality.

Also, `@HostBinding()` could just be compiled to a `host` property, couldn't it?
