### ISSUE TITLE
View encapsulation no longer handles `:is()` and `:not()` consistently

### ISSUE THREAD

**Issue by Blackbaud-PaulCrowder** [angular/angular#58153]
### Which @angular/* package(s) are the source of the bug?

compiler

### Is this a regression?

No

### Description

As of [this change](https://github.com/angular/angular/commit/7a6fd427d5ad70ad4c50693f54a6e77bf51eea86) that was released in Angular 18.2.8, inner selectors of `:is()` are now scoped for view encapsulation. This broke a Sass mixin my team wrote that worked regardless of whether view encapsulation was enabled. We added branching logic to our mixin to work around this, but while troubleshooting we noticed that `:not()` still does not scope inner selectors, leading to inconsistencies between the two otherwise very similar pseudo-classes.

This Stackblitz exhibits the [old behavior](https://stackblitz.com/edit/angular-vnauyk-4tulmw?file=src%2Fapp%2Fdemo.component.ts) and this Stackblitz exhibits the [new behavior](https://stackblitz.com/edit/angular-vnauyk-98uu1x?file=src%2Fapp%2Fdemo.component.ts).

My main concern is less about whether the change to `:is()` is appropriate and more about whether `:not()` is going to change at a later date, especially in a patch release which will result in another breaking change for my team.

### Please provide a link to a minimal reproduction of the bug

https://stackblitz.com/edit/angular-vnauyk-98uu1x?file=src%2Fapp%2Fdemo.component.ts

### Please provide the exception or error you saw

N/A

### Please provide the environment you discovered this bug in (run `ng version`)

Angular CLI: 18.2.8
Node: 20.11.1
Package Manager: npm 10.2.4
OS: darwin arm64

Angular: 18.2.8
... animations, cdk, cli, common, compiler, compiler-cli, core
... forms, platform-browser, platform-browser-dynamic, router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1802.8
@angular-devkit/build-angular   18.2.8
@angular-devkit/core            18.2.8
@angular-devkit/schematics      18.2.8
@schematics/angular             18.2.8
rxjs                            7.8.1
typescript                      5.5.4
zone.js                         0.14.10

**Comment by JoostK** [comment]
@GeorgySerga this is interesting, WDYT?

**Comment by GeorgySerga** [comment]
Hello, @JoostK , thank you for tagging me. That is a very good question and example, @Blackbaud-PaulCrowder !

I'll just share my thoughts here, to start a conversation. `:not()` looks similar to `:is()` indeed, but it has a notable difference. `:is(selector[scopingAttr])` and `[scopingAttr]:is(selector)` are both scoped within the component, while `:not(selector[scopingAttr])` and `[scopingAttr]:not(selector)` are not, meaning that `:not(selector[scopingAttr])` would break encapsulation (*select all elements which are not something*), so I don't think `:not` should be scoped the same way. At least without some additional context.

The example of the broken selector is interesting. It could be fixed by proper scoping with `:host`, for example `:is(.theme-red :host *)`. Scoping of `.theme-red` breaks this selector. If I understand correctly though, this is consistent with the current logic, for example in the [spec file](https://github.com/angular/angular/blob/main/packages/compiler/test/shadow_css/shadow_css_spec.ts#L52)  `expect(shim('one two {}', 'contenta')).toEqualCss('one[contenta] two[contenta] {}');` (both selectors are scoped), but if `:host` is introduced its left side isn't scoped ([example](https://github.com/angular/angular/blob/main/packages/compiler/test/shadow_css/host_and_host_context_spec.ts#L98) in the spec and [comment](https://github.com/angular/angular/blob/main/packages/compiler/src/shadow_css.ts#L864) in the implementation). [The comment](https://github.com/angular/angular/blob/9dbe6fc18be700e89f28a023378f4775f3f7c3fe/packages/compiler/src/shadow_css.ts#L771) before my change announced the same behavior.

The reasons I decided to scope `:is()` are:
- MDN's article [hints](https://developer.mozilla.org/en-US/docs/Web/CSS/:is#difference_between_is_and_where) at the difference between `:where` and `:is`, bringing up specificity of the outcome, suggesting that otherwise those are the same;
- If `:is` receives `:host` element alongside other selectors, then scoping it with would lead to a selector which matches nothing, for example `:is(.red-theme .foo, :host)` scoped centrally (outside of `:is`), would produce `[_ngcontent]:is(.red-theme .foo, [_ng-host])` and `[_ngcontent][_ng-host]` doesn't exist. But this whole selector can't be unscoped, otherwise `.red-theme .foo` would spill out, breaking encapsulation.

In general, if I'd try to define the difference between `:is()|:where()` and `:not()` (or `:has()` for that matetr), I'd say that selectors within the former match the element to select explicitly, while latter accepts selectors relative to the element to be selected. That's why those need to be scoped outside, otherwise encapsulation might be broken.

Thanks again, let me know if that makes sense or I'm missing anything!

**Comment by Blackbaud-PaulCrowder** [comment]
@GeorgySerga I appreciate the thorough explanation. I understand the distinction, and it sounds like we can move forward with the change to `:is()` with confidence now. Thanks!
