### ISSUE TITLE
alpha.52 seems not te be working on IE11 and IE10

### ISSUE THREAD

**Issue by kampdomoj** [angular/angular#5824]
I have a simple angular2 app that works with Chrome and Firefox, but not with Internet Explorer.
Please check if I am missing something.

url to the app: http://angular-1lub4b53.cloudapp.net/test1/
sources: https://github.com/kampdomoj/Test

**Comment by tenowg** [comment]
Have you by chance included es6-shim somewhere, last I heard it is required for IE11 or lower

**Comment by kampdomoj** [comment]
included it in the webpack bundle. I don't know if that would be enough... it doesn't make it working

**Comment by pkozlowski-opensource** [comment]
> included it in the webpack bundle.

I can't see dependeny on `es-shim` in your
https://github.com/kampdomoj/Test/blob/master/package.json

**Comment by kampdomoj** [comment]
sorry, forgot to push the change :(  It's in the repo now

**Comment by wkwiatek** [comment]
Following error occurs in your app: 
```
reflect-metadata shim is required when using class decorators
```

Generally I tested Angular with IE lastly and it should work on IE10/11 (but bare in mind that `es6-shim` and `reflect-metadata` have to be included). Problems begins with IE9 but that's another story.

**Comment by pkozlowski-opensource** [comment]
Thnx for chiming in @wkwiatek - good catch with reflect-metadata.

Regarding IE9 - we definitively want to run smoothly and we still believe that making IE9 work is just a matter of IE9-spcific shims. We know that couple of APIs are missing from IE9 (requestAnimationFrame, classList etc.) but those should be polyfillable since our unit test campaign works on IE9 with polyffils.

Going to close this one as we've got  IE9 specific issues already open.

**Comment by kampdomoj** [comment]
In the mean time added es6-shim explicitly, but still no success with IE...:(

```
  <script src="es6-shim.js"></script>
</head>
```

What is wrong with http://angular-1lub4b53.cloudapp.net/test1/?
