### ISSUE TITLE
FormBuilder code sample does not compile

### ISSUE THREAD

**Issue by luaks** [angular/angular#58324]
### Describe the problem that you experienced

The sample code for the `FormBuilder` in the reactive forms docs code provides the `FormBuilder` via constructor injection.
The form itself however is defined as a member, which references the provided `FormBuilder` when building the form.
TypeScript fails to compile as the `formBuilder` is used before initialization.

```ts
@Component({/*...*/})
export class AppComponent {
  form = this.formBuilder.group({
    firstname: ['']
  });

  constructor(private formBuilder: FormBuilder) {
  }
  // ...
}
```

`TS2729: Property 'formBuilder' is used before its initialization.`

### Enter the URL of the topic with the problem

https://angular.dev/guide/forms/reactive-forms#import-the-formbuilder-class

### Describe what you want to experience that would fix the problem

One way to fix this would be providing the example using the [inject](https://angular.dev/api/core/inject) function.

```ts
@Component({/*...*/})
export class AppComponent {
  formBuilder = inject(FormBuilder);
  form = this.formBuilder.group({
    firstname: ['']
  })
}
```

Another would be to set up the form in the constructor instead of the member.

```ts
@Component({/*...*/})
export class AppComponent {
  form;

  constructor(private formBuilder: FormBuilder) {
    form = this.formBuilder.group({
      firstname: ['']
    });
  }
}
```

### If this problem caused an exception or error, please paste it here

```TS2729: Property 'formBuilder' is used before its initialization.```

### Provide any additional information here in as much as detail as you can

The project is a fresh project created with the latest angular cli.

**Comment by fMoro1999** [comment]
Hi @luaks ,
The code you mentioned in the doc is legal in an empty Angular 18 project. ([StackBlitz here](https://stackblitz.com/edit/stackblitz-starters-wadv5j?file=src%2Fmain.ts)).

By the way, in order to fix the `TS2729` error you mentioned, you need to set the `target` to `ES2022` and `useDefineForClassFields` to `false` in the `tsconfig.json` file. These settings will be automatically applied when creating/updating to a more recent Angular version (up to v.15). You can find more information in [this PR](https://github.com/angular/angular-cli/pull/23936) and in [this article](https://angular.schule/blog/2022-11-use-define-for-class-fields).

Actually, [versions strictly before v.16 are not currently supported anymore by the team](https://angular.dev/reference/releases#actively-supported-versions), so I do not believe it could make any sense to update the doc in order to provide examples compatible with versions out of support.

**Comment by JeanMeche** [comment]
@fMoro1999, the TS team intends to deprecate `useDefineForClassFields: false` in [TS 6.0](https://github.com/microsoft/TypeScript/issues/60284). So we should have an example that work without it.

**Comment by fMoro1999** [comment]
> @fMoro1999, the TS team intends to deprecate `useDefineForClassFields: false` in [TS 6.0](https://github.com/microsoft/TypeScript/issues/60284). So we should have an example that work without it. 

Oh, I didn't know this. Thank you 😅

**Comment by luaks** [comment]
@fMoro1999 Even though the stackblitz starter claims to be based on an angular cli project, this does not seem to be true (or at least not true for recent versions of angular cli).
The link you provided is a direct clone of https://github.com/stackblitz/starters/tree/main/angular instead of a fresh angular cli project.

I have set up a project with a fresh installation of the angular cli and ran `ng new` with all default settings.

Your point regarding typescript settings being able to fix this is correct, however I believe that samples in docs ought to work with default settings (or changes to the settings should be pointed out).

**Comment by MarkAxisa** [comment]
@JeanMeche  is this one still up for grabs please, or should we add appropriate label and wait for  TS 6.0 ?

**Comment by JeanMeche** [comment]
It was fixed by @JeevanMahesha !
