### ISSUE TITLE
`dartfmt` takes forever when running `gulp test.unit.dart`

### ISSUE THREAD

**Issue by tbosch** [angular/angular#5839]
Does not happen all the time, but when changing large files like the `public_api_spec.ts`...

Workaround: In `dart_tree.ts`, change function `makeDartTree` to not use `dartfmt`

**Comment by munificent** [comment]
What version of dartfmt are you using? You're probably getting bitten by [this bug](https://github.com/dart-lang/dart_style/issues/484), which is fixed in dart_style 0.2.4.

If it's not that, please do update [this bug](https://github.com/dart-lang/dart_style/issues/485) with repro steps and I'll look into it. Thanks!
