### ISSUE TITLE
Router: Erroneously recognizes non-parameter URLs

### ISSUE THREAD

**Issue by matanlurey** [angular/angular#5848]
```dart
@RouteConfig(const [
  const Route(
      name: 'Planning',
      path: 'planning',
      component: PlanningComponent),
  const Route(
      name: 'Company',
      // This 'details/' is required, otherwise there are conflicts between the
      // routes as 'all' and 'planning' are interpreted as companyId's.
      path: 'details/:companyId/...',
      component: CompanyComponent)
])
```

Ideally I'd like to remove `details/` from the URL. Right now though `planning` is interpreted as a `:companyId` and fails, requiring me to add a prefix.

**Comment by btford** [comment]
So with this configuration (but with `/:companyId/...` instead of `/details/:companyId/...`), you navigate to a URL like `/planning, and rather than navigate to `PlanningComponent`, it's navigating to `CompanyComponent` ?

What does the `RouteConfig` for `CompanyComponent` look like? Specifically, does it include a route with `path: '/'`?

I have a hunch why you might be seeing this, but want to double check to be sure.

**Comment by btford** [comment]
I have a reproduction for the case I describe above, but I want to make sure that if this is a problem in some other configuration that I include a test for it as well.

**Comment by btford** [comment]
Just chatted, and the same is true of routes with `useAsDefault`.
