### ISSUE TITLE
Query @ContentChildren of any type

### ISSUE THREAD

**Issue by adamdbradley** [angular/angular#5855]
Is it, or could it be possible to select any/all child directives with `@ContentChildren`?

For example, let's say we have a `<ion-toolbar>` component:

```
@Component({
	selector: ‘ion-toolbar’,
	template: ‘<div><ng-content></ng-content></div>’
})
class Toolbar {...}
```

And users can put any number of random components inside of ion-toolbar:

```
<ion-toolbar>
	<ion-title>...</ion-title>
</ion-toolbar>

<ion-toolbar>
	<ion-segment>...</ion-segment>
</ion-toolbar>
```

To get references to ion-title or ion-segment we'd have to query for exactly those two type of components, but would it be possible to have a generic query that gets all child components of any type?

cc @tbosch @IgorMinar

**Comment by woppa684** [comment]
... or let those types extend a generic class or implement an interface. I also really need this! I'm creating a form with custom components like my-text, my-select, my-switch etc and I want to get all of them in my form-groups.

**Comment by zoechi** [comment]
You could add the same template variable everywhere and use this instead of the type

    @ViewChildren('someVar') allFields;

**Comment by michaelbromley** [comment]
I also would find this very useful. My use case is thus:

I have a re-usable library component (`Foo`) which has a default template, but I want the user to be able to provide her own template if desired. The component's template looks like this:

```HTML
<div *ngIf="hasTemplate"><ng-content></ng-content></div>
<div *ngIf="!hasTemplate"><!-- the default template --></div>
```

So the user can either use it like this:

```
<foo></foo> <!-- uses the "default" template -->
```

or like this:

```
<foo><div class="my-custom-stuff">...</div></foo>
```

But I currently have no way to find out whether there are any arbitrary HTML elements inside the `<foo>` element, since I can only query Angular components or template variables. 

Currently I rely on the user adding a `#template` variable somewhere in their custom template, and then query it via `@ContentChildren('template')`, but this is clumsy and does not seem optimal.

**Comment by zoechi** [comment]
@michaelbromley An alterative would be to allow default content for

```
<ng-content>some default content</ng-content>
```

that is added as children when the user of the component hasn't passed own content.
This is how the shadow DOM `<content>` tag works AFAIK (not checked since a while and might have changed since).

**Comment by BenjaminDobler** [comment]
I also have a use case for this and i can`t think of a workaround. Let`s say i have a LayoutManager Component which expects Components which extend say UIComponent. Right now i can`t really do this cause i don`t know which type the components will have. I only know that they will extend UIComponent.

**Comment by pkozlowski-opensource** [comment]
This will be covered by #8563

**Comment by MurhafSousli** [comment]
@zoechi This does not work anymore! it throws an error

 > <ng-content> element cannot have content.

Related #12530
