### ISSUE TITLE
Feature Request: Component-Level Deferred Loading/Hydration Configuration in Angular

### ISSUE THREAD

**Issue by naveedahmed1** [angular/angular#58643]
### Description

**Summary**: Add an option to define deferred loading (`@defer`) configuration at the component level, eliminating the need to wrap components in `@defer` blocks in the template.

**Background**: Angular's current implementation of deferred loading requires wrapping each component instance in an @defer block in the template. While this approach offers flexibility, it also introduces repetitive work in cases where a component always requires deferred loading or hydration. By defining this configuration directly at the component level, we can make templates cleaner, streamline the component setup, and reduce repetitive declarations.

**Problem**: For components that are consistently loaded or hydrated in a deferred manner, wrapping every instance in an @defer block becomes an additional task that could be avoided with a component-level setting. Such repetitive @defer blocks add to template complexity and can lead to more verbose code, particularly when applied to multiple components.

**Proposed Solution**: Introduce a component-level configuration option for deferred loading and hydration within the component. This approach would allow developers to specify that a component should always be deferred, without needing to wrap each instance in @defer in the template.

**Benefits**:

- **Cleaner Templates**: Templates become easier to read and maintain as @defer blocks are no longer needed in the template for components that consistently require deferred loading.
- **Reduced Redundancy**: Developers can specify deferred loading once at the component level instead of adding repetitive configuration in every usage.
- **Improved Developer Experience**: Simplifies the setup process for deferred components, making the feature more approachable and less error-prone.

**Conclusion**: A component-level deferred loading configuration would enhance Angular’s usability by reducing template complexity and making the deferred loading feature more streamlined. This aligns with Angular’s philosophy of reducing configuration burden in templates, leading to more maintainable and developer-friendly code.

### Proposed solution

I'm not certain what the best solution might be, but one possible approach that comes to mind is adding a defer configuration option directly to the component decorator.

```
@Component({
  selector: 'app-lazy-component',
  templateUrl: './lazy-component.component.html',
  defer: {},  // Component-level setting for deferred loading/hydration
})
export class LazyComponent { }
```

I understand that the Angular team is focused on reducing configuration within the component decorator. An alternative approach might be a `defer` function that accepts a configuration object as input, similar to functions like `afterNextRender` or `effect`.

### Alternatives considered

The currently supported `defer` block

**Comment by thePunderWoman** [comment]
We appreciate the feature request. We consider Deferrable Views the definitive primitive in Angular for deferred loading and while we understand your desire for component level deferred loading, we have no plans to implement support for it at this time. There's a number of reasons for this, and a few of them are below. This is not an exhaustive list.

- Making component async would require some handling of "loading" and "error" states, which is a bit less organic to express on a component level.
- Component-based defer boundaries may not be straightforward for developers to understand the behavior just by looking at a template vs with @defer you clearly see "async" boundaries and can control the UX better. 
- Making component async would require large changes to Angular architecture due to Angular currently assuming and expecting components within views are available synchronously.

Thanks for your suggestion and your enthusiasm.
