### ISSUE TITLE
angular/common vs angular/core seems a bit ambiguous

### ISSUE THREAD

**Issue by thelgevold** [angular/angular#5874]
It seems to me that alpha.53 continues the approach of splitting larger modules into smaller, more targeted ones. 
This is not surprising, but I find naming conventions like angular2/core vs angular2/common to be a bit ambiguous. 'Core' and 'Common' both seem very generic and it almost sounds like they are referring to the same type of module. 
It might make sense to define these granular modules with more specific names. Core might be ok, but having a "Common" module as well might make it hard to remember which one is which....

Anyway, just my 2 cents.

**Comment by tamascsaba** [comment]
I think the same.


E.g:

common.ts
```
export * from './src/common/pipes';
export * from './src/common/directives';
export * from './src/common/forms';
export * from './src/common/common_directives';
```

It is understandable, but Pipe is importable from core
```
import {Pipe} from 'angular2/core';
```

I don't understand :(

**Comment by yfain** [comment]
I'm more concerned with the fact that now you need to import the sources of each operator from RxJS, and there are more than 80 operators. For example, the code below will work only if you include 
import 'rxjs/add/operator/map' and will do an appropriate pkg mapping in System.config() :

```
import { Http} from 'angular2/http';
import { Injectable} from "angular2/core";
import { Observable} from "rxjs/Observable";
import 'rxjs/add/operator/map';

@Injectable()
export class ProductService{
    constructor( private http: Http){}

    getProductByID(productID: string): Observable<any>{
       return this.http.get(`/products/${productID}`)
           .map(res => res.json());
    }
}
```

**Comment by tamascsaba** [comment]
I wrapped http with a service, it is better only once import rxjs operators.

**Comment by IgorMinar** [comment]
- `core` - stuff that is always require to run your app in the browser
- `common` - directives, pipes and form controls commonly needed and provided with the framework as an optional dependency (but we expect that all web apps will want them)

`core` is reused for non-browser platforms (e.g. reactnative) but most `commons` bits don't make sense there.

Is this just a documentation issue?

----

`rxjs/add/operator/map` was discussed elsewhere many times - it's the right thing to do for now until function bind `::` operator is part of the EcmaScript spec - we can either have portable+modular+low-payload code by paying via explicit dependencies, or we can have non-portable+monolithic+bloated-payload code by gaining implicit dependencies and global "variables". We prefer the former. Especially since in ES6, all imports are already explicitly defined in each file.

Please let's not hijack this issue with follow ups on this unrelated issue.

**Comment by tamascsaba** [comment]
Thanks for the answer @IgorMinar, 
When pipes ara in common, then why  ```{Pipe}``` is importable from ```'angular2/core'```?

**Comment by pkozlowski-opensource** [comment]
> When pipes ara in common, then why {Pipe} is importable from 'angular2/core'?

`Pipe` is an "interface" that concrete pipes can implement

**Comment by tamascsaba** [comment]
Thanks :+1:

**Comment by thelgevold** [comment]
@IgorMinar Thanks!
I think you're right, it will be great to get these details into the docs.
