### ISSUE TITLE
Adding a `notify` method to signals API

### ISSUE THREAD

**Issue by kai1992cool** [angular/angular#58815]
### Which @angular/* package(s) are relevant/related to the feature request?

core

### Description

Although this suggestion goes against what I have read for signals, that its mainly for primitive datatypes and non primitives data inner updates to the signals are not going to trigger an update on the signal.

While this is good and we have to destructure the object on each update of the inner property, if we add a convenience method like `notify`, we can get rid of the overhead of cloning the signal into a new memory reference.

This is just to get your opinion on this valuable feature and could help developers get rid of the cloning overhead, which results in less code, better readability.

### Proposed solution

Introduce the `notify` method to trigger the signal update similar to how BehaviourSubject does it. 

It would be great to not create a new memory reference for each call to notify.

### Alternatives considered

Or we can have a convenience method similar to notify that does the cloning in the most effecient way possible.

### Reference stackblitz with the overhead code.

[stackblitz](https://stackblitz.com/edit/stackblitz-starters-fzgcbm?file=src%2Fmain.ts)

**Comment by JeanMeche** [comment]
Basically you're asking to bring `mutate` back.
The problem behind it is the propagation of the dirtiness which won't get much further because the reference won't change (props passed to inputs won't mark children as dirty etc). This is why this feature was removed. 

If what you're looking is to schedule CD on your component, there is still `cdr.markForCheck`.
