### ISSUE TITLE
*directive not parsing correctly

### ISSUE THREAD

**Issue by mhevery** [angular/angular#5894]
See example: http://plnkr.co/edit/9GdLbXM0mh5zHPKhcwCL?p=info

Both of these should parse correctly:

```
<div *bsPane="title exp"></div>
<div *bsPane="title: exp"></div>
```

Given:

```
@Directive({
  selector: '[bsPane]'
})
class Foo {
  @Input() bsPaneTitle: string;
}
```

instead get error:

``````
Can't bind to 'bsPane' since it isn't a known native property ("
    Demo:
    <div [ERROR ->]*bsPane="title 'Overview'"></div>
    <div *bsPane="title 'Summary'"></div>"): DiDemo@2:9
Property binding bsPane not used by any directive on an embedded template ("
    Demo:
    [ERROR ->]<div *bsPane="title 'Overview'"></div>
    <div *bsPane="title 'Summary'"></div>"): DiDemo@2:4
Can't bind to 'bsPane' since it isn't a known native property ("
    Demo:
    <div *bsPane="title 'Overview'"></div>
    <div [ERROR ->]*bsPane="title 'Summary'"></div>"): DiDemo@3:9
Property binding bsPane not used by any directive on an embedded template ("
    Demo:
    <div *bsPane="title 'Overview'"></div>
    [ERROR ->]<div *bsPane="title 'Summary'"></div>"): DiDemo@3:4```
``````

and 

```
EXCEPTION: Template parse errors:
Parser Error: Unexpected token :, expected identifier, keyword, or string at column 13 in [bsPane title: 'Overview'] in DiDemo@2:9 ("
    Demo:
    <div [ERROR ->]*bsPane="title: 'Overview'"></div>
    <div *bsPane="title: 'Summary'"></div>"): DiDemo@2:9
Parser Error: Unexpected token :, expected identifier, keyword, or string at column 13 in [bsPane title: 'Summary'] in DiDemo@3:9 ("
    Demo:
    <div *bsPane="title: 'Overview'"></div>
    <div [ERROR ->]*bsPane="title: 'Summary'"></div>"): DiDemo@3:9
```

**Comment by mhevery** [comment]
This is preventing proper demo on the home page.

**Comment by vicb** [comment]
Please give a valid plunker link

**Comment by vicb** [comment]
Actually `<div *bsPane="title exp"></div>` desugars to `<div template='bsPane: title exp'>`.

The error seems legit.

**Comment by mhevery** [comment]
Updated the plunker.

You are right that  `<div *bsPane="title exp"></div>` desugars to `<div template='bsPane: title exp'>`.

But  `<div *bsPane="title: exp"></div>` should desugars to `<div template='bsPane; title: exp'>`.

**Comment by mhevery** [comment]
Closed by #6038

**Comment by tbosch** [comment]
#6038 fixed this in the wrong way by introducing see https://github.com/angular/angular/issues/9062. I am reverting #6038.

**Comment by vicb** [comment]
@mhevery do we have a design spec somewhere ?
what you describe is far from what is actually currently implemented (not sure if this has changed for the past 6+ months)

**Comment by vicb** [comment]
refs
https://github.com/angular/angular/issues/522
https://github.com/angular/angular/issues/717

**Comment by awerlang** [comment]
`<div *directive="content"></div>` desugars to `<div template="directive content"></div>` (no colon or semicolon appended). An user could write `<div template="directive: content"></div>` (with colon).

`<div *bsPane="title exp"></div>` shouldn't be supported (user didn't put a colon), the grammar would be ambiguous.

See #12841

**Comment by awerlang** [comment]
I'd like to expand on my previous comment.

There's 2 separate issues here:

1. Can't bind to 'bsPane' since it isn't a known native property
2. Parser Error: Unexpected token :, expected identifier, keyword, or string at column 13 in [bsPane title: 'Overview']

PR #12841 fixes (1) but prevents `<div *bsPane="title exp"></div>`; also fixes (2).

### Desugaring

Desugaring from * notation to `template` attribute is done before input string is tokenized. It prepends the attribute's name followed by a _space_, then it tokenizes & parses. At this moment there's no information about directives possibly being matched. I don't see how it would properly add an ";" or ":" to it instead of a space at this step, with the goal of removing ambiguity in the grammar. 

### Support for optional ":" everywhere

I propose this revised grammar:

1) The language is composed of a series of tuples
2) Every tuple contains 2 components
2.a) Alternatively, a tuple might be composed of a single component, a _key_, given that any of these is true:
2.a.i) It is the first tuple
2.a.ii) It is the last tuple
2.a.iii) It is succeded by a ";" character
3) Each first component of the tuple is a _key_
4) Each second component of the tuple is an _expression_
5) The second component is optionally preceded by a ":" character
6) The tuple is optionally succeded by a ";" character

Item 2.a.iii is there to remove ambiguity. If we permit any tuple, then I don't see how it would be feasible to parse.

Some things to note / assumptions:

* I've left assignment out because it doesn't present any challenge to parse;
* Optional delimiters ":" and ";" exists to support a more fluent language;
* More than one tuple composed of a single component (key) is useful to narrow down matching of elements to directives.

Valid input:

```
key key exp
key key: exp
key; key
key; key exp key
```

Invalid input:

```
key key key
key key key exp
key key exp key key: exp
key: key exp
```

@mhevery I'd like to know your thoughts about this. If you agree I can proceed with a PR.

**Comment by e-cloud** [comment]
looks like it's related to http://stackoverflow.com/questions/41789702/how-to-use-angular-structural-directive-with-multiple-inputs
