### ISSUE TITLE
[testing] regression with beforeEach and inject

### ISSUE THREAD

**Issue by cexbrayat** [angular/angular#5902]
I think that alpha-54 introduced a regression with b803ecf7e747a0938db89f020caf4c41b585c699

`beforeEach(inject([TestComponentBuilder], tcBuilder => tcb = tcBuilder));` used to work perfectly but now it fails with: `Failed: Error: inject returned a value. Did you mean to use injectAsync? Returned value was: [object Object]`.

I suspect that's because the arrow function returns the `tcb` object, and is thus not undefined, so it suggests to use `injectAsync` where it is not necessary.

The current workaround is to write: 
     
     beforeEach(inject([TestComponentBuilder], tcBuilder => {
       tcb = tcBuilder;
       return undefined;
     }));

Overall, I've got to point out that having to migrate again all the tests is a bit painful (thousands of errors) :) Maybe it could just be a warning instead of an error?

And the more I see this, the more I think something like #5570 would be great to separate the concerns.

cc @juliemr

**Comment by juliemr** [comment]
You're right about your suspicion. You could write a slightly simpler test:

```js
 beforeEach(inject([TestComponentBuilder], tcBuilder => { tcb = tcBuilder; }));
```

but I see your point.

We could just check if the return value is a promise, instead of checking that it is undefined. cc @IgorMinar for thoughts on that.

Breaking changes should be less frequent now that we're in beta, sorry for the churn. I know it's frustrating having to migrate lots of tests.

**Comment by juliemr** [comment]
Will be fixed with the new separation of `inject` and `async`.
