### ISSUE TITLE
flickering of elements with fixed or absolute positioning. After updating to Angular 19.

### ISSUE THREAD

**Issue by AndSokolov** [angular/angular#59036]
### Which @angular/* package(s) are the source of the bug?

Don't known / other

### Is this a regression?

Yes

### Description

After upgrading from 17 Angular to 19 Angular. Components with “fixed” or “absoulute” positioning began to work poorly. 
For example, when you click on the filter button, a window with filters with absolute positioning appears. At the beginning, it seems to shift elements for milliseconds, which are with static positioning, and then it is displayed normally.
Unpleasant flickering appeared on the page.

I use "builder": "@angular-devkit/build-angular:application"

### Please provide the exception or error you saw

```true

```

### Please provide the environment you discovered this bug in (run `ng version`)

```true
Angular CLI: 19.0.2
Node: 20.11.1
Package Manager: yarn 1.22.22
OS: win32 x64

Angular: 19.0.1
... animations, cdk, common, compiler, compiler-cli, core, forms
... material, platform-browser, platform-browser-dynamic, router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1900.2
@angular-devkit/build-angular   19.0.2
@angular-devkit/core            19.0.2
@angular-devkit/schematics      19.0.2
@angular/cli                    19.0.2
@schematics/angular             19.0.2
rxjs                            7.8.1
typescript                      5.6.2
zone.js                         0.15.0
```

**Comment by e-oz** [comment]
There are dozens of reasons that could cause that. Without reproduction this issue will not move.

**Comment by AndSokolov** [comment]
The project is quite easy. There are no extraneous libs. There are only Angular and Angular material.

The problem definitely occurred after updating these packages.

**Comment by AndSokolov** [comment]
The problem is "builder": "@angular-devkit/build-angular:application"
I switched back to the old builder and everything worked: "builder": "@angular-devkit/build-angular:browser"

I hope this helps someone.

**Comment by AndSokolov** [comment]
You can reproduce it very easily:

1. Make a button.
2. Under the button, create a table (I used mat-table)
2. Create a menu element with absolute positioning that will open when you press a button. And be located above the table.

When you press the button for the first time, the table will flicker slightly.

**Comment by wartab** [comment]
How many people need to ask you for a concrete reproduction with code?

**Comment by AndSokolov** [comment]
Dear friend 
wartab.

I indicated how this can be reproduced and what elements are needed. This can be done in 10 minutes.

Moreover, I myself found out which package was the problem.

Cuttings from my project will only confuse things further.

If no one wants to solve this problem, then you can close this task

**Comment by JeanMeche** [comment]
Thank you for reaching out about this issue. However, in order for us to effectively investigate and address the problem, we need a clear and reproducible example. Without sufficient details or a repro, it's challenging for us to determine the root cause or provide meaningful help.

Please note that per our [Code of Conduct](https://github.com/angular/code-of-conduct/blob/main/CODE_OF_CONDUCT.md), we encourage all contributors to engage constructively and collaboratively. This includes providing the necessary information when requested, as it ensures the best use of everyone’s time and effort.

If you're unwilling or unable to share a minimal reproducible example, we may not be able to proceed further with this issue. If additional context becomes available in the future, feel free to reopen or comment on this thread.

Thank you for understanding,

**Comment by AndSokolov** [comment]
Hello.
Okay, I'm happy to help with this and I've created a repository, with a little example, I hope it helps you.

https://github.com/AndSokolov/angular19

After pressing the button, a flickering occurs.
The problem disappears if you change the builder in angular.json to "builder": "@angular-devkit/build-angular:browser"
