### ISSUE TITLE
The execution of NgModule constructor and ENVIRONMENT_INITIALIZER is not stable in standalone component.

### ISSUE THREAD

**Issue by UchihaYuki** [angular/angular#59091]
### Which @angular/* package(s) are the source of the bug?

core

### Is this a regression?

No

### Description

You can switch between standalone and NgModule versions in main.ts, by commenting out the corresponding line:
![Image](https://github.com/user-attachments/assets/1fd9d728-1a72-431b-938d-6e73e51475df)

You should add "/1" to address bar to preview.

When you use standalone version, the SharedModule will be instantiated 3 times, but when you use NgModule version, it will be instantiated only twice. You can observe that in console:

standalone:
![Image](https://github.com/user-attachments/assets/6addd910-014d-4b41-b4f8-644888ca368c)

NgModule:
![Image](https://github.com/user-attachments/assets/f763b803-bf54-40b6-892d-e63f7c61464c)

### Please provide a link to a minimal reproduction of the bug

https://stackblitz.com/edit/stackblitz-starters-fjempp?file=src%2Fmain.ts

### Please provide the exception or error you saw

```true
Please see the description above
```

### Please provide the environment you discovered this bug in (run `ng version`)

```true
Please take look at the mini repo to find out.
```

**Comment by alxhub** [comment]
I think the Stackblitz repro has been modified since the issue here was written, since the messages logged are now different. Looking at the current repro I see:

* NgModule-based: instantiated once (root/app injector)
* Standalone-based: instantiated twice (root/app injector, standalone injector for `AppComponent`)

The difference is expected, since in the standalone version `SharedModule` is imported twice - once at the root level via `importProvidersFrom` and once in `ChildComponent` (which ends up included in `AppComponent`'s standalone injector). Given this, I would expect the initializer to run twice in the standalone version, which it does.

NgModules imported into standalone components do not get rolled up in the application injector - standalone components create their own injectors. As an optimization, imported NgModules of standalone components _do_ roll up to parent components, which is why `SharedModule` ends up in the injector for `AppComponent` and not just `ChildComponent`.

**Comment by UchihaYuki** [comment]
@alxhub
> I think the Stackblitz repro has been modified since the issue here was written, since the messages logged are now different. Looking at the current repro I see:

You need to append '/1' in address bar as I said in the original post like following:
![Image](https://github.com/user-attachments/assets/083b6982-ad52-44f6-871f-6336a5b60d6a)
I use this to show that when imported through route, the behavior is the same. 

> NgModules imported into standalone components do not get rolled up in the **application injector(Do you mean the root environment injector?)** - standalone components create their own injectors. As an optimization, imported NgModules of standalone components do roll up to parent components, which is why SharedModule ends up in the **injector for AppComponent(Do you mean the Standalone one)** and **not just(? Do you mean not? Because if you don't append '/1' Then there is no ChildComponent Standalone injector)** ChildComponent.

I can't understand the above. Did you only explain what happened in `bootstrap-from-standalone` version? Sorry, I'm a little confused.

There are two child components:
```
<router-outlet></router-outlet> // first one
<app-child></app-child> // second one
```
The second one doesn't instantiate SharedModule in `bootstrap-from-ngmodule` version but does in `bootstrap-from-standalone` version. The first one instantiates SharedModule in both versions.

**Comment by UchihaYuki** [comment]
I have an explanation for this phenomenon. Let's look at the following structure in `app.component.html`:
```
<#VIEW>
<router-outlet></router-outlet> // first one
<app-child></app-child> // second one
</#VIEW>
```
In `bootstrap-from-standalone` version, `ChildComponent` is provided in `AppComponent`, the `SharedModule` gets provided in `Standalone[_AppComponent]`. But in the `bootstrap-from-ngmodule` version, since `ChildComponent` is provided in `AppModule`, `SharedModule` gets provided in `root`.
As for the first one, it can be regarded as a special case in Angular. In this special case, Angular will create a Standalone injector for standalone component.

Am I right?
