### ISSUE TITLE
Displayed input value in ngFor gets duplicated when splicing an object into an array and input elements are wrapped by form (using template forms) even though name attribute is unique

### ISSUE THREAD

**Issue by motohead400** [angular/angular#59140]
### Which @angular/* package(s) are the source of the bug?

core, forms

### Is this a regression?

No

### Description

This is a pretty simple one to replicate.  I'm experiencing it in Angular 18 and I modified someone else's Stackblitz done in Angular 10 to replicate it, so it's been present at least since then.  Use a ngFor to display inputs for a object properties in an array.  Even using a track by function with unique ids, if you splice an item into the array (don't add at the end), the value will be displayed twice when surrounded by a form and using template forms.  If you take away the form tag it works fine.  It seems to have to do with how the name attribute is used within a form, even though the name attribute is unique for each input.  

### Please provide a link to a minimal reproduction of the bug

https://stackblitz.com/edit/angular-ivy-jp3hur1k?file=src%2Fapp%2Fapp.component.html

### Please provide the exception or error you saw

```true

```

### Please provide the environment you discovered this bug in (run `ng version`)

```true
Angular 10-18
```

**Comment by jnizet** [comment]
The problem here is that you're using the index of the item in the name of the input, and the name of the input is also used to identify the form control inside the form group created by the NgForm directive. It's thus a bad idea to change the name of the input, but that happens when you insert a new element in the array, since the indices change when that happens.

Use the ID of the item to generate a unique and immutable name, and the bug won't happen anymore.

**Comment by motohead400** [comment]
Ah that makes sense.  Thanks for the response!
