### ISSUE TITLE
Router.renavigate() doesn't work with Router.navigate()

### ISSUE THREAD

**Issue by LMFinney** [angular/angular#5916]
We are on alpha 54.

With AngularJS, we used `$state.go($state.current.name, $state.params, {reload: true});` to reload the contents of our app when we received a notification of stale data from the server. We're trying to use `router.renavigate()` in Angular to solve the same problem, but it's not working for us.

The problem is that `router.renavigate()` uses the last url it was given (stored in `router.lastNavigationAttempt`), but not all methods of navigation set that value. `router.lastNavigationAttempt` is set when entering a url in the browser directly, or when using the discouraged `router.navigateByUrl(...)`, but not when using the encouraged `router.navigate(...)` or `router.navigateByInstruction(...)`.

The effect is that calling `router.renavigate()` doesn't necessarily reload the current page - it often reloads another page that happens to be the starting point of the app or just some other place in the app on which I hit F5.

I created a [Plunker](http://embed.plnkr.co/dj77LxeKRMwbvrvg05of/) to demonstrate the issue. Follow these steps:
1. Click on the 'Nested Page by Url' button, which uses `router.navigateByUrl(...)`. The public behavior is that the bottom of the app now shows 'Nested Page'. You'll also see at the top that `router.lastNavigationAttempt` changes to `/nested/page`.
2. Click on the 'Home' button, which uses `router.navigate(...)` or use the 'Home' link. The public behavior is that the bottom of the app now shows 'Home'. You'll also see at the top that `router.lastNavigationAttempt` still shows `/nested/page`.
3. Click on the 'Reload' button, which uses `router.renavigate()`. You'll see that the bottom of the page changes back to 'Nested Page' because `renavigate` uses the stale `lastNavigationAttempt`. My intent was to reload the 'Home' public value, not to have it change.

We need a way to renavigate that honors routing that happened via `router.navigate(...)`

**Comment by brandonroberts** [comment]
Looks like a bug. If you want to try a workaround, you could subscribe to url updates and update the router.lastNavigationAttempt manually.

http://plnkr.co/edit/5WPHyQNZ2Dmn5nwLRkqw?p=preview

**Comment by LMFinney** [comment]
@brandonroberts That's a great, simple workaround.

Thanks

**Comment by craigsnyders** [comment]
We also ran into this issue after noticing our component run `$routerOnActivate` twice per navigation, after having called `$rootRouter.navigateByInstruction`.  

`navigateByInstruction` will activate our component, all is good so far.  At the end of the activation lifecycle, `$rootRouter` will process it's commit method, causing `$location.url(path + query)` to be called.  

Next, the watcher fires, indicating the URL has changed.  `lastNavigationAttempt` was not updated, so the router kicks of a new activation lifecycle through `navigateByUrl`.

We will use the above workaround but feel that it's less than ideal - this feels like a bug in ngComponentRouter

**Comment by brandonroberts** [comment]
Its not a bug per say. `router.renavigate` isn't meant for navigating again in the case that you configure your routes dynamically at runtime. `router.lastNavigationAttempt` is only updated when `router.navigateByUrl` is called. The navigateByUrl is called on initial load and unless you use it manually it won't get called again because the other navigation functions such as `router.navigate` and  `router.navigateByInstruction` don't update the `lastNavigationAttempt` either.

**Comment by craigsnyders** [comment]
Ah - sorry, my issue has deviated slightly from the original one in this thread.  In my case I'm using `router.navigateByInstruction`, not using `router.renavigate`.

I have found that when I call `router.navigateByInstruction` it will update the url, which in turn will cause [this watch](https://github.com/angular/angular/blob/d094a85647af04a67620ed1287103aeee3936298/modules/angular1_router/src/module_template.js#L112) to fire and compare the `lastNavigationAttempt`.  Then because `lastNavigationAttempt` wasn't updated in `navigateByInstruction`, it makes a fresh call [fresh call](https://github.com/angular/angular/blob/d094a85647af04a67620ed1287103aeee3936298/modules/angular1_router/src/module_template.js#L114) to `navigateByUrl` - resulting in a perceived 'double navigation' where the final component will activate -> deactivate -> reuse.

Perhaps I'm using it incorrectly - I can create a plunker if that will help?

**Comment by brandonroberts** [comment]
@craigsnyders yea, that doesn't seem right. If you can reproduce that in a plunker that would be great.

**Comment by vicb** [comment]
This router has been deprecated
