### ISSUE TITLE
Allow Asynchronous APP_INITIALIAZER

### ISSUE THREAD

**Issue by jteplitz602** [angular/angular#5929]
Sometimes you may want to have an async APP_INITIALIZER that needs to be resolved before bootstrapping. For example in a WebWorker you may want to receive some values from the UI (such as the browser location or history) before the app bootstraps. This is distinct from bootstrapping with `asyncApplication` because the DI providers are not themselves asynchronous, but rather some async work must be done **after** the providers are set up.

CC @vsavkin

**Comment by vsavkin** [comment]
## Option 1
We can support it as follows:

```
function funcReturningAPromise:Promise() {...}
 
platform(MY_PLATFORM).
  asyncApplication(
    () => [], 
    [platform(APP_INITIALIZER, {useFactory: () => funcReturningAPromise})]).
  then(appRef => ...);
```

* Angular will check the results of app initializers, collect all the promises, and wait for them to be resolved before resolving the application ref promise.
* Angular will throw if an initializer returned a promise when `application` was used instead of `asyncApplication`.
 
## Option 2

Another option would be to do the following:
```
function funcReturningAPromise:Promise() {...}
 
let appRef = platform(MY_PLATFORM).application([platform(APP_INITIALIZER, {useFactory: () => funcReturningAPromise})]);
appRef.get(APP_INITIALIZERS_COMPLETED).then(_ => {

});
```

This would work with both `application` and `asyncApplication`.

I think Option 1 is cleaner.

**Comment by jteplitz602** [comment]
I also think Option 1 is cleaner. I'm happy to ahead and implement it if you want. I think if we do option 1 we should allow people to pass in `null` as the first argument to `asyncApplication` as well as a function.
