### ISSUE TITLE
Rename @Template -> to @Viewport

### ISSUE THREAD

**Issue by mhevery** [angular/angular#595]
Rename:
- `@Template` -> `@Viewport`
- `ViewPort` -> `ViewContainer`

Needed for: #596

**Comment by vicb** [comment]
@mhevery Could we discuss the terminology before making the actual change ?

- I think the current `ViewPort` is a good name,
- `Views` is not such a good name, it makes it hard to distinguish between a List of `View`s (`views`) and a reference to a `Views` (`views`)

My proposal would be to keep the current `ViewPort` and rename the `@Template` annotation.

What about:
- `@Fragment()` -> in line with DocumentFragment (HTML),
- `@Instantiator()` -> the doc uses this terminology,
- other ?

**Comment by mhevery** [comment]
@vsavkin @rkirov please add your thoughts

Goal: Rename `@Template` to something else, so that it can be freed up for component template annotations

Thoughts:
- People here seem to be having allergic reaction to `Instantiator` 
- `@Fragment` is an interesting proposal. @vsavkin @rkirov thoughts?
- `@ViewPort` is liked because it is a controller which manages the ViewPort, but it does create collision with current `ViewPort` Your point about `Views` is valid in my opinion.

+1 for `ViewPort` to `ViewContainer`

**Comment by rkirov** [comment]
+1 for current favorite `@Viewport` and `class ViewContainer`.

@vicb's arguments against `views` and `ViewCollection` are valid.

My argument against `@Fragment` is that if we want to evoke connection with HTML, `@Template` is really the right connection (as those directives have to live on html5 `<template>` elements). Since we can't use `@Template` we should pick a name that has no connection with `HTML`.

**Comment by vsavkin** [comment]
I prefer @Viewport and Views, but @Viewport and ViewCollection/ViewContainer works too.

**Comment by mhevery** [comment]
OK `@Viewport` and `ViewContainer` it is.
