### ISSUE TITLE
Zone is not defined with Angular 2 beta 0

### ISSUE THREAD

**Issue by jamesthurley** [angular/angular#5957]
If I clone `https://github.com/AngularClass/angular2-webpack-starter.git` and then update the `package.json` to Angular 2 beta 0 by updating dependencies like so:

```
    "angular2": "2.0.0-beta.0",
    "rxjs": "5.0.0-beta.0",
    "zone.js": "0.5.10"
```

Then test the website with `npm start` and navigating to `http://localhost:3000/`, angular fails to load and I get an error in the console of:

```
Uncaught ReferenceError: Zone is not defined 
NgZone._createInnerZone @ ng_zone.js:325NgZone @ ng_zone.js:117createNgZone @ application_ref.js:52PlatformRef_.application @ application_ref.js:153bootstrap @ browser.js:101main @ bootstrap.ts:20run @ core.js:96zoneBoundFn @ core.js:69
```

Can anyone help?

**Comment by pkozlowski-opensource** [comment]
https://github.com/angular/angular/issues/5958

There were number of breaking changes in beta.0 and https://github.com/AngularClass/angular2-webpack-starter authors should update the repo to a new version (I would be more than happy to help if needed)

Till then you can check minimal WebPack starter kit here: https://github.com/angular/angular2-seed

**Comment by LMFinney** [comment]
Why was this closed? I'm seeing the same problem when moving from alpha 54 to beta 0, and it's not clear from the starter projects what they did (if anything) to fix this.

The changelog lists no breaking changes for beta 0, and the breaking changes for alpha 55 seems irrelevant.

I've seen this problem on two projects, and people have reported it here and on gitter. We need more information.

**Comment by pkozlowski-opensource** [comment]
@LMFinney it was closed since there is nothing more we can do in this repo. I've linked a working starter and declared to help authors of other starter kits.

**Comment by pkozlowski-opensource** [comment]
Ah, and one needs to go over breaking changes from a version currenlty used, not only ones listed in beta.0. There were braking changes in both alpha.53 and alpha.54

**Comment by LMFinney** [comment]
But we didn't have this problem when we were at alpha.54 (we had other issues because of the other breaking changes, of course). This only started happening when we moved from alpha.54 to beta.0.

**Comment by pkozlowski-opensource** [comment]
@LMFinney I'm _really_ trying to help here, but I've just cloned https://github.com/AngularClass/angular2-webpack-starter, did `npm install` and `npm start`, opened app at http://localhost:3000/ and it worked for me. And this repo is already updated to beta.0.

At this stage I'm not sure what is the exact problem you are facing and which breaking change might have caused it (not even if it was due to a breaking change).

If you still face problems please open an issue in the https://github.com/AngularClass/angular2-webpack-starter repository and provide detailed info / reproduce scenario. Once again, I would be more than happy to help resolving issue in the https://github.com/AngularClass/angular2-webpack-starter and maintainers of it (@gdi2290) know that they can reach out for help.

But at this point we've got absolutely nothing to fix in this repo.

**Comment by jamesthurley** [comment]
Hi @LMFinney, take a look at the changes done to the repo I originally referenced:

https://github.com/AngularClass/angular2-webpack-starter/commits/master

I made an error in my original comment and they actually have updated... I found going through their commits starting with `chore: angular 2.0.0-beta.0` helped me get my own project updated, and also looking through the `angular2-seed` project referenced by @pkozlowski-opensource was useful.

**Comment by LMFinney** [comment]
Our configuration was based on webpack-starter weeks ago, and their approach has changed significantly since then, so this isn't something for me to report there.

I was able to resolve the issue with these steps:
1. Added `<script src="lib/angular2-polyfills.js"></script>` as the first script call in our index.html.
2. Removed `zone.js` and `reflect-metadata` from the entries of our webpack-config.js.
3. Added `enableProdMode();` (imported from `angular2\core`) before calling bootstrap() to resolve the issue from #5918.

I think the first two steps might be the key for others in my situation.

These steps apparently became necessary for alpha.55, but we skipped over that.

@pkozlowski-opensource, I saw on gitter that you're frustrated by the flux in the build processes around Angular, and I think my frustration is similar. I hope the community consolidates on a standard approach soon.

**Comment by gdi2290** [comment]
@LMFinney can you refactor your implementation to the latest changes from angular2-webpack-starter
[webpack.config.js#L66](https://github.com/AngularClass/angular2-webpack-starter/blob/f0dcce6a9655fa9663bff5be15cf46dbd844d708/webpack.config.js#L66)
[vendor.ts](https://github.com/AngularClass/angular2-webpack-starter/blob/f0dcce6a9655fa9663bff5be15cf46dbd844d708/src/vendor.ts)
you can still use `angular2-polyfills` but do so using `noParse` 
https://github.com/angular/angular2-seed/commit/9d95e85e232066a59e208f7ba4f67f648eaba79e

**Comment by LMFinney** [comment]
@gdi2290 We'll look into that. We aren't using vendor.ts yet, but this might be sufficient motivation.

Thanks

**Comment by aluanhaddad** [comment]
> I was able to resolve the issue with these steps:
> 1. Added <script src="lib/angular2-polyfills.js"></script> as the first script call in our index.html.
> 2. Removed zone.js and reflect-metadata from the entries of our webpack-config.js.
> 3. Added enableProdMode(); (imported from angular2\core) before calling bootstrap() to resolve the issue from #5918.

Thank you, that was very helpful. I am using SystemJS, and was experiencing the same issue when i started configuring dynamic transpilation in a project based on the current angular/quick-start project. 
All I had to do was step 1. Thanks again!

**Comment by aluanhaddad** [comment]
I ran into this this issue again and I resolved it by adding this to the top of my app/main.ts

import "zone.js";
