### ISSUE TITLE
Eliminate cast for form controls updateValue

### ISSUE THREAD

**Issue by doliver3** [angular/angular#5977]
Because the Formbuilder controls collection is typed as an AbstractControl and AbstractControl does not have an updateValue method, it requires a cast to a Control which does have an updateValue method. Only Control has an updateValue method.  

Preferred and shorter which is better:
  this.myForm.controls['goal_weight'].updateValue("5");

With the cast as required by Angular2 currently:
  (<Control> this.myForm.controls['goal_weight']).updateValue("5");
  (this.myForm.controls['goal_weight'] as Control).updateValue("5");

Could you consider using types that would not require a cast here to update the value?
Perhaps by making the the controls collection contain actually the Controls class items rather than AbstractControl items?
Or perhaps you could move the updateValue method into the AbstractControl class?

Example Template using myForm:
<form [ng-form-model]="myForm"
        (submit)="onSubmit(myForm.value)">
    <div class="form-group"
        [class.has-error]="!myForm.valid">
      <label for="weightInput">Weight Goal</label>
      <input type="text"
             class="form-control"
             id="weightInput"
             placeholder="Weight Goal (pounds)"
             #weight="form"
             [ng-form-control]="myForm.controls['goal_weight']">

**Comment by tenowg** [comment]
Looking at the code, AbstractControl is the base for Control, as well as
ControlGroup, which having a value, updateValue, etc, would probably lead
to as many problems... Its not that much extra typing to just cast to
Control.

**Comment by doliver3** [comment]
Can I ask why one would ever have an AbstractControl instance in a ControlGroup?  If it is an abstract base class by typical meaning, there is no intent to have a actual live instances of the AbstractControl, correct?  If so, wouldn't a simple fix be to make a ControlGroup be defined to hold real instances rather than abstract instances?  

Couldn't the ControlGroup be set to have in it the only thing that will ever be in it: real non-abstract instances of Control rather than instances of AbstractControl?

**Comment by tenowg** [comment]
Its not that the ControlGroup is holding live instances of AbstractControl,
AbstractControl is the base for several different types of Control
(Control, ControlGroup, etc.., I am sure there are a few more)), so each of
these is seen by typescript as an AbstractControl till cast.

ControlGroup can hold other ControlGroups, and Controls side by side, in
the same array/map. So when you call `getControl` you can get a
ControlGroup or a Control (AbstractControl has no clue or knowledge of what
classes it is holding, as long as they extend AbstractControl), thus you
will need to cast to either ControlGroup or Control.

So, in reality, AbstractControl is never instantiated directly. And
ControlGroup is not holding instances of AbstractControls, but is holding
Instances of Control(AbstractControl) and ControlGroup(AbstractControl).

I hope this makes some since...

You could write methods like, getControl() and getControlGroup() and have
casting done for you, but in the end, does that really save anything?

**Comment by doliver3** [comment]
Ok, I missed that it must hold both Controls and ControlGroups.  I see why you're requiring a cast.

**Comment by antonmoiseev** [comment]
Duplicates: https://github.com/angular/angular/issues/5871 https://github.com/angular/angular/issues/5497

**Comment by magnomp** [comment]
I think ideally there should be a finder method that only returns actual Control instances and not any other AbstractControl, so we could do:
this.myForm.whateverThatOnlyMatchesControlInstances['goal_weight']).updateValue("5");

No need to cast (which is simple to do but still too verbose), no need to touch the class hierarchy.

**Comment by kara** [comment]
In master, `updateValue()` now exists on AbstractControl (and thus, every subclass like FormGroup and FormControl).  You won't need to cast anymore, and the following should work:

```ts
this.myForm.updateValue({ 'goal_weight': '5' });
this.myForm.get('goal_weight').updateValue('5');
```

Closing this as resolved!
