### ISSUE TITLE
Input gets blured after every keystroke in ngModel inside ngFor

### ISSUE THREAD

**Issue by shahata** [angular/angular#5986]
See plunker: http://plnkr.co/edit/xyAeImDUOLXx9uczsJ5k?p=preview

You can see how input gets blured every time you write something in one of them and also the input view is not synced with the model, somehow characters you type appear in the input below the input you type in.

**Comment by bek0s** [comment]
I have the exact same problem. There is a workaround for this:
Instead of using an Array of basic type (string, number, etc), create a wrapper around it.

So, instead of this:

````typescript
items: string[] = ['', '', ''];
````

Do this:

````typescript
// item-wrapper.ts
export class ItemWrapper {
    public value: string;
}

// inside your component
private items: Array<ItemWrapper> = [];
// fill items with ItemWrapper instances here
````

And inside your template:

````html

<div *ngFor="#item of items, #i=index"> 
    <input [(ngModel)]="items[i].value">
</div>
````

This will work. The problem is that I have no idea why I have to use this workaround at first place. Looks like ngFor and ngModel don't play well when the array you iterate over has a  plain type.

Can somebody tell us if this is a bug or a "feature"? And if it is the latter, why?

Thank you.

**Comment by zoechi** [comment]
I guess when the value changes, `ngFor` creates a new input because the change detection recognizes the change.
With the wrapper the change is irrelevant to `ngFor`.

**Comment by vicb** [comment]
Use ngTrackBy to solve this issue
