### ISSUE TITLE
Rename @RouteConfig to @Routes

### ISSUE THREAD

**Issue by alexpods** [angular/angular#6040]
Why `@RouteConfig` is bad:
- two words
- `Config` suffix, that makes no sense. Similarly we could have `@ViewConfig` instead of `@View` (and it was like so [a long time ago in a galaxy far far away...](https://github.com/angular/angular/blob/97f6ceb27b918bfae99dcc46ebdda5a1d8c55f47/modules/core/src/annotations/template_config.js#L3))
- actually we use it to specify "a list of routes", not "a route config"

Proposed name: `@Routes`
- one word
- have a correct meaning ("a list of routes")

Example:

```ts
@Component({
    selector: 'some-component',
    template: '<router-outlet></router-outlet>'
})
@Routes([
    {path: '/', redirectTo: ['/Home']},
    {path: '/home',  as: 'Home',  component: Home},
    {path: '/stats', as: 'Stats', component: Stats},
])
class SomeComponent {}
```

@btford @mhevery @IgorMinar 

**PS** Of course `@RouteConfig` should be deprecated, not removed.

**Comment by nosachamos** [comment]
I like this :+1:

**Comment by PascalPrecht** [comment]
I wouldn't say that `RouteConfig` makes no sense at all, but I like your proposal as it's to the point.

Wonder if that somehow collides with existing imperative counterparts in the router APIs.

**Comment by IgorMinar** [comment]
We are rethinking the whole routing api. So this will definitely change we
just don't have all the details figured out. Stay tuned.

**Comment by ewinslow** [comment]
@IgorMinar anywhere we can follow along with the api-rethink?

**Comment by thelgevold** [comment]
Very interested in learning more about the rewrite of this as well... :-)

It may not matter if the feature is totally changing, but I like the name RouteConfig over Routes since the section is more than just "routes". It also defines stuff around the routes like which component to load, how to instantiate the components (lazy loaded etc.)

**Comment by PascalPrecht** [comment]
Now that @thelgevold pointed it out, `@RouteConfig()` make indeed more sense.

**Comment by ericmartinezr** [comment]
I think @alexpods has a very good point here. I don't know if there's a point though on discussing the naming (good lord, not again) right now since this may change. Anyway, there it goes my opinion : ...

`@RouteConfig` sounds to *configuring ONE route* (Route vs Routes). To be technically speaking correct I think this should be something like 

```typescript
@Routes([
     new RouteConfig({ ... }), // currently it can be '{ ... }' or 'new Route({ ... })'
     new RouteConfig({ ... }),
     new RouteConfig({ ... }),
     ...
])
```
Because actually `@RouteConfig` is just holding an array of configurations but it's not configurating nothing by itself (just passing the array of configurations to the component), in fact the configuration is being made in each object.

**Comment by fxck** [comment]
I'm also interested in any information about the api rethink..

**Comment by wardbell** [comment]
Had the discussion with the author: `RouteConfig`, `RouterConfig`, `RoutesConfig`.  There are arguments for all three. IMO, the most important thing is that it is clear about what it does ... and I believe it succeeds in that respect.

No need to freak about the new API, currently a gleem in Igor's eye.  It will **supplement** the existing *link parameters array* ... as I understand the plan.  We're striving to avoid big breaking changes.

We'll see.

**Comment by IgorMinar** [comment]
@fxck @ewinslow @thelgevold check out:

https://docs.google.com/document/d/1IKZLXU9Y3zdnedj5M7LfW5HQEDf9zyVjNpk_79Rf3SQ/edit?ts=56611fd1

there are still issues with that design that I need to resolve.. but I think the problems are solvable and the design is much better than what we currently have.

**Comment by thelgevold** [comment]
Hm.. Interesting idea. 

One thing I prefer about the current design though is that the components are completely decoupled from the routes. In fact the components have no knowledge about being part of a router configuration at all. This means the component is agnostic of the caller, whether it be a route, a template include or a unit test.
In your new design I see that the specific routes for a given component are injected into the component and tightly coupled to the component's implementation. 

Anyway, just my initial reaction.

**Comment by jimulle** [comment]
@IgorMinar, version 2 in your google doc looks very nice. It is a lot clearer than the current implementation IMO. I am very interested in seeing how these changes to the router progress.

**Comment by thelgevold** [comment]
@IgorMinar 
I am actually curious about what short comings of the existing router you are trying to address with this new router implementation. After working with the existing router for a while now, I am actually very happy with it. It's very to the point and actually reminds me a bit of the DurandalJS router from back in the day :-)
The only thing I don't like about it is the array format for creating links in html. However, a radical shift like this feels like a "cure that is worse than the disease" though.

I really don't like the circular dependency where the component depends on a route which in turn depends on the component.
Slightly verbose too with more JavaScript code in the view (e.g. ```userRoutes.user.url(3)```)

This approach breaks with all router designs I've seen so far, so maybe there is some amount of risk involved with this as well? The existing router config is for the most part just plain ES5 JS, but the new proposed syntax will vary to some degree across different environments. 

I am generally skeptical of major rewrites, late in the game, unless tremendous value is added. So far I am not seeing the need, but am hoping you can share some of the major reasons around the decision.

**Comment by fxck** [comment]
DI in `CanActivate` https://github.com/angular/angular/issues/2965#issuecomment-152286223 amongst other things.

**Comment by IgorMinar** [comment]
That and I'm really not happy the router-link syntax.

In the new design the route is a thing that you have a reference to which
gives us a place to expose apis for listening on events like route change.
Additionally it allows us to have all the route information covered by the
type system which allows us to do error checking and auto completion in
IDEs.

**Comment by thelgevold** [comment]
I think with this we run the risk of putting to much logic/responsibility on the router and risk creating applications with unnecessary dependencies on Angular 2 (and its router). I get how it's nice to tie a general authentication check to the router, but I think that should be done as a general request validation mechanism - not at the component or individual route level. 

Secondly, I don't like the idea of running specific canActivate logic in each component to govern the routes/links. In my opinion this is better suited for custom logic running outside the router. This will ensure that that logic is decoupled and free of router dependencies. Year from now, porting a solution that relies heavily on a very specific router implementation does not seem desirable. Unit testing seems more challenging as well.

**Comment by IgorMinar** [comment]
Routable components are not reusable components unless they are built as
routable reusable components. So the fact that they are tied to the router
is already unavoidable. We might as well take a full advantage of the tie
in.

**Comment by wardbell** [comment]
@thelgevold I am highly sympathetic to your point here
> components are completely decoupled from the routes
I re-read @IgorMinar proposal and I don't see the dependency that you see. Specifically, I don't see router logic creeping into the component.

I'm talking about the component which is the leaf destination of a route, such as `HeroListComponent` and `HeroDetailComponent`. Those should be free of route configuration.

Perhaps you're worried about the "Routing Component" - the component that has an attached router, typically attached with `RouteConfig`.  That component has no purpose other than to facilitate routing. It's not reusable in some other system and, IMO, shouldn't have much going on.

Maybe I misread Igor's spec.

As for the problems addressed, Igor enumerated them and I'll repeat here:

# Why is this better?
- no need for custom DSL
- no ugly arrays bound routeLink in templates
- no magic strings
- static type check of both template and imperative code
autocompletion works
- canActivate is part of RouteConfig class so we avoid the awkwardness with static class hook
route config points to the component and not the other way around, so we can reuse a component across multiple routes
- route config can now be in a separate file which will make scaffolding easier and component class files shorter
- due to static nature we have more opportunities for code gen (speculative)

I agree with many that `routerCanActivate` should provide information necessary to re-route AND preserve the original intended route for a future re-try.

**Comment by thelgevold** [comment]
It's possible that I lack some context here or have misunderstood some of the intentions.

I guess the part I dislike is that the router configuration is bleeding into the class part of the component and creates a coupling at that level. 

Consider the current example (old way):
```
@Component(
{
    selector: 'demo-app',
    templateUrl: './demo-app.html',
    directives:[DemoPage, About, ROUTER_DIRECTIVES]
})
//The entire router config is an independent block and not inside the implementation class
@RouteConfig([
    new Route({path: '/', component: About, name: 'About'}),
    new Route({path: '/demo/...', component: DemoPage, name: 'Demo'}),
    new AsyncRoute({
        path: '/lazy',
        loader: () => ComponentHelper.LoadComponentAsync('LazyLoaded','./components/lazy-loaded/lazy-loaded'),
        name: 'Lazy'
    })
])

//No router knowledge beyond this point unless you want to use the router/location objects directly for //specific reasons
class MyDemoApp {
}
```

The class portion, which I consider the heart of the component, is agnostic of how it's used. Router, unit test, what have you.... The example in the design doc creates two classes with circular dependencies which seems a bit odd to me. I also like how the current routerConfig acts as a summary of all the routes at this level.

**Comment by otodockal** [comment]
It's definitely better to write JavaScript in expression part (and get all the benefits) than DSL. I pointed here https://github.com/angular/angular/issues/5445#issuecomment-159841054 month ago, so I prefer this change.

**Comment by thelgevold** [comment]
The other question I have. Since the component takes a specific route class as an argument. How will the same component map to multiple routes since it would likely need two different route classes?

**Comment by laco0416** [comment]
@IgorMinar :+1:  new router design is so cool and very easy to understand.

**Comment by ericmartinezr** [comment]
@IgorMinar the docs says that that proposal won't be implemented. Is there a new doc we can take a look at with the new proposal/thinking about router?

**Comment by ps2goat** [comment]
Should this be closed with it being renamed to `@Routes` in RC?

**Comment by mhevery** [comment]
yes closing
