### ISSUE TITLE
Directive selector fails to match [attribute*=value]

### ISSUE THREAD

**Issue by jardilio** [angular/angular#6042]
Per the docs:

https://github.com/angular/angular/blob/master/modules/angular2/docs/core/02_directives.md 

CSS selector Attribute contains value: [attribute*=value] should be supported, however I can't seem to get it to pick up. Exact matches work, but not contains: 

http://plnkr.co/edit/HhDGhBBo30ur9ER8i6aB?p=preview

Added same selectors to main CSS file to show it matching there and apply font colors for each.

**Comment by wesleycho** [comment]
What looks like is happening here is that https://github.com/angular/angular/blob/da9b46a071a3ab5a021e0a57a1e3f81260bfe383/modules/angular2/src/compiler/selector.ts#L258-L308 is only matching against the attribute values when it fetches from the map, and never checks the keys.

One implementation to fix this is to likely store a key map, and try getting the attribute name and `attrName + '*'` (for a relatively quicker fix). Another approach is to perhaps modify how the selector is stored instead of storing `attrName*` in the keys list. This may involve a bit of a refactor to fix this behavior.

Whatever solution gets chosen probably should add consideration for supporting the [various other attribute selectors](https://developer.mozilla.org/en-US/docs/Web/CSS/Attribute_selectors), so this probably needs some thought put into it as to the best path forward.

**Comment by jardilio** [comment]
FWIW this was important to support partial class matching of other libraries to quickly bring them into Angular2 components. 

Since Material2 isn't ready yet, and the original Material project is not compatible with NgUpgrade (https://github.com/angular/material/issues/6336) I figured I look at http://www.getmdl.io/ using a simple Angular2 component selector with [class*=mdl-js-] to automatically initialize MDL JS components during the Angular2 Component lifecycle when they are dynamically added to the DOM. 

Without partial matches, the work around is obviously to write exact class matches, but the issue remains since the document states that this should be supported.

**Comment by MaorZ** [comment]
@jardilio I am trying to do exactly the same thing to use MDL in my angular 2 app but apparently the partial matches is not working for now... So I need to explicitly use an attribute name selector like: `selector: '[MdlUpgrade]'` and add it to all the mdl components in the template...

**Comment by jardilio** [comment]
@maorZ that's a good idea, however I was trying to keep to documented implementation without introducing new undocumented attributes. Until this issue is resolved, I just set the class selector to include all the mdl-js options which is working, however I need to keep updating it when new components are added.

**Comment by pkozlowski-opensource** [comment]
I don't think there is intention to support those types of selectors, but rather throw: #2589
