### ISSUE TITLE
Re-digest a lot (about ten times)

### ISSUE THREAD

**Issue by tjoskar** [angular/angular#6064]
Hi,

If one have a simple component, like this:
```javascript
import {Component} from 'angular2/core';

@Component({
	selector: 'my-app',
	template: `<h1>{{title}}</h1>`
})
class AppComponent {
  get title() {
    console.log('fetching title');
    return 'Angular 2';
  }
}
```
http://plnkr.co/edit/lTVI04OyLkXqjeNzroZm?p=preview

The console get filled with `rendering title` (ten times). Ie. the getter method is called 10 times. Is this by design?

I was expecting two calls to the getter method due to change detection, as in angular 1: http://plnkr.co/edit/OF044j?p=preview 

I understand that Angular 2 is in a early state and that I can't expect great performance (yet) but this feels like a bug?

**Comment by thelgevold** [comment]
I know there has been some issues related to function bindings lately. I guess a getter is ultimately a function so it might be throwing off the change detection.

One way to make it stop is to rewrite it to the following:
```
import {Component} from 'angular2/core';

@Component({
	selector: 'my-app',
	template: `<h1>{{title}}</h1>`
})
export class AppComponent {
  
  title:string;
  
  constructor(){
    this.title = this.getTitle();
  }
  
  getTitle() {
    console.log('rendering title');
    return 'Angular 2';
  }
  
}
```

**Comment by robwormald** [comment]
The question here (or, the one you should be asking yourself is) - *why* do I need a getter here? If its something that's "calculated" - it would be infinitely preferable to (re)calculate and set the property when the changes happen - rather than having change detection actually do the calculation.

**Comment by vicb** [comment]
The previous comments are right, you should not be computing the value each time the change detection  is triggered. 

That being said: you are probably running the code in dev mode (see [enableProdMode()](https://angular.io/docs/ts/latest/api/core/enableProdMode-function.html)) meaning that each time the change detection is triggered there will be two passes: the first pass is the actual change detection and the second pass verifies that change detection has no side effect (the model has not been changed by the CD itself).

For this reason, you'll see half the CD runs in prod mode. That's still too many and there is already a bug tracking this, see #3701. Ultimately there should be only 1 run of the CD in prod mode.

@thelgevold not sure what issues you are referring to. Returning a new string each time should not be a problem because `'str' === 'str'` - it is an issue with Arrays and Objects (because `{} !== {}` & `[] !== []`) and in this case the second CD pass throws. _While returning a new string each time would not alter the functionality it is not efficient, see previous comments_

**Comment by tjoskar** [comment]
@thelgevold: It seems to give the same result: http://plnkr.co/edit/3dIl2Hr59lBPuFMcJXAE?p=preview

@robwormald, @vicb: Yeah, I know; one should not re-calculate the value each time the change detection is triggered but I was curious how many times it was triggered and if one is returning a primitive (like a string) I don't think it should mater if you are using a getter or a property (for the point of view of change detection except for an extra function call). Ie. 

```javascript
class MyClass {
  title = 'hello';
  // should be treated the same as:
  get title() { return 'hello'; }
}
```
 
@vicb, Thanks for the explanation! I will keep an eye on #3701. Is there any plans of implementing one-time binding (as we have in ≥1.3)?
