### ISSUE TITLE
Uncaught Error: Cannot find module "Rx"

### ISSUE THREAD

**Issue by blacksonic** [angular/angular#6066]
I tried to use the UMD built file with Webpack, but the required dependency is with upper case. If i modify it to lower case it works. Might be a typo.

**Comment by robwormald** [comment]
If you're using Webpack, don't use the UMD bundles - they are really for ES5 usage only.

**Comment by blacksonic** [comment]
It is a common practice to skip Babel transpilation on ```node_modules``` directory and it is much easier because it contains router and http also. It is not even necessary to use transpilation with Webpack, not to mention Browserify, it can be written in ES5 style. Which file would you use with Webpack?

Besides that it is still a bug in an UMD module.

**Comment by robwormald** [comment]
the source files in the node_modules are commonJS, they don't need to be re-transpiled, so Webpack can pick them right up.

it's not a bug, its a specific module rewrite so that the ES5 build can rely on the globally loaded version of Rx (which attaches to `window.Rx` ) - rather than importing the modular version.

**Comment by blacksonic** [comment]
Yes im not retranspiling it.
Then it is an umd file not compatible with commonjs? I liked umd files because they were compatible on both sides. It seems that this file is then only compatible with global window objects (because Rx is exported to the global window.Rx), so the umd here is unnecessary, or i dont see the purpose of this file.

Which is the right modular version? Which one should i put behind ```require('angular2')``` ?

**Comment by robwormald** [comment]
if you're using webpack, you should use the files in the root of the npm package, and let webpack bundle them for you. again, the `bundles/angular2.umd.js` files are *only* for ES5 users who include angular2 as a script tag, and don't use modules.

**Comment by blacksonic** [comment]
Then why umd if it is inside a script tag? :)
Lets look at jQuery for example...it exports itself to window.$ and window.jQuery . But if u use it from as an umd package you dont call it require('jQuery') or even $...it has the name jquery with lower case letters. The two names dont have be to identical'.
It would be nice to require with rx lowercase and use the Rx when getting it from the global object.

Thats my problem i dont wanna bundle used libraries with Webpack, i just wanna use them. It is common to skip transpilation on node_modules, considered a good practice also. And with it ES5 users of it can even use it.

I might be blind but i dont see an angular2.js or an index.js in the root directory. Where is that single entry point that i should use?

**Comment by robwormald** [comment]
per the tutorials - `angular2/core.js` and `angular2/platform/browser.js` are the two primary entry points, which is the main reason you cannot use the umd file with require() syntax - multiple entry points. 

Again, you are *not* re-transpiling the angular2 files, they are *already* transpiled to commonJS / ES5. If you are using *modules*, you will use webpack to bundle them.

**Comment by blacksonic** [comment]
I think we misunderstand each other. It completely works with it if you replace it with lower case.

It is much much much easier to use a single entry point from node_modules when bundling for the client.
I see the point that multiple entry points is good to be usable on the server side not only the client side.
But for client side bundling the best solution is to use a single entry point and here comes my problem with commonjs incompatible umd module format.
All the modules are lower case and you can use a shim to transform the upper case to lower case. That is what everyone is doing.

Shall i reopen it as a feature request rather than a bug? Just be open to other use cases outside yours.

**Comment by robwormald** [comment]
> But for client side bundling the best solution is to use a single entry point and here comes my problem with commonjs incompatible umd module format.

This is where we disagree, and why we specifically do *not* provide a single file build for this case. Angular2 is multiplatform, and so we have various entry points, as a single entry point unnecessarily brings in code that may not be needed on all platforms, or may break on platforms it was not designed for. 

You should be using the unbundled source of both angular2 and rxjs if you are using Webpack or other bundling tools. If you opt to use the umd file, you also need to include the global version of RxJS, which exports a global to `window.Rx` - no need to rename or lowercase anything.

To be explicit: the ES6/CommonJS source looks like
```javascript
import {Observable} from 'rxjs/Observable'
```
which transpiles to
```javascript
var Observable = require('rxjs/Observable').Observable;
```
which we rewrite to 
```javascript
var Observable = Rx.Observable
```
so that we don't rely on external module `require` statements. 

If you are using an npm module named `rx` - which is presumably why you think simply lower casing will work (?), you are using the *wrong* module - `rx` is an older version of RxJS, which we no longer support.

**Comment by blacksonic** [comment]
Now it is much clearer :) I was fooled by the renaming of rxjs to Rx.
This is what is insanely confusing:
``` exports["ng"] = factory(require("rx"), require("rxjs/observable/fromPromise"), require("rxjs/operator/toPromise")); ```
The 2 requires in one line that makes assume it is a typo.

**Comment by blacksonic** [comment]
The 2 requires mean the same rxjs?

**Comment by robwormald** [comment]
It's all configured here- https://github.com/angular/angular/blob/master/gulpfile.js#L1140 <https://github.com/angular/angular/blob/master/gulpfile.js#L1140> - but again, its not something you should worry/care about, as its purely an internal detail. These files are only designed for those using angular2 as a global, NOT for those using modules.

**Comment by blacksonic** [comment]
Cool, thanks for the help :)
