### ISSUE TITLE
Angular + CodeMirror + Chromium + Developer Tools => "Aw, Snap!"

### ISSUE THREAD

**Issue by radek-holy** [angular/angular#6103]
Hello,

I'm experiencing a very weird issue. I tried to integrate CodeMirror into my application. I've registered a change listener that emits events via `EventEmitter`. When I start typing into the CodeMirror editor and I hold down a key for about 7 seconds, Chromium with Developer Tools enabled crashes with an "Aw, Snap!" error. Here is the reproducer: http://plnkr.co/edit/Kvd5LkeEdbkiA7WE627J

I wasn't able to reproduce it without a CodeMirror instance. Also the `@Output` decorator seems to be important here. And the Developer Tools must be enabled. Also I could not reproduce it without Angular. And last but not least, it's specific to Chromium. Firefox does not crash.

Versions of affected components:
Angular 2.0.0-alpha.45 as well as Angular 2.0.0-beta.0
CodeMirror 5.10.0
Chromium 46.0.2490.86 as well as Chromium 47.0.2526.106

Please let me know if I can provide more data. If it turns out that this is a Chromium bug, I would be glad if you could give me a simpler reproducer which I can post there (I mean, you know what happens in Angular).

**Comment by robwormald** [comment]
Interesting. I can consistently reproduce this on Chrome 47 (only with DevTools open), OS X 64-bit. It does appear to be fixed in Chrome Canary though (49.0.2600.0 canary) - Devtools feels more responsive in Canary generally. Can you confirm that on your end?

Spooky bug though, and nice reproduction.

General advice - this sort of thing (holding down a key nnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnn) is gonna thrash whatever you run it through, Devtools crashes or no! It'll work, but you might want to consider leveraging an Observable here just to throttle the output so its not firing at a ridiculous rate:

``` typescript
import {Observable} from 'rxjs/Observable'
import 'rxjs/add/observable/fromEvent'
import 'rxjs/add/operator/throttleTime'

//as you were doing
let editor = CodeMirror.fromTextArea(this.field.nativeElement);

//wrap into an Observable
let changes = Observable.fromEvent(editor, 'changes');

//throttle and pipe into event emitter (16ms is roughly 60fps)
changes.throttleTime(16).subscribe(modelChanges);

```

I assume in your proper app you're doing this as a standalone component, so you could wrap all this stuff nicely in there.

**Comment by robwormald** [comment]
demo of above http://plnkr.co/edit/peludnTqLuTyvtUqDpeU?p=preview

**Comment by radek-holy** [comment]
Thank you very much for your response and for the tip! I guess I'll suggest implementing it directly to CodeMirror.

Canary does not seem to be available for Linux but I can confirm that I cannot reproduce it on Chrome 49.0.2593.0 dev. Actually it's OK even on 48.0.2564.48 beta. But I cannot reproduce it on Chrome 47.0.2526.106 (the same version as my failing Chromium) as well. I am not sure what it means...

Unfortunately I failed to find beta/dev releases of Chromium for OpenSUSE. I'll report back as soon as I notice an update.
