### ISSUE TITLE
Services Tutorial broken for "getHeroesSlowly()"

### ISSUE THREAD

**Issue by khuezy** [angular/angular#6104]
Hi, please closed if fixed/dupe/etc

https://angular.io/docs/ts/latest/tutorial/toh-pt4.html

```javascript
this._heroService.getHeroesSlowly().then(heroes => this.heroes = heroes); // typescript compile error
 "Type '{}' is not assignable to type 'Hero[]'"

this._heroService.getHeroesSlowly().then( (heroes: Hero[]) => this.heroes = heroes); // ok
```

Why does 'getHeroes()'s  promise callback not required to cast the type and 'getHeroesSlowly()' does? Thanks!

**Comment by neilyoung** [comment]
I think the tutorial is wrong here, maybe because it has been forgotten or is not finished yet? Subsequent sections are missing as well. 

In order to fix this bug you need to declare the Promise to return a "Hero[]" by using generics:

    getHeroesSlowly() {
        return new Promise<Hero[]>(resolve =>
            setTimeout(()=>resolve(HEROES), 2000) // 2 seconds
        );
    };

**Comment by ederkley** [comment]
Further to above if you are implementing the **getHeroesSlowly()** function then also note that the *hero.service.ts* file needs the following line added to the Imports:
`import {Hero} from './hero';`
Otherwise, the `return new Promise<Hero[]>...` code doesn't recognise *Hero* as a valid type.
This seems to be assumed during the tutorial as it appears in the final code example at the bottom of the page but is not explicitly mentioned.

**Comment by michalstepien** [comment]
Hi, can we close?
