### ISSUE TITLE
Proposal: StyleRef API

### ISSUE THREAD

**Issue by laco0416** [angular/angular#6120]
# Motivation
Currently, to modify a style of my component, I must use `ElementRef` and `Renderer`.

```ts
@Component({
  selector: 'element-a',
  template: `
    <span>Element A</span>
  `
})
class ElementA {
  
  constructor(elm: ElementRef, renderer: Renderer) {
    renderer.setElementStyle(elm, "display", "block");
    renderer.setElementStyle(elm, "background-color", "#FFF");
    renderer.setElementStyle(elm, "padding", "5px");
  }
}
```

This works well. But I think this is not intuitive. 

# Goal
* Provide easy way to access to the component itself styles.
* Intuitive API

# Proposal
I propose an idea: `StyleRef`
`StyleRef` accesses to styles of the component itself directly.

```ts
@Component({
  selector: 'element-b',
  template: `
    <span>Element B</span>
  `
})
class ElementB {
  
  constructor(style: StyleRef) {
    style.display = "block";
    style.padding = "5px";
    style["background-color"] = "grey"; 
  }
}
```

This is simple and very intuitive. 

I want your feedback! Please let opinion!

**Comment by laco0416** [comment]
Plunker: http://plnkr.co/edit/BfjnUoT5qABTw8jv7ZL1?p=preview

**Comment by alexpods** [comment]
To modify a style of your component you can create bindings to the host style properties:

```ts
@Component({
  selector: 'element-a',
  template: `
    <span>Element A</span>
  `,
  host: {
    '[style.display]': 'hostDisplay',
    '[style.background]': 'hostBackground',
    '[style.padding]': 'hostPadding'
  }
})
class ElementA {
  hostDisplay = 'block';
  hostBackground = '#FFF',
  hostPadding = '5px'
}

```
See [this plunk](http://plnkr.co/edit/hUlPJRpxmZz8NqlEsb6n?p=info)

**Comment by laco0416** [comment]
@alexpods Yes, `host` property is useful for specific(fixed?) styles. but this is what I want.

```ts
@Component({
  selector: 'element-a',
  template: `
    <span>Element A</span>
  `,
  host: {
    '[style]': 'style',
  }
})
class ElementA {
  style = {
    display: 'block',
    background: '#FFF',
    padding: "5px"
  }
}
```

I want to handle a style as Object.

Thanks.

**Comment by alexpods** [comment]
Use [`NgStyle`](https://github.com/angular/angular/blob/master/modules/angular2/src/common/directives/ng_style.ts#L63) for this.

**Comment by tenowg** [comment]
NgStyle doesn't work so good when adding dynamically loaded components.

**Comment by laco0416** [comment]
@alexpods NgStyle cannot handle component own style.

**Comment by shlomiassaf** [comment]
@laco0416 ,

The current implementation using `host` is quite the same to your proposal.

Current:
```
@Component({
  selector: 'element-a',
  template: `
    <span>Element A</span>
  `,
  host: {
    '[style.display]': 'hostDisplay'
  }
})
class ElementA {
     display = 'block';
}
```

Your proposal is the same but instead of setting a property on the instance you use an object to set the styles in the constructor.

It even reduce usability as it does not provide built in change detection and one will have to do it manually.

I suggest maybe to build a wrapper for both ElementRef & renderer that will handle it.
You can init it by send both object to it.

Or, it might be possible that you just require the new provider I suggested as an injectable, since it should have the same injector as the component it might be possible that the new provider will get ElementRef and Renderer using DI in its constructor..
Worth a shot.

**Comment by zoechi** [comment]
related to #6274 I guess

**Comment by pkozlowski-opensource** [comment]
Closing based on https://github.com/angular/angular/issues/6120#issuecomment-168373563
