### ISSUE TITLE
Http: should return status code / text properly from errors

### ISSUE THREAD

**Issue by robwormald** [angular/angular#6138]
Currently defaulting to the base, which is incorrect for network errors (CORS, etc)

**Comment by robwormald** [comment]
This issue was moved to angular/http#54

**Comment by robertjd** [comment]
It seems that HTTP development has moved back to this library, and that this issue should be re-opened.  The mentioned problem still exists: if the browser aborts the XHR request because of a security or network error, the error that is thrown is actually a response object. 

I haven't jumped into debugging yet, but the site to inspect seems to be here:

https://github.com/angular/angular/blob/master/modules/%40angular/http/src/backends/xhr_backend.ts#L61

**Comment by kim222** [comment]
Is this the cause?
https://github.com/angular/angular/blob/master/modules/%40angular/http/src/backends/xhr_backend.ts#L82 the status is not being included in the ResponseOptions (this is the first time I've looked at the source code so may be way off track).

This stops us from being able to use Angular 2 (need to know the difference between a 500 and 401!) Please reopen and fix :-)

**Comment by Gabriel0402** [comment]
+1

**Comment by Antwnis** [comment]
I would categorize this one as a P1 bug

    this.http.post('http://localhost:8080/user/login', body, {headers: contentHeaders})
      .subscribe(
        response => {
          // ...
        },
        error => {
            console.log(error.status); // This comes back with 200 !!!!!!!!
        }

**Comment by navmishra** [comment]
Hi,

   I don't seem to still see HTTP error status codes being set. I'm using Angular 2 RC4. This was apparently earlier fixed in RC3 .
(original issue here: https://github.com/angular/http/issues/54) but, even when using RC 4, it doesn't seem to be set. The browser shows the request all right:

**zone.js:101 POST https://someinvalidadress:5448/login? net::ERR_NAME_NOT_RESOLVED**

but the http observable error object look like this:

```
Response {_body: ProgressEvent, **status: 0**, ok: false, statusText: "", headers: Headers…}
_body:ProgressEvent
headers:Headers
ok:false
status:0
statusText:""
type:3
url:null
```
The error handling code is the same as on the developer guide: https://angular.io/docs/ts/latest/guide/server-communication.html#!#error-handling

How to get hand on the exact HTTP error code? Does anybody has got it working?

Thanks in advance and regards

**Comment by binarious** [comment]
@navmishra Some browser events do not result in a status code: http://stackoverflow.com/a/14507670

**Comment by navmishra** [comment]
Thanks. So how to distinguish between/identify these HTTP error conditions using Angular2? I don't seem to be getting other HTTP status codes such as 404, 500 and others which I get fine using jQuery AJAX. Does it require getting access to the XhrBackend?

**Comment by schmorrison** [comment]
I am curious about this too.
I am trying to indicate in an angular2 app that an API server is unavailable, but am receiving a `net::ERR_NAME_NOT_RESOLVED` in chrome which doesn't execute success, error, or complete for my observables.

That error also doesn't seem to effect timeout or retry parameters on an http.get request.

Has anyone found a way to see those events?

Schmorrison

**Comment by cokolocko** [comment]
The error is still a big issue and was not fixed!

Please reopen this issue. 

 @robwormald marked the issue as closed :
This issue was moved to angular/http#54"

However, the provided link is not available.

**Comment by JohannesRudolph** [comment]
This should indeed be fixed and reopened. There's two problems I see right now (using angular 4.3.1): 

- network errors showing as status code "0" instead of something more sensible (e.g. an error that says network or cors preflight error)
- all responses show statusText "OK" even if it's e.g. a response status code 400 where it should be "Bad Request"

**Comment by curronieto** [comment]
Using angular 4.4.6, the problem persists. I see that error handling works properly for some status codes (401, 500...). But for others, like 407 it doesn't work properly: it seems that zone.js catch the error (in the console appears the description) and passes to service an error like as @JohannesRudolph has described (with status code 0). 

I think this behaviour should be fixed and reopened, as the previos comment says. Thanks!
