### ISSUE TITLE
@Host can not impot from angular2/core

### ISSUE THREAD

**Issue by webnobushi** [angular/angular#6139]
http://plnkr.co/edit/LKO4XxsIDjhfVrxltqPk?p=preview

EXCEPTION: Cannot resolve all parameters for Child(@Host()). Make sure they all have valid type or annotations.

**Comment by pkozlowski-opensource** [comment]
There were 2 separate issues in your plunker:
* `Host` imports alright but `HostService` did not (you can verify by putting a log statement just after the imports to print out imported values). I suspect that this is due to cycles in imports but didn't dig into it.
* To expose services to directives used in a component's template you need to use `viewProviders` instead of `providers`. I suspect that we might have a broken code examples somewhere and for sure we should add proper documentation for `providers` in https://angular.io/docs/ts/latest/api/core/ComponentMetadata-class.html

Here is a working plunker showing what I believe you wanted to achieve: http://plnkr.co/edit/o8KcpS0x1OXHb1IkuVma?p=preview

**Comment by pkozlowski-opensource** [comment]
I believe that the only actionable item here is the documentation update.
