### ISSUE TITLE
HTTP headers should be case-insensitive

### ISSUE THREAD

**Issue by angexis** [angular/angular#6142]
The current (2.0.0-beta.0) implementation has got case sensitive HTTP headers (```Headers.get('Foo')``` does not return the same as  ```Headers.get('fOO')```).

However the HTTP spec http://www.ietf.org/rfc/rfc2616.txt (section 4.2) is quite specific that the header keys should **not** be case sensitive.

**Comment by robwormald** [comment]
yup, agreed.

**Comment by alexanderchr** [comment]
Agreed.

Doing this is a bit harder than it seems because it must be possible to send cased headers as some interfaces require it. This makes the tempting solution to downcase all keys unworkable.

IMO the headers should behave like this:

If i set a header 'fOO', and then set a header 'foo', the former should be replaced.
If i set a header 'fOO', and then append a header 'foo', the values i appended should be appended to 'fOO'.
If i set a header 'fOO' and then delete 'foo', 'fOO' should be deleted.
If i set a header 'fOO' and then get the header 'foo', the values of 'fOO' should be returned.

This way setting cased headers is possible while still confirming to the spec.

**Comment by robwormald** [comment]
There are two scenarios to cover here:
- retrieving headers from responses 
- setting headers on requests

The first is relatively straightforward - the Fetch specification appears to lowercase them all, and that works fine for retrieval as its simple to lowercase a key when its used - eg headers.get('Foo') -> 'foo' 

For request headers, it appears the Fetch spec (and both Chrome and Firefox, that implement it natively) always lowercase the key. That would make sense per the http spec in the original post, but doesn't work for:
> it must be possible to send cased headers as some interfaces require it.

I don't think that's possible with the native implementation of Fetch, and would seemingly violate the originally quoted spec as well. IMO it would be a Bad Idea to deviate from that spec'd behavior.

cc @jeffbcross - thoughts?

**Comment by robwormald** [comment]
This issue was moved to angular/http#53

**Comment by ManuelRauber** [comment]
@robwormald Would it be possible to reopen this? The referenced issue (https://github.com/angular/http/issues/53) is an a inactive repo and this one here is closed. :)

**Comment by zoechi** [comment]
@ManuelRauber the issues are maintained in the http repo. Development will be moved as well eventually.
