### ISSUE TITLE
Router Huge Flaw - Does not allow more than 1 level of nesting

### ISSUE THREAD

**Issue by pdeva** [angular/angular#6204]
The angular 2 router currently does not allow more than one level of nesting.

If you have a structure like:

/users/profile/detail

you cannot link to /users/profile since the router config doesnt allow creating/linking to non-terminal routes.Thus more than 1 level of nesting is not possible.

This is a huge flaw and makes angular 2 unsuitable for anything more than a toy application.

**Comment by pdeva** [comment]
Putting some code to demonstrate this:

Lets say we have these 3 route configs:

```
@RouteConfig([
	{path: '/users/...', component: UsersComponent, as: 'Users'},
])
class AppComponent {}

@RouteConfig([
	{path: '/profile/...', component: ProfileComponent, as: 'Profile'},
])
class UserComponent {}

@RouteConfig([
	{path: '/detail/...', component: DetailComponent, as: 'Detail'},
])
class ProfileComponent {}
```

You cannot do
```
<a [routerLink]="['/Users/Profile']"></a>
```

as this will result in an error.

This makes the angular router useless for real-world scenarios.

**Comment by brandonroberts** [comment]
@pdeva your router link is invalid and you either need to set a terminal route

```js
@RouteConfig([
    {path: '/users/...', component: UsersComponent, as: 'Users'},
])
class AppComponent {}

@RouteConfig([
    {path: '/profile/...', component: ProfileComponent, as: 'Profile'},
])
class UserComponent {}

@RouteConfig([
    {path: '/detail', component: DetailComponent, as: 'Detail'},
])
class ProfileComponent {}
```

```html
<a [routerLink]="['/Users', 'Profile', 'Detail']">Profile</a>
```

**Comment by machi1990** [comment]
You could also add another root-path ('/') as the terminal root for the needed behaviours. And of course  another component to serve this new added root-path.

**Comment by brandonroberts** [comment]
Here is an example plunkr: http://plnkr.co/edit/v1Np3niVn3WNTZBvHQLf?p=preview

**Comment by pdeva** [comment]
@brandonroberts  your plunkr only proves my point.
try rendering just /user without rendering '/profile'. not possible

**Comment by pdeva** [comment]
@machi1990 that works for only 1 level deep behavior.
try showing an example with 2 levels deep. not possible

**Comment by pdeva** [comment]
@brandonroberts 
> @pdeva your router link is invalid and you either need to set a terminal route


i know. that is what i am getting at.
if i want to just link to '/users/profile' that is not possible since that is a non terminal route.

**Comment by brandonroberts** [comment]
@pdeva yes, you can't nest routes to infinity, it has to end somewhere.

http://plnkr.co/edit/v1Np3niVn3WNTZBvHQLf?p=preview

**Comment by pdeva** [comment]
of course, and i want to navigate to just the 2nd level in a 3 level route.
you keep pointing to that plunker even though it has only 2 level nesting.

**Comment by brandonroberts** [comment]
@pdeva it can keep going. Check again: http://plnkr.co/edit/v1Np3niVn3WNTZBvHQLf?p=preview

**Comment by pdeva** [comment]
it seems you are not even reading what i am saying so i will stop

**Comment by brandonroberts** [comment]
@pdeva I see what you mean. Your path doesn't have to be one segment

```js
@RouteConfig([
    {path: '/user/profile/detail', component: ProfileComponent, as: 'Profile'}
])
class AppComponent {}
```

**Comment by joyeusenoelle** [comment]
@pdeva Goodness. Try communicating instead of throwing tantrums. 

You want /users to give, say, a list of users.
You want /users/profile to give a brief profile of a specific user.
You want /users/profile/details to give a detailed profile of a specific user.

But Angular 2 only provides code for a single endpoint: either /users, OR /users/profile/, OR /users/profile/details, which does not fit the use case you want. What can be done to resolve this?

**Comment by CaptainCodeman** [comment]
I don't think @pdeva is throwing tantrums, he's simply trying to explain the issue he's having which I've come up against too.

As much as I'm loving Angular2 the router part of it seems to be quite weak right now especially if you're coming to it from using something like ui-router. Some of it is probably a learning experience where we just need to adopt some different approaches to achieve things but some seems to be features lacking or not working how you would expect.

Hopefully the feedback on these features can help fill the gaps.

**Comment by NetanelBasal** [comment]
+1

**Comment by iksose** [comment]
@joyeusenoelle sounds about right. I found that a bit jarring that, as I was doing a test migration from 1.x w/ ui-router to 2x w/ the component router. Not really sure what users feedback @btford was using as a use case. Though apparently, if I'm actually remembering this being said and not making shit up, they used internal feedback from the google projects who were migrating (ie the google fiber webapp). So maybe there's a valid reason for not supporting this.

**Comment by brandonroberts** [comment]
@iksose maybe I'm missing something. You want to be able to display a 2nd level route without displaying a 3rd level route if its nested?

**Comment by CaptainCodeman** [comment]
There seems to be a basic philosophical difference of approach with the new router vs ui-router. While ui-router seemed to be able to adapt to pretty much any format of URL and so handle existing structures better, the new component router definitely wants to be in charge and define the URL format that has to be used.

This is probably fine if you're developing an app, especially for internal use, but when you have more of a 'website' app with existing URLs you want to maintain it can feel like trying to swim upstream at times.

Seemingly basic URL features such as fragments and querystring parameters don't seem to be supported right now which is a little disappointing and will hopefully be resolved soon but right now it adds to the frustration and I'm writing so much code to handle URL parameters that I start to wonder what exactly the router is really giving me.

Maybe it's a lack of substantial examples or documentation and once these come along things will be easier. I have tried using examples from the unit tests though and they don't seem to work when changed just slightly.

Sorry if this sounds a bit like a rant but I'm just trying to explain some of the frustrations that I think some of us are experiencing that are really holding back adopting Angular 2 and chipping away at confidence in it.

**Comment by brandonroberts** [comment]
@CaptainCodeman query params are supported. You are correct that they are not documented very well outside of the unit tests.

```js
@Component({...})
@RouteConfig([
    { path: '/', component: HomeComponent, name: 'Home' }
])
class AppComponent {
}

@Component({...})
class HomeComponent {
    constructor(params: RouteParams) {
        console.log(params.get('id');
    }
}
```

```html
    <a [routerLink]="['/Home', {id: 12345}]">Home 12345</a> <!-- will navigate to /?id=12345 -->
```

If you want more practical examples. See here: http://plnkr.co/edit/Bim8OGO7oddxBaa26WzR?p=preview

**Comment by iksose** [comment]
That's a great plnkr, wish it was in the docs/on the site. Could have used it when the beta came out :relaxed:

**Comment by zoechi** [comment]
Fragments are also supported with HashLocationStrategy, probably not in combination with PathLocationStrategy though.

**Comment by thelgevold** [comment]
I am not sure what the plans are for supporting this going. However if we are trying to use routes like

```/user/profile``` vs ```/user```

It seems to me like we are trying to use the 'profile' part as a parameter, so why not just use a route param here instead then? You can then toggle the leaf detail component based on the existence of the parameter. Basically just bind a flag to hide or show the details based on the url/route param?

Something like /user/?id=12345 if you want the details or just /user if you don't want the actual user info.
That way user is a terminal route always, but it contains info to turn it on or off.

**Comment by born2net** [comment]
if you want to see an example of parent and child router and params see:

http://ng2.javascriptninja.io and source at: https://github.com/born2net/ng2Boilerplate

regards

Sean.

**Comment by CaptainCodeman** [comment]
Thanks @brandonroberts - yes, I wasn't clear enough. I know I can use querystrings but it just feels like more work and that the router isn't handling as much as ui-router does (things like default params). Like I said, a lot comes down to having better examples and documentation.

Also @zoechi I wasn't clear that for the fragment I was referring to scrolling down to a particular element (e.g. a post in a topic by having #postid at the end of the URL), not the hash vs html5 strategy for the entire route. Maybe it's the wrong approach but if those are the URLs currently used, I should be able to make the router work with them.

Same with aux routes - why can't I map these to the presence of a querystring if that's what an app currently uses? That's an example if where it feels the router wants to be in charge and we have to fit in with it's way of doing things rather than it being configurable to use the URLs we want.

**Comment by udos86** [comment]
I think there is also a little flaw in the assignment of the "router-link-active" class for deep links. As you can see in @brandonroberts plunker as soon as you select "User" or "Stats" in the top navigation, both links turn red. In my opinion the css should be set only for the actual selected item. 

<img width="146" alt="bildschirmfoto 2016-01-02 um 23 05 56" src="https://cloud.githubusercontent.com/assets/508325/12076294/94767ad2-b1a5-11e5-84b1-8c34ade54dba.png">

**Comment by brandonroberts** [comment]
@udos86 Yea, its a known bug

@CaptainCodeman I understand better what you mean now. The router is still a work in progress and I think it will get better over time.

**Comment by udos86** [comment]
All right, thanks @brandonroberts for the fast reply!

**Comment by slippyC** [comment]
@born2net that is some great work you did there!

I was trying to figure out how to get child routes working, this helped me immensely.  I imagine I will be able to learn more stuff out of this app.

Thanks a bunch!

**Comment by born2net** [comment]
glad to help, I am releasing updates on a daily basis, regards

http://ng2.javascriptninja.io and source at: https://github.com/born2net/ng2Boilerplate

**Comment by wardbell** [comment]
The router documentation describes child routers in great detail. It will discuss query parameters as soon as [PR 637](https://github.com/angular/angular.io/pull/637) is published.

**Comment by thelgevold** [comment]
@wardbell I think your posted link is from a Dev environment. It points to localhost:3000 :-)

**Comment by wardbell** [comment]
You're too fast.  I edited comment to correct that but you beat me to it.

**Comment by pdeva** [comment]
@wardbell can you show how the code I put [here](https://github.com/angular/angular/issues/6204#issuecomment-168274260) can be modified to achieve the desired outcome

**Comment by pdeva** [comment]
@wardbell the link to the live example you posted has the same issue i described.

It puts all the child routes just 1 level down, eg:

```
@RouteConfig([
  {path:'/',         name: 'CrisisCenter', component: CrisisListComponent, useAsDefault: true},
  {path:'/:id',      name: 'CrisisDetail', component: CrisisDetailComponent},
  {path:'/list/:id', name: 'CrisisList',   component: CrisisListComponent}
])
export class CrisisCenterComponent { }
```

The issue is if you wanted say `CrisisDetailComponent` to have a child too, eg `CrisisExtraDetailComponent`, then it is not possible to link to just `CrisisDetailComponent` without linking all the way to `CrisisExtraDetailComponent`.

Here is code showing why:

For the above to happen, the code will need to be modified like this:

```

//note the path to `CrisisDetailComponent` now needs a `/...` at the end

@RouteConfig([
  {path:'/',         name: 'CrisisCenter', component: CrisisListComponent, useAsDefault: true},
  {path:'/:id/...',      name: 'CrisisDetail', component: CrisisDetailComponent},
])
export class CrisisCenterComponent { }

@RouteConfig([
  {path:'/moredetail',         name: 'CrisisExtraDetail', component: CrisisMoreDetailComponent},
])
export class CrisisDetailComponent { }
```

Now you cannot link to `CrisisDetailComponent` from anywhere, you can only link to `CrisisMoreDetailComponent`.

While you may think of adding an 'index' path to `CrisisDetailComponent' like this:

```
@RouteConfig([
  {path:'/',         name: 'Home', component: CrisisDetailComponent, useAsDefault: true},
  {path:'/moredetail',         name: 'CrisisExtraDetail', component: CrisisMoreDetailComponent},
])
export class CrisisDetailComponent { }
```
That is not possible cause angular will complain that `CrisisDetailComponent` is already a target of the route in `CrisisCenterComponent`

**Comment by wardbell** [comment]
I believe the difficulty stems from the desire to make a component simultaneously a Routing Component  (one with `@RouteConfig` and `RouterOutlet`) and a View Component (a leaf in the routing tree).

The routing documentation argues against such a design. It specifically calls for a component to be one or the other but not both.

I believe your troubles would melt away if you defined a child Routing Component ... call it `CrisisDetailRootComponent` ... which only had  `@RouteConfig` and `RouterOutlet` for managing the detail sub-tree. 

Then you define two components, `CrisisDetailComponent` and `CrisisExtraDetailComponent`.  The former is the default and has route path `/`.  The latter can be navigated to and has route path `/moredetail`.

It looks like this:
```
@Component({
  template: '<router-outlet></router-outlet>',
  directives: [RouterOutlet]
})
@RouteConfig([
  {path:'/',            name: 'CrisisDetail',      component: CrisisDetailComponent, useAsDefault: true},
  {path:'/moredetail',  name: 'CrisisExtraDetail', component: CrisisMoreDetailComponent},
])
export class CrisisDetailRootComponent { }
```
*Caveat: I'm only typing this here from memory. I'm sure to have made a typo somewhere.*

I trust you see my point. You may object to dedicating a component to this simple role of "top node" in a routing sub-tree. That's how the router seems to me to be designed.

Play along and it will work.

*Aux routes* are another option that my better suite your use case (or not).  Aux routes don't work yet so you'll have to stay tuned for future announcements on that front.

**Comment by pdeva** [comment]
what is an 'aux route'?

**Comment by pdeva** [comment]
@wardbell even if one were to use a separate routing component we still run into this issue:

a route can have only 1 parent.


Say you have a complex component with multiple tabs resulting in a bunch of routes.

Now, if you were to access than component through more than 1 route, that is not possible.

This is due to the fact that the route is determined statically at startup.
So even if you have say `CrisisDetailRootComponent`, it can only be referenced from 1 component. if multiple components try to route to it, you will once again get the 'target already in use by 'xxx'' error.

Now you have to literally go and copy/paste all your 'routing components' just so they can be called by a different parent.

**Comment by wardbell** [comment]
I'm missing something. What do you mean "a route can have only 1 parent"?  What makes you think "CrisisDetailRootComponent ... can only be referenced from 1 component" or that "if multiple components try to route to it, you will once again get the 'target already in use by 'xxx'' error."

None of these statements are true nor have you produced evidence to show that they are true. I don't doubt that you have created some misbehavior for yourself but you can't just blame the router and make stuff up like this.

I sure hope people reading these accusations aren't believing them.

Please try asking a specific question ... one question at time ... so that we can provide a responsible and effective answer.

And please do so in a separate issue ... or perhaps on stack overflow.  This one has turned into a rant.  I have nothing more to say.

**Comment by Raahul259** [comment]
Hi,

I am trying to Implement a File Explorer App in Angular2.

1. My Home Component will be having a list of Folders and Files. 
2. If I click on Some Folder in the List, then using Clicked Folder's name as query string i should navigate to another component which again having list of Further folder and files inside it and this can continue for some more nested levels.
3. I want each opened folder's path to be visible in url bar (i.e ./Folder1/Folder1.1/Folder1.1.2...so on.)

Folder1
           Folder1.1
                       Folder1.1.1
                       Folder1.1.2
           Folder1.2
Folder 2
-------------------------------------
Can Anyone please help me in achieving this because since component can not be used both as view and router, I am finding difficulty in achieving this because this almost infinite nesting is not allowed.

**Comment by thelgevold** [comment]
Do you need the router for this? Could you use a treeview? 
Example;
http://www.syntaxsuccess.com/angular-2-samples/#/demo/treeview

**Comment by Raahul259** [comment]
Hi, Will this TreeView be able to update the url and could be incorporated with  the use of back button button?

Sorry i am bit new to Angular2

Thanks in Advance.

**Comment by wardbell** [comment]
Please move this treeview question to stack overflow or at least create a new issue.

**Comment by pseisam** [comment]
I'd like to add a usecase which doesn't work with the current prevention of non-terminal route usage:

Let's have an addressbook whose entries are shown in a table. If you click on an entry, you want to show the details of this entry next to the table of entries. 

**http://app/addressbook/:addressbookId** should show the table only (TableComponent with router-outlet)
**http://app/addressbook/:addressbookId/entry/:entryId** should show the table and the details of entry with entryId. (TableComponent + DetailComponent)

This will not work, because http://app/addressbook/:addressbookId will give you the non-terminal route error. Also the DetailComponent in http://app/addressbook/:addressbookId/entry/:entryId  wouldn't even have access to :addressbookId which is another flaw in the current implementation.

**Comment by CaptainCodeman** [comment]
@pseisam it works if you follow the approach described by @wardbell about 8 posts above (having a `CrisisDetailRootComponent` component)

I've got a similar setup - at the top level I have a route:

    { path: '/site/:id/...', component: SiteComponent, name: 'Site', data: { public: false, roles:['admin', '{id}:admin'] } },

That SiteComponent has it's own routes:

    @RouteConfig([
      { path: '',      component: SiteView, name: 'View', useAsDefault: true },
      { path: '/edit', component: SiteEdit, name: 'Edit' },
    ])

Going to /sites/name displays the site
Going to /sites/name/edit shows the edit form

It would be easy to have things show a list instead vs a single item and any common elements can be displayed on the SiteComponent view along with the `<router-outlet></router-outlet>` used to swap in the child components.

**Comment by pseisam** [comment]
@CaptainCodeman
I tried that, but that way I didn't have access to the :id of /site/:id in the SiteEdit component.

**Comment by CaptainCodeman** [comment]
The easiest way I've found to access any parent value is to use a service.

In my case I'm doing an Http request in the `@CanActivate` decorator and setting the retrieved object in a service which is then available to all the child routes. It would be nice if this sort of setup could be streamlined and provided by the router / canActivate lifecycle (I guess 'ui-router style provides').

**Comment by wardbell** [comment]
Take a look also at the router's own [OnActivate](https://angular.io/docs/ts/latest/api/router/OnActivate-interface.html) interface. It describes the router's own component activation hook.

When you implement that method you have access to the previous and next `ComponentInstruction`.

That's undocumented as yet but inspection is both encouraging and disheartening. We can learn about the route we're going to (what is about to be activated) but not the full route that got us here.

That said, we also have access to the current `ComponentInstruction.routeData`.  `RouteData` is a router-scoped property bag that is handed from route to route. It's not hard to add your own info to it in the `routerOnActivate` hook method as you navigate from parent to child. Children can read that `routeData` to pick up information they need.

It's a side-channel within the router itself.

Something to consider.

**Comment by pseisam** [comment]
Ok, nice to see some alternatives for the routing params, thanks.
Now since I didn't remember correctly what was wrong, when using wardbells approach, I just made a new plunker example. See here: http://plnkr.co/edit/PzoKVgbZO0Xx6IE3grnG?p=preview

The main problem was not the ids, but that the table (here not really a table, but you get the idea) and the detail of an entry are not shown at the same time. Maybe that is something that was not clear.
And that is something I think, won't be possible without more nesting levels.

Feel free to fork the plunker to prove me wrong :)

**Comment by chenkie** [comment]
@pseisam @CaptainCodeman one great trick I found from the extensive routing plunk linked above is to use `Injector` to get the `RouteParams` of a parent.

```ts
import {Injecetor} from 'angular2/core';
import {RouteParams} from 'angular2/router';

...

export class UserDetail {
  parentParams: RouteParams;

  constructor(injector: Injector) {
    this.parentParams = injector.parent.parent.get(RouteParams);
  }
}
```
This can be found at `src/UsersHome.ts` here: http://plnkr.co/edit/Bim8OGO7oddxBaa26WzR?p=preview

**Comment by CaptainCodeman** [comment]
That's a handy tip, thanks @chenkie !

@pseisam The `CrisisDetailRootComponent` (the middle-man of the routes) can display other things as well as the `<router-outlet></router-outlet>` for the child routes. That makes it possible to have what you're talking about (master-list / detail view right?). Either display them directly or encapsulate them in another component included in the view.

**Comment by pseisam** [comment]
Also thanks @chenkie 

@CaptainCodeman If I display something in the CrisisDetailRootComponent (resp. TableRootComponent in my plunker) we will be back again to "Link "["TableRoot",{"tableId":23}]" does not resolve to a terminal instruction" errors ;) See here: http://plnkr.co/edit/BdJ11U9I42lIoX7Z1EVB?p=preview

**Comment by CaptainCodeman** [comment]
@pseisam I see what the issue is (I think). The router doesn't know what it's meant to load as the only route has parameters and they are no supplied so there is no route that is active. If this were part of a bigger app then you probably wouldn't hit the issue - there would be routes to load and you'd navigate to the route you want with links. It looks like it's because there are so few routes and none of them match unless the router invented some parameter to use which it can't.

I've tried to fix it and show what I _think_ you are trying to achieve or something close. The top level has a redirectTo route so it doesn't trip up at that level. Then the table detail shows having a component for an unselected state (you could do that for the root as well).

http://plnkr.co/edit/mWckPyTw2c8JFlF6uUlK?p=preview

Hope that helps

**Comment by pseisam** [comment]
@CaptainCodeman Actually (I think) it is the problem that opened this issue (https://github.com/angular/angular/issues/6204#issue-124525910): It is not allowed to link to a child route that also is a parent route.

The instruction is clear: /tableroot/:tableId/ means to load the component tableRoot with the :tableId. That would be totally fine. But the current router implementation forces you to also go the child route of tableRoot, even this isn't needed at the moment (hence the non-terminal route error). This is the core of the problem, this issue was opened for.

Your plunker now works, but at the cost of a workraround with this empty NoneComponent. That is something you don't want to use in productive code, since the NoneComponent would have no use at all in a real world app.

**Comment by CaptainCodeman** [comment]
> It is not allowed to link to a child route that also is a parent route.

@pseisam I think that's incorrect - the last plunker I showed hopefully demonstrates this is not the case. I don't think it's a workaround, it's expected behavior and I think it's unfair to call this an issue with the router itself.

The problem is you have a route of `/tableroot/:tableId/tabledetail/:detailId` but you are not supplying a URL that matches it - that is what the redirect OR the none selected route config provides. You don't *have* to go with the empty NoneComponent - that was just to show the two ways of doing it but if you don't have it then you need a redirect at that level similar to the table root redirect to tell the router where to go if you don't supply the full route (i.e. if you just link to `/tableroot/:tableid`

Without the redirect then the link would need to be in the form `<a [routerLink]="['TableRoot', {tableId:12}, 'TableDetail', {detailId:34}]">`. The none component just allows you to map something to "nothing selected yet" when you only provide the first part.

To put it another way, what route should the router go to if you give it the URL `/tabletroot/123` when the only configured route you have is `/tableroot/:tableid/tabledetail/:detailid`? The none component provides a matching route config (`/tableroot/:tableid`) while a redirect at that level would convert the URL to something like `/tableroot/123/tabledetail/456` so it _would_ match.

I don't know if you can have dynamic parameters in the route config though so the redirect is probably less realistic (unless you load & redirect to the first child in the table root). Of course if you are always linking to the full route then you'd be fine.

**Comment by pseisam** [comment]
@CaptainCodeman
Sorry, but it does not show, that a ParentRoute can be loaded without its child, because you are actually loading the child component:
```{ path: '', name: 'None', component: NoneComponent, useAsDefault: true }``` <-- this is already a child

Also I do not only have the route ```/tableroot/:tableId/tabledetail/:detailId``` I also have the shorter route configured:
In AppComponent my route is configured as:
```{path:'/tableroot/:tableId/...', name: 'TableRoot', component: TableRootComponent}```
Which explicitly says: If only /tableroot/:tableId is given, then go to the TableRootComponent and leave router-outlet empty, since no child route is provided. If also tabledetail/:detailid is given then please also go to the childRoute and fill router-outlet.

I Hope this makes my point better easier to understand.

**Comment by CaptainCodeman** [comment]
@pseisam  I understand what you're saying but I still don't agree with your interpretation of how the child routing works which is what we're disagreeing on - how it works vs how we may like it to work.

> I do not only have the route /tableroot/:tableId/tabledetail/:detailId I also have the shorter route configured

Sorry, I think you do only have one _complete_ route defined, it's just split across a parent / child component. I think the `/...` is meant to mean that it is a parent to other routes to be defined in the child component but I don't think those routes are optional. If you have no route config on the child then it throws a different error - it seems that the expectation is that "/..." means the route definition continues.

The problem is that the route has a parameter and the router can't invent a value for what any parameter should be. If it was parameterless and had a default root then it loads. The empty route effectively says that yes, you do actually have two complete routes configured:

    /tableroot/:tableId
    /tableroot/:tableId/tabledetail/:detailId

You are describing how you want the router to work - that if no route matches any children that the router should leave the outlet blank. I do think this makes some sense but I don't know enough about the router and it's overall design to know if that conflicts with anything else. Should `/tableroot/:tableId` match the URL `/tableroot/123/something-else` for instance? Wouldn't that mean each segment of the route would need to indicate if it was optional or not?

Anyway, it would probably be better to raise this use-case as a separate distinct issue though as it's pretty buried in here.

**Comment by pseisam** [comment]
@CaptainCodeman 
> we're disagreeing on - how it works vs how we may like it to work.

You are right: What I described is how I want it to work. I know that currently the ```/...``` marks a child route, where you also should deliver the childs parameter. But I am only using it, because you can't configure something like:

```
/tableroot/:tableId/...  <-- use if child route is available in url - child param needed
/tableroot/:tableId      <-- use if child route is not avaible in url - child param not needed
```

> Should /tableroot/:tableId match the URL /tableroot/123/something-else

No why should it? Only if a route for ```/tableroot/123/something-else``` is configured it should go there. If there is no config for it, just throw an error.

I think it is ok to leave the problem here, because it would be solved if the problem of the issue opener is solved :-)

**Comment by jeckkech** [comment]
Okay, so we have this child routes and stuff now but... What if I have a multiple sections on a website I want to build this app upon and use PathLocationStrategy at the same time? On angular 1.x you could simply add a state with options like '/.*/article:id/:url' and it would handle urls with multiple segments before 'article:id', it could be both 'section/section/section/article:id' or just 'section/article:id' and what now? Am I supposed to create a Route configuration for each particular case? 
What if I dont care what goes before the "data segment" of the original url and all I need is just this url?

**Comment by schippie** [comment]
I see that this issue has been closed, but i had a question and was wondering if someone had an answer to it for me.

The situation is as follows:

I want the user to be logged in and verify that he is when going to 99% of my applications pages. I can use the `@OnActive` decorator to achieve this. By checking if he is logged in and if not sending him to another Route. 

The problem i am having with this is that it would mean i would have to re-implement this same logic for the 99% since i cannot go deeper as one level with the `@RouteConfig`.

Now my question is is something like this (what is possible in angular 1 using the ui-router) possible:

```
AppComponent
    - /login => LoginComponent
    - /... => BaseComponent
BaseComponent (contains onActivate isLoggedIn Check)
    - /companies/... => CompanyComponent
    - /customers/... =>  CustomerComponent
    - /cities/... => CitiesComponent
CompanyComponent (contains  routeconfig for list, edit and new routes)
    - /list/:pageId => CompanyListComponent  (with useDefault = true)
    - /edit/:id => CompanyEditComponent
    - /new => CompanyNewComponent
```

**Comment by CaptainCodeman** [comment]
@schippie here's one approach you could look into https://github.com/angular/angular/issues/7122#issuecomment-185388662

**Comment by schippie** [comment]
@CaptainCodeman That would answer one of my questions. Though it does not answer the second part that is tied to this:

In almost all of the applications we build the login / forgottenpassword are the only pages that differentiate substantially from other pages. But the other pages generally have a sidebar header and a content area. 

With angular 2 it does not seem possible to have something like this. Where (from my example in https://github.com/angular/angular/issues/6204#issuecomment-188150252 )  the BaseComponent contains this HTML plumbing code + the associated directives. 

Then the only real way would be to have a transcluded component in which you would insert the <router-outlet> which in turn renders the content block within such a page. 
Though i am assuming here that would re-render the entire html page for every page change.

**Comment by CaptainCodeman** [comment]
@schippie yeah, it sounds like you're describing the named views in ui-router. That's what I initially thought the named outlets in component router were but I never got them to work that way (or actually at all).

I've ended up having routed / top-level components that just include the sidebar pieces each time. It's probably just a matter of features or knowhow being developed and discovered.

**Comment by brandonroberts** [comment]
@schippie if you have the @CanActivate decorator on your base component, all child routes under it will be protected by the CanActivate also, so you don't need to put the same logic on every child route under it that you want to protect.

There is nothing stopping you from going deeper than one level with @RouteConfig. The difference is that you have to terminate your route somewhere. You can't end on a `path: '/...'`, which indicates there should be some child routes associated down further.

Here is a simple example: http://plnkr.co/edit/YWyYU9?p=preview

**Comment by schippie** [comment]
@brandonroberts Thank you for clearing that one up :+1: read read your first comment as well think i just had a major derp moment hehe sorry :astonished:

**Comment by cviccaro** [comment]
Is there any way using Angular2 Routing to achieve what A1 ui-router does, namely, child states load and render all of the parent states?  Specifically, my use case, which I can't seem to achieve yet in A2 (but was trivial in A2 with ui-router) is content that is overlaid overtop a page, but loaded via a route.

Example:
State name 'home' at path '/' using say HomeController.  On this page is a button pointing to the route /blogs.
State name 'home.blogs' at path '/blogs' which loads first HomeController and renders it as if we were routing to 'home', but then loads its own BlogsController.  The route also uses onEnter to manipulate the DOM and load another directive which renders overtop the page by sliding it.  Closing this overlay would navigate back to / (state 'home'), without reloading the page or anything, just closing the overlay.

In A2, I am trying to achieve this using the new Component Router. The problem is, as described above, a component is not intended to be used as a ViewComponent and a RoutingComponent.  So now I have..

app.component.ts
`@RouteConfig([
  { path: '/...', name: 'Home', component: HomeRootComponent, useAsDefault: true }
])`

home-root.component.ts
`import {Component} from 'angular2/core';
import {RouteConfig, RouterOutlet} from 'angular2/router';
import {HomeComponent} from './home.component';
import {BlogsComponent} from './blogs.component';

@RouteConfig([
	{ path: '/', name: 'View', component: HomeComponent, useAsDefault: true },
	{ path: '/blogs', name: 'Blogs', component: BlogsComponent }
])
@Component({
	directives: [RouterOutlet],
	template: '<router-outlet></router-outlet>'
})
export class HomeRootComponent {
}`

The problem is I don't want BlogsComponent to be side-by-side with HomeComponent.. I want HomeComponent to load and render first, THEN load BlogsComponent.  Is this possible?

**Comment by brandonroberts** [comment]
@cviccaro yes, it's possible. You need to make your HomeComponent route a nested route component like your HomeRootComponent.

`{ path: '/...', component: HomeComponent, name: 'View' }`

Then add a `@RouteConfig` to your HomeComponent, move your BlogsComponent route there and a `<router-outlet></router-outlet>` to your HomeComponent template.

**Comment by cviccaro** [comment]
@brandonroberts Thanks for the quick response and the help.  In that case, I've simply removed the HomeRootComponent and am left with the AppComponent which has the single @RouteConfig as shown in your post, HomeComponent, and BlogsComponent.  

Inside **HomeComponent**...

`import {BlogsComponent} from './blogs.component';`
`@RouteConfig([`
`	{path: 'blogs', name: 'Blogs', component: BlogsComponent}`
`])`

Inside **home.component.html**:

`.... bunch of markup ....`
`<router-outlet></router-outlet>`

Now, when I goto /, I get a white page and no OnInits are fired (the problem I was getting before when I had attempted this pattern), but if I goto /blogs, I get the HomeComponent rendering as I would expect, with both the Components being loaded (OnInits are firing in both).  Last time I tried this, the BlogsComponent was not being loaded, so this is progress, but I still can't seem to get the base page at path '/' to render.

Thanks again for your help.

**Comment by brandonroberts** [comment]
@cviccaro just add the `useAsDefault: true` to your BlogsComponent route

**Comment by cviccaro** [comment]
Apologies in advance about my quick responses.. I'm sure you have better stuff to do.  In any case..

@brandonroberts Well that works in that it prevents loading a blank page, but it forces /blogs to load, which if I had my overlay wired up would then always display the blogs overlay, and would never allow the root page to be viewed.  I want HomeComponent to be able to render at the base path '/', and only load the BlogsComponent over-top-of HomeComponent when the browser navigates to '/blogs'.  Is this a case for using the lazy-loader aspect of the A2's routing?

**Comment by brandonroberts** [comment]
@cviccaro no problem. I see what you're trying to do now. What you'll have to do is add another route to the HomeComponent `@RouteConfig` that goes to `/`. The A2 router doesn't let you navigate to nested outlets, because they don't end and your route chain has to end somewhere. Nested outlets in A2 are like abstract routes in ui-router.

```
import {BlogsComponent} from './blogs.component';
import {HomeIndexComponent} from './home-index.component';

@RouteConfig([
{path: '', name: 'Index', component: HomeIndexComponent},
{path: 'blogs', name: 'Blogs', component: BlogsComponent}
])
class HomeComponent{}
```

Hope this answers your question. You can also come into the A2 chat if you have any other questions. http://gitter.im/angular/angular

**Comment by cviccaro** [comment]
Thanks @brandonroberts, it does.  That works perfectly, and using [routerLink] directive even loads the BlogsComponent without reloading the page.  Very cool.  Thanks again!

**Comment by brandonroberts** [comment]
@cviccaro Cool :+1:

**Comment by revoxover** [comment]
@brandonroberts
Thank you for all the insights you provide in this thread, It is extremely difficult to find answers to the very common scenario @cviccaro presented and I believe this may be directly related to @pdeva's original question. However, I do not fully understand what just happened in your exchange. I am trying to do something similar (I have a child component that has a dependency on the parent route...very common use case) and it appears that your answer contradicts the "a component should either be a view component or a router component but not both" pattern that is mentioned earlier in this thread. Based on your answer it looks like in order for a child component route to load a dependent parent component (for example when deep linking to the child) the child route must be defined in the parent component making the parent component both a view and routing component.

Also in your final answer to @cviccaro you introduce a new component called "HomeIndexComponent" in order to get the base "/" route to load correctly. It's only purpose seems to be to get the base "/" route to work. I have done the same thing. So in my parent component I have defined an empty child route that points to a completely empty component in order to get the base route to load. 

Is this really correct way to handle this common use case or is this a oversight in the router? If it is a oversight hopefully the Angular team can correct this behavior by perhaps determining that if a component has child routes and the base route is not defined then the component it'self is the base route.

**Comment by brandonroberts** [comment]
@revoxover no problem. Its the correct way to handle it right now. I don't think its an oversight, as I think the router wants you to be explicit about where routes end. You could always point two routes at the same component and show/hide what's necessary based on route parameters if you wanted to, but that has its own drawbacks. If they add the ability to link directly to nested outlets without having a terminating route then you won't have to do it.

**Comment by DrewynV** [comment]
__________________________________

Hi! We just wanted to let you know we receievd your email. Thank you for submitting your request. Our aim is to get back to you within 24 hours at the latest. If you have any additional information to add to your request, please reply to this email.


Also please visit our knowledgebase (http://www.support.magicdust.com.au) to browse for further info, we are adding to it all the time.

Or here is our industry report about the 11 Essentials for a Successful Website (http://www.magicdust.com.au/web-design/.

We look forward to helping you succeed online.

Thanks

The Team @ Magicdust Digital

http://support.magicdust.com.au/

Ph (02) 9979 7474
M-F | 9 am-5:00 pm AEST (AEDT in Summer) excluding Public Holidays

------------------------------------------------------------------------------------------------------------
This message was sent to  reply@reply.github.com in reference to Case #166474.
------------------------------------------------------------------------------------------------------------


[[4e160b31546efdd4aa6c7e4a443fd5adcfa4944b-673073621]]
