### ISSUE TITLE
Router: Navigate to the next/prev item of the piped output.

### ISSUE THREAD

**Issue by rosendi** [angular/angular#6208]
Here is a very simple plunk - http://plnkr.co/edit/ApSsAgUFupUMHSQ3VbWr. The question is: How could a navigation to the next/prev item could be performed? I think that it's a very common scenario, e.g., navigate to the next/prev item after a current one destruction, navigate to the next/prev item using hot keys, etc.

**Comment by zoechi** [comment]
Injecting `Location` and call `back()` / `forward()` on it should work I guess.
Some API from the router for this might be useful as well. 
For example  http://stackoverflow.com/questions/34546270/using-angular2-how-to-redirect-to-previous-url-before-login-redirect

**Comment by rosendi** [comment]
@zoechi Have you seen the plunk? The prev and next items are not the same as the `back()` and `forward()` methods, i.e. the next item is the item that is gone right after the selected item of the dom list. To navigate to that items, I need to know the next `id`, and the prev `id` as well. But, since the dom list order is different to the data service list order, it's non-trivial case, especially with a complex piped output. Is it clear now?

**Comment by brandonroberts** [comment]
@rosendi Seems like you need to store the shuffled set of items so you can use that to find the next,prev item. See http://plnkr.co/edit/ewdUQUiTk6j504XWv8w9?p=preview

**Comment by rosendi** [comment]
@brandonroberts The global variable looks strange there `let shuffledItems: any[];`, isn't it? It makes pipes non-reusable. Have you got another ideas? A plunk isn't necessary, just an proposal how it could be done if it will save your time.

**Comment by brandonroberts** [comment]
I just used the variable to demonstrate storing the result of the
transformed data. I think you could use pass a callback to your pipe to
store the transformed data. The callback would be a function in your
service. Just an idea though.

@brandonroberts <https://github.com/brandonroberts> The global variable
looks strange there let shuffledItems: any[];, isn't it? It makes pipes
non-reusable. Have you got another ideas? A plunk isn't necessary, just an
proposal how it could be done if it will save your time.

—
Reply to this email directly or view it on GitHub
<https://github.com/angular/angular/issues/6208#issuecomment-168338781>.

**Comment by wardbell** [comment]
If I may, there is nothing simple about your plunker example. It's a wildly complicated way to perform a simple task.

IMO your choice of the async pipe approach has lead you astray. You can play games by capturing the list within your shuffle method and stashing it somewhere (as someone has suggested). But you're just adding complexity and mixing up concerns by having your `Item` component handle both item display and navigation of the parent `App` component's list.

There is a much simpler way:  subscribe to the observable within the `App` component and capture the list there. If you're really excited by the async pipe, you can still forward the observable as you do now (I wouldn't).

If you really want to shuffle (why?), do it inside the data service or the `App` component before returning the list. You could as easily shuffle on the observable as anywhere else.

Then you can enrich the `App` component with prev/next methods, and display corresponding links in the `App` template rather than within the `Item` component.

All the best.

**Comment by rosendi** [comment]
@wardbell Thank you for your time. I provided the bad example.

> But you're just adding complexity and mixing up concerns by having your Item component handle both item display and navigation of the parent App component's list.

The issue was to perform a redirection (from the current item component) to a next `Item` in the shuffled items list after the current one destruction.

After a while I realized that I moved to many data logic into the async pipes in the real app, instead of a service. Closing now.
