### ISSUE TITLE
In ngFor, set animate's values inside occur errors.

### ISSUE THREAD

**Issue by kitkimwong** [angular/angular#6252]
In ngFor, set animate's values inside occur errors.		
		
    <circle *ngFor="#c of ControlCircle" 
					[attr.id] = " c.id "
					[attr.r] = "LocationR" 
					[ngStyle]="{'cx': c.x ,
						'cy': c.y
					}">
					<animate dur="3s" attributeName="r" 
						[attr.values] = "30;50;30"
					repeatCount="indefinite"  />			
				</circle>	

		this.ControlCircle = [
			{ id : "AnimatePoint" , x:30  , y: 30 ,  display : false },
			{ id : "StartAnimatePoint" , x:60  , y: 60   , display : false },
			{ id : "EndAnimatePoint" , x:80  , y: 80 ,display : false }
		];

EXCEPTION: Template parse errors:
Parser Error: Binding expression cannot contain chained expression at column 4 in [30;50;30] in MapPage@37:6 ("
					}">
						[ERROR ->][attr.values] = "30;50;30"

Can't use [attr.values] to set animate's values. Cause i want to  use dynamic variables  to set the "values" E.g: [attr.values] = "c.value1; c.value2 ; c.value1"

**Comment by pkozlowski-opensource** [comment]
You are using the `[attr.values]="exp"` which means: "bind _result_ of _exp_ to the _values_ attribute". In this case `30;50;30` is interpreted as the Angular _expression_ - but it it clearly is not one.

If you want to use literal, as your example you can either do `[attr.values]="'30;50;30'"` or just `values="30;50;30"`.

If you want to bind dynamic value from an expression ( `[attr.values]="exp"`) make sure that the `exp` is a valid expression, not a literal.

**Comment by PascalPrecht** [comment]
Couple of things:

1. You're writing `<animate>`'s `values` attribute with `[attr.values]`. Are you sure you don't want to bind to `values` property?

```
<animate [values]="expression">
```

2. As the error states, you can't have chained expressions. As soon as you use property binding syntax (`[prop]="expression"`), the thing you assigning on the right hand side is an expression and `;` are used to chain expressions in some special cases. If you want to pass the thing you're passing as string, you need to put the value in single quotes, because you're writing an expression:

```
<animate [values]="'30;50;30;'">
```

**Comment by PascalPrecht** [comment]
Oh, @pkozlowski-opensource beat me to it haha

**Comment by kitkimwong** [comment]
Thank you guys. That's my fault.
