### ISSUE TITLE
Integrating react components (interface OnChanges)

### ISSUE THREAD

**Issue by rodrigouroz** [angular/angular#6295]
I'm integrating an existing React component (http://facebook.github.io/fixed-data-table) to an Angular2 application.

My working application implies that I reload the React component on each change of an input property in my wrapper component (the table data that comes from an observable), using the interface OnChanges.

Is this the correct way of binding data from Angular to a React component?

Since I'm new to React I was wondering if there was an official documentation from the Angular team on how to do this.

I'm happy to provide a plunker if someone's interested.

**Comment by robwormald** [comment]
I don't know that we'll provide any official documentation, as such, but your basic approach is sound I would say. @Inputs to listen for data changes and @Output to broadcast interval events to the outside world. You could also use a simple setter instead of the `ngOnChanges` lifecycle hook.
`
Or, you know, write it natively in Angular2 ;-)

**Comment by rodrigouroz** [comment]
Thanks, that's what I did.

I can write it natively of course (I did with another component that I'm about to open source and publish in npm), but I was asked to test the integration with React components because I'm pushing for using Angular 2 for a new project where they want to use React and Flux, and they told me that if I prove that React components can be used inside an Angular application they'll go with Angular 2 :-)

I'll check the setter suggestion, haven't thought of that.
