### ISSUE TITLE
Router enhancement: Add state persistent functionality in router

### ISSUE THREAD

**Issue by mkrishna4u** [angular/angular#6334]
If there are parent child views and if we are using the routing for that purpose. From the usability point of view if user navigate from one state to another state then use might like to persist his previous state so that he does not have to perform navigation again to reach that particular state.

For example:
States hierarchy: T1 {PersistChildState: true, ChildState: T1C1(Default), T1C2}, T2 {PersistChildState: true, ChildStates: T2C1 (Default), T2C2}, T3
Steps: 
1. First user navigated to T2C2 state / route by clicking on UI T2 and T2C2 route links
2. Now user navigated to T1C2 state / route by clicking on UI T1 and T1C2 route links
3. Now when user click on T2 then by default T2C2 view should be opened without user intervention. Because i have set PersistChildState true.

if you need more information related to this feature. You are most welcome. This is a very useful concept in client UI.

**Comment by brandonroberts** [comment]
@mkrishna4ua you can accomplish this with default routes. You just need to add `useAsDefault: true` to your desired route.

See example: http://plnkr.co/edit/W7oLRiaQH64MCsAiPrR3?p=preview

**Comment by mkrishna4ua** [comment]
using useAsDefault option that gives the static behavior. But we want the dynamic behavior like if user navigated to another child then it should be preserved.

Another way to state this problem is,  when user launch the application first time then it should use default routing behavior and after navigation it should use the dynamic behavior,

For example if T1 has 2 children C1 (Default) and C2; T2 has 2 children C3 (default) and C4, so when user click on T1 just after launching the application then it will routed to C1 because of default setting. Now user click on C2 then T2 then T1 again then C2 should be opened because user last visited C2 under T1. This is what we call dynamic behavior.

**Comment by vicb** [comment]
Please open a new issue if this is still applicable to the new router
