### ISSUE TITLE
Date Pipe should accept string as input

### ISSUE THREAD

**Issue by oliverjanik** [angular/angular#6336]
Json retrieved from API never contains Date objects. Instead dates are transported as strings. When I run a DatePipe over a string it gives me `Invalid argument '2014-11-20T05:11:03.277+00:00' for pipe 'DatePipe'`

Please note that angular 1 date filter worked just fine with strings.

**Comment by deeleman** [comment]
This is related to the discussion held at [this issue](https://github.com/angular/angular/issues/3917) (and the ones linked from there).

**Comment by levyuk** [comment]
I think it's quite annoying that I have to do this 

new Date('2016-01-21T12:56:16.498Z') | date

instead of this

'2016-01-21T12:56:16.498Z' | date

That date is valid as far as I'm aware. Could we maybe change this function 

export function isDate(obj): boolean {
  return obj instanceof Date && !isNaN(obj.valueOf());
}

to check whether new Date('') is valid also?

**Comment by bohticus** [comment]
Fully agreed! Plus, this isn't working (for me anyway):
    {{new Date('2016-01-21T12:56:16.498Z') | date}}
OR
    <input type='text' [(ngModel)]="new Date('2016-01-21T12:56:16.498Z') | date">

EXCEPTION: Template parse errors:
Parser Error: Unexpected token 'Date' at column 5 in [new Date('2016-01-21T12:56:16.498Z') | date]

Instead I have to do something like this:
    {{ stringAsDate(sampleValue) | date }}
with
    stringAsDate(dateStr) {
        return new Date(dateStr);
    }

**Comment by pkozlowski-opensource** [comment]
Closing as duplicate of https://github.com/angular/angular/issues/3261 which is the same and is already triaged.
