### ISSUE TITLE
Router: child link href is not generated correctly by router

### ISSUE THREAD

**Issue by mkrishna4u** [angular/angular#6358]
Browser: Chrome
i specified routes and links as follows:
TOP ROUTE:
new AsyncRoute({
    path: '/admin',
    loader: () => System.import('app/admin/admin').then(m => m.Admin),
    name: 'Admin'
  })

CHILD ROUTE:
new AsyncRoute({
    path: '/securitymgmt',
    loader: () => System.import('app/admin/security-mgmt/security-mgmt').then(m => m.SecurityMgmt),
    name: 'SecurityMgmt'
  }),

And LINK:
`<a [routerLink]="['/Admin/SecurityMgmt']">Security Management</a>`

On web browser it generates href for link given sbove as follows:
`<a href="#/admin" class="router-link-active">Security Management</a>`

But it should generate href for link as given below:
`<a href="#/admin/securitymgmt" class="router-link-active">Security Management</a>`

Please fix this problem. Thanks.

**Comment by brandonroberts** [comment]
How are you generating the links? Each component is a separate item in the array

```html
    <a [routerLink]="['Admin', 'SecurityMgmt']">Security</a>
```

**Comment by mkrishna4ua** [comment]
I tried using your way it is not generating the href correctly.
My scenario is:
When i type web url as `http://localhost:8080/myapp/#/admin/systemconfig` and then hit enter then it does not generate the href correctly. When i navigate to other links and come back again to that link then it  generates correctly. So i am not sure what is happening there. It should generate on the first go.

**Comment by brandonroberts** [comment]
@mkrishna4ua can you reproduce in a plunker? Here is a sample one you can use: http://plnkr.co/edit/YLtfbHgmufFSqTJp6gju

**Comment by mkrishna4ua** [comment]
i created new plunker and it has the problem that i mentioned for incorrect Href. the point is i am using AsyncRoute for lazy loading. Please let me know if there is anything wrong.

http://plnkr.co/edit/WXJsaFRA3nFtsjh5tCV1

When click on T1 link then T1C1 link href (/t1/c1) is correct and T1C2 link href (/t1) is incorrect. For T1C2 it should be /t1/c2.

**Comment by brandonroberts** [comment]
@mkrishna4ua I see. So the way async route links work is that it will only generate enough link information link to navigate with. It doesn't technically know that T1C2 exists yet since you're lazy loading it async. Once you click the route link and T1C2 is loaded, the next time you hover over that T1C2 link, it will show the full /t1/c2 path because both routes have been loaded and are registered. Its not that you've done something incorrect, its just the way the router figures out links that aren't fully loaded yet.

Click on T1 -> T1C2 -> T2 -> T1. Hover over T1C2 and it displays /t1/c2

**Comment by mkrishna4ua** [comment]
As per my understanding it is a part of route config so it does know the route config in advance before rendering the view template, from there it should generate the correct href. Anyway we are loading the ts file first that has the template definition and route configuration so it has the complete configuration before hand to prepare the correct href.

**Comment by brandonroberts** [comment]
Ok. What I'm saying is that it doesn't load all the lazy loaded routes once the template is loaded. If your parent route is lazy loaded and all of its child routes are lazy loaded, they won't be loaded until requested for navigation.

**Comment by mkrishna4ua** [comment]
Actually we need that kind of feature in our project. So would it be possible to enhance router so that the href can be generated correctly. 
My problem is in single page application also user can launch separate window by right clicking on any of the child link (That are part of AsyncRoute). If child link href is not correct then it will not open the correct web page in separate window.

We do not want to load the whole module on client, just want to load only the part that is required to display the page. For example:

Lets say if we use URL as : http://localhost:8080/myapp/#/admin/security-mgmt

So here we want to load MainDashboard Component (Common Module)  + admin component + security-mgmt component.

So based on the URL the specified components should be loaded. 
Right now i have added my wrapper to achieve this but if this feature can be included in router that will be awesome. Thanks

**Comment by mkrishna4ua** [comment]
Are you planning to make changes in router related to href problem. It is so weird that in the case of AsynRoute the visible links' href is not correct. Lets say if operator launches the link in another window by mouse right button clicking then he/she will not be able to see the right page on another window.

Another problem in router with AsyncRoute is that if user type the complete URL like http://localhost:8080/myapp/#/admin/security-mgmt then it does not load/display the security-mgmt template/page. I think it should load/display the child routes also that are specified in Web-URL. It does not matter whether it is a Sync or Async route.

**Comment by brandonroberts** [comment]
@mkrishna4ua the complete URL does work with async routes and they work if you open a link in a new window currently. Based on your route configs, your link should be http://localhost:8080/myapp/#/admin/securitymgmt

**Comment by brandonroberts** [comment]
You should file a separate issue about async routes not opening in a new window.

**Comment by vicb** [comment]
obsolete - old router
