### ISSUE TITLE
Components with templateUrl can mess up injectAsync automatic async tracking

### ISSUE THREAD

**Issue by juliemr** [angular/angular#6359]
This came up in material2 tests. 

The testing zone that `angular2/testing` uses for determining async behavior seems to ignore XHR requests. This means that components with a `templateUrl` can cause tests to exit early.

Example:

```js
@Component({
  selector: 'my-comp',
  template: `<span>Hello</span>`,
})
class TemplateComp {
}

@Component({
  selector: 'my-comp',
  templateUrl: '/foo/bar'
})
class TemplateUrlComp {
}

    // GOOD: this one correctly fails
    it('should fail here 2',
        injectAsync([], () => {
          return builder.createAsync(TemplateComp).then((fixture) => {
            expect(11).toBe(22);
          });
        }));

    // BAD: this one DOES NOT fail
    it('should fail here 2',
        injectAsync([], () => {
          return builder.createAsync(TemplateUrlComp).then((fixture) => {
            expect(33).toBe(44);
          });
        }));
```

cc @jelbourn

**Comment by juliemr** [comment]
I believe that switching [runInTestZone](https://github.com/angular/angular/blob/e748adda2e7a1f6e302628d0d76b5c3d1e3fc196/modules/angular2/src/testing/testing.ts#L129) to use `enqueueTask` instead of `setTimeout` will fix this. I'm working on a PR.

**Comment by juliemr** [comment]
An interesting note - these exact same tests both fail (as they should) when I copy them into angular repo tests instead of the material2 repo. Maybe something to do with the different way that zone is loaded from the two karma setups?

**Comment by Tsux** [comment]
Hey @juliemr , it is nice to talk you, saw you solved lot of protractor issues in this forum. So I wanted to ask you about a problem similar to: "https://github.com/angular/protractor/issues/249"
and found FAQ you created regarding. I have protractor 3.0.0, trying to test AngularJS v1.3.8 app that lives in html tag seems Protractor cannot find Angular version inside angularTestResult protractor object. Since I read protractor team was about to add some special capabilities to get this working on Angular 2, wondering if this could be a possible cause of my issue?
You have any info about it?
btw: Sorry for postin' this here, other issues have been closed by you actually, so I was not sure if you would notice if I post in one of them, so I found this recent post. Thx in advance for your attention.

**Comment by juliemr** [comment]
@Tsux please open an issue on Protractor's tracker if you feel you have found a bug, or open up a question on SO and link us there if you have a support question. It is confusing to have unrelated comments on this issue. Thank you.

**Comment by alexeagle** [comment]
Debugging this with @vicb - I think I have the same issue.
It seems that the zone when calling setTimeout is a parent of the zone when the test creates the future.
Also we observe setTimeout being called several times.

**Comment by juliemr** [comment]
One quick option would be to kill the ngTestingZone for now and just rely completely on promises. This isn't a perfect solution (returning sub-promises can still be forgotten), but it would at least prevent silent failures from XHRs.

**Comment by juliemr** [comment]
We've decided to go with the option above (remove ngTestingZone) until we've refactored zones completely and they cover all the XHR, rejected promise, and other cases. I am preparing a PR now.
