### ISSUE TITLE
NgFor and nested components, view and model not synchronized

### ISSUE THREAD

**Issue by eugenyshchelkanov** [angular/angular#6482]
Simple select component, rendered in NgFor. When `my-select` is used to change first value to `one`, view for the second value also gets updated. Am I missing something here or is it a bug?
http://plnkr.co/edit/IFgLBhc841R5NtYzAMTc?p=preview

**Comment by mhevery** [comment]
Something weird is going on in there.

**Comment by zoechi** [comment]
I guess this is because angular can't distinguish different `undefined`. If the values are wrapped in objects this doesn't reproduce http://plnkr.co/edit/FCXT3w6gWBX0fHDGDX2c?p=preview
I don't see why identity is relevant here but if Angular searches the `values` for a specific value it can easily find the wrong one.

**Comment by zoechi** [comment]
This was fixed by `*ngForTrackBy` http://plnkr.co/edit/R4pBPVzE1K1ZPFemMhGs?p=preview

I think this can be closed.
