### ISSUE TITLE
 "EXCEPTION: Cannot find reflection information on FooBar" error is confusing

### ISSUE THREAD

**Issue by jbdeboer** [angular/angular#6494]
There are a number of causes, the exception should point to the root cause. e.g.:

a) FooBar is not annotated with @Injectable correctly
b) the transformer did not find FooBar
c) ...

In all cases, these errors should be detected at transform time instead of runtime.

**Comment by kegluneq** [comment]
Some notes on this bug:

The exception is defined in [reflection.dart](https://github.com/angular/angular/blob/master/modules/angular2/src/core/reflection/reflection.dart). Maybe we should augment the error message to include some common causes?


When FooBar is not annotated with `@Injectable`, in general we won't know about it until runtime - the only locally-knowable way to determine if a service is injectable is that annotation :\


The exception is when FooBar is listed in the `directives: [...]` parameter of a `View` or `Component`. When this happens, the transformer issues a warning ([code pointer](https://github.com/angular/angular/blob/master/modules_dart/transform/lib/src/transform/template_compiler/compile_data_creator.dart#L133)).

Would it be a better experience if this was promoted to an error?

**Comment by jbdeboer** [comment]
An error would be good, especially if #6357 was implemented.

In my case, FooBar is a service injected by another service through a constructor parameter. The transformer should be able to detect that a reflection info for a injected service is missing.

**Comment by kegluneq** [comment]
Spun off https://github.com/angular/angular/issues/6519 to promote the warning to an error - I'll discuss with folks on Tuesday and, if there are no objections, I'll submit a PR.


I've thought about this situation, but haven't been able to come up with a way to detect that `@Injectable` is missing without reading the contents of all `imports` (and the transitive closure of libraries `export`ed by those `import`s) from the file where your original service is defined. Since the omission of `@Injectable` is non-local, we would have to check this for every injected type in all files to give accurate compile-time errors.

We wouldn't want to do that by default, but we've discussed in the past having a debug mode where we're willing to do this extra processing to suss out problems.

**Comment by jbdeboer** [comment]
Thanks Tim, I discussed this issue with @trinarytree. This is a hard/interesting problem that will require some design work to implement. For now, we should leave it open until somebody can dedicate some time and thought to the problem.

One possible design involves two passes: The first pass builds an online index with audit data that can invalidate individual files. This index would contain the ```@Injectable``` bit for each class. The second pass could query the index, eliminating the non-local search.
