### ISSUE TITLE
How to test directives? It should be very simple

### ISSUE THREAD

**Issue by piernik** [angular/angular#6502]
I want to test simpliest directive:
```
import {Component} from 'angular2/core';
@Component({
  selector: 'email',
  template: `Hello Email`
})
export class EmailComponent {
}
```
and really don't know how. In angular 1 You have to use `$compile` so I found plunkr that doeas that http://plnkr.co/edit/0LLj1L8TXUBsVlrXgjgz?p=preview but when I changed to beta.1 it stopped working.

Can someone give example of test for that directive?

**Comment by zoechi** [comment]
cross-link: http://stackoverflow.com/questions/34807798/how-to-compile-html-in-angular-2
GitHub issues are for bug reports or feature requests.
Please use Gitter, StackOverflow or other available channels for questions.
The Angular repository contains tons of such tests as well that work as example. 
See also https://angular.io/docs/ts/latest/testing/

**Comment by piernik** [comment]
1. Sorry for crosslinkig but when I discovered that it works in beta.0 but not in beta.1 I thought I should ask at source.
2. I watch example tests (ngFor and so on) and those are so complicated that I gave up
3. I read tutorail and it stops at testing pipe.

I think testing directives (custom HTML) should be as simply as possible. So You can treat this topic as suggestion.

**Comment by zoechi** [comment]
I don't think cross-posting is a problem. If you think you found a bug it's right to create an issue.

**Comment by thelgevold** [comment]
I have created an "intro" to unit testing in Angular 2.0. It contains a few simple examples. I am sharing in case it will help: http://www.syntaxsuccess.com/viewarticle/angular-2.0-unit-testing

**Comment by piernik** [comment]
Thanks very much. I'll look to it closer later.

**Comment by piernik** [comment]
This worked a lot but missing one thing - hot to test templates?
As I wrote at beginning - how to test simpliest component:
```
import {Component} from 'angular2/core';
@Component({
  selector: 'email',
  template: `Hello Email`
})
export class EmailComponent {
}
```
It should display `Hello Emaill` - how to test it?

**Comment by thelgevold** [comment]
I generally avoid template based testing in unit tests. By putting all your logic in models and/or services you can decouple your code from the templates/view. This makes for much more maintainable and flexible tests. Generally it should be a goal to write code that is agnostic of the caller (view or unit test).

I understand that some people like to follow a pattern from Angular 1.x using $compile to create an instance of the directive by defining markup. This turns it into an integration test rather than a unit test though - which personally like to avoid. The markup approach makes it much harder to support targeted and granular scenarios than if you hit the services/models directly.

Testing the effects at the markup level is in my opinion a better task for e2e tests using (Selenium, Protractor etc).

**Comment by gsans** [comment]
I think these are two different topics: providing a testing recipe and
providing best practices. Also best practices have exceptions so being
neutral helps to allow for both when appropriate.

**Comment by juliemr** [comment]
This will be documented on the angular sites at https://angular.io/docs/ts/latest/guide/testing.html.
