### ISSUE TITLE
Missing a way to retrieve innerHTML of the original element

### ISSUE THREAD

**Issue by kayue** [angular/angular#6525]
I think Angular 2 is missing a way to retrieve innerHTML of the original element

```html
<foo>SOME TEXT HERE</foo>
```

I know I can render the original content with `<ng-content>`

```js
@Component({
    selector: 'foo',
    template: '<ng-content></ng-content>'
})
```

However there is no way I can retrieve the original content in constructor, or anywhere in the code.
The `@Input` is only able to access attribute, but not inner HTML. 
And the `ElementRef` in constructor is a already modified element.
May I know what is the proper way to get inner HTML of the element?

**Comment by kayue** [comment]
This is the only possible work around I can found now: http://plnkr.co/edit/TZJxWojSFaoJUJHF3EKg?p=preview

```javascript
@Component({
  selector: 'my-directive'
})
@View({
  template: `
  <input type="text" [value]='test.innerHTML'/>
  <br>
  <span class="hidden" #test><ng-content></ng-content></span>
  `
})
export class MyDirective {}
```

**Comment by pkozlowski-opensource** [comment]
@kayue out of curiosity: _why_ do you want to get access `innerHTML`. I mean - what is the functional use-case you are trying to address here?

**Comment by kayue** [comment]
@pkozlowski-opensource I want to make a "editable content" directive, for example:

```html
<div>
  <editable>
    <p>Foo</p>
    <p>Bar</p>
  </editable>
</div>
```

Whatever is wrapped inside is valid and valuable content to me.

Thanks.

**Comment by cghislai** [comment]
You want to allow editing html? I went for something like that:
```
<div [innerHtml]="myContent" [hidden]="editing"></div>
<textarea [(ngModel)]="myContent" [hidden]="!editing"></div>
```

**Comment by enzoaeneas** [comment]
I have the same problem but this arises with 3rd party webcomponents (i.e. Kendo UI) that can use or need basic HTML prior to enhancement. For example the [Kendo Splitter](http://docs.telerik.com/kendo-ui/controls/layout/splitter/overview#getting-started). 

In this example, when used within a template and as a webcomponent:
```
<kendo-splitter id="splitter">
    <div>Area 1</div>
    <div>Area 2</div>
</kendo-splitter>
```
The two interior divs are not available to the code and therefore it's initialization fails.
I have traced this through the Kendo UI source code and I get the error: 
**Uncaught TypeError: Cannot read property 'offsetWidth' of undefined**
occurring in angular2-polyfills.js @ line 143 when using Chrome 47.

When I put the same same snippet outside of the appcomponent in the my index.html, the splitter is initialized correctly.

**Comment by tom10271** [comment]
I need to originally HTML before Angular touching it. 

https://github.com/wmluke/angular-blocks

If I want to rewrite this directive so that I can extend templates, I must first replace blocks of HTML to base template then compile it manually. However I cannot find anyway now how to stop Angular compiling the code as compile hook no longer exist.

**Comment by mhevery** [comment]
So one can just inject `ElementRef` and get a native element from there and do whatever you need. Keep in mind that it is a huge security hole to work with `innerHTML`.

Assume you have this;
```
<editor>
 <div *ngFor="var item in items">{{exp}}</div>
</editor>
```

Here the compiler will get a hold of the content and starts transforming it. Later the `editor` will use `innerHTML` and get collisions since both angular and `editor` are in charge of the same DOM. Presumably the content for the `editor` comes from a different location, such as database, so the content can not even be there at the time of compilation. 

I think the best way to solve this is to have an empty `<editor [html]="expr"></editor>` component which can do the HTML editing. This is the only way to ensure that there is no DOM contention.

I am sorry, but I will close this as there is not much angular can do to help this use case.

**Comment by shortstuffsushi** [comment]
Hi guys,

I know I'm late to the party, but I'm struggling to find a way to do this in the current situation I have. I'm working to get Angular into a .NET MVC application, specifically on a form. MVC has a concept of CSRF tokens that they typically embed directly into the form, but since I'm hoping to submit the form via Ajax, I was hoping to just be able to pull that token from the page (which I could still do, just not as nicely). Ideally, what I am hoping to do is something like this, in the server code that generates the page:

```
<my-form-component>
    <csrf-token>@Html.AntiForgeryToken()</csrf-token>
</my-form-component>
```

Is there a better approach for this?

**Comment by ptollena** [comment]
You need to understand the use case before rejecting it. If innerHTML is not a way to do it then propose another way. If you received formatted HTML from outside, you need to be able to reformat it somewhat to fit angular2 model if you want to include it in a component.

**Comment by zoechi** [comment]
@ptollena this comment sounds like a complaint but I don't get about what exactly. 

To me it sounds a bit like expectations about how Angular2 works that don't match how it actually works.

I think you should discuss your use case in one of the channels mentioned in [CONTRIBUTING - Got a Question or Problem?](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question) and if there is actually a missing feature, then please create a new issue.

**Comment by select** [comment]
Hi there I'm trying to create a translate directive for i18n like the following
import { Directive, ElementRef } from '@angular/core';

```
/**
 * TranslateDirective
 * Translates the innerHTML of a DOM element.
 *
 * usage:
 * ```
 * <h1 translate>Edit</h1>
 * ```
 */
@Directive({
	selector: '[translate]',
})
export class TranslateDirective {
	static get parameters() {
		return [[ElementRef]];
	}
	constructor(el) {
		el.nativeElement.innerHTML = translationTable[el.nativeElement.innerHTML]['en'];
	}
}
```
As I understood this discussion this is not possible. Are there any alternatives?

**Comment by tom10271** [comment]
I think you are doing it wrong, you should use pipe but not directives to
handle translations.

I know there is a library handle translation for you in Angular 2. Try to
search for it.

2016-10-10 20:49 GMT+08:00 Falko <notifications@github.com>:

**Comment by select** [comment]
@tom10271 Thanks I also discovered that there is now a i18n implementation included in the latest release that works exactly like I described above.

**Comment by charitharumapperuma** [comment]
Hi, is there any solution for this particular case as of now? In my case I cannot use innerHTML because, then angular had already rendered child components, and I need to get the original code segment written in parent component.

in parent-
```
<child>
    <label>Name</label>
    <grand-child><grand-child>
</child>
```

in child-
```
<div class="preview">
    <h2>Preview</h2>
    <ng-content><ng-content>
</div>
<div class="code">
    <h2>Code</h2>
    <pre>
        {{code}}
    </pre>
</div>
```

so `code `should be a string in the child component,
```
`
<label>Name</label>
<grand-child><grand-child>
`
```

**Comment by gund** [comment]
I ran into interesting use case in one of my projects which requires this feature.

So there is sort of demo pages of Angular components built on Angular as well.
Each demo shows actual example of some component and below it - html code of that example.
I wanted to implement some directive which will be able to take that original example code and render that as text so that you can easily see the code of example.
This will remove duplications because it can just take real code from template and show it down below the example.

Example:
```html
<h3 class="header">em-textbox</h3>
<div class="example" #code>
  <em-textbox placeholder="Test Field"></em-textbox>
</div>
<div class="code">{{ code.innerHTML }}</div>
```

But since angular compiling the template it is not possible the get the original untouched template, not even as a string and the outcome is polluted with `ng-reflect-` and other stuff...

**Comment by tom10271** [comment]
@gund Did you try to escape code.innerHTML and add it to `[innerHTML]="code.innerHTML"`? I think this is the proper way to achieve your goal

**Comment by gund** [comment]
@tom10271 I tried but it does not change anything since the HTML itself is polluted/changed.

It would be great to have some API to get original template, at least as a string...

For now as a workaround I have to write some regexps to remove dirty stuff off of the template strings...

**Comment by gund** [comment]
So I was able to restore original template by applying a few regular expressions.
Will post them here - maybe someone wants use them:

```ts
function cleanupTemplateString(template: string): string {
  return template
    .replace(/\s?ng\-reflect\-.+=".*"/g, '') // Remove `ng-reflect-` things
    .replace(/\s?_nghost\-.+=".*"/g, '')     // Remove `_nghost-` things
    .replace(/\s?_ngcontent\-.+=".*"/g, ''); // Remove `_ngcontent-` things
}
```

Also if you want to remove children of component (to leave only root element) - apply next regex before those above:
```ts
function removeChildrenFromTemplate(template: string): string {
  return template.replace(/(<([^\s]+).*>)[^]*(<\/\2>)/, '$1$3') // Remove children of component
}
```

But access to original untouched template would really simplify things! =)

**Comment by gund** [comment]
Just discovered that some of the information is lost (during transformation) in particular bindings in brackets `[]`...

So actually without having support from API it is impossible to retrieve original template... 😔

**Comment by zoechi** [comment]
@gund There is no original template. When you use AoT compilation, these bindings are replaced by JS code and don't exist anymore at all anywhere within the browser (only in your source code).

**Comment by gund** [comment]
@zoechi Actually I already tested how you can get original template even in AOT compiled app - via metadata.
In a few next days will create some small POC and share here.

**Comment by zoechi** [comment]
@gund sounds weird. I think this would bloat the build output a lot. Are you sure you did a production build? I'm only using Angular with Dart and don't know much about this TS specific stuff.

**Comment by gund** [comment]
Yes I did a production build and still metadata exists on every component so you can access it as runtime.

I created a working POC for extracting pieces of template with help of directive:
https://github.com/gund/ng-original-template-poc

This approach should be fully compatible with AOT compilation as well.

**Comment by KurtGokhan** [comment]
This seemed like a valid issue to me. Can we still have this feature?
I can't directly use `ng-content` because I have to use the text as a value. Here is my use case and workaround for anyone interested:

``` html
<div #content style="display: none;">
  <ng-content>
  </ng-content>
</div>

<md-input-container>
  <input disabled readonly mdInput [placeholder]="content.innerText" #textInput>
   ....
</md-input-container>
```

**Comment by zoechi** [comment]
@KurtGokhan see https://github.com/angular/angular/issues/6525#issuecomment-173352459 and other comments. Don't expect reponses to closed issues, they aren't monitored.

**Comment by Tahiche** [comment]
Hi,
I was trying to get the original content, before Angular modifications, in order to show a "input this to get that" kind of thing, using Google Prettify. 
What i came up with i´m sure is very hacky but since it´s an internal  "reference" kind of site, I´m ok with it.
I needed a way to store the original markup/content before processing to show it alongside the Angular processed output. So I made a "base" component from which others extend. 

```
export const defaultComponentProps = {
  selector: 'app-common',
  // templateUrl: './common.component.html',
  template: require("./common.component.html"),
  styleUrls: ['./common.component.scss']
};

@Component(
    defaultComponentProps
)
```
The logical way would be to access the content of @Component['template'] (kindof;) but I haven´t been able to. Tried with Reflect and other libs to no avail. So I have to put it as a var that i can later on access from my component. By using "require('templateURL') instead of "templateUrl" i have a ref to the original content.

```
ngOnInit() {
// here´s the original content
    let templatePage = this.ComponentProps.template;
    this.externalCode = templatePage;
  }
```
After that you do whatever with it. In my case I match current elements with original elements and generate prettify markup from the original code.

Something like this (not complete, just for reference):

```
ngAfterViewInit(){
   // create DOM element from code to be able to itirate...
    let tempDiv = document.createElement('div');
    tempDiv.innerHTML = this.externalCode;
    // select the divs/elements i´m interested in.
    let matches = tempDiv.querySelectorAll(this.selectors);
    tempDiv = null;
    // prettycomponents is a list of the elements that i want to match, in this case they apply PrettycodeComponent. 
   // @ViewChildren(PrettycodeComponent) prettycomponents:PrettycodeComponent[];

    if(this.prettycomponents.length > 0){
      this.prettycomponents.forEach(
          function (component,index)  {
            // without timeout i get  error content changed!!!!
           // pass the original code to my component, you could just append it here, after the original div...
            setTimeout(()=>component.setCode(matches[index].innerHTML));
          }
      );
    }
  }
```
It´s probably overkill and hacky, but I just couldn´t find a better way to acomplish this.
