### ISSUE TITLE
Allow muting the Angular 2 mode printing in the browser console.

### ISSUE THREAD

**Issue by emesx** [angular/angular#6540]
The current implementation prints out the mode of Angular 2 to the browser's console
(see [application_ref.ts](https://github.com/angular/angular/blob/7ae23adaff2990cf6022af9792c449730d451d1d/modules/angular2/src/core/application_ref.ts#L435) ). In Dart it's not even possible to call `enableDevMode()` any more, since it's a no-op now.

Please add an option to mute this output (other than manually rebinding the `Console`) so that it's possible to have production code clean of any debug / diagnostic printouts.

**Comment by deeleman** [comment]
This is certainly a bit annoying. While muting this by hand is pretty straightforward (it just takes to remove the [logging from the Completer Promise](https://github.com/angular/angular/blob/7ae23adaff2990cf6022af9792c449730d451d1d/modules/angular2/src/core/application_ref.ts#L430-L435) returned by the bootstrap function), it would be great to have a more discreet way to inspect this information if required. The object resulted by the `bootstrap()` function itself might be a good place for that. Otherwise, adding a boolean parameter to the `enableProdMode()` function signature informing wether we want to get those printouts or not might be fine as well. Wish I had some time to send a PR myself.

**Comment by samjulien** [comment]
Would this perhaps be something a first-timer could help out with? And if so, @deeleman would you be willing to give me a nudge in the right direction for how to tackle it?

**Comment by deeleman** [comment]
Not being an authorized voice myself, that sounds like a good approach to me @samjulien. Obviously your [starting point](https://github.com/angular/angular/blob/7ae23adaff2990cf6022af9792c449730d451d1d/modules/angular2/src/facade/lang.ts#L61-L71) for this will be editing `/modules/angular2/src/facade/lang.ts` as you mentioned already.

Make sure to conform to the [contribution guidelines](https://github.com/angular/angular/blob/master/CONTRIBUTING.md) when submitting your PR ;-)

**Comment by samjulien** [comment]
Okay, great, thanks @deeleman. Code fix itself looks pretty straightforward, combing through the dev docs and contribution guidelines to make sure my styles and testing are compliant. :) I'll ping if I have any other questions.

**Comment by emesx** [comment]
Hey, it's been a while since I created this issue, but AFAICT it still is unresolved.

The console message still [says to call enableProdMode()](https://github.com/angular/angular/blob/8bb66a5eb382f454af80523894efba9c61fc7e7b/modules/angular2/src/core/application_ref.ts#L456) but that function still [does nothing](https://github.com/angular/angular/blob/50548fb5655bca742d1056ea91217a3b8460db08/modules/angular2/src/facade/lang.dart#L284) (in Dart).

Perhaps the original issue is resolved (i.e. the message is not printed in prod mode in Dart), but the message - whenever it might get printed - is misleading.

What do you think?

**Comment by vicb** [comment]
obsolete (dart related)
