### ISSUE TITLE
async routes not opening in a new window

### ISSUE THREAD

**Issue by mkrishna4u** [angular/angular#6562]
async routes does not generate the href correctly due to that when user try to open link in separate window (by mouse right click) then it does not open the correct page. See the plunker for more detail
http://plnkr.co/edit/WXJsaFRA3nFtsjh5tCV1

**Comment by ThiagoT1** [comment]
Check if this helps: https://github.com/angular/angular/issues/5908

**Comment by zoechi** [comment]
or #6358

**Comment by ThiagoT1** [comment]
I made this plunker. 

It awkwardly extends RouterLink's prototype, so new tabs work.
On plunker, a link to a new tab will result in a json object with 404 on it. Should work on a regular server though.

http://plnkr.co/edit/EgPLDzjlO5GNQtoAL1k7?p=preview

**Comment by brandonroberts** [comment]
He's more specifically talking about async child routes. If you have a parent route that is async and a child route that is async, the route link only generates enough information to navigate. So if the parent route path is /parent and the child route paths are /child(default) and /child2, the route link only generates an href of `/parent` for the /child2 route and will resolve the rest once clicked on for navigation. If you want to open the /child2 route link in a new window, it opens /parent, which will navigate to the default which is /parent/child instead of opening /parent/child2.

**Comment by ThiagoT1** [comment]
I gather that's two problems at the same time, since new tabs wont work with current RouterLink's form anyway.
As for the async issue, wouldnt it be better if nested routers were avoided?

**Comment by brandonroberts** [comment]
@ThiagoT1 there's no reason to avoid nested routes. For now there are a couple of options. One would be to only load the parent routes async and let the children load synchronously, which will provide the correct route links. Another option would be to resolve the async route components before loading the parent route. You would have to access private properties, which is discouraged but possible. Here is an example in src/T1.ts:

http://plnkr.co/edit/p6n13BT4TFPkRkjndIab?p=preview

**Comment by sumigoma** [comment]
+1, same issue when trying to right-click/new tab a router-link anchor that is supposed to have query parameters. 

i.e. Clicking the link loads the page with the supplied params as query params, while new tabbing just omits the params (and loads the parent route).

**Comment by vsavkin** [comment]
We are no longer maintaining the deprecated router to focus our efforts on making the new router solid.

It doesn't look like the issue makes sense in the context of the new router. If you think it does, please reopen the issue.
