### ISSUE TITLE
control.valueChanges can't watch when chrome auto fill password 

### ISSUE THREAD

**Issue by ibufu** [angular/angular#6615]
Chrome auto fill password to input but control.valueChanges.subscribe() can't watch password changed.

**Comment by pkozlowski-opensource** [comment]
The essence of the problem here is that various browsers don't behave differently when it comes to auto-fill and raising DOM events when the auto-fill happens. The reality on the ground is that there is no reliable way of detecting auto-fill across browsers without brutal hacks (a common technique is to pool value in some time intervals). 

Unfortunately we can't add those hacks to the framework without negatively impacting perf. We _do_ understand this is a major PITA but there is just no good, generic solution here that could be implemented in the framework (at least not in the current state of browsers....).

If anyone has a non-hacky (or at least reasonably-hacky....) proposal on tackling this we can revisit but for now I'm going to close this one as won't fix....
