### ISSUE TITLE
some problems with demo

### ISSUE THREAD

**Issue by HelloYu** [angular/angular#6628]
open the demo page,It doesn't work,seem the problem is missing some libs.
![image](https://cloud.githubusercontent.com/assets/6134340/12503425/17d9bbdc-c10f-11e5-91de-da0ed2d1fc0d.png)

**Comment by pkozlowski-opensource** [comment]
@HelloYu it is not clear what "demo page" you are talking about - please share a plunker you are trying to open. I don't think it is about a plunker forked from Angular2 documentation since we don't use jQuery there.

Closing, since I don't think it is a right repo. Happy to re-open if you can share the exact plunker you are trying to play with.
