### ISSUE TITLE
Template parser fails when <p> wraps a child element

### ISSUE THREAD

**Issue by josephperrott** [angular/angular#6648]
If a `<p>` element wraps a child element, for instance `<div>`, an error is returned.  `<p>` elements should be able to contain children.

[Plunker example](http://plnkr.co/edit/3UCCyL8CoEgti8pTlyee?p=preview)

**Component template:**
`<p><div></div></p>`

**Result:**
Template Parse Error
>Unexpected closing tag "p" ("<p><div></div>[ERROR ->]</p>"): HelloWorld@0:14

**Component template:**
`<div><div></div></div>`

**Result:**
The parser completes as expected.

**Comment by pkozlowski-opensource** [comment]
TL;DR; works as expected

> <p> elements should be able to contain children

Sure, from [HTML spec](https://www.w3.org/TR/html-markup/p.html) only [Phrasing content](https://www.w3.org/TR/html-markup/common-models.html#common.elem.phrasing)

`<div>` is _not_ phrasing content, so can't be a child of a `<p>` tag.

See also: http://stackoverflow.com/a/4434111/1418796

**Comment by jelbourn** [comment]
@pkozlowski-opensource I think we should be a little more clear on the error message in this case, as this is one of the obscure spec details. What do you think?

**Comment by PascalPrecht** [comment]
@jelbourn I agree. Issues like these are popping up here every now and then again and again. Maybe it's  better to display an error message that says sth. like: "{{tag}} can't contain child element of type {{type}}"?

**Comment by e-oz** [comment]
Have to say I absolutely hate such purism. It works in browsers, but Angular is too noble to render it. In practice it will just break some templates and create huge issues when source of content can't be controlled by frontend developer. For example, when you pull content from database. I know it sounds too old-fashioned, but some companies store some things in DB, where urgent edits are critical (such as Terms Of Service).

Another example - third party modules, plugins. If some author of some JS plugin will be dare enough to make such criminal thing as `<p><div>`, it will accidentally kill whole your app, because tiny soul of Angular renderer can't survive near so dirty html.

**Comment by pkozlowski-opensource** [comment]
> I think we should be a little more clear on the error message in this case, as this is one of the more obscure spec details. What do you think?

I'm all for better error messages! Let's check with @vicb to see what / if we can improve. 
@jelbourn feel free to re-open / follow up with @vicb

**Comment by pkozlowski-opensource** [comment]
> Have to say I absolutely hate such purism. It works in browsers

@e-oz it really doesn't "work" that well in a browser. Try this in your favourite one:

```javascript
var elm = document.createElement('div').innerHTML = '<p><div></div></p>';
```

In chrome this will give you:

```html
<div><p></p><div></div><p></p></div>
```

which means that a browser "auto-corrected" invalid HTML. The assumption was that it is better to catch those errors during compilation (a hypotetical broken 3rd party would only fail if an author didn't run it at all - I guess there is no good reason to use shuch 3rd parites...) rather than be sorry at runtime.

Once again - let's improve it as much as possible, add better error messages etc. but it is important to realise that invalid HTML is ... invalid HTML and browsers might do all sort of crazy things with it in order to make some sense of it.

**Comment by e-oz** [comment]
@pkozlowski-opensource it doesn't matter what browsers do until user/designer see "it works" and push it to DB. You ignored that example for some reason :)

> but it is important to realise that invalid HTML is ... invalid HTML

Why it's important? What it gives to us/framework? I really see it as just perfectionism, nothing else.

> and browsers might do all sort of crazy things with it in order to make some sense of it

they can do crazy things with 100% valid HTML too, so it's not an argument. That's why testing tools and QA departments exists.

**Comment by e-oz** [comment]
> a hypotetical broken 3rd party would only fail if an author didn't run it at all - I guess there is no good reason to use shuch 3rd parites...

ok, it means parser will not throw an exception if some JS code will change code of page in runtime. Good to know.

**Comment by patrikx3** [comment]
besides angular2 itself is non valid html!
please angular 2 should not be a html parser, max for angular 2 its own, leave it for the browser!
so weird!

**Comment by zoechi** [comment]
@patrikx3 anything to back up that claim?
Perhaps you should first try to understand what Angular does before criticizing?

**Comment by patrikx3** [comment]
how can itself angular2 be non valid  but the parser is valid???
```<i-am-angular/>```
still the parser is forceful?

look i like ng2:
https://pages.corifeus.tk

but i can create custom html elements, but ```div``` inside ```p``` is not valid :)

**Comment by zoechi** [comment]
Custom elements **are valid and**, `p` inside `div` **is invalid**. This was already pointed out to you.  
Please stop spamming issues with irrelevant comments (that was also already pointed out to you).

**Comment by e-oz** [comment]
@zoechi you forgot to say "please" I think. Not sure why you allow so commanding and agressive tone to yourself and don't allow to even share opinion to Patrik. For the note, p inside div is valid, talk was about div inside p, so your bold is as funny as agressive.

**Comment by zoechi** [comment]
@e-oz no idea what you mean. Yes I mixed the order of `p` and `div` - thanks for pointing that out, but my comment says 

> Please stop spamming issues ...

**Comment by AlphaJuliettOmega** [comment]
This is objectively a bad error response for html that doesn't break the browser

"Uncaught Error: Template parse errors:
Unexpected closing tag "p". It may happen when the tag has already been closed by another tag. For more info see ..."

I'd love to see @jelbourn's suggestion make its way in one day, the error returned by the compiler does not give information that's useful.

**Comment by trotyl** [comment]
@AlphaJuliettOmega Because this is syntax error, not semantic error, try out [official w3c HTML validator](https://validator.w3.org/nu/) you won't get any thing better:

> `Error`: No `p` element in scope but a `p` end tag seen.

I think you didn't aware that [the `</p>` end tag being optional in HTML](https://html.spec.whatwg.org/#optional-tags:the-p-element). So that:

```html
<p><div></div>
```

is totally valid HTML stands for two sibling `<p>` and `<div>`.

What you want for a better message is for recognizing `<div>` as a child of `<p>` and then report misplacement, but that won't happen at all per HTML syntax.

If you think HTML syntax is too ambiguous, that's totally fine, but this is still not the right place to complain with.
