### ISSUE TITLE
Synchronous EventEmitter silently swallows errors

### ISSUE THREAD

**Issue by garethdn** [angular/angular#6651]
I've come across an issue where it appeared that my `EventEmitter` wasn't triggering it's observers. The apparent symptom appeared to be somehow losing my observer of an `EventEmitter`.

As it turns out when an event is emitted from a synchronous `EventEmitter`, if any of the observers encounter an uncaught error, the error is silently swallowed and the observer appears to be unsubscribed.

To be clear, by "synchronous EventEmitter" I mean creating an `EventEmitter` like so:

`@Output() toggleSync: EventEmitter<any> = new EventEmitter(false);`

This behaviour is easily reproduced [with this plunkr](http://plnkr.co/edit/0Bu1DSvEe6YVGnBD5kG4?p=preview)

I searched through the issues and couldn't see this mentioned so hopefully it's not a duplicate.

EDIT: using beta 0 version

**Comment by Brendan-csel** [comment]
+1 here in Beta 3.  The error in my outer component  handler (my own fault) seems to be getting caught in AbstractChangeDetector handleEvent which looks like it then throws a new EventEvaluationError but nothing gets logged to the console and the Output binding on my inner component just seem to stop working.

As long as I step through my code and break in the above catch block I can see the details of my actual error - but I'm not sure where/how to plug into angular to see those errors otherwise?

**Comment by pkozlowski-opensource** [comment]
Still the issue in 2.0.1: https://plnkr.co/edit/0Q6vLb4rCMg45Nl9GGK3?p=preview

**Comment by DzmitryShylovich** [comment]
@pkozlowski-opensource what's the expected behavior? Both emmiters throw the same `Cannot read property 'split' of null` error.

**Comment by DzmitryShylovich** [comment]
@vicb can be closed

**Comment by splincode** [comment]
@mhevery Is the issue relevant?
