### ISSUE TITLE
Depends on rxjs as `dependencies`

### ISSUE THREAD

**Issue by laco0416** [angular/angular#6659]
Currently, this project uses npm v3. That's great!
But, there are still `peerDependencies` in https://github.com/angular/angular/blob/master/modules/angular2/package.json .

In npm v3, `peerDependencies` are no longer installed implicitly.

Contributors can install those as `dependencies` from package.json on root, but users cannot. I must execute commands; `npm install --save angular2@2.0.0-beta.1 rxjs@5.0.0-beta.1 reflect-metadata es6-shims es6-promise zone.js` . It's not happy for developers.

I'd like to install only `angular2` explicitly. I think many developers are also thinking so.

**Comment by laco0416** [comment]
ES6 polyfills (`es6-promise` and `es6-shims`) may not be needed in some cases. Maybe these does not have to be `dependencies`.

Angular2 polyfills (`zone.js` and `reflect-metadata`) also are not always needed because there is `angular2-polyfills.js` . 

But RxJS have to be installed always explicitly. This should be `dependencies`.

**Comment by laco0416** [comment]
@btford Hi. How are you thinking about this?

**Comment by cebor** [comment]
:+1:

**Comment by ovrmrw** [comment]
+1

**Comment by cw-okuno** [comment]
:+1:
It's a very tough.

**Comment by armorik83** [comment]
:+1:
It's really tough.

**Comment by laco0416** [comment]
#7001 could be prevent if rxjs were `dependencies`, I think.

@mhevery @IgorMinar I want you to think about this thing.

**Comment by alexeagle** [comment]
#7001 is simply tracking that changes are needed in angular 2 for us to work with the latest rxjs, not related to how the right `node_modules` structure ends up in your project.

See https://github.com/angular/angular/issues/5560 where we decided to make these peers.

@IgorMinar has written elsewhere about the reasoning for these peerDependencies - essentially it is that these are all API-level dependencies on upcoming EcmaScript standards (eg. reflect-metadata is already coming in es7, zone.js is TC-39 stage zero, rxjs is next) and so you could choose whatever implementation you want. Angular just wants you to bring some implementation for each of these standards. Also, you should use the same version of the peerDependency everywhere.

We think the right fix is to add an npm option that lets you opt-in to explicitly installing the peerDependencies that angular requests.

**Comment by laco0416** [comment]
@alexeagle I agree on your opinion about es6 shims. But I think it should not apply on RxJS. 
RxJS is just JavaScript library. And it's under developing as beta version. so it's unstable dependency.
Users can mistake easily to install wrong version RxJS. 

If angular2 keeps peerDependency for RxJS, I think that to install it on `postinstall` of angular2 is one of the way. 
What do you think this idea?

**Comment by alexeagle** [comment]
I don't even know if we've filed an issue with npm for the behavior we want.
I think something like a postinstall script in *your* project that looks
through your installed deps and installs their requested peers is closer to
correct.

**Comment by laco0416** [comment]
Okay, I can understand it. It's really correct but I'm worried if it is not friendly for beginners.
During angular2 is still in beta, this is a small problem. But in the future or soon, many people may have questions or issues like #7001.

**Comment by laco0416** [comment]
If RxJS will be stable, my worry is unnecessary. I hope it. :)

**Comment by IgorMinar** [comment]
We decided to use `peerDependencies` rather than `dependencies` for all of our dependencies for several reasons, all of which are aimed at giving developers more control and flexibility over the dependency graph. 

All of the peer dependencies as required today are expected to be provided by the runtime and compile-time environment to Angular 2 (as opposed to Angular loading these dependencies during boot time).

Let's take a look at all of them and discuss what I mean by the statement above.


- `es6-promise` - this is a polyfill that Angular requires to be provided by the environment. Due to a hack in zones.js we currently require this polyfill even when browsers provide native implementation of promises. This hack will go away when Angular 2 is upgraded to the next version of zone.js. Afterwards we expect the need for this dependency to go away once promises are implemented in all ever-green browsers we support.
- `es6-shim` - this is a polyfill that Angular requires to be provided by the environment. This polyfill monkey patches the global context (window) so we definitely don't want Angular to do this as a side-effect of loading Angular. We also want people to have a flexibility to use other polyfill implementation providing the same APIs (e.g. core-js). We are expect this dependency to go away once all ever-green browsers we support have all the APIs required by Angular available.  
- `reflect-metadata` - this is a shared dependency between Angular and TypeScript compiler. Since we want users to have the flexibility to update to a new version of TypeScript without upgrading Angular, it's important that this package is a dependency of the application and not a dependency of Angular. 
- `rxjs` - this is a [prollyfill](https://au.si/what-is-a-prolyfill) for Observables specification that is being standardized by TC39. Once again, we want developers to be able to control which version of rxjs to use (within a compatible version range) and not have to wait for Angular releases to receive bug fixes and new features. 
- `zone.js` - this is a prollyfill for Zones specification that is being standardized by TC39. Once again, we want developers to be able to control which version of rxjs to use (within a compatible version range) and not have to wait for Angular releases to receive bug fixes and new features.

Now all of the polyfill dependencies, should ideally by just a suggestion or a hint to developers so that they know what Angular expects, but they should not be a hard requirement as they are today. There is an npm feature request for "[optional peerDependencies](https://github.com/npm/npm/issues/3066#issuecomment-178871868)" which would allow us to model this relationship better. Once implemented, Angular will switch over to using these `optionalPeerDependencies` rathern than `peerDependencies` for all polyfills.

**Comment by IgorMinar** [comment]
@wardbell could you please incorporate the information in the above comment into our docs in some suitable way? Thanks!

**Comment by laco0416** [comment]
@IgorMinar Thanks to very kind explanation. I finally understood your decision and purposes.
I never worry if there is the above documentation.

**Comment by armorik83** [comment]
I see! got it. Thank you.

**Comment by wardbell** [comment]
@IgorMinar  It's on its way. See [angular.io PR #852](https://github.com/angular/angular.io/pull/852)

**Comment by SIGAN** [comment]
But there is a the problem with es6-collections & es6-promise. 

If you use them, users can't use es6-shim.

TypeScript won't compile if you include just es6-shim, it won't compile if you include both, because each time it will end up with double declaration of Promise & Collections.

And the question is how to get then newer array or string methods? With ES5 target of course.
