### ISSUE TITLE
ngIf="returnsPromise() | async" goes to infinite loop

### ISSUE THREAD

**Issue by mohsen1** [angular/angular#6696]
I was experimenting with AsyncPipe that this happened. If a method is returning a promise and you pipe it to AsyncPipe it will go to infinite loop and crashes the browser.

<img width="489" alt="screen shot 2016-01-25 at 8 45 42 pm" src="https://cloud.githubusercontent.com/assets/543633/12572733/dc8a8d66-c3a4-11e5-8bcf-f1f68e496971.png">

*Sorry for screenshot, tab was frozen and I couldn't copy the code*

**Comment by robwormald** [comment]
this is expected behavior, because each time the method is called, you're returning a new instance of the promise, which when resolved, triggers change detection, which retrieves a new promise, which triggers change detection....

You should a) generally avoid calling methods from the view and b) assign a promise to a property

**Comment by danielrasmuson** [comment]
@robwormald The example given in the docs describes piping a promise to AsyncPipe.

Should those docs be updated?

[Source Docs](https://github.com/angular/angular.io/blob/0494b141ad3aa0f8c0018838107d047646c5420a/public/docs/ts/latest/guide/pipes.jade#L204-L213)

[angular.io](https://angular.io/docs/ts/latest/guide/pipes.html)
