### ISSUE TITLE
Component not rendering after router.navigate called from inside callback.

### ISSUE THREAD

**Issue by jphillips05** [angular/angular#6752]
I have a call to auth0 returning a callback which holds information about the user being authenticated, which I capture and send my my backend through an injected service. When I get the users information back from auth0 I save them and call router.navigate. I see the route change, but the template does not render. Any help is greatly appreciated.

https://plnkr.co/edit/Oz8lY7v6q8GpH71WLtAK

**Comment by jphillips05** [comment]
I have narrowed my issue down to the callback from auth0. I am getting the values in profile and id_token, also the router seems to route correctly. It seems like the page cycle breaks after that. The constructor gets called but thats where it stops.

**Comment by allanlundhansen** [comment]
+1

**Comment by pcroc** [comment]
We saw a similar problem, but only in the Safari browser - an third party API triggered a callback which we then used to navigate to another page. The route would change but components would not be properly rendered.

The fix was to inject `NgZone` into the component and then use `ngZone.run(...)` within the callback to re-enter the Angular scope.
See: https://angular.io/docs/ts/latest/api/core/NgZone-class.html

**Comment by jphillips05** [comment]
@pcroc thank you for the work around, this did make the code run as expected.

**Comment by vicb** [comment]
obsolete - former router

**Comment by Dragomir-Ivanov** [comment]
`obsolete - former router`
Please can you elaborate on that? Is it means that with newer versions of Angular2/router this ngZone is not needed?

**Comment by QLaille** [comment]
Any news ? Even with ngZone it isnt rendering at all.
