### ISSUE TITLE
dgeni does not honor new lines in ``` tags

### ISSUE THREAD

**Issue by mhevery** [angular/angular#680]
See: 
http://localhost:8000/angular2/core/01_templates

```
` ` `
html 
<div>{{exp}}</div>
` ` `
```

Should render as:

```
html 
<div>{{exp}}</div>
```

but renders as:

```
html <div>{{exp}}</div>
```

**Comment by petebacondarwin** [comment]
The problem is that the markdown renderer treats backticked code blocks inside HTML elements (in this case `<td>`s) as inline code spans and so doesn't extract the code language (`html` in this case) from the first line and does wrap the code block in a `<pre>` tag, which is needed to preserve whitespace.

**Comment by petebacondarwin** [comment]
Probably the simplest solution, without hacking the `marked` 3rd party rendering engine, is to ditch the tables and just use headings for now.

**Comment by mhevery** [comment]
What about switching to `<pre>` instead of  back-tics. Would that solve it?
How would you change the code to keep it in a table format?

**Comment by petebacondarwin** [comment]
I tried switching to `<pre>` - this is fine but you lose the syntax highlighting.

Switching to headings would mean losing the tables.

A horrible hard coded method would be to render the code elsewhere and then copy and paste the actual HTML into the table cells...

**Comment by petebacondarwin** [comment]
http://stackoverflow.com/questions/21878143/github-markdown-syntax-highlight-of-code-blocks-in-the-table-cell
