### ISSUE TITLE
Add and Remove Validators from FormControl

### ISSUE THREAD

**Issue by VishalMadhvani** [angular/angular#6824]
As far as I can tell, it is not possible to modify the Validators on a Form Control after it has been created.
Currently to do this, the control has to be destroyed and recreated with the desired validators, but it also requires copying the old control state to the new control.

**Comment by zoechi** [comment]
I just had a brief look (in Dart)

```dart
class FormElement {
  ControlGroup form;
  FormElement(FormBuilder fb) { // constructor
    form = fb.group({
      "firstName": ['', Validators.required], // first list item is the initial value for the control
      "streetAddress": ['', Validators.required],
      "zip": [
        '',
        Validators.compose([ZipValidator.validate])
      ],
      "type": ['home']
    });
  }
}
```

and it seems to work to assign validators after the form is built 

    form.controls['firstName'].validator = ZipValidator.validate
    form.controls['firstName'].updateValueAndValidity(...);

I haven't tested myself yet if validation still works as expected afterwards.

**Comment by vishal123** [comment]
Thanks @zoechi!! 
I was doing this in a function that was being called on valueChanges and hence ran into issues due to the value being updated again.
Weirdly when only calling the function on a single control it worked fine, doing so on multiple controls caused a memory leak.

Having looked at the code i was able to call `updateValueAndValidity({onlySelf: true, emitEvent: false})` which so far seems to do the trick.

I think having add and remove functions that revalidate would be a more intuitive api.

But problem solved for me :+1:

**Comment by awerlang** [comment]
You can compose validators yourself, instead of messing with internal APIs.

```
    form = fb.group({
      "firstName": ['', Validators.required], // first list item is the initial value for the control
      "streetAddress": ['', Validators.required],
      "zip": ['', c => {
        return mustValidateZip() ? ZipValidator.validate : null
      }],
      "type": ['home']
    });
```

This is definitely the way to go.

The thing is, should the control be revalidated because an external condition changed, you'll need to call yourself `updateValueAndValidity()`.

**Comment by kara** [comment]
Thanks to @thelgevold, setting and clearing validators on existing controls was added in in RC.4.  See https://github.com/angular/angular/pull/9516.
