### ISSUE TITLE
Form and ControlValueAccessor

### ISSUE THREAD

**Issue by fredgate** [angular/angular#6899]
This is a feedback and reflection on the form of developments after a bit extensive use of FormBuilder, Control and Validator... There are some nice things, but the overall feeling is rather mixed.

Making a form with angular 2 remains incredibly complicated, even if validations management is well designed. The problem lies mainly in data typing level. For strings, it goes well, by cons to everything else, it gets complicated seriously. It is for example the case for integer and date.

The operation of the ControlValueAccessor is incomplete and causes a lot of problems :
1. The directives are automatically activated without even knowing it from standard HTML attributes. This makes it difficult or impossible to change this behavior. For example, the directive NumberValueAccessor works with real, but what if you have a field that accepts only integers ?
2. The selector of the directives can have CSS style effects. It is the case of the NumberValueAccessor which has a selector like type="number". This cause spinners to appear inside the input field, which is often not desired. Data type and style are two diffrent things, so the selector should not be based on the type attribute.
3. The directives are automatically activated which causes collisions. For example the DefaultValueAccessor and CheckboxValueAccessor can be activated for the same input field because their selectors match. To avoid this the selector of DefaultValueAccessor need to explictly exclude the selector of CheckboxValueAccessor ( input:not([type=checkbox])[ngControl] ). However it should not have dependency on it. What about the NumberValueAccessor? What happens if I add a custom ControlValueAccessor or recovers a third library.

Other people are also aware of the problems caused by the operation of ControlValueAccessor :
- suspicious solutions are envisaged to overcome this problems : #3011
- how to have custom getter/setter : #5342

Finally, would not it be better to have to explicitly specify the type of data that we want via a specific directive selector (or a attribute of the control class) : 
```
<input [(ngModel)]="model.name" ngDefaultControl />
<input [(ngModel)]="model.size" ngIntegerControl />
<input [(ngModel)]="model.weight" ngFloatControl />
<input [(ngModel)]="model.birthDate" ngDateControl />
```

**Comment by KrzysztofBogdan** [comment]
Please also note, that single ControlValueAccessor might not be enough in some cases.
For example I would like to control value from multiple directives:
`<input [(ngModel)]="model.birthDate" ui-datepicker [ui-mask]="YYYY-MM-DD"/>`
where ui-datepicker and ui-mask would modify model.

AFAIK current state of NgModel does not allow such possibility.

**Comment by kara** [comment]
@fredgate Thanks for the detailed issue.  Because it was posted in February, a lot has changed with forms.  

Directives are no longer activated automatically, as the`FormsModule` and the `ReactiveFormsModule` are opt-in and need to be imported explicitly.  Regardless, if you'd like to create a form control that accepts only integers (for example), creating a custom value accessor is the preferred solution.  Custom accessors will always override built-in accessors, so the NumberValueAccessor would become a noop.

@KrzysztofBogdan What you describe is definitely a use case we want to support. It sounds like it would be encompassed by a parser/formatter solution. See https://github.com/angular/angular/issues/3009 to track progress on that.

I'm closing this, as it seems some of the original concerns have been addressed and this issue is pretty old. If you have more/updated feedback, feel free to open a new issue. Plunker examples of where the API falls short is also welcome and helpful.
