### ISSUE TITLE
@Input should support conversion from string to types

### ISSUE THREAD

**Issue by hansl** [angular/angular#6919]
I didn't see any issues and I verified the code doesn't do the right thing (currently).

It would be nice to have support for something like this:
```typescript
@Component({ /* ... */ })
class MyComponent implements AfterContentInit {
  @Input() myNumberInput: number;
  ngAfterContentInit() {
    assert(typeof this.myNumberInput == 'number');
  }
}
```

Right now this does not work as attribute values (which are strings) are blindly set to the member without any regard to typing.

Using the reflection metadata from TypeScript we know the type of the property, which would allow us to do something as simple as 
```typescript
let T = getTypeOfMember();
setValueOfMember(new T(stringValue));
```

Which would also allow us to use Dates (or even custom classes).

If you want I can make a design doc for this and/or attempt a PR, to discuss potential implementations.

**Comment by robwormald** [comment]
Like you said, attributes *are* strings, so it feels quite strange to cast them to something else automagically, no? 

Types in TS are purely a compile-time construct, and it wouldn't work in ES5 or ES6 in either case, so you'd need some other typescript like DSL for those languages, right?

Given that using `[someprop]` type input does pass types appropriately, it seems like a lot of overhead for a limited usecase - should we not encourage `[date]="someDate"` vs `date="2015-11-25"` ?

Hmm. What sort of use cases were you thinking? (This could probably done with a wrapper around the @Input, or with a setter for most cases....)

**Comment by hansl** [comment]
The problem comes from unexpectedly propagating values in a (strong-ish) type system that aren't type validated. This goes against TypeScript. No one naively would expect the code above (in my first example) to assert. When sending those to servers or making calculations with them it could become a problem (as `+` operator on strings is concatenation).

**Comment by poke** [comment]
> This goes against TypeScript. No one naively would expect the code above (in my first example) to assert.

But TypeScript does not perform any type validation. Types are only a compile-time thing, and there is nothing that guarantees you that values at run-time match the type you specified at compile-time. Since the inputs are set dynamically at run-time, there isn’t anything that could perform a type conversion there since the target type is no longer available at that point.

Also, it isn’t really clear how such a conversion would work. It isn’t even clear on whether to use `parseFloat` or `parseInt` for a target type of `number`. And it becomes even more unclear with more complex (or own) types.

One possibility would be to have `Input()` accept an optional argument that provided some “conversion function” that is applied whenever the attribute value is processed.

But personally, I wouldn’t want a function to run every time the value is updated. And if you want custom types, you can use the binding syntax to set non-string values. For example `<test [myNumberInput]="5"></test>` would set a *number* to your input value while `<test myNumberInput="5"></test>` sets a string.

If there is anything to be done here, it’s compile-time type validation within templates, so the latter would raise an error if the input is of a different type than string.

**Comment by zoechi** [comment]
If you want your custom conversion just create a custom `ControlValueAccessor`

**Comment by hansl** [comment]
Closing this as the offline compiler will provide proper type information and invalid usage of typing will trigger compiler errors.
