### ISSUE TITLE
Refactor test suffixes and folders

### ISSUE THREAD

**Issue by tbosch** [angular/angular#692]
Change gulpfile

Suffixes:
- `*.perf.es6`: protractor with benchpress enabled
    - previous: e2e_test/**/*_perf.js
- `*.e2e.es6`: protractor with benchpress disabled
    - previous: e2e_test/**/*_spec.js
- `*.spec.js/.es6/.dart`: karma-js / karma-dart tests
    - previous: test/**/*_spec.js/.es6/.dart
- `*.spec.server.es6/*.spec.server.dart`: jasmine / guiness command line tests
    - previous: tools/transpiler/unittest/transpilertest.js

Folders:

- Move unit tests into `src` folder as well (see e.g. See https://github.com/johnpapa/angularjs-styleguide#style-y197)
- Move e2e/perf tests in the folder that contains the html page that they test

**Comment by tbosch** [comment]
For the benchpress smoke tests we will have more command line tests...

**Comment by tbosch** [comment]
@iminar what do you think?

**Comment by IgorMinar** [comment]
I think that we should get rid of the separate test/ tree. Move unit tests to be on the same level as source files and move perf and e2e tests into separate directories called _e2e and _perf within individual src directories

that way things stay together but are logically split so that we don't have hundreds of files in each directory

the reason why unit tests should be mixed with source files is that they should mirror the source closely and they also serve as a documentation for the source file, so having them in a separate directory makes discovery hard.

the extensions as proposed are fine.

**Comment by tbosch** [comment]
Update the description above

**Comment by mhevery** [comment]
Is this still an issue? Can this be closed?

**Comment by yjbanov** [comment]
I also have a feeling this is a solution looking for a problem. Do we feel a lot of pain from the current setup or is this just a style preference of a couple of folks?

**Comment by naomiblack** [comment]
Not important unless we hear user pain...
