### ISSUE TITLE
required validator does not work with number

### ISSUE THREAD

**Issue by fredgate** [angular/angular#6932]
The required validator does not work with a input whose type is number : 
`<input type="number" ngControl="weight" />`
```
this.form = fb.group({
  weight: ["", Validators.required]
});
```

When the input is empty, no error appear.

The reason is that the NumberValueAccessor selector match the input, and set the value of the Control to a number. If the entered string of the input does not match a number, the value is NaN. This is the case for the empty string.
But the required validator return a error only if the control value is blank (null or undefined) or is a empty string. This is not the case of any of these two conditions because the NumberValueAccessor set the value to the NaN number.

The required validator can not really verify the NaN value because it can appear for empty string, but also for string that are not a number (like 'aaa'). The problem is that the validator can not retrieve the entered string from the control variable.

**Comment by danielfigueiredo** [comment]
:+1: 

I ran into the same issue, I think NumberValueAccessor should be updated. I created a branch in my angular/angular fork that fix this.
https://github.com/danielfigueiredo/angular/commit/be7ccadf0b5501a8720532d88be9272d4f68225f

**Comment by ericmartinezr** [comment]
@danielfigueiredo you should send a PR if you have a fix

**Comment by danielfigueiredo** [comment]
@ericmartinezr not sure if this is the best way to do it

**Comment by ericmartinezr** [comment]
@danielfigueiredo just send it :D and it will reviewed by the ng2 team, they will tell you if it is ok or not. That's a very good way to learn :D. Send it! :D

**Comment by fredgate** [comment]
I do not thinl that NumberValueAccessor should be updated. Its job is to convert the text entered in the input field to a number, and when the text is empty it appears appropriate to return NaN.
I tend to think that the Required validator should check for the NaN value.

**Comment by ericmartinezr** [comment]
@fredgate didn't want to contaminate your PR, so I'm going to comment here. Shouldn't this be handled in NumberValueAccessor? My point here is that Validators.required needs a value to fulfill the requirement and NaN is a valid value representing a Not-A-Number (please correct me if I'm wrong). I mean, what if I want/need to require a NaN? (Would a case like that even exist? Don't know, but who knows :P). I think this should be handled by NumberValueAccessor (it would be more correct, it's its job to handled such things) which should be valid only and only if the value is a number and not a NaN. I would really love ng2 team involvement in this issue to clarify spec related stuff :D

**Comment by ericmartinezr** [comment]
I came to shut my own mouth :P . This little [fiddle](https://jsfiddle.net/7nk3tqgq/) shows that having a input type number with required and trying to assign NaN as value won't work, it's still required. But I still think this should be more correct handling it in NumberValueAccessor.

**Comment by danielfigueiredo** [comment]
Either way is a very simple fix =]

**Comment by fredgate** [comment]
Is NaN a valid value ? That is the question. I would say no, as it represents either a arithmetic error or a parsing error (see https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/NaN). It is not a value that can be entered by user in an input field and that we would need to validate.

NumberValueAccessor is a ControlValueAccessor. The role of ControlValueAccessor is to act as a bridge between a angular control and a native element. It can write a value in the input field, and notify changes. NumberValueAccessor convert the text entered by the user to a number. If the text is not a number, the special value NaN is returned. It is also the case for the empty string. I do not see what NumberValueAccessor could do more; it is not a validator. Ideas ?

**Comment by danielfigueiredo** [comment]
The reason why I think NumberValueAccessor should be updated is because the user haven't typed anything wrong. There is no value there to be incorrect, the input is empty, so that was the reason I thought the accessor should deal with this. It doesn't look right to me an empty input hold NaN as its value.

**Comment by danielfigueiredo** [comment]
Thinking more about that, changing validator required method to deal with NaN might remove the flexibility to deal with other scenarios. 
For example if I have a custom validator that performs a validation and parses the control value, but that control value should be a number and is not. My control would have NaN as a value and then required validator is call.
Updating the validator would result saying the field is empty, because it deals with NaN as empty value, however the field as an invalid value (NaN, but it has a value), if the UI that checks validation errors it would display two messages field required and invalid. That is why I think NumberValueAccessor should be smart enough to understand that empty input type=number can return empty string when the field is empty, thereafter it should not throw invalid value since there is no value.

**Comment by ericmartinezr** [comment]
>Is NaN a valid value ? That is the question

>I agree that NaN is not a valid value

My point was that NaN is a value, representing something valid or not. But who cares about that? Validators.required or NumberValueAccessor? Validators.required requires a value, but should only require *valid* values, or *invalid* values fulfill the requirement to have a value as well?

At this point I agree with both of you, lol. So I'll wait for an official opinion :P.

**Comment by fredgate** [comment]
A officiel opinion could effectively advance the discussion.
However we must keep in mind that NumberValueAccessor is an accessor that converts the text entered by the user to a numeric value. Its role ends there. When NumberValueAccessor is used, the value of the controls should always be numeric; it should not be a string (even empty). I think this is very important.
By cons, maybe in the case of an empty string, it could return null or undefined instead of NaN which would be reserved for non-empty and non-numeric texts. It might be the right solution. In this case, only NumberValueAccessor would need to be changed, because Validators.required already handles null values.

**Comment by danielfigueiredo** [comment]
@fredgate @ericmartinezr it all makes sense. Specially because HTML input type number does not allow user to type anything different than numbers. However it sends empty string when the input value is cleared.

**Comment by fredgate** [comment]
A ValueAccessor assures the mapping between the text in the input field (in the DOM) and the value of the angular control. So when a NumberValueAccessor  is used, the value of the angular control (not the DOM input) should always be a numeric and never a string.

**Comment by giorgiofran** [comment]
I think it should return 0.0 when the user clears the input (and input type number returns an empty string).

**Comment by fredgate** [comment]
If it returns 0.0 for empty string, we could not make the differnce when the user enter the 0 value.
IMHO it is not a option.

**Comment by pankajparkar** [comment]
@danielfigueiredo `type="number"` does allowed **e** character in it, which stands for exponential.

**Comment by danielfigueiredo** [comment]
@fredgate 0.0 sounds good to me as well!
I could update the fix inside the PR to support that, but let's hear from angular team first
@pankajparkar yes, you're right, but that is not a problem since it is parsing to Float, the parseFloat supports `2e2` that would return `200` after parsed for example. The problem is when the user types `e2` it is a `NaN` after parsed. For this case I think required validator should not return `required` error, because there is an information inside the field. Whether that information is invalid or not, required validator shouldn't care in my opinion. That is another type of validation.
The current problem is when user touches the field, and then leave it blank. `ControlValueAccessor` receives empty string form the dom element, which leads to `NaN`, but in this case I think `NaN` is not appropriate because user hasn't provided any value to the input field, thereafter it should be faced as empty (either `null` or `0`) rather than `NaN`.

**Comment by danielfigueiredo** [comment]
@giorgiofran @fredgate Thinking more about it, returning `0` instead `null` when input is empty looks a little bit dirty to me. 
Many cases having `null` stored instead of `0` makes different in queries, etc. Of course we could remove the field value if is equal to `0`. But that always leads me to the same question, is it right for Angular to assume that all empty fields have value `0`?
Moreover `0` and `null` are different, `0` means that some value was entered and null means the opposite. `null === 0` -> false
I don't know, my vote is still to have `null` value for empty number inputs.
My understanding of a pure generic behaviour would be:
- If input is touched or not and is empty, value in `Control` should be `null`
- If input has value, `NumberControlValueAccessor` should parse and set the value as the result, doesn't matter whether it is `NaN` or not. In other words it doesn't care if parsing was successful.
That way as far as I can tell, everything works for all cases without having to change anything else, i.e. if value is `0`, or change required validator to check for `NaN`.

**Comment by giorgiofran** [comment]
I understand that returning null is **the** correct solution.
0 is a little dirty, yes, but consider that a lot of systems give the possibility of showing a field containing zero as empty. This is commonly accepted in many programs, but I understand that there can be cases in which we have to differenciate. 
Resuming, +1 for null. Forget about 0.

**Comment by DrewynV** [comment]
__________________________________

Hi! We just wanted to let you know we receievd your email. Thank you for submitting your request. Our aim is to get back to you within 24 hours at the latest. If you have any additional information to add to your request, please reply to this email.


Also please visit our knowledgebase (http://www.support.magicdust.com.au) to browse for further info, we are adding to it all the time.

Or here is our industry report about the 11 Essentials for a Successful Website (http://www.magicdust.com.au/web-design/.

We look forward to helping you succeed online.

Thanks

The Team @ Magicdust Digital

http://support.magicdust.com.au/

Ph (02) 9979 7474
M-F | 9 am-5:00 pm AEST (AEDT in Summer) excluding Public Holidays

------------------------------------------------------------------------------------------------------------
This message was sent to  reply@reply.github.com in reference to Case #166601.
------------------------------------------------------------------------------------------------------------


[[7d2d38894a7b3beb1198fd9cdbfec84742b4f46d-673074600]]

**Comment by DrewynV** [comment]
__________________________________

Hi! We just wanted to let you know we receievd your email. Thank you for submitting your request. Our aim is to get back to you within 24 hours at the latest. If you have any additional information to add to your request, please reply to this email.


Also please visit our knowledgebase (http://www.support.magicdust.com.au) to browse for further info, we are adding to it all the time.

Or here is our industry report about the 11 Essentials for a Successful Website (http://www.magicdust.com.au/web-design/.

We look forward to helping you succeed online.

Thanks

The Team @ Magicdust Digital

http://support.magicdust.com.au/

Ph (02) 9979 7474
M-F | 9 am-5:00 pm AEST (AEDT in Summer) excluding Public Holidays

------------------------------------------------------------------------------------------------------------
This message was sent to  reply@reply.github.com in reference to Case #166647.
------------------------------------------------------------------------------------------------------------


[[11f3893efd02bd16cfaa7407acb07447931b08cb-673075435]]

**Comment by DrewynV** [comment]
__________________________________

Hi! We just wanted to let you know we receievd your email. Thank you for submitting your request. Our aim is to get back to you within 24 hours at the latest. If you have any additional information to add to your request, please reply to this email.


Also please visit our knowledgebase (http://www.support.magicdust.com.au) to browse for further info, we are adding to it all the time.

Or here is our industry report about the 11 Essentials for a Successful Website (http://www.magicdust.com.au/web-design/.

We look forward to helping you succeed online.

Thanks

The Team @ Magicdust Digital

http://support.magicdust.com.au/

Ph (02) 9979 7474
M-F | 9 am-5:00 pm AEST (AEDT in Summer) excluding Public Holidays

------------------------------------------------------------------------------------------------------------
This message was sent to  reply@reply.github.com in reference to Case #166792.
------------------------------------------------------------------------------------------------------------


[[8c67582e5e722681abeb0022e49ef5f2fa97be21-673085458]]
