### ISSUE TITLE
Equivalent to autoscroll=true: automatic scroll to top when route changes 

### ISSUE THREAD

**Issue by pcroc** [angular/angular#6946]
When navigating within our SPA, we want to scroll back to the top of the page whenever the route changes. Users have commented that it is really odd if clicking a link at the foot of the page causes the content to change but leaves you still at the bottom.

I'm not sure how best to handle this scenario, and would like to avoid having to add code to every top level component. This feels like the kind of thing that should be part of Angular itself, like autoscroll=true in Angular 1.

**Comment by pcroc** [comment]
```
    router.subscribe(() => {
      window.scrollTo(0, 0);
    });
```

**Comment by zoechi** [comment]
see also #6595

**Comment by afirdousi** [comment]
dup of #6595

**Comment by cortopy** [comment]
For router 3.0.0-beta.2 this works:

```javascript
this.router.events.subscribe((path) => {
      if (path.url != this.url) {
        window.scrollTo(0, 0);
      }
 });
```

**Comment by felipedrumond** [comment]
What if I'm navigating back? I can't scroll to top, I must recover the previous scroll. How to deal with it?

**Comment by kkuksin** [comment]
@felipedrumond 
Did you found something to deal with this case?

**Comment by felipedrumond** [comment]
Hi @kkuksin, I did not find, so I had to implement it. Check this [10929](https://github.com/angular/angular/issues/10929)

**Comment by corbfon** [comment]
@felipedrumond, just as another way to get the functionality you were talking about, you could implement the `RouteReuseStrategy`. That way you could save the state of the page which you, essentially, wanted to re-render. It would also save you service calls and make the user experience slightly better because of increased speed. Check out [this Stack Overflow](http://stackoverflow.com/questions/41280471/how-to-implement-routereusestrategy-shoulddetach-for-specific-routes-in-angular/41515648#41515648) for some details on how I've used the `RouteReuseStrategy` to accomplish exactly what you're asking

**Comment by felipedrumond** [comment]
Hi @corbfon. If RouteReuseStrategy will keep the scroll position of my components I'm not sure, because you didn't explicitly mention that on Stack Overflow, but if you are contributing to this issue, I want to believe that strategy will make the job for me! Also, that strategy you shared will help me a lot in my e-commerce website, because it will make the navigation faster and speed is a key factor that impacts revenue.
Thanks for sharing!

**Comment by RonAlmog** [comment]
@cortopy , where is this code going?

**Comment by corbfon** [comment]
@felipedrumond The implementation on my site keeps all of the scroll positions and text in place!

**Comment by RonAlmog** [comment]
never mind. i used the solution provided here:
http://stackoverflow.com/questions/26444418/autoscroll-to-top-with-ui-router-and-angularjs

$rootScope.$on('$stateChangeSuccess', function() {
   document.body.scrollTop = document.documentElement.scrollTop = 0;
});

or even better,
$rootScope.$on('$stateChangeSuccess', function() {
   $document[0].body.scrollTop = $document[0].documentElement.scrollTop = 0;
});
only remember to inject your $document in your run function.

**Comment by leonoraPanas** [comment]
@RonAlmog this is for angular 1, not angular 2

**Comment by padrian** [comment]
@RonAlmog ; try this; worked for me;

[https://stackoverflow.com/questions/39601026/angular-2-scroll-to-top-on-route-change](url)

**Comment by mahesh5b5** [comment]
@RonAlmog  URL not found

**Comment by felipedrumond** [comment]
Might be this URL: https://stackoverflow.com/questions/39601026/angular-2-scroll-to-top-on-route-change

**Comment by sal-vader** [comment]
Late to the party, but here's my two cents...

	export class AppComponent implements OnInit {
	  isPopState = false;
	  
	  constructor(private router: Router, private locStrat: LocationStrategy) { }
	  
	  ngOnInit(): void {
		this.locStrat.onPopState(() => {
		  console.log('onPopState is running');
		  this.isPopState = true;
		});
		
		this.router.events.subscribe(event => {
		  // Scroll to top if accessing a page, not via browser history stack
		  if (event instanceof NavigationEnd && !this.isPopState) {
			window.scrollTo(0, 0);
			this.isPopState = false;
		  }
		  
		  // Ensures that isPopState is reset
		  if (event instanceof NavigationEnd) {
			this.isPopState = false;
		  }
		});
	  }
	}
