### ISSUE TITLE
Remove import of dart:mirrors

### ISSUE THREAD

**Issue by kegluneq** [angular/angular#700]
`reflection_capabilities.dart` imports dart:mirrors, so we need to remove it from the source.

Currently, [examples/src/hello_world/index.dart][1] directly imports & creates `ReflectionCapabilities`, but if possible we should avoid having the user deal with this directly. This is made a bit more complicated since transformers cannot write across package boundaries.

One option would be to use `bootstrap` as a seam. If we do this, we should probably move `bootstrap` into its own file to avoid having to rewrite all imports of `angular2/angular2.dart`.

In a new file, maybe `lib/src/core/life_cycle/bootstrap_internal.dart`:

    Future<Injector> bootstrapInternal(...) {
      // Actual bootstrapping
    }

We could move `bootstrap` into, say, `lib/bootstrap.dart`:

    import '.../reflection_capabilities.dart';
    import 'application_internal.dart';
    Future<Injector> bootstrap(...) {
      reflector.reflectionCapabilities = new ReflectionCapabilities();
      return bootstrapInternal(...);
    }

In the generated code:

    // examples/web/src/hello_world/index.bootstrap.dart (generated)
    Future<Injector> bootstrap(...) {
      // Generated registration code
      return bootstrapInternal(...);
    }

And we rewrite the user's calls to `bootstrap` to use our generated call.

This involves some moving around of files, messing around with imports, and completely ignores how this would affect the js side of things, so it may not be the appropriate solution -- just somewhere to start the discussion.

[1]: https://github.com/kegluneq/angular/blob/review/modules/examples/src/hello_world/index.js

**Comment by mhevery** [comment]
After discussing the issue with the team it was decided that the current approach is the safest.

Dependencies are: `Reflection` <- `DI` <- `Angular`

assume this code:
```
reflection.reflector = new ReflectionCapability();
var module = [
    MyType,
    bind(MyComponent).toClass(MyComponentImpl);
  ]

var injector = createInjector(module);
```

In the code above the call to `bind(MyComponent)` requires us to lookup constructors in the `reflection` This means that the correct reflector already has to be set up.

But notice that `MyType` is not wrapped in the `bind()` method. This is a short hand syntax, which means that the `reflection` call is delayed until inside the createInjector.

Implications:

1. Declaring dependencies in module (before creating injector) requires the correct `ReflectionCapability`.
2. `ReflectionCapability` during the application runtime must be same as during module declaration since some bindings have delayed lookup in the `Reflector`.

Now imagine an application such as this:

```
// setup google Analytics
reflection.reflector = new ReflectionCapability();
createInjector([GoogleAnalytics]).get(GoogleAnalytics).run();

// bootsrap angular app.
bootstreap(MyApp);
```

Here before we get our application going, we register `GoogleAnalytics`, but we do it with DI (which is totally reasonable.) This means that we can't change the reflector in `bootstrap()` since that is after we configured `GoogleAnalytics`.

I think there are two problems.

1. Because `DI` is a standalone library and because `DI` depends on `Reflector`, the `Reflector` must be configured before the first use of `DI`
2. Because `Angular` depends on `DI` it can not assume that it will be the first user of `DI` as a result `Angular` can not configure the `Reflector`. 

I think it means that only the developer is in the correct position to know when the `Reflector` needs to be configured and the transformer should simply rewrite the `ReflectorCapabilities` and the `import` statement.

**Comment by mhevery** [comment]
I am going to close this Issue, as I think the correct implementation is correct. (Reopen if you feel otherwise.)

**Comment by kegluneq** [comment]
Thanks for the explanation and no disagreement about the approach. I am going to reopen the bug to track the work to rewrite the import & `ReflectionCapabilities` assignment.

A couple of questions:
 * Do I understand correctly that the call to `setupReflection` (or whatever our generated method is) should replace the `ReflectionCapability` assignment? That is, in the above example it should appear immediately before the `createInjector` call?
 * What does `DI`'s status as a separate package mean codegen-wise? Do we need a transformer for `DI` independent of Angular2? As things stand now, if `GoogleAnalytics` is not declared as a service by `MyApp` or one of its dependencies, it will not be included in the codegen since `bootstrap` is our signal to start searching for annotations.

**Comment by kegluneq** [comment]
Assigned for answers (looks like emails may not have been sent about this issue) -- reassign once updated.

**Comment by mhevery** [comment]
@kegluneq 

1. Yes setupReflection should take over the assignment to `RoflectionCapability`
2. Yes, long term we want to pull out the DI as a separate package. When that happens it will have to have its own transformer. I think we will need to think deeper about it then as how to break the transformers up.
