### ISSUE TITLE
QueryList<> interface is not iterable in TypeScript

### ISSUE THREAD

**Issue by hansl** [angular/angular#7022]
The `d.ts` generated does not contain the `Symbol.iterator` member (and does not implement the Iterable interface). That would be okay if we could use `toArray()` but the Dart implementation is missing that declaration.

**Comment by zoechi** [comment]
There is a PR for `forEach` #6314, #6341. 
I tried `.map()` recently and it doesn't seem to be implemented in Dart even though it can be called, but has no effect. (I'll check again later and file an issue)

**Comment by araujoigor** [comment]
Adding `[Symbol.iterator](): any;` manually to query_list.d.ts would do the trick temporally.

**Comment by juanmaflyer** [comment]
In **2.0.0** QueryList still isn't an Iterable. Here is a demo:

http://plnkr.co/edit/oeTcVe0jrtDjalN3nJdz?p=preview

Moreover, the docs are confunsing because it says "Implements an iterable interface, therefore it can be used in both ES6 javascript for (var i of items) loops as well as in Angular templates with *ngFor="let i of myList".

https://angular.io/docs/js/latest/api/core/index/QueryList-class.html

**Comment by zoechi** [comment]
`toArray()` can now be used. Dart is not a dependency anymore.

**Comment by vicb** [comment]
@juanmaflyer it actually seems like a bug in TS. Investigating.

**Comment by vicb** [comment]
@juanmaflyer TS assumes the object is either a string or an array when using `for..of` and the target is < ES2015.

**Comment by hansl** [comment]
@vicb: did you file a bug with typescript? I don't see it.

**Comment by mafredri** [comment]
Is there anything blocking this now that TypeScript supports the `downlevelIteration` option (https://github.com/Microsoft/TypeScript/issues/3164#issuecomment-295968922)?

**Comment by Marijus** [comment]
jkfh\sorry
