### ISSUE TITLE
Angular2 repeater doesnt work if data is coming from parent component

### ISSUE THREAD

**Issue by malichishti** [angular/angular#7029]
i have a repeater template  `<li *ngFor="#command of Commands">` it works fine as long as the array is created in current component, but as soon as i add @Input to the array and make it come from parent component it stops working??

**Comment by malichishti** [comment]
i have put {{Commands | json}} in the component, and i can see data is coming through from parent But the repeater doesn't work

**Comment by robwormald** [comment]
please replicate this in a plunker https://plnkr.co/edit/tpl:AvJOMERrnz94ekVua0u5

**Comment by malichishti** [comment]
I have replicated it at https://plnkr.co/edit/pX2H0rqBKZ3QpV8NisjP

**Comment by ericmartinezr** [comment]
If Rob lets me answer...

```
<bank-account [Commands]="[Commands]"></bank-account>
```

You have extra brackets. The input should have brackets, not the expression.

**Comment by malichishti** [comment]
That did it, thank you.
I'm new to angular so apologies for the silly question.

**Comment by robwormald** [comment]
The idea of the brackets `[Commands]="Commands"` is to tell angular "the thing on the right side of the equals sign is something from my class" rather than a regular string.

also, it's not *wrong* but typically in Javascript such things are declared in camelCase - so [commands]="someCommands" - Things that Start with Capitals are generally Classes.

You might also find this useful https://angular.io/cheatsheet

**Comment by malichishti** [comment]
Got it, i'm coming from c# world :D where public properties are in Capitals.
Thanks
