### ISSUE TITLE
angular2@2.0.0-beta.6 refuses to build

### ISSUE THREAD

**Issue by nhhockeyplayer** [angular/angular#7052]
Please goto this uploaded project to reproduce
https://github.com/nhhockeyplayer/build-beta

Here is TSC output (thanks for taking a look)

C:\apache-tomcat-8.0.23\webapps\ROOT\new\gulp.connect>tsc
node_modules/angular2/src/core/change_detection/parser/locals.d.ts(3,14): error TS2304: Cannot find name 'Map'.
node_modules/angular2/src/core/change_detection/parser/locals.d.ts(4,42): error TS2304: Cannot find name 'Map'.
node_modules/angular2/src/core/debug/debug_node.d.ts(14,13): error TS2304: Cannot find name 'Map'.
node_modules/angular2/src/core/debug/debug_node.d.ts(24,17): error TS2304: Cannot find name 'Map'.
node_modules/angular2/src/core/debug/debug_node.d.ts(25,17): error TS2304: Cannot find name 'Map'.
node_modules/angular2/src/core/di/provider.d.ts(436,103): error TS2304: Cannot find name 'Map'.
node_modules/angular2/src/core/di/provider.d.ts(436,135): error TS2304: Cannot find name 'Map'.
node_modules/angular2/src/core/render/api.d.ts(13,13): error TS2304: Cannot find name 'Map'.
node_modules/angular2/src/core/render/api.d.ts(14,84): error TS2304: Cannot find name 'Map'.
node_modules/angular2/src/facade/collection.d.ts(1,25): error TS2304: Cannot find name 'MapConstructor'.
node_modules/angular2/src/facade/collection.d.ts(2,25): error TS2304: Cannot find name 'SetConstructor'.
node_modules/angular2/src/facade/collection.d.ts(4,27): error TS2304: Cannot find name 'Map'.
node_modules/angular2/src/facade/collection.d.ts(4,39): error TS2304: Cannot find name 'Map'.
node_modules/angular2/src/facade/collection.d.ts(7,9): error TS2304: Cannot find name 'Map'.
node_modules/angular2/src/facade/collection.d.ts(8,30): error TS2304: Cannot find name 'Map'.
node_modules/angular2/src/facade/collection.d.ts(11,43): error TS2304: Cannot find name 'Map'.
node_modules/angular2/src/facade/collection.d.ts(12,27): error TS2304: Cannot find name 'Map'.
node_modules/angular2/src/facade/collection.d.ts(14,23): error TS2304: Cannot find name 'Map'.
node_modules/angular2/src/facade/collection.d.ts(15,25): error TS2304: Cannot find name 'Map'.
node_modules/angular2/src/facade/collection.d.ts(95,41): error TS2304: Cannot find name 'Set'.
node_modules/angular2/src/facade/collection.d.ts(96,22): error TS2304: Cannot find name 'Set'.
node_modules/angular2/src/facade/collection.d.ts(97,25): error TS2304: Cannot find name 'Set'.
node_modules/angular2/src/facade/lang.d.ts(13,17): error TS2304: Cannot find name 'Map'.
node_modules/angular2/src/facade/lang.d.ts(14,17): error TS2304: Cannot find name 'Set'.
node_modules/angular2/src/facade/lang.d.ts(78,59): error TS2304: Cannot find name 'Map'.
node_modules/angular2/src/facade/promise.d.ts(1,10): error TS2304: Cannot find name 'Promise'.
node_modules/angular2/src/facade/promise.d.ts(3,14): error TS2304: Cannot find name 'Promise'.
node_modules/angular2/src/facade/promise.d.ts(8,32): error TS2304: Cannot find name 'Promise'.
node_modules/angular2/src/facade/promise.d.ts(9,38): error TS2304: Cannot find name 'Promise'.
node_modules/angular2/src/facade/promise.d.ts(10,35): error TS2304: Cannot find name 'Promise'.
node_modules/angular2/src/facade/promise.d.ts(10,93): error TS2304: Cannot find name 'Promise'.
node_modules/angular2/src/facade/promise.d.ts(11,34): error TS2304: Cannot find name 'Promise'.
node_modules/angular2/src/facade/promise.d.ts(12,32): error TS2304: Cannot find name 'Promise'.
node_modules/angular2/src/facade/promise.d.ts(12,149): error TS2304: Cannot find name 'Promise'.
node_modules/angular2/src/facade/promise.d.ts(13,43): error TS2304: Cannot find name 'Promise'.
node_modules/angular2/src/http/headers.d.ts(43,59): error TS2304: Cannot find name 'Map'.
node_modules/angular2/src/http/url_search_params.d.ts(11,16): error TS2304: Cannot find name 'Map'.
node_modules/angular2/src/platform/browser/browser_adapter.d.ts(75,33): error TS2304: Cannot find name 'Map'.
node_modules/angular2/src/platform/dom/dom_adapter.d.ts(85,42): error TS2304: Cannot find name 'Map'.
node_modules/rxjs/CoreOperators.d.ts(35,67): error TS2304: Cannot find name 'Promise'.
node_modules/rxjs/CoreOperators.d.ts(50,66): error TS2304: Cannot find name 'Promise'.
node_modules/rxjs/CoreOperators.d.ts(89,67): error TS2304: Cannot find name 'Promise'.
node_modules/rxjs/CoreOperators.d.ts(94,38): error TS2304: Cannot find name 'Promise'.
node_modules/rxjs/CoreOperators.d.ts(94,50): error TS2304: Cannot find name 'Promise'.
node_modules/rxjs/Observable.d.ts(46,62): error TS2304: Cannot find name 'Promise'.
node_modules/rxjs/Observable.d.ts(47,42): error TS2304: Cannot find name 'Iterator'.
node_modules/rxjs/Observable.d.ts(103,74): error TS2304: Cannot find name 'Promise'.
node_modules/rxjs/Observable.d.ts(103,84): error TS2304: Cannot find name 'Promise'.
node_modules/rxjs/Observable.d.ts(143,66): error TS2304: Cannot find name 'Promise'.
node_modules/rxjs/Observable.d.ts(158,65): error TS2304: Cannot find name 'Promise'.
node_modules/rxjs/Observable.d.ts(201,66): error TS2304: Cannot find name 'Promise'.
node_modules/rxjs/Observable.d.ts(206,38): error TS2304: Cannot find name 'Promise'.
node_modules/rxjs/Observable.d.ts(206,50): error TS2304: Cannot find name 'Promise'.
node_modules/rxjs/observable/ForkJoinObservable.d.ts(6,50): error TS2304: Cannot find name 'Promise'.
node_modules/rxjs/observable/ForkJoinObservable.d.ts(7,58): error TS2304: Cannot find name 'Promise'.
node_modules/rxjs/observable/FromObservable.d.ts(7,38): error TS2304: Cannot find name 'Promise'.
node_modules/rxjs/observable/FromObservable.d.ts(7,51): error TS2304: Cannot find name 'Iterator'.
node_modules/rxjs/observable/PromiseObservable.d.ts(9,31): error TS2304: Cannot find name 'Promise'.
node_modules/rxjs/observable/PromiseObservable.d.ts(10,26): error TS2304: Cannot find name 'Promise'.

**Comment by lukaszczerpak** [comment]
If you use es5 target you may need to add the following line to your bootstrap file as stated in CHANGELOG (https://github.com/angular/angular/blob/master/CHANGELOG.md):

`
///<reference path="node_modules/angular2/typings/browser.d.ts"/>
`

**Comment by nhhockeyplayer** [comment]
WRONG... I dont want that solutioon

The solution was forced as follows

add the following lines to tsconfig.json


    "files":    [
        "app/app.component.ts",
        "app/app.boot.ts",
        "typings/browser/ambient/es6-promise/es6-promise.d.ts",
        "typings/browser/ambient/es6-collections/es6-collections.d.ts"
    ],

after 
typings install --save --ambient es6-promise es6-collections

WHEN IS SOMEONE GOING TO MANDATE THAT ALL TYPEDEFS BE LOCALIZED IN THE PACKAGE AT IONSTALL TIME WITH NPM ? SOME PACKAGES ARE ACTUALLY DOING THIS.
????????????????
AND TRASHCAN THE WHOLE TYPINGS ONCE AND FOR ALL. TSD WASNT ENOUGH?
I say blockage all libraries until they choose to conform and if they cannot conform exile them until they do confirm instead of creating an unending pile of heap and endless useless diagnostics work.

there remains no accountability for who where and why these crooked code impact/mandates are being forced upon the receiver of the framework (application developers)

all we know is every release something new is broken or needs to be performed (that no one knows about) in order to get their build to succeed.

Therefore unending hours and days are spent trying to troubleshoot this outrageous effort that remains out of control.

I will tell you when I go onsite to honor a client with angular and typescript the last frikkin thing I want to do is track every code module in a new build/compile file... has anyone ever thought gee well what if the consultant needs to operate 3500 files/modules. Why would anyone want to reiterate and relist that module in another ocnfig file in order to get this to work. I see the filesGlopb and files m,echanisma remain unfinished and undecided half way half done and hanging going nowhere.

for two years this is whats going on re-writes and new additions to the efrastruture (BUILD and COMPILE of languages and libraries just to get this to behave like java). No I am not going backl to JAVA enough impact has already been performed such that we are stuck with this for the long and short term for good.

when is someone going to fix this stuff for good and stop impacting the public at large.

I cannot for the life of me forsee myself designing or building anything that breaks or wipes out anyone else using it. Do you get anything out of that ? I also see these people publishing small snippets of learning maTEWRIAL THAT USELESS JUST TO GET THEIR NAMES PUBLISHED. 

i wish the ego would end and somethign get produced thats commercial grade. Open source is no excuse for this mess.

???

**Comment by KapuzenSohn** [comment]
Angular 2 is currently in beta. That there is `beta` says that the next release can have breaking changes. Angular 2 is not production ready!

**Comment by imatefx** [comment]
beta!!!

**Comment by nhhockeyplayer** [comment]
there should be NO BREAKING CHANGES period

what needs to be broken is the effort that is carrying this and remodeled 

i refuse to accept beta or open source to explain and rationalize this effort
I have seen endless issues page after page long in nature and everyone is pissed off
its been ongoing for two years and its still not gotten right

IT NEEDS TO CHANGE

**Comment by nhhockeyplayer** [comment]
these are gutter standards and its a damn shame that the good developers of high standards and quality are smothered by junior egotistical out of control process big mouths that cannot even write a compiler or library

sad globalist BS

Americans writes the best software

and I am insulted at this BS

**Comment by KapuzenSohn** [comment]
I really don´t get your point. A beta does not say that everything is implemted as it should be. Use angular 1 if you don´t wan´t breaking changes and a production ready product. Angular 2 is in BETA so breaking changes happen.

**Comment by nhhockeyplayer** [comment]
s0omeone needs to stop the spillover of typedefs into the build infrastructure of developers projects

a mandate needs to be instituted that any new package has to localize their typedefs within the package installation

we are tired of spending 80% of our development time troubleshooting this garbage
i speak for may developers that want to focus on pure businesses logic instead of some parade of idiots that cannot even write a damn line of code

who the hell is driving the ship

angular can take measures to perform this and I recommend they DO

**Comment by nhhockeyplayer** [comment]
you think transient dependencies are a problem now ?

wait til applications flood the field

**Comment by nhhockeyplayer** [comment]
measures need to be defensively taken by the industry managing this pioneering effort to weed out the youngbloods and ego brains... enough suffering has already been induced.

where is database migration ? do any of the young bloods know what I am talking about ? yeah... 
whats a database...

I got this vision some idiot python developer punched his fist thru the middle tier and created all this BS and MR BIG said... I want that, Its a shame none of them knew what the hell they were doing.

Its slow going and I am adding my 0.02 cents...

1. get typedef spillover the hell out of projects 
2. end the breaking changes disease

**Comment by pe8ter** [comment]
Typings is a tough nut to crack and the Angular team is trying to settle on the solution that's best for everyone. They're developing Angular 2 in public view so they can get feedback quickly and make the best library possible. No software project is perfect on its first release which is why (sometimes breaking) changes happen.

This is free software and the Angular team is not required to let you use it, nor are you required to update your Angular version so that you're affected by breaking changes.

The vitriol and insults are not needed.

**Comment by ericmartinezr** [comment]
@nhhockeyplayer out of curiosity, are you related to the guy on this issue https://github.com/angular/angular/issues/6204?

**Comment by nhhockeyplayer** [comment]
no comment
I am just better, thats what pisses people off
jamm your prejudice

**Comment by nhhockeyplayer** [comment]
I am a pro grade ice hockeyplayer... former pro, prospective pro  and junior pro
super disciplined form... something the real world knows nothing about
I live for crisp sizzling passes and I am seeing none as of now just a bunch of flak like now
beyond your class
when since did you drop 6lbs of sweat in full equipment... 
yeah
jamm your prejudice clown before I drop the gloves and take you to school

**Comment by nhhockeyplayer** [comment]
and thats whats so sad here is there is a global group of lowlives that are doing the same thing they did hundreds of years ago

trying to offload the cropping of their fields
and mowing of their lawns
by innocent slaves

take it any way they can...judgement has yet to come for that by the way

I dont need to write code that way
in fact I dont need code period

**Comment by imatefx** [comment]
Just out of curiosity, why did you choose angular 2 instead of angular 1 or any other framework ???

This is a community.. and open source means anyone can contribute..
if you feel so wrong ... feel free to involve in community and contribute.

**Comment by nhhockeyplayer** [comment]
typings is not tough...

Just tell es6-promises and es6-collections (and all those that angular2 depend on) to turn on the --declaration switch of the compiler and allow typedefs to be installed at npm install time. Thats it.

All typings is doing is what JAVA already did from day one... packages and types. This stuff shouldnt be churning with re-writes year after year.

google is responsible for angular and node... I remain unimpressed with their egotistical mgt. Potentially almost good stuff but it still isnt commercial grade ... close but not good enough for my standards. And if anyone is offended then they can continue playing in the minor league.

We are the folks that need to deal with this stuff in the field and attempt to obtain velocity... and so far its not safe.

**Comment by nhhockeyplayer** [comment]
its offensive that we have to modify not only our config files but our gulp scripts too to specify the proper new files (TYPEDEFS)

at this point I am not even sure anyone realizes what the ISSUE IS OR ITS EXTENT

does the fact that it impacts our configurations AND script build files raise any eye brows?

**Comment by nhhockeyplayer** [comment]
SO here is what I have to wrestle with typescript compilation

tsconfig.json
gulpfile.js

		src: [
			"typings/browser.d.ts",
			"typings/main.d.ts",
			"app/app.component.ts",
			"app/app.boot.ts",
			"typings/browser/ambient/es6-promise/es6-promise.d.ts",
			"typings/browser/ambient/es6-collections/es6-collections.d.ts",
			"typings/main/ambient/es6-promise/es6-promise.d.ts",
			"typings/main/ambient/es6-collections/es6-collections.d.ts",
			'app/app.component.ts',
			'app/app.boot.ts'
		]

i get duplicate id on the browser vs main branches

do I flip a coin to pick which one to compile against ?

is this even documented ?

when is google going to step in and eliminate some of this rifraf

**Comment by nhhockeyplayer** [comment]
I chose angular2 because its the closest thing to NORMAL

will it get NORMAL ? well the jury is still out

the scurrying language pundits are trying to make javascript java thru typescript

and I say at this time its time the boys step down and step aside and let the men take over and if that dont happen then the men need to step up and do whats right because I seen the casualties in the field and it isnt pretty

**Comment by KapuzenSohn** [comment]
Wow, what are you trying?
``` json
"typings/browser/ambient/es6-promise/es6-promise.d.ts",
"typings/browser/ambient/es6-collections/es6-collections.d.ts",
"typings/main/ambient/es6-promise/es6-promise.d.ts",
"typings/main/ambient/es6-collections/es6-collections.d.ts",
```
It is maybe a good idea to only use the browser or main folder? (I hope you find out the solution is yes)

You could replace the four lines with:
``` json
"typings/main/ambient/es6-promise/es6-promise.d.ts",
"typings/main/ambient/es6-collections/es6-collections.d.ts",
```

and in your tsconfig.json you add this

``` json
"exclude": [
"typings/browser/",
"typings/browser.d.ts"
]
```

oh and app.component.ts you also load twice. Maybe first think and not give others blame for your own stupidity?

**Comment by dsebastien** [comment]
Oh my, such aggressivity :)
If you want to get started and don't want to worry too much about the setup, take a look at my project generator: https://www.npmjs.com/package/generator-modern-web-dev I've just updated it for beta 6.

About the typings to exclude, there's a point explaining it in the docs of typings: https://github.com/typings/typings. There's also a discussion ongoing around the fact that excludes are currently required: https://github.com/typings/typings/issues/151

**Comment by CaptainCodeman** [comment]
Wow @nhhockeyplayer so much anger. Is it the hockey? It makes me angry too (well, when it's on TV instead of soccer). Just don't give in to the daaaaark side (speaks into empty bottle for cheap Darth Vader voice effect)

It's beta which means work in progress which means it's not finished yet. It's hard to finish and improve things if they are not allowed to make any changes to anything and a lot of the tools and libs that Angular 2 is being built on and with are also in a state of flux themselves right now which all adds to the challenges and the need for adjustments along the way.

We're all excited and eager to see it finished but there's a right way and a wrong way to report issues and ask for help. Don't forget there are human beings at the other end of the internet with feelings and good intentions and as well as technical issues they have to deal with us rabble as well. Sometimes things don't always work out perfectly first time and need to be fixed. Cutting them some slack is going to be more useful than beating on people.

It's only software, no one died (wait, NASA isn't using this for a mars mission control are they? Nah. they wouldn't ...)

**Comment by Namek** [comment]
It's more adequate to say: ![](https://media.giphy.com/media/3oEdv1LRqb97UMAnLy/giphy.gif)

> i wish the ego would end and somethign get produced thats commercial grade. Open source is no excuse for this mess.

I understand that anger of yours but I it's not acceptable anyway.I believe Angular Team does great job (even if current router is useless to my project, per https://github.com/angular/angular/issues/6634). Let's support them instead of yelling at them, it's a waste of time. If you need to fix your emotional stability then go do some sport - running is best if you ask me. And be nice to your team.

About project configuration of TS+A2 I use this: https://github.com/AngularClass/angular2-webpack-starter It's mostly up to date.

**Comment by largeDachshund** [comment]
@nhhockeyplayer, I'm completely empathetic.  Things could be a lot easier to endure, if there were authoritative docs that showed in a comprehensive way how to configure these projects.  "Todo" apps are terrible ways to show off your framework because they're overly simplistic.  "Todo" documentation is probably worse.  Code should be terse, not the documentation.  These frameworks, build tooling (what a mess), require such a huge learning curve, because examples are sparse and places like Stack Overflow dole out solutions akin to going to a witch doctor.  "Try this....  Oh, that didn't work, how about trying this..."

Angular team, help us make this framework a success.  I really like typescript.  I really like where you're taking the framework; it's a major improvement off of 1.*.  I'm a server-side guy and I've stayed clear of the client-side mess because maintainability of jquery or javascript for real business applications was a nightmare.

You've started to turn me into a believer.  Angular team help us configure these apps.  It's not trivial.  It's quite complex, more so, for the noobs (me included).  You might be concerned with Angular, but all the downstream processes (building modules, duplicate identifiiers,...) that's running afoul is affecting YOUR customer's user experience.  If we can't compile the dang project, it's no use to anyone.  Angular team please give us this configuration.  Guide us to what works to make the entire experience work.

**Comment by robwormald** [comment]
@nhhockeyplayer -  first and *only* warning - read the code of conduct https://github.com/angular/code-of-conduct/blob/master/CODE_OF_CONDUCT.md - your behavior in this issue is *completely* unacceptable. any more comments like this and we'll simply remove the ability for you to open issues.

I'm closing this issue as it's completely unproductive. If you'd like to open a new one and discuss your issues rationally and politely, please do so.
