### ISSUE TITLE
Template comments bug?

### ISSUE THREAD

**Issue by mrpotato3** [angular/angular#7099]
Hi, I have a problem with comments in templates. I'm using beta.6.

I describe the problem below:

```html
<!---->  works ok
<!----->  err
<!------>  works ok
```

If the number of '-' are pair template works as expected but if the number of '-' are odd angular shows this error:

![image](https://cloud.githubusercontent.com/assets/9481003/13079081/c639e9f6-d4c2-11e5-9d8c-b1cb5d7aec49.png)

I know this is not a standard html5 comment like '' but in angular 1.x this kind of comments are working okey.

Thanks.

**Comment by gbataille** [comment]
Hi @mrpotato3 ,
So to be precise, the [W3C spec](https://www.w3.org/TR/html-markup/syntax.html#comments) does not allow what you are asking to be comments (last 2 rules).

That being said
* browser would accept it (although should we rely on that?)
* I tracked the bug to a backtracking issue in the lexer implementation. It's impact is currently limited to comment parsing but since it's a low level function that could be reused, I think it ought to be fixed.

I'll propose a PR

**Comment by pkozlowski-opensource** [comment]
This got fixed by 60a2ba8
