### ISSUE TITLE
Router: RouterLink throws error when named route is a redirect

### ISSUE THREAD

**Issue by wardbell** [angular/angular#7109]
Or at least this is true if it redirects through child router(s).

Here is a repro: http://plnkr.co/edit/Mdm8yEWIyy0BAd5TTvvg?p=preview

**Comment by petebacondarwin** [comment]
I think this is because the router doesn't store the redirect links in its `ComponentRecognizer` (which I have renamed to `RuleSet`) list. So while it can recognise the URL it doesn't match by name.

Should be a fairly easy fix.

**Comment by petebacondarwin** [comment]
If only I could work out how to write tests in A2! The RouterLink directive has completely mocked out the Router so it is not possible to simulate the problem from those tests.

**Comment by wardbell** [comment]
I guess there is still a role for e2e ;-)

**Comment by btford** [comment]
You should never be linking to a redirect. What's your use case?

The error can be more instructive, but actually we should throw if you give a redirect a name.

**Comment by petebacondarwin** [comment]
Why not link to a redirect?
If we have a redirect in place then it is a shortcut for some more complex link, right?

I think the case given in the plunker is not bad - providing a nav link to a the disaster crisis.

If we force the user to recreate the full link structure then we are causing repetition in their code, since the must define the shortcut in both the redirect and then wherever they want a link.

**Comment by wardbell** [comment]
>never link to a redirect ...  throw if you give a redirect a name.

You haven't explained why a name is bad for a redirect. You merely asserted some unjustified, mystifying policy. It's pretty hard to swallow a reaction like this.

Obviously, I think it has utility as does Pete.

I gave the perfect use case. There is NO WAY TODAY to define a route that includes specific routing instructions. I showed such an example. Encapsulation of routing instructions is something we need to be able to do.

It is also useful as an app evolves. You may have two parts of the app with different route names to the same route. This happens when you're allowed to fix one part of an app but not another ... as happens in real life when there are legitimate (or illegitimate/bureaucratic) reasons why a certain part of the app is untouchable. So one section of the app refers to the Foo route and another to the Bar route.  You're trying unify or change the behavior such that anyone asking for Bar gets Foo. 

I can't see punishing the developer with an exception either.

**Comment by naomiblack** [comment]
The reason we have not supported aliases for routes is because it substantially increases the complexity of the work the router has to do in resolving child routes. The intent for the redirect API was to solve the problem of mapping an old URL structure to a new URL structure. Supporting aliases is a separate issue, and needs some design thought.

This is worthwhile for end users but won't make it into the first release due to complexity. We'll revisit.

**Comment by naomiblack** [comment]
@wardbell please link to the new issue covering the need for improved error, which will be in the first release.

**Comment by IgorMinar** [comment]
This issue was made obsolete by router v3: https://angularjs.blogspot.com/2016/06/improvements-coming-for-routing-in.html

If you believe this is not the case, please file a new issue updating the description to router v3. thank you!
