### ISSUE TITLE
Angular2 Forms Controls validation "OnLostFocus (OnBlur)" rather than "OnChange" 

### ISSUE THREAD

**Issue by liquidboy** [angular/angular#7113]
Hi,

Looking at the code for setting up form controls in  [shared.ts](https://github.com/angular/angular/blob/master/modules/angular2/src/common/forms/directives/shared.ts)  it appears we detect control changes onChange  "registerOnChange"

eg. if a user types into an input control that is an ng2 angular control, each keypress triggers a validationcheck .. 

It appears to be a big change if i were to change it from OnChange to something like LostFocus of the control ... 

The reason i ask is business really doesn't like the validation messages appearing suddenly even while the user hasn't finished filling in the field ...  eg. filling in a "Password" control, the user is suddenly shown validation errors while they're typing  ...

Anyone got a nice solution for hiding validation messages and only showing them once they tab off the control ?!

**Comment by gbataille** [comment]
That's interesting.
So the class valid/dirty/invalid seems nice (I guess you can agree with the decorator that say the field is not yet compliant).
However I agree that the messages are more cumbersome and sometimes obvious enough (like on a login screen)

The problem is when to display them then? how to know the user is "done"

For example I have a form that disables the submit button if the form is invalid. If it's the last field that is invalid, the user is editing it. He can't click on the button, so the "lost focus" event might not come depending on the user behaviour.

Let me throw a couple of UX ideas that use form validation on each change, but that react a bit differently (async ?) to it:
* display the errors/details after some timer of inactivity (a bit heavy)
* display the errors/details in a way that does not disturb the form layout (in a side floating tooltip rather than in a div that appear/disappear below each input)

what do you think?

**Comment by zoechi** [comment]
I think the issue is just about being able to use the `blur` event instead of the `change` event for calling the validator, so validation is only done when the user is done editing a field.

> display the errors/details in a way that does not disturb the form layout (in a side floating tooltip rather than in a div that appear/disappear below each input)

Shouldn't bee too hard. This is IMHO only a CSS problem not an Angular problem.

> display the errors/details after some timer of inactivity (a bit heavy)

Shouldn't be too hard to implement. Just create an additional flag used in `*ngIf` to show/hide validation errors. Subscribe to form changes and if there is some delay toggle the flag.

    <div class="validation-message" *ngIf="form.controls['xxx'].isValid && isIdle">

**Comment by liquidboy** [comment]
thanks guys ... ill try out the recommendation from zoechi ... 

our interaction designers are very adamant that the UI should NOT be changing whilst the user is entering data .. apparently they hate any form of distraction for the user during their data entry interaction..

**Comment by ps2goat** [comment]
+1 to have the option to validate on blur vs on change.

**Comment by JohnnyClutch** [comment]
The onBlur validation is definitely something I occasionally used in Angular 1, and will be implementing via a "controller" function if no provision is made by Angular 2.  +1

**Comment by redhatlinux10** [comment]
hi everyone !
i wanna know whether this `validate-onblur` mechanism has been implemented in `@angular/forms 0.2.0` ?  if not,  is there any workaround to do this ?

**Comment by BBegouin** [comment]
+1 :) any news of this feature ?

**Comment by AliHoussein** [comment]
+1 interested as well!

**Comment by Cuel** [comment]
Ran into this issue myself, would be nice if the form controls could report if their input is currently active/focused

**Comment by kara** [comment]
@liquidboy If the concern is that the error messages are being displayed as the user types (too early), have you considered using the `touched` property?  A control is only marked `touched` on the blur event, so the error message would not appear until then.

```html
<div class="error" *ngIf="email.touched && email.invalid".
   Email is invalid!
</div>
<input name="email" ngModel #email="ngModel"> 
```

What we don't have yet is support for actually running the validation on blur instead of on value change.  That seems like a good candidate for ngModelOptions.

**Comment by ghetolay** [comment]
@kara this will only work once. If user reset or manually delete the input then problem is back.

But thks it's still better and will do that from now on :)

**Comment by kara** [comment]
@ghetolay Resetting will actually set the field back to "untouched", so you shouldn't run into that problem. But you're right that if the user leaves the input, then comes back and deletes it, it will still be "touched".

**Comment by Cuel** [comment]
Telling the user that they need at least 4 characters before they've even had a chance to enter those 4 a badly designed UI. It works for `maxLength` because then we can be certain something is wrong. Not the same story for `minLength` or even `pattern`.

Fiddling with `touched` works, but it feels like a chore to fiddle it back and forth and it doesn't "feel" like the correct way to do it - developers don't know what touched might be used for internally or by e.g directives. In my app at the moment I have `validators: ValidatorFn[]` and `onChangeValidators: ValidatorsFn[]` when creating a `FormControl`. All components have an `onChange` and later on that uses `setError` to push the validator error in. It works quite well so it's certainly possible to get around this issue.

There's a few quirks introduced because editing a field and instantly clicking on a submit button might allow the event to trigger (e.g when used with disabling buttons), so I have to manually ask the `FormModel` if it's valid (allow it to update).

On top of that we have a view with quite a complex UI with over 50 inputs divided into 5-6 components. All components have to react on changes in the data in other components to update themselves with other inputs. We thought about having a store and using `valueChanges` to update the data but it didn't feel like a very performant solution - updating it onblur/change would be better.

**Comment by Longfld** [comment]
Ok, I found a way to do this as:

  `<input type="text" required  #mycontrol formControlName="MYCTRL"  (change)="MYCTRL=mycontrol.value;Update('MYCTRL')" />`

both MYCTRL and Update() as part of model.
  but, to be honestly, I wound like to have something like onModuleBlur to pass job to ng2 , rather I call  (change).
  
Well, the reason I come here as I need find out how to validate/show message (:

**Comment by fxck** [comment]
@kara imaging you have an email input, which is asynchronously checking whether it's unique or not... now no matter how much you debounce the checking event, it *never ever* makes sense to check until the user is done, which for me is when he blurs the input.

**Comment by kalyan1102** [comment]
Thinks from accessibility perspective, a screen reader user typing on the field and hearing repeat alert that the form field is invalid. This would be a nightmare for a screen reader user to. Providing a solution to validate onBlur would be very helpful... Is there any update when we will get one?

**Comment by mattdistefano** [comment]
I'll second the scenario @fxck cited - IMO async validation will more often than not need to be fired on blur. We hacked around this in our app by having our async validators return a different error when focused and filtering that off in our display logic, but it's kind of ugly.

I will add I think this setting should be specified on a per-use basis rather than per-validator-type or per-form. 

@kalyan1102 In my experience, the error message will only be announced when the DOM element is added/shown (assuming you're using `aria-live="assertive"`) so you shouldn't hear it with each keystroke.

**Comment by dsoldera** [comment]
Hi.

It's a pity that anyone have worked on this issue yet. I think Reactive Forms are great and I want to use on my project with the OnLostFocus event. Please consider to improve this issue ASAP.

**Comment by vicb** [comment]
@dsoldera feel free to help, _almost_ any contribution is welcome !

**Comment by ghetolay** [comment]
@vicb How do you see it ?

- User can freely decide of the event name : input, change, blur, mouseover, customEvent...
- Use an abstraction for only a set of events (input/change/blur)  and only permits those
- Use a boolean just to switch between input & blur.

**Comment by SystemDisc** [comment]
Would this work?
``` typescript
  dir.valueAccessor.registerOnTouched(() => {
    control.updateValueAndValidity();
    control.markAsTouched();
  });
```
https://github.com/angular/angular/blob/8f5dd1f11e6ca1888fdbd3231c06d6df00aba5cc/modules/%40angular/forms/src/directives/shared.ts#L50

**Comment by SystemDisc** [comment]
I'm pretty sure that since `onTouched()` is called for `(blur)`, that all that needs to be done is the change noted in my previous comment.

https://github.com/angular/angular/blob/45ddd6ba78b5c9a6994b800f77a0499abb5b9b1a/modules/%40angular/forms/src/directives/default_value_accessor.ts#L36

**Comment by SystemDisc** [comment]
Can someone invested in this issue look at #13832 and let me know what kinds of configuration should be available and by what means those options should be configurable?

**Comment by sgwatgit** [comment]
@SystemDisc I really like your suggested API update

```
new FormControl('name', validator, asyncValidator, {validateEvent: 'blur'});
new FormControl('name', validator, asyncValidator, {validateEvent: 'change'});
new FormControl('name', validator, asyncValidator, {validateEvent: ['blur', 'change']});
```

I think that's what the users in this thread seem to be looking for.

**Comment by mattdistefano** [comment]
I think the functionality should be provided in some manner but...

1. Specifying what look to be DOM event names in the FormControl feels like a leaky abstraction.
2. I think there needs to be a way to control the validation per-validator, so that, for example, you can run sync pattern validation on input but async validation only on blur.

**Comment by mattdistefano** [comment]
Also probably need some thought around how on-blur validation would work with programatic changes via setValue() and friends (I believe these rerun validation today).

**Comment by SystemDisc** [comment]
I agree with all your points, but in order to set the DOM event name on the element, you would not be able to specify which validator it was attached to. I think the configuration should be per-validator, and do not think setValue should call the validators. I think if you're doing something like that programmatically, you should also programmatically call for the validators to run - or perhaps setValue and similar methods should have a parameter for whether or not to call the validators.

**Comment by SystemDisc** [comment]
I'm not sure who you would specify the event names per validator, though. Perhaps ValidatorFn and AsyncValidatorFn would have to be expanded in some way.

**Comment by SystemDisc** [comment]
Perhaps:
```typescrypt
new FormControl('name', validator, asyncValidator, {validateEvent: 'blur'});
new FormControl('name', validator, asyncValidator, {validateEvent: 'change'});
new FormControl('name', validator, asyncValidator, {validateEvent: ['blur', 'change']});
new FormControl('name', validator, asyncValidator, {syncValidateEvent: 'blur'});
new FormControl('name', validator, asyncValidator, {asyncValidateEvent: 'blur'});
new FormControl('name', validator, asyncValidator, {syncValidateEvent: 'change', asyncValidateEvent: 'blur'});
new FormControl('name', validator, asyncValidator, {syncValidateEvent: ['blur', 'change'], asyncValidateEvent: 'blur'});
```

**Comment by mattdistefano** [comment]
IIRC setValue is also called by ngModel for example when its binding changes. So I'm not sure what the expected behavior would be in that case w/ validating on blur.

Re. the other changes, I think that it mostly makes sense for my use cases, however:

1. Part of me thinks the event names should be something like 'onTouched' and 'onChange' since that better reflects the abstraction (ControlValueAccessor) the FormControl is actually working with (vs. the DOM event-ish names).
2. We'd probably want a directive equivalent for template-driven forms.

**Comment by SystemDisc** [comment]
For your first note, I figured if we used actual event names, users could bind to any event. For number two, I agree. Perhaps it should all be done via attributes:

```html
<input type="test" name="firstname" formControlName="firstname" validate-event="change">
```

But, then how would you assign multiple events? Plus, it doesn't really fit with the whole `(event)="doSomething()"` syntax.

**Comment by ghetolay** [comment]
Do you guys really need the validation process to run only at blur ?
For me (and I think for OP) this is just about the view, I'm ok with validator logic running at each value change but I just want better control on when users sees it.

**Comment by mattdistefano** [comment]
How would you support arbitrary events? As I understand it, FormControl doesn't - and shouldn't - know about DOM events; rather, it uses a ControlValueAccessor as its bridge to the DOM.

**Comment by mattdistefano** [comment]
@ghetolay I think the main use case is async validators that hit remote services (checking if a username is available, for instance) - I wouldn't say it's a huge problem, but it's annoying having them running on each keystroke (or close enough to it - IIRC they only run if the sync validators pass).

1. They're chewing up network/CPU/memory resources.
2. They impact the overall validity of the control, which can make other validation more complicated than it needs to be in cases where we're trying to only show the error on blur (checking whether a username is in use, for example).

That said, I think the OPs requirements would need to be solved by adding another directive to monitor whether the control currently has focus and keying the error messages off its value.

**Comment by ghetolay** [comment]
@mattdistefano 

Yeah ok I understand that need.

In that case, validation should really be separated from `setValue()` but I don't think we should define any event name like @SystemDisc suggested.

I would rather suggest using an observable that emits item every time we wants to run validators (same for async validators).
- That Observable would be `valueChanges` by default.
- User could submit his own Observable like `Observable.fromEvent(el, 'blur')`.

Then we can still create a `validator-event` directive that would inject the control and set the Observable accordingly.

@vicb does this seems reasonable ?

**Comment by Cuel** [comment]
@ghetolay yes it's mostly regarding the view. It's horrible UX to show an error for minimum length as soon as the user start typing as they haven't done anything wrong yet. I like your suggestion, but how would it work without a lot of manual work for every input?

**Comment by SystemDisc** [comment]
@Cuel, for something like that all you need to do is check if the control has been touched (blurred) before displaying the error.

I think this issue is more related to how errors show up with AsyncValidators, and purple wanting the ability to only run validation on blur.

**Comment by ghetolay** [comment]
@cuel *mostly* isn't enough, we need to cover *all* and I think @mattdistefano's case is legit. If this was just about the view it would be easier.

> but how would it work without a lot of manual work for every input

Well like anything else: on form creation for reactive form and through directive for template driven.
I'm just having 2 interrogations for the reactive form, let's say we add a constructor field and use it like that : 

```
form = new FormGroup({
  input: new FormControl('', Validators.minLength(), Observable.fromEvent(el, 'blur') )
})
```

There is 2 problems here : 
 - `el` must be injected for each input through `@ViewChild`
 - `el` will be undefined until `ngAfterViewInit()` and form must be build before (on `constructor` or `ngOnInit`)

So to make it work we would have to inject the element and create a Subject/EventEmitter for each input and feed it with the events from the element:

```
@ViewChild('input1')
input1ElRef: ElementRef;

input1ValidatorEmitter = new EventEmitter<void>();

ngOnInit(){
  this.form = new FormGroup({
     input1: new FormControl('', Validators.minLength(), input1ValidatorEmitter)
  })
}

ngAfterViewInit() {
   Observable.fromEvent(this.input1ElRef.nativeElement, 'blur')
     .subscribe( () => this.input1ValidatorEmitter.emit() );
]
```

And now we reached a point with a lot of *manual work* for every input :/

Also I'm not even sure it's safe to use `Observable.fromEvent()`, maybe we should rather use `Renderer.listen()`.

So now this makes me thinking that this stuff should be part of the `ControlValueAccessor` because he's the one linking dom element to control.

**Comment by ghetolay** [comment]
Something we should also take care of is that we can't submit the form without validating it first.
With custom events this could happen.

**Comment by SystemDisc** [comment]
Validating in submit only _would_ be really nice.

**Comment by Cuel** [comment]
@SystemDisc One could think so, I didn't explain it very well. Touched is useless for my use-case

**Comment by mattdistefano** [comment]
@Cuel Couple options:

If your HTML structure permits it, you can always suppress the error states/messages via CSS (i.e. `input:focus.ng-invalid + .error { display: none' }` sort of thing).

If not, you can probably write a directive to monitor whether an element has focus, use a template var to get a reference to the instance of the directive, and update your template to check its value (i.e. `*ngIf="!focusMonitor.hasFocus && control.invalid"`). 

IMO the Forms API should do the latter itself, particularly since IIRC we're adding a .focus() method.

**Comment by Cuel** [comment]
Thanks, we have already solved it however with a custom form builder that allows `onChangeValidators`.

**Comment by SystemDisc** [comment]
Well, if you think your solution is elegant enough, create a pull-request and reference this issue.

**Comment by SystemDisc** [comment]
If we can come up with something that seems to fit the way Angular2 does things, which allows configuring for, at the very least, a way to have Validators run on value changed, on blur, or both, I would be more than happy to correct my PR (#13832) to get this taken care of.

**Comment by smartm0use** [comment]
@SystemDisc  I tried your solution posted [here](https://github.com/angular/angular/issues/7113#issuecomment-273667789). It doesn't work.

Here is my form:

        this.myForm = this.fb.group({
            'email': = ['', null, emailChecker(this.myService, this.SomeParam), {validateEvent: 'blur'];
            ...

Can you tell me what's wrong at it?
I also tried to use `asyncValidateEvent` or add `validate-event` in the `<input>` tag:

<input type="email" name="mail" [formControl]="myForm.controls.email" validate-event="blur">

It doesn't work, the validation is triggered as users start to fill the input field...

**Comment by SystemDisc** [comment]
That want a solution that was a proposed change to the API to make this work.

**Comment by artem-galas** [comment]
Here I found a little solution - http://stackoverflow.com/a/41973780/3933346 . I hope it is can help someone.

**Comment by umac12** [comment]
any updates on this? I am also looking for validation call to happen when the input entry is completed or the form filed lost focus. currently it is validating for every character entry.

**Comment by sergiocarneiro** [comment]
It would be nice if this could be implemented!

But until then, I simply use this CSS rule:
`input:focus + alert {
    display: none;
}
`

**Comment by sergiocarneiro** [comment]
It would be nice to have this implemented!

But until then, I simply use this CSS rule:
`input:focus + .alert {
    display: none;
}`

**Comment by JamesHenry** [comment]
I am migrating a legacy AngularJS app, and was surprised to find no equivalent of being able to set `ng-model-options="{ updateOn: 'default blur', debounce: { default: 1000, blur: 0 } }"`.

A few points have been touched on in this issue, but for some the simple cases is just controlling when to show/hide the relevant errors - "blur vs changes".

Just in case it serves as inspiration for anyone looking for a non-CSS based approach to hiding and showing the errors (with control over blur vs change), I use a wrapper component and RxJS as the key to making this behaviour possible.

A lot of the logic inside my custom wrapper component in Angular 2+ is specific to my use case, but the core of the logic that relates to this issue is this:

```ts
/**
 * Subscribe to changes to the FormControl's value, in order to monitor the outstanding errors,
 * and trigger change detection.
 *
 * We set up a "race" between the user clicking outside of the input (a blur event), and an
 * Observable which just emits after a certain amount of time.
 *
 * This effectively gives us a way to debounce our value changes, but override the debounce
 * in the case that the user has already moved on from the input.
 */
this.valueChangesSubscription = this.formControl.valueChanges
    .flatMap(() => Observable.race<any>(
        Observable.timer(this.valueChangesDebounce),
        this.inputBlur$.asObservable(),
    ))
    .subscribe(() => {
        this.hasErrors = !!this.formControl.errors
        this.changeDetectorRef.markForCheck()
    })
```

Where `this.inputBlur$` is just a `Subject` that I call `next()` on whenever there is a blur event on the `<input>` that my Component wraps.

You could obviously tweak this setup to make the blur event a requisite of progressing through the observable, and ignore the debounce aspect all together.

**Comment by anand-ma** [comment]
@JamesHenry if it's possible, i would request a link to sample project with your code.

**Comment by tylerlindell** [comment]
@JamesHenry, can you provide how you are defining `this.inputBlur$` please?

**Comment by aldo-roman** [comment]
Just a though... it seems `valueChanges` is actually triggering on `input` event rather than on `change` event. The `change` event fires at different moments, including after losing focus (the so called `onBlur`).

See:
https://developer.mozilla.org/en-US/docs/Web/Events/input
https://developer.mozilla.org/en-US/docs/Web/Events/change

Would it be nice to have:
`control.valueChanges.subscribe(...)` -> on `change` event
`control.valueInput.subscribe(...)` -> on `input` event
?

**Comment by ghetolay** [comment]
@aldo-roman 
Nope, you're mixing things, `AbstractControl` is abstracted from the DOM. And the term `changes` is some kind of convention on Angular for Observables that emits when value changes (`QueryList`, `[()]` desugar etc..). This has absolutely no relation with the `change` event.

The link between form API and dom input is through `ControlValueAccessor` so if you want an input to update on a different event you should build and bind your own custom `ControlValueAccessor`.

This is issue is about triggering validation at a different moment than when value change. At first I also thought if validation is done when value change let's just update the value on blur. But I don't think that's the solution, we should always keep state in sync and we may want to run sync validators on value change and async validators on blur.

**Comment by wnabil** [comment]
creating a directive as @artem-galas mentioned works fine.

**Comment by AndriiDidkivsky** [comment]
Hi, any updates ?

**Comment by djleonskennedy** [comment]
Hello, is there any workarounds to solve issue ?

**Comment by dcarabott** [comment]
Check this out for the time being
http://stackoverflow.com/questions/33866824/angular2-control-validation-on-blur/41973780#41973780

**Comment by AndriiDidkivsky** [comment]
@dcarabott , we've already used this solutions, but it's can't be applied in some cases.

**Comment by RevProg** [comment]
Hi. Same issue. Waiting for fix.

**Comment by anand-ma** [comment]
Angular team. Can we prioritize this. Its quite a long wait.

**Comment by wnabil** [comment]
Guys you can create a custom directive to fix it temporary as described in this link.
Just mark the control as touched on the focus out and it will work!
also on focus in you can remove the mark.
customize this solution as you want
https://stackoverflow.com/questions/33866824/angular2-control-validation-on-blur/41973780#41973780
You do not need to wait for this is if you are really need this

**Comment by SystemDisc** [comment]
It seems we have some solutions/work-arounds. If we can agree on one, why not create a pull request?

**Comment by djleonskennedy** [comment]
@SystemDisc any workaround doesn't work as expected, need ng2 solution as ng1 has

**Comment by katrina-engelbrecht** [comment]
What is the newest status? We need to have validator on blur() as well. It seems that Angular team has no interests for this big issue?

**Comment by ashley-s** [comment]
Will that be taken care of in future versions of angular?

**Comment by webmobiles** [comment]
i have heared that setters and getters is not good for performance reasons, what about this way to manage errors. 

child component.

import { Component, Input , OnInit } from '@angular/core';


@Component({
  selector: 'field-messages',
  templateUrl: 'field-messages.html'
})
export class FieldMessagesComponent implements OnInit {
  public errorsField: any =  [];
  @Input() fieldname: string;
  @Input()
  set errMsgs (errMsg: any) {
    this.errorsField = [];
    if (errMsg.hasOwnProperty(this.fieldname)) {
      this.errorsField = errMsg[this.fieldname];
    }
  }
  get errMsgs () {
    return this.errorsField ;
  }


  constructor() {
    this.errorsField = {};
  }

  ngOnInit () {

  }
}

template parent

      <field-messages fieldname="firstname" [errMsgs]="errMsgs"></field-messages>

**Comment by nazarioa** [comment]
Just voicing support for validation on blur of some kind. I personally like the API suggestion by **@SystemDisc** on **Jan 18**.

**Comment by Toxicable** [comment]
https://github.com/angular/angular/pull/18408

**Comment by jagomf** [comment]
I wouldn't close this issue until template-driven forms are supported as well...

**Comment by kara** [comment]
@jagomf Template-driven forms are already supported. See https://github.com/angular/angular/pull/18577 and https://github.com/angular/angular/pull/18594

**Comment by mlangwell** [comment]
Anyone able to get this to work? I have been trying without success. 

This is my form so far:

```
this.infoForm = this.fb.group({
      userName: [this.regServ.userName, Validators.required, { validators: userExists.bind(this), updateOn: blur }],
      email: [this.regServ.email, Validators.compose([Validators.required, verifyEmail.bind(this)])],
      confirmEmail: ['', Validators.compose([Validators.required, verifyEmail.bind(this)])],
      password: ['', Validators.required],
      confirmPassword: ['', Validators.required],
    });
```

When I type into the userName control it throws a "TypeError: v is not a function"

**Comment by kara** [comment]
@mlangwell FormBuilder doesn't yet support updateOn (see https://github.com/angular/angular/issues/19163). If you switch to creating the FormGroup yourself, it should work. Worth noting that the control options should be passed as the second arg, not the third though.

**Comment by mlangwell** [comment]
@kara thank you for clearing that up!

Regarding the third arg, isn't the third arg for asyncValidators? My third arg for userName is an async check on our API if a user name already exists. This was the only way I could get the async validator to work with a sync validator on the same control. If there is a better way I am open to suggestions!

**Comment by kara** [comment]
What version are you using? It's only available on the 5.x beta versions.

See example here: http://plnkr.co/edit/Ig8XG1rTll4FwW6gVcqK?p=preview. 

Async validators are set as a separate option.  See docs here: https://next.angular.io/api/forms/FormControl.

**Comment by mlangwell** [comment]
@kara our team is using 4.3.6, so that would be why it does not work. We are not permitted to use any beta versions unfortunately.

The only way I could get this to work was to add a blur event to the input control and then call setErrors() on the control as appropriate. This worked for me if anyone else needs the work around this is what it looks like: 

```
checkUserExists() {
    if (this.userName.value) {
      this.regServ.userNameExists(this.userName.value)
      .subscribe((exists) => {
        if (exists) {
          this.userName.setErrors({ userExists: `User Name "${this.userName.value}" already exists` });
        }
      });
    }
  }
```

**Comment by marokac** [comment]
Yoo guys on githup you never solve anything , stackOverflow is even better

**Comment by notsonotso** [comment]
@marokac that must explain the 10,000+ closed issues in this repo.

**Comment by dimi-nk** [comment]
![](https://m.popkey.co/2e18f2/VlgXG.gif)

**Comment by marokac** [comment]
**Thus because i been struggling with the sane issue here. maybe you can help. I am trying to validate a form using angular formBuilder..here is my code:**

  ngOnInit() {
    this.formBuilder = new FormBuilder();
      this.simpleForm = this.formBuilder.group({
      notifyMeRadio: [],
      notifyMeEmail: [this.notifyMeEmail,[CommonValidators.isValidEmailAddress]],
      notifyMeSMS: [this.notifyMeSMS, [Validators.minLength(10)]],
      notifyMeFax: [this.notifyMeFax,[CommonValidators.isValidBeneficiaryName]],
      notifyBeneficiaryRadio: [''],
      notifyBeneficiaryEmail: [this.notifyBeneficiaryEmail,[CommonValidators.isValidEmailAddress]],
      notifyBeneficiarySMS: [this.notifyBeneficiarySMS,[Validators.minLength(10)]],
      notifyBeneficiaryFax: [this.notifyBeneficiaryFax,[Validators.minLength(10)]],
    });
    this.simpleForm.valueChanges.subscribe(data => this.onValueChanged(data));
    this.onValueChanged();

**And my validation messages object goes like this:**

validationMessages = {
    'notifyMeSMS': {'required':'field cannot be empty',
    'isValidEmailAddress':'10 digist'
  },
    'notifyMeEmail': {'required': 'Please enter valid Email address'},
    'notifyMeFax' :  { 'required': 'Please enter valid Fax name',
    'isValidBeneficiaryName':'isValidBeneficiaryName'
   },

    'notifyBeneficiarySMS':  {'required':'Please enter valid
  SMS', 'isValidEmailAddress':'please type a valid email address'},
    'notifyBeneficiaryEmail': {'required':'required field'},
    'notifyBeneficiaryFax' :  {'required':'Please enter valid beneficiary Fax'},
  };


Form errors here:

 formErrors: {
        'notifyMeRadio':'',
        'notifyMeEmail': '',
        'notifyMeSMS': '',
        'notifyMeFax': ''
      },


And finally my OnvalueChange method:

 onValueChanged(data?: any) {
    if (!this.simpleForm) { return; }
    const form = this.simpleForm;

    for (const field in this.formStatus.formErrors) {
   
      //this.formStatus.formErrors[this.formStatus.formErrors.notifyMeSMS] = ''
      this.formStatus.formErrors[field] = '';
      const control = form.get(field)
      if (control && control.dirty && !control.valid) {
        const messages = this.validationMessages[field];
        for (const key in control.errors) {
        this.formStatus.formErrors[field] +=messages[key] + ' '
       
        
        }
      }
    }
  }


My issue here is i can only get validation messages when i include required and it only return required only 

please help guys

**Comment by notsonotso** [comment]
@marokac you should ask on StackOverflow. They're so much better than us guys.

**Comment by marokac** [comment]
@notsonotso I will beg you on this one my man please help if you can...

**Comment by trotyl** [comment]
@marokac GitHub issue is not used for support request, please refer to [CONTRIBUTING](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question) for more information.

**Comment by rmcsharry** [comment]
Validations firing onBlur appear to conflict with having a 'Cancel' button for the form. Cancel is not like a form reset, it is a 'total dismiss' of the input/edit operation, possibly even closing the form.

If a field has focus, then the validation logic fires when the field loses focus and before the Cancel click occurs. This is particularly a bad UX when the form is inside a modal - since the Cancel button also should dismiss the modal, except it cannot because of the validation firing first.

SO example [here](https://stackoverflow.com/questions/46411390/angular-form-validation-activated-before-cancel-button-is-triggered?rq=1#).

I believe in Angular 1.x we could set form.submitted = false inside the Cancel click handler, but in Angular  2+ submitted is a read-only attribute and cannot be set.

So how can we 'form cancel' without firing any validations?

**Comment by steelx** [comment]
this post should be awarded "most patient users ever"

**Comment by marokac** [comment]
Thank you

**Comment by jkrot** [comment]
I would still like this as well because doing silly things with render to get this to happen doesn't make me happy.

**Comment by imadhy** [comment]
updates ?

**Comment by spyro2000** [comment]
Why isn't that just a global setting or something?

**Comment by SystemDisc** [comment]
Someone come up with a solid proposal that we can agree on. Then, a PR can be made implementing that proposed solution.

**Comment by marokac** [comment]
I think we can fire the blur event only when click happens inside the form
