### ISSUE TITLE
Proposal: add syntax for template vars on <template> elements

### ISSUE THREAD

**Issue by jelbourn** [angular/angular#7142]
If you want to use a `TemplateRef` to instantiate an embedded View anywhere other than in that template's location (i.e., with its own `ViewRef`), the inability to grab the TemplateRef (or a directive instance) on the template element becomes cumbersome. The only real way to accomplish it now is to use `@ViewChild` / `@ViewChildren` to retrieve some decorating `Directive` that exposes the TemplateRef.

For example:
```html
<component-with-popup [popup]="content"></component-with-popup>

<template popup-content #content>
  This is the template content!
</template>
```

This doesn't work, since the assumption is that `#content` is for something _in_ the template rather than the template itself.

### Proposal:
Add a new syntax for referencing the template itself:
```html
<component-with-popup [popup]="content"></component-with-popup>

<template popup-content template-var-content>
  This is the template content!
</template>
```
This uses `template-var-` as the prefix for the variable over the standard `var-`. Since this is going to be a somewhat uncommon use-case, a shorthand syntax isn't strictly necessary. 

If desired, possible shorthand syntaxes:
`<template @content>`
`<template *#content>`
`<template **content>`
`<template ##content>`
`<template !#content>`
`<template 😱content>`

cc @vsavkin @tbosch

**Comment by zoechi** [comment]
Maybe a stupid question, I only had a brief look. Isn't this what 

    constructor(tRef:TemplateRef) 

gives you. I was wondering how this would work for more than one template.

**Comment by tbosch** [comment]
The above proposal is for more than one TemplateRef.
@jelbourn did you mean `@ContentChild/@ContentChildren` instead of `@ViewChild/@ViewChildren`?

I would rather vote for using a different syntax for defining variables that are used in a template. Something like `<template ng-for def-var-item>`. Then the regular `var-` / `#` syntax can be used to reference the template itself. I.e. `var-` / `#` would have the following semantics:

- if placed on a regular element, return the dom element (current semantics)
- if placed on a component element, return the component instance (current semantics)
- if placed on a template element, return the TemplateRef (added semantics)

So what could be a good syntax for defining variables that should be used in a template?

**Comment by tbosch** [comment]
In general, the short form should be only one character.

My favorite:
Short form: `<div *ngFor="&item of items">`
Long form: `<template ngFor def-item [of]="items">`

Why `&`? Borrowed form C++ to define a reference.

**Comment by mhevery** [comment]
Dup of https://github.com/angular/angular/issues/7158
