### ISSUE TITLE
Sample/benchmark apps are broken on Safari

### ISSUE THREAD

**Issue by tbosch** [angular/angular#721]
When running the hello_world app or one of our benchmarks in Safari I get the following errors:

```
TypeError: Attempting to change the setter of an unconfigurable property. In `traceur-runtime.js:177
```
@btford Is this related to zone.js?

```
SyntaxError: Cannot use initialiser syntax in a strict mode enumeration.
```
See https://github.com/google/traceur-compiler/issues/1647

**Comment by caitp** [comment]
so, the examples have been working in WebKit Nightly for a few months, and the june or july Safari update will maybe/hopefully incorporate the fixes.

Babel at least works around this by polyfilling collections on Safari (maybe in all browsers), not sure if TS does. This bug is probably closable since the collections issue is likely the only blocker at the moment

**Comment by caitp** [comment]
as mentioned, think this is safe to close for now --- google/traceur-compiler#1650 seems like it might fix the remaining issues eventually, but since moving away from traceur it probably doesn't matter
