### ISSUE TITLE
Cannot import node_modules in component

### ISSUE THREAD

**Issue by Znow** [angular/angular#7259]
Hi!

I've been struggling around with getting "marked" imported in my component:

```typescript
import * as marked from 'node_modules/marked/marked.min.js';
```

It cannot see the node_modules folder, since it's "excluded" in the "tsconfig.json", as per the tutorial:

```json
{
  "compilerOptions": {
    "target": "es5",
    "module": "system",
    "moduleResolution": "node",
    "sourceMap": true,
    "emitDecoratorMetadata": true,
    "experimentalDecorators": true,
    "removeComments": false,
    "noImplicitAny": false
  },
  "exclude": [
    "node_modules",
    "typings/main",
    "typings/main.d.ts"
  ]
}
```

If I remove the "node_modules" entry, it allows me to get the "marked" npm package imported in my component just fine.

Well, that makes sense, but why?

The tutorial doesn't really tell, that, if you exlude the "node_modules", you cannot import specific packages in your components for further use.

Kind regards

**Comment by ericmartinezr** [comment]
This is not related at all to angular2, this is systemjs  configuration. You should move this question to SO (rep hunters will be happy), or similars.

**Comment by Znow** [comment]
@ericmartinezr It may not be related to angular2 - but the above config is an exhibit from the angular.io tutorial.

:)

**Comment by ericmartinezr** [comment]
wooott... god damn... well... since I screwed up I'll try to fix it by trying to answer...

If you remove `node_modules` from `exclude` the typescript compiler will go look into it and try to compile the files it founds, you don't want to do that.

If you want to add marked you should add it in your systemjs config 

```
{
   map : {
     marked : 'node_modules/marked/marked.min.js';
   }
}
```
And then in your code
```
import * as marked from 'marked';
```
That should work.

By the way, I look at the tutorial and couldn't find the line, where is it?

**Comment by Znow** [comment]
@ericmartinezr Thanks alot, that makes perfectly sense!

It's in the quickstart guide - [https://angular.io/docs/ts/latest/quickstart.html](url) "Configure TypeScript"

Regards

**Comment by ericmartinezr** [comment]
@Znow Thanks, I was looking for your specific import, I found odd that a line like that would appear in the tutorial, but you were talking about the config. So, you were right about this sentence 

>The tutorial doesn't really tell, that, if you exlude the "node_modules", you cannot import specific packages in your components for further use.

I'm really sorry. If you want to ask for clarification about this you can open an issue here https://github.com/angular/angular.io (that's the repo for the website)

**Comment by alexeagle** [comment]
Generally speaking, using an ES6 import statement from a library in `node_modules` doesn't work.
That's because `import` has two meanings - a "value side" emit that causes your module loader to load the package, and a "type side" typechecker instruction for where to locate the typings.
The loader side probably works because TS can see the `export` symbol in https://github.com/chjj/marked/blob/master/lib/marked.js
But the package doesn't include typings in its distro, so the latter fails.

You may just want to use your native module loader syntax to load this dependency, and use https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/marked/marked.d.ts to instruct the typechecker.
