### ISSUE TITLE
Route.params are appended as matrix AND query to Location in Router

### ISSUE THREAD

**Issue by Batch1211** [angular/angular#7314]
So, in the `RootRouter.commit` method, the RouteParams are appended twice to the URL, causing an URL like this

`http://host.com/path?state=3&code=4`
to be transformed to an url like this
`http://host.com/path;state=3;code=4?state=3&code=4` 

by angular.

This is not very pretty, and can cause problems, especially if you allow forward slashes in url query parameters, as I propose in #7312. 

So the question is, how to fix this issue? I would propose to only append RouteParams by query parameters and drop matrix variables. However, I don't know if that is as easily done than said. 

If matrix parameters need to be supported, then I would suggest, that they are supported by some sort of strategy pattern, so we can prevent duplication of parameters in the URL.

Does anybody have an opinion on this?

**Comment by laco0416** [comment]
This is still occurring on RC.1 router-deprecated.
I'd like to prevent to use matrix parameters in my application, so I want a strategy configuration for RouteParams style like `LocationStrategy`.

The following is an idea.

```
{ provide: ParamsStrategy, useClass: MatrixParamsStrategy /** or QueryParamsStrategy */}
```

@mhevery `router-deprecated` won't be updated? I and many users are still using beta-router because RC-router is not enough for using in the real application. We need the latest milestone of the **official router**. We are confusing which router library to choose... :(

**Comment by zoechi** [comment]
It seems a new router is work in progress that will replace `router` **and** `router-deprecated`.

**Comment by vicb** [comment]
obsolete
