### ISSUE TITLE
Support async pipes with input as promises returned from a function invocation

### ISSUE THREAD

**Issue by lastmjs** [angular/angular#7328]
Right now async pipes break in templates when the promise passed into them is the result of a function invocation directly in the template. I think it would be nice to allow this behavior. For example:

```
@Component({
    selector: 'async-pipe-test',
    template: '<div>{{delayedMessage() | async}}</div>'
})

export class AsyncPipeTestComponent {
    constructor() {
         }

    delayedMessage() {
        return new Promise(function(resolve, reject) {
            setTimeout(function() {
                  resolve('this is the message');
            }, 500);
        });
    }

}
```

does not work. That was not obvious to me, and I think it should work. I at least have a use case for it, where I pass a function into the template that evaluates to a promise.

**Comment by robwormald** [comment]
The problem here is that every invocation of of the function is going to return a new Promise. As written, there's no way around it, because the function must be invoked to check if the return value has changed.

You should generally avoid calling functions from the view, and instead assign values as properties.

**Comment by Binvention** [comment]
you could just take advantage of the fact that undefined variables aren't displayed. so have the promise assign a its resulting value to a variable that was undefined before. once that variable is assigned the value it will appear in the template because the variable is now defined.

**Comment by lastmjs** [comment]
> You should generally avoid calling functions from the view, and instead assign values as properties.

@robwormald, if I have a list of items that generate dynamic text to be inserted into the view, based on parameters only known at run-time (that is what my asynchronous functions are for), it will be a little complicated trying to run those functions and stick them in properties that are then assigned to the view. Why do you say you should generally avoid calling functions from the view? I feel like my use-case is legitimate, it seems like it would be more of a hack and require more code to not do it the way I'm doing it.

**Comment by lastmjs** [comment]
Also, it would be nice if async pipes allows inputs that were not promises. Again, it comes down to the dynamic nature of my values. I have a function in a list that returns dynamic text based on parameters only known at run-time, and the functions are asynchronous sometimes but synchronous at other times. Because the async pipe only allows a promise for input, I have to make all of my functions asynchronous though they do not all perform asynchronous actions.

**Comment by robwormald** [comment]
Not sure what you mean. Dynamic values are handled fine by regular data binding. The point of the async pipe is to unwrap Promises and Observables.

**Comment by lastmjs** [comment]
This is a simplified example, but let's say I want to display preview text for a project. I only know the project id that I'm interested in at runtime, say from a user click. I want to display all of the fields of a project, but I need to go to the database to get the project, and I want to do that asynchronously:
```
<div *ngFor="item of items">{{item.getPreviewText(id) | async}}</div>

class TestComponent {
    constructor(itemsService: ItemsService, idService: IdService) {
        this.id = idService.id;
        this.items = itemsService.items;
    }
}

class ItemsService {
    items = [
        {
            getPreviewText: async (id) => {
                  const project = await GetFromDatabaseById(id);
                  return project.name;
            }
        },
        {
            getPreviewText: async (id) => {
                  const project = await GetFromDatabaseById(id);
                  return project.number;
            }
        },
        {
            getPreviewText: async (id) => {
                  const project = await GetFromDatabaseById(id);
                  return project.startDate;
            }
        }
    ];
}
```
Does that make sense? The getPreviewText is generating text based on a value that I only know at runtime. In reality, I would like the getPreviewText to perform any asynchronous task based on any inputs. It would be nice if the above code worked, so that I wouldn't have to add anymore boilerplate code.

**Comment by robwormald** [comment]
The problem is that its going to re-execute the work *every time* change detection runs (hence why it's a bad idea to do it from the view...) - there's no other way for angular to check if that binding has changed. 

Your code appears to be making the same `getFromDatabaseById` call for each item, which seems woefully inefficient. You'd be better doing something like:
```js

this.items = GetFromDatabaseById(id).then(project => {
  return ['name', 'number', 'startDate'].map(key => project[key]);
});

```
```html
<div *ngFor="item of items | async">{{item}}</div>
```
Only does the async work once, and angular only has to execute change detection when that promise resolves, and then the whole application is stable.

**Comment by lastmjs** [comment]
The GetFromDatabaseById function could be any other asynchronous function, that was just an example. In my app the itemsService is more accurately represented by arbitrary services that are "injected" into the component at runtime. The component doesn't know what the items array will be exactly, but it knows that each item has a getPreviewText function that it will pass data to and that it will return some text.

**Comment by syndicatedshannon** [comment]
We just ran across a similar desire. Our view builds a navigable hierarchical structure of unknown size. We lazy-load branches based on runtime choices by the user, and those branches's data retrieval functions of course depend on parameters from parent nodes in the view. It would be convenient to call our `GetChildNodes(ExpandedBranchId) | async` directly from the view rather than having to create an otherwise empty Component for each node type in order to hold a constant value.

Please let me know if that use-case doesn't make sense.

**Comment by syndicatedshannon** [comment]
Hopefully my prior comment demonstrated a reasonable and common use-case. Please let me know if you feel I could adjust my implementation to a more angular2-natural approach. Or maybe there's some skewed thinking on my part; some reason my lambda<observable> in the view doesn't make sense in the big picture.

In our case, we hacked this functionality in for now. We use a custom ngFor-like structural directive similar to the following:

`*ngTreeLeaf="let nomination of getNominationsForPosition; with: [position.id];"`

Feel free to start a conversation with me about it.

The thing is, an observable inverts this sort of logic by design. The observable drives change detection rather than the converse, and it often isn't necessary to detect change in the observable. In fact, most of the time I don't need to detect changes in my observables. The observable *is* the change. This seems like a little bit of encouraging antipatterns to me.

It would be nice to have the ability to disable or suspend change detection on an item like this somehow.

**Comment by xmlking** [comment]
I have similar use case:
When a my delete button is clicked, I want to auto subscribe my controller's method from the template, that returns `Observable<any>`. Here the template dont care of the data that is encapsulated in `Observable`. All the side effects I needed are taken care in the controller and its super controller via .pipe(map,catchError,finalize) chain. 

 What am asking is enrich `async` pipe to support this use case or add new `async` pipe for auto subscribing controller's methods that return `Observable<void/any>`.  

my Controller method (which extends a super controller)
```ts
  delete(item: Account) {
    return this.confirmService.confirm('Confirm', `Delete ${item.name}?`)
      .pipe(  map( confirmed => {
        if (confirmed === true) {
          super.delete(item)
            .subscribe(
              result => {
                this.snack.open('Member Deleted!', 'OK', { duration: 4000 })
              },
              error => {
                this.snack.open(error, 'OK', { duration: 4000 })
              }
            );
        }
      }))
  }
}
```
What I am expecting 

template 
```html
        <button type="button" (click)="delete(entity) | async" color="warn" mat-icon-button>
          <mat-icon>delete</mat-icon>
        </button>
```

Workaround (what works now) 
```html
        <button type="button" (click)="delete(entity).subscribe()" color="warn" mat-icon-button>
          <mat-icon>delete</mat-icon>
        </button>
```
