### ISSUE TITLE
Problem with NumberValueAccessor.

### ISSUE THREAD

**Issue by giorgiofran** [angular/angular#7399]
Dart 1.14.0 Angular2 beta.7
I have the following component:
```
import 'package:angular2/angular2.dart';

@Component(selector: 'my-app',
    template: '''
    <form>
      <input type="number" [(ngModel)]="value" [readonly]="readonly" (input)="dummy()">
      {{value}}
    </form>
    ''',
    directives: const [FORM_DIRECTIVES])
class AppComponent {

  int value = 17;
  bool  readonly =false;

  dummy() {}
}
```
When I change a value I get the following error:

>  EXCEPTION: Error during evaluation of "ngModelChange"
>     (anonymous function)	
>   ORIGINAL EXCEPTION: type 'double' is not a subtype of type 'int' of 'value'.
>     (anonymous function)	
>   ORIGINAL STACKTRACE:
>     (anonymous function)	
>   #0      AppComponent.value= (package:error_ng2_numberValueAccessor/app_component.dart:19:7)
> #1      _AppComponent_0.handleEventInternal (package:error_ng2_numberValueAccessor/app_component.template.dart:235:24)
> #2      AbstractChangeDetector.handleEvent (package:angular2/src/core/change_detection/abstract_change_detector.dart:96:
> 

 If in the example above I use a double field..
`  double value = 17.0;`
everything works fine.

**Comment by zoechi** [comment]
This is not an Angular issue. Dart doesn't reliable support `int` in the browser. This is because of JavaScript limitations. It might also be related with recent changes in Dartium where previously when run in Dartium such code run fine but failed when built to JS.
Now this fails already in Dartium because they use dart-js-interop in the newest Dartium while the Dart VM previously access Chromes C++ API.

**Comment by pkozlowski-opensource** [comment]
Thnx @zoechi
