### ISSUE TITLE
Missing import should generate an error

### ISSUE THREAD

**Issue by yfain** [angular/angular#7513]
Here's the working plunk of a simple app: http://plnkr.co/edit/HC9zaCES5IcELRBx67c9?p=preview

It imports ProductDetailComponent from the file product-detail.ts.  Initially I forgot to add "import {Component} from 'angular2/core';" in  product-detail.ts and the application didn't work showing the blank screen and no errors.  To see this issue just comment out the import statement in product-detail.ts.

Angular should throw a meaningful error in such cases.

**Comment by pkozlowski-opensource** [comment]
Isn't it more of the TypeScript (or other transpiler) thing? BTW, I believe that TypeScript reports those errors (when used from the command line).

**Comment by yfain** [comment]
Will to try it with tsc. But there is another situation where the error reporting should be improved:  if you'll forget to mention a child component in @Component({ ... difectives:[Child]}) Angular renders a blank view without reporting any errors.

**Comment by btford** [comment]
While Angular can try to be clever about detecting non-native elements for which no directive is provided, it's not possible to catch all of these types of mistakes.

I'm going to close this issue since the first issue you mention is entirely outside the scope of Angular itself. If you'd like to open a separate issue describing your other suggestion, feel free to do so.

Thanks!
