### ISSUE TITLE
Angular 2 tutorial part 4 - SyntaxError: Unexpected token <(…)Zone.run @ angular2-polyfills

### ISSUE THREAD

**Issue by dragGH102** [angular/angular#7528]
I'm submitting a ... **bug report**

The issue arises at the end of Angular 2 tutorial - **part 4** and is a **generic error**: 
> SyntaxError: Unexpected token <(…)Zone.run @ angular2-polyfills

Some things I tried:

- to replace it in Plunkr (using almost the same code as the Plunkr provided in the tutorial): http://plnkr.co/edit/Q5F0mV8Hbdcr2rtZUSw5
- use locally the exact same code as the Plunkr provided at the end of tutorial part 4, same issue.

All the **details** are available in the question I posted on Stackoverflow: http://stackoverflow.com/questions/35893320/angular-2-tutorial-part-4-syntaxerror-unexpected-token

**Environment**: latest Angular beta (I just followed what the tutorial says to install it) + Typescript and ES6. Running on Linux Debian 8 and testing on Google Chrome v47 with cache disabled.

**Comment by ericmartinezr** [comment]
Hey @dragGH102 , you should keep the question on SO. This is not a bug since the plnkr in the tutorial works fine. Github is for bugs and such. You can move your question to [gitter's chatroom](https://gitter.im/angular/angular) as well. 

Besides that it's impossible to say without a reproduction of the failure, the only repro you've provided is a working plnkr, so if you can provide a failing plnkr or a repo people can clone and check would be helpful.

**Comment by templth** [comment]
@dragGH102 @ericmartinezr is right! I just answered you on SO according to what you provide in your question... Hope it'll help you to find out your problem ;-)

**Comment by pkozlowski-opensource** [comment]
Thnx @ericmartinezr and @templth !
