### ISSUE TITLE
ngfor vs ngFor and similarly ngif vs ngIf Angular2

### ISSUE THREAD

**Issue by LotusShiv** [angular/angular#7552]
I had issues with the ngFor and ngIf. According to the various information pools that I could pour into, some say to use ngfor and some say to use with F capitalized in ngFor and I capitalized in ngIf for example (camel case vs kebab case)... I know Angular2 is still in the beta stage and things are fluid. Still I had to play around and work with it and also if I use *ngFor (with a star preceding), the template was not processed on the browser I had to use without the *. I have a separate template as a .html file which I set for templateUrl and obviously the for loop and the if conditions are there. Anyway, I would like to know from the development community what other issues are you facing in this regard.

**Comment by zoechi** [comment]
Since alpha.47 templates are case sensitive https://github.com/angular/angular/blob/master/CHANGELOG.md#200-alpha47-2015-12-01
Therefore `*ngFor`, `ngIf` are correct. Tag names are still lowercase `router-outlet`, `ng-content` to stay compatible with the web components standard which requires a dash in the name of custom tags.

GitHub issues are for bug reports and feature requests. 
    For support questions please use other channels like the ones listed in [CONTRIBUTING - Got a Question or Problem?](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question)

**Comment by pkozlowski-opensource** [comment]
@LotusShiv - go through @zoechi response (thank you, again!) - he is completely right.
