### ISSUE TITLE
Angular 2 docs for ES6/7 (Babel)

### ISSUE THREAD

**Issue by dwiyatci** [angular/angular#7600]
To quote a sentence on Angular 2 homepage:

> While this example uses TypeScript, Angular works equally well with ES5, ES6 and Dart as well.

So, in the future will there be any hope for the Babel guys to have official docs on the website? :pray:

**Comment by PascalPrecht** [comment]
There won't be any docs specifically for babel as a transpiler. The examples of the docs are planned to be written in TS, ES5 and Dart. There's no ES6 specifically since TS is a superset anyways. And we think that developers are able to find out the differences (as those would really mainly be type annotations, decorates and interfaces). The first two you can even do with plugins in babel too, but there don't fully support decorators for all cases.

**Comment by MarkPieszak** [comment]
Very true, also if you're doing ES6 you might as well upgrade to Typescript!

**Comment by valera-rozuvan** [comment]
> also if you're doing ES6 you might as well upgrade to Typescript!

TypeScript will never end up in the browser. You will always have to compile your TypeScript project (2-5 years in the future, depending on how long your project will last).

I understand why people want to use ES6. Some time down the line they can turn off their transpiler and continue developing ES6 code right in their ES6 compliant browser.

**Comment by NicoJuicy** [comment]
Angular 2.0 from the start was announced to be Typescript focused, they also have ES5 and Dart. So that's 3 ways to show something.

I suppose Typescript is a better way in their vision than ES6. Perhaps it's more usefull to change their vision towards that ;)

**Comment by oelmekki** [comment]
I guess most of people reading this are aware of it, but just in case: this issues [has been published on Hacker News](https://news.ycombinator.com/item?id=12813653), which may explain why people voting on comments on angular github issues are less supportive of typescript than usual :)

Btw people, if you don't use angular2, don't contribute to this discussion (well, I just did, but...). HN's thread is a good place for that.

**Comment by jamesharrington** [comment]
@oelmekki  if i have a voice on the future of angular 2 it makes sense to speak up here. EG: i have never used Angular2 the main reason is the strong focus on typeScript.  
So if i can sway the devs decision to add es6/7 docs it would lower my barrier to entry.  
Just food for thought.

**Comment by oelmekki** [comment]
@jamesharrington Fair enough :) At least, you mention you don't use it. I doubt all the :+1: and :-1: in this thread are from actual angular users.

**Comment by valera-rozuvan** [comment]
I am a strong believer in Angular (1 & 2) and in JavaScript. I am using Ng1 & Ng2 on production. I even have a seed project for Ng2 that uses pure ES6 (no legacy Babel plugins). See https://github.com/valera-rozuvan/angular2-es6-seed .

I know how much it hurts when you can't find decent documentation for Ng2 with ES6.

**Comment by MarkPieszak** [comment]
I didn't realize I got downvoted like crazy. :(

I didn't mean that in a negative way! As in, "it's TypeScript or nothing". 
You can code Angular2 in ES5, ES6, banascript (kidding), whatever you want. (I could be wrong) but I'm not sure there is an effort to create ES6 documentation since (as Pascal was saying as well) it'd basically mirror the TypeScript one.  
One of the major changes I can think of is that instead of using dependency injection like `private http: Http` you'd just do `@Inject(Http) http`. Other than that, if you basically disregard *types*, and other things, the documentation would be identical.
Maybe @Foxandxss could provide a better answer for this thread though.

----

Out of curiosity, what makes you want to stay away from TypeScript? @jamesharrington 
Besides Types and a few other relatively minor things, ES6 is basically the same thing minus some of the tooling benefits and code readability. 

@valera-rozuvan I totally get that, eventually you could completely remove a transpiler, but there will always be an IE6, IE8, and I'm sure IE11 will be the next one, that's holding everyone back from using all the latest & greatest features of JavaScript. So I can't imagine a time without using a transpiler of some kind through out development. I do miss the days of live editing in the browser, so I have to agree, it would be nice :)

**Comment by MarkPieszak** [comment]
That's very true! I almost forgot that.
Maybe at the very least, we could try and throw together a best-practices for ES6, and how to interpret some TS things in the documentation in an ES6 way? I could try and help put something like that together if it'd benefit people!

**Comment by valera-rozuvan** [comment]
> Maybe at the very least, we could try and throw together a best-practices for ES6, and how to interpret some TS things in the documentation in an ES6 way?

Examples of how to do in ES6:

- metadata
- decorators
- dependency injection
- directives that interact with elements in components
- services that handle communication between components with different parents
- inputs/ouputs
- etc.

**Comment by ocombe** [comment]
A lot of this things will be in the ES5 docs, the only difference between ES5 and ES6 are features that are totally angular independent and that you had to learn another way, it's not angular's role to teach you ES6. If you know ES6, then reading the ES5 docs should be enough to figure things out.

**Comment by MarkPieszak** [comment]
@valera-rozuvan 
So as for the documentation, apparently something is in the works! I'm not positive on what it exactly will entail, but there will be something geared towards ES6/7 at least :)

**Comment by robwormald** [comment]
FYI all, this is in progress already at https://github.com/angular/angular.io/pull/2606

**Comment by MarkPieszak** [comment]
Here's the Angular Universal starter written in ES6 (using Babel) for those that find this thread and are interested: https://github.com/MarkPieszak/universal-es6-starter

**Comment by valera-rozuvan** [comment]
@MarkPieszak Wow! Thanks dude. Very useful.
