### ISSUE TITLE
Tutorial on using webcomponents would be welcome!

### ISSUE THREAD

**Issue by robinbakkerus** [angular/angular#7659]
Currently there is an excellent tutorial explaining the basic concept of Angular2. 
There is (imo) one chapter missing however.
On of the reasons (if not the most important reason) to completely rewrite Angular, is to better support the upcoming webcomponents standard. Unfortunately how to setup and use webcomponents, like for example Polymer, is not explained in a worked out tutorial (like the Heroes tutorial). I could very much welcome such a tutorial.

Txs in advance.

**Comment by zoechi** [comment]
Docs issues are maintained in https://github.com/angular/angular.io.

I guess what you want yet needs to be implemented and that's one of the reasons there are no docs yet.
My experience with Polymer elements so far:
- Add full `web-components` polyfills instead of `web-components-lite`
- enable full shadow DOM (https://www.polymer-project.org/1.0/docs/devguide/settings.html)
- passing `<template>` tags to Polymer elements (like required for `<core-list>`) doesn't work because Angular handles the template before Polymer gets it
- style modules to style Polymer elements, can only be added in `<head>` or inside Polymer elements, but not in Angular components. 
- In some cases it might help to disable view encapsulation `encapsulation: ViewEncapsulation.None`

**Comment by robinbakkerus** [comment]
Wow, thank for this very rapid response!
Any idea when the "*what you want yet needs to be implemented" *will be
implemented ?

On Fri, Mar 18, 2016 at 9:52 AM, Günter Zöchbauer <notifications@github.com>
wrote:

> Docs issues are maintained in https://github.com/angular/angular.io.
>
> I guess what you want yet needs to be implemented and that's one of the
> reasons there are no docs yet.
> My experience with Polymer elements so far:
>
>    - Add full web-components polyfills instead of web-components-lite
>    - enable full shadow DOM (
>    https://www.polymer-project.org/1.0/docs/devguide/settings.html)
>    - passing <template> tags to Polymer elements (like required for
>    <core-list>) doesn't work because Angular handles the template before
>    Polymer gets it
>    - style modules to style Polymer elements, can only be added in <head>
>    or inside Polymer elements, but not in Angular components.
>    - In some cases it might help to disable view encapsulation encapsulation:
>    ViewEncapsulation.None
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/angular/angular/issues/7659#issuecomment-198261088>
>



-- 
met vriendelijke groeten
Robin Bakkerus
robin.bakkerus@gmail.com

**Comment by zoechi** [comment]
No idea, but it doesn't look like it will make it into the first release.

**Comment by pkozlowski-opensource** [comment]
This should be opened in  https://github.com/angular/angular.io.
