### ISSUE TITLE
Typings should not be included in the package (npm)

### ISSUE THREAD

**Issue by ioan-h** [angular/angular#7681]
**Note: for support questions, please use one of these channels:** https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question. This repository's issues are reserved for feature requests and bug reports.

* **I'm submitting a ... **
[x] bug report
[ ] feature request
[ ] support request => Please do not submit support request here, see note at the top of this template.

* **What is the current behavior?**

Angular2 package contains typings files when it shouldn't.
ex: node_modules/angular2/typings under which you will find es6-shims.d.ts & jasmine.d.ts

* **What is the expected behavior?**

Expected behaviour is to add any necessary typings as instructed in your own guide: https://angular.io/docs/ts/latest/quickstart.html#!#typings
(basically installing the typings as we would normally do for any typings)

* **What is the motivation / use case for changing the behavior?**

It causes unnecessary typescript compilation issues when using webstorm and node_modues cannot be excluded (and should not) as it is the library home.
There is a standard mechanism in place for obtaining typings and your package should respect that.

* **Please tell us about your environment:**

Webstorm IDE

**Comment by kylecordes** [comment]
Back a couple of months, some of the transitively needed typings were included with Angular. Then they were removed for a while. Now a small set has come back in; I think this might be an intentional choice by the Angular team. I don't know all the trade-offs, it will be interesting to see which way it ends up for release.

I think there's been some shift in the expected use of the tools. Early on, the typical configuration of typescript was to let it look all over your project to grab files, excluding just specific bits. More recently, I've seen more projects which selectively include just the key starting point files.  For example, consider the following files section of a TSconfig file:

  "files": [
    "src/app.ts",
    "node_modules/angular2/typings/browser.d.ts",
    "node_modules/zone.js/dist/zone.js.d.ts"
  ],

This is enough to let me compile Angular application code, in a small project that doesn't use typings (or tsd) at all. Note that if the files section is present, the exclude section is invalid and is ignored - I have seen highly numerous example tsconfig.json files in example Angular projects which include both sections, indicating many developers out there don't know that the exclude section is irrelevant (and ignored) if files are specified.

I haven't checked all the all this ties in with web storm though, perhaps someone else will have something to say about that. I think for now it is best to make things work as smoothly as possible with the essential underlying tools (the typescript compiler and its configuration file) and hope the IDEs follow along closely.

**Comment by ioan-h** [comment]
For anyone reading, tsd was deprecated in favor of typings.

That said, adding typings to the npm package creates inconsistencies as the agular team may decide they do so, other packages may decide not to.

I believe the package should not [try to] be more than what is expected, as in the necessary sources to develop an angular2 app. Just as npm installs this packages dependencies next to it (as in the package manager downloads the actual dependency and is not included within the package itself), there is a standard mechanism in place and it should be respected.

Not respecting an established standard is aggravating in larger projects as you need to put effort in dealing with "exception" cases. 

**That said, it is very dangerous for the angular2 package to include typed definitions for other packages within it's package.** Can you imagine the mess it would cause if many packages did that? It would be chaotic as hell to deal with. Also, packages tend to be less often updated than the typed definitions, meaning they don't follow similar deployment/update cycles.

**Comment by alexeagle** [comment]
There is an important distinction: including some files in our distribution, vs. *referencing* those files from angular sources.

As @kylecordes says, it can be convenient to have angular's dependencies available in the package. You can point your typescript compiler at them without installing anything separate, and you can be sure they are at the correct version. Installing things through the typings side-channel introduces the possibility of version skew.

We include a "browser.d.ts" here https://github.com/angular/angular/blob/builds-js/typings/browser.d.ts
specifically so that you can do a quickstart in 5m without installing any typings.

However, this is your decision in setting up your angular 2 project. Our official quickstart on angular.io instead recommends using the typings CLI to fetch ambient typings into your project.

The fix for this issue is to exclude "node_modules" in your `tsconfig.json`, which is the default setting when you run `tsc --init`.

I'll close as working as intended, please re-open if this doesn't solve your problem.
