### ISSUE TITLE
ReplacePipe only replaces the first instance of `pattern`

### ISSUE THREAD

**Issue by positron** [angular/angular#7760]
[plnkr of the problem](http://plnkr.co/edit/0qxNRWwwi7HzrpB9SKdS?p=preview)

**Current behavior**
`{{ 'a_b_c' | replace:'_':' ' }}` outputs `a b_c`

**Expected/desired behavior**
`{{ 'a_b_c' | replace:'_':' ' }}` outputs `a b c`

The [documentation](https://angular.io/docs/ts/latest/api/common/ReplacePipe-class.html) mentions an optional `flags` argument, but it only accepts two arguments.

**Comment by positron** [comment]
I would work around this by using `{{ 'a_b_c' | replace:/_/g:' ' }}` but that results in:

```
Lexer Error: Unterminated quote at column 29 in expression [ 'a_b_c' | replace:/_/g':' ' ] ("
    <div>
      <h2>[ERROR ->]Hello {{ 'a_b_c' | replace:/_/g':' ' }}</h2>
      
    </div>
"): App@2:10
```

http://plnkr.co/edit/kzjAvwQ8vVqxLvCnxhtU?p=preview

**Comment by TTTee** [comment]
A possible 'workaround':
```javascript
//our root app component
import {Component} from 'angular2/core'

@Component({
  selector: 'my-app',
  providers: [],
  template: `
    <div>
      <h2>Hello {{ 'a_b_c' | replace:myRegex:' ' }}</h2>
    </div>
  `,
  directives: []
})
export class App {
  myRegex = /_/g;
  constructor() {
    this.name = 'Angular2'
  }
}
```
Somehow it is currently not possible to add inline RegEx. The string you pass in won't be converted to RegEx by Angular at the moment, but it seems like they are working on it (see [here](https://github.com/angular/angular/blob/master/modules/angular2/src/common/pipes/replace_pipe.ts#L67)). So this might be fixed in the future. Under the hood it uses [string.replace()](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/replace) and this will only replace the first occurrence if you pass in a string. Hope this helps a bit.

**Comment by pkozlowski-opensource** [comment]
Obsolete as the replace pipe is gone.
