### ISSUE TITLE
RangeError: Maximum call stack size exceeded

### ISSUE THREAD

**Issue by bvaughn** [angular/angular#7930]
It seems incredibly easy to cause an infinite loop in a production Angular 2 app. The following example code is the most simplified reproduction case I could come up with. In dev mode, it displays what you would expect and logs the following text:
```
Demo.constructor
TopLevelComponent.constructor
SecondLevelComponent.constructor
```

In production mode the `SecondLevelComponent` gets recreated until the stack overflows. (The "_SecondLevelComponent.constructor_" message prints on loop.)

Removing either of the un-used public methods (`someMethod`) causes the problem to go away.

This is an over-simplification but it's essentially what I'm trying to do for the [bvaughn/ng2-virtualized](https://github.com/bvaughn/ng2-virtualized) demo app. The app works fine when running locally, in dev-mode. But the static production build (visible [here](http://bvaughn.github.io/ng2-virtualized/)) fails.

## Steps to reproduce and a minimal demo of the problem

Here's a Plnkr: https://plnkr.co/edit/5kHjjmkWbYpi7y8nHTqL?p=preview

And here's the source code:

#### HTML
```html
<html>
  <head>
    <script src="https://npmcdn.com/angular2@2.0.0-beta.13/bundles/angular2-polyfills.js"></script>
  </head>
  <body>
    <demo>Loading...</demo>
  </body>
</html>
```

#### JavaScript
```js
import {Component, Input, OnInit} from 'angular2/core'
import {bootstrap} from 'angular2/platform/browser'

@Component({
  selector: 'second-level-component',
  template: 'SecondLevelComponent'
})
class SecondLevelComponent  {
  constructor () {
    console.log('SecondLevelComponent.constructor')
  }

  // Note that without both this method and the one below, the error does not happen
  // But neither method is actually called
  someMethod () {}
}

@Component({
  directives: [SecondLevelComponent],
  selector: 'top-level-component',
  template: `
    <h1>TopLevelComponent</h1>
    <second-level-component></second-level-component>
  `
})
class TopLevelComponent {
  constructor () {
    console.log('TopLevelComponent.constructor')
  }

  // Note that without this method (or the one above) the error does not happen
  // But neither method is actually called
  someMethod () {}
}

@Component({
  directives: [TopLevelComponent],
  selector: 'demo',
  template: '<top-level-component></top-level-component>'
})
class Demo {
  constructor () {
    console.log('Demo.constructor')
  }
}

bootstrap(Demo)
```

#### Runtime error

```
browser_adapter.js:76Error: Uncaught (in promise): RangeError: Maximum call stack size exceeded
    at resolvePromise (angular2-polyfills.js:543)
    at angular2-polyfills.js:579
    at ZoneDelegate.invokeTask (angular2-polyfills.js:365)
    at Object.inner.inner.fork.onInvokeTask (ng_zone_impl.js:35)
    at ZoneDelegate.invokeTask (angular2-polyfills.js:364)
    at Zone.runTask (angular2-polyfills.js:263)
    at drainMicroTaskQueue (angular2-polyfills.js:482)
```

**Comment by mhevery** [comment]
I love the writeup. I wish all errors would be written up so well! Thank you for making our life easy.

This is a known issue and it has to do with minification. In short the minification is broken in Angular as of right now. The fix will come as part of https://github.com/angular/angular/pull/6567 in a week or so. The issue is that when the minfier munges the code  the classes get renamed and collide. `<second-level-component>` then gets added recursively which causes a stack overflow.

**Comment by gdi2290** [comment]
here's a current workaround for the bundle build https://github.com/angular/angular/pull/7988 you need to turn off mangle so props could be invoked and allow function names for directives/components/pipes to work in the template

**Comment by bvaughn** [comment]
Thanks for the details @mhevery and the workaround @gdi2290 :)

Glad to hear it's a known issue and a fix is on the way. Best outcome I hope for.

**Comment by bvaughn** [comment]
FWIW was able to get a working static build made by removing the `-p` param to Webpack and disabling mangling like so:

```js
    new webpack.optimize.UglifyJsPlugin({
      mangle: false,
      sourceMap: false
    })
```

(Posting in case it helps others, as I don't think Webpack and Angular 2 are a very common pair at the moment.)

**Comment by gdi2290** [comment]
the problem has more to do with the JIT template refactor from beta.1 and Uglify than webpack and angular2. You can reproduce the same error with systemjs or anything using Uglify

**Comment by bvaughn** [comment]
Yup, that was understood. Sorry. I was just trying to leave steps to fix it behind in case _anyone else_ also using Webpack and Angular 2 encountered this issue. :)

**Comment by zwhitchcox** [comment]
@bvaughn Brian! Thank you! Just wanted to confirm that I am a fellow angular 2/webpack user, and I've been trying to fix this for days, and your solution definitely helped! Thanks!

**Comment by kokokenada** [comment]
I'm getting this using Meteor 1.3 and angular 2 rc1.   Is the fix in rc1? (i.e. do I have a new issue?)

**Comment by henrique-rotava** [comment]
@kokokenada have you found a solution? I am using angular2 rc.1 with Meteor 1.3 too and I can't make the app work on Safari or any iOS browser because it throws [Error] RangeError: Maximum call stack size exceeded. In other contexts it works fine.

I have found that this happens on any xhr call, after the first one the app simply crashes. It happens when ng2-translate requires the json file from the server and also when angular tries to load any component's HTML template set on templateUrl.

**Comment by kokokenada** [comment]
@hankduan  - yes I was able to get it going.  It's a matter of getting the right magically combination of versions, I think. You should be able to use the package.json in https://github.com/kokokenada/for-real-cards to replicate the setup.  It's still at angular rc1 while I wait for the dust to settle from rc2.

**Comment by henrique-rotava** [comment]
@kokokenada, thank you! After I upgraded my meteor packages, removing and adding all of them again, it is finally working.

**Comment by nnIIInnjA** [comment]
I am not even minifying any file , still getting this.

**Comment by ganeshkbhat** [comment]
Is this bug/issue fixed/resolved? I am getting errors with Third party libraries which are minified.

**Comment by nnIIInnjA** [comment]
@ganeshkbhat in my case i was loading some wrong static files. for example :- instead of template html file, i was getting root index.html file and that file upon loading was requesting same resources again and again. so it was going in a loop.

**Comment by dpdonohue** [comment]
I had this problem.  I was using this:
````
@Component({
  templateUrl: './my.html'
})
````

It resolved when I switched to this:
````
import template from './my.html';
@Component({
  template
})
````

**Comment by ganeshkbhat** [comment]
@dpdonohue and @nnIIInnjA I know my problem is because of usage of minified files. I am using minfied RightJS for tabs to get a small footprint for a dynamic tabbed structure. When I add the files to index.html using script tags it gives this error. But when I put the files to map in systemjs.config the objects RightJS is not found 'even' after declaring the object in a .ts file

**Comment by afaslan** [comment]
I had the same problem and SOLVED my problem. I accedentally imported the same module which is TravelsModule in TravelsModule.. :) Recursive import results this probem. I removed that import and my problem is solved. As an example, I pasted it below and commented wrong line..

```typescript
@NgModule({
    imports: [
        CommonModule,
        RouterModule,
        //TravelsModule, <----- This line causes the problem
    ],
    declarations: [
      
    ],
    providers: [
      
    ],
    exports: [
      
    ]
})
export class TravelsModule {}
```

```
Uncaught RangeError: Maximum call stack size exceeded
    at Object.U (http://localhost:4200/main.bundle.js:55401:126)
    at Object.Type (http://localhost:4200/main.bundle.js:37:146)
    at isValidType (http://localhost:4200/main.bundle.js:24279:157)
    at http://localhost:4200/main.bundle.js:23808:25
    at Array.forEach (native)
    at CompileMetadataResolver.getNgModuleMetadata (http://localhost:4200/main.bundle.js:23806:44)
    at http://localhost:4200/main.bundle.js:23819:50
    at Array.forEach (native)
    at CompileMetadataResolver.getNgModuleMetadata (http://localhost:4200/main.bundle.js:23806:44)
    at http://localhost:4200/main.bundle.js:23819:50(anonymous function) @ main.bundle.js:55401(anonymous function) @ index.js:1isValidType @ metadata_resolver.js:685(anonymous function) @ metadata_resolver.js:214CompileMetadataResolver.getNgModuleMetadata @ metadata_resolver.js:212(anonymous function) @
 ....
 ....
 ....
metadata_resolver.js:212(anonymous function) @ metadata_resolver.js:225CompileMetadataResolver.getNgModuleMetadata @ metadata_resolver.js:212(anonymous function) @ metadata_resolver.js:225CompileMetadataResolver.getNgModuleMetadata @ metadata_resolver.js:212(anonymous function) @ metadata_resolver.js:225
```

**Comment by sqlsolver** [comment]
After ten days of debugging the only thing that resolved this for me was switching to an inline template from templateUrl. This issue does not occur with systemjs, only with webpack build. In a systemjs build I had the following:

*  Index.ejs has selector from the root app component which is bootstrapped by NgModule.
  *  The root app component's template has two entries, first the router outlet and then the chrome components selector.
    *  The chrome component has two routerLink entries for additional component views.

First I checked for unused methods in my solution per the initial comments from @bvaughn above, and this had no effect. I also checked each component for circular references. I then started yanking away functionality until I was down to just trying to bootstrap the main app component, and still had the error. I started a fresh app directory on my host and redeployed in case a cached value was the issue. All throughout webpack was building successfully, but Chrome spewed call stack errors while Firefox said I had 'too much recursion.' Lines in the error messages referencing webpack's outputted file were generally around creating either the module or app view prototype.

Since this occurs only with webpack I logged a new issue there linking back to this thread [#3334](https://github.com/webpack/webpack/issues/3334).

**Comment by honpery** [comment]
```
npm install angular2-template-loader --save-dev
```
add angular2-template-loader to webpack config ts loaders.

The loader depend on node type(require), if not config @type/node , follow:
```
npm install @type/node --save-dev
```
edit `tsconfig.json`, add follow config:
```
"types": ["node"]
```

**Comment by fletchsod-developer** [comment]
We had this issue and was able to resolve it by taking out the "<app></app>" tag which the Component.ts use `selector: 'app'`.  Weird.

**Comment by Nirmalkusahoo** [comment]
The same error I was getting because in the child module I was trying to call my initial child component by using 
bootstrap: [ChildFirstComponent] in my Child Module.

So instead I created  **ChildRoute** and from there I called my ChildComponent like below.
#######################
const childRoutes:Routes=[
    {path:'',component:ChildComponent},
]

@NgModule({
    imports:[RouterModule.**forChild**(childRoutes)
)],
    exports:[RouterModule]
})

##############################

Note:Use RouterModule.forChild() in the import array while you are creating child route files

**Comment by TaylorPzreal** [comment]
when you are using lazyload, don't forget  below conf:
```
@NgModule({
  imports: [
    RouterModule.forChild(ROUTES)
  ]
})
```

**Comment by masimplo** [comment]
Is there any way to track down the source of this error? I am getting this error running angular 4.4.3 in production and cannot track it down.

**Comment by inthegarage** [comment]
@masimplo I would start reducing your app, so that it just displays one page. What dependencies are needed and are they cyclic? Typically it's where your app needs something, so it goes away and get's that child item, the childitem needs something higher up and so on. Check if you've got cyclic dependencies. I'm not sure I've seen the templateurl version.

**Comment by uscbsitric** [comment]
An uncaught exception prevents Augury from continuing <--- FUck you

**Comment by mhevery** [comment]
@uscbsitric Your comment is in violation of our code of conduct and will be removed. 

I understand that at times we all get frustrated when code does not work. Code is hard. But there is no need to be offensive on a public forum. Your negativity effects other people around you. https://www.google.com/search?q=negativity+brings+people+around+you+down

**Comment by uscbsitric** [comment]
i think I left the browser open while I was at the internet cafe did not log out. 

    On Wednesday, March 14, 2018 11:07 AM, Miško Hevery <notifications@github.com> wrote:
 

 @uscbsitric Your comment is in violation of our code of conduct and will be removed.I understand that at times we all get frustrated when code does not work. Code is hard. But there is no need to be offensive on a public forum. Your negativity effects other people around you. https://www.google.com/search?q=negativity+brings+people+around+you+down—

**Comment by uscbsitric** [comment]
i just noticed this when I was checking my email.
