### ISSUE TITLE
@ContentChildren does not work when bootstrapping with UpgradeAdapter

### ISSUE THREAD

**Issue by vojtapol** [angular/angular#7933]
I need to query the list of child elements from my element. Both the parent and its children are Angular 2 components but when downgraded and used within Angular 1 app the @ContentChildren query always returns an empty list. Plunker reproducing this issue is below:

http://plnkr.co/edit/w7IAOo6wAml2KDSiSesa?p=preview

**Current behavior**
ContentChildren() query returns an empty list

**Expected/desired behavior**
ContentChildren() should return a list of three elements

**Comment by noamichael** [comment]
I also encountered this issue running Angular 1.5.6 and Angular 2.0.0-rc.1.

**Comment by lukas99** [comment]
Same problem here. I use Angular 1.3.20 and Angular 2.0.0-rc.1.

Is it planned to fix this issue?

**Comment by lukas99** [comment]
I found a workaround:

Create an Angular 2 wrapper component which uses the parent and child components in it's template. In this component, you import your parent and child components and define them as directives in the @Component configuration. Then you only downgrade your wrapper component and use this one in your html.

**Comment by ToolsMonkey** [comment]
The workaround is not viable option when you want to create a component where uix designers use markup to create the layout, in short I need to keep it simple, rather than sending in tons of options into an init function.

Ex:
using
`
@ContentChildren(Ng2Tab) childDirectives: QueryList<Ng2Tab>;
`
to get tabs children does not return any children

    <ng2-tabs>
        <ng2-tab [tabTitle]="'Tab 1'">stuff</ng2-tab>
        <ng2-tab tabTitle="Tab 2">more stuff</ng2-tab>
        <ng2-tab tabTitle="Tab 3" class="extranicestuff">otherstuff</ng2-tab>
    </ng2-tabs>

(using a1.5 code, where tabs/tab is 2.0 so downgrading it)

Is there any other working way of getting children? This is currently a blocker for me.

**Comment by pchoi** [comment]
Is there any update this? Would appreciate an alternate workaround than creating a wrapper...

**Comment by gotvitch** [comment]
I also encounter this issue, any update on it ?

**Comment by insomniac34** [comment]
Same issue here. The workaround is not viable for those using an arbitrary number of child components within <ng-content> tags.

**Comment by vojtapol** [comment]
I honestly can't comprehend how could this bug still be there after so many
updates. The UpgradeAdapter is a half-assed bogus and it is now clear that
when the Angular team promised that they would provide ways for smooth
transition from angular1 they were lying.

**Comment by banjankri** [comment]
over 18 months since reported and no update on it? seems like a pretty basic scenario to cover ....

**Comment by gkalpak** [comment]
Sorry it took so long to respond. And to make things worse, I don't even have good news to share 😛 

For `@ContentChild`/`@ContentChildren` to work, Angular needs to be in charge of that content. In a downgraded component this is not the case (AngularJS owns whatever is inside the downgraded components, since it is an AngularJS directive after all).

So, unfortunately, it is not possible to make `@ContentChild[ren]` work for downgraded components 😞 
(Just to be clear, `@ViewChild[ren]` will still work fine.)
