### ISSUE TITLE
Allow directive to guard ChangedDetection

### ISSUE THREAD

**Issue by mhevery** [angular/angular#795]
Any directive should be able to disable change detection below it (light DOM), if it knows that the current view is not visible. This needs to be annotation level information so that the HTML compiler can generate additional `ChangeDetection` class for the current view. The presence of the `ChangeDetectionControl` type in the injection will let the compiler know that we have to have artificial change detection boundary for the child elements.

```
@Decorator({
  selector: 'pane',
  bind: {
    'selected': 'selected'
  }
})
class Pane interface  {
  cdc:ChangedDetectionControl;
  constructor(cdc: ChangeDetectionControl) {
    this.cdc = cdc;
  }

  set selected(value) {
    this.cdc.enable(value);
  }
}
```

This would allow for:
```
<pane [selected]="false">
   {{ supper expensive binding which will be disabled when pane not selected.}}
</pane>
```

**Comment by mhevery** [comment]
@davideast fyi

**Comment by mhevery** [comment]
@vsavkin can you comment?

**Comment by vsavkin** [comment]
Since we are paying a source-code size penalty for every change detector class, I am considering encoding this logic into a detector (sort of like a goto statement). Another option would be to have a lightweight class (e.g., SubDetector).

This is a non-trivial change that should take a few days (maybe a week) to implement.

**Comment by mhevery** [comment]
I think this is obsolete thinking, and as such I am closing this.
