### ISSUE TITLE
Passing data to transcluded content

### ISSUE THREAD

**Issue by koganei** [angular/angular#8006]
Hi,
I'm trying to pass data from my directive to transcluded content.
The (slightly contrived) use case I have in my plunkr is this:
I have a component called show-min-max which allows me to show the lowest and highest number of an array of integers.
I'd like the consumer of my component to be able to transclude whatever template they require next to each min and max displayed numbers, so that they can have access to the min and max data, and they can do whatever they want with it within a certain area of my component.

**Steps to reproduce and a minimal demo of the problem**
http://plnkr.co/edit/Gg3R7RDrl7wCb67dLnTA?p=preview

**Current behavior**
There doesn't seem to be a way to pass data along to transcluded content.

**Expected/desired behavior**
In this plunkr, I gave a possible solution where you attach certain properties to the ng-content tag (```<ng-content [value]="someVar" select=[someSelector]>```, and expect to see them when attaching a variable to the transcluded tag (```<div someSelector #myDiv>{{myDiv.value}}</div>```)

**Other information**
Let me know if you need more info.

**Comment by zoechi** [comment]
You can do something like

```html
  template: `
  <show-min-max [items]="items" #minMax>
    <span min>
      <button (click)="pick(minMax.min)">Pick {{minMax.min}}</button>
    </span>
    <span max>
      <button (click)="pick(minMax.max)">Pick {{minMax.max}}</button>
    </span>
  </show-min-max>`,
```

[Plunker](http://plnkr.co/edit/jqimrlCgG2Qp2764rdEw?p=preview)

GitHub issues are for bug reports and feature requests.
    For support questions please use other channels like the ones listed in [CONTRIBUTING - Got a Question or Problem?](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question)

**Comment by koganei** [comment]
@zoechi Interesting, but still pretty limiting. It doesn't allow for slightly more complex use cases like having an ng-content in an ngFor (which was my original use case, but is currently not working), or having nested directives and giving the right piece of data to the right ng-content and hide it from another ng-content.
Thanks for this solution though, it's definitely a step in the right direction.

**Comment by zoechi** [comment]
For `ng-content` in `ngFor` see #4631

For repeating a template `ngForTemplate` might help https://angular.io/docs/ts/latest/api/common/NgFor-directive.html

**Comment by koganei** [comment]
Nice, thanks for this. I'll make a new plunkr later today with a use case where doing #minMax on the tag wouldn't work because the ng-content would be nested in the ngForTemplate.

**Comment by pkozlowski-opensource** [comment]
@koganei going to close for now but happy to re-open when you've got a concrete use-case and an associated plunker.

**Comment by f-mon** [comment]
I'm not very happy with the solution of using a ref  # to the outside component from within the transcoder content, if you use multiple time the outer directive in a template you should came up every time with a different id. I think ngcontent should provide a  way to pass scoped variables to the content it is transcluding, for example it could be a generic inputs attributes that pass the values es:
<ng-content [inputs.myvar1]="myvalue1" ></ng-content>

**Comment by zoechi** [comment]
@f-mon I'd suggest using `<template let-item>your content<template>` and use `<template [ngTemplateOutlet]="myTemplate" [ngOutletContext]="{$implicit: data}">` instead of `<ng-content>`

**Comment by yassern** [comment]
any news?

**Comment by zoechi** [comment]
@yassern any news about what? This issue is closed since 2 years.

**Comment by mikila85** [comment]
... +1

**Comment by mfsi-nirmitm** [comment]
i have tried the same method , but not working .

code -
<div>
<ng-content [value]="'test'" select=[selector]></ng-content>
</div>


but it is giving me the following error ->

Can't bind to 'value' since it isn't a known property of 'ng-content'.
1. If 'value' is an Angular directive, then add 'CommonModule' to the '@NgModule.imports' of this component.
2. To allow any property add 'NO_ERRORS_SCHEMA' to the '@NgModule.schemas' of this component. ("
<div *ngIf="object && isObject()" >
	<ng-content [ERROR ->][value]="'value'" select="[selector]" ></ng-content>
</div>

**Comment by Tucaen** [comment]
Maybe I'm  just missing some best-practice of Angular or any other concept here, but I think a
concrete use-case could be reusing a `ngFor ` in a `ngSwitch`.

For example I want a dropdown to support different ways of displaying it's data.
1. normal list of values
2. label + value and multiple lines
3. table
... more to come maybe

Coding in the drop component would be:
`
<div class="chosen-drop-container">
    <ng-container [ngSwitch]="type">
      <ng-container *ngSwitchCase="typeEnum.Value">
         <ul class="chosen-results">
          <ng-container *ngIf="options && options.length; else emptyTpl">
            <ng-container *ngFor="let option of options">
              <li *async="option.disabled; let disabled" class="active-result" [class.disabled]="disabled"
          [class.selected]="option.selected && !useCheckbox" (mouseover)="focus(option)" (click)="selectOption(option, disabled, $event)">
                <ng-content></ng-content>
              </li>
            </ng-container>
          </ng-container>
        </ul>
      </ng-container>
      <ng-container *ngSwitchCase="typeEnum.List">
         <ul class="chosen-results">
          <ng-container *ngIf="options && options.length; else emptyTpl">
            <ng-container *ngFor="let option of options">
              <li *async="option.disabled; let disabled" class="active-result" [class.disabled]="disabled"
          [class.selected]="option.selected && !useCheckbox" (mouseover)="focus(option)" (click)="selectOption(option, disabled, $event)">
                <ng-content></ng-content>
              </li>
            </ng-container>
          </ng-container>
        </ul>
      </ng-container>
      <ng-container *ngSwitchCase="typeEnum.Table">
        
      </ng-container>
    </ng-container>
</div>
`

Goal is to reuse the "ngFor-overhead" used in Value- and List-Mode. I know I could create a component and pass the corresponding template for Value- and List-Items, using `ng-template [ngTemplateOutlet]="optionTemplate" [ngTemplateOutletContext]="{ $implicit: option }"></ng-template>` instead of `ng-content` in this component. But I would also have to make the css and outputs work, which would be possible, but than it just feels more convenient to just copy-paste the "overhead" and make adjustments twice.
