### ISSUE TITLE
LifeCycle calls are not called on router navigation.

### ISSUE THREAD

**Issue by jcdalton2201** [angular/angular#8012]
**IMPORTANT**: This repository's issues are reserved for feature requests and bug reports. Do not submit support requests here, see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question. 

**Steps to reproduce and a minimal demo of the problem**
we are using beta 14 with babel compile. when we navigate from one path to a second path the component lifecycle is not being called. if anything happens on the compoent then the ngOnInit will be called.

code pased below.

_What steps should we try in your demo to see the problem?_

**Current behavior**
click on the task links, the routerOnActivate will be called but the ngOnInit will not be called. when we click on the back button then the ngOnInit will be called.

**Expected/desired behavior**
ngOnInit should be called when we navigate to the component.

**Other information**
main.js
```javascript
import 'angular2-polyfills';
import 'reflect-metadata';
import 'babel-polyfill';
import {bootstrap}    from 'angular2/platform/browser';
import {routeTestComponent} from './app.component';
import {ROUTER_PROVIDERS} from 'angular2/router';
bootstrap(routeTestComponent, [ROUTER_PROVIDERS]);
```
app.component.js
```javascript
import {Component} from 'angular2/core';
import {ROUTER_DIRECTIVES,RouteConfig} from 'angular2/router';
import {Dashboard} from './components/dashboard/dashboard.component';
import {About} from './components/about/about.component';
import {Tasks} from './components/tasks/tasks.component';
@Component({
  selector: 'route-test',
  template: `
  <h1>App</h1>
   <a [routerLink]="['/Dashboard']" class="link">Dashboard</a>
   <a [routerLink]="['/About']" class="link">About</a>
   <a [routerLink]="['/Tasks']" class="link">Tasks</a>
    <router-outlet></router-outlet>
  `,
  directives: [ROUTER_DIRECTIVES]
})
@RouteConfig([
  {path: '/', component: Dashboard, name: 'Dashboard'},
  {path: '/about', component: About, name: 'About'},
  {path: '/tasks/...', component: Tasks, name: 'Tasks'}

])
export class routeTestComponent { }
```
components/dashboard
```javascript
import {Component} from 'angular2/core';
@Component({
  selector: 'dashboard',
  template: '<h1>Dashboard App</h1>',
  directives: [],
  inputs:[],
  outputs:[],
  pipes:[]
})

export class Dashboard { }
```
components/about
```javascript
import {Component} from 'angular2/core';
import {Router} from 'angular2/router';
@Component({
  selector: 'about',
  template: `
  <h2>About</h2>
  <button (click)="goBack()">Go Back</button>

  `,
  directives: [],
  inputs:[],
  outputs:[],
  pipes:[]
})

export class About {
  from;
  constructor(route:Router){
    this.router = route;
  }
  routerOnActivate(to, from) {
    this.from = from;
    console.log('About: ', to, from);
  }
  
  goBack() {
    console.log(this.from);
    this.router.navigateByInstruction(this.from);
  }
 }
```
compoents/tasks/task.component.js
```javascript
import {Component} from 'angular2/core';
import {RouteConfig, ROUTER_DIRECTIVES} from 'angular2/router';
import {TasksList} from './tasks-list.component';
@Component({
  selector: 'tasks',
  template: `
  <h2>Tasks</h2>
  <router-outlet></router-outlet>

  `,
  directives: [ROUTER_DIRECTIVES],
  inputs:[],
  outputs:[],
  pipes:[]
})
@RouteConfig([
  {path: '/list', component: TasksList, name: 'List', useAsDefault: true}

])
export class Tasks {
  routerOnActivate(to, from) {
    console.log('Tasks: ', to, from);
    this.render();
  }
  render() { console.log('render fired');}
 }
```
tasks/tasks-list.component.js
```javascript
import {Component} from 'angular2/core';
import {ROUTER_DIRECTIVES, Router} from 'angular2/router';
@Component({
  selector: 'tasks-list',
  template: `
  <h3>Task-List</h3>
  <button (click)="goBack()">Go Back</button>
  `,
  directives: [ROUTER_DIRECTIVES],
  inputs:[],
  outputs:[],
  pipes:[]
})

export class TasksList {
  task = {id : 1}

  from: any;

  constructor(router: Router) {
    this.router = router;
    console.log('constructor task-list');
  }

  routerOnActivate(to, from) {
    console.log('Task-List: ', to, from);
  }
  ngOnChanges(){
    console.log('list changes');
  }
  ngOnInit(){
    console.log('here');
  }

  goBack() {
    console.log(this.from);
    this.router.navigateByInstruction(this.from);
  }
 }
```
index.html
```html
<!DOCTYPE html>
<html>
  <head>
    <base href="/" />
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Ng2</title>
    <link rel="stylesheet" href="css/main.css">
  </head>
  <body>
    <route-test>Loading...</route-test>
  <script src="main.js"></script>
</body>
</html>

```

**Comment by taohd** [comment]
I am experiencing the same behaviour. My parent component calls the correct lifecycle hooks but any of the child components using navigate only the constructor is called. ngOnInit is called after a subsequent action in the child component

**Comment by zoechi** [comment]
It's working fine in this [Plunker](https://plnkr.co/edit/NTAye1?p=preview). 
Do you think it's a babel issue? 
With which browsers could you reproduce?
Can you create a Plunker where this can be reproduces?

**Comment by jcdalton2201** [comment]
Plunker is not a good reproduction of what is happing.  We tried a TS version also with the same results.  We are compile the code into one source file. IE, firefox, and chrome all are doing this.

**Comment by zoechi** [comment]
Are you using minified bundles? You'll need to provide exact steps how to reproduce otherwise it will be hard to find the cause.

**Comment by brandonroberts** [comment]
@jcdalton2201 you shouldn't be importing `angular2-polyfills` in your build. You should either include it as a separate script tag in your index.html, or don't import it and import `babel-polyfill`, `reflect-metadata`, and `zone.js` separately.

Here is a working plunker using babel as a transpiler: http://plnkr.co/edit/Gi8WsO?p=preview

**Comment by brandonroberts** [comment]
@jcdalton2201 here is an example branch reproducing your issue. In the bootstrap.ts, if you import `angular2-polyfills` instead of the separate imports, the ngOnInit isn't called. If you import the separate dependencies, it works as designed.

https://github.com/brandonroberts/angular2-browserify-starter/tree/angular-8012
https://github.com/brandonroberts/angular2-browserify-starter/blob/angular-8012/app/bootstrap.ts

**Comment by jcdalton2201** [comment]
@brandonroberts removing the polyfills and adding the others imports work for us.  I think this should be documented on the site a little better.  there are so many examples that will get you in this stuck state and there is not a good explanation on what the polyfills import is really doing.  Thank you for your quick response.

**Comment by Foxandxss** [comment]
@jcdalton2201 Sorry about that friend. We plan on releasing a webpack cookbook in angular.io and it will have the polyfills correctly loaded.

**Comment by taohd** [comment]
we are using navigateRoute to navigate to a Splash component which is a child of a parent component . Only the constructor is called when we use this. I will try and duplicate in a plunker

**Comment by janbaer** [comment]
@Foxandxss Thanks for trying to help me to find the problem!
@brandonroberts Thanks for the hint, but you'r using a different bundler than me and it's seems that each bundler brings it owns problems and solutions, even the transpiler is the same. I also tried to add the babel polyfill, but without any change. Maybe it would be helpful to get a info from the developers team, how it should work and which polyfills for which functions are really required. It's also interesting that the second call of the same route is working, but not the first call. So that means for me, that the required functions are polyfilled, but maybe not in the right order.

And about creating a plunkr, I think it's more easier to just clone the github repository and try it out in a real project, instead of wasting time with trying to make it reproducible in a plunkr, it's a completely different environment. And in my case the project is immediately running without any external dependencies, except the npm modules. Thanks for any help in advance!

**Comment by brandonroberts** [comment]
@janbaer I agree about different bundlers bringing different problems and solutions, but the overall issue is still the same. If you are not loading the `angular2-polyfills` via a script tag, then you need to import the separate scripts that make up the `angular2-polyfills`. Here are three in the required order:

`babel-polyfill` - This one could be `core-js`, `es6-shim`, etc. Just depends on what your preferred ES6 polyfill choice is. This provides support for native browser `Promise` as well as other features of ES6 that are not available in older browsers.
`reflect-metadata` - This is what Angular uses to store/read metadata about components that have been annotated with decorators
`zone.js` - Zone.js patches most of the async browser events such as the `Promise` mentioned above. This one needs to be last in the set. This is what allows Angular to determine if change detection needs to run instead of using the digest cycle from Angular 1.

The `angular2-polyfills.js` includes all three of these, and they need to be loaded before anything else in your application is loaded, which is why its recommended they be loaded via script tag and not included in your application bundle.

As far as plunker goes, its a two way street. Plunker and other similar sites already have templates set up for Angular 2 which make it easier for you to drop in some code and provide a minimal reproduction without replicating your environment. Its also easier for someone else to run that code without pulling down your repo, and installing npm modules.  Whether your provide a github repo, gist or a plunker, the more information you can share including snippets of code is always better.

**Comment by brandonroberts** [comment]
Here is another resource about bundling and polyfills: https://github.com/angular/angular/blob/master/modules/angular2/docs/bundles/overview.md#polyfills-and-external-dependencies

**Comment by Foxandxss** [comment]
Putting the polyfills as an entry (the file directly) in webpack and making sure it is the first thing loaded also works fine.

**Comment by janbaer** [comment]
Today I found out that the following combinations have exactly the same result.

- angular2-polyfills (alone) - via script tag or as import in webpack

- babel-polyfill
- zone.js/dist/zone

- core.js
- zone.js/dist/zone

- reflect-metadata
- zone.js/dist/zone
- (I also tried es6-shim and es6-promise, but it seems that Chrome Canary don't need this)

All of this combinations are running, but all with the same result. So that means, that my angular 2 environment is running, but still not with the router. The weird with this is, when some of the upper polyfills I get a lot of exactly error messages what is missing. But after I added all required polyfills, it's still not running, but without any error message. So please give me an advice how to tackle the problem... Thanks!

**Comment by janbaer** [comment]
I've an idea why the problem is not occurring on a not so modern browser like the Safari is (related to ES6) but in Chrome it's. It's maybe because the polyfill is not active on Chrome since the native implementation is used and something is different to how the polyfill is working. It's just an idea, maybe I'm wrong...

**Comment by brandonroberts** [comment]
@janbaer can you share some code or a repo? What does your index.html and bootstrap file look like? The polyfills are included but only used if needed. Your bootstrap should look something simliar to this with babel:

```js
import 'reflect-metadata';
import 'babel-polyfill';
import 'zone.js';
import {bootstrap}    from 'angular2/platform/browser';
import {App} from './components/app/app';
import {ROUTER_PROVIDERS} from 'angular2/router';

bootstrap(App, [ROUTER_PROVIDERS]);
```

**Comment by janbaer** [comment]
@Foxandxss Is a import not the same? How to add a file in a webpack.config directly as file? Thanks!

**Comment by Foxandxss** [comment]
I tried your solution with a proper polyfill management and it wasn't working for me, so I guess you have a problem elsewhere.

**Comment by janbaer** [comment]
@brandonroberts Of course, it's here: https://github.com/howcani-project/howcani Just clone it, npm install and then gulp and you can reproduce the problem. It would be great when you could help me! Thanks!

**Comment by brandonroberts** [comment]
@janbaer I figured out your issue. Your polyfill setup is fine. The issue is you are using the github api, which uses a `Promise` for returning data. Since you are importing the github api after the `zone.js` imports, the Promise is not being patched, and therefore is running outside the zone and is not being picked up by `zone.js` to trigger change detection.

If you import the github api before the zone.js imports in your `shim.js`, it works as expected.

File: https://github.com/howcani-project/howcani/blob/master/src/shim.js

Before:

```ts
import 'es6-shim';
import 'es6-promise';
import 'reflect-metadata';

import 'zone.js/dist/zone';
import 'zone.js/dist/long-stack-trace-zone';

import 'github-api'; // after zone.js
import 'jquery';
import 'moment';
```

After:

```ts
import 'es6-shim';
import 'es6-promise';
import 'reflect-metadata';
import 'github-api'; // before zone.js

import 'zone.js/dist/zone';
import 'zone.js/dist/long-stack-trace-zone';

import 'jquery';
import 'moment';
```

**Comment by janbaer** [comment]
You're right, it works now! Thank you very much!!!!!! And I don't believe that this was the reason, since this library is always working with callbacks and never returns me a promise. But you're right inside it's using a Promise and it's calling a polyfill before.

This simple problem has taken me a lot of time in the last days and I'm very thankful for your help!

**Comment by lohiarahul** [comment]
Hi,

I have these in my index.html
    
    <script src="node_modules/core-js/client/shim.min.js"></script>
    <script src="node_modules/zone.js/dist/zone.js"></script>
    <script src="node_modules/reflect-metadata/Reflect.js"></script>
    <script src="node_modules/systemjs/dist/system.src.js"></script>

and this inside my container-component

import { Component } from '@angular/core';
import {MyComponent1} from './components/mycomponent1.component';
import {MyComponent2} from './components/mycomponent2.component';
import { ROUTER_DIRECTIVES } from '@angular/router';

The application routes between component1 and component2 inside the container component. The first component created a silverlight object on 'on-init', but when I navigate to component2 and back to component1, only the constructor event fires.

![image](https://cloud.githubusercontent.com/assets/2647136/16518387/1b0febf4-3fa0-11e6-8f14-f92f62703235.png)

Also, look at repo for sample code:
https://github.com/lohiarahul/Angular2-Silverlight-Starter

**Comment by max0x7ba** [comment]
Same issue here as @lohiarahul with rc4.

**Comment by brandonroberts** [comment]
@max0x7ba you should open a new issue with a plunker on the latest release reproducing this issue. There isn't a different in component lifecycles whether you use the hash or path strategy.

**Comment by max0x7ba** [comment]
@brandonroberts 

I am not using any hash or path strategies explicitly.

My issue is that OnInit is not called when the URL is directly typed into the address bar but works fine if an anchor tag is used.

**Comment by brandonroberts** [comment]
@max0x7ba ok. This usually isn't a routing issue though as has something to do with your setup. Are you including system polyfills in your `index.html` file?

**Comment by max0x7ba** [comment]
@brandonroberts 

Just upgraded from rc4 to rc6. Now it calls onNgInit, which is good. But something goes wrong later on, as if other lifetime hooks are not called, so that a `@ViewChildren` property of my component never gets initialized. It works as expected if an anchor tag is used though.

Another thing I just noticed is that I experience this issue when using `localhost` in the URL. When I use `127.0.0.1` this issue is gone, everything works as expected.

**Comment by brandonroberts** [comment]
@max0x7ba a reproduction in a plunker or repo we can see would help  alot more.

**Comment by max0x7ba** [comment]
@brandonroberts That would require me hosting plunker on my local machine, would it not?

It turns out that `localhost` resolves to an IPv6 address, whereas `127.0.0.1` resolves to IPv4. 

Not sure if Angular2 supports IPv6.

**Comment by zoechi** [comment]
@max0x7ba Angular doesn't need to support IPvX. Only the browser needs to support it.

**Comment by tdinar** [comment]
I am experiencing an issue with Angular 2.40 and router navigation when I use the router.navigate(/root/child) method. I am using webpack for packaging my app based on the tutorial [https://angular.io/guide/webpack.]. my setup is utilizing modules and modules routing to get to children's component (this is not an issue when links are used to navigate). 

the issue in detail:
`const dashboardRoutes: Routes = [
     { path: '', redirectTo: 'dashboard', pathMatch: 'full' },
    {path: 'dashboard', component: ParentrComponent , canActivate: [ParentResolverService],
    children: [
       {path: '', redirectTo: 'model', pathMatch: 'full'},

      { path: 'child', component: ChildComponent ,canActivate: [ChildResolverService]},

];`



The data arriving from source (a promise) is flowing to children through a store's BehaviouralSubjects.  through the AuthGuards.  I can see the data arriving inside the AuthGuards, and it is as I expect. however, my subscription inside a child component, which is placed inside ngAfterContentChecked will not fire, or more precisely, all lifecycle hooks, except constructor, are not firing.  if I place the subscription inside the constructor of a child, it fires but the componen's change detection misses the subscription and any data-flow at all. If I manually run the CD inside a constructor and within the subscription, I get an error, that the component properties do not exist on a null!.  long-live delay operator of rxjs, but I am hoping for more deterministic approach, data should be there when I render. 

expected behavior:
I expect lifecycle events to fire any time a component is inserted into the dome.
