### ISSUE TITLE
No easy way of accessing Control instance in form template

### ISSUE THREAD

**Issue by PascalPrecht** [angular/angular#8037]
Let's say I have a `ControlGroup` like this (I know I could use `FormBuilder` but that's not the point here):

```
ngOnInit() {
  this.myForm = new ControlGroup({
    username: new Control(),
    password: new Control()
  });
}
```

The dedicated template would look like this:

```
<form [ngFormModel]="myForm">
  <input ngControl="username">
  <input ngControl="password">
</form>
```

Nothing special here, I bind the form model `myForm` to the `ngForm` directive and use `ngControl` to associate form controls with the model controls.

However, it gets interesting if I want to add some CSS classes to the inputs based on a controls validity state:

```
<form [ngFormModel]="myForm">
  <input ngControl="username" [ngClass="{ invalid: !username.valid}" #username="ngForm">
  <input ngControl="password">
</form>
```

This gives me:

```
EXCEPTION: Expression '{'invalid': !username.valid } in FooComponent@12:14' has changed after it was checked. Previous value: 'true'. Current value: 'false' in [{'invalid': !username.valid} in FooComponent@12:14]
```

This is obviously a change detection error and in fact, I use `#username="ngForm"` which is not the `Control` anyways, it's the `NgControlName` instance. This might be why we have a change here after change detection has been performed.

I could probably use something like `myForm[username]` in my expressions to get hold of the control instance, but this seems cumbersome to me. Using template-driven forms, this is a not a problem at all.

`[ngFormControl]` also doesn't help here as this is a directive for a different use case (forms with a single input).

My current workaround is to make `username` and `password` a property of the component, and assign them instances of `Control` directive, so they don't change their value during change detection:

```
@Component()
class FooComponent {

  ngOnInit() {
    this.username = new Control();
    
    this.myForm = new ControlGroup({
      username: this.username,
      password: new Control()
    });
  }
}
```

**Comment by zoechi** [comment]
dup of #6041, see also #8139

**Comment by kara** [comment]
This issue was originally filed in April before the new forms module came out.  Looking over the sample code, it seems this issue is now obsolete.

Reactive form directives are no longer exported because doing so mixes the two paradigms in a way that is confusing, and makes it easy to cause change detection errors like the one from the original post. Exporting is really a relic of template-driven forms as it is reliant on and limited by change detection of the template.  Reactive forms should be driven by the imperative code, not by the template, which allows it to be free of the template's limitations. So we don't want to encourage the use of template-driven paradigms that can get you into trouble.

Using a reactive paradigm, here are a few other reasonable ways to get access to a form control without using directive exports.

1) Use the `find()` method

Something like:

`form.find('username').valid`

Or if it's nested: 

`form.find('person/username').valid`

Example: https://plnkr.co/edit/fwXcCL0t9h5v4GYBOcD3?p=preview

2)  Save a reference to the control on the class 

This was Pascal's original solution. If you want a shortcut to a control, this is a good way to do it.

3) If all you want to do is add a class based on validity state, using the "ng-valid", "ng-invalid", etc classes that are built in already would be suggested.

I'm closing this for now, as there are a few ways to access form controls from the template already. If anyone has ideas for what a shorter syntax then `form.find('fieldName')` might look like, happy to discuss.
