### ISSUE TITLE
Should we stop minifying benchmark dart2js code ?

### ISSUE THREAD

**Issue by vicb** [angular/angular#805]
Which gives unhelpful [error messages](https://travis-ci.org/angular/angular/jobs/52190590#L1492):

```
    message: 'http://localhost:8002/examples/src/hello_world/index_static.dart.js 1181:3 Uncaught Cannot find reflection information on li',
    timestamp: 1424905916331,
    type: '' } ]
```
Here we have no clue what "li" is

Without [minifying](https://travis-ci.org/angular/angular/jobs/52237178#L1518)

```
    message: 'http://localhost:8002/benchmarks/src/naive_infinite_scroll/index.dart.js 2436:15 Uncaught Cannot find reflection information on NativeShadowDomStrategy',
    timestamp: 1424936906409,
    type: '' } ]
```

**Comment by tbosch** [comment]
Overall, we should do the same on JS and Dart land: minify both or not minify both.

Eventually, I think we do want to run benchmarks against minified code as this could change performance characteristics (need to measure though).

Anyways, we should set up source maps for dart2js correctly. Even if we don't minify we actually would like to have the real dart source code line, not just a hint.

Could you change your PR to do that instead of turning off minification?

**Comment by tbosch** [comment]
Actually, even if we have source maps, they won't be applied to stack traces read out via webdriver/protractor. So we should do the following:

1. create source maps when running dart2js
2. translate stacktraces using the source maps in our e2e tests

We print the errors [here](https://github.com/angular/angular/blob/master/modules/angular2/e2e_test/test_util.es6#L24) and should use the translation logic from [here](https://github.com/angular/angular/blob/master/modules/examples/e2e_test/sourcemap/sourcemap_spec.es6)

**Comment by vicb** [comment]
@tbosch I guess you have much more experience with stack trace than I do, would you mind looking at this ?

**Comment by mhevery** [comment]
This is obsolete, and no longer relevant / actionable. To keep our issues clean, we are aggressively closing them.
