### ISSUE TITLE
Terminate the compilation early for style elements

### ISSUE THREAD

**Issue by vicb** [angular/angular#808]
Currently when the `ResolveCss` step encounter a style element, it set `currentElement.ignoreBindings` to true to "disable" further steps.

What about terminating the compile process earlier in such a case - it would speed up compilation.

I see two ways to do this:
- returning a value from `step.process()`,
- add a `terminate()` method in `CompileControl`:

```
export class CompileControl {
  _exit: boolean;

  internalProcess(results, startStepIndex, parent:CompileElement, current:CompileElement) {
    this._exit = false;
    for (var i=startStepIndex; i<this._steps.length && !this._exit; i++) {
      //...
    }
  }

  terminate() {
    this._exit = true;
  }
}
```

@tbosch, what do you think ?

**Comment by tbosch** [comment]
Let's add it to the `CompileControl` as `ignoreElement()`.
We should also move `CompileElement.compileChildren` into a method in `CompileControl` as `ignoreChildren()`.

And I just found that the `ResolveCss` step waits for a promise to replace the element text. This should also get parts of the `CompileControl` via a method `CompileControl.waitFor(promise)`. Otherwise the compiler could return a ProtoView where styles are not yet resolved as the promise might be waiting.

So all of these 3 cases should go into `CompileControl` and not in local fields in `CompileElement`.

**Comment by vicb** [comment]
Tobias, 
Thanks for the explanations.

About ResolveCss, it can return a Promise when it has to inline (hence fetch via xhr) some CSS. However we don't want to wait for it to be ready but rather parallelize nested templates download.

How this is done is that the style promises are pushed to ProtoView.stylePromises. When they're are such promises, the compiler will delay the protoview resolution until those are resolved.

We should also think about ignore children: the step that shims the Dom (by adding an attribute to each element) should still run.
