### ISSUE TITLE
Lifecycle Events not called on a dynamically loaded component

### ISSUE THREAD

**Issue by taohd** [angular/angular#8113]
components loaded with the dynamic component loader are not having their lifecycle events called. this was a attempted workaround where these same events were not called using a route. both of these situations involve angular 2 running inside of an electron application. we need the lifecycle hooks, especially ngOnInit. here is a plunker which reproduces the dcl behaviour

http://plnkr.co/edit/XXLWqxwywGoFZaX1w99I?p=preview

**Comment by ericmartinezr** [comment]
For a long time we thought loadAsRoot was broken, until we were told it wasn't and its behavior is by design (see https://github.com/angular/angular/issues/6223#issuecomment-193908465) what you really should be using is loadNextToLocation or loadIntoLocation. If you still want to use it you will have to wire up everything (see https://github.com/angular/angular/issues/6223#issuecomment-193895253) which will be reinventing the wheel and do manually what loadNextTo* and loadInto* do for you,

Changing it to use one of the two mentioned above will make it work correctly.

**Comment by taohd** [comment]
Eric,
  thank you for pointing me towards  loadNextTo and loadInto. They both worked as expected and now we can tackle the next hurdle. 

Cheers
