### ISSUE TITLE
bug(forms) Async-Validators not triggered for ControlGroup as long as Sync-Errors persist

### ISSUE THREAD

**Issue by choeller** [angular/angular#8118]
**Steps to reproduce and a minimal demo of the problem**

Having a dependent validation in the form "If state is not "BACKLOG" assignee is required" using asyncValidators is not triggering as long as other Validations-Errors (e.g. required on another field) persist.

See the following plnkr:

http://plnkr.co/edit/8bmXDkmKiILUtKkRKhaf?p=preview

When your first action is to choose the state, the asncValidator will not be executed! Only after making the title field valid, by typing something in the title-field  async-Validation works. 

**Current behavior**

Async-Validations only get triggered, when no invalid sync-validations are present.

**Expected/desired behavior**

Async-Validations should be triggered independent of other validation errors.

**Other information**

**Comment by pkozlowski-opensource** [comment]
This is by design and we've got a test to prove it: https://github.com/angular/angular/blob/e42a0570484d1be2f0f8b91b3ea4ffffde522d09/modules/%40angular/forms/test/form_control_spec.ts#L177-L187

I guess that the reasoning is that async validation is "expensive" and as such should run after sync validators.

> Async-Validations should be triggered independent of other validation errors.

Why? If sync validators mark a filed as invalid there is no point in checking with async validators. It was already market as invalid.

Do you have a specific use-case where the current design causes problems?

**Comment by kara** [comment]
Yep, this is by design.
