### ISSUE TITLE
Error when calling renderer.setElementStyle, "TypeError: i is undefined"

### ISSUE THREAD

**Issue by scrapcupcake** [angular/angular#8137]
**Steps to reproduce and a minimal demo of the problem**
[RendererBugExample.zip](https://github.com/angular/angular/files/226513/RendererBugExample.zip)

_What steps should we try in your demo to see the problem?_
Launch live-server or similar, navigate to index. With the window focused, press any key

**Current behavior**
EXCEPTION: Error during evaluation of "document:keyup" angular2.min.js:17:25209

ORIGINAL EXCEPTION: TypeError: i is undefined
With a lengthy additional exception that would probably mostly be spam to paste here.

**Expected/desired behavior**
Cursor is moved to absolute left 100px

**Other information**
I was following the demo found here: http://juristr.com/blog/2016/01/learning-ng2-dynamic-styles/ in order to construct a simple demo of moving a square cursor around the screen; There may well be other, better ways of doing this, and I'm all ears, but regardless of resolving that issue, this behavior seemed like it needed reporting as a bug.

**Comment by zoechi** [comment]
A plunker would be great that demonstrates the issue.

**Comment by scrapcupcake** [comment]
Sorry, I have no learned how to use plunkr or similar for anything more complex than hello world yet.

**Comment by scrapcupcake** [comment]
I think I figured it out:
http://plnkr.co/edit/J57tSmVHai9KpsPQba25

**Comment by ericmartinezr** [comment]
The error you're seeing `Cannot read property 'boundElements' of undefined` is because you're passing a `nativeElement` to the renderer and you're using beta.0. Renderer expects a nativeElement since beta.1. So you're making 3 mistakes : passing a nativeElement to the Renderer, you're using a really old beta, and you're asking for help where you're not supposed to. You'll get help faster if you follow the [contributing guides](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question)

**Comment by scrapcupcake** [comment]
Thank you for clarifying on the first two points. I find the third to be rather missing my own additional info.  I have read the contribution guidelines and thought I was following them.  This is my first time submitting an issue, I thought I had found a bug. I shall not be bothering to contribute further, given the warm reception my mistaken attempt received.
