### ISSUE TITLE
Directly accessing route with HTTP GET parameters, Angular2 does not preserved parameters

### ISSUE THREAD

**Issue by tom10271** [angular/angular#8182]
Given the following route:

`project.com?param=123`

Angular 2 will remove all GET query string parameters and proceed `project.com` only.

Exactly what this SO question have, but with Angular 2 beta12

[http://stackoverflow.com/questions/32816388/how-to-keep-query-string-parameters-in-url-when-accessing-a-route-of-an-angular](http://stackoverflow.com/questions/32816388/how-to-keep-query-string-parameters-in-url-when-accessing-a-route-of-an-angular)

**Comment by zoechi** [comment]
See also http://stackoverflow.com/questions/36784822/how-to-get-get-paramater-in-angular2/36785222?noredirect=1#comment61149325_36785222 they are kept if the URL matches a route. 
Query parameters are only supported for root routes, otherwise they are maintained as matrix parameters (`;` instead of `?`)
Please provide a full example (Plunker) if you can't fix it with this information.
