### ISSUE TITLE
Angular 2 DOA

### ISSUE THREAD

**Issue by adrianme8** [angular/angular#8208]
Angular 2 seems pretty much dead on arrival. It is in development for years. In Beta for months. Still third-party support is virtually non-existent (angular ui, angular material, etc.) that would allow to build any kind of reasonable application. 

Not sure how long you expect the community to look at this and hold its breath. Or how any kind of company investing in a Angular frontend stack is supposed to continue to do so.

You should consider dropping it and instead incrementally approach 2.x features in the 1.x branch without breaking backward-compatiblity.

**Comment by pkozlowski-opensource** [comment]
Interesting opinion, but discussion of this type don't belong to GitHub issues really, see:  https://github.com/angular/angular/blob/master/CONTRIBUTING.md

**Comment by shlomiassaf** [comment]
Lol, this guy opened his account today :)

**Comment by adrianme8** [comment]
maybe it would be time to look around of what is happening and take the issue seriously.

**Comment by shlomiassaf** [comment]
well my friend, renting will do you no good... 
If you want to speed up the process start contributing.

Being negative won't help you reach people

**Comment by adrianme8** [comment]
well, unfortunately, there are already thousands of contributions. But at some point, some funny guys decided all of these is not worth a dime and it is more fun to start from scratch and put a Angular version 2.0 sicker onto it instead of moving into the right direction with incremental updates.  But we do not have to argue about that, not worth my time either.

On the more constructive side:
It would be very helpful to have roadmaps and much more importantly get some ui libraries working. I guess, UI Bootstrap, UI Grid and Angular Material are quite essiential. The former two have no progress. Last comment I have seen on Bootstrap is that they are waiting for some further Angular 2.0 features. UI Grid has no resources. Angular Material is in the early alpha stages. Given that it is supposed to be backed by Google, that is quite surprising. There is a second Material implementation by JetBrains. If Google is no longer willing to put any effort in here, that should be made clear and this secondary implementation can get the necessary recognition and contributions.

I would love to start using Angular 2.0. But so far it does not seem to possible (in a reasonable way). But I gladly get proven otherwise. Then I also becomes possible to do contributions again.

**Comment by intellix** [comment]
don't mean to feed the troll but this UI library is fairly beefy :) https://github.com/valor-software/ng2-bootstrap

**Comment by PascalPrecht** [comment]
@adrianme8 I think you're missing a couple of points here.

> But at some point, some funny guys decided all of these is not worth a dime and it is more fun to start from scratch and put a Angular version 2.0 sicker onto it instead of moving into the right direction with incremental updates

This has been clarified several times on several channels already. The way A1 was build doesn't allow to get the benefits, features and performance A2 needs to bring to the table. It's not that the team puts now about ~3 years of development into a new major release simply for fun. However, if you do think it's possible (even though many people have put a lot of energy and thoughts into this already), feel free to contribute to the Angular 1 code base to make it incrementally better. The community welcomes any help.

> Given that it is supposed to be backed by Google, that is quite surprising.

Also wrong. UI Bootstrap and UI Grid are *entirely* community-driven, baked by people who spend their spare time working on these projects without complaining about a code base that is moving super fast. Again, if you care about these projects, how about helping out?

> If Google is no longer willing to put any effort in here, that should be made clear and this secondary implementation can get the necessary recognition and contributions.

There's a team at Google that works pretty much full time on Angular Material 2 and they are releasing new version very regularly.

> I would love to start using Angular 2.0. But so far it does not seem to possible (in a reasonable way). But I gladly get proven otherwise. Then I also becomes possible to do contributions again.

I think it's time to realise and appreciate that we as a community and consumer of this framework don't have to pay a single penny for all the hard work that the team is doing for us. Keep in mind that you get it all for free and that they do a ton of research and work that we don't have to do, to build a super awesome future-proof framework that everyone out there is allowed to use.

So again, instead of complaining, be grateful and help making the thing better.

**Comment by adrianme8** [comment]
I hope you understand that is no personal ranting. I'm involved in various projects and get asked the same questions.

Regarding the Google backing I was writting about Angular Material. It is clear that UI Bootstrap and Grid are community driven. And those projects are great. But it is also clear that a tremendous amount of work awaits them to do this migration. But we are not there yet. The UI bootstrap status is "waiting for further Angular 2 features" (see https://github.com/angular-ui/bootstrap/issues/3434). After three years of Angular 2 development that is really not a good thing.

Have you had a chance to look at the github statistics of Angular material? As far as I can tell there is no "Google team". There are two Google committers. One of them was fairly quiet the last few months. The other started with more frequent commits for the last couple of weeks. It will take quite some time at this pace. That is why I'm asking whether the Jetbrains implementation should be the recommended/official implementation. Because for sure the community has not the resources to implement the same thing twice. Would be nice if people chat a bit and join forces. The same questions were also asked in the Angular Material forum. But they were only met with silence.

So if Angular/Google likes to do this Angular 2 endeavor, they should get their act together, Clearly specify a roadmap. Make sure the communicty works in the same direction. And avoid redunant implementations. Otherwise, unfornately, in such a fragmented state it is just not worth any further contributions.

**Comment by otodockal** [comment]
@adrianme8 check out also ng-bootstrap project https://github.com/ng-bootstrap/core

**Comment by adrianme8** [comment]
one of my points, two project doing the same thing... why?

**Comment by zoechi** [comment]
@adrianme8 Why not? That's how open source works. It isn't Googles responsibility to ensure every contributor works on the same project.

**Comment by adrianme8** [comment]
I don't mind some competition either, but if it gets to a state where the same thing gets done multiple times, people complain about lack of resources and none of the projects get into a stable state, it is not IMHO.

**Comment by adrianme8** [comment]
more things get done if people work together...

**Comment by adrianme8** [comment]
the fork button on github can alsway be pressed later if you don't like the result.

**Comment by adrianme8** [comment]
based on ng-conf, Angular Material 2 availablity is expected to be 2017. So no material development for another year with Angular 2...

If maybe still somebody worries a bit about this, special thanks can be sent to those guys: https://angular.io/about/

**Comment by otodockal** [comment]
now you can use 12 components https://github.com/angular/material2/tree/master/src/components

or it's easy, send a pull request and stop complaining...

**Comment by cebor** [comment]
@adrianme8 its no problem to use https://getmdl.io/ in angular2

**Comment by shlomiassaf** [comment]
Where did you get that date?

Material 2 will be ready this year.

It might not have the finest animation or all extra features such as maps, tables etc.. But it will be ready and all extra will come free as you move on.

**Comment by adrianme8** [comment]
I watched ng-conf. The first day there was an Angular Material session. At the very end it was discussed when it was ready. The audience got a shy "Beta in 2016". Which should put the final/stable version in 10 to 12 months from now I would guess (there is no clear roadmap on the Material page and there seems to be currently only one main contributor). 

ng-conf is available here https://www.youtube.com/watch?v=mAjjI35RcUE. The statement is at 7:22.

BTW: it is also worth watching 6:40

**Comment by shlomiassaf** [comment]
@adrianme8 I see you don't follow Google projects to much... Every thing is beta longer then it should.

If you saw ng conf you probably heared that Adwords is using ng2 since beta, and in production! That's a lot of money on a beta version...

You won't hear a google official say that but material 2 in beta will be production ready, believe that.

Maybe animation won't be perfect but it will be ready.

**Comment by adrianme8** [comment]
Doing something like that might be ok if you are a Google project and have the Angular team right next to you fixing all your issues. For any kind of normal / production-grade application that you are not allowed to fuck up, devs hopefully never imagine doing something like this. 

I consider Angular Material (or bootstrap) to be one of the fundamental must haves in order for the community start building things on top of that and application start using it. So a Beta should have be ready now, not in 6-8 months time. All other stuff, CLI, server-side rendering, etc. could wait and is not really that important for an initial release.

**Comment by shlomiassaf** [comment]
Well, ok.

Here's what I suggest, don't build with angular.
You won't risk anything but staying behind, and that's ok.

This is the world if front end, you have to take risks and frankly I've taken mine with angular and it worked out fine, I also put typescript into a project I was leading back when it was 0.7 and quite anonymous, it worked out great...

In the world of front end you have to evaluate and bet on something, if it's rough for you that's fine, let others lead.

**Comment by adrianme8** [comment]
maybe that is half way good conclusion. Just not use it any more. A lot of trust has been put into the ecosystem. Now since three years they do not manage to get of the grounds if all the supposed new great stuff and trashed all previous contributions along the way. 

What I don't agree is the "bet on something" part, because it is just not usable anymore and will not be for quite some time. Everything done or to be done in 1.x can be thrown away at some point and is just wasted effort.

**Comment by d4nc3r** [comment]
I'd disagree that ng2 isn't stable or usable - this is a great article about a company starting a medium sized project using ng2 alpha, and they are successfully in Prod after 6 months development and on a beta version: http://m12.io/blog/we-launched-angular-2-project

Maybe that'll help put some things into perspective for you.  It helped our company make the decision to work through a major rewrite in ng2, and even despite the major changes inside router (which is the only thing throwing us for a loop at the moment), I still believe we've made the right choice.

**Comment by gonzofish** [comment]
@adrianme8 if you think Angular 2 is so bad, why keep commenting on here? Go use React or Angular 1 or Ember or Aurelia or anything. Go have fun making web development instead of being negative!

Unless you're just trolling, in which case, I'm wasting my words.

**Comment by shlomiassaf** [comment]
@adrianme8 so don't use it, bet on you're future.
If angular won't make it then you made the right call.

I think this can end the discussion, make your bet.

**Comment by cebor** [comment]
Please lock this issue!

**Comment by damiandennis** [comment]
Angular2 is awesome, incredibly flexible and has not no downsides besides the router. The problem is that its fresh and only those with good js skills can use it right now.

**Comment by adrianme8** [comment]
from a technical perspective Angular2 surely is good. I don't think good js skills are necessary. But frameworks pop in and out of existence on a weekly basis. What makes them useful is the community and contributions around them. Without them one reinvents a lot of things and loses a lot of time. Here Angular2 starts from scratch. It hijacked the Angular name, which helps a bit. But probably it is not that great when it comes to documentation (for the years to come it will be a bit of a mess when searching for angular problems and components and to quickly differentiate between 1 and 2). And as pointed out, I don't have the impression that it currently has the pace it should have. I consider Angular Material to be quite pivotal for this, since it provides the necessary UI components to build decent apps. The classical chicken/egg problem, people don't start using it before there is a decent amount of support/components, which in turn means people don't start contributing. But here Google resp. the Angular team really takes its time (again...). So you can either bash my comments here for putting a critical spin on all this, or put some pressure on Google to finish their stuff a bit quicker. Maybe repriorize some other stuff. Over the last few months, there is not much activity on Material. Usually a single developer. So come on, they can do better than that. They might spare some devs flogging advertisement.

**Comment by gonzofish** [comment]
I'm not sure what you're talking about with Material, but there's commits every day to Material 2 (https://github.com/angular/material2/commits/master) and Material 1 (https://github.com/angular/material/commits/master)...these people are working their butts off to provide us something for free.

**Comment by ssougnez** [comment]
I think that calling Angular 2 "DOA" just because it takes its time to be released is a bit of a non sense for me. Before starting to work with Angular 1.x/2, I worked a lot with Microsoft products and I noticed that, at that time (because it starts to improve), they were working in an opposite way than Google: they were releasing their product/framework way too early and therefore, it was either buggy, or incomplete (or both) and this was quite frustrating (e.g. Silverlight... WPF...).

Concerning Angular 2, that's true, it takes time but at least you can play with the alpha/beta/rc version which is quite a great advantage. Personally, I really prefer a product that takes some time to be released but is complete and not to buggy to a product released too early and almost not usable. We are not doing fan service but quality.

For me, the only thing that frustrates me a bit with Angular 2 is all the new things it brings. Let's be clear, it does not frustrate me because of all these new concept but because we have to learn them all in once to be able to use Angular 2 correctly. You have to understand the loading module system (commonjs, systemjs, etc...), you have to understand how node works to be able to use the "package.json" file and everything that goes with it. You need to learn TypeScript (even though you can use JavaScript but TypeScript seems to be the way to go), therefore, you have to get all these typings stuff, you have to learn about Observable (=> RxJS), etc... It's a good thing that Angular 2 is using all these new technologies, but if you never used one of these before, you have to learn them in once and that's quite discouraging sometimes, especially when the documentation on that matter is pretty rare.

However, despites this drawback (for me, I repeat), I think that bashing Angular2 just because it waits to be mature before being released is not very logical ;-)
