### ISSUE TITLE
ControlGroup.value is not updated when a control is added via addControl()

### ISSUE THREAD

**Issue by bitsmag** [angular/angular#8252]
If a `Control` is added to a `ControlGroup` via `addControl()` the **current behavior** is that the value of the added `Control` is not accessible via `ControlGroup.value`. However, the value is accessible via `ControlGroup.controls['addedControl].value`. 

The **expected behavior** is that the value is also accessible via `ControlGroups.value`. 

[Here is a demo of the issue](https://plnkr.co/edit/UjTY5tvAa8qe73WReMms?p=preview)

**Comment by bitsmag** [comment]
Ohh ... that works asynchronous. Is that the way it's supposed to be?

**Comment by KannanMuruganmony** [comment]
@bitsmag is this working for you? I'm facing the same issue. Could you let me know what was the fix?

**Comment by bitsmag** [comment]
The value property is set asynchronously. You can access the property after it is set using a timeout like so: `setTimeout(() => { foo = form.value }, 0);`.

[Here](https://plnkr.co/edit/ZO7V6NRPtTJlfL9V40bb?p=preview) is the updated plunker. 

If you wonder why this works, [this talk](https://www.youtube.com/watch?v=8aGhZQkoFbQ) is amazing!

**Comment by kara** [comment]
@bitsmag   In the old API, you had to call `updateValueAndValidity()` to re-serialize the values if you made changes to the control list (e.g. add or removed a control).  If you're curious, see plunker [here](https://plnkr.co/edit/VYRPEfkJLK2lvnV8riE3?p=preview).  In your case, this method happened to be called as part of another process later, which is why it worked to wait next tick.

As of RC.2, the `updateValueAndValidity()` call now happens automatically when you change the control list, so calling `addControl` should be sufficient on its own. Closing as resolved!
