### ISSUE TITLE
[beta.16] how to get parent injector & routeParams in beta16?

### ISSUE THREAD

**Issue by naivefun** [angular/angular#8267]
This code used to work:
```
constructor(private injector:Injector) {
  let params = this.injector.parent.parent.get(RouteParams);
  let id = params.get('objectId');
}
```
Now the `Injector` interface has been changed by removing parent property. How can I access parent route params in beta.16? Thanks

**Comment by CaptainCodeman** [comment]
Does `ReflectiveInjector` work?

**Comment by naivefun** [comment]
@CaptainCodeman 
I tried to inject `ReflectiveInjector`, but exception of no provider was thrown.
![screenshot 2016-04-27 08 49 27](https://cloud.githubusercontent.com/assets/10683378/14838561/1b890ca6-0c55-11e6-9282-ba7c2cf5eb62.png)

**Comment by CaptainCodeman** [comment]
Sorry, they just renamed the injector, I thought that might work.

I'd recommend using a service to stash and access parent information as you often you want to resolve some data from a URL id and that provides the perfect place to do it. Accessing RouteParams in the constructor is generally bad practice IMO because it won't always reflect changes (if a routed component uses CanReuse) so components can be a bit 'brittle'. I think it's better to handle the routerOnActivate and routerOnChanges methods instead and the instructions to get params (may not help with parent params though, I can't remember if the instruction has the ancestors in it). It allows you to re-use the same pattern and approach though.

**Comment by naivefun** [comment]
@CaptainCodeman 
First I really cannot understand why keeping it so hard to track path variables, or parent variables. 

However could you deliberate a bit about routerOnChanges and how can I track route params for a url like `/path/:p1/:p2/:p3`? The document is not there yet ...

Thanks.

**Comment by naivefun** [comment]
Btw I could extract param from Router's instruction recursively, but it's too tricky and could break any time soon. So I keep it as my last option.

**Comment by CaptainCodeman** [comment]
Yeah, there are some gaps in the API when it comes to ease of use especially when it comes to parent -> child communication. Who knows, the **new** *new* (alt) router may improve on some things.

I got my method names a bit mixed up, it's OnChanges for regular component inputs and OnReuse for routed component inputs - there's nothing like being consistent (and this is nothing like). So the method you need is https://angular.io/docs/ts/latest/api/router/OnReuse-interface.html
You also need to handle OnActivate as well of course for the first-time settings.

**Comment by naivefun** [comment]
@CaptainCodeman 
Thanks.

I'm catching parameters and saved it to app's state.

```
routerOnActivate(next:ComponentInstruction, prev:ComponentInstruction) {
    let params = next.params;
    this.state.set('teamId', params['teamId']);
}
```
Seems it's getting more complicated since I need track the changes if I use onReuse = true.

**Comment by CaptainCodeman** [comment]
I normally have CanReuse = true (because otherwise the screen flickers when params change) and then pass the instruction from routerOnActivate and routerOnReuse to the same function to process because typically what you want to happen is the same - load something based on the URL parameter(s) whether it's the first time being loaded or the 10th time.

**Comment by naivefun** [comment]
@CaptainCodeman 
Yes after a while I'm used to capture parameters in routerOnxxx interface. Actually it feels much natural already. Indeed the constructor shall not be used for this purpose but I found it quite popular in the answers on stackoverflow & github issues. That was where I got the original solution. 🔨

**Comment by tbosch** [comment]
you can do this:
```
constructor(@SkipSelf parentInjector: Injector) { ... }
```

**Comment by ctrl-brk** [comment]
So, after all this could you please post how your code looks now instead of original

```
constructor(private injector:Injector) {
  let params = this.injector.parent.parent.get(RouteParams);
  let id = params.get('objectId');
}
```

Thanks!

**Comment by naivefun** [comment]
@ctrl-brk 
In your root component, you can capture params by:
```
  routerOnActivate(next:ComponentInstruction, prev:ComponentInstruction) {
    let params = next.params;
    let paramValue = params['paramName'];
    // save it to your app state
    this.state.set('paramName', paramValue);
  }
```
then on your sub-routes, use `this.state.get('paramName')` to access it. Because parent route is created ahead of sub-routes, the state should always hold the `paramName` value.

**Comment by ctrl-brk** [comment]
Does that mean that I have to handle routerOnActivate in the every single component on the path?
So, there's no more direct way to get your grand-grand... parent parameters?
How does this 'state' object play with page refresh?

**Comment by zoechi** [comment]
@ctrl-brk you can wait for the new router where params will be global (AFAIK)
