### ISSUE TITLE
Codemod angular 1.x to 2.x

### ISSUE THREAD

**Issue by sibelius** [angular/angular#8284]
There is a tool called [jscodeshift](https://github.com/facebook/jscodeshift) that does AST-to-AST transforms for javascript.

I wonder if it is possible to create a [Codemod](https://medium.com/@cpojer/effective-javascript-codemods-5a6686bb46fb#.x2sf3ofkh) to migrate angular 1.x code to angular 2.x

I think that there are a huge amount of projects using angular 1.x right now, so a Codemod would provide a easy path to angular 2.x

**Comment by pkozlowski-opensource** [comment]
This would a great tool indeed. Not sure if we've got enough free cycles to do this as part of the core effort. But it sounds like a great community effort. Would be happy to assist people wanting to do a stab at this, although I wouldn't expect it to be trivial due to semantic differences between ng 1 and 2. ngUpgrade path might be a more practical one.
