### ISSUE TITLE
angular_1_router: return rejected promise in $routerOnActivate should cancel the navigation like $canActivate does?

### ISSUE THREAD

**Issue by Mischi** [angular/angular#8293]
Hi, 

i have a `dataService` which loads some data via $http. If the `dataService` returns a fulfilled promise, i want the navigation to happen and the loaded data within my component's controller. If the `dataService` returns a rejected promise, i want to cancel the navigation.

**Current behavior**
Currently, $routerOnActivate can only [delay](https://github.com/angular/angular/pull/7777) the navigation until the promise settles but can not be canceled like $canActivate. I can use the $canActivate hook but how would i pass the loaded data to the controller. ngRoute's $resolve could be used to inject loaded data into the controller. Is there a similiar way in ngComponentRouter's $canActivate?

**Expected/desired behavior**
I would like to cancel the navigation from within $routerOnActivate. Is that the desired behaviour and the current limitation a bug? How is this handled in angular2?

Alternatively i would like to pass some data from the $canActivate hook to the controller instance.

**Steps to reproduce and a minimal demo of the problem**
https://embed.plnkr.co/N1W4iLIsGol5FdRy26Zv/

A small demo which tries to demonstrate the problem.

What do you think @petebacondarwin, @btford  and @brandonroberts?

CC'ing @davidreher

**Comment by mpevec** [comment]
Hi, I also have the same problem, did you find any solution ?

**Comment by davidreher** [comment]
not yet ... we are not quite sure, why the angular2router is deprecated and what changes are to be expected. But we hope that `$routerCanActivate` becomes an instance method of the controller ...

@petebacondarwin Is there any document why the router was deprecated and what will happen to it?

**Comment by wardbell** [comment]
@Mischi  I have pretty good insight - but not definitive knowledge - into what's coming in the router. 

AFAIK, the precise mechanism you seek is not available in the deprecated router and won't be in the new router.

Before you get depressed about that, maybe we should think about what you're trying to accomplish.

When I squint, it appears that you want two things:
1) To cancel the navigation if specific data from the server are unavailable
2) If the data are available, to pass them to the target component

>aside: in A2 the component doesn't _have_ a controller; the component _is_ the controller.

This will be possible, just not in precisely the way you expect. 

Among the principles of the new router:
* routing configuration is separate from the components
* decisions about whether to navigate or not to a component are made prior to instantiating the component. 
* we only create a component when we know we can navigate to it.
* to create a component is to put it in the DOM; the two acts are inseparable.


Consequences:
* routing configuration can be in its own module and bundle, loaded apart from the component(s) referenced in that configuration.
* we can't put _can activate_ logic in the component itself because that's too late in the process.
* routing configuration can (and will) hold guard logic such as the _can activate_ logic 
* services needed by guard logic can (and will) be accessible through dependency injection

So what might you do?

You could write a _can activate_ guard that fetched data from the server and allowed/cancelled/redirected based on the outcome of that operation.

Your guard can delegate the fetching operation to an injectable data access service. You can share this service class with both the configuration and the components (e.g., both configuration and components might use the same implementation for fetching heroes). 

So how do you get the data fetched during _can activate_ to the component(s) that want that data? For technical reasons, the guard in configuration and the component to which you navigate cannot easily share the same service _instance_.

This will take some creativity. You might be able to attach it to the current navigation state object which flows from guard to component during the active navigation process. I've also thought about creating a root level "router dropbox service" where the guard deposits the data and the component (in ngOnInit?) picks it up (the service can be self-cleaning). Perhaps you'll think of another place to stash the data temporarily.

The data transfer part is a bit hacky. But far less so than instantiating a component, waiting for data, realizing that the data aren't coming, and navigating somewhere else ... while the user watches the empty component flicker into and out of existence. That would suck.

c/ @davidreher @petebacondarwin @brandonroberts

**Comment by Mischi** [comment]
@wardbell, thanks for your detailed answer.

> This will take some creativity. You might be able to attach the data to the current navigation state object which flows from guard to component during the active navigation process. I've also thought about creating a root level "router dropbox service" where the guard deposits the data and the component (in ngOnInit?) picks it up (the service can be self-cleaning). Perhaps you'll think of another place to stash the data temporarily.

This is something that @davidreher and me had thought of too. Now that you made clear that there is currently no proposed way to pass data from $canActivate to the component, we will think about a possible solution which doesn't feel to hacky :smile: 

BTW, our main intention for "preloading" the data from within the $canActivate hook is that we want to prevent _flickering_ while fetching/rendering the necessary resources. We could use some kind of animation so that the _flickering_ won't be so obvious but we like the behaviour of "classical" websites where the browser stays on the currently active page while loading a new page and finally flipping the content all at once.

Cheers,
Fabian
