### ISSUE TITLE
Unsent Http Requests return invalid Status Code

### ISSUE THREAD

**Issue by danielrasmuson** [angular/angular#8297]
**Current behavior**
Currently if a request fails to send the returned response code in the error handler is 200. This might happen when the user goes offline.

**Expected/desired behavior**
I would expect the status code to be 0.

Plunker Example
http://plnkr.co/edit/6MlCleNSNRh2GM5F3aPB?p=preview

**Comment by PeterOrneholm** [comment]
I can confirm this is an issue. The problem seems to be at line 58-60 in https://github.com/angular/angular/blob/master/modules/%40angular/http/src/backends/xhr_backend.ts .
![image](https://cloud.githubusercontent.com/assets/1662918/15147959/91447110-16c3-11e6-88cd-00d47b7cd2be.png)

Those lines seems to solve an issue with Android, but they break other stuff when building an app supporting offline scenarios.

**Comment by awerlang** [comment]
Fixed in rc.3 with #9355
