### ISSUE TITLE
routerLink with function is called permanently

### ISSUE THREAD

**Issue by awallat** [angular/angular#8308]
I've got a link, which looks like this:
`
<a class="btn btn-default" [routerLink]="['Graph', determineParameters()]">
      Link
</a>
`

This way the parameters for the route will be determined dynamically. However the function "determineParameters()" is called all the time, which is not good for performance reason.
Is this approach, to use a function there, intended to be used? Or should I register a (click)-event and do the dynamic route change in that handler?

Thanks for clarifying this!

**Comment by zoechi** [comment]
This is by design. Every time when Angular gets notified by an event or when an async call is completed it runs change detection (in devMode twice) and every time it calls bound functions to check if it returns the same value or a different one. You can either bind a click handler and use `router.navigate(['Graph', determineParameters()])` or you can assign the values to a property in your class and bind to that class instead.

**Comment by awallat** [comment]
Thanks for the info!
