### ISSUE TITLE
Binding "checkbox" as type property on input control doesn't update ngControl

### ISSUE THREAD

**Issue by Cobster** [angular/angular#8392]
**  Demo **
https://plnkr.co/edit/3WhdJJ

_What steps should we try in your demo to see the problem?_
Click the checkbox input controls and see how the form value is updated.  The bound checkbox does not update.  

**Current behavior**
When a form input control has a bound type property of 'checkbox' the ngControl directive defined on the same element will not update its state via form.value.  When statically defined, it works as expected.  

**Expected/desired behavior**
The value of the input control should be reflected in the form's value object.

**Other information**
Binding the type property works for 'text' and 'number', I haven't tried the other possible values.

**Comment by zoechi** [comment]
Selectors of directives work only for statically added attributes https://github.com/angular/angular/blob/bb8976608db93b9ff90a71187608a4390cbd7a07/modules/%40angular/common/src/forms/directives/checkbox_value_accessor.ts#L20 (similar to #7393)

As a workaround you can create a custom ControlValueAccessor to be used instead of the `CheckboxControlValueAccessor`

**Comment by zoechi** [comment]
dup of #7329

**Comment by Cobster** [comment]
Thanks.
