### ISSUE TITLE
rc.0 question: if i'm using systemjs for loading, which files i need to copy using gulp while publishing app ?

### ISSUE THREAD

**Issue by virtualvoid** [angular/angular#8412]
Until the angular2 rc.0 (yay!) there was files like `angular2.dev.js` `http.dev.js` `router.dev.js` etc. 
I was copying these files using gulp task from `node_modules/angular2/bundles` into` wwwroot/libs` because it's just bad practice to deploy all the things from `node_modules` into the same folder on web server.

The [quickstart's index.html](https://angular.io/docs/ts/latest/quickstart.html) is including stuff from `node_modules`. Now the question is, which files I need to copy from `node_modules/@angular` in order to get the app working outside ?

I think it would be nice if the quickstart contains information on how to deploy apps too.

**Comment by robwormald** [comment]
we're not yet shipping bundles with the new RC (soon) - now would be a good time to look at setting up a proper build process rather than using the bundles, which will always give you more code than you need.

Assuming you have a functional app that runs by dynamically loading the individual files, its trivial to set up a system build step - https://github.com/robwormald/new-world-test/blob/system/system-js/bundle.js for example. You can wrap that in a gulp task and build your own bundle.

**Comment by damienbod** [comment]
This is a problem when trying to use angular2 with Visual Studio and the ASP.NET core template. The quick start does not work.

**Comment by virtualvoid** [comment]
@robwormald that look promising, does it work with external templates (templateUrl) ?

**Comment by antonybudianto** [comment]
@virtualvoid please take a look at my starter [setup](github.com/antonybudianto/angular2-starter)
we can use [systemjs-builder](https://github.com/systemjs/builder) to bundle everything into one file

**Comment by virtualvoid** [comment]
So, I've tried the systemjs builder and i don't like the way it works (path mapping). 

I'll stick with webpack for now. I hope it will work with rc.0.

**Comment by Kriskit** [comment]
To clarify, is this to say that systemjs bundles will no longer be provided from now on?

**Comment by woppa684** [comment]
@robwormald , it's me again ... (see, https://github.com/angular/angular/issues/5248#issuecomment-156438317) After a lot of hard work we finally had our build chain going with MSBuild:

- resolve dependencies (e.g. angular2, systemjs, es6-shim etc)
- copy d.ts files of dependencies from our thirdparty folder to the correct node_modules folder in source
- copy source html files (templates) and svg's to intermediate folder
- compile source scss files to intermediate folder (using node-sass)
- compile ts files to intermediate folder
- tslint
- inline svg's in html and css
- inline html and css files in js files
- run tests (using karma and phantomjs)
- publish generated d.ts files
- bundle (using webpack)
- copy bundles of dependencies from thirdparty folder to output folder, after this step this folder contains a working application including its dependencies

So, as I see now I have to change my build system again. What steps need to change? Since there are no bundles anymore is it expected that I compile the source into my own applications? Can I still create my own bundles or will they be here soon again? I'm a bit puzzled at the moment... 

I know this page is only for issues, but since we were already on the topic I thought I'd chip in ... :)

**Comment by vicb** [comment]
obsolete
