### ISSUE TITLE
rc.0 why performance is low?

### ISSUE THREAD

**Issue by itsurge** [angular/angular#8417]
I've updated to the new RC version and faced up  f... low performance.
too much requests has been fetched on the first boot up and make it slow.
as you can see on the attached picture determine many requests and how much longer it take.
![issue](https://cloud.githubusercontent.com/assets/12558885/14981314/87dbd49a-1143-11e6-919b-5540868637cf.jpg)

**Comment by beckler** [comment]
I'm assuming you ran the [quickstart](https://github.com/angular/quickstart/blob/master/README.md)?

It specifically says:
> This is not the perfect arrangement for your application. It is not designed for production. It exists primarily to get you started quickly with learning and prototyping in Angular 2

**Comment by itsurge** [comment]
So.I was wondering if you guide me how can I reach to the perfect prototype and fastest design.
I faced with many library which included on packageNames on the systemjs.config and need to know which of them are exactly necessary for booting up my application?
As refer to my experience on both version (the current version and beta version) I think previous one is faster than the current one. does it true or I was wrong ?

**Comment by beckler** [comment]
There are a quite a few [yeoman generators](http://yeoman.io/generators/) that can help with that.

As far as your performance experience, this isn't really the correct repository for this issue.
You should probably close this issue, and then [file a new issue here](https://github.com/angular/quickstart).

**Comment by ClementVidal** [comment]
@beckler I find here to be quiet a good place for that. It involve any angular2 projects.
@itsurge i get exactly the same issue, fetching dependencies take more or less 4 times more compared to beta16. 
Is there any plan for rc1 concerning that issues ?

**Comment by erwin-beckers** [comment]
Same here.. please bring back the bundled js files in rc1.

**Comment by ericmartinezr** [comment]
The bundles they distributed through code.angular were meant to be used with plnkrs only, you should never used them in prod, barely in dev. You should bundle your application yourselves like most people are doing it.

**Comment by erwin-beckers** [comment]
I do bundle all my application code myself and until beta 17 included the angular bundles with it.
So basically i had 2 bundles, 1 containing all libraries like angular and 1 for all my application code. This worked perfectly and was very fast so i would like to continue this way.
I have no problem bundling rc.0 myself, but don't know how ?
A tutorial on how to use angular 2 in production would be nice. 
At the moment i'm clueless how to bundle rc.0 since i'm working with visual studio 2013 and not with node , grunt and all those tools.

**Comment by talmog** [comment]
I am using https://github.com/antonybudianto/angular2-starter which is a great starter that will bundle the code for you.

**Comment by erwin-beckers** [comment]
Thanks @talmog , however thats very useful for a nodes based development system, but useless in my case (VS2013/2015) :-(

**Comment by itsurge** [comment]
@erwin-beckers In one hand I can't get why 290 request should be fetch and the other hand believe that bundle using is hack way to reach result. If I'm wrong please clarify me. 
@beckler I believe that AngularJS 2 RC 0 is going back.

**Comment by itsurge** [comment]
[quickstart ](https://angular.io/docs/js/latest/quickstart.html)has changed and The problem was solved

**Comment by ClementVidal** [comment]
@itsurge I have looked at the last commit in https://github.com/angular/quickstart, and did not find any direct clues to solve this problem.

But i saw @wardbell update from **rc0** to **rc1**, does this upgrade change the way packaging is done ?

**Comment by ChrisProlls** [comment]
@itsurge you indicate the quickstart in JavaScript, but what about TypeScript ? 
@ClementVidal I have the same problem with RC1 ...
@erwin-beckers Have you found a solution ?

**Comment by ClementVidal** [comment]
The way to solve that, and to get an even better workflow than before, is to use **WebPack** ( or promise.js ).

It took me awhile before diving into webpack, but it really worth the price !

The best way to start is here : [Introduction to webpack](https://angular.io/docs/ts/latest/guide/webpack.html)

**Comment by ChrisProlls** [comment]
Is it possible to use Webpack with VS2015 and IIS ? Any example of that ?

**Comment by beckler** [comment]
@ChrisProlls It's possible to use Webpack when building with VS. Since Webpack is more of a task runner for making bundles, you would want to run it before you deployed it to IIS. If you're using another task runner, like gulp or grunt, it's pretty easy to add that integration into your workflow. Regardless, Webpack comes with a CLI, so you could call it in the pre- or post-build script in your project. Just add a check to make sure it exists before calling it, or anyone else using your project would have it instantly fail.

**Comment by ChrisProlls** [comment]
@beckler @ClementVidal Thanks for your response !
