### ISSUE TITLE
Using dashes on directive property names throws error

### ISSUE THREAD

**Issue by pancho111203** [angular/angular#8472]
I am upgrading an angular1 directive from a library (jsonforms) to an angular2 freshly created project. The problem is that the 'jsonforms' directive expects a property called 'ui-schema'. Apparently, the use of a dash in property name causes an error (I have tried modifying the library to use 'uischema' instead and it works perfectly).

The issue is triggered here:

```
@Component({
    selector: 'sidebar',
    template: '<jsonforms class="jsf" [schema]="schema" [ui-schema]="uischema" [data]="data"></jsonforms>',
    directives: [JsonFormsAdapter]
})
```

And this is the error:

`Can't bind to 'ui-schema' since it isn't a known native property`

I went through the angular code and it seems that the error is caused on the class /compiler/src/template-parser.ts, on the method _createElementPropertyAsts.

```
private _createElementPropertyAsts(elementName: string, props: BoundElementOrDirectiveProperty[],
                                     directives: DirectiveAst[]): BoundElementPropertyAst[] {
    var boundElementProps: BoundElementPropertyAst[] = [];
    var boundDirectivePropsIndex = new Map<string, BoundDirectivePropertyAst>();
    directives.forEach((directive: DirectiveAst) => {
      directive.inputs.forEach((prop: BoundDirectivePropertyAst) => {
        boundDirectivePropsIndex.set(prop.templateName, prop);
      });
    });
    props.forEach((prop: BoundElementOrDirectiveProperty) => {
      if (!prop.isLiteral && isBlank(boundDirectivePropsIndex.get(prop.name))) {
        boundElementProps.push(this._createElementPropertyAst(elementName, prop.name,
                                                              prop.expression, prop.sourceSpan));
      }
    });
    return boundElementProps;
  }
```

**Comment by ericmartinezr** [comment]
How are you receiving the input in your JsonFormsAdapter component class? If you have an input with a dash you have to specify it in the Input like `@Input('ui-segment') uiSegment: string`, see this plnkr http://plnkr.co/edit/bNfAShKgMnAJE3OOjtFp?p=preview .  I understand there's Upgrade involved, but probably your issue is what I think it is, otherwise ignore this comment.

**Comment by pancho111203** [comment]
@ericmartinezr The directive is generated with this: upgradeAdapter.upgradeNg1Component('jsonforms');
So I'm not sure how can I add the Input() to it, if I'm not able to modify it. With angular1 it was working properly using 'ui-schema', I'm pretty sure that's the name specified in the directive.

**Comment by ericmartinezr** [comment]
@pancho111203 Ahhh, sorry, I'm not really familiarized with ng1, even less with upgrade. You're upgrading from ng1 to ng2 the component receiving the input. I thought I could be helpful but actually I misunderstood your issue, I apologize.

**Comment by pancho111203** [comment]
@ericmartinezr No need to apologize, I appreciate the intention :)

**Comment by petebacondarwin** [comment]
@pancho111203 - I am sorry I have only just got round to looking at this issue. Can you confirm that it is still a problem for you?

**Comment by petebacondarwin** [comment]
I also note that jsonForms now expects attributes with no hyphen...

**Comment by gkalpak** [comment]
Since you are in an Angular template, you should use `camelCase` as attribute values (there is not need o convert camelCase to kebab-case as in AngularJS). Also, as @petebacondarwin mentioned, `jsonForms` now accepts non-hyphenated attrs, so...

<sub>(Not related to this issue, but if you are using `upgrade/static` you can explicitly specify any attribute name: `@Input('some-attrInWeird_CASE') myProp` or `inputs: ['myProp: some-attrInWeird_CASE']`</sub>
