### ISSUE TITLE
inputs/textareas bound to a string of arrays cause typing in one input/textarea to update the next one. (see plunker)

### ISSUE THREAD

**Issue by jonah13** [angular/angular#8531]
Issue with displaying text written to textareas/inputs that are bound to an array.

**Steps to reproduce and a minimal demo of the problem**

_Minimal Demo:_
http://plnkr.co/edit/vRogMAujCbLSUwAIjSPH?p=preview

_What steps should we try in your demo to see the problem?_
Type anything in the first textarea or first input, click outside it to trigger change event.

**Current behavior**
The text you type also displays in the textarea/input next to it

**Expected/desired behavior**
Text shouldn't display in any other textarea/input

**Other information**
There's also an issue with keyup event but I think fixing the case of change event will also fix it for keyup.
P.S. noticed this issue while working on creating an editable table plugin. Hopefully it will be fixed soon.
Thanks and let me know if you need any extra information.

**Comment by zoechi** [comment]
This is because Angular (or rather TypeScript and JavaScript) can't distinguish between `''` and `''`

Wrapping the values in objects makes it work http://plnkr.co/edit/dNqTJGx1vHP9cp0oURVS?p=preview
Using `ngForTrackBy` might also work when using arrays of strings (or other primitive types) with `*ngFor`

GitHub issues are for bug reports and feature requests.
    For support questions please use other channels like the ones listed in [CONTRIBUTING - Got a Question or Problem?](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question)

**Comment by pkozlowski-opensource** [comment]
Thnx @zoechi
