### ISSUE TITLE
Bootstrap css not linked in index.html in Quickstart

### ISSUE THREAD

**Issue by billfranklin** [angular/angular#8595]
If you are going to include the Bootstrap component in the loading/configuration, you should put it in the index.html, so as not to confuse people that expect it to work.  Only took me about 3 seconds to figure it out, but I am sure others have struggled with why it isn't working.

<link href="node_modules/bootstrap/dist/css/bootstrap.css" rel="stylesheet" />

**Comment by CarlCui** [comment]
Angular2 does not force you to use any sort of css libraries. Besides, Angular2 quickstart uses its own stylesheet, so it will work.

**Comment by wardbell** [comment]
I respectfully disagree. We have Twitter bootstrap in our npm `package.json` because some of the samples   need it. Most do not and we don't see value in freighting every `index.html` with a big library that is irrelevant.

We have no evidence that anyone has been seriously put off by our decision.

Opinions may differ. That's where we stand.

Please close.
