### ISSUE TITLE
version not found: angular2@2.0.0-rc.1

### ISSUE THREAD

**Issue by OneNewLife** [angular/angular#8651]
Please publish the **angular2@2.0.0-rc.1** on NPM, I really need it 

The latest version is just **2.0.0-beta.17**

ths :)

**Comment by ericmartinezr** [comment]
Upgrade your node/npm version and see the [changelog](https://github.com/angular/angular/blob/master/CHANGELOG.md#200-rc0-2016-05-02) to see how to install it.

**Comment by gelidus** [comment]
You can also refer to the quickstart tutorial from official docs: https://angular.io/docs/ts/latest/quickstart.html

**Comment by dominique-mueller** [comment]
The package name changed wiht RC, it's now called "@angular" instead of "angular2". Just follow the links mentioned above to find the new packages you need.

**Comment by Laureian** [comment]
@OneNewLife is right. There was rc.1 beta on npm now it is probably deleted. This is not problem with installation method.

**Comment by dominique-mueller** [comment]
Since the RC, Angular is split up into multiple different packages, for example "@angular/core". These packages are in RC, the "old" "angular2" package probably will never be updated to RC.

As already mentioned, the quickstart from the official docs (https://angular.io/docs/ts/latest/quickstart.html) tells you the package names you need now.

**Comment by Laureian** [comment]
Yes, i know that. I've copied new names from quickstart, but when i tried to install it npm telled me that there is no package called for example: '@angular/common'. Now everything is fine - maybe there was problem with npm servers or something else.
