### ISSUE TITLE
EXCEPTION: ngFormModel expects a form. Please pass one in. Example: <form [ngFormModel]="myCoolForm">

### ISSUE THREAD

**Issue by pavandv** [angular/angular#8665]
After Upgrading from **2.0.0-Beta.14** to **RC.0 & RC.1**.. 
ngFormModel doesn't work anymore.

I get the folowing error provided in screenshot even though ngFormModel is in form tag.

```js
@Component({
    selector: "Login",
    templateUrl: "./auth/login.html",
    directives: [FORM_DIRECTIVES]
})
export class Login {
    loginForm: ControlGroup;
    ...
    constructor() {
        this.loginForm = new ControlGroup({
                email: new Control(self.email),
                password: new Control("")
            });
    }
...
}
```

```html
<form [ngFormModel]="loginForm" (ngSubmit)="submit()">
          <input class="Ye" required name="email" [ngControl]="email" type="email">
          <input class="Ye" required name="password" [ngControl]="password" type="password">
 </form>
```
![screenshot 34](https://cloud.githubusercontent.com/assets/10683228/15275064/7a628520-1adf-11e6-9e30-a2f69dae4303.png)

**Comment by ericmartinezr** [comment]
Remove the brackets in ngControl.

**Comment by pavandv** [comment]
I have tried that too but hard luck couldn't resolve.

Here is the plnkr link, to reproduce the same issue.
http://plnkr.co/edit/aekSvP4GM69307H5I2ag?p=preview

**Comment by ericmartinezr** [comment]
There you go http://plnkr.co/edit/OzNzLRti0u90jPCWYPHE?p=preview

**Comment by kirjai** [comment]
Hey @pavandv so the issue seems to be that you are initializing your `loginForm` inside a `.then` method. Since it's an asynchronous action that gets performed at some time in the future, upon component initialization (both the class and the template) - value of `loginForm` is undefined, and `ngFormModel` doesn't recognize it as a form (hence the error).

So if you move your `loginForm` initialization (`this.loginForm = new ControlGroup(...)`) outside `.then in your constructor`, that should fix it.

And in order to keep the functionality that you are trying to achieve, which is displaying user's email when it's returned as part of `getCurrentUser()` response, I would suggest you hide the form (or show some kind of loading state) before `getCurrentUser` returns. You already have a `[hidden] = "welcome"` specified on your `<form>` element that you can use.

**Comment by pavandv** [comment]
Thanks for your inputs @ericmartinezr @kirjai 

My bad, I should have know this.

Closing this issue.
