### ISSUE TITLE
ng.probe() is unavailable in production mode

### ISSUE THREAD

**Issue by bluejaye** [angular/angular#8682]
Dear Guys

Somehow I need to use JS to trigger angular's methods. In developer model, I can use ng.probe() to find the component resources. However, ng.probe() is not available in production mode. 

Can you give me a simple hint how to find angular 2 component by JS in production mode please?

Cheers
Jay

**Comment by mhevery** [comment]
Yes, ng.probe is not available in prod. There is speed and memory overhead to it.

**Comment by simonvane** [comment]
Hi @mhevery, 

That doesn't answer the question, just confirms what @bluejaye already said.

Any chance of answering the question?

Thanks.

**Comment by bluejaye** [comment]
@mhevery 

Expecting to get the answer .

**Comment by rpaschoal** [comment]
How can this be closed? There is no clear answer about how to do this. 

Does it means we can't push commands to Angular 2 by JS in real world scenario?

Cheers.

**Comment by mhevery** [comment]
Sorry, the answer is that you can't. For perf and size reasons angular compiles things together. `ng.probe` breaks these optimizations, so you can't have it both ways. 

I closed the issue because I thought the question was how to get hold of `ng.probe` I now see the real question is that you would like to be able to call angular app from the surrounding JS. Sorry my confusion.

The way to do that is that `boostrap` returns `ComponentRef` and there you can get a hold of root component instance. You can then call methods on the component instance. Think of root component as the interface to the outside world. 

Does that satisfy your question?

**Comment by bluejaye** [comment]
@mhevery 

Thank you so much to answer my question. The answer is very very close but I still need two line demo please.

eg:
var testabc= bootstrap(AppComponent, [ROUTER_PROVIDERS]);

how can I find testabc instance in google browser's debug console?

**Comment by doczoidberg** [comment]
you could use the window instance. window.testabc =...

**Comment by HackPoint** [comment]
@bluejaye could you please show an example of how to use it in angular5? Cause `bootstrap` doesn't exists in it.

```
const testabc = platformBrowserDynamic().bootstrapModule(AppModule)
  .catch(err => console.log(err));
console.log(testabc);
```

That doesn't show's here...
`window.abctest ==> undefined.`
