### ISSUE TITLE
Metadata-Reflect and Zone issues (death spiral)

### ISSUE THREAD

**Issue by BrewDawg** [angular/angular#8726]
I have been working on this for a week now. While there are many examples out there that can somehow run using the "npm run lite" type server we have yet to find, or produce an Angular.js 2 demo, of the simplest form, that will run launching it directly from node.exe.

The same application that will run using "npm" start where the script is 

"start": "tsc && concurrently \"npm run tsc:w\" \"npm run lite\" ",

will in no shape or form ever run by launching it using node.exe directly? Why is this.

These are the errors:

 C:\github\NodeUnderVS2015_new\Node_js\node_modules\@angular\core\src\util\decorators.js:165
        throw 'reflect-metadata shim is required when using class decorators';

Then if you do "import 'reflect-metadata';" as some suggest is the work around you get

****C:\github\NodeUnderVS2015_new\Node_js\node_modules\@angular\core\src\di\reflective_injector.js:679**
            throw e;
            ^
ORIGINAL EXCEPTION: ReferenceError: Zone is not defined
ORIGINAL STACKTRACE:
ReferenceError: Zone is not defined
    at new NgZoneImpl (C:\github\NodeUnderVS2015_new\Node_js\node_modules\@angular\core\src\zone\ng_zone_impl.js:22:13)**

This is very frustrating, we are trying to start a new project and there are no simple samples using  Angular RC-1 that work by launching them from node.exe directly, they all use the lite server, whatever that is.

**Comment by CarlCui** [comment]
Seems like you have two main issues here. 

1. You have to include reflect-metadata and zonejs for angular 2 application, as described in [quickstart](https://angular.io/docs/ts/latest/quickstart.html#!#index).

2. The lite server is just, as the name suggests, a light-weight server. You can of course replace it with any server you like (eg. expressjs), but since this is a web application, I guess you cannot just run it with node.

I strongly recommend you to follow the quickstart closely in the beginning, since it's quite a lot to learn beside angular 2 itself.

**Comment by pkozlowski-opensource** [comment]
Thnx @CarlCui
