### ISSUE TITLE
'track by' expressions for Inputs

### ISSUE THREAD

**Issue by zbjornson** [angular/angular#8738]
As discussed in https://github.com/angular/angular.js/issues/14378...

It would be nice to have `track by` expressions for Inputs that result in specialized change detection, like:

```typescript
class MyObj {
  _id: number;
  version: number;
}

@Component()
class MyComponent {
  @Input('my-arr track by _id')  myArr: [MyObj];
  @Input('my-obj track by version') myObj: MyObj;
}
```

* For array-of-object inputs, this would behave the same as ngRepeat's `track by`/`ngForTrackBy`.
* For object inputs (including arrays), this would watch the specified property on the object.
  * For arrays, this property could [only?] be `length`. To disambiguate between a `length` property of objects in an array of objects and the length of the array of objects, perhaps it would be `track by $length`.
  * For other objects, this could be whatever the user wants, e.g. a "version" property.

This is possible by implementing `doCheck`, but it takes a lot of boilerplate in every component for something that seems broadly applicable.

**Comment by sod** [comment]
Angular generates a special change detection for each component for you! And only values you use in your template are checked.

See here in the console. ComponentA uses property spy_a & spy_c. ComponentB uses spy_b. You see the change detection checks for all those. But skips spy_d, because its not used anywhere:
http://plnkr.co/edit/56OywsP4cGyMX1cLotlq?p=preview 

In the console you see angular does it's checks and then does them again. The second round is the dev mode (warns you, if something changed while change detection). If you execute `enableProdMode` every used property is exactly checked once.

**Comment by zbjornson** [comment]
That works for DOM elements, but `ngOnChanges` won't fire after initialization. In this fork, the `ngOnChanges` in ComponentA never fires, but with a custom `ngDoCheck` based on the array length in ComponentB we can detect the change:
http://plnkr.co/edit/74d0r3byCy4azyaGDSfj

**Comment by zbjornson** [comment]
(BTW, I'm volunteering to make a PR for this if the Angular developers like the idea and would accept it.)

**Comment by vicb** [comment]
You can already implement your own CD strategy.

**Comment by zbjornson** [comment]
Indeed, as mentioned in the OP, this is possible with `doCheck` but takes a lot of boilerplate code. This would be a shortcut feature for what seems like a common use case.

This might also be a performance opt if Angular is doing deep watches for template rendering (I haven't looked at what A2 does internally in a long time though).

**Comment by vicb** [comment]
> what seems like a common use case.

If this becomes a common use case then we can probably re-consider. For now it doesn't look so.
