### ISSUE TITLE
No main property in package.json

### ISSUE THREAD

**Issue by nfroidure** [angular/angular#8764]
In order to read the source, i made like i always do, open the package.json file and check the main prop. I was wondering if it make no sense at all for such a huge framework or if it had simply been forgotten.

**Steps to reproduce and a minimal demo of the problem**
Open package.json

**Current behavior**
No main prop

**Expected/desired behavior**
A main prop allowing anyone to read the source from that starting point.

**Other information**
None

**Comment by robwormald** [comment]
The distributed packages via NPM do contain a `main` property (and also a `jsnext:main` pointing to the ES6 entry point). The one in the root of this repository you'll note is called angular-srcs, and isn't the distributed version. There's no "main" entry point in this repo, as such, since it produces several packages that are shipped to npm.

**Comment by nfroidure** [comment]
@robwormald thanks for the explanations, i think it would be a good improvement to add a note about the repo's structure in the main README to bootstrap new contributors/curious developers ;).
