### ISSUE TITLE
Dynamic form with [checkbox, radio, file] doesn't work

### ISSUE THREAD

**Issue by aslan92** [angular/angular#8811]
- [ ] bug report

http://plnkr.co/edit/6XKA5Bk8Oor8dP8pL1xr?p=preview

http://stackoverflow.com/questions/37412063/angular-2-dynamic-form-with-checkbox-doesnt-work/37412218#37412218

**Comment by zoechi** [comment]
What is the expected behavior and what is the actual behavior?

**Comment by aslan92** [comment]
`app/question-control.service.ts`
```
controls.forEach(control => {
    group[control.key] = control.required ? [control.value || '', Validators.required] : [control.value || ''];
});
```

fails because `control.value` does not change

**Comment by kara** [comment]
Thanks for reporting this issue. This issue is now obsolete due to changes in recent releases. Please update to the most recent Angular version.

If the problem still persists, please file a new issue with a minimal repro on plunker.

**Comment by mohammedzamakhan** [comment]
For dynamic forms try Angular Formly 2

https://ng2.angular-formly.com/

**Comment by michael-letcher** [comment]
_Angular 5.1.2_

I believe this issue in some form still exists.

following the design pattern given via Angular's [Dynamic Form](https://angular.io/guide/dynamic-form) guide I have found that all three (checkbox, radio and file) do not work within the question component.

Only by following this [answer](https://stackoverflow.com/a/37413304/2536454) did they begin to work.

The issue seems to be that when the html elements are dynamically build they do not connect via the formControlName.
If they are static, they work no problem.
