### ISSUE TITLE
ViewContainerRef strange behavior for createComponent

### ISSUE THREAD

**Issue by zolekm** [angular/angular#8817]
* **I'm submitting a strange behavior for ViewContainerRef.createComponent.**
- [x ] bug report
- [ ] feature request
- [ ] support request => Please do not submit support request here, see note at the top of this template.

**Current behavior**
When want to create component in current component container like this component is rendered outside container of current component:  this.componentResolver.resolveComponent(SampleComponent).then((factory) => {
            console.log(this.viewContainerRef);
            this.viewContainerRef.createComponent(factory);
        });

Result:
![image](https://cloud.githubusercontent.com/assets/5635687/15512320/8cd38798-21df-11e6-9a20-01c076724a7e.png)

**Expected/desired behavior**
Expect to load new component inside container of current component example in body-bar component

* **Please tell us about your environment:**
Project generated with angular cli

* **Angular version:** 2.0.0-rc1
 
* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ] 
 
* **Language:** [TypeScript]

**Comment by zoechi** [comment]
Please provide a Plunker

**Comment by zolekm** [comment]
Here is plunker example: http://plnkr.co/edit/oqljNH1fKggO5eoaOhtV

**Comment by zoechi** [comment]
I guess that's by design. You can get a ViewContainerRef from any element in the view that has a template variable and add the component there http://plnkr.co/edit/7daeL0yEzJl2tCgAGgai?p=preview

**Comment by zolekm** [comment]
Yes, thank you for help, now it works! 👍

**Comment by pkozlowski-opensource** [comment]
Thnx for helping out @zoechi !

**Comment by joelrich** [comment]
@zoechi, maybe I am just misunderstanding something, but the behaviour seems really odd to me. Even if I use @ViewChild, the dynamic component is still added as a sibling (just as a sibling of the view child this time). If this is really the intended behaviour, how is it possible to add a dynamic component to another component without having any other children?

Example: https://plnkr.co/edit/StKsmit7edbsoFgsUFDt?p=preview

My goal is to have the example-component as the only child of the root-app component.

**Comment by zoechi** [comment]
@joelrich it's discussed in more detail here https://github.com/angular/angular/issues/9035
I'll have a look at your Plunker later.

**Comment by joelrich** [comment]
@zoechi Thanks for the link. I got it working with a ```<template>``` element. I do not find this solution satisfying though.

**Comment by pkozlowski-opensource** [comment]
>  I got it working with a <template> element. I do not find this solution satisfying though.

Why isn't it satisfying? Please note that `<template>` elements are not rendered in the resulting DOM, they exists during compilation only.

**Comment by joelrich** [comment]
@pkozlowski-opensource I am new to Angular 2 and might change my opinion later, but right now I just have the impression that this API is not high-level enough for the usage outside of the core. It behaves different from what most web developers are used to. Moreover, using an empty template feels like a hack.

I work on a highly customisable web application. If we want to use Angular 2 there, then we will have to use dynamic components everywhere. The use case is always one of the following two:

- Render one dynamic component with some properties.
- Render a list of dynamic components with some properties.

In React, this is very easy to accomplish because you can just return a random element from the render function. I wished that you could do something similar in Angular. For example:

```
<template *ngFor="let c of components" [ngComponent]="c.type"
    [prop1]="c.prop1" [prop2]="c.prop1" [ngProperties]="c.props">
```

This would render 0-n dynamic components of a certain type with some properties which are always the same as well as some other properties which are specific to the dynamic component. Probably ```template``` isn't the correct choice here, but you get the idea :-)

I think that this could replace most of the ```createComponent()``` usages. Developers would also not have to think about updates anymore because if any of the properties or even the component type changes, the view is refreshed automatically as with normal templates.

Does that make sense?

**Comment by zoechi** [comment]
That's what I explained in http://stackoverflow.com/questions/36325212/angular-2-dynamic-tabs-with-user-click-chosen-components/36325468#36325468
You can't have different inputs (`[prop1]="..."` ...) dependeing on the dynamic component but you can have some generic property where you pass an object and then assign by name to the dynamically created component in the wrapper.

**Comment by pkozlowski-opensource** [comment]
@joelrich what you are saying makes sense but I believe that what you are looking for will be covered by #8563. Anyway, your concerns are very high-level and the discussion becomes off-topic for the very precise issue here.

Please check #8563 and comment in-there if you believe that some of your use-cases are not covered by this proposal.

**Comment by joelrich** [comment]
@zoechi I know that it does not work, but I think it should be possible to render a dynamic component without having to write all this custom code. In my example, the component type is set with the ``ngComponent`` property. This would basically replace the ``<template>`` with the component element. ``prop1`` and ``prop2`` would be set like normal properties. ``ngProperties`` would set all properties from the given object to the component.

@pkozlowski-opensource If I understand #8563 correctly, then it's only about projection of content and would not allow to create dynamic components. If you think my proposal has a chance, then I will create a seperate issue for it.

**Comment by Blasz** [comment]
@joelrich I agree with you on both points. #8563 allows more programmatic control over projected content but is not related to dynamic components (this is more or less directly stated here: https://github.com/angular/angular/issues/8563#issuecomment-219163568).

There's some relevant discussion about dynamic components in https://github.com/angular/angular/issues/7596 but it's OP is about ng-include/dynamic templates rather than components (and its already closed).

I would encourage a new issue/proposal for dynamic components as they are required for any structurally configurable applications and there is currently no easy way to implement them. The two ways of implementing them currently are problematic:

* `ngSwitch`
    * a lot of property binding duplicate code
    * doesn't scale
```
<div *ngFor="let c of components" [ngSwitch]="c.type">
  <my-square *ngSwitchWhen="components.square"
    [props]="c.props">
  </my-square>
  <my-rectangle *ngSwitchWhen="components.rectangle"
    [props]="c.props">
  </my-rectangle>
  <my-circle *ngSwitchWhen="components.circle"
    [props]="c.props">
  </my-circle>
  ...
</div>
```

* Creating a custom wrapper as mentioned in the stackoverflow link above.
    * Custom low-level code.
    * Lacks support/recognition from angular team when making decisions about new features/roadmap e.g. offline compiler.
    * Could break if angular makes breaking API changes.

**Comment by joelrich** [comment]
@Blasz @pkozlowski-opensource I have opened a separate issue for my proposal: #9599

**Comment by keyiis** [comment]
@joelrich  **add a dynamic component to another component without having any other children?** 
Did you solve?

**Comment by zoechi** [comment]
@kyiis you can use `<template #target></template>` as target, then you don't need to add an artificial anchor element. The `<template>` never gets added to the DOM. 
Not sure if this is what you're asking for.

**Comment by keyiis** [comment]
@zoechi i tried,but failed.
```
<div #lgModal class="modal fade" style="">
    <div class="modal-dialog modal-lg">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" (click)="hide()" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
                <h4 class="modal-title">Description</h4>
            </div>
            <div #body class="modal-body">
                 <template #target>I hop can dynamic  insert any component to here</template>
            </div>
        </div>
    </div>
</div>
```
--------------component.ts------
```
 @ViewChild('target', {read: ViewContainerRef}) bodyContainerRef:ViewContainerRef;
    constructor(private compiler: ComponentResolver,private viewContainerRef:ViewContainerRef) {}
    body(modalBody:any) {
           this.compiler
                .resolveComponent(modalBody)
                .then(
                (factory) => this.viewContainerRef.createComponent(factory)
                ).then((componentRef) => {
                    console.log('create modal component!');
                })
    }
```

**Comment by zoechi** [comment]
@keyiis what's the problem?

**Comment by keyiis** [comment]
@zoechi when runtime,it's replaced body(target) and not insert into body(target) .

**Comment by scottseeker** [comment]
I'd like to chime in and say that the behavior of inserting the component as a sibling and not a child is odd to me.  I would expect default behavior to be the child.

In fact in the latest version of angular I had to do some typecasting to access private variables just to get a reference to the parent component of an attribute directive.   It would be amazing if I had a choice to insert as a child or a sibling.

The <ng-template #tag> approach for view children doesn't help my specific use case. This requires I know things a head of time and does not allow me to create child components conditionally/dynamically.

Because of this I must now drop my elegant approach and write a ton of boilerplate code.

**Comment by jo-soft** [comment]
from the [documentation](https://angular.io/api/core/ViewContainerRef) 
```
Instantiates a single Component and inserts its Host View **into this container** at the specified index
```
so if it's not a bug. at least the docs should be extended / improved.

**Comment by keyiis** [comment]
I still  think that the createComponent is somewhat odd

**Comment by samherrmann** [comment]
I'd have to agree that the current behaviour feels off. The following is the description in the documentation for [createComponent](https://angular.io/api/core/ViewContainerRef#createComponent):

> Instantiates a single Component and inserts its Host View into this container at the specified index.

From a semantic standpoint I'd struggle to justify wording such as "_inserts its Host View into this container_" to mean "append after".

I came across an [interesting article on hackernoon](https://hackernoon.com/exploring-angular-dom-abstractions-80b3ebcfc02) that pointed out this behaviour as well:

> What’s interesting is that Angular doesn’t insert views inside the element, but appends them after the element bound to ViewContainer. 

Having said all that, it's not a show stopper.

**Comment by lordazzi** [comment]
So, I'm two years in the future now.... there is some solution for this issue? I can make some magaiverism to put the element inside the container, to catch the behavior describe in the documentation, but I won't.

I'm using angular at 4.4.6 version.

**Comment by mlc-mlapis** [comment]
@lordazzi ... it is just a misunderstanding what is what ... `Root elements of Views attached to this container become siblings of the Anchor Element in the Rendered View.`
