### ISSUE TITLE
inconsistent behaviour when using FormBuilder instead of `new`ing controls

### ISSUE THREAD

**Issue by fxck** [angular/angular#8919]
When `push`ing a `FormBuilder.control` to a `FormBuilder.array`, and iterating over the array of controls in the template, it doesn't reflect the change in the template(but internally the control gets added), while when using `new Control` and `new ControlArray` it updates the template properly.

You can see it here:
http://plnkr.co/edit/ZfkBpsJSED31ONJiTExC?p=preview (`new`)

vs. 

http://plnkr.co/edit/8qY1TmvWV6x9wI7o4Zm4?p=preview (broken -` FormBuilder`)

The code is identical, the only difference is that the first plunk is using `new Control` , `new ControlArray`, `new ControlGroup` while the second(broken one) us using `fb.control()`, `fb.array()`, `fb.group()`

**rc.1**

**Comment by fxck** [comment]
Apparently it's **just** this line that is causing the problem `this.titleControlsArray = this._fb.array(this.titleControls);`

**Comment by kara** [comment]
@fxck  It looks like you're passing the `FormBuilder.group` method an object with `FormControl` instances as values. It actually expects initial values (or arrays containing the value and validators) because it will be instantiating the `FormControl` instance on its own.  You can see an example with the new form API here:

http://plnkr.co/edit/FKpzUqZYYSbYcpxDqgmn?p=preview
