### ISSUE TITLE
[Bug(s)] UpdateAdapter: What can it Upgrade ?

### ISSUE THREAD

**Issue by palmanis** [angular/angular#8989]
* **I'm submitting a ...**
- [] frustration report

This is my 3rd issue with the UpgradeAdapter. Makes me wonder, what exactly was this written for ? Is it capable of upgrading anything better than a Hello World directive ?
UpgradeAdapter is nowhere close to what is claimed in the documentation, it has way too many limitations and bugs for it to be of any effective use.
And i am expecting, no different response, this time as well, i.e. nobody is going to pick this up or even acknowledge this.
Previous Issues:
#8856 and #8304 

**Current behavior**
If an angular 1.0 directive has a function in the templateUrl, and if you try to Upgrade it using the UpgradeAdapter, then it gives 404 error, as assumes that templateUrl is a string (url) and not a function.

**Expected/desired behavior**
The UpgradeAdapter figure out, if templateUrl is a string or a function and take appropriate action.

* **What is the motivation / use case for changing the behavior?**
Motivation is to be able to use the UpgradeAdapter to upgrade our component library. But getting down and dirty with the UpgradeAdapter makes me think what is it capable of upgrading ?

**Other Information**
Here's the [documentation ](https://angular.io/docs/ts/latest/guide/upgrade.html#!#using-component-directives) which DOES NOT state that we cannot have templateUrl as a function.

Here's the code from UpgradeAdapter, clearly shows templateUrl is assumed to be a string.
```javascript
UpgradeNg1ComponentAdapterBuilder.prototype.compileTemplate = function(compile, templateCache, httpBackend) {
      var _this = this;
      if (this.directive.template !== undefined) {
        this.linkFn = compileHtml(this.directive.template);
      } else if (this.directive.templateUrl) {
        var url = this.directive.templateUrl;
        var html = templateCache.get(url);
        if (html !== undefined) {
          this.linkFn = compileHtml(html);
        } else {
          return new Promise(function(resolve, err) {
            httpBackend('GET', url, null, function(status, response) {
              if (status == 200) {
                resolve(_this.linkFn = compileHtml(templateCache.put(url, response)));
              } else {
                err("GET " + url + " returned " + status + ": " + response);
              }
            });
          });
        }
      } else {
        throw new Error("Directive '" + this.name + "' is not a component, it is missing template.");
      }
      return null;
      function compileHtml(html) {
        var div = document.createElement('div');
        div.innerHTML = html;
        return compile(div.childNodes);
      }
    };
```

* **Please tell us about your environment:**

* **Angular version:** 2.0.0-beta.17
 
* **Browser:** [all]

**Comment by marcalj** [comment]
Please, use latest version of Angular 2 first. I'm not having any component/directive with template function but I was able to upgrade some directives/components this week with success (but a lot of pain, due to lack of knowledge about new code). Si this is frustrating, yes, but we're on beta and we need to use the latest code since there's nothing stable yet.

PD: I'm referencing your other last issues, I know template function won't work with RC1 code.

Cheers and code on! :)

**Comment by palmanis** [comment]
Even RC1 has all the issues, that i've raised.

**Comment by CaptainCodeman** [comment]
I found the upgrade adapter almost completely useless for any real application, certainly not worth the effort given that the final app size ends up huge (because both frameworks are loaded).

It seems to kind-of work for very trivial examples or code re-written specifically for it's limitations which makes it rather pointless IMO and a waste of time and effort. I found it quicker to re-write the code for Angular 2 than to re-write it for the upgrade adapter first.

I'm still waiting to see a huge app that successfully runs using both frameworks at the same time.

**Comment by marcalj** [comment]
@CaptainCodeman I'm in the middle of an upgrade effort, do you really think I should go for a big bang strategy directly?
I'm researching all my requirements and I think I can use all third party projects with Angular 2 version, but the complete migration will be longer than a step by step usage with UpgradeAdapter.
Also, do you go with angular-cli right? Thanks!

**Comment by CaptainCodeman** [comment]
@marcalj I can't really answer that - so much depends on your project, timescales, sensitivity to deployment sizes, delays etc... I can only share my own experience and resulting disappointment with the upgrade adapter which for me was a complete waste of time and effort..

I think you need to do a thorough audit first to know whether it will work for all the places you want to use it. Unfortunately, the limitations and issues are not always clear at the outset which can mean you hit a wall. And before people dismiss the issue as being badly written components, let's remember that most of angular's own material components wouldn't work with it either.

**Comment by marcalj** [comment]
I have all my Angular 1 code using TypeScript with classes, with impoty/export defined. Using SystemJS. All directives capable of being components, are components now. I made a huuuge work since now, so maybe will worth going big bang since your experience is totally clear.
Angular-cli doesn't do hash revision of filenames, so it's a kind of stopper for me now... let's see. Thanks!

**Comment by CaptainCodeman** [comment]
I can't comment on the cli build results - I use webpack and rely on the hashed filenames to achieve long caching.

The longer-term future though seems to be using a service worker for caching which is a whole other approach to things.

**Comment by marcalj** [comment]
Absolutely, I'm waiting for this functionality in angular-cli too. But want to start playing now with my build step.

**Comment by palmanis** [comment]
Although going for the big bang approach might be a very difficult one for me right now, as we have a big library of components being used across lot of our internal applications, but even if we think of that, i'm not very sure, if Angular 2.0 is fully ready for that as well. Writing components meant we did lot of transclusion, the kinds where we take in a template from the user and compile it against new scope while looping over data, lot of DOM manipulation both to our internal templates, or to templates provided by the users. 
Maybe i haven't figured out yet, how to do that in ng2 or maybe it isn't even ready for all those sorts of things yet. What brought some of those doubts in my mind were things like #8563 (and not necessarily limited to just this one).

**Comment by marcalj** [comment]
@palmanis Could you inject ng1 services inside an ng2 provider? I cannot find a way to do it.
https://github.com/angular/angular/issues/9132
Thanks!
