### ISSUE TITLE
Confusing naming in component decorator

### ISSUE THREAD

**Issue by mbeckenbach** [angular/angular#9007]
* **I'm submitting a ...**
- [x] feature request

**Current behavior**
Naming of the properties "providers" and "directives" is confusing.

**Expected/desired behavior**
Providers should be named Services and Directives should be named Components ir splittet into Components and Directives

* **What is the expected behavior?**
The same as now but with some naming that is easier to understand.

* **What is the motivation / use case for changing the behavior?**
Ng2 should be a lot easier to learn than ng1 and its great as far as i've used it. But placing the name of a service in a property called providers feels just like in ng1 "A service is a factory, which is actually a provider that returns a service". (is it in this order? :))

Same is for the directives. Someone new to angular will read the docs and find out, that there are structural "directives" and components which are actually directives with a template. But will someone new to angular create structural directives? Maybe, but most of the time it will be components. So why should he write his component names into a property called directives?

This feels like exactly the strange and confusing naming hell that we had ng1. And I guess this is not easy to change without breaking changes as soon as ng2 is finally released.

So, to make ng2 a lot more intuitive, please think about renaming parts that need to be explained in docs, told by teachers and remembered by developers only because of the naming.

* **Please tell us about your environment:**

* **Angular version:**
Whatever is currently on npm. :)
 
* **Browser:** 
All
 
* **Language:** 
Typescript, but I guess this is targeting all languages.

**Comment by pkozlowski-opensource** [comment]
@mbeckenbach what would be your proposal for alternative naming? Given your proposal do you think it would justify breaking changes?

**Comment by mbeckenbach** [comment]
For now I've not figured out why the "providers" property is called providers as the only thing I added here are services. So simply renaming this one into "services" should be easy. If there is really a difference in meanings between a provider and a service, splitting the property into two properties should "providers" and "services" should be considered. 

Same goes for the "directives" property. It should be easy to split it into "directives" and "components" which would be merged back into a single property by angular on background as long as angular does not do different magic on those types of classes. The "components" property should take anything that has a template and is used by placing html elements, while directives should take everything that's used by using attributes like *ngIf.

The breaking change for both should be easy to be fixed for developers by simply renaming some properties in the used decorators. Or there could be some fallback mechanisms in angular to allow the current and my proposal.

**Comment by zoechi** [comment]
`providers` is just a more abstract name than `services`. `services` isn't used anywhere in Angular code, or is it? AFAIK, services is just a term used when talking about classes that are injected.
DI is used throughout the whole application for all kinds of things, not only for services. Services is the most obvious thing where DI is used by developers that build Angular applications. The more you know about Angular, the more logical these terms will become to you.

`Component` extends `Directive` which means A component **is** a directive that also happens to hav a view. When you got more familiar with Angular2 this will probably not be confusing anymore.

"Simple renaming" sounds nice but there are a few thousand developers using Angular2 since about a year who are used to these terms and they already had to endure some renamings AFAIR. I guess they won't be happy. I wouldn't be ;-)

**Comment by mhevery** [comment]
`providers` is the standard terminology in DI systems. Services are too specific to angluar, also `providers` can refer to `directives` sometimes.

`directives` can refer to both `components` and `directives` and a `component` is a kind of directive.

Sorry, but it is not compelling enough to change.
