### ISSUE TITLE
Problem loading angular2-in-memory-web-api 

### ISSUE THREAD

**Issue by lroca88** [angular/angular#9037]
* **I'm submitting a ...**
- [x] bug report
- [ ] feature request
- [ ] support request => Please do not submit support request here, see note at the top of this template.

**Current behavior**
I couldn't get the tutorial chapter 7 finished. ([https://angular.io/docs/ts/latest/tutorial/toh-pt6.html](url))
`Error: XHR error (404 Not Found) loading http://localhost:3000/node_modules/angular2-in-memory-web-api`
**Expected/desired behavior**

In **package.json** set:
'`angular2-in-memory-web-api': '0.0.10'`
in the dependecies block, and in **systemjs.config.js** set
`'angular2-in-memory-web-api': { main: 'index.js', defaultExtension: 'js' }`
in the packages object.

See: [http://stackoverflow.com/questions/37377529/angular2-tutorial-tour-of-heroes-cannot-find-module-angular2-in-memory-web-a](url) for more details.

* **If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem** via

Just follow the chapter 7 in the tutorial and check the http server's log. You will see the error described above.

* **What is the expected behavior?**

* **What is the motivation / use case for changing the behavior?**

* **Please tell us about your environment:**

* **Angular version:** 2.0.0-beta.X 
 
* **Browser:** [all] 
 
* **Language:** [TypeScript X.X]

**Comment by yaroslavOshyyko** [comment]
Also with` 'angular2-in-memory-web-api': '0.0.9'` is working well.
 I changed `'angular2-in-memory-web-api': { defaultExtension: 'js' }` to 
`'angular2-in-memory-web-api': { main: 'index.js', defaultExtension: 'js' } `and for me is working fine.

**Comment by elenigen** [comment]
This issue shouldn't be closed, the problem is still present.

> UPDATE NOTICE
> 
> As of v.0.1.0, the npm package was renamed from angular2-in-memory-web-api to its current name, angular-in-memory-web-api. All versions after 0.0.21 are shipped under this name. Be sure to update your package.json and import statements.

From: https://github.com/angular/in-memory-web-api

**Comment by getneil** [comment]
the fix in my end is making sure that HttpModule is added first before InMemoryWebApiModule

```js
  imports: [
    BrowserModule,
    FormsModule,
    AppRoutingModule,
    HttpModule, // sequence is important define HttpModule first before InMemory
    InMemoryWebApiModule.forRoot(InMemoryDataService),
  ],
```

**Comment by MojtabaGhavidel** [comment]
so how can it be fixed? i'm trying to make Tour of Heroes Part7 work.

**Comment by e-hein** [comment]
I think I had the same issue and solved it:

For me it only happend during testing code with karma (npm test instead of npm start). If your's also occurs on running npm start ... sorry, my solution won't work for you.

If it happens on npm test:
update karma.conf.js by adding
`'node_modules/angular-in-memory-web-api/bundles/in-memory-web-api.umd.js',`
to the files section. You should also add
`{ pattern: 'node_modules/angular-in-memory-web-api/**/*.js', included: false, watched: false },` to the same section to prevent watching those files. And don't forget the separating commas. 

After solving this problem I had another one with an missing APP_BASE_HREF (jasmine doesn't use the index.html), but this one is easy to solve by adding
`{ provide: APP_BASE_HREF, useValue:  "/" }`
to the providers (I did it in the app-routing.module).

**Comment by kiwi-lifter** [comment]
I was getting the "GET http://localhost:3002/api/heroes  404 Not Found error".

getneil's fix - HTTPmodule first in sequence worked for me.

**Comment by notbenj** [comment]
I have the same issue, I can't finish the chapter 7 of the tutorial...

Why is this closed?

**Comment by wilee53** [comment]
Here is what worked for me:  In packages.json, add the dependency 

  "angular-in-memory-web-api": "^0.2.0"

then, npm install and npm start.  Note that I used angular-cli to build the app, so there is no systemjs...  That's all I had to do, specifically there were no changes in the tutorial code.

**Comment by notbenj** [comment]
Thanks for the answer.

I also used angular-cli to create the project in which I followed the tutorial, hence the issue.

I think I understand why this issue was closed: the official tutorial probably assumes the user has started the project manually and not from the angular-cli.

However, the previous chapter in the official Angular website is about angular-cli, so I'm sure I won't be the last one having this issue.

I suggest the following paragraph to be added to the tutorial:
"If you used angular-cli to create the project, you need to execute the following command: 
npm install angular-in-memory-web-api --save"

What do you think? If it makes sense, could it be added?

**Comment by s17t** [comment]
I also stumbled upon this issue coming from angular-cli. You should fix this either in angular-cli or in the documentation.

Like @wilee53, adding `"angular-in-memory-web-api": "^0.2.0"` in `package.json` fix the problem.

**Comment by skonx** [comment]
like @wilee53 using ng cli: npm install angular-in-memory-web-api and that's all folks. cheers.

**Comment by skonx** [comment]
Hi tleveque23. Did you enter this command in your ng project folder? Did you import/provide angular-in-memory-web-api as well? Silent error seems you don't really use it. My bet.

**Comment by skonx** [comment]
this is my app.module.ts after having finished the tutorial : 

```
import { BrowserModule } from '@angular/platform-browser';
import { NgModule } from '@angular/core';
import { FormsModule } from '@angular/forms';
import { HttpModule } from '@angular/http';

import { AppRoutingModule } from './app-routing.module';

// Imports for loading & configuring the in-memory web api
import { InMemoryWebApiModule } from 'angular-in-memory-web-api';
import { InMemoryDataService } from './in-memory-data.service';


import { AppComponent } from './app.component';
import { HeroDetailComponent } from './hero-detail.component';
import { HeroesComponent } from "./heroes.component";
import { HeroService } from "./hero.service";
import { DashboardComponent } from './dashboard.component';
import { HeroSearchComponent } from './hero-search.component';

@NgModule({
  declarations: [
    AppComponent,
    HeroesComponent,
    HeroDetailComponent,
    DashboardComponent,
    HeroSearchComponent
  ],
  imports: [
    BrowserModule,
    FormsModule,
    HttpModule,
    InMemoryWebApiModule.forRoot(InMemoryDataService,{ delay: 100 }), //default delay is 500ms
    AppRoutingModule
  ],
  providers: [HeroService],
  bootstrap: [AppComponent]
})
export class AppModule { }

```

**Comment by tleveque23** [comment]
Yes to all your questions. The dependencies is added in my package.json.
And my app.module.ts is really really similar to yours. Except for the "delay" argument.

**Comment by skonx** [comment]
In my package.json I have "angular-in-memory-web-api": "^0.3.2" instead of your "angular-in-memory-web-api": "latest"

**Comment by tleveque23** [comment]
Yes it is just something I tried, but it was like yours before....

**Comment by skonx** [comment]
Could you please check if you have installed the module angular-in-memory-web-api in node_modules folder?

**Comment by tleveque23** [comment]
Yes it is there. If it was not, should it not log an error at runtime?

**Comment by skonx** [comment]
it should but this an experimental package as guess. I will test the behavior of your code later today. Keep in touch.

**Comment by tleveque23** [comment]
Thanks!

**Comment by skonx** [comment]
I was fed up to debug a Karma test with Angular Material so I've switched on your project with a cup of tea and I guess I've got it... why do you encapsulate a new Promise instead of using the Promise provided by the get method?

```
getHeroes(): Promise<Hero[]> {

    console.log("getHeroes method");

    return new Promise(resolve => {
      return this.http.get(this.heroesUrl)
        .toPromise()
        .then(response => response.json().data as Hero[])
        .catch(this.handleError);
    });
  }
```
You should implement getHeroes() like this : 
```
getHeroes(): Promise<Hero[]> {

    console.log("getHeroes method");

      return this.http.get(this.heroesUrl)
        .toPromise()
        .then(response => response.json().data as Hero[])
        .catch(this.handleError);
  }
```
Maybe a simple mistake during a copy/paster.

Cheers.

**Comment by tleveque23** [comment]
Forget it. I found the problem. When I copied the new code to my service, my IDE (IntelliJ) just replace a return this.http... by a return new Promise(....

**Comment by skonx** [comment]
You should use visual studio code LOL

**Comment by anandrikka** [comment]
If you are using systemjs. update map variable to include "'angular-in-memory-web-api': 'node_modules/angular-in-memory-web-api/bundles/in-memory-web-api.umd.js'". It's working for me
