### ISSUE TITLE
Component lifecycle events are not fired when router.navigate is called from within an observable subscription

### ISSUE THREAD

**Issue by justinrassier** [angular/angular#9039]
* **I'm submitting a ...**
- [x] bug report
- [ ] feature request
- [ ] support request => Please do not submit support request here, see note at the top of this template.

**Current behavior**
We have a unique situation where we have an Angular 2 app existing within an iframe. We want to be able to utilize routing of the iframe application, even from the parent window. To do this, we hooked up a service that sits on the parent's window object where the internal frame can subscribe to route change requests. When the outside frame requests a route change, it notifies the internal app via an observable, which then uses the injected router to complete the route change.

The problem is that when the parent frame requests a route change, the inner app successfully gets notified, and routes to the requested child route, but the component's lifecycle hooks (e.g. onInit) does not get fired. This is not a problem when you use the router within a router link, or even within a button click even handler from within the same app.

I know this is a weird situation, but it is possible that some other asynchronous event that is supposed to trigger a route change could have the same issue, although I haven't tried to reproduce that.

**Expected/desired behavior**
I would expect that the component's lifecycle events get fired when the route completes, even if that route request happened from some external event.

* **If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem** via
I have recreated the issue at this plunker: https://plnkr.co/edit/gFLrPqB4GBENQuHuU6TO?p=preview

* **What is the expected behavior?**
That the child component gets initialized properly

* **What is the motivation / use case for changing the behavior?**
We need the child components to be initialized even if the route is navigated by some asynchronous external event.

* **Please tell us about your environment:**

* **Angular version:** 2.0.0-rc.1
 
* **Browser:** [all ] 
 
* **Language:** [ TypeScript 1.8.10]

**Comment by zoechi** [comment]
This are two individually bootstrapped Angular applications where each one has its own zone.  
If an observable emits a value, it does it in the zone of the source application and the callback of the subscriber in the target application is also run in the zone of the source application. This way the target application (iframe) doesn't run change detection.

In the target application (where you subscribe) inject `constructor(private zone:NgZone) {}` and in the subscribe call `...subscribe(value => { this.zone.run(() => {this.prop = value; this.router.navigate(); ...})})` and lifecycle methods will be called.

The problem is quite similar to the one in http://stackoverflow.com/questions/37657779/sharing-service-between-2-applications-on-same-page-not-updating-bindings/37658509#37658509

GitHub issues are for bug reports and feature requests.
    For support questions please use other channels like the ones listed in [CONTRIBUTING - Got a Question or Problem?](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question)

**Comment by justinrassier** [comment]
@zoechi Thanks for the info! I thought I did my homework on other issues or support questions, but wasn't exactly sure what was causing the problem I was having, and thought it may be a bug with the router. I am a bit unfamiliar with the zones pieces of the change detection, and now have some homework to do.

Thanks again!
