### ISSUE TITLE
Animations cannot be set via `@host` or `Component.host`

### ISSUE THREAD

**Issue by matsko** [angular/angular#9044]

**Comment by xsilen** [comment]
the problem @host can't work always exist in systemjs(i don't know others). its because circle dependence. `@host() parent: parentComponent`, parentComponent is always `undefined`. but `@host() parent: forward(()=>parentComponent)` can work, though it cause typescript compile error.

in order to fetch parent componet in sub component constructor, i modified ng2 code.https://github.com/ridecrafty/angular/commit/0e66092b6d99a7e93bac00b11735890a1b7ef9cf

**Comment by colinkahn** [comment]
@matsko curious if this will solve a problem I'm having where when adding components using `DynamicComponentLoader.loadNextToLocation` and then removing them using `ViewContainerRef.clear` animations do not fire. I'm assuming the animations don't work because the trigger needs to be on the removed component host itself.

Here's an example:
https://plnkr.co/edit/Gba4dzuHIArG6rN4LYAd?p=preview

**Comment by zoechi** [comment]
`DynamicComponentLoader` is deprecated. https://plnkr.co/edit/f8OY6ATuRIgsf1xYmxBO?p=preview using `ViewContainerRef.createComponent()` instead results in an animation exception (I don't know animations yet)

**Comment by colinkahn** [comment]
@zoechi thanks for updating the plunker. I'm not seeing the error though (Chrome Version 51.0.2704.106 (64-bit)).

**Comment by zoechi** [comment]
> TypeError: Failed to execute 'animate' on 'Element': 'null' is not a valid value for easing

`52.0.2743.24 (Official Build) beta (64-bit)` Linux

**Comment by colinkahn** [comment]
Looks like an animation bug w/ Linux. This works fine on Mac.

**Comment by matsko** [comment]
@zoechi that bug was fixed with #9780 and will be apart of RC5 For now just use `linear` as the easing with setting a timing (e.g. `animate(1s linear, style(...))`).
