### ISSUE TITLE
Alternative to {{double curly braces}}

### ISSUE THREAD

**Issue by yjaaidi** [angular/angular#9086]
Hi !
I'm looking for an alternative to curly braces for binding. Something like ng-bind.
I was using "[innerText]" which is almost perfect except that if the value is undefined it displays "undefined" like back in the 90's. While if the value is null it displays nothing (empty string).

Is it possible to avoid serializing undefined when binding to innerText property?

Thank you in advance for your help!

**Comment by zoechi** [comment]
Can you provide a plunker that demonstrates where this causes you troubles?

**Comment by yjaaidi** [comment]
Yes! Sorry.
http://embed.plnkr.co/jCkcxD/

**Comment by zoechi** [comment]
I agree this is weird behavior. Also `{{name || ''}}` or `{{name ? name : ''}}` doesn't work.
The best workaround I come up so far was a pipe like `{{name | undef}}` http://plnkr.co/edit/CIAXgm?p=preview
The pipe can be made globally available so it doesn't need to be added to each component where it's used.

**Comment by vicb** [comment]
What is wrong with `{{name}}` ?

**Comment by vicb** [comment]
Also you can do `[innerText]='strValue'` where `strValue` is a getter that return `value || ''`

**Comment by zoechi** [comment]
I guess the problem is when `name === undefined` to not print `'undefined'` but `''`

**Comment by yjaaidi** [comment]
@vicb Hello Victor,
Can you reopen the issue? As a I don't think that this is a long term solution. I can't write a getter for each property used by my view.

Thank you @zoechi for your proposition but I would love to have something native.

The problem with the {{double curly braces}} is that it's too generic. Many templating systems use this and if the files are parsed by something else before, it might be replaced.
The other issue is that before angular is loaded the curly braces are not replaced. 
One of my favorite examples is http://ui-grid.info/docs/#/api where you can see {{name}} on the toolbar before the angular is loaded. Looks messy...

Anyway, AngularJS had ng-bind as an alternative and we need the same thing for Angular 2.

Thank you in advance!

**Comment by mhevery** [comment]
Could you formulate an argument as to why you think that `{{undefined}}` should render to empty string? What about `{{null}}` or `{{false}}`

NOTE: `[foo]="undefined"` must assign `undefined`.

**Comment by yjaaidi** [comment]
@mhevery Hi Misko!

I just updated my plunker https://embed.plnkr.co/jCkcxD/. I just want to [innerText] to have the same behaviour as {{double curly braces}}.
As you can see on the plunker, there's a different behaviour between [innerText] and {{double curly braces}}.

[innerText]="undefined" displays an empty string while [innerText]="data",  where data is undefined, displays "undefined".

Isn't that weird?

**Comment by pkozlowski-opensource** [comment]
> Isn't that weird?

Try this in your favourite browser:

```javascript
var myDiv = document.createElement('div');
myDiv.innerHTML = undefined;
console.log(myDiv); // in chrome it prints <div>undefined</undefined>
```

Why it matters? Because this is _exactly_ what `[innerText]="undefined"` does! So in the end it a browser that turns `undefined` to `"undefined"`.

Could we make it better? Probably! But this would involve have a list of _all_ DOM properties where browsers do conversion to string. And we would have to in a generic way. There is a proposal for a property binding interception in #3929 already, and it could cover this use-case. Or you could register an alternative DOM renderer that takes care about those property conversion.

**Comment by mhevery** [comment]
`[]` can not have the same behavior as `{{}}` because it is a different thing `[]` means bind value where as `{{}}` means interpolate to string.

**Comment by yjaaidi** [comment]
I understand that but then what's the Angular 2 alternative for `ng-bind`?
I would really love to avoid using `{{}}`

**Comment by zoechi** [comment]
What's the problem again with `{{}}`?

**Comment by zoechi** [comment]
and with the proposed alternative `[innerText]='strValue'`?

**Comment by yjaaidi** [comment]
Why I don't want to use `{{}}`:

1 - This syntax is too common and might collide with other templating languages.

2 - It needs an "ng-cloak" hack if used on the `index.html`. What about `<head><title></title></head>`? `<title>`'s display is already none so it won't change anything and meanwhile Angular is bootstrapping, the page's title will be "{{pageTitle}}". Ugly isn't it?

3 - It encourages developers to do things like this: `<div>Hello, {{user.firstName}} {{user.lastName}}</div>` while I think that `<div><span>Hello, </span><span [innerText]="user.firstName"><span [innerText]="user.lastName"></div>` which is ok more verbose but cleaner and more extensible as you can apply a style to the last name's span in order to make it bold or something.

4 - Protractor's binding selector is quite magic and can find `{{user.firstName}}` but what if we have two bindings in the same element... and what if some developer is not using protractor? Testing/parsing/scraping libraries can easily find elements by attribute but they will not find the `{{}}`.

5 - `{{}}` is error-prone. What happens if there is a typo? `{{user.firstName}` or `{{user.firstName} }`, well it's just ignored and this will display "{{user.firstName}" or "{{user.firstName} }". Meanwhile typos in the `[innerText]` attribute will trigger errors.
UNIX Ruleof Repair:
> Developers should design programs that fail in a manner that is easy to localize and diagnose or in other words “fail noisily”. This rule aims to prevent incorrect output from a program from becoming an input and corrupting the output of other code undetected.


The only issue with `[innerText]` is how it handles "undefined" value is the browser's behaviour is to display "undefined" which IMHO is a bad browser behaviour.

So, I think that we need an `ngBind` directive that simply wraps `[innerText]` and handles undefined correctly.

**Comment by zoechi** [comment]
1 - There was a recent change to support different delimiters than `{{}}` AFAIK.

2 - `{{}}` or any other Angular binding doesn't work outside the Angular application anyway and an Angular2 application can't be outside `<body></body>`. You might have a look at the `Title` service.

3 - 

4 - Protractor won't be able to see any `{{}}` because these never exist in the DOM

5 - 

Just create your own `ngBind` directive that replaces `undefined` by `''`. This might be worth adding to Angular but is also quite easy to work around. If you register it with 

    provide(PLATFORM_DIRECTIVES, {useValue: [MyNgBind], multi: true})

Then it's available globally in your Angular2 application.

**Comment by yjaaidi** [comment]
Thanks @zoechi.

2 - I was talking about `ngBind` vs `{{}}` in general as in AngularJS I bootstrap the app on the document instead of the body.
4 - Yup! Exactly! By the way, the `[innerText]` attribute is removed too. 

Thanks for the solution but I would really love to have something native. Am I the only one interested?

**Comment by zoechi** [comment]
>  I bootstrap the app on the document instead of the body.

In Angular2?

**Comment by yjaaidi** [comment]
With AngularJS. More precisely, an hybrid ng1/ng2 app. But I didn't try with Angular 2 yet.

Quite dirty but it works.

`upgradeAdapter.bootstrap(document.body.parentElement, ['app']);`

**Comment by yjaaidi** [comment]
Actually, with Angular 2 it shouldn't be possible as the root element is the root component.
Except if the root component selector is 'html' and if it's using projection... Oh my god, that would be so dirty... :)

**Comment by nissimlevy** [comment]
My {{}} binding is not working. In the console I see the followin error:

Error: Uncaught (in promise): Error: Error in ./SalesforceDataComponent class SalesforceDataComponent - inline template:15:29 caused by: Cannot read property 'orgName' of undefined
TypeError: Cannot read property 'orgName' of undefined

However I console logged the object that I am binding the orgName property from and it is loaded properly.

Below are the versions I'm on:


angular-cli: 1.0.0-beta.28.3
node: 6.10.0
os: win32 x64
@angular/common: 2.4.9
@angular/compiler: 2.4.9
@angular/core: 2.4.9
@angular/forms: 2.4.9
@angular/http: 2.4.9
@angular/platform-browser: 2.4.9
@angular/platform-browser-dynamic: 2.4.9
@angular/router: 3.4.9
@angular/compiler-cli: 2.4.9


Please help

**Comment by nissimlevy** [comment]
My {{}} binding is not working. In the console I see the followin error:

Error: Uncaught (in promise): Error: Error in ./DataComponent class DataComponent - inline template:15:29 caused by: Cannot read property 'orgName' of undefined
TypeError: Cannot read property 'orgName' of undefined

However I console logged the object that I am binding the orgName property from and it is loaded properly (not undefined). 

Below are the versions I'm on:

angular-cli: 1.0.0-beta.28.3
node: 6.10.0
os: win32 x64
@angular/common: 2.4.9
@angular/compiler: 2.4.9
@angular/core: 2.4.9
@angular/forms: 2.4.9
@angular/http: 2.4.9
@angular/platform-browser: 2.4.9
@angular/platform-browser-dynamic: 2.4.9
@angular/router: 3.4.9
@angular/compiler-cli: 2.4.9

Please help
