### ISSUE TITLE
router-deprecated HashLocationStrategy broken

### ISSUE THREAD

**Issue by jbeckton** [angular/angular#9099]
* **I'm submitting a ...**
- [x ] bug report
- [ ] feature request
- [ ] support request => Please do not submit support request here, see note at the top of this template.

**Current behavior**
using HashLocationStrategy the hash is not present in the url, if I add it manually and then navigate it goes away. Seems like the PathLocationStrategy is being forced. When i refresh I get 404 from the server because I cannot set up redirects required for the PathLocationStrategy

**Expected/desired behavior**
I expected the HashLocationStrategy in RC-1 to work like it did in Beta.13

http://plnkr.co/edit/lrdhAzsiICN4Fu57Mkp7?p=preview

added provide(LocationStrategy, {useClass: HashLocationStrategy}) to the bootstrap routine.
click the icon to "Launch the preview in a separate window".
Note that the url does not contain a hash. 
right click on the page in the new window and select Reload, server returns a 404 error since /dashboard is not a valid path on the server. The server could be set up to fix this but in my case I cannot.

* **What is the motivation / use case for changing the behavior?**
not everyone can set up redirects on their web server to support the HTML 5 paths style routing. The Hash Strategy used to work prior to RC-1

* **Please tell us about your environment:**

* **Angular version:** 2.0.0 RC-1
 
* **Browser:** 
Chrome on CentOs & Node.js
 
* **Language:** [ TypeScript | ES5 ]

**Comment by zoechi** [comment]
The default `LocationStrategy` is provided by `ROUTER_PROVIDERS`. If you provide your custom `LocationStrategy` in `bootstrap()` and `ROUTER_PROVIDERS` in `AppComponent` your custom provider is overridden. You need to provide `LocationStrategy` **after** `ROUTER_PROVIDERS`

http://plnkr.co/edit/tm4UCaG6bTJxNZaODMt6?p=preview

**Comment by b3kN** [comment]
I believe @zoechi is correct, there is no declaration of a class to use in the providers however there is an attempt to override it in the `bootstrap`. @zoechi's [plunker](http://plnkr.co/edit/tm4UCaG6bTJxNZaODMt6?p=preview) example does it justice, but I'll interpret a bit more as well.

More or less the `LocationStrategy` code should be in the providers rather than directly in the bootstrap, but all the right steps exist... 

[HashLocationStrategy](https://angular.io/docs/ts/latest/api/common/index/HashLocationStrategy-class.html) displays use of override in the example, but since `providers` is implemented in the `app.component.ts` file, but the provide in the `bootstrap` is going to be troublesome.

`Providers` in the original `app.component.ts` only lists `ROUTER_PROVIDERS`:
```
providers: [
  ROUTER_PROVIDERS,
  HeroService
]
```

@zoechi updated the plunker at line 24 to specify the class:
```
providers: [
  ROUTER_PROVIDERS,
  provide(LocationStrategy, {useClass: HashLocationStrategy}),
  HeroService
]
```

Remove `provide` override for `LocationStrategy` from `bootstrap` in main.ts:
```
bootstrap(AppComponent, [
  HTTP_PROVIDERS,
  provide(XHRBackend, { useClass: InMemoryBackendService }), // in-mem server
  provide(SEED_DATA,  { useClass: InMemoryDataService })     // in-mem server data
]);
```

The imports could be cleaned up on `app.component.ts` and `main.ts` but otherwise this should do the trick.

**Comment by pkozlowski-opensource** [comment]
Thnx so much @zoechi  and @b3kN for helping out with the support issues! This is very, very much appreciated!

@jbeckton please use a dedicated support forums for this types of questions: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question

**Comment by jbeckton** [comment]
Thanks guys, this fixed my issue with the router.
