### ISSUE TITLE
[Core] Could APP_INITIALIZER depend on ApplicationRef ? 

### ISSUE THREAD

**Issue by vicb** [angular/angular#9101]
Right now `APP_INITIALIZER`s can not have a dependency on `ApplicationRef` because the initializers are executed in `ApplicationRef_` ctor.

Would there be a way to allow such a dep ? (ie execute the initializers after the `ApplicationRef_` is constructed ?)

/cc @tbosch @vsavkin 

_(the use case is APP_INITIALIZER -> Router -> AppRef)_

**Comment by gdi2290** [comment]
@vicb can you take a look at #9110 that allows for this

**Comment by tbosch** [comment]
We could change this.
However, there is a more general problem to solve: If the router should be provided at a component (and not to the `bootstrap` call), app initializers won't run any more. A possible solution would be to support `Provider.eager`...

**Comment by tbosch** [comment]
Reviewed https://github.com/angular/angular/pull/9110 and added some comments. But it is the right change for now, as adding eager providers would be a bigger change...

**Comment by gdi2290** [comment]
it seems like we just need more lifecycle hooks for platform/application (sometime like: beforebootstrap, afterbootstrap, beforetick, aftertick)

**Comment by Kar0t** [comment]
Just to point out an issue created by this one. When we try to navigate in the OnInit function of the RootComponent, the navigate event is cancelled.  This happen because the method initialNavigation() on Router is called after the initialization of the RootComponent and cancelling the current ongoing navigation event.  This is caused by the setTimeout() here https://github.com/angular/angular/blob/master/modules/@angular/router/src/common_router_providers.ts#L54-L61.

It should be fix with this issue with the increase of lifecycle hooks (or whatever strategy you guys intent to do)

**Comment by laco0416** [comment]
After introducing `AppModule`, we maybe want something lifecycle method like `ngModuleLoaded` in a module class.

**Comment by tbosch** [comment]
Modules are eager, i.e. their constructor can be used as an app initializer
as well.
