### ISSUE TITLE
Using NgModel and NgControl on Radio button causes TypeError: _this._state is undefined

### ISSUE THREAD

**Issue by divyakumarjain** [angular/angular#9153]
* **I'm submitting a ...**
- [x] bug report
- [ ] feature request
- [ ] support request => Please do not submit support request here, see note at the top of this template.

**Current behavior**
Using NgModel and NgControl on Radio button causes following issue in console.

```TypeError: _this._state is undefined``` in Firefox
```TypeError: Cannot read property 'value' of undefined``` in chrome

**Expected/desired behavior**
Toggling of Radio button should work.

* **If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem** via
http://plnkr.co/edit/1G2mPd

* **What is the expected behavior?**
Toggling of Radio button should work.

* **Angular version:** 2.0.0-rc.1 
 
* **Browser:** [all] 
 
* **Language:** [all]

**Comment by divyakumarjain** [comment]
Have updated the plnkr to include a text input which works but radio button does not.

http://plnkr.co/edit/1G2mPd?p=preview

**Comment by divyakumarjain** [comment]
Following is the smallest plnkr where i can reproduce the issue.

http://plnkr.co/edit/p4vyND

**Comment by zoechi** [comment]
That's because you bind `ngModel` to a property that doesn't exist. For `<input type="radio">` it needs to hold a `RadioButtonState` otherwise it throws when it accesses the value `theModel.value`.

If you want a default value, then assign it to the model (`[(ngModel)]="model"`). As far as I know `[(ngModel)]="..."` and `[value]="..." together usually don't produce the result you want.

`@Output()` is only for `EventEmitter`, not for arbitrary properties.

Either 
```
/* @Output() */ model = {"details": {"title": "mr"}, "name": "Developer"};
```
or

```
@Output() modelChange = new EventEmitter(); /* model = {"details": {"title": "mr"}, "name": "Developer"}; */
```

GitHub issues are for bug reports and feature requests.
    For support questions please use other channels like the ones listed in [CONTRIBUTING - Got a Question or Problem?](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question)

**Comment by divyakumarjain** [comment]
@zoechi plunk http://plnkr.co/edit/p4vyND has issue so please look at http://plnkr.co/edit/1G2mPd

**Comment by divyakumarjain** [comment]
Each ```<Input type="radio``` should have its own model of type RadioButtonState. Binding ```value``` to model is not supported

**Comment by zoechi** [comment]
Plunker that at least doesn't produce exceptions http://plnkr.co/edit/1apvt8?p=preview
