### ISSUE TITLE
Angular2 RC1 loading issue zone.js 323

### ISSUE THREAD

**Issue by loutocky** [angular/angular#9171]
I am trying to update my application from Angular 2 beta 18 to Angular2 RC1, I already changed imports, fix a lot of syntax errors and now, I am getting this error when the app is loading. Also Angular2 quickstart does not work!

```
zone.js:323 Error: (SystemJS) SyntaxError: Unexpected token <
    Evaluating http://localhost:8080/@angular/platform-browser-dynamic
    Error loading http://localhost:8080/app/ts/main.component.js
```

My main components is:

```
import {bootstrap} from '@angular/platform-browser-dynamic';
import {AppComponent} from './app.component';

bootstrap(AppComponent);
```

I found this https://github.com/valor-software/ng2-dragula/issues/274, but I have no idea, what it means, where to search for require etc. Thanks.

**Comment by CaptainCodeman** [comment]
That's often caused by a request for a script being sent a html page (maybe index.html). You should check the requests and responses in the network tab.

**Comment by loutocky** [comment]
All requests are 200 OK, there are any errors in network tab.

**Comment by loutocky** [comment]
This is my index.html file:

```
<html>

<head>
    <base href="/">

    <title></title>

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">


    <!-- 1. Load libraries -->
    <!-- Polyfill(s) for older browsers -->
    <script src="node_modules/core-js/client/shim.min.js"></script>

    <script src="node_modules/zone.js/dist/zone.js"></script>
    <script src="node_modules/reflect-metadata/Reflect.js"></script>
    <script src="node_modules/systemjs/dist/system.src.js"></script>

    <link href="app/css/jquery-ui.css" rel="stylesheet">
    <link href="app/css/bootstrap.min.css" rel="stylesheet">
    <link href="app/css/font-awesome.min.css" rel="stylesheet">
    <link href="app/css/style.css" rel="stylesheet">
    <link href="app/css/bootstrap.login.css" rel="stylesheet">

    <!-- datetimepicker calendar-->
    <link rel="stylesheet" href="node_modules/eonasdan-bootstrap-datetimepicker/build/css/bootstrap-datetimepicker.min.css" />

    <script type="text/javascript" src="node_modules/jquery/dist/jquery.min.js"></script>
    <script type="text/javascript" src="node_modules/moment/min/moment.min.js"></script>
    <script type="text/javascript" src="node_modules/bootstrap/dist/js/bootstrap.min.js"></script>
    <script type="text/javascript" src="node_modules/eonasdan-bootstrap-datetimepicker/build/js/bootstrap-datetimepicker.min.js"></script>

    <!--end datetimepicker calendar-->

    <!-- build:bundlejs -->
    <!-- endbuild -->

    <!-- 2. Configure SystemJS -->
    <!-- build:systemjs -->
    <script>System.config({packages:{app:{format:'register',defaultExtension:'js'}}});System.import('app/ts/main.component').then(null, console.error.bind(console));</script>
    <!-- endbuild -->
</head>

<!-- 3. Display the application -->

<body>
    <zds>Loading...</zds>
</body>

</html>
```

**Comment by CaptainCodeman** [comment]
You should check the requests **_and responses_** in the network tab.

**Comment by templth** [comment]
It's a problem in your SystemJS configuration. This configuration changes a lot between beta and rc versions.

Here is a sample from the 5 minute quickstart (https://angular.io/docs/ts/latest/quickstart.html):

```
var map = {
    'app':                        'app', // 'dist',
    '@angular':                   'node_modules/@angular',
    'angular2-in-memory-web-api': 'node_modules/angular2-in-memory-web-api',
    'rxjs':                       'node_modules/rxjs'
  };
  // packages tells the System loader how to load when no filename and/or no extension
  var packages = {
    'app':                        { main: 'main.js',  defaultExtension: 'js' },
    'rxjs':                       { defaultExtension: 'js' },
    'angular2-in-memory-web-api': { main: 'index.js', defaultExtension: 'js' },
  };
  var ngPackageNames = [ // <-----
    'common',
    'compiler',
    'core',
    'http',
    'platform-browser',
    'platform-browser-dynamic',
    'router',
    'router-deprecated',
    'upgrade',
  ];
  // Individual files (~300 requests):
  function packIndex(pkgName) {
    packages['@angular/'+pkgName] = { main: 'index.js', defaultExtension: 'js' };
  }
  // Bundled (~40 requests):
  function packUmd(pkgName) {
    packages['@angular/'+pkgName] = { main: pkgName + '.umd.js', defaultExtension: 'js' };
  };
  // Most environments should use UMD; some (Karma) need the individual index files
  var setPackageConfig = System.packageWithIndex ? packIndex : packUmd;
  // Add package entries for angular packages
  ngPackageNames.forEach(setPackageConfig);
  var config = {
    map: map,
    packages: packages
  }
  System.config(config);
```

**Comment by loutocky** [comment]
It was necessary to edit some rows of SystemJS conf and now it works, thanks.

**Comment by sqlsolver** [comment]
Having the identical problem, with an Angular 2 app that was working when using a version of systemjs that was included in some class files from Oasis Digital. Since I ripped that out to use the right package I've not been able to get the app back up. It's hosted at [easyofficeforms.com](http://easyofficeforms.com) if anyone wishes to take a look at the source. 

I've spent several hours working on, and reading about System.config - so it could be that - but the other explanation sounds possible too as each module has its template in a separate html file. Here are the request and response headers, and then the actual response from the last file loaded:

**Request Header:**
GET /easyOfficeForms/app/EOFwelcome.ts HTTP/1.1
Host: easyofficeforms.com
Connection: keep-alive
Accept: application/x-es-module, */*
User-Agent: Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/51.0.2704.84 Safari/537.36
Referer: http://easyofficeforms.com/
Accept-Encoding: gzip, deflate, sdch
Accept-Language: en-US,en;q=0.8

**Response Header:**
HTTP/1.1 200 OK
Server: nginx/1.10.0
Date: Wed, 15 Jun 2016 12:22:33 GMT
Content-Type: text/vnd.trolltech.linguist
Content-Length: 344
Connection: keep-alive
Last-Modified: Thu, 26 May 2016 20:16:12 GMT
Accept-Ranges: bytes
Vary: Accept-Encoding
Content-Encoding: gzip

**Response:**
//Angular components
import {provide, Component} from "@angular/core";
import {OnActivate, RouteSegment, ROUTER_DIRECTIVES} from "@angular/router";

@Component({
    selector: "EOFwelcome",
    templateUrl: "/easyOfficeForms/template/EOFwelcome.html",
    directives: [ROUTER_DIRECTIVES]
  })

export class EOFwelcome implements OnActivate {
    private message: string;
//todo: change who to day of week and make different greeting each day
    routerOnActivate(curr: RouteSegment) {
        this.message = curr.getParam("who");
    }
}

**My System.config is embedded in the index file and consists of:**
System.config({
              paths: {
                  '*': './',
              },
              transpiler: 'typescript',
              map: {
                  'traceur': './node_modules/traceur/bin/traceur.js',
                  'traceur-runtime': './node_modules/traceur/bin/traceur-runtime.js',
                  'typescript': './node_modules/typescript/lib/typescript.js'
              },
              meta: {
                  'traceur': {
                      format: 'global',
                      exports: 'traceur'
                  },
                  'traceur-runtime': {
                      format: 'global',
                      exports: '$traceurRuntime'
                  },

              },
              packages: {
                  './app': {
                      main: './EOFapp.ts',
                      defaultExtension: 'js'
                  },
                  './ng2-bootstrap': {
                      main: './ng2-bootstrap.js',
                      defaultExtension: 'js'
                  }
              },
              packageNames: [
                  '@angular/common',
                  '@angular/core',
                  '@angular/compiler',
                  '@angular/http',
                  '@angular/platform-browser',
                  '@angular/platform-browser-dynamic'
              ]
          });

**Here's the EOSapp.ts file:**
`/// <reference path="../node_modules/ng2-bootstrap/ng2-bootstrap.d.ts" />
//A2
import {provide, Component} from "@angular/core";
import {bootstrap} from "@angular/platform-browser-dynamic";
import {Http, HTTP_PROVIDERS, Response} from "@angular/http";
import {Title} from "@angular/platform-browser";
import {Router, Routes, OnActivate, RouteSegment, ROUTER_DIRECTIVES, ROUTER_PROVIDERS} from "@angular/router";
import {CORE_DIRECTIVES, FORM_DIRECTIVES, LocationStrategy, HashLocationStrategy} from "@angular/common";
//rxjs
import {Observable} from "rxjs/Observable";
import "rxjs/add/operator/map";
import "rxjs/add/operator/do";
import "rxjs/add/operator/publish";
//EOF
import {EOFheader} from "./EOFheader";
import {EOFhome} from "./EOFhome";
import {EOFselector} from "./EOFselector";
import {EOFcategory} from "./EOFcategory";
import {EOFwelcome} from "./EOFwelcome";
//node_modules
import {BUTTON_DIRECTIVES, CAROUSEL_DIRECTIVES, DATEPICKER_DIRECTIVES, DROPDOWN_DIRECTIVES, PAGINATION_DIRECTIVES} from 'ng2-bootstrap';

@Component({
    selector: "EOFapp",
    template: `<EOFheader></EOFheader>
<nav class="navbar navbar-default">
    <a class="navbar-brand" [routerLink]="['/home']">Home</a>
    <a class="navbar-brand" [routerLink]="['/welcome']">Welcome</a>
    <a class="navbar-brand" [routerLink]="['/category']">Form Categories</a>
</nav>
<router-outlet></router-outlet>`,
    directives: [EOFheader, EOFhome, EOFselector, EOFcategory, ROUTER_DIRECTIVES, CORE_DIRECTIVES, FORM_DIRECTIVES, BUTTON_DIRECTIVES, CAROUSEL_DIRECTIVES, DATEPICKER_DIRECTIVES, DROPDOWN_DIRECTIVES, PAGINATION_DIRECTIVES],
    providers: [
        HTTP_PROVIDERS,
        ROUTER_PROVIDERS,
        provide(LocationStrategy, { useClass: HashLocationStrategy }),
        Title
    ]
})

@Routes([
    { path: "/home", component: EOFhome },
    { path: "/welcome", component: EOFwelcome },
    { path: "/category", component: EOFcategory }
])


class EOFapp {
    version: string = "Beta"
    constructor(router: Router, title: Title) {
        router.changes.subscribe(() => {
            // fires on every URL change
            title.setTitle(router.serializeUrl(router.urlTree));
        });    
    }
}

class EOFroute implements OnActivate {
    private message: string;

    routerOnActivate(curr: RouteSegment) {
        this.message = curr.getParam("who");
    }
}

// Bootstrap the Angular application. This is NOT the bootstrap.css framework.
bootstrap(EOFapp, [HTTP_PROVIDERS]);`

Here is tsconfig.json, and happy to post any others that may be relevant:
{
  "compilerOptions": {
    "noImplicitAny": false,
    "noEmitOnError": false,
    "removeComments": false,
    "sourceMap": true,
    "target": "es5",
    "module": "commonjs",
    "moduleResolution": "node",
    "experimentalDecorators": true,
    "emitDecoratorMetadata": true
  },
  "exclude": [ "node_modules" ],
  "compileOnSave": true
}

**Comment by sqlsolver** [comment]
@loutocky which rows did you edit?

**Comment by loutocky** [comment]
This is my SystemJS config now, but the changes are based on my structure of application and source code.

```
var map = {
    'app':                        'app', // 'dist',
    '@angular':                   'node_modules/@angular',
    'angular2-in-memory-web-api': 'node_modules/angular2-in-memory-web-api',
    'rxjs':                       'node_modules/rxjs'
  };
  // packages tells the System loader how to load when no filename and/or no extension
  var packages = {
    'app':                        { main: 'ts/main.component.js',  defaultExtension: 'js' },
    'rxjs':                       { defaultExtension: 'js' },
    'angular2-in-memory-web-api': { main: 'index.js', defaultExtension: 'js' },
  };
  var ngPackageNames = [ // <-----
    'common',
    'compiler',
    'core',
    'http',
    'platform-browser',
    'platform-browser-dynamic',
    'router',
    'router-deprecated',
    'upgrade',
  ];
  // Individual files (~300 requests):
  function packIndex(pkgName) {
    packages['@angular/'+pkgName] = { main: 'index.js', defaultExtension: 'js' };
  }
  // Bundled (~40 requests):
  function packUmd(pkgName) {
    packages['@angular/'+pkgName] = { main: pkgName + '.umd.js', defaultExtension: 'js' };
  };
  // Most environments should use UMD; some (Karma) need the individual index files
  var setPackageConfig = System.packageWithIndex ? packIndex : packUmd;
  // Add package entries for angular packages
  ngPackageNames.forEach(setPackageConfig);
  var config = {
    map: map,
    packages: packages
  }
  System.config(config);
```

And index.html:

```
<html>

<head>
    <base href="/">

    <title></title>

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">


    <!-- 1. Load libraries -->
    <!-- Polyfill(s) for older browsers -->
    <script src="node_modules/core-js/client/shim.min.js"></script>
    
    <script src="node_modules/zone.js/dist/zone.js"></script>
    <script src="node_modules/reflect-metadata/Reflect.js"></script>
    <script src="node_modules/systemjs/dist/system.src.js"></script>

    <link href="app/css/jquery-ui.css" rel="stylesheet">
    <link href="app/css/bootstrap.min.css" rel="stylesheet">
    <link href="app/css/font-awesome.min.css" rel="stylesheet">
    <link href="app/css/style.css" rel="stylesheet">
    <link href="app/css/bootstrap.login.css" rel="stylesheet">

    <!-- datetimepicker calendar-->
    <link rel="stylesheet" href="node_modules/eonasdan-bootstrap-datetimepicker/build/css/bootstrap-datetimepicker.min.css" />

    <script type="text/javascript" src="node_modules/jquery/dist/jquery.min.js"></script>
    <script type="text/javascript" src="node_modules/moment/min/moment.min.js"></script>
    <script type="text/javascript" src="node_modules/bootstrap/dist/js/bootstrap.min.js"></script>
    <script type="text/javascript" src="node_modules/eonasdan-bootstrap-datetimepicker/build/js/bootstrap-datetimepicker.min.js"></script>
    <!--end datetimepicker calendar-->

    <!-- build:bundlejs -->
    <!-- endbuild -->

    <!-- 2. Configure SystemJS -->
    <script src="systemjs.config.js"></script>
    <script>
      System.import('app').catch(function(err){ console.error(err); });
    </script>


</head>

<!-- 3. Display the application -->

<body>
    <zds>Loading...</zds>
</body>

</html>
```

Hope it helps.

**Comment by sqlsolver** [comment]
@loutocky Thanks for your quick post. I don't see anything there that seems to apply to my app though.
