### ISSUE TITLE
Add migration instructions as jsdocs to all currently deprecated apis

### ISSUE THREAD

**Issue by IgorMinar** [angular/angular#9239]
good example: https://angular.io/docs/ts/latest/api/core/testing/clearPendingTimers-function.html

**Comment by naomiblack** [comment]
I don't think this should be assigned to me... we need API doc content that uses the @deprecated tag in order to populate the migration instructions field. 

design issues with the markers should be filed on angular.io -- I think this will be addressed by the filters we're adding on the main overview, but if not, could you file an issue on angular/angular.io with more info about the user concern you want to address?

**Comment by IgorMinar** [comment]
turns out the we already have this capability, we just need to add the content:

 https://github.com/angular/angular/blob/8eb81b37416da495fb0bacdd7bb46400ea2374bf/modules/%40angular/common/src/pipes/replace_pipe.ts#L38 >>> https://angular.io/docs/ts/latest/api/common/index/ReplacePipe-class.html

**Comment by mhevery** [comment]
We are removing the API instead.
