### ISSUE TITLE
Document browser support / polyfills for final release

### ISSUE THREAD

**Issue by unsafecode** [angular/angular#9252]
* **I'm submitting a ...**
- [ ] bug report
- [x] feature request
- [ ] support request => Please do not submit support request here, see note at the top of this template.

I don't see Safari support explicited anywhere: is it supported anyway?

**Comment by IgorMinar** [comment]
Safari 8. 9.0 and 9.1 are supported: https://travis-ci.org/angular/angular/jobs/138100724#L1022

we run the tests against safari in an optional group of browsers because of network flakiness we've been experiencing lately.

we should however have an official docs page documenting the browser support. @robwormald @StephenFluin can you please help with this?

**Comment by marcalj** [comment]
Please, also add notes about which polyfills need each browser version. I'm targeting IE11+ and I'm not sure if I need complete polyfills or just some of them.
Thanks!

**Comment by aronallen** [comment]
This is really important, Safari is the second most popular browser if you include all device categories. It would also be great show the test results on the repo front page once things are operational.

**Comment by IgorMinar** [comment]
this is being fixed via https://github.com/angular/angular.io/pull/2244
