### ISSUE TITLE
Interpolation breaks sanitization

### ISSUE THREAD

**Issue by kleijnweb** [angular/angular#9253]
After updating to RC2 a component I was using to create iframes is throwing a security exception in Chrome.

**Current behavior**

```
browser_adapter.ts:74EXCEPTION: Error in http://localhost:4200/app/+legacy-iframe/legacy-iframe.component.js class LegacyIframeComponent - inline template:0:8BrowserDomAdapter.logError @ browser_adapter.ts:74BrowserDomAdapter.logGroup @ browser_adapter.ts:85ExceptionHandler.call @ exception_handler.ts:50(anonymous function) @ application_ref.ts:313schedulerFn @ async.ts:140SafeSubscriber.__tryOrUnsub @ Subscriber.ts:240SafeSubscriber.next @ Subscriber.ts:192Subscriber._next @ Subscriber.ts:133Subscriber.next @ Subscriber.ts:93Subject._finalNext @ Subject.ts:154Subject._next @ Subject.ts:144Subject.next @ Subject.ts:90EventEmitter.emit @ async.ts:125NgZone._zoneImpl.ng_zone_impl_1.NgZoneImpl.onError @ ng_zone.ts:134NgZoneImpl.inner.inner.fork.onHandleError @ ng_zone_impl.ts:87ZoneDelegate.handleError @ zone.js:327Zone.runTask @ zone.js:259drainMicroTaskQueue @ zone.js:474ZoneTask.invoke @ zone.js:426
browser_adapter.ts:74ORIGINAL EXCEPTION: Error: unsafe value used in a resource URL contextBrowserDomAdapter.logError @ browser_adapter.ts:74ExceptionHandler.call @ exception_handler.ts:62(anonymous function) @ application_ref.ts:313schedulerFn @ async.ts:140SafeSubscriber.__tryOrUnsub @ Subscriber.ts:240SafeSubscriber.next @ Subscriber.ts:192Subscriber._next @ Subscriber.ts:133Subscriber.next @ Subscriber.ts:93Subject._finalNext @ Subject.ts:154Subject._next @ Subject.ts:144Subject.next @ Subject.ts:90EventEmitter.emit @ async.ts:125NgZone._zoneImpl.ng_zone_impl_1.NgZoneImpl.onError @ ng_zone.ts:134NgZoneImpl.inner.inner.fork.onHandleError @ ng_zone_impl.ts:87ZoneDelegate.handleError @ zone.js:327Zone.runTask @ zone.js:259drainMicroTaskQueue @ zone.js:474ZoneTask.invoke @ zone.js:426
browser_adapter.ts:74ORIGINAL STACKTRACE:BrowserDomAdapter.logError @ browser_adapter.ts:74ExceptionHandler.call @ exception_handler.ts:66(anonymous function) @ application_ref.ts:313schedulerFn @ async.ts:140SafeSubscriber.__tryOrUnsub @ Subscriber.ts:240SafeSubscriber.next @ Subscriber.ts:192Subscriber._next @ Subscriber.ts:133Subscriber.next @ Subscriber.ts:93Subject._finalNext @ Subject.ts:154Subject._next @ Subject.ts:144Subject.next @ Subject.ts:90EventEmitter.emit @ async.ts:125NgZone._zoneImpl.ng_zone_impl_1.NgZoneImpl.onError @ ng_zone.ts:134NgZoneImpl.inner.inner.fork.onHandleError @ ng_zone_impl.ts:87ZoneDelegate.handleError @ zone.js:327Zone.runTask @ zone.js:259drainMicroTaskQueue @ zone.js:474ZoneTask.invoke @ zone.js:426
browser_adapter.ts:74Error: unsafe value used in a resource URL context
    at DomSanitizationServiceImpl.sanitize (dom_sanitization_service.ts:126)
    at DebugAppView._View_LegacyIframeComponent0.detectChangesInternal (LegacyIframeComponent.template.js:32)
    at DebugAppView.AppView.detectChanges (view.ts:255)
    at DebugAppView.detectChanges (view.ts:372)
    at DebugAppView.AppView.detectViewChildrenChanges (view.ts:283)
    at DebugAppView._View_LegacyIframeComponent_Host0.detectChangesInternal (LegacyIframeComponent_Host.template.js:30)
    at DebugAppView.AppView.detectChanges (view.ts:255)
    at DebugAppView.detectChanges (view.ts:372)
    at DebugAppView.AppView.detectContentChildrenChanges (view.ts:275)
    at DebugAppView._View_VspNg2AppComponent0.detectChangesInternal (VspNg2AppComponent.template.js:322)
```

It did not originally have the "register as safe" call (when I was still using RC1, which worked), but I found similar solutions referenced that would be the correct way to do it. Doesn't change anything though, and the URL is far from suspicious right now.
 
```
import { Component } from '@angular/core';
import {DomSanitizationService, SafeResourceUrl} from '@angular/platform-browser';

@Component({
  moduleId: module.id,
  selector: 'legacy-iframe',
  template: '<iframe src="{{ url }}"></iframe>'
})
export class LegacyIframeComponent {
  public url:SafeResourceUrl;

  constructor(private sanitationService:DomSanitizationService) {
    this.url = sanitationService.bypassSecurityTrustResourceUrl('/foo');
  }
}

```

I'd also be content with a workaround for now, like disabling the security altogether..

**Comment by kleijnweb** [comment]
What's interesting is that when I log the value being passed to DomSanitizationServiceImpl.prototype.sanitize(), it shows the value has been casted to a string ("[object Object]").

**Comment by pkozlowski-opensource** [comment]
@kleijnweb you've forgotten to add a link to a plunker with a minimal reproduce scenario: https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-submitting-an-issue

**Comment by vicb** [comment]
Could you please try `[src]=url` and report if this works ?

/cc @mprobst

**Comment by mprobst** [comment]
There are two problems here:

1. [ ] sanitization does not work with interpolation, even if it's effectively a no-op interpolation, we end up with a broken string.
2. [ ] we do not generate a proper error message

I talked to @tbosch, we think the fix is to move interpolation into the sanitization service, and unwrap safe values before concatenation, and not unwrap anything if it's a no-op interpolation (i.e. only the actual value). That should fix this concrete use case.

But that still means that if you do trivial concatenation, you might see problems. E.g. if you have `<a href="{{ id }} ">` (note the trailing whitespace), which is bad user experience. I wonder if we can detect a set of safe interpolations/concatenation operations? /CC @rjamet

**Comment by kleijnweb** [comment]
I've tried taking interpolation out of the equation using @vicb's suggestion to no avail. I'll try to create a Plunker for the issue.

**Comment by kleijnweb** [comment]
Okay, so avoiding interpolation *and* using `bypassSecurityTrustResourceUrl()` makes John a happy boy: http://plnkr.co/edit/2Nl7zbHG0eOyc87juH50?p=preview

**Comment by rjamet** [comment]
For general concatenations, it all boils down to whether safety is kept over concatenation, and if you can sanitize by parts. Angular 1 changes behavior depending on whether there's concatenation or not, and it understands that there's no concatenation in src="{{foo}}" (or rejects concatenations in sensitive contexts: https://github.com/angular/angular.js/blob/master/src/ng/interpolate.js#L310). 

Without trusted pieces and in sanitizable contexts, concatenation then sanitization is safe, and sounds like the good option. You can drop the trust with a warning in the trusted subparts in these cases, or just the sanitization warning might alert developers that something's wrong.

If you want to make use of trusted pieces... The conservative option is to consider something as untrusted if there's untrusted subparts. In all contexts, something can change meanings depending on what's besides it: a script tag is safe to concatenate with a sanitized div, but it won't mean the same thing after a <plaintext> in HTML for instance. It's hard to reason about, since there's always going to be things that change meaning which makes sanitization unreliable, context switches that confuse the template system, or really degenerate cases making things unsafe? Safe concatenations might exist, but they depend on the context you're in, how do you precisely define your safe types, and the paranoia of your framework :/

More practically, I'd consider as trusted:
- untrusted stuff after a trusted/sanitized protocol://fqdn/ in URL context (but that's the same as the untrust-then-sanitize approach)
- spaces before and after in non-urls contexts (covers typos in CSS and HTML, but they have meaning in URLs),

 @xtofian, @koto, any thoughts?

**Comment by xtofian** [comment]
Agree with @rjamet.  The problem is that  the languages we're interpolating into (URLs, HTML, CSS), have very complicated embedding contexts, and whether or not a particular interpolation is safe does not only depend on what we know about the value being interpolated (e.g., based on its type, or a runtime check that's been performed), but also on the context it is being interpolated into.

That context could in many cases be statically inferred; doing so would however require parsing the known prefix of the interpolation.  However, in many cases that's not even possible if there's more than one interpolation; the context that the second one will be interpreted in may depend on the run-time value of the first.

Example: In`<a href="{{a}}{{b}}">`, the context of {{b}} (and hence, how it needs to be sanitized) depends on the value of {{a}}.  If a == 'http://example.com', then {{b}} should be a path.  If a == 'javascript:' however, then {{b}} becomes a javascript expression.

Closure Templates for instance tries to correctly infer the context of substitutions into URL-valued attributes, but IIRC there are a bunch of corner cases like this that it can't cover entirely correctly (and the implementation is [quite hairy](https://github.com/google/closure-templates/blob/master/java/src/com/google/template/soy/parsepasses/contextautoesc/Context.java#L626)).

Amusing (or sad?) aside:  The email notification for @rjamet 's update looked like this:
`[...]a script tag is safe to concatenate with a sanitized div, but it won't mean the same thing after a

in HTML for instance. It&#39;s hard to reason about, since there&#39;s `

Looks like something got confused by the "angle-bracket plaintext angle-bracket".  How very a-propos.

**Comment by mprobst** [comment]
I talked about this with @tbosch, and we agree that we probably should not try to be too clever here. Folks should use property binding (e.g. `<iframe [src]="myValue">`) when using `SafeValue`s and `bypassSecurityTrustAs...`. The reasoning is that we would need to be conservative in most contexts as @xtofian describes, so the benefit is very small unless we make this really complicated. At the same time users already wrote some code that does `bypassSecurity...`, and it's trivial and more obvious to just do whatever concatenation they need to do right there.

Which really only leaves the case of `<iframe src="{{ myValue }}">`. This currently fails because the interpolation causes `myValue` to be converted to a string, which is then sanitized again, which then fails. We could special case an interpolation of just one immediate value, but that'd be fragile: if you only have a trailing whitespace, this already falls apart. That's not a nice user experience either.

So my fix will be to implement a `toString` method for `SafeValue` objects that returns `"SafeValue must use [property]= binding"`. If a user ends up with a safe value in an interpolation context, that's probably a bug, and returning this string will make it easier for them to detect the situation. Detecting the situation and throwing an error for it could cause performance issues, so we're not doing this at this point (but might revisit).

**Comment by mprobst** [comment]
I'll declare this closed for the time being. We might want to revisit some time and maybe even throw an error on interpolation of SafeValue URLs.

**Comment by chandanch** [comment]
Hello I'm facing the same problem I'm using the srcdoc attribute of the iframe, the styles are not appearing in the iframe, Here is the code snippet:

**page.html**
```
.....
<div>
   <iframe [srcdoc]="htmlData"></iframe>
</div>

```
**page.ts**

```
.....
export class Page {
   public htmlData;
   constructor(){
   }
   this.htmlData = "<html><head><link rel='stylsheet' href=../styles/mystyle.css' /></head><body><h2 class='headerstyle'>Welcome to one word</h2><p class='maincontent'>This the body of the page</p></body></html>"
}
```
On the browser console I get this message:

> WARNING: sanitizing HTML stripped some content.

How to enable the style within the iframe?

**Comment by chandanch** [comment]
@vicb I also tried like as you mentioned in your comment: 

> Could you please try [src]=url and report if this works ?

My code snippet:

`   <iframe [srcdoc]=htmlData></iframe>`

Even this did not work, Are there any alternatives for this?

**Comment by zoechi** [comment]
@chandanch as mentioned above you need to use `bapassSecurity...` like explained above and for example in https://github.com/angular/angular/issues/8491#issuecomment-217473878

**Comment by zoechi** [comment]
@chandanch GitHub issues are for bug reports and feature requests.
    For support questions please use other channels like the ones listed in [CONTRIBUTING - Got a Question or Problem?](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question)

**Comment by mprobst** [comment]
@zoechi in all fairness, we're still working on the docs, so it's pretty tricky to figure this out by yourself.

@chandanch indeed, you'll need to use `bypassSecurity...` to mark your HTML as trusted and safe. Otherwise Angular will strip active parts, like your CSS style declaration, as it could contain malicious code.

**Comment by chandanch** [comment]
Its working now, I used the bypassSecurityTrustStyle and the styles are added with the iframe as well.
Thanks!
Also, there is more issue with the innerHTML attribute, Angular strips down the id attribute if a particular innerHTML has been specified with ID, Here is the code snippet which gives more clarity on what I'm trying to explain:

**page.html**
```
.....
<div id="outerdiv" [innerHTML]="htmlElement"></div>
```
**page.ts**

```
......
export class Page {
   public htmlElement;
   constructor(){
   }
   this.htmlElement = "<html><head><link rel='stylsheet' href=../styles/mystyle.css' /></head><body><p id='maincontent'>This paragraph is generated programatically</p></body></html>"
}
```
Run this on a browser and inspect on the dynamically generated paragraph element, The id attribute will be striped down by angular.

What could be the issue for this? Any inputs on this

**Comment by mprobst** [comment]
@rjamet this might be Angular protecting against DOM poisoning. If you declare an element with the ID `foo`, it will appear as `document.foo` in the resulting DOM.

**Comment by mprobst** [comment]
@chandanch as said before, you can use the `bypassSecurityTrust...` APIs to avoid sanitization altogether, if that is what you want. Other than that, maybe follow @zoechi's link to help/support forums, for example Stack Overflow?

**Comment by chandanch** [comment]
Thanks @mprobst I forgot to use the **bypassSecurityTrustHtml** Its working now.

**Comment by rjamet** [comment]
This looks like the protection against DOM poisoning, yes. Overall, id attributes are not allowed with the sanitizer, so I'm also thinking that either `bypassSecurityTrust...` is the right tool, or you need a template ?

**Comment by hughred22** [comment]
Same issue and adding bypassSecurityTrust... solve the issue. @kleijnweb, the url can not be string in my case as sanitationService.bypassSecurityTrustResourceUrl(this.vidLink) return something else. I have to use Any type to make this works.
