### ISSUE TITLE
Runtime template compiler generated names can collide

### ISSUE THREAD

**Issue by stringham** [angular/angular#9290]
The template compiler can generate two view factories with the same name.
https://github.com/angular/angular/blob/master/modules/%40angular/compiler/src/view_compiler/util.ts#L45

`component.type.name` for one of our components (after closure renames) is `Z` and for another components it is renamed to `Z5`, so when generating a view factory for the component with name `Z` when `embeddedTemplateIndex` is `50` it makes a class named `viewFactory_Z50`, and when it generates a view factory with the component named `Z5` when the `embeddedTemplateIndex` is `0` it generates a class with the name `viewFactory_Z50`.

It would probably make sense for the angular template compiler to guarantee generated class names are unique, perhaps keeping track of all generated names thus far.

However, just adding an additional delimiter like `_` would probably be sufficient for most cases.

**Comment by mprobst** [comment]
Oh this is a nice bug. As in, a terrible bug, but it's kind of funny.

The problem is that Angular needs to create new symbols in scope, and the symbols must not collide. Angular currently does that by appending a number to the symbol name (`FooComponent` --> `FooComponent1`).

Now if you have two components, one of whose name is a prefix of the other, and the other just appends a number, this is ambiguous. Imagine you have `FooComponent` and `FooComponent1`. Now if you create a symbol from the first component by appending `10`, and create a symbol from the second component by appending `0`, you end up with a collision.

I think this is a genuine bug in Angular, though rather unlikely to trigger on non-synthetic names (but does get exposed by synthetic names, e.g. Closure here).

**Comment by vicb** [comment]
already fixed
