### ISSUE TITLE
New ngrx router index breaks path

### ISSUE THREAD

**Issue by JoostvdB94** [angular/angular#9298]
**I'm submitting a ...**  (check one with "x")
```
[X] bug report
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
Adding the `index: true` attribute to a route breaks the `path` attribute. By this i mean that navigating to `localhost/#/` gives me the route which has `index:true`, but navigating to the path that belongs to that route (e.g. `/step/1`) errors with: `Cannot match any routes: 'step/1'`

**Expected/desired behavior**
The path specified should work the same way `/` does.

**Reproduction of the problem**
Changing:
```
{ path: '/error', component: ErrorPage },
    { path: '/step/1', component: StartPage },
    { path: '/step/2', component: TwoPage },
    { path: '/step/3', component: ThreePage },
    { path: '/step/4', component: FourPage },
    { path: '/step/5', component: FivePage },
    { path: '/setup', component: SetupPage },
```
To:
```
{ path: '/error', component: ErrorPage },
    { path: '/step/1', component: StartPage, index: true },
    { path: '/step/2', component: TwoPage },
    { path: '/step/3', component: ThreePage },
    { path: '/step/4', component: FourPage },
    { path: '/step/5', component: FivePage },
    { path: '/setup', component: SetupPage },
```
breaks the path
**What is the motivation / use case for changing the behavior?**
It is not expected behaviour.

**Please tell us about your environment:**

* **Angular version:** 2.0.0-rc.2
 
* **Browser:** [all | Chrome  51.0.2704.84 ] 
 
* **Language:**  TypeScript

**Comment by zoechi** [comment]
`index` is deprecated https://github.com/angular/vladivostok/issues/62#issuecomment-226492355

**Comment by pkozlowski-opensource** [comment]
@JoostvdB94  please note that the router contained in this repository was deprecated and the new version of a router is maintained in a separate repository now at https://github.com/angular/vladivostok. You can find more background on the various versions of a router in this blog post: http://angularjs.blogspot.fr/2016/06/improvements-coming-for-routing-in.html

Since a router is maintained in a separate repository now all the issues should be opened in there as well. So could you please re-open your issue at https://github.com/angular/vladivostok? (If it is already opened in https://github.com/angular/vladivostok there is no need to duplicate it here)

PS: make sure that you follow our [submission guidelines](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-submitting-an-issue) if you believe that there is a bug and use a [dedicated support channel](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem) for support questions. This will greatly speed up issue resolution process. Thnx!
