### ISSUE TITLE
Overlay Service

### ISSUE THREAD

**Issue by mhevery** [angular/angular#932]
# Goal

Allow developers to build overlays such as popups, dialog boxes, toasters, etc.. without the access to the native DOM.

Basic idea is that the service allows the developer to load overplayed components and the service manages the size, position, and event handling. 

## API

```
class Overlay {
  /// The component instance
  component:Object;

  /// closes the overlay
  close(); 
}

class OverlayManager {
  open(
    type:Type, // Component type to load into the overlay, 
    { position:Position, // Where should the overlay be placed,
      width: String,
      height: String,
      glassPane: boolean,
      events: Map<String, EventHandler>
    }
  )
}

```

**Comment by jelbourn** [comment]
Previously filed as #620 

The biggest unknown here for me is the Position. Most of the time you will want to have a position relative to some other element with special handling around preventing the overlay from being off-screen.

The API for `close` here also isn't the best; ideally the component inside of the Overlay would be responsible for closing itself, as that's where it makes the most sense to encapsulate that logic.

There would also need to be support for animation and potentially drag-and-drop.

**Comment by jbdeboer** [comment]
@jelbourn There are cases where you want an external service to close the dialog (e.g. pressing ESC on a text box should close the auto-complete popup).  The component itself should definitely have access to this API though.

There are many use-cases that need to be considered: popups on top of popups, multiple persistent popups, relative and absolute positioning.

**Comment by jelbourn** [comment]
@jbdeboer Definitely. Other examples include having multiple panel-inducing components (say, like a `select`, `autocomplete`, `bubble`, etc.) and enforcing that only one panel is open at a time.

An API I like is being able to inject something like a `DialogBridge` into a component that it can use to close itself and return some value to the invoking site. If the component is instantiated outside of the dialog context, that `DialogBridge` would be null.

**Comment by marcysutton** [comment]
There are also accessibility considerations for this, including `role`, `tabindex`, trapping focus/screen reader interaction in a modal dialog, and more. The exact ARIA attributes required will depend on the component (e.g. toast is different than alertdialog in terms of purpose and interaction).

**Comment by mlynch** [comment]
Thinking through this, I wonder if it belongs in Angular proper? Instead, it might be more useful to have a very simple component injection system (sort of like we had with `document.body.appendChild($compile(template)($scope)[0])` in v1) so that different UI kits can implement their own Overlay style systems.

I only worry that an Overlay service might not be generic enough for Ionic (as an example), and we would code around it (much like ngRouter vs UI-Router).

**Comment by jbdeboer** [comment]
@mlynch +1. I think our needs can be satisfied by a system that allows us to move components to a different part of DOM. e.g. in a template

    <ng-modal>This is a modal</ng-modal>

Which ends up in the DOM inside a modal container at the end of the page.

    <div class="modal-container" style="z-index: 11tee-billion">This is a modal</div>

**Comment by matanlurey** [comment]
+1 on flexibility. My biggest worry about `OverlayService` is it doesn't seem to match all use cases. More likely than not, you *know* what content will need to be in a toast/popup/mole/your-favorite-UI-pattern, you need to re-express its physical location.

**Comment by mhevery** [comment]
So we have split the OverlayService into [`DynamicComponentLoader`](https://github.com/angular/angular/blob/master/modules/angular2/src/core/compiler/dynamic_component_loader.js) which should already cover your use case. We will build `OverlayService` on top of it to make it cleaner.

**Comment by gautelo** [comment]
Will this account for scrolling? Say, if you have a grid with an open autocomplete and then scroll the grid?

**Comment by mhevery** [comment]
@gautelo shouldn't relative CSS position be sufficient? If not could you describe the issue in more detail.

**Comment by gautelo** [comment]
@mhevery Relative positioning will place the popout correctly underneath the grid cell, yes. However, if the popout is taller than the available horizontal space down to the bottom of the grids viewport, then the popout will be partially hidden like the rest of the grid content. What I want is for the popout to pop out of the grids viewport. I can achieve that with some [trickery](https://css-tricks.com/popping-hidden-overflow/), provided that no element between the grids viewport and the grid cell has relative/absolute positioning, which is not always the case (see ui-grid 3.x).

In the case of ui-grid 3.x I was able to modify it so that I could use this trick for normal grid cells, but I was unable to hack the filter row. It broke down real hard if I tried to get rid of relative/absolute positioning elements. This meant I couldn't place popouts in the filter-cells.

The workaround is of course to pop out to the parent of the grid and calculate position. I totally hate doing that however. Cause I feel the DOM for the popout should be inside the grid cell where it semantically belongs rather than be placed outside. 

I realize this is as much a general html & css layout issue as an angular issue. I was just wondering if you had considered this sort of scenario when designing this overlay service?

**Comment by gautelo** [comment]
This trick leads to scrolling breaking down. That's not a problem in the case of the ui-grid cells, as editors are closed whenever you start scrolling anyway. But that's just a fortunate thing and not something that would help in the general case.

**Comment by mhevery** [comment]
@jelbourn can comment more. I think this may be supported eventually. Right now we are focusing on getting the basic primitives right. You will be able to register a scroll event and then reposition your overlay using the [`Ruler`](https://github.com/angular/angular/issues/1262).

**Comment by gautelo** [comment]
I was unaware of the ruler. Should be very useful. In fact I am a little miffed that I didn't think of it myself.

It would then leave me with a choice of 1) keeping the popout as dom inside the cell and using position: fixed on it with a ruler for positioning or 2) using an overlay (which I suspect is attached to the body?) and a ruler. Very nice! Unless I've missunderstood.

**Comment by naomiblack** [comment]
Current status: primitives are implemented. Next step is to build the overlay service. 

Moving to M8 because GT is unblocked.

**Comment by jelbourn** [comment]
In trying to build a modal dialog service to test out whether the primitives are all the way there, I've run into a few issues. There are workarounds if you do direct DOM stuff, but that's not quite ideal:

#1539: Can't use `hostListeners` or `hostProperties` for the dynamically loaded dialog component.
#1541: Have to manually construct an element (raw DOM access) and dynamically load into that in order to dynamically load a component onto the document body.
#1251: Need "actions" concept to wrap focus within a dialog without DOM access.

There will likely be a few more as I progress.

**Comment by jelbourn** [comment]
Here's my prototype dialog implementation using the existing primitives. Much remains to be done, but it can give some idea as to how it would look:
https://github.com/jelbourn/angular/blob/md-dialog/modules/angular2_material/src/components/dialog/dialog.js

**Comment by naomiblack** [comment]
We have the basic hooks in place for building an overlay service. @matanlurey and @jelbourn to meet and come up with scenarios/use cases. Please close this issue and create a new concrete task to complete.

**Comment by naomiblack** [comment]
@jelbourn still open?

**Comment by jelbourn** [comment]
@matanlurey and I haven't been able to sit down to talk about this yet. Will try to do it today.

**Comment by jelbourn** [comment]
Talked with Matan today and went over the dialog prototype I built. Impressions:
The existing primitives (DynamicComponentLoader) seem fine for doing things like dialogs, notifications, etc., but those APIs are are still very clunky for things like menu / select / autocomplete. 

I am thinking that @tbosch's changes for component renderers have the potential to solve this issue.

We also talked about adding an intermediate "Overlay" service on top of DynamicComponentLoader. The sentiment is that it seems that it is probably not a highly valuable addition at this stage and would add another API surface we would have to support. I'd like to revisit this closer to release after I've built some more of this style component to see common elements. 

Going to close this now and track the leftover concerns in #1765
