### ISSUE TITLE
Breaking change with RC2: Sending Urls with search params because of encoding search values

### ISSUE THREAD

**Issue by janbaer** [angular/angular#9348]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question

After upgrade to the RC2 of angular2 I've the following problem with sending http requests to github with using the http service

Before the upgrade the query string was the following:
```
q=repo:janbaer/howcani+type:issue&sort=created&order=desc&page
```
after the upgrade the querystring changed to:

```
q=repo%3Ajanbaer%2Fhowcani%2Btype%3Aissue&sort=created&order=desc&page=1
```

The url was build automatically by the http service with using the RequestOptions object and giving them the searchParams. One of the search params has the following value:

```
repo:howcani-project/howcani-data+type:issue
```

I think the problem here is the usage of the slash and the plus sign. But it's necessary to send the search string in this format to github. https://developer.github.com/v3/search/

How can I prevent that my query value will by escaped?

**Comment by janbaer** [comment]
In the meantime I found the reason for the breaking change. It comes from this commit here:

https://github.com/angular/angular/commit/6f3a6a55a08dd6ce12ed55009ab9fe6c29a8366f

@netdesk has commented this comment since he found out that this change leads to a breaking change since some urls (like mine) could not longer be send when using the Request options object.

**Comment by janbaer** [comment]
I just changed the title of the issue since it has nothing todo with sanitizing the url

**Comment by jeffbcross** [comment]
We dealt with this same problem in Angular 1 $http with a custom `encodeUriQuery`: https://github.com/angular/angular.js/blob/53ab8bcde1ee8fa88d06dd3b5ed4986cb141c129/src/Angular.js#L1394

As far as I remember, the `encodeUriQuery` function from ng1 pretty closely matches the ietf spec, so we should just copy it over and use it for Angular 2 http instead of `encodeURIComponent`.

**Comment by jeffbcross** [comment]
Actually, `encodeUriQuery` doesn't quite get what we need here, since it will still escape slashes.
`q=repo:janbaer%2Fhowcani%2Btype:issue&sort=created&order=desc&page=1 //encodeUriQuery`
`q=repo:janbaer/howcani+type:issue&sort=created&order=desc&page=1 // Before Change`
`q=repo%3Ajanbaer%2Fhowcani%2Btype%3Aissue&sort=created&order=desc&page=1 // Current`

If we added `/` and `+` (`%2F` and `%2B`) to whitelist, which I think are both ok with the spec to be part of query values (but I need to read again), then it would solve this use case. Though since different APIs have different arg requirements, it would be nice to provide the ability to override the serialization mechanism as they did in ng1. https://github.com/angular/angular.js/blob/53ab8bcde1ee8fa88d06dd3b5ed4986cb141c129/src/ng/http.js#L26

I'll look into this more tomorrow.

**Comment by fknop** [comment]
I'm facing the same issue. Is there any workaround in the meantime ?

**Comment by janbaer** [comment]
My workaround was to concatenate to searchparams in my own function and use the request options without searchparams.

https://github.com/howcani-project/howcani/commit/8a2fa80b079c9d340952bac371acd1c265b4e10e
