### ISSUE TITLE
404 - Extra slash in import /router//bundles/router.umd.js

### ISSUE THREAD

**Issue by sethdorris** [angular/angular#9374]
**I'm submitting a ...**  (check one with "x")
```
[ X ] bug report
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
404 Error http://localhost:3000/node_modules/@angular/router//bundles/router.umd.js 

Angular seems to be adding an extra / after router and before bundles folder

**Expected/desired behavior**

I expect the path to be only one slash

**Reproduction of the problem**
https://github.com/sethdorris/practice_angular2

just clone my github repo and "npm start"

**What is the expected behavior?**
The error does not occur when you remove the bootstrapping of the application with APP_ROUTER_PROVIDERS

**What is the motivation / use case for changing the behavior?**
I am trying to use Angular Router

**Please tell us about your environment:**

* **Angular version:** 2.0.0-rc.2
* **Angular Router Version.** 3.0.0-alpha.7
 
* **Browser:** Chrome 51.0.2704.103 m (64-bit) 
 
* **Language:**  TypeScript 1.8.10

**Comment by brandonroberts** [comment]
This is an issue with your SystemJS config: https://github.com/sethdorris/practice_angular2/blob/master/systemjs.config.js#L36

Removed the `/` before `bundles`

**Comment by sethdorris** [comment]
@brandonroberts Thank you sir!

**Comment by brandonroberts** [comment]
Close this one if resolved. 😄

**Comment by matejkramny** [comment]
Idk why but my `@angular/router` had no `bundle` folder so I resorted to using `packIndex` just for `router`.

**Comment by robinkedia** [comment]
Sorry can you share how did you fix bundles missing issue. ?
packages['@angular/router'] = { main: 'index.js', defaultExtension: 'js' };

**Comment by matejkramny** [comment]
Yeah and you need to remove it from the package list.

```
/**
 * System configuration for Angular 2 samples
 * Adjust as necessary for your application needs.
 */
(function(global) {
  // map tells the System loader where to look for things
  var map = {
    'app':                        '', // 'dist',
    '@angular':                   'node_modules/@angular',
    'angular2-in-memory-web-api': 'node_modules/angular2-in-memory-web-api',
    'rxjs':                       'node_modules/rxjs'
  };
  // packages tells the System loader how to load when no filename and/or no extension
  var packages = {
    'app':                        { main: 'main.js',  defaultExtension: 'js' },
    'rxjs':                       { defaultExtension: 'js' },
    'angular2-in-memory-web-api': { main: 'index.js', defaultExtension: 'js' },
  };
  var ngPackageNames = [
    'common',
    'compiler',
    'core',
    'forms',
    'http',
    'platform-browser',
    'platform-browser-dynamic',
    'router-deprecated',
    'upgrade',
  ];
  // Individual files (~300 requests):
  function packIndex(pkgName) {
    packages['@angular/'+pkgName] = { main: 'index.js', defaultExtension: 'js' };
  }
  // Bundled (~40 requests):
  function packUmd(pkgName) {
    packages['@angular/'+pkgName] = { main: 'bundles/' + pkgName + '.umd.js', defaultExtension: 'js' };
  }
  // Most environments should use UMD; some (Karma) need the individual index files
  var setPackageConfig = System.packageWithIndex ? packIndex : packUmd;
  // Add package entries for angular packages
  ngPackageNames.forEach(setPackageConfig);
  packages['@angular/router'] = { main: 'index.js', defaultExtension: 'js' };
  var config = {
    map: map,
    packages: packages
  };
  System.config(config);
})(this);
```

**Comment by leebyeungkok** [comment]
It's now work yet...

**Comment by pantonis** [comment]
@matejkramny  thanks for the workaround .

Is this a bug though?

**Comment by matejkramny** [comment]
Im not sure, the issue really is that the package doesn't have a bundle file. It was recently moved to `angular/angular` so we may see one when they release a new version.

**Comment by matejkramny** [comment]
The router package is alpha anyway.

**Comment by sethdorris** [comment]
@pantonis no it's not a bug.

**Comment by dhondtlaurens** [comment]
@matejkramny, Thx sir!

**Comment by robinkedia** [comment]
This is no longer a issue. Please issue npm uninstall @angular/router --save and then npm install @angular/router --save to install the package again. It works for me now.

**Comment by iaforek** [comment]
@robinkedia 
Your solution worked fine. I was getting exactly the same error message when following Angular's "Tour of Heroes" tutorial. Executing these two commands (uninstall and install) solve the issue. No need to modify any config or anything. Thanks!

**Comment by mazur-k** [comment]
Sad, but it hasn't worked for me. After uninstall/install I've got a bunch of errors about routerLink isn't a native property.

**Comment by cumanzor** [comment]
@mazur-k: Try doing an npm uninstall *, get the latest package.json file from https://angular.io/docs/ts/latest/quickstart.html#!#add-config-files, then do an npm install. Watch out for missing dependencies warnings as well.

**Comment by mazur-k** [comment]
Still nothing. What's wrong ?

**Comment by robinkedia** [comment]
Can you try new project following quick start tutorial. If the new one
works than something wrong with your existing code

On Monday, 4 July 2016, mazur-k <notifications@github.com> wrote:

> Still nothing. What's wrong ?
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/angular/angular/issues/9374#issuecomment-230266411>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AJ6mG84LldvE7zCbH2Gk5b5y8899QFyAks5qSOocgaJpZM4I6HWA>
> .
>


-- 
Cheers!

**Comment by mazur-k** [comment]
I dont think it's a right choice. As it was mentioned above, I'm trying to follow Tour of Heroes tutorial. Before adding routing it works perfectly fine. And just after routing stuff this error occurs.

**Comment by ruppalsingh** [comment]
RC4 package.json (latest as of now) file breaks the Tour of Heroes tutorial.

`
EXCEPTION: Template parse errors:
Can't bind to 'routerLink' since it isn't a known native property ("
  <h1>{{title}}</h1>
  <a [ERROR ->][routerLink]="['/heroes']">Heroes</a>
  <router-outlet></router-outlet>
  "): AppComponent@2:5
platform-browser.umd.js:1900
`

`
EXCEPTION: Template parse errors:
Can't bind to 'routerLink' since it isn't a known native property ("
  <h1>{{title}}</h1>
  <a [ERROR ->][routerLink]="['/heroes']">Heroes</a>
  <router-outlet></router-outlet>
  "): AppComponent@2:5BrowserDomAdapter.logError @ platform-browser.umd.js:1900
platform-browser.umd.js:1909
`

`
EXCEPTION: Error: Uncaught (in promise): Template parse errors:
Can't bind to 'routerLink' since it isn't a known native property ("
  <h1>{{title}}</h1>
  <a [ERROR ->][routerLink]="['/heroes']">Heroes</a>
  <router-outlet></router-outlet>
  "): AppComponent@2:5
platform-browser.umd.js:1900
`

`
EXCEPTION: Error: Uncaught (in promise): Template parse errors:
Can't bind to 'routerLink' since it isn't a known native property ("
  <h1>{{title}}</h1>
  <a [ERROR ->][routerLink]="['/heroes']">Heroes</a>
  <router-outlet></router-outlet>
  "): AppComponent@2:5BrowserDomAdapter.logError @ platform-browser.umd.js:1900
platform-browser.umd.js:1900
`

`
STACKTRACE:BrowserDomAdapter.logError @ platform-browser.umd.js:1900
platform-browser.umd.js:1900
`

`
Error: Uncaught (in promise): Template parse errors:
Can't bind to 'routerLink' since it isn't a known native property ("
  <h1>{{title}}</h1>
  <a [ERROR ->][routerLink]="['/heroes']">Heroes</a>
  <router-outlet></router-outlet>
  "): AppComponent@2:5
    at resolvePromise (zone.js:538)
    at PromiseCompleter.reject (zone.js:515)
    at eval (core.umd.js:9843)
    at ZoneDelegate.invoke (zone.js:323)
    at Object.onInvoke (core.umd.js:9100)
    at ZoneDelegate.invoke (zone.js:322)
    at Zone.run (zone.js:216)
    at zone.js:571
    at ZoneDelegate.invokeTask (zone.js:356)
    at Object.onInvokeTask (core.umd.js:9091)BrowserDomAdapter.logError @ platform-browser.umd.js:1900
zone.js:461
`

`
Unhandled Promise rejection: Template parse errors:
Can't bind to 'routerLink' since it isn't a known native property ("
  <h1>{{title}}</h1>
  <a [ERROR ->][routerLink]="['/heroes']">Heroes</a>
  <router-outlet></router-outlet>
  "): AppComponent@2:5 ; Zone: angular ; Task: Promise.then ; Value: BaseException$1consoleError @ zone.js:461
`

`
zone.js:463 Error: Uncaught (in promise): Template parse errors:(…)consoleError @ zone.js:463
`
