### ISSUE TITLE
@Input field required default value

### ISSUE THREAD

**Issue by zerovirus23** [angular/angular#9384]
**I'm submitting a ...**  (check one with "x")
```
[ x] bug report
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
```
import { Component, Input, OnInit } from '@angular/core';
import { Event, EventImpl } from '../../model/event';
import { EventService } from '../../services/event-service';

@Component({
  selector: "event-detail",
  templateUrl: "event-detail.html",
  providers: [EventService],
  moduleId: module.id
})
export class EventDetailComponent {
    @Input()
    event: Event;
    eventTypes : string[];

    constructor(private service: EventService){
    }
    
    ngOnInit(){
      this.loadEventTypes();
    }

    save(){
      this.service.create(this.event).then(
        event => this.event = event
      );
    }

    cancel(){
      this.event = null;
    }
    
    loadEventTypes(){
      let response = this.service.listEventTypes()
        .then(eventTypes => this.eventTypes = eventTypes);
    }
}
```
The event field with the Input decorator (without default value) generates the error "ReferenceError: event_1 is not defined".

The tsc compiler generates the following JavaScript with the error:
```
__decorate([
        core_1.Input(), 
        __metadata('design:type', event_1.Event)
```
Note: If I assign a default value (e.g @Input() event: Event = new EventImpl(); ) or delete the decorator the component works fine!

**Expected/desired behavior**
The component must work without assign a default value to the input field (almost all examples shows that). 

**Repo with the code that has the error:**
[Git Repo](https://github.com/zerovirus23/vogue-ui/tree/bug/input_decorator_event_detail)

**Please tell us about your environment:**
* **Angular version:** 2.0.0-rc.2
* **Browser:** all 
* **Language:** TypeScript 1.8.10

**Comment by vicb** [comment]
Please provide a repro (plunker or repo)

**Comment by zerovirus23** [comment]
You can find the code to reproduce the issue in this repo [Event.ts](https://github.com/zerovirus23/vogue-ui/blob/bug/input_decorator_event_detail/main/components/event/event-detail.ts) and the javascript with the problem in [Event.js](https://github.com/zerovirus23/vogue-ui/blob/bug/input_decorator_event_detail/main/components/event/event-detail.js)

I fount that if the field doesn't  have a default value in the typescript file, in the generated javascript the line ``` var event_1 = require('../../model/event'); ``` is missing.

If you need more information, please let me know!

**Comment by vicb** [comment]
What are the steps to reproduce ?

**Comment by zerovirus23** [comment]
To reproduce, just launch the application with ```npm start```, the list page doesn't load the application because the error (you can see the error in the console of chrome in Developer Tools)!

**Comment by pe8ter** [comment]
This is not a bug with Angular. If anything, you've found a bug in the TypeScript compiler.

You cannot create an interface `Event` and type `EventImpl` that implements that interface, then decorate a field with `@Input()` using the the interface as the type. Interfaces get compiled out of the JavaScript, therefore there's nothing concrete in JS space that can be stored in your component's metadata.

Maybe you need to turn your interface `Event` into a class. I don't know if that's okay because there's already a type in the browser called `Event`. My knowledge of TypeScript is shaky here. This is why I think you may have uncovered a bug in the TypeScript compiler. It looks like the compiler routine that adds the metadata doesn't actually verify that the import for that metadata actually exists. Maybe it's not supposed to. I think you hit on an interesting case because you chose a symbol (`Event`) that is already in use by something else. You could also try renaming `Event` to some other unused symbol name, but first you must fix the issue from the previous paragraph.

**Comment by vicb** [comment]
@pe8ter great analysis, thanks.

**Comment by zerovirus23** [comment]
Thanks @pe8ter, that solves my problem. It was a newbie's issue ;-)
