### ISSUE TITLE
Issue in Dart transformer

### ISSUE THREAD

**Issue by vicb** [angular/angular#950]
On master (afda43dc0281e3671d6df3218749d5050d47f188),

```
gulp clean
gulp build.dart
gulp serve/examples.dart
```
+ open http://localhost:8080/src/hello_world/index.html

gives the following error:

```
$ gulp serve/examples.dart
Dart SDK detected
[19:27:12] Using gulpfile ~/dart/angular/gulpfile.js
[19:27:12] Starting 'serve/examples.dart'...
Loading source assets... 
Loading angular2 transformers... 
Serving examples web  on http://localhost:8080
Serving examples test on http://localhost:8081
[Warning from DirectiveProcessor]:
Processing ng directives failed.
Exception: Error in test/benchpress/webdriver_async.server.spec.dart: Expected an identifier
Error in test/benchpress/webdriver_async.server.spec.dart: Expected to find ')'
Error in test/benchpress/webdriver_async.server.spec.dart: Expected to find ';'
Error in test/benchpress/webdriver_async.server.spec.dart: Expected to find ';'
Error in test/benchpress/webdriver_async.server.spec.dart: Expected to find ';'
Error in test/benchpress/webdriver_async.server.spec.dart: Expected to find ';'
Error in test/benchpress/webdriver_async.server.spec.dart: Expected an identifier
Error in test/benchpress/webdriver_async.server.spec.dart: Expected to find ';'
[...]
```

/cc @tbosch should we add e2e for this ?

**Comment by kegluneq** [comment]
This is due to use of `async` / `await` in [the benchpress test code](https://github.com/angular/angular/blob/master/modules/examples/test/benchpress/webdriver_async.server.spec.dart). package:analyzer has some problems parsing it prior to v0.24.0, so the solution is to bump that version.

However, package:angular and package:di both place constraints on package:analyzer, so we'll need to change them first. I'll put together PRs for that. In the meantime, these errors can be safely ignored.

**Comment by kegluneq** [comment]
Waiting on these PRs, then we'll have to pull those changes into [pub](//pub.dartlang.org) before the errors will go away.
- [ ] [Angular.dart](https://github.com/angular/angular.dart/pull/1694)
- [ ] [Angular.di](https://github.com/angular/di.dart/pull/210)
