### ISSUE TITLE
router on default path.

### ISSUE THREAD

**Issue by damiandennis** [angular/angular#9505]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
base path with parameter throws a "path not found" error.

**Expected/desired behavior**
should route and not throw an error.

**Reproduction of the problem**
If the current behavior is a bug or you can illustrate your feature request better with an example, please provide the steps to reproduce and if possible a minimal demo of the problem via https://plnkr.co or similar (you can use this template as a starting point: http://plnkr.co/edit/tpl:AvJOMERrnz94ekVua0u5).

http://plnkr.co/edit/thC5bxryZ7LStdfPVlP5?p=preview

**What is the expected behavior?**

should not be an error on page load. 

**What is the motivation / use case for changing the behavior?**

broken

**Please tell us about your environment:**

* **Angular version:** 2.0.0-rc.3
 
* **Browser:** Chrome XX
 
* **Language:** TypeScript X.X

**Comment by damiandennis** [comment]
This also happen on routes when using this.router.navigate(['/', { id: 5 }]); most likely related in some way.

**Comment by ericmartinezr** [comment]
Would this be similar to https://github.com/angular/angular/issues/9460 ?

**Comment by vsavkin** [comment]
The root segment cannot have matrix params. There are two reasons for this:

- There is no place in the URL to put them.
- Currently we reuse components when their parameters change, but in the future we will provide a way to customize the reuse behavior. So the developer will be able to get a new copy of a component any time its args change. Since the root component is created statically, we cannot implement it for the root component. 

So the following `this.router.navigate(['/', { id: 5 }])` should not be allowed. I submitted a PR that throws a descriptive error message.

**Comment by tinchou** [comment]
From RC5 to RC6 I had to change from:

```ts
this.router.navigate(["", parameters]);
```

to (notice the dot):

```ts
this.router.navigate([".", parameters]);
```

**Comment by leotm** [comment]
The dot seems to just change the error from _Root_ segment to _URL_ segment.
