### ISSUE TITLE
UMD Files not found after upgrade to rc3

### ISSUE THREAD

**Issue by zeeshanjan82** [angular/angular#9521]
I have upgraded my rc1 angular2 project to rc3 however when I run the app I am getting 404 errors for all the *.umd.js files
```js
    paths: {
      [this.BOOTSTRAP_MODULE]: `${this.APP_BASE}${this.BOOTSTRAP_MODULE}`,
      '@angular/core': `${this.APP_BASE}node_modules/@angular/core/core.umd.js`,
      '@angular/common': `${this.APP_BASE}node_modules/@angular/common/common.umd.js`,
      '@angular/compiler': `${this.APP_BASE}node_modules/@angular/compiler/compiler.umd.js`,
      '@angular/http': `${this.APP_BASE}node_modules/@angular/http/http.umd.js`,
      '@angular/router': `${this.APP_BASE}node_modules/@angular/router/router.umd.js`,
      '@angular/platform-browser': `${this.APP_BASE}node_modules/@angular/platform-browser/platform-browser.umd.js`,
      '@angular/platform-browser-dynamic': `${this.APP_BASE}node_modules/@angular/platform-browser-dynamic/platform-browser-dynamic.umd.js`,
      'rxjs/*': `${this.APP_BASE}node_modules/rxjs/*`,
      'app/*': `/app/*`,
      '*': `${this.APP_BASE}node_modules/*`
    },
```
how do I modify the above to find these files in rc3

**Comment by vicb** [comment]
Please use gitter for support requests as suggested https://github.com/angular/angular/blob/master/CONTRIBUTING.md.

You can also read the changelog to figure out the changes https://github.com/angular/angular/blob/master/CHANGELOG.md

Or check the node_modules folder on your computer.

I think they are in a bundles subdir since RC2

**Comment by mLaird** [comment]
I also upgraded from rc.1 to rc.3.  I have followed the QuickStart and Tutorial instructions. Now the app will not load. I get 'not found' Console messages like the following:
 
http://localhost:3000/node_modules/@angular/platform-browser-dynamic/platform-browser-dynamic.umd.js [HTTP/1.1 404 Not Found 2ms]

and similar messages for core.umd and router-deprecated.umd

I see no mention of umd in the Changelog.

Since it was working and it is not now working, there is a fault in either the documentation or in the code.  Something needs to get fixed.
