### ISSUE TITLE
router: CanDeactivate guard is called twice when there is a redirect in the new route

### ISSUE THREAD

**Issue by iurii-kyrylenko** [angular/angular#9530]
[ x] bug report

**Current behavior**
The CanDeactivate guard is called twice.

**Expected/desired behavior**
The CanDeactivate guard is called once.

**Reproduction of the problem**
1. The target route performs redirect in its CanActivate guard.
2. CanDeactivate guard returns an asynchronous result.

**Illustration of issue**
http://plnkr.co/edit/bnrwg1XFAZEIE73gb2wD?p=preview
See plunk's 'readme' for details.

**What is the motivation / use case for changing the behavior?**
Unexpected  behavior of the demo application (https://angular.io/docs/ts/latest/guide/router.html):
After editing the crisis name and pressing the Admin link, the confirmation dialog appears twice.

**My environment:**
* **Angular version:** 2.0.0-rc.3
* **router:** 3.0.0-alpha.7 
* **Browser:** Chrome 53

**Comment by vsavkin** [comment]
I think we should keep it the way it is right now, and here is why

1. Running guards is a part of a navigation.
2. Every navigation right now is independent. So when you call navigate in 'canActivate', you start a new navigation. There is no notion of "continuing" navigations. It's a simpler mental model.
3. Currently, canDeactivate doesn't receive the future/target state, but I think it should. Once this is done, we will have to call canDeactivate twice, as it will receive two different sets of parameters the first and the second times.
4. In general, you should rely on 'redirectTo' for url normalization. I think guards should not have any side effects, including creating new navigations. Instead, you should do something like this:

```
router.navigate(someUrl).then(res => {
  if (res === false) // guards failed 
    router.navigate(someOtherUrl);
});
```

**Comment by iurii-kyrylenko** [comment]
In my opinion, the primary reason for the described behaviour is the fact that '_canActivate_' (in target route) is called **always** - regardless of the **asynchronous** result of '_canDeactivate_' (in source route).

I would expect the same behaviour, as in synchronous mode:
'_canActivate_' is not called when '_canDeactivate_' returns `false`. It is OK.

But actually, '_canActivate_' is called when '_canDeactivate_' returns `Observable.of(false).delay(0)`
I consider this as a bug.

**Comment by davideberlein** [comment]
@vsavkin I believe your suggestion of not navigating in the guard actually misses its purpose of guards or at least the one most users use it for. (e.g. also the official documentation)
In our application e.g. you never see a link that leads to an unauthorized page so we never directly call router.navigate() on a page that will fail because the "AuthGuard" returns false.
However the user can enter a URL that needs authentication into the browser bar and we want to redirect him to the login / not authorized paged in this case.
I don't know how to solve this without actually navigating inside the guard.
What is your take on this?
