### ISSUE TITLE
consistency between path and routerLink

### ISSUE THREAD

**Issue by alanpurple** [angular/angular#9563]
some starts with '/'
some does not

it's a bit confusing

**Comment by brandonroberts** [comment]
There is a difference because you can do relative navigation as well as absolute navigation. Examples provided below. Documentation explaining the difference will be added soon.

absolute
```html
<a [routerLink]="['/parent/child/grandchild']">Absolute</a>
```

relative (If I were in the `/parent/child` route)
```html
<a [routerLink]="['grandchild']">Relative</a>
```

relative (If I were in the `/parent/child/grandchild` route)
```html
<a [routerLink]="['../../parent']">Relative</a>
```

**Comment by pkozlowski-opensource** [comment]
Thnx @brandonroberts
