### ISSUE TITLE
Ability to Navigate without pushing the location into the browser history

### ISSUE THREAD

**Issue by briananderson1222** [angular/angular#9579]
This issue is related to the new-new router:

**I'm submitting a ...**  (check one with "x")
```
[ ] bug report
[x] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
There is not currently any way to navigate through an application while skipping the browser history.

**Expected/desired behavior**
In the router-deprecated there was a second parameter on the `navigateByUrl` method that allowed us to `skipLocationChange`. It would be nice if the `navigate` method allowed this too.

**What is the motivation / use case for changing the behavior?**
I have a specific use case where we have a 'loader' component that does a service call and essentially decides where to route you. I would like to be able to navigate to this loader component without including it in the back button history so that the browser doesn't get stuck in an infinite loop of going back to the loader only to get redirected.

**Please tell us about your environment:**

* **Angular version:** 2.0.0-rc.3
* **Router version:** alpha.7
 
* **Browser:** [all] 
 
* **Language:** [all]

**Comment by milkisevil** [comment]
This is basically analogous to [history.replaceState()](https://developer.mozilla.org/en-US/docs/Web/API/History_API#The_replaceState()_method) and ideally, it'd help if the property passed to `navigate()` to activate this was named similarly (ie. prefer `{replace:true}` over `{skipLocationChange:true}`).

**Comment by AndreCAndersen** [comment]
@alxhub IMO this issue was not fully solved by [9608](https://github.com/angular/angular/pull/9608). This issue is about being able to navigate without changing the browser history. Unfortunately, 9608 also prevents the URL from being updated. My version of the use case is to add a cosmetic (pretty) name to the end of the url. If the user navigates to:

    http://example.com/#/company/42

... they get renavigated to a more readable and shareable url:

    http://example.com/#/company/42/example-inc

Using only `navigate(...)` makes it impossible to use the browser back button, but with `skipLocationChange: true` we do navigate without changing the navigation history, but it also ignores changes to the URL itself. In essence we're not doing what @philipbulley suggested by emulating [history.replaceState()](https://developer.mozilla.org/en-US/docs/Web/API/History_API#The_replaceState%28%29_method).
