### ISSUE TITLE
Boolean value is not working in ngSwitch Directive

### ISSUE THREAD

**Issue by Bretto** [angular/angular#9706]
**I'm submitting a ...** feature request

**Current behavior** the value in ngSwitch is always interpreted as a string

**Expected/desired behavior** if I do: {{!!myBooleanVar}} it should be interpreted as a boolean

**What is the motivation / use case for changing the behavior?** currently we need to convert boolean to string in the component logic. I would be nice to be able to use the boolean input with no conversion. (I did try to add a toBoolean Pipe but that did not work either)

**Please tell us about your environment:** Liniux

* **Angular version:** 2.0.0-rc.2
 
* **Browser:** All
 
* **Language:**TypeScript

**Comment by apkostka** [comment]
@Bretto Can you post a plunker with the code you're describing? If you're trying to get the `ngSwitchCase` value to be interpreted as an expression, use `[ngSwitchCase]="myBooleanVar"` instead of `ngSwitchCase="{{myBooleanVar}}"`. 

If you're talking about the switch value, you don't need to surround that in brackets, just use `[ngSwitch]="myBooleanVar"`.

Either way, this seems like a support request and not a bug fix.

**Comment by vicb** [comment]
Your question sounds like a support request.

Please use the issue tracker only for bugs and feature requests.

Use [gitter](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem) for support request.
