### ISSUE TITLE
forms: using <formControl>.updateValue(item) doesn't set the control to dirty and markAsDirty() fails too

### ISSUE THREAD

**Issue by donskifarrell** [angular/angular#9768]
**I'm submitting a ...**  (check one with "x")
```
[X] bug report
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
Updating the value of a form control using the updateValue() method will set the value correctly, but the 'dirty', 'touched' and 'pristine' properties of the control do not update. using the .markAsDirty() method fails to work. This is also described in issue #5328 
Only when you physically interact with the control do the values/flags update. 

**Expected/desired behavior**
updateValue(...) should update the flags appropriately, or have some documented way to programmatically update the value/flag states in one go.

**Reproduction of the problem**
http://plnkr.co/edit/ue2vlkzQ6Co4vDhzk0t0?p=preview

**What is the expected behavior?**
FormControl's should be updated with the correct state. ie. if the value changes then the control is now 'dirty'

**What is the motivation / use case for changing the behavior?**
Unless there is a misunderstanding on the use of FormControl (that it represents the state of an 'input' element) then the updateValue() method should work predictably.

**Please tell us about your environment:**

* **Angular version:** 2.0.0-rc.4 | **Forms:** 0.2.0
 
* **Browser:** [Chrome 51.0.2704.106 ] 
 
* **Language:** [TypeScript 1.8.10]

**Comment by kara** [comment]
We model the "touched" and "dirty" properties based on direct user interaction with the form control, not on change in value. Only when **a user** changes a value in the UI does it become dirty.   The utility of these properties is based on insight into how the user has interacted with your form.   It's trivial to detect when your application has dirtied a form programmatically because that is code you've called yourself.  

So when you change the value of your form control using `updateValue()`, it is actually by design that the these properties are not updated.  This way, it is simple to distinguish between effects that the user has had as opposed to effects the application code might have had.

In the case that some controls do need to be marked as dirty once your app updates a value, you can deliberately choose to call `markAsDirty()`, and that should work.  I checked out the plunker you provided, and I found that uncommenting the `markAsDirty()` call did mark the engine field as dirty.  Can you clarify what you expected to happen?

**Comment by donskifarrell** [comment]
Ok, so it seems I had the wrong end of the stick with the intention of the form controls. My guessing was that the updateValue() was supposed to mimic the user action and would set the flags.

re: markAsDirty() - you're right, it is working as expected. Not sure how I missed that! 

Thanks for the detailed explanation!

**Comment by proskilly** [comment]
When I call markAsDirty() it still doesn't update the form control's value, it shows an out of date value ignoring the text box being changed programatically.

```
this.filtersFormGroup.controls['startDateTime'].markAsDirty();
        console.log('startDateTime after markAsDirty : ' + this.filtersFormGroup.controls['startDateTime'].value);
```
