### ISSUE TITLE
Angular 2 Router to hide browser url parameter Id's and give alias names

### ISSUE THREAD

**Issue by vijender1256** [angular/angular#9798]
I am trying to route from EmployeeLIst to employeeDetail after I click on employee with ID 23. How do I route to employeeDetail/23 but on browser URL  show the user an alias like /EmployeeDetails?

Background

I'm trying to implement Angular 2 routing and when I went to the detail section I see:

http://localhost:3444/employeedetail/23.

Here I want to hide that 23 on the browser URL, why do i want to show the ID which can be sensitive. In UI-Router we used to have URL="something" and that URL is visible on the browser URL. Don't we have similar in Angular2 like passing RouteParams and have custom name on the browser URL instead of the Route name itself.

Example

http://plnkr.co/edit/QgehylornOgXhTaZX8Yn?p=preview

`{path: 'crisis-center/:id/:id2', component: CrisisDetailComponent}`

I want to hide those IDs on the browser URL and instead present an alias route name.

**Comment by DavideViolante** [comment]
I don't think this is possible, but I'm not sure. You could do it (dirty way imho) using the same component (EmployeeList) and show/hide the employee details using ngIf and click event (no navigation, but only template manipulation).

**Comment by vijender1256** [comment]
@DavideViolante Thanks for the reply, but I think this was possible in angular 1 using ui-router:

 ```
.state("dashboardException", {
            url: "/MyChoiceOnBrowser",
            templateUrl: "app/Dashboard/exceptiondashboard.html",
            controller: 'exceptiondashboardcontroller',
            controllerAs: "vm"
        })
```

In above code the  after passing stateParams to the controller, we can read those parameters and then show "MyChoiceOnBrowser" as the browser URL, here we are not showing the stateParams that are passed to the controller.

Does this mean Angular2 dont have this option but Angular 1 has it ?

I dont want to show the queryParams on the browser URL what if it is employeeId that is unique but I dont want users to see ?

Anyone have solution for this ?

**Comment by zoechi** [comment]
If you don't want it in the URL bar, then it is probably not relevant for routing anyway. You can use a shared service for global data.

**Comment by vsavkin** [comment]
I think what you probably want is to set state when navigating. See here https://github.com/angular/angular/issues/10248.

Currently it is not supported, so you have to use a workaround (e.g., having a service to store the data).

**Comment by werpu** [comment]
Unfortunately such a feature is not supported as it seems by the standard angular 2 routing. Also unfortunately ui-router-ng2 is not quite there yet which would support it. I used to use this feature many times in my angular1 app using ui-router. The reason simply was, I have a crud application with two levels deep details which are shown alongside the master list, however I do not want the users to jump into the details if they bookmark the page.
So giving them dedicated bookmarking points by simply having ui-router exposing the master urls only while keeping the details substates hidden from the url was the solution. The same could be achieved also by using hidden flags on the components, but this is not really the same and would basically scatter the routing code instead of keeping it in a central location. 

This problem prevents me for now to porting my app to angular2 although i have all the building bricks except the routing with hidden links working. And as I said ui-router-ng2 is not there yet, I ran into several bugs, which I cannot really isolate in a small environment (like ignoring routes in one page although they are defined). It is close, but it probably will need some time.

Either way I am in the fortunate solution that time is not pressuring for me, so I held off the transition to Angular2 for another half a year minimum until this situation is resolved. Frameworks need time to stabilize anyway.

**Comment by hopeeen** [comment]
The new router for angular2 supports query params, which I assume could be used for this type, just remember to reset the parameter after fetching it.
As I worked with this before the new router came, I made a workaround:
From an admin perspective, I list the users and change the view to display details on the selected user since every list element contains the userid.
From a login perspective, my profile component request the authid (i use angularfire2) and fetches the userdetails from my db and then displays the details.
Only downside with the workaround is that you cant navigate to the details with url , so you would always have to enter the employees component

**Comment by mlc-mlapis** [comment]
There is also 'data' property on a route and you can set it as you want and it is completelly hidden to a user and URL.

**Comment by PardeepJain** [comment]
@mlc-mlapis yes, but data property is used to send static data only, this mehod will not work in case of dynamic ID passing. i think so

**Comment by mlc-mlapis** [comment]
Yes, you are right. Then only `skipLocationChange` property could be used to protect a user from seeing URL change.

**Comment by sabithpocker** [comment]
this.router.navigate(['/dashboard'], { queryParams:  filter, skipLocationChange: true}); 

Worked for me to have matrix params hidden from the URL, only the required links need to have the flag set and others work as normal urls.

**Comment by OdaiTu** [comment]
what if i want to replace the id by the name ?? 
but i still send the id  to the server to get the data

**Comment by marslan2037** [comment]
@sabithpocker you save me 👍

**Comment by marslan2037** [comment]
@sabithpocker you answer is working, but this will also not allow actual url to change .... any suggestion?

**Comment by tsvetomirivanovv** [comment]
@OdaiTu @marslan2037 
Making it like that you hide all parameters and then you manually set the url to your desired state.

this.router.navigate(['dashboard/company/'], { queryParams:  { id: res }, skipLocationChange: true });
window.history.pushState('','',user.email)

You still can get the queryParams on your other component even with skipLocationChange: true

ngOnInit() {
    let param = this.router.parseUrl(this.router.url);
    console.log(param.queryParams.id)
}

**Comment by MahenAbeyrathna** [comment]
Can use workaround also
1) EventEmitter and a shared service
component1:
   this.router.navigate(['url']).then(()=>
  this.service.emmiter.emmit(data)
)
service :
emmiter : EventEmitter<any> = new EventEmitter();
component2:
in constructor this.service.emmiter.subscribe();
// i have tried this and works fine

2) BehaviorSubject with a shared service

**Comment by harishkrishnan24** [comment]
But reloading the browser will make the data erased right.

**Comment by werpu** [comment]
Well I found a workaround, ui-router already has hit RC stage... So I moved back to that one...

**Comment by davidmartinezros** [comment]
Hi everybody,

Do you try to use an @injectable Data?

You have to define an injectable:

import { Injectable } from '@angular/core';
@Injectable()
export class Data {
    public storage: any;
    public constructor() { }
}

Then, define like a provider in the ngModule:

@NgModule({
    declarations: [AppComponent, ...appComponents],
    bootstrap: [AppComponent],
    imports: [
        NativeScriptModule,
        NativeScriptRouterModule,
        NativeScriptRouterModule.forRoot(appRoutes)
    ],
    providers: [Data]
})

Then define in the origin page like this:

public constructor(private router: Router, private data: Data) {}

public onTap() {
        this.data.storage = {
            "firstname": "Nic",
            "lastname": "Raboy",
            "address": {
                "city": "San Francisco",
                "state": "California"
            }
        }
        this.router.navigate(["page2"]);
}

And in the receive page lke this:

public constructor(private data: Data) {
        console.log(JSON.stringify(this.data.storage));
}

I hope do you help!

Have a nice day!!!

David Martínez Ros
@davidnezan
https://davidmartinezros.com

**Comment by Kevin2iBi** [comment]
The shared emitter have to static

**Comment by iprakashkumarbehera** [comment]
> ```
> this.router.navigate(['/dashboard'], { queryParams:  filter, skipLocationChange: true}); 
> ```
> Worked for me to have matrix params hidden from the URL, only the required links need to have the flag set and others work as normal urls.

where I putting this URL, means inside which file
