### ISSUE TITLE
Router: there is no way to redirectTo passing along query string params to the target route.

### ISSUE THREAD

**Issue by nosachamos** [angular/angular#9921]
**I'm submitting a ...**

```
[ ] bug report
[X] feature request
[ ] support request
```

**Current behavior**
There is no way to configure a route redirectTo another route passing query string params to the target route.

**Expected/desired behavior**
Perhaps something like this?

```
  {
    path: '**',
    redirectTo: '/list?param=true',
    terminal: true
  }
```

This will currently fail with `EXCEPTION: Error: Uncaught (in promise): Error: Cannot match any routes: 'list?param=true'`

**Reproduction of the problem**
This plunker illustrates the issue, see `app.app-routes.rs`

http://plnkr.co/edit/KHEWJhMBlZviHrZVqbDS?p=preview

devtools will log the error. If we just remove `?param=true` from the `redirectTo`, it all works well.

**What is the expected behavior?**
I would expect the catch all route to redirect to /list passing along the `param=true` parameter, as specified in the redirect. If the `redirectTo` cannot accept URLs, then perhaps we could have another parameter to the route config to allow passing in query params?

**Please tell us about your environment:**
- **Angular version:** 2.0.0-rc.4
- **Browser:** all
- **Language:** TypeScript 1.8.10

**Comment by lazarljubenovic** [comment]
It's also very misleading that the [docs](https://angular.io/docs/ts/latest/api/router/index/Routes-type-alias.html) say 

> `redirectTo` is the url fragment which will replace the current matched segment

which implies that it's simply a string, and it's obviously not since it looks like Angular expects a declared route.

IMO there's no need to check if the route exists or not while checking `redirectTo`s. Angular should do the redirection anyway. If there's a matching route, it will work; otherwise it will break anyway (with the exact same error: no matching route). 

It would also be "nice to have" if we didn't have to write the serialized parameters such as `foo;bar=baz` but `['foo', {bar: 'baz'}]` instead, like in `routerLink`.

**Comment by DzmitryShylovich** [comment]
@nosachamos already fixed https://plnkr.co/edit/nKErDzeM8YIM9aQ4agfb?p=preview

can be closed

**Comment by chuckjaz** [comment]
Thanks!

**Comment by asadighi** [comment]
This is not working for me. I am using:
   "@angular/core": "2.4.6",
    "@angular/router": "3.4.6"

**Comment by howna13** [comment]
It only works with absolute routes that contain '/' on the redirect. Could it be possible to implement it so that we could use something like `redirectTo: 'list?param=true'`?

**Comment by redplane** [comment]
Any solution for this ? I'm having the same prob too

**Comment by lazarljubenovic** [comment]
@redplane The comment above yours tells you a workaround.

**Comment by AryanJ-NYC** [comment]
@lazarljubenovic As noted by @howna13:

> It only works with absolute routes that contain '/' on the redirect
