### ISSUE TITLE
HTTP use body options in Get Method

### ISSUE THREAD

**Issue by borgotecnologia** [angular/angular#9927]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
Http using get method and pass body with options does not work.

**Expected/desired behavior**
Please correct it to use body in method get. This is ok to post method but not to get method

**Reproduction of the problem**

This is my scenario

export class BuscaVagasService {
    private _rota = 'http://localhost:49571/api/v0/busca-vagas';

    constructor(private _http: Http) { }

    getVagas(dados: { [chave: string]: string[]; }): Observable<IResultadoBusca<IVaga>> {
        let body = JSON.stringify(dados);
        let headers = new Headers({ 'Content-Type': 'application/json' });
   
        var requestOptions = new RequestOptions({                    
            headers: headers,
            body: dados
        })
    
    let retorno = this._http.get(this._rota,  requestOptions)
            .map((response: Response) => response.json() || {});

        return retorno;
    }

**What is the expected behavior?**

pass body to webApi Method

**What is the motivation / use case for changing the behavior?**

To correct this 

**Please tell us about your environment:**

* **Angular version:** 2.0.0-rc.4
 
* **Browser:** [ Chrome 51.0.2704.103 ]
 
* **Language:** [TypeScript] 

* **Web Api: .NET Core:

        [HttpGet]
        public ResultadoBusca<Vaga> Buscar([FromBody]Dictionary<string, List<string>> dados = null, [FromQuery]bool comFacets = true)
        {
            var parametros = this._buscaVagaService.ParsearArgumentos(dados);

            return this._buscaVagaService.Buscar(parametros, comFacets);
        }

**Comment by sirajc** [comment]
This is as designed. HTTP Get does not support body and hence the Angular's Http does not support it either

**Comment by vicb** [comment]
IIRC the RFC does not prevent GET request from having a body but in practice most servers do not support this.

**Comment by dmayerdesign** [comment]
I think this actually warrants some consideration. As referenced by [Artem](https://stackoverflow.com/users/298552/artem-nakonechny) in [this SO question](https://stackoverflow.com/questions/978061/http-get-with-request-body), the [HTTP GET spec](https://tools.ietf.org/html/rfc7231#section-4.3.1) says this about payloads:
```
   A payload within a GET request message has no defined semantics;
   sending a payload body on a GET request might cause some existing
   implementations to reject the request.
```

URL limits in browsers ([even modern versions of Chrome](https://stackoverflow.com/questions/29458445/what-is-a-safe-maximum-length-a-segment-in-a-url-path-should-be/33733386)) make complex (long) GET requests fundamentally prone to failure. I.e. if I'm an e-commerce site and I want to allow really complex filtering while still fully complying with REST, I'm 100% out of luck.

So, while it's not ideal, I think any front end framework should somehow account for that reality, rather than pretending that browser implementations of HTTP are flawless.

**Comment by trotyl** [comment]
@dmayerdesign XHR doesn't [allow body in GET](https://xhr.spec.whatwg.org/#the-send()-method), it's nothing regarding Angular's choice. There's no way to make GET request with body in browser, it's only possible in non-browser HTTP clients.

**Comment by dmayerdesign** [comment]
@trotyl Ah, I see. That makes sense.

**Comment by odahcam** [comment]
What about `fetch`?

**Comment by trotyl** [comment]
> If either init["body"] exists and is non-null or inputBody is non-null, and request’s method is `GET` or `HEAD`, then throw a TypeError.

@odahcam [Fetch would throw an explicit error](https://fetch.spec.whatwg.org/#ref-for-dfn-throw%E2%91%A1%E2%91%A1) rather than silently ignoring in XHR, which is better for user to understand the restriction. But the restriction itself was still there.
